fix(compiler): move detection of unsafe properties for binding to Ele…
angular/angular pull request #11378
Opened 2016-09-06 13:38 UTC by mlaval

…mentSchemaRegistry

In some non-DOM renderers, binding to a property that starts with `on` is valid.
The check should not be "hardcoded" in the template parser, but could be externalised in the element schema registry.

Not sure about the `assertPropertySafetyForBinding` name though ...

2016-09-06 15:03 UTC, vicb commented on modules/@angular/compiler/src/schema/dom_element_schema_registry.ts
> +    let error: string = null;
`if() {return error;}`

2016-09-06 15:05 UTC, vicb commented on modules/@angular/compiler/src/schema/dom_element_schema_registry.ts
> +    let error: string = null;
we do not 'assert' anything error

2016-09-06 15:06 UTC, vicb commented on modules/@angular/compiler/src/schema/element_schema_registry.ts
> +  abstract assertPropertySafetyForBinding(propName: string): string;
method name

2016-09-06 15:07 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    const error = this._schemaRegistry.assertPropertySafetyForBinding(propName);
I don't think this is the right place to put this code (ie, not ie `_assertNoEventBinding`)

2016-09-06 15:08 UTC, vicb commented
Mark, I think the change is great but the implementation needs some more work.

We definitely need a better name fro `assert...`

2016-09-06 15:41 UTC, mlaval commented
Let's start a naming discussion for `_assertNoEventBinding` and `assertPropertySafetyForBinding` 😛

2016-09-06 16:08 UTC, vicb commented
@mlaval what I mean is that `_assertNoEventBinding` leaks DOM specific implementation details which is why I don't think it'a a good name - and also probably the call sites need to be updated to be more generic

2016-09-16 04:56 UTC, vicb commented
@mlaval what is the status ?

2016-09-23 12:01 UTC, mlaval commented
Rebased, clang did some weird changes with `template_parser_spec.ts` file where I only added 2 tests:

```
              it('should throw error when binding to an invalid property', () => {
                expect(() => parse('<my-component [onEvent]="bar"></my-component>', []))
                    .toThrowError(`Template parse errors:
Binding to property 'onEvent' is disallowed for security reasons ("<my-component [ERROR ->][onEvent]="bar"></my-component>"): TestComp@0:14`);
              });

              it('should throw error when binding to an invalid attribute', () => {
                expect(() => parse('<my-component [attr.onEvent]="bar"></my-component>', []))
                    .toThrowError(`Template parse errors:
Binding to attribute 'onEvent' is disallowed for security reasons ("<my-component [ERROR ->][attr.onEvent]="bar"></my-component>"): TestComp@0:14`);
              });
```

Then the property and attribute validations could be split with 2 separated method in `ElementSchemaRegistry`.

2016-09-23 18:01 UTC, vicb commented on modules/@angular/compiler/src/schema/dom_element_schema_registry.ts
> +  validatePropertyOrAttributeName(propName: string, isAttr: boolean): string {
propName -> name (prop or attribute)

2016-09-23 18:03 UTC, vicb commented on modules/@angular/compiler/src/schema/dom_element_schema_registry.ts
> +  validatePropertyOrAttributeName(propName: string, isAttr: boolean): string {
what about validateProperty & validateAttribute, return `{error: boolean, msg?: string}`

2016-09-23 18:18 UTC, vicb requested changes

2016-09-26 09:55 UTC, mlaval commented on modules/@angular/compiler/src/schema/dom_element_schema_registry.ts
> +  validatePropertyOrAttributeName(propName: string, isAttr: boolean): string {
Done

2016-09-26 13:55 UTC, vicb approved these changes

2016-09-26 13:55 UTC, vicb commented
Super !

2016-09-28 00:10 UTC, merged