fix(upgrade): bind optional properties when upgrading from ng1
angular/angular pull request #11411
Opened 2016-09-07 10:55 UTC by chrisse27

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

Previously, optional properties of a directive/component would be wrongly mapped and thus ignored.

See #10181

**What is the new behavior?**

Optional properties of an ng1 directive/component are correctly bound

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Closes #10181

2016-09-07 11:05 UTC, chrisse27 commented
I signed it!

2016-09-07 11:08 UTC, chrisse27 commented
I signed it!

2016-09-19 20:53 UTC, chrisse27 commented
@pkozlowski-opensource Any chance this could be added to 2.0.1?

2016-09-19 21:23 UTC, vicb commented on modules/@angular/upgrade/src/upgrade_ng1_adapter.ts
> +          switch (typeOptions) {
use ternary ?

2016-09-19 21:23 UTC, vicb commented on modules/@angular/upgrade/test/upgrade_spec.ts
> +      fit('should bind properties, events', async(() => {
remove fit

2016-09-19 21:24 UTC, vicb requested changes

2016-09-19 22:44 UTC, chrisse27 commented on modules/@angular/upgrade/src/upgrade_ng1_adapter.ts
> +          switch (typeOptions) {
Fixed.

2016-09-19 22:45 UTC, chrisse27 commented on modules/@angular/upgrade/test/upgrade_spec.ts
> +      fit('should bind properties, events', async(() => {
Removed this fit and another one.

2016-09-24 20:12 UTC, chrisse27 commented
@vicb Implemented the requested changes.

2016-09-27 17:14 UTC, vicb commented on modules/@angular/upgrade/test/upgrade_spec.ts
> +           var ng1Module = angular.module('ng1', []);
please use const where applicable (let otherwise)

2016-09-27 17:14 UTC, vicb commented on modules/@angular/upgrade/test/upgrade_spec.ts
> +           var ng1 = function() {
`() => {...}`

2016-09-28 14:18 UTC, chrisse27 commented on modules/@angular/upgrade/test/upgrade_spec.ts
> +           var ng1Module = angular.module('ng1', []);
@vicb This means I could basically change all "var" declarations in this test to "const". Since I simply copied my tests from the already existing tests (like apparently everyone else did) it would make sense to apply this rule to all tests in the file. However, I don't want to change to code for which I haven't changed the actual implementation. What's your opinion on this?

2016-09-28 14:32 UTC, chrisse27 commented on modules/@angular/upgrade/test/upgrade_spec.ts
> +           var ng1 = function() {
@vicb Similar question here. Using an old "function" declaration is how it is done throughout the whole file. Wouldn't it make more sense to go over this in a separate issue? (Regardless of this question, I do agree that arrow function should be used.)

2016-09-28 15:33 UTC, vicb commented on modules/@angular/upgrade/test/upgrade_spec.ts
> +           var ng1Module = angular.module('ng1', []);
you can change existing code in a separated "refactor" commit. that would be appreciated.

2016-09-29 12:33 UTC, chrisse27 commented on modules/@angular/upgrade/test/upgrade_spec.ts
> +           var ng1 = function() {
Fixed. Will consider refactor commit for the other test functions.

2016-09-29 12:34 UTC, chrisse27 commented on modules/@angular/upgrade/test/upgrade_spec.ts
> +           var ng1Module = angular.module('ng1', []);
Fixed. Will consider refactor commit for the other test functions.

2016-09-29 12:44 UTC, chrisse27 commented
@vicb Integrated your requests.

2016-09-29 16:26 UTC, vicb approved these changes

2016-09-29 16:45 UTC, merged