chore(build): fail on ddescribe / iit left in tests
angular/angular pull request #11504
Opened 2016-09-10 14:28 UTC by pkozlowski-opensource

Closes #10524

cc: @IgorMinar @vicb

2016-09-10 16:33 UTC, vicb commented
Not sure about the name `ddescribe-iit` - I know I will never remember it (fit-fdescribe, iit-ddescribe, ...). What about something like`check-jasmine` ?

2016-09-10 16:35 UTC, pkozlowski-opensource commented
> Not sure about the name ddescribe-iit - I know I will never remember it (fit-fdescribe, iit-ddescribe, ...). What about something like check-jasmine ?

`check-jasmine` sounds good. Other proposals could be `check-tests`, `lint-tests` or sth. Open to suggestions, will change as soon as we settle on sth.

2016-09-10 16:40 UTC, vicb commented
we have `check-cycle` so 👍 for "check-<your choice>"

does it catch `f*` & no `x*`, can we be explicit here ?

also please document your task, the gulpfile is growing again, could be helpful (bonus points if you comment other existing tasks)

Thanks

2016-09-10 16:42 UTC, pkozlowski-opensource commented
> we have check-cycle so 👍 for "check-<your choice>"

`check-tests` is my choice then.

> does it catch f* & no x*, can we be explicit here ?

It does catch `f*` but not `x*` since we've got a couple of `x*` in our code-base currently. I will make this option explicit.

> also please document your task, the gulpfile is growing again, could be helpful (bonus points if you comment other existing tasks)

OK, will document but skip the bonus points :-)

2016-09-10 16:50 UTC, pkozlowski-opensource commented
@vicb changed name & documented. Shell I stick the "merge" label on this one or do you see anything else to change / discuss / review?

2016-09-10 16:52 UTC, vicb commented
Could you please allow me to contribute on your PR, I want those bonus points - I want to try this new GH feature

2016-09-10 16:54 UTC, pkozlowski-opensource commented
> Could you please allow me to contribute on your PR, I want those bonus points - I want to try this new GH feature

Go ahead :-)

2016-09-10 19:03 UTC, vicb commented
@pkozlowski-opensource PTAL, thanks ! (pls apply "merge" if ok)

2016-09-12 13:53 UTC, IgorMinar commented on npm-shrinkwrap.clean.json
> +    "gulp-ddescribe-iit": {
is there a reason why you didn't use `gulp-acorn-ddescribe-iit` which is more suitable for avoiding false positives for `fit`?

2016-09-12 13:54 UTC, pkozlowski-opensource commented on npm-shrinkwrap.clean.json
> +    "gulp-ddescribe-iit": {
No, no particular reason - didn't know about `gulp-acorn-ddescribe-iit` TBH. Do you want me to switch to `gulp-acorn-ddescribe-iit`?

2016-09-12 13:58 UTC, IgorMinar commented on gulpfile.js
> +function pfScriptPath(path) {
pfScriptPath is not self-descriptive, maybe change to `getPath` or `platformPath`?

2016-09-12 14:00 UTC, IgorMinar commented on gulpfile.js
>      .on('close', (errorCode) => done(errorCode));
the commit message of this commit should be "build(gulp): .." per https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type

"chore" should be the type of last resort :)

2016-09-12 15:29 UTC, vicb commented on gulpfile.js
> +function pfScriptPath(path) {
good point,
Pawel, could you please change that to `platformScriptPath` when fixing other stuffs ?
It would make sense to squash my commit into yours.
Thanks

2016-09-13 07:49 UTC, IgorMinar commented on npm-shrinkwrap.clean.json
> +    "gulp-ddescribe-iit": {
yes please

2016-09-15 17:35 UTC, pkozlowski-opensource commented on gulpfile.js
>      .on('close', (errorCode) => done(errorCode));
changed

2016-09-15 17:35 UTC, pkozlowski-opensource commented on npm-shrinkwrap.clean.json
> +    "gulp-ddescribe-iit": {
@IgorMinar I must have been half-asleep while discussing `gulp-acorn-ddescribe-iit` but since it is acorn-based it doesn't understand TS so not an option for us. Unless I'm missing some obscure config / options / woodo.

2016-09-15 17:36 UTC, pkozlowski-opensource commented on gulpfile.js
> +function pfScriptPath(path) {
done

2016-09-15 17:37 UTC, pkozlowski-opensource commented
@vicb picked up your commit, changed the function name in it and put my cleaned-up commit on top. PTAL.

2016-09-15 17:41 UTC, IgorMinar commented on gulpfile.js
> +      path.join(__dirname, pfScriptPath(`/node_modules/.bin/ts-api-guardian`)),
platformScriptPath

2016-09-15 17:42 UTC, IgorMinar commented on gulpfile.js
> +      path.join(__dirname, pfScriptPath(`/node_modules/.bin/ts-api-guardian`)),
platformScriptPath

2016-09-15 17:42 UTC, IgorMinar commented on npm-shrinkwrap.clean.json
> +    "gulp-ddescribe-iit": {
aha. I didn't realize that. ok. let's stick to the regexp based one

2016-09-15 17:42 UTC, IgorMinar requested changes

2016-09-15 19:40 UTC, pkozlowski-opensource commented on gulpfile.js
> +      path.join(__dirname, pfScriptPath(`/node_modules/.bin/ts-api-guardian`)),
done

2016-09-15 19:41 UTC, pkozlowski-opensource commented on gulpfile.js
> +      path.join(__dirname, pfScriptPath(`/node_modules/.bin/ts-api-guardian`)),
done

2016-09-15 19:42 UTC, pkozlowski-opensource commented
@IgorMinar I think that it is all cleaned up, green and ready to go in now.

2016-09-17 07:22 UTC, IgorMinar approved these changes

2016-09-18 23:02 UTC, alexeagle commented
merged in fa39965

2016-09-18 23:02 UTC, closed without merging