chore(docs): Update the documentation for UpgaredAdapter
angular/angular pull request #11773
Opened 2016-09-20 22:00 UTC by mhevery

2016-09-20 22:16 UTC, vicb commented
type in the commit comment

2016-09-20 22:18 UTC, vicb commented on modules/@angular/examples/upgrade/downgradeNg2Component/ts/downgradeNg2Component_spec.ts
> +  var EC = (<any>protractor).ExpectedConditions;
const

2016-09-20 22:18 UTC, vicb commented on modules/@angular/examples/upgrade/downgradeNg2Component/ts/downgradeNg2Component_spec.ts
> +    var URL = '/upgrade/downgradeNg2Component/ts/';
const

2016-09-20 22:18 UTC, vicb commented on modules/@angular/examples/upgrade/downgradeNg2Component/ts/module.ts
> +var adapter = new UpgradeAdapter(forwardRef(() => MyNg2Module));
var -> const

2016-09-20 22:20 UTC, vicb commented on modules/@angular/upgrade/src/upgrade_adapter.ts
> + * @whatItDoes Use `UpgradeAdapter` to allow AngularJS v1 and Angular v2 to coexist in a single
remove `Use `UpgradeAdapter` to ` ?

2016-09-20 22:22 UTC, vicb commented on modules/@angular/upgrade/src/upgrade_adapter.ts
> +   * Cretase a factory in Angular 2 root injector which will retriev an instance from AngularJS v1
typo `Cretase`, `retriev` seems like your should enable the spell checker :)

2016-09-20 22:23 UTC, vicb requested changes
Also CI is red

2016-09-20 23:20 UTC, mhevery commented on modules/@angular/examples/upgrade/downgradeNg2Component/ts/downgradeNg2Component_spec.ts
> +  var EC = (<any>protractor).ExpectedConditions;
fixed

2016-09-20 23:20 UTC, mhevery commented on modules/@angular/examples/upgrade/downgradeNg2Component/ts/downgradeNg2Component_spec.ts
> +    var URL = '/upgrade/downgradeNg2Component/ts/';
fixed

2016-09-20 23:20 UTC, mhevery commented on modules/@angular/examples/upgrade/downgradeNg2Component/ts/module.ts
> +var adapter = new UpgradeAdapter(forwardRef(() => MyNg2Module));
fixed

2016-09-20 23:21 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_adapter.ts
> +   * Cretase a factory in Angular 2 root injector which will retriev an instance from AngularJS v1
fixed

2016-09-20 23:22 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_adapter.ts
> + * @whatItDoes Use `UpgradeAdapter` to allow AngularJS v1 and Angular v2 to coexist in a single
fixed

2016-09-21 13:58 UTC, Foxandxss commented on modules/@angular/examples/upgrade/overview/ts/module.ts
> +// Crete AngularJS 1 module.
create

2016-09-21 16:55 UTC, mhevery commented on modules/@angular/examples/upgrade/overview/ts/module.ts
> +// Crete AngularJS 1 module.
fixed

2016-09-22 04:58 UTC, mhevery commented
ping @vicb can I have github review approval?

2016-09-22 06:02 UTC, vicb approved these changes

2016-09-22 06:04 UTC, vicb commented on modules/@angular/examples/upgrade/downgradeNg2Component/ts/module.ts
> +var adapter = new UpgradeAdapter(forwardRef(() => MyNg2Module));
could you fix it again ?

2016-09-22 06:04 UTC, vicb commented on modules/@angular/examples/upgrade/downgradeNg2Component/ts/module.ts
> +var module = angular.module('myExample', []);
const

2016-09-22 06:05 UTC, vicb commented on modules/@angular/examples/upgrade/downgradeNg2Provider/ts/module.ts
> +var adapter = new UpgradeAdapter(forwardRef(() => MyModule));
const

2016-09-22 06:05 UTC, vicb commented on modules/@angular/examples/upgrade/downgradeNg2Provider/ts/module.ts
> +var module = angular.module('myExample', []);
const

2016-09-22 06:05 UTC, vicb commented on modules/@angular/examples/upgrade/overview/ts/module.ts
> +var adapter = new UpgradeAdapter(forwardRef(() => MyNg2Module));
const

2016-09-22 06:06 UTC, vicb commented on modules/@angular/examples/upgrade/overview/ts/module.ts
> +var module = angular.module('myExample', []);
const

2016-09-22 06:06 UTC, vicb commented on modules/@angular/examples/upgrade/upgradeNg1Component/ts/module.ts
> +var adapter = new UpgradeAdapter(forwardRef(() => MyNg2Module));
const * 2

2016-09-22 06:06 UTC, vicb commented on modules/@angular/examples/upgrade/upgradeNg1Provider/ts/module.ts
> +var adapter = new UpgradeAdapter(forwardRef(() => MyModule));
same

2016-09-22 06:11 UTC, vicb commented on scripts/ci-lite/offline_compiler_test.sh
> +  @types/{angular@1.5.14,node@6.0.38,jasmine@2.2.33}
q: should this be updated when shrinkwrap is updated ? 

zone, node, jasmine versions seems outdated here ?

2016-09-22 06:12 UTC, vicb requested changes
- more changes requested,
- CI is red, does not seem to be a flake

2016-09-22 06:31 UTC, laco0416 commented on modules/@angular/examples/upgrade/downgradeNg2Component/ts/module.ts
> +var module = angular.module('myExample', []);
`module` is a global variable in node.js context. I feel a little confused about the name...

2016-09-22 21:21 UTC, mhevery commented on modules/@angular/examples/upgrade/downgradeNg2Component/ts/module.ts
> +var adapter = new UpgradeAdapter(forwardRef(() => MyNg2Module));
fixed again. :-)

2016-09-22 21:23 UTC, mhevery commented on modules/@angular/examples/upgrade/downgradeNg2Component/ts/module.ts
> +var module = angular.module('myExample', []);
don't know what happened fixed again

2016-09-22 21:23 UTC, mhevery commented on modules/@angular/examples/upgrade/downgradeNg2Provider/ts/module.ts
> +var adapter = new UpgradeAdapter(forwardRef(() => MyModule));
don't know what happened fixed again

2016-09-22 21:23 UTC, mhevery commented on modules/@angular/examples/upgrade/downgradeNg2Provider/ts/module.ts
> +var module = angular.module('myExample', []);
don't know what happened fixed again

2016-09-22 21:23 UTC, mhevery commented on modules/@angular/examples/upgrade/overview/ts/module.ts
> +var adapter = new UpgradeAdapter(forwardRef(() => MyNg2Module));
don't know what happened fixed again

2016-09-22 21:23 UTC, mhevery commented on modules/@angular/examples/upgrade/overview/ts/module.ts
> +var module = angular.module('myExample', []);
don't know what happened fixed again

2016-09-22 21:23 UTC, mhevery commented on modules/@angular/examples/upgrade/upgradeNg1Component/ts/module.ts
> +var adapter = new UpgradeAdapter(forwardRef(() => MyNg2Module));
don't know what happened fixed again

2016-09-22 21:23 UTC, mhevery commented on modules/@angular/examples/upgrade/upgradeNg1Provider/ts/module.ts
> +var adapter = new UpgradeAdapter(forwardRef(() => MyModule));
don't know what happened fixed again

2016-09-22 21:24 UTC, mhevery commented on scripts/ci-lite/offline_compiler_test.sh
> +  @types/{angular@1.5.14,node@6.0.38,jasmine@2.2.33}
Yes, we should have a better way of doing this, but this is outside of scope of this PR.

2016-09-23 03:25 UTC, mhevery commented
@vicb OK, ci is is green. Can you give LGTM

2016-09-23 18:39 UTC, vicb commented on modules/@angular/examples/upgrade/downgradeNg2Component/ts/module.ts
> +var module = angular.module('myExample', []);
still not here.
@alexeagle is going to have a fix for that.

2016-09-23 18:41 UTC, vicb approved these changes

2016-09-27 23:49 UTC, rkirov commented
needs rebasing

2016-10-17 18:14 UTC, mhevery commented
@IgorMinar ping...

2016-10-18 05:47 UTC, IgorMinar commented
This commit breaks g3 because `@types/angular` is not available. Please take a look at cl/136436863 and prepare a patch.

also please update the commit message type to `docs(upgrade): .. `

2016-12-07 19:21 UTC, mhevery commented
Superseded by the static ngUpgrade

2016-12-07 19:21 UTC, closed without merging