refactor(animations): ensure animation input/outputs are managed within the template parser
angular/angular pull request #11782
Opened 2016-09-21 07:20 UTC by matsko

2016-09-21 14:39 UTC, vicb commented on modules/@angular/compiler/src/animation/animation_compiler.ts
> +      var factoryName = `${factoryNamePrefix}_${entry.name}`;
const * 2

2016-09-21 14:39 UTC, vicb commented on modules/@angular/compiler/src/animation/animation_compiler.ts
> +    statements.push(entry.statesMapStatement);
push(a, b)

2016-09-21 14:40 UTC, vicb commented on modules/@angular/compiler/src/animation/animation_parser.ts
> +    var errors: string[] = [];
use const or let

2016-09-21 14:42 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_ast.ts
> + * [@trigger]="stateExp")
missing back quotes

2016-09-21 14:45 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_ast.ts
> +  get isAnimation() { return this.phase && this.phase.length > 0; }
add return type
return !!this.phase (currently returns '' for empty string)

2016-09-21 14:45 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    var animationTriggerMap: {[key: string]: AnimationEntryAst} = {};
const

2016-09-21 14:47 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    const parts = splitAtPeriod(name, [name, null]);
const [event, phase] = spit...

2016-09-21 14:48 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    let animationEventNameError = validateAnimationEvent(eventName, phase);
const ?

2016-09-21 14:48 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    targetEvents.push(new BoundEventAst(eventName, target, null, ast, sourceSpan));
would it make sense to add the param at the end with a default value of null ?

2016-09-21 14:49 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +  var visitor =
const

2016-09-21 14:50 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    animationTriggerMap: {[key: string]: AnimationEntryAst},
you can use a more meaningful name instead of the generic "key" if applicable ?

2016-09-21 14:50 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    var errors: TemplateParseError[] = [];
const

2016-09-21 14:51 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    var animationInputs = inputs.filter(input => input.isAnimation);
the tmp var is not needed
an early return in the foreach would me more efficient
same below

2016-09-21 14:52 UTC, vicb requested changes
no more "var" please

2016-09-21 15:12 UTC, vicb commented on modules/@angular/core/src/linker/view.ts
> +        if (listener.eventName == animationName && listener.eventPhase == phase) {
=== for str equality

2016-09-21 15:14 UTC, vicb commented on modules/@angular/core/test/animation/animation_integration_spec.ts
> +        var failureMessage = '';
let, const fixture
```ts
try {
 const fixture = TestBed.overrideCompoment(...).createComponent(...);
}
// ...
```

2016-09-21 16:15 UTC, matsko commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    targetEvents.push(new BoundEventAst(eventName, target, null, ast, sourceSpan));
That would mean that everything else after it would also have a default value which would be misleading.

2016-09-21 16:25 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    var animationInputs = inputs.filter(input => input.isAnimation);
I mean return early "in the foreach"

2016-09-21 16:25 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    targetEvents.push(new BoundEventAst(eventName, target, null, ast, sourceSpan));
"at the end" ?

2016-09-21 17:36 UTC, tbosch commented on modules/@angular/compiler/src/animation/animation_compiler.ts
> +      entry => { statements.push(entry.statesMapStatement, entry.fnStatement); });
merge the 2 statements into an array.

2016-09-21 17:37 UTC, tbosch commented on modules/@angular/compiler/src/animation/animation_compiler.ts
> +  compile(factoryNamePrefix: string, parsedAnimations: AnimationEntryAst[]):
Change to just compile one.

2016-09-21 17:38 UTC, tbosch commented on modules/@angular/compiler/src/animation/animation_compiler.ts
> +      entry => { statements.push(entry.statesMapStatement, entry.fnStatement); });
Think about removing this method

2016-09-21 17:40 UTC, tbosch commented on modules/@angular/compiler/src/animation/animation_parser.ts
> +export function parseAnimationEntry(entry: CompileAnimationEntryMetadata): ParsedAnimationTrigger {
We need better names!

2016-09-21 17:44 UTC, tbosch commented on modules/@angular/compiler/src/animation/animation_parser.ts
> +export function parseAnimationEntry(entry: CompileAnimationEntryMetadata): ParsedAnimationTrigger {
Change to `parseAnimationTrigger`

2016-09-21 17:45 UTC, tbosch commented on modules/@angular/compiler/src/animation/animation_parser.ts
>    constructor(public ast: AnimationEntryAst, public errors: AnimationParseError[]) {}
Should be an `AnimationTriggerAst`?

2016-09-21 17:51 UTC, tbosch commented on modules/@angular/compiler/src/animation/animation_parser.ts
> +export function parseAnimationEntry(entry: CompileAnimationEntryMetadata): ParsedAnimationTrigger {
remove export

2016-09-21 17:51 UTC, tbosch commented on modules/@angular/compiler/src/animation/animation_parser.ts
>    constructor(public ast: AnimationEntryAst, public errors: AnimationParseError[]) {}
Make private

2016-09-21 18:06 UTC, tbosch commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +  public componentAnimations =
Remove this and just check the `CompileAnimationMetadata` directly of the nested components.

2016-09-22 06:28 UTC, vicb commented on modules/@angular/compiler/src/animation/animation_compiler.ts
> +    var compiledStatesMapStmt = this._statesMapVar.set(o.literalMap(lookupMap)).toDeclStmt();
consts

2016-09-22 06:30 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_ast.ts
> +  get isAnimation(): boolean { return !!this.phase && this.phase.length > 0; }
remove `&& this.phase.length > 0` - `!!'' === false`

2016-09-22 06:31 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +      var componentTemplate = parent.componentMetadata.template;
const

2016-09-22 06:31 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    var triggerLookup = new Set<string>();
const

2016-09-22 06:32 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +      let name = input.name;
const

2016-09-22 06:32 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    const animationEvents = outputs.filter(output => output.isAnimation);
merge filter into the forEach below ?

2016-09-22 06:32 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +        let found = animationInputs.find(input => input.name == event.name);
const

2016-09-22 06:33 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    let [eventName, phase] = splitAtPeriod(name, [name, null]);
const

2016-09-22 06:33 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    if (phase && phase.length) {
remove `&& phase.length`

2016-09-22 06:34 UTC, vicb commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +    return directives.filter(directive => { return directive.directive.isComponent; });
`=> { return` === `=>`

2016-09-22 06:35 UTC, vicb commented on modules/@angular/compiler/src/view_compiler/view_compiler.ts
> +    var statements: o.Statement[] = [];
const

2016-09-22 06:36 UTC, vicb commented on modules/@angular/compiler/test/animation/animation_compiler_spec.ts
> +    var parser = new AnimationParser();
const

2016-09-22 06:36 UTC, vicb commented on modules/@angular/compiler/test/animation/animation_parser_spec.ts
> +      var parser = new AnimationParser();
const * 2

2016-09-22 06:36 UTC, vicb commented on modules/@angular/core/test/animation/animation_integration_spec.ts
> +        var failureMessage = '';
let

2016-09-22 06:37 UTC, vicb requested changes

2016-09-22 17:53 UTC, tbosch commented on modules/@angular/compiler/src/animation/animation_compiler.ts
> +      AnimationEntryCompileResult[] {
Remove `AnimationEntryCompilerResult` again,
but add the `AnimationCompileResult` as above. I.e. return _one_ instance of that result that contains _all_ statements in one variable and the triggers in the other one.

2016-09-22 17:53 UTC, tbosch commented on modules/@angular/compiler/src/animation/animation_parser.ts
> +  parseWithErrors(component: CompileDirectiveMetadata): ParsedAnimationEntryResult[] {
This should be private.

2016-09-22 17:53 UTC, tbosch commented on modules/@angular/compiler/src/animation/animation_parser.ts
> +export class ParsedAnimationEntryResult {
This should be private

2016-09-22 17:53 UTC, tbosch commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +      componentMetadata: CompileDirectiveMetadata, isTemplateElement: boolean,
This is wrong. Looking at your usages above you are not storing the component that is present on this element on the `ElementContext`, but rather passing the top level component down.

We already have the `ProviderViewContext` which stores the component. I.e. just use `this.providerViewContext.component` inside of the `TemplateParserVisitor` to get the metadata of the component that is currently being compiled.

2016-09-22 17:53 UTC, tbosch commented on modules/@angular/compiler/src/animation/animation_parser.ts
> +  parseWithErrors(component: CompileDirectiveMetadata): ParsedAnimationEntryResult[] {
If you want to keep it public, rename `ParsedAnimationEntryResult` into `AnimationEntryParseResult`, similar to `AnimationEntryCompilerResult` (see above)

2016-09-22 18:19 UTC, tbosch commented on modules/@angular/compiler/src/view_compiler/view_builder.ts
> +    const parsedAnimations = this._animationParser.parse(compMeta);
We still parse again. Could you change this?

2016-09-22 18:20 UTC, tbosch commented on modules/@angular/core/src/linker/view.ts
> +  registerAnimationOutput(
Could you link to the issue in a comment to this PR once you created it?

2016-09-22 18:21 UTC, tbosch requested changes

2016-09-22 20:43 UTC, tbosch commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +      const directiveComponentAsts = this._findComponentDirectives(directiveAsts);
use a forEach over the directiveComponentAsts, as there can be at most 1 (see my previous comment)

2016-09-22 20:44 UTC, tbosch commented on modules/@angular/compiler/src/template_parser/template_parser.ts
> +      const componentTemplate = providerContext.viewContext.component.template;
There is no reason to guard this behind an if (see my previous comment)

2016-09-22 20:45 UTC, tbosch requested changes

2016-09-22 21:27 UTC, tbosch approved these changes

2016-09-22 21:31 UTC, vicb commented on modules/@angular/compiler/src/animation/animation_parser.ts
> +    var errors: AnimationParseError[] = [];
const in this file

2016-09-22 21:32 UTC, vicb commented on modules/@angular/compiler/src/offline_compiler.ts
> +    compiledAnimations.forEach(
could you `compiledAnimations.forEach(entry => targetStatements.push[...entry.statements])` ?

2016-09-22 21:33 UTC, vicb commented on modules/@angular/compiler/src/runtime_compiler.ts
> +    compiledAnimations.forEach(
same as above

2016-09-22 21:38 UTC, vicb commented
Added a last batch of comment.

If phase (string) can be changed for an enum, it would probably be preferable.

2016-09-22 21:51 UTC, vicb approved these changes

2016-09-23 20:37 UTC, merged