bug(forms) range values need to be numbers instead of strings
angular/angular pull request #11792
Opened 2016-09-21 14:00 UTC by AlmogShaul

The default values type of the range input element is strings
Added Range value accessor to convert the strings values to number values

2016-09-21 14:07 UTC, AlmogShaul commented
#11792

2016-09-21 14:09 UTC, AlmogShaul commented
#11325

2016-09-23 14:44 UTC, AlmogShaul commented
Not clear why the test fails...

2016-09-29 15:43 UTC, vicb commented on modules/@angular/forms/src/directives/range_value_accessor.ts
> +export const RANGE_VALUE_ACCESSOR: any = {
type = `Provider`

2016-10-10 06:46 UTC, AlmogShaul commented
@vicb

2016-10-12 16:39 UTC, kara requested changes
Thanks for the PR! Can you make these changes?

2016-10-12 16:39 UTC, kara commented on modules/@angular/forms/src/directives.ts
> -export {NumberValueAccessor} from './directives/number_value_accessor';
Why is this being deleted?  Looks like it wasn't intentional

2016-10-12 16:39 UTC, kara commented on modules/@angular/forms/src/directives.ts
> +import {RangeValueAccessor} from './directives/range_value_accessor';
You should also export this to match other value accessors.

2016-10-12 16:39 UTC, kara commented on modules/@angular/forms/src/directives/range_value_accessor.ts
> +  registerOnTouched(fn: () => void): void { this.onTouched = fn; }
Newline needed after line 50

2016-10-12 16:39 UTC, kara commented on modules/@angular/forms/test/range_value_accessor_spec.ts
> +  describe('range value accessor', () => {
Rather than creating a new file for this, use our existing integration test files. There should be tests for template driven ranges in template_integration_spec (view -> model and model -> view) and reactive ranges in reactive_integration_spec (view -> model and model -> view).

2016-10-12 17:33 UTC, kara commented
Note to caretaker: The commit needs to be changed to "feat" because it's adding to the API surface and changing the default behavior of ranges.

2016-10-13 11:21 UTC, AlmogShaul commented on modules/@angular/forms/src/directives.ts
> -export {NumberValueAccessor} from './directives/number_value_accessor';
right..

2016-10-14 05:13 UTC, AlmogShaul commented
@kara please review

2016-10-14 15:55 UTC, kara requested changes
Looks like we're really close. Just a few small changes and we should be good to go.

2016-10-14 15:55 UTC, kara commented on modules/@angular/forms/test/template_integration_spec.ts
> +@Component({
Looks like you have a copy-paste error here. The radio component's decorator is duplicated here and in lines 1023-1034.   Can you remove one of these?

2016-10-14 15:55 UTC, kara commented on modules/@angular/forms/test/template_integration_spec.ts
> +           expect(typeof(input.nativeElement.value)).toBe('string');
Why not test if the value is '4'?

2016-10-14 15:55 UTC, kara commented on modules/@angular/forms/test/range_value_accessor_spec.ts
> +    it('should set the component property to number instead of string', async(() => {
Can you move this test into the template driven integration spec and remove this file?

2016-10-16 11:11 UTC, AlmogShaul commented on modules/@angular/forms/test/range_value_accessor_spec.ts
> +    it('should set the component property to number instead of string', async(() => {
moved

2016-10-16 11:32 UTC, AlmogShaul commented
@kara fixed all comments

2016-10-17 16:51 UTC, kara approved these changes
LGTM!

2016-10-19 17:12 UTC, merged