chore(compiler): emit ([] as any[]) instead of purely [].
angular/angular pull request #11846
Opened 2016-09-22 23:07 UTC by rkirov

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

In SNC mode `[]` has type of never[], so we cast it to any[] to
typecheck correctly see
https://github.com/Microsoft/TypeScript/issues/10479.

This is temporary workaround, until we fully
migrate the framework to TS 2.0 and strictNullChecks.

2016-09-22 23:20 UTC, vicb commented on modules/@angular/compiler/src/output/ts_emitter.ts
> +    const result = super.visitLiteralArrayExpr(ast, ctx);
could you please add `//TODO: temp workaround` ?

2016-09-22 23:20 UTC, vicb requested changes

2016-09-22 23:20 UTC, vicb commented on modules/@angular/compiler/src/output/ts_emitter.ts
> +    const result = super.visitLiteralArrayExpr(ast, ctx);
and maybe link this PR in the comment ?

2016-09-22 23:32 UTC, rkirov commented on modules/@angular/compiler/src/output/ts_emitter.ts
> +    const result = super.visitLiteralArrayExpr(ast, ctx);
done

2016-09-23 00:13 UTC, vicb approved these changes

2016-09-23 00:13 UTC, vicb commented
needs a gulp format (trailing spaces)

2016-09-23 00:37 UTC, rkirov commented
formatted, PTAL

2016-09-23 01:14 UTC, vicb commented
:+1:

2016-09-23 17:21 UTC, merged