feat(forms): Added emitEvent to AbstractControl methods
angular/angular pull request #11949
Opened 2016-09-27 21:48 UTC by Fank

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Fixes #11286
Fixes #11551

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2016-09-27 22:45 UTC, vicb commented
please separate your changes:
- style(forms): ... -> style changes
- fix(forms): ... -> actual fix

2016-09-28 07:45 UTC, Fank commented
@vicb https://github.com/angular/angular/pull/11948#issuecomment-250092869 thanks for the info, i haven't see the information about logical separating commits, in https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit . But yea you are right, it makes it much easier to read. Fixed it.

2016-09-28 12:21 UTC, Fank commented
/cc @kara

2016-10-10 16:39 UTC, kara commented
@Fank Thanks for the PR! Can you please add tests for the methods that have changed?

2016-10-10 17:45 UTC, Fank commented
@kara as i wrote above in "Other information", there is current no specs for those cases.
How do should i test it?
And should i added test for `onlySelf` too?

2016-10-10 17:54 UTC, kara commented
@Fank I'm not sure how that's relevant. Please add tests for the code you changed. Feel free to add tests for onlySelf as well.

2016-10-10 18:12 UTC, Fank commented
@kara sry for the 1. question, it was miss written i mean:
How do the test should looks like? Because i don't how to test it, like https://github.com/angular/angular/blob/master/modules/%40angular/forms/test/form_control_spec.ts#L338 for every method?

2016-10-11 20:33 UTC, Fank commented
@kara DONE, i'll do the `onlySelf` in a seperate PR. Added tests for the `emitEvent` change.
Found a test in the FormControl, which i used for every test.

2016-10-12 16:28 UTC, kara requested changes
Thanks for doing the tests!  The FormArray and FormGroup tests need some updates, then we should be good to go.

2016-10-12 16:28 UTC, kara commented on modules/@angular/forms/test/form_array_spec.ts
> +             c.setValue('newValue', {emitEvent: false});
The array spec should be testing the FormArray's `setValue` method, so instead call:

```ts
a.setValue(['one', 'two'], {emitEvent: false});
```

2016-10-12 16:28 UTC, kara commented on modules/@angular/forms/test/form_array_spec.ts
> +             c.patchValue('newValue', {emitEvent: false});
Similarly, this should call `a.patchValue`

2016-10-12 16:28 UTC, kara commented on modules/@angular/forms/test/form_array_spec.ts
> +             c.reset({}, {emitEvent: false});
`a.reset` here (with an array as the first arg)

2016-10-12 16:28 UTC, kara commented on modules/@angular/forms/test/form_control_spec.ts
> +             c.reset({}, {emitEvent: false});
I'd reset the value to `null` here (first arg), as you're not really testing the value

2016-10-12 16:28 UTC, kara commented on modules/@angular/forms/test/form_group_spec.ts
> +             c.setValue('newValue', {emitEvent: false});
As this is the FormGroup spec, you'll want to test the FormGroups' setValue method.  

```ts
g.setValue({'one': 'one', 'two': 'two'}, {emitEvent: false});
```

2016-10-12 16:28 UTC, kara commented on modules/@angular/forms/test/form_group_spec.ts
> +             c.patchValue('newValue', {emitEvent: false});
`g.patchValue`

2016-10-12 16:28 UTC, kara commented on modules/@angular/forms/test/form_group_spec.ts
> +             c.reset({}, {emitEvent: false});
`g.reset`

2016-10-14 20:16 UTC, Fank commented
@kara done

2016-10-17 16:48 UTC, kara approved these changes
LGTM! Thanks again for the PR.

2016-10-19 16:54 UTC, merged