fix(BrowserAdapter): correctly removes styles on IE
angular/angular pull request #11953
Opened 2016-09-28 01:02 UTC by vicb

fixes #7916

2016-09-28 01:20 UTC, vicb commented
From [jQuery docs](http://api.jquery.com/css/#css2):

```
Setting the value of a style property to an empty string — e.g. $( "#mydiv" ).css( "color", "" ) — removes that property from an element if it has already been directly applied, whether in the HTML style attribute, through jQuery's .css() method, or through direct DOM manipulation of the style property. As a consequence, the element's style for that property will be restored to whatever value was applied. So, this method can be used to cancel any style modification you have previously performed. It does not, however, remove a style that has been applied with a CSS rule in a stylesheet or <style> element. Warning: one notable exception is that, for IE 8 and below, removing a shorthand property such as border or background will remove that style entirely from the element, regardless of what is set in a stylesheet or <style> element
```

2016-09-30 16:51 UTC, chuckjaz commented
Please resolve merge conflict.

2016-09-30 16:54 UTC, pkozlowski-opensource commented
@vicb is there a way of adding a unit test for this? I'm worried that this issue might come back in this or another form if we don't have a test. And since we are running all tests in IE this could be verified automatically.

2016-09-30 16:56 UTC, vicb commented
@pkozlowski-opensource please create an issue an I'll look at it (assign it to me). thanks.

@chuckjaz rebased

2016-09-30 17:49 UTC, chuckjaz requested changes

2016-09-30 17:52 UTC, vicb commented on modules/@angular/platform-browser/src/browser/browser_adapter.ts
> +  hasProperty(element: Node, name: string): boolean { return name in element; }
no part of the public API

2016-09-30 18:00 UTC, chuckjaz approved these changes

2016-09-30 18:18 UTC, merged