refactor(routerLinkActive): optimised routerLinkActive active check code
angular/angular pull request #11968
Opened 2016-09-28 22:57 UTC by connorwyatt

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] **N/A** Tests for the changes have been added (for bug fixes / features)
- [ ] **N/A** Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

The RouterLinkActive directive currently iterates over the whole list of links, even is it has found an active link. This iteration is not necessary in this case. Furthermore it checks both RouterLinks and RouterLinkWithHrefs even if there is a RouterLink that is active.

**What is the new behavior?**

The iteration now breaks on finding an active RouterLink/RouterLinkWithHref saving iteration, and also doesn't check both arrays if the first array has an active link.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Modify routerLinkActive to optimise performance by removing unnecessary iteration. By replacing Array.reduce with Array.some, the loop will break when it finds an active link. Useful if used on the parent of a large group of routerLinks. Furthermore, if a RouterLink is active it will not check the RouterLinkWithHrefs.

Notes: 

- I have not added tests for this case as it is not relied upon behaviour and is purely an implementation detail.
- I have replaced a usage of Array#reduce with Array#some and have made sure that browser support for the method is high as it is part of the core-js ES6 polyfill.

2016-09-28 23:08 UTC, vicb commented
You can make hasActiveLinks check both lists

2016-09-28 23:15 UTC, connorwyatt commented
As in, merge the two lists to pass into the method? Kind of like:

```
this.hasActiveLinks([...this.links, ...this.linkWithHrefs])
```

2016-09-28 23:38 UTC, vicb commented
I was thinking `this.hasActiveLinks()`.

Note: I'm not sure if the perf gain is really valuable here, it's more about having the correct semantic

2016-09-29 06:01 UTC, connorwyatt commented
That's fair, I can close the PR if you think it's not that valuable

2016-09-29 15:20 UTC, vicb commented
> That's fair, I can close the PR if you think it's not that valuable

I really like the improved semantic, please update the PR, we'll merge it (only saying that we should not expect significant perf gain from it)

2016-09-29 15:29 UTC, connorwyatt commented
Ah I see, I agree that it's not going to be a significant improvement performance wise, but that's cool, I'll update it this evening.

Thanks

2016-09-29 17:41 UTC, connorwyatt commented
I have had to duplicate the logic in the hasActiveLinks method as to my knowledge there is no way to merge QueryLists, if however there is a way I can update it to merge them and act on a single array

2016-09-29 20:59 UTC, vicb requested changes

2016-09-29 20:59 UTC, vicb commented on modules/@angular/router/src/directives/router_link_active.ts
> +    let hasActiveLink = this.links.some(
`return this.link.some(isRouterLinkActive) || this.linksWithHrefs(isRouterLinkActive);`

``` ts
function(isRouterLinkActive: ...|...): boolean {
  return ...;
}
```

2016-09-29 21:20 UTC, connorwyatt commented on modules/@angular/router/src/directives/router_link_active.ts
> +    let hasActiveLink = this.links.some(
As a private method on the class or inside the hasActiveLink method? From your code it looks like it would be inside the hasActiveLink method. Want to check that I understand correctly

2016-09-29 21:21 UTC, connorwyatt commented on modules/@angular/router/src/directives/router_link_active.ts
> +    let hasActiveLink = this.links.some(
E.g.

```
  private hasActiveLink(): boolean {
    function isLinkActive(link: RouterLink|RouterLinkWithHref) {
      this.router.isActive(link.urlTree, this.routerLinkActiveOptions.exact)
    }

    return this.links.some(isLinkActive) || this.linksWithHrefs.some(isLinkActive);
  }
```

2016-09-29 21:22 UTC, connorwyatt commented on modules/@angular/router/src/directives/router_link_active.ts
> +    let hasActiveLink = this.links.some(
Or:

```
  private isLinkActive(): boolean {
    return this.router.isActive(link.urlTree, this.routerLinkActiveOptions.exact);
  }

  private hasActiveLink(): boolean {
    return this.links.some(this.isLinkActive) || this.linksWithHrefs.some(this.isLinkActive);
  }
```

2016-09-29 22:17 UTC, vicb commented on modules/@angular/router/src/directives/router_link_active.ts
> +    let hasActiveLink = this.links.some(
2 is better (you don't have to re-create the fn each time.

2016-09-30 08:28 UTC, connorwyatt commented on modules/@angular/router/src/directives/router_link_active.ts
> +    let hasActiveLink = this.links.some(
I have had to return a function from the isLinkActive method due to the fact that the this context in the isLinkActive method changes due to the `some` method

2016-09-30 16:10 UTC, vicb approved these changes

2016-09-30 16:42 UTC, merged