fix(UrlSearchParams): change a behavior when a param value is null or undefined
angular/angular pull request #11990
Opened 2016-09-29 21:26 UTC by alexbyk

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
- [x] Bugfix

**What is the current behavior?**
Right now `search.set('foo', undefined)` leads to `?foo=undefined`. You can check such cases before `set` invocation, but that would be error prone. So right now almost every `reset form` action potentially leads to errors.

**What is the new behavior?**
`search.set('foo', undefined)` and  `search.set('foo', null)` WILL NOT store values in the map and the result query string WILL NOT contain `foo`. If there is already a param with the same key, it will be deleted. Also `search.has('foo')` will be falsy, because this and only this way stringification is fully reversible.

BUT: `.set('foo', '')` -> `foo=`

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

**Other information**:

Right now FF and Chrome has experimental builtin object URLSearchParams, which behaves differently (the behavior is the same as BEFORE this commit):

    var s = new URLSearchParams('q=qq'); s.set('foo', undefined); console.log(s.toString());
    // q=qq&foo=undefined

But I consider this is a bug. Because if it's not, the `toString` isn't a reversible process.

2016-09-29 22:23 UTC, vicb requested changes
see inline comments

2016-09-29 22:23 UTC, vicb commented on modules/@angular/http/src/url_search_params.ts
> +    if (typeof val == 'undefined' || val === null) {
`if (typeof val !== 'string')` ?

2016-09-29 22:23 UTC, vicb commented on modules/@angular/http/test/url_search_params_spec.ts
> +      var searchParams = new URLSearchParams('empty=');
nits:
const
remove extra blank line before the it()

2016-09-29 22:23 UTC, vicb commented on modules/@angular/http/test/url_search_params_spec.ts
> +      expect(searchParams.has('empty')).toBe(true);
toEqual

2016-09-29 22:23 UTC, vicb commented on modules/@angular/http/test/url_search_params_spec.ts
> +      searchParams.set('null', 'OLDVAL');
the 2 lines above (and the comment) are useless

2016-09-29 22:23 UTC, vicb commented on modules/@angular/http/test/url_search_params_spec.ts
> +    it('should deal with undefined and null', () => {
'should remove the parameter when set to undefined or null

2016-09-29 22:23 UTC, vicb commented on modules/@angular/http/src/url_search_params.ts
> +    if (typeof val == 'undefined' || val === null) {
unless we can call with an int today, that would be a breaking change.

`(val === void 0 || val === null)` is probably safer.

2016-09-29 23:34 UTC, alexbyk commented on modules/@angular/http/test/url_search_params_spec.ts
> +      searchParams.set('null', 'OLDVAL');
These 2 test aren't useless. They will protect us from a regression refactoring if someone will be going to change the flow and drop out `this.delete(param)` in favour of `list.length = 0`.

2016-09-29 23:36 UTC, vicb commented on modules/@angular/http/test/url_search_params_spec.ts
> +      searchParams.set('null', 'OLDVAL');
then please test that the values are set before removing them

2016-09-29 23:52 UTC, alexbyk commented on modules/@angular/http/test/url_search_params_spec.ts
> +      expect(searchParams.has('empty')).toBe(true);
Didn't get this. The next line is `expect(params.get('empty')).toEqual('');`.

2016-09-30 00:11 UTC, vicb commented on modules/@angular/http/test/url_search_params_spec.ts
> +      expect(params.has('empty')).toBe(true);
I still don't get why this first part is in the test ?

2016-09-30 00:11 UTC, vicb requested changes
Please also fix `append`

2016-09-30 00:24 UTC, alexbyk commented on modules/@angular/http/test/url_search_params_spec.ts
> +      expect(params.has('empty')).toBe(true);
an empty string is a one of the 3 special cases here ('', null, undefined). All of them in my opinion should be tested, because someone may think that `'?foo=&bar=1'` -> `get('foo') === null`

2016-09-30 00:25 UTC, vicb commented on modules/@angular/http/test/url_search_params_spec.ts
> +      expect(params.has('empty')).toBe(true);
makes sense

2016-09-30 00:26 UTC, vicb commented on modules/@angular/http/test/url_search_params_spec.ts
> +      expect(params.has('empty')).toBe(true);
but please make a distinct test with a clear description

2016-09-30 00:30 UTC, alexbyk commented on modules/@angular/http/test/url_search_params_spec.ts
> +      expect(params.has('empty')).toBe(true);
ok. right now i think it shouldn't be here

2016-09-30 00:56 UTC, alexbyk commented on modules/@angular/http/test/url_search_params_spec.ts
> +      expect(params.has('empty')).toBe(true);
Right now i think an "empty string test" isn't related to this bug. So didn't include it to the final version

2016-09-30 11:01 UTC, alexbyk commented
append is fixed in the latest version too

2016-09-30 16:21 UTC, vicb approved these changes

2016-09-30 16:57 UTC, merged