Remove some StringMapWrapper facades
angular/angular pull request #12022
Opened 2016-10-01 00:41 UTC by alexeagle

Automated using https://github.com/alexeagle/tslint/commit/12012b07a2f7c341424aee5b40660ca0839bc347
with a few manual fixes after.

2016-10-01 01:26 UTC, vicb requested changes

2016-10-01 01:26 UTC, vicb commented on modules/@angular/benchpress/src/metric/multi_metric.ts
> +    Object.keys(map).forEach(prop => {
remove "{", convert to one liner

2016-10-01 01:26 UTC, vicb commented on modules/@angular/benchpress/src/reporter/util.ts
> +  Object.keys(obj).forEach(prop => {
unused value, one liner

2016-10-01 01:26 UTC, vicb commented on modules/@angular/benchpress/src/sample_description.ts
> +      Object.keys(description).forEach(prop => {
again

2016-10-01 01:26 UTC, vicb commented on modules/@angular/benchpress/test/metric/perflog_metric_spec.ts
> +      Object.keys(stringMap).forEach(key => {
...

2016-10-01 03:37 UTC, alexeagle commented on modules/@angular/benchpress/src/metric/multi_metric.ts
> +    Object.keys(map).forEach(prop => {
The advantage of the curly braces is they either contain a return statement or are void. typescript-eng has discussed the style here and I think we've decided that arrow function with a bare expression on the RHS means you use the return value from it. Otherwise it is unclear if you are using an expression to mean void, or are using its return value.

2016-10-01 03:51 UTC, alexeagle commented on modules/@angular/benchpress/src/reporter/util.ts
> +  Object.keys(obj).forEach(prop => {
I fixed these cases where I created a value variable that was not used, PTAL

2016-10-01 05:18 UTC, vicb commented on modules/@angular/benchpress/src/metric/multi_metric.ts
> +    Object.keys(map).forEach(prop => {
Ok for braces but still should be 1 liner,  wdyt

2016-10-01 05:32 UTC, vicb reviewed
Most 2 liners should be converted to 1 line IMO
Did not repeat the same comments towards the end

2016-10-01 05:32 UTC, vicb commented on modules/@angular/benchpress/src/reporter/util.ts
> +  Object.keys(obj).forEach(prop => {
Push(...Object.keys)

2016-10-01 05:32 UTC, vicb commented on modules/@angular/benchpress/src/sample_description.ts
> +      Object.keys(description).forEach(prop => {
1 line

2016-10-01 05:32 UTC, vicb commented on modules/@angular/benchpress/test/metric/perflog_metric_spec.ts
> +      Object.keys(stringMap).forEach(key => {
Unused

2016-10-01 05:32 UTC, vicb commented on modules/@angular/benchpress/test/metric/perflog_metric_spec.ts
> +      Object.keys(stringMap).forEach(key => {
Res.push(...Object.keys)

2016-10-01 05:32 UTC, vicb commented on modules/@angular/compiler/src/animation/animation_parser.ts
> +        const value: any = (entry as{[key: string]: string | number})[prop];
Move in if

2016-10-01 05:32 UTC, vicb commented on modules/@angular/compiler/src/animation/animation_parser.ts
> +      const value = styles[prop];
Move in if

2016-10-03 17:23 UTC, alexeagle commented on modules/@angular/benchpress/src/metric/multi_metric.ts
> +    Object.keys(map).forEach(prop => {
It's up to clang-format to decide how many lines... do you just mean formatting, or do you mean to change syntax?

2016-10-03 17:51 UTC, vicb commented on modules/@angular/benchpress/src/metric/multi_metric.ts
> +    Object.keys(map).forEach(prop => {
Change the syntax, do not introduce the const

2016-10-03 17:52 UTC, alexeagle commented
I did a bunch more manual cleanup, mostly removing the introduced `const value` if it was only used once.

2016-10-03 22:44 UTC, vicb approved these changes

2016-10-03 22:45 UTC, vicb commented
@alexeagle could you please rebase

2016-10-03 23:02 UTC, alexeagle commented
rebased

On Mon, Oct 3, 2016 at 3:45 PM Victor Berchet <notifications@github.com>
wrote:

> @alexeagle <https://github.com/alexeagle> could you please rebase
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/12022#issuecomment-251248927>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAC5I1T7dOEv854HPO_TozfI5-Do6ET8ks5qwYV9gaJpZM4KLn6b>
> .
>

2016-10-03 23:46 UTC, merged