refactor(facade): inline StringWrapper
angular/angular pull request #12051
Opened 2016-10-03 21:49 UTC by alexeagle

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2016-10-04 01:10 UTC, vicb requested changes
the splice was useful to make sure JS doesn't pass extra args compared to Dart. 
Now extra params could just be ignored and we do not need to splice any more

2016-10-04 01:10 UTC, vicb commented on modules/@angular/compiler/src/output/abstract_emitter.ts
> +    match.splice(-2, 2);
remove this line

2016-10-04 01:10 UTC, vicb commented on modules/@angular/compiler/src/style_url_resolver.ts
> +    m.splice(-2, 2);
you can remove 
```
+    // Remove offset & string from the result array
 +    m.splice(-2, 2);
```
always

2016-10-04 01:10 UTC, vicb commented on modules/@angular/compiler/src/url_resolver.ts
> +    var pos = 0;
let here and below

2016-10-04 01:10 UTC, vicb commented on modules/@angular/compiler/src/url_resolver.ts
> +  if (s && s.length) {
`if (s)` is equivalent in JS

2016-10-04 01:10 UTC, vicb commented on modules/@angular/compiler/src/url_resolver.ts
> +  if (s && s.length) {
`if (s)` is equivalent in JS

2016-10-04 01:10 UTC, vicb commented on modules/@angular/compiler/src/url_resolver.ts
> +    for (var i = 0; i < s.length; i++) {
`indexOf`

2016-10-04 01:10 UTC, vicb commented on modules/@angular/compiler/src/url_resolver.ts
> +    for (var i = s.length - 1; i >= 0; i--) {
`lastIndexOf`

2016-10-04 01:10 UTC, vicb commented on modules/@angular/compiler/src/util.ts
> +    // Remove offset & string from the result array
remove

2016-10-04 01:10 UTC, vicb commented on modules/@angular/compiler/src/view_compiler/view_builder.ts
> +function compare(a: string, b: string): number {
You should be able to drop this fn - seems like the default behavior of sort

2016-10-04 01:10 UTC, vicb commented on modules/@angular/platform-browser/src/dom/util.ts
> +    m.splice(-2, 2);
remove, single line

2016-10-04 01:10 UTC, vicb commented on modules/@angular/platform-browser/src/dom/util.ts
> +    m.splice(-2, 2);
remove, single line

2016-10-04 01:10 UTC, vicb commented on modules/@angular/platform-browser/src/dom/util.ts
> +    m.splice(-2, 2);
maybe `(m0: string, m1: string)` otherwise the type checker might complain ? `s/m[1]/m1/`

2016-10-04 01:10 UTC, vicb commented on modules/@angular/platform-browser/testing/browser_util.ts
> +  css = css.replace(/\s+/g, ' ');
chain calls ?

2016-10-04 01:10 UTC, vicb commented on modules/@angular/platform-browser/testing/browser_util.ts
> +    match.splice(-2, 2);
remove here and below

2016-10-04 17:07 UTC, alexeagle commented
did most of it, PTAL

2016-10-04 17:09 UTC, vicb commented on modules/@angular/compiler/src/url_resolver.ts
> +    for (let i = s.length - 1; i >= 0; i--) {
lastIndexOf

2016-10-04 17:14 UTC, alexeagle commented on modules/@angular/compiler/test/expression_parser/unparser.ts
> +      this._expression += `"${ast.value.replace( Unparser._quoteRegExp,  '\"')}"`;
known issue in clang-format I believe

2016-10-04 17:15 UTC, alexeagle commented on modules/@angular/compiler/src/url_resolver.ts
> +    for (let i = 0; i < s.length; i++) {
no, too risky. I don't think it's the same.
stripLeft should be
`"//hello".substring("//hello".lastIndexOf("/") + 1)  => "hello"`
but then
`"//he/llo".substring("//he/llo".lastIndexOf("/") + 1)`
does the wrong thing.

I don't want to make such changes, this should be pure no-risk refactoring

2016-10-04 17:20 UTC, vicb commented on modules/@angular/compiler/src/url_resolver.ts
> +    for (let i = s.length - 1; i >= 0; i--) {
what about `s.replace(/^\/*/, '')` ?

2016-10-04 17:20 UTC, vicb commented on modules/@angular/compiler/src/url_resolver.ts
> +    for (let i = s.length - 1; i >= 0; i--) {
well `s.replace(/\/+$/, '')` here

2016-10-04 17:22 UTC, vicb commented on modules/@angular/platform-browser/testing/browser_util.ts
> +  css = css.replace(/\s+/g, ' ');
````
return css.replace(...)
    .replace(...)
// ...
    .replace(...);
```

2016-10-04 18:01 UTC, alexeagle commented on modules/@angular/compiler/src/url_resolver.ts
> +    for (let i = s.length - 1; i >= 0; i--) {
what if charVal requires escaping to be in a regex? I do not want to change this now.

2016-10-04 22:59 UTC, alexeagle commented on modules/@angular/compiler/src/url_resolver.ts
> +    for (let i = s.length - 1; i >= 0; i--) {
removed these functions altogether.

2016-10-05 01:03 UTC, vicb commented
lgtm, squash & merge

2016-10-05 01:03 UTC, vicb approved these changes

2016-10-05 16:58 UTC, alexeagle commented
Rebased

2016-10-06 22:10 UTC, merged