fix(dom_renderer): check if style is empty during styles flattering
angular/angular pull request #12203
Opened 2016-10-10 18:47 UTC by DzmitryShylovich

Fixes https://github.com/angular/angular/issues/11408

Some notes:
When ViewEncapsulation is set to None/Native [_flattenStyles method](https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/src/dom/dom_renderer.ts#L281) is called with `styles` array of length 1 but contains value undefined. So it might be a bug somewhere before.

2016-10-10 20:24 UTC, chuckjaz requested changes

2016-10-10 20:24 UTC, chuckjaz commented on modules/@angular/platform-browser/src/dom/dom_renderer.ts
> +function _flattenStyles(
Introducing types then using a cast is no better than leaving the type as `any`. I believe this can be written without casts as:

```TypeScript
interface Styles extends Array<Style> {}
type Style = undefined | string | Styles;

function _flattenStyles(compId: string, styles: Styles, target: string[]): string[] {
  for (var i = 0; i < styles.length; i++) {
    var style = styles[i];
    if (Array.isArray(style)) {
      _flattenStyles(compId, style, target);
    } else if (style) {
      target.push(style.replace(COMPONENT_REGEX, compId));
    }
  }
  return target;
}
```

Note that this kind of recursive type is awkward to write in TypeScript but it avoids the casts.

I would say we either introduce the correct typing or leave the type as `Array<any|any[]>`.

2016-10-10 21:08 UTC, DzmitryShylovich commented on modules/@angular/platform-browser/src/dom/dom_renderer.ts
> +function _flattenStyles(
I think we don't really need strong typing here so I will return `Array<any|any[]>`.

2016-10-10 22:08 UTC, DzmitryShylovich commented on modules/@angular/platform-browser/src/dom/dom_renderer.ts
> +function _flattenStyles(
done

2016-10-10 22:57 UTC, chuckjaz commented
Reviewing this more closely the code does what you intended but it doesn't resolve the original problem. This avoids raising an exception but the code generated would be incorrect.

For now I am going to close this PR and leave the original bug open. I have marked the bug in such a way that it has a high priority.

2016-10-10 22:57 UTC, closed without merging

2016-10-11 03:40 UTC, jordic commented
@chuckjaz I'm actually experien'cing this bug in one of mine applications. 
Where should I dig more? It's still not clear for me if the main problem comes from the complier (and really is an angular 'bug) or it comes from the build process (that injects undefined styles). 
Im using angular cli with ng serve --aot.

2016-10-11 17:07 UTC, chuckjaz commented
There is definitely an issue here and we are going to look into it quickly. However, this fix just masks the problem instead of fixing it. The issue is not that we are not checking for `undefined` it is that there is an `undefined` in the array at all.

The issue appears to be triggered when generating code into the source directory.

First, it is highly recommended to change the location of the generated code to another location and not generate it next to the source. We made an unfortunate choice in the default here and we will be working though the deprecation, breaking change policy to be able to change this. Second, if they do match it still work. The issue appears to be in our resolving the, in the bug's example, `app.css` getting confused by the generated `app.css.ts` file. Third, if we do run into a resolution problem we should generate an error, not insert an `undefined` into the array.

2016-11-17 12:53 UTC, elvirdolic commented
Is there any workaround for this? We are using angular-cli to run the aot build and it's not working because of this issue.

2016-11-17 12:57 UTC, DzmitryShylovich commented
> Is there any workaround for this?

nope

2016-12-01 21:59 UTC, Krisa commented
I was hopeful that the little hack-fix of @DzmitryShylovich to check whether `style` is defined would work somehow (while hiding something wrong), but in my case the CSS of the page looks totally broken when doing so, so it feels like we are all a bit stuck here waiting on a fix which after 2 months has not yet happened.

@chuckjaz - maybe this issue's fallen off the radar of the NG team, but we all would highly appreciate that this gets prioritised as it's a critical issue for many projects out there, wanting to go to prod. 

Thank you for having a quick look again!