Ngupgrade aot
angular/angular pull request #12239
Opened 2016-10-12 13:44 UTC by petebacondarwin

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2016-10-12 14:08 UTC, petebacondarwin commented on karma-js.conf.js
> +      'node_modules/angular/angular.js',
TODO: remember to revert this change

2016-10-12 18:41 UTC, mhevery requested changes
Awesome start and great progress!

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/index.ts
> +export * from './src/upgrade_module';
Don't export all. Instead list which items specifically you want to export.  Otherwise `$injectorFactory` and friends will be part of public API.

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_module.ts
> +    { provide: '$rootScope', useFactory: $rootScopeFactory, deps: ['$injector']},
@chuckjaz Notice how we have to explicitly list `$rootScopeFactory` and `$compileFactory` in future we will have many more. It would be nice to just have one function which does it all, but we get an Error:

```
Metadata collected contains an error that will be reported at runtime:
   Function calls are not supported.
   Consider replacing the function or lambda with a reference to an exported function
```

I thought we supported this, but apparently not. Could you work with @petebacondarwin and help him resolve it?

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_module.ts
> +    { provide: '$compile', useFactory: $compileFactory, deps: ['$injector']}
Should we re-export all of the `$*` items?

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_module.ts
> + * between Angular 1 and Angular 2+
We will have to update this doc with an example. We now require that full API documentation will be included at the time of submission of the PR.

//cc @IgorMinar

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_module.ts
> +   * angular1Module.factory('someService', ng2ProviderFactory(SomeService))
turn these into running examples. See: https://github.com/angular/angular/pull/11773 for how the docs should look / work.

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_module.ts
> +    return ['ng2Injector', (i: Injector) => i.get(token)];
Maybe extract the strings into constants?

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_module.ts
> +  static ng1ServiceProvider({provide, ng1Token}: {provide: any, ng1Token: any}): FactoryProvider {
We should think about the naming.  `ng2ProviderFactory` vs `ng1ServiceProvider` seem to different. Think about `downgrade`/`upgrade` word `ng1`/`ng1` name. 

Ideas:
-  `downgradeNg2Injectable` vs `upgradeNg1Injectable`
- `wrapAsNg1Factory` vs `wrapAsNg2Provider`
- `createNg1FactoryFromNg2` vs `createNg2ProviderFromNg1`

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_module.ts
> +    function directiveFactory(
this seems like cut and paste from ngUpgrade. Could we somehow refactor and keep the codebase shared? or do you think it is not worth it? (just asking)

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_module.ts
> +      const NG2_INJECTOR = 'ng2.Injector';
make sure we have consistent naming. either `ng2.foo` or `ng2Foo`

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_module.ts
> +  ngDoBootstrap() {}
add comment as to which this method is here.

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_module.ts
> +    if (config) {
why is this necessary? Wouldn't `angular.bootstrap` take care of it?

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +    it('should instantiate ng2 in ng1 template and project content', async(() => {
@juliemr we are having a hard time making the `async` work here. We are getting timeout. Could you work with @petebacondarwin on figuring out why it is failing to stabilize?

2016-10-12 18:41 UTC, mhevery commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +        ref.instance.bootstrapNg1(element, [ng1Module.name]);
Why do it here, rather than in the `Ng2Module` constructor?

2016-10-12 19:03 UTC, robwormald commented on modules/@angular/upgrade/src/upgrade_module.ts
> +  static ng1ServiceProvider({provide, ng1Token}: {provide: any, ng1Token: any}): FactoryProvider {
ideally not Ng2 anything, as it'll be Ng3 anything in a few months...

2016-10-12 19:06 UTC, petebacondarwin commented on modules/@angular/upgrade/index.ts
> +export * from './src/upgrade_module';
Right, OK. I'll fix up.

2016-10-12 19:08 UTC, petebacondarwin commented on modules/@angular/upgrade/src/upgrade_module.ts
> + * between Angular 1 and Angular 2+
These docs were mostly placeholders to help with my understanding.
We can add more as the work stabilizes

2016-10-12 19:10 UTC, petebacondarwin commented on modules/@angular/upgrade/src/upgrade_module.ts
> +    { provide: '$compile', useFactory: $compileFactory, deps: ['$injector']}
There are lots of them...
Perhaps we could just provide a recipe in the docs for people to add their own to their subclass of UpgradeModule?

2016-10-12 19:10 UTC, petebacondarwin commented on modules/@angular/upgrade/src/upgrade_module.ts
> +   * angular1Module.factory('someService', ng2ProviderFactory(SomeService))
will do as things stabilize

2016-10-12 19:11 UTC, petebacondarwin commented on modules/@angular/upgrade/src/upgrade_module.ts
> +    return ['ng2Injector', (i: Injector) => i.get(token)];
there are actually constants that I should be using in `./constants.ts`.

2016-10-12 19:12 UTC, petebacondarwin commented on modules/@angular/upgrade/src/upgrade_module.ts
> +  static ng1ServiceProvider({provide, ng1Token}: {provide: any, ng1Token: any}): FactoryProvider {
That is the tricky bit eh @robwormald  :-P

* `createDowngradeProvider` vs `createUpgradeFactory`

?

2016-10-12 19:13 UTC, petebacondarwin commented on modules/@angular/upgrade/src/upgrade_module.ts
> +    function directiveFactory(
Funnily enough I was just doing some tidying up on this.
I would like to get tests passing before doing refactoring with regards to the rest of the ngUpgrade codebase.

2016-10-12 19:15 UTC, petebacondarwin commented on modules/@angular/upgrade/src/upgrade_module.ts
> +  ngDoBootstrap() {}
strangely I did have a comment here but it seems to have failed to make it into the commit that was pushed.

2016-10-12 19:21 UTC, petebacondarwin commented on modules/@angular/upgrade/src/upgrade_module.ts
> +  static ng1ServiceProvider({provide, ng1Token}: {provide: any, ng1Token: any}): FactoryProvider {
Perhaps we drop ng2 throughout and have:

* `wrapAsProvider` vs `wrapAsNg1Factory`

And then have things like

* `ref.instance.injector` : Angular 2 injector
vs
* `ref.instance.ng1Injector` : Angular 1 injector

2016-10-12 19:22 UTC, petebacondarwin commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +    it('should instantiate ng2 in ng1 template and project content', async(() => {
I think this may have resolved itself...

2016-10-12 19:23 UTC, petebacondarwin commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +        ref.instance.bootstrapNg1(element, [ng1Module.name]);
Moving the call to `bootstrapNg1` outside the constructor makes the custom UpgradeModule more reusable. It doesn't tie it into always bootstrapping on a specific element.

2016-10-12 20:58 UTC, chuckjaz commented on modules/@angular/upgrade/src/upgrade_module.ts
> +    { provide: '$rootScope', useFactory: $rootScopeFactory, deps: ['$injector']},
@mhevery Sure.

@petebacondarwin Can I see the function that you are trying to use? It might be easy to transform.

2016-10-12 22:03 UTC, petebacondarwin commented on modules/@angular/upgrade/src/aot/ng1_service_provider.ts
> +}
shouldn't this helper fall foul of the same problems with not being allowed to use a non-exported named function as a factory?
cc @mhevery & @chuckjaz

2016-10-13 03:42 UTC, mhevery commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +        ref.instance.bootstrapNg1(element, [ng1Module.name]);
I see, good point.

2016-10-13 03:44 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_module.ts
> +      const NG2_INJECTOR = 'ng2.Injector';
I see the point with `ng2`. So maybe we should just do `$injector` and `ng.injector`? as the two ways. Renaming it would be a breaking change, even thought it is not part of the public API so it is unlikely that anyone would be using it. But sounds like the ngUpgradeAoT should use `ng.Injector`

2016-10-13 03:45 UTC, mhevery commented on modules/@angular/upgrade/src/upgrade_module.ts
> +  static ng1ServiceProvider({provide, ng1Token}: {provide: any, ng1Token: any}): FactoryProvider {
+1 for not having `ng2` anything.

I vote for - `ng1` prefix for `ng1` but no prefix for `ng2` (just as @petebacondarwin) suggested.

2016-10-13 11:27 UTC, petebacondarwin commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +      it('should properly run cleanup when ng1 directive is destroyed', async(() => {
@gkalpak  can you take a look and see if this test makes sense. The previous commented out test that this replaces is very different and in I think doesn't even work properly.

2016-10-13 11:51 UTC, gkalpak commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +      it('should properly run cleanup when ng1 directive is destroyed', async(() => {
The test makes sense. I think the previosu test tried to do the same thing.
One thing I noticed is that the previosu test calls `ref.dispose()` at the end. Is it necessary? What was the purpose?

2016-10-13 20:52 UTC, petebacondarwin commented
@gkalpak please do the honors for the googlebot

2016-10-13 21:01 UTC, gkalpak commented on modules/@angular/upgrade/src/angular_js.ts
> +export type IAngularBootstrapConfig = IInjectable;
But it is not the same. `IAngularBootstrapConfig` is the configuration that can be passed to `angular.bootstrap` and can contain `stringDi: true/false` for example. (It can also contain `debugInfoEnabled`, but that is undocumented and used internally.) Essentially, it is just an object with specific properties.

2016-10-13 21:03 UTC, gkalpak commented on modules/@angular/upgrade/src/angular_js.ts
> +export type IAngularBootstrapConfig = IInjectable;
So, it should probably be changed to:

```ts
export interface IAngularBootstrapConfig {
  strictDi?: boolean;
}
```

2016-10-14 06:09 UTC, petebacondarwin commented
Oops

On 13 Oct 2016 22:04, "Georgios Kalpakas" <notifications@github.com> wrote:

> *@gkalpak* commented on this pull request.
> ------------------------------
>
> In modules/@angular/upgrade/src/angular_js.ts
> <https://github.com/angular/angular/pull/12239>:
>
> > @@ -51,7 +51,7 @@ export interface IRootScopeService {
>    [key: string]: any;
>  }
>  export interface IScope extends IRootScopeService {};
> -export interface IAngularBootstrapConfig {}
> +export type IAngularBootstrapConfig = IInjectable;
>
> So, it should probably be changed to:
>
> export interface IAngularBootstrapConfig {
>   strictDi?: boolean;
> }
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/12239>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAA9J-80qsnq9YruZZabnZy49Ezy2RyVks5qzpzTgaJpZM4KUxSw>
> .
>

2016-10-14 07:28 UTC, gkalpak commented
@googlebot, I confirm that I'm okay with my commits being contributed to Google :smiley:

2016-10-14 12:00 UTC, gkalpak commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +          // (since there is no other injector in this system)
Still not convinced 😛

2016-10-14 12:01 UTC, petebacondarwin commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +          // (since there is no other injector in this system)
Trouble is until we have `upgradeComponent` working we can't do better than this test

2016-10-14 14:20 UTC, mhevery requested changes
Excellent progress sir!

2016-10-14 14:20 UTC, mhevery commented on modules/@angular/upgrade/src/aot/ng1_module.ts
> +    Ng1Adapter,
Why is this broken up to a separate class? Why no just part of the module? I am on the fence, and wanted to understand your reasoning.

2016-10-14 14:20 UTC, mhevery commented on modules/@angular/upgrade/src/aot/ng1_module.ts
> +/** @internal */
I don't think `@internal` provides any value. Remove? (same as below)

2016-10-14 14:20 UTC, mhevery commented on modules/@angular/upgrade/src/constants.ts
> +export const UPGRADE_MODULE_INJECTOR = 'ng2.Injector';
`export const COMPONENT_INJECTOR = 'componentInjector';`

2016-10-14 14:20 UTC, mhevery commented on modules/@angular/upgrade/src/constants.ts
>  export const NG2_COMPONENT_FACTORY_REF_MAP = 'ng2.ComponentFactoryRefMap';
not neede

2016-10-14 14:20 UTC, mhevery commented on modules/@angular/upgrade/src/constants.ts
>  export const NG2_ZONE = 'ng2.NgZone';
not needed

2016-10-14 14:20 UTC, mhevery commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +          ngDoBootstrap() {}
nice thing about extending was that one did not have to write `ngDoBootstrap` method.

2016-10-14 14:20 UTC, mhevery commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +          .directive('ng2', downgradeComponent({ selector: 'ng2', type: Ng2Component }));
Why do we have to pass in the `selector`? it should not be needed.

Also can we rename `type` to `component`?

2016-10-14 14:20 UTC, mhevery commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +          const adapter = ref.injector.get(Ng1Adapter) as Ng1Adapter;
By having `Ng1Adapter` as a separate class, there is more things to import. Still on the fence about that.

2016-10-14 15:01 UTC, petebacondarwin commented on modules/@angular/upgrade/src/angular_js.ts
> +export type Ng1Token = string;
I was looking forward to if/when we might allow non-string tokens in ng1

2016-10-14 15:06 UTC, petebacondarwin commented on modules/@angular/upgrade/src/angular_js.ts
> +export interface IAnnotatedFunction extends Function {
Well I didn't know about https://www.npmjs.com/package/@types/angular.
@gkalpak and I probably wasted a bit of time over the last few days tweaking this file.

2016-10-14 15:07 UTC, petebacondarwin commented on modules/@angular/upgrade/src/aot/downgrade_component.ts
> +      require: '?^' + UPGRADE_MODULE_INJECTOR,
OK, do we still leave the UPGRADE_MODULE_INJECTOR constant for when we are accessing the top level injector? E.g. `$injector.get(UPGRADE_MODULE_INJECTOR)`

2016-10-14 15:13 UTC, petebacondarwin commented on modules/@angular/upgrade/src/constants.ts
> +export const UPGRADE_MODULE_INJECTOR = 'ng2.Injector';
So similar question to earlier. This constant could refer to the injector on a component or to the "root" injector on the module. Should we have two constants?

2016-10-14 15:14 UTC, petebacondarwin commented on modules/@angular/upgrade/src/constants.ts
>  export const NG2_COMPONENT_FACTORY_REF_MAP = 'ng2.ComponentFactoryRefMap';
Except that it is still used by the JIT `UpgradeAdapter`

2016-10-14 15:20 UTC, petebacondarwin commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +          .directive('ng2', downgradeComponent({ selector: 'ng2', type: Ng2Component }));
You are right. I was being lazy because I was reusing `DowngradeNg2ComponentAdapter` from the JIT version which accepts a `ComponentInfo` type, which requires the selector. 

In fact the only use of `info.selector` in that class is when reporting an error.

We should refactor this and remove the selector.

2016-10-14 15:22 UTC, petebacondarwin commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +          const adapter = ref.injector.get(Ng1Adapter) as Ng1Adapter;
Let's mull it over during the weekend. Happy to revert if it still feels wrong.

2016-10-14 16:06 UTC, mhevery commented on modules/@angular/upgrade/test/upgrade_aot_spec.ts
> +          imports: [BrowserModule]
`Ng1Module` => `UpgradeModule`

2016-10-14 18:32 UTC, mhevery commented on modules/@angular/upgrade/src/aot/downgrade_component.ts
> +      require: '?^' + UPGRADE_MODULE_INJECTOR,
correct

2016-10-14 18:44 UTC, mhevery commented on modules/@angular/upgrade/src/constants.ts
> +export const UPGRADE_MODULE_INJECTOR = 'ng2.Injector';
Good question. My initial reaction is that those two things are separate, but then again it is not like you can inject module injector in Ng2. 

But the difference is that `element.data()` will never return a module injector only component injector. So I think having two different names may be easier for the reader of the code.

Fine either way.

2016-10-16 09:45 UTC, petebacondarwin commented on modules/@angular/upgrade/src/angular_js.ts
> +export interface IAnnotatedFunction extends Function {
I think we would need to do some work with that repository as I am not entirely happy with all of the hand crafted types there.

2016-10-18 00:27 UTC, alexeagle commented on modules/@angular/upgrade/src/metadata.ts
>  export interface ComponentInfo {
not part of your change - but the import of DirectiveResolver above causes @angular/upgrade to depend on @angular/compiler so my AoT example is still getting the compiler at runtime, which makes the app big. Maybe a Closure Compiler issue but it's easier to trim the dependency.
@mhevery this suggests the aot version of upgrade should be a separate package so we can avoid the reflection dependencies?

2016-10-19 20:58 UTC, alexeagle approved these changes

2016-10-19 20:58 UTC, alexeagle commented on karma-js.conf.js
> +      'node_modules/angular/angular.js',
can revert it?

2016-10-19 20:58 UTC, alexeagle commented on tools/public_api_guard/upgrade/index.d.ts
> +    $injector: angular.IInjectorService;
this only works if you have this local angular1 typings to make it match.
Real users with angular 1 and angular 2 typings will find a structural mismatch here. Needs to be `any`

2016-10-19 21:49 UTC, petebacondarwin commented on karma-js.conf.js
> +      'node_modules/angular/angular.js',
@mhevery said it can stay un-minified

2016-10-19 21:49 UTC, petebacondarwin commented on modules/@angular/upgrade/src/constants.ts
> +export const UPGRADE_MODULE_INJECTOR = 'ng2.Injector';
I think we are not using these constants in the new AoT code.

2016-10-19 21:49 UTC, petebacondarwin commented on tools/public_api_guard/upgrade/index.d.ts
> +    $injector: angular.IInjectorService;
We agreed to wait for it to break stuff

2016-10-19 21:49 UTC, petebacondarwin commented on modules/@angular/upgrade/test/aot/test_helpers.ts
> +}
@mhevery - we should consider adding this helper to the public API

2016-10-19 22:29 UTC, closed without merging