refactor(core): strong type keyvalue differs
angular/angular pull request #12570
Opened 2016-10-27 18:30 UTC by alfaproject

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?**
KeyValueDiffers and friends are not strongly typed

**What is the new behavior?**
KeyValueDiffers and friends are strongly typed

**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

2016-10-27 18:44 UTC, vicb commented on modules/@angular/common/src/directives/ng_class.ts
> +  private _keyValueDiffer: KeyValueDiffer<string[]|Set<string>|{[klass: string]: boolean}>;
revert the boolean stuff (JS accepts any if ('true'))

2016-10-27 19:10 UTC, alfaproject commented on modules/@angular/common/src/directives/ng_class.ts
> +  private _keyValueDiffer: KeyValueDiffer<string[]|Set<string>|{[klass: string]: boolean}>;
I've just reverted it

2016-10-27 21:01 UTC, vicb commented
API break -> can not merge before 3.0

2016-10-27 21:16 UTC, alfaproject commented
Pity ):

2016-10-27 21:29 UTC, vicb commented
BTW thanks for all your PRs... 
Trying to find some spare time to go over them.

2016-12-09 20:09 UTC, mhevery requested changes

2016-12-09 20:09 UTC, mhevery commented on tools/public_api_guard/common/index.d.ts
> +    constructor(_iterableDiffers: IterableDiffers, _keyValueDiffers: KeyValueDiffers<string[] | Set<string> | {
KeyValue differ can not have `string[]` or `Set<string>` as its type. This does not seem right.

2016-12-09 20:36 UTC, mhevery reviewed
I will take over this PR

2016-12-09 20:36 UTC, mhevery commented on modules/@angular/core/src/change_detection/differs/keyvalue_differs.ts
> +export class KeyValueDiffers<T> {
`KeyValueDiffers` can not be parameterized as it holds differs for many different parameters.

2016-12-11 17:33 UTC, mhevery commented
Closing this in favor of https://github.com/angular/angular/pull/13382

2016-12-11 17:34 UTC, closed without merging