refactor(ngUpgrade): Small cleanup with Testability API and resumeBootstrap
angular/angular pull request #12926
Opened 2016-11-16 20:33 UTC by sjelin

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

See "Other Information"

**What is the new behavior?**

See "Other Information"

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

**Other information**:

* With non-static ngUpgrade apps, callbacks to `whenStable` were being invoked with the wrong
  context
* With non-static ngUpgrade apps, `resumeBootstrap` was being run outside the NgZone
* Remove redundent `whenStableContext` variable
* Updated static example to get type mocks for ng1

Neither of the first two problems were actually causing bugs (as far as I know), but they *might*
have caused problems in the future.  The example had to be updated to make the tests pass (no idea
why this change mattered to that example).

Inspired by https://github.com/angular/angular/pull/12910, but for non-static apps.

2016-11-16 20:51 UTC, petebacondarwin commented on modules/@angular/examples/upgrade/static/ts/module.ts
> +import * as angular from '@angular/upgrade/src/angular_js';
We shouldn't need this to build this app.

2016-11-16 20:54 UTC, petebacondarwin requested changes
It all looks good except for the addition of the import of `angular_js` into `module.ts`.

2016-11-16 20:55 UTC, petebacondarwin commented on modules/@angular/examples/upgrade/static/ts/module.ts
> +import * as angular from '@angular/upgrade/src/angular_js';
In fact it causes Travis to fail.

2016-11-16 21:01 UTC, sjelin commented on modules/@angular/examples/upgrade/static/ts/module.ts
> +import * as angular from '@angular/upgrade/src/angular_js';
I was running into errors when I didn't have it there but I'll try again

2016-11-16 21:44 UTC, chuckjaz commented on modules/@angular/examples/upgrade/static/ts/module.ts
> +const ng1AppModule = (window as any).angular.module('ng1AppModule', []);
I just merged a fix for this. Please verify that this error is now no longer in the editor as well as not being reported when running `./test.sh`.

2016-11-16 21:46 UTC, sjelin commented on modules/@angular/examples/upgrade/static/ts/module.ts
> +const ng1AppModule = (window as any).angular.module('ng1AppModule', []);
During the build process of the tests:

```
sjelin@sjelin-linux:~/angular$ ./test.sh browserNoRouter
Watching: modules/tsconfig.json in /usr/local/google/home/sjelin/angular
=====> node_modules/.bin/tsc --emitDecoratorMetadata --project modules/tsconfig.json --watch
=====> node node_modules/karma/bin/karma start --no-auto-watch --port=9876 karma-js.conf.js
modules/@angular/examples/upgrade/static/ts/module.ts(118,22): error TS2304: Cannot find name 'angular'.
1:44:56 PM - Compilation complete. Watching for file changes.
------------------------------------------------------------------------------
Errors found.... (response not triggered)
```

I use vim so my editor doesn't provide errors

2016-11-16 22:21 UTC, sjelin commented
Should be good now @petebacondarwin.  Thanks to @chuckjaz for the fix

2016-11-16 22:36 UTC, petebacondarwin approved these changes

2016-11-18 19:31 UTC, sjelin commented
Hey, this isn't merging for some reason and I don't have the rights to merge it myself

2016-11-18 21:37 UTC, petebacondarwin commented
It is up to the caretaker to merge it. Try pinging them on Slack

2016-11-18 21:49 UTC, chuckjaz commented
@petebacondarwin This is missing an LGTM so it didn't show up in my query of PRs ready to merge.

2016-11-18 21:56 UTC, petebacondarwin commented
OK. Added.

2016-11-18 22:30 UTC, merged