fix(forms): getRawValue correctly work with nested form groups
angular/angular pull request #12964
Opened 2016-11-18 11:44 UTC by DzmitryShylovich

Fixes https://github.com/angular/angular/issues/12963

2016-11-18 11:51 UTC, DzmitryShylovich commented
Travis failed because of a Saucelabs flake.

2016-11-18 15:23 UTC, beakdoctor commented
It's also `getRawValue` in the `FormArray` class (updated plunkr in #12964 shows the same problem with a `FormArray` and a nested `FormGroup` and `FormArray` within it)

2017-02-10 03:36 UTC, kara requested changes

2017-02-10 03:36 UTC, kara commented on modules/@angular/forms/src/model.ts
> +  }
I think these methods need more discussion, so the bug fix should be separate. Can you move into a separate PR?

2017-02-10 03:36 UTC, kara commented on modules/@angular/forms/test/form_array_spec.ts
> +    });
Nit: can you move this section down below `value`? Kind of weird having it first.

2017-02-10 08:22 UTC, DzmitryShylovich commented on modules/@angular/forms/test/form_array_spec.ts
> +    });
done

2017-02-10 08:22 UTC, DzmitryShylovich commented on modules/@angular/forms/src/model.ts
> +  }
reverted

2017-02-10 08:49 UTC, DzmitryShylovich commented
@kara ready for review

2017-02-10 18:05 UTC, kara approved these changes
LGTM

2017-02-10 21:21 UTC, closed without merging