Update CHANGELOG.md
angular/angular pull request #13000
Opened 2016-11-21 04:39 UTC by nevster

**Please check if the PR fulfills these requirements**
- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ x] Other... Please describe: doc change
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

docs(changelog): giving information about where to find future changelog info

2016-11-22 19:21 UTC, chuckjaz requested changes

2016-11-22 19:21 UTC, chuckjaz commented on modules/@angular/router/CHANGELOG.md
> +* For any subsequent release of angular there will be a corresponding router release with a version number 1 higher
Please rewrite to be clear that this is only for the 3.0.0 version. This might not be true for 4.0.0

2016-11-22 19:22 UTC, chuckjaz commented
Please update the commit message to be "doc(router): update CHANGELOG.md"

2016-12-09 23:14 UTC, vicb commented
Closing as next version will be v4. We can add a note then ?

2016-12-09 23:14 UTC, closed without merging