fix(forms): provide a method to compare options
angular/angular pull request #13349
Opened 2016-12-09 21:11 UTC by DzmitryShylovich

Closes https://github.com/angular/angular/issues/13268 and https://github.com/angular/angular/issues/13295

2016-12-09 21:52 UTC, vicb commented on modules/@angular/forms/src/directives/select_control_value_accessor.ts
> +  @Input() ngEquals: (o1: any, o2: any) => boolean = looseIdentical;
`compareOptions/ equalOptions` ? 
compare implies 1, 0, -1 return... probably overkill.

2016-12-09 21:52 UTC, vicb commented
LGTM, @kara could you please review ?

2016-12-09 21:54 UTC, DzmitryShylovich commented on modules/@angular/forms/src/directives/select_control_value_accessor.ts
> +  @Input() ngEquals: (o1: any, o2: any) => boolean = looseIdentical;
> compare implies 1, 0, -1 return

yeah, this is why I  hose `equals`

2016-12-09 22:05 UTC, DzmitryShylovich commented on modules/@angular/forms/src/directives/select_control_value_accessor.ts
> +  @Input() ngEquals: (o1: any, o2: any) => boolean = looseIdentical;
in material 1 they use `ng-model-options="{trackBy: '$value.id'}"`
> ngModelController provides a track by option that allows us to specify a different expression which will be used for the equality operator. As such, we can update our html to make use of this by specifying the ng-model-options="{trackBy: '$value.id'}" on the md-select element.

2016-12-09 22:10 UTC, DzmitryShylovich commented on modules/@angular/forms/src/directives/select_control_value_accessor.ts
> +  @Input() ngEquals: (o1: any, o2: any) => boolean = looseIdentical;
so maybe instead of function just prop name?
```
<select [(ngModel)]='myItem' [trackBy]="'id'">
           <option *ngFor='let item of myItems' [ngValue]='item'>{{item.name}}</option>
      </select>
```

2016-12-12 04:08 UTC, kara requested changes
Can you also add a test for this?

2016-12-12 04:08 UTC, kara commented on modules/@angular/forms/src/directives/select_control_value_accessor.ts
> +  @Input() equalOptions: (o1: any, o2: any) => boolean = looseIdentical;
Hmm, I like the idea of an optional equality method, but I don't think this name is very intuitive. Perhaps `compareWith`?  Discussed with @StephenFluin and we think that might fit the use case better.

```html
<select [compareWith]="compareFn" [(ngModel)]="someProp">
   ...
</select>
```

2017-01-13 11:46 UTC, DzmitryShylovich commented
@kara ready for review

2017-01-30 17:48 UTC, kara approved these changes
LGTM

2017-01-31 17:37 UTC, mhevery approved these changes

2017-01-31 23:11 UTC, closed without merging

2017-10-02 13:00 UTC, JosephBL commented
Is a release date known for this feature? It would help a lot :)

2017-10-02 17:44 UTC, another-guy commented
@JosephBL this feature has been released for many months. (since `4.0.0-beta.6` : https://github.com/angular/angular/blob/master/CHANGELOG.md#400-beta6-2017-02-03  "forms: provide a method to compare options (#13349) (f89d004), closes #13268" )

2017-10-06 03:37 UTC, gdbaskara commented
So my problem is, the value of ngModel was right, but if I compared the value, in the first looping is error because the value of Ngmodel is null. but the next until the end of looping, the ngModel value is there. Any solution?

>`<select class="form-control"  [compareWith]="byId"  [(ngModel)] = "selected.status">
	<option *ngFor = "let status of status_igd" [ngValue]="status">{{ status.nama }}</option>
</select>`
byId(p1, p2) {
   return p1.id == p2.id;
}

2017-10-09 08:16 UTC, JosephBL commented
Thanks a lot, I somehow missed it :$

2018-03-10 02:26 UTC, rawatfeb commented
Thanks a lot

2018-04-06 07:40 UTC, chinthu commented
Faced an issue with this compare,  if the select is inside the form /formgroup, with name , compare is not working

2018-07-24 15:13 UTC, marticrespi commented
As @chinthu said, if the select is in a form the compare function doesn't work properly.