feat(platform-browser): allow to register event listeners in the capt…
angular/angular pull request #13371
Opened 2016-12-10 19:55 UTC by DzmitryShylovich

Closes https://github.com/angular/angular/issues/11200

2016-12-10 22:32 UTC, vicb commented
@mhevery @IgorMinar WDYT ?

Should we through when trying to bind to an Output (no phase there)

2016-12-14 17:18 UTC, mhevery requested changes
- This needs to have documentation update otherwise this feature is not discoverable.
- I am wondering if we should have a holistic view on the events and see if we can come up with a way to handle captur, prevent default, bubbling, etc in a uniform way.

2016-12-14 17:18 UTC, mhevery commented on modules/@angular/platform-browser/src/dom/events/key_events.ts
> +    return {domEventName, fullKey, useCapture};
Revert this section. `result['domEventName'] = domEventName` is not same as `{domEventName}`. this is because the former tells closure to prevent minification of `domEventName` and later does not.

2016-12-14 19:51 UTC, DzmitryShylovich commented
@mhevery 
> Revert this section.

done

> This needs to have documentation update otherwise this feature is not discoverable.

should I file an issue on angular.io?

2016-12-14 21:47 UTC, mhevery approved these changes

2016-12-14 21:49 UTC, mhevery commented
@DzmitryShylovich I think we need to think about this further as I am concerned with just adding special characters to the syntax. 
/cc @tbosch @IgorMinar

2017-02-06 16:44 UTC, tzachov commented
Any update on this one?

2017-02-08 04:35 UTC, mhevery commented
@tzachov   sorry we are busy with 4.0

2017-04-05 13:44 UTC, tzachov commented
Now that v4 is out, can you tell us if and when this feature will be merged?

Thanks.

2017-06-06 16:34 UTC, tbosch commented
We are closing this PR because it is unclear whether this is the right fix and we need to finalize the design before committing to a solution.

2017-06-06 16:34 UTC, closed without merging

2017-06-23 11:25 UTC, e-cloud commented
@tbosch closing the issue without another tracking issue is pretty not friendly for users.

2017-06-26 10:36 UTC, tbosch commented
This is a PR, not an issue. The underlying issue is #11200.