perf(animations): always run the animation queue outside of zones
angular/angular pull request #13440
Opened 2016-12-13 19:47 UTC by matsko

Related #12732

2016-12-13 22:48 UTC, mhevery requested changes

2016-12-13 22:48 UTC, mhevery commented on modules/@angular/compiler/src/view_compiler/constants.ts
> +  static animationQueue = o.variable('animationQueue');
revert

2016-12-13 22:48 UTC, mhevery commented on modules/@angular/core/src/animation/animation_queue.ts
> +        Promise.resolve(null).then(() => this._triggerAnimations());
put the `entries.length` check outside the `runOutsideAngular`

2016-12-13 22:48 UTC, mhevery commented on modules/@angular/core/src/animation/animation_queue.ts
> +      if (!player.hasStarted()) {
Discussed to `shift()` players from queue.

2016-12-13 22:48 UTC, mhevery commented on modules/@angular/core/src/animation/animation_transition.ts
> +declare let Zone: any;
revert

2016-12-13 22:48 UTC, mhevery commented on modules/@angular/core/src/animation/animation_transition.ts
> +    const fn = <any>Zone.current.wrap((change: any) => callback(event));
remove `<any>` add source argument.

2016-12-13 22:48 UTC, mhevery commented on modules/@angular/core/src/animation/animation_transition.ts
> +    const fn = <any>Zone.current.wrap((change: any) => callback(event));
remove `<any>` add source argument.

2016-12-13 23:49 UTC, mhevery approved these changes

2016-12-14 01:04 UTC, vicb commented
status ?

2016-12-14 19:45 UTC, vicb commented
Have the last 2 commits been reviewed ?

2016-12-14 19:47 UTC, matsko commented
@vicb Misko has reviewed both commits.

2016-12-14 21:05 UTC, closed without merging