feat(forms): introduce AsyncValidator interface
angular/angular pull request #13483
Opened 2016-12-14 22:25 UTC by DzmitryShylovich

Closes https://github.com/angular/angular/issues/13398

2016-12-19 08:23 UTC, xban1x commented on modules/@angular/forms/src/directives/ng_control.ts
> +  _rawAsyncValidators: Array<AsyncValidator|ValidatorFn> = [];
Should we not use here AsyncValidatorFn ?

2016-12-19 08:24 UTC, xban1x commented on modules/@angular/forms/src/directives/shared.ts
> +  dir._rawAsyncValidators.forEach((validator: AsyncValidator | ValidatorFn) => {
AsyncValidatorFn instead of ValidatorFn?

2016-12-19 08:25 UTC, xban1x commented
I added 2 comments if you can check @DzmitryShylovich

2016-12-19 17:52 UTC, DzmitryShylovich commented on modules/@angular/forms/src/directives/ng_control.ts
> +  _rawAsyncValidators: Array<AsyncValidator|ValidatorFn> = [];
In theory, yes, it should be `AsyncValidatorFn`, but in practice there's no type checking here so it can be anything. In some directives it's just `any`. :(

2016-12-19 18:56 UTC, xban1x commented on modules/@angular/forms/src/directives/ng_control.ts
> +  _rawAsyncValidators: Array<AsyncValidator|ValidatorFn> = [];
Well, in any case it should be changed if for nothing else for future to avoid possible issues.

2017-01-28 04:55 UTC, mhevery commented
@kara  can you approve this?

2017-02-10 19:28 UTC, kara requested changes
Minor tweaks. Could you also rebase?

2017-02-10 19:28 UTC, kara commented on modules/@angular/forms/src/directives/normalize_validator.ts
>    if ((<Validator>validator).validate) {
`(<AsyncValidator>validator).validate` ?

2017-02-10 19:28 UTC, kara commented on modules/@angular/forms/src/directives/validators.ts
> +import {Observable} from '../facade/async';
Import from `rxjs/Observable` instead? We should try to avoid facades if possible.

2017-02-10 19:28 UTC, kara commented on modules/@angular/forms/src/directives/validators.ts
> +  validate(c: AbstractControl): Promise<{[key: string]: any}>|Observable<{[key: string]: any}>;
Nit: whitespace around pipe for readability

```Promise<{[key: string]: any}> | Observable<{[key: string]: any}>```

2017-02-11 10:12 UTC, DzmitryShylovich commented on modules/@angular/forms/src/directives/validators.ts
> +  validate(c: AbstractControl): Promise<{[key: string]: any}>|Observable<{[key: string]: any}>;
clang format doesn't allow a whitespace

2017-02-11 10:14 UTC, DzmitryShylovich commented on modules/@angular/forms/test/validators_spec.ts
> +    > {
this is how clang formats the code ¯\_(ツ)_/¯

2017-02-11 23:35 UTC, DzmitryShylovich commented
@kara fixed what I can

2017-02-13 17:14 UTC, kara commented on modules/@angular/forms/test/validators_spec.ts
> +    > {
Clang!  *shakes fist*

2017-02-13 17:17 UTC, kara commented on modules/@angular/forms/src/directives/normalize_validator.ts
>      return (c: AbstractControl) => (<Validator>validator).validate(c);
This should also be `<AsyncValidator>validator`

2017-02-13 22:44 UTC, DzmitryShylovich commented
@kara fixed

2017-02-13 22:50 UTC, kara approved these changes
LGTM

2017-02-14 04:04 UTC, mhevery approved these changes

2017-02-21 00:26 UTC, merged