docs(http/testing/MockBackend): fix and extend samples
angular/angular pull request #13689
Opened 2016-12-28 14:46 UTC by e-hein

Fix samples for MockBackend and MockBackend.connections that were outdated. Also extend central sample for MockBackend to ease getting started.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe: Sample code in docs fixed
```

**What is the current behavior?** (You can also link to an open issue here)
- sample code crashes because of api changes (e.g. Injector there's no method Injector.resolveAndCreate anymore - moved to ReflectiveInjector)

**What is the new behavior?**
- sample code is runnable again
- refactoring to use some framework helper (fakeAsync) and try to improve readability

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
Thanks for the original sample - helped me a lot testing http connections. Hope the updated sample will help even more people.

2016-12-28 15:00 UTC, e-hein commented
- signed the cla (last week ...)
- test results are identically before and after change (86 failures caused by missing module opaque_token)

2016-12-28 16:20 UTC, e-hein commented
corrected email address - so google should find cla

2016-12-28 19:46 UTC, vicb commented on modules/@angular/http/testing/mock_backend.ts
> + *         .catch(this.handleError);
e => this.handleError(e)

2016-12-28 19:47 UTC, vicb commented on modules/@angular/http/testing/mock_backend.ts
> + *         it('getHeroes() while server is down', fakeAsync(() => {
formatting

2016-12-28 19:49 UTC, vicb commented on modules/@angular/http/testing/mock_backend.ts
> +   *   var connection : MockConnection; //this will be set when a new connection is emitted from the backend.
var -> let

2016-12-28 19:50 UTC, vicb commented
please format your patch (`gulp format`) and reword the commit message: `docs(Http): fix and extend samples for testing/MockBackend`

2016-12-28 22:02 UTC, DzmitryShylovich commented on modules/@angular/http/testing/mock_backend.ts
> + *         .toPromise()
can we also use observables instead of promises?

2016-12-28 22:14 UTC, e-hein commented on modules/@angular/http/testing/mock_backend.ts
> + *         .toPromise()
tried observable and subscribe first. Didn't work. Then I switched to promise according to other samples ... worked - don't understand why. I'd preferred the observable, too.

2016-12-28 23:02 UTC, e-hein commented on modules/@angular/http/testing/mock_backend.ts
> + *         .catch(this.handleError);
changed

2016-12-28 23:03 UTC, e-hein commented on modules/@angular/http/testing/mock_backend.ts
> + *         it('getHeroes() while server is down', fakeAsync(() => {
gulp format added the spaces ... changed some other lines, now it looks better

2016-12-28 23:03 UTC, e-hein commented on modules/@angular/http/testing/mock_backend.ts
> +   *   var connection : MockConnection; //this will be set when a new connection is emitted from the backend.
changed

2016-12-28 23:34 UTC, vicb requested changes
Pls squash your commits.

2016-12-29 07:34 UTC, vicb commented
Please sign the CLA with your email address `...@e-hein.de` or amend the commit to match the address you used for signing the CLA.

2016-12-29 08:21 UTC, e-hein commented
Double checked email of CLA

2016-12-29 16:41 UTC, vicb approved these changes

2016-12-29 16:41 UTC, vicb commented
Thanks @e-hein

2016-12-29 17:39 UTC, merged