fix(forms): Tests on undefined.
angular/angular pull request #13720
Opened 2016-12-30 12:32 UTC by Mathou54

Fix:
* The minlength test on undefined test null.
* Add undefined tests to required and maxlength

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
```

**What is the new behavior?**
Fix and add tests.

**Does this PR introduce a breaking change?** (check one with "x")
```
[x] No
```

2016-12-30 13:17 UTC, laco0416 commented
`pattern` validator also has a wrong test on `undefined`.

2016-12-31 03:36 UTC, vicb commented on modules/@angular/forms/test/validators_spec.ts
> +         () => { expect(Validators.required(2)(new FormControl(undefined))).toBeNull(); });
extra `(2)` here ?

2016-12-31 03:36 UTC, vicb requested changes
Please make sure the CI is green and squash your commits

2017-01-06 10:01 UTC, laco0416 commented
IMHO, this change is one of a refactoring, so `refactor(forms): ...`  is proper for better CHANGELOG.

2017-01-06 10:39 UTC, Mathou54 commented
It seems more like a test(forms) no?

2017-01-06 17:18 UTC, vicb commented
yep `test(forms)` seems the most appropriate here

2017-01-06 17:18 UTC, vicb approved these changes

2017-02-10 03:48 UTC, kara approved these changes
LGTM

2017-02-10 20:37 UTC, closed without merging