fix(router): wip
angular/angular pull request #13922
Opened 2017-01-13 23:06 UTC by DzmitryShylovich

2017-02-10 21:47 UTC, mhevery commented
@vicb Review when you get a chance.

2017-02-22 08:31 UTC, michelherv commented
Hi,
I have the same problem in case of Activation Guard. Have I to create a new issue ?

* **Angular version:** 2.4.6
* **Browser:** all
* **Language:** TypeScript 2.1.5

2017-03-29 22:31 UTC, vicb commented
@DzmitryShylovich could toy please rebase the PR ?
Thanks

2017-03-30 20:11 UTC, vicb commented on modules/@angular/router/src/router.ts
> -    // If the user triggers a navigation imperatively (e.g., by using navigateByUrl),
why is this removed ?

I don't think it relates to the issue ?

2017-03-30 20:12 UTC, vicb commented on modules/@angular/router/src/router.ts
> +                  // When navigation is canceled and it was initiated by the click on Back button,
What if was the forward button ?

2017-03-30 20:12 UTC, vicb requested changes
see inline comments

2017-03-30 20:13 UTC, DzmitryShylovich commented on modules/@angular/router/src/router.ts
> -    // If the user triggers a navigation imperatively (e.g., by using navigateByUrl),
this check breaks [this](https://github.com/angular/angular/pull/13922/files#diff-f48b128ef12ddeb072207e5ba88d04eeR1954) test.

2017-03-30 21:20 UTC, DzmitryShylovich commented on modules/@angular/router/src/router.ts
> -    // If the user triggers a navigation imperatively (e.g., by using navigateByUrl),
there're no unit tests for this so I'm not sure what uses cases it covers

2017-03-30 23:31 UTC, DzmitryShylovich commented
@vicb rebased
> What if was the forward button ?

if `forward` button was called but navigation was canceled by a guard browser history would be 1 item ahead. afaik hostory api doesn't allow to delete entries so to maintain a proper history we will need to call `location.back()`.
It's simple:
1. if back button was canceled we need to push 1 item by calling `location.pushState` because we're 1 item above
2. if forward button was canceled we need to remove 1 item by calling `location.back` because we're 1 item ahead

2017-03-31 12:38 UTC, DzmitryShylovich commented
@vicb I've created a new issue for Location.forward bug https://github.com/angular/angular/issues/15664

2017-05-24 13:01 UTC, bakhshi approved these changes

2017-07-14 20:25 UTC, jasonaden commented
Fixed moved to #18135

2017-07-14 20:25 UTC, closed without merging

2017-08-03 06:26 UTC, blueberrynotblue commented
feel sad for problem remained on 4.3

2018-01-12 14:40 UTC, UlricW commented
This issue is it fixed ?
Thanks

2019-04-22 14:09 UTC, zvonimirprofico commented
Does not seem like it is https://github.com/angular/angular/issues/13586#issuecomment-485036336