refactor(upgrade): partly unify the implementations of dynamic and static `upgrade`
angular/angular pull request #14037
Opened 2017-01-20 15:12 UTC by gkalpak

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
- `upgrade/dynamic` and `upgrade/static` use different (although similar) underlying implementations. This means that the two versions are getting out-of-sync in terms of features/fixes and that work needs to be duplicated across both.
- `upgrade/dynamic` only supports element selectors for downgraded components.
- `upgrade/static` does not respect injector hierarchy in downgraded components.

**What is the new behavior?**
- `upgrade/dynamic` and `upgrade/static` use the same code for upgrading/downgrading providers and downgrading components.
- `upgrade/dynamic` also supports non-element selectors for downgraded components.
- `upgrade/static` correctly wires up hierarchical injectors for downgraded components

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
[x] Maybe
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications:
TBD

**Other information**:
After this is merged, we need to look into unifying the implementations for upgrading components.

2017-01-20 15:20 UTC, gkalpak commented
I have broken the changes into several "logical" commits, so it is easier to review. Will squash them down afterwards.

This PR is only half the story. Unifying `upgradeComponent` and `bootstrap` is the other half (but it might be less straight-forward). I would prefer to get this in ASAP (and then work on the rest), because it can be quite a pain to rebase.

cc @petebacondarwin

2017-01-20 20:22 UTC, petebacondarwin commented on modules/@angular/upgrade/src/common/downgrade_component.ts
> +        // triggered by `UpgradeNg1ComponentAdapterBuilder`, before the Angular 2+ templates have
Is this true? I didn't think we have `UpgradeNg1ComponentAdapterBuilder` in `upgrade/static`.

2017-01-20 21:04 UTC, gkalpak commented on modules/@angular/upgrade/src/common/downgrade_component.ts
> +        // triggered by `UpgradeNg1ComponentAdapterBuilder`, before the Angular 2+ templates have
It says "might have been triggered" :smiley:

[spoiler]
It may not be possible now, but it soon will, because `./common/downgrade_component` will be used by both `upgrade/dynamic` and `upgrade/static`.
[/spoiler]

The idea is to move the implementation as close as possible to `downgradeNg2Component` from `upgrade/dynamic` (without breaking the behavior).

Note if `injector` is already present (which might always be the case in `upgrade/static`), `ParentInjectorPromise` will be _synchronous_. So, the flow will be the same as before.

2017-01-20 21:43 UTC, petebacondarwin commented on modules/@angular/upgrade/src/common/downgrade_component.ts
> +        // triggered by `UpgradeNg1ComponentAdapterBuilder`, before the Angular 2+ templates have
OK - just checkin'

2017-01-23 10:15 UTC, petebacondarwin requested changes
A couple of minor things:

* move the static specific helpers to the static folder
* convert the GROUP_PROJECTABLE_NODES_KEY to a class

Then squash, rebase etc and it will LGTM

2017-01-23 10:18 UTC, petebacondarwin commented on tools/public_api_guard/upgrade/static.d.ts
> -export declare function downgradeInjectable(token: any): (string | ((i: Injector) => any))[];
I think that this should not count as a BC. I think that the original function signature was wrong and too specific since it should have really been `IInjectable` (see https://github.com/angular/angular/blob/master/modules/%40angular/upgrade/src/angular_js.ts#L13)

Perhaps we should ensure that this commit changes it to return the correct type.

2017-01-23 10:25 UTC, petebacondarwin commented on modules/@angular/upgrade/src/aot/downgrade_component.ts
>  import * as angular from '../common/angular1';
To be sure that 656217a is not a BC I think we need the values of the constant to stay the same if possible. The names of the constants and where they are exported from has never been a public API.

2017-01-23 10:28 UTC, petebacondarwin commented on modules/@angular/upgrade/test/dynamic/metadata_spec.ts
> +      expect(getComponentInfo(ElementNameComponent).selector).toBe('element-name-dashed');
Hmm not sure about whether this is a BC. What is the external use case that would rely upon this behaviour?

2017-01-23 10:31 UTC, petebacondarwin commented
What is the potential BC in https://github.com/angular/angular/pull/14037/commits/54d7898d0f0e63d62f943ce377726675264e11d5? I don't see one.

2017-01-23 10:33 UTC, petebacondarwin commented
Also I don't see the BC in https://github.com/angular/angular/pull/14037/commits/17e007ba51f43b587b51b32b0bff5addd8446acb either

2017-01-24 17:18 UTC, gkalpak commented on tools/public_api_guard/upgrade/static.d.ts
> -export declare function downgradeInjectable(token: any): (string | ((i: Injector) => any))[];
IIRC, we should not use typs from our `angular1.ts` for public APIs (since users don't have access to them). So we can't use `IInjectable` here.

2017-01-24 18:17 UTC, gkalpak commented on modules/@angular/upgrade/src/aot/downgrade_component.ts
>  import * as angular from '../common/angular1';
This will make it less straight forward to unify the two implementations (which are currently using different keys for some injectables), since each module would set a different key, but the shared code wouldn't know which one to look for.

But I don't think it is a big deal anyway, because the things that change are:
- `COMPONENT_FACTORY_REF_MAP`: It is removed in a subsequent commit, so it doesn't matter.
- `COMPILER_KEY`/`INJECTOR_KEY`/`NG_ZONE_KEY`: They can be acquired directly from the Injector exposed by the upgrade module, so there shouldn't be a need to use our custom keys. (Not to mention they are private/undocumented.)

If you fel strongly about it, I can look into ways of keeping the original names :smiley:

2017-01-24 18:33 UTC, gkalpak commented on modules/@angular/upgrade/test/dynamic/metadata_spec.ts
> +      expect(getComponentInfo(ElementNameComponent).selector).toBe('element-name-dashed');
Unless I have missd something, the only thing affected in the end, is the the automatically generated ID that is put on the downgraded `$element` (which includes the selector).

2017-01-24 18:39 UTC, gkalpak commented
In 17e007b, I am not sure whether it makes any difference that we are now passing the downgraded components as `entryComponents` in our auto-generated `NgModule`. I don't know enough about `NgModule` internals to know if it will affect any usecase that is possible now (e.g. declaring the same components as `entryComponents` on another module?).

2017-01-24 19:02 UTC, gkalpak commented
In 54d7898, we are doing things a little different than before (terminal directive, creating the component with actual projected nodes (instead of `ng1-insertion-point` comment), etc) and it is one of those situations where I can't predict what subtle edge cases might be affected :confused:

2017-01-25 13:11 UTC, petebacondarwin commented on tools/public_api_guard/upgrade/static.d.ts
> -export declare function downgradeInjectable(token: any): (string | ((i: Injector) => any))[];
OK but we can recreate it as: `(string | Function)[] | Function`. I expect @mhevery and @vicb would have a view on this :-)

2017-01-25 13:13 UTC, petebacondarwin commented on modules/@angular/upgrade/src/aot/downgrade_component.ts
>  import * as angular from '../common/angular1';
OK. I agree.

I was just concerned that "people" might have been naughty and imported these constants despite them not being in the public API. While we have our backs covered, changing them could cause unnecessary hassle for them.

2017-01-25 13:31 UTC, petebacondarwin commented
For 17e007b, how does the Router get away with creating components, in its outlets, using the ComponentFactoryResolver, but not having to add them as `entryComponents`?

2017-01-25 13:33 UTC, petebacondarwin commented
Given that this PR looks good, regardless of the BCs, perhaps we should just list what we think might break and then only merge for landing in 4.0?

2017-01-28 04:27 UTC, mhevery commented
@gkalpak can you rebase.
@petebacondarwin can we have an approval?

2017-01-28 16:22 UTC, petebacondarwin approved these changes
Only for 4.0 with possible BCs

2017-01-28 16:59 UTC, petebacondarwin commented
I have approved but it also need approval from others (e.g. @mhevery, et al)

On Sat, 28 Jan 2017 at 04:28 Miško Hevery <notifications@github.com> wrote:

> @gkalpak <https://github.com/gkalpak> can you rebase.
> @petebacondarwin <https://github.com/petebacondarwin> can we have an
> approval?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/14037#issuecomment-275826583>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAA9J4HOiIPHmYtJNKts81s06vut6KbHks5rWsPVgaJpZM4LpZ7V>
> .
>

2017-01-31 01:08 UTC, mhevery approved these changes

2017-01-31 08:52 UTC, gkalpak commented
I have to rebase this (to take #10578 into account) and take care of the following (per previous feedback):

- Rename `aot/` to `static/`.
- Move the static specific test helpers to the `test/static/` folder.
- Convert the `GROUP_PROJECTABLE_NODES_KEY` to a class. Make class for grouping nodes (make it the token) and extend for `dynamic`.

2017-01-31 18:11 UTC, mhevery commented
Rebase pleseae

2017-02-01 11:39 UTC, gkalpak commented
I have rebased and squashed down to 5 commits (roughly one per feat/fix).

2017-02-01 11:48 UTC, petebacondarwin commented on modules/@angular/upgrade/test/static/integration/change_detection_spec.ts
> +import * as angular from '@angular/upgrade/src/common/angular1';
perhaps this should be?

```ts
import * as angularjs from '@angular/upgrade/src/common/angularjs';
```

(following our naming guidelines :-P

2017-02-01 11:49 UTC, petebacondarwin commented on tools/public_api_guard/upgrade/static.d.ts
> -export declare function downgradeInjectable(token: any): (string | ((i: Injector) => any))[];
It appears that they didn't. But this is going into Angular 4 so no matter.

2017-02-01 12:08 UTC, gkalpak commented on modules/@angular/upgrade/test/static/integration/change_detection_spec.ts
> +import * as angular from '@angular/upgrade/src/common/angular1';
Yeah, that bothered me too. But I thought we might need to bite the bullet in this one case, because `angular_js` is inconsistent with other files/symbol names:

- static/angular1_providers.ts
- dynamic/upgrade_ng1_adapter.ts
- `declareNg1Modules()`
- `registerForNg1Tests()`
- `upgradeNg1Component()`
- `UpgradeNg1ComponentAdapterBuilder`
- `upgradeNg1Provider()`
- `downgradeNg2Component()`
- `downgradeNg2Provider()`

So, in the context of the `upgrade` source code, naming things (at least files) ng1/ng2 makes it much easier to for us imo. But I am fine changing them too.

2017-02-01 15:30 UTC, closed without merging