feat(compiler-cli): Pipe out compiler output
angular/angular pull request #14135
Opened 2017-01-27 11:53 UTC by jolly-roger

Support of piping out compiled files was added

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-02-10 23:17 UTC, mhevery commented
@chuckjaz please review when you get a chance.

2017-02-11 00:47 UTC, chuckjaz requested changes

2017-02-11 00:47 UTC, chuckjaz commented on modules/@angular/compiler-cli/src/main.ts
> +    args: any, consoleError: (s: string) => void = console.error): Promise<number> {
This would be much easier if you added a `writeFile` callback to the `main()` that, if present, assigns the `writeFile` field of `host` to the passed in `writeFile`.  `pipe` could use a wrapper around `main()` that records the results of `writeFile()` and converts to the promise to the list of written files.

2017-02-15 13:25 UTC, jolly-roger commented on modules/@angular/compiler-cli/src/main.ts
> +    args: any, consoleError: (s: string) => void = console.error): Promise<number> {
Hmm, I am not sure that it would be easier and right. I have seen that tsc wrapper use more then one `host` and there is `middleware` solution, so, from my point of view, it is more correctly to introduce some new middleware, more over I have checked that it is important to write compiled sources to filesystem, because they are used in the process of compilation, especially in AOT mode, that is why I think it is risky to assign externally defined `writeFile` to `host`.
Regrading enveloping `main`, I think that it would be right solution, because I think that it is better to save interface and behavior of `main`  the same as before.
Please, correct me if I am wrong. Thanks a lot in advance.

2017-02-16 21:33 UTC, jolly-roger commented on modules/@angular/compiler-cli/src/main.ts
> +    args: any, consoleError: (s: string) => void = console.error): Promise<number> {
@chuckjaz Could you kindly review one more time. Thanks a  lot in advance.

2017-02-21 17:14 UTC, chuckjaz commented on modules/@angular/compiler-cli/src/main.ts
> +    args: any, consoleError: (s: string) => void = console.error): Promise<number> {
@jolly-roger I don't like that pipe is so baked into the compiler they way you have done it. For example, you have introduced the `PipeHost` that is always used and returns the compiled sources which is discarded. I would support a change that enables collecting the compiled sources but do not support a change that bakes this in. This change is not that bad but it sets a bad precedent by adding non-core behavior directly into the core code path. I don't want follow-on PR's to take this as an example.

I understand your hesitance to  assign to `writeFile` field of the host but it is a field just for this reason, to allow hooking writes without having to use inheritance.  However, if you still are nervous about assigning the field, create a subclass that takes a `written` callback in its constructor and only use it when the `written` callback passed to `main`. This would enabled using `main` in the manner of your PR without backing in a particular use case.

2017-05-23 21:45 UTC, closed without merging