fix(compiler): allow expressions or functions in extends
angular/angular pull request #14158
Opened 2017-01-27 23:37 UTC by alexeagle

Fixes #14154

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[X ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

Exception thrown from aot in the situations indicated in #14154

**What is the new behavior?**

Ignore unsupported supertypes

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ X] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-01-27 23:45 UTC, chuckjaz requested changes

2017-01-27 23:45 UTC, chuckjaz commented on modules/@angular/compiler/src/aot/static_reflector.ts
> +        try {
This will not work for the language service as the error will still be recorded and will show up in the editor. Instead create a `trySimplify()` that sets `errorRecorder` to a dummy function and restores the original function on the way out. When `errorRecorder` is set, exceptions are sent to it instead of thrown.

2017-01-28 00:34 UTC, alexeagle commented on modules/@angular/compiler/src/aot/static_reflector.ts
> +        try {
got it, PTAL

2017-01-28 00:35 UTC, chuckjaz approved these changes

2017-01-30 20:27 UTC, mhevery approved these changes

2017-01-31 22:23 UTC, mhevery commented
@alexeagle I can't merge this into g3 as there is a local modification which is preventing it from going in. Can we chat about it?

2017-01-31 22:54 UTC, alexeagle commented
The local modification is for this issue - just stomp over the file in
google3?

On Tue, Jan 31, 2017 at 2:23 PM Miško Hevery <notifications@github.com>
wrote:

> @alexeagle <https://github.com/alexeagle> I can't merge this into g3 as
> there is a local modification which is preventing it from going in. Can we
> chat about it?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/14158#issuecomment-276512714>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAC5IyrHv1ZnxAMqJwkX-T3xQCBDEfp3ks5rX7RtgaJpZM4LwVBX>
> .
>

2017-02-01 01:02 UTC, closed without merging