feat(i18n): Implement XLIFF 2.0 serializer
angular/angular pull request #14185
Opened 2017-01-30 10:21 UTC by panuruj

- Use <ph/> for self-closing placeholder tags
- Use <pc></pc> for other placeholder tags
- Ensure that the result pass OASIS XLIFF 2.0 schema validation

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
There is currently no XLIFF 2.0 serializer for i18n.
closes angular/angular#11735

**What is the new behavior?**
Implemented XLIFF 2.0 serializer

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-01-31 00:21 UTC, panuruj commented
@vicb I have updated the XLIFF 2.0 serialization based on the latest codebase. Please let me know if you have any feedback.

2017-01-31 19:05 UTC, vicb commented on modules/@angular/compiler-cli/integrationtest/test/i18n_spec.ts
> +    <unit id="76e1eccb1b772fa9f294ef9c146ea6d0efa8a2d4">
could you please use `decimalDigest` instead ? 
I'd like to migrate 1.2 as well (which will need some upgrade script)

2017-01-31 19:06 UTC, vicb commented on modules/@angular/compiler-cli/src/extractor.ts
> +      const content = this.serialize(bundle, formatName);
format ?

2017-01-31 19:06 UTC, vicb commented on modules/@angular/compiler-cli/src/extractor.ts
> +      case 'xliff2':
'xlf2' ?

2017-01-31 19:06 UTC, vicb commented on modules/@angular/compiler-cli/src/extractor.ts
> +    throw new Error(`Unsupported format "${formatName}"`);
:+1:

2017-01-31 19:07 UTC, vicb commented on modules/@angular/compiler/src/i18n/serializers/xliff2.ts
> +      if (visited[id]) return;
this is not required any more (check xliff)

2017-01-31 19:11 UTC, vicb commented
Could you please address the comments and check the latest changes in the xliff 1.2 serializer ?

Thanks

2017-01-31 19:56 UTC, panuruj commented on modules/@angular/compiler/src/i18n/serializers/xliff2.ts
> +      if (visited[id]) return;
Removed

2017-01-31 19:57 UTC, panuruj commented on modules/@angular/compiler-cli/src/extractor.ts
> +      case 'xliff2':
Updated

2017-01-31 19:57 UTC, panuruj commented on modules/@angular/compiler-cli/src/extractor.ts
> +      const content = this.serialize(bundle, formatName);
Updated

2017-01-31 19:57 UTC, panuruj commented on modules/@angular/compiler-cli/integrationtest/test/i18n_spec.ts
> +    <unit id="76e1eccb1b772fa9f294ef9c146ea6d0efa8a2d4">
Yup, updated

2017-01-31 20:15 UTC, panuruj commented on modules/@angular/compiler-cli/integrationtest/test/i18n_spec.ts
> +    <unit id="76e1eccb1b772fa9f294ef9c146ea6d0efa8a2d4">
I have updated the `decimalDigest`.
Quick question, how does this integration test work?
Both the XLIFF formats have the same extension, so there is only 1 file. What would you recommend in order to work around the issue?

2017-01-31 20:18 UTC, panuruj commented on modules/@angular/compiler-cli/integrationtest/test/i18n_spec.ts
> +    const xlfOutput = path.join(outDir, 'messages.xlf');
@vicb, I'm not quite sure how to get this to work. Both XLIFF formats generate the same filename, so how would you recommend validating the files in the integration tests?

2017-02-09 00:39 UTC, panuruj commented
@vicb, I have addressed all of the feedback, and I have just one question left about the integration test.

2017-02-10 23:21 UTC, mhevery approved these changes

2017-02-13 19:21 UTC, mhevery commented
The PR is failing tests. Please fix before it can be merged.

2017-02-13 23:26 UTC, panuruj commented
@mhevery I have addressed all of the build errors.

2017-02-20 23:51 UTC, vicb commented on modules/@angular/compiler-cli/integrationtest/test/i18n_spec.ts
> +  xit('should extract i18n messages as xliff version 2.0', () => {
xit ?

2017-02-21 19:16 UTC, panuruj commented on modules/@angular/compiler-cli/integrationtest/test/i18n_spec.ts
> +  xit('should extract i18n messages as xliff version 2.0', () => {
That's the part that I need your help. The integration tests run through all of the commands first, then do the assertion. The two XLIFF serializers (1,2 and 2..0) generate the same filename and overwrite on each other. What would be your recommendation to test this? Would you recommend renaming one of the files during the test run? Thank you in advance.

2017-02-21 19:38 UTC, vicb commented on modules/@angular/compiler-cli/integrationtest/test/i18n_spec.ts
> +  xit('should extract i18n messages as xliff version 2.0', () => {
https://github.com/angular/angular/pull/14508 will help here

2017-02-21 22:05 UTC, vicb commented
I think #14537 and #14508 need to be merged before.

/cc @ocombe

2017-02-24 10:46 UTC, panuruj commented
@vicb @ocombe, I have merged with the latest master and re-enabled the E2E test for XLIFF 2.0. Please let me know if there is anything else that needs to be fixed.

2017-02-24 10:53 UTC, ocombe commented
I was about to say that you needed to add the locale, but you already did that! Kuddos!
I'll take a deeper look at it later today

2017-02-24 17:57 UTC, ocombe commented on modules/@angular/compiler-cli/src/extractor.ts
> +      case 'xlf2':
should you also add xliff2 if you add xliff below?

2017-02-24 17:57 UTC, ocombe commented on modules/@angular/compiler/src/i18n/i18n_html_parser.ts
> +    case 'xlf2':
same thing here with xliff2 ?

2017-02-24 18:50 UTC, panuruj commented on modules/@angular/compiler-cli/src/extractor.ts
> +      case 'xlf2':
I had that earlier, but @vicb suggested that it should just be xlf2.
Would you prefer to have both?

2017-02-24 18:52 UTC, ocombe commented on modules/@angular/compiler-cli/src/extractor.ts
> +      case 'xlf2':
well it makes more sense but @vicb decides, so don't bother adding it again then

2017-02-28 20:45 UTC, panuruj commented
@vicb  @ocombe , do you have any questions or concerns? I have been using this code to translate to 40+ languages in the past month.

2017-02-28 21:05 UTC, ocombe commented
No questions on my part it sounds good. I think that @vicb was waiting for v4 to be released before merging this PR, it should get into v4.1 (v4.0 roadmap was already fixed).

2017-03-20 09:36 UTC, ocombe commented
@panuruj the first 4.1 beta should be released soon (in 1 or 2 weeks), can you fix the conflicts before that? Thanks

2017-03-20 18:53 UTC, panuruj commented
@ocombe I should be able to get to it this weekend.

2017-03-20 18:57 UTC, ocombe commented
Ok, no rush, you have until v4 final is published, and if necessary we can fix the conflict ourselves

2017-04-07 07:40 UTC, panuruj commented
@ocombe I have resolved merge conflicts and incorporate ICU to the XLIFF 2 serializer. Please take another look and let me know if you have any feedback.

2017-04-07 20:19 UTC, ocombe approved these changes
Nice thanks, sounds good to me!

2017-04-07 21:38 UTC, vicb commented on packages/compiler/src/i18n/serializers/xliff2.ts
> +        [].concat(...ml.visitAll(this, xmlIcu.rootNodes));
[...ml.visitAll(this, xmlIcu.rootNodes)]

2017-04-07 21:38 UTC, vicb commented on packages/compiler/src/i18n/serializers/xliff2.ts
> +      i18nNodes: i18nNodes,
i18nNodes

2017-04-07 21:39 UTC, vicb commented on packages/compiler/src/i18n/serializers/xliff2.ts
> +            ...[].concat(...el.children.map(node => node.visit(this, null))),
simplify

2017-04-07 21:39 UTC, vicb commented on packages/compiler/src/i18n/serializers/xliff2.ts
> +      nodes: [].concat(...ml.visitAll(this, icuCase.expression)),
simplify

2017-04-07 21:39 UTC, vicb requested changes
Please address inline comments

2017-04-07 21:40 UTC, vicb commented on packages/compiler/src/i18n/serializers/xliff2.ts
> +      unit.children.push(new xml.CR(4));
collpase with previous `push`

2017-04-07 21:42 UTC, vicb commented on packages/compiler/src/i18n/serializers/xliff2.ts
> +    return [].concat(...nodes.map(node => node.visit(this)));
simplify

2017-04-07 22:58 UTC, panuruj commented on packages/compiler/src/i18n/serializers/xliff2.ts
> +        [].concat(...ml.visitAll(this, xmlIcu.rootNodes));
They are not the same...
visitAll() returns an array of node array. I need to flatten them first with concat().

2017-04-07 23:35 UTC, panuruj commented on packages/compiler/src/i18n/serializers/xliff2.ts
> +      i18nNodes: i18nNodes,
updated

2017-04-07 23:35 UTC, panuruj commented on packages/compiler/src/i18n/serializers/xliff2.ts
> +            ...[].concat(...el.children.map(node => node.visit(this, null))),
updated

2017-04-07 23:36 UTC, panuruj commented on packages/compiler/src/i18n/serializers/xliff2.ts
> +      nodes: [].concat(...ml.visitAll(this, icuCase.expression)),
I need to flatten an array of array, so this is as simple as it gets.

2017-04-07 23:37 UTC, panuruj commented on packages/compiler/src/i18n/serializers/xliff2.ts
> +    return [].concat(...nodes.map(node => node.visit(this)));
Same here. I need to flatten an array of array.

2017-04-12 04:18 UTC, vicb commented on packages/compiler/src/i18n/serializers/xliff2.ts
> +    return [].concat(...nodes.map(node => node.visit(this)));
you're right LGTM

2017-04-12 04:18 UTC, vicb approved these changes

2017-04-14 16:05 UTC, merged