feat(upgrade): support multi-slot projection in upgrade/static
angular/angular pull request #14282
Opened 2017-02-03 14:05 UTC by petebacondarwin

Closes #14261

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

downgradedComponents in upgrade/static did not correctly project multi-slot content.

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-02-03 14:27 UTC, gkalpak requested changes

2017-02-03 14:27 UTC, gkalpak commented on modules/@angular/upgrade/src/common/downgrade_component.ts
> + * The `selectors` are the strings that appear in the `ng-content` element's `select` attribute.
Maybe: _element's `select` attribute_ --> _elements' `select` attributes_

2017-02-03 14:27 UTC, gkalpak commented on modules/@angular/upgrade/test/common/downgrade_component_adaptor_spec.ts
> +/**
Naming the file `_adapter_` instead of `_adaptor_` would be more consistent with the class name :wink:

2017-02-03 14:27 UTC, gkalpak commented on modules/@angular/upgrade/test/common/downgrade_component_adaptor_spec.ts
> +            'id', {component: null, selectors}, content, null, null, null, fakeInjector, null, null,
Too much mocking here (Travis complains) :smiley:
`DowngradeComponentAdapter` creates the `componentScope` in the constructor, so it needs a `$scope` with a `$new` method.

2017-02-03 16:17 UTC, petebacondarwin commented on modules/@angular/upgrade/test/common/downgrade_component_adaptor_spec.ts
> +            'id', {component: null, selectors}, content, null, null, null, fakeInjector, null, null,
Or not enough mocking!

2017-02-03 16:58 UTC, petebacondarwin commented
@gkalpak PTAL

2017-02-03 16:58 UTC, petebacondarwin commented
I have checked that this code passes #14276

2017-02-03 22:37 UTC, gkalpak approved these changes

2017-02-09 09:18 UTC, petebacondarwin commented
@IgorMinar  or @mhevery can we get a LGTM on the public api file change?

2017-02-09 10:31 UTC, gkalpak commented on modules/@angular/upgrade/src/common/downgrade_component_adapter.ts
> +import {CssSelector, SelectorMatcher, createElementCssSelector} from '@angular/compiler';
This line will now be included in `upgrade/static`. Can someone (@alexeagle?) verify that this won't have unwanted side effects (such as pulling in too much code from `@angular/compiler`)?

2017-02-09 17:17 UTC, alexeagle commented on modules/@angular/upgrade/src/common/downgrade_component_adapter.ts
> +import {CssSelector, SelectorMatcher, createElementCssSelector} from '@angular/compiler';
Sorry this is obsured from you :(
We could maybe split the `modules/@angular/upgrade` tsconfig into two compilation units that match how we compile it internally.

The short answer is that we compile only these files
```
    "modules/@angular/upgrade/src/common/**/*.ts",
    "modules/@angular/upgrade/src/static/**/*.ts",
    "modules/@angular/upgrade/src/facade/**/*.ts",
    "modules/@angular/upgrade/static.ts",
```

so this file would need to be moved out of common, or needs to be excluded from the compilation (and then not imported by anything else in static)

2017-02-09 17:18 UTC, alexeagle commented on modules/@angular/upgrade/src/common/downgrade_component_adapter.ts
> +import {CssSelector, SelectorMatcher, createElementCssSelector} from '@angular/compiler';
(because of limitations in the treeshaker, we don't include @angular/compiler as a transitive dependency of angular apps at all)

2017-02-09 18:18 UTC, mhevery approved these changes

2017-02-09 18:18 UTC, mhevery commented
Please resolve conflicts

2017-02-09 19:40 UTC, petebacondarwin commented on modules/@angular/upgrade/src/common/downgrade_component_adapter.ts
> +import {CssSelector, SelectorMatcher, createElementCssSelector} from '@angular/compiler';
@alexeagle shall I move these functions into some common place, `@angular/common`(??) or maybe `facade`? Or should i just make a copy of the files (I feel very bad about that) into `upgrade`?

2017-02-09 19:41 UTC, alexeagle commented on modules/@angular/upgrade/src/common/downgrade_component_adapter.ts
> +import {CssSelector, SelectorMatcher, createElementCssSelector} from '@angular/compiler';
It seems like either 1) upgrade shouldn't use these because they are part of the compiler, or 2) they are not really part of the compiler and could move to common.

@tbosch or @IgorMinar  ?

2017-02-09 19:51 UTC, mhevery commented
1) We should not import from compiler as that creates a runtime dependency.
2) We want to get rid of the facade, so that is not a good place to put
them either.
3) We don't really have a common dumping ground.

Given 1,2,3, I would be OK with just making a copy.

On Thu, Feb 9, 2017 at 11:41 AM, Alex Eagle <notifications@github.com>
wrote:

> *@alexeagle* commented on this pull request.
> ------------------------------
>
> In modules/@angular/upgrade/src/common/downgrade_component_adapter.ts
> <https://github.com/angular/angular/pull/14282>:
>
> > @@ -6,13 +6,14 @@
>   * found in the LICENSE file at https://angular.io/license
>   */
>
> +import {CssSelector, SelectorMatcher, createElementCssSelector} from '@angular/compiler';
>
> It seems like either 1) upgrade shouldn't use these because they are part
> of the compiler, or 2) they are not really part of the compiler and could
> move to common.
>
> @tbosch <https://github.com/tbosch> or @IgorMinar
> <https://github.com/IgorMinar> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/14282>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAG1T7o7_SkpgqHp4hHP93KuPkmi4pJFks5ra2v-gaJpZM4L2XFx>
> .
>

2017-02-09 21:37 UTC, petebacondarwin commented
Copy it is  then. I will update the PR tomorrow.

2017-02-10 11:08 UTC, petebacondarwin commented
Unfortunately, @mhevery, I don't think that making a copy is an option. While these three imports look small on the surface, they hide loads of code in the form of the HTML template parser.

2017-02-10 20:18 UTC, mhevery commented
@petebacondarwin ok, lets put in in the facade then.

2017-02-28 11:32 UTC, petebacondarwin commented
Actually looking at this again, I think we can accomplish this by creating symlinks for the `selector.ts` file and the `ml_parser` folder; and then copy over a couple of functions from the `template_parser`.

2017-03-02 06:55 UTC, gkalpak commented on modules/@angular/upgrade/src/dynamic/upgrade_adapter.ts
> +                      {provide: NgContentSelectorHelper, useClass: DynamicNgContentSelectorHelper},
Couldn't we get rid of having to provide `NgContentSelectorHelper` by automaticalky populating `info.selector` in the dynamic version?

2017-03-02 11:18 UTC, petebacondarwin commented on modules/@angular/upgrade/src/dynamic/upgrade_adapter.ts
> +                      {provide: NgContentSelectorHelper, useClass: DynamicNgContentSelectorHelper},
You mean do it here? https://github.com/petebacondarwin/angular/blob/8c88cca5f54b6eca51dcea3d3350946fe744e8a0/modules/%40angular/upgrade/src/dynamic/upgrade_adapter.ts#L194

Yes that sounds reasonable. I'll try it out.

2017-03-08 16:38 UTC, petebacondarwin commented on modules/@angular/upgrade/src/dynamic/upgrade_adapter.ts
> +                      {provide: NgContentSelectorHelper, useClass: DynamicNgContentSelectorHelper},
Sadly we cannot do that because the `downgradeComponent` helper is called before we bootstrap, so the `Compiler` service is not available.
I guess we could rewrite everything so that this information could be computed lazily after bootstrap but I don't think the benefit of removing the `NgContentSelectorHelper` would warrant the effort and the churn.

2017-03-11 00:51 UTC, chuckjaz commented
This PR needs to be rebased.

2017-03-11 09:05 UTC, petebacondarwin commented
@chuckjaz - done.

2017-03-14 00:05 UTC, chuckjaz commented
This PR looks like it needs to be rebased again.

2017-03-14 00:34 UTC, merged

2017-03-14 02:37 UTC, tbosch commented on packages/upgrade/src/common/downgrade_component_adapter.ts
> +          createElementCssSelector(node.nodeName.toLowerCase(), getAttributesAsArray(node));
Couldn't we use `element.matches` (see https://developer.mozilla.org/en-US/docs/Web/API/Element/matches)? Angular already verified during compiling the component that the selector is a "simple" selector that could be resolved via `CssSelector`, and `CssSelector` is a strict subset of the full css spec...

2017-03-14 02:38 UTC, tbosch commented on packages/upgrade/src/common/ng_content_selector_helper.ts
> +  getNgContentSelectors(info: ComponentInfo): string[] {
I think we should change `ComponentRef` to have a getter `ngContentSelectors`. This way, we can use this information in AOT and JIT mode without the user specifying it...

2017-03-14 02:42 UTC, tbosch commented on packages/upgrade/src/common/downgrade_component.ts
>    inputs?: string[];
Using a string array here will break with closure enhanced optimizations. Also, I think we should change the compiler to provide an `inputs` and `outputs` map in the `ComponentRef` class, together with `ngContentSelectors`. Something like this:

```
class ComponentFactory<T> {
  // mapping from mangeled input name to non mangeled name.
  inputs: {[key: string]: string};
  // mapping from mangeled output name to mangeled name.
  outputs: {[key: string]: string};
  // array of the selectors users in `ng-content`.
  ngContentSelectors: string[];
}

2017-03-14 02:45 UTC, tbosch commented
Sorry, I missed this PR somehow... But I do think we should change this before cutting the next rc as
- we probably want to deprecate the old way of specifying `inputs` and `outputs` as they break closure compiler.
- we don't want users to repeat the selectors of `ng-content`
- I would like to keep the `CssSelector` and parser classes private to the compiler, so that we can change it more easily...

2017-03-14 06:56 UTC, petebacondarwin commented
@tbosch:
Removing boilerplate from the `upgrade/static` API would make my day :-)
What do we need to do to make the compiler changes happen?
When we deprecate the inputs/outputs then they would just have no effect, right? Since the JIT/AOT compilers will do the work going forward.

2017-03-14 22:44 UTC, tbosch commented
See https://github.com/angular/angular/pull/15156 for the cleanups...