fix(platform-browser): DomAdapter should resolve event names by keyCode first
angular/angular pull request #14344
Opened 2017-02-07 17:08 UTC by DzmitryShylovich

Closes #8273
Closes #9419

2017-02-08 20:45 UTC, DzmitryShylovich commented on modules/@angular/platform-browser/src/browser/browser_adapter.ts
> -          // https://code.google.com/p/chromium/issues/detail?id=155654
bug was fixed

2017-02-09 19:45 UTC, mhevery approved these changes

2017-02-09 21:37 UTC, mhevery requested changes
We can't take code from other projects without their approval. This can not be merged.

2017-02-10 04:51 UTC, IgorMinar commented
we shouldn't even try to fix this PR. stealing code is not OK.

@DzmitryShylovich please do not ever try to submit PRs to any of our repos that contain stolen code. Doing so violates the Google CLA you signed and also violates license of the project you stole the code from. If such code was accidentally merged into our repo, the whole project could be jeopardized and I'm sure that's not something you'd like to see happen.

Open source is great way to learn about software and collaborate, but just because some code is open sourced it doesn't mean that it can be copy&pasted into other open source project without fulfilling all the attribution, licensing and any other legal requirements of the originating and receiving project.

2017-02-10 04:51 UTC, closed without merging

2017-02-10 13:36 UTC, DzmitryShylovich commented
@IgorMinar 
Probably `steal` was a poor word choice. I would call it `adopting` :)
Here we are talking about 20 LOC method to get event keys. It's not super secret/important algo or something like that. 
I don't really want to reinvent the wheel for such a common use case. And I don't see anything bad in adopting experience of another successful framework. And I'm 99% sure that react guys wouldn't be against. But I understand that it violates licensing so I'll try to roll out more independent solution.