build: allow users to specify --strictNullChecks
angular/angular pull request #14382
Opened 2017-02-09 20:14 UTC by alexeagle

fixes #11844

2017-02-09 21:37 UTC, IgorMinar requested changes

2017-02-09 21:37 UTC, IgorMinar commented on integration/run_tests.sh
> +# Because yarn cache won't reinstall file:// URIs when package json is unchanged
is there a yarn bug for this?

blowing away the cache should be the last resort workaround.

2017-02-09 21:37 UTC, IgorMinar commented on modules/@angular/platform-browser/src/browser/meta.ts
> +  [prop: string]: string|undefined;
is this right? can't we remove the `[prop: string]: string` from the original api and void this completely?

I'll track this one down.

2017-02-09 21:37 UTC, IgorMinar commented on modules/@angular/core/src/util/decorators.ts
> +  [x: string]: Type<any>|Function|any[]|undefined;
is this right? Alex says that if we made `extends` non-optional by defaulting it to Object we can remove the bracket access completely.

@mhevery @tbosch could we do that?

2017-02-09 21:50 UTC, gkalpak commented on integration/run_tests.sh
> +../node_modules/.bin/yarn cache clean
Since d1feb47, the global yarn is being used. I don't think there is any reason to use the local one here.
(In fact, there is no reason to have `yarn` as a dependency any more afaik.)

2017-02-09 22:17 UTC, alexeagle commented on integration/run_tests.sh
> +# Because yarn cache won't reinstall file:// URIs when package json is unchanged
changed to use a local cache dir for this one installation, which is deleted next run.

2017-02-09 23:20 UTC, alexeagle commented on integration/run_tests.sh
> +../node_modules/.bin/yarn cache clean
We still want to pin the version of yarn that we run, right? Just like we do for npm? Otherwise the behavior will depend on what version travis has or someone has global-installed

2017-02-09 23:26 UTC, alexeagle commented on integration/run_tests.sh
> +../node_modules/.bin/yarn cache clean
Ah, I see your other comment about pinning in env.sh.
Still fishy to me that local devs may get the wrong version but I'm happy to follow your lead

2017-02-09 23:39 UTC, IgorMinar approved these changes

2017-02-10 20:37 UTC, closed without merging

2017-02-10 20:46 UTC, alexeagle commented on integration/run_tests.sh
> +../node_modules/.bin/yarn cache clean
Global yarn is okay with me, as long as we check it - the same way we do for npm seems like a consistent way to start