fix(platform-browser): update template binding regex to match any string
angular/angular pull request #14424
Opened 2017-02-11 15:26 UTC by DzmitryShylovich

Closes #14423

2017-02-11 19:09 UTC, vicb requested changes
The server renderer needs the same fix and you should also add tests. Thanks.

2017-02-11 19:34 UTC, DzmitryShylovich commented
@vicb where can I find test specs for debug bindings? Didn't find anything.

2017-02-13 04:19 UTC, vicb commented on modules/@angular/platform-browser/test/dom/dom_renderer_spec.ts
> +          const expression = `{"ng-reflect-ng-if": "${String.fromCharCode(8233)}"}`;
I'm not really sure if those added tests are really helpful... ie do we use that regexp at all ?

Integration tests would be much better. Could you take a stab at adding them ?

2017-02-17 08:06 UTC, closed without merging

2017-02-17 08:07 UTC, DzmitryShylovich commented
fix after 4.0 when api will be stable