docs(router): fix broken link
angular/angular pull request #14431
Opened 2017-02-12 07:22 UTC by DzmitryShylovich

Closes #14430

2017-02-13 04:14 UTC, vicb commented on modules/@angular/router/README.md
> +Read the book [here](https://leanpub.com/router).
IMO you should mention:
- this is a paid book,
- written by victor savkin the architect of the router.

2017-02-13 04:14 UTC, vicb commented on modules/@angular/router/README.md
> +Read the overview of the Router [here](https://vsavkin.com/angular-2-router-d9e30599f9ea#.lcmgpt8p7).
remove the # part

2017-02-13 08:51 UTC, DzmitryShylovich commented
@vicb updated

2017-02-14 23:34 UTC, vicb approved these changes

2017-02-16 19:18 UTC, IgorMinar commented
hi @DzmitryShylovich 

README files are not an appropriate place for advertising paid services, and we try to avoid favoritism. We will not add a paid book link to the readme.

Can you please change the PR to update the blog post link but not add the other one? thanks!

2017-02-16 19:18 UTC, IgorMinar requested changes
hi @DzmitryShylovich

README files are not an appropriate place for advertising paid services, and we try to avoid favoritism. We will not add a paid book link to the readme.

Can you please change the PR to update the blog post link but not add the other one? thanks!

2017-02-16 19:27 UTC, DzmitryShylovich commented
@IgorMinar done

2017-02-16 19:31 UTC, IgorMinar approved these changes

2017-02-16 19:32 UTC, IgorMinar commented
thanks @DzmitryShylovich

2017-02-16 19:32 UTC, merged