fix(platform-server): render styles in app component instead of <head>
angular/angular pull request #14483
Opened 2017-02-14 21:11 UTC by alxhub

This ensures when the tree is serialized to the client and the app is later bootstrapped,
the <style> tags created during server-side rendering are destroyed.

2017-02-14 21:21 UTC, vikerman requested changes

2017-02-14 21:21 UTC, vikerman commented on modules/@angular/platform-browser/src/private_export.ts
> +  DOCUMENT: typeof dom_tokens.DOCUMENT,
DOCUMENT is a public symbol in @angular/platform-browser.

2017-02-14 21:21 UTC, vikerman commented on modules/@angular/platform-server/src/parse5_adapter.ts
> +export let treeAdapter: any;
Why do you need to export this?

2017-02-14 21:37 UTC, alxhub commented on modules/@angular/platform-browser/src/private_export.ts
> +  DOCUMENT: typeof dom_tokens.DOCUMENT,
Fixed

2017-02-14 21:38 UTC, alxhub commented on modules/@angular/platform-server/src/parse5_adapter.ts
> +export let treeAdapter: any;
Fixed

2017-02-14 22:44 UTC, vikerman approved these changes

2017-02-14 22:44 UTC, vikerman commented on modules/@angular/platform-server/src/styles_host.ts
> + */
The convention for file name seems to indicate this file should be named server_styles_host.ts. Easier to search later.

2017-02-14 22:44 UTC, vikerman commented on modules/@angular/platform-server/src/styles_host.ts
> +
Can we add unit tests for this class alone? Or open an issue to add later.

2017-02-15 00:07 UTC, alxhub commented on modules/@angular/platform-server/src/styles_host.ts
> + */
"server styles host" as a search returns this file. I prefer not having redundancy in the file name.

2017-02-15 00:07 UTC, alxhub commented on modules/@angular/platform-server/src/styles_host.ts
> +
Issue would be best, will do.

2017-02-15 00:13 UTC, mhevery approved these changes

2017-02-15 19:42 UTC, closed without merging