feat(aio): upgrade to CLI beta.32 and MD beta.2
angular/angular pull request #14611
Opened 2017-02-21 03:09 UTC by wardbell

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

2017-02-21 17:10 UTC, gkalpak commented on aio/e2e/app.po.ts
> +  datePipeLink = element.all(by.css('md-toolbar a[aioNavLink="api/common/date-pipe"]'));
Why are there multiple nav-links for the same URL?

2017-02-21 17:10 UTC, gkalpak commented on aio/package.json
> -    "build": "ng build",
What happened to `build`?

2017-02-21 17:10 UTC, gkalpak commented on aio/package.json
>      "pree2e": "webdriver-manager update --standalone false --gecko false",
Should this be renamed to `pree2e:old`? Is it still needed before `ng e2e`?

2017-02-21 17:10 UTC, gkalpak commented on aio/protractor.conf.js
> -      binary: process.env.CHROME_BIN
Why is this no longer necessary?

2017-02-21 19:41 UTC, wardbell commented on aio/package.json
> -    "build": "ng build",
Restoring

2017-02-21 19:42 UTC, wardbell commented on aio/e2e/app.po.ts
> +  datePipeLink = element.all(by.css('md-toolbar a[aioNavLink="api/common/date-pipe"]'));
It appears twice in the DOM, once in the top menu bar and once at the top of the left nav. Only one set of links is visible to the user at any one time. It's a hide/show thing.

2017-02-21 19:43 UTC, wardbell commented on aio/package.json
>      "pree2e": "webdriver-manager update --standalone false --gecko false",
For reasons unknown to me, the `e2e` command does not update webdriver even thought the command name is `pree2e`.  The latter command must be run by hand after every `npm install` or `yarn install`.

2017-02-21 19:43 UTC, wardbell commented on aio/protractor.conf.js
> -      binary: process.env.CHROME_BIN
Restoring

2017-02-21 20:05 UTC, gkalpak commented on aio/package.json
>      "pree2e": "webdriver-manager update --standalone false --gecko false",
That's is weird (and most probably untrue 😛).

2017-02-21 20:18 UTC, gkalpak commented on aio/package.json
>      "pree2e": "webdriver-manager update --standalone false --gecko false",
For some reason, both ChromeDriver v2.15 and v2.27 are downloaded on Travis (e.g. https://travis-ci.org/angular/angular/jobs/203945848). No idea why or if this is related...

2017-02-21 21:09 UTC, gkalpak commented on aio/e2e/app.po.ts
> +  datePipeLink = element.all(by.css('md-toolbar a[aioNavLink="api/common/date-pipe"]'));
Not feeling strong about it, but I would prefer to have the `.get(0)` here, rather than on call site. The fact that there are multiple navs for the same target is an implementation detail that doesn't need to "leak" outside `app.po.ts` imo.

2017-02-21 21:11 UTC, gkalpak commented on aio/package.json
>      "pree2e": "webdriver-manager update --standalone false --gecko false",
Nit: It is clearer imo to keep `pre-`/`post-` scripts close to the main script (so that would be moving this right above `e2e`).

2017-02-22 20:56 UTC, petebacondarwin requested changes
Can you squash in this commit: https://github.com/IdeaBlade/angular/pull/1/commits/320a2df752a6f310261daa7b1551134249b1c7bf

2017-02-22 21:19 UTC, petebacondarwin approved these changes
LGtM

2017-02-22 21:52 UTC, IgorMinar requested changes

2017-02-22 21:52 UTC, IgorMinar commented on scripts/ci-lite/env.sh
> +CHROMIUM_VERSION=433059 # Chrome 56 linux stable, see https://www.chromium.org/developers/calendar
why this change? this is a big change for our CI that must be in a separate commit.

2017-02-22 21:52 UTC, IgorMinar commented on scripts/ci-lite/test_aio.sh
> +# e2e starts server itself as of beta.32.3
no need for this comment. it's not going to mean anything to us in 6 months.

2017-02-22 21:52 UTC, IgorMinar commented on aio/karma.conf.js
> +      require('karma-jasmine-html-reporter'),
this change is not mentioned in the commit message. it should be a separate commit, but you already have a PR for this. was this left here by accident?

2017-02-22 21:52 UTC, IgorMinar commented on aio/package.json
> +    "e2e:old": "protractor",
do we still need the old lint and e2e tasks?

2017-02-22 21:52 UTC, IgorMinar commented on aio/tslint.json
> +    "no-inferrable-types": [true, "ignore-params"],
why this change?

2017-02-22 23:48 UTC, wardbell commented on scripts/ci-lite/test_aio.sh
> +# e2e starts server itself as of beta.32.3
Will remove

2017-02-22 23:49 UTC, wardbell commented on aio/karma.conf.js
> +      require('karma-jasmine-html-reporter'),
It will obviate the need for that PR. This change is now part of CLI beta.32.3

2017-02-22 23:50 UTC, wardbell commented on aio/tslint.json
> +    "no-inferrable-types": [true, "ignore-params"],
It's in cli: https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/tslint.json#L49

2017-02-22 23:51 UTC, wardbell commented on aio/package.json
> +    "e2e:old": "protractor",
I was being cautious. I don't think so. Will remove.

2017-02-22 23:52 UTC, wardbell commented on scripts/ci-lite/env.sh
> +CHROMIUM_VERSION=433059 # Chrome 56 linux stable, see https://www.chromium.org/developers/calendar
Moved to separate commit. From now on, any changes to anything OUTSIDE of the `aio` will be in a separate commit and possibly a separate PR.

2017-02-22 23:53 UTC, wardbell commented on scripts/ci-lite/test_aio.sh
> +# e2e starts server itself as of beta.32.3
Should this script file, which is aio-specific, be in the aio folder?

2017-02-23 00:26 UTC, IgorMinar approved these changes

2017-02-23 00:26 UTC, IgorMinar commented on aio/tslint.json
> +    "no-inferrable-types": [true, "ignore-params"],
thanks for explanation

2017-02-23 00:26 UTC, IgorMinar commented on scripts/ci-lite/env.sh
>  NODE_VERSION=6.9.5
the commit message should no longer be scoped to "aio" because this commit affects stuff outside of the `aio/` directory. Suggested replacement: `ci: update local chrome to v56` + merge the `test_aio.sh` change in to the previous commit that upgrades the CLI version.

2017-02-23 00:26 UTC, wardbell commented on scripts/ci-lite/env.sh
>  NODE_VERSION=6.9.5
Changing that now

2017-02-23 00:46 UTC, wardbell commented on aio/karma.conf.js
> +      require('karma-jasmine-html-reporter'),
I'll close that PR #14392 when this PR merges.

2017-02-23 01:53 UTC, merged