feat(forms): wip
angular/angular pull request #14679
Opened 2017-02-23 17:55 UTC by DzmitryShylovich

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-03-10 15:33 UTC, DzmitryShylovich commented
@kara can you take a look please? it's [stated in the changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#typescript-21) that angular 4  compliant with TypeScript’s StrictNullChecks but it's not actually true.

2017-03-10 17:48 UTC, kara requested changes
I think you're still missing updates in `runValidator()` and `runAsyncValidator()`(for consistency), and this will need a rebase. But looks good (minor comments).

2017-03-10 17:48 UTC, kara commented on modules/@angular/forms/src/directives/validators.ts
> +export type Errors = {
This seems a bit general. How about `ValidationErrors`?

2017-03-10 17:48 UTC, kara commented on modules/@angular/forms/src/model.ts
> +import {EventEmitter} from './facade/async';
Can you switch to `@angular/core` for this import?

2017-03-10 17:48 UTC, kara commented on modules/@angular/forms/test/directives_spec.ts
> +import {Errors} from '@angular/forms/src/directives/validators';
Can you remove this deep import? Should come from `@anguar/forms`.

2017-03-10 18:42 UTC, DzmitryShylovich commented
@kara fixed. PTAL

btw what do you think about making `FormGroup.controls` a readonly property to prevent issues like https://github.com/angular/angular/issues/11701 ? (it's a subject of another pr but anyway 😄)

2017-03-10 18:57 UTC, kara approved these changes
LGTM

2017-03-10 19:44 UTC, kara commented
@DzmitryShylovich Hmm, something to think about. You're right that people should really be using our established ways to register controls rather than mutating the controls list directly. But changing this would be a big breaking change, so we'll have to ensure we're not missing any use cases.

2017-03-10 19:55 UTC, DzmitryShylovich commented
> But changing this would be a big breaking change, so we'll have to ensure we're not missing any use cases.

this is why I asked before 4.0 final. 
And tbh I don't think it will be that big. People usually use `controls` for iteration. I don't see use cases for direct control list mutation. Sooner or later it will cause problems.

2017-03-10 19:58 UTC, DzmitryShylovich commented
rebase everything once again 😱

2017-03-11 15:56 UTC, DzmitryShylovich commented
@kara if you're interested pr is here https://github.com/angular/angular/pull/15086 😃

2017-03-14 18:21 UTC, mmc41 commented
Really need a fix for this. strictNullChecks is a major feature improvement in 4.0 and it is clearly advertised as supported already right from RC1.

2017-03-14 18:27 UTC, kara approved these changes
LGTM (again).

2017-03-14 18:52 UTC, mhevery requested changes

2017-03-14 18:52 UTC, mhevery commented on tools/public_api_guard/forms/typings/forms.d.ts
> +} | null;
I don't think the type should include `|null` since 1) It is a bit of a surprise that it is nullable and 2) there is no way to refer to the non-nullable version of this type. 

Please inline the `|null` to the calls sites.

2017-03-14 19:02 UTC, DzmitryShylovich commented on tools/public_api_guard/forms/typings/forms.d.ts
> +} | null;
> It is a bit of a surprise that it is nullable 

surprise for who? everybody who use validators knows that it can return an object or null

> there is no way to refer to the non-nullable version of this type

why? :)

The whole idea of this alias is to reduce boilerplate. Plus users can benefit from it. Otherwise you force users to add `|null` everywhere as well

2017-03-14 19:15 UTC, DzmitryShylovich commented on tools/public_api_guard/forms/typings/forms.d.ts
> +} | null;
it's just an alias. you can you `{[key: string]: any}` if you don't need null in the type or `{[key: string]: any}|null`

2017-03-14 21:09 UTC, IgorMinar approved these changes

2017-03-14 21:20 UTC, IgorMinar commented
I think that this needs a rebase.

I had a similar concern as @mhevery about custom type, but I don't think it's valid since the union type is a proper way to express the nullability of the property and it's less error-prone to do do it this was as opposed to inlining nulls everywhere.

Misko, am I missing anything?

2017-03-15 18:27 UTC, mhevery commented
Hey @DzmitryShylovich  we need this change soon. Could you work on it in the next hour or so?

- [ ] We have to have explicit `ValidationErrors | null` everywhere
- [ ] Rebase

We have discussed this as a team, and our conclusion is that stylistically we would like to have all types not include `null` or `undefined` as it:
- Makes it hard to reason about what is and is not nullable since all types become suspect. So we would like to make sure that no types ever include `null` or `undefined` in its definition.
- It makes it not possible to refer to non-nullable type. since the type name contains nullability.
- Alternatively if the type is nullable it should be clear from name as in `OptionalValidationErrors`. But the word 'optional' implies `undefined` rather than `null`.

2017-03-15 18:35 UTC, DzmitryShylovich commented
>  Could you work on it in the next hour or so?

ok, I'll do, but this is very strange decision :)

2017-03-15 19:03 UTC, DzmitryShylovich commented
@mhevery done

2017-03-15 21:45 UTC, mhevery approved these changes

2017-03-17 20:28 UTC, closed without merging

2017-03-17 20:42 UTC, DzmitryShylovich commented
@mhevery there's an error in the commit message. it should close #14677 instead of #14667