chore: update to yarn 0.21.3
angular/angular pull request #14805
Opened 2017-02-28 17:08 UTC by ocombe

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Build related changes
```

**What is the current behavior?**
We are using an old version of yarn

**What is the new behavior?**
We are using the latest yarn version at the time: 0.21.3

**Does this PR introduce a breaking change?**
```
[x] No
```

**Other information**:
Yarn is also installed locally as a dev dependency but is never used (we always use the global yarn), someone should remove it from package.json and update the shrinkwrap file.

2017-02-28 17:26 UTC, IgorMinar requested changes

2017-02-28 17:31 UTC, IgorMinar commented on package.json
> +    "yarn": ">=0.19.1 <=0.21.3"
<0.22.0

2017-02-28 18:08 UTC, IgorMinar approved these changes

2017-03-01 23:47 UTC, IgorMinar commented
@ocombe ignore the extra commits I pushed to this branch. I'll squash them. I did this just to retrigger travis after the big amazon outage

2017-03-01 23:55 UTC, ocombe commented
By the way you can push empty commits with `git commit --allow-empty` if you just want to trigger travis :)

2017-03-02 07:58 UTC, merged