aio: remove gulp tasks
angular/angular pull request #14889
Opened 2017-03-02 21:19 UTC by petebacondarwin

This is built upon #14868. Only the last commit is specific to this PR.

2017-03-03 07:45 UTC, IgorMinar requested changes
the CI is failing

2017-03-03 07:45 UTC, IgorMinar commented on aio/src/app/shared/link.directive.spec.ts
> +xdescribe('LinkDirective', () => {
don't use `xdescribe` simply remove the second argument from all nested `it`s and you'll get the same effect but the its will be marked as pending rather than disabled.

2017-03-03 07:45 UTC, IgorMinar commented on aio/src/app/navigation/navigation.service.spec.ts
> +  xit('should compute the navigation map', () => {});
just remove the second arg

2017-03-03 07:45 UTC, IgorMinar commented on aio/package.json
> +    "build": "yarn check-env && yarn docs && ng build -prod -aot -sm",
- `-aot` the default

2017-03-03 07:45 UTC, IgorMinar commented on aio/package.json
> +    "pre~~deploy": "yarn check-env && ng build --prod",
is it --prod or -prod?

2017-03-03 08:52 UTC, gkalpak commented on aio/check-env.js
> +});
Why do we need a separate `check-env.js`?
Is it so that we don't rely on stuff outside the `aio/` directory?

2017-03-03 08:52 UTC, gkalpak commented on aio/package.json
> +    "build": "yarn check-env && yarn docs && ng build -prod -aot -sm",
Does it work with single dashes? I thought you needed double dash for non-shortcut options.

2017-03-03 08:52 UTC, gkalpak commented on aio/check-env.js
> +});
BTW, I would prefer if such scripts were not on the root-level. We already have a `scripts/` directory :wink:

2017-03-03 08:52 UTC, gkalpak commented on aio/package.json
> +    "build": "yarn check-env && yarn docs && ng build -prod -aot -sm",
Should we have separate yarn scripts for dev build vs prod build? Or do we always want the prod build?

2017-03-03 08:52 UTC, gkalpak commented on aio/package.json
> +    "deploy-staging": "firebase use staging --token \"$FIREBASE_TOKEN\" && yarn ~~deploy",
Wow! We don't need `run` anymore with yarn? 🕺

2017-03-03 09:13 UTC, petebacondarwin commented on aio/src/app/navigation/navigation.service.spec.ts
> +  xit('should compute the navigation map', () => {});
@IgorMinar  It doesn't work because there is a bug in zone.js:

```
  /**
   * Gets a function wrapping the body of a Jasmine `it/beforeEach/afterEach` block to
   * execute in a ProxyZone zone.
   * This will run in `testProxyZone`. The `testProxyZone` will be reset by the `ZoneQueueRunner`
   */
  function wrapTestInZone(testBody: Function): Function {
    // The `done` callback is only passed through if the function expects at least one argument.
    // Note we have to make a function with correct number of arguments, otherwise jasmine will
    // think that all functions are sync or async.
    return (testBody.length == 0) ? function() {
      return testProxyZone.run(testBody, this);
    } : function(done) {
      return testProxyZone.run(testBody, this, [done]);
    };
  }
```

Note that it doesn't check to see if the function body is defined before reading its length.

2017-03-03 09:14 UTC, petebacondarwin commented on aio/package.json
> +    "build": "yarn check-env && yarn docs && ng build -prod -aot -sm",
Why would be "build" a dev version?
If I am doing development work then I use "ng serve"

2017-03-03 09:15 UTC, petebacondarwin commented on aio/package.json
> +    "pre~~deploy": "yarn check-env && ng build --prod",
From the Angular CLI help usage:

```
--target (String) (Default: development) Defines the build target.
    aliases: -t <value>, -dev (--target=development), -prod (--target=production), --target <value>, --target <value>
```

So it appears to be `-prod`. I'll fix this

2017-03-03 09:16 UTC, petebacondarwin commented on aio/check-env.js
> +});
we don't have a `scripts` folder in `aio/`.
I am cool with moving this to the top level folder.

2017-03-03 09:17 UTC, petebacondarwin commented on aio/package.json
> +    "deploy-staging": "firebase use staging --token \"$FIREBASE_TOKEN\" && yarn ~~deploy",
Yes that is something that `yarn` really got right!

2017-03-03 09:18 UTC, petebacondarwin commented on aio/src/app/shared/link.directive.spec.ts
> +xdescribe('LinkDirective', () => {
There is a bug in zone.js. See my other comment

2017-03-03 10:59 UTC, petebacondarwin commented on aio/src/app/navigation/navigation.service.spec.ts
> +  xit('should compute the navigation map', () => {});
I have a PR for it: https://github.com/angular/zone.js/pull/659
But the zone.js project has problems of its own :-(

2017-03-03 11:27 UTC, petebacondarwin commented
Addressed all comments, rebased on master, aio tasks in the Travis build now pass.

2017-03-03 12:14 UTC, gkalpak commented on aio/package.json
> +    "build": "yarn check-env && yarn docs && ng build -prod -aot -sm",
Point taken :smiley:

2017-03-03 12:16 UTC, gkalpak commented on aio/check-env.js
> +});
Right. We don't have right now. But we will have one when #14330 lands :wink:

2017-03-03 12:19 UTC, gkalpak commented on aio/package.json
> +    "pre~~deploy": "yarn check-env && ng build --prod",
The search results indicate otherwise: [--prod][1] vs [-prod][2]
Could it be a typo in the help message?

[1]: https://github.com/angular/angular-cli/search?utf8=%E2%9C%93&q=--prod&type=Code
[2]: https://github.com/angular/angular-cli/search?utf8=%E2%9C%93&q=-prod&type=Code

2017-03-05 16:19 UTC, IgorMinar commented
@petebacondarwin I rebased your PR and pushed to your branch. I'm about to merge this in if CI passes, so please do not make more changes in this branch

2017-03-05 16:19 UTC, IgorMinar approved these changes

2017-03-05 16:41 UTC, merged