fix(@angular/platform-server): fix get/set title for parse5 adapter
angular/angular pull request #14965
Opened 2017-03-06 21:31 UTC by FrozenPandaz

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

Fixes https://github.com/angular/angular/issues/14936

Currently, setting and getting the title on platform-server is broken and untested.

**What is the new behavior?**

Getting and setting the title will function and be tested

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

2017-03-06 21:31 UTC, FrozenPandaz commented
I'm planning a change which will cache the document's title the first time its retrieved so we dont have to query every time.

2017-03-06 21:32 UTC, DzmitryShylovich commented
They are moving away from parse5 https://github.com/angular/angular/pull/14939

2017-03-06 21:36 UTC, FrozenPandaz commented
@DzmitryShylovich It's an on going discussion

2017-03-06 23:01 UTC, vikerman commented
Hey @DzmitryShylovich  - I've been in sync with @FrozenPandaz and asked him to submit this PR. The PR to move to jsdom is still experimental. We still have to figure out whether it is performant enough. Thanks.

2017-03-06 23:07 UTC, vikerman requested changes
Please fix the commit message to fix(platform-server):...

2017-03-06 23:07 UTC, vikerman commented on modules/@angular/platform-server/src/parse5_adapter.ts
> +    let title = this.querySelector(doc, 'head title');
Can you just query doc.head for title?

2017-03-06 23:07 UTC, vikerman commented on modules/@angular/platform-server/src/parse5_adapter.ts
> +    this.appendChild(this.querySelector(doc, 'head'), title);
doc.head should already be set to the head element

2017-03-06 23:07 UTC, vikerman commented on modules/@angular/platform-server/test/integration_spec.ts
> +          expect(getDOM().getText(title)).toContain('Test');
Can you make it stricter to .toBe('Test') ?

2017-03-06 23:07 UTC, vikerman commented on modules/@angular/platform-server/test/integration_spec.ts
> +    it('adds title to the document', async(() => {
Thanks for adding this integration test!

2017-03-06 23:07 UTC, vikerman commented on modules/@angular/platform-server/test/integration_spec.ts
> +        });
For a more end to end check we should do a PlatformState.renderToString() and make sure the title is rendered

2017-03-06 23:19 UTC, FrozenPandaz commented on modules/@angular/platform-server/test/integration_spec.ts
> +    it('adds title to the document', async(() => {
Then it'll never happen again :)

2017-03-06 23:19 UTC, FrozenPandaz commented on modules/@angular/platform-server/src/parse5_adapter.ts
> +    this.appendChild(this.querySelector(doc, 'head'), title);
I thought so too.. but i was having trouble.. i will double check

2017-03-06 23:20 UTC, FrozenPandaz commented on modules/@angular/platform-server/test/integration_spec.ts
> +        });
Good idea, i think i'll make it a separate it() so we know the difference

2017-03-07 00:42 UTC, vikerman requested changes

2017-03-07 00:42 UTC, vikerman commented on modules/@angular/platform-server/test/integration_spec.ts
> +          getDOM().setTitle(doc, 'Test');
Please use the Title service in the test. That's how we want end users to set the title.

2017-03-07 03:29 UTC, vikerman approved these changes

2017-03-07 03:29 UTC, vikerman commented on modules/@angular/platform-server/test/integration_spec.ts
> +    it('adds title to the document', async(() => {
Can you remove this test? We just want to test public API in the integration test.

2017-03-07 21:33 UTC, vikerman requested changes

2017-03-07 21:33 UTC, vikerman commented on modules/@angular/platform-server/src/parse5_adapter.ts
> +export function parseDocument(html: string): Document {
Please leave the return type as any - since it's a parse5 Document and not the standard TS Document interface,

2017-03-07 21:33 UTC, vikerman commented on modules/@angular/platform-server/src/parse5_adapter.ts
> +  private title: HTMLTitleElement;
Please leave the type of this as any - This is a parse5 Element and not an actual HTMLTitleElement.

2017-03-07 21:42 UTC, vikerman approved these changes

2017-03-10 22:51 UTC, chuckjaz commented
This PR needs to be rebased.

2017-03-10 23:02 UTC, FrozenPandaz commented
rebased

2017-03-12 00:52 UTC, vikerman approved these changes

2017-03-13 20:22 UTC, merged