Standardize source dir
angular/angular pull request #14972
Opened 2017-03-07 01:06 UTC by jasonaden

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-03-07 05:19 UTC, IgorMinar requested changes
- `packages/examples/` and `packages/docs` are not "packages", we should find them a better home.

I still want to take a thorough look at the build.sh changes, but otherwise this looks pretty good!!!

2017-03-07 05:19 UTC, IgorMinar commented on packages/language-service/rollup.config.js
> +console.log('running')
poop

2017-03-07 05:19 UTC, IgorMinar commented on build.sh
> +NODE_TOOLS=(compiler-cli
consider renaming to `NODE_PACKAGES` to prevent confusion with stuff under `/tools`

2017-03-07 05:19 UTC, IgorMinar commented on build.sh
> +downlevelES2015_v2() {
remove `_v2`?

2017-03-07 05:19 UTC, IgorMinar commented on packages/core/tsconfig-build.json
> -    "preserveConstEnums": true
did you drop this option on purpose?

2017-03-08 00:16 UTC, jasonaden commented on packages/language-service/rollup.config.js
> +console.log('running')
👍

2017-03-08 23:19 UTC, mary-poppins commented
The angular.io preview for c8e5030 is available [here][1].

[1]: https://pr14972-c8e503084b6af497007703c0c3c91ae74e3ccc4b.ngbuilds.io/

2017-03-09 00:38 UTC, mary-poppins commented
The angular.io preview for a902ee8 is available [here][1].

[1]: https://pr14972-a902ee85422978711fd98d49d20d86644ee8bc44.ngbuilds.io/

2017-03-09 00:51 UTC, mary-poppins commented
The angular.io preview for bf2e5f4 is available [here][1].

[1]: https://pr14972-bf2e5f4bef548d1d20123ea0071e048ba8dacc04.ngbuilds.io/

2017-03-09 01:21 UTC, mary-poppins commented
The angular.io preview for bd271e8 is available [here][1].

[1]: https://pr14972-bd271e8dd5ad3d6fc8bba43e0fffc4f5aa7f791b.ngbuilds.io/

2017-03-09 01:31 UTC, mary-poppins commented
The angular.io preview for a28fb63 is available [here][1].

[1]: https://pr14972-a28fb63bbeec4d5052acb53cc905375bb885d415.ngbuilds.io/

2017-03-09 01:44 UTC, mary-poppins commented
The angular.io preview for bebedfe is available [here][1].

[1]: https://pr14972-bebedfed24d6fbfa492e97f071e1d1b41e411280.ngbuilds.io/

2017-03-10 19:54 UTC, merged