aio: generate api list json
angular/angular pull request #15018
Opened 2017-03-08 22:25 UTC by petebacondarwin

2017-03-09 07:05 UTC, gkalpak requested changes
I wonder what should happen for params without an `=`. E.g. `x/y?z`. Currently, it would be `{z: undefined}` I think, but maybe `null` would make more sense.

In any case, there should be a test for this.
Other than that LGTM.

2017-03-09 09:35 UTC, petebacondarwin commented
Updated and force pushed after @gkalpak's comments. PTAL

2017-03-09 11:22 UTC, gkalpak commented on aio/src/app/embedded/api/api.service.ts
>      }
This should be rmoved as well. This is also why Travis fails and we get no preview 😞

2017-03-09 11:58 UTC, petebacondarwin commented on aio/src/app/embedded/api/api.service.ts
>      }
Doh!

2017-03-09 12:07 UTC, mary-poppins commented
The angular.io preview for e759a22 is available [here][1].

[1]: https://pr15018-e759a22d83af04c64e76281ade7327b8649273db.ngbuilds.io/

2017-03-09 12:51 UTC, gkalpak approved these changes
LGTM

2017-03-11 18:13 UTC, mary-poppins commented
The angular.io preview for 534f63b is available [here][1].

[1]: https://pr15018-534f63b733195065552ffe7e0743e8e97484013a.ngbuilds.io/

2017-03-12 15:47 UTC, mary-poppins commented
The angular.io preview for 61a9494 is available [here][1].

[1]: https://pr15018-61a9494f69013e1cb043d5fffedbdc4d02d1c2dc.ngbuilds.io/

2017-03-13 20:08 UTC, gkalpak approved these changes

2017-03-13 20:52 UTC, mary-poppins commented
The angular.io preview for 9f9ac61 is available [here][1].

[1]: https://pr15018-9f9ac614835394eb452bc0f8d1cf335e2284faf2.ngbuilds.io/

2017-03-13 23:52 UTC, merged