docs(router): add router event subscription example
angular/angular pull request #15142
Opened 2017-03-14 13:23 UTC by amcdnl

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Other... Please describe: Docs
```

**What is the current behavior?** (You can also link to an open issue here)
No documentation is found for how to subscribe and filter to events.

**What is the new behavior?**
Add documentation for subscribing and filtering events.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-07-14 17:21 UTC, jasonaden requested changes
Thanks for the doc update. One change requested.

2017-07-14 17:21 UTC, jasonaden commented on packages/router/src/router.ts
> +   * You can subscribe to specific events by using
Yes, you're correct this would work, but only if the user has the `filter` operator added to the Observable prototype. The Angular project doesn't add that for you (since there's performance and tree shaking implications of doing so).

Maybe just add a `case` statement to the above showing the same filtering. Or you could also just expand the example to show unsubscribing as well.

2017-07-17 21:50 UTC, jasonaden commented on packages/router/src/router.ts
> +   * You can subscribe to specific events by using
The point is that this code will not work out of the box, therefore we should probably make an example that will.

2017-07-26 17:29 UTC, jasonaden commented
@amcdnl Can you make the update requested?

2017-07-26 17:46 UTC, amcdnl commented
Sorry haven't had time, will try to get to it this week.

2017-12-21 23:40 UTC, jasonaden commented
Closing as this hasn't been updated.

2017-12-21 23:40 UTC, closed without merging