build(aio): copy examples boilerplate
angular/angular pull request #15194
Opened 2017-03-16 01:24 UTC by Foxandxss

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

This PR introduces the `add-example-boilerplate` to the new aio.

It is made with the new changes on the folder structure (AKA no `/ts` folders on the examples) but none of the examples has been touched yet.

The examples right now are a copy & paste and some of them lacks files, others have more files than needed.

So I created a `tools` folder that will host our different tools. For now it is contains a set of `fs` utilities.

Inside the `scripts` folder I created a few `.sh` that we use to set up the environment and a `add-example-boilerplate` node file that will initialize all the examples.

Since this is a fresh start, I am not sure what is the best way to lay down the different tools and scripts, so please if you have a different idea, let's discuss it.

2017-03-16 01:25 UTC, Foxandxss commented
Uhm, I can't launch the node script from the sh like that. I need to run a function.

I probably need to think something else tomorrow.

2017-03-16 01:32 UTC, mary-poppins commented
The angular.io preview for f9120a0 is available [here][1].

[1]: https://pr15194-f9120a095ac79a72614a8e76811d05fca8ce37ff.ngbuilds.io/

2017-03-16 13:03 UTC, Foxandxss commented
I added the remaining changes so this is up for review.

I haven't created yet a script to initialize the project, but there is a `check-env` which doesn't exist that could be a good fit.

2017-03-17 16:11 UTC, petebacondarwin commented on aio/scripts/install.sh
> +fi
We should not be doing these checks here. Use `yarn check-env` instead.

2017-03-17 16:11 UTC, petebacondarwin commented on aio/scripts/examples-install.sh
> +(cd tools/example-boilerplate && node add-example-boilerplate.js add)
what's the point of this script, when it would seem that it is just as easy to do something like `yarn boilerplate:add`?

2017-03-17 16:26 UTC, petebacondarwin requested changes
I might be missing something but I don't see the point of the bash scripts here. They just delegating through to yarn scripts anyway, or could do so easily. Why not use yarn directly?

I note that there is a new yarn.lock in the examples folder. I guess that matches the package.json that is in there already. Good call to lock it down.

But I am confused that we have also a package.json in the boilerplate folder too. Is the whole reason for the package.json in the examples folder only to act as a place to trigger the original node_modules installation before we link the folder into each of the examples? If so do we need to have the script properties in it? Or do we actually use it for running e2e tests across the whole collection of examples?

I note that `/aio/content/examples/protractor.config.js` has some logic in it related to the language of the examples. I expect that this will need to be changed. Are you going to set up e2e testing of the examples in another PR?

All this example stuff needs to be heavily documented: explaining the strategy of each example being able to run as its own mini project; what it means to add the boilerplate - especially the node_modules linking; what the steps are to add or remove boilerplate, and how to run the examples and their tests (both individually and as a collection).

2017-03-17 16:26 UTC, petebacondarwin commented on aio/scripts/install.sh
> +echo "Installation done"
I think this whole script should go. Instead just use `yarn boilerplate:add`, right?

2017-03-17 16:26 UTC, petebacondarwin commented on aio/tools/fs-utils/fsUtils.js
> +}
Is there not some common node library that we can use instead of writing these helper functions ourselves?

2017-03-17 16:26 UTC, petebacondarwin commented on aio/yarn.lock
> +zone.js@0.7.8, zone.js@^0.7.2:
+1

2017-03-17 16:26 UTC, petebacondarwin commented on aio/package.json
> +    "boilerplate:remove": "node ./tools/example-boilerplate/add-example-boilerplate remove"
these two lines look nice and neat.

2017-03-17 16:42 UTC, Foxandxss commented on aio/scripts/install.sh
> +fi
Right. At first I though that `check-env` was empty, then I realized that the tool is in the parent folder. I will remove it from here.

2017-03-17 16:43 UTC, Foxandxss commented on aio/yarn.lock
> +zone.js@0.7.8, zone.js@^0.7.2:
I don't know wh y this happens Pete, first time I use yarn. I just installed a few dependencies with `yarn add foo --dev` and that happened.

2017-03-17 16:44 UTC, Foxandxss commented on aio/tools/fs-utils/fsUtils.js
> +}
Does node include this functions now? I carried this over from angular.io, we have a lot of helpers there for all our scripts. I will check if they are needed or not anymore.

2017-03-17 16:50 UTC, Foxandxss commented
>I might be missing something but I don't see the point of the bash scripts here. They just delegating through to yarn scripts anyway, or could do so easily. Why not use yarn directly?

In angular.io, to setup the entire repo we do a `./scripts/install.sh` so I replicated the same scripts in here.

I actually talked with Ward about how we shall organize the tools and scripts. I guess we can add all the stuff to yarn scripts and create one called `setup`  which will call a few others and do all the basic steps. Setup boilerplate (this one), plunkers and zips.

>I note that there is a new yarn.lock in the examples folder. I guess that matches the package.json that is in there already. Good call to lock it down.

>But I am confused that we have also a package.json in the boilerplate folder too. Is the whole reason for the package.json in the examples folder only to act as a place to trigger the original node_modules installation before we link the folder into each of the examples? If so do we need to have the script properties in it? Or do we actually use it for running e2e tests across the whole collection of examples?

Exactly, the package.json in the examples contains the list of packages that are needed for all the examples. So yes, it is the place to trigger the original node_modules before we link it.

Also yes, those scripts are related with e2e tests. I haven't touch the examples here yet.

> I note that /aio/content/examples/protractor.config.js has some logic in it related to the language of the examples. I expect that this will need to be changed. Are you going to set up e2e testing of the examples in another PR?

That is a copy & paste from our other repo. The e2e needs to be done in another PR and integrated with the angular/angular system. The sole purpose of this PR is to create all the links of node_modules and copy the boilerplate files to the respective places.

> All this example stuff needs to be heavily documented: explaining the strategy of each example being able to run as its own mini project; what it means to add the boilerplate - especially the node_modules linking; what the steps are to add or remove boilerplate, and how to run the examples and their tests (both individually and as a collection).

Yes, that is a good idea. Once we define how we want to setup the whole project, e.g `yarn run setup` we can document it. No problem.

2017-03-17 16:53 UTC, petebacondarwin commented on aio/tools/fs-utils/fsUtils.js
> +}
I meant some 3rd party npm module (like fs-extra etc) rather than a core node library :-)

2017-03-17 17:02 UTC, petebacondarwin commented on aio/yarn.lock
> +zone.js@0.7.8, zone.js@^0.7.2:
It looks like something that you installed had a dependency upon a different version of zone.js, so we all got bumped up.

2017-03-17 17:10 UTC, Foxandxss commented on aio/yarn.lock
> +zone.js@0.7.8, zone.js@^0.7.2:
I don't think so, but I will double check.

Now that I think about it, my PR was originated from master and not aio-master. Perhaps I need rebase.

2017-03-27 17:55 UTC, mary-poppins commented
The angular.io preview for 09a8ee9 is available [here][1].

[1]: https://pr15194-09a8ee9e2cd805b43929259c61bb9879b476fea7.ngbuilds.io/

2017-03-27 17:58 UTC, mary-poppins commented
The angular.io preview for edb1669 is available [here][1].

[1]: https://pr15194-edb16698eaee34c877f6bc1fded436ae0c967246.ngbuilds.io/

2017-03-27 19:44 UTC, petebacondarwin commented on aio/tools/example-boilerplate/add-example-boilerplate.js
> +  if (fs.existsSync(nodePath)) { console.log('here?'); return; }
strange `console.log` message :-)
I don't think we should do this.
Yarn is super quick if everything is already in place, so we should just run yarn even if there is a `node_modules` folder in place already.

2017-03-27 19:47 UTC, petebacondarwin reviewed
Given that we don't have a `aio/tools` folder but we do have a `aio/scripts` folder. Would it not be better to put these files in `aio/scripts`?

2017-03-27 19:54 UTC, petebacondarwin commented on aio/tools/example-boilerplate/add-example-boilerplate.js
> +  const nodeModulesPaths = getNodeModulesPaths(EXAMPLES_PATH);
Would it be simpler to iterate through each example and run `git clean` in that working directory?
Or even easier to just run it at the examples folder level?

2017-03-27 19:55 UTC, petebacondarwin requested changes
@Foxandxss - yes this looks much better. I left some general comments. Only two things to change that block landing this though:

* move the scripts into the scripts folder
* run yarn every time

2017-03-27 20:19 UTC, Foxandxss commented on aio/tools/example-boilerplate/add-example-boilerplate.js
> +  const nodeModulesPaths = getNodeModulesPaths(EXAMPLES_PATH);
Definitely. Now that I know that `git clean` doesn't clean the entire repo.

Addressed.

2017-03-27 20:19 UTC, Foxandxss commented on aio/tools/example-boilerplate/add-example-boilerplate.js
> +  if (fs.existsSync(nodePath)) { console.log('here?'); return; }
Fixed.

2017-03-27 20:28 UTC, petebacondarwin commented on aio/scripts/add-example-boilerplate.js
> +function deleteFiles(baseFileNames, destPaths) {
No longer used?

2017-03-27 20:38 UTC, petebacondarwin approved these changes
LGTM - squash and rebase, then wait for the content update to land.

2017-03-28 15:28 UTC, IgorMinar commented
@Foxandxss can you please rebase this so that we can merge it before it goes stale? thanks!

2017-03-28 15:48 UTC, Foxandxss commented
@IgorMinar done.

Although I discovered some issues that needs to be addressed in the migrator. But this PR cannot be pushed further.

2017-03-28 16:06 UTC, mary-poppins commented
The angular.io preview for 75da1d0 is available [here][1].

[1]: https://pr15194-75da1d0dbd59083e6a274f4de81cd02c540b1cfe.ngbuilds.io/

2017-03-31 07:31 UTC, petebacondarwin commented
I rebased and force pushed this PR

2017-03-31 07:40 UTC, mary-poppins commented
The angular.io preview for b05d5d8 is available [here][1].

[1]: https://pr15194-b05d5d81d565ec4fbb54562fc46aa9c65381dc09.ngbuilds.io/

2017-03-31 08:50 UTC, mary-poppins commented
The angular.io preview for 2311ed0 is available [here][1].

[1]: https://pr15194-2311ed06e20c05ee6b5831e1fd583b55993692b3.ngbuilds.io/

2017-03-31 08:57 UTC, merged