fix(core): ErrorHandler should not rethrow an error by default (#15077)
angular/angular pull request #15208
Opened 2017-03-16 17:08 UTC by mhevery

ErrorHandler can not throw errors because it will unsubscribe itself from
the error stream.

Zones captures errors and feed it into NgZone, which than has a Rx Observable
to feed it into ErrorHandler. If the ErroHandler throws, then Rx will teardown
the observable which in essence causes the ErrorHandler to be removed from the
error handling. This implies that the ErrorHandler can never throw errors.

Closes #14949
Closes #15182
Closes #14316

2017-03-16 17:27 UTC, chuckjaz requested changes

2017-03-16 17:27 UTC, chuckjaz commented on packages/core/src/error_handler.ts
> +   * @deprecated since v4.0 parameter no longer has an effect, as ErrorHandler will never rethrow.
You must leave `@internal` or you will break implementors of this class.

2017-03-16 17:28 UTC, chuckjaz commented on packages/core/src/error_handler.ts
> +   * @deprecated since v4.0 parameter no longer has an effect, as ErrorHandler will never rethrow.
Also the field is not deprecated, the parameter is.

2017-03-16 18:11 UTC, DzmitryShylovich commented on packages/core/src/error_handler.ts
> +   * @deprecated since v4.0 parameter no longer has an effect, as ErrorHandler will never rethrow.
I think you should overload the constructor and deprecate the one with parameter

2017-03-16 18:46 UTC, chuckjaz approved these changes

2017-03-16 19:58 UTC, merged

2017-03-17 22:24 UTC, DzmitryShylovich commented
@chuckjaz @mhevery btw IDE doesn't cross out constructor when parameter is deprecated:
```
class Test {
  constructor(/** @deprecated */ obj?: any) {
  }
}

new Test1(11); // everything is ok
```

but with constructor overload it does
```
class Test {
  constructor();
  /** @deprecated */
  constructor(obj: any);
  constructor(obj?: any) {
  }
}

new Test(11); // constructor is crossed out
```

2017-04-29 14:12 UTC, christianacca commented
Unfortunately https://github.com/angular/angular/issues/14316 is not fixed by this PR