buid(aio): do not render private classes and members
angular/angular pull request #15285
Opened 2017-03-19 08:35 UTC by petebacondarwin

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-03-19 10:53 UTC, mary-poppins commented
The angular.io preview for fd38caa is available [here][1].

[1]: https://pr15285-fd38caaecae7c24f4f1495edd48dff53d279c884.ngbuilds.io/

2017-03-20 10:01 UTC, mary-poppins commented
The angular.io preview for d06de26 is available [here][1].

[1]: https://pr15285-d06de2631313431ecc1e26ebcfe1284d2c697bf1.ngbuilds.io/

2017-03-20 14:03 UTC, gkalpak requested changes
Generally LGTM.
<sub>(AFAICT, PR only partly addresses #15270. The other part would be moving the cheatsheet over, right?)</sub>

2017-03-20 14:03 UTC, gkalpak commented on aio/transforms/angular.io-package/processors/processNavigationMap.js
> +      const url = child.replace(/#\w*$/, ''); // strip hash
Why `/w`? This won't match `-` for example.

2017-03-20 14:03 UTC, gkalpak commented on aio/transforms/angular.io-package/processors/processNavigationMap.js
> +        errors.push({ path: path.join('.'), url});
<sub>😱 Inconsistent spacing 😱 around `{...}` 😱</sub>

2017-03-20 14:03 UTC, gkalpak commented on aio/transforms/angular.io-package/processors/processNavigationMap.js
> +        log.warn('Missing navigation map document (docType="navigation-map"). Did you forget to add it to the readFileProcessor?');
Should this be an error instead of a warning?

2017-03-20 14:03 UTC, gkalpak commented on aio/transforms/angular.io-package/processors/processNavigationMap.js
> +      }
Is it intentional that processing continues even if `navigationDoc` was not found?

2017-03-20 14:03 UTC, gkalpak commented on aio/src/app/navigation/navigation.service.ts
> +    Object.keys(navigation).forEach(key => Array.isArray(navigation[key]) && navigation[key].forEach(node => walkNodes(node)));
This seems a little confusing. A comment about what a non-Array value might be (or why it is OK to expect extra, non-Array values) would help.

2017-03-20 14:43 UTC, petebacondarwin commented on aio/transforms/angular.io-package/processors/filterPrivateDocs.js
> +      return docs.filter(function(doc) { return !doc.name || (doc.name.indexOf('ɵ') !== 0); });
Well, the thing is that there can also be "member" docs that are members of a class.
I was trying to capture those as well...

2017-03-20 14:44 UTC, petebacondarwin commented on aio/transforms/angular.io-package/processors/processNavigationMap.js
> +        log.warn('Missing navigation map document (docType="navigation-map"). Did you forget to add it to the readFileProcessor?');
eventually. but right now we are not stopping the build for this.

2017-03-20 14:45 UTC, petebacondarwin commented on aio/transforms/angular.io-package/processors/processNavigationMap.js
> +      }
I guess I am being too lenient here :-)

2017-03-20 14:46 UTC, petebacondarwin commented on aio/transforms/angular.io-package/processors/processNavigationMap.js
> +      const url = child.replace(/#\w*$/, ''); // strip hash
I am rubbish at regex. Can you suggest a better one?

2017-03-20 14:46 UTC, petebacondarwin commented on aio/transforms/angular.io-package/processors/processNavigationMap.js
> +        errors.push({ path: path.join('.'), url});
Gadzooks!

2017-03-20 14:47 UTC, petebacondarwin commented on aio/src/app/navigation/navigation.service.ts
> +    Object.keys(navigation).forEach(key => Array.isArray(navigation[key]) && navigation[key].forEach(node => walkNodes(node)));
Yeah, you are right.
Actually what I ought to be doing here is extracting the version data and making it available.

2017-03-20 16:35 UTC, petebacondarwin commented on aio/transforms/angular.io-package/processors/processNavigationMap.js
> +      const url = child.replace(/#\w*$/, ''); // strip hash
OK, I am going with the full-on: `/#.*$/`

2017-03-20 16:40 UTC, gkalpak commented on aio/transforms/angular.io-package/processors/filterPrivateDocs.js
> +      return docs.filter(function(doc) { return !doc.name || (doc.name.indexOf('ɵ') !== 0); });
So, this processor and `marlBarredODocsAsPrivate` receive a different `docs` array.
(You can tell I don't know much about the docs-gen pipeline :grin:)

2017-03-20 16:42 UTC, gkalpak commented on aio/transforms/angular.io-package/processors/processNavigationMap.js
> +      }
It will throw errors down the road, when trying to find properties on undefined. The question is, do you want it to throw those errors, or do you want to stop/handle the processing here :smiley:

2017-03-20 16:43 UTC, gkalpak commented on aio/transforms/angular.io-package/processors/processNavigationMap.js
> +      const url = child.replace(/#\w*$/, ''); // strip hash
Since hash is the last part of a URL, `/#.*/` is the first thing that comes to mind.

2017-03-20 17:17 UTC, petebacondarwin commented on aio/transforms/angular.io-package/processors/filterPrivateDocs.js
> +      return docs.filter(function(doc) { return !doc.name || (doc.name.indexOf('ɵ') !== 0); });
I see that you know more than me :-). I'll change this

2017-03-21 06:36 UTC, petebacondarwin commented
@gkalpak I have fixed all of your comments.
Regarding the cheatsheet stuff. The migrator has been modified to bring over the new standalone content page. I was waiting for this PR to land before hitting everyone with an update to the content folder, which would contain numerous file changes.

2017-03-21 06:48 UTC, mary-poppins commented
The angular.io preview for aa099ee is available [here][1].

[1]: https://pr15285-aa099ee6e3a9e77f7e7e78dc3c696e11b26d85fe.ngbuilds.io/

2017-03-21 06:53 UTC, mary-poppins commented
The angular.io preview for f559cf2 is available [here][1].

[1]: https://pr15285-f559cf26a541488eba7d05c7b0129eb95221e2af.ngbuilds.io/

2017-03-21 09:35 UTC, gkalpak requested changes

2017-03-21 09:35 UTC, gkalpak commented on aio/src/app/navigation/navigation.service.ts
> +    const versionInfo = navigationInfo.map(response => response['__versionInfo']).publishReplay(1);
Is this replublishing necessary (given we already have the `navigationInfo` observable)?
Wouldn't the following work just as well:

```ts
private getVersionInfo(navigationInfo: Observable<NavigationResponse>) {
  return navigationInfo.map(response => respons['__versionInfo']);
}
```

2017-03-21 09:35 UTC, gkalpak commented on aio/src/app/navigation/navigation.service.ts
> +    const versionInfo = navigationInfo.map(response => response['__versionInfo']).publishReplay(1);
Is this replublishing necessary (given we already have the `navigationInfo` observable)?
Wouldn't the following work just as well:

```ts
private getVersionInfo(navigationInfo: Observable<NavigationResponse>) {
  return navigationInfo.map(response => respons['__versionInfo']);
}
```

(Same for `getNavigationViews` below.)

2017-03-21 10:58 UTC, petebacondarwin commented on aio/src/app/navigation/navigation.service.spec.ts
> +        ['__versionInfo']: { raw: '4.0.0' }
'cos :-P

2017-03-21 11:11 UTC, petebacondarwin commented on aio/src/app/navigation/navigation.service.spec.ts
> +      const backend = injector.get(ConnectionBackend);
nope

2017-03-21 11:13 UTC, petebacondarwin commented on aio/src/app/navigation/navigation.service.ts
> +export type NavigationResponse = {'__versionInfo': VersionInfo } & { [name: string]: NavigationNode[] };
You're right. It turns out it worked, since we never actually create an explicit instance of this type. But since it is a bit wrong, I have changed it to 

```
export type NavigationResponse = {__versionInfo: VersionInfo } & { [name: string]: NavigationNode[]|VersionInfo };
```

which is not as accurate at describing the type but will work for assignment. You just need to do a little bit more typecasting later, is all.

2017-03-21 11:15 UTC, petebacondarwin commented on aio/src/app/navigation/navigation.service.ts
> +    const versionInfo = navigationInfo.map(response => response['__versionInfo']).publishReplay(1);
If you don't republish then every subscriber will trigger the `map` function again.
Either way, I don't believe this is a significant performance issue for this one.
For the other one, I would rather not be calling the `unpluck` for every subscriber, so I made both published to be consistent.

2017-03-21 11:41 UTC, mary-poppins commented
The angular.io preview for dec731e is available [here][1].

[1]: https://pr15285-dec731e3921bb1936e910a3816a0ba9dc77137b5.ngbuilds.io/

2017-03-21 11:43 UTC, gkalpak approved these changes
LGTM as soon as it LGT Travis.

2017-03-21 11:44 UTC, mary-poppins commented
The angular.io preview for a5038be is available [here][1].

[1]: https://pr15285-a5038be0df500ffd104226fcc5568659f1a99fba.ngbuilds.io/

2017-03-21 11:50 UTC, merged