docs(examples): clarify querying all descendants
angular/angular pull request #15400
Opened 2017-03-22 20:16 UTC by mikeybyker

Updated example to illustrate @ContentChildren default behaviour (only query direct children), and how to query for nested elements/all descendants.
PR Close #14417

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: Example in docs updated
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-03-22 23:16 UTC, vicb commented on packages/examples/core/di/ts/contentChildren/content_children_example.ts
> +  @ContentChildren(Pane, { descendants: true }) allPanes: QueryList<Pane>;
maybe rename:
- `panes` -> `topLevelPanes`
- `allPanes` -> `arbitraryNestedPanes`

to make it even clearer ?

2017-03-22 23:18 UTC, vicb requested changes
Thanks for the PR:
- please consider addressing the feedback,
- update [the spec](https://github.com/angular/angular/blob/master/packages/examples/core/di/ts/contentChildren/e2e_test/content_children_spec.ts)
- squash your commit into a single one.

Thanks !

2017-03-23 12:12 UTC, mikeybyker commented
Requested changes plus the updated spec commited and squashed

2017-03-23 17:15 UTC, vicb commented
Thanks !

2017-03-23 17:15 UTC, vicb approved these changes

2017-03-23 17:18 UTC, DzmitryShylovich commented
duplicated commit message http://prntscr.com/enlaiu

2017-03-23 17:39 UTC, mikeybyker commented
Duplicated messages must have sneaked in when I rebased/squashed commits together, sorry.

2017-03-23 20:01 UTC, vicb commented
@mikeybyker could you amend the commit message please ?

2017-03-23 20:28 UTC, mikeybyker commented
@vicb yes, that's amended now...

2017-03-24 21:36 UTC, vicb commented
Thanks !

2017-03-24 21:36 UTC, merged