feat(aio): add and test FileLoaderService w/ HttpFileLoaderService
angular/angular pull request #15409
Opened 2017-03-23 01:13 UTC by wardbell

Abstracts document fetching to the `FileLoaderService` which may use any technique to fetch the JSON content from the `/contents` folder. 

This implementation use the Angular `HttpModule`.  See closed PR #15407 for alternatives, including the XHR implementation.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-03-23 06:23 UTC, petebacondarwin requested changes

2017-03-23 06:23 UTC, petebacondarwin commented on aio/src/app/documents/document.service.spec.ts
> +        { provide: FileLoaderService, useClass: TestFileLoaderService },
nit: indentation

2017-03-23 06:23 UTC, petebacondarwin commented on aio/src/app/documents/document.service.spec.ts
> +      expect(loader.connectionsArray[0].url).toEqual(CONTENT_URL_PREFIX + 'guide/index.json');
This change is not correct and is probably why the e2e test is failing.
I think that you have been testing against an old version of the JSON files and needed to run `yarn docs`.

We should probably run `yarn docs` as a `pree2e` thing.

2017-03-23 06:25 UTC, petebacondarwin commented on aio/src/app/documents/document.service.ts
> +    return 'docs' + url + '.json';
This change is incorrect. The doc gen now removes all `index.json` files.

2017-03-23 06:40 UTC, petebacondarwin commented on aio/src/app/navigation/navigation.service.ts
> +  const result = { ...obj };
ooh fancy!

2017-03-23 06:54 UTC, petebacondarwin requested changes

2017-03-23 06:54 UTC, petebacondarwin commented on aio/src/app/shared/file-loader.service.spec.ts
> +  });
Why create your own test HTTP implementation, when the library provides one already?

2017-03-23 06:54 UTC, petebacondarwin commented on aio/src/app/shared/file-loader.service.ts
> +    status: number;
Given that we are abstracting above the HTTP service, why are we exposing HTTP specific things, such as status codes (404, etc).

2017-03-23 06:54 UTC, petebacondarwin commented on aio/src/app/shared/file-loader.service.ts
> +    json(): any ;
Is there any situation where a response from this service will not be an object?
It would simplify usage if we dealt with converting from JSON inside the file loader service and then not expose the original response string here.

2017-03-23 06:54 UTC, petebacondarwin commented on aio/src/testing/file-loader.service.ts
> +}
This mock service is basically reimplementing the HTTP mock service.
Which means that all the unit tests are still tied to that interface.
It seems that we should either simplify this mock since the FileLoaderService has no concept of connections - and so update the specs that use it; or just not bother with this mock and continue to use the standard mock Http stuff in our tests.

2017-03-23 07:30 UTC, mary-poppins commented
The angular.io preview for 804b763 is available [here][1].

[1]: https://pr15409-804b7631e18ef9d01987a06f0cc1ea98e1c6f8d7.ngbuilds.io/

2017-03-23 07:35 UTC, wardbell commented on aio/src/app/documents/document.service.spec.ts
> +      expect(loader.connectionsArray[0].url).toEqual(CONTENT_URL_PREFIX + 'guide/index.json');
Nope. It is correct and is NOT why e2e tests fail. That was for other reasons.

2017-03-23 07:36 UTC, wardbell commented on aio/src/app/shared/file-loader.service.ts
> +    status: number;
Because the HTTP status codes are an industry standard way of talking about the conditions that apply regardless of the underlying technology ... whether we use the HttpModule, raw XHR, or webpack.

2017-03-23 07:37 UTC, wardbell commented on aio/src/app/shared/file-loader.service.ts
> +    json(): any ;
I would be happy to consider that. I thought about it and backed off, although I don't remember why.

2017-03-23 07:42 UTC, wardbell commented on aio/src/testing/file-loader.service.ts
> +}
Actually, I did simplify it.
* it doesn't bother with anything but GET
* the `mockRespond` is much simpler
* no `mockError` because you do that easily enough in `mockRespond`

I never looked at the Http mock ... except for the traces of it in the original specs. It was funny how it re-asserted itself as I tried to keep the old specs alive. The features it has now are the features that grew of necessity from the previous specs.

I never loved the word "connections" but that is indeed what happens when you make a doc request. Each request is its own "connection" to the server, going about its merry async business and completing when done. I couldn't think of a better word.

2017-03-23 07:43 UTC, mary-poppins commented
The angular.io preview for 7c31628 is available [here][1].

[1]: https://pr15409-7c31628595fd15f21d2126e0a1749180d22dda40.ngbuilds.io/

2017-03-23 07:45 UTC, wardbell commented on aio/src/app/shared/file-loader.service.spec.ts
> +  });
Had to. Can't use the HTTP remember? The premise of this approach is that it enables us to get rid of the HTTP module (if/when we are ready to do so).

2017-03-23 07:49 UTC, petebacondarwin commented on aio/e2e/app.po.ts
> +    return element.all(by.cssContainingText('aio-nav-item a', searchString)).first();
Ooh I didn't know about this locator!

2017-03-23 07:59 UTC, wardbell commented on aio/src/app/documents/document.service.spec.ts
> +        { provide: FileLoaderService, useClass: TestFileLoaderService },
Fixing

2017-03-23 08:43 UTC, mary-poppins commented
The angular.io preview for 3d0a7b5 is available [here][1].

[1]: https://pr15409-3d0a7b5e91d5948400c3cd1870d72decaa24e816.ngbuilds.io/

2017-03-23 09:24 UTC, Toxicable commented on aio/src/app/shared/file-loader.service.ts
> +    status: number;
Just gonna float this idea here, but what if you swapped it for a websocket backend? that dosen't have status code

2017-03-24 08:37 UTC, petebacondarwin commented
We are not going to merge this as it stands. @wardbell is going to extract the juicy bits from this in another PR. See #15448

2017-03-24 08:37 UTC, closed without merging