fix(core): check for undefined on normalizeDebugBindingValue
angular/angular pull request #15503
Opened 2017-03-26 13:30 UTC by diestrin

DebugServices is parsing false attributes values incorrectly.
Parse5 expects a string value for attributes, but currently boolean is being sent.

Closes #15494

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
#15494 

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

2017-03-26 13:39 UTC, DzmitryShylovich commented on packages/core/src/view/services.ts
> +    return value !== undefined ? value.toString().slice(0, 30) : value;
`value != null`

2017-03-27 22:01 UTC, vikerman requested changes
Can you please add a test to https://github.com/angular/angular/blob/master/packages/platform-server/test/integration_spec.ts ?

2017-03-27 22:48 UTC, tbosch approved these changes
LGTM, once we have a test

2017-03-27 23:03 UTC, diestrin commented
I'll try to add the tests tonight :)

2017-03-28 15:37 UTC, diestrin commented
Unit test added

2017-03-28 18:04 UTC, vikerman approved these changes

2017-03-28 20:33 UTC, merged