feat(ApplicationRef): Allow custom selector in bootstrap
angular/angular pull request #15668
Opened 2017-03-31 14:47 UTC by chrisse27

- fixes #7136

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

In order to bootstrap components on a different selector than the one specified in the declaration one has to currently use the hack as described in #7136. The solution described was a hack in ng 2 and is now in ng 4 even worse. We need a stable solution for this.

**What is the new behavior?**

This PR gives everyone who needs custom selector a well defined place to set this selector or even the concrete element. 

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Use case: We at @comerge need this feature in a setup where ng is integrated into a CMS.

2017-04-11 18:47 UTC, chrisse27 commented
@mhevery or @IgorMinar I know you guys are busy, but could you give me a hint whether my PR has any chance of making into the code base at some point? Thanks a lot in advance!

2017-04-19 13:33 UTC, chrisse27 commented
@vicb Would you maybe have time to look at this?

2017-04-26 15:20 UTC, tbosch commented on packages/core/test/application_ref_spec.ts
> +    function createCustomRootEl(selector: string) {
Could you just change `createRootEl` to take an optional `selector` with default being `bootstrap-app`?

2017-04-26 15:21 UTC, tbosch requested changes
See my comment above.

2017-04-26 15:22 UTC, tbosch commented
Otherwise looks good.

2017-04-26 21:32 UTC, chrisse27 commented on packages/core/test/application_ref_spec.ts
> +    function createCustomRootEl(selector: string) {
Sure. Will update the PR.

2017-04-27 20:58 UTC, chrisse27 commented
@tbosch I incorporated your suggestion. Please consider again.

2017-04-28 17:35 UTC, tbosch approved these changes
Thanks a lot!

2017-04-28 20:23 UTC, chrisse27 commented
Cool, thank you for the review.

2017-04-28 23:10 UTC, closed without merging

2018-02-20 09:42 UTC, chrisse27 commented
@mortenmoulder It's part of Angular 5, just use it. :-)

2018-02-20 09:55 UTC, mortenmoulder commented
@chrisse27 O.. oh. I've looked around for hours and I simply can't see how to do it, then. It doesn't seem like there's any official documentation on it?

2018-02-20 10:46 UTC, mortenmoulder commented
Okay, so I tried something and it actually works.

I created a new `custom.module.ts` file next to my custom component's files. It contains the same things as `app.module.ts` except the routing part. At the bottom of `main.ts`, this was written:

    platformBrowserDynamic().bootstrapModule(AppModule).catch(err => console.log(err));

I then added another one for my new custom component:

    platformBrowserDynamic().bootstrapModule(CustomModule).catch(err => console.log(err));

and then it actually works. I do, however, receive an error in the console:

>ERROR Error: The selector "app-root" did not match any elements

and

>Unhandled Promise rejection: The selector "app-root" did not match any elements ; Zone: <root> ; Task: Promise.then ; Value: Error: The selector "app-root" did not match any elements

Not sure if that's a bug in Angular or my code, but it seems like it works!

2018-04-12 15:00 UTC, jur4ik54 commented
Hi all, can somebody please give a short example how to use the new feature?
I have two components which have to be bootstraped on different places on the website and only if this part of the website is called. I have tried to make two seperate module and bootstrap them with platformBrowserDynamic().bootstrapModule but get an error:  No NgModule metadata found for 'ProsModule'.

Thanks a lot!

Best John

2018-04-12 15:47 UTC, chrisse27 commented
@jur4ik54 Can you provide an example of your approach on stackblitz or plunkr?

2018-04-12 17:24 UTC, jur4ik54 commented
@chrisse27  I would love to but I thinking about how can I do this. I'm not sure if I can reproduce the problem on stackblitz or plunkr. The problem is it's a clients .net mvc application where the frontend is based on plain javascript. The plan is to litle by litle move the frontend to angular. We have two components, which are placed in different views. The current approach is working with ngdobootstrap, where we have one module and two components which we set to "entryComponents". The problem with this approach is that the constructor of component A would be called twice of e.g. component A if we navigate from view A, where component A was bootstrapped, to view B where component B will be bootstrapped. All the inputs of component A would be reseted if they were set before navigation from view A to view B. Therefore we thought about creating two seperate modules which one component each and use platformBrowserDynamic().bootstrapModule for each module in the main.ts file. But we get an error with metadata. I'm not sure where to use the feature you have introduced :(
Thanks a lot

John

2018-04-13 10:48 UTC, chrisse27 commented
@jur4ik54 Thanks for the explanation. I still think you should provide a Plunkr / Stackblitz example. I'd be happy to have a look at it.