feat(aio): code block styles with header
angular/angular pull request #15735
Opened 2017-04-03 19:48 UTC by sjtrimble

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-04-10 12:49 UTC, petebacondarwin commented on aio/src/app/embedded/code/code-example.component.ts
> +    </aio-code>
we can do this more simply with a single element:

```html
<aio-code [class.headed-code]="title" [class.simple-code]="!title" [code]="code" [language]="language" [linenums]="linenums"></aio-code>
```

2017-04-10 12:53 UTC, petebacondarwin requested changes

2017-04-10 12:53 UTC, petebacondarwin commented on aio/src/app/embedded/code/code-example.component.ts
> +    </aio-code>
or possibly `ngClass`:

```html
<aio-code [ngClass]="{'headed-code':title, 'simple-code':!title}" [code]="code" [language]="language" [linenums]="linenums"></aio-code>
```

2017-04-10 12:54 UTC, petebacondarwin commented
Also these changes seem to have broken the unit tests, which you can check locally with `yarn test`

2017-04-10 19:45 UTC, sjtrimble commented
@petebacondarwin thanks! I used ngClass like you recommended. I wasn't able to figure out yarn test (yarn test v0.21.3 | error Command "test" not found) so I may need some help there.

2017-04-10 19:53 UTC, mary-poppins commented
The angular.io preview for 4b88a97 is available [here][1].

[1]: https://pr15735-4b88a97731d55771d95080fd9218d9c1f90ffe33.ngbuilds.io/

2017-04-11 21:16 UTC, petebacondarwin approved these changes

2017-04-12 13:29 UTC, merged