fix(ci): fix #15785, travis script should load project root dir dynamically
angular/angular pull request #15786
Opened 2017-04-05 11:37 UTC by JiaLiPassion

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
#15785 

**What is the new behavior?**

I can run ci test with my own travis account.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-04-11 11:28 UTC, gkalpak requested changes

2017-04-11 11:28 UTC, gkalpak commented on scripts/ci/env.sh
> +  export NGBUILDS_IO_KEY=${NGBUILDS_IO_KEY:-$SAUCE_ACCESS_KEY}
This change is not valid. It is important that this bit happens _before_ setting `SAUCE_ACCESS_KEY` in this script.

2017-04-11 17:40 UTC, JiaLiPassion commented on scripts/ci/env.sh
> +  export NGBUILDS_IO_KEY=${NGBUILDS_IO_KEY:-$SAUCE_ACCESS_KEY}
@gkalpak , thank you for you review, but if I change the NGBUILDS_IO_KEY before SAUCE_ACCESS_KEY definition, it will report error that SAUCE_ACCESS_KEY is unbound value, I will do more research, if you have some information why the NGBUILDS_IO_KEY must before SAUCE_ACCESS_KEY and why it is work in angular build, please tell me, thank you.

2017-04-12 09:57 UTC, gkalpak commented on scripts/ci/env.sh
> +  readonly SAUCEKEY=${SAUCE_ACCESS_KEY:-}
If I understand correctly, the issue when running travis on your own fork is that you don't have a `SAUCE_ACCESS_KEY` travis env var, right?
How does this line help? Wouldn't it overwrite `SAUCEKEY` the next time that `env.sh` is called (by which point `SAUCE_ACCESS_KEY` will be defined)?

2017-04-12 15:48 UTC, JiaLiPassion commented on scripts/ci/env.sh
> +  readonly SAUCEKEY=${SAUCE_ACCESS_KEY:-}
@gkalpak , yes, the issue is in line 78, NGBUILDS_IO_KEY try to use $SAUCE_ACCESS_KEY, and report unbound var.
this added line only prevent this unbound error.  So if next time SAUCE_ACCESS_KEY was updated, I believe it will use the updated one

And I am not sure I fully understand why the script use SAUCE_ACCESS_KEY before it was set later.

And change it this way, I can run travis build with my own travis account.

2017-04-13 17:58 UTC, gkalpak commented on scripts/ci/env.sh
> +  readonly SAUCEKEY=${SAUCE_ACCESS_KEY:-}
I see. I wonder if it would be less noisy to do it like this:

```
# Avoid "unbound variable" error in case `SAUCE_ACCESS_KEY` is not set (e.g. on a fork).
SAUCE_ACCESS_KEY=${SAUCE_ACCESS_KEY:-}
...
```

##
> And I am not sure I fully understand why the script use SAUCE_ACCESS_KEY before it was set later.

Long story :smiley: It's a hack to work around some artificial Travis limitation and use JWT for our own service (the preview server). Quoting [aio-builds-setup docs][1]:

> Travis does only allow specific whitelisted property names to be used with the JWT addon. The only known such property at the time is `SAUCE_ACCESS_KEY` (used for integration with SauceLabs). In order to be able to actually use the JWT addon we had to name the encrypted variable `SAUCE_ACCESS_KEY` (which we later re-assign to `NGBUILDS_IO_KEY`).

[1]: https://github.com/angular/angular/blob/3bb5990/aio/aio-builds-setup/docs/overview--security-model.md

2017-04-13 19:07 UTC, JiaLiPassion commented on scripts/ci/env.sh
> +  readonly SAUCEKEY=${SAUCE_ACCESS_KEY:-}
@gkalpak ，thank you for the detailed explanation, I will modify it as you suggested.

2017-05-24 06:39 UTC, JiaLiPassion commented on scripts/ci/env.sh
> +  readonly SAUCEKEY=${SAUCE_ACCESS_KEY:-}
@gkalpak, I have updated this PR, please review, thank you very much.

2017-05-24 14:07 UTC, gkalpak reviewed
LGTM (with one question).
cc @IgorMinar

2017-05-24 14:07 UTC, gkalpak commented on scripts/ci/env.sh
> +readonly projectRoot=$(cd ${thisDir}/../..; pwd)
Why a new var? Can't we use `$PROJECT_ROOT` below?

2017-05-24 15:23 UTC, JiaLiPassion commented on scripts/ci/env.sh
> +readonly projectRoot=$(cd ${thisDir}/../..; pwd)
@gkalpak, I have modified this one, please review.

2017-05-24 16:11 UTC, gkalpak commented
LGTM as soon as CIs are green. You need to update the commit message to follow the guidelines. E.g. something like:

> ci: allow CI scripts to run on forks
>
> Fixes #15785

2017-05-24 16:23 UTC, JiaLiPassion commented
@gkalpak , thank you, I have updated the commit message. Please review.

2017-05-24 16:35 UTC, gkalpak approved these changes

2017-05-24 16:36 UTC, gkalpak commented
This needs to be approved by @IgorMinar or @mhevery.

2017-12-05 23:26 UTC, IgorMinar requested changes
I don't mind the other changes. But It's almost impossible for us to guarantee that we will not break this in the future.

We typically expect that if you want to run CI tests you just send us a PR. For example the aio preview server will never work when CI is running on a private fork.

2017-12-05 23:26 UTC, IgorMinar commented on scripts/ci/env.sh
> +  SAUCE_ACCESS_KEY=${SAUCE_ACCESS_KEY:-}
I'm not sure if this is the right change. even on private forks, you'll need to specify some valid key otherwise the authentication will fail.

2017-12-09 16:27 UTC, JiaLiPassion commented on scripts/ci/env.sh
> +  SAUCE_ACCESS_KEY=${SAUCE_ACCESS_KEY:-}
@IgorMinar ,got it, I will try to modify the script.

2018-02-08 23:33 UTC, IgorMinar commented
@JiaLiPassion can we just close this? I don't think that we want to support travis forks, especially considering that we are slowly moving most of the jobs to circle ci.

2018-02-12 23:32 UTC, closed without merging