WIP feat(aio): about page
angular/angular pull request #15914
Opened 2017-04-12 06:52 UTC by sjtrimble

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-04-12 07:01 UTC, mary-poppins commented
The angular.io preview for cabf32c is available [here][1].

[1]: https://pr15914-cabf32cea53ae99235aaed4412e249815d33731f.ngbuilds.io/

2017-04-12 21:37 UTC, mary-poppins commented
The angular.io preview for 0d1f773 is available [here][1].

[1]: https://pr15914-0d1f773db196a879d3e798f56271de600ec9737e.ngbuilds.io/

2017-04-12 21:47 UTC, mary-poppins commented
The angular.io preview for 432391a is available [here][1].

[1]: https://pr15914-432391ae2ce6a80807fa9078b1838c99de74faea.ngbuilds.io/

2017-04-13 01:37 UTC, mary-poppins commented
The angular.io preview for 8e95783 is available [here][1].

[1]: https://pr15914-8e95783375a307cdfe55f252a633e642c4f9fa7b.ngbuilds.io/

2017-04-13 02:01 UTC, mary-poppins commented
The angular.io preview for 1f4abfe is available [here][1].

[1]: https://pr15914-1f4abfe98c4f07ed5293d20a0e92bcd17532545c.ngbuilds.io/

2017-04-14 19:58 UTC, petebacondarwin submitted a review, later dismissed
Along with my other comments, the CircleCI test is failing due to invalid commit messages and the Travis failures appear to be due to linting errors in the code.

Perhaps it would be best to just squash all the commits?
And you can check the linting by running `yarn lint` I think.

2017-04-14 19:58 UTC, petebacondarwin commented on aio/content/marketing/index.html
> +    <div class="cta-bar"><a href="/docs/ts/latest/quickstart.html" md-button="md-button" class="button button-large button-shield mat-raised mat-primary">Get Started</a></div>
The URL here is incorrect. I think it should be simply: `guide/quickstart`. For example: https://aio-staging.firebaseapp.com/guide/quickstart

2017-04-14 19:58 UTC, petebacondarwin commented on aio/src/app/embedded/contributor/contributor-list.component.ts
> +    console.log('selectedGroup: ', this.selectedGroup);
Can we remove these console logs now that you are happy that it works?

2017-04-14 19:58 UTC, petebacondarwin commented on aio/src/app/embedded/contributor/contributor.component.ts
> +            <div *ngIf="person.picture" class="contributor-image" [style.background-image]="'url('+pictureBase+person.picture+')'">
Why use a background image rather than an image tag?
Doesn't this impact accessibility?

2017-04-14 19:58 UTC, petebacondarwin commented on aio/src/app/embedded/contributor/contributor.component.ts
> +        console.log('Flipped Status: ', this.person.isFlipped);
Let's remove the logging. It must only have been used to debug during development.

2017-04-14 19:58 UTC, petebacondarwin commented on aio/src/app/embedded/contributor/contributor.component.ts
> +import { DomSanitizer, SafeResourceUrl, SafeUrl} from '@angular/platform-browser';
these don't appear to be used

2017-04-14 19:58 UTC, petebacondarwin commented on aio/src/app/embedded/contributor/contributor.component.ts
> +import { Pipe, PipeTransform } from '@angular/core';
these don't appear to be used either

2017-04-15 06:19 UTC, sjtrimble commented on aio/src/app/embedded/contributor/contributor.component.ts
> +            <div *ngIf="person.picture" class="contributor-image" [style.background-image]="'url('+pictureBase+person.picture+')'">
In order to get a centered round image (from a square or rectangular image of any size).

2017-04-15 06:25 UTC, sjtrimble commented
@petebacondarwin I squashed the commits and cleaned up the code.

2017-04-15 09:28 UTC, petebacondarwin commented
Sorry @sjtrimble - it still fails `yarn lint`: https://travis-ci.org/angular/angular/jobs/222292909#L972

2017-04-15 12:11 UTC, gkalpak commented on aio/content/marketing/contributors.json
> +    "group": "Angular"
OOC, where did these changes come from?

2017-04-15 16:29 UTC, petebacondarwin commented
@sjtrimble - also this conflicts in a big way with @wardbell's recent PR which we merged this weekend. Can you work with him to sort this out. For instance, he is sorting the contributor groups alphabetically, rather than by a hard coded order.

2017-04-16 09:16 UTC, sjtrimble commented on aio/content/marketing/contributors.json
> +    "group": "Angular"
Jules requested we change the groups to Angular, GDE and Community. Something new :) We'll need to add all of the GDEs as most are not currently there.

2017-04-16 09:17 UTC, sjtrimble commented
@petebacondarwin @wardbell This functionality is what was discussed with Jules which should remain. The alphabetical order should only apply within a selected group (i.e. Angular team members can be alphabetized).

2017-04-16 23:46 UTC, wardbell commented
@sjtrimble I rebased and merged it with the changes I had made to the contributors before you got started. Should be good to go.

One thing in your department: the bio card chops off the bottom of the name. And I don't love centered for anything but very short text. Are you sure about that?
![image](https://cloud.githubusercontent.com/assets/129061/25075220/3c5c4534-22c4-11e7-836c-510ceb245cce.png)

2017-04-16 23:52 UTC, wardbell requested changes
See my concerns about formatting of the bio card.
Otherwise LGTM

2017-04-16 23:56 UTC, mary-poppins commented
The angular.io preview for 0a54f16b4ebc7d359bc988b62aa368cc1f8f2181 is available [here][1].

[1]: https://pr15914-0a54f16b4ebc7d359bc988b62aa368cc1f8f2181.ngbuilds.io/

2017-04-17 01:44 UTC, sjtrimble reviewed
We have links changed here that should remain as google.com, no?

2017-04-17 06:59 UTC, petebacondarwin commented on aio/content/marketing/index.html
> +>>>>>>> feat(aio): about page styles
There is an unresolved conflict here.

2017-04-17 07:02 UTC, petebacondarwin commented on aio/src/app/embedded/contributor/contributor.service.spec.ts
> +      "website": "https://Angular.com/+IgorMinar",
this doesn't affect the app, because it is only test data but, yes, this should be google not Angular

2017-04-17 07:02 UTC, petebacondarwin commented on aio/src/app/embedded/contributor/contributor.service.spec.ts
> +      "website": "https://Angular.com/+IgorMinar",
And similarly below

2017-04-17 07:03 UTC, petebacondarwin submitted a review, later dismissed
Fix the merge conflict

2017-04-17 16:42 UTC, wardbell commented on aio/src/app/embedded/contributor/contributor.service.spec.ts
> +      "website": "https://Angular.com/+IgorMinar",
LOL about the test data. My search and replace of "google" by "Angular" was a bit aggressive.

2017-04-17 17:56 UTC, mary-poppins commented
The angular.io preview for 147434645f1b446ae8a88cd3875d675fbcd74a35 is available [here][1].

[1]: https://pr15914-147434645f1b446ae8a88cd3875d675fbcd74a35.ngbuilds.io/

2017-04-18 00:39 UTC, wardbell approved these changes

2017-04-18 00:43 UTC, merged