feat(aio): implement resources with resources.json
angular/angular pull request #15950
Opened 2017-04-13 07:39 UTC by wardbell

Converts "Resources" from angular.io

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

2017-04-13 07:49 UTC, mary-poppins commented
The angular.io preview for 13ec2fb is available [here][1].

[1]: https://pr15950-13ec2fba5482991234c0080fc5cd7b8308f21456.ngbuilds.io/

2017-04-13 08:32 UTC, gkalpak reviewed
I didn't look at the CSS/styling, but the rest looks good :+1:

2017-04-13 08:32 UTC, gkalpak commented on aio/src/app/embedded/contributor/contributor-list.component.ts
> +  subscription: Subscription;
Is this initialized anywhere?

2017-04-13 08:32 UTC, gkalpak commented on aio/src/app/embedded/resource/resource-list.component.ts
> +    window.addEventListener('scroll', this.scrollHandler );
Couldn't we use `@HostListener` (which theoretically should be more platform-server friendly?

Does `@HostListener` take care of cleaning up on destroy?

2017-04-13 10:14 UTC, petebacondarwin commented on aio/src/app/embedded/contributor/contributor-list.component.ts
> +  subscription: Subscription;
No it needs to be done on line 23 below.

2017-04-13 10:15 UTC, petebacondarwin commented on aio/src/app/embedded/resource/resource-list.component.html
> +          <h2 class="text-headline text-uppercase">{{category.title}}</h2>
I know this was probably copied from angular.io but this kind of non-semantic CSS class (`text-uppercase`) infuriates me :-)

2017-04-13 10:22 UTC, petebacondarwin commented on aio/src/app/embedded/resource/resource-list.component.html
> +  <div class="c3">
We ought to find a way to generalize this floating side navigator. It would be great to use in the rest of the docs, especially for longish guides.
I had a thought that we could catch the scroll position change (perhaps debounced) in the DocViewerComponent and then provide this navigator as a component that actually exists outside the doc being rendered. Somehow getting its list of links from the doc being rendered...

2017-04-13 10:23 UTC, petebacondarwin commented on aio/src/app/embedded/resource/resource-list.component.ts
> +  categories: Observable<Category[]>;
In the `ContributorListComponent` we have switched to handling the observable in the component rather than using the `async` pipe. Should we be consistent and do the same here?

2017-04-13 10:24 UTC, petebacondarwin commented on aio/src/app/embedded/resource/resource-list.component.ts
> +    window.addEventListener('scroll', this.scrollHandler );
I believe you are right in both cases here, @gkalpak.

2017-04-13 16:21 UTC, wardbell commented on aio/src/app/embedded/resource/resource-list.component.ts
> +    window.addEventListener('scroll', this.scrollHandler );
Yes ... I woke up this morning with that fix on my mind. Just spaced-out when I wrote this last night.

2017-04-13 16:22 UTC, wardbell commented on aio/src/app/embedded/resource/resource-list.component.html
> +          <h2 class="text-headline text-uppercase">{{category.title}}</h2>
I did copy it. Please offer an improvement. @sjtrimble wants to hear your thoughts :)

2017-04-13 16:23 UTC, wardbell commented on aio/src/app/embedded/resource/resource-list.component.html
> +  <div class="c3">
I agree that we should look at that.  Would be nice to get it working at all. Then we can create something like this from a formalized TOC on each page.

2017-04-13 16:30 UTC, wardbell commented on aio/src/app/embedded/resource/resource-list.component.ts
> +  categories: Observable<Category[]>;
We switched didn't use `async` pipe because we currently sort/sub-select the contributors within the component.  If/when I do some magic in the `contributor.service` along the lines of what I do here in the `resources.service`, we can simplify the component and use `async` pipe. 

I suspect we will tackle that in a near-future PR given that the current, almost random listing of names is likely to draw critical attention.

2017-04-13 17:40 UTC, wardbell commented on aio/src/app/embedded/contributor/contributor-list.component.ts
> +  subscription: Subscription;
Changing to only subscribe once to get the contribs and then completes. A simple pattern

2017-04-13 17:46 UTC, mary-poppins commented
The angular.io preview for 6d9d00e is available [here][1].

[1]: https://pr15950-6d9d00e628162b833eb5b5f4c6e200a54640fb56.ngbuilds.io/

2017-04-13 17:53 UTC, mary-poppins commented
The angular.io preview for cfeec2b is available [here][1].

[1]: https://pr15950-cfeec2bb9e99a5e0c41bd6c5b9e64152c7c5ca71.ngbuilds.io/

2017-04-13 17:53 UTC, wardbell commented on aio/src/app/embedded/contributor/contributor-list.component.ts
> +  subscription: Subscription;
Upon further reflection, I'm going with the `first()` pattern which is this simplest, safe thing for cases where we just want the initial json and we're done. Modified both `contributor-list` and `resource-list` accordingly.

2017-04-13 18:02 UTC, mary-poppins commented
The angular.io preview for 743b6e4 is available [here][1].

[1]: https://pr15950-743b6e43aea5fe22bdca2746efe3c57cb0c911df.ngbuilds.io/

2017-04-14 20:40 UTC, petebacondarwin requested changes
This look much better than before, with the use of `hostListener` etc.
I can live with the `first()` being there even though I believe it is redundant.
My main problem is that on the preview the floating contents list is position in a strange place and doesn't appear to stay in view when you scroll down...

![screen shot 2017-04-14 at 21 38 00](https://cloud.githubusercontent.com/assets/15655/25055466/e1134ff2-215a-11e7-9036-0349b4058ccb.png)

We ought to be able to concoct an e2e test that checks that this is visible when we have scrolled to the bottom of the page.

2017-04-14 20:40 UTC, petebacondarwin commented on aio/src/app/embedded/contributor/contributor-list.component.ts
> +    this.contributorService.contributors.first().subscribe(cgs => {
Actually I don't think you need the `first()` here, since the `contributors` observable only ever emits one value and then completes, right? So the first doesn't give you anything. Same for the `categories` observable below I believe.

2017-04-15 05:41 UTC, wardbell commented on aio/src/app/embedded/contributor/contributor-list.component.ts
> +    this.contributorService.contributors.first().subscribe(cgs => {
You're right! I misremembered. I added tests that confirm that complete is called for both the `ContributorService` and the `ResourceService`.

2017-04-15 05:42 UTC, wardbell commented
Added tests (see commit message). Ready to ship?

2017-04-15 05:51 UTC, petebacondarwin approved these changes

2017-04-15 05:55 UTC, mary-poppins commented
The angular.io preview for e5ef243 is available [here][1].

[1]: https://pr15950-e5ef243e42c9909e693046f2e8f6435179d7b629.ngbuilds.io/

2017-04-15 05:59 UTC, mary-poppins commented
The angular.io preview for c4a03bd is available [here][1].

[1]: https://pr15950-c4a03bd6af4c26bb95ee651bd0c9280ce5510cef.ngbuilds.io/

2017-04-15 10:05 UTC, mary-poppins commented
The angular.io preview for d549a29 is available [here][1].

[1]: https://pr15950-d549a2976d153cb9884761de46de7c05ec1da442.ngbuilds.io/

2017-04-15 15:53 UTC, merged