build(aio): IDEs should only parse the `src` files
angular/angular pull request #16039
Opened 2017-04-16 19:07 UTC by petebacondarwin

I found that VS Code was taking an age to bring up the intellisense
for TypeScript source files in the `aio/src` folder.
I believe that this is because it was trying to parse all the files in
the `aio/content/examples` folder as well, which is not relevant to the
web app development.

This change restricts the root `aio/tsconfig.json` to only the `aio/src`
folder.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-04-16 19:19 UTC, wardbell approved these changes
I like it if it works. We can rescind/amend if it doesn't

2017-04-16 19:22 UTC, wardbell requested changes
It sounds good and we have to solve the problem but this approach prevents VS Code from looking at `/e2e` and `/tools` which both have `.ts` files.

Would it work if we add those folders to the `include`?

What about `/scripts` and `/transforms`?  They aren't presently written with TS. But perhaps they should be and will be someday.

2017-04-16 19:32 UTC, petebacondarwin commented
I would be happy to include `e2e`, not sure about `tools`. The problem there is that I believe that `tools/examples/shared` ends up with a `node_modules` folder. Not sure if this would also be parsed...

Once my authoring PR lands I am going to move `transforms` into `tools` - so that removes that question.

For sure one could open VS Code up focussed on the `tools` folder, perhaps?

2017-04-17 23:16 UTC, wardbell approved these changes

2017-04-17 23:36 UTC, wardbell requested changes

2017-04-17 23:36 UTC, wardbell commented on aio/tsconfig.json
> +  "include": [
I really think it should be this for now:
```
    "include": [
      "src",
      "e2e",
      "tools/examples/shared/protractor-helpers.ts"
    ]
```

2017-04-18 01:11 UTC, wardbell commented
@petebacondarwin I pushed two commits that do the trick ... thanks to @Foxandxss.

2017-04-18 01:12 UTC, wardbell approved these changes

2017-04-18 01:20 UTC, mary-poppins commented
The angular.io preview for decdf0e27bb09878dc0fd21868b7357b0926bd37 is available [here][1].

[1]: https://pr16039-decdf0e27bb09878dc0fd21868b7357b0926bd37.ngbuilds.io/

2017-04-18 09:10 UTC, gkalpak approved these changes

2017-04-18 09:10 UTC, gkalpak commented on aio/tsconfig.json
> +    "tools"
I would consider adding `aio-builds-setup` and maybe `node_modules` here too.

2017-04-18 12:29 UTC, petebacondarwin commented on aio/tsconfig.json
> +    "tools"
I agree!

2017-04-18 15:20 UTC, IgorMinar commented on aio/tsconfig.json
> +    "tools"
a better solution is to remove `exclude` block altogether and instead add `files` block and specify entry points to the app explicitly. That way only stuff reachable from the entry points is crawled by the language service

2017-04-18 15:33 UTC, petebacondarwin commented on aio/tsconfig.json
> +    "tools"
Hmm, so we would need:

```
files: [
  "src/main.ts",
  "src/test.ts".
  "e2e/*.spec.ts"
]
```

Anything else?
Does that actually work?

2017-04-19 06:57 UTC, petebacondarwin commented on aio/tsconfig.json
> +    "tools"
Using `files` does not work. It fails the production build.
I could not work out what set of files needed to be included so I am going to go with excluding the main problematic folders for now.

2017-04-19 07:26 UTC, gkalpak commented on aio/tsconfig.json
> +    "tools"
Note that this file is not really used for building. It is extended by `src/tsconfig.app.json`, `src/tsconfig.spec.json` and `e2e/tsconfig.e2e.json`, so whatever change we make here it needs to be compatible with these.

2017-04-19 07:30 UTC, mary-poppins commented
The angular.io preview for 4a95e5b6513c87cd5578dbc4b8c6f5d7786e4c3d is available [here][1].

[1]: https://pr16039-4a95e5b6513c87cd5578dbc4b8c6f5d7786e4c3d.ngbuilds.io/

2017-04-19 07:31 UTC, mary-poppins commented
The angular.io preview for 16b95b0d864a2b2a15a43c4448e9b6f81e34c045 is available [here][1].

[1]: https://pr16039-16b95b0d864a2b2a15a43c4448e9b6f81e34c045.ngbuilds.io/

2017-04-19 07:36 UTC, merged