feat(aio): set the document title in the browser title
angular/angular pull request #16031
Opened 2017-04-16 10:54 UTC by petebacondarwin

2017-04-16 11:07 UTC, mary-poppins commented
The angular.io preview for e81f63e65bfe65a190c87025cfdc990b4ace3bb3 is available [here][1].

[1]: https://pr16031-e81f63e65bfe65a190c87025cfdc990b4ace3bb3.ngbuilds.io/

2017-04-16 11:31 UTC, Foxandxss requested changes
Other things than docs gives undefined.

2017-04-16 11:52 UTC, petebacondarwin commented
Good point. I'll fix it up

2017-04-16 11:53 UTC, petebacondarwin commented
By ensuring `doc.title` is never undefined

2017-04-16 19:55 UTC, mary-poppins commented
The angular.io preview for 3f51460462268f5ecdb55960352b094ad6f637ae is available [here][1].

[1]: https://pr16031-3f51460462268f5ecdb55960352b094ad6f637ae.ngbuilds.io/

2017-04-16 21:48 UTC, mary-poppins commented
The angular.io preview for d35abaa468ef2407ae6d2c67d96cdddd9753014d is available [here][1].

[1]: https://pr16031-d35abaa468ef2407ae6d2c67d96cdddd9753014d.ngbuilds.io/

2017-04-18 01:29 UTC, wardbell approved these changes
LGTM

2017-04-18 07:10 UTC, gkalpak commented on aio/tools/transforms/angular.io-package/processors/convertToJson.js
> +            contents = contents.replace(/<h1[^>]*>(.+?)<\/h1>/, (outerHeading, innerHeading) => {
Why `replace` when you are not actually replacing it? I assume it is a left-over from a previous implementation that _did_ replace it.

2017-04-18 09:44 UTC, petebacondarwin commented on aio/tools/transforms/angular.io-package/processors/convertToJson.js
> +            contents = contents.replace(/<h1[^>]*>(.+?)<\/h1>/, (outerHeading, innerHeading) => {
you're right. I'll change that

2017-04-18 10:00 UTC, petebacondarwin commented
@gkalpak PTAL

2017-04-18 10:19 UTC, gkalpak approved these changes
LGTM

2017-04-18 10:19 UTC, gkalpak commented on aio/tools/transforms/angular.io-package/processors/convertToJson.spec.js
> +    const docs = [ { docType: 'test-doc' }];
Consistently inconsistent spacing (`[ {` vs `}]`).
<sub>(Which is way better than inconsistently inconsistent spacing, but still... 😛 </sub>

2017-04-18 12:25 UTC, petebacondarwin commented on aio/tools/transforms/angular.io-package/processors/convertToJson.spec.js
> +    const docs = [ { docType: 'test-doc' }];
:-(

2017-04-18 15:55 UTC, mary-poppins commented
The angular.io preview for e83c09e964ff584f66ae08562e7999792d9a2b88 is available [here][1].

[1]: https://pr16031-e83c09e964ff584f66ae08562e7999792d9a2b88.ngbuilds.io/

2017-04-18 22:20 UTC, merged