build(aio): ability to generate zips
angular/angular pull request #16043
Opened 2017-04-16 21:50 UTC by Foxandxss

This gives zippers to AIO. The last piece of tooling (for now :P)

It is made with a customizer which basically creates a package.json on the fly for each type of example.

2017-04-16 22:03 UTC, mary-poppins commented
The angular.io preview for 92efa26aaa42a13c0c16c50489f166b5fd226101 is available [here][1].

[1]: https://pr16043-92efa26aaa42a13c0c16c50489f166b5fd226101.ngbuilds.io/

2017-04-17 12:11 UTC, petebacondarwin commented
This all looks pretty cool! My main gripe is the complete lack of tests.
I know it seems difficult but it will pay dividends in the long run.

2017-04-17 12:23 UTC, petebacondarwin requested changes
Minor comments but it really needs tests

2017-04-17 12:23 UTC, petebacondarwin commented on aio/tools/example-zipper/customizer/package-json/packageJsonCustomizer.js
> +    this.dependenciesPackageJson = JSON.parse(fs.readFileSync(path.join(__dirname, '../../../examples/shared//package.json')));
Can you have a constant that is something like: `const examplesPath = path.resolve(__dirname, '../../../examples');`?

2017-04-17 12:23 UTC, petebacondarwin commented on aio/tools/example-zipper/customizer/package-json/packageJsonCustomizer.js
> +    let packageJson = JSON.parse(fs.readFileSync(`${__dirname}//package.json`));
Unnecessary double slash. In fact it is safer to use `path.resolve` here

2017-04-17 12:23 UTC, petebacondarwin commented on aio/tools/example-zipper/customizer/package-json/packageJsonCustomizer.js
> +    this.basePackageJson = JSON.parse(fs.readFileSync(`${__dirname}/base.json`));
Another constant would be good: `const packageFolder = path.resolve(__dirname);` would make it easier to move these package files around later if necessary.

2017-04-17 12:23 UTC, petebacondarwin commented on aio/tools/example-zipper/customizer/package-json/packageJsonCustomizer.js
> +const fs = require('fs');
Did you know that you can use `require` to load up JSON files, rather than `fs.readFileSync`?
E.g. instead of:

```
this.dependenciesPackageJson = JSON.parse(fs.readFileSync(path.join(__dirname, '../../../examples/shared//package.json')));
```

you can do

```
this.dependenciesPackageJson = require(path.resolve(examplesPath, 'shared//package.json'));
```

It automatically parses the JSON in an object :-)

2017-04-17 12:23 UTC, petebacondarwin commented on aio/tools/example-zipper/exampleZipper.js
> +    let json = JSON.parse(fs.readFileSync(configFileName, 'utf-8'));
you can use `require` here

2017-04-17 12:23 UTC, petebacondarwin commented on aio/tools/example-zipper/exampleZipper.js
> +    let defaultIncludes = ['**/*.ts', '**/*.js', '**/*.es6', '**/*.css', '**/*.html', '**/*.md', '**/*.json', '**/*.png'];
Given that everything else is in JSON files, perhaps it would be nice to move these includes and excludes into separate files too?

2017-04-17 13:30 UTC, Foxandxss commented on aio/tools/example-zipper/exampleZipper.js
> +    let defaultIncludes = ['**/*.ts', '**/*.js', '**/*.es6', '**/*.css', '**/*.html', '**/*.md', '**/*.json', '**/*.png'];
I don't follow Pete.

2017-04-17 20:08 UTC, petebacondarwin commented on aio/tools/example-zipper/exampleZipper.js
> +    let defaultIncludes = ['**/*.ts', '**/*.js', '**/*.es6', '**/*.css', '**/*.html', '**/*.md', '**/*.json', '**/*.png'];
Given that all the other data in this PR is stored in "data files", such as all the bits that you load in to create the `package.json`, why hard code these paths into this source file?

2017-04-18 18:15 UTC, mary-poppins commented
The angular.io preview for a8bd664c54e191b554ccaac5960be5983ddef0d9 is available [here][1].

[1]: https://pr16043-a8bd664c54e191b554ccaac5960be5983ddef0d9.ngbuilds.io/

2017-04-19 10:21 UTC, petebacondarwin approved these changes

2017-04-19 10:34 UTC, merged