docs(ts-to-js):  apply guidelines and update TOCs
angular/angular pull request #16054
Opened 2017-04-17 17:32 UTC by kapunahelewong

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: Copy edits to apply guidelines, make TOCs reflect doc shape, and clean up spaces added by migration tool.
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-04-17 17:45 UTC, mary-poppins commented
The angular.io preview for b31dab86b6e1efb8984f93787ab320ba918e4b16 is available [here][1].

[1]: https://pr16054-b31dab86b6e1efb8984f93787ab320ba918e4b16.ngbuilds.io/

2017-04-17 18:55 UTC, Foxandxss commented on aio/content/guide/ts-to-js.md
> +Angular offers two modes of template compilation, JIT (_just-in-time_) and
why lowercase? And wasn't it JiT and AoT?

2017-04-17 18:57 UTC, Foxandxss commented on aio/content/guide/ts-to-js.md
>  In the example above, there is no provider for the `'titlePrefix'` token.
can we indent this? Not sure if it is a good idea but I think so

2017-04-17 18:58 UTC, kapunahelewong commented on aio/content/guide/ts-to-js.md
> +Angular offers two modes of template compilation, JIT (_just-in-time_) and
@Foxandxss It was recently changed in the wordlist.

2017-04-17 18:59 UTC, kapunahelewong commented on aio/content/guide/ts-to-js.md
>  In the example above, there is no provider for the `'titlePrefix'` token.
Sure - I just tried it and it worked. Last week it broke it to indent it. I like it indented better too.

2017-04-17 19:30 UTC, mary-poppins commented
The angular.io preview for 9e89c4823fe4c5ab806651136b8d2e5869450e52 is available [here][1].

[1]: https://pr16054-9e89c4823fe4c5ab806651136b8d2e5869450e52.ngbuilds.io/

2017-04-17 20:27 UTC, mary-poppins commented
The angular.io preview for 6a6c1213fbf0b84efc17e0b59110884d1dd71efd is available [here][1].

[1]: https://pr16054-6a6c1213fbf0b84efc17e0b59110884d1dd71efd.ngbuilds.io/

2017-04-19 16:05 UTC, mary-poppins commented
The angular.io preview for 1d1b06a45a68302da8b636a1831889ff7c0d93ff is available [here][1].

[1]: https://pr16054-1d1b06a45a68302da8b636a1831889ff7c0d93ff.ngbuilds.io/

2017-04-19 16:05 UTC, mary-poppins commented
The angular.io preview for bd2c9fb21079033a0ddb7c194700c77e176ff851 is available [here][1].

[1]: https://pr16054-bd2c9fb21079033a0ddb7c194700c77e176ff851.ngbuilds.io/

2017-04-20 07:07 UTC, petebacondarwin commented on aio/content/guide/ts-to-js.md
>  <div class="l-sub-section">
you need a blank line here for the next lines to be recognized as markdown rather than plain HTML

2017-04-20 07:07 UTC, petebacondarwin commented on aio/content/guide/ts-to-js.md
> +  and the component displays the title without a prefix.
and a blank line here

2017-04-20 07:08 UTC, petebacondarwin commented on aio/content/guide/ts-to-js.md
> +  _View_ children are associated with element tags that appear _within_ the component's template.
blank line before this line - and before the `</div>` below.

2017-04-20 07:09 UTC, petebacondarwin commented on aio/content/guide/ts-to-js.md
> +  In _TypeScript_ and _ES6-with-decorators_ you can also use the  `queries` metadata
you get the idea :-)

2017-04-20 07:09 UTC, petebacondarwin requested changes
if you have a block of HTML that should contain markdown then you need to separate the markdown from the HTML by blank lines.

2017-04-20 14:17 UTC, kapunahelewong commented on aio/content/guide/ts-to-js.md
>  <div class="l-sub-section">
Done.

2017-04-20 14:17 UTC, kapunahelewong commented on aio/content/guide/ts-to-js.md
> +  and the component displays the title without a prefix.
Done.

2017-04-20 14:17 UTC, kapunahelewong commented on aio/content/guide/ts-to-js.md
> +  _View_ children are associated with element tags that appear _within_ the component's template.
Done.

2017-04-20 14:17 UTC, kapunahelewong commented on aio/content/guide/ts-to-js.md
> +  In _TypeScript_ and _ES6-with-decorators_ you can also use the  `queries` metadata
Yes, thank you for looking out! :)

2017-04-20 14:41 UTC, mary-poppins commented
The angular.io preview for c05efcf253f74ff5e4a0229bea875ad5dc096da2 is available [here][1].

[1]: https://pr16054-c05efcf253f74ff5e4a0229bea875ad5dc096da2.ngbuilds.io/

2017-04-21 16:59 UTC, mary-poppins commented
The angular.io preview for a145e73208ea7910d40d588cb115fc545b4e854e is available [here][1].

[1]: https://pr16054-a145e73208ea7910d40d588cb115fc545b4e854e.ngbuilds.io/

2017-04-28 02:19 UTC, wardbell commented
I fixed merge conflicts. We both have signed the CLA

2017-04-28 02:24 UTC, wardbell approved these changes
LGTM. This is a pure docs change the the Travis error is an unrelated flake. Merge away.

2017-04-28 02:35 UTC, mary-poppins commented
The angular.io preview for 1749f04e629ad1651631e55902512e632046f1f8 is available [here][1].

[1]: https://pr16054-1749f04e629ad1651631e55902512e632046f1f8.ngbuilds.io/

2017-04-28 04:42 UTC, mhevery commented
fix circle/ rebase

2017-04-28 09:58 UTC, mary-poppins commented
The angular.io preview for 8244bcf5034f8d709ab0728a6f5b7f9a6efd5a52 is available [here][1].

[1]: https://pr16054-8244bcf5034f8d709ab0728a6f5b7f9a6efd5a52.ngbuilds.io/

2017-04-28 10:00 UTC, mary-poppins commented
The angular.io preview for 0415112e9313b723c1002a485cb8908770654903 is available [here][1].

[1]: https://pr16054-0415112e9313b723c1002a485cb8908770654903.ngbuilds.io/

2017-04-28 22:34 UTC, merged