WIP fix(aio): accessibility items
angular/angular pull request #16062
Opened 2017-04-17 20:20 UTC by sjtrimble

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-04-17 20:34 UTC, mary-poppins commented
The angular.io preview for 75c2b598965668671d8fc3e8c83662febc213633 is available [here][1].

[1]: https://pr16062-75c2b598965668671d8fc3e8c83662febc213633.ngbuilds.io/

2017-04-17 21:50 UTC, mary-poppins commented
The angular.io preview for cc34d50770157910747f5a598bfff028e41c5590 is available [here][1].

[1]: https://pr16062-cc34d50770157910747f5a598bfff028e41c5590.ngbuilds.io/

2017-04-17 22:00 UTC, mary-poppins commented
The angular.io preview for 09e83f5ceda2863efb2cb3805e6d59e34b63c0ee is available [here][1].

[1]: https://pr16062-09e83f5ceda2863efb2cb3805e6d59e34b63c0ee.ngbuilds.io/

2017-04-18 15:28 UTC, IgorMinar commented
Please rebase this PR

2017-04-18 16:02 UTC, mary-poppins commented
The angular.io preview for 0c77c65c1ee5efd2676f2caad592acc9be510d43 is available [here][1].

[1]: https://pr16062-0c77c65c1ee5efd2676f2caad592acc9be510d43.ngbuilds.io/

2017-04-18 16:02 UTC, gkalpak requested changes
One minor issue. LGTM othrwise.

2017-04-18 16:02 UTC, gkalpak commented on aio/src/styles/1-layouts/_layout-global.scss
> +    display: none;
I think that `display:none` is usually not announced by screen readers. So, this won't work as intended.

2017-04-18 16:14 UTC, sjtrimble commented
@gkalpak I changed the way the hidden class works so it should only apply to the visual aspect now. Thanks for pointing out!

2017-04-18 16:30 UTC, mary-poppins commented
The angular.io preview for 3dd5b008a2c3e7ec62745e65de96bb561c7a9c69 is available [here][1].

[1]: https://pr16062-3dd5b008a2c3e7ec62745e65de96bb561c7a9c69.ngbuilds.io/

2017-04-18 18:56 UTC, gkalpak approved these changes
LGTM (1 minor nit - not a blocker)

2017-04-18 18:56 UTC, gkalpak commented on aio/src/styles/1-layouts/_layout-global.scss
> +.hidden {
Nit: I think it is common to use a name like `.visually-hidden` to convey that it is not hidden from screen-readers.

2017-04-18 19:25 UTC, sjtrimble commented on aio/src/styles/1-layouts/_layout-global.scss
> +.hidden {
Made the change. I agree.

2017-04-18 19:39 UTC, mary-poppins commented
The angular.io preview for e4eddf6f67b6f936b8498b8a6f482de4e1f01cd8 is available [here][1].

[1]: https://pr16062-e4eddf6f67b6f936b8498b8a6f482de4e1f01cd8.ngbuilds.io/

2017-04-18 21:46 UTC, mary-poppins commented
The angular.io preview for 857f44a4a7d6834dc817f56b7badf5ef185ea351 is available [here][1].

[1]: https://pr16062-857f44a4a7d6834dc817f56b7badf5ef185ea351.ngbuilds.io/

2017-04-19 07:18 UTC, gkalpak approved these changes

2017-04-19 10:52 UTC, merged