feat(aio): add embedded TOC component
angular/angular pull request #16078
Opened 2017-04-18 08:58 UTC by wardbell

**WHAT IS IT?**

Adds an expando embedded Table of Contents component (`<aio-toc>`) that works much like 
[this google web documentation page](https://developers.google.com/web/fundamentals/getting-started/principles/).

Second commit shows the `<aio-toc>` component at work in the "Angular Modules" guide, `ngModules.md`.

**Todo**
- [ ] Add tests
- [ ] Consider how to show in separate pane in wide mode
- [ ] Consider adding ability to build a TOC from doc's h2 and h3 tags when no content specified. Or dgeni could do that.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

2017-04-18 16:32 UTC, mary-poppins commented
The angular.io preview for 415f3fc76ea21580942c1ee0f543d4e02a5a531c is available [here][1].

[1]: https://pr16078-415f3fc76ea21580942c1ee0f543d4e02a5a531c.ngbuilds.io/

2017-04-19 12:57 UTC, gkalpak commented
It can use some styling love, but generally LGTM. I think it is quite useful (especially for longer pages).
👍 for have it as a fixed/floating pane on wider screens.
👍 for auto-generating.

2017-04-19 13:17 UTC, petebacondarwin commented on aio/src/app/embedded/code/code-example.component.ts
> +export class CodeExampleComponent implements OnInit {
❤️

2017-04-19 13:24 UTC, petebacondarwin reviewed
Do you specifically want to create these TOCs manually? Would it not be cleaner (and less maintenance for authors) if we parsed the document after it is rendered and genearate the TOC from all the H2s, etc.

2017-04-19 14:59 UTC, IgorMinar commented
I agree with Pete, TOC should be auto generated by dgeni.

We should just put a placeholder for dgeni to know where to drop the TOC and then dgeni can do the rest (especially once the header anchor PR is merged, this will be trivial and less error prone)

2017-04-19 15:00 UTC, IgorMinar requested changes
I agree with Pete, TOC should be auto generated by dgeni.

We should just put a placeholder for dgeni to know where to drop the TOC and then dgeni can do the rest (especially once the header anchor PR is merged, this will be trivial and less error prone)

2017-04-19 22:51 UTC, mary-poppins commented
The angular.io preview for 05819207b05e66e181a7b81e80b944443c8fd3df is available [here][1].

[1]: https://pr16078-05819207b05e66e181a7b81e80b944443c8fd3df.ngbuilds.io/

2017-04-19 22:53 UTC, wardbell commented
Regarding TOC generation. I thought about that when I started this journey. I should have explained in the opening comment. I have updated it with our ( @petebacondarwin and my) plan.

2017-04-20 10:51 UTC, wardbell commented
Ready to explore. No tests yet so still WIP.

1) `yarn docs`
2) Navigate to "Angular Modules" guide to see `<aio-toc>...</aio-toc>` when author specifies the TOC with a `<ul>` list.
3) Navigate "Animations" guide to see `<aio-toc></aio-toc>` (no list), which leads to auto-generation of the TOC from H2 and H3.

The TOC generator will use heading ids if present. If missing, it creates them.

2017-04-20 11:11 UTC, IgorMinar commented
build failed, so there is no preview.

2017-04-20 11:15 UTC, IgorMinar submitted a review, later dismissed
Can you please explain why we should implement this functionality in dgeni? it already does all the anchor handling and link checking, so it's only natural that it will also do TOC generation.

2017-04-20 11:15 UTC, IgorMinar commented on aio/src/app/embedded/toc/toc.component.ts
> +    setTimeout(() => {
this is a big red flag. Whatever you are doing here is likely either bad design or a bug in Angular. Since I see that you are recreating your own templating engine above, I suggest that you stop doing that and use Angular templating instead of custom dom manipulation.

2017-04-20 11:15 UTC, IgorMinar commented on aio/src/app/embedded/toc/toc.component.ts
> +      // Security: the aioTocContent comes from the pre-rendered DOM and is considered to be secure
not true. by now you have no idea what is being appended because you processed the DOM in many ways and you don't know the origin and interaction of various interpolated parts.

2017-04-20 11:15 UTC, IgorMinar commented on aio/src/app/shared/toc.service.spec.ts
> +// TODO: WRITE TESTS
when?

2017-04-20 11:15 UTC, IgorMinar commented on aio/src/app/embedded/toc/toc.component.html
> +  <div *ngIf="hasSecondary" class="toc-heading secondary"
does this really need to be this complicated? it's just a TOC :-)

why do we need the ability to close the TOC? if we really do need that functionality, shouldn't we use the material zippy instead?

2017-04-20 11:27 UTC, IgorMinar commented on aio/src/app/embedded/toc/toc.component.ts
> +    if (this.hasContent) {
do we really want to allow manually created TOC? why have two ways of doing this? Let's just have one. Can we remove this option?

2017-04-25 11:29 UTC, petebacondarwin commented
I spoke with @IgorMinar.
We want to generate the TOC data as part of the doc-gen, and add this to the `DocumentContents` data that is sent down the wire to the `DocViewerComponent`. This component will then render this TOC in a separate element to the document contents itself that should be attached the top right of the page.

2017-04-26 23:13 UTC, mary-poppins commented
The angular.io preview for c4d55c8edb1a115e0304f09a646820f71451491a is available [here][1].

[1]: https://pr16078-c4d55c8edb1a115e0304f09a646820f71451491a.ngbuilds.io/

2017-04-26 23:45 UTC, mary-poppins commented
The angular.io preview for 9bd4a417349e0e79cf8c3b4857b286928d986f25 is available [here][1].

[1]: https://pr16078-9bd4a417349e0e79cf8c3b4857b286928d986f25.ngbuilds.io/

2017-04-26 23:51 UTC, mary-poppins commented
The angular.io preview for ae473eb4f87648d84f47bb1ed03ea463ec71f7b3 is available [here][1].

[1]: https://pr16078-ae473eb4f87648d84f47bb1ed03ea463ec71f7b3.ngbuilds.io/

2017-04-27 00:19 UTC, mary-poppins commented
The angular.io preview for aae9080aca5a51f301222fe25bb3c0ff2bc76c55 is available [here][1].

[1]: https://pr16078-aae9080aca5a51f301222fe25bb3c0ff2bc76c55.ngbuilds.io/

2017-04-27 01:54 UTC, mary-poppins commented
The angular.io preview for 719bb08c0ce727cbe15b201646ee23951defecad is available [here][1].

[1]: https://pr16078-719bb08c0ce727cbe15b201646ee23951defecad.ngbuilds.io/

2017-04-27 02:13 UTC, mary-poppins commented
The angular.io preview for 0f1e9588792a2ad742c17e7240a0d4a68e57ca73 is available [here][1].

[1]: https://pr16078-0f1e9588792a2ad742c17e7240a0d4a68e57ca73.ngbuilds.io/

2017-04-27 03:15 UTC, mary-poppins commented
The angular.io preview for 004fc908b93e32d9c35ea5e4c28e0737368b369e is available [here][1].

[1]: https://pr16078-004fc908b93e32d9c35ea5e4c28e0737368b369e.ngbuilds.io/

2017-04-27 06:27 UTC, mary-poppins commented
The angular.io preview for bdc0ccac4dff1129ba3e1bcad15e26a33c2f9fc1 is available [here][1].

[1]: https://pr16078-bdc0ccac4dff1129ba3e1bcad15e26a33c2f9fc1.ngbuilds.io/

2017-04-27 14:08 UTC, petebacondarwin commented on aio/src/app/embedded/toc/toc.component.spec.ts
> +// TODO: WRITE TESTS
perhaps you can remove this now?

2017-04-27 14:11 UTC, petebacondarwin commented on aio/src/app/layout/doc-viewer/doc-viewer.component.ts
> +    // If you don't want a TOC, don't have an <h1>
The home page will have an `h1` right? But I guess it shouldn't have a TOC.

2017-04-27 14:12 UTC, petebacondarwin reviewed
At a very high level this looks awesome! I'll pick through it tonight.

2017-04-27 16:47 UTC, wardbell commented on aio/src/app/layout/doc-viewer/doc-viewer.component.ts
> +    // If you don't want a TOC, don't have an <h1>
It will be marked with `no-toc` class and thus skipped

2017-04-27 17:08 UTC, wardbell commented on aio/src/app/shared/toc.service.spec.ts
> +// TODO: WRITE TESTS
Done

2017-04-27 17:24 UTC, mary-poppins commented
The angular.io preview for 40e6e2c281194dcb6bf7bd4c9899b00860b689ed is available [here][1].

[1]: https://pr16078-40e6e2c281194dcb6bf7bd4c9899b00860b689ed.ngbuilds.io/

2017-04-27 17:27 UTC, mary-poppins commented
The angular.io preview for 395476d27975b274293719c4addbd9c358e9f81d is available [here][1].

[1]: https://pr16078-395476d27975b274293719c4addbd9c358e9f81d.ngbuilds.io/

2017-04-27 19:14 UTC, mary-poppins commented
The angular.io preview for eb283829d1cd359ea3ca1a418060463c31dfa328 is available [here][1].

[1]: https://pr16078-eb283829d1cd359ea3ca1a418060463c31dfa328.ngbuilds.io/

2017-04-27 20:21 UTC, petebacondarwin approved these changes
This PR works for me. I couldn't see any major issues with the implementation. I guess we need to implement the floating ToC now too?

2017-04-27 20:51 UTC, gkalpak approved these changes
The `file-not-found` and `fetching-error` content need a `no-toc` classes.

2017-04-27 20:51 UTC, gkalpak commented on aio/src/app/embedded/toc/toc.component.html
> +  <div *ngIf="!hasSecondary"class="toc-heading">Contents</div>
Nit: Missing space before `class` (unless it is intentional to align with the one below 😛)

2017-04-27 20:51 UTC, gkalpak commented on aio/src/app/layout/doc-viewer/doc-viewer.component.ts
> +    // If you don't want a TOC, don't have an <h1>
Maybe this is worth putting into the comment for posterity.

2017-04-27 20:51 UTC, gkalpak commented on aio/src/styles/2-modules/_toc.scss
> +  aio-toc.embedded:not(:empty) {
This selector does work. `:empty` will not match even if there is only whitespace in the element.

2017-04-27 21:01 UTC, petebacondarwin commented
@wardbell - marked for merge. Feel free to fix up @gkalpak's comments if you have time. Otherwise, please create issues to track them for fixing later.

2017-04-27 22:29 UTC, wardbell commented on aio/src/app/layout/doc-viewer/doc-viewer.component.ts
> +    // If you don't want a TOC, don't have an <h1>
Done

2017-04-27 22:32 UTC, merged

2017-04-27 22:32 UTC, wardbell commented on aio/src/styles/2-modules/_toc.scss
> +  aio-toc.embedded:not(:empty) {
I copied it from the google web doc example and don't know what it does. I'm not testing it either. Removing.

2017-04-27 22:44 UTC, wardbell commented
Implemented @gkalpak suggestions in PR #16391