fix(aio): autoscroll & add #top_of_page
angular/angular pull request #16072
Opened 2017-04-17 23:49 UTC by wardbell

also adds  `<a id="top_of_page"></a>` which will benefit future efforts to navigate there from within a page.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

2017-04-18 00:28 UTC, mary-poppins commented
The angular.io preview for d326f4a9bcb1820db7c7abce473e8c07dd1dbd19 is available [here][1].

[1]: https://pr16072-d326f4a9bcb1820db7c7abce473e8c07dd1dbd19.ngbuilds.io/

2017-04-18 00:43 UTC, wardbell commented
I believe this is only failing because "PWA score is too low".  That's not a valid test yet, right?

2017-04-18 07:45 UTC, gkalpak commented
> I believe this is only failing because "PWA score is too low".

Right!

> That's not a valid test yet, right?

No, idea what you're talking about 😛

The test is valid (but not very reliable - depending on network latency and browser/VM performance). Maybe we should lower our expectation 😞

2017-04-18 08:16 UTC, gkalpak approved these changes
A couple of nits, but LGTM otherwise. I think that kind of thing would benefit from some e2e tests, but not a blocker.

2017-04-18 08:16 UTC, gkalpak commented on aio/src/app/shared/auto-scroll.service.ts
> +      top.scrollIntoView();
Since `window.scrollBy(0, -80)` doesn't make a difference when already at the top of the page, this method could be simplified by unifying some paths:

```ts
scroll() {
  const hash = this.getCurrentHash();
  const element: HTMLElement = hash
      ? this.document.getElementById(hash)
      : this.document.getElementById('top_of_page') || this.document.body;
  if (element) {
    element.scrollIntoView();
    if (window) { window.scrollBy(0, -80); }
  }
}
```

2017-04-18 15:31 UTC, IgorMinar requested changes

2017-04-18 15:31 UTC, IgorMinar commented on aio/src/app/app.component.html
> +<md-toolbar color="primary" class="app-toolbar" >
⏰

2017-04-18 15:31 UTC, IgorMinar commented on aio/src/app/app.component.html
> +    <a id="top_of_page"></a>
+1

2017-04-18 15:31 UTC, IgorMinar commented on aio/src/app/shared/auto-scroll.service.ts
> +      top.scrollIntoView();
+1

2017-04-18 21:11 UTC, wardbell commented on aio/src/app/app.component.html
> +    <a id="top_of_page"></a>
I picked the anchor that google uses. Don't care one way or the other. I'll fix it.

2017-04-19 07:09 UTC, wardbell commented on aio/src/app/shared/auto-scroll.service.ts
> +        if (window) { window.scrollBy(0, -80); } // account for top menu overlay
If it is as follows, will it _break_ or simply not scroll up as desired? Can live with the latter for quite a while. The referenced code is pretty baroque. 
```
if (window && window.scrollBy) { window.scrollBy(0, -80); }
```
I tried the code in this (revised) PR with a target anchor just above the footer (worst case for us). Looked fine in Chrome at all viewport sizes.

2017-04-19 07:14 UTC, wardbell commented
I believe my update addresses all concerns. Please re-review

2017-04-19 07:37 UTC, mary-poppins commented
The angular.io preview for bfbf601e6380f79fc6fd4f77b73c99e9244b00a6 is available [here][1].

[1]: https://pr16072-bfbf601e6380f79fc6fd4f77b73c99e9244b00a6.ngbuilds.io/

2017-04-19 08:32 UTC, gkalpak commented on aio/src/app/shared/auto-scroll.service.ts
> +        if (window) { window.scrollBy(0, -80); } // account for top menu overlay
I meant not scroll as expected. E.g. notice that the topbar has different height on different viewports and nobody will remember to update this when we change something topbar-related.

<sub>AngularJS's `$anchorScroll` allows specifying an element (e.g. the topbar) and then it tracks its size and automatically adjusts the scrolling offset (instead of having a hardcoded offet value), which is pretty cool.</sub>

But like I said, let's worry about it when/if it becomes a real concern.

2017-04-19 09:54 UTC, petebacondarwin commented on aio/src/app/shared/auto-scroll.service.spec.ts
> +    expect(document.getElementById).toHaveBeenCalledWith('not-found');
Should there not be an expectation to ensure that it did not scroll? Perhaps:

```
expect(window.scrollBy).not.toHaveBeenCalled();
```

2017-04-19 10:00 UTC, petebacondarwin commented on aio/src/app/shared/auto-scroll.service.ts
> +      if (window && window.scrollBy) { window.scrollBy(0, -80); }
In AngularJS's autoScroll we are able to pass in an element that is used to compute the amount of offset that is required. See https://github.com/angular/angular.js/blob/master/src/ng/anchorScroll.js#L61-L69

In this case we would provide the toolbar element?

This should not block this PR but I would recommend something similar in a future PR.

2017-04-19 10:01 UTC, petebacondarwin requested changes
Just the extra expectations in the test for not scrolling then LGTM

2017-04-20 09:25 UTC, petebacondarwin commented
Resolved the conflict and force pushed

2017-04-20 09:26 UTC, petebacondarwin approved these changes

2017-04-20 09:42 UTC, mary-poppins commented
The angular.io preview for fa893b958254d79a309b298b17083392a2162796 is available [here][1].

[1]: https://pr16072-fa893b958254d79a309b298b17083392a2162796.ngbuilds.io/

2017-04-20 09:47 UTC, merged