WIP feat(aio): 404 page
angular/angular pull request #16089
Opened 2017-04-18 14:50 UTC by sjtrimble

404 page styling with graphic. Will update once https://github.com/angular/angular/pull/16085 lands.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

2017-04-18 15:04 UTC, mary-poppins commented
The angular.io preview for 8d2c043698d07c1cb9d4a5268bac40a261f00dce is available [here][1].

[1]: https://pr16089-8d2c043698d07c1cb9d4a5268bac40a261f00dce.ngbuilds.io/

2017-04-18 15:26 UTC, petebacondarwin commented on aio/src/styles/1-layouts/_not-found.scss
> +#notfound {
so this will change to `#file-not-found`

2017-04-18 16:10 UTC, mary-poppins commented
The angular.io preview for c130c3374927f9e37e19d63b38dc66adde85343b is available [here][1].

[1]: https://pr16089-c130c3374927f9e37e19d63b38dc66adde85343b.ngbuilds.io/

2017-04-18 16:15 UTC, sjtrimble commented
Thanks @petebacondarwin :) I changed it

2017-04-19 07:05 UTC, gkalpak requested changes

2017-04-19 07:05 UTC, gkalpak commented on aio/content/file-not-found.md
> +    <img src="assets/images/support/angular-404.svg" width="300px;" height="300px;"/>
`width` and `height` attributes hold the _"[intrinsic width/height of the image in pixels][1]"_. You only need to specify the numeric value (the rest is ignored).

[1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

2017-04-19 07:05 UTC, gkalpak commented on aio/content/file-not-found.md
> +@title Page Not Found
Having a title here, adds an `h1` heading to the page that doesn't look inline with the rest of the design.
(Not sure what the correct solution is for such cases.)

2017-04-19 07:36 UTC, wardbell requested changes
LGTM after you fix the title `<h1>` problem

2017-04-19 07:36 UTC, wardbell commented on aio/content/file-not-found.md
> +@title Page Not Found
The problem here is that Pete will report it as an error (which a missing title would be normally).
A solution would be to style that `<h1>` so it disappears.

2017-04-19 07:36 UTC, wardbell commented on aio/src/assets/images/support/angular-404.svg
> +<?xml version="1.0" encoding="utf-8"?>
As we discussed, a lighter weight alternative is an MD icon such as seen in the network fail page PR #16139.

I would merge this now and wait to change it a later PR.

2017-04-19 08:32 UTC, petebacondarwin commented on aio/content/file-not-found.md
> +@title Page Not Found
How about we allow an empty `@title` tag, which indicates that we explicitly do not want a heading?

2017-04-19 08:34 UTC, gkalpak commented on aio/content/file-not-found.md
> +@title Page Not Found
SGTM :smiley:

2017-04-19 14:43 UTC, IgorMinar commented on aio/content/file-not-found.md
> +    <img src="assets/images/support/angular-404.svg" width="300px;" height="300px;"/>
also there should be no extra commas in the value strings.

2017-04-19 14:43 UTC, IgorMinar commented on aio/content/file-not-found.md
> +@title Page Not Found
won't that be error-prone? how about we allowed `@title VOID` instead?

2017-04-19 14:47 UTC, IgorMinar commented
I suggest we remove the h1 heading and the vertical bar under it. And instead of 404 turn the logo into a sad face. That way we can use it elsewhere and we don't have the issue with 0 being visually split into two by the logo which looks "disturbing".

<img width="1664" alt="screen shot 2017-04-19 at 4 44 53 pm" src="https://cloud.githubusercontent.com/assets/216296/25186166/afa27f74-251f-11e7-90d8-ac1cc6b6b983.png">

2017-04-19 14:56 UTC, petebacondarwin commented on aio/content/file-not-found.md
> +@title Page Not Found
It is not that error prone because it is very unlikely that someone would add a `@title` tag and forget to add a title.

The support for this landed a few hours ago.

I just realised though that this might not be necessary. If no title is provided via `@title` then the content is searched for the first `h1` element.

So if @sjtrimble changes the file so that `<h2>Page Not Found</h2>` becomes `<h1>Page Not Found</h1>` then we can ditch the `@title` and `@description` tags from the file altogether.

2017-04-19 15:14 UTC, gkalpak commented on aio/content/file-not-found.md
> +@title Page Not Found
Wouldn't that render the title (which is exactly what we are trying to prevent)?

2017-04-19 17:21 UTC, petebacondarwin commented on aio/content/file-not-found.md
> +@title Page Not Found
As I understand it, we do want a heading (there is already a `h2` there) but not at the top of the page. The thing about adding a title via the `@title` tag is that it automatically adds a `h1` at the top of the page.

2017-04-19 17:28 UTC, gkalpak commented on aio/content/file-not-found.md
> +@title Page Not Found
Oh, I see. Then, I agree this could be solved by removing the `@title` and changing the `h2` to `h1` (and styling it appropriately).

2017-04-19 18:13 UTC, sjtrimble commented
@IgorMinar This builds on top of Pete's PR which has a specific section ID that I use to override the h1 all together so it's hidden. 

I can make a sad face instead :)

2017-04-19 18:44 UTC, sjtrimble commented
I have made the changes - new icon, no @title on the .md, and custom h1 styling.

2017-04-19 18:45 UTC, mary-poppins commented
The angular.io preview for 5bfa352c6427bf9735101cf389c9591b2628fac0 is available [here][1].

[1]: https://pr16089-5bfa352c6427bf9735101cf389c9591b2628fac0.ngbuilds.io/

2017-04-19 18:45 UTC, petebacondarwin commented on aio/content/file-not-found.md
>  @description
You can remove this `@description` as well :-)

2017-04-19 18:57 UTC, mary-poppins commented
The angular.io preview for b2999f624387f3fb764e753f6c0e624125d57c94 is available [here][1].

[1]: https://pr16089-b2999f624387f3fb764e753f6c0e624125d57c94.ngbuilds.io/

2017-04-19 19:43 UTC, petebacondarwin approved these changes
LGTM - let's merge it and iterate on the fine tuning of the design if necessary.

2017-04-19 20:02 UTC, mary-poppins commented
The angular.io preview for 114fa3cb5f61a4ca1390a278400a74cef10c6476 is available [here][1].

[1]: https://pr16089-114fa3cb5f61a4ca1390a278400a74cef10c6476.ngbuilds.io/

2017-04-20 03:40 UTC, closed without merging