fix(aio): style mods and content udpates
angular/angular pull request #16138
Opened 2017-04-18 23:39 UTC by sjtrimble

Fixed capitalization in sidenav menu items
Add min height property to sidenav-content for better viewing on short pages or high resolution screens
Add dividier between change log items as before to h2
Table adjustments to reduce off-screen items
Content updates including capitalization consistency and title additions

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-04-18 23:52 UTC, mary-poppins commented
The angular.io preview for 745f2eb6a1441d6c922dde9a040ab5f9e5814797 is available [here][1].

[1]: https://pr16138-745f2eb6a1441d6c922dde9a040ab5f9e5814797.ngbuilds.io/

2017-04-19 00:03 UTC, mary-poppins commented
The angular.io preview for 0da63a6a276cd48177bbf2f2dcd9cce0afd3125e is available [here][1].

[1]: https://pr16138-0da63a6a276cd48177bbf2f2dcd9cce0afd3125e.ngbuilds.io/

2017-04-19 00:15 UTC, mary-poppins commented
The angular.io preview for 7b59a4f0e66b1dceb969ffc649193268f7c121d7 is available [here][1].

[1]: https://pr16138-7b59a4f0e66b1dceb969ffc649193268f7c121d7.ngbuilds.io/

2017-04-19 09:23 UTC, gkalpak requested changes

2017-04-19 09:23 UTC, gkalpak commented on aio/content/guide/browser-support.md
> +<table class="fixed-table">
_fixed-table_ --> _table-fixed_

2017-04-19 09:23 UTC, gkalpak commented on aio/src/styles/1-layouts/_content-layout.scss
> +#guide-change-log h2::before {
Such selectors (that rely on auto-generated stuff) are brittle. Could we somehow target the specific `h2` explicitly (e.g. by adding a class/id to it)?

2017-04-19 09:23 UTC, gkalpak commented on aio/src/styles/2-modules/_table.scss
> +    table-layout: fixed;
Why this?

2017-04-19 18:15 UTC, sjtrimble commented on aio/src/styles/1-layouts/_content-layout.scss
> +#guide-change-log h2::before {
Not sure what the easiest way would be. The intent was to have each change log section separated by an hr. We could do this by changing the authored document by either adding the hr itself, or by moving the sections into div's labeled with appropriate classes, and then I can easily add an after that way.

Do you have a recommendation on which one would be more appropriate. I'd prefer the authoring changes with divs for sections + classes.

2017-04-19 19:07 UTC, gkalpak commented on aio/src/styles/1-layouts/_content-layout.scss
> +#guide-change-log h2::before {
Actually, after realizing this targets all `h2` element inside that document and not a specific one, I think thisis fine as it is.

2017-04-19 19:07 UTC, gkalpak approved these changes

2017-04-19 19:44 UTC, mary-poppins commented
The angular.io preview for b61c21bb3a7001dfd8e1bc961ce0f5280d21a9c1 is available [here][1].

[1]: https://pr16138-b61c21bb3a7001dfd8e1bc961ce0f5280d21a9c1.ngbuilds.io/

2017-04-20 03:40 UTC, closed without merging