fix(aio): handle clicks deep within anchor tags
angular/angular pull request #16131
Opened 2017-04-18 19:42 UTC by wardbell

Several docs (e.g., "Docs" guide page) surround arbitrary HTML content in anchor tags. Clicking on that content triggered page refresh because we did not find the anchor.

In this fix, the click interception analysis in `AppComponent` climbs the ancestor tree until it finds an anchor tag to analyze and, potentially, intercept. If it doesn't find an anchor, the default click handling is allowed (returns `true`).

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

2017-04-18 19:57 UTC, mary-poppins commented
The angular.io preview for b52f0de76e577eb8a4036a218de83082b1894828 is available [here][1].

[1]: https://pr16131-b52f0de76e577eb8a4036a218de83082b1894828.ngbuilds.io/

2017-04-19 07:19 UTC, wardbell commented
Failing the Travis saucelabs task. Flake?

2017-04-19 08:46 UTC, gkalpak requested changes
I wonder (mostly ooc) why we have stuff wrapped deeply in anchors, but if we must this LGTM (with the test fixed).

2017-04-19 08:46 UTC, gkalpak commented on aio/src/app/app.component.spec.ts
> +      anchorElement.appendChild(imageElement);
_imageElement_ --> _divElement_

2017-04-19 08:46 UTC, gkalpak commented on aio/src/app/app.component.ts
> +    if (target instanceof HTMLAnchorElement) {
No need for `instanceof` check any more. If it is truthy, it will be an `HTMLAnchorElement`.

2017-04-19 14:38 UTC, IgorMinar requested changes

2017-04-19 14:38 UTC, IgorMinar commented on aio/src/app/app.component.spec.ts
> +      imageElement.click();
I suggest that you simplify this code by using innerHTML which makes the whole thing way more readable:

```
fixture.nativeElement.innerHTML="<a href='some/url'><div><img></div></a>"
const imageElement = fixture.nativeElement.findElementByTagName('img');
imageElement.click();
```

3 readable lines vs 8 error prone lines of code. simple is better. :)

2017-04-19 14:38 UTC, IgorMinar commented on aio/src/app/app.component.spec.ts
> +      imageElement.click();
use the same declarative approach as I explained above.

2017-04-19 14:38 UTC, IgorMinar commented on aio/src/app/app.component.ts
> +    if (target instanceof HTMLAnchorElement) {
+1

2017-04-19 22:33 UTC, wardbell commented
Thanks. Review again please.

2017-04-19 22:43 UTC, mary-poppins commented
The angular.io preview for e760b2d222cf796ed8fcc03ff0dcecf352c9625f is available [here][1].

[1]: https://pr16131-e760b2d222cf796ed8fcc03ff0dcecf352c9625f.ngbuilds.io/

2017-04-20 09:15 UTC, petebacondarwin approved these changes

2017-04-20 09:16 UTC, merged