docs(aio): adjust zips/plunker paths
angular/angular pull request #16194
Opened 2017-04-20 11:34 UTC by Foxandxss

Fixes #16117

2017-04-20 11:50 UTC, mary-poppins commented
The angular.io preview for e20f5bc03c58223f2c4ca9e45ec03ccac4313541 is available [here][1].

[1]: https://pr16194-e20f5bc03c58223f2c4ca9e45ec03ccac4313541.ngbuilds.io/

2017-04-20 11:51 UTC, Foxandxss commented
Hold on this one, there is a weird behavior.

2017-04-20 12:34 UTC, gkalpak requested changes

2017-04-20 12:34 UTC, gkalpak commented on aio/content/guide/cli-quickstart.md
> +And you can also <a href="/content/zips/cli-quickstart/cli-quickstart.zip">download the example.</a>
This is trying to fetch `/content/docs/content/zips/cli-quickstart/cli-quickstart.zip.json`.
I think you need to tell the LocationService that it should not try to navigate to this as a doc, by either adding a `download` attribute or a `target` (other than `_self`).

2017-04-20 13:27 UTC, mary-poppins commented
The angular.io preview for 4937973254695fe06b97e7d05fd5b83dd1f41934 is available [here][1].

[1]: https://pr16194-4937973254695fe06b97e7d05fd5b83dd1f41934.ngbuilds.io/

2017-04-20 13:37 UTC, gkalpak requested changes

2017-04-20 13:37 UTC, gkalpak commented on aio/content/guide/ts-to-js.md
> +**Run and compare the live <live-example name="cb-ts-to-js/ts">TypeScript</live-example> and <live-example name="cb-ts-to-js/js">JavaScript</live-example>
The zips for these files cannot be found on the preview.

2017-04-20 16:29 UTC, mary-poppins commented
The angular.io preview for a67d329f986f87eb27f10003c90fc21613d935ff is available [here][1].

[1]: https://pr16194-a67d329f986f87eb27f10003c90fc21613d935ff.ngbuilds.io/

2017-04-20 19:13 UTC, gkalpak approved these changes
One minor suggestion. LGTM regardless.

2017-04-20 19:13 UTC, gkalpak commented on aio/tools/example-zipper/exampleZipper.js
> +      exampleZipName = relativeDirName.split('/')[0];
Could the zip name be `relativeDirName.split('/').join('-')` or something? I think it is useful to not have the same name for different zips.

2017-04-20 22:37 UTC, Foxandxss commented on aio/tools/example-zipper/exampleZipper.js
> +      exampleZipName = relativeDirName.split('/')[0];
I don't think there is any case where that would happen.

2017-04-21 08:56 UTC, merged

2017-04-21 09:36 UTC, gkalpak commented on aio/tools/example-zipper/exampleZipper.js
> +      exampleZipName = relativeDirName.split('/')[0];
It does happen with the `cb-ts-to-js` one, but it shipped now, so...

2017-04-21 09:37 UTC, petebacondarwin commented on aio/tools/example-zipper/exampleZipper.js
> +      exampleZipName = relativeDirName.split('/')[0];
Can you create an issue to track it @gkalpak

2017-04-21 09:39 UTC, gkalpak commented on aio/tools/example-zipper/exampleZipper.js
> +      exampleZipName = relativeDirName.split('/')[0];
I can...but will I? 😛

2017-04-21 09:41 UTC, gkalpak commented on aio/tools/example-zipper/exampleZipper.js
> +      exampleZipName = relativeDirName.split('/')[0];
For reference: #16227