docs(aio): content re-org #16248
angular/angular pull request #16253
Opened 2017-04-22 01:49 UTC by wardbell

closes #16248

This is step along the "Stage One" path outlined in the "[Docs Refresh](https://docs.google.com/document/d/1QIQrHhT8YqgYNUHrI9ZBoekCv4CeaCarYsW5mWKC6GE/edit?ts=58fa36dc)" design doc.

It reorganizes the sidenav (governed by `navigation.json`), folds the cookbook into the guide, and revises file/folder names accordingly.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

2017-04-22 02:02 UTC, mary-poppins commented
The angular.io preview for d8f598300f9108ffdaab852e8547a6be25eacecf is available [here][1].

[1]: https://pr16253-d8f598300f9108ffdaab852e8547a6be25eacecf.ngbuilds.io/

2017-04-22 03:01 UTC, mary-poppins commented
The angular.io preview for f0d708be7dbad0247eb3737433f908228e00c0a7 is available [here][1].

[1]: https://pr16253-f0d708be7dbad0247eb3737433f908228e00c0a7.ngbuilds.io/

2017-04-22 07:09 UTC, gkalpak requested changes
Much, much better 💯

BTW, you also need to update [ngsw-manifest.json][1] with the updated image paths.

[1]: https://github.com/angular/angular/blob/7a8bd99ab1ba98a5593fba961d7872c1adcba47c/aio/ngsw-manifest.json#L4

2017-04-22 10:37 UTC, Foxandxss commented on aio/content/examples/set-document-title/e2e-spec.ts
> +// gulp run-e2e-tests --filter=set-document-title
No. Can be deleted.

2017-04-22 10:38 UTC, Foxandxss commented on aio/content/guide/dependency-injection-in-action.md
> +* [Application-wide dependencies](guide/dependency-injection-in-action#app-wide-dependencies)
No, they don't.

2017-04-22 10:44 UTC, Foxandxss commented
Good work on the new side nav bar. I like the new organization. Perhaps a bit weird that some of them are not in alphabetic order.

And there is a `yarn setup` now @wardbell :)

2017-04-23 07:29 UTC, mary-poppins commented
The angular.io preview for 99a617edc44c6b2a44084bdb409cb7e83c88348a is available [here][1].

[1]: https://pr16253-99a617edc44c6b2a44084bdb409cb7e83c88348a.ngbuilds.io/

2017-04-24 07:34 UTC, wardbell commented on aio/content/guide/aot-compiler.md
> +<a href="assets/images/guides/aot-compiler/toh6-bundle.png" target="_blank" title="View larger image">
Huh? I swear I swept this completely in this PR.

2017-04-24 07:35 UTC, wardbell commented on aio/content/navigation.json
> -          "url": "guide/learning-angular",
Gone. Needed the MD briefly but no more.

2017-04-24 07:46 UTC, mary-poppins commented
The angular.io preview for d6c8ac9a5e59da50fe58b6d416d66ad8212411cb is available [here][1].

[1]: https://pr16253-d6c8ac9a5e59da50fe58b6d416d66ad8212411cb.ngbuilds.io/

2017-04-24 07:53 UTC, wardbell commented on aio/content/guide/dependency-injection-in-action.md
> +* [Application-wide dependencies](guide/dependency-injection-in-action#app-wide-dependencies)
I'd really really like to fix this so we don't have to specify the doc id.

2017-04-24 08:00 UTC, mary-poppins commented
The angular.io preview for 0428044012fbb0000b237ba98a57d8d967063bbd is available [here][1].

[1]: https://pr16253-0428044012fbb0000b237ba98a57d8d967063bbd.ngbuilds.io/

2017-04-24 08:08 UTC, mary-poppins commented
The angular.io preview for 4bb36f7bdd791f35feb9c7dde55daa47e1b33455 is available [here][1].

[1]: https://pr16253-4bb36f7bdd791f35feb9c7dde55daa47e1b33455.ngbuilds.io/

2017-04-24 08:22 UTC, gkalpak commented on aio/content/guide/dependency-injection-in-action.md
> +* [Application-wide dependencies](guide/dependency-injection-in-action#app-wide-dependencies)
As pointed out by @petebacondarwin off-GitHub, this already works (thanks to dgeni): https://github.com/angular/angular/blob/master/aio/tools/transforms/angular-base-package/processors/fixInternalDocumentLinks.js

2017-04-24 12:43 UTC, petebacondarwin commented on aio/content/guide/docs.md
> +- **Getting Started** is a taste of Angular in under five minutes.
Should these not be links? Making the user have to go look in the side nav seems like [brain-watts wasted](https://www.avis.it/userfiles/file/Dont_Make_Me_Think_A_Common_Sense_Approach_to_Web_Usability_2nd_Ed_2005.pdf)...

2017-04-24 12:45 UTC, petebacondarwin commented on aio/content/guide/docs.md
> +This is the Angular **version 4** documentation. See what's new in the [documentation changelog](guide/change-log). View the [Angular change log](https://github.com/angular/angular/blob/master/CHANGE
enhancement**s**

2017-04-24 12:52 UTC, petebacondarwin commented on aio/content/guide/set-document-title.md
> +      <img src='assets/images/plunker/plunker-switch-to-editor-button.png' width="200px" height="70px" alt="pop out the window" align="right"></img>      <br></br>      <img src='assets/images/plunke
why are these in the plunker folder rather than simply guide?

2017-04-24 12:55 UTC, petebacondarwin approved these changes
LGTM - a few very minor comments that could be picked up in future changes.

2017-04-24 13:00 UTC, merged

2017-04-24 16:02 UTC, wardbell commented on aio/content/guide/set-document-title.md
> +      <img src='assets/images/plunker/plunker-switch-to-editor-button.png' width="200px" height="70px" alt="pop out the window" align="right"></img>      <br></br>      <img src='assets/images/plunke
Because they describe general behavior of plunkers and appear on several docs ... or rather they _used to_ appear on several docs. I don't know what happened.

2017-04-24 16:14 UTC, petebacondarwin commented on aio/content/guide/set-document-title.md
> +      <img src='assets/images/plunker/plunker-switch-to-editor-button.png' width="200px" height="70px" alt="pop out the window" align="right"></img>      <br></br>      <img src='assets/images/plunke
Even if they did appear in several docs, I would still expect them to be stored in the `guide` folder, with the `plunker` folder beneath?