fix(aio): fine-tune which files are pre-fetched/cached by the ServiceWorker
angular/angular pull request #16318
Opened 2017-04-25 15:04 UTC by gkalpak

- Move `content/images/bios/` to `assets/images/bios/` (where all other images are).
- Move images that are currently not being used to `unused/` subdirectories.
- Update `ngsw-manifest.json`:
  * Fix routing.
  * Update the `static.ignore` list.
  * Cache certain external resources.

Fixes #16198.

2017-04-25 15:11 UTC, gkalpak commented
@alxhub, I added external URLs in #16318 and I ran into two issues:

1. The requests to external resources have the `?ngsw-cache-bust=...` query param, which in not desirable (e.g. `unpkg.com` returns an `Invalid URL` error). It seems to me that the cache-busting only makes sense for our own resources, not external ones. Do I miss something?

2. The Google Fonts URLs (`https://fonts.googleapis.com/css?family=Droid+Sans+Mono` and `https://fonts.googleapis.com/icon?family=Material+Icons`) fail to be served fromthe cache (although the ServiceWorker does pre-fetch them). I wonder if it is because they have a query param or if it's unrelated.

Any thoughts or feedback are welcome :smiley:

2017-04-25 15:20 UTC, mary-poppins commented
The angular.io preview for 7b3144b6959bad0c0e739ea0f4a3779b6d80f3b4 is available [here][1].

[1]: https://pr16318-7b3144b6959bad0c0e739ea0f4a3779b6d80f3b4.ngbuilds.io/

2017-04-25 15:35 UTC, IgorMinar requested changes

2017-04-25 15:35 UTC, IgorMinar commented on aio/src/app/embedded/contributor/contributor.component.ts
> +  pictureBase = 'assets/images/bios/';
is this right? why don't we keep the bios with the content? we should keep content specific images together with the content that pulls it and use assets only for images used by the shell (not depended upon by any content).

2017-04-25 15:35 UTC, IgorMinar commented on aio/ngsw-manifest.json
> +    "^/assets/images/(?:bios|guide|plunker|.*/unused)/",
see.. we should actually move all the guide and plunker images under `content` and cache all the `assets`, because the stuff left should be all the bits needed by the app shell.

2017-04-25 20:10 UTC, mary-poppins commented
The angular.io preview for 162482032dc56788f904b0906a890555ffaf7f6c is available [here][1].

[1]: https://pr16318-162482032dc56788f904b0906a890555ffaf7f6c.ngbuilds.io/

2017-04-26 10:40 UTC, gkalpak commented on aio/src/app/embedded/contributor/contributor.component.ts
> +  pictureBase = 'assets/images/bios/';
For reference:
We decided to move images that are related to content (not the app shell) to `content/images/`. So, I moved `assets/images/(bios|guide|plunker)` to `content/images/(bios|guide|plunker)`.

2017-04-26 10:49 UTC, gkalpak commented
WRT https://github.com/angular/angular/pull/16318#issuecomment-297061893:

1. As explained by @alxhub, although there might be cases where the `?ngsw-cache-bust=...` query param is indeed not necessary or desirable for external resources, it is a sane default. Even for external resources, you don't want the browser to serve something that might have been cached before the current `ngsw-manifest.json` was created.
For `unpkg.com` specifically, it works if you explicitly use the URL to the file instead of relying for unpkg to infer it (e.g. use `/lunr@0.7.2/lunr.js` instead of `/lunr@0.7.2`). In any case, we decided to get `lunr` as a local dependency. 

2. With @alxhub's guidance, I got the font URLs caching working by also caching the `.woff2` requests (for the URLs included in the original font files and updating `@angular/service-worker` to v1.0.0-beta.10. (Not 100% sure if updating to beta.10 was necessary.)

2017-04-26 12:53 UTC, mary-poppins commented
The angular.io preview for 646722df0961969e61a742e1933fb9bb493fc98a is available [here][1].

[1]: https://pr16318-646722df0961969e61a742e1933fb9bb493fc98a.ngbuilds.io/

2017-04-26 13:02 UTC, gkalpak commented
Updated based on feedback (see the updated [description][1]). Probably easier to review per-commit.
@IgorMinar, feel free to TAL :smiley:

Notes:

- I didn't change `lunr` to a local dependency, because I couldn't find a simple/clean way of copying it to dist. The ServiceWorker caches it now, so only the first load (or when no ServiceWorker is available) will be affected. (Still not ideal that an `unpkg.com` outage will break our search for first-time-users. Open to suggestions.)

- There seem to be a few logos inside [assets/images/logos/][2] (which we currently pre-fetch/cache). Do we need them to be pre-fetched/cached?

- @wardbell, I moved `docs.md` from `guide/` back to `marketing/` (mainly because of 5.ii [above][1]), but I can move it back (and have a more complex RegExp in `ngsw-manifest.json`) if you want me to :smiley:

[1]: https://github.com/angular/angular/pull/16318#issue-224170262
[2]: https://github.com/gkalpak/angular/tree/646722df0961969e61a742e1933fb9bb493fc98a/aio/src/assets/images/logos

2017-04-27 08:40 UTC, petebacondarwin commented on aio/ngsw-manifest.json
> +    "^/assets/images/.*/unused/",
why do we need to ignore these if they are unused?

2017-04-27 08:43 UTC, petebacondarwin reviewed
Some of the images in https://github.com/angular/angular/pull/16318/commits/0895d23a7466bb802bc27513a67bb307641fdfc6 appear to have been modified as well as moved. Do you know why this is?

2017-04-27 08:45 UTC, petebacondarwin commented on aio/content/navigation.json
>        "hidden": true
this is the `hidden: true` that @wardbell agreed to remove last night.

2017-04-27 08:50 UTC, gkalpak commented on aio/ngsw-manifest.json
> +    "^/assets/images/.*/unused/",
They are unused, but still present in the `dist/` folder, so SW will try to fetch them. Ideally, I would remove them altogether (and then we wouldn't have to ignore them), but I wasn't sure if someone needed them around.

So, I moved them into `unused` folders and ignored them for now. Someone with more knowledge on whether they are/will be used can verify that they are indeed unnecessary and remove them altogether (but it seemed outside the scope of this PR).

2017-04-27 08:54 UTC, gkalpak commented
> Some of the images in 0895d23 appear to have been modified as well as moved. Do you know why this is?

Can you give an example. (I haven't intentionally modified any image.)

2017-04-27 08:57 UTC, petebacondarwin commented
E.g. https://github.com/angular/angular/pull/16318/files#diff-d33d2bbf86a9a435e51d309d7955313d

2017-04-27 09:07 UTC, petebacondarwin approved these changes

2017-04-27 09:14 UTC, merged

2017-04-27 09:18 UTC, gkalpak commented
For reference (wrt image changes):
GitHub limits the number of renderable files (such as images) to 25. After that, it suppresses the diff (with a "Diff not rendered") message, even if the diff is empty. No images should have changed.

From [the docs][1]:

> The maximum number of renderable files (such as images, PDFs, and GeoJSON files) in a single diff is limited to 25.

[1]: https://help.github.com/articles/limits-for-viewing-content-and-diffs-in-a-repository/#diff-limits