WIP feat(aio): api pages styling
angular/angular pull request #16327
Opened 2017-04-25 18:57 UTC by sjtrimble

- Banner class code consolidation for API pages
- Set up temporary table of contents class and file
- API pages title styling

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-04-25 19:15 UTC, mary-poppins commented
The angular.io preview for f18c6d70b0f074f941599a52db3e9a7c6c1ec702 is available [here][1].

[1]: https://pr16327-f18c6d70b0f074f941599a52db3e9a7c6c1ec702.ngbuilds.io/

2017-04-25 19:35 UTC, gkalpak requested changes
LGTM except for a couple of minor issue.

2017-04-25 19:35 UTC, gkalpak commented on aio/src/styles/2-modules/_api-list.scss
> +  .info-banner .material-icons {
This messes the search icon in the API docs search field
(I wonder what this style is for anyway.)

2017-04-25 19:35 UTC, gkalpak commented on aio/src/app/app.component.html
> +  <!--<nav id="main-table-of-contents">
This (and the corresponding CSS) seems unrelated to this PR.

2017-04-25 19:42 UTC, sjtrimble commented on aio/src/app/app.component.html
> +  <!--<nav id="main-table-of-contents">
This is intended to be the starting point of the placement for the fixed TOC but I haven't had much luck with the 'fixed' part of it ...

Do you think it's okay to leave for now, or should I remove the HTML and rename the PR to include this. I did include the description of this change in the PR description/comments.

2017-04-25 19:59 UTC, mary-poppins commented
The angular.io preview for 7303d095929f144c7eb52c48e15ffa83c63a4b7a is available [here][1].

[1]: https://pr16327-7303d095929f144c7eb52c48e15ffa83c63a4b7a.ngbuilds.io/

2017-04-25 22:29 UTC, mary-poppins commented
The angular.io preview for 8edf90902970bf3e805fb82bf17e33fef0708e75 is available [here][1].

[1]: https://pr16327-8edf90902970bf3e805fb82bf17e33fef0708e75.ngbuilds.io/

2017-04-25 23:58 UTC, mary-poppins commented
The angular.io preview for 853e1ca2af029b06b47a88e9cd468e1700e6ba30 is available [here][1].

[1]: https://pr16327-853e1ca2af029b06b47a88e9cd468e1700e6ba30.ngbuilds.io/

2017-04-26 05:15 UTC, mary-poppins commented
The angular.io preview for dacea81a609f7359b842fbfc34889ac4231ab5c5 is available [here][1].

[1]: https://pr16327-dacea81a609f7359b842fbfc34889ac4231ab5c5.ngbuilds.io/

2017-04-26 09:10 UTC, gkalpak commented on aio/src/app/app.component.html
> +  <!--<nav id="main-table-of-contents">
Generally it is not a good idea to leave dead code in (because often it ends up staying there forever), but if you are confident that you are going to work on it in the near future, I don't mind :smiley:

2017-04-26 09:13 UTC, gkalpak approved these changes
My understanding is that the API pages are still WIP (i.e. this is not the final PR for API pages), so there is little point in nitpicking on every (visual or other) issue atm.

In that sense, this LGTM. This should get in before it starts growing too big :smiley:

2017-04-26 09:42 UTC, petebacondarwin commented
I agree, we just need to fix the conflicts

2017-04-26 13:10 UTC, petebacondarwin commented
I rebased and force pushed

2017-04-26 13:27 UTC, mary-poppins commented
The angular.io preview for 95dffad7ca5f303e9af02558a8e3eaa0e6efab41 is available [here][1].

[1]: https://pr16327-95dffad7ca5f303e9af02558a8e3eaa0e6efab41.ngbuilds.io/

2017-04-26 13:31 UTC, merged