feat(compiler-cli): add i18n parameters to tsconfig
angular/angular pull request #16365
Opened 2017-04-27 07:50 UTC by ocombe

**What kind of change does this PR introduce?**
```
[x] Feature
```

**What is the current behavior?** (You can also link to an open issue here)
Right now you cannot add existing i18n parameters to tsconfig, see issue #16232

**What is the new behavior?**
You can now add parameters to your tsconfig that will be used when you don't provide cli parameters. It works with ng-xi18n and ngc. Since they both have some parameters with a similar name, those options in tsconfig have a slightly different name compared to the cli parameters (with the prefix source for ng-xi18n and the prefix target for ngc).

**Does this PR introduce a breaking change?** (check one with "x")
```
[x] No
```

2017-04-27 11:39 UTC, vicb commented on tools/@angular/tsc-wrapped/src/options.ts
> +  // you should only use this if you have one tsconfig file per locale
you can remove this line "you should ..."

2017-04-27 11:40 UTC, vicb commented on packages/compiler-cli/src/codegen.ts
> +      i18nFormat: cliOptions.i18nFormat || options.targetI18nFormat,
` || sourceFormat` at the end (useful when they are the same)

2017-04-27 11:41 UTC, vicb commented on packages/compiler-cli/src/extract_i18n.ts
> +          (cliOptions.i18nFormat || ngOptions.sourceI18nFormat) !,
Please take the opportunity of this PR to clean the `(...)!` hack.

2017-04-27 11:43 UTC, vicb commented on tools/@angular/tsc-wrapped/src/options.ts
> +  sourceI18nFormat?: string;
As a general comment on this PR, "source" is confusing because it relates to the file being written which is counter-intuitive - same for "target".

Can you think about better names ?

2017-04-27 11:43 UTC, vicb reviewed
See inline comments + need tests

2017-04-28 08:41 UTC, ocombe commented on packages/compiler-cli/src/codegen.ts
> +      i18nFormat: cliOptions.i18nFormat || options.targetI18nFormat,
For xmb/xtb source & target format are different, this could lead to bugs. The only case where this would work would be for xlf and it's already the default format.

2017-04-28 12:13 UTC, vicb commented on packages/compiler-cli/src/codegen.ts
>        if (!cliOptions.locale) {
should be `locale` ?

2017-04-28 12:15 UTC, ocombe commented on packages/compiler-cli/src/codegen.ts
>        if (!cliOptions.locale) {
I wanted to be sure if you really paid attention to the code.

Jokes aside, good catch, fixed

2017-04-28 12:16 UTC, vicb commented on packages/compiler-cli/src/codegen.ts
> +      i18nFormat: cliOptions.i18nFormat || options.i18nTranslationFormat,
move this to the top with other parameters ? 
explain why we do `|| options.i18nTranslationFormat` (ie most files contain both messages and translations)

2017-04-28 12:17 UTC, vicb commented on packages/compiler-cli/src/extract_i18n.ts
> +          cliOptions.i18nFormat || ngOptions.i18nFormat || null,
same thing here, move init to the top, missing `i18nTranslationFormat` here

2017-04-28 12:17 UTC, vicb commented on packages/compiler-cli/src/extract_i18n.ts
> +          cliOptions.i18nFormat || ngOptions.i18nFormat || null,
format could not be null -> `|| ''` at the end

2017-04-28 12:18 UTC, vicb commented on packages/compiler-cli/src/extract_i18n.ts
> +          cliOptions.outFile || ngOptions.outFile || null);
move init at the top

2017-04-28 12:18 UTC, vicb commented on packages/compiler-cli/src/extract_i18n.ts
> +          cliOptions.i18nFormat || ngOptions.i18nFormat || null,
forget my first comment, you have updated the API

2017-04-28 12:21 UTC, vicb commented on tools/@angular/tsc-wrapped/src/options.ts
> +  // strategy to use for missing translations
specify the possible values in the comment

2017-04-28 12:21 UTC, ocombe commented on packages/compiler-cli/src/extract_i18n.ts
> +          cliOptions.i18nFormat || ngOptions.i18nFormat || null,
We don't use "i18nTranslationFormat" for the extraction (this is ng-xi18n, not ngc)

2017-04-28 12:34 UTC, vicb requested changes
- see inline comments,
- add tests

2017-05-01 13:42 UTC, vicb commented on packages/compiler-cli/src/extract_i18n.ts
> +  const format = cliOptions.i18nFormat || ngOptions.i18nFormat || null;
set the default to xliff

2017-05-01 13:42 UTC, vicb commented on packages/compiler-cli/src/extractor.ts
> +  extract(formatName: string|null, outFile: string|null): Promise<void> {
revert `|null`

2017-05-01 13:46 UTC, vicb commented on packages/compiler-cli/src/main.ts
> +        (n: tsc.AngularCompilerOptions, c: tsc.NgcCliOptions, p: ts.Program, h: ts.CompilerHost) =>
why this change ?

2017-05-01 13:46 UTC, vicb commented on packages/compiler-cli/src/ngtools_api.ts
> +    return extractor.extract(options.i18nFormat || null, options.outFile || null);
same, add `xliff` by default

2017-05-02 11:38 UTC, ocombe commented on packages/compiler-cli/src/main.ts
> +        (n: tsc.AngularCompilerOptions, c: tsc.NgcCliOptions, p: ts.Program, h: ts.CompilerHost) =>
It's the only way that I found to add the unit test. I can remove it, but I'll have to remove the test as well

2017-05-10 14:28 UTC, vicb approved these changes

2017-05-10 14:29 UTC, vicb commented
LGTM, needed before merge:
- @ocombe to update the tests according to discussions,
- travis should be green (the failure does not seem to relate to the changes).

2017-05-15 23:31 UTC, vicb commented
Blocked because missing approval.

@alexeagle could you please review. Thanks.

2017-05-16 01:25 UTC, alexeagle reviewed
/cc @vikerman

2017-05-16 01:25 UTC, alexeagle commented on tools/@angular/tsc-wrapped/src/options.ts
> +  outFile?: string;
this is probably confusing.

```
"compilerOptions": {
  "outDir": "foo",
  "out": "bar"
},
"angularCompilerOptions": {
  "outFile": "baz"
}
```

I think either these options need to have i18n in the name, or be nested:

```
"angularCompilerOptions": {
  "i18n_msgs": {
    "extract": {
      "outFile": "msgs.xtb"
    },
    "merge": {
      "i18nFile": "msgs.xtb"
    }
  }
}
```

WDYT?

2017-05-16 01:25 UTC, alexeagle commented on tools/@angular/tsc-wrapped/src/options.ts
> +  locale?: string;
I was expecting multiple locales to appear here. Users shouldn't have N tsconfig files (and note that the tsconfig "extends" behavior doesn't cover unknown config properties like "angularCompilerOptions")

2017-05-16 07:49 UTC, ocombe commented on tools/@angular/tsc-wrapped/src/options.ts
> +  locale?: string;
This is the locale used for extracted messages, which is the main locale of your application. There is only one here since you only do one extraction.
You are referring to `translationLocale?: string;` which is the locale used when you compile the application. I had a comment there that @vicb made me remove which was something like "only use this if you have one tsconfig file / locale".
I agree that it would be better if we could compile all locales in one command, but that is not possible yet. There's a bit refactor coming for the compiler and it will probably change at that point, but for now we can only compile for one locale.

2017-05-16 07:51 UTC, ocombe commented on tools/@angular/tsc-wrapped/src/options.ts
> +  outFile?: string;
We used the same name as the current cli options (when possible). We can nest them though, what do you think @vicb ?

2017-07-27 03:29 UTC, vikerman commented
Does this have google3 impact?

2017-08-05 00:24 UTC, vicb commented on tools/@angular/tsc-wrapped/src/options.ts
> +  outFile?: string;
it's not possible to nest the options:
`    type CompilerOptionsValue = string | number | boolean | (string | number)[] | string[] | MapLike<string[]> | PluginImport[];
`

2017-08-07 16:41 UTC, alexeagle commented on tools/@angular/tsc-wrapped/src/options.ts
> +  outFile?: string;
Isn't `MapLike<string[]>` the way to nest options? TypeScript does nest them, eg. `compilerOptions.paths`

2017-08-11 18:17 UTC, vicb commented
closing as implemented in the new 5.x compiler flow - see https://github.com/angular/angular/pull/18494

2017-08-11 18:17 UTC, closed without merging