WIP docs(aio): Added developer guide on RxJS
angular/angular pull request #16452
Opened 2017-05-01 04:13 UTC by brandonroberts

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

Developer guide on observable usage. This was migrated over from https://github.com/angular/angular.io/pull/3047

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-05-01 04:28 UTC, mary-poppins commented
The angular.io preview for 49b1b705870d35e2c53755d71641e5772643f6bb is available [here][1].

[1]: https://pr16452-49b1b705870d35e2c53755d71641e5772643f6bb.ngbuilds.io/

2017-05-08 01:22 UTC, mary-poppins commented
The angular.io preview for 7d154136e25bee0b4f2e29a30788a7136d83d0d2 is available [here][1].

[1]: https://pr16452-7d154136e25bee0b4f2e29a30788a7136d83d0d2.ngbuilds.io/

2017-05-08 02:38 UTC, mary-poppins commented
The angular.io preview for 1afc491617a7c397e692de72997403f36651472a is available [here][1].

[1]: https://pr16452-1afc491617a7c397e692de72997403f36651472a.ngbuilds.io/

2017-06-12 02:19 UTC, mary-poppins commented
The angular.io preview for a481925ced0ecc78cb3a7a425e89b1acf01b240b is available [here][1].

[1]: https://pr16452-a481925ced0ecc78cb3a7a425e89b1acf01b240b.ngbuilds.io/

2017-06-12 11:59 UTC, gkalpak commented on aio/content/navigation.json
> +          "url": "guide/pipes",
Is it intentional that pipes are added here, while they are already present above (around line 188)?

2017-06-13 00:29 UTC, brandonroberts commented on aio/content/navigation.json
> +          "url": "guide/pipes",
I doubt it. Probably happened during a rebase.

2017-07-03 14:07 UTC, Foxandxss requested changes
Where is the plunker? Rxjs is a complex subject and there is a lot of examples that you don't know what kind of output to expect.

Continuing on that, there are a few simple snippets that could use some comments saying what is the expected output.

I saw you named hot and cold but there is no more on it. A link would be nice.

There is a part where you give a few resources link. That is better to be at the end. To not distract people from reading your guide.

I find the first part (Observable is a function) to be too complicated.

2017-07-24 13:05 UTC, mary-poppins commented
You can preview 7fa4b70 at https://pr16452-7fa4b70.ngbuilds.io/.

2017-07-27 13:29 UTC, mary-poppins commented
You can preview 84c07c9 at https://pr16452-84c07c9.ngbuilds.io/.

2017-08-31 13:26 UTC, mary-poppins commented
You can preview 9012622 at https://pr16452-9012622.ngbuilds.io/.

2017-09-03 04:16 UTC, mary-poppins commented
You can preview 0bb8174 at https://pr16452-0bb8174.ngbuilds.io/.

2017-09-04 23:15 UTC, mary-poppins commented
You can preview a705287 at https://pr16452-a705287.ngbuilds.io/.

2017-09-05 02:25 UTC, mary-poppins commented
You can preview 4c46d6c at https://pr16452-4c46d6c.ngbuilds.io/.

2017-09-05 02:35 UTC, mary-poppins commented
You can preview a4a1f76 at https://pr16452-a4a1f76.ngbuilds.io/.

2017-09-05 03:04 UTC, mary-poppins commented
You can preview f840570 at https://pr16452-f840570.ngbuilds.io/.

2017-09-25 12:40 UTC, mary-poppins commented
You can preview 7ab406e at https://pr16452-7ab406e.ngbuilds.io/.

2017-10-21 03:44 UTC, mary-poppins commented
You can preview bd0bad4 at https://pr16452-bd0bad4.ngbuilds.io/.

2018-01-04 06:56 UTC, jenniferfell commented
@jasonaden :  Recommendation here? Has all of this been incorporated into the new doc you're working on, so this can be closed? Other next steps on this PR? Thanks.

2018-01-24 00:17 UTC, jenniferfell commented
@jasonaden Can we close this as a duplicate of https://github.com/angular/angular/pull/21423 ?

2018-03-16 09:43 UTC, splincode commented
@brandonroberts what is the status of your pull request? is it still relevant? please fix conflicts if they exist

2018-03-20 01:04 UTC, brandonroberts commented
@splincode this guide has been folded into the Observables guide except for the marble testing area, which will come along later. I think this can be closed.

2018-03-20 01:04 UTC, closed without merging