WIP feat(aio): implement ScrollSpy service (to highlight currently viewed section)
angular/angular pull request #16703
Opened 2017-05-10 17:29 UTC by gkalpak

Seems to work nicely, but no tests yet 😳
It turned out way more complicated than I wanted t to be. Alternative ideas or suggestions welcome 😕

2017-05-10 17:56 UTC, petebacondarwin commented on aio/src/app/shared/scroll-spy.service.ts
> +      unspy: () => this.unspy(spiedGroup)
Given that observables are inherently unsubscribable, it would seem that this `unspy` is unnecessary.
Why not put the logic of `ScrollSpyService.unspy` into the logic to handle the observable being unsubscribed from?

2017-05-10 18:46 UTC, mary-poppins commented
The angular.io preview for 30f99dc8aa9422d3a26a29dbe367b920c1afe055 is available [here][1].

[1]: https://pr16703-30f99dc8aa9422d3a26a29dbe367b920c1afe055.ngbuilds.io/

2017-05-10 20:13 UTC, gkalpak commented on aio/src/app/shared/scroll-spy.service.ts
> +      unspy: () => this.unspy(spiedGroup)
I think, because there is no guarantee that the consumer will actually subscribe to `active`.

2017-05-12 01:20 UTC, wardbell requested changes
I have my snowflake quibbles.

The significant issue is that the TOC does not scroll when the selected TOC item is not visible.

Look at the Routing guide to see this problem. As you scroll through that long guide, eventually the current TOC item is no longer visible on the right side TOC.

I suggest that when the current TOC item is no longer visible, the right-side TOC should scroll the current TOC item into view, possibly the middle of the TOC panel.

Thoughts?

2017-05-12 01:20 UTC, wardbell commented on aio/src/testing/scroll-spy.service.ts
> +export class MockScrollSpyService {
Why create a `MockScrollSpyService` way out here?

IMO, following DAMP principles, we should create mock/test classes where they are used so that the reader isn't wandering around the code base. They shouldn't be in far away files unless ...

1. they are reused significantly
2. they have non-trivial implementations 

This is a trivial mock class, referenced (but not yet used!) in one spec file only and unlikely to be reused. YAGNI?

I could not, in good conscience, block this PR for this objection, particularly as we have decided to postpone testing style discussions until after our release.

2017-05-12 01:20 UTC, wardbell commented on aio/src/app/shared/toc.service.spec.ts
> +      { provide: ScrollSpyService, useValue: new MockScrollSpyService() },
Why `useValue: new MSSS()` instead of `useClass: MSSS` ?

2017-05-12 01:20 UTC, wardbell commented on aio/src/app/shared/toc.service.ts
> +    return Array.prototype.filter.call(headings, skipNoTocHeadings);
I don't really mind a for loop but I see you do ;-)

2017-05-17 16:30 UTC, mary-poppins commented
The angular.io preview for 0a97dfc950996406d0cfd31a923ed4223c3c4cbd is available [here][1].

[1]: https://pr16703-0a97dfc950996406d0cfd31a923ed4223c3c4cbd.ngbuilds.io/

2017-05-17 22:34 UTC, mary-poppins commented
The angular.io preview for 98e22145db209aaaca5bd9886eeaa1ea52790e22 is available [here][1].

[1]: https://pr16703-98e22145db209aaaca5bd9886eeaa1ea52790e22.ngbuilds.io/

2017-05-18 09:10 UTC, gkalpak commented on aio/src/testing/scroll-spy.service.ts
> +export class MockScrollSpyService {
Fair enough :smiley: If this turns out to only be used in one place I will move it into the spec file.

2017-05-18 11:12 UTC, petebacondarwin commented on aio/src/app/embedded/toc/toc.component.ts
> +          .takeUntil(this.onDestroy)
totally irrelevant here but I think a better convention would be to rename `this.onDestroy` to `this.destroyEvent`. This is because `onDestroy` sounds like a handler for the destroy event but actually it is an event source (i.e. an `Observable`).

2017-05-18 11:14 UTC, petebacondarwin commented on aio/src/app/embedded/toc/toc.component.ts
> +            if (index === null || index >= items.length) {
Why not set `this.activeItemIndex` in this subscribe, rather than creating an additional one above?

2017-05-18 21:33 UTC, gkalpak commented on aio/src/app/embedded/toc/toc.component.ts
> +            if (index === null || index >= items.length) {
I tried hard to do it like that, but I was getting a error that some value changed after it had been checked (I think it was the `i === activeIndex` in the view).

I don't know much about the ViewChildren and change-detection, so I amy be missing something. (Suggestions welcome :smiley:)

2017-05-18 21:34 UTC, mary-poppins commented
The angular.io preview for bdb8face4c49c0f716af288561bd13d7e37e30e6 is available [here][1].

[1]: https://pr16703-bdb8face4c49c0f716af288561bd13d7e37e30e6.ngbuilds.io/

2017-05-18 21:38 UTC, mary-poppins commented
The angular.io preview for 26fe492f7a170bbb9659f6fef0b66829d37f8d59 is available [here][1].

[1]: https://pr16703-26fe492f7a170bbb9659f6fef0b66829d37f8d59.ngbuilds.io/

2017-05-18 21:39 UTC, gkalpak commented
This is now ready for review. I also added the scrolling of the selected ToC item into view (if it is not visible).
The unit tests for `ScrollSpyService` are not very fine-grained, but I felt that putting more effort/time into unit/e2e testing (for this non-critical feature) wasn't worth it at the moment.

2017-05-18 21:51 UTC, mary-poppins commented
The angular.io preview for 7578b998826a1b031b587fdcc047e677df1a86a9 is available [here][1].

[1]: https://pr16703-7578b998826a1b031b587fdcc047e677df1a86a9.ngbuilds.io/

2017-05-19 01:51 UTC, sjtrimble commented
@gkalpak Is the "active" class assigned to the a tag the one that we'll use for styling? If so, can we make it applicable to the li element instead so I can add the circle before and then dig down into the a tag for styling as well? (I have made the design refresh css code work this way right now)

... OR is that class specifically on the a tag being used for another reason that I'm missing?

2017-05-19 09:03 UTC, gkalpak commented
> Is the "active" class assigned to the a tag the one that we'll use for styling? If so, can we make it applicable to the li element instead?

Yes and sure.

> so I can add the circle before

I thought there would be no circles 😈

##
I'll move the class.

2017-05-19 09:39 UTC, petebacondarwin commented on aio/src/app/embedded/toc/toc.component.spec.ts
> +        expect(newActive).not.toBe(oldActive);
Doesn't this behaviour depend upon whether Angular reuses DOM nodes in `ngFor` or not?

2017-05-19 09:56 UTC, gkalpak commented on aio/src/app/embedded/toc/toc.component.spec.ts
> +        expect(newActive).not.toBe(oldActive);
Good point 👍

2017-05-19 09:57 UTC, petebacondarwin commented on aio/src/app/embedded/toc/toc.component.spec.ts
> +        expect(newActive).not.toBe(oldActive);
I wondered if this test should just insert a new item at the start of the array, rather than replacing it altogether? That would mean that the nodes might just shift and not be replaced but the component would need to move the active class to a different node?

2017-05-19 10:03 UTC, gkalpak commented on aio/src/app/embedded/toc/toc.component.spec.ts
> +        expect(newActive).not.toBe(oldActive);
I like it. Let's do both :smiley:

2017-05-19 10:05 UTC, petebacondarwin commented on aio/src/app/shared/scroll-spy.service.ts
> +  needsRecalibration(scrollTop: number, topOffset: number) {
A comment or two in this class to explain the goal and approach of "(re)calibration" would save time in the future when people come to maintain this code.

2017-05-19 10:11 UTC, petebacondarwin commented on aio/src/app/shared/scroll-spy.service.ts
> +      this.scrollEvents.subscribe(() => this.onScroll());
The way this service is architected, it looks like we might be able to spy on multiple sets of `elements` at once. If that is the case, then it looks to me like we would be creating unnecessary additional subscriptions to the `resizeEvents` and `scrollEvents` observables for the 2nd and subsequent elements sets.

Given that right now we don't spy on more than one set at a time, this doesn't matter. But if we did then we would need a more clever subscribe/unsubscribe arrangement (e.g. through `.share()`, which does a `.refCount()` if I remember correctly).

2017-05-19 10:13 UTC, petebacondarwin commented on aio/src/app/shared/scroll-spy.service.ts
> +      this.scrollEvents.subscribe(() => this.onScroll());
Actually, in the case of spying on multiple sets of elements, we would probably want to specify the scroll top (i.e. the scroll container dimensions) separately for each set.

2017-05-19 10:15 UTC, gkalpak commented on aio/src/app/shared/scroll-spy.service.ts
> +      this.scrollEvents.subscribe(() => this.onScroll());
Yes, we can spy on multiple sets of elements, but there is only one subscription for each `resize` and `scroll` active at time. Note, we only subscribe when the first element set is spied on and unsubscribe when the last one is "unspied".

2017-05-19 10:16 UTC, petebacondarwin commented on aio/src/app/shared/scroll-spy.service.ts
> +      this.scrollEvents.subscribe(() => this.onScroll());
And given that we are not planning on doing any of that, we could probably make this service simpler.

2017-05-19 10:22 UTC, petebacondarwin approved these changes
A few Qs but nothing to block the merge.

2017-05-19 10:23 UTC, petebacondarwin commented on aio/src/app/shared/scroll-spy.service.ts
> +      unspy: () => this.unspy(spiedGroup)
which indicates to me that we are doing too much work upfront and not allowing our observables to be lazy enough :-)

2017-05-19 10:25 UTC, petebacondarwin commented
Back to you @gkalpak - please fix up the changes for @sjtrimble, squash and apply the merge label.

2017-05-19 11:13 UTC, petebacondarwin commented on aio/src/app/shared/scroll-spy.service.ts
> +      this.scrollEvents.subscribe(() => this.onScroll());
Oh yeah, I didn't notice the `if (!this.spiedElementGroups.length) {`

2017-05-19 14:31 UTC, sjtrimble commented
@gkalpak circle will only appear on active item for clear indication of current location. Regardless, it gives us more flexibility for styling purposes.

2017-05-19 18:34 UTC, gkalpak commented on aio/src/app/embedded/toc/toc.component.spec.ts
> +        expect(newActive).not.toBe(oldActive);
Done.

2017-05-19 22:14 UTC, gkalpak commented on aio/src/app/shared/scroll-spy.service.ts
> +  needsRecalibration(scrollTop: number, topOffset: number) {
While adding comments, I realized that this check is not necessary. The reason my original (less expensive) check didn't work was a bug: I was checking for changes in the viewport height (`body.clientHeight`), while I should be checking for changes in the total content height (`body.scrollHeight`).

<sub>(I 'll still add comments to the rest of methods :wink:)</sub>

2017-05-19 23:41 UTC, mary-poppins commented
The angular.io preview for c333f8731f53edf01dc6d59c45ebb2f91d685c98 is available [here][1].

[1]: https://pr16703-c333f8731f53edf01dc6d59c45ebb2f91d685c98.ngbuilds.io/

2017-05-19 23:42 UTC, gkalpak commented on aio/src/app/shared/scroll-spy.service.ts
> +      unspy: () => this.unspy(spiedGroup)
I am actually very tempted to re-architecture `ScrollSpy`, so that it doesn't  keep track of the `ScrollSpiedElementGroup`s and `spyOn` would just return a cold, shareable observable (with access to shared, ref-counting `onResize`/`onScroll` observables). But I think I'll pass :smiley:

I will add it to a list of possible future enhancements/improvements for scroll-spying, though.

2017-05-20 00:12 UTC, gkalpak commented
Rebased, addressed feedback and simplified a bit (originally in [c333f87][1], now squashed into the first commit). Adding the `merge` label and I'll create an issue to track possible future improvements.

Thx for the reviews!

[1]: https://github.com/angular/angular/pull/16703/commits/c333f8731f53edf01dc6d59c45ebb2f91d685c98

2017-05-20 00:18 UTC, mary-poppins commented
The angular.io preview for 18e66ce169aecf66ecf75e59593ae6da5277bfe4 is available [here][1].

[1]: https://pr16703-18e66ce169aecf66ecf75e59593ae6da5277bfe4.ngbuilds.io/

2017-05-20 11:08 UTC, merged