feat: introduce `TestBed.overrideProvider`
angular/angular pull request #16725
Opened 2017-05-11 18:20 UTC by tbosch

This allows to overwrite all providers for a token, not matter
where they were defined.

This can be used to test JIT and AOT’ed code in the same way.

Design doc: https://docs.google.com/document/d/1VmTkz0EbEVSWfEEWEvQ5sXyQXSCvtMOw4t7pKU-jOwc/edit?usp=sharing

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-05-11 20:59 UTC, vicb commented on packages/core/src/view/entrypoint.ts
> +      private _ngModuleDefFactory: NgModuleDefinitionFactory, ) {
nit: do we want the trailing coma here ?

2017-05-11 21:01 UTC, vicb commented on packages/core/src/view/entrypoint.ts
> +  get moduleType(): Type<any> { return this._moduleType; }
IIRC using `readonly` is better for code size.

2017-05-11 21:06 UTC, vicb commented on packages/core/src/view/services.ts
> +  if (!providerOverrides.size) {
nit `!size` is very JS, could you size `size === 0` instead

2017-05-11 21:06 UTC, vicb commented on packages/core/src/view/services.ts
> +  if (!elementIndicesWithOverwrittenProviders.length) {
same nit here

2017-05-11 21:17 UTC, vicb approved these changes
a few nits, otherwise :+1:

2017-05-12 00:28 UTC, tbosch commented on packages/core/src/view/entrypoint.ts
> +      private _ngModuleDefFactory: NgModuleDefinitionFactory, ) {
Changed

2017-05-12 00:29 UTC, tbosch commented on packages/core/src/view/entrypoint.ts
> +  get moduleType(): Type<any> { return this._moduleType; }
Good point. Changed.

2017-05-12 00:30 UTC, tbosch commented on packages/core/src/view/services.ts
> +  if (!providerOverrides.size) {
Changed, but I like JS :-)

2017-05-12 00:30 UTC, tbosch commented on packages/core/src/view/services.ts
> +  if (!elementIndicesWithOverwrittenProviders.length) {
Changed

2017-05-12 19:26 UTC, IgorMinar requested changes

2017-05-12 19:26 UTC, IgorMinar commented on tools/public_api_guard/core/testing.d.ts
> +    static overrideProvider(token: any, provider: {
shouldn't this api be closer to the regular provider definition? why doesn't `overrideProvider` just take `Provider` as the only argument?

2017-05-12 22:32 UTC, tbosch commented on tools/public_api_guard/core/testing.d.ts
> +    static overrideProvider(token: any, provider: {
Why not the regular `Provider`:
- we require `deps` as we don't want to rely on runtime metadata.
- that's also the reason why a regular `useClass` does not work.

Having the `token` be the first argument is more inline with the other `override` methods as well.

2017-05-12 22:32 UTC, tbosch commented on packages/core/testing/src/test_bed.ts
> +  static overrideProvider(token: any, provider: {useValue: any;}): void;
How can I get a preview with the new docs infrastructure?

2017-05-12 23:47 UTC, IgorMinar commented on tools/public_api_guard/core/testing.d.ts
> +    static overrideProvider(token: any, provider: {
ok. that makes sense. thanks!

2017-05-12 23:47 UTC, IgorMinar approved these changes

2017-05-15 07:49 UTC, gkalpak commented on packages/core/testing/src/test_bed.ts
> +  static overrideProvider(token: any, provider: {useValue: any;}): void;
(You should have gotten a preview (comment with link on this PR), but didn't due to a bug on master. It has been fixed, so rebasing on latest master will create a preview.)

2017-05-15 20:12 UTC, merged