fix(aio): remove searchbox shrink animation
angular/angular pull request #16804
Opened 2017-05-15 20:11 UTC by wardbell

In mobile mode, the search box animated to a smaller size when you typed in the box, presumably to make more room to type a longer search term. The animation is both distracting and unnecessary.

This PR has a wide and narrower searchbox but does not animate. Even the narrower width for mobile is wide enough to accommodate the longest typical search term (e.g., "ahead-of-time compilation").

<hr>

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-05-15 20:21 UTC, mary-poppins commented
The angular.io preview for b58e1e54c1c4fa3b8a3966d928207587a10064d5 is available [here][1].

[1]: https://pr16804-b58e1e54c1c4fa3b8a3966d928207587a10064d5.ngbuilds.io/

2017-05-15 20:39 UTC, petebacondarwin approved these changes

2017-05-16 08:22 UTC, gkalpak requested changes
This doesn't look right on small screens:
![small-screen](https://cloud.githubusercontent.com/assets/8604205/26096403/bbbb61c6-3a29-11e7-976b-c21c6d7eec90.png)

I like the fixed width (i.e. not animating when focused/blurred), but it should take into account smaller screens (e.g. be switching from a hard-coded value to a percentage).

2017-05-16 08:41 UTC, petebacondarwin commented
That's a pretty small screen @gkalpak  :-) It is fine on my "fairly old" S6!
Looking at the screenshot, I would say that the problem is the menu button is taking up too much space, pushing the logo over too much.

2017-05-16 08:54 UTC, gkalpak commented
I wasn't sure what is the min resolution we target/support. I just used the smaller one in Chrome DevTools.
We can also start handing out "fairly old" S6s to all visitors 😛

2017-05-16 08:58 UTC, petebacondarwin commented
How about we switch to a flexbox solution, where the search box takes up all the available space, with a max-width? Then we wouldn't need to use a responsive breakpoint change at all.

2017-05-16 16:31 UTC, wardbell commented
HEY ... That is an unrelated problem, tackled in a separate PR #16803

2017-05-16 16:33 UTC, wardbell commented
@sjtrimble Choose this approach. I don't know that a searchbox that took up all remaining space is a desirable outcome. It's certainly not my call. We can hand this over to her.

2017-05-16 18:36 UTC, IgorMinar approved these changes

2017-05-17 00:08 UTC, wardbell commented
At standup today @IgorMinar confirmed that he did _not_ want a flexbox to let search box consume remaining space (a huge searchbox on wide screens is undesirable) and he does not think we should worry today about devices that are 320px wide (which is when the icons on toolbar overlap).

Let's merge it.

2017-05-17 01:02 UTC, sjtrimble commented
I liked the expanding animation :( What if we cap the max width of the search box expand?

2017-05-17 07:22 UTC, merged

2017-05-17 07:24 UTC, petebacondarwin commented
I merged this, although I would be happy to see an improved design from @sjtrimble. But that should not be a priority, given the marketing refresh is still outstanding.