fix(aio): replace headers on the temporary marketing page
angular/angular pull request #16825
Opened 2017-05-16 19:33 UTC by wardbell

closes #16824
Although this page is being replaced (#16228), current page has annoying anchor headers. Remove them, replacing h1/h2/h3 with title/section/article and applying the respective header styles to these semantic tags.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2017-05-16 19:41 UTC, mary-poppins commented
The angular.io preview for 14a74e02430db27913655f6b112f8390c08a3c46 is available [here][1].

[1]: https://pr16825-14a74e02430db27913655f6b112f8390c08a3c46.ngbuilds.io/

2017-05-16 19:43 UTC, mary-poppins commented
The angular.io preview for ab569acdf1cf1ad26d706eb26308d0ae6a23fac4 is available [here][1].

[1]: https://pr16825-ab569acdf1cf1ad26d706eb26308d0ae6a23fac4.ngbuilds.io/

2017-05-16 20:31 UTC, gkalpak approved these changes
IIRC this has already been discussed and it's been decided to use `title`/`section`/`article` on marketing pages to avoid the link. Given that LGTM

2017-05-16 20:31 UTC, gkalpak commented on aio/content/marketing/index.html
> +    <title class="text-headline">One framework. Mobile &amp; desktop.</title>
No `<br>` inside `<title>` 😞

2017-05-17 16:23 UTC, petebacondarwin requested changes
Sorry I don't know what was agreed but this is a misuse of HTML semantic elements.

For example:

> The section element represents a generic document or application section…The section element is not a generic container element. When an element is needed only for styling purposes or as a convenience for scripting, authors are encouraged to use the div element instead. A general rule is that the section element is appropriate only if the element’s contents would be listed explicitly in the document’s outline.

Further the `title` tag is only valid inside the `head` tag and so should not be used here.

Moreover the generic styling applied in the _typography.scss, making all `title`, `section` and `article` tags match the styling of `h1`, `h2` and `h3` seems wrong. For instance, a section would normally contain prose (including a heading) and would not expect to be styled like a heading; and an `article` is a higher level concept than a `section`.

I believe we should simply use `div` tags to do this styling.

2017-05-17 16:53 UTC, sjtrimble commented
Any chance we can hold on this - I have the divs already updated with the appropriate classes assigned and other classes updated.

2017-05-18 17:07 UTC, wardbell commented
@petebacondarwin Good point about `<title>`. I see the point. So we should use styled `<div>`. Closing as this isn't the right approach.

2017-05-18 17:07 UTC, closed without merging