feat(testability): Improvements to the Testability API.
angular/angular pull request #16863
Opened 2017-05-18 06:56 UTC by heathkit

Allow passing an optional timeout to Testability's whenStable(). If
specified, if Angular is not stable before the timeout is hit, the
done callback will be invoked with a list of pending macrotasks.

Also, allows an optional update callback, which will be invoked whenever
the set of pending macrotasks changes. If this callback returns true,
the timeout will be cancelled and the done callback will not be invoked.

Implements #15917

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

`Testability.whenStable()` will wait an indefinite amount of time for Angular to become stable. Protractor relies on a script timeout to know when waiting has timed out (typically longer than 10 seconds or so).

**What is the new behavior?**

Users can now pass a timeout to `whenStable()`. If there are still macrotasks pending when the timeout occurs, the callback will receive a list of pending tasks (provided by the TaskTracking zone spec). 

`whenStable()` also now accepts an optional callback to invoke whenever the state of pending macrotasks changes. If this callback returns true, `whenStable()` will cancel the pending done callback, allowing users more control over which macrotasks they wait for.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

2017-05-18 23:42 UTC, juliemr commented on packages/core/test/testability/testability_spec.ts
> +             testability.whenStable(execute, 1000, execute2);
Maybe instead of `execute2` make a new spy and call it something like `updateCallback`?

2017-05-18 23:42 UTC, juliemr commented on packages/core/src/testability/testability.ts
> +  // on NodeJS it returns a Timer.
Could it be a `number|Timer` then?

2017-05-18 23:42 UTC, juliemr commented on packages/core/src/testability/testability.ts
> +          let cb = (this._callbacks.pop() as WaitCallback);
Why is casting here necessary? Shouldn't TS know it's an array of `WaitCallback`s?

2017-05-18 23:42 UTC, juliemr commented on packages/core/src/testability/testability.ts
> +   *    pending macrotasks changes. If this callback returns true doneCb will not be invoked.
... and no further updates will be issued.

2017-05-20 11:52 UTC, heathkit commented on packages/core/test/testability/testability_spec.ts
> +      it('should not call whenstable callbacks when there are pending counts', fakeAsync(() => {
Done

2017-05-20 11:52 UTC, heathkit commented on packages/core/test/testability/testability_spec.ts
> +
Done

2017-05-20 11:52 UTC, heathkit commented on packages/core/test/testability/testability_spec.ts
> +             testability.whenStable(execute, 1000, execute2);
Done

2017-05-20 11:54 UTC, heathkit commented on packages/core/src/testability/testability.ts
> +  // on NodeJS it returns a Timer.
The problem is Timer is only defined in the NodeJS typings, which is only brought in for the platform-server tsconfig. I can't figure out a type that builds for both browser and server platforms, since in the browser setTimeout returns a number.

Of course, with Zone.js, setTimeout returns the same thing on both platforms - a Zone task. So the typings are wrong, anyway  ¯\_(ツ)_/¯

2017-05-20 11:54 UTC, heathkit commented on packages/core/src/testability/testability.ts
> +          let cb = (this._callbacks.pop() as WaitCallback);
I accidentally dropped the not null assertion `!`, so I needed a cast. I put it back, but I do find the`!` a little easy to miss.

2017-05-20 11:54 UTC, heathkit commented on packages/core/src/testability/testability.ts
> +   *    pending macrotasks changes. If this callback returns true doneCb will not be invoked.
Done

2017-05-22 20:03 UTC, juliemr commented
LGTM, cc @vikerman for additional approval.

2017-05-22 20:04 UTC, juliemr approved these changes

2017-05-22 23:59 UTC, heathkit commented
PTAL again - I had to make some slight changes to get CI to pass - updated the public API. Also changed it so you only get an error if the task tracking zone isn't available if you pass a timeout or update callback to whenStable()

2017-05-30 21:07 UTC, vikerman commented
LGTM - can we add an end to end test with Protractor for this?

2017-05-30 21:07 UTC, vikerman approved these changes

2017-06-02 19:09 UTC, heathkit commented
Added an integration test for whenStable() timeout.

2017-06-02 19:09 UTC, juliemr commented
I believe Vikram said that Igor should take a look at this - ping @IgorMinar

2017-06-05 18:28 UTC, mhevery requested changes

2017-06-05 18:28 UTC, mhevery commented on packages/core/src/testability/testability.ts
> +export type UpdateCallback = (tasks: PendingMacrotask[]) => boolean;
`UpdateCallback` and `DoneCallback` should show up in the API guard. The fact that they don't implies that they are not visible to the developer (ie they are not exported at top level).

2017-06-07 00:01 UTC, heathkit commented on tools/public_api_guard/core/core.d.ts
> +    whenStable(doneCb: DoneCallback, timeout?: number, updateCb?: UpdateCallback): void;
Fixed.

2017-06-07 00:02 UTC, heathkit commented on packages/core/src/testability/testability.ts
> +export type UpdateCallback = (tasks: PendingMacrotask[]) => boolean;
Fixed.

2017-06-16 00:20 UTC, IgorMinar requested changes
How do we expect developers to receive this update?

I suspect that once they update to karma that depends on this API they will get the missing zone spec error, not understanding what that means or what to do about it.

If they read up on the change in some changelog they'll figure out that they need to add the new zone spec.

If they do add these zone spec, would they know how to remove them in production?

And if they are not removed from production builds, do we understand the performance impact of having task tracking enabled all the time?

It seems to me that the PR as is will create a lot of pain for developers not suspecting or understanding this change. Am I missing something?

2017-06-16 00:20 UTC, IgorMinar commented on packages/core/src/testability/testability.ts
> +  /** @deprecated pending requests are now tracked with zones */
does this mean that the old way of using this api still works? what happens if you have task tracking enabled and you use older protractor that doesn't have the task tracking support yet? Will it just work?

2017-06-16 00:20 UTC, IgorMinar commented on tools/public_api_guard/core/core.d.ts
> +export declare type DoneCallback = (didWork: boolean, tasks?: PendingMacrotask[]) => void;
Do we have to export these types? Can't we just inline them?

It's weird that someone can do `import {DoneCallback} from '@angular/core';` - not only that the name is too ambiguous, I'm not sure if we want to be on the hook to support such api if someone decides to create their implementation.

2017-06-16 00:20 UTC, IgorMinar commented on tools/public_api_guard/core/core.d.ts
> +export interface PendingMacrotask {
same as above. we should expose as little as possible. Do we need to provide all of this type info?

2017-06-16 00:20 UTC, IgorMinar commented on tools/public_api_guard/core/core.d.ts
> +export declare type UpdateCallback = (tasks: PendingMacrotask[]) => boolean;
inline (as above)?

2017-06-16 18:41 UTC, heathkit commented on tools/cjs-jasmine/index-tools.ts
> +require('zone.js/dist/task-tracking.js');
No, the timeout and update callback are optional. If those aren't passed, testability should continue to work as before.

2017-06-16 18:41 UTC, heathkit commented on packages/examples/core/testability/ts/whenStable/e2e_test/testability_example_spec.ts
> +    it('', (done) => {
oops, fixed :)

2017-06-16 18:42 UTC, heathkit commented on packages/core/src/testability/testability.ts
> +  /** @deprecated pending requests are now tracked with zones */
Yes, the old way of using the API should still work without errors. If task tracking is enabled but Protractor isn't passing an update callback, it will just work with the current behavior.

2017-06-16 18:43 UTC, heathkit commented on packages/core/src/testability/testability.ts
> +   * Wait for angular to be stable with a timeout. If the timeout is hit before Angular becomes
Done

2017-06-16 18:44 UTC, heathkit commented on packages/core/src/testability/testability.ts
> +      throw new Error('Task tracking zone required when using whenStable() with a timeout!');
I tried to make it more clear. Also, this API isn't really intended for end users as much as it is for tool developers, like Protractor. On the Protractor side, we'll try to turn this into a more acitonable, understandable error.

2017-06-16 18:46 UTC, heathkit commented on tools/public_api_guard/core/core.d.ts
> +export declare type DoneCallback = (didWork: boolean, tasks?: PendingMacrotask[]) => void;
Yeah. I kind of like having the types for the callbacks available so I know what parameters they need to accept, but it's probably not a good thing to have this in the public API. The Protractor side of this is written in ES5, anyway, so it's not like I'd actually be able to use these types yet.

2017-06-16 18:46 UTC, heathkit commented on tools/public_api_guard/core/core.d.ts
> +export interface PendingMacrotask {
I'll just make this Function.

2017-06-16 18:46 UTC, heathkit commented on tools/public_api_guard/core/core.d.ts
> +export declare type UpdateCallback = (tasks: PendingMacrotask[]) => boolean;
see above

2017-06-16 19:19 UTC, heathkit commented
> How do we expect developers to receive this update?
>
> I suspect that once they update to karma that depends on this API they will get the missing zone spec error, not understanding what that means or what to do about it.

That should not happen - at least it's not the intention. The error for the missing zone spec is only thrown when someone tries to call `whenStable()` with an update callback. Protractor's current behavior should not be affected. 

The current behavior for Protractor is to pass a done callback and wait forever. The timeout is actually handled by WebDriver's script execution timeout. Moving the timeout and task tracking logic to Testability will allow us to greatly simplify Protractor's [browser.waitForAngular](https://github.com/angular/protractor/blob/master/lib/browser.ts#L627)
 
> If they read up on the change in some changelog they'll figure out that they need to add the new zone spec.
> 
> If they do add these zone spec, would they know how to remove them in production?

That's a good point, which Misko brought up when we talked this idea over with him. The goal is to fix that with https://github.com/angular/angular/pull/17390, which adds a way to explicitly set which zone specs get loaded by setting flags in session state. The idea is that if `NG_DEFER_BOOTSTRAP` is in `window.name` (which is how Protractor signals to AngularJS that it's under test and needs to load mock modules and such), then the task tracking zone is enabled. So users that want to use Protractor's task tracking would need to always include the zone spec (similar to how they include long-stack-trace), but it will only be forked during a Protractor test.

> It seems to me that the PR as is will create a lot of pain for developers not suspecting or understanding this change. Am I missing something?

The goal of this PR is to preserve current behavior, but allow us to add task tracking in future Protractor releases. This will provide better debugging information when Protractor times out waiting for stability, and will also enable us to build a more high-level API for waiting on macrotasks. The change should be transparent. If Protractor attempts to use task tracking but the zone isn't present, it can log a warning (or error or whatever we decide is appropriate).

Once https://github.com/angular/angular/pull/17390 is in we'll be able to continue this work on the Protractor side. We're also planning on doing the same changes to whenStable for AngularJS.

2018-02-07 02:36 UTC, naomiblack commented
Nudging this issue -- are there more actions required before this can be merged? We (heathkit/juliemr) believe this is ready to go. Could you clarify next steps to get this change merged in?

2018-02-08 18:07 UTC, mhevery approved these changes

2018-02-08 18:07 UTC, mhevery commented
@IgorMinar can you approve to get this merged.

2018-03-01 00:53 UTC, splincode commented
@IgorMinar  What is the status of the task?

2018-03-07 22:26 UTC, gkalpak commented on packages/examples/core/testability/ts/whenStable/testability_example.ts
> +// #docregion Component
Nit: Unused docregion.

2018-03-07 22:26 UTC, gkalpak commented on packages/examples/core/testability/ts/whenStable/e2e_test/testability_example_spec.ts
> +      expect(element(by.css('.status')).getText()).not.toContain('done');
Wouldn't it make more sense for this to be moved inside the `then()` callback above (in order to ensure that `whenStable()` was called before the timeout was triggered)?

2018-03-09 21:16 UTC, heathkit commented on packages/examples/core/testability/ts/whenStable/testability_example.ts
> +// #docregion Component
Done

2018-03-09 21:17 UTC, heathkit commented on packages/examples/core/testability/ts/whenStable/e2e_test/testability_example_spec.ts
> +      expect(element(by.css('.status')).getText()).not.toContain('done');
Good catch, fixed.

2018-03-14 00:25 UTC, IgorMinar approved these changes
I discussed this with @heathkit and we resolved all the remaining issues. lgtm.

2018-03-14 00:26 UTC, IgorMinar commented
caretaker note: can you please run a g3 presubmit on this one before merging? thanks!

2018-03-14 02:52 UTC, kara commented
[presubmit](https://test.corp.google.com/ui#id=OCL:188969972:BASE:188970010:1520995799785:68e847fe)

2018-03-14 05:45 UTC, IgorMinar commented
great. the presubmit passed. @kara can you please merge this? thanks

2018-03-14 06:41 UTC, IgorMinar commented
@heathkit can you please check why the circleci tests are failing? they are the same unit tests that execute on travis, but they run under bazel which also need the new zone spec configuration. you should be able to reproduce this failure locally.

2018-03-14 08:13 UTC, heathkit commented
@IgorMinar Thanks, that was it. Updated BUILD.bazel and init_node_spec.ts, circle is passing now.

2018-03-14 15:40 UTC, IgorMinar commented
awesome! thanks @heathkit

2018-03-14 15:41 UTC, IgorMinar commented
@kara the previous presubmit is still valid since the fixes that Michael made do not affect g3.

2018-03-14 15:50 UTC, closed without merging