[WIP] feat(aio): add progress bar
angular/angular pull request #16886
Opened 2017-05-19 09:02 UTC by wardbell

**WIP - Do Not Merge Until**
- [ ] figure out why there is jank
- [ ] confirm progress bar color and position
- [ ] add tests

## Jank Nightmares

I'm using absolute positioning which I thought meant that the `<md-progress-bar>` in `app.component.html` would not take space. But I cannot stop the content area from bobbing during/after progress. Interestingly the side-nav and TOC panel don't jump. Only the main content area.

We should only see the bar if there is going to be an appreciable delay.
This implementation won't reveal the progress bar _at all_ if the time from location change to doc render is brief (see use of `setTimeout` and `isFetchingId` in  `app.component.ts).

It can be hard to see what's going on when running on a desktop browser. One approach I took is to add a 2sec delay to doc.json fetching in the `document.service`.

<hr>

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

2017-05-19 09:10 UTC, mary-poppins commented
The angular.io preview for faf70cb689e6a224856ab0baa437a547b7e3510e is available [here][1].

[1]: https://pr16886-faf70cb689e6a224856ab0baa437a547b7e3510e.ngbuilds.io/

2017-05-19 09:14 UTC, mary-poppins commented
The angular.io preview for 16f7a118f3d50e6e601a57ddd4b2fd7561ff61f9 is available [here][1].

[1]: https://pr16886-16f7a118f3d50e6e601a57ddd4b2fd7561ff61f9.ngbuilds.io/

2017-05-19 09:15 UTC, gkalpak commented
The jank is because `MdProgressBar` styles its host with `position: relative`, thus overwriting your `position: absolute` :smiley:

2017-05-19 10:27 UTC, gkalpak reviewed
Generally looks good. Thinks I would consider:

- Move the progress bar to the top of the page (or maybe at the bottom of the topbar - not right below it - to avoid hiding the topbar's shadow.

- Make it thinner.

- Make it less blue :smiley:

2017-05-19 10:27 UTC, gkalpak commented on aio/src/app/app.component.html
> +
???

2017-05-19 10:27 UTC, gkalpak commented on aio/src/app/app.component.ts
> +      this.isFetchingId = setTimeout(() =>  this.isFetching = true, 200);
Double space between in `=>  this.isFetching` 😱

2017-05-19 10:27 UTC, gkalpak commented on aio/src/app/app.component.ts
> +      this.isStarting = false;
Nit: Does this need to be inside the timeout?

2017-05-19 10:27 UTC, gkalpak commented on aio/src/app/app.component.ts
> +      this.isFetchingId = setTimeout(() =>  this.isFetching = true, 200);
This should only be called if `this.currentPath !== path`. In different case, there will be no `onDocRendered` call to clear the probress bar and it stays there. (E.g. click on the link for a page, while you are already on that page.)

2017-05-19 13:29 UTC, petebacondarwin commented on aio/src/app/app.component.ts
> +      this.isStarting = false;
I think it does make sense, if we are assuming that we need to wait for the document to be displayed correctly, then we might as well wait before clearing the isFetching and isStarting flags too.

2017-05-20 21:18 UTC, mary-poppins commented
The angular.io preview for 2d588404d7826bee1ae7c578f744e2ae87b9088f is available [here][1].

[1]: https://pr16886-2d588404d7826bee1ae7c578f744e2ae87b9088f.ngbuilds.io/

2017-05-20 23:25 UTC, mary-poppins commented
The angular.io preview for 093831fd60a7034577dffe2f91249f80884147c6 is available [here][1].

[1]: https://pr16886-093831fd60a7034577dffe2f91249f80884147c6.ngbuilds.io/

2017-05-20 23:36 UTC, mary-poppins commented
The angular.io preview for e900956670c61c4a1518900d9ae36290835c0563 is available [here][1].

[1]: https://pr16886-e900956670c61c4a1518900d9ae36290835c0563.ngbuilds.io/

2017-05-20 23:51 UTC, gkalpak commented
Fixed up, rebased and added tests.
Also, created [fancy preview with live-tweakable progress-bar][1] (because @IgorMinar can't decide if he doesn't see it live 😛).

Action item:
- [ ] Decide whether it is desirable to show a progress bar during the initial navigation.

[1]: https://pr16886-093831fd60a7034577dffe2f91249f80884147c6.ngbuilds.io/

2017-05-21 06:34 UTC, petebacondarwin commented on aio/src/app/app.component.ts
> +        this.isFetchingTimeout = setTimeout(() => this.isFetching = true, 200);
I thought we agreed to ditch the timeout?

2017-05-21 06:38 UTC, petebacondarwin requested changes
I think we should remove the delay at the start and don't include the `isFetching` and `isStarting` in the scroll timeout.

2017-05-21 06:38 UTC, petebacondarwin commented on aio/src/app/app.component.ts
> +      this.isStarting = false;
Thinking about this more, I think we should stop the progress bar as soon as we get `docRendered`, not in this scroll timeout. The way it is now means that even for cached fast loading documents you will get the progress bar for 300ms (or 500ms if we ditch the delay).
In practice the document is ready and viewable as soon as this event is triggered, it is just that if you want to auto scroll to the bottom of the page the layout might not be quite right for a few milliseconds.

2017-05-22 11:18 UTC, gkalpak commented on aio/src/app/app.component.ts
> +      this.isStarting = false;
> The way it is now means that even for cached fast loading documents you will get the progress bar for 300ms (or 500ms if we ditch the delay).

For cached documents, it will (usually) not show if we keep the delay, beause the navigation will happen instantly. I think that is the point of the initial delay: Super-fast loaded documents (either cached or served from the ServiceWorker in the future maybe or on super-fast networks) won't show a progress-bar.

The hide delay ensures that there is no FOPB (Flash Of Progress Bar - 😛) in case the document takes just above 200ms to load. I think this is a good thing.
<sub>(Obviously, there are other more accurate (but involved) ways of ensuring that the progress-bar will remain visible for a minimum amount of time (once shown), but I am fine with this "naive" implementation too :grin:</sub>

2017-05-22 11:20 UTC, gkalpak commented on aio/src/app/app.component.ts
> +        this.isFetchingTimeout = setTimeout(() => this.isFetching = true, 200);
I thought we didn't reach a conclusion. (But I think it is [we might want to keep it][1].) 

[1]: https://github.com/angular/angular/pull/16886#discussion_r117720558

2017-05-22 11:42 UTC, petebacondarwin commented
I guess this is a small issue. For want of a  easy life in happy to go with this for now.

2017-05-22 12:47 UTC, petebacondarwin commented on aio/src/app/app.component.ts
> +      this.isStarting = false;
My point was that putting the `this.isFetching` inside the auto-scroll timeout means that it will always be shown for that length of time even if the fetch is super quick.

2017-05-22 17:19 UTC, gkalpak commented on aio/src/app/app.component.ts
> +      this.isStarting = false;
It will only be shown if `onDocRendered()` is called after 200ms (so **not** for super quick renders).

2017-05-22 18:50 UTC, mary-poppins commented
The angular.io preview for 0d5ec81784e50225f86668ba6fffe76e09f46d2d is available [here][1].

[1]: https://pr16886-0d5ec81784e50225f86668ba6fffe76e09f46d2d.ngbuilds.io/

2017-05-22 19:05 UTC, mary-poppins commented
The angular.io preview for 9779411c25bbd11a20b6ead7430ff39131c8974e is available [here][1].

[1]: https://pr16886-9779411c25bbd11a20b6ead7430ff39131c8974e.ngbuilds.io/

2017-05-22 20:14 UTC, petebacondarwin commented on aio/src/app/app.component.ts
> +      this.isStarting = false;
you're right!

2017-05-22 20:14 UTC, petebacondarwin approved these changes

2017-05-22 20:14 UTC, petebacondarwin commented
Please squash and mark for merge @gkalpak

2017-05-23 00:15 UTC, chuckjaz commented
The aio test failure looks real. @gkalpak, can you investigate and mark it as merge again once this is resolved?

2017-05-23 00:16 UTC, chuckjaz commented
Also, @gkalpak, can you update the PR to remove the "WIP - Do Not Merge Until" if all the tasks have been completed?

2017-05-23 05:55 UTC, mary-poppins commented
The angular.io preview for 43263c8ddf13c7326f123663517b26427775c9ab is available [here][1].

[1]: https://pr16886-43263c8ddf13c7326f123663517b26427775c9ab.ngbuilds.io/

2017-05-23 06:52 UTC, gkalpak commented
The failure was probably due to the preview server being down (someone restarted it and it is now green.
Updated the initia commit. Both @wardbell and I have signed CLAs.
This should be good to go :smiley:

2017-05-23 06:59 UTC, IgorMinar commented
@gkalpak I restarted it. it looks good now

2017-05-23 07:00 UTC, merged