[WIP] docs(aio): move Set Document Title to API
angular/angular pull request #16974
Opened 2017-05-23 20:43 UTC by kapunahelewong

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: Move Set Doc Title to API Reference
```

**What is the current behavior?** (You can also link to an open issue here)

Currently Set Doc Title is in the docs.

**What is the new behavior?**

Now it is in the API Reference.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

I need help on this. I'm not familiar with editing the API docs and the format is different, not markdown.

2017-05-23 20:53 UTC, mary-poppins commented
The angular.io preview for 745ee376345a48416fd7a0d1e815bb4f84572525 is available [here][1].

[1]: https://pr16974-745ee376345a48416fd7a0d1e815bb4f84572525.ngbuilds.io/

2017-05-24 14:52 UTC, mary-poppins commented
The angular.io preview for a0ae63cb790cad97c8d909206672fd8fb983aa2e is available [here][1].

[1]: https://pr16974-a0ae63cb790cad97c8d909206672fd8fb983aa2e.ngbuilds.io/

2017-05-24 18:07 UTC, mary-poppins commented
The angular.io preview for 9b21cea66af56bd513a6dfae3d5b281f1aeddb37 is available [here][1].

[1]: https://pr16974-9b21cea66af56bd513a6dfae3d5b281f1aeddb37.ngbuilds.io/

2017-05-24 19:05 UTC, mary-poppins commented
The angular.io preview for f48a2a2be602550ac8fa83ac829da2fdc64b9386 is available [here][1].

[1]: https://pr16974-f48a2a2be602550ac8fa83ac829da2fdc64b9386.ngbuilds.io/

2017-05-24 19:14 UTC, mary-poppins commented
The angular.io preview for 3ad3dff7a2e4a4c2de35632486d6009a0d52d0af is available [here][1].

[1]: https://pr16974-3ad3dff7a2e4a4c2de35632486d6009a0d52d0af.ngbuilds.io/

2017-05-25 15:11 UTC, Foxandxss commented
Apart from deleting that .DS_Store file that got there, you need to remove the entry from the sidebar and add a redirect rule to the firebase.json file.

2017-05-25 16:07 UTC, mary-poppins commented
The angular.io preview for 7921265ea3af54a555a47a743a31caed13fe0f94 is available [here][1].

[1]: https://pr16974-7921265ea3af54a555a47a743a31caed13fe0f94.ngbuilds.io/

2017-05-25 16:54 UTC, mary-poppins commented
The angular.io preview for fa04b6e25880ef02c78a28c50209a7af1c13ff80 is available [here][1].

[1]: https://pr16974-fa04b6e25880ef02c78a28c50209a7af1c13ff80.ngbuilds.io/

2017-05-25 18:02 UTC, mary-poppins commented
The angular.io preview for cc5b6e2b50a9b7dad366c48ea8edbe4d4416a35e is available [here][1].

[1]: https://pr16974-cc5b6e2b50a9b7dad366c48ea8edbe4d4416a35e.ngbuilds.io/

2017-05-25 18:26 UTC, mary-poppins commented
The angular.io preview for 9543462b8dbd4fd8055334dcb661b56673bc825f is available [here][1].

[1]: https://pr16974-9543462b8dbd4fd8055334dcb661b56673bc825f.ngbuilds.io/

2017-05-25 19:19 UTC, kapunahelewong commented
Currently fixing errors.

2017-05-25 21:50 UTC, mary-poppins commented
The angular.io preview for df8b97fe3bda27afbbd8a6b14d207c43d7a74cfb is available [here][1].

[1]: https://pr16974-df8b97fe3bda27afbbd8a6b14d207c43d7a74cfb.ngbuilds.io/

2017-05-25 21:56 UTC, mary-poppins commented
The angular.io preview for a0e0209dd76290337487cbb8ca4f1e082e644e2b is available [here][1].

[1]: https://pr16974-a0e0209dd76290337487cbb8ca4f1e082e644e2b.ngbuilds.io/

2017-05-25 22:14 UTC, mary-poppins commented
The angular.io preview for 47d050fa8355ac713eaa7c0263f732c90ee93d16 is available [here][1].

[1]: https://pr16974-47d050fa8355ac713eaa7c0263f732c90ee93d16.ngbuilds.io/

2017-05-25 22:33 UTC, mary-poppins commented
The angular.io preview for 150491e5f827f8b8d1bb607f7160cf66ed36460b is available [here][1].

[1]: https://pr16974-150491e5f827f8b8d1bb607f7160cf66ed36460b.ngbuilds.io/

2017-05-25 23:22 UTC, mary-poppins commented
The angular.io preview for 9ac54790a28eded68f192f8f7290147db6681886 is available [here][1].

[1]: https://pr16974-9ac54790a28eded68f192f8f7290147db6681886.ngbuilds.io/

2017-05-25 23:40 UTC, mary-poppins commented
The angular.io preview for c80bc3ef2ab20372a50bef489fbf6c44bd5db947 is available [here][1].

[1]: https://pr16974-c80bc3ef2ab20372a50bef489fbf6c44bd5db947.ngbuilds.io/

2017-05-26 00:10 UTC, Foxandxss commented
All fix, ready to be reviewed.

2017-05-26 11:12 UTC, gkalpak requested changes

2017-05-26 11:12 UTC, gkalpak commented on packages/examples/platform-browser/browser/title.ts
> +import {Title} from '@angular/platform-browser';
Why remove the spaces inside `{ ... }`?

2017-05-26 11:12 UTC, gkalpak commented on packages/examples/platform-browser/browser/module.ts
> +    Title
Why add `Title` to `providers`?

2017-05-26 11:12 UTC, gkalpak commented on packages/examples/platform-browser/browser/e2e_test/title_spec.ts
> +
Inconsistent newlines: Either use @bennadel -style newlines or don't 😛

2017-05-26 11:12 UTC, gkalpak commented on packages/examples/platform-browser/browser/e2e_test/title_spec.ts
> +function waitForElement(selector: string) {
This doesn't seem to be used. Is it necessary?

2017-05-26 11:12 UTC, gkalpak commented on aio/content/navigation.json
> -
Don't remove both newlines (befoe and after) :smiley:

2017-05-26 11:35 UTC, Foxandxss commented on packages/examples/platform-browser/browser/title.ts
> +import {Title} from '@angular/platform-browser';
This is clang-format doing. It doesn't like them :(

2017-05-26 11:35 UTC, Foxandxss commented on packages/examples/platform-browser/browser/module.ts
> +    Title
Good question. Did this change in later versions or was it wrong since always?

2017-05-26 12:09 UTC, Foxandxss commented on aio/content/navigation.json
> -
I "think" I addressed this too.

2017-05-26 12:39 UTC, mary-poppins commented
The angular.io preview for cd5dbc46d5bca39cd8d9e4086fc766eba97b0a98 is available [here][1].

[1]: https://pr16974-cd5dbc46d5bca39cd8d9e4086fc766eba97b0a98.ngbuilds.io/

2017-05-26 13:07 UTC, gkalpak commented on packages/examples/platform-browser/browser/title.ts
> +import {Title} from '@angular/platform-browser';
Why not in [other files][1] then?

[1]: https://github.com/IdeaBlade/angular/blob/cd5dbc46d5bca39cd8d9e4086fc766eba97b0a98/packages/examples/platform-browser/browser/module.ts

2017-05-26 13:08 UTC, gkalpak commented on packages/examples/platform-browser/browser/module.ts
> +    Title
No idea 😕

2017-05-26 13:10 UTC, gkalpak commented on aio/firebase.json
> +      {"type": 301, "source": "/docs/ts/latest/cookbook/set-document-title.html", "destination": "/api/platform-browser/Title"},
We ussually put a comment above (e.g. `// cookbook/set-document-title.html`).

2017-05-26 13:12 UTC, gkalpak commented on packages/examples/platform-browser/browser/e2e_test/title_spec.ts
> +import {ExpectedConditions, browser, by, element, ElementFinder} from 'protractor';
`ExpectedConditions` is not used.

2017-05-26 13:21 UTC, mary-poppins commented
The angular.io preview for a5d40a5f19f5398424fdaed290ed3e4ef50c08c7 is available [here][1].

[1]: https://pr16974-a5d40a5f19f5398424fdaed290ed3e4ef50c08c7.ngbuilds.io/

2017-05-26 13:23 UTC, mary-poppins commented
The angular.io preview for e022c376159e01b51e13b294c8f4a346ad52a7a8 is available [here][1].

[1]: https://pr16974-e022c376159e01b51e13b294c8f4a346ad52a7a8.ngbuilds.io/

2017-06-22 02:27 UTC, wardbell commented on packages/examples/platform-browser/browser/title.ts
> +import {Title} from '@angular/platform-browser';
We don't use clang-format in guide docs. But (we think) that they do in Angular code where this change resides. Therefore, we conform to clang-format rules in API docs, and our rules in guide pages.

2017-06-22 02:29 UTC, wardbell commented
Added "aio" label because it touches the Angular code file while updating an API doc. Need @IgorMinar to steer this PR until we nail down process for updating API docs.

2018-08-03 16:08 UTC, closed without merging