feat(http): new HttpClient API
angular/angular pull request #17143
Opened 2017-05-31 18:39 UTC by alxhub

HttpClient is an evolution of the existing Angular HTTP API, which exists
alongside of it in a separate package, @angular/http/client. This structure
ensures that existing codebases can slowly migrate to the new API.

The new API improves significantly on the ergonomics and features of the legacy
API. A partial list of new features includes:

* Typed, synchronous response body access, including support for JSON body types
* JSON is an assumed default and no longer needs to be explicitly parsed
* Interceptors allow middleware logic to be inserted into the pipeline
* Immutable request/response objects
* Progress events for both request upload and response download
* Post-request verification & flush based testing framework

2017-05-31 21:42 UTC, mary-poppins commented
The angular.io preview for 8ac3fae7610574468704c54bc4f02c6c52da09a5 is available [here][1].

[1]: https://pr17143-8ac3fae7610574468704c54bc4f02c6c52da09a5.ngbuilds.io/

2017-06-01 10:19 UTC, diicar commented on packages/http/client/src/request.ts
> +    if (typeof this.body === 'object' || typeof this.body === 'number' || Array.isArray(this.body)) {
typeof this.body === 'boolean' maybe needed here

2017-06-01 12:48 UTC, sod commented on packages/http/client/test/client_spec.ts
> +        backend.expectOne('/test').flush({'data': 'hello world'});
thats an awesome improvement over the [current ConnectionBackend hoopla](https://angular.io/docs/ts/latest/api/http/testing/index/MockBackend-class.html) 👍

2017-06-01 16:25 UTC, alxhub commented on packages/http/client/src/request.ts
> +    if (typeof this.body === 'object' || typeof this.body === 'number' || Array.isArray(this.body)) {
Good catch, I'll add it.

2017-06-06 19:04 UTC, mhevery requested changes

2017-06-06 19:04 UTC, mhevery commented on packages/http/client/public_api.ts
> +export * from './src/client_types';
please export things individually so that we don't accidentally expose API.

2017-06-06 19:04 UTC, mhevery commented on packages/http/client/src/jsonp.ts
> +export interface JsonpAdapterCallbackMap {
Convert this to `abstract class`

2017-06-06 19:04 UTC, mhevery commented on packages/http/client/src/jsonp.ts
> +export const JSONP_ADAPTER_CALLBACK_MAP = new InjectionToken<JsonpAdapterCallbackMap>('JSONP_ADAPTER_CALLBACK_MAP');
remove this.

2017-06-06 19:04 UTC, mhevery commented on packages/http/client/src/jsonp.ts
> +  constructor(@Inject(JSONP_ADAPTER_CALLBACK_MAP) private callbackMap: JsonpAdapterCallbackMap, @Inject(DOCUMENT) private document: any) {}
no need for `@Inject`

2017-06-06 19:04 UTC, mhevery commented on packages/http/client/src/jsonp.ts
> +        delete this.callbackMap[callback];
When you use `delete` the object becomes slow forever. Consider `this.callbackMap[...] = undefined`

2017-06-06 19:06 UTC, mhevery submitted a review, later dismissed

2017-06-06 19:06 UTC, mhevery commented on packages/http/client/src/client.ts
> +  request<R>(req: HttpRequest<any>): Observable<HttpEvent<R>>;
document these

2017-06-06 21:36 UTC, alxhub commented on packages/http/client/public_api.ts
> +export * from './src/client_types';
Done.

2017-06-06 22:07 UTC, alxhub commented on packages/http/client/src/jsonp.ts
> +export interface JsonpAdapterCallbackMap {
Done

2017-06-06 22:07 UTC, alxhub commented on packages/http/client/src/jsonp.ts
> +export const JSONP_ADAPTER_CALLBACK_MAP = new InjectionToken<JsonpAdapterCallbackMap>('JSONP_ADAPTER_CALLBACK_MAP');
Done

2017-06-06 22:20 UTC, alxhub commented on packages/http/client/src/jsonp.ts
> +        delete this.callbackMap[callback];
I think in this case, because it's `window` deleting is reasonable (and keeps from polluting it forever / leaking memory).

2017-06-06 22:30 UTC, mary-poppins commented
The angular.io preview for c83299dabb2695bc2817c40b38cdcfcef18f7a6e is available [here][1].

[1]: https://pr17143-c83299dabb2695bc2817c40b38cdcfcef18f7a6e.ngbuilds.io/

2017-06-07 08:41 UTC, cexbrayat commented on packages/http/client/src/request.ts
> +    case 'DELETE':
In case this is not on purpose: `DELETE` is listed here as not having a body, but is in the `HttpBodyMethod` type above.

2017-06-07 17:56 UTC, mary-poppins commented
The angular.io preview for b18bb9fe693bcc28a5d17b4587a59aced5a596a6 is available [here][1].

[1]: https://pr17143-b18bb9fe693bcc28a5d17b4587a59aced5a596a6.ngbuilds.io/

2017-06-07 18:10 UTC, mary-poppins commented
The angular.io preview for 4b770e260967b8802f058cb5f29446b8a82571ea is available [here][1].

[1]: https://pr17143-4b770e260967b8802f058cb5f29446b8a82571ea.ngbuilds.io/

2017-06-14 17:52 UTC, mary-poppins commented
The angular.io preview for 10db6e58ae76cf58fb1d9dac4610dfb491bccdf2 is available [here][1].

[1]: https://pr17143-10db6e58ae76cf58fb1d9dac4610dfb491bccdf2.ngbuilds.io/

2017-06-15 18:38 UTC, mary-poppins commented
The angular.io preview for 5a2fe052c78d413313f2626aa085e4d8723e8e56 is available [here][1].

[1]: https://pr17143-5a2fe052c78d413313f2626aa085e4d8723e8e56.ngbuilds.io/

2017-06-15 18:39 UTC, mary-poppins commented
The angular.io preview for 27793b024fef212213dc9401f3d471e20164c2fd is available [here][1].

[1]: https://pr17143-27793b024fef212213dc9401f3d471e20164c2fd.ngbuilds.io/

2017-06-15 19:46 UTC, mary-poppins commented
The angular.io preview for 0495b72f6c281fd3c45de246c1a2f23162f659ae is available [here][1].

[1]: https://pr17143-0495b72f6c281fd3c45de246c1a2f23162f659ae.ngbuilds.io/

2017-06-16 01:39 UTC, laco0416 commented
New APIs aren't exposed in API References

2017-06-16 20:00 UTC, alxhub commented on packages/http/client/src/request.ts
> +    case 'DELETE':
Fixed!

2017-06-16 20:00 UTC, alxhub commented on packages/http/client/src/client.ts
> +  request<R>(req: HttpRequest<any>): Observable<HttpEvent<R>>;
Done

2017-06-17 18:49 UTC, chenkie commented
Looking forward to this :) Any rough estimates as to when it will land?

2017-06-20 18:43 UTC, cexbrayat commented on packages/http/client/src/module.ts
> +    {provide: HTTP_INTERCEPTORS, useValue: JsonpInterceptor, multi: true},
@alxhub Sorry if this is a misunderstanding, but shouldn't that be `useClass` instead of `useValue`?

2017-06-20 19:01 UTC, cexbrayat commented on packages/http/client/src/request.ts
> +    this.headers.seal();
Same here, I'm probably missing something, but does that mean an interceptor can't update the headers as they are sealed right away on the request?

2017-06-26 16:31 UTC, alxhub commented on packages/http/client/src/request.ts
> +    this.headers.seal();
@cexbrayat most of the `Request` object is immutable (save for the body which we sadly have no control over). To change headers, you should `.clone()` the request and either pass a new set of headers or a map of headers to append.

2017-06-26 17:24 UTC, cexbrayat commented on packages/http/client/src/request.ts
> +    this.headers.seal();
Thank you for your answer. That's what I supposed and did, but I was hoping for a less verbose way than the cloning way.

2017-06-26 17:27 UTC, cexbrayat commented
@alxhub I tried to build my own version and play with the API, but the testing part is not exposed (or I missed something). I just wanted to warn you if that was not on purpose.

2017-06-26 19:21 UTC, mary-poppins commented
The angular.io preview for 94e5130bb949209b657cdbf4101bdf1f7b8a9c1d is available [here][1].

[1]: https://pr17143-94e5130bb949209b657cdbf4101bdf1f7b8a9c1d.ngbuilds.io/

2017-06-26 20:23 UTC, mary-poppins commented
The angular.io preview for ebdf05dd6aae3bf8b75788e6956c8f72b7d44da4 is available [here][1].

[1]: https://pr17143-ebdf05dd6aae3bf8b75788e6956c8f72b7d44da4.ngbuilds.io/

2017-06-27 17:13 UTC, mary-poppins commented
The angular.io preview for fbb347e229c7675e8b08187c6097e9aa044f92ea is available [here][1].

[1]: https://pr17143-fbb347e229c7675e8b08187c6097e9aa044f92ea.ngbuilds.io/

2017-06-27 22:34 UTC, mary-poppins commented
You can preview 11974b697ada2f082005638217f6909be6dc2986 at https://pr17143-11974b697ada2f082005638217f6909be6dc2986.ngbuilds.io/.

2017-06-29 23:25 UTC, IgorMinar commented on tools/public_api_guard/http/client.d.ts
> +export declare class BrowserXhr implements XhrFactory {
this is an implementation detail. we don't need to export it.

2017-06-29 23:33 UTC, IgorMinar commented on tools/public_api_guard/http/client.d.ts
> +    request(url: string, method: HttpMethod | string, options: zHttpRequestOptionsObserveTextEvents<any>): Observable<HttpEvent<string>>;
have you considered swapping url and method? in all the apis above you first specify method and then url. this is how $http works as well (although there the method is provided via an object).

2017-06-30 08:25 UTC, petebacondarwin commented
@alxhub for this to be included in the API docs on angular.io you will need to add the entry points to https://github.com/angular/angular/blob/40921bb92722a708d292a19f8703403851164f2c/aio/tools/transforms/angular-api-package/index.js#L35-L60

2017-06-30 08:28 UTC, petebacondarwin commented on packages/http/client/src/jsonp.ts
> + * An {@Link HttpInterceptor} which identifies requests with the method JSONP and
type: `@Link` -> `@link`

2017-06-30 08:30 UTC, petebacondarwin commented on packages/http/client/src/response.ts
> + * Any error returned on the {@link Observable} response stream will be
Observable is not part of the API docs and so you cannot link to it.

2017-06-30 08:50 UTC, petebacondarwin commented on packages/http/client/src/url_params.ts
> + * This class accepts an optional second parameter of ${@link ɵHttpQueryEncoder},
API elements starting with `ɵ` are private and do not appear in the API docs, so you cannot link to them,

2017-06-30 08:54 UTC, petebacondarwin commented on packages/http/client/src/jsonp.ts
> + * An {@Link HttpInterceptor} which identifies requests with the method JSONP and
It turns out that our automatic link generator will convert this to a link for you if you wrap it in an inline code block:

```
An `HttpInterceptor` which ...
```

So there is no need to use so many `{@link ... }` tags.

2017-06-30 18:53 UTC, IgorMinar commented on packages/http/client/src/url_params.ts
> + * This class accepts an optional second parameter of ${@link ɵHttpQueryEncoder},
+1

2017-06-30 19:02 UTC, IgorMinar requested changes

2017-06-30 19:02 UTC, IgorMinar commented on packages/http/client/src/headers.ts
>   */
why did you make this file executable? please remove

2017-06-30 19:02 UTC, IgorMinar commented on packages/http/client/src/url_params.ts
>    }
remove executable bit from this file

2017-06-30 19:17 UTC, IgorMinar commented on packages/http/client/src/backend.ts
> + * @experimental
can you add brief documentation explaining what this class does?

2017-06-30 19:17 UTC, IgorMinar commented on packages/http/client/src/backend.ts
> + * @experimental
can you add brief documentation explaining what this class does?

2017-06-30 19:20 UTC, IgorMinar commented on packages/http/client/src/client.ts
> +      first: string|HttpRequest<any>, method?: HttpMethod|string,
first? how about `destination` or `request`?

2017-06-30 19:28 UTC, IgorMinar commented on packages/http/client/src/headers.ts
>    // TODO(vicb): any -> string|string[]
remove todo? it doesn't make sense any more

2017-06-30 19:32 UTC, IgorMinar commented on packages/http/client/src/jsonp.ts
> +export const JSONP_HOME = '__ng__jsonp__';
where is this used? I don't see the callsite, just one import in module.ts

2017-06-30 21:05 UTC, IgorMinar commented on packages/http/client/src/jsonp.ts
> +export const JSONP_HOME = '__ng__jsonp__';
you are actually using a string literal without underscore prefix a few lines below.

2017-06-30 21:10 UTC, IgorMinar commented on packages/http/client/src/response.ts
> +export interface HttpUserEvent<T> { type: HttpEventType.User; }
What's the `T` for? Don't you want to add a field call `data: T` or something like that?

2017-06-30 21:10 UTC, mary-poppins commented
You can preview 4ac67f5 at https://pr17143-4ac67f5.ngbuilds.io/.

2017-06-30 21:14 UTC, IgorMinar commented on packages/http/client/src/response.ts
> +    this.headers.seal();
why do we care? and if we do care to make this immutable why don't we remove seal and make the constructor take object that would internally be used to retrieve the headers?

2017-06-30 21:17 UTC, IgorMinar commented on packages/http/client/src/headers.ts
> +  static fromResponseHeaderString(headersString: string): HttpHeaders {
does this need to be a public api? if so, why not overload a constructor instead?

2017-06-30 23:02 UTC, IgorMinar commented on packages/http/client/src/headers.ts
> +  entries() { throw new Error('"entries" method is not implemented on ɵHttpHeaders class'); }
we shouldn't refer to internal classes in the error messages. What are you trying to say? How would one get this error? do we expect anyone to to implement their headers class?

2017-07-01 16:24 UTC, cexbrayat commented
After playing a bit with the new testing API, here are a few things I'd love to see:

- an `HttpClientTestingModule` that we can import in our test, instead of having to provide `HttpClient` with the correct backend in every test (see #13044 that I wanted to introduce for the current HttpModule).
- more matching methods, like we had in AngularJS 1.x (`expectPOST`, `expectDELETE`...). The current `expectOne` forces to define a custom matching function if we want to check the body or the headers for example.

Sorry if this is already in your plans, I had to say it 😄

2017-07-06 00:42 UTC, IgorMinar commented on packages/common/http/src/module.ts
> +  let _global: {[key: string]: any};
what is this variable for? it doesn't seem to be used.

2017-07-06 00:42 UTC, IgorMinar commented on tools/public_api_guard/common/http.d.ts
> +export declare abstract class JsonpCallbackMap {
this is really a "Context" rather than a "Map". Rename?

Also, are we sure we want to expose this as a public api?

2017-07-06 00:42 UTC, IgorMinar commented on tools/public_api_guard/common/http/testing.d.ts
> +    cancelled: boolean;
turn into a getter?

2017-07-06 00:42 UTC, IgorMinar commented on tools/public_api_guard/common/http/testing.d.ts
> +export declare type TestResponseBody = ArrayBuffer | Blob | string | number | Object | (string | number | Object | null)[];
would inlining this make things better in the docs?

2017-07-06 00:42 UTC, IgorMinar commented on tools/public_api_guard/common/http/testing.d.ts
> +export interface VerifyOptions {
inline

2017-07-06 00:42 UTC, IgorMinar commented on packages/platform-browser/src/dom/dom_tokens.ts
> + * @deprecated, import from `@angular/common` instead.
remove comma after deprecated

2017-07-06 00:42 UTC, IgorMinar commented on packages/common/http/test/url_encoded_body_spec.ts
> +  fdescribe('HttpUrlEncodedBody', () => {
remove `f`

2017-07-06 04:41 UTC, alxhub commented on tools/public_api_guard/common/http/testing.d.ts
> +export interface VerifyOptions {
Sure. I've yet to see a pattern for documenting the fields of inline types though in a way that shows up in our doc viewer. Is there a way to do that?

2017-07-06 04:45 UTC, alxhub commented on tools/public_api_guard/common/http/testing.d.ts
> +export declare type TestResponseBody = ArrayBuffer | Blob | string | number | Object | (string | number | Object | null)[];
Done

2017-07-06 04:48 UTC, alxhub commented on tools/public_api_guard/common/http/testing.d.ts
> +    cancelled: boolean;
Done

2017-07-06 04:48 UTC, alxhub commented on tools/public_api_guard/common/http/testing.d.ts
> +export declare type RequestMatchFn = (req: HttpRequest<any>) => boolean;
Done

2017-07-06 04:48 UTC, alxhub commented on packages/common/http/src/headers.ts
> +  id: number = seq++;
This was for some debugging, removed now.

2017-07-06 04:50 UTC, alxhub commented on tools/public_api_guard/common/http.d.ts
> +export declare type HttpNoBodyMethod = 'DELETE' | 'GET' | 'HEAD' | 'JSONP' | 'OPTIONS';
It's used in two places (`HttpMethod` and `HttpRequest.constructor()`). Inlined it anyway.

2017-07-06 04:53 UTC, alxhub commented on tools/public_api_guard/common/http.d.ts
> +export declare abstract class JsonpCallbackMap {
Done.

2017-07-06 04:53 UTC, alxhub commented on packages/common/http/src/module.ts
> +  let _global: {[key: string]: any};
Removed.

2017-07-06 04:53 UTC, alxhub commented on packages/common/http/test/url_encoded_body_spec.ts
> +  fdescribe('HttpUrlEncodedBody', () => {
Done.

2017-07-06 04:54 UTC, alxhub commented on packages/platform-browser/src/dom/dom_tokens.ts
> + * @deprecated, import from `@angular/common` instead.
Done.

2017-07-06 10:13 UTC, cexbrayat commented on packages/common/http/testing/src/module.ts
> +export class HttpClientTestingModule {
👌 but it would be great to have `HttpClient` and its dependencies in the providers too, no?

2017-07-06 15:22 UTC, alxhub commented on packages/common/http/testing/src/module.ts
> +export class HttpClientTestingModule {
`HttpClient` should already be a dependency of your application, I don't think it's needed here.

2017-07-06 16:24 UTC, mary-poppins commented
You can preview cd06aab at https://pr17143-cd06aab.ngbuilds.io/.

2017-07-06 16:26 UTC, cexbrayat commented on packages/common/http/testing/src/module.ts
> +export class HttpClientTestingModule {
Of the application yes, but to unit test a service like this:

```typescript
@Injectable()
export class UserService {
  constructor(private http: HttpClient) {}
  // ...
}
```  
you'll have to write something like :
```typescript
beforeEach(() => TestBed.configureTestingModule({
  imports: [HttpClientModule, HttpClientTestingModule],
  providers: [UserService]
}));
```

Whereas if `HttpClientTestingModule` already gives us `HttpClient` and its deps,
you could write:
```typescript
beforeEach(() => TestBed.configureTestingModule({
  imports: [HttpClientTestingModule],
  providers: [UserService]
}));
```

That's shorter, clearer and this would be more coherent with `RouterTestingModule` which already includes the `Router` and its deps (see https://github.com/angular/angular/blob/master/packages/router/testing/src/router_testing_module.ts#L137).

2017-07-06 17:07 UTC, IgorMinar commented on packages/platform-server/src/http.ts
> +                throw new Error('invoke twice');
what does this error mean? imagine that as a developer you get an error "Error: invoke twice" what would you do? :)

2017-07-06 17:09 UTC, IgorMinar commented on packages/common/http/testing/src/module.ts
> +export class HttpClientTestingModule {
+1

2017-07-06 17:25 UTC, IgorMinar commented on packages/common/http/src/jsonp.ts
> +export const JSONP_HOME = '__ng__jsonp__';
this is still not being used by anything and the actual prefix in JsonpClientBackend#nextCallback is does not contain the underscore prefix

2017-07-06 17:25 UTC, mary-poppins commented
You can preview b7ab701 at https://pr17143-b7ab701.ngbuilds.io/.

2017-07-06 17:26 UTC, mary-poppins commented
You can preview da86d95 at https://pr17143-da86d95.ngbuilds.io/.

2017-07-06 17:34 UTC, mary-poppins commented
You can preview 1a27eb4 at https://pr17143-1a27eb4.ngbuilds.io/.

2017-07-06 17:38 UTC, IgorMinar commented on tools/public_api_guard/common/http.d.ts
> +export declare type HttpResponseType = 'arraybuffer' | 'blob' | 'json' | 'text';
inline?

2017-07-06 17:38 UTC, IgorMinar commented on tools/public_api_guard/common/http.d.ts
> +export declare type HttpSerializedBody = ArrayBuffer | Blob | FormData | string;
inline?

2017-07-06 17:40 UTC, IgorMinar commented on tools/public_api_guard/common/http.d.ts
> +export declare type HttpMethod = 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'GET' | 'HEAD' | 'JSONP' | 'OPTIONS';
could we make this type internal? the public apis that use this type also use `| string` so the type is meaningless there.

2017-07-06 18:26 UTC, alxhub commented on tools/public_api_guard/common/http.d.ts
> +export declare type HttpMethod = 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'GET' | 'HEAD' | 'JSONP' | 'OPTIONS';
Done

2017-07-06 18:28 UTC, alxhub commented on tools/public_api_guard/common/http.d.ts
> +export declare type HttpSerializedBody = ArrayBuffer | Blob | FormData | string;
Done

2017-07-06 18:28 UTC, alxhub commented on tools/public_api_guard/common/http.d.ts
> +export declare type HttpResponseType = 'arraybuffer' | 'blob' | 'json' | 'text';
Done

2017-07-06 18:37 UTC, alxhub commented on packages/common/http/src/jsonp.ts
> +export const JSONP_HOME = '__ng__jsonp__';
Done.

2017-07-06 18:37 UTC, alxhub commented on packages/common/http/testing/src/module.ts
> +export class HttpClientTestingModule {
Good point, @cexbrayat. Done.

2017-07-06 18:54 UTC, mary-poppins commented
You can preview c4ae85a at https://pr17143-c4ae85a.ngbuilds.io/.

2017-07-06 19:01 UTC, mary-poppins commented
You can preview ef6d58d at https://pr17143-ef6d58d.ngbuilds.io/.

2017-07-06 19:09 UTC, cexbrayat commented on packages/common/http/testing/src/module.ts
> +export class HttpClientTestingModule {
Awesome @alxhub !

And what do you think about having more matching methods for unit tests, like we had in AngularJS 1.x (`expectPOST`, `expectDELETE`...)? As I pointed out in an earlier comment, the current `expectOne` forces to define a custom matching function if we want to check the body or the headers for example.

2017-07-06 19:54 UTC, mary-poppins commented
You can preview 1097bf2 at https://pr17143-1097bf2.ngbuilds.io/.

2017-07-06 20:50 UTC, mary-poppins commented
You can preview cd73359 at https://pr17143-cd73359.ngbuilds.io/.

2017-07-06 20:56 UTC, IgorMinar approved these changes
expand the interceptor test and this is good to go.

🎉 🎈 🎆

2017-07-06 21:18 UTC, mary-poppins commented
You can preview 475a86c at https://pr17143-475a86c.ngbuilds.io/.

2017-07-06 22:31 UTC, mary-poppins commented
You can preview e37f23f at https://pr17143-e37f23f.ngbuilds.io/.

2017-07-07 07:45 UTC, cexbrayat commented
@alxhub @IgorMinar I've got a few remaining questions if you don't mind.

- I don't see how the query parameters are passed to the HttpClient. The old `Http` service allowed `http.get(url, { params: { status: currentStatus }})`, but I don't think it's possible with `HttpClient`? 

- You probably thought long about this, but `@angular/common/http` is really counter-intuitive :)

- If `expectOne` is going to be the only matching method available for unit tests, can we have a third parameter to check the body and another to check the headers?  The `method` field of `RequestMatch` could also be more strictly typed (`'GET'|'POST'|...`).

Currently testing a service doing a POST implies something like:

```typescript
http
 .expectOne(req => {
   expect(req.method).toBe('POST');
   expect(req.url).toBe(`/api/users/1`);
   expect(req.body).toEqual(user);
   return true;
 })
 .flush(user);
```

whereas we could have:

```typescript
http
 .expectOne('POST', '/api/users/1', user)
 .flush(user);
```

or (even better?):

```typescript
http
 .expectPOST('/api/users/1', user)
 .flush(user);
```

- The error message in a unit test when the request doesn't match what was expected is not very helpful: `Expected one matching request, found none.`. We'll need to see what was expected and what was the actual value.

If this is going to be merged soon, do you want me to open specific issues for some/all the points above?

2017-07-07 17:34 UTC, IgorMinar commented
@cexbrayat thanks for the feedback!

- *"I don't see how the query parameters are passed to the HttpClient"*
@alxhub is adding this feature
- *"@angular/common/http is really counter-intuitive"*
  I'd like us to consolidate on a fewer packages (i.e. merge all the platform packages into one, possibly move forms into common as well, etc)
- like the idea of `expectPOST`, `expectGET` helper matchers with better error messages.

2017-07-07 18:01 UTC, alxhub commented
@cexbrayat awesome feedback, thanks!

> I don't see how the query parameters are passed to the HttpClient.

As Igor mentioned, this is coming to the API.

> If expectOne is going to be the only matching method available for unit tests, can we have a third parameter to check the body and another to check the headers?

I'd rather not go down this route, actually. The new API considers request _matching_ to be separate from _assertion_. I would write your POST body expectation as follows:

```
const req = http.expectOne({method: 'POST', url: '/api/users/1');
expect(req.request.body).toBe(user);
req.flush(user);
```

This example is actually broken:
```
http
 .expectOne(req => {
   expect(req.method).toBe('POST');
   expect(req.url).toBe(`/api/users/1`);
   expect(req.body).toEqual(user);
   return true;
 })
 .flush(user);
```

The function taken by `expectOne()` is a predicate - it will be called against every request currently queued. Those `expect()`s will fail if there are other, unrelated requests that happen to not match them.

2017-07-07 19:11 UTC, jasonaden commented
Merged manually.

2017-07-07 19:11 UTC, closed without merging

2017-07-08 15:02 UTC, cexbrayat commented
@alxhub @IgorMinar Thank you for listening and taking the time to answer!

I followed with a few issues regarding params handling (potential bugs) and testing APIs (potential improvements :) ):
- #18012 
- #18013 
- #18014

2017-07-17 20:44 UTC, dominique-mueller commented
**Great work!**

I'm curious, why did you guys put the new HTTP client into `@angular/common/http` and not into `@angular/http`? Because of breaking changes (if so, why not publish with v5)?
And what will happen to the "old" implementation (which, by the way, is still mentioned in the "Angular / Tutorial / HTTP" page)? Will the `@angular/http` package be deprecated and removed at some point in the future? Or will the new implementation replace the old one?

Just interested in the overall strategy here :)