fix(aio): fix scrolling
angular/angular pull request #17266
Opened 2017-06-06 18:10 UTC by gkalpak

This commit also partially reverts #17102 (that assumed a fixed topbar which is
no longer the case after #17155).

Fixes ##17219.

2017-06-06 18:19 UTC, mary-poppins commented
The angular.io preview for 56b8edb8ac7c12400fb16fe5a58d9f65a5fab500 is available [here][1].

[1]: https://pr17266-56b8edb8ac7c12400fb16fe5a58d9f65a5fab500.ngbuilds.io/

2017-06-06 21:28 UTC, mary-poppins commented
The angular.io preview for 457c28c1431f61367686a10c4484ef867e3eed42 is available [here][1].

[1]: https://pr17266-457c28c1431f61367686a10c4484ef867e3eed42.ngbuilds.io/

2017-06-06 21:49 UTC, mary-poppins commented
The angular.io preview for d394f92027f2fcdc9d2808c356f483746734a8c0 is available [here][1].

[1]: https://pr17266-d394f92027f2fcdc9d2808c356f483746734a8c0.ngbuilds.io/

2017-06-07 09:37 UTC, petebacondarwin commented on aio/src/app/shared/scroll.service.ts
> +        if (window.pageYOffset < 20) {
this looks like an ideal place to put a comment explaining why this is being done :-)

2017-06-07 09:39 UTC, petebacondarwin commented on aio/src/styles/1-layouts/_content-layout.scss
>  .sidenav-content {
Not related to this PR but `sidenav-content` is a really bad name because it is actually the main content of the page. It just happens that the main content sits inside a sidenav container.

2017-06-07 09:41 UTC, petebacondarwin commented on aio/src/app/shared/scroll.service.ts
> +      const toolbar = this.document.querySelector('md-toolbar.app-toolbar');
In mobile mode the toolbar is not static. Where is this taken into account?

2017-06-07 09:57 UTC, petebacondarwin commented on aio/src/app/shared/scroll.service.spec.ts
> +      const element = new MockElement() as any as Element;
another way of writing this could be `const element: Element = new MockElement() as any;`. Is that any cleaner?

2017-06-07 10:06 UTC, petebacondarwin commented on aio/src/app/shared/scroll.service.ts
> +      const toolbar = this.document.querySelector('md-toolbar.app-toolbar');
Actually I see now that in mobile mode it is static. So nothing doing here.

2017-06-07 10:13 UTC, petebacondarwin requested changes
I think a comment explaining the yOffset tweak and a more descriptive commit message are in order. But otherwise, LGTM.

2017-06-07 12:27 UTC, gkalpak commented on aio/src/app/shared/scroll.service.spec.ts
> +      const element = new MockElement() as any as Element;
Either way works for me. Happy to change it.

2017-06-07 12:50 UTC, petebacondarwin commented on aio/src/app/shared/scroll.service.spec.ts
> +      const element = new MockElement() as any as Element;
As you like. It would be even nicer if we didn't need to cast every time we created a `MockElement`.

2017-06-07 12:52 UTC, gkalpak commented
Updated. @petebacondarwin PTAL.

2017-06-07 13:03 UTC, petebacondarwin approved these changes

2017-06-07 13:04 UTC, petebacondarwin commented
Needs a rebase conflict resolution thingy :-(

2017-06-07 13:09 UTC, gkalpak commented
Rebased.

2017-06-07 13:17 UTC, mary-poppins commented
The angular.io preview for 0b872ecbe72d067f71732f1e1e430315ab02fec9 is available [here][1].

[1]: https://pr17266-0b872ecbe72d067f71732f1e1e430315ab02fec9.ngbuilds.io/

2017-06-07 13:37 UTC, merged