fix(aio): make the ToC left hand-side bar shorter
angular/angular pull request #17280
Opened 2017-06-06 23:39 UTC by gkalpak

Make the ToC left hand-side bar shorter, so that it starts at the initial bullet and ends at the final bullet.

Fixes #17221.

2017-06-06 23:47 UTC, mary-poppins commented
The angular.io preview for c9889cf0582bb72b213a0309e22e4a1e2b3415e1 is available [here][1].

[1]: https://pr17280-c9889cf0582bb72b213a0309e22e4a1e2b3415e1.ngbuilds.io/

2017-06-06 23:57 UTC, mary-poppins commented
The angular.io preview for 92ed0095e99138a8733f93429dde500960872b47 is available [here][1].

[1]: https://pr17280-92ed0095e99138a8733f93429dde500960872b47.ngbuilds.io/

2017-06-07 00:06 UTC, mary-poppins commented
The angular.io preview for 468868b8fabaea24c3b0d8fc39cb0f4364781f94 is available [here][1].

[1]: https://pr17280-468868b8fabaea24c3b0d8fc39cb0f4364781f94.ngbuilds.io/

2017-06-07 00:16 UTC, mary-poppins commented
The angular.io preview for c00a6f4c14eddd78aae1501338aa70ef1f0444a6 is available [here][1].

[1]: https://pr17280-c00a6f4c14eddd78aae1501338aa70ef1f0444a6.ngbuilds.io/

2017-06-07 00:18 UTC, gkalpak commented
Initial solution plus three extra styling variations:

- [Variation 1][1]: Just a bar
- [Variation 2][2]: Bar with start/end markers (lines)
- [Variation 3][3]: Bar with start/end markers (dots)
- [Variation 4][4]: Bar with markers for all elements (dots)

[1]: https://pr17280-c9889cf0582bb72b213a0309e22e4a1e2b3415e1.ngbuilds.io/guide/cli-quickstart
[2]: https://pr17280-92ed0095e99138a8733f93429dde500960872b47.ngbuilds.io/guide/cli-quickstart
[3]: https://pr17280-468868b8fabaea24c3b0d8fc39cb0f4364781f94.ngbuilds.io/guide/cli-quickstart
[4]: https://pr17280-c00a6f4c14eddd78aae1501338aa70ef1f0444a6.ngbuilds.io/guide/cli-quickstart

2017-06-07 10:18 UTC, petebacondarwin commented on aio/src/styles/2-modules/_toc.scss
> +      &:not(.active) a:before,
Can we group all the `:not(.active)` rules under a single block? I.E.:

```scss
&:not(.active) {
  a:before { ... }
  &:first-child, &:last-child {
    a:before { ... }
  }
  &:hover {
     ...
  }
}
```

2017-06-07 10:20 UTC, petebacondarwin commented on aio/src/styles/2-modules/_toc.scss
> +        height: 4px;
I don't think we need to repeat many of these rules as they would be inherited from the rule above, right? 
You only need to tweak the top, left, width and height rules.

2017-06-07 10:21 UTC, petebacondarwin commented on aio/src/styles/2-modules/_toc.scss
> +      &:not(.active) a:before {
Isn't this selector the same as the previous one?

2017-06-07 10:21 UTC, petebacondarwin requested changes
It would be good to try to avoid the duplication of rules.

2017-06-07 12:55 UTC, gkalpak commented on aio/src/styles/2-modules/_toc.scss
> +      &:not(.active) a:before {
Possibly :smiley:

2017-06-07 12:57 UTC, gkalpak commented on aio/src/styles/2-modules/_toc.scss
> +        height: 4px;
I have put this together in a POC-y way. I will clean it up once we decide which variation we prefer.

2017-06-07 13:06 UTC, petebacondarwin commented
"Just a bar works best for my eyes"

2017-06-07 16:21 UTC, IgorMinar commented
If you combine this change with the fix for #17219 which I don't see applied to aio-staging even though it has been merged, you get variation 4 but "active". I believe this would be the most desirable.

2017-06-07 16:23 UTC, sjtrimble commented
100% just a bar!

2017-06-07 16:35 UTC, sjtrimble commented
@IgorMinar What about it? The "just a bar" option @gkalpak provided here includes the circles. Do you mean something else?

2017-06-07 16:36 UTC, gkalpak commented
@IgorMinar, this is independent of #17219. This one just styles ToC's left hand-side bar.
#17219 fixes scrolling (and detecting the active/scrolled to element).

2017-06-07 17:21 UTC, gkalpak commented
"Just a bar" it is then (I would swear the other variations looked nice when I came up with them late last night 😕).

2017-06-07 17:26 UTC, IgorMinar commented
Sorry, I think the links from @gkalpak above don't reflect the description. What I believe we all want is just a bar with the H1 active upon navigation to the document:

<img width="352" alt="screen shot 2017-06-07 at 10 24 37 am" src="https://user-images.githubusercontent.com/216296/26891944-9c431a3e-4b6b-11e7-8ccd-bba86f855f88.png">

Am I mistaken?

2017-06-07 17:27 UTC, gkalpak commented
Rebased on master and removed excess commits/variations 😢

2017-06-07 17:33 UTC, gkalpak commented
> What I believe we all want is just a bar with the H1 active upon navigation to the document

The "active upon navigation to the document" part is fixed by another PR. This PR just makes the left bar shorter.

Before this PR:
![toc-staging](https://user-images.githubusercontent.com/8604205/26892315-956ab122-4bc0-11e7-8ae9-b101c358504f.png)

After this PR:
![toc-preview](https://user-images.githubusercontent.com/8604205/26892217-3da6cbc4-4bc0-11e7-9618-c230ff2d5334.png)

2017-06-07 17:39 UTC, mary-poppins commented
The angular.io preview for 13e5ddbe38f38aaed32a354efff0648e63a81f3a is available [here][1].

[1]: https://pr17280-13e5ddbe38f38aaed32a354efff0648e63a81f3a.ngbuilds.io/

2017-06-07 17:52 UTC, petebacondarwin approved these changes

2017-06-07 17:53 UTC, petebacondarwin commented
I'll let @IgorMinar have the last say.

2017-06-07 21:01 UTC, IgorMinar approved these changes
this looks great now! thanks

2017-06-08 07:56 UTC, merged