fix(aio): remove glossary l-sub-section class
angular/angular pull request #17305
Opened 2017-06-07 17:49 UTC by sjtrimble

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Closes https://github.com/angular/angular/issues/17265

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

2017-06-07 18:02 UTC, mary-poppins commented
The angular.io preview for a7a0c5bfa9a3c80ce16ef742b0bab247ace17f6c is available [here][1].

[1]: https://pr17305-a7a0c5bfa9a3c80ce16ef742b0bab247ace17f6c.ngbuilds.io/

2017-06-07 18:02 UTC, petebacondarwin requested changes

2017-06-07 18:02 UTC, petebacondarwin commented on aio/content/guide/glossary.md
> +<div>
Since there is no class, you can get rid of the `div` altogether and remove the extra blank lines.

2017-06-07 18:15 UTC, sjtrimble commented on aio/content/guide/glossary.md
> +<div>
I wasn't sure in case we wanted to style differently. Can do!

2017-06-07 18:42 UTC, mary-poppins commented
The angular.io preview for 4cfadfa35faeed78979ae37b852f3eb1aaa23640 is available [here][1].

[1]: https://pr17305-4cfadfa35faeed78979ae37b852f3eb1aaa23640.ngbuilds.io/

2017-06-08 17:13 UTC, sjtrimble commented
@petebacondarwin Can you review this again - I think I got them all.

2017-06-08 18:58 UTC, IgorMinar approved these changes

2017-06-08 18:58 UTC, merged