fix(aio): make search results better
angular/angular pull request #17419
Opened 2017-06-12 13:55 UTC by petebacondarwin

* update to latest version of lunr search
* add trailing wildcard to search terms to increase matches
* fix unwanted error when escape was pressed

Closes #17417

2017-06-12 14:00 UTC, petebacondarwin commented on aio/src/app/app.component.html
> +  <aio-search-box class="search-container" #searchBox (onSearch)="doSearch($event)"></aio-search-box>
It turned out that because the input box inside the search box component was of type "search" then it would also trigger this handler directly, which meant that the `$event` was an event object rather than the expected string.
The easiest solution was just not to use the name `search` for the component's output event.

2017-06-12 14:01 UTC, petebacondarwin commented on aio/src/app/search/search-worker.js
> +    addFn(this);
The new version of Lunr requires the index to be immutable, so you must load up the index data when you create the index.

2017-06-12 14:02 UTC, petebacondarwin commented
TODO: I think we should also do the following (after we go to production):

1) Host our own copy of the lunr library, rather than relying upon the unpkg CDN.
2) Prebuild the index on the server, as part of the dgeni build

2017-06-12 14:11 UTC, mary-poppins commented
The angular.io preview for 0cdac5352993439b393e1909f5b83e1a5552f6e4 is available [here][1].

[1]: https://pr17419-0cdac5352993439b393e1909f5b83e1a5552f6e4.ngbuilds.io/

2017-06-12 15:13 UTC, gkalpak requested changes
You also need to update [ngsw-manifest.json][1].

[1]: https://github.com/petebacondarwin/angular/blob/0cdac5352993439b393e1909f5b83e1a5552f6e4/aio/ngsw-manifest.json#L9

2017-06-12 15:13 UTC, gkalpak commented on aio/src/app/search/search-worker.js
> +  var terms = query.split(/\s/);
Nit: `/\s+/`

2017-06-12 15:44 UTC, MartinKolarik commented on aio/src/app/search/search-worker.js
> +importScripts('https://unpkg.com/lunr@2.1.0/lunr.js');
jsDelivr with on-demand minification to the rescue 😄
https://cdn.jsdelivr.net/npm/lunr@2.1.0/lunr.min.js

2017-06-12 16:40 UTC, gkalpak commented on aio/src/app/search/search-worker.js
> +      if (terms.length === 1 || term.length > 2) qb.term(term, { wildcard: lunr.Query.wildcard.TRAILING });
By doing the `.length > 2` check here, we end up showing the "No results" message when the user starts typing, which is confusing. Could we do the check on the search-box component and not send a query if the term doesn't meet some criteria (e.g. min length)?

2017-06-12 16:42 UTC, petebacondarwin commented on aio/src/app/search/search-worker.js
> +importScripts('https://unpkg.com/lunr@2.1.0/lunr.js');
Don't know. but this is another good reason to host our own?

2017-06-12 16:44 UTC, gkalpak commented on aio/src/app/search/search-worker.js
> +      if (terms.length === 1 || term.length > 2) qb.term(term, { wildcard: lunr.Query.wildcard.TRAILING });
I also noticed that we are sending several empty-string `query`. Probably a good idea to avoid or short-circuiting those.

2017-06-12 16:46 UTC, gkalpak commented on aio/src/app/search/search-box/search-box.component.ts
> +    (keyup)="doSearch()"
I just remembered `(input)` is useful for catching changes coming from right-click+cut/paste actions.

2017-06-12 16:54 UTC, gkalpak commented
> Host our own copy of the lunr library, rather than relying upon the unpkg CDN.

Adding some context:
We have briefly considered that in the past. The problem was that the cli didn't support copying something outside the `src/` directory (i.e. from `aio/node_modules/lunr/`), so we decided to keep fetching drom unkpg.com (since the ServiceWorker will serve it after the first time anyway), until we have time to find a better solution. Definitely something to look into post-release 👍 

##
> Prebuild the index on the server, as part of the dgeni build

I thought the reason we didn't do that was that the index was pretty large for downloading, so it was preferrable to download the keywords and build the index on the client. Has that changed with lunr 2.x?

2017-06-12 16:58 UTC, petebacondarwin commented on aio/src/app/search/search-worker.js
> +      if (terms.length === 1 || term.length > 2) qb.term(term, { wildcard: lunr.Query.wildcard.TRAILING });
But the `terms === 1` should cause the search to go ahead for the first two chars. I suspect that you are just seeing the "No results" because the index has not yet finished building.

2017-06-12 16:58 UTC, petebacondarwin commented on aio/src/app/search/search-box/search-box.component.ts
> +    (keyup)="doSearch()"
Hmm, OK. So I think I need to make all this a bit more observable :-)

2017-06-12 17:09 UTC, petebacondarwin commented
Apparently the index is smaller in 2.x.

2017-06-12 18:50 UTC, mary-poppins commented
The angular.io preview for bdd895c5565bb63a8c6f1906ff8dba8e845e7336 is available [here][1].

[1]: https://pr17419-bdd895c5565bb63a8c6f1906ff8dba8e845e7336.ngbuilds.io/

2017-06-12 19:30 UTC, IgorMinar commented on aio/src/app/search/search-worker.js
> +importScripts('https://unpkg.com/lunr@2.1.0/lunr.js');
yeah. we should host our own

2017-06-12 19:34 UTC, IgorMinar requested changes
Let's figure out how to get rid of the dependency on the external cdn.

Unless I'm missing something, I don't see this change as a critical improvement. If that's the case then let's defer this upgrade until later. We should not be introducing this kind of change now. Especially since it's unclear how the non-minified download affects performance.

2017-06-12 20:31 UTC, gkalpak commented on aio/src/app/search/search-worker.js
> +      if (terms.length === 1 || term.length > 2) qb.term(term, { wildcard: lunr.Query.wildcard.TRAILING });
Ah, true about the `terms === 1` check. It's probably the index (in which case we should show a better message (but not something for this PR)).

2017-06-12 21:05 UTC, mary-poppins commented
The angular.io preview for 8202bd924ea0afae9011e21fa51aa0134a3bfc76 is available [here][1].

[1]: https://pr17419-8202bd924ea0afae9011e21fa51aa0134a3bfc76.ngbuilds.io/

2017-06-12 21:41 UTC, petebacondarwin commented
I have arranged for us to minify and host the lunr library file ourselves. See the second commit.

I looked into building the index on the server but it is coming in at around 1.5Mb, which is simply too large. So we will continue to build in a web-worker.

Later this week I can look at delaying the download of the keywords, etc till the app is up and running.

2017-06-12 21:43 UTC, petebacondarwin commented on aio/ngsw-manifest.json
> +      {"url": "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"}
I believe we don't need a line for the lunr library now that it is a local file - similar to the prettify.js library, right @gkalpak ?

2017-06-12 21:43 UTC, petebacondarwin commented on aio/src/app/search/search-box/search-box.component.ts
> +                           .distinctUntilChanged();
Now we only trigger an `onSearch` output event when the query is not blank and is different from before.

2017-06-12 22:28 UTC, mary-poppins commented
The angular.io preview for 07483ddd36c12dcb062f0c278ca253ac7191d899 is available [here][1].

[1]: https://pr17419-07483ddd36c12dcb062f0c278ca253ac7191d899.ngbuilds.io/

2017-06-12 23:00 UTC, gkalpak reviewed
A couple of minor comments.
LGTM otherwise.

2017-06-12 23:00 UTC, gkalpak commented on aio/ngsw-manifest.json
> +      {"url": "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"}
Right!

2017-06-12 23:00 UTC, gkalpak commented on aio/src/app/app.component.spec.ts
> +        it('should re-run the search when the search box regains focus and is not empty', () => {
How is the "is not empty" checked?

2017-06-12 23:00 UTC, gkalpak commented on aio/src/app/search/search-box/search-box.component.ts
> +                           .filter(value => !!(value && value.trim()));
One side effect of this is that it will not clear the search results when you empty the search field (e.g. via BACKSPACE or by clicking on the `x` button). I liked that "feature". Now, the only way to hide the results is to click somewhere outside of the results panel and there is not much space left; espacially on mobile.

2017-06-12 23:04 UTC, petebacondarwin commented on aio/src/app/search/search-box/search-box.component.ts
> +                           .filter(value => !!(value && value.trim()));
OK, so let's ditch the filter, then.

2017-06-12 23:05 UTC, petebacondarwin commented on aio/src/app/search/search-box/search-box.component.ts
> +                           .filter(value => !!(value && value.trim()));
Although hitting escape does clear the results

2017-06-12 23:39 UTC, mary-poppins commented
The angular.io preview for 624acdc3d72f605e7f629c30a4f57c81003c69fe is available [here][1].

[1]: https://pr17419-624acdc3d72f605e7f629c30a4f57c81003c69fe.ngbuilds.io/

2017-06-13 06:24 UTC, gkalpak commented on aio/src/app/search/search-box/search-box.component.ts
> +                           .filter(value => !!(value && value.trim()));
Most mobile keyboards don't have escape though :grin:

2017-06-13 06:42 UTC, petebacondarwin commented
I fixed up the removal of the results view when you empty the search box @gkalpak PTAL

2017-06-13 07:10 UTC, gkalpak approved these changes

2017-06-13 10:14 UTC, mary-poppins commented
The angular.io preview for fec11b141a55766bbf38af84c09d3c16d95c410f is available [here][1].

[1]: https://pr17419-fec11b141a55766bbf38af84c09d3c16d95c410f.ngbuilds.io/

2017-06-13 10:26 UTC, petebacondarwin commented
Travis failure is in core e2e tests and unrelated to this change

2017-06-13 10:26 UTC, merged

2017-06-14 08:49 UTC, olivernn commented
> I looked into building the index on the server but it is coming in at around 1.5Mb, which is simply too large. So we will continue to build in a web-worker.

Getting the index size down is my current performance focus. Out of interest, how small would the index need to be for pre-building the index to be a viable solution here?

Also, what is the best way for me to get my hands on your corpus, so I can do some testing locally?

2017-06-14 09:00 UTC, petebacondarwin commented
@olivernn - thanks for your continued support with this. I really appreciate your proactive approach.
The corpus is a little tricky to acquire because it is generated on the fly as part of our build process for https://github.com/angular/angular/tree/master/aio

One thing you can do is get hold of the data we are using on the client to generate the index, which is https://angular.io/generated/docs/app/search-data.json

And you can see what we do with it in our web worker: https://github.com/angular/angular/blob/master/aio/src/app/search/search-worker.js

If you want to try building the website locally you need to do something along the following lines:

```bash
git clone https://github.com/angular/angular
cd angular
npm install
./build.sh #possibly might not work (on Windows) and may not be necessary
cd aio
yarn setup
yarn start
```