docs(aio): fixed grammar and typos
angular/angular pull request #17481
Opened 2017-06-13 21:49 UTC by Sibiraj-S

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
grammar mistakes and typos

**What is the new behavior?**
fix grammar and typos

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

2017-06-13 22:18 UTC, Sibiraj-S commented
I signed it!

2017-06-21 10:56 UTC, Sibiraj-S commented
@gkalpak . Can this be merged? as it is getting outdated from the current one.

2017-06-21 17:40 UTC, gkalpak commented
cc @wardbell

2017-06-22 06:26 UTC, wardbell requested changes
LGTM except as noted and you have to resolve the merge conflicts. I would have fixed it myself but I can't update your branch.

2017-06-22 06:26 UTC, wardbell commented on aio/content/marketing/resources.json
> +            "desc": "A Universal Windows App (uwp) powered by Angular 2",
The merge conflict is here. Please replace "Angular 2" with "Angular"

2017-06-22 06:52 UTC, Sibiraj-S commented on aio/content/marketing/resources.json
> +            "desc": "A Universal Windows App (uwp) powered by Angular 2",
since I made the change. a week ago. I deleted my branch. Is there anything else can be done

2017-06-23 13:52 UTC, Sibiraj-S commented on aio/content/marketing/resources.json
> +            "desc": "A Universal Windows App (uwp) powered by Angular 2",
?

2017-06-25 16:39 UTC, Sibiraj-S commented on aio/content/marketing/resources.json
> +            "desc": "A Universal Windows App (uwp) powered by Angular 2",
what to do now @wardbell

2017-06-25 16:40 UTC, Sibiraj-S commented on aio/content/marketing/resources.json
> +            "desc": "A Universal Windows App (uwp) powered by Angular 2",
can this get cleaned up while merging?

2017-06-27 07:05 UTC, Sibiraj-S commented
@wardbell opened a new PR #17782 for the same since I deleted the branch for this PR.  Both have same changes but up to date with master

2017-06-27 14:44 UTC, gkalpak commented
Closing in favor of #17782.

2017-06-27 14:44 UTC, closed without merging