feat(router): add router-level events for GuardsCheck and Resolve
angular/angular pull request #17601
Opened 2017-06-18 18:58 UTC by jasonaden

This PR adds router-level event hooks so user-land knows when Guards and Resolves start and end for each route navigation. This makes the full lifecycle of events at the router level bigger:

```
NavigationStart
RoutesRecognized
GuardsCheckStart // new
GuardsCheckEnd // new
ResolveStart // new
ResolveEnd // new
NavigationEnd
```

With optional events:

```
RouteConfigLoadStart
RouteConfigLoadEnd
NavigationCancel
NavigationError
```

This will be especially useful for metrics. Things such as timing how long guards and resolves take on average.

These APIs are experimental and are documented as such.

2017-06-18 19:14 UTC, mary-poppins commented
The angular.io preview for 2ba0836ea2bb00e4f2c2b61bc5dd596d9c0f518a is available [here][1].

[1]: https://pr17601-2ba0836ea2bb00e4f2c2b61bc5dd596d9c0f518a.ngbuilds.io/

2017-06-18 19:26 UTC, mary-poppins commented
The angular.io preview for 8fbf1d3ff44ec9ea17069a9264b542a99f9c3207 is available [here][1].

[1]: https://pr17601-8fbf1d3ff44ec9ea17069a9264b542a99f9c3207.ngbuilds.io/

2017-06-22 17:04 UTC, vicb commented on packages/router/src/events.ts
> - * - {@link RouteConfigLoadEnd}
What about adding a timeline for the events ?

I think the docs could be improved here.

2017-06-22 17:07 UTC, vicb commented on packages/router/src/router.ts
> +            if (p.shouldActivate && preActivation.isActivating()) {
what is `&& preActivation.isActivating()` ?

2017-06-22 17:08 UTC, vicb commented on packages/router/src/router.ts
> +  isDeactivating(): boolean { return this.canDeactivateChecks.length !== 0; }
`hasDeactivateChecks` ?

2017-06-22 17:09 UTC, jasonaden commented on packages/router/src/events.ts
> - * - {@link RouteConfigLoadEnd}
Agreed on the docs. I think there's a lot to do on that, and I want to get that done ASAP. Just not as part of this PR. I've started mapping this out for myself so I could actually write a good doc on it.

2017-06-22 17:11 UTC, vicb requested changes
Changes LGTM.
Docs for event is sparse. Please take this opportunity to add more docs.

2017-06-22 17:14 UTC, jasonaden commented on packages/router/src/router.ts
> +            if (p.shouldActivate && preActivation.isActivating()) {
Basically I want to refactor the `PreActivation` class but can't do that at this time.

`PreActivation` determines if the route is going to activate by a combination of things. One is the `shouldActivate`, and the other is whether or not the `canActivateChecks` array has length.

2017-06-22 17:23 UTC, jasonaden commented on packages/router/src/router.ts
> +  isDeactivating(): boolean { return this.canDeactivateChecks.length !== 0; }
Same as above.

2017-06-23 17:01 UTC, mary-poppins commented
The angular.io preview for 2ca0086b8ba0b11de484f6ffc9139afd89d6a268 is available [here][1].

[1]: https://pr17601-2ca0086b8ba0b11de484f6ffc9139afd89d6a268.ngbuilds.io/

2017-06-23 17:23 UTC, mary-poppins commented
The angular.io preview for 3a23f0ee388719de1040dbdd108417e70ab37d71 is available [here][1].

[1]: https://pr17601-3a23f0ee388719de1040dbdd108417e70ab37d71.ngbuilds.io/

2017-06-26 18:33 UTC, vicb approved these changes

2017-06-26 23:23 UTC, IgorMinar approved these changes

2017-06-27 00:27 UTC, mary-poppins commented
The angular.io preview for 5e399ead6e64928596b3208a94f93f35e8ed72b4 is available [here][1].

[1]: https://pr17601-5e399ead6e64928596b3208a94f93f35e8ed72b4.ngbuilds.io/

2017-06-27 22:44 UTC, mary-poppins commented
You can preview 683f880733335fd3b8732e3106835953fa4b81d5 at https://pr17601-683f880733335fd3b8732e3106835953fa4b81d5.ngbuilds.io/.

2017-07-01 17:30 UTC, merged