feat(core): support for bootstrap with custom zone
angular/angular pull request #17672
Opened 2017-06-21 20:26 UTC by jasonaden

This PR is based on Misko's PR (#17142), with PR comments addressed.

2017-06-21 21:07 UTC, mary-poppins commented
The angular.io preview for 2fbe11978106b86f912b91500093f686fd06ee27 is available [here][1].

[1]: https://pr17672-2fbe11978106b86f912b91500093f686fd06ee27.ngbuilds.io/

2017-06-21 22:03 UTC, mary-poppins commented
The angular.io preview for c8c66486735c08e8bed441806205854490b3640e is available [here][1].

[1]: https://pr17672-c8c66486735c08e8bed441806205854490b3640e.ngbuilds.io/

2017-06-21 22:29 UTC, mary-poppins commented
The angular.io preview for 75bbe3811f26251c114eb0ecb4a7da9abd3d18b7 is available [here][1].

[1]: https://pr17672-75bbe3811f26251c114eb0ecb4a7da9abd3d18b7.ngbuilds.io/

2017-06-22 17:14 UTC, mary-poppins commented
The angular.io preview for 181e4497be5b8e3ba8f57b07063d7b9a601f3a7c is available [here][1].

[1]: https://pr17672-181e4497be5b8e3ba8f57b07063d7b9a601f3a7c.ngbuilds.io/

2017-06-22 17:20 UTC, vicb commented on packages/core/src/application_ref.ts
> +      if (objs.hasOwnProperty(key)) {
`Object.keys()`

2017-06-22 17:24 UTC, vicb approved these changes

2017-06-22 17:31 UTC, jasonaden commented on packages/core/src/application_ref.ts
> +      if (objs.hasOwnProperty(key)) {
Spread operator.

2017-06-22 17:47 UTC, mary-poppins commented
The angular.io preview for 8a13973e7506e7971d82a28384aec91cd4a5ff38 is available [here][1].

[1]: https://pr17672-8a13973e7506e7971d82a28384aec91cd4a5ff38.ngbuilds.io/

2017-06-22 20:14 UTC, IgorMinar submitted a review, later dismissed

2017-06-22 20:14 UTC, IgorMinar commented on packages/core/test/zone/ng_zone_spec.ts
> +      expect(ngZone.onMicrotaskEmpty instanceof EventEmitter).toBe(true);
doesn't typechecking verify this?

2017-06-22 20:14 UTC, IgorMinar commented on packages/core/test/zone/ng_zone_spec.ts
> +        ngZone.runGuarded(() => { ngZone.runOutsideAngular(() => { works = true; }); });
how does this proves that the NoNgZone works?

2017-06-22 20:14 UTC, IgorMinar commented on packages/core/src/zone/ng_zone.ts
> +export class NoNgZone implements NgZone {
you described the zone as "noop", why do we then call it "No*"? I propose that you rename it to "NoopNgZone".

2017-06-22 20:14 UTC, IgorMinar commented on tools/public_api_guard/core/core.d.ts
> +    /** @stable */ abstract bootstrapModule<M>(moduleType: Type<M>, compilerOptions?: (CompilerOptions & BootstrapOptions) | Array<CompilerOptions & BootstrapOptions>): Promise<NgModuleRef<M>>;
BootstrapOptions are not being exported.

But more importantly, why do we export both the BootstrapOptions with "none" literal string API as well as No(op)NgZone. We should either not export No(op)NgZone, or export it and then allow BootstrapOptions to accept it without going through the "none" string.

And if we do stick to the "none" string literal, we should likely rename it to "noop" to be consistent with the internal naming as well as external behavior (it's not like NgZone doesn't exist, it's just that it doesn't do anything).

2017-06-23 17:28 UTC, jasonaden commented on packages/core/test/zone/ng_zone_spec.ts
> +        ngZone.runGuarded(() => { ngZone.runOutsideAngular(() => { works = true; }); });
The test is for `should run` which this does prove since it's calling all the `run*` functions.

2017-06-23 17:30 UTC, jasonaden commented on packages/core/test/zone/ng_zone_spec.ts
> +      expect(ngZone.onMicrotaskEmpty instanceof EventEmitter).toBe(true);
It verifies the type, but not the runtime `instanceof` check.

2017-06-23 18:34 UTC, mary-poppins commented
The angular.io preview for 87ba8a504fad3361b412a07e72b9c66e91008f74 is available [here][1].

[1]: https://pr17672-87ba8a504fad3361b412a07e72b9c66e91008f74.ngbuilds.io/

2017-06-26 19:06 UTC, mary-poppins commented
The angular.io preview for 26e804f26df3aa87c9419935ec7b16ab4f55a515 is available [here][1].

[1]: https://pr17672-26e804f26df3aa87c9419935ec7b16ab4f55a515.ngbuilds.io/

2017-07-05 22:25 UTC, mhevery requested changes

2017-07-05 22:25 UTC, mhevery commented on tools/public_api_guard/core/core.d.ts
> +export declare class NoNgZone implements NgZone {
`NoNgZone` is private implementation and should not be exported.

2017-07-05 22:25 UTC, mhevery commented on packages/core/src/application_ref.ts
> +  ngZone?: NgZone|'default'|'none';
this should be `NgZone|'zone.js'|'noop'`

2017-07-05 22:25 UTC, mhevery commented on packages/core/src/zone/ng_zone.ts
>  export class NgZone {
- rename `NgZone` to `ZoneJSNgZone`.
- Create new abstract class `NgZone` to be an injection token.
- have `ZoneJSNgZone` and `NoopNgZone` extends `NgZone`

2017-09-13 10:05 UTC, ocombe commented on packages/upgrade/src/dynamic/upgrade_adapter.ts
> +    angular.bootstrap(element, [this.ng1Module.name], config !);
@IgorMinar @mhevery: I had to do this change to make the upgrade_spec tests pass, otherwise they would (almost) all fail with the error `Error: Uncaught (in promise): Error: Expected to not be in Angular Zone, but it is!`.
I don't know if it is the correct fix or not.

2017-09-13 10:06 UTC, ocombe commented
Rebased & refactored based on your comments.

2017-09-13 10:15 UTC, mary-poppins commented
You can preview d04cea8 at https://pr17672-d04cea8.ngbuilds.io/.

2017-09-13 10:42 UTC, gkalpak commented on packages/upgrade/src/dynamic/upgrade_adapter.ts
> +    angular.bootstrap(element, [this.ng1Module.name], config !);
This doesn't look right 😟 
(But no idea why the tests fail.)

2017-09-13 13:05 UTC, gkalpak commented on packages/upgrade/src/dynamic/upgrade_adapter.ts
> +    angular.bootstrap(element, [this.ng1Module.name], config !);
AFAICT, this PR is just a refactoring as far as ngUpgrade is concerned. Under the hood, the exact same operations should happen while bootstrapping. It is surprizing that the behavior has changed.

(Do I miss something, @ocombe?)

2017-09-13 13:11 UTC, ocombe commented on packages/upgrade/src/dynamic/upgrade_adapter.ts
> +    angular.bootstrap(element, [this.ng1Module.name], config !);
I agree, I've searched in the updated code for what could be the reason for this, but I couldn't find it, that's why I added this comment saying that it's probably incorrect

2017-09-13 17:42 UTC, mary-poppins commented
You can preview 8c0886f at https://pr17672-8c0886f.ngbuilds.io/.

2017-09-13 17:44 UTC, ocombe commented
I've pushed my code without the change to zone run in the upgrade file, but it fails the tests on travis as expected: https://travis-ci.org/angular/angular/jobs/275139988#L1020

2017-09-13 19:41 UTC, ocombe commented
The code has been fixed, there was an error in the optionsReducer function which ended up creating 2 NgZone instances (thanks @mhevery for finding where the bug was). I added a test for that as well.

2017-09-13 19:46 UTC, mary-poppins commented
You can preview 02190de at https://pr17672-02190de.ngbuilds.io/.

2017-09-13 20:20 UTC, mhevery approved these changes

2017-09-15 18:07 UTC, matsko commented
@jasonaden @mhevery please rebase

2017-09-15 20:07 UTC, mhevery commented
Actually this is now owned by @ocombe and he said he will rebase.

2017-09-15 20:34 UTC, mary-poppins commented
You can preview 9165169 at https://pr17672-9165169.ngbuilds.io/.

2017-09-15 20:52 UTC, mary-poppins commented
You can preview 0b64c26 at https://pr17672-0b64c26.ngbuilds.io/.

2017-09-20 21:19 UTC, IgorMinar commented
can you please rebase?

2017-09-21 08:46 UTC, mary-poppins commented
You can preview 64256bd at https://pr17672-64256bd.ngbuilds.io/.

2017-09-21 08:50 UTC, ocombe commented
Rebased!

2017-09-21 23:06 UTC, mary-poppins commented
You can preview 18507b0 at https://pr17672-18507b0.ngbuilds.io/.

2017-09-22 00:59 UTC, closed without merging