fix(aio): restore visible keyboard focus
angular/angular pull request #17831
Opened 2017-06-29 07:02 UTC by wardbell

To prevent keyboard focus on hidden child nodes,
also collapses inner expanded nodes when parent node is collapsed.
The implicit parent node of top nodes is always expanded.

Also, raise the right-TOC by 20px (96px->76px) because was too far down.

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

2017-06-29 07:16 UTC, mary-poppins commented
You can preview 03d16cb8da8705c737ed93bb3526a50ed4c87ddc at https://pr17831-03d16cb8da8705c737ed93bb3526a50ed4c87ddc.ngbuilds.io/.

2017-06-29 07:25 UTC, mary-poppins commented
You can preview ea581b8f31b26ef622dbc9993afe9226d3930273 at https://pr17831-ea581b8f31b26ef622dbc9993afe9226d3930273.ngbuilds.io/.

2017-06-29 08:06 UTC, gkalpak approved these changes
A couple of minor suggestions/questions.
LGTM otherwise.

2017-06-29 08:06 UTC, gkalpak commented on aio/src/app/layout/nav-item/nav-item.component.ts
> +      this.isExpanded = this.isParentExpanded &&
I am not sure how I feel about this, but I think I lean towards liking it :grin:

2017-06-29 11:25 UTC, petebacondarwin commented
Why are we averse to just using an `ngIf` or perhaps changing the exposed `nodeChildren` array when the item is not expanded? Doing so would avoid the hack of tracking whether the parent item is expanded or not.

2017-06-29 11:25 UTC, petebacondarwin commented on aio/src/app/layout/nav-item/nav-item.component.ts
> +      this.isExpanded = this.isParentExpanded &&
I am not sure I like it

2017-06-29 11:36 UTC, petebacondarwin requested changes
I agree with @gkalpak's comments and suggest that they are acted upon.

2017-06-29 17:06 UTC, wardbell commented on aio/src/styles/2-modules/_toc.scss
>    bottom: 32px;
I agree. Not sure where all the pieces are. My starting question ... do you agree that TOC needs to start higher on the page?

2017-06-29 17:07 UTC, wardbell commented on aio/src/styles/1-layouts/_sidenav.scss
> +    padding-left: 2px;
How much more?

Btw ... have you seen how tight the outline is for the right TOC items? I think it's zero px. Do you feel the same way about that?

2017-06-29 17:09 UTC, Foxandxss commented
I like that it is more obvious now, but what is with that black to blue animation? :P

2017-06-29 17:09 UTC, wardbell commented
@petebacondarwin I considered `*ngIf`. It doesn't make the code easier and the expand animation goes away! We aren't using Angular Animations (because of size?). So I stuck with this approach.

2017-06-29 17:18 UTC, wardbell commented on aio/src/styles/1-layouts/_sidenav.scss
> +    outline-color: $accentblue;
I stole that CSS from elsewhere. Damned if I know.  Will fix.

2017-06-29 17:55 UTC, gkalpak commented on aio/src/styles/2-modules/_toc.scss
>    bottom: 32px;
I have also thought that it started lower than necessary, but I assumed it was a concious design decision :grin: I don't mind either way.

2017-06-29 18:00 UTC, gkalpak commented on aio/src/styles/1-layouts/_sidenav.scss
> +    padding-left: 2px;
Yeah. ToC could use some space too, but at least it is symmetric on the two sides. It is also less obvious in ToC, because it is not obvious on hover, only when focused. With the left SideNav, hovering over the items makes their background gray which makes it obvious that the left and right padding are quite different:

![test](https://user-images.githubusercontent.com/8604205/27702814-fe6bce3c-5d0d-11e7-8ac7-30472d93df51.png)

2017-06-29 18:32 UTC, IgorMinar commented
@wardbell TOC alignment adjustment lgtm

2017-06-29 22:32 UTC, wardbell commented on aio/src/styles/2-modules/_toc.scss
>    bottom: 32px;
I changed to `bottom: 12px;` and reduced the "fudge margin" in the [`maxTocHeight` calculation][1] as you suggested.


[1]: https://github.com/IdeaBlade/angular/blob/ea581b8f31b26ef622dbc9993afe9226d3930273/aio/src/app/app.component.ts#L280

2017-06-29 22:33 UTC, wardbell commented
@Foxandxss @sjtrimble removed the gray->blue transition as you requested.

2017-06-29 22:35 UTC, mary-poppins commented
You can preview dc16c05 at https://pr17831-dc16c05.ngbuilds.io/.

2017-06-29 22:56 UTC, mary-poppins commented
You can preview 5627c3a at https://pr17831-5627c3a.ngbuilds.io/.

2017-06-30 10:58 UTC, merged

2017-06-30 10:59 UTC, petebacondarwin commented
Cherry picked via 7080fccb38ba41b11b0deb25e1b8d15fbc9c856c