docs(aio): Add resources contributor info
angular/angular pull request #17851
Opened 2017-06-29 18:25 UTC by StephenFluin

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?

```
[X] Documentation content changes

```

2017-06-29 18:28 UTC, juleskremer approved these changes

2017-06-30 08:55 UTC, gkalpak requested changes
Shouldn't a corresponding entry be added to `navigation.json`? Else this will be hidden in the site, but not easily accessible. (Or is this intended atm?)

2017-06-30 08:55 UTC, gkalpak commented on aio/content/marketing/resources-contributing.md
> +1. Your contribution should have a clear and concise title and description
Missing `.` (here and below) :grin:

2017-06-30 08:55 UTC, gkalpak commented on aio/content/marketing/resources-contributing.md
> +1. Your resource should follow our brand guidelines (see our [https://angular.io/presskit](Presskit))
Didn't you mean `[Presskit](https://angular.io/presskit)`?

2017-06-30 08:55 UTC, gkalpak commented on aio/content/marketing/resources-contributing.md
> +# How do I get listed?
Douments are not allowed to have multiple `<h1>` elements (anf that's why the `aio` job fails on Travis.

2017-06-30 18:41 UTC, StephenFluin commented on aio/content/marketing/resources-contributing.md
> +# How do I get listed?
Correcting to a single H1

2017-06-30 18:42 UTC, StephenFluin commented on aio/content/marketing/resources-contributing.md
> +1. Your contribution should have a clear and concise title and description
Removing `.`

2017-06-30 18:42 UTC, StephenFluin commented on aio/content/marketing/resources-contributing.md
> +1. Your resource should follow our brand guidelines (see our [https://angular.io/presskit](Presskit))
I did!

2017-06-30 18:42 UTC, StephenFluin commented
Not linking to this page from navigation is intentional. The hope is that it is only seen by those looking in the source code and trying to modify `resources.json`.

2017-06-30 18:52 UTC, mary-poppins commented
You can preview 69ec333 at https://pr17851-69ec333.ngbuilds.io/.

2017-06-30 19:22 UTC, gkalpak approved these changes

2017-06-30 19:24 UTC, gkalpak commented
> Not linking to this page from navigation is intentional. The hope is that it is only seen by those looking in the source code and trying to modify resources.json.

Just beware that this _will_ show up in search results too :grin:
https://pr17851-69ec333.ngbuilds.io/?search=resources

2017-06-30 20:23 UTC, mary-poppins commented
You can preview 6b6a8e5 at https://pr17851-6b6a8e5.ngbuilds.io/.

2017-07-01 13:38 UTC, merged

2017-07-01 13:39 UTC, petebacondarwin commented
Cherry picked into 4.2.x as c460757d2ec2bae9276b2fd1f2b5422804b15f53