build(aio): various API doc-gen fixes and improvements
angular/angular pull request #17857
Opened 2017-06-29 21:32 UTC by petebacondarwin

Closes #17669
Closes #17041

2017-07-02 18:48 UTC, mary-poppins commented
You can preview 9b44880 at https://pr17857-9b44880.ngbuilds.io/.

2017-07-02 18:50 UTC, petebacondarwin commented
Hurray it works! Please review...

2017-07-02 18:51 UTC, petebacondarwin commented
Here is a page that shows multiple exported function overloads: https://pr17857-9b44880.ngbuilds.io/api/core/testing/withModule

![screen shot 2017-07-02 at 19 50 53](https://user-images.githubusercontent.com/15655/27772719-c25c8e50-5f5f-11e7-9b0a-0afc8475b72d.png)

2017-07-02 18:52 UTC, petebacondarwin commented
`NgForOf` is a directive page, but also shows overloads for the `ngForTrackBy` setter: https://pr17857-9b44880.ngbuilds.io/api/common/NgForOf

![screen shot 2017-07-02 at 19 52 12](https://user-images.githubusercontent.com/15655/27772725-f9c57578-5f5f-11e7-8f2d-44fab85c76ec.png)

2017-07-02 18:54 UTC, petebacondarwin commented
Here is the `Injector` with overloads, mentioned in #17041: https://pr17857-9b44880.ngbuilds.io/api/core/Injector

![screen shot 2017-07-02 at 19 53 20](https://user-images.githubusercontent.com/15655/27772743-33ed6544-5f60-11e7-8fd0-bccfc9e1979f.png)

2017-07-02 18:55 UTC, petebacondarwin commented
Here you can see the `ActivatedRouteSnapshot` is now displaying all its public properties (mentioned in #17669): https://pr17857-9b44880.ngbuilds.io/api/router/ActivatedRouteSnapshot

![screen shot 2017-07-02 at 19 54 53](https://user-images.githubusercontent.com/15655/27772753-6652c84e-5f60-11e7-8154-56231d163d94.png)

2017-07-05 21:09 UTC, gkalpak reviewed
This looks great 💯 

I wonder why `InjectSetupWrapper` placed on new line ([here][1])? Is it related to this PR (I couldn't really tell).
![with-module](https://user-images.githubusercontent.com/8604205/27884690-d3bcabd2-61dd-11e7-9b47-27441d865791.png)

Another thing that would be nice (not for this PR) is making mentioned types (e.g. param or return types) links to the corresponding entities. E.g. `TestModuleMetadata` and `InjectSetupWrapper` [here][1] could be links to the API docs for `TestModuleMetadata` and `InjectSetupWrapper` respectively.

[1]: https://pr17857-9b44880.ngbuilds.io/api/core/testing/withModule

2017-07-05 21:32 UTC, petebacondarwin commented on aio/tools/transforms/angular-api-package/processors/matchUpDirectiveDecorators.js
> +  return (typeof(value) === 'string') ? value.replace(/^(['"])(.*)\1/, '$2') : value;
That would not be valid but happy to tighten up the regex

2017-07-05 21:34 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/decorator.template.html
> +  {% include "includes/interface-overview.html" %}
Well.... decorators are actually made up of a couple of different kind of code elements that we merge together. I am (re)using the interface-overview because it felt most appropriate for this type. Happy to change if you have a better idea.

2017-07-05 21:36 UTC, petebacondarwin commented
RE: `InjectSetupWrapper` the layout of the return type is taken directly from the source code. See https://github.com/angular/angular/blob/c805082648b3067a7b0f3d21a1d1ea0edf77e4df/packages/core/testing/src/test_bed.ts#L540-L541

I didn't feel confident trying to reformat the text from the source file, since to do that correctly would require writing a load of code that can render the TypeScript AST.

2017-07-05 22:11 UTC, gkalpak commented on aio/tools/transforms/templates/api/decorator.template.html
> +  {% include "includes/interface-overview.html" %}
My only concern is that this will be printed as `interface SomeDecorator { ... }`. If that will always be true, then `interface-overview` is fine.

2017-07-06 11:22 UTC, petebacondarwin commented on aio/tools/transforms/angular-api-package/processors/mergeDecoratorDocs.js
> +          var callMember = doc.members.filter(function(member) { return member.isCallMember; })[0];
I will add an extra member to the array of mock members, which is not a callMember.
In practice this is not valid (or at least as far as I know we are not interested in such members) so we ignore them.

So the tests should just not fail with such a member; rather than doing anything in particular.

2017-07-06 11:37 UTC, petebacondarwin commented on aio/tools/transforms/angular-api-package/processors/matchUpDirectiveDecorators.spec.js
> +});
adding...

2017-07-06 11:41 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/decorator.template.html
> +  {% include "includes/interface-overview.html" %}
Fair point. I will create a more specific include for decorators.

2017-07-10 10:00 UTC, mary-poppins commented
You can preview 125d6d5 at https://pr17857-125d6d5.ngbuilds.io/.

2017-07-10 12:34 UTC, gkalpak requested changes
Overall looks great. Just a couple of small things.

2017-07-10 12:34 UTC, gkalpak commented on aio/tools/transforms/examples-package/inline-tag-defs/example.spec.js
> +        handler({}, 'example', 'test/uri missing-region');
Should this be `test/url`?

2017-07-10 12:34 UTC, gkalpak commented on aio/content/marketing/index.html
> +@title Home
This causes an `<h1>` element to be included, which creates an empty ToC but most importantly breaks the layout (look at the top right corner):

![broken-home](https://user-images.githubusercontent.com/8604205/28018174-e501e8f8-6584-11e7-8932-550684bd98bf.png)

2017-07-10 14:40 UTC, petebacondarwin commented on aio/content/marketing/index.html
> +@title Home
I'm going to revert this commit and redo it in a separate PR, so that we can merge this without waiting for marketing approval.

2017-07-10 15:15 UTC, mary-poppins commented
You can preview 0602593 at https://pr17857-0602593.ngbuilds.io/.

2017-07-10 16:08 UTC, Foxandxss approved these changes

2017-07-10 17:25 UTC, petebacondarwin commented
@gkalpak PTAL

2017-07-10 20:20 UTC, gkalpak approved these changes

2017-07-11 10:44 UTC, merged

2017-07-11 10:51 UTC, petebacondarwin commented
Cherry picked to 4.2.x via:

09261e6c4d2360747048e23ccd60ba570bc2ea1f docs(aio): fix dangling links
b61c19a86ea0e90d4734d1b4402341c937cdcb00 build(aio): fix matchUpDirectiveDecorators processor
f6ebb40fbc1d63c017a055bb0c885829ee09ad10 build(aio): fix mergeDecoratorDocs processor
0ce454299038e4d04e0be40b31c601c2849b8b72 docs(aio): fix potential invalid jsdoc tag
8072fe120aa370d7350cffddd39ecedc7bf7db12 build(aio): use dedicated overview for decorator API docs
50e79ace12906992987bd34257864003d6b6dc5c build(aio): update doc-gen templates
aa39449ce4d7f0e46cb5dea60c5561802e244d2d build(aio): fix mergeDecoratorDocs processor
d1434e82dfb66ba23a10d1f2b93fd1f20d602f32 build(aio): fix matchUpDirectiveDecorators processor
6a0d5b58259f07539f3b972a07e3c1236ec6f654 build(aio): fix test description
5e4c41fcdfd14c060bed8f50730184a15cf96a3b build(aio): refactor filterMemberDocs to be more general
4c8413986e3870d4bb2928b079ea4d34fb3eca28 build(aio): upgrade to dgeni-packages v0.20.0-rc.1