docs(core): add API docs for i18n tokens
angular/angular pull request #17920
Opened 2017-07-04 15:09 UTC by ocombe

## PR Type
What kind of change does this PR introduce?
```
[x] Documentation content changes
```

## What is the current behavior?
No API docs on i18n tokens

## What is the new behavior?
Documentation is available

## Does this PR introduce a breaking change?
```
[x] No
```

2017-07-04 16:11 UTC, mary-poppins commented
You can preview 975a5ae at https://pr17920-975a5ae.ngbuilds.io/.

2017-07-04 16:28 UTC, mary-poppins commented
You can preview 82b7a06 at https://pr17920-82b7a06.ngbuilds.io/.

2017-07-05 20:50 UTC, vicb commented on packages/core/src/i18n/tokens.ts
> + * is used for i18n extraction, in i18n pipes ({@link DatePipe}, {@link I18nPluralPipe},
used "by" * 2(instead of in)

2017-07-05 20:51 UTC, vicb commented on packages/core/src/i18n/tokens.ts
> + * This token has to be provided at bootstrap because it is used by the HTML compiler.
could you please describe JIT vs AOT

2017-07-05 20:53 UTC, vicb commented on packages/core/src/i18n/tokens.ts
> + * - Error
docs what each value means

2017-07-05 20:53 UTC, vicb requested changes
We should probably make what apply to JIT only more explicit. Otherwise :+1:

2017-07-07 14:19 UTC, mary-poppins commented
You can preview ac67960 at https://pr17920-ac67960.ngbuilds.io/.

2017-07-07 14:24 UTC, mary-poppins commented
You can preview 9d3ce7c at https://pr17920-9d3ce7c.ngbuilds.io/.

2017-07-07 14:31 UTC, ocombe commented
@vicb let me know if the updates are ok for you

2017-07-07 20:15 UTC, vicb commented
blocked on https://github.com/angular/angular/issues/16960

2017-07-07 20:17 UTC, vicb commented on packages/core/src/i18n/tokens.ts
> + * is used for i18n extraction, by i18n pipes ({@link DatePipe}, {@link I18nPluralPipe},
remove the link here (because it will get outdated at some point) and add the link there

2017-07-07 20:17 UTC, vicb commented on packages/core/src/i18n/tokens.ts
> + * If you are using AOT, you can define the locale with the cli parameter `--locale` for ngc
should not be on this API doc - move to angular.io

2017-07-07 20:18 UTC, vicb commented on packages/core/src/i18n/tokens.ts
> + * ```typescript
should be on angular.io (we do not use inline exemple any more in the API doc any more but include them from the examples folder AFAIR)

2017-07-07 20:18 UTC, vicb commented on packages/core/src/i18n/tokens.ts
> + * ```typescript
The comment on this doc block apply to all blocks in this PR

2017-07-07 21:18 UTC, ocombe commented on packages/core/src/i18n/tokens.ts
> + * If you are using AOT, you can define the locale with the cli parameter `--locale` for ngc
something like: "If you are using AOT see [i18n guide](https://angular.io/guide/i18n)" ?

2017-07-10 16:11 UTC, mary-poppins commented
You can preview 2d54ba1 at https://pr17920-2d54ba1.ngbuilds.io/.

2017-07-26 19:56 UTC, mary-poppins commented
You can preview 12b706b at https://pr17920-12b706b.ngbuilds.io/.

2017-11-21 17:48 UTC, vicb commented
As commented earlier this was not merged because it does not work as documented in JIT ("blocked on #16960").

Please either fix the root cause or remove the misleading doc from this PR.

I would like this PR closed by eow. Either by merging it or closing it as non applicable.

2017-11-22 10:29 UTC, ocombe commented
I've updated the docs, waiting for the docs team to give me my approval on the changes. I've noticed that we removed the docs on the missing translation strategy from the guide in v5, which is why I added it again here at the same time.

2017-11-22 10:34 UTC, mary-poppins commented
You can preview bb24d4f at https://pr17920-bb24d4f.ngbuilds.io/.

2017-11-22 10:40 UTC, mary-poppins commented
You can preview 73036fe at https://pr17920-73036fe.ngbuilds.io/.

2017-11-22 10:53 UTC, mary-poppins commented
You can preview 7951e7c at https://pr17920-7951e7c.ngbuilds.io/.

2017-11-24 16:54 UTC, mary-poppins commented
You can preview 203f5ce at https://pr17920-203f5ce.ngbuilds.io/.

2017-11-24 19:17 UTC, vicb commented on aio/content/guide/i18n.md
> +but since specifications change over time, here is a list of equivalences between old locale
Need some love from a native speaker.

2017-11-24 19:18 UTC, vicb approved these changes

2017-11-24 19:19 UTC, vicb commented
LGTM for the correctness of the information.
Needs some proof reading / updates by someone on the doc team

2017-11-28 17:08 UTC, jbogarthyde commented on aio/content/guide/i18n.md
> +but since specifications change over time, here is a list of equivalences between old locale
The locale identifiers used by CLDR and Angular are based on [BCP47](http://www.rfc-editor.org/rfc/bcp/bcp47.txt).  These specifications change over time; the following table maps old identifiers to current ones at time of writing.

2017-11-28 19:58 UTC, jbogarthyde reviewed
Copy-edit suggestions

2017-11-28 19:58 UTC, jbogarthyde commented on aio/content/guide/i18n.md
>  </div>
Notice that the tool has assigned generated IDs, which are hard to work with and are regenerated when either the text or meaning changes. We recommend that you [specify custom IDs](guide/i18n#custom-id), in order to avoid [maintenance](guide/i18n#maintenance) problems.

2017-11-28 19:58 UTC, jbogarthyde commented on aio/content/guide/i18n.md
>  A nested expression is similar to the previous examples. As in the previous example, there are
A nested expression, like a select statement, gets broken into separate translation units for the outer and inner expressions. The first one contains...

2017-11-28 19:58 UTC, jbogarthyde commented on aio/content/guide/i18n.md
>  into the app.
Lose this line - it doesn't add anything and there is another subsection before the "next section".

2017-11-28 19:58 UTC, jbogarthyde commented on aio/content/guide/i18n.md
>  The sample app and its translation file are now as follows:
After completing the translations, the sample app and translation files are ready to be merged. The prepared files look like this:

2017-11-28 19:58 UTC, jbogarthyde commented on aio/content/guide/i18n.md
> +
There are a bunch of subsections missing here that show up in Mary Poppins -- I wanted to make an edit in the first one, "SystemsJS text plugin" -- is it part of another PR?
The others are "Create translation providers", "Bootstrap with translation providers", and "Internationalization with the AOT compiler" -- do you want a copy edit on those?

2017-11-28 19:58 UTC, jbogarthyde commented on aio/content/guide/i18n.md
> +</code-example>
The last section is also missing -- and there is a reference to it earlier: guide/i18n#file-maintenance-and-id-changes

2017-11-28 19:58 UTC, jbogarthyde commented on aio/content/guide/i18n.md
>  ## i18n pipes
This section is missing from the Mary Poppins page I'm looking at (https://pr17920-9d3ce7c.ngbuilds.io/guide/i18n)
The descriptive text for the code example can use some work, but I can't do it without seeing the code that's being described. 
Did the pipes section get moved somewhere else? It does seem to be kind of out-of-place here.

2017-11-29 09:02 UTC, ocombe commented
@jbogarthyde use the last preview link: https://pr17920-203f5ce.ngbuilds.io/guide/i18n
I've removed the other ones to avoid confusion

2017-11-30 21:39 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +but since specifications change over time, here is a list of equivalences between old locale
Agree with Judy's recommendation.

2017-11-30 21:39 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +but since specifications change over time, here is a list of equivalences between old locale
(optional) Additional refinement: Can we say what we mean by "old"? Angular v4? BCP47 in 2015?

2017-11-30 21:47 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +while the second parameter is the locale id for which you want to register those data. This second
Recommend shorter sentences: "The first parameter is an object containing the locale data imported from 'angular/common/locales'.

2017-11-30 21:54 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +in the list of locales supported by Angular.
Tech questions: I'm a bit confused because it sounds like the second parameter is used to associate imported locale data with a custom locale id, but the example shows the id 'fr' which is a standard predefined id. In this case, does the imported locale data get registered with that standard id, replacing any standard or previous registered data? If I don't include the second parameter, what happens with the object that represents the imported locale data? Do I  just have to use the object, because there is no shorthand (id) assigned?

2017-11-30 21:58 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +  * With [JIT](guide/i18n#merge-jit), you provide the information at bootstrap time.
Confirmed. Links work as desired.

2017-11-30 22:07 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +When a translation is missing, the build will succeed but it will print a warning that you might
Edit: When a translation is missing, the build succeeds but generates a warning. You can configure...

2017-11-30 22:12 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +* Error: throw if you have missing translations.
Edits:
Error: throw an error. 
Warning (default): Show a warning in the console or shell.
Ignore: do nothing.

2017-11-30 22:13 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +* Warning (default): show a warning in the console and/or shell.
Can we offer more information? 
Error: Does the build still succeed or does it fail? What is the error message or keyword to search for in error logs or messages?
Warning: What is the warning or keyword to search for?

2017-11-30 22:15 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +To change this behavior use the CLI parameter `--missingTranslation` with the name of the strategy
Edit: If you use the AOT compiler, you can specify the warning level by using the CLI parameter '--missingTranslation'. The example below shows how to set the warning level to error:

2017-11-30 22:19 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +If you use JIT, you need to provide the missing translation strategy in the compiler config at
Edit: If you use the JIT compiler, specify the warning level in the compiler config at bootstrap by adding the 'MissingTranslationStrategy' parameter. The example below shows how to set the warning level to error:

(I'm not sure if the right word is parameter or option or setting. Choose the right word for how you talk about the compiler config file things.)

2017-11-30 22:20 UTC, jenniferfell commented
Review completed. I understand that any comments we made on lines that aren't affected by this PR won't be incorporated at this time.

2017-12-01 09:12 UTC, ocombe commented on aio/content/guide/i18n.md
> +in the list of locales supported by Angular.
if you don't specify the second parameter, it will use what's defined in the data (for "fr" it will be "fr", for en-GB it will be "en-GB"...)
But if you want to use "fr-FR" for fr data, you have to specify that, otherwise it'll use "fr" by default

2017-12-01 09:13 UTC, ocombe commented on aio/content/guide/i18n.md
> +but since specifications change over time, here is a list of equivalences between old locale
old = anything before the last update of BCP47

2017-12-01 09:22 UTC, ocombe commented on aio/content/guide/i18n.md
> +* Warning (default): show a warning in the console and/or shell.
An error will fail the build for AOT, or fail the app loading for JIT.
The error/warning message will be something like that: `Missing translation for message "foo"`.

2017-12-01 09:26 UTC, ocombe commented on aio/content/guide/i18n.md
> +If you use JIT, you need to provide the missing translation strategy in the compiler config at
In this case the correct word would be "property"

2017-12-04 21:51 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +but since specifications change over time, here is a list of equivalences between old locale
Can we be specific about a date or version of BCP47 that is "old"? The standard I found is from 2009, so is old "prior to the 2009 update of BCP47"? https://tools.ietf.org/html/bcp47

2017-12-04 22:03 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +* Warning (default): show a warning in the console and/or shell.
Let's be clear that's the default. 
By default, when a translation is missing, the build succeeds but generates a warning such as Missing translation for message "foo". You can configure the level of warning that is generated by the Angular compiler.

2017-12-04 22:05 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +* Error: throw if you have missing translations.
We can add more detail to this list. 
Error: throws an error. If you are using AOT compilation, the build will fail. If you are using JIT compilation, the app will fail to load. 
Warning (default): show a 'Missing translation' warning in the console or shell.
Ignore: do nothing

2017-12-04 22:06 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +* Warning (default): show a warning in the console and/or shell.
See above for suggestions to incorporate more of this detail into the bulleted list

2017-12-04 22:18 UTC, jenniferfell commented on aio/content/guide/i18n.md
> +in the list of locales supported by Angular.
Ah ha! That makes sense. So maybe change the example to "fr-FR" so it's not already using the default. Then lets add that info:
"The first parameter is an object containing the locale data imported from 'angular/common/locales'. By default, the imported locale data is registered with the locale id that is defined in the Angular locale data itself.  If you want to register the imported locale data with another locale id, use the second parameter to specify a custom locale id. For example, Angular's locale data defines the locale id for French as "fr". You can use the second parameter to associate the imported French locale data with the custom locale id "fr-FR."

2017-12-04 22:19 UTC, jenniferfell commented
@ocombe Replied to your questions.

2017-12-05 13:20 UTC, ocombe commented on aio/content/guide/i18n.md
> +but since specifications change over time, here is a list of equivalences between old locale
I'm not sure about the date of each change, let's keep it like this for now.

2017-12-05 13:50 UTC, mary-poppins commented
You can preview d7ec1c6 at https://pr17920-d7ec1c6.ngbuilds.io/.

2017-12-05 14:02 UTC, gkalpak approved these changes
LGTM (as long as both Travis and @jenniferfell are happy :smiley:)

2017-12-05 14:02 UTC, gkalpak commented on packages/core/src/i18n/tokens.ts
> + * });
Hard-coded example 😱 
<sub>(Ideally all code snippets should come from actual examples.)</sub>

2017-12-05 17:52 UTC, jenniferfell approved these changes

2017-12-05 17:56 UTC, jenniferfell commented
I approve all the text changes. I'm okay with deferring work to fix the hard-coded example. 

Footnote on my approval:  I can't speak to why Travis is failing. That probably needs to be addressed before merge.

2017-12-06 14:42 UTC, closed without merging