fix(aio): add actual promo img w/h for consistent sizing
angular/angular pull request #17927
Opened 2017-07-04 22:41 UTC by sjtrimble

+ restructured the order of attributes on home page images so they consistent among all pictures

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number:
Addresses images sizing component of https://github.com/angular/angular/pull/17658 as intended

## What is the new behavior?
Image width and height set to actual height with max height restriction consistent with maintaining a max height on the images.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2017-07-04 22:58 UTC, mary-poppins commented
You can preview 2c95289 at https://pr17927-2c95289.ngbuilds.io/.

2017-07-05 16:24 UTC, gkalpak commented on aio/src/styles/2-modules/_images.scss
> +    max-height: 240px;
Isn't this style always applied? If so, why do we need to specify widths and heights explicitly?

2017-07-05 16:41 UTC, sjtrimble commented on aio/content/marketing/index.html
> +          <img src="assets/images/home/responsive-framework.svg" width="1295" height="795" alt="responsive framework">
Yes, that would be cleaner :) is that what we should do? I had second thoughts as this is the home page and got worried if something breaks with Dgeni ... perhaps some tests could fix that?

2017-07-05 16:42 UTC, sjtrimble commented on aio/src/styles/2-modules/_images.scss
> +    max-height: 240px;
@gkalpak I have a cleanup PR https://github.com/angular/angular/pull/17926 that moves this over to the appropriate section .. that might address your comment. Not sure I follow otherwise.

2017-07-05 18:03 UTC, gkalpak commented on aio/content/marketing/index.html
> +          <img src="assets/images/home/responsive-framework.svg" width="1295" height="795" alt="responsive framework">
Nothing breaks when dgeni takes care of it :smiley:
(Even statistically, we (humans) have broken much more things than dgeni in this project 😛)

2017-07-05 18:04 UTC, gkalpak commented on aio/src/styles/2-modules/_images.scss
> +    max-height: 240px;
I mean if this style is always in effect (i.e. not on specific screen sizes), then the widths/heights set as attributes on the `<img>` elements shouldn't have much effect, right?

2017-07-05 22:07 UTC, IgorMinar requested changes

2017-07-05 22:07 UTC, IgorMinar commented on aio/content/marketing/index.html
> +          <img src="assets/images/home/responsive-framework.svg" width="1295" height="795" alt="responsive framework">
These changes don't look right. The width/height should either not be specified or be specified exactly to the same dimensions that the stylesheet will set them to once downloaded.

If you look at the preview and inspect it you'll see that the width/height get overruled by dimensions set in  stylesheets because these attributes have low specificity. So in the end these numbers seem to have no real impact, except that if missing we could see a FOUC if the stylesheet is taking a long time to download.

2017-07-10 08:47 UTC, petebacondarwin commented
Resolved the conflict and force-pushed

2017-07-10 09:03 UTC, mary-poppins commented
You can preview 0910cb3 at https://pr17927-0910cb3.ngbuilds.io/.

2017-07-10 09:56 UTC, petebacondarwin approved these changes

2017-07-11 16:35 UTC, StephenFluin commented
I don't know if this is just an out of date preview or something, but the top image looks like it has too much space around it vs what is live?

![image](https://user-images.githubusercontent.com/165056/28079218-51ba4a20-661c-11e7-84c0-4416824087bc.png)

2017-07-11 16:49 UTC, petebacondarwin commented
You're right @StephenFluin - I think when I rebased and removed the `max-height` rule it broke the layout.

2017-09-11 07:07 UTC, petebacondarwin commented
Closing as this PR is stale and doesn't look like it is going to be updated.

2017-09-11 07:07 UTC, closed without merging