feat(animations): support disabling animations for sub elements
angular/angular pull request #17944
Opened 2017-07-05 21:47 UTC by matsko

2017-07-05 21:55 UTC, mhevery requested changes
Add API docs.

2017-07-05 21:55 UTC, mhevery commented on packages/core/test/animation/animation_integration_spec.ts
> +          const engine = TestBed.get(ɵAnimationEngine);
delete?

2017-07-05 22:02 UTC, mary-poppins commented
You can preview e2e86d9 at https://pr17944-e2e86d9.ngbuilds.io/.

2017-07-05 22:35 UTC, mary-poppins commented
You can preview 7c8a3a7 at https://pr17944-7c8a3a7.ngbuilds.io/.

2017-07-05 22:39 UTC, mhevery approved these changes

2017-07-05 22:40 UTC, mary-poppins commented
You can preview 0b1f720 at https://pr17944-0b1f720.ngbuilds.io/.

2017-07-06 18:12 UTC, mary-poppins commented
You can preview bed3e9f at https://pr17944-bed3e9f.ngbuilds.io/.

2017-07-07 18:42 UTC, matsko commented
Closed on favour of https://github.com/angular/angular/pull/17980

2017-07-07 18:42 UTC, closed without merging