fix(aio): remove title from callout
angular/angular pull request #17950
Opened 2017-07-06 05:22 UTC by sjtrimble

Per discussion - removed title from callout to remain consistent style-wise.

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2017-07-06 05:23 UTC, sjtrimble commented
@gkalpak Do you think we could add tests for this - to prevent titles (headers) in callouts and alerts?

2017-07-06 08:45 UTC, petebacondarwin commented
@sjtrimble we could add an HTML post-processor to the doc-gen to check for this.

2017-07-06 08:46 UTC, petebacondarwin commented on aio/content/guide/ts-to-js.md
> +  {@a getters-setters}
why move this anchor?

2017-07-07 19:55 UTC, sjtrimble commented on aio/content/guide/ts-to-js.md
> +  {@a getters-setters}
It affected the spacing -- styles weren't fully applying. This was the only way I was able to get it to look as intended.

2017-07-07 20:49 UTC, petebacondarwin commented on aio/content/guide/ts-to-js.md
> +  {@a getters-setters}
To be honest I don't know if we even need this anchor. The "Properties with getters and setters" will have its own anchor auto-attached. I can't find anywhere in the docs that links to `#getters-setters`.

2017-07-07 22:00 UTC, sjtrimble commented on aio/content/guide/ts-to-js.md
> +  {@a getters-setters}
I can remove ... was tempted to but wasn't quite sure as I'm not usually in the `.md` files

2017-07-10 08:23 UTC, petebacondarwin requested changes

2017-07-10 08:23 UTC, petebacondarwin commented on aio/content/guide/ts-to-js.md
> +  {@a getters-setters}
I moved the anchor back to the original place and it didn't appear to have any visual difference on Chrome, Safari or Firefox (all on OS/X). Are you sure this needs to move?

2017-07-14 11:22 UTC, petebacondarwin approved these changes

2017-07-14 11:29 UTC, mary-poppins commented
You can preview 397f19b at https://pr17950-397f19b.ngbuilds.io/.

2017-07-14 11:34 UTC, petebacondarwin commented
![screen shot 2017-07-14 at 12 34 43](https://user-images.githubusercontent.com/15655/28210741-d65967d6-6890-11e7-9e79-adbd171e8c53.png)

2017-07-15 14:33 UTC, Foxandxss approved these changes

2017-07-15 14:35 UTC, petebacondarwin commented
Thanks @Foxandxss

2017-07-15 14:35 UTC, merged