fix(upgrade): update touched state of NgModelController
angular/angular pull request #17964
Opened 2017-07-06 17:58 UTC by sshev

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
When downgrade component that implements `ControlValueAccessor` the downgraded `NgModelController` controller's touched state is not being updated from original ng2 component and always stays as "untouched". 

Issue Number: N/A

## What is the new behavior?
`NgModelController` properly reflects touched state of original ng2 component.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2017-07-07 09:52 UTC, gkalpak requested changes
Looks reasonable, but we need some tests for the new behavior. @kseamon, wdyt about the change?

2017-07-07 09:52 UTC, gkalpak commented on packages/upgrade/src/common/util.ts
> +      typeof component.registerOnTouched === 'function';
Isn't this a breaking change? Previously, it was possible to only implement `writeValue` and `registerOnChange` (i.e. not the whole `ControlValueAccessor` interface) and still get `ngModel` wired up. Now you need `registerOnTouched` as well.

2017-07-07 10:00 UTC, sshev commented on packages/upgrade/src/common/util.ts
> +      typeof component.registerOnTouched === 'function';
According to interface `registerOnChange()` property is required when implementing `ControlValueAccessor` 
https://github.com/angular/angular/blob/master/packages/forms/src/directives/control_value_accessor.ts#L30

2017-07-07 10:16 UTC, gkalpak commented on packages/upgrade/src/common/util.ts
> +      typeof component.registerOnTouched === 'function';
Yes, but one doesn't have to implement the interface. Duck-typing works just as well :smiley:

2017-07-07 11:18 UTC, sshev commented on packages/upgrade/src/common/util.ts
> +      typeof component.registerOnTouched === 'function';
you are right, I made `registerOnTouched` optional at https://github.com/angular/angular/pull/17964/commits/f93eb5553757da18fe1e1d14609944e9fbb1ae78

2017-07-07 11:33 UTC, kseamon commented
Looks reasonable to me, especially with the breaking change reverted.

2017-07-07 16:25 UTC, gkalpak commented
@sshev, looks much better now without the breaking change. We still need tests :grin:

2017-07-10 09:36 UTC, sshev commented
will add tests shortly

2017-07-11 11:50 UTC, sshev commented
@gkalpak I've added some tests

2017-07-14 13:13 UTC, gkalpak approved these changes

2017-07-14 13:31 UTC, gkalpak commented
Can you squash the commits and update the commit message to something like:

> feat(upgrade): propagate touched state of NgModelController

<sub>(Because I think this is more of a feature that a fix.)</sub>

2017-07-14 13:41 UTC, sshev commented
Done

2017-07-18 17:35 UTC, merged