feat(animations): support :increment and :decrement transition aliases
angular/angular pull request #17989
Opened 2017-07-07 16:11 UTC by matsko

2017-07-07 16:20 UTC, mary-poppins commented
You can preview 664f6e0 at https://pr17989-664f6e0.ngbuilds.io/.

2017-07-07 21:42 UTC, mhevery requested changes

2017-07-07 21:42 UTC, mhevery commented on packages/animations/src/animation_metadata.ts
> + *
turn it into `@example`

2017-07-07 21:43 UTC, mhevery approved these changes

2017-07-18 23:25 UTC, matsko commented
This now now unblocked because master===5x

2017-07-18 23:35 UTC, mary-poppins commented
You can preview 031fb95 at https://pr17989-031fb95.ngbuilds.io/.

2017-07-18 23:54 UTC, mary-poppins commented
You can preview 6c773a4 at https://pr17989-6c773a4.ngbuilds.io/.

2017-07-19 18:24 UTC, merged