fix(aio): fix tab animations on CodeTabsComponent
angular/angular pull request #18042
Opened 2017-07-10 21:39 UTC by gkalpak

In our attempt to remove the material ripple effect from tab labels, we were killing all `transform`-based animations on other `md-tab-group` elements, such as animating the content when entering/leaving. (This wasn't an issue on Chrome, because it didn't respect our `!important` flag.)

This commit fixes it by properly hiding the ripple effect (using a feature introduced in angular/material2@e4789c7) and allowing other animations to execute normally.

Fixes #17998.

2017-07-10 21:49 UTC, mary-poppins commented
You can preview d5db5e4 at https://pr18042-d5db5e4.ngbuilds.io/.

2017-07-11 14:19 UTC, petebacondarwin approved these changes

2017-07-11 14:22 UTC, petebacondarwin requested changes

2017-07-11 14:22 UTC, petebacondarwin commented on aio/src/app/embedded/code/code-tabs.component.spec.ts
> +import { NoopAnimationsModule } from "@angular/platform-browser/animations";
```
😱 😱    😱 😱 
   😱      😱 
😱       😱 
```

2017-07-11 15:00 UTC, gkalpak commented on aio/src/app/embedded/code/code-tabs.component.spec.ts
> +import { NoopAnimationsModule } from "@angular/platform-browser/animations";
VSCode auto-imports still need work 😛

2017-07-11 15:20 UTC, gkalpak commented on aio/src/app/embedded/code/code-tabs.component.spec.ts
> +import { NoopAnimationsModule } from "@angular/platform-browser/animations";
Fixed. PTAL

2017-07-11 15:29 UTC, mary-poppins commented
You can preview d5d3575 at https://pr18042-d5d3575.ngbuilds.io/.

2017-07-11 16:46 UTC, petebacondarwin approved these changes

2017-07-11 18:49 UTC, merged