feat(compiler): add representation of placeholders to xliff & xmb
angular/angular pull request #18075
Opened 2017-07-12 14:43 UTC by ocombe

## PR Type
What kind of change does this PR introduce?
```
[x] Feature
```

## What is the current behavior?
Xliff 2 uses `disp` attributes to represent the placeholders (interpolations/tags) content so that tools can display something when you're translating.
Xliff doesn't have this, and xmb outputs `INTERPOLATION` for interpolations instead of the actual interpolation value.

Issue Number: #17345

## What is the new behavior?
#### Xliff:
- added "disp" attribute on interpolation placeholders
- added "dispStart" and "dispEnd" attributes on start tag placeholders, we could just use "disp" instead since there is no spec for this, but I think that it's probably better to follow the same rules as xliff2

Note that we can add those attributes to xliff placeholders since it is valid to add any non-XLIFF attribute on `<x>` tags: http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#x

#### Xmb:
- replaced `INTERPOLATION` with the actual value of the interpolation in the `<ex>` tag of interpolation placeholders

## Does this PR introduce a breaking change?
```
[x] No
```
I don't think it is a breaking change to replace "INTERPOLATION" with the actual value of the interpolation for XMB since it is only used to display something in translation tools.

PS: @vicb I wasn't very inspired for the commit message, if you have a better idea...

2017-07-12 15:01 UTC, mary-poppins commented
You can preview d93562b at https://pr18075-d93562b.ngbuilds.io/.

2017-07-12 15:25 UTC, mary-poppins commented
You can preview a772d95 at https://pr18075-a772d95.ngbuilds.io/.

2017-07-13 08:33 UTC, mary-poppins commented
You can preview 174015b at https://pr18075-174015b.ngbuilds.io/.

2017-07-18 17:46 UTC, vicb commented on packages/compiler/src/i18n/serializers/xliff.ts
> +      return [new xml.Tag(_PLACEHOLDER_TAG, {id: ph.startName, ctype, disp: `<${ph.tag}/>`})];
is `disp` in XLIFF ? 
Seems it is not from the PR message -> if it is not, must be removed (together with `dispStart` and `dispEnd`

2017-07-18 17:56 UTC, vicb requested changes
please fix comments

2017-07-18 17:56 UTC, vicb commented on packages/compiler/src/i18n/serializers/xmb.ts
> +    const exTag = new xml.Tag(_EXEMPLE_TAG, {}, [new xml.Text(`{{${ph.value}}}` || '...')]);
`{{${ph.value}}}` || '...' ??

2017-07-18 17:56 UTC, vicb commented on packages/compiler/test/i18n/integration_xmb_xtb_spec.ts
> +        <ph name="ICU"><ex>{sex, select, m {...} f {...}}</ex></ph>
what if a message contains HTML ? (`<p>`)

2017-07-18 17:56 UTC, vicb commented on packages/compiler/test/i18n/integration_xmb_xtb_spec.ts
> +        <ph name="ICU"><ex>{sex, select, m {...} f {...}}</ex></ph>
Ok it will always be `{...}`.
I don't think it's very helpful but might be slightly better than what we have today

2017-07-18 20:47 UTC, ocombe commented on packages/compiler/src/i18n/serializers/xliff.ts
> +      return [new xml.Tag(_PLACEHOLDER_TAG, {id: ph.startName, ctype, disp: `<${ph.tag}/>`})];
It's not an official attribute, but there's no equivalent in xliff 1.2, and the spec says that we can add any non-xliff attribute. The idea here is to give more info for tools so that they can show something relevant where the PH is (see issue linked). By choosing the same name that we use in xliff2, it will be easy for tool to support this

2017-07-18 20:48 UTC, ocombe commented on packages/compiler/src/i18n/serializers/xmb.ts
> +    const exTag = new xml.Tag(_EXEMPLE_TAG, {}, [new xml.Text(`{{${ph.value}}}` || '...')]);
I've reused the same code that you added here: https://github.com/ocombe/angular/blob/174015bb3f97758cdbb27149cc36184d1e66155d/packages/compiler/src/i18n/serializers/xmb.ts#L163

2017-07-19 09:17 UTC, mary-poppins commented
You can preview 0e9f3bf at https://pr18075-0e9f3bf.ngbuilds.io/.

2017-07-19 16:46 UTC, vicb commented on packages/compiler/test/i18n/integration_xliff_spec.ts
> +        <source><x id="START_ITALIC_TEXT" ctype="x-i" dispStart="&lt;i&gt;" dispEnd="&lt;/i&gt;"/>with placeholders<x id="CLOSE_ITALIC_TEXT" ctype="x-i"/></source>
?

2017-07-19 19:52 UTC, mary-poppins commented
You can preview 7875127 at https://pr18075-7875127.ngbuilds.io/.

2017-07-19 21:20 UTC, vicb approved these changes

2017-07-20 08:21 UTC, ocombe commented
Can we remove the pr_action:cleanup and add the merge label instead?

2017-07-21 17:20 UTC, closed without merging