docs: rewrite 'Server Communication' on AIO to use HttpClient
angular/angular pull request #18079
Opened 2017-07-12 20:43 UTC by alxhub

2017-07-12 20:52 UTC, mary-poppins commented
You can preview c9527e6 at https://pr18079-c9527e6.ngbuilds.io/.

2017-07-12 23:12 UTC, mary-poppins commented
You can preview af18ed0 at https://pr18079-af18ed0.ngbuilds.io/.

2017-07-13 00:11 UTC, IgorMinar requested changes
For the first draft this look very good. I left comments throughout.

There are several things that I find missing in this guide, specifically coverage of:
- jsonp
- xsrf (if I'm not mistaken, we don't currently expose public api for parsing cookies, so we can't just say use interceptors for xsrf)
- submitting forms

2017-07-13 00:11 UTC, IgorMinar commented on aio/content/guide/http.md
> +#### Logging
I think especially the readers familiar with AngularJS and spring would be more familiar with "around interceptors" which is a term commonly used for interceptors that intercept both directions.

2017-07-13 12:44 UTC, kapunahelewong commented on aio/content/guide/http.md
> +# HTTP Fundamentals
Changed title in doc and in navigation.json to HttpClient.

2017-07-13 12:48 UTC, kapunahelewong commented on aio/content/guide/http.md
> +`@angular/common/http` provides a simplified API for HTTP functionality for use with Angular applications, building on top of the `XMLHttpRequest` interface exposed by browsers.
Added. Also edited line 5 to start with "With HttpClient".

2017-07-13 12:48 UTC, kapunahelewong commented on aio/content/guide/http.md
> +Before you can use the Angular HTTP APIs, you need to install the `HttpClientModule` which provides them. This can be done in your application module, and is only necessary once.
Done.

2017-07-13 12:55 UTC, kapunahelewong commented on aio/content/guide/http.md
> +    HttpClientModule,
Inside the doc it looked ok, but I reset it anyway and one of the invisible characters changed. I think I fixed it. Someone please correct me if I'm mistaken. Thanks!

2017-07-13 12:56 UTC, kapunahelewong commented on aio/content/guide/http.md
> +Once `HttpClientModule` is imported into your app module, `HttpClient` will be injectable into your components and services.
Fixed and changed from passive to active voice.

2017-07-13 12:57 UTC, kapunahelewong commented on aio/content/guide/http.md
> +    "Igor",
Changed to items and Item 1 and Item 2.

2017-07-13 13:00 UTC, kapunahelewong commented on aio/content/guide/http.md
> +That was easy!
Removed because I think we're taking out references like this.

2017-07-13 13:00 UTC, kapunahelewong commented on aio/content/guide/http.md
Changed to "straightforward".

2017-07-13 13:10 UTC, kapunahelewong commented on aio/content/guide/http.md
> +    err => {
Fixed. Invisible characters again.

2017-07-13 13:20 UTC, kapunahelewong commented on aio/content/guide/http.md
> +There are two types of errors that can occur. If the backend returns an unsuccessful response code (404, 500, etc), it gets returned as an error. Also, if something goes wrong client-side (like an ex
I'd like to change these from passive to active voice but don't know what the subjects are in the following:

"...it gets returned as an error." <-What is returning the error?
"...an exception gets thrown" <- What's throwing the exception? The RxJS operator?
"...an actual `Error` will be thrown." <-What's throwing the error?

@alxhub could you clarify for me and I'll update the copy? Thanks!

2017-07-13 13:45 UTC, kapunahelewong commented on aio/content/guide/http.md
> +  .retry(3)
Leaving this one to @alxhub. Not sure of the operator to import.

2017-07-13 13:59 UTC, kapunahelewong commented on aio/content/guide/http.md
> +#### Caution: Observables are cold
Changed to a callout, thought I think we are trying to minimize these.

2017-07-13 14:11 UTC, kapunahelewong commented on aio/content/guide/http.md
> +The `HttpHeaders` class is immutable, so every `.set()` returns a new instance with the changes applied.
Leaving to @alxhub

2017-07-13 14:14 UTC, kapunahelewong commented on aio/content/guide/http.md
> +A major feature of `@angular/common/http` is _interception_, the ability to declare interceptors which sit in between your application and the backend. When your application makes a request, it will
"...before being sent to the server...." 

I changed this to:

"When your application makes a request, interceptors transform it 
before sending it to the server, and the interceptors can transform the response on its way back before your application sees it."

But I'm not sure if the interceptors are what's sending the request. @alxhub can you make sure this has the right subject doing the action?

2017-07-13 14:16 UTC, kapunahelewong commented on aio/content/guide/http.md
> +To implement an interceptor, you declare a class that implements `HttpInterceptor`, which has a single `intercept` method. Here is a simple interceptor which does nothing but forward the request thro
Leaving to @alxhub

2017-07-13 14:25 UTC, kapunahelewong commented on aio/content/guide/http.md
> +Interceptors are required to deal with all `HttpEvent`s that a request may return. Many interceptors are only concerned with the outgoing request, though, and will simply return the event stream from
Changes this first sentence to: "All `HttpEvent`s that a request may return require interceptors." @alxhub does this still convey the meaning you intend? (Change is because of using active instead of passive voice.)

2017-07-13 14:39 UTC, kapunahelewong commented on aio/content/guide/http.md
> +Interceptors exist to examine and mutate outgoing requests and incoming responses. It may be surprising, then, to learn that the `HttpRequest` and `HttpResponse` classes are largely immutable.
Took it out and reworded it a little.

2017-07-13 14:40 UTC, kapunahelewong commented on aio/content/guide/http.md
> +There is one case where type safety cannot protect you or anyone else writing interceptors &mdash; the request body. It is invalid to mutate a request body within an interceptor, but this is not chec
Done.

2017-07-13 14:41 UTC, kapunahelewong commented on aio/content/guide/http.md
> +To safely make changes within an interceptor, make use of `HttpRequest`'s `.clone()` functionality.
Replaced. @alxhub fyi.

2017-07-13 14:42 UTC, kapunahelewong commented on aio/content/guide/http.md
> +##### Cloning
Done.

2017-07-13 14:43 UTC, kapunahelewong commented on aio/content/guide/http.md
> +#### Logging
Leaving for @alxhub. Not sure how to incorporate this.

2017-07-13 14:59 UTC, kapunahelewong commented on aio/content/guide/http.md
> +  // Make an HTTP GET request, and expect that it returns an object
Changed "returns" to "return" as this requires the subjunctive rather than the indicative. 

"expect that it return"

For the curious, this is the same construction as "Mom expects that you be home by 12".

2017-07-13 15:05 UTC, alxhub commented on aio/content/guide/http.md
> +    HttpClientModule,
Ahh, must've been a few tab characters in there.

2017-07-13 15:09 UTC, alxhub commented on aio/content/guide/http.md
> +There are two types of errors that can occur. If the backend returns an unsuccessful response code (404, 500, etc), it gets returned as an error. Also, if something goes wrong client-side (like an ex
* In the first and third case it's the `XhrBackend` which is the bit of the API that actually wraps `XMLHttpRequest` which throws the error. The user doesn't need to be familiar with `XhrBackend` though - as far as they're concerned, the error comes out of the `HttpClient` API.

* In the second case, the "exception" (maybe we should use "error" here too for consistency?) is thrown by some user-added piece of logic along the way. For example:

```javascript
http.get('/foo').map(body => body.foo.bar).subscribe(...)
```

The Observable will emit an error if `body.foo` is null or undefined, since it can't be dereferenced to look up `.bar` in that case.

2017-07-13 15:10 UTC, alxhub commented on aio/content/guide/http.md
> +  .retry(3)
```javascript
import 'rxjs/add/operator/retry';
```

2017-07-13 15:12 UTC, alxhub commented on aio/content/guide/http.md
> +The `HttpHeaders` class is immutable, so every `.set()` returns a new instance with the changes applied.
```javascript
headers: new HttpHeaders().set('Authorization', 'my-auth-token').set('Cache-Control', 'no-cache'),
```

2017-07-13 15:14 UTC, kapunahelewong commented on aio/content/guide/http.md
> +If you need to respond to duplicate requests in your test, use the `.match()` API instead of `.expectOne()`, which takes the same arguments but returns an array of matching requests. Once returned, t
This sentence:

" Once returned, these requests are removed from future matching and are your responsibility to verify and flush." 

What returns the requests and what removes them from future matching? I can update if you can fill me in, @alxhub.

2017-07-13 15:16 UTC, alxhub commented on aio/content/guide/http.md
> +A major feature of `@angular/common/http` is _interception_, the ability to declare interceptors which sit in between your application and the backend. When your application makes a request, it will
In a technical sense, yes, they are.

An understanding of "the request passes through each interceptor before being sent to the server, and the response goes through them on the way back" is sufficient to use interceptors for most use cases.

A more technical understanding is that each interceptor makes a decision whether to continue passing the (possibly modified) request down the chain, eventually reaching the backend, or to break out and handle the request itself. An example of this is my caching interceptor, which in the case that the request exists in cache chooses not to continue the chain and returns the cached response instead.

2017-07-13 15:17 UTC, alxhub commented on aio/content/guide/http.md
> +To implement an interceptor, you declare a class that implements `HttpInterceptor`, which has a single `intercept` method. Here is a simple interceptor which does nothing but forward the request thro
I agree.

```javascript
export class LoggingInterceptor implements HttpInterceptor {
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    console.log(`Outgoing ${req.method} request for ${req.urlWithParams}`);
    return next.handle(req);
  }
}

2017-07-13 15:21 UTC, alxhub commented on aio/content/guide/http.md
> +Interceptors are required to deal with all `HttpEvent`s that a request may return. Many interceptors are only concerned with the outgoing request, though, and will simply return the event stream from
Are you talking about this sentence? 
> Interceptors are required to deal with all `HttpEvent`s that a request may return.

In that case no, that changes the meaning.

What I was trying to convey here is that an interceptor **must** pass through all events that it does not understand or intend to modify. It's not acceptable to filter out events it didn't expect to process.

2017-07-13 15:23 UTC, alxhub commented on aio/content/guide/http.md
> +To safely make changes within an interceptor, make use of `HttpRequest`'s `.clone()` functionality.
The statement should actually be stronger - the developer is responsible for copying the request body themselves, mutating the copy, and then using `.clone()` to copy the request and set the new body.

2017-07-13 15:27 UTC, alxhub commented on aio/content/guide/http.md
> +#### Logging
Maybe something like
> You may know this pattern as "around interceptors" in other frameworks.

2017-07-13 15:28 UTC, alxhub commented on aio/content/guide/http.md
> +  // Make an HTTP GET request, and expect that it returns an object
Whoops :)

2017-07-13 15:44 UTC, mary-poppins commented
You can preview 7bec24d at https://pr18079-7bec24d.ngbuilds.io/.

2017-07-13 15:48 UTC, kapunahelewong commented on aio/content/guide/http.md
> +There are two types of errors that can occur. If the backend returns an unsuccessful response code (404, 500, etc), it gets returned as an error. Also, if something goes wrong client-side (like an ex
Per conversation with @alxhub I'm going to work on this paragraph in a separate PR in the interest of time. The use of the passive voice here might actually be helpful in making the concept succinct for the time being. The subjects of the actions reveal more info than the dev just learning the ropes might need at this point. I have to find a way to switch to active while maintaining the brevity and not getting overly wordy.

2017-07-13 15:52 UTC, kapunahelewong commented on aio/content/guide/http.md
> +  .retry(3)
Added. Thanks!

2017-07-13 15:56 UTC, kapunahelewong commented on aio/content/guide/http.md
> +### Reading the full response
Moved. @alxhub can you check me here?

2017-07-13 15:57 UTC, kapunahelewong commented on aio/content/guide/http.md
> +A major feature of `@angular/common/http` is _interception_, the ability to declare interceptors which sit in between your application and the backend. When your application makes a request, it will
Ah I see. Thank you!

2017-07-13 16:04 UTC, kapunahelewong commented on aio/content/guide/http.md
> +Interceptors are required to deal with all `HttpEvent`s that a request may return. Many interceptors are only concerned with the outgoing request, though, and will simply return the event stream from
Yes, I meant "changed" not "changes".

Updated.

2017-07-13 16:05 UTC, kapunahelewong commented on aio/content/guide/http.md
> +##### Providing your interceptor
Swapped with Events.

2017-07-13 16:07 UTC, kapunahelewong commented on aio/content/guide/http.md
> +To safely make changes within an interceptor, make use of `HttpRequest`'s `.clone()` functionality.
Changed to this: 

"If you have a need to mutate the request body, you need to copy the request body, mutate the copy, and then use `clone()` to copy the request and set the new body."

2017-07-13 16:19 UTC, mary-poppins commented
You can preview 1a8be3e at https://pr18079-1a8be3e.ngbuilds.io/.

2017-07-13 17:33 UTC, mary-poppins commented
You can preview d3ed467 at https://pr18079-d3ed467.ngbuilds.io/.

2017-07-13 17:43 UTC, mary-poppins commented
You can preview 641c001 at https://pr18079-641c001.ngbuilds.io/.

2017-07-13 17:50 UTC, mary-poppins commented
You can preview 07183c4 at https://pr18079-07183c4.ngbuilds.io/.

2017-07-13 18:06 UTC, mary-poppins commented
You can preview 51df647 at https://pr18079-51df647.ngbuilds.io/.

2017-07-13 22:22 UTC, merged