fix(upgrade): ensure downgraded components are created in the Angular zone
angular/angular pull request #18209
Opened 2017-07-18 18:01 UTC by gkalpak

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

When using `downgradeModule()` from `@angular/upgrade/static`, the Angular component is not created inside the Angular zone.

Issue Number: N/A

## What is the new behavior?
The Angular component is created inside the Angular zone.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2017-07-18 18:35 UTC, mary-poppins commented
You can preview 5affe94 at https://pr18209-5affe94.ngbuilds.io/.

2017-07-18 19:02 UTC, mary-poppins commented
You can preview 68affdc at https://pr18209-68affdc.ngbuilds.io/.

2017-07-18 20:36 UTC, mhevery requested changes
I think we have to do the same thing for when a property changes in the AngularJS which than triggers a CD in Angular. We have to make sure that the CD is in `NgZone` as well.

2017-07-18 20:36 UTC, mhevery commented on packages/upgrade/src/common/downgrade_component.ts
> +            const ngZone = injector.get<NgZone>(NgZone);
Can we cache the `ngZone` I think the cost of lookup is similar to entering zone.

2017-07-18 23:40 UTC, mhevery requested changes

2017-07-18 23:40 UTC, mhevery commented on packages/upgrade/src/common/util.ts
> +let ngZone: NgZone;
I don't think this is OK. If you had more than one Angular app on a single page which is sharing code than they will also share the NgZone instance which is wrong. This has to be component specific.

Can we store the instance with downgradeComponent and pass it into the adapter?

2017-07-19 17:03 UTC, mary-poppins commented
You can preview 6f7ab26 at https://pr18209-6f7ab26.ngbuilds.io/.

2017-07-19 17:16 UTC, mary-poppins commented
You can preview f54f582 at https://pr18209-f54f582.ngbuilds.io/.

2017-07-19 17:39 UTC, mary-poppins commented
You can preview 015db04 at https://pr18209-015db04.ngbuilds.io/.

2017-07-19 17:50 UTC, mary-poppins commented
You can preview 478d09d at https://pr18209-478d09d.ngbuilds.io/.

2017-07-19 20:57 UTC, gkalpak commented on packages/upgrade/src/common/util.ts
> +  return () => NgZone.isInAngularZone() ? fn() : ngZone.run(fn);
This seems to be causing some `$digest is already in progress` errors, when used with the UpgradeModule :confused:

2017-07-19 21:21 UTC, gkalpak commented on packages/upgrade/src/common/util.ts
> +  return () => NgZone.isInAngularZone() ? fn() : ngZone.run(fn);
The problem seems to be the following:
- `$digest` is called outside the Angular zone.
- As part of the digest, `wrapInNgZone()` is called (e.g. [here][1]).
- Since we are outside the Angular zone, [wrapInNgZone()][2] calls `ngZone.run(...)`.
- Once that completes, `onMicrotaskEmpty()` will be triggered.
- Which in turn, [invokes `$digest()`][3].
- Which results in a `$digest already in progress` errors.

[1]: https://github.com/gkalpak/angular/blob/478d09dc63a587e4044584d1ac0ba9fc19efd9bd/packages/upgrade/src/common/downgrade_component_adapter.ts#L141
[2]: https://github.com/gkalpak/angular/blob/478d09dc63a587e4044584d1ac0ba9fc19efd9bd/packages/upgrade/src/common/util.ts#L61
[3]: https://github.com/gkalpak/angular/blob/478d09dc63a587e4044584d1ac0ba9fc19efd9bd/packages/upgrade/src/static/upgrade_module.ts#L249

2017-07-19 21:56 UTC, mhevery commented on packages/upgrade/src/common/util.ts
> +  return () => NgZone.isInAngularZone() ? fn() : ngZone.run(fn);
discussed offline, and have resolution.

2017-07-19 22:00 UTC, mhevery requested changes

2017-07-19 22:00 UTC, mhevery commented on packages/upgrade/src/common/downgrade_component_adapter.ts
> +      this.componentScope.$watch(wrapInNgZone(detectChanges, this.ngZone));
There needs to be an `else` block here which does something like this:
```
this.applicationRef.attachView(this.componentRef.hostView);
```

Also when the component is removed it should be removed from the `ApplicationRef`

2017-07-19 22:00 UTC, mhevery commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +                     'ng2', downgradeComponent({component: Ng2Component, propagateDigest: false}))
Add a tests which shows that subsequent changes do not trigger the CD.

1) create a template with a button which ups the count
2) click the button
3) observe that the template has been updated with the count.

As of right now the click causes `ApplicationRef.tick` but because the component is not in the ApllicationRef its CD does not get called.

2017-07-19 22:40 UTC, mary-poppins commented
You can preview 3fb7845 at https://pr18209-3fb7845.ngbuilds.io/.

2017-07-20 13:43 UTC, mary-poppins commented
You can preview 3f7d954 at https://pr18209-3f7d954.ngbuilds.io/.

2017-07-20 15:58 UTC, mary-poppins commented
You can preview 35813d6 at https://pr18209-35813d6.ngbuilds.io/.

2017-07-20 16:31 UTC, mhevery commented on packages/upgrade/src/common/downgrade_component_adapter.ts
> +                                   detectChanges();
I think it would be better if `detectChanges()` moved to `wrappCallback`, since you can determine it once and always use the same roles.

We have these states:
- 'propagetDigest: false && boostrapInNgZone: false`:  need explicit `detectChanges();` using `NgZone.run`
- 'propagetDigest: false && boostrapInNgZone: true`:  need explicit `detectChanges();`
- 'propagetDigest: true && boostrapInNgZone: false`:  `detectChanges()` no needed since they will be passed by `$watch`
- 'propagetDigest: true && boostrapInNgZone: true`: `detectChanges()` no needed since they will be passed by `$watch`  using `NgZone.run`

I think it would be best of all of theses states were captured in `wrapCallback` rather than a mix of `wrapCallback` and if statements.

2017-07-20 16:31 UTC, mhevery commented on packages/upgrade/src/static/upgrade_module.ts
> +                  (injector: Injector) => ({injector, bootstrappedInNgZone: true})
I think it would be easier to reason about the code if `boostrapInNgZone` would be renamed to `needsNgZone`. In general you want to have positive variables otherwise you get double negative in `if (!negativeVar)`

2017-07-20 17:00 UTC, mary-poppins commented
You can preview 55399f7 at https://pr18209-55399f7.ngbuilds.io/.

2017-07-20 19:50 UTC, gkalpak commented on packages/upgrade/src/common/downgrade_component_adapter.ts
> +      this.componentScope.$watch(wrapInNgZone(detectChanges, this.ngZone));
If I understand correctly, whether we need to manually `attachView` does not depend on `propagateDigest`, but rather on whether we use `downgradeModule()` or not, right?

<sub>(Although primarily designed for `downgradeModule()`, there is nothing stopping you from using `propagateDigest: false` with "normal" ngUpgrade.)</sub>

2017-07-20 19:54 UTC, gkalpak commented on packages/upgrade/src/common/downgrade_component_adapter.ts
> +                                   detectChanges();
I am not sure I understand what you are suggesting 😕

2017-07-20 20:24 UTC, mary-poppins commented
You can preview c51c59a at https://pr18209-c51c59a.ngbuilds.io/.

2017-07-20 20:28 UTC, gkalpak commented on packages/upgrade/src/common/downgrade_component_adapter.ts
> +    if (needsNgZone) {
I am essentially piggybacking on `needsNgZone` as an indication of whether this is a downgraded module (via `downgradeModule()`) or a full `UgradeModule`.

(Looking at it again, it should probably be `if (needsNgZone || !propagteDigest)`.)

2017-07-20 20:37 UTC, mary-poppins commented
You can preview 3472c8f at https://pr18209-3472c8f.ngbuilds.io/.

2017-07-20 20:47 UTC, mhevery approved these changes

2017-07-20 20:47 UTC, mhevery commented on packages/upgrade/src/common/downgrade_component_adapter.ts
> +    if (needsNgZone) {
yes, it should be `if (needsNgZone || !propagteDigest)`

2017-07-20 21:51 UTC, closed without merging

2017-10-02 17:36 UTC, petebacondarwin commented on packages/upgrade/src/common/downgrade_component_adapter.ts
> +    if (needsNgZone) {
`propagte` LOL