Fix intl api 10809
angular/angular pull request #18284
Opened 2017-07-21 18:14 UTC by ocombe

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[x] Feature
```

## What is the current behavior?
We need the intl API for i18n pipes

Issue Number: #10809, #9524, #7008, #9324, #7590, #6724, #3429, #17576, #17478, #17319, #17200, #16838, #16624, #16625, #16591, #14131, #12632, #11376, #11187

## What is the new behavior?
We don't need the intl API anymore, we extract and use data from CLDR instead.

### Date pipe:
- new formats (breaking change), see [comparative document](https://docs.google.com/spreadsheets/d/12iygt-_cakNP1VO7MV9g4lq9NsxVWG4tSfc98HpHb0k/edit?usp=sharing)
- new optional parameter: `timezone` that lets you specify the timezone for a date (it will shift the date values based on the locale timezone so that you see it as it was from this other timezone).
- new optional parameter: `locale` that lets you use a specific locale for this pipe (instead of using the default `LOCALE_ID`)
 
### Plural pipe:
- new optional parameter: `locale` that lets you use a specific locale for this pipe (instead of using the default `LOCALE_ID`)
 
### Decimal pipe:
- new optional parameter: `locale` that lets you use a specific locale for this pipe (instead of using the default `LOCALE_ID`)

### Percent pipe:
- new optional parameter: `locale` that lets you use a specific locale for this pipe (instead of using the default `LOCALE_ID`)
 
### Currency pipe:
- the parameter `symbolDisplay` is no longer a boolean (it still works with a boolean, but it prints a warning to let you know that it changed), it’s now taking the values `code`, `symbol`, or `symbol-narrow` (the default is still code) which gives you access to more options for to show your currencies (e.g. the canadian dollar with the code `CAD` has the symbol `CA$` and the symbol-narrow `$`).
- new optional parameter: `locale` that lets you use a specific locale for this pipe (instead of using the default `LOCALE_ID`)

## Does this PR introduce a breaking change?
```
[x] Yes
```

All i18n pipes have been updated to not require the intl API anymore. Some results might vary, see the document to update from v4 to v5 for more information.

## TODO
- write a document to update from v4 to v5
- decide if we make the old pipes opt-in or opt-out
- create an access point from @angular/common/i18n that lets you import the locale that you want (need @IgorMinar's help for that)

2017-07-21 18:23 UTC, mary-poppins commented
You can preview 38d3eed at https://pr18284-38d3eed.ngbuilds.io/.

2017-07-21 18:39 UTC, vicb commented on tools/gulp-tasks/cldr/extract.js
> +  if(dayPeriodsFormat !== dayPeriodsStandalone) {
add comment on dedup

2017-07-21 23:08 UTC, vicb commented on packages/common/src/i18n/localization.ts
> +  const normalizedLocale = locale.toLowerCase().replace(new RegExp('_', 'g'), '-');
nit: `new RegExp('_', 'g')` -> `/-/g`

2017-07-21 23:12 UTC, vicb commented on packages/common/src/i18n/localization.ts
> +  const currentLocale = getNormalizedLocale(locale);
currentLocale -> normalizedLocale

2017-07-21 23:17 UTC, vicb commented on packages/platform-browser/test/browser_util_spec.ts
> -        expect(bd.isOldChrome).toBe(browser['isOldChrome']);
why this change ?

2017-07-24 07:50 UTC, ocombe commented on packages/platform-browser/test/browser_util_spec.ts
> -        expect(bd.isOldChrome).toBe(browser['isOldChrome']);
`isOldChrome` is only used by intl api, when I first did the PR, I removed the old pipes and the tests for them. But then I moved them as deprecated pipes instead, and forgot to revert this change. Doing it now.

2017-07-24 08:27 UTC, mary-poppins commented
You can preview 1d5eed7 at https://pr18284-1d5eed7.ngbuilds.io/.

2017-07-24 09:26 UTC, mary-poppins commented
You can preview 1053613 at https://pr18284-1053613.ngbuilds.io/.

2017-07-25 19:42 UTC, mary-poppins commented
You can preview d513368 at https://pr18284-d513368.ngbuilds.io/.

2017-07-25 20:17 UTC, mary-poppins commented
You can preview c33247f at https://pr18284-c33247f.ngbuilds.io/.

2017-07-25 20:49 UTC, mary-poppins commented
You can preview 052a61a at https://pr18284-052a61a.ngbuilds.io/.

2017-07-25 23:40 UTC, vicb commented on packages/common/i18n/full/locale_af-NA.ts
> +const dpF = {
change `dpF

2017-07-25 23:43 UTC, vicb commented on tools/gulp-tasks/cldr/extract.js
> +// This is generated code DO NOT MODIFY
THIS CODE IS GENERATED - DO NOT MODIFY

2017-07-25 23:49 UTC, vicb commented on packages/common/i18n/full/locale_af-NA.ts
> +format.narrow = {...format.narrow, ...dpF.narrow};
Thoughts:
- I think we can remove all of the `{..., ...}`,
- I think we can also remove the need to import the std objects and merge the full object

Because we are going to use an API to access the data (which goal is to abstract the storage format).

Also the `registerLocaleData(...)` could help here.

2017-07-25 23:51 UTC, vicb commented on tools/gulp-tasks/cldr/extract.js
> +    settings: ${getNumberSettings(localeData)}
do we need a nested key here and below ?

2017-07-25 23:51 UTC, vicb commented on tools/gulp-tasks/cldr/extract.js
> +  if (dpF === dpStd) {
add a comment explaining what you do pls

2017-07-25 23:52 UTC, vicb commented on tools/gulp-tasks/cldr/extract.js
> +const format = NgLocale${toPascalCase(locale)}.dateTime.translations.dayPeriods.format;
There is probably no need to duplicate this logic as many time as we have locales

2017-07-25 23:53 UTC, vicb commented on tools/gulp-tasks/cldr/extract.js
> +    narrow: objectValues(dayNames.format.narrow),
Have you tried to generate arrays instead of obj ?
What is the diff in size ?

2017-07-25 23:57 UTC, vicb commented on packages/common/i18n/full/locale_ar-QA.ts
> +/**
Idea: I donc speak `ar` but the files look really similar for different regions (the `QA` part). Is there any check in place to make sure we do not duplicate the same data multiple times ?

2017-07-26 00:00 UTC, vicb commented on packages/common/i18n/locale_fr-BJ.ts
> +import {LOCALE_DATA, NgLocale, Plural} from '@angular/common';
meme remarque encore ici: probablement beaucoup de chose en commun avec `fr-*` (sauf currency et peut etre numbers). Would be NICE to check what we can factor.

2017-07-26 00:01 UTC, vicb commented on packages/common/src/i18n/currencies.ts
> +  'ADP': {symbol: 'ADP'},
An array would make sense here instead of an obj.

2017-07-26 00:02 UTC, vicb commented on packages/common/i18n/tsconfig-build.json
> +//    "rootDir": ".",
DEBUG ?

2017-07-26 00:03 UTC, vicb commented on packages/common/src/i18n/ng_locale.ts
> +// Day    E	      c
??

2017-07-26 05:27 UTC, ocombe commented on tools/gulp-tasks/cldr/extract.js
> +    settings: ${getNumberSettings(localeData)}
not yet, just thinking about future things that we might add

2017-07-26 05:28 UTC, ocombe commented on packages/common/i18n/full/locale_ar-QA.ts
> +/**
Not between different locales no, but it doesn't really matter since people will only import one of them, not all

2017-07-26 10:33 UTC, ocombe commented on packages/common/src/i18n/currencies.ts
> +  'ADP': {symbol: 'ADP'},
👍 Just saved 8.5ko minified by optimizing this file!

2017-07-26 16:02 UTC, vicb commented on packages/common/i18n/full/locale_ar-QA.ts
> +/**
It will prevent devs to have to buy a new SSD only to npm install Angular. 
The check is easy enough. Please git it a try to see how much we can save.

2017-07-26 23:16 UTC, vicb commented on tools/gulp-tasks/cldr/extract.js
> +      rules.push(dayPeriodRules[key]);
`const rules = keys.map();`

2017-07-26 23:21 UTC, vicb commented on packages/common/src/i18n/locale_en.ts
> +      [ [ [ [ 'a', 'p' ], [ 'AM', 'PM' ], [ 'AM', 'PM' ] ],
Do we need that much nested arrays ?

2017-07-26 23:24 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> +    pipe: Type<any>, value: number | string, style: NumberFormatStyle, format: string,
pipe ???

2017-07-26 23:24 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> +    throw invalidPipeArgumentError(pipe, number);
pipe ???

2017-07-26 23:24 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> +        throw new Error(`${digitsInfo} is not a valid digit info for number pipes`);
pipes

2017-07-26 23:26 UTC, vicb commented on packages/common/src/i18n/locale_api.ts
> +const FORMS = ['format', 'standalone'];
any reason not to use enums ?

2017-07-26 23:28 UTC, vicb commented on packages/common/src/i18n/locale_api.ts
> +export class I18nApi {
Thoughts:
Does it really makes sense to make it a class ?

2017-07-26 23:29 UTC, vicb commented on packages/common/src/i18n/locale_api.ts
> +    const amPm = this.data[1][0][0];
`[1][0][0]`-> constants

2017-07-26 23:31 UTC, vicb commented on packages/common/src/i18n/locale_api.ts
> +    return data[TRANSLATION_WIDTHS.indexOf(width)];
-> with numeric enums you should be able to remove `indexOf`

2017-07-26 23:33 UTC, vicb commented on packages/common/src/pipes/number_pipe.ts
> +  constructor(@Inject(LOCALE_ID) private locale: string) {}
ping

2017-07-26 23:33 UTC, vicb commented on packages/common/src/pipes/number_pipe.ts
> +  constructor(@Inject(LOCALE_ID) private locale: string) {}
ping

2017-07-27 09:03 UTC, ocombe commented on packages/common/src/i18n/locale_api.ts
> +export class I18nApi {
Well it uses the constructor to get the data. This way you don't need to know how to get the data (from `LOCALE_DATA`), otherwise it means that you need to pass the locale data to each function, which means that you need to get them in each pipe / service that will use this api.

2017-07-27 09:03 UTC, ocombe commented on packages/common/src/i18n/locale_api.ts
> +const FORMS = ['format', 'standalone'];
no, good idea

2017-07-27 12:52 UTC, ocombe commented on packages/common/src/i18n/locale_en.ts
> +      [ [ [ [ 'a', 'p' ], [ 'AM', 'PM' ], [ 'AM', 'PM' ] ],
I'll try to remove some of them

2017-07-27 16:04 UTC, mary-poppins commented
You can preview 5940f28 at https://pr18284-5940f28.ngbuilds.io/.

2017-07-27 18:30 UTC, vicb commented on packages/common/src/common_module.ts
> + * @deprecated
`@deprecated` -> from when

2017-07-27 18:34 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +export function formatDatePattern(
api as a class again - to discuss

2017-07-27 18:39 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> +    value: number | string, style: NumberFormatStyle, format: string, api: LocaleDataApi,
- api again to discuss,
- argument order is not consistent with the date counterpart

2017-07-27 18:40 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> +  const patternParts = format.split(PATTERN_SEP), positive = patternParts[0],
we don't use coma in the CS. 
Use multiple const

2017-07-27 18:44 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +  firstDayOfWeek(): number { return this.data[8]; }
We should return an enum `enum Days { Sunday = 0, ...}`

2017-07-27 18:45 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +  dateFormat(width: FormatWidth): string { return this.data[10][width]; }
`this.data[10]` -> pls use constants

2017-07-27 18:45 UTC, mary-poppins commented
You can preview f2d1c45 at https://pr18284-f2d1c45.ngbuilds.io/.

2017-07-27 18:48 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +  let res, i = index;
- do not use `,`
- a `for` loop might be clearer
- `!== undefined` would be be better (and does what the function name implies)

2017-07-27 18:50 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +  const specialPatterns: {[key: string]: string} = {
- name = "namedPatterns" ?
- it should probably not be a local variable (re-created each time the fn is called)
- it should probably not be an object (we don't want to compute all the value each time we init the obj)
- same comment for below

2017-07-27 18:52 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +  return parseInt(str, 10);
do we really need that ? and to export that ?

2017-07-27 18:53 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +      value = 12;
what is that ?

2017-07-27 18:57 UTC, vicb commented on packages/common/src/pipes/date_pipe.ts
> +export function isBlank(obj: any): boolean {
pipes should not export utils function

2017-07-27 19:13 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +  return function(date: Date, api: LocaleDataApi): string {
breakdown to improve readability:

```ts
return function((...) {
  part = getDatePart(...);
  // offset black magic
  return padNumber(...);
}

----

function getDatePart {
  switch {
    case a : return A;
    case b: return B;
 }

}

```

2017-07-27 19:14 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +    switch (name) {
same comment -> same refactoring as above

2017-07-27 19:17 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +            padNumber(Math[zone > 0 ? 'floor' : 'ceil'](zone / 60), 2, minusSign) +
please use `zone > 0 ? Math.floor(...) : ...` better for minification & static analysis.

2017-07-27 19:18 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +          // TODO(ocombe): support optional seconds field, if there really is a use case
`if there really is a use case` -> remove the TODO for now

2017-07-27 19:20 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +  // 0 = index of January
use a constant instead of number + comment ?

2017-07-27 19:23 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +const DATE_FORMATS: {[format: string]: DateFormatter} = {
What about computing this lazily ?

2017-07-27 19:27 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +    let amPm = firstDefined([this.data[1], this.data[2]], formStyle);
const

2017-07-27 19:27 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +    let months = firstDefined([this.data[3], this.data[4]], formStyle);
const

2017-07-27 19:27 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +  weekEndRange(): [number, number] { return this.data[9]; }
same thing -> enum

2017-07-27 19:29 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +   * There are four basic date formats.
It's good to have API docs but reading this I have no clue what the method returns ?

replace `full` with `FormatWidth.full`, ... ?

2017-07-27 19:35 UTC, vicb commented on packages/common/src/pipes/date_pipe.ts
> + * - this pipe only contains en-US locale data by default. You have to import data for other locales
`this pipe only contains en-US` -> rephrase

2017-07-27 19:38 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> +  error: string | null
should probably be `error?:string` - same for `str` ?

2017-07-27 19:39 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> +  if (value == null) return res;
should it be an error ? or fix the param types ?

2017-07-27 19:44 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> +  number = typeof value === 'string' && isNumeric(value) ? +value : value as number;
`number = value as number;` is weird when value is not a number.

refactor 
```
if (value is numeric string) {
  value = +value;
} 
if (typeof value !== 'number') {
  return ...;
}
// TS should infer that value is a number from here

```


```

2017-07-27 20:36 UTC, vicb commented
There is a circular dep (check Travis):

```
Found circular dependencies!
[ [ '@angular/common/src/i18n/localization',
    '@angular/common/src/i18n/locale_data_api' ] ]
```

2017-07-27 20:40 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +  dateFormat(width: FormatWidth): string { return this.data[10][width]; }
Constant for "10" or for "this.data[10]" ?
Something like `this.data[DATE_FORMAT]` where `DATE_FORMAT = 10` ? I could even use an enum here actually

2017-07-27 20:42 UTC, ocombe commented on packages/common/src/i18n/format_date.ts
> +  return parseInt(str, 10);
It's only exported because it's used in multiple internal files, but it stays internal. Using this function probably gains a bit of space in the final bundle? It was like this in angularjs, I don't mind replacing by parseInt everywhere it is used, if there is a point to it?

2017-07-27 20:43 UTC, ocombe commented on packages/common/src/i18n/format_date.ts
> +      value = 12;
I explained in the previous PR, but it disappeared.
It's for AM/PM --> 00h00 = 12 am (at least that's how I understand it).

2017-07-27 20:46 UTC, ocombe commented on packages/common/src/i18n/format_date.ts
> +const DATE_FORMATS: {[format: string]: DateFormatter} = {
Do you mean only creating "DATE_FORMATS" the first time we need it? If you want, I'm not sure about the gain, we probably want the date pipe to be as fast as possible when it runs since it's synchronous, but we also compute so many things at bootstrap that removing this from the critical path might be better, especially if we never use the date pipe.

2017-07-27 20:47 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +   * There are four basic date formats.
good point, I'll add example of the returned data

2017-07-27 20:57 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +      value = 12;
> this comes from angularjs
This is not a good reason to introduce a bug.

This is probably missing `name === DateType.Hours &&` (& please also fix angular.js)

2017-07-27 20:59 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +const DATE_FORMATS: {[format: string]: DateFormatter} = {
creating `DATE_FORMATS.[format]` - additional benefit is that most apps probably only need a small subset

2017-07-27 21:01 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +   * There are four basic date formats.
>  I'll add example of the returned data

I don't think that much is missing.

But API docs *should* start with a sentence describing what the method/function/class does. This is missing here.

2017-07-27 21:01 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +  dateFormat(width: FormatWidth): string { return this.data[10][width]; }
10

2017-07-27 21:04 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +  return parseInt(str, 10);
the points are that:
- there is no reason why `format_date` should export a `toInt`, who would look for it there ?
- closure takes care of optimizing the size (much better than any other tricks)

2017-07-27 21:37 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +  // Day in Week narrow (Su-Sa)
typo (not narrow).

Also with enum a single comment on the group might be enough ? (ie `// Day in week`)

2017-07-28 07:53 UTC, ocombe commented on packages/common/src/i18n/format_date.ts
> +  return parseInt(str, 10);
Most people don't use closure, but I guess it's the same with uglify & co

2017-07-28 08:52 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +  let res, i = index;
Actually `!== undefined` was necessary, otherwise we could have an error when res is "" or 0 for example. Good catch.

2017-07-28 09:32 UTC, ocombe commented on packages/common/src/i18n/format_date.ts
> +      value = 12;
Well the offset argument is only used for hours in AM/PM , so there is no need to fix angularjs (it's not like they are going to change the date pipe), but I'll add a check here just in case

2017-07-28 09:37 UTC, ocombe commented on packages/common/src/pipes/date_pipe.ts
> +export function isBlank(obj: any): boolean {
I only export it because it's also used in the deprecated pipe and I wanted to remove the duplicated code, do you prefer to have the same function in both pipes?

2017-07-28 14:00 UTC, ocombe commented on packages/common/src/i18n/format_number.ts
> +  error: string | null
str should as least be `string | null` because the number pipes can return `string | null`, not undefined

2017-07-28 18:15 UTC, mary-poppins commented
You can preview 101e17d at https://pr18284-101e17d.ngbuilds.io/.

2017-07-28 18:19 UTC, mary-poppins commented
You can preview a4d4596 at https://pr18284-a4d4596.ngbuilds.io/.

2017-07-28 18:25 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +    case DateType.FullYear:
check the former comment:

```
case DateType.Month:
     return date.getMonth();
```

-> `getDartPart()` is expected to return a date part. Handle offset at calling site.

Throw on case default.

2017-07-28 18:27 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +  return new Date(year, 0, ((firstDayOfYear <= THURSDAY) ? 5 : 12) - firstDayOfYear);
5 ? 12 ?
-> THURSDAY + 1 / THURSDAY + 1 + 7

2017-07-28 18:29 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +      break;
default: return null;

2017-07-28 18:29 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +  if (formatter) {
remove the if

2017-07-28 18:30 UTC, vicb commented on packages/common/src/i18n/format_number.ts
>    str: string | null,
when/why null ?

2017-07-28 18:31 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +  Sunday,
we want to be explicit with day index, don't we (check my former comment)

2017-07-28 18:31 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +  LocaleId,
Should be the same here ?

2017-07-28 18:33 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +  return res !;
why `!` here ?

2017-07-28 18:34 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +    res = data[i];
would be more clear to return early if not undefined inside the for, no ?

2017-07-28 18:36 UTC, vicb commented on packages/common/src/util.ts
> +export function isBlank(value: any): boolean {
We have spent time to remove all the facades we had - are those really helpful ?

2017-07-28 19:32 UTC, ocombe commented on packages/common/src/i18n/format_number.ts
>    str: string | null,
because the pipes require string or null, not undefined

2017-07-28 19:34 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +  return res !;
It cannot return undefined based on how I extract the data, which means that I don't want to change the api return type to include undefined, but given how the for loop works typescript thinks that it could be undefined

2017-07-28 20:29 UTC, mary-poppins commented
You can preview 921c52b at https://pr18284-921c52b.ngbuilds.io/.

2017-07-28 21:02 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +    case DateType.FullYear:
again:
```
case DateType.Month:
     return date.getMonth();
```

no need for value & break

2017-07-28 21:08 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +  return data[index];
really ?

2017-07-28 21:10 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> +  if (typeof value === 'string' && !isNaN(+value - parseFloat(value))) {
is the `+` needed / valid here ?

2017-07-28 21:35 UTC, ocombe commented on packages/common/src/i18n/format_number.ts
> +  if (typeof value === 'string' && !isNaN(+value - parseFloat(value))) {
It's either that or `<any>` otherwise typescript throws (the function that you asked me to remove did cast it to any). I've done a few tests and it seems to be ok to use "+" ¯\_(ツ)_/¯

2017-07-28 21:45 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +  return data[index];
got a better idea?

2017-07-30 04:46 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +  return data[index];
we could also throw an error instead, since this use case is not supposed to happen

2017-08-04 00:07 UTC, vicb commented on packages/common/src/i18n/format_number.ts
>    str: string | null,
Please add a comment on the type, ie when is this `null` ? (Can we assume this is not null if there is no error).

_There is no reason why one consumer (the pipe) should dictate the data format_

2017-08-04 00:10 UTC, vicb commented on packages/common/src/i18n/localization.ts
> + * ie: "en-US" will return "en", and "fr_ca" will return "fr-CA"
Not sure to understand the "en-US"->"en" transform ? Is it because "en-US" is not supposed to exist ?

(On a side note is it expected to have a "en-US-POSIX" locale ?)

2017-08-04 00:16 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +  return data[index];
yep this should throw

2017-08-07 05:13 UTC, mary-poppins commented
You can preview e559e6f at https://pr18284-e559e6f.ngbuilds.io/.

2017-08-07 07:53 UTC, mary-poppins commented
You can preview 151f6ce at https://pr18284-151f6ce.ngbuilds.io/.

2017-08-10 21:45 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +      value = date.getDate();
simplify to return value and remove the break

2017-08-10 21:46 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +    switch (width) {
- compute `Math.floor(zone/60)` once before the switch
- early return instead of assigning to value

2017-08-10 21:50 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +      const diff = +thisThurs - +firstThurs;
use `getTime` instead of `+`

2017-08-10 21:54 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +enum LocaleData {
what is this ? (comment)

2017-08-10 21:57 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +   * The locale id for the chosen locale, for example `en-US`.
Does it exist (see my other related question)

2017-08-10 21:58 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +   * Periods of the day (e.g. AM/PM).
> (e.g. AM/PM)

this method returns an array of string, how does this related ?? (same below)

2017-08-10 21:58 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +   * Days of the week for the Gregorian calendar (e.g. `Sunday`).
index 0 is ?

2017-08-10 21:59 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +   * |--------|---------|
pls use fixed width cols

2017-08-10 22:00 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +      } else {
no else

2017-08-10 22:16 UTC, mary-poppins commented
You can preview 04c2c63 at https://pr18284-04c2c63.ngbuilds.io/.

2017-08-14 08:09 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +   * |--------|---------|
I can't because it gets over the 100 characters limit and `gulp format` moves some of the text to the next line, which breaks the table in the docs... Is there a way to force gulp format to ignore a specific comment?

2017-08-14 08:11 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +      } else {
By the way do you think that it's ok if `dayPeriodRules` returns `Time|[Time, Time]` or should it return `Time[]` instead? (I could convert the single value to an array with only one value, either in the api or in the extract script)

2017-08-14 09:02 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +   * The locale id for the chosen locale, for example `en-US`.
What do you mean by "does it exist" ?

2017-08-14 10:18 UTC, mary-poppins commented
You can preview 9cd9be3 at https://pr18284-9cd9be3.ngbuilds.io/.

2017-08-14 10:34 UTC, mary-poppins commented
You can preview 578d98a at https://pr18284-578d98a.ngbuilds.io/.

2017-08-14 16:21 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +   * |--------|---------|
`// clang-format [off/on]`

2017-08-14 17:59 UTC, mary-poppins commented
You can preview 1f70149 at https://pr18284-1f70149.ngbuilds.io/.

2017-08-14 18:39 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +    const minutes = Math.floor(zone / 60);
hour ?

2017-08-14 18:39 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +        return ((zone >= 0) ? '+' : '') + padNumber(zone > 0 ? minutes : minutes, 2, minusSign) +
`zone > 0 ? minutes : minutes`
test ?

2017-08-14 18:40 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +  return function(date: Date, api: LocaleDataApi, offset: number) {
offset -> add unit

2017-08-14 18:41 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> + * | decimal | 2,345`.`67 | decimal separator |
wrong

2017-08-14 18:44 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +        dateFormatter(date, locale, dateTimezoneOffset) :
getDateFromatter ?

2017-08-14 18:47 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +enum ExtraLocaleData {
-> better name

2017-08-14 18:52 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +    LOCALE_DATA[localeId][LocaleData.DayPeriodsRules] = extraData[ExtraLocaleData.DayPeriodsRules];
why `DayPeriodsRules` while other are prefixed with `Extra` ?
why multiple slots ?

2017-08-14 19:28 UTC, ocombe commented on packages/common/src/i18n/format_date.ts
> +        dateFormatter(date, locale, dateTimezoneOffset) :
no, `dateFormatter` that we define just above

2017-08-14 19:44 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +        dateFormatter(date, locale, dateTimezoneOffset) :
I mean the name could be improved

2017-08-14 20:21 UTC, mary-poppins commented
You can preview 252bbb4 at https://pr18284-252bbb4.ngbuilds.io/.

2017-08-14 21:01 UTC, mary-poppins commented
You can preview 5bca539 at https://pr18284-5bca539.ngbuilds.io/.

2017-08-14 21:10 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> + * Returns the first value that is defined in an array, going backwards.
first ... backwards = last ? -> `getLastDefinedValue` ?

2017-08-14 21:10 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> + * To avoid repeating equivalent data (e.g. when "format" and "standalone" are the same) we only
`equivalent` -> `same` ?

2017-08-14 21:11 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> + * To avoid repeating equivalent data (e.g. when "format" and "standalone" are the same) we only
"the other ones are undefined if they are duplicates" -> "are only defined when different"

2017-08-14 21:13 UTC, vicb commented on packages/common/test/pipes/date_pipe_spec.ts
> +                   .toMatch(/07-05-2017 \d{2}:\d{2}/));
why change from `22:14` to `\d{2}:\d{2}` ? Is there a change in TZ handling ?

2017-08-14 21:13 UTC, vicb commented on packages/common/test/pipes/date_pipe_spec.ts
> +        expect(pipe.transform('2017-06-13T10:14:39+0000', 'shortTime', '+0000'))
why changed ?

2017-08-14 21:18 UTC, ocombe commented on packages/common/test/pipes/date_pipe_spec.ts
> +        expect(pipe.transform('2017-06-13T10:14:39+0000', 'shortTime', '+0000'))
it failed the tests on travis (worked fine on local)

2017-08-14 21:19 UTC, ocombe commented on packages/common/test/pipes/date_pipe_spec.ts
> +                   .toMatch(/07-05-2017 \d{2}:\d{2}/));
we're testing the format, not the timezone (and it failed on travis because of the different time zone)

2017-08-14 22:14 UTC, vicb commented on packages/common/test/pipes/date_pipe_spec.ts
> +        expect(pipe.transform('2017-06-13T10:14:39+0000', 'shortTime', '+0000'))
Do you understand why ?
Why do we have a "in Safari" remaining in this spec ?

2017-08-14 22:15 UTC, vicb commented on packages/common/test/pipes/date_pipe_spec.ts
> +                   .toMatch(/07-05-2017 \d{2}:\d{2}/));
Do you understand why ?
Why do we have a "in IE11" remaining in this spec ?

2017-08-15 07:19 UTC, ocombe commented on packages/common/src/i18n/format_date.ts
> +  return function(date: Date, api: LocaleDataApi, offset: number) {
what do you mean?

2017-08-15 07:19 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> + * | decimal | 2,345`.`67 | decimal separator |
what is wrong?

2017-08-15 07:22 UTC, ocombe commented on packages/common/test/pipes/date_pipe_spec.ts
> +                   .toMatch(/07-05-2017 \d{2}:\d{2}/));
I removed the ie11 test

2017-08-15 07:39 UTC, ocombe commented on packages/common/test/pipes/date_pipe_spec.ts
> +        expect(pipe.transform('2017-06-13T10:14:39+0000', 'shortTime', '+0000'))
The problem is explained in the deprecated date pipe test with the following comment:
```ts
// TODO: reactivate the disabled expectations once emulators are fixed in SauceLabs
// In some old versions of Chrome in Android emulators, time formatting returns dates in the
// timezone of the VM host,
// instead of the device timezone. Same symptoms as
// https://bugs.chromium.org/p/chromium/issues/detail?id=406382
// This happens locally and in SauceLabs, so some checks are disabled to avoid failures.
// Tracking issue: https://github.com/angular/angular/issues/11187
```

The original tests for IE & safari only checks the date, not the hours/minutes because of that bug:
```ts
it('should format invalid in Safari ISO date',
         () => expect(pipe.transform('2017-01-20T19:00:00+0000')).toEqual('Jan 20, 2017'));
```

What we are testing here is that we can actually parse an ISO string as is it formatted by safari/IE (which is not a "valid" ISO string as defined in the ISO spec)

I'm not sure why I changed the test to minutes/hours, I think that what I wanted to do originally is test whether fixing the new "zone" parameter fixes the problem of mismatched hours/minutes (which is the point of this parameter).
I'm going to reintroduce the 2 original safari/IE test, and add a new one that checks the timezone parameter.

2017-08-15 08:23 UTC, mary-poppins commented
You can preview 8513413 at https://pr18284-8513413.ngbuilds.io/.

2017-08-15 08:25 UTC, ocombe commented on packages/common/test/pipes/date_pipe_spec.ts
> +        expect(pipe.transform('2017-06-13T10:14:39+0000', 'shortTime', '+0000'))
Ok I reran the tests without the timezone and we have the bug in safari: https://travis-ci.org/angular/angular/jobs/264651270#L869-L912
This is the bug reported here: https://github.com/angular/angular/issues/17478
I'm not sure how we should fix this

2017-08-15 08:36 UTC, mary-poppins commented
You can preview 1da05f9 at https://pr18284-1da05f9.ngbuilds.io/.

2017-08-15 08:56 UTC, mary-poppins commented
You can preview 764e74a at https://pr18284-764e74a.ngbuilds.io/.

2017-08-15 09:25 UTC, mary-poppins commented
You can preview a6dc69f at https://pr18284-a6dc69f.ngbuilds.io/.

2017-08-15 13:08 UTC, mary-poppins commented
You can preview cc8d7e4 at https://pr18284-cc8d7e4.ngbuilds.io/.

2017-08-15 15:49 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +  return function(date: Date, api: LocaleDataApi, offset: number) {
offset seconds ie

2017-08-15 16:27 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +  const amPm = getLastDefinedValue<[string, string][]>(
remove the type on call sites `getLastDefinedValue(...)`

2017-08-15 16:28 UTC, vicb commented on packages/common/test/pipes/date_pipe_spec.ts
> +      xit('should show the correct time in Safari with shortTime and custom format', () => {
xit ?

2017-08-16 10:06 UTC, mary-poppins commented
You can preview f10f254 at https://pr18284-f10f254.ngbuilds.io/.

2017-08-16 10:26 UTC, mary-poppins commented
You can preview 940cedf at https://pr18284-940cedf.ngbuilds.io/.

2017-08-16 10:59 UTC, mary-poppins commented
You can preview 57ebe23 at https://pr18284-57ebe23.ngbuilds.io/.

2017-08-16 16:20 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> +      } else if (parts[3] != null && minFraction > maxFraction) {
PLS remove magic 1, 3, 5, replace with constants with comments on them

2017-08-16 16:22 UTC, vicb commented on packages/common/src/i18n/locale_data_api.ts
> +  const data = <[string, string][][]>findLocaleData(locale);
`const data = <[string, string][][]>findLocaleData(locale);`
vs
`const data = <string[][][]>findLocaleData(locale);`

at least one place is wrong.

Types are not here to (only) please the compiler !

2017-08-16 16:25 UTC, vicb commented on tools/gulp-tasks/cldr/extract.js
> + * e.g.: [x, y, undefined, z, undefined, undefined] will be [x, y, , z, , ]
pls keep undefined here

2017-08-16 16:26 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +  const data = <[string, string][][]>findLocaleData(locale);
they are both correct I think:
- the first one contains [string, string]
- the second one contains an unknown number of strings because of period rules (we can have 0+)

2017-08-16 16:29 UTC, ocombe commented on tools/gulp-tasks/cldr/extract.js
> + * e.g.: [x, y, undefined, z, undefined, undefined] will be [x, y, , z, , ]
this almost double the size of locale files and is not necessary, why would we keep it?

2017-08-16 17:03 UTC, mary-poppins commented
You can preview 9d537f6 at https://pr18284-9d537f6.ngbuilds.io/.

2017-08-16 17:57 UTC, juleskremer approved these changes
OC: Approved change to docs; however, additional changes will be needed post-RC0.  I will create a new issue when ready.

2017-08-16 18:42 UTC, mary-poppins commented
You can preview 2f8665a at https://pr18284-2f8665a.ngbuilds.io/.

2017-08-16 19:05 UTC, mary-poppins commented
You can preview f2ae5d0 at https://pr18284-f2ae5d0.ngbuilds.io/.

2017-08-16 21:46 UTC, vicb requested changes

2017-08-16 21:46 UTC, vicb commented on packages/common/src/pipes/date_pipe.ts
> + *  |                    | aaaa        | Wide                                                          | ante meridiem/post meridiem                                |
This does not match the code:
- remove the code,
- remove any provision there could be in the code for that

2017-08-16 21:53 UTC, mary-poppins commented
You can preview 146f211 at https://pr18284-146f211.ngbuilds.io/.

2017-08-17 08:14 UTC, mary-poppins commented
You can preview fe7d604 at https://pr18284-fe7d604.ngbuilds.io/.

2017-08-17 09:08 UTC, mary-poppins commented
You can preview 277aa56 at https://pr18284-277aa56.ngbuilds.io/.

2017-08-17 10:13 UTC, mary-poppins commented
You can preview c59f749 at https://pr18284-c59f749.ngbuilds.io/.

2017-08-17 16:42 UTC, cexbrayat commented on packages/common/src/i18n/locale_data_api.ts
> + * | nan                    | `NaN`             | "not a number".                             |
@ocombe Not sure if relevant: `timeSeparator` and `currencyGroup` are missing in the docs here.

2017-08-17 16:56 UTC, cexbrayat commented on packages/common/src/pipes/number_pipe.ts
> + * - `display` indicates whether to show the currency symbol or the code.
@ocombe This is still called `symbolDisplay` in the `howToUse` section.

2017-08-17 17:09 UTC, vicb approved these changes

2017-08-17 17:10 UTC, vicb commented
LGTM when Travis is green.

@ocombe please rebase (the mem fix for CI has been merged), create a new issue for the optional test which is failing, add a link to the PR in the issue.
Thanks.

2017-08-17 17:11 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> + * | nan                    | `NaN`             | "not a number".                             |
good call, adding those, and the missing `currencyDecimal` also

2017-08-17 17:57 UTC, mary-poppins commented
You can preview eac0b99 at https://pr18284-eac0b99.ngbuilds.io/.

2017-08-18 07:50 UTC, mary-poppins commented
You can preview 97c6974 at https://pr18284-97c6974.ngbuilds.io/.

2017-08-21 08:39 UTC, mary-poppins commented
You can preview 154def8 at https://pr18284-154def8.ngbuilds.io/.

2017-08-21 08:49 UTC, mary-poppins commented
You can preview 591dea5 at https://pr18284-591dea5.ngbuilds.io/.

2017-08-21 15:49 UTC, mary-poppins commented
You can preview 3ae3d61 at https://pr18284-3ae3d61.ngbuilds.io/.

2017-08-21 17:26 UTC, mary-poppins commented
You can preview 9613115 at https://pr18284-9613115.ngbuilds.io/.

2017-08-22 18:25 UTC, vicb commented on packages/common/src/common.ts
> -export {findLocaleData, registerLocaleData, NumberFormatStyle, FormStyle, Time, TranslationWidth, FormatWidth, NumberSymbol, WeekDay, getLocaleDayPeriods, getLocaleDayNames, getLocaleMonthNames, getL
hum ?

2017-08-22 20:40 UTC, mhevery approved these changes

2017-08-22 20:54 UTC, closed without merging