ci: compute AIO deployment mode
angular/angular pull request #18297
Opened 2017-07-23 08:39 UTC by petebacondarwin

There are now 3 modes for deployment: next, stable, archive.
We compute which mode (and other deployment properties)
from the TRAVIS_BRANCH and the STABLE_BRANCH.

If the TRAVIS_BRANCH is master we deploy as "next".
If the TRAVIS_BRANCH matches the STABLE_BRANCH then
we deploy as "stable"
Otherwise we deploy as "archive" and compute the firebase
project and deployment url based on the major version of the
TRAVIS_BRANCH.

As well as choosing where to deploy the build, we also use this
to select the environment file for the AIO Angular app.
This will enable the app to change its rendering and behaviour
based on its mode.

See #18287

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2017-07-25 21:25 UTC, gkalpak requested changes

2017-07-25 21:25 UTC, gkalpak commented on aio/src/app/app.component.html
> -    <div class="doc-version" title="Angular docs version {{currentDocVersion?.title}}">
OOC, why?

2017-07-25 21:25 UTC, gkalpak commented on aio/src/app/app.component.ts
> +      // Redirect to docs if we are in archive mode and not hitting a docs page (i.e. a marketing page)
_we are in archive mode_ --> _we are not in stable mode_/_we are in archive or next mode_

2017-07-25 21:25 UTC, gkalpak commented on aio/src/app/app.component.spec.ts
> +    })
Missing `;` 🙀

2017-07-25 21:25 UTC, gkalpak commented on aio/src/app/app.component.spec.ts
> +      });
No tests for other modes 😞

2017-07-26 16:55 UTC, petebacondarwin commented on aio/.angular-cli.json
> -        "prod": "environments/environment.prod.ts"
OK

2017-07-26 16:58 UTC, petebacondarwin commented on aio/src/environments/environment.ts
> +  mode: 'stable'
I think we agreed that dev env would just use this `gaId` since we can filter out `localhost` requests??  @wardbell or @IgorMinar  might know more.

2017-07-26 16:58 UTC, petebacondarwin commented on aio/scripts/deploy-to-firebase.sh
> +    echo "Unknown deployment environment ('$deployEnv'). Expected 'next', 'stable' or 'archive'."
OK

2017-07-26 17:05 UTC, petebacondarwin commented on scripts/ci/deploy.sh
>          exit 0
:-( you're right. How about we try to deploy for any build that is at the head of a branch?
The actual firebase deploy will fail because there will be no matching FB project.

For example, building `my-temp-branch` on `angular/angular` would result in `deploy-to-firebase.sh` attempting to deploy to the FB project called `angular-io-my-temp-branch` at the url `https://vmy-temp-branch.angular.io/`

Or is this too hacky?

Otherwise we have to somehow work out if the branch is a valid archive branch or not...

2017-07-26 17:13 UTC, petebacondarwin commented on aio/src/app/app.component.html
> -    <div class="doc-version" title="Angular docs version {{currentDocVersion?.title}}">
This just seems wrong. The `div` is a container that holds the drop-down to select versions. Why should it have a `title` that describes just one of the versions?
If anything I would expect it to have a title that said something like `"Select a version of Angular"`.

Moreover, because there were no other `title` attributes, further down, it meant that this tooltip pops up when you hover over any of the individual versions in the drop-down.

![image](https://user-images.githubusercontent.com/15655/28634104-0d9849e6-722e-11e7-9493-35e3b4b7f425.png)

![image](https://user-images.githubusercontent.com/15655/28634121-1bdbff16-722e-11e7-8d66-db34e910f9ce.png)

2017-07-26 17:17 UTC, petebacondarwin commented on aio/src/app/app.component.spec.ts
> +      });
gotcha!

2017-07-26 17:17 UTC, petebacondarwin commented on aio/src/app/app.component.spec.ts
> +    })
OMG!

2017-07-26 17:53 UTC, gkalpak commented on scripts/ci/deploy.sh
>          exit 0
But archive branches will not deploy to a project matchig their name exactly, would they? Because we only care about the major version.
We need to somehow detect if a branch is an archive branch and even further detect if it is the latest branch for that major version. E.g. we don't want to deploy to `v4.angular.io` from `4.2.x` once `4.3.x` has been released.

2017-07-26 19:45 UTC, petebacondarwin commented on scripts/ci/deploy.sh
>          exit 0
Agh! Yes we don't want to deploy from 4.2.x at all once 4.3.x is released...
What to do ...

2017-07-26 20:01 UTC, petebacondarwin commented on scripts/ci/deploy.sh
>          exit 0
So instead when we have an archive release, we search github for the most recent minor release for that archive's major version and only deploy if that matches the current branch, right?

2017-07-26 20:05 UTC, IgorMinar reviewed
There is no preview link - I guess because of the recent CI issues.

Overall this looks very good. Posting a few minor comments. Let's wait for the preview before merging this in.

2017-07-26 20:05 UTC, IgorMinar commented on aio/src/app/app.component.html
> -    <div class="doc-version" title="Angular docs version {{currentDocVersion?.title}}">
was this done for (wrong) accessibility reasons? AFAIK the title attribute is not useful in this context.

2017-07-26 21:00 UTC, mary-poppins commented
You can preview 7f4d13b at https://pr18297-7f4d13b.ngbuilds.io/.

2017-07-26 21:07 UTC, petebacondarwin commented on scripts/ci/deploy.sh
>          exit 0
I updated the code for this... PTAL

2017-07-26 21:08 UTC, petebacondarwin commented on aio/src/app/app.component.html
> -    <div class="doc-version" title="Angular docs version {{currentDocVersion?.title}}">
I guess that was the case.

2017-07-26 21:09 UTC, petebacondarwin commented on aio/src/app/layout/mode-banner/mode-banner.component.ts
> +    This is the <strong>archived documentation for Angular v{{version?.major}}.</strong>
I'll check

2017-07-26 21:09 UTC, petebacondarwin commented on aio/src/extra-files/archive/robots.txt
> +Disallow: /
done

2017-07-26 21:14 UTC, petebacondarwin commented on aio/src/app/shared/deployment.service.ts
> +  mode: string = this.location.search()['deploymode'] || environment.mode;
I was worried that 'mode' would be too generic and might conflict with some future feature...
Since this is a debug thing, how about '_mode'?

2017-07-26 21:25 UTC, petebacondarwin commented on aio/src/app/shared/deployment.service.ts
> +  mode: string = this.location.search()['deploymode'] || environment.mode;
Actually let's just go with 'mode' - first come first served

2017-07-26 21:41 UTC, petebacondarwin commented on aio/src/app/layout/mode-banner/mode-banner.component.ts
> +    This is the <strong>archived documentation for Angular v{{version?.major}}.</strong>
No, the version info is set via a subscription in the AppComponent: https://github.com/angular/angular/blob/205abe814017a48ec602db959dea37966292dd32/aio/src/app/app.component.ts#L176

2017-07-26 21:43 UTC, petebacondarwin commented
Updated @IgorMinar - PTAL

2017-07-26 22:17 UTC, wardbell commented on aio/src/environments/environment.ts
> +  mode: 'stable'
What he said ^^^

2017-07-26 23:01 UTC, mary-poppins commented
You can preview 771a433 at https://pr18297-771a433.ngbuilds.io/.

2017-07-27 06:19 UTC, petebacondarwin commented
Some examples:

Archive mode: https://pr18297-771a433.ngbuilds.io/tutorial?mode=archive

![screen shot 2017-07-27 at 07 14 12](https://user-images.githubusercontent.com/15655/28656686-40aaf848-729b-11e7-89d7-d19a3f7ebff9.png)

Next mode: https://pr18297-771a433.ngbuilds.io/tutorial?mode=archive

![screen shot 2017-07-27 at 07 15 00](https://user-images.githubusercontent.com/15655/28656717-6ab212f2-729b-11e7-9ef5-ba2536e78d7d.png)

Redirection - clicking on this link will redirect you to the docs page: https://pr18297-771a433.ngbuilds.io/resources?mode=next. Note that the query string doesn't survive the redirection (which is not a problem in practice) but does mean that the mode disappears after the redirection in this case.

2017-07-27 06:20 UTC, petebacondarwin commented on aio/package.json
> +    "build": "ng build ng build --target=production --environment=stable -sm -vc=false",
This change fixes @gkalpak comment https://github.com/angular/angular/pull/18297/files#r129411614

2017-07-27 06:21 UTC, petebacondarwin commented on aio/src/app/app.component.spec.ts
> +      });
added

2017-07-27 07:03 UTC, mary-poppins commented
You can preview 377cf4b at https://pr18297-377cf4b.ngbuilds.io/.

2017-07-27 10:39 UTC, gkalpak requested changes

2017-07-27 10:39 UTC, gkalpak commented on aio/scripts/deploy-to-firebase.sh
> +    git ls-remote https://github.com/angular/angular refs/heads/${majorVersion}.*.x |
Nit: Why not use `origin`? (We already use it to determine the lastest commit.)

2017-07-27 10:39 UTC, gkalpak commented on aio/scripts/deploy-to-firebase.sh
> +    readonly deployEnv=archive
This will still deploy `4.2.x` to `v4.angular.io` when `4.3.x` is the stable. Is it intentional?

2017-07-27 10:39 UTC, gkalpak commented on aio/scripts/deploy-to-firebase.sh
>      readonly deployedUrl=https://$projectId.firebaseapp.com/
Shouldn't this be `https://next.angular.io/`?

2017-07-27 10:39 UTC, gkalpak commented on aio/scripts/deploy-to-firebase.sh
> +  cp -rf src/extra-files/$buildEnv/. dist/
`$buildEnv` --> `$deployEnv`

2017-07-27 14:43 UTC, petebacondarwin commented on aio/src/environments/environment.ts
> +  gaId: 'UA-8594346-26', // Staging id
OK - let's call it dev

2017-07-27 14:43 UTC, petebacondarwin commented on aio/scripts/deploy-to-firebase.sh
> +    git ls-remote https://github.com/angular/angular refs/heads/${majorVersion}.*.x |
Because I was worried that `origin` might not exist on a CI server. But I guess, if we are using it elsewhere then it is less fragile for using with a different repo.

2017-07-27 14:46 UTC, petebacondarwin commented on aio/scripts/deploy-to-firebase.sh
> +    readonly deployEnv=archive
While 4.3.x is stable, there will be no `angular-io-4` firebase project, so it would just fail.
Perhaps we want not to fail but just quietly not deploy...

2017-07-27 15:04 UTC, petebacondarwin commented on aio/scripts/deploy-to-firebase.sh
> +    readonly deployEnv=archive
OK, so I'll change it so that we quietly fail if there is a branch with the same major but a higher minor version number - even if that higher branch is marked as the stable branch.

2017-07-27 15:06 UTC, petebacondarwin commented on aio/scripts/deploy-to-firebase.sh
>      readonly deployedUrl=https://$projectId.firebaseapp.com/
Hmm, well strictly we are deploying to `aio-staging.firebaseapp.com` it just happens that this is also `next.angular.io`. Happy to change later if that is a problem.

2017-07-27 15:06 UTC, petebacondarwin commented on aio/scripts/deploy-to-firebase.sh
> +  cp -rf src/extra-files/$buildEnv/. dist/
:scream:

This file really should have some kind of unit test :-(

2017-07-27 15:21 UTC, petebacondarwin commented on aio/scripts/deploy-to-firebase.sh
> +  fi
So now we will only deploy to `stable` if there is no branch with a the same major and higher minor version. This means that we couldn't have a stable branch of `4.3.x` and then have another branch with `4.4.x`.

2017-07-27 15:36 UTC, mary-poppins commented
You can preview 58aa117 at https://pr18297-58aa117.ngbuilds.io/.

2017-07-27 22:04 UTC, gkalpak commented on aio/scripts/deploy-to-firebase.sh
>      readonly deployedUrl=https://$projectId.firebaseapp.com/
Strictly we are deploying stable to `angular-io.firebaseapp.com`, but that didn't stop you from use `https://angular.io` as the deployed URL 😛 

There shouldn't be any practical difference (except maybe that using `next.angular.io` would also verify that the DNS is configured correctly 🎉).

2017-07-27 22:10 UTC, gkalpak commented on aio/scripts/deploy-to-firebase.sh
> +  fi
Hm...that sound almost right, but...
What happens when 4.3.x is the stable branch and we want to deploy `4.4.0-beta.1` from the 4.4.x branch?
We need a more elaborate check that only archives branches below the current stable branch.

2017-07-28 11:15 UTC, mary-poppins commented
You can preview e668e8b at https://pr18297-e668e8b.ngbuilds.io/.

2017-07-28 11:46 UTC, gkalpak approved these changes
Love the bash script unit test. It's a shame not to run it on CI, though 😞 

LGTM (as soon as Travis is green).

2017-07-28 11:46 UTC, gkalpak commented on aio/scripts/deploy-to-firebase.test.sh
> +  exit 0
No indentation 😞

2017-07-28 11:46 UTC, gkalpak commented on aio/scripts/deploy-to-firebase.test.sh
> +    export TRAVIS_BRANCH=2.1.x
I might add a test with `TRAVIS_BRANCH.minor > STABLE_BRANCH.minor` (e.g. `TRAVIS_BRANCH=2.4.x`, `STABLE_BRANCH=2.2.x`) just to make it more obvious.
(It is essentally the same check that is in effect for this test, it just makes the intent in that specific corner-case more obvious.)

2017-07-28 11:53 UTC, gkalpak commented on scripts/ci/deploy.sh
>      fi
Oh, this `fi` should go (kudos to Travi for catching that).

2017-07-28 12:21 UTC, mary-poppins commented
You can preview a16e9dc at https://pr18297-a16e9dc.ngbuilds.io/.

2017-07-28 12:38 UTC, mary-poppins commented
You can preview 25e25d9 at https://pr18297-25e25d9.ngbuilds.io/.

2017-07-28 15:59 UTC, mary-poppins commented
You can preview 0856320 at https://pr18297-0856320.ngbuilds.io/.

2017-07-28 22:27 UTC, alxhub commented
Removing the merge label as this doesn't have full approval yet. I'll ping it to Igor.

2017-08-02 18:29 UTC, IgorMinar approved these changes

2017-08-02 22:40 UTC, vicb commented
conflicts -> blocked
@petebacondarwin could you please rebase ?

2017-08-03 18:40 UTC, mary-poppins commented
You can preview 68ad94c at https://pr18297-68ad94c.ngbuilds.io/.

2017-08-03 19:14 UTC, gkalpak commented
Rebased. (CI failures "inherited" from master.)

2017-08-04 16:15 UTC, closed without merging

2017-08-04 16:16 UTC, vicb commented
Thanks for rebasing @gkalpak