fix(ngc-wrapped): fix broken bazel build
angular/angular pull request #18335
Opened 2017-07-25 23:16 UTC by adeora

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Bazel build doesn't work properly

Issue Number: N/A

## What is the new behavior?
Bazel build works properly

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2017-07-25 23:54 UTC, chuckjaz requested changes

2017-07-25 23:54 UTC, chuckjaz commented on tools/ngc-wrapped/index.ts
> +  const result = ngc(args, undefined);
Change this to use the the new API instead.

2017-07-26 01:21 UTC, chuckjaz approved these changes

2017-07-26 16:40 UTC, mhevery approved these changes

2017-07-26 16:40 UTC, merged