ci(aio): Refactored payload size script, add script to track payload …
angular/angular pull request #18517
Opened 2017-08-03 22:43 UTC by tinayuangao

…size for hello-world cli project

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
- Refactored payload-size script so it's re-usable
- Added script in `run_tests.sh` to generate a new hello-world project using angular-cli
- Track all the project size in `integration` if they have a `dist` folder

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2017-08-03 22:53 UTC, mary-poppins commented
You can preview bc50b65 at https://pr18517-bc50b65.ngbuilds.io/.

2017-08-04 00:19 UTC, gkalpak reviewed
`scripts/ci/payload-size.sh` is kind of hard to follow (with all the globals etc), but other than that LGTM (afaict - you can never be sure with bash :smiley:)

2017-08-04 22:36 UTC, mary-poppins commented
You can preview d9dea1a at https://pr18517-d9dea1a.ngbuilds.io/.

2017-08-04 23:12 UTC, mary-poppins commented
You can preview 859c2ba at https://pr18517-859c2ba.ngbuilds.io/.

2017-08-04 23:46 UTC, mary-poppins commented
You can preview bf8ea16 at https://pr18517-bf8ea16.ngbuilds.io/.

2017-08-04 23:56 UTC, mary-poppins commented
You can preview 6da75c8 at https://pr18517-6da75c8.ngbuilds.io/.

2017-08-05 00:10 UTC, mary-poppins commented
You can preview 68d74c1 at https://pr18517-68d74c1.ngbuilds.io/.

2017-08-10 01:41 UTC, IgorMinar commented on integration/run_tests.sh
> +npm install -g @angular/cli
I think we should pin this dependency, otherwise we can get easily broken when a cli release with regression happens.

I suggest we add a new global variable into `env.sh` specifying the cli version that should be used for this test, we do the same thing with chrome version or yarn.

2017-08-12 01:12 UTC, tinayuangao commented
@IgorMinar Added comments, and checked payload size for `hello_world__cli` and `hello_world__closure`. Will track umd size in a separate pr. PTAL. Thanks for review!

2017-08-17 18:12 UTC, tinayuangao commented
Sync and rebased on Misko's PR. Please take another look. Thanks!

2017-08-17 18:20 UTC, mary-poppins commented
You can preview 5b8952c at https://pr18517-5b8952c.ngbuilds.io/.

2017-08-17 18:24 UTC, mary-poppins commented
You can preview ab7b7fc at https://pr18517-ab7b7fc.ngbuilds.io/.

2017-08-17 18:29 UTC, mary-poppins commented
You can preview 41587f5 at https://pr18517-41587f5.ngbuilds.io/.

2017-08-17 18:53 UTC, mary-poppins commented
You can preview 36ad3b6 at https://pr18517-36ad3b6.ngbuilds.io/.

2017-08-18 17:35 UTC, tinayuangao commented
Added tracking `umd` size part. Please take another look. Thanks! @IgorMinar

2017-08-18 17:59 UTC, mary-poppins commented
You can preview b3d5fa1 at https://pr18517-b3d5fa1.ngbuilds.io/.

2017-08-18 18:34 UTC, mhevery requested changes
One change, LGTM otherwise

2017-08-18 18:34 UTC, mhevery commented on integration/run_tests.sh
> +    # Track payload size for cli-hello-world and hello_world__closure
Could we just add `yarn build` before `yarn test` and make sure that all of the subdirectories have an appropriate `yarn build` command even if it is noop?

2017-08-18 19:26 UTC, mary-poppins commented
You can preview ff2be79 at https://pr18517-ff2be79.ngbuilds.io/.

2017-08-18 19:41 UTC, tinayuangao commented on integration/run_tests.sh
> +    # Track payload size for cli-hello-world and hello_world__closure
Done. Added `ngc` or `echo noop` in `package.json` files. PTAL. Thanks!

2017-08-18 21:41 UTC, mhevery approved these changes

2017-08-19 04:14 UTC, closed without merging