fix(forms): markAsPending to emit events
angular/angular pull request #18676
Opened 2017-08-14 11:40 UTC by ksvitkovsky

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #17958 

## What is the new behavior?

Control emits `PENDING` event on `markAsPending` method call.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2017-08-14 23:06 UTC, kara requested changes
Thanks for the fix! Some minor comments. Ping me when it's ready for review again.

2017-08-14 23:06 UTC, kara commented on packages/forms/test/form_array_spec.ts
> +      });
Can you add a test for when the array itself is marked as pending?

2017-08-14 23:06 UTC, kara commented on packages/forms/test/form_control_spec.ts
> +      it('should not update the parent when onlySelf = true', () => {
In this test setup, there isn't a  parent control. Not sure what this is testing? Given the tests in form_group_spec and form_array_spec, I'd delete this one.

2017-08-14 23:06 UTC, kara commented on packages/forms/test/form_group_spec.ts
> +        });
Can you add a test for when the group itself is marked as pending?

2017-08-15 05:24 UTC, ksvitkovsky commented on packages/forms/test/form_array_spec.ts
> +      it('should be false after creating a control', () => { expect(a.pending).toEqual(false); });
It seems that the assertions was added here in the first place to check the control itself. Since I added the suite for control in `form_control_spec.ts` I thought these assertions could be removed. 

Am I wrong? If so, should I add similar expectations in `form_group_spec.ts`?

2017-08-15 05:25 UTC, ksvitkovsky commented on packages/forms/src/model.ts
>        this._parent.markAsPending(opts);
Sorry, I did not quite get it 😊  It is passed on line 359, or did you mean something else?

2017-08-15 05:35 UTC, ksvitkovsky commented
@kara sorry, that is a sloppy work indeed 😔  but some points are unclear, added comments

2017-08-15 16:59 UTC, kara commented on packages/forms/src/model.ts
>        this._parent.markAsPending(opts);
You are right! Somehow I read that as `markAsPending()` without the arg. Ignore me :)

2017-08-15 17:00 UTC, kara commented on packages/forms/test/form_array_spec.ts
> +      it('should be false after creating a control', () => { expect(a.pending).toEqual(false); });
I see. I think these are distinct because they are controls with a `FormArray` parent (which could affect the outcome). In the form control spec, you are only testing form controls in isolation.

2017-09-10 08:51 UTC, Toxicable commented
@ksvitkovsky could you do a rebase with master than squash your commits
address the other comments 
Changes `Issue Number: #17958` or `closes #17958` this just means it's auto closed when this is merged

2017-10-30 17:27 UTC, closed without merging