fix(tsc-wrapped): add metadata for `type` declarations
angular/angular pull request #18704
Opened 2017-08-15 14:41 UTC by alan-agius4

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
At the moment types don't have metadata, and is resulting in incorrect metadata in json when the file only contain `type`

Issue: #18675  

## What is the new behavior?
Type have now metadata

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

2017-08-17 16:32 UTC, chuckjaz requested changes

2017-08-17 16:32 UTC, chuckjaz commented on packages/tsc-wrapped/src/collector.ts
> +              metadata[name] = {__symbolic: 'type'};
Use `{ __symbolic: 'interface' }` instead.  The metadata uses "interface" as the symbolic token value for all non-class types.

2017-08-17 16:37 UTC, chuckjaz commented
Please also squash both the commits into one.

2017-08-17 18:33 UTC, alan-agius4 commented
@chuckjaz squashed commits and changed the `__symbolic ` value as suggested

2017-08-17 18:33 UTC, alan-agius4 commented on packages/tsc-wrapped/src/collector.ts
> +              metadata[name] = {__symbolic: 'type'};
done

2017-08-17 20:31 UTC, chuckjaz approved these changes

2017-08-18 06:20 UTC, closed without merging

2017-08-24 06:34 UTC, alan-agius4 commented
@chuckjaz wasn't this also supposed to be merged as a patch?

2017-08-24 18:55 UTC, alan-agius4 commented
@chuckjaz & @mhegazy wasn't this also supposed to be merged as a patch?