build(aio): add support for using the locally built Angular packages for aio
angular/angular pull request #18722
Opened 2017-08-16 00:44 UTC by gkalpak

Fixes #18611.

2017-09-08 08:44 UTC, petebacondarwin commented
Various failures on Travis.

2017-09-08 09:52 UTC, mary-poppins commented
You can preview 0742e1b at https://pr18722-0742e1b.ngbuilds.io/.

2017-09-11 13:02 UTC, gkalpak commented on scripts/ci/test-aio.sh
> -    yarn boilerplate:test
This is now part of `yarn tools-test`:

https://github.com/gkalpak/angular/blob/f739b94fcaef280487377fbd6ef87f4c20b36f91/aio/package.json#L39

...which is run in `test-aio-tools.sh`:

https://github.com/gkalpak/angular/blob/f739b94fcaef280487377fbd6ef87f4c20b36f91/scripts/ci/test-aio-tools.sh#L13

2017-09-11 18:58 UTC, mary-poppins commented
You can preview 90a1837 at https://pr18722-90a1837.ngbuilds.io/.

2017-09-11 21:13 UTC, mary-poppins commented
You can preview f99b8bb at https://pr18722-f99b8bb.ngbuilds.io/.

2017-09-13 13:11 UTC, petebacondarwin requested changes
I may be wrong but I think that the scripts `setup` and `setup-local` are calling `ng-packages-installer` unnecessarily. Isn't it enough to do:

```json
"setup": "yarn boilerplate:add",
"setup-local": "yarn boilerplate:add -- --local",
```

2017-09-13 13:11 UTC, petebacondarwin commented on aio/package.json
> +    "setup": "node tools/ng-packages-installer restore . && yarn boilerplate:add",
Um, doesn't `yarn boilerplate:add` effectively run `ng-packages-installer restore` already?
Similarly `yarn boilerplate:add --local` effectively runs `ng-packages-installer overwrite`?

2017-09-13 18:11 UTC, gkalpak commented on aio/package.json
> +    "setup": "node tools/ng-packages-installer restore . && yarn boilerplate:add",
`yarn boilerplate:xyz` runs `ng-packages-installer` for the boilerplate files. `yarn setup-local/build-local` run it for `aio/`.

2017-09-13 18:14 UTC, gkalpak commented on aio/package.json
> +    "post~~build": "yarn sw-manifest && yarn sw-copy",
Not really. It was like this before (as `build` and `postbuild`), so I just added the `~~` prefix.

2017-09-13 18:18 UTC, gkalpak commented on aio/package.json
> +    "postsetup-local": "yarn ~~setup-phase3",
The initial idea for not having `"presetup-local": "yarn presetup"` was that it is not obvious (if you don't look carefully through the scripts) that `"presetup": "..."` applies to `setup-local` too. So, someone might make a change that is specific to `setup` not realizing that it will affect `setup-local` too.

Given that the likelihood of this happening is very low, I am happy to reduce the number of scripts :smiley:

2017-09-13 18:23 UTC, gkalpak commented
The extra calls are for `aio/` itself (not boilerplate).
Fixed the other comments.

2017-09-13 18:30 UTC, mary-poppins commented
You can preview 551c5ad at https://pr18722-551c5ad.ngbuilds.io/.

2017-09-18 10:25 UTC, petebacondarwin commented
We agreed to change this so that you can switch from being in "npm" mode to "local" mode and back; and then all the other commands work in the current mode, e.g. build, serve, etc.

2017-09-18 14:46 UTC, mary-poppins commented
You can preview 1a4ae90 at https://pr18722-1a4ae90.ngbuilds.io/.

2017-09-18 20:07 UTC, mary-poppins commented
You can preview 07de92a at https://pr18722-07de92a.ngbuilds.io/.

2017-09-18 20:07 UTC, mary-poppins commented
You can preview 0d0853e at https://pr18722-0d0853e.ngbuilds.io/.

2017-09-18 23:22 UTC, mary-poppins commented
You can preview 02a4e23 at https://pr18722-02a4e23.ngbuilds.io/.

2017-09-19 08:22 UTC, mary-poppins commented
You can preview ed16645 at https://pr18722-ed16645.ngbuilds.io/.

2017-09-19 09:23 UTC, mary-poppins commented
You can preview a157d0e at https://pr18722-a157d0e.ngbuilds.io/.

2017-09-19 09:45 UTC, gkalpak commented
I played around with decoupling npm/local packages from `yarn setup` and run into some issues/concerns:

- In `setup`, boilerplate is removed and re-added every time (including `node_modules/`), so it is not straight forward to retain the setting (npm or local) for boilerplate.
- Whenever a dependency is updated (e.g. you checkout an update `yarn.lock`) and `yarn [install]` is run (which happens implicitly for `yarn setup` and the scripts that directly or indirectly depend on it), then the packages are restored (i.e. the ones from npm replace the local ones).

These make it difficult to guarantee that switching to local packages will not be unexpectedly switched under the hood.

We could have mechanisms to ensure that, but they have their cons to. E.g.:

- Using `yarn link` is a little too magical and affects global state. It is for example not possible to have two different local clones (e.g. one for master, one for stable) and independently test each against their respective local packages).
- Somehow cache the current state of Angular packages (i.e. npm or local) and choosing a behavior based on that is unnecessarily complicated.

##
With the current implementation:

- One can use `setup`/`setup-local` (or `build`/`build-local`) as the switch. The former ensures that the packages come form npm (and affects subsequent commands, such as `yarn test`, `yarn e2e` etc). The latter ensures that the local package are used (and similarly affects subsequent commands).
- A warning is printed before any script if there are any local packages used.
- One could still manually switch to npm/local packages (for a specific directory) with `node tools/ng-packages-installer (restore|overwrite) <root/dir>`.

I slightly prefer this approach (with `setup`/`setup-local`), because it is more explicit (less magical), predictable (if you stick to using the scripts, you won't be unexpectedly switched to npm/local packages) and unifies the behavior across the project (e.g. you don't have to switch `boilerplate` separately.

It is not ideal, but maybe good enough for now. @petebacondarwin, wdyt?

2017-09-19 10:03 UTC, petebacondarwin commented
I'll take a look when I am done with Jesus' PR

2017-09-19 14:06 UTC, petebacondarwin commented
I think this approach will have to do for now. I haven't had time to go through the PR in detail. Will do so tomorrow.

2017-09-20 17:45 UTC, petebacondarwin commented on aio/package.json
> +    "setup-local": "node tools/ng-packages-installer overwrite . && yarn boilerplate:add -- --local",
no that we are on yarn v1, we don't need all these `--` to separate the arguments to be passed through.

2017-09-20 17:47 UTC, petebacondarwin commented on aio/package.json
> +    "postcheck-env": "yarn check-ng-packages -- .",
+1!

2017-09-20 17:50 UTC, petebacondarwin commented on aio/tools/examples/example-boilerplate.spec.js
> +const exampleBoilerPlate = require('./example-boilerplate');
Ordering alphabetically by const (`ngPackagesInstaller`>`exampleBoilerPlate`!) or by module name (`glob`>`canonical-path`!)?

2017-09-20 18:00 UTC, petebacondarwin commented on aio/tools/examples/example-boilerplate.spec.js
> +      ngPackagesInstaller.overwritePackages.and.callFake(() => expect(shelljs.exec).toHaveBeenCalled());
This seems a slightly convoluted way of checking that `shelljs.exec` has been called. Is there some reason why you wouldn't just check directly after the following line?

2017-09-20 18:44 UTC, gkalpak commented on aio/tools/examples/example-boilerplate.spec.js
> +const exampleBoilerPlate = require('./example-boilerplate');
Or by path (`./<...>` > `../<...>`) :grin:

2017-09-20 18:56 UTC, gkalpak commented on aio/tools/examples/example-boilerplate.spec.js
> +      ngPackagesInstaller.overwritePackages.and.callFake(() => expect(shelljs.exec).toHaveBeenCalled());
I want to verify the order :grin:
Latest jasmine has some matchers for that (e.g. `toHaveBeenCalledAfter()`), but we're not there yet.

2017-09-20 19:26 UTC, petebacondarwin commented on aio/tools/examples/example-boilerplate.spec.js
> +const exampleBoilerPlate = require('./example-boilerplate');
By path (`glob`>`canonical-path`!) :-P

2017-09-20 19:27 UTC, petebacondarwin commented on aio/tools/examples/example-boilerplate.spec.js
> +      ngPackagesInstaller.overwritePackages.and.callFake(() => expect(shelljs.exec).toHaveBeenCalled());
Right I see. You could also use a log for that.

2017-09-20 19:31 UTC, petebacondarwin commented on aio/tools/ng-packages-installer.js
> +const PACKAGES_DIST_DIR = path.join(ROOT_DIR, 'dist/packages-dist');
IMO `resolve` is always a safer bet that `join`, just in case the base path is not absolute (which I admit it is in this case, for now)

2017-09-20 19:32 UTC, petebacondarwin commented on aio/tools/ng-packages-installer.js
> +     * (Detected as directories in '/packages/' that contain a top-level 'package.json' file.)
+100 - we should roll this out across the project :-)

2017-09-20 20:24 UTC, petebacondarwin commented on aio/tools/ng-packages-installer.js
> +    const isLocal = fs.existsSync(localFlagFile);
So if the node_modules package has been overwritten in any other way than via this tool, we would not be able to tell. I guess this is a reasonable constraint.

2017-09-20 20:27 UTC, petebacondarwin commented on aio/tools/ng-packages-installer.js
> +      shelljs.rm('-rf', targetPackageDir);
If for some reason (in the future) the local package relied upon a different version of a dependency that the rest of the setup, then this folder would contain its own `node_modules` folder, containing the conflicted versions.  By deleting the whole folder we are removing these dependencies.

Are we happy with this limitation?

2017-09-20 20:33 UTC, petebacondarwin commented on aio/tools/ng-packages-installer.js
> +    shelljs.exec(installCmd, {cwd: rootDir});
I assume `--check-files` checks all the files and not just the `package.json`?

2017-09-20 20:45 UTC, petebacondarwin commented on aio/tools/ng-packages-installer.js
> +      this._log(`Available Angular packages:\n${packagePrefix}${this.ngPackages.join(`\n${packagePrefix}`)}`);
This would render strangely if there were no packages in the array. How about:

```typescript
this._log(`Available Angular packages: ${this.ngPackages.map(p => `\n${packagePrefix}${p}`)}`);
```

2017-09-20 20:54 UTC, petebacondarwin commented on aio/tools/ng-packages-installer.spec.js
> +        expect(warnings[1]).toMatch(restoreCmdRe2);
Any reason not to interleave these expectations with their calls, i.e.:

```
const dir1 = rootDir;
const restoreCmdRe1 = RegExp(`\\bnode .*?ng-packages-installer restore .*?${path.normalize(rootDir)}\\b`);
installer.checkPackages(dir1);
const warnings = console.warn.calls.allArgs().map(args => args[0]);
expect(warnings[0]).toMatch(restoreCmdRe1);
console.warn.reset();

const dir2 = '.';
const restoreCmdRe2 = RegExp('\\bnode .*?ng-packages-installer restore \\.');
installer.checkPackages(dir2);
const warnings = console.warn.calls.allArgs().map(args => args[0]);
expect(warnings[0]).toMatch(restoreCmdRe2);
```

2017-09-20 20:55 UTC, petebacondarwin commented on aio/tools/ng-packages-installer.spec.js
> +      expect(installer._findLocalPackages).toHaveBeenCalledWith(absoluteRootDir);
```
expect(installer._reinstallOverwrittenNodeModules).not.toHaveBeenCalledWith(absoluteRootDir);
```
here too

2017-09-20 20:56 UTC, petebacondarwin commented on aio/tools/ng-packages-installer.spec.js
> +      expect(installer._findLocalPackages).toHaveBeenCalledWith(absoluteRootDir);
Oh, I see you test that below.

2017-09-20 20:57 UTC, petebacondarwin commented on aio/tools/ng-packages-installer.spec.js
> +      fs.existsSync.and.returnValues(true, false);
nice

2017-09-20 21:03 UTC, petebacondarwin commented on aio/tools/ng-packages-installer.spec.js
> +    it('should do nothing is the Angular package is not installed', () => {
should do nothing **if** the Angular package is not installed

2017-09-20 21:05 UTC, petebacondarwin approved these changes
Just a few minor comments/questions but nothing blocking merging. We will need approval from @IgorMinar for the CI script change.

2017-09-23 12:54 UTC, gkalpak commented on aio/tools/examples/example-boilerplate.spec.js
> +const exampleBoilerPlate = require('./example-boilerplate');
Sigh! 😞

2017-09-23 13:30 UTC, gkalpak commented on aio/tools/ng-packages-installer.js
> +const PACKAGES_DIST_DIR = path.join(ROOT_DIR, 'dist/packages-dist');
`resolve` has its issues as well. If you accidentally pass a `/`-prefixed segment, it will ignore all previous segments. So, neither is ideal, but at least there are tests to catch mishaps :smiley:

(Since we are using `canonical-path`, I am actually tempted to change them to `${ROOT_DIR}/packages` and `${ROOT_DIR}/packages-dist` :smiley:)

2017-09-23 13:33 UTC, gkalpak commented on aio/tools/ng-packages-installer.js
> +    const isLocal = fs.existsSync(localFlagFile);
Yeah, it won't be detected. I think it is a reasonable constraint too.

2017-09-23 13:35 UTC, gkalpak commented on aio/tools/ng-packages-installer.js
> +      this._log(`Available Angular packages:\n${packagePrefix}${this.ngPackages.join(`\n${packagePrefix}`)}`);
The fact that there are no packages would be much stranger than the message 😛
But point taken :smiley:

2017-09-23 13:52 UTC, gkalpak commented on aio/tools/ng-packages-installer.js
> +    shelljs.exec(installCmd, {cwd: rootDir});
I checked and it works for our usecase (probably doing an integrity check or something). But I admit there is no guarantee it will not break in a future version :grin:

2017-09-23 13:57 UTC, gkalpak commented on aio/tools/ng-packages-installer.spec.js
> +        expect(warnings[1]).toMatch(restoreCmdRe2);
I find it easier to compare, but happy to move them around :smiley:

2017-09-23 14:12 UTC, gkalpak commented on aio/tools/ng-packages-installer.js
> +      shelljs.rm('-rf', targetPackageDir);
I am not thrilled, but I can live with it.

Generally, I think we will have the same versions of dependencies as the `@angular` packages in our `yarn.lock`, so I don't expect there to be node_modules dirs inside them. What _can_ happen though is the local packages having newer peerDependencies versions than the ones we have currently installed, which might be a problem. But I don't see that happening often and given that I can't think of a good solution I am happy.

2017-09-23 14:23 UTC, mary-poppins commented
You can preview 327f59a at https://pr18722-327f59a.ngbuilds.io/.

2017-09-23 14:28 UTC, gkalpak commented on aio/content/guide/docs-style-guide.md
> -Most guide pages should have [accompanying sample code](#from-code-samples) with
This file contains a lot of trailing whitespace removals. Better to review with `?w=1`.

2017-09-23 14:29 UTC, gkalpak commented
Rebased on master, addressed (most of the) comments and added an extra commit to remove unnecessary `--` from yarn commands.

@petebacondarwin, PTAL

2017-09-23 14:36 UTC, mary-poppins commented
You can preview 6be673d at https://pr18722-6be673d.ngbuilds.io/.

2017-09-24 15:07 UTC, petebacondarwin commented on aio/tools/examples/example-boilerplate.spec.js
> +      ngPackagesInstaller.overwritePackages.and.callFake(() => expect(shelljs.exec).toHaveBeenCalled());
Wot? You don't like `expect(log).toEqual(['first-thing', 'second-thing', 'third-thing`])` approach to checking the order that spies are called?

2017-09-24 15:12 UTC, petebacondarwin commented on aio/tools/ng-packages-installer.js
> +const PACKAGES_DIST_DIR = path.join(ROOT_DIR, 'dist/packages-dist');
> If you accidentally pass a /-prefixed segment, it will ignore all previous segments
More commonly you actually mean to pass a previously resolved path as a later argument, which then gets corrupted by `join`:

```
const myPath1 = path.join(myBase, getPossiblyAbsolutePathToResource());
const myPath2 = path.resolve(myBase, getPossiblyAbsolutePathToResource());

> myPath1 -> /a/b/c/x/y/z
> myPath2 -> /x/y/z
```

2017-09-24 15:17 UTC, petebacondarwin approved these changes
Still approved :-)

2017-09-25 08:20 UTC, gkalpak commented on aio/tools/examples/example-boilerplate.spec.js
> +      ngPackagesInstaller.overwritePackages.and.callFake(() => expect(shelljs.exec).toHaveBeenCalled());
I like that particular line :smiley: I don't like the boilerplate to get there :smiley::

```ts
const log = [];
spy1.and.callFake(() => log.push('spy1'));
spy2.and.callFake(() => log.push('spy2'));
expect(log).toEqual(['spy1', 'spy2']);
expect(spy2).toHaveBeenCalledWith('foo');

// vs

spy2.and.callFake(() => expect(spy1).toHaveBeenCalled());
expect(spy2).toHaveBeenCalledWith('foo');
```

2017-09-25 08:21 UTC, gkalpak commented on aio/tools/ng-packages-installer.js
> +const PACKAGES_DIST_DIR = path.join(ROOT_DIR, 'dist/packages-dist');
> More commonly you actually mean to pass a previously resolved path as a later argument

I never mean to pass previously resolved paths when using `join()` 😛

2017-09-25 08:37 UTC, mary-poppins commented
You can preview 45d133d at https://pr18722-45d133d.ngbuilds.io/.

2017-09-25 12:30 UTC, petebacondarwin commented
Just waiting on @IgorMinar for approval now

2017-09-25 21:34 UTC, mhevery approved these changes

2017-09-25 22:46 UTC, gkalpak commented
Merged as 7a965dc58 and ffceae0a0.

2017-09-25 22:46 UTC, closed without merging