refactor(compiler): make the new ngc API independent of tsickle
angular/angular pull request #18739
Opened 2017-08-16 23:04 UTC by tbosch

Note: The first 3 commits are from https://github.com/angular/angular/pull/18683

2017-08-16 23:16 UTC, mary-poppins commented
You can preview dd769a4 at https://pr18739-dd769a4.ngbuilds.io/.

2017-08-16 23:19 UTC, chuckjaz requested changes

2017-08-16 23:19 UTC, chuckjaz commented on packages/compiler-cli/test/ngc_spec.ts
> -describe('ngc transformer command-line', () => {
remove `f` from `fdescribe`

2017-08-16 23:19 UTC, chuckjaz commented on packages/compiler-cli/src/transformers/program.ts
> +    return emitResult as ER;
This cast should not be necessary as `emitResult` is calls callback a callback with `ER` as a result type.

2017-08-17 00:33 UTC, tbosch commented on packages/compiler-cli/test/ngc_spec.ts
> -describe('ngc transformer command-line', () => {
Done.

2017-08-17 00:34 UTC, tbosch commented on packages/compiler-cli/src/transformers/program.ts
> +    return emitResult as ER;
I thought about it more after out discussion, and you were right that it is possible to do without: I created a function overload for
- the version where no `emitCallback` is passed and which always returns a `ts.EmitResult`
- the version where a `emitCallback` is passed and which uses the generic.

2017-08-17 00:40 UTC, chuckjaz approved these changes

2017-08-17 00:42 UTC, chuckjaz commented
Looks like you need to fix the compiler errors, however.

2017-08-17 00:49 UTC, mary-poppins commented
You can preview 8f04da6 at https://pr18739-8f04da6.ngbuilds.io/.

2017-08-17 00:58 UTC, mary-poppins commented
You can preview af6d596 at https://pr18739-af6d596.ngbuilds.io/.

2017-08-17 01:20 UTC, mary-poppins commented
You can preview 770d650 at https://pr18739-770d650.ngbuilds.io/.

2017-08-17 14:44 UTC, mary-poppins commented
You can preview 07c572d at https://pr18739-07c572d.ngbuilds.io/.

2017-08-17 15:56 UTC, mary-poppins commented
You can preview 2fd2b25 at https://pr18739-2fd2b25.ngbuilds.io/.

2017-08-17 16:52 UTC, chuckjaz approved these changes

2017-08-17 16:52 UTC, chuckjaz commented on packages/compiler/test/core_spec.ts
> +function compareMetadataValue(a: any, b: any) {
nit: using "metadata" here is a bit confusing as it not the way the term metadata is used everywhere else (i.e. the content of a decorator or derived from type information).

Consider "shape" instead of "metadata" as you are testing the runtime shape of the instance.

2017-08-17 16:52 UTC, chuckjaz commented on packages/compiler/test/core_spec.ts
> +  return Object.keys(a).filter(prop => prop !== 'ngMetadataName').sort();
Consider filtering "_" prefix fields as well (using that as a runtime indicator as private) as we might want to add a private member to one of these classes in the future.

2017-08-17 16:53 UTC, mary-poppins commented
You can preview 829489a at https://pr18739-829489a.ngbuilds.io/.

2017-08-17 16:55 UTC, chuckjaz commented on packages/compiler/test/core_spec.ts
> +function typeExtends<T1 extends T2, T2>() {}
Trivia: this type of test is called a type trait test. In C++ this can be made into a function that only returns true if the constraint is true.

2017-08-17 20:31 UTC, tbosch commented on packages/compiler/test/core_spec.ts
> +function compareMetadataValue(a: any, b: any) {
Done

2017-08-17 20:31 UTC, tbosch commented on packages/compiler/test/core_spec.ts
> +  return Object.keys(a).filter(prop => prop !== 'ngMetadataName').sort();
Done

2017-08-17 20:32 UTC, tbosch commented on packages/compiler/test/core_spec.ts
> +function typeExtends<T1 extends T2, T2>() {}
Ah, cool!

2017-08-17 21:18 UTC, mary-poppins commented
You can preview b9584be at https://pr18739-b9584be.ngbuilds.io/.

2017-08-18 06:20 UTC, closed without merging