Added ability to pass relativeTo to routerLink
angular/angular pull request #18771
Opened 2017-08-18 09:17 UTC by eyalhakim

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines:  https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
**didn't read this before committing, how do i fix?**

- [ ] Tests for the changes have been added (for bug fixes / features)
**couldn't find tests for routerLink whatsoever**

- [ ] Docs have been added / updated (for bug fixes / features)
**where are the relevant docs located?**

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

routerLink directive always navigate relatively to the current activated route
Issue Number: N/A

## What is the new behavior?
routerLink is now able to navigate relatively to other routes

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-03-16 18:01 UTC, splincode commented
@eyalhakim what is the status of your pull request? is it still relevant?

2018-03-16 18:39 UTC, eyalhakim commented
Sure, it's still not implemented as far as I know.

2018-07-17 07:30 UTC, markgolding commented
What is the timeline to getting this implemented really need this feature.

2018-10-09 22:53 UTC, jasonaden commented
Sorry this has sat so long. We've reviewed our process and are trying to pick up some of these long-standing PRs to get them addressed.

That being said, can you please provide a few things so this can be merged:

* Because this is adding a new public API, we need to have some documentation for the feature. Take a look at the comment block above your change and you can add some documentation there.
* We need to have some tests for this change. You can take a look at the other [`routerLink` tests here](https://github.com/angular/angular/blob/master/packages/router/test/integration.spec.ts#L1458) for examples.
* Rebase to current Angular.

2018-10-16 22:12 UTC, jasonaden requested changes

2018-10-16 22:12 UTC, jasonaden commented on packages/router/src/directives/router_link.ts
> +  @Input() relativeTo: ActivatedRoute;
This needs documentation.

2018-10-16 22:12 UTC, jasonaden commented on packages/router/src/directives/router_link.ts
> +  @Input() relativeTo: ActivatedRoute;
Also a test to confirm it works.

2020-06-01 23:03 UTC, closed without merging