feat(platform-server): Provide a DOM implementation on the server
angular/angular pull request #18822
Opened 2017-08-22 09:08 UTC by vikerman

Fixes #14638

Uses Domino - https://github.com/fgnass/domino and removes dependency on
Parse5.

The DOCUMENT and nativeElement were never typed earlier and were
different on the browser(DOM nodes) and the server(Parse5 nodes). With
this change, platform-server also exposes a DOCUMENT and nativeElement
that is closer to the client.

Removes the need to add services for each and every Document
manipulation like Title/Meta etc.

This does *not* provide a global variable 'document' or 'window' on the
server. You still have to inject DOCUMENT to get the document backing
the current platform server instance.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2017-08-22 09:15 UTC, mary-poppins commented
You can preview 4fa4f6c at https://pr18822-4fa4f6c.ngbuilds.io/.

2017-08-22 19:36 UTC, mary-poppins commented
You can preview 26fdff0 at https://pr18822-26fdff0.ngbuilds.io/.

2017-08-22 19:43 UTC, mary-poppins commented
You can preview bc20f92 at https://pr18822-bc20f92.ngbuilds.io/.

2017-08-22 21:12 UTC, mhevery requested changes

2017-08-22 21:12 UTC, mhevery commented on packages/platform-browser/testing/src/browser_util.ts
> +  getDOM().dispatchEvent(element, getDOM().createEvent(eventType, defaultDoc));
`element.ownerDocument`

2017-08-22 21:12 UTC, mhevery commented on packages/platform-browser/testing/src/browser_util.ts
> +      getDOM().content(getDOM().createTemplate(html, defaultDoc)));
`getDOM().getDefaultDoc`

2017-08-23 00:29 UTC, mary-poppins commented
You can preview 88e69ca at https://pr18822-88e69ca.ngbuilds.io/.

2017-08-23 18:50 UTC, mary-poppins commented
You can preview 4861762 at https://pr18822-4861762.ngbuilds.io/.

2017-08-23 19:05 UTC, mary-poppins commented
You can preview 3191a33 at https://pr18822-3191a33.ngbuilds.io/.

2017-08-23 20:45 UTC, mhevery commented on packages/platform-browser/test/animation/animation_renderer_spec.ts
> +  describe('flushing animations', () => {
find out what is going on here with all of the removals and additions.

2017-08-23 20:45 UTC, mhevery commented on packages/platform-server/src/domino_adapter.ts
> +  isTextNode(node: any): boolean { return node.nodeType === TEXT_NODE; }
Can we use `Document.TEXT_NODE`

2017-08-23 20:45 UTC, mhevery commented on packages/platform-server/src/domino_adapter.ts
> +  isCommentNode(node: any): boolean { return node.nodeType === COMMENT_NODE; }
Can we use `Document.COMMENT_NODE`

2017-08-23 20:45 UTC, mhevery commented on packages/platform-server/src/domino_adapter.ts
> +  isElementNode(node: any): boolean { return node ? node.nodeType === ELEMENT_NODE : false; }
Can we use `Document.ELEMENT_NODE`

2017-08-23 20:45 UTC, mhevery commented on packages/platform-server/src/domino_adapter.ts
> +const TEXT_NODE = 3;
Remove the constants

2017-08-23 20:57 UTC, mary-poppins commented
You can preview a98eb41 at https://pr18822-a98eb41.ngbuilds.io/.

2017-08-23 21:57 UTC, mary-poppins commented
You can preview 4af9b7f at https://pr18822-4af9b7f.ngbuilds.io/.

2017-08-23 22:02 UTC, gdi2290 commented on packages/platform-server/src/domino_adapter.ts
> +let defaultDoc: Document|null = null;
we can't do this without running into concurrency issues (two requests with async http calls same document)

2017-08-23 22:49 UTC, vikerman commented on packages/platform-server/src/domino_adapter.ts
> +let defaultDoc: Document|null = null;
Used only for tests.

2017-08-24 00:02 UTC, mary-poppins commented
You can preview aeffc6f at https://pr18822-aeffc6f.ngbuilds.io/.

2017-08-24 00:06 UTC, mary-poppins commented
You can preview d7dac9a at https://pr18822-d7dac9a.ngbuilds.io/.

2017-08-24 03:53 UTC, mary-poppins commented
You can preview d1c87db at https://pr18822-d1c87db.ngbuilds.io/.

2017-08-24 22:31 UTC, mhevery approved these changes

2017-08-28 21:50 UTC, mary-poppins commented
You can preview 006ca59 at https://pr18822-006ca59.ngbuilds.io/.

2017-08-29 18:26 UTC, mary-poppins commented
You can preview d5bf62c at https://pr18822-d5bf62c.ngbuilds.io/.

2017-08-29 21:40 UTC, mary-poppins commented
You can preview 851bb9c at https://pr18822-851bb9c.ngbuilds.io/.

2017-08-31 16:55 UTC, jasonaden commented
Merged

2017-08-31 16:55 UTC, closed without merging