test: support debugging unit tests in node
angular/angular pull request #18987
Opened 2017-08-31 21:07 UTC by petebacondarwin

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2017-08-31 21:12 UTC, mhevery requested changes

2017-08-31 21:12 UTC, mhevery commented on test.sh
> +  node dist/tools/tsc-watch/ $1 watch $2
update line 9 with [--debug] as option

2017-08-31 21:12 UTC, mhevery commented on tools/tsc-watch/index.ts
> +    .concat(debugMode ? ['--inspect'] : [])
don't you also want `--debug-brk` here?

2017-08-31 21:12 UTC, mhevery commented on test.sh
> +  node dist/tools/tsc-watch/ $1 watch $2
Also please add `docs/DEBUG.md` file

2017-08-31 21:14 UTC, petebacondarwin commented on tools/tsc-watch/index.ts
> +    .concat(debugMode ? ['--inspect'] : [])
`--debug-brk` causes the processing to stop immediately, which in practice is not that helpful, since it is in the middle of the jasmine library. It is nicer to add a `debugger` statement to your code, so that it only stops there first.

2017-08-31 21:15 UTC, petebacondarwin commented on test.sh
> +  node dist/tools/tsc-watch/ $1 watch $2
will do

2017-08-31 21:44 UTC, petebacondarwin commented on test.sh
> +  node dist/tools/tsc-watch/ $1 watch $2
done

2017-09-01 03:53 UTC, mhevery commented on tools/tsc-watch/index.ts
> +    .concat(debugMode ? ['--inspect'] : [])
my understanding is that `debugger` statement is a noop if the debugger is not connected. The problem is that if the tests finished before you have time to connect the debugger than you will not be able to debug the test. For example if you put `fit` on the test that the test will finish before you have time to connect the debugger, even if you plate the `debugger` statement.

2017-09-01 06:14 UTC, petebacondarwin commented on tools/tsc-watch/index.ts
> +    .concat(debugMode ? ['--inspect'] : [])
If you are using Chrome as the debugger then this is not a problem. You open up the dev tools before running the tests and it auto attaches when the test is run. I have tested this (and used it in my own debugging). I have  not tried it with the Visual Code debugger.

Moreover, if the debugger misses the first run then it is very simply to open any source file and hit Save, which will trigger a new test run.

My understanding, also, is that `--debug-brk` has no effect if the debugger is not attached as well, so there would be no benefit in adding this in for the use case you give.

By the way, the latest node supports `--inspect-brk` (see https://nodejs.org/en/docs/inspector/) but this doesn't seem to work on node 6.

Why don't you give it a try and then come back to me if you find it unworkable?

2017-09-01 18:58 UTC, mhevery commented on tools/tsc-watch/index.ts
> +    .concat(debugMode ? ['--inspect'] : [])
SGTM

2017-09-01 18:59 UTC, mhevery approved these changes

2017-09-01 21:27 UTC, closed without merging