fix(platform-browser): simple version of zone aware addEventListener
angular/angular pull request #18993
Opened 2017-09-01 11:31 UTC by JiaLiPassion

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 18753

## What is the new behavior?

EventHandler will run into the correct zone which will be the zone when `addEventListener` is invoked

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Add a simple version of zone aware addEventListener.

1. create a `globalEventHandler` to handle all events to avoid creating to many closure function.
2. keep `zone` when `addEventListener`, but for better performance, we don't use `zone.js` mechanism to `scheduleEventTask`, so `ZoneSpec.onInvokeTask`, `ZoneSpec.onScheduleTask`, `ZoneSpec.onCancelTask` will not be invoked.
3. when call `addEventListener`, if the `Zone.current` is `ngZone`, we just use `native addEventListener` for better performance (which will be the most cases).

@mhevery , please review.

2017-09-01 19:10 UTC, mhevery requested changes

2017-09-01 19:10 UTC, mhevery commented on packages/platform-browser/src/dom/events/dom_events.ts
> +  return blackListedEvents.filter(blackListedEvent => blackListedEvent === eventName).length > 0;
Could we turn the events into map. Calling `filter` all the time has negative perf implication. This would be faster. `blackListMap.hasOwnProperty(eventName)`

2017-09-01 19:10 UTC, mhevery commented on packages/platform-browser/src/dom/events/dom_events.ts
> +    const isBlackListed = isBlackListedEvent(eventName);
PERF: We should delay checking if it is black-listed until after we know we have Zone.

2017-09-02 02:09 UTC, JiaLiPassion commented on packages/platform-browser/src/dom/events/dom_events.ts
> +  return blackListedEvents.filter(blackListedEvent => blackListedEvent === eventName).length > 0;
@mhevery , got it, I will use map to check.

2017-09-02 02:09 UTC, JiaLiPassion commented on packages/platform-browser/src/dom/events/dom_events.ts
> +    const isBlackListed = isBlackListedEvent(eventName);
@mhevery , ok, I will check it after `zoneJsLoaded` is true.

2017-09-02 02:18 UTC, JiaLiPassion commented
@mhevery , I have updated the commits.

1. use `blackListedMap` to check eventName is `blackListed` or not.
2. check `isBlackListedEvent` after `zoneJsLoaded` is true.
3. add test cases for add multiple listeners and add duplicate listener.

please review.

2017-09-02 04:05 UTC, mhevery requested changes

2017-09-02 04:05 UTC, mhevery commented on packages/platform-browser/src/dom/events/dom_events.ts
> +const blackListedMap: {[key: string]: string} = Zone && Zone[__symbol__('BLACK_LISTED_EVENTS')];
Sorry I meant that you would convert the array into the map, rather than expect that the data is provided as a map.

2017-09-02 04:27 UTC, JiaLiPassion commented on packages/platform-browser/src/dom/events/dom_events.ts
> +const blackListedMap: {[key: string]: string} = Zone && Zone[__symbol__('BLACK_LISTED_EVENTS')];
@mhevery , got it, sorry for misunderstanding, I will modify it now.

2017-09-02 05:00 UTC, JiaLiPassion commented
@mhevery , I have updated the source and write a sample code to describe how to set `blackListedEvents` for both `addEventListener` and `onProperties`, maybe we should document this somewhere. 

Please review.

2017-09-02 06:04 UTC, mhevery approved these changes

2017-09-05 05:26 UTC, JiaLiPassion commented
@mhevery , I found a bug which is the same one with https://github.com/angular/zone.js/pull/839, I will fix it and update the PR.

2017-09-06 03:18 UTC, closed without merging

2017-09-15 06:54 UTC, PierreDuc commented
Little late to the party, but doesn't the introduction of a `globalEventHandler` introduce a regression with using `stopImmediatePropagation`. This won't work anymore, because all the handlers on the same element will be called regardless. I also see issues once it's possible to add event options like `capture`, `passive` and definitely `once`.

2017-09-15 07:03 UTC, JiaLiPassion commented
@PierreDuc , could you post some sample code or reproduce repo to describe the issue?

2017-09-15 07:37 UTC, PierreDuc commented
I guess sample code will be fine:

Let's say your `AppComponent` has this template:

```
<app-foo></app-foo>
<app-foo></app-foo>
```

And your `FooComponent` looks like this:

```
@Component({
  selector: 'app-foo',
  template: ``
})
export class FooComponent {
 
  @HostListener('document:click', ['$event'])
  public onClick(event: MouseEvent): void {
      console.log('document has been clicked');
      event.stopImmediatePropagation();
  }

}
```

Then even though you call `stopImmediatePropagation`, the listener is called twice. I would expect only the first listener to be called.

2017-09-15 07:45 UTC, JiaLiPassion commented
@PierreDuc , got it, thank you, I can fix this one.