feat(compiler): deprecate i18n comments in favor of `ng-container`
angular/angular pull request #18998
Opened 2017-09-01 15:57 UTC by ocombe

## PR Type
What kind of change does this PR introduce?
```
[x] Feature
```

## What is the current behavior?
I18n comments require a lot of code to work, it's a big effort to maintain and it can easily be replaced by `<ng-container i18n></ng-container>`

## What is the new behavior?
I18n comments have been deprecated and will print a warning in dev mode

## Does this PR introduce a breaking change?
```
[x] No
```

2017-09-01 16:02 UTC, ocombe commented on packages/compiler/src/i18n/extractor_merger.ts
> +   * @deprecated from v5 you should use <ng-container i18n> instead of i18n comments
I wasn't sure where to put the deprecated tag, I guess here is as good as any

2017-09-01 16:11 UTC, mary-poppins commented
You can preview 1242c28 at https://pr18998-1242c28.ngbuilds.io/.

2017-09-01 16:36 UTC, vicb commented on packages/compiler/src/i18n/extractor_merger.ts
> +import {warnOnlyOnce} from '../template_parser/template_parser';
no.
either refactor it to have it at a sensible place or copy it.
I have a preference for the later until we have a better logging/deprecation story. And yes I would love for someone to work on it.

2017-09-01 16:38 UTC, vicb commented on packages/compiler/src/i18n/extractor_merger.ts
> +                         .filter(warnOnlyOnce([I18N_COMMENTS_WARNING]));
Why would warnings always be i18n comments ?

2017-09-01 16:39 UTC, vicb commented on packages/compiler/src/i18n/extractor_merger.ts
> +   * @deprecated from v5 you should use <ng-container i18n> instead of i18n comments
`visitComment` is not deprecated.
Remove `@deprecated` on the method add a `// deprecated` comment in the code

2017-09-01 16:40 UTC, vicb commented on packages/compiler/src/i18n/extractor_merger.ts
> +          if (isDevMode()) {
check if it is the first time we hit the if clause and warn there. No need for `warnOnlyOnce` and pushing warnings.

2017-09-01 16:41 UTC, vicb commented on packages/compiler/src/i18n/parse_util.ts
> +import {ParseError, ParseErrorLevel, ParseSourceSpan} from '../parse_util';
revert

2017-09-01 16:42 UTC, vicb commented on packages/compiler/src/template_parser/template_parser.ts
> +export function warnOnlyOnce(warnings: string[]): (warning: ParseError) => boolean {
revert

2017-09-01 16:42 UTC, vicb requested changes
- see inline comments
- add DEPRACTIONS in the commit body with BEFORE/ACTION code snippet. 
Thanks

2017-09-01 17:35 UTC, mary-poppins commented
You can preview 9131eaf at https://pr18998-9131eaf.ngbuilds.io/.

2017-09-01 18:09 UTC, juleskremer approved these changes
lgtm

2017-09-01 18:12 UTC, mary-poppins commented
You can preview a7e4cec at https://pr18998-a7e4cec.ngbuilds.io/.

2017-09-05 16:40 UTC, vicb commented on packages/compiler/src/i18n/extractor_merger.ts
> +                ` I18n comments are deprecated, use an <ng - container> element instead (${comment.sourceSpan.start}${details})`);
Any reason for the WS in `<ng - container>` ?

2017-09-05 16:40 UTC, vicb commented on packages/compiler/test/i18n/extractor_merger_spec.ts
> +      it('should console.warn if we use i18n comments', () => {
remove this test (no assertion, useless)

2017-09-05 16:41 UTC, vicb requested changes
see inline comments

2017-09-05 16:43 UTC, ocombe commented on packages/compiler/src/i18n/extractor_merger.ts
> +                ` I18n comments are deprecated, use an <ng - container> element instead (${comment.sourceSpan.start}${details})`);
hu no sorry, mistake

2017-09-05 17:41 UTC, mary-poppins commented
You can preview c8b3dec at https://pr18998-c8b3dec.ngbuilds.io/.

2017-09-05 17:46 UTC, vicb approved these changes

2017-09-05 17:57 UTC, mary-poppins commented
You can preview 1bb6e44 at https://pr18998-1bb6e44.ngbuilds.io/.

2017-09-05 18:31 UTC, vicb commented
@ocombe please check what is wrong with Travis

2017-09-05 19:05 UTC, mary-poppins commented
You can preview bb3762b at https://pr18998-bb3762b.ngbuilds.io/.

2017-09-06 03:18 UTC, closed without merging