build(aio): auto-link more code items
angular/angular pull request #19109
Opened 2017-09-08 15:14 UTC by petebacondarwin

I looked at various ways to achieve this but it is not possible to know until after
rendering exactly what code is going to be on the page.
So I opted for post-processing the HTML, effectively expanding what we were doing
for simple code elements already to parse through the text of all `code`, `code-example`
and `code-pane` elements for potentially matching code items.
This means that we could accidentally get a false positive but a quick anecdotal survey
of the docs hasn't found any so far.

2017-09-08 15:27 UTC, mary-poppins commented
You can preview 52599ff at https://pr19109-52599ff.ngbuilds.io/.

2017-09-08 16:56 UTC, gkalpak requested changes
OMG!!! This is huge 💯 💯 💯 

One thing: Could we update the styling of hovered links inside `code-example`/`code-pane` elements (e.g. underline).

2017-09-08 16:56 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.spec.js
> +fdescribe('autoLinkCode post-processor', () => {
😱

2017-09-08 16:56 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +                const nodes = textContent(node).split(/([A-Za-z0-9]+)/)
OOC, do we need `textContent()` here (given we are visiting `text` nodes)?

##
AFAICT, `.split(/[^A-Za-z0-9]+/)` would work too (and is marginally more straight forward :grin:).
BTW, I would expect including `_` too. Was is left out on purpose?

2017-09-08 16:56 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +                      const previous = nodes[node.length];
Why `nodes[node.length]`??? What do I miss?

2017-09-08 21:41 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +                      const previous = nodes[node.length];
oops, `length-1` I think.

2017-09-09 08:01 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +                const nodes = textContent(node).split(/([A-Za-z0-9]+)/)
@gkalpak your regex doesn't work because you then lose the whitespace:

```
> 'a b c'.split(/([a-z])/)
[ '', 'a', ' ', 'b', ' ', 'c', '' ]
> 'a b c'.split(/[^a-z]/)
[ 'a', 'b', 'c' ]
```

2017-09-09 08:03 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +                      const previous = nodes[node.length];
I realise that we don't  actually need to join up these text nodes as at the end of the postProcessing we just render the AST back to an HTML string. So we can just push new text nodes.

2017-09-09 08:04 UTC, petebacondarwin commented
I'll add some new CSS but that is venturing into wild places I fear to tread!

2017-09-09 08:15 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +                const nodes = textContent(node).split(/([A-Za-z0-9]+)/)
Yeah, I thought you didn't need them. I know realize you need all "tokens" :grin:

2017-09-09 08:26 UTC, mary-poppins commented
You can preview 53897a8 at https://pr19109-53897a8.ngbuilds.io/.

2017-09-09 08:28 UTC, gkalpak approved these changes

2017-09-09 08:28 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.spec.js
> +    const doc = { docType: 'test-doc', renderedContent: '<code>myFunc() {\n  return new MyClass(MY_CONST));\n}</code>' };
Extra closing `)` 😛

2017-09-09 09:41 UTC, mary-poppins commented
You can preview eac48ac at https://pr19109-eac48ac.ngbuilds.io/.

2017-09-12 18:08 UTC, matsko commented
Landed as 9ab9437319987a251e1b1104402acd0cc474a907 and 9d93c859d7791fb16c216ff95265c58ba1000c5a

2017-09-12 18:08 UTC, closed without merging