feat(upgrade): add testability hook to downgraded component
angular/angular pull request #19114
Opened 2017-09-08 21:51 UTC by qiyigg

Add testability hook to downgraded component so that protractor can wait for asynchronous call to complete.
Add unregisterApplication() and unregisterAllApplications() to testability registry for cleaning up testability and unit test.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2017-09-08 23:12 UTC, mhevery requested changes

2017-09-08 23:12 UTC, mhevery commented on packages/core/src/testability/testability.ts
> +  unregisterApplication(token: any) { this._applications.delete(token); }
Since this is a public API we need to have proper API docs. Please add them here. (ideally add them to the whole class)

2017-09-09 05:42 UTC, gkalpak commented on packages/upgrade/src/common/downgrade_component_adapter.ts
> +    }
I am not very familiar with Testability and co, but I wonder why this is necessary here. When using `UpgradeModule`, we [wire up the testabilities][1] and it was supposed to be enough (we don't do it for `downgradeModule()` yet, but it is on the roadmap).

Would this still be necessary once we wired up the testabilities on `downgradeModule()`?

[1]: https://github.com/qiyigg/angular/blob/1e8a98185d58f95c52b6b4c0376dd8c9d71afa97/packages/upgrade/src/static/upgrade_module.ts#L171-L250

2017-09-11 18:38 UTC, mhevery approved these changes

2017-09-11 22:13 UTC, vikerman commented on packages/upgrade/src/common/downgrade_component_adapter.ts
> +    }
Discussed offline. We are going with having separate testabilities for Angular and AngularJS and changing Protractor to wait for both of them each time.

2017-09-18 19:46 UTC, vikerman commented
Merged with https://github.com/angular/angular/commit/97cc6caa33912b4534773563bc2ff19bebbf3644

2017-09-18 19:46 UTC, closed without merging