docs(aio): fix weird text
angular/angular pull request #19132
Opened 2017-09-10 21:40 UTC by maxime1992

2017-09-11 09:42 UTC, gkalpak commented on aio/content/guide/reactive-forms.md
> +but it does facilitate the reactive programming approach.
How is this text weird?

2017-09-11 09:43 UTC, gkalpak commented on aio/content/guide/reactive-forms.md
>  Using reactive form directives does not require you to follow all reactive priniciples,
While you're at it:
_priniciples_ --> _principles_

2017-09-11 10:13 UTC, maxime1992 commented on aio/content/guide/reactive-forms.md
> +but it does facilitate the reactive programming approach.
Well it seems that it's a way to speak in english that I'm not used to so maybe this PR doesn't make sense!

2017-09-11 10:44 UTC, gkalpak commented on aio/content/guide/reactive-forms.md
> +but it does facilitate the reactive programming approach.
Maybe adding a comma before `should` would make it more easy to read (but I am not a native speaker, so I am not sure if it syntactically correct :grin:).

2017-11-28 14:48 UTC, petebacondarwin requested changes

2017-11-28 14:48 UTC, petebacondarwin commented on aio/content/guide/reactive-forms.md
> +but it does facilitate the reactive programming approach.
I think a comma is adequate here; and a fix to the `priniciples` typo above.

2018-01-05 21:45 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +but it does facilitate the reactive programming approach.
I agree with @petebacondarwin on both points. The phrase "...should you choose to use it" is standard English, though it is an advanced construction, which might be difficult for non-native speakers.

For the grammatically curious, this is a construction using inversion and an omission of the conditional "if". "Should" is an example of the subjunctive mood (conditional tense of "shall"). For more info, checkout these Wikipedia entries:

[English Conditional Sentences](https://en.wikipedia.org/wiki/English_conditional_sentences#Inversion_in_condition_clauses)

[Inversion and the Subjunctive](https://en.wikipedia.org/wiki/English_subjunctive#Inversion)

So, I like the comma, which allows the "should" phrase to stay. However, we could clarify it for non-native speakers with something like this:

> ...the reactive programming approach, if you were to use it.

Thoughts?

2018-08-02 18:28 UTC, brandonroberts commented
Closing as outdated since the reactive forms guide has been rewritten.

2018-08-02 18:28 UTC, closed without merging