fix(animations): properly support boolean-based transitions and state changes
angular/angular pull request #19279
Opened 2017-09-19 21:27 UTC by matsko

2017-09-19 21:42 UTC, mary-poppins commented
You can preview c809202 at https://pr19279-c809202.ngbuilds.io/.

2017-09-20 16:06 UTC, mhevery requested changes

2017-09-20 16:06 UTC, mhevery commented on packages/animations/browser/src/render/transition_animation_engine.ts
> +  return value != null ? value : null;
???

`value != null ? value : null` 
should be same as:
`value == null ? null : value`
which should be same as 
`value`

Am I missing something?

2017-09-20 16:06 UTC, mhevery commented on packages/animations/browser/src/dsl/animation_transition_expr.ts
> +TRUE_BOOLEAN_VALUES.add('1');
why is `1` as true? Usually everything which is not `false` is true.

2017-09-20 16:19 UTC, devoto13 commented on packages/animations/browser/src/render/transition_animation_engine.ts
> +  return value != null ? value : null;
Note "not strict" comparison. It will convert `undefined` to `null` as well. I.e.

if value is undefined -> null
if value is null -> null
else -> value

2017-10-04 22:20 UTC, matsko commented on packages/animations/browser/src/render/transition_animation_engine.ts
> +  return value != null ? value : null;
add a comment.

2017-10-04 22:22 UTC, matsko commented on packages/animations/browser/src/dsl/animation_transition_expr.ts
> +TRUE_BOOLEAN_VALUES.add('1');
add documentation to the `trigger` docs

2017-10-05 18:47 UTC, mary-poppins commented
You can preview f39d479 at https://pr19279-f39d479.ngbuilds.io/.

2017-10-05 21:16 UTC, mary-poppins commented
You can preview 3295c6a at https://pr19279-3295c6a.ngbuilds.io/.

2017-10-05 21:41 UTC, mhevery approved these changes

2017-10-06 23:21 UTC, closed without merging

2017-10-11 20:50 UTC, chuckjaz commented
@matsko This PR does not apply cleanly on 4.4.x. Can you create a 4.4.x PR with these changes?