docs(aio): document Custom Async validators
angular/angular pull request #19409
Opened 2017-09-26 15:01 UTC by karptonite

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

I spent a while debugging an Async validator that emitted the correct result but never completed. I hope that this addition to the docs will save other developers from falling into that trap. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2017-10-03 18:54 UTC, kapunahelewong requested changes
@karptonite Thanks for this. I have a couple of editorial suggestions. Let me know your thoughts.

2017-10-03 18:54 UTC, kapunahelewong commented on aio/content/guide/form-validation.md
> +Custom Async validators are similar to Sync validators, but they must instead return a Promise or Observable
Could you make these lowercase:

Async --> async 
Sync --> sync

2017-10-03 18:54 UTC, kapunahelewong commented on aio/content/guide/form-validation.md
> +
How about this?: 

"In the case of an Observable, the Observable must complete, at which point the form uses the last value emitted for validation."

Does that still carry your intent?

2017-10-03 19:07 UTC, karptonite commented
@kapunahelewong Sounds good--I've incorporated your suggestions to the pull request.

2017-10-03 19:13 UTC, kapunahelewong approved these changes

2017-10-04 14:16 UTC, kapunahelewong commented
@karptonite Looks great. Would you mind squashing? :)

2017-10-04 15:07 UTC, karptonite commented
@kapunahelewong squashed.

2017-10-04 15:10 UTC, kapunahelewong commented
@juleskremer This is ready for your review. Thank you!

2017-10-04 16:38 UTC, juleskremer approved these changes

2017-10-04 22:07 UTC, merged