Make incremental mode in ngc faster
angular/angular pull request #19487
Opened 2017-09-29 22:03 UTC by tbosch

2017-09-29 22:13 UTC, mary-poppins commented
You can preview e36857b at https://pr19487-e36857b.ngbuilds.io/.

2017-09-29 23:32 UTC, mary-poppins commented
You can preview 27abe31 at https://pr19487-27abe31.ngbuilds.io/.

2017-09-29 23:40 UTC, tbosch commented
Also: make the number of max files before we do a full emit a top level constant

2017-09-29 23:49 UTC, chuckjaz requested changes

2017-09-29 23:49 UTC, chuckjaz commented on packages/compiler/src/aot/generated_file.ts
> +    return o.areAllEquivalent(this.stmts !, other.stmts !);
consider `if ((this.stmts == null)  != (other.stmts == null)) { return false; }` and prefixing the this line with `this.stmts != null`

2017-09-29 23:49 UTC, chuckjaz commented on packages/compiler/src/output/output_ast.ts
> +  isEquivalent(e: Expression): boolean { return e instanceof ReadVarExpr && this.name === e.name; }
`builtIn`?

2017-09-29 23:49 UTC, chuckjaz commented on packages/compiler/src/output/output_ast.ts
> +    return e instanceof WriteKeyExpr && this.index.isEquivalent(e.index) &&
`receiver`?

2017-09-29 23:49 UTC, chuckjaz commented on packages/compiler/src/output/output_ast.ts
>    constructor(public value: any, type?: Type|null, sourceSpan?: ParseSourceSpan|null) {
Consider changing this to `number|string|boolean|null|undefined` to make it clear the comparison below works.

2017-09-29 23:49 UTC, chuckjaz commented on packages/compiler/src/output/output_ast.ts
> +        this.value.moduleName === e.value.moduleName && this.value.runtime === e.value.runtime;
source `ExternalRefernce` have an `isEquivialent`?

2017-09-29 23:49 UTC, chuckjaz commented on packages/compiler/src/output/output_ast.ts
> +    return e instanceof FunctionExpr && areAllEquivalent(this.statements, e.statements);
`params`?

2017-09-29 23:49 UTC, chuckjaz commented on packages/compiler/src/output/output_ast.ts
> +    return stmt instanceof DeclareFunctionStmt &&
`params`?

2017-09-29 23:49 UTC, chuckjaz commented on packages/compiler/src/output/output_ast.ts
> +    return stmt instanceof ClassStmt && this.name === stmt.name &&
`fields`?
`parent`?

2017-09-30 00:18 UTC, tbosch commented on packages/compiler/src/output/output_ast.ts
> +        this.value.moduleName === e.value.moduleName && this.value.runtime === e.value.runtime;
No, we use it more as an interface. Changing to an actual interface.

2017-09-30 00:35 UTC, tbosch commented on packages/compiler/src/aot/generated_file.ts
> +    return o.areAllEquivalent(this.stmts !, other.stmts !);
Done

2017-09-30 00:36 UTC, tbosch commented on packages/compiler/src/output/output_ast.ts
> +  isEquivalent(e: Expression): boolean { return e instanceof ReadVarExpr && this.name === e.name; }
Done

2017-09-30 00:36 UTC, tbosch commented on packages/compiler/src/output/output_ast.ts
> +    return e instanceof WriteKeyExpr && this.index.isEquivalent(e.index) &&
Done

2017-09-30 00:37 UTC, tbosch commented on packages/compiler/src/output/output_ast.ts
>    constructor(public value: any, type?: Type|null, sourceSpan?: ParseSourceSpan|null) {
Done

2017-09-30 00:38 UTC, tbosch commented on packages/compiler/src/output/output_ast.ts
> +        this.value.moduleName === e.value.moduleName && this.value.runtime === e.value.runtime;
Actually, this is used in a ton of places. Adding a comment for now that we also use it as an interface.

2017-09-30 00:39 UTC, tbosch commented on packages/compiler/src/output/output_ast.ts
> +    return e instanceof FunctionExpr && areAllEquivalent(this.statements, e.statements);
Done

2017-09-30 00:39 UTC, tbosch commented on packages/compiler/src/output/output_ast.ts
> +    return stmt instanceof DeclareFunctionStmt &&
Done

2017-09-30 00:41 UTC, tbosch commented on packages/compiler/src/output/output_ast.ts
> +    return stmt instanceof ClassStmt && this.name === stmt.name &&
Done

2017-09-30 00:55 UTC, mary-poppins commented
You can preview f533563 at https://pr19487-f533563.ngbuilds.io/.

2017-09-30 03:00 UTC, chuckjaz approved these changes

2017-10-02 05:01 UTC, mary-poppins commented
You can preview 1afb65c at https://pr19487-1afb65c.ngbuilds.io/.

2017-10-02 14:07 UTC, mary-poppins commented
You can preview a40c2d0 at https://pr19487-a40c2d0.ngbuilds.io/.

2017-10-02 15:12 UTC, IgorMinar approved these changes

2017-10-02 15:24 UTC, merged