feat(core): add source to `StaticInjectorError` message [WIP]
angular/angular pull request #19482
Opened 2017-09-29 14:14 UTC by ocombe

## PR Type
What kind of change does this PR introduce?

```
[x] Feature
```

## What is the current behavior?
We need more info on `StaticInjectorError` to help with debugging

Issue Number: #19302

## What is the new behavior?
We add the source component (or module) that tried to inject the missing provider, and we also add the source from the injector which triggered the error

Notes:
- I couldn't get the name of the module containing the component with the failing injector, only the name of the main module (that created the injector).
- I added a property on tokens named `__source`, we could use a different property name (I wasn't inspired), but I'm not sure if it's ok to add a property name like that.
- I'm not sure if adding "Platform: core" for the root injector is really useful, I could remove it

## Does this PR introduce a breaking change?
```
[x] No
```

2017-09-29 14:28 UTC, mary-poppins commented
You can preview a888e1f at https://pr19482-a888e1f.ngbuilds.io/.

2017-10-20 04:54 UTC, mhevery requested changes

2017-10-20 04:54 UTC, mhevery commented on packages/core/src/di/injector.ts
> +  static create(providers: StaticProvider[], parent?: Injector, source?: string): Injector {
I am concerned that this will get long. I think we should change signature to
```
// @Deprecate(...)
static create(providersOrOptions: StaticProvider[], parent? Injector);
static create (options: {
  providers?: StaticProviders[],
  parent? Injector
  name?: string
});
```

This will be more future safe.

2017-10-23 10:03 UTC, ocombe commented
I've updated the signature for the create method. Can you double check that I did it well? It's the first time that I overload a method in typescript (the docs go on the signature methods right?).

Since `providers` is required, maybe that we could change the signature to `create(providers: StaticProviders[], options: {parent?: Injector, name?: string})` instead ?

2017-10-23 10:10 UTC, mary-poppins commented
You can preview ade0356 at https://pr19482-ade0356.ngbuilds.io/.

2017-10-23 11:03 UTC, erbsenkoenig commented
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[angular/angular] feat(core): add source to `StaticInjectorError` message
[WIP] (#19482)" gesendet am 23.10.2017 12:12:09.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

2017-10-23 11:03 UTC, erbsenkoenig commented
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[angular/angular] feat(core): add source to `StaticInjectorError` message
[WIP] (#19482)" gesendet am 23.10.2017 12:04:35.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

2017-10-23 12:06 UTC, mary-poppins commented
You can preview 6666ceb at https://pr19482-6666ceb.ngbuilds.io/.

2017-10-23 13:02 UTC, mary-poppins commented
You can preview adfee2b at https://pr19482-adfee2b.ngbuilds.io/.

2017-10-24 03:09 UTC, mhevery requested changes

2017-10-24 03:09 UTC, mhevery commented on packages/core/src/view/util.ts
> +      Object.defineProperty(token, '__source', {value: sourceName, configurable: true});
This is not JSCompiler safe. `'__source'` will not be renamed, but than you are reading it as `token.__source` which will be renamed. 

change to `Object.defienProperty(token, SOURCE, ...)`\

2017-10-24 03:09 UTC, mhevery commented on packages/core/src/di/injector.ts
> +      if (token.__source) {
To be JsCompiler safe you must either always access using `.__source` or using `['__source']`. Because you mix it will break minification.

I suggest that you crate constant `conts SOURCE = '__source'` and than access as `[SOURCE]`

2017-10-24 06:53 UTC, ocombe commented
Code updated

2017-10-24 07:01 UTC, mary-poppins commented
You can preview 1dfc520 at https://pr19482-1dfc520.ngbuilds.io/.

2017-10-24 16:08 UTC, mhevery approved these changes

2017-10-24 16:27 UTC, mary-poppins commented
You can preview d496472 at https://pr19482-d496472.ngbuilds.io/.

2017-10-24 17:04 UTC, mary-poppins commented
You can preview 2b3b565 at https://pr19482-2b3b565.ngbuilds.io/.

2017-11-03 18:14 UTC, merged