fix(router): avoid applying active class to null router links
angular/angular pull request #19589
Opened 2017-10-06 07:44 UTC by ivanryuu

Null roots should not have the active class applied to them.

Closes #18347

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Issue Number: #18347

## What is the new behavior?
Avoid applying the active class to null router links.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2018-10-15 16:48 UTC, jasonaden commented
@ivanryuu Sorry this has been sitting for so long. But I've taken a look at it. Let me know if you want to continue to get this in shape to be merged. We are now going back to these older PRs to try to get them addressed and catch up the backlog.

2018-10-15 16:57 UTC, jasonaden requested changes

2018-10-15 16:57 UTC, jasonaden commented on packages/router/src/directives/router_link.ts
> +    if (commands !== null && commands !== undefined && commands !== []) {
This line doesn't seem to change the existing logic.

`commands !== null && commands !== undefined` is the same as `commands != null`. We use the latter to shorten as an optimization.

Also, `commands !== []` will *always* be `true` since the empty array is being created in place. Similarly, `[] !== []` will *always* be `true` because it's checking object equality.

2021-07-23 19:10 UTC, atscott commented
Closing since we're working on changing the behavior of a `null` `routerLink` so that the commands are `null` rather than set to `[]`. This would make the change here obsolete since `routerLinkActive` would not set `isActive` to `true` if `commands === null`

2021-07-23 19:10 UTC, closed without merging