[WIP] docs(aio): fix toh-pt6 example
angular/angular pull request #19668
Opened 2017-10-11 18:33 UTC by kapunahelewong

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Plunker uses `json().data` but that breaks it. Removed `.data`, plunker works now.

Issue Number: #19602

## What is the new behavior?
Now you can `getHero`, `getHeroes`, `delete`, `create`, `update`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Fixes #19602.

@petebacondarwin Could you review this when you get a chance? I've marked it WIP because I have questions regarding `HttpClient`, the Promises, and that locally, when running it, it can't find `app.module.ngfactory`.

2017-10-11 19:12 UTC, gkalpak requested changes
In order for this to work locally and on zips, you need to upgrade `angular-in-memory-web-api` to 0.5.x [here][1], which means that you have to also update all similar occurrences of `.data` in all `aio/content/examples/` :grin:

[1]: https://github.com/ExpertSupport/angular/blob/c87a328bbc4993969e249c8be096342f3a063415/aio/tools/examples/shared/package.json#L28

2017-10-11 19:25 UTC, gkalpak commented
As discussed offline, the easiest way to solve this issue (until we implement a more future-proof solution for the plnkrs) is to restrict the `angular-in-memory-web-api` to 0.4.x on plnkrs too. Essentially, modify the `*.config.*` files in [here][1]:

```diff
-'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
+'angular-in-memory-web-api': 'npm:angular-in-memory-web-api@0.4/bundles/in-memory-web-api.umd.js',
```

[1]: https://github.com/angular/angular/blob/566606ef4638636fedfd08d864029cfc5b4b09a7/aio/tools/examples/shared/boilerplate/systemjs/src

2017-10-11 19:53 UTC, kapunahelewong commented
@gkalpak changed! Thanks for the specifics. :)

2017-10-11 20:26 UTC, petebacondarwin approved these changes

2017-10-11 20:27 UTC, gkalpak approved these changes
LGTM. I would prefer to get a second opinion from Travis, but apparently he/she is busy atm :smiley:

2017-10-11 20:42 UTC, gkalpak commented
I opened #19670 to test it against 4.4.x.

2017-10-11 21:40 UTC, gkalpak commented
Some of the examples e2e tests are failing (with error `Could not find Angular on page`) 😕
No idea why. Do the tests pass locally, @kapunahelewong?

[1]: https://travis-ci.org/angular/angular/builds/286714513

2017-10-12 14:19 UTC, kapunahelewong commented
Tests are failing locally. @gkalpak is aware per offline conversation.

2017-10-16 13:18 UTC, gkalpak commented
I tried this against latest master and it works.
There are still some failures against 4.4.x. Investigating...

2017-10-16 18:10 UTC, gkalpak requested changes

2017-10-16 18:10 UTC, gkalpak commented on aio/tools/examples/shared/boilerplate/systemjs/src/systemjs.config.js
> +      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api@0.4/bundles/in-memory-web-api.umd.js'
This is causing the errors. I didn't realize this file is only used locally and maps `npm` to the `node_modules/` directory, so no version range should be present in the path.

2017-10-16 18:36 UTC, kapunahelewong commented on aio/tools/examples/shared/boilerplate/systemjs/src/systemjs.config.js
> +      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api@0.4/bundles/in-memory-web-api.umd.js'
Wow, thank you so much for figuring it out.

2017-10-17 12:40 UTC, gkalpak approved these changes

2017-10-17 12:41 UTC, gkalpak commented
Travis doesn't pick up this PR (for whatever reason). Tested manually against master and 4.4.x.

2017-10-17 17:41 UTC, tbosch commented
Merged.

2017-10-17 17:41 UTC, closed without merging