wip: first bazel test for `ng_module`
angular/angular pull request #19703
Opened 2017-10-13 17:36 UTC by tbosch

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2017-10-13 17:51 UTC, mary-poppins commented
You can preview e5397c7 at https://pr19703-e5397c7.ngbuilds.io/.

2017-10-14 01:02 UTC, mary-poppins commented
You can preview e513fd5 at https://pr19703-e513fd5.ngbuilds.io/.

2017-10-16 19:45 UTC, mary-poppins commented
You can preview 06140a1 at https://pr19703-06140a1.ngbuilds.io/.

2017-10-16 23:11 UTC, mary-poppins commented
You can preview a59ffbb at https://pr19703-a59ffbb.ngbuilds.io/.

2017-10-16 23:45 UTC, mary-poppins commented
You can preview 9fedfb1 at https://pr19703-9fedfb1.ngbuilds.io/.

2017-10-17 01:04 UTC, IgorMinar requested changes

2017-10-17 01:04 UTC, IgorMinar commented on .bazelrc
> +build --show_result=1
is this a leftover? the comment above is now out of date.

2017-10-17 01:04 UTC, IgorMinar commented on WORKSPACE
> -    tag = "0.1.6",
can you leave a comment about why we need this particular SHA?

2017-10-17 01:04 UTC, IgorMinar commented on packages/bazel/test/ngc-wrapped/BUILD.bazel
> +licenses(["notice"])  # Apache 2.0
Apache 2???

2017-10-17 01:04 UTC, IgorMinar commented on packages/bazel/test/ngc-wrapped/empty/BUILD.bazel
> +licenses(["notice"])  # Apache 2.0
apache?

2017-10-17 03:29 UTC, alexeagle commented on WORKSPACE
> -    tag = "0.1.6",
I'll cut a release first thing tomorrow (will have Windows support too :)

2017-10-17 03:29 UTC, alexeagle commented on packages/bazel/test/BUILD.bazel
> +# Empty marker file, indicating this directory is a Bazel package.
this file not needed (we don't reference any files in this directory as labels)

2017-10-17 03:29 UTC, alexeagle commented on packages/bazel/test/ngc-wrapped/BUILD.bazel
> +# We need a filegroup so that we can refer
yes, good solution for this

2017-10-17 03:29 UTC, alexeagle commented on packages/bazel/test/ngc-wrapped/empty/READM.md
> +# Empty ng_module to capture the default tsconfig.json
file name is misspelled (misspelt if you like)

2017-10-17 03:29 UTC, alexeagle commented on packages/bazel/test/ngc-wrapped/test.json
> +{
this file shouldn't be checked into VCS right?

2017-10-17 03:29 UTC, alexeagle commented on packages/bazel/test/ngc-wrapped/test_support.ts
> +import {runOneBuild} from '@angular/bazel/index';
any particular reason you import from `@angular/bazel/index` instead of `@angular/bazel`?

2017-10-17 03:29 UTC, alexeagle commented on packages/bazel/test/ngc-wrapped/tsconfig_template.ts
> +export function createTsConfig(options: TsConfigOptions) {
this is still pretty heavy - I wonder if this would be much shorter if it were written in skylark, like how we override tsconfig properties in ng_module itself. Not sure though.

2017-10-17 04:07 UTC, tbosch commented on packages/bazel/test/ngc-wrapped/tsconfig_template.ts
> +export function createTsConfig(options: TsConfigOptions) {
It would be simpler. However, the TypeScript code needs to be able to call this, which makes it hard.

2017-10-17 16:57 UTC, tbosch commented on .bazelrc
> +build --show_result=1
Yes, removed.

2017-10-17 16:58 UTC, tbosch commented on WORKSPACE
> -    tag = "0.1.6",
Used tag 0.1.11 now.

2017-10-17 16:59 UTC, tbosch commented on packages/bazel/test/ngc-wrapped/empty/READM.md
> +# Empty ng_module to capture the default tsconfig.json
changed

2017-10-17 16:59 UTC, tbosch commented on packages/bazel/test/ngc-wrapped/test.json
> +{
removed

2017-10-17 16:59 UTC, tbosch commented on packages/bazel/test/ngc-wrapped/test_support.ts
> +import {runOneBuild} from '@angular/bazel/index';
Changed

2017-10-17 17:02 UTC, tbosch commented on packages/bazel/test/BUILD.bazel
> +# Empty marker file, indicating this directory is a Bazel package.
Removed

2017-10-17 17:06 UTC, tbosch commented on WORKSPACE
> -    tag = "0.1.6",
Actually need to keep the commit for now as Alex is still working on producing a good node_js rules that work with typescript rules. Left a TODO for Alex.

2017-10-17 17:10 UTC, tbosch commented on packages/bazel/test/ngc-wrapped/BUILD.bazel
> +licenses(["notice"])  # Apache 2.0
Copy and paste error, removed them.

2017-10-17 17:10 UTC, tbosch commented on packages/bazel/test/ngc-wrapped/empty/BUILD.bazel
> +licenses(["notice"])  # Apache 2.0
Copy and paste error, removed them.

2017-10-17 17:12 UTC, alexeagle commented on WORKSPACE
> -    tag = "0.1.6",
need more mature release practices for this stuff as it starts to get users....

2017-10-17 17:12 UTC, alexeagle approved these changes

2017-10-17 17:42 UTC, IgorMinar approved these changes

2017-10-17 18:05 UTC, mary-poppins commented
You can preview 7a8c2c7 at https://pr19703-7a8c2c7.ngbuilds.io/.

2017-10-17 22:15 UTC, tbosch commented
Travis fails because of #19768, everything else should be good.

2017-10-17 22:52 UTC, closed without merging