fix(compiler-cli): diagnostics file paths relative to cwd, not tsconfig
angular/angular pull request #19748
Opened 2017-10-16 16:32 UTC by alexeagle

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2017-10-16 16:41 UTC, mary-poppins commented
You can preview f6b0a67 at https://pr19748-f6b0a67.ngbuilds.io/.

2017-10-16 17:12 UTC, tbosch requested changes

2017-10-16 17:12 UTC, tbosch commented on packages/compiler-cli/src/perform_compile.ts
>  export function formatDiagnostics(options: api.CompilerOptions, diags: Diagnostics): string {
Could you change this to pass in an optional `tsFormatHost`, so that we can control the currentDirectory in tests (so it gets easy to fix the tests on Travis)?

2017-10-16 17:12 UTC, tbosch commented on packages/compiler-cli/src/perform_compile.ts
>  export function formatDiagnostics(options: api.CompilerOptions, diags: Diagnostics): string {
Could you then also remove the `options`, as they are not used anymore?

2017-10-16 17:50 UTC, mary-poppins commented
You can preview d6ad333 at https://pr19748-d6ad333.ngbuilds.io/.

2017-10-16 21:22 UTC, mary-poppins commented
You can preview 6106663 at https://pr19748-6106663.ngbuilds.io/.

2017-10-17 18:14 UTC, mary-poppins commented
You can preview 7cf3d1d at https://pr19748-7cf3d1d.ngbuilds.io/.

2017-10-17 18:15 UTC, tbosch commented on packages/compiler-cli/src/perform_compile.ts
> +export function formatDiagnostics(diags: Diagnostics, tsFormatHost?: ts.FormatDiagnosticsHost): string {
nit: maybe use `tsFormatHost = defaultFormatHost`?

2017-10-17 18:15 UTC, tbosch approved these changes

2017-10-17 18:22 UTC, alexeagle commented on packages/compiler-cli/src/perform_compile.ts
> +export function formatDiagnostics(diags: Diagnostics, tsFormatHost?: ts.FormatDiagnosticsHost): string {
🥇

2017-10-17 18:34 UTC, mary-poppins commented
You can preview e4adaef at https://pr19748-e4adaef.ngbuilds.io/.

2017-10-17 19:45 UTC, chuckjaz approved these changes

2017-10-18 19:47 UTC, closed without merging