docs(compiler-cli): add warning about changing ngtools_api2
angular/angular pull request #19804
Opened 2017-10-19 13:10 UTC by filipesilva

A recent change (https://github.com/angular/angular/pull/19748) broke the error reporting in Angular CLI. This warning should help coordinate changes to prever situations like that.

2017-10-19 13:27 UTC, mary-poppins commented
You can preview 3157025 at https://pr19804-3157025.ngbuilds.io/.

2017-10-19 14:33 UTC, tbosch requested changes
A better way would be to add an entry to .pullapprove. This way this gets checked automatically.

2017-10-19 14:38 UTC, filipesilva commented
@tbosch done. I left the warning as well, or do you want me to remove it?

2017-10-19 14:47 UTC, mary-poppins commented
You can preview 56e99d3 at https://pr19804-56e99d3.ngbuilds.io/.

2017-10-19 14:48 UTC, tbosch approved these changes

2017-10-19 14:48 UTC, tbosch commented
Looks good, thanks!

2017-10-19 14:52 UTC, gkalpak commented on .pullapprove.yml
> +        - "packages/compiler-cli/src/ngtools*"
Shouldn't these files be excluded from the `compiler-cli` group?

2017-10-19 14:56 UTC, filipesilva commented on .pullapprove.yml
> +        - "packages/compiler-cli/src/ngtools*"
I think it still falls under the umbrella of the `compiler-cli`, no?

2017-10-19 15:27 UTC, IgorMinar requested changes

2017-10-19 15:27 UTC, IgorMinar commented on .pullapprove.yml
> +# brocco - Mike Brocchi
please keep the list sorted

2017-10-19 15:27 UTC, IgorMinar commented on .pullapprove.yml
> +        - "packages/compiler-cli/src/ngtools*"
If the goal is to notify someone on the cli team about this change then we should exclude this path from the compiler-cli rule that follows.

2017-10-19 15:28 UTC, IgorMinar commented on packages/compiler-cli/src/ngtools_api2.ts
> + * PLEASE PING THE ANGULAR CLI TEAM BEFORE ALTERING THIS FILE. *
how about -> Changes to this file need to be approved by the Angular CLI team.

2017-10-19 15:38 UTC, filipesilva commented on .pullapprove.yml
> +# brocco - Mike Brocchi
Done

2017-10-19 15:38 UTC, filipesilva commented on packages/compiler-cli/src/ngtools_api2.ts
> + * PLEASE PING THE ANGULAR CLI TEAM BEFORE ALTERING THIS FILE. *
Done

2017-10-19 15:38 UTC, filipesilva commented on .pullapprove.yml
> +        - "packages/compiler-cli/src/ngtools*"
Done

2017-10-19 15:47 UTC, mary-poppins commented
You can preview 411045b at https://pr19804-411045b.ngbuilds.io/.

2017-10-19 16:33 UTC, IgorMinar approved these changes
can you please reclassify this commit to be "build:" rather than "docs:". otherwise lgtm.

2017-10-19 16:38 UTC, filipesilva commented
Done

2017-10-19 16:49 UTC, mary-poppins commented
You can preview 628278a at https://pr19804-628278a.ngbuilds.io/.

2017-10-20 00:15 UTC, IgorMinar approved these changes

2017-10-20 16:39 UTC, merged