docs: Deployment guide for CLI
angular/angular pull request #19839
Opened 2017-10-20 22:43 UTC by wardbell

See Issue # 19510
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

2017-10-20 22:56 UTC, mary-poppins commented
You can preview 0306819 at https://pr19839-0306819.ngbuilds.io/.

2017-10-21 19:46 UTC, mary-poppins commented
You can preview 97dde14 at https://pr19839-97dde14.ngbuilds.io/.

2017-10-23 16:16 UTC, filipesilva requested changes

2017-10-23 16:16 UTC, filipesilva commented on aio/content/guide/deployment.md
> +For the simplest deployment, build for development and xcopy the output directory to a web server.
`xcopy` -> `copy`

2017-10-23 16:16 UTC, filipesilva commented on aio/content/guide/deployment.md
> +The remaining [xcopy deployment steps](#xcopy) are the same as before.
`xcopy`->`copy`

2017-10-23 16:16 UTC, filipesilva commented on aio/content/guide/deployment.md
> +Building for production (or appending the `--environment=prod` flag) enables _production mode_
`--environment=prod` -> `--target=prod`

These two are actually different: https://github.com/angular/angular-cli/wiki/build#build-targets-and-environment-files

2017-10-23 16:16 UTC, filipesilva commented on aio/content/guide/deployment.md
> +Unlike `build`, **it erases the output directory** and serves the build artifacts from memory instead of from files for a faster development experience.
`ng build` also deletes the directory, it just outputs new files there after.

2017-10-23 16:16 UTC, filipesilva commented on aio/content/guide/deployment.md
> +Note that the `ng serve` does NOT update generated files as you make changes.
You can use `ng build --watch` to continuously generate files.

2017-10-23 20:11 UTC, wardbell commented on aio/content/guide/deployment.md
> +Building for production (or appending the `--environment=prod` flag) enables _production mode_
I just compared `--environment=prod` vs `--environment=dev` and they enable/disable `prodMod` exactly as I said and expected.

So do `--target=production` vs `--target=development`. But the `--environment` flag is way more intuitive, especially after looking at `main.ts`
```
if (environment.production) {
  enableProdMode();
}
```
Why should I change from `--environment` to `--target`?  The wiki page is not helping me understand.

2017-10-23 20:52 UTC, filipesilva commented on aio/content/guide/deployment.md
> +Building for production (or appending the `--environment=prod` flag) enables _production mode_
You're right, I misunderstood what was being talked about here.

2017-10-23 21:05 UTC, mary-poppins commented
You can preview fd31ace at https://pr19839-fd31ace.ngbuilds.io/.

2017-10-24 12:55 UTC, Foxandxss approved these changes

2017-10-24 12:55 UTC, Foxandxss commented on aio/content/guide/deployment.md
>  [Quickstart repo](https://github.com/angular/quickstart) is pre-configured to fallback to `index.html`.
We will deprecate the quickstart, we shouldn't name it anymore.

2017-11-02 12:58 UTC, filipesilva approved these changes

2017-11-02 13:23 UTC, mary-poppins commented
You can preview d64b1fc at https://pr19839-d64b1fc.ngbuilds.io/.

2017-11-02 18:25 UTC, vicb commented
missing:
- target label
- merge label
- green CI

2017-11-02 23:58 UTC, IgorMinar commented
@vicb the ci failure is a flake and unrelated to this change.

2017-11-03 00:00 UTC, IgorMinar commented
I fixed the labels. @wardbell please always apply "target" and "merge" label when your pr is ready for merge.

2017-11-03 00:03 UTC, Foxandxss commented
Yes sorry, I have too many PRs and travis is being flaky all day so I go back and forward restarting them and checking all the statuses.

2017-11-03 18:10 UTC, merged