build: upgrade jasmine to latest version
angular/angular pull request #19904
Opened 2017-10-24 15:58 UTC by gkalpak

## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] ~~Tests for the changes have been added (for bug fixes / features)~~
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

## PR Type
```
[x] Build related changes
```

## What is the current behavior?
Older version of `jasmine`/`jasmine-node` and corresponding typings.

## What is the new behavior?
Latest version of `jasmine`/`jasmine-node` and corresponding typings.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No(t intentionally :grin:)
```

2017-10-24 16:10 UTC, mary-poppins commented
You can preview 3e2ed3c at https://pr19904-3e2ed3c.ngbuilds.io/.

2017-10-24 17:36 UTC, gkalpak commented on tools/types-ext/jasminewd2.d.ts
> +  interface DoneFn extends Function {
Come on clang-format! 😞

2017-10-24 17:36 UTC, gkalpak commented on tools/types-ext/jasminewd2.d.ts
> +    declare function fit(
😞 😞 😞

2017-10-24 17:55 UTC, mary-poppins commented
You can preview bc82db9 at https://pr19904-bc82db9.ngbuilds.io/.

2017-10-24 18:24 UTC, mary-poppins commented
You can preview c0746ed at https://pr19904-c0746ed.ngbuilds.io/.

2017-10-25 08:09 UTC, mary-poppins commented
You can preview c4c20ae at https://pr19904-c4c20ae.ngbuilds.io/.

2017-10-25 08:14 UTC, mary-poppins commented
You can preview 9316f5b at https://pr19904-9316f5b.ngbuilds.io/.

2017-10-25 09:41 UTC, mary-poppins commented
You can preview 5a78966 at https://pr19904-5a78966.ngbuilds.io/.

2017-10-25 10:26 UTC, gkalpak commented on packages/common/test/pipes/date_pipe_spec.ts
> +         () => expect(pipe.transform('2017-05-07T12:13:14', 'dd-MM-yyyy HH:mm'))
This relies on timezone (e.g. failed on my UTC+2 timezone 😞).
Using `12` as the hour it is more resilient to timezone differences (albeit not entirely immune) and thus more likely to pass when run locally.

2017-10-25 10:42 UTC, gkalpak commented on packages/compiler-cli/test/metadata/collector_spec.ts
> +    } as any as MetadataMap);
I noticed that there are several occurrences where types were a little loose or not-specific in `compiler-cli`-related stuff. For example nullable/"undefined-able" values typed as non-nullable (e.g. [here][1], [here][2], [here][3]) or values whose properties could be more strictly typed (e.g. the changes in this file), etc.

Is this expected/intentional, @tbosch, @chuckjaz?
<sub>
Obviously, I don't understand enough about the implications of changing the types of these APIs :grin:
Just bringing it up as my instinctive, very-high-level-understanding reaction/thought.
</sub>

[1]: https://github.com/angular/angular/pull/19904/files#diff-93cb4d146755c3214602a83de1c313f2R455
[2]: https://github.com/angular/angular/pull/19904/files#diff-cdf1f6981339577e6b2003f82efb749eL118
[3]: https://github.com/angular/angular/pull/19904/files#diff-0cb86a67c64e9b1b291919678078a500R275

2017-10-25 10:47 UTC, gkalpak commented on packages/core/test/linker/source_map_integration_node_only_spec.ts
> +      // TODO: Figure out a better way to retrieve the JIT sources, without spying on `Function`.
@tbosch, @chuckjaz: Not a big deal, but if it is possible to retrieve the JIT sources without spying on such a fundamental built-in (`Function`), I think it is worth doing. (The current approach is a little brittle.)

2017-10-25 10:58 UTC, gkalpak commented on packages/router/src/url_tree.ts
> +      public queryParams: Params,
This is a public API (`{key: string}` --> `{key: any}`) plus using the already public `Params` type for that.
But I think it is necessary, because this is what actually happens (i.e. the values are not restricted to `string`).

If a more specific type is desirable, I can dig deeper into what the possible types are and update (from a quick look it might just be `string | string[]`).

2017-10-25 11:16 UTC, gkalpak commented on tools/types-ext/jasminewd2.d.ts
> +    declare function afterAll(action: (done: DoneFn) => Promise<void>, timeout?: number): void;
@vikerman (or anyone else working on [jasminewd][1]), should these changes be ported to [DefinitelyTyped][2]?

[1]: https://github.com/angular/jasminewd
[2]: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jasminewd2

2017-10-25 11:30 UTC, mary-poppins commented
You can preview 8a3b7da at https://pr19904-8a3b7da.ngbuilds.io/.

2017-10-25 13:57 UTC, ocombe commented on packages/common/test/pipes/date_pipe_spec.ts
> +         () => expect(pipe.transform('2017-05-07T12:13:14', 'dd-MM-yyyy HH:mm'))
yes, that test is a little bit flacky

2017-10-25 16:03 UTC, chuckjaz commented on packages/compiler-cli/test/metadata/collector_spec.ts
> +    } as any as MetadataMap);
Can you leave TODO review comments anywhere where `as any as` is needed?

2017-10-25 16:12 UTC, alexeagle commented on tools/types-ext/jasminewd2.d.ts
> +    declare function afterAll(action: (done: DoneFn) => Promise<void>, timeout?: number): void;
Yes, you can send me a PR against the upstream typings on DefinitelyTyped, I'm a committer there

2017-10-25 23:23 UTC, mary-poppins commented
You can preview 4e2adb2 at https://pr19904-4e2adb2.ngbuilds.io/.

2017-10-26 00:01 UTC, mary-poppins commented
You can preview 1e0a451 at https://pr19904-1e0a451.ngbuilds.io/.

2017-11-02 10:57 UTC, mary-poppins commented
You can preview b96ce54 at https://pr19904-b96ce54.ngbuilds.io/.

2017-11-02 11:19 UTC, mary-poppins commented
You can preview 6324f02 at https://pr19904-6324f02.ngbuilds.io/.

2017-11-02 19:44 UTC, IgorMinar commented on packages/examples/tsconfig.json
> +// WARNING:
maybe call this file as tsconfig.e2e.json?

2017-11-02 19:50 UTC, IgorMinar requested changes
can we implement this without the public api change? I believe Jason is already working on a rollout plan for the router api change.

2017-11-02 19:50 UTC, IgorMinar commented on packages/router/src/url_tree.ts
> +      public queryParams: Params,
@jasonaden will have to take a look at this. it looks like a breaking change to me, which we can't do now. Jason is this the same api change you were trying to make during v5 RC?

2017-11-02 19:50 UTC, IgorMinar commented on tools/public_api_guard/router/router.d.ts
> +    queryParams: Params;
this change won't fly now. we can't be changing the public api in this way.

2017-11-02 20:43 UTC, gkalpak commented on packages/router/src/url_tree.ts
> +      public queryParams: Params,
Just to be clear, the public API type is wrong. It claims that `queryParams` values are always strings, but this is not the case. So, your app might typecheck fine, but break at runtime. But this change might indeed cause an app not to compile any more (for good reasons :wink:)

LMK if it is better to remove it (and use `as any` in the tests to work around it).

2017-11-02 20:56 UTC, gkalpak commented on packages/examples/tsconfig.json
> +// WARNING:
I thought aboutt that. The only issue is that VSCode didn't seem to pick it up (not sure what other editors/IDEs do) 😒

2017-11-29 15:33 UTC, gkalpak commented on packages/router/src/url_tree.ts
> +      public queryParams: Params,
Just to be more clear, `Params` is alias for `{[key: string]: any}`, so it is wider than the previous type.

2017-11-29 15:36 UTC, gkalpak commented
@IgorMinar, should I still revert the public API change (despite https://github.com/angular/angular/pull/19904#discussion_r148654182)?

2017-11-29 15:38 UTC, mary-poppins commented
You can preview 4bba091 at https://pr19904-4bba091.ngbuilds.io/.

2017-11-29 16:08 UTC, mary-poppins commented
You can preview 2630492 at https://pr19904-2630492.ngbuilds.io/.

2017-11-29 16:21 UTC, mary-poppins commented
You can preview 593841e at https://pr19904-593841e.ngbuilds.io/.

2017-12-01 06:31 UTC, IgorMinar commented
I really need @jasonaden to look at the API change because he attempted to do something similar just to break g3 and revert that change. Jason?

2017-12-01 16:50 UTC, jasonaden commented
The change we were trying to make was to make the type `{[key: string]: string | string[]}`. I think the API change looked the same as this, but in that other change we also changed Params to the above (which is the accurate type). So this change should be okay in terms of the types because this PR is making the types more general rather than making them more specific.

2017-12-01 19:36 UTC, gkalpak commented
Is there a way to try this PR in g3 and see if anything breaks?

2017-12-05 16:31 UTC, mary-poppins commented
You can preview c6f1342 at https://pr19904-c6f1342.ngbuilds.io/.

2017-12-05 23:49 UTC, IgorMinar commented
@gkalpak if you get it pass reviews and CI then apply the merge label and it will be tested in g3 by the caretaker. otherwise you'd need to find a googler to test it in an ad-hoc fashion.

2017-12-06 16:30 UTC, mary-poppins commented
You can preview 3ff492c at https://pr19904-3ff492c.ngbuilds.io/.

2017-12-06 19:26 UTC, mary-poppins commented
You can preview d01cf8b at https://pr19904-d01cf8b.ngbuilds.io/.

2017-12-06 20:04 UTC, gkalpak commented
> @gkalpak if you get it pass reviews and CI

CI is green.
Not sure how to get reviews to pass :grin:

2017-12-11 12:54 UTC, mary-poppins commented
You can preview fe93a10 at https://pr19904-fe93a10.ngbuilds.io/.

2017-12-12 11:59 UTC, mary-poppins commented
You can preview 15f1b21 at https://pr19904-15f1b21.ngbuilds.io/.

2017-12-12 13:42 UTC, alexeagle approved these changes
approval for the 'bazel' group

2017-12-12 13:42 UTC, alexeagle commented on modules/types.d.ts
>  /// <reference path="../node_modules/@types/jasmine/index.d.ts" />
at present, this means that usage of jasmine will type-check in production code. We should probably have different typings present for test compilations - but I can clean this up later as part of the bazel conversion; you're not introducing the problem

2017-12-12 13:58 UTC, gkalpak commented on modules/types.d.ts
>  /// <reference path="../node_modules/@types/jasmine/index.d.ts" />
TBH, I am not even sure if this file is used at all (or what for) 😇
Could be a relic from before moving from `modules/` to `packages/`.

2017-12-12 14:05 UTC, gkalpak commented
@alexeagle, is the approval explicitly only for the `bazel` group? What about `build-and-ci`, `compiler-cli` and `integration`? :cry:

2017-12-12 14:20 UTC, alexeagle commented
Click the details link for the pullapprove status. You'll see a whole
explanation of which individuals you need to chase down to get your missing
approvals. I suggest pinging them individually until you're collected the
whole set.

On Tue, Dec 12, 2017 at 6:08 AM George Kalpakas <notifications@github.com>
wrote:

> @alexeagle <https://github.com/alexeagle>, is the approval explicitly
> only for the bazel group? What about build-and-ci, compiler-cli and
> integration? 😢
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/19904#issuecomment-351060723>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAC5I0QXfHSyAHWbN8Lyu9d4k5Ix4bbOks5s_oiMgaJpZM4QErCh>
> .
>

2017-12-12 19:45 UTC, jasonaden approved these changes

2017-12-12 19:51 UTC, IgorMinar approved these changes
I talked to Jason. all good now.

2017-12-12 19:52 UTC, IgorMinar commented
@gkalpak apply the merge label whenever you are ready. I'm not sure if you are still changing anything in the PR..

2017-12-12 22:27 UTC, gkalpak commented
I have just been rebasing the PR on master (and fixing conflicts and new errors). Applying the merge label.
Thx for the reviews!

2017-12-12 23:06 UTC, hansl approved these changes

2018-01-18 13:26 UTC, mary-poppins commented
You can preview 3e2ed3c at https://pr19904-3e2ed3c.ngbuilds.io/.
You can preview bc82db9 at https://pr19904-bc82db9.ngbuilds.io/.
You can preview c0746ed at https://pr19904-c0746ed.ngbuilds.io/.
You can preview c4c20ae at https://pr19904-c4c20ae.ngbuilds.io/.
You can preview 9316f5b at https://pr19904-9316f5b.ngbuilds.io/.
You can preview 5a78966 at https://pr19904-5a78966.ngbuilds.io/.
You can preview 8a3b7da at https://pr19904-8a3b7da.ngbuilds.io/.
You can preview 4e2adb2 at https://pr19904-4e2adb2.ngbuilds.io/.
You can preview 1e0a451 at https://pr19904-1e0a451.ngbuilds.io/.
You can preview b96ce54 at https://pr19904-b96ce54.ngbuilds.io/.
You can preview 6324f02 at https://pr19904-6324f02.ngbuilds.io/.
You can preview 4bba091 at https://pr19904-4bba091.ngbuilds.io/.
You can preview 2630492 at https://pr19904-2630492.ngbuilds.io/.
You can preview 593841e at https://pr19904-593841e.ngbuilds.io/.
You can preview c6f1342 at https://pr19904-c6f1342.ngbuilds.io/.
You can preview 3ff492c at https://pr19904-3ff492c.ngbuilds.io/.
You can preview d01cf8b at https://pr19904-d01cf8b.ngbuilds.io/.
You can preview fe93a10 at https://pr19904-fe93a10.ngbuilds.io/.
You can preview 15f1b21 at https://pr19904-15f1b21.ngbuilds.io/.

2018-01-18 13:26 UTC, mary-poppins commented
You can preview a3e36e9 at https://pr19904-a3e36e9.ngbuilds.io/.

2018-01-18 13:30 UTC, mary-poppins commented
You can preview cd7457a at https://pr19904-cd7457a.ngbuilds.io/.

2018-01-18 14:14 UTC, gkalpak commented
Rebased on master to resolve conflicts and fixed new issues in [render3/di_spec.ts][1] and [render3/properties_spec.ts][2].

[1]: https://github.com/angular/angular/pull/19904/files#diff-e2a2b6e7885a8a837c1451411c46c084
[2]: https://github.com/angular/angular/pull/19904/files#diff-91ba8623acc9f9071a8ee650ee6c4d56

2018-01-18 14:29 UTC, ocombe approved these changes

2018-02-13 08:51 UTC, gkalpak commented
Thx for trying :smiley:

If/when someone wants to take another stab at it, lmk and I will resolve the conflicts (I won't be rebasing regularly, because it isn't much fun :grin:)
Or maybe it is not worth it and we should just close it 😕

2018-02-13 15:55 UTC, alfaproject commented
@gkalpak a suggestion if I may since I had to do something similar recently. I ended up creating satellite PRs of small things that I found when the types got more strict like, for example, the public API change would be a good candidate to do in another PR. The downside is that it will take longer to get this landed. #life

2018-02-20 09:51 UTC, gkalpak commented
Thx for the suggestion, @alfaproject. Unfortunately, I didn't do much else than upgrading jasmine (and `@types`) and fixing up the errors that came up. So, other than the public API change (which is actually a type fix, not an actual change) I don't know what else could be split out into separate PRs 😕
<sub>(And I don't think the public API change is the reason this is difficult to get merged.)</sub>

That said, I am happy to do whatever makes this more easily mergeable (from a caretaker point-of-view).

2018-07-03 13:06 UTC, mary-poppins commented
You can preview 74a80af at https://pr19904-74a80af.ngbuilds.io/.

2018-07-03 15:09 UTC, mary-poppins commented
You can preview d6bca63 at https://pr19904-d6bca63.ngbuilds.io/.

2018-07-03 20:36 UTC, mary-poppins commented
You can preview 88d620b at https://pr19904-88d620b.ngbuilds.io/.

2018-07-04 09:36 UTC, mary-poppins commented
You can preview 28a5abe at https://pr19904-28a5abe.ngbuilds.io/.

2018-07-04 10:29 UTC, mary-poppins commented
You can preview 0d81dc3 at https://pr19904-0d81dc3.ngbuilds.io/.

2018-07-05 00:00 UTC, mary-poppins commented
You can preview 76abb75 at https://pr19904-76abb75.ngbuilds.io/.

2018-07-05 00:16 UTC, mary-poppins commented
You can preview 25a5698 at https://pr19904-25a5698.ngbuilds.io/.

2018-07-05 11:46 UTC, gkalpak commented on packages/types.d.ts
> -/// <reference path="../node_modules/@types/selenium-webdriver/index.d.ts" />
Protractor explicitly depends on these, so we shouldn't need to manually bring them in.

2018-07-05 13:14 UTC, mary-poppins commented
You can preview 8bf34b7 at https://pr19904-8bf34b7.ngbuilds.io/.

2018-07-05 13:37 UTC, mary-poppins commented
You can preview cbf2c48 at https://pr19904-cbf2c48.ngbuilds.io/.

2018-07-05 15:22 UTC, mary-poppins commented
You can preview 2ae2792 at https://pr19904-2ae2792.ngbuilds.io/.

2018-07-05 18:29 UTC, mary-poppins commented
You can preview e147306 at https://pr19904-e147306.ngbuilds.io/.

2018-07-05 19:12 UTC, mary-poppins commented
You can preview 1fdac95 at https://pr19904-1fdac95.ngbuilds.io/.

2018-07-05 19:21 UTC, mary-poppins commented
You can preview 97dfaf3 at https://pr19904-97dfaf3.ngbuilds.io/.

2018-07-06 04:33 UTC, mary-poppins commented
You can preview 0f35833 at https://pr19904-0f35833.ngbuilds.io/.

2018-07-06 06:28 UTC, mary-poppins commented
You can preview 1a3f52c at https://pr19904-1a3f52c.ngbuilds.io/.

2018-07-06 08:42 UTC, mary-poppins commented
You can preview b3a3be0 at https://pr19904-b3a3be0.ngbuilds.io/.

2018-07-06 09:10 UTC, mary-poppins commented
You can preview 8071de3 at https://pr19904-8071de3.ngbuilds.io/.

2018-07-06 10:00 UTC, mary-poppins commented
You can preview 0ebba85 at https://pr19904-0ebba85.ngbuilds.io/.

2018-07-06 12:50 UTC, gkalpak commented
This is now ready for review 😅
(cc @mhevery, @rkirov)

2018-07-06 17:01 UTC, mhevery commented
http://test/OCL:203491123:BASE:203491196:1530896473331:c6268e84

2018-07-06 17:21 UTC, alfaproject commented on packages/benchpress/test/webdriver/chrome_driver_extension_spec.ts
> +import {AsyncTestCompleter, describe, expect, fit, inject, it} from '@angular/core/testing/src/testing_internal';
Oops?

2018-07-06 17:22 UTC, alfaproject commented on packages/common/http/test/client_spec.ts
> +import {ddescribe, describe, fit, it} from '@angular/core/testing/src/testing_internal';
Oops?

2018-07-06 18:30 UTC, mhevery commented on packages/benchpress/test/webdriver/chrome_driver_extension_spec.ts
> +import {AsyncTestCompleter, describe, expect, fit, inject, it} from '@angular/core/testing/src/testing_internal';
fixed

2018-07-06 18:30 UTC, mhevery commented on packages/common/http/test/client_spec.ts
> +import {ddescribe, describe, fit, it} from '@angular/core/testing/src/testing_internal';
fixed

2018-07-06 18:44 UTC, mary-poppins commented
You can preview edb5217 at https://pr19904-edb5217.ngbuilds.io/.

2018-07-06 19:19 UTC, gkalpak commented on packages/benchpress/test/webdriver/chrome_driver_extension_spec.ts
> +import {AsyncTestCompleter, describe, expect, fit, inject, it} from '@angular/core/testing/src/testing_internal';
What was the problem??? 😕

2018-07-06 19:20 UTC, gkalpak commented on packages/common/http/test/client_spec.ts
> +import {ddescribe, describe, fit, it} from '@angular/core/testing/src/testing_internal';
😕

2018-07-06 19:21 UTC, gkalpak commented on packages/benchpress/test/webdriver/chrome_driver_extension_spec.ts
> +import {AsyncTestCompleter, describe, expect, fit, inject, it} from '@angular/core/testing/src/testing_internal';
AFAICT, everything was fine before (and Travis agrees with me 😛).

2018-07-06 20:44 UTC, mhevery commented on packages/benchpress/test/webdriver/chrome_driver_extension_spec.ts
> +import {AsyncTestCompleter, describe, expect, fit, inject, it} from '@angular/core/testing/src/testing_internal';
Yes, had to revert my `fit` => `iit` change.

2018-07-06 20:50 UTC, closed without merging