feat(forms): match getError has hasError to get's signature
angular/angular pull request #20211
Opened 2017-11-06 08:13 UTC by Toxicable

closes #19734

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Feature
```

## What is the current behavior?
`getError` and `hasError` mismatch the api of `get`

Issue Number: #19734

## What is the new behavior?
apis match

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2018-02-06 23:43 UTC, kara reviewed
Looks good, but can we also get a test for `hasError`, since we are changing it here?

2018-02-07 07:29 UTC, Toxicable commented
@kara done

2018-02-07 23:12 UTC, kara approved these changes
LGTM

2018-02-07 23:13 UTC, kara commented
@IgorMinar API review?

2018-02-08 06:47 UTC, IgorMinar requested changes

2018-02-08 07:33 UTC, Toxicable commented on packages/forms/src/model.ts
> +  hasError(errorCode: string, path?: Array<string|number>|string): boolean {
Seams valid if you're traversing through a form array.
Ill add some tests.

2018-02-08 08:21 UTC, Toxicable commented on packages/forms/src/model.ts
>     * If no path is given, it checks for the error on the present control.
Wasn't sure what to change here so I added a note on how the path can be used.
Let me know if you want something else

2018-02-13 01:33 UTC, Toxicable commented
Travis failure looks like a flake to me

2018-02-20 23:59 UTC, kara commented on packages/forms/src/model.ts
>     * If no path is given, it checks for the error on the present control.
@Toxicable I took a look again, but wasn't able to find the docs that you added. Is the commit up to date?

2018-02-21 00:03 UTC, Toxicable commented on packages/forms/src/model.ts
>     * If no path is given, it checks for the error on the present control.
@kara Uhhh, I guess not sorry, Ill double check this afternoon

2018-02-21 06:24 UTC, Toxicable commented on packages/forms/src/model.ts
>     * If no path is given, it checks for the error on the present control.
@kara Added some detail on what the path is meant to be and how to use it

2018-02-22 17:14 UTC, kara commented on packages/forms/src/model.ts
>     * If no path is given, it checks for the error on the present control.
Looks good. I'll let @IgorMinar take one more look though, while it's presubmitting.

2018-02-22 17:15 UTC, kara commented
[presubmit](http://test/OCL:186625804:BASE:186625815:1519319672973:9db50399)

2018-02-23 23:37 UTC, IgorMinar approved these changes

2018-02-23 23:38 UTC, IgorMinar commented
thanks

2018-02-27 16:35 UTC, kara commented
Some Google test failures that need to be investigated

2018-06-14 01:03 UTC, rafaelss95 commented
@kara sry to ping you, but do you have any news?

2018-10-09 22:49 UTC, kara commented
@Toxicable Would you mind rebasing this? Sorry it's been sitting so long. If you can rebase, we can take another look at the test failures and see if they're still relevant.

2018-11-28 09:05 UTC, Toxicable commented
@kara rebased! 
`ci/circleci: test_aio_local ` looks like a flake

2018-11-29 23:17 UTC, kara commented
[new presubmit](https://test.corp.google.com/ui#id=OCL:223420403:BASE:223420525:1543533441617:26cec8df)

2018-11-30 00:06 UTC, kara requested changes

2018-11-30 00:06 UTC, kara commented on packages/forms/src/model.ts
> +  hasError(errorCode: string, path?: Array<string|number>|string): boolean {
Can you update the type signature on `AbstractControlDirective` as well? Looks like it's inconsistent.

2018-11-30 00:09 UTC, Toxicable commented on packages/forms/src/model.ts
> +  hasError(errorCode: string, path?: Array<string|number>|string): boolean {
oh yes, will get on that

2018-12-19 08:17 UTC, Toxicable commented
@kara Hey, sorry the turn around from my side has been so slow.
updated those signatures aswell and re-rebased, let me know if I missed anything else

2018-12-21 02:06 UTC, kara approved these changes
LGTM. This last change fixed the internal failures (and don't worry about timing, you are still doing better than we are :) ).

2018-12-21 02:08 UTC, kara commented
@IgorMinar I think it needs one more review from you since the public-API changed again.

2018-12-22 00:23 UTC, IgorMinar approved these changes
Thank you, @Toxicable!!!

2018-12-22 00:28 UTC, IgorMinar reviewed
dang! I just noticed that this PR also needs API docs update. I asked @kara to send a follow up PR so that we don't need to block this, but in the future @Toxicable please do update the API docs.

I also noticed that you wrote a great justification of this change in the issue, but that justification is not available in the commit message, in the future it would be easier for us to review these kinds of changes if the explanation was in the commit message. thank you

2018-12-22 00:30 UTC, IgorMinar reviewed
dang #2!

this commit should have been a feature or a fix since it changes the public api surface
otherwise the change won’t get highlighted in the changelog and nobody will know

2018-12-22 00:31 UTC, Toxicable commented
@IgorMinar I can change it to a fix now if you like?

2018-12-22 00:32 UTC, kara commented
@Toxicable If you can change it to a fix and add the justification to the commit message, that'd be awesome!

2018-12-22 00:40 UTC, Toxicable commented
@kara done!

2019-01-03 18:17 UTC, closed without merging