fix(upgrade): need to take base uri into account in setUpLocationSync
angular/angular pull request #20244
Opened 2017-11-07 17:26 UTC by jahumes

The url.pathname passes the base uri as part of the url instead of removing it

Fixes angular/angular#20061

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
I am modifying the setUpLocationSync in packages/router/upgrade/src/upgrade.ts to take the base tag into account when navigating by url

Issue Number: 20061

## What is the new behavior?
The base tag is removed from the pathname before the router navigates to the specified url. This stops an infinite loop from occurring when navigating between Angular and AngularJS.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2017-11-07 17:27 UTC, jahumes commented
I had one question. This function isn't being tested anywhere in Angular that I can find. I am not sure if I should make an entire test file and write new tests for all of the functionality.

2017-11-08 18:12 UTC, zbuhler commented
The logic on this is pretty sound but there is a problem with the commit as is. If pulled in as is you will still get the infinite redirect.

Until the url.href is set (like it is on ```url.href = next;```) ```url.protocol``` and ```url.host``` will not be set properly (":" and "" respectively). The logic for setting the baseHref most likely needs to be put in the ```$locationChangeStart``` **AFTER** the ```url.href = next;```.

2017-11-10 14:14 UTC, jahumes commented
I have submitted a fix for the issues listed. Please recheck to see if this fixes this bug.

2017-11-15 18:47 UTC, gkalpak requested changes
Thx for looking into this 👍
I left a couple of comments. And yes, we should definitely have tests for this kind of stuff 😕

Ideally, we should have both unit and integration tests. But either is better than nothing :grin:
Feel free to add a new spec file with tests &nbsp;❤️

2017-11-15 18:47 UTC, gkalpak commented on packages/router/upgrade/src/upgrade.ts
> +      let path = url.pathname.replace(baseHref, baseHref.endsWith('/') ? '/' : '');
I think the general direction (stripping `baseHref` from the URL) is correct, but I think it would be better to use something like [Location#normalize()][1] for that. This ensures that there is no unnecessary duplication (of code and runtime overhead) and provides a more robust implementation (for examples it takes `APP_BASE_HREF` into account if provided).

WDYT?

[1]: https://github.com/angular/angular/blob/d47b2a6f706c42c049bf0faf1112c97ecf681c0a/packages/common/src/location/location.ts#L83-L85

2017-11-17 15:55 UTC, jahumes commented on packages/router/upgrade/src/upgrade.ts
> +    .$on('$locationChangeStart', (_: any, next: string, __: string) => {
Thanks for looking at this! I just got back from a trip and will push a fix for this over the weekend.

2017-11-17 15:57 UTC, jahumes commented on packages/router/upgrade/src/upgrade.ts
> +      let path = url.pathname.replace(baseHref, baseHref.endsWith('/') ? '/' : '');
That sounds like a much better solution. I will make those changes and write unit tests for them. They should be up either this weekend or early next week.

2017-12-15 12:35 UTC, gkalpak commented
@jahumes, any update on this? Will you find time to work on this in the near future or should someone else take it on?

2017-12-27 18:50 UTC, jahumes commented
I have done what you have requested with the change and that helped greatly make the code much smaller and normalized. 

I have been having a hard time with the writing of tests (which is why this has taken so long to push). I seem to be unable to get my tests to run at all. When I create a new file (packages/router/test/upgrade.spec.ts), none of the tests I create in there are run during `./test.sh node`. Am I required to run the build process after I make my changes before my tests start running?

2018-01-23 10:45 UTC, gkalpak commented
I think the tests inside `packages/router` are run with `./test.sh router` (or `./test.sh browser`, but `./test.sh router` should suffice).

If you need `ngUpgrade` files in your tests, you will also need to update [router/karma.conf.js][1] to include them (but you might not need them at all).

##
If you find any difficulties (or if you don't have time to work on this atm and want someone else to take it over), just let me know :wink:

[1]: https://github.com/angular/angular/blob/95fbb7d675d43e6d9954a3f8efb051fcf2f1f58a/packages/router/karma.conf.js

2018-01-24 16:18 UTC, jahumes commented
Thanks @gkalpak! I will look at this and if I can't get to by next week, I will let you know.

2018-02-24 00:07 UTC, mafredri commented
It would be awesome to get this merged, I've just spent two days hunting down this bug :-/. Unfortunately I only found this issue after I traced the bug and solved the issue.

Anything I can do to help so that others can benefit?

2018-02-25 18:00 UTC, gkalpak commented
@mafredi, currently this PR is missing tests. If @jahumes doesn't have time to work on this atm, perhaps you could give it a shot (adding tests)?

2018-02-27 14:07 UTC, jahumes commented
I have finally had the time to figure out how create a new test file. All my issues were around including a new module (@angular/upgrade/static) in my test file. I have it working and should be sending a PR today.

2018-02-27 15:19 UTC, jahumes commented
@gkalpak Do these tests work? Is there anything else you would like me to do?

2018-02-27 20:42 UTC, gkalpak requested changes
A few minor questions/suggestions. Looks pretty good overall 👍

2018-02-27 20:42 UTC, gkalpak commented on packages/router/testing/rollup.config.js
> +  '@angular/upgrade/static': 'ng.upgrade.static'
Is this change really necessary? AFAICT, `@angular/upgrade/static` is not used in `@angular/router/testing`, is it?

2018-02-27 20:42 UTC, gkalpak commented on packages/router/testing/tsconfig-build.json
> +      "@angular/upgrade/static": ["../../../dist/packages/upgrade/static"]
Is this change really necessary? AFAICT, `@angular/upgrade/static` is not used in `@angular/router/testing`, is it?

2018-02-27 20:42 UTC, gkalpak commented on packages/router/karma.conf.js
> +      {pattern: 'dist/all/@angular/upgrade/static/src/**/*.js', included: false, watched: false},
Why is this needed? What is requesting stuff from `upgrade/static/src/...`?

2018-02-27 20:42 UTC, gkalpak commented on packages/router/test/upgrade.spec.ts
> +/**
I think this file should be in `packages/router/upgrade/test/...`. From what I see in other similar packages, (e.g. `packages/animations/browser/`), `test/` should be next to the corresponding `src/`.

2018-02-27 20:42 UTC, gkalpak commented on packages/router/test/upgrade.spec.ts
> +  it('should setup by getting the Router and Location from the Angular injector', () => {
This test is redundant (since this is implicitly verified by the test below).

2018-02-27 20:42 UTC, gkalpak commented on packages/router/test/upgrade.spec.ts
> +  let callback: Function;
Nit: Since these three vars (`$injector`, `injector`, `callback`) are not necessary for most tests, I think it would make the tests cleaner if you removed them from here (and in `beforeEach()`) and get them only in the tests that actually use them.

2018-02-27 20:42 UTC, gkalpak commented on packages/router/test/upgrade.spec.ts
> +      get: () => {
Nit: Since `callback` is only needed it one test, this could be simplified as:

```ts
get: jasmine.createSpy('$injector.get').and.returnValue({'$on': () => undefined})
```

2018-02-27 20:42 UTC, gkalpak commented on packages/router/test/upgrade.spec.ts
> +       spyOn(injector, 'get');
This seems redundant.

2018-02-27 20:42 UTC, gkalpak commented on packages/router/test/upgrade.spec.ts
> +       expect($injector.get).toHaveBeenCalledTimes(1);
These two assertions are redundant imo. For example, you can implicitly test this, by changing the `$injector.get` spy to:

```ts
$injector.get.and.callFake((name: string) => (name === '$rootScope') && $rootScope)
```

<sub>(Keeping the tests focused on what matters most, makes them easier to follow.)</sub>

2018-02-27 20:50 UTC, gkalpak commented on packages/router/test/upgrade.spec.ts
> +/**
Which means, you should also update [this list][1].

[1]: https://github.com/angular/angular/blob/79656e7f961403fad2cc2029df2ffdea5453d71a/karma-js.conf.js#L57-L72

2018-02-27 22:10 UTC, jahumes commented
@gkalpak Thanks for the feedback! I will revisit and send you responses and fixes shortly.

2018-02-27 23:44 UTC, jahumes commented on packages/router/testing/rollup.config.js
> +  '@angular/upgrade/static': 'ng.upgrade.static'
This is a mistake from all the testing I had to do to figure out how to get the tests to run successfully

2018-02-27 23:46 UTC, jahumes commented on packages/router/testing/tsconfig-build.json
> +      "@angular/upgrade/static": ["../../../dist/packages/upgrade/static"]
Same as the above issue.

2018-02-27 23:47 UTC, jahumes commented on packages/router/karma.conf.js
> +      {pattern: 'dist/all/@angular/upgrade/static/src/**/*.js', included: false, watched: false},
The new test file upgrade.spec.ts requests this. I will review with the below request and see if I can get it to work.

2018-02-28 00:03 UTC, jahumes commented on packages/router/karma.conf.js
> +      {pattern: 'dist/all/@angular/upgrade/static/src/**/*.js', included: false, watched: false},
After reviewing this, this is required because the spec file needs the UpgradeModule for the test bed.
See line 31 of upgrade.spec.ts

2018-02-28 00:03 UTC, jahumes commented on packages/router/test/upgrade.spec.ts
> +/**
Good idea. I will make this change.

2018-02-28 00:05 UTC, jahumes commented on packages/router/test/upgrade.spec.ts
> +  it('should setup by getting the Router and Location from the Angular injector', () => {
I will remove it.

2018-02-28 00:09 UTC, jahumes commented on packages/router/test/upgrade.spec.ts
> +      get: () => {
Easy change to make.

2018-02-28 00:09 UTC, jahumes commented on packages/router/test/upgrade.spec.ts
> +  let callback: Function;
Easy change to make.

2018-02-28 00:19 UTC, jahumes commented on packages/router/test/upgrade.spec.ts
> +       spyOn(injector, 'get');
Are you talking about spying on the injector.get? I am doing this primarily to isolate the test from any side effects. I will try removing it to see if I can get away with it.

2018-02-28 00:50 UTC, jahumes commented on packages/router/test/upgrade.spec.ts
> +       expect($injector.get).toHaveBeenCalledTimes(1);
I have made this change.

2018-02-28 00:55 UTC, jahumes commented
@gkalpak I have made the changes you have requested. Please review and let me know if there is anything I have missed or still need to change.

2018-02-28 13:34 UTC, gkalpak requested changes
Thx for the quick turnaround, @jahumes 👍 
Almost there :smiley:

2018-02-28 13:34 UTC, gkalpak commented on packages/router/upgrade/test/upgrade.spec.ts
> +  });
Nit: I would simplify this test like this (but it is totally optional :grin:):

```ts
const $rootScope = jasmine.createSpyObj('$rootScope', ['$on']);
upgradeModule.$injector.get.and.returnValue($rootScope);
LocationMock.normalize.and.returnValue(pathname);

setUpLocationSync(upgradeModule);

const url = 'https://google.com';
const pathname = '/custom/route';
const query = '?query=1&query2=3';
const hash = '#new/hash';
const callback = $rootScope.$on.calls.argsFor(0)[1];

callback({}, url + pathname + query + hash, '');

expect(LocationMock.normalize).toHaveBeenCalledTimes(1);
expect(LocationMock.normalize).toHaveBeenCalledWith(pathname);

expect(RouterMock.navigateByUrl).toHaveBeenCalledTimes(1);
expect(RouterMock.navigateByUrl).toHaveBeenCalledWith(pathname + query + hash);
```

2018-02-28 15:45 UTC, jahumes commented on packages/router/karma.conf.js
> +      {pattern: 'dist/all/@angular/upgrade/static/src/**/*.js', included: false, watched: false},
So, without both of these lines, Karma can't find all of necessary files. In karma-test-shim.js, we are linking the module @angular/upgrade/static to the index.js files which includes files from the src directory. ([See here](https://github.com/jahumes/angular/blob/85247ffc3371cbb799715d3c796a01d23ed5e261/packages/router/karma-test-shim.js#L48-L49))

If I remove either one of them, I get the following error:
`
ERROR: Error{__zone_symbol__currentTask: ZoneTask{_zone: Zone{_properties: ..., _parent: ..., _name: ..., _zoneDelegate: ...}, runCount: 0, _zoneDelegates: null, _state: 'notScheduled', type: 'microTask', source: 'Promise.then', data: undefined, scheduleFn: undefined, cancelFn: null, callback: function () { ... }, invoke: function () { ... }}}
`

2018-02-28 15:52 UTC, jahumes commented on packages/router/upgrade/test/upgrade.spec.ts
> +       spyOn(upgradeModule.$injector, 'get');
Thanks. I had to modify line 31 above to not use a fat arrow function and that allowed me to remove it.

2018-02-28 15:54 UTC, jahumes commented on packages/router/upgrade/test/upgrade.spec.ts
> +  });
Thanks! I am always happy to see new ways to do things. I wasn't aware about the argsFor functionality. That makes it much easier.

2018-02-28 15:56 UTC, jahumes commented on karma-js.conf.js
> +      'dist/all/@angular/upgrade/test/**',
So sorry! I will make this change.

2018-02-28 16:13 UTC, jahumes commented
@gkalpak I have pushed another set of small changes based on your advice.

2018-03-01 09:48 UTC, mafredri commented
Thanks for your efforts @jahumes and @gkalpak, excited to see this moving along.

My co-worker just noticed that this does not work in IE 11. The problem lies in using `a.href` and relying on the output.

The `url.pathname` does not have a leading slash, which prevents `Location` from normalizing the URL:

* Chrome: `/base/user/1`
* IE 11: `base/user/1`

In IE, `base` does not match `/base` which prevents the normalization.

I'm thinking something like:

```typescript
let path = url.pathname;
if (!path.startsWith('/')) {
  path = `/${path}`;
}
path = location.normalize(path);
```

Would that cause any other problems, can we assume there always should be a leading slash?

2018-03-01 14:49 UTC, gkalpak approved these changes

2018-03-01 14:49 UTC, gkalpak commented on karma-js.conf.js
>        'dist/all/@angular/router/test/**',
This is not obsolete, since it is covered by `dist/all/@angular/router/**/test/**` below.

2018-03-01 15:23 UTC, jahumes commented
@gkalpak Is there something else I need to do? I would like to incorporate the changes suggested by @mafredri

2018-03-01 15:26 UTC, gkalpak commented
@jahumes, I pulled the commits down to try something and took the liberty to squash the commits (which should happen anyway before merging) and add some minor fixes/refactorings. You can see my changes in the second `fixup!` commit.

##
Thx @mafredri. Actually, your comment made me realize that things are even worse in IE. It is not just missing `/`; it doesn't even apply the base href. I should have known better, because we have dealt with [this very issue in AngularJS][1] :smiley:

[1]: https://github.com/angular/angular.js/blob/2c7400e7d07b0f6cec1817dab40b9250ce8ebce6/src/ng/urlUtils.js#L26-L33

2018-03-01 16:21 UTC, gkalpak commented
Added another `fixup!` commit that addresses the IE issues. @mafredri, could you verify that it works for you?

2018-03-01 16:24 UTC, gkalpak commented
Ooops, sorry @jahumes, I only now saw your previous comment :grin:

2018-03-01 17:04 UTC, mafredri commented
> Actually, your comment made me realize that things are even worse in IE. It is not just missing /; it doesn't even apply the base href.

Haha, why am I not surprised 😅.

I can verify that this works just fine in IE 11 (and Edge, Chrome, etc), thanks @gkalpak!

2018-03-01 22:49 UTC, alfaproject commented on packages/router/upgrade/src/upgrade.ts
> +    pathname: `/${anchor.pathname.replace(/^\//, '')}`,
Wouldn't this be more performant or legible? `anchor.pathname[0] === '/' ? anchor.pathname : '/' + anchor.pathname;`

2018-03-01 23:01 UTC, mafredri commented on packages/router/upgrade/src/upgrade.ts
> +    pathname: `/${anchor.pathname.replace(/^\//, '')}`,
As this is called one per navigation in AngularJS, I don't think we need to consider performance. And I'd argue ternary operator (+ verboseness) might actually be less legible than the simple regex 😄.

2018-03-02 22:47 UTC, gkalpak commented
@jahumes, we just need approval from `root` and `router` owners.

2018-04-16 21:58 UTC, jahumes commented
@gkalpak I know this isn't that high of a priority commit, but it would be nice to get this into the first bug commit in Angular 6

2018-04-18 04:39 UTC, gkalpak commented
Sorry for the delay, @jahumes. We still need approval from `root` and `router` owners.
/ping @alexeagle, @jasonaden, @IgorMinar

2018-05-02 23:02 UTC, jasonaden approved these changes
Looks good. I think if you revert the change to `karma-js.conf.js`, it will not require `root` approval and we can just move forward.

2018-05-02 23:02 UTC, jasonaden commented on karma-js.conf.js
> +      'dist/all/@angular/router/**/test/**',
This change shouldn't be needed.

2018-05-02 23:55 UTC, jahumes commented on karma-js.conf.js
> +      'dist/all/@angular/router/**/test/**',
This change was made because we added new test files outside of the router/test folder; specifically, in router/upgrade/test. Rather, than add a new line, we decided to modify the existing line to exclude all test folder like the examples folder. If you wanted to change this, we would have to move files from router/upgrade/test to router/test.

2018-05-02 23:58 UTC, alexeagle commented on karma-js.conf.js
> +      'dist/all/@angular/router/**/test/**',
@jasonaden we still run the old test fixture for now, the karma.conf.js should be deleted soon...

2018-05-02 23:58 UTC, alexeagle commented on packages/router/karma.conf.js
> +      {pattern: 'dist/all/@angular/upgrade/static/src/**/*.js', included: false, watched: false},
Do the new tests run under `bazel test //...` ?

2018-05-03 10:07 UTC, gkalpak commented on karma-js.conf.js
> +      'dist/all/@angular/router/**/test/**',
@alexeagle, do you approve of this change? 🙏

2018-06-07 04:54 UTC, KevinSchiffmann commented
Any update on this? Any chance to have it included in the next Angular 6 release?

Thank you very much

2018-06-08 17:16 UTC, gkalpak commented
/ping @alexeagle 
Do we now need changes for bazel running unit tests?

2018-06-08 18:29 UTC, alexeagle commented on karma-js.conf.js
> +      'dist/all/@angular/router/**/test/**',
sure, someone from framework team should take a TODO to remove this file very soon. @matsko maybe?

2018-06-08 18:35 UTC, alexeagle commented on packages/router/karma.conf.js
> +      {pattern: 'dist/all/@angular/upgrade/static/src/**/*.js', included: false, watched: false},
ping! we ought to make sure any added tests are being run by circleci

2018-06-08 18:36 UTC, alexeagle approved these changes
approval for `bazel`

2018-06-08 18:39 UTC, alexeagle commented
@gkalpak you just need to make sure some existing `ts_web_test_suite` target includes any newly added files.
For example if you add a new subdirectory with some specs, it's possible that no `ts_web_test_suite` picks up and runs them.

2018-06-08 18:39 UTC, gkalpak commented on packages/router/karma.conf.js
> +      {pattern: 'dist/all/@angular/upgrade/static/src/**/*.js', included: false, watched: false},
👍 I'll make sure tests are run and then mark for merge.

2018-06-11 12:36 UTC, gkalpak commented
The specs were indeed not being run under bazel (afaict). I added a commit which fixes that, but now the tests fail with:

```
==================== Test output for //packages/router/upgrade/test:test_web:
No browsers configured. Configuring Karma to use system Chrome.
11 06 2018 12:07:28.484:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
11 06 2018 12:07:28.486:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
11 06 2018 12:07:28.536:INFO [launcher]: Starting browser ChromeHeadless
11 06 2018 12:07:29.970:INFO [HeadlessChrome 63.0.3239 (Linux 0.0.0)]: Connected on socket 0SDn6LEZgg7I1HNPAAAA with id 10045697
HeadlessChrome 63.0.3239 (Linux 0.0.0) ERROR: 'There is no timestamp for tslib.js!'

11 06 2018 12:07:30.914:WARN [web-server]: 404: /tslib.js
HeadlessChrome 63.0.3239 (Linux 0.0.0) ERROR
  Script error.
  at :0:0
```

I have no clue what this means :grin:
(cc @alexeagle)

2018-06-11 14:19 UTC, alexeagle commented
It means that require.js tried to fetch `tslib.js` dynamically at runtime,
but the karma server doesn't have such a file to serve. The correct
behavior was for `tslib.js` to be bundled into the single script that karma
serves.

On Mon, Jun 11, 2018 at 5:38 AM George Kalpakas <notifications@github.com>
wrote:

> The specs were indeed not being run under bazel (afaict). I added a commit
> which fixes that, but now the tests fail with:
>
> ==================== Test output for //packages/router/upgrade/test:test_web:
> No browsers configured. Configuring Karma to use system Chrome.
> 11 06 2018 12:07:28.484:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
> 11 06 2018 12:07:28.486:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
> 11 06 2018 12:07:28.536:INFO [launcher]: Starting browser ChromeHeadless
> 11 06 2018 12:07:29.970:INFO [HeadlessChrome 63.0.3239 (Linux 0.0.0)]: Connected on socket 0SDn6LEZgg7I1HNPAAAA with id 10045697
> HeadlessChrome 63.0.3239 (Linux 0.0.0) ERROR: 'There is no timestamp for tslib.js!'
>
> 11 06 2018 12:07:30.914:WARN [web-server]: 404: /tslib.js
> HeadlessChrome 63.0.3239 (Linux 0.0.0) ERROR
>   Script error.
>   at :0:0
>
> I have no clue what this means 😁
> (cc @alexeagle <https://github.com/alexeagle>)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/20244#issuecomment-396228257>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAC5IyrJCiyNwUaIMRUBGeWqN-LOfjvZks5t7mSrgaJpZM4QVKLA>
> .
>

2018-06-11 14:33 UTC, gkalpak commented
Still no idea why or how to fix :grin:

2018-06-11 14:54 UTC, alexeagle commented
I see that you added tests for the whole upgrade/static package - I wonder
if that would fail if you made a separate PR to add that at HEAD. If so,
let's make a separate PR to add that package to `bazel test` and not hold
up this PR any more.

On Mon, Jun 11, 2018 at 7:35 AM George Kalpakas <notifications@github.com>
wrote:

> Still no idea why or how to fix 😁
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/20244#issuecomment-396265006>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAC5I8jPCbSI2bsj6att-zCCJC2ccOokks5t7oAWgaJpZM4QVKLA>
> .
>

2018-06-11 15:04 UTC, gkalpak commented
> I see that you added tests for the whole upgrade/static package

No, this PR adds tests for `router/upgrade`. It doesn't change anything wrt `upgrade/static` 😕

2018-07-23 11:31 UTC, KevinSchiffmann commented
Sorry to come again, but do you have any update on this issue? Is there anything I can do to speed up the process?

Thank you very much

2018-07-23 13:08 UTC, gkalpak commented
Oh, apparently, I [was supposed][1] to ensure the tests are run in CircleCI.
@KevinSchiffmann, can you please rebase this on master (and see if the flake goes away) and maybe add a temporary commit that makes the tests fail (to verify whether they run on CircleCI :grin:)?

[1]: https://github.com/angular/angular/pull/20244/files#r194147674

2018-07-24 13:40 UTC, gkalpak commented
You seem to have done everything fine, @KevinSchiffmann  💯

- The good news is that the tests do run on CircleCI :smiley:
- The bad news is that they fail and I have no idea why 😒
    We could probably work around the error with some [karma config][1], but I want to understand why it happens 🤔 

I wonder if we need something like [that][2] in the router Karma config.

[1]: https://github.com/karma-runner/karma-requirejs/pull/48
[2]: https://github.com/jahumes/angular/blob/a8986c183d16f396b9a743bf4a89f998b902748c/karma-js.conf.js#L103-L105

2018-07-24 14:11 UTC, alexeagle commented
@gregmagolan could you help them green this up?

2018-08-06 11:31 UTC, gkalpak commented
It should be green now. We just need another `bazel` approval, @alexeagle 🙏

2018-08-06 15:28 UTC, alexeagle approved these changes

2018-08-06 18:12 UTC, closed without merging