feat(compiler-cli): improve error messages produced during structural errors
angular/angular pull request #20459
Opened 2017-11-15 18:34 UTC by chuckjaz

The errors produced when error were encountered while interpreting the
content of a directive was often incomprehencible. With this change
these kind of error messages should be easier to understand and diagnose.

## PR Type
What kind of change does this PR introduce?

```
[x] Feature
```

## What is the current behavior?

The errors reported by static reflector are often incomprehensible.

## What is the new behavior?

The errors are now somewhat more comprehensible.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2017-11-15 18:47 UTC, mary-poppins commented
You can preview 41fc09b at https://pr20459-41fc09b.ngbuilds.io/.

2017-11-16 18:41 UTC, mary-poppins commented
You can preview 6719ce8 at https://pr20459-6719ce8.ngbuilds.io/.

2017-11-20 16:51 UTC, mary-poppins commented
You can preview d87a51c at https://pr20459-d87a51c.ngbuilds.io/.

2017-11-20 17:45 UTC, chuckjaz commented
CARETAKER: This PR increases the size of the compiler to improve the static reflector errors so the size failure is expected.

2017-11-20 17:48 UTC, vicb commented on packages/compiler-cli/src/metadata/collector.ts
> +import {Evaluator, errorSymbol, recordMapEntry, sourceInfo} from './evaluator';
do you need `sourceInfo`

2017-11-20 17:58 UTC, vicb commented on packages/compiler-cli/src/transformers/program.ts
> +    results.push(...parserErrors.map<Diagnostic>(e => ({
nit:
Do we need `const results` here ? returning directly would remove `push` and `...`

2017-11-20 17:59 UTC, vicb commented on packages/compiler-cli/src/transformers/program.ts
> +  const result: any = {fileName, text: ''};
nit: Do we need that local here (and in `diagnosticSourceOfSpan` above) ?

2017-11-20 18:04 UTC, vicb commented on packages/compiler/src/aot/formatted_error.ts
> +function indentStr(level: number): string {
nit: nice code but can't we use `''.repeat()` ?

2017-11-20 18:05 UTC, vicb commented on packages/compiler/src/aot/formatted_error.ts
> +  const prefix = position && !indent ? `${position}: ` : '';
nit: `=== 0` for `number` ?

2017-11-20 18:09 UTC, vicb commented on packages/compiler/src/aot/static_reflector.ts
> +                {message, advise, context: errorContext, chain, symbol: nestedContext}, context);
nit: IMO allocating const make it less readable vs `
{
  message: e.message,
  ...
  chain: {message: summary, position, next: e.chain}, 
}
```

2017-11-20 18:12 UTC, vicb commented on packages/compiler/src/aot/static_reflector.ts
> +    case 'Reference to non-exported class':
`''Reference to non-exported class'` would it make more sense to use constants ?

2017-11-20 18:14 UTC, vicb commented on packages/compiler/src/aot/static_symbol_resolver.ts
> +            topLevelPath.replace(/((\.ts)|(\.d\.ts)|)$/, '.ts').replace(/^.*node_modules[/\\]/, '');
q: `((\.ts)|(\.d\.ts)|)` why the last `|` ?

2017-11-20 18:16 UTC, vicb commented on packages/compiler/test/aot/static_reflector_spec.ts
> +            .toContain(`Consider changine the function expression into an exported function`);
typo `changine`

2017-11-20 18:18 UTC, vicb commented on packages/language-service/test/test_utils.ts
> +  } else if (message.message.indexOf(messageFragment) >= 0) {
nit: consider removing the `else` ?

2017-11-20 18:19 UTC, vicb requested changes
Nice PR !
A few minor findings and some nits.

2017-11-20 18:28 UTC, chuckjaz commented on packages/compiler/src/aot/formatted_error.ts
> +function indentStr(level: number): string {
We cannot use repeat yet so I am keeping this for now.

2017-11-20 18:39 UTC, chuckjaz commented on packages/compiler/src/aot/static_reflector.ts
> +                {message, advise, context: errorContext, chain, symbol: nestedContext}, context);
????

2017-11-20 18:40 UTC, chuckjaz commented on packages/compiler/src/aot/static_reflector.ts
> +    case 'Reference to non-exported class':
From where exactly?

2017-11-20 18:41 UTC, mary-poppins commented
You can preview 0e174b4 at https://pr20459-0e174b4.ngbuilds.io/.

2017-11-20 19:14 UTC, mary-poppins commented
You can preview 6abfcab at https://pr20459-6abfcab.ngbuilds.io/.

2017-11-27 22:34 UTC, vicb approved these changes

2017-11-27 23:35 UTC, mary-poppins commented
You can preview 1f8440e at https://pr20459-1f8440e.ngbuilds.io/.

2017-11-28 00:53 UTC, closed without merging