WIP(core): make a NoopZone implementation for NoopNgZone
angular/angular pull request #20640
Opened 2017-11-27 13:54 UTC by JiaLiPassion

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 20582

## What is the new behavior?
Provide a `NoopZone` implementation to implement `Zone` API when `angular` use `NgNoopZone` and not loading `zone.js`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

@mhevery , please help me to check whether my consideration is correct or not, currently in `angular` code, there are several places still call `Zone.current` , such as 

- https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L302
- https://github.com/angular/angular/blob/master/packages/platform-browser/animations/src/animation_renderer.ts#L72

I am not sure will those code be called when we use `NoopNgZone`, but if it does still call `Zone.current`, we may need to provide a `Noop Zone` implementation to just do nothing.

And in this PR, I just provide an empty `Zone` implementation, and only add `auto tick` in `Zone.wrap` which I think should `auto do tick()` .

Please review, Thank you!

2017-11-27 21:13 UTC, mhevery requested changes
I would much rather remove the reference to Zone  https://github.com/angular/angular/commit/25e5b2fdf00175291d8719cc57f0bd4d130c2c4a#diff-7f0963cbc503a361ded7d2bfec5f01b9R386 rather than trying to create a mock. Could we do that instead?

2017-11-28 00:02 UTC, JiaLiPassion commented
@mhevery , sure, I will try to rewrite it.
And I will also check the other code, such as `animation_renderer` to make sure all `Zone.current` be handled correctly under `NoopNgZone`.

2017-11-28 06:36 UTC, JiaLiPassion commented
@mhevery , I have checked the source, and I think because `zone.js` already patch `popstate`, so we don't need to use `Zone.current.wrap` in `router` any longer, 
here is the issue that why use `Zone.current.wrap`, https://github.com/angular/angular/pull/10096, I have created a sample application to test, without `Zone.current.wrap`, in safari/IE11, the back button will work as normal, and the code of `ngOnit()` will be called in `ngZone`.

Please review. thank you.

2018-01-11 13:20 UTC, mohammedzamakhan commented
Any updates on this PR??

2018-01-30 23:04 UTC, mhevery approved these changes

2018-01-30 23:06 UTC, mhevery commented
@JiaLiPassion could you rebase this on master so that we can get this in.

2018-01-31 00:09 UTC, JiaLiPassion commented
@mhevery , I have rebased the PR, please review, thank you!

2018-01-31 18:55 UTC, mhevery commented
http://test/OCL:183899528:BASE:184015406:1517424943121:4fd0de04

2018-02-02 16:01 UTC, alxhub commented
Greetings from your friendly neighborhood Angular caretaker, @jasonaden @JiaLiPassion,

This is targeted to both `master` and the patch branch, but doesn't cleanly apply on the patch branch. Can you please split the PR into two, one against `master` and the other against the `patch` branch?

Thanks,
Alex

2018-02-02 16:16 UTC, JiaLiPassion commented
@alxhub , thank you for review,  I am not sure how to do to split the PR to different branch, could you tell me more?

2018-02-02 17:02 UTC, alxhub commented
@JiaLiPassion sure thing! When you create a branch locally, you typically start on `master`. To create one for the patch branch, you'll want to start on `5.2.x` instead, then in Github when you make the PR, that becomes your target branch.

2018-02-02 18:35 UTC, mhevery commented
I have changed the target to master only. @JiaLiPassion Please create an we PR and rebase it on top of `5.2.x` branch and resubmit.

2018-02-03 00:55 UTC, JiaLiPassion commented
@mhevery , @alxhub, thank you! I have created a PR which target `5.2.x`, https://github.com/angular/angular/pull/22007. please review.

2018-02-05 21:07 UTC, closed without merging