fix(core): should check Zone existance when scheduleMicroTask
angular/angular pull request #20656
Opened 2017-11-28 07:26 UTC by JiaLiPassion

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

When use `noop ngZone` and `not` import `zone.js`, `Zone.current` will throw TypeError,
in current code, there are still several places call `Zone.current.scheduleMicroTask` directly, so 
we need to check `typeof Zone` is undefined or not, if `Zone` not exist, use `Promise.then` instead.

## What is the new behavior?

 if `Zone` not exist, use `Promise.then` instead.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2017-11-28 23:14 UTC, mhevery requested changes

2017-11-28 23:14 UTC, mhevery commented on packages/platform-browser/animations/src/animation_renderer.ts
> +      this.promise.then(() => {
perhaps we should always use a promise and not ever bother with the Zone? The only benefit to zone would be a better error message, which I don't think justifies the if.

2017-11-28 23:14 UTC, mhevery commented on packages/core/src/util.ts
> +  if (typeof Zone === 'undefined') {
We should probably just always use promise, since it will create a micro-task internally if zone is present..

2017-11-28 23:46 UTC, JiaLiPassion commented
@mhevery , yes, you are right, with zone, the only benefit is to have a formatted error message, I have updated the PR to always use `promise.then`.

2018-01-16 23:40 UTC, mhevery approved these changes

2018-01-16 23:42 UTC, mhevery commented
@JiaLiPassion This is approved, but we need to get CI green, can you look into it.

2018-01-17 01:03 UTC, JiaLiPassion commented
@mhevery , got it, I will check it.

2018-01-17 13:18 UTC, JiaLiPassion commented
@mhevery , I just updated the PR, and the reason the test cases failed is the following cases.

```javascript
const promise: Promise<any> = new Promise((res) => { resolve = res; });
_zone.onError.subscribe(() => {
  // step5
  // handleError.
});

_zone.run(() => {
  scheduleMicroTask(() => {
      // step1
      scheduleMicroTask(() => {
          resolve(null); // step2
          throw new Error('ddd'); // step3
      });
  });
});

promise.then((_) => {
    // step4
    expect(_traces.length).toBe(1);
    expect(_traces[0].length).toBeGreaterThan(1);
});
```

with the original version, `scheduleMicroTask` use `Zone.current.scheduleMicroTask`, the difference between `Zone.current.scheduleMicroTask` with `Promise.then` is the order of Error handling.

the code above, 

- with original version, `Zone.current.scheduleMicroTask`
  - step1, scheduleMicroTask->Zone.current.scheduleMicroTask
  - step2, resolve(null) -> a microTask (promise.then) was scheduled.
  - step3, throw error. the error was catch by `zone.runTask` and `zoneSpec.onHandleError` was called.
  - step5, zone.onError was called.
  - step4, promise.then was called.

- with the previous PR version, `scheduleMicroTask` use `Promise.then`.
    - step1, scheduleMicroTask->Promise.then->a microTask was scheduled.
  - step2, resolve(null) -> a microTask (promise.then) was scheduled.
  - step3, throw error. the error was catch but not invoke `zoneSpec.onHandleError` immediately, it will invoke `zoneSpec.onHandleError` until all microtasks are finished.
  - step4, promise.then was called.
  - step5, all microTasks are finished, zone.onError was called.

So the invoke order when error occurs in `scheduleMicroTask` is different. I think it is a little risky to change the order, so I just add back the original logic. 

- when `Zone` exists, still use `Zone.current.scheduleMicroTask`.
- when `Zone` not exists, use `Promise.then`.

Please review.

2018-02-02 05:18 UTC, mhevery approved these changes

2018-02-02 05:19 UTC, mhevery requested changes
reset

2018-02-02 05:19 UTC, mhevery approved these changes

2018-02-02 05:22 UTC, mhevery commented
http://test/OCL:184239105:BASE:184239114:1517548905773:3d6af1c8

2018-02-02 15:54 UTC, closed without merging