docs(aio): update myUnless references to appUnless
angular/angular pull request #20658
Opened 2017-11-28 10:06 UTC by hartraft

fixes Issue Number: #20447

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
myUnless is referenced in the documentation where appUnless is shown in code examples

Issue Number: #20447 

## What is the new behavior?
appUnless is referenced in the aio docs

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

2017-11-28 20:41 UTC, kapunahelewong commented
@hartraft You even did the e2e tests! Thanks!

@gkalpak LGTM, is there anything else I should do to help this along?

2017-11-28 20:52 UTC, kapunahelewong approved these changes

2017-11-28 22:35 UTC, gkalpak requested changes
I left a couple of minor comments.
Can you also squash the commits together?

2017-11-28 22:35 UTC, gkalpak commented on aio/content/guide/structural-directives.md
> +That means the directive needs a `appUnless` property, decorated with `@Input`
_a_ --> _an_

2017-11-28 22:35 UTC, gkalpak commented on aio/content/guide/structural-directives.md
> +Angular sets the  `appUnless` property whenever the value of the condition changes.
Unrelated to this PR, but while you are at it, feel free to fix the double-space :grin:

2017-11-29 23:11 UTC, hartraft commented
@gkalpak thanks for reviewing the PR! I've made the changes needed 😃

2017-11-30 12:59 UTC, gkalpak approved these changes

2017-11-30 13:00 UTC, gkalpak commented
The Travis failures are not related to this PR. ("Inherited" from master.)

2017-12-06 14:42 UTC, closed without merging