A couple SW fixes
angular/angular pull request #20715
Opened 2017-11-30 17:31 UTC by alxhub

2017-11-30 17:42 UTC, mary-poppins commented
You can preview f850bbc at https://pr20715-f850bbc.ngbuilds.io/.

2017-11-30 17:52 UTC, mary-poppins commented
You can preview 815891e at https://pr20715-815891e.ngbuilds.io/.

2017-11-30 18:01 UTC, mary-poppins commented
You can preview 121c135 at https://pr20715-121c135.ngbuilds.io/.

2017-11-30 18:17 UTC, mary-poppins commented
You can preview 2fb7f66 at https://pr20715-2fb7f66.ngbuilds.io/.

2017-11-30 22:24 UTC, mary-poppins commented
You can preview cc6b515 at https://pr20715-cc6b515.ngbuilds.io/.

2017-11-30 23:17 UTC, gkalpak reviewed
Is this still necessary:

https://github.com/angular/angular/blob/b922743f6e023a4fd76bf9b8e571e727073a1793/packages/service-worker/worker/src/driver.ts#L119-L131

If not, then this can probably be updated as well:

https://github.com/angular/angular/blob/b922743f6e023a4fd76bf9b8e571e727073a1793/packages/service-worker/worker/src/driver.ts#L195-L198

2017-11-30 23:17 UTC, gkalpak commented on packages/service-worker/src/module.ts
> +    // Wait for service worker controller changes, and fire an ACTIVATE action when a new SW becomes
Actually, it is an `INITIALIZE` action :grin:

2017-12-01 06:21 UTC, IgorMinar reviewed
In https://github.com/angular/angular/pull/20715/commits/b8e60e287b1aaa2cf44d1d0f49d09080c625f82a you said that "The Service Worker" had a mechanism to keep itself alive, but it's not clear if you are referring to the platform api or to our implementation on top of it.

In any case, in that description you make it sound like you are replacing one way of keeping the service worker alive with this other way. But I don't see any code being removed, only code being added. Is this right?

2017-12-01 17:21 UTC, mary-poppins commented
You can preview 6163466 at https://pr20715-6163466.ngbuilds.io/.

2017-12-01 18:01 UTC, IgorMinar requested changes

2017-12-01 18:01 UTC, IgorMinar commented on packages/service-worker/src/module.ts
> +    // Wait for service worker controller changes, and fire an ACTIVATE action when a new SW becomes
@alxhub  can you please correct this?

2017-12-01 18:01 UTC, IgorMinar approved these changes
once corrected, please mark for merge.

2017-12-01 19:40 UTC, gkalpak commented
I am still curious about https://github.com/angular/angular/pull/20715#pullrequestreview-80362233.

2017-12-01 21:54 UTC, IgorMinar approved these changes

2017-12-01 22:15 UTC, alxhub commented on packages/service-worker/src/module.ts
> +    // Wait for service worker controller changes, and fire an ACTIVATE action when a new SW becomes
Done.

2017-12-01 22:16 UTC, alxhub commented
@gkalpak yes, we still want the SW to have that behavior.

2017-12-01 22:21 UTC, merged

2017-12-01 22:28 UTC, mary-poppins commented
You can preview b607997 at https://pr20715-b607997.ngbuilds.io/.