fix(forms): ensure to emit status change events on subsequent value-update / validations
angular/angular pull request #20806
Opened 2017-12-05 17:14 UTC by kgopi

fix(forms): ensure to emit status change events on subsequent value-update / validations

RCA:

During initialization of FormControl, `emitEvent` is getting passed as `false` to `updateValueAndValidity` function, inturn the same value got passed to the `_runAsyncValidator` function. (sets status = 'PENDING') and asyncValidator will be invoked.
When we set the `FormControl` to the `FormGroup` via `FormGroup.setcontrol`, internally it is calling `updateValueAndValidity` (on FormGroup) function with `emitEvent` as undefined, it causes status change event to be emitted on `FormGroup` instance. (causes 'PENDING' status change event)
When the asyncValidator (of FormControl) got resolved, `setErrors` function is getting invoked by passing the lexical scoped variable `emitEvent` (false in this case).
As emitEvent value is `false`, susbsequent status change events are not getting notified !!

If I understand correctly, status-change-events needs to be notified on value update / validations.

Please correct me, If I am wrong.

Issue: https://github.com/angular/angular/issues/20424

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/angular/angular/issues/20424

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2017-12-06 05:15 UTC, kgopi commented
How to re-trigger the continuous-integration/travis-ci/pr job ?
Seems to be the job failed because of random issues !!

2018-06-06 11:33 UTC, HBO2 approved these changes

2019-12-11 08:17 UTC, suspectpart commented
@alexeagle, @alxhub, @amcdnl, @andrewkushnir, @andrewseguin, @angular-jira-bot, @angular-pullapprove-bot, @benlesh, @b-laporte, @bowenni, @bradlygreen, @brandonroberts, @chembu, @clydin, @crisbeto, @dennispbrown, @devversion, @evmar, @filipesilva, @foxandxss, @gkalpak, @google-admin, @googlebot, @gregmagolan, @hansl, @hazmatdance, @igorminar, @jasonaden, @jbogarthyde, @jelbourn, @jenniferfell, @johnpapa, @josephperrott, @jtraband, @juliemr, @kapunahelewong, @kara, @kyliau, @lucassloan, @manughub, @marcelgood, @marclaval, @matsko, @mgechev, @mhevery, @mmalerba, @mprobst, @narretz, @ocombe, @petebacondarwin, @pkozlowski-opensource, @rkirov, @robwormald, @sjtrimble, @stephenfluin, @vikerman, @vivian-hu, @wardbell 

Any chance we can merge this (see Discussion in https://github.com/angular/angular/issues/20424)?

2019-12-11 09:25 UTC, mprobst commented
@suspectpart: please don't spam.

2019-12-11 09:56 UTC, oyo-kgopi approved these changes

2019-12-11 12:36 UTC, suspectpart commented
> @suspectpart: please don't spam.

I am sorry for spamming you, not the best way for sure. I just didn't know who in the list of reviewers is still active and could provide some feedback. My apologies.

2020-01-07 03:19 UTC, JasonRammoray approved these changes

2020-01-07 03:26 UTC, JasonRammoray commented
Having in mind the fact that everyone is quite busy, one can't help but notice this is quite a severe issue especially in cases when a form control is being encapsulated within a container with `*ngIf` structural directive that changes its value depending on a context.
It's been a while now since the fix has been prepared for more than two years.
What shall be done in order to merge it with the master branch?
Thanks.

2020-01-08 14:34 UTC, petebacondarwin approved these changes

2020-01-08 14:34 UTC, petebacondarwin commented on packages/forms/src/model.ts
> +      emitEvent: asyncValidator ? true : false
Not sure what others think, but I would be tempted to make this shorter by using `!!asyncValidator`.

2020-01-08 14:36 UTC, petebacondarwin commented
Rebased on master...

2020-01-08 14:37 UTC, petebacondarwin commented
To land this we need a presubmit from a Googler, and a review from someone in the `angular/fw-forms` code owner group.

2020-01-09 00:44 UTC, AndrewKushnir commented
[Presubmit](https://test.corp.google.com/ui#id=OCL:288801238:BASE:288801281:1578530562979:4b4c1559)

2020-01-09 00:45 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +      emitEvent: asyncValidator ? true : false
I'd prefer shorter version as well 👍

2020-01-09 21:11 UTC, AndrewKushnir commented
Hi @kgopi, after running google3 tests, it turned out that this change breaks a few targets and additional investigation is required to find the origin of these failures and perform the necessary adjustments (either in the changes in this PR or in google3 apps code). I added the "blocked" label for now to indicate that and we'll get back to this PR once v9 final is released. Thank you.

2020-01-10 08:49 UTC, suspectpart commented
> 
> 
> Hi @kgopi, after running google3 tests, it turned out that this change breaks a few targets and additional investigation is required to find the origin of these failures and perform the necessary adjustments (either in the changes in this PR or in google3 apps code). I added the "blocked" label for now to indicate that and we'll get back to this PR once v9 final is released. Thank you.

Can you give a rough projection when this is gonna happen? Is it more like a few weeks or a couple of months?

2020-01-10 20:39 UTC, AndrewKushnir commented
> Can you give a rough projection when this is gonna happen? Is it more like a few weeks or a couple of months?

Hi @suspectpart, I can not provide any ETA at this moment unfortunately, since ETA also depends on post v9 prioritization. I've added this ticket to "v10-candidates" milestone, so it will be reviewed and prioritized after v9 is released. Thank you.

2020-02-21 17:28 UTC, JasonRammoray commented
> I added the "blocked" label for now to indicate that and we'll get back to this PR once v9 final is released.
@AndrewKushnir, the 9th version [has been rolled out ](https://angular.io/guide/updating-to-version-9)recently.
Could you, please, shed some light on google3 tests failure investigation process?
Thanks.

2020-05-15 14:35 UTC, estankovic commented
Any updates on this one? It have been a while since v9 rolled out

2020-06-15 20:09 UTC, AndrewKushnir requested changes

2020-06-15 20:09 UTC, AndrewKushnir commented on packages/forms/test/form_group_spec.ts
> +      it('should only emit (`VALID`) status change event in absence of `FormControl.asyncValidator`',
Thanks for adding tests 👍 

I think we should increase test coverage a bit more to handle additional cases, for example:

- Standalone `FormControl` with **async validator** and both `statusChanges` and `valueChanges` subscriptions and log what the output is. We should have 2 tests here tp cover both `VALID` and `INVALID` results of the validation.

- Standalone `FormControl` with **both** sync and async validators and see what happens in `statusChanges` and `valueChanges` subscriptions when sync validators return true/false and async validator returns true/false.

- Combination of `FormGroup` and a child `FormControl` to test the behavior when we *initialize* such combination and:
  - async validator is present on a `FormControl` level
  - async validator is present on both `FormGroup` and a child `FormControl` level

- Similar to the previous item, but cover the `setControl` case (this is what is partially implemented already).

- Similar to the one above, the combination of `FormArray` and a child `FormControl`: initialization phase and a case with calling some API methods that might trigger status change (like pushing new controls to the array).

- Combination of all classes: `FormGroup`, `FormArray` (as a child to the `FormGroup`) and `FormControl` (as a child to `FormArray`).

Once we have improved coverage, we can also see what the difference is in what we emit into the `statusChanges` and `valueChanges` now vs what the new set of events are. That should help better formalize the "breaking changes" note to let developers know which changes to expect and how to handle them (if needed).

Please let me know if any additional information is required.

2020-06-15 20:10 UTC, AndrewKushnir commented
Hi @kgopi, sorry for the delay in answering.

I've re-ran presubmit and it looks like there is a couple places where this change triggering some failures. I will perform additional investigation and let you know.

I also had a look at the changes and posted additional comments, mostly related to proposed increase in test coverage. Please let me know if you have any questions/comments.

Thank you.

2020-06-15 20:27 UTC, AndrewKushnir commented on packages/forms/test/form_group_spec.ts
> +      it('should only emit (`VALID`) status change event in absence of `FormControl.asyncValidator`',
Quick comment to the previous one: I think it'd also be great to have a test that would replace/remove a control (via `setControl` and/or other methods) which is running an async validator at this moment (i.e. in `PENDING` state), to see which events would be emitted in `statusChanges`.

2020-06-16 00:44 UTC, AndrewKushnir commented on packages/forms/test/form_group_spec.ts
> +      it('should only emit (`VALID`) status change event in absence of `FormControl.asyncValidator`',
Sorry, one more comment: it looks like PR https://github.com/angular/angular/pull/22575 might also be related to your PR, since it fixes the problem with async validation status, so you may see some incorrect results (described in #22575) in the `statusChanges` log until #22575 is accepted/merged.

2020-07-16 01:27 UTC, AndrewKushnir commented
Hi @kgopi,

Just want to give a quick update: the PR #22575 that I mentioned (with the fixes to the control status with async validators) has landed recently (so you should have more accurate control status in tests now). Also I've updated a couple apps in Google's codebase to be compatible with this change.

If you have a chance to perform additional updates based on the comments above (and add tests as I mentioned in https://github.com/angular/angular/pull/20806#discussion_r440416887), please let us know.

Thank you.

2020-08-28 00:05 UTC, AndrewKushnir commented
Hi @kgopi, thanks for working on this issue and proposing the fix. FYI, similar change was made in #38354, so I'm closing this PR in favor of #38354. Thank you.

2020-08-28 00:05 UTC, closed without merging