feat(aio): update url parameters on search
angular/angular pull request #20848
Opened 2017-12-07 00:01 UTC by josephperrott

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently searching on aio does not update the URL parameters of the page, which prevents direct linking to the search results. 

## What is the new behavior?
As a user searches in the search box, the URL parameters for the page are updated, replacing the state in history.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2017-12-13 16:52 UTC, petebacondarwin commented
We didn't want the URL updating as often so we removed this feature before. But we have agreed that something like this is needed. I think that the suggested solution was: it’s fine if we update it when users hit enter, and use location.replace for all subsequent (not the first) url updates.

2018-02-13 23:50 UTC, mary-poppins commented
You can preview e4e8681 at https://pr20848-e4e8681.ngbuilds.io/.
You can preview 4253ce9 at https://pr20848-4253ce9.ngbuilds.io/.
You can preview 13f3ade at https://pr20848-13f3ade.ngbuilds.io/.

2018-02-13 23:55 UTC, IgorMinar requested changes
this looks quite good except for two bugs:

- [ ] when the search input field is emptied, I'd like to see the query param disappear from the url 
- [ ] when I navigate to a url with the query param, the search input field is not initialized to the value in the query, example: https://pr20848-13f3ade.ngbuilds.io/?search=aot

2018-10-12 09:51 UTC, petebacondarwin commented
@josephperrott did you want to address the bugs identified by @IgorMinar ?

2019-02-06 19:48 UTC, closed without merging