feat(core): initial API work for tree shakable injectors
angular/angular pull request #20850
Opened 2017-12-07 00:40 UTC by tinayuangao

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Current `Injectable` don't take any parameters. 

## What is the new behavior?

`Injectable` can be used with `NgModule` and provider

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

## Other information

2017-12-07 00:48 UTC, mary-poppins commented
You can preview 408eaba at https://pr20850-408eaba.ngbuilds.io/.

2017-12-07 01:10 UTC, mary-poppins commented
You can preview 25c7788 at https://pr20850-25c7788.ngbuilds.io/.

2017-12-07 01:23 UTC, mary-poppins commented
You can preview e772936 at https://pr20850-e772936.ngbuilds.io/.

2017-12-07 01:33 UTC, mary-poppins commented
You can preview b4fd66b at https://pr20850-b4fd66b.ngbuilds.io/.

2017-12-07 17:35 UTC, mary-poppins commented
You can preview a59b047 at https://pr20850-a59b047.ngbuilds.io/.

2017-12-07 19:28 UTC, mary-poppins commented
You can preview 6fd9547 at https://pr20850-6fd9547.ngbuilds.io/.

2017-12-08 06:40 UTC, mhevery requested changes
Excellent work! We are a bit light on tests, but otherwise this is a very sold start.

Please address the comments, and I will have another look when ready

2017-12-08 06:40 UTC, mhevery commented on packages/core/src/di/injector.ts
> +      if (providerOrInjectorDefType.ngInjectorDef.imports) {
I think we need to process this in different order.
Given
```
@NgModule({
  provides: [{provide: Foo, useValue: 'fooChild'}]
})
class ModuleChild {}

@NgModule({
  provides: [{provide: Foo, useValue: 'fooParent'}]
  imports: [ModuleChild]
})
class ModuleParent {}
```
In the above case the `ModuleParent`'s `providers` should override that of `ModuleChild`, which means that `Foo` should be `fooParent` not `fooChild`. The way it is being processed now the `imports` are being overwritten. 

So I think we need to process `providers` first and than process `providers`.

Also please add a tests which demonstrates it.

2017-12-08 06:40 UTC, mhevery commented on packages/core/src/di/injector.ts
> +        token: providerOrInjectorDefType.ngInjectorDef.type,
can you add a tests which shows that `providerOrInjectorDefType.ngInjectorDef.type` gets instantiated eagerly? Which means that we will probably have to collect all of them into some array and than when the injector is done constructing we need to iterate over the array and retrieve all of the types so that they get treated.

2017-12-08 06:40 UTC, mhevery commented on packages/core/src/di/injector.ts
> +  const targetSymbol = symbols.find(symbol => token[symbol]);
using `find` is not as performant as doing a `for` loop over the array. Since retrieval is time sensitive could you use a for loop. 

Also we should be looking up the token only if we don't have `record` since otherwise we are wasting time. Please move closer to the place of use.

2017-12-08 06:40 UTC, mhevery commented on packages/core/src/di/injector.ts
> +    value = resolveProvider(provider);
We also need to create the `record` here so that the next time we get here we don't have to iterate over the symbols. Also we should add test for that.

also `token[targetSymbol` is being dereferenced twice. Since it is megamorphic let's not do it more than we have to. (so lets read it only once)

2017-12-08 06:40 UTC, mhevery commented on packages/core/src/di/injector.ts
>      value = parent.get(token, notFoundValue);
Also add record here so that we can cache the parent value. This will also increase performance.

2017-12-08 06:40 UTC, mhevery commented on packages/core/src/metadata/ng_module.ts
> +      if (ngModule) {
I don't think `ngModule` will ever be not defined. So this check is not needed.

2017-12-08 06:40 UTC, mhevery commented on packages/core/src/metadata/ng_module.ts
> +        const imports = ngModule.imports as any[];  // TODO: Need a proper way of converting.
What is the `TODO` comment for?

2017-12-08 06:40 UTC, mhevery commented on packages/core/test/di/static_injector_spec.ts
> +      const injector = new StaticInjector([SalutationModule as InjectorDefType<any>]);
1) use `Injector.create` since that is the public API.
2) Until that TS bug gets fixed we should change the public API to take `Type` so that we can avoid these casts.

2017-12-08 06:40 UTC, mhevery commented on tools/public_api_guard/core/core.d.ts
> +export interface ExistingProvider extends ExistingSanProvider {
We need to export all of the `SenProvider`s as well

2017-12-11 20:27 UTC, mary-poppins commented
You can preview a024bb2 at https://pr20850-a024bb2.ngbuilds.io/.

2017-12-11 20:31 UTC, mary-poppins commented
You can preview 38258e1 at https://pr20850-38258e1.ngbuilds.io/.

2017-12-11 21:53 UTC, mary-poppins commented
You can preview 7bd76e1 at https://pr20850-7bd76e1.ngbuilds.io/.

2017-12-11 22:24 UTC, mary-poppins commented
You can preview 863bd38 at https://pr20850-863bd38.ngbuilds.io/.

2017-12-11 23:21 UTC, mary-poppins commented
You can preview 3fb4ad2 at https://pr20850-3fb4ad2.ngbuilds.io/.

2017-12-11 23:37 UTC, mary-poppins commented
You can preview fafd80f at https://pr20850-fafd80f.ngbuilds.io/.

2017-12-12 00:32 UTC, mary-poppins commented
You can preview 59863b9 at https://pr20850-59863b9.ngbuilds.io/.

2017-12-12 00:56 UTC, mary-poppins commented
You can preview 961ee48 at https://pr20850-961ee48.ngbuilds.io/.

2017-12-12 03:10 UTC, mary-poppins commented
You can preview 1d39f0b at https://pr20850-1d39f0b.ngbuilds.io/.

2017-12-12 04:00 UTC, mary-poppins commented
You can preview d167117 at https://pr20850-d167117.ngbuilds.io/.

2017-12-12 04:31 UTC, tinayuangao commented
@mhevery Comments addressed. Please take a look. Thanks!

2017-12-13 00:19 UTC, mary-poppins commented
You can preview a10ac68 at https://pr20850-a10ac68.ngbuilds.io/.

2017-12-13 06:27 UTC, mhevery requested changes

2017-12-13 06:27 UTC, mhevery commented on packages/core/src/di/injector.ts
> +    symbols.forEach(symbol => {
Please use `for(...)` loop over `.forEach` for performance sensitive code such as this.

Also short circuit the loop once you find the record for the symbol.

2017-12-13 06:27 UTC, mhevery commented on packages/core/src/di/injector.ts
> +    if (!value) {
I don't think that `!value` is the right check since a provider could return `0` for example and this would fail your code. I think the correct check is `value !== notFoundValue`. Does that seem right to you?

Also add a tests case for this.

2017-12-13 06:27 UTC, mhevery commented on packages/core/src/metadata/ng_module.ts
> +    type: InjectorDefType<T>, deps: any[],
Can you move `type` and `deps` to be part of `opts` This way it is consistent with `defineComponent` see: https://github.com/mhevery/angular/blob/eb93a7904f0c2223610a647ab2927ccfc7c1369c/packages/core/src/render3/public_interfaces.ts#L82

2017-12-13 06:27 UTC, mhevery commented on packages/core/src/metadata/ng_module.ts
> +export function convertStaticProviders(
Could we have explicit tests for this function?

2017-12-13 06:27 UTC, mhevery commented on packages/core/test/di/static_injector_spec.ts
> +      const toast = injector.get<Toast>(Toast);
you should have an assertion such as `expect(toast instanceof Toast).toBe(true);`

2017-12-13 06:27 UTC, mhevery commented on packages/core/test/di/static_injector_spec.ts
> +    // TODO(tinayuangao): change the public API to take `Type` so we can avoid casts.
Yes, we should take care of this API, and leave a TODO to put it back once https://github.com/Microsoft/TypeScript/issues/4881 is solved

2017-12-13 06:27 UTC, mhevery commented on packages/core/test/di/static_injector_spec.ts
> +      const greeter = injector.get<Greeter>(Greeter);
add some assertions.

2017-12-13 06:27 UTC, mhevery commented on packages/core/test/di/static_injector_spec.ts
> +    it(`should child found parent's module data`, () => {
maybe: should delegate to parent injector???

2017-12-13 19:23 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +        (servideType as any)[moduleType.ngInjectorDef.symbol] = provide;
could we change this to:

```
(serviceType as InjectableType).ngInjectableDef = defineInjectable({
  module: moduleType, 
  type: injectableType
})
```

This means that you need to define `defineInjectable` method ass well `InjectableType` as someplace.

```
interface InjectableType<T> extends Type<T> {
  ngInjectableDef: Injectable
}
```

2017-12-13 19:23 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +    (servideType: Type<any>, moduleType: InjectorDefType<any>, provide: any) => {
typo `servideType` => `injectableType`

2017-12-13 19:26 UTC, mhevery requested changes

2017-12-13 19:26 UTC, mhevery commented on packages/core/src/di.ts
> +export {StaticProvider, ValueProvider, ValueSanProvider, ExistingProvider, ExistingSanProvider, FactoryProvider, FactorySanProvider, Provider, TypeProvider, ClassProvider, StaticClassSanProvider, Con
I am really sorry but this is my fault. It is `Sans` not `San`. could you rename all of theses? [dictionary sans](https://www.google.com/search?q=dictionary+sans)

2017-12-14 02:00 UTC, mary-poppins commented
You can preview 3d677c5 at https://pr20850-3d677c5.ngbuilds.io/.

2017-12-14 02:43 UTC, mary-poppins commented
You can preview c32e83e at https://pr20850-c32e83e.ngbuilds.io/.

2017-12-14 02:50 UTC, mary-poppins commented
You can preview b1296d7 at https://pr20850-b1296d7.ngbuilds.io/.

2017-12-14 03:04 UTC, mary-poppins commented
You can preview 6df26ad at https://pr20850-6df26ad.ngbuilds.io/.

2017-12-14 03:33 UTC, mary-poppins commented
You can preview 7e1df35 at https://pr20850-7e1df35.ngbuilds.io/.

2017-12-14 03:56 UTC, tinayuangao commented
@mhevery Comments addressed. Please take a look. Thanks!

2017-12-14 06:09 UTC, mhevery requested changes
Hi Tina,

sorry for a slew of comments, but there is a bit of change of direction. Please don't hesitate to come and ask me questions over chat or in person. I am happy to help and better explain things.

-- Misko

2017-12-14 06:09 UTC, mhevery commented on packages/core/src/di/injector.ts
> +function resolveProvider(provider: SupportedProvider | InjectableProvider, type?: any): Record {
revert second argument and `InjectableProvider`. It is no longer needed since the `provider` will always be `SupportedProvider`

2017-12-14 06:09 UTC, mhevery commented on packages/core/src/di/injector.ts
> +import {ConstructorProvider, ConstructorSansProvider, ExistingProvider, ExistingSansProvider, FactoryProvider, FactorySansProvider, InjectableProvider, StaticClassProvider, StaticClassSansProvider, S
There should be no imports to `Sans` in Injector. Injector should only deal with `StaticProvider`s.

2017-12-14 06:09 UTC, mhevery commented on packages/core/test/di/static_injector_spec.ts
> +    it('should instantiate a class in module from symbol', () => {
we need to add test `it('should not instantiate Injectable from not our NgModule', ...`

This test should create two modules A and B, and have Injectable on module A. It should than assert that injectA can see injectable but injectorB can not. This is the test which is missing which the last refactoring accidentally broke.

2017-12-14 17:49 UTC, mary-poppins commented
You can preview a17740f at https://pr20850-a17740f.ngbuilds.io/.

2017-12-14 19:03 UTC, tinayuangao commented on packages/core/src/di/metadata.ts
> +      (injectableType as InjectableType<any>).ngInjectableDef =
Hi Misko,

I updated the PR and addressed the comments. 
1.2.4 are done.

For 3, `StaticProvider` has `any[]` so I added `SupportedProvider` to `provider.ts`, and changed the API to `SupportedProvider`. Not sure this is desired.  
I also added code to convert `InjectableProvider` to `SupportedProvider`. This step is just setting the `provide` with type.

Please take a look. Thanks!

2017-12-14 19:20 UTC, devoto13 commented on packages/core/test/di/static_injector_spec.ts
Maybe also add a test showing if it is possible to use multiple `@Injectable()` decorators on a single class to register provider in multiple modules?

2017-12-14 20:12 UTC, mhevery requested changes

2017-12-14 20:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +export interface InjectableType<T> extends Type<T> { ngInjectableDef: Injectable; }
make `ngInjectableDef?` optional

2017-12-14 20:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +    provide: convertInjectableProviderToStatic(opt.type, opt.provide)
`provide: opt.provider`

2017-12-14 20:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +  provide?: InjectableProvider;
`provide: ResolvedProvider`

2017-12-14 20:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +            defineInjectable({module: moduleType, provide: provide, type: injectableType});
`provider: convertInjectableProviderToStatic(...)`

2017-12-14 20:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +    return provider as ValueProvider;
All of these should make a new object, rather than patching existing one.

2017-12-14 20:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +  } else if ((provider as StaticClassSansProvider).useClass) {
In the case of `StaticClassProvider` you need to compute `deps` using reflection.

2017-12-14 20:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +    return {deps: [], provide: type};
deps should use reflection to compute constructor arguments.

2017-12-14 20:12 UTC, mhevery commented on packages/core/src/di/provider.ts
> +export type InjectableProvider = ValueSansProvider | ExistingSansProvider |
Could you move this definition next to `InjectableDecorator`

2017-12-14 20:17 UTC, devoto13 commented
I really like where this is heading! Great work :) 

One thing, which worries me is that it quite drastically changes semantic meaning of the `@Injectable()` decorator: before it was marking something, what can be injected and now it marks an injection token instead. Maybe it is better to give it a new name?

Another issue is that `InjectableProvider` is a bit limited comparing to traditional providers - it is only possible to use annotated class as a DI token. However often annotated class needs to be used as a provided value for another token. See couple of examples below:

```
    { provide: HTTP_INTERCEPTORS, useClass: ErrorInterceptor, multi: true }, // providing InjectionToken
    { provide: EventManager, useClass: CustomEventManager }, // providing custom implementation for third-party service
```

In both cases I can not put `@Injectable()` on the token. Would it make sense to also allow setting `provide` property inside decorator? E.g. for above example it will be possible to do something like this:

```
@Injectable(MyModule, { provide: HTTP_INTERCEPTORS, useClass: ErrorInterceptor, multi: true })
class ErrorInterceptor { }

@Injectable(MyModule, { provide: EventManager, useClass: CustomEventManager }
class CustomEventManager { }
```

This should still be tree-shakable, but will cover more usage patterns.

2017-12-14 21:16 UTC, tinayuangao commented on packages/core/src/di/metadata.ts
> +  } else if ((provider as StaticClassSansProvider).useClass) {
I have a question here:
`StaticClassSansProvider` already have it's own `deps`. What should we do with user defined `deps`?

2017-12-15 01:48 UTC, mary-poppins commented
You can preview d32bfa2 at https://pr20850-d32bfa2.ngbuilds.io/.

2017-12-15 05:47 UTC, mary-poppins commented
You can preview 9d39919 at https://pr20850-9d39919.ngbuilds.io/.

2017-12-15 18:56 UTC, tinayuangao reviewed
@mhevery Updated the PR and addressed all the comments. Please take another look. Thanks!

2017-12-19 03:12 UTC, mhevery requested changes

2017-12-19 03:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +const USE_VALUE = 'useValue';
This will not work after Closure Compiler minifies properties. The issue is that `{useValue:0}` will get renamed to something like `{a:0}` which means your check `USE_VALUE in {a:0}` will fails. See `Injector.ts` and do `const USE_VALUE = getClosureSafeProperty<ValueProvider>({provide: String, useValue: GET_PROPERTY_NAME});`

The easiest is to probably move the `getClosureSafeProperty` into some util file and than import it here.

2017-12-19 03:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +export interface Injectable {
This is export of interface where as line 247 is an export of Value. So I think it should be fine. I looked into it and it seems to be a bug in public api guard. We can ignore it.

2017-12-19 03:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +  moduleType: Type<any>;
`Type` => `InjectorDefType`

2017-12-19 03:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +export interface DefineInjectableArgs {
This interface is same as `Injectable` interface. Let's get rid of this interface in favor of `Injectable` (so delete this).

2017-12-19 03:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +function defineInjectable(opt: DefineInjectableArgs) {
`DefineInjectableArgs` => `Injectable`

2017-12-20 00:17 UTC, mhevery requested changes
don't duplicate code.

2017-12-20 00:17 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +function getClosureSafeProperty<T>(objWithPropertyToExtract: T): string {
This is correct behavior, but now we have `getClosureSafeProperty` duplicated twice. Could we pull it into common location?

2017-12-20 04:53 UTC, mhevery approved these changes

2017-12-20 05:12 UTC, mhevery requested changes

2017-12-20 05:12 UTC, mhevery commented on packages/core/src/metadata/ng_module.ts
> +export function defineInjector<T>(opts: DefineInjectorArgs<T>): InjectorDef<T> {
1) I don't see this function exported in the public API.
2) Also I was thinking about `DefineInjectorArgs` and I think we should just inline(delete it) it in the function def. 

```
export function defineInjector<T>(opts: {
  type: InjectorDefType<T>;
  deps: any[];
  providers: StaticProvider[];
  imports: InjectorDefType<any>[];
}): InjectorDef<T> {...}
```

3) Mark it `experimenteal`

2017-12-20 05:12 UTC, mhevery commented on packages/core/src/di/metadata.ts
> +        (injectableType as InjectableType<any>).ngInjectableDef =
1) we need to have `defineInjectable` method (similar to `defineInjector`) and it has to be public and marked experimental.
```
function defineInjectable<T>(opts: InjectableType<T>): InjectableType<T> {
  return opts;
}
```

I know that the method does not do anything but we need to be consistent.
- `defineInjectable`
- `defineInjector`
Other PRs`
- `defineComponent`
- `defineDirective`
- `definePipe`

2017-12-20 20:51 UTC, tinayuangao commented on packages/core/src/metadata/ng_module.ts
> +export function defineInjector<T>(opts: DefineInjectorArgs<T>): InjectorDef<T> {
Updated. Exported `defineInjector` and removed `DefineInjectorArgs`.

Please take a look. Thanks!

2018-01-02 19:47 UTC, mhevery requested changes
I found one more issue which we need to address.

2018-01-02 19:47 UTC, mhevery commented on packages/core/src/metadata/ng_module.ts
> +      const imports = ngModule.imports as any[];
You should not have to cast to `any[]` since the type of `import` is `Array<Type<any>|ModuleWithProviders|any[]>|undefined`. Looking at it more it looks like you will have to write a function which will convert the `Array<Type<any>|ModuleWithProviders|any[]>|undefined` into `InjectorDefType<any>[]`

1. flatten nested arrays
2. assert that all `Types` have `ngInjectorDef` and hence can safely be casted to `InjectorDefType`
3. Convert `ModuleWithProviders` into `InjectorDefType`

2018-01-02 19:47 UTC, mhevery commented on packages/core/src/metadata/ng_module.ts
> +    module.providers !.forEach(provider => {
the `!` is unnecessary, please remove.

2018-01-02 19:47 UTC, mhevery commented on packages/core/src/metadata/ng_module.ts
> +        providers.push(provider);
This is not right since the child array can have providers which need to be resolved. So you need to recurse into `convertStaticProvider` here. Please add test for this.

2018-01-03 18:26 UTC, mary-poppins commented
You can preview 408eaba at https://pr20850-408eaba.ngbuilds.io/.
You can preview 25c7788 at https://pr20850-25c7788.ngbuilds.io/.
You can preview e772936 at https://pr20850-e772936.ngbuilds.io/.
You can preview b4fd66b at https://pr20850-b4fd66b.ngbuilds.io/.
You can preview d6dad71 at https://pr20850-d6dad71.ngbuilds.io/.
You can preview a59b047 at https://pr20850-a59b047.ngbuilds.io/.
You can preview 6fd9547 at https://pr20850-6fd9547.ngbuilds.io/.
You can preview a024bb2 at https://pr20850-a024bb2.ngbuilds.io/.
You can preview 38258e1 at https://pr20850-38258e1.ngbuilds.io/.
You can preview 7bd76e1 at https://pr20850-7bd76e1.ngbuilds.io/.
You can preview 863bd38 at https://pr20850-863bd38.ngbuilds.io/.
You can preview 3fb4ad2 at https://pr20850-3fb4ad2.ngbuilds.io/.
You can preview fafd80f at https://pr20850-fafd80f.ngbuilds.io/.
You can preview 59863b9 at https://pr20850-59863b9.ngbuilds.io/.
You can preview 961ee48 at https://pr20850-961ee48.ngbuilds.io/.
You can preview 1d39f0b at https://pr20850-1d39f0b.ngbuilds.io/.
You can preview d167117 at https://pr20850-d167117.ngbuilds.io/.
You can preview a10ac68 at https://pr20850-a10ac68.ngbuilds.io/.
You can preview 3d677c5 at https://pr20850-3d677c5.ngbuilds.io/.
You can preview c32e83e at https://pr20850-c32e83e.ngbuilds.io/.
You can preview b1296d7 at https://pr20850-b1296d7.ngbuilds.io/.
You can preview 6df26ad at https://pr20850-6df26ad.ngbuilds.io/.
You can preview 7e1df35 at https://pr20850-7e1df35.ngbuilds.io/.
You can preview a17740f at https://pr20850-a17740f.ngbuilds.io/.
You can preview d32bfa2 at https://pr20850-d32bfa2.ngbuilds.io/.
You can preview 9d39919 at https://pr20850-9d39919.ngbuilds.io/.
You can preview 00d6ab8 at https://pr20850-00d6ab8.ngbuilds.io/.
You can preview ec3c4a0 at https://pr20850-ec3c4a0.ngbuilds.io/.
You can preview 01d016c at https://pr20850-01d016c.ngbuilds.io/.
You can preview 585f345 at https://pr20850-585f345.ngbuilds.io/.

2018-01-03 18:26 UTC, mary-poppins commented
You can preview 2341242 at https://pr20850-2341242.ngbuilds.io/.

2018-01-03 18:35 UTC, mary-poppins commented
You can preview cf724a4 at https://pr20850-cf724a4.ngbuilds.io/.

2018-01-03 19:57 UTC, mary-poppins commented
You can preview 8e1cd1c at https://pr20850-8e1cd1c.ngbuilds.io/.

2018-01-04 22:14 UTC, mhevery approved these changes

2018-01-05 10:11 UTC, LinBoLen commented
I can't understand title. I have a little knowledge about `tree shakable`. can anyone explain `tree shakable injectors`

2018-01-05 11:38 UTC, trotyl commented
@LinBoLen It make dropping unused injectables(services) possible for size saving purpose. (In combining with proper JavaScript bundler)

2018-01-08 17:49 UTC, mary-poppins commented
You can preview 4f5c60c at https://pr20850-4f5c60c.ngbuilds.io/.

2018-01-08 18:08 UTC, mary-poppins commented
You can preview 5b0759a at https://pr20850-5b0759a.ngbuilds.io/.

2018-01-08 23:33 UTC, alexeagle commented
FYI @tinayuangao this causes some google3 test failures :red_circle: 
http://test/OCL:181226863:BASE:181226869:1515453522251:e529f628

2018-01-08 23:43 UTC, mary-poppins commented
You can preview 7b02a73 at https://pr20850-7b02a73.ngbuilds.io/.

2018-01-09 00:07 UTC, mary-poppins commented
You can preview d5e098e at https://pr20850-d5e098e.ngbuilds.io/.

2018-01-09 07:48 UTC, IgorMinar commented
We should merge this only after 5.2.0 is cut on Wednesday.

2018-01-10 07:52 UTC, mary-poppins commented
You can preview dbf6255 at https://pr20850-dbf6255.ngbuilds.io/.

2018-02-16 14:17 UTC, trotyl commented
Superseded by #22005.

2018-02-17 01:45 UTC, mhevery commented
Closing this PR since @alxhub has taken over.

2018-02-17 01:45 UTC, closed without merging