build: check clang-format in a pre-commit hook
angular/angular pull request #20884
Opened 2017-12-08 05:59 UTC by alexeagle

This moves the formatting check to the user's machine. We don't have to do this on CI anymore.

Even better, it only checks/enforces formatting in edited regions, so we can upgrade clang-format without touching the history of any files 🌮

2017-12-08 18:48 UTC, mary-poppins commented
You can preview 95d9ee1 at https://pr20884-95d9ee1.ngbuilds.io/.

2017-12-08 18:50 UTC, mary-poppins commented
You can preview 6f609a0 at https://pr20884-6f609a0.ngbuilds.io/.

2017-12-09 00:49 UTC, IgorMinar commented
please ensure that this is compatible with 5.1.x branch and it's cherry-picked there, otherwise we'll get weird errors when jumping between branches. Example:

```
$ git co update-developer-doc
Already on 'update-developer-doc'
ls: /Users/iminar/Dev/angular/hooks: No such file or directory
```

2017-12-09 00:53 UTC, IgorMinar commented
and also commit errors like: 

```
$ git commit -m "X"
ls: /Users/iminar/Dev/angular/hooks: No such file or directory
ls: /Users/iminar/Dev/angular/hooks: No such file or directory
ls: /Users/iminar/Dev/angular/hooks: No such file or directory
ls: /Users/iminar/Dev/angular/hooks: No such file or directory
```

2017-12-09 01:00 UTC, IgorMinar reviewed
does this modify the `.git` directory via `yarn postinstall` or how do the hooks get installed?

2017-12-09 01:00 UTC, IgorMinar commented on docs/DEVELOPER.md
> +and it will re-format regions that you modified in a commit.
`<irony>`
  can you please reformat this text so that there is only one sentence per line? wrapping free-form text to a column limit results in bad diffs. One sentence per line has been working as a nice compromise.
`</irony>`

2017-12-11 15:05 UTC, ocombe commented
[Manual bot mode] It seems that you have conflicts on this PR, can you rebase it with the latest changes from master please?

2017-12-11 15:14 UTC, ocombe requested changes

2017-12-11 15:14 UTC, ocombe commented on packages/language-service/src/html_info.ts
> +// This section is describes the DOM property surface of a DOM element and is derived
"is describes" --> "describes"

2017-12-11 15:14 UTC, ocombe commented on tools/gulp-tasks/format.js
> -  '!tools/gulp-tasks/cldr/extract.js',
Can you add `//clang-format disable` on the file `tools/gulp-tasks/cldr/extract.js` please? clang-format will try to change the code and since we manually generate files with ES6 template strings there, it will create wrongly-formatted TS code...

2017-12-11 15:14 UTC, ocombe commented on package.json
> +    "shared-git-hooks": "^1.2.1",
This library doesn't work on windows: https://github.com/kilianc/shared-git-hooks/issues/8
I would recommend to use https://github.com/typicode/husky instead which is the reference for shared git hooks (works on all platforms and in GUI tools as well)

2017-12-11 16:02 UTC, ocombe commented on hooks/pre-commit.clang-format
> +      curl https://raw.githubusercontent.com/llvm-mirror/clang/master/tools/clang-format/git-clang-format > /usr/local/bin/git-clang-format
it would be nice to have instructions to install this on windows too

2017-12-11 16:28 UTC, alexeagle reviewed
I fixed the versioning issue for `git-clang-format` Igor -

Martin already included the script in https://github.com/angular/clang-format/blob/master/bin/git-clang-format
so we just need to call that one. I added `format` script to the package.json to make it obvious. We don't support `git clang-format` anymore.

I added a wrapper to verify formatting in `tools/precommit.clang-format`. Ideally this wrapper should live in the clang-format repository - if this approach works well for us I'll port it there, and then document this setup to the world.

2017-12-11 16:28 UTC, alexeagle commented on docs/DEVELOPER.md
> +and it will re-format regions that you modified in a commit.
done

2017-12-11 16:28 UTC, alexeagle commented on package.json
> +    "shared-git-hooks": "^1.2.1",
switched, thanks for the pointer

2017-12-11 16:28 UTC, alexeagle commented on packages/language-service/src/html_info.ts
> +// This section is describes the DOM property surface of a DOM element and is derived
:+1:

2017-12-11 16:28 UTC, alexeagle commented on tools/gulp-tasks/format.js
> -  '!tools/gulp-tasks/cldr/extract.js',
done.

(note, you can always do this later when clang-format notices a change to a file, otherwise there is no enforcement)

2017-12-11 21:12 UTC, alexeagle commented
Igor: now that it uses husky, I moved to another branch and verified that there is no error, if the precommit yarn script is not found, it silently skips the formatting check.

Let's discuss how to land this, please. Maybe we should keep the circleci formatting check until everyone is running the new code, or there will be a gap in validation.

2017-12-11 21:18 UTC, mary-poppins commented
You can preview e21ea8c at https://pr20884-e21ea8c.ngbuilds.io/.

2017-12-11 21:20 UTC, mary-poppins commented
You can preview 1b3e243 at https://pr20884-1b3e243.ngbuilds.io/.

2017-12-11 21:42 UTC, gkalpak commented
So, there will be no format enforcing on CI? That doesn't sound right. Did I miss something 😕

2017-12-11 21:45 UTC, ocombe commented
There's a difference between "we **don't have** to do this on CI anymore" and "we won't do it on CI anymore" :-)

2017-12-11 21:50 UTC, gkalpak commented
Just to be clear, I am not referring to "We don't have to do this on CI anymore".
I am referring to the code changes (e.g. [this line][1]).

[1]: https://github.com/angular/angular/pull/20884/files#diff-b9e12334e9eafd8341a6107dd98510c9R38

2017-12-11 21:52 UTC, ocombe commented
ah good point, not sure if it is recommendable for now?

2017-12-12 00:40 UTC, alexeagle commented
@gkalpak and @ocombe there are two questions - how to manage formatting during the transition, and what to do long-term.

There is another way to possibly roll this out:
- keep clang-format version the same
- keep enforcement on CI
- I'd have to cut a point release of clang-format 1.0.49-bugfix that includes the pre-commit hook glue https://github.com/angular/clang-format/blob/master/bin/check-clang-format.js
- Turn on the hook for everyone so we can try out the new git workflow
- If there are blocking issues, then instead of rollback we can just advise you to `git commit --no-verify` and do formatting the old, slow way
- Only upgrade clang-format after everyone is happy using the hook

But in the end of this process, we still are in a state where any enforcement must be run only on what you've changed. I'm concerned that it will be tricky to get the CI to correctly calculate the delta that must be formatted (eg. we had a lot of false positives with the commit message check).
That said, I think it should be doable.

Lastly, I would like to stop working on this because I need to get ABC stuff launched this quarter...

2017-12-12 00:47 UTC, alexeagle commented
As the author of https://github.com/angular/angular/pull/19685/files#diff-3f85e628e799c057dd7411ae42bd625a maybe @petebacondarwin has some advice about running `git-clang-format` with the correct git range

2017-12-12 06:55 UTC, gkalpak commented
That code runs on CircleCI which does not expose the PR ranges (and we have to work around that). If we run format checks on Travis it should be very straight forward to get to tge files that changed in the PR's commits.

I don't feel strongly about it. I just wanted to point out that not running it on CI drops the guarantee that our code will be formatted (e.g. people can easily work around the precommit hook or people submitting changes via the web interface). I don't expect that this will create any significant issues, so fine by me :grin:

2017-12-12 08:24 UTC, petebacondarwin commented
As @gkalpak says, if you run the formatting check in Travis then you can get the commit range, specifically the [`TRAVIS_COMMIT_RANGE` environment variable](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables).

CircleCI does expose the [PR number](https://circleci.com/docs/2.0/env-vars/) but not the commits, which doesn't help as it is hard to workout what the base commit of the PR is. We found it was most straightforward to "guess" the base branch of the build by looking for the latest release label in git that matches the major and minor versions given in package.json.

2017-12-12 08:55 UTC, gkalpak commented
I was going through the [env vars][1] exposed by CircleCI again. I wonder if we could easily extract the commit ranges from `CIRCLE_COMPARE_URL` 🤔 

[1]: https://circleci.com/docs/2.0/env-vars/#circleci-environment-variable-descriptions

2017-12-12 09:33 UTC, gkalpak commented
Hm...I checked [on a PR][1] and `CIRCLE_COMPARE_URL` is empty 😞 

[1]: https://circleci.com/gh/angular/angular/27168#tests/containers/0

2017-12-12 10:18 UTC, gkalpak commented
To get some context, what is the motivation of this change:
<sub>(choose all that apply)</sub>

1. Do less work on CI?
2. Be faster on user's machine?
3. Something else?

For example, why not keep the old (slow) way on CI and add the git hook as an extra feature. Things will remain unchanged on CI, but users won't have to manually `gulp format` (and wait...) any more.

2017-12-12 13:37 UTC, alexeagle commented
Goals are:
1) get a `lint` result back from the CI in under a minute after pushing a commit
2) spend no time thinking about formatting during the dev process
3) (continue to) spend no time thinking about formatting during PR review
4) let us upgrade clang-format without reformatting everything

the last objective is why we can't continue to enforce this on CI. We will have a mix of different formatting, and this is fine. Why? For one thing, this is how we do it in Google - we have a mix of every version of clang-format if you study the sources carefully. But in practice you can barely notice. Every version we ever used produced readable code.
Here's a thought experiment. What if every file in angular's code that starts with A-M was already formatted slightly differently from L-Z? Would you care?

2017-12-12 14:47 UTC, gkalpak commented
I see. In that case, it seems that the ideal slution would be to have the hook locally and only run on affected files on CI. Since we are not super-concerned about missing a file or two (afaict), using the same "trick" as in https://github.com/angular/angular/pull/19685/files#diff-3f85e628e799c057dd7411ae42bd625a to get the affected files should be fine.

I wonder why CircleCI does not already expose the commit ranges. Doesn't sound like too much to ask :grin:

2017-12-12 14:50 UTC, alexeagle commented
I have a meeting with a sr. engineer at CircleCI tomorrow, I'll bring it up.

On Tue, Dec 12, 2017 at 6:48 AM George Kalpakas <notifications@github.com>
wrote:

> I see. In that case, it seems that the ideal slution would be to have the
> hook locally and only run on affected files on CI. Since we are not
> super-concerned about missing a file or two (afaict), using the same
> "trick" as in
> https://github.com/angular/angular/pull/19685/files#diff-3f85e628e799c057dd7411ae42bd625a
> to get the affected files should be fine.
>
> I wonder why CircleCI does not already expose the commit ranges. Doesn't
> sound like too much to ask 😁
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/20884#issuecomment-351072483>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAC5I8VDocyl5HEt3GlshSTjw_1f4vlfks5s_pJNgaJpZM4Q6ogw>
> .
>

2017-12-21 21:38 UTC, alexeagle commented
@ocombe we decided to soft-launch: we'll turn on the pre-commit hook for everyone, but if it's breaky you can opt-out and use `gulp format` the old way. We'll leave enforcement turned on in CircleCI for now.

2017-12-21 23:05 UTC, IgorMinar commented
The current installation error messages that everyone trying to make the first commit will see are a bit cryptic and hard to action on:

```
      ERROR: Found git config --get clangFormat.binary = ""
      This can result in running a different version of clang-format than your
      co-workers, leading to inconsistent formatting.

      ERROR: Found git config --get clangFormat.style = ""
      The style should be set so that the settings in .clang-format are used.

      ERROR: You need to configure git-clang-format:
      $ git config clangFormat.binary node_modules/.bin/clang-format
      $ git config clangFormat.style file
```

Could we reword them and consolidate them? example:

```
      ERROR: `git config --get clangFormat.binary` returned an empty string.

      If this property is not set, you might be using an incorrect version of clang-format,
      resulting in formatting inconsistencies that will cause the CI to fail.

      To correct this problem use:
      $ git config clangFormat.binary node_modules/.bin/clang-format


      ERROR: `git config --get clangFormat.style` returned an empty string.

      The style should be set so that the settings in .clang-format are used.

      To correct this problem use:

      $ git config clangFormat.style file
```

2017-12-21 23:07 UTC, IgorMinar commented
The current formatting error messages make it hard to find the action to take to resolve the formatting errors:

```
iminar@iminar2:~/gits/angular$ git commit -m "wip: test commit"
husky > npm run -s precommit (node v5.12.0)

diff --git a/packages/core/src/di/injector.ts b/packages/core/src/di/injector.ts
index 672773fdc4..e29226bf79 100644
--- a/packages/core/src/di/injector.ts
+++ b/packages/core/src/di/injector.ts
@@ -18,9 +18,7 @@ const _THROW_IF_NOT_FOUND = new Object();
 export const THROW_IF_NOT_FOUND = _THROW_IF_NOT_FOUND;
 
 class _NullInjector implements Injector {
-    get(token: any, notFoundValue: any = _THROW_IF_NOT_FOUND): any {
-    return notFoundValue;
-  }
+  get(token: any, notFoundValue: any = _THROW_IF_NOT_FOUND): any { return notFoundValue; }
 }
 
 /**

      ERROR: please run yarn format to format changes in your commit
```


how about:

```
      ERROR: please run format changes in your commit with:
             
      $ yarn format
```

2017-12-22 05:56 UTC, IgorMinar commented
Just for reference, @alexeagle pointed out this discussion related to husky precommit hooks and code formatting tool prettier that covers similar challenges as what we've been discussing: https://github.com/okonet/lint-staged/issues/62#issuecomment-348333347

2018-01-30 05:35 UTC, mary-poppins commented
You can preview 95d9ee1 at https://pr20884-95d9ee1.ngbuilds.io/.
You can preview 6f609a0 at https://pr20884-6f609a0.ngbuilds.io/.
You can preview e21ea8c at https://pr20884-e21ea8c.ngbuilds.io/.
You can preview 1b3e243 at https://pr20884-1b3e243.ngbuilds.io/.
You can preview e175a97 at https://pr20884-e175a97.ngbuilds.io/.
You can preview 0378889 at https://pr20884-0378889.ngbuilds.io/.

2018-01-30 05:35 UTC, mary-poppins commented
You can preview 9f4d972 at https://pr20884-9f4d972.ngbuilds.io/.

2019-05-21 22:46 UTC, alexeagle commented
Giving up on finding time to work on this

2019-05-21 22:46 UTC, closed without merging