[WIP] docs(aio): Rename service worker files, update examples, move SW under Techniques
angular/angular pull request #20893
Opened 2017-12-08 16:39 UTC by chembu

… worker under Techniques

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Doesn't test service worker functionality.
Service worker is under Fundamentals.
Issue Number: N/A

## What is the new behavior?
Service worker is under Techniques.
Working on testing service worker functionality.
Renamed service worker doc filenames.
Added server-side redirects.
Refactored examples.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

## Other information
Need help in writing e2e test for service worker.

2017-12-08 17:57 UTC, chembu commented
@alxhub, @gkalpak: Please take a look at the updated SW contents.

2017-12-11 12:40 UTC, gkalpak commented
The Travis failures seem valid. Can you please take a look?

2017-12-12 23:43 UTC, alxhub commented on aio/content/guide/service-worker-config.md
> +ngsw-config dist src/ngsw-config.json /base/href
Nice catch!

2017-12-12 23:43 UTC, alxhub approved these changes

2017-12-13 17:21 UTC, mary-poppins commented
You can preview afb227f at https://pr20893-afb227f.ngbuilds.io/.
You can preview 68d3085 at https://pr20893-68d3085.ngbuilds.io/.
You can preview b3c434a at https://pr20893-b3c434a.ngbuilds.io/.
You can preview f323654 at https://pr20893-f323654.ngbuilds.io/.
You can preview faa88ea at https://pr20893-faa88ea.ngbuilds.io/.

2017-12-13 21:09 UTC, gkalpak requested changes
Most of the issues have been fixed. Yay 💯 
A couple of comments:

1. AFAICT, the app's services are still not included in tests (see https://github.com/angular/angular/pull/20736#discussion_r155291213).

2. The plunker example is currently broken for two reasons:

    1. `environments/environment.ts` is not included.
    2. SystemJS is not configured to retrieve `@angular/service-worker`.

    Ignore (i) for now. We probably have to fix the `PlunkerBuilder`. (_EDIT: Created #20992 to track it._)

    For (ii), you need to add a mapping for `@angular/service-worker` in [systemjs.config.js][1], [systemjs.config.web.js][2], and [systemjs.config.web.build.js][3]:

    ```js
    '@angular/service-worker': 'npm:@angular/service-worker/bundles/service-worker.umd.js',
    ```

[1]: https://github.com/ExpertSupport/angular/blob/faa88ea3f7fba2afde5f82788d409b50f68d6a41/aio/tools/examples/shared/boilerplate/systemjs/src/systemjs.config.js#L17-L31
[2]: https://github.com/ExpertSupport/angular/blob/faa88ea3f7fba2afde5f82788d409b50f68d6a41/aio/tools/examples/shared/boilerplate/systemjs/src/systemjs.config.web.js#L38-L52
[3]: https://github.com/ExpertSupport/angular/blob/faa88ea3f7fba2afde5f82788d409b50f68d6a41/aio/tools/examples/shared/boilerplate/systemjs/src/systemjs.config.web.build.js#L41-L55

2017-12-13 22:59 UTC, chembu commented on aio/content/guide/service-worker-communications.md
> +* [Getting Started with Service Workers](guide/service-worker-intro).
Updated URL

2017-12-13 23:00 UTC, chembu commented on aio/content/examples/service-worker-getting-started/src/app/app.component.ts
> +        .update
Updated

2017-12-13 23:00 UTC, chembu commented on aio/content/examples/service-worker-getting-started/src/app/app.component.html
> +<p id="checkResult" *ngIf="updateCheckText !== ''">{{updateCheckText}}</p>
@kapunahelewong : please take a look

2017-12-13 23:00 UTC, chembu commented on aio/content/examples/service-worker-getting-started/e2e/app.e2e-spec.ts
> +   it('SwUpdate.checkForUpdate() should return a rejected promise', () => {
Added comment

2017-12-13 23:07 UTC, chembu commented on aio/content/examples/service-worker-getting-started/src/app/check-for-update.service.ts
>  function promptUser(event): boolean {
Removed promptUser function

2017-12-13 23:08 UTC, chembu commented on aio/content/examples/service-worker-getting-started/src/app/check-for-update.service.ts
> +import { interval } from 'rxjs/observable/interval';
Removing prompt user function makes this line just above the "interval" usage.

2017-12-13 23:08 UTC, chembu commented on aio/content/examples/service-worker-getting-started/plnkr.json
> +      "!**/*.[1,2].*"
Removed.

2017-12-13 23:24 UTC, kapunahelewong commented on aio/content/examples/service-worker-getting-started/src/app/app.component.html
> +<p id="checkResult" *ngIf="updateCheckText !== ''">{{updateCheckText}}</p>
Hey @alxhub I think this `ngIf` is necessary so we can see the failure for the e2e test, right?

2017-12-14 09:51 UTC, gkalpak commented on aio/content/examples/service-worker-getting-started/e2e/app.e2e-spec.ts
> +   it('SwUpdate.checkForUpdate() should return a rejected promise', () => {
I don't see it 😕

2017-12-14 09:52 UTC, gkalpak commented on aio/content/examples/service-worker-getting-started/plnkr.json
> +      "!**/*.[1,2].*"
I still see it 😕

2017-12-14 09:55 UTC, gkalpak commented on aio/content/examples/service-worker-getting-started/src/app/check-for-update.service.ts
> +import { interval } from 'rxjs/observable/interval';
It still has to be part of the `docregion` (so it shows up in the code snippet in the guide.

2017-12-14 09:55 UTC, gkalpak commented on aio/content/examples/service-worker-getting-started/src/app/app.component.html
> +<p id="checkResult" *ngIf="updateCheckText !== ''">{{updateCheckText}}</p>
It shouldn't be 😕

2017-12-14 10:05 UTC, gkalpak commented
I also noticed the example zip is broken, because `@angular/service-worker` is not included in dependencies. You need to add it to [package.json][1].

[1]: https://github.com/angular/angular/blob/6e2a8a2ba44b95636d975a249d52ebadc80d8347/aio/tools/example-zipper/customizer/package-json/base.json#L6-L17

2017-12-14 10:24 UTC, gkalpak commented
A couple mor comments:

- [Here][1] we mention `http-server`, but it is not sufficiently explained. (What is it? Where does it come from? How to install it?)

- The example zip is broken (for several reasons):
  - `@angular/service-worker` is not included in dependencies. You need to add it to [package.json][2].
  - The version of `@angular/cli` included in devDependencies is not compatible with `@angular/service-worker@5`.
  - We do not have `serviceWorker` enabled in `.angular-cli.json` (so it will not copy the config to `dist/`).

(The last two bullet-points are related to the `ExampleZipper` utility, so don't worry about them for now. We need to fix them.)

[1]: https://github.com/ExpertSupport/angular/blame/faa88ea3f7fba2afde5f82788d409b50f68d6a41/aio/content/guide/service-worker-getting-started.md#L101-L108
[2]: https://github.com/angular/angular/blob/6e2a8a2ba44b95636d975a249d52ebadc80d8347/aio/tools/example-zipper/customizer/package-json/base.json#L6-L17

2017-12-14 16:07 UTC, chembu commented on aio/content/examples/service-worker-getting-started/src/app/check-for-update.service.ts
> +import { interval } from 'rxjs/observable/interval';
Ok.

2017-12-14 16:13 UTC, chembu commented on aio/content/examples/service-worker-getting-started/e2e/app.e2e-spec.ts
> +   it('SwUpdate.checkForUpdate() should return a rejected promise', () => {
Didn't push the changes yet, was replying to keep track of the fix.

2017-12-14 18:53 UTC, chembu commented on aio/content/examples/service-worker-getting-started/src/app/app.component.html
> +<p id="checkResult" *ngIf="updateCheckText !== ''">{{updateCheckText}}</p>
Removed ngIf.

2017-12-14 19:03 UTC, mary-poppins commented
You can preview 7937127 at https://pr20893-7937127.ngbuilds.io/.

2017-12-14 19:43 UTC, jenniferfell commented
Re comment by @gkalpak above re HTTP server. I agree we should be more clear about what's happening here. The reader can use any HTTP they want locally. Something like this:

Because ng serve does not work with service workers, you must use a separate HTTP server to test your project locally. You can use any HTTP server. The example below uses the http-server package from npm. To reduce the possibility of conflicts, test on a dedicated port.

Maybe link from "http-server package" to this: https://www.npmjs.com/package/http-server

2017-12-14 22:47 UTC, mary-poppins commented
You can preview ae2ece3 at https://pr20893-ae2ece3.ngbuilds.io/.

2017-12-15 03:53 UTC, mary-poppins commented
You can preview c4fa613 at https://pr20893-c4fa613.ngbuilds.io/.

2017-12-18 10:05 UTC, gkalpak commented
I am marking this PR as blocked on #20165 (which converts live-examples from plnkr to stackblitz). #20165 needs to land first, then this one needs to be adapted to also use stackblitz (the process is straight forward - don't worry about it for now).

You can continue working on this PR as usual (just don't get it merged before #20165).

2017-12-18 19:26 UTC, mary-poppins commented
You can preview cc46f8b at https://pr20893-cc46f8b.ngbuilds.io/.

2017-12-18 19:36 UTC, mary-poppins commented
You can preview 95677eb at https://pr20893-95677eb.ngbuilds.io/.

2017-12-18 22:28 UTC, mary-poppins commented
You can preview 9f9e4f8 at https://pr20893-9f9e4f8.ngbuilds.io/.

2017-12-18 22:28 UTC, gkalpak commented
Except for the issues listed below, the rest LGTM 👍
The pending issues (not necessarily to be fixed in this PR):

1. The app's services are still not included in tests (see https://github.com/angular/angular/pull/20736#discussion_r155291213).

2. The plunker example is currently broken for several reasons, including:
    - `environments/environment.ts` is not included. (Fixed in #21013.)
    - SystemJS is not configured to retrieve `@angular/service-worker`.
        Requires to add a mapping for `@angular/service-worker` in [systemjs.config.js][1], [systemjs.config.web.js][2], and [systemjs.config.web.build.js][3].
    - `ngsw-worker.js` is not available in plnkr.

3. The example zip is currently broken for several reasons, including:
    - `@angular/service-worker` is not included in dependencies. Needs to be added it to [package.json][4].
    - The version of `@angular/cli` included in devDependencies is not compatible with `@angular/service-worker@5`.
    - We do not have `serviceWorker` enabled in `.angular-cli.json` (so it will not copy the config to `dist/`).

    (The last two bullet-points are related to the `ExampleZipper` utility.)

[1]: https://github.com/ExpertSupport/angular/blob/faa88ea3f7fba2afde5f82788d409b50f68d6a41/aio/tools/examples/shared/boilerplate/systemjs/src/systemjs.config.js#L17-L31
[2]: https://github.com/ExpertSupport/angular/blob/faa88ea3f7fba2afde5f82788d409b50f68d6a41/aio/tools/examples/shared/boilerplate/systemjs/src/systemjs.config.web.js#L38-L52
[3]: https://github.com/ExpertSupport/angular/blob/faa88ea3f7fba2afde5f82788d409b50f68d6a41/aio/tools/examples/shared/boilerplate/systemjs/src/systemjs.config.web.build.js#L41-L55
[4]: https://github.com/angular/angular/blob/6e2a8a2ba44b95636d975a249d52ebadc80d8347/aio/tools/example-zipper/customizer/package-json/base.json#L6-L17

2017-12-18 23:37 UTC, gkalpak approved these changes
As discussed "offline", a live-example probably doesn't make sense (since you need to update the hashes n `ngsw.json` on every file change) and the downloadable zip is currently broken (and requires aio infrastructure changes to work).

LGTM with the `<live-example>` removed from the Getting Started guide.
<sub>(The remaining issues can be addressed in separate PRs.)</sub>

2017-12-19 00:02 UTC, mary-poppins commented
You can preview 092813a at https://pr20893-092813a.ngbuilds.io/.

2017-12-19 00:04 UTC, mary-poppins commented
You can preview 95845e3 at https://pr20893-95845e3.ngbuilds.io/.

2017-12-19 10:01 UTC, mary-poppins commented
You can preview c727b5a at https://pr20893-c727b5a.ngbuilds.io/.

2017-12-19 18:21 UTC, alxhub commented
@jenniferfell waiting on your final approval.

2017-12-19 19:00 UTC, jenniferfell commented
"The bad news is that it appears that one or more commits were authored by someone other than the pull request submitter. We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that here in the pull request." 

This has been resolved.

2017-12-19 19:00 UTC, jenniferfell approved these changes

2017-12-19 19:07 UTC, merged