[WIP]docs(aio): add section on file uploads for reactive forms
angular/angular pull request #20920
Opened 2017-12-10 08:51 UTC by Toxicable

## PR Type
What kind of change does this PR introduce?

```
[x] Documentation content changes
```
This is very much a draft at this stage.
Looking for some feedback on the direction I'm taking before continuing

2018-01-02 21:36 UTC, kapunahelewong requested changes
This is great. Just a few writing style edits (to conform to the guidelines) for your consideration.

2018-01-02 21:36 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +Handling file uploads with Reactive forms has a couple of challenges we can solve with a few tools we've learnt about.
~we~ -> you 
~tools we've learnt about~ -> techniques.

2018-01-02 21:36 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +
Each point should end with a period.

2018-01-02 21:36 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +The first way to handle file uploads would be to create a `FileAccessor`, this would handle retrieving the file from the native UI element and pass it to the form. From there the file must be uploade
How about:

One way to handle file uploads is to create `FileAccessor`&mdash;this handles retrieving the file from the native UI element and passing it to the form. (Keep next sentence as is. Also notice the em dash with no spaces around it.)

2018-01-02 21:36 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +The First way would be to use a `ControlValueAccessor` which takes the file out of an input with `type=file` and pass it to the form control.
How about:

Use a `ControlValueAccessor` to take the file...

or 

Use `ControlValueAccessor`... (no "a")

2018-01-02 21:36 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +Another way would be to make a component which handled all of the file uploading for you. We could pass it the `FormControl` and expect the value to be set to the files url rather than the file itsel
What about:

~way~ --> option, ~handled~ -> handles

~We~ --> You could then pass it...

~therefore~ --> thus

2018-01-02 21:36 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +Finally we would also want to show our users the progress of our file uploads to provide some feedback. We can build onto our `FileUploadComponent` by utilizing the progress events emitted by the [Ht
How about: 
Finally, show users the progress of file uploads...

and 

~We~ --> you, ~our~ --> your

2018-01-03 15:36 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +One way to handle file uploads is to create `FileAccessor`—this handles retrieving the file from the native UI element and passing it to the form. From there the file must be uploaded along with the
gah, my apologies, I mistakenly left out the "a" in my last comment on this sentence. I meant "a `FileAccessor`", as you had previously.

2018-01-03 17:10 UTC, Toxicable commented on aio/content/guide/reactive-forms.md
> +One way to handle file uploads is to create `FileAccessor`—this handles retrieving the file from the native UI element and passing it to the form. From there the file must be uploaded along with the
Ah! thought that sounded odd there :D

2018-01-03 18:52 UTC, mary-poppins commented
You can preview c551625 at https://pr20920-c551625.ngbuilds.io/.
You can preview eaf027f at https://pr20920-eaf027f.ngbuilds.io/.
You can preview c982225 at https://pr20920-c982225.ngbuilds.io/.
You can preview 3a1b66e at https://pr20920-3a1b66e.ngbuilds.io/.

2018-01-03 21:12 UTC, wardbell requested changes
I like this idea a lot, even if it does extend what is already a long chapter.

I've added comments about things that should change (IMO) before we merge. In summary:
1. A few grammar/style issues
2. Maybe only one approach instead of two
3. Make it a working sample
4. Update the `plunker-final.json` so that the working code appears in the plunker (soon to be Stackblitz)

2018-01-03 21:12 UTC, wardbell commented on aio/content/guide/reactive-forms.md
> +Notice how the component is first setting the value to `null`, this is so that it will remove any old url if the file has been changed and so that the Required validator can be used.
Passive. Try something like:
"Notice that the component first sets the control value to null, clearing the input box of a previous URL and activating the `Required` validator."

2018-01-03 21:12 UTC, wardbell commented on aio/content/guide/reactive-forms.md
> +Finally, show users the progress of file uploads to provide some feedback. We can build onto our `FileUploadComponent` by utilizing the progress events emitted by the [HttpClient](/guide/http).
Doc style guidelines require "you" instead of "we" and they ask for the purpose to appear as an initial dependent clause. Perhaps something like:

"To provide feedback to users, you can add a `FileUploadComponent` that visually indicates file upload progress with the help of the progress events emitted by the [`HttpClient`](/guide/http)."

2018-01-04 07:15 UTC, Toxicable commented on aio/content/examples/reactive-forms/src/app/file-upload/file-upload-progress.component.ts
> +    this.httpClient.post<{ url: string }>('/file-upload', formData, { reportProgress: true, observe: 'events' })
Just one consideration about this. Since there are 2 versions (no progress and progress) do you think it would be best to have 1 service with both methods (only display one at a time) or have 2 separate services with their respective methods

2018-01-04 07:24 UTC, Toxicable commented on aio/content/guide/reactive-forms.md
> +Finally, show users the progress of file uploads to provide some feedback. We can build onto our `FileUploadComponent` by utilizing the progress events emitted by the [HttpClient](/guide/http).
done

2018-01-04 07:24 UTC, Toxicable commented on aio/content/examples/reactive-forms/src/app/file-upload/file-upload.component.ts
> +    this.httpClient.post<{ url: string }>('/file-upload', files)
as above

2018-01-04 07:39 UTC, Toxicable commented on aio/content/guide/reactive-forms.md
> +### File Upload Accessor
added a sentence explaining where the FileAccessor is useful

2018-01-04 07:39 UTC, Toxicable commented on aio/content/guide/reactive-forms.md
> +Notice how the component is first setting the value to `null`, this is so that it will remove any old url if the file has been changed and so that the Required validator can be used.
Done

2018-01-04 07:42 UTC, Toxicable commented on aio/content/guide/reactive-forms.md
> +One way to handle file uploads is to create a `FileAccessor`—this handles retrieving the file from the native UI element and passing it to the form. From there the file must be uploaded along with th
Should I maybe add another section showing how the file accessor would be used along with the rest of the form? However, I feel it might be bloating the guide a bit much.

2018-01-04 07:51 UTC, mary-poppins commented
You can preview b4e2124 at https://pr20920-b4e2124.ngbuilds.io/.

2018-01-04 09:39 UTC, rafaelss95 commented on aio/content/examples/reactive-forms/src/app/file-upload/file-accessor.directive.ts
> +        { provide: NG_VALUE_ACCESSOR, useExisting: FileValueAccessor, multi: true }
Indentation seems wrong here. In fact, there are some places that you mixed up between 2 and 4 spaces(?).

2018-01-04 17:36 UTC, Toxicable commented on aio/content/examples/reactive-forms/src/app/file-upload/file-accessor.directive.ts
> +        { provide: NG_VALUE_ACCESSOR, useExisting: FileValueAccessor, multi: true }
done

2018-01-04 17:46 UTC, mary-poppins commented
You can preview cd421dd at https://pr20920-cd421dd.ngbuilds.io/.

2018-01-04 23:34 UTC, frederikprijck commented on aio/content/examples/reactive-forms/src/app/file-upload/file-upload.service.ts
> +    const formData = new FormData();
It looks like formData isn't used?

2018-01-04 23:42 UTC, rafaelss95 commented on aio/content/examples/reactive-forms/src/app/file-upload/file-accessor.directive.ts
> +import { NG_VALUE_ACCESSOR, ControlValueAccessor } from "@angular/forms";
I guess single quotes is preferably (as you did in other files).

2018-01-04 23:42 UTC, rafaelss95 commented on aio/content/examples/reactive-forms/src/app/file-upload/file-accessor.directive.ts
> +  selector: "input[type=file]",
I guess single quotes is preferably (as you did in other files).

2018-01-04 23:45 UTC, rafaelss95 commented on aio/content/examples/reactive-forms/src/app/file-upload/file-upload.service.ts
> +    const formData = new FormData();
It's used, see the next line :)

2018-01-04 23:46 UTC, frederikprijck commented on aio/content/examples/reactive-forms/src/app/file-upload/file-upload.service.ts
> +    const formData = new FormData();
It's not passed to the post call..

2018-01-04 23:47 UTC, rafaelss95 commented
This _section_ should follow the `Angular Styleguide`? If so, check https://angular.io/guide/styleguide#style-03-06 (imports part).

2018-01-04 23:49 UTC, Toxicable commented on aio/content/examples/reactive-forms/src/app/file-upload/file-upload.service.ts
> +    const formData = new FormData();
Yup @frederikprijck is right, dunno how `files` got in there :P

2018-01-05 06:34 UTC, mary-poppins commented
You can preview fd0a110 at https://pr20920-fd0a110.ngbuilds.io/.

2018-01-14 22:29 UTC, phenomnomnominal commented on aio/content/examples/reactive-forms/src/app/file-upload/file-accessor.directive.ts
> +    this.onTouched()
missing `;`

Also, as mentioned on Gitter, `blur` is fired when the file-select dialog opens. That means the form control will be `invalid` too early.  I've solved this in the past by waiting for the `(change)` event to call the `touched` handler.

2018-01-14 22:32 UTC, phenomnomnominal commented on aio/content/guide/reactive-forms.md
> +Notice that the component first sets the control value to null, clearing the input box of a previous URL and activating the `required` validator.
The default `required` directive doesn't work with a `<input type="file">`. You can end up with an empty `FileList` if they cancel the input. 

We do something like this:

```
// Angular:
import { Directive, Input, forwardRef } from '@angular/core';
import { NG_VALIDATORS, FormControl, ValidationErrors } from '@angular/forms';

// Dependencies:
import { isBool, Value } from '@trademe/ensure';
import { ValidatorDirective } from '../validation/validator.directive';

@Directive({
    selector: `
        tg-file-uploader[required][ngModel],
        tg-file-uploader[required][formControl],
        tg-file-uploader[required][formControlName]
    `,
    providers: [
        { provide: NG_VALIDATORS, useExisting: forwardRef(() => FileUploaderRequiredDirective), multi: true }
    ]
})
export class FileUploaderRequiredDirective extends ValidatorDirective {
    @Input() @Value(isBool) public required: boolean;

    protected _validate (control: FormControl): ValidationErrors {
        let { value } = control;

        let invalid = this.required && (value == null || value && value.length === 0);

        return invalid ? { required: true } : null;
    }
}
```

2018-01-19 17:42 UTC, Toxicable commented
Closing as this section is likely more complex  than whats needed expected for this guide

2018-01-19 17:42 UTC, closed without merging