fix(forms): prevent event emission on enable/disable  when emitEvent …
angular/angular pull request #21018
Opened 2017-12-14 16:52 UTC by teh-skrud

…is false (#12366)

Previously, the emitEvent flag was only checked when emitting on the current control. Thus, if  the control was part of a hierarchy, events were emitted on the parent and the childrens. This fixes the issue by properly passing the emitEvent flag to both parent and childrens.

Fixes #12366

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2017-12-15 07:50 UTC, teh-skrud commented
I signed it!

2018-01-11 23:43 UTC, kara requested changes
Looks good, just needs the tests to be fixed.

@teh-skrud Can you ping me when this is ready for review again?

2018-01-11 23:43 UTC, kara commented on packages/forms/test/form_array_spec.ts
> +          a.valueChanges.subscribe(() => logger.push('array'));
Looks like these should be `statusChanges` subscriptions, no?

2018-01-11 23:43 UTC, kara commented on packages/forms/test/form_control_spec.ts
> +          c.valueChanges.subscribe(() => logger.push('control'));
Looks like this should be `statusChanges`

2018-01-12 10:36 UTC, teh-skrud commented
@kara : Thx for the review. I've fixed the tests and rebased the whole on the current master.

2018-02-07 00:12 UTC, kara approved these changes
LGTM

2018-02-07 01:32 UTC, kara commented
[presubmit](https://test.corp.google.com/ui#id=OCL:184767834:BASE:184767852:1517966983060:f735035a)

2018-02-07 20:06 UTC, closed without merging