fix(service-worker): check platformBrowser before accessing navigator.serviceWorker
angular/angular pull request #21231
Opened 2017-12-31 05:50 UTC by leo6104

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
bug fix for server side rendering 

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

#21230

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-03-20 14:24 UTC, gkalpak requested changes

2018-03-20 14:24 UTC, gkalpak commented on packages/service-worker/src/module.ts
> +      isPlatformBrowser(platformId) && opts.enabled !== false ? navigator.serviceWorker : undefined,
Good catch! Since you are checking for `isPlatformBrowser()` here, we don't need to pass `platformId` to the constructor any more. Could you refactor that bit out (and also update [the tests][1])?

[1]: https://github.com/leo6104/angular/blob/7bfd01442d076787a846d58b6b35e5bc9b87706c/packages/service-worker/test/comm_spec.ts

2018-03-24 20:11 UTC, levgaas commented on packages/service-worker/src/module.ts
> +      isPlatformBrowser(platformId) && opts.enabled !== false ? navigator.serviceWorker : undefined,
I've found similar logic in `ngswAppInitializer` function. What if we extract that to function.
Something like:
```
function canUseSw(options: RegistrationOptions, platformId: string): boolean {
  return isPlatformBrowser(platformId) && ('serviceWorker' in navigator) &&
      options.enabled !== false;
}
```
And then use it in
```
export function ngswCommChannelFactory(
    opts: RegistrationOptions, platformId: string): NgswCommChannel {
  return new NgswCommChannel(
      canUseSw(opts, platformId) ? navigator.serviceWorker : undefined);
}
```
and here 
```
export function ngswAppInitializer(
    injector: Injector, script: string, options: RegistrationOptions,
    platformId: string): Function {
  const initializer = () => {
    const app = injector.get<ApplicationRef>(ApplicationRef);
    if (!canUseSw(options, platformId)) {
      return;
    }
```
cc. @gkalpak

2018-03-24 21:17 UTC, levgaas commented on packages/service-worker/src/module.ts
> +      isPlatformBrowser(platformId) && opts.enabled !== false ? navigator.serviceWorker : undefined,
@gkalpak 
If we get rid of `platformId` from a constructor of `NgswCommChannel` class tests will fail. Since `platformId` is a part of:
```
if (!serviceWorker || !isPlatformBrowser(platformId)) {
  this.serviceWorker = undefined;
  this.worker = this.events = this.registration = errorObservable(ERR_SW_NOT_SUPPORTED);
}
```

Having only `serviceWorker` there is insufficient. Since we should do those sanity checks.

Also I've noticed pretty the same logic is used in both `ngswCommChannelFactory` and `NgswCommChannel` constructor.
What if we extract that into function
```
function canUseSw(options: RegistrationOptions, platformId: string): boolean {
  return isPlatformBrowser(platformId) && ('serviceWorker' in navigator) &&
      options.enabled !== false;
}
```

What are your thoughts ?

2018-03-25 05:58 UTC, gkalpak commented on packages/service-worker/src/module.ts
> +      isPlatformBrowser(platformId) && opts.enabled !== false ? navigator.serviceWorker : undefined,
What I am suggesting is removing duplicate work. (This involves not only removing the argument from the constructor, but also the usages.)

Essentially, we are now checking `isPlatformBrowser()` twice and there is no need to do that twice (afaict).

2018-03-25 08:11 UTC, levgaas commented on packages/service-worker/src/module.ts
> +      isPlatformBrowser(platformId) && opts.enabled !== false ? navigator.serviceWorker : undefined,
@gkalpak 
My apologies for being blunt =)
What I meant is that tests do something like 
```
const comm = new NgswCommChannel(mock as any, 'server');
```
or
```
const comm = new NgswCommChannel(mock as any, 'browser');
```
If we move `isPlatformBrowser()` to `ngswCommChannelFactory` then we probably would want to use 
```
const comm = ngswCommChannelFactory(mock as any, 'server');
```
Since we drop `platformId` from `NgswCommChannel` then we might want to move 
```
export function ngswCommChannelFactory(opts: RegistrationOptions, platformId: string): 
const sw = opts.enabled !== false && isPlatformBrowser(platformId) ? navigator.serviceWorker : undefined;
 {
  return new NgswCommChannel(
    , platformId);
}
```
to `ngswCommChannelFactory`

2018-03-25 11:14 UTC, levgaas commented on packages/service-worker/src/module.ts
> +      isPlatformBrowser(platformId) && opts.enabled !== false ? navigator.serviceWorker : undefined,
@gkalpak 
Agreed. Was too late when I was looking in the code ))

2018-03-26 10:50 UTC, gkalpak requested changes
I would be nice if we also tested the `ngswCommChannelFactory`...
<sub>Just saying...</sub>

2018-03-26 10:50 UTC, gkalpak commented on packages/service-worker/test/comm_spec.ts
> -      });
Maybe add a test for when the first argument passed is undefined.

2018-03-26 12:38 UTC, leo6104 commented on packages/service-worker/test/comm_spec.ts
> -      });
I agree. I thought, NgswCommChannel itself doesn't have any variable to check platform-server. 
So not just change the first argument to 'undefined', 
I replace this code to, as you said, `ngswCommChannelFactory` test code using `TestBed.configureTestingModule`.

```ts
TestBed.configureTestingModule({
          providers: [
            {provide: PLATFORM_ID, useValue: 'server'},
            {provide: RegistrationOptions, useValue: {enabled: true}}, {
              provide: NgswCommChannel,
              useFactory: ngswCommChannelFactory,
              deps: [RegistrationOptions, PLATFORM_ID]
            }
          ]
});

expect(TestBed.get(NgswCommChannel).isEnabled).toEqual(false);
```
Please review my test code. :)

2018-03-27 07:57 UTC, gkalpak commented on packages/service-worker/src/low_level.ts
>        this.serviceWorker = undefined;
This line is now unnecessary.

2018-03-27 07:57 UTC, gkalpak commented on packages/service-worker/test/comm_spec.ts
>        it('is disabled for platform-server', () => {
Could you make this a `describe` block with tests for all cases where it should be disabled (i.e. not in browser, `opts.enabled` is false, `navigator.serviceWorker` is undefined).

And once you do that, you can actually add a test to verify the actual fix that this PR adds: The `navigator.serviceWorker` is not even accessed if not in browser :grin:

2018-03-27 15:12 UTC, leo6104 commented
@gkalpak Thank you for giving me a chance to contribute angular project. :) 
Could you have a look at my commits? 

I added 3 test codes but i'm not have certainty for one test case. 
**`navigator.serviceWorker` is undefined**

If my first thought was right, i could implement the test case like below.
```ts
global.navigator.serviceWorker = undefined; // or global.navigator = {}; 
TestBed.configureTestingModule({
     providers: [
     {provide: PLATFORM_ID, useValue: 'browser'},
     {provide: RegistrationOptions, useValue: {enabled: true}}, {
         provide: NgswCommChannel,
         useFactory: ngswCommChannelFactory,
         deps: [RegistrationOptions, PLATFORM_ID]
      }
    ]
});
expect(TestBed.get(NgswCommChannel).isEnabled).toEqual(false);
```
But i concern that this way could be any side-effect to other test cases accessing `navigator.serviceWorker`

So i just implement the test code as passing first argument as undefined in NgswCommChannel like below.
```ts
it('is disabled for no SW', () => {
        const comm = new NgswCommChannel(undefined);
        expect(comm.isEnabled).toEqual(false);
});
```

2018-03-27 16:20 UTC, gkalpak commented on packages/service-worker/test/comm_spec.ts
> +      it(' gives disabled NgswCommChannel for platform-server', () => {
Please, remove the leading whitespace before `gives` (here and below).

2018-03-27 16:22 UTC, leo6104 commented on packages/service-worker/test/comm_spec.ts
> +      it(' gives disabled NgswCommChannel for platform-server', () => {
Removed!

2018-03-27 16:38 UTC, gkalpak commented
Thank you for the work you are putting into this ❤️
I would test for undefined `navigator.serviceWorker` like this:

```ts
TestBed.configureTestingModule({
  providers: [
    {provide: PLATFORM_ID, useValue: 'browser'},
    {provide: RegistrationOptions, useValue: {enabled: true}},
    {
      provide: NgswCommChannel,
      useFactory: ngswCommChannelFactory,
      deps: [RegistrationOptions, PLATFORM_ID],
    },
  ],
});

// Store the original `navigator.serviceWorker` descriptor.
// (This will be `undefined` if `serviceWorker` is a property on the prototype.)
const originalDescriptor = Object.getOwnPropertyDescriptor(navigator, 'serviceWorker');

try {
  // Set `navigator.serviceWorker` to `undefined`.
  Object.defineProperty(navigator, 'serviceWorker', {value: undefined, configurable: true});
  expect(TestBed.get(NgswCommChannel).isEnabled).toBe(false);
} finally {
  // Restore the original `navigator.serviceWorker`.
  if (originalDescriptor) {
    // Restore `serviceWorker` on the `navigator` instance itself.
    Object.defineProperty(navigator, 'serviceWorker', originalDescriptor);
  } else {
    // Delete our `serviceWorker` property on the `navigator` instance,
    // which was shadowing the actual property on  the prototype. 
    delete navigator.serviceWorker;
  }
}
```

2018-03-27 17:09 UTC, leo6104 commented
@gkalpak Wow... I saw `Object.getOwnPropertyDescriptor` method first time in here. 
It's really useful method in this case. I really appreciate for sharing your knowledge. 

There is one thing i modify `delete navigator.serviceWorker` to `delete (navigator as any).serviceWorker;`
> `delete navigator.serviceWorker` gives lint error because of readonly property of navigator.

2018-03-27 17:21 UTC, gkalpak reviewed
Looks great. Thx!
Just one last test to add :grin:

2018-03-27 17:21 UTC, gkalpak commented on packages/service-worker/test/comm_spec.ts
> +            // which was shadowing the actual property on  the prototype.
Double-space after `on` 😇

2018-03-27 17:21 UTC, gkalpak commented on packages/service-worker/test/comm_spec.ts
> +    describe('ngswCommChannelFactory', () => {
Let's also add a test showing that `ngswCommChannelFactory` gives an enabled `NgswCommChannel` (when in browser, not disabled, etc).

2018-03-27 17:50 UTC, leo6104 commented
@gkalpak How could we check navigator.serviceWorker if jasmine node does not define `navigator` variable? CircleCI Build failed with `ReferenceError: navigator is not defined`

2018-03-27 17:53 UTC, leo6104 commented on packages/service-worker/test/comm_spec.ts
> +            // which was shadowing the actual property on  the prototype.
Done!

2018-03-27 17:53 UTC, leo6104 commented on packages/service-worker/test/comm_spec.ts
> +    describe('ngswCommChannelFactory', () => {
Done!

2018-03-27 19:51 UTC, gkalpak commented
Ooops! I tried this and it seems to work :smiley:

```ts
      it('gives disabled NgswCommChannel when navigator.serviceWorker is undefined', () => {
        TestBed.configureTestingModule({
          providers: [
            {provide: PLATFORM_ID, useValue: 'browser'},
            {provide: RegistrationOptions, useValue: {enabled: true}},
            {
              provide: NgswCommChannel,
              useFactory: ngswCommChannelFactory,
              deps: [RegistrationOptions, PLATFORM_ID],
            },
          ],
        });

        // Store the original `navigator` descriptor.
        // (This will be `undefined` if `navigator` is not defined.)
        const context: any = global || window;
        const originalDescriptor = Object.getOwnPropertyDescriptor(context, 'navigator');
        const patchedDescriptor = {value: {serviceWorker: undefined}, configurable: true};

        try {
          // Set `navigator.serviceWorker` to `undefined`.
          Object.defineProperty(context, 'navigator', patchedDescriptor);
          expect(TestBed.get(NgswCommChannel).isEnabled).toBe(false);
        } finally {
          // Restore the original `navigator`.
          if (originalDescriptor) {
            Object.defineProperty(context, 'navigator', originalDescriptor);
          } else {
            delete context.navigator;
          }
        }
      });
```

2018-03-28 02:24 UTC, leo6104 commented
@gkalpak It works! :D

2018-03-28 10:41 UTC, gkalpak approved these changes
LGTM

2018-03-28 10:41 UTC, gkalpak commented on packages/service-worker/test/comm_spec.ts
> +        // (This will be `undefined` if `navigator` is a property on the prototype.)
This line is obsolete now.

2018-03-28 10:41 UTC, gkalpak commented on packages/service-worker/test/comm_spec.ts
> +            // which was shadowing the actual property on the prototype.
This comment is no longer relevant. (It is not a question of whether `navigator` was on the instance or the prototype. It is a question of whether `navigator` existed at all :grin:)

2018-03-28 10:41 UTC, gkalpak commented on packages/service-worker/test/comm_spec.ts
> +      it('gives enabled NgswCommChannel when browser support SW and enabled option is true', () => {
_support_ --> _supports_

2018-03-28 10:42 UTC, gkalpak commented
Assigned @alxhub to give the final LGTM and decide the target branch.

2018-04-22 22:07 UTC, RicardoVaranda commented
Hi guys, thanks for the great work in this PR, is there time line for when it will be merged?

2018-05-04 16:26 UTC, leo6104 commented
@alxhub Can you have a look for this PR? :D

2018-05-09 14:12 UTC, alxhub approved these changes

2018-05-09 14:35 UTC, gkalpak commented
We are almost good to go. @leo6104, could you please squash the commits into one and rebase on latest master?

2018-05-09 15:13 UTC, leo6104 commented
@gkalpak Thanks :D Rebase & Squash Done!

2018-05-22 19:10 UTC, closed without merging