fix(compiler): add support for marker tags in xliff serializers
angular/angular pull request #21250
Opened 2018-01-02 10:22 UTC by ocombe

## PR Type
What kind of change does this PR introduce?
```
[x] Bugfix
```

## What is the current behavior?
We do not support marker tags that are specified in the XLIFF spec

Issue Number: #21078

## What is the new behavior?
We support those tags (those are "inert" tags used by translation tools, we just need to ignore them and parse their contents)

## Does this PR introduce a breaking change?
```
[x] No
```

2018-01-02 10:28 UTC, mary-poppins commented
You can preview 4e7c585 at https://pr21250-4e7c585.ngbuilds.io/.

2018-01-11 19:16 UTC, vicb commented on packages/compiler/src/i18n/serializers/xliff.ts
> +const _SEGMENT_SOURCE_TAG = 'seg-source';
add `seg-source` in the commit description

2018-01-11 19:19 UTC, vicb commented on packages/compiler/src/i18n/serializers/xliff.ts
>      if (el.name === _PLACEHOLDER_TAG) {
I think this is confusing now could you please change the code to remove all else and return in each if:
```
if (...) {

if () return ...;

return null;
}

if (...) { ...; return ...}

...
return null;

```

2018-01-11 19:21 UTC, vicb commented on packages/compiler/test/i18n/serializers/xliff_spec.ts
> +          <mrk mtype="seg" mid="1">First sentence.</mrk>
The `mrk` tag will not be handled here (because it's inside a `seg-source`)

2018-01-11 19:22 UTC, vicb commented on packages/compiler/src/i18n/serializers/xliff.ts
>          // ignore source message
is the comment still valid here ?

2018-01-11 19:27 UTC, vicb commented on packages/compiler/test/i18n/serializers/xliff_spec.ts
> +        <target><mrk mtype="seg" mid="1">Translated first sentence.</mrk> <mrk mtype="seg" mid="2">Translated second sentence.</mrk></target>
question: is there any specific reason to have 2 siblings `<mrk>` ? (does this specifically test something 1 would not ?)

2018-01-11 22:07 UTC, ocombe commented on packages/compiler/test/i18n/serializers/xliff_spec.ts
> +        <target><mrk mtype="seg" mid="1">Translated first sentence.</mrk> <mrk mtype="seg" mid="2">Translated second sentence.</mrk></target>
Not really, I've just used the example from the xliff spec

2018-01-12 14:21 UTC, ocombe commented on packages/compiler/test/i18n/serializers/xliff_spec.ts
> +          <mrk mtype="seg" mid="1">First sentence.</mrk>
I think that it's better to keep the test with real code (I've used the example from the xliff spec)

2018-01-12 14:32 UTC, mary-poppins commented
You can preview cbd039e at https://pr21250-cbd039e.ngbuilds.io/.

2018-01-12 17:28 UTC, vicb commented on packages/compiler/test/i18n/serializers/xliff_spec.ts
> +          <mrk mtype="seg" mid="1">First sentence.</mrk>
I think what is important is to test the code. Here you don't test that `<seg-source>` content is skipped, please update.

2018-01-12 17:29 UTC, vicb commented on packages/compiler/test/i18n/serializers/xliff_spec.ts
> +        <target><mrk mtype="seg" mid="1">Translated first sentence.</mrk> <mrk mtype="seg" mid="2">Translated second sentence.</mrk></target>
Please use only one then so that we better understand what is tested and how

2018-01-12 17:29 UTC, vicb requested changes
see inline comments (tests)

2018-01-12 17:33 UTC, vicb commented on packages/compiler/src/i18n/serializers/xliff.ts
> +  visitElement(el: ml.Element, context: any): any|null {
Change this to be more correct: `i18n.Placeholder|ml.Node[]|null`

2018-01-12 22:42 UTC, vicb commented
add tests for nested `<mrk>`

2018-01-15 16:08 UTC, ocombe commented on packages/compiler/test/i18n/serializers/xliff_spec.ts
> +          <mrk mtype="seg" mid="1">First sentence.</mrk>
Oh I see, and it would throw if it was parsed, ok I'll update the code

2018-01-15 16:59 UTC, ocombe commented
ok PR updated, test+code added for nested `mrk` tags (I checked the spec, and it's possible)

2018-01-15 17:05 UTC, mary-poppins commented
You can preview 4e8a990 at https://pr21250-4e8a990.ngbuilds.io/.

2018-01-16 17:16 UTC, vicb approved these changes

2018-01-18 01:05 UTC, closed without merging