[WIP]: docs(aio): document the template compiler options
angular/angular pull request #21333
Opened 2018-01-05 16:18 UTC by chembu

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Added documentation for template compiler options.

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently, compiler options are not documented.
Issue Number: N/A

## What is the new behavior?
Existing AOT compiler page is updated to include compiler options.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-01-05 16:28 UTC, mary-poppins commented
You can preview 26c43da at https://pr21333-26c43da.ngbuilds.io/.

2018-01-05 17:00 UTC, chuckjaz requested changes

2018-01-05 17:00 UTC, chuckjaz commented on aio/content/guide/aot-compiler.md
> +
the ',' following "comment" is incorrect and this should read "...in the comment documenting the symbol".

2018-01-05 17:00 UTC, chuckjaz commented on aio/content/guide/aot-compiler.md
> +  produce a warning. When this option is not provided, the compiler treats it as `false`.
We don't need the sentence "When this option is not provide, the compiler treats it as `false`." as well sentence following this comment  "This option defaults to `false`." as they say the same thing.

2018-01-05 17:00 UTC, chuckjaz commented on aio/content/guide/aot-compiler.md
> +  It is recommended to set this explicitly to `false` as it emits smaller template factory modules
Consider prefixing with `*Note*:` as other similar statements about the future above.

2018-01-05 17:00 UTC, chuckjaz commented on aio/content/guide/aot-compiler.md
> +  `false` by default. This is an option used by the `bazel` rule and is needed to simplify
consider replacing "the `bazel` rule" with "`bazel` build rules" as there are more than one.

2018-01-05 17:00 UTC, chuckjaz commented on aio/content/guide/aot-compiler.md
> +For example, the _collector_ can evaluate the expression `1 + 2  3 + 4` and replace it with the result, `10`.
The removal of the `+` is incorrect and seem inadvertent.

2018-01-05 17:00 UTC, chuckjaz commented on aio/content/guide/aot-compiler.md
> +  The non-null assertion operator should be used sparingly. However, as refactoring of the component
The use of "However" here is incorrect as the sentence explains why the non-null assertion operator should be used sparingly instead of describing a special case of this general rule. Consider just eliding ". However, " and breaking the sentence in two by replacing "constraint, in" with "constraint. In".

2018-01-05 18:17 UTC, mary-poppins commented
You can preview c6f5b8d at https://pr21333-c6f5b8d.ngbuilds.io/.

2018-01-05 18:36 UTC, chembu commented on aio/content/guide/aot-compiler.md
> +  The non-null assertion operator should be used sparingly. However, as refactoring of the component
Done

2018-01-05 18:37 UTC, chembu commented on aio/content/guide/aot-compiler.md
> +For example, the _collector_ can evaluate the expression `1 + 2  3 + 4` and replace it with the result, `10`.
Done

2018-01-05 18:44 UTC, mary-poppins commented
You can preview ca53b04 at https://pr21333-ca53b04.ngbuilds.io/.

2018-01-05 18:55 UTC, mary-poppins commented
You can preview 8b51cb4 at https://pr21333-8b51cb4.ngbuilds.io/.

2018-01-05 19:08 UTC, chuckjaz approved these changes

2018-01-05 20:03 UTC, chembu commented on aio/content/guide/aot-compiler.md
> +
Done.

2018-01-05 20:03 UTC, chembu commented on aio/content/guide/aot-compiler.md
> +  produce a warning. When this option is not provided, the compiler treats it as `false`.
Done.

2018-01-05 20:04 UTC, chembu commented on aio/content/guide/aot-compiler.md
> +  It is recommended to set this explicitly to `false` as it emits smaller template factory modules
Done.

2018-01-05 20:05 UTC, chembu commented on aio/content/guide/aot-compiler.md
> +  `false` by default. This is an option used by the `bazel` rule and is needed to simplify
Done.

2018-01-05 22:18 UTC, mary-poppins commented
You can preview bb82a55 at https://pr21333-bb82a55.ngbuilds.io/.

2018-01-05 23:28 UTC, mary-poppins commented
You can preview 7c08a61 at https://pr21333-7c08a61.ngbuilds.io/.

2018-01-08 16:25 UTC, mary-poppins commented
You can preview 7f2f269 at https://pr21333-7f2f269.ngbuilds.io/.

2018-01-08 16:46 UTC, mary-poppins commented
You can preview 9b94c7e at https://pr21333-9b94c7e.ngbuilds.io/.

2018-01-08 18:25 UTC, closed without merging