style(aio): enforce strict TypeScript checks
angular/angular pull request #21342
Opened 2018-01-05 23:01 UTC by petebacondarwin

Unfortunately the version of `@angular/service-worker` that we are using (^1.0.0-beta.16)
contains an implicit `any` which is the only thing preventing the enforcement of `noImplicitAny`.
This looks like it is fixed in v5+ of the package.

Closes #20646

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2018-01-05 23:08 UTC, mary-poppins commented
You can preview 78cebb9 at https://pr21342-78cebb9.ngbuilds.io/.

2018-01-09 12:11 UTC, gkalpak requested changes
Overall LGTM 👍
Just a couple of nits and a linting error.

2018-01-09 12:11 UTC, gkalpak commented on aio/src/app/search/interfaces.ts
> +  title?: string;
OOC, under what circumstances can a search result have no associated title?

2018-01-09 14:55 UTC, petebacondarwin commented on aio/src/app/app.component.spec.ts
> +      const id = match![1]!;
if you insist

2018-01-09 16:07 UTC, gkalpak commented on aio/src/app/app.component.spec.ts
> +      const id = match![1]!;
I don't :smiley:

2018-01-10 06:54 UTC, IgorMinar commented
If I understand Pete's comment correctly, this is blocked on #19795. right?

2018-01-10 09:59 UTC, petebacondarwin commented on aio/src/app/layout/doc-viewer/doc-viewer.component.ts
> +              ? this.void$.do(() => (elem.style as any)[prop] = to)
not quite so simple since `length` and `parentRule` properties are readonly :-)

2018-01-10 10:19 UTC, petebacondarwin commented on aio/src/app/shared/custom-icon-registry.spec.ts
> +    let svgElement: any;
+1
I fixed by relaxing the return type of `createSvg(svgSrc: string): SVGElement`

2018-01-10 10:21 UTC, petebacondarwin commented on aio/src/app/shared/location.service.ts
> +    const search: { [index: string]: string|undefined; } = {};
I don't think we do 😱 - perhaps I was being over-zealous!

2018-01-10 10:28 UTC, petebacondarwin commented on aio/src/app/shared/location.service.ts
> +  setSearch(label: string, params: { [key: string]: string|undefined}) {
OK, so as far as we use this we never pass `null`, so instead of relaxing the `params` type I am going to fix the use of double equals below this.

2018-01-10 10:32 UTC, petebacondarwin commented on aio/src/app/shared/scroll-spy.service.spec.ts
> +      let lastActiveItem: ScrollItem|null|undefined;
OK, so initially I was concerned that we actually check that this value is null at the end of the test, so if none of the subscription handlers were called then this pass despite not being correct. But I now notice that before we check for it becoming null we check that it is some non-null value, so if none of the handler ran then the first expectation would fail before we get the false positive.

2018-01-10 10:33 UTC, petebacondarwin commented on aio/src/app/shared/scroll.service.spec.ts
> +              .callFake((id:string)  => id === 'top-of-page' ? topOfPage : null);
+1

2018-01-10 10:42 UTC, petebacondarwin commented on aio/src/app/sw-updates/sw-updates.service.spec.ts
> +  const run = (specFn: Function) => () => {
No idea but I changed it to `VoidFunction` just to keep you happy.

2018-01-10 10:44 UTC, petebacondarwin commented
@IgorMinar : No, this is not blocked on #19795 but we just can't turn on the final `noImplicitAny` rule until that lands. Our code is all now compliant with that rule, we just don't have it turned on.

2018-01-10 10:47 UTC, gkalpak commented on aio/src/app/layout/doc-viewer/doc-viewer.component.ts
> +              ? this.void$.do(() => (elem.style as any)[prop] = to)
Ooops 😞

2018-01-10 10:49 UTC, petebacondarwin commented on aio/src/app/shared/location.service.ts
> +  go(url: string|null|undefined) {
So we do have explicit tests for each of these scenarios: https://github.com/angular/angular/blob/master/aio/src/app/shared/location.service.spec.ts#L272
But looking at the code, we never call with `undefined` or `null` so actually let's make it tighter.

2018-01-10 10:50 UTC, mary-poppins commented
You can preview d1aa41e at https://pr21342-d1aa41e.ngbuilds.io/.

2018-01-10 10:52 UTC, mary-poppins commented
You can preview 40a4e68 at https://pr21342-40a4e68.ngbuilds.io/.

2018-01-10 12:53 UTC, petebacondarwin commented on aio/src/app/layout/doc-viewer/doc-viewer.component.ts
> +              ? this.void$.do(() => (elem.style as any)[prop] = to)
Arguably, this points out a bug in the code :-) I have put a check for those two properties.

2018-01-10 12:54 UTC, petebacondarwin commented on aio/src/app/search/interfaces.ts
> +  title?: string;
Never :-)

2018-01-10 15:03 UTC, mary-poppins commented
You can preview 124c34e at https://pr21342-124c34e.ngbuilds.io/.

2018-01-10 16:59 UTC, IgorMinar commented
@petebacondarwin I see. that makes sense. thanks

2018-01-11 12:47 UTC, gkalpak approved these changes
LGTM (as soon as CI is green :smiley:)
🎉

2018-01-11 14:38 UTC, mary-poppins commented
You can preview d133c0e at https://pr21342-d133c0e.ngbuilds.io/.

2018-01-11 14:50 UTC, petebacondarwin commented
oh I forgot about the e2e scripts

2018-01-11 18:54 UTC, mary-poppins commented
You can preview 537e4d0 at https://pr21342-537e4d0.ngbuilds.io/.

2018-01-11 22:28 UTC, gkalpak commented
File sizes were affected for some reason :grin:
The limits need to be updated.

2018-01-12 22:37 UTC, closed without merging