docs: add docs for fakeAsync test with custom macroTask in aio
angular/angular pull request #21669
Opened 2018-01-19 18:21 UTC by JiaLiPassion

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

- since `zone.js` have provided support for `fakeAsync` test with customize `macroTask` , such as test `HTMLCanvasElement.toBlob()`, so in this PR , I added document and sample in aio to describe how to do that.
- remove an unused line in `fake_async.ts`.

2018-01-22 12:05 UTC, gkalpak requested changes

2018-01-22 12:05 UTC, gkalpak commented on aio/content/examples/testing/src/app/shared/canvas.test.ts
> +}];
This file is not used anywhere, so having it be part of the example doesn't add any value imo. (It will probably become outdated sooner or later and nobody will remember to update it, so it might end up being more confusing than helpful.)

Ideally, we should be running unit tests on the examples (so that we could actually tests the fix proposed here). But, since we don't (for the time being), I think it is better to just hard-code the relevnt snippet into the `.md` file:


```
<code-example language="typescript" title="src/test.ts" "linenums="false">
  window['__zone_symbol__FakeAsyncTestMacroTask'] = [{
    source: 'HTMLCanvasElement.toBlob',
    callbackArgs: [{size: 100}]  // the test blob data which will be passed back to callback
  }];
</code-example>
```

2018-01-22 12:16 UTC, JiaLiPassion commented on aio/content/examples/testing/src/app/shared/canvas.component.spec.ts
> +// #docplaster
got it , thank you!

2018-01-22 12:16 UTC, JiaLiPassion commented on aio/content/examples/testing/src/app/shared/canvas.component.ts
> +  selector: 'twain-quote',
yes, I copied it from else where :) I will modified it.

2018-01-22 12:17 UTC, JiaLiPassion commented on aio/content/examples/testing/src/app/shared/canvas.test.ts
> +}];
yes, you are right, I will remove this file and add the content to `testing.md`

2018-01-22 12:17 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +By default `fakeAsync` support following `macroTasks`.
got it.

2018-01-22 12:17 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +if you run other `macroTask` such as `HTMLCanvasElement.toBlob()`, `Unknown macroTask scheduled in fake async test` error will be thrown.
got it.

2018-01-22 12:18 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +    title="src/app/shared/canvas.component.spec.ts (fakeAsync test)" linenums="false">
got it.

2018-01-22 12:19 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +if you want to support such case, you need to define the `macroTask` you want to support in `test.ts`
got it, thank you!

2018-01-22 12:35 UTC, JiaLiPassion commented
@gkalpak , I have updated the PR, please review, thank you.

2018-01-22 22:03 UTC, mary-poppins commented
You can preview b116034 at https://pr21669-b116034.ngbuilds.io/.
You can preview b07fbc1 at https://pr21669-b07fbc1.ngbuilds.io/.
You can preview ac6eeaa at https://pr21669-ac6eeaa.ngbuilds.io/.
You can preview 31c1eea at https://pr21669-31c1eea.ngbuilds.io/.

2018-01-22 22:06 UTC, gkalpak approved these changes
👍 LGTM (as far the example and code are concerned), but someone from the docs team has to take a look as well.

2018-01-22 22:06 UTC, gkalpak commented on aio/content/guide/testing.md
> +if you want to support such case, you need to define the `macroTask` you want to support in `test.ts` which is generated by `angular/cli`.
_if_ --> _If_

2018-01-23 00:03 UTC, JiaLiPassion commented
@gkalpak , thank you!

2018-01-25 04:51 UTC, mary-poppins commented
You can preview 106a68a at https://pr21669-106a68a.ngbuilds.io/.

2018-02-27 00:44 UTC, mary-poppins commented
You can preview fdad28d at https://pr21669-fdad28d.ngbuilds.io/.

2018-08-06 13:57 UTC, brandonroberts commented
@JiaLiPassion will you rebase this on top of master?

2018-08-06 18:45 UTC, IgorMinar approved these changes
small nitpicks, otherwise lgtm

2018-08-06 18:45 UTC, IgorMinar commented on aio/content/guide/testing.md
> +If you want to support such case, you need to define the `macroTask` you want to support in `test.ts` which is generated by `angular/cli`.
This should either be `@angular/cli` or Angular CLI, but not `angular/cli`.

2018-08-06 18:45 UTC, IgorMinar commented on aio/content/guide/testing.md
> +  callbackArgs: [{size: 100}]  // the test blob data which will be passed back to callback
it's unclear if this needs to be defined for each task scheduled via this api or if the size is the max size or what. Can you please clarify?

2018-08-06 20:42 UTC, JiaLiPassion commented
@brandonroberts, got it, I will rebase now, thank you.

2018-08-06 20:42 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +If you want to support such case, you need to define the `macroTask` you want to support in `test.ts` which is generated by `angular/cli`.
Got it!

2018-08-06 21:36 UTC, IgorMinar requested changes
I believe the `test.ts` placement of this code is wrong. Can you please change that part?

2018-08-06 21:36 UTC, IgorMinar commented on aio/content/guide/testing.md
> +  callbackArgs: [{size: 100}]  // the test blob data which will be passed back to callback
but that kind of setup needs to be performed in beforeEach as you did above or sometimes even within individual `it` specs, which then means that "you need to define the `macroTask` you want to support in `test.ts`" is the wrong advice as that's usually where the overall testing harness is setup. setting the tasks up in test.ts doesn't give you fine enough control over the arguments.

2018-08-06 21:42 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +  callbackArgs: [{size: 100}]  // the test blob data which will be passed back to callback
@IgorMinar, yes you are right, I will update the `test.md`. We should do such `setup` in `beforeEach`.

BTW, we can not do it inside `it`, because `fakeAsync` will read this variable already.

2018-08-06 22:33 UTC, mary-poppins commented
You can preview bac27d9 at https://pr21669-bac27d9.ngbuilds.io/.

2018-08-06 22:38 UTC, JiaLiPassion commented
@IgorMinar, @brandonroberts  I have updated the `sample code` and `testing.md` and move the `setup` to `beforeEach`. please review, thank you.

2018-08-06 22:40 UTC, mary-poppins commented
You can preview 89b5dde at https://pr21669-89b5dde.ngbuilds.io/.

2018-08-06 22:44 UTC, mary-poppins commented
You can preview 603dab9 at https://pr21669-603dab9.ngbuilds.io/.

2018-08-07 22:54 UTC, IgorMinar commented
I've split the change into two and fixed some indentation issues. I think it looks good now.

2018-08-07 23:00 UTC, mary-poppins commented
You can preview dd74a8d at https://pr21669-dd74a8d.ngbuilds.io/.

2018-08-07 23:00 UTC, IgorMinar approved these changes

2018-08-08 17:28 UTC, kara commented
[presubmit](http://test/OCL:207907078:BASE:207907138:1533749234765:df90ad00)

2018-08-08 20:12 UTC, closed without merging