feat(ivy): update specification to include template variables
angular/angular pull request #21677
Opened 2018-01-19 23:09 UTC by chuckjaz

## PR Type
What kind of change does this PR introduce?

```
[x] Feature
```

## What is the current behavior?

No specification how to generate variables.

## What is the new behavior?

Template variables is specified.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2018-01-19 23:16 UTC, mary-poppins commented
You can preview 2dcc5bf at https://pr21677-2dcc5bf.ngbuilds.io/.

2018-01-19 23:17 UTC, mary-poppins commented
You can preview ab3ed18 at https://pr21677-ab3ed18.ngbuilds.io/.

2018-01-22 17:52 UTC, mary-poppins commented
You can preview 2564fc0 at https://pr21677-2564fc0.ngbuilds.io/.

2018-01-22 20:30 UTC, mhevery requested changes

2018-01-22 20:30 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +          template: function(ctx: MyComponent, cm: boolean) {
`function MyComponentTemplate`

2018-01-22 20:30 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +            function C1(ctx1: any, cm: boolean) {
`C1` => `MyComponent_NgForOfDirective_1Template`

2018-01-22 20:30 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +          template: function(ctx: MyComponent, cm: boolean) {
`function MyComponentTemplate`

2018-01-22 20:30 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +            function C1(ctx1: any, cm: boolean) {
`C1` => `MyComponent_NgForOfDirective_1Template`

2018-01-22 20:30 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +              function C2(ctx2: any, cm: boolean) {
`C2` => `MyComponent_NgForOfDirective_NgForOfDirective_2Template`

2018-01-22 22:18 UTC, chuckjaz commented on packages/core/test/render3/compiler_canonical_spec.ts
> +            function C1(ctx1: any, cm: boolean) {
How about `MyComponent_NgForOfDirective_Template_1`. The infixed number looks weird to me.

2018-01-22 22:22 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +            function C1(ctx1: any, cm: boolean) {
LGTM

2018-01-22 22:39 UTC, mary-poppins commented
You can preview a6c9504 at https://pr21677-a6c9504.ngbuilds.io/.

2018-01-22 22:56 UTC, mhevery requested changes

2018-01-22 22:56 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +            function MyComponent_ForOfDirective_1(ctx1: any, cm: boolean) {
Why not end with `_Template`?

2018-01-22 22:56 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +          factory: () => new MyComponent(),
For factory method we said we needed to have a name. Do you want to do it now or later PR? (same for refresh and host)

2018-01-22 22:56 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +        factory: () => new ForOfDirective(r3.injectViewContainerRef(), r3.injectTemplateRef()),
missing name

2018-01-22 22:56 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +        refresh: (directiveIndex: number, elementIndex: number) => {
needs a name

2018-01-23 18:12 UTC, mhevery approved these changes

2018-01-23 18:28 UTC, mary-poppins commented
You can preview e0b0cee at https://pr21677-e0b0cee.ngbuilds.io/.

2018-01-23 19:02 UTC, mary-poppins commented
You can preview aa72375 at https://pr21677-aa72375.ngbuilds.io/.

2018-01-23 21:35 UTC, closed without merging