feat(ivy): support ng-content projection in the ivy compiler
angular/angular pull request #21764
Opened 2018-01-25 00:22 UTC by chuckjaz

## PR Type
What kind of change does this PR introduce?

```
[x] Feature
```

## What is the current behavior?

The ivy compiler doesn't support content projection.

## What is the new behavior?

The ivy compiler supports content projection.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2018-01-25 00:29 UTC, mary-poppins commented
You can preview 327ce09 at https://pr21764-327ce09.ngbuilds.io/.

2018-01-25 00:37 UTC, mary-poppins commented
You can preview 3d5eb7e at https://pr21764-3d5eb7e.ngbuilds.io/.

2018-01-25 01:12 UTC, vicb commented on packages/compiler/src/render3/r3_view_compiler.ts
> +    [R3SimpleCssSelector, R3SimpleCssSelector] | [null, R3SimpleCssSelector];
could positive be `null` ?

2018-01-25 01:22 UTC, vicb commented on packages/compiler/src/render3/r3_view_compiler.ts
> +      selector.classNames && selector.classNames.length ? ['class', ...selector.classNames] : [];
document the format on the type ?

2018-01-25 01:40 UTC, vicb requested changes
a few nits

2018-01-27 01:13 UTC, chuckjaz commented on packages/compiler/src/render3/r3_view_compiler.ts
> +      selector.classNames && selector.classNames.length ? ['class', ...selector.classNames] : [];
Add a reference to the documentation in core.

2018-01-27 01:20 UTC, mary-poppins commented
You can preview a20c578 at https://pr21764-a20c578.ngbuilds.io/.

2018-01-27 01:50 UTC, vicb commented on packages/compiler/src/render3/r3_view_compiler.ts
> +      selector.classNames && selector.classNames.length ? ['class', ...selector.classNames] : [];
it's more about the class part `[..., class, ...classNames]`

2018-01-27 01:52 UTC, vicb approved these changes
one doc nit

2018-01-27 03:37 UTC, chuckjaz commented on packages/compiler/src/render3/r3_view_compiler.ts
> +      selector.classNames && selector.classNames.length ? ['class', ...selector.classNames] : [];
Yes. That is documented as part of the CssSelector in the referenced file.

2018-01-29 17:00 UTC, mary-poppins commented
You can preview 3d0799a at https://pr21764-3d0799a.ngbuilds.io/.

2018-01-29 19:36 UTC, closed without merging