fix(aio): firebase redirects and service worker routing fixes
angular/angular pull request #21763
Opened 2018-01-24 22:58 UTC by petebacondarwin

Since this sits on top the previous Firebase redirects PR, this is targeting only master.
Once we are happy both PRs should be cherry picked to stable.

2018-01-24 23:06 UTC, mary-poppins commented
You can preview d753539 at https://pr21763-d753539.ngbuilds.io/.

2018-01-25 09:16 UTC, mary-poppins commented
You can preview 12003f3 at https://pr21763-12003f3.ngbuilds.io/.

2018-01-25 11:10 UTC, mary-poppins commented
You can preview 7c0557e at https://pr21763-7c0557e.ngbuilds.io/.

2018-01-25 12:29 UTC, mary-poppins commented
You can preview 606a621 at https://pr21763-606a621.ngbuilds.io/.

2018-01-25 14:26 UTC, mary-poppins commented
You can preview 8661adf at https://pr21763-8661adf.ngbuilds.io/.

2018-01-25 14:27 UTC, gkalpak requested changes
Half-way through the PR. I will finish up later today.

2018-01-25 14:27 UTC, gkalpak commented on aio/ngsw-manifest.json
> +      "^(?!/docs/.|(?:/guide/(?:cli-quickstart|metadata|ngmodule|service-worker-(?:getstart|comm|configref)|learning-angular)|/news)(?:\\.html|/)?$|/testing|/api/(?:.+/[^/]+-|platform-browser/Animati
1. The RegExp does also match URLs that end with a filename containing a `.`. This was explicitly prevented by the previous version in order to allow `.json` or `.zip`files (maybe others too) to pass through.

2. One possible branch of the RegExp boils down to: `^(?!/api/.+/[^/]+-)`
    This will not allow `-` in any segment after `/api/<foo>/`. I don't think we have any now, but who knows what happens in the future (e.g. `/api/upgrade/semi-lite/StuffDoer`). 
    (Maybe not worth worrying about too much, since this RegExp will probably become obsolete once we move to the new SW.)

3. One possible branch of the RegExp boils down to: `^(?!.*\/e?stackblitz.html$)`
    - The `e?` part is not necessary any more (afaict).
    - `.html` should be `\\.html`
    - It is safer if the RegExp handles URL both with and without the `.html` extension, because Firebase automatically drops the `.html` suffix from URLs (and it is possible -albeit improbable- that someone ends up with the stripped URL).

2018-01-25 14:31 UTC, petebacondarwin commented on aio/.angular-cli.json
> +      "config": "tests/e2e/protractor.conf.js"
It just felt like there was no where to put the new tests; and I didn't want to create yet another  new folder at the root of AIO. Any suggestions?

2018-01-25 14:33 UTC, petebacondarwin commented on aio/ngsw-manifest.json
> +      "^(?!/docs/.|(?:/guide/(?:cli-quickstart|metadata|ngmodule|service-worker-(?:getstart|comm|configref)|learning-angular)|/news)(?:\\.html|/)?$|/testing|/api/(?:.+/[^/]+-|platform-browser/Animati
1) I'll add these cases to the test harness and then fix them.

2018-01-25 14:42 UTC, petebacondarwin commented on aio/tools/firebase-test-utils/FirebaseGlob.ts
> +const possibleEmptySegments = /([/^]).🐷\//g       // e.g. `a/**/b` can also match `a/b`
I need to read that book :-) .

Interestingly I do have a test case for this: https://github.com/angular/angular/pull/21763/files#diff-22e59ed41aedd162e2e04b5612493359R19 so perhaps it is not even needed.

2018-01-25 14:50 UTC, petebacondarwin commented on aio/tools/firebase-test-utils/FirebaseGlob.ts
> +const possibleEmptySegments = /([/^]).🐷\//g       // e.g. `a/**/b` can also match `a/b`
Actually we can't do it this way, because the `^` doesn't get passed through to the `$1` in the replace.

2018-01-25 16:35 UTC, gkalpak reviewed
Some more comments (still not done 😞).

2018-01-25 19:07 UTC, petebacondarwin commented on aio/.angular-cli.json
> +      "config": "tests/e2e/protractor.conf.js"
But it feels weird to have app specific tests inside the tools folder.

2018-01-25 20:20 UTC, petebacondarwin commented on aio/tests/deployment/testServiceWorkerRoutes.spec.ts
> +      expect(routes.every(test => test(url))).toBeTruthy(url);
Of course! Doesn't make a difference when there is only one route though I guess :-)

2018-01-25 20:27 UTC, mary-poppins commented
You can preview decc1ca at https://pr21763-decc1ca.ngbuilds.io/.

2018-01-25 21:51 UTC, mary-poppins commented
You can preview fba45e1 at https://pr21763-fba45e1.ngbuilds.io/.

2018-01-26 08:09 UTC, mary-poppins commented
You can preview a96c732 at https://pr21763-a96c732.ngbuilds.io/.

2018-01-26 10:11 UTC, gkalpak requested changes
Review - part 3/3 :grin:

2018-01-26 10:11 UTC, gkalpak commented on aio/firebase.json
> +      {"type": 301, "source": "/api/animate/:rest*", "destination": "/api/animations/:rest"},
According to the Firebase [docs example][1], you need to keep the `*` in the destination:

```
"redirects": [
  {
    "source": "/blog/:post*",
    "destination": "https://blog.myapp.com/:post*",
    "type": 301
  },
  ...
]
```

(If that is indeed the case, `FirebaseGlob` needs to be adjusted accordingly as well.)

[1]: https://firebase.google.com/docs/hosting/full-config#redirects

2018-01-26 11:04 UTC, petebacondarwin commented on aio/firebase.json
> +      {"type": 301, "source": "/api/animate/:rest*", "destination": "/api/animations/:rest"},
Ahah! That is why I had the `*` there in the first place. Good spot, thanks

2018-01-26 14:59 UTC, petebacondarwin commented on aio/tools/firebase-test-utils/FirebaseGlob.spec.ts
> +      testGlob('asdf/**.jpg',
It seems that in this case Firebase treats it like two separate `*`s.
Matches: `asdf/a.jpg`, `asdf/abc.jpg`
Does not match: `asdf/.jpg`, `asdf/a/b.jpg`

2018-01-26 15:50 UTC, petebacondarwin commented on aio/firebase.json
> +      {"type": 301, "source": "/api/animate/:rest*", "destination": "/api/animations/:rest"},
This is fun. You do need the * on the end, but if you happen to have one param with a star and one without then the first one appears to win. Of course that is totally weird so shouldn't happen in practice.

2018-01-26 15:55 UTC, petebacondarwin commented on aio/tools/firebase-test-utils/FirebaseGlob.ts
> +        .replace(namedParamExtra, '/(?<$1>.+)?')        // capture the rest of the string
yes it does match

2018-01-26 15:56 UTC, petebacondarwin commented on aio/tools/firebase-test-utils/FirebaseGlob.ts
> +        .replace(namedParam, '/(?<$1>[^/]+)')           // capture the named parameter
No

2018-01-27 10:31 UTC, petebacondarwin commented on aio/tools/firebase-test-utils/FirebaseGlob.spec.ts
> +        ['/asdf/asdf.jpg', ]);
a leading `/` and a `.js` actually matches :-)

2018-01-27 14:22 UTC, petebacondarwin commented on aio/tools/firebase-test-utils/FirebaseGlob.spec.ts
> +      testGlob('aaa/*.@(bbb|ccc)',
we now throw an unsupported error in the test harness :-)

2018-01-27 14:24 UTC, petebacondarwin commented
@gkalpak PTAL

2018-01-27 14:31 UTC, mary-poppins commented
You can preview d478886 at https://pr21763-d478886.ngbuilds.io/.

2018-01-28 11:18 UTC, petebacondarwin commented on aio/tools/firebase-test-utils/FirebaseGlob.spec.ts
> +      testGlob('aaa/*.@(bbb|ccc)',
From what I can see failing to add the `@` or any other character just leads to the redirect not matching. E.g. give this config:

```json
      { "type": 301, "source": "/@(a|b)/c", "destination": "/x/y/z" },
      { "type": 301, "source": "/(1|2)/3", "destination": "/4/5/6" }
```

Then you get the following behaviour:

```
/a/c => /x/y/z
/b/c => /x/y/z
/a/b => 404

/1/3 => 404
/2/3 => 404
/1/2 => 404
/(1|2)/3 => /(1%7C2)/3 => 404
```

Since it is very likely an error in the config to have `/(a|b)` type grouping, the test harness throws an error if it doesn't recognise the preceding character before the group.

2018-01-29 13:26 UTC, gkalpak commented on aio/firebase.json
> +      {"type": 301, "source": "/api/animate/:rest*", "destination": "/api/animations/:rest"},
I think that's reasonable. Starred params are supposed to capture everything that follows.

2018-01-29 14:55 UTC, gkalpak requested changes

2018-01-29 14:55 UTC, gkalpak commented on aio/firebase.json
> +      {"type": 301, "source": "/api/animate/:rest*", "destination": "/api/animations/:rest"},
So, don't you need the `*` at the end of the destination URL?

2018-01-29 14:55 UTC, gkalpak commented on aio/tools/firebase-test-utils/FirebaseGlob.spec.ts
> +      },{
Missing whitespace after comma 😱
No linting?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;😱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

2018-01-29 14:55 UTC, gkalpak commented on aio/tools/firebase-test-utils/FirebaseGlob.spec.ts
> +  });
Much much better 😄, but...
...still no `match` test for pattern without named params? 😢

2018-01-29 14:55 UTC, gkalpak commented on aio/tools/firebase-test-utils/FirebaseGlob.spec.ts
> +        '/a': {b: undefined},
Does this mean that it's a match. I would expect `'/a': undefined` 😕 
Is this how Firebase handles that?

2018-01-29 14:55 UTC, gkalpak commented on aio/tools/firebase-test-utils/FirebaseRedirect.ts
> +      const restReplacers = Object.keys(this.glob.restParams).map(name => [ XRegExp(`:${name}\*`, 'g'), match[name] ]);
I think `\*` was supposed to be `\\*`?
(This would probably make some tests fail, which could be expectd, since we are currently omitting `*` from rest-param names in destinations.)

2018-01-29 14:55 UTC, gkalpak commented on aio/tools/firebase-test-utils/FirebaseGlob.ts
> +            return `(?:/(?<${param}>.🐷))?`;
Is the `/` really optional?

2018-01-29 16:10 UTC, gkalpak commented on aio/tools/firebase-test-utils/FirebaseGlob.ts
> +          .replace(doubleStar, '.🐷')                     // use the pig to avoid replacing ** in next rule
What happened to leading/trailing `/`? AFAICT, this line will replace `/**/` with `.🐷`.

2018-01-30 11:55 UTC, petebacondarwin commented on aio/firebase.json
> +      {"type": 301, "source": "/api/animate/:rest*", "destination": "/api/animations/:rest"},
Yes you do.

2018-01-30 14:47 UTC, mary-poppins commented
You can preview b1a0088 at https://pr21763-b1a0088.ngbuilds.io/.

2018-01-30 17:54 UTC, petebacondarwin commented on aio/tools/firebase-test-utils/FirebaseGlob.ts
> +            return `(?:/(?<${param}>.🐷))?`;
I am pretty sure it is (as I think I tried it and then added a unit test for it): `/a/:b*` matches `/a/` and `/a`

2018-01-30 17:58 UTC, petebacondarwin commented on aio/tools/firebase-test-utils/FirebaseGlob.ts
> +          .replace(doubleStar, '.🐷')                     // use the pig to avoid replacing ** in next rule
`doubleStar` matches `**` only; and then `possiblyEmptyInitialSegments` matches `**/` at the start of the line (or really `.🐷/`) and `possiblyEmptySegments` matches `/**/` (or really `/.🐷/`). Otherwise other double stars will be mapped to the other possibilities.

2018-01-30 17:59 UTC, petebacondarwin commented on aio/tools/firebase-test-utils/FirebaseGlob.spec.ts
> +        '/a': {b: undefined},
I am pretty sure that it does match, from my previous experiments.

2018-01-30 20:34 UTC, gkalpak commented on aio/tools/firebase-test-utils/FirebaseGlob.spec.ts
> +        '/a': {b: undefined},
Unexpected, but I'll trust you 😛

2018-01-30 20:44 UTC, gkalpak requested changes
Almost there 😄

2018-01-30 20:44 UTC, gkalpak commented on aio/package.json
> +    "tools-lint": "tslint -c \"tools/tslint.json\" \"tools/firebase-test-utils/**/*.ts\"",
❤️

2018-01-30 20:44 UTC, gkalpak commented on aio/tools/firebase-test-utils/FirebaseGlob.spec.ts
> +      });    });
Missing newline :grin:

2018-01-30 20:44 UTC, gkalpak commented on aio/tools/firebase-test-utils/FirebaseGlob.ts
> +    } catch (e) {
He he he 😈

2018-01-30 20:44 UTC, gkalpak commented on aio/tools/firebase-test-utils/FirebaseGlob.ts
> +          .replace(doubleStar, '.🐷')                     // use the pig to avoid replacing ** in next rule
AFAICT, [doubleStar][1] matches `/**/`, not just `**`: `/(?:^|\/)\*\*(?:$|\/)/g`

[1]: https://github.com/angular/angular/pull/21763/files#diff-9a588366fd4fdb7a6699bad216ca2482R5

2018-01-30 22:22 UTC, petebacondarwin commented on aio/tools/firebase-test-utils/FirebaseGlob.ts
> +          .replace(doubleStar, '.🐷')                     // use the pig to avoid replacing ** in next rule
Doh! Sorry, you got me. I'll fix this.

2018-01-30 22:23 UTC, petebacondarwin commented
Last try @gkalpak - PTAL.

2018-01-30 22:31 UTC, mary-poppins commented
You can preview d687a95 at https://pr21763-d687a95.ngbuilds.io/.

2018-01-31 13:01 UTC, mary-poppins commented
You can preview 7b3a33d at https://pr21763-7b3a33d.ngbuilds.io/.

2018-02-01 09:59 UTC, gkalpak approved these changes
✨

2018-02-01 10:01 UTC, gkalpak commented
Requires `root` approval 😕

2018-02-01 10:03 UTC, gkalpak commented
BTW, you need a space after `fixup!` in commit messages :smiley:

2018-02-01 17:09 UTC, mary-poppins commented
You can preview 3844ad8 at https://pr21763-3844ad8.ngbuilds.io/.

2018-02-01 22:48 UTC, IgorMinar approved these changes

2018-02-02 15:53 UTC, closed without merging