refactor(ivy): validate that identifier identity in emitted output
angular/angular pull request #21877
Opened 2018-01-29 23:42 UTC by chuckjaz

Modifies validation syntax to generate back references to ensure
that identifiers are used consistently.

Introduced … to allow validating constant definition and usage.

## PR Type
What kind of change does this PR introduce?

```
[x] Refactoring (no functional changes, no api changes)
```

## What is the new behavior?

Modifies validation syntax to generate back references to ensure
that identifiers are used consistently.

Introduced … to allow validating constant definition and usage.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2018-02-03 00:39 UTC, mary-poppins commented
You can preview ad64214 at https://pr21877-ad64214.ngbuilds.io/.

2018-02-06 02:27 UTC, vicb requested changes
Great change!

As discussed earlier I would love to see `mock_compile_spec.ts` if I have to debug/enhance the test code at some point. At the very least add a one liner comment to the fns and on each of the important blocks ?

What about replacing `…` by something easier to type ie `// ...` ?

2018-02-06 02:32 UTC, vicb commented on packages/compiler/test/render3/mock_compile.ts
> +  let results: string[] = [];
didn't lint use to enforce `const` ?

2018-02-07 22:23 UTC, chuckjaz commented
Added unit tests.

Explained in comments why … is a good thing ;-).

2018-02-07 22:30 UTC, mary-poppins commented
You can preview ec0f991 at https://pr21877-ec0f991.ngbuilds.io/.

2018-02-07 22:34 UTC, mary-poppins commented
You can preview 6c2c0b6 at https://pr21877-6c2c0b6.ngbuilds.io/.

2018-02-07 23:05 UTC, vicb approved these changes
I love it !

2018-02-07 23:31 UTC, mary-poppins commented
You can preview e5fdefa at https://pr21877-e5fdefa.ngbuilds.io/.

2018-02-09 21:07 UTC, closed without merging