Canonical query examples
angular/angular pull request #21912
Opened 2018-01-30 19:30 UTC by kara

This PR adds canonical examples for view and content queries. It also adds the dM instruction as a start to the content query implementation.

2018-01-30 19:38 UTC, mary-poppins commented
You can preview 9f5207a at https://pr21912-9f5207a.ngbuilds.io/.

2018-01-30 20:05 UTC, mary-poppins commented
You can preview 5e1c604 at https://pr21912-5e1c604.ngbuilds.io/.

2018-01-30 22:11 UTC, mhevery requested changes

2018-01-30 22:11 UTC, mhevery commented on packages/core/src/render3/query.ts
> +export function directiveMemory<T>(
I think of `directiveMemory` as general function for staring data, not specific to queries. 
- It should return `T` not `QueryList<T>`
- It should not be in `query.ts` but rather in `instructions.ts` as a generic storage mechanism.

2018-01-30 22:11 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +export function getData(): any {
you don't need `getData` if `directiveMemory` is moved here.

2018-01-30 22:11 UTC, mhevery commented on packages/core/src/render3/query.ts
> +  } else {
`else` branch is not needed per our discussion

2018-01-30 22:11 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +              return new ContentQueryComponent();
`return [new ContentQueryComponent(), r3.Q(null, SomeDirective, false))`

2018-01-30 22:11 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +                r3.m(0, r3.Q(SomeDirective, false));
could we simplify to: `r3.Q(0, SomeDirective, false);`

2018-01-30 23:12 UTC, mary-poppins commented
You can preview ccf2ed0 at https://pr21912-ccf2ed0.ngbuilds.io/.

2018-01-30 23:44 UTC, mary-poppins commented
You can preview 0928e1d at https://pr21912-0928e1d.ngbuilds.io/.

2018-01-30 23:46 UTC, mary-poppins commented
You can preview fa03e93 at https://pr21912-fa03e93.ngbuilds.io/.

2018-01-30 23:46 UTC, mhevery approved these changes
Please add JSDoc, LGTM otherwise

2018-01-30 23:46 UTC, mhevery commented on packages/core/src/render3/query.ts
>  export function query<T>(
Since `query` is public can we add jsdoc?

2018-01-31 00:04 UTC, mhevery approved these changes

2018-01-31 00:16 UTC, mary-poppins commented
You can preview 6437b38 at https://pr21912-6437b38.ngbuilds.io/.

2018-01-31 18:20 UTC, closed without merging

2018-01-31 19:03 UTC, JoostK commented on packages/core/src/render3/query.ts
> + * this is is a content query and the QueryList will be saved later through directiveCreate.
"is is" -> "is"