[WIP] Edit DI intro and headers
angular/angular pull request #21915
Opened 2018-01-30 19:50 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
General style update, make page titles more descriptive

2018-01-30 20:12 UTC, mary-poppins commented
You can preview 2fad0c9 at https://pr21915-2fad0c9.ngbuilds.io/.

2018-01-31 18:09 UTC, mary-poppins commented
You can preview 8298e2a at https://pr21915-8298e2a.ngbuilds.io/.

2018-01-31 20:04 UTC, mary-poppins commented
You can preview aa0aa8e at https://pr21915-aa0aa8e.ngbuilds.io/.

2018-02-13 17:15 UTC, mary-poppins commented
You can preview 58d01f3 at https://pr21915-58d01f3.ngbuilds.io/.

2018-03-01 17:07 UTC, mary-poppins commented
You can preview 2993cfa at https://pr21915-2993cfa.ngbuilds.io/.

2018-05-31 19:59 UTC, jbogarthyde commented
Rebased on current master, to include new material on provider methods.
Re-org to simplify structure. 
Moved some material from main page to sub-pages, including a new Providers page.

2018-06-15 18:49 UTC, jbogarthyde commented
Requesting tech review as soon as this passes tests. @jenniferfell  @mhevery 

Please use the preview to read through the whole section before commenting on specifics. It has been extensively reorganized and rewritten, and it will be very hard to see in the code changes. In the preview, go to the **Dependency Injection** guide under **Fundamentals** - there are four pages. 

This is generally what has changed (in addition to addressing some specific issues that had been raised against the previous content):

-- Organized and edited all pages for clarity.
-- Move in-depth section on providers into a subpage, parallel to subpage on hierarchical injectors.
-- Tightened up the cookbook page (still WIP) to remove redundancies with concept pages.
-- Removed negative references ("here's a thing you can do, but don't do it") and obscure points ("here's a thing you can do, but I'm not going to tell you how or why")
-- Removed the previous landing page, `dependency-injection-pattern.md`, which is about the DI concept and why it's a good thing. The concept is now explained in the architecture overview, and this doesn't do anything to add the discussion of how it works in Angular. Landing page is now `dependency-injection.md`

2018-06-15 19:37 UTC, mary-poppins commented
You can preview 49fb2bf at https://pr21915-49fb2bf.ngbuilds.io/.

2018-06-15 23:13 UTC, mary-poppins commented
You can preview 50a3a6d at https://pr21915-50a3a6d.ngbuilds.io/.

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection-providers.md
> +A service **provider** provides the concrete, runtime version of a dependency value.
Can we reword this. A **provider** is a configuration of a token to an Injector so that injector knows how to create instances for that token. 

Or something like that.

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection-providers.md
> +The injector relies on its registered providers to create instances of the services
... an injector relies on provider configuration...

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection-providers.md
> +You must register a service *provider* with an injector, or it won't know how to create the service.
Don't use the work `register`. Say `Injector is configured`

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection-providers.md
> +The most obvious way to provide an instance of a service class is with the class itself. In the following typical example, the `Logger` class itself provides a `Logger` instance.
most obvious way to configure a token is to provide the instance of the token itself.

Or something like that.

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection-providers.md
> +based on information you won't have until the last moment.
until runtime

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection-providers.md
> +_NgModule-level_ providers (registered with `@NgModule#providers`) are registered with the application's root injector. Angular can inject the corresponding services in any class it creates. Once cre
once created the service lives for the life of the injector, (which may not be that of the app.)

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection.md
> +Angular has its own dependency injection framework, and you really can't build an Angular application without it.
You can build application with out DI. So I would reword this to be less strong.

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection.md
> +You must register providers with an injector before that injector can create a service.
we configure the injector (not register providers with injector) Please check the rest of the PR for this inconsistency.

Registration implies that you have something and are notifying someone else of what you have (you own the instance).
Configuration implies that you are telling someone how to do it. Once finish you don't have the configuration.

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection.md
> +Without a provider, an injector cannot do anything.
Without configuring the injector for a provider, the injector can't instantiated it.

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection.md
> +and register more than one provider.
register => configure

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection.md
> +Injectors are inherited, which means that a component can get services from its own providers,
Injectors are inherited, which means that if a given injector does not know how to resolve a service, it asks the parent injector to do the resolution instead.

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection.md
> +Learn more about [where to register providers](guide/dependency-injection-providers#where-to-register).
register => configure

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection.md
> +Services are singletons _within the scope of an injector_. That is, there is at most one instance of a service in a given injector.
👍

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection.md
> +There is only one root injector. Registering `UserService` at the NgModule level means it is registered with the root injector. Therefore, there can be just one `UserService` instance in the entire a
Not true. A child injector can be configured with `UserService` and that child injector will return a different instance. Needs to be reworded.

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection.md
> +While _any_ decorator will do, the `@Injectable()` decorator is the standard decorator for service classes.
Not with AOT. It has to be `@Injectable`. Remove the bit about any decorator will do.

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/dependency-injection.md
>  Unfortunately, you cannot use a TypeScript interface as a token:
you should say why. The reason is that interfaces don't have a runtime representation (token). They are a design time (live in compiler) concept.

2018-06-26 23:35 UTC, mhevery commented on aio/content/guide/hierarchical-dependency-injection.md
> +To prevent this, we register the service directly with the `HeroTaxReturnComponent`, using the  `providers` property in the component metadata.
register => configure

2018-06-26 23:37 UTC, mhevery commented
https://github.com/angular/angular/pull/21915/commits/35a62f1e577e92964e924b2ecfc6a7ac3d76ebdd

2018-06-27 15:51 UTC, jbogarthyde commented
Thanks for your review - but now you have to fix the CLA conflict.
I will work on your comments, but I can't push my changes at the moment:
```git push --force-with-lease
To https://github.com/jbogarthyde/angular.git
 ! [rejected]              jb-fix-di-headers -> jb-fix-di-headers (stale info)
error: failed to push some refs to 'https://github.com/jbogarthyde/angular.git
'```
I hope it's because of the CLA conflict.

2018-06-27 16:12 UTC, jbogarthyde commented on aio/content/guide/dependency-injection-in-action.md
> +* The dependency being provides is something other than a service, such as an object or value.
I'm not sure where this point came from - I'll take it out. 
Is there anything special about where you should provide different kinds of dependencies?

2018-06-27 19:00 UTC, mhevery commented
@jbogarthyde 
- The CLA is easy to fix, done.
- Yes you can't push because your branch has diverged from `origin` branch due to my push.  Here is how to fix it.

```
git fetch origin
```
NOTE: I am assuming that you have `origin` set up properly.

While you are on `jb-fix-di-headers` with all changes checked in.
```
git rebase origin/jb-fix-di-headers
```

```
git push origin --force-with-lease
```

2018-06-27 19:43 UTC, jbogarthyde commented on aio/content/guide/dependency-injection-providers.md
> +The most obvious way to provide an instance of a service class is with the class itself. In the following typical example, the `Logger` class itself provides a `Logger` instance.
Check again - altered it, but I'm not sure it captures this nuance.

2018-06-29 16:39 UTC, mary-poppins commented
You can preview 2b3e9c3 at https://pr21915-2b3e9c3.ngbuilds.io/.

2018-06-29 16:48 UTC, mary-poppins commented
You can preview de20881 at https://pr21915-de20881.ngbuilds.io/.

2018-07-04 16:20 UTC, jbogarthyde commented
@alxhub Can you please review? Misko has looked at it, I would like your take as well.

2018-07-04 16:40 UTC, mary-poppins commented
You can preview 0fc5fc0 at https://pr21915-0fc5fc0.ngbuilds.io/.

2018-07-05 19:45 UTC, mary-poppins commented
You can preview fce982f at https://pr21915-fce982f.ngbuilds.io/.

2018-07-09 16:29 UTC, mary-poppins commented
You can preview e1d88bf at https://pr21915-e1d88bf.ngbuilds.io/.

2018-07-12 19:40 UTC, mary-poppins commented
You can preview 5a5f80f at https://pr21915-5a5f80f.ngbuilds.io/.

2018-07-13 15:44 UTC, mary-poppins commented
You can preview d9ef578 at https://pr21915-d9ef578.ngbuilds.io/.

2018-07-16 16:30 UTC, mary-poppins commented
You can preview 0db7d19 at https://pr21915-0db7d19.ngbuilds.io/.

2018-07-16 19:29 UTC, mary-poppins commented
You can preview afce8c1 at https://pr21915-afce8c1.ngbuilds.io/.

2018-07-16 20:35 UTC, mary-poppins commented
You can preview e307053 at https://pr21915-e307053.ngbuilds.io/.

2018-07-17 15:50 UTC, mary-poppins commented
You can preview 802a713 at https://pr21915-802a713.ngbuilds.io/.

2018-07-19 18:52 UTC, alxhub approved these changes
LGTM overall, with a few comments!

2018-07-19 18:52 UTC, alxhub commented on aio/content/guide/dependency-injection.md
> +There is only one root injector. Providing the `UserService` at the NgModule level means it is registered with the root injector. There will be just one `UserService` instance in the entire app and e
> Providing the `UserService` at the NgModule level means it is registered with the root injector.

Unless that `NgModule` is lazy loaded.

2018-07-19 18:52 UTC, alxhub commented on aio/content/guide/hierarchical-dependency-injection.md
> +Each NgModule and each component instance in an NgModule has its own injector.
Each `NgModule` is not its own injector, they are grouped into injectors. The `AppModule` and all of its imports become the root injector, and any lazy-loaded modules (and their imports) form injectors of their own.

2018-07-19 18:52 UTC, alxhub commented on aio/content/guide/hierarchical-dependency-injection.md
> +_This is a topic for another day._ IF YOU'RE NOT GOING TO TELL ME HOW, WHY MENTION IT?
Is this an editorial note?

2018-07-19 19:20 UTC, mary-poppins commented
You can preview 44ec665 at https://pr21915-44ec665.ngbuilds.io/.

2018-07-19 19:22 UTC, jbogarthyde commented on aio/content/guide/dependency-injection-in-action.md
> +You can do this, for example, to let users explicitly opt-in to use a service, rather than letting
Thanks - moved this case to component providers section further down

2018-07-19 20:02 UTC, jbogarthyde commented on aio/content/guide/hierarchical-dependency-injection.md
> +_This is a topic for another day._ IF YOU'RE NOT GOING TO TELL ME HOW, WHY MENTION IT?
Yes -- whoops. Failed to remove it, thanks.

2018-07-19 20:32 UTC, mary-poppins commented
You can preview 26fe731 at https://pr21915-26fe731.ngbuilds.io/.

2018-07-19 21:04 UTC, jbogarthyde commented on aio/content/guide/hierarchical-dependency-injection.md
> +_This is a topic for another day._ IF YOU'RE NOT GOING TO TELL ME HOW, WHY MENTION IT?
Found an example

2018-07-19 21:13 UTC, mary-poppins commented
You can preview cb6798f at https://pr21915-cb6798f.ngbuilds.io/.

2018-07-19 21:22 UTC, mary-poppins commented
You can preview c93580d at https://pr21915-c93580d.ngbuilds.io/.

2018-07-20 10:42 UTC, trotyl commented on aio/content/guide/dependency-injection-providers.md
> +Tree-shaking doesn't work here because Angular cannot decide to exclude one chunk of code (the provider definition for the service within the module factory) based on whether another chunk of code (t
Should be `tree-shakable` per https://github.com/angular/angular/pull/24057.

2018-07-20 10:42 UTC, trotyl commented on aio/content/guide/dependency-injection.md
> +* The `@NgModule` and `@Component` decorators have the `providers` metadata option, where you can configure providers for the NgModule-level or component-level injectors.
Also `@Directive`?

2018-07-20 10:42 UTC, trotyl commented on aio/content/guide/dependency-injection-in-action.md
> +When a service is provided at the root level, Angular can inject it into the constructor of any component or service, anywhere injection is allowed.
What about `any directive` and `any pipe` then?

2018-07-20 10:42 UTC, trotyl commented on aio/content/guide/dependency-injection-providers.md
> +_Component-level_ providers configure each component instance's own injector.
The `directives` property in `Component` is inherited from `Directive`, calling it `Component-level` doesn't sounds right, at least should be `Directive-level` as all directives have that.

But actually a provider doesn't belong to single directive, but shared between all directives of the host element. So technically  it's `Element-level`.

2018-07-20 16:23 UTC, jbogarthyde commented on aio/content/guide/dependency-injection-in-action.md
> +By using `providedIn`, you are telling Angular that the root injector is responsible for creating an instance of the `HeroService`
Alex says it is deliberate - we are considering the platform injector internal.

2018-07-20 16:29 UTC, jbogarthyde commented on aio/content/guide/dependency-injection-in-action.md
> +The `AppModule` injector is the same as the `root` injector, but providers configured in the `AppModule` override those configured in the `@Injectable` decorator.
Alex says that `providedIn:root` actually does configure the app-wide root injector, not the platform root

2018-07-20 16:36 UTC, trotyl commented on aio/content/guide/dependency-injection-in-action.md
> +By using `providedIn`, you are telling Angular that the root injector is responsible for creating an instance of the `HeroService`
I'm fine with that, but given all platform stuffs are still public APIs, would it deserve a simple note?

2018-07-20 19:42 UTC, jbogarthyde commented on aio/content/guide/dependency-injection-providers.md
> +_Component-level_ providers configure each component instance's own injector.
Working on adding the directive-level providers concept in all page.
@brandonroberts When you get chance, can you check out the new section at the end of `dependency-injection-in-action` and help me work up the example @alxhub gave me into a full, external example?

2018-07-23 13:11 UTC, brandonroberts commented
Here are some things I noted from reading the guide

- Missing any mention of using `multi` when defining providers
- DI in Action section feels a little repetitive. 
- No mention of built-in DI tokens such as `APP_INITIALIZER`, `APP_BOOTSTRAP_LISTENER`, etc.

2018-07-23 23:47 UTC, trotyl commented on aio/content/guide/dependency-injection-in-action.md
> +This allows multiple apps to run at the same time; however, you cannot configure providers at the platform level.
[Platform Extra Providers](
https://angular.io/api/platform-browser/platformBrowser) is fully user-controlled and part of the bootstrap process, which is under the same injector with Platform Internal Providers.

2018-07-25 17:49 UTC, trotyl commented on aio/content/guide/dependency-injection-providers.md
> +Use the `@NgModule()` `provides` option if a module is [lazy loaded](guide/lazy-loading-ngmodules). The module's own injector is configured with the provider when that module is loaded, and Angular c
`providedIn: 'myLazyloadModule'` -> `providedIn: MyLazyloadModule`? (Not a string, PascalCase for conversion)?

2018-07-25 18:23 UTC, jbogarthyde commented on aio/content/guide/dependency-injection-providers.md
> +Use the `@NgModule()` `provides` option if a module is [lazy loaded](guide/lazy-loading-ngmodules). The module's own injector is configured with the provider when that module is loaded, and Angular c
Re-organizing, so this is now in the `hierarchical-dependency-injection.md` page

2018-07-27 20:42 UTC, mary-poppins commented
You can preview 82d3af0 at https://pr21915-82d3af0.ngbuilds.io/.

2018-07-30 18:56 UTC, mary-poppins commented
You can preview 112051d at https://pr21915-112051d.ngbuilds.io/.

2018-07-30 22:33 UTC, mary-poppins commented
You can preview 7ec2010 at https://pr21915-7ec2010.ngbuilds.io/.

2018-07-31 16:25 UTC, mary-poppins commented
You can preview a26923c at https://pr21915-a26923c.ngbuilds.io/.

2018-07-31 21:52 UTC, mary-poppins commented
You can preview a8de342 at https://pr21915-a8de342.ngbuilds.io/.

2018-08-01 15:02 UTC, firrae commented
There is a spelling/grammar error at this point in the documentation: https://pr21915-772e873.ngbuilds.io/guide/hierarchical-dependency-injection#ngmodule-level-injectors

> "However, if you configure a app-wide provider in the@NgModule() metadata for AppModule..."

There is no space between `the` and `@NgModule()`.

2018-08-01 15:03 UTC, firrae commented on aio/content/guide/hierarchical-dependency-injection.md
> +However, if you configure a app-wide provider in the`@NgModule()` metadata for `AppModule`,
There is no space between `the` and `@NgModule()` here.

2018-08-02 17:29 UTC, firrae commented on aio/content/guide/dependency-injection-providers.md
> +a third-part library that wasn't designed to work with DI.
I think `third-part` is supposed to be `third-party`?

2018-08-03 17:27 UTC, jbogarthyde commented on aio/content/guide/dependency-injection-providers.md
> +a third-part library that wasn't designed to work with DI.
Thanks!

2018-08-03 17:38 UTC, mary-poppins commented
You can preview 6925452 at https://pr21915-6925452.ngbuilds.io/.

2018-08-03 17:40 UTC, mary-poppins commented
You can preview be01518 at https://pr21915-be01518.ngbuilds.io/.

2018-08-06 15:54 UTC, mary-poppins commented
You can preview 0e3d633 at https://pr21915-0e3d633.ngbuilds.io/.

2018-08-06 16:04 UTC, mary-poppins commented
You can preview 099453f at https://pr21915-099453f.ngbuilds.io/.

2018-08-13 15:29 UTC, mary-poppins commented
You can preview 7c6b054 at https://pr21915-7c6b054.ngbuilds.io/.

2018-08-14 23:15 UTC, mary-poppins commented
You can preview eb1adb6 at https://pr21915-eb1adb6.ngbuilds.io/.

2018-08-15 15:44 UTC, mary-poppins commented
You can preview 214ca1e at https://pr21915-214ca1e.ngbuilds.io/.

2018-08-16 16:50 UTC, mary-poppins commented
You can preview b32846b at https://pr21915-b32846b.ngbuilds.io/.

2018-08-17 15:48 UTC, mary-poppins commented
You can preview 2fe443e at https://pr21915-2fe443e.ngbuilds.io/.

2018-08-20 20:28 UTC, brandonroberts requested changes

2018-08-20 20:28 UTC, brandonroberts commented on aio/content/guide/dependency-injection-providers.md
> +<code-example path="dependency-injection/src/app/providers.component.ts" region="EvenBetterLogger"  linenums="false">
This example should be updated to use `providedIn: 'root'`

2018-08-20 20:28 UTC, brandonroberts commented on aio/content/guide/dependency-injection-providers.md
> +In the following typical example, the `Logger` class itself provides a `Logger` instance.
A code example for the `Logger` class should be in here.

2018-08-20 20:28 UTC, brandonroberts commented on aio/content/guide/dependency-injection-in-action.md
>  <code-example path="dependency-injection-in-action/src/app/user-context.service.ts" region="injectables" title="user-context.service.ts (injection)" linenums="false">
Should be updated to use `providedIn` root

2018-08-20 20:28 UTC, brandonroberts commented on aio/content/guide/dependency-injection-in-action.md
> +## Element-level providers
I would remove/comment out this for now until we can get a proper example together.

2018-08-20 21:46 UTC, mary-poppins commented
You can preview f7e4bee at https://pr21915-f7e4bee.ngbuilds.io/.

2018-08-20 23:25 UTC, jbogarthyde commented on aio/content/guide/hierarchical-dependency-injection.md
> +In our sample app, `HeroComponent` is created when the application starts
Is there an example of a such a component? I can't see what he's trying to say - maybe he's talking about the original tutorial example, rather than the live example in this section.
Can we create an illustrative example of a service that should restricted in this way, and needs to be provided at the component level?

2018-08-20 23:35 UTC, jbogarthyde commented on aio/content/guide/dependency-injection-providers.md
> +<code-example path="dependency-injection/src/app/providers.component.ts" region="EvenBetterLogger"  linenums="false">
Can you fix this? It would have to go in logger.service.ts, right? Would it change the previous example? Do we have to make two versions of `Logger`?

2018-08-20 23:36 UTC, jbogarthyde commented on aio/content/guide/dependency-injection-providers.md
> +In the following typical example, the `Logger` class itself provides a `Logger` instance.
This would be the version with `providedIn`, right?

2018-08-20 23:37 UTC, jbogarthyde commented on aio/content/guide/dependency-injection-in-action.md
>  <code-example path="dependency-injection-in-action/src/app/user-context.service.ts" region="injectables" title="user-context.service.ts (injection)" linenums="false">
same here - can you update the example, please?

2018-08-20 23:49 UTC, jbogarthyde commented on aio/content/guide/dependency-injection-in-action.md
> +## Element-level providers
Commented out the whole section.

2018-08-21 15:42 UTC, mary-poppins commented
You can preview 727077a at https://pr21915-727077a.ngbuilds.io/.

2018-08-21 19:07 UTC, brandonroberts commented on aio/content/guide/hierarchical-dependency-injection.md
> +In our sample app, `HeroComponent` is created when the application starts
I think this section can be removed and just update the link to the component injector scenarios to `see an example...`. We already have an example there that covers it.

2018-08-21 19:09 UTC, brandonroberts commented on aio/content/guide/dependency-injection.md
> +you have to change the implementation of `HerosListComponent` and
HeroesListComponent

2018-08-22 02:46 UTC, mary-poppins commented
You can preview 53a87ea at https://pr21915-53a87ea.ngbuilds.io/.

2018-08-22 14:32 UTC, mary-poppins commented
You can preview ba6d168 at https://pr21915-ba6d168.ngbuilds.io/.

2018-08-22 15:30 UTC, mary-poppins commented
You can preview 2492c18 at https://pr21915-2492c18.ngbuilds.io/.

2018-08-22 15:30 UTC, mary-poppins commented
You can preview 0a32d32 at https://pr21915-0a32d32.ngbuilds.io/.

2018-08-22 15:35 UTC, mary-poppins commented
You can preview 85f7a06 at https://pr21915-85f7a06.ngbuilds.io/.

2018-08-22 15:38 UTC, mary-poppins commented
You can preview 88c5f22 at https://pr21915-88c5f22.ngbuilds.io/.

2018-08-22 16:59 UTC, mary-poppins commented
You can preview 73625e2 at https://pr21915-73625e2.ngbuilds.io/.

2018-08-23 00:56 UTC, jbogarthyde commented
@jenniferfell @brandonroberts All green except approvals

2018-08-29 17:39 UTC, mhevery approved these changes

2018-08-29 17:39 UTC, mhevery commented on aio/content/guide/dependency-injection-navtree.md
> +*Barry* is the problem. He needs to reach his parent, *Alice*, and also be a parent to *Carol*.
`is` => `has`???

2018-08-29 17:39 UTC, mhevery commented on aio/content/guide/dependency-injection-navtree.md
> +That means he must both *inject* the `Parent` class interface to get *Alice* and
`both inject` => `inject both`???

2018-08-29 17:41 UTC, mhevery reviewed
The `@Self` and `@SkipSelf` examples LGTM

2018-08-29 18:29 UTC, mary-poppins commented
You can preview d0b8e90 at https://pr21915-d0b8e90.ngbuilds.io/.

2018-08-29 18:30 UTC, mary-poppins commented
You can preview cb9a306 at https://pr21915-cb9a306.ngbuilds.io/.

2018-08-29 20:15 UTC, brandonroberts approved these changes

2018-08-30 17:03 UTC, jenniferfell approved these changes

2018-08-30 17:17 UTC, closed without merging

2018-10-01 21:42 UTC, alex-okrushko commented
Thanks for referencing blog.angularindepth.com for the details 👍