feat(ivy): memoize array literals in render3
angular/angular pull request #21973
Opened 2018-02-01 20:57 UTC by kara

Currently in render3, if you pass an array literal into a binding, it will be re-created every change detection run and its binding will be re-set every change detection run. 

This PR adds a new set of `mo1()...mo8()` instructions that ensure the property is only set when one of the bound expressions in the array literal actually changes.

This template:

```html
<div [ngClass]="['one', myClass, 'two']"></div>
```

currently generates this instruction:
```ts
p(0, 'names', b(['one', ctx.myClass, 'two']));
```

will generate this instruction: 
```ts
p(0, 'names', mo1(e0_literal, 1, ctx.myClass));
...
const e0_literal = ['one', null, 'two'];
```

2018-02-01 21:06 UTC, mary-poppins commented
You can preview 02b6bd8 at https://pr21973-02b6bd8.ngbuilds.io/.

2018-02-01 21:33 UTC, mhevery requested changes

2018-02-01 21:33 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +/**
`instructions.ts` is getting large as is. Can we move these into a separate file?

2018-02-01 21:33 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +function updateBinding4(
Building it up like this is clever. :-)

2018-02-01 21:33 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +  return updateBinding2(arr, index1, exp1, index2, exp2) ? arr.slice() : NO_CHANGE;
I don't think this is right. If I am reading correctly you update the `arr` and than you make a copy. But `arr` is the prototype, which means that you are updating it for everyone. I think the correct behavior is to 1) determine if there are changes 2) clone the `arr` and 3) assign the changes to the array.

2018-02-01 21:33 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +        expect(renderComp(MyApp)).toEqual(`<my-comp><p>Nancy</p><p>Bess</p></my-comp>`);
assert that `e0_literal` has not been changed. (I believe that your code changes it which is incorrect.)

2018-02-01 22:20 UTC, kara commented on packages/core/src/render3/instructions.ts
> +  return updateBinding2(arr, index1, exp1, index2, exp2) ? arr.slice() : NO_CHANGE;
Discussed offline. For anyone curious: the current algorithm works because we are comparing bindings against themselves instead of against the array that is changing. But changing the const array that is generated by the compiler causes compiler complexity, so instead we will save a copy on TView.

2018-02-01 23:34 UTC, mary-poppins commented
You can preview b4793f2 at https://pr21973-b4793f2.ngbuilds.io/.

2018-02-01 23:56 UTC, mary-poppins commented
You can preview a16c5db at https://pr21973-a16c5db.ngbuilds.io/.

2018-02-02 00:13 UTC, mhevery requested changes
I think the same exact code with few minor changes should work for object literals as well as for arrays.

2018-02-02 00:13 UTC, mhevery commented on packages/core/src/render3/object_literal.ts
> +function updateArrBinding(arr: any[], index: number, exp: any): boolean {
I think this can be `updateBinding` since `Array` and `Object` will have the same exact code.

2018-02-02 00:13 UTC, mhevery commented on packages/core/src/render3/object_literal.ts
> +  const tView = getTView();
can you add assert that `index` comes in the right order? so that we don't create a spares array.

2018-02-02 00:13 UTC, mhevery commented on packages/core/src/render3/object_literal.ts
> +      (objectLiterals || (tView.objectLiterals = []))[index] = arr.slice();
If you do something like `Array.isArray(arr) ? arr.slice() : Object.create(Object, arr)`. it should work for both array and object. You may want to rename `arr` => `obj`

2018-02-02 00:13 UTC, mhevery commented on packages/core/src/render3/object_literal.ts
> +function getObjectCopy(index: number, arr: any[]): any[] {
Can we call it `getMutableBlueprint`?

2018-02-05 19:45 UTC, mary-poppins commented
You can preview b1ce536 at https://pr21973-b1ce536.ngbuilds.io/.

2018-02-05 21:38 UTC, mhevery approved these changes

2018-02-06 01:35 UTC, kara commented
[presubmit](https://test.corp.google.com/ui#id=OCL:184612957:BASE:184613625:1517880698097:473dd450)

2018-02-06 16:02 UTC, closed without merging

2018-02-06 20:00 UTC, vicb commented on packages/core/src/render3/object_literal.ts
> +function updateBinding2(obj: any, key1: number, exp1: any, key2: number, exp2: any): boolean {
`string | number`

2018-02-06 20:01 UTC, vicb commented on packages/core/src/render3/object_literal.ts
> + * Updates an expression in an object literal if the expression has changed.
`object literal` should be `object literal or array`

2018-02-06 20:03 UTC, kara commented on packages/core/src/render3/object_literal.ts
> +function updateBinding2(obj: any, key1: number, exp1: any, key2: number, exp2: any): boolean {
Good catch. Can include in my follow-up here https://github.com/angular/angular/pull/22045/

2018-02-06 20:03 UTC, vicb commented on packages/core/src/render3/object_literal.ts
> +export function objectLiteral1(objIndex: number, obj: any, key: string | number, exp: any): any {
objectLiteral is confusing wrt to array ?

2018-02-06 20:03 UTC, vicb commented on packages/core/src/render3/object_literal.ts
> + * @param exp2
remove undocumented params ?

2018-02-06 20:07 UTC, kara commented on packages/core/src/render3/object_literal.ts
> +export function objectLiteral1(objIndex: number, obj: any, key: string | number, exp: any): any {
Since the instruction encompasses both, @mhevery and I discussed using "object" as the more general of the two.