feat(aio): enable data driven homepage announcements
angular/angular pull request #22043
Opened 2018-02-06 18:00 UTC by petebacondarwin

WIP - needs tests

2018-02-07 00:28 UTC, IgorMinar commented on aio/src/app/embedded/announcement-bar/announcement-bar.component.ts
> +      .filter(announcement => new Date(announcement.endDate).valueOf() > Date.now())
nice!

2018-02-07 00:28 UTC, IgorMinar commented on aio/src/app/embedded/announcement-bar/announcement-bar.component.ts
> +  <!-- Announcement Bar -->
the comment is no longer needed

2018-02-07 10:18 UTC, petebacondarwin commented on aio/content/marketing/announcements.json
> +  }
This ngATL banner will never be shown as it has expired, but I am leaving it here as an example.

I have not yet added the ng-conf banner because the logo doesn't look right.

2018-02-07 21:28 UTC, IgorMinar requested changes

2018-02-07 21:28 UTC, IgorMinar commented on aio/src/app/embedded/embedded.module.ts
> +  AnnouncementBarComponent, ApiListComponent, CodeExampleComponent, CodeTabsComponent, ContributorListComponent,
I think this is not quite right. If we want to get good experience for loading the homepage, we need to bundle the AnnouncementBarComponent within the main bundle. Otherwise we won't be able to fully render the homepage without downloaded the main bundle and the embedded components bundle.

2018-02-07 21:58 UTC, petebacondarwin commented on aio/src/app/embedded/embedded.module.ts
> +  AnnouncementBarComponent, ApiListComponent, CodeExampleComponent, CodeTabsComponent, ContributorListComponent,
Good point! So the two options are:

1) Move the announcements component to the main bundle so it is loaded upfront.
2) Move the announcement component to its own bundle, so we don't need to load the other embedded components on the homepage.

The former is simpler but makes the main bundle larger even if someone is going straight to the docs pages. The latter requires a second request, but this could be HTTP preloaded for the homepage.

2018-02-07 22:19 UTC, petebacondarwin commented on aio/src/app/embedded/embedded.module.ts
> +  AnnouncementBarComponent, ApiListComponent, CodeExampleComponent, CodeTabsComponent, ContributorListComponent,
which do you prefer @IgorMinar ?

2018-02-08 06:41 UTC, IgorMinar commented
Move it to the main bundle please. It's not that much code.



On Wed, Feb 7, 2018, 2:19 PM Pete Bacon Darwin <notifications@github.com>
wrote:

> *@petebacondarwin* commented on this pull request.
> ------------------------------
>
> In aio/src/app/embedded/embedded.module.ts
> <https://github.com/angular/angular/pull/22043#discussion_r166774725>:
>
> > @@ -34,7 +35,7 @@ import { ResourceService } from './resource/resource.service';
>   * such as CodeExampleComponent, LiveExampleComponent,...
>   */
>  export const embeddedComponents: Type<any>[] = [
> -  ApiListComponent, CodeExampleComponent, CodeTabsComponent, ContributorListComponent,
> +  AnnouncementBarComponent, ApiListComponent, CodeExampleComponent, CodeTabsComponent, ContributorListComponent,
>
> which do you prefer @IgorMinar <https://github.com/igorminar> ?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/22043#discussion_r166774725>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AANM6IpuJiID0kYBAdVhLhldbG_kltKbks5tSiFlgaJpZM4R7emY>
> .
>

2018-02-08 09:58 UTC, petebacondarwin commented
Done - PTAL

2018-02-08 10:05 UTC, mary-poppins commented
You can preview ee64148 at https://pr22043-ee64148.ngbuilds.io/.

2018-02-09 05:58 UTC, IgorMinar approved these changes
thanks Pete!

2018-02-09 21:11 UTC, closed without merging