refactor(ivy): assertion
angular/angular pull request #22189
Opened 2018-02-13 06:47 UTC by vicb

Encourage the use of message to explain the assertion

Note: the messages in this PR are as good as it was possible to do with my current understanding & fast enough.

2018-02-13 06:54 UTC, mary-poppins commented
You can preview 9c6d5dd at https://pr22189-9c6d5dd.ngbuilds.io/.

2018-02-13 13:56 UTC, wartab commented on packages/core/src/render3/instructions.ts
> +  ngDevMode && assertEqual(attrs.length % 2, 0, 'each attribute should a a key and a value');
Found a small typo here. Assuming it should be "have".

2018-02-13 17:23 UTC, alfaproject commented on packages/core/src/render3/instructions.ts
> +*  - `true`: then `previousOrParentNode` points to a parent node.
Oops

2018-02-13 18:11 UTC, mary-poppins commented
You can preview d827b88 at https://pr22189-d827b88.ngbuilds.io/.

2018-02-13 18:35 UTC, kara requested changes
The code changes look good to me. I think it will be good to require us to write meaningful error messages.

In that spirit, I had a few suggestions for error messages, since I noticed a lot of them were missing subjects (which might be confusing).

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/component.ts
> +  ngDevMode && assertNotNull(component, 'should have a component');
How about `detectChanges should be called with a component` ?

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/component.ts
> +  ngDevMode && assertNotNull(hostNode.data, 'should have a lview');
`Component host node should be attached to an LView`

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/component.ts
> +  ngDevMode && assertNotNull(component, 'should have a component');
`markDirty should be called with a component`

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/instructions.ts
> +    ngDevMode && assertNull((state as LView).node, 'should not have been initialized');
`LView.node should not have been initialized`

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/instructions.ts
> +        ngDevMode && assertNull(previousOrParentNode.child, 'previousNode.child');
Am I right that this would now read: `ASSERTION ERROR: previousNode.child` ?

How about: `previousOrParentNode's child should not have been set.`

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/instructions.ts
> +      ngDevMode && assertNull(previousOrParentNode.next, 'previousNode.next');
`previousOrParentNode's next property should not have been set.`

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/instructions.ts
> +  ngDevMode && assertNotNull(hostView, 'should be the lview of the component');
`Host node should have an LView defined in host.data.`

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/instructions.ts
> +          currentView.bindingStartIndex, 'directive nodes should be created before any bindings');
Nit: directives don't have nodes, so might be clearer as just `directives should be created before any bindings`

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/instructions.ts
> +                   'The first native node should not be initialized yet');
How about `the container's native element should not have been set yet.`

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/instructions.ts
> +    ngDevMode && assertNotNull(element.data, 'components shuold have a lview');
`Component's host node should have an LView attached.`

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/instructions.ts
> +    ngDevMode && assertNotNull(hostView, 'a component should have a lview');
This looks like a duplicate assertion of line 1191. Remove?

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/instructions.ts
> +  assertNotNull(previousOrParentNode, 'should have a parent');
`previousOrParentNode should have a parent`

2018-02-13 18:35 UTC, kara commented on packages/core/src/render3/node_assert.ts
> +  assertNotNull(node, 'should have a node');
`assertNodeOfPossibleTypes should be called with a node`

2018-02-13 19:26 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +    ngDevMode && assertNotNull(hostView, 'a component should have a lview');
good catch !

2018-02-13 19:28 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +  assertNotNull(previousOrParentNode, 'should have a parent');
IIUC "previousOrParentNode should **be** a parent" would be better but still not accurate - probably the message should be passed from the caller but let's shot for incremental improvements.

2018-02-13 20:04 UTC, mary-poppins commented
You can preview 5dfe4b1 at https://pr22189-5dfe4b1.ngbuilds.io/.

2018-02-13 21:56 UTC, kara approved these changes
LGTM

2018-02-13 22:25 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +  assertNotNull(previousOrParentNode, 'should have a parent');
Oops you are totally right !
I removed the `.parent` by mistake in my code and that's why the code didn't make sense any more. I'll fix that.

2018-02-13 22:38 UTC, mary-poppins commented
You can preview 5d5bfec at https://pr22189-5d5bfec.ngbuilds.io/.

2018-02-14 18:34 UTC, mhevery approved these changes

2018-02-14 20:06 UTC, matsko commented
Please make sure this PR has approval from all members ... otherwise remove the extra reviewers.

2018-02-15 21:09 UTC, closed without merging