fix(core): require factory to be provided for shakeable InjectionToken
angular/angular pull request #22207
Opened 2018-02-13 21:03 UTC by alxhub

InjectionToken can be created with an ngInjectableDef, and previously
this allowed the full expressiveness of @Injectable. However, this
requires a runtime reflection system in order to generate factories
from expressed provider declarations.

Instead, this change requires scoped InjectionTokens to provide the
factory directly (likely using inject() for the arguments), bypassing
the need for a reflection system.

Fixes #22205

2018-02-13 21:13 UTC, mary-poppins commented
You can preview 6ef95a9 at https://pr22207-6ef95a9.ngbuilds.io/.

2018-02-13 23:43 UTC, mary-poppins commented
You can preview e3ea3c5 at https://pr22207-e3ea3c5.ngbuilds.io/.

2018-02-14 00:09 UTC, mary-poppins commented
You can preview b1283ca at https://pr22207-b1283ca.ngbuilds.io/.

2018-02-14 17:28 UTC, mhevery approved these changes
there were no tests affected by this?

2018-02-14 23:07 UTC, mary-poppins commented
You can preview a7c6905 at https://pr22207-a7c6905.ngbuilds.io/.

2018-02-14 23:28 UTC, alxhub commented
`packages/compiler-cli/integrationtest/bazel/injectable_def/app/src/token.ts` was updated.

2018-02-14 23:48 UTC, chuckjaz approved these changes

2018-02-15 16:07 UTC, mary-poppins commented
You can preview 793d220 at https://pr22207-793d220.ngbuilds.io/.

2018-02-15 22:35 UTC, mhevery approved these changes

2018-02-15 22:35 UTC, mhevery requested changes
test

2018-02-15 22:35 UTC, mhevery approved these changes

2018-02-16 00:17 UTC, closed without merging