test(ivy): add missing host binding and query tests
angular/angular pull request #22213
Opened 2018-02-14 02:27 UTC by kara

2018-02-16 00:34 UTC, chuckjaz requested changes

2018-02-16 00:34 UTC, chuckjaz commented on packages/core/test/render3/compiler_canonical_spec.ts
> +      type $MyApp$ = MyApp;
This demonstrates host bindings but not host attributes or host listeners.

For host attributes we should consider adding a create mode file the as this only has to be performed once.

2018-02-16 01:41 UTC, kara commented on packages/core/test/render3/compiler_canonical_spec.ts
> +      type $MyApp$ = MyApp;
Okay, happy to add cases of both. By host attributes, I'm assuming you mean

```ts
@HostBinding('attr.aria-label') label: string;
```

These bindings can change. Unless you are talking about `@Attibute()` in the constructor? That hasn't been implemented yet, as far as I know.

2018-02-16 17:21 UTC, chuckjaz commented on packages/core/test/render3/compiler_canonical_spec.ts
> +      type $MyApp$ = MyApp;
Neither actually. They are odd as they can only appear in the host configuration field of a directive or component:

```ts
@Directive({
  ...
  host: {
    'foo': 'bar'
  }
})
...
```

This means to unconditionally always set the `foo` attribute of the host element to `bar`.  This means that it only really needs to be done in create mode. This would imply a host binding similar to:

```ts
   hostBinding: (dirIndex, elIndex, cm) => {
     if (cm) {
       $r3$.ɵp(elIndex, 'foo', 'bar');
     }
   }
```

I currently generate these as:

```ts
   hostBinding: (dirIndex, elIndex, cm) => {
     $r3$.ɵp(elIndex, 'foo', 'bar');
   }
```

which constantly and unnecessarily sets these every refresh cycle. I could generate this as,

```ts
   hostBinding: (dirIndex, elIndex, cm) => {
     $r3$.ɵp(elIndex, 'foo', $r3$.ɵb('bar'));
   }
```

which saves the unnecessary DOM write at the cost of a slot. The `cm` parameter saves both.

2018-02-16 17:25 UTC, chuckjaz commented on packages/core/test/render3/compiler_canonical_spec.ts
> +      type $MyApp$ = MyApp;
One example use I found was material uses it to set the `role` attribute: https://github.com/angular/material2/blob/master/src/lib/select/select.ts#L194

2018-02-16 18:16 UTC, kara commented on packages/core/test/render3/compiler_canonical_spec.ts
> +      type $MyApp$ = MyApp;
Ohhhh, I forgot about those! Thanks for clarifying. Seems like I could add a test for the HostBinding attr above and also for host attributes.

In the case above, it seems like we should probably use the `a` instruction (`p` calls `setElementProperty`), but in the style of creation-time bindings as you suggest.

2018-02-16 19:15 UTC, kara commented on packages/core/test/render3/compiler_canonical_spec.ts
> +      type $MyApp$ = MyApp;
Actually, thinking about it more, I think we should be able to put the instruction in `factory`. That way, the attribute is set with other attributes on the element, the instruction does not need to re-run every CD, and we can avoid the code size hit of passing in `cm` for every comp.

2018-02-16 19:49 UTC, mary-poppins commented
You can preview 521d797 at https://pr22213-521d797.ngbuilds.io/.

2018-02-16 20:17 UTC, mhevery requested changes

2018-02-16 20:17 UTC, mhevery commented on packages/core/src/render3/interfaces/definition.ts
> +  attributes?: string[];
This is public API and `string[]` is internal perf implementation. We should take input from user in form of `{[key:string]:string}` and convert it into `[string, string,...]` (just as we do with `inputs` and `outputs`)

2018-02-16 20:18 UTC, mary-poppins commented
You can preview eac770f at https://pr22213-eac770f.ngbuilds.io/.

2018-02-16 20:21 UTC, mary-poppins commented
You can preview efd97c5 at https://pr22213-efd97c5.ngbuilds.io/.

2018-02-16 21:33 UTC, mary-poppins commented
You can preview 5c15f44 at https://pr22213-5c15f44.ngbuilds.io/.

2018-02-16 21:43 UTC, chuckjaz requested changes

2018-02-16 21:43 UTC, chuckjaz commented on packages/core/test/render3/compiler_canonical_spec.ts
> +            $r3$.ɵL('click', $dir$.onClick.bind($dir$));
We cannot use bind as this is not guaranteed to be a method call. Consider changing this to:

```ts
$r3$..ɵL('click',  function HostListenerDir_click_Handler(event) { 
  $dir$.onClick();
})
```
as it also must handle host bindings like:

```ts
@Directive({
  host: {
    '(click)': 'onClick($event), onClack()'
  }
})
class HostListenerExample {
  ...
}
```

which would turn into:

```ts
$r3$..ɵL('click',  function HostListenerDir_click_Handler(event) { 
  $dir$.onClick(event);
  $dir$.onClack();
});
```

2018-02-16 21:43 UTC, chuckjaz commented on packages/core/test/render3/compiler_canonical_spec.ts
> +          attributes: {'role': 'listbox'}
I would prefer `['role', 'listbox']` which avoids the need for `convertToArray` and is consistent with the `element` instruction that has a parameter with the same purpose.

2018-02-16 21:45 UTC, kara commented on packages/core/test/render3/compiler_canonical_spec.ts
> +          attributes: {'role': 'listbox'}
See https://github.com/angular/angular/pull/22213#discussion_r168860375

2018-02-16 21:46 UTC, kara commented on packages/core/test/render3/compiler_canonical_spec.ts
> +            $r3$.ɵL('click', $dir$.onClick.bind($dir$));
The `bind` is to be consistent with how normal listeners are defined (see listener_spec). It seems you want to change this everywhere, not just host listeners?

2018-02-16 22:33 UTC, mhevery approved these changes
Please revert my request. I was mistaken.

2018-02-16 22:33 UTC, mhevery commented on packages/core/test/render3/compiler_canonical_spec.ts
> +          attributes: {'role': 'listbox'}
@kara I am sorry I was totally wrong, Both `startElement` as well as `defineComponent` are public so we should be consistent and use `[string, string]` My fault for making you do unnecessary work. I should have thought it out more.

2018-02-16 23:53 UTC, kara commented on packages/core/test/render3/compiler_canonical_spec.ts
> +          attributes: {'role': 'listbox'}
No worries; I'll revert

2018-02-17 00:43 UTC, mhevery approved these changes

2018-02-17 00:47 UTC, mary-poppins commented
You can preview fb4ebd2 at https://pr22213-fb4ebd2.ngbuilds.io/.

2018-02-17 00:48 UTC, chuckjaz approved these changes

2018-02-17 00:49 UTC, kara commented
[presubmit](https://test.corp.google.com/ui#id=OCL:186064763:BASE:186064792:1518828522797:d5c9fde9)

2018-02-18 21:23 UTC, closed without merging