fix(forms): properly handle special properties in FormGroup.get
angular/angular pull request #22249
Opened 2018-02-16 13:27 UTC by trotyl

closes #17195

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #17195

## What is the new behavior?

`formGroup.get('constructor')` will now return `null`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-02-16 13:28 UTC, trotyl commented on packages/tsconfig.json
> +    "lib": ["es5", "dom", "es2015.promise", "es2015.collection", "es2015.iterable", "es2015.core"],
For `Object.assign()`, object spread in useless in this case.

2018-04-05 22:44 UTC, kara requested changes

2018-04-05 22:44 UTC, kara commented on packages/forms/src/model.ts
> +    this.controls = Object.assign(Object.create(null), controls);
We can't use `Object.assign` because we have to support IE 11.

2018-04-06 12:39 UTC, trotyl commented
Changed to `hasOwnProperty` guard, the size-limit failure seems unrelated.

2018-04-06 17:41 UTC, kara approved these changes
LGTM

2018-04-06 17:50 UTC, kara commented on packages/forms/src/model.ts
> +      return v.controls.hasOwnProperty(name) ? v.controls[name] : null;
You'll need to cast `name` as a `string` or it won't build.

` error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'string'. `

2018-04-06 17:51 UTC, kara requested changes
The type casting needs to be fixed before this can be merged

2018-04-07 07:12 UTC, trotyl commented
Done, but I'll argue it's their own fault for not [using `"lib": ["es2015"]`](https://github.com/Microsoft/TypeScript/blob/4170f35abcec2710c4549d0b3a14d39dd9692988/lib/lib.es2015.core.d.ts#L286) in their configuration on g3.

2018-06-05 23:21 UTC, kara commented
[presubmit](https://test.corp.google.com/ui#id=OCL:191908297:BASE:199376573:1528240867881:97a6b309)

2018-06-06 00:46 UTC, kara approved these changes
LGTM

2018-06-06 01:29 UTC, closed without merging