feat(ivy): implement pipes
angular/angular pull request #22254
Opened 2018-02-16 15:47 UTC by marclaval

This PR implements pipes in Ivy.

Some comments about the decisions taken here:
- `pipeBind1` to `pipeBind4` could be shortened if using the spread operator, but it transpiles into for loops
- `pipeBindV` has a different signature to match `objectLiteralV`
- a pipe can return a `WrappedValue`, which means that any binding can store such object. So when accessing a binding, it has to be unwrapped
- the global cache of pure pipes has been kept, a new global variable has been added to the instruction module (since we don't have a proper application state)
 => the signature of the `pipe` instruction has been changed.  The instruction is responsible for instanciating the pipe (or to use the cache)
 => the canonical spec has updated accordingly
- tests are directly ported from current Angular, most of them test the HTML (sorry @vicb)

2018-02-16 15:47 UTC, marclaval commented on packages/core/src/render3/definition.ts
> +        simpleChanges[minKey] = new SimpleChange(this[privateMinKey], value, isFirstChange);
This is how it works in current Angular

2018-02-16 15:48 UTC, marclaval commented on packages/core/src/render3/node_manipulation.ts
> +      while (viewOrContainer && !viewOrContainer !.next && viewOrContainer !== rootView) {
if the `viewOrContainer` is the `rootView`, then the cleanup is done twice

2018-02-16 17:49 UTC, vicb commented on packages/core/src/render3/definition.ts
> +        simpleChanges[minKey] = new SimpleChange(this[privateMinKey], value, isFirstChange);
If `minKey` is the minified key I think the current Angular does not work this way, i.e. `simpleChanges` is indexed by full property name.

Please add a comment in the code to explain what this code does and the intended user behavior.

2018-02-16 17:55 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +  return purePipeCache;
I think it would make more sense to move the  `getGlobalX()` right after `globalX` ?

2018-02-16 17:56 UTC, vicb commented on packages/core/src/render3/interfaces/view.ts
> +export type TData = (TNode | DirectiveDef<any>| PipeDef<any>| null)[];
update the comment ?

2018-02-16 17:57 UTC, vicb commented on packages/core/src/render3/node_manipulation.ts
> +      while (viewOrContainer && !viewOrContainer !.next && viewOrContainer !== rootView) {
Is there a test ?
Add a comment.

2018-02-16 17:58 UTC, vicb commented on packages/core/src/render3/pipe.ts
> +export function pipe<T>(index: number, pipeDef: PipeDef<T>): void {
Please update the API doc (argument)

2018-02-16 18:03 UTC, vicb commented on packages/core/src/render3/pipe.ts
> +export function pipe<T>(index: number, pipeDef: PipeDef<T>): void {
actually @chuckjaz as implemented the former API in https://github.com/angular/angular/pull/22034/files#diff-b9d784499e486a026b7e92e7a1ee99eaR348

2018-02-16 18:19 UTC, vicb commented on packages/core/src/render3/instructions.ts
> + * A cache of all the pure pipes of the application.
nit: Explain that we only ever need a single instance of each pure pire instead ?

(IMO `A cache of all the pure pipes of the application.` does not add a lot more to `purePipeCache`).

2018-02-16 18:22 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +  purePipeCache.clear();
not sure when `resetApplicationState` gets called.
ie what if we bootstrap 2 components ? could we be destroying a shared cache at this point ?
Add a comment on this function ?

2018-02-16 18:36 UTC, vicb commented on packages/core/src/render3/pipe.ts
> +    bind(result);
`objectLiteral1 ` will be rename to `pureFunction` and will always return a value
see @kara pending PR

2018-02-16 18:39 UTC, vicb commented on packages/core/src/render3/pipe.ts
> +  } else {
no `else` after a `return` ? (might be a personal preference)

2018-02-16 18:45 UTC, vicb commented on packages/core/test/render3/pipe_spec.ts
> +  it('should use the return value of the pipe', () => {
`should use the return value of the pipe` sounds like we are not testing the pipe ?

2018-02-16 18:47 UTC, vicb commented on packages/core/test/render3/pipe_spec.ts
> +  it('should associate pipes right-to-left', () => {
not sure what we test here ? 
Should it be a conformance test rather, ie given a template the pipes will be called in the expected order

2018-02-16 18:49 UTC, vicb commented on packages/core/test/render3/imported_renderer2.ts
> +// TODO: code duplicated from ../linker/change_detection_integration_spec.ts, to be removed
What about 
`// START duplicated code ... // END duplicated code`

2018-02-16 18:49 UTC, vicb commented on packages/core/test/render3/imported_renderer2.ts
> +export function patchLoggingRenderer2(rendererFactory: RendererFactory2, log: RenderLog) {
Add comments ?

2018-02-16 18:54 UTC, vicb commented on packages/core/test/render3/pipe_spec.ts
> +  it('should support calling pure pipes with different number of arguments', () => {
Not sure why ` pure pipes` here ?
Should we have Top Level
```
describe(pipes)
  it(...)
  it(...)
  describe(pure)
    it(...)
  describe(not pure)
    it(...)
```

2018-02-16 18:55 UTC, vicb commented on packages/core/test/render3/pipe_spec.ts
> +  it('should unwrap the wrapped value and force a change', () => {
about pure/not pure would make more sense to get the diff from this test vs the previous ?

2018-02-16 18:57 UTC, vicb commented on packages/core/test/render3/pipe_spec.ts
> +    @Directive({selector: '[testDirective]'})
I very much prefer to have `Directive` / `Pipe` inside the it (aka new style testing) vs the having all the Pipe at the end of the file. Could you change that ?

2018-02-16 19:00 UTC, vicb commented on packages/core/test/render3/pipe_spec.ts
> +    function Template(person: Person, cm: boolean) {
Not sure of the added value of this test ?
Are we testing anything different from the previous one ?

2018-02-16 19:02 UTC, vicb commented on packages/core/test/render3/pipe_spec.ts
> +      pipeInstances.push(memory<CountingPipe>(1), memory(3));
use `<CountingPipe>` consistently ?

2018-02-16 19:03 UTC, vicb commented on packages/core/test/render3/pipe_spec.ts
> +    expect(pipeInstances[3]).toBeAnInstanceOf(CountingPipe);
the instanceOf[1...3] tests are redundant, can be removed

2018-02-16 19:07 UTC, vicb commented
Again I think we should have a clear distinction between
- unit tests,
- integration tests,
- conformance tests.

2018-02-16 19:30 UTC, mhevery requested changes

2018-02-16 19:30 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +const purePipeCache: Map<PipeDef<any>, any> = new Map<PipeDef<any>, any>();
This is a global, which will span multiple apps. A function can be pure, but it may also inject things into its constructor, and what is visible depends on the location of the pipe. So at best we can have cache on template level, not on app level. (see later comment)

2018-02-16 19:30 UTC, mhevery commented on packages/core/src/render3/pipe.ts
> +  tView.data[index] = pipeDef;
why do we need to store this? I don't think that is needed.

2018-02-16 19:30 UTC, mhevery commented on packages/core/src/render3/pipe.ts
> +    if (purePipeCache.has(pipeDef)) {
Looking up values from cache is not the fastest. If the function is pure could we store it in the `TView`? That way our cache is per view (rather than per app). It also means that we don't have to have a global map.  I would imagine something like this:

```
if (pipeDef.pure) {
  pipeInstance = tView.data[index];
} else {
  pipeInstance = pipeDef.n();
}
```

2018-02-16 20:52 UTC, JoostK commented on packages/core/src/render3/definition.ts
> +    pure: pure !== false,
@mhevery Huh?? This simply states that pure defaults to true if not explicitly set to false.

2018-02-16 21:43 UTC, kara commented on packages/core/src/render3/pipe.ts
> +    const value = result === NO_CHANGE ? peekBinding() : result;
The rename PR hasn't gone in yet:

https://github.com/angular/angular/pull/22214

2018-02-17 03:42 UTC, trotyl commented on packages/core/src/render3/definition.ts
> +    pure: pure !== false,
`false !== false` is `false`, isn't it?

2018-02-22 13:17 UTC, marclaval commented on packages/core/src/render3/definition.ts
> +        simpleChanges[minKey] = new SimpleChange(this[privateMinKey], value, isFirstChange);
Adressed in https://github.com/angular/angular/pull/22352

2018-02-22 13:18 UTC, marclaval commented on packages/core/src/render3/node_manipulation.ts
> +      while (viewOrContainer && !viewOrContainer !.next && viewOrContainer !== rootView) {
Adressed in https://github.com/angular/angular/pull/22350

2018-02-22 13:20 UTC, marclaval commented on packages/core/src/render3/pipe.ts
> +  tView.data[index] = pipeDef;
We need it to know if the pipe is pure

2018-02-22 17:30 UTC, marclaval commented
I've updated the PR thanks to your comments. Summary of the changes:
- the lifecycle issues that were discovered have been moved to their own PRs: #22350 and #22352 
- as the pure pipe cache is per template in current Angular, the global cache has been removed. It has been agreed with @chuckjaz to have more work done by the compiler. The canonical spec has been updated accordingly.
- it has been rebased to use pure functions, which I modified as per @mhevery suggestion. I also realised that these pure functions can get `WrappedValue`, so I have done some changes to handle this case.
- tests have been reorganised and improved following @vicb comments.

2018-02-22 18:40 UTC, chuckjaz requested changes

2018-02-22 18:40 UTC, chuckjaz commented on packages/core/test/render3/compiler_canonical/compiler_canonical_spec.ts
> +            let pi: MyPurePipe;
This should be:

```
let $pi$: $MyPurePipe$;
```

and a `type $MyPurePipe$ = MyPurePipe;` be included outside the `// NORMATIVE` block.

This makes it easy for me to cut and paste the normative block into the compiler tests and we can easily see when they are out of sync.

2018-02-22 20:25 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +    return unwrap(value);
you should also probably update `bindingUpdated`(and the tests there)

2018-02-22 21:04 UTC, vicb commented on packages/core/src/render3/pipe.ts
> +  if (pipeDef.pure) {
looks the same as
```
const p = pipeDef.pure && firstInstance ? firstInstance : pipeDef.n();
```

2018-02-22 21:06 UTC, vicb commented on packages/core/src/render3/pipe.ts
> +                         pipeInstance.transform.apply(pipeInstance, values);
`pipeInstance.transform(pipeInstance, ...values);` ?

2018-02-22 21:37 UTC, marclaval commented on packages/core/src/render3/pipe.ts
> +                         pipeInstance.transform.apply(pipeInstance, values);
The spread operator would be transpiled into a for loop, which doesn't seem to be a good idea.

2018-02-22 21:38 UTC, marclaval commented on packages/core/src/render3/pipe.ts
> +  if (pipeDef.pure) {
👍

2018-02-22 22:01 UTC, marclaval commented on packages/core/src/render3/instructions.ts
> +    return unwrap(value);
I don't think so as we want to store the wrapped values, let's double check

2018-02-23 09:46 UTC, marclaval commented
PR updated: comments have been integrated, the disabled tests have been enabled, and one more test has been added to ensure that we always unwrap values before calling a Pipe's transform function.

2018-02-23 18:11 UTC, kara requested changes

2018-02-23 18:11 UTC, kara commented on packages/core/test/render3/pipe_spec.ts
> +      expect(log).toEqual(['pipeWithOnDestroy - ngOnDestroy']);
If you set the age to 25, then 15 again, I think this test will fail. It should be 2 logs, but it will be 3.

2018-02-24 00:48 UTC, mhevery requested changes

2018-02-24 00:48 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +    return unwrap(value);
I think `unwrap` should be used from pipes only. `unwrap` is not small and we should not be pulling in the code if there are no pipes.

2018-02-24 00:48 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +  return changed ? unwrap(value) : NO_CHANGE;
remove `unwrap`

2018-02-24 00:48 UTC, mhevery commented on packages/core/src/render3/pipe.ts
> +  tView.data[index] = pipeDef;
👍  what @kara said

2018-02-24 00:48 UTC, mhevery commented on packages/core/src/render3/pipe.ts
> +      pipeInstance.transform.apply(pipeInstance, values.map(value => unwrap(value)));
do not use `map` in Ivy code as it is not as fast as a for loop.

2018-02-24 00:48 UTC, mhevery commented on packages/core/src/render3/pipe.ts
> +  return isPure(index) ? pureFunction1(pipeInstance.transform, v1, pipeInstance) :
There is an asymmetry between args in pure and non-pure case. They should be the same. Maybe have `isPure && unwrap(x)` as a way of turning pure with wrap into non-pure or something?

2018-02-24 00:48 UTC, mhevery commented on packages/core/src/render3/pipe.ts
> + * @param firstInstance (optional) The first instance of the pipe that can be reused for pure pipes.
Instead of passing `firstInstance` as a `Pipe` we could pass it as an index which would greatly simplify the work which compiler has to do. 

/cc @chuckjaz

2018-02-24 00:48 UTC, mhevery commented on packages/core/src/render3/pipe.ts
> + * @returns T the instance of the pipe which was stored in the bindings array.
I think it should just say `@returns the instance of the pipe`. Come to think of it do we even need to return anything? Can't this just be void?

2018-02-24 00:48 UTC, mhevery commented on packages/core/src/render3/pure_function.ts
> +  return getCreationMode() ? checkAndUpdateBinding(pureFn.call(thisArg)) : consumeBinding();
`pureFn.call(thisArg)` will make it slow all the time. It would be much faster if you do `thisArg ? pureFn.call(thisArg) : pureFn()`

2018-02-24 00:48 UTC, mhevery commented on packages/core/src/render3/pure_function.ts
> +  return different ? checkAndUpdateBinding(pureFn.apply(thisArg, exps.map(exp => unwrap(exp)))) :
don't use `map`

2018-02-24 00:48 UTC, mhevery commented on packages/core/src/render3/util.ts
> +  value = unwrap(value);
This really bugs me that we have to do `unwrap` here. The issue is that we will pull in `unwrap` all the time even if it is not needed. We should only pull it in if we have pipes. So I think we should remove this and rely that `unwrap.toString()` will return the right value by calling `stringify` internally

2018-02-24 00:48 UTC, mhevery commented on packages/core/test/bundling/hello_world/bundle.golden_symbols.json
> +    "name": "WrappedValue"
This is wrong. Hello world should not be pulling in `WrappedValue`

2018-02-24 17:21 UTC, chuckjaz commented on packages/core/src/render3/pipe.ts
> + * @param firstInstance (optional) The first instance of the pipe that can be reused for pure pipes.
Either is fine.

Storing it in a temporary that is not closure captured is simple to generate and is relatively efficient.

Passing in an index is easier. If it is already in an index then the index of the first one is an easy thing to track.

We should do whatever is consistent for the API of the instructions and the most efficient at runtime. The compiler can easily generate either.

2018-02-26 13:23 UTC, marclaval commented on packages/core/src/render3/pure_function.ts
> +      checkAndUpdateBinding(pureFn(unwrap(exp1), unwrap(exp2), unwrap(exp3))) :
You're right, it should, fixed

2018-02-26 13:33 UTC, marclaval commented on packages/core/src/render3/util.ts
> +export function unwrap(value: any): any {
Added

2018-02-26 13:33 UTC, marclaval commented on packages/core/test/render3/pipe_spec.ts
> +      expect(log).toEqual(['pipeWithOnDestroy - ngOnDestroy']);
Done

2018-02-26 13:34 UTC, marclaval commented on packages/core/src/render3/pipe.ts
> + * @returns T the instance of the pipe which was stored in the bindings array.
Returning the instance is needed for the pure cache pipe (see other comment)

2018-02-26 13:34 UTC, marclaval commented on packages/core/src/render3/pipe.ts
> +  tView.data[index] = pipeDef;
👍 Done

2018-02-26 13:42 UTC, marclaval commented on packages/core/src/render3/pipe.ts
> +  return isPure(index) ? pureFunction1(pipeInstance.transform, v1, pipeInstance) :
They can't be the same.

In the pure case, `pureFunction1` will check the bindings and then, if some input has changed, it will unwrap the values and call `transform`.
In the impure case, `transform` can be called immediately with unwrapped values.

2018-02-26 13:43 UTC, marclaval commented on packages/core/src/render3/pipe.ts
> + * @param firstInstance (optional) The first instance of the pipe that can be reused for pure pipes.
Using index was my first idea, but it wouldn't work with embedded views, and it should.

2018-02-26 14:05 UTC, marclaval commented on packages/core/src/render3/pure_function.ts
> +  return getCreationMode() ? checkAndUpdateBinding(pureFn.call(thisArg)) : consumeBinding();
:ok:

2018-02-26 14:06 UTC, marclaval commented on packages/core/src/render3/pure_function.ts
> +  return different ? checkAndUpdateBinding(pureFn.apply(thisArg, exps.map(exp => unwrap(exp)))) :
:ok:

2018-02-26 14:28 UTC, marclaval commented on packages/core/src/render3/pipe.ts
> +      pipeInstance.transform.apply(pipeInstance, values.map(value => unwrap(value)));
:ok:

2018-02-26 16:44 UTC, marclaval commented on packages/core/src/render3/util.ts
> +  value = unwrap(value);
:+1:

2018-02-28 19:29 UTC, marclaval commented
As discussed with @mhevery , the support of `WrappedValue` has been removed for now. PTAL

2018-02-28 21:49 UTC, mhevery approved these changes

2018-02-28 21:49 UTC, mhevery commented on packages/core/test/render3/imported_renderer2.ts
> +// TODO: code duplicated from ../linker/change_detection_integration_spec.ts, to be removed
@marclaval I see that you did what @vicb asked you. Awesome, could you leave a note that this issue has been taken care of, it makes reading the PR easier. I usually leave 👍  or `fixed` note.

2018-02-28 21:52 UTC, mhevery commented on packages/core/src/render3/pipe.ts
> +  return isPure(index) ? pureFunction1(pipeInstance.transform, v1, pipeInstance) :
Now that we have removed `unwrap` can we make them symmetric?

2018-02-28 21:52 UTC, mhevery commented
Please resolve conflicts

2018-02-28 21:54 UTC, chuckjaz approved these changes

2018-03-01 05:50 UTC, kara approved these changes
LGTM

2018-03-01 08:52 UTC, marclaval commented on packages/core/src/render3/pipe.ts
> +  return isPure(index) ? pureFunction1(pipeInstance.transform, v1, pipeInstance) :
@mhevery Can you please clarify what you have in mind?

2018-03-01 08:53 UTC, marclaval commented
Rebased

2018-03-06 14:29 UTC, marclaval commented
Rebased, PTAL

2018-03-06 16:52 UTC, chuckjaz commented on packages/core/src/render3/pure_function.ts
> +export function pureFunction0<T>(pureFn: () => T, thisArg: any = null): T {
Consider just using `thisArg?: any` as adds `if (thisArg === void 0) { thisArg = null; }` to the beginning of the function for no good reason.

2018-03-06 17:20 UTC, chuckjaz submitted a review, later dismissed

2018-03-06 17:20 UTC, chuckjaz commented on packages/core/test/render3/compiler_canonical/pipes_spec.ts
> +          let pi: MyPurePipe;
Change to `let pi: $MyPurePipe$` (with the corresponding `type` declaration above) as all types are non-canonical

2018-03-06 17:20 UTC, chuckjaz commented on packages/core/test/render3/compiler_canonical/pipes_spec.ts
> +          $r3$.ɵt(0, $r3$.ɵi1('', $r3$.ɵpb2(1, ctx.name, ctx.size), ''));
Consider adding an example with an embedded template to demonstrate why the local is needed (not just a slot value) and why the `let` should be outside the block. These are both necessary but the normative example does not show an example where this is required.

2018-03-06 17:23 UTC, marclaval commented on packages/core/src/render3/pure_function.ts
> +export function pureFunction0<T>(pureFn: () => T, thisArg: any = null): T {
:+1:

2018-03-07 11:03 UTC, marclaval commented on packages/core/test/render3/compiler_canonical/pipes_spec.ts
> +          let pi: MyPurePipe;
Done

2018-03-07 11:04 UTC, marclaval commented on packages/core/test/render3/compiler_canonical/pipes_spec.ts
> +          $r3$.ɵt(0, $r3$.ɵi1('', $r3$.ɵpb2(1, ctx.name, ctx.size), ''));
Done with a structural directive

2018-03-07 19:16 UTC, chuckjaz approved these changes

2018-03-07 23:28 UTC, mhevery commented
http://test/OCL:188244226:BASE:188244256:1520465278593:6088a334

2018-03-08 04:59 UTC, closed without merging