fix(common): inconsistency on TitleCasePipe
angular/angular pull request #22322
Opened 2018-02-20 03:55 UTC by ottonascarella

TitleCasePipe was not behaving as expected with non-ascii characters.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

TitleCasePipe was not working on strings containing accent characters. Ex: é ó å ä ü, etc...

Issue Number: N/A

## What is the new behavior?
It works with those.

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

Bug was found on https://br.udacity.com

2018-02-20 14:06 UTC, trotyl commented
Relates to #20123

2018-02-20 14:16 UTC, ottonascarella commented
yeah. it should close his case too, although his case should not close mine.
I will write his tests on mine too later on.

2018-02-20 19:32 UTC, vicb commented on packages/common/src/pipes/case_conversion_pipes.ts
> +    return value.toLocaleLowerCase();
If we use the `toLocaleLowerCase()` variant, we should inject the locale and use it.

2018-02-20 19:33 UTC, vicb requested changes
Great change, thanks.

Please use the system wide locale.

2018-02-20 20:32 UTC, gkalpak commented on packages/common/src/pipes/case_conversion_pipes.ts
> +  return str.split(/\s/g)
Just wanted to point out that this is potentially a BC. E.g. `reg,green,blue` would previously become `Reg,Green,Blue`.
Since apparently the rules for title-casing aren't standardized, it might be a good idea to be explicit about what this pipe does.

2018-02-20 20:33 UTC, gkalpak commented on packages/common/src/pipes/case_conversion_pipes.ts
> +      .join(' ');
This will replace all whitespace characters (e.g. `\t` or `\n`) with ` `, which is unexpected (even if uncommon :smiley:).

2018-02-20 21:57 UTC, ottonascarella commented on packages/common/src/pipes/case_conversion_pipes.ts
> +    return value.toLocaleLowerCase();
I don't think it should be necessary. I can revert to using `toLowerCase` and `toUpperCase` which were working (regex was culprid)

2018-02-21 06:24 UTC, vicb commented on packages/common/src/pipes/case_conversion_pipes.ts
> +    return value.toLocaleLowerCase();
yep please revert then

2018-02-21 06:29 UTC, vicb commented
This is a change in behavior (wrt to the aaa,bbb,ccc mentioned by @gkalpak) and the implementation could be simpler.
I think we need to discuss that with the team.

2018-02-27 07:28 UTC, MattiJarvinen-BA commented
I don't even get why use title case pipe. 
CSS has `text-transform: capitalize;`
https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform

2018-03-23 20:04 UTC, gkalpak commented
Handling accent characters has been fixed by #22600.
AFAICT, this is obsolete now.

##
WRT https://github.com/angular/angular/pull/22322#issuecomment-368772636, it would be fun to make a titlecase pipe that is compatible with the CSS spec :grin:

2018-03-23 20:04 UTC, closed without merging