feat(common): export pipe utility functions
angular/angular pull request #22372
Opened 2018-02-22 16:07 UTC by ocombe

## PR Type
What kind of change does this PR introduce?

```
[x] Feature
```

## What is the current behavior?

If you want to use the number, percent, currency and date pipes outside of your templates, you need to instantiate those pipes and manually transform the values

Issue Number: #20536

## What is the new behavior?
The utility functions `formatNumber`, `formatPercent`, `formatCurrency`, and `formatDate` used by the number, percent, currency and date pipes are now available for developers who want to use them outside of templates.

## Does this PR introduce a breaking change?
```
[x] No
```

2018-02-22 16:17 UTC, mary-poppins commented
You can preview aee9a42 at https://pr22372-aee9a42.ngbuilds.io/.

2018-02-22 16:39 UTC, mary-poppins commented
You can preview c4e518f at https://pr22372-c4e518f.ngbuilds.io/.

2018-02-22 17:21 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * @stable
needs more doc !

2018-02-22 17:22 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * Transforms a value into a date
comment here do no say anything more than `toDate()`. 
Pls improve

2018-02-22 17:22 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * Transforms a value into a date
refine type also

2018-02-22 17:22 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +     * For ISO Strings without time the day, month and year must be extracted from the ISO String
move to API doc of the function ?

2018-02-22 17:23 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +export function isoStringToDate(match: RegExpMatchArray): Date {
add a comment here pls

2018-02-22 17:23 UTC, vicb commented on packages/common/src/i18n/format_number.ts
>   *
please add docs

2018-02-22 17:24 UTC, vicb commented on packages/common/src/i18n/format_number.ts
>   *
please add docs

2018-02-22 17:24 UTC, vicb commented on packages/common/src/pipes/date_pipe.ts
> + * If you want to use this pipe outside of a template, you can use the function
no you don't want to use the pipe outside of a template. Remove ?

2018-02-22 17:25 UTC, vicb commented on packages/common/src/pipes/number_pipe.ts
> + * If you want to use this pipe outside of a template, you can use the function
same comment as other non-pipes

2018-02-22 17:26 UTC, vicb commented on packages/common/test/pipes/date_pipe_spec.ts
> +        expect(isDate(toDate(date))).toBeTruthy();
what is the intent here ?
Does this belong to `date_pipe_spec.ts` ?

2018-02-22 17:31 UTC, vicb requested changes
Please
- Add or expand the API docs. Especially important for API docs. Internal functions should also have a short comment,
- refine date type from "any" to a|b|c,
- I was expected to see more tests moved to the new format spec. It doesn't make sense any more to have them in the pipes if pipes only forward to those functions (only a sanity check is ok for the pipes).

2018-02-23 15:36 UTC, ocombe commented on packages/common/src/i18n/format_date.ts
> +     * For ISO Strings without time the day, month and year must be extracted from the ISO String
No, it's there to explain the method used to convert the ISO string to a date, but it has no value for people who use the function.

2018-02-23 17:20 UTC, mary-poppins commented
You can preview 0fe525a at https://pr22372-0fe525a.ngbuilds.io/.

2018-02-23 17:25 UTC, mary-poppins commented
You can preview d4d8baa at https://pr22372-d4d8baa.ngbuilds.io/.

2018-02-23 17:25 UTC, mary-poppins commented
You can preview a3fd774 at https://pr22372-a3fd774.ngbuilds.io/.

2018-02-23 17:46 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * - `value` is a date object or a number (milliseconds since UTC epoch) or an ISO string
please update the type accordingly

2018-02-23 17:47 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * - `value` is a date object or a number (milliseconds since UTC epoch) or an ISO string
"is a `Date` or"

2018-02-23 17:48 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * - `locale` is a `string` defining the locale to use (uses the current {@link LOCALE_ID} by
no default

2018-02-23 17:50 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + *  `'+0430'` (4 hours, 30 minutes east of the Greenwich meridian)
remove "(4 hours, 30 minutes east of the Greenwich meridian)" - no added value and technically wrong GMT vs UTC

2018-02-23 17:51 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + *  If not specified, the local system timezone of the end-user's browser will be used.
"the local system timezone of the end-user's browser will be used." -> host system settings are used.

2018-02-23 17:51 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * See {@link DatePipe} for more details about the parameters.
See {@link DatePipe} for more details

2018-02-23 17:52 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +  let date = toDate(value);
const

2018-02-23 17:56 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +       * For ISO Strings without time the day, month and year must be extracted from the ISO String
move to the API doc of toDate

2018-02-23 17:57 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * Transforms a value into a date. The supported values are dates, numbers, numeric strings
throw if not able to convert to a date

2018-02-23 17:58 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * This function converts a string matching the ISO8601_DATE_REGEX to a date.
"This function converts a string matching the ISO8601_DATE_REGEX to a date." 
What does this means ?
What about "Convert a date in ISO8601 to a `Date`" ?

2018-02-23 17:59 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> +  const h = +(match[4] || '0') - tzHour;
+ -> Number, '0' -> 0

2018-02-23 17:59 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> +function formatNbToStr(
formatNbAsString ?

2018-02-23 18:00 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> + * - `locale` is a `string` defining the locale to use (uses the current {@link LOCALE_ID} by
no default

2018-02-23 18:03 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * description.
nit: I think aligning the text for continued line is easier to read

2018-02-23 18:03 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> + * - `value` is a number.
does not match the function !

2018-02-23 18:04 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> + * - `value` is a number.
does not match the fn - number only seems to be the right thing

2018-02-23 18:04 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> + * - `locale` is a `string` defining the locale to use (uses the current {@link LOCALE_ID} by
no default

2018-02-23 18:04 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> + * - `value` is a number.
again

2018-02-23 18:05 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> + * configurations are based on the active locale.
active locale -> locale.

2018-02-23 18:05 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> + * - `locale` is a `string` defining the locale to use (uses the current {@link LOCALE_ID} by
no default

2018-02-23 18:05 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> + *   - `minFractionDigits` is the minimum number of digits after fraction. Defaults to `0`.
"after fraction" is it the correct terminology ?

2018-02-23 18:07 UTC, vicb commented on packages/common/test/i18n/format_date_spec.ts
> +    describe('transform', () => {
transform ?

2018-02-23 18:08 UTC, vicb commented on packages/common/test/i18n/format_number_spec.ts
> +{
remove this

2018-02-23 18:08 UTC, vicb commented on packages/common/test/i18n/format_date_spec.ts
> +{
remove

2018-02-23 18:09 UTC, vicb commented on packages/common/test/pipes/date_pipe_spec.ts
> +         () => { expect(() => pipe.transform('2015-06-15T21:43:11Z')).not.toThrow(); });
revert the diffs ?

2018-02-23 18:35 UTC, ocombe commented on packages/common/src/i18n/format_date.ts
> +  let date = toDate(value);
we change the value later if there is a timezone

2018-02-23 19:11 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * Converts a value to date
missing final .

2018-02-23 19:12 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * Convert a date in ISO8601 to a Date.
Convert*s*

2018-02-23 19:12 UTC, vicb commented on packages/common/src/i18n/format_date.ts
> + * Used instead of Date.parse because of browser discrepancies.
quote `Date.parse`

2018-02-23 19:13 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> + * - `value` is a number or numeric string.
wrong way ! -> number

2018-02-23 19:14 UTC, vicb commented on packages/common/src/i18n/format_number.ts
> + * - `digitInfo` is a `string` which has a following format: <br>
add to all pipes or no pipe (other have `{@link ...}`)

2018-02-23 19:24 UTC, mary-poppins commented
You can preview da8586b at https://pr22372-da8586b.ngbuilds.io/.

2018-02-23 20:15 UTC, wKoza commented on packages/common/src/i18n/format_date.ts
>      strNum = strNum.substr(strNum.length - digits);
`strNum.length - digits` isn't always equal to `0`?

2018-02-23 20:15 UTC, wKoza commented on packages/common/src/i18n/format_date.ts
> + * - `Date`s
`Date`

2018-02-23 20:45 UTC, ocombe commented on packages/common/src/i18n/format_date.ts
>      strNum = strNum.substr(strNum.length - digits);
not always, we can have additional zeros

2018-02-23 21:06 UTC, mary-poppins commented
You can preview 6d02858 at https://pr22372-6d02858.ngbuilds.io/.

2018-02-23 21:37 UTC, mary-poppins commented
You can preview dc77b4e at https://pr22372-dc77b4e.ngbuilds.io/.

2018-02-23 21:43 UTC, IgorMinar approved these changes
the rest looks good. thanks

2018-02-23 21:43 UTC, IgorMinar commented on packages/common/src/i18n/format_number.ts
> +function formatNbToLocaleString(
please avoid using custom abbreviations in non-local variables. formatNbToLocaleString -> formatNumberToLocaleString

anyone not familiar with our codebase that sees "Nb" will have to question what it means. This makes our code base harder to read and change by people not familiar with every change we make - e.g. our community, but also team members working on other parts of the code base that come across this code.

2018-02-23 22:20 UTC, vicb approved these changes

2018-02-23 22:22 UTC, vicb commented
[presubmit](	http://test/OCL:186822308:BASE:186822499:1519424521742:7ea2c4fa
)

2018-02-23 22:24 UTC, mary-poppins commented
You can preview 8ce1f81 at https://pr22372-8ce1f81.ngbuilds.io/.

2018-02-23 22:58 UTC, closed without merging