build(aio): jsdoc tag changes
angular/angular pull request #22401
Opened 2018-02-23 13:52 UTC by petebacondarwin

Addresses #22135 and #22385

2018-02-23 14:00 UTC, mary-poppins commented
You can preview 4a9a812 at https://pr22401-4a9a812.ngbuilds.io/.

2018-02-23 14:10 UTC, petebacondarwin commented
Here is a good example of the `description` splitting: https://pr22401-4a9a812.ngbuilds.io/api/animations/AnimationBuilder

The rendered docs look like:

![screen shot 2018-02-23 at 14 09 50](https://user-images.githubusercontent.com/15655/36598183-3f0ae86e-18a3-11e8-8fde-0650cee0c1af.png)

While the original source code comment looks like:

![screen shot 2018-02-23 at 14 10 09](https://user-images.githubusercontent.com/15655/36598211-57f7aa88-18a3-11e8-9e57-fff78bde1194.png)

2018-02-23 15:12 UTC, mary-poppins commented
You can preview 4c56f8b at https://pr22401-4c56f8b.ngbuilds.io/.

2018-02-23 18:18 UTC, mary-poppins commented
You can preview b4d9007 at https://pr22401-b4d9007.ngbuilds.io/.

2018-02-25 10:10 UTC, mary-poppins commented
You can preview 9d42efc at https://pr22401-9d42efc.ngbuilds.io/.

2018-02-26 22:11 UTC, mary-poppins commented
You can preview a138ceb at https://pr22401-a138ceb.ngbuilds.io/.

2018-02-26 22:24 UTC, gkalpak requested changes

2018-02-26 22:24 UTC, gkalpak commented on aio/src/styles/0-base/_typography.scss
> -}
This change seems totally unrelated to this commit. Maybe move it in a separate one 😇 
Also, there is one more `h1:after` style in `_typography.scss` and one in `_marketing-layout.scss` that are redundant now.

2018-02-26 22:24 UTC, gkalpak commented on aio/tools/transforms/templates/api/includes/what-it-does.html
> -<div class="what-it-does info-banner">
If we don't use `info-banner` any more here, could we remove the corresponding CSS styles?

2018-02-26 22:24 UTC, gkalpak commented on aio/tools/transforms/templates/api/export-base.template.html
> +  <p class="short-description">{$ doc.shortDescription | marked $}</p>
Is it possible to not have `shortDescription`? In that case, would it be better to omit the `<p>` altogether?

2018-02-26 22:24 UTC, gkalpak commented on aio/tools/transforms/templates/api/class.template.html
> +  <p class="short-description">{$ doc.shortDescription | marked $}</p>
Is it possible to not have `shortDescription`? In that case, would it be better to omit the `<p>` altogether?

2018-02-26 22:24 UTC, gkalpak commented on aio/tools/transforms/angular-api-package/tag-defs/usageNotes.js
> +module.exports = function(log, createDocMessage) {
Unused deps :grin:

2018-02-26 22:24 UTC, gkalpak commented on aio/tools/transforms/angular-api-package/processors/splitDescription.js
> +          const endOfParagraph = description.indexOf('\n\n');
Is it possible to have whitespace between the two `\n`?

2018-02-26 22:29 UTC, petebacondarwin commented on aio/tools/transforms/angular-api-package/processors/splitDescription.js
> +          const endOfParagraph = description.indexOf('\n\n');
That would be nasty 😠 but OK, I guess we can handle that too.

2018-02-26 22:30 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/class.template.html
> +  <p class="short-description">{$ doc.shortDescription | marked $}</p>
I think that the short description will come under the "required" parts of the API docs.

2018-02-26 22:30 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/export-base.template.html
> +  <p class="short-description">{$ doc.shortDescription | marked $}</p>
https://github.com/angular/angular/pull/22401#discussion_r170758306

2018-02-27 10:40 UTC, petebacondarwin commented on aio/tools/transforms/angular-api-package/processors/splitDescription.spec.js
> +fdescribe('splitDescription processor', () => {
Oops

2018-02-27 11:05 UTC, mary-poppins commented
You can preview 5bd18b0 at https://pr22401-5bd18b0.ngbuilds.io/.

2018-02-27 11:05 UTC, mary-poppins commented
You can preview 6d0e882 at https://pr22401-6d0e882.ngbuilds.io/.

2018-02-27 21:20 UTC, gkalpak approved these changes
:100:

2018-02-27 21:20 UTC, gkalpak commented on aio/src/styles/0-base/_typography.scss
> -    margin: 0;
Why remove this style?

2018-02-28 10:38 UTC, petebacondarwin commented on aio/src/styles/0-base/_typography.scss
> -    margin: 0;
Previously there was an underline beneath `h1` tags. This underline was given the appropriate margin (`8px 0`) for the surrounding text.  Now that the underline has gone the margins are set by the following rule.

That being said, I now see that this rule also removes margin from before the `h1` on narrow screens so I will put that back in.

2018-02-28 10:46 UTC, petebacondarwin commented on aio/src/styles/0-base/_typography.scss
> -    margin: 0;
See last fixup commit 1443bfb190856ebd60ddbbaaf987a2ce3032be18

2018-02-28 10:52 UTC, mary-poppins commented
You can preview 1443bfb at https://pr22401-1443bfb.ngbuilds.io/.

2018-02-28 18:44 UTC, closed without merging