feat(ivy): support OnPush change detection
angular/angular pull request #22417
Opened 2018-02-23 21:37 UTC by kara

This PR adds basic support for OnPush change detection. Specifically:

- Adds flags for components that are OnPush and Dirty
- Marks components dirty if their inputs have changed
- Marks components dirty if an event occurs inside them
- Skips checking any components that are OnPush and not dirty

TODO in follow-up PRs: 
- Support injection of ChangeDetectorRef
- Support calling markForCheck / detectChanges programmatically
- Support attaching/detaching views from change detection

2018-02-23 21:45 UTC, mary-poppins commented
You can preview 09d6b1f at https://pr22417-09d6b1f.ngbuilds.io/.

2018-02-23 22:16 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +  creationMode = newView && (newView.flags & LViewFlags.CreationMode) === 1;
humm:
- why checking for newView ? (type is `newView: LView`)
- either remove the check or update the callsite to remove `!` overrides ?
- `=== 1` should be `=== LViewFlags.CreationMode` (`!== 0` also works)

2018-02-23 22:18 UTC, mary-poppins commented
You can preview 6d3d0e7 at https://pr22417-6d3d0e7.ngbuilds.io/.

2018-02-23 22:19 UTC, mary-poppins commented
You can preview 9363bbb at https://pr22417-9363bbb.ngbuilds.io/.

2018-02-23 22:21 UTC, kara commented on packages/core/src/render3/instructions.ts
> +  creationMode = newView && (newView.flags & LViewFlags.CreationMode) === 1;
1.  It's not guaranteed to exist, so `newView` is checked in the lines above too. For history, see change introduced here: https://github.com/angular/angular/pull/22018/files#diff-ce885db4223480bd4f7b78bd22b6f058R139.

2. Re === 1, they are functionally the same, but I agree that the latter is probably clearer :+1

2018-02-23 22:24 UTC, vicb commented on packages/core/src/render3/interfaces/view.ts
> +   * First bit: Whether or not the view is in creationMode.
What about a {@link LViewFlags} instead of this line ?
The fact that is it the first or a random bit 
- has no added value here,
- can change

2018-02-23 22:25 UTC, vicb commented on packages/core/src/render3/interfaces/view.ts
> +/** Flags associated with an LView (see LView.flags) */
const enum ?

2018-02-23 22:25 UTC, kara commented on packages/core/src/render3/interfaces/view.ts
> +   * First bit: Whether or not the view is in creationMode.
I realized the same thing, so the second commit moves it. If you look at the file changes from there, you should see the update.

2018-02-23 22:28 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +function buildViewFlags(onPush: boolean): LViewFlags {
comment or name should specify "creation" ?

2018-02-23 22:30 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +    (cleanup || (cleanup = currentView.cleanup = [
```
const cleanups = ...;
cleanups.push(...);
```
to optimize readability ? (same above)

2018-02-23 22:31 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +  while (view != null) {
`let currentView: LView|null = view;` and remove the `!` ?

2018-02-23 22:32 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +    markOnPushDirty(node);
do we mark dirty if `!isDifferent()` ?

2018-02-23 22:33 UTC, kara commented on packages/core/src/render3/instructions.ts
> +    markOnPushDirty(node);
This is guarded by the bind() function, which has the `isDifferent` check. Values of `NO_CHANGE` return early above.

2018-02-23 22:34 UTC, vicb commented on packages/core/src/render3/interfaces/view.ts
> +  /** Whetehr or not this view is currently dirty (needing check) */
typo in `Whether`

2018-02-23 22:48 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +  creationMode = newView && (newView.flags & LViewFlags.CreationMode) === 1;
2) It is the same until you change CreationMode.

2018-02-23 23:05 UTC, mary-poppins commented
You can preview 7e9dcd2 at https://pr22417-7e9dcd2.ngbuilds.io/.

2018-02-23 23:16 UTC, mary-poppins commented
You can preview 1b37227 at https://pr22417-1b37227.ngbuilds.io/.

2018-02-23 23:24 UTC, mhevery requested changes

2018-02-23 23:24 UTC, mhevery commented on packages/core/src/render3/component.ts
> +          null, rootContext, componentDef.onPush),
What do you think about: `component.onPush ? LViewFlags.ON_PUSH : LViewFlags.CHECK_ALWAYS`. This way you can push the flags directly in, rather than push boolean which needs to be later converted.

2018-02-23 23:24 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +function buildViewFlags(onPush: boolean): LViewFlags {
I think this function can be dropped. See my other comment about not passing a boolean around.

2018-02-23 23:24 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> +}
Add:
```
ON_PUSH = LViewFlags.Dirty | LViewFlags.OnPush | LViewFlags.CreationMode,
CHECK_ALWAYS = LViewFlags.CreationMode,
```

match the camel case as needed.

2018-02-23 23:24 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +    markSelfAndParentsDirty(view);
I am not sure if this is sufficient. Can you see how `markDirty` works int `component.ts`. I think we should also be scheduling this for CD not just marking it.

2018-02-23 23:24 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +function wrapListenerWithDirtyLogic(view: LView, listener: EventListener): EventListener {
can we move this function to a separate file `change_detection.ts` to keep `instructions.ts` to a minimum. I don't think this function accesses global state so it does not need to be here.

2018-02-23 23:24 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +export function markSelfAndParentsDirty(view: LView): void {
can we move this function to a separate file `change_detection.ts` to keep `instructions.ts` to a minimum. I don't think this function accesses global state so it does not need to be here.

2018-02-23 23:24 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +/** If node is an OnPush component, marks its LView dirty. */
can we move this function to a separate file `change_detection.ts` to keep `instructions.ts` to a minimum. I don't think this function accesses global state so it does not need to be here.

2018-02-23 23:24 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +    if (hostView.flags & LViewFlags.OnPush && (hostView.flags & LViewFlags.Dirty) == 0) {
Instead of `0` Can we have some ` === LViewFlags.SOMETHING` (more readable). (also use `===` not `==`)

2018-02-23 23:24 UTC, mhevery commented on packages/core/src/render3/interfaces/definition.ts
> +
revert

2018-02-23 23:24 UTC, mhevery commented on packages/core/src/render3/interfaces/definition.ts
> +  readonly onPush: boolean;
what do you think of returning `LViewFlags` directly here? That would make `LViewFlags` public API. I am on the fence.

2018-02-23 23:24 UTC, mhevery commented on packages/core/src/render3/interfaces/definition.ts
> +  changeDetection?: ChangeDetectionStrategy;
What do you think of converting `ChangeDetectionStrategy` into `const enum`?

2018-02-23 23:42 UTC, kara commented on packages/core/test/render3/on_push_spec.ts
> +  it('should call doCheck even when OnPush components are not dirty', () => {
Discussed offline, keeping as is

2018-02-24 00:26 UTC, kara commented on packages/core/src/render3/interfaces/definition.ts
> +  readonly onPush: boolean;
Discussed offline, keeping as is

2018-02-24 00:35 UTC, kara commented on packages/core/src/render3/interfaces/definition.ts
> +  changeDetection?: ChangeDetectionStrategy;
Sounds good to me. @chuckjaz WDYT?

2018-02-24 02:30 UTC, mary-poppins commented
You can preview bba8fb1 at https://pr22417-bba8fb1.ngbuilds.io/.

2018-02-24 03:32 UTC, mary-poppins commented
You can preview 2e4fed6 at https://pr22417-2e4fed6.ngbuilds.io/.

2018-02-24 03:59 UTC, mary-poppins commented
You can preview 630dab8 at https://pr22417-630dab8.ngbuilds.io/.

2018-02-26 22:37 UTC, mhevery approved these changes

2018-02-26 22:37 UTC, mhevery requested changes
Per comments above

2018-02-26 23:13 UTC, kara commented on packages/core/src/render3/change_detection.ts
> +    view: LView, listener: EventListener, scheduler: (c: any) => void): EventListener {
This is really the `scheduleChangeDetection` function. We can't import it into this file without creating a circular dependency, so it has to be explicitly passed in if we want to call it.  We could try re-creating it here, but it uses `detectChanges` which also has dependencies from `instructions`. I think it might make the most sense to re-integrate `change_detection.ts` with 1instructions` into one file.

2018-02-26 23:16 UTC, kara commented on packages/core/src/render3/change_detection.ts
> +function markSelfAndParentsDirty(view: LView, scheduler: (c: any) => void): void {
We would have to move a few more functions into instructions, but seems like a good idea 👍

2018-02-26 23:19 UTC, kara commented on packages/core/src/render3/instructions.ts
> +export function getCleanPromise(): Promise<null> {
I was trying to avoid the pattern [here](https://github.com/angular/angular/blob/master/packages/core/src/render3/PERF_NOTES.md#exporting-top-level-variables). Doesn't apply here?

2018-02-26 23:44 UTC, mhevery commented on packages/core/src/render3/change_detection.ts
> +    view: LView, listener: EventListener, scheduler: (c: any) => void): EventListener {
Can we move the code around so that it does not create circular dep. I don't think there is any reason why it has to be where it is.

2018-02-26 23:44 UTC, mhevery commented on packages/core/src/render3/change_detection.ts
> +function markSelfAndParentsDirty(view: LView, scheduler: (c: any) => void): void {
lets do that.

2018-02-26 23:45 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +export function getCleanPromise(): Promise<null> {
Yes it applies but there is more than one way to solve it. I think 

```
const _CLEAN_PROMISE = ...;
export const CLEAN_PROMISE  = _CLEAN_PROMISE;
```

is a better way to do that.

2018-02-27 00:22 UTC, mary-poppins commented
You can preview 2418393 at https://pr22417-2418393.ngbuilds.io/.

2018-02-28 04:33 UTC, mhevery approved these changes
please fix indentation, otherwise LGTM

2018-02-28 04:33 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +*
indentation seems messed up

2018-02-28 04:34 UTC, mhevery approved these changes

2018-02-28 04:38 UTC, kara commented on packages/core/src/render3/instructions.ts
> +*
Fixed, thank you!

2018-02-28 04:42 UTC, kara commented
[presubmit](https://test.corp.google.com/ui#id=OCL:187274235:BASE:187274254:1519792885490:ff578ea8)

2018-02-28 04:44 UTC, mary-poppins commented
You can preview f975d8c at https://pr22417-f975d8c.ngbuilds.io/.

2018-02-28 09:32 UTC, trotyl commented on packages/core/src/render3/instructions.ts
> +    listener(e);
This is not compatible with `return false` usage, is it?

2018-02-28 15:22 UTC, kara commented on packages/core/src/render3/instructions.ts
> +    listener(e);
Nope, we don't support that yet (outside the scope of this PR).

2018-02-28 18:43 UTC, closed without merging