Fix table in comparing-observables.md
angular/angular pull request #22485
Opened 2018-02-28 04:42 UTC by ro-savage

Fix table in comparing-observables.md that was incorrectly formatted.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Table columns are off by one.

Issue Number: N/A

## What is the new behavior?
Table formatted correctly.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2018-07-31 19:20 UTC, brandonroberts requested changes
Update the git commit message to `docs: fix table formatting in comparing observables guide`

2018-08-02 19:09 UTC, brandonroberts approved these changes

2018-08-02 19:17 UTC, mary-poppins commented
You can preview 95151a1 at https://pr22485-95151a1.ngbuilds.io/.

2018-08-06 19:01 UTC, IgorMinar approved these changes

2018-08-06 20:42 UTC, closed without merging