feat(ivy): add support for the ngProjectAs attribute
angular/angular pull request #22498
Opened 2018-02-28 16:47 UTC by pkozlowski-opensource

This PR adds support for the `ngProjectAs` attribute. 

The implementation in this PR requires us to store a CSS selector (from the `<ng-content>`'s `select` attribute) in **both** parsed and raw (un-parsed) form. The raw form is needed so we can easily compare it with a value of the `ngProjectAs` attribute.

@chuckjaz this PR changes the compiler's canonical spec for content projection, so the compiler's implementation will have to be updated accordingly.

2018-02-28 18:09 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +    if (attrs[i] !== NG_PROJECT_AS_ATTR_NAME) {
what about
```
const attrName = a[i];
const attrValue = a[i+1];
// ... use attrName & attrValue
```

2018-02-28 18:10 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +      const matchedIdx = matchingSelectorIndex(componentChild.tNode, selectors !, rawSelectors !);
You should be able to remove the ! from `selectors !` (b/c `if (selectors)`)

2018-02-28 18:11 UTC, vicb commented on packages/core/src/render3/node_selector_matcher.ts
> +function isNodeMatchingProjectAs(tNode: TNode, rawSelector: string): boolean {
comment ?

2018-02-28 18:14 UTC, vicb commented on packages/core/src/render3/node_selector_matcher.ts
> +    if (ngProjectAsAttrIdx > -1) {
`if (ngProjectAsAttrIdx & 1 === 0)` -> add a test

2018-02-28 18:16 UTC, vicb commented on packages/core/src/render3/node_selector_matcher.ts
> +    if (ngProjectAsAttrIdx > -1) {
Should `NG_PROJECT_AS_ATTR_NAME` always come first and then we don't have to iterate ?

2018-02-28 18:19 UTC, vicb commented on packages/core/src/render3/node_selector_matcher.ts
> +    if (isNodeMatchingProjectAs(tNode, rawSelectors[i]) ||
Is this logic right ?
I think that when a node is ngProjectedAs we should not isNodeMatchingSelector

2018-02-28 18:25 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> + * @param rawSelectors A collection of CSS selectors in the raw, un-parsed form
I think `rawSelectors` needs more documentation. Why is it needed, What is the format., how to use it. Also why do we have two different formats? Can it be unified?

2018-02-28 19:14 UTC, chuckjaz approved these changes
The changes to the compiler spec look good.

2018-02-28 20:04 UTC, vicb commented on packages/core/src/render3/instructions.ts
> + * @param rawSelectors A collection of CSS selectors in the raw, un-parsed form
maybe `textSelectors` ?

2018-02-28 20:04 UTC, vicb requested changes
See inline comments

2018-03-01 09:15 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +    if (attrs[i] !== NG_PROJECT_AS_ATTR_NAME) {
👍 done

2018-03-01 09:31 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +      const matchedIdx = matchingSelectorIndex(componentChild.tNode, selectors !, rawSelectors !);
👍 done

2018-03-01 09:33 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_selector_matcher.ts
> +function isNodeMatchingProjectAs(tNode: TNode, rawSelector: string): boolean {
IMO the function name is descriptive enough, don't think a comment would bring much more here. Prefer to leave as-is.

2018-03-01 09:37 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_selector_matcher.ts
> +    if (ngProjectAsAttrIdx > -1) {
> if (ngProjectAsAttrIdx & 1 === 0)

Huh? I find it hard to read / understand and not sure how it is better as compared to simple `ngProjectAsAttrIdx > -1`. I might be missing your intention here but for now prefer to leave as-is. 

Adding a test, though.

2018-03-01 09:38 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_selector_matcher.ts
> +    if (ngProjectAsAttrIdx > -1) {
> Should `NG_PROJECT_AS_ATTR_NAME` always come first and then we don't have to iterate ?

It would be a possible runtime optimisation at the expense of more work in the compiler. I will let @chuckjaz to decide.

2018-03-01 10:30 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_selector_matcher.ts
> +    if (isNodeMatchingProjectAs(tNode, rawSelectors[i]) ||
Oh, good catch! You are right, we should probably _not_ match selectors if `ngProjectAs` is not matching. Changed the logic and added a test. Thnx!

2018-03-01 10:35 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_selector_matcher.ts
> +    if (ngProjectAsAttrIdx > -1) {
> if (ngProjectAsAttrIdx & 1 === 0) -> add a test

This function went away with the recent code changes.

2018-03-01 10:39 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_selector_matcher.ts
> +function isNodeMatchingProjectAs(tNode: TNode, rawSelector: string): boolean {
This function went away with the recent code changes.

2018-03-01 10:53 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> + * @param rawSelectors A collection of CSS selectors in the raw, un-parsed form
Renamed to `textSelectors`

2018-03-01 11:00 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> + * @param rawSelectors A collection of CSS selectors in the raw, un-parsed form
@mhevery documented here: https://github.com/angular/angular/pull/22498/files#diff-ce885db4223480bd4f7b78bd22b6f058R1284

2018-03-01 11:01 UTC, pkozlowski-opensource commented
@mhevery @vicb all the comments addressed, please have another look.

2018-03-01 17:56 UTC, mhevery approved these changes

2018-03-01 18:04 UTC, vicb commented on packages/core/src/render3/node_selector_matcher.ts
> +    if (ngProjectAsAttrIdx > -1) {
this is still wrong see my previous comment.
Also please create a github issue to move the ngProjectAs attr first.

2018-03-01 18:06 UTC, vicb commented on packages/core/src/render3/node_selector_matcher.ts
> +        ngProjectAsAttrVal === null && isNodeMatchingSelector(tNode, selectors[i])) {
nit: Wouldn't `ngProjectAsAttrVal  && ngProjectAsAttrVal === textSelectors[i] || isNodeMatchingSelector(tNode, selectors[i])` make more sense ? (with the same behavior)

2018-03-01 18:36 UTC, vicb commented on packages/core/src/render3/node_selector_matcher.ts
> +        ngProjectAsAttrVal === null && isNodeMatchingSelector(tNode, selectors[i])) {
that's actually wrong !
current impl is fine.

2018-03-01 19:15 UTC, vicb commented on packages/core/test/render3/node_selector_matcher_spec.ts
> +  describe('getProjectAsAttrValue', function() {
nit `describe('reading the ngProjectAs attribute value' => ...`
b/c function names change.

2018-03-01 19:15 UTC, vicb approved these changes
1 nit on the test name

2018-03-01 20:36 UTC, JoostK commented
Would it be possible to let the template compiler recognize the ngProjectAs attribute and have it perform the CSS compilation that is then stored on `TNode`, such that we may compare by compiled selector instead? That would save the need to have a duplicate representation at runtime and would also normalize for whitespace differences etc.

2018-03-01 20:42 UTC, pkozlowski-opensource commented
@JoostK it would be certainly possible but would have drawbacks:
* we would have to allocate a field for `ngProjectAs` on every `TNode` and this would be wasteful (memory-wise), especially that `ngProjectAs` is super-rare
* comparing compiled version of CSS selectors would be much more expensive that just comparing strings.

I'm _sure_ that there are ways of improving solution from this PR but I've considered what you are suggesting and decided against it for the reasons outlined above. But definitively, feel free to send follow-up PR(s) when this one lands, if you've got ideas for a better solution!

2018-03-06 14:56 UTC, closed without merging