chore: partial revert of #22263
angular/angular pull request #22527
Opened 2018-03-01 15:30 UTC by CaerusKaru

* Partially reverts #22263 due to lack of total spec complicance
  on the server
* Maintains the camel-case styles fix

2018-03-01 15:31 UTC, CaerusKaru commented
@vikerman @alexeagle

2018-03-01 21:18 UTC, vicb commented
1) What was the issue ? (could you please create a GH issue and link it from the test)
2) could you please rephrase the commit message:
```
fix(platform-server): <what does this fix ?>

partial revert of #22263
```

2018-03-01 21:22 UTC, vicb commented on packages/platform-server/src/domino_adapter.ts
> +      const styleList = styleAttribute.split(/;+/g);
nit: what about `/[\s;]+/g` here ?

2018-03-01 21:26 UTC, vicb commented on packages/platform-server/src/domino_adapter.ts
> +      const styleList = styleAttribute.split(/;+/g);
oh would not work either so maybe 
1- split on `/;+/g`
2- `trim()` the parts
3- ignore empty parts

2018-03-01 21:33 UTC, CaerusKaru commented on packages/platform-server/src/domino_adapter.ts
> +      const styleList = styleAttribute.split(/;+/g);
I changed the logic, let me know if that's what you had in mind

2018-03-01 21:33 UTC, CaerusKaru commented
@vicb changed commit message and opened a new issue

2018-03-14 14:46 UTC, agustinhaller commented
@vicb any updates on merging this PR?

2018-03-14 19:29 UTC, vicb commented on packages/platform-server/src/domino_adapter.ts
> +        if (styleList[i].length > 0) {
`trim`ing before checking the length would probably make more sense ?

2018-03-14 19:29 UTC, vicb commented on packages/platform-server/src/domino_adapter.ts
> +          const colon = style.indexOf(':');
nit colon -> colonIndex

2018-03-14 19:30 UTC, vicb commented on packages/platform-server/src/domino_adapter.ts
> +          (styleMap as any)[style.substr(0, colon).trim()] = style.substr(colon + 1).trim();
nit: extract `const name = style.substr(0, colon).trim();`

2018-03-14 19:32 UTC, vicb commented on packages/platform-server/src/domino_adapter.ts
> +    const styleMap = {};
`const styleMap: {[name: string]: string} = {}` and then remove un-needed "as any"

2018-03-14 19:32 UTC, vicb commented on packages/platform-server/src/domino_adapter.ts
> +  _readStyleAttribute(element: any) {
add return type

2018-03-14 19:33 UTC, vicb commented on packages/platform-server/src/domino_adapter.ts
> +          (styleMap as any)[style.substr(0, colon).trim()] = style.substr(colon + 1).trim();
there should be `as any` needed here

2018-03-14 19:34 UTC, vicb commented on packages/platform-server/src/domino_adapter.ts
> +    (styleMap as any)[styleName] = styleValue;
no need for any if types are specified upstream

2018-03-14 19:34 UTC, vicb commented on packages/platform-server/src/domino_adapter.ts
> +    return styleMap.hasOwnProperty(styleName) ? (styleMap as any)[styleName] : '';
no need for as any

2018-03-14 19:34 UTC, vicb requested changes
a few nits but LGTM otherwise.
Thanks  and sorry for the delay in reviewing

2018-03-14 19:35 UTC, vicb commented
- Typo in the commit message (complicance)
- Was is the target: master and/or patch

2018-03-14 20:07 UTC, CaerusKaru commented on packages/platform-server/src/domino_adapter.ts
> +    const styleMap = {};
Fixed

2018-03-14 20:07 UTC, CaerusKaru commented on packages/platform-server/src/domino_adapter.ts
> +          (styleMap as any)[style.substr(0, colon).trim()] = style.substr(colon + 1).trim();
Fixed

2018-03-14 20:07 UTC, CaerusKaru commented on packages/platform-server/src/domino_adapter.ts
> +          const colon = style.indexOf(':');
Fixed

2018-03-14 20:08 UTC, CaerusKaru commented on packages/platform-server/src/domino_adapter.ts
> +        if (styleList[i].length > 0) {
Fixed

2018-03-14 20:08 UTC, CaerusKaru commented on packages/platform-server/src/domino_adapter.ts
> +  _readStyleAttribute(element: any) {
Fixed

2018-03-14 20:09 UTC, CaerusKaru commented on packages/platform-server/src/domino_adapter.ts
> +    (styleMap as any)[styleName] = styleValue;
Fixed

2018-03-14 20:09 UTC, CaerusKaru commented on packages/platform-server/src/domino_adapter.ts
> +    return styleMap.hasOwnProperty(styleName) ? (styleMap as any)[styleName] : '';
Fixed

2018-03-14 20:10 UTC, CaerusKaru commented
Should be `PR target: master & patch`

2018-03-14 20:14 UTC, vicb commented on packages/platform-server/src/domino_adapter.ts
> +    styleMap[styleName] = styleValue + '';
do we really want `"undefined"` as a possible value ?

2018-03-14 20:15 UTC, vicb commented on packages/platform-server/src/domino_adapter.ts
> +    return styleMap.hasOwnProperty(styleName) ? styleMap[styleName] : '';
`return styleMap[styleName] || '';` ?

2018-03-14 20:17 UTC, CaerusKaru commented on packages/platform-server/src/domino_adapter.ts
> +    styleMap[styleName] = styleValue + '';
Fixed

2018-03-14 20:17 UTC, CaerusKaru commented on packages/platform-server/src/domino_adapter.ts
> +    return styleMap.hasOwnProperty(styleName) ? styleMap[styleName] : '';
Fixed

2018-03-14 20:27 UTC, vicb approved these changes
Thanks for the updates !

2018-03-14 20:29 UTC, vicb commented
g3 status: tap/189074679 
Thanks @kara

2018-03-14 20:38 UTC, vikerman approved these changes

2018-03-14 21:13 UTC, closed without merging