fix(aio): reposition and simplify github links
angular/angular pull request #22565
Opened 2018-03-02 23:33 UTC by petebacondarwin

Closes #22379

2018-03-02 23:43 UTC, mary-poppins commented
You can preview 536a565 at https://pr22565-536a565.ngbuilds.io/.

2018-03-03 00:13 UTC, petebacondarwin commented
I tried to fix the here for the "suggest edits" but it doesn't appear to have worked. I'll fix over the weekend.

2018-03-03 09:37 UTC, mary-poppins commented
You can preview 908d42e at https://pr22565-908d42e.ngbuilds.io/.

2018-03-03 09:59 UTC, mary-poppins commented
You can preview 87c7dec at https://pr22565-87c7dec.ngbuilds.io/.

2018-03-03 15:12 UTC, gkalpak reviewed
Have we considered using icon only buttons (no border, no background)? I think I would like the better.
(cc @sjtrimble).

2018-03-03 15:12 UTC, gkalpak commented on aio/tools/transforms/templates/api/lib/githubLinks.html
> +https://github.com/{$ versionInfo.gitRepoInfo.owner $}/{$ versionInfo.gitRepoInfo.repo $}/edit/master/packages/{$ doc.fileInfo.realProjectRelativePath $}?message=docs(API%20Reference)%3A%20describe%2
Couldn't we extract the package name from `doc.fileInfo.realProjectRelativePath` and use it in the message (`docs(<package-name>): ...`)?

2018-03-03 20:32 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/lib/githubLinks.html
> +https://github.com/{$ versionInfo.gitRepoInfo.owner $}/{$ versionInfo.gitRepoInfo.repo $}/edit/master/packages/{$ doc.fileInfo.realProjectRelativePath $}?message=docs(API%20Reference)%3A%20describe%2
Actually we can use `doc.moduleDoc.name` I believe

2018-03-03 20:42 UTC, petebacondarwin commented
> Have we considered using icon only buttons (no border, no background)? I think I would like the better.

Here are screenshots of what this might look like. I am not convinced by them. I think the background (making them look more like buttons) makes it clearer that you can click on them.

<img width="808" alt="screen shot 2018-03-03 at 20 41 37" src="https://user-images.githubusercontent.com/15655/36939085-6c2c0572-1f23-11e8-8fb5-8b1707e37a58.png">
<img width="807" alt="screen shot 2018-03-03 at 20 41 20" src="https://user-images.githubusercontent.com/15655/36939086-6c558fc8-1f23-11e8-944e-0baff516084b.png">
<img width="833" alt="screen shot 2018-03-03 at 20 41 10" src="https://user-images.githubusercontent.com/15655/36939087-6c6f82c0-1f23-11e8-812b-1d78f835b515.png">

2018-03-03 20:44 UTC, petebacondarwin commented
Other than the background to the links, I have addressed the other comments @gkalpak PTAL

2018-03-03 20:54 UTC, mary-poppins commented
You can preview 223008d at https://pr22565-223008d.ngbuilds.io/.

2018-03-04 13:16 UTC, gkalpak requested changes

2018-03-04 13:16 UTC, gkalpak commented on aio/tools/transforms/templates/api/lib/githubLinks.html
> +https://github.com/{$ versionInfo.gitRepoInfo.owner $}/{$ versionInfo.gitRepoInfo.repo $}/edit/master/packages/{$ doc.fileInfo.realProjectRelativePath $}?message=docs({$ doc.moduleDoc.id | escape $})
1. Using `moduleDoc.id` doesn't always give the corrct scope. E.g. for stuff in [HttpBackend][1] is give `common/http` instead of `common`. We need to ignore stuff after `/` (if one exists).

2. By always poitning to master, there is the risk that the content on master is different than the version they are viewing. I am fine with that, just pointing it out in case someone has a clever idea to improve this.

[1]: https://pr22565-223008d.ngbuilds.io/api/common/http/HttpBackend

2018-03-04 13:16 UTC, gkalpak commented on aio/tools/transforms/templates/api/base.template.html
> +    <div class="breadcrumb">
Indentation still funky 😛

2018-03-04 20:13 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/lib/githubLinks.html
> +https://github.com/{$ versionInfo.gitRepoInfo.owner $}/{$ versionInfo.gitRepoInfo.repo $}/edit/master/packages/{$ doc.fileInfo.realProjectRelativePath $}?message=docs({$ doc.moduleDoc.id | escape $})
I never realised that the scope is not actually the barrel! I can fix that.

2018-03-04 20:25 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/base.template.html
> +    <div class="breadcrumb">
Gotcha!

2018-03-04 20:32 UTC, petebacondarwin commented
I can live with no-background buttons, by adding the background when you hover over them, which is what happens at https://material.angular.io/components/button/examples

PTAL

2018-03-05 10:13 UTC, gkalpak commented
The Travis failures seem legit.

2018-03-05 12:23 UTC, mary-poppins commented
You can preview 72591a2 at https://pr22565-72591a2.ngbuilds.io/.

2018-03-05 13:40 UTC, petebacondarwin commented
Travis is now green @gkalpak PTAL

2018-03-05 13:42 UTC, gkalpak approved these changes

2018-03-05 18:15 UTC, closed without merging