refactor: tree-shakeable providers API updates
angular/angular pull request #22655
Opened 2018-03-08 16:20 UTC by alxhub

Rename @Injectable({scope -> providedTo}).

Instead of {providedTo: APP_ROOT_SCOPE}, accept {providedTo: 'root'}.
Also, {providedTo: null} implies the injectable should not be added
to any scope.

2018-03-08 16:28 UTC, mary-poppins commented
You can preview 679fee0 at https://pr22655-679fee0.ngbuilds.io/.

2018-03-08 18:07 UTC, mary-poppins commented
You can preview ae6e61c at https://pr22655-ae6e61c.ngbuilds.io/.

2018-03-08 23:15 UTC, mary-poppins commented
You can preview 0210da8 at https://pr22655-0210da8.ngbuilds.io/.

2018-03-08 23:29 UTC, mary-poppins commented
You can preview 57d4702 at https://pr22655-57d4702.ngbuilds.io/.

2018-03-09 23:46 UTC, mary-poppins commented
You can preview 142c604 at https://pr22655-142c604.ngbuilds.io/.

2018-03-09 23:56 UTC, mary-poppins commented
You can preview 4bbb8b3 at https://pr22655-4bbb8b3.ngbuilds.io/.

2018-03-12 16:14 UTC, mary-poppins commented
You can preview 76207e5 at https://pr22655-76207e5.ngbuilds.io/.

2018-03-12 17:17 UTC, mary-poppins commented
You can preview 5d277a6 at https://pr22655-5d277a6.ngbuilds.io/.

2018-03-12 20:16 UTC, mary-poppins commented
You can preview af9c32f at https://pr22655-af9c32f.ngbuilds.io/.

2018-03-12 21:56 UTC, chuckjaz approved these changes

2018-03-12 21:56 UTC, chuckjaz commented on packages/compiler/src/core.ts
> +  providedIn?: Type|any;
Consider adding `|'root'`. Since it is `any` it is not necessary but it would be more clear that `'root'` is special.

2018-03-12 22:00 UTC, alxhub commented on packages/compiler/src/core.ts
> +  providedIn?: Type|any;
Done.

2018-03-12 22:08 UTC, mary-poppins commented
You can preview 5cd6b0c at https://pr22655-5cd6b0c.ngbuilds.io/.

2018-03-12 22:10 UTC, mary-poppins commented
You can preview 1649970 at https://pr22655-1649970.ngbuilds.io/.

2018-03-12 22:28 UTC, mary-poppins commented
You can preview 227e098 at https://pr22655-227e098.ngbuilds.io/.

2018-03-12 22:31 UTC, mary-poppins commented
You can preview 663f1dc at https://pr22655-663f1dc.ngbuilds.io/.

2018-03-12 23:44 UTC, mhevery requested changes

2018-03-12 23:44 UTC, mhevery commented on packages/platform-browser/src/browser.ts
> +    {provide: APP_ROOT, useValue: true},
Is there another way to mark a module as root without relying on `APP_ROOT`? I think the design would be nicer if this line would not exist.

We could test if we are root if:
- There is no parent
- The parent injector is NULL_INJECTOR
- The parent injector is PlatformRef injector?

Alternatively we could have the boostrap method call createModule with some extra argument to designate that it should be root injector.

2018-03-12 23:44 UTC, mhevery commented on packages/core/src/view/ng_module.ts
> +    if (provider.token === APP_ROOT) {
Is there another way to mark a module as root without relying on `APP_ROOT`? 

We could have the boostrap method call createModule with some extra argument to designate that it should be root injector.

2018-03-12 23:44 UTC, mhevery commented on packages/core/src/di/scope.ts
> +export const APP_ROOT = new InjectionToken<boolean>(
I would like to get rid of `APP_ROOT`. It is not public, but it sort of is since platform-browser has a special relationship with it. Which means that platform-browser is special and only it can create root injectors.

2018-03-12 23:56 UTC, alxhub commented on packages/platform-browser/src/browser.ts
> +    {provide: APP_ROOT, useValue: true},
This is an internal implementation detail only (`APP_ROOT` is not exposed to the user), so yes, we could have a different way of detecting it.

This current setup does have an advantage - because `APP_ROOT` is tied to `BrowserModule` in the existing system, it guarantees that the application-level services which Angular provides are in the "root scope" injector as well. This isn't necessarily the case if the user gets creative with injector structures.

2018-03-12 23:56 UTC, alxhub commented on packages/core/src/view/ng_module.ts
> +    if (provider.token === APP_ROOT) {
Answered above.

2018-03-12 23:57 UTC, alxhub commented on packages/core/src/di/scope.ts
> +export const APP_ROOT = new InjectionToken<boolean>(
I think this should be a separate discussion and should not block this PR which is blocking 6.0 RC. Since it is internal we can change the behavior before 6.0 final.

2018-03-13 03:51 UTC, mhevery approved these changes

2018-03-13 16:29 UTC, closed without merging