docs(aio): add Material Community Components
angular/angular pull request #22660
Opened 2018-03-08 19:04 UTC by tiaguinho

@StephenFluin can you check this?

2018-03-09 16:37 UTC, StephenFluin approved these changes
From a content perspective this looks good. Not sure why CircleCI is failing though, so we need to figure that out.

2018-03-09 18:18 UTC, kara commented
@StephenFluin The failure is unrelated to this PR. It was a rebase error that is now fixed in master

2018-03-14 10:54 UTC, tiaguinho commented
Thanks, @kara.
Is everything alright then?

2018-05-04 12:03 UTC, tiaguinho commented
@StephenFluin, do you think I need to do some change on this PR?

2018-05-09 15:33 UTC, StephenFluin commented
It looks like you added another commit. We'll need to squash / remove that before we can merge.

2018-05-09 15:44 UTC, tiaguinho commented
Hi @StephenFluins sorry for that. I think it's correct now.

2018-05-09 18:52 UTC, StephenFluin requested changes
One tiny problem still, can you add back the newline at the end of the file so there isn't the extra change?

2018-05-09 22:08 UTC, tiaguinho commented
Just add the line. Can I do anything more to help?

2018-05-10 17:03 UTC, gkalpak commented
@tiaguinho, you just need to squash the commits and we're good to go :grin:

2018-05-11 08:53 UTC, tiaguinho commented
@gkalpak I think we good to go now... 😃

2018-05-11 09:33 UTC, gkalpak commented on aio/content/marketing/resources.json
> +
Where did this come from? can you remove it please :grin:

2018-05-21 21:19 UTC, closed without merging