build(aio): demo of RxJS API docs
angular/angular pull request #22677
Opened 2018-03-09 12:25 UTC by petebacondarwin

This is a PoC of how the angular.io app and infrastructure could be repurposed to generate API docs for the RxJS code base.

If you want to run this locally then do the following:

```bash
git clone --branch rxjs-docs https://github.com/petebacondarwin/angular
cd angular/aio
yarn setup
yarn start
```

Then browse to `http://localhost:4200/api`

-------

### Notes

* The configuration of the doc-gen is all inside `aio/tools/transforms`. It uses a tool called [Dgeni](https://github.com/angular/dgeni) which is configured via packages. Some packages can be found in the `transforms` folder and other more general ones are imported from [Dgeni Packages](https://github.com/angular/dgeni-packages).
* `yarn setup` will run the subcommand `yarn get-rxjs-docs` which will shallow clone the rxjs repository into the `aio/content/rxjs`.
* I had to turn off certain checks due to invalid links or missing images.

2018-03-09 12:31 UTC, mary-poppins commented
You can preview d591321 at https://pr22677-d591321.ngbuilds.io/.

2018-03-09 12:32 UTC, petebacondarwin commented
Here are some screenshots if you can't wait for the online preview:

<img width="1300" alt="screen shot 2018-03-09 at 12 30 40" src="https://user-images.githubusercontent.com/15655/37207629-c03ed7cc-2395-11e8-974d-e538f231ecce.png">
<img width="1304" alt="screen shot 2018-03-09 at 12 30 05" src="https://user-images.githubusercontent.com/15655/37207630-c05d6df4-2395-11e8-8efa-c25c10a6b51d.png">
<img width="1306" alt="screen shot 2018-03-09 at 12 29 38" src="https://user-images.githubusercontent.com/15655/37207631-c07b5922-2395-11e8-9bb9-0c07ce1860f6.png">
<img width="1268" alt="screen shot 2018-03-09 at 12 29 19" src="https://user-images.githubusercontent.com/15655/37207632-c09c1cb6-2395-11e8-9969-0645daa63c92.png">
<img width="1072" alt="screen shot 2018-03-09 at 12 29 07" src="https://user-images.githubusercontent.com/15655/37207633-c0b5dc96-2395-11e8-9a43-cef5c25b4cdd.png">
<img width="1112" alt="screen shot 2018-03-09 at 12 29 00" src="https://user-images.githubusercontent.com/15655/37207634-c0cd6438-2395-11e8-89b0-321a08b736cf.png">

2018-03-09 12:50 UTC, DiedrikDM commented
Just to clarify: things I'll focus on: make the documentation generated for all of the rxjs operators look more closely aligned with the new rxjs-docs (content wise).

2018-03-09 12:53 UTC, DiedrikDM commented
BTW: @petebacondarwin  this already really looks cool/awesome/other superlative! Thanks for the work!

2018-03-09 15:14 UTC, JWO719 commented
Wow this is absolutely amazing. Thanks for the support. I will take a closer look soon.

2018-03-09 16:57 UTC, sumitarora commented
Awesome Looks really good :D

2018-03-09 17:08 UTC, ashwin-sureshkumar commented
@@petebacondarwin - This is amazing. Great work !

2018-03-09 18:44 UTC, IgorMinar requested changes
Just to be clear, this is just a demo to show how the current documentation infrastructure could be used to generate docs for rxjs. We have no intentions to actually pull rxjs docs into angular.io docs.

2018-03-09 19:01 UTC, benlesh commented
Thank you SO much for this proof of concept, Pete! I really hope the RxJS docs team can take this example and run with it. I'm curious how you'd manage versions.

2018-03-10 21:00 UTC, btroncone commented
Looks amazing! 👍🏻

2018-03-23 07:40 UTC, petebacondarwin commented
Closing as @ashwin-sureshkumar is working on a version within the RxJS project.

2018-04-05 16:38 UTC, closed without merging