fix(ivy): elements properties should not be stringified
angular/angular pull request #22683
Opened 2018-03-09 17:31 UTC by marclaval

This PR fixes a regression introduced by #22540

2018-03-09 19:21 UTC, mhevery requested changes

2018-03-09 19:21 UTC, mhevery commented on packages/core/test/render3/instructions_spec.ts
> +      expect((t.hostNode.native as HTMLElement).querySelector('div') !.hidden).toEqual(false);
Wouldn't this allow someone to create `{toString:() => 'evel text'} and bypass sanitization? 
Or is your argument that user can't do that only bad programing practice?
Or maybe we just skip sanatiazation for primitives and sanitizae evrything else?

2018-03-09 19:21 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +    value = typeof value == 'string' && sanitizer != null ? (sanitizer(value) as any) : value;
I would feel better if the check was `typeof value !== 'number' && typeof value !== 'boolean'` since we need to guard against `{toString: () => 'evil text'} `

2018-03-12 17:13 UTC, marclaval commented
Updated with the assumption that the compiler will only "inject" the sanitizer for properties that are not safe, PTAL

2018-03-12 19:01 UTC, mhevery approved these changes

2018-03-12 20:17 UTC, closed without merging