docs(aio): refactor pipe example to use the HttpClient
angular/angular pull request #22741
Opened 2018-03-13 16:45 UTC by danielsogl

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Actually the pipes example is using the deprecated HttpModule.

## What is the new behavior?
Refactored the example to use the new HttpClient

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-03-14 02:21 UTC, trotyl commented
Partially covered by #22727

2018-07-05 15:07 UTC, brandonroberts commented
@danielsogl will you rebase on master and remove `(aio)` from the git commit message?

2018-07-05 15:35 UTC, danielsogl commented
@brandonroberts Done!

2018-07-05 18:05 UTC, brandonroberts commented
Update the commit message to start with `docs: ...`

2018-07-05 19:34 UTC, danielsogl commented
@brandonroberts fixed

2018-07-11 13:32 UTC, brandonroberts submitted a review, later dismissed

2018-07-11 13:37 UTC, brandonroberts commented
@danielsogl can you rebase this branch on master? Some of these changes have already landed in master

2018-07-18 14:15 UTC, brandonroberts commented
@danielsogl something went off track with your rebase. Will you rebase on master again?

2018-07-20 02:52 UTC, brandonroberts requested changes
There are still some changes outside the `aio` folder that need to be reverted.

2018-07-20 02:52 UTC, brandonroberts commented on aio/content/examples/pipes/src/app/app.module.ts
> +import { HttpClientModule } from '@angular/common/http';
An `HttpClientModule` import already exists

2018-07-20 02:52 UTC, brandonroberts commented on aio/content/examples/pipes/src/app/app.module.ts
> -import { BrowserModule } from '@angular/platform-browser';
This should not be removed

2018-07-20 02:52 UTC, brandonroberts commented on aio/content/examples/pipes/src/app/fetch-json.pipe.ts
> +import { HttpClient } from '@angular/common/http';
The `from` statements should be lined up. This is intentional.

2018-07-25 05:53 UTC, danielsogl commented
@brandonroberts rebased on master again

2018-07-25 08:55 UTC, gkalpak requested changes

2018-07-25 08:55 UTC, gkalpak commented on aio/content/examples/pipes/src/app/app.module.ts
> +export class AppModule {}
Please don't remove the spaces (here and above) for consistency.
(I don't like them either, but it is preferrable to remain consistent across examples and most examples use them.)

2018-07-25 08:55 UTC, gkalpak commented on aio/content/examples/pipes/src/app/fetch-json.pipe.ts
> +  constructor(private http: HttpClient) {}
Keep the space.

2018-07-25 08:55 UTC, gkalpak commented on aio/content/examples/pipes/src/app/fetch-json.pipe.ts
> +      this.http.get(url).subscribe(result => (this.cachedData = result));
Why the parens?

2018-07-25 08:55 UTC, gkalpak commented on aio/content/guide/architecture-components.md
> +* `providers`: An array of **dependency injection providers** for services that the component requires. In the example, this tells Angular how provide the `HeroService` instance that the component's
Revert.

2018-07-25 08:55 UTC, gkalpak commented on modules/benchmarks/src/tree/render3/tree.ts
> +        C(4);
These changes seem irrelevant :grin:
(Probably a rebase gone bad.)

2018-07-25 10:13 UTC, danielsogl commented
@gkalpak yes I failed with the rebase. Now it should be fine

2018-07-25 10:40 UTC, gkalpak approved these changes
Looks great :smiley: Thx! 👍 
(Leaving it to @brandonroberts to give the final LGTM - assuming CI is green 🤔)

2018-07-27 17:06 UTC, brandonroberts approved these changes

2018-07-30 21:28 UTC, closed without merging