WIP: Ivy hello world
angular/angular pull request #22788
Opened 2018-03-15 04:32 UTC by mhevery

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2018-03-18 17:30 UTC, kara approved these changes
LGTM aside from typo

2018-03-18 17:30 UTC, kara commented on packages/core/test/bundling/hello_world/index.ts
> +//TODO(misko): Forgeting to export HellWorld and not having NgModule fails silently.
Typos: Forgeting -> Forgetting, HellWorld -> HelloWorld

2018-03-18 18:39 UTC, mhevery commented on packages/core/test/bundling/hello_world/index.ts
> +//TODO(misko): Forgeting to export HellWorld and not having NgModule fails silently.
fixed

2018-03-18 22:43 UTC, vicb commented on WORKSPACE
> +    url = "https://github.com/mhevery/rules_nodejs/archive/07c2cf1f04fa7b68220d730bc8df37ee9811b5e8.zip",
Why do you point to your repo here ?
Add comment with tracking issue.

2018-03-18 22:44 UTC, vicb commented on packages/core/src/render3/assert.ts
> +export function assertComponentType(actual: any) {
other `assert`s have a `msg` parameter ? Would it make sense here ?

2018-03-18 22:45 UTC, vicb commented on packages/core/src/render3/component.ts
> +        Type<T>/* Type as workaround for: Microsoft/TypeScript/issues/4881 */
Should this be a `TODO...`

2018-03-18 22:46 UTC, vicb commented on packages/core/src/render3/component.ts
>      // Create directive instance with n() and store at index 1 in data array (el is 0)
look like this comment is a little out of sync with the code now  ?

2018-03-18 22:49 UTC, vicb commented on packages/core/test/bundling/hello_world/index.ts
> +// TODO(misko): Forgetting to export HelloWorld and not having NgModule fails silently.
tracking issue ?

2018-03-18 22:51 UTC, vicb commented on tools/symbol-extractor/symbol_extractor.ts
> +          fnRecurseDepth++;
don't you ever need to `--` ?

2018-03-18 22:53 UTC, vicb commented on tools/symbol-extractor/symbol_extractor.ts
> +function isStoringIIFE(child: ts.VariableDeclarationList): boolean {
`isRollupExportSymbol()` as it seems super specific to this use case ?

2018-03-18 22:53 UTC, vicb commented on tools/symbol-extractor/symbol_extractor.ts
> +    return true;
nit: `return decl.initializer && decl.initializer.kind == ts.SyntaxKind.CallExpression;`

2018-03-18 22:55 UTC, vicb commented on tools/symbol-extractor/symbol_extractor_spec/iife_with_export.js
> +var fooBar = function(exports) {
Add a comment what this test is about (ie rollup export) ?

2018-03-18 22:56 UTC, vicb requested changes
Changes mostly LGTM.
I'd like to see more comments.

2018-03-19 17:50 UTC, mhevery commented on WORKSPACE
> +    url = "https://github.com/mhevery/rules_nodejs/archive/07c2cf1f04fa7b68220d730bc8df37ee9811b5e8.zip",
That was a temporary work around until https://github.com/bazelbuild/rules_nodejs/pull/158 got merged. It now points back to the main repo.

2018-03-19 17:51 UTC, mhevery commented on packages/core/src/render3/assert.ts
> +export function assertComponentType(actual: any) {
What would the message say other than `Expecting ComponentType but got something else.`

2018-03-19 17:53 UTC, mhevery commented on packages/core/test/bundling/hello_world/index.ts
> +// TODO(misko): Forgetting to export HelloWorld and not having NgModule fails silently.
I will be working on Ivy backlog and this will be included there. Don't have issue # yet.

2018-03-19 17:54 UTC, mhevery commented on packages/core/src/render3/component.ts
>      // Create directive instance with n() and store at index 1 in data array (el is 0)
fixed

2018-03-19 17:54 UTC, mhevery commented on packages/core/src/render3/component.ts
> +        Type<T>/* Type as workaround for: Microsoft/TypeScript/issues/4881 */
I don' think so. These are all over the code base, and there will have to be big clean up once that is resolved.

2018-03-19 17:55 UTC, mhevery commented on tools/symbol-extractor/symbol_extractor.ts
> +          fnRecurseDepth++;
good catch, added.

2018-03-19 17:56 UTC, mhevery commented on tools/symbol-extractor/symbol_extractor.ts
> +function isStoringIIFE(child: ts.VariableDeclarationList): boolean {
changed.

2018-03-19 21:08 UTC, mhevery commented on tools/symbol-extractor/symbol_extractor.ts
> +    return true;
fixed

2018-03-19 21:08 UTC, mhevery commented on tools/symbol-extractor/symbol_extractor_spec/iife_with_export.js
> +var fooBar = function(exports) {
added

2018-03-19 21:11 UTC, vicb commented on tools/symbol-extractor/symbol_extractor.ts
> +  return (decl.initializer && decl.initializer.kind == ts.SyntaxKind.CallExpression);
needs `!!` for `boolean` return type

2018-03-19 21:13 UTC, vicb commented on packages/core/src/render3/assert.ts
> +export function assertComponentType(actual: any) {
It could be `msg || "Expecting ComponentType but got something else"` and the callee could describe why there should be a component at that point. Would be consistent

2018-03-19 21:14 UTC, vicb commented on packages/core/src/render3/component.ts
> +        Type<T>/* Type as workaround for: Microsoft/TypeScript/issues/4881 */
Should `ComponentType` be an union type with a TODO then ?

2018-03-19 21:14 UTC, vicb commented on tools/symbol-extractor/symbol_extractor.ts
> +          fnRecurseDepth++;
do we need the test to be updated ?

2018-03-19 21:16 UTC, mhevery commented on tools/symbol-extractor/symbol_extractor.ts
> +  return (decl.initializer && decl.initializer.kind == ts.SyntaxKind.CallExpression);
argh! Fixed.

2018-03-19 21:41 UTC, mhevery commented on packages/core/src/render3/assert.ts
> +export function assertComponentType(actual: any) {
fixed

2018-03-19 21:42 UTC, mhevery commented on packages/core/src/render3/component.ts
> +        Type<T>/* Type as workaround for: Microsoft/TypeScript/issues/4881 */
No, because then it would apply to all cases and we would lose type safety internally. We really just want it on the user code Ivy boundary.

2018-03-19 21:43 UTC, mhevery commented on tools/symbol-extractor/symbol_extractor.ts
> +          fnRecurseDepth++;
For this to fail, we would have to have more than one top level closure, which does not happen in real life. Not sure that would be useful, what do you think.

2018-03-19 21:45 UTC, vicb commented on packages/core/src/render3/component.ts
> +        Type<T>/* Type as workaround for: Microsoft/TypeScript/issues/4881 */
Like a `FromUserComponentType` ?

2018-03-19 21:46 UTC, vicb commented on tools/symbol-extractor/symbol_extractor.ts
> +          fnRecurseDepth++;
I would update the test but it's up to you.

2018-03-19 21:47 UTC, vicb approved these changes
Thanks for the updates.

2018-03-19 23:01 UTC, closed without merging