[WIP]: Tree-shakable providers documentation
angular/angular pull request #22803
Opened 2018-03-15 17:35 UTC by chembu

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

No docs existing for new-feature tree-shakable providers.
Issue Number: N/A

## What is the new behavior?
Added tree-shakable provider documentation with a recommendation to use it as the default method.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-03-15 17:46 UTC, mary-poppins commented
You can preview 7b6b0a7 at https://pr22803-7b6b0a7.ngbuilds.io/.

2018-03-16 16:25 UTC, mary-poppins commented
You can preview 10ada60 at https://pr22803-10ada60.ngbuilds.io/.

2018-03-16 19:57 UTC, chembu commented
@jenniferfell , @alxhub : Take a look at the tree-shakable providers doc for V6.

2018-03-18 15:19 UTC, mary-poppins commented
You can preview 1bd449e at https://pr22803-1bd449e.ngbuilds.io/.

2018-03-19 02:33 UTC, trotyl commented
Should be able to close #21913 as well

2018-03-21 09:31 UTC, jenniferfell requested changes
Partial review complete

2018-03-21 09:31 UTC, jenniferfell commented on aio/content/guide/styleguide.md
> +**Do** provide services with the app root injector in the `@Injectable` decorator of the service.
Trying to resolve the plural - singular shift. Maybe "Do provide a service with the app root injector in the @Injectable decorator of the service" ?

2018-03-21 09:31 UTC, jenniferfell commented on aio/content/guide/styleguide.md
> +that instance is shared and available in every class that needs the service. And provding it in the `@Injectable` decorator allows Angular compiler to perform tree-shaking on services that are not us
Recommend: "...that instance of the service is shared.."

2018-03-21 09:31 UTC, jenniferfell commented on aio/content/guide/styleguide.md
> +that instance is shared and available in every class that needs the service. And provding it in the `@Injectable` decorator allows Angular compiler to perform tree-shaking on services that are not us
Last sentence could use some editing. 
- Rewrite to not start sentence with And
- Providing is missing an i
- "It" could be more clear
- "an application"  ->  "the app"
Perhaps "Providing that instance of the service in the @Injectable decorator allows the Angular compiler to perform tree-shaking on services that are not used it the app."

2018-03-21 09:31 UTC, jenniferfell commented on aio/content/guide/providers.md
> +Assuming you already have a CLI generated app, create a service using the following CLI command (replace User with the name of your service) in the root project directory:
Editorial fine-tuning: 
- "If you have an app generated that was generated with the CLI..."
Or 
- "If you have a CLI-generated app, ..."

2018-03-21 09:31 UTC, jenniferfell commented on aio/content/guide/providers.md
> +Assuming you already have a CLI generated app, create a service using the following CLI command (replace User with the name of your service) in the root project directory:
I recommend pulling out the parenthetical. "...create a service using the following CLI command in the root project directory. Replace User with the name of your service."

2018-03-21 09:31 UTC, jenniferfell commented on aio/content/guide/providers.md
> +Assuming you already have a CLI generated app, create a service using the following CLI command (replace User with the name of your service) in the root project directory:
What if I don't have a CLI-generated app?

2018-03-21 21:25 UTC, mary-poppins commented
You can preview c7c0b67 at https://pr22803-c7c0b67.ngbuilds.io/.

2018-03-23 17:14 UTC, mary-poppins commented
You can preview 95a505f at https://pr22803-95a505f.ngbuilds.io/.

2018-03-23 17:58 UTC, alxhub commented on aio/content/guide/providers.md
> +@Injectable({
Example: user.service.0.ts

2018-03-23 17:58 UTC, alxhub commented on aio/content/guide/providers.md
> +@Injectable({
Example: user.service.1.ts

2018-03-23 17:58 UTC, alxhub commented on aio/content/guide/providers.md
> +
Example: user.module.ts

2018-03-23 17:58 UTC, alxhub commented on aio/content/guide/styleguide.md
> +<code-example>
Example: hero.service.ts

2018-03-26 20:53 UTC, alfaproject requested changes

2018-03-26 20:53 UTC, alfaproject commented on aio/content/guide/dependency-injection-in-action.md
> +From V6 onwards, providers for application-wide dependencues should be defined by specifying `providedIn: 'root'` on their `@Injectable()` decorator (in the case of services) or at `InjectionToken` c
dependencies*

2018-03-27 22:20 UTC, chembu commented
New PR: https://github.com/angular/angular/pull/23027

2018-03-27 23:13 UTC, jenniferfell commented
@alfaproject Thanks. Good catch!

2018-03-27 23:13 UTC, jenniferfell commented
Moved work to https://github.com/angular/angular/pull/23027

2018-03-27 23:13 UTC, closed without merging