docs: update text around changed obs examples
angular/angular pull request #22920
Opened 2018-03-21 23:36 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A
#22890

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
mostly cosmetic changes

2018-03-21 23:45 UTC, mary-poppins commented
You can preview d6628b0 at https://pr22920-d6628b0.ngbuilds.io/.

2018-03-23 17:36 UTC, jenniferfell requested changes

2018-03-23 17:36 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +Notice that `hero-list.component.ts` imports `Observable` and the `finally` operator, while `hero.service.ts` imports `Observable`, `of` and the `delay` operator from `rxjs`.
Minor: Google style uses Oxford comma. "...imports Observable, of, and the delay operator from rxjs."

2018-03-23 17:36 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +Notice that `hero-list.component.ts` imports `Observable` and the `finally` operator, while `hero.service.ts` imports `Observable`, `of` and the `delay` operator from `rxjs`.
Example: Please double-check. Looking at hero-list.component.ts, it looks like the import is "finalize" instead of "finally".

2018-03-23 17:43 UTC, jenniferfell commented
@IgorMinar @jasonaden I noticed that most changes are editorial. I just confirmed with @jbogarthyde. "The doc never described the code in enough detail to need alteration. The changes were mostly to how rxjs things are imported -- there was one very minor text change that resulted from that." (in reactive forms doc)

2018-03-23 18:09 UTC, mary-poppins commented
You can preview cdeeb1e at https://pr22920-cdeeb1e.ngbuilds.io/.

2018-03-23 18:11 UTC, jenniferfell approved these changes

2018-03-23 18:36 UTC, mary-poppins commented
You can preview 1fb1304 at https://pr22920-1fb1304.ngbuilds.io/.

2018-03-23 19:35 UTC, jenniferfell commented
@jbogarthyde Thanks for fixing those legacy issues by changing HeroService in text to match the HeroesService we see in the examples. (unrelated to rxjs changes)

@mhevery HTTP and Reactive Forms have content changes related to the examples and rxjs. Other files are just editorial to match style guide or how we refer to observables elsewhere. IMO this is ready to merge. Q: Do you want @jbogarthyde to merge the commits first? Thanks for stepping in!

2018-03-23 19:36 UTC, jenniferfell approved these changes

2018-03-26 17:29 UTC, jenniferfell commented
@mhevery @IgorMinar Hi. Can one of you approve, please...or let us know what we need to do/change before approval? Thanks!

2018-03-27 17:14 UTC, jenniferfell commented
@IgorMinar While you were away, Brad and @mhevery said you need to be the one to review and approve this. Thanks.

2018-03-29 16:15 UTC, IgorMinar approved these changes
looks good.

I'm a bit surprised that no bigger changes were necessary given all the changes that happened to the example code, but I'm not aware of any particular sections that still need an update.

2018-03-29 16:17 UTC, IgorMinar commented
caretaker note: I'm not sure why the circleCI jobs didn't fire on this PR, but the changes in this PR are docs only so it doesn't matter. If we do see other PRs with CI results missing we should investigate.

2018-03-29 16:21 UTC, closed without merging