DOCS Update tutorial to recommend tree-shakeable providers
angular/angular pull request #22934
Opened 2018-03-22 17:50 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Mentions best practice of providing at component level, but does not change the example to follow it.

2018-03-22 18:04 UTC, mary-poppins commented
You can preview 589955d at https://pr22934-589955d.ngbuilds.io/.

2018-03-22 19:01 UTC, mary-poppins commented
You can preview 2cf3585 at https://pr22934-2cf3585.ngbuilds.io/.

2018-03-22 19:04 UTC, mary-poppins commented
You can preview ff82b4a at https://pr22934-ff82b4a.ngbuilds.io/.

2018-03-22 19:05 UTC, vicb commented on aio/content/tutorial/toh-pt4.md
> +as you will do [below](#inject). A provider is something that can create or deliver a service; in this case, it instaniates the `HeroService` class to provide the service.
typo instantiates

2018-03-22 20:27 UTC, mary-poppins commented
You can preview ae03b63 at https://pr22934-ae03b63.ngbuilds.io/.

2018-03-31 00:05 UTC, mary-poppins commented
You can preview 6ee2e3b at https://pr22934-6ee2e3b.ngbuilds.io/.

2018-03-31 00:10 UTC, mary-poppins commented
You can preview a2e7817 at https://pr22934-a2e7817.ngbuilds.io/.

2018-04-02 15:21 UTC, chembu commented on aio/content/tutorial/toh-pt4.md
> +You can register the `HeroService` as the provider of this service at different levels:
By default, the Angular CLI command `ng generate service` registers a provider with the root injector for your service. When you provide it at the root level, Angular creates a single, shared instance of HeroService and injects into any class that asks for it. You can modify this and register your service at different levels (HeroesComponent, AppModule) based on your use case.

2018-04-02 15:21 UTC, chembu commented on aio/content/tutorial/toh-pt4.md
> +Since you did not, you'll have to provide it yourself.  A good practice is to provide it in the metadata for the service itself, which makes it available at a given level, but also allows for it to b
Remove: Since you did not, you'll have to provide it yourself.  A good practice is to provide it in the metadata for the service itself, which makes it available at a given level, but also allows for it to be removed from the app if it turns out not be used after all.

2018-04-02 15:21 UTC, chembu commented on aio/content/tutorial/toh-pt4.md
> +To do this, look for the `@Injectable()` statement right before the `HeroService` class definition, and add the `providedIn` metadata value.You typically provide a service at the root level, so that
Remove

2018-04-02 15:21 UTC, chembu commented on aio/content/tutorial/toh-pt4.md
> + When you provide it at the root level, Angular creates a single, shared instance of `HeroService`
Remove

2018-04-02 17:21 UTC, mary-poppins commented
You can preview c460a55 at https://pr22934-c460a55.ngbuilds.io/.

2018-04-02 19:53 UTC, mary-poppins commented
You can preview 5c614bc at https://pr22934-5c614bc.ngbuilds.io/.

2018-04-02 20:04 UTC, mary-poppins commented
You can preview 6efd5b0 at https://pr22934-6efd5b0.ngbuilds.io/.

2018-04-03 17:12 UTC, mary-poppins commented
You can preview 10b7f85 at https://pr22934-10b7f85.ngbuilds.io/.

2018-04-03 17:18 UTC, trotyl commented on aio/content/examples/toh-pt4/src/app/hero.service.2.ts
> +@Injectable({providedIn : root})
Missing quote for `root`?

2018-04-03 17:29 UTC, mary-poppins commented
You can preview e73e1d9 at https://pr22934-e73e1d9.ngbuilds.io/.

2018-04-03 17:35 UTC, mary-poppins commented
You can preview 80ffdbf at https://pr22934-80ffdbf.ngbuilds.io/.

2018-04-03 17:41 UTC, chembu commented on aio/content/tutorial/toh-pt4.md
>  When you provide a service at the root level, Angular creates a single, shared instance of `HeroService` and injects into any class that asks for it.
You can remove line 105. We are already mentioning this in the paragraph above.

2018-04-03 17:55 UTC, alxhub submitted a review, later dismissed

2018-04-03 17:55 UTC, alxhub commented on aio/content/tutorial/toh-pt4.md
> +* You registered the `HeroService` as the _provider_ of its service as the root level, so that it can be injected anywhere in the app.
> at the root level

2018-04-03 17:55 UTC, alxhub commented on aio/content/tutorial/toh-pt4.md
> +When you provide a service at the root level, Angular creates a single, shared instance of `HeroService` and injects into any class that asks for it.
> ...creates a single, shared instance of `HeroService` and injects it into any class that asks for it.

This is also a duplicate of line 98 above.

2018-04-03 18:08 UTC, jbogarthyde commented on aio/content/tutorial/toh-pt4.md
> +* You registered the `HeroService` as the _provider_ of its service as the root level, so that it can be injected anywhere in the app.
rewrote this section, typo gone

2018-04-03 19:47 UTC, StephenFluin requested changes
toh-pt4/src/app/hero.service.1.ts needs to be updated with the latest CLI generated code too

2018-04-03 19:47 UTC, StephenFluin commented on aio/content/examples/toh-pt4/src/app/hero.service.ts
> +<<<<<<< HEAD
This shouldn't be in the commit? This looks like an unresolved merge conflict?

2018-04-03 20:01 UTC, jbogarthyde commented on aio/content/examples/toh-pt4/src/app/hero.service.ts
> +<<<<<<< HEAD
It's not in my changed files, don't know where you are seeing it.

2018-04-03 22:59 UTC, mary-poppins commented
You can preview 84ef48e at https://pr22934-84ef48e.ngbuilds.io/.

2018-04-03 23:42 UTC, mary-poppins commented
You can preview 35a70b6 at https://pr22934-35a70b6.ngbuilds.io/.

2018-04-04 13:55 UTC, brandonroberts requested changes

2018-04-04 13:55 UTC, brandonroberts commented on aio/content/examples/toh-pt4/src/app/app.module.ts
> +import { HeroService } from './hero.service';
The `HeroService` doesn't need to be imported into the `app.module.ts` file anymore.

2018-04-04 13:55 UTC, brandonroberts commented on aio/content/tutorial/toh-pt4.md
> +<code-example path="toh-pt4/src/app/app.module.ts" linenums="false" title="src/app/app.module.ts (import service)" region="import-heroservice">
This code example can be removed

2018-04-04 13:55 UTC, brandonroberts commented on aio/content/tutorial/toh-pt4.md
> +@Injectable({providedIn: 'root'})
This needs to match what the CLI generates

```ts
@Injectable({
  providedIn: 'root',
})
```

2018-04-04 13:55 UTC, brandonroberts commented on aio/content/tutorial/toh-pt4.md
>  ### _@Injectable()_ services
The code example should match what the CLI generates

```ts
@Injectable({
  providedIn: 'root',
})
export class HeroService {
```

2018-04-04 13:58 UTC, brandonroberts commented
In the `Create the MessageService` section, the `--module=app` flag can be removed and the `Injectable` decorator needs to match what the CLI generates.

```ts
@Injectable({
  providedIn: 'root',
})
```

2018-04-04 16:29 UTC, mary-poppins commented
You can preview 12f176d at https://pr22934-12f176d.ngbuilds.io/.

2018-04-04 17:32 UTC, mary-poppins commented
You can preview 0b4df82 at https://pr22934-0b4df82.ngbuilds.io/.

2018-04-04 18:13 UTC, mary-poppins commented
You can preview afe22cf at https://pr22934-afe22cf.ngbuilds.io/.

2018-04-04 18:30 UTC, jenniferfell requested changes
Minor edits can be skipped if necessary for time. The important changes are 1) the navigation.json removal from this PR and 2) clearly marking the supplemental info as now part of the main tutorial flow. Otherwise, looks great. Thanks!

2018-04-04 18:30 UTC, jenniferfell commented on aio/content/navigation.json
>          },
Please move this into its own PR. It's unrelated to the other work in this PR, and it has different merge and pull-approve requirements. Thanks.

2018-04-04 18:30 UTC, jenniferfell commented on aio/content/tutorial/toh-pt4.md
> +If you need to, you can register providers at different levels:
This isn't part of the main tutorial flow, so I recommend putting it in a blue box and including a reference to ngModules provider or DI for more information. I'd be very clear that this supplementary information and not part of the flow.

2018-04-04 18:30 UTC, jenniferfell commented on aio/content/tutorial/toh-pt4.md
> +* You registered the `HeroService` as the _provider_ of its service as the root level, so that it can be injected anywhere in the app.
No comma before dependent clause. "....root level so that it can be injected..."

2018-04-04 18:30 UTC, jenniferfell commented on aio/content/tutorial/toh-pt4.md
> +The `HeroService` class should look like the following.
Minor edit. Dropped noun. Recommend "...should look like the following example."

2018-04-04 18:30 UTC, jenniferfell commented on aio/content/tutorial/toh-pt4.md
> +When you provide it at the root level, Angular creates a single, shared instance of `HeroService` and injects into any class that asks for it.
Minor Edit: "it"? When you provide ___ at the root level

2018-04-04 19:08 UTC, jbogarthyde commented on aio/content/tutorial/toh-pt4.md
> +When you provide it at the root level, Angular creates a single, shared instance of `HeroService` and injects into any class that asks for it.
done

2018-04-04 19:08 UTC, jbogarthyde commented on aio/content/tutorial/toh-pt4.md
> +The `HeroService` class should look like the following.
done

2018-04-04 19:08 UTC, jbogarthyde commented on aio/content/tutorial/toh-pt4.md
> +* You registered the `HeroService` as the _provider_ of its service as the root level, so that it can be injected anywhere in the app.
done

2018-04-04 19:50 UTC, mary-poppins commented
You can preview c8d6fe7 at https://pr22934-c8d6fe7.ngbuilds.io/.

2018-04-04 20:30 UTC, brandonroberts approved these changes

2018-04-04 22:24 UTC, StephenFluin requested changes

2018-04-04 22:24 UTC, StephenFluin commented on aio/content/navigation.json
>          },
Still needs to be removed

2018-04-04 22:24 UTC, StephenFluin commented on aio/content/tutorial/toh-pt4.md
> +the class with the `@Injectable()` decorator. This marks the class as one that participates in the _dependency injection system_, either by providing an injectable service or consuming one.
Remove 'or consuming one'. This may have been old guidance to put `@injectable` on anything that may consume a service, but it's not relevant anymore.

2018-04-04 23:38 UTC, mary-poppins commented
You can preview 81b4006 at https://pr22934-81b4006.ngbuilds.io/.

2018-04-04 23:39 UTC, mary-poppins commented
You can preview 580c13e at https://pr22934-580c13e.ngbuilds.io/.

2018-04-05 00:32 UTC, mary-poppins commented
You can preview f571703 at https://pr22934-f571703.ngbuilds.io/.

2018-04-05 00:42 UTC, mary-poppins commented
You can preview b96ee22 at https://pr22934-b96ee22.ngbuilds.io/.

2018-04-05 04:38 UTC, StephenFluin approved these changes
I think we may need to squash the commits, but other than that, looks good!

2018-04-05 05:35 UTC, devoto13 commented on aio/content/tutorial/toh-pt4.md
> +* You registered the `HeroService` as the _provider_ of its service as the root level so that it can be injected anywhere in the app.
as the root level -> at the root level

2018-04-05 14:54 UTC, mary-poppins commented
You can preview 6545420 at https://pr22934-6545420.ngbuilds.io/.

2018-04-05 14:56 UTC, mary-poppins commented
You can preview 3636c0a at https://pr22934-3636c0a.ngbuilds.io/.

2018-04-05 19:15 UTC, mary-poppins commented
You can preview 0869d98 at https://pr22934-0869d98.ngbuilds.io/.

2018-04-05 19:41 UTC, jenniferfell approved these changes

2018-04-05 20:01 UTC, mary-poppins commented
You can preview 9789249 at https://pr22934-9789249.ngbuilds.io/.

2018-04-06 15:16 UTC, mary-poppins commented
You can preview deef42f at https://pr22934-deef42f.ngbuilds.io/.

2018-04-06 15:19 UTC, mary-poppins commented
You can preview aefddc9 at https://pr22934-aefddc9.ngbuilds.io/.

2018-04-07 04:50 UTC, IgorMinar approved these changes

2018-04-07 04:50 UTC, closed without merging