docs: add link to cli and material docs for ng add options
angular/angular pull request #23003
Opened 2018-03-26 18:33 UTC by jenniferfell

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Tutorial and Getting Started currently describe how to use ng new to create a default skeleton app that displays a welcome page.

Issue Number: N/A

## What is the new behavior?
Tutorial and Getting Started now have a note box that introduces the idea of creating more sophisticated apps at project creation by specifying a package and schematics. Included links to CLI doc for ng new and to Material guides for info about materials schematics that are available. 

Did not change main flow of the example being created by Tutorial or Getting Started. That larger change should be considered for a future update. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2018-03-29 23:26 UTC, jenniferfell commented
I removed the stray commits. 

@hansl @jelbourn @StephenFluin How does this look? I need approval from @StephenFluin so I can mark for merge by EOD 3/30. Thanks!

2018-03-30 00:01 UTC, jelbourn approved these changes
LGTM

2018-03-30 00:01 UTC, jelbourn commented on aio/content/guide/quickstart.md
> +See the [Angular Material documentation](https://material.angular.io/guides "Angular Material documentation") for details.
This is good for now; we can update to the specific guide after it's published.

2018-03-30 05:10 UTC, jenniferfell commented on aio/content/guide/quickstart.md
> +See the [Angular Material documentation](https://material.angular.io/guides "Angular Material documentation") for details.
Thanks! Yes, when we have a more specific link, I'm happy to update this reference.

2018-03-30 16:09 UTC, StephenFluin commented on aio/content/guide/quickstart.md
> +For more information, see [ng new](https://github.com/angular/angular-cli/wiki/new "ng new documentation") in the Angular CLI documentation.
Shouldn't we be pointing users to the `ng add` documentation? `ng new` isn't changing (it previously had and continues to have schematics support, it's the addition of `ng add` we want to draw people's attention to.

2018-03-30 16:10 UTC, StephenFluin requested changes
I'm confused as to why we are focusing on `ng new`, I believe we should be focusing on `ng add`.

2018-03-30 17:58 UTC, jenniferfell commented on aio/content/guide/quickstart.md
> +For more information, see [ng new](https://github.com/angular/angular-cli/wiki/new "ng new documentation") in the Angular CLI documentation.
Thank you! I just went back and re-read the meeting notes. Yes. All the examples at the top were ng new, but I clearly did this without caffeine. No page for ng add yet, so I'll update to link to top of CLI wiki and can update again later when there's a specific page for ng add.

2018-03-30 18:01 UTC, jenniferfell commented on aio/content/guide/quickstart.md
> +For more information, see [ng new](https://github.com/angular/angular-cli/wiki/new "ng new documentation") in the Angular CLI documentation.
Let's talk. I'm confused why we're talking about ng add when someone is creating a new project with ng new. I think that's why I assumed there was a change to ng new....because the doc request was related to getting started and tutorial where we create a project. Positioning may be distracting. Does this go somewhere else.

2018-03-30 20:38 UTC, mary-poppins commented
You can preview c5bbe5e at https://pr23003-c5bbe5e.ngbuilds.io/.
You can preview 7b4690a at https://pr23003-7b4690a.ngbuilds.io/.
You can preview a69ef99 at https://pr23003-a69ef99.ngbuilds.io/.

2018-03-30 20:48 UTC, mary-poppins commented
You can preview 104f1ca at https://pr23003-104f1ca.ngbuilds.io/.

2018-03-30 21:09 UTC, jenniferfell commented
Moved to new PR to resolve CLA issue. https://github.com/angular/angular/pull/23098

2018-03-30 21:09 UTC, closed without merging