Update chars.ts
angular/angular pull request #23077
Opened 2018-03-30 01:15 UTC by TzyHuan

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Make parameters can be named in "Traditional Chinese" as well.

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[x ] Other... Please describe:
```
add language.

## What is the current behavior?

Angular is used worldwide, I hope parameters can be named not only English!!

Issue Number: #517 

## What is the new behavior?
To satisfy my needs at first, I add a judgement to allow Traditional Chinese only.
Make parameters can be named in "Traditional Chinese".

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

## Other information

2018-03-30 01:48 UTC, TzyHuan commented
I signed it!

2018-03-30 14:40 UTC, vicb commented on packages/compiler/src/chars.ts
> +  return code >= $a && code <= $z || code >= $A && code <= $Z  || (code >= 0x4E00 && code <= 0x9FA5);
- We should probably not limit this to traditional Chinese, some work has been done recently in the [TitleCasePipe](https://github.com/angular/angular/blob/master/packages/common/src/pipes/case_conversion_pipes.ts#L31) that could probably help,
- The name of the function should be change (it's no more ASCII letters),
- The tests should be updated

2018-03-30 14:41 UTC, vicb requested changes
See inline comments

2018-04-03 22:45 UTC, vicb commented
Please open a new PR when the changes are done. Thanks.

2018-04-03 22:45 UTC, closed without merging