docs: add fakeAsync test new feature document
angular/angular pull request #23117
Opened 2018-04-01 14:15 UTC by JiaLiPassion

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: PR #23108

## What is the new behavior?
add document to explain the new feature of `fakeAsync` in `zone.js 0.8.23`.

- support auto patch `Date.now` and `new Date()` in `fakeAsync`.

```javascript
 fakeAsyncTestZone.run(() => {
        const start = Date.now();
        testZoneSpec.tick(100);
        const end = Date.now();
        expect(end - start).toBe(100);
  });

 fakeAsyncTestZone.run(() => {
        const start = new Date();
        testZoneSpec.tick(100);
        const end = new Date();
        expect(end.getTime() - start.getTime()).toBe(100);
  });
```

- automatically run a `fakeAsync` test when `jasmine.clock().install` is called.

```javascript
   beforeEach(() => {
      jasmine.clock().install();
    });

    afterEach(() => {
      jasmine.clock().uninstall();
    });

    it('should get date diff correctly', () => {  // we don't need fakeAsync here.
      // automatically run into fake async zone, because jasmine.clock() is installed.
      const start = Date.now();
      jasmine.clock().tick(100);
      const end = Date.now();
      expect(end - start).toBe(100);
    });
```

- rxjs `Scheduler` support, need to import `zone.js/dist/zone-patch-rxjs-fake-async`.

```javascript
    import '../../lib/rxjs/rxjs-fake-async';
    it('should get date diff correctly', (done) => {
      fakeAsyncTestZone.run(() => {
        let result = null;
        const observable = new Observable((subscribe: any) => {
          subscribe.next('hello');
        });
        observable.delay(1000).subscribe(v => {
          result = v;
        });
        expect(result).toBeNull();
        testZoneSpec.tick(1000);
        expect(result).toBe('hello');
        done();
      });
    });
```

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

because if user user `jasmine.clock().install`, the `it` will go into `fakeAsync` automatically, and user don't need to  call `fakeAsync` themselves, and if they call `fakeAsync`, `fakeAsync can't be nested` error will throw. So it may affect some existing test cases.

## Other information

the doc will be available from `zone.js 0.8.23` and after #23108 is merged.

@mhevery , please review, thank you.

2018-04-01 14:27 UTC, alfaproject commented
So, basically `zone.js` introduced a new feature (moved from Angular), that introduces a breaking change in Angular.

Angular now needs to force the consumers to update to latest `zone.js` explicitly? Are there going to be version checks?

2018-04-01 15:21 UTC, JiaLiPassion commented
@alfaproject, yes, there are break changes, I am not sure how to do version check...

2018-04-02 15:08 UTC, JiaLiPassion commented
@alfaproject , I have removed all `breaking changes` in other PR, so I also updated the document here.

2018-05-15 14:43 UTC, alfaproject commented
@JiaLiPassion after updating to Angular 6 and removing `rxjs-compat`, then I get this error:

```
ERROR in ./node_modules/zone.js/dist/zone-patch-rxjs-fake-async.js
Module not found: Error: Can't resolve 'rxjs/Scheduler' in '/Users/alfa/Documents/xcaliber/stash/xc-r2d2/node_modules/zone.js/dist'
 @ ./node_modules/zone.js/dist/zone-patch-rxjs-fake-async.js 9:72-97
 @ ./src/test.base.ts
 @ ./src/test.ts
```

This is the only thing preventing me from getting rid of `rxjs-compat`. ):

2018-05-15 14:50 UTC, JiaLiPassion commented
@alfaproject, the `rxjs scheduler` patch now only support `rxjs 5.x`, I am working on it to support `rxjs 6`, so please wait for a while.

2018-05-15 14:58 UTC, alfaproject commented
@JiaLiPassion thanks (:

2018-07-04 12:42 UTC, mary-poppins commented
You can preview c073396 at https://pr23117-c073396.ngbuilds.io/.
You can preview 60595c0 at https://pr23117-60595c0.ngbuilds.io/.
You can preview e591062 at https://pr23117-e591062.ngbuilds.io/.
You can preview 90eaa73 at https://pr23117-90eaa73.ngbuilds.io/.
You can preview ec3bb79 at https://pr23117-ec3bb79.ngbuilds.io/.
You can preview e151484 at https://pr23117-e151484.ngbuilds.io/.
You can preview f1cfb11 at https://pr23117-f1cfb11.ngbuilds.io/.
You can preview f346daa at https://pr23117-f346daa.ngbuilds.io/.
You can preview 34a731b at https://pr23117-34a731b.ngbuilds.io/.

2018-07-19 03:16 UTC, JiaLiPassion commented
@brandonroberts, thank you for reviewing the document and if there is anything need to update, please tell me.

2018-07-23 14:04 UTC, brandonroberts requested changes

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +
Few changes

The `tick()` function accepts _milliseconds_ as parameter (defaults to `0` if not provided). The parameter represents how much the virtual clock advances. For example, if you have a `setTimeout(fn, 100)` in a `fakeAsync()` test, you need to use `tick(100)` to trigger the `fn` callback.

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +`fakeAsync` implements a virtual scheduler to simulate clock, so you can still check Date such as calculate date diff inside `fakeAsync`.
"simulate passage of time, which allows you to calculate the difference between dates inside `fakeAsync`"

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +jasmine also provide a `clock` feature to mock date, angular provide a feature that if user use `jasmine.clock().install()`, the following `it` test will automatically into `fakeAsync` until `jasmine
"Jasmine also provides a `clock` feature to mock dates. Angular automatically runs tests that are run after 
 `jasmine.clock().install()` is called inside a `fakeAsync()` method until `jasmine.clock().uninstall()` is called.  `fakeAsync` is not needed and throws an error if nested.

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +For example, if you use angular/cli, you can config this flag in `src/test.ts`.
"if you use the `Angular CLI`, configure this flag..."

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +By default, this feature is disabled, to enable it, you need to set a global flag before import `zone-testing`.
"disabled. To enable it, set a global flag..."

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +`fakeAsync` implements a virtual scheduler to simulate clock, so you can still check Date such as calculate date diff inside `fakeAsync`.
Always refer to methods with parenthesis... `fakeAsync()`

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +#### rxjs scheduler with fakeAsync ####
"Using the RxJS scheduler..."

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +You can also use rxjs scheduler in fakeAsync just like using `setTimeout` or `setInterval`, but you need to import `zone.js/dist/zone-patch-rxjs-fake-async` to patch rxjs scheduler.
Add parenthesis to methods

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
>  Writing test functions with `done()`, is more cumbersome than `async`and `fakeAsync`.
Add a space between `async`and

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +code that involves the `intervalTimer()` like `setInterval`.
Not sure what happened here?

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +You can't call `done` in `async` or `fakeAsync` functions, because the `done`
"done()"

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +You can't call `done` in `async` or `fakeAsync` functions, because the `done`
"because the `done` is `undefined`"

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +And if you use `intervalTimer()` such as `setInterval()` in `async()`, you need to make sure you cancel the timer with such as `clearInterval()` after the test, otherwise the `async()` will never end
"`async()` never ends."

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/testing.md
> +You don't need to pass Jasmine's `done()` into the test and call `done()`, in fact you can not pass `done()` because it will be `undefined` in promise or observable callbacks.
remove ", in fact you can not pass `done()`"

2018-07-23 14:04 UTC, brandonroberts commented on aio/content/guide/setup.md
> +
I think this should be included in the testing guide and linked to from the `fakeAsync` and `async` sections.

2018-07-23 21:21 UTC, JiaLiPassion commented
@brandonroberts, thank you for reviewing the PR, I have modified the contents, please review.

2018-07-23 21:32 UTC, mary-poppins commented
You can preview 75f617b at https://pr23117-75f617b.ngbuilds.io/.

2018-07-24 10:12 UTC, mary-poppins commented
You can preview f4321ea at https://pr23117-f4321ea.ngbuilds.io/.

2018-07-27 17:08 UTC, brandonroberts commented on aio/content/guide/setup.md
> +
I misspoke. I don't think this should be in the appendix for getting setup and it should only be in the testing guide.

2018-07-27 17:16 UTC, brandonroberts requested changes

2018-07-27 17:16 UTC, brandonroberts commented on aio/content/guide/setup.md
> +And in the ealier version of `angular`, you may have imported the following files or added then in your html file.
"earlier"
`Angular`

2018-07-27 17:16 UTC, brandonroberts commented on aio/content/guide/setup.md
> +If you use `fakeAsync()/async()` helper function to do unit test (for detail, please read [testing guide](guide/testing#async-test-with-fakeasync)), you need to import the following file.
"use the"
"to run unit tests"

2018-07-27 17:16 UTC, brandonroberts commented on aio/content/guide/setup.md
> +you must import `zone.js/dist/zone-testing`, if you create project with angular/cli, it will be already imported in `src/test.ts`.
"You must import `...`. If you..."
angular/cli -> Angular CLI
"it will be" -> it is

2018-07-27 17:16 UTC, brandonroberts commented on aio/content/guide/setup.md
> +you can still load those files seperately, but the order is important, you must import `proxy` before `sync-test`, `async-test`, `fake-async-test` and `jasmine-patch`. And you also need to import `sy
"You"
"instead of"

2018-07-27 17:16 UTC, brandonroberts commented on aio/content/guide/testing.md
> +To use `async()` functionality, you need to import `zone-testing`, for details, please read [setup guide](https://pr23117-34a731b.ngbuilds.io/guide/setup#appendix-test-using-fakeasyncasync).
This should use a local link and not the full path

2018-07-27 17:16 UTC, brandonroberts commented on aio/content/guide/testing.md
> +You can't call `done()` in `async()` or `fakeAsync()` functions, because the `done`
`done()`

2018-07-27 20:47 UTC, JiaLiPassion commented on aio/content/guide/setup.md
> +And in the ealier version of `angular`, you may have imported the following files or added then in your html file.
Thank you, done!

2018-07-27 20:48 UTC, JiaLiPassion commented on aio/content/guide/setup.md
> +If you use `fakeAsync()/async()` helper function to do unit test (for detail, please read [testing guide](guide/testing#async-test-with-fakeasync)), you need to import the following file.
Thank you, done!

2018-07-27 20:49 UTC, JiaLiPassion commented on aio/content/guide/setup.md
> +you must import `zone.js/dist/zone-testing`, if you create project with angular/cli, it will be already imported in `src/test.ts`.
Thank you, done!

2018-07-27 20:50 UTC, JiaLiPassion commented on aio/content/guide/setup.md
> +you can still load those files seperately, but the order is important, you must import `proxy` before `sync-test`, `async-test`, `fake-async-test` and `jasmine-patch`. And you also need to import `sy
Thank you, done!

2018-07-27 20:51 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +To use `async()` functionality, you need to import `zone-testing`, for details, please read [setup guide](https://pr23117-34a731b.ngbuilds.io/guide/setup#appendix-test-using-fakeasyncasync).
Thank you, done!

2018-07-27 20:54 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +You can't call `done()` in `async()` or `fakeAsync()` functions, because the `done`
Here I want to say that `done` is undefined.
I change it to `done parameter`, is that ok?

2018-07-27 20:56 UTC, JiaLiPassion commented
@brandonroberts, I have modified the doc based on your comments, thank you! And about the last comment, I have some other thoughts, please review, thank you.

2018-07-27 21:05 UTC, mary-poppins commented
You can preview 3585d40 at https://pr23117-3585d40.ngbuilds.io/.

2018-07-30 19:55 UTC, brandonroberts requested changes

2018-07-30 19:55 UTC, brandonroberts commented on aio/content/guide/setup.md
> +If you use the `fakeAsync()/async()` helper function to run unit tests (for detail, please read [testing guide](guide/testing#async-test-with-fakeasync)), you need to import the following file.
"detail, please read" -> "details, read the"

2018-07-30 19:55 UTC, brandonroberts commented on aio/content/guide/setup.md
> +If you use the `fakeAsync()/async()` helper function to run unit tests (for detail, please read [testing guide](guide/testing#async-test-with-fakeasync)), you need to import the following file.
"you need to import `zone.js/dist/zone-testing` in your test setup file"

2018-07-30 19:55 UTC, brandonroberts commented on aio/content/guide/setup.md
> +you must import `zone.js/dist/zone-testing` if you create project with `Angular/CLI`, it is already imported in `src/test.ts`.
Remove "you must import ..." and only include "If you created the project with the `Angular CLI`..."

2018-07-30 19:55 UTC, brandonroberts commented on aio/content/guide/setup.md
> +And in the earlier version of `Angular`, you may have imported the following files or added then in your html file.
"versions"
"you may have imported the following files..." -> "the following files were imported or added in your html file:"

2018-07-30 19:55 UTC, brandonroberts commented on aio/content/guide/testing.md
> +To use `fakeAsync()` functionality, you need to import `zone-testing`, for details, please read [setup guide](https://pr23117-34a731b.ngbuilds.io/guide/setup#appendix-test-using-fakeasyncasync).
This link should be (/guide/setup...)

2018-07-30 19:55 UTC, brandonroberts commented on aio/content/guide/testing.md
> +The `fakeAsync()` function enables a linear coding style by running the test body in a special _fakeAsync test zone_.
"zone_" => "zone"

2018-07-30 19:55 UTC, brandonroberts commented on aio/content/guide/testing.md
> +`fakeAsync()` simulate passage of time, which allows you to calculate the difference between dates inside `fakeAsync()`.
"simulates"

2018-07-30 19:55 UTC, brandonroberts commented on aio/content/guide/testing.md
> +You can also use rxjs scheduler in `fakeAsync()` just like using `setTimeout()` or `setInterval()`, but you need to import `zone.js/dist/zone-patch-rxjs-fake-async` to patch rxjs scheduler.
"RxJS"

2018-07-30 19:55 UTC, brandonroberts commented on aio/content/guide/testing.md
> +You can also use rxjs scheduler in `fakeAsync()` just like using `setTimeout()` or `setInterval()`, but you need to import `zone.js/dist/zone-patch-rxjs-fake-async` to patch rxjs scheduler.
"to patch the RxJS scheduler"

2018-07-30 19:55 UTC, brandonroberts commented on aio/content/guide/testing.md
> +#### Date in fakeAsync() ####
Comparing dates inside `fakeAsync()`

2018-07-30 19:55 UTC, brandonroberts commented on aio/content/guide/testing.md
> +And if you use `intervalTimer()` such as `setInterval()` in `async()`, you need to make sure you cancel the timer with such as `clearInterval()` after the test, otherwise the `async()` never ends.
"And if you use" -> "When using an"

2018-07-30 19:55 UTC, brandonroberts commented on aio/content/guide/testing.md
> +And if you use `intervalTimer()` such as `setInterval()` in `async()`, you need to make sure you cancel the timer with such as `clearInterval()` after the test, otherwise the `async()` never ends.
"you need to make sure you..." -> "remember to cancel the timer with `clearInterval()`"

2018-07-31 14:37 UTC, JiaLiPassion commented on aio/content/guide/setup.md
> +If you use the `fakeAsync()/async()` helper function to run unit tests (for detail, please read [testing guide](guide/testing#async-test-with-fakeasync)), you need to import the following file.
Thank you, done!

2018-07-31 14:37 UTC, JiaLiPassion commented on aio/content/guide/setup.md
> +you must import `zone.js/dist/zone-testing` if you create project with `Angular/CLI`, it is already imported in `src/test.ts`.
Thank you, done!

2018-07-31 14:40 UTC, JiaLiPassion commented on aio/content/guide/setup.md
> +And in the earlier version of `Angular`, you may have imported the following files or added then in your html file.
Thank you, done!

2018-07-31 14:40 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +To use `fakeAsync()` functionality, you need to import `zone-testing`, for details, please read [setup guide](https://pr23117-34a731b.ngbuilds.io/guide/setup#appendix-test-using-fakeasyncasync).
Thank you, done!

2018-07-31 14:40 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +The `fakeAsync()` function enables a linear coding style by running the test body in a special _fakeAsync test zone_.
Thank you, done!

2018-07-31 14:40 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +`fakeAsync()` simulate passage of time, which allows you to calculate the difference between dates inside `fakeAsync()`.
Thank you, done!

2018-07-31 14:41 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +You can also use rxjs scheduler in `fakeAsync()` just like using `setTimeout()` or `setInterval()`, but you need to import `zone.js/dist/zone-patch-rxjs-fake-async` to patch rxjs scheduler.
Thank you, done!

2018-07-31 14:42 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +#### Date in fakeAsync() ####
Thank you, done!

2018-07-31 14:43 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +And if you use `intervalTimer()` such as `setInterval()` in `async()`, you need to make sure you cancel the timer with such as `clearInterval()` after the test, otherwise the `async()` never ends.
Thanks, done!

2018-07-31 14:53 UTC, mary-poppins commented
You can preview 93aefa4 at https://pr23117-93aefa4.ngbuilds.io/.

2018-07-31 15:13 UTC, JiaLiPassion commented
@brandonroberts, thank you again for the detailed review and check, I have updated the PR, please review.

2018-08-08 13:35 UTC, brandonroberts approved these changes

2018-08-10 13:47 UTC, brandonroberts commented
@JiaLiPassion will you rebase this branch again?
@IgorMinar will you review?

2018-08-10 22:34 UTC, mary-poppins commented
You can preview 3f86758 at https://pr23117-3f86758.ngbuilds.io/.

2018-08-11 05:57 UTC, JiaLiPassion commented
@brandonroberts, sure, I have rebased the branch, please review, thank you.

2018-08-11 08:56 UTC, JoostK commented on aio/content/examples/testing/src/app/demo/async-helper.spec.ts
> +    afterEach(jasmine.clock().uninstall);
Perhaps make these `beforeEach(() => jasmine.clock().install());` to have `this` refer to `jasmine.clock()` instead of whatever `beforeEach` passes as context? Currently jasmine doesn't refer to `this` from either `install`/`uninstall` so it works, but it will result in hard to track errors if they ever to start to use `this`.

2018-08-11 14:42 UTC, JiaLiPassion commented on aio/content/examples/testing/src/app/demo/async-helper.spec.ts
> +    afterEach(jasmine.clock().uninstall);
@JoostK, thank you for pointing out this issue, I will fix this one.

2018-08-11 15:06 UTC, mary-poppins commented
You can preview e8b0a80 at https://pr23117-e8b0a80.ngbuilds.io/.

2018-08-20 13:28 UTC, brandonroberts commented
@JiaLiPassion waiting on another review/approval for this one.

2018-08-21 04:10 UTC, JiaLiPassion commented
@brandonroberts, sure, got it, thank you for your great help!

2018-10-04 23:54 UTC, IgorMinar approved these changes

2018-10-04 23:55 UTC, IgorMinar commented
thanks @JiaLiPassion!

2018-10-05 00:49 UTC, JiaLiPassion commented
@IgorMinar Thanks for the review!

2018-10-05 22:44 UTC, closed without merging