refactor(service-worker): public API/docs fixes and minor refactoring
angular/angular pull request #23138
Opened 2018-04-03 11:05 UTC by gkalpak

## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] ~~Tests for the changes have been added (for bug fixes / features)~~
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
```
[x] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
```

## What is the current behavior?
`NgswCommChannel`, `UpdateAvailableEvent`, `UpdateActivatedEvent` are mentioned in the docs without being part of the public API. 
The constructors of `SwPush`/`SwUpdate` are shown in the docs, making it look like they could be manually constructed.

## What is the new behavior?
`UpdateAvailableEvent`, `UpdateActivatedEvent` are added to the public API.
`SwPush`/`SwUpdate` are changed to abstract classes, so their constructors (including the `NgswCommChannel`) are not shown in the docs.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No (afaict :D)
```

2018-04-10 22:47 UTC, mary-poppins commented
You can preview 17e5de9 at https://pr23138-17e5de9.ngbuilds.io/.
You can preview 5197d77 at https://pr23138-5197d77.ngbuilds.io/.
You can preview aed1cdb at https://pr23138-aed1cdb.ngbuilds.io/.
You can preview 9dae264 at https://pr23138-9dae264.ngbuilds.io/.

2018-05-09 14:19 UTC, alxhub requested changes

2018-05-09 14:19 UTC, alxhub commented on packages/service-worker/src/module.ts
> +    {provide: SwPush, useClass: SwPushImpl},
This is unnecessary, just mark the constructors `@internal` instead.

2018-05-09 15:02 UTC, gkalpak commented on packages/service-worker/src/module.ts
> +    {provide: SwPush, useClass: SwPushImpl},
IIRC, marking the constructor as `@internal` converts the class to an interface (in the API docs).
And interfaces can't be used as injection tokens (while abstract classes can), so I thought it would be confusing for users (not realizing they _can_ use `SwPush` as an injection token even if it shows up as an interface in the docs).

But happy to change it `@internal` constructor if you feel strongly about it.

2018-05-17 11:36 UTC, gkalpak commented on packages/service-worker/src/module.ts
> +    {provide: SwPush, useClass: SwPushImpl},
Discussed offline:
We'll leave the constructors for now, since this is a general problem throughout the framework.
(Hopefully there will be a better solution in the near future.)

2018-05-17 12:49 UTC, mary-poppins commented
You can preview 31359f9 at https://pr23138-31359f9.ngbuilds.io/.

2018-05-17 13:17 UTC, gkalpak commented
Updated as discussed and rebased on master. PTAL, @alxhub.

2018-09-21 12:57 UTC, mary-poppins commented
You can preview 75e7a34 at https://pr23138-75e7a34.ngbuilds.io/.

2018-09-21 14:43 UTC, alxhub approved these changes
Nice job!

2018-10-05 15:20 UTC, IgorMinar approved these changes
thanks for the cleanup!

2018-10-05 19:03 UTC, jenniferfell commented
FYI: swupdate is mentioned in 3 places in the guides. If it's not part of the public API, we'll need to rewrite those sections.

2018-10-05 19:11 UTC, IgorMinar commented
@jenniferfell it is. but we haven't made any change that would modify the previously exposed public api. This PR only reexports two interfaces that were previously not exported by mistake.

2018-10-05 20:49 UTC, closed without merging