docs: add new page about updating angular version
angular/angular pull request #23184
Opened 2018-04-05 08:52 UTC by jenniferfell

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Adds a new page about updating the version of Angular

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The current docs do not include any information about updating. All of the information is in other locations. 

Issue Number: N/A

## What is the new behavior?
Add a new page about updating. Rename navigation items related to upgrading from AngularJS so the distinction is more clear. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[X ] No
```

## Other information

2018-04-05 09:30 UTC, mary-poppins commented
You can preview d548eba at https://pr23184-d548eba.ngbuilds.io/.

2018-04-13 21:48 UTC, mary-poppins commented
You can preview 289b9d3 at https://pr23184-289b9d3.ngbuilds.io/.

2018-04-13 22:35 UTC, mary-poppins commented
You can preview ed46518 at https://pr23184-ed46518.ngbuilds.io/.

2018-04-13 22:46 UTC, mary-poppins commented
You can preview 1ab3391 at https://pr23184-1ab3391.ngbuilds.io/.

2018-04-14 00:43 UTC, IgorMinar requested changes
I think we should update this doc more before merging it because it contains a small number of factual errors.

2018-04-14 00:43 UTC, IgorMinar commented on aio/content/guide/update-angular.md
> +* Major releases contain significant changes to Angular. A major release may contain breaking changes. A breaking change happens whenever you as a developer and consumer of a library may need to adju
this wording is not quite right. we need to be very careful about how we word this because our goal is to focus on minimizing any upgrade page.

Breaking changes mean that a public api has changed in a way where the users of that api can no longer use it. It's very very rare for us to make those kinds of changes or make them without deprecating the API first for the period of at least two major releases (our n+2 deprecation policy).

I would simplify the distinction to of these three paragraphs into:

- major release = significant new features, some but minimal developer assistance expected during the update (like running update scripts, refactoring code, running more tests, getting familiar with new apis)
- minor release = new smaller features, fully backwards compatible, no developer assistance during expected
- patch releases = low risk, bug fix releases. no developer assistance during update expected

2018-04-14 00:43 UTC, IgorMinar commented on aio/content/guide/update-angular.md
> +Angular supports updating within a major version, such as from 5.1.0 to 5.2.9. Angular also supports updating from one major version to the next, such as from any 4.x version to the most current 5.x
This paragraph should have it's own heading - "Update planning" or something like that.

- expect a major release every 6 months, typically around march/april and september/october
- 2-3 minor releases for each major cycle
- approximately weekly patch releases

you might want to move some content from https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md and move it here

Then next section should be the one you tried to cover here "Update strategy":
- if you are updating from one version to the next within the same major version, then we recommend that you just skip any intermediate versions and update to the targeted version
- if you are updating from one major version to another and your application is non-trivial, then we recommend that you don't skip major versions and instead use updating instructions for each major release to incrementally get to the targeted version, testing and validating at each step.

2018-04-14 00:43 UTC, IgorMinar commented on aio/content/guide/update-angular.md
> +## Learning about new releases
this paragraph and the one above seem to be about the same thing - maybe merge them?

2018-04-14 00:43 UTC, IgorMinar commented on aio/content/guide/update-angular.md
> +The [Angular release schedule](https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md "Angular release schedule") contains a record of past Angular releases and the future release sc
we should in fact try to roll that whole doc into this doc and remove it from /docs/ and host it on angular.io instead.

2018-04-14 00:43 UTC, IgorMinar commented on aio/content/guide/update-angular.md
> +By default, the CLI command `ng update` updates your project to the most recent version of Angular. You don't need to specify a version.
this incorrect. it should be: By default, the CLI command `ng update` (without additional arguments) lists the updates available to you and provides you with recommended steps to update your application.

2018-04-14 00:43 UTC, IgorMinar commented on aio/content/guide/update-angular.md
> +By default, the CLI command `ng update` updates your project to the most recent version of Angular. You don't need to specify a version.
@StephenFluin @hansl if update.angular.io is our goto update resource then we should mention it in the output of `ng update` no?

2018-04-14 00:43 UTC, IgorMinar commented on aio/content/guide/update-angular.md
> +To update your app or library, follow the instructions in the interactive [Angular Update Guide](https://angular-update-guide.firebaseapp.com/ "Angular Update Guide"). The Angular Update Guide provid
please update the link to https://update.angular.io

2018-04-14 00:43 UTC, IgorMinar commented on aio/content/guide/update-angular.md
> +* Update instructions: [Angular Update Guide](https://angular-update-guide.firebaseapp.com/ "Angular Update Guide")
https://update.angular.io

2018-04-14 00:43 UTC, IgorMinar commented on aio/content/guide/update-angular.md
> +To update your app or library, follow the instructions in the interactive [Angular Update Guide](https://angular-update-guide.firebaseapp.com/ "Angular Update Guide"). The Angular Update Guide provid
the link doesn't work yet, but will soon, so we should just use the new address already

2018-04-14 00:43 UTC, IgorMinar commented on aio/content/guide/update-angular.md
> +
two important question that the current doc doesn't answer is what version should I use and how long will that version be supported: 

- use the latest version whenever possible, all of the applications at google run on the pre-release version of Angular, so while occasional regressions do occur, we feel pretty confident in our releases
- all major versions are actively supported (bugfixes and features) until the next major release (~6 months after its release), and then we provide LTS support (critical security and bug fixes) for another two major releases (so e.g. v4 was actively supported until v5 was released, and we provide LTS support until v7 is released)

2018-04-16 14:11 UTC, mary-poppins commented
You can preview 1e64a69 at https://pr23184-1e64a69.ngbuilds.io/.

2018-04-16 15:58 UTC, jenniferfell commented on aio/content/guide/update-angular.md
> +Angular is continually improving. Keeping your Angular app up-to-date enables you to take advantage of the most recent bug fixes, changes, and new features.
Done

2018-04-16 16:02 UTC, jenniferfell commented on aio/content/guide/update-angular.md
> +Angular version numbers indicate the level of changes that are introduced by the release. This use of [semantic versioning](https://semver.org/ "Semantic Versioning 2.0.0") helps you understand the p
The 2.0.0 wasn't in visible text, only the link hover text. But...I changed it to "Semantic Versioning Specification" to future-proof if SemVer has a new version.

2018-04-16 16:08 UTC, jenniferfell commented on aio/content/guide/update-angular.md
> +* Major releases contain significant changes to Angular. A major release may contain breaking changes. A breaking change happens whenever you as a developer and consumer of a library may need to adju
Done

2018-04-16 16:53 UTC, jenniferfell commented on aio/content/guide/update-angular.md
> +## Learning about new releases
Clarified the difference. Thx.

2018-04-16 17:07 UTC, jenniferfell commented on aio/content/guide/update-angular.md
> +By default, the CLI command `ng update` updates your project to the most recent version of Angular. You don't need to specify a version.
Updated. Kept focus here on finding out what Angular releases are available.

2018-04-16 17:13 UTC, jenniferfell commented on aio/content/navigation.json
> +              "title": "AngularJS to Angular Reference",
Former title "Upgrading cheatsheet" sounded like it was a cheatsheet to the steps for doing the upgrade, which it isn't, so I wanted to change nav to capture the important part "AngularJS to Angular" mappings.  "Cheatsheet" doesn't fit in the nav without wrapping, and it doesn't match the actual page title. So I tried "QuickRef" this time. 

fwiw...In my experience, most people have a vague understanding "guide" to be "how to" and conceptual info, and "Reference" to be look up information, such as project file listings and syntax descriptions or this table of mappings.

2018-04-16 17:29 UTC, jenniferfell commented on aio/content/navigation.json
> +          "url": "guide/update-angular",
done

2018-04-16 19:28 UTC, mary-poppins commented
You can preview 9170a34 at https://pr23184-9170a34.ngbuilds.io/.

2018-04-25 20:52 UTC, mary-poppins commented
You can preview a89f705 at https://pr23184-a89f705.ngbuilds.io/.

2018-04-26 00:06 UTC, jenniferfell commented
Git issues. Moved work to new PR. https://github.com/angular/angular/pull/23551

2018-04-26 00:06 UTC, closed without merging