Special case [style] and [class] bindings
angular/angular pull request #23232
Opened 2018-04-06 20:41 UTC by matsko

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2018-04-06 20:50 UTC, mary-poppins commented
You can preview 749ed3f at https://pr23232-749ed3f.ngbuilds.io/.

2018-04-06 20:59 UTC, mhevery approved these changes
one small nit, LGTM otherwise

2018-04-06 20:59 UTC, mhevery commented on packages/compiler/test/render3/r3_view_compiler_styling_spec.ts
> +/* These tests are codified version of the tests in compiler_canonical_spec.ts. Every
remove this comment as it is not relevant

2018-04-06 22:56 UTC, vicb commented on packages/compiler/src/render3/r3_view_compiler.ts
>        const instruction = BINDING_INSTRUCTION_MAP[input.type];
why not `const instruction = getInputInstruction(input);` ?

2018-04-06 22:57 UTC, vicb commented on packages/compiler/test/render3/r3_view_compiler_styling_spec.ts
> +/* These tests are codified version of the tests in compiler_canonical_spec.ts. Every
Shouldn't this be a conformance test ?

2018-04-06 22:58 UTC, vicb commented on packages/compiler/test/render3/r3_view_compiler_styling_spec.ts
> +            $r3$.ɵs(0,ctx.myStyleExp);
`ctx` should probably not be hardcoded -> use `$ctx$` instead ? (in the arg list and here)

2018-04-06 22:58 UTC, vicb requested changes
see inline comments

2018-04-07 23:01 UTC, mary-poppins commented
You can preview 5e61db0 at https://pr23232-5e61db0.ngbuilds.io/.

2018-04-07 23:04 UTC, mary-poppins commented
You can preview 5c4fc09 at https://pr23232-5c4fc09.ngbuilds.io/.

2018-04-07 23:07 UTC, mary-poppins commented
You can preview 3c1d545 at https://pr23232-3c1d545.ngbuilds.io/.

2018-04-07 23:13 UTC, sandangel commented on packages/compiler/test/render3/r3_view_compiler_styling_spec.ts
> +            $r3$.ɵs(0,$ctx$.myStyleExp);
space after comma?

2018-04-09 16:31 UTC, vicb commented on packages/compiler/src/render3/r3_view_compiler.ts
> +const SPECIAL_CASED_BINDING_INSTRUCTION_MAP: {[index: string]: o.ExternalReference | undefined} = {
`| undefined` ?

2018-04-09 16:48 UTC, matsko commented on packages/compiler/test/render3/r3_view_compiler_styling_spec.ts
> +            $r3$.ɵs(0,$ctx$.myStyleExp);
No it's not needed because this code is generated by AOT (and it conserves size by avoiding unnecessary space usage).

2018-04-09 16:48 UTC, matsko commented on packages/compiler/test/render3/r3_view_compiler_styling_spec.ts
> +            $r3$.ɵk(0,$ctx$.myClassExp);
See comment above.

2018-04-09 18:00 UTC, mhevery commented on packages/compiler/test/render3/r3_view_compiler_styling_spec.ts
> +            $r3$.ɵs(0,$ctx$.myStyleExp);
this is a test, and spaces are ignored so for readability you should add it.

2018-04-09 18:01 UTC, mhevery commented on packages/compiler/test/render3/r3_view_compiler_styling_spec.ts
> +            $r3$.ɵk(0,$ctx$.myClassExp);
see my comment above. please add space to make it more readable. This is test only and will not have effect on output of compiler.

2018-04-12 18:50 UTC, vicb reviewed
inline comments

2018-04-12 18:50 UTC, vicb commented on packages/compiler/src/render3/r3_view_compiler.ts
> +  'className': R3.elementClass,
`class` ?

2018-04-12 18:50 UTC, vicb commented on packages/compiler/test/render3/r3_view_compiler_styling_spec.ts
> +/* These tests are codified version of the tests in compiler_canonical_spec.ts. Every
?

2018-04-12 18:59 UTC, mary-poppins commented
You can preview 29d4466 at https://pr23232-29d4466.ngbuilds.io/.

2018-04-12 19:03 UTC, vicb approved these changes

2018-04-12 19:08 UTC, mary-poppins commented
You can preview 80feb9d at https://pr23232-80feb9d.ngbuilds.io/.

2018-04-18 14:52 UTC, AlexGorGor commented on packages/compiler/src/render3/r3_view_compiler.ts
>        const instruction = BINDING_INSTRUCTION_MAP[input.type];
hehe

2018-06-01 16:49 UTC, mary-poppins commented
You can preview e1d89d9 at https://pr23232-e1d89d9.ngbuilds.io/.

2018-06-01 23:38 UTC, mary-poppins commented
You can preview f0ca8b9 at https://pr23232-f0ca8b9.ngbuilds.io/.

2018-06-04 18:06 UTC, mary-poppins commented
You can preview 428f29d at https://pr23232-428f29d.ngbuilds.io/.

2018-06-04 19:21 UTC, JoostK commented on packages/compiler/test/render3/r3_view_compiler_styling_spec.ts
> +              $r3$.ɵs(0,$r3$.ɵb($ctx$.myClassExp));
Shouldn't this be `ɵk`?

2018-06-06 21:44 UTC, vicb submitted a review, later dismissed
please update status.md

2018-06-07 18:39 UTC, mary-poppins commented
You can preview e284c46 at https://pr23232-e284c46.ngbuilds.io/.

2018-06-07 21:01 UTC, mhevery commented
`STATUS.md` updated

2018-06-07 21:17 UTC, mary-poppins commented
You can preview 292f37d at https://pr23232-292f37d.ngbuilds.io/.

2018-06-08 16:04 UTC, vicb commented on packages/compiler/src/render3/r3_identifiers.ts
> +  static elementClass: o.ExternalReference = {name: 'ɵk', moduleName: CORE};
Could you please update [environment.ts](https://github.com/angular/angular/blob/master/packages/core/src/render3/jit/environment.ts) with that.

Also may be add a comment in this file and environment.ts to remember to keep them in sync.

Thanks

2018-06-08 21:33 UTC, vicb approved these changes

2018-06-08 22:29 UTC, closed without merging