refactor(ivy): speed up bound text nodes
angular/angular pull request #23386
Opened 2018-04-14 19:23 UTC by kara

We were previously delaying creation of bound text nodes until their values were known, so we could create them with the correct value (rather than creating, then setting value later). However, by the time values are known, other nodes have been created, so it's necessary to find the correct node to insert before. We found that this search process is actually slower than creating and setting separately. 

Creating text nodes eagerly and appending them in order shaves about 30% off render time for a large table of bound text nodes.

2018-04-14 19:27 UTC, mhevery approved these changes

2018-04-14 19:32 UTC, mary-poppins commented
You can preview b671a80 at https://pr23386-b671a80.ngbuilds.io/.

2018-04-14 19:37 UTC, kara commented
[presubmit](http://test/OCL:192902562:BASE:192902555:1523734559218:910f8dde)

2018-04-14 19:58 UTC, mary-poppins commented
You can preview 1d2036c at https://pr23386-1d2036c.ngbuilds.io/.

2018-04-15 14:42 UTC, mhevery requested changes
test

2018-04-15 14:42 UTC, mhevery approved these changes

2018-04-15 23:49 UTC, IgorMinar approved these changes

2018-04-16 00:17 UTC, vicb submitted a review, later dismissed
see inline comments

2018-04-16 16:46 UTC, mary-poppins commented
You can preview 6467400 at https://pr23386-6467400.ngbuilds.io/.

2018-04-17 20:50 UTC, closed without merging