feat(forms): provide options on push, insert, removeAt, and setControl
angular/angular pull request #23393
Opened 2018-04-16 11:18 UTC by davinkevin

This modification allows to give the standard options `{onlySelf: boolean, emitEvent: boolean}` to each of those method. This can be used to modify an FormArray without notifying the parent if needed. The standard behavior is still the same after this modification.

Closes #23336

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Issue Number: #23336

## What is the new behavior?

We are now able to give an `options` object as last parameters on `push`, `insert`, `removeAt` and `setControl` of a `FormArray`

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

I hope I haven't forget something... 😉

2018-04-17 06:38 UTC, davinkevin commented
The build failed due to the evolution of the API. Do I have something to do to make the build pass?

2018-05-03 22:25 UTC, kara commented
@davinkevin You'll need to run the bazel task to update the golden file:

```
bazel run //tools/public_api_guard:forms_forms_api.accept
```

2018-05-03 22:32 UTC, kara requested changes
Looks good, but duplicate tests need to be removed and the public-api file needs to be updated.

2018-05-03 22:32 UTC, kara commented on packages/forms/test/form_array_spec.ts
> +      it('should emit valueChange for pushing', () => {
This looks like a dupe of the test on line 87, no?

2018-05-03 22:32 UTC, kara commented on packages/forms/test/form_array_spec.ts
> +      it('should emit valueChange for removing', () => {
Dupe of test at line 96?

2018-05-03 22:32 UTC, kara commented on packages/forms/test/form_array_spec.ts
> +      it('should emit valueChange for inserting', () => {
Dupe of test at line 108?

2018-05-04 03:26 UTC, davinkevin commented on packages/forms/test/form_array_spec.ts
> +      it('should emit valueChange for pushing', () => {
For those 3, it isn't a duplicate but a bad copy/paste of the test name. Should have been `should emit statusChange for pushing|removing|inserting`.

2018-05-04 03:27 UTC, davinkevin commented on packages/forms/test/form_array_spec.ts
> +      it('should emit valueChange for removing', () => {
For those 3, it isn't a duplicate but a bad copy/paste of the test name. Should have been `should emit statusChange for pushing|removing|inserting`.

2018-05-04 03:27 UTC, davinkevin commented on packages/forms/test/form_array_spec.ts
> +      it('should emit valueChange for inserting', () => {
For those 3, it isn't a duplicate but a bad copy/paste of the test name. Should have been `should emit statusChange for pushing|removing|inserting`.

2018-05-04 03:29 UTC, davinkevin commented
Modification made for the 3 tests badly named. The `bazel` command have been run, so it seems to be OK for me. Waiting for the CI.

@kara 👍

2018-05-04 03:43 UTC, kara commented on packages/forms/test/form_array_spec.ts
> +      it('should emit valueChange for removing', () => {
Ah, I see. Thanks for correcting!

2018-05-04 03:45 UTC, kara approved these changes
LGTM

2018-06-05 23:12 UTC, kara commented
@IgorMinar Public API review?

2018-06-05 23:14 UTC, kara requested changes
One more thing!

2018-06-05 23:14 UTC, kara commented on packages/forms/src/model.ts
>     */
Can you update the API docs so they explain what the options mean for each of these?

2018-06-06 18:29 UTC, davinkevin commented on packages/forms/src/model.ts
>     */
Done, I've used the same explanation used on other methods in the same object. I hope that will match your expectation 😊

Thanks

2018-06-06 18:32 UTC, kara approved these changes
LGTM.

2018-06-06 18:32 UTC, kara commented on packages/forms/src/model.ts
> +   * to be emitted. This defaults to false
`false` -> `false.`

2018-06-06 18:40 UTC, davinkevin commented on packages/forms/src/model.ts
> +   * to be emitted. This defaults to false
Well seen!

Modification done 👍

2018-06-13 00:34 UTC, IgorMinar requested changes
I have a concern about this change. It seems that we are trying to suppress notifications about state changes just because we don't want to trigger change notifications to be delivered to the very same code that caused the state change to occur.

This approach makes a dangerous assumption that no other code is subscribed to the same observable. If someone else is listening, they'll never hear about the form being updated.

I suggest that rather than adding an api that suppresses the notifications in the forms, we come up with a pattern that would allow for one subscriber to ignore a notification if the subscriber is also causing a mutation within the same form it's subscribed to.

The simplest one I can think of is if your app uses the valueChanges observable to drive things in the app, then refactor it to drive all the changes that depend on the form value state. If an forms observable is how you pick up changes that happen to the form, then write the rest of the code to derive its state from this observable. In the case of redux store mentioned in the original issue, it seems to me that both reducer and the forms observable are trying to be the source of truth for some form state changes and they are coliding. Why not let the reducer just update the form, and then once the form is updated, pick up the form state and update the redux store via the action fired from the observable rather than via the original reducer?

I also suspect that this problem is not specific to forms. For example router users can run into the same problem where a code both listens to route/location changes and causes a navigation (or redirect) to occur. @jasonaden might want to weight in on how to handle these. 

(and yes, I realize that some of the forms apis use these flags to suppress notifications. I suspect that that's not right, but I don't know how/why that was added. we should discuss this change more before we potentially make the current problem worse via this api addition).

2018-06-16 13:51 UTC, davinkevin commented
@robwormald I've fixed the documentation you highlight in the code review.

> In the case of redux store mentioned in the original issue, it seems to me that both reducer and the forms observable are trying to be the source of truth for some form state changes and they are coliding

We are simply using the form API in our component and we are using the `valueChanges` observable to reflect the modification made in the form into our store. But our store can be modified from 'outside', so when its value changes, we want to reflect it in our component without `emitting` back this modification. 

BTW, I may be wrong, but this seems to be the only solution to use the form API, the redux store, and the redux dev-tools? 

I think this is a complex problem to explain without a code example, so I will try to provide a stack-blitz example as soon as possible (I'm currently working on an Angular presentation for VoxxedDays Luxembourg 😅).

/cc @fttriquet : if you can provide this stack-blitz example, it's welcomed!

2018-06-26 14:23 UTC, rysilva commented
I hope it's OK for me to add to this discussion on the PR. I came here looking for this behavior and here are my thoughts:

I agree with Igor that when we have a circular chain causing an endless loop it's often a reason to reconsider the design. I've occasionally encountered this problem in many frameworks. Back in the BackboneJS days we solved this by passing an options object with the event (`{ triggeredBy: this }`) which allowed listeners to ignore the event. I think this is more in line with what Igor was recommending, but I'm not sure how it could be done today in Angular with FormControl's EventEmitter.

Here is the problem I had: I had a component which maintained both internal and external FormArrays (the external gets mapped to the internal, which the template renders). When internal changes (add/remove/update), we update external's value. If something from the outside updates the external value, we need to react to that and reset our internal value. When we subscribe to changes from the outside we don't know if they were caused by ourselves or not.

I solved this problem when I realized FormArray was the wrong structure. You can't call `setValue` on a FormArray with a different number of items (think of a form component with rows that can be added/removed. Removing items--remove FormArray elements--then resetting the form will cause an error). It should be a FormControl with an array value. If it's a FormControl, then my component can implement `ControlValueAccessor` instead of being passed a FormArray. Then I don't subscribe to the FormArray value, I implement `writeValue` which is not called when I internally call the onChange handler. Thus there is no loop.

Essentially, the way the ControlValueAccessor is designed allows it to automatically ignore events that were caused by calling its own `onChange` function. Perhaps there's some way to bake that in?

As a very crude example:
```
formControl.registerOnChange(
  function onChange(value) { 
    /* called when value changes, unless change was  triggered by the below function */ 
  },
  function registerSetValue(setValue) {
    /* ... */
    setValue(val); // this won't call our onChange function
  }
)
```

2018-07-03 10:38 UTC, davinkevin commented
I'm totally agree with @rysilva about complexity but I've tried to align APIs on different kind of Control in this PR. 

> It should be a FormControl with an array value.

In your case, you have to add an extra layer of complexity (with ControlValueAccessor) and I think you are loosing the power of FormControl on each elements of your array? In our case, we have to handle complex validation for each line...

You can see here an example of code presenting our problem. It's fairly simple but it represent a formArray which can be updated from 'inside' (the comp) and from 'outside' (the store). 

[Example on Stack-Blitz](https://stackblitz.com/github/davinkevin/angular-ngrx-with-form/)

If you want to drop this PR, I'm fine with it, but it would be great to have an advice on how we should do that 😊.

2018-09-14 11:33 UTC, davinkevin commented
Any news about this PR? If no, we can close it (sadly...)

2018-11-06 17:04 UTC, Spawnrad commented
Any news about this PR?

2018-11-09 10:01 UTC, davinkevin commented
Not a the moment... I think this should be closed if the Angular team thinks this isn’t a good idea. 
But, I still think this problem remain open

2019-01-27 12:49 UTC, moniuch commented
Not sure why being able to suppress emitting event would be of concern. I use it extensively when construting forms dynamically, such as from API data. It is part of API and works like a charm. I can control what is happening in my form.

I can see two different scenarios where `emitEvent` would be desirable or unwanted.

1. **Desired**: A UI where user has ability to create another control/group for their immediate use - such as another type of postal address on a contact form. Pushing this member to an array should have an immediate effect in the `form.value` and in existing subscriptions to `valueChanges`. This is where `emitEvent` should definitely kick in.

2. **Unwanted**: When dynamically constructing a form (such as form API response, especially at every subsequent response) - developer would like to suppress emitting of the event while pushing the newly parsed members in a loop.[ This stackblitz has an example.](https://stackblitz.com/edit/angular-formarray-emitevent?file=src%2Fapp%2Fapp.component.ts)

Of course, we **do** have a workaround - one could introduce a `construction: boolean` flag and filter `valueChanges` accordingly. One could also unsubscribe and resubscribe to that FormArray. How much simpler though, and at the same time consistent with the existing API, would it be to use `emitEvent` in case 2.

Why has `emitEvent` been introdued at all? Wasn't that to help developer be in control?

@IgorMinar

2019-10-01 14:23 UTC, Thenis commented
Any update on this? It really introduces difficulties when dealing with dynamic forms

2020-07-09 15:14 UTC, szymonlacki commented
You can work around it. For example, create your own flag. E.g
![image](https://user-images.githubusercontent.com/37595359/87057617-60a1d680-c207-11ea-8be8-95547f72ca1a.png)
and then filter your stream:
![image](https://user-images.githubusercontent.com/37595359/87057821-a3fc4500-c207-11ea-9a10-77da8f6e9a1e.png)

2020-08-25 08:52 UTC, sdahlberg commented
Shouldn't this include the `clear` function?

2020-08-25 11:31 UTC, Totati commented
> 2. **Unwanted**: When dynamically constructing a form (such as form API response, especially at every subsequent response) - developer would like to suppress emitting of the event while pushing the newly parsed members in a loop.[ This stackblitz has an example.](https://stackblitz.com/edit/angular-formarray-emitevent?file=src%2Fapp%2Fapp.component.ts)
> 
> @IgorMinar

This could be solved, if the push could accept a spread array of `AbsctractControl`s as `Array.prototype.push()` can.

2020-11-24 08:48 UTC, astukanov commented
HI @kara @davinkevin I have to strongly agree with @moniuch. The same concern borught up bu @IgorMinar could be applied to any other form group being changed, where we have the functionality to ignore the event. 
In my case I want to be able to have the logic (pre-calculation) being done server side and slight adjustments to it still being possible in frontend, with validation. 
For the time being I receive initial data from the server I don't want to emit any change event, as it will trigger the retrieval of data again. After any change, events have to be triggered in order to adjust further parts of the application. 
Of course there are possibilities to work around it, but it pains me to do so when the solution would be a simple one. Please reconsider adding this functionality. 
It won't brake anything and in my opinion it is better to have a solution for 95% of the problems right now, and maybe work on edge cases which @IgorMinar pointed out when obviously needed, than just leave it as is and having those 95% struggling  for no reason.

2020-12-10 22:15 UTC, rimendoz86 commented
I have to not use removeAt and instead splice the control and then updateValueAndValidity({ emitEvent: false });

:// would be nice/safer to be able to do that through an optional param.

2021-02-01 06:32 UTC, AndrewKushnir commented
Closing this PR in favor of #31031.

2021-02-01 06:32 UTC, closed without merging