test(ivy): add html tp ivy ast transformer tests
angular/angular pull request #23546
Opened 2018-04-25 18:39 UTC by vicb

A few TODO to address in a follow up PR

2018-04-25 18:45 UTC, vicb commented
http://test/OCL:194273559:BASE:194273575:1524681894215:ef78aa35

2018-04-25 21:14 UTC, mary-poppins commented
You can preview e55adf9 at https://pr23546-e55adf9.ngbuilds.io/.

2018-04-25 23:52 UTC, mary-poppins commented
You can preview 8d81813 at https://pr23546-8d81813.ngbuilds.io/.

2018-04-25 23:57 UTC, vicb commented on packages/compiler/test/expression_parser/utils/BUILD.bazel
> +load("@build_bazel_rules_nodejs//:defs.bzl", "jasmine_node_test")
@alexeagle I guess I can remove that together with `, "ts_web_test"` on the line above ?

2018-04-26 00:57 UTC, mary-poppins commented
You can preview 3b5f3fd at https://pr23546-3b5f3fd.ngbuilds.io/.

2018-04-26 16:51 UTC, mary-poppins commented
You can preview e56b761 at https://pr23546-e56b761.ngbuilds.io/.

2018-04-26 18:00 UTC, alexeagle approved these changes
Bazel changes LGTM

2018-04-27 22:27 UTC, mary-poppins commented
You can preview ad3bd16 at https://pr23546-ad3bd16.ngbuilds.io/.

2018-04-27 23:33 UTC, mary-poppins commented
You can preview 2902f82 at https://pr23546-2902f82.ngbuilds.io/.

2018-04-28 00:52 UTC, vicb commented
http://test/OCL:194273559:BASE:194618618:1524876693731:9385c1d4

2018-04-28 14:14 UTC, vicb commented
Ready to be merged after review

2018-05-07 12:48 UTC, ocombe approved these changes

2018-05-07 12:48 UTC, ocombe commented on packages/compiler/src/aot/compiler.ts
> +            context, directiveMetadata, ivy.nodes, ivy.hasNgContent, ivy.ngContentSelectors,
why not pass an `IvyParseResult` instead of `ivy.nodes, ivy.hasNgContent, ivy.ngContentSelectors` ?

2018-05-07 12:48 UTC, ocombe commented on packages/compiler/src/expression_parser/ast.ts
>  export class BoundElementProperty {
shouldn't you rename this as well if you rename `BoundElementBindingType`?

2018-05-07 12:48 UTC, ocombe commented on packages/compiler/test/render3/mock_compile.ts
> +                  outputCtx, directive, ivy.nodes, ivy.hasNgContent, ivy.ngContentSelectors,
you could pass an `IvyParseResult` here as well, instead of ivy.nodes, ivy.hasNgContent, ivy.ngContentSelectors ?

2018-05-07 17:15 UTC, vicb commented on packages/compiler/src/aot/compiler.ts
> +            context, directiveMetadata, ivy.nodes, ivy.hasNgContent, ivy.ngContentSelectors,
Good idea, will do

2018-05-07 17:26 UTC, mary-poppins commented
You can preview b87e10f at https://pr23546-b87e10f.ngbuilds.io/.

2018-05-08 17:07 UTC, alxhub requested changes

2018-05-08 17:57 UTC, mary-poppins commented
You can preview f6aa20c at https://pr23546-f6aa20c.ngbuilds.io/.

2018-05-08 22:46 UTC, vicb commented
http://test/OCL:194273559:BASE:195889302:1525819571999:dcade5b9

2018-05-08 22:54 UTC, mary-poppins commented
You can preview f7091cf at https://pr23546-f7091cf.ngbuilds.io/.

2018-05-09 18:42 UTC, vicb commented
Travis is red because of the Saucelabs build.

2018-05-09 18:50 UTC, closed without merging