docs: add doc to include updates to the index.html with the new ng add command
angular/angular pull request #23616
Opened 2018-04-30 17:28 UTC by chembu

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently, the doc does not have content that explains updates to the index.html with the `ng add  @angular/pwa` command.
Issue Number: 23373

## What is the new behavior?
Added doc to explain the updates to index.html file with the `ng add  @angular/pwa` command

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-04-30 17:37 UTC, mary-poppins commented
You can preview 0660306 at https://pr23616-0660306.ngbuilds.io/.

2018-04-30 19:03 UTC, Brocco approved these changes
LGTM

2018-04-30 22:09 UTC, mary-poppins commented
You can preview a96507d at https://pr23616-a96507d.ngbuilds.io/.

2018-04-30 23:06 UTC, jenniferfell requested changes
Please clarify which "installed PWA" because we haven't used that phrase in these docs before. Other comments are optional, but while you're here... :-)

2018-04-30 23:06 UTC, jenniferfell commented on aio/content/guide/service-worker-getting-started.md
> +5. Installs icon files to support the installed Progressive Web App (PWA).
Unclear reference: We've never mentioned "the installed Progressive Web App (PWA)" using that phrase before. Is this the app/project to which we're currently adding service worker support? 

And I don't think we've been clear in the past about what icon file we're adding any why.  What's the icon file for? Also....as a developer, I might wonder why you're adding icon files to my app? Is this the file we're talking about: favicon.ico?

2018-04-30 23:06 UTC, jenniferfell commented on aio/content/guide/service-worker-getting-started.md
> +6. Creates the service worker configuration file called `ngsw-config.json` which specifies the caching behaviors and other settings.
Missing comma: Creates the service worker configuration file called `ngsw-config.json`, which specifies the caching behaviors and other settings. 

Also...maybe add a link from this filename to the doc file about config options?

2018-05-01 00:16 UTC, chembu commented on aio/content/guide/service-worker-getting-started.md
> +    * Adds meta tags for `theme-color`.
I checked with him and he confirmed that the Description meta tag is not added.

2018-05-01 16:52 UTC, mary-poppins commented
You can preview 759bd8f at https://pr23616-759bd8f.ngbuilds.io/.

2018-05-01 22:33 UTC, jenniferfell approved these changes

2018-05-01 22:34 UTC, jenniferfell commented
I still think we can be more clear about this item:
"Installs icon files to support the installed Progressive Web App (PWA)."

But we can come back as necessary if others are confused. Nothing technically incorrect or missing.

2018-05-01 22:35 UTC, jenniferfell commented
@IgorMinar Hi. The essentials have been updated. With a pull-approve member approval, I think we can merge.

2018-05-02 22:18 UTC, IgorMinar approved these changes

2018-05-02 22:19 UTC, closed without merging