DOCS add event-manager API doc
angular/angular pull request #23656
Opened 2018-05-02 21:49 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number:  #21146

## What is the new behavior?
doc added

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Closed previous PR, too old to sync. Needs new review.

2018-05-02 21:58 UTC, mary-poppins commented
You can preview 5f23736 at https://pr23656-5f23736.ngbuilds.io/.

2018-05-02 22:10 UTC, petebacondarwin requested changes
I would try to remove all the `@description` and `{@link}` usage.
I noted a few content issues, that you may want to consider.

2018-05-02 22:10 UTC, petebacondarwin commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> + * Supported HammerJS recognizer event names.
Perhaps a link to what a HammerJS recognizer is would be helpful here?

2018-05-02 22:10 UTC, petebacondarwin commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> + * DI token for providing {@link http://hammerjs.github.io/ HammerJS} support to Angular.
It is actually preferable not to use `{@link ... }` for external links any more.
(I am trying to get rid of this inline jsdoc tag altogether)
It is cleaner (and works better with markdown syntax highlighting etc) if you just did:

```
 DI token for providing [HammerJS](http://hammerjs.github.io/) support to Angular.
```

2018-05-02 22:10 UTC, petebacondarwin commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> + * @see  {@link HammerGestureConfig HammerGestureConfig}
No need for `{@link ... }` here . Just putting the API item in backticks should be enough to turn it into a link:

```
@see `HammerGestureConfig`
```

2018-05-02 22:10 UTC, petebacondarwin commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> +   * @param element The element that will recognize gestures.
Does the element recognize gestures? Or is it just the source of the gesture?

2018-05-02 22:10 UTC, petebacondarwin commented on packages/platform-browser/src/dom/events/key_events.ts
> +   * Initializes an instance of the key-event management service.
Is "management service" accurate? Isn't this initializing a key-event plugin?

2018-05-02 22:10 UTC, petebacondarwin commented on packages/platform-browser/src/dom/events/key_events.ts
> +    * @param element The HTML element to receive event notifications.
Does the element receive or trigger events?

2018-05-02 22:10 UTC, petebacondarwin commented on packages/platform-browser/src/dom/events/key_events.ts
> +    */
Missing `@returns`?

2018-05-02 22:10 UTC, petebacondarwin commented on packages/platform-browser/src/dom/events/key_events.ts
> +   * @param zone The zone in which the event occurred.
Missing `@returns`?

2018-05-02 22:27 UTC, petebacondarwin commented on packages/platform-browser/src/dom/events/event_manager.ts
> + export const EVENT_MANAGER_PLUGINS =
pretty sure this should not be indented.

2018-05-02 22:27 UTC, petebacondarwin commented on packages/platform-browser/src/dom/events/event_manager.ts
> +@Injectable()
And this.

2018-05-02 22:27 UTC, petebacondarwin commented on packages/platform-browser/src/dom/events/event_manager.ts
> +  *
Why add this empty comment?

2018-05-02 22:27 UTC, petebacondarwin commented on packages/platform-browser/src/dom/events/event_manager.ts
> +  /**
Should there be an empty line before this comment?

2018-05-02 22:30 UTC, jbogarthyde commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> + * Supported HammerJS recognizer event names.
They don't explain what it is or define it in their doc. Perhaps @vicb can define it?

2018-05-02 22:31 UTC, jbogarthyde commented on packages/platform-browser/src/dom/events/event_manager.ts
> + * @description An injectable service that provides event management in the browser.
Added a minimal statement - @vicb, can you provide more context?

2018-05-02 22:34 UTC, jbogarthyde commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> +   * @param element The element that will recognize gestures.
I don't know. @vicb ?

2018-05-02 22:35 UTC, mary-poppins commented
You can preview bf16706 at https://pr23656-bf16706.ngbuilds.io/.

2018-05-02 22:35 UTC, jbogarthyde commented on packages/platform-browser/src/dom/events/key_events.ts
> +   * Initializes an instance of the key-event management service.
I think you're right, but I also think this file is not getting into the doc at all.

2018-05-02 22:52 UTC, mary-poppins commented
You can preview ceffc05 at https://pr23656-ceffc05.ngbuilds.io/.

2018-05-02 22:56 UTC, mary-poppins commented
You can preview c26b27c at https://pr23656-c26b27c.ngbuilds.io/.

2018-05-03 15:55 UTC, jbogarthyde commented on packages/platform-browser/src/dom/events/key_events.ts
> +    * @param element The HTML element to receive event notifications.
I don't know either, but this is not getting into the doc. Removing comments.

2018-05-08 18:18 UTC, mary-poppins commented
You can preview 375bb09 at https://pr23656-375bb09.ngbuilds.io/.

2018-05-08 18:55 UTC, mary-poppins commented
You can preview f9c57ba at https://pr23656-f9c57ba.ngbuilds.io/.

2018-05-10 21:47 UTC, IgorMinar approved these changes
lgtm except for a few small nits

2018-05-10 21:47 UTC, IgorMinar commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> +   * @description A set of supported event names for gestures to be used in Angular.
the @description tag is not necessary in this case

2018-05-10 21:47 UTC, IgorMinar commented on packages/platform-browser/src/dom/events/event_manager.ts
> +   * Registers a handler for a specific element and event.
could we add a blank line that separates the description from params? the blank line makes the doc block easier to read in the source form and doesn't affect the presentation on angular.io. thanks!

2018-05-10 21:47 UTC, IgorMinar commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> +
please remove this blank line. by convention the docs block should be attached to the prop declaration.

2018-05-10 21:56 UTC, jbogarthyde commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> +
corrections made

2018-05-10 22:01 UTC, mary-poppins commented
You can preview 58830de at https://pr23656-58830de.ngbuilds.io/.

2018-05-10 22:06 UTC, mary-poppins commented
You can preview a9e68f2 at https://pr23656-a9e68f2.ngbuilds.io/.

2018-05-14 16:14 UTC, petebacondarwin approved these changes

2018-05-17 18:03 UTC, mary-poppins commented
You can preview a26db46 at https://pr23656-a26db46.ngbuilds.io/.

2018-05-17 18:06 UTC, mary-poppins commented
You can preview dc81601 at https://pr23656-dc81601.ngbuilds.io/.

2018-05-22 21:34 UTC, closed without merging