fix(aio): only do search when the current query is different than the last
angular/angular pull request #23711
Opened 2018-05-04 15:35 UTC by HVND

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The search box is searching when the current query is the same than the last.

## What is the new behavior?
Only do search when the current query is different than the last.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-05-05 12:00 UTC, gkalpak requested changes

2018-05-05 12:00 UTC, gkalpak commented on aio/src/app/search/search-box/search-box.component.ts
> +  @Output() onSearch = this.searchSubject.pipe(debounceTime(this.searchDebounce), distinctUntilChanged());
Can you explain what this fixes? Why didn't it work as expected before?
Also, how come no tests need to be changed/added?

2018-05-21 15:27 UTC, petebacondarwin commented on aio/src/app/search/search-box/search-box.component.ts
> +  @Output() onSearch = this.searchSubject.pipe(debounceTime(this.searchDebounce), distinctUntilChanged());
The only thing I can think is if you type something, change it quickly and then go back to what you had previously - all during the debounce period you would get two requests... For example:

```
--1--2--1--
[distinctUntilChanged]
--1--2--1--
[debounce]{300ms}
--1-----1--
```
<img width="1135" alt="screen shot 2018-05-21 at 16 25 29" src="https://user-images.githubusercontent.com/15655/40315555-9c42e00e-5d13-11e8-9f57-a089bc4a8da6.png">


```
--1--2--1--
[debounce]{300ms}
--1--------
[distinctUntilChanged]
--1--------
```

<img width="1082" alt="screen shot 2018-05-21 at 16 27 13" src="https://user-images.githubusercontent.com/15655/40315636-d7f0244a-5d13-11e8-874b-d859d935e28d.png">

2018-05-21 15:28 UTC, petebacondarwin commented on aio/src/app/search/search-box/search-box.component.ts
> +  @Output() onSearch = this.searchSubject.pipe(debounceTime(this.searchDebounce), distinctUntilChanged());
But I agree that this would need unit tests to prove what it was fixing and a more clear commit message.
@HVND do you have time to add these?

2018-05-21 15:29 UTC, petebacondarwin requested changes
@HVND Please see comments above.

2020-11-10 14:20 UTC, petebacondarwin commented
Closing as this PR is old, stale and has not had any updates for a long time.

2020-11-10 14:20 UTC, closed without merging