docs(aio): add cross field validation section to form validation chapter at aio
angular/angular pull request #23743
Opened 2018-05-07 11:17 UTC by zetsnotdead

## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

## PR Type

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Issue Number: #23182 

## What is the new behavior?
Add cross field validation section to form validation chapter at angular.io. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2018-05-08 19:35 UTC, jenniferfell commented
@zetsnotdead Thanks!

@brandonroberts @kara When you get a chance, if you could take a look at this PR, that would be most spiffy. I'll take a read for editorial style, and I'll entrust the technical accuracy and positioning to you. Thanks!

2018-05-14 15:03 UTC, mary-poppins commented
You can preview 4fa78d7 at https://pr23743-4fa78d7.ngbuilds.io/.

2018-05-31 23:14 UTC, kara requested changes
Thanks for adding the section!  Looks good. My primary feedback is that it should be shortened to keep the guide focused.

2018-05-31 23:14 UTC, kara commented on aio/content/guide/form-validation.md
> +Identity validator implements the `ValidatorFn` interface. It takes an Angular control object as an argument and returns either null if the form is valid, or ValidationErrors otherwise.
ValidationErrors -> `ValidationErrors`

2018-05-31 23:14 UTC, kara commented on aio/content/guide/form-validation.md
> +If the values do not match the hero's identity remains disguised, and we can safely return null. Otherwise, the hero's identity is revealed and we must mark the form as invalid by returning an error
> If the values do not match, the hero's identity remains secret, and we can safely return null.

2018-05-31 23:14 UTC, kara commented on aio/content/examples/form-validation/src/app/shared/identity-revealed.directive.ts
> +  return name && alterEgo && name.value !== alterEgo.value ? null : { 'identityRevealed': { value: true } };
Think we can simplify the error to just `{identityRevealed: true}`.

2018-05-31 23:14 UTC, kara commented on aio/content/guide/form-validation.md
> +<code-example path="form-validation/src/app/reactive/hero-form-reactive.component.ts" region="cross-validation-register" title="reactive/hero-form-template.component.ts" linenums="false">
We already added the validator in line 237; don't think it's necessary to do twice.

2018-05-31 23:14 UTC, kara commented on aio/content/guide/form-validation.md
> +Finally, we want to style the `input` elements to give visual feedback about form control's validity. Unfortunately, the `identityRevealed` error is on the form group control (`heroForm`) and not on
I think styling is outside the scope of this validation guide (which is already pretty long). Remove the rest of this section (until "Adding to template driven forms")? We can keep the code in the final example but I don't think it needs an extended explanation.

2018-05-31 23:14 UTC, kara commented on aio/content/guide/form-validation.md
> +First we must create a directive that will wrap the validator function. We provide it as the validator using the `NG_VALIDATORS` token. If you are not sure why, or you do not fully understand the syn
or you do not fully understand the syntax revisit -> or you do not fully understand the syntax, revisit

2018-05-31 23:14 UTC, kara commented on aio/content/guide/form-validation.md
> +Finally, we want to style the `input` elements to give visual feedback about form control's validity. Unfortunately, the `identityRevealed` error is on the form group control (`heroForm`) and not on
Again, styling is outside the scope of this guide. Let's remove the rest of this section.

2018-06-04 09:53 UTC, mary-poppins commented
You can preview 72cac7a at https://pr23743-72cac7a.ngbuilds.io/.

2018-06-05 08:00 UTC, zetsnotdead commented
Thank you for the review  :smile: I've updated the PR with all the requested changes.

2018-06-05 13:54 UTC, brandonroberts requested changes

2018-06-05 22:52 UTC, kara commented on aio/content/guide/form-validation.md
> +Next, we have to add the directive to the html template. Since the validator must be registered at the `FormGroup` level, we put the directive on the `form` tag.
Template-driven forms also have a `FormGroup` internally, but I agree that it's not clear from this sentence. Maybe add a bit more to clarify that point?

2018-06-05 22:57 UTC, kara reviewed
Super close, just some nits

2018-06-05 22:57 UTC, kara commented on aio/content/guide/form-validation.md
> +Notice that the name and alterEgo are sibling controls. To evaluate both controls in a single custom validator, we should perform the validation in a common ancestor control: the FormGroup. That way,
All the references to `FormGroup` should be wrapped in backticks

2018-06-05 22:57 UTC, kara commented on aio/content/guide/form-validation.md
> +Identity validator implements the `ValidatorFn` interface. It takes an Angular control object as an argument and returns either null if the form is valid, or `ValidationErrors` otherwise.
Identity validator -L> The identity validator

2018-06-05 22:57 UTC, kara commented on aio/content/examples/form-validation/src/app/shared/identity-revealed.directive.ts
> +  return name && alterEgo && name.value !== alterEgo.value ? null : { 'identityRevealed': true };
Can we flip the ternary? It's hard to scan what the opposite of !== is.

```ts
  return name && alterEgo && name.value === alterEgo.value ? { 'identityRevealed': true } : null;
```

2018-06-06 08:32 UTC, mary-poppins commented
You can preview dba4d17 at https://pr23743-dba4d17.ngbuilds.io/.

2018-06-06 08:41 UTC, zetsnotdead commented on aio/content/guide/form-validation.md
> +Next, we have to add the directive to the html template. Since the validator must be registered at the `FormGroup` level, we put the directive on the `form` tag.
Apart from this one, I've made all the suggested changes. How should this be worded?

2018-06-06 17:04 UTC, brandonroberts commented on aio/content/guide/form-validation.md
> +Next, we have to add the directive to the html template. Since the validator must be registered at the `FormGroup` level, we put the directive on the `form` tag.
What about `Since the validator must be registered at the highest level in the form, ...`

2018-06-11 12:37 UTC, mary-poppins commented
You can preview b42eea7 at https://pr23743-b42eea7.ngbuilds.io/.

2018-06-11 12:59 UTC, zetsnotdead commented
@brandonroberts @kara Thanks again for the review :+1: Is there anything else I should change?

2018-06-19 23:09 UTC, jenniferfell commented
@zetsnotdead Hi. Thanks for all your work on this. We haven't forgotten. :-) Your PR changes are in the review stack for our current sprint. Thanks again! (and thanks for your patience as we build better habits and workflow on our side so things don't sit so long in the future)

2018-06-22 12:27 UTC, brandonroberts approved these changes

2018-06-22 12:30 UTC, brandonroberts commented
Changes LGTM. Final approval will need to be added by Kara or someone else in the forms group

2018-06-25 15:09 UTC, mhevery commented
I can approve, but were @kara`s comments addressed?

2018-06-25 15:45 UTC, brandonroberts commented
@mhevery yes, her comments were addressed.

2018-06-25 18:03 UTC, kara approved these changes
LGTM

2018-06-26 18:04 UTC, closed without merging