feat(ivy): add support of ApplicationRef.bootstrapModuleFactory
angular/angular pull request #23811
Opened 2018-05-09 23:51 UTC by jasonaden

2018-05-10 00:02 UTC, mary-poppins commented
You can preview 9d8aa90 at https://pr23811-9d8aa90.ngbuilds.io/.

2018-05-10 00:16 UTC, mhevery requested changes

2018-05-10 00:16 UTC, mhevery commented on packages/core/src/di/injector.ts
> +      // Intentionally left behind to help in dev mode
Could you add more detailed text.

`Intentionally left behind: With dev tools open the debugger will stop here. There is no reason why correctly written  application should cause this exception.`

2018-05-10 00:16 UTC, mhevery commented on packages/core/src/di/r3_injector.ts
>   * @experimental
I know this was not changed by you, but we should leave the code in better state than we found it. Could you add detailed documentations for this methods since it is be public. See: https://angular.io/api/core/createInjector

also add docs for the `additionalProviders`

2018-05-10 00:16 UTC, mhevery commented on packages/core/src/di/r3_injector.ts
> +    } else {
We need unit tests for this change. The bug was that having more than one multi provider would cause an error and it was not possible to retrieve the array of providers.

2018-05-10 00:16 UTC, mhevery commented on packages/core/src/render3/component_ref.ts
> +  const array: {propName: string; templateName: string;}[] = [];
can we have unit test for this? We have to make sure that the minified and non minified name are correctly mapped. You can use `@Input('unminifiedName') minifiedName: string` as a simulation if the names propagate correctly.

2018-05-10 00:16 UTC, mhevery commented on packages/core/src/render3/component_ref.ts
> +export const SCHEDULER = new InjectionToken<((fn: () => void) => void)>(
This will eventually become public API, we need descriptive docs.

2018-05-10 00:16 UTC, mhevery commented on packages/core/src/render3/component_ref.ts
> +export class ComponentFactory<T> extends viewEngine_ComponentFactory<T> {
This file seems to missing some comments, and maybe TODOs of what needs to be implemented later.

2018-05-10 00:16 UTC, mhevery commented on packages/core/src/render3/ng_module_ref.ts
> +    assertDefined(
needs `ngDevMode && `  Maybe even better to refactor to `ngDevMode && assertModuleType(ngModuleType)`

2018-05-10 00:16 UTC, mhevery commented on packages/core/src/render3/ng_module_ref.ts
> +    assertDefined(this.destroyCbs, 'NgModule already destroyed');
`ngDevMode && `

2018-05-10 00:16 UTC, mhevery commented on packages/core/src/render3/ng_module_ref.ts
> +    assertDefined(this.destroyCbs, 'NgModule already destroyed');
`ngDevMode && `

2018-05-10 00:16 UTC, mhevery commented on packages/core/test/render3/application_ref_integration_spec.ts
> +fdescribe('ApplicationRef bootstrap', () => {
`fdescribe`

2018-05-10 02:52 UTC, trotyl commented on packages/platform-browser/src/browser.ts
> +  constructor(@Optional() @SkipSelf() parentModule: BrowserModule|null) {
This will break JIT as TypeScript will only emit `Object`: https://github.com/Microsoft/TypeScript/issues/18509

2018-05-10 10:31 UTC, JoostK commented on packages/core/src/render3/component_ref.ts
> +    const componentTag = this.componentDef.selectors ![0] ![0] as string;
How is this different from `this.selector`?

2018-05-10 10:31 UTC, JoostK commented on packages/core/src/render3/component_ref.ts
> +    let component: T;
Can we move this declaration closer to the `try`-block, next to `elementNode`?

2018-05-10 10:31 UTC, JoostK commented on packages/core/src/render3/component_ref.ts
> +    assertDefined(this.destroyCbs, 'NgModule already destroyed');
Cool, this is finally implemented now 👍

2018-05-10 10:31 UTC, JoostK commented on packages/core/src/render3/interfaces/view.ts
> +   * RootComponents - The components which was instantiated by the call to
The components which **were** instantiated

2018-05-10 10:31 UTC, JoostK commented on packages/core/test/render3/application_ref_integration_spec.ts
> +          debugger;
debugger

2018-05-10 10:31 UTC, JoostK commented on packages/core/src/di/injector.ts
> +      // Intentionally left behind to help in dev mode
Given this is for debugging, I guess `if (ngDevMode) debugger;` would allow the statement to be elided in prod builds

2018-05-10 10:31 UTC, JoostK commented on packages/core/src/render3/component_ref.ts
> +      if (rendererFactory.end) rendererFactory.end();
Is it intentional that `end` is called after `leaveView`? This is asymmetric from the entering behavior, in which the view is first entered and then `renderFactory.begin` is called.

2018-05-10 10:31 UTC, JoostK commented on packages/core/src/render3/component_ref.ts
> +    assertDefined(this.destroyCbs, 'NgModule already destroyed');
As per @mhevery's comments, `ngDevMode &&`

2018-05-10 10:31 UTC, JoostK commented on packages/core/src/render3/component_ref.ts
> +    assertDefined(this.destroyCbs, 'NgModule already destroyed');
`ngDevMode &&`

2018-05-10 10:57 UTC, JoostK commented on packages/core/src/render3/component.ts
> +  const rootContext = createRootContext(opts.scheduler || requestAnimationFrame.bind(window));
This is probably the first step towards the new rendering infrastructure, in the future I'd expect we use `opts.injector.get(ROOT_CONTEXT)` here if `opts.injector` is provided?

2018-05-10 10:57 UTC, JoostK commented on packages/core/src/render3/component_ref.ts
> +    this.destroyCbs = null;
Probably for a separate PR: we'd need to remove ourselves from `RootContext.components` upon destroying the component.

2018-05-10 18:44 UTC, jasonaden commented on packages/core/src/core_render3_private_export.ts
> +  NgModuleFactory as ɵNgModuleFactory,
`NgModuleDef` is needed for the monkey patching in the integration spec (comment added to remove the export when we remove the monkey patching).

`NgModuleFactory` is directly being tested:

```
it('should bootstrap hello world', withBody('<hello-world></hello-world>', async() => {
  const MyAppModuleFactory = new NgModuleFactory(MyAppModule);
  const platform = platformBrowser();
  const moduleRef = await platform.bootstrapModuleFactory(MyAppModuleFactory);
...
```

2018-05-10 22:19 UTC, kara commented on packages/core/test/render3/application_ref_integration_spec.ts
> +       //  expect(helloWorldComponent.log).toEqual(['OnInit', 'DoCheck']);
I think we need to do 2 things to get this to work:

1) Make sure that `ApplicationRef.tick` is occurring at the correct level (above the root component - see my earlier comment).

2) Call `queueInitHooks` and `queueLifeycleHooks` somewhere. Currently, lifecycle hooks on the root component work with `renderComponent` because they are queued with a host feature called `LifecycleHooksFeature`. We can either add these function calls to `ComponentRef.create` directly (and accept that they won't be tree-shaken) or we can see if we can bootstrap modules with similar options / host features?

2018-05-10 22:25 UTC, kara commented on packages/core/src/render3/instructions.ts
> +  rootContext.components.forEach(rootComponent => {
`forEach` is usually slower than a regular for loop. Switch over?

2018-05-10 22:25 UTC, kara commented on packages/core/src/render3/ng_module_ref.ts
> +    this.destroyCbs !.forEach(fn => fn());
Replace with for loop? Or `addDestroyable`

2018-05-10 22:31 UTC, mhevery commented on packages/core/src/render3/ng_module_ref.ts
> +    return new NgModuleRef(this.moduleType, parentInjector);
I am not a fan of `addDestroyable` since it is code which has to run on each instance. We should have it run on the `prototype` exactly once.

2018-05-10 22:35 UTC, mhevery commented on packages/core/src/render3/component_ref.ts
> +    this.hostView = this.changeDetectorRef = new ViewRef(rootView, instance);
@kara yes, we were not sure how to do that, and so we kind of hacked it. Can you work with @jasonaden on adding a tests for it and making it pass.

2018-05-10 23:27 UTC, kara commented on packages/core/src/render3/component_ref.ts
> +      leaveView(oldView);
I think we might want `enterView(oldView, null)` here. `leaveView` will call `viewInit` hooks and set `creationMode` to false (which we don't want here because unlike in `renderComponent`, we haven't actually checked this view yet.

2018-05-11 00:02 UTC, kara commented on packages/core/src/render3/ng_module_ref.ts
> +    return new NgModuleRef(this.moduleType, parentInjector);
Okay, that's fair. Maybe we should consider removing it from `createViewRef` too then? (in a different PR)

2018-05-14 20:39 UTC, jasonaden commented on packages/core/src/render3/component_ref.ts
> +    this.injector = injector;
I prefer not to mix these syntaxes. Since we have several properties in the constructor that need to be manually instantiated, I find it more readable not to have the visibility on the constructor params.

2018-05-14 20:45 UTC, jasonaden commented on packages/core/src/render3/instructions.ts
> +  rootContext.components.forEach(rootComponent => {
I wanted to leave `forEach` for readability, but I could change it if we have to. It's most likely this is an array of small length, so execution time will be quite close either way.

2018-05-14 21:05 UTC, kara commented on packages/core/src/render3/component_ref.ts
> +    this.injector = injector;
Ok, fair enough :+1

2018-05-14 23:02 UTC, jasonaden commented on packages/core/src/render3/component_ref.ts
> +      leaveView(oldView);
👍

2018-05-16 20:34 UTC, mary-poppins commented
You can preview adda8bf at https://pr23811-adda8bf.ngbuilds.io/.

2018-05-21 16:47 UTC, mary-poppins commented
You can preview 48d3eb9 at https://pr23811-48d3eb9.ngbuilds.io/.

2018-06-01 13:09 UTC, marclaval commented
For information, this PR is needed to implement `ViewContainerRef.createComponent`. I'll do that when it lands.

2018-06-05 04:41 UTC, mhevery approved these changes

2018-06-05 18:38 UTC, jasonaden commented
[Presubmit](http://test/OCL:197813238:BASE:199331884:1528223895429:c5bc6404)

2018-06-06 01:50 UTC, mary-poppins commented
You can preview 13ac560 at https://pr23811-13ac560.ngbuilds.io/.

2018-06-06 03:09 UTC, vicb commented
force merging as the PR has approved by @mhevery recently

2018-06-06 05:14 UTC, vicb commented
breaks g3. Check #caretaker for the details.

2018-06-06 18:19 UTC, mary-poppins commented
You can preview 156c37c at https://pr23811-156c37c.ngbuilds.io/.

2018-06-06 18:22 UTC, jasonaden commented
Fixed the problem causing rollback. [Presubmit](http://test/OCL:197813238:BASE:199494736:1528308748077:31708210)

2018-06-07 17:22 UTC, mary-poppins commented
You can preview 5fc6923 at https://pr23811-5fc6923.ngbuilds.io/.

2018-06-07 20:16 UTC, closed without merging

2018-06-26 05:55 UTC, trotyl commented on packages/core/src/render3/component_ref.ts
> +    this.selector = componentDef.selectors[0][0] as string;
This is not compatible, current implementation would [provide raw selector string](https://stackblitz.com/edit/angular-737jcz?file=src%2Fapp%2Fapp.component.ts) rather than first element selector.