test doc for decorator and directive templates
angular/angular pull request #23902
Opened 2018-05-14 16:27 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Test doc for new templates: decorators, directives, maybe NgModules

2018-05-14 16:40 UTC, mary-poppins commented
You can preview ec5314b at https://pr23902-ec5314b.ngbuilds.io/.

2018-05-15 17:35 UTC, mary-poppins commented
You can preview cf4bc61 at https://pr23902-cf4bc61.ngbuilds.io/.

2018-05-15 18:34 UTC, mary-poppins commented
You can preview 52ad098 at https://pr23902-52ad098.ngbuilds.io/.

2018-05-16 00:06 UTC, mary-poppins commented
You can preview d72e7e8 at https://pr23902-d72e7e8.ngbuilds.io/.

2018-05-16 16:37 UTC, mary-poppins commented
You can preview def161a at https://pr23902-def161a.ngbuilds.io/.

2018-05-16 16:41 UTC, mary-poppins commented
You can preview ac03ac6 at https://pr23902-ac03ac6.ngbuilds.io/.

2018-05-16 17:07 UTC, mary-poppins commented
You can preview c83f4cc at https://pr23902-c83f4cc.ngbuilds.io/.

2018-05-16 18:30 UTC, IgorMinar submitted a review, later dismissed

2018-05-16 18:30 UTC, IgorMinar commented on packages/core/src/metadata/directives.ts
>    /**
reviewed only up to here, but I'm posting the comments I have so far..

2018-05-17 16:00 UTC, mary-poppins commented
You can preview a3b8fdb at https://pr23902-a3b8fdb.ngbuilds.io/.

2018-05-17 20:03 UTC, mary-poppins commented
You can preview fb9698e at https://pr23902-fb9698e.ngbuilds.io/.

2018-05-18 05:32 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> +   * statement evalueates to `false`, then `preventDefault`is applied on the DOM
Missing space in "\`preventDefault\`is".

2018-05-18 05:32 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> +   *     setInterval(() => this.five5Secs.emit("event"), 5000);
Use single quotes in TypeScript for consistency?

2018-05-18 05:32 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> + * DOM sub-tree by using the`ngPreserveWhitespaces` attribute:
Missing space between "the\`ngPreserveWhitespaces\`".

2018-05-18 05:32 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> + * The result of the expression is passed to the pipe's `transform()' method.
Wrong (end) quote in \`transform()'.

2018-05-18 05:32 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> + * to a directive, component, or application. To make it a member of an NgModule,
Is using pipe outside template being recommended?

2018-05-18 05:32 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> + *   constructor(public control:NgModel) {}
Missing space in "control:NgModel".

2018-05-18 05:32 UTC, trotyl commented on packages/core/src/metadata/ng_module.ts
> +   * A name or path that uniquely identifies this NgModule in`getModuleFactory`.
Missing space in "in\`getModuleFactory\`".

2018-05-18 15:20 UTC, jbogarthyde commented on packages/core/src/metadata/ng_module.ts
> +   * A name or path that uniquely identifies this NgModule in`getModuleFactory`.
Thanks for the careful read. Fixed all of these in new push.

2018-05-18 16:17 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> +   * - `bindingProperty` specifies the DOM property the event handler is attached to.
Forgot to mention, there's another one for outputs. 😅

2018-05-18 16:20 UTC, mary-poppins commented
You can preview 9b594f6 at https://pr23902-9b594f6.ngbuilds.io/.

2018-05-18 16:34 UTC, mary-poppins commented
You can preview d2735d9 at https://pr23902-d2735d9.ngbuilds.io/.

2018-05-18 16:45 UTC, jbogarthyde commented
@IgorMinar I made your changes a while ago - and some more additions. Can you take another look, please?

2018-05-25 16:53 UTC, mary-poppins commented
You can preview a712295 at https://pr23902-a712295.ngbuilds.io/.

2018-05-25 17:28 UTC, mary-poppins commented
You can preview 36ad2f4 at https://pr23902-36ad2f4.ngbuilds.io/.

2018-05-31 21:45 UTC, mary-poppins commented
You can preview 17ca4af at https://pr23902-17ca4af.ngbuilds.io/.

2018-06-04 12:47 UTC, petebacondarwin commented on packages/core/src/metadata/directives.ts
> + * Marks a class as a directive and provides configuration metadata.
I would say "A decorator that marks a class as ..." since in the IDE you would only see this text when hovering over a `Directive` type outside of the context of calling it as a decorator.

2018-06-04 12:53 UTC, petebacondarwin requested changes

2018-06-04 12:53 UTC, petebacondarwin commented on packages/core/src/metadata/directives.ts
> +   * ```typescript
It is dangerous to include long examples like this directly in the code.

a) they are not type/syntax checked so they are likely to contain errors
b) the IDE is not able to syntax colour them so it is harder to maintain them
c) there is no automated way to check that these still work when the actual library code changes

Instead such examples should be created standalone with tests etc and included using `<code-example>` tags.

2018-06-04 12:53 UTC, petebacondarwin commented on packages/core/src/metadata/directives.ts
> +   * ```typescript
This also provides the benefit of automated StackBlitz links rather than these hardcoded plunkers.

2018-06-04 19:35 UTC, jbogarthyde commented on packages/core/src/metadata/directives.ts
> +   * ```typescript
OK - put in a TODO, asked @brandonroberts to take a look at providing as a referenced example.

2018-06-04 19:35 UTC, jbogarthyde commented on packages/core/src/metadata/directives.ts
> + * Marks a class as a directive and provides configuration metadata.
Made this change in all of them.

2018-06-04 19:52 UTC, brandonroberts commented on packages/core/src/metadata/directives.ts
> +   * ```typescript
I agree with your points Pete, and I think creating examples for these is a good idea. Would  these go under `/examples` and what kind of tests would we write for these? I don't think we need more E2E tests for these examples since they should be small and concise.

2018-06-05 19:44 UTC, mary-poppins commented
You can preview 163943b at https://pr23902-163943b.ngbuilds.io/.

2018-06-06 08:20 UTC, petebacondarwin commented on packages/core/src/metadata/directives.ts
> +   * ```typescript
@brandonroberts:

For API docs I would put their relevant examples in the `packages/examples` folder. You can look at the other folders in there to see what it looks like.

Even without tests we get the benefit of compilation and linting on the code.

I am not sure if we have setup the infrastructure to run unit or e2e tests on API examples at this stage....

2018-06-06 12:46 UTC, brandonroberts commented on packages/core/src/metadata/directives.ts
> +   * ```typescript
Ok. I'll add the code examples to the `packages/examples` for these and change them to references

2018-06-06 18:39 UTC, brandonroberts commented
@googlebot confirm

2018-06-06 18:53 UTC, mary-poppins commented
You can preview 94688df at https://pr23902-94688df.ngbuilds.io/.

2018-06-06 20:03 UTC, mary-poppins commented
You can preview c80e751 at https://pr23902-c80e751.ngbuilds.io/.

2018-06-06 20:59 UTC, mary-poppins commented
You can preview ca1ac0b at https://pr23902-ca1ac0b.ngbuilds.io/.

2018-06-07 17:18 UTC, mary-poppins commented
You can preview efac6f2 at https://pr23902-efac6f2.ngbuilds.io/.

2018-06-08 15:42 UTC, mary-poppins commented
You can preview 392c1b6 at https://pr23902-392c1b6.ngbuilds.io/.

2018-06-08 15:46 UTC, mary-poppins commented
You can preview 3559708 at https://pr23902-3559708.ngbuilds.io/.

2018-06-15 16:03 UTC, jbogarthyde commented
@IgorMinar @petebacondarwin 
All the changes you requested have been made, please approve. This is all green otherwise, and can land w/approvals.

2018-06-15 16:49 UTC, petebacondarwin approved these changes

2018-06-15 17:18 UTC, mary-poppins commented
You can preview 02844c7 at https://pr23902-02844c7.ngbuilds.io/.

2018-06-15 17:21 UTC, mary-poppins commented
You can preview 824c660 at https://pr23902-824c660.ngbuilds.io/.

2018-06-21 17:52 UTC, jbogarthyde commented
Igor's requested changes have been made - this should be mergeable.

2018-06-21 20:52 UTC, jenniferfell commented
@mhevery Hi. Judy has made Igor's changes. We now need approval from someone from http and core groups. Can you do this review and approval for us? Thanks!

2018-06-21 20:56 UTC, mhevery approved these changes

2018-06-21 20:58 UTC, mhevery commented
http://test/OCL:201581351:BASE:201581364:1529614679394:2f414e85

2018-06-25 17:08 UTC, mary-poppins commented
You can preview ff1b098 at https://pr23902-ff1b098.ngbuilds.io/.

2018-06-25 17:51 UTC, closed without merging

2018-06-25 20:41 UTC, cexbrayat commented
I spotted a few typos in the merged PR, and opened #24665 to fix them (cc @jbogarthyde )