refactor(ivy): remove dynamicViewCount from LContainer
angular/angular pull request #23963
Opened 2018-05-17 14:27 UTC by marclaval

From my understanding, the `dynamicViewCount` property of `LContainer` was introduced during the initial implementation of `ViewContainerRef` to count the number of dynamic views in the container, but it is now used as a flag to know if the `LContainer` belongs to a `ViewContainerRef` or if it was created from an instruction.
In fact, this flag can be simplified and be simply set when the `LContainer` is created.

Following a tricky suggestion from @pkozlowski-opensource , having a dedicated flag is not even needed as the `nextIndex` property is not used when the `LContainer` belongs to a `ViewContainerRef`. **Using -1 as a special value for `nextIndex` is enough to create a flag**

2018-05-17 14:39 UTC, mary-poppins commented
You can preview 782b815 at https://pr23963-782b815.ngbuilds.io/.

2018-05-23 04:11 UTC, mhevery approved these changes

2018-05-23 04:11 UTC, mhevery commented on packages/core/src/render3/interfaces/container.ts
> +   * it is set to -1 to identify this scenario.
Could you add some more reasoning as to why `ViewContainerRef` does not need `nextIndex`? Not obvious from reading this.

2018-05-23 04:12 UTC, mhevery commented
LGTM, please address one doc comment. Also I would like to hear from @alxhub since he originally implemented this.

2018-05-23 13:27 UTC, marclaval commented on packages/core/src/render3/interfaces/container.ts
> +   * it is set to -1 to identify this scenario.
Done

2018-05-23 13:48 UTC, mary-poppins commented
You can preview b1c6d84 at https://pr23963-b1c6d84.ngbuilds.io/.

2018-05-23 14:59 UTC, alxhub submitted a review, later dismissed

2018-05-23 15:41 UTC, marclaval commented on packages/core/src/render3/instructions.ts
> +    nextIndex: isForViewContainerRef ? -1 : 0,
Changed to `null`, this is documented in the LContainer interface

2018-05-29 12:43 UTC, mary-poppins commented
You can preview a04b64c at https://pr23963-a04b64c.ngbuilds.io/.

2018-05-29 13:56 UTC, marclaval commented
Rebased, PTAL

2018-05-30 00:31 UTC, mhevery commented
http://test/OCL:198484568:BASE:198484580:1527640248517:137a13c7

2018-05-30 13:19 UTC, mary-poppins commented
You can preview d988eca at https://pr23963-d988eca.ngbuilds.io/.

2018-05-30 13:40 UTC, mary-poppins commented
You can preview e5c7e70 at https://pr23963-e5c7e70.ngbuilds.io/.

2018-05-30 17:24 UTC, mhevery approved these changes

2018-05-30 17:24 UTC, mhevery requested changes
pullapprove test

2018-05-30 17:24 UTC, mhevery approved these changes

2018-05-30 17:26 UTC, jasonaden approved these changes

2018-05-30 17:29 UTC, mhevery commented
TO: Caretaker

This PR has been approved but [pullapprove](https://pullapprove.com/angular/angular/pull-request/23963/reviews/#group:build-and-ci) is showing that it has not. No idea why since I am in the group. Could caretaker merge it even thought it is not green.

2018-05-30 18:07 UTC, vicb commented
It's only that the bot was taking a nape. Everything is green now.

2018-05-30 18:26 UTC, closed without merging