Update highlight.directive.2.ts
angular/angular pull request #23972
Opened 2018-05-17 19:47 UTC by arunkarthicksr

Fix for issue #23503.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

There is a small typo in ‘src/app/highlight.directive.ts’ embedded code snippet on ['https://angular.io/guide/attribute-directives#respond-to-user-initiated-events'](https://angular.io/guide/attribute-directives#respond-to-user-initiated-events)
Issue Number: 23503

## What is the new behavior?
'}' is added as expected at the last line in ‘src/app/highlight.directive.ts’ embedded code snippet on ['https://angular.io/guide/attribute-directives#respond-to-user-initiated-events'](https://angular.io/guide/attribute-directives#respond-to-user-initiated-events)

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

## Other information

2018-05-17 19:53 UTC, arunkarthicksr commented
I signed it!

2018-05-18 07:46 UTC, gkalpak requested changes

2018-05-18 07:46 UTC, gkalpak commented on aio/content/examples/attribute-directives/src/app/highlight.directive.2.ts
> +// #docregion mouse-methods,
I don't think this is the right fix. It should be `// #docregion` (and `// #enddocregion` below).

2018-05-18 07:48 UTC, mary-poppins commented
You can preview aec15f2 at https://pr23972-aec15f2.ngbuilds.io/.

2018-05-18 07:48 UTC, gkalpak commented on aio/content/examples/attribute-directives/src/app/highlight.directive.2.ts
> +
Remove whitespace from this line to make linting happy :grin:

2018-05-18 07:50 UTC, gkalpak commented
In order for linting to pass, you also need to follow our [commit message guidelines][1]. I.e. change the commit message to something like:

> docs: fix docregion in `highlight.directive.2.ts`
>
> Fixes #23503

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

2018-06-12 17:32 UTC, brandonroberts commented
@arunkarthicksr will you fix the issues with this PR so it can land?

2018-06-13 19:44 UTC, arunkarthicksr reviewed
made the changes suggested in the review

2018-06-13 19:53 UTC, mary-poppins commented
You can preview 77c8c0c at https://pr23972-77c8c0c.ngbuilds.io/.

2018-06-14 13:51 UTC, brandonroberts approved these changes

2018-06-14 13:53 UTC, brandonroberts commented
@arunkarthicksr changes LGTM. Just need to update the commit message so this can land.

2018-06-14 19:12 UTC, arunkarthicksr commented
Hi Brandon,
Please send me the format of accepted commit message and kindly guide me to edit the existing commit message.
Thanks,
Arunkarthick

Sent from Mail for Windows 10

From: Brandon
Sent: 14 June 2018 19:24
To: angular/angular
Cc: Arunkarthick S. R.; Mention
Subject: Re: [angular/angular] docs: fix docregion in highlight.directive.2.tsFixes #23503 (#23972)

@arunkarthicksr changes LGTM. Just need to update the commit message so this can land.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2018-06-18 13:16 UTC, brandonroberts commented
@arunkarthicksr You have a couple of options. You can just close this PR, edit the file in GitHub again and open a new PR with the change and a good commit message like `docs: fix docregion in attribute directives for highlight directive`. Your other option is to use the git command line to edit your commit message in this PR. I've written out the steps below.

1. Clone your fork to your machine: `git clone git@github.com:arunkarthicksr/angular-1.git angular`
2. Checkout your branch: `git checkout patch-1`
3. Amend your commit: `git commit --amend -m "docs: fix docregion in attribute directives for highlight directive"`
4. Push your branch back up: `git push origin -f patch-1`

2018-06-20 19:39 UTC, arunkarthicksr commented
HI Brandon,
I have made the requested changes via git command line.
Thanks,
Arun

Sent from Mail for Windows 10

From: Brandon
Sent: 18 June 2018 18:47
To: angular/angular
Cc: Arunkarthick S. R.; Mention
Subject: Re: [angular/angular] docs: fix docregion in highlight.directive.2.tsFixes #23503 (#23972)

@arunkarthicksr You have a couple of options. You can just close this PR, edit the file in GitHub again and open a new PR with the change and a good commit message like docs: fix docregion in attribute directives for highlight directive. Your other option is to use the git command line to edit your commit message in this PR. I've written out the steps below.
1. Clone your fork to your machine: git clone git@github.com:arunkarthicksr/angular-1.git angular
2. Checkout your branch: git checkout patch-1
3. Amend your commit: git commit --amend -m "docs: fix docregion in attribute directives for highlight directive"
4. Push your branch back up: git push origin -f patch-1
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2018-06-20 19:47 UTC, mary-poppins commented
You can preview e84f179 at https://pr23972-e84f179.ngbuilds.io/.

2018-06-22 12:34 UTC, brandonroberts commented
@arunkarthicksr one of your commit message is still invalid.

![image](https://user-images.githubusercontent.com/42211/41776713-6f79deda-75ee-11e8-8f11-b8241d84d1c7.png)

The `Update highlight.directive.2.ts` message should match the format of the other message.

2018-06-23 15:51 UTC, arunkarthicksr commented
Hi Brandon,
Kindly help to change this commit message.
Thanks,
Arun

Sent from Mail for Windows 10

From: Brandon
Sent: 22 June 2018 18:05
To: angular/angular
Cc: Arunkarthick S. R.; Mention
Subject: Re: [angular/angular] docs: fix docregion in highlight.directive.2.tsFixes #23503 (#23972)

@arunkarthicksr one of your commit message is still invalid.

The Update highlight.directive.2.ts message should match the format of the other message.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2018-06-23 16:46 UTC, mary-poppins commented
You can preview 8e6abbf at https://pr23972-8e6abbf.ngbuilds.io/.

2018-06-25 17:31 UTC, arunkarthicksr commented
Cheers Brandon.

Sent from Mail for Windows 10

From: Brandon
Sent: 25 June 2018 22:57
To: angular/angular
Cc: Arunkarthick S. R.; Mention
Subject: Re: [angular/angular] docs: fix docregion in highlight.directive.2.tsFixes #23503 (#23972)

@arunkarthicksr the commit message has been updated. Just needs help from the caretaker due to CI flakiness.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2018-06-29 14:04 UTC, gkalpak approved these changes

2018-06-30 10:59 UTC, mary-poppins commented
You can preview 2c2b731 at https://pr23972-2c2b731.ngbuilds.io/.

2018-06-30 13:51 UTC, gkalpak commented
Rebased on master and it's green now.

2018-07-02 21:37 UTC, closed without merging