feat(ivy): separate attributes for directive matching purposes
angular/angular pull request #23991
Opened 2018-05-18 09:42 UTC by pkozlowski-opensource

In ngIvy directives matching (determining which directives are active based
on a CSS seletor) happens at runtime. This means that runtime needs to have
enough context to match directives. This PR takes care of cases where a directive's
selector should match bindings (ex. [foo]="exp") and event handlers (ex. (out)="do()").
In the mentioned cases we need to have binding / output "attributes" for directive's
CSS selector matching purposes. At the same time those are not regular attributes and
as such should not  be reflected in the DOM.

In the proposed PR binding / output "attributes" are _not_ stored on TNode and only
used for directives matching on the first render of a given template.

Closes #23706

2018-05-18 09:45 UTC, pkozlowski-opensource commented
@mhevery here is a PR that adds "attributes" (extracted from bindings and outputs) for directive matching purposes. It takes a slightly different approach as compared to @benlesh namespaces handling as it wasn't clear for me how multiple namespaced attributes are to be handled - see https://github.com/angular/angular/pull/23899#pullrequestreview-121344166

Please review and let's discuss as needed.

2018-05-18 09:56 UTC, mary-poppins commented
You can preview 1cfcfbf at https://pr23991-1cfcfbf.ngbuilds.io/.

2018-05-18 18:23 UTC, mhevery requested changes
Overall this is on the right track.

1) change `NG_BIND_OUT_ATTRS` into number per reasons explained.
2) I don't think we should be splitting the array into two parts. We should always deal with it as a single array.

2018-05-22 09:09 UTC, pkozlowski-opensource commented on packages/core/test/render3/node_selector_matcher_spec.ts
> +      it('should take optional binding attribute names into account', () => {
In the proposed design  `NG_BIND_OUT_ATTRS` is a separate array so the `NG_BIND_OUT_ATTRS ` name will not show up here. In other words selector matcher is not aware of `NG_BIND_OUT_ATTRS`

2018-05-22 14:40 UTC, pkozlowski-opensource commented on packages/core/test/render3/node_selector_matcher_spec.ts
> +      it('should take optional binding attribute names into account', () => {
Moved binding / output "attributes" back to `TNode` and changed thise tests.

2018-05-22 14:41 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_selector_matcher.ts
> +    tNode: TNode, selector: CssSelector, bindOutAttrNames?: string[]): boolean {
Changed. There are trade-offs, though, see more details in the PR comment.

2018-05-22 14:45 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +export const NG_BIND_OUT_ATTRS = 'əngBindOutAttrsMarker';
Changed to use a number as a flag.

2018-05-22 14:51 UTC, mary-poppins commented
You can preview e2f7c49 at https://pr23991-e2f7c49.ngbuilds.io/.

2018-05-23 03:59 UTC, mhevery commented on packages/core/test/render3/directive_spec.ts
> +        elementStart(0, 'span', ['class', 'fade', 'test', BOAV, 'other', BOAV]);
hmm... I had something else in mind.
`['class', 'fade', BOAV, 'test', 'other']`
This way as soon as you reach `BOAV` you know you can either exit, or process on attrs only. 

Per https://github.com/angular/angular/pull/23991#issuecomment-391167261
`['class', 'fade', AttributeMarker.SELECT_ONLY, 'test', 'other']`?

Which one do you think is easier for implementation?

2018-05-23 04:06 UTC, mhevery requested changes
Do you want to sync up on this over VC in the morning?

2018-05-23 04:06 UTC, mhevery commented on packages/core/src/render3/di.ts
>        if (attrs[i] == attrName) {
if we implemented https://github.com/angular/angular/pull/23991/files#r190116824 than this would be just
```
if (attrs[i] === AttributeMarker.SELECT_ONLY) break;
```

2018-05-23 04:06 UTC, mhevery commented on packages/core/src/render3/instructions.ts
>      if (attrName !== NG_PROJECT_AS_ATTR_NAME) {
if we would implement https://github.com/angular/angular/pull/23991/files#r190116824 than
```
if (attrName === AttributeMarker.SELECT_ONLY) break;
```

2018-05-23 04:06 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +    const attrValue = attrs[i + 1];
same here

2018-05-23 04:06 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +export const NG_BIND_OUT_ATTR_VAL = 1;
change to 

```
const enum AttributeMarker {
  NS = 0; // namespace. Has to be repeated.
  SELECT_ONLY = 1 // for matching selectors but not for reading. Early exit
}
```

per https://github.com/angular/angular/pull/23991/files#r190116824

2018-05-23 04:06 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +// TS complains about export type TAttrs = (string|NG_BIND_OUT_ATTR_VAL)[]
`(string|AttributeMarker)[]` should work.

2018-05-23 04:06 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +export type TAttrs = (string | 1)[];
Maybe spell out as `TAttributes`????

2018-05-23 09:29 UTC, pkozlowski-opensource commented on packages/core/test/render3/directive_spec.ts
> +        elementStart(0, 'span', ['class', 'fade', 'test', BOAV, 'other', BOAV]);
I don't think that one is easier to implement vs. another. Went with your suggestion as it results in smaller generated code.

2018-05-23 09:29 UTC, pkozlowski-opensource commented on packages/core/src/render3/di.ts
>        if (attrs[i] == attrName) {
Done

2018-05-23 09:29 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +    const attrValue = attrs[i + 1];
Done

2018-05-23 09:29 UTC, pkozlowski-opensource commented on packages/core/src/render3/interfaces/node.ts
> +// TS complains about export type TAttrs = (string|NG_BIND_OUT_ATTR_VAL)[]
Yep, it works 👍

2018-05-23 09:30 UTC, pkozlowski-opensource commented on packages/core/src/render3/interfaces/node.ts
> +export type TAttrs = (string | 1)[];
Changed

2018-05-23 13:36 UTC, mary-poppins commented
You can preview 5926ca1 at https://pr23991-5926ca1.ngbuilds.io/.

2018-05-23 14:59 UTC, pkozlowski-opensource commented
@mhevery went through your comments, went with your suggestions. I believe that we are in-sync right now. Please have a look. Let's VC if there is anything else to clarify / discuss.

2018-05-23 21:55 UTC, mhevery approved these changes
I left few more minor comments, which would be good if you could address, but LGTM otherwise.

2018-05-23 21:55 UTC, mhevery commented on packages/core/src/render3/di.ts
> +      if (attrs[i] === AttributeMarker.SELECT_ONLY) break;
we are reading `attrs[i]` twice can we pull that out to local var?

2018-05-23 21:55 UTC, mhevery commented on packages/core/src/render3/index.ts
> +    AttributeMarker as AM,
Why are we renaming it to AM? Given that it is a `const enum` it will never show up in generated code. I vote for keeping long name.

2018-05-23 21:55 UTC, mhevery commented on packages/core/src/render3/instructions.ts
>      if (attrName !== NG_PROJECT_AS_ATTR_NAME) {
Could we change `NG_PROJECT_AS_ATTR_NAME` into `AttributeMarker.NG_PROJECT_AS`?

Maybe a follow on PR?

2018-05-23 21:55 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +export type TAttributes = (string | AttributeMarker.SELECT_ONLY)[];
I think this should be `(string | AttributeMarker)`?

2018-05-23 21:55 UTC, mhevery commented on packages/core/test/render3/content_spec.ts
> +            elementStart(1, 'span', ['title', AM.SELECT_ONLY]);
Shouldn't this be `[AM.SELECT_ONLY, 'title']`

2018-05-24 08:29 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
>      if (attrName !== NG_PROJECT_AS_ATTR_NAME) {
Sure, will do in a separate PR!

2018-05-24 08:31 UTC, pkozlowski-opensource commented on packages/core/src/render3/di.ts
> +      if (attrs[i] === AttributeMarker.SELECT_ONLY) break;
👍 Done

2018-05-24 08:32 UTC, pkozlowski-opensource commented on packages/core/src/render3/index.ts
> +    AttributeMarker as AM,
Done.

2018-05-24 08:43 UTC, pkozlowski-opensource commented on packages/core/src/render3/interfaces/node.ts
> +export type TAttributes = (string | AttributeMarker.SELECT_ONLY)[];
👍 Done

2018-05-24 08:43 UTC, pkozlowski-opensource commented on packages/core/test/render3/content_spec.ts
> +            elementStart(1, 'span', ['title', AM.SELECT_ONLY]);
Oh yes, good catch! Done.

2018-05-24 08:57 UTC, mary-poppins commented
You can preview 3c5a60e at https://pr23991-3c5a60e.ngbuilds.io/.

2018-05-24 22:12 UTC, mhevery commented
http://test/OCL:197961884:BASE:197961905:1527199903121:a529fb22

2018-05-25 18:20 UTC, pkozlowski-opensource commented
@matsko I've just rebased the PR but it looks like bot re-requires approval and pre-submit _again_ .
This PR was previously approved and had pre-submit run. Marking for merge-assistance.

2018-05-25 18:28 UTC, vicb commented on packages/core/src/render3/instructions.ts
>      if (attrName !== NG_PROJECT_AS_ATTR_NAME) {
Not sure about this one. `NG_PROJECT_AS_ATTR_NAME` is an actual attribute name.

2018-05-25 18:33 UTC, pkozlowski-opensource commented
This PR also addresses runtime part of #23560

2018-05-25 18:52 UTC, mary-poppins commented
You can preview 36af425 at https://pr23991-36af425.ngbuilds.io/.

2018-05-25 21:31 UTC, mhevery commented
http://test/OCL:197961884:BASE:198103784:1527283905307:2fb09e93

2018-05-30 12:06 UTC, mary-poppins commented
You can preview d994d63 at https://pr23991-d994d63.ngbuilds.io/.

2018-05-30 12:12 UTC, pkozlowski-opensource commented
Rebased on top of the latest master.

2018-05-30 16:57 UTC, closed without merging