build(aio) + docs: miscellaneous updates to the doc-gen
angular/angular pull request #24000
Opened 2018-05-18 18:40 UTC by petebacondarwin

There are quite a lot of commits here but each is fairly self-contained and intuitive.

2018-05-18 18:53 UTC, mary-poppins commented
You can preview af721ca at https://pr24000-af721ca.ngbuilds.io/.

2018-05-22 10:40 UTC, gkalpak requested changes
Good stuff 💯
(Only some minor comments.)

2018-05-22 10:40 UTC, gkalpak commented on aio/tools/transforms/templates/api/includes/decorator-overview.html
> +<table class="is-full-width list-table options-table">
1. Is the indentation here intentional?
2. Should `options-table` be `option-table`?

2018-05-22 10:40 UTC, gkalpak commented on aio/tools/transforms/templates/api/includes/decorator-overview.html
> +    </tr>
Incorrect indentation.

2018-05-22 10:40 UTC, gkalpak commented on aio/tools/transforms/templates/api/decorator.template.html
> +  <table class="is-full-width option-table">
Incorrect indentation 😱

2018-05-22 10:40 UTC, gkalpak commented on aio/tools/transforms/templates/api/decorator.template.html
> +      <thead><tr><th><h3>{$ option.name $}</h3></th></tr></thead>
Is the `h3` needed here?

2018-05-22 10:40 UTC, gkalpak commented on aio/tools/transforms/templates/api/includes/decorator-overview.html
> -@{$ doc.name $}{$ doc.typeParams | escape $}({ {$ memberHelper.renderMembers(doc) $}
Isn't this needed any more?

2018-05-22 10:40 UTC, gkalpak commented on aio/tools/transforms/templates/api/lib/memberHelpers.html
> +        <h3>Usage Notes</h3>
Does this need the `.no-anchor` class (as in [decorator.template.html][1])?

[1]: https://github.com/angular/angular/pull/24000/files#diff-3ab70739108ff0d7be74c2f43afca985R35

2018-05-23 14:05 UTC, petebacondarwin commented on aio/tools/transforms/angular-api-package/index.js
> +  return doc.hasOwnProperty('parameters') && !doc.isGetAccessor && !doc.isSetAccessor;
I think so yes.

2018-05-23 15:13 UTC, petebacondarwin commented on aio/tools/transforms/angular-api-package/index.js
> +    rules.push((doc, prop, value) => value && !isMethod(doc) &&
Not quite. This rule only runs on docs that are of the types given in `API_CONTAINED_DOC_TYPES`. It just turns out that all methods and properties are of the same `docType` (i.e. `member`) so we have to have this additional check here.
So since the rule doesn't run on other docTypes (e.g. `class` or `function`) they are not constrained by it.

2018-05-23 15:47 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/includes/decorator-overview.html
> +<table class="is-full-width list-table options-table">
1. No the indentation is totally screwy
2. yes

2018-05-23 15:49 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/decorator.template.html
> +      <thead><tr><th><h3>{$ option.name $}</h3></th></tr></thead>
The headings for the properties table also uses H3 here.
I guess we could avoid both and use appropriate changes to CSS.

2018-05-23 16:03 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/decorator.template.html
> +      <thead><tr><th><h3>{$ option.name $}</h3></th></tr></thead>
Actually thinking about this again, I think we should keep H3s here. Although wrapped in a table (for rendering) the semantic meaning is that the name of the option/property is the heading for this section, which describes this option/property.

2018-05-23 16:06 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/lib/memberHelpers.html
> +        <h3>Usage Notes</h3>
Actually I think that Usage Notes here should perhaps be a H4 since the main heading for this table is the H3 property name.

2018-05-23 17:04 UTC, gkalpak commented on aio/tools/transforms/angular-api-package/index.js
> +    rules.push((doc, prop, value) => value && !isMethod(doc) &&
So, this means that `usageNotes` are not allowed in members, except for methods (where they are allowed)?

2018-05-23 17:34 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/lib/memberHelpers.html
> +        <h3>Usage Notes</h3>
Even further I decided that there should be no heading at all in this case!

2018-05-23 17:34 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/lib/memberHelpers.html
> +        <h3>Usage Notes</h3>
And the same for the decorator case.

2018-05-23 17:45 UTC, petebacondarwin commented
OK I fixed up commits based on all those lovely comments. Thanks @gkalpak 
I have now noticed two new issues:

* we are capturing the docs on the  decorator `const` declaration, which is not really desirable
* "Query" (e.g. `ViewChild`) decorator options are missing. I think this is because these are declared in a more complicated manner than most other decorators.

I suggest that we get this merged and fix those in subsequent PRs.

2018-05-23 17:46 UTC, petebacondarwin commented on packages/core/src/di/forward_ref.ts
> + * @see `forwardRef`
I have updated the others to use `@see` as well.

2018-05-23 17:56 UTC, mary-poppins commented
You can preview 704ab82 at https://pr24000-704ab82.ngbuilds.io/.

2018-05-23 18:08 UTC, mary-poppins commented
You can preview d6d73eb at https://pr24000-d6d73eb.ngbuilds.io/.

2018-05-23 20:42 UTC, IgorMinar commented
- [ ] core/Directives
- [ ] breadcrumbs missing
- [ ] edit & source code button for individual options (ideally this should also show up for class methods and anything similar to that, but it's ok if this is a separate PR)

2018-05-23 20:52 UTC, petebacondarwin commented
* [ ] fail doc-gen if invalid tag is found (requires change to dgeni-packages)

2018-05-23 22:01 UTC, petebacondarwin commented
I have cleaned up this PR and added commits for the items that Igor requested above.

2018-05-23 22:16 UTC, mary-poppins commented
You can preview 9842371 at https://pr24000-9842371.ngbuilds.io/.

2018-05-24 08:27 UTC, gkalpak approved these changes
Excited to have the `view`/`edit` buttons on members \o/
Not thrilled about how they look (and adding red arrows didn't actually help) :grin: :

![view-edit-members](https://user-images.githubusercontent.com/8604205/40473474-f7c6587e-5f44-11e8-9ba9-d08e42030854.png)

2018-05-24 08:27 UTC, gkalpak commented on aio/src/styles/1-layouts/_api-page.scss
> +            padding: 8px 16px;
Are `.api-section` and `.api-table` used anywhere? I couldn't find any occurrences :confused:

2018-05-24 08:27 UTC, gkalpak commented on aio/tools/transforms/angular-api-package/processors/computeApiBreadCrumbs.js
> +          if (doc.moduleDoc) doc.breadCrumbs.push({ text: '@angular/' + doc.moduleDoc.id, path: doc.moduleDoc.path });
1. There is no test for this conditional 😱
2. Under what circumstances can a `doc` have no corresponding `moduleDoc`? Do you have an example?

2018-05-24 08:27 UTC, gkalpak commented on aio/tools/transforms/templates/api/decorator.template.html
> +  <table class="is-full-width option-table">
Indentation still incorrect :grin:

2018-05-24 08:27 UTC, gkalpak commented on aio/tools/transforms/templates/api/lib/githubLinks.html
> +<div class="page-actions">
`page-actions` might not be an descriptive name any more :grin:

2018-05-25 08:16 UTC, petebacondarwin commented on aio/src/styles/1-layouts/_api-page.scss
> +            padding: 8px 16px;
weird me neither...

2018-05-25 08:18 UTC, petebacondarwin commented on aio/tools/transforms/angular-api-package/processors/computeApiBreadCrumbs.js
> +          if (doc.moduleDoc) doc.breadCrumbs.push({ text: '@angular/' + doc.moduleDoc.id, path: doc.moduleDoc.path });
when it is a module? I'll add a test

2018-05-25 08:43 UTC, petebacondarwin commented on aio/src/styles/1-layouts/_api-page.scss
> +            padding: 8px 16px;
I'm going to delete this and consolidate the other styles into the `styles/2-modules/_api-pages.scss` file

2018-05-25 09:13 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/lib/githubLinks.html
> +<div class="page-actions">
renamed to `github-links`

2018-05-25 09:14 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/decorator.template.html
> +  <table class="is-full-width option-table">
I have unindented the `section` tag which should now solve this problem.

2018-05-25 09:34 UTC, mary-poppins commented
You can preview c065871 at https://pr24000-c065871.ngbuilds.io/.

2018-05-25 09:50 UTC, petebacondarwin commented
@gkalpak do you have any suggestions for better styling of the GH links on methods and options?

2018-05-25 10:12 UTC, gkalpak commented
I'm no designer 😛

But I would definitely start at centering them vertically:
![member-gh-links-1](https://user-images.githubusercontent.com/8604205/40539310-04265a50-601d-11e8-94fa-efdb0b5f9e54.png)

And I would try out different colors (a dark-ish gray maybe, to make them stand out less):
![member-gh-links-2](https://user-images.githubusercontent.com/8604205/40539308-03f621c8-601d-11e8-8d18-5bc2ce140e5a.png)

@sjtrimble will definitely have more useful insights than me :grin:

2018-05-25 16:12 UTC, sjtrimble commented
Coming late to the party - is the thought that the main page source and edit would still be there in addition to the 'individual option' ones?

I like @gkalpak idea of having the buttons be more subtle. Would be nice if they turned blue on hover (but without the rounded box border of the current page icons).

Aligning the card header content vertically is as intended in the original design - so that's a go from my perspective :)

2018-06-04 13:43 UTC, petebacondarwin commented
@sjtrimble:

> is the thought that the main page source and edit would still be there in addition to the 'individual option' ones?

Yes that is correct. The "individual option" ones link to the source for those specific items (e.g. the method), whereas the top level on is for the export as a whole (e.g. the class).

I have centred and coloured the links as suggested.

PTAL

2018-06-04 13:54 UTC, mary-poppins commented
You can preview 1b5959c at https://pr24000-1b5959c.ngbuilds.io/.

2018-06-04 14:41 UTC, petebacondarwin commented
<img width="1051" alt="screen shot 2018-06-04 at 15 40 53" src="https://user-images.githubusercontent.com/15655/40923825-b585566e-680d-11e8-83f0-c49c42330bd3.png">

This shows one link being hovered (in blue) while the other is normal (grey).

2018-06-06 15:46 UTC, jbogarthyde commented
I can't see where one overload ends and another one starts -- I would like to see at least an <hr> between them - preferably a descriptive header. How do you navigate to the one you want among 17 almost identical versions?
I have some test doc for the HttpClient file in another PR -- https://github.com/angular/angular/pull/23839

2018-06-06 17:57 UTC, petebacondarwin commented
@jbogarthyde there actually are `<hr>`s between the overloads but they are quite faint! I think the main problem is that the "heading" of each overload is being rendered in a non-bold font and also has line numbers, which makes them look like an example rather than a heading.

Currently we don't have an anchor on each of the overloads so you cannot navigate to them directly. Moreover since these overloads are hidden inside a closed `<details>` element then I am not sure if they would automatically open and scroll to this position even if you could link to them. Is that what you mean by navigating to them?

2018-06-06 19:35 UTC, mary-poppins commented
You can preview 7c06727 at https://pr24000-7c06727.ngbuilds.io/.

2018-06-06 19:44 UTC, mary-poppins commented
You can preview 9697d53 at https://pr24000-9697d53.ngbuilds.io/.

2018-06-06 22:28 UTC, jbogarthyde commented
It would be nice to have a descriptive header that made it into the right-hand TOC, but failing that, you should be able to scroll through opened detail pane and pick out the one you want. 
I guess what I would like to see (in addition to removing the line numbers) is a header between each @returns line and the next signature, that describes the difference -- something like "Get a blog", "Get an observable", "Get observables"...  The header should stand out a bit from the param/return headers, maybe slightly bigger, different color?

2018-06-07 11:08 UTC, petebacondarwin commented
@jbogarthyde can you create a new issue to track this?

2018-06-12 19:26 UTC, IgorMinar approved these changes

2018-06-12 19:29 UTC, IgorMinar commented
@petebacondarwin it looks like this PR breaks CI. can you please check? thanks

2018-06-12 20:48 UTC, petebacondarwin commented
The breakage was not due to a direct change. So I am rebasing again to see if that makes things better.

2018-06-12 21:32 UTC, mary-poppins commented
You can preview 48cfabe at https://pr24000-48cfabe.ngbuilds.io/.

2018-06-13 06:28 UTC, petebacondarwin commented
All green!

2018-06-13 18:19 UTC, mhevery commented
This PR can't be merged because the `fixup!` do not apply cleanly. Could you squash the `fixups` into the corresponding SHAs and than it can be merged.

2018-06-13 22:08 UTC, mary-poppins commented
You can preview 14acfc2 at https://pr24000-14acfc2.ngbuilds.io/.

2018-06-13 23:54 UTC, closed without merging