feat(ivy): add support for short-circuiting
angular/angular pull request #24039
Opened 2018-05-21 23:00 UTC by vicb

Short-circuitable expressions (using ternary & binary operators) could not use
the regulat binding mechanism as it rely on thr bindings being checked every
single time - the index is incremented while checking the bindings.

Then for pure function kind of bindings we use a different mechanism with a
fixed index. As such short circuiting a binding check does not mess with the
expected binding index.

Note that all pure function bindings are handled the same wether or not they
actually are short-circuitable. This allows to keep the compiler and compiled
code simple - and there is no runtime perf cost anyway.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2018-05-21 23:02 UTC, vicb commented on packages/compiler/test/render3/r3_compiler_compliance_spec.ts
> +      const factory = 'factory: function MyComponent_Factory() { return new MyComponent(); }';
useless remove

2018-05-21 23:03 UTC, vicb commented on packages/compiler/test/render3/r3_compiler_compliance_spec.ts
> +                i0.ɵrS(10);
`i0` -> `$r3$` - everywhere updated

2018-05-21 23:04 UTC, vicb commented on packages/core/src/render3/instructions.ts
> + *  |  LNodes ... | pure function bindings | regular binding / interpolations |
reg binding*S*

2018-05-21 23:12 UTC, mary-poppins commented
You can preview e81bc71 at https://pr24039-e81bc71.ngbuilds.io/.

2018-05-21 23:34 UTC, mary-poppins commented
You can preview 28e7953 at https://pr24039-28e7953.ngbuilds.io/.

2018-05-21 23:34 UTC, vicb commented on packages/core/test/render3/compiler_canonical/component_directives_spec.ts
> +              // TODO(vicb): Shouldn't bind be the outer call ?
@mhevery the code needs to be update here, right ?

2018-05-21 23:45 UTC, mary-poppins commented
You can preview f399591 at https://pr24039-f399591.ngbuilds.io/.

2018-05-22 00:15 UTC, mary-poppins commented
You can preview 8662643 at https://pr24039-8662643.ngbuilds.io/.

2018-05-22 04:54 UTC, mhevery requested changes

2018-05-22 04:54 UTC, mhevery commented on packages/compiler/test/render3/r3_compiler_compliance_spec.ts
> +            i0.ɵp(0, 'or', i0.ɵb((ctx.cond || i0.ɵf1(6, _c0, ctx.c))));
This does not look right to me. `6` is already used 2 lines above. Are we double using the slots?

2018-05-22 04:54 UTC, mhevery commented on packages/compiler/test/render3/r3_compiler_compliance_spec.ts
> +                    $r3$.ɵb($r3$.ɵfV(10, $e0_ff$, ctx.n0, ctx.n1, ctx.n2, ctx.n3, ctx.n4, ctx.n5, ctx.n6, ctx.n7, ctx.n8)));
This seems wrong. `ɵfV(10, $e0_ff$, [ctx.n0, ctx.n1, ctx.n2, ctx.n3, ctx.n4, ctx.n5, ctx.n6, ctx.n7, ctx.n8]))`  (note that args should be in array)

2018-05-22 04:54 UTC, mhevery commented on packages/core/src/render3/index.ts
> +  reserveSlots as rS,
I am starting to think that maybe we should have a general instruction 
```
function reserve(
  elementCount: number,
  bindingCount: number,
  pureFnCount?: number,
  pipeCount?: number,
): void;
```
This instruction would be always required as first instruction and it would allocate the data. What do you think?

2018-05-22 04:54 UTC, mhevery commented on packages/core/src/render3/pure_function.ts
> +    slotOffset: number, pureFn: (...v: any[]) => any, exps: any[], thisArg?: any): any {
Note `exps` is `any[]` hence `pureFunctionV` must take args as `[arg0, arg1, ...]`

2018-05-22 04:54 UTC, mhevery commented on packages/core/test/render3/compiler_canonical/component_directives_spec.ts
> +              // TODO(vicb): Shouldn't bind be the outer call ?
correct, it needs to be wrapped in `bind`

2018-05-22 04:54 UTC, mhevery commented on packages/core/test/render3/compiler_canonical/pipes_spec.ts
> +                $r3$.ɵi1('', $r3$.ɵpb2(1, 6, $r3$.ɵpb2(2, 3, ctx.name, ctx.size), ctx.size), ''));
same here, missing `bind`. 

Thinking more about it, I think we should just inline bind into `text`, `property`, `attribute` instruction. This way it will be less code to generate. Maybe follow up PR?

2018-05-22 05:21 UTC, vicb commented on packages/compiler/test/render3/r3_compiler_compliance_spec.ts
> +                    $r3$.ɵb($r3$.ɵfV(10, $e0_ff$, ctx.n0, ctx.n1, ctx.n2, ctx.n3, ctx.n4, ctx.n5, ctx.n6, ctx.n7, ctx.n8)));
I think at some point Chuck used that to prevent building an array. But good catch. I'll update (compiler + test).
_This error is not introduced by the current PR but was here before_

2018-05-22 05:23 UTC, vicb commented on packages/core/src/render3/index.ts
> +  reserveSlots as rS,
Might be. 
I think we discussed reserving the `bindingCount` part today (current issue with `undefined` not being detected as a change).
Should be designed/agreed, I would tend to do this in a follow up PR. WDYT ?

2018-05-22 05:25 UTC, vicb commented on packages/core/test/render3/compiler_canonical/pipes_spec.ts
> +                $r3$.ɵi1('', $r3$.ɵpb2(1, 6, $r3$.ɵpb2(2, 3, ctx.name, ctx.size), ctx.size), ''));
This one is actually correct. `interpolationX` returns `NO_CHANGE`.

2018-05-22 05:37 UTC, vicb commented
@mhevery Thanks for the review. I'll update this PR first thing tomorrow morning.

2018-05-22 18:20 UTC, mary-poppins commented
You can preview a973202 at https://pr24039-a973202.ngbuilds.io/.

2018-05-22 21:00 UTC, JoostK commented on packages/core/test/render3/compiler_canonical/pipes_spec.ts
> +                $r3$.ɵi1('', $r3$.ɵpb2(1, 6, $r3$.ɵpb2(2, 3, ctx.name, ctx.size), ctx.size), ''));
@mhevery I was thinking the same thing, but that isn't trivial for cases where interpolation is relevant. Please refer to #23881 and #23923.

2018-05-22 21:01 UTC, vicb commented
http://test/OCL:197619135:BASE:197619176:1527022871189:d520265

2018-05-22 21:04 UTC, mary-poppins commented
You can preview 4adff90 at https://pr24039-4adff90.ngbuilds.io/.

2018-05-23 17:45 UTC, mary-poppins commented
You can preview bb679b3 at https://pr24039-bb679b3.ngbuilds.io/.

2018-05-23 21:45 UTC, mhevery commented on packages/core/src/render3/index.ts
> +  reserveSlots as rS,
SGTM

2018-05-23 21:46 UTC, mhevery approved these changes

2018-05-24 17:57 UTC, kara reviewed
FYI found some minor typos (probably for a follow-up, since this already has a merge label).

2018-05-24 17:57 UTC, kara commented on packages/core/src/render3/instructions.ts
> + * Sets up the binding index before execute any `pureFunctionX` instructions.
`before execute` -> `before executing`

2018-05-24 17:57 UTC, kara commented on packages/core/src/render3/instructions.ts
> + * Binding for pure functions are store after the LNodes in the data array but before the binding.
`Binding for pure functions` -> `Bindings for pure functions`
`are store` -> `are stored`

2018-05-24 17:57 UTC, kara commented on packages/core/src/render3/instructions.ts
> +  // whether is happens or not during the first change detection pass - pure functions checks
`is happens` -> `it happens`

2018-05-24 17:57 UTC, kara commented on packages/core/src/render3/instructions.ts
> + * On the first template pass the reserved slots should be set `NO_CHANGE`.
`On the first template pass the reserved slots` -> `On the first template pass, the reserved slots`

2018-05-25 17:48 UTC, closed without merging