feat(ivy): runtime i18n
angular/angular pull request #24037
Opened 2018-05-21 18:57 UTC by ocombe

## PR Type
What kind of change does this PR introduce?

```
[x] Feature
```

## What is the current behavior?
There is no runtime i18n for ivy

## What is the new behavior?
Runtime i18n works for ivy

## Does this PR introduce a breaking change?
```
[x] No
```

2018-05-21 21:11 UTC, mary-poppins commented
You can preview 391ac36 at https://pr24037-391ac36.ngbuilds.io/.

2018-05-22 05:18 UTC, mhevery requested changes

2018-05-22 05:18 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +export function i18nMapping(msg: string, placeholders: string[]): any[] {
can you type the return value better than `any[]` maybe `I18nInstruction[]` where `type Instruction = number|string`

2018-05-22 05:18 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +export function i18nApply(instructions: any[]): void {
`any[]` => `I18nInstruction[]`

2018-05-22 05:18 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +    children.splice(i + 1, 0, ...getChildren(children[i]));
can you not use `...` operators since when down-leveled to `ES5` it is slow.
Notice that it causes `apply` to be called
http://www.typescriptlang.org/play/#src=children.splice(i%20%2B%201%2C%200%2C%20...getChildren(children%5Bi%5D))%3B

2018-05-22 05:18 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +        expRegex, (match: string, p1: string) => { return args[placeholders.indexOf(p1)]; });
You are allocating a regexp and than doing string replace. This will create GC pressure every time we run change detection and it is not the fastest. Can we refactor this so that it does not allocate anything when there is no change to inputs.

2018-05-22 05:18 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +export function i18nInterpolation(
What is the point of this method with 7 args? Why 7?

2018-05-22 05:18 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +  if (args.some(value => bind(value) !== NO_CHANGE)) {
Don't use `some` same argument as `forEach`

2018-05-22 05:18 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +export function getChildren(parent: LNode): LNode[] {
The way you can make this method cacheable, is to collect method induces rather than `LNode`s themselves. So return would be `number[]`. Than you could do the dereference when processing instructions.

2018-05-22 12:38 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +    children.splice(i + 1, 0, ...getChildren(children[i]));
I can use slice & concat instead: https://jsperf.com/slice-concat-vs-splice-spread
It's faster in chrome (about the same in firefox).
Unless you have a better idea?

2018-05-22 13:46 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +        expRegex, (match: string, p1: string) => { return args[placeholders.indexOf(p1)]; });
actually this is the same regex that it used above, I'll use the same constant

2018-05-22 16:27 UTC, mary-poppins commented
You can preview 767144e at https://pr24037-767144e.ngbuilds.io/.

2018-05-22 16:51 UTC, mary-poppins commented
You can preview b4a00f4 at https://pr24037-b4a00f4.ngbuilds.io/.

2018-05-22 18:32 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +        const element = children[instruction & I18nFlags.INDEX_MASK];
`data[children[instruction & I18nFlags.INDEX_MASK]]`

`data[instruction & I18nFlags.INDEX_MASK]`

2018-05-22 18:32 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +    if (currentNode.native) {
`currentNode.tNode.index`

2018-05-22 20:55 UTC, JoostK requested changes

2018-05-22 20:55 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +  if (bind(a0) !== NO_CHANGE || bind(a1) !== NO_CHANGE) {
We could use `bindingUpdatedN` here, with `N` in `{,2,4}` to combine the bind checks. That would also get rid of the need for `NO_CHANGE` as then only booleans are handled. Refer to the `interpolation#` instructions where the same approach is used.

Applies to all `i18nInterpolation#` functions.

2018-05-22 20:55 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +      return msg.replace(
The early return here can't be right. We'd need to traverse all bindings for them to be updated and become string replaced.

2018-05-22 20:55 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +  if (bind(a0) !== NO_CHANGE || bind(a1) !== NO_CHANGE) {
Also, watch out with short circuiting. We do not want that to happen, because it would cause bindings not to be updated. Recall that `bind` wither updates or consumes a binding which causes `bindingIndex` to be incremented past the binding slot, we need to make sure that always occurs for the bindings to stay in sync.

2018-05-22 20:55 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +    if (match = elementRegex.exec(value)) {
We can probably get away with a lot less regex matching here, if we were to change the regex into `/\{\$((?:exp|p|c)_\w+)\}/g`. We'd then know that all odd indices actually match, and we can easily figure out the instruction per the odd matches' prefix and the identifier from a substring. One regex match, then just string manipulation with known offsets.

2018-05-23 08:45 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +  if (bind(a0) !== NO_CHANGE || bind(a1) !== NO_CHANGE) {
Good points, I didn't think about that! thanks

2018-05-23 08:46 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +  if (bind(a0) !== NO_CHANGE || bind(a1) !== NO_CHANGE) {
actually I think I should probably use interpolation1, ... instead

2018-05-23 09:19 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +    if (match = elementRegex.exec(value)) {
Very good idea, thanks!

2018-05-24 10:44 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +  let children = data.slice(startIndex, endIndex + 1);
If we offset each lookup into `data` with `startIndex`, we'd void having to create a copy. We may then even get rid of `endIndex`, or use it only in dev mode for bounds checking.

2018-05-24 12:08 UTC, mary-poppins commented
You can preview 1171f4c at https://pr24037-1171f4c.ngbuilds.io/.

2018-05-24 12:08 UTC, mary-poppins commented
You can preview b528710 at https://pr24037-b528710.ngbuilds.io/.

2018-05-24 17:59 UTC, vicb commented on packages/core/src/render3/instructions.ts
> + * We shift the flags by 29 so that 30 & 31 & 32 bits contains the instructions.
nit: use constant rather than number in the comment and in the enum to avoid then getting out of sync later

2018-05-24 18:00 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +  INSTRUCTION_MASK = ~((1 << 29) - 1),
nit: `0b111 << INSTRUCTION_SHIFT`

2018-05-24 18:05 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +  const instructions = [];
add type ?

2018-05-24 18:06 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +    // odd index is either element, expression or close tag
`// odd index are placeholders`

2018-05-24 18:08 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +      switch (value.substr(0, 1)) {
`value.charAt(0)`

_Note: p/e/c will change later_

2018-05-24 18:09 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +          instructions.push(placeholders.indexOf(value) | I18nFlags.ELEMENT);
why use `.indexOf(value)` instead of the map as proposed in the compiler side spec ?

2018-05-24 18:11 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +      // don't create a text node for empty values
I don't understand what `// don't create a text node for empty values` means here ?
Should it be a TODO ? / What not doing it then ?

2018-05-24 18:12 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +      instructions.push(i | I18nFlags.REMOVE_NODE);
You should not push instructions for closing tags ?

2018-05-24 18:15 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +  ngDevMode &&
nit:
I find
```
if (ngDevMode) {
  // 2 instrcutions
}
```
more readable ?

2018-05-24 18:19 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +  for (let i = 0; i < instructions.length; i++) {
As discussed with @mhevery, not moving the LNode will break projections.
Has this been thought through in the design spec ?

2018-05-24 18:21 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +        const element = data[startIndex + instruction & I18nFlags.INDEX_MASK];
Question:
why `startIndex + instruction & I18nFlags.INDEX_MASK` ?
In my compiler side spec the index (` instruction & I18nFlags.INDEX_MASK`) is an absolute index.

2018-05-24 18:21 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> + * We shift the flags by 29 so that 30 & 31 & 32 bits contains the instructions.
I tried that at first but for some reason typescript doesn't want a variable in a an enum value

2018-05-24 18:23 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +export function i18nInterpolation1(msg: string, ph0: string, v0: any): string|NO_CHANGE {
The compiler design spec propose and implementation with no need for the 1, 2, ..., 8 variants.
Why do you think this one is better ?

2018-05-24 18:26 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +      // don't create a text node for empty values
When using split above, it will create empty string fragments, for example: `{$p_1}trad 1{$c_p}` will be `["", "p_1", "trad 1", "c_p", ""]. The `if` here is used to avoid pushing instructions that are useless, we don't want to create empty text node

2018-05-24 18:27 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +      instructions.push(i | I18nFlags.REMOVE_NODE);
when we read the instructions, we need to know the current parent to which we should add the childs, we change the parent when we see an opening tag (`p_x`), and change it again when we see the closing tag

2018-05-24 18:28 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +function replaceAllStr(str: string, pattern: string, replacement: string): string {
I am not sure to understand how `replaceAllStr()` / ` i18nInterpolationX()` will work at all.
Seems like this is unused in this PR / not described in the doc.
Remove from this PR for now until details are figured out ?

2018-05-24 18:28 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +  ngDevMode &&
it's like that all over the place in `instructions.ts`, I don't mind changing it, since it's one less test to do, but we should change it in the other parts of the code as well

2018-05-24 18:29 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +  for (let i = 0; i < instructions.length; i++) {
no, that's why I asked if we could have a meeting about that, but @mhevery said that he would think about it, I'm giving him some time for that first, I'll update the code once we have a good solution

2018-05-24 18:30 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +export function i18nInterpolation1(msg: string, ph0: string, v0: any): string|NO_CHANGE {
Oh this is used for attributes only.

Need to be discussed.

2018-05-24 18:31 UTC, vicb submitted a review, later dismissed
Great start.

2018-05-24 18:33 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +export function i18nInterpolation1(msg: string, ph0: string, v0: any): string|NO_CHANGE {
isn't it more optimized to do it like that?

2018-05-24 18:36 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +          instructions.push(placeholders.indexOf(value) | I18nFlags.ELEMENT);
good point, I've changed the code a few times, and now it seems like a map would be better, I'll update my code

2018-05-24 18:37 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +        const element = data[startIndex + instruction & I18nFlags.INDEX_MASK];
ok, I'll change my code then

2018-05-24 18:57 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +const tagRegex = /\{\$((?:exp|p|c)_\w+)\}/g;
I don't see how to split the translation efficiently without a regex?

2018-05-24 18:59 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +    if ((i % 2) === 1) {
oh nice trick

2018-05-24 19:37 UTC, mary-poppins commented
You can preview 2d23955 at https://pr24037-2d23955.ngbuilds.io/.

2018-05-24 21:21 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +export function i18nInterpolation1(msg: string, ph0: string, v0: any): string|NO_CHANGE {
My spec is for the compiler side:

> This design specs details the output of the compiler for i18n templates. It does also describe what the IVY runtime should do but not how it should do it.

2018-05-24 21:29 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +export function i18nInterpolation1(msg: string, ph0: string, v0: any): string|NO_CHANGE {
What I envision:
```
function i18nInterpolation(
   mapping: I18nMapping, 
   a0: any, 
   a1: any, 
   // ... 
   a7: any
): string | NO_CHANGE;
```

The first argument `mapping` could contain a list of static strings `['a', 'b', 'c']` and a list of placeholder index `[2, 0, 1]` compute once the first time the template function is executed.

Updating the value would compute `'a' + a2 + 'b' + a0 + 'c' + a1`.

2018-05-24 21:33 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +const tagRegex = /\{\$((?:exp|p|c)_\w+)\}/g;
There should probably be a regexp, but a simpler/faster one ie `/\{\$[^}]+\}/g`
The other part of the perf gain is that placeholders would be specified as maps (one for element and an other one for expression).

2018-05-24 21:38 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +      // don't create a text node for empty values
Oh you are absolutely right. I totally miss that there was an if here.

May be write 
``` typescript
} else if (value) {
  instructions.push(I18nFlags.TEXT, value);
}
```

2018-05-24 21:40 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +      instructions.push(i | I18nFlags.REMOVE_NODE);
Yes I agree. But this seems to be `CLOSE_NODE` l2433, this one is `REMOVE_NODE`

2018-05-24 21:44 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +  ngDevMode &&
Different people like to write code in different ways. I find the proposal above easier to read.
When I say "nit:" it's a hint that you might or might not want to do it. Up to what you find is more readable.

2018-05-25 18:08 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +        const element = data[startIndex + instruction & I18nFlags.INDEX_MASK];
Also because the index only has a limited number of bits for encoding, there should be an assert to make sure that no overflow occurs

2018-05-28 08:42 UTC, mary-poppins commented
You can preview 8203e35 at https://pr24037-8203e35.ngbuilds.io/.

2018-05-28 09:34 UTC, mary-poppins commented
You can preview 81c65ad at https://pr24037-81c65ad.ngbuilds.io/.

2018-05-28 12:01 UTC, mary-poppins commented
You can preview 95d5e5c at https://pr24037-95d5e5c.ngbuilds.io/.

2018-05-28 13:12 UTC, mary-poppins commented
You can preview c0b6c98 at https://pr24037-c0b6c98.ngbuilds.io/.

2018-05-28 13:31 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +    if (i & 1) {
`i += 2` would avoid the odd check.

2018-05-28 16:50 UTC, mary-poppins commented
You can preview 3da714a at https://pr24037-3da714a.ngbuilds.io/.

2018-05-29 17:02 UTC, ocombe commented on packages/core/src/render3/node_manipulation.ts
> +  // for i18n, we use pNextOrParent to point to the virtual next child
I decided to use `pNextOrParent` to point to the first child for projections, but I could also add another new property on the `LNode` or `TNode` (like `pChild` for example) that would be used just for that. What do you prefer @mhevery @vicb?

2018-05-29 17:03 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +    componentChild = getNextLNodeWithProjection(componentChild);
I haven't found any downside to use `getNextLNodeWithProjection` instead of `getNextLNode`, and all the tests pass, but maybe there something that I missed here?

2018-05-29 17:05 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +  // TODO(ocombe): add a test to check if we really need to update the last pointer
I'm not sure if we really need to update the last node pointer, since it should be the parent (the i18n block), and it shouldn't change anything for projections. If that's the case, then we can drop `endIndex` because it isn't used anywhere.
Can you come up with a scenario where updating that pointer is necessary?

2018-05-29 17:28 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +          instructions.push(placeholders[value] | I18nFlags.Element);
Add assert to make sure `placeholders[value]` does not overflow

2018-05-29 17:29 UTC, vicb commented on packages/core/src/render3/instructions.ts
> + * @param startIndex Used for content projections
May be start by what this is before how it is used ?

2018-05-29 17:32 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +        // create the LNode for projections
Explain why we need this ?

2018-05-29 17:43 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +export type I18nInstruction = number | string;
Expand on what instructions could be:
- a placeholder index,
- a static text,
- a bit field

2018-05-29 17:44 UTC, vicb commented on packages/core/src/render3/node_manipulation.ts
> +  // for i18n, we use pNextOrParent to point to the virtual next child
I don't know this code well enough to tell.
What is a "virtual" child ?

2018-05-29 17:47 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +            textBinding(2, bind(ctx.exp2));
- Do you have a test with a `textBinding` to a node that has been remove ?

2018-05-29 17:53 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +    const i18n_1 = i18nMapping(MSG_1, {p_0: 1, p_1: 2, p_2: 3, p_3: 4});
seems like closing tag placeholders are missing (in multiple tests)

2018-05-29 17:56 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +            text(1);
For each test, you should probably explicit the source structure and the translation.
Also explain what the `text()` instructions are for ? I don't see why we have 3 here ?

2018-05-29 17:57 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +    const MSG_2 = `start {$exp_2} middle {$exp_1} end`;
may be use longer name to give more context ? 
- `MSG_ATTRIBUTE_1`
- `MSG_DIV_2`
- ...

2018-05-30 01:15 UTC, mhevery requested changes

2018-05-30 01:15 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +  // for i18n, we use pNextOrParent to point to the virtual next child
What you did is correct.

However, @kara is refactoring to get rid of `LNode`s and so your approach will have to change. @kara do you think we can leave it now, and deal with it when we do our refactoring or should we design it differently now?

The new approach I think will have to create a `T` array for the projected nodes instead of `pNextOrParent`, which means that these new nodes will have to be stored someplace in the data array. Seems like you should just go with this approach, and we will have to fix it once we do the refactoring.

2018-05-30 01:47 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> +  // for i18n, we use pNextOrParent to point to the virtual next child
Yeah, this does create a bit more work for me, but I don't think it makes sense to do it now with the data refactoring 50% done. Can we put a TODO in here to remove?

2018-05-30 11:42 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +          instructions.push(placeholders[value] | I18nFlags.Element);
I think that we can safely assume that we will never have an index number that exceeds 28 bits (268435456), right?

2018-05-30 12:06 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +    translation: string, placeholders: PlaceholderMap = {}): I18nInstruction[] {
we can just say that it cannot be empty, and pass an empty object when there is no placeholder

2018-05-30 12:18 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +    componentChild = getNextLNodeWithProjection(componentChild);
@vicb you are overestimating my knowledge here :-) 

Anyhow, I find this change slightly surprising since the oryginal logic was:
* go over each and every content node;
* distribute it (potentially adding it to the "default" bucket if none of the selector matches)

With this change it seems like we can skip / omit some of the nodes when going over content nodes and on the surface it doesn't sound right. What is the motivation for this change?

2018-05-30 12:20 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +  const staticText: I18nInstruction[] = translation.split(tagRegex);
Using more local variables is less efficient, you'd need to loop on all indexes instead of just `odd` ones.
I'll add a new type since it's not the same kind of instructions (no binary values here)

2018-05-30 12:55 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +      switch (instructions[i]) {
it's 30% slower with an external function https://jsperf.com/switch-function-inline

2018-05-30 13:04 UTC, ocombe commented on packages/core/src/render3/instructions.ts
> +      if (bindingUpdated(value)) {
I'll have to check the bindings for v0 to v7, even if we only pass 1 value, since there's no way to know if the value is undefined or if we don't have that value at all...

2018-05-30 17:53 UTC, mary-poppins commented
You can preview 7185151 at https://pr24037-7185151.ngbuilds.io/.

2018-05-30 18:59 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +      switch (instructions[i]) {
leave as is than.

2018-05-30 19:00 UTC, mhevery approved these changes

2018-06-05 03:23 UTC, kara reviewed
Some nits about comments, if you have time.

2018-06-06 15:39 UTC, mary-poppins commented
You can preview 4b671b4 at https://pr24037-4b671b4.ngbuilds.io/.

2018-06-06 17:17 UTC, mary-poppins commented
You can preview a95898b at https://pr24037-a95898b.ngbuilds.io/.

2018-06-08 12:50 UTC, mary-poppins commented
You can preview 6c566bb at https://pr24037-6c566bb.ngbuilds.io/.

2018-06-08 16:49 UTC, vicb requested changes
- There are deviations from the compiler side spec to be discussed before this can go in,
- Not all my comments have been addressed,
- Please do not dismiss my reviews w/o asking me before.

2018-06-08 18:24 UTC, mhevery requested changes
Waiting until the container implementation is done

2018-06-11 11:49 UTC, mary-poppins commented
You can preview 1106b3a at https://pr24037-1106b3a.ngbuilds.io/.

2018-06-11 16:17 UTC, mary-poppins commented
You can preview 82544b7 at https://pr24037-82544b7.ngbuilds.io/.

2018-06-12 13:12 UTC, mary-poppins commented
You can preview 18f2153 at https://pr24037-18f2153.ngbuilds.io/.

2018-06-13 17:40 UTC, mary-poppins commented
You can preview 27665ad at https://pr24037-27665ad.ngbuilds.io/.

2018-06-13 22:04 UTC, vicb commented
- Please add canonical tests in `packages/core/test/render3/compiler_canonical` (ie tests that will get mirrored in the compiler tests),
- Seems like all the projection tests use NO selector. I would expect to see tests trying to project element that have been removed explicitly ?

2018-06-13 22:04 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * @param msgList The translation string split into an array of placeholders and text elements
not in sync with the code

2018-06-13 22:09 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * A function to recursively generate the instructions for i18nMapping
> `A function to recursively generate the instructions for i18nMapping`
doesn't really help to know the intent of this function.
What are the inputs, the outputs, what does this fn works on ? a template ?
"to recursively" seems useless here. That's purely an implementation details that brings not useful information to the caller.

2018-06-13 22:11 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +      if (elements && elements[tmplIndex] &&
Add a comment on what  you are testing and what instruction you generate. (one liner)

2018-06-13 22:13 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +        if (tmplIndex > 0 || (tmplContainers && tmplContainers.indexOf(value) !== -1)) {
where is the spec for the handling of embedded template ? I thought you told me you would update it ?

2018-06-13 22:15 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +    elements: (PlaceholderMap | null)[] | null, expressions?: (PlaceholderMap | null)[] | null,
Question: why and array of `PlaceholderMap` ?

2018-06-13 22:18 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +    const tmplElements = elements[tmplIndex];
comment, comment, comment...
what are you trying to do ?

2018-06-13 22:20 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * Takes a translation string and the initial list of placeholders (elements and expressions)
Please separate and clearly indicate in the comment (again)
1) instructions, called from template
2) internal functions

2018-06-18 13:58 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +    elements: (PlaceholderMap | null)[] | null, expressions?: (PlaceholderMap | null)[] | null,
The indexes of the placeholders are different in each template function, we need a placeholder map for each template because of that

2018-06-18 15:11 UTC, mary-poppins commented
You can preview 4202fcf at https://pr24037-4202fcf.ngbuilds.io/.

2018-06-18 16:50 UTC, ocombe commented on packages/core/test/render3/i18n_spec.ts
> +      // Remove the last item
PR to fix that bug: https://github.com/angular/angular/pull/24564

2018-06-18 20:09 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * Internal function that reads the translation parts and generates a set of instructions for each
Could at least you move the i18n API first and the internal fn last (if possible different files would be better)

2018-06-18 20:11 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * and their indexes.
Could you please add more detail on element ph indexes / expression ph indexes ? (may be adding a small ex)

2018-06-18 20:12 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * @returns the current index in msgList
what is `msgList` ?

may be giving an example would help understand this function ?

2018-06-18 20:13 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * @param index The current index in `translationParts`.
if index applies to `translationParts`, it would be nice to have those 2 back to back ?

2018-06-18 20:16 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +      // Test if the value is an element
"Test if" sounds useless. Move the comment inside the `if`: "The placeholder represents a DOM element`

2018-06-18 20:16 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +        // Add an instruction to move the element to that index
"that index" ?

2018-06-18 20:17 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +  const phAdded = [];
`phVisited` ?

2018-06-18 20:19 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +        if (tmplIndex > 0 || (tmplContainers && tmplContainers.indexOf(value) !== -1)) {
`tmplIndex > 0`:
- I have no clue why this test,
- because `tmplIndex` is a const, you should move the test oustise of the loop `const is... =  tmplIndex > 0`;

2018-06-18 20:19 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * @param tmplContainers An array of template container placeholders whose content should be ignored
what are `template container` ?

2018-06-18 20:20 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +        tmplInstructions.push(phIndex | I18nFlags.Expression);
how can we "move" an expression ?

2018-06-18 20:22 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +  let tagCounter = 0;
`tagConter` -> `openedTagCount` ?

2018-06-18 20:27 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +          tmplInstructions.push(index | I18nFlags.RemoveNode);
Question: should RemoveNode be DetachNode ?
Same comment as few weeks ago: assert that the index does not overflow (`ngDevMode && assert(...)`)

2018-06-18 20:28 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +    // The current parent has more children, we need to append them at the end to keep the order
I don't understand `we need to append them at the end to keep the order` ?

2018-06-18 20:29 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +      // their children, all we need to do is to append them at the end
append means at the end -> you can remove "at the end"

2018-06-18 20:30 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * indexes, and returns a list of instructions for each template.
same comment as above in my design spec, we use expressions order, not indexes. Pls clarify.

2018-06-18 20:31 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +  // Call the recursive function that will update the instructions
useless comment ?
but maybe the function should be named `updateInstructions` / `appendInstructions` ?

2018-06-18 20:49 UTC, vicb requested changes
See inline commits for feedback.
Please add to this PR:
- What is done and todo in the PR headline,
- The status of the design spec in the PR headline,
- What is changed by each fixup commits.
So that github (and not slack or any other channel) is the single/up to date source of truth.

I can see some progress by I have no clear idea of what is left to be done.

2018-06-19 08:30 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> + * @returns the current index in msgList
aren't the tests enough?

2018-06-19 08:43 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +        if (tmplIndex > 0 || (tmplContainers && tmplContainers.indexOf(value) !== -1)) {
Actually the "if" is useless here, we can just always increase the `tagCounter`

2018-06-19 08:46 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +        tmplInstructions.push(phIndex | I18nFlags.Expression);
by moving the text node associated with this expression

2018-06-19 09:07 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +          tmplInstructions.push(index | I18nFlags.RemoveNode);
I added the assert but I feel like it's useless, we will never have an index that goes beyond 28 bits (~268435455)

2018-06-19 09:08 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> + * @param tmplContainers An array of template container placeholders whose content should be ignored
I'm talking about instructions of the type `container(1, liTemplate, null, ['ngForOf', '']);` that have a template function and generate an embedded template.

2018-06-19 13:14 UTC, mary-poppins commented
You can preview e2654f0 at https://pr24037-e2654f0.ngbuilds.io/.

2018-06-20 05:46 UTC, vicb commented on packages/core/src/core_render3_private_export.ts
> -  defineComponent as ɵdefineComponent,
Re-ordering alphabetically is probably a good idea... but not in this PR.
(and such refactor should be done in refactor commits)

2018-06-20 05:48 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * A list of flags to encode the i18n instructions used to translate the template.
Technically speaking, those are not Flags (a flag is usually a bit that can be 0 or 1).
Check the core to see how they are called where we use such a mechanism an name this one consistently.

2018-06-20 05:50 UTC, ocombe commented on packages/core/src/core_render3_private_export.ts
> -  defineComponent as ɵdefineComponent,
not my fault, it's `gulp format`! And it's needed to pass the lint tests

2018-06-20 22:02 UTC, mhevery requested changes
I have given it a thorough review and fixed minor issues here b697333535. 

The big issue which needs to be resolved before this can be merged in is moving `detached` from `LNode` to `TNode`.

Also left few other comments.

2018-06-20 22:02 UTC, mhevery commented on packages/core/test/render3/compiler_canonical/i18n_spec.ts
> +            $r3$.ɵiA(1, $i18n_1$[0]);
Why is `$i18n_1$` an array where we read `[0]`? Under what conditions would we use the other items in the array?

2018-06-20 22:02 UTC, mhevery commented on packages/core/test/render3/compiler_canonical/i18n_spec.ts
> +            $r3$.ɵiA(1, $i18n_1$[0]);
I see when the translation crosses container boundaries.

2018-06-20 22:02 UTC, mhevery commented on packages/core/src/render3/instructions.ts
> +///////////////////////////////
Could we move this section to `i18n.ts`? This file is already to big.

2018-06-20 22:02 UTC, mhevery commented on packages/core/test/render3/i18n_spec.ts
> +    // TODO(ocombe): make this work once PR #24346 has landed
The PR has landed. Can we remove the comment and resolve it?

2018-06-20 22:02 UTC, mhevery commented on packages/core/test/render3/i18n_spec.ts
> +      // Remove the last item
I will merge it in a bit, please resolve this.

2018-06-20 22:02 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +  detached: boolean;
- The comment above says it is `null` but it is `boolean`
- The bigger problem is that this data is on `LNode` which means that we would have to store it in `LViewData` after @kara is finished refactoring. This needs to move to the `TNode`. Since all templates will have their nodes translated same way it should be fine there. This needs to be resolved before we can merge it in.

2018-06-20 22:09 UTC, mary-poppins commented
You can preview b697333 at https://pr24037-b697333.ngbuilds.io/.

2018-06-21 06:55 UTC, ocombe commented on packages/core/src/core_render3_private_export.ts
> -  defineComponent as ɵdefineComponent,
I think I found the mistake, removing the last `,` at the end of the list. I've added it back and it seems to be ok this time.

2018-06-21 08:33 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +              phIndex.toString(2).length, 28, `Index ${phIndex} is too big and will overflow`);
that's what I said to Victor ¯\_(ツ)_/¯

2018-06-21 08:56 UTC, ocombe commented
new fixup commit:
- moved everything into i18n.ts
- fixed reordering of exports for core_render3_private_export.ts
- improved performance for `i18nInterpolationV` and added a test for it
- moved `detached` property to `tNode`
- other small stuff

2018-06-21 09:15 UTC, mary-poppins commented
You can preview ffc36db at https://pr24037-ffc36db.ngbuilds.io/.

2018-06-21 13:01 UTC, vicb commented on packages/core/src/core_render3_private_export.ts
> +  I18nInstruction as ɵI18nInstruction,
`Instruction` sounds usless here and below (you wouldn't name `add(a, b)` `addFunction(a, b)` ?)

2018-06-21 13:02 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +/** Mapping of placeholder names to their absolute index in the current view. */
is this true for expression / embedded templates ?

2018-06-21 13:03 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * indexes of their corresponding expression nodes to return a list of instructions for each
`indexes of their corresponding expression nodes` unclear, as already commented

2018-06-21 13:03 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * template.
template ->template function ?

2018-06-21 13:12 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * @param tmplContainers An array of template container placeholders whose content should be ignored
view containers

2018-06-21 13:13 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * value will be concatenated into the final translation.
+1 - I had the same comment before

2018-06-21 13:16 UTC, vicb commented on packages/core/test/render3/compiler_canonical/i18n_spec.ts
> +  it('should support expressions', () => {
add html to assert html vs expression indexes

2018-06-21 13:17 UTC, vicb commented on packages/core/test/render3/compiler_canonical/i18n_spec.ts
> +  it('should support expressions in attributes', () => {
add a test for attributes without expression (unless there is one already ?)

2018-06-21 13:17 UTC, vicb commented on packages/core/test/render3/compiler_canonical/i18n_spec.ts
> +  it('should support expressions in attributes', () => {
missing a test for embedded templates

2018-06-21 13:18 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +    const i18n_1 = i18nMapping(MSG_DIV_SECTION_1, [{p_0: 1, p_1: 2, p_2: 3, p_3: 4}]);
change the placeholder name: if `<tag> / </tag>` -> `START_TAG` and `END_TAG`

2018-06-21 13:20 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +  describe('containers', () => {
view containers / embedded templates

2018-06-21 13:21 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +      // The indexes are based on each template function
There should be a canonical to assert that the compiler generates the correct code

2018-06-21 13:23 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +          // </ul>
for each test, please give:
- the initial structure (the lines above),
- the translation.

2018-06-21 13:28 UTC, ocombe commented on packages/core/test/render3/compiler_canonical/i18n_spec.ts
> +  it('should support expressions', () => {
there is already a test for that: "should support both html elements, expressions and expressions in attributes"

2018-06-21 13:30 UTC, ocombe commented on packages/core/test/render3/compiler_canonical/i18n_spec.ts
> +  it('should support expressions in attributes', () => {
Attributes without expressions are static attributes, it's already tested in the compiler (nothing required at runtime).
There is a test for embedded templates line ~441

2018-06-21 14:32 UTC, mhevery approved these changes

2018-06-21 14:40 UTC, mhevery commented
http://test/OCL:201522516:BASE:201522609:1529591995239:2f0e49c4

2018-06-21 15:38 UTC, ocombe commented
new fixup commit:
- renamed all tags in the tests to `START_...` / `END_...`
- added a canonical test for embedded templates

2018-06-21 15:47 UTC, mary-poppins commented
You can preview fe62b7b at https://pr24037-fe62b7b.ngbuilds.io/.

2018-06-21 16:08 UTC, mary-poppins commented
You can preview fad434f at https://pr24037-fad434f.ngbuilds.io/.

2018-06-21 19:45 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * indexes of their corresponding expression nodes to return a list of instructions for each
see the design spec.

2018-06-21 20:14 UTC, closed without merging