test api doc for directives
angular/angular pull request #24135
Opened 2018-05-25 19:11 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-06-13 19:48 UTC, mary-poppins commented
You can preview 62cbb1d at https://pr24135-62cbb1d.ngbuilds.io/.

2018-06-13 19:49 UTC, mary-poppins commented
You can preview ea6598d at https://pr24135-ea6598d.ngbuilds.io/.

2018-06-28 18:14 UTC, mary-poppins commented
You can preview 1a7e488 at https://pr24135-1a7e488.ngbuilds.io/.

2018-07-04 16:21 UTC, mary-poppins commented
You can preview e5cdb0f at https://pr24135-e5cdb0f.ngbuilds.io/.

2018-07-09 16:20 UTC, mary-poppins commented
You can preview b29b47f at https://pr24135-b29b47f.ngbuilds.io/.

2018-07-13 15:37 UTC, mary-poppins commented
You can preview c8cc271 at https://pr24135-c8cc271.ngbuilds.io/.

2018-07-13 20:13 UTC, mary-poppins commented
You can preview 4e9ef50 at https://pr24135-4e9ef50.ngbuilds.io/.

2018-07-17 16:20 UTC, mary-poppins commented
You can preview 98b3203 at https://pr24135-98b3203.ngbuilds.io/.

2018-07-18 09:56 UTC, trotyl commented on packages/common/src/directives/ng_switch.ts
> + * more than one case.
How? AFAIK this is a pending feature request: https://github.com/angular/angular/issues/14659.

2018-07-31 16:50 UTC, mary-poppins commented
You can preview 11963ca at https://pr24135-11963ca.ngbuilds.io/.

2018-08-03 17:52 UTC, mary-poppins commented
You can preview d2ef512 at https://pr24135-d2ef512.ngbuilds.io/.

2018-08-06 16:41 UTC, mary-poppins commented
You can preview c8045e1 at https://pr24135-c8045e1.ngbuilds.io/.

2018-08-14 23:15 UTC, mary-poppins commented
You can preview 3bcde99 at https://pr24135-3bcde99.ngbuilds.io/.

2018-08-15 15:46 UTC, mary-poppins commented
You can preview 77ee702 at https://pr24135-77ee702.ngbuilds.io/.

2018-08-15 16:34 UTC, mary-poppins commented
You can preview 0b07dd5 at https://pr24135-0b07dd5.ngbuilds.io/.

2018-08-15 21:38 UTC, mary-poppins commented
You can preview d7d320c at https://pr24135-d7d320c.ngbuilds.io/.

2018-08-15 21:49 UTC, mary-poppins commented
You can preview 277016c at https://pr24135-277016c.ngbuilds.io/.

2018-08-15 22:50 UTC, mary-poppins commented
You can preview 9198d81 at https://pr24135-9198d81.ngbuilds.io/.

2018-08-15 22:54 UTC, mary-poppins commented
You can preview a1adc60 at https://pr24135-a1adc60.ngbuilds.io/.

2018-08-16 18:50 UTC, mary-poppins commented
You can preview b9b5217 at https://pr24135-b9b5217.ngbuilds.io/.

2018-08-16 21:47 UTC, mary-poppins commented
You can preview f271520 at https://pr24135-f271520.ngbuilds.io/.

2018-08-16 22:29 UTC, mary-poppins commented
You can preview f1187d7 at https://pr24135-f1187d7.ngbuilds.io/.

2018-08-16 23:34 UTC, mary-poppins commented
You can preview 11f58f5 at https://pr24135-11f58f5.ngbuilds.io/.

2018-08-17 15:46 UTC, mary-poppins commented
You can preview 2e266de at https://pr24135-2e266de.ngbuilds.io/.

2018-08-17 15:48 UTC, mary-poppins commented
You can preview fd8acc0 at https://pr24135-fd8acc0.ngbuilds.io/.

2018-08-21 15:01 UTC, mary-poppins commented
You can preview 0923fd0 at https://pr24135-0923fd0.ngbuilds.io/.

2018-08-22 15:47 UTC, mary-poppins commented
You can preview c2038a5 at https://pr24135-c2038a5.ngbuilds.io/.

2018-08-29 18:45 UTC, mary-poppins commented
You can preview dee5798 at https://pr24135-dee5798.ngbuilds.io/.

2018-08-30 15:12 UTC, mary-poppins commented
You can preview bb3633e at https://pr24135-bb3633e.ngbuilds.io/.

2018-08-31 15:55 UTC, mary-poppins commented
You can preview 417885e at https://pr24135-417885e.ngbuilds.io/.

2018-09-03 15:13 UTC, mary-poppins commented
You can preview 137cf4e at https://pr24135-137cf4e.ngbuilds.io/.

2018-09-10 20:41 UTC, mary-poppins commented
You can preview 52b06a7 at https://pr24135-52b06a7.ngbuilds.io/.

2018-09-13 15:26 UTC, mary-poppins commented
You can preview 44bc988 at https://pr24135-44bc988.ngbuilds.io/.

2018-09-13 20:43 UTC, petebacondarwin approved these changes

2018-09-13 20:47 UTC, jbogarthyde commented
Passing test - -can @IgorMinar or @mhevery  please approve so we can land this and test Pete's template work.

2018-09-14 15:52 UTC, jbogarthyde commented
Fixing Issue #24896

2018-09-14 15:56 UTC, mary-poppins commented
You can preview 24d1415 at https://pr24135-24d1415.ngbuilds.io/.

2018-09-17 17:38 UTC, mary-poppins commented
You can preview 8027630 at https://pr24135-8027630.ngbuilds.io/.

2018-09-17 18:02 UTC, mary-poppins commented
You can preview 32cc25d at https://pr24135-32cc25d.ngbuilds.io/.

2018-09-18 17:36 UTC, mary-poppins commented
You can preview 5f5dd19 at https://pr24135-5f5dd19.ngbuilds.io/.

2018-09-18 22:13 UTC, mary-poppins commented
You can preview 9d56994 at https://pr24135-9d56994.ngbuilds.io/.

2018-09-19 16:12 UTC, mary-poppins commented
You can preview 3bce52b at https://pr24135-3bce52b.ngbuilds.io/.

2018-09-19 21:17 UTC, mary-poppins commented
You can preview 64a126c at https://pr24135-64a126c.ngbuilds.io/.

2018-09-26 18:04 UTC, mary-poppins commented
You can preview 6ca0027 at https://pr24135-6ca0027.ngbuilds.io/.

2018-09-26 21:34 UTC, mary-poppins commented
You can preview cbeb472 at https://pr24135-cbeb472.ngbuilds.io/.

2018-09-26 21:35 UTC, mary-poppins commented
You can preview c08dfc1 at https://pr24135-c08dfc1.ngbuilds.io/.

2018-09-26 21:38 UTC, mary-poppins commented
You can preview faf50e9 at https://pr24135-faf50e9.ngbuilds.io/.

2018-09-27 16:39 UTC, mary-poppins commented
You can preview a76a3d6 at https://pr24135-a76a3d6.ngbuilds.io/.

2018-10-03 00:47 UTC, jenniferfell requested changes
I've reviewed ng_for_of, viewport_scroller, template_ref, directives and form_control_directive files. Title and commit message should make it clear that this has more than just updates for directives.

2018-10-03 00:47 UTC, jenniferfell commented on packages/forms/src/directives/reactive_directives/form_control_directive.ts
> + * in the associated DOM element (model -> view), and values written to the
In the new forms intro, we used "model-to-view" or "model to view" instead of "model -> view"

2018-10-03 00:47 UTC, jenniferfell commented on packages/forms/src/directives/reactive_directives/form_control_directive.ts
>   * directives (and get/set values using reactive forms patterns) or switch over to
Suggested rewrite: To update your code to the current best practices, first decide whether to use reactive forms or template-driven forms. The two approaches are explained and compared in [Introduction to forms](guide/forms-overview).

2018-10-03 00:47 UTC, jenniferfell commented on packages/forms/src/directives/reactive_directives/form_control_directive.ts
> + * This has been deprecated for several reasons. First, developers have found this pattern
I'm not sure about this positioning. We should definitely get @kara and @IgorMinar to review. 

I would say something like this: 

This pattern has been deprecated because it mixes template-driven and reactive forms approaches, which limits the benefits of each approach and creates unnecessarily complex behaviors. 

* Setting the value in the template violates the template-agnostic principles behind reactive forms.
* Adding a `FormControl`/`FormGroup` layer in the class removes the convenience of defining forms in the template.	  
* Although it seems like the actual `ngModel` directive is being used, an input/output property named `ngModel` on the reactive form directive is being used instead.  That input/output property approximates (some of) the ngModel directive's behavior. Specifically, it allows getting/setting the value and intercepting value events. However, some of the `ngModel` directive's other features&mdash;such as delaying updates with`ngModelOptions` or exporting the directive&mdash;don't work.

2018-10-03 00:47 UTC, jenniferfell commented on packages/forms/src/directives/reactive_directives/form_control_directive.ts
>   * By default, when you use this pattern, you will see a deprecation warning once in dev
Future tense and a "once" that is ambiguous

2018-10-03 00:47 UTC, jenniferfell commented on packages/core/src/metadata/directives.ts
> +   * ### Using animations
Link to animations guide? Not sure why this particular example is included. Remove it now that animations is documented better?

2018-10-03 00:47 UTC, jenniferfell commented on packages/core/src/metadata/directives.ts
> +   * Removing whitespace can greatly reduce AOT-generated code size, and speed up view creation.
Comma and missing word: Removing whitespace can greatly reduce AOT-generated code size and speed up view creation.  As of Angular 6, the default

2018-10-03 00:47 UTC, jenniferfell commented on packages/core/src/metadata/directives.ts
> +   * Current implementation removes whitespace characters as follows:
The current implementation..
or maybe remove the idea that this implementation is ever-changing...

The AOT compiler removes whitespace characters as follows:

2018-10-03 00:47 UTC, jenniferfell commented on packages/core/src/metadata/directives.ts
> +   * `<button>Action 1</button><button>Action 2</button>`.
Where my screen broke this line, I couldn't see the difference. Perhaps:
 For example, it removes the white space between button element definitions, so `<button>Action 1</button>  <button>Action 2</button>` becomes `<button>Action 1</button><button>Action 2</button>`.

2018-10-03 00:47 UTC, jenniferfell commented on packages/core/src/metadata/directives.ts
> +   * Current implementation removes whitespace characters as follows:
Question: Do you think the details about what is removed should be here or in the AOT compiler option description for preserveWhitespaces? Should this focus on taking the compiler option and applying it to select subsets of the HTML, and link to the AOT compiler doc for details on preserving whitespace in general? 

(And perhaps the AOT doc should refer readers here if they want to change the setting for a subset of their template?)

2018-10-03 00:47 UTC, jenniferfell commented on packages/common/src/viewport_scroller.ts
>     * See also [window.history.scrollRestoration
Needs . at the end

2018-10-03 00:47 UTC, jenniferfell commented on packages/common/src/viewport_scroller.ts
> +>>>>>>> docs: cleanup
What is this? Why only here and not in every place where "Empty implementation" occurs? Is this a comment that you need an engineer to provide more information? If so, let's get that info rather than publish with docs: cleanup annotations. Move this file/work to another PR?

2018-10-03 00:51 UTC, jenniferfell commented
@IgorMinar We'll need your technical review on this PR (or another team member who can review forms, core, common). 

Also, there's a reference in the Form API about deprecation: "Support for using the ngModel input property and ngModelChange event with reactive form directives has been deprecated in Angular v6 and will be removed in Angular v7." I don't think that matches the stated deprecation policy. Recommended replacement? (@jbogarthyde @brandonroberts The replacement will need to be propagated to other forms API docs as well.)

2018-10-03 00:52 UTC, jenniferfell commented
@jbogarthyde I changed labels, because we can't have PR action: merge-assistance until everything under our control (pull approvals) is green and we are also ready to mark with PR action: merge.

2018-10-03 16:03 UTC, jbogarthyde commented on packages/common/src/directives/ng_for_of.ts
>   * ### Example
Done. Issue #26235

2018-10-03 16:03 UTC, mary-poppins commented
You can preview d207ea9 at https://pr24135-d207ea9.ngbuilds.io/.

2018-10-03 16:08 UTC, jbogarthyde commented on packages/forms/src/directives/reactive_directives/form_control_directive.ts
>   * Support for using the `ngModel` input property and `ngModelChange` event with reactive
Changing to "removed in v8" -- unless @IgorMinar tells me otherwise.

2018-10-03 16:10 UTC, jbogarthyde commented on packages/forms/src/directives/reactive_directives/form_control_directive.ts
>   *
We do if we can figure it out. There are a lot of existing examples with no intros, so in the interest of getting the pages generally updated, I have not attempted to get the description if it is not obvious to me. 
Maybe @brandonroberts can give me a description of what this example shows.

2018-10-03 16:20 UTC, jbogarthyde commented on packages/core/src/metadata/directives.ts
> +   * ### Using animations
Actually, this is where that example came from. It was buried here, and was the only Component metadata property that had any doc at all.  Since that property now refers to the guide, I'll take this out.

2018-10-03 16:28 UTC, jbogarthyde commented on packages/common/src/viewport_scroller.ts
> +>>>>>>> docs: cleanup
Conflict - resolved.

2018-10-03 16:38 UTC, mary-poppins commented
You can preview 1c1fbe1 at https://pr24135-1c1fbe1.ngbuilds.io/.

2018-10-04 16:29 UTC, mary-poppins commented
You can preview 77de074 at https://pr24135-77de074.ngbuilds.io/.

2018-10-04 18:13 UTC, mary-poppins commented
You can preview b3a1de6 at https://pr24135-b3a1de6.ngbuilds.io/.

2018-10-05 15:33 UTC, mary-poppins commented
You can preview c1f5e30 at https://pr24135-c1f5e30.ngbuilds.io/.

2018-10-05 17:29 UTC, mary-poppins commented
You can preview 054737c at https://pr24135-054737c.ngbuilds.io/.

2018-10-08 18:51 UTC, mary-poppins commented
You can preview cf57520 at https://pr24135-cf57520.ngbuilds.io/.

2018-10-10 21:14 UTC, mary-poppins commented
You can preview a463606 at https://pr24135-a463606.ngbuilds.io/.

2018-10-10 22:09 UTC, jbogarthyde commented
@jenniferfell Your requested changes were incorporated - please remove blocker.

2018-10-16 16:52 UTC, mary-poppins commented
You can preview 9b5e60b at https://pr24135-9b5e60b.ngbuilds.io/.

2018-10-17 18:13 UTC, mary-poppins commented
You can preview b55789f at https://pr24135-b55789f.ngbuilds.io/.

2018-10-18 20:29 UTC, jenniferfell commented
Pls change: Support for using ... has been deprecated in Angular v6.

Don't mention when support will be removed. Thx

2018-10-19 22:05 UTC, jbogarthyde commented
@jenniferfell Your requested changes were incorporated - please remove blocker.

2018-10-19 22:10 UTC, mary-poppins commented
You can preview f2041c2 at https://pr24135-f2041c2.ngbuilds.io/.

2018-10-22 17:01 UTC, IgorMinar requested changes
I was able to review just the ngFor section so far. One piece of feedback on that one is that we should decide how to refer to the symbol being documented. Here is the issue - developers can refer to the symbol in three different ways:

- `NgForOf` class name - this is the class that implements the functionality, but for most developers this is just an implementation detail and 99% of developers can live happily not knowing that NgForOf even exists. Currently our documentation focuses on this name, which seems counterintuitive and surprising to the unsuspecting reader.
- `ngFor` selector - this is the selector that is used in a template and is the main name developers would use to refer to this directive. (please note that there is also an `ngForOf` selector that needs to be used *in addition* (not instead) of `ngFor` if the developers use the long form syntax.

2018-10-22 19:19 UTC, mary-poppins commented
You can preview 8a79685 at https://pr24135-8a79685.ngbuilds.io/.

2018-10-22 21:02 UTC, mary-poppins commented
You can preview 1bca278 at https://pr24135-1bca278.ngbuilds.io/.

2018-10-23 19:09 UTC, mary-poppins commented
You can preview 374a75a at https://pr24135-374a75a.ngbuilds.io/.

2018-10-30 15:23 UTC, mary-poppins commented
You can preview 824fdcc at https://pr24135-824fdcc.ngbuilds.io/.

2018-10-31 19:54 UTC, mary-poppins commented
You can preview 4ef664f at https://pr24135-4ef664f.ngbuilds.io/.

2018-11-02 15:35 UTC, mary-poppins commented
You can preview c93efba at https://pr24135-c93efba.ngbuilds.io/.

2018-11-12 16:17 UTC, mary-poppins commented
You can preview 2729dd4 at https://pr24135-2729dd4.ngbuilds.io/.

2018-11-13 16:43 UTC, mary-poppins commented
You can preview 95f7f13 at https://pr24135-95f7f13.ngbuilds.io/.

2018-11-13 20:51 UTC, mary-poppins commented
You can preview a1e7273 at https://pr24135-a1e7273.ngbuilds.io/.

2018-11-16 16:43 UTC, mary-poppins commented
You can preview 3583dbb at https://pr24135-3583dbb.ngbuilds.io/.

2018-11-18 06:56 UTC, trotyl commented on packages/common/src/directives/ng_for_of.ts
> + * `<li *ngFor="let item of items; index as i; trackBy: trackByFn">...</li>`
Also, is there any chance to document [the syntax of `*` micro-syntax itself](https://github.com/angular/angular/issues/24961#issuecomment-406000798) besides specific directive API?
There've been many people thought `NgForOf` and `NgIf` having their own syntax rules.

2018-11-21 01:02 UTC, jbogarthyde commented on packages/common/src/directives/ng_for_of.ts
> + * `<li *ngFor="let item of items; index as i; trackBy: trackByFn">...</li>`
@jenniferfell Can you put this in the doc backlog? The only current doc I could find is here - hard to find, and not all that clear.
https://angular.io/guide/structural-directives#the-asterisk--prefix

2018-11-21 17:35 UTC, jenniferfell commented on packages/common/src/directives/ng_for_of.ts
> + * `<li *ngFor="let item of items; index as i; trackBy: trackByFn">...</li>`
Will do

2018-11-26 17:10 UTC, mary-poppins commented
You can preview 19d7af5 at https://pr24135-19d7af5.ngbuilds.io/.

2018-11-27 16:49 UTC, mary-poppins commented
You can preview fb33966 at https://pr24135-fb33966.ngbuilds.io/.

2018-11-28 23:17 UTC, mary-poppins commented
You can preview eaa716c at https://pr24135-eaa716c.ngbuilds.io/.

2018-11-29 20:29 UTC, mary-poppins commented
You can preview ef08c0d at https://pr24135-ef08c0d.ngbuilds.io/.

2018-11-29 20:37 UTC, jbogarthyde commented on packages/forms/src/directives/reactive_directives/form_control_directive.ts
>   *
Looks like this got done in Brandon's forms-directive PR that already landed. That supersedes this, not doing anymore to this one in this PR.

2018-11-29 20:39 UTC, mary-poppins commented
You can preview e9678c6 at https://pr24135-e9678c6.ngbuilds.io/.

2018-11-30 07:57 UTC, petebacondarwin commented on packages/common/src/directives/ng_style.ts
> + * Sets one or more style propeties, specified as key-value pairs.
typo: properties

2018-11-30 20:41 UTC, jbogarthyde commented
Broken up into individual PRs for each file:
https://github.com/angular/angular/pull/27376
https://github.com/angular/angular/pull/27377
https://github.com/angular/angular/pull/27378
https://github.com/angular/angular/pull/27379
https://github.com/angular/angular/pull/27380
https://github.com/angular/angular/pull/27381

2018-11-30 20:41 UTC, closed without merging