docs(aio): Add notes on manual sanitization to guides/security.md
angular/angular pull request #24176
Opened 2018-05-29 13:50 UTC by rjamet

Some users have remarked that there's no explanation on how to manually call sanitization, so add a few lines on that. Doc-only change.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
No explanations on how to call Angular's sanitization directly

## What is the new behavior?
Explain that, in the contexts where it makes sense to use it (i.e. not in a template)

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2018-05-29 14:17 UTC, mary-poppins commented
You can preview 566339d at https://pr24176-566339d.ngbuilds.io/.

2018-05-29 14:20 UTC, gkalpak approved these changes

2018-05-29 14:20 UTC, gkalpak commented on aio/content/guide/security.md
> +[`DomSanitizer.sanitize`](/api/platform-browser/DomSanitizer#sanitize) method with the
Nit: `/api/...` could be `api/...` (without the leading slash).
<sub>It doesn't make any difference now, but it could in the future.</sub>

2018-05-29 14:53 UTC, rjamet commented on aio/content/guide/security.md
> +[`DomSanitizer.sanitize`](/api/platform-browser/DomSanitizer#sanitize) method with the
Fixed, thanks.

2018-05-30 07:38 UTC, mary-poppins commented
You can preview bc69b1a at https://pr24176-bc69b1a.ngbuilds.io/.

2018-07-11 13:18 UTC, brandonroberts requested changes

2018-07-11 13:18 UTC, brandonroberts commented on aio/content/guide/security.md
> +
I would update this to

`
For cases where this is unavoidable, use the built-in Angular sanitization functions. Sanitize untrusted values with the [`DomSanitizer.sanitize`](api/platform-browser/DomSanitizer#sanitize) method and the appropriate `SecurityContext`. That function accepts values that are not sanitized but marked as trusted using the `bypassSecurityTrust...` functions as [described below](#bypass-security-apis).
`

2018-07-11 13:20 UTC, brandonroberts commented
Thanks for the PR @rjamet! I left you some feedback. Will you also rebase on master and update the git commit message to `docs: Add notes on manual sanitization to security guide`

Thanks

2018-07-17 15:58 UTC, rjamet commented on aio/content/guide/security.md
> +
Ok for the first part, but how about 

```
That function also accepts values that were marked as trusted using the `bypassSecurityTrust`... functions, and will not sanitize them, as [described below](#bypass-security-apis).
```
for that last sentence ? I'm having a bit of trouble with saying that these blessed values will pass through without being altered.

2018-07-17 16:51 UTC, brandonroberts commented on aio/content/guide/security.md
> +
That works for me

2018-07-17 17:14 UTC, rjamet commented on aio/content/guide/security.md
> +
Done, and fixed the commit message as well.

2018-07-17 17:34 UTC, mary-poppins commented
You can preview 8ebb9da at https://pr24176-8ebb9da.ngbuilds.io/.

2018-07-17 17:49 UTC, brandonroberts approved these changes

2018-07-20 17:28 UTC, closed without merging