fix(elements): initialization should run in ngZone (#24181)
angular/angular pull request #24185
Opened 2018-05-29 19:04 UTC by remackgeek

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #24181 
When an angular element is created outside the angular zone, such as in setTimeout(), automatic change detection no longer works

## What is the new behavior?
during connect(), initializeComponent is always called in the angular zone

## Does this PR introduce a breaking change?
```
[ ] Yes
[ x] No
```

## Other information
@JiaLiPassion this is based/extends on your PR 23885, please review

2018-05-30 01:35 UTC, JiaLiPassion commented
@remackgeek , sure, I think a demo to describe this issue will be helpful. So your use case is you will create the `Angular Elements` dynamically with such as `setTimeout`?

2018-05-30 03:16 UTC, remackgeek commented
Here's a quick demo, the top one is broken using setTimeout, the bottom one
works inline:
https://stackblitz.com/edit/angular-12t6rr?file=src%2Findex.html


Conceptually it is similar to this:
https://stackblitz.com/edit/angular-dxu5td?file=src%2Fmain.ts in the bug
https://github.com/angular/angular/issues/24181

On Tue, May 29, 2018 at 6:36 PM, JiaLiPassion <notifications@github.com>
wrote:

> @remackgeek <https://github.com/remackgeek> , sure, I think a demo to
> describe this issue will be helpful. So your use case is you will create
> the Angular Elements dynamically with such as setTimeout?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/24185#issuecomment-393002004>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXEyV1qzRSP-2oiGNAxD8pwIZjqkIqGLks5t3fehgaJpZM4USDOz>
> .
>

2018-05-30 23:28 UTC, gkalpak reviewed
Wouldn't the same issue affect things like `detectChanges()` and `destroy()`?

2018-06-03 20:09 UTC, remackgeek commented
@gkalpak, yes. Please see the latest update -- if you choose zone behavior, this wraps all the strategy methods.

2018-06-04 12:55 UTC, gkalpak commented on packages/elements/src/component-factory-strategy-zone.ts
> +  disconnect() { this.insureAngularZone(super.disconnect); }
Wouldn't this cause `this` to be undefined inside `super.disconnect`?

2018-06-04 20:31 UTC, robwormald commented on packages/elements/src/component-factory-strategy-zone.ts
> + * extends ComponentNgElementStrategy to insure callbacks run in the Angular zone
*ensure

2018-06-04 20:31 UTC, robwormald commented on packages/elements/src/component-factory-strategy-zone.ts
> +  private insureAngularZone(fn: () => any) {
*ensure

would this be better named as `runInZone` or similar?

2018-06-04 20:31 UTC, robwormald commented on packages/elements/src/component-factory-strategy-zone.ts
> +  disconnect() { this.insureAngularZone(super.disconnect); }
yeah, and its inconsistent with the line above it.

2018-06-05 03:52 UTC, remackgeek commented
@gkalpak, @robwormald thanks for the review. Updated.

2018-06-19 03:36 UTC, LinBoLen commented
I picked `ComponentNgElementZoneStrategyFactory` out. and it works.

2018-07-24 07:43 UTC, krawetko commented
@robwormald remackgeek what are your plans for this change? In my company we have many Angular Components and having the opportunity to export them as WebComponent and integrate in other non Angular applications (with Zones/Change Detection working out of the box) is a huge use case and argument to move a lot of development into Angular Components.

2018-08-14 14:54 UTC, kseamon commented
Does this ensure that external callbacks attached to our @Outputs run outside of the Angular zone? I'd think that's desirable for performance and encapsulation reasons.

The existing code in this PR would ensure that we re-enter the zone on @Input, so it should be safe as well.

2018-08-14 15:11 UTC, kseamon requested changes

2018-08-14 15:11 UTC, kseamon commented on packages/elements/src/component-factory-strategy-zone.ts
> +  constructor(protected componentFactory: ComponentFactory<any>, protected injector: Injector) {
No need for these to be protected here - the superclass already takes care of assigning them to itself.

2018-08-14 15:11 UTC, kseamon commented on packages/elements/src/component-factory-strategy.ts
> +  constructor(protected componentFactory: ComponentFactory<any>, protected injector: Injector) {}
protected readonly

2018-08-14 15:11 UTC, kseamon commented on packages/elements/src/component-factory-strategy-zone.ts
> +  private ngZone: NgZone;
readonly

2018-08-14 18:33 UTC, kseamon commented
To clarify my output runOutsideAngular suggestion, it would look something like this:

initializeOutputs() {
  // Sets this.events
  super.initializeOutputs();

  this.events = this.events.pipe(runOutsideAngularZone(this.ngZone));
}

function runOutsideAngularZone(ngZone: NgZone) {
  return <T>(source: Observable<T>) => NgZone.isInAngularZone() ?
      new Observable<T>((observer) => source.subscribe({
           next: (value) => zone.runOutsideAngular(() => observer.next(value)),
           error: (err) => observer.error(err),
           complete: () => observer.complete()
         })) : 
      source;
}

2018-08-20 00:01 UTC, remackgeek commented
@kseamon, wouldn't there be cases where you want the event to be in the zone? Say a third-party element being used in an Angular SPA.

2018-08-20 11:12 UTC, tnicola commented on packages/elements/src/component-factory-strategy-zone.ts
> +  private runInZone(fn: () => any) { return NgZone.isInAngularZone() ? fn() : this.ngZone.run(fn); }
Remove NgZone.isInAngularZone() check. If we are are in a micro-frondend situation (an Angular shell app with many angular components imported from different js angular bundles), this condition will return true, because we always are in a AngularZone, but the wrong one to perfom change detection: the shell, we need to run the code in the element zone instead, in order to get the change detection ( AppReference.tick()) working for the element.

On the other hand, in a normal situation with just one angular shell and elements created from the inside, it won't be a problem to call ngZone.run(), it should cost zero, so the "zone check" could be safely removed.

You can find the PoC and more details in this PR: remackgeek/elements-zone-strategy#2.

2018-08-20 15:41 UTC, kseamon commented
Per @tnicola's comment, each child app would have it's own ngZone, so leaving it should be fine and would not cause the parent app to leave its own zone.

2018-08-20 20:45 UTC, tnicola commented
@kseamon You're right, each child would have its own NgZone instance indeed. Each child has also its own ApplicationRef instance (responsible for ticking the change detection in its own zone).

Lets suppose the following scenario: shell (the angular parent), childA, childB (angular children apps). Shell would have ngZoneRoot instance and appRefRoot intances, childA would have ngZoneA and appRefA instances, childB would have ngZoneB and appRefB instances. 

Then, if we're in the shell and we connect to childA, `NgZone.isInAngularZone()` would return true because we're in a Angular zone, the ngZoneRoot one. At that point we decided to not run in the childA zone and to remain in the ngZoneRoot. Then Change Detection won't work for our childA! Why? Because all the childA events patched from zone, would be quequed as tasks in ngZoneA, then, appRefA should wait the the task list to be empty to perform the change detection. This won't ever happen! Why? Because we decided to not run the code in the child Zone and the tasks will be added to ngZoneRoot.

So, leaving the `NgZone.isInAngularZone()` means that CD for children will fail. On the other hand, running the child code, in the child zone seems a more natural solution.
You can have a look to this PR: remackgeek/elements-zone-strategy#2. There's a demonstration of what I'm saying.

2018-08-26 23:43 UTC, remackgeek commented
To support the multiple ngZone case, maybe there should be an instance-level method for checking if the current zone is *this* ngZone (since you can't get at _inner without cheating)? 
@JiaLiPassion, do you have any thoughts on this?

2018-08-27 07:49 UTC, JiaLiPassion commented
@remackgeek, yeah, I am working on a `scoped zone` in `zone.js`, so in theory, we can have separate `zone` per `Angular Element`. https://github.com/angular/zone.js/pull/1126

2018-08-28 02:46 UTC, remackgeek commented
So, to summarize the various threads to make sure I'm following everything:

1) To support the multiple ngZone case, the wrappers should always call **ngZone.run()**, because the **NgZone.isInAngularZone()** check doesn't distinguish between ngZones. This will add performance overhead to the case where the wrapper is already in the correct ngZone.  [PR 1126](https://github.com/angular/zone.js/pull/1126) should address this.

2) In all cases, the strategy should avoid leaking it's ngZone in callbacks, so the connect wrapper should capture **Zone.current** before running in the ngZone and run the callback events in that zone.

This should handle the 3 broad use cases:
1) The outer zone is the same ngZone as the element -- both the element and the host belong to the same angular application.
2) The outer zone is the root zone -- the element was created in a setTimeout() or similar.
3) The outer zone is another ngZone -- the host is an angular app consuming separately built angular elements.

2018-09-04 02:53 UTC, remackgeek commented
@tnicola, I updated the PR to check the specific ngZone while waiting for [PR 1126 ](https://github.com/angular/zone.js/pull/1126) land

@kseamon, I did some testing -- the event handlers for the outputs already run in the zone they were created in, so I'm not sure where there would be a performance gain changing zones in the Observable. But the mechanics of zones are black magic to me, so let me know if I missed something.

2018-09-04 12:02 UTC, kseamon commented
Can you include a unit test to verify that going forward? Thanks.

Sent from my iPhone

> On Sep 3, 2018, at 10:56 PM, remackgeek <notifications@github.com> wrote:
> 
> @tnicola, I updated the PR to check the specific ngZone while waiting for PR 1126 land
> 
> @kseamon, I did some testing -- the event handlers for the outputs already run in the zone they were created in, so I'm not sure where there would be a performance gain changing zones in the Observable. But the mechanics of zones are black magic to me, so let me know if I missed something.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-09-09 17:08 UTC, JiaLiPassion commented
I created a PR in `zone.js` here, https://github.com/angular/zone.js/pull/1133, it will patch all `CustomElement v1` APIs, so this issue will not exist if we run `customElements.define` in `ngZone`.

2018-09-11 20:43 UTC, robwormald commented
@JiaLiPassion 's PR has landed in zone.js, so I'd appreciate people testing against that and letting us know about any changes

2018-09-12 00:57 UTC, JiaLiPassion commented
@robwormald, sure, I will test it!

2018-09-12 13:55 UTC, remackgeek commented
I ran my examples and everything worked as expected. Thanks, @JiaLiPassion !

Will the next version of zone.js be released with Angular 7?

2018-09-12 16:18 UTC, JiaLiPassion commented
@remackgeek, thanks for the confirmation, I am not sure the `release date`, several PRs are still pending review.

2018-09-16 01:09 UTC, remackgeek commented
@JiaLiPassion , I did some more testing and I did find an issue. Your PR doesn't seem to also fix [#23841](https://github.com/angular/angular/issues/23841), while this one does.  I have example code [here](https://github.com/remackgeek/ngElementForLoop). A live example is [here](https://remackgeek.github.io/ngElementForLoop/new-zone/index.html)

2018-09-16 05:56 UTC, JiaLiPassion commented
@remackgeek, thank you for the testing, yes, it will not work because we still need to update the `customElement` code here, https://github.com/angular/angular/blob/master/packages/elements/src/create-custom-element.ts#L187, to make sure the `propertyChange` also in `ngZone`.
Because `zone.js` not released, so we have to make this change after a new release of `zone.js`.

2020-06-23 15:23 UTC, gkalpak reviewed
@remackgeek, as mentioned in https://github.com/angular/angular/pull/37416#issuecomment-648180446 we have decided this is a valueable fix to get into `@angular/elements`. Are you still interested in working on this?

To be discussed/determined:
- [ ] I noticed the implementation here is different than the one in [remackgeek/elements-zone-strategy/.../element-zone-strategy.ts][1]. Am I correct to assume that the implementation in this PR is more performant (when already in the zone) and covers more usecases? Is there any downside (once we address `Zone` being potentially undefined)?
- [ ] If we can ensure there is no extra overhead when already inside the zone, then I would be tempted to incorporate the fix into `ComponentNgElementStrategy`.

[1]: https://github.com/remackgeek/elements-zone-strategy/blob/a507e63203efcf414a6979068ea29717828cf582/projects/elements-zone-strategy/src/lib/element-zone-strategy.ts

2020-06-24 02:29 UTC, remackgeek commented
@gkalpak, I'd be happy to work on this!

I'd guess that the PR version is more performant and handles the same cases, but I'm not a zone wizard. I shamelessly lifted the basic pattern from  @JiaLiPassion in [PR23885.](https://github.com/angular/angular/pull/23885).

It would be cool to put this in ComponentNgElementStrategy, but then don't you lose the ability to tree-shake out the zone stuff for zoneless users?

2020-06-24 11:06 UTC, gkalpak commented
> don't you lose the ability to tree-shake out the zone stuff for zoneless users

Not sure 🤔 Why would that be the case? What part would prevent the tree-shaking?
Oh, are you referring to the `NgZone` class?

2020-06-25 15:01 UTC, remackgeek commented
I did some quick-and-dirty performance checking -- on my machine, the overhead for wrapping in ngZone.run() is about 20ms for 1 million calls. The overhead for comparing zones in the "already in zone" case is lost in the noise.
If you're not worried about tree-shaking ngZone, I'll put together a PR to modify `ComponentNgElementStrategy`.

2020-06-25 16:57 UTC, gkalpak commented
I don't think `NgZone` would get tree-shaken anyway (due to how it is loaded), so I would go for it.

2020-06-29 01:06 UTC, remackgeek commented
The new PR is here: [#37814](https://github.com/angular/angular/pull/37814).

2020-06-29 12:57 UTC, gkalpak commented
Thx, @remackgeek :sparkles:
Closing this PR in favor of #37814.

2020-06-29 12:57 UTC, closed without merging