docs: describe rounding behaviour of "DecimalPipe" (#24038)
angular/angular pull request #24303
Opened 2018-06-05 09:08 UTC by s-gbz

Document that DecimalPipe incorrectly rounds negative numbers when the fraction is .5.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #24038 

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

2018-06-05 11:53 UTC, s-gbz commented
**2 failing, 2 pending, and 6 successful checks**

Can someone help me out?
- [Travis CI failed](https://travis-ci.org/angular/angular/jobs/388205652)
  - But I only changed docs.
- google3 Pending — Googler: run g3sync presubmit 24303  
  - What kind of check is this?

2018-06-05 20:38 UTC, vicb commented on packages/common/src/pipes/number_pipe.ts
> + * Keep in mind that negative numbers with a fraction of .5 will be rounded up
I would:
- remove "Keep in mind that" 
- inline the example (easier to check in the code)
- specify that the behavior is different from `Math.round()`

2018-06-05 20:38 UTC, vicb requested changes
Thanks for the PR.

See inline comment for suggestions

2018-06-05 20:41 UTC, vicb commented
> run g3sync presubmit 24303

This is tests we run on our internal code base. No need to worry for docs only changes.

2018-06-07 22:20 UTC, vicb commented
@s-gbz could you please update your PR with the comments ? Thanks

2018-06-08 05:43 UTC, s-gbz commented
Hello @vicb , yes I'm on it now 👍

2018-06-18 17:49 UTC, s-gbz commented
@vicb could you take a look if it's alright now?

2018-06-20 18:52 UTC, ocombe commented on packages/common/src/pipes/number_pipe.ts
> + * <a href="https://en.wikibooks.org/wiki/Arithmetic/Rounding">here</a>.
Could you use a markdown link instead of html please?

```ts

2018-06-20 18:53 UTC, ocombe commented on packages/common/src/pipes/number_pipe.ts
> + * <code-example language="typescript">
it's not `typescript`

2018-06-20 19:13 UTC, mary-poppins commented
You can preview c375b2d at https://pr24303-c375b2d.ngbuilds.io/.
You can preview 3664e31 at https://pr24303-3664e31.ngbuilds.io/.
You can preview 216acdb at https://pr24303-216acdb.ngbuilds.io/.
You can preview 525475b at https://pr24303-525475b.ngbuilds.io/.

2018-06-21 12:16 UTC, mary-poppins commented
You can preview 3843cd3 at https://pr24303-3843cd3.ngbuilds.io/.

2018-06-21 12:19 UTC, HoangBaLinh commented
Ru i

Vào 21 thg 6, 2018 19:18, "Mary Poppins" <notifications@github.com> đã viết:

You can preview 3843cd3
<https://github.com/angular/angular/commit/3843cd37e41c1f7ca3bcc7e1c127934478a4953b>
at https://pr24303-3843cd3.ngbuilds.io/.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/angular/angular/pull/24303#issuecomment-399083349>, or mute
the thread
<https://github.com/notifications/unsubscribe-auth/ATKcOBbju9CvV9U9PVhz-cfGWcEotg9qks5t-48IgaJpZM4Uabrh>
.

2018-06-21 17:34 UTC, jbogarthyde requested changes
Thanks, this was definitely needed.  This is a great addition.

Note that there is another PR set to merge ( https://github.com/angular/angular/pull/24141) that rewrites this and other pipe doc to be compatible with the new Reference doc templates and style guidelines.  
Perhaps you can rebase on that, once it merges. The whole section on rounding should probably go under the new `@usageNotes` tag.

Here's a copy edit for reference-doc style considerations.

2018-06-21 17:34 UTC, jbogarthyde commented on packages/common/src/pipes/number_pipe.ts
> + *
Thanks, this was definitely needed. Here's a copy edit for reference-doc style considerations.

2018-06-21 17:34 UTC, jbogarthyde commented on packages/common/src/pipes/number_pipe.ts
> + * [here](https://en.wikibooks.org/wiki/Arithmetic/Rounding).
--  the function rounds... (rather than repeating this fn name).
-- instead of "as described", try "using this  [rounding method](link)."

2018-06-21 17:34 UTC, jbogarthyde commented on packages/common/src/pipes/number_pipe.ts
> + * <code-example>
... from that of the JavaScript `Math.round()` function.

2018-06-21 17:34 UTC, jbogarthyde commented on packages/common/src/pipes/number_pipe.ts
> + * </code-example>
I don't think this is actually a code example. How about:
For example, in the following case, the pipe rounds down, where the `Math.round()` function rounds up:
```
-2.5 | number:'1.0-0' 
   > -3
    Math.round(-2.5)
   > -2
```

2018-06-21 17:34 UTC, jbogarthyde commented on packages/examples/common/pipes/ts/number_pipe.ts
> +    <p>-2.5 (1.0-0): {{-2.5 | number:'1.0-0'}}</p>
I think they only expect that if they are comparing it to Math.round().
Maybe, instead of "expected", something like  " / rounds down, unlike Math.round()".

2018-06-21 18:03 UTC, s-gbz commented
Thank's a lot for the review @jbogarthyde! 
I will wait until your PR is merged and update accordingly.

I have a hard time handling the necessary tests, because they seem to be failing randomly, or stop working at all. Could you help me out via mail/skype or refer to someone who can?

2018-06-21 18:19 UTC, jbogarthyde commented
You're actually doing pretty well with the tests - Travis build often fails for reasons unrelated to your PR. Next time it might work. 
When it gets closer to mergeable, you can request assistance by adding the label `PR action: merge-assistance`.

2018-06-25 19:02 UTC, jbogarthyde commented
The Pipes rewrite (24141) just landed - look out for it to hit master any time now :-)

2018-06-29 07:28 UTC, mary-poppins commented
You can preview e019b39 at https://pr24303-e019b39.ngbuilds.io/.

2018-06-29 07:43 UTC, mary-poppins commented
You can preview f981f6b at https://pr24303-f981f6b.ngbuilds.io/.

2018-06-29 07:47 UTC, mary-poppins commented
You can preview e89a4c8 at https://pr24303-e89a4c8.ngbuilds.io/.

2018-06-30 06:47 UTC, mary-poppins commented
You can preview 08bd46f at https://pr24303-08bd46f.ngbuilds.io/.

2018-07-02 16:36 UTC, jbogarthyde reviewed
Very minor edit - function name should be code font:
the `Math.round()` function...

2018-07-02 19:05 UTC, s-gbz commented
Thanks for your support @jbogarthyde 👍 
All we need now is @vicb's blessing.

2018-07-02 19:11 UTC, mary-poppins commented
You can preview efb2972 at https://pr24303-efb2972.ngbuilds.io/.

2018-07-05 20:08 UTC, vicb approved these changes
Thanks !

2018-07-05 20:16 UTC, vicb commented
merge-assistance: docs only, does not affect g3

2018-07-05 20:19 UTC, jbogarthyde approved these changes

2018-07-06 17:14 UTC, closed without merging