fix(router): allow using query params without '='
angular/angular pull request #24354
Opened 2018-06-07 19:51 UTC by martinsik

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

There's no way we can create query params such as `foo&bar`. The only closest solution is `foo=&bar=` where their values are parsed as empty strings.

Parameters with `undefined` and `null` value are ignored

Issue Number: #23714

## What is the new behavior?

New behavior is as follows:

- `undefined` - `[queryParams]="{foo: undefined, bar: 1}"` - param is ignored => `bar=1`
- `null` - `[queryParams]="{foo: null, bar: 1}"` - param is added without "=" char => `foo&bar=1`
- `''` - `[queryParams]="{foo: '', bar: 1}"` - param is added with "=" char => `foo=&bar=1`

## Does this PR introduce a breaking change?

- [X] Yes
- [ ] No

## Other information

2018-06-07 19:51 UTC, martinsik commented
I didn't want to update docs until I get permission from someone competent that this changes make sense :).

2018-06-08 07:09 UTC, martinsik commented
Actually I don't know why the integration tests failed with:
```
08 06 2018 06:47:14.722:INFO [Chrome 63.0.3239 (Linux 0.0.0)]: Connected on socket gztp2AhJ-CjzV5aaAAAA with id 21818362
08 06 2018 06:47:36.851:WARN [Chrome 63.0.3239 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
Chrome 63.0.3239 (Linux 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.
Chrome 63.0.3239 (Linux 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.

Chrome 63.0.3239 (Linux 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.

error Command failed with exit code 1.
```

2020-03-30 08:25 UTC, martinsik commented
The failing test is because the bundle size increased but it looks like the expected size was already outdated. [It expects `226144` bytes](https://github.com/angular/angular/blob/master/integration/_payload-limits.json#L52) but when I run the same integration test locally the same bundle has `226631`. With this PR the same bundle has `226666`.

2020-08-10 15:41 UTC, atscott requested changes
Hi @martinsik, given that this is a breaking change (note all the tests that needed to be changed) and wouldn't be easy to fix with an automated migration, the best we could do to land this would be to make it an opt-in feature in `ExtraOptions` that's disabled by default. That said, I'm not sure this provides enough value to warrant that. Since the issue was reported in 2018, there hasn't been much activity on it so I can't say this is something many people want. 

If you feel strongly that this should be supported, please make it an opt-in option and provide some justification for the use-case. Otherwise, feel free to close this. We can keep the issue itself open for tracking purposes and that will always maintain a link to this PR even if it's closed.

2020-10-09 20:51 UTC, jelbourn commented
Revisiting older issues and PRs. Going to close this since we don't have a strong enough signal for this feature.

2020-10-09 20:51 UTC, closed without merging