feat(ivy): namespaced attributes added to output instructions
angular/angular pull request #24386
Opened 2018-06-08 22:29 UTC by benlesh

NOTE: This does NOT add parsing of namespaced attributes

- Adds AttributeMarker for namespaced attributes
- Adds test for namespaced attributes
- Updates AttributeMarker enum to use CamelCase, and not UPPER_CASE names

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently there is no output instruction handling for attributes with namespacing on elements

Issue Number: N/A

## What is the new behavior?

`element` and `elementStart` will support arrays of attributes that allow for namespaced elements to be passed in like so:

```
[AttributeMarker.NamespaceURI, 'http://someuri', 'prefix:name', 'value']
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Related to #23899

2018-06-08 22:36 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +        i += 2;
nit: might be less confusing to NOT increment in the `for(i += 2)` and increment in each case ? I had to compute 2+2 to make this you were right ;)

2018-06-08 22:38 UTC, vicb commented on packages/core/src/render3/node_selector_matcher.ts
> +      step = 4;
looks wrong to me as we never reset to 2 ?
again I think `i += step` is confusing. Remove it from the `for()` and increment `i` in an `if/else/else`

2018-06-08 22:41 UTC, vicb commented on packages/core/src/render3/di.ts
> +      if (attrName === AttributeMarker.SelectOnly) break;
note: I would have done a first `refactor` commit with the name change and the actual interesting change in a subsequent commit (no need to change now)

2018-06-08 22:42 UTC, mary-poppins commented
You can preview 772e020 at https://pr24386-772e020.ngbuilds.io/.

2018-06-08 22:44 UTC, vicb requested changes
- see inline comments
- please add compiler_canonical tests so that we know what to implement compiler side - also update status.md with a link to those tests.

2018-06-08 23:32 UTC, benlesh commented on packages/core/src/render3/di.ts
> +      if (attrName === AttributeMarker.SelectOnly) break;
True.... I was all worried about the "fixup" business :P

2018-06-08 23:40 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> +        i += 2;
done

2018-06-08 23:41 UTC, mary-poppins commented
You can preview 6ac566a at https://pr24386-6ac566a.ngbuilds.io/.

2018-06-11 17:38 UTC, mary-poppins commented
You can preview 5382f38 at https://pr24386-5382f38.ngbuilds.io/.

2018-06-11 17:44 UTC, mary-poppins commented
You can preview 1de4b97 at https://pr24386-1de4b97.ngbuilds.io/.

2018-06-11 17:50 UTC, vicb commented on packages/compiler/test/render3/r3_compiler_compliance_spec.ts
> +                  template: \`<div xmlns:foo="http://someurl/foo" class="my-app" foo:bar="baz" title="Hello">Hello <b>World</b>!</div>\`
There should probably be more than 1 ns attribute here (to make it clear that `0` is not a marker used only once in the attr list).

2018-06-11 18:52 UTC, vicb commented on packages/core/src/render3/instructions.ts
> +    const attrName = first === AttributeMarker.NamespaceURI ? attrs[i += 2] : first;
does not sound right ?
either we should discard ns attributes totally or deal with the ns ?

2018-06-11 18:53 UTC, vicb commented on packages/core/src/render3/node_selector_matcher.ts
> +          nodeAttrValue = nodeAttrs[attrIndexInNode + 2] as string;
does not sound right ?
either we should discard ns attributes totally or deal with the ns ?

2018-06-11 20:44 UTC, vicb commented on packages/core/test/render3/compiler_canonical/elements_spec.ts
> +      // foo:bar="baz"
wrong comment

2018-06-11 20:45 UTC, vicb commented on packages/compiler/test/render3/r3_compiler_compliance_spec.ts
> +          const $c1$ = ['class', 'my-app', 0, 'http://someuri/foo', 'foo:bar', 'baz', 'title', 'Hello'];
this spec needs be updated to match the core test

2018-06-11 20:45 UTC, vicb requested changes
see inline comments

2018-06-11 20:46 UTC, vicb commented on packages/core/src/render3/STATUS.md
> +| `<div xmlns:foo="url" foo:bar="baz">`       |  ✅     |  ✅      |  ❌      |
please add a link to this PR and describe what is left to do compiler in the header of the GH PR.

2018-06-11 21:58 UTC, benlesh commented on packages/core/src/render3/STATUS.md
> +| `<div xmlns:foo="url" foo:bar="baz">`       |  ✅     |  ✅      |  ❌      |
Done

2018-06-11 22:01 UTC, benlesh commented on packages/compiler/test/render3/r3_compiler_compliance_spec.ts
> +          const $c1$ = ['class', 'my-app', 0, 'http://someuri/foo', 'foo:bar', 'baz', 'title', 'Hello'];
done

2018-06-11 22:01 UTC, benlesh commented on packages/core/test/render3/compiler_canonical/elements_spec.ts
> +      // foo:bar="baz"
fixed

2018-06-11 22:13 UTC, vicb commented on packages/compiler/test/render3/r3_compiler_compliance_spec.ts
> +          const $c1$ = ['class', 'my-app', 0, 'http://someuri/foo', 'foo:bar', 'baz', 'title', 'Hello', 0, 'http://someuri/foo', 'foo:qux', 'quacks'];
should be `http://someurl/foo` ?

2018-06-11 22:16 UTC, vicb commented on packages/core/test/render3/compiler_canonical/elements_spec.ts
> +          `<div class="my-app" foo:bar="baz" title="Hello" foo:qux="quacks">Hello <b>World</b>!</div>`
does not match `template: \`<div xmlns:foo="http://someurl/foo" class="my-app" foo:bar="baz" title="Hello" foo:qux="quacks">Hello <b>World</b>!</div>\`

2018-06-11 22:34 UTC, mary-poppins commented
You can preview 350430f at https://pr24386-350430f.ngbuilds.io/.

2018-06-11 22:47 UTC, vicb approved these changes

2018-06-13 05:30 UTC, mary-poppins commented
You can preview 23dcc63 at https://pr24386-23dcc63.ngbuilds.io/.

2018-06-13 20:29 UTC, closed without merging