feat(core): add DoBootstrap interface.
angular/angular pull request #24558
Opened 2018-06-18 09:31 UTC by RoopeHakulinen

Closes #24557.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #24557 

## What is the new behavior?
The `DoBootstrap` interface is added.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-07-02 15:39 UTC, mhevery requested changes

2018-07-02 15:39 UTC, mhevery commented on packages/elements/test/create-custom-element_spec.ts
> +class TestModule implements DoBootstrap {
That is not a best example since `ngDoBootstrap` does nothing. Could we create an example where the `ngDoBoostrap` would actually bootstrap the application.

2018-07-02 15:39 UTC, mhevery commented on packages/core/src/metadata/ng_module.ts
> + * @usageNotes
The first line the docs should be a single sentence describing the purpose of this. Something like: `Lifecycle hook that is called during application bootstrapping process.

2018-07-02 16:48 UTC, RoopeHakulinen commented on packages/core/src/metadata/ng_module.ts
> + * @usageNotes
Oh, copied it from somewhere and edited it improperly. Fixed now.

2018-07-02 16:52 UTC, RoopeHakulinen commented on packages/elements/test/create-custom-element_spec.ts
> +class TestModule implements DoBootstrap {
Thanks for the comment @mhevery! I totally agree but unfortunately I went through all of the current usages of `ngDoBoostrap` in the Angular source and none of them did anything else than what is needed in hybrid apps (prevented the bootstrapping, that is).

What would an ideal example look like in your opinion and where should I put it as there's no test case for it currently? Should some test case be added? If so, what would be a meaningful test case?

Is this the simplest way to use it?
```
class AppModule implements DoBootstrap {
  ngDoBootstrap(appRef: ApplicationRef) {
    appRef.bootstrap(AppComponent); // Or some other component
  }
}
```

2018-07-02 17:44 UTC, JoostK commented on packages/elements/test/create-custom-element_spec.ts
> +class TestModule implements DoBootstrap {
@RoopeHakulinen One use case for `ngDoBootstrap` is with `@angular/elements`

2018-07-02 18:23 UTC, RoopeHakulinen commented on packages/elements/test/create-custom-element_spec.ts
> +class TestModule implements DoBootstrap {
@JoostK Thanks for bringing that up! Am I right, though, stating that in case of Angular Elements, the `ngDoBootstrap` will still have an empty body?

2018-07-02 18:50 UTC, mhevery commented on packages/elements/test/create-custom-element_spec.ts
> +class TestModule implements DoBootstrap {
In case of Elements it will do nothing, but in most cases the example you gave above is correct. We simply boostrap the app. The reason why this example is important is to show to the user how they can do work before or after the bootstrap.

2018-07-03 03:50 UTC, trotyl commented on packages/elements/test/create-custom-element_spec.ts
> +class TestModule implements DoBootstrap {
Possibly a dynamic element bootstrap example for https://github.com/angular/angular/pull/15668? Like:

```typescript
class AppModule implements DoBootstrap {
  constructor(private cfr: ComponentFactoryResolver) { }

  ngDoBootstrap(appRef: ApplicationRef) {
    const componentFactory = this.cfr.resolveComponentFactory(AppComponent);
    appRef.bootstrap(componentFactory, document.getElementById('dynamic-container'));
  }
}
```

2018-07-03 06:31 UTC, JoostK commented on packages/elements/test/create-custom-element_spec.ts
> +class TestModule implements DoBootstrap {
@RoopeHakulinen I typically do the `createCustomElement`/`customElements.define` dance in `ngDoBootstrap`. Perhaps @robwormald can shed some light on the preferred location for registering your custom elements, I personally dislike doing it from the constructor.

2018-07-17 18:22 UTC, mhevery commented
Any progress on this PR? I would love to merge this in, but I need the comments addressed.

2018-07-17 19:23 UTC, RoopeHakulinen commented
Thanks for pinging me @mhevery It is very much on my todo list but I've been busy unfortunately. Hoping to get back to it on weekend. I'm also still wondering where to put the code examples (as there is none in current code base) and which one would be the best one of different types (Angular elements, bootstrapping hybrid app or adding side effects before/after the bootstrapping)?

2018-07-25 04:42 UTC, mhevery commented
Ping, I would love to get this merged...

2018-07-25 04:45 UTC, trotyl commented
@mhevery I think you haven't make a conclusion what the example should be..

2018-07-27 17:36 UTC, mhevery commented
Sorry, I thought we will be implementing @RoopeHakulinen comment:

```
class AppModule implements DoBootstrap {
  ngDoBootstrap(appRef: ApplicationRef) {
    appRef.bootstrap(AppComponent); // Or some other component
  }
}
```

We just need an example showing the happy path of bootstrapping the application programmatically rather than declaratively.

2018-07-28 08:57 UTC, RoopeHakulinen commented
@mhevery Updated it now to contain an inline example. :)

2018-08-07 09:27 UTC, RoopeHakulinen commented
Ping @mhevery :)

2018-08-07 17:55 UTC, mhevery approved these changes

2018-08-07 18:44 UTC, kara commented
[presubmit](https://test.corp.google.com/ui#id=OCL:207753198:BASE:207753237:1533667433570:129a89c4)

2018-08-07 20:18 UTC, closed without merging