feat(ivy): inheritance
angular/angular pull request #24570
Opened 2018-06-18 22:07 UTC by benlesh

- Adds InheritanceDefinitionFeature to ivy
- Ensures that lifecycle hooks are inherited from super classes whether they are defined as directives or not
- Directives cannot inherit from Components
- Components can inherit from Directives or Components
- Ensures that Inputs, Outputs, and Host Bindings are inherited
- Ensures that super class Features are run

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

Ivy does not currently support inheritance of components and directives

## What is the new behavior?

Ivy will support inheritance of components and directives

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-06-18 22:15 UTC, mary-poppins commented
You can preview a625492 at https://pr24570-a625492.ngbuilds.io/.

2018-06-18 23:28 UTC, mhevery requested changes

2018-06-18 23:28 UTC, mhevery commented on packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
> +    typeSourceSpan: null !, usesInheritance,
nit: can you rewrite as `usesInheritance: usesInheritance`. I know that it is equivalent, bu the former will break if you rename the local var, and is not obvious what is going on.

2018-06-18 23:28 UTC, mhevery commented on packages/compiler/src/render3/r3_identifiers.ts
> +      o.ExternalReference = {name: 'ɵInheritanceDirectiveFeature', moduleName: CORE};
bikeShedding: Did we decide on `Inheritance`? Looking at it it is a bit weird. I think `InheritDirectiveFeature` sounds better to me.

2018-06-18 23:28 UTC, mhevery commented on packages/core/test/render3/define_spec.ts
> +    describe('InheritanceDefinitionFeature', () => {
This seems a little light on tests. Could we add at least one test for each of the items in the PR description:
- Adds InheritanceDefinitionFeature to ivy
- Ensures that lifecycle hooks are inherited from super classes whether they are defined as directives or not
- Directives cannot inherit from Components
- Components can inherit from Directives or Components
- Ensures that Inputs, Outputs, and Host Bindings are inherited
- Ensures that super class Features are run

2018-06-18 23:28 UTC, mhevery commented on packages/core/test/render3/define_spec.ts
> +        expect(subDir.log).toEqual([
At first I thought that you are testing if TypeScript correctly deals with inheritance, not if the code you have written correctly merges things into `ComponentDef`.

I would prefer if the tests did not refer `this.log.push` and execute things.

The test should be more like:
```
expect(SubDirective.ngDirectiveDef.ngOnChanges).toBe(SubDirective.prototype.ngOnChanges);
```
It would be much more explicit and easier to follow.

2018-06-18 23:28 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +/**
Could we pull this feature (and maybe the existing feature) to a new file called `features.ts`. It would make it more readable.

I know it is not directly related to you, but let's make the code in better shape than we found it.

2018-06-18 23:28 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +function fillProperties(target: {[key: string]: any}, source: {[key: string]: any}) {
bike-shedding: I wonder if `backFillProperties` would be a better name?

2018-06-18 23:28 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +    if (target[key] === undefined && source.hasOwnProperty(key)) {
Why not `target.hasOwnProperty(key)` rather than `target[key] === undefined`?

2018-06-18 23:28 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +function isComponentDefInternal<T>(definition: DirectiveDefInternal<T>| ComponentDefInternal<T>):
bike-shedding: I would drop `Internal` as it does not add any value. I think `isComponentDef` would be sufficient?

2018-06-18 23:28 UTC, mhevery commented on packages/core/src/render3/definition.ts
> + * @param definition The definition that is a SubClass of another directive of component
This will become public API, and so it needs extensive documentation showing how and when to use it as well as an example of usage.

2018-06-18 23:28 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +    if (isCompDef) {
consider pulling it into separate function for readability.

```
superDef = getDefinition(isCompDef, superType)
```

2018-06-18 23:28 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +        definition.hostBindings = (directiveIndex: number, elementIndex: number) => {
I think we should be smarter here. If only `prevHostBindings` or `superHostBindings` are true than we can just use it. We only need to create the merged function if we have both of them. This way the code only becomes megamorphic if both host-bindings are present.

2018-06-18 23:28 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +      // NOTE(benlesh): Assume super class inheritance feature has already run.
nit: remove `benlesh` because it is not a note just for you but for everyone. :-)

2018-06-18 23:28 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +        definition.afterContentChecked = superDef.afterContentChecked;
bike-shedding: I think this is easier to read? What do you think?
```
definition.afterContentChecked = definition.afterContentChecked || superDef.afterContentChecked;
```

2018-06-18 23:28 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +            (feature as DirectiveDefFeature)(definition);
I don't think this is this simple. Can you add this test.

- Parent implements NgOnChanges which includes `NgOnChangesFeature`
- Child extends and implements `NgDoCheck`

I think the above would break because:
- We don't need to run `NgOnChangesFeature` again on the child.
- The child does not know that it has to call super on `NgDoCheck`

It almost feels like the feature should return a value which would be a feature which should be run on child components. Let's discuss this more in person.

2018-06-18 23:28 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +      if (definition.onInit === undefined) {
Code duplication from above. Could you refactor this somehow to remove duplication?

2018-06-18 23:28 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +      if (!definition.factory) {
I don't think `factory` is needed. Each child must declare its own factory. 

@alxhub I thought we discussed some complication regarding factories, and how we need to call super on them. Can you remember the details?

2018-06-19 03:45 UTC, trotyl commented on packages/core/src/render3/definition.ts
> +      if (!definition.factory) {
@mhevery In current view engine a derived component class [may not have a decorator](https://stackblitz.com/edit/angular-g6xdq7?file=src%2Fapp%2Fhello.component.ts), is it still going to be supported in Ivy?

2018-06-19 03:59 UTC, JoostK commented on packages/core/src/render3/definition.ts
> +      const superHostBindings = definition.hostBindings;
`superDev`

2018-06-19 03:59 UTC, JoostK commented on packages/core/src/render3/jit/directive.ts
> +    usesInheritance: type.constructor !== Object,
Is this correct? Seems wrong to me

2018-06-19 04:01 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
> +    typeSourceSpan: null !, usesInheritance,
(personally I would prefer to keep it as a shorthand assignment - the rest of `ngtsc` uses shorthand assignments and I've found it to be very positive for readability, not confusing at all)

2018-06-19 04:02 UTC, alxhub commented on packages/compiler/src/render3/r3_identifiers.ts
> +      o.ExternalReference = {name: 'ɵInheritanceDirectiveFeature', moduleName: CORE};
+1 for `InheritDirectiveFeature`

2018-06-19 04:03 UTC, alxhub commented on packages/core/test/render3/define_spec.ts
> +        expect(subDir.log).toEqual([
Agreed, and this test actually does only test JS/TS inheritance, not the result of the feature application.

2018-06-19 04:08 UTC, trotyl commented on packages/core/src/render3/definition.ts
> +      superDef = superType.ngComponentDef || superType.ngDirectiveDef;
Currently a component may extend non-directive type, for example https://github.com/angular/angular/issues/16566#issuecomment-337960028. Would this be broken?

2018-06-19 04:08 UTC, trotyl commented on packages/core/src/render3/definition.ts
> +        throw new Error('Directives may not inherit Components');
This is also supported currently, breaking change or not implemented yet?

2018-06-19 04:08 UTC, trotyl commented on packages/core/src/render3/definition.ts
> +      // Merge inputs
`// Merge inputs & outputs`? Or another `// Merge outputs` comment?

2018-06-19 04:59 UTC, JoostK commented on packages/core/src/render3/definition.ts
> +  while (superType && !superDef) {
Traversing the full ancestor tree is neither correct, nor necessary, I'd say. Inheritance is inherently transitive, so by just referring to the super definition we also inherit any of its base types, as those have already been incorporated into super's definition (given that the super type also has `InheritDirectiveFeature`). This is ordering sensitive, but AFAIK the `ngDirectiveDef`/`ngComponentDef` is fully initialized once leaving `defineDirective`/`defineComponent` so initialization order is guaranteed by my reasoning.

The current implementation has an issue with multiple layers of inheritance, as host bindings will now be collected multiple times (once per level) and therefore be called multiple times.

2018-06-21 21:10 UTC, benlesh commented on packages/compiler/src/render3/r3_identifiers.ts
> +      o.ExternalReference = {name: 'ɵInheritanceDirectiveFeature', moduleName: CORE};
done

2018-06-21 21:11 UTC, benlesh commented on packages/core/test/render3/define_spec.ts
> +        expect(subDir.log).toEqual([
I see. I was just copying a pattern from another test. Should we change that one too?

2018-06-21 22:04 UTC, benlesh commented on packages/core/src/render3/jit/directive.ts
> +    usesInheritance: type.constructor !== Object,
:man_facepalming: Yes. LOL.

It looks like I'll need to check `Object.getPrototypeOf(type)` against `Object.prototype` to see if I've bottomed out in the inheritance chain. :thinking: 

cc @mhevery

2018-06-22 08:15 UTC, JoostK commented on packages/core/test/render3/define_spec.ts
> +        subDir.ngOnChanges({} as SimpleChanges);
These calls are all targeting the actual JS instance, where we should be calling the functions from the `ngDirectiveDef` as those are the ones that have been corrected by `InheritDirectiveFeature`

2018-06-22 08:15 UTC, JoostK commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +  while (superType && !superDef) {
Repeated from earlier comment that has been gobbled up because of the code moves:

Traversing the full ancestor tree is neither correct, nor necessary, I'd say. Inheritance is inherently (no pun intended) transitive, so by just referring to the super definition we also inherit any of its base types, as those have already been incorporated into super's definition (given that the super type also has InheritDirectiveFeature). This is ordering sensitive, but AFAIK the ngDirectiveDef/ngComponentDef is fully initialized once leaving defineDirective/defineComponent so initialization order is guaranteed by my reasoning.

The current implementation has an issue with multiple layers of inheritance, as host bindings will now be collected multiple times (once per level) and therefore be called multiple times.

2018-06-22 22:14 UTC, alxhub requested changes

2018-06-22 22:14 UTC, alxhub commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +    if (isComponentDefInternal(definition)) {
In general, reads of `ngComponentDef` / `ngDirectiveDef` / etc should be minimized, as they're megamorphic and thus expensive.

In this case it'd only be a problem for a deep inheritance property, but just pointing it out in general.

2018-06-22 22:14 UTC, alxhub commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +        definition.hostBindings = (directiveIndex: number, elementIndex: number) => {
I agree with @mhevery - we should only create this function if they're both set, and not pay the cost of checking during every change detection.

2018-06-22 22:14 UTC, alxhub commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +      if (!definition.factory) {
You can drop these lines - `definition.factory` will always be set, and in general it's always wrong to directly copy the factory over, as that will return an instance of the supertype, not the subtype.

2018-06-22 22:14 UTC, alxhub commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> +      if (inputs.hasOwnProperty(pubKey)) {
I think these `hasOwnProperty` checks are unnecessary, there won't be deep prototype structures in the definitions.

2018-06-22 22:14 UTC, alxhub commented on packages/compiler/src/render3/view/compiler.ts
> +    // TODO(benlesh): ask alxhub about where I should get this information.
Just leave it as `false` - this code path's days are numbered.

2018-06-22 22:16 UTC, mhevery commented on packages/core/test/render3/define_spec.ts
> +        expect(subDef.inputs.foo).toBe(superDef.inputs.foo);
`expect(subDef.inputs).toEqual({foo:'foo', bar:'bar', baz:'baz', qux: 'qux'})` would be more readable.

2018-06-22 22:16 UTC, mhevery commented on packages/core/test/render3/define_spec.ts
> +        expect(subDef.outputs.foo).toBe(superDef.outputs.foo);
same here.

2018-06-22 22:16 UTC, mhevery commented on packages/core/test/render3/define_spec.ts
> +
```
expect(log).toEqual([...]);
log = []; 
```

This will make the test a lot more readable.

2018-06-23 00:07 UTC, benlesh commented on packages/core/test/render3/define_spec.ts
> +        expect(subDef.outputs.foo).toBe(superDef.outputs.foo);
done

2018-06-23 00:07 UTC, benlesh commented on packages/core/test/render3/define_spec.ts
> +
done

2018-06-23 00:07 UTC, benlesh commented on packages/core/test/render3/define_spec.ts
> +        const log: string[] = [];
done

2018-06-23 00:08 UTC, benlesh commented on packages/compiler/src/render3/view/compiler.ts
> +    // TODO(benlesh): ask alxhub about where I should get this information.
👍

2018-06-23 00:11 UTC, benlesh commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> +      if (inputs.hasOwnProperty(pubKey)) {
I see. Given that it's "more correct" :tm:, I think we can leave these here and remove them if they become a perf issue. What do you think?

2018-06-23 00:12 UTC, benlesh commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +      if (!definition.factory) {
Yeah, that makes a LOT more sense. I'm not sure why in my notes I had that I needed to inherit the factory function.

2018-06-23 00:17 UTC, benlesh commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +        definition.hostBindings = (directiveIndex: number, elementIndex: number) => {
done

2018-06-23 00:18 UTC, benlesh commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +// tslint:disable-next-line:no-any these objects could have any value stored
Yeah, it's just complaining about the use of any.

2018-06-25 06:44 UTC, trotyl commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> + * The NgOnChangesFeature function that is returned decorates a component with support for
The description here should be updated as well, it's no longer a higher-level factory function.

2018-06-25 06:44 UTC, trotyl commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> + * @returns DirectiveDefFeature
Also outdated jsdoc.

2018-06-25 22:35 UTC, mary-poppins commented
You can preview 8cb2c2b at https://pr24570-8cb2c2b.ngbuilds.io/.

2018-06-25 22:58 UTC, mary-poppins commented
You can preview ce3af47 at https://pr24570-ce3af47.ngbuilds.io/.

2018-06-26 02:26 UTC, mhevery approved these changes
Hi Ben,

I have done bunch of work to make it ready for merging here 71ab9ad5e2f716e295a40c07c56423b58de7e523 Please verify that you are OK with it.

2018-06-26 02:33 UTC, mary-poppins commented
You can preview 71ab9ad at https://pr24570-71ab9ad.ngbuilds.io/.

2018-06-26 02:36 UTC, benlesh reviewed
Lgtm

2018-06-26 02:42 UTC, alxhub commented on packages/compiler/src/render3/r3_identifiers.ts
> +  // tslint:disable-next-line:variable-name
There are a lot of tslint lines added here for warnings I don't get in my working copy. Are you sure you're using the repository lint and not your own script?

2018-06-26 02:43 UTC, alxhub commented on packages/compiler/src/render3/view/compiler.ts
> +    features.push(o.importExpr(R3.InheritDefinitionFeature, null, null));
You don't need the extra `null`s here.

2018-06-26 02:45 UTC, alxhub commented on packages/core/src/render3/definition.ts
> +      secondary && (secondary[declaredName] = minifiedKey);
Prefer `if` statements to clever code.

2018-06-26 02:47 UTC, alxhub commented on packages/core/src/render3/interfaces/definition.ts
> +  features: DirectiveDefFeature[]|undefined;
Use `null` and not `undefined` for definition properties.

2018-06-26 02:49 UTC, alxhub commented on packages/core/src/render3/jit/directive.ts
> +function isUsingInheritance(obj: {}) {
As a general habit I prefer return types to be declared explicitly.

2018-06-26 02:50 UTC, alxhub commented on packages/core/test/bundling/todo/index.ts
> -import {CommonModule, NgForOf, NgIf} from '@angular/common';
Thanks for the cleanup, but it should probably go in a separate commit.

2018-06-26 02:54 UTC, alxhub commented
Perhaps also expand the `feat(ivy): inheritance` commit line to be more descriptive about the change. The description has the context, but it'd be nice to be able to tell at a glance what this commit does to support inheritance.

2018-06-26 17:42 UTC, mhevery commented on packages/compiler/src/render3/r3_identifiers.ts
> +  // tslint:disable-next-line:variable-name
removed

2018-06-26 17:42 UTC, mhevery commented on packages/compiler/src/render3/view/compiler.ts
> +    features.push(o.importExpr(R3.InheritDefinitionFeature, null, null));
fixed

2018-06-26 17:43 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +      secondary && (secondary[declaredName] = minifiedKey);
fixed

2018-06-26 17:43 UTC, mhevery commented on packages/core/src/render3/interfaces/definition.ts
> +  features: DirectiveDefFeature[]|undefined;
fixed

2018-06-26 17:44 UTC, mhevery commented on packages/core/src/render3/jit/directive.ts
> +function isUsingInheritance(obj: {}) {
fixed

2018-06-26 18:02 UTC, alxhub approved these changes

2018-06-26 18:05 UTC, mary-poppins commented
You can preview 7262919 at https://pr24570-7262919.ngbuilds.io/.

2018-06-26 19:48 UTC, alxhub approved these changes

2018-06-26 20:05 UTC, JoostK commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> +             Object.getPrototypeOf(checkProto) !== Object.getPrototypeOf(Object.prototype)) {
`Object.getPrototypeOf(Object.prototype)` should always be null. I think this should just be `Object.getPrototypeOf(Object)` as seen in JIT's `isUsingInheritance` function.

2018-06-27 07:35 UTC, trotyl commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> +             Object.getPrototypeOf(checkProto) !== Object.getPrototypeOf(Object.prototype)) {
Even `Object.getPrototypeOf(Object)` is still wrong, it's just `Object.prototype`:

```javascript
class Foo {}
const foo = new Foo()

const proto_0 = Object.getPrototypeOf(foo)
const proto_1 = Object.getPrototypeOf(proto_0)

console.log(proto_0 === Foo.prototype)                 // true
console.log(proto_1 === Object.prototype)              // true
console.log(proto_1 === Object.getPrototypeOf(Object)) // false
```

2018-06-27 07:52 UTC, trotyl commented on packages/core/src/render3/jit/directive.ts
> +  return Object.getPrototypeOf(obj) !== OBJECT_PROTOTYPE;
From the usage below, the parameter of `isUsingInheritance` is the type/class, not the instance.
The name `obj` is quite misleading, and **performing `getPrototypeOf` on class doesn't make any sense**.

Should be:

```typescript
function isUsingInheritance(type: {}): boolean {
  Object.getPrototypeOf(type.prototype) !== Object.prototype
}
```

Checking code:

```javascript
class Foo {}
class Bar extends Foo {}

console.log(Object.getPrototypeOf(Foo.prototype) !== Object.prototype)  // false
console.log(Object.getPrototypeOf(Bar.prototype) !== Object.prototype)  // true
```

2018-06-27 08:06 UTC, trotyl commented on packages/core/src/render3/jit/directive.ts
> +function isUsingInheritance(obj: {}): boolean {
The parameter name is a little confusing, the `obj` here is the **type/class** rather instance. Possibly just call it `type`?

2018-06-27 09:28 UTC, JoostK commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> +             Object.getPrototypeOf(checkProto) !== Object.getPrototypeOf(Object.prototype)) {
@trotyl I thought the same thing, but looking at `isUsingInheritance` made me switch to what was used there. That is probably also incorrect then?

2018-06-27 09:40 UTC, trotyl commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> +             Object.getPrototypeOf(checkProto) !== Object.getPrototypeOf(Object.prototype)) {
@JoostK In `isUsingInheritance` it's checking the `SomeType.__proto__` itself rather than `SomeType.prototype.__proto__`, I tried that and seems it indeed works (but admit I don't know that could work before).

2018-06-27 12:37 UTC, trotyl commented on packages/core/src/render3/jit/directive.ts
> +  return Object.getPrototypeOf(obj) !== OBJECT_PROTOTYPE;
Possibly we could change this to:

```javascript
Object.getPrototypeOf(/* type */obj.prototype) !== Object.prototype
```

Which would still work under IE.

2018-06-27 21:43 UTC, mhevery commented on packages/core/src/render3/jit/directive.ts
> +function isUsingInheritance(obj: {}): boolean {
good catch, fixed

2018-06-27 21:43 UTC, mhevery commented on packages/core/src/render3/jit/directive.ts
> +  return Object.getPrototypeOf(obj) !== OBJECT_PROTOTYPE;
fixed

2018-06-27 21:45 UTC, mhevery commented
http://test/OCL:202372731:BASE:202372789:1530135906370:4d1459c6

2018-06-27 22:00 UTC, mary-poppins commented
You can preview 56fcf77 at https://pr24570-56fcf77.ngbuilds.io/.

2018-06-28 08:04 UTC, trotyl commented on packages/core/src/render3/jit/directive.ts
> +  return Object.getPrototypeOf(type) !== Object.prototype;
I meant `Object.getPrototypeOf(type.prototype)`, is the `__proto__` of `prototype` rather than of type itself:

```javascript
class Foo { }
class Bar extends Foo { }

console.log(Object.getPrototypeOf(Foo.prototype) === Object.prototype)  // true
console.log(Object.getPrototypeOf(Bar.prototype) === Object.prototype)  // false
console.log(Object.getPrototypeOf(Foo) === Object.prototype)            // false
console.log(Object.getPrototypeOf(Bar) === Object.prototype)            // false
```

2018-06-28 08:11 UTC, trotyl commented on packages/core/src/render3/jit/directive.ts
> +  return Object.getPrototypeOf(type) !== Object.prototype;
Since unnecessary inheritance support would not actually break anything (only breaks in the opposite way), I'd suggest add a test like `should only enable inheritance when needed` to make sure it not happened.

2018-06-29 03:20 UTC, mhevery commented on packages/core/src/render3/jit/directive.ts
> +  return Object.getPrototypeOf(type) !== Object.prototype;
Good catch, fixed and added tests.

2018-06-29 13:44 UTC, closed without merging