WIP docs: add new Reactive Forms guide
angular/angular pull request #24578
Opened 2018-06-19 18:04 UTC by brandonroberts

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-06-19 18:12 UTC, mary-poppins commented
You can preview 49f836a at https://pr24578-49f836a.ngbuilds.io/.

2018-06-19 21:48 UTC, tinayuangao commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.css
> +/* HeroDetailComponent's private CSS styles */
Change the name to ProfileEditor?

2018-06-19 21:48 UTC, tinayuangao commented on aio/content/examples/reactive-forms/stackblitz.json
> +    "!**/app-old/**/*.*",
what's this `app-old`?

2018-06-19 21:48 UTC, tinayuangao commented on aio/content/guide/reactive-forms.md
> +Try the <live-example title="Reactive Forms (final) in Stackblitz">Reactive Forms live-example</live-example>.
Are we going to have intermediate steps stackblitz?

2018-06-19 21:48 UTC, tinayuangao commented on aio/content/guide/reactive-forms.md
> +<table width="100%">
Are we going to include `setValue` `patchValue` in this table?

2018-06-19 21:48 UTC, tinayuangao commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.2.ts
> +    return this.fb.control(['']);
Here should be `this.fb.control('')`? since one alias is a string.

2018-06-19 21:48 UTC, tinayuangao commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.2.ts
> +    firstName: [''],
We can also use `firstName: ''` if there's validator

2018-06-20 17:19 UTC, kapunahelewong reviewed
@brandonroberts this is excellent! I want to say, "just a few things", but I really got sucked into reading the md file and made simple notes all along as I went. There are a number of them, but they are are really straightforward language/writerly style guide things. Thanks for requesting my review. Youʻre very kind and this is a super clear guide. Well done!

2018-06-20 17:19 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +Form validation is necessary when receiving user input through forms. This guide will cover using a single validator for a form control. Form validation is covered more extensively in the `Form Valid
Could link to Form Validation guide

2018-06-20 17:19 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +Reactive forms includes a set of validator functions out of the box for common use cases. These functions are provided the control to validate against, and return and error object or null based on th
includes --> include? (if we are using plural)

In:
> These functions are provided the control to validate against, and return and error object or null based on the validation check. 

Does it make sense to say: 
> provided **to** the control

Donʻt need the comma after "against" since thatʻs a dependent clause and not able to stand on its own. 

> and return and error --> and return **an** error

2018-06-20 17:19 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +This validator is synchronous, in that it immediately returns the result of the validation when called. Converse to an asynchronous validator than performs validation that take some amount of time to
Add subject and verb to:
> Converse to an asynchronous validator than performs validation that take some amount of time to complete before returning its result.

To make it a complete sentence you could do:
>**This is c**onverse to an asynchronous validator than performs validation that take some amount of time to complete before returning its result.

2018-06-20 17:19 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +When importing the `ReactiveFormsModule`, you also gain access to directives to use in your templates for bind the data model to the forms declaratively.
"for bind" -- > "for binding"

2018-06-20 17:19 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +When building forms, a `FormArray` is an alternative to a `FormGroup` in that you manage any number of unnamed controls to represent a set of values for a control. You can dynamically insert and remo
Are we able to use we/letʻs? (I hope so!!!) Otherwise, the last sentence would have to leave letʻs out.

2018-06-20 17:19 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +A `FormArray` can initialized with zero to many controls defined in an array. Add an `aliases` property to the `FormGroup` for the `profileForm` to define the `FormArray`. Use the `FormBuilder.array`
Careful of the passive (and missing word "be"):

> A `FormArray` can initialized with zero

To make it active, maybe you could do:

> You can initialize a `FormArray` with any number of controls, from zero to many, by defining them in an array.

"Use the `FormBuilder.array`" --> Use the `FormBuilder.array()`

2018-06-20 17:19 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +### Access the FormArray control
You can use code font in headers now if you like

2018-06-20 17:19 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +The aliases `FormArray` is defined in your model, now add it to the template for user input. Similar to the `formGroupName` input provided by the `FormGroupNameDirective`, a `formArrayName` is used t
To shift from passive to active, how about something like: 

> Now that your model defines the aliases `FormArray`, add it to the template for user input.

and

> a `formArrayName` ~is used to~ binds communication from the `FormArray`

and div -->`<div>`

2018-06-25 14:52 UTC, brandonroberts commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.2.ts
> +    firstName: [''],
In the guide, I'm using an array by default to make it easier to add a validator later.

2018-06-25 14:54 UTC, brandonroberts commented on aio/content/guide/reactive-forms.md
> +Try the <live-example title="Reactive Forms (final) in Stackblitz">Reactive Forms live-example</live-example>.
There won't be intermediate examples on StackBlitz, just the final live example.

2018-06-25 14:58 UTC, brandonroberts commented on aio/content/guide/reactive-forms.md
> +Reactive forms use a more explicit and immutable approach to managing the state of a form at a given point in time. Each change to the form state returns a new state, maintaing the integrity of the m
I think `form value changes` would be clearer here. I'm talking about the value from the form input elements changing, and the form value itself changing.

2018-06-25 15:21 UTC, brandonroberts commented on aio/content/guide/reactive-forms.md
> +Reactive forms includes a set of validator functions out of the box for common use cases. These functions are provided the control to validate against, and return and error object or null based on th
I'm using `provided to the control` to refer to how the function is used.

```
function validator(control: FormControl) { <-- function is provided the control
 // return error object or null  
}

```

2018-06-25 15:33 UTC, brandonroberts commented
I addressed the initial review feedback

2018-06-25 15:59 UTC, mary-poppins commented
You can preview 4c59921 at https://pr24578-4c59921.ngbuilds.io/.

2018-06-25 16:06 UTC, kapunahelewong approved these changes

2018-06-25 21:25 UTC, kara requested changes
Great work! I love how you pared down the guide so it's very simple and direct. Some nits below about 
 forms nuances and some ideas on how to simplify the guide even further.

2018-06-26 02:47 UTC, brandonroberts commented on aio/content/guide/reactive-forms.md
> +<code-example path="reactive-forms/src/app/app.component.1.html" region="app-name-editor" linenums="false" title="src/app/app.component.html (name editor)">
Its more for ease of use to copy/paste

2018-06-26 03:01 UTC, mary-poppins commented
You can preview 6d954ce at https://pr24578-6d954ce.ngbuilds.io/.

2018-06-26 03:02 UTC, brandonroberts commented
@kara Thanks for the review! I address your feedback items.

2018-06-26 03:05 UTC, mary-poppins commented
You can preview 16b008a at https://pr24578-16b008a.ngbuilds.io/.

2018-06-26 03:08 UTC, mary-poppins commented
You can preview 64518d5 at https://pr24578-64518d5.ngbuilds.io/.

2018-06-26 18:44 UTC, tinayuangao commented on aio/content/guide/reactive-forms.md
> +  <img src="generated/images/guide/reactive-forms/name-editor-1.png" alt="Name Editor">
Updated the image with updated text?

2018-06-26 19:03 UTC, brandonroberts commented on aio/content/examples/reactive-forms/src/app/name-editor/name-editor.component.ts
> +  constructor() { }
It's part of CLI generated code. It's not need for the example though.

2018-06-26 19:03 UTC, brandonroberts commented on aio/content/examples/reactive-forms/src/app/name-editor/name-editor.component.ts
> +  ngOnInit() {
It's part of CLI generated code. It's not need for the example though.

2018-06-26 20:47 UTC, kara approved these changes
LGTM aside from the typos.

2018-06-26 20:47 UTC, kara commented on aio/content/guide/reactive-forms.md
> +        <li>For a `FormControl`, the current value.</li>
For some reason, the backticks are shown in the preview (instead of the code snippet formatting)

2018-06-26 20:47 UTC, kara commented on aio/content/guide/reactive-forms.md
> +A `FormArray` is an alternative to a `FormGroup` that allows you to manage any number of unnamed controls. As with `FormGroup`s, you can dynamically insert and remove controls from a `FormArray`, and
Missing a word

>its value and validation status is calculated from its child controls

2018-06-26 20:47 UTC, kara commented on aio/content/guide/reactive-forms.md
> +Reactive forms include a set of validator functions out of the box for common use cases. These functions are provided the control to validate against and return and error object or null based on the
Typo: `and error object` -> `an error object`

2018-06-26 20:47 UTC, kara commented on aio/content/guide/reactive-forms.md
> +<table width="100%">
Hmm, looking at this again, I'm wondering if it's necessary to inline here. This just duplicates the information in AbstractControl. Can we just link to that page instead?

2018-06-26 21:32 UTC, tinayuangao approved these changes
LGTM

Except for the outdated images

2018-06-27 03:00 UTC, mary-poppins commented
You can preview 276c055 at https://pr24578-276c055.ngbuilds.io/.

2018-07-03 19:23 UTC, jenniferfell requested changes
Sending more comments in a PDF via slack or email.

2018-07-03 19:23 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +Reactive forms use a more explicit and immutable approach to managing the state of a form at a given point in time. Each change to the form state returns a new state, which maintains the integrity of
more than what? I recommend positioning without comparing. "Reactive forms use an explicit and immutable..."

2018-07-03 19:23 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +It also allows for easier testing since you have an assurance that your data is consistent and predictable when requested. Consumers outside your templates have access to the same streams, where they
testing because you have...

2018-07-03 19:23 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +Reactive forms differ from template-driven forms in distinct ways. See the [Appendix](#appendix) for detailed comparisons between the two paradigms.
Is there a quick "Use reactive forms if..." to add here.

Also good place to add prerequisites: This reactive forms guide assumes that you know..."

2018-07-03 19:23 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +In order to use reactive forms, import the `ReactiveFormsModule` from the `@angular/forms` package and add it to your NgModule's `imports` array.
I printed and made notes by hand. I'll send that to you directly. Red notes are more important than blue notes. Blue notes are editorial style.

2018-07-03 19:23 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +The `FormControl` is the most basic building block when using reactive forms. Import the `FormControl` symbol into your component and create an instance of a new form control as a class property. To
Let's talk about how this section and later sections are positioned. Is this beginning tutorial, where you expect the reader to follow along and build exactly the app you are describing? Or is this more guide-like with an example that you are describing/showing but you don't expect your reader to type along?  

If you start with a tutorial, I recommend an explicit "ta da" point and more context along the way. 

Then, I recommend switching to a more guide style, where you first describe generally how to do something and then  come back to the example. Perhaps change style at "Managing Control Values" section. The guide style would be more like:  "To create a form control, import the FormControl class into the component and then create a new form control as a class property. Looking again at the example application, notice the 'name' property is used to store the form control (insert code snippet." 

The user tasks and flow are really good. A more clear tutorial v. guide style would tighten up the tone and context a bit. More related notes in the document I'll send directly. 

I

2018-07-13 20:33 UTC, mary-poppins commented
You can preview 7c9ebcd at https://pr24578-7c9ebcd.ngbuilds.io/.

2018-07-14 01:24 UTC, kara reviewed
Some nits

2018-07-16 13:03 UTC, mary-poppins commented
You can preview e6a7c7f at https://pr24578-e6a7c7f.ngbuilds.io/.

2018-07-16 16:46 UTC, kara approved these changes
LGTM, just a few formatting nits

2018-07-16 16:46 UTC, kara commented on aio/content/guide/reactive-forms.md
> +The `FormControl` is the most basic building block when using reactive forms. Import the `FormControl` class into your component and create   a new instance of `FormControl` to save as a class proper
Nit: extra spaces before 'a new instance'

2018-07-16 16:46 UTC, kara commented on aio/content/guide/reactive-forms.md
> +value of a `FormControl` and change it.
NIt: Formatting?

2018-07-16 19:36 UTC, mary-poppins commented
You can preview 0d01fbf at https://pr24578-0d01fbf.ngbuilds.io/.

2018-07-16 20:24 UTC, jenniferfell approved these changes
Comments marked "Editorial" aren't show stoppers. 

Please address before merging:
- Add "Step 4" for "Display the component" subsection
- Add numbered Step to titles for other subsection groups that must be done in sequence
- Consider replacement titles for the two that have use/usage in them

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +Since a `FormArray` represents an undefined number of controls in array, accessing the control through a getter provides convenience and reusability. Define a getter class property to retrieve the al
Editorial - too casual? I'm not sure, but I found myself trying to replace "a getter " with anything. "A get() method"? "A get class property?

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +*Note*: Since the returned control is of type `AbstractControl`, you provide an explicit type to access the `FormArray` specific syntax for the methods.
Editorial: 
Note: Because the returned control...

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +Since a `FormArray` represents an undefined number of controls in array, accessing the control through a getter provides convenience and reusability. Define a getter class property to retrieve the al
Editorial: Should aliases be possessive or plural?
Define a getter class property to retrieve the alias's `FormArray` control from the parent `FormGroup`.

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +Define a method to dynamically insert an alias control into the aliases `FormArray`. The `FormArray.push()` method inserts the control as a new item in the array.
Editorial: Should aliases be possessive or plural?
into the alias's FormArray.

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +The `*ngFor` directive iterates over each `FormControl` provided by the aliases `FormArray`. Because `FormArray` elements are unnamed, you assign the _index_ to the `i` variable and pass it to each c
Editorial: Should aliases be possessive or plural?
 the alias's FormArray.

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +*Note*: Instead of a `FormControl` for each alias, you could compose another `FormGroup` with additional fields but the process of defining a control for each item is the same.
Editorial - missing comma, "but" feels negative
*Note*: Instead of a `FormControl` for each alias, you could compose another `FormGroup` with additional fields. The process of defining a control for each item is the same.

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +You can download the complete source for all steps in this guide
Editorial: I would just remove this. The link is at the top of the document, and there's no specific reason to say it here.

Future: You could add a "Final code review" section like the TOH Tutorial has.

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +Listed below are the base classes and services used to track form controls.
Editorial: "track?"
create and manage?

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +### Reactive forms API
Future: We're adding package/module overviews to the API reference. This kind of content will probably be included there, so we might consider just a cross-reference here.

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +      [`AbstractControl`](api/forms/AbstractControl "API Reference: FormControl") is the abstract base class for the three concrete form control classes;
Editorial: No need to repeat the class name from the left

"The abstract base class for..."
"Manages the value and validity status of an individual form control"
"An injectable service..."

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +      [`FormControlDirective`](api/forms/FormControlDirective "API Reference: FormControlDirective") syncs a standalone `FormControl` instance to a form control element.
Editorial: Same note as above. No need to repeat directive name in the description field.

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +### Template-driven forms compared
Editorial - parsing: Comparison to template-driven forms

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +_Template-driven_ forms, introduced in the [Template guide](guide/forms), take a completely different approach.
Doc title is "Forms" but the nav entry is better: in the [Template-driven forms guide]

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +You place HTML form controls (such as `<input>` and `<select>`) in the component template and
Editorial - feels like three bullets:
* You place HTML form controls
* You don't create Angular form control objects
* You don't push and pull data values

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +Reactive forms are synchronous while template-driven forms are asynchronous.
Editorial - missing comma, consider and instead of while: 
Reactive forms are synchronous, and template-driven forms are asynchronous.

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +### Async vs. sync
Future: Conceptually this is a subsection of the Comparison before it. Let's address in next version, because I think we should move all this info higher up in the Forms discussion overall.

2018-07-16 20:24 UTC, jenniferfell commented on aio/content/guide/reactive-forms.md
> +## Advanced usage with form arrays
Editorial - can we find a title that gives more info about why to use form arrays? An idea: 
Creating dynamic groups
Creating dynamic groups with form arrays
Dynamic groups using form arrays

2018-07-17 18:43 UTC, brandonroberts commented on aio/content/guide/reactive-forms.md
> +Since a `FormArray` represents an undefined number of controls in array, accessing the control through a getter provides convenience and reusability. Define a getter class property to retrieve the al
That's what the syntax is for the accessing a computed variable this way. I updated to this for clarity. "Use the _getter_ syntax to create an _aliases_ class property to retrieve the aliases `FormArray` control from the parent `FormGroup`."

2018-07-17 18:46 UTC, brandonroberts commented on aio/content/guide/reactive-forms.md
> +Define a method to dynamically insert an alias control into the aliases `FormArray`. The `FormArray.push()` method inserts the control as a new item in the array.
Possessive. I'm referring to the class property named `aliases`

2018-07-17 19:05 UTC, brandonroberts commented on aio/content/guide/reactive-forms.md
> +### Display the component
This is included more for easy copy/paste rather than an explicit step. I bumped it to an h4(####) so its not included in the chapter navigation but included in the section above it.

2018-07-17 19:19 UTC, mary-poppins commented
You can preview 61ffa36 at https://pr24578-61ffa36.ngbuilds.io/.

2018-07-18 12:38 UTC, mary-poppins commented
You can preview 19a6d43 at https://pr24578-19a6d43.ngbuilds.io/.

2018-07-19 15:31 UTC, mary-poppins commented
You can preview 5e79b49 at https://pr24578-5e79b49.ngbuilds.io/.

2018-07-19 17:47 UTC, closed without merging