WIP Add api doc for programmatic animation classes
angular/angular pull request #24668
Opened 2018-06-25 23:19 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-06-25 23:27 UTC, mary-poppins commented
You can preview 873d38c at https://pr24668-873d38c.ngbuilds.io/.

2018-06-26 19:07 UTC, mary-poppins commented
You can preview cff8f3d at https://pr24668-cff8f3d.ngbuilds.io/.

2018-06-26 19:50 UTC, mary-poppins commented
You can preview bd10170 at https://pr24668-bd10170.ngbuilds.io/.

2018-06-27 15:29 UTC, mary-poppins commented
You can preview 8a8a5a3 at https://pr24668-8a8a5a3.ngbuilds.io/.

2018-06-27 15:40 UTC, mary-poppins commented
You can preview a9e4205 at https://pr24668-a9e4205.ngbuilds.io/.

2018-06-28 18:15 UTC, mary-poppins commented
You can preview 220b2ff at https://pr24668-220b2ff.ngbuilds.io/.

2018-07-04 16:21 UTC, mary-poppins commented
You can preview 780eeab at https://pr24668-780eeab.ngbuilds.io/.

2018-07-09 16:19 UTC, mary-poppins commented
You can preview 9166a7a at https://pr24668-9166a7a.ngbuilds.io/.

2018-07-12 15:36 UTC, mary-poppins commented
You can preview b99432e at https://pr24668-b99432e.ngbuilds.io/.

2018-07-12 15:49 UTC, mary-poppins commented
You can preview fe845ae at https://pr24668-fe845ae.ngbuilds.io/.

2018-07-12 16:06 UTC, mary-poppins commented
You can preview 7f5d1e1 at https://pr24668-7f5d1e1.ngbuilds.io/.

2018-07-12 19:24 UTC, mary-poppins commented
You can preview 74b0a6e at https://pr24668-74b0a6e.ngbuilds.io/.

2018-07-12 19:41 UTC, mary-poppins commented
You can preview d31c797 at https://pr24668-d31c797.ngbuilds.io/.

2018-07-12 20:02 UTC, mary-poppins commented
You can preview f50a9ac at https://pr24668-f50a9ac.ngbuilds.io/.

2018-07-12 23:44 UTC, mary-poppins commented
You can preview 01b16b1 at https://pr24668-01b16b1.ngbuilds.io/.

2018-07-12 23:57 UTC, mary-poppins commented
You can preview c737b1e at https://pr24668-c737b1e.ngbuilds.io/.

2018-07-13 00:32 UTC, mary-poppins commented
You can preview 6653298 at https://pr24668-6653298.ngbuilds.io/.

2018-07-13 15:22 UTC, jbogarthyde commented
@matsko Please review content, and help me fix the golden file so it will pass the circleci:test.

2018-07-13 20:48 UTC, jenniferfell requested changes

2018-07-13 20:48 UTC, jenniferfell commented on packages/animations/src/animation_builder.ts
> + * * Use the player object to control the animation programmatically.
I'm unclear about the relationship among bullet items. Add intro sentence. If these are a sequence, use numbers. 
I wasn't clear if they were all the steps or options until I looked at the code. (I really like the synergy between these and the code comments.)

2018-07-13 20:48 UTC, jenniferfell commented on packages/animations/src/animation_builder.ts
> +   * the `AnimationBuilder`.`build()` method that returned this instance,
Unclear parsing "that returned this instance"? Creates an instance for the thing defined by a method that returned this same instance?

2018-07-13 20:48 UTC, jenniferfell commented on packages/animations/src/animation_builder.ts
> +   * @param options A set of options that can include a time delay, and
No comma. Fix typo: A set of options that can include a time delay and additional developer-defined parameters.

2018-07-13 20:48 UTC, jenniferfell commented on packages/animations/src/animation_event.ts
>   * @experimental Animation support is experimental.
Animation support in general isn't. Is this specific interface still experimental?

2018-07-13 20:48 UTC, jenniferfell commented on packages/animations/src/players/animation_group_player.ts
> + * Used internally to control animations.
Good note!

2018-07-13 20:48 UTC, jenniferfell commented on packages/animations/src/players/animation_player.ts
> +   * Resets the animation to it initial state.
it's

2018-07-13 20:48 UTC, jenniferfell commented on packages/animations/src/players/animation_player.ts
> +   * @param p A point in screen coordinates?? (no one-letter param names allowed now)
make sure to get an answer

2018-07-13 20:48 UTC, jenniferfell commented on packages/animations/src/players/animation_player.ts
> +   * @returns The position. ??(what does the number mean?)
I like ?? for notes to reviewers. Easy to search and remove before approval review.

2018-07-13 20:48 UTC, jenniferfell commented on packages/animations/src/players/animation_player.ts
> +   * @return The parent player, if any. ?? (when/why does it have a parent?)
This text doesn't seem to be captured in the output doc

2018-07-13 20:48 UTC, jenniferfell commented on packages/animations/src/players/animation_player.ts
> +   * @returns The time in milliseconds. ??
Again, the @returns for properties doesn't seem to appear in the doc that is generated.

2018-07-13 21:29 UTC, jbogarthyde commented on packages/animations/src/players/animation_player.ts
> +   * @returns The time in milliseconds. ??
my fault -- these are properties, not methods. They have a value, not a return value.

2018-07-13 21:33 UTC, jbogarthyde commented on packages/animations/src/players/animation_player.ts
> +   * @returns The position. ??(what does the number mean?)
Thanks for the review -- I have made your changes.
Still need technical review and resolution of ?? questions from @matsko
 (and eng help with the experimental status/golden file).

2018-07-19 15:16 UTC, matsko commented on packages/animations/src/players/animation_player.ts
> +   * @param p A point in screen coordinates?? (no one-letter param names allowed now)
milliseconds

2018-07-19 15:16 UTC, matsko commented on packages/animations/src/players/animation_player.ts
> +   * @returns The position. ??(what does the number mean?)
The current amount of milliseconds as to where the animation is playing.

2018-07-26 07:32 UTC, matsko requested changes

2018-07-26 07:32 UTC, matsko commented on packages/animations/src/animation_builder.ts
> + * through the `_builder` property.
`_builder` implies it's private. Please review this sentence.

2018-07-27 06:39 UTC, matsko approved these changes

2018-07-27 06:40 UTC, matsko commented on packages/animations/src/animation_event.ts
>   * @experimental Animation support is experimental.
Let's keep it as `@experimental` for now. Once we approach NG7 we can figure out if/when that will be removed.

2018-07-27 16:11 UTC, jbogarthyde commented on packages/animations/src/animation_event.ts
>   * @experimental Animation support is experimental.
Still have to check that golden file matches current stable APIs

2018-07-31 21:46 UTC, mary-poppins commented
You can preview 58dd70f at https://pr24668-58dd70f.ngbuilds.io/.

2018-08-03 17:48 UTC, mary-poppins commented
You can preview 9050560 at https://pr24668-9050560.ngbuilds.io/.

2018-08-03 20:05 UTC, mary-poppins commented
You can preview dffeaff at https://pr24668-dffeaff.ngbuilds.io/.

2018-08-07 18:11 UTC, kara commented
@jbogarthyde It looks like this PR Is still missing approval from @jenniferfell and the public-api group. When all the approvals are in, I can help get this merged.

2018-08-07 18:16 UTC, IgorMinar approved these changes

2018-08-07 22:18 UTC, IgorMinar commented
This PR looks good to me. @jenniferfell's review is the last holding it back, but I think all her comments have been addressed already. If so, can you please dismiss/update the review and send this for merge? thanks

2018-08-07 22:45 UTC, jenniferfell requested changes

2018-08-07 22:45 UTC, jenniferfell commented on packages/animations/src/animation_builder.ts
> + * * Use the `build()` method to create a programmatic animation using the
Please change to numbered steps. Use markdown syntax.

1. Use the `build()` method to...
1. Use the factory object to ...
1. Use the playter object to...

2018-08-07 22:45 UTC, jenniferfell commented on packages/animations/src/animation_builder.ts
> +   * and attaches the new player a DOM element.
Feels like a word is missing. "...and attaches the new player to a DOM element." ?

2018-08-07 22:53 UTC, jbogarthyde commented on packages/animations/src/animation_builder.ts
> +   * and attaches the new player a DOM element.
Creates and attaches the player -- just a long clause about how it creates the player.

2018-08-07 22:59 UTC, mary-poppins commented
You can preview 4e3f641 at https://pr24668-4e3f641.ngbuilds.io/.

2018-08-07 23:04 UTC, mary-poppins commented
You can preview c43608d at https://pr24668-c43608d.ngbuilds.io/.

2018-08-08 00:06 UTC, mary-poppins commented
You can preview 36207a1 at https://pr24668-36207a1.ngbuilds.io/.

2018-08-13 15:37 UTC, mary-poppins commented
You can preview 1fa7ad5 at https://pr24668-1fa7ad5.ngbuilds.io/.

2018-08-13 19:35 UTC, jbogarthyde commented
All green - please run G3 if needed.

2018-08-13 21:26 UTC, IgorMinar commented
I wasn't sure if the new jsdoc tags could affect g3 in some way since closure reads them, so I kicked off a presubmit at http://test/OCL:208541253:BASE:208541646:1534195208651:b2b43c02

2018-08-14 16:55 UTC, jenniferfell approved these changes

2018-08-14 20:14 UTC, benlesh commented
Forced google3 status. Will merge in a few.

2018-08-14 20:16 UTC, closed without merging