feat(ivy): support templateUrl for ngtsc
angular/angular pull request #24704
Opened 2018-06-28 22:33 UTC by alxhub

This commit adds support for templateUrl in component templates within
ngtsc. The compilation pipeline is split into sync and async versions,
where asynchronous compilation invokes a special preanalyze() phase of
analysis. The preanalyze() phase can optionally return a Promise which
will delay compilation until it resolves.

A ResourceLoader interface is used to resolve templateUrls to template
strings and can return results either synchronously or asynchronously.
During sync compilation it is an error if the ResourceLoader returns a
Promise.

Two ResourceLoader implementations are provided. One uses 'fs' to read
resources directly from disk and is chosen if the CompilerHost doesn't
provide a readResource method. The other wraps the readResource method
from CompilerHost if it's provided.

2018-06-28 22:48 UTC, mary-poppins commented
You can preview 9d100de at https://pr24704-9d100de.ngbuilds.io/.

2018-06-29 06:07 UTC, alfaproject commented
Will this support TypeScript path resolution?

2018-06-29 17:01 UTC, mary-poppins commented
You can preview af7f6f9 at https://pr24704-af7f6f9.ngbuilds.io/.

2018-07-02 20:30 UTC, mhevery requested changes

2018-07-02 20:30 UTC, mhevery commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +  it('should compile Components without errors', () => {
Can we have tests for the cases which throw errors.

2018-07-02 22:21 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +  it('should compile Components without errors', () => {
Eventually we will. Right now the errors the compiler throws are temporary - basically assertions that `throw new Error(...)` on encountering something unexpected.

In the future, these will be migrated to become actual user-facing errors which will be reported via TypeScript's diagnostic system, including line/col pointers to the location of the error in the source. These are the errors we should write tests for.

2018-07-02 22:51 UTC, mhevery approved these changes

2018-07-02 23:35 UTC, mary-poppins commented
You can preview c5afae1 at https://pr24704-c5afae1.ngbuilds.io/.

2018-07-03 15:38 UTC, mhevery commented
http://test/OCL:203127686:BASE:203127689:1530632274073:dd5170b0

2018-07-03 20:33 UTC, closed without merging