docs(forms): update API reference for form validators
angular/angular pull request #24734
Opened 2018-07-02 15:43 UTC by brandonroberts

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-07-02 15:54 UTC, mary-poppins commented
You can preview edbc859 at https://pr24734-edbc859.ngbuilds.io/.

2018-07-02 18:55 UTC, kara requested changes

2018-07-02 18:55 UTC, kara commented on packages/forms/src/validators.ts
> +   * if the validation check fails, otherwise `null`.
> A validator function that returns an error map with the `min` property if the validation check fails (e.g. `{min: {min: 3, actual: 2}}`), otherwise `null`.

2018-07-02 18:55 UTC, kara commented on packages/forms/src/validators.ts
> +   * Validator that requires controls to have a value less than the provided number. The validator
> less than or equal to the provided number.

2018-07-02 18:55 UTC, kara commented on packages/forms/src/validators.ts
> +   * if the validation check fails, otherwise `null`.
> A validator function that returns an error map with the `max` property if the validation check fails (e.g. `{max: {max: 3, actual: 4}}`), otherwise `null`.

2018-07-02 18:55 UTC, kara commented on packages/forms/src/validators.ts
> +   * Validator that requires the control value be true.
Can we add something like

> This validator is commonly used for required checkboxes.

2018-07-02 18:55 UTC, kara commented on packages/forms/src/validators.ts
> +   * Validator that requires the control be greater than the provided minimum length. The validator
> Validator that requires the length of the control's value to be greater than or equal to the provided minimum length

2018-07-02 18:55 UTC, kara commented on packages/forms/src/validators.ts
> +   * Validator that requires the controls be less than the provided maximum length. The validator
> Validator that requires that the length of the control's value to be less than or equal to the provided maximum length

2018-07-02 18:55 UTC, kara commented on packages/forms/src/validators.ts
> +   * HTML5 `minlength` attribute.
Maybe instead of `The validator is also provided...`

> This validator is also provided by default if you add the HTML5 `minlength` attribute.

2018-07-02 18:55 UTC, kara commented on packages/forms/src/validators.ts
> +   * is also provided as a `maxlength` directive which is used in combination with the
> This validator is also provided by default if you use the HTML5 `maxlength` attribute.

2018-07-02 18:55 UTC, kara commented on packages/forms/src/validators.ts
> +   * values if the validation check fails, otherwise `null`.
> A validator function that returns an error map with the `minLength` property if the validation check fails (e.g. `{minLength: {requiredLength: 2, actualLength: 1}}`), otherwise `null`.

2018-07-02 18:55 UTC, kara commented on packages/forms/src/validators.ts
> +   * values if the validation check fails, otherwise `null`.
> A validator function that returns an error map with the `maxLength` property if the validation check fails (e.g. `{maxLength: {requiredLength: 3, actualLength: 4}}`), otherwise `null`.

2018-07-02 18:55 UTC, kara commented on packages/forms/src/validators.ts
> +   * is also provided as a `pattern` directive which is used in combination with the
> This validator is also provided by default if you use the HTML5 `pattern` attribute.

2018-07-02 18:55 UTC, kara commented on packages/forms/src/validators.ts
> +   * values if the validation check fails, otherwise `null`.
> A validator function that returns an error map with the `pattern` property if the validation check fails (e.g. `{minLength: {requiredPattern: '[a-zA-Z ]*' , actualValue: '1'}}`), otherwise `null`.

2018-07-02 19:19 UTC, brandonroberts commented on packages/forms/src/validators.ts
> +   * if the validation check fails, otherwise `null`.
What about updating the text, but putting the error map in the example?

```ts
const control = new FormControl(2, Validators.min(3));

console.log(control.errors); // Logs {min: {min: 3, actual: 2}}
```

2018-07-02 19:22 UTC, kara commented on packages/forms/src/validators.ts
> +   * if the validation check fails, otherwise `null`.
That works too!

2018-07-02 19:47 UTC, mary-poppins commented
You can preview cfe5a35 at https://pr24734-cfe5a35.ngbuilds.io/.

2018-07-02 19:50 UTC, mary-poppins commented
You can preview 5cd8003 at https://pr24734-5cd8003.ngbuilds.io/.

2018-07-02 20:05 UTC, mary-poppins commented
You can preview 00a5169 at https://pr24734-00a5169.ngbuilds.io/.

2018-07-10 17:56 UTC, kara approved these changes
LGTM

2018-07-10 17:56 UTC, kara commented on packages/forms/src/validators.ts
> +   * validator exists only as a function and not as a directive.
Nit: fix this formatting? (and on line 107)

2018-07-10 18:05 UTC, kara commented
[presubmit](http://test/OCL:203976753:BASE:203977469:1531245888229:3d955006)

2018-07-10 18:14 UTC, mary-poppins commented
You can preview 3f60556 at https://pr24734-3f60556.ngbuilds.io/.

2018-07-11 01:53 UTC, closed without merging