WIP add API doc for high-priority items
angular/angular pull request #24744
Opened 2018-07-03 16:30 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Adding and editing doc for API items marked as top-priority, starting with Change Detection and Lifecycle Hooks.

2018-07-03 16:40 UTC, mary-poppins commented
You can preview 03b1979 at https://pr24744-03b1979.ngbuilds.io/.

2018-07-03 21:03 UTC, mary-poppins commented
You can preview 949e582 at https://pr24744-949e582.ngbuilds.io/.

2018-07-04 16:36 UTC, mary-poppins commented
You can preview e9293fa at https://pr24744-e9293fa.ngbuilds.io/.

2018-07-05 18:43 UTC, mary-poppins commented
You can preview 227811f at https://pr24744-227811f.ngbuilds.io/.

2018-07-10 15:12 UTC, matpag commented on packages/core/src/change_detection/change_detector_ref.ts
> +   * Components are normally maked as dirty (in need of rerendering) when inputs
Should "maked" be "marked" instead?

2018-07-10 17:22 UTC, mhevery requested changes

2018-07-10 17:22 UTC, mhevery commented on packages/core/src/render/api.ts
> +   * A unique identifying string for the new renderer.
It should say why do we need it. The unique string is used when creating unique styles for encapsulation.

2018-07-10 17:22 UTC, mhevery commented on packages/core/src/render/api.ts
> +   */
There is now a forth one: https://github.com/angular/angular/blob/master/packages/core/src/metadata/view.ts#L39-L49

2018-07-10 17:22 UTC, mhevery commented on packages/core/src/render/api.ts
> +   * Begins rendering.
Notifies that the rendering has began.

2018-07-10 17:22 UTC, mhevery commented on packages/core/src/render/api.ts
> +   * Halts rendering.
Notifies that the rendering is finished.

2018-07-10 17:22 UTC, mhevery commented on packages/core/src/render/api.ts
> +  /**
Used in test only to notify the test when the rendering is completed. Used in combination with animations.

2018-07-10 17:22 UTC, mhevery commented on packages/core/src/render/api.ts
> +   * True to mark a style as important.
it is not a boolean hence no true. Just `Mark style as important`

2018-07-10 17:22 UTC, mhevery commented on packages/core/src/render/api.ts
> +   * True to mark a style as using dash case naming (this-is-dash-case).
same here

2018-07-10 17:22 UTC, mhevery commented on packages/core/src/render/api.ts
> + * expressed declaratively. For example if you need to set a property or an attribute whose name is
I think better text would be:
```
Implement / extend this base class if you wish to implement custom rendering. (Angular has an implementation which renders into DOM) Use custom render if you wish to render to something other than DOM or if you wish to intercept rendering calls. 
```
This is reversed. Normally you write docs from the point of view of I call this method when. But this is a callback so you need to write it from the point of view of When angular calls me I need to do X.

2018-07-10 17:22 UTC, mhevery commented on packages/core/src/render/api.ts
> +   * Destroys the renderer or the host element??
`Notifies that the render is being destroyed.`

Switch the point of view. Because you implement this class, the direction is reversed. You don't call the method. The framework calls it and than it is your responsibility to react.

2018-07-10 17:22 UTC, mhevery commented on packages/core/src/render/api.ts
> +   */
Please rewrite all of the methods from the other point of view because it is a callback.

2018-07-12 22:10 UTC, petebacondarwin commented on packages/examples/core/ts/change_detect/change-detection.ts
> +  set live(value) {
change this to

```
set live(value: boolean) {
```

2018-07-12 22:11 UTC, petebacondarwin commented on packages/core/src/event_emitter.ts
> +   * @internal
Remove this

2018-07-12 22:11 UTC, petebacondarwin commented on packages/core/src/event_emitter.ts
> +  __isAsync: boolean; // tslint:disable-line
Possibly add an extra space before the comment for tslint?

2018-07-12 23:21 UTC, mary-poppins commented
You can preview e7da92c at https://pr24744-e7da92c.ngbuilds.io/.

2018-07-13 15:41 UTC, mary-poppins commented
You can preview 501bf4e at https://pr24744-501bf4e.ngbuilds.io/.

2018-07-13 18:01 UTC, mary-poppins commented
You can preview 21ea4d8 at https://pr24744-21ea4d8.ngbuilds.io/.

2018-07-16 16:42 UTC, jbogarthyde commented
@mhevery I have incorporated your review comments on renderer and externalized the examples you commented on. The rest of the content needs technical review and approval. I'm afraid that externalizing all examples is too problematic to do as part of this PR - let's table that for the moment and handle it separately.

The new doc is pretty much all in core. I don't know who else to ask -- but perhaps you can suggest someone. It's all green now, maybe we can take advantage of this unusual state to get this done.

2018-07-16 16:54 UTC, mary-poppins commented
You can preview 0a70152 at https://pr24744-0a70152.ngbuilds.io/.

2018-07-17 16:20 UTC, mary-poppins commented
You can preview e82a23c at https://pr24744-e82a23c.ngbuilds.io/.

2018-07-17 20:27 UTC, mhevery approved these changes

2018-07-17 20:55 UTC, mhevery commented
http://test/OCL:204968842:BASE:204969005:1531860913267:75c05ced

2018-07-18 15:47 UTC, jbogarthyde commented on packages/core/src/metadata/directives.ts
> +   * Like component and pipes, they must be declared by an NgModule
You're right, and it dosn't add much - removed the modifier.

2018-07-18 15:50 UTC, mary-poppins commented
You can preview 819b337 at https://pr24744-819b337.ngbuilds.io/.

2018-07-18 15:50 UTC, jbogarthyde commented on packages/core/src/metadata/ng_module.ts
> +   * A template can exported declarables from any
can USE exported...

2018-07-18 15:55 UTC, jbogarthyde commented on packages/core/src/metadata/ng_module.ts
> +   * For example, `CommonModule` imports `BrowserModule`, make the
import and export are related concepts, so it makes sense to mention it here

2018-07-18 15:58 UTC, trotyl commented on packages/core/src/metadata/ng_module.ts
> +   * For example, `CommonModule` imports `BrowserModule`, make the
I meant `BrowserModule` imports (and also exports) `CommonModule`, but not the opposite way...

2018-07-18 16:02 UTC, jbogarthyde commented on packages/core/src/metadata/ng_module.ts
> +   * For example, `CommonModule` imports `BrowserModule`, make the
Actually, this contradicts what the "exports" description says about not re-exporting things. Which is true? Does CommonModule have to re-export things from BrowserModule to make them available to ModuleA that imports CommonModule?

2018-07-18 16:05 UTC, jbogarthyde commented on packages/core/src/metadata/ng_module.ts
> +   * For example, `CommonModule` imports `BrowserModule`, make the
How about this: 
 * A template can use exported declarables from any
   * imported module, including those that are imported indirectly
   * and re-exported.
   * For example, `CommonModule` imports `BrowserModule`, and re-exports
   * some declarables, which are then available wherever `CommonModule` is imported.

2018-07-18 16:10 UTC, trotyl commented on packages/core/src/metadata/ng_module.ts
> +   * For example, `CommonModule` imports `BrowserModule`, make the
The point is **`BrowserModule` covers `CommonModule`**, but not the **`CommonModule` covers `BrowserModule`**. Also, `BrowserModule` doesn't import `CommonModule`, but only exports it:
https://github.com/angular/angular/blob/0b28732d779f86f05b4152e77a1cd0f198ce74fe/packages/platform-browser/src/browser.ts#L99

2018-07-18 17:21 UTC, jbogarthyde commented on packages/core/src/metadata/ng_module.ts
> +   * Importing a module does not automatically re-export the imported module's imports.
I've rewritten both `imports` and `exports` - please check again.

2018-07-18 17:35 UTC, trotyl commented on packages/core/src/render/api.ts
> + * `setElementAttribute()` method.
`setElementProperty()` and `setElementAttribute()` are old Renderer V1 API.

2018-07-18 17:35 UTC, mary-poppins commented
You can preview 42f5e7d at https://pr24744-42f5e7d.ngbuilds.io/.

2018-07-18 17:36 UTC, trotyl commented on packages/core/src/render/api.ts
> +   * as a root element, and return the element instance..
Duplicate period at end?

2018-07-18 18:14 UTC, mary-poppins commented
You can preview 79ac05d at https://pr24744-79ac05d.ngbuilds.io/.

2018-07-18 18:24 UTC, mary-poppins commented
You can preview eb73c64 at https://pr24744-eb73c64.ngbuilds.io/.

2018-07-18 19:10 UTC, mary-poppins commented
You can preview 7ab5cac at https://pr24744-7ab5cac.ngbuilds.io/.

2018-07-19 17:49 UTC, matsko commented
https://test/ui#id=OCL:205265446:BASE:205265506:1532022522840:6b09a503

2018-07-20 18:18 UTC, jenniferfell commented
caretaker: This has approvals and seems to have passed all doc-specific tests. It's stuck pending google3 tests. When I click "Details" for the google3 test, I get "This site can't be reached." I'm not sure if this is just a "keep waiting" or if there's something that needs to happen to unstick it. Let us know if we've missed a step we can take on our end. Thanks!

2018-07-20 18:50 UTC, vicb commented
http://test/OCL:205428978:BASE:205429779:1532112201239:1a2bb26b

2018-07-20 19:41 UTC, closed without merging