refactor(ivy): replace pNextOrParent with TNode props
angular/angular pull request #24752
Opened 2018-07-04 05:45 UTC by kara

WIP PR to remove pNextOrParent

2018-07-04 06:30 UTC, mary-poppins commented
You can preview 8a43e3f at https://pr24752-8a43e3f.ngbuilds.io/.

2018-07-04 13:49 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +    const tails: (TNode | null)[] = new Array(noOfNodeBuckets).fill(null);
IIRC you recently mentioned somewhere that `array.slice()` is faster than `new Array(#).fill()` so we may use `pData.slice()` here instead :)

2018-07-05 22:00 UTC, mhevery requested changes
I don't think the current approach will work. I left some comments and created a failing test demonstrating the issue. 587d194690 Let's chat more in the office.

2018-07-05 22:00 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +   * This data used to be stored on LProjectionNode, but cannot be moved to TProjectionNode because
Don't talk about how we got there since the reader may not have the history. Only talk about current state.

Also an example illustrating what is happening would be very useful.

2018-07-05 22:00 UTC, mhevery commented on packages/core/test/render3/content_spec.ts
> +   *      <ng-content></ng-content>
Fix indentation

2018-07-05 22:00 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +   * of the projection list is stored in pData.
I am confused what `pTargetIndex` and `pListIndex` are used for. Perhaps an example would make this more clear to the reader?

2018-07-05 22:00 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +   * list is stored here according to selector index. Otherwise, this is null.
I may be misunderstanding the comment... I am confused that you use the word `selector` here. A component can be used in multiple places, which means that each time it is used it would select different things. 

We should have a test demonstrating it.

2018-07-05 22:08 UTC, mary-poppins commented
You can preview 587d194 at https://pr24752-587d194.ngbuilds.io/.

2018-07-05 22:12 UTC, mary-poppins commented
You can preview 945c0a6 at https://pr24752-945c0a6.ngbuilds.io/.

2018-07-06 20:49 UTC, kara commented on packages/core/src/render3/interfaces/node.ts
> +   * list is stored here according to selector index. Otherwise, this is null.
We have an existing test on line 1071 of content_spec. In the meantime, I added an example that should hopefully make this clearer.

2018-07-06 20:50 UTC, kara commented on packages/core/src/render3/instructions.ts
> +    const tails: (TNode | null)[] = new Array(noOfNodeBuckets).fill(null);
Good call, will change

2018-07-06 20:54 UTC, mary-poppins commented
You can preview 70cd1c2 at https://pr24752-70cd1c2.ngbuilds.io/.

2018-07-07 02:43 UTC, mary-poppins commented
You can preview 2d02880 at https://pr24752-2d02880.ngbuilds.io/.

2018-07-07 02:59 UTC, mary-poppins commented
You can preview 4027280 at https://pr24752-4027280.ngbuilds.io/.

2018-07-09 18:09 UTC, mary-poppins commented
You can preview 97d225d at https://pr24752-97d225d.ngbuilds.io/.

2018-07-09 18:18 UTC, mary-poppins commented
You can preview f6f40fc at https://pr24752-f6f40fc.ngbuilds.io/.

2018-07-09 19:01 UTC, mary-poppins commented
You can preview 375897a at https://pr24752-375897a.ngbuilds.io/.

2018-07-09 19:15 UTC, mary-poppins commented
You can preview 9b03d77 at https://pr24752-9b03d77.ngbuilds.io/.

2018-07-09 21:19 UTC, mary-poppins commented
You can preview 8c155fa at https://pr24752-8c155fa.ngbuilds.io/.

2018-07-09 21:21 UTC, mary-poppins commented
You can preview c5b8049 at https://pr24752-c5b8049.ngbuilds.io/.

2018-07-09 22:42 UTC, mhevery approved these changes

2018-07-09 23:03 UTC, kara commented
[presubmit](http://test/OCL:203847343:BASE:203847413:1531177366567:30b2b2cc)

2018-07-10 18:13 UTC, closed without merging