Refactor runtime i18n code
angular/angular pull request #24805
Opened 2018-07-09 18:59 UTC by ocombe

## PR Type
What kind of change does this PR introduce?

```
[x] Refactoring (no functional changes, no api changes)
```

See #24785

## Does this PR introduce a breaking change?
```
[x] No
```

2018-07-09 19:09 UTC, mary-poppins commented
You can preview 22ba22f at https://pr24805-22ba22f.ngbuilds.io/.

2018-07-09 19:20 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * @param templateRoots An array of template placeholders whose content should be ignored when
could you please reword "template placeholders"

2018-07-09 19:23 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +                    [{'START_LI_1': 2}, {'EXP_1': 1}], ['START_LI_1']);
` [{'START_LI_1': 2}, {'EXP_1': 1}]` is that right ? (isn't this supposed to be expressions only ?)

2018-07-09 19:25 UTC, vicb requested changes
See online comments.

Please add a link to that PR in the GH issue  for all the items addressed here (edit the description).

Thanks

2018-07-10 07:36 UTC, mary-poppins commented
You can preview 16e5f34 at https://pr24805-16e5f34.ngbuilds.io/.

2018-07-10 22:09 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +                    [{'START_LI_1': 2}, {'EXP_1': 1}], ['START_LI_1']);
If this is really the case, we need to change 
- the parameter names,
- the comments,
- the design spec.

ie, in the current i18n.ts:
```
 * @param expressions An array containing, for each template, the maps of expression placeholders
 * and their indexes.
```

2018-07-10 22:11 UTC, vicb commented on packages/core/src/render3/i18n.ts
>   * @param expressions An array containing, for each template, the maps of expression placeholders
as discussed this sometime contains elementPlaceholders this makes the code confusing.

Please update - and check if it is possible to have the ALL element placeholders moved to elements

2018-07-10 22:12 UTC, vicb commented
Could you please next time send 1 commit per change ?

2018-07-11 08:10 UTC, ocombe commented on packages/core/test/render3/i18n_spec.ts
> +                    [{'START_LI_1': 2}, {'EXP_1': 1}], ['START_LI_1']);
It's already in the design doc:
> The important thing to notice here is that the template container p_2 is passed as an expression for the root template, and as an element for the embedded template.

2018-07-11 08:13 UTC, ocombe commented on packages/core/test/render3/i18n_spec.ts
> +                    [{'START_LI_1': 2}, {'EXP_1': 1}], ['START_LI_1']);
Any idea for the name of the parameter? Something that would say "not elements", or "anything with just one tag and no closing tag"?

2018-07-11 08:17 UTC, ocombe commented on packages/core/src/render3/i18n.ts
>   * @param expressions An array containing, for each template, the maps of expression placeholders
I don't think it's possible if we don't want to give a recognizable pattern name to placeholders. It's not really a matter of whether they are elements or something else (we can test the type in the `i18nApply` method), we just need to differentiate placeholders that have an opening AND closing tag from placeholders that don't.

2018-07-12 09:03 UTC, ocombe commented on packages/core/src/render3/i18n.ts
>   * @param expressions An array containing, for each template, the maps of expression placeholders
fixed based on our discussion yesterday

2018-07-12 09:08 UTC, mary-poppins commented
You can preview ba53d9a at https://pr24805-ba53d9a.ngbuilds.io/.

2018-07-12 09:17 UTC, mary-poppins commented
You can preview c33a78b at https://pr24805-c33a78b.ngbuilds.io/.

2018-07-12 15:12 UTC, vicb commented on packages/core/src/render3/i18n.ts
> -  Expression = 3 << 29,
Why not keep `Expression` and add a `TemplateRoot` ?

2018-07-12 15:14 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +                    [{'START_LI': 1}, {'START_SPAN': 1}, {'EXP_1': 1}], ['START_LI', 'START_SPAN']);
Still mixing elements and expressions here

2018-07-13 08:58 UTC, mary-poppins commented
You can preview da42b4f at https://pr24805-da42b4f.ngbuilds.io/.

2018-07-13 18:28 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +              i18n_3 = i18nExpMapping(MSG_ATTR_1, {'EXP_1': 0, 'EXP_2': 1});
shouldn't expression placeholders be the 3rd arg ?

2018-07-13 18:29 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +                    [{'START_LI_0': 1, 'START_LI_1': 2}, {'EXP_1': 1}, {'EXP_2': 1}],
still mixing elements and expressions ?

2018-07-13 18:29 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +                    [null, {'START_SPAN': 1}, {'EXP_1': 1}], ['START_LI', 'START_SPAN']);
still mixing elements and expressions ?

2018-07-13 18:30 UTC, vicb commented on packages/core/test/render3/i18n_spec.ts
> +    const i18n_1 = i18nExpMapping(MSG_DIV_SECTION_1, {'EXP_1': 0, 'EXP_2': 1});
shouldn't expressions be the 3rd argument ?

2018-07-16 08:13 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +  Other = 5 << 29,
For now it's only used for the elements that we want to append at the end when there is a ng-container (and we are inserting in the middle, with existing elements at the end).
We don't want to treat them as regular elements.
Could be replaced by double instruction instead (element + close node) if you want.

2018-07-16 08:46 UTC, ocombe commented on packages/core/test/render3/i18n_spec.ts
> +    const i18n_1 = i18nExpMapping(MSG_DIV_SECTION_1, {'EXP_1': 0, 'EXP_2': 1});
it's `i18nExpMapping` not `i18nMapping`

2018-07-16 08:46 UTC, ocombe commented on packages/core/test/render3/i18n_spec.ts
> +              i18n_3 = i18nExpMapping(MSG_ATTR_1, {'EXP_1': 0, 'EXP_2': 1});
it's `i18nExpMapping` not `i18nMapping`

2018-07-16 08:56 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +  Other = 5 << 29,
I went ahead and replaced it, it makes more sense

2018-07-16 09:36 UTC, mary-poppins commented
You can preview 606d3ba at https://pr24805-606d3ba.ngbuilds.io/.

2018-07-18 21:33 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +  Other = 5 << 29,
>  they could be of any type
nit: Would `Any` be a better name ? (To me other implies different from the others)

2018-07-19 07:44 UTC, mary-poppins commented
You can preview 1574409 at https://pr24805-1574409.ngbuilds.io/.

2018-07-19 09:12 UTC, mary-poppins commented
You can preview 945e533 at https://pr24805-945e533.ngbuilds.io/.

2018-07-19 17:29 UTC, vicb commented on packages/core/src/render3/i18n.ts
>            typeof(phIndex = elements[tmplIndex] ![value]) !== 'undefined') {
please change
```
       if (elements && elements[tmplIndex] &&
           typeof(phIndex = elements[tmplIndex] ![value]) !== 'undefined') {

pour

// compute current element outside of the loop to avoid doing it each time
       if (currentElements && currentElements[value] !== undefined) {
```

2018-07-19 17:36 UTC, vicb commented on packages/core/src/render3/i18n.ts
Below change `// Check if some elements from the template are missing from the translation` for `// Add instructions to remove elements that are not used in the translation`, same kind of thing for expressions

2018-07-19 17:36 UTC, vicb commented on packages/core/src/render3/i18n.ts
>        if (ngDevMode) {
is `ng-container` right on l 227 ?

2018-07-20 08:59 UTC, ocombe commented on packages/core/src/render3/i18n.ts
>        if (ngDevMode) {
yes, to be updated once ng-containers are really integrated into ivy, but I think the behavior will be similar to what I expected

2018-07-20 15:19 UTC, mary-poppins commented
You can preview 143c36d at https://pr24805-143c36d.ngbuilds.io/.

2018-07-20 15:20 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +            (templateRoots.indexOf(value) + 1) !== tmplIndex) {
remove duplicate indexOf call

2018-07-20 15:21 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * @param tmplIndex The index of the current set of instructions
`The index of the current set of instructions` I don't think this is a good description ?

2018-07-20 15:22 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +        if (newTmplIndex !== 0 && newTmplIndex !== tmplIndex) {
add a comment (I don't get why `!== 0` ?)

2018-07-20 15:23 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +            (templateRoots.indexOf(value) + 1) !== tmplIndex) {
Seems to be done further down

2018-07-20 15:30 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +  let currentElements;
Also assigning a temporary empty array would simplify the code below.
(if you do so make it global to avoid having to recreate it on every single fn call)

2018-07-20 15:33 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +  for (let i = 0; i < instructions.length; i++) {
would it be simpler with 2 ifs instead of a for ?

2018-07-20 15:34 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +      let value = b1 ? v1 : v0;
const

2018-07-20 15:36 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +      let value = b4 ? (b1 ? v5 : v4) : (b2 ? (b1 ? v3 : v2) : (b1 ? v1 : v0));
looks wrong

2018-07-20 16:10 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +  for (let i = 0; i < instructions.length; i++) {
instructions can be of any length because the translation can use the same binding multiple times

2018-07-20 16:12 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +              newTmplIndex, index, translationParts, instructions, elements, expressions,
rename `index` to `instructionIndex` ?

2018-07-20 16:55 UTC, mary-poppins commented
You can preview a6c6c87 at https://pr24805-a6c6c87.ngbuilds.io/.

2018-07-20 17:39 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +      (new Array(templateRoots ? templateRoots.length + 1 : 1)).fill(undefined);
nit: extract `numTemplates` in a local variables

2018-07-20 17:42 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +    const value = translationParts[instructionsIndex];
please change `value` for what it is in each of the if branch. A generic `value` makes the review difficult.

2018-07-24 08:31 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +    const value = translationParts[instructionsIndex];
If it was a different type I would do it, but here it's always a string that is always the name of either an element, an expression or a template root. It would make the code more complicated to add `const elementName = value` because it adds no value other than changing the name of the variable.

2018-07-24 08:45 UTC, mary-poppins commented
You can preview e36cab5 at https://pr24805-e36cab5.ngbuilds.io/.

2018-07-24 15:15 UTC, mary-poppins commented
You can preview cbd4709 at https://pr24805-cbd4709.ngbuilds.io/.

2018-07-24 15:15 UTC, vicb reviewed
few minor comments

2018-07-24 15:15 UTC, vicb commented on packages/core/src/render3/i18n.ts
> + * @param instructionsIndex The current index in `translationParts`.
`partIndex` ?

2018-07-24 15:15 UTC, vicb commented on packages/core/src/render3/i18n.ts
> +        if (templateRoots && templateRoots.indexOf(value) !== -1 &&
Please remove duplicate call to `indexOf`

2018-07-24 20:09 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +        if (templateRoots && templateRoots.indexOf(value) !== -1 &&
I had removed it, the rebase must of squeezed that

2018-07-24 20:33 UTC, mary-poppins commented
You can preview c02665f at https://pr24805-c02665f.ngbuilds.io/.

2018-07-24 21:39 UTC, vicb approved these changes
Great, thanks !

2018-07-24 23:03 UTC, vicb commented
http://test/OCL:205905230:BASE:205905270:1532472380460:b05f96a9

2018-07-24 23:42 UTC, closed without merging