feat(ivy): initial ngcc code dump
angular/angular pull request #24897
Opened 2018-07-16 09:31 UTC by petebacondarwin

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2018-07-16 09:35 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/transform/src/translator.ts
> +    { name: string, as: string }[] {
Oops I guess I have a different curly brace formatting approach!

2018-07-16 09:37 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/testing/in_memory_typescript.ts
> +    throw new Error(`Typescript diagnostics failed! ${errors.join(', ')}`);
This block of changes just makes the error output a bit clearer - and is in keeping with how the TS compiler outputs errors.

2018-07-16 09:37 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/testing/in_memory_typescript.ts
> +    return ts.createSourceFile(fileName, contents, languageVersion);
Not all source files are TypeScript :-P

2018-07-16 13:29 UTC, mary-poppins commented
You can preview ee37256 at https://pr24897-ee37256.ngbuilds.io/.

2018-07-17 07:12 UTC, alxhub requested changes
Initial round of comments. Looks great! Should be only minor stylistic updates.

2018-07-17 07:12 UTC, alxhub commented on packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts
> +function isThisAssignment(node: ts.Declaration): node is ts.BinaryExpression {
You can carry extra information here:

`node is ts.BinaryExpression & {lhs: ts.PropertyAccessExpression}`

That will help you avoid the cast above.

2018-07-17 07:12 UTC, alxhub commented on packages/compiler-cli/src/ngcc/src/host/esm5_host.ts
> +    }
Explicit return at the end of the function.

2018-07-17 07:12 UTC, alxhub commented on packages/compiler-cli/src/ngcc/src/host/esm5_host.ts
> +  getClassSymbol(declaration: ts.Declaration) {
Declare the return type.

2018-07-17 07:12 UTC, alxhub commented on packages/compiler-cli/src/ngcc/src/host/esm5_host.ts
> +  protected getConstructorParameterDeclarations(classSymbol: ts.Symbol) {
Declare return type, and throughout.

2018-07-17 07:12 UTC, alxhub commented on packages/compiler-cli/src/ngcc/src/host/esm5_host.ts
> +    if (classSymbol.exports && classSymbol.exports.has(CONSTRUCTOR_PARAMS)) {
Consider inverting the logic here, with early returns if the preconditions aren't met, instead of nested if statements.

2018-07-17 07:12 UTC, alxhub commented on packages/compiler-cli/src/ngcc/src/parsing/esm2015_parser.ts
> +                }
Explicit return

2018-07-17 07:12 UTC, alxhub commented on packages/compiler-cli/src/ngcc/src/rendering/esm2015_renderer.ts
> +    // QUESTION: Should we move the imports to after any initial comment in the file?
I don't think it'll matter. Top of the file should be fine.

2018-07-17 10:01 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/host/esm5_host.ts
> +    if (classSymbol.exports && classSymbol.exports.has(CONSTRUCTOR_PARAMS)) {
Actually I am sorely tempted to implement  tsquery for a lot of this logic. It would be cleaner to read and easier to maintain.

2018-07-17 13:36 UTC, mary-poppins commented
You can preview 493098b at https://pr24897-493098b.ngbuilds.io/.

2018-07-18 12:56 UTC, mary-poppins commented
You can preview 51cc660 at https://pr24897-51cc660.ngbuilds.io/.

2018-07-18 13:37 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts
> +    // QUESTION: do we need to consider decoratored functions (i.e. not ES5 class constructors)?
@alxhub - actually in practice this method is only called with a non-class from within methods on `TypeScriptReflectionHost`. For instance inside `getConstructorParameters()` and `_reflectMember()`. All of these calls are in methods that are not called in the ESM2015 and ESM5 reflection host classes.

Therefore I don't believe that this should be a requirement of the `ReflectionHost` interface.

Instead, I suggest that we rename this interface method to `getDecoratorsOfClass(declaration: ts.Declaration)` and then refactor the `TypeScriptReflectionHost` to have a protected method that can find decorators on any declaration, which is what is used internally for those methods mentioned above.

2018-07-18 13:55 UTC, mary-poppins commented
You can preview 082c994 at https://pr24897-082c994.ngbuilds.io/.

2018-07-23 06:31 UTC, mary-poppins commented
You can preview 8a7b0e9 at https://pr24897-8a7b0e9.ngbuilds.io/.

2018-07-23 06:54 UTC, mary-poppins commented
You can preview 0650f32 at https://pr24897-0650f32.ngbuilds.io/.

2018-07-23 07:13 UTC, mary-poppins commented
You can preview e6466a9 at https://pr24897-e6466a9.ngbuilds.io/.

2018-07-23 14:48 UTC, alxhub commented on packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts
> +    // QUESTION: do we need to consider decoratored functions (i.e. not ES5 class constructors)?
Ah, understood and agreed. `getDecoratorsOfClass` makes more sense.

2018-07-24 10:52 UTC, gkalpak approved these changes

2018-07-24 13:36 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/main-ngcc.ts
> +}
Not sure. This is how Alex set it up for us.

2018-07-24 15:28 UTC, alxhub approved these changes
Approved pending the comments above.

Nice job, especially on the thorough tests!

2018-07-25 05:53 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/rendering/renderer.ts
> +    // QUESTION: do we need to remove contructor param metadata and property decorators?
@alxhub I will do this in a follow up PR as it requires changes to ngtsc

2018-07-25 05:54 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/test/host/esm5_host_spec.ts
> +        { type: ViewContainerRef, },
They are defined locally in this "file". The names happen to coincide with things that `@angular/core` exports but really we are just testing that we have "some" type that can be injected.

2018-07-25 06:37 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/host/esm5_host.ts
> +    }
updated now

2018-07-25 06:37 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/host/esm5_host.ts
> +function getIifeBody(declaration: ts.VariableDeclaration): ts.Block|undefined {
done

2018-07-25 06:41 UTC, mary-poppins commented
You can preview 70668f7 at https://pr24897-70668f7.ngbuilds.io/.

2018-07-25 06:44 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/rendering/renderer.ts
> +    // QUESTION: do we need to remove contructor param metadata and property decorators?
Tracking it here https://github.com/angular/angular/issues/25084

2018-07-26 16:57 UTC, mary-poppins commented
You can preview 70174d1 at https://pr24897-70174d1.ngbuilds.io/.

2018-07-26 17:35 UTC, alxhub commented
To the caretaker: 

When syncing this change into g3, please apply the delta to the BUILD file from cl/206023828 - ngcc needs to be excluded when building :compiler_cli.

2018-07-26 19:12 UTC, alexeagle approved these changes
LGTM for Bazel files

2018-07-26 19:12 UTC, alexeagle commented on BUILD.bazel
> +        "convert-source-map",
note, this will need a minor rebase since https://github.com/angular/angular/pull/24663 is probably landing first

2018-07-27 06:23 UTC, petebacondarwin commented on BUILD.bazel
> +        "convert-source-map",
rebased

2018-07-27 18:39 UTC, IgorMinar commented
I'm going to resolve the conflict and forcepush

2018-07-27 19:00 UTC, mary-poppins commented
You can preview 3d81e06 at https://pr24897-3d81e06.ngbuilds.io/.

2018-07-27 19:55 UTC, petebacondarwin commented
weird was there another conflict because I thought I resolved it this morning

2018-07-27 22:04 UTC, mhevery commented
http://test/OCL:206379974:BASE:206380034:1532729085499:8c249e7f

2018-07-28 00:16 UTC, closed without merging

2018-07-28 09:55 UTC, gkalpak commented
AFAICT, [this change][1] was dropped from this PR (possibly due to a bad rebase?).
I will add it back in #25090.

[1]: https://github.com/angular/angular/commit/89ad4f219#diff-01543abe03a85c5d43cfe49dacb463eaR675