fix(ivy): flatten template fns for nested views
angular/angular pull request #24943
Opened 2018-07-18 00:51 UTC by kara

This PR fixes contexts for recursive components and components with deeply nested `ngFors`. It also fixes bindings to local refs before local ref definitions.

Changes:
- Template functions for dynamically created views are no longer nested inside each other. Instead of nesting the functions and using closures to get parent contexts, the parent contexts are re-defined explicitly through an instruction. This means we no longer create multiple function instances for loops that are nested inside other loops.

Example:
```html
<ul *ngFor="let list of lists">
   <li *ngFor="let item of list'> {{ item }} {{ name }} </li>
</ul>
```

Before:
```ts
function AppComponent(rf: RenderFlags, ctx: AppComponent) {
      // some instructions here
      function ulTemplate(rf1: RenderFlags, ctx0: any) {
            // instructions

            function liTemplate(rf1: RenderFlags, ctx1: any) {...}
      }
}
```

After:
```ts
function ulTemplate(rf: RenderFlags, ctx: any) {...}
function liTemplate(rf: RenderFlags, ctx: any) {
  if (rf & RenderFlags.Create) {
      T(0);
  }
  if (rf & RenderFlags.Update) {
     const item = ctx.$implicit;
     const comp = x(2);
     t(0, i2('', item, ' ', comp.name, ''));
  }
}

function AppComponent(rf: RenderFlags, ctx: AppComponent) {
      // some instructions here
}
```

- `TView.components` no longer tracks directive indices (just host element indices). We can cut the components array in half because context for components is now being stored in the component's `LViewData` instance and can be accessed from there.
- We now have a new instruction, `reference()` (`r()`). Previously, we were using closures to get access to local refs in parent views. Now that nested template functions are flat, they do not have access to the local refs through a closure, so we need another way to walk the view tree. `reference` takes a nesting level and the local ref's index, then walks the view tree to find the correct view from which to load the local ref.

Before:
```ts
function AppComponent(rf: RenderFlags, ctx: AppComponent) {
  if (rf & RenderFlags.Create) {
      Ee(0, 'div', null, ['foo', '']);
      C(2, nestedTemplate, null, [AttributeMarker.SelectOnly, 'ngIf']);
  }
  const foo = load(1) as any;
  function IfTemplate(rf: RenderFlags, ctx: any) {
      if (rf & RenderFlags.Create) {
         T(0);
      }
     if (rf & RenderFlags.Update) {
         t(0, bind(foo));
     }
  }
}
```

After:
```ts
function IfTemplate(rf: RenderFlags, ctx: any) {
    if (rf & RenderFlags.Create) {
       T(0);
    }
   if (rf & RenderFlags.Update) {
      const foo = reference(1, 1) as any;
      t(0, bind(foo));
   }
}
function AppComponent(rf: RenderFlags, ctx: AppComponent) {
  if (rf & RenderFlags.Create) {
      Ee(0, 'div', null, ['foo', '']);
      C(2, nestedTemplate, null, [AttributeMarker.SelectOnly, 'ngIf']);
  }
}
```

2018-07-18 02:08 UTC, mary-poppins commented
You can preview 0734a4e at https://pr24943-0734a4e.ngbuilds.io/.

2018-07-18 17:14 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +  tView.template !(rf, context, ...contexts);
Downleveled to ES5, this will become suboptimal:

`template.apply(void 0, [rf, context].concat(contexts))`.

Manually maintaining the arguments would avoid the array creation :)

(Do we even care in a slow path? 🙈)

2018-07-18 17:14 UTC, JoostK commented on packages/core/test/render3/component_spec.ts
> +            elementStart(0, 'ng-if-tree');
`elementStart(...); elementEnd();` -> `element(...);`

Occurs more often than only here 👍

2018-07-18 17:17 UTC, kara commented on packages/core/test/render3/component_spec.ts
> +            elementStart(0, 'ng-if-tree');
I prefer the explicit syntax

2018-07-18 18:50 UTC, mhevery commented on packages/core/src/render3/interfaces/definition.ts
> +  (rf: RenderFlags, ctx: T, ...parentCtx: ({} | null)[]): void; ngPrivateData?: never;
```
type none = {
  __brand__: 'should not match';
}

type ComponentTemplate<T1, T2 = none, T3 = none, T4 = none> = {	 
  (ctx1: T1, ctx2: T2): void;
};	


let fn1: ComponentTemplate<string>;
fn1 = function () { } 
fn1 = function (x:number) { } 
fn1 = function (x:string) { } 
fn1 = function (x:string, y: number) { } 

let fn2: ComponentTemplate<string, number>;
fn2 = function () { } 
fn2 = function (x:string) { } 
fn2 = function (x:string, y: number) { } 

```

Can we get rid of `ngPrivateData`

2018-07-18 18:50 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> +   * This is also the "insertion" parent for embedded views. This allows us to properly
nit: remove `also`

2018-07-18 20:36 UTC, mhevery requested changes

2018-07-18 20:36 UTC, mhevery commented on packages/compiler/test/render3/r3_compiler_compliance_spec.ts
> +            function MyComponent_li_Template_2(rf: IDENT, ctx0: IDENT, ctx: IDENT) {
per our discussion these functions should be pulled out. (I believe that they will end up in the constant pool)

2018-07-18 22:01 UTC, kara commented on packages/core/src/render3/instructions.ts
> +  tView.template !(rf, context, ...contexts);
This is the slow path, but if we can save on array creation, we should :)

2018-07-19 17:32 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +    null  // declarationParent
declarationView

2018-07-19 17:32 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +  lView[DECLARATION_VIEW] = declarationParent;
declarationView

2018-07-19 17:32 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +  const parentContext3 = parentView3[CONTEXT] !;
Why an exclamation mark for parent view context 3, 2, and 1, but not the the others?

2018-07-19 17:32 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +    currentView = currentView[DECLARATION_VIEW] !;
Perhaps `ngDevMode && assert` here?

2018-07-19 18:09 UTC, mary-poppins commented
You can preview 854d2ee at https://pr24943-854d2ee.ngbuilds.io/.

2018-07-23 21:40 UTC, mary-poppins commented
You can preview 61a7d91 at https://pr24943-61a7d91.ngbuilds.io/.

2018-07-23 21:48 UTC, mary-poppins commented
You can preview e68ff53 at https://pr24943-e68ff53.ngbuilds.io/.

2018-07-23 22:18 UTC, mary-poppins commented
You can preview c4eee9b at https://pr24943-c4eee9b.ngbuilds.io/.

2018-07-23 22:30 UTC, mary-poppins commented
You can preview 4705613 at https://pr24943-4705613.ngbuilds.io/.

2018-07-23 22:47 UTC, mary-poppins commented
You can preview 1a11bd2 at https://pr24943-1a11bd2.ngbuilds.io/.

2018-07-23 22:48 UTC, alxhub reviewed
I'll review more later, but publishing comments for now.

2018-07-23 22:48 UTC, alxhub commented on packages/core/src/render3/instructions.ts
> +  // We support up to 8 nesting levels in embedded views before we give up and call apply()
This is a fair bit of code to be included in every Angular app, regardless of template nesting depth. My test shows this change increases Brotli-compressed hello world size by 150 bytes, or about 5%.

I'm wondering if there's a way to move this logic into the template function itself somehow.

2018-07-23 22:48 UTC, alxhub commented on packages/core/src/render3/instructions.ts
> +  if (!parentView2) {
Nit: in performance sensitive code, use `x === undefined` instead of `!x`. This generates fewer machine code instructions as comparison to `undefined` is cheaper than comparison to falsy values.

2018-07-23 22:48 UTC, alxhub commented on packages/core/src/render3/instructions.ts
> + *  function ulTemplate(rf, ulCtx, appCtx) {...}
How would this work on a definition type?

```
class FooCmp {
  static ngComponentDef = defineComponent({
    template: ?
  });
}
```

What gets passed as `template`? Should it be an array, where the 0th element is the outer template, and indices are used to refer to the inner ones? Do the inner templates need to be hoisted outside the class?

2018-07-23 22:55 UTC, kara commented
> How would this work on a definition type?

The code in that comment is actually outdated (thanks for finding!). It should be: 

```ts
function ulTemplate(rf, ulCtx, appCtx) {...}
function liTemplate(rf, liCtx, ulCtx, appCtx) {...}

class AppComponent {...}
AppComponent.ngComponentDef = defineComponent({
  ...
  template: function AppComponent(rf, appCtx) {...}
});
```

The component's template function is passed as the template property. Any nested templates are hoisted above the class.

(For some reason, I can't reply directly to the comment, so replying here)

2018-07-23 22:59 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +  // We support up to 8 nesting levels in embedded views before we give up and call apply()
@alxhub should be fairly simply with a new instruction, similar to `reference`.

2018-07-23 23:10 UTC, kara commented on packages/core/src/render3/instructions.ts
> +  // We support up to 8 nesting levels in embedded views before we give up and call apply()
@alxhub Yeah, agree it's a fair amount of code. The core problem here is that we haven't been tree-shaking dynamic view code like `renderEmbeddedTemplate` (which calls `callTemplateWithContexts`). Making dynamic view code tree-shakable has been on my list, but it's probably outside the scope of this PR.

2018-07-26 03:38 UTC, mary-poppins commented
You can preview f6081cd at https://pr24943-f6081cd.ngbuilds.io/.

2018-07-26 03:57 UTC, mary-poppins commented
You can preview 2f0a983 at https://pr24943-2f0a983.ngbuilds.io/.

2018-07-26 06:20 UTC, JoostK reviewed
The `getNextContext` instruction is awesome! Nicely done 👍 

We could potentially sync `reference` together with `getNextContext` in order to align their behavior and walk the view in steps for both kind of data.

2018-07-26 06:20 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +export function getNextContext(level: number = 1): any {
We could potentially rewrite to `getNextLevel(level?: number)` and use `level || 1` to save on some bytes (mostly for ES5 targets), although that would change behavior for `getNextContext(0)`.

2018-07-26 17:39 UTC, kara commented on packages/core/src/render3/instructions.ts
> +export function getNextContext(level: number = 1): any {
Although, now that I think about it, if we do end up making `reference` instructions relative, we could get in a case where `reference` comes before a `getNextContext` call on the same level...

2018-07-26 17:52 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +export function getNextContext(level: number = 1): any {
@kara Oh well that is a good point! I'd say if we would expect 0 at some point in time, the argument shouldn't be optional at all.

2018-07-26 19:02 UTC, mhevery approved these changes

2018-07-26 19:02 UTC, mhevery commented on packages/compiler-cli/test/compliance/r3_view_compiler_template_spec.ts
> +          const $inner$ = ctx.$implicit;
Per our discussion let's refactor this to:
```
      function MyComponent_ul_li_div_Template_1(rf, ctx) {
        
        if (rf & 1) {
          const opeqStateOfCurrentView = getRestoreState();
          $i0$.ɵE(0, "div");
          $i0$.ɵL("click", function MyComponent_ul_li_div_Template_1_div_click_listener($event){
            restoreState(opeqStateOfCurrentView);
            const $inner$ = ctx.$implicit;
            const $middle$ = $i0$.ɵx().$implicit;
            const $outer$ = $i0$.ɵx().$implicit;
            const $myComp$ = $i0$.ɵx();
            return $myComp$.onClick($outer$, $middle$, $inner$);
          });
          $i0$.ɵT(1);
          $i0$.ɵe();
        }
```
We can do it in follow up PR.

2018-07-26 19:02 UTC, mhevery commented on packages/core/src/render3/view_ref.ts
> +import {EmbeddedTemplate} from './interfaces/definition';
Is this needed? Seems like a stray import?

2018-07-26 19:02 UTC, mhevery commented on packages/core/src/render3/interfaces/definition.ts
> +export type EmbeddedTemplate<T> = {
Why do we need to have `EmbeddedTemplate` if it is same signature as `ComponentTemplate` function? (remember `ngPrivateData` will go away soon)

2018-07-26 19:10 UTC, kara commented on packages/core/src/render3/interfaces/definition.ts
> +export type EmbeddedTemplate<T> = {
Yeah, no longer necessary given `ngPrivateData` is going away

2018-07-28 02:06 UTC, mary-poppins commented
You can preview e940532 at https://pr24943-e940532.ngbuilds.io/.

2018-07-28 02:46 UTC, alxhub approved these changes
LGTM from the compiler side.

2018-07-28 02:46 UTC, alxhub commented on packages/compiler/src/render3/view/template.ts
> +  private _updateCodeFns: (() => o.Statement)[] = [];
Can you add a comment for each of these changed/added fields, just a 1-2 line explanation of what's being tracked and why? I think it would greatly aid the reviewability of future PRs against this class.

2018-07-28 02:46 UTC, alxhub commented on packages/compiler/src/render3/view/template.ts
> +  checkForSharedContextVar(value: BindingData) {
I prefer to name functions like this `maybeGenerateSharedContextVar()`. It implies a possible action, whereas `check*` implies side-effect-freeness to me.

2018-07-28 02:47 UTC, mary-poppins commented
You can preview 96806d7 at https://pr24943-96806d7.ngbuilds.io/.

2018-07-28 02:52 UTC, mary-poppins commented
You can preview d4103d6 at https://pr24943-d4103d6.ngbuilds.io/.

2018-07-28 02:57 UTC, kara commented on packages/compiler/src/render3/view/template.ts
> +  checkForSharedContextVar(value: BindingData) {
Funny you mention that, I had it as `maybe` and then changed it to this. I'll change it back!

2018-07-28 09:35 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> + * e.g. const outer = x().$implicit; const inner = x().$implicit;
Given that we traverse the views bottom-up, shouldn't `outer` and `inner` be swapped here? To me, `outer` would refer to the view that is higher up in the tree, so should be hit later than `inner`.

2018-07-28 09:35 UTC, JoostK commented on packages/core/test/render3/common_integration_spec.ts
> +    it('should support context for 9+ levels of embedded templates', () => {
This test is not so relevant anymore after the refactoring to `nextContext`. Should we keep it in? Or perhaps rename the `it` as in the future it may not be obvious why this specific test for 9+ levels is here.

2018-07-29 23:44 UTC, mary-poppins commented
You can preview 26f76b1 at https://pr24943-26f76b1.ngbuilds.io/.

2018-07-29 23:52 UTC, kara commented
[presubmit](http://test/OCL:206511152:BASE:206511379:1532908098675:19d886a0)

2018-07-30 06:30 UTC, trotyl commented
Before this change, **private properties usage is fully supported in any template**, but this change is going to **make private properties usage quite inconsistent**. Given the class:

```typescript
class AppComponent {
  private foo = 42
}
```

Then using private property directly inside Component template is allowed:

```html
<!-- Works -->
<div>{{ foo }}</div>
```

But using private property inside any embedded template is NOT allowed:

```html
<!-- Throws -->
<div *ngIf="true">{{ foo }}</div>
```

Even supporting private property is not promised, but the implementation detail could make it confusing to users.

2018-07-30 17:34 UTC, mhevery commented
@trotyl 
1. Private references to context should never be supported and it is not supported in current version, so I am confused about your comment.
2. Type checking is a separate issues which is outside the scope of the runtime.

2018-07-30 22:54 UTC, mary-poppins commented
You can preview 180082e at https://pr24943-180082e.ngbuilds.io/.

2018-07-30 22:55 UTC, closed without merging

2018-07-31 02:49 UTC, trotyl commented
@mhevery I didn't mean it's a breaking change from view engine, but having in-fact partial support is confusing.

Imagine a user have private property already, once he/she added an `*ngIf` then it suddenly becomes an error.

Also polluting entire module scope with additional `FunctionDeclaration`s is dangerous and could break users' code.

So how about using IIFE while and do NOT emit code outside the `ClassDeclaration` like:

```typescript
class MyComponent {
  static ngComponentDef = ɵdefineComponent({
    template: (() => {
      function MyComponent_li_Template_2(rf: RenderFlags, ctx: SomeContext) {
        // ...
      }
      function MyComponent_Template(rf: RenderFlags, ctx: MyComponent) {
        if (rf & 1) {
          ɵE(0, "ul", null, $c1$);
          ɵC(2, MyComponent_li_Template_2, null, $c2$);
          ɵe();
        }
        // ...
      }
      return MyComponent_Template;
    })()
  })
}
```

I guess this is also what TypeScript does in their code emitting.

2018-08-01 10:43 UTC, trotyl commented
@mhevery Please also consider the possibility of `ClassExpression` support in the future, a `ClassExpression` could have same name or even no name:

```typescript
const createFooComponent = (val: number) => (@Component({}) class { foo = val })
const createBarComponent = (val: number) => (@Component({}) class { bar = val })
```

And it's impossible to emit code to their own scopes, but only at top-level. Then the compiler would need to maintain an extra class counter per module.