docs: square odds example in rxjs guide
angular/angular pull request #24947
Opened 2018-07-18 06:27 UTC by palerdot

The example `squareOdd` for showing squaring odd numbers using RxJS operators is wrong. The current snippet will square even numbers. The same example is shown correctly in the `chaining` section.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-07-18 08:44 UTC, JanMalch commented
Did you test it? It works correctly, because 
`n % 2` for even is `0`, which evaluates to `false` for booleans.
If there is a problem, then it's that TypeScript has a problem with the result being `number` and not `boolean`. Your solution is better in that case and better to read, but I'm JavaScript the code is working as intended.

2018-07-18 12:34 UTC, brandonroberts requested changes
The git commit message should be updated to `docs: square odds example in rxjs guide`

2018-07-18 12:34 UTC, brandonroberts commented on aio/content/examples/rx-library/src/operators.1.ts
>  const squareOddVals = pipe(
This should be updated to add a type to the `n` value in the `filter` function. See https://github.com/angular/angular/issues/24560 for context.

2018-07-20 02:15 UTC, brandonroberts commented
@palerdot squash these down to a single commit with the updated message.

2018-07-20 02:15 UTC, brandonroberts approved these changes

2018-07-20 05:00 UTC, palerdot commented
@brandonroberts squashed into a [single commit](https://github.com/angular/angular/pull/24947/commits/cc33319b8aba6591ed1279d40a0a34501154d2d5)

2018-07-23 12:54 UTC, brandonroberts approved these changes

2018-07-23 15:43 UTC, closed without merging