docs(aio): Remove subsections and update contribute page
angular/angular pull request #24986
Opened 2018-07-19 22:03 UTC by sjtrimble

- Removed `l-sub-section` class and use throughout which is the same as the `alert is-helpful` element
- Updated the author style guide notes on how alerts and callouts should be used
- Updated Contribute page to not use alerts (not proper semantics)

<hr>
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2018-07-19 22:14 UTC, mary-poppins commented
You can preview 045d6f6 at https://pr24986-045d6f6.ngbuilds.io/.

2018-07-20 09:31 UTC, gkalpak reviewed
I trust you to have replaced all `l-sub-section` occurrences (I didn't check myself :grin:).

2018-07-20 09:31 UTC, gkalpak commented on aio/src/styles/2-modules/_card.scss
> +  padding: 1rem 2rem;
Does it make sense to use rems here, while we use px almost everywhere else?
(If you're not doing the right thing, at least be consistent about doing a bad thing :stuck_out_tongue:)

2018-07-20 09:31 UTC, gkalpak commented on aio/src/styles/2-modules/_contribute.scss
> +    *:first-child {
I think you meant `> :first-child` (to only apply to the first child of the `.card-section`). `*:first-child` (which is equivalent to just `:first-child`) will apply to any nested element that is the first child of its parent and has `.card-section` as a (distant) ancestor.

2018-07-20 09:31 UTC, gkalpak commented on aio/content/guide/docs-style-guide.md
> +Alerts draw attention to short important points. Alerts should not be used for multi-line content (use [callouts](#callouts "callouts") insteads).
_insteads_ --> _instead_

2018-07-20 09:31 UTC, gkalpak commented on aio/content/guide/docs-style-guide.md
> +  You'll learn about styles for live examples in the [section below](guide/docs-style-guide#live-examples "Live examples").
The link URL could just be `#live-examples` (I think).
But what do live examples have to do with alerts? :confused:

2018-07-20 09:31 UTC, gkalpak commented on aio/content/guide/docs-style-guide.md
> +  Note that at least one blank line must follow the opening `<div>`. A blank line before the closing `</div>` is customary but not required.
At this point, you haven't mentioned anything about a `<div>`.
Maybe move this sentence below the code example or mention how alerts are created.

2018-07-21 16:49 UTC, petebacondarwin requested changes
A few minor changes required

2018-07-21 16:49 UTC, petebacondarwin commented on aio/content/guide/docs-style-guide.md
> +An alert of callout _must not_ contain anything _essential_ to that understanding. Don't put a critical instruction or a tutorial step in a subsection.
Typo
> An alert **or** callout...

2018-07-21 16:49 UTC, petebacondarwin commented on aio/content/guide/docs-style-guide.md
> +An alert of callout _must not_ contain anything _essential_ to that understanding. Don't put a critical instruction or a tutorial step in a subsection.
subsection -> alert or callout

2018-07-21 16:49 UTC, petebacondarwin commented on aio/content/guide/docs-style-guide.md
> +  Note that at least one blank line must follow the opening `<div>`. A blank line before the closing `</div>` is customary but not required.
Actually I would rather say that the div tags (both opening and closing) must have a blank line before *and* after.  E.g.

```html
content before

<div ...>

inner content

</div>

content after
```

This is because the markdown parser doesn't understand that things are separate HTML tags if they are connected to markdown paragraphs.

2018-07-21 16:49 UTC, petebacondarwin commented on aio/content/guide/docs-style-guide.md
> +You'll learn about styles for live examples in the [section below](guide/docs-style-guide#live-examples "Live examples").
blank line needed before this paragraph

2018-07-21 16:49 UTC, petebacondarwin commented on aio/src/styles/2-modules/_card.scss
> +  // Does not produce an on-hover effect as the card mixin has
I don't quite understand this comment. Are you saying that this rule is needed "because" the card mixin doesn't not provide one?

2018-07-23 05:05 UTC, sjtrimble commented on aio/content/guide/docs-style-guide.md
> +You'll learn about styles for live examples in the [section below](guide/docs-style-guide#live-examples "Live examples").
There should be a blank line there already, as the paragraph before it got removed.

2018-07-23 05:06 UTC, sjtrimble commented on aio/content/guide/docs-style-guide.md
> +  Note that at least one blank line must follow the opening `<div>`. A blank line before the closing `</div>` is customary but not required.
I thought so, but the previous text didn't specify so I thought perhaps it was for a reason. I have updated now.

2018-07-23 05:06 UTC, sjtrimble commented on aio/content/guide/docs-style-guide.md
> +  You'll learn about styles for live examples in the [section below](guide/docs-style-guide#live-examples "Live examples").
Just kept what the previous text used to have. Not sure what would make more sense? Just let me know and I can change.

2018-07-23 05:07 UTC, sjtrimble commented on aio/src/styles/2-modules/_card.scss
> +  padding: 1rem 2rem;
😱 I updated this and a couple other rem references :)

2018-07-23 05:08 UTC, sjtrimble commented on aio/src/styles/2-modules/_card.scss
> +  // Does not produce an on-hover effect as the card mixin has
I updated the comment that is hopefully clearer- basically trying to say that the `card` mixin has a hover effect and this style removes that.

2018-07-23 05:12 UTC, mary-poppins commented
You can preview 08e9aff at https://pr24986-08e9aff.ngbuilds.io/.

2018-07-23 06:55 UTC, petebacondarwin commented on aio/content/guide/docs-style-guide.md
> +You'll learn about styles for live examples in the [section below](guide/docs-style-guide#live-examples "Live examples").
Oh yes, sorry. I missed that.

2018-07-23 06:58 UTC, petebacondarwin approved these changes

2018-07-23 20:52 UTC, kara approved these changes
LGTM

2018-07-24 15:23 UTC, closed without merging