feat(common): support custom JSON parser in HttpClient
angular/angular pull request #25027
Opened 2018-07-22 12:20 UTC by trotyl

closes #21079

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #21079

When user works with an extended JSON format, eg. [JSON5](https://json5.org/), due to it's not compatible with `JSON.parse()`, user have to make it raw text and parse it manually.

But JSON5 format is still conceptually `'json'` rather than `'text'`, it's a fully superset of ES JSON, just being more human friendly.

## What is the new behavior?

Simply with:

```typescript
@NgModule({
  providers: [
    { provider: JsonParser, useValue: JSON5 }
  ]
})
class AppModule {}
```

Then server could provide JSON5 response directly and no error would be raised.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-07-22 20:06 UTC, JoostK commented on packages/common/http/src/module.ts
> +    {provide: JsonParser, useFactory: _JSON, deps: []},
Couldn't this just be `useValue: JSON`?

2018-07-22 23:37 UTC, alfaproject commented on packages/common/http/src/xhr.ts
> +export abstract class JsonParser {
Why not an interface/token?

2018-07-23 01:41 UTC, trotyl commented on packages/common/http/src/module.ts
> +    {provide: JsonParser, useFactory: _JSON, deps: []},
From my knowledge, AOT compiler doesn't support global/ambient identifier reference yet:

https://github.com/angular/angular/blob/7960d1879d87f1d9e4f7f202423960d874a6a08f/packages/platform-browser/src/browser.ts#L59-L61

2018-07-23 02:05 UTC, trotyl commented on packages/common/http/src/xhr.ts
> +export abstract class JsonParser {
Sounds reasonable, since this is only consumed by Angular rather than by user, a token should be better.

2018-07-23 07:10 UTC, JoostK commented on packages/common/http/src/module.ts
> +    {provide: JsonParser, useFactory: _JSON, deps: []},
@trotyl Makes sense, thanks for enlightening me 👍

2019-09-04 07:13 UTC, Lonli-Lokli commented
What should be done to accept this PR?

2021-01-26 19:35 UTC, petebacondarwin requested changes
@trotyl thanks for this PR. I am sorry it slipped under our radar for so long. I rebased it and cleaned up the conflicts. But I have a few suggestions for how to make it a bit slimmer.

2021-01-26 19:35 UTC, petebacondarwin commented on packages/common/http/src/xhr.ts
> +  constructor(private xhrFactory: XhrFactory, @Inject(JSON_PARSER) private jsonParser: JsonParser) {
How about making this optional, then we wouldn't have to define a provider for the default case:

```suggestion
  constructor(private xhrFactory: XhrFactory, @Optional() @Inject(JSON_PARSER) private jsonParser?: JsonParser) {
  if (jsonParser == null) { // note == matches both `null` and `undefined`
    this.jsonParser = JSON;
  }
```

2021-01-26 19:35 UTC, petebacondarwin commented on packages/common/http/test/xhr_spec.ts
> +      backend = new HttpXhrBackend(factory, JSON);
If `jsonParser` was optional this would not need to change.

2021-01-26 19:35 UTC, petebacondarwin commented on packages/common/http/src/xhr.ts
> + * Utility for parsing JSON text to JavaScript object
I think we would need a bit more documentation for this and the `JSON_PARSER` token below, ideally with an example and referencing each other.

2021-01-26 19:35 UTC, petebacondarwin commented on packages/common/http/src/module.ts
> +}
If `jsonParser` was optional then this would not be needed.

2021-01-29 15:42 UTC, petebacondarwin commented
We discussed this in the team meeting yesterday. The general consensus is that this is actually fairly straightforward to do via an interceptor and that the real problem is the lack of discoverability of this approach to solving the problem.

We accept that the problem is compounded by the fact that HttpClient defaults to json parsing with its own parser and so the natural solution that people lean towards is replacing this built-in JSON parsing directly. It would have been better if the default had been text so that JSON parsing felt more like a special case that would lead more naturally to overriding via an interceptor.

The proposal then, is not to merge this feature into core, but instead to improve the documentation to lead developers clearly to an interceptor based solution.

Here is a link to an example of how custom JSON parseing could be done in a reusable interceptor: https://stackblitz.com/edit/angular-ivy-nrdj5q?file=src%2Fapp%2Fapp.module.ts. Note that this could be wrapped up and distributed as a 3rd party library and then the application developer would only need to provide their own JsonParser class.

2021-01-29 15:49 UTC, closed without merging