doc: refactor lazy loading modules example
angular/angular pull request #25071
Opened 2018-07-24 14:36 UTC by danielsogl

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The `angular/http` is deprecated

## What is the new behavior?
Replaced the deprecated `angular/http` module import by `angular/common/http` module

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-07-24 14:36 UTC, danielsogl commented
cc @brandonroberts

2018-07-25 02:16 UTC, brandonroberts requested changes

2018-07-25 02:16 UTC, brandonroberts commented on aio/content/examples/lazy-loading-ngmodules/src/app/app.module.ts
> -import { BrowserModule } from '@angular/platform-browser';
I don't feel too strongly about it, but I feel like `BrowserModule` should be first. Its the first import when you generate a new project.

2018-07-25 05:43 UTC, danielsogl commented on aio/content/examples/lazy-loading-ngmodules/src/app/app.module.ts
> -import { BrowserModule } from '@angular/platform-browser';
But if you read [Style Guide 03-06](https://angular.io/guide/styleguide#style-03-06): 

> Consider listing destructured imported symbols alphabetically. Why? Alphabetizing makes it easier to read and locate symbols.

2018-07-27 17:17 UTC, danielsogl commented
@brandonroberts can you remove the cleanup label?

2018-07-27 17:26 UTC, brandonroberts approved these changes

2018-08-01 17:55 UTC, closed without merging