feat(ivy): JIT support for inheriting input/output from bare base class
angular/angular pull request #25094
Opened 2018-07-25 16:42 UTC by benlesh

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[x] Other... Please describe: ivy work
```

## What is the new behavior?

Adds support for inheriting bare classes, that have `@Input` and `@Output` properties, at runtime.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-07-25 17:44 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> +function fillProperties(target: {[key: string]: string}, source: {[key: string]: string}) {
Possibly should reuse the utils this time...

https://github.com/angular/angular/blob/0bcf20c9fa7273371d053ffe1ef91451714b592d/packages/core/src/render3/features/inherit_definition_feature.ts#L19-L25

2018-07-25 17:44 UTC, trotyl commented on packages/core/src/render3/definition.ts
> +   *    API will be simplified to be consistent with `output`.
`output` (in the last) -> `outputs`?

2018-07-25 17:44 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> +      const defProp = baseDef[key] = baseDef[key] || {};
Wouldn't `inputs`/`outputs` here **NOT** be minified by closure compiler while got minified in `initializeBaseDef` and `defineBase`?

2018-07-27 00:22 UTC, mhevery requested changes

2018-07-27 00:22 UTC, mhevery commented on packages/core/test/render3/Inherit_definition_feature_spec.ts
> +    expect(subDef.declaredInputs).toEqual({
This use case is the case when declared inputs and inputs are the same. Could we have a use-case where they are not the same as in:
```
class MyClass {
  @Input('publicName')
  declaredName: string = 'value';
}
```

2018-07-27 00:22 UTC, mhevery commented on packages/core/src/metadata/directives.ts
> +const NG_BASE_DEF = 'ngBaseDef';
I think all of these constant should be removed. The reason is that you are breaking closure compiler. 
```
class C {
  static ngBaseDef = defineBase(...);
}
```
than `ngBaseDef` is eligible for renaming by closure compiler to `a` or something in which case this will fail.

```
C[NG_BASE_DEF]; // will read the declared name rather than minified name.
```

So the correct way to read this is:
```
C.ngBaseDef
```
That way the closure compiler will rename this read as well.

2018-07-27 00:22 UTC, mhevery commented on packages/core/src/metadata/directives.ts
> +const updateBaseDefFromIOProp = (key: 'inputs' | 'outputs') =>
Same problem here. You can't have both `obj.input` and `obj['input']` It will confuse closure. You always have to be consistent, and in our case it should be `obj.input`. I would pass in `boolean` and than do `ifInput ? obj.input : obj.output`.

2018-07-27 00:22 UTC, mhevery commented on packages/core/src/metadata/directives.ts
> +      const defProp = baseDef[key] = baseDef[key] || {};
correct, this is an issue.

2018-07-27 00:22 UTC, mhevery commented on packages/core/src/render3/definition.ts
> + * Create a base definition
This is a public API. You need to explain this in detail along with an example.

2018-07-27 00:22 UTC, mhevery commented on packages/core/src/render3/definition.ts
> +   *   minifiedDeclaredInput2: [ 'publicInput2', 'declaredInput2'],
I don't see a spec for this use case.

2018-07-27 00:22 UTC, mhevery commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +      break;
not a fan of `break` could we rewrite without it? `superType = null`?

2018-07-27 00:22 UTC, mhevery commented on packages/core/test/render3/ivy/jit_spec.ts
> +// tslint:disable-next-line:no-unused-expression
I don't think we need this. I think you have a different version of tslint and it is causing issues. Please clean this up.

2018-07-30 17:21 UTC, benlesh commented on packages/core/src/metadata/directives.ts
> +const NG_BASE_DEF = 'ngBaseDef';
Is closure compiler smart enough to account for the `hasOwnProperty` check? :thinking:

2018-07-30 17:26 UTC, benlesh commented on packages/core/src/render3/definition.ts
> + * Create a base definition
What more would you add? I was following what was done for `defineComponent` and `defineDirective`.

2018-07-30 17:30 UTC, benlesh commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +      break;
I don't think that is going to make it more readable.

`break`, which idiomatically breaks the (only) `while` loop, versus setting a variable to `null`, which the reader only knows breaks the while loop if they've memorized the conditional from the `while` at the top, or the scroll back up to look at it.

If it were two or more nested loops, I'd agree, but in this case I'm resisting. :P

2018-07-30 17:40 UTC, benlesh commented on packages/core/test/render3/ivy/jit_spec.ts
> +// tslint:disable-next-line:no-unused-expression
I have the latest version of tslint, typescript, and the tslint plugin for VSCode. It's a lint violation and it causes the _entire document_ to be highlighted in greed while I'm editting. It would probably be better if we just used `if` statements in places like this.

2018-07-30 17:45 UTC, benlesh commented on packages/core/test/render3/Inherit_definition_feature_spec.ts
> +    expect(subDef.declaredInputs).toEqual({
Done.

2018-07-30 19:08 UTC, gkalpak commented on packages/core/src/render3/definition.ts
> +   *   minifiedDeclaredInput2: [ 'publicInput2', 'declaredInput2'],
The order of values in the array is reversed (compared to the unminified version).

2018-07-30 21:28 UTC, benlesh commented on packages/core/src/render3/definition.ts
> +   *   minifiedDeclaredInput2: [ 'publicInput2', 'declaredInput2'],
:+1:

2018-07-30 21:36 UTC, benlesh commented on packages/core/src/metadata/directives.ts
> +function fillProperties(target: {[key: string]: string}, source: {[key: string]: string}) {
Agree... moving that to `util/property`

2018-07-30 22:55 UTC, mhevery approved these changes

2018-07-31 20:50 UTC, mary-poppins commented
You can preview ce86f70 at https://pr25094-ce86f70.ngbuilds.io/.

2018-07-31 20:53 UTC, mary-poppins commented
You can preview 8c350f9 at https://pr25094-8c350f9.ngbuilds.io/.

2018-07-31 21:49 UTC, mhevery commented
http://test/OCL:206831311:BASE:206831398:1533073719295:3d648d08

2018-07-31 23:26 UTC, closed without merging

2018-08-01 05:01 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> +      if (!constructor.hasOwnProperty('ngBaseDef')) {
This still breaks minification, isn't it?