docs(testing): Update the link to the Jasmine docs
angular/angular pull request #25175
Opened 2018-07-28 00:25 UTC by samal84

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #24462

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Also update the http part of the link to to https.

2018-07-28 00:37 UTC, brandonroberts requested changes
Remove `(testing)` from the commit message so it's just `docs: ...`

2018-07-28 09:11 UTC, gkalpak commented on aio/content/guide/testing.md
> +The Angular CLI downloads and install everything you need to test an Angular application with the [Jasmine test framework](https://jasmine.github.io/2.9/introduction.html).
I think it would be better to just link to https://jasmine.github.io/ (instread of having to constantly update the link).
From there, people can easily find what they are looking for (what is JAsmine, how to get started, docs about a specific version, etc.).

2018-07-30 19:05 UTC, brandonroberts commented on aio/content/guide/testing.md
> +The Angular CLI downloads and install everything you need to test an Angular application with the [Jasmine test framework](https://jasmine.github.io/2.9/introduction.html).
I don't have an issue with linking to the general Jasmine docs. Let's just hope it doesn't lead to someone opening an issue about pointing to a specific version ;-)

2018-08-01 23:11 UTC, IgorMinar commented
I updated the PR and force-pushed

2018-08-01 23:13 UTC, closed without merging