docs(aio): add async validation chapter
angular/angular pull request #25189
Opened 2018-07-29 09:53 UTC by zetsnotdead

## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

## PR Type

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Issue Number: #22881 

## What is the new behavior?
Add async validation section to form validation chapter at angular.io. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2018-07-30 20:55 UTC, mary-poppins commented
You can preview 9386751 at https://pr25189-9386751.ngbuilds.io/.

2018-08-01 20:10 UTC, kara requested changes
Great job on this section!  Some initial feedback below.

2018-08-01 20:10 UTC, kara commented on aio/content/guide/form-validation.md
> +* Observable must be finite, meaning it must complete at some point. You can convert an infinite Observable into a finite one with the use of operators such as `first`, `last`, `take` or `takeUntil`.
Important point 👍

2018-08-01 20:10 UTC, kara commented on aio/content/guide/form-validation.md
> +With Reactive Forms:
With reactive forms:

2018-08-01 20:10 UTC, kara commented on aio/content/examples/form-validation/src/app/shared/alter-ego.directive.ts
> +  validate(ctrl: FormControl) {
This method receives the `AbstractControl` type and returns `Promise<ValidationErrors|null>|Observable<ValidationErrors|null>`

2018-08-01 20:10 UTC, kara commented on aio/content/guide/form-validation.md
> +The `UniqAlterEgoValidator` delegates to the `HeroesService` `isAlterEgoTaken` method with the current control value. We `map` the result into the `ValidationError` object if the alter ego is taken,
It might be good to call out that the `isAlterEgoTaken` method returns an Observable, so that after we pipe it through `map`, what we are actually returning from the `validate` method is an `Observable`. We should probably also say something about how the async request is triggered by validation, but the validation errors (or null) won't be set until the HTTP request completes.

2018-08-01 20:10 UTC, kara commented on aio/content/guide/form-validation.md
> +### Adding to Template Driven Forms
I don't think these next two sections are necessary, given that we already explained how to add custom validators in reactive/TD forms in the last section. I'd remove.

2018-08-02 07:39 UTC, zetsnotdead commented
Thank you for the quick review. I'll fix it asap :ok_hand:

2018-08-02 08:02 UTC, zetsnotdead commented on aio/content/guide/form-validation.md
> +<input [(ngModel)}="name" #nameCtrl="ngModel" appSomeAsyncValidator>
Wouldn't naming the template variable `name` clash with the `name` property binding?

2018-08-02 10:12 UTC, mary-poppins commented
You can preview a6c7509 at https://pr25189-a6c7509.ngbuilds.io/.

2018-08-02 16:35 UTC, kara commented on aio/content/guide/form-validation.md
> +<input [(ngModel)}="name" #nameCtrl="ngModel" appSomeAsyncValidator>
Yep, it would, sorry! I didn't see that. Maybe `#nameDir` or `nameModel` ?

2018-08-02 16:43 UTC, kara reviewed
Thanks for the quick update! This looks good to me, aside from a few final typos / nits. @brandonroberts @jenniferfell Do you have any feedback from the docs team side?

2018-08-02 16:43 UTC, kara commented on aio/content/guide/form-validation.md
> +As you can see the `UniqueAlterEgoValidator` class implements the `AsyncValidator` interface. In the constructor, we inject the `HeroesService` that has the following interface:
Missing comma

> As you can see, the ...

2018-08-02 16:43 UTC, kara commented on aio/content/guide/form-validation.md
> +### Implementing Custom Validator
> Implementing Custom Async Validator

2018-08-02 16:43 UTC, kara commented on aio/content/guide/form-validation.md
> +After some time passes, the `Observable` chain completes and the async validation is done. The `pending` flag is set to `false`, ale the form validity is updated.
Typo: ale -> and

2018-08-02 18:20 UTC, brandonroberts requested changes

2018-08-03 11:13 UTC, zetsnotdead commented
Thanks for another quick review @brandonroberts @kara. Fixed everything as requested :+1:

2018-08-03 11:17 UTC, mary-poppins commented
You can preview d90e953 at https://pr25189-d90e953.ngbuilds.io/.

2018-08-09 22:55 UTC, kara approved these changes
LGTM. @brandonroberts Do you want to take another look?

2018-08-10 01:29 UTC, brandonroberts approved these changes

2018-08-10 01:29 UTC, brandonroberts commented
LGTM

2018-08-10 16:15 UTC, closed without merging