fix(core): allow abstract class as injection token
angular/angular pull request #25222
Opened 2018-07-31 13:50 UTC by trotyl

closes #23611

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/angular/angular/issues/23611

There're many services used an abstract class as tokens, like:

+ [ChangeDetectorRef](https://angular.io/api/core/ChangeDetectorRef);
+ [Injector](https://angular.io/api/core/Injector);
+ [NgModuleFactoryLoader](https://angular.io/api/core/NgModuleFactory);
+ [TemplateRef](https://angular.io/api/core/TemplateRef);
+ [ViewContainerRef](https://angular.io/api/core/ViewContainerRef);
+ [RendererFactory2](https://angular.io/api/core/RendererFactory2);
+ [Renderer2](https://angular.io/api/core/Renderer2);
+ [Sanitizer](https://angular.io/api/core/Sanitizer);
+ ...

After https://github.com/angular/angular/pull/13785 merged, `injector.get(ChangeDetectorRef)` would produce a deprecation warning since an `abstract class` is not a `Type`:

https://github.com/angular/angular/blob/3f20a2fb5ad243a85a215cbf70269a769804a224/packages/core/src/di/injector.ts#L71-L75

Also in the new `inject()` API, it throws an error as no deprecated `any` fallback:

https://github.com/angular/angular/blob/3f20a2fb5ad243a85a215cbf70269a769804a224/packages/core/src/di/injector.ts#L459-L461

## What is the new behavior?

Abstract classes should be allowed as injection tokens, this PR has relaxed typing of `Type` so that abstract class can be now used.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-07-31 14:18 UTC, JoostK commented
Instead of relaxing the constraints of `Type`, we could also introduce a new type for `Token` in general. That would avoid the cast to `Constructor` for e.g. `useClass` providers. Furthermore, providers would not be able to  incorrectly use an abstract class as value type (`useClass` or using the shortcut syntax of only the class), only as token (the `provide` property would be of type `Token`, same as `inject`'s parameter).

2018-07-31 14:26 UTC, trotyl commented
@JoostK It's only possibly to restrict it at provider-side, but not consumer-side. From consumer's perspective (`inject`), an abstract class is always valid, and cannot determine whether it's the own class or not to be used.

2018-07-31 14:38 UTC, trotyl commented
@JoostK With `providedIn` usage, the type-to-construct is determined at consumer-side, not provider-side:

```typescript
@Injectable({
  providedIn: 'root'
})
abstract class Foo { }
```

The newable or not of class `Foo` cannot be combined with `Injectable` options (extra provider or not), so there's no validation in the provider-side and consumer-side can only allow an abstract class without validation.

Then it will always be casting as `new`ing an abstract class cannot be prevented.

2018-08-07 22:48 UTC, mhevery requested changes

2018-08-07 22:48 UTC, mhevery commented on packages/core/src/application_ref.ts
> +        undefined :
What is the reasoning to change `null` to `undefined`?

2018-08-07 22:48 UTC, mhevery commented on packages/core/src/type.ts
> +export interface Type<T> extends Function { prototype: T; }
I think this is a breaking change since we are changing the meaning of `Type`. I would much rather create `AbstractType` which is than extended by `Type`

```
interface AbstractType<T> extends Function { prototype: T; }
interface Type<T> extends AbstractType<T> { new (...args: any[]): T;}
```

I think that would work better and be less breaking. Many of the changes you had to do would not need to be made. What do you think?

2018-08-08 01:37 UTC, trotyl commented on packages/core/src/application_ref.ts
> +        undefined :
https://github.com/angular/angular/blob/732026c3f56a91b016fcf79ebc581569d7c89618/packages/core/src/linker/component_factory.ts#L85-L87

`ComponentFactory#create()` accepts `NgModuleRef | undefined`, not `NgModuleRef | null`, it's a compilation error in TypeScript.

Previously `ngModule` is of `any` type so bypassed the type-checking.

2018-08-08 01:38 UTC, trotyl commented on packages/core/src/type.ts
> +export interface Type<T> extends Function { prototype: T; }
Sounds reasonable, I'll have a try.

2018-08-08 04:34 UTC, trotyl commented on packages/core/src/type.ts
> +export interface Type<T> extends Function { prototype: T; }
This is indeed less breaking, but would let `Type` being completely meaningless, every API would only use `AbstractType` rather than `Type`.

<sub>`AbstractType | Type` is just `AbstractType`.</sub>

2018-09-23 03:47 UTC, mhevery approved these changes
Created fixup for outstanding issues.

2018-09-23 03:48 UTC, mhevery commented
http://test/OCL:214144130:BASE:214144163:1537674480964:6ddc23f4

2018-09-23 05:39 UTC, mhevery commented
http://test/OCL:214144130:BASE:214148814:1537681151554:eb68748d

2018-09-23 19:30 UTC, mhevery commented
There are a lot of breaking targets in Googl3 from this PR so this seems to be a breaking change. Needs more investigation.

2018-09-24 03:00 UTC, trotyl commented
@mhevery The code `return DynamicTemplateComponent as Type<T>;` doesn't make sense, how would a non-generic concrete type be coerced to a generic type where `T` is defined in context?

2018-10-02 20:44 UTC, mhevery commented
Currently blocked on this issue: http://www.typescriptlang.org/play/#src=interface%20Type%3CT%3E%20extends%20Function%20%7B%20prototype%3A%20any%20%7D%0D%0Ainterface%20Constructor%3CT%3E%20extends%20Type%3CT%3E%20%7B%20new%20(...args%3A%20any%5B%5D)%3A%20T%3B%20%7D%0D%0Ainterface%20ComponentType%3CT%3E%20extends%20Type%3CT%3E%20%7B%20ngComponentDef%3A%20never%3B%20%7D%0D%0Ainterface%20ConcreteComponentType%3CT%3E%20extends%20Constructor%3CT%3E%20%7B%20ngComponentDef%3A%20never%3B%20%7D%0D%0A%0D%0Aclass%20Concrete%20%7B%20%7D%0D%0A%0D%0Aconst%20a%20%3D%20Concrete%20as%20ComponentType%3Cany%3E%3B%20%2F%2F%20Why%20is%20this%20error%3F%0D%0Aconst%20b%20%3D%20Concrete%20as%20ConcreteComponentType%3Cany%3E%3B%20%2F%2F%20But%20this%20is%20OK!

2018-10-02 22:04 UTC, mhevery commented
Ok, it turns out that doing it this way makes it work. I will update the PR accordingly
```
interface AbstractType<T> extends Function { prototype: T }
interface ConcreteType<T> extends Function { new (...args: any[]): T; }

type Type<T> = AbstractType<T> | ConcreteType<T>;

type ComponentType<T> =  Type<T> & { ngComponentDef: never; }

class Concrete { }

null as Type<any> as ComponentType<any>;
```

2018-10-03 04:28 UTC, trotyl commented
Simply remove the `as Constructor<any>` part and [it would work](http://www.typescriptlang.org/play/#src=interface%20Type%3CT%3E%20extends%20Function%20%7B%20prototype%3A%20T%20%7D%0D%0Ainterface%20Constructor%3CT%3E%20extends%20Type%3CT%3E%20%7B%20new%20(...args%3A%20any%5B%5D)%3A%20T%3B%20%7D%0D%0Ainterface%20ComponentType%3CT%3E%20extends%20Type%3CT%3E%20%7B%20ngComponentDef%3A%20never%3B%20%7D%0D%0Ainterface%20ConcreteComponentType%3CT%3E%20extends%20Constructor%3CT%3E%20%7B%20ngComponentDef%3A%20never%3B%20%7D%0D%0A%0D%0Aclass%20Concrete%20%7B%20%7D%0D%0A%0D%0Aconst%20a%20%3D%20Concrete%20as%20Type%3CConcrete%3E%20as%20ComponentType%3CConcrete%3E%3B%20%2F%2F%20Why%20is%20this%20error%3F%0D%0Aconst%20b%20%3D%20Concrete%20as%20ConcreteComponentType%3CConcrete%3E%3B%20%2F%2F%20But%20this%20is%20OK!%0D%0AConcrete.prototype%20as%20Type%3CConcrete%3E%3B%0D%0A%0D%0Anull%20as%20Type%3Cany%3E%20as%20ComponentType%3Cany%3E%3B).

2018-10-03 04:52 UTC, mhevery commented
http://test/OCL:214144130:BASE:215512383:1538542333897:5e488cea

2018-10-03 15:32 UTC, IgorMinar requested changes
I like this version of the PR, but I don't see any test that proves that abstract classes can actually be used as injection tokens. Can you please add one?

2018-10-03 15:39 UTC, IgorMinar commented
The PR also needs a rebase, which might uncover other compilation issues (many tests didn't run on CI). And I see that google3 has quite a few compilation failures as well.

The combination of all of these makes me more and more uncomfortable about landing this change now. If we can't make this a no/low developer pain change, we should wait with this until v8 and make a plan to roll it out.

2018-10-03 16:47 UTC, mhevery commented
Rebased and added a test.

2018-10-03 17:08 UTC, mhevery commented
# Issues:
## `injector.get()`
https://github.com/angular/angular/blob/master/packages/core/src/di/injector.ts#L66-L76

2020-11-18 00:59 UTC, AndrewKushnir commented
Hi, I'm closing this PR in favor of recently active #37958 that targets Ivy code. Thank you.

2020-11-18 00:59 UTC, closed without merging