fix(router): mount correct component if router outlet was not instantiated and if using a route reuse strategy
angular/angular pull request #25314
Opened 2018-08-05 15:50 UTC by danielwiehl

## PR Type

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
If using a custom route reuse strategy and if the router outlet was not instantiated at the time the route got activated (ie inside a NgIf), the previous activated component is mounted.

Issue Number: #25313

## What is the new behavior?
The component of the currently activated route is mounted.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
* added new Jasmine custom matcher in `platform-browser\testing\src\matchers.ts` to expect a component of a given type to show; used by spec of this PR

2018-08-23 18:18 UTC, jasonaden requested changes
Looks great overall. Just a couple comments.

2018-08-23 18:18 UTC, jasonaden commented on packages/router/test/integration.spec.ts
> +         class ToolRouteReuseStrategy implements RouteReuseStrategy {
(maybe you could just add the setting of `null` to `AttachDetachReuseStrategy` in order to support that part of your test)

2018-08-23 18:18 UTC, jasonaden commented on packages/router/test/integration.spec.ts
> +             this.subscription =
Can this just be simplified to just setting `isToolpanelShowing` to `true` on first `NavigationEnd` and then unsubscribe? Looks like you basically want it `false` to begin with, then toggle to `true` and stay `true`. Just to simplify this test.

2018-08-26 21:01 UTC, danielwiehl commented on packages/router/test/integration.spec.ts
> +         class ToolRouteReuseStrategy implements RouteReuseStrategy {
There is a little difference because `AttachDetachReuseStrategy` is very specific and caches only the route pointing to 'a'. But I wanted to have a simple cache strategy to cache any route.
Anyway, it would work with `AttachDetachReuseStrategy`. So I could rewrite the test to use that strategy, or alternatively rename 'ToolRouteReuseStrategy' to something like `SimpleRouteCacheStrategy` and move it after the other 2 strategies.
Which option do you prefer?

2018-08-26 21:10 UTC, danielwiehl commented on packages/router/test/integration.spec.ts
> +             this.subscription =
Unfortunately, that would not work because the bug only occurs if the router outlet is not instantiated at the time of the route activation.

To simulate that situation when activating 'tool-2', we first navigate to a `null` route to remove the previously mounted component from the outlet and also to remove the outlet from the DOM. That state is reflected in `isToolpanelShowing`.

```typescript
router.navigate([{outlets: {toolpanel: null}}]);
```
Then, we activate 'tool-2' as following:

```typescript
router.navigate([{outlets: {toolpanel: 'tool-2'}}]);
```

2018-08-26 21:11 UTC, danielwiehl commented on packages/router/test/integration.spec.ts
> +    it('should mount the correct component if the router outlet was not instantiated at the time the route got activated and if using a route reuse strategy',
Good point. What do you think of this? 
*should not mount the component of the previously reused route when the outlet was not instantiated at the time of route activation*

The point is that the bug occurs only if the route of the previously mounted component was reused.

2018-08-27 17:44 UTC, jasonaden commented on packages/router/test/integration.spec.ts
> +    it('should mount the correct component if the router outlet was not instantiated at the time the route got activated and if using a route reuse strategy',
Yes. That's a good description.

2018-08-27 17:47 UTC, jasonaden commented on packages/router/test/integration.spec.ts
> +         class ToolRouteReuseStrategy implements RouteReuseStrategy {
I prefer simplicity and/or re-using what's already there, so I think using `AttachDetachReuseStrategy` would be good. Having another one that's very similar means when reading the tests later, someone would have to identify the differences.

2018-08-27 17:48 UTC, jasonaden commented on packages/router/test/integration.spec.ts
> +             this.subscription =
Gotcha. Sounds good.

2018-09-10 22:03 UTC, danielwiehl commented
Forced pushed findings as requested. Thanks @jasonaden for your patience.

2018-09-11 02:39 UTC, jasonaden commented
Looks good. [Presubmit](http://test/OCL:212379981:BASE:212380014:1536633435985:62be587a)

2018-09-11 02:40 UTC, jasonaden approved these changes

2018-09-11 14:01 UTC, IgorMinar requested changes
can you please fix the matcher name? otherwise lgtm. thanks

2018-09-11 14:01 UTC, IgorMinar commented on packages/platform-browser/testing/src/matchers.ts
> +  toShow(expectedComponentType: Type<any>, expectationFailOutput?: any): boolean;
I don't think that "show" is the right name, since the actual dom can be invisible. how about "toContainComponent" ?

2018-09-11 16:33 UTC, jasonaden commented on packages/platform-browser/testing/src/matchers.ts
> +  toShow(expectedComponentType: Type<any>, expectationFailOutput?: any): boolean;
Sounds good. I fixed that.

2018-09-11 16:34 UTC, IgorMinar approved these changes

2018-09-11 23:27 UTC, closed without merging