Work in progress feat(ng-let): ng-let directive is added to store async value locally
angular/angular pull request #25351
Opened 2018-08-07 11:39 UTC by sanbornsen

- This helps to store async value locally in the template
- This fixes #15280

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2018-08-09 01:36 UTC, hiepxanh commented
that really necessary for my project

2018-08-15 09:57 UTC, sanbornsen commented
Can anyone guide me on how to fix The Travis build? No clue!

2018-08-19 15:32 UTC, ibarsi commented on packages/common/src/directives/ng_let.ts
> + * ## Storing result in a variable
It's important that these comments clearly illustrate directive usage, as they are used to generate the official Angular docs. It seems as though this section was copied from `ngIf`.

[I wrote up some documentation](https://github.com/angular/angular/pull/25472/files#diff-39dbb50aa55ff2d3e9bc8341b1206fbdR19) in my PR (#25472) that reflects (at least my) intended usage of `ngLet`, which could be merged in here as a starting point 🙂

2018-08-19 15:36 UTC, ibarsi commented on packages/common/src/directives/ng_let.ts
> +      if (this._thenTemplateRef) {
I don't believe this condition check is required, as `_ thenTemplateRef` is set in the constructor. We can rest assured that this value will always be available!

2018-08-19 15:37 UTC, ibarsi commented on packages/common/src/directives/ng_let.ts
> +        this._thenViewRef =
Does this reference need to be set? It doesn't look like it's used anywhere. We can probably get away with invoking `createEmbeddedView` directly and letting the reference pass.

2018-08-19 15:40 UTC, ibarsi commented on packages/common/src/directives/ng_let.ts
> +    if (!this._thenViewRef) {
I'm wondering what would happen if `ngLet`'s value changes once the view has already been updated? Since the view already exists at that point, would this condition fail and prevent the template from updating with the latest value?

2018-08-19 15:40 UTC, ibarsi commented on packages/common/src/directives/ng_let.ts
> +  private _thenTemplateRef: TemplateRef<NgLetContext>|null = null;
Curious, how come these properties are prefixed with `then`? Is this another copy/paste remnant from `ngIf`?

2018-08-19 15:53 UTC, ibarsi requested changes
Great work on this PR! 🎉

This looks feature complete to me, everything that's needed seems to be there. 

I would recommend updating the comments section above your `ngLet` implementation. This is key, as that content is used to automatically generate the official Angular docs.

I'd be happy to help out by contributing to your branch if you're open to it! Let me know 👍🏼

2018-08-19 15:55 UTC, ibarsi commented on packages/common/src/directives/ng_let.ts
> +    this._thenTemplateRef = templateRef;
Does `templateRef`'s reference need to be set to this other class property? `templateRef` is already accessible anywhere in the class, so you could probably get away with using it directly instead of re-setting it here 👍🏼

2018-08-20 14:20 UTC, lacolaco commented
Thank you to nice PR. Honestly, I was going to submit the same one :) 
My implementation is here. 
https://stackblitz.com/edit/ng-let-counter?file=src%2Fapp%2Fng-let.directive.ts

2018-08-29 11:55 UTC, ibarsi commented
@googlebot I'm okay with my commits being contributed to this project :)

2018-09-21 01:23 UTC, ethanj commented
might I suggest an improvement...
Allow the directive to take 1 or more variable assignments, so you do not have to create a bunch of nested ng-templates if you have multiple vars.
Not sure of exact syntax, but perhaps something like:

<ng-template *ngLet="foo1 | async as bar1" >
<ng-template *ngLet="foo1 | async as bar1 , foo2 | async as bar2">
<ng-template *ngLet="foo1 | async as bar1 , foo2 | async as bar2, ...">

or perhaps syntax based on *ngFor="let a of b; let index = index"

2018-09-21 01:33 UTC, lacolaco commented
@ethanj I can't agree with it. It will become complicated behavior if `ngLet` has multiple subscriptions in itself.

I think `foo1` and `foo2` should be combined in the component and use just one stream.

```
context$ = combineLatest(foo1, foo2, (bar1, bar2) => ({bar1, bar2});

<ng-template *ngLet="context$ | async as context">
// context.bar1 and context.bar2 are available
</ng-template>
```

2018-09-21 17:32 UTC, ethanj commented
@lacolaco While that is certainly a way to incorporate multiple subscriptions, there are several ways to do that in the component, including explicitly subscribing, which if you are willing to do that, would negate the need for ngLet to exist at all.
The point is to not have to add any code to the component at all (except injecting access in the constructor), and be able to access multiple subscriptions directly within the template in an elegant way.

"It will become complicated behavior if ngLet has multiple subscriptions in itself." - I dont agree that the behavior is complicated.. perhaps you meant that the syntax is complicated? That is why i suggested that it has a simple format which enables single vars, and only if people want multiple vars does it become slightly more complicated syntax, but syntax which is consistent with other directives, like ngFor.

2018-09-22 00:13 UTC, lacolaco commented
@ethanj I can agree with what you say, I think multiple assigning is good to simplify the template nesting.
But that I pointed out is not about syntax but internal behavior and implementation.

In the first place, `*ngLet="foo as bar` syntax is not able to apply to multiple. It depends on `NgLetContext#ngLet` property, so one directive can give only one _implicit_ `as` syntax.

`ngForOf` can have multiple `as` segments, but they're all properties defined in its _context_.

```
<ng-template *ngFor="let bar of foo1$ | async as list; index as i">
```

In the situation, `ngForOf` has a context like:

```
{
  $implicit: {{ iteration item }}
  ngForOf: {{ iterable from `foo1$ | async` }},
  index,
  odd,
  ...
}

`bar` is from `$implicit` and `list` is from `ngForOf`. They'are different context values.

Then, look at `ngLet`;

```
<ng-template *ngLet="foo1$ | async as bar1; foo2$ | async as bar2">
```

So I think this syntax is impossible in _current_ Angular. 

And I concern the rendering performance. To update that template, there're 2 patterns;

1. `foo1$` emits new value.
1. `foo2$` emits new value.

But what will happen in the below case?

```
export class Cmp {
  someFn() {
    this.foo1$.next("updated");
    this.foo2$.next("updated");;
  }
}
```

When `foo1$` and `foo2$` are updated at the same time, but because they're async, change detection and re-rendering may be triggered twice.
It probably can be handled as a single change, but it's _blackbox_ in Angular implementation. 
Unit testing and performance validation for that are not simple. And I want Angular not to create any more _beginner's pitfalls_.

2018-09-24 02:13 UTC, ethanj commented
@lacolaco Ah.. it was not clear that you were saying the implementation would be the roadblock. Thanks for the extended description of the issue.

"When foo1$ and foo2$ are updated at the same time, but because they're async, change detection and re-rendering may be triggered twice." - wouldn't this be identical to having 2 ngLet async's in nested ng-templates? I was not thinking this proposal would somehow improve performance by combining multiple async vars into a single rendering pass. It would not be appropriate, unless explicitly coded, to "hold up" rendering until multiple async vars became ripe. I really just think of this proposal as syntactic sugar.

In any case, if implementing this functionality is either too hard or theoretically impossible, then I guess its a no go.

2018-09-27 22:07 UTC, ethanj commented
@lacolaco i found this existing implementation which accomplishes the goal of doing everything in-template, albeit with a working but unorthodox methodology in the case of multiple vars. In fact perhaps that syntax works with your current version? If not, you might want to connect up with them and see if you can converge on a superior version to add to core angular.

[ngrx-utils](https://github.com/ngrx-utils/ngrx-utils)

```
<ng-container *ngLet="(filterDate$ | async) as filterDate">
<ng-container *ngLet="{
        device: device$ | async,
        date: filterDate$ | async
      } as options">
```

2018-10-17 02:58 UTC, IgorMinar commented on packages/common/src/directives/ng_let.ts
> + * - `<div *ngLet="condition as value">{{value}}</div>`
I think you mean `*ngLet="expression as identifier"`

2018-10-17 02:58 UTC, IgorMinar commented on packages/common/src/directives/ng_let.ts
> + * - `<ng-template [ngLet]="condition as value"><div>{{value}}</div></ng-template>`
same as above

2018-10-17 03:17 UTC, IgorMinar reviewed
I'm not too keen on creating new embedded views for each variable declaration. This will become a performance issue once you start declaring multiple variables within a single template and especially if you place them into an ngFor.

I think we should find a way to support this in a similar way as we support `#myVar` declarations in the template. Something along the lines of `#[myVar]="someExpression"`.

2018-10-17 03:45 UTC, IgorMinar commented
I've posted more about this on https://github.com/angular/angular/issues/15280#issuecomment-430479166. The implementation in this PR can't be accepted as it would (eventually) result in perf issues. Thanks for exploring this problem space. Your work will inform future implementations.

2018-10-17 03:45 UTC, closed without merging