build(docs-infra): package entry points API templates
angular/angular pull request #25453
Opened 2018-08-13 09:58 UTC by petebacondarwin

2018-08-13 10:10 UTC, mary-poppins commented
You can preview 16e2f1a at https://pr25453-16e2f1a.ngbuilds.io/.

2018-08-13 11:31 UTC, petebacondarwin commented
You can see a class inside a secondary entry point, which is inside a package here: https://pr25453-16e2f1a.ngbuilds.io/api/animations/browser/AnimationDriver

2018-08-13 11:33 UTC, petebacondarwin commented
Here are some screenshots:

![screen shot 2018-08-13 at 12 32 22](https://user-images.githubusercontent.com/15655/44029368-ffc45432-9ef4-11e8-9815-81fb09207a79.png)
<img width="877" alt="screen shot 2018-08-13 at 12 32 00" src="https://user-images.githubusercontent.com/15655/44029369-ffdd83b2-9ef4-11e8-925c-138570eec69e.png">
<img width="466" alt="screen shot 2018-08-13 at 12 31 47" src="https://user-images.githubusercontent.com/15655/44029370-fff82514-9ef4-11e8-849c-4eb7ca80fb97.png">

2018-08-13 14:49 UTC, jbogarthyde commented
LGTM

2018-08-13 21:04 UTC, IgorMinar requested changes

2018-08-13 21:04 UTC, IgorMinar commented on packages/animations/PACKAGE.md
> +@experimental
Pete, did you miss the discussion where we agreed that these tags are meaningless because users don't really see them and as of now, all apis regardless of the experimental label are considered stable and can't be broken without a deprecation/update plan.

Can you please remove this tag and also remove the support for displaying these tags in the templates you touched here. Thanks!

2018-08-13 21:04 UTC, IgorMinar commented on aio/tools/transforms/templates/api/package.template.html
> -  {$ listItems([doc.packageInfo.primary], 'Primary') $}
It would also be awesome if we could make the primary entry point table entry (e.g. `@angular/animations`) a link to the `Primary Entry Point Exports` rather than link back to the package, which will confuse people.

2018-08-13 21:08 UTC, petebacondarwin commented on aio/tools/transforms/templates/api/package.template.html
> -  {$ listItems([doc.packageInfo.primary], 'Primary') $}
I'll make that happen

2018-08-13 21:08 UTC, petebacondarwin commented on packages/animations/PACKAGE.md
> +@experimental
OK - I did miss that

2018-08-13 21:28 UTC, petebacondarwin commented
@IgorMinar - done PTAL

2018-08-13 21:37 UTC, mary-poppins commented
You can preview e588bf9 at https://pr25453-e588bf9.ngbuilds.io/.

2018-08-14 03:54 UTC, IgorMinar approved these changes
yup. looks good to me now! thanks

2018-08-14 20:18 UTC, closed without merging