feat(common): Implemented ng-let directive.
angular/angular pull request #25472
Opened 2018-08-14 01:33 UTC by ibarsi

`ngLet` exposes the result of an expression that is stored as a variable to its child view.

Fixes #15280

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #15280

## What is the new behavior?

`ngLet` has been implemented to support exposure of the result of an expression to its child view, without conditional rendering.

```html
<div *ngLet="condition as value">{{value}}</div>
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

N/A

2018-08-20 11:51 UTC, sebek64 commented
This feature is tightly related to https://github.com/angular/angular/pull/25251, which is in some sense more general, but maybe a bit less readable. For me (as the author of the other pull request), both solutions are quite fine. The fact that these pull requests emerge indicates that this is a real deficiency that should be addressed somehow, by merging either one (or by proposing a completely different solution).

2018-08-20 12:59 UTC, sandangel requested changes
I think you should add more tests for some use case like nested *ngLet, usage with `async` pipe...

2018-08-20 12:59 UTC, sandangel commented on packages/common/src/directives/ng_let.ts
> +  set ngLet(condition: any) {
should we name it condition?
we can absolutely use something like `*ngLet="data$ | async as data"` here.

2018-08-20 12:59 UTC, sandangel commented on packages/common/src/directives/ng_let.ts
> +    this._viewContainer.createEmbeddedView(this._templateRef, this._context);
why you put it here? Is that mean we will createEmbeddedView everytime input change?

I think we just need to `createEmbeddedView` once in the `ngOnInit` hook and only changes the value of property in the context object when `Input` changes.
```ts
  @Input()
  set ngLet(value: any) {
    this._context.$implicit = this._context.ngLet = value;
  }

  constructor(private _vcr: ViewContainerRef, private _templateRef: TemplateRef<NgLetContext>) {}

  ngOnInit() {
    this._vcr.createEmbeddedView(this._templateRef, this._context);
  }
```

2018-08-20 13:02 UTC, sandangel commented on packages/common/test/directives/ng_let.spec.ts
> +         const template = '<span *ngLet="booleanCondition let v">{{v}}</span>';
Correct me if I'm wrong but I think the syntax should be `*ngLet="booleanCondition; let v"`

2018-08-21 01:30 UTC, ibarsi commented on packages/common/src/directives/ng_let.ts
> +  set ngLet(condition: any) {
Absolutely! It's not expected to be a "condition" at all. Thanks for pointing that out. Maybe `value` or `data` is more appropriate?

2018-08-21 01:32 UTC, ibarsi commented on packages/common/src/directives/ng_let.ts
> +    this._viewContainer.createEmbeddedView(this._templateRef, this._context);
This is an excellent point... I didn't even consider that updating `context` on input changes would be enough 🤔

This makes a lot of sense, will update 👍🏼

2018-08-21 02:48 UTC, ibarsi commented on packages/common/test/directives/ng_let.spec.ts
> +         const template = '<span *ngLet="booleanCondition let v">{{v}}</span>';
It's good either way, the semicolon isn't required 🙂

2018-08-21 03:54 UTC, sandangel commented
Hi, I think you should have a look at [`*ngIf` directive test cases](https://github.com/angular/angular/blob/master/packages/common/test/directives/ng_if_spec.ts). some tests I think you should have are binding in `ng-template`, nested `*ngLet`, update multiple nodes...

2018-08-21 07:56 UTC, jotatoledo commented on packages/common/test/directives/ng_let.spec.ts
> +    it('should support binding to observable using as', async(() => {
Dont use `EventEmitter` for the purpose of an `Observable` instance. Use a Subject or similar.

2018-10-17 03:45 UTC, IgorMinar commented
hi there. thanks for the PR. I've posted on https://github.com/angular/angular/issues/15280#issuecomment-430479166 about how we should go about implementing this feature. The implementation in this PR can't be accepted as it would (eventually) result in perf issues. Thanks for exploring this problem space. Your work will inform future implementations.

2018-10-17 03:45 UTC, closed without merging