fix(router): validate lazy-loaded routes and allow canActivate routes
angular/angular pull request #25498
Opened 2018-08-15 10:28 UTC by dirkluijk

Closes #25431.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
```

## What is the current behavior?
Routes in lazy-loaded modules are not validated, opposed to "normal" routes. Also, routes with just "path" and "canActivate" are not allowed, which means you _have_ to provide a component (e.g. dummy), even when the guard _always_ performs a redirect action.

Issue Number: https://github.com/angular/angular/issues/25431#issuecomment-413039007

## What is the new behavior?
With this PR, lazy-loaded route configuration is validated as well (when they are loaded). Also, component-less routes with CanActivate guards are now allowed.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No (validation is less strict so it won't break anything)
```

2018-08-31 20:43 UTC, dirkluijk commented
Alternative solution: https://github.com/angular/angular/issues/25773.

2018-09-04 23:16 UTC, jasonaden commented
@dirkluijk Thanks for this PR. Overall it seems good. However, we need to have some new tests validating the functionality you're adding. While yes, it's now less restrictive, we also need to make sure a route with only `canActivate` will behave as expected. This is under the assumption there was a reason it wasn't included when originally written, so let's at least add a test that validates it works as expected.

Also, we'll likely merge this for `v7` rather than a patch since it's possible to introduce a breaking change. We're now doing validation on configurations as they are lazy loaded. While invalid configurations likely didn't work in the past, they would silently fail. It's possible someone would have child configs that previously wouldn't cause an error at runtime if never activated, but were technically invalid so will throw an error after this PR.

2018-09-05 21:09 UTC, dirkluijk commented
@jasonaden Yes, you are right. It will actually break invalid configurations in lazy-loaded modules that were accidentally allowed before. So it is breaking in that perspective.

What kind of tests should be added? Then I will add some.

2018-09-06 05:03 UTC, jasonaden commented
@dirkluijk After this PR a config with `canActivate` will be valid with no other properties in the config. You provided the test for the validator function itself which is great. But we need a test where a config that previously would have failed validation is now valid and results in successful navigation. Basically we need to make sure that when people use this new feature it won't break.

I would suggest adding it to [regression_integration.spec.ts](https://github.com/angular/angular/blob/master/packages/router/test/regression_integration.spec.ts) where you can reference the PR number of this change.

Let me know if that makes sense or if you need more info.

2020-08-05 22:22 UTC, atscott commented
Hi @dirkluijk, could you split this into two separate PRs - one which allows `canActivate` routes and one that validates the config for lazy loaded modules? When you create the `canActivate` PR, please also mark it as resolving #18605 and #13373 and add a test as @jasonaden mentioned in https://github.com/angular/angular/pull/25498#issuecomment-418965571

Then for this PR, because it's a breaking change as described in https://github.com/angular/angular/pull/25498#issuecomment-418882342, I think this would need to be an opt-in validation. Please add it as an option in the `ExtraOptions`, something like `validateLazyLoadedConfigs` with a default value of `false`.

2020-08-10 15:29 UTC, atscott requested changes
Setting review state to "request changes" per https://github.com/angular/angular/pull/25498#issuecomment-669551468

2020-12-04 18:49 UTC, atscott commented
Closing this PR due to lack of activity. If you still want to make this contribution, please open a new PR and I'd be happy to review it. Thanks!

2020-12-04 18:49 UTC, closed without merging