docs: rewrite binding-syntax section in template-syntax.md
angular/angular pull request #25561
Opened 2018-08-18 17:21 UTC by kapunahelewong

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Current section uses hero examples. 

Issue Number: 
Closes #18665

## What is the new behavior?
Rewrite of Binding Section updates prose and introduces an example specific to Binding Syntax that demos the two examples that are currently explained in that section. It also moves away from heroes.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

This is part 2 of the Template Syntax rewrite. The intention is that each part be rewritten with relevant, separate examples. When the entire Template Syntax document is complete, these will be broken out into their own standalone docs.

2018-08-20 04:54 UTC, brandonroberts requested changes

2018-08-20 04:54 UTC, brandonroberts commented on aio/content/examples/binding-syntax/e2e/src/app.e2e-spec.ts
> +    const logs = await browser.manage().logs().get(logging.Type.BROWSER);
The process of getting the browser logs and check what string you're searching for should be moved into a helper function since you're using it multiple times.

2018-08-20 04:54 UTC, brandonroberts commented on aio/content/examples/binding-syntax/example-config.json
> +{
This file should be empty since you don't need any custom configuration.

2018-08-20 04:54 UTC, brandonroberts commented on aio/content/examples/binding-syntax/src/app/app.component.ts
> +    let inputVal = document.getElementById("bindingInput").getAttribute("value");
We should be using `ViewChild` with a template reference here instead of accessing the DOM directly to read attributes and properties.

2018-08-20 04:54 UTC, brandonroberts commented on aio/content/examples/binding-syntax/src/app/app.component.ts
> +    testButton.disabled == false ? testButton.disabled = true : testButton.disabled = false;
This can be shortened to toggle the boolean: `testButton.disabled = !testButton.disabled;`

2018-08-20 15:55 UTC, kapunahelewong commented on aio/content/examples/binding-syntax/e2e/src/app.e2e-spec.ts
> +    const logs = await browser.manage().logs().get(logging.Type.BROWSER);
fixed.

2018-08-20 15:55 UTC, kapunahelewong commented on aio/content/examples/binding-syntax/example-config.json
> +{
fixed.

2018-08-20 15:58 UTC, kapunahelewong commented on aio/content/examples/binding-syntax/src/app/app.component.ts
> +    testButton.disabled == false ? testButton.disabled = true : testButton.disabled = false;
fixed.

2018-08-20 18:56 UTC, kapunahelewong commented on aio/content/examples/binding-syntax/src/app/app.component.ts
> +    let inputVal = document.getElementById("bindingInput").getAttribute("value");
Got it and updated. Thanks!

2018-09-07 16:03 UTC, mary-poppins commented
You can preview 191194b at https://pr25561-191194b.ngbuilds.io/.

2018-09-20 16:41 UTC, mary-poppins commented
You can preview 521c71f at https://pr25561-521c71f.ngbuilds.io/.

2018-09-20 17:57 UTC, mary-poppins commented
You can preview 1bffd60 at https://pr25561-1bffd60.ngbuilds.io/.

2018-09-28 17:06 UTC, mary-poppins commented
You can preview 8648f10 at https://pr25561-8648f10.ngbuilds.io/.

2018-10-03 17:18 UTC, mary-poppins commented
You can preview 0bd3c2c at https://pr25561-0bd3c2c.ngbuilds.io/.

2018-11-13 17:09 UTC, mary-poppins commented
You can preview c5213a9 at https://pr25561-c5213a9.ngbuilds.io/.

2018-11-27 19:09 UTC, mary-poppins commented
You can preview 0823229 at https://pr25561-0823229.ngbuilds.io/.

2018-11-27 19:18 UTC, mary-poppins commented
You can preview d5235d7 at https://pr25561-d5235d7.ngbuilds.io/.

2018-11-30 18:13 UTC, mary-poppins commented
You can preview 2dc35b4 at https://pr25561-2dc35b4.ngbuilds.io/.

2018-12-03 16:50 UTC, mary-poppins commented
You can preview 6ee0bcc at https://pr25561-6ee0bcc.ngbuilds.io/.

2019-01-15 20:06 UTC, mary-poppins commented
You can preview 128ee9f at https://pr25561-128ee9f.ngbuilds.io/.

2019-01-17 00:53 UTC, mary-poppins commented
You can preview 7d5664e at https://pr25561-7d5664e.ngbuilds.io/.

2019-01-17 18:47 UTC, mary-poppins commented
You can preview 555e666 at https://pr25561-555e666.ngbuilds.io/.

2019-03-13 15:00 UTC, mary-poppins commented
You can preview 8c21d00 at https://pr25561-8c21d00.ngbuilds.io/.

2019-03-22 19:01 UTC, mary-poppins commented
You can preview 191194b at https://pr25561-191194b.ngbuilds.io/.
You can preview 521c71f at https://pr25561-521c71f.ngbuilds.io/.
You can preview 1bffd60 at https://pr25561-1bffd60.ngbuilds.io/.
You can preview 8648f10 at https://pr25561-8648f10.ngbuilds.io/.
You can preview 0bd3c2c at https://pr25561-0bd3c2c.ngbuilds.io/.
You can preview bce7244 at https://pr25561-bce7244.ngbuilds.io/.
You can preview c5213a9 at https://pr25561-c5213a9.ngbuilds.io/.
You can preview 0823229 at https://pr25561-0823229.ngbuilds.io/.
You can preview d5235d7 at https://pr25561-d5235d7.ngbuilds.io/.
You can preview 2dc35b4 at https://pr25561-2dc35b4.ngbuilds.io/.
You can preview 6ee0bcc at https://pr25561-6ee0bcc.ngbuilds.io/.
You can preview 128ee9f at https://pr25561-128ee9f.ngbuilds.io/.
You can preview 7d5664e at https://pr25561-7d5664e.ngbuilds.io/.
You can preview 555e666 at https://pr25561-555e666.ngbuilds.io/.
You can preview 47ef49c at https://pr25561-47ef49c.ngbuilds.io/.
You can preview 8c21d00 at https://pr25561-8c21d00.ngbuilds.io/.

2019-03-22 19:01 UTC, mary-poppins commented
You can preview c6c7960 at https://pr25561-c6c7960.ngbuilds.io/.

2019-03-25 20:20 UTC, mary-poppins commented
You can preview 6faa6b7 at https://pr25561-6faa6b7.ngbuilds.io/.

2019-04-14 15:04 UTC, trotyl commented on aio/content/guide/template-syntax.md
> +Property values can change; attribute values can't.**
Attributes can be changed by [`setAttribute()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute), which will re-initialize corresponding DOM properties again.

2019-04-14 15:04 UTC, trotyl commented on aio/content/guide/template-syntax.md
> +rather than the attribute, which is what you do when you use Angular to bind
This is not true, when binding the attribute with `null` value, Angular will call `removeAttribute` (rather than setting an empty string), which results same behavior as changing the property:

https://github.com/angular/angular/blob/da2880d7c495022405102f89b8c641b23516388d/packages/core/src/view/refs.ts#L440-L443

2019-05-23 17:44 UTC, mary-poppins commented
You can preview 54af4a3 at https://pr25561-54af4a3.ngbuilds.io/.

2019-05-28 19:29 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +or preceded by a prefix; `bind-`, `on-`, `bindon-`.
fixed! :)

2019-05-28 19:41 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +Data binding is a mechanism for coordinating what users see, specifically
Added. Good spot.

2019-05-28 19:53 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +Binding types other than interpolation have a **target name** to the left of the equal sign, either surrounded by punctuation, `[]` or `()`,
Ah yes, @trotyl, I definitely want to stay consistent. Would you have a recommendation on how I could say it better? Maybe linking to the interpolation section or defining it?

2019-05-28 19:58 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +Every member of a **source** directive is automatically available for binding.
Got it!

2019-05-29 06:12 UTC, trotyl commented on aio/content/guide/template-syntax.md
> +Binding types other than interpolation have a **target name** to the left of the equal sign, either surrounded by punctuation, `[]` or `()`,
Sorry I wasn't aware there's a **Type** column, look good to me now. But from the linguistic order of **Binding types can be grouped into three categories**, I'll prefer **Binding types** (subject) to be the first column.

2019-05-29 17:34 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +Binding types other than interpolation have a **target name** to the left of the equal sign, either surrounded by punctuation, `[]` or `()`,
Ah, I see your point. If I change to "Binding types" (which is a good idea), then there's "Type" in the third column, which seems repetitive. Do you think there might be another way to title the third column that would vary the wording? Maybe "Examples"?

![image](https://user-images.githubusercontent.com/4116963/58578170-226d7180-8216-11e9-91be-82a111403caa.png)

2019-05-29 17:47 UTC, trotyl commented on aio/content/guide/template-syntax.md
> +Binding types other than interpolation have a **target name** to the left of the equal sign, either surrounded by punctuation, `[]` or `()`,
Sorry for the confusion, I mean is it might be better to swapping the column order, like:

Type|Syntax|Category
---|---|---
Interpolation|`{{expression}}`|One-way (multi-line-cell)
Property|`[target]="expression"`| -
...|...|...

"Category" looks fine for me, previous I was confused by "Category" with "Type"... 😄

2019-05-29 18:44 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +The *source* is either inside quotes (`" "`) or within an interpolation (`{{}}`).
Fixed. :)

2019-05-29 18:48 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +* Some HTML attributes don't have corresponding properties; for example, `aria`.
ah, yes, good point. Fixed.

2019-05-29 18:48 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +The distinction between an HTML attribute and a DOM property is key to understanding how Angular binding works. **Attributes are defined by HTML. Properties are defined by the DOM, or the Document Ob
Fixed.

2019-05-29 19:10 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +Binding types other than interpolation have a **target name** to the left of the equal sign, either surrounded by punctuation, `[]` or `()`,
I see. Ok, fixed (and I managed to not break the table! 😅). Thank you :)

2019-05-29 19:32 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +Property values can change; attribute values can't.**
😅You're right! I've put in a note based on your comment. I think the general guideline is helpful for beginners, but knowing that there is indeed an exception to this rule is good too!

2019-05-29 19:49 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +rather than the attribute, which is what you do when you use Angular to bind
Ah, this is really helpful @trotyl. So would it make more sense to say:

> To control the state of the button, set the `disabled` *property*.
or 
> To control the state of the button, set the `disabled` *property* rather than the attribute.

The part after "which" is unclear anyway.

2019-05-29 19:59 UTC, mary-poppins commented
You can preview 0074379 at https://pr25561-0074379.ngbuilds.io/.

2019-05-30 03:03 UTC, trotyl commented on aio/content/guide/template-syntax.md
> +rather than the attribute, which is what you do when you use Angular to bind
@kapunahelewong Both `[disabled]` property binding and `[attr.disabled]` attribute binding could control the `disabled` state, but the values used are different. The property binding works by the truthyness, while in attribute binding is about nullness:

```html
<input [disabled]="condition ? true : false">
<input [attr.disabled]="condition ? 'anything' : null">
```

Generally property binding is the preferred way.

2019-05-30 19:59 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +rather than the attribute, which is what you do when you use Angular to bind
ohhhh. @trotyl Your comments are so helpful! 

So should I say:

> To control the state of the button, set the disabled property. 

> Note: Though you could technically set the `[attr.disabled]` attribute binding, the values are different in that property binding works by truthiness, while attribute binding relies on whether the value is `null` or not. Consider the following:

```
<input [disabled]="condition ? true : false">
<input [attr.disabled]="condition ? 'anything' : null">
```

> Generally, use property binding as attribute bindings that resolve to `null` are removed from the DOM.

What do you think?

2019-05-31 15:36 UTC, trotyl commented on aio/content/guide/template-syntax.md
> +rather than the attribute, which is what you do when you use Angular to bind
> in that property binding works by truthiness, while attribute binding relies on whether the value is `null` or not.

Better to make it clear this is only about **boolean attribute**, not a general binding behavior.

> use property binding as attribute bindings that resolve to null are removed from the DOM.

I don't see it a good explanation, I believe the main reason here is property binding is more intuitive (boolean value used) and shorter in syntax (no prefix), also a bit more performant in VM.

> `[attr.disabled]="condition ? 'anything' : null"`

The value `anything` isn't good for real documentation (my bad), which technically violates the [HTML spec](https://html.spec.whatwg.org/#boolean-attributes) in:

> If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

So the right way is `[attr.disabled]="condition ? 'disabled' : null"`. Although `[attr.disabled]="condition ? '' : null"` is also correct, but due to both ` ` (empty string) and `null` are falsy values, that would be super confusing.

2019-06-03 18:33 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +rather than the attribute, which is what you do when you use Angular to bind
Ah, thanks for the clarification @trotyl. How about this:

> To control the state of the button, set the disabled property.

> Note: Though you could technically set the [attr.disabled] attribute binding, the values are different in that property binding evaluates to a boolean value, while attribute binding relies on whether the value is `null` or not. Consider the following:
```
<input [disabled]="condition ? true : false">
<input [attr.disabled]="condition ? 'disabled' : null">
```
>Generally, use property binding over attribute binding as it is more intuitive (being a boolean value), has a shorter syntax, and is more performant.

2019-06-03 18:49 UTC, mary-poppins commented
You can preview 87e9601 at https://pr25561-87e9601.ngbuilds.io/.

2019-06-04 04:26 UTC, trotyl commented on aio/content/guide/template-syntax.md
> +rather than the attribute, which is what you do when you use Angular to bind
I'd suggest:

> in that **the** property binding **requires** a boolean value, while **its corresponding** attribute binding relies on whether the value is `null` or not.

2019-06-04 11:51 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +rather than the attribute, which is what you do when you use Angular to bind
Ah, got it! Thank you for your patience as I learn my way through! :)

2019-06-04 11:59 UTC, mary-poppins commented
You can preview 7f03ac1 at https://pr25561-7f03ac1.ngbuilds.io/.

2019-06-04 13:20 UTC, mary-poppins commented
You can preview 08e300b at https://pr25561-08e300b.ngbuilds.io/.

2019-06-04 13:37 UTC, mary-poppins commented
You can preview 699ed87 at https://pr25561-699ed87.ngbuilds.io/.

2019-06-04 14:24 UTC, mary-poppins commented
You can preview 95e56a1 at https://pr25561-95e56a1.ngbuilds.io/.

2019-06-04 15:00 UTC, mary-poppins commented
You can preview eeb85ab at https://pr25561-eeb85ab.ngbuilds.io/.

2019-06-07 16:35 UTC, mary-poppins commented
You can preview 4188424 at https://pr25561-4188424.ngbuilds.io/.

2019-06-08 07:29 UTC, trotyl commented on aio/content/guide/template-syntax.md
> +The distinction between an HTML attribute and a DOM property is key to understanding how Angular binding works. **Attributes are defined by HTML. Properties are defined by the DOM, or the Document Ob
Sorry for not being clear enough about this, DOM is a platform-agnostic and language-agnostic API layer, it only defines the relationship of the Nodes in a document, but doesn't cover the property shape of any specific Node type.

In short:

+ The DOM properties of HTML elements are defined by HTML;
+ The DOM properties of SVG elements are defined by SVG;
+ The DOM properties of MathML elements are defined by MathML;

No DOM properties are defined by DOM as it's only the abstraction layer.

2019-06-08 12:39 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +The distinction between an HTML attribute and a DOM property is key to understanding how Angular binding works. **Attributes are defined by HTML. Properties are defined by the DOM, or the Document Ob
This is great. Per offline conversation with @trotyl, reworded as: 

>Attributes are defined by HTML. Properties are accessed from DOM, or the Document Object Model, nodes.

His explanation here is also very helpful and I will be looking for a place to incorporate this differentiation going forward in the Template Syntax restructure. Thank you, @trotyl 🤗

2019-06-08 12:45 UTC, mary-poppins commented
You can preview fcd7f94 at https://pr25561-fcd7f94.ngbuilds.io/.

2019-06-13 16:21 UTC, mary-poppins commented
You can preview bad0ca6 at https://pr25561-bad0ca6.ngbuilds.io/.

2019-06-13 17:12 UTC, brandonroberts approved these changes

2019-06-13 18:25 UTC, mary-poppins commented
You can preview 959e8b5 at https://pr25561-959e8b5.ngbuilds.io/.

2019-06-13 19:17 UTC, mary-poppins commented
You can preview 0f19f8d at https://pr25561-0f19f8d.ngbuilds.io/.

2019-06-14 17:27 UTC, closed without merging