build(bazel): fix bazel types reference directive resolves
angular/angular pull request #25581
Opened 2018-08-20 20:00 UTC by gregmagolan

Depends on https://github.com/angular/angular/pull/25490 && https://github.com/bazelbuild/rules_typescript/pull/259.

Build will fail with tsickle diagnostics until https://github.com/angular/angular/pull/25490 lands and this is rebased.

Will need to updated to tagged rules_typescript release after https://github.com/bazelbuild/rules_typescript/pull/259 lands.

2018-08-20 20:00 UTC, gregmagolan commented
Resolves https://github.com/angular/angular/issues/25051

2018-08-20 20:08 UTC, mary-poppins commented
You can preview 287662c at https://pr25581-287662c.ngbuilds.io/.

2018-08-22 23:59 UTC, mary-poppins commented
You can preview b7e7e8a at https://pr25581-b7e7e8a.ngbuilds.io/.

2018-08-23 00:00 UTC, mary-poppins commented
You can preview 6c33165 at https://pr25581-6c33165.ngbuilds.io/.

2018-08-23 06:05 UTC, alfaproject commented on packages/compiler-cli/src/transformers/compiler_host.ts
> +  resolveTypeReferenceDirectives !: (names: string[], containingFile: string) => (ts.ResolvedTypeReferenceDirective | undefined)[];
`!` -> `|undefined` since it's not always defined, so that would be the correct type.
`!` means that it's always defined which is wrong, currently.

2018-08-23 22:47 UTC, mary-poppins commented
You can preview 51a5d2b at https://pr25581-51a5d2b.ngbuilds.io/.

2018-08-24 03:36 UTC, mary-poppins commented
You can preview 01acbd0 at https://pr25581-01acbd0.ngbuilds.io/.

2018-08-24 06:21 UTC, alfaproject requested changes

2018-08-27 17:44 UTC, gregmagolan commented on packages/compiler-cli/src/transformers/compiler_host.ts
> +  resolveTypeReferenceDirectives !: (names: string[], containingFile: string) =>
good catch. thanks. I updated it to
```
  resolveTypeReferenceDirectives?: (names: string[], containingFile: string) =>
      (ts.ResolvedTypeReferenceDirective | undefined)[];
```
to match the `ts.CompilerHost` base class definition

2018-08-27 18:10 UTC, mary-poppins commented
You can preview 8028fd4 at https://pr25581-8028fd4.ngbuilds.io/.

2018-08-27 18:27 UTC, mary-poppins commented
You can preview 69d78d1 at https://pr25581-69d78d1.ngbuilds.io/.

2018-08-27 21:30 UTC, mary-poppins commented
You can preview 206e094 at https://pr25581-206e094.ngbuilds.io/.

2018-08-27 23:08 UTC, mary-poppins commented
You can preview a623188 at https://pr25581-a623188.ngbuilds.io/.

2018-08-28 15:00 UTC, alexeagle approved these changes

2018-08-28 15:00 UTC, alexeagle commented on WORKSPACE
> +    sha256 = "240e44169a071de27f207222c0ed9637e4b02c4521014f45115222cda1cabc8c",
released 0.16.2 so you don't need to depend on a commit hash

2018-08-28 15:00 UTC, alexeagle commented on integration/bazel/package.json
> +    "@bazel/typescript": "https://github.com/bazelbuild/rules_typescript/archive/c7766689fbb0597c36e34a8c8284a62ab680b69c.tar.gz",
same

2018-08-28 15:28 UTC, gregmagolan commented on WORKSPACE
> +    sha256 = "240e44169a071de27f207222c0ed9637e4b02c4521014f45115222cda1cabc8c",
Sweet. I was just thinking that as the min working version needs be updated as well as this is a breaking change downstream.

2018-08-28 15:29 UTC, gregmagolan commented on .circleci/config.yml
> +var_2: &cache_key v2-angular-{{ .Branch }}-{{ checksum "yarn.lock" }}-bust1-0.4.0
yes. removing the patch-types means the node_modules cache needs invalidating even with the lock file not changing

2018-08-28 16:01 UTC, mary-poppins commented
You can preview 2a2cbde at https://pr25581-2a2cbde.ngbuilds.io/.

2018-08-28 16:18 UTC, gregmagolan commented on WORKSPACE
> +    sha256 = "240e44169a071de27f207222c0ed9637e4b02c4521014f45115222cda1cabc8c",
done

2018-08-28 16:18 UTC, gregmagolan commented on integration/bazel/package.json
> +    "@bazel/typescript": "https://github.com/bazelbuild/rules_typescript/archive/c7766689fbb0597c36e34a8c8284a62ab680b69c.tar.gz",
done

2018-08-28 17:41 UTC, mary-poppins commented
You can preview edc864c at https://pr25581-edc864c.ngbuilds.io/.

2018-08-28 18:19 UTC, mary-poppins commented
You can preview 3ca1cf7 at https://pr25581-3ca1cf7.ngbuilds.io/.

2018-08-28 20:27 UTC, IgorMinar commented
ci still fails with a typecheck error

2018-08-28 20:44 UTC, mary-poppins commented
You can preview aa1d813 at https://pr25581-aa1d813.ngbuilds.io/.

2018-08-28 21:56 UTC, IgorMinar approved these changes

2018-08-29 16:37 UTC, gregmagolan commented
Blocked from going green by an issue with the angular github robot: https://github.com/angular/github-robot/issues/20. Please merge.

2018-08-29 20:34 UTC, alfaproject approved these changes

2018-08-31 18:15 UTC, closed without merging