TSLint: Identifier 'i' is never reassigned; use 'const' instead of 'let'. (prefer-const)
angular/angular pull request #25629
Opened 2018-08-23 09:06 UTC by jestersimpps

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

change let to const in locale files to avoid linting errors

```
[ ] Bugfix
[ ] Feature
[x ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

## Other information

2018-08-23 09:11 UTC, jestersimpps commented
I signed it!

2018-08-23 13:01 UTC, alfaproject requested changes

2018-08-23 13:01 UTC, alfaproject commented on packages/common/locales/fr-BE.ts
> +  const i = Math.floor(Math.abs(n));
Read line 9

2018-08-23 13:01 UTC, alfaproject commented on packages/common/locales/nl-BE.ts
> +  const i = Math.floor(Math.abs(n)), v = n.toString().replace(/^[^.]*\.?/, '').length;
Read line 9

2018-08-23 13:04 UTC, trotyl commented
Please respect:

> `// THIS CODE IS GENERATED - DO NOT MODIFY`
> `// See angular/tools/gulp-tasks/cldr/extract.js`

2018-08-24 07:39 UTC, jestersimpps commented on packages/common/locales/fr-BE.ts
> +  const i = Math.floor(Math.abs(n));
oops

2018-08-24 07:39 UTC, closed without merging