docs: Clarification of hero selection in section Routing
angular/angular pull request #25634
Opened 2018-08-23 11:01 UTC by FrederikSchlemmer

Better explanations in the Tour of Heroes in the section Routing. The title "Top Heroes" was misleading because of the limited selection of four Top Heroes.

Fixes #25212

2018-08-24 15:05 UTC, mary-poppins commented
You can preview 2dd03b0 at https://pr25634-2dd03b0.ngbuilds.io/.

2018-08-27 13:05 UTC, brandonroberts requested changes

2018-08-27 13:05 UTC, brandonroberts commented on aio/content/examples/toh-pt5/src/app/dashboard/dashboard.component.1.html
> +<h3>Four of the Top Heroes</h3>
I think the title can remain the same because you've updated the text to be more clear below.

2018-08-27 13:06 UTC, brandonroberts commented
@FrederikSchlemmer will you also update the commit message to `docs: clarification of hero selection in routing section`

2018-08-28 04:34 UTC, FrederikSchlemmer commented on aio/content/examples/toh-pt5/src/app/dashboard/dashboard.component.1.html
> +<h3>Four of the Top Heroes</h3>
I think leaving the title unchanged also makes sense, because otherwise the overview at the beginning would no longer match the finished application.

2018-08-28 04:44 UTC, mary-poppins commented
You can preview 95534cc at https://pr25634-95534cc.ngbuilds.io/.

2018-08-28 04:53 UTC, FrederikSchlemmer commented
@brandonroberts Thank you for your feedback. I have applied the suggestions and updated the commit message.

2018-08-28 18:36 UTC, brandonroberts approved these changes

2018-08-29 02:17 UTC, closed without merging