docs: add forms overview guide
angular/angular pull request #25663
Opened 2018-08-24 17:10 UTC by brandonroberts

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Adds Forms Overview page to Forms section. Reorganizes forms guides in nav also.

2018-08-24 21:25 UTC, mihalskiy approved these changes

2018-08-27 02:11 UTC, trotyl commented on aio/content/guide/forms-overview.md
> +Template-driven forms are less explicit in that the source of truth for is the directives in the template. Directives are necessary to bind the model to the component class. You no longer have direct
NgModel should be in backticks?

2018-08-27 16:45 UTC, jbogarthyde commented on packages/forms/PACKAGE.md
> +* Track and listen changes to the form's data model
listen for changes

2018-08-27 16:47 UTC, jbogarthyde commented on packages/forms/PACKAGE.md
> +to the value and status of the controls as provided as observables.
are provided

2018-08-27 16:48 UTC, jbogarthyde commented on packages/forms/PACKAGE.md
> +* **Reactive** using existing instances of a `FormControl` or `FormGroup` to build a form model. This form
**Reactive forms** use ...

2018-08-27 16:49 UTC, jbogarthyde commented on packages/forms/PACKAGE.md
> +* **Template-driven** using directives such as `NgModel` and `NgModelGroup` that provide two-way data binding to
**Template-driven forms** use ...

2018-08-27 16:52 UTC, jbogarthyde commented on packages/forms/PACKAGE.md
> +Implements a set of directives and providers to communicate with native DOM elements when building forms
Nice summary  - only minor editorial comments :-)

2018-08-27 17:00 UTC, jbogarthyde reviewed
Started copy edit, but too awkward in git. Leaving it for Sarah - just reading it now.

2018-08-30 01:25 UTC, kara reviewed
This is looking great. Some comments below. I think it will be a bit easier to review once the diagrams are in.

2018-08-30 01:25 UTC, kara commented on aio/content/guide/forms-overview.md
> +Template-driven forms are less explicit in that the source of truth for is the directives in the template. Directives are necessary to bind the model to the component class. You no longer have direct
>In template-driven forms, the source of truth is the template, so developers create their desired form through the placement of template-driven directives like `NgModel` and `NgModelGroup`. The directives then create the `FormControl` or `FormGroup` instances that make up the form model, link them with form elements through a value accessor, and manage them within the constraints of the template's change detection cycle.  

> This abstraction promotes simplicity over structure.  It is simple to add directives, but because these directives are dependent on the UI, they must work around the change detection cycle. Programmatic value changes are registered during change detection (as they occur through an `@Input` to a directive), so it's not possible to update the value and validity immediately because it may affect elements that have already been checked in that view (e.g. the parent form). For this reason, value changes are delayed until the next tick, which allows change detection to complete and a new change detection process to be triggered with the updated value. In other words, the process happens asynchronously and introduces unpredictability for querying the source of truth.

2018-08-30 01:25 UTC, kara commented on aio/content/guide/forms-overview.md
> +Validation is an integral part of managing any set of forms. Whether you’re checking for required fields or querying an external API for an existing username, Angular provides a set of built-in valid
> With reactive forms, custom validators are functions that receive a control to value to validate.

2018-08-30 01:25 UTC, kara commented on aio/content/guide/forms-overview.md
> +Testing also plays a large part in complex applications and an easier testing strategy is always welcomed.  Reactive forms provide an easy testing strategy to due to synchronous access to the form an
>  In order to access the underlying controls with template-driven forms, you must wait for the appropriate lifecycle hooks to finish before extracting any values, testing its validity or changing its value.

I think the testing section might benefit from an example comparing a simple test.

2018-08-30 01:25 UTC, kara commented on aio/content/guide/forms-overview.md
> +      Immutable
Hmm can you explain what you mean by mutable in TD?

2018-08-31 15:03 UTC, brandonroberts commented on aio/content/guide/forms-overview.md
> +* **Template-driven forms** are useful for adding a simple form to an app, such as a single email list signup form. They are easy to add to an app, but they do not scale as well as reactive forms. If
I think its ok to mention here as a quick decision point. I updated the text to be:

* **Reactive forms** are more robust: they are more scalable, reusable, and testable. If forms are a key part of your application, or you're already using reactive patterns for building your application, use reactive forms.

2018-08-31 15:04 UTC, brandonroberts commented on aio/content/guide/forms-overview.md
> +**Diagram of Input Event Flow For Reactive Forms**
Yes, once the technical review is done, we'll work on getting the diagrams integrated

2018-08-31 15:57 UTC, brandonroberts commented on aio/content/guide/forms-overview.md
> +      Immutable
I added a section above scalability

## Mutability

How changes are tracked plays a role in the efficiency of your application. Reactive forms keep the data model pure by providing it as an immutable data structure. Each time the a change is triggered on the data model, a new data model is returned rather than updating the data model directly. This is more efficient, giving you the ability track unique changes to the data model. It also follows reactive patterns that integrate with observable operators to map and transform data. Template-driven forms rely on mutability with two-way data binding to update the data model in the component as changes are made in the template.

2018-08-31 16:34 UTC, mary-poppins commented
You can preview 0d05573 at https://pr25663-0d05573.ngbuilds.io/.

2018-08-31 20:25 UTC, kara commented on packages/forms/PACKAGE.md
> +* *Template-driven* use directives such as `NgModel` and `NgModelGroup` that provide two-way data binding to
Nit: Technically, two-way binding is a framework feature you can use anywhere (not provided by the directives). How about:

> Template-driven forms rely on directives such as `NgModel` and `NgModelGroup` to create the form model for you, so any changes to the form are communicated through the template.

2018-09-05 14:07 UTC, mary-poppins commented
You can preview 210d1e3 at https://pr25663-210d1e3.ngbuilds.io/.

2018-09-05 17:20 UTC, kara commented on aio/content/guide/forms-overview.md
> +### Data flow in template-driven forms
It looks like this header is too high? It comes before the reactive forms explanation.

2018-09-05 18:31 UTC, mary-poppins commented
You can preview 8542715 at https://pr25663-8542715.ngbuilds.io/.

2018-09-12 18:31 UTC, jenniferfell requested changes
Navigation review completed. A few minor things, while we have this open. Thanks.

2018-09-12 18:31 UTC, jenniferfell commented on aio/content/navigation.json
> +              "tooltip": "Create a template-driven form using directives and Angular template syntax"
please add . to match style of others
".... template syntax."

2018-09-12 18:31 UTC, jenniferfell commented on aio/content/navigation.json
>                "title": "Dynamic forms",
While you're here, please fix caps to match others in TOC: "Dynamic Forms" Thanks!

2018-09-12 18:31 UTC, jenniferfell commented on aio/content/navigation.json
> +              "tooltip": "User input triggers DOM events. We listen to those events with event bindings that funnel updated values back into our components and models."
While you're here, please fix the "we" and "our". 
"Angular listens to those events"? 
"...your app's components and models"?

2018-09-13 19:23 UTC, jenniferfell requested changes
A few comments directly here. Others have been shared via Google drive in a Google doc and an uploaded marked up PDF.

2018-09-17 17:11 UTC, mary-poppins commented
You can preview cc14a62 at https://pr25663-cc14a62.ngbuilds.io/.

2018-09-17 17:38 UTC, mary-poppins commented
You can preview 223b8da at https://pr25663-223b8da.ngbuilds.io/.

2018-09-18 18:33 UTC, mary-poppins commented
You can preview 3e19c4c at https://pr25663-3e19c4c.ngbuilds.io/.

2018-09-18 18:48 UTC, jbogarthyde commented on aio/content/guide/forms-overview.md
> +
Each set of forms promote a distinct... -> Each approach uses a distinct...
"These concepts are key..."  -- which concepts?? 

This is all about the differences and comparison, but doesn't offer any common ground -  I would like to start with some "key concepts" that apply to all forms, but are handled differently in the two approaches. This would be something about how forms need to tie together the view and data model, so that changes in one can be reflected in the other.

2018-09-18 18:53 UTC, jbogarthyde commented on aio/content/guide/forms-overview.md
> +
... to use it in a template.   To use *what*  in a template?

2018-09-18 19:03 UTC, jbogarthyde commented on aio/content/guide/forms-overview.md
> +This is demonstrated in the examples above using the **favorite color** input element. With reactive forms, the **form control instance** always returns a new value when the control's value is update
This is demonstrated -> This difference is demonstrated

2018-09-18 19:09 UTC, jbogarthyde commented on aio/content/guide/forms-overview.md
> +- Template-driven forms rely on mutability with two-way data binding to update the data model in the component as changes are made in the template.
...a new data model is returned rather than updating the data model directly. 
  Make this active -- *Who* returns a new data model? *Who* updates the data model directly? 

 How does returning a new data model give you the ability to track changes?

Maybe refer to some discussion of why mutability is undesirable?

2018-09-18 19:29 UTC, jbogarthyde commented on aio/content/guide/forms-overview.md
> +
Because template-driven forms focus on simple scenarios with very little validation, they are not as reusable *and abstract away the low-level APIs and access to the data model is handled asynchronously.*
 - I don't see how the last part of this sentence is related to the first part. Is the abstraction a result of the simplicity and lack of validation? Or is it a separate issue that also affects scalability? If so, how? 
 What about the async data access -- is that related to the simplicity and lack of validation, or to the abstraction? How does it affect scalability? By reducing performance?

2018-09-18 19:34 UTC, jbogarthyde commented on aio/content/guide/forms-overview.md
> +
complements > complement (to agree with plural "forms" and be parallel with "integrate" .)

"...all play important parts in the infrastructure..." > perhaps "... are all important considerations in choosing the infrastructure..."

2018-09-19 18:04 UTC, mary-poppins commented
You can preview 039335c at https://pr25663-039335c.ngbuilds.io/.

2018-09-19 18:18 UTC, mary-poppins commented
You can preview e90df2d at https://pr25663-e90df2d.ngbuilds.io/.

2018-09-19 18:30 UTC, kara commented on aio/content/guide/forms-overview.md
> +1. The control value accessor on the form input element is updates the element with the latest value.
Typo: is updates -> updates

2018-09-19 18:30 UTC, kara commented on aio/content/guide/forms-overview.md
> +1. The form input element emits an input event with the latest value.
I think we may be missing a step here for what triggers the input event. Maybe:

> 1. The end user types a value into the input element.
> 2. The form input element emits an input event with that value.
> 3. The control value accessor on the form input element immediately relays the new value to the `FormControl` instance, which then emits the value through the `valueChanges` observable.

2018-09-19 18:30 UTC, kara commented on aio/content/guide/forms-overview.md
> +1. The form control instance sets the latest value and emits the latest value through the `valueChanges` observable.
'form control instance' -> `FormControl` instance

2018-09-19 18:30 UTC, kara commented on aio/content/guide/forms-overview.md
> +1. The form control instance sets the latest value and emits the latest value through the `valueChanges` observable.
I think we should mention `setValue()` specifically or it's not clear what kicks off the process.

> 1. `favoriteColorControl.setValue()` is called, which updates the `FormControl` value and emits...

2018-09-19 18:30 UTC, kara commented on aio/content/examples/forms-overview/src/app/reactive/favorite-color/favorite-color.component.ts
> +  favoriteColor = new FormControl('');
Should be `favoriteColorControl` to match diagram?

2018-09-19 18:30 UTC, kara commented on aio/content/guide/forms-overview.md
> +1. The control value accessor uses the `NgModel` directive to update its model, queues an async task to set the value for the internal form control instance.
view -> model updates aren't actually asynchronous because updates occur during the event phase, before change detection runs.  I'd write the steps as: 

> 1. The end user types "blue" into the input element.
> 2. The input element emits an "input" event with the value "blue". 
> 3. The control value accessor attached to the input triggers `setValue()` to be called on the `FormControl` instance, which emits that value through the `valueChanges` observable.
> 4. The control value accessor also calls `NgModel`'s `viewToModel` function, which emits an `ngModelChange` event.
> 5. Since the component template uses a two-way binding for `favoriteColor`, the `favoriteColor` property in the component is updated to the value emitted by the `ngModelChange` event ("blue").

2018-09-19 18:30 UTC, kara commented on aio/content/guide/forms-overview.md
> +1. Change detection calls the `ngOnChanges` method on the `NgModel` directive instance, updates the `NgModel` instance model value, and queues an async task to set the value for the internal form con
form control instance -> `FormControl` instance

2018-09-19 18:30 UTC, kara commented on aio/content/guide/forms-overview.md
> +1. After the change detection cycle completes, the task to set the form control instance value is called, when then emits the latest value through the `valueChanges` observable.
> On the next browser tick, the task to set the `FormControl` instance value is executed, which then ...

2018-09-19 18:43 UTC, kara commented on aio/content/examples/forms-overview/src/app/template/favorite-color/favorite-color.component.spec.ts
> +    tick();
Hm, I don't think this `tick()` is necessary here. But we do need a `fixture.detectChanges`.

2018-09-19 19:14 UTC, brandonroberts commented on aio/content/guide/forms-overview.md
> +1. After the change detection cycle completes, the task to set the form control instance value is called, when then emits the latest value through the `valueChanges` observable.
We don't specifically mention "browser tick" anywhere else. Can we just use the next tick?

2018-09-19 19:28 UTC, mary-poppins commented
You can preview 5e59490 at https://pr25663-5e59490.ngbuilds.io/.

2018-09-19 19:39 UTC, mary-poppins commented
You can preview 4971419 at https://pr25663-4971419.ngbuilds.io/.

2018-09-19 19:45 UTC, kara commented on aio/content/guide/forms-overview.md
> +1. After the change detection cycle completes, the task to set the form control instance value is called, when then emits the latest value through the `valueChanges` observable.
Yeah, that works too

2018-09-20 14:27 UTC, jenniferfell commented
This is coming along really nicely! As a reader, I think I get it! The diagrams and data flow and test sections are really falling into place. 

I'll probably send some notes offline in scanned PDF. Highlights:

- Diagrams and code titles: Parentheses should only be used for text that is supplemental/optional. In the diagram titles and code example titles, the text in parentheses is actually an essential part of the title and key differentiator. Please change. Also please be consistent everywhere with "model to view" spaces v. hypenation. Ex 1: "Reactive Forms - Data Flow (Model to View)" please change to "Reactive Forms Data Flow - Model to View". Ex 2: "Favorite color test (model-to-view)" please change to "Favorite color test - model to view". (@sjtrimble also a note for you there, thanks)

- Terminology: The diagrams focus on "form control instance" and the surrounding text focuses on "form model." There is one sentence early that defines "form model" as a FormControl instance, so I assume they are interchangeable. The problem is that readers have to keep doing that replacement in their heads. Please pick a term and stay with it (ideally) or (if that's not possible for some reason) then reinforce the connection in each diagram description, so the text below the diagrams is easier to match to the diagrams. 

- Setup: Please see notes on my previous review. I still think setup should be its own section before data flow section. I think setup = what's in "Form model" + the code examples from the start of data flow. You can see how the reactive forms diagram flows into "the form model is explicitly defined in the component class" and that flows into the code example from data flows, which shows how all these things are set up in the code itself. Section title could be "Setup and the form model" or "Setting up the form model" or something like that. Use subheadings for reactive v. template-driven, to match the way you handled data flows. 

- "This" and "it": Review everywhere and make sure references are clear. 

- Introductions to lists: Always use a full sentence. Never use a partial sentence or assume that the diagram can stand as an introduction to the list. 

- Data flow and testing sections: A couple sentences in each to reinforce points from the table would be nice. For example, I can see hints of how source of truth and predictability (async v sync) are in each data flow, but using the same words as the table and intros might reinforce exactly how it's demonstrated here. Be concrete in the context of the example, to make it real. If you can. 

-  I like the differences table consolidation, but should we add "source of truth" back in? Also, that term needs a definition when first used. The trusted storage of the data value, from which all other uses are updated?

2018-09-20 14:27 UTC, jenniferfell requested changes
See summary notes in previous comment.

2018-09-20 15:41 UTC, jenniferfell requested changes
This was more clear than my handwritten PDF. Note all changes are required, but not quite ready to approve. Definitely coming along really well!

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +With reactive forms, the form model is explicitly defined in the component class. The reactive form directive (in this case, `FormControlDirective`) then links the existing form control instance to a
Where is the component class in this diagram? Can we connect to what we see? Maybe bring the dashed box with { } TypeScript into this diagram so the setup part is complete here and we just add data flow annotations in diagrams 3 and 4? @sjtrimble ?

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +When building forms in Angular, it's important to understand how the the framework handles data flowing from the user or from programmatic changes. Reactive and template-driven forms follow two diffe
Suggestion - rephrase to talk about what the doc/example are doing, and the components are part of that. Something like: "The data flow examples below define a component that uses an input field to manage a *favorite color* value, and they show how changes to favorite color are handled in reactive forms compared to template-driven forms."

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +When building forms in Angular, it's important to understand how the the framework handles data flowing from the user or from programmatic changes. Reactive and template-driven forms follow two diffe
We've already used favorite color above in the setup / form model section. Probably should move the example description up to that section. Then here focus on: "The data flow examples below begin with the favorite color input field example from above, and they show how changes to favorite color are handled in reactive forms compared to template-driven forms."

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +Here is a component with an input field for a single control implemented using reactive forms.
I'd move this into setup/form model above.

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +The diagrams below show how the data flows for an input with reactive forms.
With the code moved up to setup/form model, maybe an intro like this: "As described above, in reactive forms each form element in the view is directly linked to a form model (`FormControl` instance). The diagrams below uses the same favorite color example to demonstrate how data flows when an input field's value is changed from the view and then from the model."

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +  <img src="generated/images/guide/forms-overview/dataflow-reactive-forms-vtm.png" alt="Reactive forms view to model data flow" width="100%">
alt="Reactive forms data flow - view to model"

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +From the view-to-model:
Full sentence intros to lists

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +1. The control value accessor on the form input element immediately relays the new value to the `FormControl` instance, which then emits the value through the `valueChanges` observable.
Maybe break this into 2 steps?

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +1. The control value accessor on the form input element immediately relays the new value to the `FormControl` instance, which then emits the value through the `valueChanges` observable.
So control value accessors listen for events from form elements?

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +1. The control value accessor on the form input element immediately relays the new value to the `FormControl` instance, which then emits the value through the `valueChanges` observable.
Highlight how the form model is the single source of truth?

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +1. The control value accessor on the form input element immediately relays the new value to the `FormControl` instance, which then emits the value through the `valueChanges` observable.
Final step maybe: Anything that subscribes to this valueChanges observable then updates its value to Blue?

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +1. The end user types a value into the input element.
Opportunity to reinforce diagram connection and be specific: The end user types a value into the input element, in this case the favorite color "blue".

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +1. The `favoriteColorControl.setValue()` method is called, which updates the `FormControl` value and emits the latest value through the `valueChanges` observable.
I'd change "latest value" to "new value." The initiating action is a change of value, not a query for the current (or last set) value.

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +1. The control value accessor on the form input element updates the element with the latest value.
And then anything else subscribing to the valueChanges observable also updates itself? I ask because it seems like that's an important benefit and so maybe being explicit is helpful?

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +1. The control value accessor attached to the input triggers the `setValue()` method on the `FormControl` instance, which emits that value through the `valueChanges` observable.
maybe split into 2 steps?

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +1. The end user types "Blue" into the input element.
I like how this is specific :-)

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +Validation is an integral part of managing any set of forms. Whether you’re checking for required fields or querying an external API for an existing username, Angular provides a set of built-in valid
Could make easier to scan by putting RF and TDF sentences in 2 bullets. Maybe make functions and directives bold, to emphasize the diff and connect to the words in the key diffs table earlier?

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +### Testing a reactive form
Better heading style: "Testing reactive forms"

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +Reactive forms provide a relatively easy testing strategy to due to synchronous access to the form and data models, and being independent of the UI. In these set of tests, controls and data are queri
New paragraph. Some cleanup: "The following tests use the favorite color components mentioned earlier to validate the view-to-model and model-to-view data flows for a reactive form."

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +The following test validates the view-to-model data flow:
Is there a word other than "validates"? I ask just because this section comes right after "Form validation" which is different. Hmmm...

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +Reactive forms provide a relatively easy testing strategy to due to synchronous access to the form and data models, and being independent of the UI. In these set of tests, controls and data are queri
Rewrite: Reactive forms provide a relatively easy testing strategy because they provide synchronous access to the form and data models, and they can be tested without rendering the UI.

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +Reactive forms provide a relatively easy testing strategy to due to synchronous access to the form and data models, and being independent of the UI. In these set of tests, controls and data are queri
Edit: In this set of tests
Also...which? the tests shown here in this doc?

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +Reactive forms provide a relatively easy testing strategy to due to synchronous access to the form and data models, and being independent of the UI. In these set of tests, controls and data are queri
New paragraph before "The following tests" helps when reading online

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +1. On the next tick, the task to set the `FormControl` instance value is executed, when then emits the latest value through the `valueChanges` observable.
when then?

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +Writing tests with template-driven forms is more involved and requires more detailed knowledge of the change detection process and how directives run on each cycle to ensure elements are queried, tes
While readers are probably reading sequentially, perhaps remove some of the comparison "more": "Writing tests with template-driven forms requires more detailed knowledge of the change detection process and how directives run on each cycle to ensure elements are queried, tested, or changed at the correct time."

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +
Is it possible to use the steps to reinforce why  UI rendering is required for template-driven forms?

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +- Template-driven forms rely on mutability with two-way data binding to update the data model in the component as changes are made in the template. Because there are no unique changes to track on the
binding, change detection is....

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +## Scalability
Bullets would help for RF and TDF sentences

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +If forms are a central part of your application, scalability is very important. Being able to reuse form models across components is critical. Reactive forms make creating large scale forms easier by
make parallel: Because template-driven forms focus on simple scenarios, they are not as reusable, abstract away the low-level APIs and access to the form model is provided asynchronously.

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +If forms are a central part of your application, scalability is very important. Being able to reuse form models across components is critical. Reactive forms make creating large scale forms easier by
I had trouble parsing this: This (ref?) surfaces in testing also, where testing reactive forms requires less setup and has no dependance on the change detection cycle when updating and validating the form and data models during testing.

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +Choosing a strategy begins with understanding the strengths and weaknesses of the options presented. Low-level API and form model access, predictability, mutability, straightforward validation and te
A little less casual and be careful not to insult AngularJS...

"Template-driven forms are similar to patterns in AngularJS, but they have limitations given the criteria of many modern, large-scale Angular apps."

"Template-driven forms are familiar to AngularJS developers, but they have limitations given the criteria of many modern, large-scale Angular apps."

Maybe also add " Those limitations are alleviated with reactive forms."

2018-09-20 15:41 UTC, jenniferfell commented on aio/content/guide/forms-overview.md
> +You can learn more with examples and best practices using reactive forms or template-driven forms. The following guides are the next steps in the learning process.
I tripped over the first sentence. Maybe just remove it? Maybe rephrase?

2018-09-24 16:58 UTC, jenniferfell commented
Approving for RC 1. Any changes that can't be incorporated for RC 1 can come later. Nothing show-stopping in my comments.

2018-09-24 16:58 UTC, jenniferfell approved these changes

2018-09-24 20:32 UTC, mary-poppins commented
You can preview 159f5ef at https://pr25663-159f5ef.ngbuilds.io/.

2018-09-24 20:44 UTC, kara requested changes
Typos

2018-09-24 20:44 UTC, kara commented on aio/content/guide/forms-overview.md
> +|Setup (form model)|More explicit created in the component class.|Less explicit, created by the directives.|
Missing comma after `more explicit`?

2018-09-24 20:44 UTC, kara commented on aio/content/guide/forms-overview.md
> +As described above, in reactive forms each form element in the view is directly linked to a form model (FormControl instance). Updates from the view to model and model to view are synchronous and not
Missing backticks around `FormControl`

Typo: the diagrams below uses -> the diagrams below use

2018-09-24 20:44 UTC, kara commented on aio/content/guide/forms-overview.md
> +In template-driven forms each form element in the linked to a directive that manages the form model internally. The diagrams below uses the same favorite color example to demonstrate how data flows w
Do you mean ` is linked to a directive`?

> In template-driven forms each form element in the linked to a directive that manages the form model internally

Should be

>In template-driven forms, each form element is linked to a directive that manages the form model internally

2018-09-24 20:44 UTC, kara commented on aio/content/guide/forms-overview.md
> +1. The form input element emits an input event with the latest value.
The "input" event has quotes in later sections. Add quotes here too?

2018-09-25 15:54 UTC, mary-poppins commented
You can preview ee3cf2d at https://pr25663-ee3cf2d.ngbuilds.io/.

2018-09-25 16:21 UTC, StephenFluin requested changes
Content looks really good, just a couple nits to simplify code samples.

2018-09-25 16:21 UTC, StephenFluin commented on aio/content/examples/forms-overview/src/app/template/favorite-color/favorite-color.component.ts
> +  styles: []
Is there any reason to have the empty styles here?

2018-09-25 16:21 UTC, StephenFluin commented on aio/content/examples/forms-overview/src/app/reactive/favorite-color/favorite-color.component.ts
> +  styles: []
Is there any reason to have the empty styles here?

2018-09-25 16:21 UTC, StephenFluin commented on aio/content/examples/forms-overview/src/app/app.module.ts
> +  providers: [],
Is there any reason for the empty providers here?

2018-09-25 16:54 UTC, brandonroberts commented
@StephenFluin the unused properties have been removed.

2018-09-25 17:01 UTC, StephenFluin approved these changes

2018-09-25 17:03 UTC, mary-poppins commented
You can preview b03b981 at https://pr25663-b03b981.ngbuilds.io/.

2018-09-26 01:01 UTC, kara reviewed
Last nits

2018-09-26 01:01 UTC, kara commented on aio/content/guide/forms-overview.md
> +- With reactive forms, the **form control instance** always returns a new value when the control's value is updated.
`FormControl` instance

2018-09-26 01:01 UTC, kara commented on aio/content/guide/forms-overview.md
> +- **Template-driven** forms focus on simple scenarios, are not as reusable, abstract away the low-level APIs and access to the form model is  provided asynchronously. The abstraction with template-dr
Typo: dependance -> dependence

2018-09-26 01:38 UTC, kara approved these changes
LGTM

2018-09-26 01:42 UTC, mary-poppins commented
You can preview ca69fad at https://pr25663-ca69fad.ngbuilds.io/.

2018-09-26 01:49 UTC, closed without merging