docs: add missing instruction in HTTP section
angular/angular pull request #25715
Opened 2018-08-29 06:05 UTC by FrederikSchlemmer

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The current behavior is that the steps in the "HTTP" section of the Tour of Heroes cause confusion for the user. A step for creating the file "in-memory-data.service" is missing.

The problem has been reported by others in Stack Overflow:
[https://stackoverflow.com/questions/39877282/cannot-find-module-in-memory-data-service-in-tour-of-heroes-for-angular2]()

Issue Number: #25693

## What is the new behavior?
The new behavior is that the step to create the file "in-memory-data.service" is explained correctly.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-08-29 13:44 UTC, mary-poppins commented
You can preview c46678f at https://pr25715-c46678f.ngbuilds.io/.

2018-08-29 14:03 UTC, brandonroberts commented
Shouldn't be a `class` that's generated and not a service?

2018-09-04 19:33 UTC, brandonroberts requested changes

2018-09-04 19:33 UTC, brandonroberts commented on aio/content/tutorial/toh-pt6.md
> +Now the class `src/app/in-memory-data.service.ts` is generated by the following command:
"Now the" -> "The"

2018-09-04 19:33 UTC, brandonroberts commented on aio/content/tutorial/toh-pt6.md
> +  ng generate service InMemoryData --module=app
Remove `--module=app` as this is no longer supported in the CLI.

2018-09-04 19:33 UTC, brandonroberts commented on aio/content/tutorial/toh-pt6.md
>  <code-example path="toh-pt6/src/app/in-memory-data.service.ts" region="init" title="src/app/in-memory-data.service.ts" linenums="false"></code-example>
The code snippet here needs to be updated also with the default syntax generated for a service.

```
@Injectable({
  providedIn: 'root'
})
export ...
```

2018-09-05 09:50 UTC, FrederikSchlemmer commented on aio/content/tutorial/toh-pt6.md
>  <code-example path="toh-pt6/src/app/in-memory-data.service.ts" region="init" title="src/app/in-memory-data.service.ts" linenums="false"></code-example>
Also updated the code snippet!

2018-09-05 09:51 UTC, mary-poppins commented
You can preview 368045c at https://pr25715-368045c.ngbuilds.io/.

2018-09-05 09:58 UTC, FrederikSchlemmer commented
@brandonroberts When updating the code snippet I noticed that the example on stackblitz would also need to be updated.
Could you briefly explain to me how to update from stackblitz examples?

Live Example:
https://stackblitz.com/angular/xkxkdjbqaol

2018-09-05 13:40 UTC, brandonroberts commented
@FrederikSchlemmer the stackblitz examples are generated at build time, so as long as your change is included in the doc regions it will be added in the example.

2018-09-05 13:41 UTC, brandonroberts requested changes

2018-09-05 13:41 UTC, brandonroberts commented on aio/content/examples/toh-pt6/src/app/in-memory-data.service.ts
> +})
Move the decorator right above the class.

```
@Injectable({
  providedIn: 'root',
})
export class ...
```

2018-09-06 05:57 UTC, FrederikSchlemmer commented
@brandonroberts Good to hear that the stackblitz example is updated automatically! I have applied the changes.

2018-09-06 06:03 UTC, mary-poppins commented
You can preview dfe1ccc at https://pr25715-dfe1ccc.ngbuilds.io/.

2018-09-12 13:24 UTC, brandonroberts approved these changes

2018-10-10 14:05 UTC, FrederikSchlemmer commented
@brandonroberts I made a rebase on this pull request, which requires a new approval.

I hope that the PR will be merged soon...

2018-10-10 14:08 UTC, mary-poppins commented
You can preview 2a69150 at https://pr25715-2a69150.ngbuilds.io/.

2018-10-25 18:39 UTC, mary-poppins commented
You can preview d4c2156 at https://pr25715-d4c2156.ngbuilds.io/.

2018-10-31 07:54 UTC, FrederikSchlemmer commented
@brandonroberts What do you think about this PR?

2018-11-05 14:09 UTC, brandonroberts commented
@FrederikSchlemmer PR is still good. Will you rebase this branch again? Still waiting on a second review/approval.

2018-11-08 05:54 UTC, FrederikSchlemmer commented
@brandonroberts I did the rebase. 
Ready for the next review @IgorMinar @jenniferfell.

2018-11-09 07:50 UTC, IgorMinar approved these changes

2018-11-09 15:13 UTC, mary-poppins commented
You can preview a6ce410 at https://pr25715-a6ce410.ngbuilds.io/.

2018-11-09 17:45 UTC, closed without merging