Universal: Integrate CLI wiki material and copy edit
angular/angular pull request #25752
Opened 2018-08-30 22:36 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Added more succinct CLI-oriented info at beginning as a summary, made the existing ToH example more specifically tutorial-style. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-08-30 22:42 UTC, mary-poppins commented
You can preview ebbee7f at https://pr25752-ebbee7f.ngbuilds.io/.

2018-08-31 02:44 UTC, CaerusKaru commented
Not sure if this PR is the appropriate place for this, but we recently removed the Webpack part of the Universal build process in `universal` and `universal-starter`. cc @vikerman @Toxicable @IgorMinar for guidance.

2018-08-31 15:26 UTC, jbogarthyde commented
This is exactly the right place to correct the current doc :-)
Can you mark up the exact  parts of the doc that should be removed or changed?
And also, the content should get a complete technical review from everyone involved, if possible.

2018-08-31 15:30 UTC, mary-poppins commented
You can preview a171d8a at https://pr25752-a171d8a.ngbuilds.io/.

2018-09-03 15:13 UTC, mary-poppins commented
You can preview 6649b56 at https://pr25752-6649b56.ngbuilds.io/.

2018-09-10 20:48 UTC, mary-poppins commented
You can preview e2100dd at https://pr25752-e2100dd.ngbuilds.io/.

2018-09-11 19:19 UTC, mary-poppins commented
You can preview bb88b3b at https://pr25752-bb88b3b.ngbuilds.io/.

2018-09-13 15:27 UTC, mary-poppins commented
You can preview 7e7aeb5 at https://pr25752-7e7aeb5.ngbuilds.io/.

2018-09-14 15:45 UTC, mary-poppins commented
You can preview eb81296 at https://pr25752-eb81296.ngbuilds.io/.

2018-09-14 16:06 UTC, mary-poppins commented
You can preview 95a8e18 at https://pr25752-95a8e18.ngbuilds.io/.

2018-09-19 21:11 UTC, mary-poppins commented
You can preview fc1b2f3 at https://pr25752-fc1b2f3.ngbuilds.io/.

2018-09-20 15:58 UTC, mary-poppins commented
You can preview 1015933 at https://pr25752-1015933.ngbuilds.io/.

2018-09-21 18:16 UTC, mary-poppins commented
You can preview a236105 at https://pr25752-a236105.ngbuilds.io/.

2018-09-22 00:34 UTC, vikerman requested changes

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
> +The server (a [Node Express](https://expressjs.com/) server in this guide's example)
duplicate 'server'

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
> +
This summary is good in explaining how to move from client-side only app to SSR version. But with the schematics we probably need not go into the actual commands? 

I would want to say something like `@nguniversal/express-engine` schematics takes care of all the steps required to prepare the app for SSR. Here is the summary of steps it actually performs ....

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
> + * A webpack config file for the server, `webpack.server.config.js`
Remove all of this in favor of 

Run 

ng add @nguniversal/express-engine --clientProject angular.io-example

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
>  {@a preparation}
It is good to continue to mention the new files added by the schematics like above.

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
> +It gives the appearance of a near-instant application, while the browser downloads the client app scripts in background.
Remove this section

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
Remove this section

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
Remove section

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
This is good to keep. Though I didn't have to make any changes to the Tour of heroes app app to keep it working.

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
> +## Add server code
Remove section

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
> +### Create an app server module
Remove section

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
> +### Create an app server entry point
Remove section

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
> +### Configure the web server
Remove section

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
>  ### Universal TypeScript configuration
Remove section. Not needed to explain again. I think already explained in Summary?

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
This section provides a good overview of the generated Express code. We should keep it.

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
>  ### Angular CLI configuration
Remove section

2018-09-22 00:34 UTC, vikerman commented on aio/content/guide/universal.md
> +## Build and run with Universal
Remove. Done by the schematics and explained in summary

2018-09-22 15:47 UTC, mary-poppins commented
You can preview 8ace262 at https://pr25752-8ace262.ngbuilds.io/.

2018-09-22 15:55 UTC, jbogarthyde commented on aio/content/guide/universal.md
> +It gives the appearance of a near-instant application, while the browser downloads the client app scripts in background.
@vikerman  There was a reference to this section on line 64 - I have removed the reference, but it the concept still true?  

"In practice, you'll serve a static version of the landing page to hold the user's attention.
At the same time, you'll load the full Angular app behind it.  <removed ref to "as described in...">
The user perceives near-instant performance from the landing page
and gets the full interactive experience after the full app loads."

2018-09-22 16:08 UTC, jbogarthyde commented on aio/content/guide/universal.md
>  ### Angular CLI configuration
Which section? 
### Universal webpack configuration
or 
### Angular CLI configuration

2018-09-25 15:53 UTC, jbogarthyde commented on aio/content/guide/universal.md
> +## Build and run with Universal
It's not entirely clear to me which sections your comments refer to -- 
I removed

2018-09-25 18:13 UTC, mary-poppins commented
You can preview 4ad565d at https://pr25752-4ad565d.ngbuilds.io/.

2018-09-26 15:46 UTC, mary-poppins commented
You can preview bf573d5 at https://pr25752-bf573d5.ngbuilds.io/.

2018-09-27 16:30 UTC, mary-poppins commented
You can preview 5e49881 at https://pr25752-5e49881.ngbuilds.io/.

2018-09-27 16:35 UTC, mary-poppins commented
You can preview f2690da at https://pr25752-f2690da.ngbuilds.io/.

2018-09-27 17:45 UTC, vikerman requested changes

2018-09-27 17:45 UTC, vikerman commented on aio/content/guide/universal.md
> +The CLI schematic `@nguniversal/express-engine` performs the steps required to prepare an app for server-side rendering. This section provides a summary of how the CLI sets up required configuration.
Can you increase the importance of this section so that it's clear that the schematics takes care of everything below?

2018-09-27 17:45 UTC, vikerman commented on aio/content/guide/universal.md
> +### Install the project and Universal libraries
Please remove this and everything under

### Install the project and Universal libraries

2018-09-27 17:45 UTC, vikerman commented on aio/content/guide/universal.md
> +Create a `tsconfig.server.json` file in the project root directory to configure TypeScript and AoT compilation of the Universal app.
Please remove Universal TypeScript configuration and everything under it

2018-09-27 17:45 UTC, vikerman commented on aio/content/guide/universal.md
> +`ng add @nguniversal/express-engine --clientProject angular.io-example`
Please put the "ng add command" as code-example format="." language="bash" so that it's clear that it's a command to be executed.

2018-09-27 18:18 UTC, jbogarthyde commented on aio/content/guide/universal.md
> +`ng add @nguniversal/express-engine --clientProject angular.io-example`
Done - if it looks ok, please check off your "Changes requested" status.

2018-09-27 18:27 UTC, mary-poppins commented
You can preview a485281 at https://pr25752-a485281.ngbuilds.io/.

2018-09-27 19:09 UTC, jenniferfell commented
"Universal" would be good to add to the glossary, because we talk about "Angular Universal" in misc places: https://github.com/angular/angular/issues/26147

2018-09-27 19:35 UTC, jenniferfell requested changes

2018-09-27 19:35 UTC, jenniferfell commented on aio/content/guide/universal.md
>  There are three main reasons to create a Universal version of your app.
If "Why Universal" is so long that it requires subheadings (H4), then I recommend putting the H2 back in place.

2018-09-27 19:35 UTC, jenniferfell commented on aio/content/guide/universal.md
> +
If part of this doc is what the schematic does v. what I need to do as a developer, then that needs to be more clear. That wasn't very clear to me.

2018-09-27 19:35 UTC, jenniferfell commented on aio/content/guide/universal.md
> +## Summary
Needs better title. Setting up an app for server-side rendering?

2018-09-27 19:35 UTC, jenniferfell commented on aio/content/guide/universal.md
> +#### Create scripts
Seems important enough to get its own step or heading level that will show in the TOC

2018-09-27 19:35 UTC, jenniferfell commented on aio/content/guide/universal.md
> +The _Tour of Heroes_ tutorial is the foundation for this walkthrough.
Need to tell users where to get the TOH files that you expect them to start with. Seems to miss a key setup step.

2018-09-27 19:35 UTC, jenniferfell commented on aio/content/guide/universal.md
> +The command creates the following folder structur.
missing e

2018-09-27 19:35 UTC, jenniferfell commented on aio/content/guide/universal.md
> +### Use absolute URLs for server requests
As a concept, this seems parallel to the working around the browser APIs. Maybe there's a section to introduce key things you'll need to consider when preparing your app for server-side rendering. Then this tutorial step already has some context. "As mentioned above, you need to use absolute URLs. The Tour of Heroes doesn't, so you'll need to fix it." (skimmed, but it feels like that's what's going on here)

2018-09-27 19:35 UTC, jenniferfell commented on aio/content/guide/universal.md
>  #### Universal template engine
This seems important but as L4 inside the tutorial, it's not in the TOC and it isn't in a place where I can easily "get" the key concepts of Universal. Should this be up in how it works?

2018-09-27 19:35 UTC, jenniferfell commented on aio/content/guide/universal.md
> +<strong>Universal HTTP requests have different security requirements</strong>
Seems important and buried

2018-09-27 19:35 UTC, jenniferfell commented on aio/content/guide/universal.md
>  ## Universal in action
This should be part of the tutorial above

2018-10-02 16:05 UTC, mary-poppins commented
You can preview 4198cad at https://pr25752-4198cad.ngbuilds.io/.

2018-10-02 16:38 UTC, jbogarthyde commented on aio/content/guide/universal.md
> +The _Tour of Heroes_ tutorial is the foundation for this walkthrough.
Is there a place to download a finished one? Is it the "live example"?

2018-10-02 16:40 UTC, jbogarthyde commented on aio/content/guide/universal.md
> +### Use absolute URLs for server requests
Moved the working-around browser section here, to be parallel. Not sure if these two subsections need a new parent section.

2018-10-02 16:44 UTC, jbogarthyde commented on aio/content/guide/universal.md
>  #### Universal template engine
Moved all of these up - still not sure they belong in tutorial.

2018-10-02 17:02 UTC, jbogarthyde commented on aio/content/guide/universal.md
> +<strong>Universal HTTP requests have different security requirements</strong>
Moved it up - doesn't quite fit in anywhere.

2018-10-02 17:08 UTC, mary-poppins commented
You can preview d2ddbd5 at https://pr25752-d2ddbd5.ngbuilds.io/.

2018-10-04 16:29 UTC, mary-poppins commented
You can preview 42974c0 at https://pr25752-42974c0.ngbuilds.io/.

2018-10-05 15:34 UTC, mary-poppins commented
You can preview 8eee5e9 at https://pr25752-8eee5e9.ngbuilds.io/.

2018-10-08 18:56 UTC, mary-poppins commented
You can preview 0ed4fbc at https://pr25752-0ed4fbc.ngbuilds.io/.

2018-10-09 16:30 UTC, mary-poppins commented
You can preview de78365 at https://pr25752-de78365.ngbuilds.io/.

2018-10-09 23:01 UTC, jenniferfell commented
@vikerman @jbogarthyde : I just closed PR https://github.com/angular/angular/pull/26286, which was a suggestion to include info about how to install the webpack CLI. Is that step still needed in the approach in this new doc? If so, please refer to that PR for a bit to include here. Thanks!

2018-10-10 21:14 UTC, mary-poppins commented
You can preview dca3e3b at https://pr25752-dca3e3b.ngbuilds.io/.

2018-10-11 17:29 UTC, vikerman commented
We don't need to include the webpack CLI info as it's not needed.

2018-10-11 17:45 UTC, jenniferfell approved these changes
I only looked at the overall structure in the right nav. LGTM except the two things we talked about in slack.

2018-10-11 17:45 UTC, jenniferfell commented on aio/content/guide/universal.md
> +## Step 2: Prepare your app
From our slack...to avoid duplicate heading, maybe "Modify your app and configuration"

2018-10-11 17:45 UTC, jenniferfell commented on aio/content/guide/universal.md
> +### 2a. Add Universal support to your app
In the preview that I looked at, this heading isn't rendering correctly

2018-10-11 17:47 UTC, jenniferfell commented
@vikerman Just to confirm, these changes also apply to v6, yes?

2018-10-11 17:55 UTC, jbogarthyde commented on aio/content/guide/universal.md
> +### 2a. Add Universal support to your app
Fixed it already, and the md is now correct. Still not rendering though - don't know what else to do to fix it.

2018-10-11 18:01 UTC, mary-poppins commented
You can preview c48c4d5 at https://pr25752-c48c4d5.ngbuilds.io/.

2018-10-12 18:44 UTC, vikerman commented
@jenniferfell - Yes. Applies to V6 as well.

2018-10-12 18:45 UTC, vikerman approved these changes

2018-10-12 18:46 UTC, vikerman commented
Approved. Restarting the flaky tests

2018-10-12 19:41 UTC, vikerman commented
@jbogarthyde - Can you please rebase the PR? Tests continue to fail (clearly unrelated to this PR but would be better to get it passing cleanly before merge)

2018-10-12 21:42 UTC, jbogarthyde commented
Rebased and squashed

2018-10-12 21:43 UTC, mary-poppins commented
You can preview 90f12c8 at https://pr25752-90f12c8.ngbuilds.io/.

2018-10-12 21:44 UTC, mary-poppins commented
You can preview 6b1c429 at https://pr25752-6b1c429.ngbuilds.io/.

2018-10-15 16:57 UTC, mary-poppins commented
You can preview de25370 at https://pr25752-de25370.ngbuilds.io/.

2018-10-15 18:23 UTC, closed without merging