docs: Rename 'QuickStart' to 'Getting Started'
angular/angular pull request #25762
Opened 2018-08-31 11:28 UTC by FrederikSchlemmer

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #25524

## What is the new behavior?
In the entire project 'QuickStart' has been changed to 'Getting Started'.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
I am not sure if it is wanted that the deletion of the symlinks is also considered as a change by Github.

I mean the deletion of 'packages/upgrade/static/src'.

2018-09-02 06:52 UTC, trotyl commented on aio/content/guide/attribute-directives.md
> +3. Talking to DOM API directly isn't a best practice.
Why this change?

2018-09-02 09:53 UTC, sarunint commented on aio/content/guide/attribute-directives.md
> +3. Talking to DOM API directly isn't a best practice.
@FrederikSchlemmer if you want to make this change, submit to it as another PR. This PR focuses on changing QuickStart to Getting Started.

2018-09-02 10:33 UTC, trotyl commented on aio/content/guide/attribute-directives.md
> +3. Talking to DOM API directly isn't a best practice.
Also this will make the maintenance harder, if you want to insert something beside `1` and `2`, then you need to change from line 2 to the end. Leaving everything to 1 make it much easier, just a little ugly in source code.

2018-09-02 11:07 UTC, sarunint commented on aio/content/guide/attribute-directives.md
> +3. Talking to DOM API directly isn't a best practice.
Wow, I don't know that before!

2018-09-04 06:04 UTC, FrederikSchlemmer commented on aio/content/guide/attribute-directives.md
> +3. Talking to DOM API directly isn't a best practice.
@trotyl @sarunint The change was not intended and actually not made by me. Maybe this place was modified by Visual Studio code?

2018-09-04 15:50 UTC, StephenFluin requested changes
This is awesome! Thanks for this contribution. Can we also rename the URL  and filepath of the quickstart to be getting started as well so that we have consistency?

Does the deletion of /upgrade/static/src belong in this PR? I feel like it should be removed

2018-09-05 06:15 UTC, FrederikSchlemmer commented
@StephenFluin As already described in 'Other Information' I wasn't sure if this deletion belongs in the commit either. I have now taken it out.

@jenniferfell My recommendation would be to just change the in-page title and leave the nav title, URL, etc. in place. There are various links to this page, which would break.
Maybe the linking problem should be treated as a separate issue?

2018-09-25 13:54 UTC, jenniferfell commented
Thanks for the ping. I haven't forgotten this. In fact, I've been rewriting the Getting Started for other reasons, so I changed the page title. https://github.com/angular/angular/pull/26093

I'm hoping that rewrite is merged in the next day or so. Then I'd like to merge your changes to the cross reference text. (Thanks for finding all of those.) Would that work for you? It means one more rebase, probably late this week or next. I can let you know. 

Re the URL...we're still considering in the context of some future doc work. 

Thanks again.

2018-09-27 16:23 UTC, jenniferfell approved these changes

2018-09-28 15:20 UTC, StephenFluin approved these changes

2018-10-03 06:54 UTC, gkalpak approved these changes

2018-10-03 06:56 UTC, gkalpak commented
I closed and reopened the PR, because Travis was stuck. Now it need re-approval 😇

2018-10-03 16:25 UTC, jenniferfell approved these changes

2018-10-05 22:44 UTC, closed without merging