Docs: add temp section for new CLI-story pages
angular/angular pull request #25776
Opened 2018-08-31 22:18 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-08-31 22:18 UTC, jbogarthyde commented
Not yet added to nav

2018-08-31 23:53 UTC, mary-poppins commented
You can preview 238a54d at https://pr25776-238a54d.ngbuilds.io/.

2018-09-03 15:11 UTC, mary-poppins commented
You can preview 5e794ae at https://pr25776-5e794ae.ngbuilds.io/.

2018-09-04 18:08 UTC, mary-poppins commented
You can preview d084db7 at https://pr25776-d084db7.ngbuilds.io/.

2018-09-04 21:00 UTC, mary-poppins commented
You can preview 5298fea at https://pr25776-5298fea.ngbuilds.io/.

2018-09-12 16:50 UTC, mary-poppins commented
You can preview 1658ddc at https://pr25776-1658ddc.ngbuilds.io/.

2018-09-12 21:37 UTC, mary-poppins commented
You can preview 482430f at https://pr25776-482430f.ngbuilds.io/.

2018-09-17 22:17 UTC, mary-poppins commented
You can preview a4d2e23 at https://pr25776-a4d2e23.ngbuilds.io/.

2018-09-18 15:33 UTC, mary-poppins commented
You can preview 9ae2769 at https://pr25776-9ae2769.ngbuilds.io/.

2018-09-18 15:59 UTC, mary-poppins commented
You can preview 2024490 at https://pr25776-2024490.ngbuilds.io/.

2018-09-18 16:02 UTC, mary-poppins commented
You can preview 263d6c9 at https://pr25776-263d6c9.ngbuilds.io/.

2018-09-18 16:07 UTC, mary-poppins commented
You can preview c82683e at https://pr25776-c82683e.ngbuilds.io/.

2018-09-18 16:09 UTC, mary-poppins commented
You can preview cdbcbc5 at https://pr25776-cdbcbc5.ngbuilds.io/.

2018-09-18 16:39 UTC, mary-poppins commented
You can preview ee08d86 at https://pr25776-ee08d86.ngbuilds.io/.

2018-09-19 16:43 UTC, mary-poppins commented
You can preview da4617d at https://pr25776-da4617d.ngbuilds.io/.

2018-09-19 17:52 UTC, mary-poppins commented
You can preview 7a2cf62 at https://pr25776-7a2cf62.ngbuilds.io/.

2018-09-19 22:35 UTC, mary-poppins commented
You can preview 3f35385 at https://pr25776-3f35385.ngbuilds.io/.

2018-09-19 22:38 UTC, mary-poppins commented
You can preview 0b38d35 at https://pr25776-0b38d35.ngbuilds.io/.

2018-09-20 00:16 UTC, mary-poppins commented
You can preview d9a9cb0 at https://pr25776-d9a9cb0.ngbuilds.io/.

2018-09-20 00:33 UTC, mary-poppins commented
You can preview 5864ef2 at https://pr25776-5864ef2.ngbuilds.io/.

2018-09-20 13:39 UTC, Gillespie59 commented on aio/content/guide/deployment.md
> +* [NGinx](http://nginx.org/): use `try_files`, as described in
Nginx

2018-09-20 15:27 UTC, mary-poppins commented
You can preview 950057e at https://pr25776-950057e.ngbuilds.io/.

2018-09-20 15:35 UTC, mary-poppins commented
You can preview 2c31441 at https://pr25776-2c31441.ngbuilds.io/.

2018-09-20 16:06 UTC, mary-poppins commented
You can preview c45724e at https://pr25776-c45724e.ngbuilds.io/.

2018-09-20 18:50 UTC, mary-poppins commented
You can preview f688364 at https://pr25776-f688364.ngbuilds.io/.

2018-09-20 21:03 UTC, mary-poppins commented
You can preview 3a7f96a at https://pr25776-3a7f96a.ngbuilds.io/.

2018-09-20 22:06 UTC, mary-poppins commented
You can preview 6bba59a at https://pr25776-6bba59a.ngbuilds.io/.

2018-09-21 18:15 UTC, mary-poppins commented
You can preview f353532 at https://pr25776-f353532.ngbuilds.io/.

2018-09-25 17:38 UTC, jenniferfell commented
File name and page title recommendations: 

* `navigation.json`: Changes here are temporary. Is this easiest if we copy mine (https://github.com/angular/angular/pull/26099)  into your PR?

* `WIP-cli-appdev.md`: Placeholder. This will be deleted when content is correctly integrated into the navigation. 

* `app-design-and-dev.md`: Coming soon. Hmmm....

* `app-dev-file-structure.md`: 
    - Filename: Please rename to just `file-structure.md`
    - Page title: Great as is (Workspace and Project File Structure). Please change to sentence caps per style guide.
    - Nav title: Great as is. (Project File Structure)

* `app-dev-lib-create.md`: 
    - Filename: Please rename to `library-creating.md` or `library-create.md`
    - Page title: Good as is (Creating libraries). Sentence caps. 
    - Nav title: Please change to "Creating libraries" or "Publishing libraries" 

* `app-dev-lib.md:`
    - Filename: Please rename to `library-using.md` or `library-use.md`
    - Page title: Please change to "Using Angular libraries"
    - Nav title: Please change to "Using libraries in apps" or just "Using libraries"

* `app-dev-test.md`: Option 1 is integrate this into testing.md somewhere. Option 2 is keep this separate and position to focus on integration testing, ci, reporting, automation of testing. Future is rewrite testing as its own nav section with children. If option 2, 
    - Filename: Rename to `testing-ci.md` or `testing-automation.md`
    - Page title: Rename to `Continuous integration testing' or something like that
    - Nav title: Rename to something like "Testing - CI" so it can sit next to "Testing".  

* 'deployment.md`: Filename and page title are fine (from v6). Navigation title will be "Deployment", from existing navigation.

2018-09-25 17:55 UTC, jenniferfell commented
* 'app-design-and-dev.md`: 
    - Filename: Please rename to `build.md`
    - Page title: Please rename to "Building and serving Angular apps"
    - Nav title: Please rename to "Building and serving"
Future: I think this will evolve in the next few weeks to be >1 file, but the theme seems to be building apps and serving apps. No current topics in Angular conflict with those names, so they are open to use here without conflicts.

2018-09-25 18:01 UTC, jenniferfell commented
Re fka app-design-and-dev.md content...what about this organization?

H1: Building and serving Angular apps

H2: Configuring application environments
H3: Configure environment-specific defaults
H3: Using environment-specific variables in your app
H3: Configuring target-specific file replacements

H2: Configuring size budgets
H2: Adding project assets
H2: Configuring browser compatibility

H2: Serving from disk
H2: Proxing to a backend server
H3: Rewrite the URL path
H3: Proxy multiple entries
H3: Bypass the proxy
H3: Use corporate proxy

Configure hot module replacement - delete ALL 

Preferred title style is "-ing" such as "Serving from disk" for all.

2018-09-25 18:16 UTC, mary-poppins commented
You can preview 2fd0579 at https://pr25776-2fd0579.ngbuilds.io/.

2018-09-25 18:23 UTC, jenniferfell requested changes
See comments in Conversation thread. Thanks.

2018-09-25 19:44 UTC, mary-poppins commented
You can preview f57c0c1 at https://pr25776-f57c0c1.ngbuilds.io/.

2018-09-25 19:51 UTC, IgorMinar commented on aio/content/guide/app-dev-test.md
> + ng e2e --progress=false
this doesn't work today. suppressing the verbose logging on ci requires more changes to angular.json, which is not very convenient. @hansl has more details.

@hansl it's not unreasonable to make it work, or would this be a problem? could we just pass the flag through to `ng build`?

2018-09-25 20:32 UTC, jenniferfell commented
navigation.json update (transferring this way rather than via commit so that CLA=yes remains yes)

Same as file sent via slack.  To use, remove.txt from suffix. (Github wouldn't upload a .json)

[navigation.json.txt](https://github.com/angular/angular/files/2416961/navigation.json.txt)

2018-09-25 20:39 UTC, jenniferfell commented
bad refs fixed 
[navigation.json.txt](https://github.com/angular/angular/files/2416981/navigation.json.txt)

2018-09-26 20:52 UTC, jenniferfell commented
@jbogarthyde Don't forget to remove WIP-cli-appdev.md

2018-09-26 22:02 UTC, mary-poppins commented
You can preview 91d0c3a at https://pr25776-91d0c3a.ngbuilds.io/.

2018-09-27 01:57 UTC, jenniferfell approved these changes

2018-09-27 02:02 UTC, jenniferfell commented
Sorry, I just noticed that the commit message still describes this as a temp section. Because commit messages are permanent history and go in the change log, please update. Something like "docs: integrate CLI stories with Angular guides". Thanks.

2018-09-27 02:03 UTC, jenniferfell commented
@IgorMinar Aside from the commit message, I think this is ready for your review-requests-approval. Thanks!

2018-09-27 16:04 UTC, mary-poppins commented
You can preview 41247e3 at https://pr25776-41247e3.ngbuilds.io/.

2018-09-27 16:05 UTC, mary-poppins commented
You can preview 9d33364 at https://pr25776-9d33364.ngbuilds.io/.

2018-09-27 16:31 UTC, mary-poppins commented
You can preview a3c2050 at https://pr25776-a3c2050.ngbuilds.io/.

2018-09-27 16:49 UTC, mary-poppins commented
You can preview 45749bb at https://pr25776-45749bb.ngbuilds.io/.

2018-09-27 16:51 UTC, mary-poppins commented
You can preview 5b819ed at https://pr25776-5b819ed.ngbuilds.io/.

2018-09-27 22:07 UTC, IgorMinar approved these changes

2018-09-27 22:34 UTC, closed without merging