docs: update service-worker-getting-started page
angular/angular pull request #25821
Opened 2018-09-05 19:34 UTC by LiadIdan

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
```

## What is the current behavior?

Issue Number: #25783

## What is the new behavior?
Preventing cache collision with the service worker by adding the `-c-1` parameter when starting `http-server`

## Does this PR introduce a breaking change?
```
[x] No
```

## Other information

2018-09-05 19:36 UTC, LiadIdan commented
I signed it!

2018-09-06 11:33 UTC, gkalpak requested changes
Good catch 👍

2018-09-06 11:33 UTC, gkalpak commented on aio/content/guide/service-worker-getting-started.md
> +Because `ng serve` does not work with service workers, you must use a separate HTTP server to test your project locally. You can use any HTTP server. The example below uses the [http-server](https://
As it is now, this sentence makes it sound as if disabling the cache reduces the possibility of conflicts (which is not true). I would change it to something like:

> To reduce the possibility of conflicts and avoid serving stale content, test on a dedicated port and disable caching.

2018-09-06 12:54 UTC, LiadIdan commented on aio/content/guide/service-worker-getting-started.md
> +Because `ng serve` does not work with service workers, you must use a separate HTTP server to test your project locally. You can use any HTTP server. The example below uses the [http-server](https://
@gkalpak, done!

2018-09-06 14:43 UTC, gkalpak approved these changes
LGTM (+ one minor optional suggestion)

2018-09-06 14:43 UTC, gkalpak commented on aio/content/guide/service-worker-getting-started.md
> +http-server -p 8080 -c-1
Not directly related to this PR, but wouldn't it be better to save one step with:

```
http-server -p 8080 -c-1 dist/<project-name>
```

2018-09-06 15:10 UTC, LiadIdan commented on aio/content/guide/service-worker-getting-started.md
> +http-server -p 8080 -c-1
Yeah good point :smiley:

2018-09-06 15:20 UTC, gkalpak requested changes
Almost there 😅

2018-09-06 15:20 UTC, gkalpak commented on aio/content/guide/service-worker-getting-started.md
> +http-server -p 8080 -c-1 dist/<project-name>
Good catch. I had missed this one 😇

2018-09-06 15:20 UTC, gkalpak commented on aio/content/guide/service-worker-getting-started.md
>  cd dist/*project-name*
You can now get rid of the `cd` commands (here and below) and update the corresponding text to not mention that you have to _"change to the directory containing your web app"_.

```diff
-To serve with `http-server`, change to the directory containing your web files and start the web server:
+To serve the directory containing your web files with `http-server`, run the following command:
```

2018-09-06 15:55 UTC, LiadIdan commented
@gkalpak so I need to change all the previous commit messages? if so maybe I'll open a new PR because I don't want to pull the repo to my machine :sweat_smile:

2018-09-06 16:48 UTC, LiadIdan commented
Alright so I'm closing this one and will open a new PR in a bit :smile:

2018-09-06 16:48 UTC, closed without merging