html sanitizer fix to remove comment nodes that are child nodes of unsafe elements
angular/angular pull request #25879
Opened 2018-09-09 06:31 UTC by shinok01

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Input HTML string to be sanitized -
<style></style>

Output returned is encoded comment string like

&lt;!-- something--&gt;

Issue Number: N/A

## What is the new behavior?
Each text node is checked if its opening and closing symbols match the format of an HTML comment.
If they match, then the node is ignored.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X ] No
```

## Other information

2018-09-09 06:34 UTC, shinok01 commented
Covered by Google Corporate CLA ( shinok@)

2018-09-10 07:19 UTC, mihalskiy approved these changes

2018-09-10 17:11 UTC, mhevery requested changes

2018-09-10 17:11 UTC, mhevery commented on packages/core/test/sanitization/html_sanitizer_spec.ts
> +      expect(_sanitizeHtml(defaultDoc, '<style><!-- foobar --></style>')).toEqual('');
what if the text is `<style> before <-- comment --!> after </style>`? i think this would fail.

2018-09-10 17:11 UTC, mhevery commented on packages/core/src/sanitization/html_sanitizer.ts
> +function isCommentNode(el: Node): boolean {
This seems like a very error-prone way to check for comments. It also seems like a fix in a wrong place since it seems to be fixing the symptom rather than the core issue.

2018-09-19 16:15 UTC, benlesh commented
Related issue: https://github.com/angular/angular/issues/26007

2018-10-23 03:36 UTC, IgorMinar approved these changes
lgtm with @mhevery's fixes

2018-10-23 03:37 UTC, mhevery approved these changes

2018-10-23 03:40 UTC, mhevery commented
http://test/OCL:218278875:BASE:218278901:1540264963332:dae4503

2018-10-23 04:35 UTC, mhevery commented
http://test/OCL:218284351:BASE:218284412:1540269329384:9880c966

2018-10-23 15:32 UTC, alxhub commented
This fails g3 presubmit (something called the safevalues_compatibility_test). Kicking back to @shinok01 - please prepare an internal CL with the required updates to g3.

2018-10-25 18:21 UTC, closed without merging