docs(forms): change headings
angular/angular pull request #25900
Opened 2018-09-11 09:00 UTC by georgewilde

Change the headings of the template-driven forms guide page.

This makes the first heading consistent with other guide pages and the menu label reducing confusion to users browsing the guide.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ x] No
```

## Other information

2018-09-12 12:59 UTC, mary-poppins commented
You can preview 0b368d6 at https://pr25900-0b368d6.ngbuilds.io/.

2018-09-17 15:06 UTC, georgewilde commented
Thanks @mary-poppins, it looks good to me. Is there anything else you need me to do on this?

2018-09-17 16:49 UTC, kara approved these changes
LGTM

2018-09-17 17:39 UTC, brandonroberts requested changes

2018-09-17 17:39 UTC, brandonroberts commented on aio/content/guide/forms.md
> +#### Forms
Remove this subheading

2018-09-17 17:39 UTC, brandonroberts commented on aio/content/guide/forms.md
> +#### Template-driven forms
I think this should be changed to "Introduction to Template-driven forms" and moved above "Developing forms requires design skills ...".

2018-09-21 20:33 UTC, georgewilde commented
@brandonroberts I agree with your suggestions and have amended the PR accordingly. Thanks

2018-09-21 20:39 UTC, mary-poppins commented
You can preview b3aaa6a at https://pr25900-b3aaa6a.ngbuilds.io/.

2018-09-24 18:57 UTC, brandonroberts commented on aio/content/guide/forms.md
> +#### Introduction to Template-driven forms
This should be `##` so it adds a TOC item

2018-10-04 09:35 UTC, mary-poppins commented
You can preview c22fdbb at https://pr25900-c22fdbb.ngbuilds.io/.

2018-10-16 22:43 UTC, brandonroberts approved these changes

2018-10-17 03:41 UTC, closed without merging