docs: add Leonardo Zizzamia to GDE resources
angular/angular pull request #25935
Opened 2018-09-12 19:20 UTC by Zizzamia

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
This adds Leonardo Zizzamia to the list of Angular GDEs on the Angular Docs page -> cc @StephenFluin

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-09-13 16:19 UTC, StephenFluin requested changes

2018-09-13 16:19 UTC, StephenFluin commented on aio/content/marketing/contributors.json
> +    "group": "Angular"
This should be 'GDE'

2018-09-16 03:47 UTC, Zizzamia commented on aio/content/marketing/contributors.json
> +    "group": "Angular"
Thank you @StephenFluin

2018-09-17 16:23 UTC, StephenFluin requested changes
Can you squash these two commits?

https://twitter.com/stephenfluin/status/1009904095073718275

2019-01-22 16:04 UTC, brandonroberts requested changes
Update git commit message to `docs: add Leonardo Zizzamia to GDE resources`

2019-01-29 15:43 UTC, brandonroberts commented
@Zizzamia will you rebase on master and update the git commit message?

2019-01-30 16:21 UTC, StephenFluin approved these changes

2019-01-30 19:48 UTC, brandonroberts approved these changes

2019-02-22 18:23 UTC, brandonroberts commented
@Zizzamia will you rebase again to fix the merge conflict? Thanks.

2019-02-25 22:09 UTC, closed without merging