docs: Fix typo in hero-detail.component.spec.ts
angular/angular pull request #25975
Opened 2018-09-15 07:39 UTC by houfu

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information
Missing space between "new" and "Event" (Shows up in "testing" tutorial)

2018-09-16 11:01 UTC, trotyl commented
Please have a look at https://github.com/angular/angular/issues/23370, it's correct.

2018-09-17 18:14 UTC, brandonroberts commented
Thanks for the PR @houfu! Will you update the PR by renaming the `newEvent` function to `createCustomEvent` so its clear its a custom function to return an event?

2018-09-17 18:16 UTC, brandonroberts requested changes

2018-09-17 18:16 UTC, brandonroberts commented on aio/content/examples/testing/src/app/hero/hero-detail.component.spec.ts
> -    page.nameInput.dispatchEvent(newEvent('input')); // tell Angular
Rename the `newEvent` function to `createCustomEvent` here https://github.com/angular/angular/blob/master/aio/content/examples/testing/src/testing/index.ts#L23 so its clear its a custom function to return an event.

2018-09-24 15:17 UTC, houfu commented on aio/content/examples/testing/src/app/hero/hero-detail.component.spec.ts
> -    page.nameInput.dispatchEvent(newEvent('input')); // tell Angular
Thanks, sorry I only noticed the custom function only after submitting the PR. Rather than renaming the function, I suggest explaining it in comment. Something like this:
```typescript
page.nameInput.dispatchEvent(newEvent('input')); // create custom event to tell Angular, alternatively use "page.nameInput.dispatchEvent(new Event('input'));"
```

2018-09-28 23:19 UTC, closed without merging