docs: rewrite attribute binding section of Template Syntax and add example
angular/angular pull request #26004
Opened 2018-09-18 20:33 UTC by kapunahelewong

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Rewrites the Attribute Binding section of Template syntax and adds an example that demonstrates the topics discussed in that section. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

The intention is that when Template Syntax is broken into individual docs that each doc (for the most part) will have its own example.

2018-09-18 20:43 UTC, mary-poppins commented
You can preview a152342 at https://pr26004-a152342.ngbuilds.io/.

2018-09-20 16:49 UTC, mary-poppins commented
You can preview 7e66851 at https://pr26004-7e66851.ngbuilds.io/.

2018-09-28 17:07 UTC, mary-poppins commented
You can preview c549085 at https://pr26004-c549085.ngbuilds.io/.

2018-10-01 12:52 UTC, mary-poppins commented
You can preview b6bd9f4 at https://pr26004-b6bd9f4.ngbuilds.io/.

2018-10-03 17:17 UTC, mary-poppins commented
You can preview 3c5ead7 at https://pr26004-3c5ead7.ngbuilds.io/.

2018-10-18 16:08 UTC, brandonroberts requested changes

2018-10-18 16:08 UTC, brandonroberts commented on aio/content/guide/template-syntax.md
> +consider the `NgClass` directive when
Shouldn't this link to the `NgClass` section in this doc instead of the API reference?

2018-10-18 16:08 UTC, brandonroberts commented on aio/content/guide/template-syntax.md
> +the `NgStyle` directive when setting several inline styles at the same time.
Shouldn't this link to the `NgStyle` section in this doc instead of the API reference?

2018-10-18 16:08 UTC, brandonroberts commented on aio/content/guide/template-syntax.md
> +You can set the value of an attribute directly with an **attribute binding**. This is the only exception to the rule that a binding sets a target property and the only binding that creates and sets a
Remove _can_

2018-10-18 16:08 UTC, brandonroberts commented on aio/content/guide/template-syntax.md
>  You can add and remove CSS class names from an element's `class` attribute with
Remove _can_

2018-10-18 16:08 UTC, brandonroberts commented on aio/content/guide/template-syntax.md
> +the `NgStyle` directive when setting several inline styles at the same time.
Wrap the "Note:" in two asterisks

2018-10-18 16:08 UTC, brandonroberts commented on aio/content/guide/template-syntax.md
> +The template syntax provides specialized one-way bindings for scenarios less well-suited to property binding.
Is there a live example to link to?

2018-10-23 20:31 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +consider the `NgClass` directive when
Fixed. I think this one just got lost in the shuffle.

2018-10-23 20:31 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +the `NgStyle` directive when setting several inline styles at the same time.
Fixed.

2018-10-23 20:32 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +You can set the value of an attribute directly with an **attribute binding**. This is the only exception to the rule that a binding sets a target property and the only binding that creates and sets a
Fixed.

2018-10-23 20:32 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
>  You can add and remove CSS class names from an element's `class` attribute with
Fixed.

2018-10-24 16:59 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +the `NgStyle` directive when setting several inline styles at the same time.
Fixed.

2018-10-24 17:10 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +The template syntax provides specialized one-way bindings for scenarios less well-suited to property binding.
Ah! Thank you! I'd just forgotten to put it in!

2018-10-24 17:22 UTC, mary-poppins commented
You can preview 4923814 at https://pr26004-4923814.ngbuilds.io/.

2018-11-12 20:02 UTC, mary-poppins commented
You can preview 54f6174 at https://pr26004-54f6174.ngbuilds.io/.

2018-11-13 17:09 UTC, mary-poppins commented
You can preview d23c705 at https://pr26004-d23c705.ngbuilds.io/.

2018-11-27 19:07 UTC, mary-poppins commented
You can preview f14eb47 at https://pr26004-f14eb47.ngbuilds.io/.

2018-11-27 19:17 UTC, mary-poppins commented
You can preview e588c5b at https://pr26004-e588c5b.ngbuilds.io/.

2018-11-30 18:04 UTC, mary-poppins commented
You can preview 3b05ac2 at https://pr26004-3b05ac2.ngbuilds.io/.

2019-01-15 19:56 UTC, mary-poppins commented
You can preview abb784e at https://pr26004-abb784e.ngbuilds.io/.

2019-01-16 21:34 UTC, mary-poppins commented
You can preview f37bd31 at https://pr26004-f37bd31.ngbuilds.io/.

2019-01-17 01:06 UTC, mary-poppins commented
You can preview 8988ea9 at https://pr26004-8988ea9.ngbuilds.io/.

2019-03-22 18:57 UTC, mary-poppins commented
You can preview 204996c at https://pr26004-204996c.ngbuilds.io/.

2019-03-26 15:30 UTC, mary-poppins commented
You can preview f8461fb at https://pr26004-f8461fb.ngbuilds.io/.

2019-03-26 19:19 UTC, mary-poppins commented
You can preview 97f738f at https://pr26004-97f738f.ngbuilds.io/.

2019-03-27 20:33 UTC, mary-poppins commented
You can preview c5a66da at https://pr26004-c5a66da.ngbuilds.io/.

2019-03-28 20:34 UTC, mary-poppins commented
You can preview 2548404 at https://pr26004-2548404.ngbuilds.io/.

2019-03-28 21:43 UTC, mary-poppins commented
You can preview 4bb87c4 at https://pr26004-4bb87c4.ngbuilds.io/.

2019-05-08 20:08 UTC, mary-poppins commented
You can preview a752337 at https://pr26004-a752337.ngbuilds.io/.

2019-05-09 13:49 UTC, trotyl commented on aio/content/guide/template-syntax.md
> +You then set the attribute value, using an expression that resolves to a string.
Or remove the attribute when the expression resolves to `null`.

2019-05-23 17:43 UTC, mary-poppins commented
You can preview 90ab2c7 at https://pr26004-90ab2c7.ngbuilds.io/.

2019-06-03 18:47 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +You then set the attribute value, using an expression that resolves to a string.
Fixed. Thank you :)

2019-06-03 18:57 UTC, mary-poppins commented
You can preview 1334993 at https://pr26004-1334993.ngbuilds.io/.

2019-06-13 16:28 UTC, mary-poppins commented
You can preview 9e4c1f6 at https://pr26004-9e4c1f6.ngbuilds.io/.

2019-06-13 18:43 UTC, mary-poppins commented
You can preview ea75193 at https://pr26004-ea75193.ngbuilds.io/.

2019-06-13 19:14 UTC, mary-poppins commented
You can preview e10f240 at https://pr26004-e10f240.ngbuilds.io/.

2019-06-13 20:01 UTC, brandonroberts approved these changes

2019-06-13 20:16 UTC, brandonroberts commented
Caretaker note: The Codefresh job is unrelated and still pending. I am using a global approval

2019-06-14 17:29 UTC, AndrewKushnir commented
@kapunahelewong, it looks like this PR now has a conflict with master branch after merging PR 25561 that also updated .github/CODEOWNERS file. Could you please rebase this PR and resolve conflict(s)? Feel free to add "merge" label back once PR is updated. Thank you.

2019-06-14 18:06 UTC, mary-poppins commented
You can preview 4ad0724 at https://pr26004-4ad0724.ngbuilds.io/.

2019-06-14 19:01 UTC, mary-poppins commented
You can preview 1c11789 at https://pr26004-1c11789.ngbuilds.io/.

2019-06-14 19:23 UTC, closed without merging