WIP: docs(docs-infra): add getting started widgets
angular/angular pull request #26059
Opened 2018-09-21 16:04 UTC by brandonroberts

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2018-09-21 16:09 UTC, mary-poppins commented
You can preview 2b8eaa9 at https://pr26059-2b8eaa9.ngbuilds.io/.

2018-09-21 17:13 UTC, gkalpak reviewed
The tests seem a little off. I didn't look through all of them carefully. The rest looks reasonable, but it would be better if we could see them in action :wink:

Some observations:
- Too much observables. Often seem unnecessary.
- It would be nice if we could get rid of `.template` and derive it from the `.result` HTML. (That would make them more future proof too.)
- If we expect to have more of these components in the future, it might make sense to make them more generic/configuration based. But they are fine for now imo.

2018-09-21 17:13 UTC, gkalpak commented on aio/src/testing/dom-utils.ts
> +  let evt = document.createEvent('CustomEvent');
_let_ --> _const_ :grin:

2018-09-21 17:13 UTC, gkalpak commented on aio/src/testing/dom-utils.ts
> +  return evt;
Why not just `return new CustomEvent(eventName, {bubbles, cancelable});`?

2018-09-21 17:13 UTC, gkalpak commented on aio/src/app/custom-elements/getting-started/property-binding/property-binding.module.ts
> +export class PropertyBindingModule implements WithCustomElementComponent{
Missing whitespace before `{`.

2018-09-21 17:13 UTC, gkalpak commented on aio/src/app/custom-elements/getting-started/ng-if/ng-if.module.ts
> +  providers: [ProductService]
Inconsistent whitespace 😱

2018-09-24 14:44 UTC, brandonroberts commented on aio/src/app/custom-elements/getting-started/ng-for/ng-for.component.ts
> +      <ng-container class="template">&lt;span *ngFor="let product of products">{{ '{' + '{' }}product{{ '}' + '}' }} &lt;/span&gt;</ng-container>
The extra spacing shouldn't be needed here. I'll remove

2018-09-24 14:44 UTC, brandonroberts commented on aio/src/app/custom-elements/getting-started/ng-for/ng-for.component.ts
> +  constructor(private productService: ProductService) {}
The same data and debounce was needed across the ng-for and ng-if components, so I put it in a service to share.

2018-09-24 14:54 UTC, brandonroberts commented on aio/src/app/custom-elements/getting-started/interpolation/interpolation.component.ts
> +      <ng-container class="result"><h1>Welcome to {{ siteName$ | async }}</h1></ng-container>
I was using a function to set the siteName when the input changed, but then I had to mark the component for check. I've changed it to update the value from the template instead.

2018-09-24 14:57 UTC, brandonroberts commented on aio/src/testing/dom-utils.ts
> +  return evt;
This was an example fo creating a custom event from the testing docs, so I used it here. 😑

2018-09-24 15:12 UTC, brandonroberts commented on aio/src/app/custom-elements/getting-started/event-binding/event-binding.component.ts
> +        <input #input (input)="alertText$.next(input.value)" [value]="alertText$ | async">
I updated the template to reflect the data entered

2018-09-24 15:32 UTC, mary-poppins commented
You can preview 9f76b82 at https://pr26059-9f76b82.ngbuilds.io/.

2018-09-24 16:11 UTC, mary-poppins commented
You can preview a4abdcf at https://pr26059-a4abdcf.ngbuilds.io/.

2018-09-24 16:50 UTC, mary-poppins commented
You can preview fb59be2 at https://pr26059-fb59be2.ngbuilds.io/.

2018-09-24 17:28 UTC, mary-poppins commented
You can preview 9f50303 at https://pr26059-9f50303.ngbuilds.io/.

2018-09-24 18:27 UTC, brandonroberts commented
@gkalpak You can see the widgets on the `/tutorial` page temporarily. I will remove them before the PR lands.

2018-09-24 18:28 UTC, mary-poppins commented
You can preview 34bddba at https://pr26059-34bddba.ngbuilds.io/.

2018-09-24 18:30 UTC, mary-poppins commented
You can preview 5db11b0 at https://pr26059-5db11b0.ngbuilds.io/.

2018-09-25 09:19 UTC, gkalpak requested changes
BTW, I would consider changing all widget selectors to `...-gs-...` (instead of `...-getting-started-...` for consistency. (The directory name should be a strong enough hint as to what `gs` stands for.)

2018-09-25 09:19 UTC, gkalpak commented on aio/src/app/custom-elements/getting-started/ng-for/ng-for.component.ts
> +          <input #input (input)="productsData$.next(input.value)" [value]="productsData$ | async">
The template implies that `products` is a property on the component. I think it would be more consistent with the other widgets if this also followed the `products = <input>` (or `products = [<input>]`) format.

2018-09-25 09:19 UTC, gkalpak commented on aio/src/app/custom-elements/getting-started/ng-for/ng-for.component.ts
> +      flex-direction: row;
Nit: This is redundant (since it is the default).

2018-09-25 09:19 UTC, gkalpak commented on aio/src/app/custom-elements/getting-started/products.ts
> +export const PRODUCT_DATA = { products: ['Shoes', 'Phones'] };
This file is unused (or did I miss something?).

2018-09-25 09:19 UTC, gkalpak commented on aio/src/app/app.module.ts
> +    OverlayModule,
What is this for?

2018-09-25 09:19 UTC, gkalpak commented on aio/src/testing/dom-utils.ts
> +}
Playing devils advocate [to myself][1]:
While `CustomEvent` is supported in almost all major browsers, it cannot be used as a constructor on IE 😒

Since it is a tiny change, let's make this code IE-safe (for those poor souls still doing dev on IE 😛).
See the helper we are using in [@angular/elements][2]. (Feel free to either use it as is, or switch to `createEvent()` for all browsers (which is deprecated but 🤷‍♂️).)

[1]: https://github.com/angular/angular/pull/26059#discussion_r219564301
[2]: https://github.com/angular/angular/blob/cf095d982dec9fe9bfd66d3df6eb4fe3d4034dd9/packages/elements/src/utils.ts#L60-L72

2018-09-25 09:19 UTC, gkalpak commented on aio/src/app/custom-elements/getting-started/ng-if/ng-if.component.ts
> +      <ng-container class="result"><p *ngIf="(products$ | async)?.length > 0">We still have products available.</p></ng-container>
I was looking at this again, and I feel it is overly complicated for an `ngIf` demonstration. Why not just use a checkbox to switch `ngIf` to true/false?

2018-09-25 09:36 UTC, gkalpak commented
BTW, you can add the widgets in [test.html][1] (for showcase/review purposes).

[1]: https://github.com/angular/angular/blob/master/aio/content/marketing/test.html

2018-09-25 16:16 UTC, brandonroberts commented on aio/src/app/custom-elements/getting-started/ng-if/ng-if.component.ts
> +      <ng-container class="result"><p *ngIf="(products$ | async)?.length > 0">We still have products available.</p></ng-container>
That is the example Stephen has for demonstrating ngIf. It may get changed later based on feedback.

2018-09-25 16:21 UTC, brandonroberts commented on aio/src/app/app.module.ts
> +    OverlayModule,
Its needed for the tooltip that displayed when the JSON in invalid. I believe Angular Material needs to be at least version `6.1.x` to lazy load the OverlayModule.

2018-09-25 16:58 UTC, mary-poppins commented
You can preview 536d2fa at https://pr26059-536d2fa.ngbuilds.io/.

2018-09-25 17:04 UTC, gkalpak commented on aio/src/app/app.module.ts
> +    OverlayModule,
So, importing `MatTooltipModule` is not enough? That's weird. Is it because we lazy-load `MatTooltipModule`?

2018-09-25 17:05 UTC, gkalpak commented on aio/src/app/custom-elements/getting-started/ng-if/ng-if.component.ts
> +      <ng-container class="result"><p *ngIf="(products$ | async)?.length > 0">We still have products available.</p></ng-container>
Here is my early feedback for @StephenFluin: This example is unnecessary complicated for showcasing `ngIf` 😛

2018-09-25 17:06 UTC, brandonroberts commented on aio/src/app/app.module.ts
> +    OverlayModule,
Its not enough to import `MatTooltipModule`. It throws an error with the `Overlay` provider being missing.

2018-09-25 17:15 UTC, brandonroberts commented on aio/src/app/app.module.ts
> +    OverlayModule,
Misunderstood. Yes its because `MatTooltipModule` is lazy loaded.

2018-09-25 19:37 UTC, mary-poppins commented
You can preview 29fcf4c at https://pr26059-29fcf4c.ngbuilds.io/.

2018-09-26 12:55 UTC, brandonroberts commented
@gkalpak will you take another look?

2018-09-26 15:02 UTC, gkalpak commented on aio/src/app/custom-elements/getting-started/ng-if/ng-if.component.ts
> +          data = '<input #input (input)="productsData$.next(input.value)" [value]="productsData$ | async">';
No need to have quotes around the input here (since there is no indication that `data` is a string).
Furthermore, `data` is a little confusing, because it is not mentioned in the template. I think it would be better to have:

```html
products = <input ... />
```

...where input will have a value of `["obj 1", "obj 2"]`.
(You can still `JSON.parse` a stringified array, similar to how you parse the whole object now.)

2018-09-26 18:22 UTC, gkalpak approved these changes
A couple of last comments (plus the failing CI). Otherwise LGTM :grin:

2018-09-26 19:06 UTC, mary-poppins commented
You can preview 3e8c877 at https://pr26059-3e8c877.ngbuilds.io/.

2018-09-26 20:04 UTC, brandonroberts commented
@IgorMinar will you provide a review/approval on this? It matched *testing* because of the folder in aio.

2018-09-26 20:07 UTC, mary-poppins commented
You can preview bff1e04 at https://pr26059-bff1e04.ngbuilds.io/.

2018-09-27 11:14 UTC, gkalpak commented
The Travis failures are valid. I am not sure where the increase in main and runtime bundles came from 😕

2018-09-27 16:44 UTC, gkalpak commented
IIRC, similar increase happened before upgrading material. It would be good no pinpoint which commit introduced the change and understand why.

2018-09-28 16:57 UTC, mary-poppins commented
You can preview 53ecb63 at https://pr26059-53ecb63.ngbuilds.io/.

2018-09-28 17:00 UTC, mary-poppins commented
You can preview 8b64ba5 at https://pr26059-8b64ba5.ngbuilds.io/.

2018-10-05 13:07 UTC, mary-poppins commented
You can preview 9418031 at https://pr26059-9418031.ngbuilds.io/.

2018-10-05 19:58 UTC, IgorMinar requested changes
So far we tried hard to make all the highly visible pages on angular.io look good on mobile, but the table layout in the widgets is not mobile friendly. Can you make the table turn to row layout instead of column layout for narrow viewports? thanks

2018-10-05 19:58 UTC, IgorMinar commented on aio/scripts/_payload-limits.json
> +        "main": 496276,
ouch.. this is a lot. do we know what caused this?

2018-10-05 19:58 UTC, IgorMinar commented on aio/src/app/custom-elements/code/code-tabs.module.ts
> +import { MatTabsModule } from '@angular/material/tabs';
why this change? does it have any impact on code size? it shouldn't have.

2018-10-05 19:58 UTC, IgorMinar commented on aio/src/app/custom-elements/code/code.module.ts
> +import { MatSnackBarModule } from '@angular/material/snack-bar';
same as above..

2018-10-08 21:27 UTC, brandonroberts commented on aio/scripts/_payload-limits.json
> +        "main": 496276,
From using source-map-explorer, the bulk of the increase in main comes from the CDK in material. Everything else stayed relatively the same. CDK included went from 20kb to 31kb on its own. Source map explorer images attached. This is with Angular Material 7 RC0

![image](https://user-images.githubusercontent.com/42211/46634542-cfc03780-cb16-11e8-8596-60c782c9f71e.png)


![image](https://user-images.githubusercontent.com/42211/46634514-bfa85800-cb16-11e8-8420-7117efb27d84.png)

2018-10-08 21:32 UTC, mary-poppins commented
You can preview 170e754 at https://pr26059-170e754.ngbuilds.io/.

2018-10-08 21:34 UTC, mary-poppins commented
You can preview 88efd64 at https://pr26059-88efd64.ngbuilds.io/.

2018-10-08 21:41 UTC, mary-poppins commented
You can preview 6276651 at https://pr26059-6276651.ngbuilds.io/.

2018-10-12 21:22 UTC, jelbourn commented on aio/scripts/_payload-limits.json
> +        "main": 496276,
I took a look, and I believe the majority of the increase is from adding `MatTooltip` to aio, which was not previously used. The tooltip uses the `AriaDescriber` service from `cdk/a11y`, which most other components do not use.

2018-10-13 12:48 UTC, brandonroberts commented on aio/scripts/_payload-limits.json
> +        "main": 496276,
@gkalpak Yes, it is being loaded lazily. Could something else be pulling in a11y that was already in main that's causing the increase @jelbourn ?

2018-10-15 16:58 UTC, jelbourn commented on aio/scripts/_payload-limits.json
> +        "main": 496276,
If I make a change that **only** updates the cdk/material version without changing any other code locally, the size doesn't go up by that same amount.

2018-10-15 17:47 UTC, mary-poppins commented
You can preview 6a83958 at https://pr26059-6a83958.ngbuilds.io/.

2018-10-15 17:48 UTC, brandonroberts commented on aio/scripts/_payload-limits.json
> +        "main": 496276,
I rebased on master that's already been bumped to Material RC1 and it only increased the main bundle from 494475kb to 499953kb, which is within acceptable range.

2018-10-15 19:29 UTC, mary-poppins commented
You can preview fd4f7d3 at https://pr26059-fd4f7d3.ngbuilds.io/.

2018-10-15 19:53 UTC, brandonroberts commented
@IgorMinar this is ready for another review.

2018-10-15 19:58 UTC, mary-poppins commented
You can preview 0a772c0 at https://pr26059-0a772c0.ngbuilds.io/.

2018-10-19 13:04 UTC, mary-poppins commented
You can preview d98e78e at https://pr26059-d98e78e.ngbuilds.io/.

2018-10-24 19:42 UTC, mary-poppins commented
You can preview f25f968 at https://pr26059-f25f968.ngbuilds.io/.

2018-10-25 12:17 UTC, mary-poppins commented
You can preview de01285 at https://pr26059-de01285.ngbuilds.io/.

2018-11-02 13:29 UTC, IgorMinar approved these changes
looks good now on mobile. thanks!

I'm not happy about the size in increase, but we'll investigate that more once we switch to ivy.

Can you please:
- rebase on master
- squash into a single commit
- prefix the commit with `feat(docs-infra): ` ("docs(docs-infra)" means documentation for docs-infrastruture).

thanks!

2018-11-02 14:08 UTC, mary-poppins commented
You can preview 4f2014d at https://pr26059-4f2014d.ngbuilds.io/.

2018-11-02 17:36 UTC, closed without merging