fix(ivy): objects like ElementRef should not use a special injection fn
angular/angular pull request #26064
Opened 2018-09-21 23:10 UTC by kara

2018-09-21 23:17 UTC, mary-poppins commented
You can preview 4338a5f at https://pr26064-4338a5f.ngbuilds.io/.

2018-09-21 23:27 UTC, mary-poppins commented
You can preview 14f8102 at https://pr26064-14f8102.ngbuilds.io/.

2018-09-22 00:57 UTC, mary-poppins commented
You can preview 10230b7 at https://pr26064-10230b7.ngbuilds.io/.

2018-09-22 01:03 UTC, mary-poppins commented
You can preview c1ce2d1 at https://pr26064-c1ce2d1.ngbuilds.io/.

2018-09-22 01:12 UTC, mary-poppins commented
You can preview f8141d4 at https://pr26064-f8141d4.ngbuilds.io/.

2018-09-22 01:30 UTC, mary-poppins commented
You can preview b408b72 at https://pr26064-b408b72.ngbuilds.io/.

2018-09-22 01:33 UTC, mary-poppins commented
You can preview 0a83be4 at https://pr26064-0a83be4.ngbuilds.io/.

2018-09-22 01:38 UTC, mary-poppins commented
You can preview 0a787e8 at https://pr26064-0a787e8.ngbuilds.io/.

2018-09-22 01:49 UTC, mary-poppins commented
You can preview 5ee4b83 at https://pr26064-5ee4b83.ngbuilds.io/.

2018-09-22 01:59 UTC, mary-poppins commented
You can preview 50b1d68 at https://pr26064-50b1d68.ngbuilds.io/.

2018-09-22 02:54 UTC, mary-poppins commented
You can preview 141daad at https://pr26064-141daad.ngbuilds.io/.

2018-09-22 10:05 UTC, JoostK commented on packages/core/src/change_detection/change_detector_ref.ts
> +      (() => ChangeDetectorRef)|null = CHANGE_DETECTOR_REF_FACTORY__PRE_NGCC__;
I would expect ngcc to replace this reference with `CHANGE_DETECTOR_REF_FACTORY__POST_NGCC__` , which would not be available now as it isn't imported.

2018-09-22 15:06 UTC, mhevery requested changes
- Need to move `*__POST_NGCC__` into `ivy_switch.ts` otherwise all ivy code will need `enableIvyInjectableFactories()`
- Consider removing these so that compiler has no special logic for any of the tokens:
  - `injectInjector()`
  - `injectRenderer2()`
  - `injectAttribute()`
- Introduce `AbstractType` so that we can remove all of the `as any`
- `NG_ELEMENT_ID` must be closure safe.

2018-09-22 15:39 UTC, trotyl commented on packages/core/test/render3/change_detection_spec.ts
> +          factory: () => myComp = new MyComp(directiveInject(ChangeDetectorRef as any)),
But in any circumstance `AbstractType | Type` (or `AbstractType | ConcreteType`) would just be `AbstractType`, in current TypeScript concepts there's no way to make some type abstract-only, and then `Type` is useless anywhere.

2018-09-22 18:04 UTC, kara commented on packages/compiler/src/render3/r3_factory.ts
>        return o.importExpr(R3.injectAttribute).callFn([dep.token]);
This sounds good, but let's push to another PR?

2018-09-22 22:46 UTC, mary-poppins commented
You can preview 1243e35 at https://pr26064-1243e35.ngbuilds.io/.

2018-09-23 00:04 UTC, mary-poppins commented
You can preview a0077dd at https://pr26064-a0077dd.ngbuilds.io/.

2018-09-23 00:05 UTC, kara commented on packages/core/test/render3/change_detection_spec.ts
> +          factory: () => myComp = new MyComp(directiveInject(ChangeDetectorRef as any)),
@mhevery Added to JIRA so we don't forget about this.

2018-09-23 00:50 UTC, mary-poppins commented
You can preview eb83b4a at https://pr26064-eb83b4a.ngbuilds.io/.

2018-09-23 02:29 UTC, mary-poppins commented
You can preview 5247c84 at https://pr26064-5247c84.ngbuilds.io/.

2018-09-25 05:07 UTC, mary-poppins commented
You can preview b579f91 at https://pr26064-b579f91.ngbuilds.io/.

2018-09-25 05:11 UTC, mary-poppins commented
You can preview d7b4959 at https://pr26064-d7b4959.ngbuilds.io/.

2018-09-25 06:41 UTC, mary-poppins commented
You can preview 87af032 at https://pr26064-87af032.ngbuilds.io/.

2018-09-25 08:32 UTC, mary-poppins commented
You can preview 89305ed at https://pr26064-89305ed.ngbuilds.io/.

2018-09-25 17:27 UTC, mary-poppins commented
You can preview 3ed2a11 at https://pr26064-3ed2a11.ngbuilds.io/.

2018-09-25 17:32 UTC, mary-poppins commented
You can preview bcdd7f2 at https://pr26064-bcdd7f2.ngbuilds.io/.

2018-09-25 17:45 UTC, kara commented on packages/core/BUILD.bazel
> +    name = "ivy_switch_runtime",
The compiler switch relies on `jit/directive`  <-- `jit/environment` <--  `render3/index`. So any file that has imports/exports in `render3/index.ts` (most render3 files) is importing into `ivy_switch`. Separating it out into its own file gives us a bit more flexibility.

2018-09-25 18:53 UTC, mhevery approved these changes

2018-09-25 19:03 UTC, kara commented
[presubmit](https://test.corp.google.com/ui#id=OCL:214479273:BASE:214479319:1537902106784:a96124c9)

2018-09-25 19:52 UTC, closed without merging

2018-09-25 19:58 UTC, JoostK commented on packages/core/test/render3/common_integration_spec.ts
> +                  templateRefExtractor(TemplateRef, ElementRef));
@kara is the compiler now expected to generate this call as such? Does that mean that this will be the actual public API for this instruction (in which case we leak `typeof viewEngine_TemplateRef` etc in its signature)? I don't see why we are passing the constructors here, or is this only temporary for now?

Sorry for all the questions, I am just trying to understand why this was changed as such.

2018-09-25 21:11 UTC, mhevery commented on packages/core/test/render3/common_integration_spec.ts
> +                  templateRefExtractor(TemplateRef, ElementRef));
Hmm... I don't think that is right. Good catch, I think we should revert this back. I will follow up with @kara

2018-09-26 00:14 UTC, kara commented on packages/core/test/render3/common_integration_spec.ts
> +                  templateRefExtractor(TemplateRef, ElementRef));
@JosstK The constructors are temporary and should only be necessary to avoid circular deps until we can remove some of the switch code. We shouldn't be leaking anything since `TemplateRef` and `ElementRef` from `ViewEngine` are already public API, but the extra codegen isn't ideal (even if temporary), so we'll be exporting a wrapper function in a follow-up.