feat: Updated RxJS to ^6.3.0
angular/angular pull request #26087
Opened 2018-09-24 18:44 UTC by benlesh

Updates RxJS to latest minor, 6.3.0 as a requirement

2018-09-24 20:11 UTC, IgorMinar requested changes
you'll need to update one or more yarn.lock files as well - see CI failures.

2018-09-24 20:11 UTC, IgorMinar commented on yarn.lock
> +rxjs@^6.3.0:
I'd expect that we'd also drop the current version. Does anyone still depend on it?

2018-09-24 21:06 UTC, mary-poppins commented
You can preview ce3f1fd at https://pr26087-ce3f1fd.ngbuilds.io/.

2018-09-24 22:41 UTC, mary-poppins commented
You can preview e4ae1e6 at https://pr26087-e4ae1e6.ngbuilds.io/.

2018-09-24 23:17 UTC, mary-poppins commented
You can preview be2cc80 at https://pr26087-be2cc80.ngbuilds.io/.

2018-09-25 00:18 UTC, mary-poppins commented
You can preview 582d248 at https://pr26087-582d248.ngbuilds.io/.

2018-09-25 05:49 UTC, gkalpak commented on integration/bazel/package.json
> +    "rxjs": "^6.3.0",
:thinking: Was this change intentional?

2018-09-25 05:49 UTC, gkalpak commented on integration/hello_world__systemjs_umd/package.json
> +    "@angular/core": "file:../../dist/packages-dist/core",
:100:

2018-09-25 05:49 UTC, gkalpak commented on integration/hello_world__systemjs_umd/package.json
> +    "rxjs": "^6.3.0",
:thinking: Was this change intentional?

2018-09-25 06:01 UTC, trotyl commented
Should update `peerDependencies` in `/packages/core/package.json` as well, per https://github.com/angular/angular/issues/25225.

2018-09-26 00:35 UTC, mary-poppins commented
You can preview 52a56e0 at https://pr26087-52a56e0.ngbuilds.io/.

2018-09-26 16:50 UTC, mary-poppins commented
You can preview f2ce857 at https://pr26087-f2ce857.ngbuilds.io/.

2018-09-26 17:31 UTC, mary-poppins commented
You can preview 886d9b8 at https://pr26087-886d9b8.ngbuilds.io/.

2018-09-26 17:54 UTC, mary-poppins commented
You can preview 1b1fbd7 at https://pr26087-1b1fbd7.ngbuilds.io/.

2018-09-26 18:10 UTC, mary-poppins commented
You can preview 6e001f1 at https://pr26087-6e001f1.ngbuilds.io/.

2018-09-26 19:30 UTC, mary-poppins commented
You can preview ddb6dca at https://pr26087-ddb6dca.ngbuilds.io/.

2018-09-26 20:54 UTC, IgorMinar commented on integration/hello_world__systemjs_umd/package.json
> +    "rxjs": "^6.3.0",
no. this was not supposed to have changed.

2018-09-26 22:19 UTC, mary-poppins commented
You can preview 3ab46a7 at https://pr26087-3ab46a7.ngbuilds.io/.

2018-09-26 22:29 UTC, benlesh commented on integration/hello_world__systemjs_umd/package.json
> +    "rxjs": "^6.3.0",
Thanks, yeah, I ran `yarn upgrade` in here. Reverted.

2018-09-26 22:36 UTC, mary-poppins commented
You can preview 2ffbab4 at https://pr26087-2ffbab4.ngbuilds.io/.

2018-09-26 22:58 UTC, mary-poppins commented
You can preview 50f0e1a at https://pr26087-50f0e1a.ngbuilds.io/.

2018-09-26 23:32 UTC, IgorMinar approved these changes

2018-09-27 00:02 UTC, closed without merging

2018-09-27 00:08 UTC, mary-poppins commented
You can preview 3c33605 at https://pr26087-3c33605.ngbuilds.io/.