feat(ivy): enhance [style] and [class] bindings to be animation aware
angular/angular pull request #26096
Opened 2018-09-25 07:36 UTC by matsko

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2018-09-25 07:43 UTC, mary-poppins commented
You can preview 98fdf28 at https://pr26096-98fdf28.ngbuilds.io/.

2018-09-26 01:08 UTC, mary-poppins commented
You can preview c45f1d0 at https://pr26096-c45f1d0.ngbuilds.io/.

2018-09-26 17:18 UTC, mary-poppins commented
You can preview 647b2f0 at https://pr26096-647b2f0.ngbuilds.io/.

2018-09-26 17:36 UTC, mary-poppins commented
You can preview b8327b5 at https://pr26096-b8327b5.ngbuilds.io/.

2018-09-27 05:07 UTC, mary-poppins commented
You can preview 213646d at https://pr26096-213646d.ngbuilds.io/.

2018-09-27 05:10 UTC, mary-poppins commented
You can preview 02a5e45 at https://pr26096-02a5e45.ngbuilds.io/.

2018-09-27 05:14 UTC, mary-poppins commented
You can preview b8d098f at https://pr26096-b8d098f.ngbuilds.io/.

2018-09-27 06:32 UTC, mary-poppins commented
You can preview 19d06ab at https://pr26096-19d06ab.ngbuilds.io/.

2018-09-27 07:44 UTC, mary-poppins commented
You can preview 6cc7d39 at https://pr26096-6cc7d39.ngbuilds.io/.

2018-09-27 08:00 UTC, mary-poppins commented
You can preview 4e668f5 at https://pr26096-4e668f5.ngbuilds.io/.

2018-09-27 17:33 UTC, mary-poppins commented
You can preview 535ae85 at https://pr26096-535ae85.ngbuilds.io/.

2018-10-03 21:19 UTC, mary-poppins commented
You can preview 7f9c876 at https://pr26096-7f9c876.ngbuilds.io/.

2018-10-03 22:20 UTC, mary-poppins commented
You can preview 9b73c8b at https://pr26096-9b73c8b.ngbuilds.io/.

2018-10-03 22:50 UTC, mary-poppins commented
You can preview 3f13dec at https://pr26096-3f13dec.ngbuilds.io/.

2018-10-03 22:57 UTC, mary-poppins commented
You can preview eabcec5 at https://pr26096-eabcec5.ngbuilds.io/.

2018-10-03 23:08 UTC, mary-poppins commented
You can preview 3e811eb at https://pr26096-3e811eb.ngbuilds.io/.

2018-10-03 23:11 UTC, mary-poppins commented
You can preview c56bcfc at https://pr26096-c56bcfc.ngbuilds.io/.

2018-10-04 00:08 UTC, mary-poppins commented
You can preview 774e5be at https://pr26096-774e5be.ngbuilds.io/.

2018-10-04 04:47 UTC, mhevery requested changes
All public APIs need to have docs. (Not clear which methods are intended to be public)

Please document the methods. It is not clear what they do. The comments should say what it does, how it does it, and why its done that way (or what problem does it solve).

What I am missing (and I assume that others will to) is how all of these pieces fit together. Could we get together and discuss this? Perhaps create a animations.md file explaining how these things work and how they are intended to be used.

2018-10-04 04:47 UTC, mhevery commented on packages/core/src/render3/styling/player_factory.ts
> +export function createPlayerFactory<T>(
This is public interface, needs detail docs

2018-10-04 04:47 UTC, mhevery commented on packages/core/src/render3/styling/player_factory.ts
> +export function createPlayerFactory<T>(
Wondering if `bindPlayerFactory` would be a better name. You are not actually creating a player here, just wrapping it up in a bundle. Also maybe change `PlayerFactory` to `BoundPlayerFactory`

2018-10-04 04:47 UTC, mhevery commented on packages/core/src/render3/interfaces/player.ts
> +export interface PlayerBuilder extends BindingStore {
Needs public doc. What is the difference between `PlayerBuilder` and `BindingStore`. Are these public docs? Can this be simplified? And how is the `PlayerBuilder` and `PlayerFactory` related?

2018-10-04 04:47 UTC, mhevery commented on packages/core/src/render3/players.ts
> +export function addPlayer(
Needs public doc

2018-10-04 04:47 UTC, mhevery commented on packages/core/src/render3/players.ts
> +export function getPlayers(ref: ComponentInstance | DirectiveInstance | HTMLElement): Player[] {
Needs public doc

2018-10-15 22:59 UTC, matsko commented on packages/core/src/render3/interfaces/player.ts
> +export interface PlayerBuilder extends BindingStore {
This is private

2018-10-15 23:03 UTC, mary-poppins commented
You can preview 14e9d25 at https://pr26096-14e9d25.ngbuilds.io/.

2018-10-16 20:39 UTC, mhevery approved these changes

2018-10-16 20:42 UTC, mary-poppins commented
You can preview 5cf81d0 at https://pr26096-5cf81d0.ngbuilds.io/.

2018-10-16 21:15 UTC, mary-poppins commented
You can preview 591d0fa at https://pr26096-591d0fa.ngbuilds.io/.

2018-10-17 03:40 UTC, closed without merging