Update HttpClient API documentation
angular/angular pull request #26143
Opened 2018-09-27 16:05 UTC by chembu

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The existing documentation is not detailed enough.
Issue Number: N/A

## What is the new behavior?
Added details on each HTTP client API calls.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-09-27 16:13 UTC, mary-poppins commented
You can preview a42df9f at https://pr26143-a42df9f.ngbuilds.io/.

2018-09-28 16:49 UTC, mary-poppins commented
You can preview 8d50b06 at https://pr26143-8d50b06.ngbuilds.io/.

2018-11-16 06:02 UTC, jenniferfell commented
Internal link: https://angular-team.atlassian.net/browse/DOCS-131

2018-12-07 20:10 UTC, CaerusKaru requested changes
Mostly good. A few nits and some things that need to be updated

2018-12-07 20:10 UTC, CaerusKaru commented on packages/common/http/src/client.ts
> +   * Sends an HTTP request and returns the response as an observable stream of HTTP events.
Not sure you need to include observable here, but if you do, it should be capitalized as `Observable` (here and below)

2018-12-07 20:10 UTC, CaerusKaru commented on packages/common/http/src/client.ts
> +   *   * An `observe` value of events returns an observable of the raw `HttpEvent` stream, including progress events by default.
Should these values be in quotes, ie "events" instead of events?

2018-12-07 20:10 UTC, CaerusKaru commented on packages/common/http/src/client.ts
> +   * Constructs an observable that, when subscribed, cause the configured
/s/cause/causes

2018-12-07 20:10 UTC, CaerusKaru commented on packages/common/http/src/client.ts
> +   * javascript file and tricks the browser to process the requests.The endpoint API must support
Missing space after "requests."

2018-12-07 20:10 UTC, CaerusKaru commented on packages/common/http/src/client.ts
> +   * `OPTIONS` request to execute on the server. The method allows client
"the client"?

2018-12-07 20:10 UTC, CaerusKaru commented on packages/common/http/src/client.ts
> +   * with new set of values.
"a new set of values"

2018-12-14 19:24 UTC, chembu commented on packages/common/http/src/client.ts
> + *  return this.httpClient.request("GET", this.heroesUrl, {responseType:"json",params});
@CaerusKaru  : I was trying to show an example of using HTTP request method.  The HTTP GET method has an example documented in HTTP guide.

2018-12-16 08:42 UTC, trotyl commented on packages/common/http/src/client.ts
> + *  return this.httpClient.request("GET", this.heroesUrl, {responseType:"json",params});
Should all string literals be in single quote for consistency?

2019-01-09 00:09 UTC, benlesh submitted a review, later dismissed
First: Apologies for the late review.

Overall, there are some good changes in here, started to comment on individual things, but I didn't want to pepper this with too many comments, because it's the same comment everywhere:

Can you please revert any change where you removed the symbol/type from the sentence? For example:

`Returns an \`Observable\` of \`HttpEvent\`s where the body is an \`ArrayBuffer\`` should stay that way. Changing it to `Returns an \`Observable\` of http events where the body is an array buffer` is less precise.

This was done in a lot of places in this PR. If we can just revert those changes, we can have another look and try to get the good stuff in. :)

2019-01-09 00:09 UTC, benlesh commented on packages/common/http/src/client.ts
> +   * @return  An `Observable` of the response, with the response body as an array buffer.
Please revert. This does indeed return an `Observable<ArrayBuffer>`, so I think saying `ArrayBuffer` here is more precise. :)

2019-01-09 00:09 UTC, benlesh commented on packages/common/http/src/client.ts
> +   * @return An `Observable` of the response, with the response body as a blob.
`Blob` was correct, here.

2019-01-28 18:15 UTC, mary-poppins commented
You can preview b87919a at https://pr26143-b87919a.ngbuilds.io/.

2019-02-14 16:43 UTC, mary-poppins commented
You can preview 0bafa59 at https://pr26143-0bafa59.ngbuilds.io/.

2019-02-21 19:02 UTC, mary-poppins commented
You can preview ea11a71 at https://pr26143-ea11a71.ngbuilds.io/.

2019-02-21 19:29 UTC, mary-poppins commented
You can preview d4a8158 at https://pr26143-d4a8158.ngbuilds.io/.

2019-02-22 02:05 UTC, IgorMinar commented
I rebased and squested this PR

2019-02-22 02:05 UTC, IgorMinar commented
and force-pushed to this git branch (@chembu please update your local branch if you need to work on this branch more)

2019-02-22 02:08 UTC, IgorMinar commented
http://test/OCL:235109220:BASE:235109252:1550801301360:c4c1b462

2019-02-22 02:09 UTC, mary-poppins commented
You can preview eca16f0 at https://pr26143-eca16f0.ngbuilds.io/.

2019-02-22 04:57 UTC, IgorMinar approved these changes
I took a cursory look over this and it seems much better than what we have. It could still use more polish but we can do that in the follow-up PRs.

2019-02-22 04:57 UTC, IgorMinar commented
thanks @chembu !

2019-02-22 04:57 UTC, closed without merging

2019-02-22 04:58 UTC, mary-poppins commented
You can preview a440a6c at https://pr26143-a440a6c.ngbuilds.io/.