feat(ivy): compiler support to generate QUERY_READ_FROM_NODE calls
angular/angular pull request #26171
Opened 2018-09-29 00:37 UTC by AndrewKushnir

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
```

## What is the current behavior?
Currently when we generate the code for View and Content Queries which use local refs, we do not append QUERY_READ_FROM_NODE as an argument.

## What is the new behavior?
This PR adds the necessary compiler support to add QUERY_READ_FROM_NODE as an argument when queries use local refs.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2018-09-29 00:45 UTC, mary-poppins commented
You can preview 1f053a2 at https://pr26171-1f053a2.ngbuilds.io/.

2018-09-29 05:06 UTC, mhevery requested changes
I fixed the `as any` here 3868eca7fc

I have update FW-496 with more details as to what needs to be done.

The reason why we have the symbols bellow is because we wanted the query system to be tree shakable. For this reason we created these symbols for each case of query and each of theses symbols would pull in different part of the code base.
- `QUERY_READ_ELEMENT_REF` 
- `QUERY_READ_TEMPLATE_REF`
- `QUERY_READ_CONTAINER_REF`
- `QUERY_READ_FROM_NODE`

However, we have since solved this issue by patching `__NG_ELEMENT_ID__` on the type which allows us to only pull in the creation code for a type if the type is actually referenced. Example: https://github.com/angular/angular/blob/2ad1bb4eb905b7d4982e6f82eb17da8d860a67e2/packages/core/src/linker/element_ref.ts#L52-L53

The `__NG_ELEMENT_ID__` points to `null` if in ViewEngine but points to `createElementRef` in Ivy mode. This makes `QUERY_READ_ELEMENT_REF` unnecessary since all it does is invoke `createElementRef`.

## Proposal

Completely remove all `QUERY_READ_*` symbols and change the implementation of `query` such that it can perform all of its duties without the need to reference any special token such as `ElementRef`/`createElementRef` which would preserve the tree shaking but simplify the public API surface of the not having the compiler understand these cases. This way the compiler will always generate the same format of code for the query. (simplification for the win)

2018-10-02 00:33 UTC, AndrewKushnir commented on packages/compiler-cli/test/compliance/r3_compiler_compliance_spec.ts
> +              @ViewChild('myRef') myRef: any;
We have a basic test case above that check reads with directives. However, we may need to add more tests to check different combinations of read args like `@ViewChildren(SomeDirectiveType, {read: ElementRef})`.

2018-10-02 00:35 UTC, mary-poppins commented
You can preview f9701a2 at https://pr26171-f9701a2.ngbuilds.io/.

2018-10-02 00:38 UTC, AndrewKushnir commented
@mhevery thanks for the review! I've updated this PR according to your proposal. Thank you.

2018-10-02 04:06 UTC, mary-poppins commented
You can preview 5c2824b at https://pr26171-5c2824b.ngbuilds.io/.

2018-10-02 04:14 UTC, mhevery requested changes

2018-10-02 04:14 UTC, mhevery commented on packages/compiler/src/render3/view/util.ts
> +      // (for ex. 'ref, ref1, ..., refN'), thus we exract individual refs and store them
`exract` => `extract`

2018-10-02 04:14 UTC, mhevery commented on packages/core/src/render3/query.ts
> +  if (read === ViewEngine_ElementRef || read === ViewEngine_TemplateRef ||
Is it is written right now the reference to `ViewEngine_ViewContainerRef ` will prevent tree shaking from happening. So this code needs to be written in a way so that it is `ViewEngine_ViewContainerRef ` agnostic. Something like:
```typescript
const fnOrId =(read as any)[NG_ELEMENT_ID]
if (typeof fnOrId == 'function') {
  return fnOnId();
} else {
  ....
}
```

2018-10-02 04:14 UTC, mhevery commented on packages/core/src/render3/query.ts
> +    return createTemplateRef(ViewEngine_TemplateRef, ViewEngine_ElementRef, tNode, currentView);
Argh! I see `ViewEngine_TemplateRef` and `ViewEngine_ElementRef` will not be tree shakable, and there is not much we can do about it without getting crazy complicated on compiler. But at least we can tree shake `ViewEngine_ViewContainerRef` above.

2018-10-02 18:19 UTC, AndrewKushnir commented on packages/compiler-cli/test/compliance/r3_compiler_compliance_spec.ts
> +                $r3$.ɵquery(0, ["myRef"], true);
Great catch, makes sense. I will create a separate ticket and PR to take care of that.

2018-10-02 18:53 UTC, AndrewKushnir commented on packages/compiler-cli/test/compliance/r3_compiler_compliance_spec.ts
> +            @ContentChild('myRef') myRef: any;
I've added extra tests to check basic `{read: <TOKEN>}` operations, will add more as a part of the next PR (to increase test coverage for View and Content Queries feature).

2018-10-02 18:55 UTC, AndrewKushnir commented
@mhevery thanks for the comments. I've addressed them: performed additional changes and planned a couple followup tasks. Please have a look when you get a chance. Thank you.

2018-10-02 18:59 UTC, mary-poppins commented
You can preview d7a3ab0 at https://pr26171-d7a3ab0.ngbuilds.io/.

2018-10-03 03:51 UTC, mhevery approved these changes

2018-10-03 16:45 UTC, kara approved these changes
LGTM

2018-10-03 18:38 UTC, mary-poppins commented
You can preview 85569c4 at https://pr26171-85569c4.ngbuilds.io/.

2018-10-03 19:29 UTC, closed without merging