doc : updated doc to reflect the changes in rxjs6
angular/angular pull request #26238
Opened 2018-10-03 18:27 UTC by siddhant1

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2018-10-03 18:35 UTC, siddhant1 commented
I have signed it

2018-10-03 18:37 UTC, siddhant1 commented
ref #26182

2018-10-04 08:27 UTC, trotyl commented on aio/content/guide/observables.md
> +In order to show how subscribing works, we need to create a new observable. There is a constructor that you use to create new instances, but for illustration, we can use some static methods from the
Also `static methods` doesn't fit any more, they're just plain functions now.

2018-10-04 12:29 UTC, siddhant1 commented on aio/content/guide/observables.md
> +In order to show how subscribing works, we need to create a new observable. There is a constructor that you use to create new instances, but for illustration, we can use some static methods from the
I have to just remove the static keyword? Any other changes that I have to make?

2018-10-04 13:54 UTC, sarunint commented
The commit message should be `docs: update docs to reflect the changes in RxJS 6`.

Hint: The spaces are important, and you should use present verb.

2018-10-04 14:00 UTC, siddhant1 commented
Thanks for picking that out !

2018-10-04 14:02 UTC, trotyl commented on aio/content/guide/observables.md
> +In order to show how subscribing works, we need to create a new observable. There is a constructor that you use to create new instances, but for illustration, we can use some static methods from the
It's no longer `method`, just `function`.

2018-10-04 14:03 UTC, sarunint commented
If possible, please squash all commits together and rewrite the commit message.

2018-10-04 21:38 UTC, jenniferfell approved these changes

2018-10-04 21:39 UTC, jenniferfell commented
@jasonaden @benlesh This lgtm from an editorial POV. Needs your review/approval from the technical side. Is this what we want to say now? Thanks!

2018-10-05 17:30 UTC, brandonroberts requested changes

2018-10-05 17:30 UTC, brandonroberts commented on aio/content/guide/observables.md
> +In order to show how subscribing works, we need to create a new observable. There is a constructor that you use to create new instances, but for illustration, we can use some methods from the `rxjs`
`rxjs` -> `RxJS`

2018-10-05 17:39 UTC, jenniferfell commented on aio/content/guide/observables.md
> +In order to show how subscribing works, we need to create a new observable. There is a constructor that you use to create new instances, but for illustration, we can use some methods from the `rxjs`
I checked in the current RxJS docs, and it looks like we use this convention:
- In flowing text, "RxJS does things" without code font
- In code examples or other places where we explicitly name constructs, "rxjs" lowercase

https://angular.io/guide/rx-library

To me, this feels like the second case, where we explicitly name the library and use the lowercase. 

Question: Does the library self-identify as lowercase or mixed case? If code references should be mixed case, then we should open an issue to fix other docs, too. :-)

2018-10-05 17:41 UTC, mary-poppins commented
You can preview 37ac9d1 at https://pr26238-37ac9d1.ngbuilds.io/.

2018-10-05 17:44 UTC, brandonroberts approved these changes

2018-10-05 17:52 UTC, brandonroberts commented on aio/content/guide/observables.md
> +In order to show how subscribing works, we need to create a new observable. There is a constructor that you use to create new instances, but for illustration, we can use some methods from the `rxjs`
The library identifies as mixed case. Its used as lowercase when used in code reference for imports. I think it should be used here as mixed case, but we can omit the code font.

2018-10-05 17:54 UTC, brandonroberts commented
@siddhant1 one more thing. Will you remove the backticks from RxJS and squash everything down to one commit?

2018-10-05 17:58 UTC, siddhant1 commented
Sure

2018-10-05 18:13 UTC, mary-poppins commented
You can preview 83fb5a0 at https://pr26238-83fb5a0.ngbuilds.io/.

2018-10-05 18:17 UTC, mary-poppins commented
You can preview 58102b3 at https://pr26238-58102b3.ngbuilds.io/.

2018-10-05 21:28 UTC, brandonroberts commented
@jenniferfell the failure was a flaky test with Travis and unrelated to these changes. I restarted the test and it passed.

2018-10-08 20:44 UTC, closed without merging