Update file structure guide
angular/angular pull request #26256
Opened 2018-10-04 20:25 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-10-04 20:30 UTC, mary-poppins commented
You can preview 3d2b07b at https://pr26256-3d2b07b.ngbuilds.io/.

2018-10-05 15:32 UTC, mary-poppins commented
You can preview dfab133 at https://pr26256-dfab133.ngbuilds.io/.

2018-10-11 18:32 UTC, jenniferfell commented on aio/content/guide/file-structure.md
> +| `angular.json` | Sets defaults for the CLI and configuration options for build, serve, and test tools that the CLI uses, such as [Karma](https://karma-runner.github.io/) and [Protractor](http://www
Please remove this xref, so that we can land this before the new angular.json reference. Thanks.

2018-10-12 18:43 UTC, mary-poppins commented
You can preview 5507c83 at https://pr26256-5507c83.ngbuilds.io/.

2018-10-12 22:39 UTC, IgorMinar reviewed
first batch of comments... I'm not done yet.

2018-10-13 09:53 UTC, IgorMinar requested changes
please consider my suggestion to reorder how we introduce the files.

2018-10-13 09:53 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +  tsconfig.test.json
this file doesn't exist

2018-10-13 09:53 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +  angular.json (top level only)
all of these files are "top level only" - please remove the note

2018-10-13 09:53 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +## Project folder structure
this whole doc would flow better if we started by introducing the files in this order:


## workspace files
workspace-wide files, mostly configuration files, a readme file, and node_modules that provides npm packages to the entire workspace.

```
├── .editorconfig
├── .gitignore
├── README.md
├── tslint.json
├── angular.json
├── node_modules
├── package.json
├── tsconfig.json
├── tslint.json
└── yarn.lock
```

## default app project files

source files and configuration files for the default application

tsconfig.*.json and tslint.json files inherit from the workspace files tsconfig.json and tslint.json respectively.

Workspace-wide node_modules dependencies are visible to this project.

```
├── src
│   ├── app
│   ├── assets
│   ├── browserslist
│   ├── environments
│   ├── favicon.ico
│   ├── index.html
│   ├── karma.conf.js
│   ├── main.ts
│   ├── polyfills.ts
│   ├── styles.sass
│   ├── test.ts
│   ├── tsconfig.app.json
│   ├── tsconfig.spec.json
│   └── tslint.json
```

## default app project e2e files
config files and source files for the end-to-end tests

tsconfig.e2e.json inherits from the workspace-wide tsconfig.json.

Workspace-wide node_modules dependencies are visible to this project.


```
├── e2e
│   ├── protractor.conf.js
│   ├── src
│   └── tsconfig.e2e.json
```

## project directories for additional applications and libraries

These directories have similar layout to the default app and default app e2e projects directories

```
├── projects
│   ├── my-library
│   ├── my-other-app
│   └── my-other-app-e2e
```

2018-10-15 16:40 UTC, mary-poppins commented
You can preview ece6577 at https://pr26256-ece6577.ngbuilds.io/.

2018-10-15 22:32 UTC, mary-poppins commented
You can preview 9cfbeec at https://pr26256-9cfbeec.ngbuilds.io/.

2018-10-16 01:09 UTC, IgorMinar commented on aio/content/guide/file-structure.md
>  CLI `new` command, you can specify the `--style` option to use SASS or STYL styles.
in v7 we also let people configure this via a prompt that shows up during ng new if --style was not provided

2018-10-16 01:09 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> -You can add more global styles by configuring the build options in the `angular.json` configuration file.
this global mean runtime global, which is different from workspace-wide, so the change is incorrect

2018-10-16 01:09 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> -### Adding a global library
I don't see this content in the new version. Are we dropping it?

2018-10-16 01:09 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +## Configuring workspace-wide access
I see a lot of confusion about what "global" means below and it will take quite some work to fix that.

In the original text when we mentioned "global" what we meant was "global at runtime" as in globally accessible in the browser runtime when the application executes.

workspace-wide means available to all projects within a workspace at build time. For example package.json (node_modules) are a good example of workspace-wide configuration, but this configuration only affects how we build projects and changing package.json doesn't make script or stylesheets automatically available globally to the runtime of the applications built as projects within the workspace.

I'm not sure if this makes sense... or if we'll need to VC about this.

2018-10-16 14:51 UTC, clydin commented on aio/content/guide/file-structure.md
> -### Adding a global library
These are definitely useful sections.  The JQuery example is very appropriate as many _script_ based libraries may still rely on it.
Bootstrap itself may not be the best example as there are pure Angular versions of the script/logic elements of bootstrap that may be more appropriate for use in an Angular application.  However, as an initial example it does have some merit as it is a popular package.  And maybe a note that other third party Angular specific options exist as an alternative to the scripts?

2018-10-16 15:56 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> -### Adding a global library
Restoring the section -- I removed it because I was told that the source wiki for libraries was badly out-of-date. The other library material has not been included in the current doc.
Please check the accuracy of this section, and if you can, provide a better example.

@clydin - This requires a bit more context than I have -- can you be more specific about where the note should be and how it should be worded? perhaps examples of  one or two such Angular-specific options?

2018-10-16 16:15 UTC, mary-poppins commented
You can preview d192038 at https://pr26256-d192038.ngbuilds.io/.

2018-10-16 16:21 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +## Configuring workspace-wide access
@IgorMinar I have tried to correct this, please check. If I still don't understand it, we should talk.

2018-10-16 18:22 UTC, jenniferfell commented on aio/content/guide/file-structure.md
> +## Workspace files
Any idea why this is displaying as an H3 in the right side TOC/

2018-10-16 18:31 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +## Workspace files
Just corrected it - haven't gotten new preview yet

2018-10-16 18:42 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +| `tsconfig.app.json/`   | Default TypeScript configuration for apps in the workspace. |
```suggestion
| `tsconfig.app.json`   | Default TypeScript configuration for apps in the workspace. |
```

2018-10-16 18:44 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +| `package.json/`        | Lists package dependencies. |
```suggestion
| `package.json`        | Lists package dependencies. |
```

2018-10-16 18:44 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +| `angular.json/`        | CLI configuration for all projects in the workspace, including configuration options for build, serve, and test tools that the CLI uses, such as [Karma](https://karma-runne
```suggestion
| `angular.json`        | CLI configuration for all projects in the workspace, including configuration options for build, serve, and test tools that the CLI uses, such as [Karma](https://karma-runner.github.io/) and [Protractor](http://www.protractortest.org/).  |
```

2018-10-16 18:44 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +| `angular.json/`        | CLI configuration for all projects in the workspace, including configuration options for build, serve, and test tools that the CLI uses, such as [Karma](https://karma-runne
```suggestion
| `angular.json`        | CLI configuration for all projects in the workspace, including configuration options for build, serve, and test tools that the CLI uses, such as [Karma](https://karma-runner.github.io/) and [Protractor](http://www.protractortest.org/).  |
```

2018-10-16 18:44 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +| `tsconfig.spec.json/`  | Default TypeScript configuration for e2e test apps in the workspace. |
```suggestion
| `tsconfig.spec.json`  | Default TypeScript configuration for e2e test apps in the workspace. |
```

2018-10-16 18:44 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +| `tslint.json/`         | Default TSLint configuration for apps in the workspace. |
```suggestion
| `tslint.json`         | Default TSLint configuration for apps in the workspace. |
```

2018-10-16 18:45 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +<code-example format="." language="none" linenums="false">
maybe drop this section since we don't have it in the app or e2e files section?

2018-10-16 18:46 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +| `tsconfig.app.json/`   | Inherits from the workspace-wide `tsconfig.app.json` file. |
please drop all the `/` suffixes for file names, they should only be after directory names.

2018-10-16 18:48 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +{@a ws-global-access}
As discussed with @jenniferfell - everything under this heading doesn't belong to this doc.

We need to take this content and move it to other existing docs (e.g. how to install packages should go to the package doc, how to add scripts and stylesheets should go to the setup & build doc)

2018-10-16 19:05 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +| `tsconfig.app.json/`   | Inherits from the workspace-wide `tsconfig.app.json` file. |
oops

2018-10-16 19:15 UTC, mary-poppins commented
You can preview c0af207 at https://pr26256-c0af207.ngbuilds.io/.

2018-10-16 19:47 UTC, mary-poppins commented
You can preview 4949eea at https://pr26256-4949eea.ngbuilds.io/.

2018-10-16 21:47 UTC, mary-poppins commented
You can preview f408359 at https://pr26256-f408359.ngbuilds.io/.

2018-10-16 22:04 UTC, mary-poppins commented
You can preview c069efa at https://pr26256-c069efa.ngbuilds.io/.

2018-10-17 05:42 UTC, IgorMinar approved these changes

2018-10-17 12:55 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
>  <div class="alert-is-helpful>
this should be `<div class="alert is-helpful">`

2018-10-17 12:56 UTC, alan-agius4 requested changes
See comment

2018-10-17 14:54 UTC, mary-poppins commented
You can preview c26bb6e at https://pr26256-c26bb6e.ngbuilds.io/.

2018-10-17 15:42 UTC, skreborn reviewed
Mostly nitpicking, so feel free to ignore or reject any or all comments.

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +When you run this command, the CLI installs the necessary Angular npm packages and other dependencies a new workspace, with a root folder named *project_name*.
This sentence seems incomplete. Perhaps you meant

> When you run this command, the CLI installs the necessary Angular npm packages and other dependencies **to** a new workspace, with a root folder named *project_name*.

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +| `.gitignore`           | Specifies intentionally untracked files that Git should ignore. |
Since you've added links to all other products, maybe you could also add one for [Git](https://git-scm.com/)?

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +| `package.json`        | Lists package dependencies. |
The `package.json` knows a little more than that - although I'm unsure if the extra capabilities are worth explaining. You could simply add a link to the [npm documentation](https://docs.npmjs.com/files/package.json) to allow the user to further dig in if they so choose.

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +| `tsconfig.spec.json`  | Default TypeScript configuration for e2e test apps in the workspace. |
Are end-to-end tests really apps? I believe the following would be sufficient:

> Default TypeScript configuration for e2e test ~apps~ in the workspace.

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +| `tsconfig.app.json`   | Default TypeScript configuration for apps in the workspace. |
For completion's sake, you could also link to [TypeScript's home page](http://www.typescriptlang.org/).

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +| `tslint.json`         | Default TSLint configuration for apps in the workspace. |
Link to [TSLint's website](https://palantir.github.io/tslint/)?

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +| `package-lock.json`    | Provides version information for all of packages installed into node_modules by the npm client. [More info](https://docs.npmjs.com/files/package-lock.json). If you use the
The word *"of"* seems incorrect here. Maybe just omit entirely?

> Provides version information for all ~of~ packages installed into node_modules by the npm client

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +All of the projects within a workspace share this configuration context.
Same as above, but now with [reference](https://jakubmarian.com/is-it-all-the-or-all-of-the-in-english/)! :tada:

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +Project-specific TypeScript configuration files inherit from the workspace-wide `tsconfig.*.json`, and app-specific [TSLint](https://palantir.github.io/tslint/) configuration files inherit from the w
Link to TypeScript if you're linking to TSLint, too. The user will most likely already be familiar with it at this point, but an extra link can't hurt anyone.

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +| `browserlist`          | Configures sharing of target browsers and Node.js versions among various front-end tools. |
Link to [Browserlist's GitHub page](https://github.com/browserslist/browserslist) to allow the user to read further.

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +| `styles.sass`          | Lists CSS files that supply styles for a project. |
The extension of this file depends on how the project was created. Should we mention that here?

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +| `tsconfig.app.json`   | Inherits from the workspace-wide `tsconfig.app.json` file. |
Isn't the workspace-wide file simply named `tsconfig.json`? Same for the next line.

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +Inside the `src/` folder, the `app/` folder contains your app's logic and data. Angular components, templates, styles, images, and anything else your app needs go here. Files at the top level of `src
Images don't actually go here, do they? They should be stored in the `assets` folder as far as I know.

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +my-app/
Like the file tree below (in *App source folder*), this should also be enclosed within a `<code-example>` block for consistency. Same goes for the file tree under *Project folders for additional apps and libraries*.

2018-10-17 15:42 UTC, skreborn commented on aio/content/guide/file-structure.md
> +| `app/app.component.ts`      | Defines the logic for the app's root component, named AppComponent. The view associated with this root component becomes the root of the [view hierarchy](guide/glossar
Format all class names in `code` style to allow for easier distinction.

2018-10-17 15:52 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +| `tsconfig.spec.json`  | Default TypeScript configuration for e2e test apps in the workspace. |
I think they are really apps -- at least, they are separate projects in the file structure. 
@igor How do you want to talk about them?

2018-10-17 16:11 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +my-app/
I took out the code-example blocks to try and get it to stop highlighting keywords. It didn't work - I'll put them back.

2018-10-17 16:18 UTC, mary-poppins commented
You can preview 37d2d11 at https://pr26256-37d2d11.ngbuilds.io/.

2018-10-17 16:19 UTC, mary-poppins commented
You can preview f935eaa at https://pr26256-f935eaa.ngbuilds.io/.

2018-10-17 16:51 UTC, jenniferfell commented on aio/content/guide/file-structure.md
> +| `.editorconfig`        | Configuration for code editors. See [EditorConfig](https://editorconfig.org/). |
Pete has separate PR to fix

2018-10-17 16:52 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
>  <div class="alert-is-helpful>
@alan-agius4 Please approve.

2018-10-17 18:10 UTC, closed without merging