[WIP]: feat(ivy): support i18n & ICU expressions
angular/angular pull request #26275
Opened 2018-10-05 17:07 UTC by ocombe

## PR Type
What kind of change does this PR introduce?

```
[x] Feature
```

## What is the new behavior?
Support for i18n & ICU expressions in ivy.
Implementation of the design https://github.com/angular/angular/pull/26091

## Does this PR introduce a breaking change?
```
[x] No
```

2018-10-05 17:13 UTC, mary-poppins commented
You can preview 3d07ba1 at https://pr26275-3d07ba1.ngbuilds.io/.

2018-10-05 17:15 UTC, mary-poppins commented
You can preview 7027ade at https://pr26275-7027ade.ngbuilds.io/.

2018-10-09 05:32 UTC, mhevery requested changes

2018-10-09 05:32 UTC, mhevery commented on packages/core/test/render3/i18n_spec.ts
> +    expect(cropMessage(message, 3)).toEqual('before�*4��*�after');
I have changed the encoding rules. See: https://github.com/angular/angular/pull/26091/files#diff-bf70cd3451a2cb2d8e20237ae913bafaR88

2018-10-09 05:32 UTC, mhevery commented on packages/core/test/render3/i18n_spec.ts
> +          'simple text', -1 << I18nMutateOpCode.SHIFT_REF | I18nMutateOpCode.AppendChild
I think this should be `0` not `-1`. See: https://github.com/angular/angular/pull/26091/files#diff-bf70cd3451a2cb2d8e20237ae913bafaR561 

(same for the remainder of the tests)

2018-10-09 05:32 UTC, mhevery commented on packages/core/test/render3/i18n_spec.ts
> +          'Hello �0�!', -1 << I18nMutateOpCode.SHIFT_REF | I18nMutateOpCode.AppendChild
This should be empty string `''` instead of `Hello �0� `. The reason for this is that empty string is interned and it will marshal faster into DOM. Since we will overwrite it later anyways `document.createText(``)` is faster than `document.createText('Hello �0�')`.

2018-10-09 05:32 UTC, mhevery commented on packages/core/test/render3/i18n_spec.ts
> +          -1 << I18nUpdateOpCode.SHIFT_REF | I18nUpdateOpCode.Text
`-1` is not correct. In this example it should be`0` because `expandoStartIndex === 0`, there fore the text node is stored at that location. 

But this is a bad test because `0` location is where the `i18nStart(0, MSG_DIV)` is stored.

2018-10-09 05:32 UTC, mhevery commented on packages/core/test/render3/i18n_spec.ts
> +      const opCodes = i18nStart(0, MSG_DIV);
`i18nStart` should be void. This is because it is public API and we don't want to expose our internals to the outside world. So in tests we should have some other way of retrieving the `TI18n`

2018-10-09 05:32 UTC, mhevery commented on packages/core/test/render3/i18n_spec.ts
> +      opCodes = i18nStart(0, MSG_DIV, 3);
`3` is not correct in this location. It should be block id as described here: https://github.com/angular/angular/pull/26091/files#diff-bf70cd3451a2cb2d8e20237ae913bafaR88

2018-10-09 05:32 UTC, mhevery commented on packages/core/test/render3/i18n_spec.ts
> +      // Original text was: `�0� is rendered as: �*3�before�*4�middle�*�after�*�!`
Something is missing in this test. How should the test know what the original text was, or how many placeholders there are.

2018-10-09 05:32 UTC, mhevery commented on packages/core/src/render3/i18n.ts
> + * Breaks pattern into strings and top level {...} blocks.
Just a friendly reminder that this well need useful docs.

2018-10-09 05:32 UTC, mhevery commented on packages/core/src/render3/i18n.ts
> +function extractParts(pattern: string): (string | /*IcuExpression*/any)[] {
need unit tests for this function.

2018-10-09 05:32 UTC, mhevery commented on packages/core/src/render3/i18n.ts
> +export function i18nStart(index: number, message: string, subTemplateIndex?: number): TI18n {
function should have `void` return type.

2018-10-09 05:32 UTC, mhevery commented on packages/core/src/render3/i18n.ts
> +          if (value.charAt(0) === '#') {
Spec has changed for closing tag.

2018-10-09 14:39 UTC, ocombe commented on packages/core/test/render3/i18n_spec.ts
> +      // Original text was: `�0� is rendered as: �*3�before�*4�middle�*�after�*�!`
yes, I wrote this before our discussion with i18nEnd deleting placeholders
that's why the test is `xit`, it wasn't running

2018-10-12 17:19 UTC, mary-poppins commented
You can preview 35c2eed at https://pr26275-35c2eed.ngbuilds.io/.

2018-10-17 14:29 UTC, mary-poppins commented
You can preview 4d6c1be at https://pr26275-4d6c1be.ngbuilds.io/.

2018-10-17 19:50 UTC, ocombe commented on packages/core/src/render3/interfaces/i18n.ts
> +>>>>>>> feat(ivy): support i18n & ICU expressions
woops look like I missed that one, I'll remove the conflict in the next push

2018-10-17 19:51 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +          const phIndex = parseInt(value.substr(1), 10);
this should probably be `const phIndex = parseInt(value.substr(1), 10) + HEADER_OFFSET`;

2018-10-17 22:51 UTC, mhevery requested changes
Overall this is looking good! I made some changes here ebe11f299d Please review them to make sure that you agree with them.

One major point is please pay more attention to naming and documentation. At times it is hard to follow as to what is going on. 

Let me know when you have the next set of changes for me to review.

2018-10-17 22:51 UTC, mhevery commented on packages/core/src/render3/i18n.ts
> +interface IcuExpression {
Please add docs explaining: what, how and why.

2018-10-17 22:54 UTC, mary-poppins commented
You can preview ebe11f2 at https://pr26275-ebe11f2.ngbuilds.io/.

2018-10-18 13:21 UTC, ocombe commented on packages/core/src/render3/interfaces/icu.ts
> +export const enum IcuType {Plural = 0, Select = 1}
actually I just forgot to delete this file :D

2018-10-22 09:44 UTC, mary-poppins commented
You can preview e3e5d9c at https://pr26275-e3e5d9c.ngbuilds.io/.

2018-10-22 19:29 UTC, mary-poppins commented
You can preview 24166c0 at https://pr26275-24166c0.ngbuilds.io/.

2018-10-23 12:31 UTC, mary-poppins commented
You can preview ade3587 at https://pr26275-ade3587.ngbuilds.io/.

2018-10-23 14:23 UTC, mary-poppins commented
You can preview 4b86f4a at https://pr26275-4b86f4a.ngbuilds.io/.

2018-10-29 18:35 UTC, mary-poppins commented
You can preview 0f554b9 at https://pr26275-0f554b9.ngbuilds.io/.

2018-10-29 18:49 UTC, mary-poppins commented
You can preview 4b57280 at https://pr26275-4b57280.ngbuilds.io/.

2018-10-29 19:09 UTC, mary-poppins commented
You can preview daa4494 at https://pr26275-daa4494.ngbuilds.io/.

2018-10-30 16:47 UTC, mary-poppins commented
You can preview 27b61b3 at https://pr26275-27b61b3.ngbuilds.io/.

2018-10-31 18:14 UTC, mhevery requested changes
Overall looks good. (I made some minor fixes 6a6c78e0b8) 
Please look at my comments and address them. Ping when ready for last review.

2018-10-31 18:14 UTC, mhevery commented on packages/core/src/render3/i18n.ts
> +  expChangedStack[expChangedStackPointer++] = expression;
We should not be having our own stack `expChangedStack` We should just be using `bind` We can retrieve the value using `viewData[bindingIndex - i18nOffset]` also we should be updating the maskBit here. We than don't need `flushExpChangedStack`

2018-10-31 18:14 UTC, mhevery commented on packages/core/src/render3/i18n.ts
> +  readUpdateOpCodes(updateOpCodes, icus, viewData);
1. please pass `changeMask` explicitly (rather than rely on global state inside the `readUpdateOpCodes`) function.
2. I think we should have a short circuit `if` here in case `changeMask` is `0` to not bother with anything (most common case)

2018-10-31 18:52 UTC, mary-poppins commented
You can preview 6a6c78e at https://pr26275-6a6c78e.ngbuilds.io/.

2018-11-01 09:11 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +const BINDING_REGEXP = /�(\d+):?\d*�/gi;
It's in the design docs. We've discussed this a bit with @AndrewKushnir but we should probably discuss this a bit more.

2018-11-01 09:16 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +  // TODO(ocombe): support ICU expressions in attributes, see #21615
Yes, this is a new feature that was requested by people from Google (they need it for aria labels). It would be nice to add it as the same time but it's not MVP.

2018-11-01 09:58 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +function readUpdateOpCodes(
no because `I18nMutateOpCode.MASK_OPCODE` is different from `I18nUpdateOpCode.MASK_OPCODE`

2018-11-01 13:59 UTC, mary-poppins commented
You can preview e01c3c8 at https://pr26275-e01c3c8.ngbuilds.io/.

2018-11-08 22:58 UTC, AndrewKushnir commented on packages/core/src/render3/util.ts
> +export function addAllToArray(items: any[], arr: any[]) {
It looks like this function is unused?

2018-11-08 23:00 UTC, AndrewKushnir commented on packages/core/test/render3/i18n_spec.ts
> -
Do we need this code?

2018-11-08 23:01 UTC, AndrewKushnir commented on packages/core/test/render3/i18n_spec.ts
> -
Do we need these lines?

2018-11-08 23:06 UTC, AndrewKushnir commented on packages/core/src/render3/util.ts
> +export function addAllToArray(items: any[], arr: any[]) {
We can probably do something like this (that would do the same thing):
```
items.push(...arr);
```

2018-11-09 15:47 UTC, mhevery approved these changes

2018-11-12 12:55 UTC, ocombe commented on packages/core/src/render3/util.ts
> +export function addAllToArray(items: any[], arr: any[]) {
So apparently using spread is bad because it uses `.apply` which creates more memory pressure, or something like that.

2018-11-12 13:00 UTC, mary-poppins commented
You can preview 6d84a22 at https://pr26275-6d84a22.ngbuilds.io/.

2018-11-12 13:16 UTC, mary-poppins commented
You can preview 7610dc3 at https://pr26275-7610dc3.ngbuilds.io/.

2018-11-12 13:43 UTC, mary-poppins commented
You can preview 3ecfb77 at https://pr26275-3ecfb77.ngbuilds.io/.

2018-11-12 14:02 UTC, mary-poppins commented
You can preview 8aa7969 at https://pr26275-8aa7969.ngbuilds.io/.

2018-11-12 14:11 UTC, mary-poppins commented
You can preview 6ee59f2 at https://pr26275-6ee59f2.ngbuilds.io/.

2018-11-12 14:38 UTC, alxhub approved these changes
LGTM from the compiler side - runtime review left to @mhevery

2018-11-12 21:21 UTC, mhevery commented
http://test/OCL:221145653:BASE:221145709:1542057665529:fe9a09d2

2018-11-12 23:19 UTC, mhevery commented
http://test/OCL:221145653:BASE:221166396:1542064725363:dc3c8482

2018-11-12 23:21 UTC, mary-poppins commented
You can preview a271fd2 at https://pr26275-a271fd2.ngbuilds.io/.

2018-11-13 08:38 UTC, mary-poppins commented
You can preview 54cce35 at https://pr26275-54cce35.ngbuilds.io/.

2018-11-13 08:41 UTC, mary-poppins commented
You can preview 02d3627 at https://pr26275-02d3627.ngbuilds.io/.

2018-11-13 17:36 UTC, mhevery commented
http://test/OCL:221145653:BASE:221280903:1542130571606:90b96ef2

2018-11-13 21:46 UTC, mary-poppins commented
You can preview 385ec46 at https://pr26275-385ec46.ngbuilds.io/.

2018-11-13 21:56 UTC, AndrewKushnir commented
Note: 7f9a749 - restoring missing import after rebase

2018-11-13 21:59 UTC, mary-poppins commented
You can preview 7f9a749 at https://pr26275-7f9a749.ngbuilds.io/.

2018-11-13 22:51 UTC, closed without merging