docs(docs-infra): update doc example style
angular/angular pull request #26372
Opened 2018-10-10 16:54 UTC by krzysztof-grzybek

Only update style in docs example.
HostListener is preferred over host metadata by official style guide

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-10-10 18:09 UTC, gkalpak requested changes
You alspo need to update the wording in [testing.md][1].
Also, please change the commit message to `docs: ...`.

Other than that LGTM.

[1]: https://github.com/angular/angular/blob/767d62efca7febc65943caee2315a36afabeb007/aio/content/guide/testing.md

2018-10-10 20:30 UTC, krzysztof-grzybek commented
@gkalpak  done :)

2018-10-11 07:23 UTC, gkalpak requested changes

2018-10-17 14:57 UTC, krzysztof-grzybek commented
@gkalpak FYI, I made requested changes (dunno if You receive notification after amend commit)

2018-10-17 15:04 UTC, gkalpak approved these changes

2019-01-14 16:35 UTC, brandonroberts approved these changes

2019-01-14 16:39 UTC, mary-poppins commented
You can preview 1e63969 at https://pr26372-1e63969.ngbuilds.io/.

2019-01-15 01:06 UTC, closed without merging