docs: remove "setup for local dev" and "anatomy of setup" docs from nav
angular/angular pull request #26380
Opened 2018-10-10 21:32 UTC by chembu

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
remove setup for local dev and anatomy of setup docs from nav

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Now the setup for local dev and anatomy of setup exists in the nav.
Issue Number: N/A

## What is the new behavior?
"setup for local dev" is redirected to getting started guide and "anatomy of setup" is redirected to file structure guide.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-10-10 23:46 UTC, jbogarthyde commented on aio/content/guide/upgrade.md
If there is only one thing to do now, instead of two, this should not be a bullet. Something like this:

Add Angular and other new dependencies from the `package.json` file that was created for [Getting Started](guide/quickstart). When this is done, install the new dependencies:
```
npm install
```

2018-10-11 19:35 UTC, jenniferfell requested changes
LGTM: navigation and redirects 

Need input from engineering on upgrade.md. Upgrade instructions rely on setup guide, which explained how to clone old quickstart repo. Changing to use Getting Started and a CLI workspace/project, it's not clear where developers get systemjs config file. 

Also, do developers need to install CLI and run ng new, or do they just need to download the new Getting Started app solution and copy files from it into their AngularJS project?

2018-10-11 19:35 UTC, jenniferfell commented on aio/content/guide/upgrade.md
> +You can see how this can be done with SystemJS by following the instructions in the [Getting Started](guide/quickstart) guide.
The Getting Started doesn't talk about SystemJS. How about this: 
To begin converting your AngularJS application to a hybrid, you need to load the Angular framework. Follow the instructions in [Getting Started](guide/quickstart) to install the Angular CLI, create an Angular workspace, and create an initial Getting Started app project.

2018-10-11 19:35 UTC, jenniferfell commented on aio/content/guide/upgrade.md
> +Add Angular and other new dependencies from the `package.json` file that was created for [Getting Started](guide/quickstart). When this is done,  install the new dependerncies:
"created for" seems odd. Maybe: 
Add Angular and other new dependencies from the `package.json` file that you create in (or download from) [Getting Started](guide/quickstart).

2018-10-11 19:35 UTC, jenniferfell commented on aio/content/guide/upgrade.md
> +Add Angular and other new dependencies from the `package.json` file that was created for [Getting Started](guide/quickstart). When this is done,  install the new dependerncies:
Typo and extra space: When this is done, install the new dependencies:

2018-10-11 19:35 UTC, jenniferfell commented on aio/content/guide/upgrade.md
> +You also need to make a couple of adjustments to the `systemjs.config.js` .
We definitely need to find out where developers get this file now that they aren't using the quickstart repo app. I don't see it anywhere in the workspace, project, app created by ng new in v7. @IgorMinar ?

2018-10-11 19:38 UTC, jenniferfell commented
@IgorMinar Hi. We need a bit of advice from someone familiar with upgrading. As part of removing old Setup doc, we need to adjust the upgrading info so it doesn't rely on the old quickstart repo.

2018-10-11 20:04 UTC, gkalpak submitted a review, later dismissed
Unfortunately, the upgrade guides depend on a setup that is different from what the cli generates (one that involves SystemJS). We cannot simply remove `guide/setup` and replace references with `guide/quickstart`.

The whole upgrade guide should be rewritten to be compatible with the cli setup. This is something that is good anyway (and should happen at some point), but:

1. It is not a trivial undertaking.
2. We don't know how to create hybrid apps with the cli setup.
    (I'm not saying it is not possible; it is just that we haven't investigated it. But I suspect it will not be straight forward.)

2018-10-11 20:10 UTC, jenniferfell commented on aio/content/navigation.json
> -          "hidden": true
Oh right, I forgot to check for those removals. Yes, the .md files are supposed to be removed in this PR, too.

2018-10-11 20:18 UTC, jenniferfell commented
@gkalpak @chembu So, it sounds like we should do this for now:

*Anatomy: Remove from doc set*
Continue to remove Anatomy of the Setup (https://angular.io/guide/setup-systemjs-anatomy) from nav, remove file, update all links to it, and do the redirect to file-structure. 

*Setup*
* Leave setup in the file in the doc set for now. 
* Leave setup hidden in the nav for now (as was before this PR).
* Do NOT redirect setup URL.
* Do update all non-upgrade xrefs to setup.md to go to quickstart.md
* Keep upgrade.md as-it-was before this PR for now.

*Then...stage 2 in a new PR soon*
* Rewrite upgrade.md to include the necessary info from setup.md, so that only upgrading users are directed to use the old quickstart repo and app.
* Remove setup.md and do the redirects to quickstart.md

*Finally...stage 3 in a new PR when we have engineering time to ensure we get it right*
* Rewrite upgrade.md to use a CLI-based app instead of the old quickstart repo app

2018-10-11 23:08 UTC, IgorMinar requested changes

2018-10-11 23:08 UTC, IgorMinar commented on aio/content/guide/upgrade.md
> +You also need to make a couple of adjustments to the `systemjs.config.js` .
yeah.. this guide is not based on Angular CLI, it's based on the quckstart repo that we want to remove. Which means that this doc can't point people to https://angular.io/guide/quickstart at all because the rest of the doc is not compatible with CLI, it's config, and directory structure.

this doc will need a full rewrite but that's more than what we can do now. I suggest we just keep it referencing the old systemjs-based repo for now. :-(

2018-10-12 17:06 UTC, mary-poppins commented
You can preview 1d02b87 at https://pr26380-1d02b87.ngbuilds.io/.

2018-10-15 21:53 UTC, jenniferfell commented
Descoped this PR to just removing "Anatomy of the Setup" and redirecting users to the new file-structure.md page.

2018-10-15 21:54 UTC, jenniferfell approved these changes

2018-10-15 21:58 UTC, jenniferfell commented
@IgorMinar @gkalpak : I narrowed the scope of this PR to just removal of the old "Anatomy of the Setup" document, with redirect to https://next.angular.io/guide/file-structure

Please review and request changes or approve. Thanks!

P.S. I opened a separate issue for work to remove "Setup for Local Development" and to update all docs that refer to the old QuickStart repo described in that guide. (Link to PR above.)

2018-10-16 00:41 UTC, IgorMinar approved these changes
lgtm. if you want to move the upgrade docs under techniques maybe do that in a separate PR?

2018-10-16 00:41 UTC, IgorMinar commented on aio/content/navigation.json
> +        {
@jenniferfell didn't you say that you wanted these docs to go under techniques?

2018-10-16 08:13 UTC, gkalpak commented on aio/content/navigation.json
> +        {
Yes, these guides are under Techniques on master. This change seems invalid.

https://github.com/angular/angular/blob/1c9b06504b45280a30df937b99bc26256732b55e/aio/content/navigation.json#L477-L497

2018-10-16 21:15 UTC, closed without merging