fix(docs-infra): rename "title" by "header" to avoid unwanted tooltips
angular/angular pull request #26396
Opened 2018-10-11 11:34 UTC by wmarques

Closes #26174

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The `title` attribute of code-example and code-pane examples are in conflict with the HTML attribute `title`, which makes a tooltip appearing when we hover on those components.

Issue Number: #26174 

## What is the new behavior?
As suggested by @gkalpak, I renamed `title` into `header` and made the changes in the pages that used those components. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-10-11 22:50 UTC, gkalpak requested changes
Wow, I didn't expect to have so many files affected.
Great job, btw 👍 

I left a few (mostly minor) commets. Here are some more:
- You missed a few `title`s in [guide/i18n.md][1].
- You missed a `title` in [tutorial/toh-pt1.md][2].

Please, if you make further changes do _NOT_ amend the orignal commit. Just add them as new commits (so it is easier to review).

##
BTW, I think it would be a good idea to print an error or warning if people try to actually use `title` instead of `header`. Because many people will not be aware of this change and may put `title` on their code snippets, not realizing it will be ignored.

[1]: https://github.com/angular/angular/blob/de43e6c9d5813d525975ac26e093185639fc361e/aio/content/guide/i18n.md
[2]: https://github.com/angular/angular/blob/de43e6c9d5813d525975ac26e093185639fc361e/aio/content/tutorial/toh-pt1.md

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/i18n.md
> +  <a href="http://cldr.unicode.org/" header="CLDR">Common Locale Data Repository (CLDR)</a>.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/i18n.md
> +  <a href="http://userguide.icu-project.org/formatparse/messages" header="ICU Message Format">ICU Message Format</a>
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/i18n.md
> +  <a href="http://cldr.unicode.org/index/cldr-spec/plural-rules" header="Pluralization Rules">CLDR pluralization rules</a>.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/reactive-forms.md
> +Try the <live-example header="Reactive Forms in Stackblitz">Reactive Forms live-example</live-example>.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/router.md
> +Try it by clicking on this <live-example header="Hero Employment Agency Live Example">live example link</live-example>.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/router.md
> +from the <live-example name="toh-pt4" header="Tour of Heroes: Services example code"></live-example>.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/router.md
> +  the <live-example name="toh-pt4" header="Tour of Heroes: Services example code">"Services" tutorial</live-example> into the `hero-list.component.html` template.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/router.md
> +<a href="https://blog.8thlight.com/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html" header="Separation of Concerns">*Separation of Concerns* principle</a>,
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/router.md
> +Please visit the <live-example header="Router Sample in Stackblitz"></live-example>
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/router.md
> +<a href="https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries" header="HTML5 browser history push-state">history.pushState</a>,
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/router.md
> +<a href="https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries" header="HTML5 browser history push-state">history.pushState</a>
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/router.md
> +<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base" header="base href">&lt;base href&gt; element</a>**
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/router.md
> +<a href="https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries" header="Browser history push-state">HTML5 pushState</a>
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/router.md
> +<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base" header="base href">&lt;base href&gt; element</a>
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/security.md
> +<a href="https://www.youtube.com/watch?v=9inczw6qtpY" header="Cross Site Request Funkery Securing Your Angular Apps From Evil Doers">talk on XSRF at AngularConnect 2016</a>.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/setup-systemjs-anatomy.md
> +      <a href="http://www.protractortest.org/" header="Protractor: end-to-end testing for Angular">protractor</a>
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/setup-systemjs-anatomy.md
> +      Configuration for the <a href="https://karma-runner.github.io/1.0/index.html" header="Karma unit test runner">karma</a>
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/setup-systemjs-anatomy.md
> +      Script to run <a href="https://karma-runner.github.io/1.0/index.html" header="Karma unit test runner">karma</a>
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/setup-systemjs-anatomy.md
> +         header="npm scripts for Angular documentation samples">Read more</a> about them.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/setup-systemjs-anatomy.md
> +      <a href="http://www.protractortest.org/" header="Protractor: end-to-end testing for Angular">protractor</a>
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/setup.md
> +<a href="https://github.com/angular/quickstart/archive/master.zip" header="Download the QuickStart seed repository">Download the QuickStart seed</a>
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/setup.md
> +<a href="https://docs.npmjs.com/getting-started/installing-node" target="_blank" header="Installing Node.js and updating npm">
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/setup.md
> +<live-example header="QuickStart Seed in Stackblitz">Live coding</live-example> in the browser is a great way to explore Angular.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/setup.md
> +Use the <live-example header="QuickStart Seed in Stackblitz">live coding</live-example> environment as a _playground_,
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/setup.md
> +<a href="https://github.com/angular/angular/issues/new" header="File a documentation issue">file a documentation issue</a> or
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/setup.md
> +<a href="https://github.com/angular/angular/issues/new" header="File an Angular issue">file an issue with Angular itself</a>.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/setup.md
> +In windows, by default one application can only have 6 websocket connections, <a href="https://msdn.microsoft.com/library/ee330736%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#websocket_maxconn" hea
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/structural-directives.md
> +<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors" header="MDN: Attribute selectors">attribute selector</a>.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/template-syntax.md
> +in the <live-example header="Template Syntax Live Code"></live-example>.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/guide/template-syntax.md
> +<a href="https://developer.mozilla.org/en-US/docs/Web/Web_Components" header="MDN: Web Components">web component</a>.
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/marketing/docs.md
> +    header="Experience Angular in a live coding environment">
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/marketing/docs.md
> +  <a href="guide/quickstart" class="docs-card" header="Angular Getting Started">
Do not change this one.

2018-10-11 22:50 UTC, gkalpak commented on aio/content/marketing/docs.md
> +  <a href="guide/architecture" class="docs-card" header="Angular Architecture">
Do not change this one.

2018-10-12 08:03 UTC, wmarques commented
@gkalpak Thanks for all the reviews ! I'll work on it during the weekend 😄

2018-10-12 08:42 UTC, gkalpak commented
Awesome, thx!
(To repeat myself, please make sure you do _not_ change the original commit. Just add new commits with the changes :grin:)

2018-10-12 10:17 UTC, petebacondarwin commented
We should try to get this reviewed and merged quickly as it is likely to become stale quite quickly!

2018-10-12 15:59 UTC, wmarques commented
@gkalpak Sure I'll add more commit after the one I did 😄  Didn't know about the `--fixup`, I'll try ! 
@petebacondarwin I'll work on this tomorrow, these are not big changes so that shouldn't take much time !

2018-10-14 13:48 UTC, wmarques commented
I don't understand why I'm having some commits from other people... Maybe I should create a new branch and cherry-pick my two commits, is that ok?

2018-10-14 19:44 UTC, gkalpak commented
Seems like a rebase gone bad :smiley:
I fixed it for you :wink:

2018-10-15 13:36 UTC, wmarques commented
@gkalpak oh thanks ! 
I don't understand what you meant by "the actual implementation changes are missing".
Beside this comment, I only need to add a warning for the `title` input, right ?

2018-10-16 08:48 UTC, gkalpak commented
@wmarques, I see you are still pushing changes. Feel free to ping me once this is ready for another review  (or if you have any questions/run into problems) :wink:

2018-10-16 08:57 UTC, wmarques commented
@gkalpak I think it's ready for review, the only thing I'm missing is `The spec changes lgtm, but the actual implementation changes are missing`, I don't understand what you meant by this :(

2018-10-16 09:16 UTC, gkalpak commented
+1 for Travis for letting you know 😛 (But -1 for being flakey 😛)
(Pro tip: Rebasing on latest master should make most of the flakes go away.)

2018-10-16 09:19 UTC, wmarques commented
@gkalpak thanks alot ! Is that ok for you if I only do 'fixup' commits ? Or you prefer more explicit commit messages ?

2018-10-16 15:17 UTC, gkalpak requested changes
Almost there 🏁 🏎
Nice job 👍

2018-10-16 15:17 UTC, gkalpak commented on aio/tools/transforms/examples-package/inline-tag-defs/example.js
> +        'Process inline example tags (of the form {@example some/uri Some header}), replacing them with HTML anchors',
Not directly related to this PR, but since you are at it, this description is in accurate; it should be:

> [...] of the form {@example some/uri some-region Some header} [...]

2018-10-16 15:20 UTC, wmarques commented on aio/src/app/custom-elements/code/code-example.component.ts
> +  }
Well, I'll create the ticket and if I find more time I'd be glad to get on this adventure 😄 But I prefer merging this asap as it becomes stale quite quickly :) 
I'll do that later this day, thanks again !

2018-10-16 22:10 UTC, wmarques commented
@gkalpak Should be ok now ! 😄

2018-10-17 10:47 UTC, gkalpak requested changes
One last comment 😇 and it should be good to go.

2018-10-17 10:47 UTC, gkalpak commented on aio/content/guide/docs-style-guide.md
You also need to update the working below (to mention `header` instead of `title`).

2018-10-17 11:55 UTC, wmarques commented on aio/content/guide/docs-style-guide.md
@gkalpak Should be ok now 😄

2018-10-17 12:18 UTC, gkalpak approved these changes

2018-10-17 14:48 UTC, gkalpak commented on aio/src/app/custom-elements/code/code-example.component.ts
> +  }
Sorry, @wmarques, I went ahead and created #26514 myself (because I think it is important to land it right after this PR).
Don't worry, though. There are plenty of adventures to be had on aio-land 😛

2018-10-17 16:47 UTC, mary-poppins commented
You can preview 02d2d3a at https://pr26396-02d2d3a.ngbuilds.io/.
You can preview 72e6a72 at https://pr26396-72e6a72.ngbuilds.io/.
You can preview 81e3464 at https://pr26396-81e3464.ngbuilds.io/.
You can preview e008fa1 at https://pr26396-e008fa1.ngbuilds.io/.
You can preview d9eb643 at https://pr26396-d9eb643.ngbuilds.io/.
You can preview aca6da3 at https://pr26396-aca6da3.ngbuilds.io/.
You can preview b95a17e at https://pr26396-b95a17e.ngbuilds.io/.
You can preview 0ab972f at https://pr26396-0ab972f.ngbuilds.io/.
You can preview 550595c at https://pr26396-550595c.ngbuilds.io/.

2018-10-17 16:55 UTC, IgorMinar approved these changes
thanks for fixing this one!

2018-10-17 17:32 UTC, jenniferfell approved these changes
I didn't review each change, but the general concept and a spot-check LGTM. Thanks for fixing the Author's Style Guide, too. I'll let the writers know about this change.

2018-10-17 18:06 UTC, closed without merging

2018-10-18 08:19 UTC, wmarques commented
Thanks ! Glad to have my first PR on the angular repo merged 😄