docs: Updated Browser support for Service Worker
angular/angular pull request #26408
Opened 2018-10-11 21:11 UTC by nik72619c

##Documentation regarding the changes for browser support of Service Worker

The docs status for the Prerequisites section of the angular service worker only specified that the only Chrome and Firefox provided the support for the same.

But according to the latest data from caniuse.com and MDN Web docs, many other browsers, along with their updated versions now support service workers.
Browsers like opera still do not provide the support.
Hence,  provided the updated information regarding the same.

#Addition of a short code snippet

I also provided a short code snippet, illustrating how to detect the browser support for the service workers before rendering the code using the navigator object.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2018-10-11 21:33 UTC, nik72619c commented
#26408 

created a pull request for issue 26408

2018-10-16 09:01 UTC, gkalpak requested changes
Thank, @nik72619c, for working on this 👍
I have left some suggestions/comments.

2018-10-16 09:01 UTC, gkalpak commented on aio/content/guide/service-worker-intro.md
> +```
This code snippet is redundant for `@angular/service-worker`, because users do not manually register their SW and Angular will already do the check under the hood.
Please remove it.

2018-10-16 21:18 UTC, nik72619c commented on aio/content/guide/service-worker-intro.md
> +```
I made the required changes.

2018-10-16 21:18 UTC, nik72619c commented
Made the required changes !

2018-10-17 10:42 UTC, gkalpak requested changes
Thx fior working on this. I left a couple more suggestions 😇

2018-10-17 10:42 UTC, gkalpak commented on aio/content/guide/service-worker-intro.md
> +Your application must run in a web browser that supports service workers. Currently, the latest versions of Chrome and Firefox support service workers along with Edge (17,18), Safari, UC Browser (And
Some more suggestion:

- Since you mention Opera Mini, I think it is a good idea to also mention that Opera _does_ support SW (to avoid confusion). 
- You can drop the version after IE (11), since no version of IE will ever support SW.
- According to [Can I Use][1], the latest version of iOS Safari _does_ support SW.
- Change `http://caniuse.com` to `https://caniuse.com`.

Overall, I would change this paragraph to something like:

> Your application must run in a web browser that supports service workers. Currently, service workers are supported in the latest versions of Chrome, Firefox, Edge, Safari, Opera, UC Browser (Android version) and Samsung Internet. Browsers like IE and Opera Mini do not provide the support. To learn more about other browsers that are service worker ready, see the \[Can I Use](https://caniuse.com/#feat=serviceworkers) page and \[MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API).

[1]: http://caniuse.com/#feat=serviceworkers

2018-10-17 13:48 UTC, nik72619c commented
I made the suggested changes...

2018-10-17 13:49 UTC, nik72619c commented on aio/content/guide/service-worker-intro.md
> +```
I made the changes ...

2018-10-17 14:57 UTC, gkalpak approved these changes
Awesome ❤️ (Thx for staying with me :grin:)
Can you please squash the commits into one and change the commit message to:

> docs(service-worker): update browser support for Service Worker

2018-10-19 08:43 UTC, nik72619c commented
done!

2018-10-19 09:59 UTC, gkalpak commented
Thx for making the change, but there seems to be a space after `docs`, which makes our linter unhappy (and CI fails).
Can you please remove the space (`docs (service-worker): ...` --> `docs(service-worker): ...`)?

2018-10-19 10:01 UTC, nik72619c commented
oh ok!

2018-10-19 10:35 UTC, gkalpak commented
👌 
CI is happy. I'm happy. Let's get this merged 😛

2018-10-19 10:35 UTC, gkalpak commented
Thx again for working in this, @nik72619c 👍

2018-10-19 10:37 UTC, nik72619c commented
Thank you for guiding me out @gkalpak !

2018-10-19 18:09 UTC, closed without merging