docs: update npm packages to be accurate for v7
angular/angular pull request #26422
Opened 2018-10-12 18:25 UTC by jenniferfell

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Npm packages doc was not current for v7.
* Referred to old version of node
* Described yarn as default for CLI, not npm
* package lists were not current

Issue Number: N/A

## What is the new behavior?

The doc needs a larger rewrite, but this PR is to make it accurate in the ways mentioned above. 

Also made some copy edits. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[X ] No
```

## Other information

2018-10-12 21:04 UTC, IgorMinar requested changes

2018-10-12 21:04 UTC, IgorMinar commented on aio/content/guide/npm-packages.md
> +## Dependencies
it would be great if we could say that to add a new "Dependency" to the list, developers should use the "ng add" command.

2018-10-12 21:04 UTC, IgorMinar commented on aio/content/guide/npm-packages.md
> +## DevDependencies
it would be great if we could say that to add a new "devDependency" to the list, developers should use the "npm install --dev" or "yarn add --dev" command.

2018-10-12 21:04 UTC, IgorMinar commented on aio/content/guide/npm-packages.md
> +See [Deployment](guide/deployment) to learn more.
instead we should point people to the build & serve docs to show them how all these packages come together to create a development (build & serve guide) and production (deployment guide) builds.

2018-10-13 16:16 UTC, mary-poppins commented
You can preview 5b38230 at https://pr26422-5b38230.ngbuilds.io/.

2018-10-13 22:05 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
> +## DevDependencies
done

2018-10-13 22:07 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
> +## Dependencies
done

2018-10-13 22:08 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
> +You don't deploy them with the production application, although there is no harm in doing so.
super. done

2018-10-13 22:09 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
good catch. thx. done

2018-10-13 22:39 UTC, mary-poppins commented
You can preview 697ceab at https://pr26422-697ceab.ngbuilds.io/.

2018-10-16 00:45 UTC, IgorMinar commented
there are still many unresolved comments on this pr

2018-10-16 19:18 UTC, IgorMinar commented on aio/content/guide/npm-packages.md
> +* `npm install --dev`
`npm install --dev <name-of-the-package>`

2018-10-16 19:18 UTC, IgorMinar commented on aio/content/guide/npm-packages.md
> +* `yarn add --dev`
add `<name-of-the-package>`

2018-10-17 18:47 UTC, mary-poppins commented
You can preview 4e3b615 at https://pr26422-4e3b615.ngbuilds.io/.

2018-10-17 21:05 UTC, mary-poppins commented
You can preview 2de0e55 at https://pr26422-2de0e55.ngbuilds.io/.

2018-10-17 21:06 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
> +* `yarn add --dev`
Done

2018-10-17 21:06 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
> +* `npm install --dev`
Done

2018-10-17 21:08 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
> +For a complete list of Angular packages (and links to package overviews), see the [API reference](http://angular.io/api?type=package). The following packages are included as dependencies in the initi
done

2018-10-17 21:10 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
>  This guide focuses on the most important packages in the starter set.
done and thanks for the link

2018-10-17 21:38 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
> +See [Deployment](guide/deployment) to learn more.
Done. Replaced "Managing packages and files" with a "Related information" section with links to build and deployment guides.

2018-10-17 21:59 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
>  Both `npm` and `yarn` install packages that are identified in a [**package.json**](https://docs.npmjs.com/files/package.json) file.
Added note about yarn back in above

2018-10-17 22:00 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
> -The [**yarn client**](https://yarnpkg.com/en/) is a popular alternative for downloading and installing npm packages.
Done.

2018-10-17 22:02 UTC, mary-poppins commented
You can preview b668c2d at https://pr26422-b668c2d.ngbuilds.io/.

2018-10-17 22:03 UTC, jenniferfell commented
@IgorMinar : Ready for another look. 

Q1: is package.json  workspace-scope  or project-scope? I see that ng new creates a package.json at the workspace level. I see that ng generate app does not create a package.json in my new app project under projects.

Current text: ”The CLI `ng new` command creates a default `package.json` file for your project.”

Seems like it should either be that `ng new` creates a `package.json` for your workspace, or that both `ng new` and `ng generate app` create `package.json` when they create projects?

* Q2: Page title “Angular packages and dependencies” and nav title “Packages and dependencies” ? OR “Angular package dependencies” and “Package dependencies” ? Just trying something other than “npm packages” if you have a quick pref to change.

* Q3: Are these the best URLs for the devDependencies that begin @angular? 

Thanks!

2018-10-18 14:31 UTC, IgorMinar approved these changes
A1: workspace scoped
A2:  neither is great. packages are dependencies. so we just repeat the same thing using two different words. how about: “npm dependencies” and “Workspace npm dependencies”?
A3: left in inline comment. the rest looks good.

2018-10-18 14:31 UTC, IgorMinar commented on aio/content/guide/npm-packages.md
>  **[@angular/language-service](https://github.com/angular/angular-cli/)**: The Angular language service analyzes component templates and provides type and error information that TypeScript-aware edito
I don't know why this points to the cli repo, but that's wrong. please remove the link.

2018-10-18 14:32 UTC, IgorMinar commented
I'm going to approve this because it's almost done. Let's change the title, resolve the other issues and get this in.

2018-10-18 17:39 UTC, mary-poppins commented
You can preview 5791c46 at https://pr26422-5791c46.ngbuilds.io/.

2018-10-19 00:38 UTC, Splaktar commented on aio/content/guide/npm-packages.md
>  The CLI `ng new` command creates a default `package.json` file for your project.
`project` should actually be `workspace` here.

2018-10-19 00:40 UTC, Splaktar commented
> Q1: is package.json workspace-scope or project-scope? I see that ng new creates a package.json at the workspace level. I see that ng generate app does not create a package.json in my new app project under projects.

> Current text: ”The CLI ng new command creates a default package.json file for your project.”

> Seems like it should either be that ng new creates a package.json for your workspace, or that both ng new and ng generate app create package.json when they create projects?

Right, as mentioned by Igor, `package.json` in the root of the workspace is workspace-scope. `ng g app` doesn't create a `package.json` for new projects added to the workspace in `projects/`.

I added a comment on the line that "project" should be "workspace" in this case.

Note that `ng g library` does however create a `package.json` for the library, but it's really there for publishing the library to NPM. It's not something that would be `npm install`ed in the project dir. I'm sure that the library details are covered elsewhere in the docs and doesn't need to be part of this page.

2018-10-19 17:48 UTC, mary-poppins commented
You can preview d1eb8bd at https://pr26422-d1eb8bd.ngbuilds.io/.

2018-10-19 19:06 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
>  **[@angular/language-service](https://github.com/angular/angular-cli/)**: The Angular language service analyzes component templates and provides type and error information that TypeScript-aware edito
Done

2018-10-19 19:07 UTC, jenniferfell commented on aio/content/guide/npm-packages.md
>  The CLI `ng new` command creates a default `package.json` file for your project.
Done

2018-10-19 19:33 UTC, jenniferfell commented
> Note that `ng g library` does however create a `package.json` for the library, but it's really there for publishing the library to NPM. It's not something that would be `npm install`ed in the project dir. I'm sure that the library details are covered elsewhere in the docs and doesn't need to be part of this page.

Thanks for this tip. I don't think it's covered in the AIO docs, and I don't see it clearly stated on the CLI wiki. In general, we're trying to do a better job of including information about library development (we have a few top-of-backlog items), so I included a brief mention and link to `ng generate` doc. We'll need to add more to that doc and address the backlog need for guide material, but I do think this is the right place to mention that libs have package.json files. Thanks again!

2018-10-19 20:34 UTC, mary-poppins commented
You can preview 296f04f at https://pr26422-296f04f.ngbuilds.io/.

2018-10-19 20:55 UTC, mary-poppins commented
You can preview a368f7c at https://pr26422-a368f7c.ngbuilds.io/.

2018-10-19 21:02 UTC, jenniferfell commented
@IgorMinar Here, again. I changed navigation.json so now the PR needs a fresh approval from someone in the marketing group. Thx.

2018-10-19 21:04 UTC, jenniferfell commented
Other than that approval, I think it's ready. I've incorporated all review feedback, updated and added cross-reference links, and moved the lists into tables that are easier to read. (When I added links, scanning the in-line titles became harder. The table fixes that.)

2018-10-20 00:50 UTC, Splaktar approved these changes
LGTM

2018-10-22 20:22 UTC, mary-poppins commented
You can preview d9415fb at https://pr26422-d9415fb.ngbuilds.io/.

2018-10-23 16:00 UTC, closed without merging