docs: update universal documentation as per starter
angular/angular pull request #26444
Opened 2018-10-15 08:30 UTC by alan-agius4

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
At them moment the docs here do not reflect the starter kit in https://github.com/angular/universal-starter

## What is the new behavior?

This PR aligns them.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2018-10-16 05:34 UTC, mary-poppins commented
You can preview 774835e at https://pr26444-774835e.ngbuilds.io/.

2018-10-16 05:34 UTC, mary-poppins commented
You can preview 4dec587 at https://pr26444-4dec587.ngbuilds.io/.

2018-10-17 07:52 UTC, mary-poppins commented
You can preview 28a0d15 at https://pr26444-28a0d15.ngbuilds.io/.

2018-10-17 15:28 UTC, mary-poppins commented
You can preview 1506a41 at https://pr26444-1506a41.ngbuilds.io/.

2018-10-18 12:09 UTC, mary-poppins commented
You can preview 71dcc89 at https://pr26444-71dcc89.ngbuilds.io/.

2018-10-29 14:22 UTC, brandonroberts commented
@alan-agius4 will you rebase this on master?

2018-10-29 14:28 UTC, alan-agius4 commented
rebase done

2018-10-29 14:33 UTC, mary-poppins commented
You can preview bcbba63 at https://pr26444-bcbba63.ngbuilds.io/.

2018-10-29 14:48 UTC, brandonroberts requested changes

2018-10-29 14:48 UTC, brandonroberts commented on aio/content/guide/universal.md
> +  **Note:** If you have Lazy Loaded modules togather with an App Shell you also need to configure `NgModuleFactoryLoader` as a server provider.
When using lazy loaded modules together with an app shell, you ...

2018-10-29 14:48 UTC, brandonroberts commented on aio/content/guide/universal.md
> -      "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
Will you also fix the "architect" text in this code example since this should reflect the `scripts` section in a `package.json` file?

2018-10-29 15:09 UTC, alan-agius4 commented on aio/content/guide/universal.md
> -      "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
Actually I updated this section as it was not correct.

2018-10-29 15:10 UTC, alan-agius4 commented on aio/content/guide/universal.md
> +  **Note:** If you have Lazy Loaded modules togather with an App Shell you also need to configure `NgModuleFactoryLoader` as a server provider.
updated

2018-10-29 15:13 UTC, mary-poppins commented
You can preview 63e5f7a at https://pr26444-63e5f7a.ngbuilds.io/.

2018-10-29 15:14 UTC, mary-poppins commented
You can preview afe4962 at https://pr26444-afe4962.ngbuilds.io/.

2018-10-29 15:30 UTC, jbogarthyde commented
LGTM --jb

2018-10-29 15:43 UTC, brandonroberts commented
@alan-agius4 the example dependencies need to be updated also. The `ts-loader` and `webpack-cli` dependencies should be removed from https://github.com/angular/angular/blob/master/aio/tools/examples/shared/package.json and https://github.com/angular/angular/blob/master/aio/tools/examples/shared/boilerplate/universal/package.json

You'll also need to run yarn in the `aio/tools/examples/shared` folder to update the `yarn.lock` file.

2018-10-29 17:07 UTC, alan-agius4 commented
@brandonroberts, Updated. Though `ts-node` needs to stay as it's required for angular-cli

2018-10-29 17:12 UTC, mary-poppins commented
You can preview f52c5a3 at https://pr26444-f52c5a3.ngbuilds.io/.

2018-10-29 17:19 UTC, brandonroberts commented
@alan-agius4 yes, but `ts-loader` is the one that should be removed.

2018-10-29 17:46 UTC, alan-agius4 commented
Sorry mate, been a long day. Pushed an update.

2018-10-29 17:50 UTC, mary-poppins commented
You can preview e61f017 at https://pr26444-e61f017.ngbuilds.io/.

2018-10-29 19:24 UTC, brandonroberts commented
@alan-agius4 something happened with the latest push and the other changes aren't showing.

2018-10-29 19:33 UTC, alan-agius4 commented
@brandonroberts, that was akward, don't know what happened, as everything was squashed.

I re-pushed.

2018-10-30 12:21 UTC, brandonroberts approved these changes

2018-11-05 13:40 UTC, brandonroberts commented
@alan-agius4 will you rebase this branch again?

2018-11-05 13:53 UTC, CaerusKaru commented
I want to begin by saying that this is excellent work, and almost all of it is perfect as-is. The only thing that needs to be changed is the Webpack -> TypeScript configuration change. While this was implemented in the Universal Starter, it ended up causing more headaches than it fixed. In the `@nguniversal` schematics, we've already reverted this change (with an optional flag to enable pure TypeScript behavior), and whenever I get some free time we'll be reverting the Universal Starter as well.

The reason behind this is that the TypeScript-only configuration only works if the Angular CLI's `bundleDependencies` feature works, which it doesn't. Without it, there are too many issues loading non-conformant libraries, thus requiring Webpack.

In a future update, we will update the docs to reflect using just the schematics, so that all of this is handled automatically, anyway.

2018-11-07 18:30 UTC, alan-agius4 commented
@CaerusKaru, thanks for your review. I updated as requested.

2018-11-07 18:32 UTC, mary-poppins commented
You can preview 04a9f80 at https://pr26444-04a9f80.ngbuilds.io/.

2018-11-07 18:36 UTC, mary-poppins commented
You can preview 81287e9 at https://pr26444-81287e9.ngbuilds.io/.

2018-11-08 14:49 UTC, brandonroberts commented on aio/content/guide/universal.md
> +  "build:client-and-server-bundles": "ng build --prod && ng run my-project:server:production",
Should "my-project" be "angular.io-example" here if they are following the guide?

2018-11-08 14:55 UTC, alan-agius4 commented on aio/content/guide/universal.md
> +  "build:client-and-server-bundles": "ng build --prod && ng run my-project:server:production",
I don't have any preference, I just kept the name that it is currently being used in this doc.

2018-11-08 15:18 UTC, brandonroberts commented on aio/content/guide/universal.md
> +  "build:client-and-server-bundles": "ng build --prod && ng run my-project:server:production",
I see. Its not part of the tutorial section, so I think its fine to leave as-is.

2018-11-15 14:51 UTC, brandonroberts commented
@IgorMinar will you review/approve this so it can land?

2019-01-03 07:12 UTC, mary-poppins commented
You can preview eed1a1a at https://pr26444-eed1a1a.ngbuilds.io/.

2019-01-10 23:57 UTC, IgorMinar approved these changes
This looks good to me, except that now that we had `ng add` shouldn’t this guide use that instead of manual setup? 

I think it’s fine to merge this as is, but we should follow up with refactoring this doc to rely on `ng add`.

@alan-agius4 can you please rebase this on top of master before  labeling this for merge? Thanks

2019-01-11 20:37 UTC, alan-agius4 commented
@IgorMinar, rebased

Yeah, indeed as as there is also a bit of confusion as in the CLI itself we have `ng generate universal`, which is a subset of what `ng add` does.

I'll open an issue tomorrow to keep track of it.

PS: I cannot change labels on angular/angular, I don't have access :(

2019-01-11 20:41 UTC, mary-poppins commented
You can preview 01303d3 at https://pr26444-01303d3.ngbuilds.io/.

2019-01-12 17:06 UTC, gkalpak commented
MArking it for merge based on the conversation above.

2019-01-14 18:12 UTC, closed without merging