Redirect if a guard returns a UrlTree
angular/angular pull request #26521
Opened 2018-10-17 16:52 UTC by jasonaden

2018-10-17 16:56 UTC, mary-poppins commented
You can preview ef48f54 at https://pr26521-ef48f54.ngbuilds.io/.

2018-10-17 17:10 UTC, benlesh requested changes
Only one small change I'd make.

2018-10-17 17:10 UTC, benlesh commented on packages/router/test/router.spec.ts
> +      .subscribe(
RxJS core team recommends using an Observer for all subscriptions that use more than one callback, like:

```ts
obs.subscribe({
  next(value) { },
  error(err) { }
});
```

2018-10-17 17:43 UTC, JoostK requested changes

2018-10-17 17:43 UTC, JoostK commented on packages/router/src/utils/type_guards.ts
> +  return guard && isFunction<CanActivateChild>(guard.canActivate);
```suggestion
  return guard && isFunction<CanActivateChild>(guard.canActivateChild);
```

2018-10-17 21:06 UTC, jasonaden commented on packages/router/test/router.spec.ts
> +      .subscribe(
Convention and more readable.

2018-10-17 21:46 UTC, benlesh approved these changes

2018-10-17 21:53 UTC, mary-poppins commented
You can preview a1f41fc at https://pr26521-a1f41fc.ngbuilds.io/.

2018-10-17 22:18 UTC, mary-poppins commented
You can preview 94328f9 at https://pr26521-94328f9.ngbuilds.io/.

2018-10-18 00:33 UTC, jasonaden commented
[Global Presubmit](https://test.corp.google.com/OCL:217592184:BASE:217619644:1539822702393:e18f5a52)

2018-10-18 07:10 UTC, sarunint reviewed
Great feature!

2018-10-18 07:10 UTC, sarunint commented on packages/router/src/interfaces.ts
> + *   ): Observable<boolean>|Promise<boolean>|boolean|UrlTree {
```suggestion
 *   ): Observable<boolean|UrlTree>|Promise<boolean|UrlTree>|boolean|UrlTree {
```

2018-10-18 07:10 UTC, sarunint commented on packages/router/src/interfaces.ts
> + *   ): Observable<boolean>|Promise<boolean>|boolean|UrlTree {
```suggestion
 *   ): Observable<boolean|UrlTree>|Promise<boolean|UrlTree>|boolean|UrlTree {
```

2018-10-18 07:10 UTC, sarunint commented on packages/router/src/interfaces.ts
> + *   ): Observable<boolean>|Promise<boolean>|boolean|UrlTree {
```suggestion
 *   ): Observable<boolean|UrlTree>|Promise<boolean|UrlTree>|boolean|UrlTree {
```

2018-10-18 07:10 UTC, sarunint commented on packages/router/src/interfaces.ts
> +    Observable<boolean>| Promise<boolean>| boolean;
```suggestion
    Observable<boolean|UrlTree>| Promise<boolean|UrlTree>| boolean | UrlTree;
```

2018-10-30 18:56 UTC, jasonaden commented on packages/router/src/interfaces.ts
> +    Observable<boolean>| Promise<boolean>| boolean;
We aren't actually adding this feature for `CanLoad` guards since this type of guard is really completely separate from the others (probably shouldn't have been called a `Guard` actually). But the other suggestions are great.

2018-10-30 19:12 UTC, mary-poppins commented
You can preview eeeb56b at https://pr26521-eeeb56b.ngbuilds.io/.

2018-10-30 19:31 UTC, mary-poppins commented
You can preview 43e34dc at https://pr26521-43e34dc.ngbuilds.io/.

2018-10-31 23:53 UTC, closed without merging

2018-12-14 14:31 UTC, myrddraall commented on packages/router/src/interfaces.ts
> +    Observable<boolean>| Promise<boolean>| boolean;
@jasonaden could you give a little more detail? why is canLoad different?