feat(ivy): resilient ngcc to invalid package.json
angular/angular pull request #26539
Opened 2018-10-18 13:17 UTC by cexbrayat

Some package.json files may have invalid JSON, for example package.json blueprints from `@schematics/angular` (see https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/workspace/files/package.json).

This makes ngcc more resilient, by simpling logging a warning if an error is encountered, instead of failing as it does right now.

cc @petebacondarwin as we talked about it on Slack.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

An invalid package.json file would make `ngcc` fail.

## What is the new behavior?

Simply logs a warning with the path of the invalid package.json and goes on.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2018-10-18 13:20 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/packages/entry_point.ts
>        EntryPointPackageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
Actually this is the only place we need to catch the error when trying to parse the JSON.
Is there a reason why you wrapped a much larger block of code?

2018-10-18 13:23 UTC, petebacondarwin requested changes
Nice PR @cexbrayat - thanks. I made a few comments.
Also I would make the commit message something like `fix(ivy): ngcc should not fail on invalid package.json`

2018-10-18 13:30 UTC, cexbrayat commented on packages/compiler-cli/src/ngcc/src/packages/entry_point.ts
>        EntryPointPackageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
The variables assigned are used in the whole bloc. I can only wrap `JSON.parse` but need to refactor like:

```typescript
  let entryPointPackageJson: EntryPointPackageJson;
  try {
    entryPointPackageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  } catch (e) {
    // We may have run into a package.json with unexpected symbols
    console.warn(`Failed to read entry point info from ${packageJsonPath} with error ${e}.`);
    return null;
  }

  // According to https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html,
  // `types` and `typings` are interchangeable.
  const {name, fesm2015, fesm5, esm2015, esm5, main, types, typings = types} = entryPointPackageJson;
```

Do you prefer that way?

2018-10-18 14:09 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/packages/entry_point.ts
>        EntryPointPackageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
I think I would prefer to move it to its own function... e.g

```ts
const entryPointPackageJson = loadEntryPoint(packageJsonPath);
if (!entryPointPackageJson) {
  return null;
}
```

2018-10-18 14:10 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/packages/entry_point.ts
>        EntryPointPackageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
```ts
function loadEntryPointPackage(packageJsonPath) {
  try {
    return JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  } catch (e) {
    // We may have run into a package.json with unexpected symbols
    console.warn(`Failed to read entry point info from ${packageJsonPath} with error ${e}.`);
    return null;
  }
}
```

2018-10-18 15:01 UTC, petebacondarwin approved these changes
LGTM thanks!

2018-10-18 15:02 UTC, petebacondarwin approved these changes
LGTM thanks!

2018-11-02 11:19 UTC, cexbrayat commented
@petebacondarwin I rebased on master and fixed conflicts now that your various PRs have landed.

2018-11-02 13:34 UTC, petebacondarwin approved these changes
Great! Thanks

2018-11-12 16:26 UTC, alxhub approved these changes

2018-11-12 17:37 UTC, cexbrayat commented on packages/compiler-cli/src/ngcc/src/packages/entry_point.ts
> +function loadEntryPointPackage(packageJsonPath: string): any|null {
@alxhub 👌 changed

2018-11-13 18:50 UTC, closed without merging