style: whitespaces in import statement and rename classname
angular/angular pull request #26583
Opened 2018-10-19 10:13 UTC by ashishpatelcs

Adding whitespaces in import statement and renamed classname from `SimpleFormComp` to `SimpleFormComponent`.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2018-10-19 12:34 UTC, brandonroberts commented
@ashishpatelcs you'll need to run `gulp format:changed` to format the files with clang. The `SimpleFormComp` needs to be updated in the `module.ts` file also.

2018-10-19 12:35 UTC, brandonroberts requested changes
Fix broken e2e tests

2018-10-25 22:30 UTC, kara commented
@ashishpatelcs Can you please squash the commits into 1 and fix the commit message according to our guidelines? https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

2018-12-04 14:37 UTC, brandonroberts commented
@ashishpatelcs are you still interested in landing this change?

2018-12-04 23:15 UTC, kara commented
Closing as stale. @ashishpatelcs Feel free to open a new PR if you'd like to address the comments.

2018-12-04 23:15 UTC, closed without merging