The comment output is wrong
angular/angular pull request #26804
Opened 2018-10-28 11:51 UTC by MasteRoi

Edited the comment to March instead of April

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2018-10-28 11:52 UTC, ericmartinezr commented
https://github.com/angular/angular/pull/26277#issuecomment-427458866

2018-10-28 15:12 UTC, alfaproject requested changes

2018-10-28 15:12 UTC, alfaproject commented on aio/content/examples/pipes/src/app/hero-birthday1.component.ts
> +  birthday = new Date(1988, 3, 15); // March 15, 1988
This is not wrong. The month is 0 based: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Parameters

2018-10-29 04:54 UTC, JoostK commented
You could perhaps change `3` into `4-1` and/or include a comment to clarify, seeing that you're not the only one misinterpreting this.

2018-11-01 12:30 UTC, closed without merging