docs: fix typo in testing guide
angular/angular pull request #26828
Opened 2018-10-29 17:24 UTC by courtneypattison

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

memory,based
Issue Number: N/A

## What is the new behavior?
memory, based

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## Other information

2018-11-01 14:33 UTC, brandonroberts approved these changes

2018-11-01 14:33 UTC, brandonroberts requested changes
Update git commit message to `docs: fix typo in testing guide`

2018-11-09 19:35 UTC, courtneypattison commented
Updated git commit message :)

2018-11-09 19:51 UTC, brandonroberts approved these changes

2019-01-14 16:18 UTC, brandonroberts approved these changes

2019-01-14 18:32 UTC, closed without merging