docs(examples): minor wording change in code example comment
angular/angular pull request #26835
Opened 2018-10-29 18:29 UTC by null-reference

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
No behaviour change; minor wording change in code example.

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2018-11-01 14:30 UTC, brandonroberts requested changes
Update git commit message to: `docs: minor wording change in code example comment`

2018-11-04 21:44 UTC, null-reference commented
Commit message updated.

2018-11-08 14:00 UTC, brandonroberts approved these changes

2019-01-14 16:16 UTC, brandonroberts approved these changes

2019-01-14 18:32 UTC, closed without merging