fix(ivy): restore missing match operation in View and Content Queries
angular/angular pull request #26847
Opened 2018-10-30 05:02 UTC by AndrewKushnir

This PR restores missing check when we query (view or content) using type predicate. Currently query logic may false-positively return more elements than needed. Also this PR unifies query logic for selector and predicate-based queries.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2018-10-30 05:07 UTC, mary-poppins commented
You can preview 21a949a at https://pr26847-21a949a.ngbuilds.io/.

2018-10-30 07:09 UTC, alfaproject commented on packages/core/src/render3/query.ts
> +function read(
Why not make this function a generic instead of using `any`?

2018-10-30 09:38 UTC, pkozlowski-opensource commented on packages/core/src/render3/query.ts
> +    tNode: TNode, currentView: LViewData, predicate: QueryPredicate<any>,
Maybe just pass the `read` part of the `QueryPredicate` as this is the only thing that you are using in this function?

2018-10-30 09:45 UTC, pkozlowski-opensource commented on packages/core/test/render3/query_spec.ts
> +
I would like to see another test with a selector-based directives (ex. `@ ViewChildren('foo',  {read: Child})` for a template like `<div #bar child>`

2018-10-30 09:46 UTC, pkozlowski-opensource commented on packages/core/test/render3/query_spec.ts
> +      it('should not add results to directive-based query if only read token matches', () => {
Isn't this test essentially the same as above? We are swapping `Child` and `OtherChild` around but this is is essentially the same case, no?

2018-10-30 09:51 UTC, pkozlowski-opensource commented on packages/core/src/render3/query.ts
> +          const result = read(tNode, currentView, predicate, directiveIdx);
Could we rename `directiveIdx` to something else here? The thing is that here we can get `-1` which will point to an element. Can't think of a good name, though... Maybe just `matchingIdx` as above?

BTW, as soon as you rename it to `matchingIdx` you will notice code duplication with the fragment above, maybe we should extract it to an utility function?

2018-10-31 09:18 UTC, pkozlowski-opensource commented on packages/core/test/render3/query_spec.ts
> +
@kara @AndrewKushnir the current view engine doesn't support using `ElementRef` as a predicate, check: https://stackblitz.com/edit/angular-i3hy3w

I think that it would be interesting to support it in the longer run as it would open up more dynamic queries (especially combined with new context discovery). Having said this there are probably plenty of corner cases here that we never thought out, so I would probably leave out support for `ElementRef ` for now - to be discussed / decided.

2018-10-31 09:22 UTC, pkozlowski-opensource commented on packages/core/src/render3/query.ts
> +      const matchingIdx = getIdxOfMatchingDirective(tNode, currentView, type);
@kara if we do the above than any type with `NG_ELEMENT_ID` could be used as a predicate and some of them would match lots of LNodes:
* `ElementRef` - every element, ng-container, template and container
* `ViewContainerRef` - same as above

It is also getting more interesting for other special types like `Renderer2` which I guess would match on each and every element?

As stated in the comment above, I would probably limit predicates to `TemplateRef` here or spend more time going through all those new cases and see if they make sense.

2018-10-31 17:12 UTC, kara commented on packages/core/src/render3/query.ts
> +      const matchingIdx = getIdxOfMatchingDirective(tNode, currentView, type);
Ah, I thought `ElementRef` was a valid predicate, but I suppose I should have double-checked. In that case, what @pkozlowski-opensource suggests with special casing `TemplateRef` makes more sense.

2018-11-01 16:51 UTC, mary-poppins commented
You can preview ed4165e at https://pr26847-ed4165e.ngbuilds.io/.

2018-11-05 18:46 UTC, kara requested changes

2018-11-05 18:46 UTC, kara commented on packages/core/test/render3/query_spec.ts
> +      it('should not add results to the query in case no match found (via TemplateRef)', () => {
This test description doesn't seem to match the test, given that there's no `TemplateRef`.

```suggestion
      it('should read a token from a query with a string predicate', () => {
```

2018-11-05 18:46 UTC, kara commented on packages/core/test/render3/query_spec.ts
> +            3, 0, [Child, OtherChild], [],
Should be 2 consts here. Same on 1034 and 1099.

2018-11-05 18:46 UTC, kara commented on packages/core/test/render3/query_spec.ts
> +            2, 0, [Child], [],
Should be 3 consts here

2018-11-05 18:46 UTC, kara commented on packages/core/test/render3/query_spec.ts
> +            elementStart(1, 'div');
Since this is an embedded template function, numbering always starts at 0.

2018-11-05 18:46 UTC, kara commented on packages/core/test/render3/query_spec.ts
> +            3, 0, [], [],
Consts should be 5

2018-11-05 18:46 UTC, kara commented on packages/core/src/render3/query.ts
> +        const factoryFn = type[NG_ELEMENT_ID];
Since we know this is `TemplateRef`, I think we can actually just use `createTemplateRef` directly instead of looking it up.

2018-11-05 18:46 UTC, kara commented on packages/core/src/render3/query.ts
> +          const result = queryRead(tNode, currentView, predicate.read || type);
If we query for `TemplateRef` and don't have a read, we're currently:

- creating a `TemplateRef` by calling the factory function and throwing it away
- passing `TemplateRef` into `queryRead()`, which then calls the same factory function again to create a second instance of `TemplateRef` and returning that. 

I think it might make more sense to check if there's a read token first. If there is a read, call `queryRead()` with the read token. If not, just return the result of the original factory function invocation to avoid calling it twice.

2018-11-05 18:46 UTC, kara commented on packages/core/src/render3/query.ts
> +function read(tNode: TNode, currentView: LViewData, token: any, matchingIdx: number): any {
Nit: I think this could use a more specific name, given that we have both `read` and `queryRead`.

2018-11-05 18:46 UTC, kara commented on packages/core/src/render3/query.ts
> +          }
I'm noticing that we have this `if (result !== null) { addMatch(...) }` block a few times. Perhaps we should move the `result` variable up a few levels and have a common `addMatch` block at the bottom. e.g.

```ts
let result: any;
if (type) {
  ...
  result = ...
} else {
...
  result = ...
}

if (result !== null) {
  addMatch(query, result);
}
```

2018-11-06 01:10 UTC, AndrewKushnir commented on packages/core/src/render3/query.ts
> +    tNode: TNode, currentView: LViewData, predicate: QueryPredicate<any>,
Done!

2018-11-06 01:11 UTC, AndrewKushnir commented on packages/core/src/render3/query.ts
> +          const result = read(tNode, currentView, predicate, directiveIdx);
I've renamed `directiveIdx` to `matchingIdx` as you proposed.

2018-11-06 01:11 UTC, AndrewKushnir commented on packages/core/test/render3/query_spec.ts
> +                element(1, 'div', ['foo', '']);
Fixed!

2018-11-06 01:41 UTC, AndrewKushnir commented
@kara @pkozlowski-opensource I've applied additional changes according to the most recent feedback. Could you plz have another look? Thank you.

2018-11-06 01:43 UTC, mary-poppins commented
You can preview 55b180b at https://pr26847-55b180b.ngbuilds.io/.

2018-11-06 18:34 UTC, kara requested changes

2018-11-06 18:34 UTC, kara commented on packages/core/src/render3/query.ts
> +            predicate.read ? queryRead(tNode, currentView, predicate.read) : type[NG_ELEMENT_ID]();
Hmm, this still doesn't look right to me. If you have a `TemplateRef` query with a `read` token, we should still be calling the `TemplateRef` factory function to ensure the result isn't null. Consider:

```ts
@ViewChild(TemplateRef, {read: ElementRef})
```

with a template of 

```html
<div></div>
```

With this code, I believe that `queryRead` would be called with `ElementRef`. `ElementRef` factory function would be called and we'd get an `ElementRef` for the div, even though it's not a valid `TemplateRef`.

We need a test for a `TemplateRef` query with a read on something like a div.

2018-11-06 22:16 UTC, mary-poppins commented
You can preview 751d0ea at https://pr26847-751d0ea.ngbuilds.io/.

2018-11-06 22:19 UTC, AndrewKushnir commented
Thanks for the review @kara! I've added missing case (and a test case to verify it) and did some refactoring. Could you please have another look? Thank you.

2018-11-07 22:45 UTC, kara approved these changes
LGTM, just a few nits

2018-11-07 22:45 UTC, kara commented on packages/core/src/render3/query.ts
> +    templateRef: any, tNode: TNode, currentView: LViewData, read: any): any {
Nit: maybe call this `templateRefToken` and type it `ViewEngine_TemplateRef` instead of `any`

2018-11-07 22:45 UTC, kara commented on packages/core/src/render3/query.ts
> +  return null;
What do you think of this?

```ts
  const templateRefResult = templateRef[NG_ELEMENT_ID]();
  if (read) {
    return templateRefResult ? queryByReadToken(read, tNode, currentView) : null;
  } else {
    return templateRefResult;
  }
```

2018-11-07 23:13 UTC, mary-poppins commented
You can preview 590be9e at https://pr26847-590be9e.ngbuilds.io/.

2018-11-08 00:30 UTC, closed without merging