fix(ivy): enable packages/core/test/render3 test for AoT
angular/angular pull request #26863
Opened 2018-10-31 00:04 UTC by mhevery

2018-10-31 00:07 UTC, mary-poppins commented
You can preview faf171b at https://pr26863-faf171b.ngbuilds.io/.

2018-11-01 17:36 UTC, mary-poppins commented
You can preview 5717104 at https://pr26863-5717104.ngbuilds.io/.

2018-11-01 18:04 UTC, mary-poppins commented
You can preview fb27d3b at https://pr26863-fb27d3b.ngbuilds.io/.

2018-11-01 22:34 UTC, mary-poppins commented
You can preview c2c5f7c at https://pr26863-c2c5f7c.ngbuilds.io/.

2018-11-01 23:27 UTC, IgorMinar requested changes
I love having this flag to disable individual tests or blocks of test but I think it should be implemented differently.

Can you define the const in https://github.com/angular/angular/tree/master/packages/private/testing as a test helper because the const/flag is not a property of the compiler but rather a build configuration flag for our repo. You can still use the genrule to generate a file with the const, and reexport that const from https://github.com/angular/angular/blob/master/packages/private/testing/index.ts

You can then import the const from @angular/private/testing into the jasmine and karma init scripts and use the const in the body of the fixmeIvy function defined in these init scripts.

Also, as we discussed we no longer need to compile the framework in the JIT mode, so we can get rid of this test and simplify the signature of `ivyFixMe` to just `function ivyFixMe(reason: string): boolean`.

And lastly, can you rename this function from `ivyFixMe` to `fixmeIvy` or rename all bazel tags from `fixme-ivy-*` to `ivy-*-fixme`, so that we don't have two ways of calling this at different levels?

These changes simplify the setup and ivy, remove the need to pollute the production compiler code and the reliance on the flag published on the global ng object.

2018-11-02 03:38 UTC, mhevery commented on package.json
> +}
reverted

2018-11-02 03:38 UTC, mhevery commented on packages/core/test/render3/pipe_spec.ts
> +  // In test we use @Component for documentation only.
fixed

2018-11-02 03:40 UTC, mhevery commented on tools/testing/init_node_spec.ts
> +(global as any).ivyFixMe = (mode: string) => mode !== (global as any).ng.ɵcompileMode;
you don't need reason here as it is for reader only.

2018-11-02 03:42 UTC, mhevery commented on packages/compiler/BUILD.bazel
> +## This file generates `src/ivy_switch.ts` file which reexports symbols for `ViewEngine` or `Ivy.`
updated.

2018-11-02 03:46 UTC, mhevery commented on tools/testing/init_browser_spec.ts
> +(window as any).ivyFixMe = () => true;
fixed.

2018-11-02 03:50 UTC, mhevery commented on packages/core/test/render3/pipe_spec.ts
> +  // In test we use @Directive for documentation only.
fixed

2018-11-02 03:50 UTC, mhevery commented on packages/core/test/render3/view_container_ref_spec.ts
> +  // In test we use @Component for documentation only.
fixed

2018-11-02 03:54 UTC, mhevery commented on packages/core/test/render3/load_domino.ts
> +  (global as any).ivyFixMe = (mode: string) => mode !== (global as any).ng.ɵcompileMode;
simplified.

2018-11-02 03:54 UTC, mhevery commented on packages/compiler/BUILD.bazel
> +## - append `--define=compile=jit` to `bazel` command to rexport `./ivy_switch_jit` and use `Ivy`
dropped

2018-11-02 04:04 UTC, mary-poppins commented
You can preview 23937f9 at https://pr26863-23937f9.ngbuilds.io/.

2018-11-02 04:31 UTC, mary-poppins commented
You can preview 01f64b1 at https://pr26863-01f64b1.ngbuilds.io/.

2018-11-02 09:16 UTC, IgorMinar approved these changes
Thanks for making all the changes. I left one more suggestion but the rest looks great!

2018-11-02 09:16 UTC, IgorMinar commented on packages/private/testing/src/fixme.ts
> +export function fixmeIvy(reason?: string): boolean {
can we make the reason required?

2018-11-02 09:16 UTC, IgorMinar commented on packages/private/testing/src/fixme.ts
> +export function fixmeIvy(reason?: string): boolean {
even "unknown reason" is better than no reason at all.

2018-11-02 09:17 UTC, IgorMinar commented on .circleci/config.yml
> -
oops.. there are more references to "test_ivy_jit" in this file that need to be removed.

2018-11-02 09:19 UTC, IgorMinar commented
and more more thing: to make cherry-picking easier we are trying to merge all major infrastructure changes to master and patch branch, so I relabeled this PR to master&patch.

2018-11-02 18:13 UTC, kara commented
@mhevery @IgorMinar Looks like the test_ivy_jit task is still failing with `Cannot find a job named `test_ivy_jit` to run in the `jobs:` section of your configuration file.`

2018-11-02 21:35 UTC, mary-poppins commented
You can preview 5e91b52 at https://pr26863-5e91b52.ngbuilds.io/.

2018-11-02 22:44 UTC, kara commented
FYI we will be creating a new PR for patch

2018-11-02 22:45 UTC, closed without merging

2018-11-02 23:13 UTC, mhevery commented
@IgorMinar I tried to patch this to `7.0.x` but the two branches have diverged too much to be able to do that. The issue is that `master` no longer has `ivy_switch` and the `7.0.x` still does.

2018-11-04 20:07 UTC, IgorMinar commented
OK. If it's too much work then it's ok to skip, but in that case can you at
least cherry pick the circle ci changes to reduce the load ok the ci?
Thanks

On Fri, Nov 2, 2018, 11:13 PM Miško Hevery <notifications@github.com wrote:

> @IgorMinar <https://github.com/IgorMinar> I tried to patch this to 7.0.x
> but the two branches have diverged too much to be able to do that. The
> issue is that master no longer has ivy_switch and the 7.0.x still does.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/26863#issuecomment-435535696>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AANM6IDRchlz8m5ycAbMlYM7i-mgjgJCks5urNGpgaJpZM4YDGsD>
> .
>