ngcc: re-export private NgModule declarations
angular/angular pull request #26906
Opened 2018-11-01 22:01 UTC by petebacondarwin

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2018-11-01 22:05 UTC, mary-poppins commented
You can preview fd6cbc6 at https://pr26906-fd6cbc6.ngbuilds.io/.

2018-11-01 22:10 UTC, mary-poppins commented
You can preview 1ae87b6 at https://pr26906-1ae87b6.ngbuilds.io/.

2018-11-01 23:42 UTC, Toxicable commented on packages/compiler-cli/src/ngcc/src/analysis/decoration_analyzer.ts
> +    compiledClasses.forEach(c => {
Looks like you've got `forEach` a few times here, unless im missing something they should be replace with for loops.
ref: https://github.com/angular/angular/blob/master/packages/core/src/render3/PERF_NOTES.md#loops

2018-11-01 23:48 UTC, JoostK commented on packages/compiler-cli/src/ngcc/src/analysis/decoration_analyzer.ts
> +    compiledClasses.forEach(c => {
@Toxicable those rules are mostly only adhered to in the runtime implementation, not in the compiler infrastructure.

2018-11-02 00:16 UTC, Toxicable commented on packages/compiler-cli/src/ngcc/src/analysis/decoration_analyzer.ts
> +    compiledClasses.forEach(c => {
I think it would be a good idea to adheard to in throughout the codebase.
But I see your point that changing it wouldn't produce any noticable impact to users.

2018-11-02 08:57 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/analysis/decoration_analyzer.ts
> +    compiledClasses.forEach(c => {
Interesting point @Toxicable. Performance is always a trade-off. In this case this function, `getPrivateDeclarations()` only gets called once per entry-point and also `rootFiles` should be very small (hopefully just 1 - although there might be stdlibs, etc).

Given the amount of calls to things like `map()` and `filter()` I doubt that optimising this particular bit of the code will make much difference.

Finally, using `forEach` in this case makes the code much more readable.

I intend to do some performance tuning later in the development cycle, but my initial experiments suggest that generating the TypeScript `Program` and `TypeChecker` take up about 70% of the processing time, so it is unlikely that tuning these loops will have negligible benefit to the speed of ngcc. But we will see!

2018-11-12 13:32 UTC, mary-poppins commented
You can preview 86732c9 at https://pr26906-86732c9.ngbuilds.io/.

2018-11-12 14:05 UTC, mary-poppins commented
You can preview 9ba0954 at https://pr26906-9ba0954.ngbuilds.io/.

2018-11-12 14:37 UTC, mary-poppins commented
You can preview 16fa15f at https://pr26906-16fa15f.ngbuilds.io/.

2018-11-12 14:46 UTC, JoostK commented on packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts
> +        return this.dtsClassMap.get(declaration.name.text) || null;
Yes, being less strict here resolves an issue for me as well 👍

2018-11-12 15:15 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts
> +        return this.dtsClassMap.get(declaration.name.text) || null;
Great! I think I am done with refactoring this. Ready for a proper review.

2018-11-12 15:16 UTC, mary-poppins commented
You can preview a75a204 at https://pr26906-a75a204.ngbuilds.io/.

2018-11-12 15:17 UTC, petebacondarwin commented
@alxhub, @JoostK & @gkalpak ready for a review. My big concern here is that there is no integration test of this functionality. I have checked that it works manually for me.

I would like to add a proper integration test, but I have been battling to move integration tests to use Bazel, and I think this is good enough to land now and then add the tests once Bazel tests are working properly.

2018-11-12 22:50 UTC, JoostK reviewed
I should have seen this PR earlier, as I should have used it as base commit (this badly conflicts with #27055, 😭)

2018-11-12 22:50 UTC, JoostK commented on packages/compiler-cli/src/ngcc/src/analysis/private_declarations_analyzer.ts
> +        const node = (reference.value as any).node;
This should be `WrappedNodeExpr` it seems. Could we introduce a function similar to `hasNameIdentifier` to make that a bit more explicit?

2018-11-12 22:50 UTC, JoostK commented on packages/compiler-cli/src/ngcc/test/analysis/private_declarations_analyzer_spec.ts
> +           {identifier: 'ComponentB', from: '/src/b.js', dtsFrom: null},
Come to think of it, could we rename the symbols such that they reflect what is special about them? I had a hard time figuring out how `ComponentB` differs from `ComponentC`.

2018-11-12 22:50 UTC, JoostK commented on packages/compiler-cli/src/ngcc/src/packages/transformer.ts
> +        format, reflectionHost, isCore, r3SymbolsFile, entryPointFile, dtsEntryPoint);
The `entryPointFile` and `dtsEntryPoint` seem like symbols that could fit within the `BundleInfo` I just introduced:

https://github.com/angular/angular/pull/27055/commits/a1f12712a837dfa8daf48ab62d667ad5459381a2#diff-cfb1d3ef1d964c8d5401a9b3afeb3037R15

Let's see if that concept sticks. It would at least alleviate the chance of conflicts.

2018-11-12 22:50 UTC, JoostK commented on packages/compiler-cli/src/ngcc/src/rendering/esm_renderer.ts
> +            `There is no typings path for ${privateExport.identifier} in ${privateExport.from}`);
Can we elaborate on why having a typings file is important. Basically for the reasons outlined in the  commit message but then targeting an end user.

2018-11-12 22:50 UTC, JoostK commented on packages/compiler-cli/src/ngcc/src/rendering/esm_renderer.ts
> +      const basePath = fromPath.replace(/\.(js|d\.ts$)/, '');
Should include `$` for js as well:

```suggestion
      const basePath = fromPath.replace(/\.(js|d\.ts)$/, '');
```

2018-11-12 22:50 UTC, JoostK commented on packages/compiler-cli/src/ngcc/src/rendering/renderer.ts
> +      const entryPointBasePath = this.entryPoint.fileName.replace(/\.(js|d\.ts$)/, '');
```suggestion
      const entryPointBasePath = this.entryPoint.fileName.replace(/\.(js|d\.ts)$/, '');
```

2018-11-13 08:38 UTC, mary-poppins commented
You can preview ef5fafc at https://pr26906-ef5fafc.ngbuilds.io/.

2018-11-13 08:51 UTC, mary-poppins commented
You can preview c9e8d33 at https://pr26906-c9e8d33.ngbuilds.io/.

2018-11-13 09:16 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/packages/transformer.ts
> +        format, reflectionHost, isCore, r3SymbolsFile, entryPointFile, dtsEntryPoint);
I am loathe to introduce another vague term that is a collection of "stuff": `Package`, `Module`, `EntryPoint`, `Bundle` etc

This `Bundle` concept is only used for rendering, right? So perhaps we could put it all together into an `AnalyzedEntryPoint` object, which contains everything the renderer needs to do its work?

2018-11-13 09:20 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/packages/transformer.ts
> +        format, reflectionHost, isCore, r3SymbolsFile, entryPointFile, dtsEntryPoint);
But generally I like the idea of an object to hold this stuff.

2018-11-13 14:42 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/packages/transformer.ts
> +        format, reflectionHost, isCore, r3SymbolsFile, entryPointFile, dtsEntryPoint);
I have refactored the code to use a similar idea, `EntryPointBundle` after a discussion offline with @JoostK.

2018-11-13 14:46 UTC, mary-poppins commented
You can preview 3817acb at https://pr26906-3817acb.ngbuilds.io/.

2018-11-13 14:49 UTC, mary-poppins commented
You can preview cfed4e1 at https://pr26906-cfed4e1.ngbuilds.io/.

2018-11-13 14:58 UTC, mary-poppins commented
You can preview 1957035 at https://pr26906-1957035.ngbuilds.io/.

2018-11-20 09:19 UTC, alxhub requested changes

2018-11-20 10:03 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/analysis/decoration_analyzer.ts
> +    const analyzedFiles =
Just trying to be consistent :-)

2018-11-20 10:07 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts
> +      if (declaration && ts.isClassDeclaration(declaration) && !dtsClassMap.has(name)) {
This can happen because we are not only looking at exports in `srcFile` but also exports from other source files too. `collectExportedClasses` gets called for each source file in the program, and each one adds to the `dtsMap`.

It is true that only one could ever be exported publicly from the entry-point, but this PR has to deal with "internal" classes too.

2018-11-20 10:08 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/analysis/decoration_analyzer.ts
> +        declarations.push(...c.analysis.ngModuleDef.declarations);
OK, I guess you mean `DecoratorHandler` there?

2018-11-20 11:04 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/analysis/decoration_analyzer.ts
> +        declarations.push(...c.analysis.ngModuleDef.declarations);
I just realised that we probably ought to check the `imports`, `exports` and `bootstrap` collections too, right? You could have a scenario where an `NgModule` references another `NgModule`, as an import say, but that second `NgModule` is not publicly exported... right?

2018-11-21 11:32 UTC, mary-poppins commented
You can preview 224b691 at https://pr26906-224b691.ngbuilds.io/.

2018-11-21 11:53 UTC, petebacondarwin commented
@alxhub and @JoostK I have completely refactored the private exports bit of this PR. I also moved all the refactoring of entry-point bundles to the start of the PR so that it is not dependent upon the private export stuff. This means that it would be reusable if we decided not to take the last few commits.

PTAL!

2018-11-21 12:44 UTC, mary-poppins commented
You can preview 6920a45 at https://pr26906-6920a45.ngbuilds.io/.

2018-11-21 15:51 UTC, alxhub approved these changes

2018-11-21 15:51 UTC, alxhub commented on packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts
> +      const declaration = exportedSymbol.declarations[0];
I'm not sure about the ordering of `declarations` here -- we could probably check `.valueDeclaration` and not `.declarations[0]`.

2018-11-21 15:51 UTC, alxhub commented on packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts
> +      if (declaration && ts.isClassDeclaration(declaration) && !dtsClassMap.has(name)) {
I think we should still do something other than silently ignore when there's more than one class with the same name. Can we store an array of them, or put a special marker in the `Map` that will cause an error if we try to publicly export one of these?

2018-11-21 15:51 UTC, alxhub commented on packages/compiler-cli/src/ngcc/src/packages/entry_point.ts
> +export type EntryPointFormat = keyof(EntryPointPaths);
I don't mind either way, but the parentheses here are optional, `keyof EntryPointPaths` works just as well.

In general this change appears to be a nice simplification! 🥂

2018-11-21 15:51 UTC, alxhub commented on packages/compiler-cli/src/ngcc/src/packages/transformer.ts
> +    const r3SymbolsPath =
Help me understand a little here - what happens if the current entypoint is a FESM file where there's no individual `r3_symbols` file to import from?

2018-11-21 16:12 UTC, JoostK commented on packages/compiler-cli/src/ngcc/src/packages/transformer.ts
> +    const r3SymbolsPath =
@alxhub for FESMs it works for the same reason as outlined in #27055 (no imports will be generated at all when compiling core). The ESM bundles are currently broken however (they reference `@angular/core` imports from within core itself); that is actually being fixed in #27055.

2018-11-21 19:22 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/references_registry.ts
> +    // ngtsc compilation.
This comment could use some more context, specifically the mention of ngcc that is currently the only consumer of this logic. It's now confusing that `ngtsc` contains code that it apparently doesn't use itself.

Thinking about this more, we might want to convert `ReferencesRegistry` into an interface and pass an `IntoTheVoidRegistry` 😉  with ngtsc, and move the current impl to ngcc such that this logic becomes ngcc specific. Doing so would also justify this implementation's choice to only store `ResolvedReference`s and ignore all others.

2018-11-21 19:36 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/src/references_registry.ts
> +    // ngtsc compilation.
Yes I like that idea.

2018-11-21 19:37 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts
> +      const declaration = exportedSymbol.declarations[0];
I think there was a reason why I used `declarations[0]` rather than `valueDeclaration` but I can't remember now. I'll take a look and check.

2018-11-21 19:58 UTC, JoostK commented on packages/compiler-cli/src/ngcc/src/rendering/esm_renderer.ts
> +    privateExports.forEach(privateExport => {
This `addExports` now has a much different signature compared to `addImports`. I think the logic that is now in this method should be computed by the caller, similar to how `addImports` only gets the import data.

2018-11-21 20:53 UTC, mary-poppins commented
You can preview 6ef8be2 at https://pr26906-6ef8be2.ngbuilds.io/.

2018-11-21 20:53 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts
> +      const declaration = exportedSymbol.declarations[0];
I switched it and no tests fail, so... let's go with `valueDeclaration` until something breaks.
(I agree that we are only interested in concrete classes here, so they should have a value declaration).

2018-11-21 21:02 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts
> +      if (declaration && ts.isClassDeclaration(declaration) && !dtsClassMap.has(name)) {
There are two scenarios, we should deal with:

1) There is both a public and one or more internal exports with the same name.
2) There is no public but more than one internal export with the same name.

In most cases it is the public one we are after, right? So should we just ignore additional internal matching names?

But if we are trying to create an export for an internal class and we have multiple classes with the same name, then I think this should probably error, since we don't know which we are supposed to be exporting.

2018-11-21 21:04 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts
> +      if (declaration && ts.isClassDeclaration(declaration) && !dtsClassMap.has(name)) {
So I think that the best solution is for `getDtsDeclarationOfClass` to return an array of possible declarations, with the public one (if any) first. The user of `getDtsDeclarationOfClass` then has to decide whether having more than one result is an error or not.

2018-11-22 11:46 UTC, petebacondarwin commented
The current rebase broke the fix from @JoostK for r3 symbols in .d.ts files. I have it fixed locally but I need to rework the changes back into the commits - again!

2018-11-25 11:30 UTC, mary-poppins commented
You can preview 3aed964 at https://pr26906-3aed964.ngbuilds.io/.

2018-11-25 22:34 UTC, mary-poppins commented
You can preview 6f21d4e at https://pr26906-6f21d4e.ngbuilds.io/.

2018-11-25 22:38 UTC, mary-poppins commented
You can preview 1635469 at https://pr26906-1635469.ngbuilds.io/.

2018-11-26 09:41 UTC, mary-poppins commented
You can preview e10bce0 at https://pr26906-e10bce0.ngbuilds.io/.

2018-11-26 14:38 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/rendering/esm_renderer.ts
> +    privateExports.forEach(privateExport => {
Ahah! I just realised that I did not address this @JoostK ... I'll take a look tonight

2018-11-26 14:58 UTC, mary-poppins commented
You can preview 59f21c9 at https://pr26906-59f21c9.ngbuilds.io/.

2018-11-26 15:00 UTC, petebacondarwin commented on packages/compiler-cli/src/ngcc/src/rendering/esm_renderer.ts
> +    privateExports.forEach(privateExport => {
I simplified it a bit.

2018-11-26 15:50 UTC, mary-poppins commented
You can preview f044bc7 at https://pr26906-f044bc7.ngbuilds.io/.

2018-11-26 16:31 UTC, mary-poppins commented
You can preview 3419c2b at https://pr26906-3419c2b.ngbuilds.io/.

2018-11-26 18:57 UTC, JoostK reviewed
Looks great!

<sup>PS. Where did my code go? 😝</sup>

2018-11-26 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/references_registry.ts
> +  getDeclarationMap(): Map<ts.Identifier, Declaration>;
I think this accessor can be removed from the interface, as it's only consumed by ngcc and perhaps specific to ngcc as well. The `Registry` part of the name would then become inaccurate though, so perhaps this is just fine here.

2018-11-26 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngcc/src/packages/entry_point_bundle.ts
> +  src: BundleProgram;
I like this, makes sense and achieves quite a cleanup in the transformer 👍

2018-11-26 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngcc/src/rendering/esm5_renderer.ts
> +      protected host: NgccReflectionHost, isCore: boolean, bundle: EntryPointBundle,
Looks like the `protected` can be dropped

2018-11-26 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngcc/test/rendering/renderer_spec.ts
> +                'foo(x: number): number;\n    static ngDirectiveDef: ɵngcc0.ɵDirectiveDefWithMeta');
I realize that there's no such test for `@angular/core`, in which we expect `ngDirectiveDef: DirectiveDefWithMeta`. I did add that assertion to the integration test but might as well test it from here.

2018-11-26 22:19 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/src/references_registry.ts
> +  getDeclarationMap(): Map<ts.Identifier, Declaration>;
I'll see what @alxhub says but my inclination would be to leave it in place for now.

2018-11-26 23:06 UTC, JoostK commented on packages/compiler-cli/src/ngcc/test/rendering/renderer_spec.ts
> +                'foo(x: number): number;\n    static ngDirectiveDef: ɵngcc0.ɵDirectiveDefWithMeta');
Sure!

2018-11-27 08:08 UTC, mary-poppins commented
You can preview c1139c0 at https://pr26906-c1139c0.ngbuilds.io/.

2018-11-28 17:11 UTC, mhevery approved these changes

2018-11-28 17:13 UTC, mhevery commented
http://test/OCL:223178683:BASE:223178801:1543425187595:be63129f

2018-11-29 08:44 UTC, petebacondarwin commented
Caretaker: can you check the status of the presubmit and then merge if all is good?

2018-11-30 05:37 UTC, IgorMinar commented
OCL:223178683:BASE:223462597:1543556237402:8cd641d9

2018-11-30 21:09 UTC, IgorMinar commented
http://test/OCL:223563071:BASE:223563100:1543612151002:79d21975

2018-11-30 22:03 UTC, closed without merging