docs(forms): update API reference for validator directives
angular/angular pull request #26926
Opened 2018-11-02 18:07 UTC by brandonroberts

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2018-11-02 18:12 UTC, mary-poppins commented
You can preview d47cc89 at https://pr26926-d47cc89.ngbuilds.io/.

2018-12-03 17:07 UTC, brandonroberts commented
@kara this one is ready for review

2018-12-04 23:26 UTC, kara requested changes

2018-12-10 14:19 UTC, mary-poppins commented
You can preview 46cc019 at https://pr26926-46cc019.ngbuilds.io/.

2018-12-11 23:33 UTC, kara requested changes
A few more changes, sorry!

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> + * Provider which adds `CheckboxRequiredValidator` to the `NG_VALIDATORS` mult-iprovider list.
```suggestion
 * Provider which adds `CheckboxRequiredValidator` to the `NG_VALIDATORS` multi-provider list.
```

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> +   * Tracks changes to the required attribute bound to this directive is required.
```suggestion
   * Tracks changes to the required attribute bound to this directive.
```

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> +   * Method that receives a control to validate against if required.
Might be easier to understand this way (had to read it a few times because I thought it was saying we were validating whether or not the control was required, rather than only validating if the control was required)

```suggestion
   * Method that validates whether the control is empty.
```

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> +   * Returns the validation result if required, otherwise null.
```suggestion
   * Returns the validation result if enabled, otherwise null.
```

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> +   * Returns the validation result if required, otherwise null.
```suggestion
   * Returns the validation result if enabled, otherwise null.
```

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> +   * Method that receives a control to validate against if required to be true.
```suggestion
   * Method that validates whether or not the checkbox has been checked.
```

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> +   * Method that receives a control to validate whether the email is valid.
```suggestion
   * Method that validates whether an email address is valid.
```

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> + * Defines a function that receives a control and synchronously returns a map of
```suggestion
 * A function that receives a control and synchronously returns a map of
```

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> + * Defines a function that receives a control and returns a Promise or observable
```suggestion
 * A function that receives a control and returns a Promise or observable
```

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> +   * Method that receives a control to validate whether the value meets the minimum length
```suggestion
   * Method that validates whether the value meets a minimum length
```

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> +   * Method that receives a control to validate whether the value exceeds
```suggestion
   * Method that validates whether the value exceeds
```

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> +   * Tracks changes to the the pattern bound to this directive.
```suggestion
   * Tracks changes to the pattern bound to this directive.
```

2018-12-11 23:33 UTC, kara commented on packages/forms/src/directives/validators.ts
> +   * Method that receives a control to validate whether the value matches the
```suggestion
   * Method that validates whether the value matches the
```

2018-12-14 21:44 UTC, kara approved these changes
LGTM

2018-12-17 17:49 UTC, mary-poppins commented
You can preview 34a5403 at https://pr26926-34a5403.ngbuilds.io/.

2018-12-17 18:32 UTC, brandonroberts commented
@kara will you run presubmit and approve again. Pullapprove didn't update the status. Thanks

2018-12-17 23:48 UTC, kara approved these changes

2018-12-18 00:46 UTC, closed without merging