feat(ivy): introduce the `animate` pipe for styling bindings
angular/angular pull request #26931
Opened 2018-11-02 22:50 UTC by matsko

2018-11-02 23:02 UTC, mary-poppins commented
You can preview 7f1a9be at https://pr26931-7f1a9be.ngbuilds.io/.

2018-11-03 15:54 UTC, JoostK requested changes

2018-11-03 15:54 UTC, JoostK commented on packages/core/src/render3/animations/util.ts
> +  return window ? window.performance && window.performance.now() : Date.now();
There's a bug here, should be:

```suggestion
  return window && window.performance && window.performance.now() || Date.now();
```

2018-11-03 15:54 UTC, JoostK commented on packages/core/src/render3/styling/util.ts
> +    player.status.subscribe(state => {
This subscription is not unsubscribed from, nor is the `status` `Subject` being completed, so this will probably leak by the looks of it.

2018-11-03 15:54 UTC, JoostK commented on packages/core/src/render3/animations/util.ts
> +  let val = (gcs as any)[prop];
nit:

```suggestion
  const val = (gcs as any)[prop] || gcs.getPropertyValue(prop);
```

2018-11-03 15:54 UTC, JoostK commented on packages/core/src/render3/animations/css_transition_animator.ts
> +      store[className] = revert ? false : true;
nit:
```suggestion
      store[className] = !revert;
```

2018-11-03 15:54 UTC, JoostK commented on packages/core/src/render3/animations/css_transition_animator.ts
> +    revert?: boolean, store?: {[key: string]: any} | null) {
nit: what I think is strange is that `backupStyles` is not optional, whereas its read is conditional on the optional `revert` param being true.

2018-11-03 15:54 UTC, JoostK commented on packages/core/src/render3/animations/util.ts
> +    duration = <number>exp;
nit: cast should have been inferred?

2018-11-03 15:54 UTC, JoostK commented on packages/core/src/render3/animations/util.ts
> +  let w = element.clientWidth + 1;
nit:

```suggestion
  const w = element.clientWidth + 1;
```

2018-11-03 15:54 UTC, JoostK commented on packages/core/src/render3/animations/animate_pipe.ts
> +  let animator = ANIMATOR_MAP.get(element) as CssTransitionAnimator;
nit: redundant cast

2018-11-03 15:54 UTC, JoostK commented on packages/core/src/render3/animations/css_transition_animator.ts
> +          cb();
This looks broken? I expect smth like:
```suggestion
          this._waitingForFrameFns[i]();
```

But then `cb` wouldn't be exectuted at all. I am a bit puzzled by this piece of logic.

2018-11-03 15:54 UTC, JoostK commented on packages/core/src/render3/animations/interfaces.ts
> +  fill: FillMode|null|undefined;
What's the meaning of `null` vs `undefined` for the above properties?

2018-11-03 15:54 UTC, JoostK commented on packages/core/src/render3/animations/interfaces.ts
> +  onAllEffectsDone(cb: () => any): void;
```suggestion
  onAllEffectsDone(cb: () => void): void;
```

2018-11-06 09:16 UTC, matsko commented on packages/core/src/render3/animations/interfaces.ts
> +  onAllEffectsDone(cb: () => any): void;
This is needed so you can do something like `onAllEffectsDone(x => foo());` (incase `foo()` returns something ... otherwise typings would fail)

2018-11-06 10:32 UTC, gkalpak commented on packages/core/src/render3/animations/interfaces.ts
> +  onAllEffectsDone(cb: () => any): void;
It is perfectly fine to use a function with a non-void return type in place of a `() => void` function (e.g. see https://github.com/Microsoft/TypeScript/issues/20006#issuecomment-344343843).
(There are discussions about changing that.)

If you wanted to be fancy (and safe), you could use `() => unknown` 😛

2018-11-06 23:40 UTC, mary-poppins commented
You can preview 6a548fe at https://pr26931-6a548fe.ngbuilds.io/.

2018-11-08 09:16 UTC, trotyl commented on packages/core/test/render3/animations/animate_pipe_spec.ts
> +  it('should produce return a PlayerFactory when the pipe is executed', () => {
```suggestion
  it('should return a PlayerFactory when the pipe is executed', () => {
```

2018-11-11 15:55 UTC, mary-poppins commented
You can preview a6789ad at https://pr26931-a6789ad.ngbuilds.io/.

2018-11-11 18:34 UTC, mary-poppins commented
You can preview 30d7ce1 at https://pr26931-30d7ce1.ngbuilds.io/.

2018-11-12 09:44 UTC, mary-poppins commented
You can preview 5e9d7b4 at https://pr26931-5e9d7b4.ngbuilds.io/.

2018-11-14 01:00 UTC, mary-poppins commented
You can preview ee19734 at https://pr26931-ee19734.ngbuilds.io/.

2018-11-14 12:41 UTC, mary-poppins commented
You can preview 63fa062 at https://pr26931-63fa062.ngbuilds.io/.

2018-11-14 13:12 UTC, mary-poppins commented
You can preview 2e5ba0f at https://pr26931-2e5ba0f.ngbuilds.io/.

2018-11-14 13:20 UTC, mary-poppins commented
You can preview 90be434 at https://pr26931-90be434.ngbuilds.io/.

2018-11-26 12:15 UTC, mary-poppins commented
You can preview 55251b6 at https://pr26931-55251b6.ngbuilds.io/.

2018-11-26 12:19 UTC, matsko commented on packages/core/src/render3/animations/animate_pipe.ts
> +const ANIMATOR_MAP = new WeakMap<HTMLElement, Animator>();
The old animation expando code is unrelated to this one. The ivy monkey patching could in theory be used, but the AnimatePipe lookup code is not as performance-critical as the internal element context lookup. Also, we know 100% that we are using the DOM here, so a WeakMap does ensure if the DOM node is removed then the map is cleaned up.

2018-11-26 12:20 UTC, matsko commented on packages/core/src/render3/animations/util.ts
> +  const regex = /^(-?[\.\d]+)(m?s)(?:\s+(-?[\.\d]+)(m?s))?(?:\s+([-a-z]+(?:\(.+?\))?))?$/i;
fixed

2018-11-26 12:20 UTC, matsko commented on packages/core/src/render3/animations/animate_pipe.ts
> +export class AnimatePipeModule {
This is temporary until the labs entry point is ready.

2018-11-26 12:20 UTC, matsko commented on packages/core/src/render3/animations/css_transition_animator.ts
> + * uses uses the `transitionend` event to detect for animations that
fixed

2018-11-26 12:21 UTC, matsko commented on packages/core/src/render3/animations/css_transition_animator.ts
> + * For this to work, all the styles are classes are applied onto the
fixed

2018-11-26 12:55 UTC, mary-poppins commented
You can preview 61e800c at https://pr26931-61e800c.ngbuilds.io/.

2018-12-05 18:48 UTC, mary-poppins commented
You can preview 6fdf1d3 at https://pr26931-6fdf1d3.ngbuilds.io/.

2018-12-05 19:16 UTC, mary-poppins commented
You can preview 94adb4d at https://pr26931-94adb4d.ngbuilds.io/.

2018-12-05 19:55 UTC, mary-poppins commented
You can preview f98fe37 at https://pr26931-f98fe37.ngbuilds.io/.

2018-12-05 19:59 UTC, mary-poppins commented
You can preview 06b03e3 at https://pr26931-06b03e3.ngbuilds.io/.

2018-12-05 21:02 UTC, mary-poppins commented
You can preview dd02c54 at https://pr26931-dd02c54.ngbuilds.io/.

2018-12-05 21:02 UTC, mary-poppins commented
You can preview 13fe0dc at https://pr26931-13fe0dc.ngbuilds.io/.

2018-12-05 21:02 UTC, mary-poppins commented
You can preview df73dbf at https://pr26931-df73dbf.ngbuilds.io/.

2018-12-05 22:03 UTC, mary-poppins commented
You can preview 1d1e08d at https://pr26931-1d1e08d.ngbuilds.io/.

2018-12-05 22:07 UTC, mary-poppins commented
You can preview 67ce48f at https://pr26931-67ce48f.ngbuilds.io/.

2018-12-05 22:34 UTC, mary-poppins commented
You can preview 8f0c799 at https://pr26931-8f0c799.ngbuilds.io/.

2018-12-06 15:18 UTC, mary-poppins commented
You can preview f1d1d6b at https://pr26931-f1d1d6b.ngbuilds.io/.

2018-12-07 19:09 UTC, mary-poppins commented
You can preview bbe62d3 at https://pr26931-bbe62d3.ngbuilds.io/.

2018-12-11 19:01 UTC, mary-poppins commented
You can preview 6826828 at https://pr26931-6826828.ngbuilds.io/.

2019-04-24 14:26 UTC, mohammedzamakhan commented
@matsko I was excited about `animate` pipe, but don't see it landing in labs too :(

2019-07-19 17:44 UTC, closed without merging