Glossary update: add architect terms and xrefs to new pages
angular/angular pull request #26963
Opened 2018-11-06 20:32 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2018-11-06 20:36 UTC, mary-poppins commented
You can preview c04f0c4 at https://pr26963-c04f0c4.ngbuilds.io/.

2018-11-07 23:29 UTC, mary-poppins commented
You can preview 76df0cd at https://pr26963-76df0cd.ngbuilds.io/.

2018-11-08 18:30 UTC, hansl commented
One comment, otherwise looks good to me.

2018-11-08 21:02 UTC, mary-poppins commented
You can preview 24b7b18 at https://pr26963-24b7b18.ngbuilds.io/.

2018-11-08 21:06 UTC, mary-poppins commented
You can preview 23ca3c8 at https://pr26963-23ca3c8.ngbuilds.io/.

2018-11-09 16:30 UTC, mary-poppins commented
You can preview 96086f6 at https://pr26963-96086f6.ngbuilds.io/.

2018-11-12 16:13 UTC, mary-poppins commented
You can preview c299fd6 at https://pr26963-c299fd6.ngbuilds.io/.

2018-11-13 16:42 UTC, mary-poppins commented
You can preview e14ffed at https://pr26963-e14ffed.ngbuilds.io/.

2018-11-15 19:31 UTC, jenniferfell reviewed
Some questions. Not sure if they can be resolved in this pass, so not making them blocking. I feel like we're 90% of the way there on some of these definitions, which is pretty good...so my brain pushes for more because it feels so close.

2018-11-15 19:31 UTC, jenniferfell commented on aio/content/guide/glossary.md
> +Additional project-specific configuration files are used by subsystems and tools, such as `package.json` for the [npm package manager](#npm-package), and `tsconfig.json` for [TypeScript transpilation
I like this :-)

2018-11-15 19:31 UTC, jenniferfell commented on aio/content/guide/glossary.md
> +In Angular, a standalone application or [library](guide/glossary#library) in a [workspace](#workspace).
Hmmm. One thing I liked about the original/previous definition is that it makes it clear that project is a dev-time construct. An app or library exists in both dev-time and runtime contexts. The app or library is what you're developing; a project is the context in which you do that development. It's the set of source files and related config files needed to dev, test?, and deploy the app or library.

2018-11-15 19:31 UTC, jenniferfell commented on aio/content/guide/glossary.md
> +Most Architect targets correspond to [CLI commands](#cli), such as `build`, `serve`, `test`, and `lint`.
I like how this focuses on the end result. How does that mesh with the description of ng run, where the target is the config file itself? Maybe just refine that doc as a follow-on step to match this idea of target as destination, and that command needs the config file associated with that destination/end result?

2018-11-15 19:31 UTC, jenniferfell commented on aio/content/guide/glossary.md
> +Most Architect targets correspond to [CLI commands](#cli), such as `build`, `serve`, `test`, and `lint`.
Positioning: Link to Architect definition. Mention that ng run makes it possible to use custom builders and targets, as a parallel to the internal pre-defined targets mentioned here (build, serve, test, lint)?

2018-11-15 21:32 UTC, mary-poppins commented
You can preview aef6376 at https://pr26963-aef6376.ngbuilds.io/.

2018-11-15 21:56 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +The tool that the CLI uses to perform complex tasks such as compilation and test running, according to provided configurations.  Architect is a shell that runs a specific *builder* (an [npm package](
Added ##builder

2018-11-15 21:58 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +The tool that the CLI uses to perform complex tasks such as compilation and test running, according to provided configurations.  Architect is a shell that runs a specific *builder* (an [npm package](
The positioning is not clear to me either. Or to Hans, who has agreed that the terms are a bit slippery.

2018-11-15 22:03 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +You can invoke Architect for a given target using the [CLI command `ng run`](cli/run).
Architect invokes a builder. The builder invokes a tool, using a target-specific configuration. The tool creates the targeted result -- that can be anything you define in your builder.

2018-11-15 22:12 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +Most Architect targets correspond to [CLI commands](#cli), such as `build`, `serve`, `test`, and `lint`.
I thought that was how I describe the run command - please keep track of this, we should check.

2018-11-16 06:48 UTC, jenniferfell commented
Internal link: https://angular-team.atlassian.net/browse/DOCS-539

2018-11-16 17:42 UTC, mary-poppins commented
You can preview 6f72c5b at https://pr26963-6f72c5b.ngbuilds.io/.

2018-11-26 17:10 UTC, mary-poppins commented
You can preview d0eeaa1 at https://pr26963-d0eeaa1.ngbuilds.io/.

2018-11-27 16:48 UTC, mary-poppins commented
You can preview 5034e3e at https://pr26963-5034e3e.ngbuilds.io/.

2018-11-28 23:19 UTC, mary-poppins commented
You can preview 97090d2 at https://pr26963-97090d2.ngbuilds.io/.

2018-11-30 16:55 UTC, jenniferfell commented
@hansl @jenniferfell If we review and approve (or request changes), this can move forward to merge. Thanks!

2018-12-03 17:06 UTC, mary-poppins commented
You can preview 111284c at https://pr26963-111284c.ngbuilds.io/.

2018-12-03 17:08 UTC, mary-poppins commented
You can preview ccd5490 at https://pr26963-ccd5490.ngbuilds.io/.

2018-12-05 18:00 UTC, mary-poppins commented
You can preview 67037ca at https://pr26963-67037ca.ngbuilds.io/.

2018-12-06 16:30 UTC, mary-poppins commented
You can preview 0cd9e0f at https://pr26963-0cd9e0f.ngbuilds.io/.

2018-12-07 17:20 UTC, mary-poppins commented
You can preview 55055fe at https://pr26963-55055fe.ngbuilds.io/.

2018-12-07 18:50 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +When defining a [directive](guide/glossary#directive), the `@Output{}` decorator on a directive property
Done - Don't want to confuse the CLA

2018-12-07 18:57 UTC, mary-poppins commented
You can preview 01ce698 at https://pr26963-01ce698.ngbuilds.io/.

2018-12-10 17:04 UTC, mary-poppins commented
You can preview 59a05ba at https://pr26963-59a05ba.ngbuilds.io/.

2018-12-10 22:19 UTC, mary-poppins commented
You can preview 2b216bb at https://pr26963-2b216bb.ngbuilds.io/.

2018-12-11 16:30 UTC, mary-poppins commented
You can preview 05f202c at https://pr26963-05f202c.ngbuilds.io/.

2018-12-12 18:15 UTC, mary-poppins commented
You can preview d659af4 at https://pr26963-d659af4.ngbuilds.io/.

2018-12-12 22:20 UTC, jbogarthyde commented
@jenniferfell A couple of issues to track, but I think you could approve this and we can get it landed.

2018-12-14 17:04 UTC, mary-poppins commented
You can preview 5e67d8c at https://pr26963-5e67d8c.ngbuilds.io/.

2018-12-14 17:05 UTC, mary-poppins commented
You can preview e309ffc at https://pr26963-e309ffc.ngbuilds.io/.

2018-12-17 15:44 UTC, mary-poppins commented
You can preview 7a5aeb2 at https://pr26963-7a5aeb2.ngbuilds.io/.

2018-12-18 16:01 UTC, mary-poppins commented
You can preview 3abb315 at https://pr26963-3abb315.ngbuilds.io/.

2018-12-19 18:10 UTC, mary-poppins commented
You can preview 9b3c2d6 at https://pr26963-9b3c2d6.ngbuilds.io/.

2018-12-20 18:44 UTC, mary-poppins commented
You can preview 7f519d5 at https://pr26963-7f519d5.ngbuilds.io/.

2018-12-21 16:52 UTC, mary-poppins commented
You can preview 616043d at https://pr26963-616043d.ngbuilds.io/.

2018-12-26 18:10 UTC, mary-poppins commented
You can preview 4280e29 at https://pr26963-4280e29.ngbuilds.io/.

2018-12-27 21:35 UTC, mary-poppins commented
You can preview 3389ce5 at https://pr26963-3389ce5.ngbuilds.io/.

2019-01-04 22:36 UTC, mary-poppins commented
You can preview 0ca3277 at https://pr26963-0ca3277.ngbuilds.io/.

2019-01-10 23:54 UTC, mary-poppins commented
You can preview 9d32600 at https://pr26963-9d32600.ngbuilds.io/.

2019-01-11 21:35 UTC, mary-poppins commented
You can preview 28f34b5 at https://pr26963-28f34b5.ngbuilds.io/.

2019-01-14 17:12 UTC, mary-poppins commented
You can preview c4d5a43 at https://pr26963-c4d5a43.ngbuilds.io/.

2019-01-15 17:14 UTC, mary-poppins commented
You can preview 70077d0 at https://pr26963-70077d0.ngbuilds.io/.

2019-01-16 20:00 UTC, mary-poppins commented
You can preview 653b13a at https://pr26963-653b13a.ngbuilds.io/.

2019-01-17 16:53 UTC, mary-poppins commented
You can preview 5e93bd0 at https://pr26963-5e93bd0.ngbuilds.io/.

2019-01-18 19:25 UTC, mary-poppins commented
You can preview 8b0ae95 at https://pr26963-8b0ae95.ngbuilds.io/.

2019-01-22 22:23 UTC, mary-poppins commented
You can preview b513821 at https://pr26963-b513821.ngbuilds.io/.

2019-01-22 22:35 UTC, mary-poppins commented
You can preview 31964b8 at https://pr26963-31964b8.ngbuilds.io/.

2019-01-23 21:10 UTC, mary-poppins commented
You can preview dcbbc95 at https://pr26963-dcbbc95.ngbuilds.io/.

2019-01-24 17:04 UTC, mary-poppins commented
You can preview 835cc96 at https://pr26963-835cc96.ngbuilds.io/.

2019-01-24 22:09 UTC, hansl approved these changes

2019-01-25 17:43 UTC, mary-poppins commented
You can preview c3ebb69 at https://pr26963-c3ebb69.ngbuilds.io/.

2019-01-28 23:13 UTC, mary-poppins commented
You can preview 933293d at https://pr26963-933293d.ngbuilds.io/.

2019-01-29 16:40 UTC, mary-poppins commented
You can preview 815d2ce at https://pr26963-815d2ce.ngbuilds.io/.

2019-01-30 18:20 UTC, mary-poppins commented
You can preview d7eab31 at https://pr26963-d7eab31.ngbuilds.io/.

2019-01-31 18:03 UTC, mary-poppins commented
You can preview 1e8b911 at https://pr26963-1e8b911.ngbuilds.io/.

2019-01-31 18:16 UTC, jbogarthyde commented
Added note on using elements instead of libs for non-Angular web apps, in response to Issue https://github.com/angular/angular/pull/28341

2019-02-01 17:02 UTC, mary-poppins commented
You can preview a638342 at https://pr26963-a638342.ngbuilds.io/.

2019-02-04 17:07 UTC, mary-poppins commented
You can preview 8531894 at https://pr26963-8531894.ngbuilds.io/.

2019-02-05 20:21 UTC, mary-poppins commented
You can preview 6c6c012 at https://pr26963-6c6c012.ngbuilds.io/.

2019-02-06 16:44 UTC, mary-poppins commented
You can preview 40bab2d at https://pr26963-40bab2d.ngbuilds.io/.

2019-02-08 16:34 UTC, mary-poppins commented
You can preview 02f9030 at https://pr26963-02f9030.ngbuilds.io/.

2019-02-11 16:51 UTC, mary-poppins commented
You can preview 5c2f570 at https://pr26963-5c2f570.ngbuilds.io/.

2019-02-12 21:38 UTC, mary-poppins commented
You can preview ced6c24 at https://pr26963-ced6c24.ngbuilds.io/.

2019-02-13 17:02 UTC, mary-poppins commented
You can preview a0eb55b at https://pr26963-a0eb55b.ngbuilds.io/.

2019-02-13 19:03 UTC, mary-poppins commented
You can preview b946bb6 at https://pr26963-b946bb6.ngbuilds.io/.

2019-02-13 21:11 UTC, mary-poppins commented
You can preview 332c1a7 at https://pr26963-332c1a7.ngbuilds.io/.

2019-02-14 17:00 UTC, mary-poppins commented
You can preview ac6e2b5 at https://pr26963-ac6e2b5.ngbuilds.io/.

2019-02-15 16:02 UTC, mary-poppins commented
You can preview 35460f2 at https://pr26963-35460f2.ngbuilds.io/.

2019-02-18 17:11 UTC, mary-poppins commented
You can preview 1ec74e6 at https://pr26963-1ec74e6.ngbuilds.io/.

2019-02-20 18:33 UTC, mary-poppins commented
You can preview 5e491fd at https://pr26963-5e491fd.ngbuilds.io/.

2019-02-21 15:57 UTC, mary-poppins commented
You can preview edd562f at https://pr26963-edd562f.ngbuilds.io/.

2019-02-21 23:45 UTC, mary-poppins commented
You can preview d86bcd2 at https://pr26963-d86bcd2.ngbuilds.io/.

2019-02-22 16:21 UTC, mary-poppins commented
You can preview c311eab at https://pr26963-c311eab.ngbuilds.io/.

2019-02-25 17:02 UTC, mary-poppins commented
You can preview 66f0bcd at https://pr26963-66f0bcd.ngbuilds.io/.

2019-02-26 16:40 UTC, mary-poppins commented
You can preview 2b555f6 at https://pr26963-2b555f6.ngbuilds.io/.

2019-02-27 16:34 UTC, mary-poppins commented
You can preview 4c0c5dc at https://pr26963-4c0c5dc.ngbuilds.io/.

2019-02-28 16:29 UTC, mary-poppins commented
You can preview c99833d at https://pr26963-c99833d.ngbuilds.io/.

2019-03-04 16:15 UTC, mary-poppins commented
You can preview 7de6e66 at https://pr26963-7de6e66.ngbuilds.io/.

2019-03-05 16:19 UTC, mary-poppins commented
You can preview 505b1d0 at https://pr26963-505b1d0.ngbuilds.io/.

2019-03-06 19:31 UTC, mary-poppins commented
You can preview 5781b07 at https://pr26963-5781b07.ngbuilds.io/.

2019-03-06 19:36 UTC, mary-poppins commented
You can preview fbd9553 at https://pr26963-fbd9553.ngbuilds.io/.

2019-03-07 16:53 UTC, mary-poppins commented
You can preview a60d5b9 at https://pr26963-a60d5b9.ngbuilds.io/.

2019-03-11 17:13 UTC, mary-poppins commented
You can preview 3651845 at https://pr26963-3651845.ngbuilds.io/.

2019-03-12 15:17 UTC, mary-poppins commented
You can preview 3d9614e at https://pr26963-3d9614e.ngbuilds.io/.

2019-03-14 18:22 UTC, mary-poppins commented
You can preview 5939b31 at https://pr26963-5939b31.ngbuilds.io/.

2019-03-16 09:23 UTC, farmboy3184 approved these changes

2019-03-19 15:44 UTC, mary-poppins commented
You can preview 8235038 at https://pr26963-8235038.ngbuilds.io/.

2019-03-20 15:56 UTC, mary-poppins commented
You can preview d2284c5 at https://pr26963-d2284c5.ngbuilds.io/.

2019-03-25 17:04 UTC, mary-poppins commented
You can preview 2ea8c77 at https://pr26963-2ea8c77.ngbuilds.io/.

2019-03-26 16:58 UTC, mary-poppins commented
You can preview f076c55 at https://pr26963-f076c55.ngbuilds.io/.

2019-03-27 16:41 UTC, mary-poppins commented
You can preview ef26ed4 at https://pr26963-ef26ed4.ngbuilds.io/.

2019-03-27 16:42 UTC, mary-poppins commented
You can preview 928d40e at https://pr26963-928d40e.ngbuilds.io/.

2019-03-28 15:55 UTC, mary-poppins commented
You can preview c3a3619 at https://pr26963-c3a3619.ngbuilds.io/.

2019-03-28 16:47 UTC, jbogarthyde commented
@hansl @filipesilva 
Clarified definitions of 'Architect', 'builder', and 'target', according to my best current understanding. Please check. 
This should agree with the new Architect page we're working on -- my edit (based on Hans` blog draft) in progress here: 
https://docs.google.com/document/d/1G4GXO2wowakSELEbdG6gUOJLTUpN0iN3bxNEbEilus8

2019-03-28 16:48 UTC, mary-poppins commented
You can preview c4ea6e3 at https://pr26963-c4ea6e3.ngbuilds.io/.

2019-03-28 18:02 UTC, filipesilva commented
@clydin PTAL, since you're now taking care of the stable architect integration.

2019-04-01 16:02 UTC, mary-poppins commented
You can preview 313d46a at https://pr26963-313d46a.ngbuilds.io/.

2019-04-01 16:03 UTC, alexeagle approved these changes

2019-04-02 18:14 UTC, mary-poppins commented
You can preview fcb5347 at https://pr26963-fcb5347.ngbuilds.io/.

2019-04-03 17:38 UTC, mary-poppins commented
You can preview fd8a6bb at https://pr26963-fd8a6bb.ngbuilds.io/.

2019-04-04 15:28 UTC, mary-poppins commented
You can preview 646dc63 at https://pr26963-646dc63.ngbuilds.io/.

2019-04-04 15:29 UTC, mary-poppins commented
You can preview d260a09 at https://pr26963-d260a09.ngbuilds.io/.

2019-04-04 18:15 UTC, mary-poppins commented
You can preview 65adfb0 at https://pr26963-65adfb0.ngbuilds.io/.

2019-04-08 16:23 UTC, mary-poppins commented
You can preview 623cc76 at https://pr26963-623cc76.ngbuilds.io/.

2019-04-08 16:24 UTC, mary-poppins commented
You can preview 6e87a03 at https://pr26963-6e87a03.ngbuilds.io/.

2019-04-09 21:45 UTC, mary-poppins commented
You can preview 5a71a49 at https://pr26963-5a71a49.ngbuilds.io/.

2019-04-09 23:27 UTC, Splaktar requested changes
I've made a number of suggested changes to best align with the updates to the CLI and Architect in version 8. They also better align with the (still in progress) Architect guide that we've been working on.

2019-04-09 23:27 UTC, Splaktar commented on aio/content/guide/glossary.md
> +There are some additional predefined builders and targets, and it is possible to define your own custom builders and target configurations. You can run a builder with a specified target using the [`n
```suggestion
The [CLI](#cli) provides a set of builders. The [`ng new` command](cli/new) provides a set of targets for the initial application project. The [`ng generate application`](cli/generate#application) and [`ng generate library`](cli/generate#library) commands provide a set of targets for each new [project](#project). These targets, their options and configurations, can be customized to meet the needs of your project. For example, you may want to add a "staging" or "testing" configuration to a project's "build" target.

Additionally, it is possible to define a custom builder. You can define a new target, in a project, that uses your custom builder. Then you can run that target using the [`ng run`](cli/run) CLI command.
```

2019-04-09 23:27 UTC, Splaktar commented on aio/content/guide/glossary.md
> +This installs the `schematics` executable, which you can use to create a new schematics [collection](#collection) with an initial named schematic. The collection folder is a workspace for schematics.
```suggestion
This installs the `schematics` executable, which you can use to create a new schematics [collection](#collection) with an initial named schematic. The collection folder is a workspace for schematics. You can use the `schematics` executable to add a new schematic to an existing collection, or extend an existing schematic.
```

2019-04-09 23:27 UTC, Splaktar commented on aio/content/guide/glossary.md
> +* [Library](#library) developers can create schematics that enable the Angular CLI to add and update their published libraries, and to generate artifacts the library defines.
```suggestion
* [Library](#library) developers can create schematics that [enable the Angular CLI](guide/creating-libraries#integrating-with-the-cli) to add and update their published libraries, and to generate artifacts the library defines.
```

2019-04-09 23:27 UTC, Splaktar commented on aio/content/guide/glossary.md
> +In [schematics](#schematic), a function that operates on a [file tree](#file-tree) to create, delete, or modify code files in a specific manner.
```suggestion
In [schematics](#schematic), a function that operates on a [file tree](#file-tree) to create, delete, or modify files in a specific manner.
```

2019-04-09 23:27 UTC, Splaktar commented on aio/content/guide/glossary.md
> +In the Angular development environment, a standalone application, test application, or [library](guide/glossary#library) in a [workspace](#workspace).
```suggestion
In the Angular [CLI](#cli) development environment, a standalone application or [library](#library) in a [workspace](#workspace).
```

2019-04-09 23:27 UTC, Splaktar commented on aio/content/guide/glossary.md
> +A workspace can contain multiple projects, which share a compilation context.
```suggestion
```

2019-04-09 23:27 UTC, Splaktar commented on aio/content/guide/glossary.md
> +A application project (and its related end-to-end test project) contains the set of source files, resources, and configuration files that you need to develop, test, and deploy applications.
```suggestion
```

2019-04-09 23:27 UTC, Splaktar commented on aio/content/guide/glossary.md
> +Additional project-specific configuration files are used by subsystems and tools, such as `package.json` for the [npm package manager](#npm-package), and `tsconfig.json` for [TypeScript transpilation
```suggestion
Additional project-specific configuration files are used by tools, such as `package.json` for the [npm package manager](#npm-package), `tsconfig.json` for [TypeScript transpilation](#transpile), and `tslint.json` for configuring lint rules with [TSLint](https://palantir.github.io/tslint/).
```

2019-04-09 23:27 UTC, Splaktar commented on aio/content/guide/glossary.md
> +A file named `angular.json` at the root level of an Angular [workspace](#workspace) provides workspace-wide and project-specific configuration defaults for build and development tools provided by the
```suggestion
A file named `angular.json` at the root level of an Angular [workspace](#workspace) provides workspace-wide and project-specific configuration defaults for build and development tools that are provided by, or integrate with, the [Angular CLI](#cli).
```

2019-04-09 23:56 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +A file named `angular.json` at the root level of an Angular [workspace](#workspace) provides workspace-wide and project-specific configuration defaults for build and development tools provided by the
Yes--  I'm doing it in my name rather than committing the suggestion (to avoid CLA problems)

2019-04-09 23:59 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +A workspace can contain multiple projects, which share a compilation context.
Why remove this? Shared compilation space was the first definition I heard for "workspace"

2019-04-09 23:59 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +A application project (and its related end-to-end test project) contains the set of source files, resources, and configuration files that you need to develop, test, and deploy applications.
Why remove this?

2019-04-10 00:25 UTC, Splaktar commented on aio/content/guide/glossary.md
> +A file named `angular.json` at the root level of an Angular [workspace](#workspace) provides workspace-wide and project-specific configuration defaults for build and development tools provided by the
The CLA warning isn't an issue, any Googler who is doing to the final merge can dismiss it.

2019-04-10 00:28 UTC, Splaktar commented on aio/content/guide/glossary.md
> +A workspace can contain multiple projects, which share a compilation context.
This is the definition of `project` and the definition of `workspace` is linked above. This helps keep the definition of workspace in one place rather than needing to fix/change the definition here and there.

2019-04-10 00:34 UTC, Splaktar commented on aio/content/guide/glossary.md
> +A application project (and its related end-to-end test project) contains the set of source files, resources, and configuration files that you need to develop, test, and deploy applications.
`(and its related end-to-end test project)` is no longer accurate for Angular CLI version 8 AFAIK. The rest of it is also not completely accurate either. It isn't needed to define what a CLI "project" is. Plus in the next line we point them to the Project File Structure guide which includes a more detailed explanation.

2019-04-10 00:37 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +A workspace can contain multiple projects, which share a compilation context.
Ah. Ok - I did finally get down to workspace and saw it there...

2019-04-10 17:54 UTC, mary-poppins commented
You can preview 62c0231 at https://pr26963-62c0231.ngbuilds.io/.

2019-04-10 22:22 UTC, Splaktar requested changes

2019-04-10 22:22 UTC, Splaktar commented on aio/content/guide/glossary.md
> +Use the [CLI command `ng run`](cli/run) to invoke a builder with a specific configuration.
```suggestion
Use the [CLI command `ng run`](cli/run) to invoke a builder by specifying a [target configuration](#target) associated with the builder.
```

2019-04-10 22:22 UTC, Splaktar commented on aio/content/guide/glossary.md
> +The builder code is defined in an [npm package](#npm-package).
```suggestion
The code for a builder is packaged and can be published in an [npm package](#npm-package).
```

2019-04-10 22:22 UTC, Splaktar commented on aio/content/guide/glossary.md
> +The [workspace configuration](guide/workspace-config) file, `angular.json`, contains default configurations for built-in builders.
```suggestion
The [workspace configuration](guide/workspace-config) file, `angular.json`, contains default [target configurations](#target) for builders provided by [Architect](#architect).
```

2019-04-10 22:22 UTC, Splaktar commented on aio/content/guide/glossary.md
> +In the Angular development environment, a standalone application or [library](#library) in a [workspace](#workspace).
I think that this is too general. I suggested (not accepted) the addition of "Angular CLI" here because that is where `project` is relevant. It is possible to have Angular development environments that do not use the CLI and do not have the idea of `projects` or `workspaces`.

2019-04-10 22:22 UTC, Splaktar commented on aio/content/guide/glossary.md
> +An application project (and its related end-to-end test project) contains the set of source files, resources, and configuration files that you need to develop, test, and deploy applications.
There is no `(and its related end-to-end test project)` in version 8.

2019-04-10 22:22 UTC, Splaktar commented on aio/content/guide/glossary.md
> +An application project (and its related end-to-end test project) contains the set of source files, resources, and configuration files that you need to develop, test, and deploy applications.
A application `project` does not include information for how to deploy an application. That is at the `workspace` level.

2019-04-10 22:22 UTC, Splaktar commented on aio/content/guide/glossary.md
> +In the `angular.json` file, each project has an "architect" section that contains targets which configure built-in builders. Some of these targets correspond to [CLI commands](#cli), such as `build`,
I think that `built-in` here should be removed as these are not limited to builders provided by Architect and this does not specify that it is only talking about the state of the configuration in a newly generated project.

2019-04-10 22:22 UTC, Splaktar commented on aio/content/guide/glossary.md
> +For example, the Architect builder invoked by the `ng build` command to compile a project uses a particular build tool, and has a default configuration whose values can be overridden on the command l
There seems to be a grammar issue here:

>  that can be invoked with flag on the `build` command.

2019-04-10 22:22 UTC, Splaktar commented on aio/content/guide/glossary.md
> +The [CLI](#cli) provides a set of builders. The [`ng new` command](cli/new) provides a set of targets for the initial application project. The [`ng generate application`](cli/generate#application) an
```suggestion
The [Architect](#architect) provides a set of builders. The [`ng new` command](cli/new) provides a set of targets for the initial application project. The [`ng generate application`](cli/generate#application) and [`ng generate library`](cli/generate#library) commands provide a set of targets for each new [project](#project). These targets, their options and configurations, can be customized to meet the needs of your project. For example, you may want to add a "staging" or "testing" configuration to a project's "build" target.
```

2019-04-10 22:22 UTC, Splaktar commented on aio/content/guide/glossary.md
> +An Angular compilation context for [projects](guide/glossary#project) (that is, applications and libraries).
```suggestion
An Angular compilation context for [projects](#project) (that is, applications and libraries).
```

2019-04-10 22:22 UTC, Splaktar commented on aio/content/guide/glossary.md
> +An Angular compilation context for [projects](guide/glossary#project) (that is, applications and libraries).
`workspace`s are specific to the Angular CLI. It is possible to develop Angular applications without the Angular CLI. So I think that the following is too broad

> An Angular compilation context

2019-04-10 23:29 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +In the Angular development environment, a standalone application or [library](#library) in a [workspace](#workspace).
How about this.

2019-04-10 23:39 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +An Angular compilation context for [projects](guide/glossary#project) (that is, applications and libraries).
If we do this one, we might as well do all of them.

2019-04-10 23:47 UTC, mary-poppins commented
You can preview 2f6b55c at https://pr26963-2f6b55c.ngbuilds.io/.

2019-04-15 15:37 UTC, mary-poppins commented
You can preview 38d16d7 at https://pr26963-38d16d7.ngbuilds.io/.

2019-04-16 18:27 UTC, mary-poppins commented
You can preview 36ed911 at https://pr26963-36ed911.ngbuilds.io/.

2019-04-16 18:27 UTC, mary-poppins commented
You can preview 5b5ea52 at https://pr26963-5b5ea52.ngbuilds.io/.

2019-04-16 19:28 UTC, Splaktar commented on aio/content/guide/glossary.md
> +In the Angular development environment, a standalone application or [library](#library) in a [workspace](#workspace).
> In the Angular CLI, a standalone application or [library](#library) that can be created or modified by a CLI command.

Looks good.

2019-04-16 19:29 UTC, Splaktar commented on aio/content/guide/glossary.md
> +The [workspace configuration](guide/workspace-config) file, `angular.json`, contains default configurations for built-in builders.
Any questions about this?

2019-04-16 19:29 UTC, Splaktar commented on aio/content/guide/glossary.md
> +The builder code is defined in an [npm package](#npm-package).
Any questions about this?

2019-04-17 16:00 UTC, mary-poppins commented
You can preview 2bdd9f9 at https://pr26963-2bdd9f9.ngbuilds.io/.

2019-04-18 15:27 UTC, mary-poppins commented
You can preview 4f7f1e1 at https://pr26963-4f7f1e1.ngbuilds.io/.

2019-04-28 16:48 UTC, IgorMinar approved these changes
lgtm with a few corrections I suggested. thanks!

2019-04-28 16:48 UTC, IgorMinar commented on aio/content/guide/glossary.md
> +An compilation context used by the [Angular CLI](#cli) for [projects](#project) (that is, applications and libraries).
```suggestion
A collection of Angular [projects](#project) (that is, applications and libraries) powered by the [Angular CLI](#cli) that are typically collocated in a single source control repository (e.g. [git](https://git-scm.com/)).
```

2019-04-28 16:48 UTC, IgorMinar commented on aio/content/guide/glossary.md
> +An object in the [workspace configuration file](guide/workspace-config#project-tool-configuration-options) that configures an [Architect](#architect) [builder](#builder) for use in a [project](#proje
```suggestion
A buildable or runnable subset of a [project](#project), configured as an object in the [workspace configuration file](guide/workspace-config#project-tool-configuration-options), and executed by an [Architect](#architect) [builder](#builder).
```

2019-04-28 16:48 UTC, IgorMinar commented on aio/content/guide/glossary.md
> +## configuration
isn't this too generic? how about "Workspace configuration"?

2019-04-28 16:48 UTC, IgorMinar commented on aio/content/guide/glossary.md
> +The [workspace configuration](guide/workspace-config) file, `angular.json`, contains default configurations for built-in builders.
lgtm

2019-04-28 16:48 UTC, IgorMinar commented on aio/content/guide/glossary.md
> +The builder code is defined in an [npm package](#npm-package).
lgtm

2019-04-28 16:50 UTC, IgorMinar commented
@jbogarthyde in the future please separate the link/anchor refactoring into a separate PR because it added a lot of noise into this PR which made it look much bigger and much harder to review than it was / should have been. Doing it this way, will make it easier and faster to review the changes because reviewing big PRs with just mechanical changes can be done fairly quickly. thanks for understanding!

2019-04-28 17:28 UTC, mary-poppins commented
You can preview 0ad505d at https://pr26963-0ad505d.ngbuilds.io/.

2019-04-28 17:31 UTC, jbogarthyde commented
Incorporated Igor's changes, ready for merge.

2019-04-28 17:40 UTC, mary-poppins commented
You can preview c417b71 at https://pr26963-c417b71.ngbuilds.io/.

2019-04-29 20:23 UTC, closed without merging