fix(forms): typed argument for FormBuilder group
angular/angular pull request #26985
Opened 2018-11-07 19:59 UTC by cexbrayat

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The refactored `group` method of `FormBuilder` introduced by #24599 allows two types of options but the signature doesn't show it.

## What is the new behavior?

It adds a stricter type to the refactored `group` method.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

cc @kara

2018-11-08 09:18 UTC, IgorMinar reviewed
@kara can you take a look too please? Thanks

2018-11-08 09:18 UTC, IgorMinar commented on packages/forms/src/form_builder.ts
> +        updateOn = legacyOrOpts.updateOn != null ? legacyOrOpts.updateOn : undefined;
Why do we need all the ternary operator checks? Couldn't we use object destructuring instead? It seems that we are doing a lot of work no obvious reason.

2018-11-08 09:18 UTC, IgorMinar commented on packages/forms/src/form_builder.ts
> +      legacyOrOpts: AbstractControlOptions|{[key: string]: any}|null = null): FormGroup {
I'm now realizing that this param name is very confusing. I think we should just call it options and document that it has two shapes one of which is deprecated.

2018-11-08 09:18 UTC, IgorMinar commented on tools/public_api_guard/forms/forms.d.ts
> +      }, legacyOrOpts?: AbstractControlOptions | {
I like this. Change. At minimum from docs perspective it makes the api cleaner.

2018-11-12 09:31 UTC, LayZeeDK commented on packages/forms/src/form_builder.ts
> +        updateOn = legacyOrOpts.updateOn != null ? legacyOrOpts.updateOn : undefined;
To support the legacy options of shape
```
{
  asyncValidator?: AsyncValidatorFn | AsyncValidatorFn[] | null;
  validator?: ValidatorFn | ValidatorFn[] | null;
}
```
as well as `AbstractControlOptions` with similar but slightly differently named properties (notice the ending **s**)
```
{
  asyncValidators?: AsyncValidatorFn | AsyncValidatorFn[] | null;
  validators?: ValidatorFn | ValidatorFn[] | null;
  updateOn?: 'change' | 'blur' | 'submit';
}
```

2018-11-21 00:03 UTC, kara approved these changes
LGTM (once Igor's comments are addressed)

2018-11-21 00:03 UTC, kara commented on packages/forms/src/form_builder.ts
> +      legacyOrOpts: AbstractControlOptions|{[key: string]: any}|null = null): FormGroup {
Works for me

2018-11-21 00:05 UTC, kara commented on tools/public_api_guard/forms/forms.d.ts
> +      }, legacyOrOpts?: AbstractControlOptions | {
Yeah, in terms of types, there isn't really a difference, but I do think this is helpful documentation.

2018-11-21 09:14 UTC, skreborn requested changes
Just casual nitpicking following up on the `legacyOrOpts` -> `options` change.

2018-11-21 09:14 UTC, skreborn commented on packages/forms/src/form_builder.ts
> +        // `legacyOrOpts` are `AbstractControlOptions`
`legacyOrOpts` should also be replaced in the comment here since it was renamed to `options`.

2018-11-21 09:14 UTC, skreborn commented on packages/forms/src/form_builder.ts
> +        // `legacyOrOpts` are legacy form group options
Same as above.

2018-11-21 09:14 UTC, skreborn commented on tools/public_api_guard/forms/forms.d.ts
> +      }, legacyOrOpts?: AbstractControlOptions | {
@IgorMinar Should `legacyOrOpts` be replaced with `options` here, too?

2018-11-21 09:43 UTC, cexbrayat commented on packages/forms/src/form_builder.ts
> +        // `legacyOrOpts` are `AbstractControlOptions`
Right, thanks for catching that. I fixed.

2018-11-21 10:35 UTC, LayZeeDK commented
Please note my comment and make sure that you don't recreate the issue that broke your internal Google tests, @kara and @IgorMinar 
https://github.com/angular/angular/pull/26985#issuecomment-437811275

This is the reason types were made less strict and correct.

2018-11-21 18:53 UTC, kara commented
@LayZeeDK This PR does not actually make any meaningful type changes because `AbstractControlOptions` is a subtype of `{[key:string]: any}` type and does not replace it. It's mostly being added for documentation purposes.

2018-11-21 18:53 UTC, kara commented
[presubmit](https://test.corp.google.com/ui#id=OCL:222428684:BASE:222428855:1542825287854:fb72345)

2018-11-21 18:57 UTC, kara approved these changes
LGTM

2018-11-21 18:57 UTC, kara commented
@IgorMinar Can you take another look?

2018-11-22 06:38 UTC, LayZeeDK commented
So Angular 7.1.0 landed.

2018-12-07 02:02 UTC, IgorMinar approved these changes
Lgtm. Thanks for being patient!

2018-12-07 17:31 UTC, closed without merging