docs: update location API docs
angular/angular pull request #27010
Opened 2018-11-08 18:45 UTC by chembu

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Updated API documentation.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2018-11-08 18:56 UTC, mary-poppins commented
You can preview 6eaa645 at https://pr27010-6eaa645.ngbuilds.io/.

2018-11-16 06:01 UTC, jenniferfell commented
Internal link: https://angular-team.atlassian.net/browse/DOCS-130

2019-02-14 16:45 UTC, mary-poppins commented
You can preview 84789d2 at https://pr27010-84789d2.ngbuilds.io/.

2019-02-27 19:09 UTC, mary-poppins commented
You can preview 27742ba at https://pr27010-27742ba.ngbuilds.io/.

2019-02-28 18:21 UTC, mary-poppins commented
You can preview a2ba6ca at https://pr27010-a2ba6ca.ngbuilds.io/.

2019-03-13 17:59 UTC, mary-poppins commented
You can preview 5564a82 at https://pr27010-5564a82.ngbuilds.io/.

2019-04-01 17:22 UTC, mary-poppins commented
You can preview 20f4de0 at https://pr27010-20f4de0.ngbuilds.io/.

2019-04-01 19:06 UTC, jasonaden requested changes
This looks good, but needs a rebase. All commits should be squashed into one.

2019-04-01 19:28 UTC, mary-poppins commented
You can preview d11ea3e at https://pr27010-d11ea3e.ngbuilds.io/.

2019-04-02 18:01 UTC, mary-poppins commented
You can preview 8760c40 at https://pr27010-8760c40.ngbuilds.io/.

2019-04-02 23:10 UTC, jasonaden approved these changes

2019-04-02 23:13 UTC, closed without merging