docs(forms): update API reference for common APIs and template-driven direcrtives
angular/angular pull request #27033
Opened 2018-11-09 20:16 UTC by brandonroberts

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2018-11-09 20:20 UTC, mary-poppins commented
You can preview 537bfdd at https://pr27033-537bfdd.ngbuilds.io/.

2018-11-12 17:00 UTC, mary-poppins commented
You can preview 54eaefe at https://pr27033-54eaefe.ngbuilds.io/.

2018-11-14 00:08 UTC, kara requested changes

2018-11-14 00:08 UTC, kara commented on packages/forms/src/directives/ng_model_group.ts
> + * for the sub-group in the form's full value. You also export the directive into
Same here. "can" is necessary, as this is optional.

2018-11-14 00:08 UTC, kara commented on packages/forms/src/directives/default_value_accessor.ts
> + * the "compositionend" event occurs.
> Provide this token to control if form directives buffer IME input until the "compositionend" event occurs.

2018-11-15 16:31 UTC, mary-poppins commented
You can preview c4dbe29 at https://pr27033-c4dbe29.ngbuilds.io/.

2018-11-15 17:00 UTC, mary-poppins commented
You can preview ed4edca at https://pr27033-ed4edca.ngbuilds.io/.

2018-11-27 23:17 UTC, kara requested changes
Almost there, just a few more typos

2018-11-27 23:17 UTC, kara commented on packages/forms/src/directives/ng_form.ts
> +   * **updateOn**: Sets as the default `updateOn` value for all child `NgModels` below it
```suggestion
   * **updateOn**: Sets the default `updateOn` value for all child `NgModels` below it
```

2018-11-27 23:17 UTC, kara commented on packages/forms/src/directives/ng_model.ts
> + * The following examples shows a simple standalone control using `ngModel`:
```suggestion
 * The following examples show a simple standalone control using `ngModel`:
```

2018-11-27 23:17 UTC, kara commented on packages/forms/src/directives/ng_model.ts
> +   * as a stanaldone control.
```suggestion
   * as a standalone control.
```

2018-11-27 23:17 UTC, kara commented on packages/forms/src/directives/ng_model.ts
> +               * The top-level directive for this conrol if present, otherwise null.
```suggestion
               * The top-level directive for this control if present, otherwise null.
```

2018-11-29 15:07 UTC, brandonroberts commented
@kara latest changes are done.

2018-11-29 15:11 UTC, mary-poppins commented
You can preview fef8313 at https://pr27033-fef8313.ngbuilds.io/.

2018-11-29 23:13 UTC, kara approved these changes
LGTM

2018-11-30 05:34 UTC, closed without merging