[POC DNM] refactor: remove @angular/http
angular/angular pull request #27038
Opened 2018-11-10 03:38 UTC by CaerusKaru

This is just a test balloon PR to see the ramifications for removing `@angular/http` (since it's been deprecated for two major versions).

NOTE: This does not convey any intent, official or otherwise, to remove this package from the framework in the near or short term.

2018-11-15 17:31 UTC, IgorMinar commented
I'd love for this to happen in v8! Would you be willing to work through the cleanup, writing up migration instructions for anyone still using the old http, and get this PR into a mergable state?

2018-12-25 03:59 UTC, CaerusKaru commented
CI is good, only blocked on https://github.com/angular/in-memory-web-api/pull/226

2019-01-14 07:31 UTC, IgorMinar requested changes
We are almost there!! Can you please fix the following:

```
git grep "@angular/http" | grep -v CHANGELOG.md


.github/CODEOWNERS:#  @angular/http
aio/tools/examples/shared/boilerplate/service-worker/package.json:    "@angular/http": "^7.0.0",
integration/platform-server/yarn.lock:"@angular/http@file:../../dist/packages-dist/http":
modules/playground/src/web_workers/worker-systemjs-configure.ts:    '@angular/http': '/packages-dist/http/bundles/http.umd.js',
packages/platform-server/package.json:    "@angular/http": "0.0.0-PLACEHOLDER",
```

Also, I looked into google3 and there is still a lot of usage of this package, so we'll need to figure out a plan for that. My current thinking is that unlike with other changes, we'll delete this package from github and schedule a google3 cleanup for after v8.

Lastly, similar to the DOCUMENT PR, please change the commit message type to "feat".

2019-01-14 07:31 UTC, IgorMinar commented on packages/platform-server/src/location.ts
> +import {DOCUMENT, LocationChangeEvent, LocationChangeListener, PlatformLocation} from '@angular/common';
naughty! this change doesn't belong here. I'll keep it in, but please try to avoid this in the future because you are only increasing the review burden and risk of collisions.

2019-01-14 09:02 UTC, CaerusKaru commented on packages/platform-server/src/location.ts
> +import {DOCUMENT, LocationChangeEvent, LocationChangeListener, PlatformLocation} from '@angular/common';
Argh! You caught me 😉. This PR originally started off as a "get rid of deprecated stuff in platform-server," and expanded from there. I've removed this since #28117 now addresses it.

2019-01-14 09:05 UTC, CaerusKaru commented
@IgorMinar added remaining files, ready for another look!

2019-03-05 22:05 UTC, alexeagle commented
Could you please split it into two:
1) remove any references to old http in our code, but still keep the implementation. This lets us still publish `@angular/http` for v8 if needed
2) PR that actually deletes the package in case of victory

2019-03-17 03:15 UTC, CaerusKaru commented
@alexeagle I've opened https://github.com/angular/angular/pull/29355. We've already migrated all of the docs in AIO, and platform-server can't be migrated until we remove Http entirely (although technically we could: this is up to @IgorMinar).

2019-04-11 09:16 UTC, ankeshdave commented
Will angular not support `@angular/http` in v8. Any clarity around this will help of people decide on migration strategy (I still have some projects were migrations is pending).

2019-10-07 08:08 UTC, petebacondarwin commented
@CaerusKaru - where are we at with this PR? It needs a rebase but it is not clear to me whether you successfully split the changes into two as requested by @alexeagle ?

2020-01-16 21:19 UTC, CaerusKaru commented
@petebacondarwin This PR hasn't been rebased on top of #29355, which is the split @alexeagle mentioned. Rebasing at this point would be tricky and I might just start from scratch, but only with commitment from the team that this is still needed.

2020-01-22 02:53 UTC, CaerusKaru commented
Blocked on https://github.com/angular/angular/pull/34892

2020-04-28 17:48 UTC, kara commented
@CaerusKaru Rebase?

2020-05-01 22:25 UTC, kara approved these changes
LGTM

2020-05-04 17:44 UTC, IgorMinar approved these changes
LGTM! Thank you for being **super** patient!

The merging of this PR is still blocked on a config change CL in google3 that @matsko is landing right now.

Reviewed-for: global-approvers

2020-05-04 23:29 UTC, kara commented
G3 change should be in, so this is unblocked

2020-05-04 23:36 UTC, matsko commented
@kara @IgorMinar unfortunately the G3 change is causing files to be removed. We can't merge this yet.

2020-05-05 18:41 UTC, matsko commented
This is now unblocked because G3 doesn't sync `@angular/http` anymore.

Here's the latest sync (of this PR) that proves it: https://critique-ng.corp.google.com/cl/309988926

2020-05-06 00:42 UTC, closed without merging