WIP - fix(upgrade): several ngUpgradeLite fixes
angular/angular pull request #27217
Opened 2018-11-21 19:44 UTC by gkalpak

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2018-11-21 19:48 UTC, mary-poppins commented
You can preview e1865d1 at https://pr27217-e1865d1.ngbuilds.io/.

2018-11-21 20:30 UTC, JoostK commented on packages/upgrade/src/common/downgrade_component.ts
> +                return value || mInjector.get(token, notFoundValue, flags);
This won't work for tokens that resolve to a falsy value

2018-11-21 20:30 UTC, JoostK commented on packages/upgrade/src/common/downgrade_component.ts
> +          parentInjector! : !parentInjector ?
This ternary blows my mind! 😄

2018-11-21 20:30 UTC, JoostK commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +             ngDoBootstrap() {}
There's a `DoBootstrap` interface nowadays 👍

2018-11-22 21:39 UTC, gkalpak commented on packages/upgrade/src/common/downgrade_component.ts
> +                return value || mInjector.get(token, notFoundValue, flags);
I know. I was just trying something out. This is still WIP :grin:

2018-11-22 21:42 UTC, gkalpak commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +             ngDoBootstrap() {}
Cool, I didn't know. But even so, I don't see any value in using it in these tests. Do I miss something?

2018-11-22 21:49 UTC, JoostK commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +             ngDoBootstrap() {}
Nope, works fine without of course.

2018-11-22 21:49 UTC, JoostK commented on packages/upgrade/src/common/downgrade_component.ts
> +                return value || mInjector.get(token, notFoundValue, flags);
Cool. I saw the WIP title too late ;)

2018-11-22 22:17 UTC, mary-poppins commented
You can preview bde12ee at https://pr27217-bde12ee.ngbuilds.io/.

2018-11-22 22:39 UTC, petebacondarwin commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +           // Important: `ng-if` makes `<zonetest>` render asynchronously.
Do you mean `<test>` and below?

2018-11-22 22:41 UTC, petebacondarwin commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +             count = 0;
This is a good change, but I am surprised that you added it here...

2018-11-23 09:33 UTC, gkalpak commented on packages/upgrade/src/common/downgrade_component.ts
> +          parentInjector! : !parentInjector ?
Too bad it didn't end up in the final code 😛

2018-11-23 09:34 UTC, gkalpak commented on packages/upgrade/src/common/downgrade_component.ts
> +                return value || mInjector.get(token, notFoundValue, flags);
No worries. This is now ready for review, if you are interested :grin:

2018-11-23 09:40 UTC, gkalpak commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +             count = 0;
Sorry 😞 I just came across this, while scrolling between my two newly added tests and could help "fixing" it.
It seemed too minor for a separate commit, especially given it doesn't make any difference (it is just a one-word refactoring).

I'll remove it to avoid distractions, since it is indeed irrelevant to this commit 😇

2018-11-23 11:13 UTC, mary-poppins commented
You can preview 5d2796a at https://pr27217-5d2796a.ngbuilds.io/.

2018-11-24 09:05 UTC, petebacondarwin commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +                   .toBe('FOO:CompB-foo BAR:ModB-bar BAZ:ModB-baz QUX:Plat-qux QUUX:Plat-quux');
So ModuleA doesn't get a look in in either of these expectations! Interesting...

2018-11-24 09:06 UTC, petebacondarwin commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +                       'ng2A( FOO:CompB-foo BAR:CompA-bar BAZ:ModB-baz QUX:Plat-qux QUUX:Plat-quux )');
Ahah!

2018-11-24 21:08 UTC, petebacondarwin approved these changes
I am not 100% confident that the injector traversal is accurate but I don't know if anyone does.
Let's go with this and see if it causes any problems.

2018-11-26 15:31 UTC, gkalpak commented
> I am not 100% confident that the injector traversal is accurate but I don't know if anyone does.

I don't think there is a definition of accurate. We get to decide it for ourselves :grin:

The main controversy is that, once the element injector tree has been traversed and we get to the component's module, no other modules are checked. This is different than what happens with lazy-loaded modules (which is the only other case I know of, where multiple moduleRef's have their own injector).

The difference here (if my understanding is correct), is that moduleRefs can have other moduleRefs as parents. The router sets the lazy loaded modules to have the main app module as parent, thus the main injector is checked when something cannot be found on the lazy-loaded module's injector. But with `ngUpgradeLite`, there is hierarchical ordering of downgraded modules, so we are not setting up parent/child moduleRef relations.

As a workaround, one has to ensure that any shared dependencies must be on the platform injector (which is an ancestor of all module injectors).

##
One usecase that might catch people off-guard, is when you have one main downgraded module and several smaller (possibly lazy-loaded) downgraded modules. And you expect components in those smaller modules to be able to access providers from the "main" module.

Maybe we could make so that the downgraded module that is instantiated first is considered the "main" module and all other downgraded modules are considered its children (so they all have access to its providers).

2018-11-26 15:39 UTC, petebacondarwin commented
> Maybe we could make so that the downgraded module that is instantiated first is considered the "main" module and all other downgraded modules are considered its children (so they all have access to its providers).

I think this is a good backup plan, but is it worth implementing now? Perhaps we should ask someone like @mhevery ?

2018-11-27 16:46 UTC, gkalpak commented
Maybe I should just document the current behavior better for now.
Changing it after it has been released would require a breaking change though 🤔

2018-12-04 18:00 UTC, mhevery commented
I am not fully following the discussion. But here is how I think the injection should work.

1) We should check NodeInjectors first. This should mirror the DOM tree in logical sense. (ie, your parent is the parent declared in the template not the parent which may be in the DOM. This could be different because of re-projection.)
2) After the NodeInjectors are checked the ModuleInjector should be checked. Each Module Injector can have a parent Injector. There is not strict ordering of who your parent is, and often depends on the application. For example when router loads a route it makes the RouteModuleInjector point to the AppModuleInjector.

2018-12-05 16:38 UTC, mary-poppins commented
You can preview 4d5735e at https://pr27217-4d5735e.ngbuilds.io/.

2018-12-10 15:06 UTC, mary-poppins commented
You can preview ad0ed91 at https://pr27217-ad0ed91.ngbuilds.io/.

2018-12-12 13:42 UTC, mary-poppins commented
You can preview f3ab4ec at https://pr27217-f3ab4ec.ngbuilds.io/.

2018-12-12 15:14 UTC, petebacondarwin requested changes

2018-12-12 15:14 UTC, petebacondarwin commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +      fit('should support accessing injectables provided it \'root\' from any downgraded module',
`fit`

2018-12-12 17:02 UTC, gkalpak commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +      fit('should support accessing injectables provided it \'root\' from any downgraded module',
Yes, that's intentional (it fails currently), until we decide what to do about this.
I should probably switch the PR back to `WIP`.

2018-12-13 12:52 UTC, mary-poppins commented
You can preview 541089a at https://pr27217-541089a.ngbuilds.io/.

2018-12-13 13:19 UTC, mary-poppins commented
You can preview ab23620 at https://pr27217-ab23620.ngbuilds.io/.

2018-12-13 13:50 UTC, mary-poppins commented
You can preview c43ed9c at https://pr27217-c43ed9c.ngbuilds.io/.

2018-12-13 15:18 UTC, mary-poppins commented
You can preview 1c1e4e6 at https://pr27217-1c1e4e6.ngbuilds.io/.

2018-12-13 15:31 UTC, gkalpak commented
Per discussion with @mhevery and @petebacondarwin, there doesn't seem to be a good way to establish module/injector hierarchy (given that consumers can pass a `bootstrapFn()` function that is a black box for `downgradeModule()`). If people need to have such a hierarchy, they need to manually wire the modules/injectors in their `bootstrapFn`s.

I am going to add docs on that and then it will be ready to go :smiley:

2018-12-13 22:48 UTC, mary-poppins commented
You can preview df23b7d at https://pr27217-df23b7d.ngbuilds.io/.

2018-12-13 22:49 UTC, mary-poppins commented
You can preview c1ca458 at https://pr27217-c1ca458.ngbuilds.io/.

2018-12-14 13:52 UTC, mary-poppins commented
You can preview e1475d2 at https://pr27217-e1475d2.ngbuilds.io/.

2018-12-14 16:34 UTC, mary-poppins commented
You can preview 6bf0608 at https://pr27217-6bf0608.ngbuilds.io/.

2018-12-14 16:43 UTC, mary-poppins commented
You can preview 9722c50 at https://pr27217-9722c50.ngbuilds.io/.

2018-12-14 22:37 UTC, mary-poppins commented
You can preview 06a7f31 at https://pr27217-06a7f31.ngbuilds.io/.

2018-12-15 12:03 UTC, gkalpak commented
@petebd, PTAL. I added some fixup commits and a new docs commit at the end.

2018-12-19 12:06 UTC, petebacondarwin commented on packages/examples/upgrade/static/ts/lite-multi-shared/e2e_test/static_lite_multi_shared_spec.ts
> +    expect(compB.getText()).toBe('Component B (Service ID: 2)');
Does this work in ivy mode?

2018-12-19 12:08 UTC, petebacondarwin commented on packages/examples/upgrade/static/ts/lite-multi-shared/module.ts
> +})
Doesn't this module need to import `Ng2RootModule` in order to be able to inject `Ng2Service`?

2018-12-19 12:09 UTC, petebacondarwin commented on packages/examples/upgrade/static/ts/lite-multi-shared/module.ts
> +})
Or is that only for directives, components and pipes?

2018-12-19 12:16 UTC, petebacondarwin commented on packages/examples/upgrade/static/ts/lite-multi-shared/module.ts
> +                     // Since there are more than one downgraded Angular module,
One of the following is needed:

* are -> is
* module -> modules

with my preference for the former.

2018-12-19 12:22 UTC, gkalpak commented on packages/examples/upgrade/static/ts/lite-multi-shared/module.ts
> +})
Since this module will be created using RootModule's injector, it gets access to its injectables.

2018-12-19 12:33 UTC, petebacondarwin commented on packages/upgrade/src/common/downgrade_component.ts
> +        // If there is a parent component that belongs to the same `NgModule`, use its injector.
The way I read this is, from the code above:

> If there are multiple top level modules, in which case the parent may belong to a different module, then use the module injector
> Otherwise use the parent injector

Is that right? Is that different to what is in the comment here?

2018-12-19 12:36 UTC, petebacondarwin commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +      fixmeIvy('FW-714: ng1 projected content is not being rendered')
FW-714 is now described as `Ivy is not filling out the `componentFactory.ngContentSelectors` property`. Can you check that this is the case for this test and change the description here accordingly.

2018-12-19 12:37 UTC, petebacondarwin approved these changes
Some questions and suggestions

2018-12-19 12:49 UTC, mary-poppins commented
You can preview 9f9adaf at https://pr27217-9f9adaf.ngbuilds.io/.

2018-12-19 12:53 UTC, gkalpak commented on packages/upgrade/src/common/downgrade_component.ts
> +        // If there is a parent component that belongs to the same `NgModule`, use its injector.
Yes, it is different. The `moduleInjector` is used for module-specific stuff, like getting the `ComponentFactoryResolver`. For other stuff, we use the parent injector.
So, if there is a parent component that belongs to a different `NgModule`, we want to separate the module injector for the parent injector.

2018-12-19 12:55 UTC, gkalpak commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +      fixmeIvy('FW-714: ng1 projected content is not being rendered')
Sneaky 😒
Other than the description change, the result won't change: Projected content will not be rendered, right?

2018-12-19 13:40 UTC, petebacondarwin commented on packages/upgrade/src/common/downgrade_component.ts
> +        // If there is a parent component that belongs to the same `NgModule`, use its injector.
What I mean is that the comment doesn't seem to match my understanding of the code.

Are you saying that if `parentInjector` is defined AND `hasMultipleDownloadModules` is true, then the `parentInjector` must come from another `NgModule`?

2018-12-19 13:41 UTC, petebacondarwin commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +      fixmeIvy('FW-714: ng1 projected content is not being rendered')
All the other occurrences of this FW-714 were caused by this, so I changed the description.
I just want to check that this was not an outlier that was not caused by the lack of `ngContentSelectors`. I suspect it is.

2018-12-19 15:15 UTC, gkalpak commented on packages/upgrade/src/common/downgrade_component.ts
> +        // If there is a parent component that belongs to the same `NgModule`, use its injector.
There are two injectors: `finalParentInjector` and `finalModuleInjector` (they might be the same instance, but that is irrelevant).

- `finalModuleInjector` is used to retrieve `ComponentFactoryResolver`, thus it must be on the same tree as the `NgModule` that declares this downgraded component.
- `finalParentInjector` is used for all other injection purposes. Note that Angular knows to only traverse the component-tree part of that injector when looking for an injectable and then switch to the module injector.

There are basically three cases:

1. If there is no parent component (thus no `parentInjector`), we bootstrap the downgraded `NgModule` and use its injector as both `finalParentInjector` and `finalModuleInjector`.
2. If there is a parent component (and thus a `parentInjector`) and we are sure that it belongs to the same `NgModule` as the current downgraded component (e.g. because there is only one downgraded modules - i.e. `hasMultipleDowngradedModules` is `false`), we use that `parentInjector` as both `finalParentInjector` and `finalModuleInjector`.
3. Finally, if there is a parent component but it may belong to a different `NgModule`, then we use the `parentInjector` as `finalParentInjector` and this downgraded component's declaring `NgModule`'s injector as `finalModuleInjector`.
    Note 1: If the `NgModule` is already bootstrapped, we just get its injector (we don't bootstrap again).
    Note 2: It is possible that (while there are multiple downgraded modules) this downgraded component and its parent component both belong to the same `NgModule`. In that case, we could have used the `parentInjector` as both `finalParentInjector` and `finalModuleInjector`, but (for simplicity) we are treating this case as if they belong to different `NgModule`s. That doesn't really affect anything, since `parentInjector` has `moduleInjector` as ancestor and trying to resolve `ComponentFactoryResolver` from either one will return the same instance.

2018-12-20 12:18 UTC, petebacondarwin commented on packages/upgrade/src/common/downgrade_component.ts
> +        // If there is a parent component that belongs to the same `NgModule`, use its injector.
This is a great write up. I think this is the sort of thing that would be great to cut and paste actually into the code - "For Future Generations™️"

2018-12-20 12:25 UTC, petebacondarwin approved these changes

2018-12-20 14:07 UTC, gkalpak commented on packages/upgrade/test/static/integration/downgrade_module_spec.ts
> +      fixmeIvy('FW-714: ng1 projected content is not being rendered')
Actually, there are several occurrences of `fixmeIvy('FW-714: ...')` (outside of this PR) with the old description.
I don't think updating them adds much value. Let's wait for FW-714 to be fixed and then either remove them or change them to another Jira issue (if applicable).

2018-12-20 14:42 UTC, mary-poppins commented
You can preview 5cb5cce at https://pr27217-5cb5cce.ngbuilds.io/.

2018-12-20 16:41 UTC, gkalpak commented
CI green --> marking for merge :tada:

2018-12-20 17:17 UTC, matsko commented
https://test.corp.google.com/ui#id=OCL:226343919:BASE:226343988:1545325414311:69ff0ff7

2018-12-20 21:21 UTC, closed without merging