fix(ivy): TestBed.get(Compiler) throws "Error: Runtime compiler is not loaded"
angular/angular pull request #27223
Opened 2018-11-22 06:48 UTC by mhevery

This PR adds support for the `TestBed.get(Compiler)` and unblocks FW-561.

2018-11-22 06:52 UTC, mary-poppins commented
You can preview e1b3860 at https://pr27223-e1b3860.ngbuilds.io/.

2018-11-22 09:45 UTC, pkozlowski-opensource commented on packages/core/src/debug/debug_node.ts
> +export interface DebugNode {
This is a breaking change, technically speaking, right? I mean, previously people could import and instantiate `DebugNode` and it was part of the public API.

I don't suspect that many people actually do it but we should still document this as a breaking change

2018-11-22 09:56 UTC, pkozlowski-opensource commented on packages/core/src/debug/debug_node.ts
> +  get references(): {[key: string]: any;} {
Couldn't we use https://github.com/angular/angular/blob/dc300c5c4172e1f8a6f3f84da6797e427e3626c0/packages/core/src/render3/discovery_utils.ts#L185-L193 here?

2018-11-22 10:01 UTC, pkozlowski-opensource commented on packages/core/src/debug/debug_node.ts
> +  get attributes(): {[key: string]: string | null;} { throw notImplemented(); }
What would be the strategy for implementing it in the future? Just get static attrs from `TView`? Would we also need info about attr bindings (`attr.foo="expr"`) here? Same applies to classes and styles.

Generally speaking I'm not clear how the current view engine works in this respect...

2018-11-22 10:07 UTC, pkozlowski-opensource commented on packages/core/src/debug/debug_node.ts
> +    const event = document.createEvent('MouseEvent');
Uh, this is big change as compared to the current implementation that tries to abstract native event handlers. Not only the `'MouseEvent'` is hard-coded here but I suspect that it will fail for pseudo-events like `window.keydown.ESC`.


Also I'm not sure if the current implementation triggers event handlers on directives.

tl;dr; is that I was trying to take the approach you are taking in this PR and decided agains party for the above reasons. The existing `DebugElement` abstracts native platform while here we are going low-level native. `TestBed` is a public API and this change would be very breaking for many projects I know (ex. ng-bootstrap).

As a very minimum we need to evaluate this breaking change and document if we decide to go down this path.

2018-11-22 10:10 UTC, pkozlowski-opensource commented on packages/core/src/render3/context_discovery.ts
> -function assertDomElement(element: any) {
👍 good move moving this one :-)

2018-11-22 10:13 UTC, pkozlowski-opensource commented on packages/core/src/view/services.ts
>      const debugCtx = getCurrentDebugContext() || (ivyEnabled ? this.createDebugContext(el) : null);
I believe that we can remove the part guided by `ivyEnabled` now.

2018-11-22 10:33 UTC, pkozlowski-opensource requested changes
@mhevery I've left few comments in the code, the most important being about breaking changes. I was trying to take the same approach in the past but I got scared off the breaking changes with triggering event handlers etc. Basically we would loose the abstraction over native platform and this sounds like "big deal". Let's discuss.

If we decide to go ahead with this approach it is not clear for me what should happen with https://github.com/angular/angular/blob/master/packages/core/src/render3/debug.ts and all infrastructure that plugs it (https://github.com/angular/angular/blob/master/packages/core/testing/src/r3_test_bed.ts#L426-L429)  

Lastly, the CI is red with some tests failing.

2018-11-23 03:42 UTC, mhevery commented on packages/core/src/debug/debug_node.ts
> +export interface DebugNode {
@IgorMinar 

From my point of view we have accidentally exposed more API than we intended to. 
- We exposed the constructor
- We exposed the mutation methods 

By changing this from `class` to `interface` I think we are only removing the API which was accidentally exposed and which serves no purpose to the end user.

2018-11-23 03:43 UTC, mary-poppins commented
You can preview afe9b25 at https://pr27223-afe9b25.ngbuilds.io/.

2018-11-23 03:57 UTC, mhevery commented on packages/core/src/debug/debug_node.ts
> +  get references(): {[key: string]: any;} {
you are right, fixed

2018-11-23 03:57 UTC, mhevery commented on packages/core/src/debug/debug_node.ts
> +  get attributes(): {[key: string]: string | null;} { throw notImplemented(); }
We have all of the information in `TNode` it is just a matter of getting it. I am not sure what the current behavior is either. sounds like we need to do some investigation.

2018-11-23 03:57 UTC, mhevery commented on packages/core/src/debug/debug_node.ts
> +    const event = document.createEvent('MouseEvent');
sorry, this is a temporary hack implementation. Proper implementation to be added. I have added comments to document it.

2018-11-23 03:57 UTC, mhevery commented on packages/core/src/debug/debug_node.ts
> +    const event = document.createEvent('MouseEvent');
https://angular-team.atlassian.net/browse/FW-719

2018-11-23 04:51 UTC, mhevery commented on packages/core/src/view/services.ts
>      const debugCtx = getCurrentDebugContext() || (ivyEnabled ? this.createDebugContext(el) : null);
Good catch.

I removed the check

2018-11-23 04:52 UTC, mhevery commented
> If we decide to go ahead with this approach it is not clear for me what should happen with https://github.com/angular/angular/blob/master/packages/core/src/render3/debug.ts and all infrastructure that plugs it (https://github.com/angular/angular/blob/master/packages/core/testing/src/r3_test_bed.ts#L426-L429)

Ahh that is an excellent Catch! Yes that code is dead and I have now deleted it. :-)

2018-11-23 05:05 UTC, mary-poppins commented
You can preview bb8f9cb at https://pr27223-bb8f9cb.ngbuilds.io/.

2018-11-23 14:34 UTC, pkozlowski-opensource approved these changes
@mhevery  if you are positive that we can implement the rest of the `DebugElement` methods this LGTM
Would be probably good if someone else can do another pass on it as we are touching many parts

2018-11-23 15:20 UTC, JoostK commented on packages/core/src/debug/debug_node.ts
> +export interface DebugNode {
@mhevery Could you add to the list of breaking changes that `instanceof DebugNode` checks can no longer be done.

2018-11-26 17:45 UTC, mhevery commented
http://test/OCL:222839683:BASE:222839704:1543254316995:47c83647

2018-11-26 17:47 UTC, mhevery commented on packages/core/src/debug/debug_node.ts
> +export interface DebugNode {
@JoostK will add.

2018-11-26 18:57 UTC, kara approved these changes

2018-11-26 18:57 UTC, kara commented on packages/common/test/directives/ng_component_outlet_spec.ts
> +  fixmeIvy('destroy is not being called') &&
Can you add the Jira ticket number associated with this bug or mark it "unknown"? Otherwise it's hard to tell whether this root cause has been triaged.

2018-11-26 18:57 UTC, kara commented on packages/core/src/render3/assert.ts
> +  assertEqual(node instanceof Node, true, 'The provided value must be an instance of an DOM Node');
```suggestion
  assertEqual(node instanceof Node, true, 'The provided value must be an instance of a DOM Node');
```

2018-11-26 18:57 UTC, kara commented on packages/core/test/linker/ng_module_integration_spec.ts
> +      fixmeIvy('No module with ID myid loaded') && it('should register loaded modules', () => {
Reason should have Jira ticket or "unknown" here?

2018-11-26 20:14 UTC, IgorMinar commented on packages/core/src/debug/debug_node.ts
> +export interface DebugNode {
@mhevery it should be fine to change this behavior, but we need to document it.

2018-11-27 01:49 UTC, mary-poppins commented
You can preview c479d06 at https://pr27223-c479d06.ngbuilds.io/.

2018-11-27 01:51 UTC, mary-poppins commented
You can preview dfbf641 at https://pr27223-dfbf641.ngbuilds.io/.

2018-11-27 03:10 UTC, mary-poppins commented
You can preview 2564f80 at https://pr27223-2564f80.ngbuilds.io/.

2018-11-27 03:56 UTC, mhevery commented on packages/common/test/directives/ng_component_outlet_spec.ts
> +  fixmeIvy('destroy is not being called') &&
destroy on NgModuleRef is not being called

2018-11-27 03:56 UTC, mhevery commented on packages/core/src/render3/assert.ts
> +  assertEqual(node instanceof Node, true, 'The provided value must be an instance of an DOM Node');
fixed

2018-11-27 04:00 UTC, mhevery commented on packages/core/test/linker/ng_module_integration_spec.ts
> +      fixmeIvy('No module with ID myid loaded') && it('should register loaded modules', () => {
https://angular-team.atlassian.net/browse/FW-740

2018-11-27 04:07 UTC, mary-poppins commented
You can preview 07c95ec at https://pr27223-07c95ec.ngbuilds.io/.

2018-11-27 05:48 UTC, IgorMinar approved these changes
The rest looks good

2018-11-27 05:48 UTC, IgorMinar commented on packages/core/src/metadata/directives.ts
> + * @publicApi
why do we declare and export directive interface twice? that looks really fishy. Can we remove one?

2018-11-27 05:48 UTC, IgorMinar commented on tools/public_api_guard/core/testing.d.ts
> +export interface TestBed {
I can't believe that we missed having all of these interfaces in the guard. Good catch!!!

2018-11-27 06:02 UTC, mary-poppins commented
You can preview 8ecc627 at https://pr27223-8ecc627.ngbuilds.io/.

2018-11-27 06:11 UTC, mhevery commented on tools/public_api_guard/core/testing.d.ts
> +export interface TestBed {
fixed

2018-11-27 06:13 UTC, mhevery commented
http://test/OCL:222881368:BASE:222938072:1543299184520:907394cc

2018-11-27 06:16 UTC, mary-poppins commented
You can preview 9028161 at https://pr27223-9028161.ngbuilds.io/.

2018-11-27 10:07 UTC, pkozlowski-opensource commented
@mhevery looks like CI is red (the golden symbols file need updating etc.)

2018-11-27 17:30 UTC, mhevery commented
http://test/OCL:222839683:BASE:223003683:1543339823046:c3644f5e

2018-11-27 17:35 UTC, mary-poppins commented
You can preview 8ee99af at https://pr27223-8ee99af.ngbuilds.io/.

2018-11-27 17:57 UTC, mary-poppins commented
You can preview 7e65c8a at https://pr27223-7e65c8a.ngbuilds.io/.

2018-11-27 20:14 UTC, mary-poppins commented
You can preview 8504136 at https://pr27223-8504136.ngbuilds.io/.

2018-11-27 20:58 UTC, mary-poppins commented
You can preview f6f9612 at https://pr27223-f6f9612.ngbuilds.io/.

2018-11-27 21:43 UTC, closed without merging