docs: single run does not exist anymore
angular/angular pull request #27269
Opened 2018-11-26 13:07 UTC by Mathou54

and fix a typo (the flag is browsers and not browser)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2018-11-29 19:13 UTC, mjawulski commented
I have opened similar PR but changed wrong flags everywhere not only in one place. You can check details here: #27334

2018-12-07 01:23 UTC, IgorMinar requested changes

2018-12-07 07:17 UTC, Mathou54 commented on aio/content/guide/testing.md
> +  ng test --watch=false --no-progress --browsers=ChromeHeadlessCI
It has changed with version 7 (I think) of the CLI. Now the default for the watch flag is true.

https://github.com/angular/angular-cli/pull/13051/files

2019-01-14 15:55 UTC, brandonroberts commented
@Mathou54 will you rebase on master to see if these changes are still needed?

2019-01-15 07:35 UTC, Mathou54 commented
It has been changed with `--no-watch` and this flag is working.

2019-01-15 07:35 UTC, closed without merging