Add schematic details and links to config page
angular/angular pull request #27272
Opened 2018-11-26 18:22 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2018-11-27 18:20 UTC, mary-poppins commented
You can preview 0337411 at https://pr27272-0337411.ngbuilds.io/.

2018-11-27 19:00 UTC, alan-agius4 commented on aio/content/guide/workspace-config.md
> +* [component](https://github.com/angular/angular-cli/blob/v6.0.0-rc.8/packages/%40angular/cli/lib/config/schema.json#L74-L144)
I don't think we should use tags here, at least not for version 6.

But what should we use instead, thoughts?

//cc @hansl

2018-11-27 19:00 UTC, alan-agius4 commented on aio/content/guide/workspace-config.md
> +These schematics are collected in the [`@angular-devkit/build-angular` package](https://github.com/angular/angular-cli/blob/v6.0.0-rc.8/packages/%40angular/cli/lib/config/schema.json). They configure
Nit: `package` should not be part of the link.

2018-11-27 19:32 UTC, mary-poppins commented
You can preview 7d04ba3 at https://pr27272-7d04ba3.ngbuilds.io/.

2018-11-27 19:36 UTC, mary-poppins commented
You can preview 29427dd at https://pr27272-29427dd.ngbuilds.io/.

2018-11-27 19:42 UTC, mary-poppins commented
You can preview c2a61d9 at https://pr27272-c2a61d9.ngbuilds.io/.

2018-11-30 16:19 UTC, mary-poppins commented
You can preview 5810a3c at https://pr27272-5810a3c.ngbuilds.io/.

2018-12-03 17:13 UTC, mary-poppins commented
You can preview 1274cbf at https://pr27272-1274cbf.ngbuilds.io/.

2018-12-05 17:59 UTC, mary-poppins commented
You can preview a5a284b at https://pr27272-a5a284b.ngbuilds.io/.

2018-12-06 16:29 UTC, mary-poppins commented
You can preview 8411ac8 at https://pr27272-8411ac8.ngbuilds.io/.

2018-12-07 17:20 UTC, mary-poppins commented
You can preview eac3e38 at https://pr27272-eac3e38.ngbuilds.io/.

2018-12-10 17:05 UTC, mary-poppins commented
You can preview 8968ade at https://pr27272-8968ade.ngbuilds.io/.

2018-12-10 22:19 UTC, mary-poppins commented
You can preview 6c43ca9 at https://pr27272-6c43ca9.ngbuilds.io/.

2018-12-12 18:16 UTC, mary-poppins commented
You can preview 44bb8ce at https://pr27272-44bb8ce.ngbuilds.io/.

2018-12-12 22:16 UTC, jbogarthyde commented
@alan-agius4 @hansl  Please resolve issue of links into JSON schema so we can get this landed.

2018-12-14 17:02 UTC, mary-poppins commented
You can preview dc18441 at https://pr27272-dc18441.ngbuilds.io/.

2018-12-14 17:04 UTC, mary-poppins commented
You can preview 633af04 at https://pr27272-633af04.ngbuilds.io/.

2018-12-14 17:07 UTC, hansl commented on aio/content/guide/workspace-config.md
> +* [component](https://github.com/angular/angular-cli/blob/v6.0.0-rc.8/packages/%40angular/cli/lib/config/schema.json#L74-L144)
The tag is fine. I don't think we should use RC tags, only stable ones.

Is there a reason this points to 6.0 instead of 7?

2018-12-14 17:19 UTC, jbogarthyde commented on aio/content/guide/workspace-config.md
> +* [component](https://github.com/angular/angular-cli/blob/v6.0.0-rc.8/packages/%40angular/cli/lib/config/schema.json#L74-L144)
I'm not sure we should even have these individual links - Are they useful?
They were from the wiki page  -- one of our requirements was to make sure all information got transferred from the old wiki to the regular aio doc.

2018-12-14 17:54 UTC, mary-poppins commented
You can preview 96c4b6c at https://pr27272-96c4b6c.ngbuilds.io/.

2018-12-14 18:06 UTC, mary-poppins commented
You can preview b371794 at https://pr27272-b371794.ngbuilds.io/.

2018-12-17 15:42 UTC, mary-poppins commented
You can preview 77e8f25 at https://pr27272-77e8f25.ngbuilds.io/.

2018-12-17 17:51 UTC, mary-poppins commented
You can preview 3749532 at https://pr27272-3749532.ngbuilds.io/.

2018-12-18 16:00 UTC, mary-poppins commented
You can preview 6b14d6a at https://pr27272-6b14d6a.ngbuilds.io/.

2018-12-18 16:08 UTC, mary-poppins commented
You can preview 67ed101 at https://pr27272-67ed101.ngbuilds.io/.

2018-12-18 21:15 UTC, mary-poppins commented
You can preview 469f782 at https://pr27272-469f782.ngbuilds.io/.

2018-12-19 18:16 UTC, mary-poppins commented
You can preview ecac0ce at https://pr27272-ecac0ce.ngbuilds.io/.

2018-12-20 18:38 UTC, mary-poppins commented
You can preview 4e991c4 at https://pr27272-4e991c4.ngbuilds.io/.

2018-12-21 16:41 UTC, mary-poppins commented
You can preview d1c12b7 at https://pr27272-d1c12b7.ngbuilds.io/.

2018-12-26 18:13 UTC, mary-poppins commented
You can preview 3cb1875 at https://pr27272-3cb1875.ngbuilds.io/.

2019-01-04 22:53 UTC, mary-poppins commented
You can preview 87ffe07 at https://pr27272-87ffe07.ngbuilds.io/.

2019-01-10 23:49 UTC, mary-poppins commented
You can preview 549b2e5 at https://pr27272-549b2e5.ngbuilds.io/.

2019-01-11 21:41 UTC, mary-poppins commented
You can preview a0c4aeb at https://pr27272-a0c4aeb.ngbuilds.io/.

2019-01-14 17:11 UTC, mary-poppins commented
You can preview e9b38e1 at https://pr27272-e9b38e1.ngbuilds.io/.

2019-01-14 17:22 UTC, mary-poppins commented
You can preview 3673753 at https://pr27272-3673753.ngbuilds.io/.

2019-01-15 17:02 UTC, mary-poppins commented
You can preview 738c1eb at https://pr27272-738c1eb.ngbuilds.io/.

2019-01-16 20:00 UTC, mary-poppins commented
You can preview a02bb2d at https://pr27272-a02bb2d.ngbuilds.io/.

2019-01-17 16:53 UTC, mary-poppins commented
You can preview f0ec757 at https://pr27272-f0ec757.ngbuilds.io/.

2019-01-18 19:24 UTC, mary-poppins commented
You can preview 7aab846 at https://pr27272-7aab846.ngbuilds.io/.

2019-01-22 22:23 UTC, mary-poppins commented
You can preview 807799a at https://pr27272-807799a.ngbuilds.io/.

2019-01-23 21:11 UTC, mary-poppins commented
You can preview d6c7ab5 at https://pr27272-d6c7ab5.ngbuilds.io/.

2019-01-24 17:02 UTC, mary-poppins commented
You can preview cfd2f7a at https://pr27272-cfd2f7a.ngbuilds.io/.

2019-01-24 22:10 UTC, hansl approved these changes

2019-01-25 17:44 UTC, mary-poppins commented
You can preview f248ce9 at https://pr27272-f248ce9.ngbuilds.io/.

2019-01-28 23:12 UTC, mary-poppins commented
You can preview 9841aeb at https://pr27272-9841aeb.ngbuilds.io/.

2019-01-29 16:41 UTC, mary-poppins commented
You can preview 58203c4 at https://pr27272-58203c4.ngbuilds.io/.

2019-01-30 18:19 UTC, mary-poppins commented
You can preview 490118a at https://pr27272-490118a.ngbuilds.io/.

2019-02-01 17:03 UTC, mary-poppins commented
You can preview 9a3d2e7 at https://pr27272-9a3d2e7.ngbuilds.io/.

2019-02-04 17:13 UTC, mary-poppins commented
You can preview 1f668e2 at https://pr27272-1f668e2.ngbuilds.io/.

2019-02-05 16:31 UTC, mary-poppins commented
You can preview 4f1eb0b at https://pr27272-4f1eb0b.ngbuilds.io/.

2019-02-06 16:53 UTC, mary-poppins commented
You can preview 02b7854 at https://pr27272-02b7854.ngbuilds.io/.

2019-02-08 16:35 UTC, mary-poppins commented
You can preview efc53d0 at https://pr27272-efc53d0.ngbuilds.io/.

2019-02-11 16:51 UTC, mary-poppins commented
You can preview 3321316 at https://pr27272-3321316.ngbuilds.io/.

2019-02-12 21:37 UTC, mary-poppins commented
You can preview 6229ff6 at https://pr27272-6229ff6.ngbuilds.io/.

2019-02-13 17:01 UTC, mary-poppins commented
You can preview 623f9cb at https://pr27272-623f9cb.ngbuilds.io/.

2019-02-14 16:58 UTC, mary-poppins commented
You can preview 78ec2d8 at https://pr27272-78ec2d8.ngbuilds.io/.

2019-02-15 16:01 UTC, mary-poppins commented
You can preview 785e060 at https://pr27272-785e060.ngbuilds.io/.

2019-02-18 17:13 UTC, mary-poppins commented
You can preview 72fe9b0 at https://pr27272-72fe9b0.ngbuilds.io/.

2019-02-20 18:33 UTC, mary-poppins commented
You can preview 8baa633 at https://pr27272-8baa633.ngbuilds.io/.

2019-02-21 16:08 UTC, mary-poppins commented
You can preview cc4bf30 at https://pr27272-cc4bf30.ngbuilds.io/.

2019-02-21 21:11 UTC, Splaktar requested changes
I wasn't able to review every part of this, but I did notice that the links need some tweaking.

2019-02-21 21:11 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +The JSON schemas for the default schematics used by the CLI to generate projects and parts of projects are collected in the package [`@schematics/angular`](https://raw.githubusercontent.com/angular/a
We should not link to the raw content here. https://github.com/angular/angular-cli/blob/7.0.x/packages/schematics/angular/application/schema.json goes to the latest `7.0.x` version of this file.

2019-02-21 21:11 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +The JSON schemas that the define the options and defaults for each of these schematics are collected in the [`@angular-devkit/build-angular`](https://github.com/angular/angular-cli/blob/v7.1.3/packag
This should probably link to https://github.com/angular/angular-cli/blob/7.0.x/packages/angular/cli/lib/config/schema.json unless we want to update this one and the above to go to `7.3.x` instead of `7.0.x`.

It's probably best to link to the stable major release if there aren't important changes in the minors as we likely don't want to update the doc links for each minor release.

2019-02-21 23:46 UTC, mary-poppins commented
You can preview 98e03b6 at https://pr27272-98e03b6.ngbuilds.io/.

2019-02-22 16:23 UTC, mary-poppins commented
You can preview 05ea6b1 at https://pr27272-05ea6b1.ngbuilds.io/.

2019-02-25 17:01 UTC, mary-poppins commented
You can preview a6e1e3a at https://pr27272-a6e1e3a.ngbuilds.io/.

2019-02-25 19:02 UTC, hansl approved these changes

2019-02-26 16:42 UTC, mary-poppins commented
You can preview 66d01fa at https://pr27272-66d01fa.ngbuilds.io/.

2019-02-27 16:31 UTC, mary-poppins commented
You can preview 8895a5b at https://pr27272-8895a5b.ngbuilds.io/.

2019-02-28 16:26 UTC, mary-poppins commented
You can preview 9eba413 at https://pr27272-9eba413.ngbuilds.io/.

2019-03-04 16:19 UTC, mary-poppins commented
You can preview bd88700 at https://pr27272-bd88700.ngbuilds.io/.

2019-03-05 16:17 UTC, mary-poppins commented
You can preview 895bb98 at https://pr27272-895bb98.ngbuilds.io/.

2019-03-06 19:45 UTC, mary-poppins commented
You can preview 7bc49e5 at https://pr27272-7bc49e5.ngbuilds.io/.

2019-03-07 16:51 UTC, mary-poppins commented
You can preview fbf6330 at https://pr27272-fbf6330.ngbuilds.io/.

2019-03-11 17:14 UTC, mary-poppins commented
You can preview ae272ba at https://pr27272-ae272ba.ngbuilds.io/.

2019-03-12 15:15 UTC, mary-poppins commented
You can preview f720582 at https://pr27272-f720582.ngbuilds.io/.

2019-03-14 18:16 UTC, mary-poppins commented
You can preview c7487ee at https://pr27272-c7487ee.ngbuilds.io/.

2019-03-19 15:41 UTC, mary-poppins commented
You can preview 79db1d6 at https://pr27272-79db1d6.ngbuilds.io/.

2019-03-20 16:17 UTC, mary-poppins commented
You can preview ea07cf7 at https://pr27272-ea07cf7.ngbuilds.io/.

2019-03-25 07:47 UTC, Splaktar requested changes
There still seems to be some confusion here between Schematics and Architect that needs to be resolved. There are also some minor suggested improvements.

2019-03-25 07:47 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +At the top level of `angular.json`, a few properties configure the workspace, and a `projects` section contains the remaining per-project configuration options. CLI defaults set at the workspace leve
Can we add something to the effect of "These are the top level workspace properties:" here?

2019-03-25 07:47 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +Angular generation [schematics](guide/glossary#schematic) are instructions for modifying a project by adding files to it or modifying existing files.
It's possible for schematics to remove files from a project as well.

2019-03-25 07:47 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +The JSON schemas for the default schematics used by the CLI to generate projects and parts of projects are collected in the package [`@schematics/angular`](https://raw.githubusercontent.com/angular/a
```suggestion
The JSON schemas for the default schematics used by the CLI to generate projects and parts of projects are collected in the package [`@schematics/angular`](https://github.com/angular/angular-cli/blob/7.0.x/packages/schematics/angular/application/schema.json).
```

2019-03-25 07:47 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +Specify the schematic named for a subcommand in the format `schematic-package:schematic-name`;
```suggestion
Specify the schematic name for a subcommand in the format `schematic-package:schematic-name`;
```

2019-03-25 07:47 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +Architect is the tool that the CLI uses to perform complex tasks such as compilation and test running, according to provided configurations.
```suggestion
Architect is the tool that the CLI uses to perform complex tasks, such as compilation and test running, according to provided configurations.
```

2019-03-25 07:47 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +The JSON schemas that the define the options and defaults for each of these schematics are collected in the [`@angular-devkit/build-angular`](https://github.com/angular/angular-cli/blob/v7.1.3/packag
```suggestion
The JSON schemas that the define the options and defaults for each of these schematics are collected in the [`@angular-devkit/build-angular`](https://github.com/angular/angular-cli/blob/7.0.x/packages/angular/cli/lib/config/schema.json) package. The schemas configure options for the following Architect targets:
```

2019-03-25 07:47 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +| `options`       | This section contains default schematics for target options, used when no named alternative configuration is specified. See [Default target schematics](#default-target-schematics)
This doesn't quite seem accurate to me. Here's a common Architect `build` object like Angular `7.2.10` or `8.0.0-beta.7` generates
```js
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/web",
            "index": "projects/web/src/index.html",
            "main": "projects/web/src/main.ts",
            "polyfills": "projects/web/src/polyfills.ts",
            "tsConfig": "projects/web/tsconfig.app.json",
            "assets": [
              "projects/web/src/favicon.ico",
              "projects/web/src/assets"
            ],
            "styles": [
              "projects/web/src/styles.scss"
            ],
            "scripts": [],
            "es5BrowserSupport": true
          },
```
Categorizing `outputPath`, `index`, `main`, `polyfills`, etc as "default schematics" doesn't seem right. They do seem to be "default build target options" though.

2019-03-25 07:47 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +### Default target schematics
This section seems to be describing "Default builders" or "Default build targets", not "target schematics".

2019-03-25 07:47 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +Angular generation [schematics](guide/glossary#schematic) are instructions for modifying a project by adding files to it or modifying existing files.
```suggestion
Angular generation [schematics](guide/glossary#schematic) are instructions for modifying a project by adding files or modifying existing files.
```

2019-03-25 07:47 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +Individual schematics for Angular CLI `ng generate` sub-commands are collected in the package `@angular`.
```suggestion
Individual schematics for the default Angular CLI `ng generate` sub-commands are collected in the package `@angular`.
```

2019-03-25 16:19 UTC, jbogarthyde commented
Thanks Michael -- corrections made.

2019-03-25 16:23 UTC, mary-poppins commented
You can preview c504609 at https://pr27272-c504609.ngbuilds.io/.

2019-03-25 16:24 UTC, mary-poppins commented
You can preview 54b6e63 at https://pr27272-54b6e63.ngbuilds.io/.

2019-03-26 09:48 UTC, Splaktar requested changes
Some additional suggestions.

2019-03-26 09:48 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +The following properties at the top level of the file configure the workspace.
```suggestion
The following are properties at the top level of the workspace configuration file:
```

2019-03-26 09:48 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +Angular defines default schematics for use with the Architect tool and `ng run` command.
```suggestion
Angular defines default builders for use with the Architect tool and `ng run` command.
```

2019-03-26 09:48 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +The schematics provide instructions for using a particular tool to perform a complex operation.
```suggestion
The default builders provide implementations using a particular tool to perform a complex operation. Builders may do things like perform builds (using tools like Webpack, ng-packagr, and others), run schematics, execute tooling from a library like tslint, and execute test infrastructure (like Karma and Protractor).
```

2019-03-26 09:48 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +The JSON schemas that the define the options and defaults for each of these schematics are collected in the [`@angular-devkit/build-angular`](https://github.com/angular/angular-cli/blob/7.0.x/package
```suggestion
The JSON schemas that the define the options and defaults for each of these builders are collected in the [`@angular-devkit/build-angular`](https://github.com/angular/angular-cli/blob/7.0.x/packages/angular/cli/lib/config/schema.json) package. The schemas configure options for the following Architect build targets:
```

2019-03-26 15:34 UTC, mary-poppins commented
You can preview 323792a at https://pr27272-323792a.ngbuilds.io/.

2019-03-26 16:56 UTC, mary-poppins commented
You can preview e24620e at https://pr27272-e24620e.ngbuilds.io/.

2019-03-26 18:35 UTC, Splaktar requested changes

2019-03-26 18:35 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +The following properties are at the top level of the file configure the workspace.
My whole suggestion was not accepted for this line. It still has some grammar issues even after that update.

2019-03-26 18:37 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +The schematics provide instructions for using a particular tool to perform a complex operation.
I'd like some feedback on why the details in the second part of this suggestion were not accepted 😄

2019-03-26 19:41 UTC, jbogarthyde commented on aio/content/guide/workspace-config.md
> +The following properties are at the top level of the file configure the workspace.
Oops, fixing typo. This line introduces the list of top-level properties: 
"The following properties at the top level of the file configure the workspace."
 What do you think is wrong with it?

2019-03-26 19:51 UTC, mary-poppins commented
You can preview 7dbbc48 at https://pr27272-7dbbc48.ngbuilds.io/.

2019-03-26 19:58 UTC, Splaktar commented on aio/content/guide/workspace-config.md
> +The following properties are at the top level of the file configure the workspace.
Oh I think that I see how you want it to read... perhaps this would make that more clear to the reader:
"The following properties, at the top level of the file, configure the workspace."

2019-03-26 20:37 UTC, jbogarthyde commented on aio/content/guide/workspace-config.md
> +The following properties are at the top level of the file configure the workspace.
You're right. Done.

2019-03-26 20:44 UTC, mary-poppins commented
You can preview 58ff57f at https://pr27272-58ff57f.ngbuilds.io/.

2019-03-26 21:10 UTC, Splaktar approved these changes
LGTM

2019-03-27 16:33 UTC, mary-poppins commented
You can preview b6ce9a6 at https://pr27272-b6ce9a6.ngbuilds.io/.

2019-03-27 16:36 UTC, mary-poppins commented
You can preview 4adefc8 at https://pr27272-4adefc8.ngbuilds.io/.

2019-03-27 17:00 UTC, closed without merging