Add api doc for ngfor
angular/angular pull request #27377
Opened 2018-11-30 20:24 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
https://angular-team.atlassian.net/browse/DOCS-121

2018-12-01 03:13 UTC, trotyl commented on packages/common/src/directives/ng_for_of.ts
> + * The context for each instantiated view inherits from the outer context,
There's no context inheritance in Angular (like what in AngularJS), the context of embedded view is made available via explicit opt-in:

```html
<ng-template let-i="index">
```

The component context is the one real context for both direct content or its `<ng-template>`s, while the context of embedded view is an add-on being logically merged to current component context according to lexical position.

2018-12-01 03:13 UTC, trotyl commented on packages/common/src/directives/ng_for_of.ts
> + * For simplicity, Angular allows only one structural directive on an element.
The restriction only applies to short-hand micro syntax.

2018-12-02 10:36 UTC, Airblader commented on packages/common/src/directives/ng_for_of.ts
> + * The following exmaple shows the shorthand syntax with some options,
Typo in "example"

2018-12-03 18:02 UTC, mary-poppins commented
You can preview 5e834a6 at https://pr27377-5e834a6.ngbuilds.io/.

2018-12-05 17:42 UTC, mary-poppins commented
You can preview 9199f8b at https://pr27377-9199f8b.ngbuilds.io/.

2018-12-06 21:35 UTC, petebacondarwin commented on packages/common/src/directives/ng_for_of.ts
> + * once per item from an iterable.
This is a complicated way of describing this directive... 

> A structural directive that renders a template for each item in a collection.

2018-12-06 21:57 UTC, petebacondarwin commented on packages/common/src/directives/ng_for_of.ts
> + * The directive is placed on a root or anchor element, which becomes the parent
`root` and `anchor` are overloaded terms (especially anchor, which make me think of `<a>`). Perhaps a different way of describing this would be good?

2018-12-06 21:59 UTC, petebacondarwin commented on packages/common/src/directives/ng_for_of.ts
> + * <ng-template ngFor let-item [ngForOf]="items" let-i="index" [ngForTrackBy]="trackByFn">
I believe it is not necessary to have both the `ngFor` and `ngForOf` attributes in this form...

2018-12-06 22:03 UTC, petebacondarwin commented on packages/common/src/directives/ng_for_of.ts
> + * To customize the default tracking algorithm, `NgForOf` supports a `trackBy` option.
Perhaps precede this line with a sentence that indicates that the problem from the previous paragraph can be solved using tracking.

2018-12-07 02:14 UTC, trotyl commented on packages/common/src/directives/ng_for_of.ts
> + * <ng-template ngFor let-item [ngForOf]="items" let-i="index" [ngForTrackBy]="trackByFn">
@petebacondarwin It's required by the selector: `[ngFor][ngForOf]`

2018-12-07 08:05 UTC, petebacondarwin commented on packages/common/src/directives/ng_for_of.ts
> + * <ng-template ngFor let-item [ngForOf]="items" let-i="index" [ngForTrackBy]="trackByFn">
Oh yeah, I misread the component selector. I thought I had seen a comma in there.

2018-12-07 16:36 UTC, mary-poppins commented
You can preview 15abf57 at https://pr27377-15abf57.ngbuilds.io/.

2018-12-08 07:55 UTC, petebacondarwin commented on packages/common/src/directives/ng_for_of.ts
> + * ``
Ahah! Here is your problem. A bad triple backtick!

2018-12-08 16:37 UTC, mary-poppins commented
You can preview 8470551 at https://pr27377-8470551.ngbuilds.io/.

2018-12-10 17:00 UTC, mary-poppins commented
You can preview ee6ae2e at https://pr27377-ee6ae2e.ngbuilds.io/.

2018-12-10 22:17 UTC, mary-poppins commented
You can preview 035c30e at https://pr27377-035c30e.ngbuilds.io/.

2018-12-11 16:31 UTC, mary-poppins commented
You can preview f9ab67f at https://pr27377-f9ab67f.ngbuilds.io/.

2018-12-12 18:12 UTC, mary-poppins commented
You can preview 157fc2b at https://pr27377-157fc2b.ngbuilds.io/.

2018-12-12 22:07 UTC, jbogarthyde commented
All requested changes made 
@IgorMinar please approve/run g3 if needed

2018-12-12 22:25 UTC, petebacondarwin approved these changes

2018-12-14 17:59 UTC, mary-poppins commented
You can preview d333850 at https://pr27377-d333850.ngbuilds.io/.

2018-12-17 15:41 UTC, mary-poppins commented
You can preview d8ee269 at https://pr27377-d8ee269.ngbuilds.io/.

2018-12-18 16:03 UTC, mary-poppins commented
You can preview e671b4e at https://pr27377-e671b4e.ngbuilds.io/.

2018-12-19 18:11 UTC, mary-poppins commented
You can preview c55810c at https://pr27377-c55810c.ngbuilds.io/.

2018-12-20 18:39 UTC, mary-poppins commented
You can preview b4f9dbd at https://pr27377-b4f9dbd.ngbuilds.io/.

2018-12-21 16:42 UTC, mary-poppins commented
You can preview 6fb66d3 at https://pr27377-6fb66d3.ngbuilds.io/.

2018-12-26 18:12 UTC, mary-poppins commented
You can preview c639e67 at https://pr27377-c639e67.ngbuilds.io/.

2018-12-27 21:33 UTC, mary-poppins commented
You can preview 038230e at https://pr27377-038230e.ngbuilds.io/.

2019-01-04 22:52 UTC, mary-poppins commented
You can preview 7a24c56 at https://pr27377-7a24c56.ngbuilds.io/.

2019-01-10 23:50 UTC, mary-poppins commented
You can preview f9f332e at https://pr27377-f9f332e.ngbuilds.io/.

2019-01-11 21:40 UTC, mary-poppins commented
You can preview 2f00819 at https://pr27377-2f00819.ngbuilds.io/.

2019-01-14 17:08 UTC, mary-poppins commented
You can preview abea438 at https://pr27377-abea438.ngbuilds.io/.

2019-01-15 15:31 UTC, brandonroberts requested changes

2019-01-15 15:31 UTC, brandonroberts commented on packages/common/src/directives/ng_for_of.ts
>   * See a [live demo](http://plnkr.co/edit/KVuXxDp0qinGDyo307QW?p=preview) for a more detailed
The plunker demo is broken and should be removed

2019-01-15 15:31 UTC, brandonroberts commented on packages/common/src/directives/ng_for_of.ts
> - * ### Local Variables
Shouldn't this section be titled as `Usage Notes` instead of `Description`?

2019-01-15 15:31 UTC, brandonroberts commented on packages/common/src/directives/ng_for_of.ts
>   * See a [live demo](http://plnkr.co/edit/KVuXxDp0qinGDyo307QW?p=preview) for a more detailed
This is what it looks like, but I don't know if its worth keeping: https://stackblitz.com/edit/angular-ngevhx?file=src%2Fapp%2Fapp.component.ts

2019-01-15 15:33 UTC, brandonroberts commented on packages/common/src/directives/ng_for_of.ts
> + * @see [Structural Directives](guide/structural-directives)
Are we documenting the inputs and methods also?

2019-01-15 16:34 UTC, jbogarthyde commented on packages/common/src/directives/ng_for_of.ts
>   * See a [live demo](http://plnkr.co/edit/KVuXxDp0qinGDyo307QW?p=preview) for a more detailed
Removing it.

2019-01-15 16:34 UTC, jbogarthyde commented on packages/common/src/directives/ng_for_of.ts
> - * ### Local Variables
No - for directives, the long description and usage notes get run together - we only use the usageNotes tag to allow headings within the long description.

2019-01-15 16:34 UTC, mary-poppins commented
You can preview fcc277f at https://pr27377-fcc277f.ngbuilds.io/.

2019-01-15 16:54 UTC, jbogarthyde commented on packages/common/src/directives/ng_for_of.ts
> + * @see [Structural Directives](guide/structural-directives)
I'm not sure how to do so. 
I don't know either how to describe them, or where to put the description for it to be rendered.
@petebacondarwin - should we try to do this? The inputs are described in the referenced Guide (although the description is a bit difficult). 

I see that one static method does have a description, which is also a bit difficult and is about Ivy, which isn't released or documented yet.

2019-01-15 17:00 UTC, mary-poppins commented
You can preview 31a149b at https://pr27377-31a149b.ngbuilds.io/.

2019-01-16 19:55 UTC, mary-poppins commented
You can preview 89acc53 at https://pr27377-89acc53.ngbuilds.io/.

2019-01-16 22:40 UTC, jbogarthyde commented on packages/common/src/directives/ng_for_of.ts
> + * @see [Structural Directives](guide/structural-directives)
Attempted to add doc for Inputs - PLEASE CHECK.

2019-01-16 22:44 UTC, mary-poppins commented
You can preview 1d37f9c at https://pr27377-1d37f9c.ngbuilds.io/.

2019-01-17 08:43 UTC, petebacondarwin commented on packages/common/src/directives/ng_for_of.ts
> +   * When supplied, Angular tracks changes by the return value of the function.
There is quite a good description of the aims of `trackBy` in the AngularJS docs: https://docs.angularjs.org/api/ng/directive/ngRepeat#tracking-and-duplicates

I think this description should be more along the lines of:

> A function that defines how to track items in the iterable.
>
> When items are added, moved or removed in the iterable the directive must re-render the appropriate DOM nodes. To minimize churn in the DOM, only nodes that have changed should be re-rendered. By default `ngForOf` will assume that the object instance identifies the node in the iterable.
> 
> When supplied, the directive will use the result of calling this function as the identify of the item rather than the identify of the object itself.

2019-01-17 08:44 UTC, petebacondarwin commented on packages/common/src/directives/ng_for_of.ts
> +   * The [template reference variable](guide/template-syntax#template-reference-variables--var-)
I think for users this can be more simply put: this input holds a reference to the template that will be stamped out for each item in the iterable.

2019-01-17 16:14 UTC, mary-poppins commented
You can preview 51ff925 at https://pr27377-51ff925.ngbuilds.io/.

2019-01-17 16:49 UTC, mary-poppins commented
You can preview 93305b9 at https://pr27377-93305b9.ngbuilds.io/.

2019-01-17 17:03 UTC, jbogarthyde commented
@brandonroberts Please check and resolve "review requested" status.

2019-01-17 18:40 UTC, jbogarthyde commented
All green now - @brandonroberts, can this be approved?

2019-01-18 19:23 UTC, mary-poppins commented
You can preview a2bef56 at https://pr27377-a2bef56.ngbuilds.io/.

2019-01-21 12:52 UTC, brandonroberts commented on packages/common/src/directives/ng_for_of.ts
> + * @see [Structural Directives](guide/structural-directives)
`ngDoCheck` needs a description, but everything else LGTM.

2019-01-21 17:04 UTC, mary-poppins commented
You can preview 81b5ccb at https://pr27377-81b5ccb.ngbuilds.io/.

2019-01-21 18:46 UTC, brandonroberts approved these changes

2019-01-21 18:48 UTC, brandonroberts commented
Caretaker note: This is a docs-only change that should not impact g3. Please run presubmit.

2019-01-22 18:36 UTC, alxhub commented
[Presubmit](http://test/OCL:230365480:BASE:230366491:1548182026274:bcc80304)

2019-01-22 20:19 UTC, closed without merging