docs(core): describe your change...
angular/angular pull request #27374
Opened 2018-11-30 18:36 UTC by ErickXavier

Adds the information that the templateUrl and styleUrls options supports only relative Urls.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
This change updates the documentation to add the information that the templateUrl and styleUrls supports only relative Urls.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2018-11-30 20:21 UTC, Airblader requested changes
Your commit message's headline is currently just a copy-pasted placeholder. It should instead do what it says: describe the change.

2018-12-11 13:56 UTC, brandonroberts requested changes
Update git commit message to `docs: add relative path information to component metadata`

2018-12-28 15:18 UTC, brandonroberts approved these changes

2018-12-29 07:40 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> +   * The relative URL of a template file for an Angular component. If provided,
This is **NOT** about relative URL, but relative path, they're totally different concepts. Any URL do not start with **scheme** is a relative URL:

+ `/foo/bar`: this is relative URL;
+ `//example.com`: this is relative URL.

2019-01-07 03:45 UTC, ErickXavier commented on packages/core/src/metadata/directives.ts
> +   * The relative URL of a template file for an Angular component. If provided,
The document already talks about URLs. I just added the "relative" information just to make sure it is well detailed. Because when you say just "URL", at least for me, I would assume it would be a non absolute URL. But I understand the difference between URLs and paths. I agree the document could be changed to paths and I'll do it.

2019-01-07 03:59 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> +   * The relative URL of a template file for an Angular component. If provided,
Then the change itself is incorrect. Angular do support absolute URL in JIT, but only require it in AOT. So assuming this documentation is about the AOT requirement, then relative URL still won't work (as explained `//example.com` is also a relative URL), but only a small subset of it does.

2019-01-07 04:02 UTC, closed without merging

2019-01-07 04:03 UTC, ErickXavier commented on packages/core/src/metadata/directives.ts
> +   * The relative URL of a template file for an Angular component. If provided,
Ok, and what about changing it to **relative paths and/or absolute URLs**?

2019-01-07 04:07 UTC, trotyl commented on packages/core/src/metadata/directives.ts
> +   * The relative URL of a template file for an Angular component. If provided,
I'm not sure what's the intent of this change, the relative URLs which not being relative path of course still supported by JIT, if it's about AOT requirement, I'd suggest adding a side note rather than change the description of concept.

2019-01-07 16:34 UTC, ErickXavier commented on packages/core/src/metadata/directives.ts
> +   * The relative URL of a template file for an Angular component. If provided,
I just think the description is incomplete without this information.