Add api doc for viewport scroller
angular/angular pull request #27381
Opened 2018-11-30 20:36 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
JIRA https://angular-team.atlassian.net/browse/DOCS-543

2018-11-30 20:40 UTC, mary-poppins commented
You can preview 11b512b at https://pr27381-11b512b.ngbuilds.io/.

2018-12-05 17:58 UTC, mary-poppins commented
You can preview aa0f3f9 at https://pr27381-aa0f3f9.ngbuilds.io/.

2018-12-06 22:30 UTC, petebacondarwin commented on packages/common/src/viewport_scroller.ts
>     * Sets the scroll position.
It might be nice to use the same language as `scrollToAnchor`...
E.g. `Scroll to the specified position.`

2018-12-06 22:32 UTC, petebacondarwin commented on packages/common/src/viewport_scroller.ts
> +   * offset position value or invokes the given function.
This description should be kept in sync with the same method on the base class above, right?

2018-12-06 22:33 UTC, petebacondarwin commented on packages/common/src/viewport_scroller.ts
> +   * Scrolls to an anchor element.
Should action method (that do stuff) be more imperative? E.g. "Scroll to" rather than "Scrolls to"?

2018-12-06 22:34 UTC, petebacondarwin requested changes
Minor comments

2018-12-07 21:09 UTC, jbogarthyde commented on packages/common/src/viewport_scroller.ts
> +   * Scrolls to an anchor element.
It's a description of what it does, so this is the convention I've been using.

2018-12-07 21:15 UTC, mary-poppins commented
You can preview 86b24d1 at https://pr27381-86b24d1.ngbuilds.io/.

2018-12-07 21:16 UTC, mary-poppins commented
You can preview e71f500 at https://pr27381-e71f500.ngbuilds.io/.

2018-12-10 17:03 UTC, mary-poppins commented
You can preview f41f570 at https://pr27381-f41f570.ngbuilds.io/.

2018-12-10 22:20 UTC, mary-poppins commented
You can preview 87c5863 at https://pr27381-87c5863.ngbuilds.io/.

2018-12-11 16:29 UTC, mary-poppins commented
You can preview 18d969d at https://pr27381-18d969d.ngbuilds.io/.

2018-12-11 21:01 UTC, mary-poppins commented
You can preview a5bee6a at https://pr27381-a5bee6a.ngbuilds.io/.

2018-12-11 21:05 UTC, jbogarthyde commented
@petebacondarwin All changes/corrections/suggestions incorporated - please approve.

2018-12-12 18:14 UTC, mary-poppins commented
You can preview 2a42069 at https://pr27381-2a42069.ngbuilds.io/.

2018-12-12 22:03 UTC, jbogarthyde commented
@petebacondarwin please remove changes-required status
@IgorMinar please approve/run g3 if needed

2018-12-12 22:22 UTC, petebacondarwin approved these changes

2018-12-14 17:10 UTC, mary-poppins commented
You can preview 9281401 at https://pr27381-9281401.ngbuilds.io/.

2018-12-14 17:12 UTC, mary-poppins commented
You can preview bd393dc at https://pr27381-bd393dc.ngbuilds.io/.

2018-12-14 17:13 UTC, mary-poppins commented
You can preview f8f8bf0 at https://pr27381-f8f8bf0.ngbuilds.io/.

2018-12-17 15:44 UTC, mary-poppins commented
You can preview 496a15c at https://pr27381-496a15c.ngbuilds.io/.

2018-12-18 12:16 UTC, trotyl commented on packages/common/src/viewport_scroller.ts
> + * Base class for managing the scroll position.
This doesn't seem right, a base class is for `extends`ing, but this one (as well as other injection token) are just for defining the shape and being `implements`ed by real implementation. It never act as the base class.

2018-12-18 16:02 UTC, mary-poppins commented
You can preview 40373a5 at https://pr27381-40373a5.ngbuilds.io/.

2018-12-18 16:31 UTC, jbogarthyde commented on packages/common/src/viewport_scroller.ts
> + * Base class for managing the scroll position.
@trotyl Is this better?

2018-12-18 16:35 UTC, mary-poppins commented
You can preview 3fe9dd0 at https://pr27381-3fe9dd0.ngbuilds.io/.

2018-12-19 02:57 UTC, trotyl commented on packages/common/src/viewport_scroller.ts
> + * Base class for managing the scroll position.
LGTM

2018-12-19 18:13 UTC, mary-poppins commented
You can preview ce20593 at https://pr27381-ce20593.ngbuilds.io/.

2018-12-20 18:37 UTC, mary-poppins commented
You can preview 28099b8 at https://pr27381-28099b8.ngbuilds.io/.

2018-12-21 16:42 UTC, mary-poppins commented
You can preview f053ba5 at https://pr27381-f053ba5.ngbuilds.io/.

2018-12-26 18:13 UTC, mary-poppins commented
You can preview 3183e22 at https://pr27381-3183e22.ngbuilds.io/.

2018-12-26 19:43 UTC, benlesh commented
sync is running: https://test.corp.google.com/ui#id=OCL:226938731:BASE:226938796:1545853368729:69135b73

2018-12-26 19:48 UTC, closed without merging