docs(fix): wrong explanation of @Injectable decorator
angular/angular pull request #27480
Opened 2018-12-05 15:18 UTC by stevermeister

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Other information

it was wrong explanation of @Injectable decorator

2018-12-05 15:35 UTC, stevermeister commented
hm, it says problem with commit message, what's wrong with it?
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

2018-12-05 16:48 UTC, alfaproject commented
`fix` is not a valid scope. That's a commit type, but in here the type is `docs`.

This is what you probably want: `docs: fix wrong explanation of @Injectable decorator`

2018-12-06 02:47 UTC, trotyl commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
The requirement only applies to [`ClassProvider`](https://angular.io/api/core/ClassProvider). For example, [`Router`](https://angular.io/api/router/Router) is a well-known service that has many dependencies, but not having `Injectable()` due to it's created by [`FactoryProvider`](https://angular.io/api/core/FactoryProvider):

https://github.com/angular/angular/blob/8282e15c2becbe42a49befa07d6407247e8243d8/packages/router/src/router.ts#L226-L228

2018-12-06 10:00 UTC, stevermeister commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
you are right, but current version is completely wrong

2018-12-21 14:50 UTC, brandonroberts commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
I'm not sure how this is more clear. It doesn't enable you to inject services, it enables your service to be injected somewhere else. How about:

`The Injectable decorator provides metadata that allows your class provider needs to be *injected* as a dependency.`

2018-12-21 14:55 UTC, trotyl commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
@brandonroberts That's the wrong explanation today, when `MyService` being decorated with `@Injectable()`, it **means** other dependencies can be injected into `MyService`. It **doesn't mean** `MyService` can be injected into other types.

2018-12-21 15:07 UTC, brandonroberts commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
Gotcha. The statement still could be clearer.

`
The decorator provides the metadata that allows other providers to be **injected** into your service.
`

2018-12-21 15:12 UTC, trotyl commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
`Service` is a common case, but not the only one, for example [a base class of component/directive also need `@injectable()`](https://github.com/angular/angular/issues/16566#issuecomment-337960028).

I'd prefer a more general wording that fits all conditions.

2018-12-21 15:21 UTC, brandonroberts commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
More general as in `dependencies` instead of `providers`?

2018-12-21 15:23 UTC, trotyl commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
I mean `into your type/class` rather than `into your service`, as the target might not be a service.

2018-12-21 15:58 UTC, stevermeister commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
@brandonroberts , 
yes thx. hope I understand you correctly

2018-12-21 16:01 UTC, trotyl commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
I didn't really mean `type/class` literally, but whichever of them... 😢

2018-12-21 16:02 UTC, brandonroberts requested changes

2018-12-21 16:02 UTC, brandonroberts commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
Slight tweak.

`
The decorator provides the metadata that allows other providers to be **injected** into your type/class as a dependency.
`

2018-12-21 16:11 UTC, stevermeister commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
my bad, fixed

2018-12-27 17:05 UTC, stevermeister commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
is it good now?

2018-12-28 13:48 UTC, brandonroberts requested changes
The decorator provides the metadata that allows to *inject* another services into your class as a dependency.

2018-12-28 13:48 UTC, brandonroberts commented on aio/content/guide/architecture.md
> +For data or logic that isn't associated with a specific view, and that you want to share across components, you create a *service* class. A service class definition is immediately preceded by the `@I
Should read as:

`The decorator provides the metadata that allows other providers to be **injected** into your class as a dependency.`

2019-01-14 14:25 UTC, brandonroberts requested changes

2019-01-16 14:03 UTC, stevermeister commented
@brandonroberts sure, will do

2019-01-16 14:12 UTC, stevermeister commented
@brandonroberts done

2019-01-22 15:17 UTC, brandonroberts approved these changes

2019-01-22 15:18 UTC, brandonroberts commented
Caretaker note: This is a docs-only change and I am using a global approval.

2019-01-22 15:19 UTC, brandonroberts commented
Thanks @stevermeister!

2019-01-22 18:19 UTC, closed without merging