fix(ivy): support complex type nodes in ModuleWithProviders
angular/angular pull request #27562
Opened 2018-12-09 14:39 UTC by JoostK

With ngcc's ability to fixup pre-Ivy `ModuleWithProviders` such that they
include a reference to the NgModule type, the type may become a qualified
name:

```
import {ModuleWithProviders} from '@angular/core';
import * as ngcc0 from './module';

export declare provide(): ModuleWithProviders<ngcc0.Module>;
```

ngtsc now takes this situation into account when reflecting a
`ModuleWithProvider`'s type argument.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

2018-12-09 17:52 UTC, JoostK commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
>      expect(dtsContents).toContain(`import * as i1 from 'router';`);
Hmm, we have to be careful here. The `InternalRouterModule` is not publicly exported in this test, but still we generated an import to the public API. I think this is correct, as that module is the one that should be exporting that symbol, but it seems to be up to the library author to actually make the type publicly available.

2018-12-10 18:32 UTC, alxhub approved these changes

2018-12-10 18:32 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
>      expect(dtsContents).toContain(`import * as i1 from 'router';`);
This is actually something we're aware of. `ngcc` will publicly export these symbols. `ngtsc` will throw an error (which would be a breaking change in Ivy).

2018-12-11 12:38 UTC, petebacondarwin commented
CARETAKER: Can you please run presubmit and then merge.

2018-12-12 20:58 UTC, mhevery commented
http://test/OCL:225237261:BASE:225237286:1544648302785:6f9e937

2018-12-13 01:43 UTC, alxhub requested changes

2018-12-13 01:43 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +        import * as internal from './internal';
Let's create a separate test for this case, instead of mutating this one.

2018-12-13 01:52 UTC, IgorMinar commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +        import * as internal from './internal';
+1 - putting too many assertions into a single test makes it hard to understand the intent of the assertion. please create a separate spec/`it` with clear description. thank you!

2018-12-14 01:52 UTC, alxhub approved these changes

2018-12-14 06:40 UTC, petebacondarwin commented
CARETAKER: Can you please run presubmit?

2018-12-14 18:24 UTC, closed without merging