fix(ivy): check semantics of NgModule for consistency
angular/angular pull request #27604
Opened 2018-12-11 18:43 UTC by mhevery

`NgModule` requires that `Component`s/`Directive`s/`Pipe`s are listed in
declarations, and that each `Component`s/`Directive`s/`Pipe` is declared
in exactly one `NgModule`. This change adds runtime checks to ensure
that these sementics are true at runtime.

There will need to be seperate set of checks for the AoT path of the
codebase to verify that same set of semantics hold. Due to current
design there does not seem to be an easy way to share the two checks
because JIT deal with references where as AoT deals with AST nodes.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [n/a] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2018-12-11 18:48 UTC, mary-poppins commented
You can preview 8197b6d at https://pr27604-8197b6d.ngbuilds.io/.

2018-12-11 19:16 UTC, kara requested changes
Nits

2018-12-11 19:16 UTC, kara commented on packages/core/src/render3/jit/module.ts
> +      // components are often compiled in many different context. If we are tracking components add
```suggestion
      // components are often compiled in many different contexts. If we are tracking components, add
```

2018-12-11 19:16 UTC, kara commented on packages/core/src/render3/jit/module.ts
> +        verifySemanticsOfNgModuleDef(moduleType as unknown as NgModuleType, ngModule);
Should these be dev mode checks?

2018-12-11 19:18 UTC, alxhub approved these changes

2018-12-11 19:18 UTC, alxhub commented on packages/core/src/linker/ng_module_factory_loader.ts
> +export function registerNgModuleType(id: string, ngModuleType: NgModuleType) {
This could have been a separate `feat` commit, since this is new behavior :)

2018-12-11 19:18 UTC, alxhub commented on packages/core/test/linker/ng_module_integration_spec.ts
> +          .fit('should throw when no type and not @Inject (factory case)', () => {
`.fit`. -> `.it`

2018-12-11 19:35 UTC, JoostK commented on packages/core/src/linker/ng_module_factory_loader.ts
> +export function getModuleFactory__POST_R3__(id: string): NgModuleFactory<any> {
Please add to `core_render3_private_export.ts` as it will otherwise be DCE'd during Rollup bundling ⚠️

2018-12-11 19:35 UTC, JoostK commented on packages/core/src/di/r3_injector.ts
> +      const argLength = token.length;
Rename `argLength` to `numberOfParams`? The number of arguments is zero here as we don't have any args at this point

2018-12-11 19:35 UTC, JoostK commented on packages/core/src/di/r3_injector.ts
> +        args.fill('?');
Can just become
```typescript
const args: string[] = new Array(argLength).fill('?');
```

2018-12-11 19:35 UTC, JoostK commented on packages/core/src/linker/ng_module_factory_loader.ts
> +let modules = new Map<string, NgModuleFactory<any>|NgModuleType>();
No longer reassigned.
```suggestion
const modules = new Map<string, NgModuleFactory<any>|NgModuleType>();
```

2018-12-11 19:35 UTC, JoostK commented on packages/core/src/render3/jit/module.ts
> +        // We are exporting something which we don't explicitly
```suggestion
        // We are exporting something which we don't explicitly declare.
```

2018-12-11 19:35 UTC, JoostK commented on packages/core/test/linker/ng_module_integration_spec.ts
> +        obsoleteInIvy('Ivy does not have a restriction on classes being exported')
I don't follow. This test is not about exported classes (as in ES module exports) but about the visibility of NG directives/pipes that are not exported from their NgModule so should not be visible to outside modules.

2018-12-11 19:35 UTC, JoostK commented on packages/core/testing/src/r3_test_bed.ts
> +    // Drain an reset previous associations between the Component and NgModule.
```suggestion
    // Drain and reset previous associations between the Component and NgModule.
```

2018-12-11 21:47 UTC, mhevery commented on packages/core/src/render3/jit/module.ts
> +        || getDirectiveDef(type) && 'directive'        //
Those comments are there so t that the formatting looks sane.

2018-12-11 21:50 UTC, mary-poppins commented
You can preview c0b8828 at https://pr27604-c0b8828.ngbuilds.io/.

2018-12-11 21:50 UTC, mary-poppins commented
You can preview 09243f9 at https://pr27604-09243f9.ngbuilds.io/.

2018-12-11 21:50 UTC, mary-poppins commented
You can preview 5ccfe99 at https://pr27604-5ccfe99.ngbuilds.io/.

2018-12-11 21:51 UTC, mary-poppins commented
You can preview e4614ce at https://pr27604-e4614ce.ngbuilds.io/.

2018-12-11 21:52 UTC, mary-poppins commented
You can preview 328d4e9 at https://pr27604-328d4e9.ngbuilds.io/.

2018-12-11 21:52 UTC, mary-poppins commented
You can preview 33668b4 at https://pr27604-33668b4.ngbuilds.io/.

2018-12-11 21:52 UTC, mhevery commented on packages/core/test/linker/ng_module_integration_spec.ts
> +          .fit('should throw when no type and not @Inject (factory case)', () => {
fixed

2018-12-11 21:52 UTC, mary-poppins commented
You can preview 2ba9011 at https://pr27604-2ba9011.ngbuilds.io/.

2018-12-11 21:53 UTC, mhevery commented on packages/core/src/render3/jit/module.ts
> +        || getDirectiveDef(type) && 'directive'        //
`kind` is used in the error msg.

2018-12-11 21:54 UTC, mhevery commented on packages/core/src/render3/jit/module.ts
> +        // We are exporting something which we don't explicitly
fixed

2018-12-11 21:54 UTC, mhevery commented on packages/core/src/render3/jit/module.ts
> +        verifySemanticsOfNgModuleDef(moduleType as unknown as NgModuleType, ngModule);
good idea, done.

2018-12-11 21:56 UTC, mhevery commented on packages/core/test/linker/ng_module_integration_spec.ts
> +          .fit('should throw when no type and not @Inject (factory case)', () => {
fixed

2018-12-11 21:59 UTC, mhevery commented on packages/core/src/linker/ng_module_factory_loader.ts
> +export function getModuleFactory__POST_R3__(id: string): NgModuleFactory<any> {
done

2018-12-11 22:01 UTC, mhevery commented on packages/core/src/di/r3_injector.ts
> +      const argLength = token.length;
fixed

2018-12-11 22:01 UTC, mhevery commented on packages/core/src/di/r3_injector.ts
> +        args.fill('?');
fixed

2018-12-12 00:07 UTC, mary-poppins commented
You can preview 2c02fcd at https://pr27604-2c02fcd.ngbuilds.io/.

2018-12-12 21:33 UTC, mhevery commented on packages/core/test/linker/ng_module_integration_spec.ts
> +        obsoleteInIvy('Ivy does not have a restriction on classes being exported')
You are right, I have miss-understood the test. making it pass now.

2018-12-13 09:38 UTC, pkozlowski-opensource commented on packages/core/src/render3/view_ref.ts
> +      const index = this._viewContainerRef.indexOf(this);
See https://github.com/angular/angular/pull/27585/files#r241200578

2018-12-13 09:44 UTC, pkozlowski-opensource commented on packages/core/test/render3/pipe_spec.ts
> +    }).toThrowError(/The pipe 'randomPipeName' could not found!/);
missing `be`, the error message is `The pipe 'randomPipeName' could not be found!` - see the failing tests on CI

2018-12-13 09:46 UTC, pkozlowski-opensource commented
There are legit lint and tests failures

2018-12-13 18:42 UTC, mhevery commented on packages/core/src/render3/view_ref.ts
> +      const index = this._viewContainerRef.indexOf(this);
I fixed up #27585 and will rebase mine on top of that fix.

2018-12-13 18:44 UTC, mhevery commented on packages/core/test/render3/pipe_spec.ts
> +    }).toThrowError(/The pipe 'randomPipeName' could not found!/);
fixed

2018-12-14 00:34 UTC, mary-poppins commented
You can preview b8bf96c at https://pr27604-b8bf96c.ngbuilds.io/.

2018-12-14 01:22 UTC, kara approved these changes
LGTM, aside from the CI failures

2018-12-14 22:12 UTC, mary-poppins commented
You can preview 679ff56 at https://pr27604-679ff56.ngbuilds.io/.

2018-12-15 00:41 UTC, mary-poppins commented
You can preview 30e5f7f at https://pr27604-30e5f7f.ngbuilds.io/.

2018-12-17 17:59 UTC, mary-poppins commented
You can preview 5ce177a at https://pr27604-5ce177a.ngbuilds.io/.

2018-12-17 20:04 UTC, mhevery commented on packages/core/src/render3/jit/module.ts
> +        ngDevMode && verifySemanticsOfNgModuleDef(moduleType as unknown as NgModuleType);
```suggest
         ngDevMode && verifySemanticsOfNgModuleDef(moduleType as unknown as NgModuleType);
```

2018-12-17 20:11 UTC, mary-poppins commented
You can preview 66e2f6f at https://pr27604-66e2f6f.ngbuilds.io/.

2018-12-17 22:50 UTC, closed without merging