fix(ivy): @Host should behave as in View Engine
angular/angular pull request #27646
Opened 2018-12-13 10:15 UTC by marclaval

This PR follows discussions that happened in #27387 and #27444.

The implemented rule is: when `@Host` is added, from the host itself, only viewProviders and the component can be found, providers and other directives can't.

2018-12-13 10:19 UTC, mary-poppins commented
You can preview 313f1b7 at https://pr27646-313f1b7.ngbuilds.io/.

2018-12-13 14:08 UTC, mary-poppins commented
You can preview 4db17b3 at https://pr27646-4db17b3.ngbuilds.io/.

2018-12-13 14:48 UTC, mary-poppins commented
You can preview 930f2f1 at https://pr27646-930f2f1.ngbuilds.io/.

2018-12-13 15:38 UTC, mary-poppins commented
You can preview ffd86aa at https://pr27646-ffd86aa.ngbuilds.io/.

2018-12-14 04:37 UTC, kara requested changes
Nits

2018-12-17 14:44 UTC, marclaval commented on packages/core/test/render3/di_spec.ts
> +          it('should behave same as ViewEngine', () => {
LGTM

2018-12-17 15:30 UTC, marclaval commented on packages/core/src/render3/util.ts
> +export function getHostTElementNode(lView: LView): TElementNode|null {
Did it, but I'm not sure I like it, please let me know what you think

2018-12-17 15:33 UTC, mary-poppins commented
You can preview fb1e95d at https://pr27646-fb1e95d.ngbuilds.io/.

2018-12-17 15:46 UTC, mary-poppins commented
You can preview 10492fc at https://pr27646-10492fc.ngbuilds.io/.

2018-12-17 18:28 UTC, kara requested changes

2018-12-19 11:30 UTC, marclaval commented on packages/core/src/render3/util.ts
> +                       declarationMode && rootTNode.type !== TNodeType.Element)) {
💡

2018-12-19 18:18 UTC, kara approved these changes
LGTM

2018-12-19 18:21 UTC, kara commented
[presubmit](http://test/OCL:226193097:BASE:226193166:1545243668024:655997dd)

2018-12-19 20:13 UTC, closed without merging