ci: replace our pullapprove setup with GitHub CODEOWNERS
angular/angular pull request #27690
Opened 2018-12-15 06:33 UTC by IgorMinar

Summary of changes:
- created .github/CODEOWNERS with docs and config similar to the one in .pullapprove.yml
- updated docs
- updated .github/angular-robot.yml to not expect pullapprove status
- removed .pullapprove.yml

2018-12-15 07:54 UTC, ocombe requested changes
Any chance we could get an "i18n" section too?

```md
/aio/content/guide/i18n.md                     @ocombe @AndrewKushnir @IgorMinar @jenniferfell @kara @mhevery
/packages/core/src/i18n/**                     @ocombe @alxhub @AndrewKushnir @IgorMinar @jenniferfell @kara @mhevery @pkozlowski-opensource
/packages/core/src/render3/i18n.ts             @ocombe @mhevery @alxhub @AndrewKushnir @IgorMinar @jenniferfell @kara @pkozlowski-opensource
/packages/core/src/render3/i18n.md             @ocombe @mhevery @alxhub @AndrewKushnir @IgorMinar @jenniferfell @kara @pkozlowski-opensource
/packages/core/src/render3/interfaces/i18n.ts  @ocombe @mhevery @alxhub @AndrewKushnir @IgorMinar @jenniferfell @kara @pkozlowski-opensource
/packages/common/locales/**                    @ocombe @alxhub @AndrewKushnir @IgorMinar @jenniferfell @kara @mhevery @pkozlowski-opensource
/packages/common/src/i18n/**                   @ocombe @alxhub @AndrewKushnir @IgorMinar @jenniferfell @kara @mhevery @pkozlowski-opensource
/packages/common/src/pipes/date_pipe.ts        @ocombe @alxhub @AndrewKushnir @IgorMinar @jenniferfell @kara @mhevery @pkozlowski-opensource
/packages/common/src/pipes/i18n_plural_pipe.ts @ocombe @alxhub @AndrewKushnir @IgorMinar @jenniferfell @kara @mhevery @pkozlowski-opensource
/packages/common/src/pipes/i18n_select_pipe.ts @ocombe @alxhub @AndrewKushnir @IgorMinar @jenniferfell @kara @mhevery @pkozlowski-opensource
/packages/common/src/pipes/number_pipe.ts      @ocombe @alxhub @AndrewKushnir @IgorMinar @jenniferfell @kara @mhevery @pkozlowski-opensource
/packages/compiler/src/i18n/**                 @AndrewKushnir @ocombe @mhevery @alxhub @IgorMinar @jenniferfell @kara @mhevery
/packages/compiler/src/render3/view/i18n/**    @AndrewKushnir @alxhub @IgorMinar @jenniferfell @kara @mhevery
/packages/compiler-cli/src/extract_i18n.ts     @AndrewKushnir @alxhub @IgorMinar @jenniferfell @kara @mhevery
tools/gulp-tasks/cldr/**                       @ocombe @alexeagle @IgorMinar
tools/gulp-tasks/cldr.js                       @ocombe @alexeagle @IgorMinar
```

2018-12-15 07:54 UTC, ocombe commented on .github/CODEOWNERS
> +/packages/bazel/**                                              @alexeagle @kyliau @IgorMinar @jenniferfell @kara @mhevery
you could add any `BUILD.bazel` file there too?

2018-12-17 07:08 UTC, IgorMinar commented on .github/CODEOWNERS
> +/packages/bazel/**                                              @alexeagle @kyliau @IgorMinar @jenniferfell @kara @mhevery
the build files should be reviewed and approved by component code owners. if they don't feel confident in approving the changes, they should pull in someone with the expertise. we should aim to get to the point where build files contain only easy to follow config which shouldn't require starlark language expertise (please note that .bzl files are guarded by a different group, because those can get tricky to write and review, and thus require special expertise).

2018-12-17 07:08 UTC, IgorMinar commented on .github/CODEOWNERS
> +#  General rules / phylosophy
🤦‍♂️

2018-12-17 07:09 UTC, IgorMinar commented on .github/CODEOWNERS
> +/packages/platform-browser/**                                   @alxhub @AndrewKushnir @IgorMinar @jenniferfell @kara @mhevery @pkozlowski-opensource
good catch!

2018-12-17 07:33 UTC, IgorMinar commented
@ocombe I added an i18n section. PTAL

2018-12-17 08:13 UTC, ocombe approved these changes

2018-12-17 16:56 UTC, alexeagle approved these changes
agreed this is better than what we have now. Thanks for doing the research!

2018-12-18 06:34 UTC, IgorMinar commented
@ocombe my understanding is that the following:

```
/packages/core/**  @alxhub @AndrewKushnir @IgorMinar @jenniferfell @kara @mhevery @pkozlowski-opensource
/packages/core/**/*.ts  @kara @pkozlowski-opensource 
```

means that only kara and pawel are owners - the last rule always wins.

2018-12-18 07:20 UTC, IgorMinar commented
ok.. having individual users is a no-go option because it results in a confusing pull request options. e.g. for a PR that crosses i18n, ivy and aio we end up with:

<img width="250" alt="screen shot 2018-12-17 at 11 19 21 pm" src="https://user-images.githubusercontent.com/216296/50138139-59486000-0252-11e9-852c-5f744ac2074f.png">

And from this list it's not clear which groups must approve the PR.

2018-12-18 08:01 UTC, IgorMinar commented
tomorrow I'll explore github teams and pullapprove v3

2018-12-22 08:47 UTC, IgorMinar commented
ok... I think I have a workable solution. Please take another look at the PR.

Some test PRs:

- https://github.com/angular/angular/pull/27812
- https://github.com/angular/angular/pull/27813
- https://github.com/angular/angular/pull/27815

Example review request for a PR crossing multiple file groups: 
<img width="232" alt="screen shot 2018-12-22 at 12 47 06 am" src="https://user-images.githubusercontent.com/216296/50372435-202a2b80-0583-11e9-8c21-8548a6a4dd67.png">

2018-12-22 09:08 UTC, IgorMinar commented
oh.. one more thing... I did my best to put the right people in the right groups. if I missed someone who's qualified to do codereviews in some areas, please let me know. it would be a miracle if there were no errors in that config.

2018-12-22 10:20 UTC, gkalpak commented on .github/CODEOWNERS
> +#  @angular/platform-webworker
What about `platform-webworker-dynamic`? :grin:

2018-12-22 23:48 UTC, gkalpak approved these changes
:tada:

There are also some `/packages/examples/**` that are not listed:
- /packages/examples/common
- /packages/examples/compiler
- /packages/examples/core
- /packages/examples/forms
- /packages/examples/http
- /packages/examples/platform-browser

2018-12-22 23:48 UTC, gkalpak commented on .github/CODEOWNERS
> +
Missing 3rd empty line 🙊

2018-12-23 17:29 UTC, ocombe approved these changes

2019-01-06 01:35 UTC, kara approved these changes
LGTM. Just found a few last typos.

2019-01-06 01:35 UTC, kara commented on .github/CODEOWNERS
> +#  - we enforce that only approved PRs get merged to ensure that unreviewed code doesn't get accidentaly merged
```suggestion
#  - we enforce that only approved PRs get merged to ensure that unreviewed code doesn't get accidentally merged
```

2019-01-06 01:35 UTC, kara commented on .github/CODEOWNERS
> +#  - Each codeowners team must have write access to the repo, otherwise their reviewes won't count.
```suggestion
#  - Each codeowners team must have write access to the repo, otherwise their reviews won't count.
```

2019-01-06 01:40 UTC, closed without merging