build: load angular.js minified output in upgrade tests
angular/angular pull request #27711
Opened 2018-12-17 17:28 UTC by devversion

We should try loading Angular.JS for the upgrade tests in their minfied output. 

There seems to be a lot flakiness in regards to loading `AngularJS` within Travis, and the `onerror` messages aren't really too helpful. In order to reduce the payload that will be passed through the Saucelabs tunnel, we should try to load the minfied output files.

2018-12-17 17:32 UTC, mary-poppins commented
You can preview b59c2c1 at https://pr27711-b59c2c1.ngbuilds.io/.

2018-12-17 19:19 UTC, gkalpak requested changes
As discussed "offline", this change will make it harder to debug failing tests locally, but is worth it if it will make the CI more stable.

Could you make it easier to switch to the none-minified version (for when we want to run and debug tests locally). E.g. serve both minified and non-minified files and have a flag in `test_helpers.ts` the determines which ones to use. (It will use the minified ones, but we would be able to switch to non-minified by flipping that flag.

2018-12-17 19:23 UTC, devversion commented
@gkalpak That sounds like a good idea. How would that work with the Bazel and Karma configuration? Should we just add the unminifed Angular versions to the karma config? (they won't be included anyway)

And for Bazel, we can just declare the unminfied Angular version also as `srcs`, but that feels like an anti-pattern. Any ideas? should we just leave out Bazel?

2018-12-17 19:38 UTC, gkalpak commented
I don't know much about bazel, but my thought was including both minified and non-minified (to both karma files and bazel). I don't think bazel will mind and those files will change very infrequently.

2018-12-17 20:44 UTC, mary-poppins commented
You can preview 1593da4 at https://pr27711-1593da4.ngbuilds.io/.

2018-12-17 20:46 UTC, devversion commented
@gkalpak Addressed your feedback.

2018-12-17 22:23 UTC, gkalpak approved these changes

2018-12-18 07:48 UTC, IgorMinar approved these changes
thanks

2018-12-18 17:30 UTC, closed without merging