Add API doc for DI decorators
angular/angular pull request #27731
Opened 2018-12-18 16:21 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2018-12-18 17:47 UTC, mary-poppins commented
You can preview 34d01b4 at https://pr27731-34d01b4.ngbuilds.io/.

2018-12-18 20:44 UTC, mary-poppins commented
You can preview 7426c50 at https://pr27731-7426c50.ngbuilds.io/.

2018-12-19 18:15 UTC, mary-poppins commented
You can preview 8aaa5c4 at https://pr27731-8aaa5c4.ngbuilds.io/.

2018-12-20 18:35 UTC, mary-poppins commented
You can preview ab26503 at https://pr27731-ab26503.ngbuilds.io/.

2018-12-21 16:42 UTC, mary-poppins commented
You can preview 922bfb3 at https://pr27731-922bfb3.ngbuilds.io/.

2018-12-26 18:13 UTC, mary-poppins commented
You can preview 39c7eb7 at https://pr27731-39c7eb7.ngbuilds.io/.

2018-12-27 21:30 UTC, mary-poppins commented
You can preview 67a6f7a at https://pr27731-67a6f7a.ngbuilds.io/.

2019-01-04 22:52 UTC, mary-poppins commented
You can preview 1864f50 at https://pr27731-1864f50.ngbuilds.io/.

2019-01-10 23:50 UTC, mary-poppins commented
You can preview 3cef6cb at https://pr27731-3cef6cb.ngbuilds.io/.

2019-01-11 21:40 UTC, mary-poppins commented
You can preview dca29fd at https://pr27731-dca29fd.ngbuilds.io/.

2019-01-14 17:05 UTC, mary-poppins commented
You can preview f5f7124 at https://pr27731-f5f7124.ngbuilds.io/.

2019-01-14 17:06 UTC, mary-poppins commented
You can preview 24aabcc at https://pr27731-24aabcc.ngbuilds.io/.

2019-01-15 16:18 UTC, brandonroberts requested changes

2019-01-15 16:18 UTC, brandonroberts commented on packages/core/src/di/injectable.ts
>     *
The `providedIn` option needs a description

2019-01-15 16:18 UTC, brandonroberts commented on packages/core/src/di/injectable.ts
>     * {@example core/di/ts/metadata_spec.ts region='Injectable'}
These examples should be updated to use `Injector` instead of `ReflectiveInjector`

2019-01-15 16:18 UTC, brandonroberts commented on packages/core/src/di/injectable.ts
> -   * ### Example
Usage notes example needs a header

2019-01-15 16:18 UTC, brandonroberts commented on packages/common/src/location/location_strategy.ts
> - * ### Example
Usage notes example needs a header

2019-01-15 16:18 UTC, brandonroberts commented on packages/core/src/di/metadata.ts
>     * {@example core/di/ts/metadata_spec.ts region='Inject'}
Examples here need updating to use `Injector`

2019-01-15 18:33 UTC, jbogarthyde commented on packages/core/src/di/injectable.ts
> -   * ### Example
No- in directives this tag is just a hack to allow headers in the long description. All directive doc is basically usage notes.

2019-01-15 18:33 UTC, jbogarthyde commented on packages/common/src/location/location_strategy.ts
> - * ### Example
no

2019-01-15 19:22 UTC, jbogarthyde commented on packages/core/src/di/injectable.ts
>     *
@petebacondarwin Where do we put the description for a directive option?

2019-01-15 19:23 UTC, jbogarthyde commented on packages/core/src/di/injectable.ts
>     * {@example core/di/ts/metadata_spec.ts region='Injectable'}
@brandonroberts Can you do this update, or show me how?

2019-01-15 19:33 UTC, jbogarthyde commented on packages/core/src/di/metadata.ts
>     * {@example core/di/ts/metadata_spec.ts region='Inject'}
@brandonroberts Can you do this update, or show me how?

2019-01-16 08:43 UTC, petebacondarwin commented on packages/core/src/di/injectable.ts
>     *
I would say you need to put it here: https://github.com/angular/angular/blob/0efbb3738127eb73369679353073eaec952f3dc0/packages/core/src/di/injectable.ts#L59

You can find this by clicking on the "view source" button in the docs at https://angular.io/api/core/Injectable

![screenshot 2019-01-16 at 08 43 11](https://user-images.githubusercontent.com/15655/51236746-d4448980-196a-11e9-8dca-4527091e8009.png)

2019-01-16 19:37 UTC, mary-poppins commented
You can preview 3c5b5a8 at https://pr27731-3c5b5a8.ngbuilds.io/.

2019-01-16 19:41 UTC, mary-poppins commented
You can preview 1382879 at https://pr27731-1382879.ngbuilds.io/.

2019-01-16 19:43 UTC, mary-poppins commented
You can preview 5837818 at https://pr27731-5837818.ngbuilds.io/.

2019-01-16 20:08 UTC, mary-poppins commented
You can preview a6aa0ef at https://pr27731-a6aa0ef.ngbuilds.io/.

2019-01-16 22:42 UTC, jbogarthyde commented
@brandonroberts @petebacondarwin This was passing tests before I tried to fix it. I would appreciate some help figuring out what I broke :-(

2019-01-17 16:47 UTC, mary-poppins commented
You can preview d20d1fc at https://pr27731-d20d1fc.ngbuilds.io/.

2019-01-17 17:05 UTC, mary-poppins commented
You can preview 019561d at https://pr27731-019561d.ngbuilds.io/.

2019-01-17 18:38 UTC, jbogarthyde commented
All green now - @brandonroberts, can this be approved?

2019-01-18 19:21 UTC, mary-poppins commented
You can preview 5c4a26a at https://pr27731-5c4a26a.ngbuilds.io/.

2019-01-21 13:04 UTC, brandonroberts approved these changes

2019-01-21 13:07 UTC, brandonroberts commented on packages/core/src/metadata/di.ts
> +   * ### Example as ES5 annotation
Remove ES5 annotation example.

2019-01-21 13:15 UTC, brandonroberts requested changes

2019-01-21 13:15 UTC, brandonroberts commented on packages/core/src/di/injectable.ts
> +  /**
This should be a note about configuring the injector, see options under https://angular.io/api/core/defineInjectable

2019-01-21 17:30 UTC, mary-poppins commented
You can preview 971df37 at https://pr27731-971df37.ngbuilds.io/.

2019-01-21 20:09 UTC, brandonroberts approved these changes

2019-01-21 20:09 UTC, brandonroberts commented
Changes LGTM. Will you take a second look @petebacondarwin?

2019-01-22 22:23 UTC, mary-poppins commented
You can preview 90a2579 at https://pr27731-90a2579.ngbuilds.io/.

2019-01-23 09:34 UTC, petebacondarwin commented on packages/core/src/di/injectable.ts
> +   * Determines which injectors will include the injectable,
NIT:  will include the injectable -> will provide the injectable ??

2019-01-23 09:53 UTC, petebacondarwin requested changes

2019-01-23 09:53 UTC, petebacondarwin commented on packages/core/src/di/injectable.ts
> +   * by either associating it with an @NgModule or other InjectorType,
InjectorType should be in backticks so that it is clickable.

2019-01-23 09:53 UTC, petebacondarwin commented on packages/core/src/di/metadata.ts
> +   * that marks the dependency as optional.
This sentence is a bit of a mouthful and hard to scan. How about something like:

> A parameter decorator to be used on constructor parameters,
> which mark the parameter as being an option dependency.

2019-01-23 09:53 UTC, petebacondarwin commented on packages/core/src/di/metadata.ts
> +   * A parameter decorator on a dependency parameter of a class constructor
Similarly to `OptionalDecorator` above this could be worded to read more easily.

2019-01-23 09:53 UTC, petebacondarwin commented on packages/core/src/di/metadata.ts
> +   * A parameter decorator on a dependency parameter of a class constructor
Ditto

2019-01-23 09:53 UTC, petebacondarwin commented on packages/core/src/metadata/di.ts
> + * that will populate the `entryComponents` fields of components and NgModules
typo: fields  -> field

2019-01-23 09:53 UTC, petebacondarwin commented on packages/core/src/metadata/di.ts
> + * Type of the Attribute decorator / constructor function.
should we put `Attribute` in backticks here?

2019-01-23 09:53 UTC, petebacondarwin commented on packages/core/src/metadata/di.ts
> +   * {@example core/ts/metadata/metadata.ts region='attributeFactory'}
I don't think this example adds any value here - it is basically identical to the previous one.
The only "real' difference is that one is on a `Directive` while the other is on a `Component`.

2019-01-23 09:53 UTC, petebacondarwin commented on packages/core/src/metadata/di.ts
> +   * The name of the attribute being decorated.
This is actually the "name of the attribute to be injected into the constructor".
The thing that is being decorated is the constructor parameter.

2019-01-23 16:52 UTC, jbogarthyde commented on packages/core/src/di/metadata.ts
> +   * that marks the dependency as optional.
Much better - thanks!

2019-01-23 17:05 UTC, mary-poppins commented
You can preview 1c57806 at https://pr27731-1c57806.ngbuilds.io/.

2019-01-23 17:27 UTC, jbogarthyde commented
@petebacondarwin Made your corrections - if this is it, please remove Changes Required status -- and perhaps mark for Merge?

2019-01-23 19:29 UTC, petebacondarwin approved these changes
One minor nit.

2019-01-23 19:40 UTC, mary-poppins commented
You can preview bdee3a8 at https://pr27731-bdee3a8.ngbuilds.io/.

2019-01-23 21:00 UTC, mary-poppins commented
You can preview 1c92ff0 at https://pr27731-1c92ff0.ngbuilds.io/.

2019-01-23 21:10 UTC, mary-poppins commented
You can preview 4b1717f at https://pr27731-4b1717f.ngbuilds.io/.

2019-01-24 17:03 UTC, mary-poppins commented
You can preview 23902f1 at https://pr27731-23902f1.ngbuilds.io/.

2019-01-25 17:42 UTC, mary-poppins commented
You can preview 36d0d8a at https://pr27731-36d0d8a.ngbuilds.io/.

2019-01-28 23:15 UTC, mary-poppins commented
You can preview b72859a at https://pr27731-b72859a.ngbuilds.io/.

2019-01-30 18:22 UTC, mary-poppins commented
You can preview a5f3e85 at https://pr27731-a5f3e85.ngbuilds.io/.

2019-01-31 17:25 UTC, mary-poppins commented
You can preview 07ffc6e at https://pr27731-07ffc6e.ngbuilds.io/.

2019-02-01 17:06 UTC, mary-poppins commented
You can preview 4365e3e at https://pr27731-4365e3e.ngbuilds.io/.

2019-02-04 17:11 UTC, mary-poppins commented
You can preview b29bcd2 at https://pr27731-b29bcd2.ngbuilds.io/.

2019-02-06 16:54 UTC, mary-poppins commented
You can preview 3f620a1 at https://pr27731-3f620a1.ngbuilds.io/.

2019-02-08 16:33 UTC, mary-poppins commented
You can preview 456dbf2 at https://pr27731-456dbf2.ngbuilds.io/.

2019-02-11 16:51 UTC, mary-poppins commented
You can preview b23016a at https://pr27731-b23016a.ngbuilds.io/.

2019-02-12 21:36 UTC, mary-poppins commented
You can preview c9e17d2 at https://pr27731-c9e17d2.ngbuilds.io/.

2019-02-13 17:01 UTC, mary-poppins commented
You can preview bcc321f at https://pr27731-bcc321f.ngbuilds.io/.

2019-02-13 20:01 UTC, closed without merging