fix(ivy): adding event listeners for global objects (window, document, body)
angular/angular pull request #27772
Opened 2018-12-20 07:40 UTC by AndrewKushnir

This update introduces support for global object (window, document, body) listeners, that can be defined via host listeners on Components and Directives.

PR resolves issue FW-743.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2018-12-20 07:44 UTC, mary-poppins commented
You can preview 92d0b2d at https://pr27772-92d0b2d.ngbuilds.io/.

2018-12-20 07:52 UTC, pkozlowski-opensource commented on packages/core/src/render3/util.ts
> +export function extractEventListenerDetails(eventName: string, element: RElement):
Would it be possible to have this splitting logic in the compiler instead and modify (or better yet - introduce a new) listener instruction? My concern is that this adds more code / processing on runtime. On top of this the code is not tree-shakable and will be pulled in even if there are no global events listened to in the application.

2018-12-20 09:41 UTC, pkozlowski-opensource requested changes
I would love to discuss the possibility of moving more logic to the compiler side and thus making the "global events" logic tree-shakable

2018-12-20 16:31 UTC, AndrewKushnir commented
Thanks for the feedback @pkozlowski-opensource! I will have a look at this today and let you know.

2018-12-20 22:10 UTC, mary-poppins commented
You can preview 991994d at https://pr27772-991994d.ngbuilds.io/.

2018-12-21 05:04 UTC, kara requested changes

2018-12-21 06:09 UTC, JoostK commented on packages/core/src/render3/interfaces/renderer.ts
> +export type GlobalTargetSelector = 'document' | 'window' | 'body';
I find the name to be confusing, as I interpret "selector" as CSS related which these strings are not. Would `GlobalTargetName` or `GlobalTargetIdentifier` be an option?

2018-12-21 06:09 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +    globalTargetGetter?: (element: any) => {
Could we name this `targetResolver` or something? To me, `globalTargetGetter` is odd.

2018-12-21 06:09 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +    const glob = globalTargetGetter ? globalTargetGetter(native) : {} as any;
`glob` usually means the file globbing tool :)

2018-12-21 06:09 UTC, JoostK commented on packages/core/src/render3/instructions.ts
> +      const cleanupFn = renderer.listen(glob.selector || target, eventName, listenerFn);
Why pass only the "selector" here? Wouldn't it be nice if the procedural renderer had access to the resolver fn as well as the name (because it seems the name is only necessary for `Renderer2` compat).

2018-12-21 09:58 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +    globalTargetGetter?: (element: any) => {
+1 maybe `eventTargetResolver`?

2018-12-21 10:00 UTC, pkozlowski-opensource commented on packages/core/src/render3/util.ts
> +    }
Yep, this would be my preferred approach as well

2018-12-21 18:46 UTC, mary-poppins commented
You can preview 3ac2eac at https://pr27772-3ac2eac.ngbuilds.io/.

2018-12-21 20:17 UTC, mary-poppins commented
You can preview a65120c at https://pr27772-a65120c.ngbuilds.io/.

2018-12-21 21:12 UTC, AndrewKushnir commented on packages/core/src/render3/instructions.ts
> +      const cleanupFn = renderer.listen(glob.selector || target, eventName, listenerFn);
Thanks for the comment @JoostK. I'll keep it as is to support Render2 contract. Changing existing behavior of Renderer2 is outside of the scope of this task.

2018-12-21 21:15 UTC, mary-poppins commented
You can preview c8c3ad8 at https://pr27772-c8c3ad8.ngbuilds.io/.

2018-12-21 21:16 UTC, AndrewKushnir commented
Thanks for the review everyone!

I've created 3 fixup commits (to address different parts of the feedback):

- removing duplicate logic in event params generation in compiler: https://github.com/angular/angular/pull/27772/commits/3ac2eac552f5ee70aa167708df23f2b9aba88f7d
- introduce specific function to resolve window/document/body: https://github.com/angular/angular/pull/27772/commits/a65120cf20678dd14e60646cb8dfed09a20ce1d6
- extract global target tests into separate functions: https://github.com/angular/angular/pull/27772/commits/c8c3ad8208bdb145de87f8e873f96031c32ec7c7

Please have a look again and let me know if you have any additional feedback/comments.

Thank you.

2018-12-21 21:19 UTC, pkozlowski-opensource approved these changes
This LGTM to now, thnx for making all those changes @AndrewKushnir !

2018-12-24 23:09 UTC, mary-poppins commented
You can preview 2c31ed7 at https://pr27772-2c31ed7.ngbuilds.io/.

2018-12-24 23:14 UTC, mary-poppins commented
You can preview b83ef5d at https://pr27772-b83ef5d.ngbuilds.io/.

2018-12-24 23:19 UTC, AndrewKushnir commented
Thanks for the review @pkozlowski-opensource!

FYI, I've added extra test (in [a separate fixup commit](https://github.com/angular/angular/pull/27772/commits/b83ef5d468f311c5e5d5e923f2ce9596675d5cbc)) to check whether we unsubscribe correctly, as Kara suggested. In order to cleanup (remove global listeners) once the test is done, I've introduced simple `destroy` method for `ComponentFixture` and `TemplateFixture` to invoke all LView cleanup machinery (we should probably call this method for each Fixture after each test?).

@kara could you please have a look at this commit: https://github.com/angular/angular/pull/27772/commits/b83ef5d468f311c5e5d5e923f2ce9596675d5cbc and let me know if you have any feedback?

P.S. I also rebased to the latest master to resolve conflicts.

Thank you.

2018-12-26 00:07 UTC, mary-poppins commented
You can preview dbc5885 at https://pr27772-dbc5885.ngbuilds.io/.

2018-12-26 00:13 UTC, mary-poppins commented
You can preview 66ce7d6 at https://pr27772-66ce7d6.ngbuilds.io/.

2018-12-26 17:56 UTC, trotyl commented on packages/core/src/render3/util.ts
> +  return {name: 'window', target: element.ownerDocument.defaultView};
Isn't it breaking custom `Renderer`? The API requirement on `Renderer`-site is only `RElement`:

https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/core/src/render3/interfaces/renderer.ts#L61

So that a conforming `Renderer` implementation could throw `cannot read property 'defaultView' of undefined` here, right?

2019-01-07 19:34 UTC, mary-poppins commented
You can preview 581fec4 at https://pr27772-581fec4.ngbuilds.io/.

2019-01-07 23:28 UTC, kara approved these changes
LGTM

2019-01-07 23:34 UTC, kara commented
[presubmit](http://test/OCL:228248486:BASE:228248674:1546904044109:ea86d3ac)

2019-01-08 18:34 UTC, closed without merging