fix(ivy): ngOnChanges only runs for binding updates
angular/angular pull request #27787
Opened 2018-12-21 03:58 UTC by benlesh

Updates ivy to trigger onChanges only when bindings update on not when properties are set.

- Currently there are still test failures in a few places, I'm not sure they are related as `core` is passing, if they are not, I'll mark them `fixMeIvy` and move on, because this PR is already pretty large
- SimpleChanges is now stored alongside the directive instance in LView. May changes had to be made to accommodate looking up directive and component instances from LView because of this.
- refactors hooks.ts slightly
- Adds handling for `onChanges` events to `hooks.ts` in `callHooks`.
- Fixes a bug where ngBaseDef creation was not honoring pre-existing ngComponentDef and ngDirectiveDef items
- Updates the Inherit Definition Feature to support inheriting onChanges
- Removes NgOnChangesFeature

**This isn't ready to merge yet**. Just looking for @kara and @mhevery's review.

2018-12-21 03:58 UTC, benlesh commented on packages/common/src/directives/ng_template_outlet.ts
> +        // this._viewRef = null;
I'll revert this.

2018-12-21 03:59 UTC, benlesh commented on packages/core/src/di/injector.ts
> +  debugger;
I'll revert this.

2018-12-21 04:00 UTC, benlesh commented on packages/core/src/render3/definition.ts
> +
Will revert.

2018-12-21 04:02 UTC, mary-poppins commented
You can preview fad83a8 at https://pr27787-fad83a8.ngbuilds.io/.

2018-12-21 04:02 UTC, benlesh commented on packages/core/src/render3/hooks.ts
> +const ON_CHANGES = -2;
Will add doc comment. 

NOTE: I chose -2 because the array this goes in stored numbers that were all indices, and -1 generally signals "not found in array". This is being used as a marker in the array, not an index. I could use something else, just figured this was lightweight.

2018-12-21 04:03 UTC, benlesh commented on packages/core/src/render3/hooks.ts
> +export function setupHooksDirectiveStart(
Renamed purely for clarity around what this was doing. `queueInitHooks` was confusing to me for a while when I started working on this.

2018-12-21 04:03 UTC, benlesh commented on packages/core/src/render3/hooks.ts
> +    (tView.checkHooks || (tView.checkHooks = [])).push(index, ON_CHANGES, onChanges);
Note the ON_CHANGES marker added to the array.

2018-12-21 04:04 UTC, benlesh commented on packages/core/src/render3/hooks.ts
> +    const isOnChanges = arr[i + 1] === ON_CHANGES;
Down here is where we're looking for the ON_CHANGES marker as it will cause us to pull out the SimpleChangse ref and adjust our "step" in the loop.

2018-12-21 04:05 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> +import {executeHooks as executeHooks, setupHooksDirectiveStart, setupHooksDirectiveEnd, executeInitHooks} from './hooks';
Will revert `executeHooks as executeHooks`, I think VS Code did that.

2018-12-21 04:06 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> +      const firstChange = !hasChanged.has(privateName);
The use of a `Set` here is debatable. Happy to use something else. But we can probably refine that in another PR.

2018-12-21 04:07 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> +    }
This is where we're storing the instance, the `SimpleChanges` (or null), and the `Set` of what we've already seen in the `LView`.

2018-12-21 04:08 UTC, benlesh commented on packages/core/test/linker/change_detection_integration_spec.ts
> +      debugger;
will revert

2018-12-21 04:08 UTC, benlesh commented on packages/core/test/linker/change_detection_integration_spec.ts
> +    debugger;
will revert

2018-12-21 04:08 UTC, benlesh commented on packages/core/test/render3/inherit_definition_feature_spec.ts
> +      @Input()
Will revert.

2018-12-21 04:09 UTC, benlesh commented on packages/core/test/render3/inherit_definition_feature_spec.ts
> +import {ComponentDef, DirectiveDef, InheritDefinitionFeature, ProvidersFeature, RenderFlags, allocHostVars, bind, defineBase, defineComponent, defineDirective, directiveInject, element, elementProper
Will revert.

2018-12-21 04:09 UTC, benlesh commented on packages/core/test/render3/inherit_definition_feature_spec.ts
> +import {Inject, InjectionToken, Input} from '../../src/core';
will revert

2018-12-21 04:09 UTC, benlesh commented on packages/core/test/render3/lifecycle_spec.ts
> +
will revert.

2018-12-21 04:10 UTC, benlesh commented on packages/core/test/render3/lifecycle_spec.ts
> +
will revert.

2018-12-21 04:10 UTC, benlesh commented on packages/core/test/render3/query_spec.ts
> +                tmp = load<QueryList<any>>(0);
will revert.

2018-12-21 04:11 UTC, benlesh commented on packages/core/test/render3/view_container_ref_spec.ts
> +
will revert.

2018-12-21 05:54 UTC, JoostK commented on packages/core/src/render3/hooks.ts
> +// TODO(benlesh): It seems like we could just replace this with some ternaries and
Yes, we can: #25295. That PR got lost and is quite outdated now, I can update it after this one lands if that's desirable.

2018-12-21 17:41 UTC, benlesh commented on packages/core/src/render3/hooks.ts
>      currentView: LView, allHooks: HookData | null, checkHooks: HookData | null,
Oh... good catch, I think that got trampled when I rebased.

2018-12-21 17:43 UTC, benlesh commented on packages/core/src/render3/hooks.ts
> +// TODO(benlesh): It seems like we could just replace this with some ternaries and
Now that this method is actually checking lView flags, I don't think we can. I'll remove the comment.

2019-01-03 02:21 UTC, mary-poppins commented
You can preview 3bc95f8 at https://pr27787-3bc95f8.ngbuilds.io/.

2019-01-03 16:53 UTC, mary-poppins commented
You can preview 27bd171 at https://pr27787-27bd171.ngbuilds.io/.

2019-01-03 16:55 UTC, mary-poppins commented
You can preview feb69e4 at https://pr27787-feb69e4.ngbuilds.io/.

2019-01-03 21:17 UTC, mhevery requested changes
I have created a fixup commit 2942cb3a69. Can we get this PR green, so that I can take another look?

2019-01-03 21:17 UTC, mhevery commented on packages/core/test/linker/change_detection_integration_spec.ts
> +             const ctx = createCompFixture('<div testDirective="dir" [a]="\'test\'" [b]="\'test\'"></div>');
Why did you have to change this test?

2019-01-03 21:17 UTC, mhevery commented on packages/core/test/render3/inherit_definition_feature_spec.ts
> +        elementProperty(0, 'someInput', bind('Weee'));
You added conditions to test, but you did not add any assertions. Either revert or add assertions.

2019-01-03 21:17 UTC, mhevery commented on packages/core/test/view/provider_spec.ts
> +        fixmeIvy('FW-875: The source of the error is missing in the `StaticInjectorError` message')
Why is code which used to pass now failing?

2019-01-03 21:21 UTC, mary-poppins commented
You can preview 2942cb3 at https://pr27787-2942cb3.ngbuilds.io/.

2019-01-03 21:58 UTC, mary-poppins commented
You can preview b69a64a at https://pr27787-b69a64a.ngbuilds.io/.

2019-01-03 22:12 UTC, mary-poppins commented
You can preview 41cfe45 at https://pr27787-41cfe45.ngbuilds.io/.

2019-01-03 22:12 UTC, benlesh commented on packages/core/test/view/provider_spec.ts
> +        fixmeIvy('FW-875: The source of the error is missing in the `StaticInjectorError` message')
Possibly some poorly resolved merge conflict. It doesn't seem to be related to any code touched for onChanges. I think @ocombe might be able to provide insight here, as I'm pretty sure he's the one who I saw fix this issue.

2019-01-03 23:57 UTC, mary-poppins commented
You can preview a514402 at https://pr27787-a514402.ngbuilds.io/.

2019-01-04 00:08 UTC, mary-poppins commented
You can preview 774da4c at https://pr27787-774da4c.ngbuilds.io/.

2019-01-04 00:09 UTC, mary-poppins commented
You can preview 2d2fdd2 at https://pr27787-2d2fdd2.ngbuilds.io/.

2019-01-04 01:50 UTC, mary-poppins commented
You can preview 1efffdd at https://pr27787-1efffdd.ngbuilds.io/.

2019-01-04 02:11 UTC, mary-poppins commented
You can preview cf67e48 at https://pr27787-cf67e48.ngbuilds.io/.

2019-01-04 02:13 UTC, benlesh commented on packages/core/test/render3/inherit_definition_feature_spec.ts
> +        elementProperty(0, 'someInput', bind('Weee'));
The assertion is below. This test used to rely on the fact we were patching the setters, but now binding is required to trigger onChanges.

2019-01-04 02:20 UTC, benlesh commented on packages/core/test/linker/change_detection_integration_spec.ts
> +             const ctx = createCompFixture('<div testDirective="dir" [a]="\'test\'" [b]="\'test\'"></div>');
Ah.. this was changed before I realized I needed up update SimpleChanges in setInputsFromAttrs

Reverted.

2019-01-04 02:21 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> +    for (let i = 0; i < initialInputs.length; i += 3) {
You've changed this in your commit.

2019-01-04 02:40 UTC, mary-poppins commented
You can preview dcb214c at https://pr27787-dcb214c.ngbuilds.io/.

2019-01-04 03:00 UTC, mary-poppins commented
You can preview d312aa3 at https://pr27787-d312aa3.ngbuilds.io/.

2019-01-04 08:03 UTC, ocombe commented on packages/core/test/view/provider_spec.ts
> +        fixmeIvy('FW-875: The source of the error is missing in the `StaticInjectorError` message')
I think it's @pkozlowski-opensource that fixed this one

2019-01-04 22:03 UTC, mary-poppins commented
You can preview 483b598 at https://pr27787-483b598.ngbuilds.io/.

2019-01-04 22:51 UTC, mary-poppins commented
You can preview 53c312f at https://pr27787-53c312f.ngbuilds.io/.

2019-01-04 23:47 UTC, mary-poppins commented
You can preview 511ece6 at https://pr27787-511ece6.ngbuilds.io/.

2019-01-05 01:21 UTC, mary-poppins commented
You can preview 32bbadc at https://pr27787-32bbadc.ngbuilds.io/.

2019-01-07 16:09 UTC, kara commented
@benlesh This PR seems to have pulled in a number of unrelated commits from master (like forms changes and animations changes, etc). It's not really reviewable in this state. Can you fix the Github history so it only contains your own commits?

2019-01-07 16:42 UTC, benlesh commented
@kara looks like a bad rebase. Not sure how that happened, I might just have to start a new branch and cherry-pick my changes over, which would mean a different PR. I'll see what I can do.

2019-01-07 17:28 UTC, closed without merging