fix(ivy): restore NG defs after running tests in TestBed
angular/angular pull request #27786
Opened 2018-12-21 01:55 UTC by AndrewKushnir

`R3TestBed` allows consumers to configure a "testing module", declare components, override various metadata, etc. To do this, it implements its own JIT compilation, where components/directives/modules have Ivy definition fields generated based on testing metadata. It results in tests interfering with each other. One test might override something in a component that another test tries to use normally, causing failures.

In order to resolve this problem, we store current components/directives/modules defs before applying overrides and re-compiling. Once the test is complete, we restore initial defs, so the next tests interact with "clean" components.

**NOTE: this PR is based on another one (PR #27693), so please have a look at this commit only:** https://github.com/angular/angular/commit/6a30d7103ea1840ba7a0e109f1618e6d1ec01d50 .

This PR resolves FW-872.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2018-12-21 01:59 UTC, mary-poppins commented
You can preview 6a30d71 at https://pr27786-6a30d71.ngbuilds.io/.

2018-12-21 09:06 UTC, ocombe requested changes
Looks good, but you need to add a test that checks that we do restore NG defs correctly

2018-12-21 10:51 UTC, trotyl commented on packages/core/testing/src/r3_test_bed.ts
> +        {provide: token, useFactory: provider.useFactory, deps: provider.deps || []} :
```suggestion
        {provide: token, useFactory: provider.useFactory, deps: provider.deps || EMPTY_ARRAY} :
```

I guess `deps` is immutable?

2018-12-21 10:51 UTC, trotyl commented on packages/core/testing/src/r3_test_bed.ts
> +      throw new Error(`${stringify(moduleType)} has not @NgModule annotation`);
```suggestion
      throw new Error(`${stringify(moduleType)} has no @NgModule annotation`);
```

2018-12-21 10:51 UTC, trotyl commented on packages/core/testing/src/r3_test_bed.ts
> +        throw new Error(`Importing ${imported.name} which does not have an @ngModule`);
```suggestion
        throw new Error(`Importing ${imported.name} which does not have an @NgModule`);
```

2018-12-21 10:51 UTC, trotyl commented on packages/core/testing/src/r3_test_bed.ts
> +      const exportedTyped = exported as Type<E>& {
`exportedTyped` -> `exportedType`?

2018-12-21 10:51 UTC, trotyl commented on packages/core/testing/src/r3_test_bed.ts
> +      // ngComponentDef as it might be compiled asynchronously).
Technically it do has an `ngComponentDef`, but throws when triggering the getter. So that existence testing like `NG_COMPONENT_DEF in type` should still work.

2018-12-21 10:51 UTC, trotyl commented on packages/core/testing/src/r3_test_bed.ts
> +      } else if (exportedTyped.ngPipeDef !== undefined) {
I'm a little concerned about this kind of property testing with inheritance, given:

```typescript
@Pipe({ ... })
class Base {}

@Directive({ ... })
class Derived extends Base {}
```

Would `Derived` be considered a pipe?

2018-12-25 22:04 UTC, mary-poppins commented
You can preview b81aff1 at https://pr27786-b81aff1.ngbuilds.io/.

2018-12-26 18:46 UTC, mary-poppins commented
You can preview 2c0f48f at https://pr27786-2c0f48f.ngbuilds.io/.

2018-12-26 18:46 UTC, AndrewKushnir commented
@ocombe thanks for the review. I've added a test to verify that we reset metadata (pipes and directives) after executing `TestBed.resetTestingModule`. It looks like component's `directiveDefs` also contains a reference to itself, that we add during `transitiveScopesFor` function execution (i.e. it's not a regression in this PR). I will take a note on that and double check whether this behavior is correct outside of the scope of this PR.

2018-12-26 18:55 UTC, AndrewKushnir commented
@trotyl thanks for the comments. The thing is that this PR was created on top of another one (PR #27693), but now it's rebased off the latest master, so the changes you refer to are not included here (they were made in another PR). The `transitiveScopesFor` function was moved from one place to another (without any changes) in the previous PR (#27693) and the logic in that function is similar to what we have in `packages/core/src/render3/jit/module.ts`, so I took a note on your feedback and we'll take it into account while refactoring this function in future PRs. Thank you.

2019-01-07 17:08 UTC, ocombe approved these changes

2019-01-07 19:21 UTC, mhevery approved these changes

2019-01-07 19:24 UTC, kara commented
[presubmit](http://test/OCL:228201524:BASE:228201683:1546889074550:14736f8c)

2019-01-07 22:45 UTC, closed without merging