refactor(router): subscribe router events until destroyed
angular/angular pull request #27842
Opened 2018-12-27 07:53 UTC by JLHwung

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

The `RouterPreloader` now does not relies on external `setUpPreloading` calls.

2018-12-27 09:31 UTC, alfaproject commented on packages/router/src/router_preloader.ts
> +        .pipe(takeUntil(this.destroyed))
Why 2 `pipe`?

2018-12-27 09:31 UTC, alfaproject commented
Should be easy to make a unit test for this and I think it's required to be able to be merged at some point

2018-12-27 10:20 UTC, JLHwung commented on packages/router/src/router_preloader.ts
> +        .pipe(takeUntil(this.destroyed))
Ah, I could have used only one pipe. Fixed.

2018-12-29 08:17 UTC, alfaproject commented
#1 is what you fixed right? That's probably good enough

2019-01-08 23:46 UTC, benlesh requested changes
Using a Subject here adds a bit of unnecessary overhead. It's a fine approach when you have more than one way to terminate a subscription, or you're managing a lot of subscriptions.

In this case, I think we'd be fine just checking to see if `this.subscription` exists, and calling `this.subscription.unsubscribe()` accordingly. That's the least overhead and the fewest allocations.

(Unrelated: The call to `complete` on the destroyed Subject is superfluous in this case)

2019-01-09 08:18 UTC, JLHwung commented
@benlesh Revised with simpler empty check for `this.subscription`.

2020-08-06 21:08 UTC, atscott commented
Looks like this was addressed in https://github.com/angular/angular/commit/763023472b15f82a7551c9c4f8f43cda1d259dd5. Sorry about this change getting lost!

2020-08-06 21:08 UTC, closed without merging