docs: fix broken html for deployment.md
angular/angular pull request #27851
Opened 2018-12-27 22:49 UTC by JohannesHoppe

minor fix in the markdown. without the closing quote the text and link are not displayed correctly

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

Content on angular.io is not shown. First part of the text is invisible and the link is not clickable.

## What is the new behavior?

Content on angular.io is shown.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2018-12-28 13:53 UTC, mary-poppins commented
You can preview b899f55 at https://pr27851-b899f55.ngbuilds.io/.

2018-12-28 13:55 UTC, brandonroberts requested changes

2018-12-28 13:55 UTC, brandonroberts commented on aio/content/guide/deployment.md
> +<div class="alert is-helpful1">
This should be `is-helpful`

2018-12-28 13:55 UTC, brandonroberts commented on aio/content/guide/deployment.md
> +<div class="alert is-helpful1">
`is-helpful1` -> `is-helpful`

2018-12-29 19:34 UTC, JohannesHoppe commented on aio/content/guide/deployment.md
> +<div class="alert is-helpful1">
sorry, fat fingers! 😄

2018-12-29 19:38 UTC, mary-poppins commented
You can preview 3df2ca8 at https://pr27851-3df2ca8.ngbuilds.io/.

2019-01-04 15:43 UTC, brandonroberts approved these changes

2019-01-04 15:50 UTC, mary-poppins commented
You can preview a76cfd9 at https://pr27851-a76cfd9.ngbuilds.io/.

2019-01-11 00:05 UTC, IgorMinar approved these changes
Thanks

2019-01-11 00:05 UTC, IgorMinar commented
Caretaker note: legacy pullapprove flake - please ignore.

2019-01-11 01:05 UTC, closed without merging