fix(bazel): Add /bazel-out to .gitignore
angular/angular pull request #27874
Opened 2018-12-31 03:33 UTC by lacolaco

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #27873 

## What is the new behavior?

Add `/bazel-out` line to `.gitignore` file created by `ng-new`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-01-09 00:22 UTC, kyliau requested changes

2019-01-09 00:22 UTC, kyliau commented on packages/bazel/src/schematics/ng-new/index.ts
> +      throw new Error(`Could not find ${gitignore}`);
Should just return here instead of throwing error, because `ng new` could potentially be invoked with `--skip-git`, in which case the `.gitignore` file will not be created.

2019-01-09 02:26 UTC, kyliau approved these changes
Thank you!

2019-01-09 06:48 UTC, IgorMinar commented
@lacolaco can you please squash this into a single commit (or use --fixup commits instead of additional `fix: ` commits?) - we want the history of the master branch to be clean without superfluous
 commits.

@kyliau please ensure you keep on monitoring this PR for the requested update and once everything is good to go, please label the PR for merge - only team members can change labels, so it is your responsibility as the reviewer/approver to hand this PR off to the caretaker once it's ready. thanks!

2019-01-10 19:17 UTC, kyliau commented on packages/bazel/src/schematics/ng-new/index.ts
> +    const compileOutput = lines.findIndex((line: string) => line === '# compiled output');
I think this is fine since we have a test to make sure `/bazel-out` is written to `.gitignore`. When the test fails we will know that the format has changed, and we can then update the code accordingly.

2019-01-10 21:41 UTC, closed without merging