docs(core): adds detailed information to directive metadata
angular/angular pull request #27962
Opened 2019-01-07 16:34 UTC by ErickXavier

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Adds more detailed information about the templateUrl and styleUrls metadatas.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Doest talk anything about the field being possible to be relative paths and/or absolute urls.

Issue Number: N/A

## What is the new behavior?
Now it describes the fasct that the paths can be relative and the urls can be absolute.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-01-07 18:25 UTC, jenbuzz requested changes

2019-01-10 16:34 UTC, ErickXavier commented on packages/core/src/metadata/directives.ts
> +   * do not supply ainline template using `template`.
Fixed. Thanks for the warning.

2019-01-10 23:31 UTC, mhevery commented on packages/core/src/metadata/directives.ts
> +   * If provided, do not supply ai nline template using `template`.
`ai nline` is a typo, maybe `an inline`?

2019-01-14 19:15 UTC, mary-poppins commented
You can preview 88a09f9 at https://pr27962-88a09f9.ngbuilds.io/.
You can preview 130a108 at https://pr27962-130a108.ngbuilds.io/.

2019-01-14 22:32 UTC, jbogarthyde commented on packages/core/src/metadata/directives.ts
> +   * If provided, do not supply ai nline template using `template`.
"an inline"

2019-01-14 22:33 UTC, jbogarthyde requested changes
Please correct typo and non-compliant commit message. 
Otherwise fine.

2019-01-24 18:13 UTC, jbogarthyde approved these changes

2019-01-24 18:45 UTC, jenbuzz approved these changes

2019-01-29 15:06 UTC, brandonroberts approved these changes

2019-01-29 15:06 UTC, brandonroberts commented
Caretaker note: This is a docs only change and should not impact g3. Please run presubmit.

2019-01-30 00:32 UTC, closed without merging