fix(ivy): ngOnChanges only runs for binding updates
angular/angular pull request #27965
Opened 2019-01-07 17:26 UTC by benlesh

Updates ivy to trigger onChanges only when bindings update on not when properties are set.

- Currently there are still test failures in a few places, I'm not sure they are related as `core` is passing, if they are not, I'll mark them `fixMeIvy` and move on, because this PR is already pretty large
- SimpleChanges is now stored alongside the directive instance in LView. May changes had to be made to accommodate looking up directive and component instances from LView because of this.
- refactors hooks.ts slightly
- Adds handling for `onChanges` events to `hooks.ts` in `callHooks`.
- Fixes a bug where ngBaseDef creation was not honoring pre-existing ngComponentDef and ngDirectiveDef items
- Updates the Inherit Definition Feature to support inheriting onChanges
- Removes NgOnChangesFeature

### Addendum

- Also solves an issue where `ts_web_test_suite` rule was sometimes adding `init_browser_spec.js` out of order, causing Karma tests to fail when examining uninitialized `isNode` variable in global scope.
- Had to increase the payload limit of hello-world to `187437` from `185238`

2019-01-07 17:31 UTC, mary-poppins commented
You can preview 51d5a13 at https://pr27965-51d5a13.ngbuilds.io/.

2019-01-07 23:04 UTC, jelbourn reviewed
* Can you copy the description from the original PR instead of just referencing it?
* I know I've left some comments that touch on things that were already there, but look to be worth touching up
* This PR looks like it would have been a good candidate for breaking up into smaller PRs. E.g., moving `SimpleChange` could have happened by itself for a really trivial PR

I'm halfway through, I'll send my comments on the second half shortly

2019-01-07 23:04 UTC, jelbourn commented on packages/core/src/render3/hooks.ts
> +    const isOnChangesHook = index < 0;
I would repeat the context here that a negative index signals that this is specifically an `OnChanges` hook so that it can be passed the `SimpleChanges`

2019-01-07 23:04 UTC, jelbourn commented on packages/core/src/render3/hooks.ts
> +    const record = currentView[isOnChangesHook ? -index : index];
Could this name be more specific than `record`?

2019-01-07 23:45 UTC, mhevery approved these changes

2019-01-07 23:48 UTC, mary-poppins commented
You can preview 9031fd9 at https://pr27965-9031fd9.ngbuilds.io/.

2019-01-07 23:52 UTC, benlesh commented on packages/core/src/change_detection/simple_change.ts
> + * Represents a basic change from a previous to a new value.
Added more details.

2019-01-08 00:11 UTC, benlesh commented on packages/core/src/metadata/directives.ts
> +    let def: any =
It's not always `ngBaseDef`, sometimes it's `ngComponentDef`, sometimes it's `ngDirectiveDef`. I've added better doc comments to clarify.

2019-01-08 00:12 UTC, benlesh commented on packages/core/src/metadata/directives.ts
> +    if (!(name in defProp)) {
Done.

2019-01-08 00:12 UTC, benlesh commented on packages/core/src/render3/di_get_node_injectable.ts
> +let includeViewProviders = false;
File was a duplicate.

2019-01-08 00:13 UTC, benlesh commented on packages/core/src/render3/di_get_node_injectable.ts
> +function setIncludeViewProviders(v: boolean): boolean {
This was copied over while I was trying to resolve circular dependency issues, and then accidentally included in a commit. The file was deleted.

2019-01-08 00:13 UTC, benlesh commented on packages/core/src/render3/di_get_node_injectable.ts
> + * resolution.
This was copied over while I was trying to resolve circular dependency issues, and then accidentally included in a commit. The file was deleted.

2019-01-08 00:14 UTC, benlesh commented on packages/core/src/render3/di_get_node_injectable.ts
> + *     {provide: String, value: 'providers' }
This was copied over while I was trying to resolve circular dependency issues, and then accidentally included in a commit. The file was deleted.

2019-01-08 00:17 UTC, benlesh commented on packages/core/src/render3/di_get_node_injectable.ts
> +    try {
It's sorta funny that so many of your comments are on code I literally copied and pasted from `di.ts` to elevate a circular refrence issue, then accidentally included in my commit after I went another route. :laughing: 

I'm going to go through them and update `di.ts` as needed, even though it was mostly untouched.

2019-01-08 00:30 UTC, benlesh commented on packages/core/src/render3/hooks.ts
> +    const record = currentView[isOnChangesHook ? -index : index];
Done

2019-01-08 00:31 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> +      for (let i = 0; i < propsLength;) {
This code was added by @mhevery during another review. Leaving it for now.

2019-01-08 00:34 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> +        const directiveIndex = props[i++] as number;
The code below this and the documentation of `PropertyAliasValue` do a good job here. I don't think I'd want to repeat in a comment what is already apparent from the code.

2019-01-08 00:35 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> +    const record = lView[directiveIndex];
done.

2019-01-08 00:37 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> +    const instance = hasOnChanges ? unwrapOnChangesDirectiveWrapper(record) : record;
Done.

2019-01-08 00:39 UTC, benlesh commented on packages/core/src/render3/interfaces/view.ts
> +export type HookData = (number | (() => void) | ((changes: SimpleChanges) => void))[];
Noted. Perhaps `LifecycleHookRegistry` or something? It's really to store pairs of indices and hook functions.

2019-01-08 00:41 UTC, benlesh commented on packages/core/src/render3/onchanges_util.ts
> +export function isExactInstanceOf(obj: any, type: any): boolean {
Good idea.

2019-01-08 00:45 UTC, mary-poppins commented
You can preview af64c06 at https://pr27965-af64c06.ngbuilds.io/.

2019-01-08 01:35 UTC, jelbourn commented on packages/core/src/render3/onchanges_util.ts
> +export function isExactInstanceOf<T>(obj: any, type: T): obj is T {
This isn't exactly right; this is saying that `type` is an _instance_ of `T`, when you want to express that `type` is a _constructor_ for `T`. You'd want to pretty much do what I showed in that typescript playground example. The missing `prototype` property is actually a clue that something is amiss; changing it to a constructor makes it so that TypeScript knows that property is there.

2019-01-08 02:35 UTC, kara requested changes
Yay, this is getting close! Mostly small things below.

2019-01-08 02:35 UTC, kara commented on packages/core/src/render3/di.ts
> +  return unwrapOnChangesDirectiveWrapper(value);
Here we are always unwrapping the value, but I think we can predict that if a value is a factory, it hasn't yet been wrapped with `onChanges`. Let's move the unwrapping to the else block so we can skip it on first pass?

2019-01-08 02:35 UTC, kara commented on packages/core/src/render3/instructions.ts
> +        recordChange(record, declaredName, attrValue);
This loop looks really similar to the loop in `setInputsForProperty`. Any way we can share the code?

2019-01-08 02:35 UTC, kara commented on packages/core/test/render3/ng_on_changes_feature_spec.ts
> -  it('should patch class', () => {
I don't think we should delete these tests wholesale. I see that they use the old-style API (e.g. expecting prop change to trigger onChanges), but this is also the only place where we seem to have r3 unit tests for `SimpleChange.firstChange`, etc, so I think those parts are important to keep. Can you update these tests (and maybe rename this file)?

2019-01-08 02:35 UTC, kara commented on packages/core/test/render3/lifecycle_spec.ts
I think we need a test in this spec that asserts that changing the property outside of the template does *not* call onChanges, so we don't accidentally re-introduce this bug.

2019-01-08 17:34 UTC, benlesh commented on packages/core/src/render3/onchanges_util.ts
> +export function isExactInstanceOf<T>(obj: any, type: T): obj is T {
Good suggestion. I missed that in your example.

2019-01-08 17:41 UTC, benlesh commented on packages/core/src/render3/hooks.ts
> +export function setupHooksDirectiveEnd(tView: TView, tNode: TNode): void {
Okay... I think `queue` is a misnomer here, since we never dequeue anything. I'll try to think of something.

2019-01-08 17:48 UTC, benlesh commented on packages/core/src/render3/load_internal.ts
> +export function loadInternal<T>(view: LView | TData, index: number): T {
I'll leave the one in `util` because that's the one that existed and is currently being used.

The other was _accidentally_ included when I did a `git add` and forgot it was in my file system while trying to solve some circular dependency issues.

2019-01-08 17:48 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> +    if (def.onChanges) {
Done.

2019-01-08 17:53 UTC, jelbourn commented
FYI if you respond to changes in the "Files changed" tab, it will let you batch all of the responses into one email rather than sending one email per comment. 

We also have a practice on the components repo to use a thumbs-up reaction on a comment to mean "Done" without sending an email.

2019-01-08 17:55 UTC, benlesh commented on packages/core/src/render3/di.ts
> +  return unwrapOnChangesDirectiveWrapper(value);
Makes sense.

2019-01-08 18:11 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> +        recordChange(record, declaredName, attrValue);
Done.

2019-01-08 18:18 UTC, mary-poppins commented
You can preview 09678ec at https://pr27965-09678ec.ngbuilds.io/.

2019-01-08 18:19 UTC, benlesh commented on packages/core/src/metadata/directives.ts
> +    getOrCreateDefinitionAndUpdateMappingFor(baseDef => baseDef.outputs || {}));
Done.

2019-01-08 18:20 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> + * @param inputAliases mapping between the public name and and private properties to write to.
Fixed.

2019-01-08 18:21 UTC, benlesh commented on packages/core/src/render3/onchanges_util.ts
> + * Updates the `simpleChanges` property on the `wrapper` instance, such that when it's
Fixed in a different commit. Thanks.

2019-01-08 18:33 UTC, mary-poppins commented
You can preview 43096f5 at https://pr27965-43096f5.ngbuilds.io/.

2019-01-08 18:43 UTC, mary-poppins commented
You can preview ecc8bf5 at https://pr27965-ecc8bf5.ngbuilds.io/.

2019-01-08 21:00 UTC, kara commented on packages/core/src/render3/hooks.ts
> +export function setupHooksDirectiveEnd(tView: TView, tNode: TNode): void {
Hmm, yeah, I could see that. Threw around a few names with @jelbourn and we came up with  `registerPreOrderLifecycleHooks` and `registerPostOrderLifecycleHooks`. WDYT?

2019-01-09 00:55 UTC, mary-poppins commented
You can preview 389d01e at https://pr27965-389d01e.ngbuilds.io/.

2019-01-09 19:22 UTC, jelbourn commented on packages/core/src/render3/onchanges_util.ts
> +      Object.getPrototypeOf(obj) == (type as any).prototype;
You shouldn't need the `as any` here any more

2019-01-10 00:13 UTC, benlesh commented on packages/core/src/render3/hooks.ts
> +export function setupHooksDirectiveEnd(tView: TView, tNode: TNode): void {
Especially since I've written a few dozen event dispatchers that actually did queue and dequeue events, I found this really confusing.

2019-01-11 00:44 UTC, mary-poppins commented
You can preview 0021fbb at https://pr27965-0021fbb.ngbuilds.io/.

2019-01-11 00:59 UTC, mary-poppins commented
You can preview e037edf at https://pr27965-e037edf.ngbuilds.io/.

2019-01-11 16:16 UTC, mary-poppins commented
You can preview 5cc6f96 at https://pr27965-5cc6f96.ngbuilds.io/.

2019-01-11 17:43 UTC, benlesh commented
http://test/OCL:228895685:BASE:228895808:1547228501322:e6ec4c5b

2019-01-11 18:11 UTC, mhevery approved these changes

2019-01-11 18:31 UTC, kara requested changes
A few items still TODO from the first review:
- Look into why new tests are failing (https://github.com/angular/angular/pull/27965#discussion_r245855954)
- Remove extra `loadInternal` implementation (https://github.com/angular/angular/pull/27965#discussion_r245857410)
- Add dedicated test for property changes (https://github.com/angular/angular/pull/27965#discussion_r245861617)

2019-01-11 18:31 UTC, kara commented on packages/core/test/render3/lifecycle_spec.ts
> +        elementProperty(0, 'publicVal2', bind(ctx.b));
Looks like this no longer matches the comment?

2019-01-11 19:33 UTC, mary-poppins commented
You can preview a01cd31 at https://pr27965-a01cd31.ngbuilds.io/.

2019-01-11 19:36 UTC, benlesh commented on packages/core/src/render3/load_internal.ts
> +export function loadInternal<T>(view: LView | TData, index: number): T {
done

2019-01-11 19:41 UTC, mary-poppins commented
You can preview 3db0d71 at https://pr27965-3db0d71.ngbuilds.io/.

2019-01-11 20:37 UTC, mary-poppins commented
You can preview 2ea9535 at https://pr27965-2ea9535.ngbuilds.io/.

2019-01-11 21:12 UTC, kara approved these changes
LGTM

2019-01-11 21:31 UTC, mary-poppins commented
You can preview c9e614e at https://pr27965-c9e614e.ngbuilds.io/.

2019-01-11 22:30 UTC, closed without merging