fix(ivy): support multiple exportAs
angular/angular pull request #27996
Opened 2019-01-08 20:26 UTC by crisbeto

Allows for multiple, comma-separated `exportAs` names, similarly to `ViewEngine`.

These changes fix FW-708.

2019-01-08 20:30 UTC, mary-poppins commented
You can preview 7b89b3e at https://pr27996-7b89b3e.ngbuilds.io/.

2019-01-08 20:44 UTC, mary-poppins commented
You can preview d97ab1f at https://pr27996-d97ab1f.ngbuilds.io/.

2019-01-08 20:50 UTC, mary-poppins commented
You can preview f828c7f at https://pr27996-f828c7f.ngbuilds.io/.

2019-01-08 20:58 UTC, mary-poppins commented
You can preview 90d6a83 at https://pr27996-90d6a83.ngbuilds.io/.

2019-01-08 21:43 UTC, alxhub requested changes

2019-01-08 21:43 UTC, alxhub commented on packages/compiler/src/render3/view/compiler.ts
> +    const exportAsValues = meta.exportAs.split(',').map(part => o.literal(part.trim()));
`meta.exportAs` should already be split here. We should do that processing for AOT in [ngtsc/annotations/src/directive.ts](https://github.com/angular/angular/blob/a0840242d7cf695a4bc41d39a6f937a72e6bd722/packages/compiler-cli/src/ngtsc/annotations/src/directive.ts#L178) and for JIT in [render3/jit/directive.ts](https://github.com/angular/angular/blob/a0840242d7cf695a4bc41d39a6f937a72e6bd722/packages/core/src/render3/jit/directive.ts#L153).

For the compiler, it's actually a little more complicated as `exportAs` is one of the metadata elements written to `.d.ts` files, so that needs to change as well. Additionally there's the template type-checking code which matches against this...

Let me make you a precursor PR for the compiler which adds this support that you can build on.

2019-01-10 20:53 UTC, mary-poppins commented
You can preview d021ced at https://pr27996-d021ced.ngbuilds.io/.

2019-01-10 21:22 UTC, alxhub approved these changes

2019-01-10 21:34 UTC, kara commented
[presubmit](http://test/OCL:228767245:BASE:228767272:1547156050182:60833465)

2019-01-10 22:04 UTC, alxhub commented
> core/todo/bundle increased by 41 bytes.

Unacceptable!! ;)

2019-01-11 00:54 UTC, closed without merging