fix(ivy): directives without selector should not be supported
angular/angular pull request #28021
Opened 2019-01-09 17:00 UTC by marclaval

This PR fixes the remaining part of FW-662 about directives without selector or with an empty selector.

2019-01-09 17:05 UTC, mary-poppins commented
You can preview 04f4059 at https://pr28021-04f4059.ngbuilds.io/.

2019-01-09 17:50 UTC, mhevery approved these changes

2019-01-09 19:27 UTC, kara requested changes
Thanks for the quick turnaround on this! One nit and we should be good to go

2019-01-10 02:15 UTC, trotyl commented
Why does this restriction still needed as there will be an imperative `createDirective()` function?

2019-01-10 09:40 UTC, marclaval commented on packages/compiler-cli/test/compliance/r3_compiler_compliance_spec.ts
> +      expect(() => compile(files, angularFiles)).toThrow();
Done

2019-01-10 09:41 UTC, mary-poppins commented
You can preview 45d4eed at https://pr28021-45d4eed.ngbuilds.io/.

2019-01-10 15:02 UTC, kara commented
@trotyl We can revisit if/when `createDirective` API appears. For now, we're keeping the behavior consistent with View Engine.

2019-01-10 15:02 UTC, kara approved these changes
LGTM

2019-01-10 15:05 UTC, kara commented
[presubmit](https://test.corp.google.com/ui#id=OCL:228704095:BASE:228704128:1547132667026:9f965029)

2019-01-10 18:52 UTC, closed without merging