WIP feat(docs-infra): saves the scroll position before the change of loca…
angular/angular pull request #28037
Opened 2019-01-10 07:30 UTC by wKoza

…tion

closes #27916

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [X] Yes
- [ ] No

## Other information

2019-01-10 15:45 UTC, wKoza commented
Hi @petebacondarwin , 
What do you think about this kind of implementation / behavior ? I'm agree with @IgorMinar, use history API is more usual but It's currently more tricky because of the current mechanical of displaying.

2019-01-10 15:54 UTC, mary-poppins commented
You can preview 4ecf896 at https://pr28037-4ecf896.ngbuilds.io/.
You can preview 9ac71d8 at https://pr28037-9ac71d8.ngbuilds.io/.

2019-01-10 15:56 UTC, petebacondarwin commented
@wKoza - it seems that your second commit came from a different account to the first commit, and does not have CLA approval. Could you squash the commits into one committed by the appropriate account?
I have triggered the AIO preview so we can see this in action, before I give an opinion on the appoach :-)

2019-01-10 16:07 UTC, petebacondarwin commented
One problem I note immediately in the preview is that this is not working when you use the forward button to navigate.

2019-01-10 16:51 UTC, wKoza commented
It's Ok with the CLAs.  Can you give me an example of reproduction steps ?

2019-01-10 17:00 UTC, petebacondarwin commented
1) Navigate to any guide, scroll down
2) Navigate to another guide, scroll down
3) Navigate to a third guide, scroll down
4) Click back button: the second guide is scrolled correctly
5) Click back button again: the first guide is scrolled correctly 
6) Click the forward button: the second guide is displayed but not scrolled.

2019-01-11 11:07 UTC, mary-poppins commented
You can preview b9407ca at https://pr28037-b9407ca.ngbuilds.io/.

2019-01-11 11:11 UTC, mary-poppins commented
You can preview f10e0d8 at https://pr28037-f10e0d8.ngbuilds.io/.

2019-01-11 13:03 UTC, mary-poppins commented
You can preview cf9d264 at https://pr28037-cf9d264.ngbuilds.io/.

2019-01-11 13:37 UTC, wKoza commented
thank you @petebacondarwin , I have changed my strategy. It seems better. However, I have some changes with the behavior. For example with this url : https://pr28037-cf9d264.ngbuilds.io/guide/template-syntax#event-binding---event-  // https://angular.io/guide/template-syntax#event-binding---event- . The display is not the same.
Question : Do you know why `---event-` has been added at the end of the anchro

I have also some changes with my UTs...

2019-01-12 13:03 UTC, mary-poppins commented
You can preview 437fd9f at https://pr28037-437fd9f.ngbuilds.io/.

2019-01-14 07:56 UTC, IgorMinar submitted a review, later dismissed
I've just tested similar workflow as what @petebacondarwin described in https://github.com/angular/angular/pull/28037#issuecomment-453171555 and still see inconsistencies when going forward and back. On certain "back" transitions, the scroll position is offset/incorrect.

I'm not sure if we can rely on the browser to correctly restore the scroll position. What makes us believe that the browser can do this correctly for a client-side app? (for static html, yes - it should work, but with client-side rendered dom I'm not confident that this is a reliable strategy today and the weirdness I see suggests that there are issues in how browsers handle this). Maybe this is possible and we just need to tune it. Alternatively, we should store the scroll position in the history stack via the `state` param in [Location#go ](https://angular.io/api/common/Location#go).

Additionally, I'd also like to be able to reload a page and have the scroll position to be preserved across reload. Your current strategy appears to be preventing the browser from doing this (try scrolling down and reloading, you'll see that page loads, the browser scrolls down and then we call scroll to top).

2019-01-14 07:56 UTC, IgorMinar commented on aio/src/app/app.component.spec.ts
>        it('should scroll after a delay when call `onDocInserted` directly', fakeAsync(() => {
this description now doesn't reflect what the test is asserting. can you update?

2019-01-14 11:06 UTC, wKoza commented
> On certain "back" transitions, the scroll position is offset/incorrect.

I have a problem with this scenario:
- I'm on page and I click on a link with an anchor 
- I'm scroll down and I click on link (api for example)
- I'm going back and I come back on the first anchor

It is a personal choice. If I don't do that, sometime the scroll position is offset when I'm going back also. 
I have not found out other problems however.

Maybe, can we use `ViewportScroller` and the history stack; I'll try.

2019-01-15 20:38 UTC, mary-poppins commented
You can preview 33cd455 at https://pr28037-33cd455.ngbuilds.io/.

2019-01-15 21:01 UTC, mary-poppins commented
You can preview 73ab6ff at https://pr28037-73ab6ff.ngbuilds.io/.

2019-01-15 22:24 UTC, wKoza commented
It's just an example of implementation for testing the behavior. 
 - A refactoring is necessary
 - Reloading a page with keeping the scroll position is not implemented (We might store the position in the localstorage)
- Using `replaceState()` many times is it detrimental to performance ?
-  We should keep the old behavior if `scrollRestoration` isn't knew.

2019-01-16 07:54 UTC, mary-poppins commented
You can preview 1488364 at https://pr28037-1488364.ngbuilds.io/.

2019-01-16 10:02 UTC, mary-poppins commented
You can preview 684617a at https://pr28037-684617a.ngbuilds.io/.

2019-01-16 10:02 UTC, mary-poppins commented
You can preview 4ad8769 at https://pr28037-4ad8769.ngbuilds.io/.

2019-01-16 10:12 UTC, wKoza commented
Hi @petebacondarwin,

I have changed my strategy and I think we are close to the objective. Have you any comment /  thought ?

2019-01-16 14:29 UTC, petebacondarwin requested changes
This seems to be working much better. Excellent work @wKoza.

I can confirm that moving forward and backward through the history maintains the scroll position.
And that refreshing the page resets the scroll position to the top (or to that calculated from the hash).

A few suggestions:

1) We do not need to delay the scroll if we are scrolling to a position from the history. Currently this is quite off-putting, since the page jumps to the top and then to the historical scroll position.  I have tested the following change to the code locally:

```
    // we use `scroll() when we load a new document or when we click navigate to an anchor
    if (!this.popStateFired || !this.scrollPosition || !this.supportManualScrollRestoration()) {
      // Scroll 500ms after the new document has been inserted into the doc-viewer.
      // The delay is to allow time for async layout to complete.
      setTimeout(() => this.autoScroll(), 500);
    } else {
      // The document is reloaded following a popState` event`, so we manage the scroll scrollPosition
      // We don't need to delay for layout because we are moving back to a position that was computed before.
      this.viewportScroller.scrollToPosition(this.scrollPosition);
      this.popStateFired = false;
    }
```

*(Since the doc contents are already cached in memory I believe that the rendering is done immediately and so there is no chance of the scroll failing to occur correctly. I tried it with a really long document and it always ended up scrolling to the correct place).*

2) From an architectural point of view, I feel that the logic that is being added in this PR should mostly live in the `ScrollService` so that the `AppComponent` knows as little as possible about this new behaviour. Can you see if you can move it over - or convince me otherwise?

3) You have relocated `onScroll()` and `onKeyUp()` methods within the file. This appears purely stylistic and doesn't affect the actual functionality, right? Doing so in this PR makes it more difficult to see the actual change within these methods: one line in `onScroll()` and none in `onKeyUp()`. I would prefer not to make these sort of stylistic changes; and if you must then put them in a different commit so that it is easier to follow the git history when we come back to it later.

2019-01-16 15:50 UTC, wKoza commented
It is really good to hear ;)

1. I'm totally agree with you, 
2. I hesitated about this point.  I have to be able to extract some stuffs.
3. Yes, you are right (it's a obsessive-compulsive disorder ;)). I will retore that.

2019-01-18 12:53 UTC, mary-poppins commented
You can preview f4b91d0 at https://pr28037-f4b91d0.ngbuilds.io/.

2019-01-18 13:17 UTC, mary-poppins commented
You can preview 97e3cde at https://pr28037-97e3cde.ngbuilds.io/.

2019-01-18 13:42 UTC, mary-poppins commented
You can preview 688ce03 at https://pr28037-688ce03.ngbuilds.io/.

2019-01-18 13:48 UTC, petebacondarwin requested changes

2019-01-18 13:48 UTC, petebacondarwin commented on aio/src/app/app.component.ts
> +    }
Much better, but why not go all the way and putting all this code in a method in the `ScrollService` too? If necessary passing in the potential delay needed by the AppComponent to do it render as an argument?

2019-01-18 14:02 UTC, wKoza commented on aio/src/app/app.component.ts
> +    }
The navigation seems more fluent when we load a new page due to `this.scrollService.isLocationWithHash()`. 
Yes, we can put all this code in a new method, It's more coherent.

2019-01-18 15:10 UTC, mary-poppins commented
You can preview bc69419 at https://pr28037-bc69419.ngbuilds.io/.

2019-01-18 17:20 UTC, petebacondarwin requested changes
Now we are looking good. Thanks!
Can you fix the broken tests in the CI?

2019-01-18 18:04 UTC, wKoza commented
Now, it's the weekend. I'm going serenely to end by fixing the broken tests (and add others) . I have to add a feature: reloading a page and have the scroll position preserved across reload.

2019-01-19 14:39 UTC, mary-poppins commented
You can preview 96ce96e at https://pr28037-96ce96e.ngbuilds.io/.

2019-01-19 17:02 UTC, petebacondarwin requested changes
I ❤️ this PR! It is a really nice bit of coding. Thank you @wKoza !
It seems to work really well when navigating, especially on Chrome and Firefox.
I have a few suggestions, if you don't mind. Otherwise LGTM.

2019-01-19 18:43 UTC, wKoza commented on aio/src/app/app.component.spec.ts
> +        expect(scrollSpy).not.toHaveBeenCalled();
You are right, functionally, this has no interest for this test. I'm facing a problem when running this test. I can't figure out why I have this error when I remove `tick(scrollDelay);`. I should have noticed this after the push. 
This is my error when I remove these lines:

```
Chrome 71.0.3578 (Mac OS X 10.14.2) AppComponent with proper DocViewer auto-scrolling should call `scrollAfterDocInserted` (via `onDocInserted`) when navigate to a new Doc FAILED
        Error: 3 timer(s) still in the queue.
            at UserContext.<anonymous> (http://localhost:9876/node_modules/zone.js/dist/zone-testing.js?:1435:1)
            at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/node_modules/zone.js/dist/zone.js?:388:1)
            at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/node_modules/zone.js/dist/zone-testing.js?:288:1)
            at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/node_modules/zone.js/dist/zone.js?:387:1)
            at Zone../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:9876/node_modules/zone.js/dist/zone.js?:138:1)
            at runInTestZone (http://localhost:9876/node_modules/zone.js/dist/zone-testing.js?:509:1)

````

2019-01-19 19:02 UTC, petebacondarwin commented on aio/src/app/app.component.spec.ts
> +        expect(scrollSpy).not.toHaveBeenCalled();
That error indicates that we have triggered some `setTimeout()` calls somewhere that have not yet completed. This was hidden by the original `tick(scrollDelay)`.
I am pretty sure that it is nothing inside the `ScrollService`, since you have mocked out the only function that calls `setTimeout()`. 
It is probably something else in the DocViewer or AppComponent that scheduled something to happen...

2019-01-19 19:05 UTC, petebacondarwin commented on aio/src/app/app.component.spec.ts
> +        expect(scrollSpy).not.toHaveBeenCalled();
Perhaps this is one of them:

```
setTimeout(() => this.isFetching = false, 500);
```

2019-01-19 19:05 UTC, petebacondarwin commented on aio/src/app/app.component.spec.ts
> +        expect(scrollSpy).not.toHaveBeenCalled();
And another:

````
setTimeout(() => this.updateShell());
```

2019-01-19 19:06 UTC, petebacondarwin commented on aio/src/app/app.component.spec.ts
> +        expect(scrollSpy).not.toHaveBeenCalled();
And also

```
this.isFetchingTimeout = setTimeout(() => this.isFetching = true, 200);
```

2019-01-19 19:08 UTC, petebacondarwin commented on aio/src/app/app.component.spec.ts
> +        expect(scrollSpy).not.toHaveBeenCalled();
That makes three :-)
I would just call `tick(500)` at the end of the test with a comment explaining that there are other outstanding timers in the AppComponent that are not relevant.

2019-01-19 19:39 UTC, wKoza commented on aio/src/app/shared/scroll.service.spec.ts
> +import { fakeAsync, tick } from '@angular/core/testing';
👍

2019-01-19 19:58 UTC, wKoza commented on aio/src/app/shared/scroll.service.spec.ts
> +      expect(scrollService.supportManualScrollRestoration()).toBe(true);
I propose a conditionnal test like this:
```typescript
it('should return true when popState event was fired after a back navigation if the browser supports ' +
      '`scrollRestoration`. Otherwise, needToFixScrollPosition() returns false', () => {

      if (scrollService.supportManualScrollRestoration()) {
        location.go('/initial-url1');
        // We simulate a scroll down
        location.replaceState('/initial-url1', 'hack', {scrollPosition: [2000, 0]});
        location.go('/initial-url2');
        location.back();

        expect(scrollService.popStateFired).toBe(true);
        expect(scrollService.scrollPosition).toEqual([2000, 0]);
        expect(scrollService.needToFixScrollPosition()).toBe(true);
      } else {
        location.go('/initial-url1');
        location.go('/initial-url2');
        location.back();
        expect(scrollService.popStateFired).toBe(false); // popStateFired is always false
        expect(scrollService.scrollPosition).toEqual([0, 0]); // scrollPosition always equals [0, 0]
        expect(scrollService.needToFixScrollPosition()).toBe(false);
      }

    });
```

2019-01-19 20:04 UTC, wKoza commented on aio/src/app/shared/scroll.service.spec.ts
> +    it('should return true when popState event was Fired after a forward navigation', () => {
I have also wrote a conditionnal test

2019-01-19 20:34 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +  scrollAfterDocInserted(delay: number) {
Oh yes, I wasn't very inspired. `scrollAfterRender` sounds good.

2019-01-19 20:54 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +    }
I have saw this page but I have prefered basing me on the work of Victor [here](https://github.com/angular/angular/blob/b61dafaeacbe80572b76884aa7acf1ba1c6ac45a/packages/common/src/viewport_scroller.ts#L128). 
For me, if the browser doesn't support this feature, we have `!!undefined`.
I've not the response, but, in all cases, we should be coherent.

2019-01-19 21:30 UTC, mary-poppins commented
You can preview 4f9f3bf at https://pr28037-4f9f3bf.ngbuilds.io/.

2019-01-20 12:56 UTC, mary-poppins commented
You can preview 885c910 at https://pr28037-885c910.ngbuilds.io/.

2019-01-20 13:20 UTC, wKoza commented
I have pushed the last feature (restore the scroll position after a reload). Thanks a lot for your reviews @petebacondarwin :tada: :tada: :tada:

2019-01-20 16:15 UTC, wKoza commented
If a create a big static file with an anchor in the middle, I observe the following behavior:

- **With Chrome and Firefox**
* If I scroll down and press "refresh", I stay at the last position
* If I click on an anchor, then I scroll down / up and press "refresh", I stay at the last position

- **With Firefox**
* If I scroll down and reload the page with the address bar, **I go to the top of the page**
* If I click on an anchor, then I scroll down / up and reload with the address bar, **I return at the  anchor**

- **With Chrome**
* If I scroll down and reload the page with the address bar, I stay at the last position
* If I click on an anchor, then I scroll down / up and reload with the address bar, I stay at the last position

So, only Firefox have a difference with a specific action

2019-01-20 18:19 UTC, petebacondarwin commented
Blimey! You are right! I am sure I tried this out last week and got completely different behaviour...

OK let's go with this feature then :-)

2019-01-20 18:31 UTC, petebacondarwin requested changes
Good stuff.

So I notice that there is a little bit of jank when you do a reload - it starts at the top of the page and only scrolls down after the `scrollDelay`. Is there anything we can do about that?

Also, I feel that some of these new method names are a bit unwieldy:

* I don't think we need to rename the `needToFixScrollPosition()` method - the jsdoc description explains the circumstance.
* The `getScrollPositionFromSessionStorage()` and `removeScrollPositionFromSessionStorage()` feel like they are exposing an implementation detail (the session storage) too much. Can we just call them `getStoredScrollPosition()` and `removeStoredScrollPosition()`; or maybe `getPreviousScrollPosition()` and `clearPreviousScrollPosition()`?

2019-01-20 19:50 UTC, wKoza commented
Ok for `needToFixScrollPosition`, JSDoc will be there to clarify. I have also change the methods like this : getStoredScrollPosition() and removeStoredScrollPosition(). It's good.

For the first comment, maybe can we play with the `opaticiy` with an animation. I can try this.

2019-01-20 20:03 UTC, mary-poppins commented
You can preview 5bcda90 at https://pr28037-5bcda90.ngbuilds.io/.

2019-01-21 13:30 UTC, petebacondarwin commented
Sorry to keep pushing back on this. It is a very good PR!

1) I just wondered, why are you using session storage rather than history to store the current page position? Is that because unless you move elsewhere there is no item in the history?
2) Regarding the jank when loading - can we not work out that we are reloading rather than navigating to a new page via a URL, and then avoid the `setTimeout(..., scrollDelay)`?

2019-01-21 14:35 UTC, petebacondarwin commented
OK, I can live with that! Great work - and thank you for your patience. Just waiting on the CI integration test. (I restarted it in case it was a flake). If that goes green then I think it is simplest to squash all these commits together before merging - unless you feel that some of them should be separate?

2019-01-21 14:35 UTC, petebacondarwin approved these changes

2019-01-21 14:49 UTC, petebacondarwin commented
It was a flake! So if you don't mind squashing these commits (as you see fit) and then we'll double-check with @IgorMinar before merging. Great work!

2019-01-21 14:59 UTC, mary-poppins commented
You can preview a9d0785 at https://pr28037-a9d0785.ngbuilds.io/.

2019-01-21 15:08 UTC, petebacondarwin commented on aio/src/app/shared/scroll.service.ts
> +   * Check if the browser support `scrollTo` and `scrollRestoration`
support -> supports

2019-01-21 15:08 UTC, petebacondarwin commented on aio/src/app/shared/scroll.service.ts
> +   * Check if the scroll positon need to manually fix after popState event
positon -> position

2019-01-21 15:19 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +   * Check if the scroll positon need to manually fix after popState event
Sorry, needs to be manually **fixed** ?

2019-01-21 15:22 UTC, petebacondarwin commented on aio/src/app/shared/scroll.service.ts
> +   * Check if the scroll positon need to manually fix after popState event
Yes, the whole line should be:

```
Check if the scroll position needs to be manually fixed after popState event.
```

2019-01-21 16:14 UTC, gkalpak reviewed
Sorry to crash the party, but I was passing by and thought I'd add some comments :grin:
The implementation seems a little complicated (I am not even 100% sure how it works :grin:), but the end result looks correct ✔️
Nice one, @wKoza 👍

2019-01-21 16:14 UTC, gkalpak commented on aio/src/app/shared/scroll.service.ts
> +        if (state.type === 'hashchange') {
For future reference, I think it would be useful to have some comments explaining when each type of event would be emitted.

2019-01-21 16:14 UTC, gkalpak commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollPosition = state.state ? state.state['scrollPosition'] : null;
It is an edge-case, but I believe we should store the new `scrollPosition` to `sessionStorage`. As it is now, if the user reloads before the 500ms delay, they will end up to the previous page's scroll position.

2019-01-21 16:14 UTC, gkalpak commented on aio/src/app/shared/scroll.service.ts
> +  }
For future reference, it would be helpful to have some comments in this method explaining when each branch would be "hit".

2019-01-21 16:39 UTC, petebacondarwin commented on aio/src/app/shared/scroll.service.ts
> +  supportManualScrollRestoration(): boolean {
Originally it was being mocked out in tests, so it helped to have a method. But no benefit now.

2019-01-21 16:40 UTC, petebacondarwin commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollPosition = state.state ? state.state['scrollPosition'] : null;
Good catch

2019-01-21 16:42 UTC, wKoza commented on aio/src/app/app.component.ts
> +    this.scrollService.removeStoredScrollPosition();
The name of the method is `onDocRemoved`. I think the first line is redundant.
The second line have to be removed. We stop to scrollToTop() when the Doc is removed.

2019-01-21 16:54 UTC, wKoza commented on aio/src/app/app.component.ts
> +    this.scrollService.updateScrollPositionInHistory();
We update the scroll position in the case there is no scroll event on the page before;
I add it

2019-01-21 16:58 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +    return this.popStateFired && this.scrollPosition && this.supportManualScrollRestoration()
:scream:

2019-01-21 17:00 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +      this.location.subscribe(state => {
:+1:

2019-01-21 17:07 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +      setTimeout(() => this.viewportScroller.scrollToPosition(this.getStoredScrollPosition() !), delay);
Because it's marginal case but we can compute the value before the `if`

2019-01-21 19:12 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollPosition = state.state ? state.state['scrollPosition'] : null;
In this case, we doesn't have a delay. You can see [this line](https://github.com/angular/angular/blob/a9d0785b5137fe74764d6b4d20a966e1c3adbe5f/aio/src/app/shared/scroll.service.ts#L102)

2019-01-21 19:43 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +    return this.popStateFired && this.scrollPosition && this.supportManualScrollRestoration()
@gkalpak , our tslint.json is wrong. We should have this:
````json
"semicolon": [
      true,
      "always"
    ] 
```

2019-01-21 20:22 UTC, wKoza commented
> Sorry to keep pushing back on this. It is a very good PR!
> 
> 1. I just wondered, why are you using session storage rather than history to store the current page position? Is that because unless you move elsewhere there is no item in the history?
> 2. Regarding the jank when loading - can we not work out that we are reloading rather than navigating to a new page via a URL, and then avoid the `setTimeout(..., scrollDelay)`?

@petebacondarwin , finally, the setTimeOut [here](https://github.com/angular/angular/blob/a9d0785b5137fe74764d6b4d20a966e1c3adbe5f/aio/src/app/shared/scroll.service.ts#L90) seems to be unnecessary. I'll remove it.

2019-01-21 21:10 UTC, mary-poppins commented
You can preview 09b3d1f at https://pr28037-09b3d1f.ngbuilds.io/.

2019-01-22 20:11 UTC, gkalpak commented on aio/src/app/app.component.ts
> +    this.scrollService.updateScrollPositionInHistory();
Since `updateScrollPositionInHistory()` isn't trivial, it might be a good idea to do some debouncing here. WDYT?

2019-01-22 20:11 UTC, gkalpak commented on aio/src/app/shared/scroll.service.ts
> +          this.popStateFired = false;
This isn't necessary, since `scrollToPosition()` sets `popStateFired` to false.

2019-01-22 20:11 UTC, gkalpak commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollToPosition();
Do you mean [here][1]? If so, why do we need both calls?
More importantly, why do we need to scroll to `this.scrollPosition`, whent the hash changes (and not scroll to the target element or to the top)?

[1]: https://github.com/angular/angular/pull/28037/files#diff-47630de76f405b4b39f729528b9b8918R130

2019-01-22 20:11 UTC, gkalpak commented on aio/src/app/app.component.ts
> +    this.scrollService.updateScrollPositionInHistory();
Why do we care if there was no scroll before? Should we be at (0, 0) then?

2019-01-22 20:15 UTC, gkalpak commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollPosition = state.state ? state.state['scrollPosition'] : null;
The scrolling is synchronous in `scrollAfterDelay()` (which is not a great name for a method that scrolls synchronously 😛), but calling `scrollAfterDelay()` is not synchronous wrt this line here. I was able to reproduce this by clicking the back button and reloading quickly.

2019-01-23 06:57 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +        // The document was reloaded following a popState `event`, so we manage the scroll scrollPosition
Yes, I add it

2019-01-23 07:06 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +        // The document was reloaded following a link. If the location contains a hash, we have to wait for async
Why "reloaded" ... I don't know. But loaded, yes !
Yes , also. I add it
````
// The document was loaded either of the following cases: a direct navigation via typing the URL in the address bar or a click on a link. If the location contains a hash, we have to wait for async layout.
```

2019-01-23 07:42 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollToPosition();
After, when a location had a hash, we called autoscroll() to scroll to the target element. Now, we can go back and return to a location which has a hash **BUT**, we can be to a another position (we have scrolled after have been to target element (anchor)). It's clear ?

2019-01-23 07:57 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollPosition = state.state ? state.state['scrollPosition'] : null;
Your comment is outofdate. The name is now scrollAfterRender() :innocent:. 
I 'm not able to reproduce this. For me, It would mean rather that the event `onDocRemoved` was been fired .

2019-01-23 08:18 UTC, wKoza commented on aio/src/app/app.component.ts
> +    this.scrollService.updateScrollPositionInHistory();
Yes, I saw that as a security, but I can remove it. That should be good (before, I have had some problems but it was with an other implementation).

2019-01-23 08:21 UTC, wKoza commented
@gkalpak, I've covered all of your questions. Notify me before my (last?) commit ;)

2019-01-23 12:11 UTC, gkalpak commented on aio/src/app/app.component.ts
> +    this.scrollService.updateScrollPositionInHistory();
I would remove anything that is not necessary. The implementation is already a little complicated :grin:
The simpler it is, the easier it will be to maintain :wink:

2019-01-23 13:23 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollToPosition();
I propose to you this scenario :

- Go to: https://pr28037-a9d0785.ngbuilds.io/guide/template-syntax
- Scroll down to the section "Expression guidelines"
- Click on "Simplicity"; Now url is "https://pr28037-a9d0785.ngbuilds.io/guide/template-syntax#simplicity"
- Scroll down ...
- Click on "User Input" int the left menu; Url is https://pr28037-a9d0785.ngbuilds.io/guide/user-input
- Go back; url is "https://pr28037-a9d0785.ngbuilds.io/guide/template-syntax#simplicity" and you are in last position in this page (popState event has been fired -> event InseredDoc -> call scrollAfterRender() )
- Go back: url is "https://pr28037-a9d0785.ngbuilds.io/guide/template-syntax" and you are on link "Simplicity" (popState then hashchange have been fired -> this.scrollToPosition());

2019-01-23 13:32 UTC, gkalpak commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollToPosition();
Yeah, but wouldn't the scrolling be taken care of [this line][1] in that case?

[1]: https://github.com/angular/angular/pull/28037/files#diff-47630de76f405b4b39f729528b9b8918R130

2019-01-23 15:18 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollToPosition();
Yes ,This line is called at the last step but it scrolls to the top since there is no more hash. But I'm agree, sometimes, this line is called for nothing.

2019-01-23 15:47 UTC, gkalpak commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollToPosition();
I don't understand in what circumstances this could have an effect.
AFAICT, [this line][1] is enough for scrolling to the top. It seems to me that one of the two has to go. Am I missing something? 

[1]: https://github.com/angular/angular/pull/28037/files#diff-47630de76f405b4b39f729528b9b8918R130

2019-01-23 16:15 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollToPosition();
[this line](https://github.com/angular/angular/pull/28037/files#diff-47630de76f405b4b39f729528b9b8918R130)  provide the scroll to hash (step 3). [This line](https://github.com/angular/angular/pull/28037/files/a9d0785b5137fe74764d6b4d20a966e1c3adbe5f#diff-bc2334a81b493353fc53a822bec60f8cR53) is not called.
And [this line](https://github.com/angular/angular/pull/28037/files/a9d0785b5137fe74764d6b4d20a966e1c3adbe5f#diff-bc2334a81b493353fc53a822bec60f8cR53) provide the scroll to the link (step 7).
If you remove one of this lines , either the step3 or 7 will fail

2019-01-23 20:11 UTC, gkalpak commented on aio/src/app/app.component.ts
> +    this.scrollService.updateScrollPositionInHistory();
On Chrome (desktop), after some scrolling, I start to get the following warnings in the console: 

> Throttling history state changes to prevent the browser from hanging.

So, I believe it is a good idea to do some throttling/debouncing here.

2019-01-23 21:00 UTC, gkalpak commented on aio/src/app/shared/scroll.service.ts
> +          this.scrollToPosition();
I see. I played with this locally and the emitted events are very different from what I expected.
Let's leave it as is for now (since it seems to work fine). We can always tweak it later is needed :wink:

2019-01-23 21:01 UTC, gkalpak commented
@wKoza, I think you are good to go for that (last?) commit 💪

2019-01-23 22:41 UTC, mary-poppins commented
You can preview bf6bc41 at https://pr28037-bf6bc41.ngbuilds.io/.

2019-01-24 09:42 UTC, gkalpak commented on aio/src/app/shared/scroll.service.ts
> +        && 'scrollY' in window && !!history && !!history.scrollRestoration;
OOC, under what circumstances do we expect this line to throw?

2019-01-24 10:14 UTC, gkalpak approved these changes
Awesome work, @wKoza 💯 
Thx so much ❤️ ❤️ ❤️

2019-01-24 10:17 UTC, gkalpak commented
BTW, I have created #28332 to track possible improvements to scroll position restoration (but nothing that should block this PR) :wink:

2019-01-24 13:14 UTC, wKoza commented on aio/src/app/shared/scroll.service.ts
> +        && 'scrollY' in window && !!history && !!history.scrollRestoration;
This code come from [here](https://github.com/angular/angular/blob/b61dafaeacbe80572b76884aa7acf1ba1c6ac45a/packages/common/src/viewport_scroller.ts#L150). So, maybe `window.scrollTo` might throw an error or is "just in case". @vsavkin can maybe explain its choice.

2019-01-24 13:57 UTC, gkalpak commented on aio/src/app/shared/scroll.service.ts
> +        && 'scrollY' in window && !!history && !!history.scrollRestoration;
It seems redundant (unless there are environments where `window` is defined and has a `scrollTo` getter, but trying to access `window.scrollTo` throws an error.

<sub>(Not that I haven't seen such strange limitations in certain environments :wink: angular/angular.js#13945)</sub>

2019-01-24 18:26 UTC, closed without merging

2019-01-24 18:43 UTC, petebacondarwin commented
🎉