fix(docs-infra): improve a11y
angular/angular pull request #28086
Opened 2019-01-11 18:59 UTC by wKoza

related to #27723

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

This PR improve accessibility score. 

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Actual score : 79% on index.html

Issue Number: 27723

## What is the new behavior?
Actual score : 90% on index.html

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2019-01-11 21:41 UTC, petebacondarwin requested changes
Nice PR thanks @wKoza - a couple of suggested changes.

2019-01-11 21:41 UTC, petebacondarwin commented on aio/src/app/app.component.html
> +  <section class="sidenav-content" [id]="pageId" role="article">
Actually I think that the [`Main role`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Main_role) is more appropriate here. In which case, according to the docs, we should use the `<main>` tag instead of the aria role.

2019-01-11 21:41 UTC, petebacondarwin commented on aio/src/app/custom-elements/announcement-bar/announcement-bar.component.ts
> +      <img [src]="announcement.imageUrl" alt="announcement">
Not sure if this is right, I would be tempted to go with `alt=""` since we do not know what is going to be in the image, and most likely it is being described by the message directly below. I don't think that "announcement" either describes the image nor gives the reader any real benefit in understanding the content.

2019-01-12 07:10 UTC, wKoza commented on aio/src/app/app.component.html
> +  <section class="sidenav-content" [id]="pageId" role="article">
Sure, We can use `<main>` element, but, since we have to be compatible with IE , we should also  add a [`role` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main#Browser_compatibility) like this: 
```html
<main role="main">
  ...
</main>
```

2019-01-16 09:37 UTC, petebacondarwin approved these changes
Great! I have restarted the flaky test and will add the merge label when it is green.

2019-01-16 09:44 UTC, mary-poppins commented
You can preview 9f2248a at https://pr28086-9f2248a.ngbuilds.io/.
You can preview e7b09bf at https://pr28086-e7b09bf.ngbuilds.io/.

2019-01-16 10:57 UTC, gkalpak requested changes
👌

2019-01-16 10:57 UTC, gkalpak commented on aio/src/app/app.component.html
> +  <main class="sidenav-content" [id]="pageId" role="main">
Youi also need to update related styles, e.g.:

- https://github.com/angular/angular/blob/e7b09bfba1b8c3562467a17d2aaca5c58962d88b/aio/src/styles/1-layouts/_marketing-layout.scss#L37
- https://github.com/angular/angular/blob/e7b09bfba1b8c3562467a17d2aaca5c58962d88b/aio/src/styles/1-layouts/_marketing-layout.scss#L271
- https://github.com/angular/angular/blob/e7b09bfba1b8c3562467a17d2aaca5c58962d88b/aio/src/styles/1-layouts/_marketing-layout.scss#L277
- https://github.com/angular/angular/blob/e7b09bfba1b8c3562467a17d2aaca5c58962d88b/aio/src/styles/2-modules/_notification.scss#L92

2019-01-16 11:02 UTC, wKoza commented on aio/src/app/app.component.html
> +  <main class="sidenav-content" [id]="pageId" role="main">
Good catch ! I'll fix it.

2019-01-16 11:11 UTC, petebacondarwin commented on aio/src/app/app.component.html
> +  <main class="sidenav-content" [id]="pageId" role="main">
Doh! I didn't notice that!

2019-01-16 12:07 UTC, mary-poppins commented
You can preview ba41c5b at https://pr28086-ba41c5b.ngbuilds.io/.

2019-01-16 12:22 UTC, wKoza commented on aio/src/app/app.component.html
> +  <main class="sidenav-content" [id]="pageId" role="main">
By the way, the line 37 doesn't need to be fixed. Thanks guys !

2019-01-16 12:31 UTC, gkalpak commented on aio/src/app/app.component.html
> +  <main class="sidenav-content" [id]="pageId" role="main">
> By the way, the line 37 doesn't need to be fixed.

How so?

2019-01-16 12:32 UTC, gkalpak commented on aio/src/app/app.component.html
> +  <main class="sidenav-content" [id]="pageId" role="main">
Oh, it's a different `section` element. 😇

2019-01-16 13:45 UTC, petebacondarwin requested changes
OK, this looks like it is working style-wise now. Thanks.
Can you squash all the commits into one please, remembering that the subject should start with a lower case letter. Also for future reference, if you are making a fixup commit it is best to use `git commit --fixup=SHA` to ensure that the syntax of the commit is correct, otherwise our merge-script might not squash commits correctly.

2019-01-16 14:06 UTC, wKoza commented
Thank you for the tips !

2019-01-16 14:07 UTC, mary-poppins commented
You can preview 19da954 at https://pr28086-19da954.ngbuilds.io/.

2019-01-16 19:06 UTC, petebacondarwin approved these changes

2019-01-16 19:44 UTC, gkalpak approved these changes

2019-01-17 01:38 UTC, closed without merging