fix(ivy): debug node references not returning template ref
angular/angular pull request #28101
Opened 2019-01-12 12:54 UTC by crisbeto

Fixes the `DebugNode.references` returning a reference to the underlying comment node, rather than the `TemplateRef` that the reference is pointing to. The issue comes from the fact that `discoverLocalRefs` falls back directly to returning the native node, if the ref isn't pointing to a directive, rather than looking through the locals.

These changes resolve FW-870.

2019-01-12 12:58 UTC, mary-poppins commented
You can preview aba8fb8 at https://pr28101-aba8fb8.ngbuilds.io/.

2019-01-12 13:03 UTC, mary-poppins commented
You can preview 098cdda at https://pr28101-098cdda.ngbuilds.io/.

2019-01-14 20:17 UTC, kara requested changes

2019-01-14 20:17 UTC, kara commented on packages/core/src/render3/context_discovery.ts
> +    for (let i = 0; i < tNode.localNames.length; i += 2, localIndex++) {
Can we move this `localIndex++` down into the for loop? It took me a bit to find it.

2019-01-14 20:17 UTC, kara commented on packages/core/src/render3/context_discovery.ts
> +        result[localRefName] = lView[localIndex] || getNativeByTNode(tNode, lView);
This strategy of copying resolved values in the `LView` should actually work for regular elements and directives as well, so I think we can simplify the whole conditional block to:

```ts
result[localRefName] = lView[localIndex]
```

2019-01-14 20:40 UTC, mary-poppins commented
You can preview d3b94c3 at https://pr28101-d3b94c3.ngbuilds.io/.

2019-01-14 20:49 UTC, crisbeto commented
I've addressed the feedback @kara, can you take another look?

2019-01-14 21:13 UTC, alfaproject commented on packages/core/src/render3/context_discovery.ts
> -      const localRefName = tNode.localNames[i];
I think keeping this line improves readability and should minify just the same

2019-01-14 21:20 UTC, kara approved these changes
LGTM

2019-01-15 01:12 UTC, closed without merging