fix(ivy): Ensure proper namespace is used to create elements in JIT
angular/angular pull request #28144
Opened 2019-01-15 00:24 UTC by benlesh

Updates render to properly use the namespace URL that Ivy passes around rather than use it to look up the namespace URL ala ViewEngine. 

Resolves [FW-811](https://angular-team.atlassian.net/browse/FW-811)

2019-01-15 01:01 UTC, AndrewKushnir commented
@benlesh it looks like you've created this PR on top of the master while it was in a state where "integration_test" was broken. Please rebase it from the latest master to make "integration_test" pass. Thank you.

2019-01-15 01:45 UTC, mary-poppins commented
You can preview 3c7b67d at https://pr28144-3c7b67d.ngbuilds.io/.

2019-01-15 01:46 UTC, mary-poppins commented
You can preview 5033202 at https://pr28144-5033202.ngbuilds.io/.

2019-01-15 01:51 UTC, kara requested changes

2019-01-15 01:51 UTC, kara commented on packages/platform-browser/src/dom/dom_renderer.ts
> +      return document.createElementNS(NAMESPACE_URIS[namespace] || namespace, name);
There are two other places where we look the namespace up in this file - `setAttribute` and `removeAttribute`. Can you update those too?

2019-01-15 04:11 UTC, AndrewKushnir commented
@kara @benlesh I think we may also need to check how VE and Ivy handle the case when invalid/unsupported namespace is specified and align this behavior (and have a test to capture this). My understanding is that we'll see a difference after this change due to the fact that we return namespace as is in case it's not registered in `NAMESPACE_URIS`.

2019-01-15 05:00 UTC, mhevery submitted a review, later dismissed
Presumably there is a failing tests which this unblocks. I don't see any changes to the tests.

2019-01-16 13:21 UTC, trotyl commented
What if some custom renderers do need the raw namespace text? Renderer is a public API, how could a breaking change being introduced directly?

2019-01-17 00:07 UTC, kara commented on packages/platform-browser/src/dom/dom_renderer.ts
> +      return document.createElementNS(NAMESPACE_URIS[namespace] || namespace, name);
Update based on offline discussion: 
- add TODO comments to `setAttribute` and `removeAttribute`
- remove fixme for test

2019-01-18 02:31 UTC, kara approved these changes
LGTM, aside from typo

2019-01-18 02:31 UTC, kara commented on packages/platform-browser/src/dom/dom_renderer.ts
> +      // full URIs for namespaces, therefor this lookup will fail.
Same below:

```suggestion
      // full URIs for namespaces, therefore this lookup will fail.
```

2019-01-18 17:58 UTC, closed without merging