docs: edit $any() section and add example in Template Syntax
angular/angular pull request #28157
Opened 2019-01-15 17:10 UTC by kapunahelewong

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Edits to copy and creation of a new example just for this section. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This is the 11th (and last) in a series of PRs that together are a complete rewrite of Template Syntax. Once they are all merged, the next step is to break them into individual docs as in the NgModules section.

The with this PR and the other 9 that are yet to be merged, the Template Syntax rewrite is complete! 🎉The only remaining task is to then break them apart! 🌷

2019-01-15 17:15 UTC, mary-poppins commented
You can preview fccf28a at https://pr28157-fccf28a.ngbuilds.io/.

2019-01-22 15:06 UTC, brandonroberts requested changes

2019-01-22 15:06 UTC, brandonroberts commented on aio/content/examples/built-in-template-functions/e2e/src/app.e2e-spec.ts
> +describe('Built-in-template-functions-example', function () {
```suggestion
describe('Built-in Template Functions Example', function () {
```

2019-01-22 15:06 UTC, brandonroberts commented on aio/content/examples/built-in-template-functions/e2e/src/app.e2e-spec.ts
> +    let jsonDate = element(by.css('h2'));
jsonDate?

2019-01-23 14:58 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +## Built-in template functions
Added that it's during AoT and linked to it.

2019-01-23 14:59 UTC, kapunahelewong commented on aio/content/examples/built-in-template-functions/e2e/src/app.e2e-spec.ts
> +describe('Built-in-template-functions-example', function () {
got it, thanks!

2019-01-23 15:14 UTC, kapunahelewong commented on aio/content/examples/built-in-template-functions/e2e/src/app.e2e-spec.ts
> +    let jsonDate = element(by.css('h2'));
Ha! That's unintended. Fixed to something that makes sense. Thank you!

2019-01-23 15:39 UTC, mary-poppins commented
You can preview 8be4091 at https://pr28157-8be4091.ngbuilds.io/.

2019-01-29 14:58 UTC, brandonroberts requested changes
Delete the `aio/content/examples/.DS_Store` file.

2019-01-29 16:44 UTC, kapunahelewong commented
> Delete the `aio/content/examples/.DS_Store` file.

Gah! That thing snuck by me! Thanks for catching it. 😅

2019-01-29 17:01 UTC, mary-poppins commented
You can preview 0170a67 at https://pr28157-0170a67.ngbuilds.io/.

2019-03-15 13:21 UTC, brandonroberts approved these changes

2019-03-15 13:22 UTC, brandonroberts commented
Caretaker note: Using a global approval for a docs only change.

2019-03-15 13:28 UTC, mary-poppins commented
You can preview 206ed41 at https://pr28157-206ed41.ngbuilds.io/.

2019-03-19 17:21 UTC, closed without merging