fix(ivy): ensure element removal triggers host removal animations
angular/angular pull request #28162
Opened 2019-01-15 18:42 UTC by matsko

Prior to this fix Ivy would not execute any animation triggers
that exist as host bindings on an element if it is removed by
the parent template.

2019-01-15 18:47 UTC, mary-poppins commented
You can preview 5542c5f at https://pr28162-5542c5f.ngbuilds.io/.

2019-01-15 20:20 UTC, mary-poppins commented
You can preview d678291 at https://pr28162-d678291.ngbuilds.io/.

2019-01-15 22:01 UTC, mary-poppins commented
You can preview 61da545 at https://pr28162-61da545.ngbuilds.io/.

2019-01-15 23:13 UTC, matsko commented
https://test.corp.google.com/ui#id=OCL:229449485:BASE:229449511:1547594026564:99abc37e

2019-01-16 00:15 UTC, mary-poppins commented
You can preview f8f4abf at https://pr28162-f8f4abf.ngbuilds.io/.

2019-01-16 21:51 UTC, kara requested changes

2019-01-16 21:51 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> +    const isHostElement = (tNode.flags & TNodeFlags.isComponent) > 0;
You can use the `isComponent` util here:

```suggestion
    nativeRemoveChild(renderer, parent !, node, isComponent(tNode));
```

2019-01-16 21:51 UTC, kara commented on packages/core/test/animation/animation_query_integration_spec.ts
> +      fixmeIvy('unknown').it(
Can you look into why your change doesn't fix this test? If there is a different root cause, we should create a Jira ticket and link it here.

2019-01-16 23:11 UTC, mary-poppins commented
You can preview e97daca at https://pr28162-e97daca.ngbuilds.io/.

2019-01-16 23:41 UTC, matsko commented
https://tap.corp.google.com/ui#id=OCL:229449485:BASE:229639434:1547681851872:fca9a958

2019-01-16 23:43 UTC, mary-poppins commented
You can preview 0ed8966 at https://pr28162-0ed8966.ngbuilds.io/.

2019-01-17 01:31 UTC, kara approved these changes
LGTM

2019-01-17 16:54 UTC, mary-poppins commented
You can preview 420e869 at https://pr28162-420e869.ngbuilds.io/.

2019-01-17 18:00 UTC, closed without merging