build: upgrade zone.js to 0.8.28
angular/angular pull request #28219
Opened 2019-01-18 00:53 UTC by JiaLiPassion

Upgrade zone.js to 0.8.28

2019-01-22 23:44 UTC, mhevery approved these changes

2019-01-23 00:01 UTC, gkalpak reviewed
The commit message should mention now 0.8.29 (not 0.8.28).

2019-01-23 04:52 UTC, JiaLiPassion commented on packages/core/testing/src/async_fallback.ts
> +  proxyZone !.parent !.run(() => {
Yes, getZoneWith will return `Zone | null`
```
    getZoneWith(key: string): Zone | null;
```

So we will need to add `!`, and `Zone.parent` will also return `Zone | null`. 

The reason of those changes, because `Zone.js` just added `strict:true` in `tsconfig.json`, so a lot of `null type check` are added.

2019-01-23 06:44 UTC, gkalpak approved these changes

2019-01-23 06:44 UTC, gkalpak commented on integration/_payload-limits.json
> +        "polyfills": 42053
Any idea why the increase in size?
It would be worth mentioning in the commit message.

2019-01-23 06:45 UTC, gkalpak commented on packages/core/testing/src/async_fallback.ts
> +  proxyZone !.parent !.run(() => {
I wonder if that change shoukd be considered breaking (for zone.js) and warrants a minor version bump.

2019-01-23 07:48 UTC, JiaLiPassion commented on packages/core/testing/src/async_fallback.ts
> +  proxyZone !.parent !.run(() => {
@gkalpak , yeah, I agree.

2019-01-23 07:50 UTC, JiaLiPassion commented on integration/_payload-limits.json
> +        "polyfills": 42053
Some additional patch was added to `zone.js`.
1. `fetch`.
2. `customElement v1`.

So the size is increased a little.  I am working on to separate some `IE` specified logic to some standalone `zone-legacy.js`, so the size can be reduced a little.

2019-01-23 11:36 UTC, gkalpak commented on integration/_payload-limits.json
> +        "polyfills": 42053
I see. Please add that info to the commit message, so it is easy to find when `git blame`-ing, for example.

BTW, is it possible to only include specific features from zone.js. For example, if one is not using `fetch` or `customElements`, then there is no need loading the code for patching them.

2019-01-24 01:53 UTC, JiaLiPassion commented on integration/_payload-limits.json
> +        "polyfills": 42053
@gkalpak, got it, I will update the commit message.
And yes, user can specify which `module` user want to use, but currently, user still need to load all modules, maybe we can discuss whether we need to separate those modules into different files.

2019-01-28 19:32 UTC, JiaLiPassion commented on integration/_payload-limits.json
> +        "polyfills": 42053
@gkalpak , it seems my `commit message` is too long then `120 chars`, should I reduce the commit message or leave it there?

2019-01-28 20:20 UTC, gkalpak commented on integration/_payload-limits.json
> +        "polyfills": 42053
There is a typo in the commit message (updaet --> update).
Also, I would change it to something like:

> build: update zone.js to 0.8.29
>
> The API changes are due to enabling strict checks in TypeScript (via \`strict: true\`). <<--- Even better, add the commit that did this.
> The payload size changes in \`polyfills.js\` are due to more browser APIs being patched in recent versions (e.g. \`fetch\`, \`customElement v1\`).

2019-01-29 02:00 UTC, JiaLiPassion commented on integration/_payload-limits.json
> +        "polyfills": 42053
@gkalpak , thanks, I have updated the commit message.

2019-01-29 10:25 UTC, JiaLiPassion commented on integration/_payload-limits.json
> +        "polyfills": 42053
@IgorMinar, got it, I am working on it, it will not be that hard, I will finish it in about 2 weeks and submit a PR in zone.js first.

2019-01-29 23:19 UTC, mhevery commented on packages/core/testing/src/async_fallback.ts
> +  proxyZone !.parent !.run(() => {
I am fine bumping it to v0.9.0

2019-02-07 09:24 UTC, gkalpak commented on packages/core/testing/src/async_fallback.ts
> +  proxyZone !.parent !.run(() => {
@JiaLiPassion, do you think it would be reasonable to revert the breaking changes in 0.8.x and re-apply them in 0.9.0?
Or is it better/OK to keep them at 0.8.x, given that:
a. `zone.js` is still at 0.x (meaning [the public API is not stable][1])
b. most people won't be affected by the changes
c. the changes have been released weeks ago

I am fine either way, but I would like to get the PR in (one way or another) to see if it will improve a particular CI flake (or at least help debug). 

[1]: https://semver.org/#spec-item-4

2019-02-11 15:09 UTC, kara commented on packages/core/testing/src/async_fallback.ts
> +  proxyZone !.parent !.run(() => {
@JiaLiPassion bump on George's Q ^

2019-02-11 16:06 UTC, JiaLiPassion commented on packages/core/testing/src/async_fallback.ts
> +  proxyZone !.parent !.run(() => {
@gkalpak, @kara, sure, I will make a PR in `zone.js` to bump the version to `0.9.0`, because I think this `API` change will affect some other libraries (in my knowledge, such as angular-fire also use raw `Zone` directly).

2019-02-19 01:55 UTC, JiaLiPassion commented on integration/_payload-limits.json
> +        "polyfills": 42053
@IgorMinar, @gkalpak, here is the PR in `zone.js` for `evergreen bundles`.
https://github.com/angular/zone.js/pull/1186
Please review, thanks!

2019-03-22 14:36 UTC, JiaLiPassion commented
I updated this PR to upgrade `zone.js` to `0.9.0`, please review, thanks!

2019-03-22 17:50 UTC, gkalpak requested changes
Thx, @JiaLiPassion!
Should we also update the zone.js version for the `@angular/*` packages (e.g. [core][1], etc.)?

[1]: https://github.com/angular/angular/blob/fcc7cc1294441206594d4a7c1ea58475b13c818d/packages/core/package.json#L20

2019-03-22 17:50 UTC, gkalpak commented on packages/core/test/testability/testability_spec.ts
> +             expect(update2[1].data !.delay).toEqual(300);
No `toBeTruthy()` check for `update2[1].data`? 😛
(I wouldn't mind getting rid of all the `toBeTruthy()` checks tbh :grin:)

2019-03-22 17:50 UTC, gkalpak commented on integration/_payload-limits.json
> -        "polyfills": 38390
I assume this was removed by accident (probably during a rebase). Please restore it and update the numbers?

2019-03-23 01:45 UTC, JiaLiPassion commented on integration/_payload-limits.json
> -        "polyfills": 38390
Got it, will do, thanks!

2019-03-23 01:46 UTC, JiaLiPassion commented on packages/core/test/testability/testability_spec.ts
> +             expect(update2[1].data !.delay).toEqual(300);
Got it, will do!

2019-03-23 03:04 UTC, JiaLiPassion commented
@gkalpak, thank you for the review, I updated all `zone.js 0.8.26` to `zone.js 0.9.0`.

2019-03-24 08:02 UTC, vikerman approved these changes

2019-03-25 06:37 UTC, gkalpak approved these changes

2019-03-25 06:37 UTC, gkalpak commented on aio/tools/ng-packages-installer/index.spec.js
> +        'zone.js@^0.9.0': {version: '0.9.0'}
These are for testing purposes only and need to remain unchanged (because they are testing a specific feature of `NgPackagesInstaller`).

2019-03-25 06:37 UTC, gkalpak commented on aio/scripts/_payload-limits.json
> +        "polyfills": 59197
I think this should be approved by @IgorMinar.

2019-03-25 06:37 UTC, gkalpak commented on packages/core/package.json
> +    "migrations": "./schematics/migrations.json",
❤️

2019-03-25 06:37 UTC, gkalpak commented on packages/core/package.json
> +    "zone.js": "~0.9.0"
cc @IgorMinar (to confirm this is the right thing to do - I think it is)

2019-03-25 07:21 UTC, JiaLiPassion commented on aio/tools/ng-packages-installer/index.spec.js
> +        'zone.js@^0.9.0': {version: '0.9.0'}
Got it, I will revert this change. Thanks.

2019-03-25 07:21 UTC, JiaLiPassion commented on aio/scripts/_payload-limits.json
> +        "polyfills": 59197
Got it!

2019-03-25 07:21 UTC, JiaLiPassion commented on packages/core/package.json
> +    "migrations": "./schematics/migrations.json",
Thanks, I will remove the `space`.

2019-03-25 07:22 UTC, JiaLiPassion commented on packages/core/package.json
> +    "zone.js": "~0.9.0"
Got it!

2019-03-26 19:52 UTC, closed without merging

2019-03-26 20:41 UTC, IgorMinar commented on aio/scripts/_payload-limits.json
> +        "polyfills": 59197
yeah. this is not ok. 5kb is a lot.

@JiaLiPassion can you please check if this increase is necessary? if it is then we'll live with it for now and revisit again once the differential loading lands in CLI and we'll be able to load just the zone.js evergreen bundle for modern browsers. But if the increase was due to a bug or there is low hanging fruit out there to decrease the payload, we should that. thank you!

2019-03-26 22:18 UTC, JiaLiPassion commented on aio/scripts/_payload-limits.json
> +        "polyfills": 59197
@IgorMinar, sure, the reason of the `increase` is because `zone.js` add some new `monkey-patch` after `0.8.26`.
1. customElement
2. fetch

those `new patches` will make the `size bigger`.
And with `zone-evergreen.js`, the size will be `4k` smaller.