build: bump year
angular/angular pull request #28220
Opened 2019-01-18 02:07 UTC by CaerusKaru

Patch version of https://github.com/angular/angular/pull/27880

2019-01-18 02:07 UTC, CaerusKaru commented
cc @jenniferfell

2019-01-23 00:32 UTC, mary-poppins commented
You can preview a17e7c6 at https://pr28220-a17e7c6.ngbuilds.io/.

2019-01-23 00:37 UTC, jenniferfell commented
> Facebook stripped this out from their headers in a previous commit ([facebook/react#13593](https://github.com/facebook/react/pull/13593)). Wouldn't this be a bit easier if this was followed here?

Thanks, but we're going to continue using what's already been approved by Google's legal team.

2019-01-23 00:38 UTC, jenniferfell approved these changes
LGTM. @IgorMinar approved https://github.com/angular/angular/pull/27880 which is exactly the same changes just with a merge target that didn't include patch (stable).

2019-01-23 00:39 UTC, jenniferfell commented
@petebacondarwin or @gkalpak : Can you approve as docs-infra? Thanks!

2019-01-23 09:59 UTC, petebacondarwin requested changes

2019-01-23 09:59 UTC, petebacondarwin commented on packages/router/README.md
> +Read the dev guide [here](https://angular.io/guide/router).
The changes to this file seem unrelated to this commit @jenniferfell. Is this intentional or an accident during cherry-picking?

2019-01-23 11:40 UTC, gkalpak commented on aio/src/app/layout/footer/footer.component.html
> +  Super-powered by Google ©2010-2019.
💪

2019-01-23 13:35 UTC, CaerusKaru commented on packages/router/README.md
> +Read the dev guide [here](https://angular.io/guide/router).
If you look at the original PR, you’ll see it’s a conscious edit that Igor made. I’m not sure exactly why he did it, but it’s there

2019-01-23 20:18 UTC, jenniferfell commented on packages/router/README.md
> +Read the dev guide [here](https://angular.io/guide/router).
We talked about this PR at eng standup today. Igor does remember approving the original PR, and he just missed the PR targets, so I think sticking with what's been approved is the fastest path. :-)

2019-01-23 20:21 UTC, petebacondarwin approved these changes

2019-02-01 00:09 UTC, jasonaden reviewed
For Docs team.

2019-02-02 08:38 UTC, IgorMinar approved these changes

2019-02-02 08:41 UTC, IgorMinar commented
merge-assistance: this is a patch branch PR - no g3 impact. also pull approve seems stale. please rebase if necessary so that this PR lands.

2019-02-04 19:59 UTC, alexeagle approved these changes

2019-02-04 21:05 UTC, jenniferfell commented
@CaerusKaru @IgorMinar Heads up: As you probably recall, this PR was specifically to take changes that had already been approved and merged into master, and also apply those same changes to patch (aka stable). Any additional changes made in this PR mean that you'll need to merge into master & patch.

2019-02-04 22:20 UTC, closed without merging