docs(guide/browser-support): try to clarify about JIT-polyfills
angular/angular pull request #28238
Opened 2019-01-18 15:54 UTC by oBusk

Since https://github.com/angular/angular-cli/commit/30f8352ca2b3cccd72f5fcff8e09a543f9c70a8d
disabling AOT will automatically include the required polyfills. This should be clarified
in the documentation

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

Documentation states that you need to import `es7/reflect` polyfill to use JIT compilation. Since `@angular/cli@7.0`, this is untrue.

## What is the new behavior?

Try to shortly explain this

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-01-22 13:34 UTC, brandonroberts requested changes
Also update git commit message to `docs: clarify when polyfills are included with JIT compilation in browser support guide`

2019-01-22 13:34 UTC, brandonroberts commented on aio/content/guide/browser-support.md
> +      [ES7/reflect](guide/browser-support#core-es7-reflect) (JIT only, automatically included by @angular/cli if AOT is off)
I don't think this is needed here. JIT assumes AOT is off.

2019-01-22 13:34 UTC, brandonroberts commented on aio/content/guide/browser-support.md
> +      All current browsers. Included automactically by @angular/cli if AOT is off.
What about "Included by default when using the Angular CLI"? Its already assumed your running JIT compilation.

2019-01-22 14:12 UTC, oBusk commented on aio/content/guide/browser-support.md
> +      [ES7/reflect](guide/browser-support#core-es7-reflect) (JIT only, automatically included by @angular/cli if AOT is off)
Indeed, but I wanted to clarify that the developer does not have to import it since the CLI will handle it. Would it make sense to use the same wording here; `(JIT only, included automatically by Angular CLI)`?

2019-01-22 14:19 UTC, oBusk commented
@brandonroberts I found https://github.com/angular/angular-cli/pull/13403 and I'm guessing that with that change, the `browser-support` will change a lot to reflect this, seeing how https://github.com/angular/angular-cli/blob/v7.3.0-beta.0/packages/schematics/angular/application/files/src/polyfills.ts.template will now be much simpler and not list any of the [Mandatory Polyfills](https://pr28238-c815422.ngbuilds.io/guide/browser-support#mandatory-polyfills). Is there any work in progress for this? It'd make sense to try to clarify not needing JIT polyfills on that updated page rather than on the current I guess.

2019-03-20 13:08 UTC, brandonroberts commented
@oBusk will you provide an update on this PR. Is it still needed?

2019-04-03 13:35 UTC, closed without merging