fix(ivy): content projection with Shadow DOM not working
angular/angular pull request #28261
Opened 2019-01-20 12:21 UTC by crisbeto

Fixes components with native content projection (using `<content>` or `<slot>`) not working under Ivy.

The issue comes from the fact that when creating elements inside a component, we sometimes don't append the element immediately, but we leave it to projection to move it into its final destination. This ends up breaking the native projection, because the slots have to be in place from the beginning. The following changes switch to appending the element immediately when inside a component with Shadow DOM encapsulation.

This PR resolves FW-841.

2019-01-22 17:55 UTC, mhevery approved these changes

2019-01-22 19:32 UTC, kara requested changes

2019-01-22 19:32 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> +      const componentDef = componentInstance && getComponentDef(componentInstance.constructor);
`getComponentDef` has a megamorphic property access inside it, so let's avoid using it. There is another way to get a component def for a node:

```ts
const tData = currentView[TVIEW].data;
const tNode = tData[parent.index] as TNode;
const encapsulation = tData[tNode.directiveStart].encapsulation;
```

2019-01-22 20:25 UTC, kara approved these changes
LGTM

2019-01-22 21:34 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> +import {ViewEncapsulation} from '../core';
This import is causing a "cyclical dependency" error between files in G3. Can you drill down to the `metadata/view` file?

2019-01-23 18:57 UTC, alxhub commented
Needs a rebase :) thanks!

2019-01-23 19:00 UTC, crisbeto commented
Rebased.

2019-01-23 19:59 UTC, kara commented
merge assistance: looks like the merge status is stuck, though all checks pass.

2019-01-23 23:06 UTC, closed without merging