docs: migrate examples from @angular/http to @angular/common/http
angular/angular pull request #28296
Opened 2019-01-22 16:43 UTC by CaerusKaru

Fixes #28294

2019-01-22 16:43 UTC, CaerusKaru commented
cc @brandonroberts @IgorMinar

2019-01-22 16:53 UTC, mary-poppins commented
You can preview e3192d1 at https://pr28296-e3192d1.ngbuilds.io/.

2019-01-22 16:54 UTC, brandonroberts commented
@CaerusKaru this seems reasonable to me. We also need to check the affected pages for text referencing the legacy package, for example https://pr28296-e3192d1.ngbuilds.io/guide/testing#httpclienttestingmodule

2019-01-22 17:36 UTC, brandonroberts requested changes

2019-01-22 17:36 UTC, brandonroberts commented on aio/tools/examples/shared/boilerplate/cli/package.json
> -    "@angular/http": "^7.0.0",
`angular-in-memory-web-api` needs a bump in this `package.json`

2019-01-22 17:36 UTC, brandonroberts commented on aio/tools/examples/shared/boilerplate/i18n/package.json
> -    "@angular/http": "^7.0.0",
`angular-in-memory-web-api` needs a bump in this `package.json`

2019-01-22 17:36 UTC, brandonroberts commented on aio/tools/examples/shared/boilerplate/service-worker/package.json
> -    "@angular/http": "^7.0.0",
`angular-in-memory-web-api` needs a bump in this `package.json`

2019-01-22 17:36 UTC, brandonroberts commented on aio/tools/examples/shared/boilerplate/universal/package.json
> -    "@angular/http": "^7.0.0",
`angular-in-memory-web-api` needs a bump in this `package.json`

2019-01-22 17:36 UTC, brandonroberts commented on aio/content/examples/upgrade-phonecat-2-hybrid/app/app.module.ts
>    // #docregion bare, upgrademodule, httpmodule, phone
All docregions referring to `httpmodule` need to be updated.

2019-01-22 17:36 UTC, brandonroberts commented on aio/content/examples/testing/src/app/model/http-hero.service.spec.ts
> -  MockBackend,
The testing guide needs to be updated to remove the text above referencing the legacy tests.

https://pr28296-e3192d1.ngbuilds.io/guide/testing#httpclienttestingmodule

2019-01-22 17:48 UTC, CaerusKaru commented
@brandonroberts Will address comments later today!

2019-01-23 03:11 UTC, CaerusKaru commented
@brandonroberts Feedback addressed :+1:

2019-01-24 15:27 UTC, brandonroberts requested changes

2019-01-24 15:27 UTC, brandonroberts commented on aio/content/examples/testing/src/app/model/http-hero.service.spec.ts
>  } from '@angular/core/testing';
I think its safe to delete this file as it only served to show testing for the old HttpModule. Reference to the test also need to be removed from `aio/content/examples/testing/src/tests.sb.ts` and `aio/content/examples/testing/src/tests.html`

2019-01-24 16:06 UTC, CaerusKaru commented
@brandonroberts Fixed :+1:

2019-01-29 14:43 UTC, brandonroberts commented
LGTM

2019-01-29 14:45 UTC, brandonroberts approved these changes

2019-01-29 16:24 UTC, IgorMinar approved these changes
The rest looks great!

2019-01-29 16:24 UTC, IgorMinar commented on aio/content/examples/testing/src/tests.html
> -      'app/model/http-hero.service.spec',
Why delete this spec?

2019-01-29 16:34 UTC, CaerusKaru commented on aio/content/examples/testing/src/tests.html
> -      'app/model/http-hero.service.spec',
Yeah, that one got me too. But as @brandonroberts mentioned above, it’s actually a duplicate spec. There’s another http spec for the newer client one directory down.

2019-01-29 16:48 UTC, gkalpak requested changes

2019-01-29 17:14 UTC, CaerusKaru commented on aio/tools/examples/shared/boilerplate/universal/package.json
> -    "@angular/http": "^7.0.0",
This all depends on @IgorMinar and v8 planning. Http is scheduled to be removed in another PR, but I don’t know if we want this to happen before or after that.

2019-01-29 18:07 UTC, brandonroberts commented on aio/content/examples/testing/src/tests.html
> -      'app/model/http-hero.service.spec',
Yes, I think the `app/model/http-hero.service.ts` should probably be deleted also. Its a duplicate of the `hero.service.ts` referring to the old Http also

2019-03-05 22:09 UTC, alexeagle commented on aio/tools/examples/shared/boilerplate/universal/package.json
> -    "@angular/http": "^7.0.0",
http won't  be removed yet. We should update the examples on AIO but not break platform-server. So I guess this does need to stay

2019-03-05 22:43 UTC, mary-poppins commented
You can preview 9ae3678 at https://pr28296-9ae3678.ngbuilds.io/.

2019-03-07 11:22 UTC, gkalpak requested changes
Almost there 👌

2019-03-07 11:22 UTC, gkalpak commented on aio/content/examples/upgrade-phonecat-3-final/karma.conf.js
> +      { pattern: 'node_modules/tslib/**/*.js.map', included: false, watched: false },
OOC, do you know why this wasn't needed before?

2019-03-07 11:22 UTC, gkalpak commented on aio/tools/examples/shared/yarn.lock
> +  version "7.2.7"
This file seems to contain several changes that are related to upgrading dependencies to latest versions (subject to range limits in package.json).
It would be better to move the upgrade changes to a separate commit, since they are unrelated to removing `@angular/http` from examples (and it would be even better to also update the ranges in `package.json`).

2019-03-07 16:17 UTC, CaerusKaru commented on aio/content/examples/upgrade-phonecat-3-final/karma.conf.js
> +      { pattern: 'node_modules/tslib/**/*.js.map', included: false, watched: false },
IIRC it's because the new HTTP library requires it, but I've removed it in the latest commit to see if it actually breaks something. If it does, I'll add it back.

2019-03-07 16:22 UTC, mary-poppins commented
You can preview f43a504 at https://pr28296-f43a504.ngbuilds.io/.

2019-03-07 16:44 UTC, CaerusKaru commented
@gkalpak All comments addressed, PTAL :+1:

2019-03-07 20:41 UTC, gkalpak commented on aio/tools/examples/shared/yarn.lock
> +  version "7.2.7"
Just to be clear, I didn't mean that upgrading the packages is not a good change; just that it doesn't belong to this commit/PR 😇

2019-03-07 20:41 UTC, gkalpak approved these changes

2019-03-07 20:43 UTC, gkalpak commented
Great work, @CaerusKaru 😍
This is now pending approval from @vikerman (as the sole member of the `fw-testing` group :grin:).

2019-03-11 16:50 UTC, vikerman approved these changes

2019-03-11 17:53 UTC, closed without merging