fix(docs-infra): change the key used to find out the cli section
angular/angular pull request #28293
Opened 2019-01-22 13:16 UTC by wKoza

closes #28185

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently, it isn't possible to translate 'CLI COMMANDS'  in https://angular.jp or other localized versions because it's a key of the internal process of generation.  

Issue Number: #28185

## What is the new behavior?
Now, we use the key `url` which is  deemed stable.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2019-01-22 13:31 UTC, petebacondarwin requested changes
I remember when I wrote this, that I thought we might get bitten by this, but I had no better idea.
This approach is better, but it will need unit testing: https://github.com/angular/angular/blob/fdcf1bfad8fc2df6fa0d0dfaa3cd82c0d3200e0d/aio/tools/transforms/cli-docs-package/processors/processCliCommands.spec.js#L236

2019-01-23 09:23 UTC, mary-poppins commented
You can preview fdcf1bf at https://pr28293-fdcf1bf.ngbuilds.io/.
You can preview 16f5529 at https://pr28293-16f5529.ngbuilds.io/.
You can preview de4a705 at https://pr28293-de4a705.ngbuilds.io/.
You can preview 3de6e72 at https://pr28293-3de6e72.ngbuilds.io/.
You can preview ca62573 at https://pr28293-ca62573.ngbuilds.io/.

2019-01-23 09:24 UTC, petebacondarwin approved these changes

2019-01-23 09:28 UTC, petebacondarwin requested changes
Actually a few minor changes, please.

2019-01-23 09:50 UTC, wKoza commented on aio/tools/transforms/cli-docs-package/processors/processCliCommands.spec.js
> +  it('should have a key `cli` from navigation.json', () => {
I admit that this test can be weird of course; It's not the best place. It is not here to test this code but its 'configuration' (navigation.json). That is not really relevant to this code, yes.
But how can we prevent a developper that changing the `url` "break" the generation ?

2019-01-23 10:21 UTC, petebacondarwin commented on aio/tools/transforms/cli-docs-package/processors/processCliCommands.spec.js
> +  it('should have a key `cli` from navigation.json', () => {
If we care about having it then we should put a test in the actual processor. E.g. if there is no matching node then throw an error and block the doc-gen.
Then if we really want to get rid of CLI, then we can set `processCliCommands.$enabled = false` in the `angular.io-package` setup.
We can keep a test similar to this, but instead of reading the real `navigation.json` we just test that the processor errors if there is no matching node.
Sound good?

2019-01-23 10:25 UTC, wKoza commented on aio/tools/transforms/cli-docs-package/processors/processCliCommands.spec.js
> +  it('should have a key `cli` from navigation.json', () => {
Sound good

2019-01-24 16:09 UTC, mary-poppins commented
You can preview 0c1a8c1 at https://pr28293-0c1a8c1.ngbuilds.io/.

2019-01-24 16:10 UTC, mary-poppins commented
You can preview 2e1d081 at https://pr28293-2e1d081.ngbuilds.io/.

2019-01-24 16:12 UTC, petebacondarwin approved these changes

2019-01-24 16:13 UTC, petebacondarwin requested changes
Oops I spoke too soon. The unit tests are failing due to your changes.

2019-01-24 16:14 UTC, petebacondarwin commented on aio/tools/transforms/cli-docs-package/processors/processCliCommands.js
> +      if (!navigationNode && navigationDoc) {
This should throw regardless of the existence of `navigationDoc`

2019-01-24 17:00 UTC, wKoza commented on aio/tools/transforms/cli-docs-package/processors/processCliCommands.js
> +      if (!navigationNode && navigationDoc) {
The error message says "CLI Commands must include a first child node", thus CLI commands must exist.

Furthermore `navigationDoc` had been added because it prevented to break all tests ... but I should not have deleted [this line](https://github.com/angular/angular/commit/2e1d081607624f67d30a95bbe672e078bfc0603f#diff-0bd6d2370a3881404af5d0fd92fac892L17) at the last moment. The error :(
Do you prefer that I set back this test or that I change all the tests @petebacondarwin ?

2019-01-24 19:04 UTC, mary-poppins commented
You can preview 1064643 at https://pr28293-1064643.ngbuilds.io/.

2019-01-24 19:13 UTC, mary-poppins commented
You can preview b303e7f at https://pr28293-b303e7f.ngbuilds.io/.

2019-01-24 21:08 UTC, petebacondarwin approved these changes

2019-01-24 23:43 UTC, closed without merging