fix(ivy): compile NgModule type providers without @Injectable annotation
angular/angular pull request #28331
Opened 2019-01-24 10:01 UTC by pkozlowski-opensource

Ref: FW-718

2019-01-24 10:33 UTC, petebacondarwin commented on packages/upgrade/test/BUILD.bazel
> -        "//packages/private/testing",
🥇

2019-01-24 10:34 UTC, petebacondarwin approved these changes
Woohoo! Last fixmeivy on upgrade??

2019-01-24 15:01 UTC, pkozlowski-opensource commented on packages/upgrade/test/BUILD.bazel
> -        "//packages/private/testing",
@petebacondarwin yep, this is the last test in `ngUpgrade` :-)

2019-01-24 20:21 UTC, pkozlowski-opensource commented
@JoostK yeh, there are more cases where a type with dependencies and without `@Inject` annotation can be used and still "work" in the current view engine (at least in the JIT mode), ex. https://stackblitz.com/edit/angular-gsutee?file=src%2Fapp%2Fapp.module.ts 

I'm referring to:

```javascript
{
      provide: 'service',
      useClass: Ng2Service,     
}
```

Need to test if it works in the AOT mode today....

2019-01-25 00:07 UTC, mhevery approved these changes

2019-01-25 00:18 UTC, mhevery commented
http://test/OCL:230809548:BASE:230810729:1548375474808:e52e7cde

2019-01-25 09:56 UTC, picheli20 commented on packages/core/src/di/util.ts
> +}
Just a detail, the new line on the file end :)

https://github.com/angular/angular/blob/master/.editorconfig#L10

2019-01-25 19:03 UTC, alxhub commented
(@pkozlowski-opensource and I talked about this over Slack, this is a summary of our conclusions)

While this solution would work for JIT, there's no way for the AOT compiler to support it. DI in Ivy is a runtime concept, and the AOT compiler does not introspect the providers passed to any `@NgModule`. In fact, it's impossible to do so - if you have `providers` which reference a `ModuleWithProviders` function from another module, or a constant array from another module, we don't have the information at build time.

So the correct solution here is for the user to add `@Injectable` to services they want to use via DI. This is a breaking change from View Engine in the specific cases such as this one, but the impact is expected to be minimal as most services do use `@Injectable`.

2019-01-25 19:33 UTC, alxhub requested changes
(see above)

2019-01-28 10:04 UTC, pkozlowski-opensource commented
@alxhub as discussed I've removed the traversing into providers during the JIT compilation and added `@Injectable` annotation in the test to indicate that this is required now. Please take another look and approve.

2019-01-28 19:14 UTC, alxhub approved these changes
👍

2019-01-28 20:02 UTC, closed without merging