docs: clarify angular library definition and mention angular elements
angular/angular pull request #28341
Opened 2019-01-24 16:39 UTC by FrederikSchlemmer

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #28125

## What is the new behavior?
It was explained more clearly that an Angular Library is primarily developed for the Angular Framework and can be integrated into it. Furthermore, the Angular Elements were mentioned as a framework-agnostic way.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-01-25 01:11 UTC, jenniferfell commented on aio/content/guide/libraries.md
> +Angular Libraries are intended for usage in Angular Apps and can only be used with additional effort in other projects. If the intention is to create a library in a framework-agnostic way, then [Angu
Recommended edits: 
To run, a library must be imported and used in an app.
Angular libraries are intended for use in Angular apps. ([Angular Elements](guide/elements) can be used in non-Angular web apps.)

2019-01-25 01:13 UTC, jenniferfell commented on aio/content/guide/libraries.md
> +Angular Libraries are intended for usage in Angular Apps and can only be used with additional effort in other projects. If the intention is to create a library in a framework-agnostic way, then [Angu
I'd like @jbogarthyde to also review this PR. Pondering: 
* Should this link to the glossary definition of custom elements, to stay in the context of understanding terms? 
* Should something like this also be said in the the library overview, and from there link to the Elements guide?

2019-01-25 01:14 UTC, jenniferfell requested changes
See comments inline

2019-01-31 17:59 UTC, jbogarthyde commented on aio/content/guide/libraries.md
> +Angular Libraries are intended for usage in Angular Apps and can only be used with additional effort in other projects. If the intention is to create a library in a framework-agnostic way, then [Angu
Added ref to elements in current glossary update PR
 https://github.com/angular/angular/pull/26963

2019-02-06 05:13 UTC, FrederikSchlemmer commented on aio/content/guide/libraries.md
> +Angular Libraries are intended for usage in Angular Apps and can only be used with additional effort in other projects. If the intention is to create a library in a framework-agnostic way, then [Angu
@jbogarthyde Is this PR still relevant or does your PR #28476 adopt the changes to the definition? I'm a bit confused why a new pull request was opened on the topic.

2019-02-06 16:45 UTC, jbogarthyde commented on aio/content/guide/libraries.md
> +Angular Libraries are intended for usage in Angular Apps and can only be used with additional effort in other projects. If the intention is to create a library in a framework-agnostic way, then [Angu
There was already work in progress on both the Glossary and the Libraries guide, so I added this information there. My PRs do adopt the changes you wanted, and since it is difficult to get PRs through the process, I think it's better to have it all reviewed at once.

2019-05-08 16:06 UTC, jbogarthyde commented
Please check that the new text covers the issues you raised - if so, we can close this.

2019-05-08 16:11 UTC, closed without merging