fix(ivy): verify Host Bindings and Host Listeners before compiling them
angular/angular pull request #28356
Opened 2019-01-25 01:32 UTC by AndrewKushnir

Prior to this change we may encounter some errors (like pipes being used where they should not be used) while compiling Host Bindings and Listeners. With this update we move validation logic to the analyze phase and throw an error if something is wrong. This also aligns error messages between Ivy and VE.

This PR resolves FW-725 and FW-742.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-01-25 21:33 UTC, alxhub requested changes

2019-01-25 21:33 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
> +  const errors = verifyHostBindings(bindings, null !);
1) Whenever you pass primitive arguments to a function, it's a good idea to add a comment with the argument name.
2) Make the comment here a TODO.

2019-01-25 21:33 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
> +  if (errors.length) {
Use a real check instead of shortcut code:

```suggestion
  if (errors.length > 0) {
```

2019-01-25 21:33 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
> +        ErrorCode.HOST_BINDING_PARSE_ERROR, metadata.get('host') !,
It would be nice if we could map this back to the actual host binding and not the entire object. We'll have to work on that. Please add a TODO.

2019-01-25 21:33 UTC, alxhub commented on packages/compiler/src/jit_compiler_facade.ts
> +    facade: R3DirectiveMetadataFacade, typeSourceSpan: ParseSourceSpan): R3DirectiveMetadata {
This seems wrong to me - we shouldn't be passing extra data that's not already in the facade.

2019-01-25 21:33 UTC, alxhub commented on packages/compiler/src/render3/view/compiler.ts
> +export function parseHostBindings(host: {[key: string]: string}): ParsedHostBindings {
An exported function shouldn't have a non-exported type as part of its signature. You also should export `ParsedHostBindings`.

2019-01-25 21:33 UTC, alxhub commented on packages/compiler/src/render3/view/compiler.ts
> +  // Abstract out host bindings verification logic and use it instead of
`TODO`!

2019-01-25 21:33 UTC, alxhub commented on packages/compiler/src/parse_util.ts
> +export function r3TypeSourceSpan(
I'm not sure what this function is supposed to do - return invalid `ParseSourceSpan`s?

Can you document this, and if it's only intended to work around not having proper spans, please give it a name that makes it clear it's only a temporary hack.

2019-01-25 23:03 UTC, jelbourn commented on packages/compiler-cli/src/ngtsc/diagnostics/src/code.ts
> +  HOST_BINDING_PARSE_ERROR = 5001,
I know none of the others have this, but it seems like it would be good to start a pattern of adding a more descriptive comment for these error codes (even though this one is pretty self-explanatory). I would do something like
```
// Raised when a host expression has a parse error, such as a host
// listener expression containing a pipe.
```

2019-01-25 23:03 UTC, jelbourn commented on packages/compiler/src/render3/view/compiler.ts
> +interface ParsedHostBindings {
Add a description?

2019-01-25 23:03 UTC, jelbourn commented on packages/compiler/src/render3/view/compiler.ts
> +export function verifyHostBindings(
Add a function description?

2019-01-28 22:59 UTC, AndrewKushnir commented
@alxhub, @jelbourn thanks a lot for the review and comments. I've added the necessary changes to the code to address your comments. Could you please have another look when you get a chance? Thank you.

2019-01-29 00:41 UTC, jelbourn approved these changes
LGTM

2019-01-29 19:34 UTC, alxhub approved these changes

2019-01-29 19:34 UTC, alxhub commented on packages/core/src/compiler/compiler_facade_interface.ts
> +  createTypeSourceSpan(kind: string, typeName: string, sourceUrl: string): any;
Nit: shouldn't this return `ParseSourceSpan`? And maybe be called `createParseSourceSpan`?

2019-01-29 22:31 UTC, AndrewKushnir commented on packages/core/src/compiler/compiler_facade_interface.ts
> +  createTypeSourceSpan(kind: string, typeName: string, sourceUrl: string): any;
Thanks Alex, updated!

2019-01-29 22:32 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:231474539:BASE:231474581:1548801142856:cf42fe80)

2019-01-30 00:37 UTC, closed without merging