Clarify multi project structure
angular/angular pull request #28377
Opened 2019-01-25 18:46 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number:  26254

## What is the new behavior?
Describes multiple-project file structure vs single-project structure, adds best-practice advice for multi-project workspace.
Corrects package.json file placement in multi-project workspace.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-01-25 18:51 UTC, mary-poppins commented
You can preview 788001f at https://pr28377-788001f.ngbuilds.io/.

2019-01-28 20:15 UTC, Splaktar commented on aio/content/guide/file-structure.md
> +The starter app does not have it's own `package.json` configuration file.
The previous sentence refers to the `initial app`, but this sentence refers to the `starter app`. Unless these are different things, it seems like we should use the same vocabulary.

2019-01-28 20:22 UTC, Splaktar commented on aio/content/guide/file-structure.md
> +These projects have their own `package.json` configuration files.
This is not true for application or e2e projects. Only libraries have a `package.json` file in the root of the project when generated.

2019-01-28 20:24 UTC, Splaktar commented on aio/content/guide/file-structure.md
> +Inside the `src/` folder (at the top level for a starter app, or in the `projects/` folder for additional projects), an `app/` or `lib/` folder contains your project's logic and data.
Should it be `initial app` here as well for consistency?

2019-01-28 23:00 UTC, mary-poppins commented
You can preview f9f207b at https://pr28377-f9f207b.ngbuilds.io/.

2019-01-28 23:10 UTC, mary-poppins commented
You can preview ee12f61 at https://pr28377-ee12f61.ngbuilds.io/.

2019-01-30 18:18 UTC, mary-poppins commented
You can preview 9d4f386 at https://pr28377-9d4f386.ngbuilds.io/.

2019-02-01 17:02 UTC, mary-poppins commented
You can preview b014c9a at https://pr28377-b014c9a.ngbuilds.io/.

2019-02-04 17:13 UTC, mary-poppins commented
You can preview 50fd2bc at https://pr28377-50fd2bc.ngbuilds.io/.

2019-02-05 20:16 UTC, mary-poppins commented
You can preview b1cdb1c at https://pr28377-b1cdb1c.ngbuilds.io/.

2019-02-06 16:45 UTC, mary-poppins commented
You can preview 580f18d at https://pr28377-580f18d.ngbuilds.io/.

2019-02-08 16:37 UTC, mary-poppins commented
You can preview 70046e8 at https://pr28377-70046e8.ngbuilds.io/.

2019-02-11 16:48 UTC, mary-poppins commented
You can preview fd030d2 at https://pr28377-fd030d2.ngbuilds.io/.

2019-02-12 21:39 UTC, mary-poppins commented
You can preview 9630232 at https://pr28377-9630232.ngbuilds.io/.

2019-02-13 16:58 UTC, mary-poppins commented
You can preview dab64ee at https://pr28377-dab64ee.ngbuilds.io/.

2019-02-14 17:01 UTC, mary-poppins commented
You can preview 1380835 at https://pr28377-1380835.ngbuilds.io/.

2019-02-15 16:04 UTC, mary-poppins commented
You can preview 11f8003 at https://pr28377-11f8003.ngbuilds.io/.

2019-02-18 17:12 UTC, mary-poppins commented
You can preview b0d883f at https://pr28377-b0d883f.ngbuilds.io/.

2019-02-20 18:34 UTC, mary-poppins commented
You can preview 6286e26 at https://pr28377-6286e26.ngbuilds.io/.

2019-02-21 16:11 UTC, mary-poppins commented
You can preview 185be1d at https://pr28377-185be1d.ngbuilds.io/.

2019-02-21 23:46 UTC, mary-poppins commented
You can preview 08acb62 at https://pr28377-08acb62.ngbuilds.io/.

2019-02-22 16:20 UTC, mary-poppins commented
You can preview 4250a0c at https://pr28377-4250a0c.ngbuilds.io/.

2019-02-25 17:03 UTC, mary-poppins commented
You can preview 418310a at https://pr28377-418310a.ngbuilds.io/.

2019-02-26 16:39 UTC, mary-poppins commented
You can preview dd4df83 at https://pr28377-dd4df83.ngbuilds.io/.

2019-02-27 16:34 UTC, mary-poppins commented
You can preview ddba8de at https://pr28377-ddba8de.ngbuilds.io/.

2019-02-28 16:28 UTC, mary-poppins commented
You can preview b4c3b14 at https://pr28377-b4c3b14.ngbuilds.io/.

2019-03-04 16:20 UTC, mary-poppins commented
You can preview 946e04f at https://pr28377-946e04f.ngbuilds.io/.

2019-03-05 16:16 UTC, mary-poppins commented
You can preview 344f03e at https://pr28377-344f03e.ngbuilds.io/.

2019-03-05 21:02 UTC, mary-poppins commented
You can preview 5967a13 at https://pr28377-5967a13.ngbuilds.io/.

2019-03-05 22:16 UTC, alexeagle approved these changes
Looks right to me.

@alan-agius4 has been working on the layout of apps and might have feedback

2019-03-06 07:09 UTC, alan-agius4 requested changes
Couple of small things.

I don't think this PR should be merged to `patch` as certain things are only relevant if you use version 8. As for version 7, the structure is slightly different.

2019-03-06 07:09 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +It resides in the `src/` subfolder, with tests in the `e2e/` subfolder).
I would clarify that end-to-end are in `e2e` folder, as other tests are in the feature folder.

_with tests in the `e2e/` subfolder -> with end-to-end tests in the `e2e/` subfolder._

Also there seems to be an extra `)` at the end.

2019-03-06 07:09 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
>  | `README.md`            | Introductory documentation. |
There are more workspace files, such as the default `tsconfig.json`, `angular.json` and `package.json`.

Probably it's worth mentioning them as well

2019-03-06 07:09 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
>  | `tsconfig.spec.json`  | Inherits from the workspace-wide `tsconfig.json` file. |
`tsconfig.spec.json`, `browserslist` and `tsconfig.spec.json` are outside of the App src dir. 

See 
<img width="309" alt="53824958-7e0cc380-3f75-11e9-947b-b3be7fab42f7" src="https://user-images.githubusercontent.com/17563226/53862100-76393780-3fe6-11e9-96f9-6636376ae583.png">

2019-03-06 07:09 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +    my-other-app-e2e/  (corresponding test app)
This is no longer true for version 8.

As described above, the E2E is no longer a seperate project but rather a sub directory of the application,

Example:
```
my-other-app/
  -- e2e
  ---- src
  -- (config files)
```

Also config files are outside of the `src` folder.

2019-03-06 07:09 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +The `src/` subfolder contains the source files (app logic, data, and assets), along with configuration files for the initial starter app.
This statement is not entire true, the config files are outside of the `src/` folder. See screenshot in my other comment

2019-03-06 07:13 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
>      tsconfig.e2e.json   (TypeScript config inherits from workspace tsconfig.json)
_tsconfig.e2e.json -> tsconfig.json_

2019-03-06 07:15 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
>  | `tsconfig.spec.json`  | Inherits from the workspace-wide `tsconfig.json` file. |
`tsconfig.spec.json`,`tslint.json`, `browserslist` and `tsconfig.spec.json` are outside of the App src dir. 

See 
<img width="309" alt="53824958-7e0cc380-3f75-11e9-947b-b3be7fab42f7" src="https://user-images.githubusercontent.com/17563226/53862100-76393780-3fe6-11e9-96f9-6636376ae583.png">

2019-03-06 10:21 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
>  | APP SOURCE & CONFIG FILES    | PURPOSE |
`CONFIG FILES` are not within the applications src folder, in version 8

2019-03-06 10:25 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
>  ### Default app project e2e files
E2E structure in version 8 will be the same for default applications and multi project environment.


I suggest something like

**E2E files**

An e2e/ subfolder contains configuration and source files for a set of end-to-end tests that correspond to the initial app.

```
my-app/
  e2e/                  (end-to-end tests or my-app)
    src/                (e2e source files)
    protractor.conf.js  (test-tool config)
    tsconfig.json   (TypeScript config inherits from workspace tsconfig.json
```

2019-03-06 10:27 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +
Nit: remove extra new line.

2019-03-06 10:32 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
>  ### Default app project files
_Default app project_ files -> _Application project files_

In version 8, the file layout for `default` application & application under `projects` is the same, so in theory we shouldn't deferential when explain the files.

The difference would be where the application will be located. 

For the `ng new`, it will be under the root folder of the workspace, while for `ng g app` it will be under projects (projects/myapp)

2019-03-06 10:34 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
>  ### Default app project e2e files
I reckon also, that this should be a sub heading of `Application Files`. Alternatively maybe it's best to change the heading to `Application E2E files`

2019-03-06 10:43 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +## Project files
The section here is really unclear to me. It is explaining libraries and application however the files here are related solely to an application.

IMHO I think;

- This  table, should be moved right under the application files structure table. Aka above or under this line `Applications do not have their own package.json configuration`

- This below part, should be included in the Application part instead.

> 
> Inside the src/ folder (at the top level for a starter app, or in the projects/ folder for additional projects), an app/ or lib/ folder contains your project's logic and data. Angular components, templates, and styles go here.
> 
> An assets/ subfolder contains images and anything else your app needs. Files at the top level of src/ support testing and running your app.

And removing any library references.

- Add a separate section similar to Applications files, that explains Library files, not sure if it's best in here or here https://pr28377-5967a13.ngbuilds.io/guide/creating-libraries. Anyhow, were ever it is put I think there should be a link in the other to reference it.

2019-03-06 19:14 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +
Not sure what you mean- which extra new line?

2019-03-06 19:45 UTC, jbogarthyde commented
Re-organized for v8 structure - @alan-agius4 please check.

2019-03-06 19:49 UTC, mary-poppins commented
You can preview 0107b2e at https://pr28377-0107b2e.ngbuilds.io/.

2019-03-07 07:46 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `tsconfig.spec.json`     | [TypeScript](https://www.typescriptlang.org/) configuration for the default app, including TypeScript and Angular template compiler options. See [TypeScript Configuration
[TypeScript](https://www.typescriptlang.org/) configuration for the default app tests. See [TypeScript Configuration](guide/typescript-configuration

2019-03-07 07:49 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `assets/*`                  | Contains image files and other asset files to be copied as-is when you build your application. |
Nit: For consistency it'd remove the `*` here as other folder end with `/`

Maybe change?
_Contains image files and other asset files_ -> _Contains image and other asset files_

2019-03-07 07:51 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +For a single-app workspace, the `src/` folder contains the source and configuration files for the root app.
For a single-app workspace, the `src/` folder contains the source ~~and configuration files~~ for the root app.

2019-03-07 07:52 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
>  | APP SOURCE & CONFIG FILES    | PURPOSE |
APP SOURCE & CONFIG FILES -> APP SOURCE

2019-03-07 07:54 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +
this seems to be breaking the table in the preview 

![image](https://user-images.githubusercontent.com/17563226/53940677-90424b00-40b6-11e9-827e-c332f405e68d.png)

2019-03-07 07:55 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +For a single-app workspace, the `src/` folder contains the source and configuration files for the root app.
Unless configuration is meant to also include `environments` this should be changed to For a single-app workspace, the `src/` folder contains the source ~~and configuration files~~ for the root app.

2019-03-07 07:56 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
>  | APP SOURCE & CONFIG FILES    | PURPOSE |
Unless configuration is meant to also include `environments`. This should be changed to `APP SOURCE`

2019-03-07 07:56 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +  e2e/
Nit: can we make the text in brackets aligned?
![image](https://user-images.githubusercontent.com/17563226/53940840-ee6f2e00-40b6-11e9-992f-75397437a267.png)

2019-03-07 08:04 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
>    projects/           (additional apps and libs)
This is a bit hard to comprehend when viewing it in AIO
![image](https://user-images.githubusercontent.com/17563226/53940897-0ba3fc80-40b7-11e9-89a3-57eb8328cc89.png)

Also the structure is not correct.

See below.
```
my-app/
  ...
  projects/                (additional apps and libs)
    my-other-app/          (a second app)
      ...                  (app-specific config)
      e2e/                 (corresponding e2e tests)
              src/         (e2e tests source files)
              ...          (e2e specific config)
      src/                 (source files for app)
    my-lib/                (a generated library)
      ...                  (library specific config files)
```

2019-03-07 08:05 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +     src/               (end-to-end test app for my-app)
_(end-to-end test app for my-app_) -> _(end-to-end test files for my-app)_

the E2E is not longer a seperate app.

2019-03-07 08:07 UTC, alan-agius4 commented
Hi @jbogarthyde, this is coming together really well. Just a couple of more small issues.

2019-03-07 16:22 UTC, mary-poppins commented
You can preview d7fd286 at https://pr28377-d7fd286.ngbuilds.io/.

2019-03-07 16:55 UTC, mary-poppins commented
You can preview 1f4aeb8 at https://pr28377-1f4aeb8.ngbuilds.io/.

2019-03-07 16:56 UTC, mary-poppins commented
You can preview 6910897 at https://pr28377-6910897.ngbuilds.io/.

2019-03-07 17:35 UTC, mary-poppins commented
You can preview 65e92f2 at https://pr28377-65e92f2.ngbuilds.io/.

2019-03-07 19:13 UTC, mary-poppins commented
You can preview d9c9a94 at https://pr28377-d9c9a94.ngbuilds.io/.

2019-03-08 07:42 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +     src/                 (end-to-end testsfor my-app)
Nit: missing space between `tests` and `for`

2019-03-08 07:48 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| APP SUPPORT FILES    | PURPOSE |
_APP SUPPORT FILES_ -> APP SOURCE FILES

2019-03-08 07:48 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +### Application support files
_Application support files -> Application source files_

2019-03-08 07:48 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +Project-specific [TypeScript](https://www.typescriptlang.org/) configuration files inherit from the workspace-wide `tsconfig.*.json`, and project-specific [TSLint](https://palantir.github.io/tslint/)
_tsconfig.*.json -> tsconfig.json,_

2019-03-08 08:01 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `browserslist`          | Configures sharing of target browsers and Node.js versions among various front-end tools. See [Browserslist on GitHub](https://github.com/browserslist/browserslist) for mo
I am uncertain of adding `browserslist`, `karma.conf.json`, `tsconfig.app.json`. `tsconfig.spec.json` in here. As these are not workspace config file but rather specific to the application, which happens that for the default application, there are in the root.

If we amend this a bit, we can cover, file structures for both the default application, or when you want to have a mono-repo style aka, multiple apps residing under `projects/`

My suggestions would be:

```
## Workspace configuration files

 All projects within a workspace share a [CLI configuration context](guide/workspace-config).
The top level of the workspace contains workspace-wide configuration files.

 WORKSPACE CONFIG FILES    | PURPOSE |
| :--------------------- | :------------------------------------------|
| `node_modules/`        | Provides [npm packages](guide/npm-packages) to the entire workspace. Workspace-wide `node_modules` dependencies are visible to all applications and e2e projects. |
| `.editorconfig`        | Configuration for code editors. See [EditorConfig](https://editorconfig.org/). |
| `.gitignore`           | Specifies intentionally untracked files that [Git](https://git-scm.com/) should ignore. |
| `angular.json`         | CLI configuration defaults for all projects in the workspace, including configuration options for build, serve, and test tools that the CLI uses, such as [TSLint](https://palantir.github.io/tslint/), [Karma](https://karma-runner.github.io/), and [Protractor](http://www.protractortest.org/). For details, see [Angular Workspace Configuration](guide/workspace-config). |
| `package.json`          | Configures [npm package dependencies](guide/npm-packages) that are available to all projects in the workspace. See [npm documentation](https://docs.npmjs.com/files/package.json) for the specific format and contents of this file. |
| `package-lock.json`     | Provides version information for all packages installed into `node_modules` by the npm client. See [npm documentation](https://docs.npmjs.com/files/package-lock.json) for details. If you use the yarn client, this file will be [yarn.lock](https://yarnpkg.com/lang/en/docs/yarn-lock/) instead. |
| `README.md`             | Introductory documentation for the root app. |
| `tsconfig.json`         | Default [TypeScript](https://www.typescriptlang.org/) configuration for projects in the workspace. |
| `tslint.json`           | Default [TSLint](https://palantir.github.io/tslint/) configuration for projects in the workspace. |
```

Right above `### Application support files`



### Application config files
The app-specific configuration files for the root app reside at the workspace root level. For a multi-project workspace, app-specific configuration are in root of `project-name/` under `projects/`.

```
 APP CONFIG FILES    | PURPOSE |
| :--------------------- | :------------------------------------------|
| `browserslist`          | Configures sharing of target browsers and Node.js versions among various front-end tools. See [Browserslist on GitHub](https://github.com/browserslist/browserslist) for more information.  |
| `karma.conf.json`       | [Karma](https://karma-runner.github.io/2.0/config/configuration-file.html) configuration for the root application. |
| `tsconfig.app.json`     | [TypeScript](https://www.typescriptlang.org/) configuration for the app, including TypeScript and Angular template compiler options. See [TypeScript Configuration](guide/typescript-configuration). |
| `tsconfig.spec.json`     | [TypeScript](https://www.typescriptlang.org/) configuration for the app tests. See [TypeScript Configuration](guide/typescript-configuration). |
| `tslint.json`           | [TSLint](https://palantir.github.io/tslint/) app specific lint configuration. |
```

2019-03-08 08:04 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `browserslist`          | Configures sharing of target browsers and Node.js versions among various front-end tools. See [Browserslist on GitHub](https://github.com/browserslist/browserslist) for mo
Also kindly note: that `karma.conf.json` should be `karma.conf.js`

2019-03-08 08:12 UTC, alan-agius4 commented
Not need to do it for this PR, but it's good to keep it in mind. I would really like to standardize the terms so we also use to refer to an `application` and `library`. For consistency, when referring to an application we should use either `app` or `application` and for library either `lib` or `library`

IMHO, I would go for the complete word instead of the abbreviations in documentation.

2019-03-08 16:44 UTC, mary-poppins commented
You can preview ffce46e at https://pr28377-ffce46e.ngbuilds.io/.

2019-03-08 17:05 UTC, mary-poppins commented
You can preview 321e9d2 at https://pr28377-321e9d2.ngbuilds.io/.

2019-03-09 10:57 UTC, alan-agius4 approved these changes
@jbogarthyde, this is really good. 

LGTM, just one small nit.

2019-03-09 10:57 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `node_modules/`        | Provides [npm packages](guide/npm-packages) to the entire workspace. Workspace-wide `node_modules` dependencies are visible to all applications and e2e projects. |
_ visible to  all applications and e2e projects._ -> visible to all projects.

2019-03-09 10:57 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +For more information about the library project structure, see [Creating Libraries](https://angular.io/guide/creating-libraries).
Is there a follow up tasks to add library project structure?

2019-03-09 11:09 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +<div class="callout is-helpful">
shouldn't this be an `alert`, or otherwise if this is supposed to the a callout the title should be an a `<header>` tag

2019-03-11 15:44 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +For more information about the library project structure, see [Creating Libraries](https://angular.io/guide/creating-libraries).
I'll file an issue to add this to the [Creating Libraries](https://angular.io/guide/creating-libraries) page. Can you get me the information, or point me to an example? Will it change for v8?

2019-03-11 15:46 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +<div class="callout is-helpful">
The title is H3. Do you think it should be something else?

2019-03-11 15:47 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +For more information about the library project structure, see [Creating Libraries](https://angular.io/guide/creating-libraries).
No, it should change in version 8

2019-03-11 15:48 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +<div class="callout is-helpful">
In callouts unless there is a `header` tags the titles doesn’t seem to have the correct padding.

2019-03-11 16:03 UTC, mary-poppins commented
You can preview 7c2d4ec at https://pr28377-7c2d4ec.ngbuilds.io/.

2019-03-11 16:04 UTC, mary-poppins commented
You can preview 513b4a4 at https://pr28377-513b4a4.ngbuilds.io/.

2019-03-11 16:13 UTC, mary-poppins commented
You can preview f580363 at https://pr28377-f580363.ngbuilds.io/.

2019-03-11 17:11 UTC, mary-poppins commented
You can preview b914a35 at https://pr28377-b914a35.ngbuilds.io/.

2019-03-12 15:18 UTC, mary-poppins commented
You can preview f30c6eb at https://pr28377-f30c6eb.ngbuilds.io/.

2019-03-12 17:03 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| APP SUPPORT FILES    | PURPOSE |
This is still pending.

2019-03-12 19:14 UTC, mary-poppins commented
You can preview 12652b5 at https://pr28377-12652b5.ngbuilds.io/.

2019-03-12 21:19 UTC, alexeagle approved these changes

2019-03-12 21:20 UTC, alexeagle commented
Caretaker: merge assistance because this tripped over the
```
Commit 12652b51bddd3eadaf3ca09533ede668c8c6e095 uncompressed main exceeded expected size by >1% (expected: 209904, actual: 212976).
If this is a desired change, please update the size limits in file '/home/circleci/ng/integration/../integration/_payload-limits.json'.
Exited with code 1
```
problem that's already fixed at HEAD

2019-03-13 01:07 UTC, closed without merging

2019-03-25 05:36 UTC, Splaktar commented on aio/content/guide/file-structure.md
> +and for enterprises that use a "mono-repo" development style, with a single repository and global configuration for all Angular projects.
I assume that "mono-repo" is correct grammatically. However, in actual use there are a lot of references to "monorepo" like https://en.wikipedia.org/wiki/Monorepo. Should we mention "monorepo" here somewhere as an alternative spelling so that people searching for "monorepo" will find this?

Currently searching https://next.angular.io for "mono-repo" shows this guide as a result, but searching for "monorepo" gives no results in the Angular docs.