fix(bazel): Fix appending bazel-out to gitignore
angular/angular pull request #28385
Opened 2019-01-26 01:25 UTC by kyliau

The current implementation appends '/bazel-out' to the wrong location
in the .gitignore file. This PR fixes that and adds a stricter test.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-01-26 01:43 UTC, mgechev commented on packages/bazel/src/schematics/ng-new/index.ts
> +    if (gitIgnoreContent.includes('/bazel-out')) {
If we drop the `\n` suffix `.includes('/bazel-out-foo')` will also return true; why do we have to remove it?

2019-01-27 05:22 UTC, IgorMinar requested changes

2019-01-28 18:42 UTC, kyliau commented on packages/bazel/src/schematics/ng-new/index.ts
> +    if (gitIgnoreContent.includes('/bazel-out')) {
Modified the code to check for start and end lines. The gitignore file is generated by the `ng new` template, and in schematics all templates have '\r' endings only.

2019-01-28 18:43 UTC, kyliau commented on packages/bazel/src/schematics/ng-new/index_spec.ts
> +    expect(content).toMatch('# compiled output\n/bazel-out');
done

2019-01-28 18:44 UTC, kyliau commented on packages/bazel/src/schematics/ng-new/index.ts
> + * Apend '/bazel-out' to the gitignore file.
thanks for the correction.

2019-01-28 19:12 UTC, gkalpak commented on packages/bazel/src/schematics/ng-new/index.ts
> +    recorder.insertRight(insertionIndex, '/bazel-out\n');
This assumes that the file ends with a newline. Is this guaranteed to be the case?

2019-01-28 19:20 UTC, kyliau commented on packages/bazel/src/schematics/ng-new/index.ts
> +    recorder.insertRight(insertionIndex, '/bazel-out\n');
Yes, please see the comment in https://github.com/angular/angular/pull/28385#discussion_r251542430

tldr:  The gitignore file is generated by the ng new template, and in schematics all templates have '\r' endings only.

2019-01-28 21:42 UTC, kyliau commented on packages/bazel/src/schematics/ng-new/index.ts
> +    recorder.insertRight(insertionIndex, '/bazel-out\n');
ah, yes, I meant `\n` line endings.

1. The templates end each line with a line ending
Yes, because this code is run immediately after the original `ng new` is run, it's effectively modifying this template [file](https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/workspace/files/__dot__gitignore.template).

2. There is no way the file could have been updated since its creation
Same argument as above

i.e. This is an extension to the original `ng new` and it's modifying the template output of the schematic.

2019-01-29 09:21 UTC, gkalpak commented on packages/bazel/src/schematics/ng-new/index.ts
> +    recorder.insertRight(insertionIndex, '/bazel-out\n');
Hm...In that case, why not assume that `# compiled output` will always exist?

2019-01-29 18:01 UTC, kyliau commented on packages/bazel/src/schematics/ng-new/index.ts
> +    recorder.insertRight(insertionIndex, '/bazel-out\n');
that is party to make the implementation more robust. In case upstream `ng new` changes the template, this implementation would just append the line to the end of the file.

2019-02-05 19:45 UTC, kyliau commented
Changes have been incorporated into https://github.com/angular/angular/pull/28436 as part of a major refactoring of `@angular/bazel`.

2019-02-05 19:45 UTC, closed without merging