fix(ivy): remove DOM nodes from their real parent vs saved parent
angular/angular pull request #28455
Opened 2019-01-30 18:26 UTC by jelbourn

Currently, DOM node removal called `removeChild` on the saved parent
node when destroying a component. However, this will fail if the
component has been manually moved in the DOM. This change makes the
removal always use the node's real `parentNode` and ignore the provided
`parent`.

Reference: FW-977

2019-01-30 20:15 UTC, kara requested changes

2019-01-30 20:15 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> +    renderer.removeChild(parent as RElement, child, isHostElement);
Could we not pass in `child.parentNode` here and avoid changing implementation of the dom renderer?

2019-01-30 20:15 UTC, kara commented on packages/core/test/render3/view_container_ref_spec.ts
> +        // Manually nove the loaded component to some arbitrary DOM node.
```suggestion
        // Manually move the loaded component to some arbitrary DOM node.
```

2019-01-30 20:31 UTC, JoostK commented on packages/core/src/render3/node_manipulation.ts
> +    renderer.removeChild(parent as RElement, child, isHostElement);
There's a helper fn `nativeParentNode` that seems appropriate to use here. That would also correspond with ViewEngine logic:

https://github.com/angular/angular/blob/885f1af509eb7d9ee049349a2fe5565282fbfefb/packages/core/src/view/util.ts#L268-L270

2019-01-30 20:41 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> +    renderer.removeChild(parent as RElement, child, isHostElement);
Yeah, seems like we could do this as well, if that's what you mean:

```ts
renderer.removeChild(renderer.parentNode(child), child, isHostElement);
```

2019-01-31 15:20 UTC, pkozlowski-opensource commented on packages/core/test/render3/view_container_ref_spec.ts
> +  describe('with manually moved nodes', () => {
I would rather write this test as a `TestBed` test as it would be less brittle.

2019-01-31 15:23 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +  if (isProceduralRenderer(renderer)) {
If we do this logic here in nativeRemoveChild it will mean that we still execute all the logic to find a logical render parent and this is useless. I would rather modify the `removeChild` function and there lookup a parent from the DOM, instead of executing `const parentNative = getRenderParent(childTNode, currentView);`

Then the `null` check be in there as well and you wouldn't need to modify renderer

2019-01-31 15:25 UTC, pkozlowski-opensource requested changes
I think that we should rather:
* modify the `removeChild` function (see my in-line comments);
* have a `TestBed` test on top of / instead of renderer3 runtime test

Happy to help if needed but I would like to very much avoid the situation where we do _both_ logical render parent lookup _and_ lookup in the DOM.

2019-01-31 22:55 UTC, jelbourn commented on packages/core/src/render3/node_manipulation.ts
> +  if (isProceduralRenderer(renderer)) {
This is what I originally had and @kara asked to change it. @kara what are your thoughts here?

2019-01-31 22:56 UTC, jelbourn commented on packages/core/test/render3/view_container_ref_spec.ts
> +  describe('with manually moved nodes', () => {
I wasn't aware that was even an option. Just using TedBed in this same spec?

2019-02-01 03:35 UTC, kara commented on packages/core/test/render3/view_container_ref_spec.ts
> +  describe('with manually moved nodes', () => {
It would probably be cleaner to add it to an existing TestBed spec file. I think in this case `view_injector_integration_spec.ts` would be the best one.

2019-02-01 03:38 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> +  if (isProceduralRenderer(renderer)) {
@jelbourn I believe @pkozlowski-opensource is actually talking about our version of `removeChild` here:
https://github.com/angular/angular/blob/master/packages/core/src/render3/node_manipulation.ts#L696

I'd agree with him that we should update that function to remove the logic that finds the render parent.

2019-02-01 23:56 UTC, jelbourn reviewed
Comments addressed, let me know what you think

2019-02-01 23:56 UTC, jelbourn commented on packages/core/src/render3/node_manipulation.ts
> +  if (isProceduralRenderer(renderer)) {
I totally misread Pawel's original comment; I hadn't seen that `getRenderParent` function earlier. 

In making the change to avoid calling that, I didn't want to move the "get parent node" bit into `removeChild` because then `nativeRemoveChild` would have the assumption that it's the right parent node baked into it. So, I instead changed `removeChild` to `removeNode` and made it just a pass-through to `nativeRemoveChild`, which also now does not have `parent` in its arguments. 

Let me know what you think.

2019-02-04 09:52 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +    // We intentionally don't use the given parent node since it may no longer
So the idea behind the `native[...]()` functions in this file that those are here to basically abstract a renderer type being used. So far those functions didn't have any logic and I would love to keep it this way.

I would rather prefer that we keep `nativeRemoveChild` "dumb" and move all the "logic" into the `removeChild` function. I find this approach easier to follow and IMO the code is shorter / simpler (less checks / branching logic).

I've pushed a fixup commit https://github.com/angular/angular/pull/28455/commits/4d7d430efb7e939ca16331145406e5add999ea36 to your  branch with the changes I'm describing above, please review.

2019-02-04 09:52 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +export function removeNode(childTNode: TNode, childEl: RNode, currentView: LView): void {
Actually, I've pushed a fixup commit https://github.com/angular/angular/pull/28455/commits/4d7d430efb7e939ca16331145406e5add999ea36 to your  branch with the changes I'm describing above, please review.

2019-02-04 14:02 UTC, ocombe approved these changes

2019-02-04 15:22 UTC, kara approved these changes
LGTM

2019-02-04 15:27 UTC, pkozlowski-opensource approved these changes
LGTM with the fixup commit but we can iterate more if @jelbourn has objections

2019-02-05 00:04 UTC, jelbourn commented
I'm good with the proposed changes

2019-02-05 19:58 UTC, matsko commented
http://test/OCL:232530052:BASE:232530123:1549396551445:4021aaca

2019-02-06 04:30 UTC, closed without merging