WIP: docs(docs-infra): build examples with Ivy
angular/angular pull request #28463
Opened 2019-01-31 05:39 UTC by brandonroberts

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-01-31 05:44 UTC, mary-poppins commented
You can preview 473dff2 at https://pr28463-473dff2.ngbuilds.io/.

2019-01-31 06:10 UTC, mary-poppins commented
You can preview ed56d95 at https://pr28463-ed56d95.ngbuilds.io/.

2019-02-01 16:53 UTC, mary-poppins commented
You can preview 9a72f1e at https://pr28463-9a72f1e.ngbuilds.io/.

2019-02-01 20:41 UTC, mary-poppins commented
You can preview f37351a at https://pr28463-f37351a.ngbuilds.io/.

2019-02-01 20:42 UTC, mary-poppins commented
You can preview d43b0b2 at https://pr28463-d43b0b2.ngbuilds.io/.

2019-02-04 13:20 UTC, mary-poppins commented
You can preview 4bdecd1 at https://pr28463-4bdecd1.ngbuilds.io/.

2019-02-04 15:34 UTC, mary-poppins commented
You can preview 6e59f45 at https://pr28463-6e59f45.ngbuilds.io/.

2019-02-04 16:32 UTC, mary-poppins commented
You can preview 0e89204 at https://pr28463-0e89204.ngbuilds.io/.

2019-02-04 18:05 UTC, mary-poppins commented
You can preview 2378682 at https://pr28463-2378682.ngbuilds.io/.

2019-02-05 15:49 UTC, ocombe commented
You can't run i18n code with ivy until this is resolved: https://angular-team.atlassian.net/browse/FW-1026
We need to polyfill the runtime service for now.

2019-02-05 16:18 UTC, mary-poppins commented
You can preview ea55d46 at https://pr28463-ea55d46.ngbuilds.io/.

2019-02-05 19:17 UTC, mary-poppins commented
You can preview 2d02433 at https://pr28463-2d02433.ngbuilds.io/.

2019-02-05 19:48 UTC, mary-poppins commented
You can preview ae3e922 at https://pr28463-ae3e922.ngbuilds.io/.

2019-02-06 14:55 UTC, IgorMinar requested changes
Can you add a better commit message please, we really need to get better at describing the changes and especially mentioning why we are making certain changes because that helps everyone understand our changes better. We can't assume that everyone reading the commit knows why we made this change. Thanks!

Otherwise this looks really good! I assume that the "ignored" tests are tests that are currently failing with ivy? Can you please clarify?

2019-02-06 14:55 UTC, IgorMinar commented on .circleci/config.yml
> +      - *yarn_install
we made a bunch of changes to all jobs in upstream (we now download and install yarn) - please rebase and add the missing step if necessary.

2019-02-06 14:55 UTC, IgorMinar commented on aio/content/examples/dependency-injection/src/app/heroes/hero.service.provider.ts
> +  return heroService;
why this change? seems unnecessary. if it's unrelated to ivy then please move it to a separate commit. If ivy requires this change then we shouldn't make it and instead surface this as a bug in ivy.

in general we should try to not make any changes to an existing app code to make ivy work because we are just working around regressions that our customers will see.

2019-02-06 14:55 UTC, IgorMinar commented on aio/content/examples/dependency-injection/src/app/heroes/hero.service.ts
> +    private logger: Logger) { }
same as above...

2019-02-06 14:55 UTC, IgorMinar commented on aio/content/examples/dependency-injection/src/app/tree-shaking/service.0.ts
> +  constructor(@Inject(DEP_TOKEN) private dep: string) {
same as above

2019-02-06 14:55 UTC, IgorMinar commented on aio/content/examples/forms/src/app/hero-form/hero-form.component.html
> +      <form>
same as above

2019-02-06 14:55 UTC, IgorMinar commented on aio/content/examples/styleguide/src/01-01/app/heroes/hero.component.avoid.ts
> +  styleUrls: ['../app.component.css']
was this a bug in the app or a breaking change in ivy?

2019-02-06 14:55 UTC, IgorMinar commented on aio/content/examples/styleguide/src/02-07/app/heroes/hero.component.avoid.ts
> +  template: ''
is this a breaking change in ivy? if so, we need to fix it and not break the app.

2019-02-06 14:55 UTC, IgorMinar commented on aio/tools/examples/run-example-e2e.js
> +const IGNORED_IVY_EXAMPLES = [
can you document why they are being ignored please? if this is due to bugs, we should file a jira ticket and point @kara to it.

2019-02-06 14:55 UTC, IgorMinar commented on aio/tools/examples/run-example-e2e.js
> +  log.push('Suites ignored:');
maybe also mention why in the stdout so that it's clear. ignoring tests is a scary thing :)

2019-02-06 14:55 UTC, IgorMinar commented on aio/tools/examples/shared/boilerplate/ivy/cli/src/tsconfig.app.json
> +    "allowEmptyCodegenFiles": true
is this to enable shims? if so, we should add a todo and file an issue/jira ticket to remove this before v8 launch because we'd prefer to launch with shims turned off by default. but it is ok to merge this PR initially with shims if that makes more tests pass.

2019-02-06 14:55 UTC, IgorMinar commented on aio/tools/examples/shared/package.json
> +    "angular-in-memory-web-api": "github:brandonroberts/in-memory-web-api-bazel#50a34d8",
why do we need this?

2019-02-06 16:30 UTC, kara requested changes

2019-02-06 16:30 UTC, kara commented on aio/tools/examples/run-example-e2e.js
> +const IGNORED_IVY_EXAMPLES = [
Rather than filing Jira tickets, can you instead put a comment above each of these example names that says "fixmeIvy('unknown')" ? We shouldn't file Jira tickets until someone on Ivy does root cause analysis.

2019-02-06 16:30 UTC, kara commented on aio/content/examples/dependency-injection/src/app/heroes/hero.service.provider.ts
> +  return heroService;
+1

2019-02-08 16:22 UTC, brandonroberts commented on aio/tools/examples/shared/boilerplate/ivy/cli/src/tsconfig.app.json
> +    "allowEmptyCodegenFiles": true
This is necessary for lazy loading to work per https://github.com/angular/angular-cli/pull/13524

2019-02-08 16:24 UTC, brandonroberts commented on aio/tools/examples/shared/package.json
> +    "angular-in-memory-web-api": "github:brandonroberts/in-memory-web-api-bazel#50a34d8",
I've filed an issue here https://github.com/angular/angular/issues/28603. The current release of `angular-in-memory-web-api` `0.8.0` doesn't work with ivy/ngtsc.

2019-02-08 16:27 UTC, brandonroberts commented on aio/content/examples/dependency-injection/src/app/heroes/hero.service.provider.ts
> +  return heroService;
The previous code doesn't work with version 7 and AoT enabled, and I couldn't find any tests that validate that it should.

2019-02-08 17:00 UTC, mary-poppins commented
You can preview 0f37ea0 at https://pr28463-0f37ea0.ngbuilds.io/.

2019-02-08 17:02 UTC, mary-poppins commented
You can preview 86bfb95 at https://pr28463-86bfb95.ngbuilds.io/.

2019-02-08 17:06 UTC, mary-poppins commented
You can preview 4cb738d at https://pr28463-4cb738d.ngbuilds.io/.

2019-02-08 18:04 UTC, mary-poppins commented
You can preview 98d3926 at https://pr28463-98d3926.ngbuilds.io/.

2019-02-08 18:05 UTC, mary-poppins commented
You can preview 0739323 at https://pr28463-0739323.ngbuilds.io/.

2019-02-08 18:05 UTC, mary-poppins commented
You can preview 0517871 at https://pr28463-0517871.ngbuilds.io/.

2019-02-08 18:31 UTC, mary-poppins commented
You can preview f514575 at https://pr28463-f514575.ngbuilds.io/.

2019-02-08 22:38 UTC, kara approved these changes
LGTM

2019-02-09 06:53 UTC, IgorMinar commented on aio/tools/examples/shared/boilerplate/ivy/cli/src/tsconfig.app.json
> +    "allowEmptyCodegenFiles": true
ah. right. thnx!

2019-02-09 06:55 UTC, IgorMinar approved these changes
thanks!

2019-02-11 14:31 UTC, brandonroberts commented
Caretaker note: https://github.com/angular/angular/pull/28592 should land before this one as it may need a rebase.

2019-02-11 17:18 UTC, closed without merging

2019-02-12 08:03 UTC, gkalpak commented on .circleci/config.yml
> +            # Get the artifacts to publish from the build-packages-dist job
Ooops!

2019-02-12 08:13 UTC, gkalpak commented on aio/tools/examples/example-boilerplate.js
> +      shelljs.exec(`yarn --cwd ${SHARED_PATH} ivy-ngcc`);
Oh, so this means that once you run examples with ivy, they will silently stay that way until you re-install `node_modules/`.
Let's hope people don't need to do this locally :grin:

2019-02-12 08:15 UTC, gkalpak commented on aio/tools/examples/run-example-e2e.js
> +    log.push('Suites ignored due to breakage with Ivy:');
❤️