Rename blacklist/whitelist to blocklist/safelist
angular/angular pull request #28529
Opened 2019-02-04 22:10 UTC by benlesh

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This PR renames all uses of "blacklist" and "whitelist" to "blocklist" and "safelist".

The Angular team is committed to making sure this is an inclusive environment for all. This PR is not about the origins of the phrases, rather it's about making everyone feel welcome and comfortable while reading our code base. 

**NOTE: This PR is blocked on a yet-to-be-filed PR to angular material, which needs to update a generated filename**

2019-02-05 14:33 UTC, SebastianPodgajny commented
That's amazing, but why you want to merge it to MASTER branch? I find it offensive 😞 and there is a lot of `master` in this repository MasterService, MasterFlag, MasterConfig it is notappropriatee name in 2019 in my opinion. Maybe we should change it to leader (leader branch, leader service etc) that is more welcoming.
Also `RubberMan` from ToH should be changed to `RubberPerson` also `son` it's not ideal part maybe `RubberPerchild` that's better 🙂

2019-02-05 14:44 UTC, skreborn commented
Personal opinions aside - as it is up to the Angular team to decide their preferences on this matter -, I don't believe "safelist" is a viable alternative to "whitelist". The latter word is simply more versatile in meaning, while the former makes it difficult to understand its purpose in some cases.

A whitelisted item can give you access, permissions, exception, safety, and a number of other things. On the other hand, a safelist implies only one of those.

2019-02-05 15:07 UTC, SebastianPodgajny commented
Of Course that is only my opinion and Angular team will decide, but i wanted to express it as it relates to this topic

2019-02-05 15:16 UTC, alfaproject commented
I respect and commend any effort on inclusivity. I'm glad more organizations are doing it, but in this particular case, isn't it a bit too farfetched?

In any case, why not consider other alternatives for some of those cases like `includes`/`excludes` since it's basically what those lists are for: either to include and accept something or exclude and not accept something. `block`/`safe` seem to have a stronger semantic meaning that doesn't really suit in a lot of those replacements. I don't think search/replace is a good thing for this change.

2019-02-05 16:12 UTC, ericmartinezr commented
I would label it as "risk: high" since if sjw dont like this all of our careers and our phisycal integrity are in great danger

2019-02-05 18:44 UTC, jenniferfell commented
> I respect and commend any effort on inclusivity. I'm glad more organizations are doing it, but in this particular case, isn't it a bit too farfetched?
> 
> In any case, why not consider other alternatives for some of those cases like `includes`/`excludes` since it's basically what those lists are for: either to include and accept something or exclude and not accept something. `block`/`safe` seem to have a stronger semantic meaning that doesn't really suit in a lot of those replacements. I don't think search/replace is a good thing for this change.

To be clear, my thumbs up here is not that this request is farfetched. I think it's a reasonable request. My thumbs up is to include/exclude, which I agree are more neutral in tone than block/safe. But I defer to the technical intent re the strength of terms chosen.

2019-02-06 23:31 UTC, robwormald commented
Reminder to all on Angular's [Code of Conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md) 

> Communication through any of Angular's channels (GitHub, Gitter, IRC, mailing lists, Google+, Twitter, etc.) must be constructive and never resort to personal attacks, **trolling**, public or private harassment, insults, or other unprofessional conduct.

Please keep all feedback on-topic and constructive.

2019-02-06 23:56 UTC, SebastianPodgajny commented
Yes my comment was a joke, but I want to make a point by showing where it is going, blacklist is blacklist word used in industry for years and I don't see anything wrong with it. I really admire all of you and yours work on this framework, please don't take this framework into this political games.

Why `black` in a word is not welcoming and not comfortable?
Is blacksmith, blackmail and blackjack banned words in USA already?

2019-02-07 00:11 UTC, robwormald commented
@SebastianPodgajny if you'd like to discuss this further, you are welcome to email me - robwormald at google dot com, and I'm happy to explain our rationale behind making changes like this, and also why comments and trolling like yours are unhelpful and counterproductive to our project and community. 

Pull Requests are not the place. Final Warning.

2019-02-07 00:29 UTC, benlesh commented
The readability of the variable names we choose is a valid concern. However we cannot return to "whitelist" or "blacklist", that's not an option.

Going forward, we will just need to use names that are appropriate that are _not_ "whitelist" or "blacklist". So we might have "approvedList", "bannedList", "safeList", "accessList", etc. Whatever makes the most sense.

To reiterate, **"blacklist" and "whitelist" are off the table, and will not return**. I think we can come up with better, more descriptive names for such lists anyhow.

2019-02-07 01:30 UTC, alfaproject commented
@benlesh that's basically my point. I don't think a blind search/replace will do any good. If it's being changed now, please take a proper look at the contextual uses of the replacements.

P.S.: `blocklist` is really bad by the way and it almost sounds like you know what.

2019-02-14 23:09 UTC, benlesh commented
presubmit at:  http://test/OCL:234037925:BASE:234037977:1550185741537:eb43f3d1

2019-02-15 11:07 UTC, skreborn requested changes
I believe this is going in a much better direction than initially, but there are still a few things to look at.

- There are a _lot_ of unnecessary white-space changes included in this PR. I'm guessing that this is due to an automatic formatter, but maybe we should consider excluding them unless they improve upon the code.

-  Zone.js-private variables are renamed but these changes are not supported on the [other side](https://github.com/angular/zone.js/blob/master/lib/browser/browser.ts#L56).

- There is also something going on with the polyfills file, which I just don't understand at all. Why were those changes made at all? Why the separation of files, and why did you extend the description? I believe it was perfectly good as it was, but I'm open to a conversation if you have a valid argument.

2019-02-15 11:07 UTC, skreborn commented on packages/platform-browser/test/dom/events/event_manager_spec.ts
> +    it('should run disallowedEvents handler outside of ngZone', () => {
It's called "disabled" above, but here it's "disabled". Aren't those two the same? If so, we should probably use only one of these terms (preferably "disallowed").

2019-02-15 11:07 UTC, skreborn commented on packages/platform-browser/testing/src/browser_util.ts
> +const _safeTags = ['br', 'hr', 'input'];
Should call this `_emptyTags` or `_voidTags`, as single-tag elements are usually either called empty or void elements.

2019-02-15 11:07 UTC, skreborn commented on test-events.js
> -Zone[Zone.__symbol__('BLACK_LISTED_EVENTS')] = ['scroll'];
zone.js support

2019-02-15 11:07 UTC, skreborn commented on tools/material-ci/angular_material_test_blocklist.js
> +window.testBlockList = {
Why was the capitalization changed here?

2019-02-19 23:52 UTC, IgorMinar reviewed
this PR needs some work but overall looks good. please clean it up.

2019-02-19 23:52 UTC, IgorMinar commented on aio/tools/examples/shared/boilerplate/cli/src/polyfills.ts
> + * because those flags need to be set before `zone.js` being loaded, and webpack
has this change been upstreamed to the CLI repo?

2019-02-19 23:52 UTC, IgorMinar commented on aio/tools/examples/shared/boilerplate/cli/src/polyfills.ts
> + * because those flags need to be set before `zone.js` being loaded, and webpack
I think @skreborn is right that this change seems unnecessary. can you explain?

2019-02-19 23:52 UTC, IgorMinar commented on aio/tools/transforms/angular-base-package/processors/createSitemap.js
> +    ignoredPaths: ['test', 'file-not-found', 'overview-dump'],
wild guess: line length limit caused the first one to be formatted differently?

2019-02-19 23:52 UTC, IgorMinar commented on aio/tools/transforms/angular-base-package/processors/createSitemap.js
> +                  // Filter out docs that are not outputted
yeah.. it's unclear what or how this file was reformatted.

2019-02-19 23:52 UTC, IgorMinar commented on aio/tools/transforms/angular-base-package/processors/createSitemap.spec.js
> +      it('ignoring blocked doc types', () => {
+1

2019-02-19 23:52 UTC, IgorMinar commented on aio/tools/transforms/angular-base-package/processors/createSitemap.spec.js
> +      it('ignoring blocked paths', () => {
+1

2019-02-19 23:52 UTC, IgorMinar commented on integration/cli-hello-world/src/polyfills.ts
> + * ```js
again. all of these changes should be upstreamed to CLI first and then downstreamed here. is that what you are doing?

2019-02-19 23:52 UTC, IgorMinar commented on packages/compiler/src/assertions.ts
> +const FORBIDDEN_INTERPOLATION_REGEXPS = [
how about: 
```
INTERPOLATION_BLOCKLIST = [...] : RegExp[]
```
?

2019-02-19 23:52 UTC, IgorMinar commented on packages/core/src/sanitization/url_sanitizer.ts
> -const SAFE_SRCSET_PATTERN = /^(?:(?:https?|file):|[^&:/?#]*(?:[/?#]|$))/gi;
+1 - what happened?

it's concerning that this is in url sanitizer - can you please verify how this line was made unused and if the previous change was correct and only forgot to remove this line. We need to be confident that we didn't screw up the previous change before removing this line.

2019-02-19 23:52 UTC, IgorMinar commented on packages/platform-browser/src/dom/events/dom_events.ts
> +    (typeof Zone !== 'undefined') && (Zone as any)[__symbol__('DISABLE_EVENTS')];
correct - you can't change this without requiring a new version of zone.js in peer deps. alternatively, and likely more preferably we should check for both symbols and leave a comment about when to remove the obsolete one in the future.

2019-02-19 23:52 UTC, IgorMinar commented on packages/platform-browser/src/dom/events/dom_events.ts
> +    (typeof Zone !== 'undefined') && (Zone as any)[__symbol__('DISABLE_EVENTS')];
also, shouldn't it be `DISABLED_EVENTS` ? or something even more descriptive?

2019-02-19 23:52 UTC, IgorMinar commented on packages/platform-browser/test/dom/events/event_manager_spec.ts
> +    it('should run disallowedEvents handler outside of ngZone', () => {
+1

2019-02-19 23:52 UTC, IgorMinar commented on packages/platform-browser/testing/src/browser_util.ts
> +const _safeTags = ['br', 'hr', 'input'];
+1 for `_voidTags`

2019-02-19 23:52 UTC, IgorMinar commented on test-events.js
> -Zone[Zone.__symbol__('BLACK_LISTED_EVENTS')] = ['scroll'];
+1

2019-02-19 23:52 UTC, IgorMinar commented on tools/material-ci/angular_material_test_blocklist.js
> +window.testBlockList = {
whatever we do, we should be consistent about the capitalization across the board...

2019-02-19 23:52 UTC, IgorMinar commented on tools/ts-api-guardian/test/unit_test.ts
> +  it('should throw on using disallowed module imports in expression position', () => {
```suggestion
  it('should throw on using module import names in expression position, if the names have not been explicitly allowed', () => {
```

2019-02-20 23:08 UTC, benlesh commented on aio/content/guide/browser-support.md
> +    // __zone_symbol_DISABLE_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames
cc @JiaLiPassion it seems like these things must be upstreamed in Zone.js?

2019-02-20 23:10 UTC, benlesh commented on aio/tools/examples/shared/boilerplate/cli/src/polyfills.ts
> + * because those flags need to be set before `zone.js` being loaded, and webpack
The comments here seems largely duplicated through more than one copy of `polyfills.ts`.  I may have copied and pasted improperly here.

2019-02-20 23:10 UTC, benlesh commented on aio/tools/transforms/angular-base-package/processors/createSitemap.js
> +    ignoredPaths: ['test', 'file-not-found', 'overview-dump'],
Igor is correct, this was auto-formatted.

2019-02-20 23:11 UTC, benlesh commented on aio/tools/transforms/angular-base-package/processors/createSitemap.js
> +                  // Filter out docs that are not outputted
Auto-formatted by clang formatter (our formatter)

2019-02-21 15:07 UTC, gkalpak commented on aio/content/guide/browser-support.md
> +    // __zone_symbol_DISABLE_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames
If we want to make these changes in zone.js, they either need to happen in a backwards compatible way or via a breaking change (which means Angular also needs a breaking change to break compatibility with older zone.js versions).

2019-02-21 15:50 UTC, JiaLiPassion commented on aio/content/guide/browser-support.md
> +    // __zone_symbol_DISABLE_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames
@benlesh, @gkalpak, yeah, I can make a PR in `zone.js` to do the rename and also keep the `backward compatiblity` so the `__zone_symbol__BLACK_LISTED_EVENTS` and `__zone_symbol_DISABLE_EVENTS` can all work.

2019-02-21 15:51 UTC, JiaLiPassion commented on packages/platform-browser/src/dom/events/dom_events.ts
> +    (typeof Zone !== 'undefined') && (Zone as any)[__symbol__('DISABLE_EVENTS')];
Like above, I will make a PR in `zone.js` first.

2019-02-21 15:51 UTC, JiaLiPassion commented on test-events.js
> -Zone[Zone.__symbol__('BLACK_LISTED_EVENTS')] = ['scroll'];
@skreborn , @IgorMinar , sure, got it!

2019-03-29 18:32 UTC, benlesh commented
Most of these issues were resolved in other PRs. I broke the remaining issues into smaller PRs. We can close this one.

2019-03-29 18:32 UTC, closed without merging

2019-05-21 18:45 UTC, elimin8r commented
seems like a lot of effort to rename some variables. also, if you dont scrub the git history, the very beings you are catering to will still be triggered when they examine the past, thus rendering this an exercise in futility.