fix(ivy): ngOnChanges should be inherited from super class
angular/angular pull request #28563
Opened 2019-02-06 14:02 UTC by marclaval

This fixes FW-1013.

Since a simple class doesn't have a definition, the `NgOnChangesFeature` was not applied on the sub directive/component.
The issue was only occurring in upgrade e2e tests.

2019-02-06 17:29 UTC, gkalpak approved these changes
LGTM for `upgrade` 😃

2019-02-06 18:38 UTC, kara requested changes

2019-02-06 18:38 UTC, kara commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +          NgOnChangesFeature()(definition);
We probably don't want `InheritDefinitionFeature` to depend directly on `NgOnChangesFeature`, as this won't tree-shake.

2019-02-06 18:38 UTC, kara commented on packages/core/test/render3/inherit_definition_feature_spec.ts
> +    it('should not be inherited when it exists on the SubDirective, whatever the features order in the definition',
Can you convert this into a TestBed test in the acceptance folder? We shouldn't have any new runtime-only tests.

2019-02-07 13:09 UTC, marclaval commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +          NgOnChangesFeature()(definition);
I agree. But I don't see how could be done, unless the feature is "attached" by the compiler to the super class, which is just a class.

2019-02-07 14:19 UTC, JoostK commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +          NgOnChangesFeature()(definition);
Perhaps `ngBaseDef` could incorporate that, otherwise I also don't see how that would be possible.

2019-02-07 16:05 UTC, trotyl commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +          NgOnChangesFeature()(definition);
It's about the decision whether life-cycle hooks in computed base need to be recognized:

```typescript
@Component()
class MyComponent extends foo()[bar] { }
```

If true, then `NgOnChangesFeature` must be brought by `InheritDefinitionFeature`, there's no way to make it tree-shakable as not possible for compile-time check.

2019-02-11 17:00 UTC, marclaval commented on packages/core/test/render3/inherit_definition_feature_spec.ts
> +    it('should not be inherited when it exists on the SubDirective, whatever the features order in the definition',
Done

2019-02-11 17:08 UTC, marclaval commented
@kara I've moved the tests.
About the tree-shaking point, I don't see how it could be addressed.

Note: I had to fix the JIT compiler so that it respects locality

2019-02-11 22:49 UTC, mhevery commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +          NgOnChangesFeature()(definition);
I also don't see a way to make this tree shakable. As @marclaval points out `ngOnChanges` can be on a superclass which has no decorator, hence it does not get processed by the compiler. As a result this inheritance feature must assume that it could have been done, and must depend on `NgOnChangesFeature`

2019-02-11 22:49 UTC, mhevery approved these changes

2019-02-11 22:56 UTC, kara commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +          NgOnChangesFeature()(definition);
Okay, looks like we all agree that there isn't really a way to avoid the cost. I can't think of anything either.

2019-02-11 22:59 UTC, kara approved these changes
LGTM, thanks for updating the test

2019-02-12 00:23 UTC, closed without merging