test: introduce first integration test for ngtsc in ts_library
angular/angular pull request #28573
Opened 2019-02-06 18:47 UTC by alexeagle

2019-02-08 17:10 UTC, alxhub approved these changes

2019-02-13 05:28 UTC, IgorMinar requested changes

2019-02-13 05:28 UTC, IgorMinar commented on packages/compiler-cli/test/ngtsc/tsc_plugin/BUILD.bazel
> +    compile_angular_templates = True,
can we please reconsider this attribute name for the following reasons:
- it's too long
- it's technically incorrect - we compile not just templates, but all metadata captured in Angular decorators (e.g. services, directives, etc)

how about one of:
- `plugin_angular = True`
- `plugin = angular_compiler` (where angular_compiler is a symbol/token exported from rules_typescript)
- `angular_pass = True`
- `angular = True`

2020-07-29 01:39 UTC, alexeagle commented
I think this is obsolete

2020-07-29 01:39 UTC, closed without merging