docs: remember Windows users to install Git
angular/angular pull request #28624
Opened 2019-02-08 21:17 UTC by cironunes

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The docs don't tell Windows users to install Git which is a prerequisite of the Angular CLI

## What is the new behavior?
Docs updated to tell Windows users to install Git.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-02-19 14:09 UTC, mary-poppins commented
You can preview 661f0b8 at https://pr28624-661f0b8.ngbuilds.io/.

2019-02-19 14:13 UTC, brandonroberts requested changes

2019-02-19 14:13 UTC, brandonroberts commented on aio/content/guide/quickstart.md
> +{@ windowsusers}
This should be a more general section like `### Git`

```
Some description of Git with a link to installation

To check that you have the git client installed, run `git --version` in a terminal/console window.
```

2019-02-21 21:01 UTC, cironunes commented on aio/content/guide/quickstart.md
> +{@ windowsusers}
cool. I'll update the PR

2019-05-06 14:06 UTC, brandonroberts commented
@cironunes are you still interested in making these changes?

2019-05-28 16:46 UTC, brandonroberts commented
Reopen this PR or open a new one when you're ready. Thanks

2019-05-28 16:46 UTC, closed without merging