feat(ivy): support i18n without closure
angular/angular pull request #28689
Opened 2019-02-13 13:52 UTC by ocombe

So far using runtime i18n with ivy meant that you needed to use Closure and `goog.getMsg` (or a polyfill). This PR changes the compiler to only output closure code when the compiler option `i18nUseClosure` is set to true. This option is set to false when the option `i18nInFile` is used, which is what the AoT compiler uses when you load a translations file.
This means that if you use the Angular CLI with ivy and load a translations file, you can use i18n and the application will not throw at runtime.
For now it will not translate your application, but at least you can try ivy in AoT mode without having to remove all of your i18n code and configuration.

2019-02-13 13:57 UTC, petebacondarwin approved these changes
LGTM for ngcc

2019-02-13 19:34 UTC, mhevery approved these changes

2019-02-13 19:57 UTC, AndrewKushnir approved these changes
@ocombe looks good! Just left a couple minor comments. Thank you.

2019-02-13 19:57 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/program.ts
> +          this.options.i18nUseExternalIds !== false, !this.options.i18nInFile, this.moduleResolver,
nit: I'd propose to define a separate const called `i18nUseClosure` and used it here as an arg. That should improve readability and also we can use it as an anchor for additional documentation on why we do it this way (what you explained in PR description):

```
/**
 *  We define `i18nUseClosure` based on the `i18nInFile` config option value. <here is why>
 *  ...
 */
const i18nUseClosure = !this.options.i18nInFile;
```

2019-02-13 19:57 UTC, AndrewKushnir commented on packages/core/src/render3/i18n.ts
> +export function i18nConfigureLocalize(options: I18nLocalizeOptions = {
This function sets translations hash only. Should we may be call it `i18nSetTranslations` and accept translations map as an argument?

2019-02-18 15:06 UTC, ocombe commented
Blocked by https://angular-team.atlassian.net/browse/FW-1076 (bazel issue)

2019-02-20 09:41 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +export function i18nConfigureLocalize(options: I18nLocalizeOptions = {
It sets translations hash only for now, but I think that we'll need to add the locale_id soon as well

2019-02-26 09:34 UTC, gregmagolan commented
> Blocked by https://angular-team.atlassian.net/browse/FW-1076 (bazel issue)

Alex got https://github.com/angular/angular/pull/21883 merged which should resolve FW-1076. You should be unblocked on master.

2019-02-26 12:58 UTC, ocombe commented
@gregmagolan just rebased on master and it doesn't change anything for me. It still doesn't take the tsconfig into consideration. Am I supposed to change something else to the bazel build file to make this work?

2019-03-01 18:55 UTC, mhevery requested changes

2019-03-01 18:55 UTC, mhevery commented on packages/compiler/src/render3/view/api.ts
> +  i18nUseClosure: boolean;
this flag is bothering me. The way I understand it, it controls if the generated code will use `goog.getMsg` or not. The issue is that we plan to allow people to ship code to NPM, which means that the generated code has to be such that it works in both modes, with and without closure.

2019-03-01 18:55 UTC, mhevery commented on packages/core/test/bundling/todo_i18n/tsconfig.json
> +    "i18nInFile": "translations.xlf",
Can we discuss how passing in `.xlf` file into closure will be compatible with our long term goals.

2019-03-04 21:59 UTC, petebacondarwin approved these changes
still LGTM for ngcc (given that it doesn't seem to touch any ngcc files anymore)

2019-03-04 23:39 UTC, mhevery approved these changes
With a minor quibble.

2019-03-04 23:39 UTC, mhevery commented on packages/core/test/bundling/hello_world_i18n/index.html
> +      window.ngI18nClosureMode = false;
This should not be needed. Just make sure that `ng_i18n_closure_mode.ts` is imported from `ng_dev_mode` or some other place which will make it ubiquitous.

2019-03-04 23:39 UTC, mhevery commented on packages/core/test/bundling/todo_i18n/index.html
> +    window.ngI18nClosureMode = false;
same here (should not be needed).

2019-03-05 00:58 UTC, AndrewKushnir requested changes

2019-03-05 00:58 UTC, AndrewKushnir commented on packages/compiler-cli/test/compliance/r3_view_compiler_i18n_spec.ts
> +        var $MSG_EXTERNAL_idA$$APP_SPEC_TS_0$;
I just tested that with Closure compiler and here are the findings:

- `goog.getMsg` call output should be assigned to separate/unique const (as it was before)
- other var names mush *not* start with `MSG_` prefix, since it's reserved by Closure for `goog.getMsg` output
- multiple declarations of a var with the same `MSG_` prefix are not allowed

Generated output code should look similar to [what we have in our original design doc](https://github.com/angular/angular/blob/master/packages/core/src/render3/i18n.md#translation-message-retrieval) (with a small correction to avoid `MSG_`-prefixed consts/vars in places other than `goog.getMsg`s invocation):

```
var I18N_EXTERNAL_idA$$APP_SPEC_TS_0;
if (ngI18nClosureMode) {
  const MSG_EXTERNAL_idA$$APP_SPEC_TS_0  = goog.getMsg('Hello World!');
  I18N_EXTERNAL_idA$$APP_SPEC_TS_0 = MSG_EXTERNAL_idA$$APP_SPEC_TS_0;
} else {
  I18N_EXTERNAL_idA$$APP_SPEC_TS_0 = i0.ɵi18nLocalize('Hello World!');
}
```

2019-03-05 00:58 UTC, AndrewKushnir commented on packages/compiler-cli/test/compliance/r3_view_compiler_i18n_spec.ts
> +        const _c2 = ["title", $MSG_EXTERNAL_idB$$APP_SPEC_TS_1$];
It'd be great to keep $$ around consts to test output less fragile (otherwise we'll start checking for specific chars).

2019-03-05 00:58 UTC, AndrewKushnir commented on packages/compiler-cli/test/compliance/r3_view_compiler_i18n_spec.ts
> +            $MSG_EXTERNAL_7432761130955693041$$APP_SPEC_TS_3$ = goog.getMsg("{$interpolation}", { "interpolation": "\uFFFD0\uFFFD" });
Could you plz apply the formatting of the 2nd argument's fields? That makes the output more readable (in case it should be manually verified) and the logic that verifies the output is tolerant to whitespaces.

2019-03-05 00:58 UTC, AndrewKushnir commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +    expect(jsContents).toContain(`var MSG_EXTERNAL_8321000940098097247$$TEST_TS_0;
I think this check is not needed here. The main idea of the test is to verify the format of const names, not the entire translation block structure. (similar comment to the change below in this file)

2019-03-05 00:58 UTC, AndrewKushnir commented on packages/core/src/util/ng_i18n_closure_mode.ts
> +  const goog: {getMsg: (input: string, placeholders?: {[key: string]: string}) => string;};
Closure compiler conflicts with this `goog` definition, we can just remove it and use `window.goog` in the checks below if needed.

2019-03-05 00:58 UTC, AndrewKushnir commented on packages/core/src/util/ng_i18n_closure_mode.ts
> +  if (typeof window != 'undefined') {
It looks like we already have a function to get the `global this` reference in [packages/core/src/util/global.ts](https://github.com/angular/angular/blob/master/packages/core/src/util/global.ts#L18), so we can just reuse it (and probably update ng_dev_mode.ts logic to make use of it as well).

2019-03-05 13:09 UTC, ocombe commented on packages/compiler-cli/test/compliance/r3_view_compiler_i18n_spec.ts
> +        var $MSG_EXTERNAL_idA$$APP_SPEC_TS_0$;
nooo :( I spent so much time updating your tests
well, back to square one then

2019-03-05 13:47 UTC, ocombe commented on packages/compiler-cli/test/compliance/r3_view_compiler_i18n_spec.ts
> +        var $MSG_EXTERNAL_idA$$APP_SPEC_TS_0$;
Actually do we need complex variable names like this for anything else than closure? Could we just have:
```
var _c0;
if (ngI18nClosureMode) {
  const MSG_EXTERNAL_idA$$APP_SPEC_TS_0  = goog.getMsg('Hello World!');
  _c0 = MSG_EXTERNAL_idA$$APP_SPEC_TS_0;
} else {
  _c0 = i0.ɵi18nLocalize('Hello World!');
}
```

2019-03-05 23:46 UTC, AndrewKushnir requested changes

2019-03-05 23:46 UTC, AndrewKushnir commented on packages/core/src/util/ng_i18n_closure_mode.ts
> +
I just tested the latest changes in g3 and here are the results:

1. Closure compiler throws an error at `ngI18nClosureMode`:
```
app.closure.js:16: ERROR - variable ngI18nClosureMode is undeclared
if (ngI18nClosureMode) {
    ^^^^^^^^^^^^^^^^^
```

in order to avoid that, the proposal is to add the following code to the `packages/core/src/util/ng_i18n_closure_mode.ts` script right after the import statement:

```
declare global {
  const ngI18nClosureMode: boolean;
}
```

2. Closure also produces a warning like this:

```
app.closure.js:125: WARNING - constant module$contents$google3$javascript$angular2$tests$i18n_test$app$app_I18N_29 assigned a value more than once.
Original definition at XXX/app.closure.js:119
    I18N_29 = i0.?i18nLocalize("Hello {$interpolation}!", { "interpolation": "\uFFFD0\uFFFD" });
```

it looks like the problem was caused by the misplaced comments/annotations:

```
/**
 * @desc d
 * @meaning m
 */ 
var I18N_29;
if (ngI18nClosureMode) {
    const MSG_EXTERNAL_8071726987696286356$$JAVASCRIPT_ANGULAR2_TESTS_I18N_TEST_APP_APP_TS_30 = goog.getMsg("Hello {$interpolation}!", { "interpolation": "\uFFFD0\uFFFD" });
    I18N_29 = MSG_EXTERNAL_8071726987696286356$$JAVASCRIPT_ANGULAR2_TESTS_I18N_TEST_APP_APP_TS_30;
}
```

Note that the @desc and @meaning tags are not attached to the `const MSG_XXX = goog.getMsg(...)` statement.

2019-03-07 01:51 UTC, AndrewKushnir commented
@ocombe thanks for additional changes! I did another round of testing in g3:

- demo app (with i18n) was built successfully, generated code looks good
- I was *unable* to fully test the app, because of the issue I described in FW-1140: i18n runtime seems to generate incorrect HTML structure (missing content) in case there are few i18n sections present in a template, like:

```
  <div i18n>Section 1</div>
  <div i18n>Section 2</div>
  <div i18n>Section 3</div>
```

the output is `<div></div><div></div><div>Section 3</div>`.

I verified that this problem exists in current master and understand that this problem is not related to this PR, but it makes impossible to do full round of testing in g3 (to make sure there are no other hidden issues while generating code using Closure Compiler and running it afterwards).

Could you please let me know if this is something you can look at?

2019-04-03 14:15 UTC, cexbrayat commented
@ocombe Is this still blocked? That would be awesome to get it merged because it is currently blocking external testing :)

2019-04-03 14:15 UTC, cexbrayat commented
(damn, you pushed when I commented 👌 )

2019-04-03 14:16 UTC, ocombe commented
it isn't blocked, I just asked @AndrewKushnir to test it against g3 again, hopefully we should be able to merge it now

2019-04-03 17:11 UTC, AndrewKushnir commented
@ocombe I will test it in g3 asap. I also started a [presubmit](http://test/OCL:236737578:BASE:241753940:1554311423906:fc81342e). Thank you.

2019-04-03 18:06 UTC, AndrewKushnir commented
Presubmit is successful, basic checks with demo app also look good, but we need to look into the `ngI18nClosureMode` flag in Closure configuration to make sure unnecessary code is tree-shaken away properly.

2019-04-03 18:09 UTC, AndrewKushnir approved these changes

2019-04-05 19:58 UTC, mhevery approved these changes

2019-04-05 21:35 UTC, IgorMinar requested changes
can you please address the comments I posted and split this PR into two - one for cli update to beta.11 and one for the remaining changes. that way we can isolate the payload size regression and attribute it to this change or an issue in cli. thanks

2019-04-05 21:35 UTC, IgorMinar commented on integration/cli-hello-world-ivy-compat/package.json
> +    "@angular/cli": "^8.0.0-beta.11",
can you please not change this. if you need a newer version, then you should update the root package.json and not this one.

2019-04-05 21:35 UTC, IgorMinar commented on integration/cli-hello-world-ivy-compat/yarn.lock
> +"@angular/cli@^8.0.0-beta.11":
please revert

2019-04-05 21:35 UTC, IgorMinar commented on integration/cli-hello-world-ivy-minimal/package.json
> +    "@angular/cli": "^8.0.0-beta.11",
revert

2019-04-05 21:35 UTC, IgorMinar commented on integration/cli-hello-world-ivy-minimal/yarn.lock
> +"@angular/cli@^8.0.0-beta.11":
revert

2019-04-05 21:35 UTC, IgorMinar commented on packages/core/test/bundling/todo_i18n/index.ts
> +// TODO(ocombe): replace this with the real runtime i18n service configuration
why will this happen? if this really is a TODO then we should likely have an item in jira for this. If this is just a note then make it a note and not a TODO

2019-04-05 21:35 UTC, IgorMinar commented on integration/_payload-limits.json
> +        "main": 14261,
what is causing this regression? do you know?

2019-04-05 22:30 UTC, ocombe commented on integration/_payload-limits.json
> +        "main": 14261,
I think this is the content of `ng_i18n_closure_mode.ts` where we define a global value for the i18n closure mode

2019-04-05 22:31 UTC, ocombe commented on packages/core/test/bundling/todo_i18n/index.ts
> +// TODO(ocombe): replace this with the real runtime i18n service configuration
Because `ɵi18nConfigureLocalize` is just temporary (as explained in its api docs) until we can work on the service. We needed something for our tests to make i18n work without closure so that people can test ivy even if they use i18n.

2019-04-05 22:32 UTC, ocombe commented on integration/cli-hello-world-ivy-compat/package.json
> +    "@angular/cli": "^8.0.0-beta.11",
we talked about this at the framework meeting yesterday and it was decided to only change this in the ivy integration apps for now

2019-04-05 22:34 UTC, ocombe commented
@IgorMinar the size regression was present before the cli change. I tried to update the cli version to see if my change to tree shake `ngI18nClosureMode` could fix the regression (https://github.com/angular/angular-cli/pull/13905) but it didn't change anything (in fact it added 2 bytes).

2019-04-08 09:06 UTC, ocombe commented
I removed the cli changes, and rebased onto master and it fixed the size regression issue. @IgorMinar can you approve the PR now? :)

2019-04-08 14:28 UTC, alxhub approved these changes

2019-04-09 00:26 UTC, IgorMinar commented on integration/cli-hello-world-ivy-compat/package.json
> +    "@angular/cli": "^8.0.0-beta.11",
can you please share why?

my concern is that we are making our integration testing infrastructure more fragile if we make this change and we are increasing technical debt. I'd prefer not to make a change like that unless we really really have to (and then there should be a follow up work to remove this temporary hack which should be tracked and scheduled so that we don't forget).

2019-04-09 00:28 UTC, IgorMinar commented on packages/core/test/bundling/todo_i18n/index.ts
> +// TODO(ocombe): replace this with the real runtime i18n service configuration
let me try to explain my question better: if I'm reading this todo in the codebase a month from now, what should I do, how should I interpret it, or how can I learn more about what this comment stands for?

In its current form, all I can do is ask you personally what this is about and where I can learn more, and that doesn't scale.

2019-04-09 00:33 UTC, IgorMinar approved these changes
lgtm except for that one todo

2019-04-09 19:03 UTC, ocombe commented on packages/core/test/bundling/todo_i18n/index.ts
> +// TODO(ocombe): replace this with the real runtime i18n service configuration
I've updated the todo, let me know if it is still unclear. If not then please approve the PR and run g3sync.

2019-04-09 19:14 UTC, kara commented
[presubmit](http://test/OCL:242713975:BASE:242714971:1554837219843:3c6df3f6)

2019-04-11 14:59 UTC, IgorMinar approved these changes

2019-04-11 15:03 UTC, IgorMinar commented
previews presubmit failed, so here is a new one after the last set of changes: http://test/OCL:243069482:BASE:243069609:1554994952547:fae7a7a0

2019-04-11 15:30 UTC, closed without merging