fix(ivy): circular reference in i18n
angular/angular pull request #28744
Opened 2019-02-15 00:59 UTC by mhevery

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-02-15 08:03 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +      assertNotEqual(cursor, tNode, 'We have created a loop');
This will never be correct, you say `let cursor: TNode|null = tNode;` and then you try to assert that it's not equal. There's no way this is gonna pass.
You probably need to put the assert after `cursor = cursor.next;`.

2019-02-15 08:03 UTC, ocombe requested changes
The assert is wrong and will never pass.

2019-02-15 08:09 UTC, petebacondarwin requested changes
No unit tests?

2019-02-15 18:24 UTC, mhevery commented on packages/core/src/render3/i18n.ts
> +      assertNotEqual(cursor, tNode, 'We have created a loop');
Ohh right good catch. I have fixed it . But it still fails. `bazel test packages/core/test/render3`

2019-02-15 18:25 UTC, mhevery commented
@petebacondarwin 
> No unit tests?

This is not a real PR, rather I want to demonstrate to @ocombe that there is something wrong going on with i18n.

2019-02-19 20:28 UTC, mhevery commented
resolved by https://github.com/angular/angular/pull/28827

2019-02-19 20:28 UTC, closed without merging