fix(ivy): incorrectly remapping certain properties that refer inputs
angular/angular pull request #28765
Opened 2019-02-15 20:46 UTC by crisbeto

During build time we remap particular property bindings, because their names don't match their attribute equivalents (e.g. the property for the `for` attribute is called `htmlFor`). This breaks down if the particular element has an input that has the same name, because the property gets mapped to something invalid.

The following changes address the issue by mapping the name during runtime, because that's when directives are resolved and we know all of the inputs that are associated with a particular element.

2019-02-19 18:13 UTC, kara requested changes
Changes look good to me, just needs some test updates

2019-02-19 18:13 UTC, kara commented on packages/core/test/render3/properties_spec.ts
> +  it('should map properties whose names do not correspond to their attribute names', () => {
We're trying to avoid adding new tests with handwritten generated code. Can you convert these tests to TestBed tests and add them to the `core/test/acceptance` folder?  Also seems like we'll need a test in the compliance spec to test that we are generating code without the mapping.

2019-02-19 20:19 UTC, crisbeto commented
@kara I've switched the tests over to `TestBed` and added a new test for the code generation. Can you take another look? The CI failures seem to be unrelated.

2019-02-19 21:41 UTC, kara commented on packages/compiler-cli/test/compliance/r3_view_compiler_template_spec.ts
> +  it('should not remap property names whose names do not correspond to their attribute names',
Would you mind moving this to the compliance_binding_spec? This file is specifically for nested template tests, to the test doesn't really fit in here.

https://github.com/angular/angular/blob/6ed7120be0b284c302b786c567024d1ee754c747/packages/compiler-cli/test/compliance/r3_view_compiler_binding_spec.ts

2019-02-19 21:55 UTC, crisbeto commented on packages/compiler-cli/test/compliance/r3_view_compiler_template_spec.ts
> +  it('should not remap property names whose names do not correspond to their attribute names',
Done.

2019-02-19 22:00 UTC, kara approved these changes
~~LGTM~~

2019-02-19 22:00 UTC, kara commented on packages/compiler-cli/test/compliance/r3_view_compiler_template_spec.ts
> +  it('should not remap property names whose names do not correspond to their attribute names',
Thanks!

2019-02-19 22:48 UTC, kara requested changes
@crisbeto Just realized that this PR should fix a number of Material tests, but we're not actually removing anything from the blocklist.  Can you remove the relevant tests?

https://github.com/angular/angular/blob/master/tools/material-ci/angular_material_test_blocklist.js#L1861

2019-02-20 08:36 UTC, crisbeto commented
Updated @kara. It also has two new bonus failures that are due to static queries.

2019-02-20 12:39 UTC, filipesilva approved these changes
LGTM for the changes in `tools/material-ci/angular_material_test_blocklist.js` (the ones I assumed triggered the `angular/fw-dev-infra` review).

2019-02-20 19:54 UTC, kara approved these changes
LGTM, though it needs a rebase

2019-02-20 22:10 UTC, crisbeto commented
It's rebased @kara.

2019-02-20 22:29 UTC, alxhub approved these changes

2019-02-20 22:42 UTC, kara commented
[presubmit](http://test/OCL:234871613:BASE:234871688:1550702469282:d518b76b)

2019-02-22 02:01 UTC, closed without merging