docs: add angular.de to the workshops page
angular/angular pull request #28856
Opened 2019-02-20 08:34 UTC by web-dave

I added our community (angular.de) to the workshops page (https://angular.io/resources)
We offer public and inhouse Workshops onsite since 2013

2019-02-21 19:57 UTC, mary-poppins commented
You can preview 77b1e1c at https://pr28856-77b1e1c.ngbuilds.io/.

2019-02-21 20:13 UTC, brandonroberts approved these changes
LGTM. @StephenFluin will have to add final approval.

2019-02-23 06:29 UTC, web-dave commented
@mary-poppins looks good.

2019-02-25 16:28 UTC, StephenFluin requested changes
The content you added looks good, but there seems to be an unrelated change in the commit. Can we clean that up?

2019-02-25 16:28 UTC, StephenFluin commented on aio/content/marketing/resources.json
> +            "desc": "Amexio Canvas is Drag and Drop Environment to create Fully Responsive Web and Smart Device HTML5/Angular Apps. Code will be auto generated and hot deployed by the Canvas for live
Looks like there's an unrelated whitespace change, can we remove this from the commit?

2019-02-26 19:14 UTC, web-dave commented on aio/content/marketing/resources.json
> +            "desc": "Amexio Canvas is Drag and Drop Environment to create Fully Responsive Web and Smart Device HTML5/Angular Apps. Code will be auto generated and hot deployed by the Canvas for live
certainly I can, even if it is completely useless. But I will fix it.

2019-02-26 19:16 UTC, web-dave commented on aio/content/marketing/resources.json
> +            "desc": "Amexio Canvas is Drag and Drop Environment to create Fully Responsive Web and Smart Device HTML5/Angular Apps. Code will be auto generated and hot deployed by the Canvas for live
done

2019-02-26 19:19 UTC, mary-poppins commented
You can preview 39a8e39 at https://pr28856-39a8e39.ngbuilds.io/.

2019-02-27 17:47 UTC, StephenFluin commented
It looks like we now have two commits, can you squash them into one and force push?

https://twitter.com/stephenfluin/status/1009904095073718275?lang=en

2019-02-27 19:02 UTC, mary-poppins commented
You can preview 47305c2 at https://pr28856-47305c2.ngbuilds.io/.

2019-03-11 23:51 UTC, web-dave commented
What about this @StephenFluin?
Is there something else that I should do?

2019-03-29 16:40 UTC, mary-poppins commented
You can preview 253c9ac at https://pr28856-253c9ac.ngbuilds.io/.

2019-04-03 17:27 UTC, StephenFluin approved these changes

2019-04-03 22:41 UTC, closed without merging