fix(ivy): resolve forwardRef when analyzing NgModule
angular/angular pull request #28942
Opened 2019-02-23 11:15 UTC by crisbeto

Fixes forward refs not being resolved when an NgModule is being analyzed by ngtsc.

This PR resolves FW-1094.

2019-02-26 23:12 UTC, mhevery submitted a review, later dismissed

2019-02-26 23:15 UTC, mhevery commented
http://test/OCL:235803302:BASE:235803353:1551222930519:a4b701f7

2019-02-26 23:50 UTC, alxhub requested changes

2019-02-26 23:50 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts
> +        if (entry instanceof DynamicValue) {
I need to look more at this, but this approach is incorrect, we shouldn't get `DynamicValue` in the first place.

2019-02-26 23:53 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
> +  const node = unwrapForwardRef(args[0], reflector) || args[0];
I don't quite understand what's going on here. `unwrapForwardRef` returns a `ts.Expression`, it should never be false-y.

2019-02-26 23:59 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
> +  const node = unwrapForwardRef(args[0], reflector) || args[0];
Ah, I see this change adds `|null` to the signature.

2019-02-27 00:54 UTC, alxhub requested changes

2019-02-27 00:54 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts
> +        if (entry instanceof DynamicValue) {
Okay!

So, the `PartialEvaluator` already supports this concept called a `ForeignFunctionResolver`. Basically, if it encounters a function call that it can't resolve past, it will try the `ForeignFunctionResolver` to see if the caller knows how to resolve it.

You can see that in use in `analyze` above:

```
const importsMeta = this.evaluator.evaluate(
          rawImports, ref => this._extractModuleFromModuleWithProvidersFn(ref.node));	          rawImports, ref => this._extractModuleFromModuleWithProvidersFn(ref.node));
```

`this._extractModuleFromModuleWithProvidersFn` is a `ForwardRefResolver` which can "see" past a function call of the form `RouterModule.forRoot(...)` as long as the return type is properly annotated.

There is a `forwardRefResolver` in util.ts which can see past `forwardRef()` calls during partial evaluation. This just needs to be plumbed into the `this.evaluator.evaluate` calls above.

I prototyped this in a draft PR for you: https://github.com/angular/angular/pull/28998/files#diff-8cc55c2b0602ebe2a2876924979869b7. To get there I wrote a `combineResolvers` utility to allow both the `forwardRefResolver` and `_extractModuleFromModuleWithProvidersFn` to be used together.

Please update this PR to use that approach and add tests for imports, exports, etc. Thanks!

2019-02-27 18:56 UTC, alxhub approved these changes

2019-02-27 19:26 UTC, alxhub commented
[Presubmit](http://test/OCL:235951903:BASE:235958014:1551295556242:7ef32591)

2019-02-27 22:04 UTC, closed without merging