fix(ivy): avoid missing imports for types that can be represented as values
angular/angular pull request #28941
Opened 2019-02-23 02:13 UTC by AndrewKushnir

Prior to this change, TypeScript stripped out some imports in case we reference a type that can be represented as a value (for ex. classes). This fix ensures that we use correct symbol identifier, which makes TypeScript retain the necessary import statements.

Thanks @alxhub for the help with investigation and fix.

This PR resolves FW-1099.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-02-26 21:48 UTC, alxhub requested changes

2019-02-26 21:48 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +    expect(jsContents).toContain(trim(imports));
I'd inline the assertions here, and only assert those conditions that fall under the scope of the test. We don't need to test that the whole `setClassMetadata` call is character-for-character correct. In my experience that tends to make the tests too brittle.

2019-02-26 21:48 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +      export interface MyType {
Change this to use `export type MyType = Map<any, any>` - I'd like to test it with a type that does have a resolvable value side.

2019-02-27 19:26 UTC, AndrewKushnir commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +    expect(jsContents).toContain(trim(imports));
Thanks Alex, I've updated the test to check for the things we need to verify in a context of this test.

2019-02-27 19:32 UTC, AndrewKushnir commented
@alxhub thanks for the review! I've applied the changes based on your feedback. Could you please take another look? Thank you.

2019-02-27 19:35 UTC, alxhub approved these changes
One more test is needed, otherwise lgtm!

2019-02-27 19:35 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +  it('should use imported types in setClassMetadata if they can be represented as values', () => {
Please add a test to ensure we get it right if the class is implemented as:

```
import * as foo from 'foo';
...
constructor(f: foo.Foo) {}
```

2019-02-27 19:49 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:235962879:BASE:235962915:1551296981393:e3abb76d)

2019-02-27 23:15 UTC, closed without merging