docs: update Universal guide
angular/angular pull request #28956
Opened 2019-02-24 23:55 UTC by CaerusKaru

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-02-25 08:42 UTC, alan-agius4 commented
Maybe we can combine this with https://github.com/angular/angular/pull/28231?

2019-02-25 13:23 UTC, mary-poppins commented
You can preview e6cf904 at https://pr28956-e6cf904.ngbuilds.io/.

2019-02-25 15:03 UTC, MarkPieszak approved these changes

2019-02-26 00:54 UTC, CaerusKaru commented
@alan-agius4 I made these edits with your PR in mind, I'm hoping that it at least mostly matches up with the changes you made? If there's something specific you'd like me to port over, please let me know.

I was hoping your PR was going to be merged by now, but it looks like it got stalled.

2019-03-04 18:11 UTC, jbogarthyde reviewed
Copy edit

2019-03-04 18:11 UTC, jbogarthyde commented on aio/content/guide/universal.md
> +1. Facilitate web crawlers (search engine optimization, aka SEO)
how about: 
1. Facilitate web crawlers through [search engine optimization (SEO)](https://static.googleusercontent.com/media/www.google.com/en//webmasters/docs/search-engine-optimization-starter-guide.pdf).

2019-03-04 18:11 UTC, jbogarthyde commented on aio/content/guide/universal.md
> +1. Show the first page quickly (first-contentful paint, aka FCP)
how about:

1. Show the first page quickly with a [first contentful paint (FCP)](https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint).

(trying to avoid "aka" and make FCP parallel with SEO)

2019-03-04 18:14 UTC, jbogarthyde commented on aio/content/guide/universal.md
If you put the link in the intro, you don't need this line.

2019-03-05 21:21 UTC, vikerman requested changes

2019-03-05 21:21 UTC, vikerman commented on aio/content/guide/universal.md
> +falls under the category of "SSR with (Re)Hydration".
This is not correct for the current version of Angular SSR. We don't support Rehydration. Suggest just removing this line.

2019-03-05 21:21 UTC, vikerman commented on aio/content/guide/universal.md
> +Notice, however, that clicks, mouse-moves, and keyboard entries are inert.
I'm not clear what this section is trying to convey. This behavior only applies if client side JS is not loaded? Maybe just explain the client side JS bootstraps and takes over the page? And to checkout preboot if events need to be buffered.

2019-03-05 21:21 UTC, vikerman commented on aio/content/guide/universal.md
> +@Injectable({providedIn: 'root'})
This service is explicitly provided. We should not need the {providedIn: 'root'}

2019-03-06 03:32 UTC, CaerusKaru commented on aio/content/guide/universal.md
> +
Is this an AIO thing? Bc GitHub markdown doesn't care (see [here](https://github.com/angular/angular/blob/e6cf90434a9f409b26a7aabeff68a81bcef28d10/aio/content/guide/universal.md))

2019-03-06 03:35 UTC, CaerusKaru commented on aio/content/guide/universal.md
> +falls under the category of "SSR with (Re)Hydration".
Wishful thinking 😉

2019-03-06 03:39 UTC, CaerusKaru commented
@jbogarthyde @vikerman Feedback addressed :+1:

2019-03-06 03:44 UTC, mary-poppins commented
You can preview 6f79659 at https://pr28956-6f79659.ngbuilds.io/.

2019-03-06 16:22 UTC, jbogarthyde commented on aio/content/guide/universal.md
> +
It's still not rendering correctly in the preview, at least in my browser (Firefox).

https://pr28956-6f79659.ngbuilds.io/guide/universal#universal-in-action

2019-03-06 18:38 UTC, vikerman approved these changes

2019-03-07 03:04 UTC, CaerusKaru commented on aio/content/guide/universal.md
> +
Should be fixed with latest edit. Weird that whatever converter we use doesn't have the same syntax as GitHub.

2019-03-07 03:08 UTC, mary-poppins commented
You can preview ec3dd78 at https://pr28956-ec3dd78.ngbuilds.io/.

2019-03-11 17:40 UTC, kara commented
@jbogarthyde Does this have approval from docs team?

2019-03-11 22:30 UTC, jbogarthyde commented
It does if I have the right to approve it.

2019-03-11 22:34 UTC, closed without merging