docs: update developer guide for testing and IntelliJ
angular/angular pull request #29048
Opened 2019-03-01 01:14 UTC by Splaktar

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
New contributors are told to run all test suites before submitting a PR, but then they have to go read a whole Bazel doc just to find that command.
There are plugin details about VS Code, but nothing for WebStorm and IntelliJ IDEs.

Issue Number: N/A

## What is the new behavior?

- provide the command for running all test suites
  - don't make new contributors read the whole Bazel doc
- add info about ClangFormatIJ plugin for IntelliJ
- add info about Bazel plugin for IntelliJ
- fix inconsistent casing of GitHub

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
I am working on some blog posts for contributing to Angular and these issues stood out as some minor pain points.

2019-03-01 09:55 UTC, devversion commented on docs/DEVELOPER.md
> +- `yarn bazel build packages/...`
This builds all Bazel targets. No tests are run with this command.

2019-03-01 10:38 UTC, Splaktar commented on docs/DEVELOPER.md
> +- `yarn bazel build packages/...`
Sorry, copy/paste error, will fix. Thanks for the heads up!

2019-03-04 16:57 UTC, brandonroberts requested changes

2019-03-04 16:57 UTC, brandonroberts commented on docs/DEVELOPER.md
> +$ ./scripts/publish/publish-build-artifacts.sh [GitHub username]
I propose we point users to the VS Code extension officially written and supported by the Bazel team below instead.

https://marketplace.visualstudio.com/items?itemName=BazelBuild.vscode-bazel

2019-03-07 05:51 UTC, Splaktar commented on docs/DEVELOPER.md
> +$ ./scripts/publish/publish-build-artifacts.sh [GitHub username]
This would make more sense to address in PR https://github.com/angular/angular/pull/29044.

2019-03-07 06:14 UTC, Splaktar commented on docs/DEVELOPER.md
> +$ ./scripts/publish/publish-build-artifacts.sh [GitHub username]
Tracking this in https://github.com/angular/angular/pull/29044#issuecomment-470395305.

2019-03-15 13:11 UTC, brandonroberts approved these changes

2019-03-15 13:11 UTC, brandonroberts commented
LGTM. The branch needs a rebase on master and a final approval.

2019-03-15 20:41 UTC, Splaktar commented
Rebase complete.

2019-03-22 17:59 UTC, mhevery approved these changes

2019-03-22 20:07 UTC, closed without merging