Use correct plural form for ivy
angular/angular pull request #29160
Opened 2019-03-07 16:44 UTC by ocombe

Plural ICU expressions depend on the locale (different languages have different plural forms). Until now the locale was hard coded as `en-US`.
This PR refactors all of the localization code that was previously living in `@angular/common`. Everything but the locale data has been moved to `@angular/core`, making it possible to get the correct plural form. Since we plan on refactoring all of this later and we didn't want to create a breaking change for that now, everything is still publicly exported by `@angular/common`, but the code is actually in `@angular/core`, making it possible to use it in core (core cannot import from common).
For compatibility reasons, if you use ivy with AOT and bootstrap your app with `bootstrapModule` then the `LOCALE_ID` token will be set automatically for ivy, which is then used to get the correct plural form.

### BREAKING CHANGE:

In v5, we deprecated support for the intl API in order to improve the browser support. We are now removing these deprecated APIs for v8. See the original change here for more info on why: #18284.

2019-03-07 17:59 UTC, IgorMinar commented
This looks good to me at the high level as long as the following are ok with this change as well: @kara, @mhevery, @stephenfluin and google3

2019-03-07 19:05 UTC, mhevery requested changes
- It is not clear to me, what is the motivation for this? Could you better explain it in the description of the PR.
- How do we communicate to people that the `@angular/common` `i18n` is deprecated?
- I see whole bunch of things removed from @angular/common but I don't see a corresponding things added to @angular/core. Without that we will break the API over time.

2019-03-07 19:05 UTC, mhevery commented on packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts
> +        name: 'ngLocaleIdDef',
why `ngLocaleIdDef` why not just `ngLocaleDef`?  Why the extra `id`. When most people talk about locales they thing `local` not `localId`.

2019-03-07 19:05 UTC, mhevery commented on packages/core/src/render3/ng_module_ref.ts
> +      setLocaleId(ngLocaleIdDef);
I think we should add some check here which would prevent loading different locales into the system. Once you select `en` it should be an error to load `fr` afterwards. What do you think?

2019-03-07 19:05 UTC, mhevery commented on tools/public_api_guard/common/common.d.ts
> -export declare enum FormatWidth {
I see whole bunch of things removed from `@angular/common` but I don't see a corresponding things added to `@angular/core`. Without that we will break the API over time.

2019-03-07 19:32 UTC, ocombe commented on packages/common/src/i18n/localization.ts
> +import {Inject, Injectable, LOCALE_ID, ɵgetPluralCase} from '@angular/core';
we could move them, but we don't need them anymore with ivy

2019-03-07 19:34 UTC, ocombe commented on packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts
> +        name: 'ngLocaleIdDef',
No reason really, I needed to pick a name and it seemed logical since it contains the value of `LOCALE_ID` which people are familiar with (including in our guides on angular.io).
But this definition is mostly internal, I'm not sure it really matters.

2019-03-07 19:35 UTC, ocombe commented on packages/core/src/render3/ng_module_ref.ts
> +      setLocaleId(ngLocaleIdDef);
That's a good idea yes

2019-03-07 19:36 UTC, ocombe commented on tools/public_api_guard/common/common.d.ts
> -export declare enum FormatWidth {
Yes, I asked @IgorMinar for help about this because I don't understand why it was removed from the common API.
The functions are in core, but exported as private, that's why they aren't in the core api, but since we export them publicly in common they should stay here. I think it's a bug or a weird case that wasn't taken into account.

2019-03-07 21:32 UTC, AndrewKushnir commented
@ocombe I'm wondering if it's possible (and if it's not too much work) to split this PR into 2 separate ones?
- removal of already deprecated APIs/functions
- move/update the remaining code around

That should help with code review as well as minimize the risk of any potential issues (so we have less code to move around).

Thank you.

2019-03-12 14:21 UTC, ocombe commented on packages/core/src/render3/ng_module_ref.ts
> +      setLocaleId(ngLocaleIdDef);
Actually that would complicate the setup for tests

2019-03-12 14:24 UTC, ocombe commented
Closing this PR, I'm going to recreate 2 different PR, one for each commit

2019-03-12 14:24 UTC, closed without merging

2019-03-12 14:29 UTC, ocombe commented
Follow up in https://github.com/angular/angular/pull/29249 and https://github.com/angular/angular/pull/29250