fix(compiler): inherit param types when class has a constructor which…
angular/angular pull request #29232
Opened 2019-03-11 20:53 UTC by bolu

… takes no declared parameters and delegates up

In ReflectionCapabilities, when checking for own parameters of a type, inherit the types properly for classes that do have a constructor, but the constructor takes no declared parameters and just delegates to super(...arguments). This removes the need to declare trivial constructors in such classes to make them work properly in JIT mode. Without this, DI fails and injectables are undefined.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-03-12 18:20 UTC, kara approved these changes
LGTM

2019-03-12 18:26 UTC, alxhub reviewed
Hi @bolu,

How hard do you think it would be to add a test for this fix?

2019-03-12 18:26 UTC, alxhub requested changes
(for the test)

2019-03-12 18:27 UTC, alxhub requested changes
Also, please merge your two commits into one single commit. `git rebase -i` is useful for this.

2019-03-12 18:28 UTC, kara commented
[presubmit](http://test/OCL:238058377:BASE:238058723:1552415133062:b1e4c6c6)

2019-03-14 21:00 UTC, matsko commented
http://test/OCL:238513286:BASE:238513362:1552597194178:27e13635

2019-03-22 20:09 UTC, alxhub approved these changes

2019-03-22 20:14 UTC, closed without merging

2019-05-09 20:25 UTC, petebacondarwin commented
Here are the tests that never appeared in this PR: https://github.com/angular/angular/pull/30368