feat(ivy): use i18n locale data to determine the plural form of ICU expressions
angular/angular pull request #29249
Opened 2019-03-12 14:26 UTC by ocombe

Plural ICU expressions depend on the locale (different languages have different plural forms). Until now the locale was hard coded as `en-US`.
This PR refactors all of the localization code that was previously living in `@angular/common`. Everything but the locale data has been moved to `@angular/core`, making it possible to get the correct plural form. Since we plan on refactoring all of this later and we didn't want to create a breaking change for that now, everything is still publicly exported by `@angular/common`, but the code is actually in `@angular/core`, making it possible to use it in core (core cannot import from common).
For compatibility reasons, if you use ivy with AOT and bootstrap your app with `bootstrapModule` then the `LOCALE_ID` token will be set automatically for ivy, which is then used to get the correct plural form.
⚠️ For JIT you need to call `ɵsetLocaleId` manually to define the `LOCALE_ID` before bootstrap. Same thing if you don't use the compat mode and start your app with `renderComponent`. We expect this to change once we start adding the new i18n APIs, so don't rely on this function (there's a reason why it's a private export).

2019-03-22 19:09 UTC, IgorMinar reviewed
please reexport the symbols and types and reattach the docs to the exports.

afterwards please validate that the api docs look right (the type signatures are correct) on the ngbuilds.io preview server.

2019-03-23 21:22 UTC, kara requested changes

2019-03-23 21:22 UTC, kara commented on packages/core/test/render3/i18n_spec.ts
> +  it('should return the correct plural form for ICU expressions when using a specific locale',
Can you re-write this as a TestBed test and move to the i18n_integration_spec? We shouldn't have any new tests with handwritten generated code.

2019-03-26 14:46 UTC, mary-poppins commented
You can preview d9ff164 at https://pr29249-d9ff164.ngbuilds.io/.
You can preview edc9394 at https://pr29249-edc9394.ngbuilds.io/.
You can preview a9a43c8 at https://pr29249-a9a43c8.ngbuilds.io/.
You can preview d204e5d at https://pr29249-d204e5d.ngbuilds.io/.

2019-03-26 14:52 UTC, mary-poppins commented
You can preview 6b3c5da at https://pr29249-6b3c5da.ngbuilds.io/.

2019-03-26 15:40 UTC, ocombe commented
So I updated the code as requested by @IgorMinar so that it re-exports the symbols. It works for api guard, but we loose the api docs in the process.
![image](https://user-images.githubusercontent.com/265378/55011135-c2740800-4fe5-11e9-8086-550ff0759393.png)

@petebacondarwin seems to think that it will be complicated to fix dgeni for that... not sure what the next move is.
We can duplicate the api docs, but we will still see the wrong code: `type FormStyle = ɵFormStyle;` instead of
```enum FormStyle {
  Format
  Standalone
}```

2019-03-26 17:00 UTC, ocombe commented on packages/core/test/render3/i18n_spec.ts
> +  it('should return the correct plural form for ICU expressions when using a specific locale',
Well actually the locale data def (`ngLocaleIdDef`) isn't defined for test bed, so that wouldn't work :-/

2019-03-27 14:00 UTC, ocombe commented on packages/core/test/render3/i18n_spec.ts
> +  it('should return the correct plural form for ICU expressions when using a specific locale',
I've added a TestBed test, but I kept this one as they don't test the same thing

2019-03-27 14:01 UTC, ocombe commented
Blocked by FW-1207

2019-03-27 14:05 UTC, mary-poppins commented
You can preview bf02a00 at https://pr29249-bf02a00.ngbuilds.io/.

2019-03-27 14:06 UTC, mary-poppins commented
You can preview 66f74e7 at https://pr29249-66f74e7.ngbuilds.io/.

2019-03-29 18:28 UTC, alxhub requested changes

2019-03-29 18:28 UTC, alxhub commented on packages/core/test/application_ref_spec.ts
> +      onlyInIvy('We only need to define `LOCALE_ID` for runtime i18n')
Do we need `ResourceLoader` as part of this test? It could be written without it.

2019-03-29 18:28 UTC, alxhub commented on packages/core/test/i18n_integration_spec.ts
> +       TestBed.overrideProvider(LOCALE_ID, {useValue: 'ro'});
```suggestion
       TestBed.configureTestingModule({providers: [LOCALE_ID, {useValue: 'ro'}]});
```

2019-03-29 18:28 UTC, alxhub commented on packages/core/testing/src/r3_test_bed_compiler.ts
> +  ɵtransitiveScopesFor as transitiveScopesFor, LOCALE_ID,
Sort this into the import list on its own line, please :)

2019-03-29 18:28 UTC, alxhub commented on packages/core/testing/src/r3_test_bed_compiler.ts
> +import {setLocaleId} from '@angular/core/src/render3';
We should try to avoid deep imports. Can these be exported (publicly or privately) from the root of `@angular/core`?

2019-03-29 18:28 UTC, alxhub commented on packages/core/testing/src/r3_test_bed_compiler.ts
> +    const localeId = this.testModuleRef.injector.get(LOCALE_ID);
Should we specify a default here, like we do in `compileNgModuleFactory`?

2019-03-29 19:54 UTC, ocombe commented on packages/core/test/application_ref_spec.ts
> +      onlyInIvy('We only need to define `LOCALE_ID` for runtime i18n')
yes because `compileNgModuleFactory` requires `ResourceLoader`, which is usually provided when you use platform-browser in a real application, but not here in the tests. It throws with an error otherwise...

2019-03-29 19:55 UTC, ocombe commented on packages/core/test/i18n_integration_spec.ts
> +       TestBed.overrideProvider(LOCALE_ID, {useValue: 'ro'});
We already use `configureTestingModule` in `beforeEach`, if I use it here I'll have to re-add the declarations

2019-03-29 19:56 UTC, ocombe commented on packages/core/testing/src/r3_test_bed_compiler.ts
> +import {setLocaleId} from '@angular/core/src/render3';
it is privately exported, updated the code to use that

2019-03-29 20:08 UTC, alxhub approved these changes

2019-03-29 20:08 UTC, alxhub commented on packages/core/test/application_ref_spec.ts
> +      onlyInIvy('We only need to define `LOCALE_ID` for runtime i18n')
I think it's only needed here because the test was copied from another which uses a `templateUrl`. If you don't use a `templateUrl` with the component you shouldn't need the `ResourceLoader`.

2019-03-29 20:08 UTC, alxhub commented on packages/core/test/i18n_integration_spec.ts
> +       TestBed.overrideProvider(LOCALE_ID, {useValue: 'ro'});
`configureTestingModule` is cumulative.

2019-03-29 20:19 UTC, alxhub requested changes
I think the logic in `compileNgModuleFactory` might be wrong.

2019-03-29 20:44 UTC, alxhub approved these changes

2019-03-29 20:44 UTC, alxhub commented on packages/core/src/application_ref.ts
> +      // If the `LOCALE_ID` provider is defined at bootstrap, we set the value for runtime i18n
Maybe expand the comment to mention that this is an Ivy-specific operation?

2019-03-29 20:48 UTC, mary-poppins commented
You can preview fa18cec at https://pr29249-fa18cec.ngbuilds.io/.

2019-03-29 20:58 UTC, mary-poppins commented
You can preview 36de339 at https://pr29249-36de339.ngbuilds.io/.

2019-04-02 20:50 UTC, kara approved these changes

2019-04-05 12:49 UTC, mary-poppins commented
You can preview 40445bb at https://pr29249-40445bb.ngbuilds.io/.

2019-04-05 16:13 UTC, mhevery commented
http://test/OCL:242135545:BASE:242135584:1554480750448:5f91d5e9

2019-04-05 17:01 UTC, mhevery requested changes
Public API guard needs to be fixed.

2019-04-05 17:01 UTC, mhevery commented on packages/common/src/i18n/locale_data_api.ts
> +export type FormatWidth = ɵFormatWidth;
The fact that you have to use `FormatWidth_` is annoying. So I think if you move it into a separate file it would work just fine.

2019-04-08 09:03 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +export type FormatWidth = ɵFormatWidth;
This doesn't work, typescript errors with `Argument of type 'FormatWidth_' is not assignable with parameter of type 'FormatWidth'` whenever I tried to use one of the functions exported by core (and re-exported by common), for example if I do `const formatValue = getLocaleDateFormat(locale, FormatWidth.Short);`

2019-04-08 13:06 UTC, mary-poppins commented
You can preview 670ecc7 at https://pr29249-670ecc7.ngbuilds.io/.

2019-04-08 13:32 UTC, mary-poppins commented
You can preview bcd6fdf at https://pr29249-bcd6fdf.ngbuilds.io/.

2019-04-08 17:25 UTC, mhevery requested changes
Your change will make it so that `core:Plural.ZERO !== common:Plural.ZERO` which is wrong.

61a4dd9304 is a proper fix. Please align rest of the types with it.

2019-04-08 17:29 UTC, mary-poppins commented
You can preview 61a4dd9 at https://pr29249-61a4dd9.ngbuilds.io/.

2019-04-08 17:47 UTC, mary-poppins commented
You can preview 956617f at https://pr29249-956617f.ngbuilds.io/.

2019-04-08 20:30 UTC, mhevery commented on packages/common/src/i18n/locale_data_api.ts
>  export function getLocalePluralCase(locale: string): (value: number) => Plural {
We should not have to have wrapping functions. Can't we just do:
```
export const getLocalePluralCase: .... = ɵgetLocalePluralCase;
```

2019-04-08 20:57 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
>  export function getLocalePluralCase(locale: string): (value: number) => Plural {
if we do that, we loose the public api guard definition (it'll just be an alias instead of the full definition), which would relax our constraints

2019-04-08 20:59 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
>  export function getLocalePluralCase(locale: string): (value: number) => Plural {
actually let me try something

2019-04-08 21:43 UTC, AndrewKushnir approved these changes
LGTM 👍

2019-04-08 22:07 UTC, mhevery requested changes

2019-04-08 22:07 UTC, mhevery commented on packages/core/src/i18n/localization.ts
> +    case 0:
I think you can revert this. The original code was better.

2019-04-09 16:38 UTC, mhevery commented on packages/common/src/common.ts
> +export {registerLocaleData} from './i18n/locale_data';
The issue here is that `Plural` defined in `locale_data` is type information only, no value. So when rollup tries to read the value it blows up.

2019-04-09 16:38 UTC, mhevery commented on packages/common/src/common.ts
> +export {Plural, NumberFormatStyle, FormStyle, Time, TranslationWidth, FormatWidth, NumberSymbol, WeekDay, getNumberOfCurrencyDigits, getCurrencySymbol, getLocaleDayPeriods, getLocaleDayNames, getLoca
`Plural` here contains both type as well as value, hence rollup works.

2019-04-09 18:50 UTC, mhevery approved these changes

2019-04-09 19:07 UTC, kara commented
[presubmit](http://test/OCL:242713752:BASE:242713809:1554836806793:8832bbc)

2019-04-11 15:08 UTC, IgorMinar commented
the last presubmit failed - running an new one: http://test/OCL:243070544:BASE:243070563:1554995271004:b929419d

2019-04-11 15:29 UTC, IgorMinar commented
@ocombe can you please rebase?

2019-04-11 16:07 UTC, ocombe commented
@IgorMinar done

2019-04-15 16:37 UTC, alxhub commented
[Presubmit](https://test.corp.google.com/ui#id=OCL:243629037:BASE:243630442:1555345847096:3f2f1f27) after rebase.

Caretaker note: this PR requires an additional g3 fix to its BUILD file.

2019-04-16 23:33 UTC, alxhub commented
Caretakers: this PR was reverted originally due to its effect on a number of Firebase targets in g3 (it caused build timeouts). This needs to be investigated.

2019-04-17 01:03 UTC, alxhub requested changes
This PR is being held until the start of partner testing. Talk to @alxhub or @kara for context.

2019-05-16 16:40 UTC, alxhub approved these changes

2019-05-20 14:14 UTC, ocombe commented
The size increase check is false (I manually checked against master myself, and the bundle file for hello_world is exactly the same)

2019-05-20 17:06 UTC, jasonaden commented
[Presubmit](http://test/OCL:249071179:BASE:249071208:1558371940116:484e87c6)

2019-05-24 18:00 UTC, matsko commented
@ocombe rebase please

2019-05-27 17:40 UTC, matsko commented
http://test/OCL:250167572:BASE:250167579:1558978723403:5c4448db

2019-05-30 19:11 UTC, closed without merging