update examples region to match the description in the docs
angular/angular pull request #29259
Opened 2019-03-12 18:39 UTC by chembu

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Example snippet was not matching the text description in the doc.
Issue Number: 28147

## What is the new behavior?

Updated example region to match the text description.
## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-03-15 13:05 UTC, brandonroberts commented
@chembu will you rebase to resolve the conflicts?

2019-03-20 16:56 UTC, brandonroberts requested changes

2019-03-20 16:56 UTC, brandonroberts commented on aio/content/examples/router/src/app/heroes/hero-list/hero-list.component.1.html
> +    <!-- #docregion nav-to-detail-->
```suggestion
    <!-- #docregion nav-to-detail -->
```

2019-03-20 16:56 UTC, brandonroberts commented on aio/content/examples/router/src/app/heroes/hero-list/hero-list.component.1.html
> +    <!-- #docregion link-parameters-array-->
```suggestion
    <!-- #docregion link-parameters-array -->
```

2019-03-20 16:56 UTC, brandonroberts commented on aio/content/examples/router/src/app/heroes/hero-list/hero-list.component.1.html
> +      <!-- #enddocregion link-parameters-array-->
```suggestion
      <!-- #enddocregion link-parameters-array -->
```

2019-03-22 14:53 UTC, brandonroberts requested changes

2019-03-22 14:53 UTC, brandonroberts commented on aio/content/examples/router/src/app/heroes/hero-list/hero-list.component.1.html
> +      <!-- #enddocregion link-parameters-array -->
```suggestion
    <!-- #enddocregion link-parameters-array -->
```

2019-03-22 14:53 UTC, brandonroberts commented on aio/content/examples/router/src/app/heroes/hero-list/hero-list.component.1.html
> +      <!-- #enddocregion link-parameters-array -->
The region matchers must line up

2019-03-27 14:04 UTC, brandonroberts commented on aio/content/guide/router.md
> +<code-example path="router/src/app/heroes/hero-list/hero-list.component.html" linenums="false" header="src/app/heroes/hero-list/hero-list.component.html (link-parameters-array)" region="link-paramete
```suggestion
<code-example path="router/src/app/heroes/hero-list/hero-list.component.1.html" linenums="false" header="src/app/heroes/hero-list/hero-list.component.html (link-parameters-array)" region="link-parameters-array">
```

2019-03-27 14:04 UTC, brandonroberts requested changes
Update example path

2019-03-27 15:30 UTC, brandonroberts approved these changes

2019-03-27 15:33 UTC, mary-poppins commented
You can preview f729602 at https://pr29259-f729602.ngbuilds.io/.

2019-03-27 15:38 UTC, mary-poppins commented
You can preview df521f0 at https://pr29259-df521f0.ngbuilds.io/.

2019-03-29 15:41 UTC, mary-poppins commented
You can preview 1c4173e at https://pr29259-1c4173e.ngbuilds.io/.

2019-03-29 18:07 UTC, jasonaden requested changes
This needs a rebase.

Also, can't we remove the `link-parameters-array` section in [`hero-list.component.1.ts`](https://github.com/angular/angular/blob/master/aio/content/examples/router/src/app/heroes/hero-list/hero-list.component.1.ts#L33)?

2019-04-01 22:35 UTC, jasonaden commented
@chembu This is still waiting for the rebase and the change above. Changing to `cleanup` status.

2019-04-02 17:47 UTC, mary-poppins commented
You can preview 197a191 at https://pr29259-197a191.ngbuilds.io/.

2019-04-02 23:08 UTC, jasonaden approved these changes

2019-04-02 23:11 UTC, closed without merging