fix(ivy): do not inject attributes with namespace
angular/angular pull request #29257
Opened 2019-03-12 18:20 UTC by cexbrayat

When injecting with `@Attribute`, namespaced attributes should not match (in order to have feature parity with View Engine).

This PR resolves FW-1137

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: FW-1137

## What is the new behavior?

DI now skips namespaced attributes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-03-12 18:53 UTC, kara requested changes
Thanks for the PR! Change itself looks great, just needs a test update.

2019-03-12 18:53 UTC, kara commented on packages/core/test/render3/di_spec.ts
> +    it('should not inject attributes with namespace', () => {
We're trying to move away from writing generated code by hand, so new tests should be written with TestBed in the `core/test/acceptance` folder. There is another `di_spec` there - can you convert this test?

2019-03-12 20:14 UTC, cexbrayat commented on packages/core/test/render3/di_spec.ts
> +    it('should not inject attributes with namespace', () => {
@kara I gave it a try, but even a simple test to inject an attribute like the following is failing:

```typescript
it('should inject attribute', () => {
  @Component({
    selector: 'my-comp',
    template: '<div exist="existValue"></div>'
  })
  class MyComp {
    constructor(@Attribute('exist') public exist: string) {}
  }

  TestBed.configureTestingModule({declarations: [MyComp]});
  const fixture = TestBed.createComponent(MyComp);
  fixture.detectChanges();
  expect(fixture.componentInstance.exist).toBe('existValue');
});
```
with error:
```
di @Attribute should inject attribute
  Message:
    Expected null to be 'existValue'.
```
Am I missing something obvious?

2019-03-12 20:28 UTC, kara commented on packages/core/test/render3/di_spec.ts
> +    it('should not inject attributes with namespace', () => {
That test doesn't look quite right. It seems like you're trying to inject the `exist` attribute, but in your test, it's inside the template for `MyComp`, rather than on its host node. I think you need a component wrapping `MyComp` that also has an `exists` attribute. e.g.:

```
template: '<my-comp exist="existValue"></my-comp>'
```

2019-03-12 20:32 UTC, cexbrayat commented on packages/core/test/render3/di_spec.ts
> +    it('should not inject attributes with namespace', () => {
Argh, of course, sorry...

2019-03-12 20:44 UTC, cexbrayat commented on packages/core/test/render3/di_spec.ts
> +    it('should not inject attributes with namespace', () => {
@kara OK done! I pushed a fixup commit to let your review.
Would it be useful to migrate all the other `@Attribute` tests as well?

2019-03-13 00:26 UTC, kara commented on packages/core/test/render3/di_spec.ts
> +    it('should not inject attributes with namespace', () => {
Yes, that would be super helpful! But perhaps in a separate PR?

2019-03-13 00:27 UTC, kara approved these changes
LGTM. Just needs a rebase!

2019-03-13 00:29 UTC, kara commented
[presubmit](http://test/OCL:238132911:BASE:238132962:1552436925034:a3001251)

2019-03-13 13:01 UTC, cexbrayat commented
@kara I rebased 👍 Note that I updated the test to make it look like the one added in #29192 I also wrapped them in a test suite, as it was the case in `render3/di_spec.ts`.

I'll start working on migrating the existing tests in DI when this is merged. Let me know if I need to assign myself on a Jira ticket (I didn't find one, but maybe I missed it).

2019-03-14 07:09 UTC, closed without merging