fix(ivy): ensure template styles/classes are applied before directives are instantiated
angular/angular pull request #29269
Opened 2019-03-12 21:33 UTC by matsko

Angular Ivy interprets inline static style/class attribute values as instructions that
are processed whilst an element gets created. Because these inline style values are
referenced by style/class bindings, their inline style values are applied at a later
stage. Despite them being eventually applied, their values should be applied earlier
before any directives are instantiated so that directive code can rely on any inline
style/class changes.

This patch ensures that all static style/class attribute values are applied (rendered)
on the element before directives are instantiated.

Jira Issue: FW-1133

2019-03-12 22:43 UTC, matsko commented
https://tap.corp.google.com/ui#id=OCL:238107081:BASE:238111662:1552430037504:1125e5a5

2019-03-12 23:48 UTC, kara requested changes

2019-03-12 23:48 UTC, kara commented on tools/material-ci/angular_material_test_blocklist.js
> +    "notes": "Unknown"
Looks like the root causes of these stepper tests has been overwritten (seems like you need to re-run the install script from angular master?). Can you restore the root causes?

2019-03-12 23:48 UTC, kara commented on tools/material-ci/angular_material_test_blocklist.js
> +    "notes": "Unknown"
Same here. Can you restore the root cause? I think the script may have messed up here because the hash generated in the error changed.

2019-03-12 23:48 UTC, kara commented on tools/material-ci/angular_material_test_blocklist.js
> +    "notes": "Unknown"
Same here

2019-03-12 23:48 UTC, kara commented on tools/material-ci/angular_material_test_blocklist.js
>      "error": "TypeError: Cannot read property 'nativeElement' of undefined",
This change should have fixed the two `MatTooltip` tests marked FW-1133, but they still look like they're broken? Can you determine why?

2019-03-12 23:48 UTC, kara commented on packages/core/src/render3/instructions.ts
> +  // we render the styling again below incase any directives have set any `style` and/or
```suggestion
  // we render the styling again below in case any directives have set any `style` and/or
```

2019-03-14 21:13 UTC, kara commented on packages/core/src/render3/instructions.ts
> +  // we render the styling again below incase any directives have set any `style` and/or
^ Can you fix? Missed the original one :-)

2019-03-14 21:13 UTC, kara commented on tools/material-ci/angular_material_test_blocklist.js
> +    "notes": "Unknown"
Can you address? ^

2019-03-14 21:18 UTC, kara approved these changes
LGTM

2019-03-14 21:22 UTC, matsko commented
https://tap.corp.google.com/ui#id=OCL:238107081:BASE:238517919:1552598414574:fbe497ed

2019-03-14 22:24 UTC, closed without merging