Add API doc for pipes/i18n config
angular/angular pull request #29289
Opened 2019-03-13 22:24 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Doc missing or unclear or not placed properly

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-03-14 13:29 UTC, ocombe requested changes

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/format_date.ts
> + * @param locale The locale code.
Maybe add a link to the locale section in the i18n guide here?

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/format_number.ts
> +import { NumberFormatStyle, NumberSymbol, getLocaleNumberFormat, getLocaleNumberSymbol, getNumberOfCurrencyDigits } from './locale_data_api';
you need to run `gulp format` to avoid those formatting error (the lint job fails)

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/format_number.ts
> + * @param locale A locale code for the locale format rules to use.
Maybe add a link to the locale section in the i18n guide here?
Also you should have the same description for all `locale` params of all of those functions. Right now the description is different but it's talking about the same thing. For example for `formatDate` it says `@param locale The locale code.`.

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/format_number.ts
> + * @param currency A string containing the currency symbol or its name, such as "$" or "Canadian Dollar".
It should be made clear that this will be used in the output string once formatted, but it has no impact whatsoever on the function itself. You can literally use anything you want.

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/format_number.ts
> + * @returns The formatted number.
`currency` instead of `number`?

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/format_number.ts
> + * @param locale A locale code for the locale format rules to use.
same comments as above

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/format_number.ts
> + * @returns The formatted number.
`percentage` instead of `number`?

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/format_number.ts
> + * configuration based on the locale.
`parameters` instead of `configuration`?

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> + * Examples are given for the word "Sunday" in English.
You talk about examples but you removed it. I don't think that inline comments will be visible on the API docs.

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +   */
Same thing here, can you check if inline comments are visible in the API docs?

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> + * @param locale A locale code, such as `fr-FR`.
Maybe add a link to the locale section in the i18n guide here?

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> + * @param locale The locale code.
Maybe add a link to the locale section in the i18n guide here?
And use the same text as the other `locale` params.

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> + * @param locale The locale code.
same as above

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> + * @param locale The locale code.
Same as above.

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> + * @param locale The locale code.
Same as above.

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> + * @param locale The locale code.
Same as above.

2019-03-14 13:29 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> + * For example, for the default `en` locale, the code `USD` can
`en-US` instead of `en`

2019-03-14 13:29 UTC, ocombe commented on packages/core/src/di/injector_compatibility.ts
> + *
Not sure what this is doing in the i18n docs PR, it probably should be in another PR?

2019-03-14 15:07 UTC, ocombe commented on packages/common/src/i18n/locale_data_api.ts
> +  /** 2 characters, For example: "Su" */
That's why the api docs above say "examples are for `en-US`"

2019-03-14 15:11 UTC, trotyl commented on packages/common/src/i18n/locale_data_api.ts
> +  /** 2 characters, For example: "Su" */
Yep, but `2 characters` here is posted before `For example`, which sounds like description.

2019-03-14 15:51 UTC, jbogarthyde commented on packages/core/src/di/injector_compatibility.ts
> + *
Started this branch just looking for stuff to fix - I'll leave this in, but won't add anything more outside i18n for this PR.

2019-03-19 16:30 UTC, mary-poppins commented
You can preview 5d271ad at https://pr29289-5d271ad.ngbuilds.io/.

2019-03-19 16:46 UTC, mary-poppins commented
You can preview dd9b11a at https://pr29289-dd9b11a.ngbuilds.io/.

2019-03-20 15:55 UTC, mary-poppins commented
You can preview e7445a0 at https://pr29289-e7445a0.ngbuilds.io/.

2019-03-20 16:29 UTC, mary-poppins commented
You can preview 9c54f7c at https://pr29289-9c54f7c.ngbuilds.io/.

2019-03-21 16:03 UTC, mary-poppins commented
You can preview f998309 at https://pr29289-f998309.ngbuilds.io/.

2019-03-21 17:27 UTC, ocombe approved these changes

2019-03-21 17:41 UTC, jbogarthyde commented on packages/common/src/i18n/locale_data_api.ts
> +   */
Yes, the description with example is shown for each member.

2019-03-21 17:42 UTC, jbogarthyde commented on packages/common/src/i18n/locale_data_api.ts
> + * Examples are given for the word "Sunday" in English.
Yes, the member descriptions with the examples are shown.

2019-03-21 19:41 UTC, mary-poppins commented
You can preview ea309e6 at https://pr29289-ea309e6.ngbuilds.io/.

2019-03-25 15:54 UTC, mary-poppins commented
You can preview 1fd6fd6 at https://pr29289-1fd6fd6.ngbuilds.io/.

2019-03-26 16:55 UTC, mary-poppins commented
You can preview 7b085da at https://pr29289-7b085da.ngbuilds.io/.

2019-03-27 16:31 UTC, mary-poppins commented
You can preview dd54b3f at https://pr29289-dd54b3f.ngbuilds.io/.

2019-03-27 16:32 UTC, mary-poppins commented
You can preview 14b099d at https://pr29289-14b099d.ngbuilds.io/.

2019-03-28 15:54 UTC, mary-poppins commented
You can preview d20587c at https://pr29289-d20587c.ngbuilds.io/.

2019-03-28 22:17 UTC, mhevery approved these changes

2019-03-29 17:29 UTC, closed without merging