docs: no network request for performance strategy
angular/angular pull request #29288
Opened 2019-03-13 21:20 UTC by Jun711

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
It adds clarification to the users that no network requests will be sent if strategy is performance. Some might be confused that cache is first used while waiting for a network request.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2019-03-15 12:48 UTC, brandonroberts commented
Thanks for the PR @Jun711! You must [Sign the CLA](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#cla) before this PR can move forward.

2019-03-15 17:24 UTC, Jun711 commented
I signed it!

2019-03-27 13:02 UTC, brandonroberts requested changes

2019-03-27 13:02 UTC, brandonroberts commented on aio/content/guide/service-worker-config.md
> +* `performance`, the default, optimizes for responses that are as fast as possible. If a resource exists in the cache, the cached version is used, there will be no request from the network at all. Th
```suggestion
* `performance`, the default, optimizes for responses that are as fast as possible. If a resource exists in the cache, the cached version is used, and no network request is made. This allows for some staleness, depending on the `maxAge`, in exchange for better performance. This is suitable for resources that don't change often; for example, user avatar images.
```

2019-03-29 14:54 UTC, brandonroberts approved these changes

2019-03-29 16:19 UTC, gkalpak approved these changes
The commit message should be `docs(service-worker): ...`.
Other than that LGTM 👍

2019-03-29 17:30 UTC, closed without merging