refactor(ivy): add new view container api
angular/angular pull request #29339
Opened 2019-03-15 19:25 UTC by benlesh

- Adds view container API in preparation to refactor how we insert embedded views (#28031)
- Fixes minor issue with `i18n` that was revealed by an added assertion.

2019-03-15 21:06 UTC, benlesh commented
[presubmit](https://test.corp.google.com/ui#id=OCL:238706797:BASE:238706859:1552683980262:ff4002cd)

2019-03-15 22:03 UTC, mhevery requested changes
Needs public API cleanup otherwise LGTM.

2019-03-15 22:03 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> + * This interface replaces the real {@link LView} interface if it is an argument or the return value
This comment is public API and needs to be written from the developers point of view and can't talk about internal implementation details such as `LView`. Because it is public API it needs first paragraph to be a singe sentence of what it is which will show up in index. The remaining paragraphs should talk about how to use it etc...

2019-03-15 22:03 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> + * This interface replaces the real {@link LContainer} interface if it is an argument or the return
Same here, this is public API

2019-03-15 22:03 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> + * The public API for creating an embedded view.
needs better public API text.

2019-03-15 22:07 UTC, benlesh commented on packages/core/src/render3/node_manipulation.ts
> +export function insertLContainerIntoParentLView(
insert
> place, fit, or thrust (something) into another thing, especially with care.

attach
> fasten; join.

I'd like to stay with `insert` here, I think. To me `attach` is like sticking tape on something, where `insert` means more to place something carefully inside of another thing. Which I think is what we're doing here.

2019-03-15 22:09 UTC, benlesh commented on packages/core/src/render3/node_manipulation.ts
> +  // directives that inject ViewContainerRef.
Haha.. Actually, this comment was added alongside @kara after her review. Basically, the alternative was to traverse TNodes, but that would not always work, because we are inserting Views that could be dynamically added using ViewContainerRefs.

2019-03-18 14:14 UTC, ocombe requested changes

2019-03-18 14:14 UTC, ocombe commented on packages/core/src/render3/i18n.ts
>          previousOrParentTNode.index << I18nMutateOpCode.SHIFT_REF | I18nMutateOpCode.Select);
I believe that `previousOrParentTNode.index` is wrong, it should be `previousOrParentTNode.index - HEADER_OFFSET`. Could you fix that as well please?
And we should probably add a test that catches this error.

2019-03-18 16:06 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +        previousOrParentTNode.index - HEADER_OFFSET << I18nMutateOpCode.SHIFT_REF |
I believe that `<<` is taking priority over the `-` operation, you probably need to use parenthesis for that (I'm not 100% sure, I don't use bitwise operations often)

2019-03-18 16:36 UTC, benlesh commented on packages/core/src/render3/i18n.ts
> +        previousOrParentTNode.index - HEADER_OFFSET << I18nMutateOpCode.SHIFT_REF |
`+`, `-`  and run _just_ before bitwise operations like `<<`, this is fine. :) 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

2019-03-18 17:16 UTC, ocombe approved these changes

2019-03-18 17:45 UTC, mhevery requested changes

2019-03-18 17:45 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> + * Represents Angular view data.
```suggestion
 * Represents Angular View.
```
The fact that it is data is internal concern not external.

2019-03-18 17:45 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> + * This interface replaces the real {@link LView} interface if it is an argument or the return value
You need to remove `LView` reference from public API. This documentation should instead talk about what `View` is for the external user.

2019-03-18 17:45 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> + * Represents Angular view container data
```suggestion
 * Represents Angular View container.
```

2019-03-18 17:45 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> + * This interface replaces the real {@link LContainer} interface if it is an argument or the return
Same issue here. `LContainer` is private API which we should not discussed on public interface.

2019-03-18 17:45 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> + * Creates a {@link View} instance by instantiating all view data and passing the provided `context`
- first paragraph needs to be one sentence of what it is
- Remove private types

2019-03-18 17:45 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> +export interface EmbeddedViewFactoryInternal<T extends{}> {
Needs public API

2019-03-18 17:45 UTC, mhevery commented on packages/core/src/render3/view.ts
> + * Gets an {@link EmbeddedViewFactory} that will produce an embedded view.
```suggestion
 * Gets an {@link EmbeddedViewFactory} that will produce an embedded view.
 
```

Needs line break.

2019-03-18 17:45 UTC, mhevery commented on packages/core/src/render3/view.ts
> + * Gets a {@link ViewContainer} instance from a container comment DOM node (`<!-- container -->`),
Needs title paragraph

2019-03-18 17:45 UTC, mhevery commented on packages/core/src/render3/view.ts
> + * Searches the `viewContainer` for a the first instance of a given `view` and returns its index
title paragraph

2019-03-18 17:45 UTC, mhevery commented on packages/core/src/render3/view.ts
> + * Used to remove (embedded) views from a container. Will detach the view and destroy it, and will
title paragraph

2019-03-18 17:45 UTC, mhevery commented on packages/core/src/render3/view.ts
> + * Gets the number of views in the container.
title paragraph

2019-03-18 17:45 UTC, mhevery commented on packages/core/src/render3/view.ts
> + * Retrieves a view from a container by index.
title paragraph

2019-03-18 18:21 UTC, benlesh commented on packages/core/src/render3/interfaces/view.ts
> +export interface EmbeddedViewFactoryInternal<T extends{}> {
I *think* you mean you want a doc comment, so I'll add one. :+1:

2019-03-18 21:12 UTC, mhevery approved these changes

2019-03-18 22:20 UTC, benlesh commented
@kara... responding to your other comment [here](https://github.com/angular/angular/pull/29031#discussion_r265669856)

> It seems like to use this functionality, there are several different standalone functions that need to be imported separately. Is there a reason we're not putting them on a class to reduce the number of imports users have to write?

TMK, class methods don't tree-shake, and we should provide users individual functions for these things to help reduce bundle size.

2019-03-18 22:28 UTC, kara commented
@benlesh That makes sense. I suppose slightly reduced ergonomics is a good tradeoff for the tree-shaking?

2019-03-18 23:40 UTC, benlesh commented
[new presubmit](https://test.corp.google.com/ui#id=OCL:238706797:BASE:239087131:1552952385926:67e448e0)

2019-03-19 02:16 UTC, kara requested changes

2019-03-19 23:17 UTC, benlesh commented on packages/core/src/render3/node_manipulation.ts
> + * This assures that the linked list of {@link LView} instances is in the same order as they
LOL... oops. :man_facepalming:

2019-03-19 23:21 UTC, benlesh commented on packages/core/src/render3/view.ts
> +  const lContext = getLContext(containerComment);
IIRC, I got them working in my follow up PR, so yes. Although, it's worth an offline discussion with @mhevery to confirm.

2019-03-19 23:23 UTC, benlesh commented on packages/core/src/render3/view.ts
> + * inserted behind. If `null`, we will insert the view at the end of the container.
The comment is wrong.

2019-03-19 23:26 UTC, benlesh commented on packages/core/src/render3/view.ts
> + * Searches the `viewContainer` for a the first instance of a given `view` and returns its index
I was just being precise in my verbiage. This function doesn't have knowledge of how we're inserting views, only how to find the first one of a particular reference.

2019-03-19 23:31 UTC, kara commented on packages/core/src/render3/view.ts
> + * Searches the `viewContainer` for a the first instance of a given `view` and returns its index
I see what you're saying, but I think the way it's phrased is confusing. It's optimizing for a case we should never encounter if things are working correctly.

2019-03-19 23:57 UTC, benlesh commented on packages/core/test/acceptance/view_spec.ts
> +         viewContainerInsertAfter(container, view, null);
Resolved this. I also added an additional test to make sure that `viewContainerInsertAfter` performs a move if you try to "re-insert" a view.

2019-03-20 19:34 UTC, kara commented on packages/core/src/render3/view.ts
> +export function getViewContainer(containerComment: RComment): ViewContainer|null {
Is the type of this arg correct?  Here and in the docs comment above, it implies that only comments should be supported, but you have a test [here](https://github.com/angular/angular/pull/29339/files#diff-9c4a5bd39a10cbff63fa0ffbd9a656fdR60) that passes in a `<div>` element.

If we expect this to work with non-comment elements (and already have a test for it), we should update the function signature and docs comment.

```suggestion
export function getViewContainer(containerHost: RElement | RComment): ViewContainer|null {
```

2019-03-20 19:34 UTC, kara commented on packages/core/src/render3/view.ts
> +          createLContainer(hostNode as RComment | RElement, lView, containerComment, true);
If we expect this to work with elements, we can't pass in the unwrapped `hostNode` as the first arg here. It will overwrite any styling context or component view associated with that element. It needs the raw value.

Can we add a test for this?

2019-03-20 19:34 UTC, kara commented on packages/core/src/render3/view.ts
> +        insertAfterLView ? getLastRootElementFromView(insertAfterLView) : commentNode;
What happens if the last TNode of the `insertAfterLView` is an instantiated template?  Wouldn't the nodes from that template be inserted after the comment node? So the next sibling (for the `beforeNode`) would be the first root node of the template. It seems like we should have a test for this.

2019-03-20 19:38 UTC, pkozlowski-opensource commented on packages/core/src/render3/view.ts
> +export function getViewContainer(containerComment: RComment): ViewContainer|null {
Yep, this was my question as well....

2019-03-20 21:59 UTC, benlesh commented on packages/core/src/render3/view.ts
> +        insertAfterLView ? getLastRootElementFromView(insertAfterLView) : commentNode;
I've added a test for this case.  :+1:

2019-03-20 22:25 UTC, benlesh commented on packages/core/src/render3/view.ts
> +export function getViewContainer(containerComment: RComment): ViewContainer|null {
Actually changed to `containerNative` to align with where it is stored in `LContainer`.

2019-03-20 22:37 UTC, pkozlowski-opensource commented on packages/core/src/render3/interfaces/view.ts
> + *
Comment above doesn't match my mental model of what is going on. The way I have it in my had is that:
* it all starts with an element in a template (by "element" here I mean either a regular DOM element, `<ng-container>` or `<ng-template>`);
* an element can have one or more directives "sitting" on it (an element is a host for a directive);
* any directive can _ask_ for a `ViewContainer` and then _anyone_ having access to a `ViewContainer` can insert views into this container;
* the host element of a `ViewContainer` acts as an "anchor" point so we know where to insert view nodes in the DOM.

Assuming that the above is correct those parts of the comment don't match my understanding:

> An Angular View container is associated with views

I would say: Views are inserted into a ViewContainer

> directives and components that dynamically add and remove views

I would rather say: "directives that _ask_ for a ViewContainer" on a given element.

>  A container can be selected by passing a `<!-- container -->` DOM element to

This part is confusing for me, I don't understand what you are trying to say here. My understanding is that a _directive_ can _ask_ for (an existing or a new) ViewContainer on any element (so it doesn't have to be a comment node). Also, maybe "retrieved" would be a better wording as compared to "selecting"?

I'm not sure if my understanding of the model is not correct or the PR is changing things (or both)... Would love to clarify.

2019-03-21 15:21 UTC, pkozlowski-opensource commented on packages/core/src/render3/util/view_utils.ts
> +export function getLastRootElementFromView(lView: LView): RNode {
So I know that this PR is part of the larger effort and my understanding was that we want to insert view nodes _before_ another view (still _after_ container's comment node) - at leat this is what I've understood from Misko's doc. Somehow I was expecting something like `getFirstNativeNodeFromView` - would love to clarify this...

2019-03-21 15:24 UTC, pkozlowski-opensource commented on packages/core/src/render3/view.ts
> +export function getViewContainer(containerNative: RElement | RComment): ViewContainer|null {
I feel uneasy about the fact that we use DOM as a thing on which a `ViewContainer` is sitting. I would expect that we are using a logical tree here (LView + TNode). Could we discuss this in more details? 

Also the comment about the comment node should be updated :-)

2019-03-21 15:26 UTC, pkozlowski-opensource commented on packages/core/src/render3/view.ts
> +    viewContainer: ViewContainer, view: View, insertAfterView: View | null): void {
Could you elaborate on the API choices here? Why is it `insertAfterView` and not index / `insertBeforeView`? Asking since my understanding was that we want to insert _before_ other views (still after container comment node) and view engine is using indexes...

2019-03-22 10:34 UTC, pkozlowski-opensource commented on packages/core/src/render3/util/view_utils.ts
> +export function getLastRootElementFromView(lView: LView): RNode {
My understanding is that using doing "insert before another view"  we could use `getBeforeNodeForContainedView`  and this function here wouldn't be needed at all. This would save us ~20 LOC :-)

2019-03-22 10:56 UTC, pkozlowski-opensource commented on packages/core/src/render3/util/view_utils.ts
> +export const viewContainerToLContainer: (view: ViewContainer) => LContainer =
This and another conversion functions above are only needed since:
* we are introducing new public APIs 
* we are using those newly introduced APIs internally.

This adds more code to the framework, introduces more concepts and makes the whole mental model harder to follow - now we've got 2 public APIs for a view (`View` and `ViewRef`) and container (`ViewContainer` and `ViewContainerRef`). 

With all those drawbacks and no clear benefits I think that we should remove those new APIs and their usage from this PR.

2019-03-22 11:01 UTC, pkozlowski-opensource commented on packages/core/src/render3/view.ts
> +export function viewContainerLength(viewContainer: ViewContainer): number {
This function is only needed since we are introducing new public APIs here which are _different_ from `ViewContainerRef` but don't seem to be _significantly_ different nor clearly better as compared to the existing APIs.

For example, it is not clear how `viewContainerLength(lContainerInstance)` is "better" as compared to `viewContainerRef.length`... 

Unfortunately at this point I see just more code and concepts with no clear benefits...

2019-03-22 18:52 UTC, benlesh commented on packages/core/src/render3/view.ts
> +export function viewContainerLength(viewContainer: ViewContainer): number {
Resolved via offline discussion.

2019-03-22 18:52 UTC, benlesh commented on packages/core/src/render3/util/view_utils.ts
> +export const viewContainerToLContainer: (view: ViewContainer) => LContainer =
Discussed offline.

2019-03-22 18:53 UTC, benlesh commented on packages/core/src/render3/view.ts
> +    viewContainer: ViewContainer, view: View, insertAfterView: View | null): void {
Switched to insert before behavior.

2019-03-22 18:53 UTC, benlesh commented on packages/core/src/render3/view.ts
> +export function getViewContainer(containerNative: RElement | RComment): ViewContainer|null {
Comment updated, the rest was discussed offline.

2019-03-22 19:22 UTC, benlesh commented on packages/core/src/render3/util/view_utils.ts
> +export function getLastRootElementFromView(lView: LView): RNode {
I've refactored to try to use some existing methods. The `getFIrstNativeFromView` wasn't a round fit, so I left a `TODO` that we should refactor this. I suspect there is a refactoring pass where we could clean up a lot of duplicate code around simple tasks here. I'd do that in this PR, but this PR has already sprawled enough, IMO.

2019-03-22 19:31 UTC, benlesh commented on packages/core/src/render3/interfaces/view.ts
> + *
Doc comment has been updated.

2019-03-25 15:24 UTC, benlesh commented
[new presubmit](https://test.corp.google.com/ui#id=OCL:238706797:BASE:240142830:1553527361819:d313369)

2019-03-25 22:07 UTC, benlesh commented
We're putting this on a backburner until ivy lands in g3.

2019-04-23 07:46 UTC, trotyl commented
> TMK, class methods don't tree-shake, and we should provide users individual functions for these things to help reduce bundle size.

@benlesh What about providing them in a secondary path? Then it can be used with namespace import like:

```typescript
import * as viewHelpers from '@angular/core/view'

class Foo {
  someMethod() {
    viewHelpers.insertBefore(viewContainer, view, null)
    const length = viewHelpers.lengthOf(viewContainer)
  }
}
```

It's still tree-shakable but seems more ergonomic to me.

2020-08-22 17:21 UTC, closed without merging