refactor(ivy): Update query-related comments
angular/angular pull request #29342
Opened 2019-03-15 20:20 UTC by benlesh

Just updating comments in query-related things to make it easier for the next person that has to grok this for the first time.

Also adds a demo from @mhevery to one of the query specs

Related #29031

2019-03-15 20:45 UTC, AndrewKushnir approved these changes
LGTM!

2019-03-15 21:42 UTC, kara requested changes

2019-03-15 21:42 UTC, kara commented on packages/core/src/render3/query.ts
> + * @returns `true` if a query got dirty during change detection, `false` otherwise.
Can you update this based on my comment on your other pr? It's not quite accurate for static queries

2019-03-15 21:51 UTC, mhevery approved these changes

2019-03-15 21:51 UTC, mhevery commented
Please address @kara's comment, LGTM otherwise.

2019-03-16 00:35 UTC, benlesh commented on packages/core/src/render3/query.ts
> + * @returns `true` if a query got dirty during change detection, `false` otherwise.
I suspect you mean this comment? https://github.com/angular/angular/pull/29031#discussion_r265406725

2019-03-18 01:03 UTC, kara approved these changes
LGTM

2019-03-18 17:23 UTC, benlesh commented
Caretaker: @kara and @mhevery are global approvers.

2019-03-18 21:06 UTC, matsko commented
This made master fail. Please rebase.

2019-03-18 21:39 UTC, closed without merging