refactor(ivy): update TNodeType
angular/angular pull request #29343
Opened 2019-03-15 20:40 UTC by benlesh

- Remove an extra type `ViewOrElement`, which even had the same numeric value as `View`.
- Updates comment to remove part about alleged bit-masking that we could be doing here.
  We aren't using this with bitmasks, and if we were, everything would be a `NodeType.Container`,
  because it's value was `0`.
- Updates the number values to be simple, human-readable integers, since we're not using these
  with any kind of bit-manipulation.
- Add comments about each type.

2019-03-15 20:45 UTC, AndrewKushnir approved these changes
LGTM!

2019-03-15 20:52 UTC, benlesh commented
[presubmit](http://test/OCL:238703994:BASE:238704083:1552683092709:ded1c07a)

2019-03-15 21:41 UTC, kara requested changes
One small thing

2019-03-15 21:41 UTC, kara commented on packages/core/src/render3/interfaces/node.ts
> +   * The TNode contains information about a container comment {@link RNode}.
I would say ng-container somewhere in here, since the comment is an implementation detail

2019-03-15 22:02 UTC, kara approved these changes
LGTM

2019-03-16 00:09 UTC, benlesh commented
Caretaker: CI flakes with this PR.

2019-03-18 14:17 UTC, closed without merging