refactor(ivy): Add i18n create op codes debug info
angular/angular pull request #29348
Opened 2019-03-15 23:53 UTC by benlesh

Friday late-afternoon hack!

Simply adds a `debug` property to the array of create opcodes while inside
`readCreateOpCodes` in i18n. This `debug` property has a property called `operations`
that is a human-readable list of operations that will be performed, as derived
from the op codes themselves, and the view it's acting upon.

![debug_i18n_cropped](https://user-images.githubusercontent.com/1540597/54467515-ce88db80-4742-11e9-8c90-788d1fa9bfd0.png)

2019-03-16 02:09 UTC, mhevery requested changes
I ❤️ it! Do you think you could add single sanity test for it.

2019-03-16 06:48 UTC, ocombe approved these changes
That's great! Could you do that for update codes as well?

2019-03-18 17:12 UTC, benlesh commented
@mhevery I've pinged @ocombe to help me come up with an appropriate sanity test.

@ocombe - I'd love to add this for update codes and the like as well, but I haven't had to deal with those yet. Why don't we just land this helper now, and perhaps add the others later if this one works out?

2019-03-18 17:52 UTC, mhevery commented
I am pretty sure that @IgorMinar will kick it out during release review because it has no test.

2019-03-21 17:01 UTC, benlesh reviewed
Your additions LGTM, @ocombe!

2019-03-21 19:26 UTC, mhevery commented on packages/core/src/render3/interfaces/i18n.ts
> +  debug?: I18nOpCodesDebug;
Why do you think this is needed? we don't do it for `LView`

2019-03-21 19:26 UTC, mhevery commented on packages/core/src/render3/interfaces/i18n.ts
> +  debug?: I18nOpCodesDebug;
same here

2019-03-21 19:29 UTC, mhevery commented on packages/core/test/render3/i18n_spec.ts
> +        update: jasmine.objectContaining([
Why do we have to change all of this code?

2019-03-21 22:39 UTC, benlesh commented on packages/core/src/render3/interfaces/i18n.ts
> +  debug?: I18nOpCodesDebug;
I agree. this isn't needed.

2019-03-21 22:39 UTC, benlesh commented on packages/core/test/render3/i18n_spec.ts
> +        update: jasmine.objectContaining([
I think @ocombe added this because `debug` was now poluting the tests and making them harder to check with deep-equality?

We can probably just have a helper method strip the `debug` property off prior to the test. That should clean this up.

2019-03-22 00:06 UTC, benlesh commented on packages/core/test/render3/i18n_spec.ts
> +        update: jasmine.objectContaining([
I think I said this elsewhere, but I think @ocombe was trying to circumvent the fact that the deep-equality check was picking up the debug property. I've reverted that change in favor of just removing the property prior to the check.

2019-03-25 15:35 UTC, benlesh commented
Rebased and pushed.

[presubmit here](http://test/OCL:240144754:BASE:240144795:1553528084898:ee7b4e15)

2019-03-27 22:28 UTC, mhevery requested changes

2019-03-27 22:28 UTC, mhevery commented on packages/core/test/render3/i18n_spec.ts
> +  delete (opCodes.create as any).debug;
Instead of deleting all of the debug elements can't we just make them non-enumerable and that way this would not be needed? See other comment.

2019-03-27 22:28 UTC, mhevery commented on packages/core/src/render3/debug.ts
> +  (mutateOpCodes as any).debug = new I18nMutateOpCodesDebug(mutateOpCodes, lView);
Patching this property seems to be causing some tests to fail. Could we make the property non-enumerable?

```
function attachDebugObject(obj: any, debug: any) {
  Object.defineProperty(obj, 'debug', {value: debug, enumerable: false});
}
```

2019-03-29 16:49 UTC, benlesh commented
New [presubmit](http://test/OCL:240876341:BASE:240996195:1553878074823:b8b8533f)

2019-03-29 19:20 UTC, benlesh commented
Addressed comments, rebased and pushed... [new presubmit](http://test/OCL:240144754:BASE:241027824:1553887162308:a34752f9)

2019-03-30 01:52 UTC, mhevery approved these changes

2019-03-30 01:52 UTC, mhevery commented on packages/core/src/render3/debug.ts
> +  Object.defineProperty(obj, 'debug', {value: debug, enumerable: false});
can you change  on line 54 (sorry can't comment there)

```
export function attachLContainerDebug(lContainer: LContainer) {
  (lContainer as any).debug = new LContainerDebug(lContainer);
}
```

to: 

``` 
export function attachLContainerDebug(lContainer: LContainer) {
  attachDebugObject(lContainer, new LContainerDebug(lContainer));
}
```

2019-04-01 15:39 UTC, benlesh commented on packages/core/src/render3/debug.ts
> +  Object.defineProperty(obj, 'debug', {value: debug, enumerable: false});
Done for lContainer and lView debug.

2019-04-02 22:00 UTC, benlesh commented
I had to refactor the nodes in the debug to be classes, because Closure compiler didn't like getters on POJOs.

[new presubmit](https://test.corp.google.com/ui#id=OCL:240144754:BASE:241610570:1554242296705:7c71fdfb)

2019-04-02 22:28 UTC, benlesh commented
And *another* [presubmit](https://test.corp.google.com/ui#id=OCL:240144754:BASE:241615864:1554243921007:abe8b65c) to meet google3 typescript requirements http://go/ts-conformance#property-renaming-safe

2019-04-03 22:56 UTC, closed without merging