Insert after comment
angular/angular pull request #29340
Opened 2019-03-15 20:08 UTC by benlesh

- Moves embedded view management to insert nodes *after* the `` comment, rather than before.
- Updates several tests that were relying on node order in the DOM
- Updates animation renderer to ensure that the proper pathways are invoked if we are inserting embedded views for things like `*ngFor` or `*ngIf`, et al.

This is part of what was #29031.

Blocked waiting for #29339

2019-03-16 08:35 UTC, gkalpak commented
Could you, please, add more context in the commit messages (e.g. why changing the insertion location from _before_ to _after_)? 🙏
I see #29031 has more info. It would be good to capture that in the commit messages (and ideally in this PR's description too). It makes it esier to reasona about the changes when looking back in git file/line history etc.

2019-03-18 14:30 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +    // This is highly suspect, IMO, but it seems to have things working.
Hmm yes this is probably not a good idea, you're just patching the issue and not fixing the bug here.
What are the cases where the nodes are not added to the intended parent? If you have a repro I can take a look at it and fix it for real

2019-03-18 14:33 UTC, ocombe commented on packages/core/test/i18n_integration_spec.ts
> +    fixmeIvy('FW-1166: i18n not removing TNodes properly')
FW-1166 was merged into master, could you remove the `fixmeIvy` here?

2019-03-18 14:34 UTC, ocombe requested changes
Looks ok for i18n except for the `fixmeIvy` that you should revert and the "hack" with icu comment nodes (it can stay like that for now, but please create an issue with a repro so that I can fix the real cause)

2019-03-18 17:14 UTC, benlesh commented
@gkalpak and @ocombe - Just to over-communicate a little: I'm not ignoring your reviews, but I'll address them once #29339 is merged (as it's a blocker) <3

2019-03-22 09:58 UTC, pkozlowski-opensource commented on packages/animations/browser/src/render/animation_engine_next.ts
> +    this._transitionEngine.insertNode(namespaceId, element, parent, shouldCollectEnterElement);
Would be great if code readability improvements are done in a separate PR (or at least in a separate commit). Having minor edits like this mixed with API changes makes it harder to review and focus on the essence of a PR. I know that it requires more work on the PR author but it significantly helps review efforts (and usually there are more reviewers than authors :-))

2019-03-22 09:58 UTC, pkozlowski-opensource commented on packages/animations/browser/src/render/transition_animation_engine.ts
> +    if (shouldCollectEnterElement) {
Would be great if code readability improvements are done in a separate PR (or at least in a separate commit).

2019-03-22 10:06 UTC, pkozlowski-opensource commented on packages/core/src/render3/component_ref.ts
> +        createElementRef(viewEngine_ElementRef, tElementNode, rootLView), lViewToView(rootLView),
The comment below applies to this line and all the other lines in the PR where we've got `lViewToView` and `viewToLView` conversions:

so the design issue I see here is that we are using "public" APIs internally which forces us have those conversions all over the place. IMO it would be easier if we've got a set of internal APIs that operate on `LView` and use those APIs internally in the ivy codebase. We can expose other APIs externally in the future but I don't see the point of using those external APIs internally. It is an additional function call that adds another layer of indirection and clutters the code with all the conversions.

2019-03-22 10:06 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +export function renderEmbeddedTemplate<T>(lViewToRender: LView, tView: TView, context: T) {
Would be great if code readability improvements are done in a separate PR (or at least in a separate commit).

2019-03-22 10:06 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +  if (tNode === null) {
Would be great if code readability improvements are done in a separate PR (or at least in a separate commit).

2019-03-22 10:07 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +export function componentHostSyntheticListener(
Would be great if code readability improvements are done in a separate PR (or at least in a separate commit).

2019-03-22 10:08 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +        // Legacy behavior expects some context.
Could you please clarify what you mean by "Legacy behaviour"?

2019-03-22 10:09 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +  let current = lView[CHILD_HEAD];
Would be great if code readability improvements are done in a separate PR (or at least in a separate commit).

2019-03-22 10:09 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +export function componentRefresh(adjustedElementIndex: number): void {
Would be great if code readability improvements are done in a separate PR (or at least in a separate commit).

2019-03-22 10:13 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions.ts
> +  return lViewToView(getLView());
Again, I'm totally puzzled as if to why we would like to use "public" API internally - the constant wrapping / unwrapping is just so much unnecessary work / noise in the code...

2019-03-22 10:17 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +export function renderChild(
I would suggest sticking with the existing name. `renderChild` suggest an action of rendering while what we are doing here is clearly an action of appending (inserting) nodes in the DOM tree.

2019-03-22 10:32 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +export function getBeforeNodeForContainedView(lContainer: LContainer, lViewInContainer: LView) {
I thought that we would this function to find the first node of a view so we can use to do "insert before" another view. As such `getLastRootElementFromView` from https://github.com/angular/angular/pull/29339/files#diff-88400e1d02ebaaffc34dc7ff8b2da482R232 wouldn't be needed, right?

2019-03-22 10:35 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +      renderChild(nodeOrContainer[NATIVE], currentView, insertBefore, renderParent);
Again, could we please go back to the previous name?

2019-03-22 10:38 UTC, pkozlowski-opensource commented on packages/core/src/render3/view_engine_compatibility.ts
> +        // Legacy behavior dictates that some sort of context should exist if none was provided.
Not sure what you are trying to say here. I would just remove this comment, sounds like a note that was useful during development

2019-03-22 10:40 UTC, pkozlowski-opensource commented on packages/core/src/render3/view_engine_compatibility.ts
> +        return new ViewRef(lViewToView(this.embeddedViewFactory(context)), context, -1);
`lViewToView` this is really, really not right... 

Also puzzled as to why we need to pass `context` to 2 functions here...

2019-03-22 10:42 UTC, pkozlowski-opensource commented on packages/core/src/render3/view_engine_compatibility.ts
> +      get length(): number { return viewContainerToLContainer(this._viewContainer)[VIEWS].length; }
This is another place where we see the effect of "public" API usage internally. This is not right and this is the biggest issue in this PR.

2019-03-22 10:45 UTC, pkozlowski-opensource commented on packages/core/src/render3/view_engine_compatibility.ts
> +  return new R3ViewContainerRef(lContainerToViewContainer(lContainer), hostTNode, hostView);
I'm sorry for being pain in a neck but we _really_ need to decide what it the API we are using internally / externally. Those type conversions all over the place really doesn't help wth m=mental model, following logic and code readability...

2019-03-22 10:47 UTC, pkozlowski-opensource commented on packages/core/src/render3/view_ref.ts
> +  public _view: View<T>;
Why we are changing this??? Again, we need to decide what is the API... I'm sorry but I see absolutely _no_ value in using `View` here...

2020-08-13 17:41 UTC, closed without merging