ci: add yarn cache for material-unit tests job
angular/angular pull request #29378
Opened 2019-03-18 18:24 UTC by devversion

* See individual commits.

2019-03-19 07:21 UTC, gkalpak requested changes

2019-03-19 07:21 UTC, gkalpak commented on scripts/ci/clone_angular_material_repo.sh
> +rm -Rf ${MATERIAL_REPO_TMP_DIR}
`-R`, ha? So, consistency means nothing to you 😭 😛

2019-03-19 07:21 UTC, gkalpak commented on .circleci/config.yml
> +          command: git ls-remote ${MATERIAL_REPO_URL} ${MATERIAL_REPO_IVY_BRANCH} | cut -f1 > material_repo_sha
_MATERIAL_REPO_IVY_BRANCH_ --> _MATERIAL_REPO_BRANCH_ (?)

2019-03-19 07:21 UTC, gkalpak commented on .circleci/config.yml
> +            # Needs to be hardcoded because environment variables are not interpolated here.
😞

2019-03-19 07:21 UTC, gkalpak commented on .circleci/config.yml
> +    parallelism: 2
So, how does Material know which tests to run in each instance?

2019-03-19 16:07 UTC, devversion commented on scripts/ci/clone_angular_material_repo.sh
> +rm -Rf ${MATERIAL_REPO_TMP_DIR}
It does 🤷‍♂️ 😁 See how I incorporated the `set` command for consistency! 

<sup>Will switch to lower-cased `R`. Though for the record: there is a lot of inconsistency with `cp -R/-r` as well</sup>

2019-03-19 16:08 UTC, devversion commented on .circleci/config.yml
> +    parallelism: 2
We handle it here: https://github.com/angular/material2/blob/master/test/karma.conf.js#L109-L113.

I will try to add that to the comment as well.

2019-03-19 19:06 UTC, gkalpak approved these changes

2019-03-19 19:06 UTC, gkalpak commented on .circleci/config.yml
> +    # https://github.com/angular/material2/blob/master/test/karma.conf.js#L109-L113
I prefer using specific commits, because the lines tend to get out-of-sync when linking to master.

2019-03-19 19:06 UTC, gkalpak commented on scripts/ci/run_angular_material_unit_tests.sh
> +# The angular/material2 CI sets TEST_PLATFORM to either local, saucelabs, or BrowserStack.
So, `saucelabs` is all lowercase, ha? :stuck_out_tongue:

2019-03-19 20:18 UTC, devversion commented on scripts/ci/run_angular_material_unit_tests.sh
> +# The angular/material2 CI sets TEST_PLATFORM to either local, saucelabs, or BrowserStack.
Updated.

2019-03-19 20:33 UTC, devversion commented on .circleci/config.yml
> +    # https://github.com/angular/material2/blob/master/test/karma.conf.js#L109-L113
Updated as well. Though not too sure if it helps much because it could imply that the code still exists, while it's no longer there

2019-03-19 21:00 UTC, alexeagle approved these changes

2019-03-19 21:15 UTC, devversion commented on .circleci/config.yml
> +      # sharding individual specs across the defined multiple instances.
Yep. That's something we need to explore in follow-ups. I think our master branch currently does not work with Ivy yet.

2019-03-19 21:16 UTC, closed without merging

2019-03-20 01:37 UTC, IgorMinar commented
excellent work. thank you @devversion!