docs(docs-infra): add project structure for library
angular/angular pull request #29376
Opened 2019-03-18 17:26 UTC by santoshyadav198613

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Added documentation for library project structure.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

We don't have project structure for libraries.
Issue Number: 29225

## What is the new behavior?
Added project structure for library.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-03-18 17:44 UTC, santoshyadav198613 commented
> I signed it!

2019-03-18 17:57 UTC, alan-agius4 requested changes
Thanks for taking this up.

Kindly find some comments above.

2019-03-18 17:57 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +Inside the `Project/` folder, the `my-lib` folder contains your library code. Angular components,services, module, directive and pipes can be added as a part of library.
_Angular components,services, module, directive and pipes can be added as a part of library. 
 -> Angular components, services, modules, directives and pipes can be added in a library._

2019-03-18 17:57 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `ng-package.json` | Configuration file used by ng-packagr for building your library. |
Please add link to ng-packagr github repo

2019-03-18 17:57 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `src/public_api.ts`    | All files which needs to exported are provided here. |
This is no longer valid, this has been changed to be `public-api.ts`

2019-03-18 17:57 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `tsconfig.lib.json`   | Inherits from the workspace-wide `tsconfig.json` file. |
I'd update these to have the same description as https://github.com/angular/angular/blob/master/aio/content/guide/file-structure.md#application-configuration-files

2019-03-18 17:57 UTC, alan-agius4 commented on aio/content/guide/libraries.md
> +A library must be imported and used in an app.You can refer the [application structure](guide/file-structure)
The change should be referenced in this file https://angular.io/guide/creating-libraries and not in this page.

I'd add a helpful alert under
````
A simple example might be a button that sends users to your company website, that would be included in all apps that your company builds.

<div class="alert is-helpful">
     <p>For more details on how a library project is structure you can refer the [library source folder](guide/file-structure#library-source-folder)</p>
</div>
```

2019-03-18 17:57 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| :-------------------------- |:------------------------------------------|
Kindly revert this change

2019-03-18 17:57 UTC, alan-agius4 commented
Kindly also squash all commits into a single one.

2019-03-18 18:55 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +| `ng-package.json` | Configuration file used by ng-packagr for building your library. |
don.

2019-03-18 18:55 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +| `src/public_api.ts`    | All files which needs to exported are provided here. |
done.

2019-03-18 18:56 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +| `tsconfig.lib.json`   | Inherits from the workspace-wide `tsconfig.json` file. |
Done.

2019-03-18 18:56 UTC, santoshyadav198613 commented on aio/content/guide/libraries.md
> +A library must be imported and used in an app.You can refer the [application structure](guide/file-structure)
Done.

2019-03-18 18:57 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +| :-------------------------- |:------------------------------------------|
Done, but somehow not visible here.

2019-03-18 18:59 UTC, santoshyadav198613 commented
> Kindly also squash all commits into a single one.

Also can you help me with this step as i tried but still can see all commit.

Also some error is coming in build step that there is some whitespace, can you help.

2019-03-18 19:37 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +Inside the `Project/` folder, the `my-lib` folder contains your library code. Angular components,services, module, directive and pipes can be added as a part of library.
Done

2019-03-19 15:22 UTC, alan-agius4 commented
@santoshyadav198613 to squash you can:

```
git reset --soft HEAD~9
git commit -m 'docs: add library structure  

Fixes #29225'
git push  -f
```

2019-03-19 15:23 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +Inside the `Project/` folder, the `my-lib` folder contains your library code. Angular components,services, module, directive and pipes can be added as a part of library.
still pending!

2019-03-19 15:24 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +Inside the `Project/` folder, the `my-lib` folder contains your library code. Angular components,services, module, directive and pipes can be added in a library.
_Inside the `Project/` folder, the `my-lib`_ -> _Inside the `projects/` folder, the `my-lib`_

2019-03-19 15:25 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `tsconfig.app.json`    | Library-specific [TypeScript](https://www.typescriptlang.org/) configuration, including TypeScript and Angular template compiler options. See [TypeScript Configuration](gui
_tsconfig.app.json_ -> tsconfig.lib.json

2019-03-19 15:25 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `tsconfig.spec.json`   | [TypeScript](https://www.typescriptlang.org/) configuration for the application tests. See [TypeScript Configuration](guide/typescript-configuration). |
application tests -> library tests

2019-03-19 15:28 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +## Library source folder
Actually in this section we are not explaining the source folder, but rather `Library project files`

Would you mind changing it through out, include the links?

2019-03-19 15:29 UTC, alan-agius4 commented on aio/content/guide/creating-libraries.md
> +     <p>For more details on how a library project is structure you can refer the [library source folder](guide/file-structure#library-source-folder)</p>
Sorry made a typo

_library project is structure -> library project is structured_

2019-03-19 15:29 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `/src/lib`      | this folder contains all code related to your library you can add component, directive, pipes, module or services as a part of library also this folder contains empty component,mo
Can you please go through this and replace `Application-specific` with `Library-specific`?

2019-03-19 15:51 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `/src/lib`      | this folder contains all code related to your library you can add component, directive, pipes, module or services as a part of library also this folder contains empty component,mo
| `/src/lib`      | Contains the files in which your library logic and data are defined. See details below.

| `package.json`         | Configures [npm package dependencies](guide/npm-packages) that are required for this library.|

2019-03-19 18:53 UTC, gkalpak reviewed
I was just passing by (haven't looked at the content) and just wanted to point out that the commit message should start with `docs: ...` (not `docs(docs-infra): ...`).
<sub>`docs(docs-infra)` means documentation for the infrastructure/tooling/app.</sub>

2019-03-19 18:56 UTC, alan-agius4 commented
Always a pleasure to have you by @gkalpak.

Yeah indeed and this was already pointed out: 
https://github.com/angular/angular/pull/29376#issuecomment-47442057

😊2

2019-03-20 09:27 UTC, gkalpak commented
Ha ha, I should have known better 😄
Leaving this in your capable hands 😎
Sorry for the noise 😇

2019-03-20 21:08 UTC, santoshyadav198613 commented
> @santoshyadav198613 to squash you can:
> 
> ```
> git reset --soft HEAD~9
> git commit -m 'docs: add library structure  
> 
> Fixes #29225'
> git push  -f
> ```
> Kindly note the commit message, it should be `docs: ` instead of `docs(docs-infra): `
I am getting below message when trying to commit this message
INVALID COMMIT MSG: "docs:add library structure Fixes #29225"
 => ERROR: The commit message does not match the format of '<type>(<scope>): <subject>' OR 'Revert: "type(<scope>): <subject>"'

2019-03-20 21:31 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +| `/src/lib`      | this folder contains all code related to your library you can add component, directive, pipes, module or services as a part of library also this folder contains empty component,mo
Completed all changes but still getting lint errors.

2019-03-21 08:07 UTC, alan-agius4 commented
Hi @santoshyadav198613, you still have multiple commits, and also it seems that from the build failure you need to rebase with master.

Also the `Fixes` in the commit message should be on a separate line like:
```
docs: add library structure

Fixes #29225
```

2019-03-21 08:27 UTC, santoshyadav198613 commented
> Hi @santoshyadav198613, you still have multiple commits, and also it seems that from the build failure you need to rebase with master.
> 
> Also the `Fixes` in the commit message should be on a separate line like:
> 
> ```
> docs: add library structure
> 
> Fixes #29225
> ```

Sorry @alan-agius4 ,
This is my first contribution, once i get regular will be able to resolve this quickly. Sorry you have to bother you like this. Making changes now.

2019-03-21 08:57 UTC, petebacondarwin commented
@santoshyadav198613 - don't worry. We all started somewhere. And git is a right brain-melter at times. Thank you for your contributions. It always takes a time to get used to our practices and expectations. Keep going!

2019-03-21 09:42 UTC, mary-poppins commented
You can preview 6f51804 at https://pr29376-6f51804.ngbuilds.io/.

2019-03-21 09:47 UTC, santoshyadav198613 commented
> @santoshyadav198613 - don't worry. We all started somewhere. And git is a right brain-melter at times. Thank you for your contributions. It always takes a time to get used to our practices and expectations. Keep going!

Thanks finally figured it out, also realized how helpful git bash is  :+1:

2019-03-21 09:58 UTC, santoshyadav198613 commented
> Hi @santoshyadav198613, you still have multiple commits, and also it seems that from the build failure you need to rebase with master.
> 
> Also the `Fixes` in the commit message should be on a separate line like:
> 
> ```
> docs: add library structure
> 
> Fixes #29225
> ```

Hey @alan-agius4 ,

Now all changes are done, there is only one problem the code added in creating library section is not coming as link.  Can you suggest the changes,

2019-03-21 10:13 UTC, petebacondarwin commented on WORKSPACE
> +    yarn_version = "1.12.1",
I think this change should be, at least, in a different commit, or maybe even a different PR.
It is a helpful change for you working in Windows. But it is not relevant to the changes you are making in this PR.

2019-03-21 10:14 UTC, santoshyadav198613 commented on WORKSPACE
> +    yarn_version = "1.12.1",
Yes i just did rebase from master, not related to my commit.

2019-03-21 10:15 UTC, petebacondarwin commented on aio/content/guide/creating-libraries.md
> +     <p>For more details on how a library project is structured you can refer the [library project files](guide/file-structure#library-project-files)</p>
This block of text will not be parsed as markdown, because it is inside an HTML tag.

If you want that to happen then you must put empty blank lines either side of the block of text.

But given that you are in HTML it is probably easier just to use `<a href="guide/file-structure#library-project-files">library project files</a>` here instead.

2019-03-21 10:15 UTC, santoshyadav198613 commented on aio/content/guide/creating-libraries.md
> +     <p>For more details on how a library project is structured you can refer the [library project files](guide/file-structure#library-project-files)</p>
Thanks let me make the changes

2019-03-21 10:27 UTC, mary-poppins commented
You can preview 66cb66b at https://pr29376-66cb66b.ngbuilds.io/.

2019-03-21 10:31 UTC, petebacondarwin reviewed
I don't think has rebased on master cleanly, because you have code changes here that should be already in master.  Did you do?

```bash
git fetch upstream master
git rebase upstream/master
```

2019-03-21 10:31 UTC, petebacondarwin commented on aio/content/guide/file-structure.md
> +| `tslint.json`          | Library-specific [TSLint](https://palantir.github.io/tslint/) configuration. |
Personally, if you are going to use markdown tables then I would encourage you to use whitespace to pad out the cells so that they look cleaner, more readable and more like a table. E.g.

```
| LIBRARY SOURCE FILES | PURPOSE                                                                                                                                                                                                   |
| :------------------- | :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `/src/lib`           | Contains the files in which your library logic are defined.                                                                                                                                               |
| `/src/test.ts`       | The main entry point for your unit tests, with some Library-specific configuration. You don't typically need to edit this file.                                                                           |
| `src/public-api.ts`  | All files which needs to exported are provided here.                                                                                                                                                      |
| `karma.conf.js`      | Library-specific [Karma](https://karma-runner.github.io/2.0/config/configuration-file.html) configuration.                                                                                                |
| `ng-package.json`    | Configuration file used by [ng-packagr](https://github.com/ng-packagr/ng-packagr) for building your library.                                                                                              |
| `package.json`       | Configures [npm package dependencies](guide/npm-packages) that are required for this library.                                                                                                             |
| `tsconfig.lib.json`  | Library-specific [TypeScript](https://www.typescriptlang.org/) configuration, including TypeScript and Angular template compiler options. See [TypeScript Configuration](guide/typescript-configuration). |
| `tsconfig.spec.json` | [TypeScript](https://www.typescriptlang.org/) configuration for the library tests. See [TypeScript Configuration](guide/typescript-configuration).                                                        |
| `tslint.json`        | Library-specific [TSLint](https://palantir.github.io/tslint/) configuration.                                                                                                                              |
```

2019-03-21 10:41 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +| `tslint.json`          | Library-specific [TSLint](https://palantir.github.io/tslint/) configuration. |
sure. will make the changes.

2019-03-21 10:44 UTC, mary-poppins commented
You can preview 4fc4887 at https://pr29376-4fc4887.ngbuilds.io/.

2019-03-21 11:02 UTC, santoshyadav198613 commented
> I don't think has rebased on master cleanly, because you have code changes here that should be already in master. Did you do?
> 
> ```shell
> git fetch upstream master
> git rebase upstream/master
> ```

Thanks man, you saved me from a blunder, i missed upstream while doing rebase.

2019-03-21 11:07 UTC, mary-poppins commented
You can preview b46700b at https://pr29376-b46700b.ngbuilds.io/.

2019-03-21 11:26 UTC, santoshyadav198613 commented
Hey @alan-agius4 , @petebacondarwin ,

Ready for review now, let me know if any changes are needed.

2019-03-21 13:03 UTC, petebacondarwin requested changes
Did you mean to change the file mode of the scripts?

e.g.  `aio/scripts/contributors/generate_org_chart.sh 100755 → 100644`

I think not. Can you revert those changes?

2019-03-21 13:37 UTC, santoshyadav198613 commented
> Did you mean to change the file mode of the scripts?
> 
> e.g. `aio/scripts/contributors/generate_org_chart.sh 100755 → 100644`
> 
> I think not. Can you revert those changes?

Done, there was no diff but somehow they came as a change, reverted back. thanks.

2019-03-21 13:42 UTC, mary-poppins commented
You can preview 0ca13b3 at https://pr29376-0ca13b3.ngbuilds.io/.

2019-03-21 21:09 UTC, jenniferfell commented
@jbogarthyde is the doc team owner for these files--and she recently made some changes to master for the next release--so I'd also like her to review. Thanks! (@jbogarthyde: Please validate accuracy, organization, and target as next or patch. Thanks!)

2019-03-21 22:47 UTC, jbogarthyde requested changes
Copy edit.

2019-03-21 22:47 UTC, jbogarthyde commented on aio/content/guide/creating-libraries.md
> +</div>
For details on how a library project is structured, see <a href="guide/file-structure#library-project-files">Library Project Files</a>.

2019-03-21 22:47 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +
When you generate a library using the CLI (with a command such as `ng generate library my-lib`), the generated files go into the `projects/` folder of the workspace. For more information about creating your own libraries, see [Creating Libraries](https://angular.io/guide/creating-libraries).

**replace line 167**
**move before line 166**

2019-03-21 22:47 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +Under the `Projects/` folder, the `my-lib` folder contains your library code. Angular components,services, module, directive and pipes can be added in a library.
`projects/` (lowercase)

lose second sentence - goes into table below (slightly modified)

2019-03-21 22:47 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +| `/src/lib`           | Contains the files in which your library logic are defined.
|  `/src/lib/`           |  Contains your library project's logic and data. Like an application project, a library project can contain components, services, modules, directives, and pipes.  |

2019-03-21 22:47 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +| `/src/test.ts`       | The main entry point for your unit tests, with some Library-specific configuration. You don't typically need to edit this file.
library-specific (lowercase)

2019-03-21 22:47 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
> +| `src/public-api.ts`  | All files which needs to exported are provided here.
Specifies all files that are exported from your library.

2019-03-22 07:50 UTC, santoshyadav198613 commented
Thanks for review guys will make the changes and update

2019-03-22 18:12 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +| `src/public-api.ts`  | All files which needs to exported are provided here.
Done.

2019-03-22 18:12 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +| `/src/test.ts`       | The main entry point for your unit tests, with some Library-specific configuration. You don't typically need to edit this file.
Done.

2019-03-22 18:12 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +| `/src/lib`           | Contains the files in which your library logic are defined.
Done.

2019-03-22 18:12 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +Under the `Projects/` folder, the `my-lib` folder contains your library code. Angular components,services, module, directive and pipes can be added in a library.
Done.

2019-03-22 18:12 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +
Done.

2019-03-22 18:13 UTC, santoshyadav198613 commented
Hi @jbogarthyde ,

Completed the changes, waiting for build than you can verify.

2019-03-22 18:17 UTC, mary-poppins commented
You can preview 2380975 at https://pr29376-2380975.ngbuilds.io/.

2019-03-22 18:30 UTC, santoshyadav198613 commented
Hi Everyone,
The test failed for lifecyle-hooke, should i fix it in this PR, or raise another issue, please let me know.

Regards,
Santosh

2019-03-22 18:33 UTC, alan-agius4 commented
That should be a flake m, I’ll the trigger the build.

2019-03-22 18:44 UTC, santoshyadav198613 commented
> Hi Everyone,
> The test failed for lifecyle-hooke, should i fix it in this PR, or raise another issue, please let me know.
> 
> Regards,
> Santosh

IT Worked thanks Alan.

2019-03-25 09:33 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `/src/lib`           |  Contains your library project's logic and data. Like an application project, a library project can contain components, services, modules, directives, and pipes.
Nit: for consistence can you kindly remove the leading slash?

2019-03-25 09:33 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `/src/test.ts`       | The main entry point for your unit tests, with some library-specific configuration. You don't typically need to edit this file.
Nit: for consistence can you kindly remove the leading slash?

2019-03-25 16:30 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +| `/src/test.ts`       | The main entry point for your unit tests, with some library-specific configuration. You don't typically need to edit this file.
You mean i should keep it as src/lib?

2019-03-25 16:37 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `/src/test.ts`       | The main entry point for your unit tests, with some library-specific configuration. You don't typically need to edit this file.
Yes please

2019-03-25 16:38 UTC, santoshyadav198613 commented on aio/content/guide/file-structure.md
> +| `/src/lib`           |  Contains your library project's logic and data. Like an application project, a library project can contain components, services, modules, directives, and pipes.
Done @alan-agius4 .

2019-03-25 16:42 UTC, mary-poppins commented
You can preview 562b305 at https://pr29376-562b305.ngbuilds.io/.

2019-03-25 16:58 UTC, jbogarthyde requested changes
Let's also change "mono-repo" to "monorepo" per @Splaktar suggestion. It occurs twice, lines 23, 25.

2019-03-25 17:09 UTC, santoshyadav198613 commented
> Let's also change "mono-repo" to "monorepo" per @Splaktar suggestion. It occurs twice, lines 23, 25.

Done.

2019-03-25 17:13 UTC, mary-poppins commented
You can preview f946a07 at https://pr29376-f946a07.ngbuilds.io/.

2019-03-26 07:21 UTC, alan-agius4 approved these changes
Thanks, LGTM

2019-03-26 15:46 UTC, jbogarthyde commented on aio/content/guide/file-structure.md
>  Libraries (unlike applications and their associated e2e projects) have their own `package.json` configuration files.
Libraries (unlike application projects) ...

(e2e tests will not be separate projects in v8)

2019-03-26 15:46 UTC, jbogarthyde approved these changes

2019-03-27 14:17 UTC, brandonroberts commented
@petebacondarwin will you review/approve?

2019-03-27 14:23 UTC, petebacondarwin approved these changes

2019-03-27 14:25 UTC, petebacondarwin commented
Not sure if `angular/fw-docs-packaging` approval is still really required?

2019-03-27 16:44 UTC, closed without merging