fix(ivy): Class selector directives execute properly on container ele…
angular/angular pull request #29383
Opened 2019-03-18 21:55 UTC by benlesh

…ments

- Adds two tests around directive execution on container elements (`<ng-container>`)
- Resolves an issue where ivy was unable to locate directives with class-based selectors if the class was on a container element.

The issue boiled down to the fact we weren't setting up a styling template for ng-container, because rendering-wise, we didn't need them. However, we *do* need them when it comes to locating directives that may exist on the container element.

2019-03-18 22:00 UTC, benlesh commented
[presubmit](http://test/OCL:239067697:BASE:239067752:1552946285420:5cd75353)

2019-03-18 22:09 UTC, petebacondarwin approved these changes

2019-03-18 22:44 UTC, AndrewKushnir approved these changes

2019-03-18 22:52 UTC, kara requested changes

2019-03-18 22:52 UTC, kara commented on packages/core/src/render3/instructions.ts
> +    if (tView.firstTemplatePass && !tNode.stylingTemplate) {
This block looks like a copy of lines 652-657 in `elementStart`. Can we share this code rather than duplicating it?

2019-03-19 02:04 UTC, benlesh commented on packages/core/src/render3/instructions.ts
> +    if (tView.firstTemplatePass && !tNode.stylingTemplate) {
I actually had that, but it seemed to add just as many lines of code as it saved, plus an additional function call in both sites. I'm sure that function call would be inlined eventually, but it seemed to be zero-cost to just keep it inline.

2019-03-19 02:14 UTC, kara commented on packages/core/src/render3/instructions.ts
> +    if (tView.firstTemplatePass && !tNode.stylingTemplate) {
Having this same code duplicated in a few places means that an update to this logic would have to happen in multiple places (which often doesn't happen, creating bugs).

Regarding size, it does actually save 5 lines.  Code right now is 7 lines at each location (14 lines total). With shared function, it's 9 lines. But my real concern is the duplication of logic.

2019-03-19 23:25 UTC, kara approved these changes

2019-03-19 23:25 UTC, kara commented on packages/core/src/render3/instructions.ts
> +      setNodeStylingTemplate(tNode, attrs, lastAttrIndex);
I think the check on line 663 is also shared, so we can move inside the function. But there's a readability trade-off, so up to you.

2019-03-20 00:12 UTC, benlesh commented
[new presubmit](http://test/OCL:239067697:BASE:239302247:1553040754342:fea2d61d)

2019-03-20 17:46 UTC, kara commented
@benlesh Needs update to golden files

2019-03-20 19:14 UTC, closed without merging