Stacks
angular/angular pull request #29429
Opened 2019-03-20 19:02 UTC by benlesh

- Adds a simple `Stack` implementation
- Uses said `Stack` in two spots where we were using a stack in `i18n`.
- Notice in [this commit](https://github.com/angular/angular/commit/3a5744771c9b42ebececede930369b5bbcd2b1cf) that it resolves a previously missed (minor) issue that we were leaving unused integers in a stack as we moved "down", but never actually "popped" the value.

NOTE: I typed the words "poop" and "pooped" about 20 times during the development of this PR.

2019-03-20 19:17 UTC, alfaproject commented on packages/core/test/render3/stack_spec.ts
> +onlyInIvy('Stacks are only used for Ivy').describe('Stack', () => {
Does it matter tho? It looks like it's generic enough that it can be a core util

2019-03-20 19:17 UTC, benlesh commented on packages/core/test/render3/stack_spec.ts
> +onlyInIvy('Stacks are only used for Ivy').describe('Stack', () => {
:man_shrugging: I'll leave that up to @angular/fw-core folks.

2019-03-20 19:19 UTC, benlesh commented
[presubmit](https://test.corp.google.com/ui#id=OCL:239449147:BASE:239449423:1553109516439:c076f7b6)

2019-03-20 19:20 UTC, alfaproject commented on packages/core/src/render3/util/stack.ts
> +  private _stack: (T|null)[] = [];
Suggestion from experience: I would leave `null` as a potential valid value and use `undefined` instead here. (a lot of JS APIs use `undefined` too like `Map.get`)

1. `null` is actually an object (`typeof null === 'object'`)
2. there might be the need of having `null` objects in the stack in the future

2019-03-20 19:53 UTC, ocombe approved these changes
ok for the i18n changes, but you should address the other comments before you merge it

2019-03-20 19:56 UTC, gkalpak commented on packages/core/src/render3/util/stack.ts
> +  private _stack: (T|null)[] = [];
It would also allow simplifying the implementation:

```ts
class Stack<T> {
  private items: T[] = [];

  push(item: T): void { this.items.push(item); }
  pop(): T | undefined { return this.items.pop(); }
  peek(): T | undefined { return this.items[this.items.length - 1]; }
}
```

2019-03-20 19:57 UTC, gkalpak commented on packages/core/src/render3/util/stack.ts
> +    _stack[currentPointer] = null;
OOC, why not just `.pop()` the item from the `_stack`?

2019-03-20 21:35 UTC, benlesh commented on packages/core/src/render3/util/stack.ts
> +    _stack[currentPointer] = null;
To avoid resizing the array over and over. The stack should grow to whatever size is needed and then just mostly stay there.

2019-03-20 21:37 UTC, benlesh commented on packages/core/src/render3/util/stack.ts
> +  private _stack: (T|null)[] = [];
@gkalpak As stated in my other comment, we're not using `Array.prototype.pop()` by design. The idea is to avoid the stack resizing that array too much once it's "warm".

Likewise, storing the current value for access via a property is an optimization to avoid needing to look the last item in the underlying array up.

2019-03-20 21:38 UTC, benlesh commented on packages/core/src/render3/util/stack.ts
> +  private _stack: (T|null)[] = [];
@alfaproject I don't disagree, if this were for general usage. We're using `null` throughout Angular Ivy, rather than `undefined` though. So this is more a continuance of that pattern.

2019-03-20 21:41 UTC, benlesh commented on packages/core/src/render3/util/stack.ts
> +  private _stack: (T|null)[] = [];
... in fact, I may want to add a  dev mode asssertion for when someone tries to pop from an empty stack :thinking:

2019-03-20 21:52 UTC, AndrewKushnir commented on packages/core/src/render3/util/stack.ts
> +  get current() { return this._current; }
The `peek()` seems like more conventional name (@gkalpak mentioned that in his comment too).

2019-03-20 21:57 UTC, AndrewKushnir commented on packages/core/src/render3/util/stack.ts
> +  private _stack: (T|null)[] = [];
@benlesh may be add an extra note into the code on why the stack size remains the same (for perf reasons)?
It might also be helpful if there is a link with extra info/tests on this (like some existing jsperf.com tests).

2019-03-20 22:06 UTC, gkalpak commented on packages/core/src/render3/util/stack.ts
> +    _stack[currentPointer] = null;
Why, though? I thought `.pop()` is cheap (just changing `.length`).
Is it slower than setting to `null`?
Does changing the length make the array slower?
<sub>(Just asking out of curiosity.)</sub>

2019-03-20 22:42 UTC, benlesh commented on packages/core/test/render3/stack_spec.ts
> +onlyInIvy('Stacks are only used for Ivy').describe('Stack', () => {
Actually, I'll just remove the `onlyInIvy`. It's just for tests, so it really doesn't matter. Although only Ivy is using it in this PR.

2019-03-21 19:33 UTC, mhevery requested changes

2019-03-21 19:33 UTC, mhevery commented on packages/core/src/render3/util/stack.ts
> +export class Stack<T> {
I am not a fan that we turned this into a Class. Rest of the Ivy could does not use classes and so we should not be using it here either.

2019-03-21 22:36 UTC, benlesh commented
I discussed this with @mhevery, and given that this PR was more of a proposal than anything, and I had no actual design document, I'm going to close this PR for now.

2019-03-21 22:36 UTC, closed without merging