refactor(upgrade): use Bazel packages to avoid symlinks in the source
angular/angular pull request #29466
Opened 2019-03-22 10:54 UTC by petebacondarwin

Previously we had to share code between upgrade/dynamic and upgrade/static
by symlinking the `src` folder, which allowed both packages to access
the upgrade/common files.

These symlinks are always problematic on Windows, where we had to run
a script to re-link them, and restore them.

This change uses Bazel packages to share the `upgrade/common` code,
which avoids the need for symlinking the `src` folder.

Also, the Windows specific scripts that fixup the symlinks have also
been removed as there is no more need for them.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-03-22 11:01 UTC, filipesilva requested changes
Can you also remove the newly added `scripts/windows/create-symlinks.cmd`, and remove its usage in `.codefresh/codefresh.yml`?

I was trialing a new Windows CI that uses needs that script so had to add an actual windows CMD for it.

2019-03-22 11:15 UTC, petebacondarwin commented
Will do!

2019-03-22 12:44 UTC, gkalpak approved these changes
Woohoo! :tada: 🎉 🎉

2019-03-22 12:44 UTC, gkalpak commented on packages/upgrade/common/BUILD.bazel
> +load("//tools:defaults.bzl", "ts_library")
`load` comes before `package` in other `BUILD.bazel` files. <sub>Just sayin'... 😛 </sub>

2019-03-22 12:44 UTC, gkalpak commented on packages/upgrade/common/BUILD.bazel
> +package(default_visibility = ["//visibility:public"])
Should we limit the visibility to the necessary packages only?

2019-03-22 12:44 UTC, gkalpak commented on tools/public_api_guard/BUILD.bazel
>      # exclude the following target because we have an explicit target for it bellow, see :core_api
The comment needs updating.

2019-03-22 12:44 UTC, gkalpak commented on tools/public_api_guard/BUILD.bazel
> +    data = ["//tools/public_api_guard:upgrade/upgrade.d.ts"] + [
OOC, why the `+` (instead of having everything in one list)?

2019-03-22 12:44 UTC, gkalpak commented on packages/upgrade/static/test/BUILD.bazel
> +package(default_visibility = ["//visibility:public"])
Why this?

2019-03-22 12:44 UTC, gkalpak commented on packages/upgrade/static/BUILD.bazel
> +            "src/*.ts",
It doesn't make a difference atm, but I would expect `src/**/*.ts`.

2019-03-22 12:44 UTC, gkalpak commented on packages/upgrade/dynamic/test/BUILD.bazel
> +package(default_visibility = ["//visibility:public"])
Is this needed? Other `test/BUILD.bazel` files don't seem to have it.

2019-03-22 12:44 UTC, gkalpak commented on packages/upgrade/common/test/helpers/BUILD.bazel
> +package(default_visibility = ["//visibility:public"])
Consider limiting visibility.

2019-03-22 12:44 UTC, gkalpak commented on packages/upgrade/common/test/BUILD.bazel
> +    srcs = glob(["**/*.ts"]),
Should `test/helpers/` be excluded or are directories with `BUILD.bazel` files excluded automatically?

2019-03-22 12:44 UTC, gkalpak commented on packages/upgrade/BUILD.bazel
> +            "dynamic/src/*.ts",
It doesn't make a difference, but I would expect `dynamic/src/**/*.ts`.

2019-03-22 12:44 UTC, gkalpak commented on packages/upgrade/BUILD.bazel
>          "@npm//zone.js",
Are `//packages/platform-browser` and `@npm//zone.js` needed?

2019-03-22 12:44 UTC, gkalpak commented on packages/upgrade/common/test/helpers/BUILD.bazel
> +        "//packages/core/testing",
Is this needed?

2019-03-22 13:50 UTC, filipesilva approved these changes

2019-03-22 14:44 UTC, petebacondarwin commented on tools/public_api_guard/BUILD.bazel
> +    data = ["//tools/public_api_guard:upgrade/upgrade.d.ts"] + [
I copied it from the core rule above. I think the idea is to split it into the "src" and the "dependencies" for readability.

2019-03-22 14:46 UTC, petebacondarwin commented on packages/upgrade/static/BUILD.bazel
> +            "src/*.ts",
My thought is that * is faster than ** when running the build; we can add it later easily enough; and it will be pretty obvious if it is needed.

2019-03-22 14:46 UTC, petebacondarwin commented on packages/upgrade/common/test/BUILD.bazel
> +    srcs = glob(["**/*.ts"]),
Anything with a BUILD.bazel file is deemed a Bazel package, and so it will be excluded from the glob.

2019-03-22 14:47 UTC, petebacondarwin commented on packages/upgrade/BUILD.bazel
> +            "dynamic/src/*.ts",
https://github.com/angular/angular/pull/29466#discussion_r268200339

2019-03-22 14:59 UTC, petebacondarwin commented on packages/upgrade/BUILD.bazel
>          "@npm//zone.js",
Zone is needed (e.g. https://github.com/angular/angular/blob/cfa6e8e008767387e366bf6a6baf6c1f2db9d122/packages/upgrade/src/dynamic/upgrade_adapter.ts#L507).

Platform-browser is not.

2019-03-22 15:01 UTC, petebacondarwin commented on packages/upgrade/common/test/helpers/BUILD.bazel
> +        "//packages/core/testing",
Without it TS complains that it doesn't know about `beforeAll` and `afterAll`.

2019-03-22 15:08 UTC, petebacondarwin commented on packages/upgrade/static/test/BUILD.bazel
> +package(default_visibility = ["//visibility:public"])
No idea :-) - removing

2019-03-22 15:10 UTC, petebacondarwin commented on packages/upgrade/common/BUILD.bazel
> +package(default_visibility = ["//visibility:public"])
Will do!

2019-03-22 15:10 UTC, petebacondarwin commented on packages/upgrade/dynamic/test/BUILD.bazel
> +package(default_visibility = ["//visibility:public"])
Removing

2019-03-22 15:10 UTC, petebacondarwin commented on packages/upgrade/common/test/helpers/BUILD.bazel
> +package(default_visibility = ["//visibility:public"])
Aye Aye

2019-03-22 16:41 UTC, gkalpak commented on packages/upgrade/static/BUILD.bazel
> +            "src/*.ts",
"Pretty obvious" :tm: 😛

2019-03-22 16:44 UTC, gkalpak commented on packages/upgrade/BUILD.bazel
>          "@npm//zone.js",
`NgZone` comes from `@angular/core`. And Zone.js is a [dependency of core][1]. Isn't that enough? <sub>(Just trying to understand bazel a little better.)</sub>

[1]: https://github.com/angular/angular/blob/cfa6e8e008767387e366bf6a6baf6c1f2db9d122/packages/core/BUILD.bazel#L21

2019-03-22 16:44 UTC, gkalpak commented on packages/upgrade/common/test/helpers/BUILD.bazel
> +        "//packages/core/testing",
🤷‍♂️

2019-03-22 20:56 UTC, alexeagle approved these changes

2019-03-25 16:33 UTC, mhevery commented
http://test/OCL:240155732:BASE:240155805:1553531503722:36978456

2019-03-25 17:45 UTC, mhevery commented
Breaks g3:

```

third_party/javascript/angular2/rc/packages/upgrade/static/public_api.ts:9:84 - error TS2307: Cannot find module '../common/src/angular1'.
	to fix, run:
	taze //third_party/javascript/angular2

9 export {getAngularJSGlobal, getAngularLib, setAngularJSGlobal, setAngularLib} from '../common/src/angular1';
                                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~
third_party/javascript/angular2/rc/packages/upgrade/static/public_api.ts:10:34 - error TS2307: Cannot find module '../common/src/downgrade_component'.
	to fix, run:
	taze //third_party/javascript/angular2

10 export {downgradeComponent} from '../common/src/downgrade_component';
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
third_party/javascript/angular2/rc/packages/upgrade/static/public_api.ts:11:35 - error TS2307: Cannot find module '../common/src/downgrade_injectable'.
	to fix, run:
	taze //third_party/javascript/angular2

11 export {downgradeInjectable} from '../common/src/downgrade_injectable';
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
third_party/javascript/angular2/rc/packages/upgrade/static/public_api.ts:12:23 - error TS2307: Cannot find module '../common/src/version'.
	to fix, run:
	taze //third_party/javascript/angular2

12 export {VERSION} from '../common/src/version';
                         ~~~~~~~~~~~~~~~~~~~~~~~
third_party/javascript/angular2/rc/packages/upgrade/static/public_api.ts:13:31 - error TS2307: Cannot find module './src/downgrade_module'.
	to fix, run:
	taze //third_party/javascript/angular2

13 export {downgradeModule} from './src/downgrade_module';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~
third_party/javascript/angular2/rc/packages/upgrade/static/public_api.ts:14:32 - error TS2307: Cannot find module './src/upgrade_component'.
	to fix, run:
	taze //third_party/javascript/angular2

14 export {UpgradeComponent} from './src/upgrade_component';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~
third_party/javascript/angular2/rc/packages/upgrade/static/public_api.ts:15:29 - error TS2307: Cannot find module './src/upgrade_module'.
	to fix, run:
	taze //third_party/javascript/angular2

15 export {UpgradeModule} from './src/upgrade_module';
                               ~~~~~~~~~~~~~~~~~~~~~~
```

2019-03-27 17:55 UTC, IgorMinar approved these changes
I discussed this with Pete and we agreed that it would be better to move `/dynamics` and `/common` under src to prevent these folders to be accidentally considered and used as entry points and public api.

otherwise this change looks great once these adjustments are made.

2019-03-27 19:02 UTC, petebacondarwin commented
Done. It'll need another presubmit.

2019-03-27 19:49 UTC, mhevery commented
http://test/OCL:240155732:BASE:240621012:1553716123697:cf97eb17

2019-03-28 11:04 UTC, gkalpak commented on tools/public_api_guard/BUILD.bazel
> +        "//packages/upgrade/common",
Shouldn't this be `//packages/upgrade/src/common` now?

2019-03-28 11:04 UTC, gkalpak commented on tools/public_api_guard/BUILD.bazel
> +        "//packages/upgrade/common",
Shouldn't this be `//packages/upgrade/src/common` now?

2019-03-28 11:48 UTC, petebacondarwin commented on tools/public_api_guard/BUILD.bazel
> +        "//packages/upgrade/common",
good spot!

2019-03-28 11:49 UTC, petebacondarwin commented on tools/public_api_guard/BUILD.bazel
> +        "//packages/upgrade/common",
again!

2019-04-01 18:17 UTC, jasonaden commented
[Presubmit](https://test.corp.google.com/ui#id=OCL:241021151:BASE:241062896:1553898449593:d027c68a)

2019-04-02 17:39 UTC, closed without merging

2019-04-02 18:47 UTC, gkalpak commented
\o/