docs(forms): properly convert number to string for formControlName input
angular/angular pull request #29473
Opened 2019-03-22 14:02 UTC by piotrtomiak

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently documentation https://angular.io/api/forms/FormArrayName for `formArrayName` encourages to pass `number` to a `string` input.

## What is the new behavior?

Documentation will encourage to use `i.toString()` to cast index to `string`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-04-05 07:19 UTC, piotrtomiak commented
Any chance to have this addressed in a near future? I would love to close my issue and let user know, which syntax he should be using.

2019-05-02 17:33 UTC, piotrtomiak commented
@jenniferfell @brandonroberts Could I get some traction on this?

2019-05-04 07:37 UTC, trotyl commented
I think interpolation here:

```html
<input formControlName="{{i}}" placeholder="City">
```

Might be better than `.toString()` call:

```html
<input [formControlName]="i.toString()" placeholder="City">
```

2019-05-06 13:29 UTC, brandonroberts commented
@piotrtomiak I agree with @trotyl, that interpolation for the string would be better here.

2019-05-06 13:30 UTC, brandonroberts requested changes

2019-05-06 13:30 UTC, brandonroberts commented on packages/examples/forms/ts/nestedFormArray/nested_form_array_example.ts
> +          <input [formControlName]="i.toString()" placeholder="City">
```suggestion
          <input [formControlName]="{{i}}" placeholder="City">
```

2019-05-06 13:31 UTC, trotyl commented on packages/examples/forms/ts/nestedFormArray/nested_form_array_example.ts
> +          <input [formControlName]="i.toString()" placeholder="City">
Also no more brackets.

2019-05-09 15:10 UTC, piotrtomiak commented on packages/examples/forms/ts/nestedFormArray/nested_form_array_example.ts
> +          <input [formControlName]="i.toString()" placeholder="City">
Fixed with force push.

2019-05-09 15:12 UTC, piotrtomiak commented
@trotyl Thanks for your suggestion! It indeed looks better.

2019-05-09 17:06 UTC, brandonroberts approved these changes

2019-05-09 17:07 UTC, brandonroberts commented
Caretaker note: The Codefresh failure is unrelated

2019-05-09 18:28 UTC, closed without merging

2019-05-10 11:32 UTC, piotrtomiak commented
@brandonroberts @alxhub Thank you for merging the change!