fix(ivy): DebugNode.query should query nodes in the logical tree
angular/angular pull request #29480
Opened 2019-03-22 17:25 UTC by marclaval

WIP draft, checking CI even if there is still some work needed

2019-03-22 18:24 UTC, pkozlowski-opensource commented
Wow, this was fast @marclaval ! The test failure on IE10 is actually my fault :-( 
I've forgotten that IE10 doesn't support node.remove() :-(
But this is what we've got tests for :-)

2019-03-25 15:16 UTC, marclaval commented
This PR is now ready for review, it fixes FW-1059, PTAL

2019-03-25 17:06 UTC, mhevery approved these changes

2019-03-25 17:08 UTC, mhevery commented
http://test/OCL:240164431:BASE:240164483:1553533710805:9acf7d84

2019-03-25 23:49 UTC, kara requested changes
Yay, thanks for doing this!  Code itself looks great, just some minor cleanup left for typos / missing comments.

2019-03-25 23:49 UTC, kara commented on packages/core/src/debug/debug_node.ts
> +            componentView[TVIEW].firstChild !, componentView, predicate, matches, elementsOnly);
Can we add a comment somewhere around here that explains that component content children will be added through their projection point? So that's why `tNode.child` shouldn't be checked here? (This confused me at first)

2019-03-25 23:49 UTC, kara commented on packages/core/src/debug/debug_node.ts
> +    }
Seems like this for loop is really similar to the for loop in lines 435 - 437. Can we break it out into a shared method?

2019-03-25 23:49 UTC, kara commented on packages/core/src/debug/debug_node.ts
> +    // The node projected at this location need to be all processed.
```suggestion
    // The nodes projected at this location all need to be processed.
```

2019-03-25 23:49 UTC, kara commented on packages/core/test/linker/ng_module_integration_spec.ts
> +import {modifiedInIvy, obsoleteInIvy, onlyInIvy} from '@angular/private/testing';
Since we are cleaning up all of these `fixmeIvy` instances, can we also remove the `fixmeIvy` method itself from `ivy_test_selectors`?

2019-03-26 14:09 UTC, marclaval commented
PR updated to take the comments into account.
CI is red because of a Saucelabs issue which is fixed in #29518

2019-03-26 17:52 UTC, kara approved these changes
LGTM

2019-03-26 17:54 UTC, kara commented
[presubmit](http://test/OCL:240381873:BASE:240381903:1553622811635:bca6068e)

2019-03-26 18:54 UTC, kara commented
merge assistance: red because of the SL issue on master

2019-03-26 19:50 UTC, closed without merging