docs(guide/schematics-for-libraries): address some comments in #28343 and typo fixes
angular/angular pull request #29505
Opened 2019-03-25 14:05 UTC by Chan4077

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes _(P.S. I wouldn't really consider this as a "documentation content change")_
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Addresses concerns that I had in the PR that introduced the Schematics docs (#28343) where the `--parents` flag of `cp` was not supported on certain platforms such as macOS.

Issue Number: N/A

## What is the new behavior?

The scripts now use the `find` and `rsync` commands respectively which should not break any existing copying functionality.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This PR also has minor documentation fixes in the Schematics for Libraries document such as the removal of extra whitespaces and typo fixes.

P.S. I can try to address the other reviews and comments made in the PR that I linked above such as mentioning schematics utilities in the document that the community have made.

2019-03-26 10:01 UTC, Splaktar commented on aio/content/examples/schematics-for-libraries/projects/my-lib/package.json
> +    "copy:files": "find schematics/*/files/** -exec rsync -R {} ../../dist/my-lib/ \\;",
What are these double backslashes for? `\\;`

2019-03-26 12:42 UTC, Chan4077 commented on aio/content/examples/schematics-for-libraries/projects/my-lib/package.json
> +    "copy:files": "find schematics/*/files/** -exec rsync -R {} ../../dist/my-lib/ \\;",
It's used to escape the second backlash.

2019-03-26 12:46 UTC, Chan4077 commented on aio/content/examples/schematics-for-libraries/projects/my-lib/package.json
> +    "copy:schemas": "find schematics -type f -name 'schema.json' -exec rsync -R {} ../../dist/my-lib/ \\;",
I haven't had the time to test on Linux or Windows 10. This command works on macOS Mojave (my local machine) though.

I haven't currently thought of any other idea to not use `rsync` ATM.

2019-04-23 07:45 UTC, gkalpak commented on aio/content/examples/schematics-for-libraries/projects/my-lib/package.json
> +    "copy:schemas": "find schematics -type f -name 'schema.json' -exec rsync -R {} ../../dist/my-lib/ \\;",
This definitely does not work on Windows :grin:
I don't think it is easy to find a command that works on all OSes 😞

One option might be simplifying the commands and using [shx][1].

[1]: https://www.npmjs.com/package/shx

2019-04-23 07:54 UTC, Chan4077 commented on aio/content/examples/schematics-for-libraries/projects/my-lib/package.json
> +    "copy:schemas": "find schematics -type f -name 'schema.json' -exec rsync -R {} ../../dist/my-lib/ \\;",
@gkalpak Thanks for the info about shx! I've never heard of it until now :smile:

2019-04-23 10:01 UTC, gkalpak commented on aio/content/examples/schematics-for-libraries/projects/my-lib/package.json
> +    "copy:schemas": "find schematics -type f -name 'schema.json' -exec rsync -R {} ../../dist/my-lib/ \\;",
Yeah, [shelljs][1] (and [shx][2]) is a life-saver when it comes to cross-OS npm scripts 😉

[1]: https://www.npmjs.com/package/shelljs
[2]: https://www.npmjs.com/package/shx

2019-05-21 22:29 UTC, Splaktar commented
It doesn't look like the concerns in https://github.com/angular/angular/pull/29505#discussion_r277552455 have been addressed as this PR still uses `find` and `rsync` and likely won't work on Windows without the Linux subsystem installed.

2019-05-29 04:22 UTC, EdricChan03 commented on aio/content/examples/schematics-for-libraries/projects/my-lib/package.json
> +    "copy:schemas": "find schematics -type f -name 'schema.json' -exec rsync -R {} ../../dist/my-lib/ \\;",
@gkalpak I've just tried appending `shx` to the `cp` command and found out that it also does not support the `--parents` flag.

2019-05-29 14:35 UTC, gkalpak commented on aio/content/examples/schematics-for-libraries/projects/my-lib/package.json
> +    "copy:schemas": "find schematics -type f -name 'schema.json' -exec rsync -R {} ../../dist/my-lib/ \\;",
Yeah, that's why I mentioned we also nee to simplify the commands :grin:

2019-09-27 16:02 UTC, leonardochaia commented
Just in case it helps someone, I've decided to setup the scripts on the root `package.json` and use `cpy-cli` and `rimraf`:

```json
{
  "scripts":{
     "prebuild:schematics": "rimraf ./dist/my-lib/schematics/",
     "build:schematics": "tsc -p ./projects/my-lib/tsconfig.schematics.json",
     "postbuild:schematics": "cpy ./schematics !**/*.ts ../../dist/my-lib/ --parents --cwd=./projects/my-lib/"
  }
}
```

2020-06-25 21:43 UTC, IgorMinar requested changes
the proposed change is also not cross-platform compatible. can you please think of a solution that does work cross windows/mac/linux platform? thanks

btw I extracted the typos commit into a separate PR #37753 and removed it from this PR. That way, we can fix the typos while the rest of your improvements are still being iterated on.

2020-06-26 00:50 UTC, EdricChan03 commented
> the proposed change is also not cross-platform compatible. can you please think of a solution that does work cross windows/mac/linux platform? thanks

Wow has it been a while since I've updated this PR.

Unfortunately, I have neither been able to find any alternative solutions to the script nor have the time to do so.

2021-04-15 18:06 UTC, gkalpak commented
Closing this PR, since it doesn't seem to solve the cross-platform issue.
(BTW, #30966 offers an alternative approach to solve the same issue.)

2021-04-15 18:06 UTC, closed without merging