build: make VSCode settings opt-in
angular/angular pull request #29504
Opened 2019-03-25 10:53 UTC by filipesilva

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The current vscode settings are mandatory for all users. Some of these settings can break or significantly alter current editor usage.

## What is the new behavior?
Settings are opt-in and include instructions on how they should be used and altered.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-03-25 11:20 UTC, petebacondarwin commented on .gitignore
> +.vscode
Actually I think the `.vscode/extensions.json` file is a good one to keep in the repo. So we should not ignore that one.

2019-03-25 11:21 UTC, petebacondarwin commented on .vscode-configuration/README.md
> +This isn't an automatic process so you will need to repat it when settings are updated.
repat => repeat

2019-03-25 11:22 UTC, petebacondarwin requested changes
Personally I think this PR should be restricted to the `.vscode/settings.json` rather than the whole folder. I like to have my own `launch.json`, which would get overridden by the current process; and also I think that the `extensions.json` is a valid file to keep in the repo.

2019-03-25 11:33 UTC, filipesilva commented on .gitignore
> +.vscode
Yes now that you bring up I totally agree. `extensions.json` is meant to signal extensions the repository team considers useful and is already an opt-in procedure. Will change.

2019-03-25 11:37 UTC, filipesilva commented on .vscode-configuration/README.md
> +This isn't an automatic process so you will need to repat it when settings are updated.
Done

2019-03-25 17:28 UTC, gkalpak approved these changes
Once this is merged, it should to be announced on Slack as it affects the whole team (in a small way).

2019-03-25 17:28 UTC, gkalpak commented on .vscode/README.md
> +## Usage
Might be worth adding a mention about where/how to find the recommended extensions for the workspace (e.g. `Ctrl/Cmd+Shift+P` and type `Show recommended extensions`).

2019-03-28 12:08 UTC, petebacondarwin approved these changes

2019-03-28 15:21 UTC, gkalpak commented
(Rebased on master to get CI green.)

2019-03-28 16:18 UTC, mhevery approved these changes

2019-03-28 17:57 UTC, filipesilva commented on .vscode/README.md
> +## Usage
Added.

2019-03-28 19:04 UTC, alexeagle approved these changes

2019-03-28 19:07 UTC, pkozlowski-opensource approved these changes

2019-03-29 10:00 UTC, petebacondarwin commented on .vscode/recommended-settings.json
>      "**/.git/subtree-cache/**": true,
Can we add this setting to:

```
  "typescript.tsdk": "node_modules/typescript/lib",
```

This tells VS code to use the workspace TS compiler rather than VS Code's built-in one.

2019-03-29 10:17 UTC, filipesilva commented on .vscode/recommended-settings.json
>      "**/.git/subtree-cache/**": true,
I'd prefer that to be done in a separate PR. It's not something I can test well right now and a bit out of scope anyway.

2019-03-29 17:28 UTC, closed without merging

2019-03-29 17:32 UTC, gkalpak commented
:tada: