refactor(ivy): move property instruction to a separate location
angular/angular pull request #29557
Opened 2019-03-27 23:09 UTC by benlesh

Simply moves the `property` instruction to its own location, to help with maintenance while we work on migrating to new update instructions.

- Also moves a shared function to the existing `shared.ts` file.

2019-03-27 23:10 UTC, benlesh commented on packages/core/src/render3/instructions/instructions.ts
> +export function savePropertyDebugData(
Shoot.. these need to move to `shared` also... VS Code got me :)

2019-03-28 14:01 UTC, kara requested changes

2019-03-28 14:01 UTC, kara commented on packages/core/src/render3/instructions/instructions.ts
> +  */
Nit: Can we also change the commit message? It sounds like we are only moving the property instruction, but I think the more important part of the PR is that we are adding this select functionality and related tests.

2019-03-28 17:43 UTC, benlesh commented
blocked on #29513

2019-03-28 23:19 UTC, benlesh commented
[presubmit](http://test/OCL:240876341:BASE:240876376:1553815160503:8008bdf9)

2019-03-29 16:46 UTC, benlesh commented
Presubmit failed on circular reference last time. I suspect because VS Code auto-added `import { NO_CHANGE } from '..`;` instead of `from '../tokens'`.  Resolved that and running again.

2019-03-29 22:59 UTC, mhevery approved these changes
LGTM, but please address my comments.

2019-03-29 22:59 UTC, mhevery commented on packages/core/src/render3/instructions/property.ts
> +import {elementPropertyInternal} from './shared';
Why do we have `elementPropertyInternal` in `shared` and not in this file? 

One concern is that WebPack does not know how to create chunk boundaries across files. So if one symbol in `shared` is needed then the whole file is included in the root chunk, even if the remainder of symbols are not needed until some later lazy loading point. For this reason I think we should not have `shared` which would be dumping ground for things.

2019-03-29 22:59 UTC, mhevery commented on packages/core/src/render3/instructions/property.ts
> +export type TsickleIssue1009 = any;
This will be needed in other places as well, (not specific to `property.ts` hence this should be in `shared`)

2019-03-29 22:59 UTC, mhevery commented on packages/core/src/render3/instructions/property.ts
> + * If the property name also exists as an input property on one of the element's directives,
This is public API and should be written from the Angular's developer point of view on how this instruction should be used and what it is for. This comment seems to be talking about some implementation detail.

2019-03-29 22:59 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +const ATTR_TO_PROP: {[name: string]: string} = {
I think just about everything should go to `property.ts` per reasons discussed.

2019-03-29 22:59 UTC, mhevery commented on packages/core/src/render3/instructions/property.ts
> +export function property<T>(
rename `property` to `®property`?

2019-03-29 23:02 UTC, benlesh commented on packages/core/src/render3/instructions/property.ts
> +import {elementPropertyInternal} from './shared';
There are two reasons:

1. It's used in both `instructions.ts` and `property.ts`
2. `all.ts` exports `*` from both `instructions` and `property`. Moving it here would cause it to be exported publicly. We could just explicitly export, but the prior art was to export `*`.

2019-03-29 23:16 UTC, benlesh commented on packages/core/src/render3/instructions/property.ts
> +import {elementPropertyInternal} from './shared';
Actually, I think I'm going to change this to put everything (including existing `elementProperty` instructions) in `property.ts`, and then my followup PR will put the `propertyInterpolate` instructions in `property.ts` as well.

2019-04-02 16:29 UTC, benlesh commented on packages/core/src/render3/instructions/property.ts
> +import {elementPropertyInternal} from './shared';
Okay, after our conversation yesterday, I've opened a different PR that moves all of the instructions here: #29646

2019-04-02 16:30 UTC, benlesh commented on packages/core/src/render3/instructions/shared.ts
> +const ATTR_TO_PROP: {[name: string]: string} = {
Yeah, please see the other PR here: #29646  (per our discussion yesterday)

2019-04-02 16:31 UTC, benlesh commented on packages/core/src/render3/instructions/property.ts
> +export function property<T>(
I've started one PR to move the instructions here: #29646

... I'd like to rename everything in a followup PR to that.

2019-04-02 16:31 UTC, benlesh commented
Closing this in favor of #29646

2019-04-02 16:31 UTC, closed without merging