perf(ivy): avoid storing raw selectors in projectionDef
angular/angular pull request #29578
Opened 2019-03-28 22:28 UTC by crisbeto

Currently in Ivy we pass both the raw and parsed selectors to the `projectionDef` instruction, because the parsed selectors are used to match most nodes, whereas the raw ones are used to match against nodes with the `ngProjectAs` attribute. The raw selectors add a fair bit of code that won't be used in most cases, because `ngProjectAs` is somewhat rare.

These changes rework the compiler not to output the raw selectors in the `projectionDef`, but to parse the selector in `ngProjectAs` and to store it on the `TAttributes`. The logic for matching has also been changed so that it matches the pre-parsed `ngProjectAs` selector against the list of projection selectors.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-03-29 09:59 UTC, petebacondarwin reviewed
I wonder if we should make `ngProjectAs` attributes special, in the sense that we create a new `AttributeMarker.ngProjectAs` flag. This would mean that our processing of "normal" attributes is not affected and fast as possible, which is the most common case.

2019-03-29 10:15 UTC, crisbeto commented
Introducing a flag would definitely make it more consistent, but I'm not sure whether it would help with processing since the `TAttributes` is still a `(string | number | CssSelector)[]` when we're iterating over it.

2019-03-29 15:21 UTC, petebacondarwin commented on packages/core/src/render3/instructions/instructions.ts
> +    if (typeof attrName !== 'string') break;
Do we guarantee that the `ngProjectAs` attribute will appear after all other attributes?

2019-03-29 19:45 UTC, crisbeto commented on packages/core/src/render3/instructions/instructions.ts
> +    if (typeof attrName !== 'string') break;
Good point, we also want to break here if the `attrName === 'ngProjectAs'`.

2019-04-01 19:39 UTC, mhevery requested changes
I am concerned about the changes we have made to the `generateInitialInputs` Could we discuss?

2019-04-01 19:39 UTC, mhevery commented on packages/core/src/render3/instructions/instructions.ts
> +    if (typeof attrName !== 'string') break;
I don't think we should have string comparison here as that is expensive. 

I do believe that `typeof attrName === 'number'` is faster than `typeof attrName !== 'string'` Why do we have to change it? Is this run on every instance or only for the initial creation? It looks like it is run for each instance, which means this change would have negative impact.

2019-04-01 19:47 UTC, crisbeto commented on packages/core/src/render3/instructions/instructions.ts
> +    if (typeof attrName !== 'string') break;
The function is called `generateInitialInputs` so I think it's only being run on init.

WRT performance: we need to change it because the `attrName` is now a `string | number | CssSelector`. This was one of the concerns I was raising earlier. These are the two alternatives I have in mind:

Option one: Add another flag for `ngProjectAs` and use that to break the loop. That will allow us to change back the check to `typeof attrName === 'number'` and would be slightly less generated code.
Option two: Change the check to `attrName === 'ngProjectAs' || typeof attrName === 'number'`. I'm not quite sure how the performance would compare against option one.

2019-04-01 20:49 UTC, gkalpak commented on packages/core/src/render3/instructions/instructions.ts
> +    if (typeof attrName !== 'string') break;
OOC, why is `typeof attrName === 'number'` faster than `typeof attrName !== 'string'`? Is it because of the extra negation that needs to happen for `!==`? Does this really have a noticeable impact?

2019-04-04 20:00 UTC, crisbeto commented
I've reworked it to use a marker for `ngProjectAs`.

2019-04-04 20:20 UTC, petebacondarwin approved these changes
It would be good to see some tests that exercise the code with `projectAs` using classes and `not` too. Currently there only appears to be attribute based selectors. But I might have missed them.

2019-04-08 20:25 UTC, kara requested changes

2019-04-08 20:45 UTC, crisbeto commented on packages/compiler-cli/test/compliance/r3_compiler_compliance_spec.ts
> +          const $_c1$ = ["[title]"];
The `c0` (parsed selectors) are still being passed into the `projectionDef` and the `c1` (raw selectors) are used in the `ComponentDef.ngContentSelectors`.

2019-04-08 21:01 UTC, crisbeto commented
Rebased and addressed the feedback @kara.

2019-04-08 21:07 UTC, kara commented on packages/compiler-cli/test/compliance/r3_compiler_compliance_spec.ts
> +          const $_c1$ = ["[title]"];
Seems like a comment might be good above the definition for this.

2019-04-08 21:08 UTC, kara approved these changes
LGTM

2019-04-08 21:17 UTC, crisbeto commented on packages/compiler-cli/test/compliance/r3_compiler_compliance_spec.ts
> +          const $_c1$ = ["[title]"];
Done.

2019-04-09 18:41 UTC, mhevery approved these changes

2019-04-09 18:44 UTC, mhevery commented
http://test/OCL:242709289:BASE:242709334:1554835459780:c2dfe02f

2019-04-09 22:16 UTC, kara commented
merge assistance: global approval

2019-04-10 19:14 UTC, IgorMinar commented
@crisbeto this PR now has a big conflict. can you please resolve it? thank you!

2019-04-10 21:13 UTC, crisbeto commented
Conflicts have been resolved.

2019-04-11 15:09 UTC, IgorMinar commented
@crisbeto thank you! ❤️

2019-04-11 15:10 UTC, closed without merging