fix(ivy): ensure parent/sub-class components evaluate styling correctly
angular/angular pull request #29602
Opened 2019-03-29 22:55 UTC by matsko

The new styling algorithm in angular is designed to evaluate host
bindings stylinh priority in order of directive evaluation order. This,
however, does not work with respect to parent/sub-class directives
because sub-class host bindings are run after the parent host bindings
but still have priority. This patch ensures that the host styling bindings
for parent and sub-class components/directives are executed with respect
to the styling algorithm prioritization.

Jira Issue: FW-1132

2019-04-03 04:22 UTC, mhevery requested changes

2019-04-03 04:22 UTC, mhevery commented on packages/core/src/render3/state.ts
> +let activeHostDirectiveIndex: number|null = null;
Do we need both`activeHostDirectiveIndex` and `activeHostDirectiveInheritanceDepth` they seem redundant.

Also I don't think `activeHostDirectiveIndex` is the right name. You are saying `index` which means it is index into something but than you just increment it. So it is more like `uniqueId` than on `index`?

2019-04-03 04:22 UTC, mhevery commented on packages/core/src/render3/state.ts
> + * Say for example we have an element that has two directives on it:
```suggestion
 * For example we have an element that has two directives on it:
```
`Say` is unnecessary. Also all comments below.

2019-04-03 04:22 UTC, mhevery commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +          // running in the parent or not). The increment/decement function calls below
```suggestion
          // running in the parent or not). The increment/decrement function calls below
```

2019-04-03 04:22 UTC, mhevery commented on packages/core/test/render3/styling/class_and_style_bindings_spec.ts
> +           updateContextWithBindings(ctx, 0, ['foo'], ['width']);
These tests are very fragile (we have to update theme every time we change something). Please consider using `StylingContext.debug` as a way to assert correct state.

2019-04-03 04:22 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +          // parent and sub-class code, the hostDirectiveIndex value needs to be
This comment makes me think it should be `hostDirectiveId`?

2019-04-03 04:22 UTC, mhevery commented on packages/core/src/render3/interfaces/styling.ts
> +   * A queue of all hostStyling* instructions.
```suggestion
   * A queue of all hostStyling instructions.
```

2019-04-03 04:22 UTC, mhevery commented on packages/core/src/render3/interfaces/styling.ts
> +   * a queue is contructed and then flushed once the styles are applied to
```suggestion
   * a queue is constructed and then flushed once the styles are applied to
```

2019-04-03 04:22 UTC, mhevery commented on packages/core/src/render3/interfaces/styling.ts
> +   * A queue of all hostStyling* instructions.
Probably add a comment that the queue is only used for the host?

2019-04-03 04:22 UTC, mhevery commented on packages/core/src/render3/styling/host_instructions_queue.ts
> + * at a later point (instead of immediately such as how templater-level styling
```suggestion
 * at a later point (instead of immediately such as how template-level styling
```

2019-04-03 04:22 UTC, mhevery commented on packages/core/src/render3/styling/host_instructions_queue.ts
> + * directives, are evluated at different points (depending on priority) and will therefore
```suggestion
 * directives, are evaluated at different points (depending on priority) and will therefore
```

2019-04-03 04:22 UTC, mhevery commented on packages/core/src/render3/styling/host_instructions_queue.ts
> + * Iterates throught the host instructions queue (if present within the provided
```suggestion
 * Iterates through the host instructions queue (if present within the provided
```

2019-04-04 19:25 UTC, kara requested changes

2019-04-04 19:25 UTC, kara commented on packages/core/src/render3/state.ts
> +let activeDirectiveElementIndex = -1;
It's not really clear to me why we need this global when we can pass the index directly. Can you clarify?

2019-04-04 19:25 UTC, kara commented on packages/core/src/render3/state.ts
> + * Sets the active directive host element.
```suggestion
 * Sets the active directive host element and the active directive ID.
```

2019-04-04 19:30 UTC, kara commented on packages/core/src/render3/state.ts
> +export function incrementActiveDirectiveSuperClassDepth() {
Nit: It seems like we could combine this with the decrement function if we add a "delta" arg (1 or -1). Since these are always used together, it's more generated code to keep them separate.

```suggestion
export function updateActiveDirectiveSuperClassDepth(delta: number) {
```

2019-04-04 20:56 UTC, mhevery requested changes

2019-04-04 20:56 UTC, mhevery commented on packages/core/src/render3/state.ts
> +let activeDirectiveElementIndex = -1;
Use `_selectIndex` field instead?

2019-04-04 20:56 UTC, mhevery commented on packages/core/src/render3/state.ts
> +const MIN_DIRECTIVE_UNIQUE_ID = 1;
drop `unique` from the name.

2019-04-04 20:56 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +import {enterView, getBindingsEnabled, getCheckNoChangesMode, getIsParent, getLView, getNamespace, getPreviousOrParentTNode, incrementActiveDirectiveUniqueId as generateAndStoreNextDirectiveUniqueId,
drop rename

2019-04-04 20:56 UTC, mhevery commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +            incrementActiveDirectiveSuperClassDepth();
please add `try-finally`

2019-04-05 06:14 UTC, matsko commented
https://tap.corp.google.com/ui#id=OCL:242073253:BASE:242074212:1554443892458:a644f778

2019-04-05 09:01 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +      .it('should render styling for parent and sub-classed components in order', () => {
If I'm not mistaken this test has the same name as one introduced above: https://github.com/angular/angular/pull/29602/files#diff-0483f62e84f992bd169dee41626776e1R158

I don't know what Jasmine does with tests with duplicated names but I was under the impression that this is some kind of a unique identifier. In any case we shouldn't have tests with duplicate names - could you please change?

2019-04-05 09:03 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +  onlyInIvy('[style] and [class] bindings are a new feature')
Could you please change this title to be more accurate? It is not like [style] and [class] bindings are really new feature - what is a new feature is that _values_ of those bindings are _combined_ and this is a new feature. We should somehow reflect it in the name of `onlyInIvy` and / or add a comment.

2019-04-05 09:06 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +      @HostBinding('style.width') public width1 = '100px';
not: you can drop `public` here and below (it is `public` by default).

2019-04-05 09:10 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +  it('should render styling for parent and sub-classed components in order', () => {
Could we change the title of this test to indicate what the "proper" order is? If I'm not mistaken you are trying to say that sub-classing overrides host bindings?

2019-04-05 09:11 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +      .it('should render styling for parent and sub-classed directives in order', () => {
Please change the name to indicate what the proper order is

2019-04-05 09:13 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +        expect(log).toEqual([
It is not clear to me why having log here is beneficial for this test?  We already have asserts to check that proper stylings are applied. For me those logs asserts might have been useful during implementation phase but I find those "noisy" for an acceptance test.

2019-04-05 09:14 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +        class OrphanDir {
nit: how about "sibling" instead of "orphan"?

2019-04-05 09:20 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +        class OrphanDir {
nit: the way I'm reading it is that this test is asserting 2 things:
* that style host bindings are evaluated properly with directive inheritance;
* that multiple directives on the same element override styling host bindings.

I would much rather prefer that we've got several separate tests here:
* just inheritance for directives (as you had for components)
* 2 directives on the same element;
* a component and a directive (to show who overrides what);
* 2 or more directives in a different order (to see how order of directive in a template influences styling instructions override);

Generally speaking I much prefer small, focused tests as those are easier to understand and debug if needed.

2019-04-05 09:21 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +      .it('should render styling for parent and sub-classed components in order', () => {
Also the name of this test should indicate what is the expected order of override.

2019-04-05 09:21 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +          @HostBinding('style.width') public width1 = '100px';
nit: drop `public`

2019-04-05 09:25 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +      @HostBinding('class.other-class') public bool = true;
nit: drop public (actually, everywhere in this test)

2019-04-05 09:26 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +  it('should allow host classes to be placed on a ng-container', () => {
So the title of this test indicates that it is about styling instructions on `<ng-container>` but the setup of this test is much more complex and involves content projection? Is the content projection essential to reproduce the issue being fixed here? If yes, we should rename this test. If not, we should simplify it.

2019-04-05 09:28 UTC, pkozlowski-opensource commented on packages/core/test/render3/styling/class_and_style_bindings_spec.ts
> +           updateContextWithBindings(ctx, 0, ['foo'], ['width']);
I would like to second this sentiment... This test file is pretty intimidating for un-initiated :-(

2019-04-05 10:19 UTC, pkozlowski-opensource requested changes
@matsko I've left some comments (mostly about tests) that I would love to see addressed before this PR gets in (mostly nits so I hope it won't be too much trouble...). Thnx!

2019-04-05 15:49 UTC, matsko commented on packages/core/test/acceptance/styling_spec.ts
> +      .it('should render styling for parent and sub-classed components in order', () => {
`should render styling for parent and sub-classed directives in order` and `should render styling for parent and sub-classed components in order`

`directives` and `components` differ in the text so I think we're ok.

2019-04-05 15:53 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +      .it('should render styling for parent and sub-classed components in order', () => {
I'm talking about duplication of `should render styling for parent and sub-classed components in order` - search through your diff and see that there are 2 tests with this name.

2019-04-05 15:54 UTC, matsko commented on packages/core/test/acceptance/styling_spec.ts
> +  it('should render styling for parent and sub-classed components in order', () => {
This test has nothing to do with that. It's just asserting that the inline styles/classes are present when the directive is instantiated.

2019-04-05 15:57 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/styling_spec.ts
> +  it('should render styling for parent and sub-classed components in order', () => {
Hmm, I'm confused even more than :-) Why is the title of the test mentioning "order" then?

2019-04-05 18:01 UTC, matsko commented
https://tap.corp.google.com/ui#id=OCL:242073253:BASE:242154491:1554487206107:17aac872

2019-04-05 20:15 UTC, mhevery approved these changes

2019-04-05 20:18 UTC, pkozlowski-opensource approved these changes

2019-04-05 21:34 UTC, kara requested changes
A few more small changes

2019-04-05 21:34 UTC, kara commented on packages/core/src/render3/state.ts
> +let activeDirectiveSuperClassHeight = 0;
As far as I can tell, this global has no docs. It's not clear to me why it's necessary (in addition to the depth). Can you add docs that explain why it's necessary?

2019-04-05 21:34 UTC, kara commented on packages/core/src/render3/styling/class_and_style_bindings.ts
> +  assertValidDirectiveIndex(context, directiveIndex);
Seems like this should be an ngDevMode assert so it tree-shakes.

2019-04-05 21:34 UTC, kara commented on packages/core/src/render3/styling/class_and_style_bindings.ts
> +  assertValidDirectiveIndex(context, directiveIndex);
Needs devmode guard

2019-04-05 22:03 UTC, kara approved these changes
You'll probably need to re-run the symbol test now that `assertValidDirectiveIndex` should be tree shaken

2019-04-05 22:03 UTC, kara commented on packages/core/src/render3/state.ts
> + * needs to keep track exactly how many were encountered so it can accurately
```suggestion
 * needs to keep track of exactly how many were encountered so it can accurately
```

2019-04-05 23:51 UTC, closed without merging