feat(forms): change addControl & removeControl to accept options
angular/angular pull request #29664
Opened 2019-04-02 14:31 UTC by MikeJerred

This commit adds an optional argument to the methods addControl
and removeControl in the FormGroup class. This argument can be
used to prevent an event from being emitted.

PR Close #29662

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-04-02 22:30 UTC, kara requested changes
Thanks for doing this! I have some thoughts below. Main things are:

- `emitEvent` flag should only control event emission, not value/validity updates
- We should probably add a similar feature to `FormArray` so they are consistent.

2019-04-02 22:30 UTC, kara commented on packages/forms/src/model.ts
> +   * observables emit events with the latest status and value when the control is added.
Nit: formatting

2019-04-02 22:30 UTC, kara commented on packages/forms/src/model.ts
> +    if (options.emitEvent === false) return;
If we simply return early here, the value and validity of the `FormGroup` will not be updated. This seems like unwanted behavior to me because it breaks our guarantee that the value and validity state of a `FormGroup` is built up based on its child controls (it will be incorrect). It also changes the behavior of the `emitEvent` flag to be inconsistent with the same flag for other methods, which only control events.

I think what you want to do is pass the options to the `updateValueAndValidity` call, so the value/validity are updated, but the events are skipped (only). Same below.

2019-04-02 22:30 UTC, kara commented on packages/forms/test/form_group_spec.ts
> +        expect(g.valid).toBe(true);
These tests don't seem to be quite right. I'd argue that the value and validity *should* be updated, but the events should not be emitted. Let's change this test to assert the opposite and add a new test that actually tests event emission?

2019-04-02 23:33 UTC, aitboudad commented on packages/forms/src/model.ts
> +    if (options.emitEvent === false) return;
still useful in some use-cases, when dealing with a large form calling updateValueAndValidity takes a quick large amount of time, so instead we call `updateValueAndValidity` once we have done with registration.

so having an option to skip `updateValueAndValidity` would be great!

2019-04-02 23:36 UTC, kara commented on packages/forms/src/model.ts
> +    if (options.emitEvent === false) return;
Seems like that would be a larger API design discussion, and outside the scope of this PR.

2019-04-03 07:57 UTC, MikeJerred commented on packages/forms/src/model.ts
> +    if (options.emitEvent === false) return;
It sounds like there should be an options parameter added to `addControl` and `removeControl`, and also there should be the `registerControl` and `unregisterControl` methods?

2019-04-04 07:44 UTC, MikeJerred commented
I have made changes so that addControl/removeControl pass the options argument to updateValueAndValidity, and also added an unregister method which does not update value and validity. If this approach seems sensible I will apply them to FormArray too.

2019-04-30 09:36 UTC, MikeJerred commented on packages/forms/src/model.ts
> +    if (options.emitEvent === false) return;
Hi, just want to check up on this: do the changes I have made here seem correct now? If so I can do them for FormArray too.

2019-05-07 22:55 UTC, kara requested changes
The `emitEvent` option looks good, but let's remove the other new APIs added since the last review into other PRs / issues.

2019-05-07 22:55 UTC, kara commented on packages/forms/src/model.ts
> +  unregisterControl(name: string): AbstractControl|null {
Can you split this out into a separate PR? We try to make atomic changes, and this is a new API that needs discussion.

2019-05-07 22:55 UTC, kara commented on packages/forms/src/model.ts
> +      opts: {onlySelf?: boolean, emitEvent?: boolean} = {}): void {
Can you split out `onlySelf` into a separate change? `emitEvent` was the original scope of the PR, and the other option needs further discussion.

2019-05-09 08:17 UTC, MikeJerred commented
@kara I have made these changes, and extended them to FormArray too

2019-05-14 23:01 UTC, kara approved these changes
Changes LGTM. Can you squash the commits such that there are the following commits:

1 - feat(forms): add emitEvent option when adding or removing controls from a group
2 - feat(forms): add emitEvent option when adding or removing controls from an array

We probably also want to add some more detail to the commit messages (e.g. why this feature is useful).

2019-05-14 23:03 UTC, kara commented
@IgorMinar Do you want to take a look at the public API changes?

2019-05-17 08:46 UTC, closed without merging

2019-05-17 08:48 UTC, MikeJerred commented
@kara I have squashed the commits but github has closed the PR when I did this as I deleted the branch on remote

2019-05-22 21:00 UTC, MikeJerred commented
@kara I have created a new PR here: https://github.com/angular/angular/pull/30623