docs(router): Move ActivatedRoute example to mini-app
angular/angular pull request #29755
Opened 2019-04-07 19:09 UTC by frederikprijck

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
As requested in https://github.com/angular/angular/pull/29752, this PR moves the example of that PR to a mini-app in such a way that the example is guaranteed to be compilable.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-04-07 19:14 UTC, mary-poppins commented
You can preview 53f7e0c at https://pr29755-53f7e0c.ngbuilds.io/.

2019-04-07 19:31 UTC, mary-poppins commented
You can preview e9c5a67 at https://pr29755-e9c5a67.ngbuilds.io/.

2019-04-07 19:37 UTC, mary-poppins commented
You can preview 280e714 at https://pr29755-280e714.ngbuilds.io/.

2019-04-07 20:25 UTC, mary-poppins commented
You can preview 02d38e5 at https://pr29755-02d38e5.ngbuilds.io/.

2019-04-07 20:53 UTC, mary-poppins commented
You can preview cca9d96 at https://pr29755-cca9d96.ngbuilds.io/.

2019-04-07 21:07 UTC, mary-poppins commented
You can preview 768b4bb at https://pr29755-768b4bb.ngbuilds.io/.

2019-04-09 09:32 UTC, gkalpak requested changes
:tada: Thx ❤️ 

The CI failure is legit. You need to apply [this change][1]; i.e. change [packages/tsconfig.json][2] like this:

```diff
-    "examples/*/main.ts",
+    "examples/**/main.ts",
```

[1]: https://github.com/angular/angular/pull/26002/commits/1f8c38dd9d7fb94fa33cbaf124a724d416d3ac44?file-filters%5B%5D=.json#diff-2ccdf1b2c6439ed3bc45e60d9ee716e6R42
[2]: https://github.com/angular/angular/blob/768b4bbb1f03ad54a2f03b254328192794738ffd/packages/tsconfig.json#L42

2019-04-09 09:32 UTC, gkalpak commented on packages/examples/router/activated-route/BUILD.bazel
> +load("//tools:defaults.bzl", "ng_module", "ts_library")
If you are not using `ts_library` and `protractor_web_test_suite` here (👀), you don't need to import them :grin:

2019-04-09 09:32 UTC, gkalpak commented on packages/examples/router/activated-route/module.ts
> +@Component({selector: 'example-app', template: '...'})
Nit: Since the component metadat are not relevant for the example (and it seems confusing to have an `ActivatedRouteComponent` with an `example-app` selector), consider either hiding them away or create an additional `AppComponent`:

**Option 1:**
```ts
@Component({
  // #enddocregion activated-route
  selector: 'example-app',
  template: '...',
  // #docregion activated-route
})
```

**Option 2:**
```ts
@Component({selector: 'activated-route', template: '...'})
export class ActivatedRouteComponent { ... }
// #enddocregion activated-route

@Component({selector: 'example-app', template: '...'})
export class ExampleAppComponent { ... }
```

2019-04-09 09:32 UTC, gkalpak commented on packages/router/src/router_state.ts
> + *     header="app.module.ts" linenums="false"}
Nit: A different name would seem more "realistic" 😛 E.g. `app.component.ts` or `activated-route.component.ts`.

2019-04-10 20:03 UTC, mary-poppins commented
You can preview 8518a16 at https://pr29755-8518a16.ngbuilds.io/.

2019-04-10 20:03 UTC, frederikprijck commented
@gkalpak I've updated the PR to resolve your comments!

2019-04-10 20:05 UTC, mary-poppins commented
You can preview f2f18d4 at https://pr29755-f2f18d4.ngbuilds.io/.

2019-04-10 20:06 UTC, mary-poppins commented
You can preview 1533653 at https://pr29755-1533653.ngbuilds.io/.

2019-04-10 20:09 UTC, mary-poppins commented
You can preview 580f7a4 at https://pr29755-580f7a4.ngbuilds.io/.

2019-04-11 06:12 UTC, frederikprijck commented
@gkalpak I've updated the PR! 🎉

2019-04-11 06:14 UTC, mary-poppins commented
You can preview a0a3ca7 at https://pr29755-a0a3ca7.ngbuilds.io/.

2019-04-11 15:26 UTC, gkalpak approved these changes
One minor comments. Other than that LGTM.
Thx for working on this ❤️

2019-04-11 15:26 UTC, gkalpak commented on packages/examples/router/activated-route/module.ts
> +// tslint:enable: no-duplicate-imports
Can you please ensure that this comment does not end up in the code snippet?

2019-04-12 20:55 UTC, mary-poppins commented
You can preview c046dc5 at https://pr29755-c046dc5.ngbuilds.io/.

2019-04-12 20:56 UTC, frederikprijck commented on packages/examples/router/activated-route/module.ts
> +// tslint:enable: no-duplicate-imports
Done

2019-04-16 14:18 UTC, brandonroberts commented
@gkalpak shouldn't the Bazel config go into the `router` folder so its consistent with the setup of the other examples?

2019-04-17 09:01 UTC, gkalpak commented
Not all example are set up equally 😛
For example, [upgrade examples][1] have per-directory `BUILD.bazel` files. As far as I understand (and it is not very far when it comes to bazel), it makes sense to have on config per project. Some examples are set up to have one project per top-level directory (and load the sub-examples as routes to that main app) and others are/will be set up as one project per sub-directory.

In some case it makes a difference (e.g. the upgrade examples use different bootstrapping, so they can all be part of a single app), but in this case it probably doesn't. I just thought that having a project in the sub-directory avoid unnecessary boilerplate. It might make sense to move to the "one main app - multiple sub-examples as routes" if we get more `router` examples.

In any case, I don't feel strongly about this. Leaving it up to you. (You knwo more than me about running examples with bazel anyway :wink:)

[1]: https://github.com/angular/angular/tree/c046dc5dfe437d66b3c1d6a8972d851e1cfbccdd/packages/examples/upgrade/static/ts/full

2019-04-28 17:54 UTC, frederikprijck commented
Im not sure if i should still make changes of not. I think both arguments make sense...

2019-05-07 17:52 UTC, gkalpak commented
CI is red and it doesn't look like a flake. (Might need another rebase on master.)

2019-05-08 07:55 UTC, mary-poppins commented
You can preview 0a3ce94 at https://pr29755-0a3ce94.ngbuilds.io/.

2019-05-08 18:45 UTC, alxhub commented
[Presubmit](https://test.corp.google.com/ui#id=OCL:247255127:BASE:247255153:1557340329937:898d6990) (note this will have the build_test failing due to a missing g3 patch for another PR still pending in the sync)

2019-05-08 20:47 UTC, jasonaden approved these changes

2019-05-08 20:54 UTC, closed without merging