perf(ivy): make sure host-styling instructions are efficiently queued
angular/angular pull request #29798
Opened 2019-04-09 23:53 UTC by matsko

2019-04-10 05:07 UTC, mhevery reviewed
a quick review, will take a better look later.

2019-04-10 05:07 UTC, mhevery commented on packages/core/src/render3/instructions/styling.ts
> +  enqueueHostInstructionStart(
Could we simplify this into a single function call. Having so many calls will take the VM a lot of time to inline. Can we make all of the functions take the same number of arguments. (Just have function ignore the extra ones) That way we keep it simple.

2019-04-10 05:26 UTC, mhevery requested changes

2019-04-10 05:26 UTC, mhevery commented on packages/core/src/render3/state.ts
> +const hostStylingQueue: HostInstructionsQueue = [HostInstructionsQueueIndex.ValuesStartPosition];
can we simplify this?

```
const hostStylingQueue: any[] = [];
let hostStylingQueueIndex = 0;

export function enqueueHostStylingFn(fn: Function, arg0, arg1, arg2, arg3, arg4): void {
 hostStylingQueue[hostStylingQueueIndex++] = fn;
 hostStylingQueue[hostStylingQueueIndex++] = arg0;
 hostStylingQueue[hostStylingQueueIndex++] = arg1;
 hostStylingQueue[hostStylingQueueIndex++] = arg2;
 hostStylingQueue[hostStylingQueueIndex++] = arg3;
 hostStylingQueue[hostStylingQueueIndex++] = arg4;
}

export function flushHostStyling() {
  for(let i=0; i<hostStylingQueueIndex; i+=4){
    hostStylingQueue[i + 0]()(
      hostStylingQueue[i + 1],
      hostStylingQueue[i + 2],
      hostStylingQueue[i + 3],
      hostStylingQueue[i + 4],
    );
  }
  hostStylingQueueIndex = 0;
}
```

2019-04-10 05:26 UTC, mhevery commented on packages/core/src/render3/styling/host_instructions_queue.ts
> +function allocateNextInsertionPoint(priority: number, isSubClassed?: boolean): number {
I don't think most of these methods are needed with the suggestion above

2019-04-10 05:26 UTC, mhevery commented on packages/core/src/render3/styling/host_instructions_queue.ts
> +  const index = context[StylingIndex.FinalDirectiveIndexThatFlushes];
Why do you care if flush is allowed? Why not just always do flush, and if there is nothing there nothing happens?

2019-04-16 21:53 UTC, matsko commented on packages/core/src/render3/styling/host_instructions_queue.ts
> +  const index = context[StylingIndex.FinalDirectiveIndexThatFlushes];
This is the hack we have in place to avoid having every `elementStylingApply()` or `hostStylingApply()` function cause a flush. Only when the very last flush is run then will the styling be applied (this check ensures that the last directive is the last one to cause the flush).

2019-04-17 12:52 UTC, mhevery approved these changes

2019-04-17 13:46 UTC, pkozlowski-opensource commented
@matsko would you mind share profiling numbers (or better yet - profile records) before / after this change? I'm asking since I did a quick test on the Material demo app with this change and couldn't see any significant difference so I guess we are looking at different scenarios... Just trying to make sure that Material case is well covered.

2019-05-07 19:48 UTC, closed without merging