Rewrite CLI analytics config
angular/angular pull request #29821
Opened 2019-04-10 20:59 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-04-10 21:05 UTC, mary-poppins commented
You can preview 7093be4 at https://pr29821-7093be4.ngbuilds.io/.

2019-04-10 21:17 UTC, petebacondarwin requested changes

2019-04-10 21:17 UTC, petebacondarwin commented on aio/content/cli/usage-analytics-gathering.md
> +The value of the key is the your organization's tracking ID, as assigned by Google Analytics.
```suggestion
The value of the key is your organization's tracking ID, as assigned by Google Analytics.
```

2019-04-10 21:17 UTC, petebacondarwin commented on aio/content/cli/usage-analytics-gathering.md
> +You can choose use a descriptive string as the key value, or be assigned a random key when you run the CLI command.
```suggestion
You can choose to use a descriptive string as the key value, or be assigned a random key when you run the CLI command.
```

2019-04-10 21:32 UTC, mary-poppins commented
You can preview 2180f53 at https://pr29821-2180f53.ngbuilds.io/.

2019-04-10 22:39 UTC, alexeagle approved these changes

2019-04-15 15:36 UTC, mary-poppins commented
You can preview 29ddafe at https://pr29821-29ddafe.ngbuilds.io/.

2019-04-16 13:14 UTC, petebacondarwin approved these changes

2019-04-16 18:24 UTC, mary-poppins commented
You can preview 1cf2532 at https://pr29821-1cf2532.ngbuilds.io/.

2019-04-16 18:25 UTC, mary-poppins commented
You can preview 3a5a908 at https://pr29821-3a5a908.ngbuilds.io/.

2019-04-17 16:05 UTC, mary-poppins commented
You can preview cf91fc6 at https://pr29821-cf91fc6.ngbuilds.io/.

2019-04-18 15:24 UTC, mary-poppins commented
You can preview 8b6248a at https://pr29821-8b6248a.ngbuilds.io/.

2019-04-23 19:05 UTC, jenniferfell approved these changes

2019-04-23 22:15 UTC, closed without merging