add redirects for deprecated http APIs
angular/angular pull request #29907
Opened 2019-04-15 15:08 UTC by chembu

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Added redirect links for deprecated http APIs

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-04-15 15:14 UTC, mary-poppins commented
You can preview 321da33 at https://pr29907-321da33.ngbuilds.io/.

2019-04-15 16:08 UTC, petebacondarwin reviewed
I wonder if we really want to direct people for individual files? Without some message explaining what has happened it could be quite confusing. I would have expected to be redirected to a page that explained how to migrate from the old http to the new one.

2019-04-15 16:21 UTC, CaerusKaru commented on aio/firebase.json
> +      {"type": 301, "source": "/**/api/http/BrowserXhr", "destination": "/api/common/http/BrowserXhr"},
I know we discussed offline that this would be made public, but other discussions have taken place with @alxhub and @vikerman since then, and that is no longer the case.

2019-04-15 17:14 UTC, gkalpak requested changes
I am not sure how I feel about this. I think I would rather either be redirected to migration docs or to the default 404 page (which shows related search results).

2019-04-15 17:14 UTC, gkalpak commented on aio/firebase.json
> +      {"type": 301, "source": "/**/api/http/ReadyState", "destination": "/api/common/http/HttpClient"},
In order for these to work correctly on subsequent navigations, you also need to update [ngsw-config.json > navigationUrls][1].

[1]: https://github.com/angular/angular/blob/321da330177a1ec0beede7fc2e802d400101aa1a/aio/ngsw-config.json#L72

2019-04-16 22:52 UTC, mary-poppins commented
You can preview a065d75 at https://pr29907-a065d75.ngbuilds.io/.

2019-04-17 18:06 UTC, mary-poppins commented
You can preview 300d999 at https://pr29907-300d999.ngbuilds.io/.

2019-04-17 18:22 UTC, mary-poppins commented
You can preview b5e820f at https://pr29907-b5e820f.ngbuilds.io/.

2019-04-18 16:53 UTC, mary-poppins commented
You can preview b9d9906 at https://pr29907-b9d9906.ngbuilds.io/.

2019-04-23 18:41 UTC, jenniferfell commented on aio/firebase.json
> +      {"type": 301, "source": "/**/api/http/BrowserXhr", "destination": "/api/common/http/BrowserXhr"},
Is this one right? I don't see a BrowserXhr in @angulat/common/http. Copy-paste typo maybe?

2019-04-23 19:00 UTC, chembu commented on aio/firebase.json
> +      {"type": 301, "source": "/**/api/http/BrowserXhr", "destination": "/api/common/http/BrowserXhr"},
Adam Plumer is working on getting the BrowserXhr externalized
https://github.com/angular/angular/pull/29236

2019-08-21 17:31 UTC, IgorMinar commented
I agree with George, we should redirect all of these to https://angular.io/guide/deprecations#angularhttp instead.

2019-09-23 15:37 UTC, closed without merging

2019-09-23 15:37 UTC, jbogarthyde commented
It was decided NOT to have individual redirects from old HTTP API pages, but a single redirect to the deprecations page. This is the current behavior.