docs: add example for multi provider
angular/angular pull request #29909
Opened 2019-04-15 17:25 UTC by santoshyadav198613

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #29860

## What is the new behavior?

Added example for multi provider.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-04-15 17:54 UTC, mary-poppins commented
You can preview f6e160e at https://pr29909-f6e160e.ngbuilds.io/.
You can preview 85d1a43 at https://pr29909-85d1a43.ngbuilds.io/.
You can preview 2a8cfc0 at https://pr29909-2a8cfc0.ngbuilds.io/.

2019-04-15 18:05 UTC, mary-poppins commented
You can preview 464828e at https://pr29909-464828e.ngbuilds.io/.

2019-04-15 18:18 UTC, mary-poppins commented
You can preview 2c3476a at https://pr29909-2c3476a.ngbuilds.io/.

2019-04-15 18:24 UTC, mary-poppins commented
You can preview 9d72cb7 at https://pr29909-9d72cb7.ngbuilds.io/.

2019-04-16 18:51 UTC, mary-poppins commented
You can preview 4592185 at https://pr29909-4592185.ngbuilds.io/.

2019-04-18 12:01 UTC, mary-poppins commented
You can preview a95b02a at https://pr29909-a95b02a.ngbuilds.io/.

2019-05-09 14:11 UTC, santoshyadav198613 commented
Hi @brandontroberts can you review once if it makes sense to have this as part of docs.

2019-05-09 14:24 UTC, trotyl commented on aio/content/examples/dependency-injection/src/app/app.config.ts
> +export const HERO_MULTI_DI_CONFIG: AppConfig[] = [{
This needs to be a single element, the array is composed by framework itself.

2019-05-09 14:24 UTC, trotyl commented on aio/content/guide/dependency-injection-providers.md
> +You can also create multiple provider, Angular uses lot of multiple providers like `HTTP_INTERCEPTORS` and provides it to be used in applications. The advantage is you can add values into an array an
```suggestion
You can also create multiple provider, Angular uses lot of multiple providers like `HTTP_INTERCEPTORS` and provides it to be used in applications. The advantage is you can add values into an array and use them whenever you need it, a simple example is, in case you want a mechanism to register external components within your framework, you can get those values via a multi provider and load them.
```

2019-05-09 19:44 UTC, mary-poppins commented
You can preview b2f2a4a at https://pr29909-b2f2a4a.ngbuilds.io/.

2019-05-21 12:09 UTC, santoshyadav198613 commented
Hi @kapunahelewong  can you review this PR.

2019-05-23 18:47 UTC, kapunahelewong commented
Hey @santoshyadav198613, I'm going to have to tag @jbogarthyde for review of this particular PR. @jbogarthyde could you take a look?

2019-05-24 12:31 UTC, santoshyadav198613 commented
Thanks @kapunahelewong.

2019-05-28 16:38 UTC, brandonroberts requested changes

2019-05-28 16:38 UTC, brandonroberts commented on aio/content/examples/dependency-injection/src/app/app.config.ts
> +export const HERO_MULTI_DI_CONFIG: AppConfig = {
This should be something other than a duplicate of what's in `HERO_DI_CONFIG`

2019-05-28 16:38 UTC, brandonroberts commented on aio/content/examples/dependency-injection/src/app/providers.component.ts
> +  /*
This isn't being displayed in the doc. Why is it needed here?

2019-05-28 16:38 UTC, brandonroberts commented on aio/content/examples/dependency-injection/src/app/providers.component.ts
> +   // #docregion provider-11-ctor-interface
Same, not being displayed or talked about in the doc

2019-05-28 16:38 UTC, brandonroberts commented on aio/content/examples/dependency-injection/src/app/providers.component.ts
> +      // added to fix unused expression error
Remove comment if not relevant

2019-05-28 16:38 UTC, brandonroberts commented on aio/content/examples/dependency-injection/src/app/providers.component.ts
> +      this.log = 'APP_CONFIG Application title is ' + c.title;
Needs a better usage example or explanation than logging out titles. Why would you use more than one application title?

2019-05-28 16:38 UTC, brandonroberts commented on aio/content/guide/dependency-injection-providers.md
> +### Multiple providers
This should be moved as a sub-section under `Predefined tokens and multiple providers`

2019-09-05 22:55 UTC, kara requested changes

2019-09-05 22:55 UTC, kara commented on aio/content/guide/dependency-injection-providers.md
> +You can also create multiple provider, Angular uses lot of multiple providers like `HTTP_INTERCEPTORS` and provides it to be used in applications. The advantage is you can add values into an array an
We should call them `multi-providers` rather than `multiple providers`. It's also not clear to me from this how they are different from normal providers and why they're benefiical.   Something like:

```suggestion
You can also create multi-providers.  Multi-providers are like normal providers, except that you can provide many values for a particular token. When the token is injected, you will receive an array of all the values that were provided (they don't override each other). This can be useful if... 
```

2019-09-05 22:55 UTC, kara commented on aio/content/guide/dependency-injection-providers.md
> +The only change you have to make is to convert the above provider to multi provider is.
Let's make this more concrete

```suggestion
To convert the above provider to a multi-provider, add the `multi` flag:
```

2019-09-05 22:55 UTC, kara commented on aio/content/guide/dependency-injection-providers.md
> +To register the multi providers use the below syntax.
```suggestion
To register the multi providers, use the below syntax.
```

2020-11-12 10:25 UTC, petebacondarwin commented
@santoshyadavdev - it looks like you never got round to addressing the feedback here; and it is now conflicting. Do you still want to complete this PR?

2020-12-08 09:55 UTC, petebacondarwin commented
Closing due to no response.

2020-12-08 09:55 UTC, closed without merging