add redirect links from deprecated http APIs page to release notes
angular/angular pull request #29951
Opened 2019-04-17 04:46 UTC by chembu

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
added redirect links from deprecated http APIs page to redirect to release notes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-04-17 04:52 UTC, mary-poppins commented
You can preview 35f36c3 at https://pr29951-35f36c3.ngbuilds.io/.

2019-04-17 15:09 UTC, mary-poppins commented
You can preview 0c70ac4 at https://pr29951-0c70ac4.ngbuilds.io/.

2019-04-17 18:01 UTC, gkalpak requested changes

2019-04-17 18:01 UTC, gkalpak commented on aio/ngsw-config.json
> +    "!/api/http/**",
You also need `"!/api/http"` (to match `angular.io/api/http`).

2019-04-17 18:04 UTC, mary-poppins commented
You can preview b82509c at https://pr29951-b82509c.ngbuilds.io/.

2019-04-17 18:06 UTC, chembu commented on aio/firebase.json
> +      {"type": 301, "source": "/api/:http*", "destination": "/guide/releases"},
/guide/releases is just a place holder. Will change it to deprecations.md as soon as Jennifer has a PR for it.

2019-04-17 19:49 UTC, mary-poppins commented
You can preview 439dd7a at https://pr29951-439dd7a.ngbuilds.io/.

2019-04-18 00:36 UTC, mary-poppins commented
You can preview f178170 at https://pr29951-f178170.ngbuilds.io/.

2019-04-18 00:55 UTC, mary-poppins commented
You can preview f404188 at https://pr29951-f404188.ngbuilds.io/.

2019-04-18 10:24 UTC, gkalpak commented
Regarding the failures in `redirects-test` (part of the `test_aio` CircleCI job):

We have a [URLS_TO_REDIRECT.txt][1] file that contains some legacy URLs (i.e. URLs from back an earlier version of angular.io, with different URL structure), which should now be redirected to new URLs. The file contains "from"/"to" pairs (one per line).

In there, there are some `/api/http/...` "from" URLs, whose "to" values need to be updated to reflect the new redirection.
(Note, there are also some URLs that are redirected to `/api/http/...` and then to something else. They need to be updated too. E.g. `/docs/latest/ts/api/http/...` might be redirected to `/api/http/...`, so that needs to be updated as well.)

If you want to check locally, you can run `yarn redirects-test` (from inside `aio/`) and see if any tests fail.

[1]: https://github.com/angular/angular/blob/78146c1890b472621acf33d778477db8df816043/aio/tests/deployment/shared/URLS_TO_REDIRECT.txt

2019-04-18 15:52 UTC, mary-poppins commented
You can preview 6b4df7a at https://pr29951-6b4df7a.ngbuilds.io/.

2019-04-23 17:09 UTC, mary-poppins commented
You can preview 6f8944c at https://pr29951-6f8944c.ngbuilds.io/.

2019-04-23 17:37 UTC, mary-poppins commented
You can preview 030a366 at https://pr29951-030a366.ngbuilds.io/.

2019-04-23 18:56 UTC, jenniferfell requested changes
The redirects look good in firebase.json, ngsw-config.json, and URLS_TO_REDIRECT.txt. 

The other three files look like they were accidentally included somehow. ?

2019-04-23 19:04 UTC, mary-poppins commented
You can preview 0bd7abf at https://pr29951-0bd7abf.ngbuilds.io/.

2019-04-23 19:12 UTC, mary-poppins commented
You can preview c5da7cd at https://pr29951-c5da7cd.ngbuilds.io/.

2019-04-23 19:27 UTC, mary-poppins commented
You can preview 53d9b36 at https://pr29951-53d9b36.ngbuilds.io/.

2019-04-23 19:41 UTC, jenniferfell approved these changes

2019-04-23 19:43 UTC, jenniferfell commented
@gkalpak How's this look? Hoping to merge to master before RC0 splits off.

2019-04-23 20:02 UTC, mary-poppins commented
You can preview eac5144 at https://pr29951-eac5144.ngbuilds.io/.

2019-04-24 17:36 UTC, gkalpak approved these changes

2019-04-24 17:36 UTC, gkalpak commented on aio/firebase.json
> +      // APIs under `http` package is deprecated and new APIs are available under `common/http` package
_is deprecated_ --> _are deprecated_

2019-04-24 18:03 UTC, IgorMinar commented on aio/firebase.json
> +      // APIs under `http` package is deprecated and new APIs are available under `common/http` package
let's fix this in a follow up PR

2019-04-24 18:03 UTC, IgorMinar commented
merge-assistance: global approval

2019-04-24 18:08 UTC, closed without merging