fix(ivy): ngcc - prefer JavaScript source files when resolving module…
angular/angular pull request #30017
Opened 2019-04-21 19:32 UTC by JoostK

… imports

Packages that do not follow APF may have the declaration files in the same
directory as one source format, typically ES5. This is problematic for ngcc,
as it needs to create a TypeScript program with all JavaScript sources of
an entry-point, whereas TypeScript's module resolution mechanism would have
resolved an internal module import to the external facing .d.ts declaration
file, instead of the JavaScript source file. This behavior results in the
program to be analysed being incomplete.

This commit introduces a custom compiler host that recognizes the above
scenario and rewires the resolution of a .d.ts declaration file to its
JavaScript counterpart, if applicable.

Fixes #29939

2019-04-24 20:59 UTC, alxhub approved these changes

2019-04-24 21:05 UTC, petebacondarwin commented
I think we should land https://github.com/angular/angular/pull/29643 and then consider using the `NgccCompilerHost` and the `ModuleResolver` to do this work.

2019-04-24 21:08 UTC, JoostK commented on packages/compiler-cli/ngcc/src/packages/entry_point_bundle.ts
> +      const {resolvedModule} = ts.resolveModuleName(
This is almost the same code as what TS uses by default, with one difference: TypeScript's default logic has an additional caching layer, besides the module resolution cache:

See `loadWithLocalCache`:
https://github.com/Microsoft/TypeScript/blob/b534fb4849eca0a792199fb6c0cb8849fece1cfd/src/compiler/program.ts#L409-L426

used here:
https://github.com/Microsoft/TypeScript/blob/b534fb4849eca0a792199fb6c0cb8849fece1cfd/src/compiler/program.ts#L653-L657

2019-04-30 12:16 UTC, MathewBerg commented
Until/if this PR lands, is there a suggested workaround that can be done locally? I'd love to test IVY but use angularfire2 extensively.

2019-04-30 12:33 UTC, petebacondarwin commented
Now that #29643 has landed we should be able to move this PR along.

2019-04-30 21:26 UTC, JoostK commented
I rebased this and derived a custom compiler host based on `NgccCompilerHost`. I did not use the `ModuleResolver` right now, as it introduces some things we would need to think about:

1) For `ResolvedExternalModule` we'd have to determine the typings location, i.e. load the `package.json` file and resolve its `typings` key. If it doesn't have it, we should instead use `main` (or others?) to resolve the `.js` source file instead?
2) For `ResolvedDeepImport` we also need to resolve the `typings` key in `package.json` and derive the correct `.d.ts` file use the deeply imported path and and the root of the typings directory.

I can't really foresee if the above would be at all accurate/cover our use-cases.

2019-05-01 07:44 UTC, petebacondarwin requested changes
I agree that using `ModuleResolver` from the dependencies folder is not correct here. That class is optimised for dependency resolution rather than actually compiling a JS program.

Can you confirm whether you agree about the `entryPointPath` check not being needed and then tidy up the other nits.

Otherwise LGTM! NIce work.

2019-05-01 07:44 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/ngcc_compiler_host.ts
> +  readonly cache = ts.createModuleResolutionCache(
Why `readonly` rather than `private`?

2019-05-01 07:44 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/ngcc_compiler_host.ts
> +      // JavaScript being present in the program. This logic recognizes this scenario and rewires
```suggestion
      // JavaScript being present in the program. This logic recognizes this scenario and rewrites
```

2019-05-01 07:44 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/ngcc_compiler_host.ts
> +          (moduleName.startsWith('./') || moduleName.startsWith('../')) &&
Use `isRelativePath()` from `utils.ts`

2019-05-01 07:44 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/ngcc_compiler_host.ts
> +          resolvedModule.resolvedFileName.startsWith(this.entryPointPath)) {
I think that this is not correct: Source files can exist in a folder that is outside of the entry-point folder (but in the same package) while still being part of the source for that entry-point. Angular Material is an example of this.

Nor is it needed, I believe: if the import is "relative" then it would be breaking the node.js module model to relatively import a JS file from outside the entry-point. There is the case where an external import is a .d.ts file that then relatively imports `.d.ts` files of its own, but this is already covered by the `containingFile.endsWith('.js')` check.

2019-05-01 07:44 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/ngcc_compiler_host.ts
> +          containingFile.endsWith('js') &&
```suggestion
          containingFile.endsWith('.js') &&
```

To be on the safe side :-)

2019-05-01 07:52 UTC, JoostK commented on packages/compiler-cli/ngcc/src/packages/ngcc_compiler_host.ts
> +          containingFile.endsWith('js') &&
Whoops, nice catch!

2019-05-01 08:01 UTC, JoostK commented on packages/compiler-cli/ngcc/src/packages/ngcc_compiler_host.ts
> +          resolvedModule.resolvedFileName.startsWith(this.entryPointPath)) {
I think you are correct that we can get rid of the check altogether. I put it in for the case where an import in an external package should not be rewritten to the `.js` file, but with the `endsWith('.js')` check this is alleviated.

There's one thing but I don't think it can actually happen: an external library import is resolved to a `.js` file, then one of its relative imports gets resolved to a `.d.ts` file. The latter step is weird, because the package did not get resolved to a `.d.ts` file in the first place so neither should its relative imports (as those must point into the same entry-point, which apparently does not have typings).

I will remove the check and verify that the tests still pass.

2019-05-01 08:03 UTC, JoostK commented on packages/compiler-cli/ngcc/src/packages/ngcc_compiler_host.ts
> +  readonly cache = ts.createModuleResolutionCache(
I should have made it `private`. The `readonly` is a habit, I just forget the `private` ;)

2019-05-01 08:14 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/ngcc_compiler_host.ts
> +          resolvedModule.resolvedFileName.startsWith(this.entryPointPath)) {
Also this check would not be sufficient in the case where there was a `node_modules` within the entry-point folder :-)

I think it would be very weird for an external entry-point to resolve to a `.js` file and then also contain `.d.ts` files. In the `NewEntryPointFileWriter` I used the `entryPoint.package` path, to decide which files to copy. If we really needed to this check then that would be the better path to use - although there could still be weird corner cases between secondary entry-points.

2019-05-01 14:46 UTC, petebacondarwin approved these changes

2019-05-01 14:50 UTC, alxhub approved these changes

2019-05-01 14:55 UTC, petebacondarwin commented
Caretaker (merge-assistance): @JoostK  and @petebacondarwin have boths signed CLAs.

2019-05-01 20:15 UTC, kara commented
[presubmit](http://test/OCL:246185704:BASE:246185723:1556741718723:42548c3d)

2019-05-01 22:43 UTC, closed without merging