refactor(ivy): undeprecate inject
angular/angular pull request #30132
Opened 2019-04-25 23:32 UTC by benlesh

Per offline discussion, `inject` is already an API that is seeing limited use. We are going to undeprecate it _for now_.

2019-04-25 23:33 UTC, kara requested changes

2019-04-25 23:33 UTC, kara commented on packages/core/src/di/injector_compatibility.ts
> - * code should now use ɵɵinject instead.
We should also remove the warning above

```
 WARNING: This function is meant to be generated by the Ivy compiler, and is not meant for
 * developer consumption!	 * developer consumption!
```

2019-04-25 23:33 UTC, kara commented on packages/core/src/di/injector_compatibility.ts
>    return (_injectImplementation || injectInjectorOnly)(token, flags);
We should also remove the prefix

2019-04-25 23:38 UTC, mhevery commented on packages/core/src/di/injector_compatibility.ts
>    return (_injectImplementation || injectInjectorOnly)(token, flags);
I think we should leave it as is. This way we have it exported twice once for public consumption and once for the generated code.

2019-04-25 23:50 UTC, kara approved these changes
LGTM

2019-04-25 23:51 UTC, kara commented on packages/core/src/di/injector_compatibility.ts
>    return (_injectImplementation || injectInjectorOnly)(token, flags);
SGTM

2019-04-26 00:14 UTC, benlesh commented
[presubmit](http://test/OCL:245336696:BASE:245336721:1556237589255:d57c564a)

2019-04-26 00:22 UTC, mhevery approved these changes

2019-04-26 17:32 UTC, IgorMinar approved these changes

2019-04-26 18:08 UTC, closed without merging