feat(common): stricter types for SlicePipe
angular/angular pull request #30156
Opened 2019-04-26 19:45 UTC by cexbrayat

Adds overloads to the `transform` methods of `SlicePipe`,
to have better types than `any` for `value` and `any` as a return.
With this commit, using `slice` in an `ngFor` still allow to type-check the content of the `ngFor`
with `fullTemplateTypeCheck` enabled in Ivy:

    <div *ngFor="let user of users | slice:0:2">{{ user.typo }}</div>
                                                        |
                                                        `typo` does not exist on type `UserModel`

whereas it is currently not catched (as the return of `slice` is `any) neither in VE nor in Ivy.

BREAKING CHANGE
`SlicePipe` now only accepts an array of values, a string, null or undefined.
This was already the case in practice, and it still throws at runtime if another type is given.
But it is now a compilation error to try to call it with an unsupported type.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #30086

## What is the new behavior?

The `slice` pipe is now properly typed, so Ivy and `fullTemplateTypeCheck` enabled will catch errors inside an `ngFor` using a slice.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

Technically this changes the API, as it was previously possible to (wrongly) call `slice.transform(14, 1);` which still throws at runtime but is now a compile time error.

## Other information

@alxhub as we talked about it on Slack

2019-04-26 20:55 UTC, alfaproject commented on packages/common/test/pipes/slice_pipe_spec.ts
> +         () => { expect(() => pipe.transform({} as string, 0)).toThrow(); });
`as any` would be less weird

2019-04-27 06:47 UTC, trotyl commented on packages/common/src/pipes/slice_pipe.ts
> +  transform<T>(value: T[], start: number, end?: number): T[];
I guess it should also accept `ReadonlyArray<T>`?

2019-04-27 07:01 UTC, cexbrayat commented on packages/common/src/pipes/slice_pipe.ts
> +  transform<T>(value: T[], start: number, end?: number): T[];
Good point. I don't know if it's best to have another overload, or if `transform<T, A extends ReadonlyArray<T>>(value: A, start: number, end?: number): A;` is enough...

2019-04-29 05:54 UTC, IgorMinar commented
if this PR presubmits without any failures in google3 which would confirm the theory that this is not a de facto breaking change then I'd be fine merging this change into the 8.0.x branch.

2019-05-07 22:13 UTC, kara approved these changes
LGTM. Running presubmit...

2019-05-07 22:14 UTC, kara commented
[presubmit](https://test.corp.google.com/ui#id=OCL:247099804:BASE:247099851:1557267260804:71947898)

2019-05-07 23:01 UTC, kara commented
@IgorMinar Looks like this passed TAP in google. Are you good with merging this?

2019-05-07 23:55 UTC, alxhub requested changes

2019-05-07 23:55 UTC, alxhub commented on packages/common/src/pipes/slice_pipe.ts
> +  transform<T, A extends ReadonlyArray<T>>(value: A, start: number, end?: number): A;
I don't think this is technically correct. `ReadonlyArray<T>.slice()` returns a `T[]` not a `ReadonlyArray<T>`. `SlicePipe` should do the same - slicing a `ReadonlyArray<T>` results in a `T[]`.

2019-05-08 00:23 UTC, IgorMinar approved these changes
Ok. Lgtm

2019-05-08 06:55 UTC, trotyl commented on packages/common/src/pipes/slice_pipe.ts
> +  transform<T, A extends ReadonlyArray<T>>(value: A, start: number, end?: number): A;
Maybe it could treat `Array<T>` and `ReadonlyArray<T>` as two overloads.

2019-05-08 20:34 UTC, alxhub commented on packages/common/src/pipes/slice_pipe.ts
> +  transform<T, A extends ReadonlyArray<T>>(value: A, start: number, end?: number): A;
There's no real need - since `slice` makes a copy, it's okay to accept `ReadonlyArray` (a strictly narrower type than `Array`) and always return the mutable `Array`.

2019-05-13 06:04 UTC, cexbrayat commented on packages/common/src/pipes/slice_pipe.ts
> +  transform<T, A extends ReadonlyArray<T>>(value: A, start: number, end?: number): A;
@alxhub I updated the signature to accept `ReadonlyArray<T>` and return `Array<T>`

2019-05-17 18:49 UTC, alxhub approved these changes

2019-05-17 19:01 UTC, alxhub commented
[Presubmit](http://test/OCL:248760896:BASE:248760918:1558119061271:1d97fe37)

2019-05-17 21:23 UTC, closed without merging