refactor(ivy): move common integration tests to acceptance
angular/angular pull request #30213
Opened 2019-04-30 12:59 UTC by cexbrayat

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

This move common integration tests to `acceptance`.

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-05-06 17:21 UTC, benlesh requested changes
Overall, I think we need to remove the use of `toContain` entirely, because of the mistakes it can allow.

```ts
expect('this is incorrect text, lol').toContain('correct text'): // passes :)
```

- Remove the use of `ViewChildren`
- Rely on `fixture.debugElement.queryAll` to find the `li` tags and map out their textContent, etc.

2019-05-06 17:21 UTC, benlesh commented on packages/core/test/acceptance/acceptance_utils.ts
> +export function initWithTemplate<T>(compType: Type<T>, template: string) {
It feels like we already have so many of these utility functions throughout our tests and they add more confusion than they help when it comes to new contributors.

External folks are going to use these acceptance tests as a how-to at some level, and I think we should just use `TestBed.createComponent` in each test in the same manner we describe in our docs. 

However, perhaps at some point we want to introduce a `TestBed.createFromTemplate` feature for users.

2019-05-06 17:21 UTC, benlesh commented on packages/core/test/acceptance/common_integration_spec.ts
> +          '<ul><li *ngFor="let item of items; index as index; count as count">{{index}} of {{count}}: {{item}}</li></ul>');
I recommend we change the names here `index as idx`, etc... to ensure that we don't make a mistake with the internals where `index as foo` isn't honoring `foo`, but instead honoring `index`. (In other words, what's the point of doing `x as x` if we're not even changing the name?)

2019-05-06 17:21 UTC, benlesh commented on packages/core/test/acceptance/common_integration_spec.ts
> +      expect(fixture.nativeElement.innerHTML).toContain('<li>first</li><li>second</li>');
`toContain` probably isn't what we want.

`<ul><li>first</li><li>second</li><li>third</li></ul>` still "contains" `<li>first</li><li>second</li>`.

We're probably better off using `debugElement` to query the `li` tags out and asserting their contents:

```ts
let listItems = fixture.debugElement.queryAll(By.css('li'));
expect(listItems.map(li => li.nativeElement.textContent)).toEqual(['first', 'second']));
```

We'll need to change this throughout this PR.

2019-05-06 17:21 UTC, benlesh commented on packages/core/test/acceptance/common_integration_spec.ts
> +      const children = fixture.componentInstance.children.toArray();
Use `fixture.debugElement.queryAll` instead of adding `@ViewChildren` to the component. For better or worse, this is an example to external users of how to test their components, and we don't want them adding unnecessary run-time implications to their components in order to facilitate testing.

2019-05-07 09:11 UTC, cexbrayat commented on packages/core/test/acceptance/acceptance_utils.ts
> +export function initWithTemplate<T>(compType: Type<T>, template: string) {
No problem, I removed the commit that extracted the function.

2019-05-07 09:16 UTC, cexbrayat commented on packages/core/test/acceptance/common_integration_spec.ts
> +      expect(fixture.nativeElement.innerHTML).toContain('<li>first</li><li>second</li>');
You're right, I reworked it throughout the PR 👍 . I went with `fixture.nativeElement.querySelectorAll('li')` instead because `debugElement.queryAll` does not always honor the DOM order, so your example would fail in certain cases.

2019-05-07 09:33 UTC, cexbrayat commented
@benlesh I added a few fixup commits with your feedback.

2019-05-08 00:57 UTC, kara requested changes
Mostly looks good, a few comments below

2019-05-08 00:57 UTC, kara commented on packages/core/test/acceptance/common_integration_spec.ts
> +      ]);
I'm not sure this test is quite as strong as the original test. We're testing that there are list items and that there are spans, but we're not testing that the spans are inserted inside the list items properly. The following HTML would still pass this test now:

```
<li></li><li></li><span>1 - first - 2</span><span>2 - first - 2</span><span>3 - second - 2</span><span>4 - second - 2</span>
```

Can you update the test so the above would not pass?

2019-05-08 00:57 UTC, kara commented on packages/core/test/acceptance/common_integration_spec.ts
> +      expect(elements[19].textContent).toBe('4.H.G.F.E.D.C.B.A.App');
The old test confirmed that the span tags were in the correct nesting order in the DOM, whereas here we are just checking the text content. e.g. the following incorrect output would still pass:

```
<span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span>1.h.g.f.e.d.c.b.a.App</span>... etc
```

Can we switch to checking the HTML more directly to avoid this issue?

2019-05-08 01:00 UTC, kara commented
@cexbrayat Also can you squash your commits and change commit message to:

```test(ivy): move common integration tests to acceptance```

2019-05-13 12:01 UTC, cexbrayat commented
@kara I squashed the commits as requested and adressed your feedback in a fixup commit: up for review.

2019-05-13 21:43 UTC, kara approved these changes
LGTM

2019-05-13 21:46 UTC, benlesh approved these changes

2019-05-14 18:39 UTC, closed without merging