docs: fix naming miss and improve with anchor reference
angular/angular pull request #30225
Opened 2019-05-01 12:26 UTC by chigix

Signed-off-by: Richard Lea <chigix@zoho.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Only a few tweak in documentation friendlyness without any relation to feature definition.

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-05-01 12:29 UTC, chigix commented
@googlebot  I signed it!

2019-05-06 12:40 UTC, mary-poppins commented
You can preview 8edb5ae at https://pr30225-8edb5ae.ngbuilds.io/.

2019-05-06 12:47 UTC, brandonroberts requested changes
Add `in router guide` to git commit message

2019-05-06 12:47 UTC, brandonroberts commented on aio/content/guide/router.md
> +each time you selected a different hero by visiting the list component previously.
```suggestion
each time you selected a different hero from the list of heroes.
```

2019-05-06 16:59 UTC, mary-poppins commented
You can preview dd8c5df at https://pr30225-dd8c5df.ngbuilds.io/.

2019-05-06 17:39 UTC, brandonroberts approved these changes

2019-05-06 17:44 UTC, mary-poppins commented
You can preview ecb5a03 at https://pr30225-ecb5a03.ngbuilds.io/.

2019-05-06 18:49 UTC, closed without merging