fix(ivy): align NgModule registration timing with ViewEngine
angular/angular pull request #30244
Opened 2019-05-02 16:18 UTC by crisbeto

Currently in Ivy `NgModule` registration happens when the class is declared, however this is inconsistent with ViewEngine and requires extra generated code. These changes remove the generated code for `registerModuleFactory`, pass the id through to the `ngModuleDef` and do the module registration inside `NgModuleFactory.create`.

This PR resolves FW-1285.

2019-05-06 16:03 UTC, mhevery approved these changes
`@angular/core` LGTM for the compiler @alxhub should approve.

2019-05-06 16:10 UTC, alxhub requested changes

2019-05-06 16:10 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts
> +    let id: string|DynamicValue|null = null;
I'm actually in favor of not attempting to interpret this value at all, and just passing it through as a `WrappedNodeExpr`, like before. The compiler doesn't need to understand this value.

2019-05-06 16:10 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts
> +  id: string|DynamicValue|null;
Per below, let's keep this as `Expression`.

2019-05-06 16:10 UTC, alxhub commented on packages/compiler/src/jit_compiler_facade.ts
> +      id: facade.id || null,
We can wrap `facade.id` in a `WrappedNodeExpr` here.

2019-05-06 23:26 UTC, crisbeto commented
@alxhub It's been reworked based on the feedback.

2019-05-07 00:11 UTC, alxhub approved these changes
One comment, otherwise LGTM!

2019-05-07 00:11 UTC, alxhub commented on packages/compiler/src/compiler_facade_interface.ts
> +  id: any;
It can remain a `string` here :)

2019-05-07 01:33 UTC, kara commented
[presubmit](https://tap.corp.google.com/ui#id=OCL:246937836:BASE:246937916:1557192817977:30c936af)

2019-05-07 05:28 UTC, kara commented
This is failing Google presubmit because of a cyclical dependency:

```
angular2/rc/packages/core/src/linker/ng_module_factory_loader.ts -> 
angular2/rc/packages/core/public_api.ts -> angular2/rc/packages/core/src/core.ts -> 
angular2/rc/packages/core/src/metadata.ts -> angular2/rc/packages/core/src/metadata/directives.ts -> 
angular2/rc/packages/core/src/render3/jit/directive.ts -> 
angular2/rc/packages/core/src/render3/jit/environment.ts -> 
angular2/rc/packages/core/src/render3/index.ts -> 
angular2/rc/packages/core/src/render3/ng_module_ref.ts -> 
angular2/rc/packages/core/src/linker/ng_module_factory_loader.ts
```

2019-05-07 16:15 UTC, alxhub commented
We can remove `registerNgModuleType` from `jit/environment.ts` as it's no longer generated by the compiler (also remove it from `r3_identifiers.ts`). That will break the circular dependency.

2019-05-07 20:15 UTC, crisbeto commented
Thank you for the pointer @alxhub! This is ready for another presubmit.

2019-05-07 20:34 UTC, kara commented
[presubmit](http://test/OCL:246937836:BASE:247080468:1557261253192:9d545fd0)

2019-05-07 21:58 UTC, kara commented
Still getting TAP failures:

```
/angular2/rc/packages/core/src/linker/ng_module_factory_loader.ts -> 
/angular2/rc/packages/core/public_api.ts -> 
/angular2/rc/packages/core/src/core.ts -> 
/angular2/rc/packages/core/src/metadata.ts -> 
/angular2/rc/packages/core/src/metadata/directives.ts -> 
/angular2/rc/packages/core/src/render3/jit/directive.ts -> 
/angular2/rc/packages/core/src/render3/jit/environment.ts -> 
/angular2/rc/packages/core/src/render3/index.ts -> 
/angular2/rc/packages/core/src/render3/ng_module_ref.ts -> 
/angular2/rc/packages/core/src/linker/ng_module_factory_loader.ts
```

2019-05-08 03:31 UTC, crisbeto commented
Moved some things around based on our discussion with @alxhub. Can you take another look? It's all in the second `fixup` commit.

2019-05-13 14:21 UTC, kara commented
[new presubmit](http://test/OCL:247929583:BASE:247929597:1557757256999:b9e10469)

2019-05-13 15:38 UTC, kara commented
merge assistance: change made to Ivy-specific API

2019-05-13 18:15 UTC, closed without merging