refactor(router): determine if a route (and its subtree) should be reattached until detached route retrieving
angular/angular pull request #30263
Opened 2019-05-04 18:33 UTC by HVND

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?
Determine if a route (and its subtree) should be reattached until detached route retrieving.

2020-08-04 23:01 UTC, atscott requested changes
Please update the commit message to describe what prompted this change. It doesn't appear to be just a "refactor" as it would change whether `retrieve` were called. Also, would this resolve #23162? If so, can you please add that as a note in the commit message as well?

2021-04-13 21:56 UTC, atscott approved these changes
Approving but since I went ahead and applied fixes to this PR it should be reviewed by someone else as well.

2021-04-13 21:56 UTC, atscott commented
[presubmit](http://test/OCL:368300294:BASE:368300335:1618350816404:c15cb978)

2021-04-13 22:06 UTC, AndrewKushnir approved these changes
The changes look good. I'm wondering if it's possible (and worthwhile) to add a test that would reproduce the original problem? It looks like the tests were updated to reflect the new behavior, should we also check that the `retrieve` function is never called in these scenarios?

2021-04-13 22:10 UTC, atscott commented
@AndrewKushnir -- Oops! I had done that but didn't add it to the commit. PTAL

2021-04-13 22:17 UTC, StevenLiekens commented
Regarding #23162

It seems like `routeReuseStrategy.shouldAttach` is still called for the initial navigation. I might just be misinterpreting the code, I haven't tested it. If so, is it possible/preferable to skip that test and go straight to the `createActivatedRoute` path for the initial navigation?

2021-04-13 22:23 UTC, AndrewKushnir approved these changes
@atscott LGTM 👍

2021-04-13 22:48 UTC, atscott commented
@StevenLiekens it may be possible but I'm wondering why it would be necessary. Shouldn't the `RouteReuseStrategy` implementation return `false` for `shouldAttach` on the initial navigation? I'm not completely familiar with this part of the router code and I'm wary of making changes beyond what I can determine to be safe. At least with the change as it is now, it can be supported by the existing implementation in the `activate_routes` code.

2021-04-14 07:51 UTC, StevenLiekens commented
> Shouldn't the `RouteReuseStrategy` implementation return `false` for `shouldAttach` on the initial navigation?

Yep, that's why I'm thinking the method shouldn't even be tested (you already know the answer). But it would only be a minor optimization so leaving it as-is seems completely reasonable.

2021-04-14 16:11 UTC, atscott commented
[global presubmit](https://test.corp.google.com/ui#id=OCL:368300294:BASE:368415676:1618416473314:2fe27f9f)
The initial presubmit brought up one test failure. The test assertion just needed to be updated and I don't believe it would affect the application functionality. Global presubmit should also run to verify there are no other failures.

2021-04-15 17:51 UTC, atscott commented
caretaker note: please merge and sync this one on its own. Global presubmit is green but it would still be good to do since this is a router change.

2021-04-15 18:33 UTC, closed without merging