fix(common): ignore question mark when parsing url with HttpParams
angular/angular pull request #30302
Opened 2019-05-07 18:16 UTC by goenning

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #28722

## What is the new behavior?

HttpParams will skip leading `?` during parse.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2019-05-07 18:18 UTC, goenning commented
I signed it!

2020-05-29 19:02 UTC, alxhub approved these changes

2020-05-29 19:03 UTC, alxhub requested changes
Please squash this down to a single commit, with a more detailed commit message which explains the bug, the spec, and the fix :)

2021-01-28 10:04 UTC, petebacondarwin commented
Closing due to lack of response and there is a new PR at #40610

2021-01-28 10:04 UTC, closed without merging