docs: add section to upgrade guide on using the unified location service
angular/angular pull request #30331
Opened 2019-05-08 14:15 UTC by brandonroberts

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

The `LocationUpgradeModule` provides a unified way of handling URL updates across AngularJS and Angular. This adds a section to upgrade guide describing the router unification and usage.

2019-05-08 14:23 UTC, mary-poppins commented
You can preview 90ee870 at https://pr30331-90ee870.ngbuilds.io/.

2019-05-08 15:03 UTC, mary-poppins commented
You can preview 2b10992 at https://pr30331-2b10992.ngbuilds.io/.

2019-05-08 16:16 UTC, mary-poppins commented
You can preview ad275eb at https://pr30331-ad275eb.ngbuilds.io/.

2019-05-08 18:27 UTC, gkalpak requested changes
A couple of suggestions:

- Commit message typo:
  _docs(docs-infra): add common/upgrade/http to API package sources_ --> _[...] common/upgrade [...]_

- The commit that changes the parameter names in golden files should be squashed with the one the changes the actual parameters imo.

2019-05-08 18:27 UTC, gkalpak commented on aio/content/guide/upgrade.md
> +To aid in your migration from AngularJS to Angular, a unified location service is provided to shift the routing responsibility previously handled by the [$location servce](https://docs.angularjs.org/
_servce_ --> _service_

2019-05-08 18:27 UTC, gkalpak commented on aio/content/guide/upgrade.md
> +AngularJS and Angular both have separate routers for configuration, handling navigation, encoding and decoding URLs, redirects, and interacting with browser APIs. When migrating from AngularJS to Ang
_your migrating_ --> _you are migrating_

2019-05-08 18:27 UTC, gkalpak commented on aio/content/guide/upgrade.md
> +The `LocationUpgradeModule.config()` method accepts a configuration object that allows you configure options including the `LocationStrategy` with the `useHash` property, and the URL prefix with `has
- _allows you configure_ --> _allows you to configure_ (?)
- _with \`hashPrefix\` property_ --> _with the \`hashPrefix\` property_

2019-05-09 13:26 UTC, mary-poppins commented
You can preview 66d3a40 at https://pr30331-66d3a40.ngbuilds.io/.

2019-05-14 19:14 UTC, jasonaden approved these changes

2019-05-15 15:29 UTC, brandonroberts commented
Caretaker note: This includes a change to public API change in addition to docs that should not impact g3. Please run presubmit.

2019-05-15 16:56 UTC, jbogarthyde reviewed
Here's a bit of organizational change, based on my first reading.
It's not clear to me if "Unified Location Service" IS the "option to run both routers". Is it a tool for configuring which tasks should be handled by the old location service, and which should be handled by the new router? If so, let's state that up front.
We should talk, then I'd like to take another look at this.

2019-05-15 16:56 UTC, jbogarthyde commented on aio/content/guide/upgrade.md
> +
In AngularJS, the [$location service](https://docs.angularjs.org/api/ng/service/$location) handles all routing configuration and navigation, encoding and decoding of URLS, redirects, and interactions with browser APIs. Angular uses a different router for all of these tasks.

When you migrate from AngularJS to Angular, you have the option of running both routers to handle navigating in different parts of your application. *(I don't understand what it means to "run both routers" - does it mean you choose one for some tasks and the other for other tasks? I'm not clear if the unified loc service is itself the way you choose what to use where*)

To help with this, Angular provides the `LocationUpgradeModule`, a  *unified location service* that shifts routing responsibilities from the AngularJS `$location service` to the Angular router.

To take advantage of new APIs, you need to move as much functionality as possible to the Angular router. 

To use...

2019-05-16 17:39 UTC, mary-poppins commented
You can preview 6433669 at https://pr30331-6433669.ngbuilds.io/.

2019-05-16 17:59 UTC, jbogarthyde requested changes
Typo

2019-05-16 17:59 UTC, jbogarthyde commented on aio/content/guide/upgrade.md
> +
Typo:  To help with...

2019-05-16 18:09 UTC, brandonroberts commented on aio/content/guide/upgrade.md
> +
Fixed

2019-05-16 18:14 UTC, mary-poppins commented
You can preview adb1cbb at https://pr30331-adb1cbb.ngbuilds.io/.

2019-05-16 18:17 UTC, jbogarthyde approved these changes
LGTM

2019-05-16 18:38 UTC, mary-poppins commented
You can preview 071225d at https://pr30331-071225d.ngbuilds.io/.

2019-05-16 19:01 UTC, closed without merging