Update Ivy preview page
angular/angular pull request #30355
Opened 2019-05-09 15:23 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Fix typo, add note on using `@next` rather than `@latest`
Placeholder for any addition info we would like to include in AIO for the preview

2019-05-09 15:32 UTC, mary-poppins commented
You can preview 80c4262 at https://pr30355-80c4262.ngbuilds.io/.

2019-05-09 15:33 UTC, filipesilva requested changes

2019-05-09 15:33 UTC, filipesilva commented on aio/content/guide/ivy.md
> +   The Ivy preview is available in the `@next` version of Angular 8, rather than `@latest`.
I don't understand what this means. At this point in time it `@angular/core@latest` happens to be 7, and `@angular/core@next` happens to be 8. But in a months time both will be 8.

Is this alert meant to be removed once Angular version 8 final is released?

2019-05-09 15:57 UTC, jbogarthyde commented on aio/content/guide/ivy.md
> +   The Ivy preview is available in the `@next` version of Angular 8, rather than `@latest`.
This page won't land until v8

2019-05-09 16:02 UTC, filipesilva commented on aio/content/guide/ivy.md
> +   The Ivy preview is available in the `@next` version of Angular 8, rather than `@latest`.
Ok, so this alert should go away once 8.1 lands, right?

2019-05-09 16:05 UTC, jbogarthyde commented on aio/content/guide/ivy.md
> +   The Ivy preview is available in the `@next` version of Angular 8, rather than `@latest`.
Right

2019-05-09 16:26 UTC, filipesilva approved these changes

2019-05-09 16:27 UTC, mary-poppins commented
You can preview a1ce030 at https://pr30355-a1ce030.ngbuilds.io/.

2019-05-10 16:01 UTC, mary-poppins commented
You can preview 036d9d1 at https://pr30355-036d9d1.ngbuilds.io/.

2019-05-10 16:06 UTC, mary-poppins commented
You can preview 5003bb4 at https://pr30355-5003bb4.ngbuilds.io/.

2019-05-14 16:00 UTC, mary-poppins commented
You can preview 5a4951e at https://pr30355-5a4951e.ngbuilds.io/.

2019-05-14 18:44 UTC, kara commented on aio/content/guide/ivy.md
> +   The Ivy preview is available in the `@angular/core@next` version of Angular (8.1.x), rather than `@angular/core@latest` (8.0.x).
This implies that the Ivy preview isn't available in latest, which might be confusing since it is available and just doesn't have all the bug fixes / improvements. Could we say something like:

> To preview Ivy, use the `@angular/core@next` version of Angular (8.1.x), rather than `@angular/core@latest` (8.0.x), as it contains all the latest bug fixes and improvements.

2019-05-14 19:19 UTC, closed without merging

2019-05-14 19:22 UTC, mary-poppins commented
You can preview 85bc1bf at https://pr30355-85bc1bf.ngbuilds.io/.

2019-05-14 19:23 UTC, mary-poppins commented
You can preview 179a27b at https://pr30355-179a27b.ngbuilds.io/.