test(ivy): pure function acceptance tests
angular/angular pull request #30406
Opened 2019-05-10 20:52 UTC by benlesh

- Moves tests related to the pureFunction instructions from render3 to acceptance tests
- Leaves behind one test for in-template javascript that is not supported syntax yet

2019-05-10 21:55 UTC, mhevery approved these changes

2019-05-10 22:17 UTC, kara requested changes
Looks good, few small things

2019-05-10 22:17 UTC, kara commented on packages/core/test/acceptance/pure_function_spec.ts
> +        imports: [CommonModule],
Why is CommonModule needed here? Seems like we can remove.

2019-05-10 22:17 UTC, kara commented on packages/core/test/acceptance/pure_function_spec.ts
> +      fixture.componentInstance.customName2 = 'George';
Seems like we probably don't need to set these again since they're set in `App`?

2019-05-10 22:17 UTC, kara commented on packages/core/test/render3/pure_function_spec.ts
> +  // the syntax is still unsupported.
The test is not really testing the inline views so much as the fact that pure functions work with for loops. Can we migrate it using *ngFor?  Otherwise we won't have working tests for this.

2019-05-13 15:03 UTC, kara approved these changes
LGTM

2019-05-13 17:57 UTC, closed without merging