refactor(router): make recognize synchronous to expose it later
angular/angular pull request #30410
Opened 2019-05-11 04:48 UTC by yelhouti

make recognize synchronous as suggested by @jasonaden in PR 15826.
This is better since it will allow to convert URLs to snapshot and use
metadata without the need for Observables

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

recognize is asynchronous as explained by @jasonaden in PR #15826.

Issue Number: #15826 

## What is the new behavior?
recognize is synchronous, this will allow to convert URLs to snapshot and use
metadata without the need for Observables

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2019-05-11 04:49 UTC, yelhouti commented
I signed it!

2019-05-17 01:13 UTC, yelhouti commented
@jasonaden I can close this, since as you can see in my other PR, even if recognize is synchronous it can't be used to retrieve a Snapshot without the use of follow redirect that is async.

2020-08-06 20:55 UTC, atscott requested changes
Hi @yelhouti, can you rebase this PR? I'm generally in favor of removing the `Observable` nature from `recognize` since it's not necessary.

2020-08-06 20:55 UTC, atscott commented on packages/router/src/recognize.ts
> -    } catch (e) {
Should this `try...catch` be moved to `operators/recognize.ts` to avoid unintentionally throwing errors that can't be handled by `catchError`?

You also removed the test for the error case below. Maybe add that back and use the `recognize` operator.

2021-01-05 20:44 UTC, closed without merging