test(ivy): add exhaustive inheritance tests
angular/angular pull request #30442
Opened 2019-05-13 22:05 UTC by benlesh

- Adds inheritance tests for many combinations of directive, component and bare class inheritance
- Adds tests that are failing in ivy, but should work, marks them with `xit` and a TODO.
- Removes render3 unit tests that cover the same things.

NOTE: There is a JIRA ticket filed for the tests marked with `xit`: https://angular-team.atlassian.net/browse/FW-1324

2019-05-14 15:06 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +          fixture.debugElement.query(By.directive(SubDirective)).componentInstance;
As @crisbeto pointed out `componentInstance` will only contain a reference to a _component_ while `SubDirective` is a directive. To get a directive instance you need to ask for it from an injector, something like:

`fixture.debugElement.query(By.directive(SubDirective)).injector.get(SubDirective);`

As a side note: I was always missing some kind of utility / API to do this simpler as the pattern is very common and quite wordy atm...

Could you please modify `xit`ed tests as suggested and see if those are still broken?

2019-05-14 15:06 UTC, pkozlowski-opensource requested changes
See https://github.com/angular/angular/pull/30442/files#r283849241

2019-05-14 15:32 UTC, crisbeto commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +          fixture.debugElement.query(By.directive(SubDirective)).componentInstance;
The way I usually deal with this is to have a `ViewChild` on the fixture component. It does depend on change detection running at least once though.

2019-05-14 15:35 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +          fixture.debugElement.query(By.directive(SubDirective)).componentInstance;
> The way I usually deal with this is to have a ViewChild on the fixture component. It does depend on change detection running at least once though.

Yeh, I'm not a huge fan of `ViewChild` queries here as IMO it is even more typing and requires CD as you've pointed out...

2019-05-14 15:49 UTC, benlesh commented
@pkozlowski-opensource sorry, that link isn't working for me for some reason. What's the review?

2019-05-14 15:59 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +          fixture.debugElement.query(By.directive(SubDirective)).componentInstance;
Haha... I think we need something more intuitive there.

2019-05-15 22:01 UTC, mhevery approved these changes

2019-05-15 22:03 UTC, benlesh commented
Caretaker: @pkozlowski-opensource's concerns were addressed, and @mhevery is a global approver.

2019-05-16 12:10 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +      TestBed.overrideComponent(
nit: would be probably shorter / more obvious to write as ` TestBed.overrideTemplate(AppComp, '<div subDir [someInput]="1"></div>')`?

Applies to this line and all the other places below

2019-05-16 12:15 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +      expect(log).toEqual(['on changes!']);
nit: as a sanity check I would have a separate test that asserts that:
* nothing is logged when there is no `ngOnChanges()` (otherwise all the tests can be made passing but pushing initial `'on changes!'` to the mock `log` that you are using;
* `ngOnChanges()` gets invoked when input changes. 

One such test would be more than enough. Sorry for being pedantic but I like to have those sanity checks in place to make sure that we are not missing any obvious things.

2019-05-16 12:20 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +    it('should inherit inputs', () => {
sounds like it should be a separate `describe` as we are "switching" from lifecycle hooks to inputs

2019-05-16 12:22 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +    it('should compose host bindings for styles', () => {
new `describe`?

2019-05-16 12:24 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +    it('should compose host bindings for styles', () => {
Would be also good to check with @matsko how to organise those tests so we are not duplicating them with styling

2019-05-16 12:24 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +    it('should inherit ContentChildren queries', () => {
new `describe`

2019-05-16 12:25 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +        // TODO(issue/24571): remove '!'.
I think that you can remove this TODO comment (queries need ! - check the issue )

2019-05-16 12:29 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +
If we want to cover all cases we should also add tests for `ViewChild` / `ContentChild`

2019-05-16 12:38 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +    it('should inherit inputs', () => {
would be great to add more sanity tests for inputs with the same name present in super and sub classes and with different:
* type
* alias

In those cases we've got a clear collision and we should be resolving somehow but I'm not sure what VE / ivy is doing atm. Same applies to outputs.

Could you please add tests for those cases (I'm not sure we need them for all the inheritance cases.

2019-05-16 12:42 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +        @HostBinding('title')
I haven't seen any test for host expressed as `host: {...}` . Also can't find any tests for "host listener". Could you please add those? Again, I don't think we need those tests for each and every inheritance case.

2019-05-16 12:48 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +
I would _love_ to see more interesting cases for queries, ex.:
*  super and sub classes have the _same_ field name but with different queries (ex.: view / children or child / children)
* super and sub classes have the same query type (ex. ViewChildren) but with different selectors - the question here is who "wins"
* super and sub classes have a field with the same name but one is annotated with a query and another with input / output / host etc. 

All those are error / corner cases but we should have them covered somehow.

2019-05-16 13:01 UTC, pkozlowski-opensource commented
@benlesh good efforts on tests here. I've left some comments but generally speaking I think that we've got 2 axis to cover here:
* various inheritance combinations;
* various inherited features.

From what I can see this PR is "various inheritance combinations" reach but a bit light on "various inherited features". Personally I would prefer to see more comprehensive tests for a single feature (I left notes for cases that were coming to my mind when I was going through the code) and then just sanity checks for various inheritance combinations. Otherwise I I feel like we are repeating same tests over and over again without going too deep into any particular area. I'm saying this since if I recall that @alxhub discovered several places where ivy and VE differ and I don't see this reflected in your tests.

Anyway, good tests here, but I think that we can improve by going deeper and scale back on duplication for each various inheritance combinations. WDYT?

2019-05-16 17:23 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +      TestBed.overrideComponent(
I am actually really against that sort of test writing. Tests should repeat themselves as much as possible, and have everything explicitly and concisely defined within the test block. Dry tests invite mistakes where another developer comes along and changes the shared testing functionality and could potentially break other tests in such a way that they still pass but are no longer valid. I was honestly uneasy even writing the lifecycle hooks inheritance tests the way I did.

Explicit, inline code, while verbose, is by its very nature _more_ readable than code relying on code that exists many lines away and/or relies on underlying magic.

2019-05-16 17:28 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +      expect(log).toEqual(['on changes!']);
I didn't write these tests. They were simply moved by reformatting. It's probably worth noting the desired changes, and we can add them in a followup PR.

2019-05-16 17:33 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +    it('should inherit inputs', () => {
I agree that we should add more tests. Can we do this in a follow up PR?

2019-05-16 17:36 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +    it('should compose host bindings for styles', () => {
A describe with a single test seems like unnecessary nesting.

I checked the styling tests when I was writing these, and I didn't see anything around inheritance. I don't think that duplicate tests are a problem, regardless.

2019-05-16 17:37 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +    it('should inherit ContentChildren queries', () => {
Sorry, I disagree. Nesting a single test in a describe doesn't provide additional value in this case.

2019-05-16 17:52 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +        @HostBinding('title')
I think it sounds important, but I'd like to add these in a follow up PR. Unfortunately, we'd probably want to add them for each inheritance case to be thorough.

2019-05-16 17:53 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +
I agree. But I think we should circle back and add those later.

2019-05-16 17:55 UTC, benlesh commented
@pkozlowski-opensource I agree that there are a lot more tests to add. This PR was just an improvement over the very small number of render3 tests we had, and was already a little out of scope to the point where I was a bit concerned I was taking time away from other important team goals.

We should probably catalog the ideas you have here for more tests and circle back to them in a separate PR. We definitely still have some dark spaces.

2019-05-16 18:05 UTC, pkozlowski-opensource approved these changes
> @pkozlowski-opensource I agree that there are a lot more tests to add. This PR was just an improvement over the very small number of render3 tests we had, and was already a little out of scope to the point where I was a bit concerned I was taking time away from other important team goals.
We should probably catalog the ideas you have here for more tests and circle back to them in a separate PR. We definitely still have some dark spaces.

I'm totally cool with adding more tests in a separate PR - I was enumerating all those case while reading code assuming that you are after exhaustive coverage. Also my comments about `describe` were assuming that you are going to add more tests.

LGTM as this PR clearly improves things but could you please create a JIRA issue with missing tests?

2019-05-16 18:47 UTC, closed without merging

2019-05-16 18:54 UTC, kara reviewed
@benlesh Can you do these in a follow-up PR? I wasn't done reviewing.

2019-05-16 18:54 UTC, kara commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +      TestBed.overrideComponent(
I gotta say I'm with Pawel on this one. I don't think adding the `new Component` invocation actually makes things clearer. I think it's confusing and doesn't actually align with how people write tests in the wild.

2019-05-16 18:54 UTC, kara commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +      expect(log).toEqual(['on changes!']);
Can you please add a TODO for this?

2019-05-16 18:54 UTC, kara commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +
Add a TODO here?

2019-05-16 18:54 UTC, kara commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +
Can you add a TODO?

2019-05-16 20:01 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +      TestBed.overrideComponent(
Discussed offline: There was some confusion here. :)

The tests above were pre-existing and the diff made it look like I added new ones. I was confused about what was being asked, and everyone else was probably equally confused by my response.  Here is a PR that is attempting to address that issue: https://github.com/angular/angular/pull/30522

2019-05-16 20:46 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +    it('should inherit inputs', () => {
TODOs added in #30522

2019-05-16 20:47 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +    it('should inherit ContentChildren queries', () => {
describe blocks and TODOs added in #30522

2019-05-16 20:47 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +    it('should compose host bindings for styles', () => {
describe blocks and TODOs added in #30522

2019-05-16 20:47 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +
TODOs added in #30522

2019-05-16 20:47 UTC, benlesh commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +
TODOs added in #30522

2019-05-16 20:48 UTC, benlesh commented
Follow up PR is here #30522