test(ivy): port TemplateRef tests over to acceptance tests
angular/angular pull request #30443
Opened 2019-05-13 23:25 UTC by benlesh

- Moves template ref tests from render3 unit tests to acceptance tests.
- Marks tests testing ivy specific changes as `onlyInIvy`.
- Deletes old render3 unit tests that are no longer necessary

2019-05-14 15:43 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/template_ref_spec.ts
> +    onlyInIvy('Ivy will get root nodes from containers in embedded views')
The way I remember it and reading a comment here this test should have the results ivy and VE - the comment is saying that VE is not descending into sub-views and this is what we are asserting in this test.

Was this test failing in VE? If so, why?

2019-05-14 15:46 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/template_ref_spec.ts
> +      expect(embeddedView.rootNodes[1].nodeType).toBe(3);  // a text node
Nit: I wonder if it would make sense to have an enum for nodes types: https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType ?

2019-05-14 15:47 UTC, pkozlowski-opensource requested changes
My understanding is that we shouldn't have `onlyInIvy` here: https://github.com/angular/angular/pull/30443/files#diff-96a437ab2b6a8ea3a3bf704d7e6fbeccR118

2019-05-14 19:57 UTC, benlesh commented on packages/core/test/acceptance/template_ref_spec.ts
> +    onlyInIvy('Ivy will get root nodes from containers in embedded views')
Yes, it was failing in VE because it was returning two root nodes instead of just the one. Both are `<!---->`. I'm not sure if this is expected behavior.

2019-05-14 21:36 UTC, benlesh commented on packages/core/test/acceptance/template_ref_spec.ts
> +    onlyInIvy('Ivy will get root nodes from containers in embedded views')
I've updated the test to account for the VE behavior and added a comment around the issue. Given the tests directly above, it seems like the differences between VE and Ivy here are now well documented.

2019-05-14 23:18 UTC, kara approved these changes
LGTM apart from typo

2019-05-14 23:18 UTC, kara commented on packages/core/test/acceptance/template_ref_spec.ts
> +     * Returning a comment node for a template ref with no nodes is wrong is fixed in Ivy.
```suggestion
     * Returning a comment node for a template ref with no nodes is wrong and is fixed in Ivy.
```

2019-05-15 18:28 UTC, pkozlowski-opensource approved these changes
Thnx for adding the "SUFFIX" trick to have a test for both VE and ivy. With others tests in this PR we are good.

LGTM

2019-05-15 21:12 UTC, closed without merging