feat(ivy): static evaluation of TypeScript's `__spread` helper
angular/angular pull request #30492
Opened 2019-05-15 19:12 UTC by JoostK

The usage of array spread syntax in source code may be downleveled to a
call to TypeScript's `__spread` helper function from `tslib`, depending
on the options `downlevelIteration` and `emitHelpers`. This proves
problematic for ngcc when it is processing ES5 formats, as the static
evaluator won't be able to interpret those calls.

A custom foreign function resolver is not sufficient in this case, as
`tslib` may be emitted into the library code itself. In that case, a
helper function can be resolved to an actual function with body, such
that it won't be considered as foreign function. Instead, a reflection
host can now indicate that the definition of a function corresponds with
a certain TypeScript helper, such that it becomes statically evaluable
in ngtsc.

Resolves #30299

2019-05-15 19:23 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/reflection/src/host.ts
> +  getDefinitionOfFunction(fn: ts.Node): FunctionDefinition|TsHelperFn|null;
I had to loosen the type requirements, as `__spread` may be a variable declaration that was not previously allowed. Because of this, several usage sites had to be updated. We can avoid these changes if desired by introducing something like `ReflectionHost.identifyHelper(node: ts.Node): TsHelperFn|null` that is called and handled accordingly before reaching out to `getDefinitionOfFunction`.

2019-05-15 19:23 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/partial_evaluator/test/evaluator_spec.ts
> +  it('should evaluate TypeScript __spread helper', () => {
We want to limit the availability of this feature to ngcc only, so should this go in ngcc's test suite, perhaps?

2019-05-15 20:34 UTC, JoostK commented
Confirmed that this change now allows `ngx-markdown` to be processed successfully! @Aw3same

2019-05-15 21:07 UTC, petebacondarwin reviewed
How about instead of adding a new type (`TsHelperFn`) we add a new constant `TsSpreadFn`, which is a specific instance of `FunctionDefinition` that happens to have a `null` body…?
I think this could make the code that works with FunctionDefinitions simpler.

Also I think in the `StaticInterpreter` we should not be hard coding the handling of spread. Instead we should add a new resolver, similar to the FFR, which can resolve TS helper functions.
Then you don’t need to have a specific unit test in the interpreter for spread.
Instead you could check that the resolver gets called when the interpreter hits a matching function definition.

2019-05-15 22:33 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/partial_evaluator/test/evaluator_spec.ts
> +  it('should evaluate TypeScript __spread helper', () => {
I actually don't mind having this test here. Conceptually, it's a part of the `partial_evaluator`, we just don't enable it in `ngtsc` itself.

2019-05-16 15:44 UTC, alxhub reviewed
I like the idea of a `FunctionDefinition` with `null` body, but with a `builtin: TsBuiltinFn` field, where `TsBuiltinFn` is an enum.

I do think we _want_ tests in `partial_evaluator` for each of the TS builtin functions. It's a function of the evaluator to evaluate them, and there's only one way to do so correctly.

2019-05-19 07:23 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
> +    }
I would be a bit happier if we did not have this `if` statement and handler code here... If we were to need to handle more helper functions then we would get a proliferation of `if`s (or a `switch`) and handlers in this function.

How about this... Instead of `fn.helper` being an `enum` which we have to switch over, we have a `fn.resolver?()` handler, which we call polymorphically if it exists to evaluate the function. Then the reflection host is responsible for attaching the correct handler when it identifies a helper function.

2019-05-19 07:24 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
> +    }
Also the `evaluateTsSpreadHelper` could be moved to `ngcc` since `ngtsc` does not need to know about this implementation. Perhaps renamed to `evaluateInlineTsSpreadHelper`?

2019-05-19 07:26 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/partial_evaluator/test/evaluator_spec.ts
> +  it('should evaluate TypeScript __spread helper', () => {
I believe that the implementation of the inline `__spread` evaluation should be moved to ngcc and tested there.

In this file we should be testing that we can handle such "special" functions by calling an appropriate `fn.resolve()` method. See https://github.com/angular/angular/pull/30492/files#r285366893

2019-05-19 07:27 UTC, petebacondarwin requested changes
Can we discuss making the change to the architecture I suggest above?

2019-05-19 09:02 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
> +    }
We could clean up this `if` a bit as follows:

```typescript
if (fn.helper !== null) {
  const args = this.evaluateFunctionArguments(node, context);
  return evaluateTsHelperInline(args.helper, args);
}
```
with `evaluateTsHelperInline` being implemented in the `ts_helpers.ts` file.

That approach however does not address your concern regarding where this code has to be implemented. I don't think the  `fn.resolver?()` approach is the way to go, as it mixes introspection (`ReflectionHost`) with evaluation (`StaticInterpreter`) which causes circular deps down the line. If we do want to move over the implementations to ngcc itself, I think we need something similar to _foreign function resolver_ (i.e. a function that can be passed into `PartialEvaluator`'s constructor from ngcc).

2019-05-19 10:48 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
> +    }
I could live with a FFR style approach, which would satisfy my desire for ngtsc not to need to know about the implementation.

I still believe that the `StaticInterpreter` does not need to be aware of the existence of `__spread` as a helper function. It should just know that a function call is "special" (currently provided by the call to `getDefinitionOfFunction()`) and then a way to get the expected result of that call given the arguments that it has already evaluated (either a FFR approach of a ReflectionHost approach would work for me here).

I don't think that the evaluation of the helper (e.g. `__spread`) should be making any further requests to the `StaticInterpreter`. It should be possible to evaluate such a function purely based on the arguments provided. In which case, I don't see why there would be any circular dependency concern.

2019-06-03 19:22 UTC, alxhub approved these changes

2019-06-03 19:22 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
> +    }
I actually favor the current design:

1. The responsibility for evaluating the function lives in `partial_evaluator` - I think this is as it should be.

`__spread` is not a "normal" foreign function. It's a special code structure that has a specific interpretation. Due to the peculiarities of different bundling formats, the `partial_evaluator` doesn't know how to recognize this structure, but it's the right place to define how it's evaluated.

I'm not so worried about the fact that `__spread` is "ngcc-only". To me, the `partial_evaluator` is just that - a utility for statically evaluating code. It has no special knowledge of code formats (that's provided by the `ReflectionHost`) but it _does_ know how to run special builtin functions it might encounter (e.g. `Array.concat`, `Array.slice`, etc). It makes sense to me that the `tslib` helper functions would be supported builtins.

2. The `ReflectionHost` identifies the `__spread` function as special.

This aspect of the design I also like. It's the `ReflectionHost`'s job to translate various code structures into a standard format for the evaluator. Since `__spread` looks different in different formats, it's natural that the `ReflectionHost` would be responsible for recognizing it and for communicating that a given function is actually an instance of a builtin.

3. `__spread` is not FFR.

To me this is a very different situation than the "foreign function" problem. These functions aren't foreign, they're simply different expressions of a built-in language operation (`{...foo}`). In that sense, it's the `ReflectionHost`'s job to recognize different syntax expressing the same concepts, and it's the `partial_evaluator`'s job to know how to evaluate them.

2019-06-03 19:25 UTC, alxhub commented
[Presubmit](http://test/OCL:251284253:BASE:251284271:1559589794940:4e8bedac)

2019-06-03 19:37 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
> +    }
Just for the record, I was not suggesting that `__spread` was a FFR, I was just saying that there should be a similar mechanism where the reflector is responsible for identifying "special" operations and providing the evaluation of them, rather than hard coding the fact that `__spread` is special into the `StaticInterpreter`.

But I am not going to fall on my sword over this one :-)

2019-06-07 20:26 UTC, petebacondarwin approved these changes

2019-06-10 23:55 UTC, closed without merging