Attribute instructions
angular/angular pull request #30503
Opened 2019-05-16 03:27 UTC by benlesh

Adds new attribute instructions to ivy based on [this design doc](https://hackmd.io/s/B1ebVfMUE)

Please see individual commits for details

- Δattribute
- ΔattributeInterpolate
- ΔattributeInterpolate1
- ΔattributeInterpolate2
- ΔattributeInterpolate3
- ΔattributeInterpolate4
- ΔattributeInterpolate5
- ΔattributeInterpolate6
- ΔattributeInterpolate7
- ΔattributeInterpolate8
- ΔattributeInterpolateV

2019-05-16 18:54 UTC, mhevery approved these changes

2019-05-16 18:54 UTC, mhevery commented on packages/core/src/render3/instructions/attribute.ts
> +  return ΔelementAttribute(index, name, Δbind(value), sanitizer, namespace);
We discussed that we should not implement innstructions in term of other instructions. Is there are reason why we are doing it here?

2019-05-16 19:57 UTC, benlesh commented on packages/core/src/render3/instructions/attribute.ts
> +  return ΔelementAttribute(index, name, Δbind(value), sanitizer, namespace);
It's just an incremental change. There will be follow up work to remove instructions, and convert some instructions into shared functions and stop exporting them.

2019-05-16 19:57 UTC, benlesh commented on packages/core/src/render3/instructions/attribute.ts
> +  return ΔelementAttribute(index, name, Δbind(value), sanitizer, namespace);
(Resolving, because we discussed this in Slack)

2019-05-16 20:02 UTC, benlesh commented
[presubmit](http://test/OCL:248583242:BASE:248583266:1558036731981:5e273691)

2019-05-16 20:47 UTC, alxhub approved these changes
👍 for the compiler.

2019-05-16 21:43 UTC, kara requested changes

2019-05-16 21:43 UTC, kara commented on packages/core/src/render3/instructions/attribute.ts
> +  return ΔelementAttribute(index, name, Δbind(value), sanitizer, namespace);
If this is the case, can we please add TODOs linking to a JIRA here? We shouldn't just commit code that ignores the rules we agreed on without explaining why.

2019-05-16 21:43 UTC, kara commented on packages/core/src/render3/instructions/attribute_interpolation.ts
> + * Used when the value passed to a property has 1 interpolated value in it, an no additional text
```suggestion
 * Used when the value passed to a property has 1 interpolated value in it, and no additional text
```

2019-05-16 21:43 UTC, kara commented on packages/core/src/render3/instructions/attribute_interpolation.ts
> +  ΔattributeInterpolate1(attrName, '', v0, '', sanitizer);
These need TODOs as well

2019-05-16 21:43 UTC, kara commented on packages/core/src/render3/instructions/attribute_interpolation.ts
> + * ΔattributeInterpolate('title', v0);
Why wouldn't we generate `attribute()` in this case? Seems like we can remove this instruction since it's always a string anyway.

2019-05-17 18:40 UTC, benlesh commented
[presubmit here](http://test/OCL:248583242:BASE:248754839:1558117150117:b9998480)

2019-05-17 19:03 UTC, kara commented on packages/core/src/render3/instructions/attribute_interpolation.ts
> +  // TODO(FW-1340): Refactor to remove the use of other instructions here.
Is there any reason why we only went up to `attributeInterpolate5` with the TODOs? Seems weird to do half

2019-05-20 17:12 UTC, benlesh commented on packages/core/src/render3/instructions/attribute_interpolation.ts
> +  // TODO(FW-1340): Refactor to remove the use of other instructions here.
:grimacing: I missed somehow... no other reason. Sorry about that.

2019-05-21 02:29 UTC, kara approved these changes
LGTM

Note: seems like this needs a big rebase after the delta prefix PR and an Ivy presubmit. This does not need "public API" approval from Igor since it is Ivy instructions only.

2019-05-22 15:47 UTC, benlesh commented
[new presubmit](http://test/OCL:248583242:BASE:249455587:1558539930797:3d8fc9d0)

2019-05-22 23:32 UTC, closed without merging

2019-05-23 16:37 UTC, kara commented
@benlesh Can you link the Ivy presubmit for this? I don't see one linked.