fix(core): remove deprecated annotation for TestBed.get
angular/angular pull request #30514
Opened 2019-05-16 15:41 UTC by cexbrayat

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #29905 and FW-1336

## What is the new behavior?

PR #29290 introduced a new `TestBed.get` signature and deprecated the existing one.
This raises a lot of TSLint deprecation warnings in projects using a strict TS config (see #29905 for context), so we are temporarily removing the `@deprecated` annotation in favor of a plain text warning until we properly fix it.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-05-17 18:41 UTC, kara requested changes
Minor nit

2019-05-17 18:41 UTC, kara commented on packages/core/testing/src/test_bed.ts
> +   * deprecated from v8.0.0 use Type<T> or InjectionToken<T>
Can we add a small note here about why we aren't using the official @deprecated? I could see someone "fixing" it later by accident.

```suggestion
// TODO: switch back to official deprecation marker once TSLint issue is resolved
/**
 * deprecated from v8.0.0 use Type<T> or InjectionToken<T>
```

2019-05-17 19:00 UTC, kara approved these changes
LGTM, though we should still get a public API review from @IgorMinar

2019-05-18 00:58 UTC, IgorMinar approved these changes
I also suggest that you rename the commit message to "fix(core): temporarily remove @deprecated jsdoc tag for a TextBed.get overload"

2019-05-18 00:58 UTC, IgorMinar commented on packages/core/testing/src/test_bed.ts
> +   * deprecated from v8.0.0 use Type<T> or InjectionToken<T>
can you also make a note in the visible part of the doc, that links to the tslint issue and explains that the symbol is not deprecated via `@deprecated` jsdoc because it renders all overloads as deprecated in tslint and not just the one that we are targeting.

2019-05-18 08:59 UTC, cexbrayat commented
@IgorMinar I updated the doc to mention the TSLint issue according to your feedback and changed the commit message.

2019-05-20 17:52 UTC, IgorMinar approved these changes

2019-05-20 17:52 UTC, IgorMinar commented
merge-assistance: ci is flaky

2019-05-21 20:13 UTC, closed without merging