WIP: test coalesce event
angular/angular pull request #30533
Opened 2019-05-17 11:51 UTC by JiaLiPassion

Pure test PR, just for some POC.

2019-05-31 03:15 UTC, mhevery requested changes
Minor comments.

2019-05-31 03:15 UTC, mhevery commented on packages/core/src/zone/ng_zone.ts
> +  get hasPendingMicrotasks(): boolean {
Let's not use getters if we don't have to. They bloat the code. Maybe just a function?

2019-05-31 03:15 UTC, mhevery commented on packages/core/src/zone/ng_zone.ts
> +  readonly hasPendingZoneMicrotasks: boolean = false;
Why did you add `Zone` to the title? I think it just makes the code bigger, without really adding to the readability, since there are no other kinds of `Microtasks`

2019-05-31 03:15 UTC, mhevery commented on packages/core/src/zone/ng_zone.ts
> +  readonly hasPendingZoneMicrotasks: boolean = false;
Ohh I see because you have a getter later. Maybe just prefix it with `_`?

2019-05-31 03:15 UTC, mhevery commented on packages/core/src/zone/ng_zone.ts
> +  get hasPendingMicrotasks(): boolean {
What do you think about renaming it to `shouldRunChangeDetection`?

2019-05-31 03:15 UTC, mhevery commented on packages/core/src/zone/ng_zone.ts
> +    forkInnerZoneWithAngularBehavior(self, shouldCoalesceEventChangeDetection);
`shouldCoalesceEventChangeDetection` is available on `self` I don't think you need to pass it again here.

2019-05-31 03:15 UTC, mhevery commented on packages/core/src/zone/ng_zone.ts
> +const _global: any = typeof window !== 'undefined' ?
import global from `core/src/util`

2019-05-31 03:15 UTC, mhevery commented on packages/core/src/zone/ng_zone.ts
> +function initNativeRequestAnimationFrame() {
maybe pull this code out to `core/src/raf`???

2019-05-31 03:15 UTC, mhevery commented on packages/core/src/zone/ng_zone.ts
> +    // option2: just return
Just return, I don't think there is a value in canceling it.

2019-05-31 03:15 UTC, mhevery commented on packages/core/src/application_ref.ts
> +  ngZoneEventCoalescing?: boolean;
Needs public API docs here.

2019-05-31 03:16 UTC, mhevery commented
Need to run `bazel run //tools/public_api_guard:core_api.accept`

2019-05-31 15:07 UTC, JiaLiPassion commented on packages/core/src/zone/ng_zone.ts
> +  get hasPendingMicrotasks(): boolean {
@mhevery, I just thought that if we change the name of  `hasPendingMicroTasks` or change it to a `function`, that will be a breaking change, because this property is a `public API`.

And `shouldRunChangeDetection` is more meaningful name, but in `checkStable`, 
```
function checkStable(zone: NgZonePrivate) {
  if (zone._nesting == 0 && !zone.hasPendingMicrotasks && !zone.isStable) {
```
we will also check `zone._nesting and zone.isStable`, so we don't only use this `hasPendingMicroTask` to decide to run `ChangeDetection` or not. So maybe `hasPendingMicroTask` is still the good name?

2019-05-31 15:19 UTC, JiaLiPassion commented on packages/core/src/zone/ng_zone.ts
> +  readonly hasPendingZoneMicrotasks: boolean = false;
You are right, I updated the name with `_`.

2019-05-31 15:19 UTC, JiaLiPassion commented on packages/core/src/zone/ng_zone.ts
> +    forkInnerZoneWithAngularBehavior(self, shouldCoalesceEventChangeDetection);
yes, you are right, thanks!

2019-05-31 15:21 UTC, JiaLiPassion commented on packages/core/src/zone/ng_zone.ts
> +const _global: any = typeof window !== 'undefined' ?
got it, thanks!

2019-05-31 15:26 UTC, JiaLiPassion commented on packages/core/src/zone/ng_zone.ts
> +function initNativeRequestAnimationFrame() {
Yes, you are right, I have moved it to `core/src/raf`.

2019-05-31 15:27 UTC, JiaLiPassion commented on packages/core/src/zone/ng_zone.ts
> +    // option2: just return
Got it!

2019-06-03 16:09 UTC, JiaLiPassion commented
@mhevery, I fixed several issues, now all tests passed, (expect the case of `integration file-size-limit`), I will continue to add test cases, could you run this version in `g3`? Thanks!

2019-06-04 20:23 UTC, mhevery commented on packages/core/src/zone/ng_zone.ts
> +  get hasPendingMicrotasks(): boolean {
I see, we don't want to break the public API

2019-06-04 20:30 UTC, mhevery commented
http://test/OCL:251502926:BASE:251502950:1559679912312:8b435b5c

2019-06-07 03:08 UTC, JiaLiPassion commented
Need wait https://github.com/angular/zone.js/pull/1239 to be merged. So the `integration` test can pass.

2019-09-06 23:27 UTC, mhevery commented
[presubmit](http://test/OCL:267696312:BASE:267696357:1567812428401:7d5138cd)

2019-09-17 19:07 UTC, mhevery requested changes

2019-09-17 19:07 UTC, mhevery commented on packages/core/src/application_ref.ts
> +  ngZoneEventCoalescing?: boolean;
can you add docs explaining what this does?

2019-09-17 19:07 UTC, mhevery commented on packages/core/src/util/raf.ts
> +initNativeRequestAnimationFrame();
I don't think we are allowed to have sideffects in imports. This will mess up the tree shaker.

2019-10-03 17:25 UTC, mhevery requested changes

2019-10-03 17:25 UTC, mhevery commented on packages/core/src/zone/ng_zone.ts
> +const {nativeRequestAnimationFrame} = initNativeRequestAnimationFrame();
it is not really `init` since you are returning things, I think it is more of `get`?

Also because you are assigning to global location, this function will not be tree shakable, which is not good. we should only call `initNativeRequestAnimationFrame` from places where we know we will be needing the value.

2019-10-03 17:31 UTC, mhevery commented
http://test/OCL:267696312:BASE:272690031:1570123702912:2a9165b6

2019-10-04 00:29 UTC, JiaLiPassion commented on packages/core/src/zone/ng_zone.ts
> +const {nativeRequestAnimationFrame} = initNativeRequestAnimationFrame();
Got it, I updated the PR, please check my understanding is correct or not. Thanks!

2019-10-05 06:15 UTC, JiaLiPassion commented
@mhevery, I have updated the PR, please review, thanks!

2019-10-16 17:12 UTC, mhevery approved these changes

2019-10-16 17:12 UTC, mhevery commented
Merge assistance: global approval

2019-10-17 16:51 UTC, matsko commented
@JiaLiPassion unfortunately this had to be reverted because it was causing failures inside of Google3. Please message me on slack so I can get this unstuck for you.

2019-10-19 04:38 UTC, JiaLiPassion commented
@matsko, I have updated the PR and now the API will not have any changes, and g3 should be ok, please review, thank you!

2019-10-19 11:14 UTC, devversion commented on packages/core/src/application_ref.ts
> +   * colesced and the change detection will be triggered multiple times.
```suggestion
   * coalesced and the change detection will be triggered multiple times.
```

2019-10-19 11:14 UTC, devversion commented on integration/side-effects/snapshots/core/esm5.js
> +var nativeRequestAnimationFrame = getNativeRequestAnimationFrame().nativeRequestAnimationFrame;
I just stumbled over this PR. Out of curiosity: is it intentional that we introduce a new side-effect global call here?

2019-10-19 11:48 UTC, JiaLiPassion commented on packages/core/src/application_ref.ts
> +   * colesced and the change detection will be triggered multiple times.
thanks for the review, updated.

2019-10-19 11:49 UTC, JiaLiPassion commented on integration/side-effects/snapshots/core/esm5.js
> +var nativeRequestAnimationFrame = getNativeRequestAnimationFrame().nativeRequestAnimationFrame;
you are right, I should not add a side-effect here, I just updated the PR to move the call inside ngZone initialize call.

2019-10-28 16:49 UTC, mhevery commented
[presubmit](http://test/OCL:277083057:BASE:277083167:1572281368843:dce210b)

2019-10-29 17:56 UTC, mhevery approved these changes

2019-11-05 00:07 UTC, mhevery commented
MERGE_ASSISTANCE: Please merge by itself as this is high risk.

2019-11-05 03:07 UTC, AndrewKushnir commented
Since this change is a high risk (as Misko mentioned), I've started a [Global VE presubmit](https://test.corp.google.com/OCL:278516469:BASE:278516693:1572923202791:9440852f) as well (and a [Blueprint one](https://test.corp.google.com/ui#id=OCL:278516469:BASE:278516521:1572923143890:31586181)).

2019-11-05 18:58 UTC, closed without merging

2019-11-05 19:01 UTC, atscott commented
This was merged to master only. @mhevery @JiaLiPassion is that good or did you also need this in the patch branch?

2019-11-07 00:31 UTC, naveedahmed1 commented
Should this provide any benefit on server, I mean in case of SSR/Universal?

2019-11-07 05:40 UTC, trotyl commented
> Should this provide any benefit on server, I mean in case of SSR/Universal?

There is little chance for DOM events to be triggered on server, unless you manually dispatch them.

2019-11-07 13:43 UTC, JiaLiPassion commented
@atscott, I am not sure about whether this need to be merged to `patch` branch, @mhevery , please confirm, thanks!