feat(ivy): in `ngDevMode` use named object literals and arrays for easier debugging/profiling
angular/angular pull request #30542
Opened 2019-05-17 16:56 UTC by mhevery

Ivy uses object literals for speed and size. These are very hard to debugging because all types are an array or object literals without any useful hints to the developer. Similarly when profiling memory consumption it is hard to tell which object is which and so it is hard to track down memory pressure. This change enables constructor names for the Ivy dat structures making the code base more approachable.  

![Screen Shot 2019-05-17 at 9 46 19 AM](https://user-images.githubusercontent.com/111951/57943710-94929d80-7889-11e9-9a32-1dd9bcf4248e.png)

2019-05-17 17:06 UTC, ocombe commented on packages/core/src/render3/instructions/debug.ts
> +export function makeNamedArray(name: string): typeof Array {
What do you think of `createNamedArray` instead of `makeNamedArray`?

2019-05-17 17:26 UTC, benlesh requested changes
This is really clever! Just one small thing to keep it "hidden" from the rest of the code.

2019-05-17 17:26 UTC, benlesh commented on packages/core/src/render3/instructions/debug.ts
> +    return Array;
the fall back could still decorate it. Then we'd still have _something_ to look at in platforms that didn't support `class` or extending Array.

2019-05-17 17:26 UTC, benlesh commented on packages/core/src/render3/instructions/debug.ts
> +    return (new Function('Array', `return class ${name} extends Array{}`))(Array);
You're going to want to add a `Symbol.species` here, if you don't want to effect the semantics

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/species]

```suggestion
    return (new Function('Array', `return class ${name} extends Array{ get [Symbol.species]() { return Array; } }`))(Array);
```

2019-05-17 17:31 UTC, mhevery commented on packages/core/src/render3/instructions/debug.ts
> +    return (new Function('Array', `return class ${name} extends Array{}`))(Array);
Cool I did not know such a thing existed, learned something new. 

I read the link and I think I specifically don't want this, since we do want to propagate the array type. Did you have something else in mind.

2019-05-17 17:34 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/debug.ts
> +  try {
If I understand things correctly `makeNamedArray` should be only called when `ngDevMode=true`. Could we add an assert that verifies that we never call it in the prod mode?

2019-05-17 17:35 UTC, mhevery commented on packages/core/src/render3/instructions/debug.ts
> +export function makeNamedArray(name: string): typeof Array {
Renamed to `createNamedArrayType`

2019-05-17 17:37 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +const TViewConstructor = class TView {
Could we move it to a separate file (ex. next to the `TView` interface? This file is quite big already...

2019-05-17 17:39 UTC, mhevery commented on packages/core/src/render3/instructions/debug.ts
> +  try {
Good idea, Added an assertion!

2019-05-17 17:40 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +const TViewConstructor = class TView {
Moved.

2019-05-17 17:47 UTC, alfaproject commented on packages/core/src/render3/instructions/shared.ts
> +}
Wouldn't creating the object literal as usual be enough and then just change the propotype to a dummy class?

```
const tView = {
  //...
};
if (ngDevMode) {
  Object.setPrototypeOf(tView, new (class TView {}));
}
return tView;
```

2019-05-17 17:54 UTC, jelbourn commented on packages/core/src/render3/instructions/debug.ts
> +
Add a file-level comment here that calls out that the code here is only for dev-mode and explains how that happens? Seems like there should also be something that enforces the `ngDevMode` gate (maybe a lint check, maybe a test)?

2019-05-17 17:54 UTC, jelbourn commented on packages/core/src/render3/instructions/shared.ts
> +let LVIEW_EMPTY: any[];  // can't initialize here or it will not be tree shaken, because `LView`
Should this be `unknown[]`?
(similar for other uses of `any`)

2019-05-17 17:54 UTC, jelbourn commented on packages/core/src/render3/instructions/shared.ts
> +const TViewConstructor = class TView {
Add description comment that explains why this is here?

2019-05-17 17:54 UTC, jelbourn commented on packages/core/src/render3/instructions/shared.ts
> +function cloneToLView(list: any[]): LView {
Add description comment that explains _why_ this function exists?
(here and for other clone functions)

2019-05-17 17:54 UTC, jelbourn commented on packages/core/src/render3/instructions/shared.ts
> +      public id: any,                    //
Should these be `unknown` instead of `any`?

2019-05-17 17:54 UTC, jelbourn commented on packages/core/src/render3/instructions/shared.ts
> +const TViewConstructor = class TView {
Would it make sense to move these constructs and the return values of `makeNamedArray` (here and elsewhere) into your newly added `debug.ts` so that it's clear they're for debugging purposes?

2019-05-17 17:57 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +}
Because that would create a slow array which has different perf characteristics and memory implications. Basically it would become a map with integer numbers as keys.

2019-05-17 18:10 UTC, mhevery commented on packages/core/src/render3/instructions/debug.ts
> +
added a test and comment.

2019-05-17 18:16 UTC, alfaproject commented on packages/core/src/render3/instructions/shared.ts
> +}
I mean, for the objects, so you don't need to replicate a class with the same shape

2019-05-17 18:16 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +let LVIEW_EMPTY: any[];  // can't initialize here or it will not be tree shaken, because `LView`
fixed

2019-05-17 18:17 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +function cloneToLView(list: any[]): LView {
fixed

2019-05-17 18:19 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +const TViewConstructor = class TView {
done.

2019-05-17 18:25 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +      public id: any,                    //
added proper types.

2019-05-17 18:25 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +const TViewConstructor = class TView {
Done.

2019-05-17 21:40 UTC, kara reviewed
Nice, I think named arrays / objects will be super useful for debugging! I do have some comments below re duplication that could lead to adding bugs in one mode or the other

2019-05-17 21:40 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> +      ];
As @pkozlowski-opensource mentioned in chat, I think duplicating the args here could potentially create bugs between dev and prod (e.g. we update a value in one of the lists and not the other). Could we create a wrapper function that calls LContainerArray with `apply()` so we can share the list between both modes? 


```ts
const lContainerValues = [hostNative, true, ...];
const lContainer =  ngDevMode ? createNamedArrayInstance(LContainerArray, lContainerValues)
                              : lContainerValues;
```

2019-05-17 21:40 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> +             viewIndex,                                                     //
Can we fill in the comments with prop names? Right now they aren't very useful as `// `

2019-05-17 21:40 UTC, kara commented on packages/core/src/render3/instructions/lview_debug.ts
> +      public id: number,                                     //
Nit: remove empty comments?

2019-05-17 21:44 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> +      ];
Update: Just saw your note about how this will change allocation :(
 
So there's no way to name these without duplicating?

2019-05-17 22:04 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +      ];
fixed

2019-05-17 22:06 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +             viewIndex,                                                     //
done.

2019-05-17 22:07 UTC, mhevery commented on packages/core/src/render3/instructions/lview_debug.ts
> +      public id: number,                                     //
Can't. Those comments are there to prevent clang-format from wrapping the list and making it unreadable.

2019-05-17 22:09 UTC, kara commented on packages/core/src/render3/instructions/lview_debug.ts
> +      public id: number,                                     //
Ohhh that's what they're for. I was wondering why.

2019-05-17 22:10 UTC, kara approved these changes
LGTM

2019-05-17 22:57 UTC, benlesh commented on packages/core/src/render3/instructions/debug.ts
> +    return (new Function('Array', `return class ${name} extends Array{}`))(Array);
:+1:

2019-05-17 22:58 UTC, benlesh approved these changes

2019-05-23 13:00 UTC, pkozlowski-opensource commented on packages/core/src/render3/i18n.ts
> -import {attachI18nOpCodesDebug} from './debug';
Seems like this is more than just rename - there is also move to the instructions folder ` packages/core/src/render3/debug.ts → ...e/src/render3/instructions/lview_debug.ts` - was this intended? 

If so we should, at one point, clarify what we mean by "instructions" - so far for me this meant "functions referenced from the generated code"

2019-05-23 13:04 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/debug.ts
> +/**
nit picking: not sure why this file is created in the `instructions` folder. I would rather see it in just top-level folder or have a dedicated folder like `debug`. Also maybe name this file as `dev_mode_debug.ts` to clearly indicate that this is only meant to be used from the dev mode?

2019-05-23 13:05 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/lview_debug.ts
> +import {ComponentTemplate} from '..';
Huh? Does it point to `../index.ts`?

2019-05-23 13:09 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +        matches || (matches = ngDevMode ? new MatchesArray() : []);
nit: maybe `DirectiveMatchesArray` ?

2019-05-23 13:19 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +          type,                                  //
empty comments - if I recall properly @kara was asking to have prop names in those comments. If we don't want to have prop names here, we should remove those comments.

2019-05-23 13:27 UTC, pkozlowski-opensource commented on packages/core/src/util/ng_dev_mode.ts
> +  const _location = typeof location === 'undefined' ? '' : location.toString();
Note to self: not sure how I feel about checking location here...

2019-05-23 13:28 UTC, pkozlowski-opensource commented on packages/core/src/render3/query.ts
> -    queryList.reset(queryListImpl._valuesTree || []);
👍

2019-05-23 13:31 UTC, pkozlowski-opensource approved these changes
Left some nit comments but nothing that would block me approval. LGTM.
(still hoping that we can remove this code once we get memory allocation under control)

2019-05-23 14:19 UTC, mhevery commented on packages/core/src/render3/i18n.ts
> -import {attachI18nOpCodesDebug} from './debug';
Yes there are two commits here. One makes the move the other does the addition of names to constructors. (Separate SHAs)

2019-05-23 14:19 UTC, mhevery commented on packages/core/src/render3/instructions/debug.ts
> +/**
moved to utils folder and renamed to `packages/core/src/util/named_array_type.ts`

2019-05-23 14:19 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +          type,                                  //
comments are there to keep cland-format from reformatting it into lines which makes it hard to read. I will add arg names as that is a good idea.

2019-05-23 14:19 UTC, mhevery commented on packages/core/src/util/ng_dev_mode.ts
> +  const _location = typeof location === 'undefined' ? '' : location.toString();
yes it is a bit hacky, but it is super convenient when debugging the application to be able to force the `ngDevMode`

2019-05-23 14:20 UTC, mhevery commented on packages/core/src/render3/instructions/lview_debug.ts
> +import {ComponentTemplate} from '..';
fixed

2019-05-23 14:21 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +        matches || (matches = ngDevMode ? new MatchesArray() : []);
Good idea, renamed.

2019-05-23 14:24 UTC, mhevery commented
http://test/OCL:249637744:BASE:249637770:1558621442012:57fd6217

2019-06-02 23:23 UTC, mhevery commented
http://test/OCL:249637744:BASE:251141713:1559517821365:55b8ce2b

2019-06-04 19:03 UTC, closed without merging