docs: add section to upgrade guide on lazy loading AngularJS
angular/angular pull request #30541
Opened 2019-05-17 16:23 UTC by brandonroberts

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-05-17 16:33 UTC, mary-poppins commented
You can preview c266e71 at https://pr30541-c266e71.ngbuilds.io/.

2019-05-17 18:37 UTC, gkalpak submitted a review, later dismissed
This is awesome :tada:
Left a few comments, plus: 

- Please, add the new files (e.g. example) to `.github/CODEOWNERS`.
- `UpgradeModule` is not used here (afaict). Although this might be a viable upgrade strategy, this is essentially not an `ngUpgrade` app.
- Where are the tests? 😱 😱 😱 

I am borderline inclined to say that this should be its own guide.
We are also talking about _"using the cli for bundling"_ like ain't nothin', but I don't think we show the users how to use the cli for a hybrid app (and it _is_ a big deal). (Just to be clear: We totally should document using the cli for hybrid apps, we just haven't done it yet.)

2019-05-17 18:37 UTC, gkalpak commented on aio/content/examples/upgrade-lazy-load-ajs/src/app/angularjs-app/index.ts
> +import 'jquery';
Why use jQuery?

2019-05-17 18:37 UTC, gkalpak commented on aio/content/examples/upgrade-lazy-load-ajs/src/app/app.component.ts
> +  title = 'angularjs-hybrid';
Is this used anywhere?

2019-05-17 18:37 UTC, gkalpak commented on aio/content/examples/upgrade-lazy-load-ajs/src/app/lazy-loader.service.ts
> +  bootstrapped = false;
Is this used anywhere?
Did you mean to use it to avoid bootstrapping the AngularJS app multiple times? (You probably should, because bootstrapping it multiple times will probably break :grin:)

2019-05-17 18:37 UTC, gkalpak commented on aio/content/guide/upgrade.md
> +In most environments where both Angular and AngularJS are used to render the application, both frameworks are loaded in the initial bundle being sent to the client. This not only results in a larger
This paragraph seems to be mixing too different aspects: (a) loading the AngularJS parts lazily and (b) bootstrapping the AngularJS app lazily.
They are not the same thing and impact the app differently.

2019-05-17 18:37 UTC, gkalpak commented on aio/content/guide/upgrade.md
> +As of Angular version 8, lazy loading code can be accomplished simply by using the dynamic import syntax `import('..')`. In your application, you create a new service that uses dynamic imports to laz
_import('..')_ --> _import('...')_

2019-05-17 18:37 UTC, gkalpak commented on aio/content/examples/upgrade-lazy-load-ajs/src/app/lazy-loader.service.ts
> +  load(el?: HTMLElement): void {
Why make `el` optional, when it is required for `app.bootstrap()`?
Also, why doesn't TS complain about that? 😕

2019-05-17 18:37 UTC, gkalpak commented on aio/content/guide/upgrade.md
> +The service uses the `import()` method to load your bundled AngularJS application lazily. This decreases the initial bundle size of your application as you're not loading code your user doesn't need
It would be useful to make `angular.bootstrap()` a link to the AngularJS docs (https://docs.angularjs.org/api/ng/function/angular.bootstrap).

2019-05-17 18:37 UTC, gkalpak commented on aio/content/guide/upgrade.md
> +**Note:** After AngularJS is loaded and bootstrapped, listeners such as those wired up in your route configuration will continue to listen for route changes. To ensure listeners are shut down when An
> isn’t

Fancy quote 🙈 

##
Also, a [link to `$routeProvider][1] would be useful.

[1]: https://docs.angularjs.org/api/ngRoute/provider/$routeProvider

2019-05-17 18:37 UTC, gkalpak commented on aio/content/guide/upgrade.md
> +To configure the Angular router, you must define a route for AngularJS URLs. To match those URLs, you add a route configuration that uses the `matcher` property. The `matcher` allows you to use custo
> doesn’t

Fancy quote 🙈

2019-05-17 18:43 UTC, brandonroberts commented on aio/content/examples/upgrade-lazy-load-ajs/src/app/lazy-loader.service.ts
> +  bootstrapped = false;
Yep 😄

2019-05-17 18:45 UTC, brandonroberts commented on aio/content/examples/upgrade-lazy-load-ajs/src/app/lazy-loader.service.ts
> +  load(el?: HTMLElement): void {
Good catch. Not sure why it doesn't complain there

2019-05-17 18:53 UTC, brandonroberts commented
> This is awesome 🎉
> Left a few comments, plus:
> 
> * Please, add the new files (e.g. example) to `.github/CODEOWNERS`.
> * `UpgradeModule` is not used here (afaict). Although this might be a viable upgrade strategy, this is essentially not an `ngUpgrade` app.
> * Where are the tests? 😱 😱 😱
> 
> I am borderline inclined to say that this should be its own guide.
> We are also talking about _"using the cli for bundling"_ like ain't nothin', but I don't think we show the users how to use the cli for a hybrid app (and it _is_ a big deal). (Just to be clear: We totally should document using the cli for hybrid apps, we just haven't done it yet.)

Thanks @gkalpak! 

- I agree, the bundling part is very hand-wavy, and that should be a follow-up as a bigger part of the rethink of the upgrade guide.
- Added example to `.github/CODEOWNERS`
- Removed UpgradeModule
- Using dynamic imports requires `esnext` in the `tsconfig.json`. I was going to do the tests in a follow-up PR after #30385 lands so no extra changes are needed

2019-05-17 19:03 UTC, jbogarthyde reviewed
copy edit/slight re-org

2019-05-17 19:03 UTC, jbogarthyde commented on aio/content/guide/upgrade.md
> +
The following example defines a custom matcher function for AngularJS routes.

2019-05-17 19:03 UTC, jbogarthyde commented on aio/content/guide/upgrade.md
> +
The following code adds a route object ...

2019-05-17 19:13 UTC, mary-poppins commented
You can preview a684746 at https://pr30541-a684746.ngbuilds.io/.

2019-05-17 19:16 UTC, mary-poppins commented
You can preview 8790c5c at https://pr30541-8790c5c.ngbuilds.io/.

2019-05-17 19:17 UTC, mary-poppins commented
You can preview 169dc4d at https://pr30541-169dc4d.ngbuilds.io/.

2019-05-17 19:18 UTC, mary-poppins commented
You can preview 15b8503 at https://pr30541-15b8503.ngbuilds.io/.

2019-05-17 19:26 UTC, mary-poppins commented
You can preview 6c6bac3 at https://pr30541-6c6bac3.ngbuilds.io/.

2019-05-17 19:56 UTC, jasonaden submitted a review, later dismissed
Agreed, this is great and I think it will really help people in this situation.

Reading it from a user's perspective, I think there's a couple things missing that could be solved by an introduction section. The problem description is there, but I think we should beef it up a little bit to make it more clear exactly what the problem is we're solving here.

The other thing I think would be really useful is an overview of the process we're going to use. There are a few distinct parts (not necessarily in this order):

* Setting up your AngularJS application to be lazy loaded (for the bootstrap callback)
* Create the lazy loading service
* Create a component to render your lazy loaded application
* Define a matcher function to determine if a URL is handled by AngularJS or not
* Configure routing

I think adding some sort of intro discussing the overall process would be really helpful for context while reading.

2019-05-17 23:39 UTC, samjulien reviewed
Just a few typos and corrections. I also agree with George on the need to document bundling/setting up the CLI with ngUpgrade, which I hope to be involved with.

2019-05-17 23:39 UTC, samjulien commented on aio/content/guide/upgrade.md
> +Overall application performance is affected in cases where the user stays on Angular-rendered pages, because the AngularJS framework and application is still loaded, and running, even if it is never
```suggestion
Overall application performance is affected in cases where the user stays on Angular-rendered pages because the AngularJS framework and application are still loaded and running, even if they are never accessed.
```

2019-05-17 23:39 UTC, samjulien commented on aio/content/guide/upgrade.md
> +To address the performance problem, you can use  [lazy loading](guide/glossary#lazy-loading) to only load, bootstrap, and render the AngularJS application when needed. This has the added benefit of r
```suggestion
To address the performance problem, you can use  [lazy loading](guide/glossary#lazy-loading) to load, bootstrap, and render the AngularJS application only when needed. This has the added benefit of reducing the initial bundle size.
```

2019-05-17 23:39 UTC, samjulien commented on aio/content/guide/upgrade.md
> +The steps below steps below show you how to create a service that lazy loads and boostraps AngularJS, create a component for AngularJS content, and how to configure the Angular Router to load Angular
```suggestion
The steps below show you how to create a service that lazy loads and bootstraps AngularJS, create a component for AngularJS content, and configure the Angular Router to load AngularJS routes only on specific URLs.
```

2019-05-17 23:39 UTC, samjulien commented on aio/content/guide/upgrade.md
> +To configure the Angular router, you must define a route for AngularJS URLs. To match those URLs, you add a route configuration that uses the `matcher` property. The `matcher` allows you to use custo
Should it always be Angular Router (capitalized)?

```suggestion
To configure the Angular Router, you must define a route for AngularJS URLs. To match those URLs, you add a route configuration that uses the `matcher` property. The `matcher` allows you to use custom pattern matching for URL paths. The Angular Router tries to match on more specific routes such as static and variable routes first. When it doesn't find a match, it then looks at custom matchers defined in your route configuration. If the custom matchers don't match a route, it then goes to catch-all routes, such as a 404 page.
```

2019-05-18 18:31 UTC, jbogarthyde commented on aio/content/guide/upgrade.md
> +To configure the Angular router, you must define a route for AngularJS URLs. To match those URLs, you add a route configuration that uses the `matcher` property. The `matcher` allows you to use custo
It should only be capitalized (and put it code font) when referring to the API element. When used descriptively like this, it should remain lowercase.

2019-05-20 14:01 UTC, mary-poppins commented
You can preview 61c1311 at https://pr30541-61c1311.ngbuilds.io/.

2019-05-20 14:02 UTC, mary-poppins commented
You can preview 03a9670 at https://pr30541-03a9670.ngbuilds.io/.

2019-05-20 14:20 UTC, mary-poppins commented
You can preview 269eec2 at https://pr30541-269eec2.ngbuilds.io/.

2019-05-20 16:09 UTC, mary-poppins commented
You can preview 80a243c at https://pr30541-80a243c.ngbuilds.io/.

2019-05-20 17:50 UTC, IgorMinar approved these changes
this looks good to me! thanks @brandonroberts

2019-05-20 19:46 UTC, jbogarthyde requested changes
Copy edit/organization

2019-05-20 19:46 UTC, jbogarthyde commented on aio/content/guide/upgrade.md
> +
[Lazy loading](guide/glossary#lazy-loading) is a technique that defers the loading of required assets and code resources until they are actually used. This reduces startup time and increases efficiency, especially when running different frameworks in the same application. 

When migrating...

2019-05-20 19:46 UTC, jbogarthyde commented on aio/content/guide/upgrade.md
> +
You can take steps to mitigate both bundle size and performance issues. By isolating your AngularJS app to a separate bundle, you can take advantage of lazy loading to load, bootstrap, and render the AngularJS application only when needed. This reduces your initial bundle size, defers any potential impact from loading both frameworks until absolutely necessary, and keeps your application running as efficiently as possible.

2019-05-20 19:46 UTC, jbogarthyde commented on aio/content/guide/upgrade.md
> +
Make this a bullet list: 

The step below show you how to do the following:

* Set up a callback function for your AngularJS bundle.
* Create a service that lazy loads and bootstraps your AngularJS app.
* Create a routable component for AngularJS content.
* Create a custom `matcher` function for AngularJS-specific URLs and configure the Angular `Router` with the custom matcher for AngularJS routes.

2019-05-20 20:12 UTC, mary-poppins commented
You can preview 8a73bfd at https://pr30541-8a73bfd.ngbuilds.io/.

2019-05-20 20:19 UTC, jasonaden approved these changes

2019-05-21 18:19 UTC, jbogarthyde approved these changes
LGTM

2019-05-21 20:07 UTC, closed without merging