refactor(ivy): make styling instructions use the new styling algorithm
angular/angular pull request #30742
Opened 2019-05-30 02:53 UTC by matsko

This commit is the final patch of the ivy styling algorithm refactor.
This patch swaps functionality from the old styling mechanism to the
new refactored code by changing the instruction code the compiler
generates and by pointing the runtime instruction code to the new
styling algorithm.

2019-06-20 07:45 UTC, matsko commented
https://test.corp.google.com/ui#id=OCL:254147799:BASE:254147805:1561016705188:e47b6a1a

2019-06-20 09:33 UTC, alfaproject commented on packages/compiler-cli/test/compliance/r3_view_compiler_styling_spec.ts
> +    it('should generate overridVjwjwe instructions for only single-level styling bindings when !important is present',
oops

2019-06-20 09:35 UTC, alfaproject commented on packages/compiler-cli/test/compliance/r3_view_compiler_styling_spec.ts
> +          $r3$.ɵɵstyleSanitizer($r3$.ɵɵdefaultStyleSanitizer);
If a sanitizer is not given explicitly, shouldn't it just use the default one?

2019-06-20 09:36 UTC, alfaproject commented on packages/compiler/src/render3/view/compiler.ts
>    // except 'style' and 'class' properties, since they should *not* allocate host var slots
I guess this comment is outdated now

2019-06-20 09:38 UTC, alfaproject commented on packages/core/src/debug/debug_node.ts
> +    let classes !: {[key: string]: boolean};
Type should be: `let classes: {[key: string]: boolean} | undefined;`

2019-06-20 09:39 UTC, alfaproject commented on packages/core/src/debug/debug_node.ts
> +    let styles !: {[key: string]: string | null};
Type should be: `let styles: {[key: string]: string | null} | undefined;`

2019-06-20 09:41 UTC, alfaproject commented on packages/core/src/render3/component.ts
> +    if (rootTNode.classes) {
`if (rootTNode.classes | rootTNode.styles)`

2019-06-20 15:58 UTC, matsko commented on packages/core/src/debug/debug_node.ts
> +    let classes !: {[key: string]: boolean};
The reason for this is because the if statement below assigns a new map and if it overwrites the value then you end up having an empty map be used for no reason.

2019-06-20 15:59 UTC, matsko commented on packages/core/src/debug/debug_node.ts
> +    let styles !: {[key: string]: string | null};
same thing here

2019-06-20 16:06 UTC, alfaproject commented on packages/core/src/debug/debug_node.ts
> +    let classes !: {[key: string]: boolean};
I mean this:
```ts
  get classes(): {[key: string]: boolean} {
    const element = this.nativeElement;
    if (element) {
      const context = loadLContextFromNode(element);
      const lView = context.lView;
      const tData = lView[TVIEW].data;
      const tNode = tData[context.nodeIndex] as TNode;
      if (tNode.classes) {
        if (isStylingContext(tNode.classes)) {
          return new NodeStylingDebug(tNode.classes as TStylingContext, lView, true).values;
        } else {
          return stylingMapToStringMap(tNode.classes);
        }
      }
    }
    return {};
  }
```

2019-06-20 21:17 UTC, matsko commented on packages/core/src/debug/debug_node.ts
> +    let classes !: {[key: string]: boolean};
Ah I see. Yes. Excellent contribution.

2019-06-20 23:18 UTC, matsko commented
https://test.corp.google.com/ui#id=OCL:254147799:BASE:254293643:1561072629996:9d39489c

2019-06-21 07:53 UTC, petebacondarwin approved these changes
LGTM for docs-infra (only size changes - some go up and some go down but none by much).

2019-06-24 15:07 UTC, mhevery requested changes
Overall I love the direction.

- The PR is huge, any way we could break it up to smaller chunks?
- I left few comments please look over them so we can resolve them.

2019-06-24 15:07 UTC, mhevery commented on packages/core/test/bundling/hello_world/bundle.golden_symbols.json
> +  {
There is quite a lot of styling code which does not get tree shaken from the hello_world. This is a problem, can we investigate what is going on?

2019-06-24 15:37 UTC, matsko commented on packages/core/src/render3/styling_next/instructions.ts
> +      fns.push(() => { updateLastDirectiveIndex(tNode, directiveStylingIndex); });
This is part of the workaround until we know what to do with `select`.

2019-06-24 15:38 UTC, matsko commented on packages/core/src/render3/styling_next/instructions.ts
> +    // temporary workaround until `select(n)` is fully compatible
Ask Kara.

2019-06-24 15:38 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +      registerInitialStylingOnTNode(tNode, attrs as TAttributes, lastAttrIndex);
This doesn't pull in anything more than one function. It just happens to be inside of the same file as the rest of the styling algorithm. Notice how are are just using the tNode as is instead of building a full context?

2019-06-24 15:39 UTC, matsko commented on packages/core/src/render3/state.ts
> +  resetStylingState();
These are just two variables that are being reset.

2019-06-24 15:40 UTC, matsko commented on packages/core/test/render3/instructions_spec.ts
> +        ɵɵstyleSanitizer(ɵɵdefaultStyleSanitizer);
The issue here is that now that styling is used across multiple directives and the template, they all need to end up sharing the same sanitizer. Back before in VE there also wasn't the map-based features. So in this case the sanitizer does need to be set before any functions run.

2019-06-24 15:41 UTC, matsko commented on modules/benchmarks/src/tree/render3_function/index.ts
> +      ɵɵstyling();
The compiler still does the property checking ahead of time to determine if the sanitizer is used. Anything that has a `url` CSS value is used to determine whether the sanitizer is apart of the generated instruction code. We can move this fully to runtime, but that would mean using your own sanitizer isn't possible (if we get rid of the instruction).

2019-06-24 15:42 UTC, matsko commented on packages/core/src/render3/styling_next/interfaces.ts
> + * tNode.styles = StylingMap; // only static values present (e.g. `<div style="width:200">`)
Yes it looks like I missed that one.

2019-06-24 15:42 UTC, matsko commented on packages/core/test/bundling/hello_world/bundle.golden_symbols.json
> +  {
The next PR cleans everything up 100%: https://github.com/angular/angular/pull/31193/files#diff-3cc55640e35db5bbf41ef849b7b98c67

2019-06-24 15:45 UTC, kara commented on packages/core/src/render3/styling_next/instructions.ts
> +      fns.push(() => { updateLastDirectiveIndex(tNode, directiveStylingIndex); });
As far as I know, this workaround is not temporary. I thought we decided not to make a breaking change to host binding execution

2019-06-24 15:46 UTC, kara commented on packages/core/src/render3/styling_next/instructions.ts
> +    // temporary workaround until `select(n)` is fully compatible
@mhevery I have a design doc I can send you, but the short of it is that this would be a breaking change from how View Engine works. Chat offline?

2019-06-24 17:45 UTC, matsko commented on packages/core/test/render3/instructions_spec.ts
> +        ɵɵstyleSanitizer(ɵɵdefaultStyleSanitizer);
The compiler still does the property checking ahead of time to determine if the sanitizer is used. Anything that has a url CSS value is used to determine whether the sanitizer is apart of the generated instruction code. We can move this fully to runtime, but that would mean using your own sanitizer isn't possible (if we get rid of the instruction).

2019-06-24 17:45 UTC, matsko commented on modules/benchmarks/src/tree/render3_function/index.ts
> +      ɵɵstyling();
There needs to be an extra instruction (the `styling()` instruction) in the creation block. This way the context knows exactly when to flush when the last `stylingApply()` function is called.

2019-06-24 17:47 UTC, matsko commented on packages/core/src/render3/styling_next/instructions.ts
> +      fns.push(() => { updateLastDirectiveIndex(tNode, directiveStylingIndex); });
Yes. Correct. With the current state of `select()` this workaround is permanent. The reason why we need this is so that each directive can register itself with the context. Then when the context is flushed it knows exactly when to apply its styling values because it knows when the very last hostBindings function is run (since the directive index is stored inside of the context).

2019-06-25 16:09 UTC, mhevery commented on packages/core/test/bundling/hello_world/bundle.golden_symbols.json
> +  {
There is still whole bunch of styling things in Hello world https://github.com/angular/angular/pull/31193/files#diff-f544a0b6aea7dc2c53efbcc2f46f43bd

2019-06-25 16:09 UTC, mhevery commented on packages/core/src/render3/styling_next/instructions.ts
> +      fns.push(() => { updateLastDirectiveIndex(tNode, directiveStylingIndex); });
Could we figure out how to get rid of the closure?

2019-06-25 16:10 UTC, mhevery commented on packages/core/src/render3/instructions/element.ts
> +      registerInitialStylingOnTNode(tNode, attrs as TAttributes, lastAttrIndex);
See https://github.com/angular/angular/pull/31193/files#diff-f544a0b6aea7dc2c53efbcc2f46f43bd it shows that things are not fully tree-shaken in hello world.

2019-06-25 16:13 UTC, mhevery commented on packages/core/test/render3/instructions_spec.ts
> +        ɵɵstyleSanitizer(ɵɵdefaultStyleSanitizer);
> The issue here is that now that styling is used across multiple directives and the template, they all need to end up sharing the same sanitizer

Why can't we just pass it in multiple times?

Why is this statement not true: I would imagine that the sanitizer would be optional for ɵɵstyleSanitizer but would be required for ɵɵstyleMap. 

There may be a good reason to do it your way, I just don't understand it.

2019-06-25 16:13 UTC, mhevery commented on modules/benchmarks/src/tree/render3_function/index.ts
> +      ɵɵstyling();
I don't follow. Why would it not work with the `styling` instruction skipped in tho creation block.

2019-06-26 17:43 UTC, matsko commented on packages/core/src/render3/styling_next/instructions.ts
> +      fns.push(() => { updateLastDirectiveIndex(tNode, directiveStylingIndex); });
Closure is removed in the follow-up cleanup PR.

2019-06-26 17:43 UTC, matsko commented on packages/core/test/bundling/hello_world/bundle.golden_symbols.json
> +  {
All styling code is removed from hello world in the follow-up cleanup PR.

2019-06-26 17:43 UTC, matsko commented on packages/core/src/render3/styling_next/interfaces.ts
> + * tNode.styles = StylingMap; // only static values present (e.g. `<div style="width:200">`)
fixed

2019-06-26 17:43 UTC, matsko commented on packages/core/src/render3/instructions/element_container.ts
> +  if (attrs && tView.firstTemplatePass) {
This can't be changed since `attrs` can be both `undefined` and `null`.

2019-06-26 17:44 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +      registerInitialStylingOnTNode(tNode, attrs as TAttributes, lastAttrIndex);
Fixed in follow-up cleanup PR.

2019-06-26 17:44 UTC, matsko commented on packages/core/src/render3/component.ts
> +  if (rootTNode.classes || rootTNode.styles) {
fixed

2019-06-26 17:44 UTC, matsko commented on packages/core/test/render3/instructions_spec.ts
> +        ɵɵstyleSanitizer(ɵɵdefaultStyleSanitizer);
Me and Misko discussed and this will be left as is.

2019-06-26 17:45 UTC, matsko commented on modules/benchmarks/src/tree/render3_function/index.ts
> +      ɵɵstyling();
We agreed that this would be changed in a follow-up PR.

2019-06-26 22:45 UTC, mhevery approved these changes

2019-06-27 02:51 UTC, kara commented on modules/benchmarks/src/tree/render3_function/index.ts
> +      ɵɵstyling();
Yeah, a follow-up sounds good so this PR doesn't get any bigger. Is there anywhere we are tracking this follow-up work? Create a Jira maybe?

2019-06-27 05:37 UTC, alfaproject commented on packages/core/src/render3/instructions/element_container.ts
> +  if (attrs && tView.firstTemplatePass) {
That's why it's `!=` and not `!==`

2019-06-28 05:02 UTC, kara requested changes
Here's my first pass. It's a big PR so maybe we can sync up in person on some parts of it tomorrow? May be easier to get on the same page.

2019-06-28 05:02 UTC, kara commented on packages/core/src/render3/styling_next/instructions.ts
> +    // temporary workaround until `select(n)` is fully compatible
Can we remove this comment? Since we don't plan on changing `select`, it's a bit misleading

2019-06-28 12:56 UTC, pkozlowski-opensource commented on packages/compiler-cli/test/compliance/r3_view_compiler_styling_spec.ts
> +          $r3$.ɵɵstyleSanitizer($r3$.ɵɵdefaultStyleSanitizer);
This sounds reasonable to me, @matsko WDYT?

2019-06-28 13:18 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/element.ts
> +      registerInitialStylingOnTNode(tNode, attrs as TAttributes, lastAttrIndex);
Why do we need cast to `TAttributes` here?

2019-06-28 13:47 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling_next/bindings.ts
> +      const nativeStyle = native.style as any | null;
I wonder if TypeScript doesn't come with a proper typing so we could avoid `any` here...

2019-06-28 17:04 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +      registerInitialStylingOnTNode(tNode, attrs as TAttributes, lastAttrIndex);
Good catch. Fixed.

2019-06-28 17:05 UTC, matsko commented on packages/core/src/render3/styling_next/bindings.ts
> +      const nativeStyle = native.style as any | null;
It was because `element` as cast as `any`. This is fixed when `element` is `RElement`.

2019-06-28 17:08 UTC, matsko commented on packages/core/src/render3/styling_next/interfaces.ts
> +export interface StylingMapArray extends Array<{}|string|number|null> {
Originally it was `TStlyingMap`, but then it ended being used inside of `LView` for `[style]` and `[class]` properties.

2019-06-28 17:08 UTC, matsko commented on packages/core/src/render3/interfaces/view.ts
> +  [HOST]: RElement|null;
it's in the next PR: https://github.com/angular/angular/pull/31193

2019-06-28 17:10 UTC, matsko commented on packages/core/src/render3/instructions/shared.ts
> +  }
Excellent suggestion. Fixed.

2019-06-28 17:15 UTC, matsko commented on packages/core/src/render3/styling_next/instructions.ts
> +    const index = getSelectedIndex();
Fixed.

2019-06-28 17:17 UTC, matsko commented on packages/core/src/render3/styling_next/instructions.ts
> +    // temporary workaround until `select(n)` is fully compatible
The entire block is removed in the next PR.

2019-06-28 17:17 UTC, matsko commented on packages/core/src/render3/styling_next/util.ts
> + * This function is designed to find an instance of `StylingMapArray` incase it is stored
Fixed.

2019-06-28 17:19 UTC, kara commented on packages/core/src/render3/styling_next/interfaces.ts
> +export interface StylingMapArray extends Array<{}|string|number|null> {
But it's no longer in `LView`, right?

2019-06-28 17:19 UTC, kara commented on packages/core/src/render3/interfaces/view.ts
> +  [HOST]: RElement|null;
I think it's worth backporting to this one. We shouldn't have inaccurate signatures while we're waiting to land the next one for others working on the project.

2019-06-28 17:20 UTC, kara commented on packages/core/src/render3/styling_next/instructions.ts
> +    // temporary workaround until `select(n)` is fully compatible
I think this is trivial enough to remove in this PR

2019-06-28 17:29 UTC, kara commented on packages/core/src/render3/styling_next/interfaces.ts
> +export interface StylingMapArray extends Array<{}|string|number|null> {
Update: Talked in person. Turns out it's both in `LView` and `T` structures, so the `T` doesn't really make sense.

2019-06-29 18:12 UTC, AndrewKushnir commented on packages/core/src/render3/styling_next/bindings.ts
>        if (value) {
@matsko it looks like we may need to adjust this check to take into account cases like the one described in #31345, where the value here would be `0` (with the type of `number`). My guess is that we may also have empty strings here, so may be we should check for `null` here, like:
```
  if (value !== null) {
```
It's not directly related to this PR, we can do it in a separate one once this PR lands.
Thank you.

2019-07-03 17:35 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +  renderInitialStyling(renderer, native, tNode);
No. This function reads `tNode.styles` or `tNode.classes` (those are populated in the function above and inside of the directive creation instructions).

2019-07-03 17:39 UTC, matsko commented on packages/core/test/render3/instructions_spec.ts
> +        ɵɵselect(0);
Removed. Everything passes.

2019-07-03 17:40 UTC, matsko commented on packages/core/src/render3/styling_next/util.ts
>    return compareValueA !== compareValueB;
Updated. Works.

2019-07-03 17:41 UTC, kara commented on packages/core/src/render3/instructions/element.ts
> +  renderInitialStyling(renderer, native, tNode);
My understanding was that `tNode.styles` and `tNode.classes` won't be populated unless there is a `style` or `class` attribute. If there isn't, then there aren't any initial styles to render. Can you clarify?

2019-07-03 18:01 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +  renderInitialStyling(renderer, native, tNode);
Yes this is true. But those attr values are populated to the `tNode` from the `element` and `hostAttrs` instructions (which is what happens in the function above and when the CREATE phase for any directives on the same element are processed). So only dealing with attrs is wrong because it doesn't take into account the static styling that was obtained from any active directives on the element.

2019-07-03 18:03 UTC, matsko commented on packages/core/src/render3/interfaces/view.ts
> +  [HOST]: RElement|null;
This is fixed (locally) and will be a part of this PR.

2019-07-03 18:03 UTC, matsko commented on packages/core/src/render3/styling_next/bindings.ts
> +  }
Fixed

2019-07-03 18:03 UTC, matsko commented on packages/core/src/render3/styling_next/bindings.ts
> +        // it's a container element or it's apart of a test
fixed

2019-07-03 18:03 UTC, matsko commented on packages/core/src/render3/styling_next/bindings.ts
> +    state.classesBitMask |= 1 << index;
comment added

2019-07-03 18:03 UTC, matsko commented on packages/core/src/render3/styling_next/instructions.ts
> +  // due to the fact that
removed

2019-07-03 18:03 UTC, matsko commented on packages/core/src/render3/styling_next/bindings.ts
> +      // it's a container element or it's apart of a test
fixed

2019-07-03 18:08 UTC, kara commented on packages/core/src/render3/instructions/element.ts
> +  renderInitialStyling(renderer, native, tNode);
Ah! Okay, that makes sense.

2019-07-08 20:45 UTC, matsko commented on packages/core/src/render3/styling_next/bindings.ts
>        if (value) {
Good find. I will fix. Thank you.

2019-07-08 20:45 UTC, matsko commented on packages/core/src/render3/styling_next/bindings.ts
>        if (value) {
`!=` needs to be used in the event that the value is `undefined`.

2019-07-08 20:50 UTC, matsko commented on packages/core/src/debug/debug_node.ts
> +            stylingMapToStringMap(tNode.styles);
Fixed.

2019-07-08 20:50 UTC, matsko commented on packages/core/src/render3/instructions/lview_debug.ts
>            isStylingContext(rawValue) ? null : toDebug(readLViewValue(rawValue));
Fixed.

2019-07-08 20:53 UTC, matsko commented on packages/core/src/render3/styling_next/bindings.ts
> +    context: TStylingContext, data: LStylingData, element: any, prop: string | null,
Fixed.

2019-07-08 21:57 UTC, matsko commented on packages/core/src/render3/styling_next/bindings.ts
> +  return false;
So originally this was a combined function, but given there are a few branching points here:

1. Different bitMask values are updated when the binding updates (classes or styles).
2. Different state counter values are updated when the binding updates (classes or styles).
3. Styling has sanitization and classes do not.

This also makes it so that the inner function `updateBindingData` doesn't need to know that the context is "class based".

I think we should keep it as two different functions.

2019-07-08 21:57 UTC, matsko commented on packages/core/src/render3/styling_next/bindings.ts
> +const DEFAULT_SIZE_VALUE = 1;
Fixed.

2019-07-15 14:58 UTC, kara commented on packages/core/src/render3/styling_next/bindings.ts
> +        // it's a container element or it's apart of a test
This `apart` still looks like it needs to be fixed. Same below in this file.

2019-07-15 14:58 UTC, kara commented on packages/core/src/render3/instructions/lview_debug.ts
>            isStylingContext(rawValue) ? null : toDebug(readLViewValue(rawValue));
Seems like this hasn't been fixed yet ^

2019-07-15 14:58 UTC, kara commented on packages/core/test/acceptance/styling_spec.ts
> +  it('should not write to a `class` input binding in the event that there is no static class value',
These tests still pass if I revert the fix to https://github.com/angular/angular/pull/30742#discussion_r299261822 in `element.ts`. 

To make sure we don't regress, it might make sense to edit this test to have a counter to ensure that the input for `class` is not set more than once. e.g. the following passes in VE but still not in this PR:

```ts
       let classCounter: number = 0;

       @Component({template: '<div [class]="c" my-class-dir></div>'})
       class Cmp {
         c: any = 'foo';
       }

       @Directive({selector: '[my-class-dir]'})
       class MyClassDir {
         @Input('class')
         set classVal(v: string) { classCounter++; }
       }

       TestBed.configureTestingModule({declarations: [Cmp, MyClassDir]});
       const fixture = TestBed.createComponent(Cmp);
       expect(classCounter).toEqual(0);
       fixture.detectChanges();
       expect(classCounter).toEqual(1);

       fixture.componentInstance.c = 'dynamic-value';
       fixture.detectChanges();
       expect(classCounter).toEqual(2);
```

2019-07-15 14:58 UTC, kara commented on packages/core/src/render3/instructions/class_map_interpolation.ts
> +  classMapInternal(getSelectedIndex(), interpolatedValue);
IIRC, these `!== NO_CHANGE` values were deliberately left in interpolation functions like this to avoid unnecessary function calls (they were degrading performance in bindings). @pkozlowski-opensource would remember better - do you think we need to keep the if blocks here?

2019-07-15 14:58 UTC, kara commented on packages/core/src/render3/instructions/element.ts
> +function setDirectiveStylingInput(
It looks like there are two different `setDirectiveStylingInput` functions with subtly different implementations: one here and one in `shared.ts`. Seems like this one should probably be cleaned up?

2019-07-15 21:00 UTC, matsko commented on packages/core/src/render3/instructions/lview_debug.ts
>            isStylingContext(rawValue) ? null : toDebug(readLViewValue(rawValue));
Sorry. It looks like a rebase managed to get this merged out. Yes that was missing. This is now fixed.

2019-07-15 21:00 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +    setDirectiveStylingInput(previousOrParentTNode, lView, true);
This was changed to only fire when `tNode.styles` and/or `tNode.classes` exists. There are now three tests that check for this under `acceptance/styling_spec.ts`

2019-07-15 21:01 UTC, matsko commented on packages/core/src/render3/interfaces/container.ts
>     * It could also be a styling context if this is a node with a style/class
Fixed.

2019-07-15 21:09 UTC, matsko commented on packages/core/src/render3/instructions/class_map_interpolation.ts
> +  classMapInternal(getSelectedIndex(), interpolatedValue);
The `NO_CHANGE` inputs do need to reach the internal styling code because that's where the binding counters update. Even if interpolations are not used then this still happens (the counters being incremented that is).

So are we really fixated on avoid a single function call? If we do that then we have state changes happening in two different spots.

2019-07-15 21:10 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +function setDirectiveStylingInput(
The one in `shared.ts` isn't used anymore. Removed.

2019-07-15 21:16 UTC, kara commented on packages/core/src/render3/instructions/class_map_interpolation.ts
> +  classMapInternal(getSelectedIndex(), interpolatedValue);
The binding counters should be updating in `interpolation1` (before the `classMapInternal`). Are there other binding counters that are updated separately of that? Seems odd that we are incrementing the binding counters twice.

2019-07-15 21:46 UTC, matsko commented on packages/core/src/render3/instructions/class_map_interpolation.ts
> +  classMapInternal(getSelectedIndex(), interpolatedValue);
Well every time `styleProp`, `classProp`, `styleMap` and `classMap` are visited then the `lView[BINDING_INDEX]` is incremented even if there are no interpolations used. Yes now we do have `stylePropInterpolate%%%` and `classMapInterpolate%%%' and we could avoid calling the internal code from there in the case of `NO_CHANGE`, but even if we do avoid the function call then we would still need to increment the index outside of same place where the other instructions increment. We would also need to avoid incrementing within the internal function as well and place that up into each instruction directly. This would add more if statements, checks and code overall making this more complicated.

2019-07-18 16:32 UTC, matsko commented on packages/core/test/acceptance/styling_spec.ts
> +  it('should not write to a `class` input binding in the event that there is no static class value',
Fixed.

2019-07-19 19:21 UTC, matsko commented
http://test/OCL:254147799:BASE:259015467:1563564083413:4de779e8

2019-07-19 19:33 UTC, kara approved these changes
LGTM

2019-07-19 19:35 UTC, kara commented
@matsko  Seeing a cyclic dependency issue


```
packages/core/src/render3/util/view_utils.ts -> packages/core/public_api.ts -> 
packages/core/src/core.ts -> packages/core/src/metadata.ts -> 
packages/core/src/metadata/directives.ts -> packages/core/src/render3/jit/directive.ts -> 
packages/core/src/render3/jit/environment.ts -> packages/core/src/sanitization/sanitization.ts -> 
packages/core/src/render3/state.ts -> packages/core/src/render3/assert.ts -> 
packages/core/src/render3/util/view_utils.ts
```

2019-07-19 22:25 UTC, matsko commented
http://test/OCL:254147799:BASE:259049799:1563575125970:1bf971b6

2019-07-19 23:43 UTC, closed without merging