docs: stable to table
angular/angular pull request #30794
Opened 2019-05-31 22:20 UTC by tomgcoleman

type of extra s before "table"

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-06-03 14:06 UTC, kapunahelewong requested changes
@tomgcoleman thanks for this PR! I've left one comment on content. Could you change the PR to be `docs: clarify toh intro` or something like that? Thanks!! 🌸

Edit: PS, make sure you sign the CLA! :)

2019-06-03 14:06 UTC, kapunahelewong commented on aio/content/tutorial/index.md
> +In this _Tour of Heroes_ tutorial, you will build an app that helps a staffing agency manage its table of heroes.
This is an interesting catch. The word "stable" is intentional, however, your PR does underscore that it can be confusing. Since we don't really need it and aren't working with a `table`, how about just removing "stable of":

> In this _Tour of Heroes_ tutorial, you will build an app that helps a staffing agency manage its ~stable of~ heroes.

or

>In this _Tour of Heroes_ tutorial, you will build an app that helps a staffing agency manage its group of heroes.

2019-07-18 18:13 UTC, kapunahelewong commented
@tomgcoleman I meant to say this previously, but will you tag me when you've made the updates so I can help it through the rest of the process? Thanks!

2019-07-23 16:18 UTC, jbogarthyde commented on aio/content/tutorial/index.md
> +In this _Tour of Heroes_ tutorial, you will build an app that helps a staffing agency manage its table of heroes.
How about "available heroes"?

2020-12-03 01:15 UTC, AndrewKushnir commented
Closing this PR since there was no recent activity. Feel free to reopen or create a new one if needed. Thank you.

2020-12-03 01:15 UTC, closed without merging