refactor(ivy): update ɵɵtextBinding to not take index
angular/angular pull request #30792
Opened 2019-05-31 21:43 UTC by benlesh

- Splits core functionality off into a shared internal function
- ɵɵtextBinding will no longer require an index
- Alters the compiler to stop generating an index argument for the instruction
- Updates tests
- Updates some usage of ɵɵtextBinding in i18n to use the helper function instead

2019-06-03 21:06 UTC, mhevery approved these changes

2019-06-03 21:17 UTC, kara commented on packages/core/src/render3/i18n.ts
> +    index: number, createOpCodes: I18nMutateOpCodes, viewData: LView): number[] {
Can you clarify why removing icus is necessary for the text binding refactor? I think I'm missing some context here.

2019-06-03 22:35 UTC, benlesh commented on packages/core/src/render3/i18n.ts
> +    index: number, createOpCodes: I18nMutateOpCodes, viewData: LView): number[] {
Looks like a bad rebase

2019-06-04 23:58 UTC, benlesh commented
[non-ivy presubmit](http://test/OCL:251545061:BASE:251545076:1559692661788:891784b5)

2019-06-05 17:25 UTC, alxhub approved these changes
👍 for the compiler.

2019-06-06 08:52 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +  isProceduralRenderer(renderer) ? renderer.setValue(element, renderStringify(value)) :
Currently `renderStringify` shows up _very_ high on the CPU profile and by calling it here we are essentially calling it multiple times in case of interpolation. I would propose that we either move `renderStringify` to this function caller (and change the signature of `textBindingInternal` accordingly) or have a specialised version of `textBindingInternal` for interpolations

2019-06-06 08:55 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/text_interpolation.ts
> +  const interpolated = ɵɵinterpolation1(prefix, v0, suffix);
Do we still want to call `ɵɵinterpolationX` from `ɵɵtextInterpolateX`? I guess not, but is there plan to tackle it in a separate PR?

2019-06-06 08:59 UTC, pkozlowski-opensource requested changes
So I'm worried that with this change we are over-calling `renderStringify` which shows up very high on the CPU profile. Essentially we _know_ that a result of `interpolateX` will be _string_ or `NO_CHANGE` so we shouldn't be calling `renderStringify` again in the `textBindingInternal`.

Also, we are still calling instructions from other instructions but I guess it should / will be tackled in a separate PR?

2019-06-06 15:38 UTC, benlesh commented on packages/core/src/render3/instructions/shared.ts
> +  isProceduralRenderer(renderer) ? renderer.setValue(element, renderStringify(value)) :
To clarify, this isn't a change to the code or the behavior, this is basically just moving what was inside of the textBinding instruction to another function. We should probably tackle this in a separate PR.

2019-06-06 15:39 UTC, benlesh commented on packages/core/src/render3/instructions/text_interpolation.ts
> +  const interpolated = ɵɵinterpolation1(prefix, v0, suffix);
Yes... that's just additional clean up.  Similarly, we need to clean up ɵɵbind

2019-06-06 22:30 UTC, benlesh commented on packages/core/src/render3/instructions/shared.ts
> +  isProceduralRenderer(renderer) ? renderer.setValue(element, renderStringify(value)) :
Put another way, we shouldn't be calling `renderStringify` any more after this PR than we were _before_ this PR, so I think we should follow up addressing performance issues related to that in another PR. Unless I'm missing something?

2019-06-07 13:55 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +  isProceduralRenderer(renderer) ? renderer.setValue(element, renderStringify(value)) :
@benlesh I've left this comment since you are extracting a new function here and this new function is called from `ɵɵtextInterpolateX` which returns a `string` so calling `renderStringify` again is not needed. 

Anyway, I'm cool with doing refactor in a follow up PR..... although I _think_ that it might be good time to change it now as you've got all the context in your brain and touching this part of code... Approving the PR and leaving the final decision up to you....

2019-06-07 13:56 UTC, pkozlowski-opensource approved these changes
Approving, but https://github.com/angular/angular/pull/30792#discussion_r291602940 ....

2019-06-07 15:50 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +  isProceduralRenderer(renderer) ? renderer.setValue(element, renderStringify(value)) :
@benlesh Please fix that since double calling `renderStringify` seems wasteful.

2019-06-07 16:13 UTC, benlesh commented on packages/core/src/render3/instructions/shared.ts
> +  isProceduralRenderer(renderer) ? renderer.setValue(element, renderStringify(value)) :
Ah, I see. I didn't catch that. Thanks.

2019-06-07 16:22 UTC, benlesh commented on packages/core/src/render3/instructions/shared.ts
> +  isProceduralRenderer(renderer) ? renderer.setValue(element, renderStringify(value)) :
FYI: We might want to use a negated type on `renderStringify` to prevent it from being called with a string at compile-time, once that feature lands: https://github.com/Microsoft/TypeScript/pull/29317

We can't do a run-time assertion here, because at run time it may be valid... But at build time it's clearly a mistake. I'll add a TODO in the code.

2019-06-07 23:15 UTC, kara commented
Marked for cleanup since it looks like we still need to fix https://github.com/angular/angular/pull/30792#discussion_r291602940

2019-06-11 21:33 UTC, AndrewKushnir commented
@benlesh FYI this PR conflicts with master (after merging other PRs). I'm removing "merge" label for now. Thank you.

2019-06-13 16:40 UTC, benlesh commented
Still needs ivy presubmit. :\

2019-06-13 22:16 UTC, benlesh commented
[ivy presubmit seems normal](https://test.corp.google.com/ui#id=OCL:251545061:BASE:253098891:1560459286396:820e801f)

2019-06-13 22:17 UTC, benlesh commented
CARETAKER: Ivy presubmit is normal.

2019-06-14 19:23 UTC, closed without merging