docs(benchpress): expand benchmark running instructions
angular/angular pull request #30824
Opened 2019-06-03 15:44 UTC by pkozlowski-opensource

2019-06-03 18:52 UTC, mhevery approved these changes

2019-06-03 20:32 UTC, JoostK commented on modules/benchmarks/README.md
> +## Run in the browser (prod mode)
There doesn't appear to be a `prodserver` target in any of the benchmarks:

```
ERROR: no such target '//modules/benchmarks/src/tree/ng2:prodserver': target 'prodserver' not declared in package 'modules/benchmarks/src/tree/ng2'
```

2020-01-31 04:16 UTC, IgorMinar commented on modules/benchmarks/README.md
> +yarn bazel run modules/benchmarks/src/tree/ng2:devserver --define=compile=aot
```suggestion
yarn bazel run modules/benchmarks/src/tree/ng2:devserver --config=ivy
```

2020-01-31 04:17 UTC, IgorMinar commented on modules/benchmarks/README.md
> +yarn bazel run modules/benchmarks/src/tree/ng2:prodserver --define=compile=aot
```suggestion
yarn bazel run modules/benchmarks/src/tree/ng2:prodserver --config=ivy
```

2020-01-31 04:17 UTC, IgorMinar commented on modules/benchmarks/README.md
> +yarn bazel run modules/benchmarks/src/tree/ng2:perf --define=compile=aot
```suggestion
yarn bazel run modules/benchmarks/src/tree/ng2:perf --config=ivy
```

2020-01-31 04:22 UTC, IgorMinar requested changes

2020-01-31 04:22 UTC, IgorMinar commented on modules/benchmarks/README.md
> +## Run in the browser (dev mode)
I don't believe that we have a dev mode for running benchmarks. The ts_devserver rule is used to provide devserver which hosts an optimized bundle used for profiling.

Also as Joost noted below there is no prodserver so the whole section you added shouldn't have been added.

2020-11-12 10:27 UTC, petebacondarwin commented
@pkozlowski-opensource - hope you are fine and dandy! Shall we just close this PR, since it hasn't been touched for almost a year, or can it be resurrected?

2021-01-13 18:50 UTC, AndrewKushnir commented
@pkozlowski-opensource hope you're doing great!
FYI, I'm closing this PR for now, feel free to reopen once you get a chance to look at it again. Thank you.

2021-01-13 18:50 UTC, closed without merging