fix(ivy): trigger directive inputs for each template creation
angular/angular pull request #30870
Opened 2019-06-05 13:39 UTC by ocombe

A directive input that doesn't use a binding is triggered during the creation phase. But this was only executed at the first template pass, and not on subsequent ones.
Now only the creation of the update instruction is executed on the first template pass, anything else is executed every time a template is created.

2019-06-05 15:58 UTC, mhevery requested changes

2019-06-05 15:58 UTC, mhevery commented on packages/core/src/render3/i18n.ts
> +  i18nAttributesFirstPass(tView, index, values);
notice that first template pass check was here. This means that VM does not have to inline `i18nAttributesFirstPass` for it to be fast. With this change first template pass is buried in `i18nAttributesFirstPass` which means the VM will have to inline this before it becomes fast. 

Could we refactor the code so that the first template pass is as close to `ɵɵi18nAttributes` as possible?

2019-06-05 16:55 UTC, AndrewKushnir commented on packages/core/test/acceptance/i18n_spec.ts
> +      // This assertion fails (second template pass)
I believe this assertion should also pass after this fix?

2019-06-05 17:43 UTC, alxhub commented on packages/core/src/render3/i18n.ts
> +          if (tView.firstTemplatePass && tView.data[index + HEADER_OFFSET] === null) {
The above work (especially the regex operation) also seems like it should only have to happen on first template pass.

2019-06-05 18:40 UTC, ocombe commented on packages/core/test/acceptance/i18n_spec.ts
> +      // This assertion fails (second template pass)
oups yes, forgot to remove that comment :)

2019-06-05 18:42 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +          if (tView.firstTemplatePass && tView.data[index + HEADER_OFFSET] === null) {
no we need to know if it has a binding or not, only bindings run on first template pass because we generate instructions that will be used during update, while non bindings values are set immediately (every time)

2019-06-05 18:44 UTC, ocombe commented on packages/core/src/render3/i18n.ts
> +  i18nAttributesFirstPass(tView, index, values);
As discussed with @mhevery we decided that we would keep the current code because it would be too complicated and add too much duplication to do it otherwise

2019-06-05 19:43 UTC, mhevery approved these changes

2019-06-05 22:13 UTC, AndrewKushnir commented
- [VE presubmit](http://test/OCL:251727364:BASE:251727388:1559772394772:23bab285)
- [Ivy presubmit](https://test.corp.google.com/ui#id=OCL:251727836:BASE:251728111:1559772596981:5cc2cdbb)

2019-06-06 03:14 UTC, kara commented
Here's another [VE presubmit](http://test/OCL:251773274:BASE:251773279:1559790864718:6f22ce07)

2019-06-06 17:24 UTC, AndrewKushnir commented
New [VE presubmit](https://test.corp.google.com/ui#id=OCL:251767629:BASE:251876516:1559841780867:d9dfe5d9).

2019-06-06 18:03 UTC, AndrewKushnir commented
Ivy presubmit looks normal, VE presubmit is successful, adding "merge" label.

2019-06-06 20:49 UTC, closed without merging