fix(service-worker): don't crash if registration failed
angular/angular pull request #30876
Opened 2019-06-05 15:59 UTC by H--o-l

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

After using `ServiceWorkerModule.register('/ngsw-worker.js'),`, if you have an unstable internet connection, `navigator.serviceWorker.register('/ngsw-worker.js')` call can fail and your application can crash.
I think that the error can't be caught on the user side.

## What is the new behavior?

If `navigator.serviceWorker.register('/ngsw-worker.js')` fail, there is no uncaught error anymore.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No (I'm not completely sure)

## Other information

N/A

2019-06-05 16:04 UTC, H--o-l commented
I signed it!

2019-06-05 19:31 UTC, gkalpak requested changes

2019-06-05 19:31 UTC, gkalpak commented on packages/service-worker/src/module.ts
> +        () => navigator.serviceWorker.register(script, {scope: options.scope}).catch(() => {}));
I don't think it is a good idea to swallow that error. If the SW fails to register (for whatever reason), the developer should know.
If you want to avoid that the uncaught rejection error, maybe we could explicitly pass it to `console.error()` inside the `catch()`? WDYT?

2019-06-06 08:39 UTC, H--o-l commented on packages/service-worker/src/module.ts
> +        () => navigator.serviceWorker.register(script, {scope: options.scope}).catch(() => {}));
Hey @gkalpak, thanks for the feedback.
It's a good idea, here is the diff I just push in my commit:
```patch
--- a/packages/service-worker/src/module.ts
+++ b/packages/service-worker/src/module.ts
@@ -118,7 +118,9 @@ export function ngswAppInitializer(
     // Don't return anything to avoid blocking the application until the SW is registered.
     // Catch and ignore the error if SW registration fails.
     readyToRegister$.pipe(take(1)).subscribe(
-        () => navigator.serviceWorker.register(script, {scope: options.scope}).catch(() => {}));
+        () =>
+            navigator.serviceWorker.register(script, {scope: options.scope})
+                .catch(err => console.error('NGSW - service worker register failed with: ', err)));
```
PS: Would you be able to help me fixing the CI tests ?
If you think this fix is a good idea of course.

2019-06-06 12:36 UTC, gkalpak requested changes
Thx, @H--o-l. I left a couple of minor comments, but otherwise lgtm.
I also suggest some changes to the commit message:
- Change the subject to `fix(service-worker): avoid uncaught rejection warning when registration fails`
- Typo: _"can failed"_ --> _"can fail"_
- Typo: _" a \`Uncaught"_ --> _"an \`Uncaught"_
- Change the last sentence to describe the new behavior (i.e. logging the error and not ignoring the error).

2019-06-06 12:36 UTC, gkalpak commented on packages/service-worker/src/module.ts
> +    // Catch and ignore the error if SW registration fails.
We are not really ignoring it any more. Maybe change to `Catch and log the error if SW registration fails to avoid uncaught rejection warning`?

2019-06-06 12:36 UTC, gkalpak commented on packages/service-worker/src/module.ts
> +                .catch(err => console.error('NGSW - service worker register failed with: ', err)));
I would change it to just `Service worker registration failed with:`.

2019-06-06 12:42 UTC, gkalpak commented on packages/service-worker/src/module.ts
> +        () => navigator.serviceWorker.register(script, {scope: options.scope}).catch(() => {}));
The failing tests on CI are due to the fact that we are mocking `serviceWorker.register()` [here][1], but not returning a promise (which was not necessary before). You need to change the above line to something like:

```diff
-beforeEach(() => swRegisterSpy = spyOn(navigator.serviceWorker, 'register'));
+beforeEach(() => swRegisterSpy = spyOn(navigator.serviceWorker, 'register').and.returnValue(Promise.resolve()));
```

[1]: https://github.com/angular/angular/blob/957f594d7cb596e495d166db3d3ecb5103abd7ea/packages/service-worker/test/module_spec.ts#L31

2019-06-06 16:14 UTC, H--o-l commented
@gkalpak, CI looks good, the fix was exactly what you proposed.
I also update the commit and commit message with changes you suggested.

Thanks for your help !

2019-06-06 17:33 UTC, gkalpak requested changes
:+1:

Looking at the test fix again, I think it is a good idea to add a test for the new behavior (in `module_spec.ts`). It could go like this:

```ts
it('catches and a logs registration errors', async() => {
  const consoleErrorSpy = spyOn(console.error);
  swRegisterSpy.and.returnValue(Promise.reject('no reason'));

  await configTestBed({enabled: true, scope: 'foo'});
  expect(consoleErrorSpy).toHaveBeenCalledWith('Service worker registration failed with:' , 'no reason');
});
```

2019-06-07 10:27 UTC, H--o-l commented
Hey @gkalpak, thanks for the idea, and the test I should have wrote myself from the beginning.
I add it to the commit, inside the `describe('register()', () => {` test section.
CI looks to like it :muscle:

2019-06-07 11:41 UTC, gkalpak approved these changes
Great job! Thx, @H--o-l 👍

2019-06-07 15:48 UTC, closed without merging