feat(docs-infra): return code typo styling
angular/angular pull request #30899
Opened 2019-06-06 19:04 UTC by sjtrimble

Returned code typography styling and added code link styles.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Code styles outside of code blocks and examples were accidentally removed.

Issue Number: N/A

## What is the new behavior?
- Returned code styles
- Added styles to links that are also code text so that the user knows that they can click on the links

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-06-06 19:11 UTC, mary-poppins commented
You can preview 163e0d8 at https://pr30899-163e0d8.ngbuilds.io/.

2019-06-06 19:19 UTC, petebacondarwin commented
I'm not sure how I feel about this page https://pr30899-163e0d8.ngbuilds.io/cli/generate

<img width="855" alt="Screenshot 2019-06-06 at 20 17 36" src="https://user-images.githubusercontent.com/15655/59060085-352c1a00-8898-11e9-87bc-3fee98eb3641.png">

And do we care that inline code blocks have padding that means they are indented slightly if they are at the start of a line?

<img width="399" alt="Screenshot 2019-06-06 at 20 18 52" src="https://user-images.githubusercontent.com/15655/59060158-660c4f00-8898-11e9-8dc4-ef5ffdf3147c.png">
<img width="407" alt="Screenshot 2019-06-06 at 20 18 45" src="https://user-images.githubusercontent.com/15655/59060159-660c4f00-8898-11e9-999d-c4d64921c167.png">


But otherwise it looks pretty good.

2019-06-06 20:01 UTC, sjtrimble commented
@petebacondarwin

1. Agree on the padding, that doesn't look right in the edge cases I've carved out - I will update that.

2. I personally like it when it's consistent throughout and everything gets styled like code with the exception of headers and such. That subcommands list - I like it like that :) or I like not having it like code at all, just regular `p` text. Same with the CLI [options table](https://pr30899-163e0d8.ngbuilds.io/cli/generate#appshell) - these could be styled like regular text.

Here are some examples:

Example (Preferred) | Full Code Styling Only Where Relevant:
http://groovy-lang.org/groovyc.html

Example | Code Styles on All Elements Regardless of Type: https://docs.djangoproject.com/en/2.2/topics/email/

2019-06-06 20:34 UTC, mary-poppins commented
You can preview c483acf at https://pr30899-c483acf.ngbuilds.io/.

2019-06-09 11:22 UTC, gkalpak approved these changes
Love the clean-ups 💯

2019-06-09 11:22 UTC, gkalpak commented on aio/src/styles/2-modules/_code.scss
> +  table td:first-child &,
Wow, I didn't realize `&` could be placed anywhere in Sass 🦅

2019-06-09 11:22 UTC, gkalpak commented on aio/src/styles/2-modules/_code.scss
> +  .alert, .callout & {
This is equivalent in CSS to `code .alert, .callout code`, which I assume is not what you are aiming for.
I would expect `.alert &, .callout &`. (OOC, why not put each on a new line as you did with everything else? 🤔)

2019-06-09 11:22 UTC, gkalpak commented on aio/src/styles/2-modules/_code.scss
> +    // border-bottom-color: transparentize($darkgray, 0.4);
🤔

2019-06-09 11:22 UTC, gkalpak commented on aio/src/styles/2-modules/_code.scss
> +    border-bottom-color: darken($darkgray, 40%);
I can hardly notice a visual difference when hovering. Is that intentional?

2019-06-09 11:22 UTC, gkalpak commented on aio/src/styles/2-modules/_code.scss
> +h6 {
Waht about `table th` (as above)? Can we combine these selectors with the similar ones for `code` above (to not have to keep them in sync)?

2019-06-09 11:22 UTC, gkalpak commented on aio/src/styles/2-modules/_code.scss
> +  } /* a function name */
Not sure how I feel about these changes :grin:

2019-06-11 05:38 UTC, Splaktar commented
I don't see any a11y contrast issues caused by this PR. 

However, our docs pages still have a lot of a11y contrast issues. Lots of the blue links on grey don't have enough contrast. Also the footer white on light blue fails contrast checks. 

I think that you made the background white in some PR. Is that not merged yet? It looks like the white background is on AIO, but not in this PR. Maybe you can rebase this one?

2019-06-12 19:12 UTC, sjtrimble commented on aio/src/styles/2-modules/_code.scss
> +code {
Oopsies :)

2019-06-12 19:12 UTC, sjtrimble commented on aio/src/styles/2-modules/_code.scss
> +  table td:first-child &,
Yes, it's my ABSOLUTE favorite SCSS feature :)

2019-06-12 19:12 UTC, sjtrimble commented on aio/src/styles/2-modules/_code.scss
> +  .alert, .callout & {
Oversight, I'll fix

2019-06-12 19:14 UTC, sjtrimble commented on aio/src/styles/2-modules/_code.scss
> +    border-bottom-color: darken($darkgray, 40%);
You're right, I made it a bit more obvious. I just wanted it slightly subtle but not super distracting.

I think we need an overall code style strategy, but for now (since we didn't have any color indicator before), this is a step in the right direction.

2019-06-12 19:14 UTC, sjtrimble commented on aio/src/styles/2-modules/_code.scss
> +h6 {
I tried for a long time and wasn't able to but I think I managed to figure it out now.

2019-06-12 19:15 UTC, sjtrimble commented on aio/src/styles/2-modules/_code.scss
> +  } /* a function name */
I don't think I changed anything here intentionally ...? I can't tell if you're telling a joke or if you think something needs to change here 😕

2019-06-12 19:16 UTC, sjtrimble commented
@Splaktar Yeah, some accessibility issues were addressed in a separate PR. Usually with several rounds of back and forth I wait until the end to rebase :) Regardless, it's now rebased.

2019-06-12 19:19 UTC, mary-poppins commented
You can preview 72e79fb at https://pr30899-72e79fb.ngbuilds.io/.

2019-06-12 21:28 UTC, gkalpak commented on aio/src/styles/2-modules/_code.scss
> +  } /* a function name */
I was referring to the indentation/code layout changes. On one hand, I love consistency - on the other hand, the one-liners were more readable/less noisy.

2019-06-22 07:48 UTC, Splaktar commented
With `component` hovered:
![Screen Shot 2019-06-22 at 03 35 33](https://user-images.githubusercontent.com/3506071/59960980-d02f1180-949e-11e9-9803-7d150c157f5e.png)
Looks good!

Unfortunately, `ng run` here fails a11y contrast audits.
![Screen Shot 2019-06-22 at 03 38 55](https://user-images.githubusercontent.com/3506071/59961014-49c6ff80-949f-11e9-9558-9272274dad8f.png)

I'm seeing this with all links that are in a code style. 
![Screen Shot 2019-06-22 at 03 41 38](https://user-images.githubusercontent.com/3506071/59961049-aa563c80-949f-11e9-8692-a938b09d7d22.png)

Changing
```css
.sidenav-content a {
    color: #1976d2;
}
```
to
```css
.sidenav-content a {
    color: #186fc6;
}
```
seems to get this to the AA recommendation of 4.5.

2019-06-22 07:50 UTC, Splaktar requested changes
I suggested some changes to bring the contrast of code + link text in line with a11y AA guidelines.

2019-10-07 08:49 UTC, petebacondarwin commented
@sjtrimble is this PR still desired? If so can you rebase and address the comments?

2019-11-11 21:12 UTC, sjtrimble commented
@petebacondarwin Yes, this is still desired - I'll address comments and rebase.

2020-11-12 10:29 UTC, petebacondarwin commented
@sjtrimble - do you still plan to land this PR?

2021-01-13 18:51 UTC, AndrewKushnir commented
FYI, I'm closing this PR for now (since there are some merge conflicts as well), feel free to reopen once you get a chance to look into it. Thank you.

2021-01-13 18:51 UTC, closed without merging