refactor(ivy): WIP
angular/angular pull request #30921
Opened 2019-06-07 16:54 UTC by petebacondarwin

Just in case I get hit by a meteor during the weekend.

2019-06-22 00:06 UTC, alxhub requested changes
Looking very good! Apart from the above:

* Circular deps issues in `file_system`, as we discussed.

One option here is to split the `AbsoluteFsPath`/etc. stuff into type and value, and declare them in separate files. All of the types (`FileSystem` & friends, etc) would go into the same file, because their types are circular.

* Circular reference in `compiler-cli`.

`compiler-cli/src/perform_compile` imports from `'../index', which is circular. I don't really understand why `compiler-cli` as a package is exporting the FS stuff at the top level. They should just be imported normally, from `./ngtsc/file_system`.

Other than that, this is looking pretty solid!

2019-06-22 00:13 UTC, alxhub commented
I ran some benchmarks in g3 on this change, to see if it has any performance implications. As far as I can tell, it doesn't. The cost seems to be under 5%, with some runs showing identical performance and the average around 1% slower. I think this is reasonable to land now - we can do some work later to speed things up (e.g. by adding a fast path for `AbsoluteFsPath.from` in POSIX, or maybe in google3).

2019-06-22 00:13 UTC, alxhub commented
The presubmit failures are the result of the circular deps - cleaning those up should fix them.

2019-06-22 06:57 UTC, petebacondarwin commented on packages/bazel/src/ngc-wrapped/index.ts
> +    // In pass-through mode for TypeScript, we want to turn off decorator transpilation
Yep. I think I indented at some point and the auto-formatter "fixed it", then didn't return it after the indent was removed.

2019-06-22 07:00 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/writing/in_place_file_writer.ts
> +    const backPath = AbsoluteFsPath.from(`${file.path}.__ivy_ngcc_bak`);
I would be fine with just casting: 

```
`${file.path}.__ivy_ngcc_bak` as AbsoluteFsPath;
```

It is still a clear flag that we have explicitly chosen to declare this as a safe branded path.

2019-06-22 07:04 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/dependencies/commonjs_dependency_host_spec.ts
> +          name: _('/no/imports/or/re-exports/index.js'),
I know where you are coming from. I kept switching back and forth myself.

I ended up liking the fact that `TestFile` expects a branded path for the name. This is because these file names are often used elsewhere, for example when looking up the source files. By insisting that they are already branded, we keep the whole tests a lot safer.

Although it is boilerplate, it is fairly easy to follow and is consistent across the codebase.

2019-06-22 07:07 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/file_system/src/compiler_host.ts
> +    return this.getDefaultLibLocation() + '/' + ts.getDefaultLibFileName(options);
Woh! How did I miss that??

2019-06-22 07:11 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/file_system/src/logical.ts
>  /// <reference types="node" />
oh! great :-)

2019-06-22 07:13 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/file_system/src/mock_file_system_native.ts
> +export class MockFileSystemNative extends MockFileSystem {
Yeah, mixins would be nice :-)

2019-06-22 07:15 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/file_system/src/util.ts
> + * Toggle the case of each character in a file path.
Because we actually need this function to return the transformed file-path to be tested for existence:

```
isCaseSensitive(): boolean { return this.exists(togglePathCase(__filename)); }
```

I couldn't change the return type without changing the doc description.

2019-06-22 07:20 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/file_system/src/node_js_file_system.ts
> +  isCaseSensitive(): boolean { return this.exists(togglePathCase(__filename)); }
Yes, I will memoize this. Regarding different partitions... TS itself doesn't account for this. Their implementation is very similar:

```
            function isFileSystemCaseSensitive(): boolean {
                // win32\win64 are case insensitive platforms
                if (platform === "win32" || platform === "win64") {
                    return false;
                }
                // If this file exists under a different case, we must be case-insensitve.
                return !fileExists(swapCase(__filename));
            }
```

2019-06-22 07:22 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/file_system/src/logical.ts
>  /// <reference types="node" />
But actually other files need node types so I am moving the directive to those files.

2019-06-22 20:20 UTC, petebacondarwin commented
The reason that compiler-cli was exporting the file-system stuff is because the ngc-wrapped in the `packages/bazel` package needed to set it...

2019-06-23 10:03 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/writing/in_place_file_writer.ts
> +    const backPath = AbsoluteFsPath.from(`${file.path}.__ivy_ngcc_bak`);
What do you think @alxhub ?

2019-06-23 10:04 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/entry_point/src/logic.ts
> +      if (FileSystem.getFileSystem().basename(tsFile) === 'index.ts' &&
👼

2019-06-23 10:05 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/file_system/src/file_system.ts
> +export class FileSystem {
I have ended up refactoring to have all the types in one file and all the helpers as free-standing function in another file. This removes the need for the private static and also solves the circular reference issues.

2019-06-23 10:06 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/file_system/src/mock_file_system_native.ts
> +export class MockFileSystemNative extends MockFileSystem {
Also I could have done this with a `Proxy`, perhaps, which would have saved the manual delegation.

2019-06-23 10:06 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/file_system/src/mock_file_system.ts
> +export abstract class MockFileSystem implements FileSystem {
Done.

2019-06-23 10:06 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/file_system/src/test_helper.ts
> +export function initMockFileSystem(os: string, cwd?: AbsoluteFsPath): void {
Done.

2019-06-23 10:14 UTC, petebacondarwin commented
@alxhub: I have added three fixup commits. (I know you prefer not but it was for my own benefit in case I needed to bail out on one or more.)

* The first addresses the small changes recommended in your review.
* The second moves all the testing stuff around so that we don't have circular package dependencies and the test utilities are in a more intuitive place.
* The third moves the FileSystem types into one file and the helper functions into another, resolving the circular dependencies between the file_system source files; and also making the positioning of all the helpers more intuitive and consistent.

2019-06-24 14:50 UTC, ocombe approved these changes
looks good to me for the i18n part

2019-06-24 21:16 UTC, alxhub commented on packages/compiler-cli/ngcc/src/writing/in_place_file_writer.ts
> +    const backPath = AbsoluteFsPath.from(`${file.path}.__ivy_ngcc_bak`);
Let's leave it for now. I'm not _terribly_ worried about the performance.

2019-06-24 21:16 UTC, alxhub commented on packages/compiler-cli/ngcc/test/dependencies/commonjs_dependency_host_spec.ts
> +          name: _('/no/imports/or/re-exports/index.js'),
👍

2019-06-24 21:17 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/file_system/src/file_system.ts
> +export class FileSystem {
👍

2019-06-24 21:17 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/file_system/src/logical.ts
>  /// <reference types="node" />
Yeah. In general anywhere we import from a node API module, we should have this directive.

2019-06-24 21:18 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/file_system/src/mock_file_system_native.ts
> +export class MockFileSystemNative extends MockFileSystem {
I prefer explicitness to tricks with `Proxy` - that way the type system guarantees things will work.

2019-06-24 21:19 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/file_system/src/util.ts
> + * Toggle the case of each character in a file path.
Hahaha oh I understand :-P it's just such a funny method to have.

It MaKeS mE tHiNk AbOuT wRitInG pAtHs LiKe ThIs

2019-06-24 21:20 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/file_system/src/node_js_file_system.ts
> +  isCaseSensitive(): boolean { return this.exists(togglePathCase(__filename)); }
Hahahaha. Beautiful.

2019-06-24 21:21 UTC, alxhub commented
@petebacondarwin 👍 

The only comment I have is that I would prefer if the mock FS stuff lived under `ngtsc/file_system/testing`. It doesn't (and shouldn't) import from any of `test/`.

2019-06-24 21:21 UTC, alxhub approved these changes

2019-06-25 05:48 UTC, petebacondarwin commented
> The only comment I have is that I would prefer if the mock FS stuff lived under ngtsc/file_system/testing. It doesn't (and shouldn't) import from any of test/.

It is not quite that simple because the `mock_file_loading.ts` file imports from the `runfile_helpers.ts`, which is also used by the old `TestSupport` and also in the `aot` `test_util.ts` files...

We would need to leave the `mock_file_loading.ts` in the `ngtsc/testing` package and then have that package depend upon the `file_system/testing` package, which sort of defeats the point of moving the other mock file stuff into its own package;

I will try to move the runfile helpers to a completely separate package, outside ngtsc, which can then be depended upon independently...

2019-06-25 17:38 UTC, kara commented
[VE presubmit](https://test.corp.google.com/ui#id=OCL:254999390:BASE:254999444:1561484220944:5e77ac1)

[Ivy presubmit](http://test/OCL:254999390:BASE:254999617:1561484268490:6c5001da)

2019-06-25 23:27 UTC, closed without merging