refactor(ivy): simplify `walkTNodeTree` method for readability
angular/angular pull request #30927
Opened 2019-06-08 03:46 UTC by mhevery

2019-06-10 06:14 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +  if (beforeNode != null) {
`!==` ?

2019-06-10 06:22 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> + * `applyContainer` performs operation on the container and its views as specified by `action`
Looks like comment here was copied from the "container" while here we are dealing with "element container".

2019-06-10 06:25 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> + * @param lView The LView which needs to be inserted, detached, destroyed.
`tElementContainerNode` is not part of the argument list

2019-06-10 06:31 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +  while (Array.isArray(wrappedNode)) {
It wasn't clear to me while reading the code what is going on here. Add comments explaining what and why we are doing here?

2019-06-10 06:34 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +    nodeOrLContainer: RNode | LContainer | LView, beforeNode?: RNode | null) {
`nodeOrLContainer` variable name is misleading as it could also be a `LView`

2019-06-10 06:37 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
>  export function addRemoveViewFromContainer(viewToWalk: LView, insertMode: false): void;
Please rename `viewToWalk` -> `lView` in all overloaded version of this function + documentation

2019-06-10 07:02 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +  const node: RNode = wrappedNode;
`node` -> `rNode`?

2019-06-10 07:06 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +    wrappedNode = wrappedNode[0];
`0` is a "magic number" here, did you mean `HOST`?

2019-06-10 07:08 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +      ngDevMode && assertNotEqual(viewRootTNodeType, TNodeType.View, 'Unexpected TNodeType.View');
Maybe turn those assertions into a "whitelist" instead (at this point it can be only a container or an element, right?

2019-06-10 07:11 UTC, pkozlowski-opensource requested changes
Left some in-line comments (mostly nits). Love the direction, generally speaking.

The are material tests failures, they look legit.

Also, wasn't clear for me if this is still WIP (there are some comments left in the code that either needs to be addressed and / or turned into TODOs / JIRA).

Finally, it needs golden file update.

2019-06-10 15:49 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +    nodeOrLContainer: RNode | LContainer | LView, beforeNode?: RNode | null) {
renamed

2019-06-10 15:49 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +  while (Array.isArray(wrappedNode)) {
added a comment

2019-06-10 15:49 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +    wrappedNode = wrappedNode[0];
fixed

2019-06-10 15:49 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +  const node: RNode = wrappedNode;
fixed

2019-06-10 15:49 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
>  export function addRemoveViewFromContainer(viewToWalk: LView, insertMode: false): void;
fixed

2019-06-10 15:49 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +  if (beforeNode != null) {
I specifically want to check for `null` and `undefined`, left a comment

2019-06-10 15:49 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +      ngDevMode && assertNotEqual(viewRootTNodeType, TNodeType.View, 'Unexpected TNodeType.View');
fixed

2019-06-10 15:49 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> + * `applyContainer` performs operation on the container and its views as specified by `action`
fixed

2019-06-10 15:49 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> + * @param lView The LView which needs to be inserted, detached, destroyed.
fixed

2019-06-14 03:10 UTC, kara requested changes
Yay, already looks so much easier to follow!  Some comments below

2019-06-14 03:10 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> +      executeNodeAction(action, renderer, renderParent, node, beforeNode);
What if a projected node is an ng-container? Doesn't seem like we handle that case?

2019-06-21 08:29 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> + * code is complicated enough that trying to implemented with recursion becomes unmaintainable.
Reworded this part of the comment.

2019-06-21 08:50 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +    // If they are we need to process the second anchor as well.
I think that this is generally the case when asking for a `ViewContainerRef` on any element other than `<ng-template>` / `<ng-container>` (those are already represented as comment nodes in the DOM). This is _exactly_ what I was getting at [in my doc](https://docs.google.com/document/d/1X5hH828uVmtJWLyi7txmyi98ETGEstZf8ANDOYajMi4/edit#heading=h.m0c2g3ussi36).

2019-06-21 10:28 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +      executeNodeAction(action, renderer, renderParent, node, beforeNode);
Yep, this is a missing case for which we don't have any unit test. Adding a test and fixing.

2019-06-21 10:29 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +                       elementContainerRootTNode, TNodeType.Element, TNodeType.Container);
Yep, this is a missing case for which we don't seem to have any test... Adding a test and fixing.

2019-06-21 14:23 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +      executeNodeAction(action, renderer, renderParent, node, beforeNode);
On top of this we are missing a case here of a projection node being part of projection (re-projection case). Adding a test and fix for this one as well.

2019-06-21 16:27 UTC, jelbourn commented on packages/core/src/render3/node_manipulation.ts
> + * `applyView` performs operation on the view as specified in `action` (insert, detach, destroy)
Function descriptions are typically written like:
"Performs the specified `action` (insert, detach, destroy) on the given view."

(similar for other functions)

2019-06-21 16:27 UTC, jelbourn commented on packages/core/src/render3/node_manipulation.ts
> + * code is complicated enough that trying to implemented with recursion becomes unmaintainable.
nit: this comment block is more conversational than authoritative, I would reword a bit like
```
For insertion *without* either projection or containers, we simply iterate over the root nodes
and perform the `action` on each.

With containers or projection, we're dealing with constructs that have their _own_
containers or further projection. While a recursion solution incurs some performance
trade-offs [citation needed], this approach makes the code significantly more maintainable.
```

2019-06-21 16:27 UTC, jelbourn commented on packages/core/src/render3/node_manipulation.ts
> +  let viewRootTNode: TNode|null = tView.node !.child;  // Why is this not `tView.firstChild`???;
Resolve this comment?

2019-06-21 16:27 UTC, jelbourn commented on packages/core/src/render3/node_manipulation.ts
> +function applyView(
`applyViewAction` or `appyActionToView`?

2019-06-24 15:34 UTC, pkozlowski-opensource commented
Closing in favour of #31182

2019-06-24 15:34 UTC, closed without merging