docs: add cross-platform support to the schematics for libraries guide
angular/angular pull request #30966
Opened 2019-06-11 03:30 UTC by DustinMEastway

Add Windows friendly commands for copying schematics into the library.

Fixes #29952

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The [schematics for libraries guide](https://angular.io/guide/schematics-for-libraries) uses the `cp` command to copy schematics into the library's output directory (in the `package.json` file). The `cp` command is not a valid command in Windows cmd.exe and will throw an error it the scripts are executed.
Issue Number: 29952

## What is the new behavior?
Additional documentation explains that Windows users should use the `copy` command or look into a cross-platform solution such as [ncp](https://www.npmjs.com/package/ncp).

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
This fix is similar to the #30018 pull request, however it adds a reference to the Linux subsystem for Windows 10 (per recommendation by @Splaktar in #29952).

2019-06-11 03:32 UTC, DustinMEastway commented
@kapunahelewong, @Splaktar this is the new pull request for issue #29952. Let me know if you see anything that you think needs to be changed.

2019-06-12 16:00 UTC, kapunahelewong requested changes
Thank you so much for this, @DustinMEastway ✨Just a couple of easy edit recommendations. 🙂

2019-06-12 19:06 UTC, jbogarthyde commented on aio/content/guide/schematics-for-libraries.md
> +**Note** For Windows users, replace the `cp` command with `copy`, use the Linux subsystem for Windows 10, or use a cross-platform solution like [ncp](https://www.npmjs.com/package/ncp).
Yes to both suggestions. You don't need **Note** if you use the div. Might be better to use 
`<div class="callout is-important">
<header>Windows users</header>
For a Windows system, replace the `cp` command with `copy`.
Alternatively, you can use the Linux subsystem for Windows 10, or a cross-platform solution such as [ncp](https://www.npmjs.com/package/ncp).


...your note...

</div>

2019-06-13 00:43 UTC, DustinMEastway commented on aio/content/guide/schematics-for-libraries.md
> +**Note** For Windows users, replace the `cp` command with `copy`, use the Linux subsystem for Windows 10, or use a cross-platform solution like [ncp](https://www.npmjs.com/package/ncp).
I have have made the suggested changes and updated the pull-request.

2019-06-13 11:39 UTC, kapunahelewong approved these changes
LGTM

2019-07-14 19:55 UTC, Splaktar approved these changes

2019-07-14 19:57 UTC, Splaktar commented
It would be nice, if you could squash the commits into a single commit, as 3 commits for a small change like this is a bit much. If you need some tips on how to squash the changes and force push them up to your branch, please ask.

2019-07-26 00:50 UTC, DustinMEastway commented
@Splaktar I have squashed the changes into a single commit. Let me know if you need anything else.

2019-07-26 01:25 UTC, jbogarthyde approved these changes
LGTM

2019-07-26 10:28 UTC, gkalpak requested changes
Sorry, but afaict neither `copy` nor `ncp` are drop-in replacements for `cp` in the example scripts. We should either provide full commands or find another way around (e.g. define a simple script that does the copying).

2019-07-26 11:44 UTC, alan-agius4 commented
Maybe we should point out to use `cpx`, though that's an additional external dependency.

2019-09-28 11:08 UTC, santoshyadav198613 commented on aio/content/guide/schematics-for-libraries.md
> +For a Windows system, replace the `cp` command with `copy`.
I am using https://www.npmjs.com/package/copyfiles and lot of projects already use this one, so rather than alternate, we can give this package as single options.

2019-09-28 15:20 UTC, alan-agius4 commented on aio/content/guide/schematics-for-libraries.md
> +For a Windows system, replace the `cp` command with `copy`.
I do agree that we should provide a single option that works on all platforms.

If I recall correctly sometime ago @gkalpak commented/suggested something around this topic.

2019-10-08 03:04 UTC, DustinMEastway commented on aio/content/guide/schematics-for-libraries.md
> +For a Windows system, replace the `cp` command with `copy`.
@santoshyadav198613 I played around with the `copyfiles` package tonight and it looks like I can flatten the copied files (with the `-f` option) which I believe to be what we want, however it does not appear to have an equivalent to the `-p` option which preserves things like permissions. This option is used in the below command; does anyone have any objections to me removing it?
`"copy:files": "cp --parents -p schematics/*/files/** ../../dist/my-lib/",`

2019-10-10 19:23 UTC, Splaktar commented on aio/content/guide/schematics-for-libraries.md
> +For a Windows system, replace the `cp` command with `copy`.
@DustinMEastway where is that `copy:files` script from?

2019-10-10 19:28 UTC, Splaktar commented on aio/content/guide/schematics-for-libraries.md
> +For a Windows system, replace the `cp` command with `copy`.
Ah, it's part of the example code in `projects/my-lib/package.json`. I guess that option is there to keep executable files with the executable permission? Is that lost with `copyfiles`? How does a file's permissions change in that case?

2021-04-15 18:20 UTC, gkalpak commented on aio/content/guide/schematics-for-libraries.md
> +For a Windows system, replace the `cp` command with `copy`.
It sounds like there is no great way of making this cross-platform compatible.
In that case, I believe mentioning a Windows compatible command in the docs is OK, as long as it is clear what command exactly to use on Windows.

@DustinMEastway, would you be interested in updating this PR with such a mention?

2021-04-16 04:25 UTC, DustinMEastway commented on aio/content/guide/schematics-for-libraries.md
> +For a Windows system, replace the `cp` command with `copy`.
@gkalpak I started researching which commands to use to make my Windows machine match my Mac's behavior and realized that the current scripts do not work on Mac either.

Turns out the `--parents` flag is not supported by many Unix based operating systems according to [this answer on Stack Overflow](https://stackoverflow.com/a/793867) so we should probably move away from it.

While testing I created a new npm script called `copy` that the other `copy:*` scripts call, so I did not have to repeat logic.

# Solution 1
The first solution I tried was just an npm script that could be swapped out for Windows.

I realized Unix systems would need a `mkdir -p` followed by `cp`. Npm can only pass parameters to the end of scripts, so I needed to use a function to pass a parameter to `mkdir` in the middle:
```
"copy": "func() { mkdir -p \"$(dirname $2)\"; cp \"$1\" \"$2\"; }; func"
```

I thought that using [xcopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy) would make the Windows version easy, but it does not appear to support wildcards in the directory part of the sources. Other than directing users to use the Linux subsystem; I am not sure how we can match the behavior using npm scripts on Windows.

# Solution 2: Script Solution
My second thought was to use a Node.JS script that the npm script runs.

The `copy` npm script looks like this and it is cross-platform:
```
"copy": "node copy.js",
```

Then a `copy.js` file would need to be added. I started with something like this, but it will need to be refined if we want to go this route, because wildcards in source directories still does not appear to work with `copyFile` on Windows. I am willing to put some more time into this to figure out how to search, then copy files if you want to go this route, but I want the okay to add this file prior to dumping more time into it.
```js
// This script is used as a cross platform way to copy from a source to a destination
const { copyFile, mkdir } = require('fs');
const { dirname } = require('path');

const source = process.argv[2];
const destination = process.argv[3];

// create the destination directory.
mkdir(dirname(destination), { recursive: true }, () => {
	// copy the source files/directories into the destination.
	copyFile(source, destination, () => {
		// intentionally left blank.
	});
});
```

2021-04-17 16:31 UTC, gkalpak commented on aio/content/guide/schematics-for-libraries.md
> +For a Windows system, replace the `cp` command with `copy`.
Thx for looking into this, @DustinMEastway :+1:
Comments below 👇 

##
> Turns out the --parents flag is not supported by many Unix based operating systems according to [this answer on Stack Overflow][1] so we should probably move away from it.

AFAICT, the SO answer you mentioned refers to `mkdir --parents`. Here, we are using `cp --parents`, which is different. Also, while getting rid of it is an option, it would make the commands (or script) much more verbode.

##
TBH, I am not thrilled about either option (using a complex npm script for Windows or using a Node.js scripts that would be somewhat complicated). So, I played around briefly with the [copyfiles][2] package (suggested by @santoshyadavdev in https://github.com/angular/angular/pull/30966/files#r329306610) and it sounds like it might work for us. While it doesn't have an explicit `--parents` option, that seems to be the default behavior. As for the `-p` option (as mentioned by @Splaktar in https://github.com/angular/angular/pull/30966/files#r333696865) it is only needed for preserving "executability", which again seems to be preserved by `copyfiles` anyway.

Could you play around with `copyfiles` and confirm that it works for you as well (for example, I haven't tested on macOS)?

[1]: https://stackoverflow.com/a/793867
[2]: https://www.npmjs.com/package/copyfiles

2021-04-22 04:29 UTC, DustinMEastway commented on aio/content/guide/schematics-for-libraries.md
> +For a Windows system, replace the `cp` command with `copy`.
Alright, I think I have [copyfiles](https://www.npmjs.com/package/copyfiles) working on MacOS & Windows so long as we are okay with telling Windows users to swap forward slashes out for backslashes in the npm scripts (let me know if this is good and I will create a PR with the below changes). Sorry for writing you a book every time, but it ended up taking a few steps to get it working.

## Installing copyfiles
I had to update the `karma` dependency to `"~5.2.0` to get `npm i` to work because `@angular-devkit/build-angular@0.1102.9` has a dependency of `karma@"^5.2.0 || ^6.0.0"`.
https://github.com/angular/angular/blob/a4a55f0687cc3940fa362ced69d2d8c6feaadd5e/aio/tools/examples/shared/package.json#L70

I added a dev dependency of `copyfiles` version `^2.4.1` to the main `package.json` (not the inner library one). Are we alright with me adding that to the shared `package.json` file?

## Fixing the TypeScript Build
TypeScript threw three errors when I ran `npm run build`.

### Error 1
```bash
schematics/my-service/index.ts:39:7 - error TS2322: Type 'string | number | boolean | JsonArray | JsonObject | null | undefined' is not assignable to type 'string | undefined'.
```
I fixed this by updating [the condition](https://github.com/angular/angular/blob/a4a55f0687cc3940fa362ced69d2d8c6feaadd5e/aio/content/examples/schematics-for-libraries/projects/my-lib/schematics/my-service/index.ts#L45) to check the type prior to setting it.
```diff
-    if (!options.project) {
+    if (!options.project && typeof workspace.extensions.defaultProject === 'string') {
       options.project = workspace.extensions.defaultProject;
     }
```

### Error 2
```bash
schematics/my-service/index.ts:42:44 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
```
I fixed this by adding a null check before [the method is called](https://github.com/angular/angular/blob/a4a55f0687cc3940fa362ced69d2d8c6feaadd5e/aio/content/examples/schematics-for-libraries/projects/my-lib/schematics/my-service/index.ts#L50).
```diff
-    const project = workspace.projects.get(options.project);
+    const project = (options.project != null) ? workspace.projects.get(options.project) : null;
```

### Error 3
```bash
schematics/ng-add/index.ts:5:23 - error TS6133: 'options' is declared but its value is never read.
```
I fixed this by adding an underscore to the parameter when [it is declared](https://github.com/angular/angular/blob/a4a55f0687cc3940fa362ced69d2d8c6feaadd5e/aio/content/examples/schematics-for-libraries/projects/my-lib/schematics/ng-add/index.ts#L5) to denote that it does not get used (not sure if it would be better to just remove it altogether).
```diff
-export function ngAdd(options: any): Rule {
+export function ngAdd(_options: any): Rule {
```

## Updating the Scripts
I swapped out the use of `cp` for `../../node_modules/.bin/copyfiles` to match [the build script](https://github.com/angular/angular/blob/a4a55f0687cc3940fa362ced69d2d8c6feaadd5e/aio/content/examples/schematics-for-libraries/projects/my-lib/package.json#L8).

I also had to replace the destination of [the copy:collection script](https://github.com/angular/angular/blob/a4a55f0687cc3940fa362ced69d2d8c6feaadd5e/aio/content/examples/schematics-for-libraries/projects/my-lib/package.json#L11) to move the file how you would expect opposed to moving it to `dist/my-lib/schematics/collection.json/schematics/collection.json` (note the double `schematics/collection.json`).
```diff
-    "copy:schemas": "cp --parents schematics/*/schema.json ../../dist/my-lib/",
-    "copy:files": "cp --parents -p schematics/*/files/** ../../dist/my-lib/",
-    "copy:collection": "cp schematics/collection.json ../../dist/my-lib/schematics/collection.json",
+    "copy:schemas": "../../node_modules/.bin/copyfiles schematics/*/schema.json ../../dist/my-lib/",
+    "copy:files": "../../node_modules/.bin/copyfiles schematics/*/files/** ../../dist/my-lib/",
+    "copy:collection": "../../node_modules/.bin/copyfiles schematics/collection.json ../../dist/my-lib/",
```

To get this working on Windows, I just had to swap the direction of the slashes and escape the backslashes.
```diff
-    "build": "../../node_modules/.bin/tsc -p tsconfig.schematics.json",
-    "copy:schemas": "../../node_modules/.bin/copyfiles schematics/*/schema.json ../../dist/my-lib/",
-    "copy:files": "../../node_modules/.bin/copyfiles schematics/*/files/** ../../dist/my-lib/",
-    "copy:collection": "../../node_modules/.bin/copyfiles schematics/collection.json ../../dist/my-lib/",
+    "build": "..\\..\\node_modules\\.bin\\tsc -p tsconfig.schematics.json",
+    "copy:schemas": "..\\..\\node_modules\\.bin\\copyfiles schematics\\*\\schema.json ..\\..\\dist\\my-lib\\",
+    "copy:files": "..\\..\\node_modules\\.bin\\copyfiles schematics\\*\\files\\** ..\\..\\dist\\my-lib\\",
+    "copy:collection": "..\\..\\node_modules\\.bin\\copyfiles schematics\\collection.json ..\\..\\dist\\my-lib\\",
```

2021-04-23 20:07 UTC, gkalpak commented on aio/content/guide/schematics-for-libraries.md
> +For a Windows system, replace the `cp` command with `copy`.
Thx for looking into this, @DustinMEastway!

The issues with having to update Karma and the TypeScript errors are quite unexpected, because we should be running these on CI with no issue. They also sound unrelated to this PR, so I would rather keep them separate (maybe on a new PR).

The updates to the scripts look good except for the path separator changes for Windows. I don't recall having to make these changes when playing with it and it would be very unexpected. Could you mke the changes to the PR with the forward spashed and met me play with it on Windows.

BTW, have you looked at mersing all `copy:*` commands into one? That would simplify the `package.json` `scripts` nicely.

2021-05-07 04:46 UTC, DustinMEastway commented on aio/content/guide/schematics-for-libraries.md
> +For a Windows system, replace the `cp` command with `copy`.
The `karma` issue appears to be related to the version of `npm` being used. Version `6.14.12` is fine, but version `7.10.0` throws an error. That said, I agree it belongs in a separate PR.

I think I also figured out why we had different behavior with forward slashes in our scripts. After some testing in Windows, I found that `npm` throws an error if the path to `copyfiles` uses forward slashes, but `yarn` corrects them and runs just fine (this hypothesis assumes you use `yarn` of course). It may be worth adding a note for Windows users letting them know that they need to use `yarn` or swap the slashes in the script or the `build` and `postbuild` scripts will fail. If you agree, let me know how to phrase it and I will add it.

I merged all of the `copy:*` commands into one as you requested. I placed result in the `postbuild` script since that is all it does, but let me know if you want it moved back into its own command to make it more clear.

2021-05-19 19:03 UTC, gkalpak commented on aio/content/guide/schematics-for-libraries.md
> +For a Windows system, replace the `cp` command with `copy`.
Oh, I see. You mean the slashes in the executable path. I was referring to the slashes in the `copyfiles` arguments.

This is indeed problematic. (We actually have the same issue with the `build` script trying to invoke `tsc`.)
I played a bit with this and it is quite annoying. I also found out that the library does not build due to typing issues 😱 (Which made me realize that we don't have proper tests set up for this sample to run on CI 😱 😱 😱)

##
Anyway, this is a solution I came up with:
Everything would be better if we tried to work with the package manager instead of around it :smiley:
So, I think we could get rid of the issues by properly installing the necessary packages as `devDependencies`.

Ideally, we should not be installing the dependencies for every library, but I don't think we can get around that entirely. Fortunately, we can mitigate much of the overhead (esp. maintenance) by installing them from the root project's `node_modules/`, which both npm and yarn seem to support atm: 

```json
  "devDependencies": {
    "typescript": "file:../../node_modules/typescript",
    "copyfiles": "file:../../node_modules/copyfiles"
  }
```

(We would also need to add a small paragraph in the guide, explaining what we're doing here.)

WDYT, @DustinMEastway?

##
(BTW, once we've sorted this out, I would be happy to add some tests and set them up to run on CI, but equally happy for you to take it over if you feel like it. LMK :wink:)

2021-10-29 13:15 UTC, gkalpak approved these changes
One minor comment. Otherwise lgtm :tada:
Thx for seeing it through, @DustinMEastway 💯 

(BTW, this will also need a rebase on latest master to make CI happy.)

##
Reviewed-for: global-docs-approvers

2021-10-30 15:36 UTC, DustinMEastway commented on aio/content/guide/schematics-for-libraries.md
> +    * Both the `build` and the `postbuild` scripts require dependencies that are found in their parent directory, they can be installed by running `npm i` prior to running the scripts.
@gkalpak I have rebased, then removed the unused variable that I had added an `_` to the front of (this was needed for a TS error) because the linter was not counting it as camel case. CI still seems somewhat unhappy, but it appears to be unrelated to my changes, so I am not sure what to do. Let me know if there are changes you would recommend.

2021-11-01 17:11 UTC, gkalpak commented on aio/content/guide/schematics-for-libraries.md
> +    * Both the `build` and the `postbuild` scripts require dependencies that are found in their parent directory, they can be installed by running `npm i` prior to running the scripts.
Awesome! Thx, @DustinMEastway :+1:
I'll make sure this is green on CI and ready to be merged 🚀

2021-11-04 18:14 UTC, AndrewKushnir commented
JFYI I've rebased this PR to resolve a merge conflict with the master branch (in the `aio/tools/examples/shared/boilerplate/cli/package.json` file, caused by recent package versions updates). This PR should be ready for merge now.

2021-11-05 16:32 UTC, atscott commented
Updating this to merge to master only since it conflicts with the 13.0.x branch. Please open a new PR that targets that branch if you would like this merged there as well.

2021-11-05 16:33 UTC, atscott commented
This PR was merged into the repository by commit 544c26d779ab36c3e19f409508eba5db5e6554ee.

2021-11-05 16:33 UTC, closed without merging