fix(docs): Remove issue id from comments.
angular/angular pull request #31008
Opened 2019-06-12 18:19 UTC by jaideepghosh

## Description:
In the doc (https://angular.io/api/core/ViewChild#usage-notes) example contains a line of unnecessary comment. In that same way, multiple doc file contains the same. So removing them to improve the readability of the doc.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-06-12 18:26 UTC, santoshyadav198613 commented on packages/benchpress/src/firefox_extension/lib/main.ts
> -  // TODO(issue/24571): remove '!'.
I can see this issue is still open, let's wait for confirmation before we remove this.
https://github.com/angular/angular/issues/24571

2019-06-12 18:30 UTC, jaideepghosh commented on packages/benchpress/src/firefox_extension/lib/main.ts
> -  // TODO(issue/24571): remove '!'.
Okay, but showing a comment in official doc's examples is not recommended. That's why I've created this PR, to remove the comments.

2019-06-12 18:34 UTC, santoshyadav198613 commented on packages/benchpress/src/firefox_extension/lib/main.ts
> -  // TODO(issue/24571): remove '!'.
Yes agreed, but the purpose here is to update the examples as well when the issue gets resolved, so we should not miss it.

2019-06-12 18:47 UTC, jaideepghosh commented on packages/benchpress/src/firefox_extension/lib/main.ts
> -  // TODO(issue/24571): remove '!'.
Agreed, but issue is already created, so once it is resolved, we can work on the required fixes.
Having an issue id in every file is not making the code readable. And specially if it is something related with official docs, then we must focus on it.

2019-06-12 19:13 UTC, Splaktar requested changes
This is related to https://github.com/angular/angular/issues/24571.

https://github.com/angular/angular/issues/24571#issuecomment-404606595 provides guidance on when/if/how the comments and the `!` should be removed. We cannot simply remove all of the comments without resolving whether or not the `!` should remain or the code should be refactored in some other way.

2019-06-21 12:32 UTC, brandonroberts commented
@jaideepghosh thanks for the PR. This should only apply to files under the `packages/examples` folder. The remaining ones in the codebase are to be left untouched.

2019-08-15 14:15 UTC, kapunahelewong commented
@jaideepghosh if you need help with anything, please tag me. Thanks!

2019-10-07 08:51 UTC, petebacondarwin commented
Closing this one as it is not as simple as deleting the comments. We need to address the reason for the `!` in each case and fix appropriately. There should be separate PRs for each block of changes.

2019-10-07 08:51 UTC, closed without merging