Projection cleanup
angular/angular pull request #31065
Opened 2019-06-15 04:45 UTC by mhevery

2019-07-18 13:58 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +  }  // Now link ourselves into the tree.
Revert?

2019-07-18 13:59 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/projection.ts
> +    // TODO(misko): can we do this in a better way?
Is this work that you are still planning to do in this PR?

2019-07-18 13:59 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/projection.ts
> +    // appendProjectedNodes(lView, tProjectionNode, selectorIndex, findComponentView(lView));
Remove?

2019-07-18 14:02 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/projection.ts
> +import {WalkTNodeTreeAction, appendProjectedNodes, applyProjection, getContainerRenderParent, getNativeAnchorNode, getRenderParent} from '../node_manipulation';
`getContainerRenderParent` is imported but doesn't seem to be used. Remove and check if it still need to be exported from node manipulation.

2019-07-18 14:03 UTC, pkozlowski-opensource commented on packages/core/src/debug/debug_node.ts
> +import {RNode} from '../render3/interfaces/renderer';
Strange that the only change in this file is an import, doesn't seem like it is used?

2019-07-18 14:06 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +    if (beforeNode == null) {
I think I find it easier to read when written like so:

```
if (parent !== null) {
	if (beforeNode != null) {
		nativeInsertBefore(renderer, parent, rNode, beforeNode);
	} else {
		nativeAppendChild(renderer, parent, rNode);
	}
}
```

2019-07-18 14:10 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +  if (beforeNode != null) {
Not sure why this change is needed, I like explicitness of the existing code. As the very minimum we should adjust type to include `undefined` it if can be passed here.

2019-07-18 14:12 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +function applyNodes(
Please document intention of this function, the name is very generic

2019-07-18 14:12 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +        throw new Error('todo implemented');
Turn it into the `ngDevMode` assertion.

2019-07-18 14:13 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +    const node = lView[tNode.index];
`node` -> `rNode` or `nativeNode`?

2019-07-18 14:14 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> + * @param renderer Render to use
Revert?

2019-07-18 14:17 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +function applyHostProjection(
Could you please document this function? Also, I'm not how "host" made it to the function name, we are dealing with projectable nodes passed during dynamic component creation here, right?

2019-07-18 14:18 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> -/**
Why do we remove documentation? Is it the case of a bad rebase?

2019-07-18 14:19 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> -  // - container's host node (this is done here)
Why remove this comment?

2019-07-18 14:20 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +    // This is very strange to me (Misko). I would expect that the native is same as anchor. I don't
The comment above (strangely removed in this PR) documents why those are different. Could we please:
- keep the comment above (refine if needed)
- remove his comment here.

2019-07-18 14:20 UTC, pkozlowski-opensource commented on packages/core/src/render3/util/view_traversal_utils.ts
> + * Given an `LView` find the closest declaration view which is not and embedded view.
Revert? Doesn't sound like a good change?

2019-07-18 18:20 UTC, mhevery commented on packages/core/src/debug/debug_node.ts
> +import {RNode} from '../render3/interfaces/renderer';
removed

2019-07-18 18:21 UTC, mhevery commented on packages/core/src/render3/instructions/projection.ts
> +import {WalkTNodeTreeAction, appendProjectedNodes, applyProjection, getContainerRenderParent, getNativeAnchorNode, getRenderParent} from '../node_manipulation';
removed

2019-07-18 23:36 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +    // This is very strange to me (Misko). I would expect that the native is same as anchor. I don't
Yes merge error. fixed.

2019-07-18 23:36 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +function applyNodes(
Yes name is very generic. Open to better name if you can suggest one.

2019-07-18 23:36 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +function applyHostProjection(
refactored and added comments to be better explain

2019-08-13 00:13 UTC, AndrewKushnir commented
- [VE Presubmit](http://test/OCL:263037365:BASE:263037383:1565655085451:e13da85c)
- [Ivy Presubmit](http://test/OCL:263037365:BASE:263037630:1565655181408:4aaa5069)

2019-08-13 22:01 UTC, AndrewKushnir commented
- [VE Presubmit #2](http://test/OCL:263222512:BASE:263222532:1565733600695:e1de661b)
- [Ivy Presubmit #2](http://test/OCL:263222512:BASE:263222800:1565733675719:3415ca10)

2019-08-13 22:39 UTC, AndrewKushnir commented
@kara @pkozlowski-opensource could you please have another look at the changes, since we added some extra fixes and refactoring? Thank you.

2019-08-14 18:03 UTC, pkozlowski-opensource commented on integration/_payload-limits.json
> +        "main": 13164,
yay!

2019-08-14 18:03 UTC, pkozlowski-opensource commented on packages/core/src/render3/i18n.ts
> +    tNode: TNode, parentTNode: TNode, previousTNode: TNode | null, lView: LView): TNode {
👍

2019-08-14 18:12 UTC, pkozlowski-opensource commented
@AndrewKushnir @mhevery I went through this PR again and it LGTM after spending ~1h reading through it. I won't pretend that I went through every single line of change but the broad strokes are perfect (_finally_ we start to unify creation and insert pass). 

I won't have more time to spend on it today so it could another pair of eyes, but yeh, it LGTM from what I can tell.

2019-08-14 23:55 UTC, AndrewKushnir commented
FYI, VE and Ivy presubmits look normal.

2019-08-16 17:53 UTC, kara requested changes
Really like the direction of the PR (and the code size savings!). Some minor comments/ questions below.

2019-08-16 17:53 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> +    // This should not exist, it is a bit of a hack. When we bootstrap to level node and we
```suggestion
    // This should not exist, it is a bit of a hack. When we bootstrap a top level node and we
```

2019-08-16 17:53 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> +    // need to support passing projectable nodes. Se we cheat and put them in the TNode
```suggestion
    // need to support passing projectable nodes, we cheat and put them in the TNode
```

2019-08-16 17:53 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> + * complication is that those nodes themselves could be re-projected from its parent component.
Revert? Think `their` is correct

```suggestion
 * complication is that those nodes themselves could be re-projected from their parent component.
```

2019-08-16 17:53 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> +    const nativeNode = lView[tNode.index];
Since this value can be a component LView or LContainer, seems like we should rename this var?
```suggestion
    const rawSlotValue = lView[tNode.index];
```

2019-08-16 17:53 UTC, kara commented on packages/core/src/render3/node_manipulation.ts
> +        nativeNode && attachPatchData(nativeNode, lView);
Seems like this wouldn't be right if `nativeNode` was a component LView or LContainer. Should we unwrap it here? Is there a test for this?

2019-08-16 19:04 UTC, AndrewKushnir commented
@kara Thanks for the comments!

I've pushed a [fixup commit](https://github.com/angular/angular/pull/31065/commits/c99b0afc4f46b6c641c9583ca7a878705843524b) to address Kara's comments. @kara @mhevery could you please have a look?

Thank you.

2019-08-19 14:28 UTC, kara approved these changes
LGTM

2019-08-19 14:34 UTC, kara commented
[VE presubmit](https://test.corp.google.com/ui#id=OCL:264152024:BASE:264152027:1566225080878:ed4f57e5)

[Ivy presubmit](https://test.corp.google.com/ui#id=OCL:264152024:BASE:264152262:1566225167520:e800e93e)

2019-08-19 15:48 UTC, kara commented
merge-assistance: global approval

2019-08-19 17:12 UTC, closed without merging