Feat/add ng submitted
angular/angular pull request #31070
Opened 2019-06-15 14:40 UTC by edwandr

Add ng-submitted class to form controls when parent form has been submitted

Fixes #30486

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

No class is added to form controls and container when parent form is submitted

Issue Number: 30486

## What is the new behavior?

When parent form is submitted (if there is a parent form), form controls get `ng-submitted` class

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

Constructor arguments of `NgControlStatus` have changed : we added one optional injected argument `controlContainer`

## Other information

Would it be better to add `submitted` property to `Form` interface (which `NgForm` and `FormGroupDirective` implement) ?

This would avoid the imports of these to directives in `ng_control_status.ts`. I'm afraid that importing them could increase bundle size.

2019-06-15 14:40 UTC, edwandr commented
I signed it!

2019-06-15 14:50 UTC, cexbrayat commented
Note to the team: this is a first time contributor, contributing to Angular during the [HackCommitPush](http://hack-commit-pu.sh/) conference, which aims to help developers to contribute to open source projects :)

2019-06-20 18:38 UTC, jasonaden commented
[Presubmit](http://test/OCL:254239287:BASE:254239351:1561055900418:f036b017)

2019-06-27 23:00 UTC, jasonaden requested changes
Overall this looks good. Just a couple notes. Thanks for the submission!

2019-07-22 16:56 UTC, mhevery commented
@edwandr can you clean up.

2019-07-29 08:53 UTC, edwandr reviewed
@jasonaden Thanks for the feedbacks ! 
@mhevery I'll clean up in the week

2019-08-09 20:56 UTC, edwandr reviewed
@jasonaden i added the optional type for controlContainer argument

2020-01-06 13:17 UTC, edwandr commented
@mhevery @jasonaden Hi, happy new year ! Are the modifications i pushed ok for you ?

2021-05-06 16:26 UTC, AndrewKushnir commented
(just for additional context: related issue #30486)

2021-05-07 01:39 UTC, AndrewKushnir requested changes
Hi @edwandr, thanks for submitting this PR and sorry that we didn't have a chance to get back to it sooner.

I've reviewed the changes and I think that we should simplify the changes and support the `ng-submitted` class **only** for the classes that actually have this status, i.e. `NgForm` and `FormGroupDirective` (the directives that can represent the top-level form). Other form elements (like `<input>`s) would be able to use the top-level form's status to set specific styling if needed (for ex.: `.ng-submitted input { font-size: 10px; }`).

Please let us know if you might be interested in making additional changes in this PR.

Thank you.

2021-05-18 22:16 UTC, AndrewKushnir commented
Closing this PR, new PR - #42132.

2021-05-18 22:16 UTC, closed without merging