Added src/app/mock-heroes.ts
angular/angular pull request #31080
Opened 2019-06-16 17:37 UTC by mrenrich84

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-06-16 17:44 UTC, mrenrich84 commented
I signed it!

2019-06-17 13:54 UTC, mary-poppins commented
You can preview ad64bd8 at https://pr31080-ad64bd8.ngbuilds.io/.

2019-06-17 13:58 UTC, brandonroberts requested changes
Remove the `(docs-infra)` scope from the git commit message

2019-06-17 13:58 UTC, brandonroberts commented on aio/content/tutorial/toh-pt2.md
> +  <code-pane header="src/app/mock-heroes.ts" path="toh-pt2/src/app/mock-heroes.ts">
Put a single line break before and after the `code-pane`

2019-06-17 14:40 UTC, mary-poppins commented
You can preview c208391 at https://pr31080-c208391.ngbuilds.io/.

2019-06-17 14:49 UTC, mary-poppins commented
You can preview 43564c3 at https://pr31080-43564c3.ngbuilds.io/.

2019-06-17 17:16 UTC, brandonroberts commented
@mrenrich84 this [git commit message](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#subject) should in present tense. Update to `docs: add mock heroes to the code review tabs for TOH pt. 2`

2019-06-17 17:59 UTC, mary-poppins commented
You can preview d31fef4 at https://pr31080-d31fef4.ngbuilds.io/.

2019-06-17 18:22 UTC, brandonroberts approved these changes

2019-06-17 18:23 UTC, brandonroberts commented
Caretaker note: integration_test failure is unrelated

2019-06-17 23:36 UTC, closed without merging