refactor(compiler): allow parsing templates with custom leadingTriviaChars
angular/angular pull request #31136
Opened 2019-06-19 15:45 UTC by ayazhafiz

Move the definition leadingTriviaChars included in parsing a template
to the parameters of parseTemplate. This allows overriding of the
default leadingTriviaChars, which is needed by some pipelines like the
indexing pipeline because leadingTriviaChars may throw off the recorded
span of selectors.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
  - N/A
- [x] Docs have been added / updated (for bug fixes / features)
  - N/A

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Templates are always parsed with the same `leadingTriviaChars` - whitespace characters.

Issue Number: N/A

## What is the new behavior?

Templates are parsed with whitespace `leadingTriviaChars` by default, but this can be overridden. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-06-19 16:01 UTC, petebacondarwin submitted a review, later dismissed
Can we add this to the `ParseTemplateOptions` interface instead of adding a new parameter?

2019-06-19 16:09 UTC, ayazhafiz commented
> Can we add this to the `ParseTemplateOptions` interface instead of adding a new parameter?

Yep, this works. We'll have to modify the component decorator.

2019-06-19 16:26 UTC, alxhub requested changes

2019-06-19 16:26 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +          leadingTriviaChars: WHITESPACE_LEADING_TRIVIA_CHARS,
Rather than move this constant to the consumer, let's make it the default value in `parseTemplate` as it is today.

2019-06-19 16:26 UTC, alxhub commented on packages/compiler/src/render3/view/template.ts
> +      htmlParser.parse(template, templateUrl, {...options, tokenizeExpansionForms: true});
To make it a default value here you can use a neat technique:

```suggestion
      htmlParser.parse(template, templateUrl, {leadingTriviaChars: LEADING_TRIVIA_CHARS, ...options, tokenizeExpansionForms: true});
```

Including it before `...options` means the value will be used if `options` doesn't override it. This makes `parseTemplate` more useful by itself (especially in tests) as users won't have to remember to configure it to behave exactly as it does when called from the real compiler.

2019-06-19 16:50 UTC, ayazhafiz commented on packages/compiler/src/render3/view/template.ts
> +      htmlParser.parse(template, templateUrl, {...options, tokenizeExpansionForms: true});
That's a lot nicer, you're right. Thanks!

2019-06-19 18:25 UTC, alxhub approved these changes

2019-06-19 21:08 UTC, AndrewKushnir commented on packages/compiler/src/render3/view/template.ts
> + * An array of characters that should be considered as leading trivia.
nit: formatting issue

2019-06-20 07:11 UTC, petebacondarwin approved these changes

2019-06-20 18:15 UTC, closed without merging