feat(ivy): integrate indexing pipeline with NgtscProgram
angular/angular pull request #31151
Opened 2019-06-20 00:28 UTC by ayazhafiz

Add an IndexingContext class to store indexing information and a
transformer module to generate indexing analysis. Integrate the indexing
module with the rest of NgtscProgram and add integration tests.

Closes #30959

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
  - N/A, limited compiler API

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Indexing module is standalone, not integrated with the compiler.

Issue Number: #30959 

## What is the new behavior?

Integrates the indexing module with all of `NgtscProgram`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-06-20 00:29 UTC, ayazhafiz commented
Waiting on #31136 to merge.

2019-06-20 18:42 UTC, alxhub requested changes

2019-06-20 18:42 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +    if (ast.receiver instanceof ImplicitReceiver) {
Instead of nesting here, do an early return if the receiver is not an `ImplicitReceiver`.

2019-06-20 18:42 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +      const identifierStart = ast.span.start + localExpression.indexOf(ast.name);
👏 this is a really clean solution, nice work!

2019-06-20 18:42 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    const template = analysis.parseTemplate({
Add a comment explaining _why_ re-parsing the template is necessary.

2019-06-20 19:10 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    let parseTemplate: (options?: ParseTemplateOptions) => ParsedTemplate;
I thought I had this but I guess not. Moved the second half of the suggested comment to where `parseTemplate` is instantiated inside the preanalyze block.

2019-06-21 16:43 UTC, alxhub requested changes

2019-06-21 16:43 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +import {ParseTemplateOptions} from '@angular/compiler/src/render3/view/template';
Should be top-level import.

2019-06-21 16:43 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +  parseTemplate(options?: ParseTemplateOptions): ParsedTemplate;
```suggestion
  parseTemplate: (options?: ParseTemplateOptions) => ParsedTemplate;
```

To me, the former implies that `parseTemplate` is a method on `ComponentHandlerData`, whereas the latter more means that the field holds a closure we can call that's otherwise independent of `ComponentHandlerData`.

2019-06-21 16:43 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/context.ts
> +  scope: BoundTarget<ComponentMeta>|null;
I'm not sure what "registry of the component" means in this context. I think we're confusing two concepts here.

A component has a "scope" if it's declared inside an NgModule. Then it has other components/directives/etc. which might be used in its template. Sometimes components don't have an associated NgModule, and thus they have no scope.

The `BoundTarget` however should always exist - it's just sometimes, there are no directives/components to add to the `SelectorMatcher` used to create it - a component without a scope has effectively an "empty" scope. So this shouldn't be `null`able, and we should adjust the logic accordingly.

2019-06-21 16:43 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +  private addIdentifier(ast: AST&{name: string, receiver: AST}, kind: IdentifierKind) {
Maybe rename this method `visitIdentifier` or `maybeAddIdentifier`. Currently it has a name which declares it always does work, but really it also has the job of considering whether to add the identifier or not.

2019-06-21 16:43 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +    }
I think there's a bug in `ExpressionVisitor` (maybe not in this method). Consider the template:

```html
<input ngModel #model="ngModel">
{{model.valid}}
```

Here the `#model` reference defines a reference to the `NgModel` directive on the `<input>`, _not_ a property of the component itself. So the expression `{{model.valid}}` will generate an AST of `PropertyRead(PropertyRead(ImplicitReceiver, 'model'), 'valid')`. This will look to the `ExpressionVisitor` currently like `model` is a property of the component, since it will hone in on the `PropertyRead(ImplicitReceiver)` and add this as an `IdentifierKind.Property` identifier. Really it's not, it's a different kind of identifier entirely.

Another example:

```html
<user-view *ngFor="let user of users" [data]="user"></user-view>
```

Here `in [data]="user"`, the `user` expression (`PropertyRead(ImplicitReceiver, 'user')`) is a variable of the child template created by `*ngFor` and also not a property on the component instance.

The trick here is to use the `BoundTarget.getExpressionTarget` method to check if the `PropertyRead` `AST` has a target within the template. It'll return `null` if the expression is pointing at the component itself.

Does that make sense?

2019-06-21 16:43 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/test/context_spec.ts
> +import {ParseSourceFile, R3TargetBinder, SelectorMatcher} from '@angular/compiler/src/compiler';
`@angular/compiler`.

2019-06-21 17:34 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +    }
Yeah, that makes sense. I’ll implement the BoundTarget trick; thanks for that tip!

Bugs like this are also fairly benign, though, in terms of their effect on indexing a source code. Working with a language analysis tool like Kythe, I’ve learned that the typical philosophy is to worry more about not crashing the the indexer than emitting correct entries. That is, we should totally strive to extract identifiers correctly, but pointing references to something that doesn’t actually exist or is the incorrect reference is not catastrophic, it’s just best-effort. Especially since the TypeScript code identifiers are not indexed, some references can _only_ be best-effort.

2019-06-21 17:54 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +  parseTemplate(options?: ParseTemplateOptions): ParsedTemplate;
I agree. Interesting; for a while I thought the former was syntactic sugar for the latter, but the latter is much more indicative of a stateful closure. Thanks!

2019-06-21 17:57 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +  private addIdentifier(ast: AST&{name: string, receiver: AST}, kind: IdentifierKind) {
Changed to `visitExpression`, which is what it's really doing.

2019-06-21 19:43 UTC, alxhub requested changes

2019-06-21 19:43 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +   * Visits an identifier, adding it to the identifier store if it is useful for indexing.
Generally for readability, there should be an empty line between the docstring and the jsdoc comments. Can you add this throughout?

2019-06-21 19:43 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +  const boundTemplate = new R3TargetBinder(new SelectorMatcher()).bind({template});
You already pass in a `BoundTemplate` as part of the `ComponentInfo`. We should use that one.

2019-06-21 20:11 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +  const boundTemplate = new R3TargetBinder(new SelectorMatcher()).bind({template});
Ah, you're right. That's much better. Thank you.

2019-06-21 20:15 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/context.ts
> +  scope: BoundTarget<ComponentMeta>|null;
Sorry, I must have missed this earlier. I see what you're saying; I'll update this to be a `boundTemplate`, combining the purpose of the BoundTarget for holding the template and for querying information about directives the template uses.

Thank you for explaining this. Definitely clears up my understanding of what a `BoundTarget` really does.

2019-06-21 22:02 UTC, alxhub approved these changes

2019-06-21 22:02 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +        matcher.addSelectables(CssSelector.parse(selector), directive);
```suggestion
        matcher.addSelectables(CssSelector.parse(directive.selector), directive);
```

Then you don't need the extraction of `selector` to a variable.

2019-06-24 17:35 UTC, ayazhafiz commented
Waiting for g3 sync, have to update internal products to be compatible with this merge first.

2019-06-24 21:48 UTC, ayazhafiz commented
Presubmits
- [ViewEngine](https://test.corp.google.com/ui#id=OCL:254832959:BASE:254832987:1561410843438:4b0a2960)
- [Ivy](https://tap.corp.google.com/ui#id=OCL:254832959:BASE:254840354:1561412900074:6b0289a5)

2019-06-25 01:49 UTC, closed without merging