docs: add correct default cli ngModule
angular/angular pull request #31166
Opened 2019-06-20 16:41 UTC by kapunahelewong

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The current code snippet is from the bootstrapping example, which has extra things like `FormsModule` and `HttpClientModule`. But we just need the default CLI generated `AppModule`.

Issue Number: #21531

## What is the new behavior?
Now has an inline snippet of the default CLI `AppModule`. Since there is no accompanying live example for this guide and it is not leading the reader through building anything, an inline example is ok here.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-06-20 16:48 UTC, mary-poppins commented
You can preview 10140ad at https://pr31166-10140ad.ngbuilds.io/.

2019-06-20 17:56 UTC, brandonroberts requested changes

2019-06-20 17:56 UTC, brandonroberts commented on aio/content/guide/ngmodules.md
> +```ts
This should not be inlined and should come from an example. What about adding an `app.module.1.ts` to the `ngmodules` example?

2019-06-20 18:01 UTC, mary-poppins commented
You can preview 55fad1c at https://pr31166-55fad1c.ngbuilds.io/.

2019-06-21 16:01 UTC, kapunahelewong commented on aio/content/guide/ngmodules.md
> +```ts
Oh thanks. I missed that one. Fixed!

2019-06-21 18:58 UTC, mary-poppins commented
You can preview beadc07 at https://pr31166-beadc07.ngbuilds.io/.

2019-06-21 19:44 UTC, brandonroberts submitted a review, later dismissed

2019-06-21 19:44 UTC, brandonroberts commented on aio/content/guide/ngmodules.md
> +<code-example path="ngmodules/src/app/app.module.1.ts" header="src/app/app.module.1.ts (default AppModule)" linenums="false">	// @NgModule decorator with its metadata
```suggestion
<code-example path="ngmodules/src/app/app.module.1.ts" header="src/app/app.module.ts (default AppModule)" linenums="false">	// @NgModule decorator with its metadata
```

2019-06-25 20:28 UTC, kapunahelewong commented on aio/content/guide/ngmodules.md
> +<code-example path="ngmodules/src/app/app.module.1.ts" header="src/app/app.module.1.ts (default AppModule)" linenums="false">	// @NgModule decorator with its metadata
Done!

2019-06-25 20:37 UTC, mary-poppins commented
You can preview d64e40e at https://pr31166-d64e40e.ngbuilds.io/.

2019-07-02 13:44 UTC, mary-poppins commented
You can preview 4aedfff at https://pr31166-4aedfff.ngbuilds.io/.

2019-07-02 19:59 UTC, mary-poppins commented
You can preview 063924f at https://pr31166-063924f.ngbuilds.io/.

2019-07-02 22:44 UTC, mary-poppins commented
You can preview 435eef6 at https://pr31166-435eef6.ngbuilds.io/.

2019-07-03 13:52 UTC, gkalpak commented on aio/content/examples/ngmodules/src/app/app.module.1.ts
> +// imports
Does this come from the cli? I don't think we do that in other examples.

2019-07-03 13:52 UTC, gkalpak commented on aio/content/examples/ngmodules/src/app/app.module.1.ts
> +export class AppModule {}
Why not reuse regions from `app.module.ts`?

2019-07-03 14:48 UTC, kapunahelewong commented on aio/content/examples/ngmodules/src/app/app.module.1.ts
> +// imports
No, it's pointing it out here specifically since the section is introducing a basic `NgModule` and talks about the imports at the top and then the properties of `@NgModule()`.

2019-07-03 16:06 UTC, kapunahelewong commented on aio/content/examples/ngmodules/src/app/app.module.1.ts
> +export class AppModule {}
Per a Slack conversation, George and I came to the decision to leave this as is because adding the necessary docregions to the `app.module.ts` would get lengthy/complicated. The `app.module.1.ts` doesn't have any logic and only exists as a reference for what the CLI generates. Thank you, @gkalpak!

2019-07-03 16:15 UTC, mary-poppins commented
You can preview 4158c54 at https://pr31166-4158c54.ngbuilds.io/.

2019-07-03 17:34 UTC, gkalpak approved these changes

2019-07-03 17:35 UTC, gkalpak commented
**merge-assistance:** Global approval for this docs-only change.

2019-07-08 17:28 UTC, closed without merging