docs: add note about cli commands
angular/angular pull request #31216
Opened 2019-06-23 10:33 UTC by FrederikSchlemmer

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #31073

## What is the new behavior?
Added a note:

"Learn more: This manual uses StackBlitz Generator for simplification. Take a look at Angular CLI to get an overview of our CLI commands."

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-06-23 10:34 UTC, FrederikSchlemmer commented
@methodbox would like to have feedback from you!

2019-06-24 14:42 UTC, jbogarthyde requested changes
I would make this more substantive,

2019-06-24 14:42 UTC, jbogarthyde commented on aio/content/start/index.md
> +
I think this needs more context, and should happen earlier. Perhaps, near the top:

We are using the StackBlitz Generator to show you a ready-made, simple application that you can examine and play with interactively. In actual development you will typically use the  [Angular CLI](guide/glossary#cli), a powerful command-line tool that lets you generate and modify applications. For more information, see the [CLI Overview](cli).

2019-06-24 15:48 UTC, methodbox commented
@FrederikSchlemmer

I agree with @jbogarthyde. The Angular team that commented on my original post may not agree, however.

It seems their view is that they want to obscure this from the user to avoid confusion.

I say let them know up front.

If the user is that confused by more clarity, it seems to me they may also be confused that StackBlitz is used and think it’s somehow required to use Angular. 

I doubt this is the case.

2019-06-25 07:47 UTC, FrederikSchlemmer commented on aio/content/start/index.md
> +
I've adopted the changes. There was a comment in the issue that it should only be a short note/link, so I only chosed this short note.
But I also prefer the detailed version at the beginning!

2019-06-25 07:48 UTC, FrederikSchlemmer commented
@methodbox I've adopted the changes. As you said, I had implemented the suggestions of the Angular Team from the issue.
In my opinion, this approach now makes more sense.

2019-06-25 13:59 UTC, mary-poppins commented
You can preview f511677 at https://pr31216-f511677.ngbuilds.io/.
You can preview 6d37839 at https://pr31216-6d37839.ngbuilds.io/.

2019-06-25 14:06 UTC, jbogarthyde approved these changes
Some minor editorial changes, then LGTM

2019-06-25 14:06 UTC, jbogarthyde commented on aio/content/start/index.md
Thanks, I think this works.   
I would move it down below the "Create a new project" header, before the "click here".
Also, I think we need to not capitalize "Generator", that doesn't seem to be a specific StackBlitz term.

2019-06-25 18:37 UTC, methodbox commented
Thanks, @mary-poppins!

I think the change is excellent, informative and doesn’t hinder the docs, yet it’s clearly placed in such a way to that it will stand out.

Good job, guys!

2019-06-25 18:47 UTC, brandonroberts approved these changes

2019-06-25 19:00 UTC, closed without merging