Feature/index selectors
angular/angular pull request #31240
Opened 2019-06-24 17:34 UTC by ayazhafiz

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Indexer module does not index the location of element selectors.

Issue Number: N/A

## What is the new behavior?
Index the location of element selectors.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-06-24 17:34 UTC, ayazhafiz commented
Blocked by #31151. Waiting for merge.

2019-06-25 18:44 UTC, alxhub requested changes

2019-06-25 18:44 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +    this.identifiers.add({
Where are we going to convey the information that the element matches some component/directive(s)?

2019-06-25 18:59 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +    this.identifiers.add({
I think that is the job of the actual indexer, not the indexing module inside the compiler. This is especially because every selector is indexed, not the ones that refer to external components.

2019-06-25 19:11 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +import {ParseSourceSpan} from '@angular/compiler/src/compiler';
Done.

2019-06-26 00:51 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +    this.identifiers.add({
Indexed elements now also include their used directives. Marking as resolved.

2019-06-28 23:22 UTC, alxhub requested changes

2019-06-28 23:22 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/api.ts
> +  value: string;
Do we need the `value` of attributes anywhere?

2019-06-28 23:22 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/api.ts
> +  usedDirectives: ts.Declaration[];
The API is starting to look a little strange. Maybe we want to introduce an `Element` type instead? Otherwise it's unclear whether `AttributeIdentifier`s live on the `ElementIdentifier` or on the `IndexedComponent.template.identifiers`.

Also, now there's overlap between `IndexedComponent.template.usedComponents` and `usedDirectives` here. These are also strange fields to have on an `Identifier` which should really only be giving information about the text of the tag name, not the whole element.

2019-06-28 23:34 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/api.ts
> +  value: string;
No, I'll remove it.

2019-06-28 23:40 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/api.ts
> +  usedDirectives: ts.Declaration[];
I agree that the overlap may be a little strange, but it is also appropriate to put information about `usedDirectives` on the element because we have to give information about directives applied to it (the indexer can't determine that without reimplementing `BoundTarget`).

I've been modeling `TemplateIdentifier`s after how TypeScript does `ts.Node`s - there is some base information, like the span and kind, but specialized nodes contain a lot more extra information, like children, arguments, etc. We introduce an `Element` type as you suggest, but I think the pattern would remain the same, just under a different name.

2019-07-01 23:20 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/api.ts
> +  usedDirectives: ts.Declaration[];
Yes, that's what I'm suggesting - an `Element` class that contains information about the element. It'll look very similar to what you already have.

Then:

* `IndexedComponent` will have an `Element[]` array.
* We get rid of `IndexedComponent.identifiers` in favor of fields on the `Element` objects, since each `TemplateIdentifier` is logically owned by an `Element`.
* `Element` gains a `tagName` `TemplateIdentifier` which maps the actual HTML tag.

2019-07-02 00:07 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/api.ts
> +  usedDirectives: ts.Declaration[];
Discussed in person. Resolving.

2019-07-02 01:09 UTC, ayazhafiz commented
Running presubmit now to make sure this introduces no breaking changes.

2019-07-03 20:54 UTC, alxhub requested changes
Otherwise this LGTM.

2019-07-03 20:54 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/api.ts
> +export interface PropertyIdentifier extends TemplateIdentifier { kind: IdentifierKind.Property; }
Doc strings identifying what each of these are.

2019-07-03 20:54 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +    this.identifiers.push({ name: ast.name, span, kind, } as TopLevelIdentifier);
This cast is here because the shape of the object you're creating there is not assignable to `TopLevelIdentifier`, because it won't work if `kind` happens to be `IdentifierKind.Element`.

In reality, this method isn't (and shouldn't) be called to add an `IdentifierKind.Element` identifier. So, instead of casting, let's fix the incoming type of `kind` to only those types which `addIdentifier` is called for.

2019-07-03 20:54 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/api.ts
> +  attributes: Set<AttributeIdentifier>;
Doc strings identifying what these are.

2019-07-03 20:54 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +    const start = sourceSpan.start.offset + sourceSpan.toString().indexOf(name);
Maybe add an assertion to verify this is always found, and not `-1`.

2019-07-03 21:45 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +    this.identifiers.push({ name: ast.name, span, kind, } as TopLevelIdentifier);
Moved to a different identifier type that only uses identifiers that can be created in expression visitors.

Unfortunately, still have to use a cast. This is a limitation of the TypeScript version used in Angular right now; see [this playground](https://www.typescriptlang.org/play/?ts=3.1.6#code/KYOwrgtgBA0gliAJlA3gKCpqAxA9rgGgywCEBDAJzQF800EAXYCgMzIGNgoSTVjMA1gkQAuWMKJYoLfGIDODCggDmAbhp1GzNpxz4owAB5Mkc7iXRShSMfCQA6PIQ30QTVhy7kKB46ERmPHxWwrbC9t5EtGgMAJ4ADlwAglAAvHq4AD7e6mjsuCAKUABGYkkA2gC6aVBV6ixgIOwMcAVQZBAAFNaiUBUA5D39lQCUwVjF9vFgcgAWnag9Yj0EMrgi-WT91CPq1EA) for an example. Switching to 3.5.1 resolves the issue.

2019-07-03 22:02 UTC, alxhub requested changes

2019-07-03 22:02 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +    } as Id);
The cast is definitely not needed if `kind` is typed correctly, even in earlier versions of TS. See [this example](https://www.typescriptlang.org/play/?ts=3.1.6#code/KYOwrgtgBA0gliAJlA3gKCpqAxA9rgGgywCEBDAJzQF800EAXYCgMzIGNgd9VjMBrBIgBcsIQDo8uANw06jZm05RyFXliiCko+EnGrZGgEaVRAZwYUEAc1m00DAJ4AHLgBUAFjagBebrgAfAzp2XBALKBZ8M1FPGwBtAF1fKCTZFjAQdgY4MKgyCAAKLRExPSkASnUsAHoaqAYvMyg4ZrIAG3bcAHdgZA9mLiNgdjIwMy4yEChcIwArEYYobrhGzSEdCSkoUZAQXCXhmZYGly5VIg06qDNcFqXEXGAzEAByJZBgPvyoV5MKV5QZwUXCuChOcR8SLRcTOcYeQqoEqiErUCp2NBAA).

2019-07-12 08:06 UTC, alxhub approved these changes
This LGTM other than the generic - please fix before submitting!

2019-07-12 08:06 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +  private visitIdentifier<Id extends ExpressionIdentifier>(
I don't think `visitIdentifier` needs to be generic. It doesn't use the generic type for anything that you couldn't name a specific type for.

2019-07-12 21:56 UTC, closed without merging