docs: clarify how to do custom two-way bindings
angular/angular pull request #31290
Opened 2019-06-26 16:24 UTC by drmercer

On the "Template Syntax" documentation page, the existing wording doesn't make it clear that the `__Change` syntax is *necessary*, not just an example.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The existing wording doesn't make it clear that the `__Change` syntax is *necessary*, not just an example.

Issue Number: N/A

## What is the new behavior?
It now explicitly states that the `__Change` syntax is what makes the two-way binding happen.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-06-26 18:34 UTC, kapunahelewong requested changes
Hi @drmercer! Thanks so much for this PR. I've left a couple of comments and am also requesting @jbogarthyde, one of our docs team members.

2019-06-26 18:34 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +Two-way binding happens when the `[()]` syntax is used **and** the element has a settable
Try to keep this sentence in the active voice rather than the passive ("is used"). This isn't always easy in tech writing, but we try to stick to it as much as possible.

2019-06-26 18:34 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +(e.g. `xChange`). For example, here's a `SizerComponent` that fits this pattern. It has a
We also try to minimize use of parentheses and use of "e.g." and "i.e." (that is, Latin that may be stumbling blocks for those whose native languages don't include these).

2019-06-26 21:43 UTC, jbogarthyde reviewed
How about this, to explicitly emphasize the need for the change event.

2019-06-26 21:43 UTC, jbogarthyde commented on aio/content/guide/template-syntax.md
> +`size` value property and a companion `sizeChange` event:
How about this: 

Two-way binding requires a settable property that corresponds to a change event. In the following example, the `SizerComponent` defines a `size` value property and a companion `sizeChange` event. The `[()]` syntax in the template ensures that when the value changes in either the component or the control, the new value is reflected in both.

2019-07-10 13:19 UTC, drmercer commented on aio/content/guide/template-syntax.md
> +`size` value property and a companion `sizeChange` event:
Thanks for the feedback!

The purpose of this PR is to make it explicitly clear that the `___Change` naming is required. Because a settable property could correspond to a change event without following the naming scheme (for example, `x` and `xWasJustChanged` are corresponding), I don't think this suggestion is sufficient to communicate the exact nature of the naming scheme.

2019-07-18 16:54 UTC, kapunahelewong commented
Hey @drmercer, when you're ready for another review pass, will you tag me? I'd like to help land this. Thanks again for this!

2020-06-30 11:36 UTC, pkozlowski-opensource commented
I'm going to close this PR for now as we haven't heard back from the PR author. Happy to re-review a new PR (or this one re-opened with the docs team feedback addressed).

2020-06-30 11:36 UTC, closed without merging