fix(ivy): handle modifiedResourceFiles being null on incremental compilation
angular/angular pull request #31322
Opened 2019-06-27 23:27 UTC by mattlewis92

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Incremental compilation fails with ivy:
```
ERROR in Cannot read property 'has' of null
ℹ ｢wdm｣: Failed to compile.
/Users/mattlewis/Code/clickup/frontend/node_modules/@angular/compiler-cli/src/ngtsc/incremental/src/state.js:120
                .some(function (resourcePath) { return _this.modifiedResourceFiles.has(resourcePath); });
                                                                                   ^

TypeError: Cannot read property 'has' of null
    at /Users/mattlewis/Code/clickup/frontend/node_modules/@angular/compiler-cli/src/ngtsc/incremental/src/state.js:120:84
    at Array.some (<anonymous>)
    at IncrementalState.hasChangedResourceDependencies (/Users/mattlewis/Code/clickup/frontend/node_modules/@angular/compiler-cli/src/ngtsc/incremental/src/state.js:120:18)
    at IncrementalState.safeToSkip (/Users/mattlewis/Code/clickup/frontend/node_modules/@angular/compiler-cli/src/ngtsc/incremental/src/state.js:70:57)
    at IvyCompilation.analyze (/Users/mattlewis/Code/clickup/frontend/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:156:39)
    at IvyCompilation.analyzeSync (/Users/mattlewis/Code/clickup/frontend/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:71:76)
    at /Users/mattlewis/Code/clickup/frontend/node_modules/@angular/compiler-cli/src/ngtsc/program.js:257:39
    at Array.forEach (<anonymous>)
    at NgtscProgram.ensureAnalyzed (/Users/mattlewis/Code/clickup/frontend/node_modules/@angular/compiler-cli/src/ngtsc/program.js:255:22)
    at NgtscProgram.getNgSemanticDiagnostics (/Users/mattlewis/Code/clickup/frontend/node_modules/@angular/compiler-cli/src/ngtsc/program.js:167:36)
```

## What is the new behavior?
Incremental compilation works

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
I applied this patch locally and everything worked smoothly after! 😄

2019-06-28 06:16 UTC, alfaproject commented on packages/compiler-cli/src/ngtsc/incremental/src/state.ts
> +    if (this.modifiedResourceFiles === undefined || this.modifiedResourceFiles === null ||
```suggestion
    if (this.modifiedResourceFiles == null ||
```

2019-06-28 06:17 UTC, alfaproject commented on packages/compiler-cli/src/ngtsc/incremental/src/state.ts
> +    if (this.modifiedResourceFiles === undefined || this.modifiedResourceFiles === null ||
The type doesn't even allow for undefined, so I guess you could just check for `null` with triple equals or fix the type if it can really be undefined.

2019-06-28 12:18 UTC, mattlewis92 commented on packages/compiler-cli/src/ngtsc/incremental/src/state.ts
> +    if (this.modifiedResourceFiles === undefined || this.modifiedResourceFiles === null ||
I'm not too sure, I guess that undefined check is there for a reason, let's see what @alxhub / @petebacondarwin say

2019-06-28 12:27 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/incremental/src/state.ts
> +    if (this.modifiedResourceFiles === undefined || this.modifiedResourceFiles === null ||
Ah! This is my mistake. Sorry.

In the original draft of the PR the parameter was optional, which meant that it could be `undefined` or defined (not `null`) but then I made it non-optional and switched to using `null` to indicate that it is explicitly not needed.

So we should be able ditch the `undefined` check in favour of the `null` check.

We should also add tests for this bug.

2019-06-28 12:30 UTC, petebacondarwin requested changes
@mattlewis92 - thanks for catching this.

Please just replace the `=== undefined` with `=== null`.


Do you fancy trying to add a test for this case to https://github.com/angular/angular/blob/master/packages/compiler-cli/test/ngtsc/incremental_spec.ts ?

If not, let me know and I can take over this PR and add the test.

2019-06-28 12:34 UTC, mattlewis92 commented
Yeah sure, I can try writing a test. If I understand the problem right, I can modify this test: https://github.com/angular/angular/blob/master/packages/compiler-cli/test/ngtsc/incremental_spec.ts#L79-L104 but then make a change to `component1.ts` instead and that should trigger the error?

2019-06-28 12:46 UTC, petebacondarwin commented
@mattlewis92 - yes copy the test not modify ;-) and make the change as you suggest. Please check that this will fail before the fix is applied. Get in touch if you have difficulty running the tests or getting it to fail. Thanks!

2019-06-28 13:25 UTC, mattlewis92 commented
@petebacondarwin I'm struggling to get this to fail as I can never get `modifiedResourceFiles` to be `null`, everything I try it always ends up being an empty set. Any ideas?

2019-06-28 13:44 UTC, petebacondarwin commented
😱 do you know what trigger in your project causes the error?

2019-06-28 13:57 UTC, mattlewis92 commented
It was the initial load of the app, before the incremental compilation would have even triggered, which [makes sense actually](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/api.ts#L287).

2019-06-28 14:01 UTC, petebacondarwin commented
But the CLI implementation of that function always returns a `Set<>` not `null` nor `undefined`...
https://github.com/angular/angular-cli/blob/70a4cbe306e50af56e9c41a1b788991abb85687b/packages/ngtools/webpack/src/compiler_host.ts#L358

2019-06-28 14:05 UTC, petebacondarwin commented
And in any case ngcc should convert any falsy value to `null`:

```
    this.modifiedResourceFiles =
        this.host.getModifiedResourceFiles && this.host.getModifiedResourceFiles() || null;
```

2019-06-28 14:08 UTC, petebacondarwin commented
Ahah! The test is at fault. See https://github.com/angular/angular/blob/7186f9c0162601828a0735919eace3a73da47a46/packages/compiler-cli/test/ngtsc/env.ts#L171

`changedResources` is of type `Set<string>|undefined = undefined;`

2019-06-28 14:09 UTC, mattlewis92 commented
> But the CLI implementation of that function always returns a `Set<>` not `null` nor `undefined`...
> [angular/angular-cli:packages/ngtools/webpack/src/compiler_host.ts@`70a4cbe`#L358](https://github.com/angular/angular-cli/blob/70a4cbe306e50af56e9c41a1b788991abb85687b/packages/ngtools/webpack/src/compiler_host.ts#L358)

Ah, I'm using the 8.0.x version of the cli which doesn't have that [method implemented](https://github.com/angular/angular-cli/blob/8.0.x/packages/ngtools/webpack/src/compiler_host.ts) so I guess it falls back to the default one provided by ngtsc, which would return undefined on the first run and then get converted to null by this:

>  this.modifiedResourceFiles =
>         this.host.getModifiedResourceFiles && this.host.getModifiedResourceFiles() || null;

2019-06-28 14:11 UTC, petebacondarwin commented
If we change that param to `null` it will probably fail without any new tests!

2019-06-28 14:13 UTC, petebacondarwin commented
So CLI is doing the right thing (even 8.0.0 version).
And your fix (to test for `null` rather than `undefined`) is correct.
The problem with getting a failing test is that the `driveMain` was not following the `null` type correctly.

2019-06-28 14:30 UTC, mattlewis92 commented
I tried changing it to `null` but the issue is that `enableMultipleCompilations` then initialises it to a new set: https://github.com/angular/angular/blob/7186f9c0162601828a0735919eace3a73da47a46/packages/compiler-cli/test/ngtsc/env.ts#L97 and that's called on every spec run: https://github.com/angular/angular/blob/7186f9c0162601828a0735919eace3a73da47a46/packages/compiler-cli/test/ngtsc/incremental_spec.ts#L22

2019-06-28 14:39 UTC, petebacondarwin commented
I'm just playing with it now...

2019-06-28 14:50 UTC, petebacondarwin commented
try these changes:


```diff
diff --git a/packages/compiler-cli/src/main.ts b/packages/compiler-cli/src/main.ts
index 13ca9d5c22..7e03a4ecb3 100644
--- a/packages/compiler-cli/src/main.ts
+++ b/packages/compiler-cli/src/main.ts
@@ -26,7 +26,7 @@ export function main(
     config?: NgcParsedConfiguration, customTransformers?: api.CustomTransformers, programReuse?: {
       program: api.Program | undefined,
     },
-    modifiedResourceFiles?: Set<string>): number {
+    modifiedResourceFiles: Set<string>| null = null): number {
   let {project, rootNames, options, errors: configErrors, watch, emitFlags} =
       config || readNgcCommandLineAndConfiguration(args);
   if (configErrors.length) {
diff --git a/packages/compiler-cli/src/perform_compile.ts b/packages/compiler-cli/src/perform_compile.ts
index 4d27b2b323..f7ea7bbb59 100644
--- a/packages/compiler-cli/src/perform_compile.ts
+++ b/packages/compiler-cli/src/perform_compile.ts
@@ -224,7 +224,7 @@ export function exitCodeFromResult(diags: Diagnostics | undefined): number {
 export function performCompilation(
     {rootNames, options, host, oldProgram, emitCallback, mergeEmitResultsCallback,
      gatherDiagnostics = defaultGatherDiagnostics, customTransformers,
-     emitFlags = api.EmitFlags.Default, modifiedResourceFiles}: {
+     emitFlags = api.EmitFlags.Default, modifiedResourceFiles = null}: {
       rootNames: string[],
       options: api.CompilerOptions,
       host?: api.CompilerHost,
@@ -234,7 +234,7 @@ export function performCompilation(
       gatherDiagnostics?: (program: api.Program) => Diagnostics,
       customTransformers?: api.CustomTransformers,
       emitFlags?: api.EmitFlags,
-      modifiedResourceFiles?: Set<string>,
+      modifiedResourceFiles?: Set<string>| null,
     }): PerformCompilationResult {
   let program: api.Program|undefined;
   let emitResult: ts.EmitResult|undefined;
diff --git a/packages/compiler-cli/test/ngtsc/env.ts b/packages/compiler-cli/test/ngtsc/env.ts
index efb1fe6793..1f1639688d 100644
--- a/packages/compiler-cli/test/ngtsc/env.ts
+++ b/packages/compiler-cli/test/ngtsc/env.ts
@@ -26,7 +26,7 @@ import {setWrapHostForTest} from '../../src/transformers/compiler_host';
 export class NgtscTestEnvironment {
   private multiCompileHostExt: MultiCompileHostExt|null = null;
   private oldProgram: Program|null = null;
-  private changedResources: Set<string>|undefined = undefined;
+  private changedResources: Set<string>|null = null;
 
   private constructor(
       private fs: FileSystem, readonly outDir: AbsoluteFsPath, readonly basePath: AbsoluteFsPath) {}
@@ -107,6 +107,12 @@ export class NgtscTestEnvironment {
     this.multiCompileHostExt.flushWrittenFileTracking();
   }
 
+  /**
+   * Older versions of the CLI do not provide the `CompilerHost.getModifiedResourceFiles()` method.
+   * This results in the `changedResources` set being `null`.
+   */
+  simulateLegacyCLICompilerHost() { this.changedResources = null; }
+
   getFilesWrittenSinceLastFlush(): Set<string> {
     if (this.multiCompileHostExt === null) {
       throw new Error(`Not tracking written files - call enableMultipleCompilations()`);
diff --git a/packages/compiler-cli/test/ngtsc/incremental_spec.ts b/packages/compiler-cli/test/ngtsc/incremental_spec.ts
index 9cf9198feb..b4daca54ff 100644
--- a/packages/compiler-cli/test/ngtsc/incremental_spec.ts
+++ b/packages/compiler-cli/test/ngtsc/incremental_spec.ts
@@ -23,6 +23,24 @@ runInEachFileSystem(() => {
       env.tsconfig();
     });
 
+    it('should not crash if CLI does not provide getModifiedResourceFiles()', () => {
+      env.write('component1.ts', `
+      import {Component} from '@angular/core';
+
+      @Component({selector: 'cmp', templateUrl: './component1.template.html'})
+      export class Cmp1 {}
+    `);
+      env.write('component1.template.html', 'cmp1');
+      env.driveMain();
+
+      // Simulate a change to `component1.ts`
+      env.flushWrittenFileTracking();
+      env.invalidateCachedFile('component1.html');
+      env.simulateLegacyCLICompilerHost();
+      env.driveMain();
+    });
+
     it('should skip unchanged services', () => {
       env.write('service.ts', `
       import {Injectable} from '@angular/core';
```

2019-06-28 15:31 UTC, mattlewis92 commented
Awesome, that got it! Thanks so much for your help! 😄

2019-07-10 09:24 UTC, petebacondarwin approved these changes

2019-07-10 09:25 UTC, petebacondarwin commented
Thanks for this @mattlewis92 - @alxhub is away at the moment but once he is back, we can get his approval and get this merged.

2019-07-11 11:42 UTC, alxhub commented
Hi @mattlewis92,

This looks good to me! The only thing that I would ask is that you add some detail to the commit message describing the bug and the fix. In particular I'm interested in how this manages to escape type checking - how do we end up with `modifiedResourceFiles` being `null` when the types should not allow that?

2019-07-11 11:43 UTC, alxhub approved these changes

2019-07-11 12:24 UTC, alxhub commented
[Presubmit](http://test/OCL:257589113:BASE:257589130:1562847704562:76acc4d4)

2019-07-16 17:12 UTC, mattlewis92 commented
> Hi @mattlewis92,
> 
> This looks good to me! The only thing that I would ask is that you add some detail to the commit message describing the bug and the fix. In particular I'm interested in how this manages to escape type checking - how do we end up with `modifiedResourceFiles` being `null` when the types should not allow that?

@petebacondarwin please can you help me out with what to put for the commit message? Thanks! 😄

2019-07-17 15:26 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/incremental/src/state.ts
> +    if (this.modifiedResourceFiles === null || !this.metadata.has(sf)) {
@alxhub this is the key change. The `IncrementalState` class takes a `Set<string>|null` for its `modifiedResourceFiles` parameter. The `modifiedResourceFiles` property could never be `undefined`, instead it could be a `Set<string>` or it could be `null`.

To tighten up the types across the system we changed everything else so that all properties and variables that could hold this modified resource files value could also never by `undefined`.

2019-07-17 15:28 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/incremental/src/state.ts
> +    if (this.modifiedResourceFiles === null || !this.metadata.has(sf)) {
An alternative approach would have been to change every type to `Set<string>|undefined` instead. But my understanding is that you prefer to use `null` when something is explicitly not being provided.

2019-07-17 15:53 UTC, petebacondarwin commented
@mattlewis92 - I would suggest something like the following for the commit message...

>>>
fix(ivy): support older CLI versions that do not pass a list of changed files

Versions of CLI prior to
https://github.com/angular/angular-cli/commit/0e339ee56051d7c625ea9d8da2fb5049d3a246e8
did not expose the `host.getModifiedResourceFiles()` method.

This meant that `null` was being passed through to the `IncrementalState.reconcile()` method
to indicate that there were either no changes or the host didn't support that method.

This commit fixes a bug where we were checking for `undefined` rather than `null` when
deciding whether any resource files had changed, causing a null reference error to be thrown.

This bug was not caught by the unit testing because the tests set up the changed files
via a slightly different process, not having access to the `CompilerHost`, and these test
were making the erroneous assumption that `undefined` indicated that there were no
changed files.

2019-07-17 16:28 UTC, mattlewis92 commented
Awesome, thanks @petebacondarwin! I've just made that change now.

2019-07-18 20:00 UTC, alxhub approved these changes

2019-07-18 20:00 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/incremental/src/state.ts
> +    if (this.modifiedResourceFiles === null || !this.metadata.has(sf)) {
👍

2019-07-18 20:07 UTC, alxhub commented
[Presubmit](http://test/OCL:257589113:BASE:258829289:1563480362430:4bb22775)

2019-07-18 21:24 UTC, closed without merging

2019-07-30 11:08 UTC, stefanocke commented
I got the same error, but not with CLI, but just by calling ncg in watch mode.
Interestingly, it only happens on every second change.

2019-07-30 11:50 UTC, mattlewis92 commented
@stefanocke ivy fixes don't get backported to 8.1.x, so you need to be on `8.2.0-rc.0` for this fix to be included. `ng update @angular/core --next --force` can do it for you automatically.