fix(docs-infra): fix `search-results` styles
angular/angular pull request #31390
Opened 2019-07-02 17:10 UTC by gkalpak

I started to fix the "No results found" message being hidden, but ended up doing some clean up and other minor fixes (see individual commits for details).

WRT to the main fix ("No results found" being hidden):

**BEFORE**
![search-not-found-before](https://user-images.githubusercontent.com/8604205/60532113-3ae51600-9d05-11e9-8da0-0fdc2817b653.png)

**AFTER**
![search-not-found-after](https://user-images.githubusercontent.com/8604205/60532123-40daf700-9d05-11e9-9890-80301502bbed.png)

##
Both before and after the "No results found" is displayed correctly on the "Page Not Found" page:

![page-not-found-before-and-after](https://user-images.githubusercontent.com/8604205/60532143-4c2e2280-9d05-11e9-9d9a-13791f4230d4.png)

2019-07-02 17:17 UTC, mary-poppins commented
You can preview 9489a5b at https://pr31390-9489a5b.ngbuilds.io/.

2019-07-03 15:13 UTC, mary-poppins commented
You can preview 119dcd1 at https://pr31390-119dcd1.ngbuilds.io/.

2019-07-03 15:16 UTC, petebacondarwin approved these changes

2019-07-04 19:35 UTC, sjtrimble commented
@gkalpak 

A couple UX/UI recommendations:
1) Don't actually show the "I have nothing to show you" message if we don't have any suggestions OR even better (maybe handle it in another PR) show them a few items where they might want to spend some time on like the blog, the guide, etc.
<img width="1409" alt="Screen Shot 2019-07-04 at 12 32 16 PM" src="https://user-images.githubusercontent.com/2958442/60685427-edc58900-9e57-11e9-9fd2-24b1469ee2f3.png">

2) Can we do something to fix the cut off face image at the top? :)
<img width="1409" alt="Screen Shot 2019-07-04 at 12 32 04 PM" src="https://user-images.githubusercontent.com/2958442/60685433-f6b65a80-9e57-11e9-9529-6e59b978980e.png">

2019-07-05 14:13 UTC, mary-poppins commented
You can preview a9b3ede at https://pr31390-a9b3ede.ngbuilds.io/.

2019-07-05 14:27 UTC, gkalpak commented
Thx for taking a look, @sjtrimble. I fixed the image placement.

Regarding the "no results" message, I wouldn't be opposed to showing something (although I assume it should rarely come up for the `page-not found` error page). It is not related to this PR though (I am just fixing the color of the message to be different from the background and thus visible). Feel free to open an issue (or a PR :wink:) about changing the message and we can discuss the details there.

2019-07-09 20:17 UTC, sjtrimble commented
One more thing @gkalpak .. I'm still seeing the headers showing up a white and thereby transparent. Try seeing here: https://pr31390-119dcd1.ngbuilds.io/ngmodules

2019-07-09 20:20 UTC, sjtrimble requested changes

2019-07-09 20:20 UTC, sjtrimble commented on aio/src/styles/2-modules/_search-results.scss
> +          &a {
I normally put a line break here so it's easier to read ... if you feel like it :)

2019-07-09 20:24 UTC, gkalpak commented on aio/src/styles/2-modules/_search-results.scss
> +          &a {
I was keeping inline with the convention in this file, which seems to be "no line break, if it's targeting the same element". Happy to go either way.

2019-07-09 20:41 UTC, gkalpak commented
> I'm still seeing the headers showing up a white and thereby transparent.

Great catch! 😱 😱 😱
Fixed.

2019-07-09 20:45 UTC, gkalpak commented on aio/src/styles/2-modules/_search-results.scss
> +          &a {
I added the line breaks (since I agree it is more readable).

2019-07-09 20:47 UTC, mary-poppins commented
You can preview 4be1fe9 at https://pr31390-4be1fe9.ngbuilds.io/.

2019-07-09 20:53 UTC, mary-poppins commented
You can preview 9967ab9 at https://pr31390-9967ab9.ngbuilds.io/.

2019-07-09 20:57 UTC, mary-poppins commented
You can preview 4fac6dd at https://pr31390-4fac6dd.ngbuilds.io/.

2019-07-10 19:16 UTC, sjtrimble approved these changes

2019-07-11 16:17 UTC, closed without merging