fix(common): preserve Map's ordered keys with keyvalue pipe
angular/angular pull request #31422
Opened 2019-07-04 19:14 UTC by ravishivt

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #31420

## What is the new behavior?

Preserve Map's ordered keys with keyvalue pipe.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

I'd say this doesn't introduce a breaking change because adjusting the sort order of a Map is unexpected behavior in the first place.

## Other information

2019-07-04 19:38 UTC, Airblader commented on packages/common/src/pipes/keyvalue_pipe.ts
> +      compareFn = defaultComparator;
Now you're just always overwriting compareFn for objects, making it impossible to pass a custom function, right?

2019-07-04 20:15 UTC, ravishivt commented on packages/common/src/pipes/keyvalue_pipe.ts
> +      compareFn = defaultComparator;
Good catch!  I modified this to preserve the passed in compareFn.  I also added a test to verify that a passed in customFn works for objects.

2019-07-04 20:48 UTC, Toxicable commented on packages/common/test/pipes/keyvalue_pipe_spec.ts
> -    it('should order by numerical', () => {
By removing this test, meaning that this test is not longer correct, makes the change here breaking

2019-07-04 21:03 UTC, ravishivt commented on packages/common/test/pipes/keyvalue_pipe_spec.ts
> -    it('should order by numerical', () => {
Yes, technically, this is a breaking change.  But I'd argue no-one expects the keyvalue pipe to adjust the sort order of a Map input.  Regardless, I've updated the PR description to indicate that this is indeed a breaking change.

2019-12-19 02:55 UTC, RobertAKARobin commented
Was just about to start on a PR for this myself. Would love to see this added. Seems very strange that sorting was added to begin with. https://github.com/angular/angular/issues/31420

2020-02-18 20:19 UTC, RobertAKARobin commented
@ravishivt Can you update this PR to pass the checks?

2020-02-20 00:19 UTC, ravishivt commented
@RobertAKARobin I just fixed a broken test, thanks for letting me know.

2021-09-15 13:31 UTC, petebacondarwin requested changes
I don't know if this has been discussed already, but one way to avoid the breaking change, and also to allow JS objects to be sorted by their default ordering, would be to specify that a `compareFn` of `null` means "do not sort".

2021-09-15 15:07 UTC, mlc-mlapis commented
> would be to specify that a compareFn of null means "do not sort".

This sounds very good and logical. Even without any breaking change.

2021-09-15 18:59 UTC, petebacondarwin commented
I discussed this a bit with other team members and we like the idea of going with `null` as an option.

@ravishivt - I am going to close this PR since it is not the approach we want to take. If you would like to try implementing the other approach then please leave a message on the issue in the next few days. Otherwise, it will be open for others to work on.

2021-09-15 18:59 UTC, closed without merging