docs: Including routed feature module case.
angular/angular pull request #31432
Opened 2019-07-05 15:32 UTC by sabithpocker

The example only covers the case of router outlet in AppModule, just added a note saying that the context will be the root component of feature module in the case of a routed feature module.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Documentation relies solely on the case of router outlet in `AppComponent`
Issue Number: N/A

## What is the new behavior?
Added a note on how to translate the example for the case of a routed feature module.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## Other information

2019-07-08 18:22 UTC, kapunahelewong commented on aio/content/guide/route-animations.md
> +**Note:** For a routed feature module, the context of above example will be the root component of the feature instead of `AppComponent` where you have `<router-outlet>` for the feature.
How about this? (Just a few little suggestions to keep with our writing guidelines):

> **Note:** For a routed feature module, the context of the above example is the root component of the feature rather than of the `AppComponent`.

I'd leave out the "where you have the `<router-outlet>` for the feature" unless you want to start a new sentence describing that idea.

2019-07-08 18:27 UTC, kapunahelewong requested changes
Just a small copy recommendation. I am also requesting engineering input from the most excellent @gkalpak. ✨

EDIT: @sabithpocker, could you amend your commit message to something like this:

> docs: add note about routed feature module context

Also, be sure to sign the CLA. Thanks!

2019-07-08 19:55 UTC, gkalpak commented on aio/content/guide/route-animations.md
> +**Note:** For a routed feature module, the context of above example will be the root component of the feature instead of `AppComponent` where you have `<router-outlet>` for the feature.
@sabithpocker, can you explain what you mean by "context of the above example"? (I am confused by this note 😕)

2019-07-09 10:35 UTC, sabithpocker commented
Closing this pull request as this is probably a misunderstanding from my side. Sorry for that.

I have a root component for each feature module with its own `<router-outlet>` rather than using the `<router-outlet>` in the `AppComponent`. I will first review why I had to do it this way and check if this is even a valid scenario.

Sorry for the time wasted.

2019-07-09 10:35 UTC, closed without merging

2019-08-07 18:15 UTC, kapunahelewong commented
It's ok, @sabithpocker. Each new PR/issue helps many of us learn (especially me!). You did not waste our time. We're all in this together. 🌸