[WIP] docs: add FAQ about updating libraries to static query migration guide
angular/angular pull request #31447
Opened 2019-07-08 05:37 UTC by istiti

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #31287

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2019-07-08 05:54 UTC, istiti commented
@kapunahelewong please take a look at this

2019-07-08 17:00 UTC, kapunahelewong commented
Thanks so much for this, @istiti!!

2019-07-08 21:17 UTC, kapunahelewong commented on aio/content/guide/static-query-migration.md
> +Yes, the Core Team's recommendation for libraries is to update to version 8 and add the static flag. Angular version 7 apps will continue to work with libraries that have this flag.
Oh, I forgot to mention this earlier. Can you put static in backticks? So it's `static`.

2019-07-09 17:42 UTC, kapunahelewong commented on aio/content/guide/static-query-migration.md
> +Yes, the Core Team's recommendation for libraries is to update to version 8 and add the static flag. Angular version 7 apps will continue to work with libraries that have this flag.
Done.

2019-07-10 17:15 UTC, kara requested changes
Thanks so much for helping with this! Some small changes requested below.

2019-07-10 17:15 UTC, kara commented on aio/content/guide/static-query-migration.md
> +Yes, the Core Team's recommendation for libraries is to update to version 8 and add the `static` flag. Angular version 7 apps will continue to work with libraries that have this flag.
Nit: We're trying to get away from saying "core team"

```suggestion
Yes, the Angular team's recommendation for libraries is to update to version 8 and add the `static` flag. Angular version 7 apps will continue to work with libraries that have this flag.
```

2019-07-10 17:15 UTC, kara commented on aio/content/guide/static-query-migration.md
> +If you update your library to Angular version 8 and want to take advantage of the new version 8 APIs, or you want more recent dependencies, such as (Typescript or RxJS), your library will be incompat
```suggestion
However, if you update your library to Angular version 8 and want to take advantage of the new version 8 APIs, or you want more recent dependencies, such as (Typescript or RxJS), your library will become incompatible with Angular version 7 apps. If your goal is to make your lib compatible with Angular versions 7 and 8, you should not update your lib at all—except for `peerDependencies` in `package.json`.
```

2019-07-10 17:15 UTC, kara commented on aio/content/guide/static-query-migration.md
> +For this reason, the most efficient plan is for libraries to adopt a 6 month major version schedule and bump their major after each Angular update. That way the libs are in the same release cadence a
```suggestion
In general, the most efficient plan is for libraries is to adopt a 6 month major version schedule and bump the major version after each Angular update. That way, libraries stay in the same release cadence as Angular. 
```

2019-07-10 17:46 UTC, kapunahelewong commented on aio/content/guide/static-query-migration.md
> +Yes, the Core Team's recommendation for libraries is to update to version 8 and add the `static` flag. Angular version 7 apps will continue to work with libraries that have this flag.
Ah, that was me. Good to know!

2019-07-12 00:24 UTC, kara approved these changes
LGTM, aside from the errant parenthesis

2019-07-12 00:24 UTC, kara commented on aio/content/guide/static-query-migration.md
> +However, if you update your library to Angular version 8 and want to take advantage of the new version 8 APIs, or you want more recent dependencies, such as (Typescript or RxJS), your library will be
```suggestion
However, if you update your library to Angular version 8 and want to take advantage of the new version 8 APIs, or you want more recent dependencies, (such as Typescript or RxJS), your library will become incompatible with Angular version 7 apps. If your goal is to make your library compatible with Angular versions 7 and 8, you should not update your lib at all—except for `peerDependencies` in `package.json`.
```

2019-07-12 00:25 UTC, kara commented
@elvisbegovic Could you also squash your commits into 1 commit? (with the message from the first commit) That should make our linter happy.

@IgorMinar What do you think of this guidance?

2019-07-12 12:48 UTC, elvisbegovic commented on aio/content/guide/static-query-migration.md
> +However, if you update your library to Angular version 8 and want to take advantage of the new version 8 APIs, or you want more recent dependencies, (such as Typescript or RxJS), your library will be
@kapunahelewong @kara just to double-check: in french language there is no sense to  write sentence then put comma then parenthesis then comm like here "...dependencies, (such as Typescript or RxJS), your library..." you confirm this is correct in english?

2019-07-12 16:44 UTC, kapunahelewong commented on aio/content/guide/static-query-migration.md
> +However, if you update your library to Angular version 8 and want to take advantage of the new version 8 APIs, or you want more recent dependencies, (such as Typescript or RxJS), your library will be
You are correct, @elvisbegovic. It would be one or the other, but not a comma along with the `()`. Maybe that got in there over the course of us editing it. Good catch though.

2019-07-15 16:21 UTC, IgorMinar approved these changes
thank you!

2019-07-15 17:59 UTC, closed without merging