feat(ivy): index template references, variables, bound attributes/events
angular/angular pull request #31535
Opened 2019-07-13 00:14 UTC by ayazhafiz

Adds support for indexing template referenecs, variables, and property
and method calls inside bound attributes and bound events. This is
mostly an extension of the existing infastructure.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Listed indexing features not supported.

Issue Number: N/A

## What is the new behavior?
Listed indexing features supported.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-07-13 00:15 UTC, ayazhafiz commented
We will be able to remove the byte offset mapping once #31391 lands! :smile:

2019-07-24 20:19 UTC, alxhub requested changes

2019-07-24 20:19 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/api.ts
> +  target?: ReferenceIdentifier|VariableIdentifier;
Nit: use `null` instead of `?` in the compiler to indicate absence of a value.

2019-07-24 20:19 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +      target = this.targetMap.get(nodeTarget);
Is it guaranteed that `targetMap` will contain the target? It's possible to have forward references in Angular templates. For example:

```html
{{foo.value}}
<input ngModel #foo="ngModel">
```

Here `foo` will be processed before the indexer has looked at the `<input>` and recorded `#foo` as a reference.

2019-07-24 20:19 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> -    const localExpression = this.expressionStr.substr(ast.span.start, ast.span.end);
Why not cut this off at the `span.end` anymore?

2019-07-24 21:01 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> -    const localExpression = this.expressionStr.substr(ast.span.start, ast.span.end);
Because in the case of a BoundAttribute the span of nested expressions is larger than the span of the top-level AstWithSource, so cutting off at `span.end` cuts off the actual expression. This is fixed in #31813.

Cutting the span off introduces no functional difference, as we're still always searching from the front. 

See https://github.com/angular/angular/pull/31535/files/859ad5606208d916e3857437a992622ff23ee0cd#diff-8939e59015d6b317dffd59a9880ef9d5R213-R222

2019-07-24 21:01 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +      target = this.targetMap.get(nodeTarget);
You're right, this fails in such a case. Moving to populating identifiers with targets after all identifiers have already been discovered.

2019-07-24 21:01 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/api.ts
> +  target?: ReferenceIdentifier|VariableIdentifier;
The only reason I don't like this is then we have to explicitly include a value for the target every time we create a `TemplateIdentifier`, which may get confusing to a reader since now populate identifiers with targets after all identifiers are already built.

Let me know if this is not a good reason, we can add `target: undefined` (or `target: null`)

2019-07-24 23:12 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/template.ts
> +   * @param targetMap map of targets defined in templates to their identifiers.
Left over?

2019-07-25 16:43 UTC, alxhub approved these changes

2019-07-25 16:43 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/indexer/src/api.ts
> +export interface ReferenceIdentifier extends TemplateIdentifier { kind: IdentifierKind.Reference; }
It might also be worthwhile to record if this is a reference to a particular directive or to an element (`BoundTarget.getReferenceTarget`).

2019-07-25 18:10 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/indexer/src/api.ts
> +export interface ReferenceIdentifier extends TemplateIdentifier { kind: IdentifierKind.Reference; }
Done. We now record template identifiers as well and perform the process of determining a reference target in the same way we determine an expression target.

2019-07-25 20:11 UTC, closed without merging