fix(router): need to export DefaultRouteReuseStrategy to Router public_api
angular/angular pull request #31575
Opened 2019-07-15 21:24 UTC by abarghoud

fix(router): need to export DefaultRouteReuseStrategy to Router public_api(#30827)

Importing DefaultRouteReuseStrategy is not working currently as it's not exported in index.ts file
Tests exist already.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Not able to import DefaultRouteReuseStrategy from @angular/router

Issue Number: #30827 

## What is the new behavior?
Ability to import DefaultRouteReuseStrategy 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-07-15 21:27 UTC, abarghoud commented
Tests and documentation have already been added, I just added the export code

2019-08-05 07:56 UTC, santoshyadav198613 commented
Hi @abarghoud ,
Can you also stash commits into a single commit.

2019-08-05 10:58 UTC, abarghoud commented
@googlebot I fixed it.

2019-08-05 10:59 UTC, abarghoud commented
@santoshyadav198613 done

2020-06-16 17:54 UTC, atscott commented
@abarghoud - could you rebase and squash the commits into one?

2020-06-16 18:05 UTC, abarghoud commented
> @abarghoud - could you rebase and squash the commits into one?

@atscott on it

2020-06-16 18:10 UTC, atscott requested changes

2020-06-16 18:10 UTC, atscott commented on packages/router/src/route_reuse_strategy.ts
>    shouldDetach(route: ActivatedRouteSnapshot): boolean { return false; }
Could you add a small bit of documentation on each of these? Generally, you'll be able to copy from the interface.
For example
```
/**
 * Returns `false`, meaning the route is never detached to be reused later.
 */
shouldDetach(...)
```

2020-06-16 18:10 UTC, atscott commented on packages/router/test/integration.spec.ts
> +    it('should not error when importing DefaultRouteReuseStrategy from @angular/route', (() => {
I'm not convinced this test is really necessary. I think the "test" is more or less the `public_api_guard`

2020-06-16 19:31 UTC, abarghoud commented
@atscott rebase and squash done.

Comments took into account.

2020-06-16 19:33 UTC, atscott approved these changes
reviewed-for: fw-router

2020-06-16 19:33 UTC, atscott commented on packages/router/src/route_reuse_strategy.ts
> +  /** Doing nothing */
```suggestion
  /** A no-op; the route is never stored since this strategy never detaches routes for later re-use. */
```

2020-06-16 19:33 UTC, atscott commented on packages/router/src/route_reuse_strategy.ts
> +  /** Returns `null` */
```suggestion
  /** Returns `null` because this strategy does not store routes for later re-use. */
```

2020-06-16 19:33 UTC, atscott commented on packages/router/src/route_reuse_strategy.ts
> +  /** Returns true, when the future routeConfig that should be reused is equal to current routeConfig */
```suggestion
  /** Returns `true` when the future route config and current route config are identical. */
```

2020-06-16 19:45 UTC, atscott commented
Hi @abarghoud - I rebased the PR for you to resolve the conflicts. Could you fetch the latest before making those final updates?

2020-06-16 19:48 UTC, abarghoud commented
> Hi @abarghoud - I rebased the PR for you to resolve the conflicts. Could you fetch the latest before making those final updates?

Thanks, I will do that.

2020-06-16 21:27 UTC, mary-poppins commented
You can preview 016a9ed at https://pr31575-016a9ed.ngbuilds.io/.
You can preview a20f1f7 at https://pr31575-a20f1f7.ngbuilds.io/.
You can preview aea5e15 at https://pr31575-aea5e15.ngbuilds.io/.
You can preview f5f93a5 at https://pr31575-f5f93a5.ngbuilds.io/.
You can preview 9925d2d at https://pr31575-9925d2d.ngbuilds.io/.
You can preview cdc75a0 at https://pr31575-cdc75a0.ngbuilds.io/.
You can preview 31dc376 at https://pr31575-31dc376.ngbuilds.io/.
You can preview 33cd468 at https://pr31575-33cd468.ngbuilds.io/.
You can preview 97c920c at https://pr31575-97c920c.ngbuilds.io/.
You can preview 62c14b9 at https://pr31575-62c14b9.ngbuilds.io/.
You can preview bcf9a6a at https://pr31575-bcf9a6a.ngbuilds.io/.

2020-06-17 02:30 UTC, jelbourn commented on packages/router/src/route_reuse_strategy.ts
>  export class DefaultRouteReuseStrategy implements RouteReuseStrategy {
@atscott what do you think about actually renaming this class before adding it to the public API? Being called "Default" doesn't actually describe what it does, just how it's consumed by the router. I'm thinking something like "NoReuseRouteReuseStrategy" or "NoopRouteReuseStrategy".

2020-06-17 02:30 UTC, jelbourn commented on packages/router/src/route_reuse_strategy.ts
> +  /** Returns `false`, meaning the route is never detached to be reused later. */
@atscott I'm wondering if these JsDoc descriptions should be worded along the lines of
```markdown
Whether the given route should detach for later reuse.
Always returns false for NoopRouteReuseStrategy.
```

2020-06-17 02:30 UTC, jelbourn commented on packages/router/src/route_reuse_strategy.ts
> + *
I would want to touch up the JsDoc description before adding this to the public API. I would word it something like
```markdown
Router reuse strategy that does not ever re-use routes. Angular uses this strategy by default.
```

2020-06-17 15:55 UTC, abarghoud commented on packages/router/src/route_reuse_strategy.ts
>  export class DefaultRouteReuseStrategy implements RouteReuseStrategy {
Yes indeed, I think that NoopRouteReuseStrategy allows better readibility and comprehension. @atscott What do you think  ?

2020-06-17 19:23 UTC, atscott commented on packages/router/src/route_reuse_strategy.ts
> + *
Note that it _does_ reuse the route when the current and future route configs are identical. This strategy prevents components from being reloaded when navigations to the same page occur when `{onSameUrlNavigation: 'reload'}` is set.

2020-06-22 20:36 UTC, atscott commented on packages/router/src/route_reuse_strategy.ts
> + *
How about

```
/**
 * This route reuse strategy only reuses routes when the matched router configs are
 * identical. This prevents components from being destroyed and recreated when 
 *`ExtraOptions#onSameUrlNavigation` is set to 'reload' (that is, the existing component
 * is _reused_).
 * 
 * This strategy does not store any routes for later reuse.
 *
 * Angular uses this strategy by default. You may extend this class to provide your own
 * RouteReuseStrategy.
 */
```
I'm not sure about the last part about extending the class. I'm trying to address the public API note "[we discourage people from extending/implementing our classes unless specifically documented](https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md)"

2020-06-22 20:37 UTC, atscott commented on packages/router/src/route_reuse_strategy.ts
> +  /** Returns `false`, meaning the route is never detached to be reused later. */
👍 
@abarghoud, can you review these JSDoc descriptions and ensure they're somewhat understandable on their own without having to reference the abstract class?

2020-06-22 20:41 UTC, atscott commented on packages/router/src/route_reuse_strategy.ts
>  export class DefaultRouteReuseStrategy implements RouteReuseStrategy {
👍 @abarghoud can you please update the class name?

2020-06-22 23:41 UTC, abarghoud commented
Hello @atscott @jelbourn, I've done requested changes.

2020-06-23 14:56 UTC, atscott commented
caretaker note: When synced to Google, it will require a patch which renames the `DefaultRouteReuseStrategy` imports for [these files](https://source.corp.google.com/search?q=import.*defaultroutereusestrategy.*from..google3&sq=package:piper%20file:%2F%2Fdepot%2Fgoogle3%20-file:google3%2Fexperimental)

2020-06-23 15:12 UTC, mary-poppins commented
You can preview e245cb4 at https://pr31575-e245cb4.ngbuilds.io/.

2020-06-23 19:06 UTC, jelbourn commented on packages/router/src/route_reuse_strategy.ts
> + *
Yeah, I would just omit the part about existing the class.

2020-06-23 19:09 UTC, jelbourn commented on packages/router/src/route_reuse_strategy.ts
> +  /** Returns `false`, meaning the route is never detached to be reused later. */
Looks like this JsDoc was updated, but we'd still want to do the other methods as well

2020-06-23 19:10 UTC, jelbourn approved these changes
LGTM for public-api, leaving the rest to @atscott 

Reviewed-for: public-api

2020-06-26 09:24 UTC, abarghoud commented
Hello @atscott, in order to accept the new golden file when executing `yarn bazel run //packages/router:router_api.accept
`
I am getting this error:
```
D:\angular\node_modules\.bin\bazel run //packages/router:router_api.accept
ERROR: error loading package '': in C:/users/barghoud/_bazel_barghoud/vo53ftom/external/build_bazel_rules_nodejs/index.bzl: Label '@build_bazel_rules_nodejs//internal/common:check_bazel_v
ersion.bzl' is invalid because 'internal/common' is not a package; perhaps you meant to put the colon here: '@build_bazel_rules_nodejs//:internal/common/check_bazel_version.bzl'?
INFO: Elapsed time: 9.941s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
error Command failed with exit code 1.
```

2020-06-29 19:16 UTC, atscott commented
> Hello @atscott, in order to accept the new golden file when executing `yarn bazel run //packages/router:router_api.accept `
> I am getting this error:
> ```

I'm not sure exactly why that error happened. I update the golden, rebased to master, and pushed to your branch so we should be good now.

@alxhub, @pkozlowski-opensource - Could you give this a quick look for public-api approval?

2020-06-29 19:23 UTC, mary-poppins commented
You can preview d0a7c2a at https://pr31575-d0a7c2a.ngbuilds.io/.

2020-07-10 19:35 UTC, atscott commented
Hi @abarghoud, after discussing with @alxhub and @pkozlowski-opensource, here's what we think should be done to move this forward:

* create a new `abstract` class (working name: `BaseRouteReuseStrategy`) and move the implementation of the `DefaultRouteReuseStrategy` (please rename it back, sorry!) in there. Having a base class called `NonStoringRouteReuseStrategy` would be misleading because users might extend it and have it actually store routes for reuse.
* mark the new `BaseRouteReuseStrategy` as `publicAPI` and specifically flag it as being "extension friendly"
* have the  `DefaultRouteReuseStrategy` extend  `BaseRouteReuseStrategy`  but do NOT export / mark it as public API
* Adjust some of the documentation language to reflect the new abstract nature. So instead of e.g.  "Returns `null` because this strategy does not store routes for later re-use", it would say something like "By default no routes are stored for later reuse so this returns null"

2020-07-27 11:53 UTC, abarghoud commented
Hi @atscott , sorry for this late response i was in vacation

> Hi @abarghoud, after discussing with @alxhub and @pkozlowski-opensource, here's what we think should be done to move this forward:
> 
> * create a new `abstract` class (working name: `BaseRouteReuseStrategy`) and move the implementation of the `DefaultRouteReuseStrategy` (please rename it back, sorry!) in there. Having a base class called `NonStoringRouteReuseStrategy` would be misleading because users might extend it and have it actually store routes for reuse.
> * mark the new `BaseRouteReuseStrategy` as `publicAPI` and specifically flag it as being "extension friendly"
> * have the  `DefaultRouteReuseStrategy` extend  `BaseRouteReuseStrategy`  but do NOT export / mark it as public API
> * Adjust some of the documentation language to reflect the new abstract nature. So instead of e.g.  "Returns `null` because this strategy does not store routes for later re-use", it would say something like "By default no routes are stored for later reuse so this returns null"

Ok will do that

2020-08-09 17:06 UTC, abarghoud commented
Hi @atscott, I've done requested changes if you can recheck and rebase please as I am not able to rebase

2020-08-10 17:00 UTC, atscott approved these changes
Thanks for making those changes! Just a couple more nits but otherwise LGTM.

Edit: I also rebased for you so you'll have to fetch the changes from your remote before addressing those final comments.

2020-08-10 17:00 UTC, atscott approved these changes
reviewed-for: public-api

2020-08-10 17:07 UTC, mary-poppins commented
You can preview fb22e26 at https://pr31575-fb22e26.ngbuilds.io/.

2020-08-10 17:16 UTC, AndrewKushnir approved these changes
LGTM, just left one quick comment.

Reviewed-for: public-api

2020-08-10 17:16 UTC, AndrewKushnir commented on packages/router/src/route_reuse_strategy.ts
> + * Extension friendly
I think it'd be great to rephrase it a bit to be specific what extension means.
```suggestion
 * It can be used as a base class for custom route reuse strategies, i.e. you can create your own class that extends the `BaseRouteReuseStrategy` one.
```

2020-08-11 09:34 UTC, mary-poppins commented
You can preview 0b3b467 at https://pr31575-0b3b467.ngbuilds.io/.

2020-08-11 09:58 UTC, mary-poppins commented
You can preview 3005050 at https://pr31575-3005050.ngbuilds.io/.

2020-08-11 10:31 UTC, mary-poppins commented
You can preview f342b71 at https://pr31575-f342b71.ngbuilds.io/.

2020-08-11 19:45 UTC, abarghoud commented
@atscott It's good for requested changes

2020-08-11 21:10 UTC, alxhub approved these changes

2020-08-11 21:10 UTC, alxhub commented on packages/router/src/route_reuse_strategy.ts
> + *
Maybe:

> This class is provided as a convenient base for `RouteReuseStrategy` implementations that also need this default behavior.

I do think mentioning it is important, because this class is designed for users to extend, and our policy is that we should specifically document that.

2020-08-11 21:10 UTC, alxhub commented on packages/router/src/route_reuse_strategy.ts
> + * when the just, the fragment, or query parameters change
```suggestion
 * when just the fragment or query parameters change
```

2020-08-12 08:07 UTC, mary-poppins commented
You can preview d8890d4 at https://pr31575-d8890d4.ngbuilds.io/.

2020-08-12 08:23 UTC, mary-poppins commented
You can preview 7698d26 at https://pr31575-7698d26.ngbuilds.io/.

2020-08-13 17:29 UTC, atscott commented
@abarghoud Could you address the final minor comment from Alex? This should be good to go after that; all the approvals are there.

2020-08-13 21:11 UTC, abarghoud commented
> @abarghoud Could you address the final minor comment from Alex? This should be good to go after that; all the approvals are there.

@atscott I am not sure of which comment you are talking as for this one https://github.com/angular/angular/pull/31575#discussion_r468865966 I've removed that paragraph and for https://github.com/angular/angular/pull/31575#discussion_r468866727 I did the correction

2020-08-13 22:04 UTC, atscott commented
@abarghoud My apologies! I was looking at the outdated comment https://github.com/angular/angular/pull/31575#discussion_r468866727 that wasn't marked as resolved. I think everything looks good now.

2020-08-13 23:02 UTC, closed without merging