feat(upgrade): support $element in upgraded component template function
angular/angular pull request #31637
Opened 2019-07-18 21:09 UTC by bamblack

Template functions on upgraded components will receive $element

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
  - I modified an existing one that verified that both `$element` and `$attrs` were undefined; it now verifies that `$element` is defined and `$attrs` is undefined
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 31565

## What is the new behavior?
Template functions on upgraded components will receive `$element` via `UpgradeHelper.compileTemplate`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2019-07-21 08:15 UTC, gkalpak commented on packages/upgrade/static/test/integration/upgrade_component_spec.ts
> -      it('should support not pass any arguments to `template` function', async(() => {
Aha!, So, it was a feature not to pass the arguments 😛

2019-07-21 09:28 UTC, gkalpak requested changes
Thx, @bamblack! I left a couple minor comments, but generally lgtm 👍

2019-07-21 09:28 UTC, gkalpak commented on packages/upgrade/src/common/src/upgrade_helper.ts
>        const url = getOrCall<string>(directive.templateUrl);
Since we are adding support for `$element` to `template`, we should do the same for `templateUrl`. Can you update the call here and also add/update tests?

2019-07-21 09:28 UTC, gkalpak commented on packages/upgrade/src/common/src/upgrade_helper.ts
> +function getOrCall<T>(property: T | Function, $element?: IAugmentedJQuery): T {
It might make sense to keep this generic and accept a list of arguments (instead of `$element`specifically).

2019-07-22 12:50 UTC, bamblack commented on packages/upgrade/src/common/src/upgrade_helper.ts
>        const url = getOrCall<string>(directive.templateUrl);
Ah I purposefully left it out of that because I wasn't aware `templateUrl` could be a function, that's what I get for not reading the docs I suppose!

2019-07-22 13:01 UTC, bamblack commented on packages/upgrade/src/common/src/upgrade_helper.ts
> +function getOrCall<T>(property: T | Function, $element?: IAugmentedJQuery): T {
Something like this then?

```
function getOrCall<T>(property: T | Function, ...templateFunctionArgs: any[]): T {
  return isFunction(property) ? property(...templateFunctionArgs) : property;
}
```

2019-07-22 18:16 UTC, gkalpak commented on packages/upgrade/src/common/src/upgrade_helper.ts
> +function getOrCall<T>(property: T | Function, $element?: IAugmentedJQuery): T {
Works for me.

2019-07-23 13:05 UTC, gkalpak requested changes
One minor suggetion. LGTM otherwise :+1:
@bamblack, can you also squash the commits together, since they are essentially all related to the same change.

2019-07-23 20:30 UTC, bamblack commented
Done and done.

2019-07-23 21:55 UTC, gkalpak approved these changes
Awesome! Thx, @bamblack 👍

2019-07-24 04:24 UTC, mhevery commented
[presubmit](http://test/OCL:259671191:BASE:259671197:1563942231841:83104e5d)

2019-07-24 21:36 UTC, closed without merging