feat(core): add undecorated-base-class migration schematic
angular/angular pull request #31650
Opened 2019-07-19 10:06 UTC by devversion

* See individual commits.

Regarding google3 tslint driver. I'm still worried about performance here. TSLint is generally pretty slow, doesn't have an analysis phase etc. read more why tslint is bad for replacements [here(bullet points)](https://github.com/angular/components/blob/master/src/cdk/schematics/ng-update/update-schematic.md#transforming-typescript-files).

It's especially bad now because the rule for this migration re-creates another program (significant memory pressure; so much overheard).. We need to create another program because we need the `AngularCompilerProgram` to read/parse and simplify AOT metadata and summaries.

2019-07-20 14:14 UTC, alexeagle commented
We now have a MapReduce over g3 that brings up an ngc `ng.Program` for every compilation. Just used it to list all Directives in g3. I'll patch this over on Monday to find all violations and count them.

2019-07-20 20:41 UTC, alexeagle commented on packages/core/schematics/utils/typescript/symbol.ts
> +    symbol = this.checker.getAliasedSymbol(symbol);
```
third_party/javascript/angular2/rc/packages/core/schematics/utils/typescript/symbol.ts:16:14 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

16     symbol = this.checker.getAliasedSymbol(symbol);
                ~~~~

```

2019-07-20 22:13 UTC, alexeagle commented
I wired it up directly in tsunami, so you can remove any google3-specific or tslint bits from this PR.

An ngTsunami analyzer is a program which gets a tsconfig path as its only argument.
It can import a helper function `createCompilationUnit` either returns an `ng.Program` or null (if it's not an Angular compilation unit for example)
It is expected to pass a protocol buffer result to an `emitAnalyzerResults` function (it happens to write them to stdout for the wrapping mapreduce binary to get them)

To start with I just want to find all the violations in google3, like tslint without `--fix`, so I just encode the map of relativeFilePath -> {line:column} in the appropriate protocol buffer.

It's not working for all inputs though, there's a crash:
```
 stderr: failed to load main  Error: Unexpected value in spread expression: [object Object]
E0720 14:57:20.751639 105917 wavelet.go:97 stderr:     at StaticInterpreter.visitSpreadElement (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.js:526:19)
E0720 14:57:20.751816 105917 wavelet.go:97 stderr:     at StaticInterpreter.visitArrayLiteralExpression (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.js:136:63)
E0720 14:57:20.751944 105917 wavelet.go:97 stderr:     at StaticInterpreter.visitExpression (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.js:106:27)
E0720 14:57:20.752108 105917 wavelet.go:97 stderr:     at StaticInterpreter.visitVariableDeclaration (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.js:256:25)
E0720 14:57:20.752249 105917 wavelet.go:97 stderr:     at StaticInterpreter.visitDeclaration (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.js:235:25)
E0720 14:57:20.752387 105917 wavelet.go:97 stderr:     at StaticInterpreter.visitIdentifier (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.js:213:27)
E0720 14:57:20.752516 105917 wavelet.go:97 stderr:     at StaticInterpreter.visitExpression (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.js:88:27)
E0720 14:57:20.752613 105917 wavelet.go:97 stderr:     at StaticInterpreter.visit (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.js:59:21)
E0720 14:57:20.752839 105917 wavelet.go:97 stderr:     at PartialEvaluator.evaluate (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/compiler-cli/src/ngtsc/partial_evaluator/src/interface.js:19:28)
E0720 14:57:20.753044 105917 wavelet.go:97 stderr:     at NgDirectiveCollector._visitNgModuleDecorator (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/core/schematics/migrations/undecorated-classes/directive_collector.js:75:44)
E0720 14:57:20.753188 105917 wavelet.go:97 stderr:     at NgDirectiveCollector._visitClassDeclaration (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/core/schematics/migrations/undecorated-classes/directive_collector.js:48:18)
E0720 14:57:20.753380 105917 wavelet.go:97 stderr:     at NgDirectiveCollector.visitNode (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/core/schematics/migrations/undecorated-classes/directive_collector.js:31:18)
E0720 14:57:20.753563 105917 wavelet.go:97 stderr:     at /export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/core/schematics/migrations/undecorated-classes/directive_collector.js:33:59
E0720 14:57:20.753692 105917 wavelet.go:97 stderr:     at visitNodes (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/node_modules/typescript/stable/lib/typescript.js:16521:30)
E0720 14:57:20.753834 105917 wavelet.go:97 stderr:     at Object.forEachChild (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/node_modules/typescript/stable/lib/typescript.js:16749:24)
E0720 14:57:20.754027 105917 wavelet.go:97 stderr:     at NgDirectiveCollector.visitNode (/export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/third_party/javascript/angular2/rc/packages/core/schematics/migrations/undecorated-classes/directive_collector.js:33:12)
E0720 14:57:20.754174 105917 wavelet.go:97 stderr:     at /export/hda3/borglet/local_ram_fs_dirs/794.mapreduce-tsunami-mapper-0.typescript.16432097079.28790bf39cfcc7a3/analyzer_pkg/google3/javascript/typescript/tsunami/analyzers/angular/undecorated.js:43:79
```

The spread operator appears in this code, hope this is enough to repro:
```
import {allComponents as sharedComponents} from 'google3/.../ng2/shared';
export type AngularComponent = Type<any>;
export const COMPONENTS: AngularComponent[] = [
  ConditionalLink,
  ExampleNg2Component,
  MatIcon,
  ...sharedComponents,
];
```

the `.../ng2/shared` is another ng_module compilation unit. 

There's a second case of the same error, code looks like
```
import * as Dash2Util from 'google3/.../ng1_util';
@NgModule({
  imports: [
    BrowserAnimationsModule,
    Dash2Util.Dash2Module,
  ],
  entryComponents: [
    ...Dash2Util.DASH2_ENTRY_COMPONENTS,
  ],
})
export class Ng2AppModule {
  ngDoBootstrap() {}
}
```

In both cases I think ngUpgrade is in use.

I'll re-run the MR with some extra error-handling so we can find out if these are all the crashes.

2019-07-20 22:16 UTC, alexeagle commented
Also FWIW, 3 out of 3337 shards of g3 experienced the crash, so we're not losing much data due to this currently.

2019-07-20 23:29 UTC, alexeagle commented
okay with those three shards excluded, I have the code locations violating the check
https://alexeagle.users.x20web.corp.google.com/ngc_tsunami.html
(googlers only sorry)
which lists a lot of violations in `.d.ts` files, not in the `.ts` file where the source lives. Maybe we need to make use of the sourcemapping to emit `.ts` locations instead?

2019-07-20 23:31 UTC, alexeagle commented
It triggers in this case which seems wrong
```
import {Pipe, PipeTransform} from '@angular/core';
@Pipe({name: 'timestamp'})
export class Timestamp implements PipeTransform {
}
```

2019-07-21 07:18 UTC, devversion commented
@alexeagle Thanks for spending time on this! Finding violations first sounds reasonable to me. 

>  so I just encode the map of relativeFilePath -> {line:column} in the appropriate protocol buffer.

The returned transform failures are only for instances where the migration could not be performed automatically. Successful replacements are stored in the update recorders. So right now I think that your MR test-run just showed cases where the migration failed to perform.

> which lists a lot of violations in .d.ts files, not in the .ts file where the source lives. 

Hmm. The transform should actually never create failures for TS nodes outside of program source files. What are the violation messages for such instances?.

2019-07-21 08:16 UTC, devversion commented
@alexeagle Removed the tslint driver bits in favor of the tsunami driver. Also I fixed the `@Pipe` case you mentioned. It looks like this one wasn't part of the migration plan but it seems reasonable to also migrate undecorated pipes that inherit metadata (case 2).

For case 1 where the pipe is decorated but inherits the constructor from undecorated pipes, we'd need to figure out what to do. cc. @alxhub. do we need an abstract `@Pipe()` as well?

2019-07-22 17:12 UTC, alexeagle commented
Probably shouldn't add a class comment if there is already one:
![image](https://user-images.githubusercontent.com/47395/61650720-27c0c880-ac69-11e9-89ed-b2262a138133.png)

2019-07-22 18:16 UTC, devversion commented
I think we should always omit the leading/trailing comment for the copied decorator. Comments that are associated with a decorator are most of the time not intended to target the decorator, but rather the class.

2019-07-23 22:11 UTC, kara requested changes

2019-07-23 22:17 UTC, devversion commented on packages/core/schematics/BUILD.bazel
> +        "//packages/core/schematics/migrations/undecorated-classes",
Is it really just for undecorated classes with DI? i.e. we add `@Directive()` even to base classes which do not have a constructor. For example:

```ts

// we want to add @Directive() here
export class SuperBaseComp {
  constructor(...) {}
}

// we want to add @Directive() here
export class BaseComp extends SuperBaseComp {}

@Component(...)
export class MyComp extends BaseComp {}
```

2019-07-23 22:23 UTC, kara commented on packages/core/schematics/BUILD.bazel
> +        "//packages/core/schematics/migrations/undecorated-classes",
Yep, ultimately the problem is using DI in that `SuperBaseComp`.

2019-08-08 21:03 UTC, kara approved these changes
LGTM

2019-08-12 19:41 UTC, devversion commented
The PR is currently blocked on a components build issue that has been unveiled by these changes. I'll rebase this PR on top of https://github.com/angular/components/pull/16758 once it landed.

2019-08-13 18:54 UTC, kara commented
Caretaker note (to self): needs a G3 patch

2019-08-13 21:40 UTC, kara commented
merge-assistance: global

2019-08-13 21:43 UTC, closed without merging