fix(zone.js): don't rely on global node typings outside of node/ dire…
angular/angular pull request #31783
Opened 2019-07-22 18:10 UTC by alexeagle

…ctory

2019-07-22 18:18 UTC, alexeagle commented
Note: this is required to switch google3 to point at this new location of zone.js sources

2019-07-22 23:31 UTC, JiaLiPassion requested changes

2019-07-22 23:31 UTC, JiaLiPassion commented on packages/zone.js/lib/zone-spec/long-stack-trace.ts
> +  // Cast through any since this property only exists on Error in the nodejs
it seems there is an additional space ` ` at the end of this comment which will fail the `tslint`.

2019-07-22 23:31 UTC, JiaLiPassion commented on packages/zone.js/lib/zone.ts
> +declare var global: {};
got it, there is a reference to `node declaration` here https://github.com/angular/angular/blob/master/packages/zone.js/lib/common/utils.ts#L14, should we also remove that?

2019-07-30 17:24 UTC, alexeagle commented on packages/zone.js/lib/zone.ts
> +declare var global: NodeJS.Global;
note, in g3 there is a transformation to replace `NodeJS.Global` with `{}` since this file is compiled without node typings in g3

2019-07-30 17:29 UTC, JiaLiPassion approved these changes

2019-07-30 17:29 UTC, alexeagle commented on packages/zone.js/lib/zone.ts
> +declare var global: {};
No we don't need to - that isn't on the critical path to fix the compilation in g3. We could do more changes later...

2019-07-30 20:02 UTC, closed without merging