docs: clarify pipe naming
angular/angular pull request #31806
Opened 2019-07-23 18:32 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The naming requirement for pipes is only mentioned as a recommended naming convention in the style guide. 

Issue Number:  https://github.com/angular/angular/issues/31787

## What is the new behavior?

Clarify requirement in style guide and add to the API doc for `@Pipe` decorator.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-07-23 18:38 UTC, mary-poppins commented
You can preview 49553ee at https://pr31806-49553ee.ngbuilds.io/.

2019-07-24 04:20 UTC, santoshyadav198613 commented
The doc related changes look good, but as @Airblader mentioned we should throw a proper exception from the framework.

2019-07-24 04:31 UTC, Airblader commented on packages/core/src/metadata/directives.ts
> +   * should use the name `myPipe`.
I disagree that something like a suffix "must" be kept. A NumberPipe would likely just have a name "number".

I also don't see why the name *must* match the class name in any way at all. There's no technical requirement for that.

The styleguide can be opionated, but IMHO here we should stick to facts.

2019-07-24 15:04 UTC, jbogarthyde commented on packages/core/src/metadata/directives.ts
> +   * should use the name `myPipe`.
I agree - that's why the wording is "MUST be in lowerCamelCase" and "by convention SHOULD match class name".

2019-07-24 15:07 UTC, jbogarthyde commented
This PR is to satisfy the doc issue. There should be a separate issue for changing the code to throw a better exception.

2019-07-24 15:17 UTC, Airblader commented on packages/core/src/metadata/directives.ts
> +   * should use the name `myPipe`.
But "must be in lowerCamelCase" is simply not true. "Cannot contain hyphens" is not the same as lowerCamelCase. I can also use rAndOmcASe if I want.

2019-07-24 15:21 UTC, jbogarthyde commented on packages/core/src/metadata/directives.ts
> +   * should use the name `myPipe`.
That also passes the lowerCamelCase definition - starts with a lower case, followed by mixed case. Using uppercase for word-separation is a convention.

2019-07-24 15:25 UTC, Airblader commented
I can also use upperCamelCase as a name. Again, there's no technical constraint for that.

2019-07-24 15:37 UTC, mary-poppins commented
You can preview 92325a2 at https://pr31806-92325a2.ngbuilds.io/.

2019-07-24 15:37 UTC, mary-poppins commented
You can preview a4a72cf at https://pr31806-a4a72cf.ngbuilds.io/.

2019-07-25 00:16 UTC, kara requested changes

2019-07-25 00:16 UTC, kara commented on packages/core/src/metadata/directives.ts
> +   * For example, the class `MyPipe` would typically use the name `myPipe`.
Hmm I'm not sure we should be this prescriptive about the pipe name matching the class name. In general it's pretty duplicative to have "pipe" in the name because it's clear by the template syntax that it's a pipe. (so it's like "pipe pipe"). That convention is typically only used in examples. I'd say something like:

```
* The pipe name to use in template bindings. Typically uses 
* [lowerCamelCase](guide/glossary#case-types) because 
* the name cannot contain hyphens. 
```

2019-07-25 00:16 UTC, kara commented on aio/content/guide/styleguide.md
> +and the `name` string should match that using *lowerCamelCase* with no hyphens.
```suggestion
and the `name` string should use *lowerCamelCase* with no hyphens.
```

2019-07-25 16:27 UTC, mary-poppins commented
You can preview 74834ab at https://pr31806-74834ab.ngbuilds.io/.

2019-08-05 15:05 UTC, jbogarthyde commented
@kara @igor Please check and approve.

2019-08-05 15:12 UTC, mary-poppins commented
You can preview 663235a at https://pr31806-663235a.ngbuilds.io/.

2019-08-05 15:12 UTC, mary-poppins commented
You can preview fb16673 at https://pr31806-fb16673.ngbuilds.io/.

2019-08-05 15:16 UTC, mary-poppins commented
You can preview 4cb698a at https://pr31806-4cb698a.ngbuilds.io/.

2019-08-06 04:55 UTC, trotyl commented on aio/content/guide/styleguide.md
> +The class name must be [UpperCamelCase](guide/glossary#case-types),
Class name is not a requirement, only preference.

2019-08-06 15:44 UTC, mary-poppins commented
You can preview 06c60a9 at https://pr31806-06c60a9.ngbuilds.io/.

2019-08-06 15:45 UTC, mary-poppins commented
You can preview ffee22a at https://pr31806-ffee22a.ngbuilds.io/.

2019-08-06 17:14 UTC, jbogarthyde commented
@kara I made your change, please check and approve.
@igor needs codeowner approval

2019-08-08 20:47 UTC, kara approved these changes
LGTM

2019-08-08 20:49 UTC, kara commented
merge-assistance: global approval

2019-08-09 17:48 UTC, closed without merging