fix(ivy): provide real source spans to locations using empty ones
angular/angular pull request #31805
Opened 2019-07-23 18:29 UTC by ayazhafiz

Some consumers of functions that take a ParseSourceSpan pass invalid or
incorrect source spans. This fixes outstanding issues of this kind.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-03-30 13:57 UTC, petebacondarwin requested changes
Just one preferred change to the `directive_spec.ts` and a couple of nits.
Also, now that 9.1.0 is out, should this target `master` and `patch`?
Thanks @ayazhafiz!!

2020-03-30 13:57 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/src/util.ts
> +}
But appears not.

2020-03-30 13:57 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/test/directive_spec.ts
>      beforeEach(() => _ = absoluteFrom);
We should move this `beforeEach()` up to the same block as the `let _`. Although at the moment there are only helpers in this block, which use the `_` function, if one were to add in additional `describe()` blocks then this could cause problems if they also called the helper functions without initializing the `_`.

2020-03-30 13:57 UTC, petebacondarwin commented on packages/compiler/src/parse_util.ts
> -
👍

2020-03-30 13:57 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/test/directive_spec.ts
> +      TestReflectionHost.hasBaseClassReturnValue = true;
I feel really uncomfortable with changing this static in a test - it is effectively a global value that you are modifying, which could have an impact on other tests if, say, this test through an exception halfway through.

Instead could you change `TestReflectionHost` to have a constructor that take a value for `hasBaseClassReturnValue` and pass that through as a parameter on `analyzeDirective()`?

```ts
  class TestReflectionHost extends TypeScriptReflectionHost {
    constructor(checker: ts.TypeChecker, private hasBaseClassReturnValue = false) {
      super(checker);
    }

    hasBaseClass(_clazz: ClassDeclaration): boolean {
      return this.hasBaseClassReturnValue;
    }
  }
```

```ts
  function analyzeDirective(program: ts.Program, dirName: string, hasBaseClassReturnValue: boolean = false) {
    const checker = program.getTypeChecker();
    const reflectionHost = new TestReflectionHost(checker, hasBaseClassReturnValue);
    ...
  }
```

2020-03-30 19:42 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/util.ts
> +      new ParseSourceFile(node.getSourceFile().getFullText(), node.getSourceFile().fileName);
```suggestion
      new ParseSourceFile(sf.getFullText(), sf.fileName);
```

2020-03-30 19:42 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
> +  let bindings: ParsedHostBindings = parseHostBindings({});
It took me a while to see why this was changed like this. I would prefer the initialization using `parseHostBindings({})` to be an `else` clause to the below `if`, and leave `bindings` uninitialized here.

2020-03-30 19:42 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/util.ts
> +  const [startOffset, endOffset] = [node.getStart(), node.end];
Any reason why this uses `getStart()` vs `.end`, and not `getEnd()`?

2020-03-30 19:42 UTC, JoostK commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +      const compSrc = `
Any reason why this is assigned into a variable?

2020-03-30 19:42 UTC, JoostK commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +      expect(errors[0].start).toBe(143);
Consider doing something like this to extract the diagnostic's location:

https://github.com/angular/angular/blob/31bec8ce61c96a4a340463997ee6b916392fe0a1/packages/compiler-cli/test/ngtsc/template_typecheck_spec.ts#L1843-L1846

2020-03-30 19:42 UTC, JoostK commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +      expect(trim(errors[0].messageText as string)).toContain('/test.ts@7:17');
Why the trim if you're using `toContain`? You shouldn't need the cast if trim is removed.

2020-03-30 20:33 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/annotations/test/directive_spec.ts
>      beforeEach(() => _ = absoluteFrom);
Good call

2020-03-30 20:33 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/annotations/test/directive_spec.ts
> +      TestReflectionHost.hasBaseClassReturnValue = true;
Done. I think this test could be made a bit better in general, what it is testing seems somewhat obtuse. But we can tackle it in a separate PR.

2020-03-30 20:33 UTC, ayazhafiz commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +      const compSrc = `
fixed

2020-03-30 20:33 UTC, ayazhafiz commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +      expect(errors[0].start).toBe(143);
Done

2020-03-30 20:33 UTC, ayazhafiz commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +      expect(trim(errors[0].messageText as string)).toContain('/test.ts@7:17');
done

2020-03-30 20:33 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/annotations/src/util.ts
> +  const [startOffset, endOffset] = [node.getStart(), node.end];
fixed

2020-03-30 21:33 UTC, JoostK approved these changes

2020-03-31 15:00 UTC, petebacondarwin approved these changes

2020-03-31 15:00 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/test/directive_spec.ts
> +    }
NIT - if you are going to declare the class inside the helper then you don't need the private `hasBaseClassReturnValue` property, since you can just use the `hasBaseClass` parameter from the closure.

2020-03-31 16:55 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/annotations/test/directive_spec.ts
> +    }
truth

2020-03-31 16:55 UTC, ayazhafiz commented
Caretaker: could you run g3sync?

2020-03-31 17:05 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:303988775:BASE:303988838:1585674335001:5282bf24)

2020-03-31 20:02 UTC, AndrewKushnir commented
FYI, g3 presubmit looks good. Thank you.

2020-03-31 23:12 UTC, AndrewKushnir commented
@ayazhafiz, just wanted to mention that this PR has conflicting `PR target` labels (both `master and patch` and `master-only`). Could you please remove the one that is not needed? Thank you.

2020-04-02 21:13 UTC, kara commented
@ayazhafiz Are you still waiting on @alxhub's review?

2020-04-06 16:28 UTC, closed without merging