refactor(ivy): move directive, component and pipe factories to ngFactoryFn
angular/angular pull request #31953
Opened 2019-08-02 00:40 UTC by crisbeto

Reworks the compiler to output the factories for directives, components and pipes under a new static field called `ngFactoryFn`, instead of the usual `factory` property in their respective defs. This should eventually allow us to inject any kind of decorated class (e.g. a pipe).

**Note:** these changes are the first part of the refactor and they don't include injectables. I decided to leave injectables for a follow-up PR, because there's some more cases we need to handle when it comes to their factories. Furthermore, directives, components and pipes make up most of the compiler output tests that need to be refactored and it'll make follow-up PRs easier to review if the tests are cleaned up now.

This is part of the larger refactor for FW-1468.

2019-08-05 16:47 UTC, mhevery approved these changes

2019-08-05 16:48 UTC, mhevery commented
LGTM. Can @alxhub  review the changes as well, also @IgorMinar needs to approve the API changes.

2019-08-06 05:55 UTC, trotyl commented
Would `directiveInject()` be removed in follow-up PRs? Which could fix cross-brand-inheritance and any-brand-as-provider use cases.

2019-08-06 11:55 UTC, petebacondarwin approved these changes
For `fw-ngcc`

2019-08-13 16:04 UTC, alxhub requested changes

2019-08-13 22:13 UTC, kara requested changes

2019-08-14 08:05 UTC, crisbeto commented on packages/core/src/render3/definition.ts
> +    throw new Error(`Type ${stringify(type)} does not have 'ngFactoryFn' property.`);
Done, although the same is happening below for the `ngModuleDef`. Should I do a separate PR to make it tree-shakeable as well?

2019-08-15 09:44 UTC, crisbeto commented
All of the feedback has been addressed @kara @alxhub. Can you take another look?

2019-08-15 22:07 UTC, kara approved these changes
LGTM, 1 comment nit

2019-08-15 22:07 UTC, kara commented on packages/core/src/render3/interfaces/definition.ts
>     * Factory function used to create a new directive instance.
Can we add a quick note about why it can be null? e.g.

```suggestion
   * Factory function used to create a new directive instance.
   * Will be null initially. Populated when the factory is first requested by directive instantiation logic.
```

2019-08-16 06:35 UTC, crisbeto commented
Addressed the latest set of feedback.

2019-08-16 17:27 UTC, AndrewKushnir commented
@crisbeto could you please rebase and resolve the conflict (I'll run g3 presubmit after that)? Thank you.

2019-08-16 17:37 UTC, crisbeto commented
Rebased @AndrewKushnir.

2019-08-16 18:08 UTC, AndrewKushnir commented
Thanks @crisbeto. I've started presubmits (we can run them again if there are any additional changes):

- [VE Presubmit](https://test.corp.google.com/ui#id=OCL:263806428:BASE:263806467:1565978770530:de36b073)
- [Ivy Presubmit](http://test/OCL:263806428:BASE:263806806:1565978847775:6fbd52de)

2019-08-16 18:26 UTC, alxhub requested changes

2019-08-16 18:26 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/factory.ts
> +    metadata: R3FactoryFnMetadata, metadataStatement: Statement | null,
Let's move `metadataStatement` out of here since it's not a concern of the factory system. Also, we can put `isPipe` in `R3FactoryFnMetadata`.

2019-08-16 18:26 UTC, alxhub commented on packages/compiler/src/render3/r3_factory.ts
> +  deps: R3DependencyMetadata[]|null;
I don't think this should be `null`able. A factory function _always_ requires dependencies (it might be `[]`, though).

2019-08-16 18:26 UTC, alxhub commented on packages/compiler/src/render3/r3_factory.ts
> +export function compileFactoryFunction(meta: R3FactoryMetadata, isPipe = false):
As mentioned, move `isPipe` into `R3FactoryMetadata`.

2019-08-16 18:26 UTC, alxhub commented on packages/compiler/src/render3/r3_factory.ts
> +        // TODO(crisbeto): this should be refactored once we start using it for injectables.
We can pass the injection function to use in `R3FactoryFnMetadata`.

2019-08-16 18:26 UTC, alxhub commented on packages/core/src/render3/jit/directive.ts
> +function getComponentCompilerOutput(type: Type<any>, metadata: Component) {
Maybe `compileComponentFields`? Also please explicitly specify the return type.

2019-08-16 18:26 UTC, alxhub commented on packages/core/src/render3/jit/directive.ts
> +        [ngComponentDef, ngFactoryFn] = getComponentCompilerOutput(type, metadata);
Doesn't this result in jitting the componentdef/factorydef twice?

Reading `ngFactoryFn` should only JIT the factory, and reading `ngComponentDef` should only JIT the component.

2019-08-16 18:26 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/factory.ts
> +export function getNgFactoryFnCompileResult(
```suggestion
export function compileNgFactoryField(
```

2019-08-16 18:26 UTC, alxhub commented on packages/compiler/src/jit_compiler_facade.ts
> +      this.jitExpression(
This function (`compileComponent`) and the other decorator compilers on the facade should not be involved in factory generation. We should introduce an additional facade method `compileFactory` for this purpose.

2019-08-17 13:02 UTC, crisbeto commented on packages/compiler/src/render3/r3_factory.ts
> +        // TODO(crisbeto): this should be refactored once we start using it for injectables.
That's what I meant with the TODO, but when I tried doing it I had some issues when importing the proper symbols. I decided to leave it for the next PR since it's not necessary in this one and the current PR is big enough as it is.

2019-08-17 15:12 UTC, crisbeto commented
@alxhub I've implemented (almost) all of the comments from the latest set of feedback. Can you take another look? It's all in the last `fixup` commit. 

Note that I had to revert the changes [from this comment](https://github.com/angular/angular/pull/31953#discussion_r314834983), because making the `deps` non-nullable ended up breaking one test in ngtsc ("generates base factories for directives"). It looks like we have some logic that treats the `deps` differently depending on whether they're `null` or an empty array (see `validateConstructorDependencies`). Furthermore, I went with making it nullable in the first place, because that's how we're treating it in the metadata for pipes, directives and components, and it makes it easier to pass the metadata around.

2019-08-19 22:18 UTC, alxhub commented on packages/compiler/src/render3/r3_factory.ts
> +  deps: R3DependencyMetadata[]|null;
You're right, actually, it should be nullable. `null` means the deps were inherited from the base class.

2019-08-19 22:25 UTC, alxhub commented on packages/compiler/src/compiler_facade_interface.ts
> +      meta: R3PipeMetadataFacade|R3DirectiveMetadataFacade|R3ComponentMetadataFacade,
Technically speaking, this isn't correct. `compileFactory` should take an `R3FactoryMetadataFacade` interface, and we should remove `deps`, etc. completely from `R3DirectiveMetadata` and its facade.

Regardless, this is okay for now. Let's get this change in and clean it up later.

2019-08-19 22:25 UTC, alxhub approved these changes

2019-08-20 16:44 UTC, AndrewKushnir commented
- [VE Presubmit](http://test/OCL:264402681:BASE:264402706:1566319412929:d35bb643)
- [Ivy Presubmit](http://test/OCL:264402681:BASE:264402891:1566319469675:946b1f04)

2019-08-20 17:11 UTC, AndrewKushnir commented
FYI, discussed with @crisbeto offline: due to the number of files changed in this PR, I will run Global TAP tonight, to make sure it's not breaking any g3 targets.

2019-08-21 00:26 UTC, IgorMinar requested changes

2019-08-21 00:26 UTC, IgorMinar commented on tools/public_api_guard/common/common.d.ts
> +    static ngFactoryFn: any;
I believe the type of this as well as the ngDirectiveDef above should be `never` as we don't want to commit to these static properties be a public api. Can you please update both? thanks

2019-08-21 00:26 UTC, IgorMinar commented on tools/public_api_guard/common/common.d.ts
> +    static ngFactoryFn: any;
same as below.

2019-08-21 00:26 UTC, IgorMinar commented on packages/core/test/render3/view_container_ref_spec.ts
> +              static ngComponentDef = ɵɵdefineComponent({
isn't the indentation off here?

2019-08-21 00:26 UTC, IgorMinar commented on tools/public_api_guard/common/common.d.ts
> +    static ngFactoryFn: any;
have we considered calling this field just `ngFactory` as opposed to `ngFactoryFn`? "Fn" suffix in api of this importance is a red flag to me, especially since in the case of a "Factory" it doesn't really add more semantic value to the reader.

2019-08-21 02:03 UTC, AndrewKushnir commented
- [VE Presubmit](https://test.corp.google.com/ui#id=OCL:264473317:BASE:264473567:1566338047364:ac8fbf5f)
- [VE Global Presubmit](https://test.corp.google.com/OCL:264473317:BASE:264517331:1566352895169:cb228f9f)
- [Ivy Presubmit](http://test/OCL:264472911:BASE:264473913:1566338159680:740f21c5)
- [Ivy Global Presubmit](https://test.corp.google.com/OCL:264472911:BASE:264517673:1566352981362:90ee0a23)

2019-08-21 18:23 UTC, crisbeto commented on packages/core/test/render3/view_container_ref_spec.ts
> +              static ngComponentDef = ɵɵdefineComponent({
It is. For some reason `clang-format` behaves weirdly with multiple static properties. It seems to have gotten back to normal if I turn it into a multi-line arrow function.

2019-08-21 19:50 UTC, crisbeto commented
@IgorMinar I've addressed the feedback. Can you take another look? Note that I had to revert the change about setting the `ngDirectiveDef` and `ngFactory` of `NgClass` and `NgStyle` to `never`, because they caused some compilation errors like:

```
node_modules/@angular/common/src/directives/ng_class.d.ts:68:22 - error TS2417: Class static side 'typeof NgClass' incorrectly extends base class static side 'typeof NgClassBase'.
  Types of property 'ngDirectiveDef' are incompatible.
    Type 'DirectiveDef<NgClass>' is not assignable to type 'never'.
```

2019-08-21 21:48 UTC, mhevery commented on tools/public_api_guard/common/common.d.ts
> +    static ngFactoryFn: any;
Sorry to be even more pain, but why is it not `ngFactoryDef` to be consistent with the other naming?

2019-08-21 21:50 UTC, mhevery commented on packages/common/src/directives/ng_class.ts
> +  static ngFactory: any = ngClassFactory;
this should be `ngFactoryDef` to be consistent with `ngDirectiveDef` etc...

2019-08-21 23:16 UTC, AndrewKushnir commented
FYI, Global TAP runs for VE and Ivy look normal. Thank you.

2019-08-27 20:57 UTC, closed without merging