fix(language-service): Make Definition and QuickInfo compatible with TS LS
angular/angular pull request #31972
Opened 2019-08-02 18:45 UTC by kyliau

Now that the Angular LS is a proper tsserver plugin, it does not make
sense for it to maintain its own language service API.

This is part one of the effort to remove our custom LanguageService
interface.
This interface is cumbersome because we have to do two transformations:
  ng def -> ts def -> lsp definition

The TS LS interface is more comprehensive anyway, so this allows the Angular LS
to return more information.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-08-02 20:52 UTC, ayazhafiz commented on packages/language-service/src/definitions.ts
> +import * as ts from 'typescript';
Can you add the comment about this being loaded at runtime and not compile time?

2019-08-02 20:52 UTC, ayazhafiz commented on packages/language-service/src/hover.ts
> +const SYMBOL_SPACE = ts.SymbolDisplayPartKind[ts.SymbolDisplayPartKind.space];
```suggestion
const SYMBOL_SPACE: string = ts.SymbolDisplayPartKind[ts.SymbolDisplayPartKind.space];
```

2019-08-02 20:52 UTC, ayazhafiz commented on packages/language-service/src/hover.ts
> +const SYMBOL_PUNC = ts.SymbolDisplayPartKind[ts.SymbolDisplayPartKind.punctuation];
```suggestion
const SYMBOL_PUNC: string = ts.SymbolDisplayPartKind[ts.SymbolDisplayPartKind.punctuation];
```

2019-08-02 20:52 UTC, ayazhafiz commented on packages/language-service/src/hover.ts
> +    // 'kind' in displayParts does not really matter.
Why does it not really matter?

2019-08-02 20:52 UTC, ayazhafiz commented on packages/language-service/src/language_service.ts
> +import * as tss from 'typescript/lib/tsserverlibrary';
```suggestion
import * as tss from 'typescript/lib/tsserverlibrary'; // types only
```

2019-08-02 20:52 UTC, ayazhafiz commented on packages/language-service/src/ts_plugin.ts
> +      options: tss.GetCompletionsAtPositionOptions | undefined) {
Can this be optional, or is better for consumers to explicitly pass `undefined`?

2019-08-02 20:52 UTC, ayazhafiz commented on packages/language-service/src/ts_plugin.ts
> +      fileName: string, position: number): ReadonlyArray<tss.DefinitionInfo>|undefined {
For later: maybe we can make everything here `ReadOnly`

2019-08-02 20:52 UTC, ayazhafiz commented on packages/language-service/src/ts_plugin.ts
> +    const {textSpan} = definitions[0];
Is there a way to display multiple definitions?

2019-08-02 20:52 UTC, ayazhafiz commented on packages/language-service/src/types.ts
> +
nit: extra line

2019-08-02 20:52 UTC, ayazhafiz commented on packages/language-service/test/definitions_spec.ts
> +function spanToTextSpan(span: Span): ts.TextSpan {
For later: consider namespacing Angular types as well to reduce ambiguity. Right now it still takes a second to recognize this is an `ng.Span` and not a `ts.Span`

2019-08-02 22:49 UTC, kyliau commented on packages/language-service/test/definitions_spec.ts
> +function spanToTextSpan(span: Span): ts.TextSpan {
done. Also added docs for the function.

2019-08-02 22:51 UTC, kyliau commented on packages/language-service/src/ts_plugin.ts
> +      fileName: string, position: number): ReadonlyArray<tss.DefinitionInfo>|undefined {
Because the plugin is a proxy for TS Language Service, the signatures are kept exactly the same. Please see https://github.com/microsoft/TypeScript/blob/e75972cbad4390057e9f531a5e5e9a945d8a2890/lib/tsserverlibrary.d.ts#L4925

2019-08-02 22:52 UTC, kyliau commented on packages/language-service/src/ts_plugin.ts
> +      options: tss.GetCompletionsAtPositionOptions | undefined) {
This has to be an explicit `undefined`.
Please see https://github.com/microsoft/TypeScript/blob/e75972cbad4390057e9f531a5e5e9a945d8a2890/lib/tsserverlibrary.d.ts#L4915

2019-08-02 22:59 UTC, kyliau commented on packages/language-service/src/definitions.ts
> +import * as ts from 'typescript';
done.

2019-08-02 23:01 UTC, kyliau commented on packages/language-service/src/hover.ts
> +    // 'kind' in displayParts does not really matter.
It is dropped when `displayParts` get converted to string.
Added comment in the code.

2019-08-05 18:34 UTC, kyliau commented on packages/language-service/src/ts_plugin.ts
> +    const {textSpan} = definitions[0];
this is a bug, and added tests to catch that.

2019-08-05 22:01 UTC, kyliau commented
@ayazhafiz, ready for round 2 review. Mostly revamped `definitions_spec.ts`. PTAL, thank you.

2019-08-05 22:18 UTC, ayazhafiz requested changes

2019-08-05 22:18 UTC, ayazhafiz commented on packages/language-service/src/hover.ts
> +    kindModifiers: '',  // kindModifier info not available on 'Symbol'
nit: say this is an Angular `Symbol` and not a TS `Symbol`

2019-08-05 22:29 UTC, kyliau commented on packages/language-service/src/hover.ts
> +    kindModifiers: '',  // kindModifier info not available on 'Symbol'
done.

2019-08-05 22:31 UTC, ayazhafiz approved these changes

2019-08-08 19:03 UTC, closed without merging