Update HTTP guide
angular/angular pull request #32045
Opened 2019-08-07 17:45 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
 HTTP guide needs work -- long and confusing

Issue Number: N/A

## What is the new behavior?
Edit and reorganize content - from unfinished PR https://github.com/angular/angular/pull/28519

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-08-07 17:52 UTC, mary-poppins commented
You can preview 093c698 at https://pr32045-093c698.ngbuilds.io/.

2019-08-12 16:46 UTC, mary-poppins commented
You can preview 81e59d9 at https://pr32045-81e59d9.ngbuilds.io/.

2019-08-13 05:10 UTC, alxhub requested changes

2019-08-13 05:10 UTC, alxhub commented on aio/content/guide/http.md
> +Specifying the response object type tells the TypeScript compiler about the response type, but it does not type-cast the response from the server.
I think this statement could be made stronger. Specifying the response type is a declaration to TypeScript that it should expect your response to be of the given type. Nothing at runtime validates that the server returns a response of the expected type. You should validate this condition yourself if it's possible for your server response to not be of the correct shape.

Also, you should use an `interface` here and not a `class` type - nothing will automatically convert the response to instances of classes.

2019-08-13 05:10 UTC, alxhub commented on aio/content/guide/http.md
> + When you pass an interface or a class as a type parameter to the `HttpClient.get()` method, use the RxJS `map` operator to read the response data. Angular parses the response with `JSON.parse()`, bu
```suggestion
 When you pass an interface as a type parameter to the `HttpClient.get()` method, use the RxJS `map` operator to read the response data. Angular parses the response with `JSON.parse()`, but does not instantiate an object of the type parameter.
```

(changed to not mention classes)

Also, I think this section is misleading - `map` should be used to transform data, it has no special connection with type parameters. The role of `map` is to convert from the model the server returns to the model needed by the UI, so that subscribing can be done with the `async` pipe.

2019-08-13 05:10 UTC, alxhub commented on aio/content/guide/http.md
> +Follow the pattern for subscribing to observables and use the RxJS `map` operator to manipulate the results.
Same point about `map` as above - its role is to transform the response before the `async` pipe.

2019-08-13 05:10 UTC, alxhub commented on aio/content/guide/http.md
> +If the term were "foo", the GET request URL would be `api/heroes/?name=foo`.
```suggestion
If the term were "foo", the GET request URL would be `api/heroes?name=foo`.
```

2019-08-13 05:10 UTC, alxhub commented on aio/content/guide/http.md
> +The `HttpParams` are immutable so you'll have to use the `set()` method to update the options.
The result of immutability is that you have to _save the return value_ of `.set()`, not just call it.

2019-08-13 05:10 UTC, alxhub commented on aio/content/guide/http.md
> +1. `distinctUntilChanged()` - wait until the search text changes.
`1. 2. 3.` ?

2019-08-13 16:29 UTC, mary-poppins commented
You can preview 5a3821d at https://pr32045-5a3821d.ngbuilds.io/.

2019-08-13 17:06 UTC, jbogarthyde commented on aio/content/guide/http.md
>  You can't write `data.heroesUrl` because TypeScript correctly complains that the `data` object from the service does not have a `heroesUrl` property.
Restructured these sections - please check.

2019-08-13 17:43 UTC, jbogarthyde commented on aio/content/guide/http.md
> + When you pass an interface or a class as a type parameter to the `HttpClient.get()` method, use the RxJS `map` operator to read the response data. Angular parses the response with `JSON.parse()`, bu
Please check

2019-08-13 17:58 UTC, mary-poppins commented
You can preview 853a538 at https://pr32045-853a538.ngbuilds.io/.

2019-08-14 15:55 UTC, mary-poppins commented
You can preview ad9916f at https://pr32045-ad9916f.ngbuilds.io/.

2019-08-19 15:56 UTC, mary-poppins commented
You can preview d16c6f4 at https://pr32045-d16c6f4.ngbuilds.io/.

2019-08-19 16:34 UTC, mary-poppins commented
You can preview 662ec0f at https://pr32045-662ec0f.ngbuilds.io/.

2019-08-20 18:01 UTC, mary-poppins commented
You can preview 041d9b7 at https://pr32045-041d9b7.ngbuilds.io/.

2019-08-21 15:52 UTC, mary-poppins commented
You can preview e965f68 at https://pr32045-e965f68.ngbuilds.io/.

2019-08-21 18:31 UTC, IgorMinar approved these changes
please make the suggested adjustments, otherwise lgtm. thanks!

2019-08-21 18:31 UTC, IgorMinar commented on aio/content/guide/http.md
> +</div>
I suggest we delete everything in between "JSONP treats..." and here. This is general info about JSOP which can be obtained from the link I proposed above. We should try to avoid documenting things that are not Angular specific.

2019-08-21 18:31 UTC, IgorMinar commented on aio/content/guide/http.md
> +The `(keyup)` event binding sends every keystroke to the component's `search()` method.
```suggestion
The `keyup` event binding sends every keystroke to the component's `search()` method.
```

2019-08-21 18:31 UTC, IgorMinar commented on aio/content/guide/http.md
> +that can also produce values for itself by calling `next(value)`,
```suggestion
that can also emit values for itself by calling `next(value)`,
```

2019-08-21 18:31 UTC, IgorMinar commented on aio/content/guide/http.md
> +1. If a previous search request is still _in-flight_ (as when the connection is poor),
```suggestion
1. If a previous search request is still _in-flight_ (as when the network connection is poor),
```

2019-08-21 18:40 UTC, IgorMinar commented on aio/content/guide/http.md
> +The `HttpClient.get()` method parses the JSON server response into the anonymous Object type. The TypeScript compiler cannot recognize properties in an Object, as it can in a class.
upon further reading this whole section (from this line until "Reading full response", except for the "important" callout about build vs runtime validation) is confusing.

I think what the text is trying to say is that if you don't specify the type in the `get` call as in `.get<Config>(...)` and instead you just do `.get(...)`, you will be handed an generic `Object` type and you will be forced to cast it to something else in order to be able to access any of the properties.

I think it is unnecessary to document how not to use the api, and then having to explain why not do it that way. We should instead focus on showing the best practice - providing the type via the `.method<Type>(...)` TypeScript syntax which ensures that the types flow correctly in any of the subsequent code.

2019-08-21 18:41 UTC, IgorMinar commented on aio/content/guide/http.md
> +The `HttpClient.get()` method parses the JSON server response into the anonymous Object type. The TypeScript compiler cannot recognize properties in an Object, as it can in a class.
so what I'm suggesting is that we remove all of these paragraphs and keep just the callout.

2019-08-21 20:49 UTC, mary-poppins commented
You can preview d251fa6 at https://pr32045-d251fa6.ngbuilds.io/.

2019-08-21 20:50 UTC, mary-poppins commented
You can preview 7cfe0ca at https://pr32045-7cfe0ca.ngbuilds.io/.

2019-08-21 20:54 UTC, mary-poppins commented
You can preview 37da89e at https://pr32045-37da89e.ngbuilds.io/.

2019-08-21 21:22 UTC, alxhub approved these changes

2019-08-21 21:22 UTC, alxhub commented on aio/content/guide/http.md
> +You can't write `data.heroesUrl` because TypeScript correctly complains that the data object from the service does not have a `heroesUrl` property.
This is still not true - `data['heroesUrl'] and `data.heroesUrl` are the same in TypeScript, with the same type-checking rules applied. There isn't a circumstance where the former is valid and the latter isn't.

2019-08-21 21:22 UTC, alxhub commented on aio/content/guide/http.md
> + When you pass an interface as a type parameter to the `HttpClient.get()` method, use the RxJS `map` operator to transform the response data  as needed by the UI. You can then pass the transformed da
```suggestion
 When you pass an interface as a type parameter to the `HttpClient.get()` method, use the RxJS `map` operator to transform the response data as needed by the UI. You can then pass the transformed data to the [async pipe](api/common/AsyncPipe).
```

Otherwise this rewording looks good!

2019-08-21 21:22 UTC, alxhub commented on aio/content/guide/http.md
> +1. If a previous search request is still _in-flight_ (as when the network connection is poor),
```suggestion
2. If a previous search request is still _in-flight_ (as when the network connection is poor),
```

2019-08-21 21:22 UTC, alxhub commented on aio/content/guide/http.md
> +1. It returns service responses in their original request order, even if the
```suggestion
3. It returns service responses in their original request order, even if the
```

2019-08-21 21:35 UTC, jbogarthyde commented on aio/content/guide/http.md
> +You can't write `data.heroesUrl` because TypeScript correctly complains that the data object from the service does not have a `heroesUrl` property.
I'm just removing the whole paragraph, I hope that works.

2019-08-21 21:44 UTC, mary-poppins commented
You can preview 2a8c292 at https://pr32045-2a8c292.ngbuilds.io/.

2019-08-22 13:40 UTC, closed without merging