docs: update readme
angular/angular pull request #32084
Opened 2019-08-09 17:18 UTC by sjtrimble

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Updated README file to improve usability

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-08-09 17:18 UTC, sjtrimble commented
Need to add a few images still.

Initial design (not pixel perfect, just for reference):
![readme-redesign](https://user-images.githubusercontent.com/2958442/62796847-106a4380-ba8f-11e9-9ac7-a3c404078901.png)

2019-08-09 20:31 UTC, gkalpak reviewed
In general, I believe it is better to use markdown as much as possible and only resort to HTML if absolutely necessary.

2019-08-09 20:31 UTC, gkalpak commented on README.md
> +  <img src="aio/assets/images/logos/angular/angular.svg" alt="angular-logo" width="60px" height="60px>
Missing closing quote for `height`.

2019-08-09 20:31 UTC, gkalpak commented on README.md
> +    </br> using Typescript/JavaScript and other languages.</i>
It's `<br>` or `<br />` :grin:

2019-08-09 20:33 UTC, gkalpak commented on README.md
> +  <img src="aio/assets/images/logos/angular/angular.svg" alt="angular-logo" width="60px" height="60px>
BTW, shouldn't it be "aio**/src**/assets/..."?

2019-08-09 20:45 UTC, sjtrimble commented
Currently broken ... can't get the second image to show up.

2020-02-09 03:04 UTC, ajitsinghkaler commented
@sjtrimble @gkalpak this seems nearly complete is there a blocker for this, If needed I can help on this

2020-02-10 03:35 UTC, sjtrimble commented
@ajitsinghkaler If you'd like to help -> could you help me to get the second image to show up? I think the `md` is not formatted properly and it's causing formatting issues.

2020-02-10 18:06 UTC, ajitsinghkaler commented
@sjtrimble can you please tell me which image is not loading

2020-08-13 22:34 UTC, sjtrimble commented
I think this is ready for another review :) @ajitsinghkaler @gkalpak

2020-08-20 18:39 UTC, gkalpak requested changes

2020-08-20 18:39 UTC, gkalpak commented on README.md
> +  <a href="https://github.com/">Contributing Guidelines</a>
```suggestion
  <a href="CONTRIBUTING.md">Contributing Guidelines</a>
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
> +  <a href="https://github.com/">Submit an Issue</a>
```suggestion
  <a href="https://github.com/angular/angular/issues">Submit an Issue</a>
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
> +  </p>
```suggestion
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
> +  <a href="https://circleci.com/gh/angular/workflows/angular/tree/master" rel="nofollow" alt="CLI Status"><img src="https://circleci.com/gh/angular/angular/tree/master.svg?style=shield"></a>
```suggestion
  <a href="https://circleci.com/gh/angular/workflows/angular/tree/master" rel="nofollow" alt="CI Status"><img src="https://circleci.com/gh/angular/angular/tree/master.svg?style=shield"></a>
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
> +  <a href="https://circleci.com/gh/angular/workflows/angular/tree/master" rel="nofollow" alt="CLI Status"><img src="https://circleci.com/gh/angular/angular/tree/master.svg?style=shield"></a>
Why the `rel="nofollow"` part (here and below)?

2020-08-20 18:39 UTC, gkalpak commented on README.md
> +  <a href="https://www.browserstack.com/automate/public-build/LzF3RzBVVGt6VWE2S0hHaC9uYllOZz09LS1BVjNTclBKV0x4eVRlcjA4QVY1M0N3PT0=--eb4ce8c8dc2c1c5b2b5352d473ee12a73ac20e06" rel="nofollow" alt="Brows
```suggestion
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
> +- Install [Node.js]
This is not a link.

2020-08-20 18:39 UTC, gkalpak commented on README.md
> + ## Setup
"Setup" is a little vague imo. It could mean setting up for development on the angular/angular repo.
I would suggest using a more descriptive title.

2020-08-20 18:39 UTC, gkalpak commented on README.md
> +- Install Node Package Manager
A link to npm would be in order, but...
...this is a little confusing, because `npm` is installed alongside Node.js (it is not a separate install).

2020-08-20 18:39 UTC, gkalpak commented on README.md
> + ### Setting Up
```suggestion
### Setting Up
```

Again, consider using a more descriptive name.

2020-08-20 18:39 UTC, gkalpak commented on README.md
> + Create workspace:
```suggestion
Create workspace:
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
> + Run the application:
```suggestion
Run the application:
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
> + ```
Remove leading whitespace.

2020-08-20 18:39 UTC, gkalpak commented on README.md
> + ### Contributing Guidelines
```suggestion
[Learn about the latest improvements][changelog].

## Upgrading
Check out our [upgrade guide](https://update.angular.io/) to find out the best way to upgrade your project.


 ## Contributing

### Contributing Guidelines
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
>  [contributing]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md
This could be:

```suggestion
[contributing]: CONTRIBUTING.md
```

Same for `[changelog]` below.

2020-08-20 18:39 UTC, gkalpak commented on README.md
> +Read through our [contributing guidelines][contributing] to learn about how to submission process, coding rules and more.
```suggestion
Read through our [contributing guidelines][contributing] to learn about our submission process, coding rules and more.
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
> + ### Want to Help?
```suggestion
### Want to Help?
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
> + Want to file a bug, contribute some code, or improve documentation? Excellent! Read up on our guidelines for [contributing][contributing] and then check out one of our issues in the [hotlist: commun
```suggestion
Want to file a bug, contribute some code, or improve documentation? Excellent! Read up on our guidelines for [contributing][contributing] and then check out one of our issues in the [hotlist: community-help](https://github.com/angular/angular/labels/hotlist%3A%20community-help).
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
> + ### Code of Conduct
```suggestion
### Code of Conduct
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
> +Conduct][codeofconduct].
```suggestion
Help us keep Angular open and inclusive. Please read and follow our [Code of Conduct][codeofconduct].
```

Also, the `codeofconduct` link is missing.

2020-08-20 18:39 UTC, gkalpak commented on README.md
> + ## Community
```suggestion
## Community
```

2020-08-20 18:39 UTC, gkalpak commented on README.md
> +<p><strong>Love Angular? Give our repo a star :star: :arrow_up:.</strong></p>
```suggestion
[![Love Angular badge](https://img.shields.io/badge/angular-love-blue?logo=angular&angular=love)](https://www.github.com/angular/angular)

**Love Angular? Give our repo a star :star: :arrow_up:.**
```

2020-08-20 21:06 UTC, sjtrimble commented on README.md
> +  <a href="https://www.angular.io"><strong>www.angular.io</strong></a>
Why remove the www? I think it helps make it clear that it's a website.

2020-08-20 21:10 UTC, sjtrimble commented on README.md
> +  <a href="https://circleci.com/gh/angular/workflows/angular/tree/master" rel="nofollow" alt="CLI Status"><img src="https://circleci.com/gh/angular/angular/tree/master.svg?style=shield"></a>
Not sure what it's for - I think that's how it was or how it comes over from the shield images

2020-08-20 21:13 UTC, sjtrimble commented on README.md
> +- Install [Node.js]
Will add link, thanks!

2020-08-20 21:14 UTC, sjtrimble commented on README.md
> + ## Setup
Yeah, good point. I'll change it to *"Development Setup"*. I had originally kept it as Setup to be consistent with the AIO docs but in this case I think the further clarification helps.

2020-08-20 21:17 UTC, sjtrimble commented on README.md
> +- Install Node Package Manager
I do think [this link](https://docs.npmjs.com/cli/install)  would help - I can use one of the links we references in the [AIO docs](https://angular.io/guide/setup-local#prerequisites)

2020-08-20 21:17 UTC, sjtrimble commented on README.md
> + ### Setting Up
You're too good at this :P

2020-08-20 21:19 UTC, sjtrimble commented on README.md
> + Run the application:
I think I thought I needed this for spacing of sorts? Not sure, will see how it looks after I push it.

2020-08-20 21:20 UTC, sjtrimble commented on README.md
> + ```
I assume you mean line 70, the white line/spaces before the triple back-tick?

2020-08-24 09:53 UTC, gkalpak commented on README.md
> + ```
On line 69, the whitespace before the tripple back-tick.

2020-08-24 09:56 UTC, gkalpak commented on README.md
> +  <a href="https://www.angular.io"><strong>www.angular.io</strong></a>
The canonical URL is without the `www.` We redirect `www.angular.io` to `angular.io`, so both will work and the user will end up on angular.io in both cases.

I don't feel strongly about it, so leaving it up to you.

2020-08-24 11:36 UTC, gkalpak requested changes

2020-08-24 11:36 UTC, gkalpak commented on README.md
> +  <a href="https://www.browserstack.com/automate/public-build/LzF3RzBVVGt6VWE2S0hHaC9uYllOZz09LS1BVjNTclBKV0x4eVRlcjA4QVY1M0N3PT0=--eb4ce8c8dc2c1c5b2b5352d473ee12a73ac20e06" alt="Browser Stack"><img
```suggestion
```

2020-08-24 11:36 UTC, gkalpak commented on README.md
> +[Node.js]: https://nodejs.org/en/
```suggestion
[Node.js]: https://nodejs.org/
```

2020-08-24 11:36 UTC, gkalpak commented on README.md
> +[Node Package Manager]: https://docs.npmjs.com/cli/install
https://docs.npmjs.com/cli/npm is probably a better link. The current link is about the `install` command of the npm CLI (which is used to install dependencies, not the npm CLI itself).

Also, it is better to use shorter link indentifiers instead of the "display text" (which includes capitalization, etc.):

```md
[Node Package Manager][npm]
...
[npm]: https://docs.npmjs.com/cli/install
```

2020-08-24 11:36 UTC, gkalpak commented on README.md
> +- Install [Node Package Manager]
I still believe that listing installing npm as a separate step is potentially confusing, because npm is typically installed alongside Node.js, so there is no extra step to do.

2020-08-24 11:36 UTC, gkalpak commented on README.md
>  [changelog]: https://github.com/angular/angular/blob/master/CHANGELOG.md
This could be just:

```suggestion
[changelog]: CHANGELOG.md
```

2020-08-24 11:36 UTC, gkalpak commented on README.md
> +Conduct][codeofconduct].
```suggestion
Help us keep Angular open and inclusive. Please read and follow our [Code of Conduct][codeofconduct].
```

2020-08-27 23:11 UTC, sjtrimble commented on README.md
> +[Node Package Manager]: https://docs.npmjs.com/cli/install
Looking back at this .. https://www.npmjs.com/get-npm might make more sense as it explains that npm is part of Node and comes with it - there's not extra step for the user. Having it as a separate link implies that there is an extra step which there is not (right?).

2020-08-27 23:12 UTC, sjtrimble commented on README.md
> +- Install [Node Package Manager]
Ahh ... just saw this comment after posting the other one saying the same thing :) glad we're on the same page!

2020-08-27 23:17 UTC, sjtrimble commented on README.md
> +  <a href="https://www.browserstack.com/automate/public-build/LzF3RzBVVGt6VWE2S0hHaC9uYllOZz09LS1BVjNTclBKV0x4eVRlcjA4QVY1M0N3PT0=--eb4ce8c8dc2c1c5b2b5352d473ee12a73ac20e06" alt="Browser Stack"><img
Do we need to replace this with something? Or just remove it all together?

2020-08-31 13:00 UTC, gkalpak commented on README.md
> +  <a href="https://www.browserstack.com/automate/public-build/LzF3RzBVVGt6VWE2S0hHaC9uYllOZz09LS1BVjNTclBKV0x4eVRlcjA4QVY1M0N3PT0=--eb4ce8c8dc2c1c5b2b5352d473ee12a73ac20e06" alt="Browser Stack"><img
Just remove it.

2020-09-09 04:38 UTC, sjtrimble commented on README.md
> +  <a href="https://www.browserstack.com/automate/public-build/LzF3RzBVVGt6VWE2S0hHaC9uYllOZz09LS1BVjNTclBKV0x4eVRlcjA4QVY1M0N3PT0=--eb4ce8c8dc2c1c5b2b5352d473ee12a73ac20e06" alt="Browser Stack"><img
Ok - I think this was the last thing to do.

2020-09-09 04:38 UTC, sjtrimble commented on README.md
> +  <a href="https://www.angular.io"><strong>www.angular.io</strong></a>
The only reason I like the `www` is because I think it would not be clear right away that `angular.io` is a website. Keeping it now as is.

2020-09-09 04:39 UTC, sjtrimble commented
@gkalpak I think everything is addressed now - will you take one final look once this updates?

2020-09-13 14:12 UTC, gkalpak requested changes
Nice! Almost lgtm :tada:

To fix CI ([failing job][1], you need to add the newly added `docs/images/` directory to a code-owner group. Currently, the `README.md` file is [owned by `dev-infra`][2] (as are [most of the files][3] in `docs/`), so it makes sense to assign `docs/images/` to the `dev-infra` too.

To do that, you need to add a new line in [.pullapprove.yml][4]:

```diff
           'docs/TRIAGE_AND_LABELS.md',
+          'docs/images/**',
           'goldens/*',
```
[1]: https://app.circleci.com/pipelines/github/angular/angular/21029/workflows/a2ccb897-57e9-4e1b-b52b-cba6b6bba3d7/jobs/802893
[2]: https://github.com/angular/angular/blob/6768fe9927ad4b9b81c5f8094c42c771d1047f56/.pullapprove.yml#L1103
[3]: https://github.com/angular/angular/blob/6768fe9927ad4b9b81c5f8094c42c771d1047f56/.pullapprove.yml#L1111-L1122
[4]: https://github.com/angular/angular/blob/6768fe9927ad4b9b81c5f8094c42c771d1047f56/.pullapprove.yml#L1122-L1123

2020-09-21 20:16 UTC, sjtrimble commented on README.md
> +Help us keep Angular open and inclusive. Please read and follow our [Code of Conduct][codeofconduct].
Added this!

2020-09-21 20:17 UTC, sjtrimble commented
@gkalpak Okay, I think I covered the remaining items. Let me know if you see anything else. We'll see how the CI does :)

2020-09-22 10:41 UTC, gkalpak approved these changes
:tada:

2020-10-15 01:48 UTC, AndrewKushnir commented
It looks like this PR is almost ready for merge!

@gkalpak @sjtrimble, could you please rebase this PR and resolve the conflict, so that we re-run the CI and proceed with the merge?

Thank you.

2020-10-15 01:50 UTC, AndrewKushnir approved these changes

2020-10-15 12:25 UTC, gkalpak commented
Rebased and resolved conflicts.

I also updated the badges (see images below for the difference):
- Replace Gitter with Discord (as is already done in `README.md` on master).
- Make the badges look more consistent with each other.
- Include logos.
- Add a little more horizontal space between badges.

**BEFORE:**
![ng-badges before](https://user-images.githubusercontent.com/8604205/96119868-49554200-0ef6-11eb-831f-562af61d8718.png)

##
**AFTER:**
![ng-badges after](https://user-images.githubusercontent.com/8604205/96119871-4a866f00-0ef6-11eb-8b04-5fd8295905dd.png)

2020-10-15 21:08 UTC, closed without merging