docs: add push notification usage to api doc
angular/angular pull request #32139
Opened 2019-08-14 17:05 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Developers have complained that doc is insufficient for using SwPush API.

Issue Number:  https://github.com/angular/angular/issues/22627

## What is the new behavior?
Adds usage information and links to further info to API doc:

https://angular.io/api/service-worker/SwPush

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-08-14 17:13 UTC, mary-poppins commented
You can preview 632d937 at https://pr32139-632d937.ngbuilds.io/.

2019-08-19 15:56 UTC, mary-poppins commented
You can preview 84f882e at https://pr32139-84f882e.ngbuilds.io/.

2019-08-19 17:07 UTC, AndrewKushnir commented
@jbogarthyde this PR still requires an approval (i.e. can not be merged), right?

2019-08-20 10:04 UTC, gkalpak requested changes
My main issue is with the hard-coded code snippets.
Otherwise lgtm (with some minor comments).

2019-08-20 10:04 UTC, gkalpak commented on packages/service-worker/src/push.ts
> + *
You could, also, mention that the app can subscribe to `SwPush.notificationClicks` to get notified when a user clicks on a notification. E.g.:

```ts
swPush.notificationClicks.subscribe(({action, notification}) => {  
  // TODO: Do something in response to notification click.
});
```

2019-08-20 10:04 UTC, gkalpak commented on packages/service-worker/src/push.ts
> + *   }
Incorrect indentation (but hard-coded code snippets are evil anyway 😛).

2019-08-20 18:03 UTC, mary-poppins commented
You can preview 72af6ce at https://pr32139-72af6ce.ngbuilds.io/.

2019-08-20 18:29 UTC, mary-poppins commented
You can preview d7b1714 at https://pr32139-d7b1714.ngbuilds.io/.

2019-08-20 18:52 UTC, mary-poppins commented
You can preview 7ecd947 at https://pr32139-7ecd947.ngbuilds.io/.

2019-08-20 18:53 UTC, mary-poppins commented
You can preview 60943b6 at https://pr32139-60943b6.ngbuilds.io/.

2019-08-20 18:57 UTC, mary-poppins commented
You can preview 788eb8f at https://pr32139-788eb8f.ngbuilds.io/.

2019-08-20 19:01 UTC, mary-poppins commented
You can preview 6fdf984 at https://pr32139-6fdf984.ngbuilds.io/.

2019-08-21 15:50 UTC, mary-poppins commented
You can preview 1db81b0 at https://pr32139-1db81b0.ngbuilds.io/.

2019-08-27 09:52 UTC, gkalpak requested changes

2019-08-27 09:52 UTC, gkalpak commented on packages/service-worker/src/push.ts
> + * Subscribe and listen to Web Push Notifications through Angular Service Worker.
Might be worth making `Web Push Notifications` a link to an explainer of push notifications (maybe [MDN: Web Push API Notifications best practices][1]).

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Best_Practices

2019-08-27 09:52 UTC, gkalpak commented on packages/service-worker/src/push.ts
> + *   }
Incorrect indentation (but hard-coded code snippets are evil anyway 😛).

2019-08-27 09:52 UTC, gkalpak commented on packages/service-worker/src/push.ts
> + *    }
We typically use an indentation of 2 spaces (not 3) 🤔

2019-08-27 09:52 UTC, gkalpak commented on packages/service-worker/src/push.ts
> + * An application can subscribe to `SWPush.notificationClicks` observable
`SWPush` --> `SwPush`

2019-08-27 09:52 UTC, gkalpak commented on packages/service-worker/src/push.ts
> + * and creates `Notification` instances in response.
Worth linking to [PushEvent][1] and [Notification][2].

[1]: https://developer.mozilla.org/en-US/docs/Web/API/PushEvent
[2]: https://developer.mozilla.org/en-US/docs/Web/API/Notification

2019-08-27 19:05 UTC, gkalpak commented on packages/service-worker/src/push.ts
> + *   }
Setting up examples is a little involved (but totally worth it in the long run imo).
I'll try to put something together.

2019-08-27 19:09 UTC, gkalpak commented on packages/service-worker/src/push.ts
> + *    }
Not quite :smiley: The first level has an indentation of 3 spaces instead of 2. (The second level is indentated correctly relative to its parent).

```diff
 {
-   "notification": {
-     "actions": NotificationAction[],
-     ...
+  "notification": {
+    "actions": NotificationAction[],
+    ...
   }
 }
```

I'll fix it up for you.

2019-08-27 20:39 UTC, gkalpak commented
@googlebot I consent.

2019-08-27 20:40 UTC, gkalpak approved these changes

2019-08-27 20:42 UTC, gkalpak commented
**merge-assistance:** Global approval for this (more or less) docs-only change.

2019-08-27 23:19 UTC, closed without merging