Clean up formats in template syntax guide
angular/angular pull request #32197
Opened 2019-08-19 21:45 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
 Inappropriate color coding in error messages, inconsistent heading levels.
Some style problems (choppy, too many forms of emphasis), which are historical and will be further eased by splitting this long page up into smaller chunks.

Issue Number:  https://github.com/angular/angular/issues/32026

## What is the new behavior?
Fixes color coding and heading levels, some smoothing of flow and emphasis.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-08-19 21:53 UTC, mary-poppins commented
You can preview 7966d3e at https://pr32197-7966d3e.ngbuilds.io/.

2019-08-20 17:58 UTC, mary-poppins commented
You can preview 2961a53 at https://pr32197-2961a53.ngbuilds.io/.

2019-08-21 13:09 UTC, kapunahelewong requested changes
Ok, so I know using `shell` was from me (oops!), but by comparing the preview and master, I realized we have to do it differently (details in comments). Otherwise, all great catches. Thanks, @jbogarthyde 😊

2019-08-21 13:09 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +```
Ok, so I just learned something new. We have to keep the `<code-example language="sh" class="code-shell">` because it colors it properly but ` ```shell ` doesn't work as expected. I've used it many times, it must have changed somewhere along the way 🤷🏻‍♀️🤔. You could also use `<code-example language="bash">`

2019-08-21 13:09 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +```
This one has the odd coloring in production right now, so now we know that `nocode` isn't what we want, so we can safely use `code-shell` or `bash`.

EDIT: same applies for the changes on lines 850 and 890.

2019-08-21 15:55 UTC, mary-poppins commented
You can preview 7931655 at https://pr32197-7931655.ngbuilds.io/.

2019-08-21 16:46 UTC, jbogarthyde commented
Combined and organized some redundancies, and clarified binding section organization.

2019-08-21 16:51 UTC, mary-poppins commented
You can preview aef0de2 at https://pr32197-aef0de2.ngbuilds.io/.

2019-08-27 14:36 UTC, kapunahelewong approved these changes
Thanks, Judy!

2019-08-27 23:14 UTC, closed without merging