fix(compiler): Support for combining host-context and host selectors
angular/angular pull request #32209
Opened 2019-08-20 10:03 UTC by avcs06

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #14349
```
:host-context(.a):host(.b) => .a[host].b[host], .a [host] -no-combinator.b[host]
```

## What is the new behavior?

```
:host-context(.a):host(.b) => .a.b[host], .a .b[host]
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-08-21 05:44 UTC, avcs06 commented
Hi, some of the circleci checks are failing with error
```
cp: cannot stat '.circleci/bazel.rc': No such file or directory
```

How can I fix these errors? I havent made any change related to bazel.rc

2021-01-23 21:32 UTC, petebacondarwin commented
Let's see if we can get this fix in after #40494

2021-01-24 20:36 UTC, petebacondarwin commented on packages/compiler/test/shadow_css_spec.ts
> +            .toEqual('div.x[a-host], div .x[a-host] {}');
Actually I think that this should convert to:

```
div.x[a-host] {}
```

Since having no space between the `:host-context` and `:host` classes means that it should only match the host element.

2021-01-24 20:41 UTC, petebacondarwin commented on packages/compiler/test/shadow_css_spec.ts
> +            .toEqual('div.x[a-host], div .x[a-host] {}');
And more usefully we want to fix (and test):

```
        expect(s(':host-context(div) :host(.x) {}', 'contenta', 'a-host'))
            .toEqual('div.x[a-host], div .x[a-host] {}');
```

2021-01-24 21:28 UTC, petebacondarwin requested changes
Hi @avcs06 - thanks for this PR but it does not actually fix the problems described in #14349.

Since #40494 changes this area of code significantly and this PR is not correct, I have added my proposed fix to that PR

Closing in favour of #40494 .

2021-01-24 21:28 UTC, closed without merging