docs: fixed a misleading sentence
angular/angular pull request #32211
Opened 2019-08-20 10:36 UTC by jrumandal

Reading this sentence, make the reader think that the second argument strictly accepts one single animate, which is not

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-08-20 10:44 UTC, santoshyadav198613 commented on aio/content/guide/animations.md
> +To make the change less abrupt, we need to define an animation *transition* to specify the changes that occur between one state and another over a period of time. The `transition()` function accepts
I think as per the documentation it accepts 3 parameters, and the second parameter is animate() or sequence() function,
https://angular.io/api/animations/transition

2019-08-20 15:32 UTC, jbogarthyde commented on aio/content/guide/animations.md
> +To make the change less abrupt, we need to define an animation *transition* to specify the changes that occur between one state and another over a period of time. The `transition()` function accepts
It does have a third arg, and the second arg is a set of *steps*, which are correctly described in the API doc: 
"One or more animation objects, as returned by the `animate()` or `sequence()` function, that form a transformation from one state to another."
It might be best to stick with the the name of the argument, and call it "animation steps".

Perhaps:
The [`transition()` function](api/animations/transition) accepts a *state change expression* that determines whether a transition should occur, and a set of animation steps that define the transition .

2019-08-20 15:33 UTC, jbogarthyde requested changes
Suggested amendment is more conceptual, includes link to API page

2019-08-20 15:40 UTC, jrumandal commented
@googlebot I signed it!

Il mar 20 ago 2019, 4:36 PM Judy Bogart <notifications@github.com> ha
scritto:

> *@jbogarthyde* requested changes on this pull request.
>
> Suggested amendment is more conceptual, includes link to API page
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/32211?email_source=notifications&email_token=AFQ653WKMO47MPF7PISXIPLQFQFOBA5CNFSM4INT5MOKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCCDJTDY#pullrequestreview-277256591>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFQ653WTDN6F46VHPDJ7CM3QFQFOBANCNFSM4INT5MOA>
> .
>

2019-08-20 16:24 UTC, santoshyadav198613 commented on aio/content/guide/animations.md
> +To make the change less abrupt, we need to define an animation *transition* to specify the changes that occur between one state and another over a period of time. The `transition()` function accepts
Sorry but this is not suggestion, may be it is misleading, I just wanted to tell him that it takes 3 arguments and animate or sequence function.

2019-08-20 20:49 UTC, jrumandal reviewed
Sorry, as per documentation [transition](https://angular.io/api/animations/transition), the method accepts only two arguments.
Where did you read the third argument?

EDIT: I see, its an  optional argument

2019-08-20 20:50 UTC, jrumandal commented on aio/content/guide/animations.md
> +To make the change less abrupt, we need to define an animation *transition* to specify the changes that occur between one state and another over a period of time. The `transition()` function accepts
Sorry, as per documentation animate, the method accepts only two arguments.
Where did you read the third argument?

2019-08-20 20:54 UTC, santoshyadav198613 commented on aio/content/guide/animations.md
> +To make the change less abrupt, we need to define an animation *transition* to specify the changes that occur between one state and another over a period of time. The `transition()` function accepts
You are writing about transition function here which takes 3 arguments of course third parameter is optional, and second parameter is animate or sequence function.

2019-08-20 21:52 UTC, jrumandal reviewed
Improved interpretation

2019-09-18 16:00 UTC, matsko approved these changes

2019-10-08 17:01 UTC, jbogarthyde approved these changes
Looks ok.

2019-10-10 20:54 UTC, closed without merging