docs: add ng deploy to the deployment guide
angular/angular pull request #32227
Opened 2019-08-20 23:16 UTC by mgechev

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [TOOL-1008](https://angular-team.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=TOOL&modal=detail&selectedIssue=TOOL-1008)

## What is the new behavior?

Added `ng deploy` to the deployment guide.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-08-21 07:45 UTC, JohannesHoppe commented on aio/content/guide/deployment.md
> +| [`angular-cli-ghpages`](https://npmjs.org/package/@angular/fire)     | Deployment to [GitHub pages](https://pages.github.com/)                    |
Typo: Wrong URLs here for the npm packages!

Personally, I would prefer it if you would link to the official website of the projects - which in all cases should be the Github address. Why? Because here you immediately see important hints in the README and not at the next version change of the package.

* https://github.com/angular/angularfire2
* https://github.com/Azure/ng-deploy-azure
* https://github.com/zeit/ng-deploy-now
* https://github.com/ngx-builders/netlify-builder
* https://github.com/angular-schule/angular-cli-ghpages

2019-08-21 10:37 UTC, santoshyadav198613 commented on aio/content/guide/deployment.md
> +| [`angular-cli-ghpages`](https://npmjs.org/package/@angular/fire)     | Deployment to [GitHub pages](https://pages.github.com/)                    |
I think the package link is repeated for all.

2019-08-21 12:21 UTC, JohannesHoppe commented on aio/content/guide/deployment.md
> +| [`angular-cli-ghpages`](https://npmjs.org/package/@angular/fire)     | Deployment to [GitHub pages](https://pages.github.com/)                    |
That's for sure!

2019-08-21 15:07 UTC, mary-poppins commented
You can preview 986ccbe at https://pr32227-986ccbe.ngbuilds.io/.

2019-08-21 15:23 UTC, jbogarthyde requested changes
Editorial changes

2019-08-21 15:23 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +| [`angular-cli-ghpages`](https://npmjs.org/package/@angular/fire)     | Deployment to [GitHub pages](https://pages.github.com/)                    |
I would put the columns the other way around -- 
`| Deploy to | Package |`
( and remove "Deployment to" from the cell contents)
You could also link directly to the README page in the npm package links.

2019-08-21 15:23 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +You can read how to use the listed deployment builders following the links associated with each package name above.
not necessary if you link to README.

2019-08-21 15:23 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +For example, to automatically deploy to Firebase via the `ng deploy` command run:
For example, the following command automatically deploys the current project to Firebase.

2019-08-21 15:23 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +The command above will:
The command is interactive. 
In this case, you must have or create a Firebase account, and authenticate using that account.  The command prompts you to select a FIrebase project for deployment

After the command produces an optimal build of your application (equivalent to `ng deploy --prod`), you must upload your assets to Firebase hosting.

2019-08-21 15:23 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +If you're deploying to a self managed server or there's no builder for your favorite cloud platform you can either:
self-managed

...cloud platform, you can either [create a builder](guide/cli-builder) that allows you to use the `ng deploy` command, or read through this guide to learn how to manually deploy your app.

2019-08-21 15:32 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +
### Automatic deployment with the CLI

2019-08-21 15:36 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +If you're deploying to a self managed server or there's no builder for your favorite cloud platform you can either:
*not sure if you are referring to the two following subsections (**Basic deployment to a remote server* and *Deploy to GitHub pages**) or to the whole rest of the page*

2019-08-21 15:37 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +- Read through the sections below to learn how to manually deploy your app
*not sure if you are referring to the two following subsections ("Basic deployment to a remote server" and "Deploy to GitHub pages") or to the whole rest of the page*

2019-08-21 16:12 UTC, JohannesHoppe commented on aio/content/guide/deployment.md
> +Angular CLI introduced `deploy` command in version 8.3.0. By default, this command will execute the `deploy` [CLI builder](https://angular.io/guide/cli-builder) associated with your project. Currentl
without "cloud" please. Not everybody wants to deploy to the cloud.

2019-08-21 18:35 UTC, mgechev commented on aio/content/guide/deployment.md
> +| [`angular-cli-ghpages`](https://npmjs.org/package/@angular/fire)     | Deployment to [GitHub pages](https://pages.github.com/)                    |
@JohannesHoppe thanks for noticing the wrong links!

I'd prefer to point to the npm packages because of the `next`, `latest` tags. By default the npm page shows the latest README, compared to GitHub which by default shows what's in `master`.

2019-08-21 18:49 UTC, jbogarthyde approved these changes
One more suggestion.

2019-08-21 18:49 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +You can read how to use the listed deployment builders following the links associated with each package name above.
Suggested: 
When you add a platform package with deployment capability, the builder is automatically added to your project configuration. Each package includes a README file that explains how to use the builder.

2019-08-21 18:51 UTC, mary-poppins commented
You can preview 5a30634 at https://pr32227-5a30634.ngbuilds.io/.

2019-08-21 19:12 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +The Angluar CLI command `ng deploy` (introduced in version 8.3.0) executes the `deploy` [CLI builder](https://angular.io/guide/cli-builder) associated with your project. A number of third-party build
typo Angluar ->Angular

2019-08-21 19:14 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +
...to the selected project. You can then use the `ng deploy` command to deploy that project.

2019-08-21 19:19 UTC, mary-poppins commented
You can preview 3abebb5 at https://pr32227-3abebb5.ngbuilds.io/.

2019-08-21 19:19 UTC, mary-poppins commented
You can preview b3a2843 at https://pr32227-b3a2843.ngbuilds.io/.

2019-08-21 19:25 UTC, mary-poppins commented
You can preview f6dc7b8 at https://pr32227-f6dc7b8.ngbuilds.io/.

2019-08-22 07:49 UTC, JohannesHoppe commented
It was a great honour to have an own section in the docs.
But "Deploy to GitHub pages" is now obsolete it should be removed entirely!

2019-08-22 17:08 UTC, mgechev commented
Let's keep it until version 10. The flow that we describe there is still going to work for older versions of the CLI.

2019-08-22 20:29 UTC, closed without merging