feat(core): add dynamic queries schematic
angular/angular pull request #32231
Opened 2019-08-21 05:12 UTC by crisbeto

Adds a schematic that will remove the explicit `static: false` flag from dynamic queries. E.g.

#### Before
```ts
import { Directive, ViewChild, ContentChild, ElementRef } from '@angular/core';

@Directive()
export class MyDirective {
  @ViewChild('child', { static: false }) child: any;
  @ViewChild('secondChild', { read: ElementRef, static: false }) secondChild: ElementRef;
  @ContentChild('thirdChild', { static: false }) thirdChild: any;
}
```

#### After
```ts
import { Directive, ViewChild, ContentChild, ElementRef } from '@angular/core';

@Directive()
export class MyDirective {
  @ViewChild('child') child: any;
  @ViewChild('secondChild', { read: ElementRef }) secondChild: ElementRef;
  @ContentChild('thirdChild') thirdChild: any;
}
```

2019-08-22 16:01 UTC, devversion approved these changes
LGTM 🎉 

Just to mention one edge case: If someone has the query options set through a variable declaration, the migration will currently do nothing. It could show a message though that the given query should be checked manually. Just mentioning this as it could make the migration more robust.

<sup>Not saying we should do it; just bringing this up for awareness; we only saw these type of queries rarely in the static-query migration<sup>.

2019-08-27 22:36 UTC, kara requested changes

2019-08-28 16:10 UTC, crisbeto commented
The feedback has been addressed @kara.

2019-09-04 18:29 UTC, kara approved these changes
LGTM, once last comment is addressed

2019-09-04 18:29 UTC, kara commented on packages/core/schematics/test/dynamic_queries_migration_spec.ts
> +  it('should not change dynamic ContentChild queries', async() => {
Looks like this change got lost in the rebase? Still says dynamic

2019-09-04 18:54 UTC, crisbeto commented on packages/core/schematics/test/dynamic_queries_migration_spec.ts
> +  it('should not change dynamic ContentChild queries', async() => {
Sorry about that, I think I messed it up when I was switching computers. It's fixed now.

2019-09-04 18:55 UTC, crisbeto commented
Rebased and addressed the last comment @kara.

2019-09-10 17:08 UTC, kara commented
[presubmit](http://test/OCL:268249985:BASE:268250017:1568135250033:63fbd00f)

2019-09-11 23:14 UTC, closed without merging