docs(language-service): update integration test information
angular/angular pull request #32269
Opened 2019-08-22 13:47 UTC by ayazhafiz

The documentation for the langauge service plugin integration test
appears to be stale. Remove section about new versions of TypeScript,
which appear not to be tested, and update the information about
generating and updating goldens to reflect the new way of doing so.
Add information about install deps in the repo root, this directory, and
building Angular before testing.

Also remove trailing whitespace on one line.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

See commit message

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-08-22 19:25 UTC, kyliau reviewed
Thanks for updating the docs!

2019-08-22 19:25 UTC, kyliau commented on integration/language_service_plugin/README.md
> +that various versions of the server can be loaded in the supported versions of
to ensure that the language service works correctly as a tsserver plugin.
We no longer tests different versions of TS.

2019-08-22 19:31 UTC, ayazhafiz commented on integration/language_service_plugin/README.md
> +that various versions of the server can be loaded in the supported versions of
Done.

2019-08-22 22:06 UTC, josephperrott approved these changes
Approval for @angular/fw-integration

2019-08-22 23:27 UTC, kyliau approved these changes

2019-08-24 01:52 UTC, ayazhafiz commented
Caretaker: Please restart test_zonejs or accept as is; it is likely flakey, as these are documentation changes.

2019-08-26 18:40 UTC, jbogarthyde requested changes
minor edits

2019-08-26 23:42 UTC, jbogarthyde approved these changes
Thanks! Looks good.

2019-08-27 16:08 UTC, closed without merging