docs: fix documentation issues in the testing and router documentation
angular/angular pull request #32329
Opened 2019-08-27 00:44 UTC by TrevorKarjanis

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

N/A

Issue Number: N/A

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-09-06 19:43 UTC, alan-agius4 commented on aio/content/guide/cli-builder.md
>      "command": {
This part is correct @kapunahelewong!

2019-09-06 19:45 UTC, kapunahelewong commented on aio/content/guide/cli-builder.md
>      "command": {
Thank you! @alan-agius4!

2019-09-06 19:49 UTC, Splaktar requested changes
LGTM other than the change to the CLI Builders doc.

2019-09-06 19:49 UTC, Splaktar commented on aio/content/guide/cli-builder.md
> +      "schema": "./src/schema.json",
These paths don't make sense in relation to the example repo that is linked in multiple parts of this doc: https://github.com/mgechev/cli-builders-demo/tree/master/command-builder

2019-09-06 19:53 UTC, kapunahelewong commented on aio/content/guide/cli-builder.md
> +      "schema": "./src/schema.json",
@TrevorKarjanis can you give us some insight on your thoughts for this particular change?

2019-09-06 19:56 UTC, alan-agius4 commented on aio/content/guide/cli-builder.md
> +      "schema": "./src/schema.json",
This code here is not in relation to the example repo, but to the code extracts and file list on the same page https://github.com/angular/angular/blob/62ac021aca3713d49cef6748ce2f9ddeeb19a140/aio/content/guide/cli-builder.md

2019-09-06 19:58 UTC, alan-agius4 commented on aio/content/guide/cli-builder.md
> +      "schema": "./src/schema.json",
See `Builder project structure` section.

2019-09-06 19:59 UTC, mary-poppins commented
You can preview 62ac021 at https://pr32329-62ac021.ngbuilds.io/.

2019-09-06 20:00 UTC, alan-agius4 commented on aio/content/guide/cli-builder.md
> +      "schema": "./src/schema.json",
https://pr32329-62ac021.ngbuilds.io/guide/cli-builder#builder-project-structure

2019-09-06 20:05 UTC, alan-agius4 commented
Something for the docs team and not related to this PR. I think for files snippets we should always have a heading with the file name

Example: https://pr32329-62ac021.ngbuilds.io/guide/i18n

2019-09-06 20:06 UTC, alan-agius4 commented on aio/content/guide/cli-builder.md
> +      "schema": "./src/schema.json",
Alternatively we can update the list of file and double check there is no reference for the old files through the page.

2019-09-06 20:32 UTC, TrevorKarjanis commented on aio/content/guide/cli-builder.md
> +      "schema": "./src/schema.json",
alan-agius4 is correct. While reading through, I associated the project structure defined at the beginning with the files created, so I was confused by the paths used here. The problem with changing these paths to "command" is that the preceding description explicitly states that the structure is, "similar in structure to an Angular workspace", and that configuration resides in a, "source folder with the code files". I understand, however, that it also states that the code from the examples is from mgechev's repository. 

I personally prefer "src" for its consistency, but I can certainly revert this change in order to remain consistent with the repository. As eluded to by alan-agius4, the long term solution may be to move these examples into the documentation.

2019-09-06 22:38 UTC, Splaktar commented on aio/content/guide/cli-builder.md
> +      "schema": "./src/schema.json",
@mgechev based on the feedback above (and the file structure in the [docs](https://angular.io/guide/cli-builder#builder-project-structure)), should the example repo be updated?

2019-09-06 22:40 UTC, Splaktar commented on aio/content/guide/cli-builder.md
> +      "schema": "./src/schema.json",
It might be best to take this CLI Builders discussion and move it into a separate, new issue report and then get this PR merged sooner w/o those changes.

2019-09-07 06:06 UTC, alan-agius4 commented on aio/content/guide/cli-builder.md
> +      "schema": "./src/schema.json",
Any reason why the example is AIO?
 Ie it’s it’s own gitrepo, this seems like a different pattern from other examples

2019-09-07 07:46 UTC, Splaktar commented on aio/content/guide/cli-builder.md
> +      "schema": "./src/schema.json",
Why it's not on AIO? I'm not sure, I think that it had something to do with the timeframe. Minko could say more. I think that it would be best to align it with the other examples when time allows.

2019-09-08 22:15 UTC, TrevorKarjanis commented on aio/content/guide/cli-builder.md
> +      "schema": "./src/schema.json",
Unless there are any objections, I will revert this change and update the PR. If we can come to a consensus, I am willing to learn to and update the source code as examples.

2019-09-09 14:33 UTC, mary-poppins commented
You can preview 794ffb5 at https://pr32329-794ffb5.ngbuilds.io/.

2019-09-09 15:00 UTC, mary-poppins commented
You can preview e98030e at https://pr32329-e98030e.ngbuilds.io/.

2019-09-09 15:41 UTC, kapunahelewong commented
Hi @TrevorKarjanis, it looks good. 😊Can you squash and tag me when you're ready? We just want one commit. For the commit message, the body of the commit doesn't have to repeat what's in the subject. In this case, you can remove the body. Maybe try just this as the commit message:

`docs: fix typos in routing and testing docs`

2019-09-09 18:23 UTC, TrevorKarjanis commented
@kapunahelewong Done.

2019-09-09 18:23 UTC, mary-poppins commented
You can preview f200d9e at https://pr32329-f200d9e.ngbuilds.io/.

2019-09-09 19:27 UTC, kapunahelewong approved these changes
LGTM. Thank you, @TrevorKarjanis!

2019-09-09 19:28 UTC, kapunahelewong commented
Caretaker, this is a docs only change. Thank you!

2019-09-10 11:58 UTC, closed without merging