docs: add individual http redirects
angular/angular pull request #32356
Opened 2019-08-27 20:26 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
People updating from earlier releases need to find the mapping from the deprecated/removed `@angular/http` package to the corresponding classes in the current `@angular/common/http` package.

There is a redirect from the old package URLs to this mapping in the deprecations page:
https://angular.io/guide/deprecations#angularhttp

Issue Number:  https://github.com/angular/angular/issues/24597

## What is the new behavior?
This would add individual redirects from each `@angular/http` page URL to the corresponding page in `@angular/common/http` .

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-08-28 18:28 UTC, vikerman approved these changes

2019-08-29 15:50 UTC, mary-poppins commented
You can preview 017f672 at https://pr32356-017f672.ngbuilds.io/.

2019-09-02 15:45 UTC, mary-poppins commented
You can preview a83f64e at https://pr32356-a83f64e.ngbuilds.io/.

2019-09-02 23:01 UTC, mary-poppins commented
You can preview b5fb1a8 at https://pr32356-b5fb1a8.ngbuilds.io/.

2019-09-03 23:45 UTC, mary-poppins commented
You can preview 6eb310c at https://pr32356-6eb310c.ngbuilds.io/.

2019-09-09 15:43 UTC, mary-poppins commented
You can preview 81d50ba at https://pr32356-81d50ba.ngbuilds.io/.

2019-09-09 15:45 UTC, mary-poppins commented
You can preview 3bb1718 at https://pr32356-3bb1718.ngbuilds.io/.

2019-09-09 17:46 UTC, gkalpak commented
For reference, this is an alternative of #29907.
(BTW, the comments I've left on #29907 are valid here as well (e.g. https://github.com/angular/angular/pull/29907/files#r275460399).)

2019-09-09 17:52 UTC, gkalpak requested changes
Before doing a full review or looking at the CI failures, we should discuss whether this is a desirable change in the first place.

Spoiler alert: [I don't think it is][1] :wink:

[1]: https://github.com/angular/angular/issues/24597#issuecomment-529592584

2019-09-09 17:52 UTC, gkalpak commented on aio/firebase.json
> +      {"type": 301, "source": "/**/api/http/BrowserXhr", "destination": "/api/common/http/BrowserXhr"},
This will not be public API (see https://github.com/angular/angular/pull/29907/files#r275441108).

2019-09-09 17:52 UTC, gkalpak commented on aio/firebase.json
> +      {"type": 301, "source": "/**/api/http/ReadyState", "destination": "/api/common/http/HttpClient"},
All these `source` URLs should start with `/api/http/` (instead of `/**/api/http/`).

2019-09-09 18:46 UTC, jbogarthyde commented
Docs mgmt decision: leave as is, with single redirect from all old http URLs to deprecations page.

2019-09-09 18:46 UTC, closed without merging