feat(forms): 🎸 adding typings to form components
angular/angular pull request #32450
Opened 2019-09-02 22:21 UTC by Waldbillig-Thomas

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
currently there is no way to have typechecking for form elements
Issue Number: N/A

## What is the new behavior?
- creating FormStatus enum (reusable)
- adding typing to AbstractControl (value, status, valueChanges, statusChanges)
- adding typing to FormControl (constructor, setValue, patchValue, reset)
- adding typing to FormGroup (constructor, registerControl, addControl, removeControl, setControl, contains, setValue, patchValue, reset, getRawValue)
- adding typing to FormArray (constructor, at, push, insert, setControl, setValue, patchValue, reset, getRawValue)

## PR Checklist

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-09-03 06:15 UTC, Airblader commented on packages/forms/src/model.ts
> +  public readonly value: T|null = null;
Isn't undefined also a valid value?

2019-09-03 06:16 UTC, Airblader commented
I understand that emoji in commit messages are somewhat modern, but Angular doesn't use those and since the commit messages are compiled into the changelog I would consider removing it.

2019-09-03 06:31 UTC, trotyl commented
Partially duplicate of https://github.com/angular/angular/pull/20040

2019-09-03 07:50 UTC, Waldbillig-Thomas commented
> I understand that emoji in commit messages are somewhat modern, but Angular doesn't use those and since the commit messages are compiled into the changelog I would consider removing it.

the emoji comes from a small app that helps with commit messages (https://github.com/commitizen)
the emoji is linked to the type of commit and i find it quite practical when searching for a commit to locate it more easily

but i can get rid of it

2019-09-03 07:53 UTC, Waldbillig-Thomas commented on packages/forms/src/model.ts
> +  public readonly value: T|null = null;
imho the value should match the type that was specified.
so, to reset it should use null and if the type is only composed of optional attributes you should pass an empty object.
or is there any special case where passing undefined might be important?

2019-09-03 07:57 UTC, Waldbillig-Thomas commented
> Partially duplicate of #20040

I hadn't seen that one...
b.t.w. does anyone have some recommendations/doc on how to setup and test your environment when working on the angular code base?

2019-09-03 07:58 UTC, Airblader commented on packages/forms/src/model.ts
> +  public readonly value: T|null = null;
Ultimately that doesn't matter, if you do not allow undefined here when it was allowed before, this is a breaking change.

2019-09-03 08:58 UTC, Waldbillig-Thomas commented on packages/forms/src/model.ts
> +  public readonly value: T|null = null;
well if you don't specify a type T defaults to any which allows undefined which should pass, no?
so the current untyped code should not be affected

2019-09-03 09:01 UTC, Airblader commented on packages/forms/src/model.ts
> +  public readonly value: T|null = null;
Ah, true, `any | null` will just collapse to `any` anyway.

2019-09-03 22:43 UTC, mhevery approved these changes

2019-09-03 22:43 UTC, mhevery commented on packages/forms/src/model.ts
> +export enum FormStatus {
```suggestion
export const enum FormStatus {
```

2019-09-04 18:38 UTC, mhevery commented
@Waldbillig-Thomas can you try to get this PR green?

2019-09-04 20:17 UTC, Waldbillig-Thomas commented
> @Waldbillig-Thomas can you try to get this PR green?

i started to look into it, but I probably won't have time to continue until this weekend

I say that there was an error when you created a formcontrol with null as value and no type, typescript infers that the type T is null and not any, which causes problems...

i will have a look if there is a way to prevent typescript from doing that or find some other solution

2019-11-05 21:38 UTC, no0x9d requested changes
As much as I want type checking for Angular forms but your pull request contains breaking changes.
When using typed forms Angular must support all valid use cases.
For some cases it's difficult to find the correct type. In my oppinion values should be of type `DeepPartial<T>`. This is not correct for FormControls but is needed for FormControls or else not all operations are possible.

2019-11-05 21:38 UTC, no0x9d commented on packages/forms/src/model.ts
> +      formState: T|null = null,
FormControl also accepts an object with the type `{value: T, disabled: boolean}`

2019-11-05 21:38 UTC, no0x9d commented on packages/forms/src/model.ts
> +  patchValue(value: T extends Object ? Partial<T> : T, options: {
Why can value be `Partial<T>`? For FormControl `setValue` and `patchValue` are the same and should have the same type. Here we can remove required properties of `T`. This should not be possible.

2019-11-05 21:38 UTC, no0x9d commented on packages/forms/src/model.ts
> +  patchValue(value: Partial<T>, options: {onlySelf?: boolean, emitEvent?: boolean} = {}):
`value` should be of type `DeepPartial<T>`. With only `Partial<T>` even the example for reactive forms in the official docs can not be typed correctly, because the method `updateProfile()` uses a deep partial on a FormGroup (see [docs](https://angular.io/guide/reactive-forms#reactive-forms)).

2019-11-05 21:38 UTC, no0x9d commented on packages/forms/src/model.ts
> +  patchValue(value: T[], options: {onlySelf?: boolean, emitEvent?: boolean} = {}): void {
This one is tricky. If the FormArray contains only FormControls the type of `T[]` is correct. But if the FormArray contains FormGroups the correct type is `Partial<T>`, for nested FormGroups `DeepPartial<T>`.
The type of `T[]` is not backwards compatible.

2019-11-05 21:38 UTC, no0x9d commented on packages/forms/src/model.ts
> +    public controls: AbstractControl<T[]>[],
I think the type should be `AbstractControl<T>[]`

2019-12-04 17:05 UTC, pauldraper commented
> When using typed forms Angular must support all valid use cases.

That is a *very, very* odd statement for a framework that chose TypeScript.

A typed language never, ever attempts to support all legal untyped operations.

`'5' - 3` is a legal JS/untyped operation, but illegal TS/typed operation. There are ways to workaround this by modifying code in a way that produces different output `+'5' - 3`, or by descending into untyped modes `<any>'5' - 3`.

Between #16828/#20040 (2 years), #31963 (4 months), and #32450 (2 months), it'd be great to see a solution for **Type**Script programming that deemed acceptable.

2019-12-04 17:23 UTC, Airblader commented
@no0x9d didn't say that the Forms API needs to support any shenanigan you can throw against it, but that it needs to support valid, existing use-cases, such as the different inputs these functions can take, dynamically adding and removing controls etc. And I definitely agree with that. Types are supposed to help us, not break APIs by not allowing us to pass valid input.

2019-12-10 18:24 UTC, pauldraper commented
> Types are supposed to help us, not break APIs by not allowing us to pass valid input.

And my point is that TypeScript "broke" JavaScript APIs, as do all types.

```js
[{name: 'one'}, {name: 'two'}].sort((a, b) => (b.name < a.name) - (a.name < b.name));
```

That is *perfectly* valid JavaScript.

It is not valid TypeScript.

If you want a type-checker to prove correct uses of types, it's not unreasonable to require different programming patterns than you might be without a type checker.

Better types are better. Hopefully it will not take Angular another 2 years to arrive at those for something as exotic as forms.

2019-12-27 21:19 UTC, gioragutt commented on packages/forms/src/model.ts
> +      formState: T|null = null,
Maybe extract to a type:

```typescript
type FormState<T> = T | { value: T, disabled: boolean };
```

This can be used in more places as well

2019-12-27 21:21 UTC, gioragutt commented on packages/forms/src/model.ts
> +  patchValue(value: T extends Object ? Partial<T> : T, options: {
Patch value should definitely be `Partial<T>` since it can pass only part of the properties of `T`.

2020-03-03 13:34 UTC, Mr1upMachine commented
@Waldbillig-Thomas do you have plans on updating this PR any further? If not, I can branch off this and begin to try and address the issues above

2020-03-15 19:33 UTC, Waldbillig-Thomas commented
Currently I do not really have the time. You can close it for now and
if/when I have more time again I will create a new pull request

Thomas

On Tue, 3 Mar 2020, 14:34 Sean Hale, <notifications@github.com> wrote:

> @Waldbillig-Thomas <https://github.com/Waldbillig-Thomas> do you have
> plans on updating this PR any further? If not, I can branch off this and
> begin to try and address the issues above
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/32450?email_source=notifications&email_token=AAEK2UOE5ESQCOKCWWR7DSTRFUBPFA5CNFSM4ITAQIDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENTP5TQ#issuecomment-593952462>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEK2ULV35VNOV4QUN6VKVTRFUBPFANCNFSM4ITAQIDA>
> .
>

2020-12-09 06:56 UTC, AndrewKushnir commented
Closing in favor of more recent #38906 and #38406. Thank you.

2020-12-09 06:56 UTC, closed without merging