docs: add undecorated classes migration faq
angular/angular pull request #32478
Opened 2019-09-04 18:17 UTC by kapunahelewong

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Add info in deprecations guide about migrating undecorated classes.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-09-04 18:51 UTC, mary-poppins commented
You can preview 768c52a at https://pr32478-768c52a.ngbuilds.io/.

2019-09-09 16:35 UTC, devversion commented on aio/content/guide/deprecations.md
> +To migrate, add the appropriate decorator, `@Component()` or `@Directive()`, to base classes that do not already have decorators.
Based on my understanding we just want to recommend adding a selector-less `@Directive()` here? `@Component` always requires a template and we just want to perform the migration by adding `@Directive()` to the undecorated base class that uses DI or Angular features (such as `@Input()` etc.)

2019-09-09 16:35 UTC, devversion commented on aio/content/guide/deprecations.md
> +use one in a template or add it to an `NgModule`, Angular will throw.
I'm not sure if we should add such a phrase. If the directive is abstract, it doesn't have a selector and cannot be used within a component template.

2019-09-09 16:35 UTC, devversion commented on aio/content/guide/deprecations.md
> +feature, such as `@Host()` or `@ViewChild()`, you need an
A more common case should be the use of `@Input()`, so maybe we should mention that as an example?

2019-09-09 16:35 UTC, devversion commented on aio/content/guide/deprecations.md
> +If you have a `@Directive()` or `@Component()` annotation with
I don't think we support component decorators without metadata. This is because `@Component` always requires a `template` to be specified. In the first migration case (undecorated base class). In that case the parent just needs a selector-less `@Directive()` decorator to be added.

In the second migration case (undecorated child class). In that case, the child should just copy/replicate the decorator from the parent (so the behavior remains the same). In any case, there will never be a `@Component` decorator with no metadata and we shouldn't mention it IMO.

2019-09-09 18:21 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +To migrate, add the appropriate decorator, `@Component()` or `@Directive()`, to base classes that do not already have decorators.
Ah, thank you for the correction. Fixed.

2019-09-09 18:22 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +feature, such as `@Host()` or `@ViewChild()`, you need an
Got it. Added. 😊

2019-09-09 18:25 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +If you have a `@Directive()` or `@Component()` annotation with
I see. Fixed. Thank you for the explanation. Learning as I go. 😅

2019-09-09 18:35 UTC, mary-poppins commented
You can preview e90a5d1 at https://pr32478-e90a5d1.ngbuilds.io/.

2019-09-09 18:58 UTC, devversion commented on aio/content/guide/deprecations.md
> +This migration adds an empty `@Directive()` decorator to base classes that are extended by directives.
The migration does two different things based on the two cases (undecorated base class and undecorated derived class)

1) In the undecorated base class case, it adds the `@Directive()` decorator (this is already covered here ✅)
2) In the undecorated derived class, it copies the _inherited_ directive or component metadata to the derived class (if possible; [see here](https://hackmd.io/sfb3Ju2MTmKHSUiX_dLWGg#Schematic-Design)). This is currently not covered in that section.

I think we should add the second bullet point here too right? The current section just talks about the first migration case but above it's mentioned that there are two inheritance patterns.

2019-09-09 18:58 UTC, devversion commented on aio/content/guide/deprecations.md
> +### When do I need an `@Directive()` or `@Component()` decorator without a selector?
Here is another case where we should remove the `@Component` I guess? (due to the same reasons as within the other comments)

2019-09-09 19:14 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +### When do I need an `@Directive()` or `@Component()` decorator without a selector?
Got it, done!

2019-09-09 19:22 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +This migration adds an empty `@Directive()` decorator to base classes that are extended by directives.
Perfect. Got it. Thanks!

2019-09-09 19:48 UTC, mary-poppins commented
You can preview f69016d at https://pr32478-f69016d.ngbuilds.io/.

2019-09-09 20:00 UTC, mary-poppins commented
You can preview a8f4ee0 at https://pr32478-a8f4ee0.ngbuilds.io/.

2019-09-09 22:26 UTC, kara requested changes

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +directive or component metadata to the derived class.
Can we add a diff for this one too?

```suggestion
It also copies any inherited directive or component metadata to the derived class.

Before:
@Component({
  selector: 'my-comp',
  template: '<div></div>'
})
class BaseComp {}

export class PlainDerivedComp extends BaseComp {}

After:
@Component({
  selector: 'my-comp',
  template: '<div></div>'
})
class BaseComp {}

@Component({
  selector: 'my-comp',
  template: '<div></div>'
})
export class PlainDerivedComp extends BaseComp {}
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +In some cases this works in View Engine, however, to migrate to Ivy, you must use decorators.
Think the info in this line is covered in the paragraph below. Omit?

```suggestion
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +To migrate, add `@Directive()` to base classes that do not already have decorators.
The schematic should already have done this for you. Maybe say:

```suggestion
In the future, add `@Directive()` to base classes that do not already have decorators and are extended by directives.
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +that the class is a `@Directive` or `@Component`.
```suggestion
that the class is a `@Directive` or `@Component`, so it doesn't generate the proper instructions for the component.
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +feature, such as `@Host()`, `@ViewChild()`, or `@Input()`, you need an
```suggestion
feature, such as `@HostBinding()`, `@ViewChild()`, or `@Input()`, you need an
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +child class that extends that base class. If you don't want
```suggestion
The decorator lets the compiler know to generate the correct instructions to create that 
class and any classes that extend it.
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +to create that class with the correct dependencies. This is
```suggestion
If you have a `@Directive()` annotation with
no metadata inside of it, that decorator tells Angular 
to generate a factory function for that class but not to 
use it to match directives.
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +important if the directives or components extend the base
```suggestion
important if any directives or components extend a base
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +use one in a template or add it to an `NgModule`, Angular will throw.
I think that's the point she's trying to make. Selectorless directives should not be added to templates or modules, and if you try to, Angular will throw. How can we clarify that sentence? Maybe

```suggestion
use one in a template or add it to an `NgModule`, Angular will throw an error.
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +If you actually want to use a `Directive()`
```suggestion
If you actually want to use a directive
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +the selector blank. If you do want it usable independently,
```suggestion
the selector blank. If you do want it to be usable independently,
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +(not declared in an NgModule), or a class that doesn't
```suggestion
(not declared in an `NgModule`), or a class that doesn't
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +If you want to support Angular Version 8 and earlier, you
```suggestion
If you want to support Angular version 8 and earlier, you
```

2019-09-09 22:26 UTC, kara commented on aio/content/guide/deprecations.md
> +add an explicit constructor to the subclass
```suggestion
add an explicit constructor to affected subclasses.
```

2019-09-09 22:34 UTC, kara commented on aio/content/guide/deprecations.md
> +#### I'm a library author. Should I add the `@Directive()` decorator to base classes?
Header formatting is off by one, I think

```suggestion
### I'm a library author. Should I add the `@Directive()` decorator to base classes in my lib?
```

2019-09-09 22:34 UTC, kara commented on aio/content/guide/deprecations.md
> +Such a base class serves as a blueprint for child classes.
```suggestion

```

2019-09-09 23:46 UTC, kara commented on aio/content/guide/deprecations.md
> +## Undecorated classes migration
```suggestion
## Undecorated classes migration (DI)
```

2019-09-09 23:46 UTC, kara commented on aio/content/guide/deprecations.md
> +This section discusses migration of two inheritance patterns which need special attention in Ivy.
Can we say something about how this is a version 8 to version 9 migration?
```suggestion
This section discusses a version 9 schematic that migrates two inheritance patterns which need special attention in Ivy.
```

2019-09-10 16:32 UTC, devversion commented on aio/content/guide/deprecations.md
> +## Undecorated classes migration
@kara Yeah, it makes sense to denote this as the `DI` migration. One concern I have is that we have a section below where we talk about `@Input`, `@HostBinding` etc. Those things are not part of the DI migration though? (so this might be confusing)

2019-09-10 16:48 UTC, devversion commented
@kara @kapunahelewong I just want to add that this migration also handles the DI case for undecorated base classes of `@Injectable`'s.

Also it copies the metadata for undecorated derived classes where the inherited metadata is from a `@Pipe()`. These are just two things which aren't covered by the document yet. I'm not sure where/whether we should add those.

2019-09-10 16:50 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +## Undecorated classes migration
Done.

2019-09-10 16:51 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +This section discusses migration of two inheritance patterns which need special attention in Ivy.
Done.

2019-09-10 16:52 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +Such a base class serves as a blueprint for child classes.
Done.

2019-09-10 16:52 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +#### I'm a library author. Should I add the `@Directive()` decorator to base classes?
Fixed.

2019-09-10 16:53 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +add an explicit constructor to the subclass
Fixed.

2019-09-10 16:54 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +For the undecorated base class,
Done.

2019-09-10 16:55 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +this migration adds an empty `@Directive()` decorator to base classes
Done.

2019-09-10 16:56 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +In some cases this works in View Engine, however, to migrate to Ivy, you must use decorators.
Done.

2019-09-10 16:56 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +To migrate, add `@Directive()` to base classes that do not already have decorators.
Done.

2019-09-10 16:57 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +If you actually want to use a `Directive()`
Done.

2019-09-10 16:57 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +the selector blank. If you do want it usable independently,
Done.

2019-09-10 16:58 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +(not declared in an NgModule), or a class that doesn't
Done.

2019-09-10 16:58 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +If you want to support Angular Version 8 and earlier, you
Done.

2019-09-10 17:00 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +that the class is a `@Directive` or `@Component`.
Done.

2019-09-10 17:00 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +feature, such as `@Host()`, `@ViewChild()`, or `@Input()`, you need an
Done.

2019-09-10 17:07 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +child class that extends that base class. If you don't want
Updated, but would like to confirm having edited as you intend:

> The decorator lets the compiler know to generate the correct
> instructions to create that class and any classes that extend it.
> To use that base class as a directive directly, leave
> the selector blank. If you do want it to be usable independently,
> fill in the metadata as usual.

2019-09-10 17:20 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +to create that class with the correct dependencies. This is
Done.

2019-09-10 17:20 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +important if the directives or components extend the base
Done.

2019-09-10 17:34 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +directive or component metadata to the derived class.
ooooh thanks for the diff! Added. 🚀

2019-09-10 17:40 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +use one in a template or add it to an `NgModule`, Angular will throw.
Added "an error". Thanks for the clarification. Leaving open so @kara can respond to @devversion.

2019-09-10 17:48 UTC, mary-poppins commented
You can preview 7788b31 at https://pr32478-7788b31.ngbuilds.io/.

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +For the undecorated derived class, it also copies the inherited
```suggestion
It also copies any inherited directive or component metadata to the derived class.
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +```
```suggestion
```ts
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +```
```suggestion
```ts
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +export class PlainDerivedComp extends BaseComp {}
Add a line between the two comps?

```suggestion

export class PlainDerivedComp extends BaseComp {}
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +class BaseComp {}
Same here. Add a line?

```suggestion

class BaseComp {}
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +### Why is this new decorator necessary?
```suggestion
### Why is this migration necessary?
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +it doesn't generate the proper instructions for the component.
Let's say directive since it's a directive in the example.

```suggestion
it doesn't generate the proper instructions for the directive.
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +@Directive({selector: '[sale-item]'})
```suggestion
@Directive({selector: '[baseDir]'})
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +@Directive({selector: '[sale-item]'})
This selector seems a bit random. How about:

```suggestion
@Directive({selector: '[derivedDir]'})
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +should not be used in templates directly. If you try to
```suggestion
cannot be used in templates directly. If you try to
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +use one in a template or add it to an `NgModule`, Angular
```suggestion
add it to an `NgModule`, Angular
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +feature, such as `@HostBinding()`, `@ViewChild()`, or `@Input()`, you need an
```suggestion
feature, such as `@HostBinding()`, `@ViewChild()`, or `@Input()`, you need a
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +To use that base class as a directive directly, leave
Looks like the logic got inverted here? :)

```suggestion
If you don't want to use that base class as a directive directly, leave
```

2019-09-10 19:22 UTC, kara commented on aio/content/guide/deprecations.md
> +use any Angular features, you don't need a decorator.
Maybe we could simplify this to

```
Classes that don't use Angular features don't need an Angular decorator.
```

2019-09-10 19:23 UTC, kara commented on aio/content/guide/deprecations.md
> +## Undecorated classes migration
Yeah, it's from a different migration, but we should answer the question completely for version 9. Omitting it wouldn't be accurate. Maybe we can link in that question to the other guide when it's ready.

2019-09-10 19:23 UTC, kara commented
@devversion Yeah, I was thinking about the @Injectable part. I just don't want the doc to be overwhelming with too many diffs. What do you think?

2019-09-10 19:40 UTC, devversion commented on aio/content/guide/deprecations.md
> +## Undecorated classes migration
Yeah, the answer to the question is accurate, but not necessarily related to that particular migration. IMO the ideal solution would be to have one document for both undecorated classes migrations. Two documents can be confusing.

Up to you though. this is just an idea.

2019-09-10 19:40 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +base classes that are extended by _either_ directives or components.
You're right. Removed.

2019-09-10 19:41 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +For the undecorated derived class, it also copies the inherited
I see. Got it. Thanks!

2019-09-10 19:42 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +```
Good catch. Fixed.

2019-09-10 19:42 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +```
Fixed!

2019-09-10 19:44 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +export class PlainDerivedComp extends BaseComp {}
Added.

2019-09-10 19:45 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +should not be used in templates directly. If you try to
Fixed.

2019-09-10 19:46 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +use one in a template or add it to an `NgModule`, Angular
Fixed.

2019-09-10 19:46 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +feature, such as `@HostBinding()`, `@ViewChild()`, or `@Input()`, you need an
Got it. Fixed.

2019-09-10 19:48 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +To use that base class as a directive directly, leave
Done!

2019-09-10 19:49 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +use any Angular features, you don't need a decorator.
Oh nice. Done!

2019-09-10 19:50 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +class BaseComp {}
Done!

2019-09-10 19:51 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +it doesn't generate the proper instructions for the component.
Fixed.

2019-09-10 19:51 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +@Directive({selector: '[sale-item]'})
Fixed.

2019-09-10 19:52 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +@Directive({selector: '[sale-item]'})
Done.

2019-09-10 19:53 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +### Why is this new decorator necessary?
Done.

2019-09-10 20:02 UTC, mary-poppins commented
You can preview 6b96f20 at https://pr32478-6b96f20.ngbuilds.io/.

2019-09-10 20:06 UTC, kara commented on aio/content/guide/deprecations.md
> +## Undecorated classes migration
Yeah, thought about that too 🤔 The only thing is that the doc would be longer... let me see what the other guide ends up looking like. Maybe we'll end up combining them if there's too much shared.

2019-09-10 20:18 UTC, kara commented on aio/content/guide/deprecations.md
> +  @Directive({selector: '[sale-item]'})
Update these ones too?

```suggestion
  @Directive({selector: '[derivedDir]'})
```

2019-09-10 20:19 UTC, kara commented on aio/content/guide/deprecations.md
> +
Can we also add a "Version 9 Schematics" section right above the Renderer guide so it's clear what the context is for these migration sections?

2019-09-10 20:20 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +  @Directive({selector: '[sale-item]'})
Oh! Thank you. Got it.

2019-09-10 20:35 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +
Added!

2019-09-10 20:40 UTC, mary-poppins commented
You can preview e68a9b5 at https://pr32478-e68a9b5.ngbuilds.io/.

2019-09-10 20:47 UTC, kara approved these changes
LGTM

2019-09-10 20:48 UTC, kara commented
merge-assistance: global approval

2019-09-10 20:53 UTC, mary-poppins commented
You can preview 818e25e at https://pr32478-818e25e.ngbuilds.io/.

2019-09-10 21:21 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +In this case, the subclass is inheriting its constructor from the base class
"is inheriting" -> "inherits"

2019-09-10 21:21 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +```
This example seems duplicative with the above "before/after" example.

(similar for the next example below)

2019-09-10 21:21 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +#### What does it mean to have a `@Directive()` annotation with no metadata inside of it?
Should consistently use "decorator" and not "annotation"

2019-09-10 21:21 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +will throw an error.
Proposed edit:
```markdown
The presence of the `@Directive` decorator causes Angular to generate
extra code for the affected class. If that decorator includes no properties (metadata),
the generated code won't run directly, but other classes that _extend_ the
directive class will inherit this generated code. You can think of this as an "abstract"
directive. 

Adding an abstract directive to an `NgModule` will cause an error. A directive must
have a `selector` property defined in order to match some element in a template.
```
I think the "factory function" bits are a bit more than most people need to know, so we can just talk about the general idea of generated code.

2019-09-10 21:47 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +two inheritance patterns which need special attention in Ivy.
Fixed.

2019-09-10 21:53 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +If a class has a `@Directive()` or `@Component()` decorator, the compiler
Got it. Thanks for the clear explanation. Changed.

2019-09-10 21:54 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +It also copies any inherited directive or component metadata to the derived class.
Fixed.

2019-09-10 21:55 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +There are two scenarios where the new decorator is necessary for migration; each involving an undecorated parent or child class.
Nice! Added.

2019-09-10 21:56 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +In this case, the subclass is inheriting its constructor from the base class
Done.

2019-09-10 21:57 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +#### What does it mean to have a `@Directive()` annotation with no metadata inside of it?
Fixed.

2019-09-10 22:01 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +  export class PlainBase {
Got it. Changed.

2019-09-10 22:22 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +```
De-duplicatized it. Also, took out the redundant stuff. (I crack me up!) 

Seriously, thank you for catching those. Nice improvement. 🙏🏼

2019-09-10 22:25 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +will throw an error.
Got it. Thanks!

2019-09-10 22:33 UTC, mary-poppins commented
You can preview 458432f at https://pr32478-458432f.ngbuilds.io/.

2019-09-10 22:35 UTC, kara requested changes

2019-09-10 22:35 UTC, kara commented on aio/content/guide/deprecations.md
> +  @Directive({selector: '[derivedDir]'})
If we change the names, can we update all the selectors to match?

2019-09-10 22:35 UTC, kara commented on aio/content/guide/deprecations.md
> +the generated code won't run directly, but other classes that _extend_ the
I found this part about generated code running to be confusing.  Maybe:

```suggestion
the directive won't be matched to elements or instantiated directly, but other classes that _extend_ the
directive class will be able to use the extra code that was generated for the base class.
```

2019-09-10 22:44 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +  @Directive({selector: '[derivedDir]'})
So embarrassing! 🙈😅Fixed.

2019-09-10 22:45 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +the generated code won't run directly, but other classes that _extend_ the
Fixed!

2019-09-10 22:49 UTC, kara approved these changes
LGTM, one more typo

2019-09-10 22:49 UTC, kara commented on aio/content/guide/deprecations.md
> +#### When do I need an `@Directive()` decorator without a selector?
```suggestion
#### When do I need a `@Directive()` decorator without a selector?
```

2019-09-10 22:53 UTC, mary-poppins commented
You can preview 69b4282 at https://pr32478-69b4282.ngbuilds.io/.

2019-09-10 22:54 UTC, mary-poppins commented
You can preview a48dee9 at https://pr32478-a48dee9.ngbuilds.io/.

2019-09-10 22:57 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +#### When do I need an `@Directive()` decorator without a selector?
Fixed! I was reading it wrong. Thanks for correcting me, @kara!

2019-09-10 23:04 UTC, mary-poppins commented
You can preview 9d831a5 at https://pr32478-9d831a5.ngbuilds.io/.

2019-09-10 23:31 UTC, jelbourn reviewed
Looks good, just a few more comments now that I read through the new flow

2019-09-10 23:31 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +  @Directive({selector: '[settingsDir]'})
"settingsDir` -> `settingsMenu`

(here and below)

2019-09-10 23:31 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +class BaseComp {}
Same name changes for this example?

2019-09-10 23:31 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +principle of locality, so it can only use data from that
optional: "principle of locality" isn't a broadly known term/concept. I might rephrase like (starting at "However")
```markdown
However, the Ivy compiler only processes each directive in isolation. This means that
compilation can be faster, but the compiler can't automatically infer the same
information as before. Adding the `@Directive` explicitly provides this information.
```

2019-09-10 23:31 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +to create it.
Suggested edit for this paragraph:
```markdown
When using inheritance, a child directive references the `constructor` of its parent class.
If that parent class doesn't have a decorator, however, its constructor lacks extra
generated code from the Angular compiler to make dependency injection work.
```

2019-09-11 21:00 UTC, mary-poppins commented
You can preview 4838673 at https://pr32478-4838673.ngbuilds.io/.

2019-09-11 22:49 UTC, kara commented on aio/content/guide/migration-undecorated-classes.md
> +shouldn't add a selectorless `@Directive()` decorator.
because support for selectorless decorators is only introduced in version 9.

2019-09-12 18:35 UTC, jelbourn approved these changes
LGTM, one tiny nit

2019-09-12 18:54 UTC, kara approved these changes
LGTM

2019-09-12 19:16 UTC, closed without merging