fix(ivy): i18n - start generated placeholder name at `ph`
angular/angular pull request #32493
Opened 2019-09-05 13:18 UTC by cexbrayat

On top of #32488 

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently the expressions used in a template string are automatically named `ph_1`, `ph_2`, etc. Whereas interpolations used in i18n templates generates placeholders automatically named `interpolation`, `interpolation_1`, etc.

## What is the new behavior?

This commit aligns the behaviors by starting the generated placeholder names for expressions at `ph`, then `ph_1`, etc.

It also documents this behavior in the documentation of `$localize` as it was not mentioned before.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This was discussed with @petebacondarwin

2019-09-06 08:43 UTC, petebacondarwin approved these changes

2019-09-09 08:05 UTC, petebacondarwin requested changes
Due to https://github.com/angular/angular/pull/32509 could you also rename the placeholders to be uppercase? I.E. `PH_...` rather than `ph_...`.

2019-09-09 08:41 UTC, cexbrayat commented
@petebacondarwin Sure, will do 👍

2019-09-17 21:11 UTC, petebacondarwin approved these changes

2019-09-17 21:16 UTC, AndrewKushnir commented
- [VE Presubmit](https://test.corp.google.com/ui#id=OCL:269652265:BASE:269652283:1568754917003:b676d577)
- [Ivy Presubmit](http://test/OCL:269652265:BASE:269652402:1568754952163:90743649)

2019-09-17 22:13 UTC, closed without merging