perf(ivy): introduce a node-based micro-benchmarks harness
angular/angular pull request #32510
Opened 2019-09-06 14:29 UTC by pkozlowski-opensource

2019-09-06 16:09 UTC, mhevery requested changes

2019-09-06 16:09 UTC, mhevery commented on packages/core/test/render3/perf/micro_bench.ts
> +      scenarioFn();
I think this is problematic because it requires that the function is inlined here for performance. This will work great for the first test case, but will cause deopt for the second use case, making it look like that the second case is slower. See solution [here](http://www.typescriptlang.org/play/#code/MYewdgzgLgBAygSQFoFEYF4YEYAMBuAKANElgEMAnCsgTwHEKQB3KACwxmAoFMypuAQtzDBWAW0oBrABQByStRowA5oxatZAGmw5du7QFYcASkIEANt1gBLMABNuADwAq1sdw4LaDZmzkBtWwdHAF1ZUwImVmtLGGkgp1d3ADoKAFcwaWNjGABvAhgYKJjuePtEt1LsvILCmEtyKloOfxDCOpgAMxAKaQaYSXR8AZgAHnhkFDwBgGoZnPyOjq8af0kQjnxawoBfWr2ds36ABzSIViSPTBWfdTlT8-DCYstpB4vK1IyshdqX0velx+NQ6-RWLTa2y6PT6VgGQ2mkjGE1QiLmvyWdRWyXe0hM7Tqe12BEORBuajYqW4xx6UGkZEsFCgESIAHp2RzOVzuRyYAIUAA5ADCAAkALIAQQASgBpGBCgDyABE0Dy1eqiLZ+BROmRgB4hCJxFIQXEAG7cCgQazgAVkdwALhg0AotmUxidAAVGJ0SgSeDSmdJOmAAPxO6QB2lOl1unLoAB8MDNIGsdg9ydTdkIey1lt1+pg3pAvtiiziGYARiAQJYyGACccfSU7Y7nVBXWBlP7vlWa3WG7VK9xoJcnWA0mJhxQc0ROhlgFAbWBODw+IJhKIJBQZMOjdvJK3uDGO27tNZtXxl0KQBkoOPJ9PtOlIA6J1PLRwjBnDVuTaaSGgGAmxLEoIC9ZtLFaCEzEKQDYD3P8dw4ecRCXcA+U3Y0dzeSDuCPE9O3dCDQLLKF+gvS0r3AG870tB8PwoDhKOodCwFosAoAJODwCAkDS2PIs8JQhc2KE0iqlNDprE6OIWOo9jb04z90FUmATCkpZ5LYjjtWYy8dKUrioQ6HgoDSCgV11cwIG4bjCRgbgbI8ctMW068jMtABaLz7NMqwLJXDs0jskyYCJByyAgcSBPs-pzCiqBLmge1jk2OK4RfXSOBfCB7P4kovhXTBUMXZcsk0njSBgMBmA4Y58x6CQRG4ZJaqYLI-JgGS4gS0dKhSsQ0oAQjUjTXKWeCYCXdwOHamAvPqRLkqgVKusKArLGSYd+tmzAxT4VhkjEWxcIk7aRySyptBm7gIkxCLQWWgbVqGubmC6nrIwybLVMwcawsKLKjJyjI8sBmAzMCroGVsrqdkc5zKrqYG7x89bIYCyzpvSUKHqhR7gLwnE8KPerSftPG6k21qdquvaYAFR9LWSSUAA0AH04AlAAxFAOYQAVnBQOgUClfK8IgHEzlYM6BPulGsZXGmCQRqLMP3KRYJgRDsMkKlA1gErRPKkNwziKMmUIuMMCTFM0wxOpbPp7hbzpCrE2RqbdWgS7yYkqWeDsNJ9WkXDuDNG0zhIgTtGACyeE4mOSnjJMJv88zsfDyPbylunLmReOqGEKALt2u6YFDImI6j6KnSLxPjIehWOmDFcAB9284Xja1a8wQHdaQAANfz1p0ABJcl1g8jx2AAdMBJ5pqWJGOMOaeTyxU+RqqgNujg5cK-PKhgVluoMjy7xgAAqHRdGMZIoBAHnrEcbg7GkABmFvJt42AGooPqTiB9cA4AWkTc6x9Zpnx9vwaAZcXY3zvg-J+L834f3xBDKG2Mh6FCXsTGms8J65FugjM4cQl6WiAVAHYABSYwQ94YPwAFapkyLIBe4QdhDx-jsBWEVsErmnlrEkBAgA)

2019-09-09 12:57 UTC, pkozlowski-opensource commented on packages/core/test/render3/perf/micro_bench.ts
> +      scenarioFn();
@mhevery changed the PR to use your micro-harness from dgzgLgBAygSQFoFEYF4YEYAMBuAKANElgEMAnCsgTwHEKQB3KACwxmAoFMypuAQtzDBWAW0oBrABQByStRowA5oxatZAGmw5du7QFYcASkIEANt1gBLMABNuADwAq1sdw4LaDZmzkBtWwdHAF1ZUwImVmtLGGkgp1d3ADoKAFcwaWNjGABvAhgYKJjuePtEt1LsvILCmEtyKloOfxDCOpgAMxAKaQaYSXR8AZgAHnhkFDwBgGoZnPyOjq8af0kQjnxawoBfWr2ds36ABzSIViSPTBWfdTlT8-DCYstpB4vK1IyshdqX0velx+NQ6-RWLTa2y6PT6VgGQ2mkjGE1QiLmvyWdRWyXe0hM7Tqe12BEORBuajYqW4xx6UGkZEsFCgESIAHp2RzOVzuRyYAIUAA5ADCAAkALIAQQASgBpGBCgDyABE0Dy1eqiLZ+BROmRgB4hCJxFIQXEAG7cCgQazgAVkdwALhg0AotmUxidAAVGJ0SgSeDSmdJOmAAPxO6QB2lOl1unLoAB8MDNIGsdg9ydTdkIey1lt1+pg3pAvtiiziGYARiAQJYyGACccfSU7Y7nVBXWBlP7vlWa3WG7VK9xoJcnWA0mJhxQc0ROhlgFAbWBODw+IJhKIJBQZMOjdvJK3uDGO27tNZtXxl0KQBkoOPJ9PtOlIA6J1PLRwjBnDVuTaaSGgGAmxLEoIC9ZtLFaCEzEKQDYD3P8dw4ecRCXcA+U3Y0dzeSDuCPE9O3dCDQLLKF+gvS0r3AG870tB8PwoDhKOodCwFosAoAJODwCAkDS2PIs8JQhc2KE0iqlNDprE6OIWOo9jb04z90FUmATCkpZ5LYjjtWYy8dKUrioQ6HgoDSCgV11cwIG4bjCRgbgbI8ctMW068jMtABaLz7NMqwLJXDs0jskyYCJByyAgcSBPs-pzCiqBLmge1jk2OK4RfXSOBfCB7P4kovhXTBUMXZcsk0njSBgMBmA4Y58x6CQRG4ZJaqYLI-JgGS4gS0dKhSsQ0oAQjUjTXKWeCYCXdwOHamAvPqRLkqgVKusKArLGSYd+tmzAxT4VhkjEWxcIk7aRySyptBm7gIkxCLQWWgbVqGubmC6nrIwybLVMwcawsKLKjJyjI8sBmAzMCroGVsrqdkc5zKrqYG7x89bIYCyzpvSUKHqhR7gLwnE8KPerSftPG6k21qdquvaYAFR9LWSSUAA0AH04AlAAxFAOYQAVnBQOgUClfK8IgHEzlYM6BPulGsZXGmCQRqLMP3KRYJgRDsMkKlA1gErRPKkNwziKMmUIuMMCTFM0wxOpbPp7hbzpCrE2RqbdWgS7yYkqWeDsNJ9WkXDuDNG0zhIgTtGACyeE4mOSnjJMJv88zsfDyPbylunLmReOqGEKALt2u6YFDImI6j6KnSLxPjIehWOmDFcAB9284Xja1a8wQHdaQAANfz1p0ABJcl1g8jx2AAdMBJ5pqWJGOMOaeTyxU+RqqgNujg5cK-PKhgVluoMjy7xgAAqHRdGMZIoBAHnrEcbg7GkABmFvJt42AGooPqTiB9cA4AWkTc6x9Zpnx9vwaAZcXY3zvg-J+L834f3xBDKG2Mh6FCXsTGms8J65FugjM4cQl6WiAVAHYABSYwQ94YPwAFapkyLIBe4QdhDx-jsBWEVsErmnlrEkBAgA

2019-09-09 16:39 UTC, mhevery approved these changes

2019-09-09 19:56 UTC, closed without merging