fix(language-service): create StaticReflector once only
angular/angular pull request #32543
Opened 2019-09-08 08:13 UTC by kyliau

The creation of StaticReflector in createMetadataResolver() is a very expensive operation because it involves numerous module resolutions (on the order of hundreds).
To make matter worse, since the API of the Reflector does not provide the ability to invalidate its internal caches, it has to be destroyed and recreated on *every* program change.
This has a HUGE impact on performance.
This PR fixes this problem by carefully invalidating all StaticSymbols in a file that has changed, thereby reducing the overhead of recomputation on program change.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-09-09 18:09 UTC, kyliau commented
Need to rebase after #32098 is merged

2019-10-03 17:44 UTC, mhevery approved these changes

2019-10-03 18:26 UTC, petebacondarwin approved these changes
LGTM once it has been rebased.

2019-10-03 20:57 UTC, ayazhafiz requested changes

2019-10-03 20:57 UTC, ayazhafiz commented on packages/compiler/src/aot/static_symbol_resolver.ts
> +    this.symbolFromFile.delete(fileName);
If this is a `StaticSymbol[]` that is empty, this branch will still be hit right? Maybe we should do a check for undefined so that the file is still deleted from `symbolFromFile` if not undefined.

2019-10-03 20:57 UTC, ayazhafiz commented on packages/language-service/src/typescript_host.ts
> +      // Should not invalidate file on the first encounter
nit: otherwise the comment makes it seem like all of `lastVersion !== undefined && version !== lastVersion` is needed to see if the file is encountered for the first time

```suggestion
      // Should not invalidate file on the first encounter or if file hasn't changed
```

2019-10-03 21:04 UTC, kyliau commented on packages/compiler/src/aot/static_symbol_resolver.ts
> +    this.symbolFromFile.delete(fileName);
Sorry, I didn't quite get that.. The case of undefined is handled on line 186. If it's an empty array, it should still be deleted from the map, which is handled here.

2019-10-03 21:35 UTC, ayazhafiz approved these changes

2019-10-03 21:35 UTC, ayazhafiz commented on packages/compiler/src/aot/static_symbol_resolver.ts
> +    this.symbolFromFile.delete(fileName);
my bad; I thought `![] === true`

2019-10-03 21:38 UTC, kara commented
merge-assistance: misko has global approval

2019-10-03 22:02 UTC, closed without merging