perf(language-service): keep analyzedModules cache when source files don't change
angular/angular pull request #32562
Opened 2019-09-09 18:15 UTC by andrius-pra

This change will improve performance of language service when working in external templates.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-09-09 20:41 UTC, ayazhafiz requested changes

2019-09-09 20:41 UTC, ayazhafiz commented on packages/language-service/src/typescript_host.ts
> +    return upToDate;
Prefer

```suggestion
    return missing.length === 0;
```

Eliminating the need for `upToDate` variable

2019-09-09 21:11 UTC, andrius-pra commented on packages/language-service/src/typescript_host.ts
> +    return upToDate;
I still need to have `hasInvalidatedFiles` or `upToDate` variable because of I need to track version changes in line 285.

2019-09-09 21:25 UTC, ayazhafiz requested changes

2019-09-09 21:25 UTC, ayazhafiz commented on packages/language-service/src/typescript_host.ts
> +    return upToDate;
How about

```typescript
const upToDate = missing.length === 0 && version === lastVersion;
return upToDate;
```

this way it's clear both conditions we are checking.

2019-09-10 17:58 UTC, ayazhafiz approved these changes

2019-09-10 17:58 UTC, ayazhafiz commented
LGTM!

2019-09-10 21:37 UTC, kyliau approved these changes

2019-09-10 21:37 UTC, kyliau commented on packages/language-service/test/typescript_host_spec.ts
> +    tsLSHost.override('/src/test.ng', '<div></div>');
the file should be `/app/test.ng`

2019-09-10 21:37 UTC, kyliau commented on packages/language-service/src/typescript_host.ts
> +    return missing.length == 0 && !hasChanges;
prefer strict equality operator `===`

2019-09-11 23:13 UTC, closed without merging