ci: update codeowners to reflect GitHub team members
angular/angular pull request #32569
Opened 2019-09-10 07:37 UTC by gkalpak

☝️

2019-09-10 20:19 UTC, josephperrott commented on .github/CODEOWNERS
>  #  AndrewKushnir - Andrew Kushnir
We should also add `atscott - Andrew Scott`

2019-09-10 20:45 UTC, josephperrott requested changes

2019-09-10 20:45 UTC, josephperrott commented on .github/CODEOWNERS
>  #   - alexeagle
`alexeagle` should be removed from:
`@angular/framework-global-approvers`
`@angular/tools-cli`
`@angular/fw-integration`
`@angular/fw-docs-packaging`
`@angular/tools-docs-libraries`
`@angular/tools-docs-schematics`

2019-09-10 21:12 UTC, gkalpak commented on .github/CODEOWNERS
>  #   - alexeagle
Removed (and updated those teams in `CODEOWNERS` to match the actual GitHub teams).

2019-09-11 09:53 UTC, gkalpak commented
The CI failures are unrelated to this PR (and will be fixed by #32602).

2019-09-11 15:03 UTC, josephperrott approved these changes
LGTM

Thanks! I know this was tedious work to have to manage the Github UI to get all of this info lined up.

2019-09-11 16:50 UTC, gkalpak commented
(Rebased on master to make CI happy.)

2019-09-11 17:50 UTC, kara requested changes

2019-09-11 17:50 UTC, kara commented on .github/CODEOWNERS
>  #   - petebacondarwin
Let's replace brandonroberts with `kapunahelewong`

2019-09-11 18:22 UTC, gkalpak commented on .github/CODEOWNERS
>  #   - petebacondarwin
Done.

2019-09-11 18:37 UTC, kara approved these changes
LGTM

2019-09-11 18:38 UTC, kara commented
merge-assistance: global approval (note: Igor approved these changes over IM)

2019-09-12 00:26 UTC, closed without merging