docs: add dynamic queries flag migration documentation
angular/angular pull request #32582
Opened 2019-09-10 15:06 UTC by kapunahelewong

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Adds documentation to deprecations guide about dynamic queries flag migration.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-09-10 15:17 UTC, mary-poppins commented
You can preview 401b900 at https://pr32582-401b900.ngbuilds.io/.

2019-09-11 17:22 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +Angular version 8 added `static` flags to all `@ViewChild` and `@ContentChild` queries.
I would combine these two one-line paragraphs into a single paragraph:
```markdown
Angular version 8 added `static` flags to all `@ViewChild` and `@ContentChild` queries.
This was the first step towards changing the default behavior. With version 9, the default value
changes to `static: false` and the flag becomes optional.
```

2019-09-11 17:22 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +Going forward, Angular will use dynamic queries by default, which simplifies the development process. Though the static feature will remain in Angular, the version 9 migration will remove the `static
Proposed edit:
```markdown
Before version 9, Angular figured out the static or dynamic nature of a query automatically based
on how the template was written. Looking at templates like this, however, incurred performance
costs. As of version 9, Angular uses dynamic queries (`static: false`) by _default_, simplifying
queries. Developers can still _explicitly_ set a query to `static: true`. This changes allows
for faster compilation.
```

2019-09-11 17:22 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +### Why is this migration necessary?
I would reference an explanation of what dynamic vs. static means at the beginning of this section.

2019-09-11 17:22 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +// this decorator doesn't change because the static value is true
I would say "this query" instead of "this decorator"

("decorator" isn't _wrong_, but it's specifically the _argument_ to the decorator that might change, not the decorator itself; using "query" skirts that technicality)

2019-09-11 19:50 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +Angular version 8 added `static` flags to all `@ViewChild` and `@ContentChild` queries.
Done!

2019-09-11 19:52 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +Going forward, Angular will use dynamic queries by default, which simplifies the development process. Though the static feature will remain in Angular, the version 9 migration will remove the `static
Added.

2019-09-11 19:55 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +// this decorator doesn't change because the static value is true
Ah I see. Thanks! (Done.)

2019-09-11 21:23 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +### Why is this migration necessary?
Done. Got great guidance from @jelbourn in off line conversation. Thanks!!

2019-09-11 21:27 UTC, mary-poppins commented
You can preview 6f13451 at https://pr32582-6f13451.ngbuilds.io/.

2019-09-11 23:45 UTC, jelbourn commented on aio/content/guide/migration-dynamic-flag.md
> +query to `static: true`. This changes allows
typo: "This changes" -> "This change"

2019-09-11 23:45 UTC, jelbourn commented on aio/content/guide/migration-dynamic-flag.md
> +The shematic scans classes in the compilation and for each class, checks if the members have a `@ViewChild()` or `@ContentChild()` query with the `static` flag set to `false`. If so, the flag is remo
typo: "shematic" -> "schematic"

2019-09-11 23:45 UTC, jelbourn commented on aio/content/guide/migration-dynamic-flag.md
> +```javascript
The language for these examples should be TypeScript (which you can write `ts`)

2019-09-12 16:39 UTC, jelbourn approved these changes
LGTM

2019-09-12 20:55 UTC, kara requested changes
gist: I think we should use more of the existing guide's explanations

2019-09-13 17:27 UTC, mary-poppins commented
You can preview 0d39590 at https://pr32582-0d39590.ngbuilds.io/.

2019-09-13 18:38 UTC, mary-poppins commented
You can preview 36ae2dd at https://pr32582-36ae2dd.ngbuilds.io/.

2019-09-18 18:21 UTC, mary-poppins commented
You can preview 5d558b3 at https://pr32582-5d558b3.ngbuilds.io/.

2019-10-01 17:31 UTC, kara requested changes
This looks really close. Some final nits:

2019-10-01 17:31 UTC, kara commented on aio/content/guide/migration-dynamic-flag.md
> +the query resolves and when Angular updates the result.
Nit: I think those two things are the same. How about:

```suggestion
the query results become available.
```

2019-10-01 17:31 UTC, kara commented on aio/content/guide/migration-dynamic-flag.md
> +immediately after the constructor.
More accurate to say: 

```suggestion
once the view has been created, but before change detection runs.
```

2019-10-01 17:31 UTC, kara commented on aio/content/guide/migration-dynamic-flag.md
> +changes to `static: false` and the flag becomes optional.
Can we move this first paragraph into the top of "What does this migration do?" It's really the background we need for that.

2019-10-01 17:31 UTC, kara commented on aio/content/guide/migration-dynamic-flag.md
> +The schematic scans classes in the compilation and for each
```suggestion
This schematic scans classes in the compilation and for each
```

2019-10-01 17:31 UTC, kara commented on aio/content/guide/migration-dynamic-flag.md
> +`false`. If so, the schematic removes the flag.
```suggestion
`false`. If so, the schematic removes the flag, as it now matches the default.
```

2019-10-01 17:31 UTC, kara commented on aio/content/guide/migration-dynamic-flag.md
> +query to `static: true`.
```suggestion
query to `static: true` if necessary.
```

2019-10-01 18:42 UTC, mary-poppins commented
You can preview c2b8720 at https://pr32582-c2b8720.ngbuilds.io/.

2019-10-01 22:05 UTC, kara approved these changes
LGTM

2019-10-01 22:07 UTC, kara commented
merge-assistance: global approval

2019-10-02 00:19 UTC, closed without merging