Modify lazy-load module instructions for new cli flag
angular/angular pull request #32588
Opened 2019-09-10 16:16 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
 https://angular.io/guide/lazy-loading-ngmodules#create-a-feature-module-with-routing
need to be modified to use the new CLI flags for `ng g m`, `--route` and `--module`

Issue Number: https://angular-team.atlassian.net/browse/TOOL-1030

## What is the new behavior?
Page describes (and example demonstrates) new way of creating lazy-loadable modules using `ng g m --route xx --module xx`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-09-10 16:23 UTC, mary-poppins commented
You can preview 6772c10 at https://pr32588-6772c10.ngbuilds.io/.

2019-09-11 15:51 UTC, mary-poppins commented
You can preview 89ff899 at https://pr32588-89ff899.ngbuilds.io/.

2019-09-11 17:35 UTC, IgorMinar approved these changes
nice cleanup! thanks

2019-09-11 17:40 UTC, alan-agius4 commented on aio/content/guide/lazy-loading-ngmodules.md
> +This creates a `customers` folder with the new lazy-loadable module `CustomersModule` defined in the file `customers.module.ts`. The command automatically adds the `CustomerListComponent` to the new
`CustomersComponent` Instead of `CustomerListComponent`

2019-09-11 17:44 UTC, alan-agius4 commented on aio/content/guide/lazy-loading-ngmodules.md
> +Instead, it adds the declared `customer-list` route to the `routes` array in `app-routing.module.ts`.
I was referring to https://github.com/angular/angular-cli/pull/15570/files

2019-09-11 17:51 UTC, alan-agius4 commented on aio/content/guide/lazy-loading-ngmodules.md
> +<code-example language="typescript" header="app-routing.module.ts">
`app-routing.module.ts` -> `src/app/app-routing.module.ts`

2019-09-11 17:52 UTC, alan-agius4 requested changes
This is good, though I have a couple of small comments, meanly related the the chat we had yesterday.

2019-09-11 18:17 UTC, mary-poppins commented
You can preview 60272ce at https://pr32588-60272ce.ngbuilds.io/.

2019-09-11 19:14 UTC, mary-poppins commented
You can preview 13c6613 at https://pr32588-13c6613.ngbuilds.io/.

2019-09-11 19:36 UTC, mary-poppins commented
You can preview b229060 at https://pr32588-b229060.ngbuilds.io/.

2019-09-11 20:20 UTC, mary-poppins commented
You can preview e112c70 at https://pr32588-e112c70.ngbuilds.io/.

2019-09-12 05:26 UTC, alan-agius4 commented on aio/content/guide/lazy-loading-ngmodules.md
> +To make one, enter the following command at the terminal window prompt, where `customers` is the name of the features module, and `customer-list` is the component to route to:
and `customer-list` is the component to route to: -> and `customer-list` is the route path to load the `customers` component.

2019-09-12 05:27 UTC, alan-agius4 commented on aio/content/guide/lazy-loading-ngmodules.md
> +To make one, enter the following command at the terminal window prompt, where `customers` is the name of the features module, and `customer-list` is the component to route to:
at the terminal window prompt -> in the terminal

2019-09-12 15:30 UTC, alan-agius4 approved these changes
LGTM one small typo

2019-09-12 17:23 UTC, closed without merging