test(language-service): add missing tests for templateUrls
angular/angular pull request #32592
Opened 2019-09-10 19:56 UTC by ayazhafiz

Add missing tests for duplicate, missing template diagnostics

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-09-11 17:46 UTC, kyliau requested changes

2019-09-11 18:28 UTC, ayazhafiz commented on packages/language-service/test/diagnostics_spec.ts
> +        import { Component, NgModule } from '@angular/core';
Fixed.

2019-09-18 18:13 UTC, kyliau approved these changes

2019-09-18 18:19 UTC, ayazhafiz commented
Caretaker: please restart build.

2019-09-18 18:27 UTC, AndrewKushnir commented
@ayazhafiz it looks like you need to rebase this PR on top of the latest master, here is an error message from CI:
```
CONFLICT (content): Merge conflict in packages/language-service/test/diagnostics_spec.ts\nPatch failed at 0001 test(language-service): add missing tests for templateUrls
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort
```
It also looks like the most recent commit will fail the lint check due to commit description. Could you please squash commits as well?
Thank you.

2019-09-18 19:45 UTC, AndrewKushnir commented
@ayazhafiz thanks for rebasing this PR, CI is "green" now. Feel free to put "merge" label back if/when PR is ready to be merged. Thank you.

2019-09-18 20:36 UTC, closed without merging