fix(ivy): DebugNode throws exceptions when querying some properties
angular/angular pull request #32622
Opened 2019-09-11 20:52 UTC by atscott

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

In Ivy, DebugElement.query throws exceptions when querying some properties because it encounters elements created outside Angular's context.

Issue Number: N/A

## What is the new behavior?

No exceptions are thrown

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
DebugElement.injector still throws an exception because the interface doesn't support returning null.

2019-09-11 22:00 UTC, AndrewKushnir commented on packages/core/src/debug/debug_node.ts
> +  private hasPatchedData(target: any) { return target && readPatchedData(target) !== null; }
Small nit: we can probably move this function outside of the calls (as it doesn't use `this` inside) and add a return value type:
```
function hasPatchedData(target: any): boolean {
  return !!target && readPatchedData(target) !== null;
}
```
Another option might be to co-locate this function in the `render3/util/view_utils` file alongside the `readPatchedData` function and just check if property exists:
```
function hasPatchedData(target: any): boolean {
  return !!target && target.hasOwnProperty(MONKEY_PATCH_KEY_NAME);
}
```

2019-09-11 22:08 UTC, atscott commented on packages/core/src/debug/debug_node.ts
> +  private hasPatchedData(target: any) { return target && readPatchedData(target) !== null; }
Done.

2019-09-11 22:23 UTC, AndrewKushnir commented on packages/core/src/debug/debug_node.ts
> +  private hasPatchedData(target: any) { return target && readPatchedData(target) !== null; }
Thanks for the update 👍

2019-09-12 18:09 UTC, kara requested changes

2019-09-12 18:51 UTC, kara approved these changes
LGTM

2019-09-13 17:13 UTC, closed without merging