test(language-service): Create proper test project
angular/angular pull request #32653
Opened 2019-09-12 22:21 UTC by kyliau

Language service uses a canonical "Tour of Heroes" project to test
    various features, but the files are all contained in test_data.ts which
    is hard to read and often contains errors that are difficult to catch
    without proper IDE syntax highlighting. The directory structure is also
    not clear from first glance.
    
    This PR refactors the test project into standalone files in the proper
    format.
    
    Next up:
    [ ] Update the interface of MockTypeScript to only accept scriptNames.
    [ ] Remove test_data.ts
    [ ] Turn on strict mode

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-09-17 19:31 UTC, ayazhafiz requested changes

2019-09-17 19:31 UTC, ayazhafiz commented on packages/language-service/test/project/app/test.css
> +body, html {
Does this file need a license?

2019-09-17 19:31 UTC, ayazhafiz commented on packages/language-service/test/project/app/test.ng
> +~{empty}
ditto, license needed?

2019-09-17 19:31 UTC, ayazhafiz commented on packages/language-service/test/test_utils.ts
> +  private angularPath?: string;
:+1:

2019-09-17 19:31 UTC, ayazhafiz commented on packages/language-service/test/test_utils.ts
> +      // return directoryExists(directoryName, this.data);
can we get rid of this comment?

2019-09-17 19:42 UTC, kyliau commented on packages/language-service/test/project/app/test.css
> +body, html {
no, license is only needed for "source code" aka TypeScript files.

2019-09-17 19:43 UTC, kyliau commented on packages/language-service/test/test_utils.ts
> +      // return directoryExists(directoryName, this.data);
oops.. missed this. thanks!

2019-09-17 19:46 UTC, ayazhafiz approved these changes

2019-09-18 17:40 UTC, devversion approved these changes

2019-09-18 20:01 UTC, kyliau commented
caretaker: I'm a code owner of language service

2019-09-18 20:07 UTC, closed without merging