Modified a lifecycle hooks documentation sentence to be more clear.
angular/angular pull request #32675
Opened 2019-09-13 19:27 UTC by jordan-amman

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The sentence isn't that readable.

Issue Number: N/A

## What is the new behavior?
The sentence is more readable and easier to understand.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## Other information
@kapunahelewong, this is the pull request you suggested, thank you for your help! [:

2019-09-16 21:18 UTC, jordan-amman commented
@kapunahelewong Just wanted to make sure you saw this pull request since you suggested it. Thanks again!

2019-09-17 17:33 UTC, kapunahelewong requested changes
Thanks for this, @jordan-amman! Just one small thing. 

Will you tag me when you're ready?

EDIT: Oh, you'll need to amend the commit message so it'll pass, too. Try something like:

```
docs: clarify sentence in lifecycle hooks doc
```

[Here](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) are my notes on how to amend commit messages if you'd find some helpful. :)

2019-09-17 17:33 UTC, kapunahelewong commented on aio/content/guide/lifecycle-hooks.md
> +Angular creates and renders components and their children, checks when their data-bound properties change, and destroys them before removing them from the DOM.
How about this little change? (I stumbled on the second "and" when I first read it.)

```suggestion
Angular creates and renders components along with their children, checks when their data-bound properties change, and destroys them before removing them from the DOM.
```

2019-09-17 18:16 UTC, jordan-amman commented on aio/content/guide/lifecycle-hooks.md
> +Angular creates and renders components and their children, checks when their data-bound properties change, and destroys them before removing them from the DOM.
So I added these changes to a new commit, but it also shows the old commit, not sure what I'm supposed to do about that? Thanks again for your help!

2019-09-17 18:30 UTC, kapunahelewong commented on aio/content/guide/lifecycle-hooks.md
> +Angular creates and renders components and their children, checks when their data-bound properties change, and destroys them before removing them from the DOM.
Ah, check out these steps. You just need to squash. [Here's what I do](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash).

Let me know if you have any questions. :)

2019-09-25 21:22 UTC, closed without merging