Circleci 2.1 config win cache
angular/angular pull request #32745
Opened 2019-09-18 15:45 UTC by filipesilva

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
CircleCI config uses anchors a bit too extensively. 

CircleCI windows jobs don't use cache or workspaces.

## What is the new behavior?
CircleCI config uses Executors and Commands present in 2.1 config.

CircleCI windows jobs use cache or workspaces.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

FW repository version of https://github.com/angular/angular-cli/commit/38f5eeeebfca6af13f28ed7ea930279ebf8e1261#diff-1d37e48f9ceff6d8030570cd36286a61 and https://github.com/angular/angular-cli/pull/15038.

Requires CircleCI pipelines to be enable in order to support 2.1 configuration version.

2019-09-18 17:16 UTC, mary-poppins commented
You can preview fc384a1 at https://pr32745-fc384a1.ngbuilds.io/.

2019-09-18 18:04 UTC, mary-poppins commented
You can preview eedff87 at https://pr32745-eedff87.ngbuilds.io/.

2019-09-19 12:28 UTC, filipesilva commented
Note to reviewers: the windows jobs usually don't run on PRs, but I forced them to run in https://circleci.com/workflow-run/01d13c10-b1d3-4f94-8cf5-82ae90958c84 to show it still works correctly.

2019-09-19 12:36 UTC, mary-poppins commented
You can preview b441836 at https://pr32745-b441836.ngbuilds.io/.

2019-09-25 18:35 UTC, gkalpak requested changes
This is awesome 😍
Great job :tada: I love it! ❤️ 

I left a few minor comments. I guess it remains to be seen whether the caching works on Windows :grin:

The links to docs in comments are just great 👌 💯
One last nit: I think the commit messages could have a little more info in the body (expanding a bit on the commit header and maybe pointing to relevant docs).

2019-09-25 18:35 UTC, gkalpak commented on .circleci/config.yml
> +        # with either "0", "1", etc" as node index. This can be passed to the "--shard" argument.
`with either "0", "1", etc"` --> `with "0", "1", etc` (?)

2019-09-25 18:35 UTC, gkalpak commented on .circleci/config.yml
> +          condition: <<parameters.ivy>>
Super-nit: `<<parameters.ivy>>` --> `<< parameters.ivy >>` (for consistency 😇)

2019-09-25 18:35 UTC, gkalpak commented on aio/package.json
> +    "build-local-with-ivy-ci": "yarn ~~build --progress=false",
The script names also need to be updated in [aio/README.md][1].

[1]: https://github.com/angular/angular/blob/edfb0e8c8/aio/README.md

2019-09-25 18:35 UTC, gkalpak commented on .circleci/config.yml
> +      # These are very slow so we run it on non-PRs only for now.
Typo: `it` --> `them`

2019-09-25 18:38 UTC, gkalpak commented
BTW, I just ran into this neat trick to avoid the annoying `var_X:` keys when defining anchors: https://github.com/integratedexperts/drupal-dev/blob/11ed22b48/.circleci/config.yml#L13-L23

2019-09-26 10:49 UTC, filipesilva commented on .circleci/config.yml
> +# TODO: move these anchors into a windows setup job when CircleCI fixes cache/workflows on win.
They were moved in subsequent commits within this PR. I left the comment in case some commits were cherry-picked to explain why the windows anchors weren't refactored along the other anchors that were refactored in that commit.

2019-09-26 10:56 UTC, filipesilva commented on .circleci/config.yml
>        # **NOTE 1 **: Folders persisted here should be kept in sync with `var_13: &attach_workspace`.
Now that you drew my attention to it, I think this comment doesn't make sense. You can't selectively attach parts of a workspace. The only thing that matters is its root.

2019-09-26 10:58 UTC, filipesilva commented on .circleci/config.yml
> -# docker image with browsers pre-installed.
It was separated from bottom bit and moved under the `browsers-executor`, because that's where it applies.

2019-09-26 10:59 UTC, filipesilva commented on .circleci/config.yml
> +  action-executor:
I didn't think too much about that name actually, just copied it over from the CLI PR.

What do you think would be a better name? Maybe `default-executor`.

2019-09-26 11:10 UTC, filipesilva commented on .circleci/config.yml
> +# **NOTE 1 **: If you change the cache key prefix, also sync the fallback_cache_key to match.
It should be `cache_key_fallback`, I forgot to change it. Fixed.

2019-09-26 11:10 UTC, filipesilva commented on .circleci/config.yml
> +# `build-npm-packages`.
Fixed

2019-09-26 11:10 UTC, filipesilva commented on .circleci/config.yml
> +var_7: &workspace_location ~/
Which are arguably the most important places for it to be :D
Fixed

2019-09-26 11:11 UTC, filipesilva commented on .circleci/config.yml
> +        # with either "0", "1", etc" as node index. This can be passed to the "--shard" argument.
Fixed

2019-09-26 11:11 UTC, filipesilva commented on .circleci/config.yml
> +          condition: <<parameters.ivy>>
Fixed

2019-09-26 11:11 UTC, filipesilva commented on aio/package.json
> +    "build-local-with-ivy-ci": "yarn ~~build --progress=false",
Thank you, I didn't checked there. Fixed now

2019-09-26 11:11 UTC, filipesilva commented on .circleci/config.yml
> +      # These are very slow so we run it on non-PRs only for now.
Fixed

2019-09-26 11:17 UTC, mary-poppins commented
You can preview 62e29ed at https://pr32745-62e29ed.ngbuilds.io/.

2019-09-26 11:31 UTC, filipesilva commented
@gkalpak thanks for making the comments in the individual commits, that made it much easier to make fixups. I have added more context on the commit messages now.

Regarding the trick for avoiding `var_X`: if I remember correctly, we actually introduced the `anchor_x` and `var_x` names in https://github.com/angular/angular/pull/18101/files so that it was clear that these things were anchors and vars and whatnot, because yaml is kinda terse and confusing on this topic. So I'm not sure we actually want to drop it.

2019-09-26 11:40 UTC, filipesilva commented on .circleci/config.yml
> +            curl --request POST --header "Content-Type: application/json" --data "$notificationJson" $SLACK_DEV_INFRA_CI_FAILURES_WEBHOOK_URL
Done as well.

2019-09-26 11:47 UTC, mary-poppins commented
You can preview fe94a4e at https://pr32745-fe94a4e.ngbuilds.io/.

2019-09-26 15:45 UTC, gkalpak commented on .circleci/config.yml
> +  action-executor:
`default-executor` sgtm.

2019-09-26 16:21 UTC, gkalpak commented
> Regarding the trick for avoiding `var_X`: if I remember correctly, we actually introduced the `anchor_x` and `var_x` names in https://github.com/angular/angular/pull/18101/files so that it was clear that these things were anchors and vars and whatnot

Putting them in an object keyed as `anchors` or `vars` is supposed to give a hint (but not as clear as having it in front of every anchor. 

I find YAML so confusing/unreadable anyway; I don't mind either way 😛

2019-09-26 17:12 UTC, gkalpak requested changes
Thx for adding the info to commit messages :+1:
Left one last comment (and there is also https://github.com/angular/angular/pull/32745#discussion_r328207559).

Otherwise lgtm ✨

2019-09-26 17:12 UTC, gkalpak commented on .circleci/config.yml
> +        type: string
The docs are not clear on why, but [env_var_name][1] seems to be a better type for this parameter.

I would also feel better, if we only passed the variable name (without the `$`) to make it clear that the value (which should remain secret) is not exposed in the config.

[1]: https://circleci.com/docs/2.0/reusing-config/#environment-variable-name

2019-09-26 18:21 UTC, filipesilva commented on .circleci/config.yml
> +        type: string
Done

2019-09-26 18:28 UTC, mary-poppins commented
You can preview 6507bac at https://pr32745-6507bac.ngbuilds.io/.

2019-09-30 12:04 UTC, mary-poppins commented
You can preview ddbe3d6 at https://pr32745-ddbe3d6.ngbuilds.io/.

2019-10-01 18:59 UTC, josephperrott approved these changes
Overall LGTM

2019-10-01 18:59 UTC, josephperrott commented on .circleci/config.yml
> +      # In order to avoid the bottleneck of having a slow host machine, we acquire a better
I'm a little confused by this comment.  From the comment it seems like we should not be requesting an xlarge resource class machine?

2019-10-02 07:33 UTC, filipesilva commented on .circleci/config.yml
> +      # In order to avoid the bottleneck of having a slow host machine, we acquire a better
I don't quite follow. The comment seems to be saying that an xlarge machine is needed because otherwise it would be a bottleneck.

2019-10-02 07:34 UTC, filipesilva commented on .circleci/config.yml
> +  action-executor:
done

2019-10-02 07:45 UTC, mary-poppins commented
You can preview a632487 at https://pr32745-a632487.ngbuilds.io/.

2019-10-02 09:12 UTC, gkalpak approved these changes

2019-10-02 16:34 UTC, closed without merging

2019-10-02 16:35 UTC, atscott commented
Hi @filipesilva - There was a merge conflict with the patch branch. Can you create a new PR that targets path only and resolve those conflicts?

2019-10-03 15:30 UTC, filipesilva commented
@atscott patch version is https://github.com/angular/angular/pull/32982