feat(language-service): module definitions on directive hover
angular/angular pull request #32763
Opened 2019-09-18 23:26 UTC by ayazhafiz

Adds information about the NgModule a Directive is declared in when the
Directive class name is hovered over, in the form

```
(directive) NgModule.Directive: class
```

Closes #32565

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Feature

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-09-19 18:10 UTC, kyliau requested changes

2019-09-19 18:10 UTC, kyliau commented on packages/language-service/src/language_service.ts
> +        return getTsHover(sf, position, this.host);
since we already have `analyzedModules` on line 95 above, I think it's more efficient (and safer) to just reuse that instead of calling `host.getAnalyzedModules()` again in the impl of `getTsHover()`. This is because `getAnalyzedModules()` retrieves the `program`, which could potentially trigger a recomputation of the dependency graph. This could be a slow operation, but more importantly, it means the second `analyzedModules` might now be different from the first `analyzedModules`.
Overall, I think the design philosophy should be that `getAnalyzedModules()` is only called once, and only in this file. (the exception being `getExternalFiles()`).

2019-10-02 14:06 UTC, ayazhafiz commented on packages/language-service/src/language_service.ts
> +        return getTsHover(sf, position, this.host);
I think we agreed on using the non-synchronized `getAnalyzedModules`, right? I'm going to implement that.

2019-10-02 17:17 UTC, kyliau approved these changes

2019-10-02 17:18 UTC, kyliau commented on packages/language-service/src/language_service.ts
> +        return getTsHover(sf, position, this.host);
yes, LGTM. thank you!

2019-10-02 18:16 UTC, ayazhafiz commented
Caretaker: test failure appears to be a flake and not related to this PR.

2019-10-02 20:26 UTC, closed without merging