refactor(compiler): add details while throw error during expression c…
angular/angular pull request #32760
Opened 2019-09-18 21:50 UTC by mohaxspb

…onvert

Fixes #32759

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 32759

## What is the new behavior?

Now there is details in error message with variable names in template expression, which causes prod build failing.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-09-19 17:00 UTC, Splaktar requested changes
Can you please add an example of the new output in your PR description?

2019-09-19 17:00 UTC, Splaktar commented on packages/compiler/src/compiler_util/expression_converter.ts
> +              'Cannot assign to a reference or variable while convert expression! Details: ' +
>  while convert expression

I'm not sure what the proper description is here, but this doesn't quite make sense or at least isn't fully proper English. If we can clean it up, it would be nice to include more than just "Cannot assign to a reference or variable!"

2019-09-19 17:54 UTC, Splaktar commented
The related test also needs to be updated:
```sh
HeadlessChrome 74.0.3729 (Linux 0.0.0) ChangeDetection expressions event expressions should throw when trying to assign to a local FAILED
	Error: Expected function to throw an exception with a message matching /Cannot assign to a reference or variable!/, but it threw an exception with message 'Cannot assign to a reference or variable while convert expression! Details: {"span":{"start":0,"end":8},"receiver":{"span":{"start":0,"end":0}},"name":"$event","value":{"span":{"start":7,"end":8},"value":1}}'.
	    at <Jasmine>
	    at UserContext.eval (packages/core/test/linker/change_detection_integration_spec.ts:667:16 <- angular/packages/core/test/linker/change_detection_integration_spec.js:517:28)
	    at UserContext.eval (node_modules/zone.js/dist/zone-testing.js:1442:34)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:396:30)
```

2019-09-19 19:39 UTC, mohaxspb commented
> Can you please add an example of the new output in your PR description?

Now I have problems with building project with angular version from PR. Yesterday it work, but now not. Am I do it correctly? I run `./build-packages-dist.sh` in `/scripts`, then replace all files in `myExampleProjectDir/node_modules/@angular`. May be there is a better way to test updated version?

2019-09-19 19:46 UTC, mohaxspb commented on packages/compiler/src/compiler_util/expression_converter.ts
> +              'Cannot assign to a reference or variable while convert expression! Details: ' +
May be something like this: `LocalExpr is not instance of ReadPropExpr in _AstToIrVisitor#visitPropertyWrite at expression_converter.ts! Expression details: ${JSON.stringify(ast)}`

Sorry, English is not my first language, so I'm not sure if text is correct)

2019-09-19 19:51 UTC, mohaxspb commented
> The related test also needs to be updated:
> 
> ```shell
> HeadlessChrome 74.0.3729 (Linux 0.0.0) ChangeDetection expressions event expressions should throw when trying to assign to a local FAILED
> 	Error: Expected function to throw an exception with a message matching /Cannot assign to a reference or variable!/, but it threw an exception with message 'Cannot assign to a reference or variable while convert expression! Details: {"span":{"start":0,"end":8},"receiver":{"span":{"start":0,"end":0}},"name":"$event","value":{"span":{"start":7,"end":8},"value":1}}'.
> 	    at <Jasmine>
> 	    at UserContext.eval (packages/core/test/linker/change_detection_integration_spec.ts:667:16 <- angular/packages/core/test/linker/change_detection_integration_spec.js:517:28)
> 	    at UserContext.eval (node_modules/zone.js/dist/zone-testing.js:1442:34)
> 	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:396:30)
> ```

OK, I'll fix it as soon as we choose correct error message)

2019-09-19 20:03 UTC, mohaxspb commented on packages/compiler/src/compiler_util/expression_converter.ts
> +              'Cannot assign to a reference or variable while convert expression! Details: ' +
There is test for it:

```
it('should throw when trying to assign to a local', fakeAsync(() => {
  expect(() => {
    _bindSimpleProp('(event)="$event=1"');
  }).toThrowError(new RegExp('Cannot assign to a reference or variable!'));
}));
```

so, may be, error message should be `Cannot assign value to a reference or variable in template. Details: ${JSON.stringify(ast)}`

And instead of `JSON.stringify(ast)` we can parse `ast` object, in attempt to restore parsed expression (i.e. `myTemplateVar=someValueOrMethodCall`). But, it depends on #32762, where this may be valid... So I'm really don't have idea what should we use as error message(

2019-09-19 20:42 UTC, Splaktar commented
Have you tried [`npm-link`](https://docs.npmjs.com/cli/link)?

2019-09-19 21:06 UTC, mohaxspb commented
> Have you tried [`npm-link`](https://docs.npmjs.com/cli/link)?

Thanks, I'll try it.

2019-09-20 16:33 UTC, mohaxspb commented
@Splaktar I change error message and fix test, where its message checks. What do you think about new error message - is it OK?

2019-09-20 23:39 UTC, Splaktar commented on packages/compiler/src/compiler_util/expression_converter.ts
> +              `LocalExpr is not instance of ReadPropExpr in _AstToIrVisitor#visitPropertyWrite at expression_converter.ts! ` +
I think that this is too much detail and it won't really be helpful to app developers. Let's get rid of this line.

2019-09-20 23:39 UTC, Splaktar commented on packages/compiler/src/compiler_util/expression_converter.ts
> +              `Do not assign to local variable in template! Failed expression details: ${JSON.stringify(ast)}`);
I don't think that the explanation point is very helpful (in this or the old version).

I'm a little hesitant to just `JSON.stringify` the whole `ast` here. Could this be a really large AST? Could there be memory or other concerns doing so?

Would it be better to just report the first few key value pairs (if they exist)?

2019-10-26 15:19 UTC, mohaxspb commented on packages/compiler/src/compiler_util/expression_converter.ts
> +              `Do not assign to local variable in template! Failed expression details: ${JSON.stringify(ast)}`);
@Splaktar hello!

I update PR. Could you, please, look at changed error message and tell me what do you think about it?

2019-10-26 15:51 UTC, mohaxspb commented
Seems to be after latest commit PR fails some check. And I have no idea what's wrong here(

2019-10-27 03:57 UTC, AndrewKushnir commented
@mohaxspb it looks like rebasing on top of the latest master should resolve the problem with CI. Thank you.

2019-10-27 15:38 UTC, mohaxspb commented
> @mohaxspb it looks like rebasing on top of the latest master should resolve the problem with CI. Thank you.

Thanks! That was the problem) I just forgot to add remote to my fork and update it)

2019-11-04 21:56 UTC, kara requested changes
Thanks for submitting a PR to improve the error message! Some thoughts below

2019-11-04 21:56 UTC, kara commented on packages/compiler/src/compiler_util/expression_converter.ts
> +              `ReadPropExpr expected but ${exprName} found with receiver "${receiver}" and value "${value}"`);
I don't think most people will know what these terms mean. Can we be specific about what the user is doing? e.g. 

```suggestion
              `Cannot assign value "${value}" to template variable "${receiver}". Template variables are read-only.`);
```

2019-11-07 15:41 UTC, mohaxspb commented on packages/compiler/src/compiler_util/expression_converter.ts
> +              `ReadPropExpr expected but ${exprName} found with receiver "${receiver}" and value "${value}"`);
@kara hello! I've update PR with suggested changes)

2019-11-07 16:50 UTC, mohaxspb commented
@Kara, seems to be I failed to correctly rebase on master... Is there is a way to fix something or I should just close PR? I really have no idea what's going on(

2019-11-07 22:32 UTC, kara commented
@mohaxspb Looks like you've mostly figured out the Git issue? The only thing left to do would be to squash the commits into one commit.

(Here's how if you've never done it before: https://github.com/wprig/wprig/wiki/How-to-squash-commits)

2019-11-07 22:32 UTC, kara approved these changes
LGTM once the commits are squashed into one.

2019-11-08 14:21 UTC, mohaxspb commented
> @mohaxspb Looks like you've mostly figured out the Git issue? The only thing left to do would be to squash the commits into one commit.
> 
> (Here's how if you've never done it before: https://github.com/wprig/wprig/wiki/How-to-squash-commits)

Done, there is the only commit in PR now. Is it OK, that some tests failed (as I remember, there are some timeout errors in `legacy-unit-tests-saucelabs`)? It was the reason for trying to rebase branch to master, as it helped previously. If rebasing required, I'll try to create new PR with same changes, as I can't succeed in rebasing with current PR, however it works some weeks ago.

2019-11-11 09:53 UTC, petebacondarwin commented
Thanks for squashing the commits @mohaxspb - I have restarted the failing test - it is probably a flake.
The PR ought to have a presubmit but since it is only a change to an error message, @kara might override that and just mark it for merge once the tests all pass.

2019-11-11 15:55 UTC, petebacondarwin commented
The rebase should be quite simple...


```
git fetch origin master
git checkout  ng-var-prod-build-error-message
git rebase master
git push --force-with-lease
```

I can rebase it for you if this does not work for you.

2019-11-11 16:12 UTC, mohaxspb commented
@petebacondarwin hmm... Seems to be I rebase it. You commands worked as expected, thanks! Lets wait and see if tests will not fail now)

2019-11-11 17:03 UTC, mohaxspb commented
@petebacondarwin , @kara @Splaktar all tests passed. As I understand, now there is nothing more to do on my side and you could merge PR?

2019-11-15 23:58 UTC, IgorMinar commented
I just started the presubmit tests at google:
- https://test/OCL:280752267:BASE:280752295:1573861687704:dc3ea22b
- http://test/OCL:280752267:BASE:280752953:1573861891965:349398ef

if they pass, we'll merge this PR next week. thanks for being patient with us.

2019-11-16 00:05 UTC, mohaxspb commented
@IgorMinar, great! Thank you) 

Is it OK that I can't see something at links in you message?

2019-11-16 08:20 UTC, petebacondarwin commented
@mohaxspb - yes - the links are to internal systems at Google. So only Googlers can access them.

2019-11-17 19:25 UTC, mohaxspb commented
@IgorMinar hello again! As I can see, something failed in tests. Is there is that I can do in that case? Or only Angular command can do something with it?

2019-11-18 00:43 UTC, AndrewKushnir commented
Hi @mohaxspb, I've checked the tests and results look good (there was 1 unrelated failure), so I changed the status of g3 check to "green". Thank you.

2019-11-18 18:10 UTC, kara commented
merge-assistance: global approval

2019-11-18 23:48 UTC, closed without merging