feat(language-service): allow retreiving synchronized analyzed NgModules
angular/angular pull request #32779
Opened 2019-09-19 21:34 UTC by ayazhafiz

Sometimes modules retreived from the language service need to be
synchronized to the last time they were updated, and not updated
on-the-fly. This PR adds a flag to
`TypeScriptServiceHost#getAnalyzedModules` that retreives cached
analyzed NgModules rather than potentially recomputing them.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Feature

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-09-19 21:58 UTC, kyliau requested changes

2019-09-19 21:58 UTC, kyliau commented on packages/language-service/src/typescript_host.ts
> +   * @param ensureSynchronized if true, returns the set of analyzedModules that is already cached.
Sorry, this seems contrary to the idea of `ensureSynchronized`.
The flag means that if true, "do the work to make sure the program is synchronized".
The cached result should be returned if `ensureSynchronized` is false, i.e. no need to make sure it is up-to-date.

tldr; this should default to true.
See https://github.com/microsoft/TypeScript/blob/e60d28e6f76e7bbb25e06a1742dc9a24fd7a1f16/src/server/project.ts#L509

2019-09-19 22:02 UTC, ayazhafiz commented on packages/language-service/src/typescript_host.ts
> +   * @param ensureSynchronized if true, returns the set of analyzedModules that is already cached.
Ah, my thinking was inverted. thanks!

2019-09-20 21:34 UTC, rbuzzibarrios approved these changes

2019-10-01 17:13 UTC, kyliau approved these changes

2019-10-01 18:02 UTC, closed without merging