docs: clarify http response type
angular/angular pull request #32817
Opened 2019-09-23 16:08 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Clarifies that the type of the `responseType` option property is String that identifies the type of response, not a union of all the types it could be. 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The combined signature for all the overloads makes it look like the type for `responseType` could be a union.

Issue Number: https://github.com/angular/angular/issues/21017

## What is the new behavior?
Added note to  https://angular.io/api/common/http/HttpClient#description clarifying the type of `responseType`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-09-23 16:17 UTC, mary-poppins commented
You can preview 315d719 at https://pr32817-315d719.ngbuilds.io/.

2019-09-23 16:30 UTC, kapunahelewong requested changes
Just a couple of notes.

2019-09-23 16:30 UTC, kapunahelewong commented on packages/common/http/src/client.ts
> + * Each data type is handled by a single overload version of the method.
Switch to active voice:

> A single overload version of the method handles each data type.

^^Does that still correctly convey the meaning?

2019-09-23 16:30 UTC, kapunahelewong commented on packages/common/http/src/client.ts
> + * The value cannot be a union (as the combined signature could imply).
Avoid parentheses. Maybe some other form of punctuation could help. Here's where I get that guideline https://developers.google.com/style/parentheses

2019-09-23 16:30 UTC, kapunahelewong commented on packages/common/http/src/client.ts
> + * Each data type is handled by a single overload version of the method.
Same as above: active/passive

2019-09-23 16:30 UTC, kapunahelewong commented on packages/common/http/src/client.ts
> + * The value cannot be a union (as the combined signature could imply).
Same note on ().

2019-09-23 16:48 UTC, mary-poppins commented
You can preview 1815935 at https://pr32817-1815935.ngbuilds.io/.

2019-09-24 17:04 UTC, mary-poppins commented
You can preview 1a891f7 at https://pr32817-1a891f7.ngbuilds.io/.

2019-09-25 16:19 UTC, mary-poppins commented
You can preview fef2ead at https://pr32817-fef2ead.ngbuilds.io/.

2019-09-26 15:56 UTC, mary-poppins commented
You can preview c755329 at https://pr32817-c755329.ngbuilds.io/.

2019-09-30 15:52 UTC, mary-poppins commented
You can preview cd1cd75 at https://pr32817-cd1cd75.ngbuilds.io/.

2019-09-30 16:14 UTC, kapunahelewong approved these changes
LGTM!

2019-10-01 15:24 UTC, jbogarthyde commented
Docs only, doesn't need G3

2019-10-01 16:04 UTC, mary-poppins commented
You can preview dcf058b at https://pr32817-dcf058b.ngbuilds.io/.

2019-10-01 18:00 UTC, closed without merging