docs: clarify getting started step 5
angular/angular pull request #32888
Opened 2019-09-27 19:31 UTC by kapunahelewong

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently, steps in deployment need a little more detail. 

Issue Number: N/A

## What is the new behavior?

Steps to deploy have accompanying info in case of polyfills error. Section on deploying to Firebase is more specific for first time user. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- Removes "we" per Google Developers Guide: https://developers.google.com/style/person
- Reduces future tense (for example "will be"): https://developers.google.com/style/tense
- Adds headers to code snippets
- Clears up passive voice
- Reduces parentheses: https://developers.google.com/style/parentheses

2019-09-27 19:38 UTC, mary-poppins commented
You can preview 1732bdb at https://pr32888-1732bdb.ngbuilds.io/.

2019-09-27 19:42 UTC, santoshyadav198613 commented on aio/content/start/deployment.md
> -1. Once deployed, visit https://your-firebase-project-name.firebaseapp.com to see it live!
Just a thought on this one as Angular already had ng deploy recently, why not to mention that rather.

2019-09-28 01:17 UTC, kapunahelewong commented on aio/content/start/deployment.md
> -1. Once deployed, visit https://your-firebase-project-name.firebaseapp.com to see it live!
I'm not sure I understand. Could you point me to the right spot?

2019-09-28 02:32 UTC, ericmartinezr commented on aio/content/start/deployment.md
> -1. Once deployed, visit https://your-firebase-project-name.firebaseapp.com to see it live!
@kapunahelewong he means this https://github.com/angular/angular-cli/pull/15105

2019-09-30 18:42 UTC, gkalpak commented on aio/content/start/deployment.md
> +1. Deploy your application with `firebase deploy`. StackBlitz has created a `firebase.json` that tells Firebase how to serve your app. The following is an example of the output of a successful deploy
This is a little confusing. If I am not mistaken, `firebase init` will create a `firebase.json` (based on your answers). If we already have a `firebase.json` from StackBlitz, why do we need `firebase init`?

2019-09-30 18:42 UTC, gkalpak commented on aio/content/start/deployment.md
> +1. For the public directory, enter `dist`.
Shouldn't it be `dist/my-project-name`?

2019-09-30 20:24 UTC, kapunahelewong commented on aio/content/start/deployment.md
> +1. Deploy your application with `firebase deploy`. StackBlitz has created a `firebase.json` that tells Firebase how to serve your app. The following is an example of the output of a successful deploy
Oh, good catch. I think that's incorrect. I just confirmed that the download from StackBlitz doesn't come with a `firebase.json` - that happens only after the `firebase init`. Fixed. 

Screenshots for the curious:
**In root:**
![image](https://user-images.githubusercontent.com/4116963/65912064-97ef7700-e39b-11e9-8695-88b85c6683f4.png)

**In `src`:**
![image](https://user-images.githubusercontent.com/4116963/65911877-4d6dfa80-e39b-11e9-8937-fa021aa4d414.png)

2019-10-04 19:41 UTC, StephenFluin requested changes

2019-10-04 19:41 UTC, StephenFluin commented on aio/content/start/deployment.md
> +<div class="alert is-helpful">
We should add a comment here about a removal date.1 month? 3 months? 6 months? we've fixed this bug so new users won't encounter this.

2019-11-18 18:24 UTC, mary-poppins commented
You can preview a771a15 at https://pr32888-a771a15.ngbuilds.io/.

2020-01-17 21:06 UTC, mary-poppins commented
You can preview 51dc51e at https://pr32888-51dc51e.ngbuilds.io/.

2020-03-11 17:14 UTC, kapunahelewong commented
Closing as @sonukapoor took this over in https://github.com/angular/angular/pull/35510. Thank you, @sonukapoor!!!

2020-03-11 17:14 UTC, closed without merging