build: generate CODEOWNERS from rules in each package
angular/angular pull request #32884
Opened 2019-09-27 17:57 UTC by alexeagle

This introduces a test `//.github:test` that asserts we generate an identical CODEOWNERS file as today.

Once we are happy with this setup (maybe during review of this PR) we can clobber the CODEOWNERS file with the generated output.

2019-09-28 03:56 UTC, alexeagle commented
@josephperrott want to review/discuss?

2019-09-28 18:59 UTC, gkalpak requested changes
Cool stuff 🤔

2019-09-28 18:59 UTC, gkalpak commented on BUILD.bazel
> +    name = "OWNERS.vscode-bazel",
Why `vscode-bazel`? These seem to be unrelated 😕

2019-09-28 18:59 UTC, gkalpak commented on package.json
> +    "unidiff": "^1.0.2",
Is this used?

2019-09-28 18:59 UTC, gkalpak commented on .github/BUILD.bazel
> +        "@angular/framework-global-approvers",
Why `allow_global_approval = False` and `@angular/framework-global-approvers`?
Couldn't it be `allow_global_docs_approval = False` instead?

2019-09-28 18:59 UTC, gkalpak commented on .github/BUILD.bazel
> +# - remove comments
Pfff...who needs comments 😛
(Kidding aside, the `CODEOWNERS` file contains some important info in comments that should be preserved somewhere.)

2019-09-30 22:56 UTC, alexeagle commented on .github/BUILD.bazel
> +# - remove comments
Yes my thought was to move it to whatever place references the codeowners in the commit where we clobber its comments

2019-09-30 22:56 UTC, alexeagle commented on package.json
> +    "unidiff": "^1.0.2",
Yes it's a dep of the golden_file_test Bazel rule.

2019-09-30 22:57 UTC, alexeagle commented on BUILD.bazel
> +    name = "OWNERS.vscode-bazel",
They are, it was just saving a few lines since they can be collapsed.
Really a lot of the complexity here is to preserve accidental total ordering constraints in the existing file.

2019-10-04 12:24 UTC, alexeagle commented on .github/BUILD.bazel
> +        "@angular/framework-global-approvers",
it can, fixed

2019-10-04 12:24 UTC, alexeagle commented
LGTY?

2019-10-04 14:00 UTC, gkalpak reviewed
BTW, we need some docs on how to add a new pattern to CODEOWNERS (including how to use `no_parent`/`no_docs_parent`).

Other than my previous comments, I don't have any objection.

2019-10-04 18:24 UTC, alexeagle commented on package.json
> +    "unidiff": "^1.0.2",
since the `golden_file_test` is defined in the build_bazel_rules_nodejs builtin, and not in an npm package under `@bazel/*`, it has no way to declare the dependency itself.

One option is to vendor the diff library so it's distributed in the .tgz file for rules_nodejs and there's no need to fetch a package. Another option is to make the golden_file_test work with some other diff library, we already have a dependency on the `diff` package in Angular. A third option is not to use that rule at all, and implement something one-off (we already have other places in the angular project which do that, like the golden symbol test and the public_api_guard)

2019-10-04 18:25 UTC, alexeagle commented on .github/CODEOWNERS
> +# testing/**                                                      @angular/fw-testing @angular/framework-global-approvers @angular/framework-global-approvers-for-docs-only-changes
oops I thought I had totally reverted changes to this file. fixed

2019-10-04 18:30 UTC, alexeagle commented on .github/CODEOWNERS
> +# /.buildkite/**                                                  @angular/dev-infra-framework
reverted

2019-10-04 18:30 UTC, alexeagle commented on .github/BUILD.bazel
> +    tags = ["manual"],
I'm sorry, seems like a snapshot didn't get published - did my push fail? Yeah I removed this

2019-10-04 18:32 UTC, alexeagle commented on tools/defaults.bzl
> +    # Preserve legacy content: no docs-only-changes in some places
added more text to clarify

# This is here to exactly match the legacy content
    # in the CODEOWNERS file while moving it to bazel-generated.
    # Some places don't permit docs-only-changes approval.
    # see http://go/owners#noparent

2019-10-04 18:49 UTC, alexeagle commented on tools/defaults.bzl
> +]
It was a shorthand, but I think it's better to have all in one place. Removed these lists and moved all config into the codeowners rules

2019-10-07 11:10 UTC, gkalpak commented on package.json
> +    "unidiff": "^1.0.2",
I am a little confused 😅
- Why is `golden_test_file` part of `rules_nodejs`? Is it used internally there?
- Does `rules_nodejs` declare a dependency on `undiff`?
- How is this thing supposed to be handled in the bazel world? How do dependants know about dependencies required by rules they use (such as `golden_test_file`)?

2019-10-10 00:30 UTC, alexeagle commented
@IgorMinar how long until you switch to pullapprove? is this still useful to move the source of truth out of a single file? when you do switch to pullapprove I'm sure we can configure it using the output of the bazel rule here

2019-10-21 15:28 UTC, matsko commented
@alexeagle please rebase your PR

2019-10-25 14:03 UTC, alexeagle commented
This seems stuck because the team is thinking about moving to pullapprove.

I'm not going to spend effort on rebase and keeping this green if it's not going to get approved.
Note that rules_nodejs uses this scheme now, along with a script to automatically keep the `.github/BUILD` up-to-date.

2019-11-21 21:57 UTC, matsko commented
I'm moving this PR out of the `PR: Merge` status because it hasn't had any activity close to two months now.

2020-02-03 16:23 UTC, IgorMinar commented
With the move to pullapprove this PR is now obsolete.

2020-02-03 16:23 UTC, closed without merging

2020-02-03 16:26 UTC, IgorMinar commented
I like the idea of decentralizing the pullapprove config it would however take too much energy to fiddle with build rules to make it work exactly how we need it. For now an explicit config is a safer choice.