docs: add info about bypassing non-css asset processing
angular/angular pull request #32921
Opened 2019-09-30 20:35 UTC by dannyskoog

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #32811

## What is the new behavior?
Describes how to bypass asset processing for non-CSS style files

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-09-30 21:20 UTC, dannyskoog commented
Poking @kapunahelewong

2019-10-01 16:08 UTC, kapunahelewong requested changes
Thanks for this, @dannyskoog! Just a couple of suggestions. Please tag me when you're ready for another review. :)

2019-10-01 18:57 UTC, dannyskoog commented on aio/content/guide/component-styles.md
> +By default assets are **processed** for non-CSS style files, although possible to bypass by using a leading *caret* in the path (e.g. `background: url("^../foo.png")`).
I like them :)

2019-10-01 19:03 UTC, dannyskoog commented on aio/content/guide/component-styles.md
> +This is useful for assets not resolvable at build time but rather at run time.
Sure

2019-10-01 19:08 UTC, kapunahelewong commented on aio/content/guide/component-styles.md
> +This is useful for assets not resolvable at build time but rather at run time.
If you want to comment them here so you donʻt have to edit and push up over and over, thatʻs works too. :)

2019-10-01 19:53 UTC, dannyskoog commented on aio/content/guide/component-styles.md
> +This is useful for assets not resolvable at build time but rather at run time.
Sure. I'm thinking something like this:

This is useful for assets not resolvable at build time but rather at run time. For example:
* Having global styles (styles.css) loaded from a CDN where assets are relative to the file itself
* Referencing assets outside of the project root

2019-10-01 20:12 UTC, kapunahelewong commented on aio/content/guide/component-styles.md
> +This is useful for assets not resolvable at build time but rather at run time.
Ah ok, that sounds good from a docs perspective. I just have to get another review. In the meantime, would you like to add it in?

2019-10-01 20:16 UTC, dannyskoog commented on aio/content/guide/component-styles.md
> +This is useful for assets not resolvable at build time but rather at run time.
Thanks. Sure, I'll get on top of it

2019-10-02 08:02 UTC, filipesilva requested changes

2019-10-02 08:02 UTC, filipesilva commented on aio/content/guide/component-styles.md
> +By default, Angular processes assets for non-CSS style files. However, it is possible to bypass this behavior by using a leading caret `^` in the path, for example, `background: url("^../foo.png")`.
Can you call them `resources` instead of `assets` here please? We try to call these two things different names in order to not confuse the dependencies of css files with the contents of the `assets` array in `angular.json`.

2019-10-02 08:02 UTC, filipesilva commented on aio/content/guide/component-styles.md
> +By default, Angular processes assets for non-CSS style files. However, it is possible to bypass this behavior by using a leading caret `^` in the path, for example, `background: url("^../foo.png")`.
@clydin is the `^` escape part of our public API and supported as such?

2019-10-02 09:44 UTC, dannyskoog commented on aio/content/guide/component-styles.md
> +By default, Angular processes assets for non-CSS style files. However, it is possible to bypass this behavior by using a leading caret `^` in the path, for example, `background: url("^../foo.png")`.
Sure @filipesilva. And you are referring to all **4** usages of the `assets` term, correct?

2019-10-02 09:47 UTC, filipesilva commented on aio/content/guide/component-styles.md
> +By default, Angular processes assets for non-CSS style files. However, it is possible to bypass this behavior by using a leading caret `^` in the path, for example, `background: url("^../foo.png")`.
I am indeed, thank you!

2019-10-02 11:24 UTC, dannyskoog commented on aio/content/guide/component-styles.md
> +By default, Angular processes assets for non-CSS style files. However, it is possible to bypass this behavior by using a leading caret `^` in the path, for example, `background: url("^../foo.png")`.
Done @filipesilva!

2019-10-02 12:40 UTC, filipesilva commented on aio/content/guide/component-styles.md
> +By default, Angular processes assets for non-CSS style files. However, it is possible to bypass this behavior by using a leading caret `^` in the path, for example, `background: url("^../foo.png")`.
Great, just waiting for @clydin's reply before I turn my review green.

2019-10-03 15:04 UTC, dannyskoog commented on aio/content/guide/component-styles.md
> +By default, Angular processes assets for non-CSS style files. However, it is possible to bypass this behavior by using a leading caret `^` in the path, for example, `background: url("^../foo.png")`.
@clydin - Could you please have a look at this PR when you have the time? Thanks

2019-10-03 15:56 UTC, clydin commented on aio/content/guide/component-styles.md
> +By default, Angular processes assets for non-CSS style files. However, it is possible to bypass this behavior by using a leading caret `^` in the path, for example, `background: url("^../foo.png")`.
While the use of the carat does provide the functionality described, it is not currently considered a supported feature and would at a minimum be deemed experimental.  There is also a high probability that this will be removed in favor of a comment-based pragma directive approach in the future.

Also of note is that the Angular CLI will process all stylesheet assets specified via a CSS `url` function with a relative URL.  This includes CSS, Sass, Less, and Stylus files.

2019-10-03 16:26 UTC, dannyskoog commented on aio/content/guide/component-styles.md
> +By default, Angular processes assets for non-CSS style files. However, it is possible to bypass this behavior by using a leading caret `^` in the path, for example, `background: url("^../foo.png")`.
Thanks for the info @clydin! So you use it internally then?

What I mean by ”process” is verifying that the asset exists at the given path (at build time). This is bypassed by using a leading caret in the path.

2019-10-04 21:02 UTC, dannyskoog commented
After info from @clydin it was brought to light that this is not a supported feature. Therefore I’ll close this PR for the time being.

2019-10-04 21:02 UTC, closed without merging