docs: added value param wrt. method signature
angular/angular pull request #32968
Opened 2019-10-02 17:30 UTC by mumairofficial

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Added missing value param for `append` method documentation. This change will help IDEs to show better documentation while code completion.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-10-02 17:31 UTC, mumairofficial commented
@googlebot I fixed it.

2019-10-02 18:21 UTC, mumairofficial commented
@googlebot I fixed it.

2019-10-18 18:21 UTC, kapunahelewong commented
Thanks for this, @mumairofficial. My apologies for the delay. Requesting @jbogarthyde for review as she knows the API docs well. @jbogarthyde, will you let me know when you're ready and I'll come back to help get this through the rest of the way? Thanks!

2019-10-21 16:21 UTC, jbogarthyde approved these changes
Good catch, thanks!

2019-10-21 20:22 UTC, kapunahelewong commented
Thanks, @jbogarthyde! @mumairofficial, all you need to do now is [fix the conflicts](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line) and rebase since it is a bit behind master. Here are my [own notes for rebasing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) if you'd like them. Will you tag me when you're ready? Thanks!

2019-10-22 00:42 UTC, trotyl commented on packages/common/http/src/headers.ts
> +   * @param value The value to set or overide for a given name.
The value here is to append, not set or override.

2019-10-22 05:33 UTC, jbogarthyde commented on packages/common/http/src/headers.ts
> +   * @param value The value to set or overide for a given name.
Oops, you’re right!  How about simply “The value to append.”

2019-10-22 05:37 UTC, jbogarthyde requested changes

2019-10-22 05:37 UTC, jbogarthyde commented on packages/common/http/src/headers.ts
> +   * @param value The value to set or overide for a given name.
Oops, you’re right! How about simply “The value to append.”

2019-10-22 06:14 UTC, trotyl commented on packages/common/http/src/headers.ts
> +   * @param value The value to set or overide for a given name.
@jbogarthyde SGTM

2019-10-22 07:25 UTC, mumairofficial commented on packages/common/http/src/headers.ts
> +   * @param value The value to set or overide for a given name.
I have updated ~set~ to append

2019-10-22 15:23 UTC, jbogarthyde reviewed
No, it does not override, it just appends. Please just use the shorter phrase: "The value to append."

2019-10-24 07:57 UTC, mumairofficial commented
@jbogarthyde I have removed the override statement as you suggested

2019-10-24 15:03 UTC, jbogarthyde approved these changes
Thanks. This works. I think you have to rebase again.

2019-11-04 23:30 UTC, jbogarthyde commented
@mumairofficial 
Looks like the rebase failed - try again?

2019-11-06 10:19 UTC, mumairofficial commented
@jbogarthyde sure I am trying again

2019-11-06 10:37 UTC, mumairofficial commented
@googlebot I fixed it.

2019-11-06 12:29 UTC, mumairofficial commented
@googlebot I consent.

2019-11-06 17:31 UTC, kapunahelewong commented
Hey @mumairofficial, it looks like the result of that last step was unintentional. To undo it, you should be able to do a `git reflog` and find the place you want to back up to. Checkout the accepted answer on this [StackOverflow question](https://stackoverflow.com/questions/11722533/rollback-a-git-merge/29110174). First, make sure to back up your work (you should just be able to copy and paste it somewhere else on your computer separate from your project because doing a git reset will erase things). If it's still not working out, please let me know.

2019-11-06 17:49 UTC, mumairofficial commented
@kapunahelewong Sure I can try.

2019-11-06 18:22 UTC, kapunahelewong commented
Hey, @mumairofficial, I think I fixed it? Mind if I push up what I did? Honestly it was a little tricky to come to my eventual (I think) solution, and I'm not sure of the answer to your question.

2019-11-06 18:23 UTC, kapunahelewong commented
I'll have to force push probably so you may want to back up your work.

2019-11-06 19:18 UTC, mumairofficial commented
@kapunahelewong yes you may push your solution. Also I am facing issues with my git behaving very strange. Thanks for backup suggestion to safe life.

2019-11-06 19:19 UTC, kapunahelewong commented
Gasp! It worked!!! Is all your work still in there though? If not, keep your back up, then pull this down and edit it. If your git is still acting funny, just put it in a comment and I'll add it for you. Easy peasy. :)

2019-11-06 19:25 UTC, mumairofficial commented
@kapunahelewong Yup recovered my work. Learned new git lesson :) Ends up replacing .git directory

2019-11-06 19:49 UTC, jbogarthyde commented
Caretaker: This is a small, doc-only change that shouldn't actually need code-owner approval or G3.

2019-11-06 19:51 UTC, closed without merging