feat(core): add postinstall ngcc migration
angular/angular pull request #32999
Opened 2019-10-04 13:23 UTC by filipesilva

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe: 

## What is the current behavior?
Projects updating via `ng update` to Angular version 9 will take longer on the first build due to running `ivy-ngcc` automatically during the build step.

## What is the new behavior?
A postinstall script ensures `ivy-ngcc` is run when installing dependencies instead.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
https://angular-team.atlassian.net/browse/TOOL-1076

2019-10-04 13:31 UTC, mary-poppins commented
You can preview 42dae45 at https://pr32999-42dae45.ngbuilds.io/.

2019-10-04 13:40 UTC, mary-poppins commented
You can preview 7f3a0d4 at https://pr32999-7f3a0d4.ngbuilds.io/.

2019-10-04 14:05 UTC, mary-poppins commented
You can preview 1e111e2 at https://pr32999-1e111e2.ngbuilds.io/.

2019-10-04 14:17 UTC, gkalpak approved these changes
A couple of nit. Otherwise lgtm 👍

There is one difference, though, that might warrant updating the [Ivy opt-out guide][1]:
Before, in order to opt-out of Ivy, it was enough to just set `enableIvy` to `false` (since `ngcc` through `ng build` would not affect the original entry-points (but create new ones)).
Now, with `ivy-ngcc` the entry-points will be modified in place, so opting out requires to remove `node_modules/` and re-install. 

Alternatively, in the interest of making it easier to opt in/out of Ivy, we could consider make `ngcc` create new entry-points by default (and allowing people to configure it otherwise)? At least if all the copying does not affect performance too much?

[1]: https://v9.angular.io/guide/ivy

2019-10-04 14:17 UTC, gkalpak commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +  // Read package.json and turn it into a AST.
Super-nit: `a AST` --> `an AST` 😇

2019-10-04 14:17 UTC, gkalpak commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +      insertPropertyInAstObjectInOrder(recorder, scriptsNode, scriptName, script, 4, );
Nit: Is the trailing comma in argument list intentional?

2019-10-04 15:34 UTC, filipesilva commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +      insertPropertyInAstObjectInOrder(recorder, scriptsNode, scriptName, script, 4, );
Nope, unintentional, good catch!

2019-10-04 15:34 UTC, filipesilva commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +  // Read package.json and turn it into a AST.
Done

2019-10-04 15:35 UTC, filipesilva commented
@gkalpak yes, you're right that opting out becomes more complicated now. I'm not sure which of those two options is the preferable one. @vikerman @IgorMinar can you chime in?

2019-10-04 15:45 UTC, mary-poppins commented
You can preview 712e5de at https://pr32999-712e5de.ngbuilds.io/.

2019-10-08 15:45 UTC, IgorMinar approved these changes
The opt-out guide does need to be updated to instruct people to remove the postinstall hook. @filipesilva or @gkalpak could you please send a PR to update it?

@gkalpak why is the entry point duplication/replacement handled differently in standalone ngcc vs the one built into webpack? Was this because we have a custom resolver in webpack that can find the right ivy file even if package.json doesn't point to it, but with the standalone ngcc we can't rely on a presence of a custom resolver so we actually need to modify the entry point?

If that's the case, then restoring node_modules would require that we undo what ngcc did, which is possible, but at that point it might be safer to just remove the postinstall ngcc hook and reinstall node_modules.

2019-10-08 18:33 UTC, gkalpak commented
> The opt-out guide does need to be updated to instruct people to remove the postinstall hook.
> [...] could you please send a PR to update it?

Shouldn't it be done as part of this PR (since this is the PR that introduces the `postinstall` script? 😕 

##
> why is the entry point duplication/replacement handled differently in standalone ngcc vs the one built into webpack? Was this because we have a custom resolver in webpack that can find the right ivy file even if package.json doesn't point to it, but with the standalone ngcc we can't rely on a presence of a custom resolver so we actually need to modify the entry point?

@IgorMinar: More or less, yes :smiley:

##
> If that's the case, then restoring node_modules would require that we undo what ngcc did, which is possible, but at that point it might be safer to just remove the postinstall ngcc hook and reinstall node_modules.

Yes, I think it safer to remove `node_modules/`. Undoing ngcc is theoretically possible (although not currently implemented iirc).

##
@IgorMinar: An alternative would be add a cli option (currently this is only available when calling `ngcc` programmatically in JS) for creating new entry-points (instead of modifying in-place) and pass that option in the postinstall script. Given that this migration will only run for `@angular/cli` users, it is safe to assume that people will also use the `@angular/cli` build infrastructure and thus can take advantage of the new entry-points.

This way, they won't have to re-install when opting out of Ivy. WDYT?

2019-10-08 19:56 UTC, alan-agius4 commented
@filipesilva, we should also make this change in the workspace schematic, so that future generated projects gets this too.

2019-10-08 19:57 UTC, alan-agius4 approved these changes

2019-10-08 20:00 UTC, alan-agius4 commented
Thinking about it, I wonder if with this approach extract-i18n will work, since essentially to extract i18n in Ivy we will need to use VE compiler.

2019-10-08 20:19 UTC, vikerman commented
We should test out extract-i18n - It uses the compiler more to parse the I18N tags out of the templates - And not a full program compile. I don't think it actually needs the dependent library code to do the extraction?

2019-10-09 09:15 UTC, alan-agius4 commented
@filipesilva & @vikerman it seems that extraction still works when using the post-install hook.

2019-10-09 09:19 UTC, alan-agius4 commented
Just though of another problem were a postinstall hook is problematic, Libraries within the workspace will get compiled using VE.

2019-10-09 09:25 UTC, alan-agius4 commented
Another reason why we postinstall hook can be problematic is because libraries will need to get compiled & tested using VE

2019-10-09 10:16 UTC, filipesilva commented
Discussed this change with @alan-agius4 and @petebacondarwin a bit more and there are some additional considerations with regards to using `ivy-ngcc` to transform node_modules entry points in place:
- i18n extraction on the CLI still uses the VE pipeline
- libraries are built with VE for production, and Ivy for development
- libraries can be unit tested with either VE or Ivy
- multi-app/lib workspaces can have individual one compile with either VE or Ivy
- switching browser or server apps between VE and Ivy using the `enableIvy` tsconfig option requires separate entry points in node_modules

@alan-agius4 tested i18n extraction and it seems to work right now.

At its core the problem is that both the runtime and `ngc` are expected to work correctly for Ivy and VE compilations regardless of entry points having been modified via `ivy-ngcc`. The official mechanism that supports this in the CLI is the creation of separate entry points via `ivy-ngcc`. To keep this mechanism consistent and ensure it is tested properly we will need a flag for the separate entry point creation for CLI usage of `ivy-ngcc`. 

It might be possible to make everything work without it. But I don't think these mixed Ivy/VE setups with and without `ivy-ngcc` modified node_modules are tested today, and if we want to ensure it works then we'd have to add a matrix-style test for all these cases. But this seems onerous and error prone.

2019-10-09 15:02 UTC, filipesilva commented on packages/core/schematics/test/postinstall_ngcc_spec.ts
> +    expect(tree.readContent(pkgJsonPath)).toContain(`"${ngccScriptName}": "${ngccScript}"`);
Removed reference back to the migration source, but left a reference to a local variable since the check is repeated a number of times.

2019-10-09 15:07 UTC, filipesilva commented
@jbogarthyde PTAL at the changes in the Ivy opt-out guide in this PR.

2019-10-09 15:17 UTC, mary-poppins commented
You can preview c5817f3 at https://pr32999-c5817f3.ngbuilds.io/.

2019-10-09 16:02 UTC, jbogarthyde requested changes
Following guidelines, we should use the code-example tag for all code snippets, with the header showing what file the snippet is from.
Let's do this in the previous snippets as well, please.

2019-10-10 12:34 UTC, filipesilva commented on aio/content/guide/ivy.md
> +When you opt-out of Ivy remove the `"postinstall": "ivy-ngcc --properties es2015 --create-new-entry-points"` script in `package.json`.
Done, but I remove the `or comment out` part because JSON doesn't have comments. I also used the full json object keys.

2019-10-10 12:41 UTC, petebacondarwin commented on packages/core/schematics/migrations/postinstall-ngcc/README.md
> +Automatically adds a postinstall script to `package.json` to run `ivy-ngcc --properties es2015`.
Perhaps you should add the new extra option `--create-ivy-entry-points`?
Here and below.

2019-10-10 12:42 UTC, petebacondarwin approved these changes

2019-10-10 12:42 UTC, mary-poppins commented
You can preview 1ecaff9 at https://pr32999-1ecaff9.ngbuilds.io/.

2019-10-10 12:48 UTC, filipesilva commented on packages/core/schematics/migrations/postinstall-ngcc/README.md
> +Automatically adds a postinstall script to `package.json` to run `ivy-ngcc --properties es2015`.
Good catch, done!

2019-10-10 12:55 UTC, mary-poppins commented
You can preview 3ffa2aa at https://pr32999-3ffa2aa.ngbuilds.io/.

2019-10-10 13:53 UTC, gkalpak approved these changes

2019-10-10 13:53 UTC, gkalpak commented on aio/content/guide/ivy.md
> +Ivy projects contain a `postinstall` script in the `scripts` section of `package.json` that converts packages in `node_modules` to use Ivy as well.
This might be confusing if the project happens to not have this script (e.g. is on a version that does not have this migration or the script ws manually removeed (for whatever reason)).

Consider changint to something like `Ivy projects usually contain ...`.

2019-10-10 13:53 UTC, gkalpak commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +        tree, 'postinstall', 'ivy-ngcc --properties es2015 --create-ivy-entry-points');
Would it be worth inspecting their `tsconfig.json` target and use an appropriate `--properties` value?

2019-10-10 13:53 UTC, gkalpak commented on packages/core/schematics/test/postinstall_ngcc_spec.ts
> +    expect(tree.readContent(pkgJsonPath)).not.toContain(ngccPostinstall);
Nit: This doesn't really verify that there is no `"postinstall": "ivy-ngcc --properties es2015 --create-ivy-entry-points && ivy-ngcc --something"`

2019-10-10 16:37 UTC, jbogarthyde commented on aio/content/guide/ivy.md
> +```json
Please use the code-example tag with the header identifying the file. I know it's in the text, but this is the doc style we have documented and are trying to make consistent throughout the docs.
Please do this for all the code snippets.

2019-10-10 17:03 UTC, filipesilva commented on aio/content/guide/ivy.md
> +Ivy projects contain a `postinstall` script in the `scripts` section of `package.json` that converts packages in `node_modules` to use Ivy as well.
Done

2019-10-10 17:03 UTC, filipesilva commented on packages/core/schematics/test/postinstall_ngcc_spec.ts
> +    expect(tree.readContent(pkgJsonPath)).not.toContain(ngccPostinstall);
Added

2019-10-10 17:03 UTC, filipesilva commented on aio/content/guide/ivy.md
> +```json
Done

2019-10-10 17:06 UTC, filipesilva commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +        tree, 'postinstall', 'ivy-ngcc --properties es2015 --create-ivy-entry-points');
Maybe... Since the postinstall is for all the workspace, we'd have to check if any individual project tsconfig is using `es5` or `es2015`, and use the union of those. Then we'd have to pass two properties for `ivy-ngcc` to process in some cases. Does it support that?

But even if we do that I don't know if that'll properly catch all Angular packages either, since we're targeting specific props and packages might not use these. 

I'm not sure what the greater plan is here. @IgorMinar can you shed some light?

2019-10-10 17:12 UTC, mary-poppins commented
You can preview 32ac32a at https://pr32999-32ac32a.ngbuilds.io/.

2019-10-10 17:44 UTC, jbogarthyde approved these changes

2019-10-10 17:49 UTC, gkalpak commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +        tree, 'postinstall', 'ivy-ngcc --properties es2015 --create-ivy-entry-points');
Ngcc does support compiling multiple properties. In case some package does not have the specific property, then it will be compiled during `ng build` (which passes a list of format properties to consider).

I think it is fine if the postinstall `ivy-ngcc` run does not handle 100% of the ngcc work, as long as it does cover most of it (so that there will be little work left to be done during the first `ng build`).

I was just worried that if an app targets `es5` it would be a waste to run `ivy-ngcc --properties es2015` in postinstall, because (a) the result wouldn't be used and (b) the real work would still happen during the first `ng build` (making it slow anyway).

##
To be clear, I don't suggest we try to be 100% correct in the postinstall script (e.g. trying to look for all workspace configs and combine them, etc.), but it might be worth catching some easy, common usecases (such as looking at `target` in the main `tsconfig`).

2019-10-10 18:15 UTC, filipesilva commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +        tree, 'postinstall', 'ivy-ngcc --properties es2015 --create-ivy-entry-points');
If the idea is to have a "smart" ngcc postinstall then ngcc should do that detection itself instead of it being determined one time during the update, or not do it at all and let the fallback work correctly.

2019-10-11 19:26 UTC, IgorMinar commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +        tree, 'postinstall', 'ivy-ngcc --properties es2015 --create-ivy-entry-points');
`ngcc` doesn't know anything about the workspace layout, and it should not know how the node_modules it prepares is ultimately used. So ngcc should not attempt any detection.

Checking the root tsconfig.json in the migration seems like a good compromise between doing the wrong thing, and being too smart (and most likely doing the wrong thing).

But here is a bigger problem: 

```
ng new ngcc-test
cd ngcc-test
yarn add ngx-bootstrap
```

```
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ ngx-bootstrap@5.1.2
info All dependencies
└─ ngx-bootstrap@5.1.2
$ ivy-ngcc --properties es2015 --create-ivy-entry-points
ls nError: Unable to process any formats for the following entry-points (tried es2015): 
  - /Users/iminar/Development/tmp/ngcc-test/node_modules/ngx-bootstrap
``` 

because `ngcc` tries to convert only the es2015 entry point, the conversion fails for libraries that don't have es2015 entry point at all. I believe that in this case, ngcc should be smarter, and understand that es2015 is the most desirable format, but if that one is not available, it should use the same fallback logic as our webpack build (which fortunately is not user-configurable, so we don't need to worry about user modifications of the default).

2019-10-11 19:31 UTC, petebacondarwin commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +        tree, 'postinstall', 'ivy-ngcc --properties es2015 --create-ivy-entry-points');
ngcc has another option: `--first-only`, which means that it will only compile the first property from the given list that exists. So we should probably change the migration to something like:

```
ivy-ngcc --properties es2015,es5 --create-ivy-entry-points --first-only
```

and just switch the order of es2015 and es5 as judged by the tsconfig.json file

2019-10-11 20:34 UTC, IgorMinar commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +        tree, 'postinstall', 'ivy-ngcc --properties es2015 --create-ivy-entry-points');
aha! that's much better. @gkalpak suggested:

```
ivy-ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points
```

and drop "es2015" if tsconfig has target set to es5. Could we do that please?

2019-10-11 21:17 UTC, clydin commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +        tree, 'postinstall', 'ivy-ngcc --properties es2015 --create-ivy-entry-points');
After further discussion, we have come to the consensus that the suggested command line above should be used but with no additional logic to determine es5/es2015 support within the migration.
To support additional developer use cases, documentation will be added to explain the post install hook and possibilities for customization based on project needs.

2019-10-14 09:18 UTC, filipesilva commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +        tree, 'postinstall', 'ivy-ngcc --properties es2015 --create-ivy-entry-points');
Added script changes as discussed.

We'll need a place where `ivy-ngcc` is documented separately though. The Ivy opt-out guide doesn't seem to be the right place.

2019-10-14 09:24 UTC, mary-poppins commented
You can preview d6d6e11 at https://pr32999-d6d6e11.ngbuilds.io/.

2019-10-14 11:56 UTC, gkalpak commented
A couple of questions in light of #33140: 

1. Do we need to check the version of `@angular/compiler-cli` and use `ivy-ngcc` or `ngcc` accordingly in the `postinstall` sccript. I assume not, because the migration is versioned along with the Angular packages, so we only need to update the `postinstall` script migration once #33140 is merged. Can someone confirm?

2. Do we need a separate migration chaning `ivy-ngcc` to `ngcc` in npm scripts or is the error message printed by `ivy-ngcc` in #33140 enough for people to fix it themselves? (I assume it is, but again need confirmation :grin:)

3. Do I miss something else that needs to be taken into account?

2019-10-14 14:39 UTC, petebacondarwin commented
1) No
2) No
3) No 

IMHO :-)

2019-10-14 15:53 UTC, filipesilva commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +        tree, 'postinstall', 'ivy-ngcc --properties es2015 --create-ivy-entry-points');
Discussed on Slack, `ngcc --help` should be enough for users that need to change it, together with information on https://github.com/angular/angular/tree/master/packages/compiler-cli.

2019-10-14 17:59 UTC, vikerman approved these changes

2019-10-14 18:03 UTC, mary-poppins commented
You can preview 6907166 at https://pr32999-6907166.ngbuilds.io/.

2019-10-14 18:04 UTC, IgorMinar approved these changes
a few more `ivy-ngcc` leftovers otherwise lgtm

2019-10-14 18:04 UTC, IgorMinar commented on packages/core/schematics/migrations.json
> +      "description": "Adds an ivy-ngcc call as a postinstall hook in package.json",
```suggestion
      "description": "Adds an ngcc call as a postinstall hook in package.json",
```

2019-10-14 18:04 UTC, IgorMinar commented on packages/core/schematics/migrations/postinstall-ngcc/README.md
> +Automatically adds a postinstall script to `package.json` to run `ivy-ngcc --properties es2015 --create-ivy-entry-points`.
```suggestion
Automatically adds a postinstall script to `package.json` to run `ngcc --properties es2015 --create-ivy-entry-points`.
```

2019-10-14 18:04 UTC, IgorMinar commented on packages/core/schematics/migrations/postinstall-ngcc/README.md
> +If a postinstall script is already there and does not call `ivy-ngcc`, the call will be prepended.
```suggestion
If a postinstall script is already there and does not call `ngcc`, the call will be prepended.
```

2019-10-14 18:04 UTC, IgorMinar commented on packages/core/schematics/migrations/postinstall-ngcc/README.md
> +    "postinstall": "ivy-ngcc --properties es2015 --create-ivy-entry-points && do-something"
```suggestion
    "postinstall": "ngcc --properties es2015 --create-ivy-entry-points && do-something"
```

2019-10-14 18:13 UTC, filipesilva commented
@IgorMinar done, thank you for verifying, I missed them.

2019-10-14 18:19 UTC, mary-poppins commented
You can preview c4bd3cc at https://pr32999-c4bd3cc.ngbuilds.io/.

2019-10-14 18:19 UTC, gkalpak approved these changes

2019-10-14 18:19 UTC, gkalpak commented on aio/content/guide/ivy.md
> +<code-example language="json" header="package.json">
This should be `tsconfig.json`, right?

2019-10-14 18:19 UTC, gkalpak commented on aio/content/guide/ivy.md
> +<code-example language="json" header="package.json">
This should be `angular.json`, right?

2019-10-14 18:19 UTC, gkalpak commented on packages/core/schematics/migrations/postinstall-ngcc/README.md
> +Automatically adds a postinstall script to `package.json` to run `ngcc --properties es2015 --create-ivy-entry-points`.
This command is not accurate any more :grin:
Not sure if it has to be anyway; maybe just `ngcc` (or `ngcc ...`) would be enough.

2019-10-14 18:19 UTC, gkalpak commented on packages/core/schematics/migrations/postinstall-ngcc/README.md
> +    "postinstall": "ngcc --properties es2015 --create-ivy-entry-points && do-something"
Not accurate any more :grin:
(Not a big deal though imo. I might still consider `ngcc ... && do-something`.)

2019-10-14 18:19 UTC, gkalpak commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> + * Runs the dynamic queries migration for all TypeScript projects in the current CLI workspace.
No dynamic queries :grin:

2019-10-14 18:35 UTC, filipesilva commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> + * Runs the dynamic queries migration for all TypeScript projects in the current CLI workspace.
Done

2019-10-14 18:35 UTC, filipesilva commented on packages/core/schematics/migrations/postinstall-ngcc/README.md
> +Automatically adds a postinstall script to `package.json` to run `ngcc --properties es2015 --create-ivy-entry-points`.
Done

2019-10-14 18:35 UTC, filipesilva commented on aio/content/guide/ivy.md
> +<code-example language="json" header="package.json">
Done

2019-10-14 18:35 UTC, filipesilva commented on aio/content/guide/ivy.md
> +<code-example language="json" header="package.json">
Done

2019-10-14 18:36 UTC, filipesilva commented on packages/core/schematics/migrations/postinstall-ngcc/README.md
> +    "postinstall": "ngcc --properties es2015 --create-ivy-entry-points && do-something"
Done

2019-10-14 18:42 UTC, mary-poppins commented
You can preview 7a8a258 at https://pr32999-7a8a258.ngbuilds.io/.

2019-10-15 04:41 UTC, trotyl commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +        if (!currentScript.includes('ngcc')) {
Technically there might be indirect invocation like:

```json
{
  "postinstall": "npm run prepare-ivy",
  "prepare-ivy": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"
}
```

I think it might not be necessary to add this if any of the scripts entry contains `ngcc`, even if not invoked in `postinstall` at all, as the user may not want to call it automatically on every install.

2019-10-15 10:12 UTC, mary-poppins commented
You can preview ac6825d at https://pr32999-ac6825d.ngbuilds.io/.

2019-10-15 10:27 UTC, filipesilva commented on packages/core/schematics/migrations/postinstall-ngcc/index.ts
> +        if (!currentScript.includes('ngcc')) {
I worry about false positives when checking all the script contents though. I don't think it's very likely that someone has a script with the string `ngcc` in the middle but if we bail out on a false positive it will be hard for the user to know that it happened. 

On the other hand if the user already knows to use `ngcc` it doesn't sound like a lot of trouble to remove the second invocation. It wouldn't be wrong anyway and the second invocation would see the artifacts on disk and skip them. It would also be very obvious on install that it is running twice.

2019-10-15 16:37 UTC, mhevery approved these changes

2019-10-15 16:41 UTC, mhevery commented
[presubmit](http://test/OCL:274823721:BASE:274823764:1571157616398:39bdb191)
[presubmit ivy](http://test/OCL:274823721:BASE:274824019:1571157695790:4572089c)

2019-10-15 17:15 UTC, IgorMinar approved these changes
merge-assistance: no g3 impact

2019-10-15 17:54 UTC, closed without merging