fix(service-worker): continue serving api requests on cache failure
angular/angular pull request #32996
Opened 2019-10-04 10:37 UTC by apocalyp0sys

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix

## What is the current behavior?
When responses are cached ok during sw initialization, but caching throws an error when handling api response, this response never gets to client. 

Issue Number: #21412 

## What is the new behavior?
Fix response delivery by catching errors and add 2 test cases.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2019-10-08 17:34 UTC, gkalpak requested changes
Thx, @apocalyp0sys! This goes into the right direction. (Also, love the tests 😍)
I have left a couple of suggestions. In addition, could you split up the PR into two commits: a `refactor` one to add the `lru` parameter to `safeCacheResponse` (since that is actually unrelated to the fix) and a `fix` one to actually fix the bug?

2019-10-08 17:34 UTC, gkalpak commented on packages/service-worker/worker/src/data.ts
>      }
I think it makes sense to log a warning here, when updating the cache fails (but not when the request fails). I would change the method body to something like:

```ts
private async safeCacheResponse(
    req: Request, resOrPromise: Response|Promise<Response>, lru: LruList,
    okToCacheOpaque?: boolean): Promise<void> {
  try {
    const res = await resOrPromise;
    try {
      await this.cacheResponse(req, res, lru, okToCacheOpaque);
    } catch (err) {
      // Saving the API response failed. This could be a result of a full storage.
      // Since this data is cached lazily and temporarily, continue serving clients as usual.
      this.debugHandler.log(
          err,
          `DataGroup(${this.config.name}@${this.config.version}).safeCacheResponse(${req.url}, status: ${res.status})`);

      // TODO: Better detect/handle full storage; e.g. using
      // [navigator.storage](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorStorage/storage).
    }
  } catch {
    // TODO: Handle this error somehow?
  }
}
```

This would require passing the [DebugHandler][1] from the `Driver` down to the `DataGroup`s.

[1]: https://github.com/angular/angular/blob/64823f561c2c25f05e9bce04de68374ce997548a/packages/service-worker/worker/src/driver.ts#L108

2019-10-09 17:38 UTC, apocalyp0sys commented
Hi, @gkalpak! Thanks for review.

So, I should open a new `refactor` PR, wait fot it to be merged, and then modify this PR? Or they should be completely independent?

2019-10-14 09:50 UTC, apocalyp0sys commented on packages/service-worker/worker/src/data.ts
>      }
Used this code, thanks!

2019-10-14 12:21 UTC, gkalpak requested changes
Awesome! Thx for making the changes, @apocalyp0sys 👍
I left a couple more minor comments, but otherwise lgtm :tada:

2019-10-14 12:21 UTC, gkalpak commented on packages/service-worker/worker/src/app-version.ts
> +      private debugHandler: DebugHandler) {
Nit: could you move the `debugHandler` argument right after `idle` (to group "utilities/helpers" and "data" separately)?

2019-10-14 12:21 UTC, gkalpak commented on packages/service-worker/worker/src/data.ts
> +      private debugHandler: DebugHandler) {
Nit: could you move the `debugHandler` argument right after `db` (to group "utilities/helpers" and "data" separately)?

2019-10-14 12:21 UTC, gkalpak commented on packages/service-worker/worker/test/happy_spec.ts
> +         });
Could you also add an assertion that an error was logged with `DebugHandler` (here and below)?
(I know we usually don't do that in other tests, but I think it is a good idea, especially here that we basically ignore the error.)

2019-10-14 13:17 UTC, apocalyp0sys commented on packages/service-worker/worker/test/happy_spec.ts
> +         });
Should I create `MockDebugHandler` or spying on existing is ok?

2019-10-14 13:54 UTC, apocalyp0sys commented on packages/service-worker/worker/test/happy_spec.ts
> +         });
Implemented spying on existing `DebugHandler`. Feel free to start another conversation if anything is not ok.

2019-10-14 14:18 UTC, gkalpak commented on packages/service-worker/worker/test/happy_spec.ts
> +         });
Spying on the existing one sounds good. Thx!

2019-10-14 14:28 UTC, gkalpak requested changes
Yay! Almost there 😅

2019-10-14 14:28 UTC, gkalpak commented on packages/service-worker/worker/test/happy_spec.ts
> +import {DebugHandler} from '@angular/service-worker/worker/src/debug';
This should be a relative import, like the rest.
(Although you might not need this at all - see below.)

2019-10-14 14:28 UTC, gkalpak commented on packages/service-worker/worker/test/happy_spec.ts
> +      const cacheErrorMessage = 'Can\'t touch this';
Good thought :smiley: However, I think this is better inlined, since the message itself doesn't have any significance (it could be any message) and it makes the code more readable when inlined (which is far more important that performance or size in testing code).

(If anything, you could define a local var inside each test.)

2019-10-14 14:28 UTC, gkalpak commented on packages/service-worker/worker/test/happy_spec.ts
> +           spyOn(DebugHandler.prototype, 'log');
Could you spy on `driver.debugger` instead to make sure that the same `DebugHandler` is used (and not for example a different instance).

2019-10-14 17:07 UTC, gkalpak approved these changes
LGTM :tada: Thx, @apocalyp0sys! ❤️

2019-10-14 20:22 UTC, mhevery commented
I was unable to merge this to the patch branch as it causes conflicts. Could we create a new PR for patch branch?

2019-10-14 20:23 UTC, closed without merging

2019-10-15 05:05 UTC, apocalyp0sys commented
Should i create a new PR targeting `8.2.x` branch?

2019-10-15 07:05 UTC, gkalpak commented
Yes, please, @apocalyp0sys 🙏