feat(ngcc): add default configuration support
angular/angular pull request #33008
Opened 2019-10-04 18:15 UTC by petebacondarwin

2019-10-04 18:22 UTC, alan-agius4 commented on packages/compiler-cli/ngcc/src/packages/entry_point.ts
> +  } catch (e) {
Nit: `(e)` in redundant in TS

2019-10-04 18:27 UTC, alan-agius4 commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +  getConfig(packagePath: AbsoluteFsPath, version: string|undefined): VersionedPackageConfig {
Question why not optional `:? string` instead of string | undefined`?

2019-10-04 18:31 UTC, alan-agius4 commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +      return null;
Seeing another code within a pr, you seem to be using `undefined` Instead of `null`, what’s preferred?

2019-10-04 21:12 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +  getConfig(packagePath: AbsoluteFsPath, version: string|undefined): VersionedPackageConfig {
I want the option of passing in `undefined` but I wanted to ensure that this was done on purpose and not just by forgetting to add the parameter.

2019-10-04 21:12 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +      return null;
Good point. Let me tidy that up.

2019-10-06 20:24 UTC, JoostK approved these changes

2019-10-08 10:31 UTC, gkalpak requested changes

2019-10-08 10:31 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +}
This function is basically:

```ts
/^(.+?)(?:@([^@]+))?$/.exec(packagePathAndVersion)!.slice(1, 3) as [string, string | undefined]
```

<sub>(I know the function form is more readable and easy to reason about, but I had to say it :grin:)</sub>

2019-10-08 10:31 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +    if (version !== undefined) {
Why not load a package config if `version` is undefined?

2019-10-08 10:31 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +    return configs[0];
I would consider returning the last config (assuming they are sorted in descending version order).
Basically, I would try to return the most recent one.

2019-10-08 17:57 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +export const DEFAULT_NGCC_CONFIG: NgccProjectConfig = {
I don't expect it to get large. From our current analysis there doesn't seem to be much more than a dozen packages that might fit here.

By the way, all our config files are JS based (not JSON) so it would be a bit weird to make this one JSON I think.

My one concern was that this was a bit buried in the code, so perhaps it move out into its own imported file at a push.

2019-10-08 18:02 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +  private defaultConfig: NgccProjectConfig;
In order to do that we must make `baseDir` a private property of the class, which I didn't think added any value.

2019-10-08 18:04 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +    this.defaultConfig = this.processDefaultConfig(baseDir);
I definitely don't expect this to become a problem.
The processing is pretty minimal - not file access just resolving a bunch of the paths in the object.

Also it is quite hard to avoid processing quite soon because you can't even match a package until you have processed the semver range out of the key.

2019-10-08 18:22 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/packages/configuration_spec.ts
>      });
The earlier test that shows that project level overrides package level also shows that entry-points are not merged.
See "should override package level config with project level config per package".

I will add similar tests for the default level - and also add a comment to that earlier test to make it clear.

2019-10-08 18:56 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +    this.defaultConfig = this.processDefaultConfig(baseDir);
If we don't expect this to get large, then there is indeed no point in changing the current implementation :+1:

2019-10-08 18:57 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +export const DEFAULT_NGCC_CONFIG: NgccProjectConfig = {
Ooops, yes, we definitely shouldn't make this one JSON :grin:
If this is not expected to get large, then either way (here or in external file) is fine by me (both have pros and cons, so 🤷‍♂).

2019-10-08 19:23 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +    if (version !== undefined) {
Hmm good question...
The only way you end up with `undefined` for `version` is if we are unable to actually load or parse the  `package.json` of the package in question. So I kind of assumed that this would mean that the package is totally broken (or does not exist). In which case there was no point in trying to look in the package for a config.

But now you mention it, there is probably no harm in trying to load such an ngcc config file, it is just that we won't be able to know what version the package is (since that info is only available in the package.json). So we could default it to `*` version.

What do you think @gkalpak ?

2019-10-08 19:24 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +}
🤓

2019-10-08 19:24 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +    return configs[0];
I don't think we can assume that they are in any particular order... with regards to semver.

2019-10-08 19:29 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +    if (version !== undefined) {
Hm...I thought `undefined` was another way of saying "I don't care about the version" (i.e. equivalent to `'*'`). I think it is reasonable to have it behave like that (i.e. try to get a package-level config - even if that is unlikely to happen when `version` is undefined).

It might also be a good idea to document why/what for `version: undefined` is expected to be used.

2019-10-08 19:29 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +    return configs[0];
We could order the default config in a particular way but the order of project configs provided by the developer are unconstrained. With that in mind I went with the simplest code here.

That being said, I think that `version: undefined` is a rare corner case where we are importing from a package that has a broken package.json  - so we were not able to read in the version.  So I think this is not going to make much difference in practice.

2019-10-08 19:33 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/entry_point.ts
>    if (entryPointConfig === undefined && !fs.exists(packageJsonPath)) {
We can't do 

```ts
  if (!fs.exists(packageJsonPath)) return null;
```

at the start because if the entryPoint has a configuration then we do not want return `null` - even if the `packageJsonPath` does not exist. (I think this is the case for deep imports).

2019-10-08 19:49 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/entry_point.ts
>    if (entryPointConfig === undefined && !fs.exists(packageJsonPath)) {
Ooops, you are right. I (incorrectly) thought that a non-existing `packageJsonPath` automatically meant no `entryPointConfig`, which is not the case.

2019-10-08 20:00 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +    if (version !== undefined) {
Good idea!

2019-10-08 20:18 UTC, alxhub approved these changes

2019-10-08 20:18 UTC, alxhub commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +      VersionedPackageConfig|undefined {
Why `undefined` and not `null`?

2019-10-08 20:26 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +      VersionedPackageConfig|undefined {
So the implication is that `undefined` indicates that no such config was found. Not that anything is wrong as such.

2019-10-08 21:00 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +      VersionedPackageConfig|undefined {
I changed them to `null`s

2019-10-08 21:01 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +    if (version !== undefined) {
Added documentation and removed the guard on trying to use a package level config

2019-10-08 21:17 UTC, gkalpak approved these changes

2019-10-10 21:00 UTC, closed without merging