fix(upgrade): remove unused version export
angular/angular pull request #33006
Opened 2019-10-04 17:44 UTC by evmar

In some module systems (Closure), it's illegal to mutate an export.
This mutated export isn't used anyway, so we can just remove it.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

(appears unused, not public API)

## Other information

2019-10-05 15:12 UTC, gkalpak requested changes
The idea was to have `angular1.ts` a public API (exports) that look identical to the `angular` global. But given that `angular1` is only used internally, this is fine, I guess.

You still need to fix some failing `ngUpgrade` tests (don't worry about the failing `integration` tests - they look like flakes).

2019-10-05 16:38 UTC, evmar commented
The integration test failures are stuff like
ERROR: no such package '@io_bazel_rules_sass//sass': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_sass/archive/86ca977cf2a8ed481859f83a286e164d07335116.zip] to /home/circleci/.cache/bazel/_bazel_circleci/8b51d73b510696780d337ceaa0e89195/external/io_bazel_rules_sass/86ca977cf2a8ed481859f83a286e164d07335116.zip: connect timed out

I'm not sure how to resolve that. 
Is there something I can do to cause it to try again?

2019-10-06 10:14 UTC, gkalpak commented
As mentioned in https://github.com/angular/angular/pull/33006#pullrequestreview-297795473, _"don't worry about the failing integration tests - they look like flakes"_ :smiley:

2019-10-10 21:12 UTC, mhevery approved these changes

2019-10-10 21:13 UTC, mhevery commented
This change breaks some tests, could you look into it?

2019-10-15 18:42 UTC, evmar commented
Trying again in https://github.com/angular/angular/pull/33180

2019-10-15 18:42 UTC, closed without merging