feat(compiler-cli): resolve type of exported *ngIf variable.
angular/angular pull request #33016
Opened 2019-10-05 13:33 UTC by andrius-pra

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Angular compiler does not resolve the type of exported variable from *ngIf directive. It always returns `any` type. So language service can't provide completions for type members.

Issue Number: angular/vscode-ng-language-service#255

## What is the new behavior?
Compiler will try resolve type of exported variable and will use this type for type-checking.  Angular language service will use this type for completions, go to definition and quick info functionality. Also language service will provide more accurate diagnostic errors during development.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-10-07 23:08 UTC, ayazhafiz requested changes
Can you add tests that check that this change correctly determines the type of exported variable?

2019-10-08 21:14 UTC, ayazhafiz requested changes
Sorry that I wasn't more clear earlier @andrius-pra; what I mean is, can we also add tests that `bindingType` returned in the compiler code is what we expect it to be?

2019-10-09 20:31 UTC, andrius-pra commented
@ayazhafiz, I'm not sure where I should add this test. Tests of compiler-cli doesn't check the type of scoped variables. It only verify that compiler will produce specific diagnostic message. Do I need to introduce a new type of tests in compiler-cli package that will check result of [getExpressionScope](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/diagnostics/expression_diagnostics.ts#L171) or [getVarDeclarations](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/diagnostics/expression_diagnostics.ts#L93)?

2019-10-10 18:38 UTC, ayazhafiz commented
I'm not sure. Perhaps it is best to defer to the compiler team to ask what they would like to do. ping @angular/fw-compiler

2019-10-10 18:39 UTC, ayazhafiz approved these changes
LGTM for Language Service

2019-10-10 18:39 UTC, ayazhafiz commented on packages/compiler-cli/src/diagnostics/expression_diagnostics.ts
> +      templateElement.directives.find(d => identifierName(d.directive.type) == 'NgIf');
```suggestion
      templateElement.directives.find(d => identifierName(d.directive.type) === 'NgIf');
```

2019-10-10 18:39 UTC, ayazhafiz commented on packages/compiler-cli/src/diagnostics/expression_diagnostics.ts
> +    const ngIfBinding = ngIfDirective.inputs.find(i => i.directiveName == 'ngIf');
```suggestion
    const ngIfBinding = ngIfDirective.inputs.find(i => i.directiveName === 'ngIf');
```

2019-10-10 21:44 UTC, kyliau requested changes

2019-10-10 21:44 UTC, kyliau commented on packages/compiler-cli/test/diagnostics/expression_diagnostics_spec.ts
> +  it('should reject misspelled field an async *ngIf', () => reject(
typo, should be `in`?

2019-10-10 21:44 UTC, kyliau commented on packages/compiler-cli/test/diagnostics/expression_diagnostics_spec.ts
> +                                                          'Identifier \'nume\' is not defined'));
Please fix formatting.

2019-10-11 19:29 UTC, andrius-pra commented on packages/compiler-cli/test/diagnostics/expression_diagnostics_spec.ts
> +                                                          'Identifier \'nume\' is not defined'));
I can't. clang-format always restores my formatting.

2019-10-12 00:12 UTC, kyliau approved these changes

2019-10-12 07:07 UTC, petebacondarwin approved these changes
It would be really helpful for reference to include more information in the commit message, explaining what this commit is doing an why it is needed.
Perhaps similar to what has been written in the description PR?

2019-10-13 20:59 UTC, andrius-pra commented
I have updated commit message.

2019-10-14 19:21 UTC, IgorMinar approved these changes

2019-10-14 19:21 UTC, IgorMinar commented
thank you @andrius-pra!

2019-10-14 20:24 UTC, closed without merging