docs: clarify http header api doc
angular/angular pull request #33038
Opened 2019-10-08 16:54 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
HTTP Header API doc does not make it obvious that changes are made to a clone of the original instance.

Issue Number: https://github.com/angular/angular/issues/33033

## What is the new behavior?
Clarify API docs 
https://angular.io/api/common/http/HttpHeaders

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-10-08 17:01 UTC, mary-poppins commented
You can preview 9a40be3 at https://pr33038-9a40be3.ngbuilds.io/.

2019-10-08 21:10 UTC, mary-poppins commented
You can preview 1c96884 at https://pr33038-1c96884.ngbuilds.io/.

2019-10-09 16:26 UTC, mary-poppins commented
You can preview 1d8ccb7 at https://pr33038-1d8ccb7.ngbuilds.io/.

2019-10-10 16:39 UTC, mary-poppins commented
You can preview b27c915 at https://pr33038-b27c915.ngbuilds.io/.

2019-10-10 17:27 UTC, JoostK requested changes
Thanks for taking this on! I left some comments inline.

Also, could the descriptions be updated to make use of the 100 chars in width? It feels strange that they are kept so short in the code.

2019-10-10 17:27 UTC, JoostK commented on packages/common/http/src/headers.ts
> +   * Checks for existence of a given key in the header.
I think the previous terminology is more correct. The new descriptions makes it feel like the full HTTP block of headers is just referred to as "header", whereas a "header" typically only refers to a single "header" line:

For instance, the HTTP snippet:

```http
POST /api/v1/users
Host: https://example.com
Content-Type: application/json
Accept: application/json
```

has three headers, named `Host`, `Content-Type` and `Accept`. I think the term "name" is more appropriate to use compared to "key", as a key implies that its occurrence is unique. This is not a necessity with HTTP, where the following is allowed:

```http
POST /api/v1/users
Host: https://example.com
Content-Type: application/json
Accept: application/json
Accept: text/plain
```

This HTTP request will be interpreted to have its `Accept` header set to `application/json, text/plain`.

2019-10-10 17:27 UTC, JoostK commented on packages/common/http/src/headers.ts
> +   * Deletes header values for a given key name.
Could we make it explicit that the original object is not modified and that the change can only be observed in the returned object? Having it only mentioned in the `@returns` is not so visible, especially on AIO where the main description is at the top of the method's card, and the return type description is all the way at the bottom:

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/123679/66591211-b838e600-eb92-11e9-907d-ab9353ce5762.png">

When reading just the method description (which is typically the case!), it is very natural to assume that the original object is updated.

This holds true for all methods that return a cloned object.

2019-10-10 17:27 UTC, JoostK commented on packages/common/http/src/headers.ts
> + * Modifying methods return a cloned instance with the change.
Could we add somehow that the original object is not changed?

```suggestion
 * Modifying methods return a cloned instance with the change, the original object is never changed.
```

2019-10-10 17:27 UTC, JoostK commented on packages/common/http/src/headers.ts
> + * Instances are immutable with lazy parsing.
To me this (as well as the original) sounds very abstract. To me, the concept of "parsing" is strange in the context of keeping track of a collection of headers. I would prefer if the mentioning of the object being immutable is fused with the subsequent sentence a bit more; i.e. what does it mean for this object to be immutable.

2019-10-10 17:51 UTC, jbogarthyde commented on packages/common/http/src/headers.ts
> + * Instances are immutable with lazy parsing.
Done. (I didn't understand that sentence at all, so I left it unchanged. Can suggest a clearer way to say it, or can I just take it out?)

2019-10-10 17:55 UTC, jbogarthyde commented on packages/common/http/src/headers.ts
> +   * Checks for existence of a given key in the header.
Thanks for the clarification - -removing the "key" concept.

2019-10-10 18:06 UTC, mary-poppins commented
You can preview 9394a33 at https://pr33038-9394a33.ngbuilds.io/.

2019-10-10 19:46 UTC, JoostK commented on packages/common/http/src/headers.ts
> + * Instances are immutable with lazy parsing.
I would be fine with taking the statement about "lazy parsing" out :+1: It's an implementation detail that does not affect the observable behavior, so my vote would be to remove it.

2019-10-10 19:57 UTC, JoostK commented on packages/common/http/src/headers.ts
> +   * values for a header and returns a clone of the original headers instance.
This sentence allows for the interpretation of the appending to also occur in the original instance (before the cloning). I prefer the way the `set` method reads "in a clone of the original instance".

Also, could the first line here span the available width and any overflow follow on the second line? The current spacing is quite awkward to read.

2019-10-10 19:57 UTC, JoostK commented on packages/common/http/src/headers.ts
> +   * its value is replaced with the given value in the returned object.
nit: could the spacing here also be cleaned up a bit?

2019-10-10 19:57 UTC, JoostK commented on packages/common/http/src/headers.ts
> +   * Retrieves a list of header values for a given name.
Could this be made consistent with `has` and `get`, which both use "for a given header". I think I like that better 😄

2019-10-10 19:57 UTC, JoostK commented on packages/common/http/src/headers.ts
> +   * @param name The header name to query.
I prefer the original 😇

2019-10-10 19:57 UTC, JoostK commented on packages/common/http/src/headers.ts
> +   * @param name The name to check for existence.
I prefer the original :)

2019-10-10 20:49 UTC, mary-poppins commented
You can preview 0f914eb at https://pr33038-0f914eb.ngbuilds.io/.

2019-10-14 16:18 UTC, mary-poppins commented
You can preview da3e501 at https://pr33038-da3e501.ngbuilds.io/.

2019-10-14 17:15 UTC, JoostK approved these changes

2019-10-14 17:17 UTC, jbogarthyde commented
Caretaker: Docs only

2019-10-14 17:23 UTC, alxhub approved these changes

2019-10-14 23:45 UTC, closed without merging