build: create tdd performance test script
angular/angular pull request #33061
Opened 2019-10-09 16:54 UTC by josephperrott

This script automates the steps from Pawel "TDD workflow productivity" doc for us to better work to track the our TDD turnaround time.

2019-10-14 09:02 UTC, filipesilva commented on scripts/local-dev/test-tdd.sh
> +#yarn -s bazel clean --expunge > /dev/null 2>&1
Should this be commented out?

2020-01-28 04:48 UTC, IgorMinar requested changes
could we use shelljs for this script rather than bash? I've been slowly switching over most of our bash scripts to shelljs because it's so much easier to read and maintain. It's also windows friendly.

2020-01-28 04:48 UTC, IgorMinar commented on scripts/local-dev/test-tdd.sh
> +echo >> ../../packages/core/test/acceptance/attributes_spec.ts
will the new line be preserved in the emitted js/d.ts files? I would feel more confident in this if we appended `console.log('hello")` to the file.

2020-01-28 04:48 UTC, IgorMinar commented on scripts/local-dev/test-tdd.sh
> +test_command="yarn -s bazel test ${test_package} --define=compile=aot > /dev/null 2>&1"
```suggestion
test_command="yarn -s bazel test ${test_package} --config=ivy > /dev/null 2>&1"
```

2020-01-28 04:48 UTC, IgorMinar commented on scripts/local-dev/test-tdd.sh
> +# Short cuts to set output as bold and normal
```suggestion
# Shortcuts to set output as bold and normal
```

2020-01-28 15:02 UTC, josephperrott commented on scripts/local-dev/test-tdd.sh
> +echo >> ../../packages/core/test/acceptance/attributes_spec.ts
The new line is actually preserved, but its much more obvious with the `console.log`

2020-03-10 22:19 UTC, closed without merging