View ref
angular/angular pull request #33074
Opened 2019-10-09 23:58 UTC by mhevery

2019-10-10 23:43 UTC, atscott commented
@googlebot I consent

2019-10-11 16:55 UTC, atscott commented
[Presubmit](http://test/OCL:274192075:BASE:274192103:1570812747020:4d131219)
[Ivy Presubmit](http://test/OCL:274192075:BASE:274192282:1570812812940:750944e1)
[Global presubmit from version without the change to markViewDirty](https://test.corp.google.com/OCL:273876804:BASE:273877032:1570676990329:7f2ce41) - fixed 73 targets. Should still rerun for current PR state

2019-10-11 17:06 UTC, atscott commented
This is related to the Ivy breaking change "Change Detection Follows Insertion Tree, Not Declaration Tree". In order to update the template at the insertion tree correct, the view ref needs to mark the embedded view as dirty instead of the declaration view. This allows users to use directives that inject `ChangeDetectorRef` inside an `ng-template` that is inserted in another context and correctly mark the insertion tree as dirty.

2019-10-15 16:37 UTC, crisbeto approved these changes
LGTM

2019-10-15 16:37 UTC, crisbeto commented on packages/core/src/render3/view_engine_compatibility.ts
> +  const isComponentView = isComponentHost(tNode) && !isPipe;
Maybe we can flip this around to `!isPipe && isComponentHost(tNode)` since the `isPipe` check should be cheaper.

2019-10-15 16:57 UTC, atscott commented
@googlebot I consent.

2019-10-16 04:16 UTC, atscott commented
[Global Ivy Presubmit](https://test.corp.google.com/OCL:274952832:BASE:274952933:1571199367681:9e23a5b5)

2019-10-16 22:34 UTC, kara requested changes

2019-10-16 22:34 UTC, kara commented on packages/core/src/render3/view_engine_compatibility.ts
> +    // We need to locate the containing LVIew (in case where the `lView` is emended view)
```suggestion
    // We need to locate the containing LView (in case where the `lView` is amended view)
```

2019-10-16 22:34 UTC, kara commented on packages/core/src/render3/view_engine_compatibility.ts
> +        const viewRef = new ViewRef<T>(lView, lView);
Here we're passing an embedded view into the `componentLView` slot. Seems like we should either find the real component host view or pass in `null`? Although if we pass in `null`, this will break some of the assumptions in `ViewRef` that the component view is always defined, so we'd need to fall back to the embedded view.

2019-10-16 23:29 UTC, kara commented on packages/core/src/render3/view_engine_compatibility.ts
> +    // We need to locate the containing LView (in case where the `lView` is emended view)
```suggestion
    // We need to locate the containing LView (in case where the `lView` is amended view)
```

2019-10-17 00:48 UTC, kara requested changes

2019-10-17 00:48 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> +      markViewDirty(declParent);
This change doesn't seem to be related to the original test case (and in fact, the test passes without this change). If I understand correctly, the problem was that we were passing the wrong starting view to `markViewDirty` - the `Declaration` view instead of the embedded view. Because of this, we would walk up the insertion tree starting at the `Declaration` view, so we never reached the `Insertion` component to check it. 

In this PR, that problem has been corrected by passing `this._requestingLView` (the embedded view itself) to `markViewDirty`. The embedded view would then walk up to its insertion view - `Insertion` - and cause it to be properly checked.

The diff here implies that we want to start marking the declaration tree dirty in addition to the insertion tree, but it's not clear why that's necessary. It seems like we are missing a test case or two.

2019-10-17 12:10 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/change_detection_spec.ts
> +import {BehaviorSubject, Observable} from 'rxjs';
`Observable` import doesn't seem to be used?

2019-10-17 12:14 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/change_detection_spec.ts
> +      it('should check insertion context with async pipe', () => {
context -> view? More generally, the way I understand the test is that we want to assure that the embedded _view_ will be checked when a said embedded view is inserted to a view different from its declaration view. How about: `async pipe should trigger CD for embedded views where the declaration and insertion views are different`?  (mouth-full but precise...)

2019-10-17 12:15 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/change_detection_spec.ts
> +        // insertion and declaration contexts.
context -> view? See https://github.com/angular/angular/pull/33074/files#r335967884

2019-10-17 12:41 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +      markViewDirty(declParent);
Agree with @kara here - looking at the case from the test the solution should be: mark for check the component view that contains a container holding an embedded view. In this particular case the only thing that should matter is the insertion point - we should start with the embedded view, get to the insertion container, go up to the component view and mark it for check.

Could we simplify this PR to have just a fix for the case exposed in the test? If there are more case (ones involving declaration view) we should have a separate test + fix for it (another commit in this PR or another PR)

2019-10-17 12:58 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +      markViewDirty(declParent);
So the way I understand the root of the problem now is that we are always injecting a component view when a pipe asks for a change detector here: https://github.com/angular/angular/pull/33074/files#diff-f0a30efe7a958f4c73731e33aa32ebfaR388

Maybe we should have a change detector ref point to a view where we ask for it (an embedded view in this case) and the mark for check should traverse up, starting from this embedded view?

2019-10-17 13:32 UTC, atscott commented on packages/core/test/acceptance/change_detection_spec.ts
> +      it('should check insertion context with async pipe', () => {
Yea, that sounds good.

2019-10-17 13:34 UTC, atscott commented on packages/core/src/render3/instructions/shared.ts
> +      markViewDirty(declParent);
Yes, there is a missing test for this change. I don't completely understand why it's necessary. The problem I had identified was with async pipe where insertion context is different than declaration context and got Misko's help to solve that. He also wanted this change but I don't completely understand which cases make it necessary (so I couldn't write a test) or if it should be in a separate PR. @mhevery - care to chime in here?

2019-10-17 16:42 UTC, atscott commented on packages/core/src/render3/instructions/shared.ts
> +      markViewDirty(declParent);
Discussed in sync and we decided this change should move to a different PR

2019-10-18 09:39 UTC, pkozlowski-opensource commented on packages/core/src/render3/view_ref.ts
> +      public _componentLView: LView,
I think that the `_componentLView` as a name is misleading here. Let's look at 3 usage scenarios we've got:
* `ChangeDetectorRef` - in this particular case  `_componentLView` makes sense;
* `ViewRef` created for a dynamic component -   `_componentLView` still makes sense;
* `ViewRef` created for an embedded view -  `_componentLView` is misleading here.

How about we leave it as `_lView` and change the other view from `_requestingLView` to something clearly indicating that we are dealing with the `ChangeDetectorRef` case here? Maybe `_cdRefInjectingView`?

2019-10-18 09:41 UTC, pkozlowski-opensource commented on packages/core/src/render3/view_ref.ts
> +      private _requestingLView: LView) {}
I think that we should make this argument optional and only pass it for cases where a `ViewRef` is created to inject a ChangeDetectorRef. This would than just require one change to the `markForCheck()`: ` markViewDirty(this._cdRefInjectingView || this._lView);`

2019-10-18 09:57 UTC, pkozlowski-opensource requested changes
@atscott ok, I think I've got a much better understanding of the problem right now. There are great moves in this PR (thnx so much for cleaning up `ViewRef` constructor and removing context and component index fields!).

Still I've left 2 comments regarding names and the (optional) second argument. I believe that we can have a slightly smaller / clearer fix, sth along the lines of https://github.com/pkozlowski-opensource/angular/commit/1817d47536d3b04bfbf38699be37e82e92b00fe9

WDYF?

2019-10-18 16:29 UTC, atscott commented on packages/core/src/render3/view_ref.ts
> +      public _componentLView: LView,
Yea, I like this option along with making _cdRefInjectingView optional. The only thing I was hesitant about for making it just `_lView` again was that it again wasn't describing the different types of `LView` it could be. I added doc comments for the 3 usage scenarios you listed so I feel better about this now.

2019-10-18 16:31 UTC, atscott commented on packages/core/src/render3/view_engine_compatibility.ts
> +        const viewRef = new ViewRef<T>(lView, lView);
Resolved by making it optional? I'm unfamiliar with the convention in the codebase though. Is null preferred over optional in all cases?

2019-10-20 14:05 UTC, pkozlowski-opensource commented on packages/core/src/render3/view_engine_compatibility.ts
> +    // We need to locate the containing LView (in case where the `lView` is amended view)
amended -> embedded

2019-10-20 14:05 UTC, pkozlowski-opensource approved these changes
LGTM, thnx!

2019-10-21 22:22 UTC, kara approved these changes
LGTM. We can refactor `ViewRef` more in a follow-up PR.

2019-10-22 17:28 UTC, matsko commented
Presubmit = http://test/OCL:276092077:BASE:276092123:1571765025290:98a79ab5

Ivy Presubmit = http://test/OCL:276092077:BASE:276092773:1571765214133:1601d9f

2019-10-22 19:00 UTC, closed without merging