docs: clarifications in Hosting on Firebase
angular/angular pull request #33089
Opened 2019-10-10 22:35 UTC by DavSanchez

Hi guys!

I have added some clarifications on the `firebase init` process and a small correction on the `firebase deploy` line, at the Deployment section of the Getting Started docs.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-10-10 22:37 UTC, DavSanchez commented
@googlebot I signed it!

2019-10-15 19:55 UTC, kapunahelewong commented
Thanks for this, @DavSanchez! I've been working through these myself and found that that part definitely needed some more detail. Could you rebase and amend your commit message to be:

> docs: clarify steps in Hosting on Firebase

In case you'd like them, I like to share my own workflow with others. Here are [my notes on rebasing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) and [my notes on amending commit messages](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit).

Please feel free to tag me with any questions and when you're ready. Thank you!

2019-10-15 20:17 UTC, DavSanchez commented
Hi @kapunahelewong, thanks for the links! I'll do the rebase and amend and come back to you with any questions I might have.

2019-10-16 04:55 UTC, DavSanchez commented
Alright! I think I did it correctly, although I ended up amending first and rebasing after, hence the two commits... is that a problem?

2019-10-16 12:27 UTC, kapunahelewong requested changes
It looks like you did a perfect job with the rebase/squashing, @DavSanchez. 🌟I just realized though that I missed one little thing yesterday. 

Regarding rebasing before or after squashing, it doesn't really matter if the change is small. Sometimes, though, with a PR with lots of changes, if you don't squash first it can get a little repetitive because the rebase goes commit by commit. So first git will rebase your first commit, then the second and so on. So, if you have any conflicts, it's possible to have some of the same ones over and over again. I found this out with a branch I had with about 10 commits once!

Anyway, when you're ready (sorry for my oversight), will you tag me again? I'll keep an eye out for you. 🙂

2019-10-16 12:27 UTC, kapunahelewong commented on aio/content/start/deployment.md
> +1. Follow the prompts to select the `Firebase` project you are creating for hosting
Oops, I missed this before. Can you put a period at the end of the sentence?
```suggestion
1. Follow the prompts to select the `Firebase` project you are creating for hosting.
```

2019-10-16 22:44 UTC, DavSanchez commented on aio/content/start/deployment.md
> +1. Follow the prompts to select the `Firebase` project you are creating for hosting
Yes! Already committed @kapunahelewong . If you need anything else please don't hesitate to let me know!

2019-10-18 20:57 UTC, kapunahelewong commented
Ah, I haven't experimented with using the UI for committing changes yet. Yes, you should be able to fix it with an amend, but really, since you want to only have 1 commit in your PR, if you squash, you can just fixup that last one and be in good shape. Here's the [squashing section of my notes](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash). Let me know if you have any questions. :)

2019-10-19 04:02 UTC, DavSanchez commented
Alright @kapunahelewong! I think it's already done. If you need anything else please let me know!

2019-10-21 19:59 UTC, kapunahelewong approved these changes
LGTM! Thank you very much, @DavSanchez!

Caretaker, this is a docs only change. Thank you!

2019-10-21 20:07 UTC, closed without merging