docs: add localize migration doc
angular/angular pull request #33086
Opened 2019-10-10 20:17 UTC by kapunahelewong

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Adds migration documentation for `$localize`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-10-10 20:25 UTC, mary-poppins commented
You can preview 09875b6 at https://pr33086-09875b6.ngbuilds.io/.

2019-10-15 21:42 UTC, jelbourn commented on aio/content/guide/deprecations.md
> +### Migratin i18n `$localize` global import
```suggestion
### Migrating the `$localize` global import
```

2019-10-15 21:42 UTC, jelbourn commented on aio/content/guide/migration-localize.md
> +
Proposed revision for this section
````markdown
Angular compiles HTML templates into generated TypeScript code. Prior to Angular v9,
Angular's internationalization (i18n) system inlined translated messages into the compiled
output as part of this template compilation. This approach required running the template
compiler once per target locale, often leading to slow production build times.

The Angular Ivy i18n system instead performs template compilation exactly once. Then,
as a _post-compilation_ step, Angular inlines messages for each target locale. By separating
this message inlining from template compilation, the process can run much faster.

However, in order for this new approach to work, each application
must now import new code from the `@angular/localize` package. If
this import is missing, you will see an error message like this:

```
Error: The global function `$localize` is missing.
Please add `import '@angular/localize/init';` to your polyfills.ts file.
```

This schematic automatically adds the `@angular/localize` import for you
if your app uses Angular's i18n APIs.
````

2019-10-15 21:42 UTC, jelbourn commented on aio/content/guide/migration-localize.md
> +You don't need to update your libraries because libraries are still shipping with View Engine.
I feel like this section needs more elaboration, but I don't know enough to propose anything

2019-10-15 21:42 UTC, jelbourn commented on aio/content/guide/migration-localize.md
> +`@angular/localize` is a new package that works with Ivy. The `$localize` function looks up the translation in your translation file and inlines translated strings.
I think it would be valuable to explain here that this new code doesn't add any run-time overhead (I believe, Kara can confirm).

2019-10-16 12:44 UTC, kapunahelewong commented on aio/content/guide/migration-localize.md
> +You don't need to update your libraries because libraries are still shipping with View Engine.
Maybe @kara has some thoughts?

2019-10-16 12:45 UTC, kapunahelewong commented on aio/content/guide/migration-localize.md
> +
Beautiful, thank you! I didn't know how to articulate some of what I wanted to say and this really helps.

2019-10-16 12:46 UTC, kapunahelewong commented on aio/content/guide/migration-localize.md
> +`@angular/localize` is a new package that works with Ivy. The `$localize` function looks up the translation in your translation file and inlines translated strings.
Added and leaving for @Kara to confirm.

2019-10-16 12:57 UTC, kapunahelewong commented on aio/content/guide/migration-localize.md
> +You don't need to update your libraries because libraries are still shipping with View Engine.
Maybe @Kara has some thoughts?

2019-10-16 13:03 UTC, mary-poppins commented
You can preview 184ecec at https://pr33086-184ecec.ngbuilds.io/.

2019-10-17 23:54 UTC, kara requested changes

2019-10-17 23:54 UTC, kara commented on aio/content/guide/migration-localize.md
> +## What does this schematic do?
This should always be the first question. Move up to the top?

2019-10-17 23:54 UTC, kara commented on aio/content/guide/migration-localize.md
> +If you're using i18n, this schematic imports `@angular/localize` to `polyfills.ts` and adds it to `package.json`.
Let's add a diff for package.json?

```suggestion
If you're using i18n, this schematic adds an import statement for `@angular/localize` to `polyfills.ts`. It will look something like this:

<example diff for polyfills.ts>

It also lists `@angular/localize` as a dependency in your app's `package.json` to ensure the import is found.

<example diff for package.json>
```

2019-10-17 23:54 UTC, kara commented on aio/content/guide/migration-localize.md
> +`@angular/localize` is a new package that works with Ivy that doesn't add any run-time overhead. The `$localize` function looks up the translation in your translation file and inlines translated stri
For v9, we are just doing compile-time inlining, so the $localize function isn't actually being called. The i18n inliner looks for`$localize` function calls and replaces the strings inside them with the proper translations (at build-time).  We just need the `$localize` function to be defined globally so the app will build (because the inlining happens after build).

When we do actual runtime i18n (probably v10), $localize will be a real runtime function that loads translations on the fly, but not yet. You can see more info here: https://github.com/angular/angular/blob/master/packages/localize/init/index.ts#L92

```suggestion
`@angular/localize` is a new package that works with Ivy that doesn't add any run-time overhead. It simply adds a `$localize` symbol to the global context, which allows i18n to work properly.
```

2019-10-17 23:54 UTC, kara commented on aio/content/guide/migration-localize.md
> +Angular compiles HTML templates into generated TypeScript code. Prior to Angular version 9,
```suggestion
Prior to Angular version 9,
```

2019-10-17 23:54 UTC, kara commented on aio/content/guide/migration-localize.md
> +output as part of this template compilation. This approach required running the template
```suggestion
output as part of the CLI build process. This approach required running the template
```

2019-10-17 23:54 UTC, kara commented on aio/content/guide/migration-localize.md
> +You don't need to update your libraries because libraries are still shipping with View Engine.
I think we can actually drop this section since 99% of libraries don't use i18n

2019-10-17 23:59 UTC, kara commented
Adding @petebacondarwin as a reviewer because he will probably have some insights

2019-10-18 00:02 UTC, kara commented on aio/content/guide/migration-localize.md
> +If you're using i18n, this schematic imports `@angular/localize` to `polyfills.ts` and adds it to `package.json`.
I think we're also missing the `no-import-side-effect` change in tslint.json

2019-10-18 06:48 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +If you're using i18n, this schematic imports `@angular/localize` to `polyfills.ts` and adds it to `package.json`.
We didn't add the tslint change in the end because the standard CLI project does not include the rule (`no-import-side-effect`) that needs to be overridden.

2019-10-18 06:50 UTC, petebacondarwin commented on aio/content/guide/deprecations.md
> +### Migrating for the `$localize` global import
Or perhaps...

```suggestion
### Migrating to the new `$localize` i18n support
```

2019-10-18 06:52 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +output as part of this template compilation. This approach required running the template
The new approach in v9 can also inline the translated messages as part of the CLI build process. So I think this needs to be more nuanced than that.

2019-10-18 06:52 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +output as part of this template compilation. This approach required running the template
I think that talking about the Angular compiler here is correct. The CLI is a layer above this.

2019-10-18 14:13 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +The Angular Ivy i18n system instead performs template compilation exactly once. Then,
I would say something along the lines of:

>>>
In the new i18n system, the Angular compiler tags i18n messages in the compiled code with a global `$localize` handler. The inlining of translations then occurs as a post-compilation step for each locale. Because the application does not need to be built again for each locale, this makes the process much faster.

2019-10-18 14:14 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +The Angular Ivy i18n system instead performs template compilation exactly once. Then,
By the way, should we be avoiding the use of the word `ivy` in these docs?

2019-10-18 14:19 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +This schematic automatically adds the `@angular/localize` import for you
```suggestion
This schematic automatically adds the `@angular/localize/init` import for you
```

2019-10-18 14:19 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +this import is missing, you will see an error message like this:
And then here you could say:

>>>
The post-compilation inlining step is optional - for example during development or if the translations will be inlined at runtime. Therefore this global `$localize` must be available on the global scope at runtime.
To make `$localize` available on the global scope, each application must now import the `@angular/localize/init` module. This has the side-effect of attaching a minimal implementation of `$localize` to the global scope.

If this import is missing, you will see an error message like this:

2019-10-18 14:38 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +If you're using i18n, this schematic imports `@angular/localize` to `polyfills.ts` and adds it to `package.json`.
But if one has it enabled manually then perhaps it is useful to mention it here?

2019-10-18 14:40 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +`@angular/localize` is a new package that works with Ivy that doesn't add any run-time overhead. The `$localize` function looks up the translation in your translation file and inlines translated stri
It is a bit more subtle... when developing (or just if you happen to have i18n tags but no translations) then the `$localize` calls do end up at the browser and do get called. The `@angular/localize/init` provides a minimal version of `$localize` that strips out any metadata and just renders the untranslated strings.

2019-10-18 15:29 UTC, kapunahelewong commented on aio/content/guide/deprecations.md
> +### Migrating for the `$localize` global import
Does a combination work, @kara and @petebacondarwin? 
```suggestion
### Migrating to the new `@angular/$localize` i18n support
```

2019-10-18 16:10 UTC, kara commented on aio/content/guide/deprecations.md
> +### Migrating for the `$localize` global import
Let's take Pete's suggestion

2019-10-18 16:14 UTC, kara commented on aio/content/guide/migration-localize.md
> +If you're using i18n, this schematic imports `@angular/localize` to `polyfills.ts` and adds it to `package.json`.
Ah, didn't realize. We should probably add an faq like "why is my tslint failing?" In case people have a custom config

2019-10-18 16:25 UTC, kara commented on aio/content/guide/migration-localize.md
> +`@angular/localize` is a new package that works with Ivy that doesn't add any run-time overhead. The `$localize` function looks up the translation in your translation file and inlines translated stri
Ahh, right, I forgot about dev mode. Let's replace "symbol" with "function"and that should encompass both

2019-10-18 16:26 UTC, kara commented on aio/content/guide/migration-localize.md
> +output as part of this template compilation. This approach required running the template
Ok let's keep it as is

2019-10-18 16:53 UTC, kapunahelewong commented on aio/content/guide/migration-localize.md
> +The Angular Ivy i18n system instead performs template compilation exactly once. Then,
Added your change, @petebacondarwin. Regarding the use of the word `Ivy`, I hadn't thought of that, but it makes sense. What should I use as an alternative?

2019-10-18 16:57 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +The Angular Ivy i18n system instead performs template compilation exactly once. Then,
Let's ask @kara :-)

2019-10-18 17:03 UTC, kapunahelewong commented on aio/content/guide/migration-localize.md
> +`@angular/localize` is a new package that works with Ivy that doesn't add any run-time overhead. The `$localize` function looks up the translation in your translation file and inlines translated stri
Have edited it. Am I making sense, @petebacondarwin?

>`@angular/localize` is a new package that works with Ivy that doesn't add any run-time overhead.
It adds a `$localize` symbol to the global context, which allows i18n to work properly.
Specifically, when developing (or just if you happen to have `i18n` tags but no translations), the `$localize` are called.
The `@angular/localize/init` provides a minimal version of `$localize` that strips out any metadata and just renders the untranslated strings.

2019-10-18 17:08 UTC, kapunahelewong commented on aio/content/guide/migration-localize.md
> +If you're using i18n, this schematic imports `@angular/localize` to `polyfills.ts` and adds it to `package.json`.
Added:

>## Why is my tslint failing?

The schematic updates the `tslint.json` config file by adding the `@angular/localize` path to the `no-import-side-effect` rule if you have enabled it manually.

```json

"no-import-side-effect": [
  true,
  {
    "ignore-module": "(core-js/.*|zone\\.js/.*|@angular\/localize)$"
  }
]

```



Should I say something about changing it? Because if it's failing, and the reason is because of `no-import-side-effect` being set to`true`, does that mean one should change it to `false`? @petebacondarwin @kara

2019-10-18 17:12 UTC, kara commented on aio/content/guide/migration-localize.md
> +`@angular/localize` is a new package that works with Ivy that doesn't add any run-time overhead. The `$localize` function looks up the translation in your translation file and inlines translated stri
I don't think we need to talk about how $localize works in development mode.  Can we just replace "symbol" with "function"?

> @angular/localize is a new package that works with Ivy that doesn't add any run-time overhead. It adds a $localize function to the global context, which allows i18n to work properly.

2019-10-18 17:15 UTC, kara commented on aio/content/guide/migration-localize.md
> +If you're using i18n, this schematic imports `@angular/localize` to `polyfills.ts` and adds it to `package.json`.
As @petebacondarwin mentioned above, the schematic no longer updates the tslint. You should say something like:

> The import of `@angular/localize/init` may cause a tslint error for 'no-import-side-effect' because it adds to the global context (i.e. a side effect). To fix this error, add the following to your tslint.config:

<diff>

2019-10-18 17:17 UTC, mary-poppins commented
You can preview 072bf06 at https://pr33086-072bf06.ngbuilds.io/.

2019-10-18 17:19 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +`@angular/localize` is a new package that works with Ivy that doesn't add any run-time overhead. The `$localize` function looks up the translation in your translation file and inlines translated stri
It makes sense but I am afraid it will confuse people who perhaps don't get the full picture....

Let's not mention overhead. It will just make people worry that it actually is adding overhead and we are trying to hide something :-)

How about something like:

> `@angular/localize` is a new package that supports i18n of messages in ivy(?) applications.
> It works by tagging such messages with a `$localize` symbol in the compiled code.
> The CLI can translate these tagged messages, inlining the translations in place of the tagged message, leaving no trace of `$localize`.
> During initial development (or if not doing compile time inlining of translations) a minimal implementation of `$localize` is needed and render tagged messages, stripping any metadata.
> This implementation must exist as a function on the global scope (e.g. the `Window`).
> This minimal implementation is loaded by importing the `@angular/localize/init` module, which has the side-effect of attaching the `$localize` function to the global scope.

2019-10-18 17:24 UTC, kara commented on aio/content/guide/migration-localize.md
> +`@angular/localize` is a new package that works with Ivy that doesn't add any run-time overhead. The `$localize` function looks up the translation in your translation file and inlines translated stri
Fair enough. I just worry about overwhelming people with too much detail, but it's a balance. Your suggestion works for me.

2019-10-18 17:29 UTC, mary-poppins commented
You can preview 748fd46 at https://pr33086-748fd46.ngbuilds.io/.

2019-10-18 17:30 UTC, jelbourn commented on aio/content/guide/migration-localize.md
> +`@angular/localize` is a new package that works with Ivy that doesn't add any run-time overhead. The `$localize` function looks up the translation in your translation file and inlines translated stri
IMO, the _migration_ docs should go into an absolute bare minimum of technical detail. The actual docs for the feature should be the canonical source of the full technical details.

2019-10-18 17:32 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +`@angular/localize` is a new package that works with Ivy that doesn't add any run-time overhead. The `$localize` function looks up the translation in your translation file and inlines translated stri
Actually I agree. So something like... ?

> `@angular/localize` is a new package that supports i18n of messages in ivy(?) applications.
> This package requires a global `$localize` symbol to exist.
> The symbol is loaded by importing the `@angular/localize/init` module, which has the side-effect of attaching it to the global scope.

2019-10-18 17:38 UTC, kapunahelewong commented on aio/content/guide/migration-localize.md
> +`@angular/localize` is a new package that works with Ivy that doesn't add any run-time overhead. The `$localize` function looks up the translation in your translation file and inlines translated stri
Thank you very much for this, everyone. Added Pete's latest^^. Will updated if it evolves further. :)

2019-10-18 17:49 UTC, mary-poppins commented
You can preview 235f571 at https://pr33086-235f571.ngbuilds.io/.

2019-10-18 18:51 UTC, kara approved these changes
LGTM, with one more nit

2019-10-18 18:51 UTC, kara commented on aio/content/guide/migration-localize.md
> +To make $localize available on the global scope, each application must now import the @angular/localize/init module.
```suggestion
To make $localize available on the global scope, each application must now import the `@angular/localize/init` module.
```

2019-10-18 19:04 UTC, kara commented
merge-assistance: global approval

2019-10-18 19:11 UTC, mary-poppins commented
You can preview bc8a1b7 at https://pr33086-bc8a1b7.ngbuilds.io/.

2019-10-18 19:13 UTC, petebacondarwin commented on aio/content/guide/migration-localize.md
> +In the new i18n system, the Angular compiler tags i18n messages in the compiled code with a global $localize handler.
```suggestion
In the new i18n system, the Angular compiler tags i18n messages in the compiled code with a global `$localize` handler.
```

2019-10-18 19:14 UTC, petebacondarwin approved these changes
One last nit :-)
Great stuff @kapunahelewong

2019-10-18 19:27 UTC, mary-poppins commented
You can preview 78b5c3d at https://pr33086-78b5c3d.ngbuilds.io/.

2019-10-18 20:30 UTC, closed without merging