docs: add example of a server in golang for deployment
angular/angular pull request #33092
Opened 2019-10-11 01:36 UTC by AndrusGerman

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The example does not exist

## What is the new behavior?

Added an example of a deployment server written in golang for `deployment.md`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information  
**Reason to add the example:** Golang is a very good alternative for high performance servers. And if, in any case, we want to implement an AngularApp, we already have an example within reach.

2019-10-11 02:13 UTC, AndrusGerman commented on aio/content/guide/deployment.md
> +  var httpPort = "80"
Server Port

2019-10-11 02:17 UTC, AndrusGerman reviewed
Sample variables They are documented

2019-10-15 20:16 UTC, kapunahelewong requested changes
Thanks for this, @AndrusGerman! Just a small docs suggestion.

2019-10-15 20:16 UTC, kapunahelewong commented on aio/content/guide/deployment.md
> +we create a basic golang file where we place the server `main.go`:
To help this adhere to the writing guidelines and pattern in the document, could you try:

```
* [Golang](https://golang.org/): create a Golang server using ([gorilla/mux](https://github.com/gorilla/mux)) with a basic Golang file that configures the server `main.go`:
```

2019-10-15 20:17 UTC, kapunahelewong commented
Oh, and also, when you're all done, you'll want to be sure to squash and rebase. When the time comes you might like [my notes on my own workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase).

2019-10-15 20:49 UTC, StephenFluin approved these changes
These instructions all look correct. We'll need a longer term conversation about what the right set of technologies to list here are, without making this section too long.

2019-10-16 17:18 UTC, AndrusGerman commented on aio/content/guide/deployment.md
> +we create a basic golang file where we place the server `main.go`:
Thank you very much for your recommendation. I'm sorry, my English needs to improve a little.

2019-10-16 17:39 UTC, AndrusGerman commented
Thank you @kapunahelewong. The suggestions were added, Is everything ok with this pull request?

2019-10-18 21:07 UTC, kapunahelewong commented
Very close, @AndrusGerman! Just don't forget to squash and rebase (or push up if you just did it and the changes aren't reflected here). If you have any questions on it, just let me know. :)

2019-10-19 02:55 UTC, AndrusGerman commented on aio/content/guide/deployment.md
> +* [Golang](https://golang.org/): create a Golang server using ([gorilla/mux](https://github.com/gorilla/mux)) with a basic Golang file that configures the server `main.go`:
@kapunahelewong  Sorry I thought that with this modification was enough, I do not understand how it should go to the next step

2019-10-21 19:56 UTC, kapunahelewong commented on aio/content/guide/deployment.md
> +* [Golang](https://golang.org/): create a Golang server using ([gorilla/mux](https://github.com/gorilla/mux)) with a basic Golang file that configures the server `main.go`:
Sure, @AndrusGerman. So the work you've done in this PR is good. You don't have to edit the files themselves. The only changes now are just to squash, or make the three commits into one, and to rebase.
## **Squashing**

**1 .** To squash, check out [my own notes on the process](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash). You want to do this because you want this to instead say "AndrusGerman wants to merge 1 commit". :
![image](https://user-images.githubusercontent.com/4116963/67237981-5aba5a00-f41a-11e9-8d52-0f049ac75ad6.png)

## **Rebasing**

**2.** Next, you'll want to rebase to make [this](https://github.com/AndrusGerman/angular/tree/deployment-golang-server-example) not say it's behind master at all. You want yours to be 1 commit ahead (rather than three) and not behind at all.
![image](https://user-images.githubusercontent.com/4116963/67238118-92c19d00-f41a-11e9-9bfe-d93d86c2d9a0.png)
Here are [my notes on rebasing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase).

Let me know if you have questions. I'm happy to help you sort out the steps if needed. 🌼

2019-10-22 23:41 UTC, AndrusGerman commented on aio/content/guide/deployment.md
> +* [Golang](https://golang.org/): create a Golang server using ([gorilla/mux](https://github.com/gorilla/mux)) with a basic Golang file that configures the server `main.go`:
@kapunahelewong In the notes I found 'git pull upstream master', after executing that command I automatically create a merge. This was counted as 1 commit in total 4,I run a 'git rebase -i HEAD ~ 4' and many external pull changes arrived, I think this is not right, and I shouldn't have run the 'git pull upstream' :(

2019-10-23 00:09 UTC, AndrusGerman commented on aio/content/guide/deployment.md
> +* [Golang](https://golang.org/): create a Golang server using ([gorilla/mux](https://github.com/gorilla/mux)) with a basic Golang file that configures the server `main.go`:
I barely noticed and my commit has an invalid message, 
> Merge branch 'deployment-golang-server-example' of https://github.com…

2019-10-23 16:34 UTC, kapunahelewong commented on aio/content/guide/deployment.md
> +* [Golang](https://golang.org/): create a Golang server using ([gorilla/mux](https://github.com/gorilla/mux)) with a basic Golang file that configures the server `main.go`:
Yes, you're correct, you didn't want to run the git pull on your golang branch. Instead, on your golang branch, you want the `git rebase origin/master`(see on step 4 how I do it on the `docs-fix` branch? That would be your golang branch.) You can undo this. But first, I'd recommend backing up your work. There are different ways to do it, but before you try it, you might want to read [this question on StackOverflow](https://stackoverflow.com/questions/1223354/undo-git-pull-how-to-bring-repos-to-old-state), or [this article](https://code.likeagirl.io/how-to-undo-the-last-commit-393e7db2840b), or [this one](https://www.atlassian.com/git/tutorials/undoing-changes).

If this were me, I'd: 

1. back up my work
2. `git log` (get the SHA of the commit you want to keep - that is, where your work is)
3. `git reset --hard <SHA>`

I've done this but it only happens every once in a while, so I can't really remember all the details. I hope this helps. Alternatively, it's totally ok to open a new PR if you don't feel like getting into all the git details. You can tag me in it and reference this PR and we can just pick up where we left off. Totally up to you. :)

2019-10-24 00:43 UTC, AndrusGerman commented on aio/content/guide/deployment.md
> +* [Golang](https://golang.org/): create a Golang server using ([gorilla/mux](https://github.com/gorilla/mux)) with a basic Golang file that configures the server `main.go`:
@kapunahelewong  I think I have done it, I learned several things from git (Thanks)
![Screenshot_20191023_204009](https://user-images.githubusercontent.com/30560543/67444126-c563c500-f5d5-11e9-86bd-cce1f7861d21.png)

2019-10-24 15:08 UTC, kapunahelewong approved these changes
LGTM! Thank you, @AndrusGerman!! 🌟

2019-10-24 15:09 UTC, kapunahelewong commented
merge assistance: global approval for docs changes

2019-10-24 16:51 UTC, closed without merging