fix(ivy): ensure overrides for 'multi: true' only appear once in final providers
angular/angular pull request #33104
Opened 2019-10-11 16:49 UTC by atscott

At the moment, if you override a provider with `mutli: true`, the TestBed goes through and overrides each place where the token is provided. Then the injector processes all of them and adds each occurrence to the provider records. As a result, if you override a `multi: true` provider, you get too many instances in the final output. You should only get the one that was provided in the override (see the test in this PR).

2019-10-11 17:11 UTC, atscott commented
[Presubmit](http://test/OCL:274195183:BASE:274195215:1570813626744:e76fe16)
[Ivy Presubmit](http://test/OCL:274195183:BASE:274195859:1570813832942:e5aa511e)
Should run a global ivy presubmit as well

2019-10-11 19:41 UTC, AndrewKushnir requested changes
@atscott thanks for the fix! I left a few comments. Thank you.

2019-10-11 19:41 UTC, AndrewKushnir commented on packages/core/testing/src/r3_test_bed_compiler.ts
> +    const providerDef = provider.useFactory ? {
I think we need a comment describing that we explicitly avoid setting `multi` flag (even if it was provided) and why we do so.

2019-10-11 19:41 UTC, AndrewKushnir commented on packages/core/testing/src/r3_test_bed_compiler.ts
> +                                              {provide: token, useValue: provider.useValue};
Formatting issue (or the code was auto-formatted like this)?

2019-10-11 19:41 UTC, AndrewKushnir commented on packages/core/test/test_bed_spec.ts
> +    TestBed.overrideProvider(token, { useValue: overrideValue, multi: true } as any);
I think it'd be great to check (and create a test for it) whether VE and Ivy TestBeds work the same in case override value is not an array (but `multi` flag is `true`), like:
```
TestBed.overrideProvider(token, { useValue: {key: 'value'}, multi: true } as any);
```

2019-10-11 20:36 UTC, AndrewKushnir approved these changes
LGTM, thanks for the changes @atscott 👍

2019-10-16 04:18 UTC, atscott commented
[Global Ivy Presubmit](https://test.corp.google.com/OCL:274953034:BASE:274953089:1571199494144:47c96398)

2019-10-21 15:52 UTC, atscott commented
[Ivy global presubmit #31032 ](https://test.corp.google.com/ui#id=OCL:274953034:BASE:275164957:1571279154099:2409cd6f)

2019-10-21 17:36 UTC, AndrewKushnir approved these changes
LGTM 👍 Thanks for adding extra tests!

2019-10-21 18:22 UTC, AndrewKushnir commented
- [VE Presubmit](http://test/OCL:275883348:BASE:275883405:1571681735256:c7a087be)
- [Ivy Presubmit](http://test/OCL:275883348:BASE:275884060:1571681927323:f16e030f)
- [Ivy Presubmit with larger subset of targets](https://test.corp.google.com/OCL:275883348:BASE:275884893:1571682145851:7ee0eab1)

2019-10-22 19:35 UTC, atscott commented
[Ivy presubmit](http://test/OCL:276119412:BASE:276120174:1571772762655:6091b4bc)
[Ivy presubmit with larger subset of targets](https://test.corp.google.com/OCL:276119412:BASE:276120666:1571772892542:ed6de407)

2019-10-24 19:41 UTC, atscott commented
[Ivy presubmit](https://test.corp.google.com/OCL:276543166:BASE:276544618:1571946083277:db0b217e)
[Ivy presubmit with larger subset](https://test.corp.google.com/OCL:276543166:BASE:276544579:1571946069990:fffa97a1)

2019-10-24 20:36 UTC, atscott commented
[Ivy presubmit](http://test/OCL:276554842:BASE:276555008:1571949320121:a420691b)
[Ivy presubmit with larger subset of targets](https://test.corp.google.com/OCL:276554842:BASE:276555213:1571949377621:365df8cf)

2019-10-28 16:25 UTC, atscott commented
[Ivy Presubmit](http://test/OCL:277078017:BASE:277078190:1572279800112:1c01e266)
[Ivy Presubmit with larger subset](https://test.corp.google.com/OCL:277078017:BASE:277078701:1572279939619:c3c11ea2)

2019-10-28 18:00 UTC, closed without merging