Add ivy template typecheck doc
angular/angular pull request #33152
Opened 2019-10-14 19:40 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

New page describing changes to template type-checking with Ivy

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
New info, no doc
Issue Number: N/A

## What is the new behavior?
This adds a proposed page with info from https://hackmd.io/I3sIbeSPSPeY0IX8LMEQ3A 
Currently not in nav and no links to the page.

We need to think about where Ivy info goes. 
It doesn't really belong under "Techniques", should be in either Dev Workflow or Configuration.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-10-14 19:47 UTC, mary-poppins commented
You can preview 24af3ef at https://pr33152-24af3ef.ngbuilds.io/.

2019-10-14 20:44 UTC, mary-poppins commented
You can preview 0e543a3 at https://pr33152-0e543a3.ngbuilds.io/.

2019-10-15 18:53 UTC, mary-poppins commented
You can preview 251339c at https://pr33152-251339c.ngbuilds.io/.

2019-10-16 16:42 UTC, mary-poppins commented
You can preview 843863e at https://pr33152-843863e.ngbuilds.io/.

2019-10-17 18:45 UTC, mary-poppins commented
You can preview 93b512d at https://pr33152-93b512d.ngbuilds.io/.

2019-10-17 20:50 UTC, jbogarthyde commented
See proposed merger of this content into a new version of the Ivy page:
https://docs.google.com/document/d/1n_RN2z0hTZoKszIoV1dmur9uXJ8XZ822e5qC3JzpmKQ

2019-10-21 19:10 UTC, mary-poppins commented
You can preview 3e46ad8 at https://pr33152-3e46ad8.ngbuilds.io/.

2019-10-23 16:06 UTC, mary-poppins commented
You can preview 53fe0ff at https://pr33152-53fe0ff.ngbuilds.io/.

2019-10-23 17:08 UTC, mary-poppins commented
You can preview c15ee98 at https://pr33152-c15ee98.ngbuilds.io/.

2019-10-23 17:40 UTC, mary-poppins commented
You can preview 525cb1f at https://pr33152-525cb1f.ngbuilds.io/.

2019-10-23 17:49 UTC, mary-poppins commented
You can preview 693c32d at https://pr33152-693c32d.ngbuilds.io/.

2019-10-23 18:23 UTC, mary-poppins commented
You can preview 30cdd2f at https://pr33152-30cdd2f.ngbuilds.io/.

2019-10-23 20:56 UTC, mary-poppins commented
You can preview cdb04e1 at https://pr33152-cdb04e1.ngbuilds.io/.

2019-10-23 21:14 UTC, mary-poppins commented
You can preview 574d7de at https://pr33152-574d7de.ngbuilds.io/.

2019-10-23 21:26 UTC, mary-poppins commented
You can preview e99805e at https://pr33152-e99805e.ngbuilds.io/.

2019-10-23 21:41 UTC, mary-poppins commented
You can preview 4b12e86 at https://pr33152-4b12e86.ngbuilds.io/.

2019-10-23 22:00 UTC, mary-poppins commented
You can preview ec5e82b at https://pr33152-ec5e82b.ngbuilds.io/.

2019-10-24 12:23 UTC, filipesilva commented on aio/content/guide/ivy.md
> +## Migrating libraries to Ivy
This section does not mention what one should do as a library consumer if `ngcc` does not correctly compile the library. This seems to be a common enough thing at the moment.

Should we point users to some catch-all ngcc issue, or maybe to submit a new issue (possibly using a ngcc related template)?

2019-10-24 12:24 UTC, filipesilva approved these changes

2019-10-24 18:10 UTC, mary-poppins commented
You can preview 31283b4 at https://pr33152-31283b4.ngbuilds.io/.

2019-10-24 20:07 UTC, mary-poppins commented
You can preview 897150e at https://pr33152-897150e.ngbuilds.io/.

2019-10-24 20:57 UTC, mary-poppins commented
You can preview 667a2c5 at https://pr33152-667a2c5.ngbuilds.io/.

2019-10-24 23:11 UTC, alxhub commented on aio/content/guide/template-typecheck.md
> +In strict mode, the following flags can be set in version 9 to enable the strictest possible type-checking of template variables in [specific cases](guide/template-typecheck#examples).
The goal of this section is to describe how to opt _out_ of strictness on a per-setting basis, so I think it needs the wording reversed - it should talk about disabling the flags if needed.

2019-10-24 23:11 UTC, alxhub commented on aio/content/guide/template-typecheck.md
> +* Checks `@Input()` assignability. For example, in the binding `[city]="Bogotá"`, Ivy checks to see if  the value `Bogotá` is actually assignable to the `city` field of the directive you're binding t
```suggestion
* Checks `@Input()` assignability. For example, in the binding `[city]="'Bogotá'"`, Ivy checks to see if the string `'Bogotá'` is actually assignable to the `city` field of the directive you're binding to.
```

2019-10-24 23:39 UTC, alxhub requested changes

2019-10-24 23:39 UTC, alxhub commented on aio/content/guide/template-typecheck.md
> +| `strictComponentRefTypes` | When `true`, type-checks references to components.  |
I don't think this is a thing.

2019-10-24 23:39 UTC, alxhub commented on aio/content/guide/template-typecheck.md
> +| `strictDomRefTypes` | When `true`, type-checks references to DOM elements. |
`strictDomLocalRefTypes`

2019-10-25 16:01 UTC, mary-poppins commented
You can preview 4805273 at https://pr33152-4805273.ngbuilds.io/.

2019-10-25 18:14 UTC, alxhub commented on aio/content/guide/template-typecheck.md
> +In this case we've made a special effort that Ivy would be non-breaking, however, you'll need to fix type errors for accuracy because if strict mode catches an error, it will need to be addressed in
I think the points in this section are in a weird order. The primary content here should be about `strictTemplates`. Roughly speaking the resolutions are:

1) determine whether it's a real issue or not. often times the errors reported by `strictTemplates` are indeed real errors.

This is where we should talk about false positives.

2) Opting out of errors

Toggling specific strictness flags off can work around problems until they're either fixed in the app, in a library, or in the compiler itself.

Here we should have a table covering the flags and a 1-sentence description of their purpose, with instructions to jump to the examples below for more details.

3) Toggling `strictTemplates` off, but maybe setting specific strictness flags to `true` if feasible.

4) Opting out of `fullTemplateTypeCheck` in its entirety. If you have to do this, then it's a bug, and you should report it to us.

2019-10-25 19:05 UTC, kapunahelewong commented on aio/content/guide/template-typecheck.md
> +## What's changing in template type-checking
Re-structured.

2019-10-25 22:34 UTC, kara commented on aio/content/guide/ivy.md
> +</code-example>
These instructions are already part of our "Updating to version 9" guide (https://github.com/angular/angular/blob/master/aio/content/guide/updating-to-version-9.md#updating-cli-apps). I don't think we need them here, since they're not Ivy-specific

2019-10-25 22:34 UTC, kara commented on aio/content/guide/ivy.md
> +# Migrating to Ivy
```suggestion
# Angular Ivy
```

2019-10-25 23:39 UTC, kara submitted a review, later dismissed

2019-10-25 23:39 UTC, kara commented on aio/content/guide/ivy.md
> +## Opting out of Ivy in version 9
Move to bottom

2019-10-25 23:39 UTC, kara commented on aio/content/guide/ivy.md
> +## Migrating libraries to Ivy
```suggestion
## Ivy and Libraries
```

2019-10-25 23:39 UTC, kara commented on aio/content/guide/ivy.md
> +## Template type checking in Ivy
Remove this section and instead add nav link under "AOT compiler". I'll add another one in the "updating to version 9" guide when this gets in

2019-10-28 16:07 UTC, jbogarthyde commented on aio/content/guide/ivy.md
> +## Migrating libraries to Ivy
This no longer applies to this page (although the information you want should probably go somewhere, perhaps in Using Libraries?)

2019-10-28 16:14 UTC, filipesilva commented on aio/content/guide/ivy.md
> +## Migrating libraries to Ivy
I think we want to direct users in how to identify and report ngcc-specific errors, and where to find and apply workarounds when available (I suppose via the ngcc configuration file).

@petebacondarwin do we have information on this topic in the docs? Are there plans to add it?

2019-10-28 16:31 UTC, mary-poppins commented
You can preview 4727e90 at https://pr33152-4727e90.ngbuilds.io/.

2019-10-28 16:58 UTC, petebacondarwin commented on aio/content/guide/ivy.md
> +## Migrating libraries to Ivy
Well there is this https://next.angular.io/guide/updating-to-version-9...
Perhaps we should have a section in there explaining how ngcc might fail?
I don't think a catch-all ngcc issue is a good idea. We have had some of those in the past and they become unfocussed and unusable very quickly.
I would encourage people to search the issues for their error (just like any other bug in Angular).

2019-10-28 17:26 UTC, mary-poppins commented
You can preview b28f33f at https://pr33152-b28f33f.ngbuilds.io/.

2019-10-28 17:35 UTC, mary-poppins commented
You can preview fcbd6d7 at https://pr33152-fcbd6d7.ngbuilds.io/.

2019-10-29 00:45 UTC, IgorMinar requested changes

2019-10-29 00:45 UTC, IgorMinar commented on aio/content/guide/ivy.md
> +In particular, the step runs for any command that affects your `node_modules` folder.
this doesn't belong / make sense here.
```suggestion
```

2019-10-29 00:45 UTC, IgorMinar commented on aio/content/guide/ivy.md
> +To do this, change the `angularCompilerOptions` in your project's TypeScript configuration, most commonly located at `/tsconfig.app.json`.
```suggestion
To do this, change the `angularCompilerOptions` in your project's TypeScript configuration, most commonly located at `tsconfig.app.json` at the root of the workspace.
```

2019-10-29 00:45 UTC, IgorMinar commented on aio/content/guide/ivy.md
> +The following example shows the new `enableIvy` option, which defaults to true in version 9.
```suggestion
The following example shows how to set the `enableIvy` option to `false`, in order to opt-out of Ivy. The value of this flag is set to `true` as of version 9.
```

2019-10-29 00:45 UTC, IgorMinar commented on aio/content/navigation.json
> +              "url": "guide/ivy",
This section should not be under the compiler - it should be under the "Release Information". Can you please move it?

2019-10-29 00:45 UTC, IgorMinar commented on aio/content/navigation.json
> +              "url": "guide/ivy",
fyi: only the template type checking doc should be under the compiler in the menu.

2019-10-29 00:45 UTC, IgorMinar commented on aio/content/guide/aot-compiler.md
> +For more information about improvements to template type checking in v9 and help in migrating to the stricter checks available in this and future releases, see [Updating to version 9](guide/updating-
```suggestion
This stricter type checking can be enabled via the `strictTemplates` config option and is not enabled by default in version 9, however we do expect it to become the default in the future.

For more information about improvements to template type checking in version 9 and help in migrating to the stricter checks available in this and future releases, see [Updating to version 9](guide/updating-to-version-9).
```

2019-10-29 00:45 UTC, IgorMinar commented on aio/content/guide/ivy.md
> +</code-example>
we should also mention that "Additionally, you might want to revert the change to the `aot` config property in angular.json described in the Ivy and AOT section above."

2019-10-29 00:45 UTC, IgorMinar commented on .github/CODEOWNERS
> -
please revert.

2019-10-29 17:43 UTC, alxhub approved these changes

2019-10-29 17:43 UTC, alxhub commented on aio/content/guide/aot-compiler.md
> +For more information about improvements to template type checking in v9 and help in migrating to the stricter checks available in this and future releases, see [Updating to version 9](guide/updating-
We need to make sure this is the correct link - do we have any template type-checking info in this doc?

2019-10-29 21:31 UTC, kara commented on aio/content/guide/aot-compiler.md
> +We do expect to make strict type checking the default in future.
```suggestion
We do expect to make strict type checking the default in the future.
```

2019-10-29 21:31 UTC, kara commented on aio/content/guide/ivy.md
> +{@a opting-out-of-angular-ivy}
It feels like we are missing a section that links to the compatibility guide. We should recommend people try to debug before giving them the opt-out instructions.

2019-10-29 21:50 UTC, jbogarthyde commented on aio/content/guide/aot-compiler.md
> +For more information about improvements to template type checking in v9 and help in migrating to the stricter checks available in this and future releases, see [Updating to version 9](guide/updating-
This should point to the new type-checking page, which hasn't landed yet.
We are planning to integrate this section with that page after it lands -- I'll comment this out for now.

2019-10-29 22:12 UTC, mary-poppins commented
You can preview 77260a1 at https://pr33152-77260a1.ngbuilds.io/.

2019-10-30 05:46 UTC, IgorMinar approved these changes
One more correction. Otherwise lgtm.

2019-10-30 05:46 UTC, IgorMinar commented on aio/content/guide/ivy.md
> +To opt out of Ivy, change the `angularCompilerOptions` in your project's TypeScript configuration, most commonly located at `/tsconfig.app.json` at the root of the workspace.
```suggestion
To opt out of Ivy, change the `angularCompilerOptions` in your project's TypeScript configuration, most commonly located in `tsconfig.app.json` at the root of the workspace.
```

2019-10-30 15:37 UTC, mary-poppins commented
You can preview 31e4c24 at https://pr33152-31e4c24.ngbuilds.io/.

2019-10-30 17:39 UTC, closed without merging

2019-10-31 16:26 UTC, kara commented on aio/content/guide/ivy.md
> +<div class="alert is-helpful>
This is missing a quotation mark, so the alert is messed up

2019-10-31 16:54 UTC, jbogarthyde commented on aio/content/guide/ivy.md
> +<div class="alert is-helpful>
@kara This already landed, so opened new PR - https://github.com/angular/angular/pull/33513