LFrame
angular/angular pull request #33178
Opened 2019-10-15 16:34 UTC by mhevery

- This PR introduces a concept of an `LFrame`. `LFrame` is just a collection of global state which the instructions used. (This is not a new concept just giving an explicit name to something which we had before but was unnamed)
- Change all of the places where we enter/leave `LFrame` to use proper methods such as `enterView` and `leaveView` rather than having hap hazard enter/leave/save state methods.

NOTE: This PR does not change how the system works, it only groups things into mental concepts and gives the mental concept a proper name.

2019-10-15 20:44 UTC, josephperrott commented on .notes.md
> +----
It looks like this file was added to `.gitignore` but made it into your PR.

2019-10-15 20:51 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/listener.ts
> +  enterView(lView, tNode);
wonder why we need to enter / exit view while processing a listener?

2019-10-16 14:49 UTC, pkozlowski-opensource commented on packages/core/src/render3/state.ts
> +   * so that we can than attach `LView` to only those elements.
attach `LView` -> attach patch data (`LView`) - somehow I would like to see "patch data" mentioned here.

2019-10-16 15:01 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +    leaveViewProcessExit();
do we need to process exit functions in the creation mode? I must say that it is not clear to me which functions can be set in which mode...

2019-10-16 20:01 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +    leaveViewProcessExit();
I think in update mode only. Fixed

2019-10-16 20:45 UTC, mhevery commented on integration/_payload-limits.json
> +        "main": 14228,
```suggestion
        "main": 14458,
```

2019-10-16 20:50 UTC, mhevery commented
[presubmit](http://test/OCL:275104943:BASE:275105022:1571258842413:547e3ab2)
[ivy presubmit](http://test/OCL:275104943:BASE:275105392:1571258969370:2df70560)

2019-10-17 00:20 UTC, AndrewKushnir commented
Restarting presubmits, since previous ones were not informative due to a set of pre-existing (non-related) failures that are now fixed.

- [VE Presubmit](http://test/OCL:275148459:BASE:275148545:1571271566120:f4ccd9cd)
- [Ivy Presubmit](http://test/OCL:275148459:BASE:275148681:1571271624614:a89701bb)

2019-10-17 01:15 UTC, AndrewKushnir commented
FYI, Ivy presubmit indicated a target that regressed in g3, related to these changes. I'm adding "blocked" label for now.

2019-10-18 10:21 UTC, pkozlowski-opensource commented on packages/core/src/render3/component.ts
> +    leaveViewProcessExit();
question: `leaveView` should be enough here, no? We are dealing with a root view that doesn't have anything beside a root component?

2019-10-18 10:23 UTC, pkozlowski-opensource commented on packages/core/src/render3/component_ref.ts
> +    // TODO(misko): it looks like we are entering view here but we don't really need to as
+1, we should fix it, I was toying with this once

2019-10-18 10:29 UTC, pkozlowski-opensource commented on packages/core/src/render3/component_ref.ts
> +      leaveViewProcessExit();
`leaveViewProcessExit` -> `leaveView`? This is a root view in creation mode only.

2019-10-18 10:58 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/listener.ts
> +  enterView(lView, tNode);
So, from the quick debugging it seems to be linked to the fact that we've got the `ɵɵrestoreView` instruction in the listener function. So it seems to me like we are trying to manipulate "current view" from 2 different places (generated code and the listener code in ivy runtime).

It still feels fishy to me at I would love that we have a clear picture of what is going on with with manipulation in case of listeners.

2019-10-18 12:21 UTC, pkozlowski-opensource requested changes
@mhevery I did another pass on this PR and left some comments. Those are mostly nits about `leaveViewProcessExit` vs. `leaveView` but the listeners case is the one that needs more attention - seems like we are doing view setting / restoration in multiple places.

Also, I think that @matsko should do a pass on it as there are some style-related changes which I don't feel comfortable reviewing. 

It will also need rebase now since your other global-state related PR landed.

2019-10-18 18:46 UTC, mhevery commented
[presubmit](http://test/OCL:275516162:BASE:275516213:1571424328369:f7dc9cfb)
[ivy presubmit](http://test/OCL:275516162:BASE:275516342:1571424381956:11883b50)

2019-10-21 17:13 UTC, mhevery commented
[presubmit ivy](http://test/OCL:275516162:BASE:275868187:1571677967409:91a331f4)

2019-10-21 20:37 UTC, mhevery commented on packages/core/src/render3/state.ts
> +   * so that we can than attach `LView` to only those elements.
fixed

2019-10-21 20:38 UTC, mhevery commented on packages/core/src/render3/component.ts
> +    leaveViewProcessExit();
fixed

2019-10-21 20:44 UTC, mhevery commented on packages/core/src/render3/component_ref.ts
> +      leaveViewProcessExit();
fixed

2019-10-21 20:46 UTC, mhevery commented on packages/core/src/render3/instructions/listener.ts
> +  enterView(lView, tNode);
Removed. Turns out that there was a separate bug which I fixed which also fixed this one.

2019-10-23 16:17 UTC, pkozlowski-opensource approved these changes
LGTM. Thnx for resolving all my comments @mhevery

2019-10-23 18:26 UTC, AndrewKushnir commented
- [VE Presubmit](http://test/OCL:276315464:BASE:276315517:1571855150655:9d7c334d)
- [Ivy Presubmit](http://test/OCL:276315464:BASE:276315684:1571855201426:8c750390)

2019-10-23 20:32 UTC, mhevery commented on .notes.md
> +----
fixed

2019-10-23 23:47 UTC, AndrewKushnir commented
FYI, g3 presubmits are successful.

I've added "blocked" label for now to avoid merging it before @kara's review.

2019-10-24 00:15 UTC, kara requested changes
Like the direction of this! Minor comments

2019-10-24 03:54 UTC, mhevery commented on packages/core/src/render3/state.ts
> +  // TODO(misko): This should throw when there is no LVIew, but it turns out we can get here from
fixed

2019-10-24 03:54 UTC, mhevery commented on packages/core/src/render3/state.ts
> +  instructionState.lFrame = instructionState.lFrame.parent;
Good idea, done.

2019-10-24 04:07 UTC, mhevery commented on packages/core/src/render3/di.ts
> +      enterView(lView, tNode);
- `getOrCreateInjectable` is called from `NodeInjector` so you can't assume that the `LView` is correct.

You are correct that it does feel very heavy weight, I feel that same way. We could have DI to have light-weight `enter`/`leave` as we know that DI does not need anything else but those values. However we need to make sure that the shape of `LFrame` is same since we want to keep things monomorphic. Let me see if I can make it simpler

2019-10-24 04:16 UTC, mhevery commented on packages/core/src/render3/di.ts
> +      enterView(lView, tNode);
I also have an idea for making `LView` smaller, but I think we should do that in a separate PR.

2019-10-24 04:35 UTC, mhevery commented on packages/core/src/render3/di.ts
> +      enterView(lView, tNode);
have a loot at https://github.com/angular/angular/pull/33178/commits/8bea09dcb00d946d468ef7fe9a44a4885d9d5ad0

2019-10-24 08:07 UTC, pkozlowski-opensource commented on packages/core/src/render3/di.ts
> +      enterView(lView, tNode);
Yeh, we should have a lighter version for DI as my profiling indicates that entering / leaving view (or setting / re-setting global state) is the most expensive part of the DI (!). I would love to spend some time on it (this is partly what I wanted to discuss with you @kara ) but let's defer this to a separate PR.

2019-10-24 17:24 UTC, kara commented on packages/core/src/render3/di.ts
> +      enterView(lView, tNode);
Ok that works for me

2019-10-24 17:29 UTC, kara approved these changes
LGTM with one more typo and moving the DI work to a new PR, as Pawel suggested.

2019-10-24 17:29 UTC, kara commented on packages/core/src/render3/state.ts
> +    // reseting for safety in dev mode only.
```suggestion
    // resetting for safety in dev mode only.
```

2019-10-24 20:07 UTC, mhevery commented on packages/core/src/render3/state.ts
> +    // reseting for safety in dev mode only.
fixed

2019-10-24 21:42 UTC, closed without merging