docs: correct vscode clang-format setup instructions
angular/angular pull request #33190
Opened 2019-10-15 22:12 UTC by dannyskoog

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The VSCode **clang-format** instructions incorrectly points out that workspace settings are automatically picked up by VSCode. This leads to new contributors possibly not being able to properly set up the VSCode clang-format extension.

Issue Number: N/A

## What is the new behavior?
The instructions are referring to the VSCode specific [readme](https://github.com/angular/angular/blob/master/.vscode/README.md) that describes how to configure the workspace settings.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-10-16 08:52 UTC, gkalpak requested changes
Good catch! This was from back when we did ship a `settings.json` file 😅

2019-10-16 08:52 UTC, gkalpak commented on docs/DEVELOPER.md
> +2. [Configure](../.vscode/README.md) settings.
Creating a `settings.json` file is independent from the `clang-format` section, so I suggest the following change:

> 1. Install ...
> 2. It will automatically pick up the settings from [.vscode/settings.json](../.vscode/settings.json).  
>     If you haven't already, create a `settings.json` file by following the instructions [here](../.vscode/README.md).

2019-10-16 17:35 UTC, dannyskoog commented on docs/DEVELOPER.md
> +2. [Configure](../.vscode/README.md) settings.
Fair point and I like your suggestion. Will amend!

2019-10-16 22:45 UTC, dannyskoog commented
Updated @gkalpak

2019-10-17 08:17 UTC, gkalpak approved these changes
Thx, @dannyskoog! LGTM :+1:

2019-10-17 08:17 UTC, gkalpak commented
**merge-assistance:** Global approval for this docs-only change.

2019-10-17 18:18 UTC, closed without merging