Recursive change detection
angular/angular pull request #33235
Opened 2019-10-17 20:33 UTC by mhevery

```
┌────────────────────────────────────┬─────────┬──────┬───────────┬───────────┬───────┐
│              (index)               │  time   │ unit │ base_time │ base_unit │   %   │
├────────────────────────────────────┼─────────┼──────┼───────────┼───────────┼───────┤
│       directive_instantiate        │  2.427  │ 'us' │   2.483   │   'us'    │ -2.26 │
│        element_text_create         │  1.266  │ 'us' │   1.278   │   'us'    │ -0.94 │
│           interpolation            │ 213.588 │ 'us' │  216.65   │   'us'    │ -1.41 │
│             listeners              │  1.921  │ 'us' │   1.952   │   'us'    │ -1.59 │
│ map_based_style_and_class_bindings │ 18.211  │ 'ms' │  17.983   │   'ms'    │ 1.27  │
│       noop_change_detection        │  24.99  │ 'us' │   23.96   │   'us'    │  4.3  │
│          property_binding          │ 220.944 │ 'us' │  219.963  │   'us'    │ 0.45  │
│      property_binding_update       │ 442.284 │ 'us' │  408.865  │   'us'    │ 8.17  │
│      style_and_class_bindings      │  1.023  │ 'ms' │  990.402  │   'us'    │ 3.29  │
│           style_binding            │ 443.163 │ 'us' │  489.636  │   'us'    │ -9.49 │
└────────────────────────────────────┴─────────┴──────┴───────────┴───────────┴───────┘
```

2019-10-18 01:17 UTC, AndrewKushnir commented
Presubmits to get initial results in g3:
- [VE Presubmit](https://test.corp.google.com/ui#id=OCL:275379455:BASE:275379490:1571361365488:4b4757d6)
- [Ivy Presubmit](https://test.corp.google.com/ui#id=OCL:275379455:BASE:275379572:1571361404878:448b4b60)

2019-10-18 21:07 UTC, mhevery commented
[presubmit](http://test/OCL:275542287:BASE:275542368:1571432667353:68f00907)
[ivy presubmit](http://test/OCL:275542287:BASE:275542847:1571432824145:93abda6f)

2019-10-19 03:07 UTC, AndrewKushnir commented
FYI, new [Global TAP run](https://test.corp.google.com/ui#id=OCL:275591098:BASE:275591227:1571454397370:270fdf4a) with the most up-to-date set of changes.

2019-10-20 23:34 UTC, rbuzzibarrios approved these changes

2019-10-23 20:34 UTC, mhevery commented
BLOCKED: waiting on https://github.com/angular/angular/pull/33178 and needs rebase

2019-10-23 20:36 UTC, AndrewKushnir commented
FYI, Global TAP run looks good 👍

2019-10-24 08:15 UTC, pkozlowski-opensource requested changes
We need acceptance unit test(s) for the cases that we are fixing in this PR.

2019-10-24 11:10 UTC, filipesilva submitted a review, later dismissed

2019-10-24 11:10 UTC, filipesilva commented on integration/_payload-limits.json
> +        "main": 14458,
Can you rebase on master please? There are additional size checks now that this PR is not updating.

Earlier this week a similar situation with https://github.com/angular/angular/commit/bb53b6549#diff-55315ab5c9e23bee7dc42a45a3517105 that prompted the caretaker to have to update the sizes on master because it was failing. This situation was a surprise and it was decided that these size increases needed more scrutiny. 

cc @kara

2019-10-24 23:16 UTC, mhevery commented on integration/_payload-limits.json
> +        "main": 14458,
fixed

2019-10-25 21:37 UTC, mhevery commented
> We need acceptance unit test(s) for the cases that we are fixing in this PR.

Test added

2019-10-27 06:17 UTC, pkozlowski-opensource commented on packages/core/src/render3/state.ts
> +export function nextBindingIndex2(): number {
Do we need this function given that we've got `incrementBindingIndex`? Also, this function doesn't seem to be used consistently (`nextBindingIndex2()` is only used in styling and `incrementBindingIndex(2)` in all other places)

2019-10-27 06:30 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/change_detection_spec.ts
> +          this.cdr.detectChanges();
This is a good test as it calls into user code in a very sensitive please (this setter can be invoked in _both_ update _and_ creation mode). I think that we've got issues report where this setter is invoked in the creation mode (from a static attribute, like `<child input="3"></child>`) and it fails as well. Not sure if you consider this "in scope" for this PR.

2019-10-28 16:43 UTC, pkozlowski-opensource approved these changes
LGTM

2019-10-28 17:59 UTC, closed without merging