fix(language-service): Add global symbol for $any()
angular/angular pull request #33245
Opened 2019-10-18 01:46 UTC by kyliau

This commit adds `$any()` function to the "global symbol table".

See https://angular.io/guide/template-syntax#the-any-type-cast-function and https://github.com/angular/vscode-ng-language-service/issues/242

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-10-19 01:08 UTC, ayazhafiz requested changes

2019-10-19 01:08 UTC, ayazhafiz commented on packages/language-service/src/template.ts
> +function createGlobalSymbolTable(query: ng.SymbolQuery) {
I think it's worth pulling this out into a separate file, because this symbol table is orthogonal to the more high-level handling of templates we do in this file.

2019-10-19 01:08 UTC, ayazhafiz commented on packages/language-service/src/template.ts
> +let GLOBAL_SYMBOL_TABLE: ng.SymbolTable|undefined;
Consider wrapping this in a singleton class rather than having a floating global variable. This would provide access control, too - only `createGlobalSymbolTable` should be able to modify this value.

2019-10-20 23:42 UTC, rbuzzibarrios approved these changes

2019-10-21 21:32 UTC, kyliau commented on packages/language-service/src/template.ts
> +function createGlobalSymbolTable(query: ng.SymbolQuery) {
that's good suggestion, thanks!

2019-10-21 21:32 UTC, kyliau commented on packages/language-service/src/template.ts
> +let GLOBAL_SYMBOL_TABLE: ng.SymbolTable|undefined;
done. I wrapped it in an IIFE instead.

2019-10-21 23:21 UTC, ayazhafiz commented on packages/language-service/src/global_symbols.ts
> +export const createGlobalSymbolTable: (query: ng.SymbolQuery) => ng.SymbolTable = (function() {
what's the benefit of an IIFE? Do we always want this to be executed when the language service is loaded, even if the table is not used? Would it not work to use a closure?

2019-10-23 03:23 UTC, kyliau commented on packages/language-service/src/global_symbols.ts
> +export const createGlobalSymbolTable: (query: ng.SymbolQuery) => ng.SymbolTable = (function() {
IIFE is just a pattern to make the GLOBAL_SYMBOL_TABLE variable "private". When the IIFE is executed, there's not much work done besides declaration of the variable. Work is done only when the function is called the first time.

In this case, I think both IIFE and Closure are reasonable, now that the function is extracted into its own file. Please let me know which style you think is better.

2019-10-23 14:02 UTC, ayazhafiz commented on packages/language-service/src/global_symbols.ts
> +export const createGlobalSymbolTable: (query: ng.SymbolQuery) => ng.SymbolTable = (function() {
Oh, I see. I was just thinking of IIFE in the most traditional form of it's usage, but in fact it's acting as a self-executing closure in this case. I think this is better than the closure in that case, as a closure would probably require `createGlobalSymbol(someQuery)(someQuery)`

2019-10-23 14:02 UTC, ayazhafiz approved these changes

2019-10-23 17:02 UTC, closed without merging