feat(docs-infra): implement figure styles
angular/angular pull request #33259
Opened 2019-10-18 23:24 UTC by sjtrimble

PR#28396 originally addressed an update via issue #23983 to make images more visible with a white background (implementation of gray "lightbox").

This PR implements those styles defined in PR#28396.

## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Images are often lost since the background change to white.

Issue Number: #23983 | and PR #28396

## What is the new behavior?
Add a shadowed gray 'lightbox' to better define images throughout the documentation.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

2019-10-18 23:31 UTC, mary-poppins commented
You can preview 187a492 at https://pr33259-187a492.ngbuilds.io/.

2019-10-19 11:07 UTC, gkalpak requested changes
Are there occurrences of `figure > img`, without `.lightbox` (or a `.card`)?
If so, how does one decide when to use `.lightbox` and `.card` and when not?

2019-10-19 11:07 UTC, gkalpak commented on aio/src/styles/2-modules/_images.scss
> +.sidenav-content {
This shouldn't be necessary 😕
Docs content is wrapped in both `.content` and `.sidenav-content`.

2019-10-21 20:31 UTC, sjtrimble commented
@gkalpak eek :/ It looks like one my fixup commits never made it on there? 

I "THINK" I took care of everything.

The extra lines were there originally and sometimes my editor made it look like I wasn't supposed to indent properly so I thought maybe it would break the markdown if I did...
<img width="963" alt="Screen Shot 2019-10-21 at 1 14 27 PM" src="https://user-images.githubusercontent.com/2958442/67240635-b67ae800-f406-11e9-8b8c-2fcadbfdd036.png">

<hr>

I was going to update the style guide to reflect when to use the `lightbox` and `card` etc.

2019-10-21 20:35 UTC, mary-poppins commented
You can preview 65e6295 at https://pr33259-65e6295.ngbuilds.io/.

2019-10-22 08:51 UTC, gkalpak commented on aio/angular.json
> +    "analytics": false
This change looks unrelated to the PR.

2019-10-22 08:51 UTC, gkalpak commented on aio/angular.json
> +}
😢

2019-10-22 08:51 UTC, gkalpak commented on aio/content/guide/dependency-injection-in-action.md
> +    act into">
Unnecessary linebreak.

2019-10-22 08:51 UTC, gkalpak commented on aio/content/guide/dependency-injection-in-action.md
> +    ger restricted API">
Unnecessary linebreak.

2019-10-22 08:51 UTC, gkalpak commented on aio/content/guide/forms-overview.md
> +  </figure>
Incorrect indentation.

2019-10-22 08:51 UTC, gkalpak commented on aio/content/guide/hierarchical-dependency-injection.md
> +      <img src="generated/images/guide/dependency-injection/injectors.svg" alt="NullInjector, ModuleInjector, root injector">
Incorrect indentation.

2019-10-22 08:51 UTC, gkalpak commented on aio/content/guide/router.md
> +
Unnecessary empty lines 😇

2019-10-22 09:02 UTC, gkalpak commented
>> Are there occurrences of `figure > img`, without `.lightbox` (or a `.card`)?
>> If so, how does one decide when to use `.lightbox` and `.card` and when not?
>
> I was going to update the style guide to reflect when to use the `lightbox` and `card` etc.

Were or are? 😕 😛
I definitely agree this should be in the guide.

My concern is that we are complicating the conventions one has to follow, which will inevitably result in them not being consistently followed 😟
I would love if we could simplify things. For example, if `.card` should always be used with `.lightbox`, then we might be able to get rid of the nested `.card` and style the `.lightbox` (or the contained imaged) instead. Or if most `fixure`s will use `.lightbox`, we could make it the default and have another class to "opt-out" of the `.lightbox` styling.

2019-10-22 17:11 UTC, mary-poppins commented
You can preview 5d987c6 at https://pr33259-5d987c6.ngbuilds.io/.

2019-10-22 18:02 UTC, sjtrimble commented
@gkalpak Here's what I was thinking on images and figures...

I see there being two types of images (both in documentation and marketing pages) that we utilize regularly:
1) *Aesthetic Image*: Usually inline images that are often there for aesthetic reasons or to reiterate something already written or explained (like this little template hero image  http://localhost:4200/guide/architecture-components#templates-and-views) -> This would have no particular styling
2) *Explanatory Image*: Call out images that further explain the documentation (like the other images on that ex page above) or that show steps (like here http://localhost:4200/start) -> This would always have the lightbox element

Furthermore, from my understanding, `figures` are actually to be used as stand-alone content that you could remove and leave untouched. Some of the images contained in `figures` in the start guide, for example, http://localhost:4200/start#template-syntax are technically not correct because they images follow ":".

To do it "really right" we would almost need to remove all of the `figures` to keep things simple (especially since we are not using captions or image groups anywhere in the doc or don't have a strong need to do so). If we do that (all just `img` tags), then I would probably have a `div.lighbox > img` structure and style accordingly for the explanatory images. What do you think?

For now however .... we could merge this PR (once clean) so it visually looks right, while I update the format again. **Thoughts?**

2019-10-22 18:13 UTC, mary-poppins commented
You can preview f588c65 at https://pr33259-f588c65.ngbuilds.io/.

2019-10-22 19:54 UTC, gkalpak commented
Thx for the clarification. SGTM. Happy to get this PR in (once all comments are resolved :wink:).

2019-10-22 20:40 UTC, sjtrimble commented
@gkalpak Is there anything missing for this PR?

2019-10-22 20:48 UTC, mary-poppins commented
You can preview 81d5340 at https://pr33259-81d5340.ngbuilds.io/.

2019-10-23 09:20 UTC, gkalpak approved these changes

2019-10-23 09:20 UTC, gkalpak commented on aio/content/guide/dependency-injection-in-action.md
> +      <img src="generated/images/guide/dependency-injection-in-action/hero-bios-and-contacts.png" alt="Bios with contact into">
```suggestion
    <img src="generated/images/guide/dependency-injection-in-action/hero-bios-and-contacts.png" alt="Bios with contact into">
```

2019-10-23 09:20 UTC, gkalpak commented on aio/content/guide/dependency-injection-in-action.md
> +      <img src="generated/images/guide/dependency-injection-in-action/minimal-logger-intellisense.png" alt="MinimalLogger restricted API">
```suggestion
    <img src="generated/images/guide/dependency-injection-in-action/minimal-logger-intellisense.png" alt="MinimalLogger restricted API">
```

2019-10-23 09:20 UTC, gkalpak commented on aio/content/start/data.md
> +   <figure class="lightbox">
```suggestion
    <figure class="lightbox">
```

2019-10-23 09:20 UTC, gkalpak commented on aio/content/start/data.md
> +    <div class="card">
```suggestion
      <div class="card">
```

2019-10-23 09:20 UTC, gkalpak commented on aio/content/start/data.md
> +      <img src='generated/images/guide/start/product-details-buy.png' alt="Display details for selected product with a Buy button">
```suggestion
        <img src='generated/images/guide/start/product-details-buy.png' alt="Display details for selected product with a Buy button">
```

2019-10-23 09:20 UTC, gkalpak commented on aio/content/start/data.md
> +    </div>
```suggestion
      </div>
```

2019-10-23 09:20 UTC, gkalpak commented on aio/content/start/data.md
> +  </figure>
```suggestion
    </figure>
```

2019-10-23 09:20 UTC, gkalpak commented on aio/content/start/data.md
>        <img src='generated/images/guide/start/cart-works.png' alt="Display cart page before customizing">
```suggestion
        <img src='generated/images/guide/start/cart-works.png' alt="Display cart page before customizing">
```

2019-10-23 09:20 UTC, gkalpak commented on aio/content/start/data.md
>        <img src='generated/images/guide/start/cart-page-full.png' alt="Cart page with products added">
```suggestion
        <img src='generated/images/guide/start/cart-page-full.png' alt="Cart page with products added">
```

2019-10-23 09:20 UTC, gkalpak commented on aio/content/start/data.md
>        <img src='generated/images/guide/start/cart-empty-with-shipping-prices.png' alt="Cart with link to shipping prices">
```suggestion
        <img src='generated/images/guide/start/cart-empty-with-shipping-prices.png' alt="Cart with link to shipping prices">
```

2019-10-23 09:20 UTC, gkalpak commented on aio/content/start/data.md
>        <img src='generated/images/guide/start/shipping-prices.png' alt="Display shipping prices">
```suggestion
        <img src='generated/images/guide/start/shipping-prices.png' alt="Display shipping prices">
```

2019-10-23 09:41 UTC, gkalpak commented
@sjtrimble, I pushed a fixup commit with some indentation fixes. If you are happy with that, feel free to mark the PR for merging (adding the `PR action: merge` and `PR action: merge-assistance` labels.

2019-10-23 09:42 UTC, gkalpak commented
@googlebot I consent.

2019-10-23 09:42 UTC, gkalpak commented
**merge-assistance:** Global approval for this docs(-infra)-only change.

2019-10-23 09:45 UTC, mary-poppins commented
You can preview 771a723 at https://pr33259-771a723.ngbuilds.io/.

2019-10-23 19:51 UTC, sjtrimble commented
Thanks @gkalpak , u da best :P

2019-10-23 19:59 UTC, closed without merging