docs: add ModuleWithProviders deprecation
angular/angular pull request #33266
Opened 2019-10-19 12:18 UTC by kapunahelewong

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Adds a section to the deprecation guide about `ModuleWithProviders`. This section also links to the migration page on the same topic.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-10-20 17:27 UTC, CaerusKaru commented on aio/content/guide/deprecations.md
> +### `ModuleWithProviders` type without a generic
Should we add this to the table above under `@angular/core`?

2019-10-20 17:27 UTC, CaerusKaru commented on aio/content/guide/deprecations.md
> +If you're using the CLI, `ng update` should [migrate your code automatically](guide/migration-module-with-providers).
Is this going to be added in a separate PR (/is this something you'd like me to contribute)?

2019-10-20 20:36 UTC, kara requested changes
A few minor things now that I look at it again

2019-10-20 20:36 UTC, kara commented on aio/content/guide/deprecations.md
> +If you're using the CLI, `ng update` should [migrate your code automatically](guide/migration-module-with-providers).
Do you mean the guide? There's a PR here:

https://github.com/angular/angular/pull/33085

2019-10-20 20:36 UTC, kara commented on aio/content/guide/deprecations.md
> +### `ModuleWithProviders` type without a generic
+1 We should add a link to this section to the index up top

2019-10-20 20:36 UTC, kara commented on aio/content/guide/deprecations.md
> +Angular version 9 deprecates use of `ModuleWithProviders` without an explicitly generic type, where the generic type refers to the type of the `NgModule`.
```suggestion
Angular version 9 deprecates use of `ModuleWithProviders` without an explicitly generic type, where the generic type refers to the type of the `NgModule`. In a future version of Angular, the generic will no longer be optional.
```

2019-10-20 20:36 UTC, kara commented on aio/content/guide/deprecations.md
> +If you're not using the CLI, you can make the change manually.
```suggestion
If you're not using the CLI, you can add any missing generic types to your application manually. 
```

2019-10-21 20:59 UTC, kara commented on aio/content/guide/deprecations.md
> +| [`ModuleWithProviders`](api/core/ModuleWithProviders) | none | v9 | See [`ModuleWithProviders`](#moduleWithProviders) |
Can you remove the diff from this section and add it to the "index" section here? https://github.com/angular/angular/blob/81f3d19c13cc9de593247bd83fce5a41d3886043/aio/content/guide/deprecations.md#index

Otherwise it looks like `ModuleWithProviders` itself is deprecated.  We want to be able to specify that it's only using `ModuleWithProviders` without a generic that's deprecated.

2019-10-22 17:36 UTC, kapunahelewong commented
Note: failing because of a link to `ModuleWithProviders` migration guide that is in https://github.com/angular/angular/pull/33085. As soon as that one is merged, and I rebase this one, it should pass.

2019-10-22 19:02 UTC, kara commented on aio/content/guide/deprecations.md
> +| `ModuleWithProviders` | [`ModuleWithProviders` without a generic](#moduleWithProviders) | v9 |
Should be moved up with the other `@angular/core` deprecations

```suggestion
| `@angular/core` | [`ModuleWithProviders` without a generic](#moduleWithProviders) | v9 |
```

2019-10-22 20:06 UTC, mary-poppins commented
You can preview 3fab0f7 at https://pr33266-3fab0f7.ngbuilds.io/.

2019-10-22 21:27 UTC, kara commented on aio/content/guide/deprecations.md
> +| `@angular/core` | [`ModuleWithProviders` without a generic](#moduleWithProviders) | v9 |
```suggestion
| `@angular/core` | [`ModuleWithProviders` without a generic](#moduleWithProviders) | v10 |
```

2019-10-22 21:30 UTC, kara commented on aio/content/guide/deprecations.md
> +Sengled Smart Wi-Fi LED Multicolor
Remove?

2019-10-22 21:34 UTC, kara approved these changes
LGTM

2019-10-22 21:35 UTC, closed without merging

2019-10-22 21:39 UTC, mary-poppins commented
You can preview 7db1323 at https://pr33266-7db1323.ngbuilds.io/.