feat(ivy): strictness flags for template type checking
angular/angular pull request #33273
Opened 2019-10-19 20:27 UTC by JoostK

**feat(ivy): strictness flags for template type checking**

The template type checking abilities of the Ivy compiler are far more
advanced than the level of template type checking that was previously
done for Angular templates. Up until now, a single compiler option
called "fullTemplateTypeCheck" was available to configure the level
of template type checking. However, now that more advanced type checking
is being done, new errors may surface that were previously not reported,
in which case it may not be feasible to fix all new errors at once.

Having only a single option to disable a large number of template type
checking capabilities does not allow for incrementally addressing newly
reported types of errors. As a solution, this commit introduces some new
compiler options to be able to enable/disable certain kinds of template
type checks on a fine-grained basis.

---

**feat(ivy): add flag to disable checking of empty attributes**

For elements that have a static attribute without a value, which is
typically the case for attributes like `disabled`, it may happen that
the element is matched by a directive that consumes the attribute as an
input. In that case, the template type checker will validate the
correctness of the attribute with respect to the directive's declared
type of the input, which would typically be `boolean` for the `disabled`
input. Since empty attributes are assigned the empty string at runtime,
the template type checker would report an error for this template.

This commit introduces a strictness flag to help alleviate this
particular situation, effectively ignoring empty attributes that happen
to be consumed by a directive.

2019-10-19 20:51 UTC, JoostK commented on packages/compiler-cli/src/transformers/api.ts
> +  /**
Unfortunately, we can't simply introduce a nested object here to collect all template type checking related flags into a single object. The reason is that `CompilerOptions` extends from `ts.CompilerOptions` which has some constraints on its index signature, which the subclass needs to adhere to.

We could probably workaround this restriction in some way but I decided to keep it simple initially.

2019-10-21 20:58 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/program.ts
> +    if (this.options.strictAnimationEventTypes !== undefined) {
I am not sure about having this flag as public flag, as it feels too specific. We may use the `strictOutputEventTypes` flag to also set `TypeCheckingConfig.checkTypeOfAnimationEvents`.

2019-10-21 21:36 UTC, alxhub commented on packages/compiler-cli/src/transformers/api.ts
> +  /**
👍

2019-10-22 17:19 UTC, kara commented on packages/compiler-cli/src/ngtsc/program.ts
> +    if (this.options.strictAnimationEventTypes !== undefined) {
Agree, let's combine them

2019-10-22 18:54 UTC, kara requested changes
Mostly comments about changing defaults to false even with TTC on.

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/ngtsc/program.ts
> +        checkTypeOfReferences: true,
The new flags should all default to `false` even with TTC on

```suggestion
        checkTypeOfReferences: false,
```

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/ngtsc/program.ts
> +    if (this.options.strictAnimationEventTypes !== undefined) {
Agree, let's combine them

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/ngtsc/typecheck/src/api.ts
> +   * up being consumed as an input with type `boolean` by the `matInput` directive. At runtime the
```suggestion
   * up being consumed as an input with type `boolean` by the `matInput` directive. At runtime, the
```

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/ngtsc/typecheck/src/api.ts
> +   * input will be set to the attribute's string value, which is the empty string for attributes
```suggestion
   * input will be set to the attribute's string value, which is an empty string for attributes
```

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/ngtsc/typecheck/src/api.ts
> +   * without a value, so with this flag set to `true` an error would be reported. If set to `false`,
```suggestion
   * without a value, so with this flag set to `true`, an error would be reported. If set to `false`,
```

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/transformers/api.ts
> +   * Defaults to `true` if "fullTemplateTypeCheck" is set, `false` otherwise.
Should default to false (needs to be changed in implementation too)

```suggestion
   * Defaults to `false` if "fullTemplateTypeCheck" is set, `false` otherwise.
```

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/ngtsc/program.ts
> +        checkTypeOfAttributes: true,
```suggestion
        checkTypeOfAttributes: false,
```

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/transformers/api.ts
> +   * Defaults to `true` if "fullTemplateTypeCheck" is set, `false` otherwise. Note that if
```suggestion
   * Defaults to `false` if "fullTemplateTypeCheck" is set, `false` otherwise. Note that if
```

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/transformers/api.ts
> +   * Defaults to `true` if "fullTemplateTypeCheck" is set, `false` otherwise.
```suggestion
   * Defaults to `false` if "fullTemplateTypeCheck" is set, `false` otherwise.
```

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/transformers/api.ts
> +   * Defaults to `true` if "fullTemplateTypeCheck" is set, `false` otherwise.
```suggestion
   * Defaults to `false` if "fullTemplateTypeCheck" is set, `false` otherwise.
```

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/transformers/api.ts
> +   * Defaults to `true` if "fullTemplateTypeCheck" is set, `false` otherwise.
```suggestion
   * Defaults to `false` if "fullTemplateTypeCheck" is set, `false` otherwise.
```

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/transformers/api.ts
> +   * Defaults to `true` if "fullTemplateTypeCheck" is set, `false` otherwise.
```suggestion
   * Defaults to `false` if "fullTemplateTypeCheck" is set, `false` otherwise.
```

2019-10-22 18:54 UTC, kara commented on packages/compiler-cli/src/transformers/api.ts
> +   */
These should all be marked deprecated as they will be removed in v11

```suggestion
@deprecated
   */
```

2019-10-23 21:45 UTC, alxhub commented
I'm going to close this just to avoid confusion, as I opened my own PR with @JoostK's commits (#33365), so I can do faster round trips and land this ASAP.

2019-10-23 21:45 UTC, closed without merging