perf(ivy): add benchmark for `[class]=exp` use case
angular/angular pull request #33309
Opened 2019-10-22 01:18 UTC by mhevery

This PR demonstrates a use case where writing to the `[class]` is much slower that direct.

```
Benchmark: class binding
  classMap: 1000.027 us(-1398%)
  classMapDirect: 66.740 us(0%)
```

This is first step in understanding the issue.

2019-10-22 06:05 UTC, IgorMinar commented on packages/core/test/render3/perf/class_binding/index.ts
> +let choseClasses = true;
```suggestion
let toggleClasses = true;
```

2019-10-23 07:15 UTC, matsko approved these changes

2019-10-23 08:38 UTC, pkozlowski-opensource commented on packages/core/test/render3/perf/class_binding/index.ts
> +import {ɵɵelement, ɵɵelementEnd, ɵɵelementStart} from '../../../../src/render3/instructions/element';
nit: `ɵɵelementStart` / `ɵɵelementEnd` imports seem unused

2019-10-23 08:38 UTC, pkozlowski-opensource commented on packages/core/test/render3/perf/class_binding/index.ts
> +import {HOST, TVIEW} from '../../../../src/render3/interfaces/view';
nit: `HOST ` import seem unused

2019-10-23 08:57 UTC, pkozlowski-opensource commented
@mhevery so the benchmark itself LGTM (in the sense of cases tested). What we should figure out, though, is presence of multiple cases in one benchmark and the `node packages/core/test/render3/perf/profile_all.js --write baseline.json` workflow.

Currently it seems to report only the first benchmark, here is the example output:

```
------------------------------------------------
PROFILING
------------------------------------------------
---------------- class_binding ----------------
Benchmark: class binding
  [class]=" '1' ": 326.413 us(-50%)
  [class]=" '1 2' ": 461.204 us(-111%)
  [class]=" '1 2 3 4 5 6 7 8 9 0' ": 1801.160 us(-726%)
  class="A B" [class]=" '1' ": 341.436 us(-57%)
  class="A B" [class]=" '1 2 3 4 5 6 7 8 9 0' ": 2112.785 us(-869%)
  class="A B" [class]=" '1' " [class.foo]="exp": 399.083 us(-83%)
  class="A B" [class]=" '1 2 3 4 5 6 7 8 9 0' " [class.foo]="exp": 2078.256 us(-853%)
  [element.class]="exp": 218.084 us(0%)
---------------- directive_instantiate ----------------
Benchmark: directive instantiate
  create: 2.569 us(0%)
---------------- element_text_create ----------------
Benchmark: element and text create
  create: 1.246 us(0%)
---------------- interpolation ----------------
Benchmark: interpolation refresh
  refresh: 227.722 us(0%)
---------------- listeners ----------------
Benchmark: listeners create
  create: 2.746 us(0%)
---------------- map_based_style_and_class_bindings ----------------
Benchmark: style and class map binding
  refresh: 20.180 ms(0%)
---------------- noop_change_detection ----------------
Benchmark: noop change detection
  refresh: 22.840 us(0%)
---------------- property_binding ----------------
Benchmark: property binding refresh
  refresh: 252.522 us(0%)
---------------- property_binding_update ----------------
Benchmark: property binding
  update: 456.747 us(0%)
---------------- style_and_class_bindings ----------------
Benchmark: style and class binding
  refresh: 1.089 ms(0%)
---------------- style_binding ----------------
Benchmark: style binding
  refresh: 481.473 us(0%)
================================================
┌────────────────────────────────────┬─────────┬──────┬───────────┬───────────┬───┐
│              (index)               │  time   │ unit │ base_time │ base_unit │ % │
├────────────────────────────────────┼─────────┼──────┼───────────┼───────────┼───┤
│           class_binding            │ 326.413 │ 'us' │           │           │   │
│       directive_instantiate        │  2.569  │ 'us' │           │           │   │
│        element_text_create         │  1.246  │ 'us' │           │           │   │
│           interpolation            │ 227.722 │ 'us' │           │           │   │
│             listeners              │  2.746  │ 'us' │           │           │   │
│ map_based_style_and_class_bindings │  20.18  │ 'ms' │           │           │   │
│       noop_change_detection        │  22.84  │ 'us' │           │           │   │
│          property_binding          │ 252.522 │ 'us' │           │           │   │
│      property_binding_update       │ 456.747 │ 'us' │           │           │   │
│      style_and_class_bindings      │  1.089  │ 'ms' │           │           │   │
│           style_binding            │ 481.473 │ 'us' │           │           │   │
└────────────────────────────────────┴─────────┴──────┴───────────┴───────────┴───┘
```

Notice that in the output table `class_binding` reports results of the first run (`[class]=" '1' "`). I presume that we either want to report all results or have the reported one being "the most representative". We can do this in the follow up PR, somehow I'm leaning towards reporting all cases, but would love to have your thoughts here.

.

2019-10-23 08:57 UTC, pkozlowski-opensource approved these changes
LGTM overall but there is a bit of cleanup needed.

2019-10-23 09:10 UTC, pkozlowski-opensource commented on packages/core/test/render3/perf/class_binding/index.ts
> +benchmark(`[class]=" '1' "`, function(rf: RenderFlags, ctx: any) {
nit: names of those benchmarks are misleading since they suggest that we don't change classes. Do you think we could:
* adjust names to better reflect what we do?
* have a comment with a template string (as written by a user)?

2019-10-23 20:51 UTC, mhevery commented on packages/core/test/render3/perf/class_binding/index.ts
> +import {ɵɵelement, ɵɵelementEnd, ɵɵelementStart} from '../../../../src/render3/instructions/element';
fixed

2019-10-23 20:52 UTC, mhevery commented
> @mhevery so the benchmark itself LGTM (in the sense of cases tested). What we should figure out, though, is presence of multiple cases in one benchmark and the `node packages/core/test/render3/perf/profile_all.js --write baseline.json` workflow.

I am aware of this. I will do a follow up PR to fix that issue. I wanted to re-do the whole thing anyways.

2019-10-23 20:52 UTC, mhevery commented on packages/core/test/render3/perf/class_binding/index.ts
> +import {HOST, TVIEW} from '../../../../src/render3/interfaces/view';
fixed

2019-10-23 23:35 UTC, mhevery commented on packages/core/test/render3/perf/class_binding/index.ts
> +benchmark(`[class]=" '1' "`, function(rf: RenderFlags, ctx: any) {
done

2019-10-24 08:54 UTC, pkozlowski-opensource approved these changes

2019-10-24 09:00 UTC, pkozlowski-opensource commented on packages/core/test/render3/perf/setup.ts
> +  function detectChanges(): void { renderView(hostLView, hostTView, null); }
I think that the `detectChanges` name is misleading here as we just create a view without change detecting it (we are just doing creation mode pass).

2019-10-24 10:13 UTC, pkozlowski-opensource requested changes
@mhevery it seems like you've changed this PR from my last review and after looking at the latest changes I think there is a misunderstanding between the `renderView` and `refreshView` functions.

In the current code base:
* `renderView` = creation mode _only_
* `refreshView` = update mode _only_

I believe that your intention was to use  `refreshView` [here](https://github.com/angular/angular/pull/33309/files#diff-4aeb2278790dcd45440ad9985c1d7f96R69)

I've pushed a [fixup commit](https://github.com/pkozlowski-opensource/angular/commit/50ef31be0a3272269c83252927356fdd75cb86ad) to [my branch](https://github.com/pkozlowski-opensource/angular/tree/style_review_cleanup) - I didn't want to push to your branch as I wanted to clarify the intention with you first.  I can update your branch when I'm sure that we are on the same page.

2019-10-24 17:58 UTC, mhevery commented
Closing in favor of https://github.com/angular/angular/pull/33375

2019-10-24 18:04 UTC, closed without merging