docs(contributors): added GDE profile of Fabian Gosebrink
angular/angular pull request #33438
Opened 2019-10-28 04:31 UTC by FabianGosebrink

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:

Added GDE Profile of Fabian Gosebrink 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-10-29 13:24 UTC, Splaktar reviewed
I think that just `docs: ...` is good for the commit message. I don't think that `docs-infra` should be used.

You can just reword the commit message and force push the update.

2019-10-29 17:57 UTC, kapunahelewong commented on aio/content/marketing/contributors.json
> +    "bio": "Fabian Gosebrink is Google Developer Expert for Angular and Web Technologies, Microsoft MVP and Web Developer for ASP.NET Core and Angular. As a professional software engineer, consultant
```suggestion
    "bio": "Fabian Gosebrink is a Google Developer Expert for Angular and Web Technologies, Microsoft MVP and Web Developer for ASP.NET Core and Angular. As a professional software engineer, consultant and trainer, he advises and supports customers in the implementation of frontend, backend, and mobile development of web applications."
```
These edits are by no means required, take them only if you agree wit them. 😊

2019-10-29 18:08 UTC, kapunahelewong commented
Hi @FabianGosebrink, this commit message should work ok:
```
docs: add GDE profile of Fabian Gosebrink
```

2019-10-29 20:30 UTC, Splaktar commented
Yeah, it can be a little bit confusing and I agree that scope was the closest, but it looks good now!

The only thing left to do is to squash your commits, [instructions](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) (from @kapunahelewong).

2019-10-29 21:57 UTC, FabianGosebrink commented on aio/content/marketing/contributors.json
> +    "bio": "Fabian Gosebrink is Google Developer Expert for Angular and Web Technologies, Microsoft MVP and Web Developer for ASP.NET Core and Angular. As a professional software engineer, consultant
Perfect, thanks!

2019-10-29 22:29 UTC, Splaktar approved these changes
LGTM

2019-10-31 18:46 UTC, StephenFluin approved these changes

2019-11-01 16:14 UTC, kapunahelewong approved these changes

2019-11-01 17:47 UTC, atscott commented
@FabianGosebrink could you please rebase this PR and resolve the conflict? Thanks.

2019-11-01 18:40 UTC, Splaktar requested changes

2019-11-01 18:40 UTC, Splaktar commented on aio/content/marketing/contributors.json
> +  },
This merge removed `"groups": ["GDE"]` from Mike Brocchi's profile. It needs to be added back 😄

2019-11-01 18:41 UTC, FabianGosebrink commented on aio/content/marketing/contributors.json
> +  },
Yes, I know...sorry!!!

2019-11-01 18:50 UTC, FabianGosebrink commented
Sorry for removing the GDE Group from Mike. That was not on purpose. Sorry, was a merge mistake.

2019-11-01 20:00 UTC, Splaktar requested changes
Brocchi's groups look good now 👍

2019-11-01 23:26 UTC, kapunahelewong commented on aio/content/marketing/contributors.json
> +  "FabianGosebrink": {
I took the liberty of fixing this for him.

2019-11-01 23:29 UTC, kapunahelewong commented
I fixed the duplication, rebased, fixed the conflict, and also fixed a small spacing issue in the entry above.

2019-11-02 00:53 UTC, closed without merging