feat(ivy): graceful evaluation of unknown or invalid expressions
angular/angular pull request #33453
Opened 2019-10-28 22:14 UTC by JoostK

During static evaluation of expressions within ngtsc, it may occur that
certain expressions or just parts thereof cannot be statically
interpreted for some reason. The static interpreter keeps track of the
failure reason and the code path that was evaluated by means of
`DynamicValue`, which will allow descriptive errors. In some situations
however, the static interpreter would throw an exception instead,
resulting in a crash of the compilation. Not only does this cause
non-descriptive errors, more importantly does it prevent the evaluated
result from being partial, i.e. parts of the result can be dynamic if
their value does not have to be statically available to the compiler.

This commit refactors the static interpreter to never throw errors for
certain expressions that it cannot evaluate.

Resolves FW-1582

2019-10-29 16:25 UTC, gkalpak commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
> +        return undefined;
Maybe just remove this `if` block?

2019-10-31 20:35 UTC, alxhub requested changes

2019-10-31 20:35 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/dynamic.ts
> +  UNKNOWN_OPERATOR,
I'd rather the `DynamicValue` types not be quite so granular. How about we introduce `UNSUPPORTED_SYNTAX` instead?

2019-10-31 20:35 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/dynamic.ts
> +  INVALID_SPREAD_ELEMENT,
`INVALID_EXPRESSION_TYPE` covers this case.

2019-10-31 21:46 UTC, alxhub approved these changes

2019-10-31 23:12 UTC, atscott commented
[presubmit](http://test/OCL:277821537:BASE:277821614:1572563273935:a801aa46)
[ivy presubmit](http://test/OCL:277821537:BASE:277821898:1572563364353:a171f98d)

2019-11-01 00:04 UTC, closed without merging