Unknown pipe & local ref diagnostics
angular/angular pull request #33454
Opened 2019-10-28 22:30 UTC by alxhub

2019-10-29 21:59 UTC, JoostK requested changes

2019-10-29 21:59 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> + * Collects reports on template diagnostics which are
Incomplete comment

2019-10-29 21:59 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +    const errorMsg = `No directive found with exportAs '${value}'.`;
For future consideration: have an intuitive way of visualising the module scope/available directive exports to better indicate what needs to happen to resolve this diagnostic. Because it's a non-local issue, how to fix it is not straightforward (and one of the areas I would like to see Angular become better is in error reporting!)

2019-10-29 21:59 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      this.checkReferencesOfNode(node);
I am surprised you took this approach, intertwining the reporting of missing refs with the generation of TCBs, instead of adding some diagnostic reporting facility to `R3TargetBinder` itself.

2019-10-29 21:59 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +        this.tcb.oobRecorder.missingReferenceTarget(this.tcb.id, binding);
I am under the impression that reporting this both here and in `checkReferencesOfNode` is not ideal and may introduce the same diagnostic twice. 

For instance:

```html
<div dir #ref="nonexistent">{{ ref.value }}</div>
```

This will create two diagnostics with identical message but different spans, if I'm not mistaken:
```html
<div dir #ref="nonexistent">{{ ref.value }}</div>
         ^~~~~~~~~~~~~~~~~~    ^~~
```
Both have the message `No directive found with exportAs 'nonexistent'.`. For the first diagnostics this message makes sense, for the second it does not.

2019-10-29 21:59 UTC, JoostK commented on packages/compiler/src/render3/view/t2_binder.ts
> +          // No matching directive was found - this reference points to an unknown target.
There's a comment on L263 that mentions "One should exist.", this is now outdated.

Also, this is the place where I expected some error reporting mechanism to be used, instead of in the TCB generation code.

2019-10-29 21:59 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/diagnostics.ts
> +export function absoluteSourceSpanToSourceLocation(
Hmm, maybe we should just decompose `TcbSourceResolver.sourceLocationToSpan` to receive two arguments instead of the `SourceLocation` bundle.

2019-10-29 21:59 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +      throw new Error(`Could not map location for error`);
Pretty cryptic error message ;)

2019-10-29 21:59 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +  missingPipe(id: string, ast: BindingPipe, sourceSpan: AbsoluteSourceSpan): void;
I now realize that `id` corresponds with the TCB id, not some pipe id which the function name suggests. These methods could use docs.

2019-10-29 21:59 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      const nameAbsoluteSpan = toAbsoluteSpan(ast.nameSpan, this.sourceSpan);
Move `nameAbsoluteSpan` into the `if (pipe === null)` below

2019-10-29 21:59 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
>  export function generateTypeCheckBlock(
I think we should make clear that this function has a side-effect when it comes to producing diagnostics. Having the _out of bands_ parameter does indicate this somewhat, but it could be made more explicit. Come to think of it, it would be a good idea for future reference to document `OutOfBandDiagnosticRecorder` on why it exists and how it's used.

2019-10-30 20:59 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +    const errorMsg = `No directive found with exportAs '${value}'.`;
I completely agree. One of the goals of having the centralized `ErrorCode` for Angular errors was to keep track of the different classes of errors and make it easier for us to set goals of improving them.

2019-10-30 21:07 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      this.checkReferencesOfNode(node);
I considered this, actually. Part of the problem is that the way we map expressions back into the original template source depends a lot on the way we traverse the template. This doesn't matter for `Reference`s which are a top level concept and have proper source spans, but for `BindingPipe`s which are an `AST` node, the source mapping depends on the context and the `R3TargetBinder` doesn't currently deal with those concerns.

Ultimately we might refactor in this direction. Especially because the HTML-level template parsing errors are not currently surfaced via our "nice" diagnostics mechanism.

2019-10-30 21:20 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +        this.tcb.oobRecorder.missingReferenceTarget(this.tcb.id, binding);
Very good point! Fixed.

2019-10-30 21:21 UTC, alxhub commented on packages/compiler/src/render3/view/t2_binder.ts
> +          // No matching directive was found - this reference points to an unknown target.
Good catch, fixed.

2019-10-30 21:22 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/diagnostics.ts
> +export function absoluteSourceSpanToSourceLocation(
I'm all for refactoring this to clean it up :)

2019-10-30 21:51 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
>  export function generateTypeCheckBlock(
Done. I updated and expanded the comment to talk about the verifications which happen during generation.

As mentioned above, I think the "right way" to do this is to refactor the template traversal to be independent of everything, and hang various operations off of this central traversal, including both the verification diagnostics and TCB generation.

2019-10-30 21:55 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      const nameAbsoluteSpan = toAbsoluteSpan(ast.nameSpan, this.sourceSpan);
Done.

2019-10-30 21:55 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +  missingPipe(id: string, ast: BindingPipe, sourceSpan: AbsoluteSourceSpan): void;
Renamed to `templateId`, and added docs.

2019-10-30 21:56 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +      throw new Error(`Could not map location for error`);
Updated :)

2019-10-30 21:56 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> + * Collects reports on template diagnostics which are
Completed comment.

2019-10-30 22:05 UTC, alxhub commented
[Presubmit](http://test/OCL:277592991:BASE:277593080:1572473092181:613f68f7)
Ivy Presubmit not needed: does not affect generated code, no new errors

2019-10-30 22:14 UTC, JoostK approved these changes
Just some more nits, otherwise LGTM

2019-10-30 22:14 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +   * @param templateId the template type-cehcking ID of the template which contains the unknown
```suggestion
   * @param templateId the template type-checking ID of the template which contains the unknown
```

2019-10-30 22:14 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +  missingPipe(id: string, ast: BindingPipe, sourceSpan: AbsoluteSourceSpan): void;
You seem to have missed the actual param name in the interface here:

```suggestion
  missingPipe(templateId: string, ast: BindingPipe, sourceSpan: AbsoluteSourceSpan): void;
```

2019-10-30 22:14 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +          //
Remove empty comment (or make it count :))

2019-10-31 23:43 UTC, closed without merging

2019-11-04 11:19 UTC, danielehrhardt commented
When do you plan to release it?