Entering change detection from the creation mode
angular/angular pull request #33463
Opened 2019-10-29 11:31 UTC by pkozlowski-opensource

Fixes #32756

2019-10-29 11:31 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/change_detection_spec.ts
> -    it('should support re-enterant change detection', () => {
note to a reviewer: this test was not deleted, just moved to another place

2019-10-29 11:34 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +  if (isCreationMode(view)) return;
So, I'm not sure if this "fix" is correct - we should probably ponder more what calling `ChangeDetectorRef.detectChanges()` from the creation mode means:
* should it be `noop`? 
* schedule CD at some "later point in time"?  
* what is VE doing here?

Also, if this is noop, should we log any warning in the dev mode?

2019-10-29 17:49 UTC, mhevery requested changes

2021-02-16 05:59 UTC, AndrewKushnir commented
Closing this PR for now based on https://github.com/angular/angular/pull/33463#discussion_r340232827, please reopen if needed. Thank you.

2021-02-16 05:59 UTC, closed without merging