Add elements project type for boilerplate sample projects
angular/angular pull request #33484
Opened 2019-10-30 03:13 UTC by yallen011

Added elements project type to the boilerplate sample projects to fix the issue with the angular elements example project in the Angular docs throwing error due to the angular elements package not being present in the `package.json` file when the zip file is downloaded.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #31332 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-10-30 03:45 UTC, yallen011 commented
@googlebot I fixed it.

2019-11-11 09:23 UTC, mary-poppins commented
You can preview 47d859d at https://pr33484-47d859d.ngbuilds.io/.
You can preview 8c0699d at https://pr33484-8c0699d.ngbuilds.io/.
You can preview 61c9fe8 at https://pr33484-61c9fe8.ngbuilds.io/.
You can preview 66e1a17 at https://pr33484-66e1a17.ngbuilds.io/.

2019-11-11 09:27 UTC, petebacondarwin approved these changes
Great first PR @yallen011 !!

One small change please. In the commit message you don't need to add the `PR Close #31332` line.
Our merge script will add this line with a link back to this PR. Please can change that line in your commit message to

```
Fixes #31332
```

2019-11-11 12:04 UTC, gkalpak requested changes
Thx, @yallen011 ✨
I left a couple more comments, but otherwise this lgtm 👍

2019-11-11 12:04 UTC, gkalpak commented on aio/tools/examples/shared/boilerplate/elements/angular.json
> +{
This file shouldn't be needed, since it is identical to the [default one][1].

[1]: https://github.com/angular/angular/blob/66e1a1769/aio/tools/examples/shared/boilerplate/cli/angular.json

2019-11-11 12:04 UTC, gkalpak commented on aio/tools/examples/shared/boilerplate/elements/package.json
> +{
Please keep this file the same as the [default package.json][1], with the exception of having `@angular/elements` as an extra dependency.

[1]: https://github.com/angular/angular/blob/66e1a1769/aio/tools/examples/shared/boilerplate/cli/package.json

2019-11-13 03:47 UTC, yallen011 commented
Ok, I will make the changes and resubmit.

2019-11-16 01:14 UTC, yallen011 commented
@gkalpak Updated pr to reflect requested changes. 

Thanks for giving such a detailed explanation for the proposed fix, which ultimately allowed me to fix the issue with only minimal changes needed after the initial review. Your explanation of how to fix the issue was also the reason I will soon be able to say that I have contributed to Angular, which has been a goal of mine for quite some time. So thank you very much...You ROCK!!!!

2019-11-16 01:18 UTC, mary-poppins commented
You can preview c082cf0 at https://pr33484-c082cf0.ngbuilds.io/.

2019-11-18 12:35 UTC, gkalpak requested changes
One minor comment, but otherwise lgtm :tada:
Also, please, update the commit message (which is already in a pretty good form) to more closely follow [our guidelines][1]:

> fix(docs-infra): add boilerplate path and project type for elements example project
>
> Fixes #31332

[1]: https://github.com/angular/angular/blob/a48573efe/CONTRIBUTING.md#commit

2019-11-18 12:35 UTC, gkalpak commented on aio/tools/examples/shared/boilerplate/elements/package.json
> +    "@angular/core": "^8.0.0",
Incorrect aplhabetic order: `core` should be above `elements` :smiley:

2019-11-18 12:36 UTC, gkalpak commented
Oh, also, please rebase on master to make CI green.

2019-11-19 03:15 UTC, yallen011 commented
Hi @gkalpak I read the doc for the commit message again, but I'm not sure what needs to be modified.

2019-11-19 09:28 UTC, gkalpak commented
I've included a suggested commit message in my previous comment :smiley: https://github.com/angular/angular/pull/33484#pullrequestreview-318296223

2019-11-19 09:52 UTC, gkalpak commented
BTW, it seems you also need to rebnase on master to make CI green. (You can follow the instructions in https://github.com/angular/angular/pull/33829#issuecomment-555417299.)

2019-11-19 13:52 UTC, yallen011 commented
Ok, I see. I misread the comment asking me to change `Closes` to `Fixes` I read it as remove that part all together. I will update code and comment then rebase.

2019-11-19 16:11 UTC, gkalpak commented
Both `Closes` and `Fixes` ([and a few others][1]) work. The important part is to include it on a new on its own, at the bottom of the commit message, separated by an empty line from the rest of the message.

The current commit message is:

> fix(docs-infra): add boilerplate path and project type for elements example project (#31332)

My suggestion is to change it to:

> fix(docs-infra): add boilerplate path and project type for elements example project
>
> Fixes #31332

##
(LMK if you run into difficulties updating the commit message or rebasing. Thx again for working on this 👍)

[1]: https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references

2019-11-19 16:23 UTC, yallen011 commented
@gkalpak that's the way I had it at first. On a new line at the bottom of the commit message.

2019-11-19 17:04 UTC, gkalpak commented
@yallen011, according to GitHub [this is the initial PR commit][1] 🤷‍♂
Maybe something got messed up during rebasing/amending?


[1]: https://github.com/angular/angular/commit/47d859d377fa5fcd89d1e62933c7c9a90a258c2d

2019-11-22 04:23 UTC, yallen011 commented
ok, updated changes and forced pushed to kick off CI job

2019-11-22 04:28 UTC, mary-poppins commented
You can preview 1728e63 at https://pr33484-1728e63.ngbuilds.io/.

2020-03-06 04:45 UTC, ajitsinghkaler commented
@gkalpak I think this commit is ready to merge can you please have a look

2020-03-06 11:40 UTC, gkalpak approved these changes
Thx for making the changes, @yallen011! LGTM ✨
I've totally missed that I needed to re-review this. Thx for the ping, @ajitsinghkaler :+1:

2020-03-06 17:36 UTC, matsko commented
@yallen011 please rebase.

2020-03-10 11:41 UTC, gkalpak commented
_Rebased on master._

2020-03-10 11:51 UTC, mary-poppins commented
You can preview 4b8f7fe at https://pr33484-4b8f7fe.ngbuilds.io/.

2020-03-10 21:27 UTC, AndrewKushnir commented
@gkalpak do we need to update Angular package versions from `^8.0.0` to `^9.0.0`?

2020-03-11 10:48 UTC, gkalpak commented
@AndrewKushnir, this should be merged as is (to be consistent with the rest of the examples). I am updating the examples to v9/Ivy in #34374.

2020-03-11 18:53 UTC, closed without merging