docs: Adding Doug Parker to contributors list.
angular/angular pull request #33516
Opened 2019-10-31 17:55 UTC by dgp1130

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

I am not in the contributors list.

Issue Number: N/A

## What is the new behavior?

I am now in the contributors list.

## Does this PR introduce a breaking change?

- [ ] Yes
- [C] No

## Other information

I listed Igor as my lead, though I'm honestly not sure what that means, so let me know if I should use someone else.

2019-10-31 18:18 UTC, StephenFluin requested changes
@dgp1130 I think you combined two unrelated changes into this PR. Can you revert the docs change so and submit it as a different PR so we can approve them independently?

2019-10-31 18:19 UTC, StephenFluin commented
Also, if you can shrink the photo to around ~20kb, that would be great.

2019-10-31 18:20 UTC, dgp1130 commented
Just reverted it, apologies about that. I made a new branch but then forgot to switch to it before making the changes. 🤦‍♂

2019-10-31 18:25 UTC, gkalpak reviewed
Can you please remove the unrelated commits (`git revert` is not enough, because they will still show up in the main branches git history - you have to entirely remove the commits).

2019-10-31 18:25 UTC, gkalpak commented on aio/content/marketing/contributors.json
> +    "bio": "Doug is an overly-opionated software developer with a passion for making awesome developer tools. He is motivated primarily by his selfish desire to make his own life easier, but loves to
> overly-opionated

Did you, by any chance, mean _"overly-op**in**ionated"_? :grin:

2019-10-31 18:31 UTC, dgp1130 commented on aio/content/marketing/contributors.json
> +    "bio": "Doug is an overly-opionated software developer with a passion for making awesome developer tools. He is motivated primarily by his selfish desire to make his own life easier, but loves to
Done, thanks for catching that.

2019-10-31 18:51 UTC, dgp1130 commented
Reduced the file size of the photo, dropped the two unrelated commits, and squashed them all together. I've used Git in a solo manner before, but am still learning how PRs work with it.

2019-10-31 18:54 UTC, StephenFluin approved these changes

2019-11-04 20:08 UTC, gkalpak approved these changes

2019-11-05 00:55 UTC, closed without merging