Locale global umd 2
angular/angular pull request #33523
Opened 2019-10-31 21:51 UTC by petebacondarwin

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-11-01 08:19 UTC, alfaproject commented on packages/common/locales/global/af-NA.js
> +  const u = undefined;
I'm fairly certain that the compression is better if you don't capture `undefined`

2019-11-01 08:30 UTC, petebacondarwin commented on packages/common/locales/global/af-NA.js
> +  const u = undefined;
Yeah, this is a bit of strange one. It was originally added here https://github.com/angular/angular/pull/23265.
Not 100% sure behind the reasoning for using a constant `u`. 
Perhaps @ocombe can explain?

2019-11-01 08:50 UTC, ocombe commented on packages/common/locales/global/af-NA.js
> +  const u = undefined;
So initially it was because we removed the undefined values in the arrays (because they are not necessary): `[1, , ,3]` is valid, and the files were smaller
But then some people complained that it was causing errors in their linting or something like that, so we were forced to re-add the undefined values
We did some comparisons and since all the files are independent (they are not always bundled, some people lazy load them), it was smaller to just defined a constant equal to undefined.
Since them the compilers might have gotten smarter, maybe it isn't necessary anymore, you can try and benchmark that :)

2019-11-01 08:55 UTC, petebacondarwin commented on packages/common/locales/global/af-NA.js
> +  const u = undefined;
Thanks @ocombe for the explanation. Data is king! We should indeed measure it.

As it turns out this PR is generating JS files that will not be further processed, so I am thinking that the generation of those files should go through terser to get them as compact as possible.

2019-11-01 09:07 UTC, trotyl commented on tools/gulp-tasks/cldr/extract.js
> +           .replace(toRegExp('if(typeof n==="string")n=parseInt(n,10);'), '')
Any reason for checking `string` given the only allowed type is `number`?

2019-11-01 09:08 UTC, ocombe commented
Yes, but it's also nice to be able to open the files and see the content,
which is not possible if it's all minified...

>

2019-11-01 09:12 UTC, petebacondarwin commented on tools/gulp-tasks/cldr/extract.js
> +           .replace(toRegExp('if(typeof n==="string")n=parseInt(n,10);'), '')
Note that this replacement is "removing" that check. It is in the original CLDR function and we are removing it here.

2019-11-01 09:17 UTC, petebacondarwin commented
@ocombe these files are pretty obscure even when they are not minified :-)

2019-11-01 12:57 UTC, clydin commented
This appears to address all the concerns I had.  I’ll give it a more thorough review today but nice job putting this together.

2019-11-01 13:12 UTC, petebacondarwin commented on tools/gulp-tasks/cldr/extract.js
> + * Generate file that contains all locale data stored in a global
Oops this jsdoc is on the wrong function.

2019-11-01 17:57 UTC, mhevery requested changes
Minor comments, LGTM otherwise.

2019-11-01 17:57 UTC, mhevery commented on tools/gulp-tasks/cldr/extract.js
> +  const root = typeof globalThis !== 'undefined' && globalThis || typeof global !== 'undefined' && global || typeof window !== 'undefined' && window;
Could we re-arrange this code slightly?
```
(function (global) {
  global.ng = global.ng || {};
 ...
})(typeof globalThis !== 'undefined' && globalThis || typeof global !== 'undefined' && global || typeof window !== 'undefined' && window);
```

2019-11-01 17:57 UTC, mhevery commented on tools/gulp-tasks/cldr/extract.js
> +      .pipe(format.format('file', clangFormat))
I see that you are doing `clang-format` here, but I don't see the output file actually being formatted. Something is going on here.

2019-11-01 17:57 UTC, mhevery commented on tools/gulp-tasks/cldr/extract.js
> +      objectValues(dayPeriods.format.narrow), objectValues(dayPeriods.format.abbreviated),
Why did the formatting changed here?

2019-11-01 17:57 UTC, mhevery commented on tools/gulp-tasks/cldr/extract.js
> +    objectValues(dayPeriods.format.narrow), objectValues(dayPeriods.format.abbreviated),
same here

2019-11-01 17:57 UTC, mhevery commented on tools/gulp-tasks/cldr/extract.js
> +    objectValues(dayNames.format.narrow), objectValues(dayNames.format.abbreviated),
all of these formattings have changed..

2019-11-01 17:57 UTC, mhevery commented on tools/gulp-tasks/cldr/extract.js
> +      localeData.get(`supplemental/weekData/weekendStart/${localeData.attributes.territory}`) ||
Maybe move all of the formating changes in separate SHA? Its hard to know what is just re-format and what is actual change.

2019-11-01 17:57 UTC, mhevery commented on packages/common/locales/global/af-NA.js
> +  const u = undefined;
👍 for just inlining `undefined` and not trying to be compressor.
👍 for going through `terser`

2019-11-01 17:57 UTC, mhevery commented on packages/common/locales/global/af-NA.js
> +(function() {
I am a bit confused, from your other code it seems this has gone through `clang-format` but the output does not seem to be formatted. What is going on?

2019-11-01 17:57 UTC, mhevery commented on packages/common/src/i18n/locale_data_api.ts
> +import {ɵCurrencyIndex, ɵExtraLocaleDataIndex, ɵLocaleDataIndex, ɵfindLocaleData, ɵgetLocalePluralCase} from '@angular/core';
This file contains a lot of changes which just prefix `ɵ` so it looks like many things even though it is really noop. Could we change the import to say `ɵfindLocaleData as findLocaleData` that way most of these changes could go away?

2019-11-01 17:57 UTC, mhevery commented on packages/common/src/i18n/locale_data_api.ts
> +        `Missing extra locale data for the locale "${data[ɵLocaleDataIndex.LocaleId]}". Use "registerLocaleData" to load new data. See the "I18n guide" on angular.io to know more.`);
Did you mean to change the error text as well???

2019-11-01 17:57 UTC, mhevery commented on packages/common/test/i18n/format_date_spec.ts
> +import {ɵDEFAULT_LOCALE_ID, ɵunregisterLocaleData, ɵregisterLocaleData} from '@angular/core';
same here, import as to have less changes in file.

2019-11-01 17:57 UTC, mhevery commented on packages/common/test/i18n/format_number_spec.ts
> +import {ɵDEFAULT_LOCALE_ID, ɵunregisterLocaleData, ɵregisterLocaleData} from '@angular/core';
import as to have fewer changes in file.

2019-11-01 17:57 UTC, mhevery commented on packages/common/test/i18n/locale_data_api_spec.ts
> +import {ɵregisterLocaleData, ɵunregisterLocaleData} from '@angular/core';
same here

2019-11-01 17:57 UTC, mhevery commented on packages/common/test/i18n/localization_spec.ts
> +import {LOCALE_ID, ɵunregisterLocaleData, ɵregisterLocaleData} from '@angular/core';
and here

2019-11-01 17:57 UTC, mhevery commented on packages/common/test/pipes/date_pipe_spec.ts
> +import {ɵunregisterLocaleData, ɵregisterLocaleData} from '@angular/core';
here

2019-11-01 17:57 UTC, mhevery commented on packages/common/test/pipes/number_pipe_spec.ts
> +import {ɵunregisterLocaleData, ɵregisterLocaleData} from '@angular/core';
here as well

2019-11-01 17:57 UTC, mhevery commented on packages/core/src/i18n/locale_data_api.ts
> +  Object.keys(LOCALE_DATA).forEach(key => delete LOCALE_DATA[key]);
can't we just do `LOCALE_DATA = {}` to reset it?
(you may need to move this function to `locale_data.ts`)

2019-11-01 17:57 UTC, mhevery commented on packages/core/test/i18n/locale_data_api_spec.ts
> +      delete global.ng.common.locale;
instead of `delete` could we just set `locale = undefined`? I know it is test, but `delete` has all kinds of bad perf implications for the VM, and I would just prefer we just don't use it anywhere so that we have good example for other code which may end up being in production.

2019-11-01 17:58 UTC, petebacondarwin commented on tools/gulp-tasks/cldr/extract.js
> +const DEFAULT_RULE = 'function anonymous(n) {\nreturn"other"\n}';
This is because the function string that is generated from the CLDR data uses the name `anonymous` which we then replace.

2019-11-01 17:58 UTC, petebacondarwin commented on tools/gulp-tasks/cldr/extract.js
> +  const root = typeof globalThis !== 'undefined' && globalThis || typeof global !== 'undefined' && global || typeof window !== 'undefined' && window;
OK

2019-11-01 18:00 UTC, petebacondarwin commented on tools/gulp-tasks/cldr/extract.js
> +      .pipe(format.format('file', clangFormat))
I made a conscious choice not to clang the JS files since it just makes them larger. Since they are already JS they will receive no further processing and so it seemed sensible to keep the size of these files down.

2019-11-01 18:00 UTC, petebacondarwin commented on tools/gulp-tasks/cldr/extract.js
> +      objectValues(dayPeriods.format.narrow), objectValues(dayPeriods.format.abbreviated),
Clang being run  on save by VS Code.

2019-11-01 18:03 UTC, petebacondarwin commented on packages/common/src/i18n/locale_data_api.ts
> +import {ɵCurrencyIndex, ɵExtraLocaleDataIndex, ɵLocaleDataIndex, ɵfindLocaleData, ɵgetLocalePluralCase} from '@angular/core';
The current situation is inconsistent with some variables using the barred-o prefix and some being aliased to remove them. I chose to change all the use of such private imports with out aliasing:

* it improves consistency
* it makes it clear that these are private APIs that we are using

So this would be a one-off change as part of this commit's refactor.

2019-11-01 18:04 UTC, petebacondarwin commented on packages/common/src/i18n/locale_data_api.ts
> +        `Missing extra locale data for the locale "${data[ɵLocaleDataIndex.LocaleId]}". Use "registerLocaleData" to load new data. See the "I18n guide" on angular.io to know more.`);
The change here is inside a back-ticked substitution so the barred-O will not be seen in the error message.

2019-11-01 18:05 UTC, petebacondarwin commented on packages/core/src/i18n/locale_data_api.ts
> +  Object.keys(LOCALE_DATA).forEach(key => delete LOCALE_DATA[key]);
Oh yes! I just copied the deletion over from when it was in the tests and we didn't have access to just rewrite the variable.

2019-11-01 18:08 UTC, petebacondarwin commented on packages/core/test/i18n/locale_data_api_spec.ts
> +      delete global.ng.common.locale;
I used delete because it also has the effect of removing the key from the container.
But I realise that we only check `global.ng.common.locale !== undefined` anyway so happy to change :-)

2019-11-01 18:55 UTC, IgorMinar commented on tools/gulp-tasks/cldr/extract.js
> +  root.ng.common.locale = root.ng.common.locale || {};
the namespace should be "locales" not "locale". Can you please fix?
```suggestion
  root.ng.common.locale = root.ng.common.locales || {};
```

2019-11-01 18:55 UTC, IgorMinar commented on tools/gulp-tasks/cldr/extract.js
> +  root.ng.common.locale = root.ng.common.locale || {};
this is because the ESM entry point is `@angular/common/locales`

2019-11-01 18:58 UTC, petebacondarwin commented on tools/gulp-tasks/cldr/extract.js
> +  root.ng.common.locale = root.ng.common.locale || {};
👍

2019-11-01 19:17 UTC, clydin commented on packages/common/locales/BUILD.bazel
> +    srcs = glob(["global/*.js"]) + ["package.json"],
Does the package.json with the side effects flag work as intended?  I remember there were some issues with it in the localize package.

2019-11-02 18:55 UTC, petebacondarwin commented on packages/common/locales/global/af-NA.js
> +  const u = undefined;
I'll add a commit.

2019-11-02 18:56 UTC, petebacondarwin commented on tools/gulp-tasks/cldr/extract.js
> +      .pipe(format.format('file', clangFormat))
Since I am going to add a commit to pass these files through terser before adding to the npm package, I will actually format them with clang after generation.

2019-11-02 18:57 UTC, petebacondarwin commented on tools/gulp-tasks/cldr/extract.js
> +      objectValues(dayPeriods.format.narrow), objectValues(dayPeriods.format.abbreviated),
I have moved the clang formatting here to a separate commit

2019-11-02 18:58 UTC, petebacondarwin commented on packages/common/locales/global/af-NA.js
> +(function() {
The JS was not being formatted because it was planned to send it straight to the distributable - but now it will be passed through terser - so we will now format the generated files that are checked in.

2019-11-02 18:59 UTC, petebacondarwin commented on packages/common/src/i18n/locale_data_api.ts
> +        `Missing extra locale data for the locale "${data[ɵLocaleDataIndex.LocaleId]}". Use "registerLocaleData" to load new data. See the "I18n guide" on angular.io to know more.`);
In case you were referring to `registerLocaleData()` - this is still a public function from `@angular/common` and so it is correct not to rename this one.

2019-11-02 19:07 UTC, petebacondarwin commented on packages/core/src/i18n/locale_data_api.ts
> +export function unregisterLocaleData() {
Done

2019-11-02 19:10 UTC, petebacondarwin commented on packages/common/locales/BUILD.bazel
> +    srcs = glob(["global/*.js"]) + ["package.json"],
`"sideEffects": false` indicates to webpack that all files in the package are side-effect free.
Obviously this is not true for the `global` files (`closure-locale.js`) but since they will not be bundled via webpack it makes no difference.

2019-11-02 19:38 UTC, clydin commented on packages/common/locales/BUILD.bazel
> +    srcs = glob(["global/*.js"]) + ["package.json"],
Technically these files could be imported directly in application code (polyfills file, for instance) and function as intended. Assuming the bundler didn't remove them due to a perceived lack of side effects.

2019-11-02 19:45 UTC, petebacondarwin commented on packages/common/locales/BUILD.bazel
> +    srcs = glob(["global/*.js"]) + ["package.json"],
Could they be imported? They are not modules... Does webpack support importing plain JS files?

2019-11-02 19:53 UTC, clydin commented on packages/common/locales/BUILD.bazel
> +    srcs = glob(["global/*.js"]) + ["package.json"],
They can.  Importing a module for side-effects only is part of the spec.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
https://www.ecma-international.org/ecma-262/6.0/#sec-imports

2019-11-02 20:02 UTC, petebacondarwin commented on packages/common/locales/BUILD.bazel
> +    srcs = glob(["global/*.js"]) + ["package.json"],
OK, I will tweak the `side-effects` attribute then. Thanks @clydin

2019-11-02 21:34 UTC, petebacondarwin commented
I had problems getting Bazel to run terser over the files before adding them to the npm package.
So I will not add a commit to do that in this PR.
Once I work out how to do that I can create another PR, which will reduce the global locale file sizes.

2019-11-02 21:34 UTC, petebacondarwin commented
@mhevery - PTAL.

2019-11-04 14:54 UTC, petebacondarwin commented on tools/gulp-tasks/cldr/extract.js
> +      localeData.get(`supplemental/weekData/weekendStart/${localeData.attributes.territory}`) ||
Done

2019-11-04 15:12 UTC, petebacondarwin commented on packages/common/src/i18n/locale_data_api.ts
> +import {ɵCurrencyIndex, ɵExtraLocaleDataIndex, ɵLocaleDataIndex, ɵfindLocaleData, ɵgetLocalePluralCase} from '@angular/core';
I have moved the renaming of the imports to their private names to the commit before this one.

2019-11-04 22:55 UTC, mhevery approved these changes

2019-11-04 22:59 UTC, mhevery commented
[presubmit](http://test/OCL:278471457:BASE:278471847:1572908354483:b48b1498)

2019-11-05 17:27 UTC, closed without merging