Update Alyssa on GDE list
angular/angular pull request #33538
Opened 2019-11-01 21:12 UTC by alyssamichelle

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe: Update to aio/marketing files for GDE list

## What is the current behavior?
Issue Number: N/A

## What is the new behavior?
New updated photo and bio for Alyssa on GDE list.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-11-01 21:26 UTC, alyssamichelle commented
@splaktar Can I get a review? :D

2019-11-01 22:22 UTC, Splaktar requested changes
As mentioned by the lint task that failed in CircleCI (`The commit message header does not match the format of '<type>(<scope>): <subject>'`), you'll need to add `docs: ` in front of your commit message (and you should add that to the PR title too).

Please resize your photo down to something that is about 20 KBs. The height and width should be around 170 x 170.

2019-11-01 22:22 UTC, Splaktar commented on aio/content/marketing/contributors.json
> +    "bio": "Alyssa is an Angular Developer Advocate for KUI and a GDE. Her two degrees (Web Design & Development and Psychology) feed her speaking career. She has spoken at over 35 conferences Intern
```suggestion
    "bio": "Alyssa is an Angular Developer Advocate for KUI and a GDE. Her two degrees (Web Design & Development and Psychology) feed her speaking career. She has spoken at over 35 conferences internationally. She is a weekly panelist on Adventures in Angular and Angular Air, which have a combined following of over 16,000 listeners. She enjoys gaming, scuba diving, and has a newborn that fondly goes by 'Mr. Milks'.",
```

2019-11-04 19:57 UTC, Splaktar commented
The only thing left to do is to squash your commits, [instructions](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) (from @kapunahelewong). Oh and I would also update the commit message to match the PR title during your squashing.

2019-11-04 19:59 UTC, kapunahelewong commented
Hi @alyssamichelle! Thanks for this update. To get your picture down to about 20k, you could try lowering the jpg quality if you haven't already. That should help while keeping it around 170x170.

For the commit messages, you'll want to squash and then do a `git commit --amend` and change the commit message to something like:

```
docs: update Alyssa on GDE list
```
That commit message should pass.

You may also like [my own notes on squashing and amending](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash). They go step-by-step and are specific to this repo.

If you have any questions just let me know and when you're all ready, please tag me. Congratulations on Mr. Milks! 🌟🍼

2019-11-04 20:14 UTC, alyssamichelle commented
Thanks @Splaktar and @kapunahelewong !! 

Killer article @kapunahelewong btw 👏

2019-11-04 20:17 UTC, kapunahelewong commented
ohhh thank you, @alyssamichelle. No blush emoji red enough 😊

2019-11-04 20:26 UTC, Splaktar approved these changes
LGTM

2019-11-20 21:25 UTC, StephenFluin approved these changes

2019-11-20 22:52 UTC, closed without merging