docs: Amexio description changed
angular/angular pull request #33570
Opened 2019-11-04 13:39 UTC by rashmithakkar

Amexio description changed

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-11-04 16:19 UTC, StephenFluin approved these changes
Content looks good.

2019-11-04 16:29 UTC, atscott commented
@rashmithakkar Could you accept the Google CLA so this can be merged?

2019-11-12 18:46 UTC, jbogarthyde requested changes
This still needs the CLA, but in the meantime, I'm suggesting some editorial changes to conform to Google and Angular documentation standards.

2019-11-12 18:46 UTC, jbogarthyde commented on aio/content/marketing/resources.json
> +            "desc": "Amexio is a rich set of Angular components powered by HTML5 & CSS3 for Responsive Web Design and 80+ built-in Material Design Themes. Amexio has 3 Editions, Standard, Enterprise
Some changes to conform with doc authoring guidelines:
- Please keep the expansion of "Amexio". 
- Amexio has 3 editions: Standard, Enterprise and Creative. 
- Std -> Standard edition (don't abbreviate, don't capitalize "edition")
- etc -> and so on
- use separate sentences for the descriptions of the 3 editions
- typo: Creative Edtion -> Creative edition
"websites with more than 200+ components/features. All editions are open-sourced and free, based on..."

2021-01-15 03:25 UTC, AndrewKushnir commented
Closing this PR due to the lack of response. Please reopen if you get a chance to look into it. Thank you.

2021-01-15 03:25 UTC, closed without merging