fix(ivy): more descriptive errors for nested i18n sections
angular/angular pull request #33583
Opened 2019-11-04 20:39 UTC by AndrewKushnir

This commit moves nested i18n section detection to an earlier stage where we convert HTML AST to Ivy AST. This also gives a chance to produce better diagnostic message for nested i18n sections, that also includes a file name and location.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-11-04 22:04 UTC, kara requested changes
Thanks for doing this! Some thoughts on the error message

2019-11-04 22:04 UTC, kara commented on packages/compiler/src/render3/r3_template_transform.ts
> +            'Could not mark an element as translatable inside of a translatable section',
I think the message might be even clearer if we explicitly say that the "i18n" marker is the problem and add a call to action.

```suggestion
            'Cannot mark an element as translatable inside of a translatable section. Please remove the nested i18n marker.`
```

2019-11-05 00:07 UTC, AndrewKushnir commented
- [VE Presubmit](http://test/OCL:278485837:BASE:278485914:1572912378406:5a4a6859)
- [Ivy Presubmit](http://test/OCL:278485837:BASE:278486031:1572912414020:58f9388e)

2019-11-05 00:07 UTC, AndrewKushnir commented on packages/compiler/src/render3/r3_template_transform.ts
> +            'Could not mark an element as translatable inside of a translatable section',
Thanks for the review @kara, the message text is now updated.

2019-11-05 03:40 UTC, kara approved these changes
LGTM

2019-11-05 17:20 UTC, closed without merging