fix(ivy): better support for attributes on <ng-container>s
angular/angular pull request #33599
Opened 2019-11-05 19:19 UTC by AndrewKushnir

Prior to this commit, i18n runtime logic used `elementAttributeInternal` function (that uses `setAttribute` function under the hood), which doesn't work for <ng-container>s, since they are not real nodes. In order to make this i18n functionality aligned with non-i18n logic, this commit replaces the `elementAttributeInternal` with `elementPropertyInternal`, which handles setting properties and inputs. Since inputs setup logic is already present in `elementPropertyInternal` function, corresponding logic was removed from i18n.ts.

This PR resolves FW-1663.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-11-05 19:29 UTC, ocombe commented on packages/core/test/acceptance/i18n_spec.ts
> +      expect(comp.componentInstance.messageText).toBe('Bonjour');
you're no longer testing if the attribute has the correct value?

2019-11-05 19:39 UTC, ocombe requested changes
I'm pretty sure that `setAttribute` and `setProperty` are not the same, some properties have different names compared to the original attributes. If you try to set the property `class` for example, it'll not work as expected, since the property for the attribute `class` is `className` instead...
Instead you should add a check to see if the element is a container, and use `elementPropertyInternal` on it, otherwise you should still use `elementAttributeInternal`

2019-11-05 21:00 UTC, AndrewKushnir commented on packages/core/test/acceptance/i18n_spec.ts
> +      expect(comp.componentInstance.messageText).toBe('Bonjour');
I reverted it, since I switched back to `elementAttributeInternal`.

2019-11-05 21:02 UTC, AndrewKushnir commented
@ocombe thanks for the review, I've updated the logic to avoid calling `elementAttributeInternal` for non-elements. For non-elements (like `<ng-container>`) we just set the necessary inputs. Could you please have a look again? Thank you.

2019-11-05 21:06 UTC, ocombe approved these changes

2019-11-05 23:53 UTC, AndrewKushnir commented
- [VE Presubmit](http://test/OCL:278726107:BASE:278726165:1572997941017:7c914c22)
- [Ivy Presubmit](http://test/OCL:278726107:BASE:278726340:1572997995185:66eadf26)

2019-11-06 09:19 UTC, petebacondarwin approved these changes

2019-11-06 09:19 UTC, petebacondarwin commented on packages/core/test/acceptance/i18n_spec.ts
> +    it('with <ng-container> elements', () => {
NIT - I appreciate that this is outside the remit of this PR but I find that inverting the `describe` and  `it` clauses - so that the "should" expression is on the `describe`) makes it much more difficult to understand what this is testing, especially when the `describe` is so much further back up the file.

2019-11-06 18:16 UTC, AndrewKushnir commented on packages/core/test/acceptance/i18n_spec.ts
> +    it('with <ng-container> elements', () => {
@petebacondarwin thanks for the review! I've updated the description of the test to be more clear.

2019-11-06 22:29 UTC, mhevery approved these changes

2019-11-07 01:51 UTC, closed without merging