docs: add ngIndia to event page
angular/angular pull request #33656
Opened 2019-11-07 17:04 UTC by santoshyadav198613

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-11-07 17:17 UTC, santoshyadav198613 commented
Cc: @kapunahelewong @StephenFluin

2019-11-07 19:48 UTC, mary-poppins commented
You can preview 9c4664f at https://pr33656-9c4664f.ngbuilds.io/.

2019-11-07 20:00 UTC, kapunahelewong requested changes

2019-11-07 20:00 UTC, kapunahelewong commented on aio/content/marketing/events.html
> +      </tr>
Thanks for moving these past events into the next section, too. As they are listed from the most recent at the top, could you move them to this location? https://github.com/angular/angular/blob/master/aio/content/marketing/events.html#L50

They should be in reverse order from what they currently are, so:
1. ReactiveConf
2. NgRome
3. Angular Connect 
4. NG-DE and so on as it currently is listed.

2019-11-07 20:54 UTC, santoshyadav198613 commented on aio/content/marketing/events.html
> +      </tr>
Done.

2019-11-07 21:02 UTC, mary-poppins commented
You can preview 578df0d at https://pr33656-578df0d.ngbuilds.io/.

2019-11-07 23:30 UTC, kapunahelewong approved these changes
Thanks, @santoshyadav198613 😊

2019-11-26 18:34 UTC, StephenFluin approved these changes

2019-11-27 21:04 UTC, closed without merging