fix(platform-browser): add unique input event plugin
angular/angular pull request #33688
Opened 2019-11-08 13:08 UTC by DerSizeS

This plugin checks if value of element is changed before firing input event  

Internet Explorer 10+ implements 'input' event but it erroneously fires under various situations, e.g. when placeholder changes, when non english placeholder is used or a control is focused

Fixed only from Edge 15.15002
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101220/
This bug will not be fixed in Internet Explorer 
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11405058/

Closes #14440, #17951, #15299, #16151

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Internet Explorer 10+ implements 'input' event but it erroneously fires under various situations, e.g. when placeholder changes, when non english placeholder is used or a control is focused

Issue Number: #14440, #17951, #15299, #16151

## What is the new behavior?
If plugin config is provided – input event is fired when value of element is changed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Here is the problem reproduction (to fix IE behavior- uncomment the provider): https://stackblitz.com/edit/angular-feu5wd?embed=1&file=src/app.module.ts

2019-11-11 09:48 UTC, petebacondarwin requested changes
This is a really nice piece of work @DerSizeS - thanks for submitting it.

I am torn though.

Since this is only fixing a bug in a small set of browsers (IE10 and IE11, right?) it feels like it is too much code to add to the standard framework. The event manager architecture is already in place in the framework to allow this to be added on a per project basis without having to modify the core.

I feel that a more effective solution, which would not impact projects that do not require IE support, would be to have this as some kind of extra module that a developer could add to their app as they need it - a bit like the polyfills approach we have already.  But I do feel like this should be easily available to developers without having to go look for some 3rd party library to do this...

@IgorMinar and @kara do you have a view on this?

2019-11-13 12:08 UTC, DerSizeS commented
How about exposing `UniqueInputEventPlugin` itself? That way developers could use `FactoryProvider` for conditional enabling plugin. 

Example:
```
export function setupUniqueInputEventManagerPlugin(document: Document) {
  if (isIE()) {
    return new UniqueInputEventPlugin(document);
  }
  return NOOP_EVENT_MANAGER_PLUGIN;
}
```
```
providers: [
  {
    provide: EVENT_MANAGER_PLUGINS,
    useFactory: setupUniqueInputEventManagerPlugin,
    deps: [DOCUMENT],
    multi: true,
  },
],
```

2019-11-14 19:41 UTC, petebacondarwin commented
That would still leave the code in framework, which is what I am unsure about. We need a call from @IgorMinar or @kara, I think.

2019-11-16 06:24 UTC, IgorMinar commented
this is a great PR, but it also increases the payload size for all apps.

We can merge it only If we figure out how to make this provider optional or IE specific.

I don't believe that there is a way in the CLI to include some code only into the legacy es5 bundle or is there, @filipesilva @clydin?

2019-11-16 08:13 UTC, petebacondarwin commented on packages/platform-browser/src/browser.ts
> +  },
So if we excluded this block of code from the library (i.e from this PR) then I believe it would get tree shaken by default and not add to the bundle size. But then the onus is on the app developer to find out about this and add it back in for their IE scenarios...

2019-11-17 15:36 UTC, petebacondarwin commented
@DerSizeS - I think we are agreed that we could land this if we only implement and export the `UniqueInputEventPlugin` but do not wire it up. We should also add a section to the API docs for it, explaining when it should be used and how it can be provided. By the way, I think it could just use the `useClass` provider, why did you suggest that the developer would need to use the `useFactory` approach?

2019-11-17 19:21 UTC, DerSizeS commented
> By the way, I think it could just use the `useClass` provider, why did you suggest that the developer would need to use the `useFactory` approach?

With `useClass` this plugin will be enabled for all browsers, in the case of `useFactory` developer will be able to control when plugin will be enabled (e.g. IE 10+).

For this scenario, I think it's worth adding `NOOP_EVENT_MANAGER_PLUGIN`.

2019-11-18 12:41 UTC, filipesilva commented
Exporting it but not wiring would not increase all users payload size, but would still increase all payload size for users that make use of it. Making it conditional in user code still includes it in bundles.

I don't think we have a way to add things to the es5-only polyfills though. @clydin is there a way?

2020-04-07 13:35 UTC, vladimirverbitski commented
This fix from @DerSizeS also help with dynamics form in IE, placeholder also trigger after page loading.
Thx!

2020-04-15 09:46 UTC, petebacondarwin commented
@IgorMinar how about we just export the `UniqueInputEventPlugin` and document it?

2020-04-15 15:26 UTC, IgorMinar commented
We just talked to @atscott yesterday about the unrelying bug and Andrew is doing the research to determine if we can drop IE9&10 support and then remove the problematic code that is causing the event duplication in modern browsers.

Does that sound like an ok solution to this?

2020-06-28 09:35 UTC, ai977313677 commented
"when a non-English placeholder is used or control is focused"

I cannot find the issue on websites. I think we can use the Unicode or HTML Entity code like this.

```html
 <input nz-input formControlName="appName" placeholder="&#35831;&#36755;&#20837;&#21517;&#31216;">
```

I checked. HTML Entity works well.

2020-11-10 16:38 UTC, petebacondarwin commented
Angular v11.0.0+ has dropped support for IE9 & 10, so we ought to be able to just remove the problematic code now, yes?

2020-11-19 23:29 UTC, mhevery commented
Closing as this PR seems abandoned, and we don't want to add more API surface to the event plugin API.

2020-11-19 23:29 UTC, closed without merging