Transplant views refactor
angular/angular pull request #33702
Opened 2019-11-08 23:14 UTC by mhevery

Based on https://github.com/angular/angular/pull/33644 (please ignore during review)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix/Performance
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2019-11-11 06:32 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/change_detection_spec.ts
> +        if (ivyEnabled && !getCheckNoChangesMode()) {
I would _personally_ prefer that we write those tests without being `ivy` specific and without digging into ivy internals. Such tests are brittle and we are not sure that we've got 1:1 behaviour with VE.

Couldn't we assert that the both interpolations are updated in the moved embedded view?

2019-11-11 06:37 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +          let parentLView = movedLView[PARENT];
Not sure why we've got the logic of getting a parent and `while (isLContainer(parentLView))` here. Shouldn't `findComponentView` go up the embedded views? 

As the very minimum it would be great to add more comments here as the logic here starts to be non-obvious.

2019-11-11 06:40 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +              (insertedComponentLView[FLAGS] & LViewFlags.CheckAlways) !== LViewFlags.CheckAlways;
We are not really determining `insertionIsOnPush` here but rather than it is _not_ CheckAlways, right?

It is not clear to me if this is intentional but I think that we should add comments + tests to explain what happens depending on the insertion view flags (OnPush, OnPush + marked for check, detatched etc.)

2019-11-12 17:17 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +          let parentLView = movedLView[PARENT];
I have refactored it to make it more clear. But the short of it is that `findComponentView` does not cross `LContainer` boundaries.

2019-11-12 18:06 UTC, mhevery commented
[presubmit](http://test/OCL:279994760:BASE:279994876:1573581901027:431c4dff)
[ivy presubmit](http://test/OCL:279994760:BASE:279995086:1573581949154:b5bf93b8)

2019-11-13 05:26 UTC, kara requested changes
Like the idea of only searching moved views if the flag is set! Some minor things below

2019-11-13 05:26 UTC, kara commented on packages/core/src/render3/interfaces/view.ts
> +  [DECLARATION_COMPONENT_VIEW]: LView|null;
We may want to note somewhere that the DECLARATION_COMPONENT_VIEW is the view itself if the LView is a component view (the simplest / most common case).

2019-11-13 05:26 UTC, kara commented on packages/core/test/acceptance/change_detection_spec.ts
> +      //   transplanted view is `CheckAlways` than the insertion component will be changed to
```suggestion
      //   transplanted view is `CheckAlways` then the insertion component will be changed to
```

2019-11-13 05:26 UTC, kara commented on packages/core/src/render3/interfaces/container.ts
> +  HAS_TRANSPLANTED_VIEWS = 1,
I'm guessing that the reason this is not on the TView is because you could have a component that has a default template in the same view (so it can be sometimes intra-component, sometimes inter-component)? Seems like we should add a test for that case to make sure we don't break it

2019-11-13 05:26 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
>  import {ActiveElementFlags, enterView, executeElementExitFn, getBindingsEnabled, getCheckNoChangesMode, getIsParent, getPreviousOrParentTNode, getSelectedIndex, hasActiveElementFlag, incrementActiveD
Won't let me comment on the right line, but we should remove the unused `findComponentView` export

2019-11-13 05:26 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> +  lView[DECLARATION_COMPONENT_VIEW] = tView.type == TViewType.Embedded ?
This seems to imply that we don't need the `findComponentView` function anymore because we save the declared component view upon creation now (and thus don't need to walk up the declaration tree all the time). Seems like we should clean up all the remaining `findComponentView` usages. Can we do that in a follow-up PR and maybe add a TODO above the function for now?

2019-11-13 23:47 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> +   * ```
👍 (thanks for appreciating/noticing)

2019-11-13 23:47 UTC, mhevery commented on packages/core/src/render3/interfaces/view.ts
> +  [DECLARATION_COMPONENT_VIEW]: LView|null;
added

2019-11-13 23:50 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
>  import {ActiveElementFlags, enterView, executeElementExitFn, getBindingsEnabled, getCheckNoChangesMode, getIsParent, getPreviousOrParentTNode, getSelectedIndex, hasActiveElementFlag, incrementActiveD
Good point. I had a quick look and there are many uses of this function so I don't feel comfortable doing it in this PR. I will start a new one.

2019-11-13 23:50 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +  lView[DECLARATION_COMPONENT_VIEW] = tView.type == TViewType.Embedded ?
Good point. I had a quick look and there are many uses of this function so I don't feel comfortable doing it in this PR. I will start a new one.

2019-11-13 23:51 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
>  import {ActiveElementFlags, enterView, executeElementExitFn, getBindingsEnabled, getCheckNoChangesMode, getIsParent, getPreviousOrParentTNode, getSelectedIndex, hasActiveElementFlag, incrementActiveD
removed

2019-11-14 00:04 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> +        (activeIndexFlag = viewOrContainer[ACTIVE_INDEX]) >> ActiveIndexFlag.SHIFT ===
```suggestion
        getLContainerActiveIndex(activeIndexFlag = viewOrContainer[ACTIVE_INDEX]) ===
```

2019-11-14 00:04 UTC, kara commented on packages/core/src/render3/interfaces/view.ts
> +   * In the above case `DECLARATION_VIEW` for `myTmpl` points to the `LView` of `ngIf` where as
```suggestion
   * In the above case `DECLARATION_VIEW` for `myTmpl` points to the `LView` of `ngIf` whereas
```

2019-11-14 00:04 UTC, kara commented on packages/core/src/render3/interfaces/view.ts
> +   * The reason for this is that all embedded views are always check-always where as the component
```suggestion
   * The reason for this is that all embedded views are always check-always whereas the component
```

2019-11-14 00:04 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> +        // on-push (not just moved within a component). If the insertion is marked dirty, than
```suggestion
        // on-push (not just moved within a component). If the insertion is marked dirty, then
```

2019-11-14 00:04 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> +  lView[DECLARATION_COMPONENT_VIEW] = tView.type == TViewType.Embedded ?
Sounds good to me

2019-11-14 00:15 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +        (activeIndexFlag = viewOrContainer[ACTIVE_INDEX]) >> ActiveIndexFlag.SHIFT ===
I don't think I can do this one. It is written specifically this way so that I don't have to read the `[ACTIVE_INDEX]` more than once.

2019-11-14 00:21 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> +        (activeIndexFlag = viewOrContainer[ACTIVE_INDEX]) >> ActiveIndexFlag.SHIFT ===
Ohh I see what you mean. OK resolving.

2019-11-14 00:22 UTC, kara approved these changes
LGTM

2019-11-14 17:28 UTC, closed without merging