fix(ivy): throw a better error when DI can't inject a ctor param
angular/angular pull request #33739
Opened 2019-11-11 18:36 UTC by alxhub

Occasionally a factory function needs to be generated for an "invalid"
constructor (one with parameters types which aren't injectable). Typically
this happens in JIT mode where understanding of parameters cannot be done in
the same "up-front" way that the AOT compiler can.

This commit changes the JIT compiler to generate a new `invalidFactoryDep`
call for each invalid parameter. This instruction will error at runtime if
called, indicating both the index of the invalid parameter as well as (via
the stack trace) the factory function which was generated for the type being
constructed.

2019-11-11 23:47 UTC, kara requested changes
Thanks for doing this! Some nits

2019-11-11 23:47 UTC, kara commented on packages/core/test/render3/ivy/jit_spec.ts
> +              /constructor is not compatible with Angular Dependency Injection because its dependency for its parameter 2 is invalid/);
It seems unexpected to me that we're not using zero-based indices here. Shouldn't it be "parameter at index 1"?

```suggestion
              /constructor is not compatible with Angular Dependency Injection because its dependency  at index 1 is invalid/);
```

2019-11-11 23:47 UTC, kara commented on packages/core/test/render3/ivy/jit_spec.ts
> +  });
Can we add a test for the missing directive decorator case?

2019-11-18 18:59 UTC, kara commented on packages/core/src/di/injector_compatibility.ts
> +      `This constructor is not compatible with Angular Dependency Injection because its dependency for its parameter at index ${index} is invalid.
Nit: I'm still having a bit of trouble parsing `its dependency for its parameter`. How about:

```suggestion
      `This constructor is not compatible with Angular Dependency Injection because its dependency at index ${index} of the parameter list is invalid. 
```

2019-11-19 21:51 UTC, alxhub commented on packages/core/src/di/injector_compatibility.ts
> +      `This constructor is not compatible with Angular Dependency Injection because its dependency for its parameter at index ${index} is invalid.
👍

2019-11-20 21:19 UTC, kara approved these changes
LGTM

2019-11-20 21:20 UTC, kara commented
merge-assistance: global approval

2019-11-20 22:02 UTC, alxhub commented
[Presubmit](http://test/OCL:281589058:BASE:281589109:1574285519868:e72dbf99)
[Ivy Presubmit](http://test/OCL:281589058:BASE:281589357:1574285592986:98b992f8)

2019-11-21 22:07 UTC, matsko commented
presubmit = https://tap.corp.google.com/ui#id=OCL:281828042:BASE:281828085:1574374000808:cacdfdd

ivy-presubmit = https://test.corp.google.com/ui#id=OCL:281828042:BASE:281828217:1574374035451:c620fa44

2019-11-27 18:35 UTC, mhevery commented
Needs rebase and fails g3

```
packages/core/src/di/injector_compatibility.closure.js:145: ERROR - [JSC_UNDEFINED_VARIABLE] variable ngDevMode is undeclared
    const msg = ngDevMode ?
                ^^^^^^^^^

1 error(s), 0 warning(s)
```

2019-12-07 00:25 UTC, alxhub commented
[Presubmit](http://test/OCL:284282047:BASE:284282095:1575677274521:5de79d48)
[Ivy Presubmit](http://test/OCL:284282047:BASE:284282095:1575677274493:2f644fe1)

2019-12-07 00:25 UTC, alxhub commented on packages/core/test/render3/ivy/jit_spec.ts
> +  });
Done!

2019-12-09 19:37 UTC, closed without merging