perf(ivy): chain styling instructions
angular/angular pull request #33837
Opened 2019-11-15 00:02 UTC by crisbeto

Adds support for chaining of `styleProp`, `classProp` and `stylePropInterpolateX` instructions whenever possible which should help generate less code. Note that one complication here is for `stylePropInterpolateX` instructions where we have to break into multiple chains if there are other styling instructions inbetween the interpolations which helps maintain the execution order.

2019-11-15 16:52 UTC, mhevery approved these changes

2019-11-15 19:17 UTC, matsko requested changes

2019-11-15 19:17 UTC, matsko commented on packages/compiler/src/render3/view/compiler.ts
> +          totalHostVarsCount += Math.max(call.allocateBindingSlots - 1, 0);
Add a comment explaining why there's a `-1`

2019-11-15 19:17 UTC, matsko commented on packages/compiler/src/render3/view/styling_builder.ts
> +  calls: StylingInstructionCall[];
Add a comment explaining what this new member is.

2019-11-15 19:17 UTC, matsko commented on packages/compiler/src/render3/view/styling_builder.ts
>  export interface StylingInstruction {
Since we're only using one property on this interface, why not just return a array of `StylingInstructionCall` instances?

2019-11-15 19:17 UTC, matsko commented on packages/core/src/render3/instructions/styling.ts
> +export function ɵɵclassProp(className: string, value: boolean | null): TsickleIssue1009 {
Add a comment explaining the return value and why it's an instance of `TsickleIssue1009`

2019-11-15 19:17 UTC, matsko commented on packages/compiler/src/render3/view/template.ts
>            fnParams.unshift(o.literal(property.name));
Add a comment explaining this `unshift` operation.

2019-11-18 18:01 UTC, crisbeto commented on packages/compiler/src/render3/view/styling_builder.ts
>  export interface StylingInstruction {
It's set up like this so that it's easier to group calls to the same instruction together. If we wanted to change it, we'd have to do something like `StylingInstructionCall[][]` instead, but that would mean looping through all the calls when we're trying to figure out whether to chain them.

2019-11-18 18:03 UTC, crisbeto commented on packages/core/src/render3/instructions/styling.ts
> +export function ɵɵclassProp(className: string, value: boolean | null): TsickleIssue1009 {
Isn't this the point of the `TsickleIssue1009` type in the first place? Also Andrew mentioned that this isn't an issue anymore so as soon as these changes land I'll clean out all the usages of the `TsickleIssue1009` type.

2019-11-18 18:04 UTC, crisbeto commented
The feedback has been addressed @matsko.

2019-11-18 18:49 UTC, kara approved these changes
LGTM aside from typos. Note that we should be careful with the G3 presubmit for this because we are changing binding order in some cases, which could break some G3 targets.

2019-11-18 18:49 UTC, kara commented on packages/compiler-cli/test/compliance/r3_view_compiler_styling_spec.ts
> +    it('should break into multiple chains if there are other styling instructions inbetween',
```suggestion
    it('should break into multiple chains if there are other styling instructions in between',
```

2019-11-18 18:49 UTC, kara commented on packages/compiler-cli/test/compliance/r3_view_compiler_styling_spec.ts
> +    it('should break into multiple chains if there are other styling interpolation instructions inbetween',
```suggestion
    it('should break into multiple chains if there are other styling interpolation instructions in between',
```

2019-11-18 19:03 UTC, matsko approved these changes

2019-11-18 19:03 UTC, matsko commented on packages/compiler/src/render3/view/styling_builder.ts
>  export interface StylingInstruction {
ah I see. I missed the `reference` member. This is fine.

2019-11-18 19:41 UTC, matsko commented
presubmit = http://test/OCL:281116837:BASE:281116883:1574105974370:89ff78f9

ivy presubmit = https://test.corp.google.com/ui#id=OCL:281116837:BASE:281117274:1574106065978:3e19703d

2019-11-19 19:44 UTC, closed without merging