docs(core): fix typo in API docs
angular/angular pull request #33912
Opened 2019-11-18 23:00 UTC by rafayel23

## fix typo in definition of *ViewEncapsulation* enum

*from* - Defines template and style encapsulation options available for Component's ~~**Component**~~
*to* -Defines template and style encapsulation options available for Component's **View**

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Semantically incorrect definition of ViewEncapsulation enum from @angular/core package.
*Defines template and style encapsulation options available for Component's **Component***
 
P.S. I believe this is just a typo.

## What is the new behavior?

Replace the word **Component** with **View** in definition to get correct meaning.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-12-23 17:54 UTC, jbogarthyde requested changes
Some edits and clarification.

2019-12-23 17:54 UTC, jbogarthyde commented on packages/core/src/metadata/view.ts
> + * Defines template and style encapsulation options available for Component's {@link View}.
There is no `View` class or type. I would link to the glossary definition instead -- 
... for the [view](guide/glossary#view) attached to a component.

2019-12-23 17:54 UTC, jbogarthyde commented on packages/core/src/metadata/view.ts
>   * See {@link Component#encapsulation encapsulation}.
Perhaps: 
Specified in the {@link Component#encapsulation encapsulation} property of the `Component` instance.

2020-03-06 22:04 UTC, mhevery commented
This PR seem abandoned and without a CLA, so we are unable to merge it. Closing. Please re-open if you want to make progress on this.

2020-03-06 22:04 UTC, closed without merging