refactor(ivy): add flag to skip non-exported classes
angular/angular pull request #33921
Opened 2019-11-19 20:05 UTC by crisbeto

In ViewEngine we were only generating code for exported classes, however with Ivy we do it no matter whether the class has been exported or not. These changes add an extra flag that allows consumers to opt into the ViewEngine behavior. The flag works by treating non-exported classes as if they're set to `jit: true`.

2019-11-19 21:24 UTC, crisbeto commented on packages/compiler-cli/src/transformers/api.ts
> +  skipNonExportedClasses?: boolean;
Some questions for the reviewer since the ticket wasn't very descriptive:

1. I'm open to suggestion on what we should call the flag.
2. Do we want to default it to `true` so it matches ViewEngine or leave it as an opt-in?

2019-11-19 21:37 UTC, alxhub commented on packages/compiler-cli/ngcc/src/analysis/decoration_analyzer.ts
> +        this.isCore, /* skipNonExportedClasses */ false),
I think the default here should be `true`, as ngcc only processes code which was intended for View Engine.

2019-11-19 21:39 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +    it('should not emit directive definitions for non-exported classes if configured', () => {
Can we put these all in a `describe('non-exported classes', ...)`?

2019-11-19 21:41 UTC, devversion commented
This PR will close #33724. This issue also provides some context and a reproduction for later reference.

2019-11-19 21:41 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts
> +      private defaultImportRecorder: DefaultImportRecorder, private skipNonExportedClasses: boolean,
Rather than carry `skipNonExportedClasses` around to each of the `DecoratorHandlers` (and in fact this PR only does 2 of them - non-exported classes will still be processed as `@Injectable`s for example) we should nip this in the bud.

In `IvyCompilation` inside `analyze`, we can skip the class for all decorator handlers without passing the flag down into each one.

2019-11-19 22:00 UTC, crisbeto commented
The feedback has been addressed.

2019-11-19 22:15 UTC, devversion commented on packages/compiler-cli/src/transformers/api.ts
> +  skipNonExportedClasses?: boolean;
That's a good question. I think there is still discussion going on. I'd vote for this being opt-in since long-term it feels like we need to come up with something that works better for unit testing w/ AOT. I've explained in the original Github issue.

2019-11-21 18:41 UTC, AndrewKushnir commented
- [VE Presubmit](http://test/OCL:281782004:BASE:281782075:1574361287241:5df846bb)
- [Ivy Presubmit](https://test.corp.google.com/OCL:281782004:BASE:281782303:1574361333701:8982e1df)

2019-11-21 19:18 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +        env.tsconfig({skipNonExportedClasses: true});
This can move into a `beforeEach` inside the `describe`. That centralizes the common thread between the tests.

2019-11-21 19:20 UTC, alxhub approved these changes

2019-11-21 19:24 UTC, alxhub requested changes

2019-11-21 19:24 UTC, alxhub commented on packages/compiler-cli/src/transformers/api.ts
> +  skipNonExportedClasses?: boolean;
In general, I think when a flag is `true` it should do something, not prevent something.

So instead of `skipNonExportedClasses`, let's go with `compileNonExportedClasses`, and make it default to `true`. Then if users don't want the behavior, they explicitly disable it, rather than explicitly enable skipping it.

2019-11-21 19:42 UTC, crisbeto commented
Updated based on the latest set of feedback.

2019-11-21 19:55 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +      private scopeRegistry: LocalModuleScopeRegistry, private compileNonExportedClasses = true) {}
No default values in compiler code. Explicitly pass in the value at the callsite.

2019-11-21 19:56 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/program.ts
> +        this.sourceToFactorySymbols, scopeRegistry, this.options.compileNonExportedClasses);
```suggestion
        this.sourceToFactorySymbols, scopeRegistry, this.options.compileNonExportedClasses !== false);
```

2019-11-21 20:07 UTC, alxhub commented
[Presubmit](http://test/OCL:281803190:BASE:281803243:1574366708702:92f3701e)
Ivy Presubmit: not needed, no a g3 behavior change.

2019-11-21 20:08 UTC, alxhub approved these changes

2019-11-25 18:38 UTC, AndrewKushnir commented
@crisbeto g3 presubmit looks good (I removed the "presubmit" label). Could you please rebase this PR and resolve a conflict? Thank you.

2019-11-25 19:40 UTC, crisbeto commented
Rebased.

2019-11-25 21:36 UTC, closed without merging