build: npm_integration_test && angular_integration_test
angular/angular pull request #33927
Opened 2019-11-20 06:13 UTC by gregmagolan

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-11-20 10:22 UTC, IgorMinar commented
This PR looks very promising!! 

I ran across some issues however... so it still needs polish (as you already mentioned on slack)...

```
yarn bazel test //integration:cli_hello_world_test --test_output=streamed
```
results in 
```

[test_runner.js] running test command '/b/f/w/bazel-out/k8-fastbuild/bin/integration/cli_hello_world_test.sh.runfiles/nodejs_darwin_amd64/bin/yarn install' in /tmp/tmp-194EFNZxTaipL8
/b/f/w/bazel-out/k8-fastbuild/bin/integration/cli_hello_world_test.sh.runfiles/nodejs_darwin_amd64/bin/yarn: line 18: /b/f/w/bazel-out/k8-fastbuild/bin/integration/cli_hello_world_test.sh.runfiles/nodejs_darwin_amd64/bin/node: No such file or directory
[test_runner.js] 0 of 2 test commands successful
[test_runner.js] test command 1 failed with status code 1
[test_runner.js] to run test in debug mode:

    bazel run //integration:cli_hello_world_test.debug
```

on mac

I also tried `bazel run //integration:cli_hello_world_test.debug` which fails with:

```
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
[09:23:55] I/launcher - Running 1 instances of WebDriver
[09:23:55] I/direct - Using ChromeDriver directly...
[09:23:57] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 75
  (Driver info: chromedriver=75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}),platform=Mac OS X 10.14.6 x86_64)
[09:23:57] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 75
```
which is different from the version I have installed locally (78.0.3904.97) - interestingly this hasn't been a problem I experienced before which is odd. I tried to manually run the webdriver-manager command to install version 78.0.3904.105 and then I got a bit further.

next I did get a build error:

```
This version of CLI is only compatible with Angular versions ^9.0.0-beta || >=9.0.0 <10.0.0,
but Angular version 0.0.0 was found instead.
```
This is due to: https://github.com/angular/angular-cli/blob/c7135fae357ffe16bd420b59b80b002632806a45/packages/angular_devkit/build_angular/src/utils/version.ts#L55-L78

I tried to use `--config=release` as well but that didn't work for me and resulted in the same error. 

In any case, build stamping is expensive because it invalidates most caches.

This check comes from: https://github.com/angular/angular-cli/blob/c7135fae357ffe16bd420b59b80b002632806a45/packages/angular_devkit/build_angular/src/utils/version.ts#L55-L58

I worked around this in the past by monkey-patching @angular/cli in node_modules and setting its version to 0.0.0 which disables the check (see cli code link above), but it might be even better to update that CLI version check to be `angularCliPkgJson['version'] === '0.0.0' || angularPkgJson['version'] === '0.0.0'`. This might be worth requesting from the CLI team or sending them a PR.

One more issue I see lurking is yarn caching issue of file:// dependencies (https://github.com/yarnpkg/yarn/issues/2165) - I believe that I don't see my updates to packages/core/src reflected after rerunning the `.debug` command and I wonder if that yarn issue is the culprit.

Lastly, I wonder if running `yarn test` automatically as part of the `.debug` workflow is ideal. Or maybe .debug should do that but there also should be a `.install` workflow that just sets up the project with locally built packages built and installed and leaves it up to me to run `yarn build` or `yarn test`. 

Sorry, I vomited a lot of stuff into this commit :-)  I'm just a bit too excited about the prospect of this actually working and us being able to cache the test results of these integration tests, and more easily rerun these tests locally and be able to iterate on core packages while observing the impact of those changes on these integration apps/tests.

2019-11-20 19:43 UTC, gregmagolan commented
Thanks for the taking a look @IgorMinar .

* Linux node issue came up in CI as well so will fix that today.

* The config:release issue I think we should fix in the CLI so that it allows version "0.0.0" otherwise we'ld have to have `--workspace_status_command="node ./tools/bazel_stamp_vars.js"` on for the build which is not desirable talking to @josephperrott as building with "0.0.0" in general prevents accidental publishes. Note: when you add `--config:release` after the build is complete once it won't re-run the build as changes to `bazel-out/volatile-status.txt` does not invalidate the build cache.

* Chromedriver issue is interesting. It seems like just running `webdriver-manager update --gecko=false --standalone=false` installs `chromedriver_75.0.3770.140` by default. The test postinstall has `webdriver-manager update --gecko=false --standalone=false $CI_CHROMEDRIVER_VERSION_ARG` and `$CI_CHROMEDRIVER_VERSION_ARG` is not set. I also had to run ``webdriver-manager update --gecko=false --standalone=false 78.0.3904.97` to get the correct version that works with my local chrome.

2019-11-22 04:47 UTC, IgorMinar commented on .bazelrc
> +run --action_env=CI_CHROMEDRIVER_VERSION_ARG
don't we install local version of chrome via rules_webtesting? if so, why not use that version of browser and a matching chromedriver version?

developers won't know what version of chromedriver they need and when it needs to be updated.

2019-11-22 05:08 UTC, IgorMinar reviewed
this PR is getting insanely complex :-(

to be honest, I can't really follow what's going on here unless I set aside half day to study all the different parts and how they interact.

I'm really concerned that we won't be able to maintain this stuff. Aren't there ways to simplify the approach?

2019-11-22 05:56 UTC, gregmagolan commented on .bazelrc
> +run --action_env=CI_CHROMEDRIVER_VERSION_ARG
bazel is just running `yarn install && yarn test` here (which runs `ng test`) so it has no control over which chrome is being run as bazel is just the task runner.

developers will need to set an env variable `CI_CHROMEDRIVER_VERSION_ARG` to a version that matches their locally installed chrome or set a `--define= CI_CHROMEDRIVER_VERSION_ARG="--versions.chrome VERSION" in their user .bazelrc.

I don't think there is anyway around this as it would be same workflow as running `cd integration/foobar && yarn install && yarn test`. Ideally we would run the test in a docker container with a predefined version of chrome.

2019-11-22 06:07 UTC, gregmagolan commented on tools/npm_integration_test/npm_integration_test.bzl
> +        launcher_content = """@echo off
actually, that a good point as this really should just be a nodejs_test rule with a config file generator rule in-front of it which would simplify the .bzl quite a bit.

The tasks for the test are:

* copy the test files to tmp folder to run out of (unless using `bazel run //my:test.debug`
* tgz npm packages to link since npm symlinks directory file: references which leads to file permission issues with bazel-bin generated npm packages
* patch package.json file in the test folder with absolute links to npm package tgz files for the npm packages linked

That is too much complexity for starlark which is why the test_runner is a node program & then that program executes which ever arbitrary commands are needed to run the integration test

2019-11-22 06:10 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +      this.successful = this.successful + 1;
I had read this post https://github.com/apple/swift-evolution/blob/master/proposals/0004-remove-pre-post-inc-decrement.md and I must now be baised against x++ and ++x

2019-11-22 06:11 UTC, gregmagolan commented
I was thinking I would upstream this to rules_nodejs as it will be useful for any project that generates npm_packages and wants to integration test.  I don't think it would make sense for the angular team to maintain this it is a general solution for integration testing against npm_package artifacts.

2019-11-22 06:14 UTC, gregmagolan commented on tools/npm_integration_test/npm_integration_test.bzl
> +        launcher_content = """@echo off
another big simplification would be for the npm_package rule to have a .tgz output so the integration test rule could test against that

2019-11-24 20:57 UTC, gregmagolan commented
Alrighty. Based on your comments @IgorMinar I've grossly simplified the rule. It is now a macro that generates a .js config file & then calls a nodejs test with that config file as the first argument.

Can't land this yet as it is waiting on the next release of angular-cli to make it to angular which includes https://github.com/angular/angular-cli/pull/16267 and it is also waiting on https://github.com/angular/angular/pull/33996 to be able to remove the nodejs patches.

Next step is to expand this too all of the integration tests (except for the bazel-in-bazel tests `integration/bazel` and `integration/bazel-schematics`) and remove those tests from CI and from the integration.sh script.

2019-11-27 01:45 UTC, gregmagolan commented
`npm_integration_test` not yet working on Windows. Tested by temporarily turning on the Windows CI. First error hit is:
```
ERROR: missing input file '@nodejs_windows_amd64//:bin/yarnpkg/yarn.cmd'
ERROR: C:/users/circleci/ng/integration/BUILD.bazel:39:5: //integration:cli-hello-world-lazy-rollup_test: missing input file '@nodejs_windows_amd64//:bin/yarnpkg/yarn.cmd'
ERROR: C:/users/circleci/ng/integration/BUILD.bazel:39:5 1 input file(s) do not exist
```
May need rules_nodejs changes. Will fix in follow up PR as this won't break Windows developers as //integration/... is not part of the regular `yarn test-non-ivy ...` and `yarn test-ivy-aot ...` workflow.

2019-11-28 20:34 UTC, gregmagolan commented
Note: updating to @angular/cli and @angular-devkit v9 rc4 releases here to pick up fix in @angular-dev/build-angular that allows for "0.0.0" @angular/core packages in integration tests.

Still waiting on https://github.com/angular/angular/pull/34073 but that is now in the merge queue so should land soon.

2019-12-04 19:34 UTC, josephperrott commented on integration/run_tests.sh
> +  if ([[ ! $testDir =~ cli-hello-world ]] && [[ ! $testDir == hello_world__closure ]]); then
Should we instead update the `.get-sharded-tests.js` script to only return the non `angular_integration_test` tests?

2019-12-04 19:34 UTC, josephperrott commented on tools/defaults.bzl
> +        # should not be build unless it is a dependency of another rule
s/build/built

2019-12-12 20:54 UTC, IgorMinar commented
I'm getting "Infinite symlink expansion" errors when running any bazel commands on the integration dir:


```
$ yarn bazel query integration/...
yarn run v1.21.1
$ bazel query integration/...
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/command.profile.gz'
ERROR: infinite symlink expansion detected
[start of symlink chain]
/Users/iminar/Development/angular-caretaking/integration/bazel/bazel-bazel/external/angular/integration
/private/var/tmp/_bazel_iminar/d38ef84bd1f6341a0d6cc37057753a88/execroot/bazel_integration_test/external/angular/integration
/private/var/tmp/_bazel_iminar/d38ef84bd1f6341a0d6cc37057753a88/external/angular/integration
/Users/iminar/Development/angular-caretaking/integration
[end of symlink chain]
ERROR: Infinite symlink expansion
Loading: 1 packages loaded
error Command failed with exit code 7.
```

2019-12-30 10:01 UTC, gregmagolan commented
Rebased on top of https://github.com/angular/angular/pull/34589 which should land first

2020-01-01 17:23 UTC, gregmagolan commented
@IgorMinar That's very strange. How did you get a `integration/bazel/bazel-bazel` folder? That looks like the source of the problem.

I ran the different variations:
```
yarn bazel test //integration:bazel_test --test_output=streamed
yarn bazel run //integration:bazel_test
yarn bazel test //integration:bazel_test.debug --test_output=streamed
yarn bazel run //integration:bazel_test.debug
```
only the .debug target runs in the `/integration/bazel` folder but `build --symlink_prefix=/` is set in `/integration/bazel/.bazelrc` so you shouldn't get any bazel symlinks there.

The query (without `bazel-bazel` there) should return:

```
$ bazel query 'kind(nodejs_test, integration/...)'
nodejs_test rule //integration:typings_test_ts36_test.debug
nodejs_test rule //integration:typings_test_ts36_test
nodejs_test rule //integration:terser_test.debug
nodejs_test rule //integration:terser_test
nodejs_test rule //integration:side-effects_test.debug
nodejs_test rule //integration:side-effects_test
nodejs_test rule //integration:service-worker-schema_test.debug
nodejs_test rule //integration:service-worker-schema_test
nodejs_test rule //integration:platform-server_test.debug
nodejs_test rule //integration:platform-server_test
nodejs_test rule //integration:ngcc_test.debug
nodejs_test rule //integration:ngcc_test
nodejs_test rule //integration:ng_update_test.debug
nodejs_test rule //integration:ng_update_test
nodejs_test rule //integration:ng_update_migrations_test.debug
nodejs_test rule //integration:ng_update_migrations_test
nodejs_test rule //integration:ng_elements_test.debug
nodejs_test rule //integration:ng_elements_test
nodejs_test rule //integration:language_service_plugin_test.debug
nodejs_test rule //integration:language_service_plugin_test
nodejs_test rule //integration:ivy-i18n_test.debug
nodejs_test rule //integration:ivy-i18n_test
nodejs_test rule //integration:injectable-def_test.debug
nodejs_test rule //integration:injectable-def_test
nodejs_test rule //integration:i18n_test.debug
nodejs_test rule //integration:i18n_test
nodejs_test rule //integration:hello_world__systemjs_umd_test.debug
nodejs_test rule //integration:hello_world__systemjs_umd_test
nodejs_test rule //integration:hello_world__closure_test.debug
nodejs_test rule //integration:hello_world__closure_test
nodejs_test rule //integration:dynamic-compiler_test.debug
nodejs_test rule //integration:dynamic-compiler_test
nodejs_test rule //integration:cli-hello-world_test.debug
nodejs_test rule //integration:cli-hello-world_test
nodejs_test rule //integration:cli-hello-world-lazy_test.debug
nodejs_test rule //integration:cli-hello-world-lazy_test
nodejs_test rule //integration:cli-hello-world-lazy-rollup_test.debug
nodejs_test rule //integration:cli-hello-world-lazy-rollup_test
nodejs_test rule //integration:cli-hello-world-ivy-minimal_test.debug
nodejs_test rule //integration:cli-hello-world-ivy-minimal_test
nodejs_test rule //integration:cli-hello-world-ivy-i18n_test.debug
nodejs_test rule //integration:cli-hello-world-ivy-i18n_test
nodejs_test rule //integration:cli-hello-world-ivy-compat_test.debug
nodejs_test rule //integration:cli-hello-world-ivy-compat_test
nodejs_test rule //integration:bazel_test.debug
nodejs_test rule //integration:bazel_test
nodejs_test rule //integration:bazel-schematics_test.debug
nodejs_test rule //integration:bazel-schematics_test
```

2020-01-01 17:28 UTC, gregmagolan commented on tools/defaults.bzl
> +        # should not be build unless it is a dependency of another rule
👍

2020-01-01 18:19 UTC, gregmagolan commented
Ahh. I see. If that line is removed from the .bazelrc you get a `integration/bazel/bazel-bazel` folder if you run the build from there. I'll add the appropriate `.bazelignore` lines so that it doesn't break things if that folder gets created.

2020-01-01 18:21 UTC, gregmagolan commented on integration/run_tests.sh
> +  if ([[ ! $testDir =~ cli-hello-world ]] && [[ ! $testDir == hello_world__closure ]]); then
seems like the better way to go yes. I'll make that change.

2020-01-01 18:23 UTC, gregmagolan commented on .bazelrc
> +run --action_env=CI_CHROMEDRIVER_VERSION_ARG
hmmmm. it's only used a runtime so the build artifacts don't change depending on its value. seems incorrect to invalidate the build if the value of CI_CHROMEDRIVER_VERSION_ARG changes.

2020-01-02 02:14 UTC, gregmagolan commented on integration/run_tests.sh
> +  if ([[ ! $testDir =~ cli-hello-world ]] && [[ ! $testDir == hello_world__closure ]]); then
Done. I just simplified the both scripts :)

2020-01-02 02:14 UTC, gregmagolan commented
@IgorMinar This is ready for a final review.

2020-01-09 20:01 UTC, IgorMinar commented
I'll take this for the spin now.

2020-01-09 22:02 UTC, IgorMinar commented
I'm getting local failures:

```
//integration:cli-hello-world-lazy_test                                 TIMEOUT in 901.1s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/cli-hello-world-lazy_test/test.log
//integration:ivy-i18n_test                                             TIMEOUT in 901.1s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/ivy-i18n_test/test.log
//integration:cli-hello-world-ivy-compat_test                            FAILED in 620.0s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/cli-hello-world-ivy-compat_test/test.log
//integration:cli-hello-world-ivy-i18n_test                              FAILED in 348.5s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/cli-hello-world-ivy-i18n_test/test.log
//integration:cli-hello-world-ivy-minimal_test                           FAILED in 575.7s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/cli-hello-world-ivy-minimal_test/test.log
//integration:cli-hello-world_test                                       FAILED in 283.3s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/cli-hello-world_test/test.log
//integration:dynamic-compiler_test                                      FAILED in 332.7s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/dynamic-compiler_test/test.log
//integration:hello_world__closure_test                                  FAILED in 224.3s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/hello_world__closure_test/test.log
//integration:hello_world__systemjs_umd_test                             FAILED in 285.8s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/hello_world__systemjs_umd_test/test.log
//integration:i18n_test                                                  FAILED in 343.4s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/i18n_test/test.log
//integration:injectable-def_test                                        FAILED in 373.9s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/injectable-def_test/test.log
//integration:language_service_plugin_test                               FAILED in 118.7s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/language_service_plugin_test/test.log
//integration:ng_elements_test                                           FAILED in 229.6s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/ng_elements_test/test.log
//integration:ng_update_migrations_test                                  FAILED in 304.9s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/ng_update_migrations_test/test.log
//integration:ngcc_test                                                  FAILED in 520.5s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/ngcc_test/test.log
//integration:platform-server_test                                       FAILED in 205.0s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/platform-server_test/test.log
//integration:side-effects_test                                          FAILED in 443.0s
  /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/testlogs/integration/side-effects_test/test.log

Executed 22 out of 22 tests: 5 tests pass and 17 fail locally.
```

it's odd that CI doesn't see them.

example logs:
<toggle>
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //integration:cli-hello-world-lazy_test
-----------------------------------------------------------------------------
[test_runner.js] running in /private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy_test.sh.runfiles/angular
[test_runner.js] test files from 'angular/integration/cli-hello-world-lazy' copied to tmp folder /var/folders/1k/21j4lqbn2kzgv1xp50nw64g4003k9q/T/tmp-65996jJTu5CFoi3tj
[test_runner.js] overriding devDependencies['typescript'] npm package with 'file:/private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy_test.sh.runfiles/npm/typescript_archive.tar.gz' in package.json file
[test_runner.js] overriding dependencies['rxjs'] npm package with 'file:/private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy_test.sh.runfiles/npm/rxjs_archive.tar.gz' in package.json file
[test_runner.js] overriding dependencies['tslib'] npm package with 'file:/private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy_test.sh.runfiles/npm/tslib_archive.tar.gz' in package.json file
[test_runner.js] overriding devDependencies['protractor'] npm package with 'file:/private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy_test.sh.runfiles/npm/protractor_archive.tar.gz' in package.json file
[test_runner.js] overriding devDependencies['@angular/cli'] npm package with 'file:/private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy_test.sh.runfiles/npm/angular_cli_archive.tar.gz' in package.json file
[test_runner.js] overriding devDependencies['@angular-devkit/build-angular'] npm package with 'file:/private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy_test.sh.runfiles/npm/angular-devkit_build-angular_archive.tar.gz' in package.json file
[test_runner.js] overriding devDependencies['@types/jasmine'] npm package with 'file:/private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy_test.sh.runfiles/npm/types_jasmine_archive.tar.gz' in package.json file
[test_runner.js] overriding devDependencies['@types/jasminewd2'] npm package with 'file:/private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy_test.sh.runfiles/npm/types_jasminewd2_archive.tar.gz' in package.json file
[test_runner.js] overriding devDependencies['@types/node'] npm package with 'file:/private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy_test.sh.runfiles/npm/types_node_archive.tar.gz' in package.json file
[test_runner.js] overriding dependencies['@angular/animations'] npm package with 'file:/private/var/tmp/_bazel_iminar/599b792019b2af1e8b9ff258eedd177a/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy_test.sh.runfiles/angular/packages/animations/npm_package_archive.tar.gz' in package.json file
[test_runner.js] overriding dependencies['@angular/common'] npm package with 'file:/priv [...]

2020-01-09 22:12 UTC, gregmagolan commented
@IgorMinar It looks like you're building the angular bundles judging by the error:
```
echo 'FAIL: Expected '''ngcc''' to add build marker for '''esm2015''' in '''@angular/common'''.'
FAIL: Expected 'ngcc' to add build marker for 'esm2015' in '@angular/common'.
```
Maybe that is set in your home .bazelrc?

I left a note about which tests fail with ivy bundles and what the errors are:

```
# The following tests should not be run with the ivy generated `--define=compile=aot` bundles
[
    angular_integration_test(
        name = test_folder + "_test",
        tags = ["no-ivy-aot"],
        test_folder = test_folder,
    )
    for test_folder in [
        # `injectable-def` has .ngfactory imports:
        # ```
        # FAIL: Expected 'ngcc' to add build marker for 'esm2015' in '@angular/common'.
        # ```
        # as it is not expecting the @angular bundles to be generated with `--define=compile=aot`
        "injectable-def",
        # `ngcc` fails with:
        # ```
        # + ngc -p tsconfig-app.json
        # src/main.ts(5,34): error TS2307: Cannot find module './app.ngfactory'.
        # Error during template compile of 'AppModule'
        #   Function calls are not supported in decorators but 'BrowserModule' was called.
        # ```
        "ngcc",
        # `ng_update_migrations` has golden tests failures such as:
        # ```
        # ✘  File "src/app/migration-tests/undecorated-derived-classes.ts" does not match the expected output.
        # --------------------------------------------
        # --- src/app/migration-tests/undecorated-derived-classes.ts	Expected content
        # +++ src/app/migration-tests/undecorated-derived-classes.ts	Actual content
        # @@ -1,50 +1,19 @@
        # -import { Directive, NgModule, NgZone, Component } from '@angular/core';
        # -import { CheckboxControlValueAccessor, NG_VALUE_ACCESSOR, NG_ASYNC_VALIDATORS } from '@angular/forms';
        # -import { BaseComponentFromOtherFile, hostBindings } from './base-component';
        # +import {Directive, NgModule, NgZone} from '@angular/core';
        # +import {CheckboxControlValueAccessor} from '@angular/forms';
        # +import {BaseComponentFromOtherFile} from './base-component';
        # ```
        "ng_update_migrations",
        # `i18n` has .ngfactory imports:
        # ```
        # $ ngc && yarn run closure && concurrently "yarn run serve" "yarn run protractor" --kill-others --success first && npm run test-locale-folder
        # src/main.ts(2,34): error TS2307: Cannot find module './app.ngfactory'.
        # Unexpected value 'BrowserModule in /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-58883IJeiUMLGHRRQ/node_modules/@angular/platform-browser/src/browser.d.ts' imported by the module 'AppModule in /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-58883IJeiUMLGHRRQ/src/app.ts'. Please add a @NgModule annotation.
        # ```
        "i18n",
        # `ivy-i18n` fails with:
        # ```
        # ERROR in Unexpected value 'BrowserModule in /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-59999cYHm5rQoUk0v/node_modules/@angular/platform-browser/src/browser.d.ts' imported by the module 'AppModule in /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-59999cYHm5rQoUk0v/src/app/app.module.ts'. Please add a @NgModule annotation.
        # @angular/core/src/i18n/tokens.ts(31,22): Error during template compile of 'LOCALE_ID'
        # Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
        # Can't resolve all parameters for AppComponent in /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-59999cYHm5rQoUk0v/src/app/app.component.ts: (?).
        # The pipe 'percent' could not be found ("
        # </div>
        # <p id="locale">{{ locale }}</p>
        # <p id="pipe">{{ [ERROR ->]1 | percent }} awesome</p>
        # <p id="date">{{ jan | date : 'LLLL' }}</p>
        # <h2>Here are some links to help")
        # The pipe 'date' could not be found ("
        # <p id="locale">{{ locale }}</p>
        # <p id="pipe">{{ 1 | percent }} awesome</p>
        # <p id="date">{{ [ERROR ->]jan | date : 'LLLL' }}</p>
        # <h2>Here are some links to help you start: </h2>
        # <ul>
        # ")
        # ```
        "ivy-i18n",
        # `cli-hello-world-ivy-i18n` fails with:
        # ```
        # ERROR in Unexpected value 'BrowserModule in /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-59695c6NwKC6Djcv4/node_modules/@angular/platform-browser/src/browser.d.ts' imported by the module 'AppModule in /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-59695c6NwKC6Djcv4/src/app/app.module.ts'. Please add a @NgModule annotation.
        # @angular/core/src/i18n/tokens.ts(31,22): Error during template compile of 'LOCALE_ID'
        #   Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
        # Can't resolve all parameters for AppComponent in /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-59695c6NwKC6Djcv4/src/app/app.component.ts: (?).
        # The pipe 'percent' could not be found ("1 i18n="some:description"> Hello {{ title }}! </h1>
        # <p id="locale">{{ locale }}</p>
        # <p id="pipe">{{ [ERROR ->]1 | percent }} awesome</p>
        # <p id="date">{{ jan | date : 'LLLL' }}</p>
        # ")
        # The pipe 'date' could not be found ("
        # <p id="locale">{{ locale }}</p>
        # <p id="pipe">{{ 1 | percent }} awesome</p>
        # <p id="date">{{ [ERROR ->]jan | date : 'LLLL' }}</p>
        # ")
        # ```
        "cli-hello-world-ivy-i18n",
        # `dynamic-compiler` has .ngfactory imports:
        # ```
        # $ ngc && yarn run closure && concurrently "yarn run serve" "yarn run protractor" --kill-others --success first
        # src/main.ts(2,34): error TS2307: Cannot find module './app.ngfactory'.
        # Unexpected value 'BrowserModule in /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-620291x2ZHDyIWIdL/node_modules/@angular/platform-browser/src/browser.d.ts' imported by the module 'AppModule in /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-620291x2ZHDyIWIdL/src/app.ts'. Please add a @NgModule annotation.
        # ```
        "dynamic-compiler",
        # `ng_elements` has .ngfactory imports:
        # ```
        # $ ngc && yarn run closure && concurrently "yarn run serve" "yarn run protractor" --kill-others --success first
        # src/main.ts(2,34): error TS2307: Cannot find module './app.ngfactory'.
        # Unexpected value 'BrowserModule in /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-620291x2ZHDyIWIdL/node_modules/@angular/platform-browser/src/browser.d.ts' imported by the module 'AppModule in /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-620291x2ZHDyIWIdL/src/app.ts'. Please add a @NgModule annotation.
        # ```
        "ng_elements",
        # `platform-server` has .ngfactory imports:
        # ```
        # src/server.ts(15,47): error TS2307: Cannot find module './helloworld/app.server.ngfactory'.
        # src/server.ts(18,50): error TS2307: Cannot find module './transferstate/app.server.ngfactory'.
        # src/helloworld/client.ts(13,41): error TS2307: Cannot find module './app.ngfactory'.
        # src/transferstate/client.ts(13,44): error TS2307: Cannot find module './app.ngfactory'.
        # Error during template compile of 'HelloWorldModule'
        #   Function calls are not supported in decorators but 'BrowserModule' was called.
        # ```
        "platform-server",
        # `side-effects` fails on minor differences to snapshots:
        # ```
        # The following snapshots have changed:
        # Index: /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-629425HECGefnB0O7/snapshots/animations-browser/esm5.js
        # ============== [...]

2020-01-09 22:27 UTC, IgorMinar commented
@gregmagolan yes, I just realized the same thing. I ran the tests with `--config=ivy`. I'm retesting this now.

2020-01-10 17:25 UTC, gregmagolan commented
#34589 landed and this is now rebased into master and ready to go in

2020-01-14 09:43 UTC, gkalpak reviewed
I don't understand most of the changes, but looked through all of them and left some comments for the parts that I (kind of) understand :grin:

I am partly excited to have more tests moved over to bazel (for the performance benefits this brings) :tada: and at the same time quite worried that it complicates the setup significantly (and makes it so much harder (for me at least) to tweak/debug it - the setup, not the tests themselves) 😱

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +  const s = a.length > b.length ? a : b;
```suggestion
  const s = a.length < b.length ? a : b;
```

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +  const l = a.length > b.length ? b : a;
```suggestion
  const l = a.length < b.length ? b : a;
```

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +  let root = path.dirname(files[0]).split('/');
Will `.split('/')` work on Windows?

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +    if (root.length <= 1) break;
Why break if `root.length === 1`?

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +      const dest = path.posix.join(to, rel);
`path.posix` hardly ever does what people think it does :grin:
It is better to use `${to}/${rel}` imo (or use [canonical-path][1], which is already a dependency in `package.json`).

[1]: https://www.npmjs.com/package/canonical-path

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +      log_verbose(`copying file ${src} -> ${dest}`);
```suggestion
      log_verbose(`copied file ${src} -> ${dest}`);
```

:grin:

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +  log(`test command ${testRunner.successful+1} failed with status code ${result}`);
Wouldn't it be useful to also log the actual command that failed?

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +  log(`test may be re-run manually under ${testRunner.testRoot}`);
No idea what this means :grin:

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +class TestRunner {
Could you add some comments explaining what the various variables/methods are for? It would make it much easier to understand the code.

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +      if (spawnedProcess.status) {
According to [the docs][1], `status` will be `null` if the subprocess terminated due to a signal.
I believe we shouldn't record it as a success in that case.

[1]: https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +      const subdir = root.split('/').slice(1).join('/');
What if `root` is an absolute path (i.e. starting with `/`)? Is that not possible?

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +        if (index == -1) {
Nit:
```suggestion
        if (index === -1) {
```

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +            path.posix.join(runfilesPath.substr(0, index), 'DO_NOT_BUILD_HERE'),
`.posix` is not necessary here. `readFileSync()` will work fine with `path.join()` and `${...}/DO_NOT_BUILD_HERE`.

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +      this.testRoot = path.posix.join(workspaceDirectory, subdir);
Again , `.posix` rarely does what people think it does, so I recommend not using it (it might give a false sense of security :grin:).
You have to ensure that `workspaceDirectory` and `subdir` are in POSIX format anyway, at which point manually concatenating with `/` is sufficient.

2020-01-14 09:43 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +process.exit(result);
Just to confirm:
This file is _not_ intended to be used directly. It is intended to be used by bazel, right?

2020-01-16 04:12 UTC, gregmagolan commented on integration/angular_integration_test.bzl
> +            "CI_CHROMEDRIVER_VERSION_ARG",
Yes. webdriver-manager will still download some version of the chrome driver but it is not guaranteed to work with your locally install version. At least that is my experience; it doesn't look like it check what version to install to work with your local chrome.

2020-01-16 04:14 UTC, gregmagolan commented on integration/angular_integration_test.bzl
> +# Copyright 2017 The Bazel Authors. All rights reserved.
Copy & paste artifact from rules_nodejs. I'll update. Thanks.

2020-01-16 04:15 UTC, gregmagolan commented on integration/BUILD.bazel
> +        "terser",
Yes. I don't know of anyway to glob directories and auto-generate targets in bazel. That being said, integration tests are not added often and it will be pretty obvious if you run `bazel test` on a non-existant target :)

2020-01-16 10:23 UTC, gkalpak commented on integration/angular_integration_test.bzl
> +            "CI_CHROMEDRIVER_VERSION_ARG",
Yes, webdriver-manager downloads the latest version of ChromeDriver if you don't specify the version. This is usually fine locally, because Chrome auto-updates so people are likely to have a reasonably recent version of Chrome, which the latest ChromeDriver is compatible with.

Let me re-phrase the question(s):

1. Will bazel error if `CI_CHROMEDRIVER_VERSION_ARG` is not defined (because it will generally only be defined on CI, not locally)?

2. Does bazel use its own version of Chrome/Chromium? (If it uses the one from the host machine, then we're fine.)

2020-01-16 18:08 UTC, gregmagolan commented on integration/angular_integration_test.bzl
> +            "CI_CHROMEDRIVER_VERSION_ARG",
Bazel itself doesn't care if the env is there or not; it just forwards the environment variable to the integration test if it is there and after that the integration test runs much the same as it does outside of bazel.

The integration tests consume it in their "postinstall",
```
"postinstall": "webdriver-manager update --gecko=false --standalone=false $CI_CHROMEDRIVER_VERSION_ARG && ngcc --properties es2015 --create-ivy-entry-points"
```

it is set to `setPublicVar CI_CHROMEDRIVER_VERSION_ARG "--versions.chrome 75.0.3770.90";` in CI and locally you can either have it set or not. If not set then $CI_CHROMEDRIVER_VERSION_ARG is just evaluated to "" by yarn.

For the integration tests anyway, these have to run locally and outside of the Bazel sandbox (they are all tagged `"no-sandbox", "no-remote-exec",` so as they do require the local version of chrome. Bazel doesn't do anything special with the integration tests which is why it doesn't manage the version of chrome for the tests (it does manage the version of chrome & chromedriver for karma_web_test_suite & protractor_web_test_suite).

The main responsibility of the angular_integration_test rule (which is a macro around npm_integraiton_test which I plan to upstream to rules_nodejs so it doesn't have to be maintained here), is to modify the package.json of the integration test to point to the bazel built @angular npm packages (+ the zone.js package and the npm packages pulled down by the root yarn_install).

2020-01-21 01:43 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +process.exit(result);
Yes. This file is part of the rule.

2020-01-21 01:44 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +        if (index == -1) {
👍

2020-01-21 01:50 UTC, gregmagolan commented on integration/dynamic-compiler/e2e/protractor.config.js
> +  // Port comes from lite-serve config `/e2e/browser.config.json` `"port": 4207`
👍

2020-01-21 01:58 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +      const subdir = root.split('/').slice(1).join('/');
Is not be possible as the testfiles as specified in Bazel manifest file format. But I will add an extra check and fail to make that clear.

2020-01-21 02:01 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +            path.posix.join(runfilesPath.substr(0, index), 'DO_NOT_BUILD_HERE'),
:) Simplified

2020-01-21 02:05 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +      this.testRoot = path.posix.join(workspaceDirectory, subdir);
👍

2020-01-21 04:48 UTC, gregmagolan commented
Add some notes on running these integration tests with Bazel to integration/README.md and added a yarn script to limit the concurrent tests to 4. HOST_CPUS*0.5 as suggested in Bazel docs did not work for me---it may just not work on OSX.

------------------------------------

These tests can be resource intensive so it is recommended to limit the number of concurrent test jobs with the `--local_test_jobs` flag.

For local testing, you can use

```
yarn test-integration ...
```

to have reasonable local_test_jobs resource limit set.

Two of the integration tests that run Bazel-in-Bazel are particularly resource intensive and are tagged "manual" and "exclusive". To run these tests use,

```
yarn test-integration //integration:bazel_test
yarn test-integration //integration:bazel-schematics_test
```

2020-01-21 04:49 UTC, gregmagolan commented
For most devs they can run all but the bazel-in-bazel tests with locally `yarn test-integration ...`

2020-01-21 20:40 UTC, josephperrott reviewed
LGTM, @IgorMinar will still need to review as well

2020-01-22 16:13 UTC, filipesilva commented on .bazelrc
> +run --action_env=CI_CHROMEDRIVER_VERSION_ARG
What about setups that use puppeteer inside node_modules? Those setups shouldn't need to set `CI_CHROMEDRIVER_VERSION_ARG` right?

2020-01-22 16:21 UTC, filipesilva commented on integration/BUILD.bazel
> +#   cli-hello-world-ivy-minimal         4204        /package.json: ng e2e --port 4204
`ng e2e` should automatically pock a post that's not in use.

2020-01-22 16:24 UTC, filipesilva commented on integration/BUILD.bazel
> +        "terser",
I think the bad case is the other way around: a test is added to the integration folder and no one knows it's not running, because it was running before.

2020-01-22 16:30 UTC, filipesilva commented on integration/cli-hello-world-ivy-compat/e2e/protractor.conf.js
> +const headless = process.env['BAZEL_TARGET'] && !process.env['BUILD_WORKSPACE_DIRECTORY'];
Could we just change all these integration tests to use puppeteer and always be headless instead?

2020-01-22 16:35 UTC, filipesilva commented on .circleci/config.yml
> +          # Run "exclusive" and "manual" bazel-in-bazel integrqation tests in their own CI job
`integrqation`->`integration`

2020-01-22 16:36 UTC, filipesilva commented on third_party/github.com/yarnpkg/yarn/releases/BUILD.bazel
> +exports_files(["download/v1.21.1/bin/yarn.js"])
I suppose not having the version name on the path would work as well.

2020-01-22 19:40 UTC, gregmagolan commented on .circleci/config.yml
> +          # Run "exclusive" and "manual" bazel-in-bazel integrqation tests in their own CI job
👍

2020-01-22 19:41 UTC, gregmagolan commented on integration/cli-hello-world-ivy-compat/e2e/protractor.conf.js
> +const headless = process.env['BAZEL_TARGET'] && !process.env['BUILD_WORKSPACE_DIRECTORY'];
Good question. Bazel is not doing anything special here so if you can change the tests to use puppeteer & always be headless outside of Bazel then bazel can execute them.

2020-01-22 19:42 UTC, gregmagolan commented on integration/BUILD.bazel
> +#   cli-hello-world-ivy-minimal         4204        /package.json: ng e2e --port 4204
That's good to know. I did run into port conflicts when running them in parallel but that may have been with the integration tests that are not using `ng e2e`?

2020-01-22 20:18 UTC, filipesilva commented on integration/BUILD.bazel
> +#   cli-hello-world-ivy-minimal         4204        /package.json: ng e2e --port 4204
I think ng test will still have port problems, it's just ng e2e that figures it out automatically. Maybe we could do the same for ng test.

2020-01-22 21:53 UTC, gregmagolan commented on integration/BUILD.bazel
> +#   cli-hello-world-ivy-minimal         4204        /package.json: ng e2e --port 4204
Hmmm. Maybe not so trivial as the port number that ng e2e uses has to match the port number in protractor.conf.js:
```
  // Port comes from package.json `e2e` script `ng e2e --port 4202`
  baseUrl: 'http://localhost:4202/',
```
Automatic ports would be preferable but maybe best to leave that for a follow up PR

2020-01-22 22:39 UTC, filipesilva commented on integration/BUILD.bazel
> +#   cli-hello-world-ivy-minimal         4204        /package.json: ng e2e --port 4204
Angular cli will automatically replace that too, otherwise it wouldn't work at all.

2020-01-23 01:09 UTC, IgorMinar requested changes
posting what I have so far.. more reviews coming

2020-01-23 01:09 UTC, IgorMinar commented on integration/README.md
> +The PR https://github.com/angular/angular/pull/33927 added the ability to run integration tests with Bazel. These tests can be resource intensive so it is recommended to limit the number of concurren
```suggestion
The PR https://github.com/angular/angular/pull/33927 added the ability to run integration tests with Bazel. These tests can be resource intensive so it is recommended to limit the number of concurrent test jobs with the `--local_test_jobs` bazel flag.
```

2020-01-23 01:09 UTC, IgorMinar commented on integration/README.md
> +to have reasonable local_test_jobs resource limit set.
```suggestion
which sets reasonable `local_test_jobs` limit to prevent full cpu utilization during local development test runs.
```

2020-01-23 01:09 UTC, IgorMinar commented on integration/angular_integration_test.bzl
> +            "CI_CHROMEDRIVER_VERSION_ARG",
it seems that we all feel uneasy about CI_CHROMEDRIVER_VERSION_ARG :) 

what would it take for bazel to correctly set `CHROME_BIN` env var and have karma and protractor automatically pick it up? that way the chrome version is managed by bazel and we won't run into version mismatches. Karma seems to support this OOB: http://karma-runner.github.io/4.0/config/browsers.html I'm not sure about protractor

2020-01-23 05:47 UTC, alan-agius4 commented on integration/BUILD.bazel
> +#   cli-hello-world-ivy-minimal         4204        /package.json: ng e2e --port 4204
@gregmagolan, for protractor (`ng e2e`) you can use port 0 either via `--port` command line option or provide this via the `angular.json`, as @filipesilva mentioned the `baseUrl` will be automatically replaced by the CLI.

Karma, always try to find an available port when spawning the server. https://github.com/karma-runner/karma/blob/f28a454fcbc9f3e9a58adc62a1afa9477688d871/lib/utils/net-utils.js

2020-01-23 07:22 UTC, gregmagolan commented on .circleci/config.yml
> +    parallelism: 3
Yes. It balances well with 3 now as its only the tests with size checks. Those will be removed in follow up PR.

2020-01-23 07:33 UTC, gregmagolan commented on .circleci/config.yml
> +          # Don't use `yarn test-non-ivy ...` as we want to include the //integration/... tests
Hmmm. Didn't see a comment on package.json.

2020-01-23 11:18 UTC, gkalpak commented on .bazelrc
> +run --action_env=CI_CHROMEDRIVER_VERSION_ARG
@IgorMinar, not sure how you got that error. Integration tests are supposed to have a `postinstall` that installs ChromeDriver.

When `CI_CHROMEDRIVER_VERSION_ARG` is defined (which is only intended to be defined on CI), it will dictate the ChromeDriver version to install (which is pinned to a version compatible with the version of Chrome on CI).

When running locally (where `CI_CHROMEDRIVER_VERSION_ARG` is not supposed to be defined), the `postinstall` script should install the latest ChromeDriver version (which is compatible with the latest Chrome version) and this should generally work locally, because Chrome is auto-updated, so people usually have a reasonably recent version.

##
(For a little extra deps size) we could indeed use `puppeteer` to ensure the same version of Chrome is used locally and on CI and then update all `postinstall` scripts to have them install a compatible ChromeDriver version.

(Personally, I don't feel strongly either way :grin:)

2020-01-23 11:46 UTC, filipesilva commented on .bazelrc
> +run --action_env=CI_CHROMEDRIVER_VERSION_ARG
Using puppeteer we could have this node script on postinstall:

2020-01-23 23:31 UTC, IgorMinar commented on .circleci/config.yml
> +          # Don't use `yarn test-non-ivy ...` as we want to include the //integration/... tests
I didn't get to it that far down!! too many files to review, but what I was going to say is that we shouldn't exclude the integration tests from the package.json scripts. if people don't want to run them they should specify a more specific path, like `yarn test-ivy-aot packages/...`.

2020-02-02 18:46 UTC, gregmagolan commented
Remote exec jobs have no network access and there doesn't seem to be any way to allow them to access the network. When running the integration tests remote (which is now possible since we use puppeteer), 
yarn reports:
```
yarn install v1.21.1
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
```
The `no-sandbox` and `requires-network` flags don't seem to have any effect on RBE. If the actions can't get network access remotely then I can work-around it by splitting out the yarn install into a separate build action that tars up the whole node_modules and passes it to the test. The former would have to run locally... however for cross-platform RBE this would still break as only yarn running on the remote executor will download the correct Linux Chrome binaries.

2020-02-02 18:47 UTC, gregmagolan commented
Also.. for local testing on OSX without remote-exec I need to make a change to yarn_install so that it provides a variant of the `@npm//puppeteer:puppeteer__files` filegroup which includes all the files with spaces. These are not included in that filegroup as those files break runfiles... but for the purposes of the integration test we need to include ALL files in the from node_modules/puppeteer in the `pkg_tar` that is generated for the integration test as on OSX the Chrome libs include files with spaces.

2020-02-04 16:04 UTC, gregmagolan commented
NB: For this PR to work on OSX it will depend on https://github.com/bazelbuild/rules_nodejs/pull/1600 landing and a 1.3.0 rules_nodejs release. This is because the node_modules/puppeteer pkg_tar on OSX needs to include files with spaces to include the Chrome libs which the `@npm//puppeteer__files` target does not currently include as these are not valid in Bazel runfiles due to https://github.com/bazelbuild/bazel/issues/5153.

https://github.com/bazelbuild/rules_nodejs/pull/1600 adds the `@npm//puppeteer__all_files` target which includes all files in the pkg including those with spaces and unicode characters. This target is not valid in runfiles.

2020-02-13 05:11 UTC, IgorMinar submitted a review, later dismissed
This is shaping up! It seems to run well on CI, but locally on linux I got:

```
$ yarn bazel test integration/...
yarn run v1.21.1
$ bazel test integration/...
Starting local Bazel server and connecting to it...
ERROR: /usr/local/google/home/iminar/.cache/bazel/_bazel_iminar/5a3cbc86f1e9dcb3e42cd9cb5b755e5a/external/npm/@schematics/angular/BUILD.bazel:96:1: no such target '@npm//:node_modules/@schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel': target 'node_modules/@schematics/angular/third_party/github.com/Microsoft/TypeScript/BUILD.bazel' not declared in package '' (did you mean 'node_modules/@schematics/angular/third_party/github.com/Microsoft/TypeScript/_BUILD.bazel'?) defined by /usr/local/google/home/iminar/.cache/bazel/_bazel_iminar/5a3cbc86f1e9dcb3e42cd9cb5b755e5a/external/npm/BUILD.bazel and referenced by '@npm//@schematics/angular:angular__files'
ERROR: Analysis of target '//integration:platform-server_test' failed; build aborted: Analysis failed
INFO: Elapsed time: 15.805s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (400 packages loaded, 17939 targets configured)
FAILED: Build did NOT complete successfully (400 packages loaded, 17939 targets configured)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Is this expected? I'd think that if it runs on CI then it should run on linux...

2020-02-13 05:11 UTC, IgorMinar commented on integration/platform-server/package.json
> +    "tsickle": "file:../../node_modules/tsickle",
that is supicious.

2020-02-13 05:11 UTC, IgorMinar commented on karma-js.conf.js
> +      'dist/all/angular1_router.js',
yup

2020-02-13 05:11 UTC, IgorMinar commented on integration/BUILD.bazel
> +# Unique ports must be managed manually or some effort must be put into
per conversation elsewhere - can't we rely on auto-assigned ports? I believe both protractor and karma support ephemeral port assignment.

I believe @filipesilva commented about that somewhere.

2020-02-13 17:42 UTC, gregmagolan commented on .bazelignore
> +integration/cli-hello-world/.yarn_local_cache
There was an old issue about this for bazel and a new one just got opened up by Or from Wix. https://github.com/bazelbuild/bazel/issues/7093. I commented there. Hopefully will get fixed soon as this file is getting out of hand.

2020-02-13 17:48 UTC, gregmagolan commented on integration/BUILD.bazel
> +# Unique ports must be managed manually or some effort must be put into
Yes. I've already switched all of the `ng e2e` calls by adding `-port 0` which makes them auto-select in an upper port range. The ones remaining here have no auto-select capabilities.

2020-02-13 17:51 UTC, gregmagolan commented on .bazelrc
> +run --action_env=CI_CHROMEDRIVER_VERSION_ARG
Puppeteer pre-factor PR resolves this.

2020-02-13 17:53 UTC, gregmagolan commented on integration/platform-server/package.json
> +    "tsickle": "file:../../node_modules/tsickle",
Not sure why it is needed. I'll will check. The dep needed to be added a previously the require would resolve to the root `node_modules/tsickle` but now these integration tests are sandboxed so the root node_modules is no longer accessible.

2020-02-13 18:03 UTC, gregmagolan commented on .bazelignore
> +integration/cli-hello-world/.yarn_local_cache
Oh. That issue is from Jan 11, 2019. Not 2020. 🙄

2020-02-13 18:16 UTC, gregmagolan commented on integration/platform-server/package.json
> +    "tsickle": "file:../../node_modules/tsickle",
The require comes from @angular/compiler-cli/src/main.js:106:24:

```
[test_runner.js] running test command 5 of 6: '/private/var/tmp/_bazel_greg/5e8f8a9cd1c6fbc1afd11e37ee1fe2e5/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/platform-server_test.sh.runfiles/nodejs_darwin_amd64/bin/yarnpkg/bin/yarn.js test' in '/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-66121FEtpcF6jrJT9'
yarn run v1.19.1
$ npm run build && concurrently "npm run serve" "npm run protractor" --kill-others --success first
npm WARN lifecycle The node binary used for scripts is /var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/yarn--1581617600241-0.7974424442979304/node but npm is using /private/var/tmp/_bazel_greg/5e8f8a9cd1c6fbc1afd11e37ee1fe2e5/external/nodejs_darwin_amd64/bin/nodejs/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> platform-server-integration@0.0.0 build /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-66121FEtpcF6jrJT9
> ./build.sh

Error: Cannot find module 'tsickle'
Require stack:
- /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-66121FEtpcF6jrJT9/node_modules/@angular/compiler-cli/src/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-66121FEtpcF6jrJT9/node_modules/@angular/compiler-cli/src/main.js:106:24
    at AngularCompilerProgram._emitRender2 (/private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-66121FEtpcF6jrJT9/node_modules/@angular/compiler-cli/src/transformers/program.js:377:34)
    at AngularCompilerProgram.emit (/private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-66121FEtpcF6jrJT9/node_modules/@angular/compiler-cli/src/transformers/program.js:201:25)
    at Object.performCompilation (/private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-66121FEtpcF6jrJT9/node_modules/@angular/compiler-cli/src/perform_compile.js:242:29)
    at main (/private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-66121FEtpcF6jrJT9/node_modules/@angular/compiler-cli/src/main.js:43:36)
    at /private/var/folders/0l/nj_q9kzj49gdz1w6f5v9tw3h0000gn/T/tmp-66121FEtpcF6jrJT9/node_modules/@angular/compiler-cli/src/main.js:215:28

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! platform-server-integration@0.0.0 build: `./build.sh`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the platform-server-integration@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/greg/.npm/_logs/2020-02-13T18_13_25_360Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2020-02-13 18:25 UTC, josephperrott commented on WORKSPACE
> +    sha256 = "b6670f9f43faa66e3009488bbd909bc7bc46a5a9661a33f6bc578068d1837f37",
We should do the `rules_nodejs 1.3.0` update in its own PR.

2020-02-13 18:26 UTC, gregmagolan commented on WORKSPACE
> +    sha256 = "b6670f9f43faa66e3009488bbd909bc7bc46a5a9661a33f6bc578068d1837f37",
Sure. Its a separate commit and required for this PR for OSX to work but I can pre-factor it.

2020-02-14 03:02 UTC, gregmagolan commented on .bazelrc
> +run --action_env=CI_CHROMEDRIVER_VERSION_ARG
Borrowed @gkalpak fix for this in https://github.com/angular/angular/pull/35381 and resolved.

2020-02-14 03:03 UTC, gregmagolan commented on integration/angular_integration_test.bzl
> +            "CI_CHROMEDRIVER_VERSION_ARG",
Puppeteer PR in an CI_CHROMEDRIVER_VERSION_ARG is no longer required for any integration tests

2020-02-14 03:04 UTC, gregmagolan commented on integration/BUILD.bazel
> +#   cli-hello-world-ivy-minimal         4204        /package.json: ng e2e --port 4204
Updated to use `ng e2e --port 0`

2020-02-14 03:07 UTC, gregmagolan commented on integration/hello_world__closure/e2e/protractor.config.js
> +  // Port comes from lite-serve config `/e2e/browser.config.json` `"port": 4208`
👍

2020-02-14 03:08 UTC, gregmagolan commented on integration/i18n/e2e/protractor.config.js
> +  // Port comes from lite-serve config `/e2e/browser.config.json` `"port": 4210`
👍

2020-02-14 03:08 UTC, gregmagolan commented on integration/ng_elements/e2e/protractor.config.js
> +  // Port comes from lite-serve config `/e2e/browser.config.json` `"port": 4212`
👍

2020-02-14 03:08 UTC, gregmagolan commented on integration/hello_world__systemjs_umd/protractor.config.js
> +  // Port comes from lite-serve config `/bs-config.e2e.json` `"port": 4209`
👍

2020-02-14 03:11 UTC, gregmagolan commented on integration/platform-server/package.json
> +    "tsickle": "file:../../node_modules/tsickle",
Ahh I see,

The tsconfig.json files for a number of integration tests has

```
  "angularCompilerOptions": {
    "annotationsAs": "static fields",
    "annotateForClosureCompiler": true,
  },
```
which triggers the require in compiler-cli

2020-02-14 03:14 UTC, gregmagolan commented on integration/platform-server/package.json
> +    "tsickle": "file:../../node_modules/tsickle",
The four are:
* `hello_world__closure`
* `i18n`
* `ng_elements`
* `platform-server`
The first three actually use closure compiler but platform-server probably just a copy & past artifact. I'll remove it.

2020-02-14 03:15 UTC, gregmagolan commented on tools/npm_integration_test/BUILD.bazel
> +# Copyright 2017 The Bazel Authors. All rights reserved.
Copy & paste from rules_nodejs. Will fix up thanks.

2020-02-14 03:15 UTC, gregmagolan commented on tools/npm_integration_test/npm_integration_test.bzl
> +# Copyright 2017 The Bazel Authors. All rights reserved.
Copy & paste from rules_nodejs. Will fix up thanks.

2020-02-14 03:17 UTC, gregmagolan commented on karma-js.conf.js
> +      'dist/all/angular1_router.js',
Removed 'dist/all/angular1_router.js' 👍

2020-02-14 03:18 UTC, gregmagolan commented on integration/platform-server/e2e/protractor.config.js
> +  // Port comes from lite-serve config `/src/server.ts` `app.listen(4213,...`
👍

2020-02-14 03:19 UTC, gregmagolan commented on third_party/github.com/yarnpkg/yarn/releases/BUILD.bazel
> +exports_files(["download/v1.21.1/bin/yarn.js"])
`third_party/github.com/yarnpkg/yarn` removed now in favor of `.yarnrc` `yarn-path ".yarn/releases/yarn-1.21.1.js"`

2020-02-14 03:21 UTC, gregmagolan commented on tools/ts-api-guardian/test/bootstrap.ts
> +    path.dirname(runfiles.resolve('angular/tools/ts-api-guardian/test/fixtures/empty.ts')))));
Actually runfiles.resolve should be able to resolve a directory. The previous require.resolve couldn't and that was left over from there. The path.resolve with `../../..` would have been much cleaner tho thanks.

2020-02-14 03:39 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +  console.error('[test_runner.js]');
👍

2020-02-14 03:45 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +  const s = a.length > b.length ? a : b;
Nice catch. This seems easier to follow:
```
function commonSlice(a, b) {
  const p = a.length < b.length ? [a,b] : [b,a];
  for (let i = 0; i < p[0].length; ++i) {
    if (p[0][i] !== p[1][i]) {
      return p[0].slice(0, i);
    }
  }
  return p[0];
}
```

2020-02-14 03:48 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +      const dest = path.posix.join(to, rel);
👍

2020-02-14 03:48 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +      log_verbose(`copying file ${src} -> ${dest}`);
👍

2020-02-14 03:49 UTC, gregmagolan commented on packages/bazel/package.bzl
> +    _maybe(
no longer in diff

2020-02-14 03:54 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +      if (spawnedProcess.status) {
You are correct. Added check for `error` first:
```
          if (spawnedProcess.error) {
            fail(
                `test command '${binary} ${args.join(' ')}' failed with ${spawnedProcess.error.code}`);
          }
          if (spawnedProcess.status) {
            return spawnedProcess.status;
          }
```

2020-02-14 04:21 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +  log(`test command ${testRunner.successful+1} failed with status code ${result}`);
👍

2020-02-14 04:38 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +  log(`test may be re-run manually under ${testRunner.testRoot}`);
add some more verboseness :)

2020-02-14 04:46 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +class TestRunner {
👍

2020-02-14 05:03 UTC, gregmagolan commented on tools/ts-api-guardian/test/bootstrap.ts
> +    path.dirname(runfiles.resolve('angular/tools/ts-api-guardian/test/fixtures/empty.ts')))));
Actually, nevermind, on Windows there is a reason to resolve to the full `empty.ts`. Added a comment on that.
```
// NB: we resolve `test/fixtures/empty.ts` and then step up 3 folders so to ensure we resolve to the
//     root of the source tree and not the output tree on Windows where there are no runfiles.
```

2020-02-14 05:38 UTC, gregmagolan commented on integration/cli-hello-world-ivy-compat/e2e/protractor.conf.js
> +const headless = process.env['BAZEL_TARGET'] && !process.env['BUILD_WORKSPACE_DIRECTORY'];
Done

2020-02-14 05:39 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +  let root = path.dirname(files[0]).split('/');
Good question. I think bazel will always pass down `/` paths but added `.replace(/\\/g, '/')` to be sure.

2020-02-14 05:48 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +    if (root.length <= 1) break;
Should be `if (!root.length) break;`. Thanks!

2020-02-14 05:48 UTC, gregmagolan commented on WORKSPACE
> +    sha256 = "b6670f9f43faa66e3009488bbd909bc7bc46a5a9661a33f6bc578068d1837f37",
Done.

2020-02-14 08:08 UTC, IgorMinar commented
when testing this on my mac I got:

```
$ yarn bazel test integration/...
yarn run v1.21.1
$ bazel test integration/...
WARNING: Download from https://mirror.bazel.build/nodejs.org/dist/v12.14.1/node-v12.14.1-darwin-x64.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: error loading package 'integration/cli-hello-world-ivy/node_modules/@angular/cli/node_modules/rxjs/src/ajax': Unable to find package for @build_bazel_rules_typescript//:defs.bzl: The repository '@build_bazel_rules_typescript' could not be resolved.
INFO: Elapsed time: 0.628s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded)
FAILED: Build did NOT complete successfully (2 packages loaded)
    currently loading: integration/cli-hello-world-ivy/node_modules/@angular/cli/node_modules/rxjs/src
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I had to:
```
23:48 $ rm -rf integration/cli-hello-world-ivy/node_modules/
```

and only then `yarn bazel test integration/...` started building...I suspect that this will be quite common issue for people already working on the repo to hit, so we might need to do something to make onboarding easier.

I'll post the results of that tomorrow (it's still building). 

The good news is that on my linux machine everything worked on the first try:
```
INFO: Build completed successfully, 1351 total actions
//integration:cli-hello-world-ivy-compat_test                            PASSED in 106.2s
//integration:cli-hello-world-ivy-i18n_test                              PASSED in 141.4s
//integration:cli-hello-world-ivy-minimal_test                           PASSED in 102.4s
//integration:cli-hello-world-lazy-rollup_test                           PASSED in 118.3s
//integration:cli-hello-world-lazy_test                                  PASSED in 114.2s
//integration:cli-hello-world_test                                       PASSED in 110.3s
//integration:dynamic-compiler_test                                      PASSED in 66.5s
//integration:hello_world__closure_test                                  PASSED in 49.6s
//integration:hello_world__systemjs_umd_test                             PASSED in 41.5s
//integration:i18n_test                                                  PASSED in 79.1s
//integration:injectable-def_test                                        PASSED in 42.5s
//integration:ivy-i18n_test                                              PASSED in 208.9s
//integration:language_service_plugin_test                               PASSED in 26.3s
//integration:ng_elements_test                                           PASSED in 47.9s
//integration:ng_update_migrations_test                                  PASSED in 57.9s
//integration:ng_update_test                                             PASSED in 13.2s
//integration:ngcc_test                                                  PASSED in 153.1s
//integration:platform-server_test                                       PASSED in 60.2s
//integration:service-worker-schema_test                                 PASSED in 8.0s
//integration:side-effects_test                                          PASSED in 96.4s
//integration:terser_test                                                PASSED in 13.1s
//integration:typings_test_ts36_test                                     PASSED in 15.6s

Executed 22 out of 22 tests: 22 tests pass.
INFO: Build completed successfully, 1351 total actions
Done in 297.70s.
```

I'll also test this with mac+rbe setup, and review the PR again tomorrow. Thanks @gregmagolan !

2020-02-14 14:25 UTC, filipesilva approved these changes
I have some questions but leaving approval anyway as I'll be out next week.

2020-02-14 14:25 UTC, filipesilva commented on integration/bazel-schematics/package.json
> +    "@angular-devkit/build-angular": "file:../../node_modules/@angular-devkit/build-angular",
Why does this test suddenly need all these dependencies?

2020-02-14 14:25 UTC, filipesilva commented on integration/hello_world__systemjs_umd/protractor.config.js
> +  // Port comes from lite-serve config `/bs-config.e2e.json` `"port": 4203`
I find these quite helpful, thanks for adding them.

2020-02-14 15:42 UTC, IgorMinar commented
ok, by mac built results are in - two failures:
```
in debug mode the integration test will be run out of the workspace folder
================================================================================
INFO: Elapsed time: 2847.277s, Critical Path: 1024.45s
INFO: 949 processes: 727 darwin-sandbox, 44 local, 178 worker.
INFO: Build completed, 2 tests FAILED, 10647 total actions
//integration:cli-hello-world-ivy-compat_test                            PASSED in 436.8s
//integration:cli-hello-world-ivy-i18n_test                              PASSED in 541.1s
//integration:cli-hello-world-ivy-minimal_test                           PASSED in 793.5s
//integration:cli-hello-world-lazy-rollup_test                           PASSED in 659.8s
//integration:cli-hello-world-lazy_test                                  PASSED in 723.5s
//integration:cli-hello-world_test                                       PASSED in 687.7s
//integration:dynamic-compiler_test                                      PASSED in 420.0s
//integration:hello_world__closure_test                                  PASSED in 360.5s
//integration:hello_world__systemjs_umd_test                             PASSED in 346.3s
//integration:i18n_test                                                  PASSED in 455.6s
//integration:injectable-def_test                                        PASSED in 244.3s
//integration:ng_elements_test                                           PASSED in 317.0s
//integration:ng_update_migrations_test                                  PASSED in 395.3s
//integration:ng_update_test                                             PASSED in 104.1s
//integration:ngcc_test                                                  PASSED in 569.3s
//integration:platform-server_test                                       PASSED in 451.6s
//integration:service-worker-schema_test                                 PASSED in 63.5s
//integration:side-effects_test                                          PASSED in 198.0s
//integration:terser_test                                                PASSED in 64.0s
//integration:typings_test_ts36_test                                     PASSED in 112.4s
//integration:ivy-i18n_test                                              FAILED in 561.8s
  /private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/testlogs/integration/ivy-i18n_test/test.log
//integration:language_service_plugin_test                               FAILED in 109.3s
  /private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/testlogs/integration/language_service_plugin_test/test.log

Executed 22 out of 22 tests: 20 tests pass and 2 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones INFO: Build completed, 2 tests FAILED, 10647 total actions
```


<details>
<summary>//integration:language_service_plugin_test  log</summary>
<pre><code>
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //integration:language_service_plugin_test
-----------------------------------------------------------------------------
[test_runner.js] running in /private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/angular
[test_runner.js] test files from 'integration/language_service_plugin' copied to tmp folder /var/folders/1k/21j4lqbn2kzgv1xp50nw64g4003k9q/T/tmp-89189iwM7IG1hb7Xh
[test_runner.js] running test command 1 of 6: 'rm -rf ./.yarn_local_cache' in '/var/folders/1k/21j4lqbn2kzgv1xp50nw64g4003k9q/T/tmp-89189iwM7IG1hb7Xh'
[test_runner.js] running test command 2 of 6: 'mkdir .yarn_local_cache' in '/var/folders/1k/21j4lqbn2kzgv1xp50nw64g4003k9q/T/tmp-89189iwM7IG1hb7Xh'
[test_runner.js] running test command 3 of 6: patching 'package.json' in '/var/folders/1k/21j4lqbn2kzgv1xp50nw64g4003k9q/T/tmp-89189iwM7IG1hb7Xh'
[test_runner.js] overriding dependencies['jasmine'] npm package with 'file:/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/npm/jasmine_archive.tar.gz' in package.json file
[test_runner.js] overriding dependencies['typescript'] npm package with 'file:/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/npm/typescript_archive.tar.gz' in package.json file
[test_runner.js] overriding dependencies['@types/jasmine'] npm package with 'file:/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/npm/types_jasmine_archive.tar.gz' in package.json file
[test_runner.js] overriding dependencies['@types/node'] npm package with 'file:/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/npm/types_node_archive.tar.gz' in package.json file
[test_runner.js] overriding dependencies['@angular/core'] npm package with 'file:/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/angular/packages/core/npm_package_archive.tar.gz' in package.json file
[test_runner.js] overriding dependencies['@angular/language-service'] npm package with 'file:/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/angular/packages/language-service/npm_package_archive.tar.gz' in package.json file
[test_runner.js] package.json file:
{
  "name": "language_service_plugin",
  "version": "0.0.0",
  "license": "MIT",
  "description": "Angular Language Service plugin integration test",
  "dependencies": {
    "@angular/core": "file:/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/angular/packages/core/npm_package_archive.tar.gz",
    "@angular/language-service": "file:/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/angular/packages/language-service/npm_package_archive.tar.gz",
    "@types/jasmine": "file:/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/npm/types_jasmine_archive.tar.gz",
    "@types/node": "file:/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/npm/types_node_archive.tar.gz",
    "jasmine": "file:/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/npm/jasmine_archive.tar.gz",
    "typescript": "file:/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/npm/typescript_archive.tar.gz"
  },
  "scripts": {
    "build": "tsc -p tsconfig.json",
    "build-dist": "node ../../scripts/build-packages-dist.js && yarn install --check-files",
    "cleanup": "rm -rf ti-*.log tsserver.log",
    "golden": "yarn build && node generate.js",
    "test": "yarn cleanup && yarn build && jasmine test.js"
  }
}
[test_runner.js] running test command 4 of 6: '/private/var/tmp/_bazel_iminar/bab9b727392758142c2877c5be831963/execroot/angular/bazel-out/darwin-fastbuild/bin/integration/language_service_plugin_test.sh.runfiles/nodejs_da [...]

2020-02-14 17:58 UTC, gregmagolan commented on integration/bazel-schematics/package.json
> +    "@angular-devkit/build-angular": "file:../../node_modules/@angular-devkit/build-angular",
Its now sandboxed so they need to be explicitly added. Previously via the shell script they were getting picked up from the root /node_modules

2020-02-14 17:58 UTC, gregmagolan commented on .circleci/config.yml
> +  install_java:
The circle node browsers docker image included Java but now we're using the bare circleci node image since we have puppeteer :)

2020-02-14 18:02 UTC, gregmagolan commented
@IgorMinar 

Was `integration/cli-hello-world-ivy` an old integration test and you had the node_modules folder kicking around? 

We could add that to`.bazelignore` to prevent other devs from running into the same issue. It would be better if that file supported wildcards (`/integration/**/node_modules`) but bazel team is has not picked up that issue in over a year: https://github.com/bazelbuild/bazel/issues/7093.

2020-02-14 18:03 UTC, gregmagolan commented on integration/hello_world__systemjs_umd/protractor.config.js
> +  // Port comes from lite-serve config `/bs-config.e2e.json` `"port": 4203`
🌮

2020-02-14 18:06 UTC, gregmagolan commented on integration/BUILD.bazel
> +# The following tests should not be run with npm packages generated with `--config=ivy`
They were run against the non-ivy bundles in the legacy integration_test job and now they are run against the same in the `test` job. I added new coverage for integration tests against the ivy generated bundles in `test_ivy_aot` for a subset of the integration tests
```
[
        "cli-hello-world",
        "cli-hello-world-ivy-compat",
        "cli-hello-world-ivy-minimal",
        "cli-hello-world-lazy",
        "cli-hello-world-lazy-rollup",
        "language_service_plugin",
        "ng_update",
        "service-worker-schema",
        "terser",
    ]
```
but left out all the ones that failed with the Ivy bundles. Out of scope for this PR to migrate them and some of them like `ngcc` are designed to run on the ViewEngine bundles.

2020-02-14 18:27 UTC, gregmagolan commented
I had the same two failure when running all the tests on my mac:

```
//integration:cli-hello-world-ivy-compat_test                            PASSED in 851.2s
//integration:cli-hello-world-ivy-i18n_test                              PASSED in 879.0s
//integration:cli-hello-world-ivy-minimal_test                           PASSED in 851.4s
//integration:cli-hello-world-lazy-rollup_test                           PASSED in 853.2s
//integration:cli-hello-world-lazy_test                                  PASSED in 850.0s
//integration:cli-hello-world_test                                       PASSED in 851.8s
//integration:dynamic-compiler_test                                      PASSED in 443.2s
//integration:hello_world__closure_test                                  PASSED in 298.6s
//integration:hello_world__systemjs_umd_test                             PASSED in 455.6s
//integration:i18n_test                                                  PASSED in 513.2s
//integration:injectable-def_test                                        PASSED in 448.7s
//integration:ng_elements_test                                           PASSED in 261.3s
//integration:ng_update_migrations_test                                  PASSED in 659.7s
//integration:ng_update_test                                             PASSED in 241.7s
//integration:ngcc_test                                                  PASSED in 887.8s
//integration:platform-server_test                                       PASSED in 558.1s
//integration:service-worker-schema_test                                 PASSED in 43.6s
//integration:side-effects_test                                          PASSED in 412.5s
//integration:terser_test                                                PASSED in 165.7s
//integration:typings_test_ts36_test                                     PASSED in 248.0s
//integration:ivy-i18n_test                                             TIMEOUT in 901.1s
  /private/var/tmp/_bazel_greg/5e8f8a9cd1c6fbc1afd11e37ee1fe2e5/execroot/angular/bazel-out/darwin-fastbuild/testlogs/integration/ivy-i18n_test/test.log
//integration:language_service_plugin_test                               FAILED in 98.6s
  /private/var/tmp/_bazel_greg/5e8f8a9cd1c6fbc1afd11e37ee1fe2e5/execroot/angular/bazel-out/darwin-fastbuild/testlogs/integration/language_service_plugin_test/test.log
```

2nd run with all the other tests cached it passed so I think there is just a resource problem for local testing. Not surprising since we had to bump the CI machine to 16 cores & 36 gigs.

I suggested in the integration/README that the number of parallel jobs be capped when running locally:
```
yarn bazel test --local_test_jobs=4 //integration/...
```

If running `yarn test-non-ivy --local_test_jobs=4 ...` that should not hurt other tests if RBE is turned on as should only affect local tests and most tests will run remote. https://docs.bazel.build/versions/2.0.0/command-line-reference.html#flag--local_test_jobs

2020-02-14 18:33 UTC, gregmagolan commented
@IgorMinar Finally, for RBE, @josephperrott solved the network access on RBE executors (it was the docker image that was blocking it). However, we ran into then next problem of the webdriver-manager not having the downloaded chromedriver which it should get from the pkg_tar of the root `/node_modules/webdriver-manager` folder.

That one should be fairly easy to track down but there a larger problem with cross-platform RBE since yarn_install will always run on the host machine and this means that puppeteer will download the OSX chrome binary and webdriver-manager will download the OSX chromedriver. The only fix I can think of for that is to configure puppeteer and webdriver-manager to also download the linux binaries when running on OSX. Seems like we should leave that for a follow up.

2020-02-14 18:36 UTC, gregmagolan commented
One thing I haven't tried is to mark the integration tests as `size = "enormous"`. Bazel may do a better job scheduling them by default if it knows this. https://docs.bazel.build/versions/2.0.0/be/common-definitions.html

2020-02-14 18:53 UTC, filipesilva commented on .circleci/config.yml
> +  install_java:
Oh wow that was surprising, didn't expect the browser imagines to also randomly include that. Good thing it's explicit now. Again it highlights on how much we rely on hidden stuff from those images.

2020-02-14 18:55 UTC, filipesilva commented on integration/BUILD.bazel
> +# The following tests should not be run with npm packages generated with `--config=ivy`
Ok so those just stay around in the legacy job then, right? sgtm

2020-02-14 18:55 UTC, filipesilva commented on integration/bazel-schematics/package.json
> +    "@angular-devkit/build-angular": "file:../../node_modules/@angular-devkit/build-angular",
Ouch, good change then.

2020-02-14 19:55 UTC, gregmagolan commented
Doing some experimentation on my Mac which has 8 cores although for some reason the HOST_CPUS keyword in Bazel thinks there at 16.

Thus, for my machine, if I set `--local_test_jobs=HOST_CPUS*.3` that makes for a maximum of 5 concurrent test jobs which means I can still use my machine while running the integration tests in parallel.

@IgorMinar This seems like a value that each developer should set in their user .bazelrc for their own machine as it would be hard to come up with a reasonable number for all cases.

2020-02-14 20:14 UTC, gregmagolan commented on integration/BUILD.bazel
> +# The following tests should not be run with npm packages generated with `--config=ivy`
Yes. I presume the bundles we'll still be running tests against the non-ivy bundles for some time.

2020-02-14 20:26 UTC, gregmagolan commented
Some more beta on this. Limiting `--local_test_jobs=4` on my machine which has 8 cores everything passed in `INFO: Elapsed time: 1120.282s, Critical Path: 811.72s`.
```
INFO: Elapsed time: 1120.282s, Critical Path: 811.72s
INFO: 303 processes: 190 darwin-sandbox, 44 local, 69 worker.
INFO: Build completed successfully, 316 total actions
//integration:cli-hello-world-ivy-compat_test                            PASSED in 252.3s
//integration:cli-hello-world-ivy-i18n_test                              PASSED in 331.5s
//integration:cli-hello-world-ivy-minimal_test                           PASSED in 215.8s
//integration:cli-hello-world-lazy-rollup_test                           PASSED in 259.1s
//integration:cli-hello-world-lazy_test                                  PASSED in 222.2s
//integration:cli-hello-world_test                                       PASSED in 191.8s
//integration:dynamic-compiler_test                                      PASSED in 125.5s
//integration:hello_world__closure_test                                  PASSED in 103.2s
//integration:hello_world__systemjs_umd_test                             PASSED in 71.9s
//integration:i18n_test                                                  PASSED in 128.2s
//integration:injectable-def_test                                        PASSED in 64.8s
//integration:ivy-i18n_test                                              PASSED in 474.8s
//integration:language_service_plugin_test                               PASSED in 44.7s
//integration:ng_elements_test                                           PASSED in 122.7s
//integration:ng_update_migrations_test                                  PASSED in 157.8s
//integration:ng_update_test                                             PASSED in 35.5s
//integration:ngcc_test                                                  PASSED in 247.3s
//integration:platform-server_test                                       PASSED in 134.8s
//integration:service-worker-schema_test                                 PASSED in 24.3s
//integration:side-effects_test                                          PASSED in 73.5s
//integration:terser_test                                                PASSED in 29.6s
//integration:typings_test_ts36_test                                     PASSED in 43.8s
```
I think this was probably faster than letting Bazel parallelize with 8 cores as they were competing for resources and all taking longer individually. Plus it didn't freeze up my machine.

2020-02-15 10:58 UTC, gregmagolan commented
Since its a long weekend and this will a few more biz days to land I did some more work and experimentation.

* Removed dependency on local chrome from integration/bazel-schematics
* Remove "manual" tag from `integration/bazel` and `integration/bazel-schematics` and added `cpu:3` instead which seems to work well in CI so I was able to move these tests to the `test` job and bump it to `2xlarge+2` which as 20 cores & 40 gigs and remove the `test_integration_bazel` job.  Test job completes in 9m and change running all integration tests:

```
//integration:bazel-schematics_test                                      PASSED in 342.6s
//integration:bazel_test                                                 PASSED in 129.0s
//integration:cli-hello-world-ivy-compat_test                            PASSED in 145.9s
//integration:cli-hello-world-ivy-i18n_test                              PASSED in 163.1s
//integration:cli-hello-world-ivy-minimal_test                           PASSED in 106.8s
//integration:cli-hello-world-lazy-rollup_test                           PASSED in 159.3s
//integration:cli-hello-world-lazy_test                                  PASSED in 157.0s
//integration:cli-hello-world_test                                       PASSED in 160.3s
//integration:dynamic-compiler_test                                      PASSED in 58.7s
//integration:hello_world__closure_test                                  PASSED in 70.5s
//integration:hello_world__systemjs_umd_test                             PASSED in 67.7s
//integration:i18n_test                                                  PASSED in 64.5s
//integration:injectable-def_test                                        PASSED in 42.1s
//integration:ivy-i18n_test                                              PASSED in 255.3s
//integration:language_service_plugin_test                               PASSED in 27.5s
//integration:ng_elements_test                                           PASSED in 64.2s
//integration:ng_update_migrations_test                                  PASSED in 99.1s
//integration:ng_update_test                                             PASSED in 36.3s
//integration:ngcc_test                                                  PASSED in 203.0s
//integration:platform-server_test                                       PASSED in 54.0s
//integration:service-worker-schema_test                                 PASSED in 6.5s
//integration:side-effects_test                                          PASSED in 78.7s
//integration:terser_test                                                PASSED in 31.9s
//integration:typings_test_ts36_test                                     PASSED in 38.2s
//integration:typings_test_ts37_test                                     PASSED in 28.6s
```

* For local testing the `...` glob will now include `integration/bazel` and `integration/bazel-schematics` so if devs are testing `integration/...` they should set a `--local_test_jobs=<n>` that makes sense for their local machine.

2020-02-15 16:35 UTC, gregmagolan commented
For reference, locally limited to 4 local_test_jobs the suite of 25 tests (including bazel-in-bazel) took 17m:

```
INFO: Found 25 targets and 25 test targets...
INFO: Elapsed time: 1015.714s, Critical Path: 996.38s
INFO: 50 processes: 50 local.
INFO: Build completed successfully, 26 total actions
//integration:bazel-schematics_test                                      PASSED in 487.1s
//integration:bazel_test                                                 PASSED in 233.1s
//integration:cli-hello-world-ivy-compat_test                            PASSED in 185.3s
//integration:cli-hello-world-ivy-i18n_test                              PASSED in 297.8s
//integration:cli-hello-world-ivy-minimal_test                           PASSED in 215.2s
//integration:cli-hello-world-lazy-rollup_test                           PASSED in 207.9s
//integration:cli-hello-world-lazy_test                                  PASSED in 223.1s
//integration:cli-hello-world_test                                       PASSED in 230.2s
//integration:dynamic-compiler_test                                      PASSED in 130.5s
//integration:hello_world__closure_test                                  PASSED in 93.9s
//integration:hello_world__systemjs_umd_test                             PASSED in 82.1s
//integration:i18n_test                                                  PASSED in 89.7s
//integration:injectable-def_test                                        PASSED in 74.7s
//integration:ivy-i18n_test                                              PASSED in 410.3s
//integration:language_service_plugin_test                               PASSED in 33.4s
//integration:ng_elements_test                                           PASSED in 110.2s
//integration:ng_update_migrations_test                                  PASSED in 106.6s
//integration:ng_update_test                                             PASSED in 27.0s
//integration:ngcc_test                                                  PASSED in 341.4s
//integration:platform-server_test                                       PASSED in 119.6s
//integration:service-worker-schema_test                                 PASSED in 10.6s
//integration:side-effects_test                                          PASSED in 83.3s
//integration:terser_test                                                PASSED in 36.3s
//integration:typings_test_ts36_test                                     PASSED in 38.5s
//integration:typings_test_ts37_test                                     PASSED in 28.6s
```

2020-02-18 16:51 UTC, gregmagolan commented on .gitignore
> +.yarn_local_cache
The integration tests all create a `.yarn_local_cache` folder when run in `.debug` mode now since they are using `file:` references. 

Ohh. On further investigation . There is a `**/.yarn_local_cache*` entry in `/integration/.gitignore` so I can remove this line.

2020-02-18 16:53 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +          if (!!args[0]) {
👍

2020-02-18 16:53 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +    let contents = JSON.parse(fs.readFileSync(packageJson, {encoding: 'utf-8'}));
👍

2020-02-18 16:53 UTC, gregmagolan commented on integration/BUILD.bazel
> +# Karma automatically find a free port so no effort is needed there.
👍

2020-02-18 16:55 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +      const args = split.slice(1);
Yes. If there was a space in the path to the binary this would break. However, since Bazel doesn't allow paths with spaces in runfiles yet then this is not a problem (yet). I'll leave a TODO here. It will be obvious if it breaks.

2020-02-18 16:57 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +      const args = split.slice(1);
Arguments with spaces would be a problem as well most likely

2020-02-18 16:58 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +        case 'patch-package-json': {
It scopes the variables for the case statement :)

2020-02-18 17:03 UTC, gregmagolan commented on .bazelignore
>  integration/bazel-schematics/demo
That should be fine. This is only meant to ignore folders that may contain BUILD files as if those are seen by Bazel it tends to blow up.

2020-02-18 17:05 UTC, gregmagolan commented on .bazelignore
>  integration/bazel-schematics/demo
Some npm packages contain BUILD files which is why we need to ignore all of the node_modules & yarn_cache folders. Unfortunately, .bazelignore doesn't support wildcards or the other .gitignore semantics and each folder/file needs to be explicitly specified.

2020-02-18 17:05 UTC, gregmagolan commented on .bazelignore
>  integration/bazel-schematics/demo
Example error when there is a rogue BUILD file that Bazel sees which is not .bazelignored:
```
ERROR: error loading package 'integration/i18n/node_modules/browser-sync-client/node_modules/rxjs/src': Unable to find package for @build_bazel_rules_typescript//:defs.bzl: The repository '@build_bazel_rules_typescript' could not be resolved.
```

2020-02-18 17:11 UTC, gregmagolan commented on integration/ng_elements_schematics/package.json
> +    "shelljs": "0.8.3",
All the integration tests have a mix of `../../node_modules/` and straight up versions. FWICT, small inconsequential utility deps such as `concurrently` and `lite-server` are not synced with the root node_modules while others larger deps such as `protractor`, `@types/jasmine` typically are. I don't think the version of shelljs is consequential but I don't have a strong opinion either way.

2020-02-18 17:12 UTC, gregmagolan commented on integration/ngcc/test.sh
> +  # See https://github.com/angular/angular-cli/blob/e36853338/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts#L34)
👍 Ahh. I see. That indentation style threw me off.

2020-02-18 17:17 UTC, gregmagolan commented on karma-js.conf.js
> +      'dist/all/@angular/service-worker/**/test/**',
That's a good question. I actually don't recall how that made it in there. I'll test with it removed.

2020-02-18 17:17 UTC, gregmagolan commented on integration/bazel-schematics/test.sh
> +}
Yes. Not my favorite line of code ever but does the job.

2020-02-18 17:18 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +   * and so that and changes made to source files such as patching package.json
👍

2020-02-18 17:20 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +}
Nice! 🌮

2020-02-18 17:25 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +      const altKey = `**/${key}`;
I'll leave a TODO as its not needed yet. When I upstream to rules_nodejs I'll address that add some unit tests for this rule as well that will test for those cases.

2020-02-18 17:29 UTC, gregmagolan commented on integration/ngcc/test.sh
> +    cache=".yarn_local_cache"
In the legacy integration tests, `$cache` is set in `/integration/run_tests.sh`:
```
export readonly cache=.yarn_local_cache
```
but we're not running with that script in the npm_integration_test context so I needed to add it here as well. Don't have a better idea of where to get that value from in this shell script when running in `npm_integration_test`.

2020-02-18 17:32 UTC, gregmagolan commented on integration/BUILD.bazel
> +#   platform-server                     4206        /src/server.ts: app.listen(4206,...
Where's the best spot for instructions that devs adding a new test will see.
The basics are:
1) Add new test to `INTEGRATION_TESTS` object (and tag as `"no-ivy-aot"` if not meant to be run against ivy bundles)
2) If test requires ports and does not support ethereal ports then make sure the port is unique and add it to the "manually configured ports" comment to document which port it is using
3) Add to .bazelignore

2020-02-18 17:39 UTC, gkalpak commented on integration/BUILD.bazel
> +#   platform-server                     4206        /src/server.ts: app.listen(4206,...
I think `/integration/README.md` is a good place.

2020-02-18 17:40 UTC, gkalpak commented on integration/ngcc/test.sh
> +    cache=".yarn_local_cache"
I guess we could pass it as an env variable, but given that (it would complicate things and) it's only this one extra occurrence, it's fine to leave it as is 🤷‍♂

2020-02-18 17:55 UTC, gregmagolan commented on integration/BUILD.bazel
> +#   platform-server                     4206        /src/server.ts: app.listen(4206,...
👍 Done

2020-02-18 19:03 UTC, gregmagolan commented on integration/ng_elements_schematics/package.json
> +    "shelljs": "0.8.3",
Removed these changes from this PR for now anyway since I haven't move this particular test to bazel yet. It was just added and follows a different pattern so will leave that for a follow up PR.

2020-02-19 19:16 UTC, gregmagolan commented on integration/README.md
> +To avoid having to specify this command line flag, you may want to include it in your `~/.bazelrc` file:
👍

2020-02-19 19:16 UTC, gregmagolan commented on integration/angular_integration_test.bzl
> +    # tests. Any give integration does not need to use all of these packages.
👍

2020-02-19 19:16 UTC, gregmagolan commented on integration/angular_integration_test.bzl
> +    # Complete of npm packages to override in the test's package.json file mapped to
👍

2020-02-19 20:11 UTC, josephperrott approved these changes
LGTM, we should confirm that @gkalpak is happy with it as well.

2020-02-21 17:05 UTC, gkalpak approved these changes
LGTM 👌

2020-02-21 17:05 UTC, gkalpak commented on tools/npm_integration_test/test_runner.js
> +      //       and quoted arguments that contains spaces
```suggestion
      //       and quoted arguments that contain spaces
```

2020-02-21 21:38 UTC, IgorMinar reviewed
almost done reviewing everything again. posting what I have so far.

2020-02-21 21:38 UTC, IgorMinar commented on integration/bazel-schematics/test.sh
> +}
since this code is moving outside of angular/angular soon, I'm fine with keeping it as is.

2020-02-23 02:12 UTC, gregmagolan commented on .circleci/config.yml
> +      resource_class: 2xlarge+
I made a difference once I moved the integration/bazel & integration/bazel-schematics tests to work in the general case without the browser docker image and with the `cpu:3` tags. Overall we're using fewer credits now.

2020-02-23 02:16 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +      //       and quoted arguments that contains spaces
👍

2020-02-24 16:57 UTC, IgorMinar approved these changes
LGTM!!! We can follow up on this with further improvements in additional PRs. Thanks @gregmagolan !!!

2020-02-24 16:59 UTC, closed without merging