feat(language-service): completions support for tuple array
angular/angular pull request #33928
Opened 2019-11-20 08:11 UTC by ivanwonder

implement the missing tuple functionality because the PR #29811 has been closed.
https://github.com/angular/angular/pull/29811#issuecomment-554812436

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-11-26 02:38 UTC, ayazhafiz requested changes

2019-11-26 02:38 UTC, ayazhafiz commented on packages/language-service/src/symbols.ts
> +   * sometimes we need the key of arguments to get the type of the expression(type Example =
```suggestion
   * Sometimes we need the key of arguments to get the type of the expression, for example
   * in the case of tuples (`type Example = [string, number]`).
```

2019-11-26 02:38 UTC, ayazhafiz commented on packages/language-service/src/typescript_symbols.ts
> +          // get the right tuple Types by value. like 'var t: [number, string];'
```suggestion
          // get the right tuple type by value, like 'var t: [number, string];'
```

2019-11-26 02:38 UTC, ayazhafiz commented on packages/language-service/test/completions_spec.ts
> +
Could you a test in `packages/language-service/test/diagnostics_spec.ts` as well? There are already tests in there for index types, so you should be able to mostly just copy one.

2019-11-26 03:28 UTC, kyliau requested changes
Thank you very much for fixing this!

2019-11-26 03:28 UTC, kyliau commented on packages/language-service/src/typescript_symbols.ts
> +            return new TypeWrapper(nType.types[value], this.context);
should we do a bounds check here?

2019-11-26 03:28 UTC, kyliau commented on packages/language-service/src/typescript_symbols.ts
> +          return undefined;
else statement and return could be omitted.

2019-11-26 03:29 UTC, kyliau commented
The commit message linter doesn't like the commit messages, could you please squash them all into one?

2019-11-26 03:40 UTC, ivanwonder commented on packages/language-service/src/typescript_symbols.ts
> +          return undefined;
because the tslint report a warning `Fallthrough case in switch.ts(7029)`.
if it doesn't matter. I will remove the else statement.

2019-11-26 03:41 UTC, ivanwonder commented
> The commit message linter doesn't like the commit messages, could you please squash them all into one?

ok, I will

2019-11-26 03:45 UTC, ivanwonder commented on packages/language-service/src/typescript_symbols.ts
> +            return new TypeWrapper(nType.types[value], this.context);
ok, I will remove the number type checker

2019-11-26 15:29 UTC, ayazhafiz approved these changes

2019-11-26 18:10 UTC, kyliau commented on packages/language-service/src/typescript_symbols.ts
> +            return new TypeWrapper(nType.types[value], this.context);
Sorry, I should have been more clear in my previous comment.
What I meant was, what if `nType.types[value]` is undefined?
For example, if the tuple is `t = [string, number, string]` and user indexes `t[3]`, would this report an error?
Perhaps we should add a test case for this.

2019-11-27 02:49 UTC, ivanwonder commented on packages/language-service/src/typescript_symbols.ts
> +            return new TypeWrapper(nType.types[value], this.context);
I see, here I will return `return nType.types[value] && new TypeWrapper(nType.types[value], this.context)`.
and then add a test case in `diagnostics_spec.ts` to check `expect(diags).toEqual([]);` if array index out of bound.

2019-11-27 19:10 UTC, kyliau approved these changes
Thank you so much!

2019-11-27 20:54 UTC, closed without merging

2019-11-27 23:41 UTC, ivanwonder commented
love the language-service, and hope it better.🤝