fix(common): ngSwitchCase to handle undefined and null properly (#33873)
angular/angular pull request #33940
Opened 2019-11-20 17:59 UTC by arvindm95

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
https://github.com/angular/angular/issues/33873

Issue Number: #33873

## What is the new behavior?
Now, ngSwitchCase will be able to handle undefined and null cases separately.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-12-03 23:10 UTC, mhevery commented
[presubmit](http://test/OCL:283631371:BASE:283631440:1575414594018:e7222c40)

2019-12-04 00:04 UTC, mhevery commented
[presubmit](http://test/OCL:283642504:BASE:283642566:1575417839119:b56ec7db)

2019-12-05 18:06 UTC, AndrewKushnir commented
It looks like a breaking change (so I marked it with the "breaking change" label). We should probably review it again, make sure there is a proper communication (in docs) and merge it after v9.

2020-07-14 18:11 UTC, petebacondarwin requested changes
Can we add something to the API docs for this to highlight that matches are strict?
Also the commit message needs a body explaining the change and it also needs a BREAKING CHANGE section.

2020-07-14 18:11 UTC, petebacondarwin commented on packages/common/test/directives/ng_switch_spec.ts
> +      it('should handle null and undefined separtely', () => {
```suggestion
      it('should handle null and undefined separately', () => {
```

2020-07-14 18:14 UTC, petebacondarwin commented
I've added a blocked label since this will not be able to land until v11

2020-11-10 17:49 UTC, petebacondarwin commented
@arvindm95 would you be interested in continuing with this PR?

2020-11-19 23:21 UTC, mhevery commented
Closing as this PR seems abandoned and it is a relatively breaking change.  (A lot of work)

2020-11-19 23:21 UTC, closed without merging