refactor(ivy): remove merge mode in favor of direct-mode styling
angular/angular pull request #34000
Opened 2019-11-22 23:23 UTC by matsko

2019-11-28 10:27 UTC, matsko commented
presubmit = https://test.corp.google.com/ui#id=OCL:282908383:BASE:282908407:1574936772802:2b228108

ivy presubmit = https://test.corp.google.com/ui#id=OCL:282908383:BASE:282908461:1574936803814:7da45c6b

2019-11-28 19:01 UTC, matsko commented
presubmit = http://test/OCL:282960825:BASE:282960833:1574967603926:629be4e8

ivy presubmit = https://test.corp.google.com/ui#id=OCL:282960825:BASE:282960950:1574967705575:7708fc40

2019-12-04 10:47 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/element.ts
> +  if (!tView.firstCreatePass &&
@matsko I did several refactorings to separate the `firstCreatePass` logic from other code and here we are breaking this code structure. The consequence of this is that you have to:
* read `tView.firstCreatePass` _again_
* read `lView[RENDERER]` _again_ in the `elementStartFirstCreatePass`
* add `Array.isArray(attrs)` check in `elementStartFirstCreatePass`

We need to split the logic differently and:
* do the registration logic _only_ in the `elementStartFirstCreatePass`
* do the actual DOM rendering logic _only_ in the `ɵɵelementStart`

2019-12-04 10:49 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/element.ts
> +    registerAndRenderInitialStyling(renderer, tNode, native, attrs, 0, false);
See https://github.com/angular/angular/pull/34000/files#r353670644

I think that the `registerAndRenderInitialStyling` should be split into 2 separate functions:
* register
* render

Otherwise we are mixing the first / subsequent creation passes, reading more memory and hurting perf as the results. I think that such split is also good for code read-ability - better to nave 2 focused functions than one bigger that "does it all"

2019-12-04 10:51 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/element_container.ts
> +    registerAndRenderInitialStyling(renderer, tNode, null, attrs, 0, false);
See https://github.com/angular/angular/pull/34000/files#r353671697

Here it is even more evident that we need to split `registerAndRenderInitialStyling` into 2 functions as for the `elementContainerStartFirstCreatePass` we want to do registration _only_ (there is no rendering happening)

2019-12-04 10:55 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/integration_spec.ts
> +           @Component({template: '<div style="width:100px; height:200px" DirWithStyle></div>'})
This change looks suspicious - why do we need to do it?

2019-12-05 06:39 UTC, mhevery requested changes

2019-12-05 06:39 UTC, mhevery commented on packages/core/src/render3/styling/state.ts
> +const _state = createStylingState();
This will defeat the tree shaker. (hence `tslint:disable` is needed) Can we just inline the object. (There is no need for `createStylingState`)

2019-12-05 06:39 UTC, mhevery commented on packages/core/src/render3/styling/state.ts
>   * Used as a state reference for update values between style/class binding instructions.
Is this needed only during first template pass? If so can you add comment to make that clear? (Maybe some `ngDevMod` assertions stating that this is the case?)

2019-12-05 06:39 UTC, mhevery commented on packages/core/test/acceptance/styling_spec.ts
> +onlyInIvy('only ivy treats [class] in concert with other class bindings')
Why is this commented out?

2019-12-05 06:39 UTC, mhevery commented on packages/core/src/render3/instructions/element.ts
> +  if (Array.isArray(attrs)) {
Would `attrs` be something other than an `Array`?

2019-12-05 16:57 UTC, matsko commented on packages/core/src/render3/util/styling_utils.ts
> +export function printStylingTable(
We can't move these into styling_debug.ts because then I can't use them while I'm debugging locally because styling_debug.ts imports from the algorithm files (it would be a cyclic dependency).

Ideally it would go into `window.ng.debugStyling()`. But we don't have this system fully in place yet.

2019-12-05 16:58 UTC, matsko commented on packages/core/src/render3/util/styling_utils.ts
> +      setStyleAttr(renderer, native, tNode.styles);
No. Only during the `firstCreatePass` does it do it once per element and each time a directive fires that has styling. After the firstCreatePass (for a tNode) it just does it once (because it knows all the styles/classes on the element).

2019-12-05 18:03 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +  if (!tView.firstCreatePass &&
Yeah this should be fine to move into the `elementStartFirstCreatePass` function.

2019-12-05 18:06 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +    registerAndRenderInitialStyling(renderer, tNode, native, attrs, 0, false);
We can't do this because we can only write to the `className` or `attribute.style` value once (which happens just before `registerAndRenderInitialStyling` is called) and then append to it (using `classList` and/or `style`). The key thing is to remember what classes/styles are extra. Otherwise you would have to store all the additional classes/styles in an array and pass that back so it can be rendered directly after. It wouldn't be much of an additional change.

2019-12-05 18:06 UTC, matsko commented on packages/core/src/render3/instructions/element_container.ts
> +    registerAndRenderInitialStyling(renderer, tNode, null, attrs, 0, false);
See my previous comment.

2019-12-05 18:06 UTC, matsko commented on packages/core/test/acceptance/integration_spec.ts
> +           @Component({template: '<div style="width:100px; height:200px" DirWithStyle></div>'})
This shouldn't matter anymore. Reverting.

2019-12-05 18:08 UTC, matsko commented on aio/scripts/_payload-limits.json
> +        "main-es2015": 509333,
Yes it looks like ES5 is bigger but other sizes are smaller.

2019-12-05 18:11 UTC, matsko commented on packages/core/src/render3/styling/state.ts
>   * Used as a state reference for update values between style/class binding instructions.
No this is used all over the algorithm during each update pass.

2019-12-05 18:12 UTC, matsko commented on packages/core/test/acceptance/styling_spec.ts
> +onlyInIvy('only ivy treats [class] in concert with other class bindings')
This was the test that me and Andrew came across. Still deciding if it's the right way to go.

2019-12-05 18:13 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +  if (Array.isArray(attrs)) {
The benchmark tests render it as `undefined` sometimes (and it is `null` by default). Instead of having to have two checks (`undefined` and `null`), better to just have one to see if it's an array?

2019-12-05 18:13 UTC, matsko commented on packages/core/src/render3/styling/state.ts
> +const _state = createStylingState();
Removing.

2019-12-05 18:13 UTC, matsko commented on packages/core/src/render3/util/styling_utils.ts
> +export function printStylingTable(
This isn't an issue for me in non-Google code, but I do use this function while testing G3 to see what's going on.

2019-12-05 18:14 UTC, matsko commented on packages/core/src/render3/util/styling_utils.ts
> +export function registerAndRenderInitialStyling(
As I mentioned to you in Slack. `styling_utils.ts` is still undocumented.

2019-12-05 18:15 UTC, matsko commented on packages/core/src/render3/util/styling_utils.ts
> +  return !Object.is(a, b);
Removing this causes various tests to fail. Looking into it.

2019-12-05 18:15 UTC, matsko commented on packages/core/src/render3/instructions/shared.ts
> +import {setClassName, setStyleAttr} from '../util/styling_utils';
Fixed.

2019-12-05 18:15 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/element.ts
> +  if (Array.isArray(attrs)) {
In this case we should rather change the benchmark to avoid Array.isArray(attrs) check here (strong preference) or just do `attrs != null`

2019-12-05 18:17 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +  if (!tView.firstCreatePass &&
Actually no. It won't work because the `firstCreatePass` code only runs on the first time the `tNode` is processed. We still need to render styling for all the other times the element is created.

2019-12-05 18:17 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +  if (!tView.firstCreatePass &&
See my other comment about the registration.

2019-12-05 18:24 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +    registerAndRenderInitialStyling(renderer, tNode, native, attrs, 0, false);
So the reason why this is a problem at all is because various Material components/directives add/remove classes/styles in their constructor code (using their own classList/style[prop] code). Components/directives also expect that various classes to be defined before they are run (which is why the rendering happens first via `renderInitialStyling`).

Then each time a directive is added it will add new classes/styles in addition to what was there earlier. Those are added via classList/style[prop]. Because Material components may add their own classes we can't rewrite the attribute again (which is what happens when `renderInitialStyling` is called) ... This is why it's skipped when on the first create pass.

This explains why:
- On firstCreatePass we need to loop over all the attributes and render multiple times
- Otherwise we can write the to the attribute directly because we know the combined className/style string that will be written to the element (combined === the template + directive initial classes/styles combined into two strings).

I understand the logic is coupled, but if you want to change how `registerAndRenderInitialStyling` work then you will need to collect the new classes/styles in an array. Then render that on the element immediately after? Doesn't that mean that more memory is used?

2019-12-05 19:47 UTC, mhevery requested changes

2019-12-05 19:47 UTC, mhevery commented on packages/core/src/render3/styling/direct_write_algorithm.ts
> +    if (isBindingRegistered(tData, bindingIndex) &&
could we change this `if` statement to something like this:
```
markLocationFromWhichStylesNeedToBeRecomputed(...)

/**
 * This function marks the place in the styling linked list from which the flushing needs to start.
 *
 * There are two things to keep in mind. 
 * 1. Bindings for template are before hostBindings for component which are before hostBindings for directives.
 *    We refer to this as source. `0` for Template, `1` for component, `2 for directive and so on.
 *    The implication of this is that a higher source ID is linked earlier in the styling linked list. 
 * 2. Within the source id the instructions are generated in the correct order. So an instruction which has should 
 *    overwrite a previous instruction will be after such instruction. Implication of this is that within the same
 *    source ID the lowest binding index wins.
 *
 * Putting the above two together yields these resolution rules.
 * 1. Always take the index of higher sourceID.
 * 2. If SourceID same the first binding index was the correct one.
 */
function markLocationFromWhichStylesNeedToBeRecomputed(...) {
  if (lastSourceId !== currentSourceID) {
    ngDevMode && assertLessThen(state.flusStartSourceId, currentSourceId, "expecting source ids to be increasing only");
    state.flushStartIndex = currentBindingIndex;
    state.flushStartSourceId = currentSourceId;
  }
}
```

I think this is a lot simpler to follow as to what is going on.

2019-12-05 19:47 UTC, mhevery commented on packages/core/src/render3/styling/state.ts
> +  if (_state.element !== element || _state.directiveIndex !== directiveIndex) {
Why do we need both directiveIndex as well as element? It seems redundant. 
- My understanding is that `element` should not be needed
- `directiveIndex` and `sourceIndex` track the same information, and should  be unified.

2019-12-05 20:01 UTC, matsko commented on packages/core/src/render3/styling/state.ts
> +  if (_state.element !== element || _state.directiveIndex !== directiveIndex) {
we can keep only `directiveIndex` because `sourceIndex` was only used with `TStylingContext`.

2019-12-05 20:01 UTC, matsko commented on packages/core/src/render3/styling/state.ts
> +  if (_state.element !== element || _state.directiveIndex !== directiveIndex) {
`element` is used to track when the template bindings exit and/or when the host bindings are done.

2019-12-05 21:58 UTC, matsko commented
http://test/OCL:284046515:BASE:284046617:1575583106000:7e519709

2019-12-05 22:00 UTC, matsko commented on packages/core/src/render3/styling/direct_write_algorithm.ts
> +function getMinSourceAndBindingIndex(
I changed them all to be:
- `setDirectiveAndBindingStartIndices`
- `getBindingStartIndex`
- `getDirectiveStartIndex`

2019-12-05 22:01 UTC, matsko commented on packages/core/src/render3/instructions/styling.ts
> +    updated = updateBindingValue(lView, tData, state, value, bindingIndex, isClassBased);
the `updated` flag is used below to update the `ngDevMode` counters.

2019-12-05 22:01 UTC, matsko commented on packages/core/src/render3/instructions/element.ts
> +  if (Array.isArray(attrs)) {
Do you think `attrs != null` is more clear than `Array.isArray`?

2019-12-06 00:08 UTC, mhevery requested changes

2019-12-06 00:08 UTC, mhevery commented on packages/core/src/render3/styling/binding_concatenation.ts
> +    sanitizer: StyleSanitizeFn | null, firstUpdatePass: boolean, hostBindingsMode: boolean): void {
`firstUpdatePass` is a suspect here. The logic here should be independent of wether or not we are in `firstUpdatePass`.

Same thing for `firstUpdatePass` 

This algorithm should be agnostic to `firstUpdatePass` and `hostBindingsMode`

2019-12-06 00:08 UTC, mhevery commented on packages/core/src/render3/styling/binding_concatenation.ts
> +export function processStylingBindingsUpToPoint(
maybe rename to `processStylingBindingsUpToPoint` => `processStylingBindingsUntilEnd`? 

It says upto point, but there is no point, it goes to end.

2019-12-06 00:08 UTC, mhevery commented on packages/core/src/render3/styling/binding_concatenation.ts
> +    sanitizer: StyleSanitizeFn | null, isClassBased: boolean): void {
We talked about having the sanitizer be stored in the `TData` Would that be too much work to refactor? It would really clean up this code.

2019-12-06 02:54 UTC, matsko commented on packages/core/src/render3/styling/binding_concatenation.ts
> +    sanitizer: StyleSanitizeFn | null, isClassBased: boolean): void {
If you're ok to do it with this PR then I'm happy to do it.

2019-12-06 02:55 UTC, matsko commented on packages/core/src/render3/styling/binding_concatenation.ts
> +export function processStylingBindingsUpToPoint(
Fixed.

2019-12-06 02:56 UTC, matsko commented on packages/core/src/render3/styling/binding_concatenation.ts
> +    sanitizer: StyleSanitizeFn | null, firstUpdatePass: boolean, hostBindingsMode: boolean): void {
It's used to determine whether or not the initial concatenated value is the initial value (used during element creation) or the most recent concatenated value.

2019-12-06 02:57 UTC, matsko commented on packages/core/src/render3/styling/binding_concatenation.ts
> +    sanitizer: StyleSanitizeFn | null, firstUpdatePass: boolean, hostBindingsMode: boolean): void {
hostBindingsMode is used to resolve whether or not the template bindings were applied in the last CD. If yes then it reads that, otherwise it gets the initial value.

2019-12-06 03:07 UTC, matsko commented on packages/core/src/render3/styling/binding_concatenation.ts
> +    const stylesTail = getStylingTail(tNode, false);
The tail is used to determine where to read the last applied value (the concatenated value).

2019-12-06 03:07 UTC, matsko commented on packages/core/src/render3/styling/binding_concatenation.ts
> +  const lastClassBindingIndex = getBindingStartIndex(state, true);
De-duped.

2019-12-06 03:07 UTC, matsko commented on packages/core/src/render3/styling/binding_concatenation.ts
> +    renderer: any, native: RElement, lView: LView, tNode: TNode, tData: TData, state: StylingState,
We would need to call the function twice then.

2019-12-06 03:07 UTC, matsko commented on packages/core/src/render3/interfaces/view.ts
> +     InjectionToken<any>| TI18n | I18nUpdateOpCodes | null | string | {})[];
Added.

2019-12-06 03:09 UTC, matsko commented on packages/core/src/render3/instructions/styling.ts
>      if (isStylingValueDefined(newValue) || !firstUpdatePass) {
`elementStart` will write the falsy value upon creation. I will add a comment that explains.

2019-12-06 03:11 UTC, matsko commented on integration/_payload-limits.json
> +        "main-es2015": 267395,
We should discuss part 1) more because I have other ideas. I don't know why the styling code is being pulled in when only static styles are used in an app. We should investigate.

2019-12-06 07:14 UTC, mhevery requested changes

2019-12-06 20:00 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/element.ts
> +  if (Array.isArray(attrs)) {
Yup! (and probably cheeper). But regardless, we should have it as `attrs !== null` (that is, fix the benchmark - we don't want to pay readabiluty / perf price of benchmarks in the prod code).

2019-12-06 20:28 UTC, kara commented on packages/core/src/render3/instructions/element.ts
> +  if (Array.isArray(attrs)) {
Yeah, I'd agree. The `isArray` check implies that there is a value other than an array. `attrs !== null` is clearer.

2019-12-06 20:43 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/element.ts
> +  if (hasClassInput(tNode) && typeof tNode.classes === 'string') {
Why do we need to check `typeof tNode.classes === 'string'`? Shouldn't it be `tNode.classes !== null` (similar question for styles)?

2019-12-10 01:32 UTC, kara requested changes
First pass - since this refactor is so large, it's mostly questions. Will do another pass once @matsko and I can sync up

2019-12-10 01:32 UTC, kara commented on packages/core/src/render3/instructions/styling.ts
> + * Applies the provided `[style]`, `[style.prop]`, `[class]` or `[class.name]` binding.
This function doesn't actually apply the styles, does it? My understanding is that it just registers the bindings and we flush the styles later, but this comment makes it sound like it does both

2019-12-10 01:32 UTC, kara commented on packages/core/src/render3/util/styling_utils.ts
>    return bindingIndex !== 0 ? data[bindingIndex] as T : null;
When is binding index 0?

2019-12-10 01:32 UTC, kara commented on packages/core/src/render3/instructions/styling.ts
> +    updated = updateBindingValue(lView, tData, state, value, bindingIndex, isClassBased);
`updateBindingValue` looks pretty similar to `bindingUpdated` (which also returns a boolean). Seems like we might be able to re-use it instead of rewriting it from scratch.

2019-12-10 01:32 UTC, kara commented on packages/core/src/render3/styling/binding_registration.ts
> +const enum BindingSourceMode {
Can we move this to the styling interface file?

2019-12-10 01:41 UTC, IgorMinar requested changes
I've reviewed `normalizeValueForConcatenation` while reviewing #34286 and I have some suggestions/questions that I'm posting as individual review comments.

2019-12-10 01:41 UTC, IgorMinar commented on packages/core/src/render3/styling/binding_concatenation.ts
> + * @returns a string value (when the value is allowed to be concatenated), otherwise a falsy
```suggestion
 * @returns a string value (when the value is allowed to be concatenated), otherwise a false
```

2019-12-10 01:41 UTC, IgorMinar commented on packages/core/src/render3/styling/binding_concatenation.ts
> + * @returns a string value (when the value is allowed to be concatenated), otherwise a falsy
unless you really mean `falsy` in which case you should be explicit and say `false|null`

2019-12-10 01:41 UTC, IgorMinar commented on packages/core/src/render3/styling/binding_concatenation.ts
> + */
I have a few questions related to this fn:

1. can you please document all parameters?
2. under what circumstances can the `sanitizer` be `null`? is that a valid scenario? I see us check if sanitizer is not `null` in many places, so maybe we should ensure that it is null early on and then expect that it will not be null.
3. related to that, is `null` really a valid return value? what does it mean to return `null`? Can you please document the meaning, or even better if possible always ensure that we return a string by returning `''` instead?
4. can you consider renaming `validateAndSanitize` to `isMapBased` as it reflects the type of binding rather than what we should do with it (similar to `isClassBased`)
5. can you please document the meaning of returned `false` value?

2019-12-10 01:41 UTC, IgorMinar commented on packages/core/src/render3/styling/binding_concatenation.ts
> +    if (isClassBased) {
Is it justified to complicate this fn using this flag? why not create two simpler functions: `normalizeStyleValueForConcatenation` and `normalizeClassValueForConcatenation`, with the second being just:

```
function normalizeClassValueForConcatenation(prop, value, sanitizer): string|false {
  return (isStylingValueDefined(value) && value !== false && value !== 0) ? false : prop;
}
```
The code assumes that I understand the meaning of `false` and `0` values, which I don't so I might have gotten that part wrong, but the general simplification suggestion should still apply. In short, I don't believe that the isClassBased flag is necessary, and it appears to make the code more convoluted.

2019-12-10 01:41 UTC, IgorMinar commented on packages/core/src/render3/styling/binding_concatenation.ts
> +  if (isStylingValueDefined(value) && value !== false) {
based on this logic, and because of the cast on the last line of the fn, if the value is `true` then this fn returns `true` in spite of the fn signature claiming that that can't be. that seems like a bug?

2019-12-10 01:41 UTC, IgorMinar commented on packages/core/src/render3/styling/binding_concatenation.ts
> +  if (isStylingValueDefined(value) && value !== false) {
I also find it confusing that `isStylingValueDefined` explicitly considers the value defined if it's set to `false` but not defined if it's set to `''` - because of this it's not clear what `isStylingValueDefined` actually means and why the comment in `isStylingValueDefined` state that the value is defined if it's set to `false`.

I'm sorry that I can't suggest what this should look like instead because I don't fully understand the significance of `''` and `false` values here, I'm just pointing out that the point of this condition is not clear and considering the `true` bug described above, we already seem to have an issue here, so it would be great to clarify this.

2019-12-10 01:41 UTC, IgorMinar commented on packages/core/src/render3/styling/binding_concatenation.ts
> +      value = renderStringify(value);
shouldn't we `unwrapSafeValue` before stringifying?

2019-12-10 01:41 UTC, IgorMinar commented on packages/core/src/render3/styling/binding_concatenation.ts
> +      value = renderStringify(value);
see related PR with a pending fix: #34286

2019-12-10 22:36 UTC, matsko commented on packages/core/src/render3/instructions/shared.ts
> +                         null,       // styles: string
@mhevery if you're going to push directly to the PR with these changes then please update the docs as well.

2019-12-10 22:40 UTC, matsko commented on packages/core/src/render3/instructions/class_map_interpolation.ts
> +  stylingBindingInternal(getSelectedIndex(), null, value, null, null, true);
We could, but there are a lot more params to pass in though. Bundle size-wise using a wrapper function would be smaller.

2019-12-10 22:54 UTC, matsko commented on packages/core/src/render3/instructions/styling.ts
> + * Applies the provided `[style]`, `[style.prop]`, `[class]` or `[class.name]` binding.
```
 * Queues the provided `[style]`, `[style.prop]`, `[class]` or `[class.name]` binding to be applied during a styling flush.
 *
 * Each time any styling instruction runs the style/class values are passed
 * in through this function, but they are not yet applied to the element.
 * They are instead "queued" until the "styling flush" occurs (which happens
 * when the element is fully processed).
 *
 * When this function is called during the first update pass (when the bindings are
 * run for the very first time on an element), the binding property name and metadata
 * are registered on the associated `TData` data-structure (which is obtained from
 * the current global `LView` instance).
```

2019-12-10 22:55 UTC, matsko commented on packages/core/src/render3/util/styling_utils.ts
>    return bindingIndex !== 0 ? data[bindingIndex] as T : null;
This is used in the current implementation (in `TStylingContext`) to specify that a binding doesn't have a value in a specific directive.

2019-12-10 22:55 UTC, matsko commented on packages/core/src/render3/util/styling_utils.ts
>    return bindingIndex !== 0 ? data[bindingIndex] as T : null;
fixed

2019-12-10 23:46 UTC, matsko commented on packages/core/src/render3/styling/binding_registration.ts
> +const enum BindingSourceMode {
moved

2019-12-12 23:23 UTC, matsko commented
https://test.corp.google.com/ui#id=OCL:284465544:BASE:285283537:1576192983681:e3657fdb

2019-12-13 22:10 UTC, matsko commented
https://tap.corp.google.com/ui#id=OCL:285468034:BASE:285468117:1576274879535:4f7ae053

2019-12-16 21:23 UTC, closed without merging