refactor(core): Add array modification functions.
angular/angular pull request #34004
Opened 2019-11-23 04:54 UTC by mhevery

# refactor(core): Add array modification functions.
This change introduces several functions for manipulating items in an array in an efficient (binary search) way.

- `arraySplice` a faster version of `Array.splice()`.
- `arrayInsert` a faster version of `Array.splice(index, 0, value)`.
- `arrayInsertSorted` a way to insert a value into sorted list.
- `arrayRemoveSorted` a way to remove a value from a sorted list.
- `arrayIndexOfSorted` a way to find a value in a sorted list.

# refactor(ivy): Add style reconciliation algorithm

This change introduces class/style reconciliation algorithm for DOM elements.
NOTE: The code is not yet hooked up, it will be used by future style algorithm.

Background: 
Styling algorithm currently has [two paths](https://hackmd.io/@5zDGNGArSxiHhgvxRGrg-g/rycZk3N5S) 
when computing how the style should be rendered. 
1. A direct path which concatenates styling and uses `elemnent.className`/`element.style.cssText` and
2. A merge path which uses internal data structures and uses `element.classList.add/remove`/`element.style[property]`.

The situation is confusing and hard to follow/maintain. So a future PR will remove the merge-path and do everything with 
direct-path. This however breaks when some other code adds class or style to the element without Angular's knowledge.
If this happens instead of switching from direct-path to merge-path algorithm, this change provides a different mental model
whereby we always do `direct-path` but the code which writes to the DOM detects the situation and reconciles the out of bound write.

The reconciliation process is as follows:
1. Detect that no one has modified `className`/`cssText` and if so just write directly (fast path).
2. If out of bounds write did occur, switch from writing using `className`/`cssText` to `element.classList.add/remove`/`element.style[property]`.
   This does require that the write function computes the difference between the previous Angular expected state and current Angular state. 
   (This requires a parser. The advantage of having a parser is that we can support `style="width: {{exp}}px" kind of bindings.`)
   Compute the diff and apply it in non destructive way using `element.classList.add/remove`/`element.style[property]`

Properties of approach:
- If no out of bounds style modification:
  - Very fast code path: Just concatenate string in right order and write them to DOM.
  - Class list order is preserved
- If out of bounds style modification detected:
  - Penalty for parsing 
  - Switch to non destructive modification: `element.classList.add/remove`/`element.style[property]`
  - Switch to alphabetical way of setting classes.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-11-25 13:38 UTC, pkozlowski-opensource commented on packages/core/src/util/array_utils.ts
> + * Same as `Array.splice(index, 0, value)` but faster.
This part of the comment is incorrect, right?

2019-11-25 13:40 UTC, pkozlowski-opensource commented on packages/core/src/util/array_utils.ts
> + * Same as `Array.splice2(index, 0, value1, value2)` but faster.
it gets any index, not only `0`, right?

2019-11-25 13:45 UTC, pkozlowski-opensource commented on packages/core/test/util/array_utils_spec.ts
> +      expect(arrayMapDelete(map, 'AA')).toEqual(~2);
why using bits inverting operator `~` here?

2019-11-25 14:11 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/reconcile.ts
> +  computeClassChanges(oldValue, newValue, removals, additions);
When we look at the implementation of the VE's `NgClass` one can notice that we use the existing `IterableDiffer` to figure out a set of operations to get from one state to another. What is the advantage of introducing another, specialised diffing algorithm here?

2019-11-25 15:07 UTC, petebacondarwin commented on packages/core/src/util/array_utils.ts
> +export function arraySplice(array: any[], index: number, count: number): void {
So this should be named `arrayRemove` or something similar. It is no longer "splicing" - neither adding nor replacing items of the array.

2019-11-25 15:08 UTC, petebacondarwin commented on packages/core/src/util/array_utils.ts
> +  }
Is this faster than setting the `length` of the array?

2019-11-25 15:54 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/class_differ.ts
> + * @param parts Where the parts will be stored
there is no `parts` argument, as far as I can tell

2019-11-25 15:56 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/class_differ.ts
> + * `A` second time. This prevents that from happening.
Huh, this is interesting! Could you please provide an example of the real-life template where such situation would happen? Naively, I would say that a binding says `remove A` we should remove it, no matter how many times it is present... I'm clearly missing context / understanding here...

2019-11-25 16:00 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/class_differ.ts
> +    oldValue: string, newValue: string, removals: string[], additions: string[]): void {
I'm surprised that the `oldValue` is a string - I was assuming that we are storing some sort of a list / collection of old values and would have to compare this data structure to changes computed by CD. Or is it supposed to be used for cases where the `classList` is "externally" mutated? Clearly missing context / big-picture design here...

2019-11-25 16:03 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/reconcile.ts
> + * Writes new `className` (style) value in the DOM node.
Not sure about the `(style)` part of the comment - we are dealing with the CSS class names here only, no?

2019-11-25 16:06 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/reconcile.ts
> + * @param element The DOM element to update.
DOM -> native?

2019-11-25 16:12 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/reconcile.ts
> +  removals.length = additions.length = 0;
Is it "worth the trouble" to share all those arrays? How could we measure this?

2019-11-26 01:05 UTC, mhevery commented on packages/core/src/render3/styling/reconcile.ts
> +  computeClassChanges(oldValue, newValue, removals, additions);
1. `IterableDiffer` is super expensive both in size, memory and runtime.
2. `IterableDiffer` is for arrays here we are working strings not arrays. Not sure how this would even fit her.

2019-11-26 01:05 UTC, mhevery commented on packages/core/src/util/array_utils.ts
> +export function arraySplice(array: any[], index: number, count: number): void {
renamed.

2019-11-26 01:05 UTC, mhevery commented on packages/core/src/util/array_utils.ts
> +  }
good idea, changed.

2019-11-26 01:05 UTC, mhevery commented on packages/core/src/util/array_utils.ts
> + * Same as `Array.splice(index, 0, value)` but faster.
I think it is correct. What specifically do you think is wrong?

2019-11-26 01:05 UTC, mhevery commented on packages/core/src/util/array_utils.ts
> + * Same as `Array.splice2(index, 0, value1, value2)` but faster.
Opps, fixed.

2019-12-03 00:19 UTC, kara requested changes

2019-12-03 00:19 UTC, kara commented on packages/core/test/render3/styling_next/reconcile_spec.ts
> +      it('should not clobber out of bound styles', () => {
It would be good to have an acceptance test for this as well

2019-12-03 00:19 UTC, kara commented on packages/core/test/render3/styling_next/reconcile_spec.ts
> +        expect(element.style.cssText).toEqual('color: red;');
Would be good to have a test for the case where there is an existing style for some property (triggering the reconciliation logic) and we have multiple style values (e.g. dir writes "color", comp writes "color", etc). We would want to make sure the last value for the conflicting style is the one written.

2019-12-03 18:56 UTC, kara commented on packages/core/src/util/array_utils.ts
> + * `ArrayMap` is an array where even positions contain keys and odd positions contain values.
Yeah `MapAsArray` isn't great either, but for me the "as" makes it clear that it's actually an array, whereas "ArrayMap" sounds like it's ultimately a map ("array-like map"). Maybe re-ordering it to `MapArray` would be slightly better?

2019-12-06 01:58 UTC, kara reviewed
Some more comments and questions here (to prime the meeting for tomorrow).

Since we're adding more code here but not using it yet, maybe we can sanity check its impact by temporarily adding `writeAndReconcileClass` and `writeAndReconcileStyle` to one of the style instructions to see how much it *would* add to something like the CLI-hello-world-ivy payload (then removing it). I think it would help to see the size impact of this pr when looking at the total size with the follow up pr

2019-12-06 01:58 UTC, kara commented on packages/core/src/util/array_utils.ts
> +  return _arrayIndexOfSorted(array, value, 0);
Is it necessary to create the `arrayIndexOfSorted` function wrapper for this? Seems like we can simplify by calling `_arrayIndexOfSorted` directly and passing through 0. Other functions are delegating directly to `_arrayIndexOfSorted` already.

2019-12-06 01:58 UTC, kara commented on packages/core/src/util/array_utils.ts
> + * https://jsperf.com/fast-array-splice (About 20x faster)
This benchmark seems slightly different than the removal code you have below. Can we benchmark the code below?

2019-12-06 01:58 UTC, kara commented on packages/core/src/util/array_utils.ts
> + * https://jsperf.com/fast-array-splice (About 20x faster)
This benchmark doesn't appear to match the code below. Can you link one that adds values?

2019-12-06 01:58 UTC, kara commented on packages/core/src/render3/styling/class_differ.ts
> + * Removes a class from a `className` string.
Where is this being used or where is it intended to be used? It's not clear to me where it will fit into the algorithm

2019-12-06 01:58 UTC, kara commented on packages/core/src/render3/styling/style_differ.ts
> + *   'd',  true, null,  '5',
Thinking out loud - if the new value is null, wouldn't you know it's a removal? And if the old value is null, wouldn't you know it's an addition?  Is recording the second value (`true` / `false` / `null`) really necessary?

2019-12-06 01:58 UTC, kara commented on packages/core/src/render3/styling/style_differ.ts
> + * (addition/removals).
```suggestion
 * in `changes`
```

2019-12-06 01:58 UTC, kara commented on packages/core/src/render3/styling/style_differ.ts
> + * @param parts Where the parts will be stored
Remove outdated param

```suggestion
```

2019-12-06 01:58 UTC, kara commented on packages/core/src/render3/styling/styling_parser.ts
> + * Consumes all of the characters belonging to style token.
I'm not sure what this means - how do you consume characters? I'm guessing this function returns the next index after the key starts?

In general, for all these "consume" methods: "consume"  is too generic to mean something to me. It seems like all of them return an index, so that should be reflected in the name to make it clear what it's for.

2019-12-06 01:58 UTC, kara commented on packages/core/src/render3/styling/styling_parser.ts
> +    throw new Error(`Expected ':' at index ${startIndex} of: ${text}`);
Can we make this a dev mode only error so it tree shakes? Same for the others in this file.

2019-12-06 01:58 UTC, kara commented on packages/core/src/render3/styling/style_differ.ts
> +      throw new Error('Malformed style: ' + text);
Make dev mode only?

2019-12-09 21:46 UTC, mhevery commented on packages/core/test/render3/styling_next/reconcile_spec.ts
> +      it('should not clobber out of bound styles', () => {
Per our discussion, we can only add acceptance tests after this is all integrated with #34000

2019-12-10 10:35 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/class_differ.ts
> + * `['A', null, 'B', false, 'C', null, 'D', true],
nit: this example suggest / looks like we are returning an array while a `Map` is returned. Maybe it would be less confusing when written as `{'A': null, 'B': false, 'C': null, 'D': true}`?

2019-12-10 10:47 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/reconcile.ts
> +      (renderer as ProceduralRenderer3).setAttribute(element, 'class', newValue);
nit: a cast to the `ProceduralRenderer3` (`(renderer as ProceduralRenderer3)`) is not needed here since the `isProceduralRenderer` has the signature of `function isProceduralRenderer(renderer: ProceduralRenderer3 | ObjectOrientedRenderer3):renderer is ProceduralRenderer3` so TS should "know" that this is a `ProceduralRenderer3`

2019-12-10 10:49 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/reconcile.ts
> +      (renderer as ProceduralRenderer3).setAttribute(element, 'style', newValue);
nit: `(renderer as ProceduralRenderer3)` is not needed, see https://github.com/angular/angular/pull/34004/files#r355965814

2019-12-10 10:53 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/reconcile.ts
> +      (renderer as ProceduralRenderer3).setAttribute(element, 'style', newValue);
nit2: we start to have this pattern repeated in some places now through the code-base:

```javascript
if (isProceduralRenderer(renderer)) {
      (renderer as ProceduralRenderer3).setAttribute(element, 'class', newValue);
    } else {
      element.className = newValue;
    }
```

what do you think of creating a util (sth like `setNativeAttribute(renderer, attrName, attrValue)` to encapsulate this logic?

2019-12-10 11:03 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/reconcile.ts
> +      }
nit: what do you think about extracting this into a `nativeAddClass` / `nativeRemoveClass` to encapsulate this logic? I think I saw those lines repeated in other places, if I'm not mistaken? Also, we used to have those `ngDevMode` DOM manipulation counters - is this something we want to keep using / adding? 

Generally speaking it shows the "cost" of the `ObjectOrientedRenderer3` and I believe that we want to remove this overhead in the future.

2019-12-10 11:09 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/style_differ.ts
> +export const enum StyleChangesArrayMapEnum {
I don't see this `StyleChangesArrayMapEnum` being used anywhere, is it here for the future work?

2019-12-10 11:12 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/style_differ.ts
> +      ngDevMode && assertNotEqual(valueStart, valueEnd, 'malformed style');
nit: could we add the string of the malformed style here for easier debugging when this assert happens to fail? `assertNotEqual(valueStart, valueEnd, `malformed style: ${cssText}`);`

2019-12-10 11:28 UTC, pkozlowski-opensource commented on packages/core/test/render3/styling_next/class_differ_spec.ts
> +});
Great tests in this file, thank you @mhevery !

2019-12-10 11:31 UTC, pkozlowski-opensource commented on packages/core/test/render3/styling_next/reconcile_spec.ts
> +      fit('should not clobber out of bound styles', () => {
`fit` left-over, fortunately it was reported by CI: https://circleci.com/gh/angular/angular/559718?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

2019-12-10 11:34 UTC, pkozlowski-opensource commented on packages/core/test/render3/styling_next/reconcile_spec.ts
> +  debugger;
`debugger;`

2019-12-10 18:09 UTC, mhevery commented on packages/core/src/render3/styling/reconcile.ts
> +  removals.length = additions.length = 0;
removed in favor of new allocation each time.

2019-12-10 19:36 UTC, mhevery commented on packages/core/src/render3/styling/class_differ.ts
> + * `['A', null, 'B', false, 'C', null, 'D', true],
fixed

2019-12-10 19:36 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> +export const enum StyleChangesArrayMapEnum {
removed

2019-12-10 19:36 UTC, mhevery commented on packages/core/test/render3/styling_next/class_differ_spec.ts
> +});
👍

2019-12-10 19:43 UTC, mhevery commented on packages/core/src/render3/styling/reconcile.ts
> +      }
1. added the counters.
2. The other locations should be deleted. This should be the only place where this happens.

2019-12-10 19:44 UTC, mhevery commented on packages/core/test/render3/styling_next/reconcile_spec.ts
> +  debugger;
removed

2019-12-10 19:44 UTC, mhevery commented on packages/core/test/render3/styling_next/reconcile_spec.ts
> +      fit('should not clobber out of bound styles', () => {
fixed

2019-12-10 19:49 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> +      ngDevMode && assertNotEqual(valueStart, valueEnd, 'malformed style');
done

2019-12-10 21:39 UTC, mhevery commented
[presubmit](http://test/OCL:284838716:BASE:284838770:1576013933303:2a115280)

2019-12-11 00:21 UTC, kara reviewed
Like how this has been simplified! Comments below are mostly to update outdated comments/typos, but I believe I may have found a bug here:

https://github.com/angular/angular/pull/34004#discussion_r356325558

2019-12-11 00:21 UTC, kara commented on packages/core/src/render3/styling/styling_parser.ts
> + * @returns Index of next non-whitespace character (May be the same as `start` if no non-whitespace
Is this right? From the name, it sounds like this should return the last index of the style key
```suggestion
 * @returns Index after last style key character 
```

2019-12-11 00:21 UTC, kara commented on packages/core/src/render3/styling/styling_parser.ts
> + * @returns Index of next non-whitespace character (May be the same as `start` if no non-whitespace
```suggestion
 * @returns Index after separator and surrounding whitespace
```

2019-12-11 00:21 UTC, kara commented on packages/core/src/render3/styling/styling_parser.ts
> + * @returns Index of next non-whitespace character (May be the same as `start` if no non-whitespace
```suggestion
 * @returns Index after last style value character
```

2019-12-11 00:21 UTC, kara commented on packages/core/src/render3/styling/styling_parser.ts
> + * @returns last char in class token (May be the same as `start` if no non-whitespace
```suggestion
 * @returns Index after last char in class token
```

2019-12-11 00:21 UTC, kara commented on packages/core/src/render3/styling/styling_parser.ts
> + * @returns Index of next non-whitespace character (May be the same as `start` if no non-whitespace
```suggestion
 * @returns Index after quoted characters
```

2019-12-11 00:21 UTC, kara commented on packages/core/test/render3/styling_next/reconcile_spec.ts
> +      });
Can we add a test where we change the value of an existing style (through reconciliation algorithm)? I believe that would fail right now

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/class_differ.ts
> + * @returns An `Map` which will be filled with changes.
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/class_differ.ts
> + * @param changes ArrayMap which will be filled with changes. (`false` - remove; `null` - noop;
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/class_differ.ts
> + * Precesses the token by adding it to the `changes` array.
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/class_differ.ts
> + *          change.) If no token exist than the new token value is `true` (add it.)
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/reconcile.ts
> + * - If we do detect change than we compute the difference between the `expectedValue` and
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/reconcile.ts
> +* - If we do detect change than we compute the difference between the `expectedValue` and
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/reconcile.ts
> +    } else if (styleValue.old === null) {
Good catch! I added a test case for this use case and a fix.

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> + * If `old === null` than add `new`.
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> + * If `new === null` than remove `old`.
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> +export type StyleChangesArrayMap = Map<string, {old: string | null, new: string | null}>;
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> + * Appends style `key`/`value` information into the list of `removal`/`additions`.
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> + * Once all of the parsing is complete, the `removal`/`additions` will contain a
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> + * @param changes An `ArrayMap3` which tracks changes.
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> + * @param value Style value to be added to the `removal`/`additions`.
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> + * @param key Style key to be added to the `removal`/`additions`.
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> +    // This code path is executed when we are iterating over previous values.
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> +    // This code path is executed when we are iteration over new values.
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/style_differ.ts
> +          // This is a special case when we are the last key in a list, we than chop of the
fix

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/styling_parser.ts
> + * @returns last char in class token (May be the same as `start` if no non-whitespace
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/styling_parser.ts
> + * @returns Index of next non-whitespace character (May be the same as `start` if no non-whitespace
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/styling_parser.ts
> + * @returns Index of next non-whitespace character (May be the same as `start` if no non-whitespace
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/styling_parser.ts
> + * @returns Index of next non-whitespace character (May be the same as `start` if no non-whitespace
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/styling_parser.ts
> +      // if we have a non-whitespace character than capture its location
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/src/render3/styling/styling_parser.ts
> + * @returns Index of next non-whitespace character (May be the same as `start` if no non-whitespace
fixed

2019-12-11 04:57 UTC, mhevery commented on packages/core/test/render3/styling_next/reconcile_spec.ts
> +      });
yes, done.

2019-12-11 17:04 UTC, mhevery commented
[presubmit](http://test/OCL:284838716:BASE:284996704:1576083865887:ae55f614)

2019-12-11 18:18 UTC, kara approved these changes
LGTM

2019-12-11 22:45 UTC, mhevery commented
merged as 7cd465aa9b

2019-12-11 22:45 UTC, closed without merging

2020-01-29 21:00 UTC, mhevery commented on packages/core/src/util/array_utils.ts
> + * https://jsperf.com/fast-array-splice (About 20x faster)
removed