docs(compiler): fix typos and spelling
angular/angular pull request #34008
Opened 2019-11-23 15:54 UTC by arturovt

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-11-25 12:49 UTC, petebacondarwin requested changes
One small fix but the rest LGTM

2019-11-25 12:49 UTC, petebacondarwin commented on packages/compiler/design/separate_compilation.md
> +In 5.0 and prior versions of Angular the compiler performs the whole program
This change is not correct. Please revert it.

2019-11-25 14:55 UTC, arturovt commented on packages/compiler/design/separate_compilation.md
> +In 5.0 and prior versions of Angular the compiler performs the whole program
@petebacondarwin Done.

2019-11-25 14:59 UTC, petebacondarwin approved these changes

2019-12-03 19:51 UTC, kapunahelewong commented
Thank you for these fixes, @arturovt! 🌺

2019-12-03 19:51 UTC, kapunahelewong commented
merge-assistance: Global approval for this docs-only change.

2019-12-04 00:05 UTC, closed without merging