Several ngcc fixes
angular/angular pull request #34014
Opened 2019-11-23 18:34 UTC by JoostK

See individiual commits for descriptions.

2019-11-23 21:33 UTC, petebacondarwin approved these changes
Great stuff @JoostK

2019-11-23 21:33 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/analysis/migration_host_spec.ts
> +        expect(diagnostics.length).toBe(1);
You could hide the internals of diagnostic chains here by using a ts helper:

```ts
        expect(ts.flattenDiagnosticMessageText(diagnostics[0].messageText, '\n'))
            .toEqual(
                `test diagnostic\n` +
                `  Occurs for @Component decorator inserted by an automatic migration\n` +
                `  @Component({ template: "", selector: "comp" })`);
```

2019-11-23 21:33 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/diagnostics/src/util.ts
>  import * as ts from 'typescript';
This import is not used.

2019-11-23 21:33 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/diagnostics/src/util.ts
> +export function replaceTsWithNgInErrors(errors: string, colorized: boolean): string {
Could you add a jsdoc here to explain what is going on (i.e. that TypeScript doesn't allow custom prefixes so we have to use -99 and then convert TS-99 to NG).

2019-11-24 19:16 UTC, JoostK commented on packages/compiler-cli/ngcc/test/analysis/migration_host_spec.ts
> +        expect(diagnostics.length).toBe(1);
Excellent, that is a nice one!

2019-11-25 14:25 UTC, gkalpak requested changes
Some minor comments - otherwise lgtm 👌

2019-11-25 14:25 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/main.ts
> +              ts.formatDiagnostics(result.diagnostics, bundle.src.host), /* colorized */ false));
OOC, why using `colorized: false` here?

2019-11-25 14:25 UTC, gkalpak commented on packages/compiler-cli/src/ngtsc/diagnostics/src/util.ts
> +const ERROR_CODE_MATCHER = /( )TS-99(\d+: )/g;
Is it guaranteed that there will always be a leading space?

2019-11-25 14:25 UTC, gkalpak commented on packages/compiler-cli/src/ngtsc/diagnostics/src/util.ts
> +    return errors.replace(ERROR_CODE_MATCHER, '$1NG$2');
Why not omit the `colorized` param and use a RegExp that can match both versions?
(Having to pass in `colorized` is error prone and can easily get out-of-sync with the actual implementation.)

2019-11-26 21:36 UTC, JoostK commented on packages/compiler-cli/ngcc/src/main.ts
> +              ts.formatDiagnostics(result.diagnostics, bundle.src.host), /* colorized */ false));
Because diagnostics are formatted using `ts.formatDiagnostics`, not `ts.formatDiagnosticsWithColorsAndContext`. This difference has been mentioned in the params documentation for `colorized`.

2019-11-26 21:37 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/diagnostics/src/util.ts
> +const ERROR_CODE_MATCHER = /( )TS-99(\d+: )/g;
Yes! The `ts.formatDiagnostic` is implemented to prefix an error code with `" TS"`.

2019-11-26 21:43 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/diagnostics/src/util.ts
> +    return errors.replace(ERROR_CODE_MATCHER, '$1NG$2');
If all is well, the non-colorized regex would work just fine for colorized diagnostics, it's just that the colorized regex is less likely to incorrectly replace some random string that happens to contain " TS-99##: ". So we _could_ drop the colorized version. I kept it the way it was as I didn't want to change the logic of how it already worked in ngtsc, as I presume it was intentionally written the way it was.

For non-colorized messages that are used in ngcc though, the colorized regex wouldn't work. Hence I added an additional one. I choose to do this in the same function, as that achieves a centralized place where this replacement occurs. One could argue that it should be two separate functions, the non-colorized one potentially only present in ngcc, however I prefered the centralized logic.

I am not convinced we should change any of this, if you feel differently please let me know :-)

2019-11-27 11:48 UTC, gkalpak commented on packages/compiler-cli/src/ngtsc/diagnostics/src/util.ts
> +    return errors.replace(ERROR_CODE_MATCHER, '$1NG$2');
Is there any particular reason we use non-colorized formatting in ngcc?

2019-12-08 21:51 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/diagnostics/src/util.ts
> +    return errors.replace(ERROR_CODE_MATCHER, '$1NG$2');
@gkalpak As mentioned on Slack, there really isn't. I have changed ngcc to report colorized diagnostics with colors, [you can see them in action here](https://app.circleci.com/jobs/github/angular/ngcc-validation/2292/parallel-runs/3?filterBy=ALL).

2019-12-09 20:19 UTC, gkalpak approved these changes

2019-12-09 21:18 UTC, JoostK commented
merge-assistance: Current reviews should be sufficient, as I'm code owner of _fw-compiler_ (and it's only a comment change).

2019-12-09 22:05 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:284630278:BASE:284630318:1575929095987:5ecd385e)

2019-12-10 00:13 UTC, closed without merging