perf: add js-web-frameworks benchmark
angular/angular pull request #34034
Opened 2019-11-25 14:49 UTC by pkozlowski-opensource

2019-11-28 06:46 UTC, IgorMinar requested changes
I pushed a commit with a few fixes + added a bunch of comments. I find the structure of the app to be hard to follow, but I don't understand what constraints you had to write it this way. I suggest separating code into 4 parts:
- the bootstrap code
- the component under test
- the code that trigers various actions
- the benchpress spec

2019-11-28 09:22 UTC, pkozlowski-opensource commented on modules/benchmarks/src/js-web-frameworks/ng2/BUILD.bazel
> +    # TODO: FW-1004 Type checking is currently not complete.
Yeh, copy & paste fail, removed...

2019-11-28 09:26 UTC, pkozlowski-opensource commented on modules/benchmarks/src/js-web-frameworks/ng2/init.ts
> +// benchpress
This was a left-over comment from my earlier experiments, removed. Thnx for catching!

2019-11-28 09:40 UTC, pkozlowski-opensource commented on modules/benchmarks/src/js-web-frameworks/ng2/BUILD.bazel
> +    entry_point = ":index_aot.ts",
Yeh, was trying to keep it in-line with all the other existing benchmarks but I think that we should have just `index.ts`. Renamed it here and opened a follow-up issues to cleanup other benchmarks.

2019-11-28 10:00 UTC, pkozlowski-opensource commented on modules/benchmarks/src/js-web-frameworks/ng2/BUILD.bazel
> +    name = "ng2",
Nope, most definitively not! The thing is that I did this benchmark so it follows the folder / file structure of all the other benchmarks (otherwise it would be confusing because of inconstancy). 

For a long time I wanted to do a bigger cleanup of the existing benchmarks but "there was never time for it" :-/ I've opened https://github.com/angular/angular/issues/34127 listing all the cleanups I think we should do.

We've got 2 options here: 

1. create this benchmark in the way we want to see the final structure, live with the inconsistency for a while, and then cleanup other benchmarks to match this one;
2. create this benchmark in the way that it follows structure of the existing benchmarks and then cleanup all benchmarks based on #34127

Personally I would prefer (2) but not feeling too strongly about it!

2019-11-28 10:01 UTC, pkozlowski-opensource commented on modules/benchmarks/src/js-web-frameworks/ng2/rows.ts
> +  bootstrap: [JsWebFrameworksComponent],
Totally, couldn't agree more! Nope, most definitively not! The thing is that I did this benchmark so it follows the folder / file structure of all the other benchmarks (otherwise it would be confusing because of inconstancy). 

For a long time I wanted to do a bigger cleanup of the existing benchmarks but "there was never time for it" :-/ I've opened https://github.com/angular/angular/issues/34127 listing all the cleanups I think we should do.

We've got 2 options here: 

1. create this benchmark in the way we want to see the final structure, live with the inconsistency for a while, and then cleanup other benchmarks to match this one;
2. create this benchmark in the way that it follows structure of the existing benchmarks and then cleanup all benchmarks based on #34127

Personally I would prefer (2) but not feeling too strongly about it!

2019-11-28 10:06 UTC, pkozlowski-opensource commented
Thnx for the review @IgorMinar ! I've addressed smaller issues, but I guess the most important item is:

> I find the structure of the app to be hard to follow, but I don't understand what constraints you had to write it this way.

Totally with you! The only "constraint" I've imposed here was "consistency with the existing benchmarks folders / files structure".

I've opened #34127 so we can clean-up things. My personal preference would be to merge this PR so it matches the existing structure and then do across-the-board cleanup as described in #34127.
But we can also make this one "role model" and then cleanup other benchmarks.

WDYT?

In any case we need to coordinate any folder / file moves with the LL setup, if I'm not mistaken?

2019-12-02 16:40 UTC, IgorMinar commented on modules/benchmarks/src/js-web-frameworks/ng2/rows.ts
> +  bootstrap: [JsWebFrameworksComponent],
Let's go with #2 for now. Thanks for opening the issue.

2019-12-02 16:43 UTC, IgorMinar commented on modules/benchmarks/src/js-web-frameworks/ng2/BUILD.bazel
> +    name = "ng2",
Answered below. Let's go with #2.

2019-12-02 16:44 UTC, IgorMinar approved these changes
Lgtm. Let's refactor the folder structure separately from this change as it will affect LL.

2019-12-02 16:46 UTC, IgorMinar commented
Merge-assistance: no g3 impact. This is just a new benchmark

2019-12-02 18:51 UTC, closed without merging