test(ivy): Add unit tests for `insertTStyleValue`
angular/angular pull request #34077
Opened 2019-11-27 07:16 UTC by mhevery

Pulled out `insertTStyleValue` into a stand alone function which is easier to test. Added unit tests which assert that linked lists are correctly updated. This is a prerequisite for integration work.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-12-13 13:58 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/STYLING.md
> +The resulting string is than written into the DOM using `element.style.cssText` (or `elemet.className`.) We rely on the browser to dedup the extra styles.
Is this still the case? I thought that we need to write just `color: {{tmplColor}}` as people are asserting on the exact string in their tests?

2019-12-14 02:12 UTC, kara requested changes
First pass through (will go through duplicates section next)

2019-12-14 02:12 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> +    tData[index + 1] = toTStylingRange(templateTail, templateHead);
```suggestion
    tData[index + 1] = toTStylingRange(previousNode, nextNode);
```

2019-12-14 18:30 UTC, mhevery commented on packages/core/src/render3/styling/STYLING.md
> +The resulting string is than written into the DOM using `element.style.cssText` (or `elemet.className`.) We rely on the browser to dedup the extra styles.
No, this is out of date, but after discussion with @matsko we decided to remove the whole file.

2019-12-14 18:30 UTC, mhevery commented on packages/core/src/render3/styling/style_binding_list.ts
> + * |10 |`null`      |`{color: '#001'}`| `ɵɵstyleMap('color', {color: '#001'})`
👍 The table is really for the future me.

2019-12-14 20:48 UTC, mhevery reviewed
- I have addressed all of your comments
- I have added more tests and documentation 7f0a10d7b7

2019-12-14 20:53 UTC, mhevery commented on packages/core/src/render3/styling/style_binding_list.ts
> +import {assertEqual, assertNotEqual, throwError} from '../../util/assert';
```suggestion
import {assertEqual, throwError} from '../../util/assert';
```

2019-12-16 09:37 UTC, pkozlowski-opensource commented on packages/core/test/render3/styling_next/class_differ_spec.ts
> +  });
Solid tests @mhevery - so good that you've taken time to consider all those cases. Our future self thank you!

2019-12-16 09:49 UTC, pkozlowski-opensource commented on packages/core/src/render3/styling/style_binding_list.ts
> +    tData: TData, tNode: TNode, tStylingKey: TStylingKey, index: number, isHost: boolean,
nit: maybe rename `isHost` to `isHostBinding`? We use `isHost` quite often to denote a node that is a host of a directive (and does has to have host _bindings_) so things might get slightly confusing?

2019-12-16 10:44 UTC, pkozlowski-opensource commented on packages/core/src/render3/interfaces/node.ts
> +   * Stores the head/tail of the class bindings.
question: "Stores the head/tail of the class bindings." - we are storing _indexes_ of the head / tail, right? And those indexes point to entries in LView / TData ?

2019-12-16 11:31 UTC, pkozlowski-opensource commented on packages/core/src/render3/interfaces/node.ts
> +   * See: `style_binding_list.md` for details.
docs nit: The `style_binding_list.md` file was removed, right? So we should remove this reference as well?

2019-12-16 11:31 UTC, pkozlowski-opensource commented on packages/core/src/render3/interfaces/node.ts
> +   * See: `style_binding_list.md` for details.
docs nit: The `style_binding_list.md` file was removed, right? So we should remove this reference as well?

2019-12-16 11:35 UTC, pkozlowski-opensource commented on packages/core/test/render3/styling_next/style_binding_list_spec.ts
> +      debugger;
lint: `debugger;`

2019-12-16 15:15 UTC, kara commented on packages/core/src/render3/interfaces/node.ts
> +   * See: `style_binding_list.md` for details.
I think he means `style_binding_list.ts` here. But we should update the name!

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/interfaces/styling.ts
> + * NODE: *duplicate* false implies that it is statically know that this binding will not collide
```suggestion
 * NODE: *duplicate* false implies that it is statically known that this binding will not collide
```

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/interfaces/styling.ts
> + * with other binding and therefor there is no need to check other bindings. For example the
```suggestion
 * with other bindings and therefore there is no need to check other bindings. For example the
```

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> + *  - if `isHost === false` (we are template) than insertion is at tail of `TStylingRange`
```suggestion
 *  - if `isHost === false` (we are template) then insertion is at tail of `TStylingRange`
```

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> + *  - if `isHost === true` (we are host binding) than insertion is at head of `TStylingRange`
```suggestion
 *  - if `isHost === true` (we are host binding) then insertion is at head of `TStylingRange`
```

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> +    // If we don't have template bindings than `tail` is 0.
```suggestion
    // If we don't have template bindings then `tail` is 0.
```

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> + * Computes the new styling value starting `index` styling binding.
```suggestion
 * Computes the new styling value starting at `index` styling binding.
```

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> +  const lastGoodValueIndex = getTStylingRangePrev(tStylingRangeAtIndex);
What's a "good value"? I'm guessing you mean the last concatenated string value composed of styles that haven't changed? Can we add a comment or update the name?

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> + *              - `boolean` if `true` than add the key to the class list string.
```suggestion
 *              - `boolean` if `true` then add the key to the class list string.
```

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> + */
Add a return value line to the comment?

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> + * way. If `ɵɵstyleMap()` is not referenced than `STYLE_MAP_STYLING_KEY` will become eligible for
```suggestion
 * way. If `ɵɵstyleMap()` is not referenced then `STYLE_MAP_STYLING_KEY` will become eligible for
```

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> + * tree shaking. (`STYLE_MAP_STYLING_KEY` also pulls int the sanitizer as `ɵɵstyleMap()` could have
```suggestion
 * tree shaking. (`STYLE_MAP_STYLING_KEY` also pulls in the sanitizer as `ɵɵstyleMap()` could have
```

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> +      ngDevMode && throwError('Unsupported value for class binding: ' + value);
```suggestion
      ngDevMode && throwError('Unsupported value for style binding: ' + value);
```

2019-12-16 16:39 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> +      ngDevMode && throwError('Style binding do not support arrays bindings: ' + value);
```suggestion
      ngDevMode && throwError('Style bindings do not support array bindings: ' + value);
```

2019-12-16 19:17 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +   * Stores the head/tail of the class bindings.
yes, rewrote to make it more clear.

2019-12-16 19:17 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +   * See: `style_binding_list.md` for details.
fixed

2019-12-16 19:17 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +   * See: `style_binding_list.md` for details.
fixed

2019-12-16 19:17 UTC, mhevery commented on packages/core/src/render3/styling/style_binding_list.ts
> +    tData: TData, tNode: TNode, tStylingKey: TStylingKey, index: number, isHost: boolean,
renamed

2019-12-16 19:17 UTC, mhevery commented on packages/core/src/render3/styling/style_binding_list.ts
> +  const lastGoodValueIndex = getTStylingRangePrev(tStylingRangeAtIndex);
renamed and added comment.

2019-12-16 19:17 UTC, mhevery commented on packages/core/src/render3/styling/style_binding_list.ts
> + */
added.

2019-12-16 19:17 UTC, mhevery commented on packages/core/test/render3/styling_next/class_differ_spec.ts
> +  });
Thank you.

2019-12-16 19:17 UTC, mhevery commented on packages/core/test/render3/styling_next/style_binding_list_spec.ts
> +      debugger;
removed

2019-12-16 19:24 UTC, kara approved these changes
LGTM, but a few more typos to fix

2019-12-16 19:24 UTC, kara commented on packages/core/src/render3/interfaces/styling.ts
> +   * This bit is set to if the next binding contains a binding which could possibly cause a
```suggestion
   * This bit is set if the next binding contains a binding which could possibly cause a
```

2019-12-16 19:24 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> + * way. If `ɵɵstyleMap()` is not referenced than `STYLE_MAP_STYLING_KEY` will become eligible for
Update? ^

2019-12-16 19:24 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> + * way. If `ɵɵclassMap()` is not referenced than `CLASS_MAP_STYLING_KEY` will become eligible for
```suggestion
 * way. If `ɵɵclassMap()` is not referenced then `CLASS_MAP_STYLING_KEY` will become eligible for
```

2019-12-16 19:24 UTC, kara commented on packages/core/src/render3/styling/style_binding_list.ts
> +  // When styling changes we don't have to start at the begging. Instead we start at the change
```suggestion
  // When styling changes we don't have to start at the beginning. Instead we start at the first changed
```

2019-12-16 20:25 UTC, mhevery commented
merged as a71965671c

2019-12-16 20:25 UTC, closed without merging