WIP: refactor(ivy): remove unnecessary fac wrapper
angular/angular pull request #34076
Opened 2019-11-27 05:25 UTC by kara

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-11-27 20:43 UTC, IgorMinar approved these changes
that turned out to be quite a simple change! thanks

2019-11-27 20:44 UTC, JoostK commented on packages/compiler/src/injectable_compiler_2.ts
> +    factory: type.prop('ɵfac')
Can this be a forward reference, in which case it would not yet be available if evaluated eagerly like this?

2019-11-27 20:47 UTC, IgorMinar commented
this will also need a rebase

2019-11-27 20:55 UTC, kara commented on packages/compiler/src/injectable_compiler_2.ts
> +    factory: type.prop('ɵfac')
I don't think that's necessary. This factory is always generated next to the type referenced here, so it has to be defined.

2019-11-27 20:58 UTC, JoostK commented on packages/compiler/src/injectable_compiler_2.ts
> +    factory: type.prop('ɵfac')
Actually I think this test is showing it is possible: https://github.com/angular/angular/pull/34076/files#diff-c2c3919962b7deb686e11f9115af9de0R291

2019-11-27 21:01 UTC, kara commented on packages/compiler/src/injectable_compiler_2.ts
> +    factory: type.prop('ɵfac')
Ahh, I see what you mean. If the classes are different, then we will do what we did before with the wrapper. Adding a forward ref in all cases would defeat the purpose of the PR.

2019-11-28 00:01 UTC, kara commented
[VE presubmit](https://tap.corp.google.com/ui#id=OCL:282848321:BASE:282848339:1574899175458:8ce9448b)

[Ivy presubmit](https://test.corp.google.com/OCL:282848321:BASE:282848577:1574899274013:411416bc)

2019-11-28 00:09 UTC, IgorMinar approved these changes
looks good to me. I thought we were hoping for a slightly bigger impact, no? I'll take 1.2k for aio :)

2019-11-28 01:29 UTC, IgorMinar commented
merge-assistance: global approval

2019-11-28 06:31 UTC, crisbeto approved these changes
For the record, the reason it was set up this way to begin with was that if the order of `Comp.ɵfac` and `Comp.ɵcmp` is reversed, the factory in `Comp.ɵcmp` will be `undefined` because the factory hasn't been defined yet.

2019-12-02 13:34 UTC, petebacondarwin requested changes

2019-12-02 13:34 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/analysis/decoration_analyzer.ts
> +        this.isCore),
We should have a test for this. Apart from anything to prevent an accidental regression (despite the comment).
I would suggest adding one here https://github.com/angular/angular/blob/2fb9b7ff1b2da43410a624e8090062a2d3bbe02d/packages/compiler-cli/ngcc/test/integration/ngcc_spec.ts

2019-12-02 13:36 UTC, petebacondarwin commented
> that turned out to be quite a simple change! thanks

@IgorMinar - I would say that is because @alxhub did a good job of architecting ngtsc :-)

2019-12-02 17:12 UTC, kara commented on packages/compiler-cli/ngcc/src/analysis/decoration_analyzer.ts
> +        this.isCore),
I added a test for ngtsc, but not for ngcc. Good catch - will add.

2019-12-02 17:57 UTC, petebacondarwin approved these changes

2019-12-02 18:24 UTC, kara commented
merge-assistance: issue with `integration_test` failing on all PRs

2019-12-02 19:35 UTC, closed without merging