docs: remove deployment section on golang
angular/angular pull request #34099
Opened 2019-11-27 18:45 UTC by kapunahelewong

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/angular/angular/issues/34036

## What is the new behavior?

Removes Golang section in Deployment doc

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Errors were reported with go server, so we're removing this from this guide.

2019-11-27 18:54 UTC, mary-poppins commented
You can preview 019aa60 at https://pr34099-019aa60.ngbuilds.io/.

2019-11-27 20:36 UTC, IgorMinar reviewed
can you please explain why?

in general, please try to state the reason for the change in the commit message. The "what" is easy to see from the diff, the "why" is not. thanks!

2019-11-27 20:37 UTC, IgorMinar requested changes
plz update commit message with the "why"

2019-12-02 16:59 UTC, kapunahelewong commented
Is this better, @IgorMinar? I added a couple words to the message and the full context in the body. https://github.com/angular/angular/pull/34099/commits

2019-12-02 17:00 UTC, mary-poppins commented
You can preview 16f0fe7 at https://pr34099-16f0fe7.ngbuilds.io/.

2019-12-18 18:11 UTC, StephenFluin approved these changes

2019-12-18 19:36 UTC, mary-poppins commented
You can preview d157cfb at https://pr34099-d157cfb.ngbuilds.io/.

2019-12-23 16:34 UTC, mary-poppins commented
You can preview 720b436 at https://pr34099-720b436.ngbuilds.io/.

2020-01-06 19:42 UTC, mary-poppins commented
You can preview 3d261f8 at https://pr34099-3d261f8.ngbuilds.io/.

2020-01-08 21:50 UTC, mary-poppins commented
You can preview 8d03ef5 at https://pr34099-8d03ef5.ngbuilds.io/.

2020-01-30 14:58 UTC, IgorMinar approved these changes

2020-01-30 18:20 UTC, closed without merging