build: update integration/bazel & @angular/bazel schematics to rules nodejs 0.42.1
angular/angular pull request #34112
Opened 2019-11-27 22:46 UTC by gregmagolan

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-11-29 04:57 UTC, IgorMinar requested changes

2019-11-29 04:57 UTC, IgorMinar commented on integration/bazel/src/BUILD.bazel
> +pkg_web(
`pkg_web`? that seems to be a very unfortunate name especially when compared to `web_package`. Why this odd rename?

2019-11-29 04:57 UTC, IgorMinar commented on integration/bazel/src/BUILD.bazel
> +    # We output "_/index.html" instead ond remap in ts_devserver & pkg_web
typo: ond -> and

2019-11-29 04:57 UTC, IgorMinar commented on integration/bazel/src/BUILD.bazel
> +        # We load zone.js outside the bundle. That's because it's a "pollyfill"
typo: pollyfill -> polyfill

2019-11-29 04:57 UTC, IgorMinar commented on integration/bazel/src/BUILD.bazel
> +        # imports from it.
why don't you import as the first import in `main.ts` (or create polyfill.ts) similar to how the CLI does it: https://github.com/angular/angular-cli/blob/a956cea8673ee04c3054742afedd06743170deda/packages/schematics/angular/application/files/src/polyfills.ts.template#L58

it must the the first import though as we don't want to evaluate any other modules before the zone.js is evaluated.

once you do that, all of this html_insert_asset won't be necessary.

2019-11-29 17:28 UTC, gregmagolan commented on integration/bazel/src/BUILD.bazel
> +pkg_web(
To be consistent with the rest of the Bazel packaging rules: https://docs.bazel.build/versions/master/be/pkg.html

2019-11-29 17:29 UTC, gregmagolan commented on integration/bazel/src/BUILD.bazel
> +    # We output "_/index.html" instead ond remap in ts_devserver & pkg_web
👍 thanks

2019-11-29 17:30 UTC, gregmagolan commented on integration/bazel/src/BUILD.bazel
> +        # We load zone.js outside the bundle. That's because it's a "pollyfill"
👍 thanks

2019-11-29 17:39 UTC, gregmagolan commented on integration/bazel/src/BUILD.bazel
> +        # imports from it.
Sure. That would simplify things here. For the purposes of the integration test the zone.js script & bundle script tags could just go into the source `index.html` itself. The purpose of the integration test is is to test @angular/bazel & ng_module & ng_package so there is no need to exercise `html_insert_assets`.

For bazel-schematics we don't have control over the sources or the html file and `html_insert_assets` is meant to replace the inject script functionality `pkg_web` was take out of pkg_web (mix of concerns there as the packaging rule shouldn't also inject scripts into index.html).

In bazel-schematics we also inject `global_styleseet.css`:

```
html_insert_assets(
    name = "inject_scripts",
    outs = ["_/index.html"],
    args = [
        "--html",
        "$(location :index.html)",
        "--out",
        "$@",
        "--roots",
        "$(RULEDIR)",
        "--assets",
        "$(location :global_stylesheet.css)",
        "$(location @npm//:node_modules/zone.js/dist/zone.min.js)",
        "bundle.min.js",
    ],
    data = [
        ":index.html",
        ":global_stylesheet.css",
        "@npm//:node_modules/zone.js/dist/zone.min.js",
    ],
)
```

In the simple case this is all hidden from users unless the build with `--leaveBazelFilesOnDisk`.

2019-12-05 06:51 UTC, gregmagolan commented on integration/bazel/src/BUILD.bazel
> +        # imports from it.
Simplified. No more `html_insert_assets` in integration/bazel :)

2019-12-11 18:41 UTC, josephperrott approved these changes
LGTM

2019-12-11 18:55 UTC, josephperrott commented
Caretaker Note: Global Approval, @IgorMinar's requested changes were addressed.

2019-12-12 00:00 UTC, kara commented
@gregmagolan This broke CI tests once it was merged into master. See https://circleci.com/workflow-run/9482b603-90a1-474b-bcf3-eaabbda0fbf5

2019-12-12 00:11 UTC, gregmagolan commented
Thanks for the head up Kara. Will TAL after BazelCon tonight. About to do a lightning talk so good timing :)

2019-12-12 08:14 UTC, IgorMinar commented on integration/bazel/src/BUILD.bazel
> +pkg_web(
sgtm

2019-12-12 08:16 UTC, IgorMinar approved these changes
thanks for resolving my comments. please figure out what's up with the windows failure. otherwise lgtm

2019-12-28 20:13 UTC, gregmagolan commented
Will make a new PR to update to rules_nodejs 1.0.0 instead.

2019-12-28 20:13 UTC, closed without merging