docs: update injectable migration guide title and schematic description
angular/angular pull request #34125
Opened 2019-11-28 09:43 UTC by devversion

* See individual commits

2019-11-28 09:50 UTC, mary-poppins commented
You can preview 474e962 at https://pr34125-474e962.ngbuilds.io/.

2019-11-28 11:58 UTC, kapunahelewong approved these changes
LGTM. Thank you, @devversion!

2019-11-28 12:01 UTC, kapunahelewong commented
merge-assistance: Global approval for this docs-only change.

2019-11-29 05:05 UTC, IgorMinar requested changes
the title looks good, but the capitalization doesn't. Let's see what @kapunahele suggests we do.

2019-11-29 05:05 UTC, IgorMinar commented on aio/content/guide/migration-injectable.md
> +# Migration for missing `@Injectable()` decorators and incomplete provider definitions
this doesn't match the capitalization used in the other guides.

@kapunahelewong is this right? should we change the other guides or fix this one?

2019-11-29 09:13 UTC, devversion commented on aio/content/guide/migration-injectable.md
> +# Migration for missing `@Injectable()` decorators and incomplete provider definitions
Good point. Happy to make it consistent. For what it's worth: looks like some migration guides are not consistent either (e.g. `migration-dynamic-flag`)

2019-12-02 16:07 UTC, kapunahelewong commented on aio/content/guide/migration-injectable.md
> +# Migration for missing `@Injectable()` decorators and incomplete provider definitions
Ah, this change is correct (sentence case, that is, only the first word is capitalized and others are lower case unless they are customarily capitalized like `@Injectable()`). I believe when we changed docs teams we went from title case to sentence case. @jbogarthyde, would you like to look into our standard and correct me if I'm missing something here?

2019-12-02 16:14 UTC, jbogarthyde commented on aio/content/guide/migration-injectable.md
> +# Migration for missing `@Injectable()` decorators and incomplete provider definitions
That is correct. We have been applying it consistently to internal headings, but not as much to page headings (h1).  
Note that even when the page heading uses sentence case, the entry in the left-nav TOC should still be title case.

2019-12-02 16:15 UTC, jbogarthyde approved these changes

2019-12-02 19:21 UTC, closed without merging

2019-12-02 22:23 UTC, kapunahelewong commented on aio/content/guide/migration-injectable.md
> +# Migration for missing `@Injectable()` decorators and incomplete provider definitions
For reference, @jbogarthyde's PR doing a consistency sweep: https://github.com/angular/angular/pull/34196

Thanks, Judy!