docs: make header full-width and panels full-width on mobile screens
angular/angular pull request #34188
Opened 2019-12-02 17:51 UTC by ajitsinghkaler

Fixes #34163

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

In the current behavior, the width of the header is lesson events page in mobile screen and I made resources full screen on the mobile screen

Issue Number: #34163

## What is the new behavior?
The header is full screen and resources are full screens on mobile.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-12-02 18:16 UTC, ajitsinghkaler commented
@gkalpak can you please help me and tell me why the integration test is failing.

2019-12-03 11:18 UTC, mary-poppins commented
You can preview 416c06e at https://pr34188-416c06e.ngbuilds.io/.
You can preview 09ee065 at https://pr34188-09ee065.ngbuilds.io/.

2019-12-03 11:30 UTC, gkalpak requested changes
Thx, @ajitsinghkaler! Can you, please, update the commit message to `fix(docs-infra): ...` and also add some more info on what exactly it is fixing (e.g. the `events` and `resources` pages)?

2019-12-03 11:30 UTC, gkalpak commented on aio/src/styles/1-layouts/_marketing-layout.scss
> +  width:100%;
Please, put a space after `:`.

2019-12-03 11:30 UTC, gkalpak commented on aio/src/styles/2-modules/_resources.scss
> +    width:100%;
Please, put a space after `:`.

2019-12-03 11:30 UTC, gkalpak commented on aio/src/styles/1-layouts/_marketing-layout.scss
> +  width:100%;
Also, can you explain what difference does this make? `.marketing-banner` is only set on `<header>` (afaict), which is a block element by default. So, `width`, shouldn't make a difference. Did I miss something?

2019-12-03 16:30 UTC, mary-poppins commented
You can preview 3eedf88 at https://pr34188-3eedf88.ngbuilds.io/.

2019-12-03 16:30 UTC, ajitsinghkaler commented on aio/src/styles/1-layouts/_marketing-layout.scss
> +  width:100%;
In the current scenario if the table in the body of the docs takes more than screen width the header does not take 100% of the screen. That is if the screen is horizontally scrollable on mobile screens then the header does not take full width making width:100% lets it take full width in those scenarios also. I've attached a screenshot for reference.

![Angular - EVENTS (1)](https://user-images.githubusercontent.com/39260684/70069761-4fad3900-1618-11ea-8c87-e1301cb4f52f.png)

2019-12-03 16:35 UTC, ajitsinghkaler commented on aio/src/styles/2-modules/_resources.scss
> +    width:100%;
I've put a space.

Here right now we have put resources 80% on desktop leaving room for a sidebar if needed to be added later. but in mobile screens, the sidebar will not be added anyways. So I used the whole space and made it go 100%  on small screens. Attaching a screenshot for reference.

![Angular - EXPLORE ANGULAR RESOURCES (1)](https://user-images.githubusercontent.com/39260684/70070039-e2e66e80-1618-11ea-98ae-ac9d98b9a851.png)

2019-12-03 17:05 UTC, gkalpak commented on aio/src/styles/1-layouts/_marketing-layout.scss
> +  width:100%;
I see. I don't think this is the right fix (because I still see it not taking up 100% of the scroll width.
I believe you need to set `overflow: auto` (or `overflow-x: auto`) to the [`<article>` element][1] there.

[1]: https://github.com/angular/angular/blob/3eedf884fa50124ff0f5dfe9be4aa2b6150dc957/aio/content/marketing/events.html#L5

2019-12-04 01:15 UTC, ajitsinghkaler commented
@gkalpak now you can have a look I attached screenshots for what changes does this PR make.

2019-12-04 05:10 UTC, ajitsinghkaler commented on aio/src/styles/1-layouts/_marketing-layout.scss
> +  width:100%;
but I've checked it in the build it is working correct I've attached screenshots and link of the build page for your reference. Link: https://pr34188-09ee065.ngbuilds.io/events Please use this link in the mobile or responsive web version.

![Angular - EVENTS](https://user-images.githubusercontent.com/39260684/70114442-7c963600-1682-11ea-88f3-0974e4142d47.png)

2019-12-04 05:14 UTC, ajitsinghkaler commented on aio/src/styles/1-layouts/_marketing-layout.scss
> +  width:100%;
![Desktop screenshot (2)](https://user-images.githubusercontent.com/39260684/70114586-f9291480-1682-11ea-8136-0aa514ff3607.png)

2019-12-04 09:32 UTC, gkalpak commented on aio/src/styles/1-layouts/_marketing-layout.scss
> +  width:100%;
Your change does fix the issue on some screen sizes, but not all. If the screen is smaller (e.g. in DevTools choose iPhone 5) there is still an empty space on the right of the header:

![image](https://user-images.githubusercontent.com/8604205/70130614-82434a00-1689-11ea-94b5-90fbdee6e460.png)

Do you have any objection against my suggestion in https://github.com/angular/angular/pull/34188#discussion_r353307115?

2019-12-04 09:32 UTC, gkalpak commented
Thx, @ajitsinghkaler. Can you also take care of the second part of https://github.com/angular/angular/pull/34188#pullrequestreview-326062811?

2019-12-05 02:17 UTC, ajitsinghkaler commented on aio/src/styles/1-layouts/_marketing-layout.scss
> +  width:100%;
No I didn't have any objection it was just width:100% was working in my pc.

2019-12-05 02:42 UTC, ajitsinghkaler commented
@gkalpak I've integrated the changes you suggested and also changes the commit message please have a look

2019-12-05 02:47 UTC, mary-poppins commented
You can preview b934e2c at https://pr34188-b934e2c.ngbuilds.io/.

2019-12-05 12:06 UTC, gkalpak approved these changes

2019-12-05 12:06 UTC, gkalpak commented on aio/src/styles/1-layouts/_marketing-layout.scss
> +  overflow-x:auto;
```suggestion
  overflow-x: auto;
```

2019-12-05 16:11 UTC, mary-poppins commented
You can preview 9f2ae82 at https://pr34188-9f2ae82.ngbuilds.io/.

2019-12-05 16:25 UTC, ajitsinghkaler commented
@gkalpak I've made the changes please approve the pull request.

2019-12-05 19:53 UTC, gkalpak approved these changes

2019-12-05 19:54 UTC, gkalpak commented
**merge-assistance:** This is a docs-infra only change (it doesn't touch marketing content). My approval should be enough.

2019-12-05 21:06 UTC, closed without merging