docs: add rxweb reactive form validation library to the new list of Reactive Forms
angular/angular pull request #34257
Opened 2019-12-05 17:48 UTC by sholkajadav11

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-12-05 18:15 UTC, StephenFluin requested changes
The tool looks valuable.

Can you instead put it in the "Data Libraries" category, and make sure your JSON is valid?

2019-12-06 00:15 UTC, sholkajadav11 commented
@StephenFluin I have done the changes as per your suggestion.

2019-12-06 00:36 UTC, StephenFluin approved these changes
Final content looks good, but you'll need to squash your commits.

https://twitter.com/stephenfluin/status/1009904095073718275?lang=en

2019-12-06 16:50 UTC, sholkajadav11 commented
@StephenFluin I squashed the commit, Please check.

2019-12-06 17:54 UTC, StephenFluin commented
@sholkajadav11 I'm seeing 4 commits right now in the PR. There should only be one.

2019-12-06 20:53 UTC, sholkajadav11 commented
@StephenFluin Please check now.

2019-12-06 20:58 UTC, StephenFluin approved these changes

2019-12-17 00:54 UTC, sholkajadav11 commented
@StephenFluin @kapunahelewong I would like to know when this will be merged?

2019-12-17 19:05 UTC, kapunahelewong requested changes
Hi @sholkajadav11! Thanks for the tag - it really is super helpful for me. I've included some minor copy edits. When you're all ready (or if you have any questions) feel free to tag me. (By the way, ultimately, you'll want just one commit. Here are [my notes on the process](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) if you'd like them.)

EDIT: Oh, you already know the squashing part. 😊

2019-12-17 19:05 UTC, kapunahelewong commented on aio/content/marketing/resources.json
> +            "desc":"RxWeb Reactive Form Validators provides all type of complex, conditional, cross field and dynamic validation on validator based reactive forms, model based Reactive Form and Templ
```suggestion
            "desc":"RxWeb Reactive Form Validators provides all types of complex, conditional, cross field, and dynamic validation on validator-based reactive forms, model-based reactive forms, and template driven forms.",
```

2019-12-18 17:34 UTC, sholkajadav11 commented on aio/content/marketing/resources.json
> +            "desc":"RxWeb Reactive Form Validators provides all type of complex, conditional, cross field and dynamic validation on validator based reactive forms, model based Reactive Form and Templ
@kapunahelewong Thanks for the edits in the description :) . I have squashed the commit. Please let me know if anything I have to do.

2019-12-18 17:40 UTC, sholkajadav11 commented
@kapunahelewong I have squashed the commit, Please check.

2019-12-18 20:54 UTC, kapunahelewong commented on aio/content/marketing/resources.json
> +           "RxWebReactiveFormValidators":{
Oh, I missed this earlier. Could you fix the formatting? And [amend the commit message](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit)?

For the commit message, can you try something like this?

>docs: add rxweb reactive form validation library to resources

This means you'll remove the body. This part:

```
Update resources.json

docs: add @rxweb/reactive-form-validators info

Update resources.json

docs: add @rxweb/reactive-form-validators info
```

Please tag me if it gets tricky and I can help. Thanks again, @sholkajadav11.

2019-12-19 00:01 UTC, sholkajadav11 commented
Thank you @kapunahelewong for quick response, I fixed the formatting and amend the commit message. Please check :) .

2019-12-20 15:24 UTC, kapunahelewong approved these changes

2019-12-20 15:30 UTC, kapunahelewong commented
Looks good! Can you [rebase](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase)? That failure looks unrelated to your change, as maybe something that was fixed since you submitted the PR. Notice that there is a 159 commit difference between your fork and angular/angular master, so I think a rebase will fix it. If it doesn't but you're all up-to-date, I can then reach out for merge assistance.  Thanks, @sholkajadav11 🌺

2019-12-20 18:05 UTC, sholkajadav11 commented
@kapunahelewong I did mistake, Please guide me how I can correct.

2019-12-20 22:12 UTC, kapunahelewong commented
I think I got it from my end, @sholkajadav11 🌈. Would you like to review to make sure everything is how you intend it? To do it I had to check it out locally on my machine and push up. I backed up what you had just in case, but can you check after me? Thank you!!!

You're so close!! 🌺

2019-12-20 23:25 UTC, sholkajadav11 commented
All Good @kapunahelewong , Thank you very much. You are so kind. Once again thank you @kapunahelewong :).

2020-01-06 19:21 UTC, closed without merging

2020-01-06 21:10 UTC, kapunahelewong commented
🎉🌈🌸😊

2020-01-06 23:33 UTC, sholkajadav11 commented
Thank you @kapunahelewong for your support.

2020-01-08 19:12 UTC, kapunahelewong commented
It was great to see this get merged! 🌟😊