Incrementality for the win!
angular/angular pull request #34288
Opened 2019-12-06 23:37 UTC by alxhub

2019-12-09 18:57 UTC, JoostK requested changes

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +        trait = trait.toErrored([err.toDiagnostic()]);
nit: all `trait` reassignments here are never read from (my IDE shows them grayed out). Since `toErrored` et al mutate the trait and the return value is just to allow proper type inference this isn't a real problem, but on first glance this looks like a bug. I don't think that removing the assignments will really improve the situation here, though.

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +        if (result.diagnostics !== undefined) {
This is undesirable in cases where there's only warning/message diagnostics reported. I don't think we have those currently, but we should probably distinguish here. Can be done in followup work.

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +  index(ctx: IndexingContext): void {
Thanks for moving this down! This has annoyed me for a while :-)

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/transform/src/trait.ts
> +   * The result of
Unfinished

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/transform/src/trait.ts
> +class TraitImpl<D, A, R> {
This is beautiful!

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +         * The following set of tests verify that after Tsickle run we do not have cases
Indentation has gone weird because of earlier clang-formats. Can you go over this file and revert irrelevant changes?

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
> +      isComponent: false, ...extractDirectiveGuards(node, this.reflector),
Same here.

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/program.ts
> +      this.recordNgModuleScopeDependencies();
This call is missing from `loadNgStructureAsync` and that is **really** an issue...

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/shims/src/factory_tracker.ts
> +export class FactoryTracker {
This one could use a docblock on what information it captures and why that's relevant.

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts
> +      // TODO: don't mutate the analysis(!)
Agreed!

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/file_system/BUILD.bazel
> +      "@npm//@types/node",
Indentation is off.

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/incremental/api.ts
> +   *
Pending a comment

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/incremental/src/README.md
> +* share a module resolution cache between ngtsc & the cycle detector
I have this in a separate PR!

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/incremental/src/dependency_tracking.ts
> +  getDependencies(sf: T): ReadonlySet<string> { return this.metadataFor(sf).dependsOn; }
This isn't currently used.

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/incremental/src/dependency_tracking.ts
> +  private metadata = new Map<T, FileMetadata>();
I feel that the term `metadata` is no longer correct in this context. It's now the concrete dependency data, crucial to a dependency graph. How about something like `nodes` and rename `FileMetadata` into `DependencyNode` or something?

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/incremental/src/dependency_tracking.ts
> +  updateWithPhysicalChanges(
This is so nicely done! 👏

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/incremental/src/dependency_tracking.ts
> +  clone(): FileDependencyGraph<T> {
I don't see this being used anymore.

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/incremental/src/state.ts
> +import {ClassRecord, TraitCompiler} from '../../transform/src/compilation';
These should be exported from the entry-point of the `transform` target.

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/incremental/src/state.ts
> +      // to the current ones.
This sentence seems incorrect.

2019-12-09 18:57 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/program.ts
> +        depGraph.addTransitiveResources(ngModuleFile, file);
Nice catch! This need a test, though.

2019-12-09 19:03 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +import {FactoryTracker} from '../../shims';
This has gone unused.

2019-12-09 21:27 UTC, alxhub commented on packages/compiler-cli/ngcc/src/analysis/decoration_analyzer.ts
> +          match.resolution = data !;
It's needed because for some reason, `undefined` is assignable to `unknown`, but not to `Readonly<unknown>`. I'm now using an explicit cast to that instead.

2019-12-09 21:28 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +  readonly name = ComponentDecoratorHandler.name;
Nope!

`readonly name` is not static. This is using the name of the constructor function (class) `ComponentDecoratorHandler`, not the instance field `name`.

2019-12-09 21:36 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +  readonly name = ComponentDecoratorHandler.name;
Ah, right. This is a bug in my IDE, then, as it clicks through to the declaration of the field itself (TypeScript itself does the right thing, so it's an IntelliJ bug)

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +      isComponent: true, ...extractDirectiveGuards(node, this.reflector),
Agreed, and done.

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
> +      isComponent: false, ...extractDirectiveGuards(node, this.reflector),
Also done!

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts
> +      // TODO: don't mutate the analysis(!)
And done!

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/file_system/BUILD.bazel
> +      "@npm//@types/node",
Shouldn't have even been changed :)

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/incremental/src/README.md
> +* share a module resolution cache between ngtsc & the cycle detector
🚀

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/incremental/src/dependency_tracking.ts
> +  private metadata = new Map<T, FileMetadata>();
+1. I went with `FileNode` since it seems to fit.

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/incremental/src/dependency_tracking.ts
> +  getDependencies(sf: T): ReadonlySet<string> { return this.metadataFor(sf).dependsOn; }
Gone!

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/incremental/src/dependency_tracking.ts
> +  updateWithPhysicalChanges(
Thank you! I added some comments describing the behavior, since it's a little convoluted (the method both mutates the current state, and returns some information).

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/incremental/src/dependency_tracking.ts
> +  clone(): FileDependencyGraph<T> {
You are absolutely right, it's not.

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/incremental/src/state.ts
> +import {ClassRecord, TraitCompiler} from '../../transform/src/compilation';
Good catch!

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/incremental/src/state.ts
> +      // to the current ones.
Fixed!

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/program.ts
> +      this.recordNgModuleScopeDependencies();
Fixed!

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/program.ts
> +        depGraph.addTransitiveResources(ngModuleFile, file);
Agreed. I'm gonna do this in a follow-up though (when we do the proper module graph logic).

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/shims/src/factory_tracker.ts
> +export class FactoryTracker {
Done.

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> + * A t
Finished!

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +        if (result.diagnostics !== undefined) {
I don't believe we have any such messages, but yeah, we need to reflect the idea in the trait system that compilation can succeed with warnings.

2019-12-10 04:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +  index(ctx: IndexingContext): void {
👍 you and me both

2019-12-10 20:51 UTC, JoostK approved these changes
Typo in commit message of ad28e7a79b0b4d65357714e5b48c77e3d646c571:

but had grown more _compilated_ -> but had grown more **complicated**

2019-12-10 20:51 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/incremental/src/README.md
> +To skip emit, ngtsc uses the _current_ compilation's dependency graph to determine whether (given the information about which files have changed), a particular file has become stale on disk and needs
The part within parens here reads a bit awkward.

2019-12-10 20:51 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/incremental/src/dependency_tracking.ts
> +   * L(n) = the logically changed files from build n - 1 to build n.
Referring to build `n - 1` as representing the reference build for logical changes is not strictly true, as any changes during failed builds will accumulate.

2019-12-10 20:51 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/incremental/src/dependency_tracking.ts
> +      } else if (!deletedTsPaths.has(sf.fileName)) {
This condition is always true, given the first condition in `isLogicallyChanged`.

2019-12-10 20:51 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> + * The `TraitCompiler` is responsible for processing all classes in the program and
Unfinished sentence

2019-12-10 21:34 UTC, JoostK commented
One more thing: can you extract this logic  out into a method so that it can be shared between `loadNgStructureAsync` and `ensureAnalyzed`:

```ts
    this.compilation.resolve();

    this.recordNgModuleScopeDependencies();

    // At this point, analysis is complete and the compiler can now calculate which files need to be
    // emitted, so do that.
    this.incrementalDriver.recordSuccessfulAnalysis(this.compilation);
```

2019-12-11 22:22 UTC, alxhub commented
> compilated

Technically, we do work on the compiler, so the code does get more _compilated_ :-P 

Thanks, fixed!

2019-12-11 22:26 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/incremental/src/README.md
> +To skip emit, ngtsc uses the _current_ compilation's dependency graph to determine whether (given the information about which files have changed), a particular file has become stale on disk and needs
Reworded!

2019-12-11 22:28 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/incremental/src/dependency_tracking.ts
> +      } else if (!deletedTsPaths.has(sf.fileName)) {
Well spotted!

This is a holdover from when the dep graph was first copied and then updated with changes. At some point I rewrote the algorithm to start with an empty graph and populate it while accounting for changes, at which point deletion is no longer needed.

2019-12-11 23:12 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> + * The `TraitCompiler` is responsible for processing all classes in the program and
Finished!

2019-12-12 18:47 UTC, alxhub commented
[Presubmit](http://test/OCL:285217442:BASE:285223078:1576176387120:87ad3dcb)
[Ivy Presubmit](http://test/OCL:285217442:BASE:285223078:1576176387120:af9a71b7)

2019-12-12 19:41 UTC, alxhub commented
merge-assistance: I am the owner of the code in question.

2019-12-12 21:11 UTC, closed without merging

2020-01-07 10:57 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
>            // analyzed and the full compilation scope for the component can be realized.
Should this comment be removed?

2020-01-07 11:55 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
>            // analyzed and the full compilation scope for the component can be realized.
Agreed, it should have been removed. Nicely spotted!