fix(ivy): various IE issues
angular/angular pull request #34305
Opened 2019-12-08 13:15 UTC by crisbeto

Since we haven't been running the Ivy tests against IE for a while, we've accumulated some errors and test failures. These changes fix the issues which come from a handful of root causes:

**i18n instructions thrown off by sanitizer:**

While sanitizing on browsers that don't support the `template` element (pretty much only IE), we create an inert document and we insert content into it via `document.body.innerHTML = unsafeHTML`. The problem is that IE appears to parse the HTML passed to `innerHTML` differently, depending on whether the element has been inserted into a document or not. In particular, it seems to split some strings into multiple text nodes, which would've otherwise been a single node. This ended up throwing off some of the i18n code down the line and causing a handful of failures. I've worked around it by creating a new inert `body` element into which the HTML would be inserted.

**Proxies being used in DebugElement.classes:**

We're currently using proxies to pick up changes to element classes coming outside of Angular. Proxies aren't supported in IE and error is always thrown. I've reworked the tests where possible and skipped the rest with a TODO to come back and re-enable them once we have som kind of fallback.

**Inconsistent `typeof Node` value:**

We have a couple of cases where we use something like `typeof Node === 'function'` to figure out whether we're in a worker context. This works in most browsers, but IE returns `object` instead of `function`. I've updated all the usages to account for it.

**IE saving the attribute case:**

In `DebugElement.attributes` we return all of the attributes from the underlying DOM node. Most browsers change the attribute names to lower case, but IE preserves the case and since we use camel-cased attributes, the return value was inconsitent. I've changed it to always lower case the attribute names.

**Unable to get own function name:**

When we log DI errors we get the name of the provider via `SomeClass.name`. In IE functions that inherit from other functions don't have their own `name`, but they take the `name` from the lowest parent in the chain, before `Function`. I've added some changes to fall back to parsing out the function name from the function's string form.

**Different attribute order in innerHTML:**

We've got some tests that assert that the generate DOM looks correct. The problem is that IE changes the attribute order in `innerHTML` which caused the tests to fail. I've reworked the relevant tests not to assert directly against `innerHTML`.

**__proto__ not supported:**

IE doesn't support `__proto__`. I've added a fallback based on #34279.

2019-12-08 13:16 UTC, crisbeto commented on .circleci/config.yml
> +  saucelabs_ivy:
Note that this is copied over from #34277 so that I can check for more failures. I'll revert it before merging.

2019-12-09 09:30 UTC, gkalpak approved these changes

2019-12-09 09:30 UTC, gkalpak commented on packages/core/src/render3/instructions/element.ts
> +        (typeof HTMLUnknownElement !== 'undefined' && HTMLUnknownElement &&
Why the `HTMLUnknownElement` check? (Wouldn't `!== 'undefined'` and `instanceof` be enough?)

2019-12-09 09:30 UTC, gkalpak commented on packages/core/src/render3/jit/directive.ts
> +  // it'll always return the name of the function itself, no matter ho many other functions it
Typo: `ho` --> `how`

2019-12-09 09:30 UTC, gkalpak commented on packages/core/src/render3/jit/directive.ts
> +  const match = (type.toString() as string).match(/^function\s*([^\s(]+)/);
Is `type` guaranteed to have a `toString()` method? (If not, something like `'' + type` would be safer.)

2019-12-09 09:30 UTC, gkalpak commented on packages/core/src/di/jit/util.ts
> +      const proto = param.__proto__ || Object.getPrototypeOf(param);
Since we are using `Object.getPrototypeOf()` elsewhere (and `__proto__` is considered a bad practice), why not use `Object.getPrototypeOf()` in all cases?

(Also, why care about the prototype in the first place? Why not just `param.ngMetadataName`?)

2019-12-09 09:30 UTC, gkalpak commented on packages/core/test/acceptance/styling_spec.ts
> +    // TODO(FW-1767): retrieving classes set through Renderer2 currently depends on Proxy which
😱

2019-12-09 09:41 UTC, crisbeto commented on packages/core/src/render3/instructions/element.ts
> +        (typeof HTMLUnknownElement !== 'undefined' && HTMLUnknownElement &&
It's unlikely, but if it's null, `typeof HTMLUnknownElement` will be `object`.

2019-12-09 09:42 UTC, crisbeto commented on packages/core/src/di/jit/util.ts
> +      const proto = param.__proto__ || Object.getPrototypeOf(param);
I'm not sure about the reason tbh. I left it in assuming there was a reason for it. I can try dropping it to see if anything breaks.

2019-12-09 10:03 UTC, gkalpak commented on packages/core/src/render3/instructions/element.ts
> +        (typeof HTMLUnknownElement !== 'undefined' && HTMLUnknownElement &&
Makes sense :+1: (Although I have no idea why it might be `null`, it doesn't hurt to play it safe.) 
Consider making the intention more explicit by chaning it to `HTMLUnknownElement !== null` then.

2019-12-10 13:42 UTC, pkozlowski-opensource commented on .circleci/config.yml
> +  saucelabs_ivy:
I think that we should do the following:
* squash all the commits from #34277
* pick-up (cherry-pick) one commit here.

It would be much easier to see what is part of this PR and what is not if the CI work would be a separate commit.

2019-12-10 13:46 UTC, pkozlowski-opensource commented on packages/core/src/di/jit/util.ts
> +      const proto = param.__proto__ || Object.getPrototypeOf(param);
>  I can try dropping it to see if anything breaks.
yeh, using `getPrototypeOf` consistently would be the best.

2019-12-10 13:46 UTC, crisbeto commented on .circleci/config.yml
> +  saucelabs_ivy:
I can do it when I get home, but it's basically just the `.yml` file changes that have been taken from #34277.

2019-12-10 14:33 UTC, devversion commented on .circleci/config.yml
> +  saucelabs_ivy:
Either that, or the #34277 can be just merged afterwards (though I could see the point of having an indicator that this PR actually fixes IE issues)

2019-12-10 14:39 UTC, pkozlowski-opensource commented on .circleci/config.yml
> +  saucelabs_ivy:
> though I could see the point of having an indicator that this PR actually fixes IE issues

yeh, we should be able to see that the issues are actually fixed...

2019-12-10 14:45 UTC, devversion commented on .circleci/config.yml
> +  saucelabs_ivy:
Okay, my other PR is ready for merge, so Kristiyan can just pull in the `.patch` for that PR.

2019-12-10 21:51 UTC, crisbeto commented
Addressed the feedback from @pkozlowski-opensource and @gkalpak.

2019-12-11 06:18 UTC, crisbeto commented on packages/core/src/render3/jit/directive.ts
> +function getTypeName(type: any): string {
This one isn't necessary and was removed yesterday. I had copied it here for easier debugging since IE10's console logs objects as strings.

2019-12-11 10:27 UTC, pkozlowski-opensource requested changes
@crisbeto could you please pick up Paul's commits from https://github.com/angular/angular/pull/34277 as discussed?

Also, ideally I would like to see work-around related to `Proxy` usage (FW-1767) in a separate commit. The reason for this is that if we decide to merge #34328 (and it looks like we will) we might not want to merge your PR with work-arounds.

Generally speaking, I'm expecting that we are only going to merge parts of the work here so having small, focused commits would make the whole operation easier (I know it is more work for you, but it will help the overall effort)

2019-12-11 11:07 UTC, crisbeto commented
@pkozlowski-opensource the problem with cherry picking the commits is that the CLA bot will start complaining if there are mixed authors. I took Paul's changes just to illustrate that everything is passing, but I'll remove them before setting it as ready to merge.

Regarding the `Proxy` error: this is the reason why I left the TODO in there and mentioned it in the issue. If we get it fixed before this PR goes in, I'll rebase and remove my workarounds.

2019-12-11 18:07 UTC, crisbeto commented
The build changes have been reverted.

2019-12-11 19:46 UTC, kara approved these changes
Thanks for all these fixes!  Changes LGTM, but we should split the fixes into separate commits as @pkozlowski-opensource suggests. If there are unintended consequences (e.g. in G3) and we have to revert something, would rather not revert all changes. Maybe a natural way to split would be by section in the PR description?

2019-12-11 21:25 UTC, crisbeto commented
I've split it up into commits @kara.

2019-12-11 21:39 UTC, kara approved these changes

2019-12-12 13:45 UTC, pkozlowski-opensource reviewed
Thnx so much for splitting things up into individual commits - this is _so_ much cleaner and easier to review (plus easier to revert individual changes if needed)! Thnx again for doing this! 

I will keep this PR as  "Request changes" so it doesn't get merged accidentally. We will land it as soon as the proxy issues is resolved.

2019-12-13 07:06 UTC, crisbeto commented
I've dropped the commit that works around the `Proxy` usages since we agreed to remove them.

2019-12-13 11:49 UTC, petebacondarwin approved these changes
LGTM for i18n

2019-12-13 18:55 UTC, pkozlowski-opensource approved these changes

2019-12-13 20:50 UTC, mhevery approved these changes

2019-12-13 21:14 UTC, kara commented
[presubmit](http://test/OCL:285457504:BASE:285457538:1576271669561:283acb72)

2019-12-13 22:20 UTC, closed without merging