fix(docs-infra): convert hard-coded cli-builder examples into proper …
angular/angular pull request #34362
Opened 2019-12-12 02:37 UTC by sonukapoor

…mini-testable apps

Closes: #34314

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #34314

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2019-12-12 11:45 UTC, mary-poppins commented
You can preview 5ff281b at https://pr34362-5ff281b.ngbuilds.io/.

2019-12-12 12:30 UTC, gkalpak requested changes
Nice! I left a few comments, but this is definitely on the right track :+1:
Thx, @sonukapoor ✨ 

BTW, why the empty `main.ts` file?

2019-12-12 12:30 UTC, gkalpak commented on aio/content/examples/cli-builder/src/create-builder2.ts
> +    options.command.toString(),
Could we use `as string` instead? Using `.toString()` on something that is supposed to be a string is confusing.

Alternatively, we could improve the `options` type; e.g.: `options: {command: string, args: string[]}`

2019-12-12 12:30 UTC, gkalpak commented on aio/content/examples/cli-builder/src/create-builder2.ts
> +    options.args.toString().split('')
This is definitely wrong :grin:
How about `options.args as string[]` (or improving the `options` type - see previous comment)?

2019-12-12 12:30 UTC, gkalpak commented on aio/content/examples/cli-builder/src/create-builder2.ts
> +// #enddocregion
This file seems to share a lot of code with `create-builder1.ts`. Can you please merge them (and use docregions to only show what we need in each code snippet)?

2019-12-12 12:30 UTC, gkalpak commented on aio/content/examples/cli-builder/src/create-builder3.ts
> +// #enddocregion
Again , this files has a lot of code in common with the previous two. Please merge them (and subsequent ones) into one.
(This helps keep the snippets consistent and reduces the maintainability cost.)

2019-12-12 12:30 UTC, gkalpak commented on aio/content/examples/cli-builder/example-config.json
> +{
Can you please remove this file from this PR and add it to #34190 (once this one is merged)?
It would be better to have all the test infrastructure code in one PR. Let's keep this PR about getting rid of the hard-coded examples.

2019-12-12 12:30 UTC, gkalpak commented on aio/content/examples/cli-builder/src/create-builder-spec.ts
> +// Our builder forwards the STDOUT of the command to the logger.
This comment seems out of place here. Either remove it altogether or place it in its original position.

2019-12-12 12:30 UTC, gkalpak commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/create-builder-spec.ts" header="Testing a builder"></code-example>
Let's use `.spec.ts` for the file extension.

2019-12-12 12:30 UTC, gkalpak commented on aio/content/examples/cli-builder/src/create-builder-spec.ts
> +    expect(logs).toContain('index.spec.ts');
This should match this file's name.

2019-12-12 12:30 UTC, gkalpak commented on aio/content/examples/cli-builder/src/create-builder-spec.ts
> +  // This might not work in Windows.
Let's use something that work on Windows then :grin:
How about:

```ts
{
  command: 'node',
  args: ['--print', '\'foo\''],
}
```

(...and then verify that the logs contain `foo`?)

2019-12-12 14:26 UTC, sonukapoor commented on aio/content/examples/cli-builder/src/create-builder3.ts
> +// #enddocregion
I can merge the first two ones together, but this should be kept separate because of the different `child` options and their return types. Let me know if I am making sense.

2019-12-12 16:30 UTC, gkalpak commented on aio/content/examples/cli-builder/src/create-builder3.ts
> +// #enddocregion
The `{stdio: 'pipe'}` options don't make any difference, since that is the default. So you can either add it in all snippets or remove it altogether (the behavior will be the same in both cases). (Make sure to also adjust the guide content accordingly, if necessary.)

Also, the return types are the same (both return `Promise<BuilderOutput>`). (I know that some have `return new Promise(...)` and others `return new Promise<BuilderOutput>(...)`, but that shouldn't make a difference, because TypeScript should be able to infer the promise type from the function's return type (which is `Promise<BuilderOutput>`).)

2019-12-12 16:37 UTC, sonukapoor commented on aio/content/examples/cli-builder/src/create-builder3.ts
> +// #enddocregion
Sounds good. Thanks for the clarification.

2019-12-12 19:58 UTC, mary-poppins commented
You can preview c776fb0 at https://pr34362-c776fb0.ngbuilds.io/.

2019-12-13 10:04 UTC, gkalpak commented on .github/CODEOWNERS
> +/aio/content/guide/ivy-compatibility-examples.md                @angular/fw-docs-packaging @angular/framework-global-approvers @angular/framework-global-approvers-for-docs-only-changes
Oh, I see you removed the indentation fix 😞

2019-12-13 10:27 UTC, gkalpak requested changes
Some more (mostly minor) comments to go 👏 
@sonukapoor, could you also create a new GitHub issue to track adding tests for the `cli-builder` example?

2019-12-13 10:27 UTC, gkalpak commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/create-builder.ts" header="src/create-builder.ts (builder-skeleton)" region="builder-skeleton"></code-example>
Let's use `my-builder.ts` as the file name (since that is given as an example above).
(Note: The spec file needs to be renamed accordingly and any references in the guide as well.)

<sub>`create-builder.ts` is confusing, because it sounds like a builder for creating stuff (which is not the case) and also could perceived as referring to the `createBuilder()` function (which, again, is not the case).</sub>

2019-12-13 10:27 UTC, gkalpak commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/create-builder.ts" header="src/create-builder.ts (handling-output)" region="handling-output"></code-example>
```suggestion
<code-example path="cli-builder/src/create-builder.ts" header="src/create-builder.ts (handling output)" region="handling-output"></code-example>
```

2019-12-13 10:27 UTC, gkalpak commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/create-builder.ts" header="src/create-builder.ts (progess-reporting)" region="progress-reporting"></code-example>
```suggestion
<code-example path="cli-builder/src/create-builder.ts" header="src/create-builder.ts (progess reporting)" region="progress-reporting"></code-example>
```

2019-12-13 10:27 UTC, gkalpak commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/create-builder.ts" header="src/create-builder.ts (report-status)" region="report-status"></code-example>
```suggestion
<code-example path="cli-builder/src/create-builder.ts" header="src/create-builder.ts (report status)" region="report-status"></code-example>
```

2019-12-13 10:27 UTC, gkalpak commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/create-builder.spec.ts" header="Testing a builder"></code-example>
Please use a file name as `header`.

2019-12-13 10:27 UTC, gkalpak commented on aio/content/examples/cli-builder/src/create-builder.ts
> +    // #enddocregion builder-skeleton, builder, handling-output
```suggestion
    // #enddocregion builder, builder-skeleton, handling-output
```

😇

2019-12-13 10:27 UTC, gkalpak commented on aio/content/examples/cli-builder/src/create-builder.ts
> +    // #docregion handling-output, builder
```suggestion
    // #docregion builder, handling-output
```

2019-12-13 10:27 UTC, gkalpak commented on aio/content/examples/cli-builder/src/create-builder.ts
> +    // #enddocregion report-status, builder
```suggestion
    // #enddocregion builder, report-status
```

2019-12-13 11:32 UTC, sonukapoor commented on .github/CODEOWNERS
> +/aio/content/guide/ivy-compatibility-examples.md                @angular/fw-docs-packaging @angular/framework-global-approvers @angular/framework-global-approvers-for-docs-only-changes
By mistake. I will add it back :)

2019-12-13 11:34 UTC, sonukapoor commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/create-builder.ts" header="src/create-builder.ts (handling-output)" region="handling-output"></code-example>
Just to clarify on these `code-example` changes, do you want both of these changes?
The single line + removing the `-` from the header name.

2019-12-13 13:00 UTC, gkalpak commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/create-builder.ts" header="src/create-builder.ts (handling-output)" region="handling-output"></code-example>
I am a little confused. What do you mean by "single line"? (They are already on a single line 😕)

<sub>
Speaking of single lines, I would actually prefer the `<code-example>`s to be like this (for readability):

```
<code-example
    some-attr="some value"
    another-attr="another value">
</code-example>
```
</sub>

2019-12-13 13:20 UTC, sonukapoor commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/create-builder.ts" header="src/create-builder.ts (builder-skeleton)" region="builder-skeleton"></code-example>
Oh. Our linter must be doing that because I did put them on separate lines.

2019-12-13 13:20 UTC, sonukapoor commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/create-builder.ts" header="src/create-builder.ts (handling-output)" region="handling-output"></code-example>
Oh. Our linter must be doing that because I did put them on separate lines.

2019-12-13 13:30 UTC, sonukapoor commented
> Some more (mostly minor) comments to go 👏
> @sonukapoor, could you also create a new GitHub issue to track adding tests for the `cli-builder` example?

https://github.com/angular/angular/issues/34393

2019-12-13 14:21 UTC, mary-poppins commented
You can preview f752948 at https://pr34362-f752948.ngbuilds.io/.

2019-12-13 14:39 UTC, sonukapoor commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/create-builder.ts" header="src/create-builder.ts (handling-output)" region="handling-output"></code-example>
My bad, I formatted the `code-example` section in my other PR. Nothing to do with lint. I will updates these soon as well.

2019-12-13 15:40 UTC, mary-poppins commented
You can preview 07ab466 at https://pr34362-07ab466.ngbuilds.io/.

2019-12-14 20:46 UTC, gkalpak requested changes
One last comment to go :tada:

Can you also squash all commits together into one and change the commit message to something like:

> fix(docs-infra): convert hard-coded \`cli-builder\` examples into a proper mini-app
>
> Previously, the examples in the \`cli-builder\` guide were hard-coded.
> This made it impossible to test them and verify they are correct.
>
> This commit fixes this by converting them into a proper mini-app. In a
> subsequent commit, tests will be added to verify that the source code
> works as expected (and guard against regressions).
>
> Fixes #34314

<sub>BTW, `Closes #34314` would work too, but not `Closes: #34314` (there should be no semi-colon).</sub>

2019-12-14 20:46 UTC, gkalpak commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/my-builder.ts" header="src/my-builder.ts (report status)" region="report-status"></code-example>
```suggestion
<code-example
    path="cli-builder/src/my-builder.ts"
    header="src/my-builder.ts (report status)"
    region="report-status">
</code-example>
```

2019-12-14 22:12 UTC, sonukapoor commented on aio/content/guide/cli-builder.md
> +<code-example path="cli-builder/src/my-builder.ts" header="src/my-builder.ts (report status)" region="report-status"></code-example>
Good catch.

2019-12-14 22:26 UTC, mary-poppins commented
You can preview dd9793f at https://pr34362-dd9793f.ngbuilds.io/.

2019-12-15 09:49 UTC, gkalpak approved these changes
Great job, @sonukapoor 👏
(Thx for seeing this through ⭐️)

2019-12-16 01:09 UTC, Splaktar commented
@mgechev this is one that you probably want to take a look at.

2019-12-16 16:13 UTC, filipesilva approved these changes

2020-01-07 01:03 UTC, sonukapoor commented
@IgorMinar Could you please review this one? Thanks

2020-01-17 03:09 UTC, Splaktar approved these changes
LGTM. This fixes a number of issues that can cause confusion when going through this guide. It would be helpful to get this into version 9.

2020-01-17 22:09 UTC, mgechev approved these changes

2020-01-19 15:52 UTC, IgorMinar approved these changes
Thank you!

2020-01-19 19:53 UTC, gkalpak commented
@caretaker: Global approvals for the docs-only changes.

2020-01-21 18:12 UTC, closed without merging