feat(language-service): completions support for template reference variables
angular/angular pull request #34363
Opened 2019-12-12 03:09 UTC by ivanwonder

https://angular.io/guide/template-syntax#how-a-reference-variable-gets-its-value
get completions from option `exportAs` of `Directive`.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-12-12 14:27 UTC, ayazhafiz submitted a review, later dismissed

2019-12-12 14:27 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +  const isTemplateRef = attr.name.startsWith('#') || attr.name.startsWith('ref-');
Please add a comment linking to reference variable documentation (https://angular.io/guide/template-syntax#template-reference-variables-var)

2019-12-12 14:27 UTC, ayazhafiz commented on packages/language-service/test/completions_spec.ts
> +    const fileName = mockHost.addCode(`
please use `mockHost.override`. It generally speeds up the tests.

2019-12-12 14:27 UTC, ayazhafiz commented on packages/language-service/test/completions_spec.ts
> +            >Name <input class="form-control" name="name" ngModel required />
is this newline intentional?

2019-12-12 14:27 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +          result.push({name: exportAs, kind: ng.CompletionKind.REFERENCE, sortText: exportAs});
nit: consider renaming `exportAs` to a more semantic name in this context, maybe `directiveName`

2019-12-12 18:51 UTC, kyliau reviewed
Thank you for contributing! Your help is much appreciated :)

2019-12-12 18:51 UTC, kyliau commented on packages/language-service/src/completions.ts
> +  const isTemplateRef = attr.name.startsWith('#') || attr.name.startsWith('ref-');
Could you please add a test for the `ref-` case?

2019-12-13 01:47 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +          result.push({name: exportAs, kind: ng.CompletionKind.REFERENCE, sortText: exportAs});
I think it's better to use the name defined by angular https://angular.io/api/core/Directive#exportas

2019-12-17 02:47 UTC, kyliau requested changes

2019-12-17 02:47 UTC, kyliau commented on packages/language-service/src/completions.ts
> +    if (path.tail instanceof ReferenceAst) {
Sorry for the delay, it took me a while to get back to this PR.
This is not the right place to do this check, because the `ExpressionVisitor` is designed specifically to traverse the TemplateAst. In this case, this visitor already knows how to go to a reference via `visitReference()`.
`ExpressionVisitor` extends `NullTemplateVisitor` and the reference node is currently not visited. This method needs to be added.
Please let me know if you need more info / clarification. I'm happy to guide you through.
Thank you again!

2019-12-17 03:00 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +    if (path.tail instanceof ReferenceAst) {
I try the method with visitReference(). There is a problem.
`<form #itemForm="ngF~{reference}"></form>`
When the angular parses the HTML, it will report an error `Template parse errors:
There is no directive with "exportAs" set to "ngF"`. So the `visitReference()` method will not invoked. This is why I add the code on line 251

2019-12-17 03:22 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +    if (path.tail instanceof ReferenceAst) {
So the `path.tail` is assigned to element `form`, and will not be regarded as a template reference.

2019-12-17 21:45 UTC, kyliau commented
@ivanwonder, you are correct. The TemplateAst parser does not parse attributes correctly. This is bad, because it means there's no 1-1 mapping from HtmlAst to TemplateAst.
More specifically, the HtmlAst would contain `Element --> Attribute`, but when it gets parsed into TemplateAst, there's only `ElementAst`. This is why the visit has no effect.
I'll fix this in a separate PR, and you should be able to implement this feature the correct way after that.
Thank you for your patience!

2019-12-18 02:46 UTC, ivanwonder commented
Thank you for your guidance. I will pick it up after you fix the problem.

2019-12-20 03:19 UTC, ivanwonder commented
@kyliau I think I can help to resolve the problem of `TemplateAst` if you have not begun to do it or no time to look into it.
I recently read the code, and my solution is to add the reference to the array `targetReferences` before reporting the error on line 596.
https://github.com/angular/angular/blob/2dffe65cfdc1329819a5ef0d0f2069efb0b07ff8/packages/compiler/src/template_parser/template_parser.ts#L593-L608

2019-12-20 22:04 UTC, ayazhafiz commented
> @kyliau I think I can help to resolve the problem of `TemplateAst` if you have not begun to do it or no time to look into it.

I think this was partially fixed in #34459, @kyliau can you confirm? I think you would have to do a little extra work to get `visitReference` to be called, since that change parses an attribute and not a reference, but you could add a call to `visitReference` in `ExpressionVisitor#visitAttr` or parse the reference where the attribute is.

> I recently read the code, and my solution is to add the reference to the array `targetReferences` before reporting the error on line 596.

I think this would work, but we will have to get a review from the compiler team to make sure it is okay. My only worry is that this would break the typings of the ReferenceAst because the value of the created reference AST would be null (since there is no matching directive to reference), so this might cause some trouble if the reference is used later in the template (but if an error is reported, I don't know if this matters).

2019-12-20 22:22 UTC, kyliau commented
yes, @ayazhafiz is right. I did the work in #34459 to partially address the problem of incomplete template AST. The ideal solution here is to visit AttrAst, create ReferenceAst, then visit it.
However, in order to get hold of the directives that apply to an Element, you have to pass the ElementAst to visitReference() as well. This can be done through the context (second parameter).
Bear in mind that it is insufficient to provide "exportAs" as the sole result set, as was done here. Other symbols that are in scope are valid candidates too.

2019-12-21 00:22 UTC, ivanwonder commented
@kyliau What are the other symbols,  can you give me an example? When I input others, it will report the error no directive with "exportAs"

2019-12-21 02:53 UTC, ivanwonder commented
I think it's better to add a new `referenceAttributeValueCompletions` here.
https://github.com/angular/angular/blob/9b9116c79d626b6356f3dfe0d48c9d990ac412a2/packages/language-service/src/completions.ts#L177
Just push the missing `ReferenceAst` to `path` if need, begin to visit it with `ElementAst` parameter in the new method. Like 
https://github.com/angular/angular/blob/9b9116c79d626b6356f3dfe0d48c9d990ac412a2/packages/language-service/src/completions.ts#L362
It's a little kind of weird to invoke the method `visitReference` in `visitAttr`, travel the `path` to get the right `ElementAst` and pass it to `visitReference`.

2019-12-21 08:48 UTC, ivanwonder commented
> yes, @ayazhafiz is right. I did the work in #34459 to partially address the problem of incomplete template AST. The ideal solution here is to visit AttrAst, create ReferenceAst, then visit it.

This is the new implementation, if need, I can change to the way as @kyliau  said above.

2019-12-21 19:20 UTC, ayazhafiz requested changes

2019-12-21 19:20 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +              }
I would prefer doing this one nesting up, because if we're in a reference name, we probably don't want to show completions since a new reference is being defined.

```typescript
const bindParts = ast.name.match(BIND_NAME_REGEXP);
const isReference = bindParts && bindParts[ATTR.KW_REF_IDX] !== undefined;
if (!isReference && (!ast.valueSpan || !inSpan(templatePosition, spanOf(ast.valueSpan)))) {
  result = attributeCompletions(templateInfo, path);
} else if (ast.valueSpan && inSpan(templatePosition, spanOf(ast.valueSpan))) {
  if (isReference) {
    result = referenceAttributeValueCompletions(templateInfo, templatePosition, ast);
  } else {
    result = attributeValueCompletions(templateInfo, templatePosition, ast);
  }
}
```

2019-12-21 19:20 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +  // When the template parser donot find the directive with "exportAs",
```suggestion
  // When the template parser does not find a directive with matching "exportAs",
```

2019-12-21 19:20 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +    // The sourceSpan of an AttrAst is the valueSpan of the HTML Attribute.
```suggestion
    // The sourceSpan of a ReferenceAst is the valueSpan of the HTML Attribute.
```

2019-12-21 19:20 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +    path.push(new ReferenceAst(attr.name, null !, attr.value, attr.valueSpan !));
Maybe we should create a dummy value for the ReferenceAst's value, but we can do that in another PR.

2019-12-21 19:20 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +      const exportAs = dir.directive.exportAs;
nit
```suggestion
      const {exportAs} = dir.directive;
```

2019-12-22 02:48 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +    path.push(new ReferenceAst(attr.name, null !, attr.value, attr.valueSpan !));
Agree, the `ReferenceAst ` with second parameter `null` will refer to the DOM element on which it is declared.
https://github.com/angular/angular/blob/2dffe65cfdc1329819a5ef0d0f2069efb0b07ff8/packages/compiler/test/template_parser/template_parser_spec.ts#L1318-L1321

2019-12-22 03:48 UTC, ayazhafiz approved these changes
Thanks for the feature 🙂

2019-12-22 03:48 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +  // the ReferenceAst will be ignore.
```suggestion
  // the ReferenceAst will be ignored.
```

2020-01-09 01:02 UTC, kyliau approved these changes

2020-01-09 21:45 UTC, closed without merging