WIP - build(docs-infra): update docs examples to latest v9 and Ivy
angular/angular pull request #34374
Opened 2019-12-12 13:40 UTC by gkalpak

2019-12-12 13:46 UTC, mary-poppins commented
You can preview c6f5e72 at https://pr34374-c6f5e72.ngbuilds.io/.

2019-12-12 14:43 UTC, mary-poppins commented
You can preview d3acac0 at https://pr34374-d3acac0.ngbuilds.io/.

2019-12-12 16:14 UTC, mary-poppins commented
You can preview 8b02ec3 at https://pr34374-8b02ec3.ngbuilds.io/.

2019-12-12 19:29 UTC, mary-poppins commented
You can preview 94dced4 at https://pr34374-94dced4.ngbuilds.io/.

2019-12-12 20:04 UTC, mary-poppins commented
You can preview bdb74cb at https://pr34374-bdb74cb.ngbuilds.io/.

2019-12-12 21:47 UTC, mary-poppins commented
You can preview 1987ff7 at https://pr34374-1987ff7.ngbuilds.io/.

2019-12-12 22:16 UTC, mary-poppins commented
You can preview 9f7cbc2 at https://pr34374-9f7cbc2.ngbuilds.io/.

2019-12-12 22:34 UTC, mary-poppins commented
You can preview be630c0 at https://pr34374-be630c0.ngbuilds.io/.

2019-12-13 10:57 UTC, mary-poppins commented
You can preview 7294b9f at https://pr34374-7294b9f.ngbuilds.io/.

2019-12-13 11:59 UTC, mary-poppins commented
You can preview 334bb0b at https://pr34374-334bb0b.ngbuilds.io/.

2019-12-13 13:00 UTC, mary-poppins commented
You can preview 92a917a at https://pr34374-92a917a.ngbuilds.io/.

2019-12-31 10:32 UTC, mary-poppins commented
You can preview 8255f1a at https://pr34374-8255f1a.ngbuilds.io/.

2020-02-04 23:21 UTC, IgorMinar requested changes
as discussed in https://github.com/angular/angular/pull/35091#discussion_r373775396 let's also switch the npm fw packages to the dist/packagest-dist VE distribution

2020-02-13 16:57 UTC, mary-poppins commented
You can preview a4893e2 at https://pr34374-a4893e2.ngbuilds.io/.

2020-02-13 17:43 UTC, mary-poppins commented
You can preview 04bc693 at https://pr34374-04bc693.ngbuilds.io/.

2020-02-24 18:48 UTC, mary-poppins commented
You can preview 475f1c9 at https://pr34374-475f1c9.ngbuilds.io/.

2020-02-24 21:12 UTC, mary-poppins commented
You can preview b625c18 at https://pr34374-b625c18.ngbuilds.io/.

2020-02-24 21:26 UTC, mary-poppins commented
You can preview d4fab26 at https://pr34374-d4fab26.ngbuilds.io/.

2020-02-25 10:26 UTC, mary-poppins commented
You can preview d052718 at https://pr34374-d052718.ngbuilds.io/.

2020-02-25 18:42 UTC, mary-poppins commented
You can preview 49b1ee1 at https://pr34374-49b1ee1.ngbuilds.io/.

2020-02-25 19:18 UTC, mary-poppins commented
You can preview 963eac0 at https://pr34374-963eac0.ngbuilds.io/.

2020-02-25 19:54 UTC, mary-poppins commented
You can preview b221938 at https://pr34374-b221938.ngbuilds.io/.

2020-02-25 20:17 UTC, mary-poppins commented
You can preview 04f904a at https://pr34374-04f904a.ngbuilds.io/.

2020-02-27 15:57 UTC, mary-poppins commented
You can preview 73cc101 at https://pr34374-73cc101.ngbuilds.io/.

2020-02-29 16:38 UTC, mary-poppins commented
You can preview bcb53ca at https://pr34374-bcb53ca.ngbuilds.io/.

2020-02-29 19:22 UTC, gkalpak commented
Marking this as blocked on #35778 and #35780, since they need to land first.

2020-02-29 23:25 UTC, mary-poppins commented
You can preview df58abd at https://pr34374-df58abd.ngbuilds.io/.

2020-03-02 08:51 UTC, mary-poppins commented
You can preview b475e53 at https://pr34374-b475e53.ngbuilds.io/.

2020-03-03 11:27 UTC, mary-poppins commented
You can preview 4d9a91c at https://pr34374-4d9a91c.ngbuilds.io/.

2020-03-03 12:09 UTC, mary-poppins commented
You can preview 73b5f11 at https://pr34374-73b5f11.ngbuilds.io/.

2020-03-03 18:11 UTC, mary-poppins commented
You can preview f8b5fb2 at https://pr34374-f8b5fb2.ngbuilds.io/.

2020-03-03 18:31 UTC, mary-poppins commented
You can preview cd97096 at https://pr34374-cd97096.ngbuilds.io/.

2020-03-04 12:26 UTC, mary-poppins commented
You can preview e1e56a1 at https://pr34374-e1e56a1.ngbuilds.io/.

2020-03-04 16:39 UTC, mary-poppins commented
You can preview 24dc855 at https://pr34374-24dc855.ngbuilds.io/.

2020-03-04 16:49 UTC, mary-poppins commented
You can preview e5d6683 at https://pr34374-e5d6683.ngbuilds.io/.

2020-03-09 15:53 UTC, mary-poppins commented
You can preview ed915a3 at https://pr34374-ed915a3.ngbuilds.io/.

2020-03-10 13:34 UTC, mary-poppins commented
You can preview 6eac4cc at https://pr34374-6eac4cc.ngbuilds.io/.

2020-03-11 14:48 UTC, mary-poppins commented
You can preview 89a37a0 at https://pr34374-89a37a0.ngbuilds.io/.

2020-03-15 11:08 UTC, mary-poppins commented
You can preview c095256 at https://pr34374-c095256.ngbuilds.io/.

2020-03-15 13:20 UTC, mary-poppins commented
You can preview dbae03a at https://pr34374-dbae03a.ngbuilds.io/.

2020-03-16 15:05 UTC, mary-poppins commented
You can preview d8b3206 at https://pr34374-d8b3206.ngbuilds.io/.

2020-03-20 19:49 UTC, mary-poppins commented
You can preview c8ce569 at https://pr34374-c8ce569.ngbuilds.io/.

2020-03-21 02:14 UTC, CaerusKaru commented on aio/content/guide/universal.md
> +One solution would be to provide the full URL to your application on the server (e.g. as a server-side only extra provider) and write an interceptor that can retrieve this value and prepend it to the
As much as is this is probably the most approachable solution, I'd like to recommend providing the `url` option to `renderModule` from `@angular/platform-server`, since that initializes the URL platform-wide.

2020-03-21 02:14 UTC, CaerusKaru approved these changes

2020-03-23 17:32 UTC, gkalpak commented on aio/content/guide/universal.md
> +One solution would be to provide the full URL to your application on the server (e.g. as a server-side only extra provider) and write an interceptor that can retrieve this value and prepend it to the
Nice! I didn't know about that; thx for bringing it up :+1:
I have pushed a fixup commit to recommend this approach instead: https://github.com/angular/angular/pull/34374/commits/3072e2e2f3109036020f650a78905802da1bc5e7

2020-07-03 14:13 UTC, gkalpak commented
The final bit was addressed in #36924, so this can be closed.

2020-07-05 20:39 UTC, closed without merging