fix(ivy): improve ExpressionChangedAfterChecked error
angular/angular pull request #34381
Opened 2019-12-12 20:52 UTC by AndrewKushnir

Prior to this change, the ExpressionChangedAfterChecked error thrown in Ivy was missing useful information that was available in View Engine, specifically: missing property name for property bindings and also the content of the entire property interpolation (only a changed value was displayed) if one of expressions was changed unexpectedly. This commit improves the error message by including the mentioned information into the error text.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-12-17 01:10 UTC, kara requested changes
Thanks for picking this up!

2019-12-17 20:33 UTC, AndrewKushnir commented on packages/core/test/acceptance/change_detection_spec.ts
> +             .toThrowError(/Previous value: '.*?initial'. Current value: '.*?changed'/);
Thanks Kara, I've created a ticket with additional improvements that we can make once this PR lands: #34454.

2019-12-17 20:36 UTC, AndrewKushnir commented on packages/core/src/render3/errors.ts
> +    while (typeof tData[idx] !== 'string' && tData[idx + 1] === null && idx >= getBindingRoot()) {
My goal was to avoid going too far "left", i.e. beyond the index where bindings start. However that should not be critical for the error message details assembling logic, so I removed the check.

2019-12-17 20:41 UTC, AndrewKushnir commented
@kara thanks for the review! I've addressed your comments, could you please have another look?

2019-12-17 20:52 UTC, Airblader commented on packages/core/src/render3/errors.ts
> +        ` Has it been created in a change detection hook ?`;
Not your change, but there should be no space before the question mark.

2019-12-17 20:52 UTC, Airblader commented on packages/core/src/render3/errors.ts
> +  // TODO: include debug context
Isn't this what you're doing now? Or does this mean something else?

2019-12-17 21:00 UTC, AndrewKushnir commented on packages/core/src/render3/errors.ts
> +        ` Has it been created in a change detection hook ?`;
Thanks for noticing that, I've updated the message to remove that whitespace.

2019-12-17 21:00 UTC, AndrewKushnir commented on packages/core/src/render3/errors.ts
> +  // TODO: include debug context
That's a different debug context, see https://github.com/angular/angular/blob/04d4fea3e8784ea81916b24f3b153331967bad71/packages/core/src/view/errors.ts#L36. I've updated the comment, so it's more clear.

2019-12-17 22:56 UTC, kara approved these changes
LGTM, with a few more small things

2019-12-17 22:56 UTC, kara commented on packages/core/test/acceptance/change_detection_spec.ts
> +    onlyInIvy('VE doesn\'t throw in case of [class] binding change')
Can we do the same with this test as the one above? It's also something we should fix.

2019-12-17 22:56 UTC, kara commented on packages/core/test/acceptance/change_detection_spec.ts
> +  });
Can we add tests for: 

- `attr.X` cas
- Host binding case

For the "attr" case, it would be nice if we could print the interpolation string and format as "attr.X", but that should probably go in a follow-up as well.

2019-12-18 00:20 UTC, AndrewKushnir commented on packages/core/test/acceptance/change_detection_spec.ts
> +  });
Added extra tests for `attr.x` cases and host bindings. Will improve error message for `attr.x` once this PR lands 👍

2019-12-18 00:26 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:286084253:BASE:286084291:1576628633370:2f6af284)

2019-12-18 00:26 UTC, kara approved these changes
LGTM

2019-12-18 17:13 UTC, closed without merging