docs: add example links to downgradeComponent function docs
angular/angular pull request #34406
Opened 2019-12-14 09:58 UTC by ajitsinghkaler

There were some extra examples for downgradeComponent in the upgrade guide added the link to those examples in the downgradeComponent docs

Fixes #31584

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The current downgradeComponent has only one example.

Issue Number: #31584

## What is the new behavior?

There were some extra examples for downgradeComponent in the upgrade guide added the link to those examples in the downgradeComponent docs

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-12-14 09:59 UTC, ajitsinghkaler commented
@kapunahelewong can you please review this.

2019-12-14 19:42 UTC, gkalpak requested changes
Thx, @ajitsinghkaler :+1:

I left a couple of suggestions. Can you also update the commit message to something like:

> docs(upgrade): add example links to \`downgradeComponent()\` function docs
>
> There were some extra examples for \`downgradeComponent()\` in the upgrade
> guide. Added a link to the relevant section of the guide in the
> \`downgradeComponent()\` docs.
>
> Fixes #31584

2019-12-14 19:42 UTC, gkalpak commented on packages/upgrade/src/common/src/downgrade_component.ts
> + * For more examples and details of upgrading AngularJS Components to
```suggestion
 * For more details and examples on downgrading Angular components to AngularJS components please
```

2019-12-14 19:42 UTC, gkalpak commented on packages/upgrade/src/common/src/downgrade_component.ts
> + * Angular Components please visit the
```suggestion
 * visit the [Upgrade guide](guide/upgrade#using-angular-components-from-angularjs-code).
```

2019-12-14 19:42 UTC, gkalpak commented on packages/upgrade/src/common/src/downgrade_component.ts
> + * [Upgrade guide](https://angular.io/guide/upgrade#using-angular-components-from-angularjs-code)
```suggestion
```

2019-12-15 05:03 UTC, ajitsinghkaler commented
@gkalpak I've made the changes and can you tell me more about this google3 check in ci

2019-12-15 09:33 UTC, mary-poppins commented
You can preview 8438eeb at https://pr34406-8438eeb.ngbuilds.io/.
You can preview 947e823 at https://pr34406-947e823.ngbuilds.io/.
You can preview 11ab7cc at https://pr34406-11ab7cc.ngbuilds.io/.

2019-12-15 09:35 UTC, gkalpak approved these changes

2019-12-15 09:37 UTC, gkalpak commented
👌 

> can you please tell me more about the google3 check, in ci

Don't worry about that. That is a Google-specific check, so a Google has to run it (if necessary at all).

##
@caretaker: This is a docs-only change. Maybe g3sync is not needed?

2019-12-16 15:45 UTC, closed without merging