Static styling
angular/angular pull request #34418
Opened 2019-12-16 05:13 UTC by mhevery

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-12-16 06:23 UTC, matsko requested changes
This entire PR does way more than it should and has continuously grown all the while #34000 has been wasting time being rebased on this. We need discuss what the boundaries are.

2019-12-18 02:48 UTC, kara requested changes

2019-12-18 02:48 UTC, kara commented on packages/core/src/render3/styling/styling_parser.ts
> + * Parses the `className` into individual class tokens.
```suggestion
 * Initializes `className` string for parsing
```

2019-12-18 02:48 UTC, kara commented on packages/core/src/render3/styling/style_differ.ts
> +  for (let i = parseStyle(text); (i = parseStyleNext(text, i)) >= 0;) {
This format is a bit hard to read because the condition and the iterator are combined.  If we add a `parseStyleNext(...)` invocation to the end of the `parseStyle` method, we can make the iteration look more idiomatic/readable:

```suggestion
  for (let i = parseStyle(text); i >= 0; i = parseStyleNext(text, i)) {
```

2020-01-02 18:04 UTC, mhevery commented on packages/core/src/render3/styling/styling_parser.ts
> + * Parses the `cssText` into individual key/value tokens.
I would like to keep it here. See screenshot below. It provides nice help to the user when using the function. If we move it to file level the developer will not get instructions on how to use it.

![Screen Shot 2020-01-02 at 9 59 51 AM](https://user-images.githubusercontent.com/111951/71683217-c12af500-2d46-11ea-8afe-fe4b011ad276.png)

2020-01-02 18:06 UTC, mhevery commented
fixes 765737ed40

2020-01-02 22:41 UTC, mhevery commented
[presubmit](http://test/OCL:287897157:BASE:287897213:1578004783356:71b84a7d)

2020-01-06 15:34 UTC, kara commented on packages/core/src/render3/styling/styling_parser.ts
> + * Parses the `cssText` into individual key/value tokens.
If you want to keep the more global information here, that works for me. But the headline is objectively incorrect, so we should change it to avoid confusion.

2020-01-06 16:20 UTC, kara commented on packages/core/src/render3/styling/static_styling.ts
> + *    special marker is used to mark where the future insert location should be.
Now it looks like the host styles will end up at the end of the `tNode` string, right? So how are we fixing the order so template styles have priority? The docs in `computeStaticStyles` are gone, so it's not clear how we're intending to use it

2020-01-06 17:58 UTC, mhevery commented on packages/core/src/render3/styling/static_styling.ts
> + *    special marker is used to mark where the future insert location should be.
That is solved in https://github.com/angular/angular/pull/34616/files#diff-5801a869012ab31776274824cc2613d7R1164-R1226

2020-01-08 00:00 UTC, kara approved these changes
LGTM

2020-01-08 00:05 UTC, kara commented
Oh - one thing - looks like the second commit message description should be updated because it says that `computeStaticStyling` is added (and that's been removed)

2020-01-09 05:44 UTC, mhevery commented
> Oh - one thing - looks like the second commit message description should be updated because it says that `computeStaticStyling` is added (and that's been removed)

Opps, that was by accident. I added the missing function back in. PTAL

2020-01-09 15:33 UTC, kara approved these changes
Ah, I thought you moved it into the follow-up styling PR. LGTM.

2020-01-14 05:44 UTC, merged