fix(language-service): Proper completions for properties and events
angular/angular pull request #34445
Opened 2019-12-17 02:13 UTC by kyliau

This commit fixes autocompletions for properties and events bindings.

The language service will no longer provide bindings like (click) or [id].
Instead, it'll infer the context based on the brackets and provide suggestions
without any brackets.

This fix also adds support for alternative binding syntax such as
`bind-`, `on-`, and `bindon`.

PR closes https://github.com/angular/vscode-ng-language-service/issues/398
PR closes https://github.com/angular/vscode-ng-language-service/issues/474

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2019-12-17 02:16 UTC, kyliau commented on packages/language-service/test/completions_spec.ts
> -  describe('property completions for members of an indexed type', () => {
This whole section is moved to the bottom of the test file.

2019-12-17 02:16 UTC, kyliau commented on packages/language-service/src/completions.ts
> +  const bindParts = attr.name.match(BIND_NAME_REGEXP);
One downside of using this regular expression (instead of a proper AST) is that 
```
[()|]
   ^ cursor is here
```
would still provide results for as if the cursor is inside the banana.
I think it's ok for now, because there's actually no such parser in the compiler.
See code in `packages/compiler/src/render3/r3_template_transform.ts`

2019-12-17 02:20 UTC, kyliau commented on packages/language-service/src/completions.ts
> +    // If bindParts is null then this must be a template reference.
Somehow TypeScript is not able to infer that if `isTemplateRef` is true here then `bindParts` in the following else statements must be truthy based on the logic on line 228.

2019-12-17 04:04 UTC, ayazhafiz requested changes

2019-12-17 04:04 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +    // If bindParts is null then this must be a template reference.
I agree; this doesn't seem too much of a worry, as users likely will not be typing in that region.

We do not need to do this now, but wouldn't it be possible to check if the cursor is between a `BoundAttribute` and a `BoundEvent` template node to deduce the location in this case?

2019-12-17 20:09 UTC, kyliau commented on packages/language-service/src/completions.ts
> +    // If bindParts is null then this must be a template reference.
> `bindParts` could still be falsy, because if `templateRef` is truthy and `bindParts` is falsy the branch on 228 will still evaluate to true.

I think this statement is incorrect. Both `templateRef` and `bindParts` must be falsy in order for line 228 to evaluate to true.

Let's make this a little more abstract.
Say I have the following code:
```typescript
const isTemplateRef = attr.name.startsWith('*');
const hasBindParts = bindParts !== null;
const isBinding = isTemplateRef || hasBindParts;
if (!isBinding) {
  return;  // isTemplateRef and hasBindParts are both false
}
// At this point, it is one of three possibilities:
// 1. isTemplateRef = true,  hasBindParts = false
// 2. isTemplateRef = false, hasBindParts = true
// 3. isTemplateRef = true,  hasBindParts = true

if (isTemplateRef) {
  // isTemplateRef must be true
} else {
  // isTemplateRef must be false, and therefore, hasBindParts must be true
}
```

However, if the code is written this way, TypeScript could not deduce that `bindParts` is truthy in the `else` statement. So we have to write 
```typescript
if (!bindParts) {
  // ...
} else {
  // can access bindParts[...] here without the non-null assertion operator
}
```

2019-12-17 20:09 UTC, kyliau commented on packages/language-service/src/completions.ts
> +    // If bindParts is null then this must be a template reference.
Yes, I meant the former. Added a link to the code. Thanks for doign the work to disambiguate the two, they are indeed confusing.

2019-12-17 20:09 UTC, kyliau commented on packages/language-service/src/completions.ts
> +  }
Will make the code more compact for now. I was thinking of making `CompletionKind` more fine-grained, so I left the `kind` there.

2019-12-17 20:09 UTC, kyliau commented on packages/language-service/src/completions.ts
> +  templateRefs: Set<string>;
Done

2019-12-17 20:09 UTC, kyliau commented on packages/language-service/src/utils.ts
> +        identifierName(diDep.token.identifier) === 'TemplateRef')
Done

2019-12-17 20:48 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +}
Ah, makes sense. Thanks!

When you say this will be going away during integration with Ivy, do you mean that the whole idea of these matching groups will be going away, or just the duplication in the Language Service?

2019-12-17 20:58 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +    // If bindParts is null then this must be a template reference.
Sorry; what I meant to say is that 228 will evaluate to false. But yes, my calculation was still incorrect - bindParts has to be true.

2019-12-17 21:01 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +}
Ah, makes sense. Thanks!

When you say this will be going away with the Ivy integration, do you mean the whole idea of matching groups or their duplication in the language service?

2019-12-17 21:13 UTC, ayazhafiz commented on packages/language-service/src/utils.ts
> +        identifierName(diDep.token.identifier) === Identifiers.TemplateRef.name)
`identifierName` can take a null parameter:

https://github.com/angular/angular/blob/6bfe214346b5b7c0e7ede3848c2975a707fbf9ab/packages/compiler/src/compile_metadata.ts#L27

So you can remove the `diDep.token.identifier` check 🙂

2019-12-17 21:13 UTC, ayazhafiz commented on packages/language-service/test/completions_spec.ts
> +    ]);
Can we add tests for custom TemplateRefs? This can be done in another PR if needed.

2019-12-17 21:13 UTC, ayazhafiz commented on packages/language-service/test/completions_spec.ts
> +      expectContain(c6, CompletionKind.ATTRIBUTE, ['outputAlias']);
Considering splitting these into three sets of test cases: input and output bindings, input bindings, output bindings.

2019-12-17 23:29 UTC, kyliau commented on packages/language-service/src/completions.ts
> +}
We'll fix the compiler so that it could provide features needed by the language service.
In this case I'd imagine either changing the compiler to parse AST, or expose the regexes and constants required by the language service.

2019-12-17 23:37 UTC, kyliau commented on packages/language-service/src/utils.ts
> +        identifierName(diDep.token.identifier) === Identifiers.TemplateRef.name)
done.

2019-12-17 23:37 UTC, kyliau commented on packages/language-service/test/completions_spec.ts
> +    ]);
Will do this in another PR. There isn't any existing directives that provide custom `TemplateRef`.

2019-12-17 23:37 UTC, kyliau commented on packages/language-service/test/completions_spec.ts
> +      expectContain(c6, CompletionKind.ATTRIBUTE, ['outputAlias']);
done.

2019-12-18 01:29 UTC, ayazhafiz approved these changes

2019-12-18 02:13 UTC, kyliau commented
caretaker: ci/angular:size got stuck

2019-12-18 17:13 UTC, closed without merging