(submit) event preconditions edit
angular/angular pull request #34467
Opened 2019-12-18 12:50 UTC by skrikl

Current document may confuse the reader by guiding how to emit a (submit) event. There are some other options to consider and one to be aware of (type='button').

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Documentation is possibly misleading
Issue Number: N/A

## What is the new behavior?
Documentation changed

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-12-18 19:48 UTC, kapunahelewong requested changes
Nice update, @skrikl. Thank you. Just some minimal copy edits. Could you also [amend your commit message](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) to something like:

> docs: edit event preconditions in reactive forms doc

The important part is the format of `docs:....` because without it the test fails. Otherwise, almost there. 🌻

2019-12-18 19:48 UTC, kapunahelewong commented on aio/content/guide/reactive-forms.md
> +The `submit` event is emitted by the `form` tag using the native DOM event. You trigger the event by clicking an <input> element with a `submit` type, or a <button> element with a type other than 'bu
Though this was already there, can you edit the first sentence so it's no longer in the passive voice? And can you put `<input>`, `<button>`, and `button` in backticks so they're in code font? Like this:
```suggestion
The `form` tag uses the native DOM event to emit the `submit` event. You trigger the event by clicking an `<input>` element with a `submit` type, or a `<button>` element with a type other than `button`. This also allows the user to press the **Enter** key to submit the completed form.
```

2019-12-20 10:00 UTC, skrikl commented on aio/content/guide/reactive-forms.md
> +The `submit` event is emitted by the `form` tag using the native DOM event. You trigger the event by clicking an <input> element with a `submit` type, or a <button> element with a type other than 'bu
Done, I hope I did it right :)

2019-12-30 19:53 UTC, kapunahelewong commented
Thanks for the additional updates, @skrikl. Requesting @jbogarthyde to review as she may have feedback on style choices, too.

Just as a note for later (that you probably already know), you'll ultimately want everything [squashed](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) into one commit.

2019-12-31 21:53 UTC, jbogarthyde requested changes
A good change. One minor point. 

We generally try standardize on asterisks rather than underscores and hyphens to indicate italics and bullets, but it doesn't really make much difference. No need to change them, but no need to change them back 😃

2019-12-31 21:53 UTC, jbogarthyde commented on aio/content/guide/reactive-forms.md
> +The `form` tag uses the native DOM event to emit the `submit` event. You trigger the event by clicking an `<input>` element with a `submit` type, or a `<button>` element with a type other than `butto
When you say "This allows...", what do you mean by "this"? Is it just the <button> tag?  Please be more specific - perhaps something like "Using a button allows the user..."

2021-02-19 06:15 UTC, AndrewKushnir commented
Closing this PR due to the lack of reply. Please reopen if needed. Thank you.

2021-02-19 06:15 UTC, closed without merging

2021-02-19 06:33 UTC, theBolck commented
skrikl:patch-2