refactor(ivy): move all element attribute creation code into shared class
angular/angular pull request #34475
Opened 2019-12-18 21:13 UTC by matsko

This patch moves all element attribute creation code (e.g. style, class,
binding names, template refs, etc...) into a shared class which is used
by compiler code that creates element and host-binding element
instructions.

2019-12-19 01:28 UTC, alxhub approved these changes

2019-12-19 01:28 UTC, alxhub commented on packages/compiler/src/render3/view/static_attributes_builder.ts
> +    if (!this._keyValueAttrs) {
I generally prefer explicit checks for `null`ness instead of relying on coercion to a boolean value.

2019-12-19 01:29 UTC, alxhub commented on packages/compiler/src/render3/view/static_attributes_builder.ts
> +function populateNameAttributeEntries(attrs: o.Expression[], names: any[]): void {
Can we remove the `any`?

2019-12-19 01:29 UTC, alxhub commented on packages/compiler/src/render3/view/static_attributes_builder.ts
> +function toLiteralArr(values: any[]) {
Same here.

2019-12-19 03:16 UTC, matsko commented
presubmit = https://test.corp.google.com/ui#id=OCL:286311063:BASE:286311085:1576725390254:4c91173d

2019-12-19 19:07 UTC, mhevery reviewed
Minor nit: 1bd70f0812

I defer to @alxhub for final approval as this is a compiler change.

2020-01-06 19:28 UTC, alxhub requested changes

2020-01-06 19:28 UTC, alxhub commented on packages/compiler/src/render3/view/static_attributes_builder.ts
> +function populateNameAttributeEntries(attrs: o.Expression[], names: any[]): void {
I still see `names: any[]` here.

2020-07-09 21:41 UTC, closed without merging