fix(ivy): add attributes and classes to host elements based on selector
angular/angular pull request #34481
Opened 2019-12-19 00:58 UTC by AndrewKushnir

In View Engine, host element of dynamically created component received attributes and classes extracted from component's selector. For example, if component selector is `[attr] .class`, the `attr` attribute and `.class` class will be add to host element. This commit adds similar logic to Ivy, to make sure this behavior is aligned with View Engine.

This PR resolves #34256.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-12-19 00:59 UTC, AndrewKushnir commented
Note: this PR is blocked on PR #34450, since functions that work with selectors (in this PR and in PR #34450) should be combined/refactored.

2020-02-03 23:29 UTC, kara requested changes
Thanks for picking this up! Some thoughts below

2020-02-03 23:29 UTC, kara commented on packages/core/test/acceptance/view_container_ref_spec.ts
> +    it('should apply attributes and classes to host element based on selector', () => {
Add a test with an SVG namespace? :)

2020-02-05 20:53 UTC, AndrewKushnir commented on packages/core/test/acceptance/view_container_ref_spec.ts
> +        selector: '[attr-a=a] .class-a :not(.class-b) :not([attr-b=b]) .class-c [attr-c]',
Thanks for the note, updated component selector.

2020-02-05 20:54 UTC, AndrewKushnir commented on packages/core/src/render3/component.ts
> +    }
Good point, moved this logic outside this function.

2020-02-05 20:55 UTC, AndrewKushnir commented on packages/core/src/render3/node_manipulation.ts
> +export function nativeSetAttribute(
It turned out this logic is not needed, I reused existing `setUpAttributes` function.

2020-02-05 20:56 UTC, AndrewKushnir commented on packages/core/src/render3/component.ts
> +  if (rNode !== null) {
This logic was moved to the function that is used to create components dynamically.

2020-02-05 20:57 UTC, AndrewKushnir commented on packages/core/test/acceptance/view_container_ref_spec.ts
> +    it('should apply attributes and classes to host element based on selector', () => {
This is done as a part of a followup PR (#35136) that handles namespaces for dynamically created components.

2020-02-05 20:58 UTC, AndrewKushnir commented
Thanks for the review @kara. I've updated the code according to the comments/suggestions. Could you please have another look when you get a chance? Thank you.

2020-02-14 12:47 UTC, pkozlowski-opensource commented
@AndrewKushnir in the description of this PR you've referenced issue #34256 but #34256 is closed now (and looks like a bit different issue from what this PR is solving?).

On the other hand it seems like this PR should fix #35445

2020-02-14 18:22 UTC, AndrewKushnir commented
@pkozlowski-opensource issue #34256 was resolved by a different PR (#35136, to fix namespaces issue with dynamically created components). You are right, the problem described in the #35445 should be fixed by the changes in this PR. I've rebased it, waiting for final review from Kara. Thank you.

2020-02-14 23:39 UTC, kara commented on packages/core/src/render3/component_ref.ts
> +      if (hostRNode) {
There are three cases that I know of: 

1) User creates component dynamically with `ViewContainerRef.createComponent` or `ComponentFactory.create` (with no selector).  In this case, we will create the component, so we should be adding appropriate attrs / classes to the new element.

2) App is bootstrapping. `ApplicationRef` will call `ComponentFactory.create` with the selector found in the component factory. Because there's a selector, we will locate the correct host element using the selector. In this case, we should not be adding attrs / classes (if we've located it based on the selector, it already has those attrs/classes, so it's wasted work).

3) User creates a component dynamically using `ComponentFactory.create` and passes in a selector. This selector will be used to locate the host element in which to bootstrap the component. In this case, I think we should also avoid adding attrs / classes. We should treat the passed selector as a replacement for the component's selector and ignore what is in the component selector. Otherwise, we could run into cases where the passed selector and the component def's selector don't match and there's no way to reconcile the two (e.g. if they both have tag selectors like 'my-comp').

In this PR, it looks like we would add the attrs / classes in all 3 cases. At the least, I think we should avoid adding attrs / classes in case 2 (bootstrap). I think it's most correct to also avoid adding attrs in case 3 as well, but that could be considered breaking to VE. What do you think?

2020-02-15 02:56 UTC, AndrewKushnir commented on packages/core/src/render3/component_ref.ts
> +      if (hostRNode) {
Thanks for review @kara!

Your proposal makes a lot of sense.

From `ComponentFactory.create` standpoint we should consider 2 cases:

- when **selector or host node is passed** into the function, which means that host node already exists on a page and we just "insert" our component into it. Since that node was already created (inside or outside of the framework), I think we should not "touch" it and just perform component bootstrap.

- when **selector or host node is not passed** into the function - we create a host node ourselves and in this case it makes sense to add attributes and classes based on selector.

The main motivation for the current implementation was to match VE behavior as closely as possible, but I agree that having different logic based on selector presence makes more sense.

2020-02-18 13:58 UTC, pkozlowski-opensource commented on packages/core/src/render3/component_ref.ts
> +      if (hostRNode) {
I would also argue for only adding attrs for the case (2) [as outlined by Kara](https://github.com/angular/angular/pull/34481#discussion_r379682699).

I think that there reasoning of "we don't touch a host node if we don't create it" is very reasonable.

2020-02-18 18:44 UTC, kara commented on packages/core/src/render3/component_ref.ts
> +      if (hostRNode) {
@pkozlowski-opensource You mean only add attrs in case 1? Case 2 is the bootstrap case.

2020-02-18 18:49 UTC, pkozlowski-opensource commented on packages/core/src/render3/component_ref.ts
> +      if (hostRNode) {
@kara sorry, this is what I've meant... My brain is half half-asleep today. Edited my comment...

2020-02-18 19:03 UTC, AndrewKushnir commented on packages/core/src/render3/component_ref.ts
> +      if (hostRNode) {
@kara and @pkozlowski-opensource thanks for reviewing this PR. I've applied the necessary changes to avoid adding attrs/classes in case selector is provided. Could you please take another look when you get a chance? Thank you.

2020-02-18 19:05 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:295775064:BASE:295775132:1582052711278:7f719618)

2020-02-18 21:32 UTC, kara approved these changes
LGTM

2020-02-18 21:32 UTC, kara commented on packages/core/test/acceptance/view_container_ref_spec.ts
> +        // this selector) retains all atts/classes and selector-based attrs/classes should *not* be
```suggestion
        // this selector) retains all attrs/classes and selector-based attrs/classes should *not* be
```

2020-02-19 01:18 UTC, closed without merging