docs: valuechanges emits on additional events documented
angular/angular pull request #34497
Opened 2019-12-19 17:56 UTC by ajitsinghkaler

The value changes emitted additionally when enable disable were called
documented the above behaviour in AbstractControl class documentaion

Fixes #34407

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #34407 

## What is the new behavior?
Added additional documentation

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-12-19 17:57 UTC, ajitsinghkaler commented
@kapunahelewong can you please review this.

2019-12-20 14:20 UTC, kapunahelewong requested changes
Thanks for this PR, @ajitsinghkaler. Just a couple of copy edit recommendations. 

EDIT: We'll also need to get an engineering approval on this change before merging.

2019-12-20 14:20 UTC, kapunahelewong commented on packages/forms/src/model.ts
> +   * the UI or programmatically. It also emits an event each time enable() or disable() without
```suggestion
   * the UI or programmatically. It also emits an event each time you call enable() or disable() without
```

2019-12-20 14:20 UTC, kapunahelewong commented on packages/forms/src/model.ts
> +   * passing along {emitEvent: false} but events emitted via this way are should be used as little
```suggestion
   * passing along {emitEvent: false}. Use events emitted this way as little
```

2019-12-21 16:50 UTC, ajitsinghkaler commented
@kapunahelewong I've made the changes please have a look

2019-12-23 16:33 UTC, kapunahelewong commented
Thank you, @ajitsinghkaler. It reads very smoothly. As soon as engineering reviews and approves for accuracy we can move forward. Marking for review.

2020-01-20 18:39 UTC, ajitsinghkaler commented
@kapunahelewong Its been nearly a month can we get this reviewed

2020-01-21 18:59 UTC, kapunahelewong commented
Hi @ajitsinghkaler, thanks for your patience. I reached out to my team lead to help us out. I'll let you know what I find.

2020-01-21 19:20 UTC, AndrewKushnir requested changes
Hi @ajitsinghkaler, thanks for creating this PR. I'd propose to remove the `Use events emitted this way as little as possible.` part. Emitting a value is a part of the logic, which can be controlled via a flag (as you mentioned in this PR) and developers may want/need to use it in certain cases.

2020-01-21 19:20 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +   * without passing along {emitEvent: false}. Use events emitted this way as little as possible.
```suggestion
   * without passing along {emitEvent: false} as a function argument.
```

2020-01-21 19:22 UTC, aikidave commented on packages/forms/src/model.ts
> +   * without passing along {emitEvent: false}. Use events emitted this way as little as possible.
Just thought I'd chime in to say that I agree with Andrew's comment, as I was just about to make a similar one. :)

2020-01-22 17:15 UTC, AndrewKushnir approved these changes
Thanks for the updates @ajitsinghkaler.

2020-01-22 19:22 UTC, ajitsinghkaler commented
@kapunahelewong can you also approve and put it in merge

2020-01-23 21:54 UTC, kapunahelewong approved these changes

2020-01-23 21:57 UTC, closed without merging