feat: support passive events by define global variables in zone.js config file
angular/angular pull request #34503
Opened 2019-12-19 22:59 UTC by JiaLiPassion

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #8866

It is not easy to `addEventListener` with `passive` option. We may need to discuss to add something like in this PR, https://github.com/angular/angular/pull/21681 in the future.

## What is the new behavior?
For now, this PR is just a temp solution until we can add a new `template syntax` in `event listener`.
In this PR, we can define a global variable before importing zone.js

```
(window as any)['__zone_symbol__PASSIVE_EVENTS'] = ['touchstart', 'scroll'];
```

and then all event listeners defined here will be automatically be `passive: true`.
## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2019-12-20 01:58 UTC, JiaLiPassion commented
@mhevery, please check whether this temp solution is ok, thank you!

2020-01-29 22:59 UTC, mhevery requested changes

2020-01-29 22:59 UTC, mhevery commented on packages/zone.js/test/browser/browser.spec.ts
> +          logs.push(e.defaultPrevented.toString());
Instead of pushing `true`/`false` which is hard to understand in the assertion, could we push text
```suggestion
          logs.push(e.defaultPrevented ? 'defaultPrevented' : 'default will run');
```

2020-01-29 22:59 UTC, mhevery commented on packages/zone.js/lib/common/events.ts
> +          for (let i = 0; i < passiveEvents.length; i++) {
why not just use `passiveEvents.indexOf(...)`?

2020-01-29 22:59 UTC, mhevery commented on packages/zone.js/lib/common/events.ts
> +    function buildPassiveOptions(options: any, passive: boolean) {
Could we add some documentation on this method. What is its purpose? why do we need it?

2020-01-29 22:59 UTC, mhevery commented on packages/zone.js/lib/common/events.ts
> +              if (!passive) {
can you flip `!passive` to `passive` and just flip the `else` branch?

2020-01-29 23:00 UTC, mhevery commented
Looks like a reasonable approach.

2020-01-30 02:20 UTC, JiaLiPassion commented on packages/zone.js/test/browser/browser.spec.ts
> +          logs.push(e.defaultPrevented.toString());
Yeah, this is better, updated.

2020-01-30 02:29 UTC, JiaLiPassion commented on packages/zone.js/lib/common/events.ts
> +          for (let i = 0; i < passiveEvents.length; i++) {
Yeah, you are right, updated. Thanks.

2020-01-30 02:34 UTC, JiaLiPassion commented on packages/zone.js/lib/common/events.ts
> +    function buildPassiveOptions(options: any, passive: boolean) {
Sure, this method is to build an `option object` to handle all possible inputs. doc added, thanks.

2020-01-30 02:36 UTC, JiaLiPassion commented on packages/zone.js/lib/common/events.ts
> +              if (!passive) {
Yeah, that will be natural. Thanks.

2020-01-30 04:33 UTC, JiaLiPassion commented
@mhevery, thanks for the review, I have updated the PR and add the document.

2020-01-31 20:01 UTC, mhevery requested changes

2020-01-31 20:01 UTC, mhevery commented on packages/zone.js/test/browser/browser.spec.ts
> +           () => { testPassive('touchstart', true, {passive: true}); });
also change `true`/`false` in these tests methods to the actual string. It will read much better.

2020-01-31 20:01 UTC, mhevery commented on integration/_payload-limits.json
> +        "main-es2015": 141476,
Why are these getting bigger?

2020-01-31 20:01 UTC, mhevery commented on packages/zone.js/test/browser/browser.spec.ts
> +            (document as any).removeAllListeners('scroll');
Why do we have to cast this to `any`?

2020-02-05 04:47 UTC, JiaLiPassion commented on packages/zone.js/lib/common/events.ts
> +    // this util function will build an option object with passive option
Got it, updated, thanks!

2020-02-05 12:40 UTC, JiaLiPassion commented on packages/zone.js/test/browser/browser.spec.ts
> +           () => { testPassive('touchstart', true, {passive: true}); });
Got it, thanks.

2020-02-05 12:44 UTC, JiaLiPassion commented on integration/_payload-limits.json
> +        "main-es2015": 141476,
I have checked the diff between the old and new dist bundles, the differences are exactly the source added to handle passive in this PR, such as this `buildPassiveOptions` function.

2020-02-05 12:44 UTC, JiaLiPassion commented on packages/zone.js/test/browser/browser.spec.ts
> +            (document as any).removeAllListeners('scroll');
Because `removeAllListeners` are the API added by `zone.js`, it is not a standard API.

2020-02-05 19:02 UTC, mhevery commented on packages/zone.js/test/browser/browser.spec.ts
> +            (document as any).removeAllListeners('scroll');
Could we create an interface such as 
```
interface ZoneDocumentExtensions {
  /** Docs here */
  removeAllListeners(name: string): void;
}
```

That way it would be clear which methods we are adding and what their docs are? We could than publish these interfaces.

2020-02-05 19:02 UTC, mhevery commented on packages/zone.js/test/browser/browser.spec.ts
> +            (document as any).removeAllListeners('scroll');
(I am OK if you want to do this in followup PR)

2020-02-05 21:50 UTC, JiaLiPassion commented on packages/zone.js/test/browser/browser.spec.ts
> +            (document as any).removeAllListeners('scroll');
Yeah, sure, this is a good idea, there are several other APIs zone.js added, I will create another PR to add it, thanks.

2020-02-11 17:57 UTC, mhevery approved these changes

2020-02-11 18:00 UTC, mhevery commented
[presubmit](http://test/OCL:294461424:BASE:294461465:1581443932965:253ce40f)

2020-02-17 06:01 UTC, JiaLiPassion commented
@kara, I have rebased the PR, please review, thanks.

2020-02-20 19:21 UTC, mhevery commented
[presubmit](http://test/OCL:294461424:BASE:296256105:1582226487454:ca5d889e)

2020-02-21 21:37 UTC, kara reviewed
Can we also add a descriptive commit message that explains why this change is necessary?

2020-02-21 21:37 UTC, kara commented on aio/content/guide/user-input.md
> +Angular also support passive event listeners. For example, we can use the following steps to make scroll event passive.
support => supports

```
Angular also supports passive event listeners. 
```

2020-02-21 21:37 UTC, kara commented on aio/content/guide/user-input.md
> +1. create a file `src/zone-flags.ts`.
create -> Create

Can we capitalize all first words of sentences in this new section?

2020-02-21 21:37 UTC, kara commented on aio/content/guide/user-input.md
> +3. in `src/polyfills.ts`, before import zone.js, import the new created `zone-flags`.
before import zone.js => before importing zone.js

2020-02-21 21:37 UTC, kara commented on aio/content/guide/user-input.md
> +after those steps, if user add event listeners for the `passive` event, the listeners will be `passive`.
if user add event listeners => if user adds event listeners

2020-02-21 21:37 UTC, kara commented on integration/_payload-limits.json
> +        "polyfills-es2015": 37300
This is a somewhat large increase. Do we know why? Can we find out how much is just accumulation?

2020-02-21 21:43 UTC, IgorMinar commented on integration/_payload-limits.json
> +        "polyfills-es2015": 37300
I agree, this seems excessive especially for the diff in this PR. Let's find out how did we accumulate this much (I've reset the polyfills limits recently so it seems like a recent accumulation of code)

2020-02-21 22:13 UTC, mhevery commented
This was accidentally merged. Reverting until we have better review.

2020-02-22 01:48 UTC, JiaLiPassion commented on aio/content/guide/user-input.md
> +Angular also support passive event listeners. For example, we can use the following steps to make scroll event passive.
Got it, updated, thanks.

2020-02-22 01:50 UTC, JiaLiPassion commented on aio/content/guide/user-input.md
> +1. create a file `src/zone-flags.ts`.
Got it, updated, thanks.

2020-02-22 01:50 UTC, JiaLiPassion commented on aio/content/guide/user-input.md
> +3. in `src/polyfills.ts`, before import zone.js, import the new created `zone-flags`.
Got it, updated, thanks.

2020-02-22 06:29 UTC, JiaLiPassion commented
@kara, @mhevery , I have updated the doc and remove some unused code. Now the size will have no changes. Please review, thanks.

2020-02-24 22:00 UTC, mhevery commented
[presubmit](http://test/OCL:294461424:BASE:296967878:1582581629409:8e2a6409)

2020-02-24 22:51 UTC, kara requested changes
Thanks for updating the PR! There are still a few things to do:

1) Update the commit message to describe what problem this PR is fixing and why (should not just be one sentence).

2) A few more docs updates below to fix

2020-02-24 22:51 UTC, kara commented on aio/content/guide/user-input.md
> +Angular also supports passive event listeners. For example, you can use the following steps to make scroll event passive.
```suggestion
Angular also supports passive event listeners. For example, you can use the following steps to make the scroll event passive.
```

2020-02-24 22:51 UTC, kara commented on aio/content/guide/user-input.md
> +3. In the `src/polyfills.ts` file, before importing zone.js, import the new created `zone-flags`.
```suggestion
3. In the `src/polyfills.ts` file, before importing zone.js, import the newly created `zone-flags`.
```

2020-02-25 00:50 UTC, JiaLiPassion commented on aio/content/guide/user-input.md
> +Angular also supports passive event listeners. For example, you can use the following steps to make scroll event passive.
Got it, thanks, updated.

2020-02-25 00:50 UTC, JiaLiPassion commented on aio/content/guide/user-input.md
> +3. In the `src/polyfills.ts` file, before importing zone.js, import the new created `zone-flags`.
Got it, updated, thanks.

2020-02-25 00:55 UTC, JiaLiPassion commented
@kara, thank you for the review, I have updated the doc and the commit message. Please review.

2020-02-25 00:57 UTC, kara approved these changes
LGTM, thanks for updating the PR @JiaLiPassion!

2020-02-25 01:30 UTC, closed without merging

2020-03-04 13:43 UTC, sod commented
What's the release schedule for zone.js? I ask as I saw quite some changes over time, but the last release was 8 months ago (0.10.2 from August 14, 2019 - https://yarnpkg.com/package/zone.js)

2020-03-05 06:50 UTC, JiaLiPassion commented
@sod, there should be a new version very soon.