Tests for observables
angular/angular pull request #34537
Opened 2019-12-22 23:27 UTC by sonukapoor

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #34398

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2019-12-23 08:15 UTC, gkalpak commented
Marking this as blocked on #34327, since it builds on top of that.

2020-01-22 01:52 UTC, sonukapoor commented
> Marking this as blocked on #34327, since it builds on top of that.

@gkalpak This is unblocked now since #34327 has been merged. Can you review it please?

2020-01-22 12:02 UTC, gkalpak requested changes
Thx, @sonukapoor ❤️
I've left some comments. Also, the current commit message ("tests for observables and promises") is too generic. Can you, please, change it to be more specific. E.g. something like:

> test(docs-infra): add tests for \`comparing-observables\` example

2020-01-23 17:42 UTC, gkalpak commented
I, also, just realized that we need to make sure the tests are run on CI (currently they are not afaict) :grin:

2020-01-24 18:56 UTC, mary-poppins commented
You can preview 583ad7f at https://pr34537-583ad7f.ngbuilds.io/.
You can preview aa9a17b at https://pr34537-aa9a17b.ngbuilds.io/.

2020-01-25 11:27 UTC, gkalpak requested changes
Just few more (minor) comments to go :smiley:

Also, as mentioned in https://github.com/angular/angular/pull/34537#issuecomment-577790886, we need to run these tests on CI. This is similar to what you did for other Observables-related examples in #34063. I.e. you need to:

- Add a dummy `e2e/src/app.e2e-spec.ts` (e.g. similar to [observables/e2e/src/app.e2e-spec.ts][1]).
- Add an appropriate `example-config.json` (e.g. similar to [observables/example-config.json][2] but specifying a different command that actually runs the unit tests).

[1]: https://github.com/sonukapoor/angular/blob/e0ad9ecda0b8a541b405d2ab35335b90ceb21fd1/aio/content/examples/observables/e2e/src/app.e2e-spec.ts
[2]: https://github.com/sonukapoor/angular/blob/e0ad9ecda0b8a541b405d2ab35335b90ceb21fd1/aio/content/examples/observables/example-config.json

2020-01-25 20:04 UTC, sonukapoor commented
> Just few more (minor) comments to go 😃
> 
> Also, as mentioned in [#34537 (comment)](https://github.com/angular/angular/pull/34537#issuecomment-577790886), we need to run these tests on CI. This is similar to what you did for other Observables-related examples in #34063. I.e. you need to:
> 
> * Add a dummy `e2e/src/app.e2e-spec.ts` (e.g. similar to [observables/e2e/src/app.e2e-spec.ts](https://github.com/sonukapoor/angular/blob/e0ad9ecda0b8a541b405d2ab35335b90ceb21fd1/aio/content/examples/observables/e2e/src/app.e2e-spec.ts)).
> * Add an appropriate `example-config.json` (e.g. similar to [observables/example-config.json](https://github.com/sonukapoor/angular/blob/e0ad9ecda0b8a541b405d2ab35335b90ceb21fd1/aio/content/examples/observables/example-config.json) but specifying a different command that actually runs the unit tests).

Yes, I haven't gotten to that yet. I wanted to make sure that we are happy with the codebase now. I should be able to look into the testing from CI next.

2020-01-25 22:58 UTC, mary-poppins commented
You can preview d902c0d at https://pr34537-d902c0d.ngbuilds.io/.

2020-01-25 23:08 UTC, mary-poppins commented
You can preview b5767ea at https://pr34537-b5767ea.ngbuilds.io/.

2020-01-25 23:43 UTC, mary-poppins commented
You can preview ddfb0fc at https://pr34537-ddfb0fc.ngbuilds.io/.

2020-01-26 00:24 UTC, mary-poppins commented
You can preview a5231d7 at https://pr34537-a5231d7.ngbuilds.io/.

2020-01-26 00:50 UTC, mary-poppins commented
You can preview d2bd1cc at https://pr34537-d2bd1cc.ngbuilds.io/.

2020-01-26 01:46 UTC, mary-poppins commented
You can preview 98a1e73 at https://pr34537-98a1e73.ngbuilds.io/.

2020-01-26 02:00 UTC, mary-poppins commented
You can preview f8e9e85 at https://pr34537-f8e9e85.ngbuilds.io/.

2020-01-26 15:36 UTC, mary-poppins commented
You can preview 0c90f43 at https://pr34537-0c90f43.ngbuilds.io/.

2020-01-26 20:51 UTC, mary-poppins commented
You can preview a5c3bb7 at https://pr34537-a5c3bb7.ngbuilds.io/.

2020-01-26 21:03 UTC, mary-poppins commented
You can preview 19d6b3b at https://pr34537-19d6b3b.ngbuilds.io/.

2020-01-28 11:52 UTC, sonukapoor commented
@gkalpak can you review the changes? I have my doubts with the tests. Please see my offline comments.

2020-01-29 01:18 UTC, mary-poppins commented
You can preview 8c74ce7 at https://pr34537-8c74ce7.ngbuilds.io/.

2020-01-29 01:51 UTC, mary-poppins commented
You can preview ff3b05c at https://pr34537-ff3b05c.ngbuilds.io/.

2020-01-29 02:09 UTC, mary-poppins commented
You can preview 66e82fd at https://pr34537-66e82fd.ngbuilds.io/.

2020-01-29 02:26 UTC, mary-poppins commented
You can preview 958cfbb at https://pr34537-958cfbb.ngbuilds.io/.

2020-01-29 02:53 UTC, mary-poppins commented
You can preview f481b50 at https://pr34537-f481b50.ngbuilds.io/.

2020-01-29 03:09 UTC, mary-poppins commented
You can preview 8dd3508 at https://pr34537-8dd3508.ngbuilds.io/.

2020-01-29 03:31 UTC, mary-poppins commented
You can preview a42e11f at https://pr34537-a42e11f.ngbuilds.io/.

2020-02-01 22:00 UTC, mary-poppins commented
You can preview f686921 at https://pr34537-f686921.ngbuilds.io/.

2020-02-01 22:11 UTC, mary-poppins commented
You can preview 8be1f4a at https://pr34537-8be1f4a.ngbuilds.io/.

2020-02-01 22:22 UTC, mary-poppins commented
You can preview 6bd0beb at https://pr34537-6bd0beb.ngbuilds.io/.

2020-02-01 22:30 UTC, mary-poppins commented
You can preview 1a9cb83 at https://pr34537-1a9cb83.ngbuilds.io/.

2020-02-02 00:20 UTC, mary-poppins commented
You can preview 188f002 at https://pr34537-188f002.ngbuilds.io/.

2020-02-02 00:30 UTC, mary-poppins commented
You can preview da228c3 at https://pr34537-da228c3.ngbuilds.io/.

2020-02-02 04:42 UTC, mary-poppins commented
You can preview ca6f557 at https://pr34537-ca6f557.ngbuilds.io/.

2020-02-02 04:55 UTC, mary-poppins commented
You can preview f54befb at https://pr34537-f54befb.ngbuilds.io/.

2020-02-02 20:48 UTC, mary-poppins commented
You can preview d9391c2 at https://pr34537-d9391c2.ngbuilds.io/.

2020-02-02 20:59 UTC, mary-poppins commented
You can preview f22a749 at https://pr34537-f22a749.ngbuilds.io/.

2020-02-02 21:02 UTC, sonukapoor commented
@gkalpak I have fixed all issues you have mentioned, except I am not able to run the tests in the CI environment. I have tried everything I could. Here are the changes I did:

- Added a `tsconfig-custom.app.json`, to transpile the spec files into the `out-tsc` folder. 
- I was able to see that the files are generated fine by temporarily adding a `js` file that prints out the contents of that folder. 
- I also added a `jasmine.json` file as config for `jasmine`. 

Besides doing all of this, I do not see the same output as I get locally, which is showing the results of the tests. Instead, all I can see is:

> running: node jasmine --config=content/examples/comparing-observables/jasmine.json
> completed: node jasmine --config=content/examples/comparing-observables/jasmine.json

Any help is appreciated.

2020-02-17 22:19 UTC, mary-poppins commented
You can preview 98e9ff4 at https://pr34537-98e9ff4.ngbuilds.io/.

2020-02-17 22:42 UTC, mary-poppins commented
You can preview a12fd79 at https://pr34537-a12fd79.ngbuilds.io/.

2020-02-17 22:50 UTC, mary-poppins commented
You can preview 05306e8 at https://pr34537-05306e8.ngbuilds.io/.

2020-02-17 23:07 UTC, mary-poppins commented
You can preview e167220 at https://pr34537-e167220.ngbuilds.io/.

2020-02-17 23:37 UTC, mary-poppins commented
You can preview d9cf686 at https://pr34537-d9cf686.ngbuilds.io/.

2020-02-17 23:47 UTC, mary-poppins commented
You can preview e956b8c at https://pr34537-e956b8c.ngbuilds.io/.

2020-02-17 23:58 UTC, mary-poppins commented
You can preview f4491cf at https://pr34537-f4491cf.ngbuilds.io/.

2020-02-18 00:22 UTC, mary-poppins commented
You can preview f040332 at https://pr34537-f040332.ngbuilds.io/.

2020-02-18 00:34 UTC, mary-poppins commented
You can preview 9a96eb2 at https://pr34537-9a96eb2.ngbuilds.io/.

2020-02-18 01:49 UTC, mary-poppins commented
You can preview 462e8b8 at https://pr34537-462e8b8.ngbuilds.io/.

2020-02-18 02:15 UTC, mary-poppins commented
You can preview 8ab4fe6 at https://pr34537-8ab4fe6.ngbuilds.io/.

2020-02-18 02:28 UTC, sonukapoor commented
@gkalpak I was able to run the unit tests in the `CI` environment. I believe this completes everything. Can you please review this one more time? 

![image](https://user-images.githubusercontent.com/59734/74697187-e32de900-51c7-11ea-9c31-711dac2435d0.png)

2020-07-21 15:40 UTC, sonukapoor commented
Blocked by https://github.com/angular/angular/pull/38143

2020-08-13 21:34 UTC, mary-poppins commented
You can preview 490eec2 at https://pr34537-490eec2.ngbuilds.io/.

2020-08-14 12:08 UTC, mary-poppins commented
You can preview 9f71b16 at https://pr34537-9f71b16.ngbuilds.io/.

2020-08-14 12:30 UTC, mary-poppins commented
You can preview 418e36f at https://pr34537-418e36f.ngbuilds.io/.

2020-08-14 12:46 UTC, mary-poppins commented
You can preview 23959b7 at https://pr34537-23959b7.ngbuilds.io/.

2020-08-22 09:25 UTC, gkalpak requested changes
The tests look fine (with some minor comments). Thx for sorting this out.
I am not a big fan of the current setup. I'll look into whether it is possible to simplify it a bit.

2020-08-24 13:20 UTC, gkalpak commented on aio/content/examples/comparing-observables/src/promises.ts
> +  // #enddocregion chain
I just realized that in order for this to be testable, we need to refactor the code a bit (and also use the "trick" from `docRegionError()` below).

```suggestion
  let promise = new Promise<number>((resolve, reject) => {
    // Executer fn...
    // #enddocregion promise
    // The below is used in the unit tests.
    resolve(2);
    // #docregion promise
  });

  // #enddocregion promise
  promise =
  // #docregion chain

  promise.then(v => 2 * v);

  // #enddocregion chain
  promise =
  // docregion promise
  promise.then(value => {
    // handle result here
    // #enddocregion promise
    // The below is used in the unit tests.
    console.log(value);
    // #docregion promise
  });

  // #enddocregion promise
  return promise;
```

[1]: https://github.com/angular/angular/blob/82d200a26f363f564a1f743bac92aa132638c7b3/aio/content/examples/comparing-observables/src/promises.ts#L33-L39

2020-08-24 13:44 UTC, sonukapoor commented on aio/content/examples/comparing-observables/src/promises.ts
> +  // #enddocregion chain
I guess at line 28, we need to return `value` as well, otherwise, the test will not pass, right?

2020-08-24 13:50 UTC, gkalpak commented on aio/content/examples/comparing-observables/src/promises.ts
> +  // #enddocregion chain
I have reordered the `then()` calls, so you can now assert that `console.log()` is called with `4` (i.e. the transformed value). You can also update the `docRegion...` function to accept the value to resolve the initial promise with.

2020-08-24 15:08 UTC, mary-poppins commented
You can preview d84dcc1 at https://pr34537-d84dcc1.ngbuilds.io/.

2020-08-24 15:51 UTC, mary-poppins commented
You can preview d4da011 at https://pr34537-d4da011.ngbuilds.io/.

2020-08-24 16:10 UTC, gkalpak requested changes

2020-08-24 16:10 UTC, gkalpak commented on aio/content/examples/comparing-observables/src/promises.ts
> +    return value;
Since you are returning the value here, there is little point in moving the `chain docregion above the `console.log()` block. Let's keep it below the `console.log()` block to avoid interleaving docregions.

2020-08-26 10:08 UTC, mary-poppins commented
You can preview 157a0f8 at https://pr34537-157a0f8.ngbuilds.io/.

2020-08-27 12:01 UTC, gkalpak requested changes
The changes lgtm. Thx for the patience while we were figuring things out, @sonukapoor :grin: :100:

One last thing:
The `docs(docs-infra)` commit message looks wrong. It should either be squashed into the first commit or it should be a `test(docs-infra)` commit.

2020-08-27 12:12 UTC, sonukapoor commented
> The changes lgtm. Thx for the patience while we were figuring things out, @sonukapoor 😁 💯

No worries @gkalpak 

> One last thing:
> The `docs(docs-infra)` commit message looks wrong. It should either be squashed into the first commit or it should be a `test(docs-infra)` commit.

I have changed this squashed them. Please review one last time. Thanks

2020-08-27 12:19 UTC, mary-poppins commented
You can preview f3bd82e at https://pr34537-f3bd82e.ngbuilds.io/.

2020-08-27 12:36 UTC, mary-poppins commented
You can preview c265a4f at https://pr34537-c265a4f.ngbuilds.io/.

2020-08-27 14:25 UTC, gkalpak requested changes

2020-08-27 14:25 UTC, gkalpak commented on aio/content/examples/comparing-observables/src/promises.spec.ts
> +      expect(value).toHaveBeenCalledWith(4);
You seem to have accidentally changed this while shifting commits around:

```suggestion
      expect(value).toBe(4);
```

2020-08-27 14:29 UTC, mary-poppins commented
You can preview e25f686 at https://pr34537-e25f686.ngbuilds.io/.

2020-08-27 14:31 UTC, sonukapoor commented on aio/content/examples/comparing-observables/src/promises.spec.ts
> +      expect(value).toHaveBeenCalledWith(4);
Sorry about that. I think it should be fixed now.

2020-08-27 14:42 UTC, mary-poppins commented
You can preview ec9406f at https://pr34537-ec9406f.ngbuilds.io/.

2020-08-27 15:28 UTC, gkalpak approved these changes
Nice job, @sonukapoor! Thx :+1:

Reviewed-for: global-docs-approvers

2020-08-27 16:06 UTC, closed without merging