feat(language-service): support completions for animation
angular/angular pull request #34597
Opened 2019-12-30 03:35 UTC by ivanwonder

Support completions for animation.
https://angular.io/guide/animations
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2019-12-30 03:36 UTC, ivanwonder commented
I don't know if it's already prepared for review. Maybe I should wait until the completion support the full binding syntax (e.g. `<button [style.font-size.em]="isSpecial ? 3 : 1" >Big</button>`).
https://angular.io/guide/template-syntax#binding-types-and-targets

2019-12-30 03:37 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +}
I don't find the right parser for it.

2020-01-01 02:33 UTC, ayazhafiz commented
Happy New Year, @ivanwonder. I will do my best to submit a review in the next day.

2020-01-01 03:53 UTC, ivanwonder commented
> Happy New Year, @ivanwonder. I will do my best to submit a review in the next day.

Happy New Year. 🎉

2020-01-03 15:34 UTC, ayazhafiz requested changes

2020-01-03 15:34 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +//           ^---- cursor, return 1.
Why does this return 1? Is it returning the cursor position in the nearest AST node? In either case, why not just take the difference between the template position and the start of the AST instead of this function?

2020-01-03 15:34 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +function completionForAnimation(
```suggestion
function animationCompletions(
```

2020-01-03 15:34 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +  namePosition += animationPrefixLength;
I think it would be better if the name was just chopped off properly so the beginning of the name was at index 0 without also keeping track of a `namePosition`.

2020-01-03 15:34 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +function completionForAnimationTrigger(info: AstResult): string[] {
```suggestion
function animationTriggerCompletions(info: AstResult): string[] {
```

2020-01-03 15:34 UTC, ayazhafiz commented on packages/language-service/test/project/app/animations-case.ts
> +}
Please place this inline in the test via `mockHost.override`. We will eventually move away from tests in `project/app`.

2020-01-04 01:47 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +const ANIMATE_PROP_PREFIX = 'animate-';
https://github.com/angular/angular/blob/9b9116c79d626b6356f3dfe0d48c9d990ac412a2/packages/compiler/src/template_parser/binding_parser.ts#L202

2020-01-04 02:08 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +//           ^---- cursor, return 1.
```
<div (@openClose.done)="onAnimationEvent($event)"></div>
```
this is an example of `ast` of  ElementAst's `outputs` for the template above.
```
0: BoundEventAst
name: "openClose"
target: null
phase: "done"
handler: ASTWithSource {span: ParseSpan, sourceSpan: AbsoluteSourceSpan, ast: MethodCall, source: "onAnimationEvent($event)", location: "/app/animations-case.ts@4:25", …}
sourceSpan: ParseSourceSpan {start: ParseLocation, end: ParseLocation, details: null}
handlerSpan: ParseSourceSpan {start: ParseLocation, end: ParseLocation, details: null}
fullName: "@openClose.done"
isAnimation: true
```
I need to know where the user is, in the name `openClose` or phase `done`. So I return 1 which represent the phasse, 0 represent name. 
BTW, there is no `ast` output for template `<div (@openClose.done)></div>`

2020-01-04 02:18 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +  namePosition += animationPrefixLength;
But the better place to achieve this is here
https://github.com/angular/angular/blob/0f7c08ae08f6478e591aaff06ba3c52f5f9e76c1/packages/language-service/src/completions.ts#L236
the different condition has different `namePosition`.
https://github.com/angular/angular/blob/0f7c08ae08f6478e591aaff06ba3c52f5f9e76c1/packages/language-service/src/completions.ts#L266
For `on-` it should be `offset + 3`, for `()`, it should be `offset + 1` (there is a bug for my code here, I will fix it ).

2020-01-04 02:24 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +  namePosition += animationPrefixLength;
I think for the binding type like  `<button [style.font-size.em]="isSpecial ? 3 : 1" >Big</button>` the name is chopped off properly

2020-01-06 00:03 UTC, ayazhafiz requested changes

2020-01-06 00:03 UTC, ayazhafiz commented on packages/language-service/test/project/app/parsing-cases.ts
> +@Component({templateUrl: 'test.ng', animations: [trigger('openClose')]})
```suggestion
@Component({templateUrl: 'test.ng', animations: [trigger('openClose')],})
```

nit: just to make easier to read ))

2020-01-06 00:26 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +const ANIMATE_PROP_PREFIX = 'animate-';
Wow, we should add some public documentation for this. It is only used in one test in the whole monorepo, and only with `bind-`.

2020-01-06 00:26 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +const SECOND_ANIMATE_PROP_PREFIX = '@';
Consider semantic renaming, maybe something like `AT_ANIMATE_PROP_PREFIX`, or putting both prefixes in an array and then when you have to use them in something like

```typescript
// https://github.com/angular/angular/pull/34597/files#diff-124f548ae63f6d523acad1f921efecbeR336-R341
if (name.startsWith(ANIMATE_PROP_PREFIX)) {
  animationPrefixLength = ANIMATE_PROP_PREFIX.length;
}
if (name.startsWith(SECOND_ANIMATE_PROP_PREFIX)) {
  animationPrefixLength = SECOND_ANIMATE_PROP_PREFIX.length;
}
```

refactoring as something like

```typescript
const ANIMATE_PREFIXES = ['animate-', '@'];
/// ...
const prefix = ANIMATE_PREFIXES.find(pre => name.startsWith(pre));
const animationPrefixLength = prefix ? prefix.length : 0;
```

2020-01-06 01:21 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +        ngAttrs));
Before you can use `bindParts[ATTR.KW_IDENT_IDX]`, for example, firstly, get the value from `bindParts[ATTR.IDENT_EVENT_IDX]`. then `bindParts[ATTR.IDENT_EVENT_IDX].math(BIND_NAME_REGEXP)`.
The value of `bindParts[ATTR.KW_IDENT_IDX]` is undefined at the first name match.

2020-01-06 01:26 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +        ngAttrs));
Yes, sorry. For matches on groups 1-6, you can use `ATTR.KW_IDENT_IDX`. Otherwise, you must fallback on groups 8/9/10.

2020-01-06 01:53 UTC, ivanwonder commented
https://github.com/angular/angular/blob/9b9116c79d626b6356f3dfe0d48c9d990ac412a2/packages/compiler/src/template_parser/binding_parser.ts#L202
https://github.com/angular/angular/blob/9b9116c79d626b6356f3dfe0d48c9d990ac412a2/packages/compiler/src/template_parser/binding_parser.ts#L343
I don't know if it's a mistake or a feat. When parse the event binding, it only supports `@` prefix.

2020-01-06 02:20 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +//           ^---- cursor, return 1.
> Why not substring the name at the template position and check that if contains a . to see if we are in the name or the phase? Bounds checking are not necessary because they have already been handled when we determined that we were in an event binding AST. This would also reduce the function to a one-line flag.

What I think here is when the cursor is in `bind-`, no need to provide completions.
https://github.com/angular/angular/blob/9b9116c79d626b6356f3dfe0d48c9d990ac412a2/packages/language-service/src/completions.ts#L228
Maybe you are right, it should not be checked here.

2020-01-06 04:34 UTC, ayazhafiz commented
> don't know if it's a mistake or a feat. When parse the event binding, it only supports `@` prefix.

Yeah, I noticed the same thing. I'm not sure if this intentional or not. @alxhub @JoostK can you provide some insight? Seems that animation bindings can be specified with the `@` or `animate-` prefix, but `animate-` only works in property bindings (and I can't seem to find any public documentation on it).

2020-01-07 03:28 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +
This code copy from here and remove some useless property
https://github.com/angular/angular/blob/9b9116c79d626b6356f3dfe0d48c9d990ac412a2/packages/compiler/src/template_parser/template_ast.ts#L111
https://github.com/angular/angular/blob/9b9116c79d626b6356f3dfe0d48c9d990ac412a2/packages/compiler/src/template_parser/template_ast.ts#L86

2020-01-07 03:32 UTC, ivanwonder commented
> > don't know if it's a mistake or a feat. When parse the event binding, it only supports `@` prefix.
> 
> Yeah, I noticed the same thing. I'm not sure if this intentional or not. @alxhub @JoostK can you provide some insight? Seems that animation bindings can be specified with the `@` or `animate-` prefix, but `animate-` only works in property bindings (and I can't seem to find any public documentation on it).

Maybe we should open an issue for it.

2020-01-07 08:32 UTC, JoostK commented
> can you provide some insight? Seems that animation bindings can be specified with the `@` or `animate-` prefix, but `animate-` only works in property bindings (and I can't seem to find any public documentation on it).

@ayazhafiz I have literally no clue about how this is supposed to be.

2020-01-08 03:06 UTC, ayazhafiz requested changes
Hi @ivanwonder, sorry for the delay. I have recently started a new job and been busy with the move and such. I will make an effort to be more active. I hope we can get this PR in soon. Keen should be back soon for a second pair of eyes as well.

2020-01-08 03:06 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +    return ANIMATION_PHASES;
nit: consider removing the constant entirely in this case

2020-01-08 03:06 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +    return SPECIAL_ANIMATION_CONTROL;
nit: consider removing the constant entirely in this case, and adding the comment on 331-332 inside the if branch.

2020-01-08 03:06 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +  if (isInAnimationPhase(bound, templatePosition)) {
if we're not in the animation name, we have to be in the animation phase right? If so, I think we should remove the functions and `isIn...` function and perform the check in this function.

2020-01-08 03:06 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +}
I don't think we should duplicate the job of the parser in the language service, especially since this could be done by creating and using a binding parser. Were you unable to extract the event/binding name using `KW_IDENT_IDX` and friends?

2020-01-08 03:07 UTC, ayazhafiz commented
> Maybe we should open an issue for it.

Agreed!

2020-01-08 03:41 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +
For me, create a new one is simple and readable.
One way to get it is to visit the `TemplateAst`(now the code use HtmlAst), but it has a problem as the reference ASTs in my earlier PR.(this way is better, but still need to create the `BoundEventAst ` when encountering an error).
If I just use the exported classes, I need to create `public handler: AST` for it, and `this.isAnimation = !!this.phase;` the `phase` maybe null or an empty string.
https://github.com/angular/angular/blob/9b9116c79d626b6356f3dfe0d48c9d990ac412a2/packages/compiler/src/template_parser/template_ast.ts#L115-L212

2020-01-08 03:43 UTC, ivanwonder commented
> Hi @ivanwonder, sorry for the delay. I have recently started a new job and been busy with the move and such. I will make an effort to be more active. I hope we can get this PR in soon. Keen should be back soon for a second pair of eyes as well.

Thanks for your reviews so much. I will do my best to finish this pr.

2020-01-08 03:45 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +}
https://github.com/angular/angular/blob/9b9116c79d626b6356f3dfe0d48c9d990ac412a2/packages/language-service/src/completions.ts#L50-L51
Only contain `@` here, or I add `animate-` to it.

2020-01-08 06:27 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +}
https://github.com/angular/angular/pull/34597#discussion_r364052767
The `TemplateAst` uses the binding parser, but just like I said, `this.isAnimation = !!this.phase;`, this is a problem. This is why the new `BoundEventInfo` I create has the fifth parameter.

2020-01-08 09:07 UTC, ivanwonder commented
> > Maybe we should open an issue for it.
> 
> Agreed!

@ayazhafiz https://github.com/angular/angular/issues/34673 I open a feature request issue

2020-01-08 16:17 UTC, ayazhafiz commented
I think we should wait on figuring out the disparity between the `@` and `animate-` prefixes before moving forward with this PR, because the diff could be large depending on whether the framework wants to support both or one prefix for events or bindings.

2020-01-10 19:59 UTC, kyliau commented
> > don't know if it's a mistake or a feat. When parse the event binding, it only supports `@` prefix.
> 
> Yeah, I noticed the same thing. I'm not sure if this intentional or not. @alxhub @JoostK can you provide some insight? Seems that animation bindings can be specified with the `@` or `animate-` prefix, but `animate-` only works in property bindings (and I can't seem to find any public documentation on it).

@matsko Do you know the specifics about the `@` and `animate-` prefix?

2020-11-24 05:27 UTC, AndrewKushnir commented
@kyliau @ayazhafiz, just want to check if the changes in this PR are still relevant in a context of upcoming Ivy-based Language Service? Thank you.

2020-11-30 01:36 UTC, ivanwonder commented
I think this should be resolved in the template parser. Now the parse will break when encounter the error, for example, `<div (@¦)="onAnimationEvent($event)"></div>`, the `outputs` of the `TemplateAst` is empty. @ayazhafiz

2020-12-01 16:29 UTC, ayazhafiz commented
> I think this should be resolved in the template parser. Now the parse will break when encounter the error, for example, `<div (@¦)="onAnimationEvent($event)"></div>`, the `outputs` of the `TemplateAst` is empty. @ayazhafiz

I agree this should be a parser-side fix, and then re 

> @kyliau @ayazhafiz, just want to check if the changes in this PR are still relevant in a context of upcoming Ivy-based Language Service? Thank you.

We should probably just use this work for the ivy-native language service.

@ivanwonder do you want to create a patch for the binding parser to handle this case? I think the r3_template_transform code is the only place we need to worry about this, if we are not interested in the fix for ViewEngine.

2020-12-02 01:05 UTC, ivanwonder commented
> @ivanwonder do you want to create a patch for the binding parser to handle this case?

yes, I will try

2020-12-02 06:29 UTC, ivanwonder commented
I find the test case support the `bind-animate-eventName`, but `on-animate-name.phase` doesn't.
https://github.com/angular/angular/blob/eac85b4e235fc99306945012a62ba4333e524718/packages/compiler/test/template_parser/template_parser_spec.ts#L726-L736

2020-12-02 06:51 UTC, ivanwonder commented
> > I think this should be resolved in the template parser. Now the parse will break when encounter the error, for example, `<div (@¦)="onAnimationEvent($event)"></div>`, the `outputs` of the `TemplateAst` is empty. @ayazhafiz
> 
> I agree this should be a parser-side fix, and then re
> 
> > @kyliau @ayazhafiz, just want to check if the changes in this PR are still relevant in a context of upcoming Ivy-based Language Service? Thank you.
> 
> We should probably just use this work for the ivy-native language service.
> 
> @ivanwonder do you want to create a patch for the binding parser to handle this case? I think the r3_template_transform code is the only place we need to worry about this, if we are not interested in the fix for ViewEngine.

@ayazhafiz  submit a PR #39925

2021-01-15 03:31 UTC, AndrewKushnir commented
@ivanwonder should we close this PR since #39925 has landed? Thank you.

2021-01-16 12:17 UTC, ivanwonder commented
> @ivanwonder should we close this PR since #39925 has landed? Thank you.

I will try to close this by this [PR](https://github.com/angular/angular/pull/40300#issuecomment-761553514)

2021-11-02 22:17 UTC, jessicajaniuk commented
Closing this since View Engine is no more and the [Ivy PR](https://github.com/angular/angular/pull/40300#issuecomment-761553514) is still around.

2021-11-02 22:17 UTC, closed without merging