fix(ivy): Ensure ngProjectAs marker name appears at even attribute index
angular/angular pull request #34617
Opened 2020-01-02 18:05 UTC by atscott

The `getProjectAsAttrValue` in `node_selector_matcher` finds the
`ProjectAs` marker and then additionally checks that the marker appears in
an even index of the node attributes because "attribute names are stored
at even indexes". This is true for "regular" attribute bindings but
classes, styles, bindings, templates, and i18n do not necessarily follow
this rule because there can be an uneven number of them, causing the
next "special" attribute "name" to appear at an odd index. To address
this issue, ensure `ngProjectAs` is placed right after "regular"
attributes.

2020-01-03 10:14 UTC, crisbeto commented on packages/compiler/src/render3/view/template.ts
> -    if (ngProjectAsAttr) {
Maybe we can keep the this logic inside `prepareNonRenderAttrs`, by moving the `push` further up? That way we can keep all the logic for the non-render attributes together.

2020-01-03 16:31 UTC, atscott commented on packages/compiler/src/render3/view/template.ts
> -    if (ngProjectAsAttr) {
I was waffling back and forth on this one. I moved it out because having it inside sort of makes some assumptions about the context in which the function is called that the function doesn't necessarily know about. It felt like the only real way to guarantee placement right after the other k/v attribute pairs was to have the code next to each other.

I did move it back though to keep it with the other non-render attributes.

2020-01-03 16:36 UTC, crisbeto approved these changes
LGTM

2020-01-03 21:08 UTC, AndrewKushnir commented on packages/compiler/src/render3/view/template.ts
> -    if (ngProjectAsAttr) {
As an option, we can refactor the code a bit and extend the function in `template.ts` that assembles attribute array (which is currently called `prepareNonRenderAttrs`, but we may need to find a better name during refactoring) to also accepts set of attributes (that should be at the very beginning of an array) as an argument. In this case, the right order/shape of the attributes array would be encapsulated within the `prepareNonRenderAttrs` function. We can reuse this function in the `visitContent` function as well for consistency.

2020-01-06 17:43 UTC, atscott commented on packages/compiler/src/render3/view/template.ts
> -    if (ngProjectAsAttr) {
Refactored to single function based on suggestion from @AndrewKushnir

2020-01-06 18:53 UTC, AndrewKushnir requested changes

2020-01-06 18:53 UTC, AndrewKushnir commented on packages/compiler/src/render3/view/template.ts
> +  private getAttributeExpressions(
Thanks for this refactoring @atscott, it looks great!

I think we should be able to use this function in the `visitContent` function as well, WDYT?

2020-01-06 18:53 UTC, AndrewKushnir commented on packages/compiler/src/render3/view/template.ts
> +      i18nAttrs: (t.BoundAttribute|t.TextAttribute)[] = [], ): o.Expression[] {
Extra comma at the end of the argument list.

2020-01-06 18:53 UTC, AndrewKushnir commented on packages/core/test/acceptance/content_spec.ts
> +         <div [color]="'blue'" ngProjectAs="[card-footer]">footer</div>
Could you plz add an attribute with a namespace, so we make sure projectAs attribute is always at the right location?

2020-01-06 19:22 UTC, atscott commented on packages/core/test/acceptance/content_spec.ts
> +         <div [color]="'blue'" ngProjectAs="[card-footer]">footer</div>
Done.

2020-01-06 19:22 UTC, atscott commented on packages/compiler/src/render3/view/template.ts
> +      i18nAttrs: (t.BoundAttribute|t.TextAttribute)[] = [], ): o.Expression[] {
Done.

2020-01-06 19:22 UTC, atscott commented on packages/compiler/src/render3/view/template.ts
> +  private getAttributeExpressions(
Done.

2020-01-06 19:29 UTC, AndrewKushnir approved these changes
LGTM 👍

2020-01-06 21:31 UTC, alxhub approved these changes

2020-01-06 21:34 UTC, atscott commented
[Ivy Presubmit](https://test.corp.google.com/ui#id=OCL:287998244:BASE:288341489:1578339247698:a76daa54)

2020-01-07 18:51 UTC, closed without merging