docs: add note that when ngOnInit not used
angular/angular pull request #34619
Opened 2020-01-02 18:29 UTC by ajitsinghkaler

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

No note on when NgOnInit used in the Your First app tutorial of getting started.

Issue Number: #34562 

## What is the new behavior?
Added a note when ngOnInit Used.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-01-02 18:35 UTC, ajitsinghkaler commented
@kapunahelewong can you please look into this.

2020-01-06 16:18 UTC, kapunahelewong requested changes
Thanks for this, @ajitsinghkaler. Just a little note.

2020-01-06 16:18 UTC, kapunahelewong commented on aio/content/start/index.md
> +  Whenever a new component is generated using the Angular CLI it comes with an empty constructor,the OnInit interface and the ngOnInit() method. Since they are not used in the following example they
How about the following edits?
```suggestion
  When the Angular CLI generates a new component, it includes an empty constructor, the `OnInit` interface, and the `ngOnInit()` method. 
  Since the following example isn't using them, they are omitted here for brevity.
```

I also put the second sentence on its own line because it makes it easier to review in the future.

2020-01-10 03:53 UTC, ajitsinghkaler commented
@kapunahelewong I've made the changes please review it.

2020-01-10 19:10 UTC, kapunahelewong approved these changes

2020-01-10 19:13 UTC, kapunahelewong commented
merge-assistance: Global approval for this docs-only change.

2020-01-10 22:40 UTC, closed without merging