docs: additional differential loading clarification
angular/angular pull request #34620
Opened 2020-01-02 19:26 UTC by clydin

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The guide contains minimal information regarding the differential build process and how it can affect deployment.

## What is the new behavior?
Provide additional details regarding the differential loading build process as well as contrast it with other methods of building the project (e.g., directly targeting ES5 as the compilation output).

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-01-02 19:35 UTC, mary-poppins commented
You can preview dd59338 at https://pr34620-dd59338.ngbuilds.io/.

2020-01-07 19:40 UTC, jbogarthyde requested changes
Copy edit

2020-01-07 19:40 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +To optimize differential loading build performance, the CLI uses a bundle level transformation process.
bundle-level

2020-01-07 19:40 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +This process also guarantees that the entire bundled application is ES5 compliant including third-party code.
490:
 Once the full ES2015 compilation is complete, a post-processing step transforms each output JavaScript file into an additional ES5 variant, and generates an additional ES5-only file containing the polyfills that are required for ES5 browsers.
491: (new paragraph)
 The bundle-level transformation process guarantees that the entire bundled application is ES5 compliant, including any third-party code. This is not the case when you simply change the compilation target to `es5`.

2020-01-07 19:40 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +This process is different than changing the compilation target to `es5`.
Bundle-level transformation is more efficient and thorough than simply changing the compilation target to `es5`.

2020-01-07 19:40 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +The main entry point may not contain code that is ES5 compatible.
remove (added to previous sentence)

2020-01-07 19:40 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +If using a compilation target of `es5`, it is important to ensure that all libraries used by the application provide ES5 compatible code.
If you do use an `es5` compilation target (rather that the bundle-level transformation), you must ensure that all libraries used by the application provide ES5 compatible code.

2020-01-07 19:40 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +When changing the compilation target to `es5`, only the TypeScript application code will be transformed to ES5. For libraries, the ES5 entry point of the library's package will be used directly. If a
When you change the compilation target to `es5`, only the TypeScript application code is transformed to ES5. For libraries, the ES5 entry point of the library's package is used directly if one exists. If it does not, the main entry point of the library's package is used, and that entry point might contain code that is not ES5-compatible.

2020-01-08 18:26 UTC, mary-poppins commented
You can preview d06917b at https://pr34620-d06917b.ngbuilds.io/.

2020-01-08 20:33 UTC, jbogarthyde approved these changes
Looks good - some minor typo corrections.

2020-01-08 20:33 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +This process requires that only one full compilation of the application in ES2015 syntax to take place.
requires only one full compilation of the application in ES2015 syntax.

2020-01-08 20:33 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +If you do use an `es5` compilation target (rather that the bundle-level transformation), you must ensure that all libraries used by the application provide ES5 compatible code.
rather than

2020-01-09 16:30 UTC, mary-poppins commented
You can preview fea3f13 at https://pr34620-fea3f13.ngbuilds.io/.

2020-01-21 05:55 UTC, IgorMinar requested changes

2020-01-21 05:55 UTC, IgorMinar commented on aio/content/guide/deployment.md
> + The bundle-level transformation process guarantees that the entire bundled application is ES5 compliant, including any third-party code. This is not the case when you simply change the compilation t
```suggestion
 The bundle-level transformation process guarantees that the entire bundled application is ES5 compliant, including any third-party code. This is not the case when you simply change the compilation target to `es5` in `tsconfig.app.json`.
```

2020-01-21 05:55 UTC, IgorMinar commented on aio/content/guide/deployment.md
> +Bundle-level transformation is more efficient and thorough than simply changing the compilation target to `es5`.
I don't think that this line and all the other newly added lines below are adding much value and only confuse the reader. I suggest that we remove them.

2020-01-21 05:55 UTC, IgorMinar commented
thanks @clydin but I think we can make the text a bit more clear. Can you please look at my comments?

2020-01-21 14:58 UTC, clydin commented on aio/content/guide/deployment.md
> +Bundle-level transformation is more efficient and thorough than simply changing the compilation target to `es5`.
Had similar thoughts when writing this part.  My initial reasoning for including it was that there have been several issues expressing confusion on why user's applications worked with differential loading but failed when only targeting es5 in the tsconfig.  (Upon investigation, some of the third-party libraries didn't provide ES5 code).

However, the underlying issue is something that will be corrected soon (and prevent the aforementioned situation) so I think removing it as you suggested is a good idea.

2020-01-21 15:18 UTC, mary-poppins commented
You can preview d7551d8 at https://pr34620-d7551d8.ngbuilds.io/.

2020-01-21 17:18 UTC, clydin commented on aio/content/guide/deployment.md
> +When targeting older browsers, [polyfills](guide/browser-support#polyfills) can help bridge the gap by providing functionality that doesn't exist in the older versions of JavaScript supported by thos
@jbogarthyde I did an initial update based on the proposal above.  Can you do another review of this section?

2020-01-21 17:23 UTC, mary-poppins commented
You can preview 16601ea at https://pr34620-16601ea.ngbuilds.io/.

2020-01-21 17:29 UTC, jbogarthyde requested changes
minor edits, plus I suggest adding the "differential loading" term to the Glossary.

2020-01-21 17:29 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +When targeting browsers that do not support ES2015, like IE11, you will need to do two things to ensure that the application runs correctly:
like -> such as
you will need to -> you must

2020-01-21 17:29 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +  1. Downlevel all JavaScript to ES5 so that the code is syntactically compatible
add period -- compatible.

2020-01-21 17:29 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +Differential loading is a technique of building and loading your application that meets both of these requirements, without penalizing users with modern browsers by having them download code that onl
*Differential loading*
Introduction of term in italics -- UNLESS you add it to the glossary and make it a link (which is not a bad idea).
I can help do that if you want -- in that case, `[Differential loading](guide/glossary#differential_loading)`

2020-01-21 17:29 UTC, jbogarthyde commented on aio/content/guide/deployment.md
> +The `ng serve`, `ng test`, and `ng e2e` commands, however, generate a single ES2015 build which cannot run in older browsers, such as IE 11.
which --> that

2020-01-21 19:20 UTC, clydin commented on aio/content/guide/deployment.md
> +Differential loading is a technique of building and loading your application that meets both of these requirements, without penalizing users with modern browsers by having them download code that onl
Text updated here to reference the glossary.
Glossary update PR: https://github.com/angular/angular/pull/34884

2020-01-25 00:34 UTC, mary-poppins commented
You can preview 3f770aa at https://pr34620-3f770aa.ngbuilds.io/.

2020-02-18 18:31 UTC, jbogarthyde approved these changes
LGTM

2020-04-06 17:13 UTC, IgorMinar requested changes
I made a few suggestions, but in general my impression is that this doc is focused more on describing the implementation than describing the feature from the customers perspective. I proposed how this content could be restructured further to be more aligned with how a user/customer of the CLI needs to ingest the information.

@aikidave, can you please take a look as well and feel free to overrule my request.

2020-04-06 17:13 UTC, IgorMinar commented on aio/content/guide/deployment.md
> +[Differential loading](guide/glossary#differential-loading) is a technique of building and loading your application that meets both of these requirements, without penalizing users with modern browser
I had to read to all the way down here to learn that:

1. the differential serving is something the CLI does and solves this compatibility problem with older browsers
2. this feature is enabled in the CLI by default, so I don't need to do anything to get it to work

This information is crucial and should be provided to the user upfront. I suggest that you rewrite this section from the customer's perspective. The customer doesn't care about how this stuff is implemented. What they care about is the following:

- Angular CLI by default ensures that your application is compatible with legacy browsers, such as IE11
- to do this, Angular CLI implements a feature called Differential Loading
- this feature requires extra processing and slows down the build, so if the audience of the app doesn't use IE11, then this feature can be disabled by doing X, to speed up the build
- differential loading is disabled in dev mode (when `ng test` or `ng serve`) are run, so if the developer needs to test their app on IE11 or other old browsers, then they can enable differential loading in the dev mode by doing Y
- *lastly* add a section on what differential serving is and how it works for those that want to know about the implementation details.

2020-04-15 00:54 UTC, aikidave commented on aio/content/guide/deployment.md
> +All modern browsers support ES2015 and beyond, but in most cases, you still have to account for users accessing your application from a browser that does not support ES2015.
I'd split this into two smaller sentences:
```suggestion
All modern browsers support ES2015 and beyond. For some applications, you still have to account for users accessing your application from a browser that does not support ES2015.
```

2020-04-15 00:54 UTC, aikidave commented on aio/content/guide/deployment.md
> +The `ng serve`, `ng test`, and `ng e2e` commands, however, generate a single ES2015 build that cannot run in older browsers, such as IE 11.
```suggestion
By default, the `ng serve`, `ng test`, and `ng e2e` commands, generate a single ES2015 build that cannot run in older browsers, such as IE 11.
```

2020-04-15 00:54 UTC, aikidave commented on aio/content/guide/deployment.md
> +[Differential loading](guide/glossary#differential-loading) is a technique of building and loading your application that meets both of these requirements, without penalizing users with modern browser
I will defer to Igor on this, but I do agree: writing with the user in mind is much better than writing for what the feature/product does. I am happy to help with this if you need someone to plan on outline or provide more structural edits.

2020-04-15 02:02 UTC, clydin commented on aio/content/guide/deployment.md
> +[Differential loading](guide/glossary#differential-loading) is a technique of building and loading your application that meets both of these requirements, without penalizing users with modern browser
My initial goal was to adjust some of the language to be more technically correct and to provide some additional insight into the underlying functionality.  This was driven by issue reports from users that were unsure of the intended/expected behavior when enabled.

However, I do agree that the section as a whole could be better structured.  I think if a larger restructuring where to occur, it may also be better served as either a standalone guide or as part of the browser support guide.  Browser support is the main goal of differential loading and there is already a short section in that guide discussing it.
Thoughts?

2020-08-31 20:42 UTC, closed without merging