build: bump year
angular/angular pull request #34651
Opened 2020-01-06 20:49 UTC by CaerusKaru

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-01-06 21:20 UTC, StephenFluin requested changes

2020-01-06 21:20 UTC, StephenFluin commented on aio/content/guide/static-query-migration.md
> +**Important note for library authors: This migration is especially crucial for library authors to facilitate their users upgrading to version 9 when it becomes available (approx Jan 2020).**
Can you just remove the date?

2020-01-06 21:59 UTC, StephenFluin approved these changes
LGTM. I'll defer to others regarding overall legal requirements for changing year.

2020-01-07 09:59 UTC, filipesilva approved these changes

2020-01-07 10:01 UTC, petebacondarwin approved these changes

2020-01-07 13:49 UTC, gkalpak approved these changes
Could you also update [aio/src/404-body.html][1], which seems to be stuck in 2018 :grin:

[1]: https://github.com/angular/angular/blob/5b864ede1/aio/src/404-body.html#L45

2020-01-07 14:16 UTC, devversion approved these changes
LGTM. FYI: It looks like there is a second PR for bumping the year: https://github.com/angular/angular/pull/34604

2020-01-07 17:00 UTC, CaerusKaru commented
@gkalpak All set :+1:

2020-01-12 02:00 UTC, IgorMinar approved these changes
thanks!

2020-01-12 02:00 UTC, IgorMinar commented
merge-assistance: global approval

2020-01-13 15:21 UTC, closed without merging