docs: add Angular-Slickgrid library to the list of resources
angular/angular pull request #34656
Opened 2020-01-07 04:12 UTC by ghiscoding

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Simply added an Angular library (that I support) to the list of Angular Resources

2020-01-07 21:25 UTC, kapunahelewong requested changes
Thank you, @ghiscoding! Just a couple of comments. :)

2020-01-07 21:25 UTC, kapunahelewong commented on aio/content/marketing/resources.json
> +            "desc": "Amexio Canvas is Drag and Drop Environment to create Fully Responsive Web and Smart Device HTML5/Angular Apps. Code will be auto generated and hot deployed by the Canvas for live
```suggestion
            "desc": "Amexio Canvas is a drag and drop environment you can use to create fully responsive web and smart device HTML5/Angular Apps. Canvas auto generates and hot deploys code for live testing. Out of the box 50+ Material Design Theme support. Commit your code to GitHub public or private repositories.",
```

2020-01-07 21:25 UTC, kapunahelewong commented on aio/content/marketing/resources.json
> +            "desc": "Angular-SlickGrid is a wrapper of the lightning fast & customizable SlickGrid datagrid library with Bootstrap 3,4 themes",
Should it be 3.4? (Period instead of comma?)

2020-01-07 21:32 UTC, ghiscoding commented on aio/content/marketing/resources.json
> +            "desc": "Angular-SlickGrid is a wrapper of the lightning fast & customizable SlickGrid datagrid library with Bootstrap 3,4 themes",
no a comma is fine, it's representing 2 versions of the Bootstrap library.

2020-01-07 21:33 UTC, ghiscoding commented on aio/content/marketing/resources.json
> +            "desc": "Amexio Canvas is Drag and Drop Environment to create Fully Responsive Web and Smart Device HTML5/Angular Apps. Code will be auto generated and hot deployed by the Canvas for live
that is actually not my library, the only reason that it shows up in my commit is because I had the auto-format on save enabled and it removed an extra space that was added by another user. So I would rather not touch it more than the space

2020-01-08 19:23 UTC, kapunahelewong commented on aio/content/marketing/resources.json
> +            "desc": "Amexio Canvas is Drag and Drop Environment to create Fully Responsive Web and Smart Device HTML5/Angular Apps. Code will be auto generated and hot deployed by the Canvas for live
Ah I see.

2020-01-08 19:24 UTC, kapunahelewong commented on aio/content/marketing/resources.json
> +            "desc": "Angular-SlickGrid is a wrapper of the lightning fast & customizable SlickGrid datagrid library with Bootstrap 3,4 themes",
Got it.

2020-01-08 19:27 UTC, kapunahelewong commented
Thanks for the clarification, @ghiscoding! When you get fw-docs-marketing approval, will you tag me (if I don't see it right away)? Don't worry about rebasing - if we have to do it, I can help you from my end. Easy peasy! 🙂

2020-01-08 19:31 UTC, ghiscoding commented
@kapunahelewong 
Will they approve it if it still shows as "Changes Requested" though?

2020-01-08 19:38 UTC, kapunahelewong commented
Yes, that shouldn't hold anything back as it can still be merged without my specific approval. Though if I leave it like that, it should prompt someone to ping me on it in this particular case. But since it's in the Docs project board, I should be back in here before it's merged anyway (usually, though not always, so I'm hoping you'll tag me if I miss their approval). Usually on a PR like this, when it gets approved I come back in and help it through the rest of the process. I'm just leaving a trail of "hey, I want to come back", if that makes sense! The reason I want to come back in is really just to help it land. :)

2020-01-08 19:51 UTC, StephenFluin approved these changes

2020-01-08 20:02 UTC, ghiscoding commented
@kapunahelewong it's now approved. Thanks 😃

2020-01-08 20:49 UTC, kapunahelewong approved these changes

2020-01-08 23:06 UTC, closed without merging

2020-01-13 15:15 UTC, ghiscoding commented
@kapunahelewong 
Thanks for all the help in merging this, I just have a quick question. Out of curiosity, how long does it take to eventually see it on the `angular.io`? Is that driven by Angular versions? The reason I'm asking is that I see even older PRs like #33730 (merged in early November) is still not showing up on the `angular.io` site.

2020-01-15 16:34 UTC, kapunahelewong commented
Hi @ghiscoding, yes, it is version related. So right now, the changes are live on [next.angular.io](http://next.angular.io) because the changes were merged into the 9.0.x branch and not the 8.2.x branch (which is what gets deployed to angular.io while 8.x is the stable version (9.x is still in RC)). Changes will appear on angular.io as soon as 9.0.0 gets released (making v9 the new stable version). 

Regarding #33730, it isn't typical of an Angular version to remain in RC that long, but v9 is special due to Ivy. 

Sorry it took me a while to respond, but I had to go learn about the process and ask a bunch of questions to clear it up my own understanding. Hope this helps!

2020-01-15 16:57 UTC, ghiscoding commented
@kapunahelewong 
Cool thanks a lot for the reply, very much appreciated, nice to know it was what I thought it was 😃