Host decl
angular/angular pull request #34683
Opened 2020-01-08 20:34 UTC by mhevery

#refactor(ivy): move `hostVars`/`hostAttrs` from instruction to `DirectiveDef`
    
This change moves information from instructions to declarative position:
- `ɵɵallocHostVars(vars)` => `DirectiveDef.hostVars`
- `ɵɵelementHostAttrs(attrs)` => `DirectiveDef.hostAttrs`
    
When merging directives it is necessary to know about `hostVars` and `hostAttrs`. Before this change that information was stored in the `hostBindings` function. This was problematic, because in order to get to that information the `hostBindings` would have to be executed. In order for `hostBindings` to be executed the directives would have to be instantiated. This means that the directive instantiation would happen before we had knowledge about the `hostAttrs` and as a result the directive could observe in the constructor that not all of the `hostAttrs` have been applied. This further complicates the runtime as we have to apply `hostAttrs` in parts over many invocations.
    
`ɵɵallocHostVars` was unnecessarily complicated because it would have to update the `LView` (and Blueprint) while existing directives are already executing. By moving it out of `hostBindings` function we can access it statically and we can create correct `LView` (and Blueprint) in a single pass.
    
This change only changes how the instructions are generated, but does not change the runtime much. (We cheat by emulating the old behavior by calling `ɵɵallocHostVars` and `ɵɵelementHostAttrs`) Subsequent change will refactor the runtime to take advantage of the static information.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-01-09 13:03 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +  describe('appendHostAttrs', () => {
Those look like low-level tests digging into ivy internals so I would probably move those out of `acceptance` into `src/render3/features/inherit_definition_feature_spec.ts`

2020-01-09 13:09 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +    ɵɵallocHostVars(def.hostVars);
I guess we should rename those functions and drop the `ɵɵ` prefix as those are not the instructions any more. Same for `ɵɵelementHostAttrs`

2020-01-09 13:11 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +      if (def.hostBindings || def.hostVars !== 0 || def.hostAttrs !== null) {
Use `TNodeFlags.hasHostBindings` since it was already set in resolve directives?

2020-01-09 16:13 UTC, kara requested changes

2020-01-09 20:12 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +    ɵɵallocHostVars(def.hostVars);
These will be deleted in follow up PRs, so I don't think it is worth creating the churn. (See: https://github.com/angular/angular/pull/34708)

2020-01-09 20:12 UTC, mhevery commented on packages/core/test/bundling/hello_world/bundle.golden_symbols.json
> +    "name": "allocStylingMapArray"
These will be deleted in follow up PR.

2020-01-09 20:20 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +    ɵɵallocHostVars(def.hostVars);
oh, sure, no need to rename if those go away!

2020-01-09 23:25 UTC, mhevery commented on packages/core/test/acceptance/inherit_definition_feature_spec.ts
> +  describe('appendHostAttrs', () => {
moved

2020-01-09 23:25 UTC, mhevery commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +                           srcMarker === -1 || srcMarker === AttributeMarker.Styles, true,
fixed

2020-01-09 23:25 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +      if (def.hostBindings || def.hostVars !== 0 || def.hostAttrs !== null) {
That is not possible. The if statement is on per directive basis, where as `TNodeFlags.hasHostBindings` is on `TNode` level. So it will either flag all or no directives. In subsequent PRs some of the `||` portions will be removed so it will become `if (def.hostBindings !== null)`

2020-01-10 00:04 UTC, kara approved these changes
LGTM

2020-01-10 00:47 UTC, JoostK commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +    (null as any as returnWritableType)(null as any as DirectiveDef<any>| ComponentDef<any>);
Instead of the weird trick with the `returnWritableType` function type, you could use a mapped type instead that removes the readonly marker:

```ts
type Writable<T> = { -readonly [K in keyof T]: T[K] };
```

2020-01-10 16:09 UTC, mhevery commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +    (null as any as returnWritableType)(null as any as DirectiveDef<any>| ComponentDef<any>);
WHAT! That is possible! I love it. Will change

2020-01-10 16:13 UTC, mhevery commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +    (null as any as returnWritableType)(null as any as DirectiveDef<any>| ComponentDef<any>);
Thanks @JoostK I learned something new!

2020-01-10 16:16 UTC, mhevery commented on packages/core/src/render3/features/inherit_definition_feature.ts
> +/// This will be tree shaken because it is reference as type only.
removed per @JoostK  suggestion

2020-01-10 17:50 UTC, mhevery commented
merged in 82a41af062

2020-01-10 17:50 UTC, closed without merging