refactor(ivy): delete `ɵɵelementHostAttrs` instruction
angular/angular pull request #34717
Opened 2020-01-10 05:50 UTC by mhevery

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-01-10 22:53 UTC, kara requested changes

2020-01-10 22:53 UTC, kara commented on packages/core/src/render3/interfaces/node.ts
> +   * Same as `TNode.attrs` but contains merged data across all directive host bindings.
I think the "why" is missing here for why they have to be two separate properties (I assume it's because host attrs shouldn't be used for matching, etc?)

2020-01-10 22:53 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> -  setCurrentDirectiveDef(def);
We should clean up the `setCurrentDirectiveDef` and `getCurrentDirectiveDef` functions, since nothing else uses them

2020-01-10 22:53 UTC, kara commented on packages/core/test/render3/node_selector_matcher_spec.ts
> -      it('should match against a class value before and after the styling context is created',
Why remove this test?

2020-01-10 22:53 UTC, kara commented on packages/core/src/render3/component.ts
> +    registerInitialStylingOnTNode(tNode, mergedAttrs, 0);
I think this is bringing in the 1.5 KB that we thought we'd remove in https://github.com/angular/angular/pull/34683/files#r364806373

2020-01-13 13:01 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/element.ts
> +  if (mergedAttrs != null) {
`!== null`?

2020-01-13 13:37 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +  // Merge the template attrs last so that they have the highest priority.
+1 for test(s) around attribute order / priority

2020-01-13 13:39 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
>  import {ActiveElementFlags, enterView, executeElementExitFn, getBindingsEnabled, getCheckNoChangesMode, getIsParent, getPreviousOrParentTNode, getSelectedIndex, hasActiveElementFlag, incrementActiveD
Unused `setCurrentDirectiveDef` import

2020-01-13 13:42 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +function findDirectiveDefMatches(
👍 for the rename (this and others)

2020-01-13 21:52 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +   * Same as `TNode.attrs` but contains merged data across all directive host bindings.
added text

2020-01-13 21:52 UTC, mhevery commented on packages/core/src/render3/node_selector_matcher.ts
> + * @param isProjectionMode Weather or not class matching should look into the attribute `class` in
fixed

2020-01-13 21:52 UTC, mhevery commented on packages/core/test/bundling/hello_world/bundle.golden_symbols.json
>    {
Sorry, they will be here: https://github.com/angular/angular/pull/34616

2020-01-13 21:52 UTC, mhevery commented on packages/core/test/render3/node_selector_matcher_spec.ts
> -      it('should match against a class value before and after the styling context is created',
Because old system supported putting StylingContext into `TNode.classes` which the new one does not. That code has been deleted/simplified.

2020-01-13 21:52 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +  // Merge the template attrs last so that they have the highest priority.
1. I was not intending to change the attr priority only styling priority. 
2. Thinking about it I think the attribute priority should follow that of classes, so I think we should change it? I could be considered either way. Let's change it and see how much g3 impact it has.
2. I have added a tests to show this.

2020-01-13 22:57 UTC, kara commented on packages/core/test/acceptance/styling_spec.ts
> +  it('should merge attributes on host and template', () => {
Given that this is a test for attributes (not styling), can we move it out of the styling spec? I think `host_binding_spec` would probably be where I would look for it.

2020-01-13 22:57 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> +  // Merge the template attrs last so that they have the highest priority.
Sounds good. If we G3 passes, let's create a Jira so we don't forget to document the new BC.

2020-01-13 23:08 UTC, kara approved these changes
LGTM, but some quick things below

2020-01-13 23:08 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> +        // Merge the attrs in the order of matches. This assumes tha the first directive is the
```suggestion
        // Merge the attrs in the order of matches. This assumes that the first directive is the
```

2020-01-13 23:08 UTC, kara commented on packages/core/test/acceptance/styling_spec.ts
> +  it('should merge attributes on host and template', () => {
Given that this is a test for attributes (not styling), can we move it out of the styling spec? I think `host_binding_spec` would probably be where I would look for it.

2020-01-14 00:06 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +   * We merge attrs heres so that it can be used in a performant way for initial rendering.
fixed

2020-01-14 00:06 UTC, mhevery commented on packages/core/src/render3/interfaces/node.ts
> +   * The `attrs` are merged an first pass in following order:
fixed

2020-01-14 00:07 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +        // Merge the attrs in the order of matches. This assumes tha the first directive is the
fixed

2020-01-14 00:08 UTC, mhevery commented on packages/core/test/acceptance/styling_spec.ts
> +  it('should merge attributes on host and template', () => {
moved

2020-01-14 05:11 UTC, mhevery commented
[presubmit](http://test/OCL:289578700:BASE:289578731:1578978677611:19927dde)

2020-01-14 05:41 UTC, merged