Ngcc lockfile
angular/angular pull request #34722
Opened 2020-01-10 09:55 UTC by petebacondarwin

2020-01-14 22:03 UTC, JoostK commented on packages/compiler-cli/ngcc/test/helpers/mock_lock_file.ts
> +    super(new MockFileSystemNative());
Could this be `getFileSystem` instead, as we run inside `runInEachFileSystem`?

2020-01-15 21:39 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +    this.fs.writeFile(this.lockFilePath, process.pid.toString());
I have changed the algorithm to use an exclusive write (and no exists check) which removes the change of a race condition, so I think we can get away with not adding the PID check here.

2020-01-15 21:40 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/helpers/mock_lock_file.ts
> +    super(new MockFileSystemNative());
I have added a comment to the code. This `MockLockFile` is not used in tests that run `runInEachFileSystem`.

2020-01-15 21:40 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +    process.once('SIGHUP', this.signalHandler);
No idea! I am hoping that our CI (or one of our Windows gurus) will test that for me :-)

2020-01-15 21:40 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +    process.once('SIGHUP', this.signalHandler);
But to be serious, I looked into it and in theory this should be enough...

2020-01-15 21:42 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +    }
Sadly we can't remove the handlers here because it breaks the unit tests. This is because in the unit tests we don't actually kill the process so `remove()` still gets called :-/

2020-01-16 08:26 UTC, JoostK commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +        pid = '{unkown}';
```suggestion
        pid = '{unknown}';
```

2020-01-16 08:26 UTC, JoostK commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +      } catch (e) {
```suggestion
      } catch {
```

2020-01-16 08:33 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +      } catch (e) {
Woh! I was sure that one had to provide the `(e)` even if you didn't use it. But I see that this is not the case. YLSED!

2020-01-16 09:19 UTC, JoostK commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +      } catch (e) {
@petebacondarwin it's been supported since TS2.5! https://mariusschulz.com/blog/optional-catch-binding-in-typescript

2020-01-16 14:30 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +    }
Hmm, but I just realised that the CLI will not exit the process after each ngcc run (i.e. they use `main.ts` directly. Which means that each time the CLI runs ngcc we will add more handlers...
So perhaps I do need to find a way to remove the handlers here - and still get it to work in the unit tests...

2020-01-16 14:53 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +    }
And I can indeed run the `removeSignalHandlers()` here!

2020-01-16 22:27 UTC, gkalpak requested changes
Looking good! Some minor comments/questions/suggestions.

2020-01-16 22:27 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/main.ts
> +    return;
`mainNgcc` is expected to return a promise if `async` is true (returning `undefined` could break someone using it programatically and expecting a promise - not that there's anyone doing this, but better to be safe :grin:):

```suggestion
    return async ? Promise.resolve() : undefined;
```

2020-01-16 22:27 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +  lockFilePath = this.fs.resolve(__dirname, '__ngcc_lock_file__');
Why not create it in a more "central" place, such as `compiler-cli/` or `compiler-cli/ngcc/`?
That would also be better DX imo (in case one needs to remove it manually after a crash or something).

2020-01-16 22:27 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +        return result.finally(() => this.remove()) as unknown as T;
[According to MDN][1], `Promise.finally` is available in Node.js since v10. Should we play it safe and refrain from using it?

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally#Browser_compatibility

2020-01-16 22:27 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +        this.exit(1);
Given that `removeSignalHandlers` is now called in `this.remove()`, this could be just `process.exit(1)` (and the `exit()` method could be dropped).

2020-01-16 22:27 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +    this.create();
So, if `this.create()` errors (and the process does not exit, because the caller handles the error), shouldn't signal handlers still be removed?

2020-01-16 22:27 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +    this.fs.ensureDir(this.fs.dirname(this.lockFilePath));
Is this necessary, given that it's `__dirname`?

2020-01-17 08:33 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +  lockFilePath = this.fs.resolve(__dirname, '__ngcc_lock_file__');
I did consider that but I was concerned about hard-coding the path to a more central place into this file. If folders/files get moved around then we would need to update the logic here, which IMO is brittle.

The path to the file is printed in the error message, so it is a simple cut-and-paste to delete it. And IMO there is not a huge difference in complexity for the developer between:

```
/Users/pete/dev/angular/tmp/ngcc-lockfile/integration/ngcc/node_modules/@angular/compiler-cli/ngcc/src/execution/__ngcc_lock_file__
```

and

```
/Users/pete/dev/angular/tmp/ngcc-lockfile/integration/ngcc/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__
```

2020-01-17 08:43 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +        return result.finally(() => this.remove()) as unknown as T;
The `package.json` for Angular indicates node.js >= 10.9; in CLI it is >=10.13. Moreover the CLI will actively error if the node.js version is below 10.13. See https://github.com/angular/angular-cli/blob/43e43bfacb7b59624b726ae1976e4d63d89bebf9/packages/angular/cli/lib/cli/index.ts#L26

So I think we are safe using this.

2020-01-17 08:48 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +        this.exit(1);
You are right, we can remove the call to `removeSignalHandlers()` from `exit()` but I want to keep that method because it is not possible to mock out `process.exit()` directly in unit tests: I found that the `process` object/namespace is not the same inside signal handlers - so if you replace `process.exit` in unit tests, the original one is still called inside the handler.

2020-01-17 09:05 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +    this.fs.ensureDir(this.fs.dirname(this.lockFilePath));
You are right that during normal operation this is not required. Good spot.

I threw this in because in many unit tests we are using a mock file-system that does not include the source files (and therefore doesn't contain this directory). If we don't do this here we have to change "a lot" of unit tests.

But I have just looked again, and I realise that I can add this to the `LockFileUnderTest` class rather than it appearing in the "real" `LockFile` class.

2020-01-17 09:15 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +        return result.finally(() => this.remove()) as unknown as T;
The `package.json` at the repository root (which I assume is what you mean by "package.json for Angular") only applies during development (i.e. when one works in the repository). It does not affect the published packages (and their consumers). The [package.json][1] of the `compiler-cli` package currently requires Node.js >=8.

Also, while the latest CLI does require >=10.13, isn't it possible (although probably not recommended) that users could use the latest Angular with an older CLI version (or without the CLI at all)?

##
Maybe we just need to update `compiler-cli/package.json` to require Node.js v10 or newer. I think that would be best for v9.

[1]: https://github.com/angular/angular/blob/f2df1c79d/packages/compiler-cli/package.json#L31

2020-01-17 09:19 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +        return result.finally(() => this.remove()) as unknown as T;
I agree that we should update the compiler-cli package.json. I'll add a commit to this PR.

2020-01-17 09:20 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +        return result.finally(() => this.remove()) as unknown as T;
The last time it was changed was to align it with the CLI: https://github.com/angular/angular/commit/c602563589a7e14f0c57ee5b191979039aa370db

2020-01-17 09:24 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +    this.fs.ensureDir(this.fs.dirname(this.lockFilePath));
Actually a whole load of the integration tests also need this folder to exist :-/

2020-01-17 09:41 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +    this.fs.ensureDir(this.fs.dirname(this.lockFilePath));
I tweaked the integration tests to also ensure this folder exists...

2020-01-17 11:48 UTC, JoostK commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +  lockFilePath = this.fs.resolve(__dirname, '__ngcc_lock_file__');
@petebacondarwin Establishing the path of the ngcc root would be quite stable with `require.resolve('@angular/compiler-cli/ngcc')`?

2020-01-17 13:08 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/lock_file.ts
> +  lockFilePath = this.fs.resolve(__dirname, '__ngcc_lock_file__');
Done

2020-01-18 18:22 UTC, gkalpak approved these changes
👌

2020-01-18 18:22 UTC, gkalpak commented on packages/compiler-cli/ngcc/test/execution/lock_file_spec.ts
> +          process.emit('SIGINT', 'SIGINT');
OOC, why the second arg?

2020-01-20 09:42 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/execution/lock_file_spec.ts
> +          process.emit('SIGINT', 'SIGINT');
I don't know if this is needed for the runtime but the typings for this overload (i.e. on that uses a signal string in the first parameter) looks like:

```ts
        emit(event: Signals, signal: Signals): boolean;
```

So at the very least, the second parameter is needed for TS compilation.

2020-01-20 12:22 UTC, JoostK approved these changes

2020-01-21 18:34 UTC, matsko commented
presubmit = https://test.corp.google.com/ui#id=OCL:290769792:BASE:290769840:1579630888550:8a26eed7

2020-01-22 13:26 UTC, petebacondarwin commented
@matsko - what is the reason for the presubmit failure?

2020-01-22 17:31 UTC, AndrewKushnir commented
@petebacondarwin it looks like there were some pre-existing failing tests. I marked "google3" check as passing for this PR. Thank you.

2020-01-22 19:38 UTC, matsko commented
@petebacondarwin please rebase.

2020-01-22 19:54 UTC, petebacondarwin commented
@matsko - done.

2020-01-22 23:35 UTC, closed without merging