ci: do not run benchmark measurements in circleci
angular/angular pull request #34753
Opened 2020-01-13 09:36 UTC by devversion

Currently we run all benchmark perf tests in CircleCI. Since we do not
collect any results, we unnecessarily waste CI/RBE resources. Instead,
we should just not run benchmark perf tests in CI, but still run the
functionality e2e tests which ensure that benchmarks are not broken.

We can do this by splitting the perf and e2e tests into separate
files/targets.

2020-01-14 21:12 UTC, IgorMinar requested changes
thanks @devversion!  I found a few things that I think we could improve, please take a look at the individual comments.

2020-01-14 21:12 UTC, IgorMinar commented on modules/e2e_util/e2e_util.ts
> +let cmdArgs: {'bundles': boolean}|undefined;
I believe that his is obsolete. In the past you used to be able to run the benchmarks with js code bundled or not. with bazel you can only run them as bundled (because the build is fast enough compared to the pre-bazel build).

I suggest, you remove this option.

2020-01-14 21:12 UTC, IgorMinar commented on modules/benchmarks/src/largeform/BUILD.bazel
> +    srcs = ["largeform.spec.ts"],
can we disambiguate the ".spec.ts" files, by calling them ".e2e-spec.ts" and ".perf-spec.ts"?

2020-01-14 21:12 UTC, IgorMinar commented on modules/benchmarks/e2e_test.bzl
> +        deps = ["@npm//yargs"] + deps,
do we still need it after you remove the command line option (see comment below)?

2020-01-15 11:27 UTC, devversion commented on modules/e2e_util/e2e_util.ts
> +let cmdArgs: {'bundles': boolean}|undefined;
Good idea. Will do! I was unsure if this is still needed somewhere.

2020-01-15 11:38 UTC, devversion commented on modules/benchmarks/src/largeform/BUILD.bazel
> +    srcs = ["largeform.spec.ts"],
Sounds good to me.

2020-01-16 11:30 UTC, devversion commented on modules/benchmarks/e2e_test.bzl
> +        deps = ["@npm//yargs"] + deps,
Yeah, this can be removed then. Nice idea 👍

2020-01-16 13:34 UTC, devversion commented
@IgorMinar Thanks for reviewing! I addressed your feedback.

2020-01-17 23:20 UTC, IgorMinar approved these changes

2020-01-17 23:20 UTC, IgorMinar commented
thank you!

2020-01-17 23:28 UTC, IgorMinar commented
Thanks Paul!

2020-01-18 03:37 UTC, IgorMinar commented
this PR fails in g3 in a catastrophic way with build errors due to internal latency lab tests. we'll need to investigate this and fix it next week.

2020-01-18 16:07 UTC, devversion commented
I don't have enough insight, but I'd guess it's because we either changed the file names of the spec files, or since we updated the test library target names (depending on how it is set up in g3)

2020-01-28 23:47 UTC, josephperrott commented
@devversion The change in file names caused the files to be included in a `glob` that they shouldn't have been in.  I created the internal change to prevent them from being included and then we should be able to re-presubmit this and get it merged.

2020-01-29 00:32 UTC, AndrewKushnir commented
I started a [new g3 presubmit](http://test/OCL:292038789:BASE:292038823:1580257804362:f6241609).

@devversion could you plz rebase your PR on top of the latest master, so we rerun CI with the most up-to-date version?

Thank you.

2020-01-29 16:17 UTC, devversion commented
@AndrewKushnir Rebased.

2020-01-29 17:22 UTC, closed without merging