fix(docs-infra): change navigation in resources page
angular/angular pull request #34756
Opened 2020-01-13 18:52 UTC by ajitsinghkaler

https://angular.io/resources needs to be structured to be able to navigate to all resources with improved user experience. A lone scroll bar in this page will not help the reader a great deal in exploring the resources
Fixes #33526

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Earlier there was no navigation available on the resources page 

Issue Number: 33526

## What is the new behavior?
Added navigation to the resources page

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-01-13 18:53 UTC, ajitsinghkaler commented
@gkalpak can you please look into this.

2020-01-14 10:31 UTC, mary-poppins commented
You can preview c771067 at https://pr34756-c771067.ngbuilds.io/.

2020-01-14 11:09 UTC, gkalpak requested changes
Thx, @ajitsinghkaler! This looks great. A couple more tweaks and should be ready to merge (as far as I am concerned).

I think it now also makes sense to center the content under the tabs (because it looks weird to have the tabs centered and the content below left-aligned:

![resources-uncentered](https://user-images.githubusercontent.com/8604205/72339264-a2c1e380-36ce-11ea-884e-f08faadadd4e.png)

##
Note to self:
This should be approved by @fw-docs-marketing too (once ready).

2020-01-14 11:09 UTC, gkalpak commented on aio/src/app/custom-elements/resource/resource-list.component.ts
> +  }
Can you please make this component similar to the [ContributorListComponent][1] (i.e. read/write from/to the URL query string, ignore case of `id`, etc.).

[1]: https://github.com/angular/angular/blob/c7710675e/aio/src/app/custom-elements/contributor/contributor-list.component.ts

2020-01-15 08:24 UTC, ajitsinghkaler commented
@gkalpak should I make the content below center-aligned or should I make it take 100% of the width

2020-01-15 09:11 UTC, gkalpak commented
I would preserve the current width.

2020-01-15 09:48 UTC, mary-poppins commented
You can preview 4a4f67f at https://pr34756-4a4f67f.ngbuilds.io/.

2020-01-15 09:51 UTC, ajitsinghkaler commented
@gkalpak can yo please review this.

2020-01-15 11:45 UTC, gkalpak requested changes
Thx, @ajitsinghkaler :+1: Yes, please, add some tests for the new functionality (i.e. toggling between categories, showing entries from a specific category only and interacting with the URL query).

I have left some comments to do some clean-up (which is not directly related to this PR, but would be awesome if you could do (on a separate commit)).

Other than that, this lgtm (pending the addition of tests) 👍

2020-01-15 11:45 UTC, gkalpak commented on aio/src/app/custom-elements/resource/resource-list.component.html
> +  <div class="flex-center group-buttons">
Thx for fixing the indentation too ❤️

2020-01-15 11:45 UTC, gkalpak commented on aio/src/app/custom-elements/resource/resource-list.component.ts
>      this.location = location.pathname.replace(/^\/+/, '');
Not directly related to this PR, but ?I? just noticed that the `location` property (and thus the `PlatformLocation` dependency) and the `href()` method are not used. If that is the case, could you please create another commit (I would put it before the current commit) cleaning up the component by removing these unused bits? 🙏

2020-01-15 11:45 UTC, gkalpak commented on aio/src/app/custom-elements/resource/resource-list.component.ts
>      this.scrollPos = target ? target.scrollTop || target.body.scrollTop ||  0 : 0;
Not directly related to this PR, but the `scrollPos` property and the `onScroll()` method don't seem to be used. Could you include them in the cleanup commit mentioned in a previous comment?

2020-01-15 14:32 UTC, mary-poppins commented
You can preview 91ea8d6 at https://pr34756-91ea8d6.ngbuilds.io/.

2020-01-15 17:01 UTC, ajitsinghkaler commented
@gkalpak I've added the cleanup please have a look

2020-01-16 17:23 UTC, gkalpak requested changes
The tests are failing, because the injector that is set up for the tests must be updated to provide the necessary dependencies [here][1]. I.e. remove `PlatformLocation` and provide a mock `Location` service (you can use [this one][2]).

<sub>Don't forget to add tests for the new functionality (as mentioned above).</sub>

[1]: https://github.com/angular/angular/blob/91ea8d6f3bb4bb9a2ac77839024f34ca52e03b39/aio/src/app/custom-elements/resource/resource-list.component.spec.ts#L21
[2]: https://github.com/angular/angular/blob/91ea8d6f3bb4bb9a2ac77839024f34ca52e03b39/aio/src/testing/location.service.ts

2020-01-16 17:23 UTC, gkalpak commented on aio/src/app/custom-elements/resource/resource-list.component.ts
>      this.location = location.pathname.replace(/^\/+/, '');
Can you please remove the `location` property (which doesn't seem to be used)?

2020-01-16 17:54 UTC, mary-poppins commented
You can preview 42c2efc at https://pr34756-42c2efc.ngbuilds.io/.

2020-01-16 18:29 UTC, mary-poppins commented
You can preview 111f54d at https://pr34756-111f54d.ngbuilds.io/.

2020-01-16 18:37 UTC, ajitsinghkaler commented
@gkalpak added the tests please have alook

2020-01-17 17:03 UTC, gkalpak requested changes
Almost there :smiley:
I left some minor clean-up suggestions for the tests. Other than that, you just need to get CI green and this is good to go.

2020-01-18 04:24 UTC, mary-poppins commented
You can preview 1a05786 at https://pr34756-1a05786.ngbuilds.io/.

2020-01-18 04:38 UTC, ajitsinghkaler commented
@gkalpak I've made all the changes. @sjtrimble can you please review my pull request

2020-01-18 21:14 UTC, gkalpak approved these changes

2020-01-30 05:48 UTC, sjtrimble approved these changes
Nice!

2020-01-30 09:55 UTC, gkalpak requested changes
I just noticed that the commit messages need some clean up (to follow our [giudelines][1]).
Can you please squash the last two commits into one (so that the PR has overall two commits) and make sure there is a blank line above `Fixes ...` in the second commit message?

[1]: https://github.com/angular/angular/blob/c1cf46c5c/CONTRIBUTING.md#commit

2020-01-30 16:20 UTC, mary-poppins commented
You can preview f7b0233 at https://pr34756-f7b0233.ngbuilds.io/.

2020-01-30 16:46 UTC, ajitsinghkaler commented
@gkalpak made the changes please have a look

2020-01-31 11:50 UTC, gkalpak approved these changes

2020-01-31 16:54 UTC, ajitsinghkaler commented
@gkalpak can you please add the merge label

2020-01-31 19:27 UTC, closed without merging