Bazel sauce labs POC
angular/angular pull request #34769
Opened 2020-01-14 04:22 UTC by gregmagolan

Based of off https://github.com/angular/angular/pull/34765 which should land first

2020-01-15 19:21 UTC, gregmagolan commented
Added cleanup tag to remind me to remove the temporary CircleCI config changes before merging

2020-01-23 21:24 UTC, gregmagolan commented
Since `saucelabs_view_engine` CI job is master-only, a separate PR turns that job on https://github.com/angular/angular/pull/34937 for CI testing.

2020-01-23 21:38 UTC, josephperrott requested changes

2020-01-23 21:38 UTC, josephperrott commented on .circleci/config.yml
> +          name: Preparing environment for running tests on Saucelabs.
We should just move setting this environment variable into the `env.sh` script

2020-01-23 21:38 UTC, josephperrott commented on .circleci/config.yml
> +          name: Starting Saucelabs tunnel service
I think this doesn't need to be `background: true` anymore since the `sauce-service.sh` exits after start now

Additionally, I think we can move this to be after the building of the packages, modules and zone.js

2020-01-23 21:38 UTC, josephperrott commented on BUILD.bazel
> +            "exclusive",
Technically, I think the `no-remote-exec` isn't necessary since `exclusive` will already make it so everything is local and in a serial order.

2020-01-23 21:38 UTC, josephperrott commented on BUILD.bazel
> +sh_library(
Should we move all of these `sh_library`/`sh_binary` targets into something line `/tools/saucelabs`

We can also include a README file there that explains how to use the saucelabs setup?

2020-01-23 21:42 UTC, gregmagolan commented on BUILD.bazel
> +            "exclusive",
Oh. Seems you are correct, although it doesn't hurt to have the redundant tag since you'd have to go to the docs on `exclusive` to determine that.

2020-01-23 21:50 UTC, gregmagolan commented on .circleci/config.yml
> +          name: Starting Saucelabs tunnel service
`./scripts/saucelabs/sauce-service.sh run` is the synchronous command for that script. Just runs the sc and doesn't exit. I had problems with CircleCI closing the process before the next `run` if I used `./scripts/saucelabs/sauce-service.sh start`

2020-01-24 02:27 UTC, gregmagolan commented on BUILD.bazel
> +sh_library(
Done & added the README as well.

2020-01-24 02:34 UTC, gregmagolan commented on .circleci/config.yml
> +          name: Preparing environment for running tests on Saucelabs.
SAUCE_ACCESS_KEY is there but in reverse so it is obfuscated hence the `$(echo $SAUCE_ACCESS_KEY | rev)`. Really it should be set in the CircleCI secret environment variables so that it is not in the code base at all. Who has access to the CircleCI account?

2020-01-24 02:37 UTC, gregmagolan commented on .circleci/config.yml
> +          name: Starting Saucelabs tunnel service
With regards to the order, its done before the build intentionally AFAIK so that the the tunnel is connecting (which can take a bit of time) during build so by the the time `./scripts/saucelabs/sauce-service.sh ready-wait` is called is should be instantaneous. This legacy saucelabs job will go away in a follow up PR as well.

2020-01-24 21:32 UTC, josephperrott commented on tools/saucelabs/README.md
> +Setup your SAUCE_USERNAME, SAUCE_ACCESS_KEY & SAUCE_TUNNEL_IDENTIFIER environment variables. These are required. On OSX, also set SAUCE_CONNECT to the path of your `sc` binary.
can we style the env variables?

Setup your `SAUCE_USERNAME`, `SAUCE_ACCESS_KEY`...

2020-01-24 21:32 UTC, josephperrott commented on tools/saucelabs/README.md
> +To see the test output while the tests are running as these are long tests, add the `--test_output=streamed` option. Note, this option will also prevent bazel from using he test cache and will force
/s/using he test cache/using the test cache

2020-01-24 21:32 UTC, josephperrott commented on tools/saucelabs/README.md
> +The `//tools/saucelabs:sauce_service_setup` target does not start the Sauce Connect proxy but it does start process which will that then listens for the start signal from the service manager script.
There is a double \`\` before `//tools/saucelabs:karama-saucelabs`

2020-01-24 21:32 UTC, josephperrott commented on tools/saucelabs/sauce-service.sh
> +    printf "# Waiting for saucelabs tunnel to connect (${SAUCE_READY_FILE})"
Should this be `@echo "Waiting for saucelabs tunnel to connect (${SAUCE_READY_FILE})"`

2020-01-24 21:38 UTC, gregmagolan commented on tools/saucelabs/README.md
> +Setup your SAUCE_USERNAME, SAUCE_ACCESS_KEY & SAUCE_TUNNEL_IDENTIFIER environment variables. These are required. On OSX, also set SAUCE_CONNECT to the path of your `sc` binary.
👍

2020-01-24 21:38 UTC, gregmagolan commented on tools/saucelabs/README.md
> +To see the test output while the tests are running as these are long tests, add the `--test_output=streamed` option. Note, this option will also prevent bazel from using he test cache and will force
👍

2020-01-24 21:38 UTC, gregmagolan commented on tools/saucelabs/README.md
> +The `//tools/saucelabs:sauce_service_setup` target does not start the Sauce Connect proxy but it does start process which will that then listens for the start signal from the service manager script.
👍

2020-01-24 21:39 UTC, gregmagolan commented on tools/saucelabs/sauce-service.sh
> +    printf "# Waiting for saucelabs tunnel to connect (${SAUCE_READY_FILE})"
Intentional printf so that its followed by ....... on the same line below with `printf "."`

2020-01-27 17:10 UTC, josephperrott approved these changes
LGTM

2020-01-27 17:10 UTC, josephperrott commented on tools/saucelabs/sauce-service.sh
> +  echo "${SAUCE_CONNECT} ${sauce_args[@]} --api-key ${SAUCE_ACCESS_KEY}"
Is this going to echo out the key?

2020-01-27 17:35 UTC, gregmagolan commented on tools/saucelabs/sauce-service.sh
> +  echo "${SAUCE_CONNECT} ${sauce_args[@]} --api-key ${SAUCE_ACCESS_KEY}"
No. `service-command` is echo'ing out into a local variable in the service code
```
local command=$(service-command)
```
This is so that only the thread that actually runs SauceConnect needs the SAUCE_* environment variables set. They are not needed by the shell script in the general case.

Removed that comment there as it was outdated and confusing.

2020-01-27 17:45 UTC, gregmagolan commented on tools/saucelabs/sauce-service.sh
> +  echo "${SAUCE_CONNECT} ${sauce_args[@]} --api-key ${SAUCE_ACCESS_KEY}"
On second thought I'll avoid that pattern and set a SERVICE_COMMAND var in `setup-service-command` instead and I can still echo out the command without the api-key at `setup`.
Cleanup up.

2020-01-28 21:47 UTC, closed without merging