Added a best practices for feature routing
angular/angular pull request #34805
Opened 2020-01-16 06:07 UTC by akilisosa

docs(upgrade): change best practices to add feature routing

Change best practices to include feature routing in the style guide. there is a suggestion in the routing documentation on the best practices but it was not reflected in the style guide. 

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently the angular style guide does not include documentation on best practices for routing. 
There are suggestions that can be found here https://angular.io/guide/router but they are not reflected in the styleGuide. 

Issue Number: N/A

## What is the new behavior?
It includes some basic suggestions for app routing. It states that the app routing module should mirror the app module to reduce clutter in that module, and that it also states that you shouldn't use routerLink='..' because that could lead to an unstable path. 

## Does this PR introduce a breaking change?
This might have a typo. 
- [ ] Yes
- [ x ] No

## Other information 
Its late, if there are typos i am sorry.

2020-01-16 17:55 UTC, kapunahelewong commented
Thank you for this, @akilisosa! While we still need some further reviews from engineering and docs, you'll ultimately want to amend your commit message so that it passes.

Try this:
```
docs: add best practices recommendation for feature routing to style guide
```

Here are my own notes on [amending commit messages](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit). Let me know when you're ready or if you have any questions during the process.

2020-01-16 23:00 UTC, akilisosa commented
Thank you so much @kapunahelewong . This is my first time making a contribution like this so its very exciting! 

When reviewing the documentation, I was navigated to a page called AngularJS git commit message conventions. I was wondering if this is correct or if its suppose to be linked to another document.

2020-02-18 20:59 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +**Do** create an route for all distinct features in an application;
...create **a** route for all distinct features in an application. For example...

(make this two sentences)

2020-02-18 21:00 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +for example, the `crisis-center-routing.module.ts`  helps navitagate through the different views in that feature.
navigate (spelling)

2020-02-18 21:11 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +
**Consider** The complexity of your application. In a larger application, the routing module should mirror your naming conventions and the locations of feature modules.

2020-02-18 21:16 UTC, akilisosa commented on aio/content/guide/styleguide.md
> +for example, the `crisis-center-routing.module.ts`  helps navitagate through the different views in that feature.
Hey @jbogarthyde I am very new to this process. Am I suppose to be making these changes or are you reviewing these and making the changes?

2020-02-18 21:20 UTC, jbogarthyde requested changes
Marked some typos-- and also needs some clarification.

2020-02-18 21:20 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +**Avoid** defining long paths ie. path: 'home/crisis-center/crisis-center-list/crisis-list-detail:3'.
... long paths, such as `path: 'home/crisis-center/crisis-center-list/crisis-list-detail:3'`. 
(use code font for code, no latin abbreviations)

2020-02-18 21:20 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +**Why?** Use of the routing module helps reduce clutter in the root and feature module files.
Ii don't get the context here. Should you avoid long paths IN the routing module? Or do you avoid long paths BY USING the routing module?

2020-02-18 21:20 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +**Do** use routerLink with the specified component name to navigate to different components.
`routerLink` (code font)
 
also, how about a positive example?

2020-02-18 21:20 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +
Didn't you just say you SHOULD use it?

2020-02-18 21:20 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +**Why?**  Specifying the routerLink location helps stabilize navigation.
Is this a reason to use it or avoid it?
(also, `routerLink`)

2020-02-18 21:22 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +for example, the `crisis-center-routing.module.ts`  helps navitagate through the different views in that feature.
Please make the requested changes. If I make changes in your PR, git gets confused about different contributors.

2020-02-19 02:36 UTC, akilisosa commented on aio/content/guide/styleguide.md
> +
I feel like this may have crossed into the ordering thing you were telling me about so that it can all make sense. Do, Avoid, Why. or Do, Why, Avoid.

2020-02-19 02:44 UTC, akilisosa commented on aio/content/guide/styleguide.md
> +**Why?** Use of the routing module helps reduce clutter in the root and feature module files.
I think the confusion may have arose because i was not following Do, avoid, why structure. I am still confused about how to use this properly. 

In my experience it seems like you should just avoid writing long paths in general. It also was commented on a video i was watching that the order in which you define your routes plays a role. I'm not to sure about this, but i know that when i created a bunch of long paths, and used `routerLink='..'` I ran into problems. If this is no longer a problem in Angular 9 please let me know.

2020-02-19 16:40 UTC, mary-poppins commented
You can preview c8a8f87 at https://pr34805-c8a8f87.ngbuilds.io/.

2020-02-19 16:42 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +
effect -> affect

2020-02-19 16:43 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +
For example:

2020-02-19 16:47 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +**Do** use routerLink with the specified component name to navigate to different components.
(still not using code font)
Do you mean "Set `routerLink` to a specific component, rather than a relative path." ?

2020-02-19 16:48 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +
Why? Is this really a best practice, or have you just had trouble with it?

2020-02-19 16:54 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +**Do** Use app routing to define short paths that relate to the components.
Use -> use

2020-02-19 16:55 UTC, akilisosa commented on aio/content/guide/styleguide.md
> +
I don't know. I did not see a relative path used in any of the angular examples, so I think according to the team that developed the examples it is a best practice. The convince of a relative path is great. Maybe I should change **Do** use routerLink with the specified components... to a **Consider**, and remove this line.

2020-02-19 16:56 UTC, jbogarthyde commented on aio/content/guide/styleguide.md
> +**Avoid** The use of the router links to relative paths. `routerLink='..'`
perhaps: 

**Avoid**  using router links to non-specific relative paths (`routerLink='..'` ).

2020-02-20 23:48 UTC, akilisosa commented on aio/content/guide/styleguide.md
> +**Avoid** The use of the router links to relative paths. `routerLink='..'`
I added a **Why** instead of changing the **Do** to a **Consider** .

2020-06-19 02:51 UTC, jelbourn reviewed
Hi @akilisosa, thanks for taking the time to send a PR

I'm not sure the changes proposed here align with recommendations we would want to make. + @mgechev to fact-check me on this

2020-06-19 02:51 UTC, jelbourn commented on aio/content/guide/styleguide.md
> +For example, the `crisis-center-routing.module.ts`  helps navigate through the different views in that feature.
I'm not sure Angular should have an opinion on the information architecture of applications. Ultimately the "best" organization of routes is going to vary from app to app, so it may be better to leave this area unopinionated.

2020-06-19 02:51 UTC, jelbourn commented on aio/content/guide/styleguide.md
> +**Consider** the complexity of your application. In a larger application, the routing module should mirror your naming conventions and the locations of feature modules.
We actually want to move _away_ from having/recommending a routing module based on feedback that it was unnecessarily complicated.

2020-06-19 02:51 UTC, jelbourn commented on aio/content/guide/styleguide.md
> +For example: `path: 'crisis-center' `
Similar to the earlier comment, I'm not sure that Angular should have an opinion about route names themselves.

2020-06-19 02:51 UTC, jelbourn commented on aio/content/guide/styleguide.md
> +**Do** use routerLink with the specified component name to navigate to different components.
I don't know that use of `routerLink` is something that belongs in the style guide, since it's the primary mechanism through with `@angular/router` functions, rather than a style choice / best practice.

2020-06-19 02:51 UTC, jelbourn commented on aio/content/guide/styleguide.md
> +
I don't believe the examples were intended to be normative in this way; I don't know of any strong reason to discourage relative paths.

2020-06-19 20:04 UTC, mgechev commented on aio/content/guide/styleguide.md
> +For example, the `crisis-center-routing.module.ts`  helps navigate through the different views in that feature.
I generally agree that it's application specific. At the same time think it's a good idea to encourage code splitting. Not sure if that's the right way to go.

2020-06-19 20:09 UTC, mgechev commented
I agree with Jeremy. I like some of the ideas, especially around code-splitting. Recently we had a discussion to move away from the routing module recommendation to simplify application structure.

I'd suggest to close the PR, but continue the discussion in a separate issue. See https://github.com/angular/angular/issues/37351

2020-06-19 20:26 UTC, akilisosa commented
This point may have gotten lost in the mix:

The main reason I suggested this pull request was because I was part of a team that developed a large application and used one centralized routing system and relative paths. The behavior became increasingly unstable until I re-organized the project with the use of the routing table.  I don't know if there is still an issue with the keeping all of your paths in one centralized place but it was an issue at the time.

2020-06-19 20:42 UTC, akilisosa commented on aio/content/guide/styleguide.md
> +For example, the `crisis-center-routing.module.ts`  helps navigate through the different views in that feature.
thank you guys for reviewing this. I am still a little new to developing and I am not sure what informational architecture refers to specifically, if it refers to the actual path names, I agree that shouldn't be angular's opinion. 

If it is referring to the folder structure: the angular style guide comments on that when it is talking about FLAT principles - keeping folders with up to 7 items, and how you should just group components together, and change names of things so they are easy to locate. 

I think when I originally proposed this I was considering this as an extension of those thoughts. 

Again I am excited to learn and be participating with you all in this way. Thank you so much.

2020-06-22 16:18 UTC, mgechev commented
@akilisosa IMO, it's worth it to mention the decentralized routing suggestion. If we can shrink the scope, it'll be easier to merge.

2020-06-22 17:30 UTC, akilisosa commented
@mgechev sorry. I think i missed the point of this document, and what I was contributing to. If I was having issues I could have raised an issue with that aspect right? 

Just let me know what you all want me to do, and how to contribute.

2020-06-22 20:34 UTC, jelbourn commented
I think it would be easiest to close this PR, and then open a new issue for discussing any more focused changes you might propose for the style guide. As @mgechev mentioned, there's potentially merit in adding guidance on decentralizing route configuration in some cases.

2020-06-26 12:34 UTC, akilisosa commented
Great! so do click on close and comment and thats it?

2020-06-26 14:20 UTC, jelbourn commented
Yep

2020-06-26 15:53 UTC, closed without merging