fix(ivy): catch FatalDiagnosticError thrown from preanalysis phase
angular/angular pull request #34801
Opened 2020-01-15 22:56 UTC by AndrewKushnir

Component's decorator handler exposes `preanalyze` method to preload async resources (templates, stylesheets). The logic in preanalysis phase may throw `FatalDiagnosticError` errors that contain useful information regarding the origin of the problem. However these errors from preanalysis phase were not intercepted in TraitCompiler, resulting in just error message text be displayed. This commit updates the logic to handle FatalDiagnosticError and transform it before throwing, so that the result diagnostic errors contain the necessary info.

Resolves #34725.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-01-23 23:11 UTC, JoostK requested changes

2020-01-23 23:11 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +            (trait as PendingTrait<unknown, unknown, unknown>).toErrored([err.toDiagnostic()]);
We may be able to avoid the cast here, after a rebase. I recently changed `scanClassForTraits` to return `Trait[]` instead of `ClassRecord`, so we can tighten the return types of `scanClassForTraits` (and `detectTraits`) such that it becomes `PendingTrait<unknown, unknown, unknown>[]`. Then, `analyzeTrait` can be updated to take a `PendingTrait`, allowing the guard in `analyzeTrait` to be dropped.

Hopefully that's all clear, theoretically this all works out :-)

2020-01-23 23:11 UTC, JoostK commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +          expect(diags[0].file !.fileName).toContain('test.ts');
Could you switch this expectation to `toBe(_('/test.ts'))`, with `_` being an import alias for `absoluteFrom`? Also the test below this one.

2020-01-23 23:11 UTC, JoostK commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +          expect(diags[0].length).toBeDefined();
nit: I would personally remove these expectations (and in the test below), as they don't add much confirmation.

2020-01-25 01:04 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +            (trait as PendingTrait<unknown, unknown, unknown>).toErrored([err.toDiagnostic()]);
Thanks @JoostK 👍 I've rebased this PR and applied the necessary changes.

2020-01-25 01:04 UTC, AndrewKushnir commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +          expect(diags[0].file !.fileName).toContain('test.ts');
Done.

2020-01-25 01:06 UTC, AndrewKushnir commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +          expect(diags[0].length).toBeDefined();
Done.

2020-01-25 01:07 UTC, AndrewKushnir commented
Thanks for review @JoostK. I've rebased this PR and applied the necessary changes. Could you please have a look when you get a chance? Thank you.

2020-01-25 02:48 UTC, JoostK approved these changes
LGTM

2020-01-25 03:40 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:291485183:BASE:291485195:1579923586421:2b14876d)

2020-01-27 18:58 UTC, closed without merging