fix(ivy): support @SkipSelf while injecting Injectors
angular/angular pull request #34839
Opened 2020-01-17 20:42 UTC by AndrewKushnir

Prior to this commit, the @SkipSelf flag was not taken into account while handling Injectors in DI. This change adds support for @SkipSelf flag and aligns the behavior with View Engine.

Closes #34819.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-01-17 21:15 UTC, AndrewKushnir commented
Related to https://github.com/angular/angular/pull/34554.

2020-01-17 22:38 UTC, AndrewKushnir commented on integration/_payload-limits.json
> +        "main-es2015": 141985,
I believe this is an accumulated size regression (i.e. not caused specifically by the changes in this PR).

2020-01-24 05:06 UTC, IgorMinar commented on integration/_payload-limits.json
> +        "main-es2015": 141985,
hmm.. ok

2020-01-24 05:08 UTC, IgorMinar approved these changes
lgtm

2020-01-24 14:39 UTC, IgorMinar commented
merge-assistance: global approval

2020-01-27 05:57 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:291656781:BASE:291656800:1580104645768:c20ee630)

2020-02-20 22:07 UTC, kara requested changes

2020-02-20 22:07 UTC, kara commented on packages/core/src/render3/di.ts
> +      // `-1` is a special value used to identify `Injector` types.
Thank you for moving the comment up. More visible this way! :)

2020-02-20 22:07 UTC, kara commented on packages/core/src/render3/di.ts
> +          tNode = tNode.parent || lView[T_HOST] as TDirectiveHostNode;
Good that we are supporting crossing component boundaries, but if we're going to do this, we also need to respect `@Host` config flags. In other words, if you have:

```ts
@SkipSelf() @Host() public vcr: ViewContainerRef 
```

The `ViewContainerRef` should only be found if the parent element is in the same view.

Can we add a test for this as well?

2020-02-21 02:07 UTC, AndrewKushnir commented
@kara thanks for the review! I've added extra logic to take `@Host()` into account. Could you please take another look? Thank you.

2020-02-21 21:13 UTC, kara approved these changes
LGTM

2020-02-21 21:13 UTC, kara commented on aio/scripts/_payload-limits.json
> +        "main-es2015": 450763,
How much of this is accumulation and how much from this PR?

2020-02-21 21:13 UTC, kara commented on packages/core/src/render3/di.ts
> +          const parentInjectorLocation = getParentInjectorLocation(tNode, lView);
Nit: Can you move this line down below the `if (tNode === null)` block? No need to look up the parent injector if we are going to return the not found value.

2020-02-21 22:49 UTC, AndrewKushnir commented on packages/core/src/render3/di.ts
> +          const parentInjectorLocation = getParentInjectorLocation(tNode, lView);
Thanks, updated!

2020-02-21 23:25 UTC, AndrewKushnir commented on aio/scripts/_payload-limits.json
> +        "main-es2015": 450763,
@kara here are the numbers for "main-es2015":
- baseline: 450017
- master: 450469 (**452b** over baseline)
- this branch: 450763 (**294b** over master)

So master on its own is very close to reaching **500b** threshold.

2020-02-22 00:34 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:291656781:BASE:296535856:1582331634314:457bd993)

2020-02-22 00:36 UTC, AndrewKushnir commented
@kara thanks for the review!

I'd like to ask you to have a look at this PR again, since I had to update a bunch of payload limits, which I believe for the most part is an accumulation of payload size increase introduced in other commits merged to master prior to this change, see https://github.com/angular/angular/pull/34839#discussion_r382851840.

Thank you.

2020-02-22 00:41 UTC, kara approved these changes
LGTM

2020-02-26 02:02 UTC, AndrewKushnir commented
Quick update: investigation of g3 failures revealed a couple use-cases that work incorrectly with the changes in this PR due to the `tView` structure implementation that doesn't allow to easily go *up* the chain (in case it's a cross-boundary read). In order to make further progress, some updates to `tView` structure is required. As a pre-requisite to that work, it'd be helpful to land PR #34715 to minimize the number of affected lines of code and avoid dealing with unnecessary tests. I'll clean up #34715 and request a review shortly. Thank you.

2020-10-28 00:43 UTC, AndrewKushnir commented
Closing this PR in favor of #39464.

2020-10-28 00:43 UTC, closed without merging