fix(ngcc): switch ngcc over to use the `TraitCompiler`
angular/angular pull request #34889
Opened 2020-01-21 23:08 UTC by JoostK

fix(ngcc): do not attempt compilation when analysis fails

In #34288, ngtsc was refactored to separate the result of the analysis
and resolve phase for more granular incremental rebuilds. In this model,
any errors in one phase transition the trait into an error state, which
prevents it from being ran through subsequent phases. The ngcc compiler
on the other hand did not adopt this strict error model, which would
cause incomplete metadata—due to errors in earlier phases—to be offered
for compilation that could result in a hard crash.

This commit updates ngcc to take advantage of ngtsc's `TraitCompiler`,
that internally manages all Ivy classes that are part of the
compilation. This effectively replaces ngcc's own `AnalyzedFile` and
`AnalyzedClass` types, together with all of the logic to drive the
`DecoratorHandler`s. All of this is now handled in the `TraitCompiler`,
benefiting from its explicit state transitions of `Trait`s so that the
ngcc crash is a thing of the past.

Fixes #34500
Resolves FW-1788

2020-01-21 23:15 UTC, JoostK commented
This PR is a replacement for #34652, with a different approach. Instead of making use of the `Trait`  types from within ngcc, this change goes one step further to drive the compilation using the `TraitCompiler`. The benefit of this is that the protocol around the calling of `DecoratorHandlers` isn't duplicated between ngtsc and ngcc, with the drawback of introducing a larger diff with more risk involved.

2020-01-22 23:17 UTC, alxhub approved these changes

2020-01-23 08:51 UTC, petebacondarwin requested changes
Nice refactoring! It is great to see so much code removed from ngcc.
Can you add the `NgccTraitCompiler` spec and simplify the `DefaultMigrationHost` spec as mentioned below.
Otherwise LGTM!

2020-01-23 08:51 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/analysis/ngcc_trait_compiler.ts
> +  injectSyntheticDecorator(clazz: ClassDeclaration, decorator: Decorator, flags?: HandlerFlags):
Can you add a jsdoc description of this method since, unlike the `DefaultMigrationHost` it cannot fallback on the decription in the base `MigrationHost` interface. Copying the one from that interface would be fine by me (although that is also missing explanation of the `flags` param!):

```
  /**
   * Associate a new synthesized decorator, which did not appear in the original source, with a
   * given class.
   * @param clazz the class to receive the new decorator.
   * @param decorator the decorator to inject.
   */
   ```

2020-01-23 08:51 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/rendering/dts_renderer.ts
>          }
Consider moving the adding of re-exports outside of the loop:

```ts
decorationAnalyses.forEach(compiledFile => {
  let addReexports = false;
  compiledFile.compiledClasses.forEach(compiledClass => {
    const dtsDeclaration = this.host.getDtsDeclaration(compiledClass.declaration);
    if (dtsDeclaration) {
      const dtsFile = dtsDeclaration.getSourceFile();
      const renderInfo = dtsMap.has(dtsFile) ? dtsMap.get(dtsFile) ! : new DtsRenderInfo();
      renderInfo.classInfo.push({dtsDeclaration, compilation: compiledClass.compilation});
      dtsMap.set(dtsFile, renderInfo);
      // Only add re-exports if the .d.ts tree is overlayed with the .js tree, as re-exports in
      // ngcc are only used to support deep imports into e.g. commonjs code. For a deep import
      // to work, the typing file and JS file must be in parallel trees. This logic will detect
      // the simplest version of this case, which is sufficient to handle most commonjs
      // libraries.
      if (compiledClass.declaration.getSourceFile().fileName === dtsFile.fileName.replace(/\.d\.ts$/, '.js')) {
        addReexports = true;
      }
    }
  });
  if (addReexports) {
    renderInfo.reexports.push(...compiledFile.reexports);
  }
});
```

2020-01-23 08:51 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/analysis/decoration_analyzer_spec.ts
> +        analyzer.handlers.splice(0, analyzer.handlers.length, testHandler);
I know that splice is probably more efficient but since this is just a test, perhaps 

```ts
analyzer.handlers = [...analyzer.handlers, testHandler];
```

is a bit more reasonable?

OOC Can you explain why we cannot just wipe out the standard handlers for this test?

2020-01-23 08:51 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/analysis/decoration_analyzer_spec.ts
> +          analyzer.handlers.splice(0, analyzer.handlers.length, new FakeDecoratorHandler());
```ts
analyzer.handlers = [...analyzer.handlers.length, new FakeDecoratorHandler()];
```

2020-01-23 08:51 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/analysis/migration_host_spec.ts
>    describe('DefaultMigrationHost', () => {
It seems to me that most of this spec file is actually testing the `NgccTraitCompiler`. The `DefaultMigrationHost` mostly just delegates to that.

How about simplifying this spec just to check that the delegation occurs as expected, and then create a spec for `NgccTraitCompiler` that exercises the tests here?

2020-01-23 08:51 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/transform/src/api.ts
>  }
I know this had none before, but some jsdoc descriptions of this interface and its fields would be great!

2020-01-23 08:51 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +
Unecessary extra blank line

2020-01-23 08:51 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +      if (this.reflector.isClass(node)) {
:100:

2020-01-23 08:51 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +    if (!this.reflector.isClass(clazz) || !this.reflector.isClass(original) ||
:+1:

2020-01-23 16:10 UTC, JoostK commented on packages/compiler-cli/ngcc/src/analysis/decoration_analyzer.ts
> +    }
In this case I don't really mind either way. I updated as suggested.

2020-01-23 16:12 UTC, JoostK commented on packages/compiler-cli/ngcc/src/analysis/decoration_analyzer.ts
>      }
Here I do actually prefer the early `continue`, as I usually deal with "edge-cases" with an early control flow statement to keep the main body of work at the top.

2020-01-23 16:18 UTC, JoostK commented on packages/compiler-cli/ngcc/src/analysis/ngcc_trait_compiler.ts
> +  injectSyntheticDecorator(clazz: ClassDeclaration, decorator: Decorator, flags?: HandlerFlags):
Added, including `flags` in both places.

2020-01-23 16:26 UTC, JoostK commented on packages/compiler-cli/ngcc/src/rendering/dts_renderer.ts
>          }
That is indeed much nicer but when I applied this change I noticed that `renderInfo` is only available in the loop. I tried to introduce

```ts
      let dtsRenderInfo: DtsRenderInfo|null = null;
```

instead of `addReexports` to capture the render info, but then you'd need to workaround a TS limitation where it doesn't recognize that `dtsRenderInfo` could have been reassigned within the closure, so it would narrow `dtsRenderInfo` to `never` after a `dtsRenderInfo !== null`. At that point I don't think the readability is better than what it currently is, so I kept it unchanged.

2020-01-23 16:36 UTC, JoostK commented on packages/compiler-cli/ngcc/test/analysis/decoration_analyzer_spec.ts
> +        analyzer.handlers.splice(0, analyzer.handlers.length, testHandler);
Oooh, so this is actually trickier than it looks (and perhaps even trickier than it should be, honestly). The `analyze.handlers` is passed into the `NgccTraitCompiler` and is shared through the array reference. Replacing the array would therefore not make the new handlers available to the trait compiler.

If I just append/prepend the handler some tests start to fail, hence the `slice`.

2020-01-23 17:09 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/analysis/decoration_analyzer_spec.ts
> +        analyzer.handlers.splice(0, analyzer.handlers.length, testHandler);
Oh! I forgot that the second parameter is the `delete`, which means that my suggestion is incorrect.
Perhaps a comment in the code to stop people like me from worrying about it?

2020-01-23 17:30 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/transform/src/api.ts
>  }
Added some

2020-01-23 18:44 UTC, JoostK commented on packages/compiler-cli/ngcc/test/analysis/migration_host_spec.ts
>    describe('DefaultMigrationHost', () => {
I'm really not fond of testing just delegation behaviour, as doing so starts to be testing an implementation rather than some desired behaviour. I do see however where you're coming from here, and have moved most of the `injectSyntheticDecorator` and `getAllDecorators` tests to an `NgccTraitCompiler` spec file, while retaining some in the `DefaultMigrationHost` specs to test the logic in the context of the migration host.

2020-01-23 20:18 UTC, JoostK commented
This is green on CI: angular/ngcc-validation#792

@petebacondarwin PTAL

2020-01-23 21:35 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/analysis/decoration_analyzer.ts
>      }
As you like 😄

2020-01-23 21:38 UTC, petebacondarwin approved these changes
Grand!

2020-01-23 21:47 UTC, JoostK commented
merge-assistence: Alex has approved on behalf of fw-compiler when it was still draft.

2020-01-23 21:50 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:291236444:BASE:291236504:1579816192037:1b275da2)

2020-01-23 22:47 UTC, closed without merging