docs: add sidenav to renderer to renderer2 migration guide
angular/angular pull request #34979
Opened 2020-01-26 18:35 UTC by ajitsinghkaler

In docs, we cannot have right side nav if something is not added to the left side nav so as a workaround added migration of renderer to renderer2 migration guide to left nav with hidden: true so that it is not shown in the left nav

Fixes #33582

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

No navigation in migration of renderer to renderer 2

Issue Number: :33582

## What is the new behavior?
Navigation available in the migration guide

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-01-27 09:59 UTC, gkalpak reviewed
What about other migration docs? It might make sense to group them all together.

2020-01-27 16:46 UTC, ajitsinghkaler commented
@gkalpak how can I find all the migration guides

I agree we can create a tab in the side panel for migration guides.

@kapunahelewong do we have a list of all the migration guides

2020-01-27 18:28 UTC, gkalpak commented
> @gkalpak how can I find all the migration guides

No, idea :grin:
I am sure @kapunahelewong knows more on that one :wink:

> I agree we can create a tab in the side panel for migration guides.

Just to be clear, I am suggesting keeping them `hidden`, but yeah, it would make sense to have them all in one group in the sidenav.

2020-01-28 18:04 UTC, kapunahelewong commented
We did discuss having them in the nav or not, with @IgorMinar and @kara recommending that they stay out and remain links from `deprecations.md`. The thought was that as we move forward through versions that deprecations would naturally grow yet become less relevant as time passed, which would in turn necessitate frequent changing of the left nav. Does that help clarify, @ajitsinghkaler?

2020-01-28 18:20 UTC, ajitsinghkaler commented
Thanks @kapunahelewong once you rename them should we add all of them to the sidenav with hidden true directive this will make the right side nav available for them and left sidenav will also not keep changing continously

2020-01-28 19:25 UTC, kapunahelewong commented
@ajitsinghkaler, I mean as I created them I named them with `migration-` to begin with (but I think there are a couple that I missed/were there already). I try not to rename files to avoid redirects. Regarding adding them as hidden so they will get the right hand TOC sounds like a great idea.

2020-01-29 18:39 UTC, ajitsinghkaler commented
@gkalpak @kapunahelewong made the changes please have a look

2020-01-29 20:06 UTC, mary-poppins commented
You can preview 0f5dc5e at https://pr34979-0f5dc5e.ngbuilds.io/.

2020-01-29 20:55 UTC, gkalpak commented
@ajitsinghkaler, can you please make CI green?

2020-01-30 16:24 UTC, mary-poppins commented
You can preview 4c28408 at https://pr34979-4c28408.ngbuilds.io/.

2020-01-30 16:37 UTC, mary-poppins commented
You can preview 95eefa1 at https://pr34979-95eefa1.ngbuilds.io/.

2020-01-30 17:00 UTC, ajitsinghkaler commented
@gkalpak made the changes please have a look

2020-01-31 11:49 UTC, gkalpak approved these changes
Thx, @ajitsinghkaler! Please change the commit message to reflect the fact that all migration guides are added to the sidenav; e.g.:

> docs: add sidenav and ToC for all migration guides
>
> ...

2020-01-31 16:52 UTC, aikithoughts requested changes
As this content is really part of the updating process, can we move the TOC entries to child elements under the Updating to Version 9 (line 706, I think?)

Also, I don't think these topics should be hidden. If they're important enough to publish, they're important enough to ensure that users can find them. And, when they do find them, they should be able to navigate back to other topics easily (without using the back button. :) )

2020-01-31 16:59 UTC, ajitsinghkaler commented
@aikidave @kapunahelewong already discussed it with @IgorMinar @kara https://github.com/angular/angular/pull/34979#issuecomment-579379393

they told us we cannot put them In the side nav.

And all of this content is not really updating to version 9 some of them are just in general migration guides for earlier versions too

2020-01-31 17:10 UTC, aikidave commented
> @aikidave @kapunahelewong already discussed it with @IgorMinar @kara [#34979 (comment)](https://github.com/angular/angular/pull/34979#issuecomment-579379393)
> 
> they told us we cannot put them In the side nav.
> 
> And all of this content is not really updating to version 9 some of them are just in general migration guides for earlier versions too

I'm happy to discuss this with folks, and I'm certainly willing to have my mind changed. But I don't think the solution "temporary" topics is to publish them but not let anyone know that they exist save through a direct link. I don't think it's hard to review content and decide that it's no longer relevant. It happens all the time. :)

I'm new to Angular, so I'll defer to you regarding whether this content is relevant to other updates. But, even so, our docs only talk about updating to version 9, so it still makes sense for this content to exist under that topic.

2020-01-31 17:15 UTC, ajitsinghkaler commented
> > @aikidave @kapunahelewong already discussed it with @IgorMinar @kara [#34979 (comment)](https://github.com/angular/angular/pull/34979#issuecomment-579379393)
> > they told us we cannot put them In the side nav.
> > And all of this content is not really updating to version 9 some of them are just in general migration guides for earlier versions too
> 
> I'm happy to discuss this with folks, and I'm certainly willing to have my mind changed. But I don't think the solution "temporary" topics is to publish them but not let anyone know that they exist save through a direct link. I don't think it's hard to review content and decide that it's no longer relevant. It happens all the time. :)
> 
> I'm new to Angular, so I'll defer to you regarding whether this content is relevant to other updates. But, even so, our docs only talk about updating to version 9, so it still makes sense for this content to exist under that topic.

Can you please talk to them about this I already proposed to put it in the side nav. As we have no links to reach these migration guides.

2020-01-31 17:16 UTC, kapunahelewong commented
@ajitsinghkaler, yes, that was the context/history of the decision to have them not in the nav, but since then @aikidave has joined as our docs team lead, so I'll have to defer to him. This PR got the docs team really talking about the concept of hidden nav entries, so thank you very much for bringing it up. Going forward, we can follow @aikidave's lead. :)

2020-01-31 17:35 UTC, ajitsinghkaler commented
thanks for clearing it out I'll make the changes and push it.

2020-01-31 17:36 UTC, aikidave commented
Thanks, @ajitsinghkaler! I am sorry I didn't think to introduce myself, and I should have! Really appreciate your contributions!

2020-01-31 19:52 UTC, ajitsinghkaler commented
No problem @aikidave we are all trying to improve angular at the end of the day. 

I've also made the changes you can have a look

2020-01-31 19:56 UTC, mary-poppins commented
You can preview d003181 at https://pr34979-d003181.ngbuilds.io/.

2020-02-04 14:13 UTC, ajitsinghkaler commented
@aikidave can you please review this

2020-02-04 17:39 UTC, aikithoughts requested changes

2020-02-04 17:39 UTC, aikidave commented on aio/content/navigation.json
> +              "title": "General Version 9 update Guide",
Let's call this "Overview" instead of "General Version 9 update Guide"

2020-02-04 17:39 UTC, aikidave commented on aio/content/navigation.json
> +              "url": "guide/migration-renderer",
I would put all of these under one heading:

"Migration details"

Then, for each child element, you can shorten the TOC title to remove "migration". So

Renderer to Renderer2 migration

becomes

Renderer to Renderer2

Note: We shouldn't change the topic titles--this is just in the TOC.

This change should help make sure folks know that these details aren't necessary for every migration.

2020-02-04 18:47 UTC, kara requested changes
@aikidave Can we discuss the nav more offline? I think it's a bit odd to give migration guides top billing, but ignore other guides that are more important like the Ivy compatibility guide. These migration guides are more like FYIs, so it makes more sense to me to keep the main "updating to version 9" page as the central page that links out to others.

2020-02-04 19:13 UTC, kara reviewed
@aikidave and I synced on the reasons behind the nav, so I'm also good on having it once the below changes are made.

2020-02-04 19:13 UTC, kara commented on aio/content/navigation.json
> +              "url": "guide/migration-renderer",
Yeah, totally agree

2020-02-04 19:13 UTC, kara commented on aio/content/navigation.json
> +              "title": "General Version 9 update Guide",
+1

2020-02-04 19:13 UTC, kara commented on aio/content/navigation.json
> +            },
Can we also add a link to the Ivy compatibility guide on top of the migration folder?

2020-02-05 03:58 UTC, ajitsinghkaler commented
@aikidave saw you started working on this. Should I still resolve all the comments by you or not?

Should I continue to work on this or you will be working on this?

2020-02-05 05:20 UTC, aikidave commented
@ajitsinghkaler I'm glad you saw that I started working on this! It got a little crazy. I was working with @kara about how to best add the migration guides to the table of contents, and things sort of escalated. 

We think the right thing to do is to add the guides as you can see in #35145. But, to do that, we also have to update the SCSS so we can support 4 levels in the table of contents.

Would you like to continue working on this? If so, you'd just need to replicate what I've been doing in #35145. I'm also happy to continue working on this if you'd rather tackle something else. Let me know--I'm good either way, although I admit I'm not sure if folks will be okay with my SCSS changes. :)

2020-02-05 16:26 UTC, ajitsinghkaler commented
@aikidave I can complete this no problem

2020-02-05 16:40 UTC, aikidave commented
Sounds good. Do you want me to push my changes to your PR? I think @kapunahelewong showed me how to do that.

There's still some debate on the best way to present this information to users. I'll see if I can get that sorted out today.

2020-02-05 16:43 UTC, ajitsinghkaler commented
okay push your changes I'll squash our commits

2020-02-05 18:48 UTC, aikidave commented
@ajitsinghkaler , I've pushed my changes to your branch. Please make sure to review my PR (#35145)  in case there are any additional comments that we should address.

2020-02-05 18:51 UTC, ajitsinghkaler commented
okay @aikidave update me if anything finalizes regarding this

2020-02-05 18:54 UTC, mary-poppins commented
You can preview ffb3b45 at https://pr34979-ffb3b45.ngbuilds.io/.

2020-02-06 04:07 UTC, ajitsinghkaler commented
@akidave I propose new headings in the navigation

Optional v9 migration details-> Optional v9 migration
Missing @Injectable() Decorators->@Injectable() Decorators or @Injectable it as apparent that it is a decorator as it used decorator syntax
$localize Global Import->$localize
Missing ModuleWithProviders Generic-> ModuleWithProviders
@Directive()/@Component() Decorators-> @Directive()/@Component()

This will make our headings quite small without compromising on the information given out by these headings

2020-02-09 03:47 UTC, ajitsinghkaler commented
@aikidave @kara Can you please review this again

2020-02-10 17:13 UTC, aikidave commented
@ajitsinghkaler , it looks like you might need to rebase. That should take care of the preview issue.

2020-02-10 17:41 UTC, mary-poppins commented
You can preview d39766a at https://pr34979-d39766a.ngbuilds.io/.

2020-02-10 17:43 UTC, ajitsinghkaler commented
@aikidave the preview is generated can you look at the pr now

2020-02-10 18:13 UTC, aikithoughts approved these changes
Looks fine to me. Should have @kara take a look as well to be sure.

2020-02-10 18:16 UTC, ajitsinghkaler commented
@kara can you please review this

2020-02-16 16:08 UTC, ajitsinghkaler commented
@kara @aikidave its been a week can you please review this

2020-02-18 00:07 UTC, aikithoughts approved these changes

2020-02-21 18:33 UTC, ajitsinghkaler commented
@kara can you please review this

2020-02-26 00:21 UTC, kara reviewed
A few more tiny things

2020-02-26 00:21 UTC, kara commented on aio/content/navigation.json
> +                  "title": "@Directive() /@Component() Decorators",
Might simplify to:

```suggestion
                  "title": "Missing @Directive() Decorators",
```

2020-02-26 00:21 UTC, kara commented on aio/angular.json
> +    }
Revert? Unrelated to your change.

2020-02-26 00:21 UTC, kara commented on aio/content/navigation.json
> +                  "tooltip": "Migration to remove unnecessary`static: false` flag from @ViewChild and @ContentChild queries."
```suggestion
                  "tooltip": "Migration to remove unnecessary `static: false` flag from @ViewChild and @ContentChild queries."
```

2020-02-26 18:25 UTC, ajitsinghkaler commented
@kara made the changes please have a look

2020-02-26 18:31 UTC, mary-poppins commented
You can preview e44f8c8 at https://pr34979-e44f8c8.ngbuilds.io/.

2020-03-04 08:43 UTC, ajitsinghkaler commented
@kara can you please review this

2020-03-11 02:35 UTC, ajitsinghkaler commented
@kara can you please review this

2020-03-23 14:35 UTC, ajitsinghkaler commented
@kara can you please review this.

2020-04-04 08:04 UTC, ajitsinghkaler commented
@kara can you please review

2020-04-08 07:49 UTC, ajitsinghkaler commented
@kara @IgorMinar can you please review this

2020-04-13 15:55 UTC, ajitsinghkaler commented
@IgorMinar @kara can you please review this

2020-04-19 17:10 UTC, ajitsinghkaler commented
@IgorMinar @kara can you please review this

2020-05-05 18:05 UTC, ajitsinghkaler commented
@kara @IgorMinar can you please have a look

2020-05-07 19:06 UTC, kara approved these changes
LGTM once caps are fixed

2020-05-07 19:06 UTC, kara commented on aio/content/navigation.json
> +              "title": "Optional v9 migration details",
```suggestion
              "title": "Optional v9 Migration Details",
```

2020-05-07 20:06 UTC, ajitsinghkaler commented
@kara made the changes

2020-05-08 05:02 UTC, ajitsinghkaler commented
I just messed up rebasing please ignore it was a rebased a long time ago. Ignore if any review request sent to you

2020-05-08 05:09 UTC, mary-poppins commented
You can preview 18b3efb at https://pr34979-18b3efb.ngbuilds.io/.

2020-05-08 05:18 UTC, ajitsinghkaler commented
The final typo was also resolved @kara @aikidave I think we can add the merge label

2020-05-08 16:38 UTC, IgorMinar approved these changes
One small tweak requested but otherwise lgtm.

2020-05-08 16:38 UTC, IgorMinar commented on aio/content/navigation.json
> +              "title": "Optional v9 Migration Details",
Could you please make this shorter so that it doesn't wrap on narrow screens? How about just  "Optional Migrations"?

2020-05-08 16:53 UTC, mary-poppins commented
You can preview f45d9e9 at https://pr34979-f45d9e9.ngbuilds.io/.

2020-05-08 17:12 UTC, ajitsinghkaler commented
@IgorMinar you can remove the cleanup label

2020-05-08 17:17 UTC, IgorMinar commented
Thanks @ajitsinghkaler !

2020-05-08 21:45 UTC, closed without merging