feat(docs-infra): add stable to the list of api statuses
angular/angular pull request #34981
Opened 2020-01-26 19:46 UTC by ajitsinghkaler

Earlier api can be filtered based on security risk and deprecated now added stable as a status for better user experience

Fixes #30396

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Earlier only api can be filtered based on deprecated and security
Issue Number: #30396
## What is the new behavior?
Api can be filtered using stable also

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-01-27 09:58 UTC, gkalpak requested changes
Thx, @ajitsinghkaler! Can you also add some tests for the new feature?

2020-01-27 09:58 UTC, gkalpak commented on aio/src/app/custom-elements/api/api-list.component.ts
> +      status === 'all' || status === item.stability || (status === 'security-risk' && item.securityRisk) ||  (status === item.stability && !item.securityRisk);
The last condition seems superfluous, since the earlier `status === item.stability` would have matched already.

2020-01-27 17:04 UTC, ajitsinghkaler commented on aio/src/app/custom-elements/api/api-list.component.ts
> +      status === 'all' || status === item.stability || (status === 'security-risk' && item.securityRisk) ||  (status === item.stability && !item.securityRisk);
I added the last one so that the security risk ones does not mix with the stable ones but you are right this condition is not right.

@gkalpak need your views on this should we add security risk items to the stable filter

2020-01-27 17:13 UTC, ajitsinghkaler commented on aio/src/app/custom-elements/api/api-list.component.ts
> +      status === 'all' || status === item.stability || (status === 'security-risk' && item.securityRisk) ||  (status === item.stability && !item.securityRisk);
@gkalpak and tests have already been added on line 82-85 it was just that the menu item needed to be added.

If we remove security risk from the stable API then the tests need to be updated otherwise these seem enough to me please have a look at the tests and tell me if any other tests are needed

2020-02-04 18:35 UTC, mary-poppins commented
You can preview f013be0 at https://pr34981-f013be0.ngbuilds.io/.

2020-02-04 18:44 UTC, gkalpak commented on aio/src/app/custom-elements/api/api-list.component.ts
> +      status === 'all' || status === item.stability || (status === 'security-risk' && item.securityRisk) ||  (status === item.stability && !item.securityRisk);
Yes, security risk is orthogonal to stability, so `stable` should include `securityRisk` items as well. I.e. the condition should remain: `status === 'all' || status === item.stability || (status === 'security-risk' && item.securityRisk)`

Fair enough about the tests. Ideally we should have e2e tests covering this feature, but we don't 😅.
(If you want to add some e2e tests, I won't stop you, but it isn't required for this PR :grin:)

2020-02-04 19:31 UTC, ajitsinghkaler commented
@gkalpak made the changes I'll add e2e tests later will make a new issue for that

2020-02-04 19:40 UTC, mary-poppins commented
You can preview 722132c at https://pr34981-722132c.ngbuilds.io/.

2020-02-04 21:05 UTC, gkalpak approved these changes

2020-02-04 23:57 UTC, closed without merging