docs: applied a much straight forward sentence
angular/angular pull request #35002
Opened 2020-01-28 12:06 UTC by jrumandal

To understand the current sentence it requires to read it multiple times. This fix should help developers to understand the sentence in a quicker way.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Displays the updated paragraph

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-01-28 12:11 UTC, petebacondarwin approved these changes

2020-01-28 19:52 UTC, jbogarthyde requested changes
We can make this even more straight-forward :-)

2020-01-28 19:52 UTC, jbogarthyde commented on aio/content/guide/singleton-services.md
> +* Set `root` as value in the `@Injectable()`'s `providedIn`' property
I suggest :
Set the `providedIn` property of the `@Injectable()` to `root`.

2020-02-26 00:38 UTC, kara commented on aio/content/guide/singleton-services.md
> +* Set `root` as value in the `@Injectable()`'s `providedIn`' property
+1 to this

2020-02-26 05:24 UTC, mhevery approved these changes

2020-02-27 19:00 UTC, atscott commented
Hi @jrumandal, can you rebase your PR so that it can be merged and also squash the two commits into one with the message being something like "docs: reword explanation for using singleton services to be more understandable" or something similar?

2020-02-27 21:18 UTC, jrumandal commented
> Hi @jrumandal, can you rebase your PR so that it can be merged and also squash the two commits into one with the message being something like "docs: reword explanation for using singleton services to be more understandable" or something similar?

Hi, is that okay? :)

2020-02-27 21:51 UTC, atscott commented
@jrumandal - commit looks good now, thank you! In order to merge, you also need to rebase with master. You can find the directions for this in the note at the end of the CI failure in the setup step:

>Rebase instructions for PR Author, please run the following commands:
> git fetch upstream master;
> git checkout patch-7;
> git rebase upstream/master;
> git push --force-with-lease;

2020-02-29 00:39 UTC, jrumandal commented
@atscott  Done ^^

2020-03-02 17:31 UTC, closed without merging