ci: minor PullApprove fixes/improvements
angular/angular pull request #35015
Opened 2020-01-28 20:56 UTC by gkalpak

This is a follow-up to #34814 to fix some typos in patterns and make them more similar to the old patterns from `.github/CODEOWNERS`.

2020-01-28 22:23 UTC, devversion approved these changes
LGTM. One comment proposal, and a question.

2020-01-28 22:23 UTC, devversion commented on scripts/github/merge-pr
> +REQUIRED_BASE_SHA_PATCH="110f6c91b904819cab639861b54b6a989e176942"  # CODEOWNERS => PullApprove migration
Out of curiosity: @josephperrott mentioned in #fw-caretaker that pullapprove walks through PRs in the backlog to assign revieweers. Does that mean that we don't need to bump the SHA here? I could see the script incorrectly blocking old PRs that have been updated by pullapprove?

2020-01-28 22:23 UTC, devversion commented on .pullapprove.yml
> +#  Used for approving minor changes, large-scale refactorings, and emergency situations.
```suggestion
#  Used for approving minor changes, large-scale refactorings, and in emergency situations.
```

2020-01-29 10:30 UTC, gkalpak commented on scripts/github/merge-pr
> +REQUIRED_BASE_SHA_PATCH="110f6c91b904819cab639861b54b6a989e176942"  # CODEOWNERS => PullApprove migration
Not sure either, so I opted to err on the side of caution :grin:

For example, this super old PR, #23015, still has no PullApprove status, so not sure what PullApprove is doing. Or maybe in these cases the PR will be on CODEOWNERS, so they will have the necessary reviews requested.

@josephperrott, wdyt?

2020-01-29 15:16 UTC, josephperrott commented on scripts/github/merge-pr
> +REQUIRED_BASE_SHA_PATCH="110f6c91b904819cab639861b54b6a989e176942"  # CODEOWNERS => PullApprove migration
After talking with PullApprove a bit, it looks like only the most recent 200 are immediately processed when the config changes.  We should include this required base update.

2020-01-29 16:47 UTC, josephperrott requested changes
Can you also remove the `fw-cli-integration` group as its glob does not match any files in the repo.

2020-01-29 16:47 UTC, josephperrott commented on .pullapprove.yml
> +          '**/*.bzl',
Can you also:
**remove:**
  - `.buildkite/**`

**change:**
  - `tools/public_api_guard/BUILD` -> `tools/public_api_guard/BUILD.bazel`
  - `**/*.BAZEL` -> `**/*.bazel`

**add:**
  - `.yarn/**`
  - `tools/brotli-cli/**`
  - `tools/browsers/**`
  - `tools/circular_dependency_test/**`
  - `tools/ng_rollup_bundle/**`
  - `tools/saucelabs/**`

2020-01-29 18:39 UTC, IgorMinar approved these changes
lgtm after cleanup. thanks for all these fixes George!

2020-01-29 18:39 UTC, IgorMinar commented on .pullapprove.yml
> +          '**/*.bzl',
all of this SGTM

2020-01-29 18:39 UTC, IgorMinar commented on .pullapprove.yml
> +          'tools/components-repo-ci/**'
ah! good catch.

2020-01-29 18:39 UTC, IgorMinar commented on scripts/github/merge-pr
> +REQUIRED_BASE_SHA_PATCH="110f6c91b904819cab639861b54b6a989e176942"  # CODEOWNERS => PullApprove migration
this change is sooooo ironic :-D

2020-01-29 19:15 UTC, gkalpak commented on .pullapprove.yml
> +          '**/*.bzl',
Done.

2020-01-29 19:40 UTC, josephperrott approved these changes
LGTM

2020-01-29 20:23 UTC, closed without merging