feat: support jest
angular/angular pull request #35080
Opened 2020-01-31 15:06 UTC by JiaLiPassion

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

add basic support for jest, basically the functionality is the same as https://github.com/thymikee/jest-preset-angular/tree/master/src/zone-patch, and I move it here to easily share function with `jasmine/mocha` patch, and also I would like to add support for `jest faketimer` integration with `fakeAsync`. So jest-preset-angular can only care about the `jest` part.
I have discussed with the owner of `jest-preset-angular` in this PR https://github.com/thymikee/jest-preset-angular/pull/340.

This PR will add the basic support, and I will add the `fakeTimer` support in the following up PRs.

2020-01-31 20:06 UTC, mhevery requested changes
- Can we add some tests to show that this works?
- This needs some documentations so that our users can discover and use the feature.

2020-02-05 04:27 UTC, JiaLiPassion commented
@mhevery, Thanks for the review.

1. I added the test cases for zone jest patch.
2. I also tested this patch integration with angular in some sample app, because to integrate with angular, we still need `jest-preset-angular`, so I need this PR to be merged first, then I will go to 
the `jest-preset-angular` repo to remove zone-patch there. After that, I will add angular sample app test in angular repo.
3. because the above reason (need to also update jest-preset-angular), I will update the doc after that.

2020-02-05 18:55 UTC, mhevery approved these changes

2020-02-05 18:55 UTC, mhevery commented on packages/zone.js/lib/jasmine/jasmine.ts
> -      //     fakeAsync behavior to the childZone.
Did you intent do delete this line? Seems like a mistake?

2020-02-05 18:55 UTC, mhevery commented on packages/zone.js/lib/jest/jest.ts
> +  if (jest['__zone_patch__']) {
how do you feel about combining the two early bail outs into one if with an `||`?

2020-02-05 18:55 UTC, mhevery commented on packages/zone.js/lib/jest/jest.ts
> +    // Note we have to make a function with correct number of arguments, otherwise jasmine will
```suggestion
    // Note we have to make a function with correct number of arguments, otherwise jest will
```

2020-02-05 22:40 UTC, JiaLiPassion commented on packages/zone.js/lib/jasmine/jasmine.ts
> -      //     fakeAsync behavior to the childZone.
Thanks, this line should be kept.

2020-02-05 22:41 UTC, JiaLiPassion commented on packages/zone.js/lib/jest/jest.ts
> +  if (jest['__zone_patch__']) {
Sure, updated, thanks.

2020-02-05 22:42 UTC, JiaLiPassion commented on packages/zone.js/lib/jest/jest.ts
> +    // Note we have to make a function with correct number of arguments, otherwise jasmine will
Updated, thanks.

2020-02-06 23:20 UTC, mhevery commented
[presubmit](http://test/OCL:293689274:BASE:293689298:1581031239751:43868d63)

2020-02-07 19:43 UTC, closed without merging