feat(language-service): provide completions for microsyntax
angular/angular pull request #35096
Opened 2020-02-01 10:47 UTC by ivanwonder

Provide completions for microsyntax, for example, `ngFor` completions will include `of`, `trackBy`, etc. `ngIf` completions will include `then`, `else`.
```
*ngFor="let item of items; | ;"
```
Here provide template context(`index`, `odd`, etc.) and directive input property(`of`, `trackBy`, etc.).
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-02-03 17:40 UTC, ayazhafiz requested changes
Great feature! I'm excited for this one )

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +        }
I think we use this pattern in several other places in the LS. we don't have to do it in this PR, but should consider a util function

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +        this.addStructuralDirectiveInputToCompletions(ast, directiveMetadata);
nit: change to `addTemplateContextCompletions` and `addDirectiveInputCompletions` for brevity

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
>        const binding = templateBindings.find(b => inSpan(valueRelativePosition, b.span));
Can you move this down to line 482 since there is now the large block to find the directive?

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +    const bindingSource = attr.value.substring(binding.span.start, binding.span.end);
can we do `toString` on the binding? I wouldn't be surprised if we can't, just wondering..

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +    const bindingSource = attr.value.substring(binding.span.start, binding.span.end);
consider calling `trim` on the construction of the source here instead of on the next line

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +        // members of the template reference's type parameter.
```suggestion
        // members of the directive's template context.
```

would you mind changing this while you're here? i think the original comment obscures what we're trying to do.

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +        // so provide template context and directive input property in here.
This doesn't happen only if we are before a semicolon, just if we're at the end of the binding right? Consider rewording the comment to something like `We are at the end of the binding span, so...`. Please correct me if I'm wrong.

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +      // The binding expression should be null,
What do you mean by should be null? Wouldn't this branch be hit if the binding name wasn't implicit or we were before the end of the binding as well?

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +      if (binding.key && binding.name === '$implicit' && endOfSyntax) {
```suggestion
      else if (binding.key && binding.name === '$implicit' && endOfSyntax) {
```

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +      const expressionExist =
```suggestion
      const expressionExists =
```

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +      // The 'of' have no span, so get it here.
```suggestion
      // The 'of' has no span, so get it here.
```

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +          // The template context should be provided here because of 'index as i'.
I am confused by this comment. Can you elaborate? How is this different from the branch on line 581?

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +      if (attr.value.substring(valueRelativePosition, binding.span.end).indexOf(':') === -1) {
I wonder if there is a way to rearrange these branches so that it is more clear that this is the only option if `:` is not found in the binding. I will think about it a little bit more; it is not a big deal.

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +  // Add the structural directive's template context(e.g. 'ngFor' has 'index', 'odd', etc.) to
```suggestion
  // Add the structural directive's template context (e.g. 'ngFor' has 'index', 'odd', etc.) to
```

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +      const _input = input.substring(key.length);
```suggestion
      const unprefixedInput = input.substring(key.length);
```

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +        const _inputInsert = _input[0].toLowerCase() + _input.substring(1);
```suggestion
        const inputName = _input[0].toLowerCase() + _input.substring(1);
```

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +      const _input = input.substring(key.length);
Consider also adding an example (`ngForTrackBy` -> `trackBy`). This is one of the most magical things in the compiler and can be kind of confusing.

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/test/completions_spec.ts
> +          `<div *ngFor="let x	~{cursor-one}; of heroes ~{cursor-two}; tr~{cursor-three};"></div>`);
For cursor-three, it looks like we also want to see `trackBy`. Is that correct?

2020-02-03 17:40 UTC, ayazhafiz commented on packages/language-service/test/completions_spec.ts
> +      expect(completions).toBeUndefined();
:+1:

2020-02-04 02:26 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +      // The binding expression should be null,
`*ngFor="let x of item; tr| ;"`
the templateBindings is
```
span: ParseSpan {start: 20, end: 22}
key: "*ngForTr"
keyIsVar: false
name: null
expression: ASTWithSource
  span: ParseSpan {start: 0, end: 0}
  sourceSpan: AbsoluteSourceSpan {start: 35, end: 35}
  ast: EmptyExpr {span: ParseSpan, sourceSpan: AbsoluteSourceSpan}
  source: ""
  location: "let x	; of heroes ; tr;"
  errors: (2) [ParserError, ParserError]
```
`*ngFor="let x of item; tr| "`
If remove the `;`, the templateBindings is
```
span: ParseSpan {start: 20, end: 22}
key: "*ngForTr"
keyIsVar: false
name: null
expression: null
```
Before this PR,  it only check `binding.expression && inSpan()`.

2020-02-04 02:37 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +          // The template context should be provided here because of 'index as i'.
`*ngFor="let item of items; trackBy| ;"`
If the cursor is here, there are two conditions, one is `index as i`, another is `trackBy: myTrack`.
And the expression doesn't exist here or is null, so I will provide `index` or `trackBy`. 
`*ngFor="let item of items; trackBy| : myTrack ;"`
Now the expression exists, it's `myTrack`, I only provide `trackBy`, `of`, etc.

2020-02-04 02:47 UTC, ivanwonder commented on packages/language-service/test/completions_spec.ts
> +          `<div *ngFor="let x	~{cursor-one}; of heroes ~{cursor-two}; tr~{cursor-three};"></div>`);
Yes, here I only list `of` to represent the directive input and  `index` to represent template context.
Need to list all of them?

2020-02-04 03:00 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +    const bindingSource = attr.value.substring(binding.span.start, binding.span.end);
return [object object]....

2020-02-04 03:11 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +      if (attr.value.substring(valueRelativePosition, binding.span.end).indexOf(':') === -1) {
In this branch, there are only three conditions, in directive input name, in expression, and after the `:`.

2020-02-04 05:19 UTC, ayazhafiz commented on packages/language-service/test/completions_spec.ts
> +          `<div *ngFor="let x	~{cursor-one}; of heroes ~{cursor-two}; tr~{cursor-three};"></div>`);
I would recommend changing the test case or adding `trackBy`. It could be confusing to someone reading the code

2020-02-04 05:21 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +          // The template context should be provided here because of 'index as i'.
So in this situation we would only want to provide `... as ...` completions, is that correct? If so, could you reword the comment?

2020-02-04 06:06 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +          // The template context should be provided here because of 'index as i'.
No, here we need to provide the template context(e.g. `index`, `odd`, etc.) and directive input(e.g. `of`, `trackBy`).

2020-02-04 06:24 UTC, ivanwonder commented on packages/language-service/test/completions_spec.ts
> +          `<div *ngFor="let x	~{cursor-one}; of heroes ~{cursor-two}; tr~{cursor-three};"></div>`);
Just add comment there.

2020-02-04 06:32 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +          // The template context should be provided here because of 'index as i'.
`*ngFor="let item of items; trackBy| ;"`
the completions include template context and directive input.
`*ngFor="let item of items; trackBy| : myTrack ;"`
the completions only include directive input.

2020-02-04 07:09 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +          // The template context should be provided here because of 'index as i'.
Okay, I understand. Sorry, the comment was confusing me -- it sounds like only the template context should be provided, because of the example `index as i`, and it is not clear where `index as i` comes from. Could you reword the comment to explain that in this case, we should provide both template context member and input completions?

2020-02-04 12:04 UTC, ivanwonder commented on packages/language-service/src/completions.ts
> +      if (attr.value.substring(valueRelativePosition, binding.span.end).indexOf(':') === -1) {
Does it better now?

2021-11-02 22:21 UTC, jessicajaniuk commented
Closing this since View Engine is no more making this no longer necessary.

2021-11-02 22:21 UTC, closed without merging