fix(docs-infra): size footer links to appropriate size for seo and small css fixes
angular/angular pull request #35098
Opened 2020-02-01 13:05 UTC by ajitsinghkaler

Footer links did not have enough space between them, so lighouse was reporting that tap targets are not appropriately sized added the required 8px space between links

Fixes #34901

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Footer Links does not have enough space between them

Issue Number: #34901

## What is the new behavior?
Added required 8 px space between them

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Added other small fixes to make it work on small screens less that with 400px and search results when scrolling soes not interfere wit the top navbar items

2020-02-04 14:12 UTC, ajitsinghkaler commented
@gkalpak can you look into this

2020-02-04 16:56 UTC, mary-poppins commented
You can preview e52ca73 at https://pr35098-e52ca73.ngbuilds.io/.
You can preview c3e377c at https://pr35098-c3e377c.ngbuilds.io/.

2020-02-04 17:37 UTC, gkalpak requested changes
Nice catches! Thx, @ajitsinghkaler.
Can you also please fix the typos in the commit messages:
- `lighouse` --> `lighthouse`
- `prperly` --> `properly`
- `searh` --> `search`

2020-02-04 17:37 UTC, gkalpak commented on aio/src/styles/1-layouts/_footer.scss
> +        padding: 4px 0;
Now that the items have more space between them, it is more difficult to distinguish the different groups in narrow screens (where the groups are stacked one under another).

Can you, also update the margin of the group headers [here][1]:

```diff
-    margin: 0 0 16px;
+    margin: 8px 0 12px;
```

[1]: https://github.com/angular/angular/blob/e52ca73f3327ca5a17d82ee121ecfcae872a021a/aio/src/styles/1-layouts/_footer.scss#L43

2020-02-04 17:37 UTC, gkalpak commented on aio/src/styles/1-layouts/_marketing-layout.scss
> -    width: 400px;
Can you post a before/after screenshot, because I don't see any difference with and without this style.

2020-02-04 17:37 UTC, gkalpak commented on aio/src/styles/2-modules/_search-results.scss
> +    border-top: 68px solid;
Interesting solution :smiley:
Can you please use an explicit border color. The default value, `currentcolor`, only works here because this elements happens to have the same background color and the color defined on `<body>` (`#444`):

```diff
-    border-top: 68px solid;
+    border-top: 68px solid transparent;
```
(We could also use #444, but then we would have to update it in two places if we decided to change the background color.)

2020-02-04 18:43 UTC, ajitsinghkaler commented on aio/src/styles/1-layouts/_marketing-layout.scss
> -    width: 400px;
![Angular](https://user-images.githubusercontent.com/39260684/73775479-f5f9f400-47ab-11ea-9a05-f9a3292354de.png)
Before removing the width:400px

![Angular (1)](https://user-images.githubusercontent.com/39260684/73775562-25106580-47ac-11ea-9653-64bd6e5dceec.png)
After removing the width:400px

2020-02-04 18:48 UTC, gkalpak commented on aio/src/styles/1-layouts/_marketing-layout.scss
> -    width: 400px;
I see, thx for the screenshots :+1:

2020-02-04 19:01 UTC, ajitsinghkaler commented on aio/src/styles/1-layouts/_footer.scss
> +        padding: 4px 0;
Added this

2020-02-04 19:01 UTC, ajitsinghkaler commented on aio/src/styles/2-modules/_search-results.scss
> +    border-top: 68px solid;
added this

2020-02-04 19:08 UTC, ajitsinghkaler commented
@gkalpak Made the changes please have a look

2020-02-04 19:14 UTC, mary-poppins commented
You can preview 1f7e6c0 at https://pr35098-1f7e6c0.ngbuilds.io/.

2020-02-04 19:33 UTC, ajitsinghkaler commented
@gkalpak these same flakey failure can you look into this.

2020-02-04 21:23 UTC, gkalpak commented
Thx, @ajitsinghkaler.
<sub>FYI: I made some minor changes to the commit messages (mostly fixing typos and missing punctuation).</sub>

2020-02-04 21:24 UTC, gkalpak approved these changes

2020-02-04 21:31 UTC, mary-poppins commented
You can preview 74bfad5 at https://pr35098-74bfad5.ngbuilds.io/.

2020-02-04 23:58 UTC, closed without merging

2020-02-05 23:52 UTC, IgorMinar commented
@ajitsinghkaler thanks for fixing the issue!!!