fix(ivy): `LFrame` needs to release memory on `leaveView()`
angular/angular pull request #35156
Opened 2020-02-05 05:44 UTC by mhevery

Root cause is that for perf reasons we cache `LFrame` so that we don't have to allocate it all the time. To be extra fast we clear the `LFrame` on `enterView()` rather that on `leaveView()`. The implication of this strategy is that the deepest `LFrame` will retain objects until the `LFrame` allocation depth matches the deepest object.

The fix is to simply clear the `LFrame` on `leaveView()` rather then on `enterView()`

Fix #35148

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-02-06 00:03 UTC, mhevery commented
[presubmit](http://test/OCL:293473862:BASE:293473903:1580947413999:38408d37)

2020-02-11 21:21 UTC, mhevery commented
[presubmit](http://test/OCL:293473862:BASE:294505492:1581456088184:75b192af)

2020-02-12 15:34 UTC, pkozlowski-opensource requested changes
The code LGTM but I'm surprised that there is code size increase (and it is even bigger than what is written in the code as the CI check fails: https://circleci.com/gh/angular/angular/621857#tests/containers/3)

2020-02-12 18:59 UTC, mhevery commented
> The code LGTM but I'm surprised that there is code size increase (and it is even bigger than what is written in the code as the CI check fails: https://circleci.com/gh/angular/angular/621857#tests/containers/3)

I think this is the case where the limit was close to 500 bytes and this CL took os over, so now you have the 500 bytes plus this CL. `226144 - 225584 = 560`

2020-02-12 19:16 UTC, pkozlowski-opensource approved these changes

2020-02-14 01:43 UTC, kara approved these changes
LGTM

2020-02-14 01:43 UTC, kara commented on packages/core/src/render3/state.ts
> + * This is a light weight version of the `leaveView` which is needed by the DI system.
```suggestion
 * This is a lightweight version of the `leaveView` which is needed by the DI system.
```

2020-02-14 01:43 UTC, kara commented on packages/core/src/render3/state.ts
> +  oldLFrame.currentQueryIndex = 0;
I wonder if we could share more code with `createLFrame`? It sets properties in similar ways.

2020-02-14 04:15 UTC, mhevery commented on packages/core/src/render3/state.ts
> + * This is a light weight version of the `leaveView` which is needed by the DI system.
fixed

2020-02-14 04:15 UTC, mhevery commented on packages/core/src/render3/state.ts
> +  oldLFrame.currentQueryIndex = 0;
Yes, that would be nice. The issue is that in `createLFrame` we are creating an object where as here we are modifying it. We could create an empty object and then set properties on it, but I am concern that it may have negative perf impact as we are adding properties one by one rather than in bulk.

2020-02-14 19:13 UTC, closed without merging

2020-02-14 19:15 UTC, kara commented on packages/core/src/render3/state.ts
> +  oldLFrame.currentQueryIndex = 0;
Yeah, that was what I was thinking, but thought maybe there could be a perf reason. Might be good to have that in a comment.