fix(language-service): Suggest ? and ! operator on nullable receiver
angular/angular pull request #35200
Opened 2020-02-06 23:07 UTC by kyliau

Under strict mode, the language service fails to typecheck nullable
symbols that have already been verified to be non-null.

This generates incorrect (false positive) and confusing diagnostics
for users.

To work around this issue in the short term (before properly fixing it in Ivy), 
this commit changes the diagnostic message from an error to a suggestion, 
and prompts users to use the safe navigation operator (?) or 
non-null assertion operator (!).

For example, instead of

```typescript
{{ optional && optional.toString() }}
```

the following is cleaner:

```typescript
{{ optional?.toString() }}
{{ optional!.toString() }}
```

Note that with this change, users who legitimately make a typo in their
code will no longer see an error. I think this is a reasonable trade-off, since
false positive is worse than false negative. However, if users follow
the suggestion, add ? or ! to their code, then the error will be surfaced.

References:

1. Safe navigation operator (?)
   https://angular.io/guide/template-syntax#the-safe-navigation-operator----and-null-property-paths
2. Non-null assertion operator (!)
   https://angular.io/guide/template-syntax#the-non-null-assertion-operator---

Thank you @andrius-pra for the suggestion =)

PR closes https://github.com/angular/angular/pull/35070
PR closes https://github.com/angular/vscode-ng-language-service/issues/589

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-02-07 00:58 UTC, ayazhafiz approved these changes
just one comment

2020-02-07 00:58 UTC, ayazhafiz commented on packages/language-service/src/expression_type.ts
> +            `Consider using the safe navigation operator (?) or non-null assertion operator (!) to access '${ast.name}'.`,
Could we provide an example based off the receiver and ast name? It would be very nice if we could suggest `(myobj?.value)` rather than just `(?)`

2020-02-07 00:58 UTC, ayazhafiz commented on packages/language-service/src/expression_type.ts
> +      if (receiverType.nullable) {
ohhhh nice. this fixes the actual typo case. sweet!

2020-02-07 01:49 UTC, kyliau commented on packages/language-service/src/expression_type.ts
> +            `Consider using the safe navigation operator (?) or non-null assertion operator (!) to access '${ast.name}'.`,
Good idea! I had to narrow down the type of `ast.receiver` to access the receiver name.
In the future we could implement [quick fixes](https://code.visualstudio.com/docs/languages/typescript#_quick-fixes) for suggestions like this.

2020-02-07 03:24 UTC, ayazhafiz requested changes

2020-02-07 03:24 UTC, ayazhafiz commented on packages/language-service/src/expression_type.ts
> +    const receiverName = (ast.receiver as PropertyRead).name;
Can we do a sanity check and bail out in case this isn’t a property read? same on line 403.

2020-02-07 05:45 UTC, kyliau commented on packages/language-service/src/expression_type.ts
> +    const receiverName = (ast.receiver as PropertyRead).name;
I went one step further, there's really no need to do the same check in multiple places. resolveMethodCall should call resolvePropertyRead, then verify that the type is callable. The code is a lot simpler now ;)

2020-02-08 02:39 UTC, kyliau commented
@ayazhafiz PTAL, thanks :)

2020-02-08 19:56 UTC, ayazhafiz requested changes

2020-02-08 19:56 UTC, ayazhafiz commented on packages/language-service/src/expression_type.ts
> +                `or non-null assertion operator (${ast.receiver.name}!.${ast.name}).`,
Sorry, just one more nit -- when we report this diagnostic, it may not be immediately clear to the user why they should use the safe navigation/assertion operator. Can we add a sentence at the beginning saying that the receiver might be null? e.g.

```typescript
`${ast.receiver.name} may not be defined. Consider...`
```

2020-02-10 18:58 UTC, kyliau commented on packages/language-service/src/expression_type.ts
> +                `or non-null assertion operator (${ast.receiver.name}!.${ast.name}).`,
Good idea, done!

2020-02-10 22:39 UTC, ayazhafiz approved these changes

2020-02-11 00:44 UTC, closed without merging