fix(elements): schematics fails with schema.json not found error
angular/angular pull request #35211
Opened 2020-02-07 07:24 UTC by alan-agius4

Fixes #35154

2020-02-07 12:43 UTC, gkalpak requested changes
Thx for adding the integration test :100:

Can you explain somewhere in the integration test (e.g. in a `README.md` or in a comment in the test script) what this test is testing. (I understand from the context that it verifies the `ng-add` schematic works correctly, but it would be hard to infer by only looking at the integration test.

2020-02-07 12:43 UTC, gkalpak commented on integration/ng_elements-schematics/package.json
> +  "main": "index.js",
```suggestion
```
(to avoid confusion)

2020-02-07 12:43 UTC, gkalpak commented on integration/ng_elements-schematics/test.sh
> +  ng add @angular/elements
Will this not install the dependencies?

2020-02-07 12:43 UTC, gkalpak commented on integration/ng_elements-schematics/package.json
> +    "@angular/cli": "file:../../node_modules/@angular/cli"
Are these dependencies used at all?
(If not, do we even need a `package.json`/`yarn.lock`?)

2020-02-07 12:43 UTC, gkalpak commented on integration/ng_elements-schematics/test.sh
> +#!/usr/bin/env bash
We try to avoid adding more bash scripts into the repo, because they are harder to understand and work with across OSes. We favor JS scripts (with `ShellJS` if needed) instead.

2020-02-07 13:02 UTC, alan-agius4 commented on integration/ng_elements-schematics/test.sh
> +  ng add @angular/elements
No, because it's already installed. `ng add` will use the local version

2020-02-07 13:03 UTC, alan-agius4 commented on integration/ng_elements-schematics/package.json
> +    "@angular/cli": "file:../../node_modules/@angular/cli"
Yes they are used.

1) CLI: because we need the local `ng`
2) Elements to ensure that we use the package from `packages-dist/elements` instead of `npm`

2020-02-07 13:49 UTC, alan-agius4 commented on integration/ng_elements-schematics/test.sh
> +#!/usr/bin/env bash
I wasn't aware of that on the move to node script. But I totally dig that!

2020-02-09 23:56 UTC, gkalpak requested changes

2020-02-09 23:56 UTC, gkalpak commented on integration/ng_elements_schematics/test.ts
> +  'language-service',
Do we need all these packages (forms, router, etc.)? Also, where is `core`? 🤔
How about having just `common`, `core`, `elements`, `platform-browser`, `platform-browser-dynamic`?

2020-02-09 23:56 UTC, gkalpak commented on integration/ng_elements_schematics/test.ts
> +].map(p => `"@angular/${p}@file:${pwd}/../../dist/packages-dist/${p}"`);
Wouldn't it be safer to use `__driname`? `pwd` depends on where the script is run from, so these paths could be wrong.

2020-02-09 23:56 UTC, gkalpak commented on integration/ng_elements_schematics/test.ts
> +shx.exec('ng new demo --skip-git --skip-install --style=css');
How come this does not ask about things like routing pn CI? (It does for me when run locally.)

2020-02-09 23:56 UTC, gkalpak commented on integration/ng_elements_schematics/test.ts
> +shx.cd('demo');
Here too, consider using `__dirname`, so that this script does not need to be run from a specific directory.

2020-02-09 23:56 UTC, gkalpak commented on integration/ng_elements_schematics/test.ts
> +shx.exec(`yarn add --ignore-scripts --silent ${packages}`);
Why are we installing the packages after running `ng add`? Couldn't we do it the other way around? (It would feel more close to what happens in reality.)
If there is a reason for the current order of commands, can you please add comments explaining that?

2020-02-09 23:56 UTC, gkalpak commented on integration/ng_elements_schematics/test.ts
> +shx.exec('ng build --no-source-map');
By default, ShellJS `exec()` (and other methods) will not cause the script to exit with an error (which is what we want here). We should use [set('-e')][1] at the top of the file.

[1]: https://documentup.com/shelljs/shelljs#setoptions

2020-02-10 07:24 UTC, alan-agius4 commented on integration/ng_elements_schematics/test.ts
> +shx.exec('ng new demo --skip-git --skip-install --style=css');
For CI environments it non interactive, I’ll add the non interactive option

2020-02-10 07:41 UTC, alan-agius4 commented on integration/ng_elements_schematics/test.ts
> +].map(p => `"@angular/${p}@file:${pwd}/../../dist/packages-dist/${p}"`);
Yeah agree.

2020-02-10 11:38 UTC, alan-agius4 commented on integration/ng_elements_schematics/test.ts
> +  'language-service',
The reason being as the the CLI will install all these packages, and we don't want to have tests failure because of incompatibilities.
https://github.com/angular/angular-cli/blob/54b79ade65bfe3749e9ec2cd4fc52f6a74c26e94/packages/schematics/angular/workspace/files/package.json.template#L13-L44

2020-02-10 12:26 UTC, alan-agius4 commented
@gkalpak PTAL

2020-02-10 12:30 UTC, alan-agius4 commented on integration/ng_elements_schematics/test.ts
> +shx.exec(`yarn add --ignore-scripts --silent ${packages}`);
No particular reason

2020-02-10 14:02 UTC, gkalpak commented on integration/ng_elements_schematics/test.ts
> +  'language-service',
I see, thx for clarifying. Could you mention that in a comment (so that people know why these packages are in the list and how to update the list in the future if needed)?

2020-02-10 14:07 UTC, gkalpak commented on integration/ng_elements_schematics/test.ts
> +import {cd, exec, set, rm} from 'shelljs';
```suggestion
import {cd, exec, rm, set} from 'shelljs';
```

😇

2020-02-10 14:07 UTC, gkalpak commented on integration/ng_elements_schematics/test.ts
> +rm('-rf', 'demo');
```suggestion
rm('-rf', `${__dirname}/demo`);
```

or 

```suggestion
cd(__dirname);
rm('-rf', 'demo');
```

2020-02-10 15:11 UTC, alan-agius4 commented on integration/ng_elements_schematics/test.ts
> +import {cd, exec, set, rm} from 'shelljs';
done.

2020-02-10 15:12 UTC, alan-agius4 commented on integration/ng_elements_schematics/test.ts
> +rm('-rf', 'demo');
Done

2020-02-10 15:22 UTC, gkalpak approved these changes

2020-02-10 15:22 UTC, gkalpak commented on integration/ng_elements_schematics/test.ts
> +cd('demo');
If you don't `cd(__dirname)` above, then you need to update this as well.
```suggestion
cd(`${__dirname}/demo`);
```

2020-02-11 18:10 UTC, mhevery approved these changes

2020-02-11 19:43 UTC, closed without merging