feat(docs-infra): feature to download docs for offline viewing
angular/angular pull request #35251
Opened 2020-02-08 11:29 UTC by ajitsinghkaler

added feature to download docs for offline viewing featching all files tat need to be downloaded from ngsw.json files and downloading them all using fetch which leads to cacheing via service worker

Fixes #27492

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Right now cannot download docs for offline download.

Issue Number: N/A

## What is the new behavior?
Added a new para at the bottom for offline download of the docs

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-02-08 11:31 UTC, ajitsinghkaler commented
I will add tests once we are sure how this functionality has to be implemented. Right now using only @gkalpak gist to download all the files. I need additional input on how can we implement it better.

2020-02-08 13:53 UTC, mary-poppins commented
You can preview a42b723 at https://pr35251-a42b723.ngbuilds.io/.

2020-02-08 14:25 UTC, IgorMinar requested changes
Awesome work @ajitsinghkaler! I tested this PR and confirmed that it works reasonably well:
 
<img width="1158" alt="Screen Shot 2020-02-08 at 5 59 28 AM" src="https://user-images.githubusercontent.com/216296/74086765-0f649f80-4a3b-11ea-91ed-85fe81e423a4.png">

I noted the "transfer" (compressed) payload size which is something we should make people aware of before the confirm that they really want to do this.

A few additional things I noticed that should be investigated/resolved:
- [ ] images are not being fetched, which results in poor UX because the app is not fully offline usable without them. We should include the images in the manifest file (currently they are not listed there)
- [ ] we need to confirm that as we modify the content and images in the future, the incremental update works automatically and is really incremental (only modified content and images should be automatically refetched) - this should work out of the box, but we should verify.
- [ ] we need some kind of test for this, a proper e2e test will be hard to build, but we should at minimum verify that the app is not broken after the full offline mode is activated.

Again awesome work @ajitsinghkaler! 🚀
I ❤️seeing all your improvements coming in.

2020-02-08 14:25 UTC, IgorMinar commented on aio/src/app/layout/footer/footer.component.html
> +<p (click)="downloadDocs()">Download docs for offline usage</p>
We might want tweak this text to:
- [ ] make it shorter
- [ ] clarify that this is full offline usage (we already have partial offline usage which is on by default)
- [ ] add a download icon of some sort (@sjtrimble can help with that after we come to a conclusion that this PR is viable)
- [ ] decide on the position of the icon+text (again @sjtrimble can help with that after other technical issues are resolved)
- [ ] we should make this accessible by not using a click handler on `p` but instead use a `button` or an `a` or use the proper `aria` roles to communicate properly with screen readers.

2020-02-08 14:25 UTC, IgorMinar commented on aio/src/app/layout/footer/footer.component.ts
> +      const confirmed = confirm(`Download all ${lazyUrls.length} URLs?`);
we should provide some kind of estimate about the download size to set the expectations. I ran a test and currently we download about 17MB of json files, without any images.

we should also modify the text to say that once downloaded, future updates will be incremental and automatic - this is actually huge win for the users because once they have the docs downloaded, they will always have a recent version of docs content available offline without any more manual downloads, as long as they occasionally connect to the internet and navigate to angular.io (which kicks in the automated incremental SW update).

2020-02-08 14:25 UTC, IgorMinar commented on aio/src/app/layout/footer/footer.component.ts
> +      const lazyUrls = manifest.assetGroups.find((g:any) => g.name === 'docs-lazy').urls;
bah! it makes me a bit sad that we have to handle it like this because the whole reason for us designing assetGroups was so that we can eventually provide a new https://angular.io/api/service-worker/SwUpdate API that would trigger download of `lazy` assetGroups. So instead of all of this code, you would be able to just to `swUpdate.fetch('docs-lazy')` and be done.

We've however haven't gotten to implementing this (trivial) functionality - something we might consider as a follow up on this PR?

2020-02-08 14:25 UTC, IgorMinar commented on aio/src/app/layout/footer/footer.component.ts
> +        alert(`Downloaded ${lazyUrls.length} URLs in ${duration}s. (${failedCount} failed.)`);
it took about 20sec for me to download everything on a relatively fast connection. Users with slower connections might need significantly more time, so we should consider providing some kind of progress indicator. We might need to replace the confirm/alert with `MatDialog` but we should be careful about not increasing the critical path bundle size in the process of doing that. Maybe the code (and the MatDialog) for full offline download could be moved to a lazy-loaded chunk?

I don't want to overcomplicate this PR, so let's discuss this one and whether my concern about lack of download progress indicator is a blocker or could be a follow up PR.

2020-02-18 19:23 UTC, gkalpak commented on aio/src/app/layout/footer/footer.component.ts
> +      const confirmed = confirm(`Download all ${lazyUrls.length} URLs?`);
> they will always have a recent version of docs content available offline without any more manual downloads

Note that this is only true for existing guides/API docs. New guides/API docs needs to be explicitly downloaded.

2020-02-18 19:31 UTC, gkalpak commented on aio/src/app/layout/footer/footer.component.ts
> +        alert(`Downloaded ${lazyUrls.length} URLs in ${duration}s. (${failedCount} failed.)`);
With the current approach of kicking off all downloads at once, I don't think it is possible to report progress, because the requests are downloaded from the SW (which first fully downloads the resource, then caches it and finally returns it to the page - so I don't think it shares progress with the page).

We could show some rough progress if we manually batched the requests (e.g. download 10 resources at a time), but that would not allow the browser to optimize the request batching.

2020-02-18 21:23 UTC, gkalpak reviewed
Nice! 🚀 

I generally agree with Igor's comments (I left some additional comments inline and below).
A couple more issues I see:

- Once cached, there is no way to remove the cached resources (and stop them from being re-fetched on every update). The only option is to clear the caches (e.g. via DevTools), but that is not easy on mobile devices.

- The error messages (when a URL fails to be downloaded) are not very helpful.

##
> images are not being fetched, which results in poor UX because the app is not fully offline usable without them. We should include the images in the manifest file (currently they are not listed there)

AFAICT, the images are in the manifest and caches ad expected. Which images did you see missing?

2020-02-18 23:25 UTC, sjtrimble commented
Couple of options:

1) Add the "download offline" icon button to the toolbar next to the social icons. Only show this when the user is on a 'true' docs site such as `/docs`, `/guide`, and '/api`

2) Add a "Download Docs Offline" menu button to the menu (menu only appears when on 'true' docs sites so no further logic needed there.

![docs](https://user-images.githubusercontent.com/2958442/74786972-dd391600-5262-11ea-9562-7a8ee60bc50a.png)

3) Add a link to the footer.
![footer](https://user-images.githubusercontent.com/2958442/74786962-d6120800-5262-11ea-8307-e46bd09eadfc.png)

I think both work - the second and third options are more subtle and less discoverable which might be good as I don't think this is a feature EVERYONE will need.

2020-03-05 15:04 UTC, mary-poppins commented
You can preview 5a44705 at https://pr35251-5a44705.ngbuilds.io/.

2020-03-05 15:07 UTC, ajitsinghkaler commented
@IgorMinar @gkalpak Made the changes put the offline content into a lazy-loaded chunk put it at the  top position. Added styles and mat dialog.

Now need some guidance or help on the following things

Icon from @sjtrimble can you please send me the SVG or should I download it my self from some free icon site

Tests: What kind of test do you think we should add here. Should we check that all requests are sent from the service worker because the test that these are saved correctly should already be present

Adding size to app data: should I change the build command to add size on each build

Progress bar: Should we show a progress bar based on the completion of each request or think about this on the follow-up pr

Errors: What to do with files that fail to download on these requests. Download again by saving failure cases or give an option to the user to try again once if that also fails, he can start the whole process over again

2020-03-08 08:31 UTC, ajitsinghkaler commented
@gkalpak @IgorMinar can you please review this.

2020-03-11 15:50 UTC, ajitsinghkaler commented
@gkalpak @IgorMinar can you please review this

2020-03-11 16:52 UTC, IgorMinar commented
Hi @ajitsinghkaler, I tested it on my phone and while I like the new dialog the download didn't seem to work. The UI doesn't look good on phone screen and when I clicked download nothing happened and the dialog remained open for several minutes until I closed it.
![Screenshot_20200311-094613](https://user-images.githubusercontent.com/216296/76442244-e018b980-637d-11ea-9647-5c2d60fabadf.png)
![Screenshot_20200311-094619](https://user-images.githubusercontent.com/216296/76442247-e149e680-637d-11ea-9776-e5091501059f.png)
![Screenshot_20200311-094657](https://user-images.githubusercontent.com/216296/76442249-e1e27d00-637d-11ea-9b13-f534c16e21b1.png)

Can you please take a look at these issues?

2021-02-24 09:28 UTC, closed without merging