feat(language-service): improve non-callable error message
angular/angular pull request #35271
Opened 2020-02-09 20:31 UTC by ayazhafiz

This commit improves the context of a non-callable function error
message by providing the affected call target and its non-callable type.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Feature

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-02-09 20:33 UTC, ayazhafiz commented
One thing we should start evaluating a design for is isolating error messages in a separate (json) file with unique IDs, descriptions, and even examples. Many modern language tools like tsserver, Rust's compiler, and Shellcheck follow this model. It will also provide a natural way for us to support enabling/disabling particular error messages as users have requested.

2020-02-11 01:28 UTC, kyliau commented
> One thing we should start evaluating a design for is isolating error messages in a separate (json) file with unique IDs, descriptions, and even examples. Many modern language tools like tsserver, Rust's compiler, and Shellcheck follow this model. It will also provide a natural way for us to support enabling/disabling particular error messages as users have requested.

In Ivy, each error already has a unique ID, but description is still generated on the fly.
It's good idea to pull them out into JSON.

https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtsc/diagnostics/src/error_code.ts

2020-02-11 01:51 UTC, kyliau requested changes

2020-02-11 01:51 UTC, kyliau commented on packages/language-service/test/diagnostics_spec.ts
> +      mockHost.override(TEST_TEMPLATE, `{{myClick()()}}`);
This case checks for a function call of which the receiver is an ImplicitReceiver.
We should add another check for which the receiver is a property read.
like `title.toString()()`

2020-02-11 01:51 UTC, kyliau commented on packages/language-service/src/expression_type.ts
>      const target = this.getType(ast.target !);
`ast.target` is of type `AST` here, but really it's a `MethodCall` AST, of which the receiver is an `ImplicitReceiver`.
The `MethodCall` AST contains the name of the function call, so it looks like a better fix here is to make a safe cast to retrieve the name.

Alternatively, we could fix the typings upstream. Right now, many parameters are just typed `AST`. They should have been more specific.

If we go with the cast, we'll have to account for the other case which is a PropertyRead receiver. Please see next comment =)

2020-02-11 02:23 UTC, ayazhafiz commented on packages/language-service/src/expression_type.ts
>      const target = this.getType(ast.target !);
Yeah, you're right. I'll see if we can type the ast specially.

2020-02-11 16:39 UTC, ayazhafiz commented on packages/language-service/src/expression_type.ts
>      const target = this.getType(ast.target !);
The problem with pulling out the name is it only contains the name for the most local AST. So for something like `title.toUpperCase()()`, the property read AST name would only give us `toUpperCase`, and we would have to continue backing up and reconstruct what we think the source code looks like to get `title.toUpperCase()`. For this reason, I think it's better to parse out the source code from the AST span.

2020-03-05 03:12 UTC, ayazhafiz commented
ptal @kyliau

2020-03-05 23:00 UTC, kyliau commented on packages/language-service/src/expression_diagnostics.ts
> +    const analyzer = new AstType(scope, this.info.query, {inEvent}, this.info.source);
We don't have to pass in the entire template, because the AST we got from the TemplateAst is actually ASTWithSource, so we already have the expression string here. This info combined with the span of the expression node should be sufficient for us to retrieve the string of interest.
Before we do that though, it might be better to update the type for all ASTs in `template_ast.ts` from AST to ASTWithSource. Please let me know if you need more clarification, thank you!

2020-03-11 01:29 UTC, ayazhafiz commented on packages/language-service/src/expression_diagnostics.ts
> +    const analyzer = new AstType(scope, this.info.query, {inEvent}, this.info.source);
I'm not sure this will work, because AstType may visit child nodes of the AST, which may not be `ASTWithSource`s. We could pass the source of just the expression, but I am weary of this it would require using more relative spans. What do you think?

2020-03-11 18:17 UTC, kyliau commented on packages/language-service/src/expression_type.ts
> +  private sourceOf(ast: AST): string { return this.source.substring(ast.span.start, ast.span.end); }
You brought up a very good point in https://github.com/angular/angular/pull/35271/files#r390700195
Could you please double check that `ast.span` here is relative to the whole template?
I think it might be relative to the expression in the template.
In the test case that you wrote in packages/language-service/test/diagnostics_spec.ts the expression is the template itself so it works. Could you please test this with a template that has multiple expressions?

2020-03-13 02:03 UTC, ayazhafiz commented on packages/language-service/src/expression_type.ts
> +  private sourceOf(ast: AST): string { return this.source.substring(ast.span.start, ast.span.end); }
Good call. Fixed to use absolute spans.

2020-03-14 01:29 UTC, kyliau approved these changes

2020-03-17 16:29 UTC, closed without merging