docs: change definition of providedIn any
angular/angular pull request #35292
Opened 2020-02-10 12:48 UTC by santoshyadav198613

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-02-12 09:16 UTC, santoshyadav198613 commented
@kapunahelewong @gkalpak ,
can you review, its small change.

2020-02-12 18:31 UTC, kapunahelewong requested changes
Thanks for this, @santoshyadav198613. Just a note on clarification.

2020-02-12 18:31 UTC, kapunahelewong commented on packages/core/src/di/injectable.ts
> +   * - 'any' : Provides a unique instance in every lazy loaded modules and all eager loaded module
```suggestion
   * - 'any' : Provides a unique instance in each lazy loaded module while all eagerly loaded modules
```

Is this the definition? That it will give a unique instance for each lazy module, but that all eagerly loaded ones will share one? (I'm still learning this.)

2020-02-13 05:31 UTC, santoshyadav198613 commented on packages/core/src/di/injectable.ts
> +   * - 'any' : Provides a unique instance in every lazy loaded modules and all eager loaded module
Yeah, this is what i wanted to write, thanks :)

2020-02-13 18:38 UTC, kapunahelewong approved these changes

2020-02-13 18:38 UTC, mary-poppins commented
You can preview 5e40996 at https://pr35292-5e40996.ngbuilds.io/.
You can preview f3f04f7 at https://pr35292-f3f04f7.ngbuilds.io/.
You can preview 3a711e1 at https://pr35292-3a711e1.ngbuilds.io/.

2020-02-13 18:54 UTC, kapunahelewong commented on packages/core/src/di/injectable.ts
> +   * modules will share an unique instance.
I must have missed this before. Pardon me. Can we try this?
```suggestion
   * modules share one instance.
```

2020-02-14 06:19 UTC, santoshyadav198613 commented on packages/core/src/di/injectable.ts
> +   * modules will share an unique instance.
Done.

2020-02-14 06:46 UTC, mary-poppins commented
You can preview 809103b at https://pr35292-809103b.ngbuilds.io/.

2020-02-19 07:24 UTC, santoshyadav198613 commented
Hi @kara ,
Can you review please.

2020-04-06 21:17 UTC, santoshyadav198613 commented
Hi @kara ,
Can you review please.

2020-05-02 12:05 UTC, santoshyadav198613 commented
Hi Team,
Can you review it, please?

2020-05-11 20:52 UTC, santoshyadav198613 commented
H @docs-team can you check and approve.

2020-06-02 18:07 UTC, santoshyadav198613 commented
Hi, @mhevery and @aikidave can you review, please.

2020-06-25 01:57 UTC, IgorMinar approved these changes
Lgtm, thanks! This is a helpful clarification.

2020-06-25 02:00 UTC, IgorMinar approved these changes
Reviewed-for: global-approvers

2020-06-25 18:37 UTC, Splaktar approved these changes
LGTM, thank you!

2020-06-25 18:40 UTC, Splaktar commented
I believe that the eng review has been completed?

It's unclear what cleanup is still needed?

2020-06-25 19:55 UTC, AndrewKushnir commented
@Splaktar, thanks for the comment. I've added the "cleanup" label because this PR required a rebase (merge script indicated that). I tried to rebase myself, but got the "permission denied" error.

@santoshyadav198613, could you please rebase this PR on top of the latest master and let me know in this thread, so I can try to merge it again.

Thank you.

2020-06-27 14:08 UTC, santoshyadav198613 commented
> @Splaktar, thanks for the comment. I've added the "cleanup" label because this PR required a rebase (merge script indicated that). I tried to rebase myself, but got the "permission denied" error.
> 
> @santoshyadav198613, could you please rebase this PR on top of the latest master and let me know in this thread, so I can try to merge it again.
> 
> Thank you.

Let me do it.

2020-06-27 14:35 UTC, mary-poppins commented
You can preview f552e99 at https://pr35292-f552e99.ngbuilds.io/.

2020-06-27 14:37 UTC, santoshyadav198613 commented
@AndrewKushnir done, you can merge now.

2020-06-29 22:00 UTC, closed without merging