fix(forms): ensure the field value of a FormGroup/FormArray always co…
angular/angular pull request #35297
Opened 2020-02-10 13:54 UTC by TidianeRol

…ntains enabled controls values

Prior to this change, the field value of a FormGroup or FormArray may contains disabled controls value.

PR close #35184

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

If you have a form which contains enabled controls, the value field contains the value of the enabled controls even if you add disabled controls of if you disable the form. The field value will always contain only enabled controls value.

The problem is : **Sometimes the field value doesn't contain only enabled controls value**
If you have a form disabled (either because it is disabled directly itself, or because all of its contained controls are disabled), the value field contains the value of the disabled controls until we add an enabled control or until we enable the form. When you add an enabled control or enable the form, the value field will always contain the value of the enabled controls even if you add disabled controls after.

Again, If you disable your form and you use setValue or patchValue method, the field value will contains the value you gave to theses methods, while the status of the form is disabled.
The field "value" sometimes doesn't contain only enabled controls value.
Issue Number: #35184

## What is the new behavior?
Now, the value field contains only enabled controls value.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-02-10 14:34 UTC, petebacondarwin commented on packages/compiler-cli/BUILD.bazel
> +        "@npm//chokidar"
This change doesn't seem to be related to this PR?

2020-02-10 14:34 UTC, petebacondarwin commented on packages/compiler-cli/tsconfig-build.json
> +    "../../node_modules/@types/chokidar/index.d.ts",
This change doesn't seem to be related to this PR?

2020-02-10 14:35 UTC, petebacondarwin commented on packages/forms/test/form_control_spec.ts
> +        // expect(g.value).toEqual({'one': 'one', 'two': 'two'});
Remove this comment - we can see from the diff what changed.

2020-02-10 14:35 UTC, petebacondarwin commented on packages/forms/test/form_group_spec.ts
> +        // expect(g.value).toEqual({'one': 'one', 'two': 'two'});
Same here.

2020-02-10 14:36 UTC, petebacondarwin commented on packages/forms/test/form_group_spec.ts
> +        // expect(g.value).toEqual({'one': 'one', 'two': 'two'});
And here!

2020-02-10 14:36 UTC, petebacondarwin commented on packages/forms/test/form_group_spec.ts
> +        // expect(g.value).toEqual({nested: {one: 'one', two: 'two'}});
ditto!

2020-02-10 14:36 UTC, petebacondarwin commented on packages/forms/test/form_control_spec.ts
> +        expect(g.value).toEqual({}); // c and c2 are disable so g.value is empty
```suggestion
        expect(g.value).toEqual({}); // c and c2 are disabled so g.value is empty
```

2020-02-10 14:36 UTC, petebacondarwin commented on packages/forms/test/form_group_spec.ts
> +        expect(g.value).toEqual({}); // gi disable so its value is empty
```suggestion
        expect(g.value).toEqual({}); // g is disabled so its value is empty
```

2020-02-10 14:37 UTC, petebacondarwin commented on packages/forms/test/form_group_spec.ts
> +        expect(g.value).toEqual({}); // g disable so its value is empty
```suggestion
        expect(g.value).toEqual({}); // g is disabled so its value is empty
```

2020-02-10 14:37 UTC, petebacondarwin commented on packages/forms/test/form_group_spec.ts
> +        expect(g.value).toEqual({}); // g disable so its value is empty
```suggestion
        expect(g.value).toEqual({}); // g is disabled so its value is empty
```

2020-02-10 14:39 UTC, petebacondarwin requested changes
Thanks @TidianeRol !

Can you remove the chokidar changes - I know that you probably need them locally to run the tests. Sorry.
We probably need another PR to add that.

I made a few suggested changes.

@kara you originally designed this disabled mechanism on forms. Do you want to have a say on whether this is a reasonable change. It looks like you designed it originally to work in this way. So you might not agree with this change.

2020-02-11 18:52 UTC, AndrewKushnir commented
@TidianeRol, thanks for creating this PR. Existing Forms logic works as expected: the list of children may contain both enabled and disabled controls. Changing this behavior will result in a breaking change that would affect lots of use-cases. We'll revisit this question while working on Forms improvements/refactoring for future versions. I'll close this ticket for now to remove it from review queue. Thank you.

2020-02-11 18:52 UTC, closed without merging