docs: Maintain `pathname` when switching angular versions
angular/angular pull request #35318
Opened 2020-02-11 03:15 UTC by sonukapoor

Previously, when switching angular versions through the
version selector in the sidenav, the path is lost, and the
user has to manually navigate to the original location.

This commit fixes this issue and maintains the `pathname`
when navigating between different versions.

Closes #24495

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #24495

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-02-14 01:05 UTC, sonukapoor commented
@petebacondarwin / @gkalpak Are we OK with this one?

2020-02-14 11:43 UTC, mary-poppins commented
You can preview 607b1f6 at https://pr35318-607b1f6.ngbuilds.io/.
You can preview 4cc785e at https://pr35318-4cc785e.ngbuilds.io/.

2020-02-14 12:00 UTC, gkalpak requested changes
Thx, @sonukapoor!
Please change the commit message to something like:

> fix(docs-infra): maintain `pathname` ...

2020-02-15 02:04 UTC, sonukapoor commented on aio/src/app/app.component.ts
> +      this.locationService.go(`${version.url}${window.location.pathname}`);
Very good point. I was not aware of the `LocationService`. I have made that change.

2020-02-15 02:26 UTC, mary-poppins commented
You can preview bf3594e at https://pr35318-bf3594e.ngbuilds.io/.

2020-02-15 02:34 UTC, sonukapoor commented on aio/src/app/app.component.spec.ts
> +import { AppModule } from './app.module';
Done

2020-02-15 02:40 UTC, mary-poppins commented
You can preview 8ab07f5 at https://pr35318-8ab07f5.ngbuilds.io/.

2020-02-16 02:53 UTC, mary-poppins commented
You can preview 73836ef at https://pr35318-73836ef.ngbuilds.io/.

2020-02-16 03:24 UTC, mary-poppins commented
You can preview f106d1c at https://pr35318-f106d1c.ngbuilds.io/.

2020-02-16 04:17 UTC, mary-poppins commented
You can preview f3cdc12 at https://pr35318-f3cdc12.ngbuilds.io/.

2020-02-17 14:49 UTC, gkalpak requested changes
Also, please, make sure you follow the [commit message guidelines][1] in all commit messages.

[1]: https://github.com/angular/angular/blob/939e2f76f/CONTRIBUTING.md#commit

2020-02-17 14:49 UTC, gkalpak commented on aio/src/app/app.component.ts
> +      .subscribe(([hasToc, showFloatingToc]) => this.hasFloatingToc = hasToc && showFloatingToc);
Please revert this.

2020-02-17 14:49 UTC, gkalpak commented on aio/src/app/app.component.ts
> +          24; //  fudge margin
Please revert this.

2020-02-17 15:21 UTC, sonukapoor commented on aio/src/app/app.component.ts
> +          24; //  fudge margin
The formatting becomes inconsistent in that case: Here is how it looks:
In some cases 2 spaces are used and in some cases 4. 
```typescript
      if (headerEl && footerEl) {
        this.tocMaxHeightOffset =
          headerEl.clientHeight +
          footerEl.clientHeight +
        24; //  fudge margin
      }
```

2020-02-17 15:24 UTC, sonukapoor commented
> Also, please, make sure you follow the [commit message guidelines](https://github.com/angular/angular/blob/939e2f76f/CONTRIBUTING.md#commit) in all commit messages.

Is there something wrong with the current commit messages of this PR?

2020-02-17 15:33 UTC, mary-poppins commented
You can preview b9bdeb6 at https://pr35318-b9bdeb6.ngbuilds.io/.

2020-02-17 16:54 UTC, gkalpak requested changes
Regarding the commit messages:

1. The first commit message still mentions only `pathname`, while the commit now also preserves query and hash.
2. The subject should not start with a capital letter (i.e. `fix(docs-infra): Maintain` -->` fix(docs-infra): maintain`).
3. The second commit (and its fixup) should use the `style` type:
    > **style:** Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)

2020-02-17 16:54 UTC, gkalpak commented on aio/src/app/app.component.spec.ts
> +        locationService.urlSubject.next('new-page');
Can you please add a query and hash fragment to show that they are also preseved in the new URL?

2020-02-17 16:54 UTC, gkalpak commented on aio/src/app/app.component.ts
> +          24; //  fudge margin
True (that's because we don't use a formatter for the AIO code 😱
But switching individual statements from one format to the other (when we haven;t decided that format is better) in an ad-hoc way is not a good idea imo (and definitely out of scope for this PR).

2020-02-17 17:45 UTC, mary-poppins commented
You can preview d4e9175 at https://pr35318-d4e9175.ngbuilds.io/.

2020-02-18 11:00 UTC, gkalpak approved these changes

2020-02-18 20:45 UTC, closed without merging