fix(forms): Call setDisabledState in in reactive directives when appropriate
angular/angular pull request #35311
Opened 2020-02-10 20:23 UTC by jermowery

When a CVA is added a form and that CVA implements setDisabledState the
reactive form directives should call setDisabledState with true when the
FormControl is disabled and false when it is enabled. Currently,
setDisabledState is only called when the FormControl is disabled.

Fixes #35309

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
setDisabledState when adding a control to a form is called with true with the FormControl is disabled and not called when the FormControl is enabled.

Issue Number: #35309 

## What is the new behavior?

setDisabledState is called when adding a control to a form with false when the FormControl is enabled and true with the FormControl is disabled.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

2020-02-11 00:35 UTC, AndrewKushnir requested changes
@jermowery thanks for creating a PR! 👍 I left a couple nits, please have a look.

It looks like this PR also introduces behavior change for Forms, where `setDisabledState` is called in situations where it was not called before. Could you please try to run Global TAP with this change to see if there are targets that might be potentially affected?

Thank you.

2020-02-11 00:35 UTC, AndrewKushnir commented on packages/forms/test/value_accessor_integration_spec.ts
> +    function initTest<T>(component: Type<T>, ...directives: Array<Type<any>>): ComponentFixture<T> {
We tend to use a short version of type notation wrt arrays, e.g. `string[]` vs `Array<string>`, so we should probably revert this change.

2020-02-11 00:35 UTC, AndrewKushnir commented on packages/forms/test/value_accessor_integration_spec.ts
> +          it('sets the disabled state when the control is initally enabled', () => {
I'm a bit confused by the test description, should it say `sets the enabled state...` (seems like this is what you are also checking in the test)?

2020-02-11 00:35 UTC, AndrewKushnir commented on packages/forms/test/value_accessor_integration_spec.ts
> +            throw new Error(
👍

2020-02-11 01:37 UTC, jermowery commented
> It looks like this PR also introduces behavior change for Forms, where `setDisabledState` is called in situations where it was not called before. Could you please try to run Global TAP with this change to see if there are targets that might be potentially affected?

There are 3 specs failing as a result of this change. 2 of which are in my own codebase. I will put together a CL that can be patched with the fixes for the Angular caretaker doing the sync

2020-02-11 02:24 UTC, AndrewKushnir reviewed
Thanks for additional changes @jermowery!

> There are 3 specs failing as a result of this change. 2 of which are in my own codebase. I will put
> together a CL that can be patched with the fixes for the Angular caretaker doing the sync

Thanks for verifying this in g3 👍Given that there are some (minor) breakages, I'd like to ask @kara to have a look at this PR too, to make sure we assess the risks accordingly.

Thank you.

2020-02-11 02:33 UTC, jermowery commented
I just took another look at my Global TAP and it looks like there are more changes than anticipated. I will discuss with you all tomorrow

2020-03-29 20:04 UTC, sonukapoor commented
Hi @jermowery, I was working on a similar PR, but noticed that your PR already covers what I was going to change as well. Is there anything I can help with for this PR?

2020-03-30 13:47 UTC, jermowery commented
Unfortunately, this breaks a significant number of tests inside Google, and I don't have to bandwidth to fix them, so this PR is pretty much abandoned

2020-06-09 20:20 UTC, AndrewKushnir commented
FYI, potentially related PR #18575 and related (duplicate?) issue #17806.

2020-06-10 06:17 UTC, AndrewKushnir commented
Hi @jermowery, since this is a breaking change and it affects a lot of targets internally in google3, I was thinking if we should consider adding a config option similar to the `warnOnNgModelWithFormControl` one [defined here](https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/forms/src/form_providers.ts#L55-L64). That should keep existing behavior, allow enabling new/corrected one and simplify the rollout of this change (make it incremental). WDYT?

2020-06-10 06:54 UTC, jermowery commented
That seems reasonable. Sadly I don't have the bandwidth right now to incorporate that change but feel free to adopt this PR if it is a priority

2020-07-21 22:57 UTC, grosch commented
What's the status of this being implemented?

2020-07-29 05:36 UTC, mohamed-gara commented
There is already this PR #20310. Maybe it's the same fix.

2021-02-09 16:30 UTC, Jakartoine commented
@AndrewKushnir,

Sorry for disturbing you but do you have any update about this point?

To workaround this, I had to recreate a custom radio button component with an override on NG_VALUE_ACCESSOR.

Already 3 years since this bug has been discovered without any fix...

Thank you in advance

2021-02-10 03:32 UTC, AndrewKushnir commented
Hi @Jakartoine,

Unfortunately we don't have any updates on this issue at this moment.

The problem with the fix is that it requires a breaking change: it changes the behavior (to be more correct), but this affects existing apps since some of them rely on the current sequence of calls to the `setDisabledState` methods defined on CVAs. Running tests in Google's codebase indicated that the breaking change is quite severe and there is no easy way to auto-correct the code with schematic/migration. We have to come up with a migration strategy, such as introducing a flag (something like `ReactiveFormsModule.withConfig({setDisabledStateBehavior: 'legacy' /* or 'new' */})`) for apps to opt into using the "correct" behavior, wait for 1-2 major versions and only after that flip the flag to make "correct" behavior default. This work requires some planning and additional investigations and we didn't have a chance to prioritize this yet. We'll keep this PR updated once we have more info available.

Thank you.

2021-02-10 08:34 UTC, Jakartoine commented
@AndrewKushnir

Alright, it sounds clearer now. Thank you for your response mate.

2022-02-04 00:34 UTC, dylhunn commented
I'm going to run a TGP to find out how severe the breakage is. I suspect it's quite bad, but the only way to know is to try!

2022-02-21 21:00 UTC, closed without merging