docs: remove @angular/platform-webworker from comment
angular/angular pull request #35333
Opened 2020-02-11 13:07 UTC by santoshyadav198613

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-02-11 20:49 UTC, kapunahelewong approved these changes
Thank you, @santoshyadav198613. Just a small fix. We'll still need engineering to review.

2020-02-11 20:49 UTC, kapunahelewong commented on packages/common/src/location/platform_location.ts
> + * implementation specific to the browser environment
```suggestion
 * implementation specific to the browser environment.
```

2020-02-12 06:06 UTC, santoshyadav198613 commented on packages/common/src/location/platform_location.ts
> + * implementation specific to the browser environment
Done.

2020-02-14 02:10 UTC, kara requested changes
@santoshyadav198613 Can you update the commit message with more information on why we should remove the mention of platform-webworker?

2020-02-14 06:16 UTC, santoshyadav198613 commented
> @santoshyadav198613 Can you update the commit message with more information on why we should remove the mention of platform-webworker?

Done.

2020-02-17 09:17 UTC, santoshyadav198613 commented
Hi @kara,
Can you check now, I have updated the message.

2020-04-06 21:16 UTC, santoshyadav198613 commented
Hi @kapunahelewong ,
Can we get it reviewed, let me know if any changes are required.

2020-05-02 03:50 UTC, santoshyadav198613 commented
Hi @kara ,
Can you please review and check if anything else is needed.

2020-05-06 17:58 UTC, santoshyadav198613 commented
Hi Team,
Can anyone look into this PR please.

2020-05-12 20:13 UTC, closed without merging

2020-05-12 20:17 UTC, santoshyadav198613 commented
Closing this PR as it was already removed.