Ng container shallow query
angular/angular pull request #35384
Opened 2020-02-12 15:28 UTC by pkozlowski-opensource

2020-02-13 17:23 UTC, mhevery approved these changes

2020-02-13 17:23 UTC, mhevery commented on packages/core/test/acceptance/query_spec.ts
> +            <ng-container>
Could we add a tests when `#target` is on `<ng-container>` As in this case:

```
<needs-target>
  <ng-container #target>
    <b #target></b>
  </ng-container>
</needs-target>
```

It is a bit surprising that we will get both `#target`s

2020-02-13 17:23 UTC, mhevery commented on packages/core/test/acceptance/query_spec.ts
> +              <ng-container>
ohh, I see this is covered sort of here. (Not sure if previous comment) applies.

2020-02-13 17:24 UTC, mhevery commented
Adding `cleanup` to consider adding additional test, LGTM otherwise.

2020-02-13 17:25 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/query_spec.ts
> +            <ng-container>
yeh, I believe that we've got such a test already, as you've noticed in [another comment](https://github.com/angular/angular/pull/35384#discussion_r379006526).

2020-02-14 02:01 UTC, kara requested changes
Mostly ready to go, but can we also add more context to the commit message about what this change is and why?

2020-02-18 13:07 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/query_spec.ts
> +        });
OMG, @kara I didn't have this test and... you know what... there was an actual bug in my impl! Good catch, thank you!

2020-02-18 13:09 UTC, pkozlowski-opensource commented on aio/scripts/_payload-limits.json
> +        "main-es2015": 449449,
yep,  size accumulating over commits... I've rebased this PR and now I don't have to bump those limits any more...

2020-02-18 13:48 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/query_spec.ts
> +      expect(cmptWithQuery.targets.length).toBe(1);
Added asserts for query result type.

2020-02-18 18:41 UTC, kara approved these changes
LGTM

2020-02-18 18:45 UTC, kara commented
[presubmit](http://test/OCL:295769176:BASE:295769224:1582051439482:5364afc6)

2020-02-19 01:17 UTC, closed without merging