feat(router): add skipNavigation option to routerLink
angular/angular pull request #35393
Opened 2020-02-12 20:55 UTC by alexduer

The RouterLink directive now has a 'skipNavigation' boolean which disables navigating.

Closes #31154

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 31154

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
I could not find documentation for the 'skipLocationChange' boolean, so I did not add any documentation for the 'skipNavigation' boolean.

2020-02-12 21:53 UTC, atscott requested changes

2020-02-12 21:53 UTC, atscott commented on packages/router/src/directives/router_link.ts
> +    if (!attrBoolValue(this.skipNavigation)) {
I think this would be better as an early return at the top like what's done with the `onClick` of `RouterLinkWithHref`

2020-02-12 21:53 UTC, atscott commented on packages/router/src/directives/router_link.ts
> +    if (!attrBoolValue(this.skipNavigation)) {
Move this to be an early return at the top with the others. Additionally, I think you should be returning `true` instead of `false` if you're not navigating.

2020-02-12 21:53 UTC, atscott commented on packages/router/src/directives/router_link.ts
> +  @Input() skipNavigation !: boolean;
I'm not sure how I feel about `skipNavigation` since navigating is kind of the only thing a `routerLink` *does* in the first place. Maybe `disabled` or `disableNavigation` would be a more appropriate name. What do you think?

2020-02-12 22:00 UTC, alexduer commented on packages/router/src/directives/router_link.ts
> +  @Input() skipNavigation !: boolean;
Good point! 'disableNavigation' is definitely clearer.

2020-02-12 22:51 UTC, atscott commented
Can you take a look at the CI failures and try to fix them? Also adding @gkalpak for some input on how this should be documented, if merged.

2020-02-19 22:55 UTC, atscott commented on packages/router/src/directives/router_link.ts
> +  @Input() disableNavigation !: boolean;
Rather than continuing to use `!` and adding to the technical debt for #24571, how about using `?` since Inputs are optional?

2020-11-30 17:18 UTC, jdgarvey commented
@alexduer are you still working on this? If you are that's cool, but if you aren't I can pick this up and get it through the rest of the process.

2020-11-30 21:18 UTC, alexduer commented
@jdgarvey you are welcome to pick up the issue

2020-12-10 05:23 UTC, atscott commented
Closing, as it looks like the work was handed off and is now in #39916

2020-12-10 05:23 UTC, closed without merging