docs: set default width of first `th` and last `td` in events `table`
angular/angular pull request #35437
Opened 2020-02-14 02:26 UTC by sonukapoor

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

**Broken layout**

![image](https://user-images.githubusercontent.com/59734/74495667-77d1d780-4ea6-11ea-9103-c939a3e6eedf.png)

**Fixed layout**

![image](https://user-images.githubusercontent.com/59734/74495623-507b0a80-4ea6-11ea-8634-3de4d92c9887.png)

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-02-14 13:00 UTC, mary-poppins commented
You can preview 610a750 at https://pr35437-610a750.ngbuilds.io/.

2020-02-14 13:14 UTC, gkalpak requested changes
Good catch!

2020-02-14 13:14 UTC, gkalpak commented on aio/src/styles/2-modules/_table.scss
> +  & table > tbody >
This seems redundant. Please remove.

2020-02-14 13:14 UTC, gkalpak commented on aio/src/styles/2-modules/_table.scss
> +    width: 15%;
On narrow screens, this makes the first column too narrow while other columns has empty space. How about making each column 33% wide?

2020-02-14 13:28 UTC, sonukapoor commented on aio/src/styles/2-modules/_table.scss
> +article[class="events-container"] {
Haha. What was I thinking :)

2020-02-15 01:48 UTC, sonukapoor commented on aio/src/styles/2-modules/_table.scss
> +    width: 15%;
Makes sense.

2020-02-15 02:02 UTC, mary-poppins commented
You can preview 916fb4f at https://pr35437-916fb4f.ngbuilds.io/.

2020-02-17 14:42 UTC, gkalpak requested changes
Thx for making the changes, @sonukapoor! Can you also change the commit message type/scope to `fix(docs-infra): ...`?

2020-02-17 14:42 UTC, gkalpak commented on aio/src/styles/2-modules/_table.scss
> +  tr > td {
Let's combine these rules to one:

```scss
.events-container {
   tr > td, tr > th {
    width: 33%;
  }
}
```

2020-02-17 15:59 UTC, mary-poppins commented
You can preview 874b0f4 at https://pr35437-874b0f4.ngbuilds.io/.

2020-02-17 16:23 UTC, gkalpak requested changes

2020-02-17 16:23 UTC, gkalpak commented on aio/src/styles/2-modules/_table.scss
> +   width: 33%;
```suggestion
    width: 33%;
```

2020-02-17 16:23 UTC, gkalpak commented on aio/src/styles/2-modules/_table.scss
> + }
```suggestion
  }
```

2020-02-17 16:40 UTC, mary-poppins commented
You can preview e6991f3 at https://pr35437-e6991f3.ngbuilds.io/.

2020-02-17 17:09 UTC, gkalpak approved these changes
👌

2020-02-18 20:48 UTC, closed without merging