fix(core): Allow modification of lifecycle hooks any time before bootstrap
angular/angular pull request #35464
Opened 2020-02-15 02:27 UTC by mhevery

Currently we read lifecycle hooks eagerly during `ɵɵdefineComponent`. The result is that it is not possible to do any sort of meta-programing such as mixins or adding lifecycle hooks using custom decorators since any such code executes after `ɵɵdefineComponent` has extracted the lifecycle hooks from the prototype. Additionally the behavior is inconsistent between AOT and JIT mode. In JIT mode overriding lifecycle hooks is possible because the whole `ɵɵdefineComponent` is placed in getter which is executed lazily. This is because JIT mode must compile a template which can be specified as `templateURL` and those we are waiting for its resolution.

- `+` `ɵɵdefineComponent` becomes smaller as it no longer needs to copy lifecycle hooks from prototype to `ComponentDef`
- `-` `ɵɵNgOnChangesFeature` feature is now always included with the codebase as it is no longer tree shakable.

Previously we have read lifecycle hooks from prototype in the `ɵɵdefineComponent` so that lifecycle hook access would be monomorphic. This decision was made before we had `T*` data structures. By not reading the lifecycle hooks we are moving the megamorhic read form `ɵɵdefineComponent` to instructions. However, the reads happen on `firstTemplatePass` only and are subsequently cached in the `T*` data structures. The result is that the overall performance should be same (or slightly better as the intermediate `ComponentDef` has been removed)

- [ ] Remove `ɵɵNgOnChangesFeature` from compiler. (It will no longer be a feature.)
- [ ] Discuss the future of `Features` as they hinder meta-programing.

Fix #30497

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-03-04 18:49 UTC, bryanrideshark commented
Thank you so much for fixing this. Angular Ivy is awesome - Being able to upgrade our app, which heavily uses custom decorators, will be possible once this PR is merged.

2020-03-12 08:38 UTC, RolginRoman commented
Really looking forward to this PR 👍

2020-03-21 23:43 UTC, ef32 commented
Really looking forward to this PR being merged

2020-03-30 07:58 UTC, qtis commented
🙄

2020-04-13 03:39 UTC, kumaresan-subramani commented
Eagerly waiting for this MR to get merged. Once this get merged so many issue must get resolved i think.

2020-04-16 21:20 UTC, lurock commented
When using Angular 9.1.1 with Ivy now when I "ng serve" all of my custom class decorators are called and working the way they did with view engine but when I run "ng build --prod" and run the application only a few of my custom decorators are called.  @mhevery will this pull request fix that?  Meaning will all my decorators get called when the application is first loaded.

2020-04-18 19:09 UTC, hakimio commented
@mhevery any idea when this might get merged and what's stopping it from getting reviewed?
It's quite important issue for us too.

2020-04-29 00:05 UTC, bryanrideshark commented
@hakimio it seems like different members of the team have different opinions about how important Metaprogramming is for users of Angular.

Thankfully @mhevery  seems to realize just how important it is to us; but he might have a challenge convincing other members. Hopefully everyone on the Angular team will realize just how prevalent metaprogramming is among Angular users.

2020-05-04 16:50 UTC, Maximaximum commented
The merge delay is quite confusing. I really hope that this PR will get into master.

2020-05-10 19:44 UTC, maxime1992 commented
Without this MR, Ivy misses a little bit to be backward compatible :) 

That'd really help us too at CloudNC to work on a new version of [ngx-sub-form](https://www.npmjs.com/package/ngx-sub-form) where we're trying to get rid of inheritance.

:crossed_fingers: for this to get merged soon

2020-05-20 09:15 UTC, LayZeeDK commented
Please don't kill [component features](https://indepth.dev/component-features-with-angular-ivy/).

Please stop worrying about custom decorators. Custom decorators are experimental and should be treated as such.

The original ECMAScript decorators proposal has been abandoned. There's a new proposal in early stages, but it has different syntax and semantics.

2020-05-20 09:41 UTC, hakimio commented
> Please don't kill [component features](https://indepth.dev/component-features-with-angular-ivy/).

AFAIK it's Angular private API and they can do whatever they want with private APIs.

> Custom decorators are experimental.

Yet they are one of the most widely used TypeScript features and many TypeScript libraries depend on them.

2020-05-20 09:52 UTC, mlc-mlapis commented
> AFAIK it's Angular private API and they can do whatever they want with private APIs.

It's private now, but because of the phase for stabilization inner structures and finalize the public API. It was always mentioned as the public API at some point.

> Yet they are one of the most widely used TypeScript features and many TypeScript libraries depend on them.

Yep, but it was meant from official ECMAScript spec.

2020-05-20 10:53 UTC, klemenoslaj commented
> Please stop worrying about custom decorators. Custom decorators are experimental and should be treated as such.

Why is everyone fixating on decorators only? The point is, that components are JS classes. Methods on classes are members of prototype. Overwriting a prototype method is an absolutely valid thing to do. Angular currently makes this impossible.

And yes, sure, decorators are one use case of it and I wouldn't make custom decorators for reasons you mentions, but there are many more use cases.
One use case is a `takeUntilDestroy` which is basically a `takeUntil` that patches `ngOnDestroy` hook in Angular. Impossible right now.

2020-05-20 17:05 UTC, bryanrideshark commented
If we can't use custom decorators, you might as well get rid of them across the board in Angular. No `@Input`, `@Output`, `@HostBinding`. I'm not going to keep using a framework if the authors of the framework take a "good for me, but not for thee" approach to something that's a key language feature. Angular originally was going to write its own language just to make decorators possible (Remember AtScript?) and now, because we've got an optimized compiler and some pet private APIs, we're going to say decorators aren't impossible or good for users to use?

It's not a good look when libraries are built around the idea that developers have to use a subset of a language.

2020-05-20 17:07 UTC, pkozlowski-opensource commented
Just FYI, the intention is to review and merge this PR. It is in progress.

2020-05-20 17:10 UTC, bryanrideshark commented
@klemenoslaj , you're absolutely right. Currently, we use a custom `takeUntil` implementation which (until Angular 9) added the ngOnDestroy method if it hadn't already been defined in the prototype. Now, I'm having to add a blank `ngOnDestroy()` method to all my components, just for the runtime to recognize that we're using the `ngOnDestroy()` hook. My compiled code has a bunch of useless `KlassComponent.prototype.ngOnDestroy = function() {}` code in it, just to convince the Angular runtime that it's actually using ngOnDestroy. Sure, maybe there's a minute performance boost in the startup time for the application, but my entire bundle has redundant code in it now, so am I really getting a win here?

2020-05-20 17:12 UTC, bryanrideshark commented
Thank you @pkozlowski-opensource  for the clarification. It's been a bit unclear as to whether or not this was going to land when you see people marked as "Contributor" sending mixed messages. I suppose "Contributor" just means you've committed code to the project, whereas "Members" have a decision making role inside Angular?

Regardless, I'm glad this is being looked at and addressed by the Angular team.

2020-05-20 17:54 UTC, LayZeeDK commented
>If we can't use custom decorators, you might as well get rid of them across the board in Angular. No @Input, @Output, @HostBinding. I'm not going to keep using a framework if the authors of the framework take a "good for me, but not for thee" approach to something that's a key language feature. Angular originally was going to write its own language just to make decorators possible (Remember AtScript?) and now, because we've got an optimized compiler and some pet private APIs, we're going to say decorators are off limits for end users?

Angular's TypeScript decorators are special in that they are compiler instructions, meaning they are annotations rather than decorators. They are converted to static properties at compile time, so they aren't used at runtime like most other custom decorators.

2020-05-20 17:58 UTC, LayZeeDK commented
>Thank you @pkozlowski-opensource for the clarification. It's been a bit unclear as to whether or not this was going to land when you see people marked as "Contributor" sending mixed messages. I suppose "Contributor" just means you've committed code to the project, whereas "Members" have a decision making role inside Angular?

I'm just voicing my opinion. Very few people are decision makers when it comes to Angular.

I think anyone's opinion should be valued, no matter whether they are an Angular team member, an Angular Collaborator, an Angular GDE, an Angular contributor, or any other form of Angular community member.

2020-05-20 17:59 UTC, klemenoslaj commented
@bryanrideshark since it was just confirmed that this MR is going to get done/merged, you can change your decorator to account for `ɵcmp`. Then you do not need to create an empty `ngOnDestroy` function.

I already use it and it works great, however, as stated above - by using private API. When this MR is merged, my private API usage can be removed too.

You can do something along these lines:

```
if (instanceConstructor.ɵcmp) {
  // Using private API until the corresponding Angular issues are resolved.
  // Issues:  https://github.com/angular/angular/issues/31495, https://github.com/angular/angular/issues/30497
  // PR:      https://github.com/angular/angular/pull/35464
  destroy = <Function>instanceConstructor.ɵcmp.onDestroy ?? noop;
  instanceConstructor.ɵcmp.onDestroy = __takeUntilDestroy__destroy__;
} else {
  destroy = <Function>instanceConstructor.prototype.ngOnDestroy ?? noop;
  instanceConstructor.prototype.ngOnDestroy = __takeUntilDestroy__destroy__;
}

function __takeUntilDestroy__destroy__() {
  destroy();
  // do something fancy
}
```

2020-05-21 08:43 UTC, zakhenry commented
For anyone that can't wait for this PR to close and be released, I've released a library that makes hooking into the angular lifecycle hooks a breeze. It does use internal APIs to get this working, and does require a class level decorator, but it works cleanly with ivy.

See https://github.com/cloudnc/ngx-observable-lifecycle

Even once this PR lands, I will continue to support this library; it will just get a bit simpler eliminating the need for implementers to use the class decorator

2020-05-26 19:53 UTC, kara submitted a review, later dismissed
Can we add some tests to this PR illustrating what we're trying to fix?

2020-05-26 19:53 UTC, kara commented on integration/_payload-limits.json
> +        "main-es2015": 154647,
This is quite a big size jump.

2020-06-03 13:13 UTC, bryanrideshark commented
@kara the following snippet is the decorator code which no longer works for our team, along with a usage example.

### Decorator:
````ts
// NgUnsubscribe (Yes, we're terrible for using the Ng prefix)

import { Subject, Observable } from 'rxjs';

export interface NgUnsubscribe {
  readonly ngUnsubscribe: Observable<void>;
}

export function NgUnsubscribe() {
  return function(constructor) {
    const originalNgOnDestroy = constructor.prototype.ngOnDestroy;

    if (constructor.prototype.__hasSetupNgUnsubscribe) {
      // Handles errors that arise from using the decorator on inherited component classes.
      throw new Error(
        `${constructor.name} used @NgUnsubscribe already. Remove the decorator from ${constructor.name}`
      );
    }
    constructor.prototype.__hasSetupNgUnsubscribe = true;

    // Actually sets up the observable.
    Object.defineProperty(constructor.prototype, 'ngUnsubscribe', {
      get() {
        if (!this.__ngUnsubscribe) {
          this.__ngUnsubscribe = new Subject<void>();
        }
        return this.__ngUnsubscribe;
      }
    });

    // Do the unsubscription
    constructor.prototype.ngOnDestroy = function() {
      try {
        if (originalNgOnDestroy && typeof originalNgOnDestroy === 'function') {
          originalNgOnDestroy.apply(this, arguments);
        }
        if (this.__ngUnsubscribe) {
          const ngUnsubscribe = this.__ngUnsubscribe;
          ngUnsubscribe.next();
          ngUnsubscribe.complete();
          ngUnsubscribe.unsubscribe();
        }
      } catch {}
    };
  };
}


`````

### In Use:
````ts

@Injectable()
export class LogService {

   logNgUnsubscribeEmitted() {
   }

   logNgOnDestroyCalled() {
   }

}


@Component({
selector: 'foo-bar',
template: '',
styles: []
})
@NgUnsubscribe()
export class FooBarComponent implements OnInit, NgUnsubscribe {
   readonly ngUnsubscribe: Observable<void>;

   constructor(private _log: LogService) {}

   ngOnInit() {
       this.ngUnsubscribe.subscribe(() => this._log.logNgUnsubscribeEmitted());
   }

   ngOnDestroy() {
      this._log.logNgOnDestroyCalled();
   }
}



````

I'm no pro at writing tests, but the test would assert
 - That you can create and initialize FooBarComponent without errors
 - That when FooBarComponent is destroyed, both `logNgUnsubscribeEmitted` and `logNgOnDestroyCalled` have been called once.


That only uses `ngOnInit` and `ngOnDestroy`. To get a full sense of the usage, you could use the following decorator in a test environment.

````ts
export interface Mocks {
  onNgOnChanges: () => void;
  onNgOnInit: () => void;
  onNgOnDoCheck: () => void;
  onNgAfterContentInit: () => void;
  onNgAfterContentChecked: () => void;
  onNgAfterViewInit: () => void;
  onNgAfterViewChecked: () => void;
  onNgOnDestroy: () => void; 
}

const MOCKS: Mocks = null;

export function setTestMocks(mocks: Mocks) {
    MOCKS = mocks;
}


export function AugmentComponentHooks() {
   return function augmentComponentHooksDecorator(Original) {
    const originalNgOnChanges = Original.prototype.ngOnChanges;
    const originalNgOnInit = Original.prototype.ngOnInit;
    const originalNgOnDoCheck = Original.prototype.ngOnDoCheck;
    const originalNgAfterContentInit = Original.prototype.ngAfterContentInit;
    const originalNgAfterContentChecked = Original.prototype.ngAfterContentChecked;
    const originalNgAfterViewInit = Original.prototype.ngAfterViewInit;
    const originalNgAfterViewChecked = Original.prototype.ngAfterViewChecked;
    const originalNgOnDestroy = Original.prototype.ngOnDestroy;

    if (originalNgOnChanges) {
        Original.prototype.ngOnChanges = function(...args: Array<any>) {
            originalNgOnChanges.apply(this, arguments);
            MOCKS.onNgOnChanges();
        };
    }
    if (originalNgOnInit) {
        Original.prototype.ngOnInit = function(...args: Array<any>) {
            originalNgOnInit.apply(this, arguments);
            MOCKS.onNgOnInit();
        };
    }
    if (originalNgOnDoCheck) {
        Original.prototype.ngOnDoCheck = function(...args: Array<any>) {
            originalNgOnDoCheck.apply(this, arguments);
            MOCKS.onNgOnDoCheck();
        };
    }
    if (originalNgAfterContentInit) {
        Original.prototype.ngAfterContentInit = function(...args: Array<any>) {
            originalNgAfterContentInit.apply(this, arguments);
            MOCKS.onNgAfterContentInit();
        };
    }
    if (originalNgAfterContentChecked) {
        Original.prototype.ngAfterContentChecked = function(...args: Array<any>) {
            originalNgAfterContentChecked.apply(this, arguments);
            MOCKS.onNgAfterContentChecked();
        };
    }
    if (originalNgAfterViewInit) {
        Original.prototype.ngAfterViewInit = function(...args: Array<any>) {
            originalNgAfterViewInit.apply(this, arguments);
            MOCKS.onNgAfterViewInit();
        };
    }
    if (originalNgAfterViewChecked) {
        Original.prototype.ngAfterViewChecked = function(...args: Array<any>) {
            originalNgAfterViewChecked.apply(this, arguments);
            MOCKS.onNgAfterViewChecked();
        };
    }
    if (originalNgOnDestroy) {
        Original.prototype.ngOnDestroy = function(...args: Array<any>) {
            originalNgOnDestroy.apply(this, arguments);
            MOCKS.onNgOnDestroy();
        };
    }




   }
}


@Component({
    selector: 'uses-augmented-component',
    template: ``,
    styles: []
})
@AugmentComponentHooks()
export class UsesAugmentedComponent {

}

````

I realize that the team might want to implement another way of augmenting the lifecycle hooks - If there was another method, perhaps another compiler API we called in order to agument the hooks at runtime or compile time, that would be sufficient for me.

I don't think we really care about patching the prototype specifically - I think we care more about being able to augment the behavior using the convenient syntax Decorators provide.

2020-06-05 21:25 UTC, mhevery commented on integration/_payload-limits.json
> +        "main-es2015": 154647,
Yes, that is because we always have to include `NgOnChangesFeature` as we don't know it will be added. Not sure we can do much about that.

2020-06-05 21:25 UTC, mhevery commented
I have added tests, ready for another round of reviews.

2020-06-05 21:29 UTC, mhevery commented
[presubmit](http://test/OCL:314996754:BASE:314996828:1591392505499:1e74d877)

2020-06-06 00:02 UTC, IgorMinar requested changes
This seems to be heading down the right path. Can you please resolve the comments and ensure that @pkozlowski-opensource also reviews the runtime part of this change? thanks!

2020-06-06 00:02 UTC, IgorMinar commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> +function wrapOnChangesHook_inPreviousChangesStorage(this: OnChanges) {
what is this function name trying to convey? could you please add a comment with docs and consider simplifying the function name? now that `wrapOnChanges` function is gone?

2020-06-06 00:02 UTC, IgorMinar commented on goldens/size-tracking/aio-payloads.json
> +        "main-es2015": 452712,
overall this change is a size reduction for bigger apps even if for minimalistic apps this change causes a minor size regression.

that's a good news!

2020-06-06 00:03 UTC, IgorMinar commented
the g3 failures seem to be unrelated to this change

2020-06-06 00:15 UTC, IgorMinar commented
@LayZeeDK I've read https://indepth.dev/component-features-with-angular-ivy/ I appreciate that you are exploring Angular truly in depth. It's cool what you can do with the pattern you documented, but I can't say strongly enough that all these features are private and highly unsable / experimental. These Ivy apis can change from one patch version to the next, so we don't advise anyone to rely on them. 

That being said, yet.. the flexibility is quite awesome and we do want to keep on making Angular better a more flexible to support these use-cases, it just takes a lot of time to do this right.

2020-06-06 01:34 UTC, LayZeeDK commented
@IgorMinar I think there's a sweet spot where Angular can allow consumers to hook into the component creation process or override the prototype while having access to the node injector without exposing the whole component definition or other internals/low level APIs.

I wanted to chime in because of this mention in the description:
>Discuss the future of Features as they hinder meta-programing.

I think it's quite the opposite. Features can enable very dynamic and reusable mixins, if we hit that sweet spot.

2020-06-06 08:19 UTC, mlc-mlapis commented
[**@IgorMinar**](https://github.com/IgorMinar) **@LayZeeDK** I always supposed that's `Component Features` is on the road to be public API when it'll be stabilized enough to avoid surprising breaking changes. Isn't the plan already?

2020-06-06 11:27 UTC, LayZeeDK commented
@mlc-mlapis they have been around for at least 2.5 years, but the primært focus for finishing the first stable release of Ivy was to maintain a proper amount of backwards compatibility. What's on the roadmap for Angular v11+, I think is still being discussed.

2020-06-08 23:06 UTC, mhevery commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> +function wrapOnChangesHook_inPreviousChangesStorage(this: OnChanges) {
I have added a comment with explanation. 

NOTE: This was existing code I only removed the un-needed `wrapOnChanges`

2020-06-08 23:06 UTC, mhevery commented on packages/core/src/render3/hooks.ts
> +    const lifecycleHooks: AfterContentInit&AfterContentChecked&AfterViewInit&AfterViewChecked&
Yes, I agree with you that it is more readable, but `clang-format` removes them.

2020-06-08 23:06 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +        const lifeCycleHooks: OnChanges&OnInit&DoCheck = def.type.prototype;
That is how `clang-format` formats the code.

2020-06-08 23:06 UTC, mhevery commented on packages/core/test/acceptance/lifecycle_spec.ts
> +  it('should allow adding lifecycle hook methods any time before bootstrap', () => {
Good point, changed the text.

2020-06-09 00:23 UTC, IgorMinar requested changes
@mhevery can you please make the CI pass. thanks

2020-06-09 00:27 UTC, IgorMinar commented
@LayZeeDK I hear you and agree about the potential and the sweet spot. But until View Engine is not fully deleted from Angular, I don't think that we have brain cycles to explore these ideas. 😞 🤯

2020-06-17 14:05 UTC, pkozlowski-opensource requested changes
@mhevery I did the first pass on this PR and I agree with the general direction.

Having said this I'm marking this PR as "Request changes", as I believe that we need more tests (see in-line comments for specifics).

Also, the commit message only references #30497 but my understanding was that the main driver here was to fix #31495 (ivy + AoT). Could you please confirm that the both issues are being solved and amend the commit message accordingly?

2020-06-17 14:10 UTC, pkozlowski-opensource requested changes
Reviewed-For: fw-core

2020-06-17 20:22 UTC, jelbourn commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> +  const current = simpleChangesStore && simpleChangesStore.current;
```suggestion
  const current = simpleChangesStore?.current;
```

2020-06-17 20:22 UTC, jelbourn commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> +function wrapOnChangesHook(this: OnChanges) {
Does the name of this function still apply? The previous version did "wrap" the changes hook in another function, but now this appears to just be called directly. Would it be more descriptive to name it `rememberChangeHistoryAndInvokeOnChangesHook`?

2020-06-17 20:22 UTC, jelbourn commented on packages/core/src/render3/features/ng_onchanges_feature.ts
> +  return wrapOnChangesHook;
Maybe add a comment here explaining that the `this` context for this function will be bound elsewhere (mentioning where that is).

2020-06-17 20:22 UTC, jelbourn commented on packages/core/test/acceptance/lifecycle_spec.ts
> +    expect(events[0].name.currentValue).toEqual('value');
Would it be valuable to add a test that looks at the previous value as well?

2020-06-19 21:16 UTC, mhevery commented on packages/core/test/acceptance/lifecycle_spec.ts
> +    (Child.prototype as any).ngOnChanges = (e: SimpleChanges) => events.push(e);
test extended

2020-06-19 21:16 UTC, mhevery commented on packages/core/test/acceptance/lifecycle_spec.ts
> +    expect(events[0].name.currentValue).toEqual('value');
added

2020-06-19 21:16 UTC, mhevery commented on packages/core/test/acceptance/lifecycle_spec.ts
> +});
Happy to add a test, but it is not clear to me what I would be testing. The framework logic simply reads the prototype chain. All this refactoring is doing is delaying the reading from eager to lazy. So I don't know what such a test would assert other than that it works the same as normally declared code. Please advise.

2020-06-19 22:33 UTC, tonivj5 commented on goldens/size-tracking/aio-payloads.json
> +<<<<<<< HEAD
Merge markers here

2020-06-19 22:33 UTC, tonivj5 commented on goldens/size-tracking/integration-payloads.json
> +<<<<<<< HEAD
Here

2020-06-19 22:33 UTC, tonivj5 commented on goldens/size-tracking/integration-payloads.json
> +<<<<<<< HEAD
Here

2020-06-19 22:33 UTC, tonivj5 commented on goldens/size-tracking/integration-payloads.json
> +<<<<<<< HEAD
And here :+1:

2020-06-22 20:31 UTC, jelbourn approved these changes
LGTM

Reviewed-for: public-api

2020-06-25 17:50 UTC, Splaktar commented
Re-ran CI and AIO local tests are now passing.

2020-06-25 19:46 UTC, jelbourn approved these changes
Still LGTM for public-api

Reviewed-for: public-api

2020-06-25 19:46 UTC, jelbourn commented on packages/core/test/acceptance/lifecycle_spec.ts
> +});
I think the rationale in adding tests for this would be that the tests don't know/care that the framework is just reading the prototype; that's just an implementation detail. The tests should verify that the expected behaviors work, even if that would seem "obvious" from the code.

2020-06-25 19:46 UTC, jelbourn commented on packages/core/test/acceptance/lifecycle_spec.ts
> +    (Child.prototype as any).ngOnInit = () => events.push('onInit');
You could avoid some repetition here by doing something like
```ts
const componentPrototype = Child.prototype as any;
```

2020-06-25 20:16 UTC, mhevery commented
[presubmit](http://test/OCL:318334378:BASE:318334429:1593116185622:cb382320)

2020-06-26 09:33 UTC, pkozlowski-opensource approved these changes
The code change looks good to me. Still I would love to see few cleanups before this PR goes in.

* [ ] This bug fix is all about the AoT mode but we currently don't run tests in the AoT mode. The net effect here is that I can run the code with the new test and _no_ code change from this PR.... and the test will still pass... Can you think of having a test that fails without the code change?
* [ ] I would love to see more test(s) as [discussed](https://github.com/angular/angular/pull/35464#discussion_r441567036) 
* [ ] add reference to the issue #31495 (fixes #31495 or similar) since this is the actual issue being fixed here, no? (also mentioned this in [my previous review](https://github.com/angular/angular/pull/35464#pullrequestreview-432427887))

Reviewed-for: public-api
Reviewed-for: fw-core

2020-06-26 09:33 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/lifecycle_spec.ts
> +});
Yeh, my thinking is in-line with @jelbourn - things might be obvious today with the current implementation but not so obvious n months down the line with a modified implementation. Personally I always start to review PRs by reading tests to understand what is the use-case being solved and at this point I have no context / details on the underlying implementation details (nor should have I!).

So yeh, even if it sounds like a super-obvious from the code author point of view, I still think that it would be beneficial to have a test - even if it acts as documentation / non regression. I would even say that we should have test(s) that use a custom decorator and class inheritance to make sure that we really cover the use-case that was reported.

2020-06-26 10:55 UTC, pkozlowski-opensource approved these changes
Reviewed-for: size-tracking

2020-06-26 15:56 UTC, mhevery commented on packages/core/src/render3/hooks.ts
> +    (tView.preOrderHooks || (tView.preOrderHooks = [])).push(0 - directiveIndex, ngOnInit);
if `directiveIndex` is `0` than `-0` is a special kind of number which de-optimizes the VM. Where ase `0-0` is always `0`.

2020-06-26 16:08 UTC, alfaproject commented on packages/core/src/render3/hooks.ts
> +    (tView.preOrderHooks || (tView.preOrderHooks = [])).push(0 - directiveIndex, ngOnInit);
Out of curiosity, will Terser try to be smart here and change to `-0` anyway?

2020-06-28 08:16 UTC, ramtob commented
Hi guys, thanks for the good work.

I suppose, when this PR is finalized, it will find its way to the new version 10 of Angular as well?

2020-07-08 20:11 UTC, IgorMinar approved these changes
LGTM - the increase is minimal

Reviewed-for: size-tracking

2020-07-15 17:16 UTC, jelbourn approved these changes
LGTM

Reviewed-for: size-tracking

2020-07-15 18:43 UTC, jelbourn approved these changes
LGTM, using global approvers because the public-api change here is a false positive

Reviewed-for: global-approvers

2020-07-15 18:48 UTC, mhevery commented
[presubmit](http://test/OCL:318334378:BASE:321406361:1594838868604:64806800)

2020-07-15 18:49 UTC, alxhub approved these changes

2020-07-15 22:38 UTC, mhevery commented on packages/core/test/acceptance/lifecycle_spec.ts
> +    (Child.prototype as any).ngOnInit = () => events.push('onInit');
fixed

2020-07-15 22:38 UTC, mhevery commented on packages/core/test/acceptance/lifecycle_spec.ts
> +});
tests added.

2020-07-15 23:22 UTC, closed without merging

2020-07-15 23:23 UTC, AndrewKushnir commented
Hi @mhevery, this PR was merged to master only, since there was a conflict while merging into a patch branch. Could you please create a new PR that targets patch branch? Thank you.