feat(docs-infra): add `searchKeywords` preprocessor
angular/angular pull request #35539
Opened 2020-02-19 02:52 UTC by sonukapoor

This commit adds a new preprocessor to use `${@searchKeywords}`, allowing
the docs to use a list of custom search phrases that will be
prioritized over the keywords found in the content.

Closes #35449

@petebacondarwin take a look at this draft. This does not include any unit tests yet. Let me know your thoughts. 

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #35449

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-02-19 08:57 UTC, petebacondarwin requested changes
Great start @sonukapoor - thanks.
A couple of changes for now.
I had a quick look at the Lunr search engine that we use, and it doesn't support phrase matching :-/
So perhaps for now we should only allow individual words in the search terms that can be provided for a doc.
(i.e. remove the stuff about adding `"` around phrases).

2020-02-19 08:57 UTC, petebacondarwin commented on aio/tools/transforms/angular-content-package/custom-search-defs/index.js
> +
Can we move this to the `angular-base-package/inline-tag-defs` folder and then update the `angular-base-package/index.js` to load this inline tag def, rather than doing it in the `angular-content-package`?
That way this tag will be available inside API docs (and CLI reference docs) as well!

2020-02-19 08:57 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/processors/generateKeywords.js
> +          doc.searchTerms.keywords = `${doc.searchKeywords} ${doc.searchTerms.keywords}`;
Can we have a separate property in `searchTerms` for these keywords, rather than pre-pending them to the current `keywords` property? This will allow us to do more fine-grained searches in the Lunr engine.

2020-02-19 12:24 UTC, sonukapoor commented on aio/tools/transforms/angular-base-package/processors/generateKeywords.js
> +          doc.searchTerms.keywords = `${doc.searchKeywords} ${doc.searchTerms.keywords}`;
Sure what would you like to use as the most common ones are already used? 

Also, does Lunr use the search-data.json file? I couldn’t find anything in the repo for Lunr.

2020-02-19 12:43 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/processors/generateKeywords.js
> +          doc.searchTerms.keywords = `${doc.searchKeywords} ${doc.searchTerms.keywords}`;
Check out this file: https://github.com/angular/angular/blob/master/aio/src/app/search/search.worker.ts

2020-02-19 12:43 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/processors/generateKeywords.js
> +          doc.searchTerms.keywords = `${doc.searchKeywords} ${doc.searchTerms.keywords}`;
How about `doc.searchKeywords.topics` or something like that?

2020-02-20 01:53 UTC, sonukapoor commented on aio/tools/transforms/angular-content-package/custom-search-defs/index.js
> +
The `inline-tag-defs` folder is also in the `angular-base-package` folder, which is why I put mine in there as well. Let me know if you want to change that.

2020-02-20 01:56 UTC, sonukapoor commented on aio/tools/transforms/angular-content-package/custom-search-defs/index.js
> +
There is no `inline-tag-defs` inside the `angular-base-package`. The `inline-tag-defs` is in the `angular-content-package`, which is why I put there.

![image](https://user-images.githubusercontent.com/59734/74893415-55363780-535a-11ea-9b64-01305cbc020a.png)

2020-02-20 02:37 UTC, sonukapoor commented on aio/tools/transforms/angular-base-package/processors/generateKeywords.js
> +          doc.searchTerms.keywords = `${doc.searchKeywords} ${doc.searchTerms.keywords}`;
@petebacondarwin comments addressed, except [this ](https://github.com/angular/angular/pull/35539#pullrequestreview-360926980)one.

2020-02-20 07:08 UTC, petebacondarwin requested changes

2020-02-20 07:08 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/processors/generateKeywords.js
> +
:scream_cat:

2020-02-20 07:08 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/processors/generateKeywords.js
> +        }
This can go now, just add the topics directly into the object literal above

2020-02-20 07:08 UTC, petebacondarwin commented on aio/tools/transforms/angular-content-package/custom-search-defs/index.js
> +
Sorry I was not clear. I meant that you could create that folder in the base package and move this tag handler there.

2020-02-20 12:19 UTC, sonukapoor commented on aio/tools/transforms/angular-content-package/custom-search-defs/index.js
> +
I assume I should leave the existing `inline-tag-defs` folder in `angular-content-packages` and just create a new one under the base folder?

2020-02-20 16:47 UTC, petebacondarwin commented on aio/tools/transforms/angular-content-package/custom-search-defs/index.js
> +
Absolutely!

2020-02-21 07:14 UTC, petebacondarwin reviewed
Looking good. Have you tried adding some topics to docs and seeing if the search results are as expected?

2020-02-21 11:12 UTC, sonukapoor commented
Yes. They show up in the search data json. I tried searching for those through the Ui on port 4200 but they don’t show the page I was expecting to see. Anything I am missing?

2020-02-24 09:20 UTC, mary-poppins commented
You can preview 7f7bbfe at https://pr35539-7f7bbfe.ngbuilds.io/.
You can preview 933833c at https://pr35539-933833c.ngbuilds.io/.
You can preview 6c70ebc at https://pr35539-6c70ebc.ngbuilds.io/.

2020-02-24 12:04 UTC, petebacondarwin commented
OK so this seems to be working for me locally. I added 

```
{@searchKeywords catalog}
``` 

to the `aio/content/guide/structural-directives.md` file and regenerated the docs.

This file now appears in the search results when you search for `catalog`.

Before:

<img width="1435" alt="Screenshot 2020-02-24 at 12 03 28" src="https://user-images.githubusercontent.com/15655/75151058-b1ec7600-56fd-11ea-9bdb-8a0872a0e1b3.png">


After:

<img width="1435" alt="Screenshot 2020-02-24 at 12 01 50" src="https://user-images.githubusercontent.com/15655/75151020-9c774c00-56fd-11ea-8b88-5352bee97cf9.png">

2020-02-24 12:06 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/inline-tag-defs/custom-search-defs/index.js
> +      doc.searchKeywords = tagDescription.replace(/"/g, '');
I don't think we need to remove `"`.

2020-02-24 12:10 UTC, sonukapoor commented on aio/tools/transforms/angular-base-package/inline-tag-defs/custom-search-defs/index.js
> +      doc.searchKeywords = tagDescription.replace(/"/g, '');
Ok. I will make the adjustment

2020-02-24 12:28 UTC, petebacondarwin approved these changes
This LGTM - I think we should land this and then @aikidave can try out adding some keywords to docs and see if it improves things from his point of view. If necessary we could then tweak the search index settings and maybe even the search results UI...

2020-02-24 12:28 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/inline-tag-defs/custom-search-defs/index.js
> +
Oops - indentation is off here.

2020-02-24 12:29 UTC, mary-poppins commented
You can preview 1c2525f at https://pr35539-1c2525f.ngbuilds.io/.

2020-02-25 00:35 UTC, mary-poppins commented
You can preview 9da791b at https://pr35539-9da791b.ngbuilds.io/.

2020-02-26 10:28 UTC, petebacondarwin requested changes

2020-02-26 10:28 UTC, petebacondarwin commented on aio/src/app/search/interfaces.ts
> +  topics?: string;
Actually, can we keep these as required and fix the tests instead please?

2020-02-27 03:26 UTC, sonukapoor commented on aio/src/app/search/interfaces.ts
> +  topics?: string;
Sure. All done. Please review and let me know if I missed anything. Thanks

2020-02-27 03:35 UTC, mary-poppins commented
You can preview 1ff6fe7 at https://pr35539-1ff6fe7.ngbuilds.io/.

2020-02-27 10:46 UTC, petebacondarwin approved these changes

2020-02-27 18:48 UTC, closed without merging