fix(ivy): adhere to bootstrap options for JIT compiled components
angular/angular pull request #35534
Opened 2020-02-18 19:42 UTC by JoostK

When using `platformBrowserDynamic().bootstrapModule()`, it is possible
to set `defaultEncapsulation` and `preserveWhitespaces` as default
configuration to influence how components are compiled. When compiling
components in JIT with Ivy, these options were not taken into account.

This commit publishes the options to be globally available, so that the
lazy compilation of JIT components has access to the configured
bootstrap options. Note that this approach does not allow changing the
options once they have been set, as Ivy's compilation model does not
allow for multiple compilations to exist at the same time.

Fixes #35230
Resolved FW-1838

2020-03-05 19:03 UTC, alxhub approved these changes

2020-03-05 19:03 UTC, alxhub commented
Nice work as usual!

2020-03-05 19:06 UTC, alxhub commented
[Presubmit](http://test/OCL:299144263:BASE:299144306:1583435155037:b0a984d4)

2020-03-05 22:57 UTC, alxhub requested changes
Reverting my approval for now. This warrants some larger discussion about the nature of this change and whether it's "breaking" by some definition.

2020-03-09 16:39 UTC, IgorMinar approved these changes
the rest looks good! thanks

2020-03-09 16:39 UTC, IgorMinar commented on packages/core/src/util/ng_jit_mode.ts
> +  const ngJitMode: boolean;
hmm.. we are starting to have too many places where the global is augmented. Could we consolidated this in a follow up PR? 

Many but possibly not all (e.g. spec?) of these files should be consolidated so that the global namespace type or value mangling happens from one place and is tracked by the ts-api-guardian:
```
git grep -E "declare (var )?global" "packages/**/*.ts" 
packages/compiler/src/util.ts:declare var global: any;
packages/core/src/util/global.ts:declare var global: any /** TODO #9100 */;
packages/core/src/util/global.ts:declare var globalThis: any /** TODO #9100 */;
packages/core/src/util/ng_dev_mode.ts:declare global {
packages/core/src/util/ng_i18n_closure_mode.ts:declare global {
packages/core/test/util/global_spec.ts:declare var globalThis: any /** TODO #9100 */;
packages/core/testing/src/async_fallback.ts:declare var global: any;
packages/core/testing/src/before_each.ts:declare var global: any;
packages/examples/upgrade/static/ts/lite/e2e_test/e2e_util.ts:declare global {
packages/localize/init/index.ts:// `declare global` allows us to escape the current module and place types on the global namespace
packages/localize/init/index.ts:declare global {
packages/localize/src/localize/src/global.ts:declare global {
packages/upgrade/src/dynamic/test/upgrade_spec.ts:declare global {
packages/zone.js/lib/zone.ts:declare var global: NodeJS.Global;
```

2020-03-09 16:41 UTC, IgorMinar commented
@alxhub can you clarify how this change would be breaking? I don't quite follow.

2020-03-09 17:03 UTC, IgorMinar commented
From team discussion: the concern is that the error throw will break currently running applications that set the configuration options multiple times and would cause headaches during minor version updates. 

that is a legit concern. let's review the impact and decide what we can do in 9.x and what needs to be deferred to v10. @alxhub is writing a doc on this, but @JoostK could do that as well since Alex is busy with many other things already.

2020-03-17 22:52 UTC, alxhub commented
[Presubmit](http://test/OCL:299144263:BASE:301470268:1584485470376:41e4b31c)

2020-03-17 22:52 UTC, alxhub approved these changes

2020-03-18 00:49 UTC, AndrewKushnir commented
@alxhub it looks like g3 presubmit finished with some newly broken targets (related to `ngJitMode` global). Could you please have a look when you get a chance? Thank you.

2020-03-18 00:53 UTC, JoostK commented
Oh, I may have an idea what's causing that: there's no import of `ng_jit_mode.ts` anywhere.

2020-03-18 19:44 UTC, alxhub approved these changes

2020-03-18 19:44 UTC, alxhub commented on packages/core/src/application_ref.ts
> +  if (typeof ngJitMode === 'undefined' || ngJitMode) {
You're correct in your assumption - `ng_jit_mode.ts` needs to be side-effectfully imported into this file.

2020-03-18 20:04 UTC, alxhub commented
[Presubmit](http://test/OCL:299144263:BASE:301650026:1584561776112:87e9ff2)

2020-03-19 15:56 UTC, AndrewKushnir commented
Presubmit is green with g3 patch that Alex mentioned, so I'm merging this PR. Thank you.

2020-03-19 15:57 UTC, closed without merging