fix(language-service): infer context type of structural directives (#35537)
angular/angular pull request #35561
Opened 2020-02-19 19:58 UTC by kondi

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #35537, #35426

## What is the new behavior?

The type of structural directive context is now correctly inferred instead of any. There was a trick before to manually handle the context of ngFor exported values (getNgForExportedValueType function), this is not needed anymore, because my solutions handle them automatically. New unit tests were added to validate this change and also to ensure the fix is actually working.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

The implementation works like in angular 8, because it relies on the already existing getTemplateContext method. So the context is inferred from the type parameter of injected TemplateRef. The ivy compiler works differently by relying on ngTemplateContextGuard static method. However, the TemplateRef solution will work with much more existing directives and as I understand, full ivy parity was not scope of language-service v9.

2020-02-19 20:13 UTC, kyliau requested changes
Thank you very much for the contribution! The change looks good.
We are in the midst of transitioning to integrate the Ivy compiler into language service, and consequently `expression_diagnostics_specs.ts` will be going away soon. 
Do you mind moving the tests to `packages/language-service/test/diagnostics_spec.ts`?
The custom directive could be moved to `packages/language-service/test/project/app/parsing-cases.ts`.

Thank you!

2020-02-19 23:10 UTC, kondi commented
> Thank you very much for the contribution! The change looks good.
> We are in the midst of transitioning to integrate the Ivy compiler into language service, and consequently `expression_diagnostics_specs.ts` will be going away soon.
> Do you mind moving the tests to `packages/language-service/test/diagnostics_spec.ts`?
> The custom directive could be moved to `packages/language-service/test/project/app/parsing-cases.ts`.
> 
> Thank you!

Thanks! I have moved the related unit tests. The other cases have been already covered in this file.

2020-02-20 01:26 UTC, kyliau approved these changes
Thank you very much!

2020-02-20 15:58 UTC, ayazhafiz commented
Closes https://github.com/angular/vscode-ng-language-service/issues/650#issuecomment-589050301

2020-02-20 15:58 UTC, ayazhafiz commented
Closes https://github.com/angular/vscode-ng-language-service/issues/650

2020-02-21 17:12 UTC, closed without merging