fix(service-worker): treat 503 as offline
angular/angular pull request #35595
Opened 2020-02-20 22:49 UTC by alexwiese

Prior to this commit the service worker only treated 504 errors as "effectively offline".
This commit changes the behaviour to treat both 503 (Service Unavailable) and 504 as "offline".

Fixes #35571

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #35571

## What is the new behavior?

503 errors will be treated as "offline" and the cached content will be served.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-02-20 22:52 UTC, alexwiese commented
@googlebot I signed it!

2020-02-23 11:40 UTC, alexwiese commented
Looks like the build/tests failed due to something outside of this PR. How can I trigger the builds again?

2020-02-24 10:45 UTC, gkalpak requested changes
Thx, @alexwiese :+1:

Could you also add a test for this. E.g. something similar to [this test][1]. To do that, we need a way to tell the mock server to return a 503 response. (We could use something similar to the [`online` flag][2] or (since this is a one-off thing) spy on `server.fetch()` and return `new MockResponse(null, {status: 503, statusText: 'Service Unavailable'})`).

[1]: https://github.com/angular/angular/blob/e084835fb/packages/service-worker/worker/test/happy_spec.ts#L864
[2]: https://github.com/angular/angular/blob/e084835fb/packages/service-worker/worker/testing/mock.ts#L106

2020-02-24 10:45 UTC, gkalpak commented on packages/service-worker/worker/src/driver.ts
> +   * offline (detected as response status 504 or 503).
I think it would be helpful to include the status test in parenthesis:

```suggestion
   * offline (detected as response status 503 (service unavailable) or 504 (gateway timeout)).
```

2020-02-24 10:45 UTC, gkalpak commented on packages/service-worker/worker/src/driver.ts
> +      } else if ((res.status === 504 || res.status === 503) && ignoreOfflineError) {
```suggestion
      } else if ((res.status === 503 || res.status === 504) && ignoreOfflineError) {
```

:grin:

2020-02-24 12:58 UTC, gkalpak commented on packages/service-worker/worker/test/happy_spec.ts
> +       });
Thx for adding the test. Have you verified that it fails without the fix?

2020-02-24 13:18 UTC, alexwiese commented on packages/service-worker/worker/test/happy_spec.ts
> +       });
I can’t get the tests to run properly on my machine. I get a folder/file not found error. Will try on another system.

2020-02-24 13:51 UTC, gkalpak commented on packages/service-worker/worker/test/happy_spec.ts
> +       });
How are you trying to run them?

2020-02-24 22:27 UTC, alexwiese commented on packages/service-worker/worker/test/happy_spec.ts
> +       });
```git clone https://github.com/alexwiese/angular/
cd angular
yarn install
node ./scripts/build-packages-dist.js
yarn bazel test packages/service-worker```
The error is  `C:/users/alex/_bazel_alex/3tbqurya/execroot/angular/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh: No such file or directory`

2020-02-24 23:10 UTC, alexwiese commented on packages/service-worker/worker/test/happy_spec.ts
> +       });
OK I spun up a brand new Ubuntu VM, installed node 12.16.1, yarn 1.21.1, ran the same commands and I get a similar error:

> error trying to exec 'cc1plus': execvp: No such file or directory

2020-02-24 23:37 UTC, alexwiese commented on packages/service-worker/worker/test/happy_spec.ts
> +       });
OK installing g++ fixed it. Not sure if that indicates an issue with the build scripts or the instructions.
`sudo apt-get install g++`
Once I did that on the Ubuntu VM I was able to build and test.
I have confirmed the test fails without the fix, and passes with the fix.

2020-02-25 10:07 UTC, gkalpak commented on packages/service-worker/worker/test/happy_spec.ts
> +       });
Thanks for figuring this out, @alexwiese :+1:

BTW, you shouldn't need `node ./scripts/build-packages-dist.js`. The `test` command should be a ble to build the necessary packages.

`g++` is indeed one of the required dependencies of bazel (see [here][1]).

(No idea where the other error came from - I've never seen that 😕)

[1]: https://docs.bazel.build/versions/master/install-ubuntu.html#step-1-install-required-packages

2020-02-25 10:08 UTC, gkalpak approved these changes

2020-02-25 21:10 UTC, closed without merging