Create tool to check for circular dependencies in source files
angular/angular pull request #35647
Opened 2020-02-24 11:27 UTC by devversion

Creates a tool for validating TypeScript circular dependencies. The tool
has been designed in a way that allows us to slowly burn down the amount
of circular dependencies while ensuring that we don't regress.

For more context. See: #35041 and [this comment](https://github.com/angular/angular/pull/34774#issuecomment-577237684).

2020-02-24 17:30 UTC, josephperrott reviewed
Before we approve and commit this, we are also talking about if this should actually live in dev-infra repo and then be depended on via npm.  So we can do the same process for components and tooling.

2020-02-24 17:30 UTC, josephperrott commented on tools/ts-circular-dependencies/index.ts
> +        chalk.green(`   Current amount of cycles: ${chalk.yellow(cycles.length.toString())}`));
Can we change this to be "Current number of cycles".

Additionally, can we always print out the number of cycles in the repo whenever the tool is run.

2020-02-24 19:46 UTC, devversion commented
@josephperrott I heard about these plans in the components sync. Concerns about not having another repository for this stuff had been raised. Also personally I'm slightly concerned about going through NPM since it could end up as with `ts-api-guardian` where it's difficult/non-standard process to get a release. It might be good to just use these things through a Bazel `http_repository`.

There are surely benefits/downsides but the primary benefit would be that we don't need any `builds` repositories for `dev-infra` and that we could easily use shared Bazel rules (like `npm_integration`).

Anyway though; TL;DR: Is there anything I need to do? Should I move this already over, or should we just get this started now and move it over once we decided on the process?

2020-02-25 13:47 UTC, devversion commented on packages/circular-dependencies-golden.json
> +[
Done. Added a small readme. I think the convention should be to have a description for each golden we add there. WDYT?

2020-03-17 13:49 UTC, devversion commented on package.json
> +    "ts-circular-deps": "ts-node dev-infra/ts-circular-dependencies/index.ts",
@josephperrott For now, until your packaging PR lands, I think we should be also fine just using `ts-node` here. It's minimal and allows us to test the changes immediately. We can always change that single line when we have the long-term plan.

2020-03-17 15:26 UTC, josephperrott requested changes

2020-03-17 15:26 UTC, josephperrott commented on dev-infra/BUILD.bazel
> +        ":cli",
Moving to a dependency on the ts_library outputs results in requiring the full umd name which doesn't work as needed.

For instance if you build the `npm_package` current and add it to try to run:
```sh
$ yarn -s ng-dev
/Users/jperrott/js/angular/node_modules/.bin/ng-dev: line 1: syntax error near unexpected token `('
/Users/jperrott/js/angular/node_modules/.bin/ng-dev: line 1: `(function (factory) {'
```

We might have to wait on https://github.com/bazelbuild/rules_typescript/pull/492 for us to be able to do something like this.

2020-03-17 15:28 UTC, devversion commented on package.json
> +    "ts-circular-deps": "ts-node dev-infra/ts-circular-dependencies/index.ts",
The generic one is actually used so that the `ts-node <..>` command doesn't need to be repeated all the time.

2020-03-17 17:20 UTC, devversion commented on dev-infra/BUILD.bazel
> +        ":cli",
I've explained in the commit message what the original problem was. There is nothing wrong with having the right AMD module paths. That's actually how the Angular NPM package output works too. The AMD module names just need to match the module name of the actual NPM package.

Also I added the shebang, so that it can be launched without having to use `node <script>`.

2020-03-17 18:37 UTC, josephperrott approved these changes
LGTM

2020-03-17 19:27 UTC, closed without merging