refactor(benchpress): delete perf_util.ts and moved it's content to e2e_util.ts
angular/angular pull request #35654
Opened 2020-02-24 22:09 UTC by wagnermaciel

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Currently we have our benchpress functions split into perf_util and e2e_util.

Issue Number: N/A

## What is the new behavior?
There is now only one file.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-02-24 22:17 UTC, wagnermaciel commented
This change was made with the purpose of making the external api more similar to the internal one so that syncing benchpress drivers can be as easy as possible.

2020-02-25 01:09 UTC, wagnermaciel commented
@jelbourn How do you feel about deleting the benchmarks_external folder?

- It hasn't been legitimately updated since [Mar 19, 2018](https://github.com/angular/angular/commits/eb8c5f709fd0da2b99ceba00d3704581aa8325e4/modules/benchmarks_external)
- It still uses `runClickBenchmark` which has not existed for a while. See [this example](https://github.com/angular/angular/blob/eb8c5f709fd0da2b99ceba00d3704581aa8325e4/modules/benchmarks_external/e2e_test/compiler_perf.ts#L9).

2020-02-25 19:12 UTC, jelbourn reviewed
Seems like that folder could be deleted if it's not even building

2020-02-25 19:12 UTC, jelbourn commented on modules/e2e_util/e2e_util.ts
> +import {SeleniumWebDriverAdapter, Options, JsonFileReporter, Validator, RegressionSlopeValidator, ConsoleReporter, SizeValidator, MultiReporter, MultiMetric, Runner, StaticProvider} from '@angular/be
I would put all of the `import` statements before any `require` statements

2020-02-25 19:12 UTC, jelbourn commented on modules/e2e_util/e2e_util.ts
> +// Note: Keep the `modules/benchmarks/README.md` file in sync with the supported options.
I would add a comment somewhere in this file that points out that it's important that `runBenchmark` and `openBrowser` are in the same file

2020-02-26 06:39 UTC, jelbourn approved these changes
LGTM

2020-02-26 06:39 UTC, jelbourn commented on modules/e2e_util/e2e_util.ts
> +// from the same file to match our internal API.
nit: I would say "Google-internal" to be explicit

2020-02-28 23:43 UTC, mhevery approved these changes

2020-02-28 23:44 UTC, mhevery requested changes
- [x]  either squash or use fixup! https://dev.to/koffeinfrei/the-git-fixup-workflow-386d. This is a single unit of work and should have single commit when merged.

2020-03-02 18:51 UTC, wagnermaciel commented
@mhevery Done

2020-03-03 22:01 UTC, mhevery approved these changes

2020-03-03 22:02 UTC, mhevery commented
LGTM, please add motivation to the commit msg.

2020-12-09 15:53 UTC, petebacondarwin commented
The code that is touched by this PR has been considerably modified (e.g. caa4ab323506538fb812b4835f9c0ba317a08648)
So this PR is no longer viable.

2020-12-09 15:53 UTC, closed without merging