fix(compiler): correct span for symbols in template expression
angular/angular pull request #35675
Opened 2020-02-25 23:25 UTC by kyliau

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-02-26 23:29 UTC, kyliau commented
reviewers: I had to disable one test and modify two others in language service, but fixing them in this PR would make it too big. Will submit subsequent PRs once this is merged.

2020-02-27 02:30 UTC, ayazhafiz requested changes

2020-02-27 02:30 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +        const source = this.input.substring(start - this.offset, this.peek(-1).end - this.offset);
I have longer term solution that will do this for all expressions in draft PR... interestingly its only blockers are template bindings!

2020-02-27 02:30 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +        const source = this.input.substring(start - this.offset, this.peek(-1).end - this.offset);
Can you add a TODO here to remove with #34690?

2020-02-27 02:30 UTC, ayazhafiz commented on packages/compiler/src/template_parser/binding_parser.ts
> + * Inline templates are, by definition, on the same line.
We also use inline templates to describe HTML templates declared on a component decorator. So maybe we can provide a less ambiguous name for this? Like inline expression or similar. Also, are we sure that template bindings can’t be stretched across multiple lines?

2020-02-27 02:30 UTC, ayazhafiz commented on packages/language-service/src/utils.ts
> +        path.push(ast);
TODO: test this util function

2020-02-28 00:08 UTC, kyliau reviewed
I cleaned up some changes in the "meat" of the PR in `parseTemplateBindings()` in `parser.ts` and added more comments. 
All Ayaz's comments have been addressed.

2020-02-28 02:21 UTC, AndrewKushnir requested changes
Great job @kyliau 👍 Also thanks for additional comments/documentation, it's very helpful.

I left a few comments, plz let me know if you have questions. Thank you.

2020-02-28 02:21 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/ast.ts
> +      public valueSpan?: ParseSourceSpan) {}
Quick question: the `sourceSpan` now only contains the var itself and `valueSpan` - the value (if present). If I understand correctly, the `sourceSpan` used to have a meaning of the "span for entire expression". For example, it looks like the case for `TemplateBinding` class above. If my understanding is correct, I'd propose to keep things aligned, where `sourceSpan` is the entire span and introduce extra spans (as needed) for pieces of the expression (like `keySpan`, `valueSpan`). WDYT?

2020-02-28 02:21 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +   */
Thanks for all the comments Keen, great job 👍

2020-02-28 02:21 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +      absoluteKeyOffset: number): TemplateBindingParseResult {
really minor nit: I'd propose to put `absoluteKeyOffset` first and `absoluteValueOffset` second (to respect the order in which they appear in expression).

2020-02-28 02:21 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> -          name = '\$implicit';
Just curios: why backslash is not needed? :)

2020-02-28 02:21 UTC, AndrewKushnir commented on packages/compiler/src/template_parser/binding_parser.ts
> +      const valueSpan = binding.expression ?
It looks like `valueSpan` is used in 2 out of 3 cases below. Would it make sense to move calculation to respective branches (1 and 2)? In the second branch the `binding.expression` check would not be required (as it's a condition to enter the branch).

2020-02-28 02:21 UTC, AndrewKushnir commented on packages/compiler/src/template_parser/binding_parser.ts
> + * @param sourceSpan original source span of the attribute
May be add a new line between function description and first `@param`?

2020-02-28 04:05 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> +      absoluteKeyOffset: number): TemplateBindingParseResult {
done.

2020-02-28 04:06 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> -          name = '\$implicit';
backslash is used to escape the character, but in javascript string '$' has no special meaning so whether it is escaped or not does not make any difference.

2020-02-28 04:07 UTC, kyliau commented on packages/compiler/src/template_parser/binding_parser.ts
> + * @param sourceSpan original source span of the attribute
done

2020-02-29 14:08 UTC, ivanwonder commented on packages/compiler/test/render3/r3_ast_spans_spec.ts
> +        ['Variable', '20:25', '<empty>'],     // local
```
['Variable', '20:25', '6:10'],     // local -> ngIf
```
https://angular.io/guide/structural-directives#microsyntax-examples
I dont know if the position `6:10` is suitable here. But I think the `local` should not be empty. It points to `ngIf`.🤔

2020-02-29 18:38 UTC, kyliau commented on packages/compiler/test/render3/r3_ast_spans_spec.ts
> +        ['Variable', '20:25', '<empty>'],     // local
yes this is a bug :) I'll fix this in the following fixup!

2020-04-30 21:33 UTC, closed without merging