docs: edit copy for tick() in testing and api docs
angular/angular pull request #35697
Opened 2020-02-26 21:45 UTC by kapunahelewong

Fixes #35696

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #35696

## What is the new behavior?

Style/copy edits to recent PR https://github.com/angular/angular/pull/33838

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-02-26 21:55 UTC, mary-poppins commented
You can preview 111004d at https://pr35697-111004d.ngbuilds.io/.

2020-02-26 21:57 UTC, aikidave commented on aio/content/guide/testing.md
> +The [tick()](api/core/testing/tick) function accepts milliseconds (`millis`) and `tickOptions` as parameters.
Why do we offer the abbreviation, `millis`?

2020-02-26 21:57 UTC, aikidave commented on aio/content/guide/testing.md
> +The milliseconds parameter represents how much the virtual clock advances and defaults to 0.
For clarity: Change "...and defaults to 0." to ". The default value is 0."

2020-02-26 21:57 UTC, aikidave commented on aio/content/guide/testing.md
>  You do have to call [tick()](api/core/testing/tick) to advance the (virtual) clock.
"do have to" -> "must"

2020-02-26 21:57 UTC, aikidave commented on aio/content/guide/testing.md
> +The optional `tickOptions` parameter with a property called `processNewMacroTasksSynchronously`, which defaults to true, specifies whether to invoke
"The optional `tickOptions` parameter, has a property called `processNewMacroTasksSynchronously`.."

Seems like we're missing a word in the current version.

2020-02-26 22:20 UTC, kapunahelewong commented on aio/content/guide/testing.md
> +The [tick()](api/core/testing/tick) function accepts milliseconds (`millis`) and `tickOptions` as parameters.
It's the official name of the parameter. See here: https://angular.io/api/core/testing/tick

@JiaLiPassion, please correct me if I'm misunderstanding.

2020-02-26 23:18 UTC, JiaLiPassion commented on aio/content/guide/testing.md
> +The [tick()](api/core/testing/tick) function accepts milliseconds (`millis`) and `tickOptions` as parameters.
@kapunahelewong , yes, you are right , the name of the parameter is `millis`.

2020-02-26 23:50 UTC, JiaLiPassion approved these changes

2020-02-27 18:52 UTC, mhevery approved these changes

2020-02-28 15:14 UTC, gkalpak submitted a review, later dismissed
Nice! I just noticed this yesterday and wanted to open a PR about this. (Glad you beat me to it 😇)

2020-02-28 15:14 UTC, gkalpak commented on packages/core/testing/src/fake_async.ts
> + * new macroTasks. The default is
Unnecessary like break.

2020-02-28 15:14 UTC, gkalpak commented on packages/core/testing/src/fake_async.ts
> + * @param tickOptions, the options of `tick()`, which has a flag called
Not sure exactly what is wrong (maybe the commas after the param names), but these docs do not seem to be included on the API docs.

2020-02-28 15:14 UTC, gkalpak commented on packages/core/testing/src/fake_async.ts
> + * false, which means that new macroTasks will be invoked.
Well, actually...the default is not exactly false :grin:

If you provide a `tickOptions` object, but do not specify a `processNewMacroTasksSynchronously` property (e.g. `tick(100, {})`), then `processNewMacroTasksSynchronously` does indeed default to false. But if you omit the `tickOptions` param altogether (which is the most common usecase - e.g. `tick(100)`), then `tickOptions` defaults to `{processNewMacroTasksSynchronously: true}`, which means `processNewMacroTasksSynchronously` will be `true`.

##
TBH, this looks more like an implementation issues than a documentation issue. (Not sure what the intended default is, but that should be consistent with both `tick(100)` and `tick(100, {})`.)

cc @JiaLiPassion

2020-03-02 18:04 UTC, jbogarthyde commented on packages/core/testing/src/fake_async.ts
> + * @param tickOptions, the options of `tick()`, which has a flag called
Move the param descriptions up before `@usageNotes`, like this:
```
@param fn A function that takes to arguments. 
  * *millis* The number of milliseconds to advance the virtual timer.
  * *tickOptions* The options to pass to the `tick()` function.
```
Then put the rest of the advice about using the options into the `@usageNotes` (rephrasing as appropriate and responding to George's notes 😄 )

2020-03-02 19:42 UTC, mary-poppins commented
You can preview 7eaef73 at https://pr35697-7eaef73.ngbuilds.io/.

2020-03-02 20:23 UTC, JiaLiPassion commented on packages/core/testing/src/fake_async.ts
> + * false, which means that new macroTasks will be invoked.
@gkalpak , yes, you are right, I agree with you, especially we may provide more options as properties of `tickOptions`. I will create a PR to fix this one. Thank you!

2020-03-02 21:04 UTC, mary-poppins commented
You can preview f08aba3 at https://pr35697-f08aba3.ngbuilds.io/.

2020-04-16 15:47 UTC, mary-poppins commented
You can preview 85187a0 at https://pr35697-85187a0.ngbuilds.io/.

2021-04-23 18:06 UTC, TeriGlover approved these changes
LGTM

2021-04-26 15:25 UTC, mary-poppins commented
You can preview 40d1942 at https://pr35697-40d1942.ngbuilds.io/.

2021-04-26 16:08 UTC, petebacondarwin requested changes

2021-04-26 16:08 UTC, petebacondarwin commented on packages/core/testing/src/fake_async.ts
> + * * *tickOptions* The options to pass to the `tick()` function.
This is not correct. There is no `fn` parameter.
`tick()` accepts the two parameters: `millis` and `tickOptions` directly.

2021-04-26 16:08 UTC, petebacondarwin commented on packages/core/testing/src/fake_async.ts
>   * @returns The function wrapped to be executed in the fakeAsync zone
It may be worth saying that any arguments passed when calling this returned function will be passed through to the `fn` function in the parameters when it is called.

2021-04-28 19:29 UTC, mary-poppins commented
You can preview 84742d9 at https://pr35697-84742d9.ngbuilds.io/.

2021-04-30 22:46 UTC, JiaLiPassion commented on packages/core/testing/src/fake_async.ts
> + * then `processNewMacroTasksSynchronously` defaults to false.
Even the user provides a `tickOptions` object without a `processNewMacroTAsksSynchronously` property, the `processNewMacroTAsksSynchronously` defaults is still be true. Just like not providing the `tickOptions`, this is fix  in the PR https://github.com/angular/angular/pull/35814.

2021-05-06 14:44 UTC, mary-poppins commented
You can preview 80e0a63 at https://pr35697-80e0a63.ngbuilds.io/.

2021-05-24 21:36 UTC, mary-poppins commented
You can preview 6b36b4f at https://pr35697-6b36b4f.ngbuilds.io/.

2021-05-24 22:06 UTC, petebacondarwin approved these changes
Just one small suggestion. But otherwise nice tidy up.

2021-05-24 22:06 UTC, petebacondarwin commented on packages/core/testing/src/fake_async.ts
> + * @param maxTurns A maximum number of turns.
So digging through the code, I think that `maxTurns` is basically the maximum number of times the scheduler will attempt to clear its queue before it gives up with an error. It's a kind of Time To Live (TTL) number.

2021-05-24 22:21 UTC, AndrewKushnir approved these changes

2021-05-24 22:25 UTC, mary-poppins commented
You can preview c5b31ca at https://pr35697-c5b31ca.ngbuilds.io/.

2021-05-25 18:03 UTC, closed without merging