perf(ngcc): reduce directory traversing
angular/angular pull request #35756
Opened 2020-02-28 14:38 UTC by alan-agius4

WIP!

This reduces the time that `findEntryPoints` takes from `9701.143ms` to `5155.315ms`
Need to add tests!. 

Just checking what breaks in CI :)

2020-03-02 10:33 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/entry_point.ts
> + * otherwise.
Could you be a bit more explicit by what "not an entry-point" and "otherwise" mean?
* `undefined`: there is no package.json at the path and there is no config to force an entry-point
* `null`: there is a package.json but it is not a valid Angular compiled entry-point

2020-03-02 10:34 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts
Can we have a test for the case when `null` is returned?

2020-03-02 11:26 UTC, alan-agius4 commented on packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts
There is https://github.com/angular/angular/blob/5bc39f8c8d5238a9be9bd968cf18ea4b738bd6be/packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts#L58

2020-03-03 09:03 UTC, alan-agius4 commented on packages/compiler-cli/ngcc/src/packages/entry_point.ts
> + * otherwise.
Updated!

2020-03-03 13:11 UTC, petebacondarwin requested changes
Thanks for this work @alan-agius4 - I can already see we will get benefits from this.

I get very nervous when we have code that starts using `null` and `undefined` to mean significant things. They are too magical and it is not easy to see immediately what they mean.

How about we modify the return value of these functions to be an object that has various flags to indicate the state of the result?

2020-03-03 13:11 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.ts
> +          if (containsEntryPoint) {
This check seems suspicious... isn't it possible to have an entry-point more than one directory below the package with no entry-point in between? E.g. `package/directory/entry-point`?

2020-03-03 13:11 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts
...except that you have changed that test to check for `undefined`!

2020-03-03 13:25 UTC, alan-agius4 commented on packages/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.ts
> +          if (containsEntryPoint) {
I guess there is nothing to stop a user from creating such format, though I don't think I ever saw this.

2020-03-03 13:25 UTC, alan-agius4 commented
Test for `null` -> https://github.com/angular/angular/blob/41b5b2714eb19a4dea334a92bccf1cb4ac66f214/packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts#L168

> I get very nervous when we have code that starts using null and undefined to mean significant things. They are too magical and it is not easy to see immediately what they mean.

Totally agree, though my worry would be that this will require some refactoring in the tests mainly. I'll look at this tomorrow.

2020-03-03 13:26 UTC, alan-agius4 commented on packages/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.ts
> +          if (containsEntryPoint) {
And in such case most likely it will get transformed by the sync version of the NGCC, when integrated with the CLI.

2020-03-03 13:29 UTC, alan-agius4 commented on packages/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.ts
> +      const nestedNodeModulesPath = this.fs.join(sourceDirectory, 'node_modules');
I was thinking of adding a check here, that we only try to traverse nested  `node_modules`, if one of the entrypoints is compiled by Angular.

It is very unlikely that a non Angular entry point has a dependency on an Angular library. 

Thoughts @petebacondarwin?

2020-03-03 14:15 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.ts
> +      const nestedNodeModulesPath = this.fs.join(sourceDirectory, 'node_modules');
I was thinking about this too. There is a very small chance, maybe, that someone creates a holding library that aggregates together a bunch of Angular libraries and re-exports them. But I think that this might well break ngcc anyway, since we would need to process the re-exported typings for it to work with ngtsc anyway.

So perhaps we can go with this idea.

2020-03-04 19:02 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.ts
> +
I know these extra blank lines are added by clang but you can remove them as they are uneeded, especially the one below.

2020-03-05 10:14 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.ts
> +          if (containsEntryPoint) {
OK let's go with this for now and revert if we get a complaint.

2020-03-05 10:15 UTC, petebacondarwin approved these changes

2020-03-05 20:57 UTC, closed without merging