refactor(compiler): Break up parseTemplateBindings() for microsyntax
angular/angular pull request #35812
Opened 2020-03-03 00:44 UTC by kyliau

This commit is purely a refactoring of the logic in
`parseTemplateBindings` method for parsing the microsyntax expression.
This is done to enable the introduction of `keySpan` and `valueSpan` in
subsequent PR.

For a detailed explanation of this work and the subsequent work items,
please see https://docs.google.com/document/d/1mEVF2pSSMSnOloqOPQTYNiAJO0XQxA1H0BZyESASOrE/edit?usp=sharing

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-03-03 02:38 UTC, AndrewKushnir requested changes
Thanks a lot for separating this change out in a standalone PR @kyliau!

FYI I've added a few comments, nothing major, but may worth looking into.

Thank you.

2020-03-03 02:38 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +   * Parse microsyntax template expression and return errors, if any.
May be rephrase this a bit to say something like:
```
Parse microsyntax template expression and return either an AST that represents this expression or parsing errors in case given expression in invalid.
```

2020-03-03 02:38 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +   * @param location
Can we add a quick description of what this parameter is (to be consistent with other params)?

2020-03-03 02:38 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +    if (rawKey !== templateKey) {
Just wondering in which case it would not be the case (may be add a comment on this)?

2020-03-03 02:38 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +    const asBinding = this.parseValueAsKey(key, rawKeySpan, absoluteOffset);
I was a bit confused by the function name (it sounds like we parse a value as a key) :) May be we can rename it to be more clear on what "as" stands for in function name, like `parseValueOfAsExpression`?

2020-03-03 02:38 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +    if (!this.optionalCharacter(chars.$SEMICOLON)) {
I think this if statement might benefit from additional comments.

2020-03-03 02:38 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +  private parseLetDeclaration(): TemplateBinding|undefined {
I glanced over other functions in the `parser.ts` script and it looks like we typically return `null` when we hit exit condition without any work performed. I think we should follow this in the newly added functions as well.

2020-03-03 03:57 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +   *                ^ absoluteOffset for `tplValue`
Consider mentioning that absoluteOffset is the start of the template binding relative to the start of the source file it's in. This example doesn't make it clear what absoluteOffset actually is.

2020-03-03 03:57 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
>     * An identifier, a keyword, a string with an optional `-` in between.
```suggestion
   * Parses an identifier, a keyword, a string with an optional `-` in between.
```

2020-03-03 03:57 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +   * Parses the bindings for microsyntax `<some-tag *tplKey=AST>`
```suggestion
   * Parses the bindings for a microsyntax expression; e.g. the AST in <some-tag *tplKey=AST>
```

2020-03-03 03:57 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +   * ```
Maybe add an example of what we expect to be parsed out of here? (let items, of expression, "as i" expression, trackBy key expression)

2020-03-03 03:57 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +        const {key, keySpan} = this.expectTemplateBindingKey();
Why do we expect a template binding key if this is not a let expression?

2020-03-03 03:57 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +      this.optionalCharacter(chars.$COLON);  // trackBy: trackByFunction
We should probably rename this to consumeOptionalCharacter or similar

2020-03-03 03:57 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +    if (!this.optionalCharacter(chars.$SEMICOLON)) {
+1 and consider renaming to consumeOptionalCharacter

2020-03-03 03:57 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +      TemplateBinding|undefined {
nit for consistency

```suggestion
      TemplateBinding|null {
```

2020-03-03 03:57 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +  private parseLetDeclaration(): TemplateBinding|undefined {
+1

2020-03-03 20:09 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> +    if (!this.optionalCharacter(chars.$SEMICOLON)) {
Will rename this in standalone PR

2020-03-03 20:09 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> +  private parseLetDeclaration(): TemplateBinding|undefined {
done

2020-03-03 21:16 UTC, kyliau commented
I've addressed all comments, PTAL.
After an offline discussion with @AndrewKushnir, I went back to look at the existing test suites for the expression parser, and found that while there are many test cases, all of them are "fictional", so I added some test cases that better represent real world usage of the two most common microsyntax directives - `ngIf` and `ngFor`.
Please let me know what you think, thank you!

2020-03-04 02:33 UTC, AndrewKushnir requested changes

2020-03-04 02:33 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +   * @param templateUrl template filename if it's external, component filename if it's inline
nit: I assume `tpl` in `tplKey` and `tplValue` is a short version of `template`. If that's the case, the `templateUrl` (with full `template` word) seems a bit inconsistent. I think `location` (that you had before) was fine, it just needed a `@param` description.

2020-03-04 02:33 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +   * contains three bindings:
May be we can also include the de-sugared version of the same example (de-sugar the `*ngFor`), so it'd be clear why we have 3 bindings?

2020-03-04 02:33 UTC, AndrewKushnir commented on packages/compiler/test/expression_parser/parser_spec.ts
> +    it('should support common usage of ngIf', () => {
Thanks for adding extra tests! 👍

2020-03-04 02:33 UTC, AndrewKushnir commented on packages/compiler/test/expression_parser/parser_spec.ts
> +        const value = keyIsVar ? name : expression ? expression.source : expression;
May be wrap inner ternary expression into `()`, so that it's easier to read?

2020-03-04 02:33 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +    if (!this.optionalCharacter(chars.$SEMICOLON)) {
@kyliau could you plz add a quick comment on why this `if` statement is here and what's the goal? (I agree that renaming `optionalCharacter` can be a part of a separate PR).

2020-03-04 03:32 UTC, kyliau reviewed
Addressed Andrew's comments

2020-03-04 03:32 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> +   * contains three bindings:
done

2020-03-04 03:32 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> +   * @param templateUrl template filename if it's external, component filename if it's inline
I prefer `templateUrl` over `location`, as the former is less ambiguous. To keep everything consistent I renamed `tplKey` and `tplValue` to `templateKey` and `templateValue`, respectively.

2020-03-04 03:32 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> +    if (!this.optionalCharacter(chars.$SEMICOLON)) {
Instead of a comment, I refactored this into a standalone method called `consumeStatementTerminator()` and added documentation there.

2020-03-04 03:32 UTC, kyliau commented on packages/compiler/test/expression_parser/parser_spec.ts
> +        const value = keyIsVar ? name : expression ? expression.source : expression;
done. Actually, I'd like to use optional chaining and nullish coalescing here, but our version of clang-format doesn't support this yet. I filed a bug with dev infra.

2020-03-04 07:05 UTC, AndrewKushnir approved these changes
Thanks for addressing all the comments @kyliau and once again thanks for additional documentation and tests 👍 The changes LGTM, but as we discussed offline, it'd be great if @alxhub would have a look at this PR too, since this PR touches pretty fundamental expression parsing logic (adding Alex as a reviewer to this PR). Thank you.

2020-03-04 07:05 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +   * 1. ngFor -> null
May be add de-sugared version here as well?

2020-03-04 08:42 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +   *                ^ absoluteOffset for `tplValue`
No, there is no other meaning. I just mean that the comment is non-obvious in that it doesn't tell us much about why the absoluteOffset is noted in the example and why it would be useful. I think it would be helpful to add this information to the comment. But this is a nit.

2020-03-04 08:42 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +   * 1. ngFor -> null
Also, consider adding a link to the template syntax grammar (https://angular.io/guide/structural-directives#grammar or https://gist.github.com/mhevery/d3530294cff2e4a1b3fe15ff75d08855). It may not be immediately clear why the binding for ngFor is null.

2020-03-04 08:42 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +        // Two possible cases here, either "value as key" or
nit: 
```suggestion
        // Two possible cases here, either `value "as" key` or
```

to make more clear that "as" is a literal rather than a variable. If you choose to apply this, the next two lines should be updated too.

2020-03-04 08:42 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +          // the key to actual key. Eg. of -> ngForOf, trackBy -> ngForTrackBy
nice comment!

2020-03-04 08:42 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +   * ```
Is this always the case? For example, in the branch on line 801 - 810, it looks like the value could be "cond | pipe". Maybe there is a better way to name this function, like `parseAsBinding`?

2020-03-04 21:58 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> +   *                ^ absoluteOffset for `tplValue`
ah I see what you mean. `absoluteOffset` is actually an input parameter to this function, which is why I called it out in the example. I've quoted it in backticks to make this more obvious. Let me know if this is better.
(in the next PR I'm going to differentiate between absoluteKeyOffset and absoluteValueOffset)

2020-03-04 21:59 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> +   * 1. ngFor -> null
added the second link

2020-03-04 22:47 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> +   * ```
No, the value cannot be "cond | pipe". In an "as" binding **that follows an expression**, the value is always the template key (ngFor, ngForOf, etc). This is documented in `parseDirectiveKeyword`. I've updated the example here to reflect the case in line 801-810.

2020-03-04 22:52 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> +   * ```
I've renamed
1. `parseDirectiveKeyword` -> `parseDirectiveKeywordBindings`
2. `parseLetDeclaration` -> `parseLetBinding`
3. `parseValueAsKey` -> `parseAsBinding`

Note that (1) is in plural form to reflect the fact that there could be two bindings.

2020-03-04 23:07 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +
Missing `*` char.

2020-03-04 23:07 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +
Missing `*` char.

2020-03-04 23:07 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +
Missing `*` char.

2020-03-04 23:57 UTC, alxhub approved these changes
Fantastic work!

2020-03-05 00:15 UTC, kyliau commented
g3 presubmit: http://test/OCL:298480280:BASE:298966468:1583367302889:60602a0a

2020-03-05 02:55 UTC, ayazhafiz approved these changes

2020-03-05 21:04 UTC, closed without merging