feat(bazel): transform generated shims (in Ivy) with tsickle
angular/angular pull request #35848
Opened 2020-03-04 01:37 UTC by alxhub

Currently, when Angular code is built with Bazel and with Ivy, generated
factory shims (.ngfactory files) are not processed via the majority of
tsickle's transforms. This is a subtle effect of the build infrastructure,
but it boils down to a TsickleHost method `shouldSkipTsickleProcessing`.

For ngc_wrapped builds (Bazel + Angular), this method is defined in the
`@bazel/typescript` (aka bazel rules_typescript) implementation of
`CompilerHost`. The default behavior is to skip tsickle processing for files
which are not present in the original `srcs[]` of the build rule. In
Angular's case, this includes all generated shim files.

For View Engine factories this is probably desirable as they're quite
complex and they've never been tested with tsickle. Ivy factories however
are smaller and very straightforward, and it makes sense to treat them like
any other output.

This commit adjusts two independent implementations of
`shouldSkipTsickleProcessing` to enable transformation of Ivy shims:

* in `@angular/bazel` aka ngc_wrapped, the upstream `@bazel/typescript`
  `CompilerHost` is patched to treat .ngfactory files the same as their
  original source file, with respect to tsickle processing.

  It is currently not possible to test this change as we don't have any test
  that inspects tsickle output with bazel. It will be extensively tested in
  g3.

* in `ngc`, Angular's own implementation is adjusted to allow for the
  processing of shims when compiling with Ivy. This enables a unit test to
  be written to validate the correct behavior of tsickle when given a host
  that's appropriately configured to process factory shims.

For ngtsc-as-a-plugin, a similar fix will need to be submitted upstream in
tsc_wrapped.

2020-03-04 01:41 UTC, alxhub commented
I intend to run a global presubmit on this PR.

2020-03-04 01:52 UTC, alxhub commented
[Presubmit(normal)](http://test/OCL:298735704:BASE:298736582:1583286737814:cb5618b3)

2020-03-05 18:41 UTC, alxhub commented
[Presubmit(global)](https://test.corp.google.com/ui#id=OCL:299029045:BASE:299029499:1583393104423:5d45a80c)

2020-03-06 18:25 UTC, AndrewKushnir requested changes
Thanks for a very detailed description of the problem and the fix @alxhub 👍 

I've left a couple comments, could you plz have a look? Thank you.

2020-03-06 18:25 UTC, AndrewKushnir commented on packages/bazel/src/ngc-wrapped/index.ts
> +      return delegate(fileName.replace(/\.(ngfactory|ngsummary)\.ts$/, ''));
The string replace operation will also strip `.ts` extension, i.e. `test.ngfactory.ts` -> `test`. If this is desirable, let's may be  update a comment above (last sentence) to say that we also strip the `.ts` part of the filename?

2020-03-06 18:25 UTC, AndrewKushnir commented on packages/compiler-cli/src/main.ts
> +    shouldSkipTsickleProcessing: (fileName) => /\.d\.ts$/.test(fileName) ||
May be add a quick comment here too on why we exclude generated files from Tsickle processing in VE? It's explained in the PR description and I think it'd be great to have a quick note here as well.

2020-03-06 18:25 UTC, AndrewKushnir commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +
nit: extra empty line

2020-03-06 21:02 UTC, alxhub commented on packages/bazel/src/ngc-wrapped/index.ts
> +      return delegate(fileName.replace(/\.(ngfactory|ngsummary)\.ts$/, ''));
Fixed!

2020-03-06 21:07 UTC, alxhub commented
[Presubmit](http://test/OCL:299029045:BASE:299419231:1583528823927:d03654a8) with the minor changes.

2020-03-06 21:08 UTC, AndrewKushnir approved these changes
LGTM, thanks for updates @alxhub! 👍

2020-03-07 14:49 UTC, IgorMinar approved these changes
lgtm - thanks!!

2020-03-07 14:50 UTC, IgorMinar commented
@alxhub consider making this a master&patch PR

2020-03-09 17:06 UTC, closed without merging

2020-03-09 17:52 UTC, EatingW commented
Thanks, Alex!