fix(core): ngOnDestroy on multi providers called with incorrect context
angular/angular pull request #35840
Opened 2020-03-03 20:06 UTC by crisbeto

Currently destroy hooks are stored in memory as `[1, hook, 5, hook]` where the numbers represent the index at which to find the context and `hook` is the function to be invoked. This breaks down for `multi` providers, because the value at the index will be an array of providers, resulting in the hook being invoked with an array of all the multi provider values, rather than the provider that was destroyed. In ViewEngine `ngOnDestroy` wasn't being called for `multi` providers at all.

These changes fix the issue by changing the structure of the destroy hooks to `[1, hook, 5, [0, hook, 3, hook]]` where the indexes inside the inner array point to the provider inside of the multi provider array. Note that this is slightly different from the original design which called for the structure to be `[1, hook, 5, [hook, hook]`, because in the process of implementing it, I realized that we wouldn't get passing the correct context if only some of the `multi` providers have `ngOnDestroy` and others don't.

I've run the newly-added `view_destroy_hooks` benchmark against these changes and compared it to master. The difference seems to be insignificant (between 1% and 2% slower).

Fixes #35231.

2020-03-04 15:59 UTC, pkozlowski-opensource commented on packages/core/src/render3/di_setup.ts
> +          (hooks[existingCallbacksIndex + 1] as(number | (() => void))[])
nit: do you think it would make sense to create a type / types for  `(number | (() => void))[])`? We seem to be using similar casts in other places and having a type with a name / description would aid understanding, maybe?

2020-03-04 16:00 UTC, crisbeto commented on packages/core/src/render3/di_setup.ts
> +          (hooks[existingCallbacksIndex + 1] as(number | (() => void))[])
It would definitely make things easier to read, but I'm not sure what we'd call it.

2020-03-11 14:40 UTC, pkozlowski-opensource commented on packages/core/src/render3/di_setup.ts
> +          (hooks[existingCallbacksIndex + 1] as(number | (() => void))[])
Right. So I think that we've got multiple types here:

* `HookCallback` / `HookFn`: `() => void`
* `HookEntry` / `HookData`: `number | HookFn`
* `HooksData` / `Hooks`: `HookData[]`
* `DestroyHookData`: (HookData | HookData[])[]

This is just hand-wavy proposal but yeh, I've found the current types and type casts hard to read.

2020-03-11 14:41 UTC, pkozlowski-opensource requested changes
The change LGTM overall but I _really_ think that we should adjust types as the code gets hard to follow. I've suggested some adjustments but I think that you've got more context than me at this point.

Happy to chat more about it if needed.

2020-03-12 20:16 UTC, crisbeto commented
Thank you for the feedback @pkozlowski-opensource, it definitely made it easier to follow 👍 Can you take another look?

Also regarding the payload increase, I think it's due to master being right on the edge, rather than the changes in this PR which are fairly minimal and don't introduce new dependencies.

2020-03-13 07:42 UTC, pkozlowski-opensource approved these changes
LGTM, you might consider adding an example (see the comment in-line)

2020-03-13 07:42 UTC, pkozlowski-opensource commented on packages/core/src/render3/interfaces/view.ts
> + */
nit: I think that it would be good to add an example, showing an example service(s) and the LView structure.

2020-03-13 15:28 UTC, crisbeto commented on packages/core/src/render3/interfaces/view.ts
> + */
Added.

2020-03-13 22:45 UTC, kara requested changes
A few minor things

Can we also add a note to the commit that notes the differences from VE and how we expect this fix to make it more compatible?

2020-04-04 08:56 UTC, crisbeto commented
Sorry for the increased diff, `clang-format` reformatted all the files I touched after I rebased. The formatting changes are in the last `fixup` commit and my latest changes are in the second-to-last commit.

2020-04-06 16:10 UTC, kara approved these changes
LGTM

(George shouldn't need to approve this one since AIO is only size changes)

Reviewed-for: global-approvers

2020-04-06 16:18 UTC, kara commented
[presubmit](http://test/OCL:305044634:BASE:305044655:1586189869333:3d7d903e)

2020-04-06 22:29 UTC, kara commented
@crisbeto Just realized the commit message hasn't been updated yet. Can you update it re https://github.com/angular/angular/pull/35840#pullrequestreview-374620905

2020-04-07 16:05 UTC, crisbeto commented
Fixed @kara. I had to squash the commits myself, because I messed up the initial rebase.

2020-04-07 17:31 UTC, closed without merging