Public API guard for angularCompilerOptions
angular/angular pull request #35885
Opened 2020-03-05 22:43 UTC by alxhub

Refactor and introduction of a public API guard for `angularCompilerOptions` in tsconfig.

2020-03-06 18:43 UTC, JoostK requested changes
Some minor comments. Also, merging this needs to be coordinated with #35768.

2020-03-06 18:43 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/core/api/src/options.ts
> +  preserveWhitespaces?: boolean;
This was here before this change, but this option is already declared in `LegacyNgOptions`.

2020-03-06 18:43 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/core/api/src/options.ts
> +  disableTypeScriptVersionCheck?: boolean;
This one should probably be under the public API guard.

2020-03-06 18:43 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/core/api/src/public_options.ts
> + * @publicApi
This is here for the golden generation to include this type, however the type itself is not really public API from a programmatic usage perspective. I'm not sure what can be done about it, but maybe include a disclaimer in the comment.

2020-03-06 20:59 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/core/api/src/public_options.ts
> + * @publicApi
There is no exported API/documentation generated for these types anyway, so the marker is more "in spirit".

2020-03-06 21:14 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/core/api/src/options.ts
> +  preserveWhitespaces?: boolean;
Good catch - deleted.

2020-03-06 21:14 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/core/api/src/options.ts
> +  disableTypeScriptVersionCheck?: boolean;
Done.

2020-03-06 21:40 UTC, JoostK approved these changes
LGTM

2020-03-06 21:40 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/core/api/src/public_options.ts
> + * @publicApi
True, true

2020-03-06 21:46 UTC, alxhub commented
[Presubmit](http://test/OCL:299424667:BASE:299424701:1583530293538:c4eb3453)

2020-03-09 17:04 UTC, IgorMinar approved these changes
lgtm for public api changes/tracking. thanks!

2020-03-10 16:39 UTC, gkalpak approved these changes

2020-03-10 18:15 UTC, closed without merging