refactor(core): misc refactoring to support upcoming changes to improve synthetic host bindings
angular/angular pull request #35884
Opened 2020-03-05 22:34 UTC by AndrewKushnir

This commit performs a few updates to internal functions that would be required in upcoming changes to support synthetic host bindings in Directives.

* the `elementPropertyInternal` function was refactored to accept renderer as an argument (prior to that, there was a function that loads the renderer in some specific way for animation bindings)
* `elementPropertyInternal`, `elementAttributeInternal` and `listenerInternal` functions were updated to have a fixed set of arguments (for better performance)
* `elementPropertyInternal` and `elementAttributeInternal` functions were updated to take `tNode` as an argument instead of passing node index (that was used to retrieve `tNode` internally), in some cases we already have `tNode` available or we can retrieve it from the state

The refactoring was triggered by the need to pass different renderers to the `elementPropertyInternal` to support synthetic host bindings in Directives (see this comment for additional context: https://github.com/angular/angular/pull/35568/files#r388034584).

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-03-06 21:46 UTC, mhevery requested changes

2020-03-06 21:46 UTC, mhevery commented on packages/core/src/render3/instructions/attribute_interpolation.ts
> +        tNode, lView, attrName, interpolatedValue, sanitizer || null, namespace || null);
Not sure I am fan of the `|| null` pattern. Could we just make `elementAttributeInternal` take `undefined` as well? Not sure what the right answer is, just asking.

2020-03-06 21:46 UTC, mhevery commented on packages/core/src/render3/state.ts
> +  return getTNode(instructionState.lFrame.tView, instructionState.lFrame.selectedIndex);
```suggestion
  const lFrame = instructionState.lFrame;
  return getTNode(lFrame.tView, lFrame.selectedIndex);
```

2020-03-07 02:19 UTC, AndrewKushnir commented
Thanks for the review @mhevery. I've applied the changes based on your feedback. Could you please take another look when you get a chance? Thank you.

2020-03-11 22:57 UTC, mhevery approved these changes

2020-03-11 22:57 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +    sanitizer?: SanitizerFn | null, nativeOnly?: boolean): void {
I see these are optional as well. Not sure if you want to take on them or not.

2020-03-11 22:57 UTC, mhevery commented on packages/core/src/render3/instructions/shared.ts
> +    namespace?: string | null) {
same here, optional args.

2020-03-11 22:57 UTC, mhevery commented on packages/core/src/render3/state.ts
> +
nit: revert extra blank line

2020-03-11 23:38 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:300433799:BASE:300433828:1583969868877:9a619582)

2020-03-13 08:22 UTC, pkozlowski-opensource requested changes
I'm marking this PR as "Request changes" since I would like to discuss some of the refactorings with @AndrewKushnir .

More specifically, I see how the "the elementPropertyInternal function was refactored to accept renderer as an argument (prior to that, there was a function that loads the renderer in some specific way for animation bindings)" refactoring is useful / required but I'm less convinced about other ones.

Also, would love to learn more about "elementPropertyInternal, elementAttributeInternal and listenerInternal functions were updated to have a fixed set of arguments (for better performance)" - I'm curious about the benchmark that showed the speed-up and the exact numbers.

Finally I'm not sure how I feel abut "elementPropertyInternal and elementAttributeInternal functions were updated to take tNode as an argument instead of passing node index (that was used to retrieve tNode internally), in some cases we already have tNode available or we can retrieve it from the state" - it seems to me like previously we were getting `TNode` instance only in dev mode (this is the only place where we need it, right?) but now we do so systematically. Would love to chat about it more!

I think that it would be _much_ better to split this PR into multiple commits (one per refactoring) if possible to aid reviewing.

2020-03-13 22:16 UTC, AndrewKushnir commented
Hi @pkozlowski-opensource, thanks for the review and comments. Please see replies below.

> Also, would love to learn more about "elementPropertyInternal, elementAttributeInternal and listenerInternal functions were updated to have a fixed set of arguments (for better performance)" - I'm curious about the benchmark that showed the speed-up and the exact numbers.

Prior to this change, the `elementPropertyInternal` and `elementAttributeInternal` functions were sometimes called with variable number of arguments, since function signature allowed it (there was a couple optional arguments at the end of these functions). This refactoring enforces the presence of all arguments. I don't have exact numbers (perf was not the main goal of this refactoring), but I can run a suite of micro benchmarks to see if there is any noticeable impact.

> Finally I'm not sure how I feel abut "elementPropertyInternal and elementAttributeInternal functions were updated to take tNode as an argument instead of passing node index (that was used to retrieve tNode internally), in some cases we already have tNode available or we can retrieve it from the state" - it seems to me like previously we were getting TNode instance only in dev mode (this is the only place where we need it, right?) but now we do so systematically.

In `elementPropertyInternal`, the `tNode` is [always retrieved](https://github.com/angular/angular/blob/master/packages/core/src/render3/instructions/shared.ts#L949), so there should be no perf difference. In the `elementAttributeInternal` function, the `tNode` is retrieved when [we update the value](https://github.com/angular/angular/blob/master/packages/core/src/render3/instructions/shared.ts#L1453), but for that we always access `tView` (as it's passed as one of the arguments). In this updated code, instead of accessing and passing `tView`, we do access and pass `tNode`, which should presumably be at the same "cost".

2020-03-16 14:08 UTC, pkozlowski-opensource approved these changes
LGTM after @AndrewKushnir additional info - thnx!

2020-03-16 19:27 UTC, AndrewKushnir commented
[Presubmit #2](http://test/OCL:300433799:BASE:301214448:1584386859015:6f79aa4d)

2020-03-16 23:44 UTC, closed without merging