feat(compiler): Add sourceSpan and keySpan to TemplateBinding
angular/angular pull request #35897
Opened 2020-03-06 06:43 UTC by kyliau

This commit adds fine-grained text spans to TemplateBinding for microsyntax expressions.

1. Source span
   By convention, source span refers to the entire span of the binding,
   including its key and value.
2. Key span
   Span of the binding key, without any whitespace or keywords like `let`

The value span is captured by the value expression AST.

This is part of a series of PRs to fix source span mapping in microsyntax expression.
For more info, see the doc https://docs.google.com/document/d/1mEVF2pSSMSnOloqOPQTYNiAJO0XQxA1H0BZyESASOrE/edit?usp=sharing

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-03-06 18:45 UTC, AndrewKushnir commented on packages/language-service/src/completions.ts
> +      const TEMPLATE_ATTR_PREFIX = '*';
@kyliau it looks like this const can be moved to the top level (outside of the class) and also used in the `if` statement above.

2020-03-06 22:09 UTC, kyliau commented on packages/language-service/src/completions.ts
> +      const TEMPLATE_ATTR_PREFIX = '*';
good call, done!

2020-03-07 01:59 UTC, AndrewKushnir requested changes
Thanks for the changes and additional docs @kyliau  👍 

I've added a couple comments, could you please have a look?

Thank you.

2020-03-07 01:59 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +    const {key, keySpan} = this.expectTemplateBindingKey();
It looks like in most cases when we retrieve a `keySpan`, we then convert it to an absolute one (i.e. keySpan.toAbsolute(this.absoluteOffset)). I'm wondering if we can return absolute form from `expectTemplateBindingKey` call instead and just pass it further? WDYT?

2020-03-07 01:59 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +    let spanEnd = this.absoluteOffset + this.inputIndex;
Just an idea: may be we can have a getter function called for ex. `currentAbsoluteOffset` that we can use to get the current offset value?

2020-03-07 19:13 UTC, ayazhafiz requested changes

2020-03-07 19:13 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
>                 false /* parseAction */, this.errors, 0 /* relative offset */)
I think this should make `offset` on the _ParseAST constructor obsolete, no? Could we remove it?

2020-03-07 19:13 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/parser.ts
> +    let spanEnd = this.absoluteOffset + this.inputIndex;
This is a bit difficult to reason about. `absoluteOffset` refers to the offset of the key, passed as a parameter. `this.absoluteOffset` is the offset of the template binding value, which is passed statefully to the parser on construction. In general, I don't think we should assume that `this.absoluteOffset` plays that role, because this parser does more than just parse template bindings. I would recommend renaming the two types of absoluteOffsets used here and passing them as parameters instead.

On the other hand, shouldn't we know the location of the value after `valueExpr` is parsed?

2020-03-07 19:13 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +    if (ast.name.startsWith(TEMPLATE_ATTR_PREFIX)) {
nit: place this constant at the top of the method since this method is the only place its used

2020-03-07 19:13 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +      const absKeyOffset = 0;
shouldn't the key offset be the start of the attribute name?

2020-03-07 19:13 UTC, ayazhafiz commented on packages/language-service/src/locate_symbol.ts
> +              span: offsetSpan(tb.keySpan, -absValueOffset),
Let's add a TODO, I think we should move to only dealing with one type of span

2020-03-09 23:16 UTC, kyliau reviewed
@AndrewKushnir @ayazhafiz Thank you for the valuable feedback!
After analyzing the structure of the code, I realized much of the complexity comes from the decision to use `ASTWithSource` to represent the value of the binding for __both__ variable binding and expression binding. 
`ASTWithSource` is messy to work with because it contains both relative span and absolute span, so we had to keep track of both.
The fundamental problem stems from the usage of __field__ variable `keyIsVar` to differentiate the data types for variable binding and expression binding. The right thing to do here is to use the __type information__ to represent the data, and I've created two separate classes, `VariableBinding` and `ExpressionBinding` to reflect this.
With this change, there is no more confusing relative spans to deal with. All spans handled within the microsyntax expression parsing are absolute spans. The implementation should be much cleaner now. Please take a look and let me know what you think. Thank you!

2020-03-10 03:55 UTC, ayazhafiz requested changes
LGTM, just a comment regarding testing spans

2020-03-10 03:55 UTC, ayazhafiz commented on packages/compiler/src/expression_parser/ast.ts
>  }
nit: consider rename to `TemplateBindingContext`

2020-03-10 03:55 UTC, ayazhafiz commented on packages/compiler/test/expression_parser/parser_spec.ts
> +      }
Can we extend these tests to also check the spans?

2020-03-10 03:55 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +      const absKeyOffset = 0;
Ah, I was under the impression AttrAst contained the info we needed. Thank you for explaining.

2020-03-10 17:40 UTC, kyliau commented on packages/compiler/test/expression_parser/parser_spec.ts
> +      }
done

2020-03-10 18:05 UTC, kyliau commented on packages/compiler/src/expression_parser/ast.ts
>  }
renamed to `TemplateBindingIdentifier`, thanks for pointing this out!

2020-03-10 18:06 UTC, kyliau commented
@ayazhafiz @AndrewKushnir I've addressed all comments, could you please take another look? Thank you!

2020-03-10 18:15 UTC, AndrewKushnir approved these changes
LGTM, thanks @kyliau 👍 

I left a few comments (mostly docs and minor refactoring proposals), please have a look when you get a chance.

Thank you.

2020-03-10 18:15 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/parser.ts
> +    const key = this.expectTemplateBindingKey();
nit: I'm wondering if it make sense to rename `expectTemplateBindingKey` -> `consumeTemplateBindingKey` in a followup PR?

2020-03-10 18:15 UTC, AndrewKushnir commented on packages/language-service/src/completions.ts
> +    if (ast.name.startsWith(TEMPLATE_ATTR_PREFIX)) {
My proposal was based on the assumption that this const can be used in other places as well, which seems like the case, for ex. here: https://github.com/angular/angular/blob/ac8dd2c32b7e4990c606e6a44653cc5c8dea2888/packages/language-service/src/completions.ts#L235
I'm fine keeping it in the function scope as well and refactor later. Up to you Keen :)

2020-03-10 18:15 UTC, AndrewKushnir commented on packages/compiler/src/expression_parser/ast.ts
> +   * @param sourceSpan entire span of the binding.
I think it'd be great to have a quick example of the binding that would be treated as `Variable` vs `Expression`. As an option, we can extend the table that you have above and annotate each line: whether a given expression is a variable or expression binding.

2020-03-10 18:17 UTC, AndrewKushnir commented
@kyliau I think it'd make sense to also run a Global TAP (in addition to Blueprint one) to make sure everything looks good. Thank you.

2020-03-10 18:32 UTC, kyliau commented on packages/compiler/src/expression_parser/ast.ts
> +   * @param sourceSpan entire span of the binding.
done

2020-03-10 18:32 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> +    const key = this.expectTemplateBindingKey();
Good call, I'll do this in a follow up PR

2020-03-10 18:32 UTC, kyliau commented on packages/language-service/src/completions.ts
> +    if (ast.name.startsWith(TEMPLATE_ATTR_PREFIX)) {
ah I didn't see that there's another usage of `*` in this file. I moved it back to the top level.

2020-03-11 04:50 UTC, kyliau commented
Global TAP: https://test.corp.google.com/OCL:300148674:BASE:300248062:1583902188182:84a773d3

2020-03-11 16:18 UTC, ayazhafiz commented on packages/compiler/test/expression_parser/parser_spec.ts
> +            ['*a="1+1"', 'a', '1+1', false, 'a="1+1', 'a', '1+1'],
Is the missing trailing quote in the source span intentional?

2020-03-11 16:19 UTC, ayazhafiz reviewed
Could we add span tests for all test cases? Sorry..

2020-03-11 17:03 UTC, kyliau commented on packages/compiler/test/expression_parser/parser_spec.ts
> +            ['*a="1+1"', 'a', '1+1', false, 'a="1+1', 'a', '1+1'],
Yes, due to the way the string is tokenized, the quotes never appear in the tokens at all.

2020-03-11 17:05 UTC, kyliau commented
> Could we add span tests for all test cases? Sorry..

My intention was to separate the testing for key value and their spans, so that we have tests that are focused. There is a dedicated section for testing spans only from line 482-552.

2020-03-11 17:27 UTC, ayazhafiz commented on packages/compiler/test/expression_parser/parser_spec.ts
> +            ['*a="1+1"', 'a', '1+1', false, 'a="1+1', 'a', '1+1'],
Oh, interesting. Thanks!

2020-03-11 17:39 UTC, ayazhafiz approved these changes

2020-03-11 18:52 UTC, closed without merging