feat(docs-infra): replace analytics.js with gtag.js
angular/angular pull request #35904
Opened 2020-03-06 10:53 UTC by ajitsinghkaler

replaced analytics.js with gtag.js for best practices

#22260

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Analytics.js is used to collect data now integrated gtag.js

Issue Number: #22260

## What is the new behavior?
Added gtag.js to collect data for analytics

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## Other information

2020-03-06 10:55 UTC, ajitsinghkaler commented
will change tests once we can confirm it works reasonably well cannot check it because I don't have analytics credentials.

2020-03-06 13:25 UTC, gkalpak requested changes
Thx for taking this on, @ajitsinghkaler. I am afraid this is not as trivial as it might seem at first sight, so I wonder if it is worth pursuing atm (given that there are higher priority issues).

In any case, in addition to my comments below (and the failing tests), it seems that you haven't followed all the instructions in the [migration guide][1]. If you wish to continue working on this, please go through the guide and make sure to follow all applicable instructions.

[1]: https://developers.google.com/analytics/devguides/collection/gtagjs/migration

2020-03-06 13:25 UTC, gkalpak commented on aio/src/index.html
> -      ~i.name.indexOf('NG_DEFER_BOOTSTRAP') || // only load library if not running e2e tests
We had code to ensure that this has no effect during e2e testing. We need to figure out a way to achive the same for `gtag.js`.

2020-03-06 13:25 UTC, gkalpak commented on aio/src/index.html
> +  <script async src="https://www.googletagmanager.com/gtag/js?id='UA-8594346-26'"></script>
I don't think we can have a hard-coded GA_MEASUREMENT_ID here, because different environments (e.g. production vs development) have different IDs.

2020-06-19 10:21 UTC, petebacondarwin commented
@ajitsinghkaler - would you like to fix up this PR so that we can land it?

2020-06-19 10:37 UTC, ajitsinghkaler commented
@petebacondarwin I wont be working on this

2020-06-19 10:37 UTC, closed without merging