docs: documentation of descendants property of @ContentChildren
angular/angular pull request #35927
Opened 2020-03-07 07:16 UTC by ajitsinghkaler

documentation of decendants property of @ContentChildren was not clear when decendants was set to false it did not pick up direct children when any directive was used on the elements. With Ivy the functionality follows the following pattern only query direct children (in the sense of elements in a template) when descendants: false is specified.

Fixes #20074

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Current documentation of decendants property of @ContentCholdren is confusing

Issue Number: #20074

## What is the new behavior?
Clear out the functionality of descendants property of @ContentChildren

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-03-07 07:16 UTC, ajitsinghkaler commented
@pkozlowski-opensource can you please look into this

2020-03-10 17:12 UTC, ajitsinghkaler commented
@pkozlowski-opensource can you please have a look

2020-03-25 07:56 UTC, ajitsinghkaler commented
@pkozlowski-opensource can you please have a look

2020-04-03 05:32 UTC, ajitsinghkaler commented
@pkozlowski-opensource can you please check this

2020-04-06 16:14 UTC, ajitsinghkaler commented
@kapunahelewong can you have alook at this too

2020-04-17 16:54 UTC, ajitsinghkaler commented
@pkozlowski-opensource can you please check this

2020-04-21 01:34 UTC, ajitsinghkaler commented
@kapunahelewong @aikidave can you please have a look from writing standpoint

2020-04-30 16:47 UTC, ajitsinghkaler commented
@pkozlowski-opensource can you please review this.

2020-05-07 15:39 UTC, kapunahelewong requested changes
Thanks for this, @ajitsinghkaler ! Since documentation review should come after engineering review engineering review, please defer to the engineering feedback.  If engineering review requires significant changes, a docs team member can review again.

2020-05-07 15:39 UTC, kapunahelewong commented on packages/core/src/metadata/di.ts
> +   * * **descendants** - Set true to include all descendants of the element, if it's value
```suggestion
   * * **descendants** - Set to true to include all descendants of the element. 
   If the value
```

2020-05-07 15:39 UTC, kapunahelewong commented on packages/core/src/metadata/di.ts
> +   * is set to false then it will only query direct children of the element.
```suggestion
   * is false, then it only queries direct children of the element.
```

2020-05-11 01:12 UTC, ajitsinghkaler commented
@pkozlowski-opensource can you please take a look

2020-05-11 18:03 UTC, kapunahelewong approved these changes
Beautiful! Thank you, @ajitsinghkaler! 

Reviewed-for: global-docs-approvers

2020-05-12 01:13 UTC, ajitsinghkaler commented
@pkozlowski-opensource can you please check this

2020-06-06 04:02 UTC, ajitsinghkaler commented
@kapunahelewong @aikidave @pkozlowski-opensource I think its done can we get this merged or @kapunahelewong can you please put that tag needs eng review

2020-06-14 08:55 UTC, ajitsinghkaler commented
@pkozlowski-opensource can you please review this

2020-06-15 16:21 UTC, ajitsinghkaler commented
@kapunahelewong @aikidave  can you please put the review label so that it is clear that this is ready for review

2020-06-16 14:35 UTC, pkozlowski-opensource requested changes
I don't think that this PR adds sufficient level of details and imo is missing examples of what we mean. 

To start with we need to define "descendants of the element" - do we mean "as written in the template"? as appearing in the DOM? something else? We need a solid explanation and examples here.

Then, we absolutely need describe behaviour for special tags like `<ng-template>`, `<ng-container>` and `<ng-content>` with good examples.

Finally we need to have good discussion of:
* content vs. view queries
* default values of the `descendants` for various queries (there are 4 cases: content/view X child/children)

I would expect to have much, much longer article here with several examples as this topic is not well documented today.

2020-06-16 17:13 UTC, ajitsinghkaler commented
> To start with we need to define "descendants of the element" - do we mean "as written in the template"? as appearing in the DOM? something else? We need a solid explanation and examples here.

Will think more on this

> Then, we absolutely need describe behaviour for special tags like `<ng-template>`, `<ng-container>` and `<ng-content>` with good examples.

I'm working on ng-content docs in PR #37268

ng-container and ng-template already have  good docs 

- https://angular.io/guide/structural-directives#the-ng-template
- https://angular.io/guide/structural-directives#group-sibling-elements-with-ng-container

> Finally we need to have good discussion of:
> * content vs. view queries
> * default values of the `descendants` for various queries (there are 4 cases: content/view X child/children)

I think we should create a separate issue and guide for this. It is outside the scope of this PR. As it seems a large effort.

Your thoughts @pkozlowski-opensource 

Should we do the last part also on this PR or on a separate PR because these are API docs where I made the change and what you are asking seems the work that should be done in an entirely new guide

2020-12-16 19:07 UTC, aikidave approved these changes
I agree. We can move forward with this change and address other issues in a separate PR.

Reviewed-for: global-docs-approvers

2021-02-16 06:08 UTC, AndrewKushnir commented
@ajitsinghkaler it looks like this PR conflicts with the main branch. Could you please rebase and resolve conflicts? Thank you.

2021-04-19 22:57 UTC, closed without merging