fix(docs-infra): fix resources page tabs text which is not visible on…
angular/angular pull request #35935
Opened 2020-03-08 11:13 UTC by ajitsinghkaler

… small screens

on small mobile screens the top tab bar contains text which was not visible on small screens changed text size, margin and padding so that the text could be contained in these screens (320px to 480px)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

On small screents tab text on resources page was not visible
![Angular - EXPLORE ANGULAR RESOURCES (1)](https://user-images.githubusercontent.com/39260684/76161716-ee878b00-615b-11ea-966d-be243e2825cd.png)

Issue Number: N/A

## What is the new behavior?
On small screents tab text on resources page is not visible
![Angular - EXPLORE ANGULAR RESOURCES](https://user-images.githubusercontent.com/39260684/76161713-e891aa00-615b-11ea-832f-465e27db0789.png)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-03-10 16:57 UTC, ajitsinghkaler commented
@petebacondarwin can you please review this

2020-03-11 13:51 UTC, mary-poppins commented
You can preview 14c21b3 at https://pr35935-14c21b3.ngbuilds.io/.
You can preview 58b3094 at https://pr35935-58b3094.ngbuilds.io/.

2020-03-11 13:59 UTC, petebacondarwin approved these changes

2020-03-11 14:27 UTC, gkalpak requested changes

2020-03-11 14:27 UTC, gkalpak commented on aio/src/styles/2-modules/_resources.scss
> +      .button, a.button.mat-button{
```suggestion
      .button, a.button.mat-button {
```

:grin:

2020-03-11 14:27 UTC, gkalpak commented on aio/src/styles/2-modules/_resources.scss
> +        padding:0;
```suggestion
        font-size: 1.2rem;
        padding: 0;
```

2020-03-11 14:27 UTC, gkalpak commented on aio/src/styles/2-modules/_resources.scss
> +      a.filter-button{
```suggestion
      a.filter-button {
```

2020-03-11 14:27 UTC, gkalpak commented on aio/src/styles/2-modules/_resources.scss
> +      a.filter-button{
@ajitsinghkaler, can you please explain why the different selectors (`.button`, `a.button.mat-button`, `a.filter-button`)?
AFAICT, they are all targeting the same elements (so one of them or a combination of them should be enough).

2020-03-25 10:55 UTC, ajitsinghkaler commented on aio/src/styles/2-modules/_resources.scss
> +      a.filter-button{
I just copied it from above if you want I can do cleanup

2020-03-25 10:59 UTC, ajitsinghkaler commented
@petebacondarwin request for review was sent to you by mistake you need not check this.

2020-03-25 10:59 UTC, ajitsinghkaler commented
@gkalpak can you please have a look

2020-03-25 13:52 UTC, gkalpak requested changes
Also, the type of the second commit should be `style` (so `style(docs-infra): ...`).

2020-03-25 13:52 UTC, gkalpak commented on aio/src/styles/2-modules/_resources.scss
> +  .group-buttons{
```suggestion

  .group-buttons {
```

2020-03-25 13:52 UTC, gkalpak commented on aio/src/styles/2-modules/_resources.scss
> +      a.filter-button{
Where did you copy it from? 😕

2020-04-06 02:42 UTC, ajitsinghkaler commented
@gkalpak made the changes please have a look

2020-04-06 02:48 UTC, ajitsinghkaler commented on aio/src/styles/2-modules/_resources.scss
> +      a.filter-button{
Sorry I made a mistake didn't copy it from anywhere.

2020-04-06 02:52 UTC, mary-poppins commented
You can preview 89f92ed at https://pr35935-89f92ed.ngbuilds.io/.

2020-04-06 03:02 UTC, mary-poppins commented
You can preview f89680b at https://pr35935-f89680b.ngbuilds.io/.

2020-04-07 16:12 UTC, gkalpak requested changes

2020-04-07 16:12 UTC, gkalpak commented on aio/src/styles/2-modules/_resources.scss
> +  .group-buttons {
Please leave an empty line between own styles and child-element styles:

```suggestion

  .group-buttons {
```

2020-04-07 16:12 UTC, gkalpak commented on aio/src/styles/2-modules/_resources.scss
> +      a.filter-button {
Why do we have two different selectors (`.button` and `a.filter-button`)?
Aren't they targeting the same elements?

2020-04-07 17:45 UTC, mary-poppins commented
You can preview 08c3e78 at https://pr35935-08c3e78.ngbuilds.io/.

2020-04-07 17:58 UTC, ajitsinghkaler commented
@gkalpak made the changes please have a look

2020-04-07 19:04 UTC, gkalpak approved these changes
Awesome ✨ Thx, @ajitsinghkaler!

2020-04-07 22:09 UTC, closed without merging