ci: exclude ngcc directory from fw-compiler pull-approve rule
angular/angular pull request #35933
Opened 2020-03-07 16:23 UTC by petebacondarwin

ngcc has its own pull-approve group

2020-03-09 16:09 UTC, IgorMinar approved these changes
lgtm if we can get the confirmation on how the argument to `exclude` behaves.

2020-03-09 16:09 UTC, IgorMinar commented on .pullapprove.yml
> +      - "files.exclude('ngcc')"
is it just `'ngcc'` or `'*ngcc*'`?

the docs are not clear: https://docs.pullapprove.com/config/conditions/ 

// @josephperrott

2020-03-09 17:30 UTC, josephperrott commented on .pullapprove.yml
> +      - "files.exclude('ngcc')"
I can't explain why exactly, but the current change doesn't work as expected.

When I tested it, the most readable option I found is
```yaml
fw-compiler:
  conditions:
    - >
      contains_any_globs(files, [
        'packages/compiler/**',
        'packages/examples/compiler/**',
        'packages/compiler-cli/**',
        'aio/content/guide/angular-compiler-options.md',
        'aio/content/guide/aot-compiler.md',
        'aio/content/guide/aot-metadata-errors.md',
        'aio/content/guide/template-typecheck.md '
        ])
    - >
      not contains_any_globs(files, [
        'packages/compiler-cli/ngcc/**'
        ])
```

This also will be _relatively_ easy to manage in our verification script, rather than having an entirely new method of matching to mimic.

2020-04-06 07:43 UTC, petebacondarwin commented
@josephperrott - is this now unblocked?

2020-04-06 14:06 UTC, josephperrott commented
Sorry, yes this is unblocked.

2020-04-06 18:53 UTC, josephperrott requested changes

2020-04-06 18:53 UTC, josephperrott commented on .pullapprove.yml
> +      - "files.exclude('ngcc')"
Now that we are probably handling this in our pullapprove verification tooling, it will verify it is as expected.  However we should move to using the `contains_any_globs` for our exclude lists as well.

Can we change 
```
    - "files.exclude('ngcc')"
```

to 

```
    - >
      not contains_any_globs(files, [
        'packages/compiler-cli/ngcc/**'
        ])
```

2020-04-06 19:31 UTC, josephperrott approved these changes
LGTM

2020-04-06 20:16 UTC, closed without merging