fix(docs-infra): remove `routerLink` from `top-bar`
angular/angular pull request #35951
Opened 2020-03-09 09:36 UTC by sonukapoor

Closes #35947

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #35947

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-03-09 15:34 UTC, gkalpak requested changes

2020-03-09 15:34 UTC, gkalpak commented on aio/content/examples/getting-started-v0/src/app/top-bar/top-bar.component.html
> +<a class="button fancy-button"><i class="material-icons">shopping_cart</i>Checkout</a>
If you remove it here, then you need to explain how to add it in the [start-data][1] step later in the tutorial.

[1]: https://angular.io/start/start-data

2020-03-09 15:43 UTC, sonukapoor commented on aio/content/examples/getting-started-v0/src/app/top-bar/top-bar.component.html
> +<a class="button fancy-button"><i class="material-icons">shopping_cart</i>Checkout</a>
It is explained here:

https://angular.io/start/start-data#create-the-cart-page

2020-03-09 15:44 UTC, petebacondarwin commented on aio/content/examples/getting-started-v0/src/app/top-bar/top-bar.component.html
> +<a class="button fancy-button"><i class="material-icons">shopping_cart</i>Checkout</a>
<img width="890" alt="Screenshot 2020-03-09 at 15 44 20" src="https://user-images.githubusercontent.com/15655/76231279-e80d1800-621c-11ea-94fd-7783e60047cf.png">

2020-03-09 15:48 UTC, sonukapoor commented on aio/content/examples/getting-started-v0/src/app/top-bar/top-bar.component.html
> +<a class="button fancy-button"><i class="material-icons">shopping_cart</i>Checkout</a>
Oops. Thanks. Will change it.

2020-03-10 08:27 UTC, mary-poppins commented
You can preview 21a78f7 at https://pr35951-21a78f7.ngbuilds.io/.
You can preview fa3b422 at https://pr35951-fa3b422.ngbuilds.io/.

2020-03-10 08:30 UTC, petebacondarwin approved these changes

2020-03-10 18:16 UTC, gkalpak requested changes

2020-03-10 18:16 UTC, gkalpak commented on aio/content/examples/getting-started/src/app/top-bar/top-bar.component.html
>  <a [routerLink]="['/cart']" class="button fancy-button">
To keep things simple, should we change this to just `routerLink="/cart"`?

2020-03-10 18:16 UTC, gkalpak commented on aio/content/start/start-data.md
> +    Open `top-bar.component.html` and add the `routerLink` directive with a value of `/cart`.
Well...it doesn't exactly have a value of `/cart` (but we could change that) :grin:

2020-03-10 18:16 UTC, gkalpak commented on aio/content/start/start-data.md
> -    </div>
This image should not be removed.

2020-03-10 18:20 UTC, sonukapoor commented on aio/content/examples/getting-started/src/app/top-bar/top-bar.component.html
>  <a [routerLink]="['/cart']" class="button fancy-button">
Yes. Makes sense.

2020-03-10 18:21 UTC, sonukapoor commented on aio/content/start/start-data.md
> +    Open `top-bar.component.html` and add the `routerLink` directive with a value of `/cart`.
As you can guess I struggled to find the right word :D

2020-03-11 01:48 UTC, mary-poppins commented
You can preview 398ba89 at https://pr35951-398ba89.ngbuilds.io/.

2020-03-13 11:24 UTC, gkalpak requested changes

2020-03-13 11:24 UTC, gkalpak commented on aio/content/start/start-data.md
> -    <div class="alert is-helpful">
This should not be removed.

2020-03-13 11:24 UTC, gkalpak commented on aio/content/start/start-data.md
>      <div class="lightbox">
This is not the correct place for the image. It should be below the "To see the new cart component" item.

2020-03-13 11:24 UTC, gkalpak commented on aio/content/start/start-data.md
> +    </code-example>
Personal preferrence (for better readability):

```suggestion
    <code-example
        header="src/app/top-bar/top-bar.component.html"
        path="getting-started/src/app/top-bar/top-bar.component.html"
        region="cart-route">
    </code-example>
```

2020-03-13 11:26 UTC, gkalpak commented on aio/content/start/start-data.md
> +    Open `top-bar.component.html` and add `routerLink` with a value to `/cart`.
```suggestion
    Open `top-bar.component.html` and add a `routerLink` directive with a value of `/cart`.
```

or

```suggestion
    Open `top-bar.component.html` and add a `routerLink` directive pointing to `/cart`.
```

2020-03-13 11:58 UTC, mary-poppins commented
You can preview 1adc3a6 at https://pr35951-1adc3a6.ngbuilds.io/.

2020-03-13 12:25 UTC, sonukapoor commented
@gkalpak CI is failing with strange errors again.

2020-03-13 12:43 UTC, gkalpak commented
Looks like a flake. Please address all my comments 🙏

2020-03-13 12:44 UTC, sonukapoor commented
> Looks like a flake. Please address all my comments 🙏

I thought I did. Which one did I miss?

2020-03-13 12:45 UTC, gkalpak commented
The one that shows up as unresolved :grin:
https://github.com/angular/angular/pull/35951#discussion_r392170315

2020-03-13 12:49 UTC, sonukapoor commented on aio/content/start/start-data.md
> -    <div class="alert is-helpful">
It's there: https://github.com/angular/angular/pull/35951/commits/1adc3a6582a193e2d8defada2bd0f702ec3967a1#diff-a0473f62fb0aa9289968df2f4d4403b5R154

2020-03-13 13:26 UTC, gkalpak commented on aio/content/start/start-data.md
> -    <div class="alert is-helpful">
I don't see it 😕

2020-03-13 13:33 UTC, sonukapoor commented on aio/content/start/start-data.md
> -    <div class="alert is-helpful">
Are we talking about the paragraph 'To see the new cart component...' or the div `<div class="alert is-helpful">`?

2020-03-13 13:46 UTC, gkalpak commented on aio/content/start/start-data.md
> -    <div class="alert is-helpful">
The `<div class="alert is-helpful">`. That is what I commented on originally.

2020-03-13 13:59 UTC, sonukapoor commented on aio/content/start/start-data.md
> -    <div class="alert is-helpful">
Hm. Where would we add this? The content for that div is not needed anymore, because it doesn't apply. Below is the original markup:

```
1. To see the new cart component, click the "Checkout" button. You can see the "cart works!" default text, and the URL has the pattern `https://getting-started.stackblitz.io/cart`,  where `getting-started.stackblitz.io` may be different for your StackBlitz project.

    <div class="alert is-helpful">

    The starter code for the "Checkout" button already includes a `routerLink` for `/cart` the top-bar component.

    </div>

    <div class="lightbox">
      <img src='generated/images/guide/start/cart-works.png' alt="Display cart page before customizing">
    </div>
```

2020-03-13 15:03 UTC, gkalpak commented on aio/content/start/start-data.md
> -    <div class="alert is-helpful">
Ooops, my bad 😇
The diff tricked me. All is well, then 🚶

2020-03-13 15:05 UTC, gkalpak approved these changes
LGTM 👍
Thx, @sonukapoor!

2020-03-13 15:25 UTC, closed without merging