fix(core): Refresh transplanted views at insertion point only
angular/angular pull request #35968
Opened 2020-03-09 18:31 UTC by atscott

Only refresh transplanted views at the insertion location in Ivy.
This change fixes several issues:

  * Transplanted views refreshed twice if both insertion and declaration
  are dirty. This could be an error if the insertion component changes
  result in data not being available to the transplanted view because it
  is slated to be removed.
  * CheckAlways transplanted views not refreshed if shielded by
  non-dirty OnPush (fixes #35400)
  * Transplanted views still refreshed when insertion tree is detached
  (fixes #21324)

2020-03-10 19:58 UTC, atscott commented
[presubmit](https://test.corp.google.com/ui#id=OCL:299893004:BASE:299982658:1583802628892:30ceb020) - failures seem to be pre-existing by comparing to [recent clean run](https://test.corp.google.com/ui#id=OCL:249542820:BASE:299986597:1583804112015:53310222)

2020-03-11 22:06 UTC, mhevery requested changes

2020-03-11 22:06 UTC, mhevery commented on packages/core/test/acceptance/change_detection_spec.ts
> +          // `Insert` or from `Declare` component.
```suggestion
          // from `Insert` or from `Declare` component.
```

2020-03-11 22:06 UTC, mhevery commented on packages/core/test/acceptance/change_detection_spec.ts
> +    describe('when declaration appears before insertion', () => {
What do you think about moving all of the transplanted views to `change_detection_transplanted_view_spec.ts` file.

2020-04-16 01:03 UTC, kara requested changes
Great work! Thanks for putting this all together.

Comments below are mostly about missing tests with some nits about comments. Implementation looks good.

Have we done a sanity run of microbenchmarks to make sure everything looks right?

2020-04-16 19:39 UTC, atscott commented on packages/core/src/render3/util/view_utils.ts
> +export function isViewAttached(view: LView): boolean {
reverting. It was a request from Misko that belongs in a different PR.

2020-04-16 19:54 UTC, atscott commented on packages/core/src/render3/instructions/shared.ts
> +            updateTransplantedViewCount(insertionLContainer, 1);
One of the options was to track them separately but would have been a breaking change so we decided to do it this way as a non-breaking fix, which is in line with what VE did. Tracking `CheckAlways` in that way (count when the transplanted view gets inserted, and always find and refresh it during CD) would result in new `ExpressionChanged` errors:

           [A]
        /       \
      [B]       [C]


- [B] is the declaration and `CheckAlways`, [C] is insertion, and [A] is `OnPush`

Because CD is broken for `OnPush` components (https://github.com/angular/angular/pull/34443), `checkNoChanges` pass does not check any children of root A. So [B] can update a binding in the template in `ngAfterViewInit` without the error being thrown. If we used the separate tracking for `CheckAlways` transplanted views, we would still check [C] because we have the ability to *always* know about `CheckAlways` children and `ExpressionChanged` error would throw.

2020-04-16 19:56 UTC, atscott commented on packages/core/test/acceptance/change_detection_transplanted_view_spec.ts
> +        // mark declaration point dirty
Added a separate test to make this assertion

2020-04-16 20:28 UTC, atscott commented on packages/core/src/render3/instructions/shared.ts
>  import {RComment, RElement, RNode, RText, Renderer3, RendererFactory3, isProceduralRenderer} from '../interfaces/renderer';
Updated commit message. Let me know if you think it could use even more detail.

2020-04-16 20:44 UTC, kara commented on packages/core/src/render3/instructions/shared.ts
> +            updateTransplantedViewCount(insertionLContainer, 1);
I see, I see. Is there a Jira for the follow-up work that's breaking?

2020-04-16 20:56 UTC, atscott commented on packages/core/test/acceptance/change_detection_transplanted_view_spec.ts
> +        expect(log).toEqual(['Insert']);
Fair point -- I moved the assertions to a test `'should set up the component under test correctly'`.  The `detectChanges` and `log.length = 0` lines are there to ensure that the tests start off in a "clean" state such that the correct views are showing, the initial values are displayed, and the counters are at 0.

As things are now, adding `fixture.detectChanges(false); log.length = 0;` in the `beforeEach` rather than having them at the top of each test isn't just about deduplication, but even more about keeping the code in the `'it'` block relevant to the individual test and not making the same setup calls/assertions in each one.

If we still disagree about the current state of the `beforeEach` in these tests, maybe it would be best to jump on a call to discuss it?

2020-04-16 21:03 UTC, kara commented on packages/core/test/acceptance/change_detection_transplanted_view_spec.ts
> +        expect(log).toEqual(['Insert']);
Eh, I don't feel so strongly about it that we need to jump on a call :). I do feel like the `detectChanges` call is necessary context to understand each test because these are specifically change detection tests (in other specs, it doesn't matter as much). If you're debugging a particular test failure, it's hard to know that the context you need is 100 lines up in the `beforeEach`. But I'll let you make the call -it's a nit.

2020-04-16 21:25 UTC, atscott commented on packages/core/src/render3/instructions/shared.ts
> +            updateTransplantedViewCount(insertionLContainer, 1);
No, but I will file one now.

2020-04-17 17:26 UTC, atscott commented on packages/core/src/render3/instructions/shared.ts
> +          // refresh.
This check was already here so I had to do some testing to figure it out. The situation where `insertedComponentLView === declaredComponentLView` would be
```
      <ng-template #template></ng-template>
      <ng-container [ngTemplateOutlet]="template"></ng-container>
```
The cases when this check would get executed would be if a view had a template that is inserted in other component views *and* inserted into itself, i.e.
```
      <ng-template #template><div>A</div></ng-template>
      <insertion [template]="template"></insertion>
      <ng-container [ngTemplateOutlet]="template"></ng-container>
```
This is because we only get to this bit of code if `lContainer[ACTIVE_INDEX] & ActiveIndexFlag.HAS_TRANSPLANTED_VIEWS` (so it would have both moved views that are transplanted views *and* moved views that aren't transplanted).
I don't think there's any test I can write that would make it fail. The only "incorrect" thing that could happen would be that we mark a moved view with the `RefreshTransplantedView` when it's not actually transplanted (because it's inserted in the same component that it was declared in). The moved view would still be refreshed as part of the regular CD process (`refreshDynamicEmbeddedViews`) and the flag would be cleared. So all way do is have an extra and potentially misleading tracking for "RefreshTransplantedView". But maybe the savings for not having to do the check outweigh this edge case. WDYT?

2020-04-17 17:26 UTC, atscott commented on packages/core/src/render3/instructions/shared.ts
> +          // refresh.
// cc @mhevery

2020-04-17 19:27 UTC, atscott commented on packages/core/src/render3/instructions/shared.ts
> +          // refresh.
@kara  - I chatted with Misko about this and we came to the same conclusion that the check isn't necessary. I removed it, along with the variable reads for those values. Do you think it's worth mentioning in a comment that it's *possible* the `movedViews` contains some that are not transplanted, but that's fine because xyz? The comment might end up being more confusing than just omitting it completely...

2020-04-20 19:31 UTC, atscott commented on packages/core/src/render3/instructions/shared.ts
>  import {RComment, RElement, RNode, RText, Renderer3, RendererFactory3, isProceduralRenderer} from '../interfaces/renderer';
As for the performance, I added a section in the design doc that talks about the analysis I've done: https://docs.google.com/document/d/1P-1MpiGPOvxidVEtiAk_S7TetotSVxWoGKGtbZgDToQ/edit#heading=h.s04duzxp3e9u

2020-04-21 17:10 UTC, atscott commented on packages/core/test/acceptance/change_detection_transplanted_view_spec.ts
> +}
First two bullets, done. Third bullet - is that covered in the first `InsertComp` template or were you thinking of something different?
```
        <div *ngIf="true">
          <!-- Add extra level of embedded view to ensure we can handle nesting -->
          <ng-container
              [ngTemplateOutlet]="template"
              [ngTemplateOutletContext]="{$implicit: greeting}">
          </ng-container>
        </div>
```

2020-04-27 22:44 UTC, kara approved these changes
LGTM

2020-04-27 22:44 UTC, kara commented on packages/core/test/acceptance/change_detection_transplanted_view_spec.ts
> +      it('should CD with insertion only', () => {
```suggestion
      it('should CD at insertion point only', () => {
```

2020-04-28 19:48 UTC, mhevery approved these changes

2020-04-29 00:19 UTC, AndrewKushnir commented
FYI, will run global presubmit tonight and update this thread with the results.

2020-04-29 17:46 UTC, AndrewKushnir commented
FYI, global presubmit went well.

@atscott could you please rebase this PR and resolve conflicts?

2020-04-29 21:31 UTC, closed without merging