fix(service-worker): allow service worker to handle non root base hrefs
angular/angular pull request #35979
Opened 2020-03-10 01:44 UTC by sonukapoor

This PR is based on the work from @mattlewis92. For now, I just have rebased and fixed the conflicts. I have not addressed any comments from the previous PR yet. 

See https://github.com/angular/angular/pull/31082 for more details on his PR.

Closes #25055
Closes #30505

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-03-10 09:00 UTC, mattlewis92 commented
Awesome, thanks for taking this over @sonukapoor 🙌

2020-06-14 18:35 UTC, gkalpak requested changes
Thx for taking this over, @sonukapoor!
I did a preliminary review and left some comments. Can you also split this up into two commits (as described in https://github.com/angular/angular/pull/31082#pullrequestreview-256034185).

2020-06-14 18:35 UTC, gkalpak commented on packages/service-worker/worker/test/happy_spec.ts
> +}
🙅

2020-07-04 10:17 UTC, gkalpak commented
Thx, @sonukapoor, for moving this further along. As discussed "offline", I am taking this over.

This is now superceded by #37922.

2020-07-04 10:17 UTC, closed without merging