fix(core): fix memory leak caused by chrome dev tool.
angular/angular pull request #36011
Opened 2020-03-11 11:04 UTC by JiaLiPassion

Close #35575

In ivy, Angular attaches lView data to the DOM node, and when the DOM node is removed ,
the DOM node and the attached lView data should be garbage collected. But in Chrome,
if the chrome dev tools is opened, the last clicked dom element will be kept in the memory,
and because the DOM node holds the instance of the lView data, and the lView data holds the
component data, so a lot of data is kept in the memory which will cause memory leak and also
make memory analyze with memory snapshot difficult.

So this PR will clear the attached lView data(__ngContext__) from the DOM node when the DOM
node is detached.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

@mhevery , please review, thank you.

2020-03-11 20:12 UTC, mhevery requested changes
I am hesitant to work around Chrome DevTools issue like this because it will have a negative perf impact. 
- [ ] At the very least we should have a perf tests which shows the impact.  
- [ ] If we chose to do this we would need tests which asserts that we are removing the path data.
- [ ] Also have concern in that just because a context is disconnected, it may be reconnected later in which case the `LView`s should be retained. So we would need a test to verify that once the removed DOM is re-inserted the `LView`s are restored.

2020-03-11 20:12 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +      detachPatchData(rNode);
This is a megamorphic write which will happen on each destruction slowing it down. Not sure how I feel about it. @kara  and @pkozlowski-opensource what do you think?

2020-03-11 20:49 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +      detachPatchData(rNode);
Tend to agree with @mhevery - this is likely to slow down destroy / detach scenarios. So, as the very minimum we should run benchmarks here (existing largetable / tree would be a good start. BUT, more importantly, if we are _sure_ that this is chrome dev tools issue we should rather follow up with this team and not work-around it in Angular.

2020-03-12 14:15 UTC, JiaLiPassion commented on packages/core/src/render3/node_manipulation.ts
> +      detachPatchData(rNode);
@pkozlowski-opensource , thanks and it seems Chrome will not fix this one, 
https://bugs.chromium.org/p/v8/issues/detail?id=10297#c5

2020-03-12 23:16 UTC, mhevery commented on packages/core/src/render3/node_manipulation.ts
> +      detachPatchData(rNode);
Given that this happens with Chrome DevTools open and is transient, do we even need to fix it? End users will not notice anything.

2020-03-13 08:54 UTC, alfaproject commented on packages/core/src/render3/node_manipulation.ts
> +      detachPatchData(rNode);
It sucks if you are debugging memory leaks. Maybe can work-around under `ngDevMode`?

2020-06-30 09:47 UTC, JohnnyDevNull commented on packages/core/src/render3/node_manipulation.ts
> +      detachPatchData(rNode);
This pretty sucks when debugging... it's now the fourth time i've dived into debugging memory leaks because of collages reported to me as main Angular Developere there would be Memory Leaks and i'am not able to argue to my team lead why this happens and the phrase "It's just because it's dev mode" is never a accaptable answer to Senior Lead Devs!

I would also suggest to workaround with ngDevMode and do there some additional cleanup when Chrom won't fix it. This would save a lot of debugging time over and over again running in the same result as described above.

2020-12-03 18:20 UTC, arturovt commented on packages/core/src/render3/node_manipulation.ts
> +      detachPatchData(rNode);
@mhevery @JiaLiPassion @pkozlowski-opensource hey guys. It's been 10 months since this pull request was opened. Basically, it's _mostly_ impossible to debug memory leaks in Chrome, other browsers, like Firefox or Safari, don't provide such rich functionality.

Can we give this issue a higher priority? At least as @JohnnyDevNull proposed to invoke this function only in development mode.

2020-12-03 19:39 UTC, mhevery commented
I agree that the current situation sucks. The issue is that chrome dev tools retains the last clicked item and with it the whole angular internal `LView`. The issue is that we can't really do much about it even if we would hide it behind `ngDevMode`. Imagine if a click removes a view, in such a situation we could clear the patched data, but 
1. it would be slow, 
2. we could do the slow part behind `ngDevMode` but
3. It would break the application. Imagine if a view is removed (we clear the patch data) and then the view is re-added. We would have to now somehow restore the data wu cleared, but there is no easy way to get that data back.

So this PR is really not a feasible solution. I hear the community that this is problematic, but it is feature of chrome dev tools, and I really can't think of a way to work around this feature.

2020-12-03 19:39 UTC, closed without merging