fix(ngcc): bad package resilience
angular/angular pull request #36083
Opened 2020-03-16 11:34 UTC by petebacondarwin

2020-03-16 21:53 UTC, petebacondarwin commented
I need to run a check against the CLI branch on ngcc-validation too.

2020-03-17 14:34 UTC, gkalpak requested changes
I generally like this (with minor comments/suggestions) :+1:
Also, great job spliting it up into cleanly separated commits 💯 

Just a couple of thoughts/concerns:

1. I think I would prefer to have a consistent default value for `errorOnFailedEntryPoint` (false), regardless of how ngcc is called. I feel like it complicates things for little benefit otherwise. Especially given that changing the default based on programmatic call or not is orthogonal to the knowledge one has for the entry-points. 
  If anything, it might make sense to change the default value depending on whether the `target` option is set, but that would complicate things even more. (Even so, I would probably prefer this over the current behavior.)
  I can be definitely convinced otherwise, though. What are your thoughts?

2. Previously, ngcc operated under the assumption that the found format properties would either be successfully compiled or the operation would halt altogether. This gave us the freedom to arbitrarily associate DTS processing with the first found format property. Now, this assumption is no longer true: It is theoretically possible that processing of `es2015` for entry-point `foo/bar` (which has `processDts: true`) fails, but processing `module` for the same entry-point (with `processDts: false`) succeeds.
  Should we rethink how we associate DTS processing with specific entry-point formats? (Note that this might complicate things significantly for parallel mode.)
  Given the above and the fact that there is avery low probability for it to cause problems, I tend to believe it is better to keep operating under the current assumptions. We could also cancel/skip processing of all formats of an entry-point as soon as the task with `processDts: true` for that entry-point fails, but the extra compication is probably not worth it.

2020-03-17 14:34 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/main.ts
> +   * failure. In this case it will clean the whole package that errored and resume processing other
> it will clean the whole package that errored

Did you intend to include that, because in practice there is nothing to clean up (as discussed offline) and this statement might confuse users (e.g. what happens to previously successfully compiled entry-points of the package)?

2020-03-17 14:34 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/main.ts
> +        onTaskCompleted(task, TaskProcessingOutcome.Failed, `compilation errors:\n${errors}`);
Aha, I see you added a `return` in a subsequent commit.

2020-03-17 15:51 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/utils.ts
> +    callbacks: Partial<Record<TaskProcessingOutcome, TaskCompletedCallback>>):
Yes, otherwise it complains.

2020-03-17 15:52 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/utils.ts
> +    TaskCompletedCallback {
Why? The task is completed but the outcome is either success or failure.

2020-03-17 15:53 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/execution/single_processor_executor_spec.ts
> +      allTasksCompleted: tasksCount === 0,
Oops!

2020-03-17 15:55 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/task_selection/base_task_queue.ts
> +  protected abstract getNextTaskWorker(): Task|null;
What do you prefer? It is indicating that this is the method that actually does the work, rather than the front-line API.

2020-03-17 15:55 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/main.ts
> +   * failure. In this case it will clean the whole package that errored and resume processing other
Nope! That is a leftover from a previous incarnation. Thanks!

2020-03-17 19:13 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/utils.ts
> +    TaskCompletedCallback {
This is just a handler for when a task has completed. Just because it happens to be used, at the moment, only when the task completes successfully is not the responsibility of this.

2020-03-17 19:51 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/task_selection/parallel_task_queue.ts
> +    super(sortTasksByPriority(tasks, dependencies), dependents);
Yes! As long as we agree to ensure that `dependencies` and `dependents` are symmetric.

2020-03-17 19:59 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/task_selection/base_task_queue.ts
> +  protected abstract getNextTaskWorker(): Task|null;
Personally, I use either a `do` prefix or an `Impl` suffix (but I don't feel strongly enough to recommend these :grin:). I find `Worker` confusing, because of the cluster executor's master/worker processes (my first thought was that this is related to the worker processes or something). So, anything that wouldn't refer to cluster/master/worker works for me :smiley:

2020-03-17 19:59 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/task_selection/parallel_task_queue.ts
> +    this.blockedTasks = dependencies;
Good spot. Will look into it.

2020-03-17 20:00 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/task_selection/base_task_queue.ts
> +  protected abstract getNextTaskWorker(): Task|null;
`getNextTaskInternal()`?

2020-03-17 20:01 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/task_selection/base_task_queue.ts
> +  protected abstract getNextTaskWorker(): Task|null;
`computeNextTask()`?

2020-03-17 20:15 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/utils.ts
> +    TaskCompletedCallback {
To me, it looks like a handler that is specifically called on completed tasks. Personally, I was slightly thrown off by the fact that it is typed as `TaskCompletedCallback`. It would have helped me to understand the code faster if the type helperd me realize this is not suppoed to handle failed cases.

Not feeling too strongly about it, though. Up to you.

2020-03-17 20:16 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/task_selection/base_task_queue.ts
> +  protected abstract getNextTaskWorker(): Task|null;
Both work for me :+1:

2020-03-17 21:33 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/utils.ts
> +    callbacks: Partial<Record<TaskProcessingOutcome, TaskCompletedCallback>>):
Actually it appears that now I can remove it...

2020-03-17 21:43 UTC, JoostK approved these changes
Excellent work!

I do agree with @gkalpak on the choice of the default value of the option, I'd prefer it to be always the same independent of the usage, or indeed be derived from `targetedEntryPoint`.

2020-03-17 21:43 UTC, JoostK commented on packages/compiler-cli/ngcc/src/execution/task_selection/base_task_queue.ts
> +  protected abstract getNextTaskWorker(): Task|null;
I tend to go with `acquire` for these sorts of things :-)

`acquireNextTask`

2020-03-17 21:43 UTC, JoostK commented on packages/compiler-cli/ngcc/src/execution/utils.ts
> + * Creates a task completed callback that calls one of those in a hash of callback based on the
I needed the code as documentation for this sentence, so it's probably not super clear.

2020-03-17 21:43 UTC, JoostK commented on packages/compiler-cli/ngcc/test/execution/helpers.ts
> +      tasks.push({ entryPoint, formatProperty: `prop-${tIdx}`, processDts: tIdx === 0, } as Task);
nit:

```suggestion
      tasks.push({ entryPoint, formatProperty: `prop-${tIdx}`, processDts: tIdx === 0 } as Task);
```

2020-03-17 21:43 UTC, JoostK commented on packages/compiler-cli/ngcc/test/execution/task_selection/serial_task_queue_spec.ts
> +import {computeTaskDependencies} from '@angular/compiler-cli/ngcc/src/execution/utils';
Oops, absolute import

2020-03-17 21:47 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/utils.ts
> + * Creates a task completed callback that calls one of those in a hash of callback based on the
OK

2020-03-18 14:28 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/utils.ts
> + * Creates a task completed callback that calls one of those in a hash of callback based on the
I have significantly rewritten this callback stuff. Hopefully it is more clear now.

2020-03-18 14:29 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/task_selection/base_task_queue.ts
> +  protected abstract getNextTaskWorker(): Task|null;
I went with `computeNextTask()`

2020-03-18 14:29 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/task_selection/parallel_task_queue.ts
> +    this.blockedTasks = dependencies;
I have changed it so that `blockedTasks` is now newly computed for each instance of `ParallelTaskQueue`.

2020-03-18 14:30 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/task_selection/parallel_task_queue.ts
> +    super(sortTasksByPriority(tasks, dependencies), dependents);
Done

2020-03-18 14:32 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/utils.ts
> +    TaskCompletedCallback {
I have refactored this to distinguish between `TaskCompletedCallback` which holds an outcome and `TaskCompletedHandler` which does not.

2020-03-18 14:37 UTC, petebacondarwin commented
Regarding the defaults. I have made both programmatic and command line version of `errorOnFailedEntryPoint` default to `true`.

This will mean that the CLI will need to add this option to the async CLI integration point to benefit from this.

I was not happy to make the default `false` since that would change the behaviour for the sync CLI integration point, where we definitely want the processing to fail if it comes up against a bad entry-point.

Furthermore, I don't believe that we should tie this `errorOnFailedEntryPoint` feature to whether we are targeting a specific package or not. They should be independent of each other.

2020-03-18 14:57 UTC, petebacondarwin commented
Of course now the problem will be that the CLI needs to provide a command line option but it will fail if there is a version mismatch and the option is not yet available on the versions of Angular compiler-cli...

2020-03-18 17:13 UTC, gkalpak requested changes
Some minor comments. Otherwise lgtm :+1:

2020-03-18 17:13 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/writing/in_place_file_writer.ts
> +            `This error is probably because two or more entry-points overlap and ngcc has been asked to process some files more than once.\n` +
I would say "probably" is a strong word here :grin:

2020-03-18 17:13 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/writing/in_place_file_writer.ts
> +            `You should check other entry-points in this package and set up a config to ignore any that you are not using.`);
Maybe we could include a link to some docs :wink:

2020-03-18 17:13 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.ts
> +          this.logger.error(message);
I don't think this situation can be a result of overlapping entry-points, so I don't think it is appropriate to handle it like that. (In fact, I don't think we can ever end up in this code branch, so this looks more like a sanity check.)

2020-03-18 17:17 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/execution/single_processor_executor_spec.ts
> +      get allTasksCompleted() { return tasksCount === 0 },
That is fixed in a later commit, but I will move the fix up to this point.

2020-03-18 17:19 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/writing/in_place_file_writer.ts
> +            `You should check other entry-points in this package and set up a config to ignore any that you are not using.`);
When we get some :-P

2020-03-18 17:37 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/tasks/completion.ts
> +    logger.error(
It is an error (non-fatal) in my opinion

2020-03-18 17:46 UTC, gkalpak commented
BTW, the 4th commit message needs updating wrt the current defaults for `errorOnFailedEntryPoint`.

2020-03-18 17:48 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.ts
> +          this.logger.error(message);
🤔

2020-03-18 18:30 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.ts
> +          this.logger.error(message);
If you are sure @gkalpak ... then I'll revert this bit.

2020-03-18 18:36 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.ts
> +          this.logger.error(message);
I am 90% to 95% sure 😛

All format properties pointing to the same path are updated together. So, if any ngcc instance/processing updates one, then it should update all of them. Hence, all `formatProperties` should have the value `oldFormatPath` (unless there is a bug in ngcc).

2020-03-18 18:40 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.ts
> +          this.logger.error(message);
Let's revert for now. If this error pops up then we can revisit logging this.

2020-03-18 20:43 UTC, gkalpak approved these changes
LGTM :tada: 👌 💯 

Commit message typo:
```diff
-This change adds a new `errorOnFailedEntryPoint` option to `mainNgcc` specifies whether ngcc should ...
+This change adds a new `errorOnFailedEntryPoint` option to `mainNgcc` that specifies whether ngcc should ...
```

2020-03-18 20:43 UTC, gkalpak commented on packages/compiler-cli/ngcc/main-ngcc.ts
> +  const errorOnFailedEntryPoint = !!targetEntryPointPath || options['error-on-failed-entry-point'];
Nit: This shouldn't be necessary, since it is taken care of in `src/main.ts`. I think it is better to have the "force true" logic in one place.

2020-03-18 21:01 UTC, petebacondarwin commented
ngcc-validation is green : https://app.circleci.com/pipelines/github/angular/ngcc-validation/2438/workflows/9fdc3ecd-4984-4626-b3ee-8a10906df6da

2020-03-18 21:20 UTC, JoostK approved these changes

2020-03-18 22:56 UTC, closed without merging