fix(elements): a couple of small fixes
angular/angular pull request #36114
Opened 2020-03-17 18:28 UTC by gkalpak

Several small fixes and refactorings. See individual commits for details.

Fixes #30848
Closes #31416

##
NOTE:
The last commit is a fix to the public API. It should not affect users in any way (afaict), but we might still want to only merge that last commit to master-only. (The rest is good for both master and patch.)
Happy to move the last commit to a separate PR, if we decide it shouldn't go into patch.

2020-03-17 18:43 UTC, mary-poppins commented
You can preview 77ea12e at https://pr36114-77ea12e.ngbuilds.io/.

2020-03-17 19:52 UTC, mary-poppins commented
You can preview 04d17e1 at https://pr36114-04d17e1.ngbuilds.io/.

2020-03-17 21:46 UTC, mary-poppins commented
You can preview bb59493 at https://pr36114-bb59493.ngbuilds.io/.

2020-03-18 20:04 UTC, antch commented
@gkalpak As requested I created #36130 for the `firstChange` property issue. I also found another issue which can be seen in the repro -- the output events are not hooked to the DOM event listeners during the component lifecycle events `ngOnInit`, `ngOnChanges`, `ngAfterViewInit`, and `ngAfterContentInit`. Should I create a separate issue for that?

2020-03-18 21:36 UTC, mary-poppins commented
You can preview 2919a13 at https://pr36114-2919a13.ngbuilds.io/.

2020-03-18 21:59 UTC, mary-poppins commented
You can preview 5740be8 at https://pr36114-5740be8.ngbuilds.io/.

2020-03-19 11:42 UTC, gkalpak commented
Thx, @antch! Yes, please create a separate issue for output events not firing (since it is a different issue). You can use the same repro.

2020-03-19 12:46 UTC, mary-poppins commented
You can preview 2d059c3 at https://pr36114-2d059c3.ngbuilds.io/.

2020-03-20 15:23 UTC, mary-poppins commented
You can preview 88d6ab0 at https://pr36114-88d6ab0.ngbuilds.io/.

2020-03-20 19:44 UTC, gkalpak commented on packages/elements/src/create-custom-element.ts
> +      }
This new block of logic is what causes the payload size increase (~170B).

2020-03-20 19:52 UTC, mary-poppins commented
You can preview 68b1e4c at https://pr36114-68b1e4c.ngbuilds.io/.

2020-03-20 20:17 UTC, mary-poppins commented
You can preview 2295bc2 at https://pr36114-2295bc2.ngbuilds.io/.

2020-03-23 17:35 UTC, andrewseguin approved these changes
LGTM

2020-04-28 16:21 UTC, IgorMinar requested changes

2020-04-28 16:21 UTC, IgorMinar commented on goldens/public-api/elements/elements.d.ts
> +    setInputValue(propName: string, value: any): void;
Is `any` absolutely necessary? I don't think it is, we could use `unknown` instead. right?

example: https://stackblitz.com/edit/setter-with-unknown-param

In general, we should be using `unknown` whenever possible instead of `any` (and we have been slowly introducing it into our code base and public api surface already).

Does that work for you?

2020-04-28 17:26 UTC, gkalpak commented on goldens/public-api/elements/elements.d.ts
> +    setInputValue(propName: string, value: any): void;
I changed to `any` to match the `getInputValue()` signature (which returns `any`).
Happy to go with `unknown` in both, although that has the slight potential of breaking people (in the unlikely case that they are implementing their own `NgElementStrategy`).

I added a fixup commit. PTAL

2020-04-28 17:36 UTC, mary-poppins commented
You can preview e82e1e3 at https://pr36114-e82e1e3.ngbuilds.io/.

2020-04-28 18:07 UTC, mary-poppins commented
You can preview 43b51aa at https://pr36114-43b51aa.ngbuilds.io/.

2020-04-28 23:10 UTC, IgorMinar approved these changes
LGTM for API changes. I'm a bit worried about the change to the getter, but I'm ok with this being a guinea pig change which could be rolled back if the impact is too severe. Before we proceed lets verify that this doesn't break google3 and do a cursory research on github via code search. Thanks!

Reviewed-for: public-api

2020-04-28 23:10 UTC, IgorMinar commented on goldens/public-api/elements/elements.d.ts
> +    getInputValue(propName: string): unknown;
This is a breaking change with possibly a significant impact. Do we have some evidence that we could get away with this in google3 as well as externally?

We could intentionally make this change, as it's likely a small impact, and use it as a pilot for fixing other `any`s in our public API surface.

To a developer updating to v10, this will look like TypeScript compiler getting better at type checking, which might be a good justification for making this breaking change (in addition to the expected impact being minimal since this is not a frequently used API today compared to other APIs in Angular).

In any case, this should be documented as a breaking change.

2020-05-01 12:59 UTC, gkalpak commented
At this point, I feel like the public API fix is not worth the time invested. Therefore, I am going to remove the public API changes and create an issue (in case we want to deal with it in the future).

---
For future reference:
I have search GitHub for custom implementation of `NgElementStrategy`. I have found at least three (that also implement `get/getInputValue()`):
- [spaceman27/angular9-d3: ng-zone-ng-element-strategy-factory.ts](https://github.com/spaceman27/angular9-d3/blob/c81b645a288f079be9326408e0e0be5ba2df3edb/libs/shared/utils/src/lib/elements-utils/ng-zone-ng-element-strategy-factory.ts)
- [tnicola/my-custom-element: elements-modified-zone-strategy.ts](https://github.com/tnicola/my-custom-element/blob/37ff1666579751a16589b9c92295401ca46ca73c/src/app/elements-modified-zone-strategy.ts)
- [jKelio/angular-element-example: custom-element-strategy.ts](https://github.com/jKelio/angular-element-example/blob/0cb8aba4ef0cea739120b09029f4224745223853/src/app/custom-strategy/custom-element-strategy.ts)

While I don't think these would break by the API changes, I can't be 100% sure. More importantly, the thing that matters more is where people might be using `get/setInputValue()`. This is quite hard to search for on GitHub (unless I miss something), since these terms are generic and yield too many results (unrelated to Angular Elements).

For reference, a earch for ["getInputValue("](https://github.com/search?q=%22getInputValue%28%22&type=Code) yields more than 300.000 results and for ["setInputValue("](https://github.com/search?q=%22setInputValue%28%22&type=Code) even more than that :grin:
Even trying to narrow them down by adding "angular" to the search, [I got 500+ results](https://github.com/search?q=%22setInputValue%28%22+angular&type=Code) and of course that does not guarantee that we are not missing valid results 🤷

2020-05-01 13:41 UTC, mary-poppins commented
You can preview 52d59af at https://pr36114-52d59af.ngbuilds.io/.

2020-05-01 14:00 UTC, mary-poppins commented
You can preview 7b7f205 at https://pr36114-7b7f205.ngbuilds.io/.

2020-05-14 22:59 UTC, mary-poppins commented
You can preview 0d94065 at https://pr36114-0d94065.ngbuilds.io/.

2020-05-15 02:25 UTC, mary-poppins commented
You can preview 3ab9f1d at https://pr36114-3ab9f1d.ngbuilds.io/.

2020-05-18 13:01 UTC, mary-poppins commented
You can preview aa39ff0 at https://pr36114-aa39ff0.ngbuilds.io/.

2020-05-18 14:29 UTC, mary-poppins commented
You can preview 1f32e73 at https://pr36114-1f32e73.ngbuilds.io/.

2020-05-18 15:13 UTC, gkalpak commented on packages/elements/src/create-custom-element.ts
> +  Object.defineProperty(NgElementImpl.prototype, 'ngElementStrategy', {enumerable: true});
This is an example of the error that this addition fixes: https://circleci.com/gh/angular/angular/714093

2020-05-18 15:34 UTC, gkalpak commented
I have added two new commits at the end (currently f67b1b28126d9ae913083b4998b929114d73e6b3 and 1f32e73d0f094352c82764c9d002097dcad95153) to fix an issue with TS 3.9 and an issue with certain polyfills that do not call the constructor (and was affecting g3 - need new presubmit to confirm).

@andrewseguin, ptal.

2020-05-18 18:45 UTC, AndrewKushnir commented
[New Presubmit](http://test/OCL:312122416:BASE:312122454:1589827421784:758287a2).

2020-05-18 21:34 UTC, AndrewKushnir commented on packages/elements/src/create-custom-element.ts
> +        // In some browsers (e.g. IE10), `Object.setPrototypeOf()` (which is required by some Custom
@gkalpak just want to check if IE 9/10 are affected only or this logic is needed for some other browsers as well? It looks like `Object.setPrototypeOf` is natively supported in modern browsers and given the fact that IE 9/10 will deprecated since v10, I'm wondering if this logic is needed?

2020-05-18 22:02 UTC, gkalpak commented on packages/elements/src/create-custom-element.ts
> +        // In some browsers (e.g. IE10), `Object.setPrototypeOf()` (which is required by some Custom
AFAICT, this isn;t needed for other browsers. However, this is going into v9 as well and also with IE<11 being deprecated doesn't mean we should break them :wink:
(Also, our current tests are failing without this fix; see https://github.com/angular/angular/pull/36114#discussion_r426700119.)

2020-05-18 22:07 UTC, AndrewKushnir commented on packages/elements/src/create-custom-element.ts
> +        // In some browsers (e.g. IE10), `Object.setPrototypeOf()` (which is required by some Custom
Sounds good, thanks @gkalpak 👍 
May be we can add a reference to [FW-2141](https://angular-team.atlassian.net/browse/FW-2141) (internal ticket to keep track of IE-specific code that we can refactor/cleanup later) as an inline comment?

2020-05-19 02:04 UTC, AndrewKushnir commented
FYI, Blueprint presubmit is successful. Started a [Global presubmit](https://test.corp.google.com/ui#id=OCL:312122416:BASE:312198700:1589853835175:fd069e3e) as well.

2020-05-19 12:40 UTC, gkalpak commented on packages/elements/src/create-custom-element.ts
> +        // In some browsers (e.g. IE10), `Object.setPrototypeOf()` (which is required by some Custom
:+1: Added a [comment][1] on FW-2141.

[1]: https://angular-team.atlassian.net/browse/FW-2141?focusedCommentId=14257

2020-05-19 17:30 UTC, AndrewKushnir commented
Global presubmit was successful as well 👍 (I've updated g3 status for this PR)

2020-05-19 17:30 UTC, AndrewKushnir commented on packages/elements/src/create-custom-element.ts
> +        // In some browsers (e.g. IE10), `Object.setPrototypeOf()` (which is required by some Custom
Thanks @gkalpak!

2020-05-19 18:37 UTC, andrewseguin approved these changes
LGTM

2020-05-19 22:17 UTC, kara commented
@gkalpak Can you rebase this? It's not applying cleanly to master for some reason. Also can you clarify if it should be in patch? Not sure what the resolution was for the last commit.

2020-05-20 08:20 UTC, gkalpak commented
I have removed the public API commit, so this is good for master _and_ patch. (I have updated the original comment.) I have also rebased and resolved conflicts.

2020-05-20 08:26 UTC, mary-poppins commented
You can preview dda5898 at https://pr36114-dda5898.ngbuilds.io/.

2020-05-20 16:43 UTC, closed without merging