fix(localize): allow ICU expansion to start with any character except…
angular/angular pull request #36123
Opened 2020-03-18 11:43 UTC by sonukapoor

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #31586

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-03-18 11:48 UTC, petebacondarwin requested changes
No need for the additional check now.

In the commit message, please change references to `expansion` to `expansion case` since this is what the commit is fixing.

2020-03-18 11:48 UTC, petebacondarwin commented on packages/compiler/src/ml_parser/lexer.ts
> +  return peek === chars.$EQ || peek !== chars.$RBRACE;
```suggestion
  return peek !== chars.$RBRACE;
```

2020-03-18 11:50 UTC, sonukapoor commented on packages/compiler/src/ml_parser/lexer.ts
> +  return peek === chars.$EQ || peek !== chars.$RBRACE;
Yes, of course...

2020-03-18 11:59 UTC, petebacondarwin approved these changes
Great! Thanks

2020-03-18 23:21 UTC, AndrewKushnir commented
Hi @sonukapoor, sorry I didn't have a chance to look at the changes in this PR today. Even though the diff is relatively small, I'd like to understand the code around it and see if there are any corner cases and why the function was not implemented like this before. I've started [g3 presubmit](http://test/OCL:301691009:BASE:301691112:1584573408494:76d9f45a) (internal only link) for this change as well to see if there are any cases in g3 that might be affected. Thank you.

2020-03-19 02:29 UTC, sonukapoor commented
Hi @AndrewKushnir, no problem at all:

I have discussed this offline with @petebacondarwin to make sure that we are safe to change this.

The template in question is:

```
<span i18n>{
  gOptionLabel, select,
  National transport {National transport}
  % by which guarantee amount is to be reduced {% by which guarantee amount is to be reduced}
  }
</span>
```

Once the expansion has started, we continue until we find the closing character `}`. In between that we only allow for alphanumeric characters. However, in the above example, we can see that `%` is being used instead, other characters could be used as well.  

To allow the usage of any character, except for the closing right bracket `}`, we have changed the condition. This resolves the issue and the current existing tests are still passing as well. Once, we hit the end character `}`, we close the expansion and can move on. This logic can be seen in this function (added comment blocks below only to make it easier to follow);

```
private _tokenizeExpansionForm(): boolean {
  // Expansion starts here
  if (this.isExpansionFormStart()) {
    this._consumeExpansionFormStart();
    return true;
  }

  // find the next char, and allow anything except `}`
  if (isExpansionCaseStart(this._cursor.peek()) && this._isInExpansionForm()) {
    this._consumeExpansionCaseStart();
    return true;
  }

  // Close the expansion as the current char is `}`
  if (this._cursor.peek() === chars.$RBRACE) {
    if (this._isInExpansionCase()) {
      this._consumeExpansionCaseEnd();
      return true;
    }

    if (this._isInExpansionForm()) {
      this._consumeExpansionFormEnd();
      return true;
    }
  }
  return false;
}
```

[Here](https://github.com/angular/angular/commit/a3a54299afd41cc2049953c52ff869ef9c36fc37)is a previous commit from Olivier that added support for numerical digits in expansion cases. 

@petebacondarwin please add anything else  I may have missed.

2020-03-19 09:21 UTC, petebacondarwin commented
@AndrewKushnir - yes @sonukapoor and I spent a lot of time discussing this offline and working through the possibilities. The [ICU spec](http://userguide.icu-project.org/formatparse/messages) is pretty vague:

> Use a "select" argument to select sub-messages via a fixed set of keywords.

It does not specify what can be a "keyword" but from looking at the surrounding syntax it appears that it can indeed be any string that does not contain a `}` character.

2020-03-19 23:06 UTC, AndrewKushnir approved these changes
Thanks for additional information @sonukapoor and @petebacondarwin, the change LGTM 👍 

The g3 presubmit is successful, I will start a global run tonight as well to test all affected targets in g3 just to make sure everything is ok.

Thank you.

2020-03-20 00:02 UTC, sonukapoor commented
Thanks 🙏

2020-03-20 02:13 UTC, AndrewKushnir commented
[Link to Global TAP run](https://test.corp.google.com/ui#id=OCL:301691009:BASE:301943198:1584670359389:bfb2773f) (internal only).

2020-03-20 23:19 UTC, AndrewKushnir commented
@sonukapoor, @petebacondarwin global presubmit looks good 👍

I have a couple more questions/notes:

- can we extend commit message to include info that Pete mentioned in https://github.com/angular/angular/pull/36123#issuecomment-601074010, that'd help to provide more context for future references

- previously whitespace symbols were not treated as a possible ICU case start. With this change whitespace symbols can technically be treated as ICU case start. Can we check if tis change doesn't affect i18n extraction mechanism and that i18n message IDs remain the same for ICUs after this change (otherwise it would trigger re-translation for all messages that contain ICUs)? Can we add a test (or find existing ones) to verify that?

Sorry for additional questions, just want to make sure we are not missing anything.

Thank you.

2020-03-21 08:26 UTC, petebacondarwin commented
Hi @AndrewKushnir 
I believe that we covered with regards to whitespace by this line: https://github.com/angular/angular/blob/f78876695dd46f28b99246536f3503d5e452bdb5/packages/compiler/src/ml_parser/lexer.ts#L624

When we consume an expansion case start we also trim whitespace off the front and back.
The only scenario I can think of would be to incorrectly identify a block of "only whitespace" as an expansion case. But this is actually covered by this line: https://github.com/angular/angular/blob/f78876695dd46f28b99246536f3503d5e452bdb5/packages/compiler/src/ml_parser/lexer.ts#L619 and this line https://github.com/angular/angular/blob/f78876695dd46f28b99246536f3503d5e452bdb5/packages/compiler/src/ml_parser/lexer.ts#L640

where consuming an "expansion form start" and an "expansion case" always end by skipping over whitespace.

2020-03-23 09:55 UTC, sonukapoor commented
@AndrewKushnir I have updated the commit message.

2020-03-23 17:10 UTC, AndrewKushnir commented
Thanks for additional information and updates @sonukapoor and @petebacondarwin, I'm marking this PR as ready for merge. Thank you.

2020-03-23 18:37 UTC, closed without merging