feat(dev-infra): handle excluding files via globs in pullapprove
angular/angular pull request #36162
Opened 2020-03-20 14:13 UTC by josephperrott

Updates the pullapprove verification script to handle
cases of excluding globs from groups.

2020-03-20 14:34 UTC, petebacondarwin commented
Just to be clear. PullApprove supports the negation but our verification script did not?

2020-03-20 14:35 UTC, josephperrott commented
Correct, our verification script did not handle the case.  Pullapprove has always allowed negation in its conditions.

2020-03-20 15:26 UTC, gkalpak requested changes
Yay for splitting into smaller, focused files :tada:

2020-03-20 15:26 UTC, gkalpak commented on dev-infra/pullapprove/verify.ts
> +      resultsByGroup.every(r => !r.unmatchedCount) && !unmatchedFiles.length;
This verifies that all groups have at least one condition that matched at least one file. Previously that groups only had "include" conditions that was enough to verify that a group matched at least one file. Now, however, that groups can also have "exclude" conditions it is not (because the "include" conditions may have matched files, which the "exclude" conditions have then excluded, making the group not match anything).

So, we also need to capture the matched files for each group (i.e. the files for which `group.testFile()` return true).

2020-03-20 16:59 UTC, josephperrott commented on dev-infra/pullapprove/verify.ts
> +  const ANGULAR_PROJECT_DIR = exec(`git rev-parse --show-toplevel`, {silent: true}).trim();
This is both to allow for usage in other repos as well as properly handling if the script is run from a different directory.

2020-03-20 16:59 UTC, josephperrott commented on dev-infra/pullapprove/verify.ts
> +      exec('git ls-files', {silent: true}).trim().split('\n').filter((_: string) => !!_);
By using `ls-files` we get the files both committed and staged, whereas with `ls-tree` we only get the files committed in the repo.

2020-03-20 16:59 UTC, josephperrott commented on dev-infra/pullapprove/verify.ts
> -  }
We not longer need to perform this check since we automatically move our working directory to the root directory of the git project

2020-03-20 16:59 UTC, josephperrott commented on dev-infra/pullapprove/verify.ts
> +      resultsByGroup.every(r => !r.unmatchedCount) && !unmatchedFiles.length;
I agree, that the case of files being simultaneously matched by two conditions is something we need to consider.

I believe this case is covered by the fact that we require all files to pass the `group.testFile()` method.

For instance, if I add this condition to the dev-infra group conditions:
```yaml
- >
  not contains_any_globs(files, [
    'dev-infra/pullapprove/**'
    ])
```

The output from the script is:
```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Overall Result                                │
└──────────────────────────────────────────────────────────────────────────────┘
PullApprove verification failed.

Please update '.pullapprove.yml' to ensure that all necessary
files/directories have owners and all patterns that appear in
the file correspond to actual files/directories in the repo.
┌──────────────────────────────────────────────────────────────────────────────┐
│                          PullApprove results by file                         │
└──────────────────────────────────────────────────────────────────────────────┘
Matched Files (9070 files)
Unmatched Files (5 files)
  dev-infra/pullapprove/BUILD.bazel
  dev-infra/pullapprove/group.ts
  dev-infra/pullapprove/logging.ts
  dev-infra/pullapprove/parse-yaml.ts
  dev-infra/pullapprove/verify.ts
┌──────────────────────────────────────────────────────────────────────────────┐
│                         PullApprove results by group                         │
└──────────────────────────────────────────────────────────────────────────────┘
Groups without matchers (1 groups)
Matched conditions by Group (34 groups)
Unmatched conditions by Group (0 groups)
```

2020-03-23 19:10 UTC, gkalpak commented on .pullapprove.yml
> +          ])
Is this for testing purposes?

2020-03-23 19:10 UTC, gkalpak commented on dev-infra/pullapprove/verify.ts
> -  set('-e');
Why remove this?

2020-03-23 19:10 UTC, gkalpak commented on dev-infra/pullapprove/verify.ts
> +      exec('git ls-files', {silent: true}).trim().split('\n').filter((_: string) => !!_);
Doh! I didn't notice the `ls-tree` to `ls-files` change :grin:

2020-03-23 19:40 UTC, gkalpak requested changes

2020-03-23 19:40 UTC, gkalpak commented on dev-infra/pullapprove/group.ts
> +      if (condition.startsWith('not contains_any_globs')) {
Nit: The `continue` statements are redundant here (and below).

```suggestion
      } else if (condition.startsWith('not contains_any_globs')) {
```

2020-03-23 19:40 UTC, gkalpak commented on .pullapprove.yml
> +          ])
Is this for testing purposes?

2020-03-23 19:40 UTC, gkalpak commented on dev-infra/pullapprove/verify.ts
> -  set('-e');
Why remove this?

2020-03-23 19:40 UTC, gkalpak commented on dev-infra/pullapprove/verify.ts
> +  const groupsWithoutMatchers = groups.filter(group => !group.hasMatchers);
Personally, I feel that groups without matchers (or actually even unknown group conditions) should cause a failure. For example, it is easy to misspell `contains_any_globs` and never match any files (which might be matched by other groups).

2020-03-23 19:40 UTC, gkalpak commented on dev-infra/pullapprove/verify.ts
> +      resultsByGroup.every(r => !r.unmatchedCount) && !unmatchedFiles.length;
It is true that in most cases this misconfiguration will result in some error. But there are situation where verification will succeed with invalid config (i.e. if the files are covered by another group).

For example, in #35933 the intention is to exclude `packages/compiler-cli/ngcc/` from the `compiler-cli` group by adding the following condition to the [`fw-compiler-cli` group][1]:

```yaml
- >
  not contains_any_globs(files, [
    'packages/compiler-cli/ngcc/**'
    ])
```

If we were to accidentally add it to the [`fw-ngcc` group][2], then the verification would pass, because `packages/compiler-cli/ngcc/` files would be matched by `fw-compiler-cli`, and both conditions of `fw-ngcc` would match files. Yet, the config would not be the intended one (and we could have caught that, because the `fw-ngcc` group would not match any files - although both of its conditions would match files).

[1]: https://github.com/angular/angular/blob/9d415f9c3f12cb2c29298ba414f55ce230201700/.pullapprove.yml#L146-L166
[2]: https://github.com/angular/angular/blob/9d415f9c3f12cb2c29298ba414f55ce230201700/.pullapprove.yml#L172-L186

2020-03-24 21:23 UTC, josephperrott commented on dev-infra/pullapprove/verify.ts
> +  const groupsWithoutMatchers = groups.filter(group => !group.hasMatchers);
We actually have a case already where we have a group without matchers.

We have our fallback group, which only has a condition that no other groups are matched.

2020-03-24 21:34 UTC, gkalpak commented on dev-infra/pullapprove/verify.ts
> +  const groupsWithoutMatchers = groups.filter(group => !group.hasMatchers);
My main concern is that we might misspell a condition and never realize it. So, I suggest we have a way to detect groups with unknown conditions and fail if there are any.

2020-03-24 22:43 UTC, josephperrott commented on dev-infra/pullapprove/verify.ts
> +      resultsByGroup.every(r => !r.unmatchedCount) && !unmatchedFiles.length;
I think I got it with my change I just made, PTAL.

2020-03-25 15:32 UTC, gkalpak approved these changes
LGTM 👌

2020-03-25 15:32 UTC, gkalpak commented on dev-infra/pullapprove/verify.ts
> +  // Exit early on shelljs errors
🤔 
```suggestion
  // Exit early on shelljs errors
```

2020-03-25 15:32 UTC, gkalpak commented on dev-infra/pullapprove/group.ts
> +        // An include condition is only considered matched if it no exclude
```suggestion
        // An include condition is only considered matched if no exclude
```

2020-03-27 18:13 UTC, closed without merging