docs: Minor fixes in NgModules section
angular/angular pull request #36177
Opened 2020-03-20 21:46 UTC by bampakoa

Apply minor fixes to various guides of the NgModules section

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-04-03 18:46 UTC, rockument69 requested changes
Thanks for this contribution! The following are minor grammar changes.

2020-04-03 19:53 UTC, bampakoa commented
@rockument69 thanks for the feedback 👍. I have already applied your recommended changes. Would you like me to squash them also?

2020-04-06 17:08 UTC, rockument69 commented
> @rockument69 thanks for the feedback 👍. I have already applied your recommended changes and waiting for the CI happiness 😄. Would you like me to squash them also?

Yes, go ahead and squash them. I approve this change, but I don't have approval permission. However @kara can approve this PR.

2020-04-06 19:36 UTC, bampakoa commented
Well, I have squashed the commits but I get some errors from the CI. Bear in mind that I needed to rebase with the master once again. Not sure if they have to do with my changes. @kapunahelewong @kara  any help on this would be much appreciated 🙏

2020-04-09 14:43 UTC, bampakoa commented
This is now ready. Thanks @gkalpak 😃

2020-04-09 18:55 UTC, kara commented on aio/content/guide/bootstrapping.md
> -**Only `@NgModule` references** go in the `imports` array.
Why remove this?

2020-04-09 19:24 UTC, bampakoa commented on aio/content/guide/bootstrapping.md
> -**Only `@NgModule` references** go in the `imports` array.
@kara it feels like it is in the wrong section since here we describe the `declarations` array. The `imports` array is described further below that already describes the removed sentence.

2020-04-09 20:12 UTC, kara commented on aio/content/guide/bootstrapping.md
> -**Only `@NgModule` references** go in the `imports` array.
I see. I thought you were implying that the sentence wasn't accurate. Thanks for clarifying!

2020-04-09 20:12 UTC, kara approved these changes
LGTM

2020-04-09 20:13 UTC, kara commented
@rockument69 Can you also approve this PR in the UI (so our CI check will pass)? Thanks!

2020-04-09 20:28 UTC, rockument69 approved these changes

2020-04-14 23:39 UTC, aikithoughts approved these changes
One minor suggestion, otherwise this looks good to me.

Reviewed-for: global-docs-approvers

2020-04-14 23:39 UTC, aikidave commented on aio/content/guide/ngmodule-vs-jsmodule.md
> +JavaScript modules help you use namespaces to prevent accidental global variable assignments.
```suggestion
JavaScript modules help you use namespaces to prevent you from accidentally assigning global variables.
```

I don't know if this rewrite has the same meaning. My goal was to avoid the "stack" of nouns at the end of the sentence.

2020-04-15 15:58 UTC, bampakoa commented on aio/content/guide/ngmodule-vs-jsmodule.md
> +JavaScript modules help you use namespaces to prevent accidental global variable assignments.
Nice catch @aikidave 😉

2020-08-25 17:10 UTC, AndrewKushnir commented
Hi @bampakoa, it looks like this PR is approved, but it has a conflict with a master branch. Could you please rebase this PR and resolve conflicts? Thank you.

2020-08-25 22:04 UTC, bampakoa commented
@AndrewKushnir this is now ready 👍

2020-08-25 22:14 UTC, AndrewKushnir commented
Thanks @bampakoa, I've added this PR to the merge queue.

2020-08-25 22:24 UTC, closed without merging