fix(compiler-cli): resolve rootDir to absolute
angular/angular pull request #36291
Opened 2020-03-28 05:10 UTC by Toxicable

## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
- [x] Feature

## What is the current behavior?
Issue Number: #36290

## What is the new behavior?
Allows for a relative rootDir to be passed, usually via the command line which we will join to the cwd

## Does this PR introduce a breaking change?
- [x] No

2020-04-03 20:37 UTC, Toxicable commented
Im not 100% certain this is the place to make this change so would appciate some feedback on that.

For context I'd like to land this so that we can remove the patch found here: https://github.com/bazelbuild/rules_nodejs/pull/1619/files#diff-5eb8729ae1c44d09b4ddc25c90585b9a

2020-07-17 19:21 UTC, JoostK requested changes
I was curious how this is handled in tsc, and they [preprocess the command line args using the internal `ts.convertToOptionsWithAbsolutePaths`](https://github.com/microsoft/TypeScript/blob/2c08affa0d0d7fc55f15ab22e0326b93326d21d8/src/compiler/commandLineParser.ts#L2182-L2214). Maybe we can implement a similar approach, to achieve consistent handling of compiler options.

Regardless, this change would need a test. You can probably extend `NgtscTestEnvironment` with a method to configure additional command line args, and then pass those through in `driveMain` and `driveDiagnostics`.

2020-10-17 05:33 UTC, jbedard commented
@Toxicable any update on this? I tried patching this along with the recommendation from @JoostK and it seems to be working. I could take it over if you'd like...

2020-10-17 20:43 UTC, Toxicable commented
@jbedard Ah yeah if you wanna take this one then that's cool with me

2020-10-18 01:57 UTC, jbedard commented
@JoostK is there an example of a test similar to what you're suggesting with `NgtscTestEnvironment`? Would this be testing a full run of ngtsc as opposed to testing only `readConfiguration` or `readCommandLineAndConfiguration`?

If we were to do something like `convertToOptionsWithAbsolutePaths` in typescript do you think that would go somewhere such as `readConfiguration`?

2020-11-09 16:22 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/util/src/typescript.ts
> +    return absoluteFrom(rooted);
Actually you could replace the whole return statement with:

```ts
return rootDirs.map(rootDir => fs.resolve(cwd, rootDir);
```

2020-11-09 17:32 UTC, petebacondarwin commented
@jbedard - you could certainly create a simply unit test in a new file `typescript_spec.ts` at https://github.com/angular/angular/tree/master/packages/compiler-cli/src/ngtsc/util/test.

I would run this test using `runInEachFileSystem()` to provide a mock `FileSystem` for the tests.

I am not convinced that an e2e test is particularly needed.

2021-03-28 18:10 UTC, literalpie commented
I'm taking a stab at this in #41359

2021-03-30 14:21 UTC, petebacondarwin commented
Closing in favour of #41359

2021-03-30 14:21 UTC, closed without merging