docs: clarifies the service limitation
angular/angular pull request #36349
Opened 2020-03-31 10:45 UTC by sonukapoor

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #36332

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-04-11 15:30 UTC, ajitsinghkaler commented
@sonukapoor commit-msg is not correct please add fixes #36332 so that that issue closes automatically once this pull request closes

2020-04-21 19:51 UTC, sonukapoor commented
@pkozlowski-opensource Can you please review this?

2020-04-23 15:09 UTC, aikithoughts requested changes

2020-04-23 15:09 UTC, aikidave commented on aio/content/guide/providers.md
> +(other components in the same module can’t access it).
Readers tend to skip content in parentheses. I recommend avoiding them. 

```suggestion
Other components in the same module can’t access it.
```

2020-04-23 15:09 UTC, aikidave commented on aio/content/guide/providers.md
> +Providing a service in the component limits the service only to that component and its descendants
```suggestion
Providing a service in the component limits the service only to that component and its descendants.
```
(This goes along with my other suggestion below.

2020-04-23 15:29 UTC, aikithoughts requested changes

2020-04-23 15:29 UTC, aikidave commented on aio/content/guide/providers.md
>  Providing a service in the component limits the service only to that component and its descendants
I think you still need a period at the end of line 61.

2020-04-23 15:33 UTC, sonukapoor commented on aio/content/guide/providers.md
>  Providing a service in the component limits the service only to that component and its descendants
Yes, I was trying the GitHub suggestion feature. It didn't work properly. I will download the branch and make the update today. Thanks for reviewing it.

2020-04-23 16:43 UTC, sonukapoor commented on aio/content/guide/providers.md
>  Providing a service in the component limits the service only to that component and its descendants
This should be good now. Please re-review.

2020-04-23 18:23 UTC, aikithoughts approved these changes

2020-05-12 10:52 UTC, sonukapoor commented
@aikidave / @pkozlowski-opensource Any chance to get this merged?

2020-05-14 18:58 UTC, kara approved these changes
LGTM

2020-05-14 18:59 UTC, closed without merging