docs: rework lifecycle hooks topic for style and clarity
angular/angular pull request #36353
Opened 2020-03-31 14:57 UTC by jbogarthyde

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

 https://angular.io/guide/lifecycle-hooks needs update to conform to current doc style standards.  

Issue Number:   https://angular-team.atlassian.net/browse/DOCS-714

## What is the new behavior?
Edited and reorganized to be more task oriented and conform to current style standards.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-03-31 15:06 UTC, mary-poppins commented
You can preview 34f2c37 at https://pr36353-34f2c37.ngbuilds.io/.

2020-03-31 16:29 UTC, mary-poppins commented
You can preview 6575729 at https://pr36353-6575729.ngbuilds.io/.

2020-03-31 23:06 UTC, rockument69 reviewed
This is very well written! My apologies if I was a bit overzealous about comments. These are suggestions, mostly about style issues that were drilled into me when I was writing for Google devs/partners. Thanks!

2020-03-31 23:06 UTC, rockument69 commented on aio/content/guide/lifecycle-hooks.md
>  the `AfterContentComponent`'s parent. Here's the parent's template:
"The following is the parent's template:"

2020-04-01 16:16 UTC, jbogarthyde commented on aio/content/guide/lifecycle-hooks.md
> +The object reference did not change when the value of its own `name` property changed.
It is.

2020-04-01 16:28 UTC, mary-poppins commented
You can preview 960c7d1 at https://pr36353-960c7d1.ngbuilds.io/.

2020-04-06 15:08 UTC, mary-poppins commented
You can preview 51bca9e at https://pr36353-51bca9e.ngbuilds.io/.

2020-04-07 16:32 UTC, mary-poppins commented
You can preview 854ae5d at https://pr36353-854ae5d.ngbuilds.io/.

2020-04-08 15:45 UTC, mary-poppins commented
You can preview 5940673 at https://pr36353-5940673.ngbuilds.io/.

2020-04-13 15:09 UTC, mary-poppins commented
You can preview 3d42bd9 at https://pr36353-3d42bd9.ngbuilds.io/.

2020-04-14 23:33 UTC, aikithoughts approved these changes
Looks good to me! A minor change needed for the Prerequisites section, and it looks like Tony has a couple of other suggestions as well. Thanks for doing this!

Reviewed-for: global-docs-approvers

2020-04-14 23:33 UTC, aikidave commented on aio/content/guide/lifecycle-hooks.md
> +#### Prerequisites
I think Prerequisites should be level 2. I think it makes it more visible to the user--especially when they are skimming the headings.

```suggestion
## Prerequisites
```

2020-04-15 15:37 UTC, mary-poppins commented
You can preview 6e61613 at https://pr36353-6e61613.ngbuilds.io/.

2020-04-15 17:02 UTC, mary-poppins commented
You can preview 8b6e83e at https://pr36353-8b6e83e.ngbuilds.io/.

2020-04-20 15:17 UTC, mary-poppins commented
You can preview 73a853a at https://pr36353-73a853a.ngbuilds.io/.

2020-04-21 22:04 UTC, mary-poppins commented
You can preview 6ded5f9 at https://pr36353-6ded5f9.ngbuilds.io/.

2020-04-22 18:57 UTC, kapunahelewong approved these changes
Just minor suggestions. 🏄🏻‍♀️

2020-04-22 18:57 UTC, kapunahelewong commented on aio/content/guide/glossary.md
> +As the Angular [change detector](#change-detection) traverses the [view hierarchy](#view-hierarchy), it needs to be sure that a change in a child does not make a change in its own parent that would l
"To ensure this...." should be on its own line.

2020-04-22 18:57 UTC, kapunahelewong commented on aio/content/guide/lifecycle-hooks.md
> +      Called  immediately before Angular destroys the directive or component.
It looks like there's an extra space after "called", but it doesn't look like it in the suggestion. **rubs eyes**

2020-04-22 18:57 UTC, kapunahelewong commented on aio/content/guide/lifecycle-hooks.md
> +The following table lists the exercises with brief descriptions. The sample code is also used to illustrate specific tasks in the following sections.
```suggestion
The following table lists the exercises with brief descriptions. 
The sample code is also used to illustrate specific tasks in the following sections.
```

(hard return for new sentence)

2020-04-22 18:57 UTC, kapunahelewong commented on aio/content/guide/lifecycle-hooks.md
> +The example does not perform any initialization or clean-up. It just tracks the appearance and disappearance of an element in the view by recording when the directive itself is instantiated and destr
Hard return for new sentence, "It just tracks..."

2020-04-22 18:57 UTC, kapunahelewong commented on aio/content/guide/lifecycle-hooks.md
> +so you can see how often `DoCheck` is called. The results are illuminating:
```suggestion
so you can see how often `DoCheck()` is called. The results are illuminating:
```

2020-04-22 20:24 UTC, jbogarthyde commented on aio/content/guide/lifecycle-hooks.md
> +      Called  immediately before Angular destroys the directive or component.
There was 👍

2020-04-22 20:39 UTC, mary-poppins commented
You can preview 68fd81b at https://pr36353-68fd81b.ngbuilds.io/.

2020-04-27 15:52 UTC, mary-poppins commented
You can preview 9d71941 at https://pr36353-9d71941.ngbuilds.io/.

2020-04-27 17:45 UTC, mary-poppins commented
You can preview d63403f at https://pr36353-d63403f.ngbuilds.io/.

2020-05-04 15:00 UTC, mary-poppins commented
You can preview 79aba47 at https://pr36353-79aba47.ngbuilds.io/.

2020-05-05 18:02 UTC, mary-poppins commented
You can preview fee73c0 at https://pr36353-fee73c0.ngbuilds.io/.

2020-05-06 15:48 UTC, mary-poppins commented
You can preview 9e5a3be at https://pr36353-9e5a3be.ngbuilds.io/.

2020-05-08 22:13 UTC, kara requested changes
Thanks for all the cleanup! Suggestions below

2020-05-08 22:13 UTC, kara commented on aio/content/guide/lifecycle-hooks.md
> +As the Angular change detector traverses the [view hierarchy](guide/glossary#view-hierarchy "Definition of view hierarchy definition"), it needs to be sure that a change in a child does not cause a c
Angular doesn't really have a separate change detector entity as such

```suggestion
As Angular traverses the [view hierarchy](guide/glossary#view-hierarchy "Definition of view hierarchy definition") during change detection, it needs to be sure that a change in a child does not attempt to cause a change in its own parent, which would not be rendered properly due to unidirectional data flow](guide/glossary#unidirectional-data-flow "Definition"). 
```

2020-05-08 22:13 UTC, kara commented on aio/content/guide/lifecycle-hooks.md
> +This rule forbids updates to a view after it has been composed.
```suggestion

```

2020-05-08 22:13 UTC, kara commented on aio/content/guide/lifecycle-hooks.md
> +The examples illustrate how to make such changes safely.
```suggestion
If you need to make a change that inverts the expected data flow, it's necessary to trigger a new change detection cycle so the change is rendered.
The examples illustrate how to make such changes safely.
```

2020-05-08 22:13 UTC, kara commented on aio/content/guide/lifecycle-hooks.md
> +This is an example of how to abide by Angular's *unidirectional data flow* rule, which forbids updates to the view after it has been composed.
Calling unidirectional data flow a "rule" makes it sound like an arbitrary stylistic thing that we enforce. In reality, it's just the order that components are checked, which is necessary to understand if you want your components to render as expected.

```suggestion
```

2020-05-08 22:13 UTC, kara commented on aio/content/guide/lifecycle-hooks.md
>  for one turn of the browser's JavaScript cycle and that's just long enough.
The docs make it sound like it's a matter of waiting long enough, but it's really that causing a browser tick in itself *causes* change detection to run (because of how zone.js works)

```suggestion
for one turn of the browser's JavaScript cycle, which triggers a new change detection cycle to run.
```

2020-05-08 22:13 UTC, kara commented on aio/content/guide/lifecycle-hooks.md
> +There's no need to delay the update to avoid violating by Angular's [unidirectional data flow rule](#wait-a-tick).
```suggestion
There's no need to delay the update to [ensure proper rendering](#wait-a-tick).
```

2020-05-11 14:58 UTC, mary-poppins commented
You can preview 243cfc3 at https://pr36353-243cfc3.ngbuilds.io/.

2020-05-11 18:11 UTC, jbogarthyde commented on aio/content/guide/lifecycle-hooks.md
> +# Managing the component lifecycle
"Hooking into the component lifecycle"

2020-05-11 18:28 UTC, kara commented on aio/content/guide/lifecycle-hooks.md
> +# Managing the component lifecycle
I like that!

2020-05-11 19:23 UTC, mary-poppins commented
You can preview fd8b838 at https://pr36353-fd8b838.ngbuilds.io/.

2020-05-12 14:46 UTC, mary-poppins commented
You can preview a6fdfd0 at https://pr36353-a6fdfd0.ngbuilds.io/.

2020-05-12 17:49 UTC, kara approved these changes
LGTM, with a few more updates

2020-05-12 17:49 UTC, kara commented on aio/content/guide/lifecycle-hooks.md
> +      See details in [Initializing on instance creation](#oninit) in this document.
Might want to update the title here too

```suggestion
      See details in [Initializing a component or directive](#oninit) in this document.
```

2020-05-12 17:49 UTC, kara commented on aio/content/guide/lifecycle-hooks.md
> +As the Angular traverses the [view hierarchy](guide/glossary#view-hierarchy "Definition of view hierarchy definition") during change detection, it needs to be sure that a change in a child does not a
This isn't a rule (it's just how the code runs).

```suggestion
As Angular traverses the [view hierarchy](guide/glossary#view-hierarchy "Definition of view hierarchy definition") during change detection, it needs to be sure that a change in a child does not attempt to cause a change in its own parent. Such a change would not be rendered properly, because of how [unidirectional data flow](guide/glossary#unidirectional-data-flow "Definition") works.
```

2020-05-12 22:15 UTC, mary-poppins commented
You can preview 87f530a at https://pr36353-87f530a.ngbuilds.io/.

2020-05-13 01:10 UTC, IgorMinar approved these changes
LGTM except for a few suggestions. Thanks!

Reviewed-for: public-api

2020-05-13 01:10 UTC, IgorMinar commented on aio/content/guide/glossary.md
> +A way to insert HTML content from outside a component into the component's template in a designated spot.
```suggestion
A way to insert DOM content from outside a component into the component's view in a designated spot.
```

2020-05-13 01:10 UTC, IgorMinar commented on aio/content/guide/glossary.md
> +In development mode, Angular throws an error if your app attempts to do this, rather than silently failing to render the new value.
```suggestion
In development mode, Angular throws the `ExpressionChangedAfterItHasBeenCheckedError` error if your app attempts to do this, rather than silently failing to render the new value.
```

2020-05-13 14:54 UTC, mary-poppins commented
You can preview ada7679 at https://pr36353-ada7679.ngbuilds.io/.

2020-05-13 22:51 UTC, closed without merging