Dev infra benchmarking
angular/angular pull request #36434
Opened 2020-04-04 22:26 UTC by wagnermaciel

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Why are we making this change?
We would like to reuse the benchmarking code in `angular/angular` in `angular/components`.

2020-04-08 00:02 UTC, wagnermaciel commented on dev-infra/tools/component_benchmark/defaults/BUILD.bazel
> +filegroup(
Should I comment each `filegroup`? All of them are doing the same thing - grouping the files so that they are all included in the `pkg_npm`.

2020-04-08 17:35 UTC, jelbourn commented on dev-infra/tools/component_benchmark/defaults/BUILD.bazel
> +filegroup(
That would be a good enough comment for me ("Make source files available for distribution via `pkg_npm`")

2020-04-08 18:57 UTC, ayazhafiz approved these changes
👍 for language service

2020-04-13 20:46 UTC, jelbourn approved these changes
LGTM

2020-04-14 20:35 UTC, devversion approved these changes
LGTM. Nice work! 🎉 A few minor nits.

2020-04-14 20:35 UTC, devversion commented on dev-infra/BUILD.bazel
> +        "//dev-infra/": "@npm_dev_infra//",
Can you please add a comment on why we need this? e.g. so that these utilties can be directly accessed from other bazel targets in the `angular/angular` repo?

2020-04-14 20:35 UTC, devversion commented on dev-infra/tmpl-package.json
> +    "reflect-metadata": "<from-root>"
Do you know where this dependency is used? I couldn't find it. Seems to be already a dep of benchpress?

2020-04-14 20:35 UTC, devversion commented on dev-infra/tmpl-package.json
> +    "fs-extra": "<from-root>",
We could omit this dependency by just using `shelljs` for `mkdir -p`.

2020-04-14 20:35 UTC, devversion commented on dev-infra/tmpl-package.json
> +    "@angular/benchpress": "^0.1.0",
This also has a dependency on `@bazel/protractor` now, right? I see it used in the start server script.

2020-04-14 20:35 UTC, devversion commented on dev-infra/BUILD.bazel
> +        "//tools:defaults.bzl": "@npm_angular_bazel//:index.bzl",
This replacement is kind of magic. Definitely needs a comment. It makes the assumption that only TypeScript stuff is imported from `tools/defaults.bzl`. We could easily regress here and the downstream package will fail, right?

2020-04-14 20:35 UTC, devversion commented on dev-infra/tmpl-package.json
> +    "@angular/benchpress": "^0.1.0",
There actually seem to be more: https://github.com/angular/angular/blob/a04e8a2c0f831dbc098d867b3e9307f51101d719/dev-infra/tools/ng_rollup_bundle/BUILD.bazel#L13-L18.

I'm unsure what our policy should be on managing dependencies for the dev-infra package.

2020-04-14 20:35 UTC, devversion commented on dev-infra/benchmark/driver-utilities/BUILD.bazel
> +filegroup(
Is this `filegroup` and the one in `benchmark/BUILD.bazel` needed? They aren't used anywhere from what I can tell.

2020-04-14 20:35 UTC, devversion commented on dev-infra/BUILD.bazel
> +        "//dev-infra/tools:files",
Are are we all set on the location of these utilities? Everything inside `dev-infra/*` could be already considered tools. 

Out of curiosity: why is `component_benchmark` not part of `dev-infra/benchmark`?

2020-04-14 21:26 UTC, wagnermaciel commented on dev-infra/BUILD.bazel
> +        "//dev-infra/tools:files",
We can change the location of the utilities. I just named it the same as what folder they were under in angular/angular.

I placed `component_benchmark` in `dev-infra/tools` instead of `dev-infra/benchmark` so that it would live with the other macros we're defining, but I can move it.

2020-04-14 21:33 UTC, wagnermaciel commented on dev-infra/BUILD.bazel
> +        "//tools:defaults.bzl": "@npm_angular_bazel//:index.bzl",
That's a great observation! I'll make the substitutions more verbose to avoid a regression like this

2020-04-14 21:36 UTC, wagnermaciel commented on dev-infra/tmpl-package.json
> +    "@angular/benchpress": "^0.1.0",
Yeah, this is kind of tricky to get right because when I'm testing this (by using it in the angular/components repo) some of these dependencies are already defined, which makes figuring out which ones are missing difficult.

Is there an easy way to track down which dependencies are missing?

2020-04-15 18:41 UTC, wagnermaciel commented on dev-infra/BUILD.bazel
> +        "//dev-infra/": "@npm_dev_infra//",
How does this sound?

"angular/angular should not consume it's own packages, so we use substitutions to replace these in the deployed version of dev-infra."

2020-04-15 18:42 UTC, wagnermaciel commented on dev-infra/tmpl-package.json
> +    "reflect-metadata": "<from-root>"
I'm not sure where, but I do remember getting errors about some files missing from `reflect-metadata` and adding this to dev-infra's deps fixed it.

2020-04-15 18:50 UTC, wagnermaciel commented on dev-infra/tmpl-package.json
> +    "fs-extra": "<from-root>",
We can, but I'd rather we do this in a follow up PR if that's ok with you

2020-04-15 20:08 UTC, devversion commented on dev-infra/BUILD.bazel
> +        "//dev-infra/": "@npm_dev_infra//",
👍

2020-04-15 20:08 UTC, devversion commented on dev-infra/tmpl-package.json
> +    "reflect-metadata": "<from-root>"
It might be worth double-checking. Most of the time we use `core-js` as a better replacement for `reflect-metadata` too.

2020-04-15 20:08 UTC, devversion commented on dev-infra/tmpl-package.json
> +    "fs-extra": "<from-root>",
Sure, fine by me.

2020-04-15 20:09 UTC, devversion commented on dev-infra/tmpl-package.json
> +    "@angular/benchpress": "^0.1.0",
I just went through the folder and looked for potential imports. I don't think there is anything easy that can help us enforcing this

2020-04-15 20:10 UTC, devversion commented on dev-infra/BUILD.bazel
> +        "//dev-infra/tools:files",
I don't mind too much. I'd like to have a policy on where which stuff should live. I could definitely imagine the component benchmark macro to be part of `dev-infra/benchmark`.

2020-04-15 22:06 UTC, wagnermaciel commented on dev-infra/benchmark/driver-utilities/BUILD.bazel
> +filegroup(
Nope. I think I left this in on accident when trying to get `npm_package` right. I'll remove it!

2020-04-16 19:48 UTC, wagnermaciel commented on dev-infra/BUILD.bazel
> +        "//dev-infra/tools:files",
@jelbourn Would you like to weigh in here. I definitely agree with @devversion that these could be structured better

@josephperrott I know you probably have strong opinions about this as well

2020-04-16 20:03 UTC, josephperrott commented on dev-infra/BUILD.bazel
> +        "//dev-infra/tools:files",
My initial thought/reaction is that we should have all the benchmarking specific stuff in dev-infra should be under `//dev-infra/benchmarking/`. Having things be in `//dev-infra/tools` to me implies that it is an end user (of the dev-infra package) tool or a common tool for usage within the dev-infra package.  But to my understanding, all of these things are specific to benchmarking, so they should live there (at least until they are needed by something else).

2020-04-16 20:16 UTC, wagnermaciel commented on dev-infra/tmpl-package.json
> +    "reflect-metadata": "<from-root>"
Just checked and didn't get the errors anymore. Even tried running `bazel clean --expunge`. I'm gonna remove it 👍

2020-04-16 20:48 UTC, wagnermaciel commented on dev-infra/BUILD.bazel
> +        "//dev-infra/tools:files",
That sounds great to me. So unless anyone has anything else to add, the plan is to delete `//dev-infra/tools` and move it's contents to `//dev-infra/benchmarking`.

2020-04-16 22:00 UTC, wagnermaciel commented on dev-infra/tmpl-package.json
> +    "@angular/benchpress": "^0.1.0",
I went through and added all of the deps that I could find to `tmpl_package.json` but this really should be double checked

2020-04-17 08:33 UTC, devversion approved these changes
Two minor nits, then this should be ready to go!

PR also needs a rebase for CI.

2020-04-17 08:33 UTC, devversion commented on dev-infra/tmpl-package.json
> +    "@types/yargs": "<from-root>",
We could skip all the `@types` dependencies here. These are only needed for creation of the `pkg_npm`, but not needed by consumers.

2020-04-17 08:33 UTC, devversion commented on dev-infra/tmpl-package.json
> +    "@angular/benchpress": "^0.1.0",
Awesome, thanks!

I'm unsure how we should manage the dependencies on `@angular/*` packages in the long-term, but for now that should be fine.

2020-04-17 08:33 UTC, devversion commented on dev-infra/tools/BUILD.bazel
> +package(default_visibility = ["//visibility:public"])
We should be able to delete that file now?

2020-04-17 15:36 UTC, IgorMinar requested changes
Thanks @wagnermaciel, this looks like an awesome cleanup!

I left a bunch of comments - please don't get discouraged by their number they are mostly related to the commit message guidelines that you don't seem to be following in this PR and the fix should be simple.

Additionally, I suggest that you squash all the `cp` and `rm` commits, which should allow git to stitch the history together and emulate `mv` operation (more details in other commits).

Lastly, let's revisit the need to use `reflect-metadata` as our dep in these benchmarks. That doesn't look right.

Thanks for all the hard work!

2020-04-17 15:36 UTC, IgorMinar commented on BUILD.bazel
>  exports_files([
can you please update the commit message as well similar to how I asked for before. in this case you might want to say something like this:
```
build(core): use dev-infra's component_benchmark rule throughout the repo

This change is a follow up on the earlier PoC that uses the newly created
`//dev-infra/tools/component_benchmark` rule in the remaining performance tests
in the repo.
```

2020-04-17 15:36 UTC, IgorMinar commented on dev-infra/tmpl-package.json
> +    "reflect-metadata": "<from-root>"
why? none of our tests should require reflect-metadata. Can we please review this as it might be a symptom of an underlying bug that should be fixed instead of this dependency being provided.

2020-04-17 15:36 UTC, IgorMinar commented on dev-infra/tmpl-package.json
> +    "reflect-metadata": "<from-root>"
also, please update the commit message capturing the "why" :-) 

this is a great example of how documenting the "why" in commit messages can speed up code reviews - if the info is provided up front, we don't need to go back and forth as much.

2020-04-17 15:36 UTC, IgorMinar commented on dev-infra/BUILD.bazel
>          "//packages/zone.js/dist:zone.js": "@npm//:node_modules/zone.js/dist/zone.js",
`fix(dev-infra): ....`

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

2020-04-17 15:36 UTC, IgorMinar commented on dev-infra/benchmark/browsers/BUILD.bazel
>          "@io_bazel_rules_webtesting//common/conditions:mac": {"CHROMIUM": "chrome-mac/Chromium.app/Contents/MacOS/chromium"},
see! this is a great example of how awesome git is at tracking file moves if you use `mv` instead of `cp`. We now have the file history preserved and git even showed us what you changed in the file in addition to the move.

2020-04-17 17:23 UTC, wagnermaciel commented on dev-infra/benchmark/browsers/BUILD.bazel
>          "@io_bazel_rules_webtesting//common/conditions:mac": {"CHROMIUM": "chrome-mac/Chromium.app/Contents/MacOS/chromium"},
I actually didn't know git was clever enough to track copying files. I just used what came to mind when trying to move the files over.

I'm going to go through and see if I can revert these commits and redo them properly

2020-04-22 20:11 UTC, wagnermaciel commented on dev-infra/tmpl-package.json
> +    "@types/yargs": "<from-root>",
@devversion I made the changes you requested. They are not in separate commits because they were squashed together to make this PR cleaner.

If you look at [`//dev-infra/tmpl-package.json`](https://github.com/angular/angular/pull/36434/files#diff-0a136973c4e9e2f95711f04ba1e719e7) you can see that I have removed all of the `@types` dependencies.

Thanks for helping me get these deps right!

2020-04-23 00:34 UTC, JiaLiPassion approved these changes
LGTM for zone.js part.

2020-04-23 17:02 UTC, devversion commented on dev-infra/tmpl-package.json
> +    "@types/yargs": "<from-root>",
Thanks! I also added an item to the dev-infra sync on how we want to manage these dependencies. In the current state, it's pretty inconvenient and difficult to enforce.

2020-04-23 18:51 UTC, IgorMinar approved these changes
This PR so now so much easier to review and the commit messages are quite good. The only thing I'd recommend in the future (not needed to fix in this PR) is to add one more sentence to each of the PR that answers the "why this change?" question - currently the commit messages primarily capture "what is this change?" which is good, but "why?" is more important.

In any case, this PR is great! Thanks for all the work! Let's get this in.

2020-04-23 18:51 UTC, IgorMinar commented on dev-infra/tmpl-package.json
> +    "@angular/bazel": "^9.0.0",
just an FYI @wagnermaciel (no action needed): @devversion will update some of these `peerDependencies` to `dependencies` after your PR lands. Is is happening due to an unrelated dev-infra improvement work that @devversion is working on. We do want to land your PR before that happens so that we don't block you any longer. If you have any questions about this, please follow up with Paul. thanks!

2020-04-23 18:51 UTC, IgorMinar commented on dev-infra/tools/BUILD.bazel
> -package(default_visibility = ["//visibility:public"])
I think this diff doesn't belong to this commit, it seems to belong to the previous commit. I'm hower fine with keeping it here just so that you don't have to rebase this PR one more time.

2020-04-23 18:51 UTC, IgorMinar commented on modules/benchmarks/src/class_bindings/BUILD.bazel
> +load("//dev-infra/benchmark/component_benchmark:component_benchmark.bzl", "component_benchmark")
yay! so much cleanup before we finally get to this PoC one liner. It might look like you haven't done much, but in fact this one liner is so significant because of all the underlying cleanup that happened to get here, and more importantly this oneliner makes a lot of our future work just a bunch of oneliners as well. Great work!

2020-04-23 18:53 UTC, IgorMinar commented
merge-assistance: if this PR doesn't cleanly cherry-pick on the patch branch, then please merge this into master-only and notify @wagnermaciel to create a separate PR that targets only the patch branch.

2020-04-23 18:57 UTC, devversion commented on modules/benchmarks/src/class_bindings/BUILD.bazel
> +load("//dev-infra/benchmark/component_benchmark:component_benchmark.bzl", "component_benchmark")
+100. awesome work!

2020-04-23 19:25 UTC, AndrewKushnir commented
@wagnermaciel, could you please rebase this PR on top of the current master? There are no conflicts from code perspective, but it'd be great to re-run CI again with the latest changes from master (that contain some CI/infra-related changes). Thank you.

2020-04-23 19:34 UTC, wagnermaciel commented
@AndrewKushnir Just finished rebasing on top of the current master as per your request 👍

2020-04-23 20:07 UTC, IgorMinar commented
@wagnermaciel please remove the "cleanup" label in the future after the PR is updated, that gives the signal to the caretaker that the PR is good to be merged now

2020-04-23 20:32 UTC, AndrewKushnir commented
Thanks for rebasing @wagnermaciel 👍

2020-04-23 20:32 UTC, closed without merging

2020-04-23 20:33 UTC, IgorMinar commented
@wagnermaciel in general the caretaker will not pick up a PR that is not fully green which looks like this:

<img width="797" alt="Screen Shot 2020-04-23 at 1 25 54 PM" src="https://user-images.githubusercontent.com/216296/80146592-edbd8380-8566-11ea-86ba-1e2ffb99a1d2.png">

It is the responsibility of a PR author (and secondarily the reviewers) to get the PR into a green state. If you can't and need help, you can ask anyone on the team or the caretaker to help get