docs: Add new section, tutorials, to left nav, and a tutorial on routing
angular/angular pull request #36545
Opened 2020-04-09 17:46 UTC by aikidave

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Many topics contain a mix of concepts, tasks, and tutorials. This mixture can make it frustrating and confusing for users reading our docs.

Issue Number: N/A

## What is the new behavior?
To better serve the developer community, I am adding a new section to the left navigation: Tutorials. I've also taken a copy of the tutorial from the Routing and Navigation topic, and added it to that directory.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-04-09 17:57 UTC, mary-poppins commented
You can preview 05014d7 at https://pr36545-05014d7.ngbuilds.io/.

2020-04-14 17:30 UTC, mary-poppins commented
You can preview 2a5fa1c at https://pr36545-2a5fa1c.ngbuilds.io/.

2020-04-14 20:22 UTC, mary-poppins commented
You can preview 608a89e at https://pr36545-608a89e.ngbuilds.io/.

2020-04-15 18:11 UTC, mary-poppins commented
You can preview aac5e91 at https://pr36545-aac5e91.ngbuilds.io/.

2020-04-16 22:23 UTC, GitHubGaryHoh commented on aio/content/guide/router-tutorial.md
> +This tutorial describes how to build a single-page application that uses multiple Angular routes.
Say "describes how you can build..."
```suggestion
This tutorial describes how you can build a single-page application that uses multiple Angular routes.
```

2020-04-20 17:28 UTC, gkalpak reviewed
Drive-by comments :smiley:

2020-04-20 17:28 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +      {path: '',    redirectTo: '/heroes-list', pathMatch: 'full' },
```suggestion
      {path: '', redirectTo: '/heroes-list', pathMatch: 'full'},
```

2020-04-22 16:21 UTC, mary-poppins commented
You can preview 7520bf6 at https://pr36545-7520bf6.ngbuilds.io/.

2020-04-22 21:43 UTC, mary-poppins commented
You can preview b5f3f39 at https://pr36545-b5f3f39.ngbuilds.io/.

2020-04-23 01:10 UTC, mary-poppins commented
You can preview a6286c9 at https://pr36545-a6286c9.ngbuilds.io/.

2020-04-23 17:51 UTC, mary-poppins commented
You can preview e2740bc at https://pr36545-e2740bc.ngbuilds.io/.

2020-04-23 18:06 UTC, mary-poppins commented
You can preview d2fd9da at https://pr36545-d2fd9da.ngbuilds.io/.

2020-04-23 19:19 UTC, kapunahelewong commented on aio/content/examples/router-tutorial/src/app/pagenotfound/pagenotfound.component.html
> +<h2>Page Not Found</h2>
```suggestion
<h3>Page Not Found</h3>
```
Oh btw, don't forget to adjust that for the e2e test (if you're using the one from slack today) because that one references the h2.

2020-04-23 21:27 UTC, mary-poppins commented
You can preview 5d6bbce at https://pr36545-5d6bbce.ngbuilds.io/.

2020-04-24 15:50 UTC, aikidave commented on aio/content/examples/router-tutorial/src/app/pagenotfound/pagenotfound.component.html
> +<h2>Page Not Found</h2>
I changed the test to look for the second h2 element, which would be the Page Not Found element. That should do the trick, right?

2020-04-24 20:39 UTC, gkalpak requested changes
Looks great. Left a few comments/questions.

2020-04-24 20:39 UTC, gkalpak commented on aio/content/examples/router-tutorial/src/app/app.component.css
> +button {
It is not great to have these custom styles for generic things such as buttons on each example.

We have a common [style.css][1] that is copied to all examples. Maybe use the generic styles from there.

[1]: https://github.com/angular/angular/blob/2365bb89d7a37089f596705db19b1ee5d0366b42/aio/tools/examples/shared/boilerplate/common/src/styles.css

2020-04-24 20:39 UTC, gkalpak commented on aio/content/examples/router-tutorial/src/app/pagenotfound/pagenotfound.component.ts
> +export class PagenotfoundComponent implements OnInit {
`PageNotFoundComponent` (and `page-not-found.component.ts`) would be more consistent with the other components :grin:

2020-04-24 20:39 UTC, gkalpak commented on aio/content/examples/router-tutorial/src/app/app.module.ts
> +  // #docplaster
As a convention, we put `// #docplaster` comments at the top of the file, unless we want to change the plaster in the middle of a file.

2020-04-24 20:39 UTC, gkalpak commented on aio/content/examples/router-tutorial/src/app/app.component.html
> +<h2>Angular Router Sample</h2>
Why not use `h1`? This seems semantically inaccurate.

2020-04-24 20:39 UTC, gkalpak commented on aio/content/examples/router-tutorial/src/app/app.component.html
> +  <button routerLink="/heroes-list" routerLinkActive="active">Heroes</button>
Why not use `<a>` elements instead? They are semantically preferrable.

2020-04-24 20:39 UTC, gkalpak commented on aio/content/examples/router-tutorial/e2e/src/app.e2e-spec.ts
> +    await crisisButton.click();
```suggestion
    const heroesButton = element.all(by.css('button')).get(1);
    await heroesButton.click();
```

2020-04-24 20:39 UTC, gkalpak commented on aio/content/examples/router-tutorial/e2e/src/app.e2e-spec.ts
> +    });
I think just `browser.get('/fake-page')` should be enough.

2020-04-24 20:39 UTC, gkalpak commented on aio/content/examples/router-tutorial/e2e/src/app.e2e-spec.ts
> +  });
This test is redundant. It checks the same thing as the `should display HEROES` test above.

2020-04-24 20:39 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +   <code-example language="none" class="code-shell">
Why not `language="sh"` (here and below)?

Actually, I think these code examples should be:

```suggestion
   <code-example language="sh">
```

<sub>I know we have the `code-shell` class in many similar code snippets, but it actually adds the same styles as `language="sh"`, so I there shouldn't be a reason not to use that instead.</sub>

2020-04-24 20:39 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +1. Use the `ng generate` to create a component, _crisis-list_.
```suggestion
1. Use the `ng generate` command to create a component, _crisis-list_.
```

???

2020-04-24 20:39 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +1. Use the `ng generate` to create a second component, _heroes-list_.
```suggestion
1. Use the `ng generate` command to create a second component, _heroes-list_.
```

???

2020-04-24 20:39 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +* The path `[root-path]/heroes-list` opens the `heroes-list` component.
OOC, why the `[root-path]` part?

2020-04-24 20:39 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +A route definition is a JavaScript object with two required propteries. The first property, `path`, is a string
> A route definition is a JavaScript object with two required propteries.

Well, these are not the only properties and they are not required :grin:
(See [here][1].)

[1]: https://angular.io/api/router/Route

2020-04-24 20:39 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +```
I think we have decided to stanrdaze to `<code-example>` instead of triple backticks for code blocks.

2020-04-24 20:39 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +1. Open the `styles.css` file and add the following styles.
Did you mean `app.component.css`?

2020-04-24 20:39 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +automatically, identifying the active component to the user.
I think we should explain how this works. The `routerLinkActive` directive adds the specified class to the `routerLink` that corresponds to the active route. So, the user must define the style for the `.active` element themselves. I think it is worth mentioning that, because otherwise the users might not realize what is going on (and how to adapt ithis to their needs).

2020-04-24 20:39 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +Currently, your `pagenotfound` component displays even when the user first opens the application.
The `pagenotfound` component is introduced in the next section :grin:

2020-04-24 20:39 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +   ng generate component PageNotFound
This command will generate a `PageNotFoundComponent` in `page-not-found.component.*` (instead of `PagenotfoundComponent` in `pagenotfound.component.*`).

<sub>Personally, I prefer what this command generates - I am just pointing out that the command should match the files.</sub>

2020-04-24 20:39 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +The next section address this.
```suggestion
The previous section addresses this.
```

😛

2020-04-24 20:39 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +a custom 404 page.
> You have extended these features to account for unexpected or undefined routes, and you've added a wildcard route to display a custom 404 page.

Aren't these two the same thing (accounting for undefined routes and adding a wildcard route)?

2020-04-28 00:13 UTC, aikithoughts reviewed
Thanks for the feedback!

2020-04-28 00:13 UTC, aikidave commented on aio/content/guide/router-tutorial.md
> +Currently, your `pagenotfound` component displays even when the user first opens the application.
Rewritten. Thank you!

2020-04-28 00:13 UTC, aikidave commented on aio/content/guide/router-tutorial.md
> +The next section address this.
Actually, the alert isn't needed any longer, so I removed it.

2020-04-28 00:13 UTC, aikidave commented on aio/tools/transforms/angular-content-package/index.js
> +        include: CONTENTS_PATH + '/{start,guide,tutorial,tutorials}/**/*.md',
Nope. Removed.

2020-04-28 18:06 UTC, mary-poppins commented
You can preview b85f91a at https://pr36545-b85f91a.ngbuilds.io/.

2020-04-28 20:56 UTC, kapunahelewong approved these changes
Well done!! 🎉Just a few small suggestions.

2020-04-28 20:56 UTC, kapunahelewong commented on aio/content/examples/router-tutorial/src/app/app.component.html
> +  <a class="button" routerLink="/crisis-list" routerLinkActive="activebutton">Crisis Center</a> |
Could we use a `button` element here instead of an `<a>` tag? That way it will be semantic in that you won't be styling an `<a>` tag with a button class and better for accessibility. (If you change it it will affect your e2e tests and css. Same note for lines 25 and 26.)

2020-04-28 20:56 UTC, kapunahelewong commented on aio/content/examples/router-tutorial/src/app/app.component.css
> +    font-size:15px;
Could we use rems instead of pixels for the font size? It makes it a little more flexible for accessibility.

2020-04-28 20:56 UTC, kapunahelewong commented on aio/content/guide/router-tutorial.md
> +   * `pathMatch`. This property instructs Angular to how much of the URL to match. For this
```suggestion
   * `pathMatch`. This property instructs Angular how much of the URL to match. For this
```
Or maybe you meant "on how much"?

2020-04-29 15:54 UTC, aikithoughts reviewed
Thanks for the feedback!

2020-04-29 15:54 UTC, aikidave commented on aio/content/guide/router-tutorial.md
> +guard against unexpected or unauthorized behavior.
I'm all for avoiding the word "use."

2020-04-29 15:54 UTC, aikidave commented on aio/content/guide/router-tutorial.md
> +   * `pathMatch`. This property instructs Angular to how much of the URL to match. For this
I meant "on." Thanks!

2020-04-29 16:04 UTC, mary-poppins commented
You can preview ae73eea at https://pr36545-ae73eea.ngbuilds.io/.

2020-04-29 17:06 UTC, aikidave commented on aio/content/examples/router-tutorial/src/app/app.component.html
> +  <a class="button" routerLink="/crisis-list" routerLinkActive="activebutton">Crisis Center</a> |
George specifically asked me to **not** use a button tag.

2020-04-29 17:08 UTC, aikidave commented on aio/content/examples/router-tutorial/src/app/app.component.css
> +    font-size:15px;
I'd prefer to handle this in a separate PR; one in which we can look at the rest of the example code.

2020-04-29 17:09 UTC, aikidave commented
@kapunahelewong @gkalpak please review! Thanks for the feedback!

2020-04-29 18:30 UTC, mary-poppins commented
You can preview c45f14e at https://pr36545-c45f14e.ngbuilds.io/.

2020-04-29 18:44 UTC, gkalpak commented on aio/content/examples/router-tutorial/stackblitz.json
> +    "!src/app/hero-list/*.*"
That might be valid for that example app, but is not valid for this one. Please remove these two lines.

2020-04-29 18:45 UTC, gkalpak commented on aio/content/examples/router-tutorial/stackblitz.json
> +    "!src/app/hero-list/*.*"
You can also try out the live example on the preview and verify that it works correctly.

2020-04-29 19:09 UTC, gkalpak commented on aio/content/examples/router-tutorial/stackblitz.json
> +    "!src/app/hero-list/*.*"
Actually, I just realized you do not include a live or downloadable example in the tutorial. Is that intentional (and if so why)?

2020-04-29 19:09 UTC, aikidave commented
I didn't know that the live example would work automatically! That's awesome. @gkalpak, thanks for the feedback!

2020-04-29 19:18 UTC, mary-poppins commented
You can preview 2e85169 at https://pr36545-2e85169.ngbuilds.io/.

2020-04-29 19:54 UTC, gkalpak requested changes
Regarding per-example styles (https://github.com/angular/angular/pull/36545#discussion_r416143288 - for some reasons, GitHub won't let me comment there):

1. It would be better to have consistent styles in all examples (for common elements, such as buttons, text fields, etc.). This makes it easier for users to focus on what's important when looking at multiple examples and makes it easier for us to update the styles.

2. It's OK to have extra styles per example for things that are not common (such as active `routeLink`s).

3. Either way, users will be able to copy the styles into their project

All in all, not a big deal (and it doesn't have to block this PR), but it is a good idea imo to try to standardize common styles across examples.

2020-04-29 19:54 UTC, gkalpak commented on aio/content/examples/router-tutorial/src/app/app.component.html
> +  <a class="button"  routerLink="/heroes-list">Heroes</a>
```suggestion
  <a class="button" routerLink="/heroes-list">Heroes</a>
```

2020-04-29 19:54 UTC, gkalpak commented on aio/content/examples/router-tutorial/e2e/src/app.e2e-spec.ts
> +    });
```suggestion
    browser.get('/fake-page');
```

2020-04-29 19:54 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +<code-example language="sh">
These are not shell commands. So, they should have no language attribute or have `language="none"`.

2020-04-29 19:54 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +1. Open the `app.component.styles.css` file and add the following styles.
```suggestion
1. Open the `app.component.css` file and add the following styles.
```

2020-04-29 19:54 UTC, gkalpak commented on aio/content/guide/router-tutorial.md
> +   <code-example header="src/app/pagenotfound/page-not-found.component.html" path="router-tutorial/src/app/page-not-found/page-not-found.component.html"></code-example>
```suggestion
   <code-example header="src/app/page-not-found/page-not-found.component.html" path="router-tutorial/src/app/page-not-found/page-not-found.component.html"></code-example>
```

2020-04-29 19:54 UTC, gkalpak commented on aio/content/examples/router-tutorial/src/app/app.component.css
> +    box-shadow:inset 0px 1px 0px 0px #ffffff;
Nit: Please leave a space after the `:`

2020-04-29 19:59 UTC, aikidave commented on aio/content/examples/router-tutorial/stackblitz.json
> +    "!src/app/hero-list/*.*"
Because no one told me that the examples were dynamically loaded. I have fixed this--the example is now available.

2020-04-29 19:59 UTC, mary-poppins commented
You can preview f8eb48b at https://pr36545-f8eb48b.ngbuilds.io/.

2020-04-29 20:14 UTC, mary-poppins commented
You can preview b0aa0cc at https://pr36545-b0aa0cc.ngbuilds.io/.

2020-04-30 12:13 UTC, gkalpak commented on aio/content/examples/router-tutorial/stackblitz.json
> +    "!src/app/hero-list/*.*"
You might want to read the [Angular documentation style guide][1] (if you haven't already) 😛
Especially the [Live examples][2] section :wink:

[1]: https://angular.io/guide/docs-style-guide
[2]: https://angular.io/guide/docs-style-guide#live-examples

2020-04-30 12:23 UTC, gkalpak approved these changes
LGTM ✨
Nice work getting the code examples and tests in 😍

One last thing:
As mentioned in the [failing lint job][1], you need to assign code-owners for the newly added files in the [PullApprove config][2]:

```diff
   # =========================================================
   #  Framework: Router
   # =========================================================
   fw-router:
     conditions:
       - *can-be-global-approved
       - *can-be-global-docs-approved
       - >
         contains_any_globs(files, [
           'packages/router/**',
           'packages/examples/router/**',
           'aio/content/guide/router.md',
           'aio/content/examples/router/**',
-          'aio/content/images/guide/router/**'
+          'aio/content/images/guide/router/**',
+          'aio/content/guide/router-tutorial.md',
+          'aio/content/examples/router-tutorial/**'
           ])
     reviewers:
       users:
         - atscott
```

[1]: https://circleci.com/gh/angular/angular/695429
[2]: https://github.com/angular/angular/blob/17865867478aa8234a40e83983e0eba17ddd0981/.pullapprove.yml#L485-L502

2020-04-30 16:55 UTC, mary-poppins commented
You can preview 536b4cc at https://pr36545-536b4cc.ngbuilds.io/.

2020-04-30 18:28 UTC, IgorMinar commented on .pullapprove.yml
> +          'aio/content/guide/router-tutorial.md',
have we considered slightly different structure: instead of `/guide/router-tutorial` create `/tutorials/router-tutorial` ?

We seem to be heading in a direction where we have multiple tutorials so it would be great to group them under the existing "tutorials" category which we currently honor only in the search results:

<img width="1495" alt="Screen Shot 2020-04-30 at 11 26 50 AM" src="https://user-images.githubusercontent.com/216296/80745774-a76fa380-8ad5-11ea-8277-3b993dcf276e.png">

2020-04-30 19:24 UTC, aikidave commented on .pullapprove.yml
> +          'aio/content/guide/router-tutorial.md',
I think this is a good idea to consider, but I'd like to discuss it with docs-infra folks--I'm never sure the full impact of such changes.

I'll file an issue if you want!

2020-04-30 19:39 UTC, gkalpak commented on .pullapprove.yml
> +          'aio/content/guide/router-tutorial.md',
If we are going to do that, I would rather do it before mergin this, because the URL might change and we would have to have a redirect 😞

2020-04-30 21:08 UTC, mary-poppins commented
You can preview 0fa2606 at https://pr36545-0fa2606.ngbuilds.io/.

2020-04-30 23:11 UTC, aikidave commented on .pullapprove.yml
> +          'aio/content/guide/router-tutorial.md',
I tried to create a new directory, and everything started to crash, because it's not entirely clear (to me) how to create a new folder in Angular.io. Could someone provide clear steps that I should follow? I'll then update the PR.

2020-05-01 16:18 UTC, aikidave commented on .pullapprove.yml
> +          'aio/content/guide/router-tutorial.md',
I think we should handle moving the directory structure around for a separate PR. The more I research changing the directory structure, the more complicated it becomes.  I agree that redirects do have a maintenance cost, but not an indefinite one.

2020-05-01 19:22 UTC, IgorMinar commented on .pullapprove.yml
> +          'aio/content/guide/router-tutorial.md',
I discussed this with Dave and we agreed on a compromise to get this in as is and kick off another project to add "tutorials/"-like top level category to angular.io + move all the existing tutorials there + setup redirects.

We have more tutorials like this coming, but we don't want to block the release of this particular tutorial on resolving the infra issues associated with proper restructuring. At this point the future cost of one more redirect is acceptable considering the cost of not merging this PR now.

2020-05-01 19:23 UTC, IgorMinar approved these changes
LGTM! Thank you! Please see https://github.com/angular/angular/pull/36545#discussion_r418697106 for justification.

Reviewed-for: global-approvers

2020-05-01 19:53 UTC, mary-poppins commented
You can preview 1633216 at https://pr36545-1633216.ngbuilds.io/.

2020-05-04 19:42 UTC, alxhub commented
@aikidave, this PR doesn't apply cleanly to the patch branch, so it can't be merged yet.

The way forward is:
- make the PR `master-only`
- (optional) open a separate `patch-only` PR, if the PR needs to also be on the patch branch. Given that v10 is right around the corner, maybe this isn't the case?

2020-05-05 15:25 UTC, mary-poppins commented
You can preview 43d75b7 at https://pr36545-43d75b7.ngbuilds.io/.

2020-05-05 18:51 UTC, closed without merging