fix(ngcc): recognize enum declarations emitted in JavaScript
angular/angular pull request #36550
Opened 2020-04-09 22:37 UTC by JoostK

_tbd_

Fixes #35584

2020-04-13 10:27 UTC, petebacondarwin requested changes
Only had time to check the ngcc source (and not the tests).

2020-04-13 10:27 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/host/esm2015_host.ts
> +    if (!ts.isCallExpression(iife)) return null;
I think we should check that the first argument to the call expression is the variable being declared, i.e. of the form `Enum || (Enum = {})`, where `Enum` is the name of the declared variable.

Otherwise there is a small chance that we get a false positive.

2020-04-13 10:27 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/host/esm2015_host.ts
> +        return null;
So if any of the statements in this function do not have the correct form, we bail out completely?
Is there a chance that there might be some innocuous additional statement in there? I guess it is unlikely.

2020-04-13 10:27 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/host/esm2015_host.ts
> +    if (!ts.isIdentifier(enumIdentifier) || enumIdentifier.text !== enumName.text) return null;
This block is basically repeated in `reflectEnumMemberAssignment()`.
If you pull this out into its own method, then it could be checked up front at the top of this method and that would avoid a) duplicating the code and b) running the code twice for numeric valued enums.

2020-04-13 10:27 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/host/esm2015_host.ts
> +}
This function already exists in `esm5_host.ts`, no?

2020-04-13 10:44 UTC, JoostK commented on packages/compiler-cli/ngcc/src/host/esm2015_host.ts
> +    if (!ts.isCallExpression(iife)) return null;
I did initially check for it, but decided to remove it. The UMD/CJS formats use `exports.Enum || (exports.Enum = {})` so there's slight variations that we'd need to account for.

2020-04-13 10:45 UTC, JoostK commented on packages/compiler-cli/ngcc/src/host/esm2015_host.ts
> +        return null;
I honestly don't know whether there's a possibility of innocuous statements. In the spirit of preventing false positives I decided to bail when there's an unrecognized statement.

2020-04-13 10:50 UTC, JoostK commented on packages/compiler-cli/ngcc/src/host/esm2015_host.ts
> +    if (!ts.isIdentifier(enumIdentifier) || enumIdentifier.text !== enumName.text) return null;
Yes, this check is the same as in `reflectEnumMemberAssignment` but it checks a different identifier.

Given `Enum[Enum["ValueA"] = 0] = "ValueA"`, this check verifies the outer `Enum` whereas `reflectEnumMemberAssignment` check verifies the inner `Enum` identifier. Or are you suggesting that the outer identifier check already occurs within the first call to `reflectEnumMemberAssignment`, such that we don't have to repeat it? If we were to do that, I think we'd need to know why the first invocation of `reflectEnumMemberAssignment` failed to match.

2020-04-13 10:51 UTC, JoostK commented on packages/compiler-cli/ngcc/src/host/esm2015_host.ts
> +}
It does! Perhaps now is the time to pull it out into a `ast_utils.ts` file.

2020-04-13 11:18 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/host/esm2015_host.ts
> +    if (!ts.isIdentifier(enumIdentifier) || enumIdentifier.text !== enumName.text) return null;
Looks like it is checking the exact same `expression` to me...

2020-04-13 11:18 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/host/esm2015_host.ts
> +    if (!ts.isIdentifier(enumIdentifier) || enumIdentifier.text !== enumName.text) return null;
I would imagine we would do something like:

```
if not `expression` matches enum name
  return null
if `x` of `Enum[x]` is a string
  return processed RHS
if not `x` of `Enum[x]` is a binary expression
  return null
if not `x` matches enum name
  return null
return processed x RHS
```

2020-04-16 20:22 UTC, petebacondarwin approved these changes
Marvellous - much easier to understand. Even at the end of the day!

2020-04-16 20:22 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/host/esm2015_host.ts
> +    // Check for the `Enum["ValueA"] = "a";` case.
```suggestion
    // Check for `Enum[...] = "...";`
```

2020-04-17 22:53 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/reflection/src/host.ts
> +   * stored here. This will be null for declarations of type `ts.EnumDeclaration`, where
This comment is incomplete!

The weirdness of this situation (that a real `ts.EnumDeclaration` doesn't need to be represented in this way) is a bit funny.

I think we should refine the way we represent this a little bit to make this a little less weird. Instead of `enumMembers` directly on `ConcreteDeclaration`, we can introduce a new `SpecialDeclarationIdentity` type with a `kind` enum. There will be one possible value (`SpecialEnum` maybe?) with `enumMembers: EnumMember[]`.

I think this approach will make it a lot more clear in the model that this is _one_ way of representing enums, but not the only way.

Alternatively, we could introduce a true `EnumDeclaration` subtype of `ConcreteDeclaration`, with `members` that may or may not have initializers, and reflect _all_ enums (whether from JS or `ts.EnumDeclaration`) that way. This is most in line with the spirit of the `ReflectionHost`, but might be too heavy-handed for this particular challenge.

2020-04-28 17:48 UTC, alxhub approved these changes
👍 this looks awesome

2020-04-28 17:55 UTC, alxhub commented
[Presubmit](http://test/OCL:308854806:BASE:308854843:1588096471736:89d90dec)

2020-04-28 19:47 UTC, alxhub approved these changes

2020-04-28 19:47 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
> +    } else if (decl.node !== null) {
Ahh, I think we should refactor this a bit. In general these "trap" `if` statements scare me.

What happens here is that this branch becomes true if `decl.node !== null`, even though the full case we intended to check here is really that and `decl.identity !== null`. This means that no other branches of the outer `if` will be checked even if `identity` IS null.

Instead, let's create a type guard function `isConcreteDeclaration` and use that to write the full condition in the outer `if` directly.

2020-04-28 21:50 UTC, AndrewKushnir commented
@JoostK @alxhub it looks like a lot of targets in g3 presubmit failed with the following error:
```
packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts:229:36 - error TS2339: Property 'identity' does not exist on type 'Declaration<Declaration>'.
  Property 'identity' does not exist on type 'InlineDeclaration'.

229         decl.node !== null && decl.identity !== null &&
                                       ~~~~~~~~
packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts:230:14 - error TS2339: Property 'identity' does not exist on type 'Declaration<Declaration>'.
  Property 'identity' does not exist on type 'InlineDeclaration'.

230         decl.identity.kind === SpecialDeclarationKind.DownleveledEnum) {
                 ~~~~~~~~
packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts:231:51 - error TS2339: Property 'identity' does not exist on type 'Declaration<Declaration>'.
  Property 'identity' does not exist on type 'InlineDeclaration'.

231       return this.getResolvedEnum(decl.node, decl.identity.enumMembers, context);
                                                      ~~~~~~~~             
```
Could you please have a look at this issue when you get a chance?

(I will remove the "merge" label for now)

2020-04-28 21:52 UTC, JoostK commented
@AndrewKushnir Thanks Andrew, we spotted the same. The problem should have been fixed already, but it does need a new presubmit.

2020-04-28 21:56 UTC, AndrewKushnir commented
@JoostK got it, thanks! I've started a new [g3 presubmit](http://test/OCL:308903090:BASE:308903122:1588110947139:aa840389) and will let you know.

2020-04-28 23:00 UTC, closed without merging