docs: place download section in architecture to the top
angular/angular pull request #36565
Opened 2020-04-10 16:19 UTC by ajitsinghkaler

link is very deep down on architecture page this commit is part of a larger effort to standardise ownload sections on angular.io

This commit partially addresses #35459

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

No standard way of downloading docs exampes

Issue Number: #35459

## What is the new behavior?
The standard way of downloading docs examples

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-04-17 16:44 UTC, ajitsinghkaler commented
@AndrewKushnir @kapunahelewong can you please have a look

2020-04-17 18:51 UTC, AndrewKushnir reviewed
Hi @ajitsinghkaler, this change looks good from engineering standpoint, but I've added @kapunahelewong to also have a look at it from docs perspective (for content, consistency with other pages, etc). Thank you.

2020-04-20 18:40 UTC, mary-poppins commented
You can preview f3b1acd at https://pr36565-f3b1acd.ngbuilds.io/.

2020-04-20 19:31 UTC, kapunahelewong requested changes
Thank you very much, @ajitsinghkaler! Just one thing I noticed in the preview. I'm not sure why it's breaking, but I'm guessing it's formatting.

2020-04-20 19:31 UTC, kapunahelewong commented on aio/content/guide/architecture.md
> +</div>
I think this is breaking the alert about the glossary. Maybe it's the spacing? You could try adding a space before the closing `</div>`. 

Preview link:
https://pr36565-f3b1acd.ngbuilds.io/guide/architecture

2020-04-20 20:02 UTC, gkalpak commented on aio/content/guide/architecture.md
> +</div>
The problem is in the previous alert:

```diff
-<div class="alert is-helpful>
+<div class="alert is-helpful">
```

This has already been fixed with #36564 (but this PR is not rebased on master).

2020-04-21 01:06 UTC, ajitsinghkaler commented
@kapunahelewong rebased the branch can you please have a look

2020-04-21 01:14 UTC, mary-poppins commented
You can preview 3debc60 at https://pr36565-3debc60.ngbuilds.io/.

2020-04-21 15:06 UTC, kapunahelewong commented on aio/content/guide/architecture.md
> +</div>
Thank you, @gkalpak!

2020-04-21 15:08 UTC, kapunahelewong approved these changes
Reviewed-for: global-docs-approvers

2020-04-21 16:50 UTC, closed without merging