fix(router): lazy loaded modules without RouterModule.forChild() won't cause infinite loop
angular/angular pull request #36605
Opened 2020-04-13 09:52 UTC by martinsik

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #29164

When loading a module that doesn't provide `RouterModule.forChild()` preloader will get stuck in a infinite loop and throw `ERROR
Error: Maximum call stack size exceeded`.

https://stackblitz.com/edit/angular-issue-repro2-atwzck?file=src%2Fapp%2Ffeature1%2Ffeature1.module.ts

The issue is that child module's `Injector` will look to its parent `Injector` when it doesn't find any `ROUTES` so it will return routes for it's parent module instead. This will load the child again that returns its parent's routes and so on.

## What is the new behavior?

Lazy loaded modules without `RouterModule.forChild()` won't break the app.

I was thinking that this might throw an exception telling me that I'm lazy loading a module that doesn't define any routes but maybe it is a valid use-case (for example I'm loading a module that only does some logic in its constructor).

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I only changed one line and added one test that would fail with `Error: 1 timer(s) still in the queue.` without this change:

https://github.com/angular/angular/compare/master...martinsik:issue-29164?expand=1#diff-2a29f955e9e56e86ee957a9768a19929R44

All other changes were made by running `yarn gulp format`

Closes #29164

2020-04-13 19:58 UTC, atscott commented
Hi @martinsik, thanks for another router fix! Can you update the commit message to match what you have in the "current behavior" section (without the stackblitz link) and also add a similar comment to the  `LoadedRouterConfig` line that you changed to describe why `InjectFlags.Self` is required (again, pretty much exactly what you have in the current behavior section)?

2020-04-13 20:03 UTC, atscott commented
[presubmit](http://test/OCL:306291989:BASE:306292029:1586808011055:74e2121)

2020-04-21 10:24 UTC, martinsik commented
Commit message updated.

2020-04-27 14:54 UTC, atscott commented
Presubmit is showing internal test failures when running with Ivy. Needs more investigation.

2020-07-09 08:49 UTC, martinsik commented
@atscott Hey, pls do you have any update on this :)?

2020-07-09 20:03 UTC, atscott requested changes

2021-01-13 09:35 UTC, martinsik commented
@atscott Hi, I addressed what you mentioned above and also added the test you made into `integration.spec.ts`.

2021-01-13 22:31 UTC, atscott approved these changes

2021-01-13 22:31 UTC, atscott commented on packages/router/test/router_preloader.spec.ts
> +              // {path: 'lazy1', loadChildren: 'expected1'},
```suggestion
```

2021-01-13 22:31 UTC, atscott commented on packages/router/test/router_preloader.spec.ts
> +                 loader.stubbedModules = {/*expected1: LoadedModule,*/ expected2: EmptyModule};
```suggestion
                 loader.stubbedModules = {expected2: EmptyModule};
```

2021-01-13 23:46 UTC, atscott commented
[global presbumit](https://test.corp.google.com/ui#id=OCL:351670318:BASE:351657287:1610581516586:76468f97)

2021-01-15 17:34 UTC, atscott commented
caretaker note: just to be safe, let's merge and sync this one on its own. I don't _anticipate_ issues as a result of this fix, but you never know.

2021-01-15 18:40 UTC, closed without merging