WIP - fix(ngcc): do not fail if a worker process crashes in parallel mode
angular/angular pull request #36626
Opened 2020-04-14 17:43 UTC by gkalpak

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-04-14 17:54 UTC, mary-poppins commented
You can preview cc6daf8 at https://pr36626-cc6daf8.ngbuilds.io/.

2020-04-15 10:39 UTC, mary-poppins commented
You can preview 8f92a83 at https://pr36626-8f92a83.ngbuilds.io/.

2020-04-15 14:01 UTC, mary-poppins commented
You can preview ed19d80 at https://pr36626-ed19d80.ngbuilds.io/.

2020-04-15 14:36 UTC, mary-poppins commented
You can preview 8335429 at https://pr36626-8335429.ngbuilds.io/.

2020-04-15 16:28 UTC, mary-poppins commented
You can preview 777cf8f at https://pr36626-777cf8f.ngbuilds.io/.

2020-04-20 20:33 UTC, mary-poppins commented
You can preview 17b4fac at https://pr36626-17b4fac.ngbuilds.io/.

2020-04-22 17:31 UTC, mary-poppins commented
You can preview 1f3257b at https://pr36626-1f3257b.ngbuilds.io/.

2020-04-22 20:34 UTC, mary-poppins commented
You can preview 03e74f2 at https://pr36626-03e74f2.ngbuilds.io/.

2020-04-23 07:46 UTC, petebacondarwin commented
One can argue that none of these commits are "feat" since they don't actually offer any new features to the end-user. Instead they are parts of a reorganisation (refactor) of the ngcc internal implementation to "fix" the problem of a lack of resilience to workers being killed.

(And features can't be cherry picked to stable).

2020-04-23 08:45 UTC, petebacondarwin commented
typo in `fix(ngcc): give up re-spawing crashed worker process after 3 attempts`:

spawing -> spawning

2020-04-23 09:43 UTC, petebacondarwin requested changes
Great PR @gkalpak - the commits are really clean and easy to follow.
There are a bunch of nits but the two main things I think we should address are:

1) How to revert the `copyBundle()` action in the `NewEntryPointFileWriter`
  One could argue that we don't need to bother reverting these files since they will be overwritten automatically when the task is re-run. But perhaps we ought to be explicit about this in the code in case something changes in who `writeBundle()` works.

2) What happens if the process dies after sending `update-package-json` but before sending `task-completed`.
  I think we will need a way to undo the changes to `package.json` in this case. Alternatively we could defer actually writing to package.json until the `task-completed` message arrives.

2020-04-23 09:43 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/writing/in_place_file_writer_spec.ts
> +      it('should only revert the written file if there is no backup', () => {
This test description is a bit misleading, since we do revert the file (to nothing). The implication of not reverting would be to leave the file untouched, which is not what happens. Perhaps instead it should be something like:

```suggestion
      it('should just remove the written file if there is no backup', () => {
```

2020-04-23 09:43 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/writing/new_entry_point_file_writer_spec.ts
> +      it('should revert a written JS file', () => {
```suggestion
      it('should remove non-typings files', () => {
```

2020-04-23 09:43 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.ts
> +
What about reverting all the files that are copied across in `copyBundle()`?

2020-04-23 09:43 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/cluster/worker.ts
> +        logger,
Good spot!

2020-04-23 09:43 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/main.ts
> +  // Create an updater that will actually write to disk.
👍

2020-04-24 20:48 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/tasks/queues/base_task_queue.ts
> +    this.tasks.unshift(task);
Exactly.

2020-04-24 21:26 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/cluster/worker.ts
> +          return process.exit(1);
Yes :grin:

2020-04-24 21:47 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/tasks/api.ts
> +  markTaskFailed(task: Task): void;
I don't feel strongly about it. Happy to go with `markAs*` (as long as the names are consistent :grin:).

2020-04-28 22:24 UTC, gkalpak commented
I added a bunch of fixup commits. PTAL.

As discussed "offline", we will not be reverting `copyBundle()` changes for now. (Added a comment to explain that.)
I also added code to revert the `updatePackageJson()` changes. For simplicity, because `updatePackageJson()` only adds properties (i.e. it does not modify existing ones), we can just remove the added properties (if they exist).

2020-04-28 22:28 UTC, mary-poppins commented
You can preview 7924a80 at https://pr36626-7924a80.ngbuilds.io/.

2020-04-29 06:53 UTC, petebacondarwin approved these changes

2020-04-29 06:53 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.ts
> +    // This way, we avoid the overhed of having to inform the master process about all source files
```suggestion
    // This way, we avoid the overhead of having to inform the master process about all source files
```

2020-04-29 10:05 UTC, mary-poppins commented
You can preview f1af402 at https://pr36626-f1af402.ngbuilds.io/.

2020-04-29 10:38 UTC, mary-poppins commented
You can preview 932a772 at https://pr36626-932a772.ngbuilds.io/.

2020-04-29 11:38 UTC, gkalpak commented
**merge-assistance:** The `size` check failure is unrelated to this PR. It looks like a CI/infrastructure issue.

2020-04-29 18:37 UTC, mary-poppins commented
You can preview 95b94b0 at https://pr36626-95b94b0.ngbuilds.io/.

2020-04-29 21:28 UTC, closed without merging