docs: add example to illustrate binding order differences in ivy
angular/angular pull request #36643
Opened 2020-04-15 19:06 UTC by crisbeto

Adds some examples and an explanation about the differences in binding order between Ivy and ViewEngine.

2020-04-16 21:29 UTC, ajitsinghkaler commented
We are working on the same thing  #36556 I'm closing my pull request in favour of this because it's more detailed than my documentation tell me if you found anything else

2020-04-16 23:20 UTC, kara requested changes
Thanks for picking this up! Some suggestions below.

2020-04-16 23:20 UTC, kara commented on aio/content/guide/ivy-compatibility-examples.md
> +In the ViewEngine runtime, input property bindings and regular data bindings were executed in different stages. This means that Angular would go through the template once and assign the `name` bindin
```suggestion
In the ViewEngine runtime, directive input bindings and element bindings were executed in different stages. Angular would process the template one full time to check directive inputs only (e.g. `[name]`), then process the whole template again to check element and text bindings only (e.g.`{{ myDir.name }}`). This meant that the `name` directive input would be checked before the `myDir.name` text binding despite their relative order in the template, which some users felt to be counterintuitive.
```

2020-04-16 23:20 UTC, kara commented on aio/content/guide/ivy-compatibility-examples.md
> +On the other hand, Ivy will go through the template once and process both the `myDir.name` and `name` bindings during the same pass. In practice, this means that the `myDir.name` binding will have `u
```suggestion
In contrast, Ivy processes the template in just one pass, so that bindings are checked in the same order that they are written in the template.   In this case, it means that the `myDir.name` binding will have be checked before the `name` input sets the property on the directive (and thus it will be `undefined`). Since the `myDir.name` property will be set by the time the next change detection pass runs, a change detection error is thrown.
```

2020-04-16 23:20 UTC, kara commented on aio/content/guide/ivy-compatibility-examples.md
> +To fix this problem, we recommend either getting the information for the binding from a different place (e.g. the `myName` property from our example) or to put the data binding after the directive ha
```suggestion
To fix this problem, we recommend either getting the information for the binding directly from the host component (e.g. the `myName` property from our example) or to move the data binding after the directive has been declared so that the initial value is available on the first pass.
```

2020-04-16 23:21 UTC, mary-poppins commented
You can preview 9bc4627 at https://pr36643-9bc4627.ngbuilds.io/.

2020-04-16 23:22 UTC, kara commented on aio/content/guide/ivy-compatibility-examples.md
> +Assuming that the value for `myName` is `Angular`, you should see an error that looks like `Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous v
Can we move the error down into its own code block? Hard to scan if it's inline:

```suggestion
Assuming that the value for `myName` is `Angular`, you should see an error that looks like 

```
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'Angular'`.
```

2020-04-17 04:49 UTC, mary-poppins commented
You can preview 28bd963 at https://pr36643-28bd963.ngbuilds.io/.

2020-04-17 04:59 UTC, crisbeto commented
The feedback has been addressed.

2020-04-17 05:31 UTC, kara approved these changes
Thanks for the updates. Just one more typo fix, and LGTM

2020-04-17 05:31 UTC, kara commented on aio/content/guide/ivy-compatibility-examples.md
> +In contrast, Ivy processes the template in just one pass, so that bindings are checked in the same order that they are written in the template.   In this case, it means that the `myDir.name` binding
### 
```suggestion
In contrast, Ivy processes the template in just one pass, so that bindings are checked in the same order that they are written in the template.  In this case, it means that the `myDir.name` binding will be checked before the `name` input sets the property on the directive (and thus it will be `undefined`). Since the `myDir.name` property will be set by the time the next change detection pass runs, a change detection error is thrown.
```

2020-04-17 06:01 UTC, mary-poppins commented
You can preview ec68719 at https://pr36643-ec68719.ngbuilds.io/.

2020-04-17 16:30 UTC, closed without merging

2020-04-17 16:30 UTC, matsko commented
@crisbeto this fails on patch. Please open up a new PR and target patch directly there.