docs: FormsModule and ReactiveForms modules....
angular/angular pull request #36658
Opened 2020-04-16 10:44 UTC by raja1203

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-04-16 15:32 UTC, aikidave commented
Hi @raja1203! Can you provide some more information about what you're trying to accomplish with this PR? Thanks!

2020-04-17 03:40 UTC, raja1203 commented
Hi,

Good day.

I am refreshing my knowledge on Angular. As a part of this exercise, I have
started building Shopping cart App. While creating forms, there is no where
it is mentioned that you need to include FormsModule and Reactive Forms
module in app.module.ts.

This is particularly important especially for those people who started
learning it for the first time. Due to my earlier knowledge , I have
included FormsModule. but still it didn't work . After checking in
Stackoverflow , I have included ReactiveForms Module also. Then it worked.

What I am trying to achieve is correction in content which will increase
completeness of the angular tutorial.
If you need any more clarification, please let me know.


Thanks and Regards

Rajasekhar




On Thu, Apr 16, 2020 at 9:02 PM David Shevitz <notifications@github.com>
wrote:

> Hi @raja1203 <https://github.com/raja1203>! Can you provide some more
> information about what you're trying to accomplish with this PR? Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/36658#issuecomment-614725959>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADTANWQC6RC3HD6EFIMPGFLRM4QIVANCNFSM4MJP5UGQ>
> .
>

2020-12-08 10:58 UTC, petebacondarwin requested changes
Thanks for this PR. Before it can be merged we need the CLA to be signed and also for you to address the following comments.

2020-12-08 10:58 UTC, petebacondarwin commented on aio/content/start/start-forms.md
> +First, in app.module.ts
```suggestion
First, in `app.module.ts`
```

2020-12-08 10:58 UTC, petebacondarwin commented on aio/content/start/start-forms.md
> +import FormsModule and ReactiveForms Module. Next register them under @NgModule. Code snippet.
```suggestion
import `FormsModule` and `ReactiveFormsModule`. Next register them under `@NgModule`. ```

Also the code snippet below should actually reference code in a real example. Something similar to:

```
<code-example header="src/app/app.module.ts" path="getting-started/src/app/app.module.ts" region="forms-module-imports"></code-example>
```

But that also requires changes to the example code itself to include the `import {FormsModule} from '@angular/forms';` line and also comments to define the region. So `aio/content/examples/getting-started/src/app/app.module.ts` would need to look like:

```
// #docregion forms-module-imports
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
// #enddocregion forms-module-imports
```

2021-01-25 22:23 UTC, jelbourn commented
Closing this since the CLA was never signed.

2021-01-25 22:23 UTC, closed without merging