Auto link code cleanup
angular/angular pull request #36686
Opened 2020-04-17 11:03 UTC by sonukapoor

This PR is based on https://github.com/angular/angular/pull/36316. It should be merged after that one is merged. 

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [X] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2020-04-17 11:04 UTC, sonukapoor commented
@gkalpak / @petebacondarwin Please take a look at this PR. I have refactored `autoLinkCode`. 🙏

2020-04-17 17:52 UTC, gkalpak requested changes
Nice 😍 Thx, @sonukapoor!

BTW, the commit message type should be `refactor` (not `style`).

2020-04-17 17:52 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +    return containsElement && hasNoAutoLink && isLanguageSupported && isInsideLink;
```suggestion
    const isCodeElement = autoLinkCodeImpl.codeElements.some(elementType => is(node, elementType));
    const hasNoAutoLink = node.properties.className && node.properties.className.includes('no-auto-link');
    const isLanguageSupported = !autoLinkCodeImpl.ignoredLanguages.includes(node.properties.language);
    const isInsideLink = ancestors.some(ancestor => is(ancestor, 'a'));
    return isCodeElement && !hasNoAutoLink && isLanguageSupported && !isInsideLink;
```

BTW, one problem (which is not terribly important here, I guess) with splitting this up into intermediate variables is that we lose the shortcircuiting capabilities of `&&`/`||`. I.e. now we will always traverse all ancestors even if this is not a code element.

Can you check whether this makes any difference in the time it takes to generate the docs?

2020-04-17 17:52 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +          if (!isInsideLink) {
```suggestion
          const isInsideLink = ancestors.some(ancestor => is(ancestor, 'a'));
          if (isInsideLink) {
```

BTW, since this same logic is used in `isValidCodeElement()`, you could extract it to a standalone function.

2020-04-17 17:52 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +      .filter(word => word.length)
While you are at it, let's do one more improvement:
The current implementation will also consider whitespace-only tokens. For example, `"foo bar"` will result into 3 words - "foo", " " and "bar". Looking for docs to match whitespace-only nodes is unnecessary. Let's fix it with:

```suggestion
      .filter(word => word.trim().length > 0)
```

2020-04-17 18:03 UTC, sonukapoor commented
Wow...Love your suggestions. Will make the changes 👍

2020-04-17 18:13 UTC, sonukapoor commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +    return containsElement && hasNoAutoLink && isLanguageSupported && isInsideLink;
When I ran the script I did not notice any significant delays. I could try to revert the code and use `console.time` to see how long it takes to generate the docs. Would that be sufficient?

2020-04-17 18:15 UTC, sonukapoor commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +    return containsElement && hasNoAutoLink && isLanguageSupported && isInsideLink;
We could always exit early? 

```typescript
const isCodeElement = ...
if (!isCodeElement) {
  return false;
}
const hasNoAutoLink = ...
```

2020-04-17 18:29 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +    return containsElement && hasNoAutoLink && isLanguageSupported && isInsideLink;
Let's see if this introduces any noticeable delay first.
Any way of timing it witl and without the change is fine.

2020-04-18 16:28 UTC, sonukapoor commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +          if (!isInsideLink) {
Is the proposed reverted logic line 40 correct? Exit out if we found a link? I thought the logic should run only for links. 😕

2020-04-18 16:31 UTC, sonukapoor commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +    return containsElement && hasNoAutoLink && isLanguageSupported && isInsideLink;
There is no significant delay. Before the change, it takes `63.63s` to run the whole process. After the change, it takes `51.22s.` I have run it a few times and don't see much difference. 

I am printing the times that the entire process takes. It does that automatically.

2020-04-18 18:27 UTC, sonukapoor commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +      .filter(word => word.length)
I tried that, but it seems we need the spaces. Without that, the code is converted to:
```typescript
abstractclassChangeDetectorRef {
  abstract markForCheck(): voidabstract detach(): voidabstract detectChanges(): voidabstract checkNoChanges(): voidabstract reattach(): void
}
```
vs

```typescript
abstract class ChangeDetectorRef {
  abstract markForCheck(): void
  abstract detach(): void
  abstract detectChanges(): void
  abstract checkNoChanges(): void
  abstract reattach(): void
}
```

2020-04-20 18:50 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +    return containsElement && hasNoAutoLink && isLanguageSupported && isInsideLink;
OK, if it doesn't make any difference, let's keep it as is.
It is strange though that it takes less time with the change. Where does the speed-up come from?

2020-04-20 18:52 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +          if (!isInsideLink) {
This post-processor generates links from code inside code-blocks. We do not want to generate any links inside other links.

So, yes, the proposed change in my previous comment is correct.

2020-04-20 18:54 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +      .filter(word => word.length)
Did you try my proposed change exaclty? It is not possible for my changes to have changed the resulting HTML (since strings are immutable and we only use `.trim()` in `filter` (which is not mutating the array)).

2020-04-21 00:50 UTC, sonukapoor commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +      .filter(word => word.length)
I did. It's not working for me as expected.

2020-04-21 00:50 UTC, sonukapoor commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +          if (!isInsideLink) {
Sounds good

2020-04-21 00:55 UTC, sonukapoor commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +    return containsElement && hasNoAutoLink && isLanguageSupported && isInsideLink;
Not entirely sure TBH. I see that the times are very random. Sometimes it takes `40`s, and sometimes `60`s. Either way, I do not see much difference, after running it a few times.

2020-04-21 12:15 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +    return containsElement && hasNoAutoLink && isLanguageSupported && isInsideLink;
:+1:

2020-04-21 12:30 UTC, gkalpak approved these changes
LGTM ✨
Thx for following through, @sonukapoor!

2020-04-21 12:30 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +          const isInsideOtherLinks = isInsideLink(ancestors);
```suggestion
          const isInsideOtherLink = isInsideLink(ancestors);
```

...or (to be consistent with the other call below):

```suggestion
          const isInLink = isInsideLink(ancestors);
```

2020-04-21 12:30 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +      .filter(word => word.length)
Oh, I see - I didn't realize we are using these nodes to replace the original code element. We need the whitespace then, yes.

Let's leave it as is then. Thx for trying it out and sorry for the noise 😅

2020-04-21 12:40 UTC, sonukapoor commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +          const isInsideOtherLinks = isInsideLink(ancestors);
Done: https://github.com/angular/angular/pull/36686/commits/47df12e967998944ee4fb8f2515dd3d3c2c5caa3

2020-04-21 16:50 UTC, closed without merging