feat(http): http requests to implement xhr timeout
angular/angular pull request #36681
Opened 2020-04-17 04:10 UTC by daftfox

Http client allows an optional timeout option to be passed.
An error will be emitted when no response is received within the allotted interval.
This reflects XMLHttpRequest behaviour that is standard in all modern browsers.
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout

This is behaviour that has been available for 'regular' js xhr requests, but has
not yet been implemented in Angular. Alternatives such as interceptors, RxJS
or custom client implementation don't offer the same behaviour in a neat package.

I have noticed that a lot of pre-existing code was modified by the formatter,
but I hope this doesn't rustle any jimmies.

fixes #34421

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The HttpClient does not allow developers to pass in a timeout option.

Issue Number: #34421

## What is the new behavior?
A timeout option can be passed when creating an Http request. When no response has been received before the time runs out, the observer's error method is called.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Docs and tests have been added or updated where applicable. In addition, the payload-size limit for the aio main-es2015.js has been increased by 150 bytes to allow for the slight increase in size that happened due to the newly added feature.

2020-04-20 23:27 UTC, daftfox commented
Would anyone be able to review this PR?

2020-04-21 14:11 UTC, gkalpak requested changes
Thx for updating the docs too 😍
A minor comments - otherwise lgtm ✨

2020-04-21 14:11 UTC, gkalpak commented on packages/common/http/src/xhr.ts
> +          statusText: 'Request timeout',
Why not `xhr.statusText || 'Request timeout'` (just in case)?

2020-04-21 14:11 UTC, gkalpak commented on aio/content/guide/http.md
> +* The server took too long to respond. The timeout can be passed in as an optional parameter with the request object or the `HttpClient`'s request methods.
Maybe it is worth mentioning that this can only happen if you specified a timeout.

2020-04-21 14:11 UTC, gkalpak commented on aio/content/examples/http/src/app/config/config.service.ts
> +    };
I don't think piggy-backing on the error-handling code-snippet to through options/timeout in the mix is a good idea. I suggest creating a new method that adds the options and a new section in the guide.

2020-04-21 21:37 UTC, daftfox commented on packages/common/http/test/xhr_mock.ts
> +  addEventListener(event: 'error'|'load'|'timeout'|'progress'|'uploadProgress', handler: Function):
Good catch! I hadn't noticed that they were in alphabetical order. I'll push your suggestions through right away.

2020-04-21 21:39 UTC, daftfox commented on packages/common/http/test/xhr_mock.ts
> +        {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: 'timeout'};
You're right. It doesn't make much sense to have it there.

2020-04-21 21:40 UTC, daftfox commented on packages/common/http/src/xhr.ts
> +          statusText: 'Request timeout',
We could do this indeed to make sure nothing breaks when the powers that be decide to change the XHR specs.

2020-04-21 21:57 UTC, daftfox commented on aio/content/examples/http/src/app/config/config.service.ts
> +    };
I'll add a new `getConfig_` method, but I think I will keep the `errorHandler` as it is since it makes sense to fit these cases together in one handler method.

2020-06-16 17:04 UTC, gkalpak approved these changes
One suggestion. Otherwise lgtm :+1:
BTW, please squash the commit into one (or create [fixup commits][1]).

[1]: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---fixupltcommitgt

2020-06-16 17:04 UTC, gkalpak commented on aio/content/examples/http/src/app/config/config.service.ts
> +    } else if (error.status === 0 && error.statusText === 'Request timeout') {
It is no longer certain that `error.statusText === 'Request timeout'`. How about `error.error instanceof ProgressEvent && error.status === 0`?

2020-06-17 03:14 UTC, jelbourn reviewed
Should there also be documentation on how to fake a request timeout for testing?

2020-06-17 03:14 UTC, jelbourn commented on aio/content/guide/http.md
> +* The server took too long to respond, but only when a timeout value has been passed in as an optional parameter with the request object or the `HttpClient`'s request methods.
Perhaps more concise: 
```suggestion
* The server took too long to respond. This can occur only when the request specifies an explicit `timeout`.
```

2020-06-17 03:14 UTC, jelbourn commented on packages/common/http/src/request.ts
> +    timeout?: number,
@gkalpak perhaps out of scope for this PR, but would it make sense to extract this options object into its own type? The repetition seems unfortunate.

2020-06-17 03:14 UTC, jelbourn commented on packages/common/http/src/request.ts
> +      if (!!options.timeout) {
Using `!!` is unnecessary in conditionals since it will always evaluate to the same thing as normal truthiness.

2020-06-17 03:14 UTC, jelbourn commented on packages/common/http/src/xhr.ts
> +      if (req.timeout) {
What happens if `xhr.timeout` is set to `null`, `undefined`, or zero?

2020-06-17 03:14 UTC, jelbourn commented on packages/common/http/src/xhr.ts
> +      const onTimeout = (error: ProgressEvent) => {
@gkalpak I'm wondering if creating this function for every request will allocate an additional amount of memory that we care about. Would it make a meaningful difference to only define `onTimeout` when `req.timeout` is set?

2020-06-17 13:07 UTC, gkalpak commented on packages/common/http/src/request.ts
> +    timeout?: number,
:+1:

2020-06-17 13:14 UTC, gkalpak commented on packages/common/http/src/xhr.ts
> +      const onTimeout = (error: ProgressEvent) => {
I doubt it will matter in the grand scheme of things, but it definitely wouldn't hurt to only define `onTimeout` if needed.
Same goes for `onDownProgress` and `onUpProgress`.

2021-01-28 13:02 UTC, petebacondarwin commented
@daftfox - sorry this PR has been around for a while. Could you respond to @jelbourn's questions and rebase (resolving the conflicts)?

2021-01-29 22:31 UTC, daftfox commented
> @daftfox - sorry this PR has been around for a while. Could you respond to @jelbourn's questions and rebase (resolving the conflicts)?

Howdy, it's been a while indeed. Will look into resolving the conflicts and answering aforementioned questions at my earliest convenience. Probably 1 Feb. Thanks for the message.

2021-04-17 12:37 UTC, petebacondarwin commented
Hi @daftfox - did you manage to find some time to update this PR?

2021-07-07 09:24 UTC, daftfox commented
Hey @petebacondarwin. Sorry, it has been a while.
I have rebased my changes on top of master.

2021-07-08 06:56 UTC, hamedtayeban commented
cd5e4b4d7101d3b7ce6905d45688fe5666b2eb10

2021-08-13 07:47 UTC, petebacondarwin commented
Looks like there is a legitimate compilation error:

```
packages/common/http/test/xhr_mock.ts:58:5 - error TS2300: Duplicate identifier 'timeout'.

58     timeout?: (event: ErrorEvent) => void,
       ~~~~~~~
packages/common/http/test/xhr_mock.ts:62:5 - error TS2300: Duplicate identifier 'timeout'.

62     timeout?: (event: ProgressEvent) => void,
       ~~~~~~~
packages/common/http/test/xhr_mock.ts:62:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'timeout' must be of type '((event: ErrorEvent) => void) | undefined', but here has type '((event: ProgressEvent<EventTarget>) => void) | undefined'.

62     timeout?: (event: ProgressEvent) => void,
       ~~~~~~~

  packages/common/http/test/xhr_mock.ts:58:5
    58     timeout?: (event: ErrorEvent) => void,
           ~~~~~~~
    'timeout' was also declared here.
packages/common/http/test/xhr_mock.ts:126:3 - error TS2393: Duplicate function implementation.

126   mockTimeoutEvent(): void {
      ~~~~~~~~~~~~~~~~
packages/common/http/test/xhr_mock.ts:130:30 - error TS2345: Argument of type 'ProgressEvent<EventTarget>' is not assignable to parameter of type 'ErrorEvent'.
  Type 'ProgressEvent<EventTarget>' is missing the following properties from type 'ErrorEvent': colno, error, filename, lineno, message

130       this.listeners.timeout(mockProgressEvent as ProgressEvent);
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
packages/common/http/test/xhr_mock.ts:146:3 - error TS2393: Duplicate function implementation.

146   mockTimeoutEvent(error: any): void {
```

2021-09-15 13:55 UTC, petebacondarwin commented
@daftfox - are you able to clean up the failures and finish dealing with the comments on this PR?

2022-02-04 00:27 UTC, alxhub commented
(Closing due to no response)

2022-02-04 00:27 UTC, closed without merging

2022-02-04 18:35 UTC, terencehonles commented
I think I might be willing to pick this up if that's OK, not sure if there are any issues with that (it looks like the CLA has been signed). I can see what bandwidth I have to pick this up and open a new PR, but I would like to know if that would be OK. I've been watching this PR for a bit but was also waiting for a response and then was busy coming upon the end of the year.

2022-03-08 00:59 UTC, jessicajaniuk commented
@terencehonles Feel free to pick this up and create a new PR with the fixes addressed. We'd love to land it. If you could mention the related issue #34421 in the PR, that'd be great.