Migrate from gulp format to ng-dev format
angular/angular pull request #36726
Opened 2020-04-20 20:15 UTC by josephperrott

See individual commits for details

2020-04-21 08:13 UTC, devversion approved these changes
Nice work! Hopefully we can remove gulp soon. I added a few minor comments below.

2020-04-21 08:13 UTC, devversion commented on dev-infra/format/run-commands-parallel.ts
> +            if (!slots.reduce((a, b) => a || b)) {
```suggestion
            if (slots.every(active => !active)) {
```

2020-04-21 08:13 UTC, devversion commented on dev-infra/format/format.ts
> +const THREAD_LIMIT = 8;
Should we limit this on the number of available core's? Otherwise the tool might have bad performance

2020-04-21 08:13 UTC, devversion commented on dev-infra/format/format.ts
> +        if (code) {
Nit: Can we be more explicit what exit code we expect here? Using `code !== 0` would already help IMO (same for `checkFiles`)

2020-04-22 01:26 UTC, josephperrott commented
Caretaker Note:  This PR is ready for merge, but needs to be merged alongside an announcement to about the change.

___
Beginning with #36726 `gulp` is no longer used for running `clang-format` across the repo.  Instead this task is now performed using the `ng-dev` command.  The formatting enforced and performed is identical and does not result in any change to the source code of the repository.

This is being done to prevent OOM issues when using gulp to perform formatting of large changes.  Additionally, this introduces some measure of parallelization to the task speeding up the performance of the task.

As we no longer rely on `gulp` the `gulp` commands have been removed, if they are called a deprecation message will be returned.

Example usage changes:
`yarn gulp format:all:enforce` -> `yarn ng-dev format all --check`
`yarn gulp format` -> `yarn ng-dev format changed`

2020-04-22 08:08 UTC, devversion approved these changes
💯 Two final comments. Other than that, LGTM.

2020-04-22 08:08 UTC, devversion commented on dev-infra/format/format.ts
> +      files, THREAD_LIMIT, `${getFormatterBinary()} -i -style=file`, (file, code, _, stderr) => {
Isn't this running sequentially now? The `THREAD_LIMIT` has been updated to `1`. Also the comment above seems to be out-of-date now.

2020-04-22 08:08 UTC, devversion commented on dev-infra/tmpl-package.json
> +    "prompts": "<from-root>",
I think replacing `prompts` with `inquirer` here fixes CI.

2020-04-22 14:28 UTC, josephperrott commented on dev-infra/format/format.ts
> +      files, THREAD_LIMIT, `${getFormatterBinary()} -i -style=file`, (file, code, _, stderr) => {
I had put it to one to retest and get the numbers for my comment, forgot to put it bad.

2020-04-22 14:32 UTC, devversion commented on dev-infra/format/format.ts
> +      files, THREAD_LIMIT, `${getFormatterBinary()} -i -style=file`, (file, code, _, stderr) => {
Do you think we should always just run at maximum available cores? Even if it's more than 8?

2020-04-22 14:41 UTC, josephperrott commented on dev-infra/format/format.ts
> +      files, THREAD_LIMIT, `${getFormatterBinary()} -i -style=file`, (file, code, _, stderr) => {
I suppose we could, for some reason I felt like we shouldn't.  But I guess there isn't really a reason not to do that.

2020-04-22 21:48 UTC, gkalpak requested changes
Drive-by review :grin:

2020-04-22 21:48 UTC, gkalpak commented on .dev-infra.json
> +      "tools/public_api_guard/**/*.d.ts",
Did you mean:

```suggestion
      "!tools/gulp-tasks/cldr/extract.js",
      "!tools/public_api_guard/**/*.d.ts",
```

Otherwise, these two shouldn't be needed (they are covered by `tools/**/*.{js,ts}`).

2020-04-22 21:48 UTC, gkalpak commented on dev-infra/format/run-commands-parallel.ts
> +const AVAILABLE_THREADS = Math.min(cpus().length - 1, 1);
Did you mean:

```suggestion
const AVAILABLE_THREADS = Math.max(cpus().length - 1, 1);
```

:grin:

2020-04-22 21:48 UTC, gkalpak commented on dev-infra/format/run-commands-parallel.ts
> + * A promise is returned, completed when the command has completed runing for each file.
```suggestion
 * A promise is returned, completed when the command has completed running for each file.
```

2020-04-22 21:48 UTC, gkalpak commented on dev-infra/format/format.ts
> +const DEFAULT_MATCHERS = ['**/*.{t,j}s', '*.{t,j}s'];
Doesn't `**/*{t,j}s` include `*.{t,j}s`?

2020-04-22 21:48 UTC, gkalpak commented on dev-infra/format/format.ts
> +  // time from 276 seconds to 39 seconds for the same 2700 files
Have you checked whether this has a negative impact for less than 20 files (which is what we usually have on a PR)?

2020-04-22 21:48 UTC, gkalpak commented on dev-infra/format/format.ts
> +      process.exit(1);
Is this intentional? Shouldn't we only exit if `formatFailed` is false at the end?

2020-04-22 21:48 UTC, gkalpak commented on dev-infra/format/format.ts
> +  // Run the formatter to format the files in place, split across up to 8 processes.
This doesn't seem to be the case any more.

2020-04-22 21:48 UTC, gkalpak commented on dev-infra/format/format.ts
> +  // as running accross entire repositories takes a large amount of time.
```suggestion
  // as running across entire repositories takes a large amount of time.
```

2020-04-22 21:48 UTC, gkalpak commented on package.json
> +    "lint": "yarn -s tslint && yarn -s ng-dev format change --check",
```suggestion
    "lint": "yarn -s tslint && yarn -s ng-dev format changed --check",
```

???

2020-04-22 21:48 UTC, gkalpak commented on dev-infra/format/cli.ts
> +            let sha = shaOrRef || `master`;
Nit:

```suggestion
            const sha = shaOrRef || 'master';
```

2020-04-22 21:48 UTC, gkalpak commented on dev-infra/format/cli.ts
> +          'changed [shaOrRef]', 'Run the formatter on files changed since the provide sha/ref', {},
```suggestion
          'changed [shaOrRef]', 'Run the formatter on files changed since the provided sha/ref', {},
```

2020-04-22 21:59 UTC, josephperrott commented on dev-infra/format/format.ts
> +const DEFAULT_MATCHERS = ['**/*.{t,j}s', '*.{t,j}s'];
Evidently thats true, I have run into a situation in the past where `**` was 1 or more, rather than 0 or more

2020-04-22 22:04 UTC, josephperrott commented on dev-infra/format/format.ts
> +  // time from 276 seconds to 39 seconds for the same 2700 files
It appears to still be of value.

Running format for this change on itself (enforced on 8 of 24 files):
1 process: 2.04s
8 processes: 1.49s

Running format for this change 19 random files in the repo:
1 process: 2.81s
8 processes: 1.29s

2020-04-22 22:09 UTC, josephperrott commented
@gkalpak Comments addressed, PTAL.

2020-04-23 12:36 UTC, gkalpak approved these changes

2020-04-23 20:33 UTC, AndrewKushnir commented
Hi @josephperrott, could you please rebase this PR and resolve conflicts? Thank you.

2020-04-24 19:24 UTC, josephperrott commented
@googlebot Look again please!

2020-04-24 19:32 UTC, closed without merging