docs: add template ref var to glossary
angular/angular pull request #36743
Opened 2020-04-21 17:34 UTC by kapunahelewong

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Adds definition for "template reference variable" to the glossary.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Per request by @jbogarthyde

2020-04-21 17:42 UTC, jbogarthyde reviewed
Maybe a little more complete?
Is this an Angular feature, or just HTML? If it's HTML, perhaps something about how it is used in Angular.

2020-04-21 17:42 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +
a reference anchor that you add to a DOM element within a template. Elements can share information by referring to one another through these variables.

(Maybe show how you make a reference using the variable?)

2020-04-21 17:42 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +
of the [Template Syntax](guide/template-syntax) guide.

2020-04-21 17:44 UTC, mary-poppins commented
You can preview 5b1fbb8 at https://pr36743-5b1fbb8.ngbuilds.io/.

2020-04-21 17:44 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +## template reference variable
add anchor: {@a template-reference-variable}

2020-04-21 17:45 UTC, jbogarthyde commented on aio/content/guide/glossary.md
> +For more information about template reference variables, see the [Template reference variable](guide/template-syntax#ref-var) section of [Template Syntax](guide/template-syntax).
For more information, see...

2020-04-22 17:23 UTC, mary-poppins commented
You can preview 9146026 at https://pr36743-9146026.ngbuilds.io/.

2020-04-22 20:51 UTC, jbogarthyde approved these changes
LGTM

2020-04-28 19:23 UTC, aikithoughts approved these changes
Judy says good to go, so who am I to argue? :D

2020-05-06 20:31 UTC, mary-poppins commented
You can preview 04b76aa at https://pr36743-04b76aa.ngbuilds.io/.

2020-05-06 20:48 UTC, mary-poppins commented
You can preview a46760a at https://pr36743-a46760a.ngbuilds.io/.

2020-05-15 20:21 UTC, mary-poppins commented
You can preview cfeac1d at https://pr36743-cfeac1d.ngbuilds.io/.

2020-05-15 21:24 UTC, kara submitted a review, later dismissed
Notes on the glossary

2020-05-15 21:24 UTC, kara commented on aio/content/guide/glossary.md
> +A template reference variable, `#var`, is a reference to a DOM element within a template.
These variables can also refer to component or directive instances, so we should probably reflect that in the definition somewhere. Maybe...:

```suggestion
A template reference variable, `#var`, is a reference to a DOM element, component instance, or directive instance within a template.
```

We should probably also explain the basic rules, i.e. that 
- if the var is declared on a component, it's the component instance
- if the var is declared on a normal tag, it's the element
- if the var has a specific export (e.g. `#var="ngModel"`), it's whichever directive or component matches that `exportAs` string

2020-05-21 15:34 UTC, mary-poppins commented
You can preview db24593 at https://pr36743-db24593.ngbuilds.io/.

2020-06-02 17:59 UTC, mary-poppins commented
You can preview 210d41d at https://pr36743-210d41d.ngbuilds.io/.

2020-06-09 17:39 UTC, mary-poppins commented
You can preview 13372ae at https://pr36743-13372ae.ngbuilds.io/.

2020-06-09 18:42 UTC, jelbourn commented on aio/content/guide/glossary.md
> +In the following example `#phone` is the template reference variable.
The following example defines a template reference variable named `#phone`

(active voice)

2020-06-09 18:42 UTC, jelbourn commented on aio/content/guide/glossary.md
> +There are several basic rules regarding template reference variables.
I would phrase this like
```markdown
The following semantics describe the behavior of template reference variables:
```

To me, the word "rules" implies they're restrictions on how the feature may be used, but we're actually just describing how the feature functions.

2020-06-09 18:42 UTC, jelbourn commented on aio/content/guide/glossary.md
> +* If the variable has a specific export, for example, #var="ngModel", the variable refers the directive or component that matches that `exportAs` string.
```suggestion
* If the variable specifies a name on the right-hand side (e.g. `#var="ngModel"`), the variable refers the directive or component on the element with a matching `exportAs` name.
```

2020-06-09 18:44 UTC, mary-poppins commented
You can preview c442489 at https://pr36743-c442489.ngbuilds.io/.

2020-06-10 07:53 UTC, IgorMinar submitted a review, later dismissed
+1 for @jelbourn's comments, except that I suggest that we move the second part of the description (semantics of the usage) into the template doc. This content is in my opinion not suitable for the glossary which should contain only a minimial description of a term with a reference to some other document providing more details (if necessary).

Reviewed-for: public-api

2020-06-16 09:32 UTC, pkozlowski-opensource commented on aio/content/guide/glossary.md
> +A template reference variable, `#var`, is a reference to a DOM element, component instance, or directive instance within a template.
We are missing the `<ng-template #ref>` in this list - in this case we are getting `TemplateRef` which is neither DOM element nor directive / component instance: https://stackblitz.com/edit/angular-azphjr?file=src/app/app.module.ts

2020-06-16 09:34 UTC, pkozlowski-opensource requested changes
We need to cover the `<ng-template #ref>` case - see in-line comments.

2020-06-16 09:34 UTC, pkozlowski-opensource commented on aio/content/guide/template-syntax.md
> +The following semantics describe the behavior of template reference variables:
We are missing the `<ng-template #ref>` in this list - in this case we are getting `TemplateRef` which is neither DOM element nor directive / component instance: https://stackblitz.com/edit/angular-azphjr?file=src/app/app.module.ts

2020-06-16 16:02 UTC, jelbourn commented on aio/content/guide/glossary.md
> +A template reference variable, `#var`, is a reference to a DOM element, component instance, or directive instance within a template.
How about something like
```markdown
A variable defined in a template that references a directive instance,
components instance, DOM element, or embedded template.
```
or, if we don't want to be strictly comprehensive
```markdown
A variable defined in a template that references an instance
associated with an element, such as a directive instance, 
component instance, or DOM element.
```

I also noticed looking at this now the the start of the entry was inconsistent with other entries; it looks like most of the other entries don't start with "_term_ is..."

2020-06-16 16:02 UTC, jelbourn commented on aio/content/guide/template-syntax.md
> +The following semantics describe the behavior of template reference variables:
@kapunahelewong I suggest adding another bullet under the "standard HTML tag" point
```markdown
* If you declare the variable on an `<ng-template>` element, the variable refers to the template (represented by a `TemplateRef` instance).
```

2020-06-17 17:33 UTC, kapunahelewong commented on aio/content/guide/glossary.md
> +A template reference variable, `#var`, is a reference to a DOM element, component instance, or directive instance within a template.
Added to this list. And thank you for the example! I'll add it to the example code in https://github.com/angular/angular/pull/31195

2020-06-17 17:35 UTC, kapunahelewong commented on aio/content/guide/template-syntax.md
> +The following semantics describe the behavior of template reference variables:
Thank you both! Added!

2020-06-17 19:10 UTC, jelbourn commented on aio/content/guide/glossary.md
> +A template reference variable, `#var`, is a reference to a DOM element, component instance, or directive instance within a template.
Did you push your changes? I see the same text as earlier

2020-06-18 08:33 UTC, pkozlowski-opensource commented on aio/content/guide/glossary.md
> +A template reference variable, `#var`, is a reference to a DOM element, component instance, or directive instance within a template.
Yeh, I also don't see TemplateRef mentioned here. Is it intentional?

2020-06-18 08:35 UTC, pkozlowski-opensource commented on aio/content/guide/glossary.md
> +Elements can share information by referring to one another through these variables.
Hmmm, this doesn't sound quite right to me. It is not like elements share information here.
I would rather say that directives can access to referenced things.

2020-06-18 08:38 UTC, pkozlowski-opensource commented on aio/content/guide/template-syntax.md
> +The following semantics describe the behavior of template reference variables:
"semantics describe the behavior" - this reads wired to me, I'm not sure what it means... we just want to say that ref variables point to different things depending on where those are defined. Can we try to express it using simpler / more direct language?

2020-06-19 03:23 UTC, jelbourn commented on aio/content/guide/template-syntax.md
> +The following semantics describe the behavior of template reference variables:
How about 
```markdown
Angular assigns each template reference variable a values based on where you declare the variable:
```

2020-06-19 03:23 UTC, jelbourn commented on aio/content/guide/glossary.md
> +Elements can share information by referring to one another through these variables.
How about
```markdown
After declaring a template reference variable on an element in a template,
you can access values from that variable elsewhere within the same template.
```

2020-06-22 19:46 UTC, mary-poppins commented
You can preview 5eeec02 at https://pr36743-5eeec02.ngbuilds.io/.

2020-06-22 19:52 UTC, kapunahelewong commented on aio/content/guide/glossary.md
> +A template reference variable, `#var`, is a reference to a DOM element, component instance, or directive instance within a template.
Oh! I think I accidentally added it to another branch! Now I've put it in here. And I have added `TemplateRef` to the list. Is this ok?

> A variable defined in a template that references an instance associated with an element, such as a directive instance, component instance, template as in `TemplateRef`, or DOM element.

@pkozlowski-opensource I added a section on TemplateRef based on your example and notes, too: https://github.com/angular/angular/pull/31195/files#diff-fe1da8d4b293de490dd0cef57e6d036bR1880

Once that's in I can add a link, What do you two think?

2020-06-22 20:06 UTC, mary-poppins commented
You can preview 08f0ab3 at https://pr36743-08f0ab3.ngbuilds.io/.

2020-06-22 20:26 UTC, jelbourn approved these changes
LGTM

Reviewed-for: public-api

2020-06-26 14:17 UTC, pkozlowski-opensource approved these changes
LGTM after latest edits, thnx!

Reviewed-for: public-api

2020-06-26 15:06 UTC, jelbourn commented
@IgorMinar I think this one is just waiting on you now

2020-07-23 15:21 UTC, aikithoughts approved these changes
Reviewed-for: global-docs-approvers

2020-07-23 15:35 UTC, kapunahelewong commented
I moved the edits to `template-syntax.md` into `template-reference-vars.md` since the PR to break apart that doc landed.

2020-07-23 15:43 UTC, jelbourn commented
@atscott can you take a look for public-api?

2020-07-23 16:08 UTC, mary-poppins commented
You can preview 28f6dec at https://pr36743-28f6dec.ngbuilds.io/.

2020-07-23 16:12 UTC, atscott approved these changes
reviewed-for: public-api

2020-07-23 17:05 UTC, petebacondarwin approved these changes
Reviewed-for: public-api

2020-07-27 18:16 UTC, alxhub approved these changes
Reviewed-for: public-api

2020-07-27 19:01 UTC, closed without merging