refactor(form): remove unnecessary `!` operators from validators and …
angular/angular pull request #36805
Opened 2020-04-25 03:52 UTC by danranVm

…add type for providers

See angular#24571

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-04-27 18:03 UTC, petebacondarwin requested changes
Please and you add more text to the commit message so that it passes our lint check.

2020-04-27 18:03 UTC, petebacondarwin commented on packages/forms/src/directives/validators.ts
> -  // TODO(issue/24571): remove '!'.
I don't think you should remove this one without first adding a comment as to why this property can have the `!` operator on it.

2020-04-29 21:21 UTC, SchnWalter commented on packages/forms/src/directives/validators.ts
> -  // TODO(issue/24571): remove '!'.
The same applies to all other directives that have a property with the same name as the selector.

2020-04-29 21:26 UTC, petebacondarwin commented on packages/forms/src/directives/validators.ts
> -  // TODO(issue/24571): remove '!'.
I am not convinced that we should leave this `!` in place either.

2020-05-01 08:32 UTC, danranVm commented on packages/forms/src/directives/validators.ts
> -  // TODO(issue/24571): remove '!'.
I thought about it for a while, and then decided to give it a default value to avoid this situation.

```html
<input ngModel="value" pattern />
```

2020-05-01 08:34 UTC, danranVm commented on packages/forms/src/directives/validators.ts
> -  // TODO(issue/24571): remove '!'.
I set a default value for it and then removed `!`.

2020-05-01 08:46 UTC, petebacondarwin commented on packages/forms/src/directives/validators.ts
> +    if (this.pattern) {
Can `""` be a valid pattern? Perhaps you should be doing this instead here?

```suggestion
    if (this.pattern !== undefined) {
```

2020-05-01 17:05 UTC, danranVm commented on packages/forms/src/directives/validators.ts
> +    if (this.pattern) {
test is failing.
it seems that I need to add a test for this situation ?

2020-05-04 19:26 UTC, petebacondarwin commented on packages/forms/src/directives/validators.ts
> +    if (this.maxlength != null) {
This typing: `maxlength?: string|number;` means that `maxlength` cannot be `null`. So I would go for `this.maxlength !== undefined` to be clear.

2020-05-05 00:01 UTC, AndrewKushnir requested changes

2020-05-05 00:01 UTC, AndrewKushnir commented on packages/forms/src/directives/validators.ts
> +export const REQUIRED_VALIDATOR: ExistingProvider = {
This change looks reasonable, but it's a breaking one and it can not be included into a patch branch. Even though these providers are not included into public API, they can be referenced through a deep import (which is not the best practice, but still a possibility). So we'd need to include this change into major version only. I'd propose to move this change to a separate PR to keep the changes in this PR backwards-compatible (as the "refactor" scope assumes).

2020-06-07 03:33 UTC, danranVm commented
@AndrewKushnir modified according to your suggestion.

2020-06-08 22:33 UTC, AndrewKushnir requested changes
Thanks for additional changes @danranVm 👍 

I've left a note on the comment that you added (I think we should move it). I've also updated PR title and description to reflect the latest changes (that you removed the providers type changes), used the title and description from the commit message.

It looks like the `lint` CI job is failing, could you please run the command [printed in the CI job output](https://app.circleci.com/pipelines/github/angular/angular/16502/workflows/754fc1d9-4620-47df-ae78-67494ef1595e/jobs/730424/steps)?

FYI, I've created a separate ticket https://github.com/angular/angular/issues/37493 to look into directive logic unification in the future (noticed that while doing code review).

Thank you.

2020-06-08 22:33 UTC, AndrewKushnir commented on packages/forms/src/directives/validators.ts
> +   * See selectors field in the Directive decorator, a property with the same name as the selector must exist.
Thanks for adding the comment! I think we should move it below to make sure it doesn't appear on the angular.io, [see here](https://angular.io/api/forms/PatternValidator) (since it's an internal implementation note). For example:
```
  @Input() minlength!: string|number;  // This input is always defined, since the name matches directive selector.
```
(the same applies to other cases below)

2020-07-13 18:57 UTC, AndrewKushnir approved these changes
Thanks for additional updates @danranVm, the changes LGTM 👍

2020-07-14 09:03 UTC, petebacondarwin approved these changes

2020-07-14 09:04 UTC, petebacondarwin commented
@AndrewKushnir - can you deal with the presubmit, please?

2020-07-14 16:36 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:321174597:BASE:321174620:1594744589420:52e143d2)

2020-07-14 18:02 UTC, closed without merging