feat(compiler): add name spans for property reads and method calls
angular/angular pull request #36826
Opened 2020-04-28 02:07 UTC by ayazhafiz

ASTs for property read and method calls contain information about
the entire span of the expression, including its receiver. Use cases
like a language service and compile error messages may be more
interested in the span of the direct identifier for which the
expression is constructed (i.e. an accessed property). To support this,
this commit adds a `nameSpan` property on

- `PropertyRead`s
- `SafePropertyRead`s
- `PropertyWrite`s
- `MethodCall`s
- `SafeMethodCall`s

The `nameSpan` property already existed for `BindingPipe`s.

This commit also updates usages of these expressions' `sourceSpan`s in
Ngtsc and the langauge service to use `nameSpan`s where appropriate.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Feature

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-04-28 03:19 UTC, kyliau approved these changes

2020-04-28 03:19 UTC, kyliau commented on packages/compiler/src/expression_parser/parser.ts
> +  get atEOF(): boolean {
please add brief documentation

2020-04-28 03:19 UTC, kyliau commented on packages/compiler/test/expression_parser/utils/unparser.ts
> +      const prefix = spanKey == 'span' ? '' : `[${spanKey}] `;
prefer strict equality

2020-04-28 03:19 UTC, kyliau commented on packages/compiler/test/expression_parser/utils/unparser.ts
> +      if ('nameSpan' in ast) {
prefer `hasOwnProperty` over `in`

2020-04-28 03:19 UTC, kyliau commented on packages/compiler/test/render3/r3_ast_absolute_span_spec.ts
> +        'prop', new AbsoluteSourceSpan(7, 10)
what does this absolute source span refer to?

2020-04-28 03:19 UTC, kyliau commented on packages/language-service/src/completions.ts
> +      let lastBindingEnd = templateBindings.length > 0 &&
prefer const over let

2020-04-28 03:19 UTC, kyliau commented on packages/language-service/src/expression_type.ts
> +    return offsetSpan(ast.nameSpan, -absoluteOffset);
please wrap if body in curly braces

2020-04-28 03:19 UTC, kyliau commented on packages/language-service/src/expressions.ts
> +  function spanFromName(ast: AST&{nameSpan: Span}): Span {
isn't nameSpan of type `AbsoluteSourceSpan`?

2020-04-28 03:19 UTC, kyliau commented on packages/language-service/test/diagnostics_spec.ts
>      const expressions = [
could you please rename this to `receivers` instead?

2020-04-28 03:19 UTC, kyliau commented on packages/language-service/test/diagnostics_spec.ts
>      const expressions = [
ditto

2020-05-02 11:09 UTC, JoostK requested changes
Thanks for working on this. I do have some comments on the chosen source spans in the template type checker.

In general, I think our AST nodes could be cleaned up a lot if we were to have something like `Identifier`, similar to the TypeScript AST. That seems like a large project by itself though, so it's not necessary for this PR. It may also be problematic to push that forward, as tools that depend on the compiler for parsing ASTs would have to be updated. Although the compiler is not technically considered public API, such breakages are still problematic to push through.

2020-05-02 11:09 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +function refinedSpan(ast: AST): AbsoluteSourceSpan {
I'm not fond of this method. The name span is not necessarily a "better" option to report diagnostics on, that all depends on context. Therefore, I don't think it's appropriate to define what a refined span is without that context.

2020-05-02 11:09 UTC, JoostK commented on packages/compiler/test/expression_parser/utils/unparser.ts
> +type UnparsedWithSpan = [string, string];
Please add a comment here what the tuple indices represent, that's not obvious to me.

2020-05-03 16:31 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      addParseSpanInfo(result, ast.nameSpan);
Thanks for reviewing this, I really just kind of blew by this and did not even look at what result was. I'll pay more attention next time.

2020-05-03 19:37 UTC, ayazhafiz commented
> In general, I think our AST nodes could be cleaned up a lot if we were to have something like `Identifier`, similar to the TypeScript AST.

> such breakages are still problematic to push through.

I agree that this would be difficult to push through. IMO the benefit of this isn't worth the churn -- the expression grammar is fairly small, so exposing a common interface for identifier-like ASTs is probably enough.

2020-05-05 11:37 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/expression.ts
> +    addParseSpanInfo(node, ast.nameSpan);
```suggestion
    addParseSpanInfo(node, ast.sourceSpan);
```

2020-05-05 11:37 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      // `$any(expr) -> expr as any`
If you want to keep this comment I would introduce two more backticks:

```suggestion
      // `$any(expr)` -> `expr as any`
```

2020-05-05 11:37 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/test/diagnostics_spec.ts
> +        `synthetic.html(1, 35): Argument of type 'number' is not assignable to parameter of type 'string'.`,
This should have stayed column 28, as it's about the full argument. I'm not sure what the comment structure currently looks like, but my guess is that this can be resolved using some parenthesis. See `wrapForDiagnostics` function and its usages that adds those parens.

2020-05-05 11:37 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/test/diagnostics_spec.ts
> +        expect(messages).toEqual([`synthetic.html(1, 41): Object is possibly 'undefined'.`]);
Much better :+1:

2020-05-05 11:37 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/test/diagnostics_spec.ts
> +          [`synthetic.html(1, 22): Type '2' is not assignable to type 'string'.`]);
TypeScript would report these on the whole assignment path, i.e. `person.name`, which I agree would be a better choice.

2020-05-05 14:24 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/typecheck/src/expression.ts
> +    addParseSpanInfo(node, ast.nameSpan);
👍

2020-05-05 14:40 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/typecheck/test/diagnostics_spec.ts
> +        `synthetic.html(1, 35): Argument of type 'number' is not assignable to parameter of type 'string'.`,
Actually I think it should be at column 9, since that's the entire expression being assigned. What do you think?

2020-05-05 15:35 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/typecheck/test/diagnostics_spec.ts
> +        `synthetic.html(1, 35): Argument of type 'number' is not assignable to parameter of type 'string'.`,
fixed

2020-05-05 15:35 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/typecheck/test/diagnostics_spec.ts
> +          [`synthetic.html(1, 22): Type '2' is not assignable to type 'string'.`]);
fixed

2020-05-05 15:40 UTC, ayazhafiz commented
@JoostK there are still some minor things that could be improved, for example wrapping method calls for diagnostics and annotating that with the span including any receivers (like is done for property reads). I think this can be done in another PR though, since this one is very large as is.

2020-05-05 16:25 UTC, JoostK approved these changes
LGTM for compiler changes.

2020-05-05 16:34 UTC, ayazhafiz commented
Caretaker: could you run g3sync? (I think there may be some failures with Codelyzer)

2020-05-05 19:23 UTC, alxhub commented
[Presubmit](http://test/OCL:309997242:BASE:309997279:1588706596131:81a944da)

2020-05-08 21:42 UTC, closed without merging