fix(core): handle pluralize functions that expect a number
angular/angular pull request #36901
Opened 2020-05-03 06:03 UTC by petebacondarwin

Previously we were passing a string form of the value to pluralize
to the `getLocalePluralCase()` function that is extracted from the
locale data. But some locales have functions that rely upon this
value being a number not a string.

Now we convert the value to a number before passing it to the
locale data function.

Fixes #36888

2020-05-04 18:31 UTC, AndrewKushnir requested changes
Thanks for the fix @petebacondarwin 👍

I guess you also added a test case for this change, but it was hard to find it, since the `i18n_spec.ts` was re-formatted. I've seen undesirable re-formatting to happen because of long lines that were added (for example, for translation strings). If that's the case, you can transform a string into a concatenation of a smaller strings - it should help avoid this re-formatting.

2020-05-04 18:31 UTC, AndrewKushnir commented on packages/core/src/i18n/localization.ts
> +export function getPluralCase(value: string, locale: string): string {
It looks like we need to update `value` argument type, since we handle other types below as well (i.e. `typeof value === 'string' ? parseInt(value, 10) : value`). I'd also propose adding an inline comment on why we do that (as it's explained in PR description).

2020-05-04 18:36 UTC, petebacondarwin commented on packages/core/src/i18n/localization.ts
> +export function getPluralCase(value: string, locale: string): string {
As it turns out this is always a string... So perhaps we should just avoid the `typeof value === 'string'` check?

2020-05-04 19:28 UTC, AndrewKushnir approved these changes
Thanks for the update @petebacondarwin 👍 

I've left 1 comment regarding a test, otherwise LGTM!

2020-05-04 19:28 UTC, AndrewKushnir commented on packages/core/test/acceptance/i18n_spec.ts
> +      TestBed.configureTestingModule({providers: [{provide: LOCALE_ID, useValue: 'es'}]});
Could you plz add a quick comment above this line on why "es" locale was selected for thus test (and may be also a comment on the previous test that uses "ro" locale)? Currently it might be a bit confusing that we have 2 tests with the same title (just different locale), when in fact we do these checks for a reason :)

As a possible option, we could also avoid adding a second test and reuse existing one:
```
// ... short description on why we test with these locales ...
['es', 'ro'].forEach(locale => {
  it(`should return the correct plural form for ICU expressions when using "${locale}" locale`, () => { ... });
});
```

2020-05-04 19:34 UTC, petebacondarwin commented on packages/core/test/acceptance/i18n_spec.ts
> +      TestBed.configureTestingModule({providers: [{provide: LOCALE_ID, useValue: 'es'}]});
Originally I did do that. But the resulting expectations are different so it just becomes a confusion of conditionals.

I'll update the test descriptions.

2020-05-04 22:02 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:309822483:BASE:309822526:1588629610502:ca66d50)

2020-05-05 02:53 UTC, AndrewKushnir commented
@petebacondarwin FYI, presubmit was successful, please add "merge" label if PR is ready to be merged.

2020-05-05 18:59 UTC, closed without merging