Refactor forms overview
angular/angular pull request #36919
Opened 2020-05-04 19:42 UTC by jbogarthyde

Reorganize and edit content of existing form overview to conform to current doc standards and styles

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Current overview does not conform to current doc standards and styles

Issue Number:  
https://angular-team.atlassian.net/browse/DOCS-721

## What is the new behavior?
Reorganizes and edits content to conform to current standards and styles

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-05-04 19:51 UTC, mary-poppins commented
You can preview 24c09c6 at https://pr36919-24c09c6.ngbuilds.io/.

2020-05-05 18:07 UTC, mary-poppins commented
You can preview b2fdc01 at https://pr36919-b2fdc01.ngbuilds.io/.

2020-05-05 23:23 UTC, rockument69 reviewed
Very well done! Just a few comments.

2020-05-05 23:23 UTC, rockument69 commented on aio/content/guide/forms-overview.md
> +* **Reactive forms** are more robust: they're more scalable, reusable, and testable. If forms are a key part of your application, or you're already using reactive patterns for building your applicati
I need in the first sentence some kind of explanation of what a reactive form is. Something like "provides access to low-level APIs and synchronous access to the form model".

2020-05-05 23:23 UTC, rockument69 commented on aio/content/guide/forms-overview.md
> +* **Template-driven forms** are useful for adding a simple form to an app, such as an email list signup form. They're easy to add to an app, but they don't scale as well as reactive forms. If you hav
I need in the first sentence some kind of explanation of what a template-driven form is. Something like "each form element is linked to a template directive that manages the form model internally."

2020-05-05 23:23 UTC, rockument69 commented on aio/content/guide/forms-overview.md
> +Reactive forms are generally  more scalable than template-driven forms, for a number of reasons.
```suggestion
Reactive forms are more scalable than template-driven forms for the following reasons:
```

2020-05-05 23:23 UTC, rockument69 commented on aio/content/guide/forms-overview.md
> +* **Reactive forms** provide access to low-level APIs and synchronous access to the form model, making creating large-scale forms easier.
This bullet doesn't need to start in bold. The 2 bullets flow from the previous sentence.

2020-05-05 23:23 UTC, rockument69 commented on aio/content/guide/forms-overview.md
> +* **Template-driven** forms focus on simple scenarios, are not as reusable, abstract away the low-level APIs, and provide only asynchronous access to the form model.
This should not be a bullet and not start with bold.

2020-05-05 23:23 UTC, rockument69 commented on aio/content/guide/forms-overview.md
> +The following diagram shows how, in reactive forms, the form model is the source of truth; it provides the value and status of the form element at any given point in time, through the `[formControl]`
Do we use figure numbers? I have been doing that in my refactors (so far), calling them figures and providing numbered captions as in "**Figure 1**. *Caption in italics*

2020-05-05 23:23 UTC, rockument69 commented on aio/content/guide/forms-overview.md
> +Testing plays a large part in complex applications and a simpler testing strategy is useful when validating that your forms function correctly.
```suggestion
Testing plays a large part in complex applications. A simpler testing strategy is useful when validating that your forms function correctly.
```

2020-05-06 15:48 UTC, mary-poppins commented
You can preview cbce423 at https://pr36919-cbce423.ngbuilds.io/.

2020-05-06 16:06 UTC, mary-poppins commented
You can preview 036c1d3 at https://pr36919-036c1d3.ngbuilds.io/.

2020-05-11 15:01 UTC, mary-poppins commented
You can preview 457880c at https://pr36919-457880c.ngbuilds.io/.

2020-05-12 14:54 UTC, mary-poppins commented
You can preview 6fb45df at https://pr36919-6fb45df.ngbuilds.io/.

2020-05-13 15:17 UTC, mary-poppins commented
You can preview 3820cbb at https://pr36919-3820cbb.ngbuilds.io/.

2020-05-18 15:29 UTC, mary-poppins commented
You can preview 3cdf77b at https://pr36919-3cdf77b.ngbuilds.io/.

2020-05-19 15:00 UTC, mary-poppins commented
You can preview e0aaab5 at https://pr36919-e0aaab5.ngbuilds.io/.

2020-05-19 17:25 UTC, atscott approved these changes

2020-05-19 17:25 UTC, atscott commented on aio/content/guide/forms-overview.md
> +* **Template-driven forms** rely on directives in the template to create and manipulate the underlying object model. They are useful for adding a simple form to an app, such as an email list signup f
Just a small nit on the very last bit "use template-driven forms". Can we soften that recommendation a bit to something more like "template-driven forms may be a good fit"? It would actually be better if nobody used template driven forms at all. It's something that we've considered deprecating altogether.

2020-05-19 17:25 UTC, atscott commented on aio/content/guide/forms-overview.md
> +When an application contains a form, Angular must keep the view in sync with the component model, and the component model in sync with the view.
```suggestion
When an application contains a form, Angular must keep the view in sync with the component model and the component model in sync with the view.
```
nit: It looks like the last part is a dependent clause so the comma shouldn't be there

2020-05-19 17:39 UTC, mary-poppins commented
You can preview 9fea8a1 at https://pr36919-9fea8a1.ngbuilds.io/.

2020-05-19 18:53 UTC, mary-poppins commented
You can preview bd972af at https://pr36919-bd972af.ngbuilds.io/.

2020-05-20 14:44 UTC, mary-poppins commented
You can preview 7ab9155 at https://pr36919-7ab9155.ngbuilds.io/.

2020-05-21 22:17 UTC, kara requested changes
Some minor comments

2020-05-21 22:17 UTC, kara commented on aio/content/guide/forms-overview.md
> +Reactive forms requires less setup for testing, and testing does not depend on the change-detection cycle when updating and validating the form and data models.
```suggestion
Reactive forms requires less setup for testing, and testing does not require deep understanding of change detection to properly test form updates and validation.
```

2020-05-21 22:17 UTC, kara commented on aio/content/guide/forms-overview.md
> +Tests rely on the change-detection cycle, and require more setup.
Technically all tests rely on change detection. The distinction is that with template-driven forms, you may not realize that you have to run change detection multiple times to accurately reflect what happens at runtime. So it's easy for your tests not to match reality.

```suggestion
Tests are deeply reliant on manual change detection execution to run properly, and require more setup.
```

2020-05-21 22:17 UTC, kara commented on aio/content/guide/forms-overview.md
> +  <img src="generated/images/guide/forms-overview/dataflow-reactive-forms-vtm.png" alt="Reactive forms data flow - view to model" width="100%">
This image looks a little off.  A little too large and pixelated?

2020-05-25 15:22 UTC, mary-poppins commented
You can preview 2c60ae3 at https://pr36919-2c60ae3.ngbuilds.io/.

2020-05-25 18:13 UTC, mary-poppins commented
You can preview d9df608 at https://pr36919-d9df608.ngbuilds.io/.

2020-05-26 15:54 UTC, aikithoughts approved these changes

2020-05-26 17:39 UTC, jbogarthyde commented
@kara Your changes have been addressed, please check.

2020-05-27 15:42 UTC, mary-poppins commented
You can preview 096e4cd at https://pr36919-096e4cd.ngbuilds.io/.

2020-05-27 18:43 UTC, kara requested changes
A few more things

2020-05-27 18:43 UTC, kara commented on aio/content/guide/forms-overview.md
> +Reactive forms requires less setup for testing, and testing does not require deep understanding of change-detection to properly test form updates and validation.
```suggestion
Reactive forms require less setup for testing, and testing does not require deep understanding of change detection to properly test form updates and validation.
```

2020-05-27 18:43 UTC, kara commented on aio/content/guide/forms-overview.md
> +Reactive forms are  more scalable than template-driven forms. They provide direct access to the underlying form API, and synchronous access to the form data model, making creating large-scale forms e
```suggestion
Reactive forms are more scalable than template-driven forms. They provide direct access to the underlying form API, and synchronous access to the form data model, making creating large-scale forms easier.
```

2020-05-27 18:43 UTC, kara commented on aio/content/guide/forms-overview.md
> +  <img src="generated/images/guide/forms-overview/dataflow-td-forms-vtm.png" alt="Template-driven forms data flow - view to model" width="100%">
These template-driven form diagrams still look a lot bigger than the reactive forms ones (in other words, blown up instead of centered). Can we make it consistent?

2020-05-27 19:42 UTC, jbogarthyde commented
@kara  Changes made, please check.

2020-05-27 19:52 UTC, mary-poppins commented
You can preview 5d5a471 at https://pr36919-5d5a471.ngbuilds.io/.

2020-05-27 20:33 UTC, kara commented
This is what I'm seeing

![Screen Shot 2020-05-27 at 1 32 18 PM](https://user-images.githubusercontent.com/3871688/83069349-98213e80-a01e-11ea-85cf-d652d48d21a7.png)

If you click on that image, you'll see that the forms diagram is blurry

2020-06-01 15:39 UTC, jbogarthyde commented
@sjtrimble is looking for the source of the image.

2020-06-01 15:44 UTC, mary-poppins commented
You can preview 6a0b1fc at https://pr36919-6a0b1fc.ngbuilds.io/.

2020-06-01 16:05 UTC, sjtrimble commented
@jbogarthyde Just shared the source files/folder with you and the SVGs.

2020-06-01 17:39 UTC, mary-poppins commented
You can preview 3151204 at https://pr36919-3151204.ngbuilds.io/.

2020-06-01 17:42 UTC, jbogarthyde commented
@kara restored original diagrams, looks correct to me. Please check.

2020-06-01 23:25 UTC, kara approved these changes
LGTM

2020-06-02 14:23 UTC, aikithoughts approved these changes
Reviewed-for: global-docs-approvers

2020-06-02 14:23 UTC, mary-poppins commented
You can preview fb3de5a at https://pr36919-fb3de5a.ngbuilds.io/.

2020-06-02 19:26 UTC, mary-poppins commented
You can preview 81b1330 at https://pr36919-81b1330.ngbuilds.io/.

2020-06-02 21:29 UTC, closed without merging