fix(router): update type for routerLink to include null and undefined
angular/angular pull request #37018
Opened 2020-05-08 18:04 UTC by atscott

PR #13380 added support for `null` and `undefined` but the type on the parameter was not updated. This would result in a compilation error if `fullTemplateTypeCheck` is enabled.

Fixes #36544

2020-05-08 18:25 UTC, AndrewKushnir approved these changes
LGTM 👍

2020-05-08 18:28 UTC, atscott commented
[presubmit](https://test.corp.google.com/ui#id=OCL:310590576:BASE:310590602:1588961276540:a823eae6)

2020-05-15 04:21 UTC, IgorMinar requested changes

2020-05-15 04:21 UTC, IgorMinar commented on packages/router/src/directives/router_link.ts
> +  set routerLink(commands: any[]|string|null|undefined) {
can you please add docs and document what will be the resulting behavior of passing `null` and `undefined` into `[router-link]`? thanks!

2020-05-15 04:28 UTC, IgorMinar requested changes
can you do a light past to add the docs? Please don’t spend too much time on it, even a single sentence per property is better than nothing.

https://next.angular.io/api/router/RouterLink
https://next.angular.io/api/router/RouterLinkWithHref

Thanks!

2020-05-18 17:29 UTC, mary-poppins commented
You can preview 62a6755 at https://pr37018-62a6755.ngbuilds.io/.
You can preview 10fc47f at https://pr37018-10fc47f.ngbuilds.io/.
You can preview 92beec0 at https://pr37018-92beec0.ngbuilds.io/.
You can preview 1719671 at https://pr37018-1719671.ngbuilds.io/.
You can preview 1e66166 at https://pr37018-1e66166.ngbuilds.io/.
You can preview 01c5d4f at https://pr37018-01c5d4f.ngbuilds.io/.

2020-05-18 17:55 UTC, IgorMinar approved these changes
LGTM after the docs are updated. Thank you!

Reviewed-for: public-api

2020-05-18 17:55 UTC, IgorMinar commented on packages/router/src/directives/router_link.ts
> +   * Passed to `Router.createUrlTree` as part of the `NavigationExtras`.
please use `#` instead of `.` in this case. The community convention is that`#` is used for instance methods and `.` is for static methods.
```suggestion
   * Passed to `Router#createUrlTree` as part of the `NavigationExtras`.
```

2020-05-18 17:55 UTC, IgorMinar commented on packages/router/src/directives/router_link.ts
> +   * @see [Router.createUrlTree](https://angular.io/api/router/Router#createurltree)
Please don't use absolute links anywhere in angular.io as this will break navigation flow when a user is visiting a versioned deployment of the docs (e.g. v9.angular.io). In fact, all that you should need here is `Router#createUrlTree`.

See an existing example: https://github.com/angular/angular/blob/22d80a6780c235b2e8c64b23ebe7dd49c49f9aae/packages/core/src/interface/lifecycle_hooks.ts#L13-L18

2020-05-18 17:55 UTC, IgorMinar commented on packages/router/src/directives/router_link.ts
> +   */
btw I'm not sure if you know, but if you add `aio: preview` label to this PR you get a comment posted on the PR by @mary-poppins - the comment then contains a link to the preview of the docs at each SHA in this PR.

You can then navigate to that URL and see what your change will look like on angular.io  without you having to build it locally.

Example link for this particular change: https://pr37018-01c5d4f.ngbuilds.io/api/router/RouterLink#properties

2020-05-18 17:55 UTC, IgorMinar commented on packages/router/src/directives/router_link.ts
> +   * @deprecated 4.0.0 use `queryParamsHandling` instead.
```suggestion
   * @deprecated As of Angular v4.0 use `queryParamsHandling` instead.
```

2020-05-18 18:05 UTC, atscott commented on packages/router/src/directives/router_link.ts
> +   */
I learned this after see you add the label to the PR. Very useful, thanks for pointing that out.

2020-05-18 18:28 UTC, mary-poppins commented
You can preview 266b6e0 at https://pr37018-266b6e0.ngbuilds.io/.

2020-05-18 18:44 UTC, mary-poppins commented
You can preview 06e8856 at https://pr37018-06e8856.ngbuilds.io/.

2020-05-18 18:46 UTC, mary-poppins commented
You can preview 7a32731 at https://pr37018-7a32731.ngbuilds.io/.

2020-05-18 19:02 UTC, mary-poppins commented
You can preview 5f66203 at https://pr37018-5f66203.ngbuilds.io/.

2020-05-18 19:41 UTC, mary-poppins commented
You can preview f2ecb52 at https://pr37018-f2ecb52.ngbuilds.io/.

2020-05-18 20:41 UTC, atscott commented
merge assistance: I'm the owner of the router. LGTMs from Igor and Andrew Kushnir should cover required approvals.

2020-05-18 21:55 UTC, closed without merging