Add aikidave to DOCS: Marketing approvers
angular/angular pull request #37014
Opened 2020-05-08 16:33 UTC by aikidave

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Only IgorMinar and StephenFluin can approve DOCS: Marketing files
Issue Number: N/A

## What is the new behavior?
Extends approvers to include aikidave

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-05-08 17:17 UTC, IgorMinar requested changes

2020-05-08 17:17 UTC, IgorMinar commented on .pullapprove.yml
> +        - aikidave
Can you please sort the list alphabetically? Thanks

2020-05-09 00:05 UTC, IgorMinar approved these changes
LGTM. Thanks!

Please keep in mind that with great powers also comes great responsibility! ❤️ 

Reviewed-for: code-ownership

2020-05-11 18:08 UTC, closed without merging

2020-05-14 08:10 UTC, petebacondarwin commented
@IgorMinar - don't forget to check the commit message is valid when reviewing... this should have been `docs:...` not `fix: ...`.

2020-05-14 14:36 UTC, aikidave commented
Why `docs:...`? It's not really a docs fix?

2020-05-14 14:39 UTC, petebacondarwin commented
Sorry I meant `build: ...`

2020-05-14 14:40 UTC, petebacondarwin commented
or `ci: ...`