docs(changelog): add doc for rxjs multicasting
angular/angular pull request #37024
Opened 2020-05-09 09:35 UTC by subratpalhar92

showing a pagination use case with rxjs subject

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-05-09 09:38 UTC, subratpalhar92 commented
Add Documentation for rxjs multicasting.

2020-07-08 17:00 UTC, jbogarthyde requested changes

2020-07-08 17:00 UTC, jbogarthyde commented on aio/content/guide/observables.md
> +
Something like this:

In the following example, several observers receive the same current-page value emitted by the `Subject`. Each one handles the received value differently to log the current-page value, the next-page value, and the previous-page value.

2020-08-15 08:54 UTC, subratpalhar92 commented on aio/content/examples/observables/src/multicasting-with-subject.ts
> +const pagination = new Subject<number>();
import statement is not necessary..

2020-08-15 08:55 UTC, subratpalhar92 commented on aio/content/guide/observables.md
> +## Multicasting with subject
> aking this part of the M

added h3(###)

2020-08-15 08:57 UTC, subratpalhar92 commented on aio/content/guide/observables.md
> +A RxJS Subject is a special type of Observable that allows values to be multicasted to many Observers.
added the note 'In RxJS, a Subject is a special'

2020-08-15 15:15 UTC, subratpalhar92 commented
i faced git rebase issue. i am making a fresh pull request.

2020-08-15 16:15 UTC, subratpalhar92 commented
added a new pull request

https://github.com/angular/angular/pull/38479

2020-08-15 16:15 UTC, closed without merging