fix(ngcc): correctly get config for packages in nested `node_modules/`
angular/angular pull request #37040
Opened 2020-05-10 19:16 UTC by gkalpak

Previously, ngcc would only be able to match an ngcc configuration to packages that were located inside the project's top-level `node_modules/`. However, if there are multiple versions of a package in a project (e.g. as a transitive dependency of other packages), multiple copies of a package (at different versions) may exist in nested `node_modules/` directories. For example, one at `<project-root>/node_modules/some-package/` and one at `<project-root>/node_modules/other-package/node_modules/some-package/`. In such cases, ngcc was only able to detect the config for the first copy but not for the second.

This commit fixes this by returning a new instance of `ProcessedNgccPackageConfig` for each different package path (even if they refer to the same package name). In these `ProcessedNgccPackageConfig`, the `entryPoints` paths have been processed to take the package path into account.

2020-05-10 19:26 UTC, mary-poppins commented
You can preview ac92b5a at https://pr37040-ac92b5a.ngbuilds.io/.

2020-05-11 07:38 UTC, devversion approved these changes
LGTM for dev-infra.

2020-05-11 10:48 UTC, petebacondarwin requested changes
Can you remove the `undefined` from the `RawNgccPackageConfig.exports` declaration.
Otherwise LGTM (with a nit or two).

2020-05-11 10:48 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +  entryPoints?: {[entryPointPath: string]: NgccEntryPointConfig|undefined};
```suggestion
  entryPoints?: {[entryPointPath: string]: NgccEntryPointConfig};
```

2020-05-11 10:48 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +                                        ]) => [resolve(packagePath, relativePath), config!]);
If this is the case, then it is better to remove the `undefined` from the definition of:

```
entryPoints?: {[entryPointPath: string]: NgccEntryPointConfig|undefined};
```

2020-05-13 19:12 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +  entryPoints?: {[entryPointPath: string]: NgccEntryPointConfig|undefined};
The reason I added `undefined` is that it will better reflect the fact that `.entryPoints.someEntryPoint` might or might not be defined. Previously, TS would infer it as `NgccEntryPointConfig` although that was not necessarily the case.

This was more of an issue when this type was returned by `getPackageConfig()`, so happy to remove it now that `RawNgccPackageConfig` is only used internally.

2020-05-13 19:15 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/entry_point.ts
> +  const packageName = packagePath.replace(/^.*\/node_modules\//i, '');
I thought about it too, but I felt it would require `getPackageConfig()` to assume too much. It is an implementation detail that `getEntryPointInfo()` only considers packages inside `node_modules/` (which might change in the future) and I think it is the caller's responsibility to determine the package name.

The dependency resolver, for example, does it differently: https://github.com/angular/angular/blob/ac92b5ac6c79f0a7cc2900b48bf8f6a3f5a85aaf/packages/compiler-cli/ngcc/src/dependencies/dependency_resolver.ts#L228-L229

WDYT?

2020-05-13 19:18 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/configuration.ts
> +                                        ]) => [resolve(packagePath, relativePath), config!]);
The main purpose of `undefined` was to guard against the fact that accessing arbitrary properties on `entryPoints` is not guaranteed to return an `NgccEntryPointConfig` (see https://github.com/angular/angular/pull/37040#discussion_r424670933). Here we are accessing properties that we know exist on `entryPoints`, so it is safe(r) to assume they are not `undefined`. (Not that it is not possible for people to set `entryPoints.foo` to undefined in their configs, but addressing that would be outside the scope of this PR :grin:)

Removing the `undefined` as mentioned in https://github.com/angular/angular/pull/37040#discussion_r424670933...

2020-05-13 19:50 UTC, gkalpak commented
Addressed feedback (or way or another 😛). @petebacondarwin, ptal.

2020-05-13 19:53 UTC, mary-poppins commented
You can preview cae6180 at https://pr37040-cae6180.ngbuilds.io/.

2020-05-20 09:36 UTC, mary-poppins commented
You can preview 577858a at https://pr37040-577858a.ngbuilds.io/.

2020-05-21 20:27 UTC, mary-poppins commented
You can preview dc697b0 at https://pr37040-dc697b0.ngbuilds.io/.

2020-05-22 17:53 UTC, mary-poppins commented
You can preview bd5b369 at https://pr37040-bd5b369.ngbuilds.io/.

2020-05-22 19:03 UTC, mary-poppins commented
You can preview 2f1b8c8 at https://pr37040-2f1b8c8.ngbuilds.io/.

2020-05-22 19:20 UTC, gkalpak commented
This turned out to be a little more tricky than I expected. I finally have something I am happy with (I think 😅).

@petebacondarwin, ptal.

2020-05-23 15:33 UTC, petebacondarwin requested changes
I am not sure how it passes integration tests but I am pretty sure we cannot rely upon secondary entry-points containing a `version` property.

2020-05-23 15:33 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/entry_point.ts
> +    packageVersion: packageJson?.version ?? null,
If the entry-point package.json does not contain a `version` property, which is possible, then we could just load up the `package.json` of the main package (found at `packagePath`)?

2020-05-23 15:33 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts
> +            expect(entryPoint).toBeInstanceOf(Object);
Another opportunity to use the `isEntryPoint()` helper suggested earlier.

2020-05-23 15:33 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts
> +              getPackageConfigSpy.withArgs(packagePath, null).and.returnValue({
Could we avoid a spy and just generate an `ngcc.config.js` file here?

2020-05-23 15:33 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts
> +              // Ensure the entry-point `package.json` does not exist (e.g. from a previous test).
Do you mean from a previous `expect()`? Since each `it()` clause should get its own new `MockFileSystem`.
Perhaps it would be safer to move each of these `expect()` calls into their own `it()` clause if we are concerned about bleeding data between them?

2020-05-23 15:33 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts
> +              // Ensure the entry-point `package.json` does not exist (e.g. from a previous test).
This would also allow us to have a description for each of them, which would be good documentation of what the tests are actually doing.

2020-05-25 08:43 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.ts
> +          subEntryPoint !== IGNORED_ENTRY_POINT) {
It felt less readable. How about re-using `isEntryPoint`:

```ts
const isEntryPoint =
    subEntryPoint !== NO_ENTRY_POINT && subEntryPoint !== INCOMPATIBLE_ENTRY_POINT;
if (isEntryPoint && subEntryPoint !== IGNORED_ENTRY_POINT) {
```

2020-06-05 19:53 UTC, mary-poppins commented
You can preview 71ae344 at https://pr37040-71ae344.ngbuilds.io/.

2020-06-06 12:25 UTC, gkalpak commented on packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts
> +              // Ensure the entry-point `package.json` does not exist (e.g. from a previous test).
Yes, from a previous `expect()`. I thought about splitting up into different `it()` calls, but I felt it wouldn't make the tests easier to follow/read.

2020-06-06 12:26 UTC, gkalpak commented on packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts
> +              // Ensure the entry-point `package.json` does not exist (e.g. from a previous test).
Happy to split it up if you think it would be better.

2020-06-06 12:27 UTC, gkalpak commented on packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts
> +              getPackageConfigSpy.withArgs(packagePath, null).and.returnValue({
I guess we could, but what would be the benefit?

2020-06-06 13:03 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/entry_point.ts
> + *   still contain the same version as the main package (e.g. `@angular/common`).
😱

2020-06-06 13:08 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/entry_point.ts
> + * contain the same version as the main package (e.g. `@angular/common`).
😱

2020-06-06 13:29 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/packages/entry_point.ts
> +      loadedEntryPointPackageJson!;
Agreed this is not great. I have moved things around to get rid of the non-null assertions.

2020-06-08 11:37 UTC, mary-poppins commented
You can preview 82ce6c7 at https://pr37040-82ce6c7.ngbuilds.io/.

2020-06-08 12:41 UTC, mary-poppins commented
You can preview 45318c8 at https://pr37040-45318c8.ngbuilds.io/.

2020-06-08 17:25 UTC, mary-poppins commented
You can preview c882ee1 at https://pr37040-c882ee1.ngbuilds.io/.

2020-06-08 20:26 UTC, gkalpak commented
@petebacondarwin, I have addressed your comments in fixup commits (all fixup commits are new) plus this new regular commit:
- **fix(ngcc): correctly retrieve a package's version from it's `package.json`** (https://github.com/angular/angular/pull/37040/commits/8d353e36fd0db65bf8830a8418291c46afffa8ae)

2020-06-08 20:34 UTC, mary-poppins commented
You can preview e9a8e1b at https://pr37040-e9a8e1b.ngbuilds.io/.

2020-06-09 20:03 UTC, petebacondarwin approved these changes
LGTM - Just the one question about the order of checking for entry-point version that I think is worth considering.

2020-06-10 21:14 UTC, petebacondarwin approved these changes
LGTM (again)

2020-06-10 21:27 UTC, JoostK approved these changes
Nice cleanup overall!

2020-06-12 01:58 UTC, closed without merging