feat(platform-server): use absolute URLs from Location for HTTP
angular/angular pull request #37071
Opened 2020-05-12 15:07 UTC by CaerusKaru

Currently, requests from the server that do not use absolute URLs
fail because the server does not have the same fallback mechanism
that browser XHR does. This adds that mechanism by pulling the
full URL out of the document.location object, if available.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-05-12 15:07 UTC, CaerusKaru commented
cc @alan-agius4

2020-05-12 22:13 UTC, kyliau requested changes

2020-05-12 22:13 UTC, kyliau commented on packages/platform-server/src/http.ts
> +const isAbsoluteUrl = /^[a-zA-Z\-\+.]+:\/\//;
Is there a spec for the scheme? If so, could you please add a comment for it?
I'm surprised that characters like `+` are allowed.

2020-05-12 22:13 UTC, kyliau commented on packages/platform-server/test/integration_spec.ts
> +         platform.bootstrapModule(HttpClientExampleModule).then(ref => {
Consider using await instead of then, since this is an `async` function.

2020-05-12 22:13 UTC, kyliau commented on packages/platform-server/test/integration_spec.ts
> +           ref.injector.get<NgZone>(NgZone).run(() => {
Is the explicit cast for `NgZone` here necessary?

2020-05-12 22:13 UTC, kyliau commented on packages/platform-server/test/integration_spec.ts
> +             http.get<string>('/testing').subscribe((body: string) => {
Likewise, is the explicit cast for `string` necessary?

2020-05-12 22:13 UTC, kyliau commented on packages/platform-server/src/http.ts
> +      return this.wrap(request.clone({url: this.doc.location.href + request.url}));
Do we have to consider trailing slash in `this.doc.location.href` or leading slash in `request.url`?
i.e.  what if the slash is missing or is present in both?

2020-05-12 22:20 UTC, kyliau commented
g3 presubmit: http://test/OCL:311212750:BASE:311212803:1589321997009:95b55e6c

2020-05-13 00:48 UTC, CaerusKaru commented on packages/platform-server/test/integration_spec.ts
> +             http.get<string>('/testing').subscribe((body: string) => {
`string` is necessary, otherwise `body` is not typed correctly.

2020-05-13 17:30 UTC, kyliau approved these changes

2020-05-13 23:00 UTC, closed without merging

2020-05-27 11:00 UTC, naveedahmed1 commented
Should this change create any side effects? I upgraded my app from Angular `10.0.0-next.6` to `10.0.0-rc.0` and suddenly it broke the SSR for my app. I downgraded `"@angular/platform-server": "10.0.0-next.6",` and everything started working fine.

2020-05-27 12:01 UTC, alan-agius4 commented
@naveedahmed1, sorry to hear that this change caused a regression.

Please fill an issue together with a minimal reproduction.

Thanks.

2020-05-27 16:39 UTC, naveedahmed1 commented
Thanks @alan-agius4, the reproduction would be a little difficult, since in my case its a .net core app.

Let me share the situation, if this can be helpful: 

1. In my case I am already converting the request url from relative to absolute in my `http interceptor`'s `intercept` method.
2. When on server, when I receive a response of the http request I add it to `this.transferState.set(CACHE_KEY, event as any);` and on client, I check if we already have the cached response, its served from cache otherwise request is sent to the server.

Does the change in this pull request honor this change I make to request url?

2020-05-27 16:43 UTC, CaerusKaru commented
This PR should leave absolute URL’s alone. It only injects the host name at the tail end of the request, eg right before the request is made. So if you provide an absolute URL, everything should work as it has in the past.

As @alan-agius4 said, if this is an issue for you, please open an issue and provide a minimal reproduction. Without this, we can’t reasonably help further.

2020-05-27 17:59 UTC, naveedahmed1 commented
Thank you @CaerusKaru for your response, I am just reviewing my code and investigating it on my end. If I don't find any solution I will definitely open an a new issue.

If you could please just comment on this:

I have a url `http://localhost:53189/jobs/job/204182`, when I open it in my browser the request goes to server which fetch data from `https://www.mustakbil.com/ws/jobs/job/204182`, render it and returns final response to client. In my component I make `http` request to `/ws/jobs/job/204182` and then in intercept method of my interceptor I convert it to `https://www.mustakbil.com/ws/jobs/job/204182`.

After this pull request, if I `console log(req.url)` in `intercept` method of my interceptor, before any modification to the request it shows `/jobs/job/204182/ws/jobs/job/204182`, whereas I expect it to be `/ws/jobs/job/204182` because that's what I passed from my component i.e. `this.http.get("/ws/jobs/job/204182")`. Any idea what's happening here?

One more question, does this pull request modifies the url after user defined interceptors have been executed?

2020-05-27 18:02 UTC, CaerusKaru commented
As I said in my previous comment, the new logic is executed at the tail end of the request, after all interceptors complete. That’s why you won’t see any changes in your code.

2020-05-27 18:05 UTC, naveedahmed1 commented
Can I add you to a private angular repo, and if you could please review the interceptor?

2020-05-27 18:10 UTC, alan-agius4 commented
@naveedahmed1, can you please open an issue? Ideally the reproduction provide contain the least possible amount of code needed to demonstrate the issue. 

Unfortunately, if the reproduction is complex or large it will take a lot of effort to debug and get to the bottom of the issue.

Also, PR’s is not the correct place to discuss issues.

Thanks for your understanding.

2020-05-27 19:18 UTC, naveedahmed1 commented
Thanks @alan-agius4 , I have created a new issue here https://github.com/angular/angular/issues/37314

2020-05-28 22:07 UTC, naveedahmed1 commented on packages/platform-server/src/http.ts
> +    const href = this.doc.location.href;
Shouldn't we use `window.location.hostname` or `location.location.hostname` ? Since `Location href` Property returns the entire URL (of the current page) and we just need the `hostname` to prepend to convert the relative url to absolute url.

2020-05-29 07:25 UTC, jedjebari commented
I have the same issue than you @naveedahmed1 .

If we bootstrap the app on root route (http://myapp/), then everything is ok.
But if we bootstrap on a feature root (http://myapp/myfeature), then it breaks, because the http request is done on http://myapp/myfeature/api/blablabla instead of http://myapp/api/blablabla.

So that's not so complex to reproduce. Can someone else try on its side ?