Update API reference doc for Pipes
angular/angular pull request #37099
Opened 2020-05-13 21:28 UTC by jbogarthyde

Edit descriptions, usage examples, and add links to be complete and consistent with API reference doc style

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Pipe API doc lacks links back to guide material (Pipes and Internationalization guides)

Issue Number: N/A

## What is the new behavior?
Language/style edits, add links to guides.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-05-13 21:38 UTC, mary-poppins commented
You can preview ad488b6 at https://pr37099-ad488b6.ngbuilds.io/.

2020-05-13 21:52 UTC, mary-poppins commented
You can preview c4c15fe at https://pr37099-c4c15fe.ngbuilds.io/.

2020-05-18 15:33 UTC, mary-poppins commented
You can preview e9c3ccf at https://pr37099-e9c3ccf.ngbuilds.io/.

2020-05-18 15:50 UTC, mary-poppins commented
You can preview 53b5428 at https://pr37099-53b5428.ngbuilds.io/.

2020-05-18 17:03 UTC, mary-poppins commented
You can preview f565a82 at https://pr37099-f565a82.ngbuilds.io/.

2020-05-18 21:31 UTC, mary-poppins commented
You can preview fa205d8 at https://pr37099-fa205d8.ngbuilds.io/.

2020-05-19 14:57 UTC, mary-poppins commented
You can preview 8edab9e at https://pr37099-8edab9e.ngbuilds.io/.

2020-05-20 14:43 UTC, mary-poppins commented
You can preview 17592f7 at https://pr37099-17592f7.ngbuilds.io/.

2020-05-25 15:22 UTC, mary-poppins commented
You can preview b0be8c4 at https://pr37099-b0be8c4.ngbuilds.io/.

2020-05-27 15:33 UTC, mary-poppins commented
You can preview c7fda16 at https://pr37099-c7fda16.ngbuilds.io/.

2020-06-01 15:45 UTC, mary-poppins commented
You can preview a648a26 at https://pr37099-a648a26.ngbuilds.io/.

2020-06-02 14:21 UTC, mary-poppins commented
You can preview 746a431 at https://pr37099-746a431.ngbuilds.io/.

2020-06-02 19:27 UTC, mary-poppins commented
You can preview 9c20d72 at https://pr37099-9c20d72.ngbuilds.io/.

2020-06-03 15:54 UTC, mary-poppins commented
You can preview eb7ff97 at https://pr37099-eb7ff97.ngbuilds.io/.

2020-06-08 15:35 UTC, mary-poppins commented
You can preview f79388c at https://pr37099-f79388c.ngbuilds.io/.

2020-06-09 14:33 UTC, mary-poppins commented
You can preview 295ecb0 at https://pr37099-295ecb0.ngbuilds.io/.

2020-06-09 19:58 UTC, mary-poppins commented
You can preview a5486b7 at https://pr37099-a5486b7.ngbuilds.io/.

2020-06-10 14:56 UTC, petebacondarwin requested changes
Reviewed-for: fw-i18n

2020-06-10 15:51 UTC, petebacondarwin approved these changes

2020-06-15 14:49 UTC, mary-poppins commented
You can preview 17b8ce8 at https://pr37099-17b8ce8.ngbuilds.io/.

2020-06-16 14:44 UTC, mary-poppins commented
You can preview ec50369 at https://pr37099-ec50369.ngbuilds.io/.

2020-06-16 17:12 UTC, jbogarthyde commented
Pete has approved this. Can someone from FW please do pull-approve?

2020-06-16 17:20 UTC, atscott approved these changes
reviewed-for: fw-core

2020-06-22 15:27 UTC, mary-poppins commented
You can preview a9a2119 at https://pr37099-a9a2119.ngbuilds.io/.

2020-06-22 18:04 UTC, jbogarthyde commented
@gkalpak Can you do global approve and G3? (@atscott has approved, although git is still listing him as pending).

2020-06-22 18:04 UTC, atscott approved these changes

2020-06-23 15:29 UTC, mary-poppins commented
You can preview 8b87cab at https://pr37099-8b87cab.ngbuilds.io/.

2020-06-23 18:21 UTC, mary-poppins commented
You can preview c10af50 at https://pr37099-c10af50.ngbuilds.io/.

2020-06-23 19:01 UTC, jbogarthyde commented
This is docs only, should not need G3

2020-06-24 15:43 UTC, mary-poppins commented
You can preview b7adfd3 at https://pr37099-b7adfd3.ngbuilds.io/.

2020-06-25 18:35 UTC, AndrewKushnir commented
Hi @jbogarthyde, it looks like @gkalpak or @IgorMinar should provide the final approval before this PR gets merged, so I'm removing the "merge" label for now. Feel free to add it back once Igor or George approve the changes. Thank you.

2020-06-25 20:00 UTC, IgorMinar submitted a review, later dismissed
Reviewed-for: docs-packaging-and-releasing

2020-06-25 20:00 UTC, IgorMinar commented on aio/content/guide/deprecations.md
> -
hey @jbogarthyde can you please help me understand why this section is being removed?

The deprecation is still active, so as far as I can tell, this text should remain here. Am I missing something? thanks

2020-06-29 15:01 UTC, mary-poppins commented
You can preview 624fcb9 at https://pr37099-624fcb9.ngbuilds.io/.

2020-06-29 15:03 UTC, jbogarthyde commented on aio/content/guide/deprecations.md
> -
I don't remember why I removed it, so I'm restoring it.

2020-06-29 15:15 UTC, mary-poppins commented
You can preview 3245c9b at https://pr37099-3245c9b.ngbuilds.io/.

2020-06-29 20:26 UTC, mary-poppins commented
You can preview 32f2a6f at https://pr37099-32f2a6f.ngbuilds.io/.

2020-06-30 15:19 UTC, jbogarthyde commented
@IgorMinar Deprecation info restored, please recheck.

2020-06-30 15:37 UTC, mary-poppins commented
You can preview bb026ff at https://pr37099-bb026ff.ngbuilds.io/.

2020-07-01 14:53 UTC, mary-poppins commented
You can preview 5162e20 at https://pr37099-5162e20.ngbuilds.io/.

2020-07-07 16:08 UTC, mary-poppins commented
You can preview 2a6f690 at https://pr37099-2a6f690.ngbuilds.io/.

2020-07-08 14:36 UTC, mary-poppins commented
You can preview 3e28d59 at https://pr37099-3e28d59.ngbuilds.io/.

2020-07-13 15:02 UTC, mary-poppins commented
You can preview bad528b at https://pr37099-bad528b.ngbuilds.io/.

2020-07-14 16:50 UTC, mary-poppins commented
You can preview 282cc19 at https://pr37099-282cc19.ngbuilds.io/.

2020-07-15 14:56 UTC, mary-poppins commented
You can preview 3c94c46 at https://pr37099-3c94c46.ngbuilds.io/.

2020-07-20 15:43 UTC, mary-poppins commented
You can preview 59e9f1a at https://pr37099-59e9f1a.ngbuilds.io/.

2020-07-21 15:15 UTC, mary-poppins commented
You can preview 313b9d8 at https://pr37099-313b9d8.ngbuilds.io/.

2020-07-22 15:09 UTC, mary-poppins commented
You can preview 0226b5e at https://pr37099-0226b5e.ngbuilds.io/.

2020-07-27 14:40 UTC, mary-poppins commented
You can preview 625b50b at https://pr37099-625b50b.ngbuilds.io/.

2020-07-28 16:06 UTC, mary-poppins commented
You can preview aa8abba at https://pr37099-aa8abba.ngbuilds.io/.

2020-07-29 00:01 UTC, jelbourn approved these changes
LGTM, using global approvers because this file touches the deprecations doc, but it only removes trailing whitespace. 

Reviewed-for: global-approvers

2020-07-29 20:14 UTC, closed without merging