fix(language-service): Recover from error in analyzing Ng Modules
angular/angular pull request #37108
Opened 2020-05-14 15:44 UTC by ayazhafiz

Closes https://github.com/angular/vscode-ng-language-service/issues/777

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-05-14 15:45 UTC, ayazhafiz commented on packages/language-service/src/typescript_host.ts
> +    }
We should propagate the error to an end user, maybe by attaching a logger to the host.

2020-05-14 22:14 UTC, kyliau requested changes

2020-05-14 22:14 UTC, kyliau commented on packages/language-service/src/typescript_host.ts
> +    }
The logger method is right in this class

https://github.com/angular/angular/blob/7acd33007d9bd30288a76fa2a3b6fe5948143d9f/packages/language-service/src/typescript_host.ts#L557-L566

2020-05-14 22:14 UTC, kyliau commented on packages/language-service/test/typescript_host_spec.ts
> +    // First create a TypescriptHost with empty script names
Please try to override `/app/main.ts` with an invalid `entryComponent` in the `NgModule`.

2020-05-15 00:08 UTC, ayazhafiz commented on packages/language-service/src/typescript_host.ts
> +  analyzeNgModules = analyzeNgModules;
I changed the PR to use a spy. I would rather use a spy because I think we should test that we handle errors from analysis generally, not committing to a specific analysis error. Lmk what you think.

2020-05-15 00:09 UTC, ayazhafiz commented on packages/language-service/test/typescript_host_spec.ts
> +    // First create a TypescriptHost with empty script names
See comment above

2020-06-01 01:37 UTC, ayazhafiz commented
ptal @kyliau. The error messages we get from resolution failure would make great diagnostics, so I think we should look into propagating it from the compiler.

2020-06-01 18:35 UTC, kyliau commented on packages/language-service/src/typescript_host.ts
> +  private lastAnalysisSucceeded = true;
Is there any reason why this flag is needed? I think the code would work without it.

2020-06-01 19:35 UTC, ayazhafiz commented on packages/language-service/src/typescript_host.ts
> +  private lastAnalysisSucceeded = true;
yeah sorry, an artifact of when i was doing the spy thing and didn't update source files

2020-06-01 20:58 UTC, kyliau approved these changes
Thank you for fixing this!

2020-06-03 22:56 UTC, closed without merging