refactor(core): assert TNode is not a container when setting attribute on element
angular/angular pull request #37111
Opened 2020-05-14 16:41 UTC by atscott

This PR provides a more helpful error than the one currently present:
`el.setAttribute is not a function`. It is not valid to have directives with host bindings
on `ng-template` or `ng-container` nodes. VE would silently ignore this, while Ivy
attempts to set the attribute and throws an error because these are comment nodes
and do not have `setAttribute` functionality.

It is better to throw a helpful error than to silently ignore this because
putting a directive with host binding on an `ng-template` or `ng-container` is most often a mistake.
Developers should be made aware that the host binding will have no effect in these cases.

Note that an error is already thrown in Ivy, as mentioned above, so this
is not a breaking change and can be merged to both master and patch.

Resolves #35994

2020-05-14 16:48 UTC, pkozlowski-opensource commented
@atscott thnx for taking a stab at it! I must say that I was on a fence regarding throwing vs. silently ignoring (as VE does). I think that your arguments in the PR description convince me so I'm fine with taking the direction you are proposing here.

Now, the change in this PR looks fine to me, after a short scan, but I think that we should cover more similar cases here (otherwise we will loose context over time). What I'm mostly talking about here are:
* host listeners
* property bindings (those would just nothing I guess)

WDYT?

2020-05-14 17:05 UTC, atscott commented
Hey @pkozlowski-opensource - That's a good point and I do think we should also take a look at host listeners and property bindings. One thing that we need to consider with those is that if there isn't already an error being thrown, it would be a breaking change to throw a new error. If that's the case, I would want this to be merged separately and we can put something in the backlog for a v11 follow-up.

2020-05-14 17:10 UTC, pkozlowski-opensource commented
> One thing that we need to consider with those is that if there isn't already an error being thrown, it would be a breaking change to throw a new error.

Totally! I _think_ that the error will be thrown in case of listeners (as you need to do `comment. addEventListener()` which I believe will fail. For a property binding I think it will be silent (no error) as the operation is `comment[prop] = val`. 

How about adding tests for the 2 above cases and seeing what happens?

2020-05-14 17:16 UTC, pkozlowski-opensource requested changes
Marking as "Request changes" based on https://github.com/angular/angular/pull/37111#issuecomment-628757168

2020-05-14 17:46 UTC, AndrewKushnir commented on packages/core/src/render3/node_assert.ts
> +      message ?
We can probably use nullish coalescing operator here?
```
assertEqual(
      found, false,
      message ?? `Should not be one of ${types.map(typeName).join(', ')} but got ${typeName(tNode.type)}`);
```

2020-05-14 18:16 UTC, atscott commented
[Ivy presubmit](https://test.corp.google.com/ui#id=OCL:311550660:BASE:311550681:1589474935895:3369f186)

With regards to property bindings, I think this is already an error of the form `Can't bind to 'X' since it isn't a known property of 'ng-template'`.

For host listeners, the runtime doesn't currently differentiate between `HostListener` and a listener added in the template (or even synthetic listeners, for that matter). All listeners share the `listenerInternal` implementation, which allows `TNodeType` `Element`, `Container`, and `ElementContainer`
https://github.com/angular/angular/blob/b2a332525821709d187d63a20e3055e9f2718718/packages/core/src/render3/instructions/listener.ts#L129-L131
It is valid to put a listener on an `ng-template` or `ng-container` for the purposes of listening to directive outputs https://github.com/angular/angular/blob/b2a332525821709d187d63a20e3055e9f2718718/packages/core/test/acceptance/directive_spec.ts#L518-L558
It may be useful to warn (or error) when the tNode type is `Container|ElementContainer` and`tNode.outputs === null || tNode.outputs[eventName] === undefined`. This would mean there was a listener put on a container and there is no matching directive output. Maybe this should be a  follow up PR?

2020-05-14 20:32 UTC, AndrewKushnir approved these changes
LGTM 👍 +1 to take care of other use-cases as the next step (and a separate PR) as Andrew suggested in https://github.com/angular/angular/pull/37111#issuecomment-628804910.

2020-06-02 13:29 UTC, pkozlowski-opensource reviewed
@atscott I did another pass on this PR today and left a couple of nit comments (see inline). 

I'm fine if we take next steps in a separate PR as long as we've got a GitHub / JIRA issue to track the remaining work. As things stand today we are very inconsistent between attrs / props and ivy / VE. Here is a stackblitz illustrating what happens with properties: https://stackblitz.com/edit/angular-wmck8s?file=src/app/app.module.ts

2 things to notice:
* `<ng-template>` and `<ng-container>` behave differently (!)
* the behaviour is different from VE (it systematically throws).

Personally I believe that we should unify what happens for attars and props as otherwise things are super - confusing for our users and I believe that it would be better to do all in this PR as we would have all the context / use-cases in front of us.

WDYT?

2020-06-02 13:29 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/host_binding_spec.ts
> +      expect(() => comp.detectChanges()).toThrowError(/ASSERTION ERROR.*/);
nit: I would love to see an assert on the actual error message here.

2020-06-02 13:29 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/host_binding_spec.ts
> +      expect(() => comp.detectChanges()).toThrowError(/ASSERTION ERROR.*/);
same as above, would love to see assert on the error message

2020-06-02 13:29 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/host_binding_spec.ts
> +    @Directive({selector: '[hostAtt]', host: {'static': 'attr', '[attr.dynamic]': '"dynamic"'}})
Could we have 2 separate directives (one with a static and another with a bound attribute)? As things stand today it is not clear if the failure occurs because of the static attr or a bound attr (especially that we don't assert on error messages - see my other comment).

2020-06-03 16:10 UTC, pkozlowski-opensource approved these changes
The change LGTM but CI is read, so it needs cleanup

2020-06-06 00:41 UTC, IgorMinar approved these changes
LGTM 

Reviewed-for: size-tracking

2020-06-08 18:13 UTC, jelbourn approved these changes
LgTM

2020-06-08 18:19 UTC, atscott commented
merge assistance: pullapprove seems to be all kinds of messed up

2020-06-08 18:21 UTC, closed without merging

2020-06-15 08:08 UTC, Prashanth-P-Prabhu commented
Is this change available in release 9.1.11?

2020-06-15 16:09 UTC, atscott commented
Hi @Prashanth-P-Prabhu - this change was merged to the `10.0.x` branch and but not `9.1.x`. Because it's only an improvement on the error being reported and it's not a bug fix, we didn't think it necessary to also cherry pick it to `9.1`.