fix(compiler-cli): use ModuleWithProviders type if static eval fails
angular/angular pull request #37126
Opened 2020-05-15 00:56 UTC by alxhub

When the compiler encounters a function call within an NgModule imports
section, it attempts to resolve it to an NgModule-annotated class by
looking at the function body and evaluating the statements there. This
evaluation can only understand simple functions which have a single
return statement as their body. If the function the user writes is more
complex than that, the compiler won't be able to understand it and
previously the PartialEvaluator would return a "DynamicValue" for
that import.

With this change, in the event the function body resolution fails the
PartialEvaluator will now attempt to use its foreign function resolvers to
determine the correct result from the function's type signtaure instead. If
the function is annotated with a correct ModuleWithProviders type, the
compiler will be able to understand the import without static analysis of
the function body.

2020-05-15 12:28 UTC, JoostK requested changes
I believe this would address #36415 (FW-2048) and make #14410 obsolete.

2020-05-15 12:28 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts
> +                className} is not a reference: ${entry!.constructor.name}`);
This seems to me like a dangerous change to make, given that `entry` could legitimately be `null`/`undefined`.

2020-05-15 12:28 UTC, JoostK commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +            export function notStaticallyAnalyzable(): ModuleWithProviders<SomeModule> {
How about adding a test where the return type is missing. We can then assert on the insightful diagnostic that should be reported by the FFR (i.e. [here](https://github.com/angular/angular/blob/b07b7c9f3e653408fdedba258778fd4cc8003535/packages/compiler-cli/src/ngtsc/annotations/src/ng_module.ts#L507-L511)) which would address the poor UX that we had until this change.

2020-05-15 17:43 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +            export function notStaticallyAnalyzable(): ModuleWithProviders<SomeModule> {
Oh, that's an interesting idea. Will do!

2020-05-15 18:08 UTC, JoostK commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +            export function notStaticallyAnalyzable(): ModuleWithProviders<SomeModule> {
It can still occur when someone leaves off the return type altogether.

2020-05-20 18:06 UTC, JoostK approved these changes

2020-05-20 23:04 UTC, alxhub commented
[Presubmit](http://test/OCL:312572515:BASE:312572747:1590015639100:10da24d1)

2020-06-01 22:26 UTC, alxhub commented
[Presubmit](http://test/OCL:312572515:BASE:314214782:1591050283518:7c59689f)

2020-06-03 20:23 UTC, closed without merging