docs: Initial commit of update guide for v10 release.
angular/angular pull request #37152
Opened 2020-05-16 01:02 UTC by aikidave

This update includes modifications to the navigation.json file to
remove unneeded migration guides.

TODO: Redirects from v9 topics to v10; links to removed migration
guides need to point to v9.angular.io.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
No documentation for updating to v10.

Issue Number: N/A

## What is the new behavior?
Update documentation to include Updating to version 10 guide.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-05-16 01:10 UTC, mary-poppins commented
You can preview a5b2857 at https://pr37152-a5b2857.ngbuilds.io/.

2020-05-20 21:16 UTC, kara requested changes
Thanks for this! Some suggestions below

2020-05-20 21:16 UTC, kara commented on aio/content/guide/updating-to-version-10.md
> +* `UrlMatcher` can now return `null` values. [PR 36402](https://github.com/angular/angular/pull/36402).
Nit: Should we be consistent with "PR" vs "See PR"?

```suggestion
* `UrlMatcher` can now return `null` values. See [PR 36402](https://github.com/angular/angular/pull/36402).
```

2020-05-20 21:16 UTC, kara commented on aio/content/guide/updating-to-version-10.md
> +
Top breaking change should be the removal of TS 3.6, 3.7, and 3.8 support

```suggestion
* Typescript 3.6, 3.7, and 3.8 are no longer supported. Please update to Typescript 3.9.
```

2020-05-20 21:16 UTC, kara commented on aio/content/guide/updating-to-version-10.md
> +In Version 9, Angular Ivy is the default rendering engine. If you haven't heard of Ivy, you can read more about it in the [Angular Ivy guide](guide/ivy).
```suggestion
Since version 9, Angular Ivy is the default rendering engine. If you haven't heard of Ivy, you can read more about it in the [Angular Ivy guide](guide/ivy).
```

2020-06-08 19:08 UTC, clydin commented on aio/content/navigation.json
>                "title": "Optional Migrations",
I think "Optional" is incorrect here.  Any migration listed in the [migration collection for core](https://github.com/angular/angular/blob/779344012a15194c7d4895faa8ee5bf8d99af424/packages/core/schematics/migrations.json) will always be run when performing an update.

2020-06-15 18:09 UTC, aikidave commented on aio/content/navigation.json
>                "title": "Optional Migrations",
We chose this wording for the v9 release. If you think we should reconsider it, could you file an issue about it? I'll raise it with the team and we can talk about changing it for the next release (v11).

2020-06-15 18:51 UTC, kara approved these changes

2020-06-19 23:05 UTC, IgorMinar approved these changes
lgtm!

2020-06-19 23:05 UTC, IgorMinar commented on aio/content/guide/updating-to-version-10.md
> +| browser support               | [`IE 9 and 10`](/guide/deprecations#ie-9-10)                                                     | <!--v10--> v11 |
```suggestion
| browser support               | [`IE 9, 10, and IE Mobile`](/guide/deprecations#ie-9-10-and-ie-mobile-support)                                                     | <!--v10--> v11 |
```

2020-06-19 23:14 UTC, aikidave commented on aio/content/navigation.json
>                "title": "Optional Migrations",
after talking with Igor, we're going with "Migrations". :)

2020-06-19 23:15 UTC, IgorMinar reviewed
These changes might still need to be incorporated into the updating-to-version-10.md from deprecations.md:

- https://github.com/angular/angular/commit/75218342967591627ee44b73999a4cfd52fb5470#diff-604f1ef235cce99ae3ac97707a845582
- https://github.com/angular/angular/commit/9dbb30f884dfedc758df1efeaf79c826c51fd1c7#diff-604f1ef235cce99ae3ac97707a845582
- https://github.com/angular/angular/commit/420b9be1c14ec6900692b641a3d89b99eb9c6e5b#diff-604f1ef235cce99ae3ac97707a845582
- https://github.com/angular/angular/commit/12f2101d08e42715a408f2af401601af8f8cbc2c#diff-604f1ef235cce99ae3ac97707a845582
- https://github.com/angular/angular/commit/75218342967591627ee44b73999a4cfd52fb5470#diff-604f1ef235cce99ae3ac97707a845582

2020-06-19 23:15 UTC, IgorMinar commented on aio/content/guide/updating-to-version-10.md
> +| `@angular/core`               | [`WrappedValue`](/guide/deprecations#core)                                                       | <!--v10--> v12 |
```suggestion
| `@angular/core`               | [`WrappedValue`](/guide/deprecations#wrapped-value)                                                       | <!--v10--> v12 |
```

2020-06-19 23:24 UTC, IgorMinar reviewed
Please add these three items to the update guide (and ignore my previous comment):
- https://next.angular.io/guide/deprecations#deprecated-cli-apis-and-options
- https://next.angular.io/guide/deprecations#style-sanitization-for-style-and-styleprop-bindings
- https://next.angular.io/guide/deprecations#esm5-and-fesm5-code-formats-in-angular-npm-packages

2020-06-22 22:45 UTC, mary-poppins commented
You can preview 3a5e680 at https://pr37152-3a5e680.ngbuilds.io/.

2020-06-22 23:04 UTC, mary-poppins commented
You can preview c25fbf2 at https://pr37152-c25fbf2.ngbuilds.io/.

2020-06-22 23:35 UTC, IgorMinar commented on aio/content/guide/updating-to-version-10.md
> +* [Migrating `ModuleWithProviders`](guide/migration-module-with-providers)
this list is incomplete and should feature all the migrations that we added recently

2020-06-23 00:16 UTC, IgorMinar commented on aio/content/guide/updating-to-version-10.md
> +* [Migrating `ModuleWithProviders`](guide/migration-module-with-providers)
let's defer this update until we have all of the migration docs in, and then we'll send one PR to update the navigation as well as this list. thanks.

2020-06-23 00:22 UTC, IgorMinar commented
I fixed the pullapprove config issue, rebased, and force-pushed.

2020-06-23 00:32 UTC, mary-poppins commented
You can preview 04d1783 at https://pr37152-04d1783.ngbuilds.io/.

2020-06-23 18:09 UTC, mary-poppins commented
You can preview 4e8852c at https://pr37152-4e8852c.ngbuilds.io/.

2020-06-23 18:19 UTC, IgorMinar commented
merge-assistance: the CI failure is unrelated and already tracked in log.angular.io as a known issue.

2020-06-23 18:57 UTC, closed without merging