feat(core): update TestModuleMetadata typings
angular/angular pull request #37179
Opened 2020-05-18 11:29 UTC by fvoska

Update TestModuleMetadata typings to be stricter and in-line with
NgModule interface typings.

Issue Close #37178

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Current `TestModuleMetadata` were loose which could lead to hard-to-pin-down issues in tests.

## What is the new behavior?
`TestModuleMetadata` has been update to be stricter and in-line with `NgModule` interface.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

This should not be a breaking change. It is a breaking change only if some tests used incorrect TestModuleMetadata configuration.

## Other information
Related issue: https://github.com/angular/angular/issues/37178

2020-05-18 11:33 UTC, fvoska commented
@googlebot I fixed it.

2020-05-18 11:43 UTC, fvoska commented
@googlebot I consent.

2020-05-18 11:43 UTC, fvoska commented
@googlebot I consent.

2020-05-18 11:45 UTC, fvoska commented
@googlebot I consent.

2020-05-18 21:26 UTC, AndrewKushnir commented
Hi @fvoska, thanks for creating this PR 👍 

The overall direction of the change looks correct to me. There are some type conflicts in R3TestBed (Ivy version of TestBed), [see this failing test suite](https://circleci.com/gh/angular/angular/714071). Could you please look at these issues? Please let us know if you need any assistance.

Note: since [TestModuleMetadata](https://angular.io/api/core/testing/TestModuleMetadata) is a part of the public API, updating the type is a breaking change. Once the CI-related issues are resolved (and the changes are finalized), we would need to estimate the amount of effort that would be required to land this change internally (we may need to update the code internally to make this change compatible in Google codebase).

Thank you.

2020-06-12 04:45 UTC, IgorMinar requested changes
Thanks for the PR @fvoska. I second what @AndrewKushnir wrote above.

This looks like a worthy change, but it needs a lot more work to get all the tests to pass and then we need to figure out how to roll this out with enough developer support so that it's not perceived as a hard breaking change. @fvoska are you interested in taking that work on?

2020-06-12 05:42 UTC, fvoska commented
Hi @IgorMinar, I will take up the task, I just didn't have the tome lately :)

2020-11-17 18:58 UTC, mhevery commented
Closing as this PR seems to have been abandoned. Feel free to reopen.

2020-11-17 18:58 UTC, closed without merging