docs(api): remove api-body width for wide screens
angular/angular pull request #37197
Opened 2020-05-19 10:21 UTC by abbeboa

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 27296

## What is the new behavior?
Removed hard coded width for api-body. Can now use full width of wide screens.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-05-19 10:24 UTC, abbeboa commented
@googlebot I signed it!

2020-05-19 13:07 UTC, gkalpak requested changes
Thx for submitting a pull request, @abbeboa!
I do not think this is the right fix and more importantly I am not sure whether we want to fix this at all (see my comment below). More discussion is needed.

cc @sjtrimble

2020-05-19 13:07 UTC, gkalpak commented on aio/tools/transforms/templates/api/base.template.html
> +  <div class="content">
FWIW, I am not sure this is something we want to do (for example there have been discussions about doing the opposite: #24707). @sjtrimble has to chime in.

In any case, if we decided to do it, remiving the `api-body` class would _not_ be the way to go (since other styles depend on it). We would change the `.api-body` styles instead: [aio/src/styles/2-modules/_api-pages.scss][1]

[1]: https://github.com/angular/angular/blob/cf7dd410a159fbce0e5733c4cefb1f9a63b1347d/aio/src/styles/2-modules/_api-pages.scss#L1-L2

2021-01-15 02:48 UTC, AndrewKushnir commented
Closing this PR due to the lack of response and based on George's comment above. Please reopen if needed. Thank you.

2021-01-15 02:48 UTC, closed without merging