refactor: move `hover` into a proper `@media` hover
angular/angular pull request #37320
Opened 2020-05-28 11:47 UTC by sonukapoor

This commit moves the contributor hover into the `@media(hover:hover)`
query. This will help to identify if the user's primary input mechanism
can hover over elements.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2020-06-03 23:03 UTC, mary-poppins commented
You can preview c8b6566 at https://pr37320-c8b6566.ngbuilds.io/.

2020-06-03 23:22 UTC, gkalpak requested changes
Thx, @sonukapoor! Can you please change the commit message to `fix(docs-infra): ...`?

2020-06-03 23:22 UTC, gkalpak commented on aio/src/styles/2-modules/_contributor.scss
> +  @media(hover:hover) {
For consistency:

```suggestion
  @media (hover) {
```

2020-06-05 11:39 UTC, sonukapoor commented on aio/src/styles/2-modules/_contributor.scss
> +  @media(hover:hover) {
@gkalpak Done. Please re-review. Thanks

2020-06-05 11:50 UTC, mary-poppins commented
You can preview c3da216 at https://pr37320-c3da216.ngbuilds.io/.

2020-06-05 17:08 UTC, gkalpak requested changes

2020-06-05 17:08 UTC, gkalpak commented on aio/src/styles/2-modules/_contributor.scss
> +  @media(hover) {
```suggestion
  @media (hover) {
```

2020-06-05 17:29 UTC, mary-poppins commented
You can preview 08a089f at https://pr37320-08a089f.ngbuilds.io/.

2020-06-05 17:42 UTC, sonukapoor commented on aio/src/styles/2-modules/_contributor.scss
> +  @media(hover) {
Done.

2020-06-05 20:13 UTC, gkalpak approved these changes
Thx for making the changes, @sonukapoor. Can you please squash the commits into one and make sure CI is happy.

2020-06-05 21:15 UTC, mary-poppins commented
You can preview c7207a5 at https://pr37320-c7207a5.ngbuilds.io/.

2020-06-15 11:14 UTC, sonukapoor commented
@gkalpak Can you review this again? I think this is good to be merged?

2020-06-15 16:39 UTC, closed without merging