fix(router): fragment can be null
angular/angular pull request #37336
Opened 2020-05-28 20:40 UTC by MatthiasKunnen

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
`ActivatedRoute.fragment` is typed as `Observable<string>` but can emit both `null` and `undefined` due to incorrect non-null assertions. 

Issue Number: #23894, #34197.

## What is the new behavior?
The non-null assertions have been removed and fragment has been retyped to `string | null`. `undefined` fragments will no longer occur.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

BREAKING CHANGE:
Strict null checks will report on fragment potentially being null.
Migration path: add null check.

## Other information
Fixes #23894, #34197.
Supersedes #37334.

2020-05-28 20:44 UTC, MatthiasKunnen commented
@atscott, this is the superseding PR.

2020-05-29 12:09 UTC, MatthiasKunnen commented
I just updated the golden file, forgot that yesterday.

2020-05-29 15:23 UTC, atscott requested changes
Thanks for fixing this and putting the breaking change footer in! LGTM with some small change requests.

As this is a breaking change, we'll need to wait until v11

2020-05-29 15:23 UTC, atscott commented on packages/router/src/create_url_tree.ts
> +    queryParams?: Params|null, fragment?: string|null): UrlTree {
Could you revert these changes that make `queryParams` and `fragment` optional? This wasn't intended to be part of the change. The case against `undefined` is that you can unintentionally forget to set them. `null` has to be deliberately set where `undefined` could be a mistake.

The mistake reported in https://github.com/angular/angular/issues/34197 is really that the `createUrlTree` is called with the null assertion operator for `fragment` and `queryParams` and should instead convert those `undefined` values to `null`.

2020-05-29 15:23 UTC, atscott commented on packages/router/src/url_tree.ts
> +      public fragment: string|null = null) {}
Please revert this `null` default as well.

2020-05-29 15:41 UTC, MatthiasKunnen commented
Made changes as requested

2020-05-29 15:46 UTC, atscott approved these changes

2020-05-29 15:48 UTC, atscott commented
Ah, looks like your second commit doesn't have a commit message body that satisfies the 100 character requirement. Maybe squash your commits into one and just use the first?

2020-05-29 15:48 UTC, atscott commented
Adding `blocked` flag, as we'll need a migration plan and have to wait for v11.

2020-06-29 21:41 UTC, jelbourn approved these changes
LGTM

Reviewed-for: public-api

2020-11-20 16:38 UTC, MatthiasKunnen commented
Is there a reason this was not part of the Angular 11 release?

2020-11-20 17:27 UTC, atscott commented
Hi @MatthiasKunnen, there's no reason other than that it got lost. We had many efforts to create migrations for breaking changes like this one and just missed it.

2020-11-20 20:58 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2020-11-23 07:51 UTC, petebacondarwin approved these changes
Reviewed-for: public-api

As @atscott points out, this needs a migration. Can you take a look at https://github.com/angular/angular/pull/39009 for an example of how to do this. Perhaps you could add such a migration to this PR?

2020-11-23 19:02 UTC, MatthiasKunnen commented
I would be willing to attempt a migration, however, wouldn't it be a problem if the migration silently added a non-null assertion which hides a potential crash? What I'm saying is wouldn't it be better if there are compile errors after upgrade to the next major and people see the cause and add checks accordingly?

2021-01-16 10:17 UTC, MatthiasKunnen commented
Resolved conflicts

2021-03-05 16:17 UTC, crisbeto commented
Migration PR: https://github.com/angular/angular/pull/41092.

2021-03-15 19:32 UTC, atscott commented
[global presubmit](https://test.corp.google.com/ui#id=OCL:362994416:BASE:362970560:1615835395194:c0a99d7b)

2021-03-19 20:55 UTC, atscott commented
[global presubmit](https://test.corp.google.com/ui#id=OCL:363658669:BASE:363963569:1616187133876:217c5ea5)

2021-03-19 20:58 UTC, atscott commented
caretaker note: please merge and sync this one on its own. g3 cleanup has been performed but things may have changed since then.

2021-03-19 20:58 UTC, atscott approved these changes
reviewed-for: public-api

2021-03-20 15:28 UTC, MatthiasKunnen commented
If you need me to do anything; rebase, ... let me know

2021-03-22 17:02 UTC, closed without merging