fix(common): prevent duplicate URL change notifications
angular/angular pull request #37404
Opened 2020-06-02 20:28 UTC by LayZeeDK

Prevent duplicate notifications for URL change listeners using `Location#onUrlChange`.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
When two URL change listeners are registered, the first one will receive duplicate URL change notifications.

Issue Number: N/A

## What is the new behavior?
When two URL change listeners are registered, both of them will only receive a single notifications when the URL changes.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Cc @aaronfrost

2020-06-02 22:14 UTC, LayZeeDK commented
Does it make sense to add an `ngOnDestroy` lifecycle hook to unsubscribe from the `_onUrlChangeSubscription` in the `Location` service? Would this make a difference to multiple applications on the same page? Is there a use case for applications being shut down after bootstrapping them? Hot Module Replacement maybe?

2020-06-03 11:04 UTC, JoostK commented
> Does it make sense to add an `ngOnDestroy` lifecycle hook to unsubscribe from the `_onUrlChangeSubscription` in the `Location` service? Would this make a difference to multiple applications on the same page? Is there a use case for applications being shut down after bootstrapping them? Hot Module Replacement maybe?

It looks like it won't be necessary to teardown the subscription manually, as the source is an `EventEmitter` that is local to the instance, and all referenced memory is also local to the instance. As soon as the instance is no longer referenced from other places, it will become eligible for the GC to collect.

2020-06-03 11:10 UTC, JoostK commented on packages/common/test/location/location_spec.ts
> +             let notificationCount = 0;
I would move this to before `incrementChangeListener` as it's referenced in that callback function.

2020-06-03 11:10 UTC, JoostK commented on packages/common/test/location/location_spec.ts
> +             expect(notificationCount).toBe(1);
Consider adding this assertion to above `simulatePopState` with an expected count of 0, making it more explicit when the counter is expected to be updated.

2020-06-03 13:21 UTC, LayZeeDK commented on packages/common/test/location/location_spec.ts
> +             let notificationCount = 0;
I like to make my declarations follow hoisting, but I can change the functions to lambda expressions to make us both happy 🙂

2020-06-03 13:22 UTC, LayZeeDK commented on packages/common/test/location/location_spec.ts
> +             expect(notificationCount).toBe(1);
In the same test case, right?

2020-06-03 15:13 UTC, JoostK commented on packages/common/test/location/location_spec.ts
> +             let notificationCount = 0;
I have the opposite preference, apparently :-) I had looked into using an arrow function as well, but noticed other tests are also written with a named function so the current state looks good to me.

2020-06-03 21:15 UTC, atscott requested changes
👍 Thanks for this fix! Only some small nits in the comments

2020-06-03 21:15 UTC, atscott commented on packages/common/src/location/location.ts
> +  _urlChangeSubscription?: SubscriptionLike;
Is there any reason this can't be `private` instead of `internal`?

2020-06-03 21:15 UTC, atscott commented on packages/common/test/location/location_spec.ts
> +             let notificationCount = 0;
```suggestion
       () => {
       const location = TestBed.get(Location);
       const locationStrategy = TestBed.get(MockLocationStrategy);
             let notificationCount = 0;
```
nit: can we update this to use the newer `TestBed` APIs?

2020-06-03 21:18 UTC, atscott commented
[presubmit](https://test.corp.google.com/ui#id=OCL:314602448:BASE:314602915:1591219093378:851c605b)

2020-06-04 20:19 UTC, LayZeeDK commented on packages/common/src/location/location.ts
> +  _urlChangeSubscription?: SubscriptionLike;
I'm trying to follow the code style of this class. If we want to change the access modifiers to `private`, shouldn't we do them all?

2020-06-04 20:19 UTC, LayZeeDK commented on packages/common/test/location/location_spec.ts
> +             let notificationCount = 0;
I'm trying to follow the code style of this test suite. If we want to use `TestBed`, shouldn't we change all the test cases? Also, we should use `TestBed.inject`.

2020-06-04 21:39 UTC, atscott commented on packages/common/src/location/location.ts
> +  _urlChangeSubscription?: SubscriptionLike;
Would you mind still making this change for the new item and contributing a follow-up PR to update the others? I don't think that we should continue bad/old conventions just for the sake of consistency.

2020-06-04 21:39 UTC, atscott commented on packages/common/test/location/location_spec.ts
> +             let notificationCount = 0;
Right, use `TestBed.inject` instead. Also, same comment as above - please still update this one to the newer style and then follow up with a PR to update refactor the others. Thanks!

2020-06-04 21:52 UTC, LayZeeDK commented on packages/common/src/location/location.ts
> +  _urlChangeSubscription?: SubscriptionLike;
Got it. We still want the underscore prefix though, right?

2020-06-04 22:01 UTC, atscott commented on packages/common/src/location/location.ts
> +  _urlChangeSubscription?: SubscriptionLike;
Yep, that convention hasn't changed AFAIK

2020-06-04 22:03 UTC, LayZeeDK commented
Good to go.

I'll open another PR afterwards to:
- Prefer `private` over `@internal`
- Prefer `TestBed.inject` over `inject`

in these files.

2020-06-04 22:14 UTC, atscott approved these changes

2020-06-04 23:19 UTC, LayZeeDK commented
I think you have to remove the `PR action: review` label, @atscott 🙂

2020-06-04 23:45 UTC, closed without merging