docs: add module/target compiler option migration docs
angular/angular pull request #37429
Opened 2020-06-04 02:15 UTC by clydin

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

This adds documentation for the tooling migration `update-module-and-target-compiler-options`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-06-04 02:26 UTC, mary-poppins commented
You can preview 424e20f at https://pr37429-424e20f.ngbuilds.io/.

2020-06-04 18:46 UTC, mary-poppins commented
You can preview f87ff0c at https://pr37429-f87ff0c.ngbuilds.io/.

2020-06-05 19:00 UTC, mary-poppins commented
You can preview 248dcdc at https://pr37429-248dcdc.ngbuilds.io/.

2020-06-08 11:10 UTC, alan-agius4 commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +For the protractor builder (`ng e2e` for applications), `module` is changed to `es2018` from `es5`.
`module` -> `target`

2020-06-08 12:41 UTC, alan-agius4 approved these changes
One small NIT.

2020-06-08 17:02 UTC, mary-poppins commented
You can preview bd78b9e at https://pr37429-bd78b9e.ngbuilds.io/.

2020-06-16 23:16 UTC, IgorMinar requested changes
Thanks for the draft! I however think we can make this guide easier to read by writing it from the perspective of a reader by reorganizing and rewording some parts of this doc as suggested in individual comments below.

2020-06-16 23:16 UTC, IgorMinar commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +Both `esnext` and `es2020` values provide support for dynamic imports which are used for lazy routing.
While this is partly true, the person reading this doesn't know this setting actually enables lazy routing (in fact more generally in enables dynamic import support).

2020-06-16 23:16 UTC, IgorMinar commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +## Can `esnext` still be used instead of `es2020`?
```suggestion
## Why `"es2020"` instead of `"esnext"`?
```

2020-06-16 23:16 UTC, IgorMinar commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +unsupported features during compilation.  This could result in either build-time or run-time errors.
How about something like this:
```suggestion

In TypeScript 3.9 the behavior of the TypeScript compiler controlled by the [`module`](https://www.typescriptlang.org/v2/en/tsconfig#module) is the same with both `"esnext"` and `"es2020"` values.
This can however change in the future where the `"esnext"` option could evolve in a backwards incompatible ways resulting in build-time or run-time errors during TypeScript update.
This could result in undesirable instability which can be avoided by using the `"es2020"` option whose behavior is not going to change any more.
```

2020-06-17 14:37 UTC, clydin commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +Unless otherwise noted, changes are only made if the existing value matches an expected value.
That wording was actually intentional.  The migration will not make any changes unless it finds a particular value already present in the option (the old generated value).  I believe this is to prevent the migration from breaking intentional changes to the configuration.  I can expand on that here.

2020-06-17 14:49 UTC, clydin commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +These changes synchronize the values of these options with new projects.
Removed.

This was intended to lead into the next sentence regarding supportability and sustainment.
I think syncing existing projects with new release is somewhat common.  There's actually a project dedicated to tracking the changes between releases to make it easy for users to adjust their projects:
https://github.com/cexbrayat/angular-cli-diff

2020-06-17 17:25 UTC, clydin commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +For the protractor builder (`ng e2e` for applications), `target` is changed to `es2018` from `es5`.
I'll try it out so we can see what it looks like.

2020-06-19 00:02 UTC, mary-poppins commented
You can preview 6b23bb5 at https://pr37429-6b23bb5.ngbuilds.io/.

2020-06-19 16:08 UTC, aikithoughts reviewed
A few suggestions for you to consider. Thanks!

2020-06-19 16:08 UTC, aikidave commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +## Why is this migration necessary?
```suggestion
## Purpose
```
Editing for conciseness.

2020-06-19 16:08 UTC, aikidave commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +This provides improvements to supportability and the long-term sustainment of projects.
```suggestion
This migration provides improvements to supportability and the long-term sustainability of projects.
```

But what is the difference between supportability and sustainability here?

2020-06-19 16:08 UTC, aikidave commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +For the functionality that executes on Node.js, such as universal and protractor, the new settings
```suggestion
For the functionality that executes on Node.js, such as universal and protractor, the new settings
```
Aren't Universal and Protractor proper names? If so, we should capitalize them.

2020-06-19 16:08 UTC, aikidave commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +provide performance and debug/troubleshooting benefits as well.
```suggestion
provide performance and debug and troubleshooting benefits as well.
```

2020-06-19 16:08 UTC, aikidave commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +The minimum Node.js version for the Angular CLI (v10.13) supports features present up to ES2018.
```suggestion
The minimum Node.js version for the Angular CLI (v10.13) supports features in ES2018 and earlier.
```
I'm not sure what "supports features present up to ES2018" means. Is this suggestion correct?

2020-06-19 16:08 UTC, aikidave commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +By targetting later ES versions, less code is transformed which allows newer features to be used directly.
```suggestion
By targeting later ES versions, the compiler transforms less code and can use newer features directly.
```
Transformed by and used by what? I think its the compiler.

2020-06-19 16:08 UTC, aikidave commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +Since zone.js does not support native async/await, the universal builds must still target ES2016.
```suggestion
Since zone.js does not support native `async` and `await`, the universal builds still target ES2016.
```

2020-06-19 16:08 UTC, aikidave commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +## Why `"es2020"` instead of `"esnext"`?
```suggestion
## `"es2020"` and `"esnext"`
```

2020-06-19 16:08 UTC, aikidave commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +In TypeScript 3.9 the behavior of the TypeScript compiler controlled by `module` is the same with both `"esnext"` and `"es2020"` values.
```suggestion
In TypeScript 3.9, the behavior of the TypeScript compiler controlled by `module` is the same with both `"esnext"` and `"es2020"` values.
```

2020-06-19 16:08 UTC, aikidave commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +This can however change in the future where the `"esnext"` option could evolve in a backwards incompatible ways resulting in build-time or run-time errors during TypeScript update.
```suggestion
This behavior can change in the future, because the `"esnext"` option could evolve in a backwards incompatible ways, resulting in build-time or run-time errors during a TypeScript update.
```

2020-06-19 16:08 UTC, aikidave commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +This could result in undesirable instability which can be avoided by using the `"es2020"` option whose behavior is not going to change any more.
```suggestion
As a result, code can become unstable. Using the `"es2020"` option mitigates this risk.
```

2020-06-19 17:17 UTC, clydin commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +Since zone.js does not support native async/await, the universal builds must still target ES2016.
"async/await" is the common term to describe the feature.

2020-06-19 17:18 UTC, clydin commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +## Why `"es2020"` instead of `"esnext"`?
The question form is following the format of the existing migration documentation.

2020-06-19 17:20 UTC, clydin commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +## What does this migration do?
These section headings are common to all migration documentation.
I believe they were intended to be more FAQ-like.

The migration docs are not really guides and eventually should be moved out of their current location but more infrastructure is necessary.  This current state is also why there needs to be an explicit pullaprove line added per migration document.

2020-06-19 17:39 UTC, mary-poppins commented
You can preview 73c7fb6 at https://pr37429-73c7fb6.ngbuilds.io/.

2020-06-19 18:23 UTC, clydin commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +This provides improvements to supportability and the long-term sustainment of projects.
From a systems engineering perspective they are related but different concepts and are generally associated with reliability and maintainability as well.
I'll reduce this to just supportability here though.

2020-06-19 18:40 UTC, mary-poppins commented
You can preview 201b96b at https://pr37429-201b96b.ngbuilds.io/.

2020-06-22 23:05 UTC, IgorMinar approved these changes
the rest looks good to me. thanks!

2020-06-22 23:05 UTC, IgorMinar commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +Workspace base [`tsconfig.base.json`] | `"module"` | `"esnext"` | `"es2020"`
I'll fix this and force-push

2020-06-22 23:16 UTC, aikidave commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +## What does this migration do?
I don't like questions in headings, because I think it makes more work for the users. But I'm happy to take an action item to create a separate PR for this.

2020-06-22 23:20 UTC, aikithoughts approved these changes

2020-06-22 23:21 UTC, IgorMinar commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +Since zone.js does not support native async/await, the universal builds must still target ES2016.
I fixed this.

2020-06-22 23:23 UTC, mary-poppins commented
You can preview 7089064 at https://pr37429-7089064.ngbuilds.io/.

2020-06-22 23:38 UTC, IgorMinar commented on aio/content/guide/migration-update-module-and-target-compiler-options.md
> +Unless otherwise noted, changes are only made if the existing value was not changed from the value previously used by a new project.
"if the existing value was not changed since the project was created." is likely the best.

2020-06-23 00:22 UTC, mary-poppins commented
You can preview 7ced904 at https://pr37429-7ced904.ngbuilds.io/.

2020-06-23 00:25 UTC, IgorMinar commented
I fixed the pullapprove lint failure and force pushed again

2020-06-23 00:26 UTC, IgorMinar approved these changes
Reviewed-for: code-ownership

2020-06-23 00:36 UTC, mary-poppins commented
You can preview 2c09fff at https://pr37429-2c09fff.ngbuilds.io/.

2020-06-23 18:02 UTC, mary-poppins commented
You can preview b0d4672 at https://pr37429-b0d4672.ngbuilds.io/.

2020-06-23 18:10 UTC, IgorMinar commented
merge-assistance: the CI failure is unrelated and already tracked in log.angular.io as a known issue.

2020-06-23 18:58 UTC, AndrewKushnir commented
Hi @clydin, it looks like this PR has a conflict with master branch after merging other docs-related PRs. Could you please rebased and resolve conflicts? Thank you.

2020-06-23 19:15 UTC, mary-poppins commented
You can preview 5160c33 at https://pr37429-5160c33.ngbuilds.io/.

2020-06-23 19:46 UTC, closed without merging