build: update to latest stable Chromium 83.0.4103
angular/angular pull request #37427
Opened 2020-06-03 22:45 UTC by gregmagolan

Also added in detailed instructions of the process to determine the URLs corresponding to Chromium version desired.

NB: updating to latest stable had issues in the past on a per platform basis

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-06-04 02:16 UTC, gregmagolan commented
All green on Circle. @IgorMinar & @josephperrott , this may be a good one to try manually on OSX and Windows; I don't think Windows CI exercises any tests that use the rules_webtesting chromium

2020-06-04 02:18 UTC, gregmagolan commented
The other spot that chrome is controlled is via the puppeteer version; that is easy to update in the root package.json + updating the map in `scripts/puppeteer-chrome-versions.js`:
```
// Mapping of puppeteer releases to their default Chrome version
// derived from https://github.com/puppeteer/puppeteer/blob/master/docs/api.md.
// The puppeteer package.json file contains the compatible Chrome revision such as
// "chromium_revision": "722234" but this does not map easily to the Chrome version
// so we use this mapping here instead.
module.exports = {
  "2.1.1": "80.0.3987.0",
  "2.1.0": "80.0.3987.0",
  "2.0.0": "79.0.3942.0",
  "1.20.0": "78.0.3882.0",
  "1.19.0": "77.0.3803.0",
  "1.17.0": "76.0.3803.0",
  "1.15.0": "75.0.3765.0",
  "1.13.0": "74.0.3723.0",
  "1.12.2": "73.0.3679.0",
};
```
Do you want me to align that version in this PR?

2020-06-04 03:03 UTC, IgorMinar requested changes
Yes. Please align the puppeteer version in this PR and document that process + cross reference it from the documentation you just wrote.

Thank you!

2020-06-04 15:22 UTC, josephperrott commented on dev-infra/browsers/browser_repositories.bzl
> +    # To update to a newer version of Chromium:
Could we move this explanation to a README file?  The write up does a great job of explaining, but its tough to read inline vs markdown.

2020-06-06 00:18 UTC, gregmagolan commented on dev-infra/browsers/browser_repositories.bzl
> +    # To update to a newer version of Chromium:
Done; put the instructions in dev-infra/browsers/README.md

2020-06-06 00:18 UTC, gregmagolan commented
Also updates puppeteer controlled version to match

2020-06-06 00:24 UTC, IgorMinar requested changes
browsers/README.md missing, otherwise LGTM

2020-06-06 00:33 UTC, IgorMinar approved these changes
LGTM after the suggestions are resolved.

2020-06-06 00:33 UTC, IgorMinar commented on dev-infra/browsers/README.md
> +# Chrome browser versions for testing and angular
```suggestion
# Chrome browser versions for testing and Angular
```

2020-06-06 00:33 UTC, IgorMinar commented on dev-infra/browsers/README.md
> +The version of chrome used in tests is determined in a few places.
```suggestion
Within the Angular monorepo, we use Chrome to perform most of the local testing, and rely on Sauce Labs and BrowserStack to do cross-browser testing on our CI.

The version of Chrome used in tests within this monorepo is configured and controlled via `rules_webtesting` and `pupeteer`. We manually keep the configuration of these two tools in sync to create a consistent testing environment across unit, e2e, and integration tests.
```

2020-06-06 00:33 UTC, IgorMinar commented on dev-infra/browsers/README.md
> +# Chrome browser versions for testing in angular
```suggestion
# Browser configuration and versioning for testing of Angular
```

2020-06-06 00:33 UTC, IgorMinar commented on dev-infra/browsers/README.md
> +Bazel `karma_web_test_suit`e and `protractor_web_test_suite` targets will use Chromium provisioned by rules_webtesting. The version of chrome used is specified in the `dev-infra/browsers/browser_repo
```suggestion
Bazel `karma_web_test_suite` and `protractor_web_test_suite` targets will use Chromium provisioned by rules_webtesting. The version of chrome used is specified in the `dev-infra/browsers/browser_repositories.bzl` file. The process of updating the Chrome version in that file consists of several steps:
```

2020-06-06 00:35 UTC, gregmagolan commented on dev-infra/browsers/README.md
> +# Chrome browser versions for testing and angular
Done

2020-06-06 00:40 UTC, gregmagolan commented on dev-infra/browsers/README.md
> +The version of chrome used in tests is determined in a few places.
👍

2020-06-06 00:40 UTC, gregmagolan commented on dev-infra/browsers/README.md
> +# Chrome browser versions for testing in angular
👍

2020-06-06 00:40 UTC, gregmagolan commented on dev-infra/browsers/README.md
> +Bazel `karma_web_test_suit`e and `protractor_web_test_suite` targets will use Chromium provisioned by rules_webtesting. The version of chrome used is specified in the `dev-infra/browsers/browser_repo
👍

2020-06-06 02:27 UTC, gregmagolan commented
Tested locally on OSX: ```INFO: Elapsed time: 1816.460s, Critical Path: 569.21s
INFO: 2426 processes: 1865 darwin-sandbox, 18 local, 543 worker.
INFO: Build completed successfully, 30276 total actions
//dev-infra/commit-message:test                                          PASSED in 0.9s
//integration:cli-hello-world-ivy-compat_test                            PASSED in 258.6s
//integration:cli-hello-world-ivy-minimal_test                           PASSED in 243.2s
//integration:cli-hello-world_test                                       PASSED in 259.9s
//integration:hello_world__systemjs_umd_test                             PASSED in 65.9s
//integration:language_service_plugin_test                               PASSED in 33.5s
//integration:ng_update_test                                             PASSED in 31.3s
//integration:service-worker-schema_test                                 PASSED in 43.8s
//integration:terser_test                                                PASSED in 36.1s
//integration:typings_test_ts39_test                                     PASSED in 36.9s
//modules/benchmarks/src/change_detection/transplanted_views:e2e_chromium PASSED in 6.1s
//modules/benchmarks/src/largeform/ng2:e2e_chromium                      PASSED in 7.9s
//modules/benchmarks/src/largetable/baseline:e2e_chromium                PASSED in 6.8s
//modules/benchmarks/src/largetable/incremental_dom:e2e_chromium         PASSED in 5.8s
//modules/benchmarks/src/largetable/iv:e2e_chromium                      PASSED in 8.3s
//modules/benchmarks/src/largetable/ng2:e2e_chromium                     PASSED in 7.4s
//modules/benchmarks/src/largetable/ng2_switch:e2e_chromium              PASSED in 6.7s
//modules/benchmarks/src/largetable/render3:e2e_chromium                 PASSED in 13.1s
//modules/benchmarks/src/tree/baseline:e2e_chromium                      PASSED in 16.0s
//modules/benchmarks/src/tree/incremental_dom:e2e_chromium               PASSED in 7.6s
//modules/benchmarks/src/tree/iv:e2e_chromium                            PASSED in 10.0s
//modules/benchmarks/src/tree/ng1:e2e_chromium                           PASSED in 11.6s
//modules/benchmarks/src/tree/ng2:e2e_chromium                           PASSED in 11.9s
//modules/benchmarks/src/tree/ng2_next:e2e_chromium                      PASSED in 39.1s
//modules/benchmarks/src/tree/ng2_static:e2e_chromium                    PASSED in 10.2s
//modules/benchmarks/src/tree/ng2_switch:e2e_chromium                    PASSED in 8.8s
//modules/benchmarks/src/tree/render3:e2e_chromium                       PASSED in 9.8s
//modules/playground/e2e_test/async:protractor_tests_chromium            PASSED in 27.5s
//modules/playground/e2e_test/hello_world:protractor_tests_chromium      PASSED in 6.8s
//modules/playground/e2e_test/http:protractor_tests_chromium             PASSED in 9.4s
//modules/playground/e2e_test/jsonp:protractor_tests_chromium            PASSED in 5.5s
//modules/playground/e2e_test/key_events:protractor_tests_chromium       PASSED in 9.3s
//modules/playground/e2e_test/model_driven_forms:protractor_tests_chromium PASSED in 6.2s
//modules/playground/e2e_test/order_management:protractor_tests_chromium PASSED in 4.7s
//modules/playground/e2e_test/person_management:protractor_tests_chromium PASSED in 6.1s
//modules/playground/e2e_test/relative_assets:protractor_tests_chromium  PASSED in 5.6s
//modules/playground/e2e_test/routing:protractor_tests_chromium          PASSED in 8.1s
//modules/playground/e2e_test/sourcemap:protractor_tests_chromium        PASSED in 3.9s
//modules/playground/e2e_test/svg:protractor_tests_chromium              PASSED in 14.6s
//modules/playground/e2e_test/template_driven_forms:protractor_tests_chromium PASSED in 5.9s
//modules/playground/e2e_test/upgrade:protractor_tests_chromium          PASSED in 6.8s
//modules/playground/e2e_test/web_workers/animations:protractor_tests_chromium PASSED in 3.5s
//modules/playground/e2e_test/web_workers/input:protractor_tests_chromium PASSED in 15.0s
//modules/playground/e2e_test/web_workers/kitchen_sink:protractor_tests_chromium PASSED in 50.2s
//modules/playground/e2e_test/web_workers/message_broker:protractor_tests_chromium PASSED in 12.9s
//modules/playground/e2e_test/web_workers/router:protractor_tests_chromium PASSED in 11.3s
//modules/playground/e2e_test/web_workers/todo:protractor_tests_chromium PASSED in 10.9s
//modules/playground/e2e_test/zippy_component:protractor_tests_chromium  PASSED in 12.6s
//packages/animations/browser/test:circular_deps_test                    PASSED in 7.1s
//packages/animations/browser/test:test                                  PASSED in 2.2s
//packages/animations/browser/test:test_web_chromium                     PASSED in 6.0s
//packages/animations/browser/test:testing_circular_deps_test            PASSED in 7.0s
//packages/animations/test:circular_deps_test                            PASSED in 2.8s
//packages/animations/test:test                                          PASSED in 2.5s
//packages/animations/test:test_web_chromium                             PASSED in 5.3s
//packages/bazel/test/ngc-wrapped:flat_module_test                       PASSED in 1.3s
//packages/bazel/test/ngc-wrapped:ngc_test                               PASSED in 6.2s
//packages/benchpress/test:test                                          PASSED in 3.3s
//packages/common/http/test:circular_deps_test                           PASSED in 6.7s
//packages/common/http/test:test                                         PASSED in 5.1s
//packages/common/http/test:test_web_chromium                            PASSED in 6.7s
//packages/common/http/testing/test:circular_deps_test                   PASSED in 5.8s
//packages/common/http/testing/test:test                                 PASSED in 5.4s
//packages/common/http/testing/test:test_web_chromium                    PASSED in 7.7s
//packages/common/test:circular_deps_test                                PASSED in 17.3s
//packages/common/test:test                                              PASSED in 6.8s
//packages/common/test:test_web_chromium                                 PASSED in 10.5s
//packages/common/test:testing_circular_deps_test                        PASSED in 7.3s
//packages/common/upgrade/test:circular_deps_test                        PASSED in 9.1s
//packages/common/upgrade/test:test                                      PASSED in 2.9s
//packages/compiler-cli/integrationtest/bazel/injectable_def/app/test:test PASSED in 6.3s
//packages/compiler-cli/integrationtest/bazel/injector_def/ivy_build/app/test:test PASSED in 4.2s
//packages/compiler-cli/ngcc/test:test                                   PASSED in 39.2s
//packages/compiler-cli/src/ngtsc/annotations/test:test                  PASSED in 3.9s
//packages/compiler-cli/src/ngtsc/core/test:test                         PASSED in 2.1s
//packages/compiler-cli/src/ngtsc/cycles/test:test                       PASSED in 2.1s
//packages/compiler-cli/src/ngtsc/entry_point/test:test                  PASSED in 0.9s
//packages/compiler-cli/src/ngtsc/file_system/test:test                  PASSED in 1.1s
//packages/compiler-cli/src/ngtsc/imports/test:test                      PASSED in 2.8s
//packages/compiler-cli/src/ngtsc/indexer/test:test                      PASSED in 1.9s
//packages/compiler-cli/src/ngtsc/partial_evaluator/test:test            PASSED in 4.9s
//packages/compiler-cli/src/ngtsc/reflection/test:test                   PASSED in 1.2s
//packages/compiler-cli/src/ngtsc/scope/test:test                        PASSED in 2.1s
//packages/compiler-cli/src/ngtsc/shims/test:test                        PASSED in 1.6s
//packages/compiler-cli/src/ngtsc/transform/test:test                    PASSED in 2.1s
//packages/compiler-cli/src/ngtsc/typecheck/test:test                    PASSED in 12.3s
//packages/compiler-cli/src/ngtsc/util/test:test                         PASSED in 4.1s
//packages/compiler-cli/test:perform_compile                     [...]

2020-06-08 16:16 UTC, closed without merging