fix(language-service): show element selectors only in element autocomplete
angular/angular pull request #37430
Opened 2020-06-04 04:14 UTC by kyliau

This commit fixes a bug whereby element in CSS selectors like `form` in
the selector of the `NgForm` directive

```ts
@Directive({
  selector: 'form:not([ngNoForm]):not([formGroup]),ng-form,[ngForm]',
  // ...
})
export class NgForm extends ControlContainer implements Form, AfterViewInit {
```

are inadvertently included in the autocomplete results for a HTML
element. Only component selectors and element selectors in directives
should be included in the results.

In addition, this commit assigns a selector to the `TemplateReference`
class. Without an explicit `selector`, Angular assigns the generic
name `ng-component`.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-06-05 07:55 UTC, JoostK commented
Drive by comment: if you have a directive with selector `'app-directive'`, why wouldn't that classify as valid autocomplete suggestion? AFAIK there isn't much of a difference between directives and components, apart from the fact that components render their view into the host element. Or am I misunderstanding the proposed change here?

2020-06-05 13:59 UTC, ayazhafiz requested changes

2020-06-05 13:59 UTC, ayazhafiz commented on packages/language-service/src/completions.ts
> +  for (const selector of selectors) {
I agree with Joost's comment. In 95% of cases if a directive has an element name selector, the selector also corresponds to an HTML element or a component. But then there are "special" cases like [`ng-form`](https://angular.io/api/forms/NgForm) which is neither a native HTML element or component, but still a valid Angular element name.

Here, could we conditionally set the `kind` of the added result based on whether it is a directive or component?

2020-06-05 21:26 UTC, kyliau commented
@ayazhafiz @JoostK My apologies, I didn't do a good job at explaining the bug, and the test actually adds confusion to the discussion rather than pinpointing the issue.

The problem I'm trying to solve is that, when autocompletion is requested at a position where a HTML element is expected, this is currently the list of items returned:

name | kind
------|------
ng-container | angular element
ng-content | angular element
ng-template | angular element
form | component
option | component
input | component
textarea | component
select | component
ng-form | component
my-app | component
my-comp | component
test-comp | component

We can see that `form`, `option`, `input`, `textarea` and `select` are clearly not components, but they get included because they are part of the selectors in various Directives in `@angular/forms`.

For example, `form` and `ng-form` are extracted from the selector in `NgForm` directive:
https://github.com/angular/angular/blob/17996bf7196c4ad05b34bb752fc9ac0a9ee11f4e/packages/forms/src/directives/ng_form.ts#L92-L99

Note that these are completions for an **external** template, and language service do not provide autocomplete for native HTML elements by design (that's the responsibility of the HTML extension). Therefore, I'd like to remove them from the results. However, since the extraction logic deals solely with the selectors, there is not an easy way to distinguish html elements vs css selectors.

The solution I proposed here is to eliminate directives entirely, which solves the problem, but like both of you pointed out, could also lead to more removals than necessary. What do you think is the best approach here?

2020-06-06 01:08 UTC, ayazhafiz commented
> However, since the extraction logic deals solely with the selectors, there is not an easy way to distinguish html elements vs css selectors.

I think you could filter out selectors that are not only element selectors (with `selector.isElementSelector`) and then check if the the element is an HTML element with the [DomElementSchemaRegistry](https://github.com/angular/angular/blob/master/packages/compiler/src/schema/dom_element_schema_registry.ts). The TS host already creates one of these so it could be shared.

2020-06-06 03:20 UTC, kyliau commented
> I think you could filter out selectors that are not only element selectors (with `selector.isElementSelector`) and then check if the the element is an HTML element with the [DomElementSchemaRegistry](https://github.com/angular/angular/blob/master/packages/compiler/src/schema/dom_element_schema_registry.ts). The TS host already creates one of these so it could be shared.

Yes, I also found that after I commented about this! Thank you for the pointer :)
However, there're some tricky situations like
https://github.com/angular/angular/blob/aaa20093b23882f828ac1a96766bd4367d74aa14/packages/forms/src/directives/select_control_value_accessor.ts#L206-L207

In this case, I think it's ok to include the selector and not dedupe it against the DomRegistry.
I've added a new `CompletionKind.Directive` to denote that such selectors come from Directives. PTAL at the update code and commit message, thanks!

2020-06-06 03:27 UTC, ayazhafiz reviewed
otherwise lgtm

2020-06-06 03:27 UTC, ayazhafiz commented on packages/language-service/src/utils.ts
> +      }
this will skip element selectors if `isElementSelector` is false :)

2020-06-06 03:34 UTC, kyliau commented on packages/language-service/src/utils.ts
> +      }
that's what I intended.
if `isElementSelectors` is true, return only element selectors
if `isElementSelectors` is false, return anything that's not element selectors  (css selectors)

2020-06-06 03:36 UTC, ayazhafiz commented on packages/language-service/src/utils.ts
> +      }
why would we want to exclude element sectors? I guess looking at the other usages this makes sense, but can you document it on the parameter JSdoc?

2020-06-06 03:41 UTC, ayazhafiz approved these changes

2020-06-06 03:49 UTC, kyliau commented on packages/language-service/src/utils.ts
> +      }
The other use cases are attribute and microsyntax autocomplete, which also call this function.
I don't think element selectors make sense in cases where an attribute is expected.
Like `<div |>`, I don't think we should suggest `ng-form` at the cursor location.
Perhaps @JoostK can chime in and correct me if I'm wrong?

2020-06-06 03:55 UTC, ayazhafiz commented on packages/language-service/src/utils.ts
> +      }
yep, makes sense

2020-06-06 11:15 UTC, JoostK requested changes
The terminology used is misleading to me, however that is due to existing code being like this. All selectors are "element selectors" to me, as selectors only target elements in the first place. An element's name is typically referred to as its "tag", which would be a better name in place of "element".

I do not suggest to change it now as it would be a large change which also changes `@angular/compiler`, but it's something to keep in mind.

---

In the commit message, you still mention "component selectors and element selectors" which is no longer accurate I believe.

2020-06-06 11:15 UTC, JoostK commented on packages/language-service/test/project/app/parsing-cases.ts
> +  selector: 'my-comp',
Instead of assigning a selector to the component, I'd actually keep this without one as that is a valid scenario to have. If we don't want to suggest `ng-component`, the LS should filter it out. The default `ng-component` comes from `ElementSchemaRegistry.getDefaultComponentElementName` btw.

2021-01-29 19:55 UTC, kyliau commented
Closing this, since current effort is focusing on improving Ivy LS.

2021-01-29 19:55 UTC, closed without merging