Improve typing of common pipes
angular/angular pull request #37447
Opened 2020-06-04 23:56 UTC by ranma42

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #36259
Several pipes have incomplete or incorrect typing.

## What is the new behavior?
The common pipes should now all have a stricter typing.

## Does this PR introduce a breaking change?

- [X] Yes
- [x] No

It depends on what is considered a breaking change: some code that would compile will now trigger a compilation error. On the other hand, the code that is made invalid by this change, such as passing an object to a numeric pipe, was incorrect in the first place (it caused errors at runtime instead of at compile time).

Fixing the fallout should be trivial.

## Other information
Originally posted as https://github.com/angular/angular/pull/36277

2020-06-04 23:59 UTC, kyliau commented
Thank you for reopening the PR @ranma42!

For context, this is a continuation of https://github.com/angular/angular/pull/36277. It was accidentally closed by me due to my silly mistake in `git push`!

2020-06-05 03:32 UTC, ayazhafiz requested changes

2020-06-05 03:32 UTC, ayazhafiz commented on packages/common/src/pipes/number_pipe.ts
> +  return !(value == null || value === '' || value !== value);
nit: I think this is fine to keep as is, just change the return type to be `value is null|undefined`. Alternatively, you could use the [nullish coalescing](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing) operator to get rid of this method entirely.

2020-06-05 03:32 UTC, ayazhafiz commented on packages/common/src/pipes/slice_pipe.ts
> +    if (value == null) return null;
Prefer strict equality

```suggestion
    if (value === null || value === undefined) return null;
```

it's a nit but it makes the intention clearer IMO

2020-06-05 03:32 UTC, ayazhafiz commented on packages/common/test/pipes/keyvalue_pipe_spec.ts
> +    expect(pipe.transform(undefined)).toEqual(null);
:+1: love that the cast can be dropped here

2020-06-05 03:32 UTC, ayazhafiz commented on packages/language-service/src/typescript_symbols.ts
> +  const passedInTypes: Array<ts.Type|undefined> = _types.map(type => {
Can we rename `_types` to `types`? I think I added this to make TS stop complaining about an unused variable..

2020-06-05 03:32 UTC, ayazhafiz commented on packages/language-service/src/typescript_symbols.ts
> +  }
Can you add a comment that this is still kind of a hack, because we're checking for strict type equality rather than compatibility. For example, if we the signature contains a `ReadonlyArray<int>` and the passed parameter type is an `Array<int>`, this will fail.

2020-06-05 03:59 UTC, kyliau commented on packages/language-service/src/typescript_symbols.ts
> +  }
The initial comment about the most appropriate approach to take still stands:
https://github.com/angular/angular/blob/3569fdf45195c36713e43a91a4feba4fa3c9facf/packages/language-service/src/typescript_symbols.ts#L227-L230
I've added additional comments below to make it clear that this is just a best-effort approach over what we currently have.

2020-06-05 04:04 UTC, kyliau commented
@ranma42 I've fixed up the language service part, should be good to go now.
@petebacondarwin Could you please take another look? Sorry I messed up the earlier PR and accidentally closed it.

2020-06-05 04:20 UTC, ayazhafiz commented on packages/language-service/src/typescript_symbols.ts
> +  }
Forgot that was there, thanks!

2020-06-05 06:17 UTC, kyliau approved these changes
LGTM for language service

2020-06-05 07:15 UTC, ranma42 commented on packages/common/src/pipes/number_pipe.ts
> +  return !(value == null || value === '' || value !== value);
I would rather avoid the `value is null|undefined` route, as the signature would be very misleading: value could also be `''` (which could be added to the signature) or `NaN` (which cannot be expressed as a literal type).

It is not clear to me how to use the `??` to get rid of this function... wouldn't you still need to check for `''` and `NaN` at every location?

2020-06-05 07:18 UTC, ranma42 commented on packages/common/src/pipes/slice_pipe.ts
> +    if (value == null) return null;
Right now all of the (common) pipes that work on scalar values check for `== null`. Should I change it also in the other ones?

2020-06-05 13:16 UTC, ayazhafiz commented on packages/common/src/pipes/slice_pipe.ts
> +    if (value == null) return null;
didn’t realize it was a convention, disregard

2020-06-05 13:16 UTC, ayazhafiz approved these changes

2020-06-08 18:41 UTC, petebacondarwin approved these changes
Apart from the additional suggested overloads, which IMO are optional for this PR, LGTM

Reviewed-for: fw-i18n

2020-06-08 18:41 UTC, petebacondarwin commented on packages/common/src/pipes/case_conversion_pipes.ts
> +  transform(value: string|null|undefined): string|null;
Is it worth adding yet another overload of

```ts
transform(value: null|undefined): null;
```

2020-06-08 18:41 UTC, petebacondarwin commented on packages/common/src/pipes/case_conversion_pipes.ts
> +  transform(value: string|null|undefined): string|null;
And similarly elsewhere.

(Disclaimer: I have not checked whether this would break the type system...)

2020-06-09 09:28 UTC, ranma42 commented on packages/common/src/pipes/case_conversion_pipes.ts
> +  transform(value: string|null|undefined): string|null;
I tried locally and it looks like it should be fine, apart from a couple of language-service tests that would need to be updated (they check that there is exactly one type for a pipe, while this change would make the resolver find two types).
Should I add it to this branch or is it better to do it in another PR?
In the first case, should I squash the changes or add them on top? (what is best for reviews/the convention for this repo?)

2020-06-09 09:30 UTC, ranma42 commented on packages/common/src/pipes/case_conversion_pipes.ts
> +  transform(value: string|null|undefined): string|null;
> Is it worth adding yet another overload of
> 
> ```ts
> transform(value: null|undefined): null;
> ```

I had omitted them assuming that it is a niche use case, but it certainly makes typing more accurate and I guess it might help spotting issues in some buggy code.

2020-06-09 11:16 UTC, petebacondarwin commented on packages/common/src/pipes/case_conversion_pipes.ts
> +  transform(value: string|null|undefined): string|null;
Not a blocker for this PR from my point of view. I just mention it because, this PR involves a public API change, and a second PR would also do so, which is extra work checking the API each time.

I would rather get @IgorMinar another public API approver to comment before you make any further changes.

2020-06-10 00:04 UTC, jelbourn commented
It looks like the changes from `any` to more strict types are breaking API changes- am I interpreting that right?

2020-06-10 06:34 UTC, IgorMinar reviewed
Thank you @ranma42 for the PR but this is definitely a breaking change and because we are already in the v10 RC period we will have to wait for the master branch to open for v11 changes before we can entertain this change.

I skimmed through the diff and at the high level this looks like a good change to me. Let's revisit this once we are working on v11.

2020-06-10 10:14 UTC, ranma42 commented
Yup, as mentioned in the checklist the typing change is a breaking change.
@IgorMinar should I do something to make the merge happen in time for v11?
(this branch sat idle for about 2 months and only lately it got some movement)

2020-06-25 06:27 UTC, ranma42 commented
Is now a good time to start working on this again?
Should I rebase and/or add the `transform(value: null|undefined): null;` specializations?

2020-06-25 09:00 UTC, petebacondarwin commented
Now that 10.0.0 is out, the `master` branch is now open for new PRs so this PR is unblocked.
@ranma42 - please do rebase and let's see what we can do to move it forward.

2020-06-25 13:14 UTC, ranma42 commented
Nice! Rebased :)

2020-06-25 23:37 UTC, jelbourn commented
@petebacondarwin since this is a breaking change, I think this wouldn't be able to move closer until we're on the v11 release train, no?

2020-06-26 05:12 UTC, petebacondarwin commented
Oops! Sorry. I forgot we are on minors for a bit now.

2020-07-22 08:37 UTC, ranma42 commented
It looks like the branch does not merge cleanly anymore; should I rebase it now or wait for master to be open to breaking changes?

Also, would it make sense to split the breaking changes and the compatible ones in two separate branches, so that the latter can proceed "immediately" while the breaking ones wait for 11?
(This would obviously require twice as many reviews, but each would be on a smaller change)

2020-07-22 09:27 UTC, petebacondarwin commented
Whether to rebase now or later is up to you. No doubt it will need another rebase closer to its merge date. But it may be that rebasing regularly will make each conflict resolution simpler? Or maybe it is just adding more work...

Given that we are entering the summer when there are naturally fewer resources to handle reviewing and merging and v11 might be open for merging early Autumn, I would just sit on this whole PR until then, unless you desperately need some of the non-breaking changes in the next release.

2020-07-23 08:55 UTC, ranma42 commented
I would hate to miss again the merge window, but I am not in a rush to get this merged (the projects I work on that would benefit from this are mostly fine with some additional casts).

2020-07-24 11:35 UTC, petebacondarwin approved these changes
Reviewed-for: public-api

2020-07-28 18:38 UTC, atscott commented
Also fixes #36404

2020-07-30 20:54 UTC, mhevery approved these changes

2020-07-30 20:55 UTC, mhevery approved these changes
reviewed-for: global-approvers
reviewed-for: fw-core

2020-08-25 02:26 UTC, dev054 commented on packages/common/src/pipes/keyvalue_pipe.ts
> +  transform<K, V>(
Could we also support `ReadonlyMap` here?

2020-08-25 06:23 UTC, ranma42 commented on packages/common/src/pipes/keyvalue_pipe.ts
> +  transform<K, V>(
Yes :)
That has already been changed in https://github.com/angular/angular/pull/37311 and will stay like that when these changes are rebased

2020-09-11 14:13 UTC, ranma42 commented
rebased

2020-09-16 07:01 UTC, ranma42 commented
@petebacondarwin this PR was assigned new tags, so I rebased it.

Note that I only fixed the conflicts; I did not address [this comment](https://github.com/angular/angular/pull/37447#discussion_r436912138), but I can certainly do it if it it is desired 😄

2020-09-16 08:08 UTC, petebacondarwin commented
Thanks for keeping this PR up to date @ranma42 - it just needs to pass the "presubmit" which is where we run it against a subset of the Google projects that use Angular internally.

2020-09-16 10:51 UTC, ranma42 commented on packages/common/src/pipes/async_pipe.ts
>    transform(obj: Observable<any>|Promise<any>|null|undefined): any {
since the object wrapping has been removed, we might avoid even just use the "strict" signature, if we like it better:

```suggestion
  transform<T>(obj: Observable<T>|Promise<T>|null|undefined): T|null {
```

note that this would not change anything for the API consumers

2020-09-16 16:37 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:332024221:BASE:332024251:1600274148829:43188e36).

2020-09-18 00:19 UTC, AndrewKushnir commented
Hi @ranma42, quick update: we ran tests in Google's codebase and found out that there are some part of code that require updates in order to land this change. We'll be look into these cases and keep this thread updated on the progress.

This PR introduces a breaking change, so we need to include the `BREAKING CHANGE` section into one of the commit message to describe what the change is and what developers should do to resolve the problem is they come across it. You can find an example of the breaking changes note in https://github.com/angular/angular/commit/6acea54f62fe7e62e9b36458b30d98501277236f.

Thank you.

2020-09-18 07:30 UTC, ranma42 commented
> Hi @ranma42, quick update: we ran tests in Google's codebase and found out that there are some part of code that require updates in order to land this change. We'll be look into these cases and keep this thread updated on the progress.
> 
> This PR introduces a breaking change, so we need to include the `BREAKING CHANGE` section into one of the commit message to describe what the change is and what developers should do to resolve the problem is they come across it.

Several commits introduce some kind of breaking change.
They are somewhat related, as they are all typing changes on the pipes, but each is independent and possibly different.
It is better to add the `BREAKING CHANGE` section to each of them (explaining what that specific commit is breaking) or should I put it in the first/last commit of the branch?

2020-09-18 07:48 UTC, petebacondarwin commented
If it makes sense for the changes to be in separate commits then they should each get their own BREAKING CHANGE (BC) block that is specific to that change. This has two benefits:

* the change log will have seperate breaking changes items for each one, which makes it easier for the reader to find BCs specific to their needs
* if. for some reason, a commit needs to be reverted, the other commits (and their BCs) are not affected.

If you feel that this is overkill then perhaps the commits should be merged?

2020-09-18 22:20 UTC, AndrewKushnir commented
Hi @ranma42, I performed further testing and came across an issue with the `TitleCasePipe` (and it might be applicable to some other pipes as well).

Here is a quick example of a pipe, similar to what we have for the `TitleCasePipe` one (from types perspective) in this PR, but a simplified version ([TypeScript playground page](https://www.typescriptlang.org/play?#code/MYGwhgzhAECyCeAFAlgBwKbQN4ChrQBcAnMAOwgDMB7IgWwAoA3MEAV3QC5oJjlSBzAD6lWIEINakAJugp90UgJRceRPkJFiA3HkIly1OkxbsVvAcu7n+O-MTKUaDZm05W1A4aPGSZc0gqWqupeYti6+MgU0Mau0AC88dCaIIrQROgErESkyd62+OmZ2bku7AUAvjhVOMBU5ATQfDxkwJhJAQDucEho6PSKOnUNRRCiBACCEADK1glNDa3oAHT2Bk70AORgAEbAm4PQAPRH0OgAHhjABApcGWMgkzNzABaQ0AAGwQIfhPAYABpoGBrqwWFwvnNBHkxB9avUeKNxlMAHLeebNAhLVb6RxGFKHE5nS7oa63JGPVHot4wD4pX4Ef7oIEgrLgz7ffjQaH0oA)):
```
class SimplePipe {
  transform(value: string|null|undefined): string|null;
  transform(value: string): string;
  transform(value: string|null|undefined): string|null {
    if (value == null) return null;
    return value;
  }
}

const pipe = new SimplePipe();
const result = pipe.transform('abc');
```

What happens here is that the `result` has the `string | null` type, when the expectation is that it should have just `string` (based on the second overload). I believe we should avoid this overlap (so that 2 overloads match the value type) to resolve the issue, so the code of the pipe might look like this ([TypeScript playground page](https://www.typescriptlang.org/play?#code/MYGwhgzhAECyCeAFAlgBwKbQN4ChrQBcAnMAOwgDMB7IgWwAoA3MEAV3QC5oJjlSBzAJRceRPvwDceQiXLU6TFuy6lWIEAB9WpACboKfdDuHRV6qfmJlKNBszaduvARrObteg6SMnR412og2NL4yBTQig7QALzRpoGC0EToBKxEpPHmIUkpaRn27BbQAL44pTjAVOQE0Hw8ZMCYcd4A7nBIaOj0glKV1TkQagQAghAAys78MbXVDegAdFZytvQA5GAARsCrPdAA9HvQ6AAeGMAERtNg56wsXMmDICPjk9AAFpDQAAZ+Al+E8AwFSqPAGQ1GADlAtM6gQ5otZDYFG5dgcjqd0OdLnFrqk7mCnpDoR8YF83P8CID0EA)):

```
class SimplePipe {
  transform(value: string): string;
  transform(value: null|undefined): null;
  transform(value: string|null|undefined): string|null {
    if (value == null) return null;
    return value;
  }
}

const pipe = new SimplePipe();
const result = pipe.transform('abc');
```

What do you think?

I'm adding the "blocked" label for now so that we resolve this question before adding this PR to the merge queue.

// cc @petebacondarwin

2020-09-18 23:05 UTC, JoostK commented
@AndrewKushnir I think you'll want to just swap the first and second signatures, such that the `transform(value: string): string` becomes the preferred signature. In your proposal, someone would get type errors for inputs of type `string|null`, as none of the signatures allow for that combination.

2020-09-18 23:13 UTC, AndrewKushnir commented
Thanks @JoostK, that makes sense 👍 

@ranma42, it looks like the following pipes are affected by this problem:

- KeyValuePipe
- LowerCasePipe
- TitleCasePipe
- UpperCasePipe
- SlicePipe

So we need to move more specific overloads for these pipes higher on the overload list.

2020-09-20 18:24 UTC, ranma42 commented
you are right, the overloads should be listed from the most specific to the most generic

2020-09-20 21:37 UTC, ranma42 commented
I tried to fix all of the issues you noticed, namely:
 - bad overload ordering (TypeScript resolves on a first-matching basis, so the specific overloads must appear before the generic ones)
 - incomplete typing around `null | undefined`
 - missing notices about `BREAKING CHANGES`

In doing so I also noticed that the typing of `KeyValuePipe` was still incorrect: if it is passed a value which is typed as `Record<number, V>` it actually returns the keys as strings.
The typing has been updated accordingly (the tests already check for this).

2020-09-20 23:16 UTC, AndrewKushnir commented
Hi @ranma42, thanks for updating the changes 👍 

FYI, I've rebased this PR on top of the latest master (the CI didn't start because the previous base commit was too old). The rebase was successful, no additional changes were made.

Since there were some changes, I'd like to ask @petebacondarwin and @JoostK to have a quick look at the changes once again to make sure everything is ok.

Thank you.

2020-09-21 00:01 UTC, AndrewKushnir commented
I've also started [tests in Google's codebase](http://test/OCL:332024221:BASE:332754939:1600646445846:9358fba5) and will keep this thread updated.

2020-09-21 06:54 UTC, ranma42 commented
I just noticed that in one of the commit messages I skipped a word :(

"The typing of the `keyvalue` has been fixed..."
instead of
"The typing of the `keyvalue` pipi has been fixed..."

2020-09-21 13:35 UTC, petebacondarwin commented on packages/common/src/pipes/async_pipe.ts
> +      return this.transform(obj);
🚀

2020-09-21 13:41 UTC, petebacondarwin commented on packages/common/src/pipes/number_pipe.ts
> +  return !(value == null || value === '' || value !== value);
Do we not prefer use of `isNaN`?

```suggestion
  return !(value == null || value === '' || isNaN(value));
```

2020-09-21 13:43 UTC, petebacondarwin commented on goldens/public-api/common/common.d.ts
> +    transform(value: number | null | undefined, pluralMap: {
We could go crazy here and do something like:

```suggestion
    transform(value: number, ...): string;
    transform(value: null | undefined, ...): '';
    transform(value: number | null | undefined, ...): string;
```

2020-09-21 13:47 UTC, petebacondarwin approved these changes
Reviewed-for: public-api

Nice work @ranma42  - thanks for your patience.

A typo in commit 1:

> instead ~~reflcts~~reflects the behaviour on `null` and `undefined`.

And a few nits and suggestions.

2020-09-21 15:37 UTC, JoostK commented on packages/common/src/pipes/keyvalue_pipe.ts
> +      input: Record<K, V>, compareFn?: (a: KeyValue<string, V>, b: KeyValue<string, V>) => number):
Shouldn't this be
```suggestion
      input: Record<K, V>, compareFn?: (a: KeyValue<number, V>, b: KeyValue<number, V>) => number):
```

Which makes it equivalent to the next overload with `K extends string|number`.

2020-09-21 15:37 UTC, JoostK commented on packages/common/src/pipes/keyvalue_pipe.ts
> +      compareFn?: (a: KeyValue<string, V>, b: KeyValue<string, V>) => number):
Same here

2020-09-21 15:37 UTC, JoostK commented on packages/common/src/pipes/number_pipe.ts
> +  transform(value: number|string, digitsInfo?: string, locale?: string): string|null;
I think this signature is not technically required, as its return type is `string|null` just like the third signature and the ordering doesn't matter in this case (i.e. this signature can be moved one down without changing the matching behavior, and can then be merged with the 3rd signature). I don't particularly mind, and from a docs perspective it may seem weird that the primary signature only takes `null|undefined`, so I am fine with keeping as is.

This comment also applies to some other pipes below.

2020-09-21 15:37 UTC, JoostK commented on packages/common/test/pipes/number_pipe_spec.ts
> +          expect(() => pipe.transform(<any>{}))
nit: we typically use `as` casts.

```suggestion
          expect(() => pipe.transform({} as any))
```

2020-09-21 16:07 UTC, petebacondarwin commented on packages/common/src/pipes/number_pipe.ts
> +  transform(value: number|string, digitsInfo?: string, locale?: string): string|null;
I agree it is not really needed but it makes the overload options clearer to the user of the code.

2020-09-23 08:09 UTC, ranma42 commented on goldens/public-api/common/common.d.ts
> +    transform(value: number | null | undefined, pluralMap: {
sure! :) should I go forward with that?

2020-09-23 08:11 UTC, ranma42 commented on packages/common/src/pipes/keyvalue_pipe.ts
> +      input: Record<K, V>, compareFn?: (a: KeyValue<string, V>, b: KeyValue<string, V>) => number):
no, the `keyvalue` pipe passes the `number` keys as strings in the case of a `Record<number, V>` object :(

I tried to explain it in the commit message, but maybe it is not explicit enough (and maybe we should also add a comment in the code to explain it, so it does not get lost in the git history)

2020-09-23 08:11 UTC, ranma42 commented on packages/common/src/pipes/keyvalue_pipe.ts
> +      compareFn?: (a: KeyValue<string, V>, b: KeyValue<string, V>) => number):
as above

2020-09-23 08:14 UTC, ranma42 commented on packages/common/src/pipes/number_pipe.ts
> +  transform(value: number|string, digitsInfo?: string, locale?: string): string|null;
Removing it also makes the pipe very weird when applied to `any`, as in that case TypeScript uses the first overload (since any overload matches `any`) instead of the most generic one.

This is very inconvenient when the first overload handles "special" cases (`null | undefined`) as it causes the result to be typed `null` as well

2020-09-23 08:18 UTC, ranma42 commented on packages/common/test/pipes/number_pipe_spec.ts
> +          expect(() => pipe.transform(<any>{}))
oops! this was based on the `should not support other objects` from `case_conversion_pipes_spec.ts`, I did not know about the new convention.

I will fix the casts am I adding/modifying.
Should I also update the existing `<xyz>` casts in the files I an touching?

2020-09-23 08:27 UTC, ranma42 commented on packages/common/test/pipes/number_pipe_spec.ts
> +          expect(() => pipe.transform(<any>{}))
I tried enabling the `no-angle-bracket-type-assertion` lint, but it looks like the codebase is still using them in several places.
I guess that kind of "global" refactor is better handled in another (non-BC) pull request.

In the meantime I will fix them in the code I am touching, so that PR will be a little bit simpler ;)

2020-09-23 08:29 UTC, JoostK commented on packages/common/test/pipes/number_pipe_spec.ts
> +          expect(() => pipe.transform(<any>{}))
Yes that sounds like the correct approach, thanks!

2020-09-23 09:16 UTC, ranma42 commented on packages/common/src/pipes/number_pipe.ts
> +  return !(value == null || value === '' || value !== value);
TypeScript rejects it because `value` is typed as `number|string` at that point.

2020-09-23 09:22 UTC, JoostK commented on packages/common/test/pipes/number_pipe_spec.ts
> +          expect(() => pipe.transform(<any>{}))
Oh by the way, these could be improved even further in the future using `// @ts-expect-error` instead of the `any` cast.

2020-09-23 09:26 UTC, ranma42 commented on goldens/public-api/common/common.d.ts
> +    transform(value: number | null | undefined, pluralMap: {
In a way, it looks like a good idea, as it provides a type-level "documentation" of the behavior in these special cases.
OTOH, it looks like a strange commitment from the perspective of the API

2020-09-23 18:05 UTC, JoostK approved these changes
LGTM, thanks for putting this together!

2020-09-23 18:11 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:332024221:BASE:333330678:1600884669816:b2811fb9).

2020-09-28 16:23 UTC, closed without merging

2020-09-28 16:28 UTC, AndrewKushnir commented
Hi @ranma42, just want to let you know that this PR was merged into master branch and the change will be included into upcoming v11 release. Thank you for contributing to Angular!