docs: corporate proxy
angular/angular pull request #37451
Opened 2020-06-05 09:50 UTC by web-dave

a more specific hint on how to set a corporate proxy.
I just talked to my customer who was struggeling with this.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-06-09 19:56 UTC, IgorMinar requested changes
Thanks for the contribution @web-dave, can you please take a look at the questions below?

2020-06-09 19:56 UTC, IgorMinar commented on aio/content/guide/build.md
> +When you define an environment variable `http_proxy` or `HTTP_PROXY`, an agent is automatically added to pass calls through your corporate proxy when running `npm start  --proxy-config proxy.conf.js`
I can't find any docs about this flag in npm cli or on the website. can you please share them with us?

Additionally, this change seems like it's suggesting that there is a way to augment the proxy configuration via a js config file and override the environment variables discussed at the begining of the paragraph. If that's the case then we might want to split this up into two sentences or two paragraphs because the two are two distinct ways of controling the proxy settings.

2020-06-10 08:11 UTC, web-dave commented on aio/content/guide/build.md
> +When you define an environment variable `http_proxy` or `HTTP_PROXY`, an agent is automatically added to pass calls through your corporate proxy when running `npm start  --proxy-config proxy.conf.js`
This flag is a webpack flag and used by the https-proxy-agent wich was mentioned right before this paragraph.

2020-12-08 11:19 UTC, petebacondarwin commented
@web-dave are you able to address the comments above?

2021-01-14 05:26 UTC, AndrewKushnir commented
FYI, closing this PR due to the lack of response. Feel free to reopen when you get a chance to look into it in the future. Thank you.

2021-01-14 05:26 UTC, closed without merging