feat(core): support injection tokens as predicate in queries
angular/angular pull request #37506
Opened 2020-06-09 13:16 UTC by devversion

Currently Angular internally already handles `InjectionToken` as
predicates for queries. This commit exposes this as public API
as people already relied on this functionality but currently used
workarounds to satisfy the type constraints (e.g. `as any`).

We intend to make this public as it low-effort, and it's a signficant
key part for the use of light-weight tokens as described in the upcoming
guide: https://github.com/angular/angular/pull/36144.

In concrete, applications might use injection tokens over class for both DI
and queries, because otherwise such class references for optional queries or DI
always cause these classes to be retained. This was also an issue in View Engine,
but now with Ivy, this pattern became worse as factories could be directly attached
to retained classes (ultimately ending up in the production bundle, while unused).

More details in the light-weight token guide and in:
https://github.com/angular/angular-cli/issues/16866.

Closes #21152. Related to #36144.

2020-06-09 18:53 UTC, jelbourn approved these changes
LGTM

2020-06-10 05:51 UTC, IgorMinar requested changes
otherwise LGTM

Reviewed-for: public-api

2020-06-10 05:51 UTC, IgorMinar commented on goldens/public-api/core/core.d.ts
> +    (selector: Type<any> | InjectionToken<any> | Function | string, opts?: {
Any reason not to use `unknown` instead of `any`? Historically we used to use `any` in our public api surface whenever the type was unknown, but ever since TypeScript introduced the `unknown` type we started to to use that one instead. Sometimes `unknown` is not suitable, but in this case it might be. Can you please try it?


```suggestion
    (selector: Type<any> | InjectionToken<unknown> | Function | string, opts?: {
```

2020-06-10 09:28 UTC, devversion commented on goldens/public-api/core/core.d.ts
> +    (selector: Type<any> | InjectionToken<any> | Function | string, opts?: {
good idea! no strong reason. I just did it that way to align with existing generics for query decorators.  Updated it to use `unknown`!

I assume we can clean up the other generics too. I can try sending a follow-up, or incorporate this here, if possible.

2020-06-11 19:04 UTC, IgorMinar approved these changes
LGTM now! Thanks

(changing existing apis to use `unknown` could be a breaking change, so we can do so only in a major version and only with proper discussion/review. So I suggest we punt that discussion until master is open for v11)

Reviewed-for: global-approvers

[presubmit](http://test/OCL:315949641:BASE:315949698:1591902482391:17d3956c)

2020-06-11 20:21 UTC, closed without merging