Docs 2 little changes
angular/angular pull request #37521
Opened 2020-06-10 08:09 UTC by alan-agius4

See each commit.

2020-06-10 10:52 UTC, alan-agius4 commented
FYI: @kyliau

2020-06-10 16:25 UTC, kyliau requested changes

2020-06-10 17:06 UTC, kyliau approved these changes

2020-06-15 18:23 UTC, IgorMinar approved these changes
lgtm otherwise

2020-06-15 18:23 UTC, IgorMinar commented on aio/content/guide/file-structure.md
> +| `package.json`              | This file is not used by package managers. It is used to tell the tools and bundlers whether the code under this directory is free of non-local [side-effects](https://
```suggestion
| `app/package.json`              | This file is generated only in projects created in the `ng new --strict` mode. This file is not used by package managers. It is used to tell the tools and bundlers whether the code under this directory is free of non-local [side-effects](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free). |
```

2020-06-16 09:44 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `package.json`              | This file is not used by package managers. It is used to tell the tools and bundlers whether the code under this directory is free of non-local [side-effects](https://
Actually that is not correct, the file is always created the value is changed based on if the project is in strict mode or not.

2020-06-16 09:46 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `package.json`              | This file is not used by package managers. It is used to tell the tools and bundlers whether the code under this directory is free of non-local [side-effects](https://
Let’s me know if we should update the schematic to only generate this file when using strict mode.

2020-06-16 15:44 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `package.json`              | This file is not used by package managers. It is used to tell the tools and bundlers whether the code under this directory is free of non-local [side-effects](https://
Following a convo with @kyliau and @mgechev we decided to drop this file when not in strict mode.

2020-06-16 16:50 UTC, alan-agius4 commented on aio/content/guide/file-structure.md
> +| `package.json`              | This file is not used by package managers. It is used to tell the tools and bundlers whether the code under this directory is free of non-local [side-effects](https://
Updated the description a bit to: `This file is generated only in applications created using `--strict` mode.`. because this also effects `ng g application`.

2020-06-16 18:57 UTC, closed without merging