fix(core): unify the signature between ngZone and noopZone
angular/angular pull request #37581
Opened 2020-06-15 03:46 UTC by JiaLiPassion

Now we have two implementations of Zone in Angular, one is NgZone, the other is NoopZone.
They should have the same signatures, includes
1. properties
2. static methods
3. methods

In this PR, unify the signatures of the two implementations, and remove the unnecessary cast.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-06-15 14:47 UTC, gkalpak approved these changes

2020-06-29 18:01 UTC, mhevery requested changes

2020-06-29 18:01 UTC, mhevery commented on packages/core/src/zone/ng_zone.ts
> +
Why do you think that the `static` methods should be part of this API? My understanding is that the existing `static` methods on `NgZone` have the correct implementation and correctly return if the code is in `NgZone`. The new methods here, have the code hard wired, and do not actually check. (It is possible that we have two apps on single page and some run `NgZone` and some run `NoopNgZone` I would just remove these `static` methods.

2020-06-29 18:05 UTC, JiaLiPassion commented on packages/core/src/zone/ng_zone.ts
> +
@mhevery , yeah, you are right, in fact there is an issue about this one (mixing two angular app in the same page),https://github.com/angular/angular/issues/37577,
I will remove all those static methods.

2020-07-10 19:51 UTC, mhevery approved these changes

2020-07-10 19:52 UTC, mhevery commented
[presubmit](http://test/OCL:320657636:BASE:320657672:1594410747140:94dbe14c)

2020-07-28 16:59 UTC, closed without merging