test(docs-infra): add end to end tests for api reference
angular/angular pull request #37612
Opened 2020-06-16 17:03 UTC by ajitsinghkaler

Api search functionality only had unit tests @gkalpak suggested we should have some e2e tests too. Added some end to end tests.

Fixes #35170

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

No e2e test for API search functionality

Issue Number: #35170

## What is the new behavior?
 e2e test for API search functionality

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-06-17 06:49 UTC, ajitsinghkaler commented
I think test failures are flake

2020-06-17 15:12 UTC, gkalpak requested changes
Looking good. I left a few minor comments/suggestions.

2020-06-17 15:12 UTC, gkalpak commented on aio/tests/e2e/src/api-list.e2e-spec.ts
> +    const input = element(by.css('aio-api-list .form-search input'));
Let's move this at the top of the `describe()` block to avoid repetition:

```
describe('api-list', () => {
  const apiSearchInput = element(by.css('aio-api-list .form-search input'));
  ...
```

Same for the selects below.

2020-06-17 15:12 UTC, gkalpak commented on aio/tests/e2e/src/api-list.e2e-spec.ts
> +  });
Can you also verify that certain results where there before but are removed after applying the search terms?
(Similar for the tests below.)

2020-06-19 04:36 UTC, ajitsinghkaler commented
@gkalpak These are flaky test failures

2020-06-21 10:16 UTC, gkalpak requested changes
Thx for making the changes, @ajitsinghkaler!
(Yes, these tests are flaky. This is tracked in #37629.)

2020-06-21 10:16 UTC, gkalpak commented on aio/tests/e2e/src/api-list.e2e-spec.ts
> +  const apiTypeDropdown = element(by.css('aio-api-list aio-select[label="Type:"] .form-select-button'));
Nit (moving uninitialized vars below initialized ones):

```suggestion
  const apiSearchInput = element(by.css('aio-api-list .form-search input'));
  const apiStatusDropdown = element(by.css('aio-api-list aio-select[label="Status:"] .form-select-button'));
  const apiTypeDropdown = element(by.css('aio-api-list aio-select[label="Type:"] .form-select-button'));
  let page: SitePage;
```

2020-06-21 10:16 UTC, gkalpak commented on aio/tests/e2e/src/api-list.e2e-spec.ts
>      expect(page.getApiSearchResults()).toContain('AnimationSequenceMetadata');
```suggestion

    expect(page.getApiSearchResults()).not.toContain('HttpEventType');
    expect(page.getApiSearchResults()).toContain('AnimationSequenceMetadata');
```

2020-06-21 10:16 UTC, gkalpak commented on aio/tests/e2e/src/api-list.e2e-spec.ts
>      expect(page.getApiSearchResults()).toContain('getLocaleDateTimeFormat');
```suggestion

    expect(page.getApiSearchResults()).not.toContain('formatCurrency');
    expect(page.getApiSearchResults()).toContain('getLocaleDateTimeFormat');
```

2020-06-21 10:16 UTC, gkalpak commented on aio/tests/e2e/src/api-list.e2e-spec.ts
>      expect(page.getApiSearchResults()).toContain('LowerCasePipe');
```suggestion
    expect(page.getApiSearchResults()).not.toContain('getLocaleDateTimeFormat');
    expect(page.getApiSearchResults()).toContain('LowerCasePipe');
```

2020-06-21 10:16 UTC, gkalpak commented on aio/tests/e2e/src/api-list.e2e-spec.ts
>      menuItem.click();
This is a good candidate for putting into a function/method (either at the top of the `describe()` block or in `SitePage`).

2020-06-21 10:16 UTC, gkalpak commented on aio/tests/e2e/src/api-list.e2e-spec.ts
>      const menuItem = element.all(by.css('aio-api-list aio-select[label="Status:"] .form-select-dropdown li')).get(3);
Here (and above), I think it would be cleaner to use [by.cssContainingText()][1], instead of a hard-coded index (which doesn't make the intention clear and is less future-proof). 

[1]: https://www.protractortest.org/#/api?view=ProtractorBy.prototype.cssContainingText

2020-06-21 10:41 UTC, ajitsinghkaler commented
@gkalpak I don't know why but all your review comments are shown outdated, is there a problem with this review

2020-06-21 10:58 UTC, ajitsinghkaler commented on aio/tests/e2e/src/api-list.e2e-spec.ts
>      menuItem.click();
I did not get this one. Can you elaborate more please

2020-06-21 12:00 UTC, gkalpak commented on aio/tests/e2e/src/api-list.e2e-spec.ts
>      menuItem.click();
These three lines for choosing a particular value from the drop-down should be converted to a helper function or method (to make the tests more declarative/easier to follow).

2020-06-21 15:06 UTC, ajitsinghkaler commented
@gkalpak tests should not increase or decrease payload-sizes is this a flake too

2020-06-21 17:47 UTC, gkalpak commented
Yes, the payload-size failures are flakes too (not sure why/how that happens, but we've seen it before a couple of times).

2020-06-24 16:03 UTC, ajitsinghkaler commented
@gkalpak can you please review this

2020-06-24 16:03 UTC, ajitsinghkaler commented
@gkalpak can you please review this

2020-06-25 17:34 UTC, gkalpak approved these changes
Nice job! Thx, @ajitsinghkaler 👍

2020-06-25 18:36 UTC, closed without merging