perf(compiler-cli): fix regression in type-checking program reuse
angular/angular pull request #37641
Opened 2020-06-19 00:06 UTC by alxhub

Commit 4213e8d5 introduced shim reference tagging into the compiler, as well
as changed how the `TypeCheckProgramHost` worked under the hood during the
creation of a template type-checking program. This work enabled a more
incremental flow for template type-checking, but unintentionally introduced
two related performance regressions:

1. The `TypeCheckProgramHost` now relies on the `ts.CompilerHost`'s
   `getSourceFile()` operation to retrieve existing `ts.SourceFile`s. If the
   host does not return unchanged source files and instead always creates
   new instances, this can throw off TypeScript's program reuse, and reduce
   the incrementality severely.

   Additionally of course, the cost of re-parsing all of the program's files
   is non-trivial, especially in the Bazel build case where .d.ts files get
   reparsed on every compilation.

2. During the creation of the template type-checking program, TypeScript
   compares the `referencedFiles` of the old and new `ts.SourceFile`s, and
   falls out of complete reuse if they differ. Because shim tags are removed
   from the old program but present in in the `TypeCheckProgramHost`'s
   returned files, these arrays always differed, and TypeScript was never
   able to reuse the old program completely in this case.

These two effects had a compounding effect: normally, only source files that
differed would be affected by 2, as otherwise the host would tag the same
instance. However, because of 1, source files might always be different
instances, and thus always affected by 2.

This commit addresses the regression by fixing both problems, as well as
introducing another optimization for edge case compilations.

Problem 1 is fixed by modifying the `TypeCheckProgramHost` to retrieve
original files from the original `ts.Program` instead of the
`ts.CompilerHost` where possible. This ensures that the file instance does
not change, which avoids the re-parsing cost as well as allows program reuse
to proceed with as much incrementality as possible.

Problem 2 is fixed by patching the old program's `referencedFiles` again
temporarily during the creation of the template type-checking program. This
ensures that TypeScript always sees matching `referencedFiles` between old
and new files, and doesn't get kicked out of complete reuse unnecessarily.

An optimization is also added to skip the template type-checking program
creation entirely if no template type-checking operations are needed (for
example, if the program contains no components). This avoids even the small
cost of complete incremental program reuse in compilations that don't need
it. This doesn't happen in CLI applications, but in Bazel compilations it's
common to have targets which only contain services or other types (pipes,
directives, etc).

Tests which verify the correct behavior of the `TypeCheckProgramHost` and
the `ReusedProgramStrategy` under the various problematic conditions were
added to the template type-checking system.

2020-06-19 00:13 UTC, alxhub commented
[Presubmit](http://test/OCL:317212167:BASE:317212178:1592525351282:d16ca656)

2020-06-19 20:42 UTC, alxhub commented
[Presubmit](http://test/OCL:317212167:BASE:317371210:1592599190234:421ac38b)

2020-06-19 23:35 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/tsc_plugin.ts
> +    const original: ts.SourceFile|undefined = ts.getOriginalNode(sf) as ts.SourceFile;
Oh, trust me, it can. I've been bitten by that before!

2020-06-19 23:36 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/host.ts
> +    let delegateSf: ts.SourceFile|undefined = this.originalProgram.getSourceFile(fileName);
No, I don't want to obey it :) I don't actually understand its purpose very well either, but the entire goal of the type-checking host is to reuse as much as possible.

2020-06-19 23:37 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/test/program_spec.ts
> +      // expect() here would create a really long error message, so this is checked manually.
Yep, I think `expect` prints out both the difference (expected A but got B) and the expectation message, and if the difference message is huge (the delta between two `program` objects can be pretty insane), it gives up at some point.

2020-06-22 09:24 UTC, alan-agius4 commented
@kyliau, requested to gather some rebuild timings for this change.

### Important notes
- The below timings have been gather on AIO, using the latest RC’s for both Angular FW and CLI.  
- The first timing is that of the first incremental re-build and not of the cold build.
- The first rebuild with fork type checker is typically slower than the following because a program nor source files have been created and cached yet in the forked process.

### With fork type checker

```
ng build --configuration=fast --aot --watch --progress --fork-type-checker
```

**Current**
```
[benchmark]   Average Time: 5014.60 ms (18230.00, 1709.00, 1409.00, 1511.00, 2214.00)
[benchmark]   Average Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Peak Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Average CPU usage: 192.48 % (215.55, 239.11, 183.33, 179.83, 144.59)
[benchmark]   Peak CPU usage: 398.44 % (610.00, 422.22, 360.00, 340.00, 260.00)
[benchmark]   Average Memory usage: 1338.61 MB (959.83, 1373.54, 1428.99, 1435.42, 1495.27)
[benchmark]   Peak Memory usage: 1489.55 MB (1556.14, 1418.00, 1456.09, 1479.27, 1538.27)
```

**With this change**
```
[benchmark]   Averaqe Time: 4894.00 ms (18734.00, 1510.00, 1410.00, 1309.00, 1507.00)
[benchmark]   Average Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Peak Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Average CPU usage: 184.63 % (208.48, 210.00, 178.07, 172.67, 153.91)
[benchmark]   Peak CPU usage: 420.00 % (640.00, 370.00, 370.00, 360.00, 360.00)
[benchmark]   Average Memory usage: 1118.72 MB (991.59, 1100.26, 1153.92, 1149.76, 1198.05)
[benchmark]   Peak Memory usage: 1278.98 MB (1658.93, 1145.76, 1160.33, 1182.18, 1247.69)
```



### Without fork type checker

```
ng build --configuration=fast --aot --watch --progress --no-fork-type-checker
```

**Current**
```
[benchmark]   Average Time: 1952.20 ms (2282.00, 2077.00, 1775.00, 1859.00, 1768.00)
[benchmark]   Average Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Peak Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Average CPU usage: 192.48 % (215.55, 239.11, 183.33, 179.83, 144.59)
[benchmark]   Peak CPU usage: 398.44 % (610.00, 422.22, 360.00, 340.00, 260.00)
[benchmark]   Average Memory usage: 1338.61 MB (959.83, 1373.54, 1428.99, 1435.42, 1495.27)
[benchmark]   Peak Memory usage: 1489.55 MB (1556.14, 1418.00, 1456.09, 1479.27, 1538.27)
```

**With this change**
```
[benchmark]   Averaqe Time: 1891.00 ms (2188.00, 1878.00, 1859.00, 1760.00, 1770.00)
[benchmark]   Average Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Peak Process usage: 2.00 process(es) (2.00, 2.00, 2.00, 2.00, 2.00)
[benchmark]   Average CPU usage: 184.63 % (208.48, 210.00, 178.07, 172.67, 153.91)
[benchmark]   Peak CPU usage: 420.00 % (640.00, 370.00, 370.00, 360.00, 360.00)
[benchmark]   Average Memory usage: 1118.72 MB (991.59, 1100.26, 1153.92, 1149.76, 1198.05)
[benchmark]   Peak Memory usage: 1278.98 MB (1658.93, 1145.76, 1160.33, 1182.18, 1247.69)
```

2020-06-22 13:26 UTC, JoostK requested changes

2020-06-22 13:26 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/tsc_plugin.ts
> +    this.host.postProgramCreationCleanup();
This looks incorrect. At least it disables the shim reference tagger, preventing sources files from being tagged. If this is not currently showing any issues it's likely to be because all files are included as root name, such that reference shimming is not required.

2020-06-22 13:26 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/tsc_plugin.ts
> +    const original: ts.SourceFile|undefined = ts.getOriginalNode(sf) as ts.SourceFile;
From looking at the source it can only be `undefined` if the input is `undefined`, or if a type guard function passed as second argument. So in this particular case I think you'd be fine with just `ts.getOriginalNode(sf)` without needing the `?? sf` fallback.

2020-06-22 13:26 UTC, JoostK commented on packages/compiler-cli/test/ngtsc/template_typecheck_spec.ts
> +      it('should allow for complete program reuse during incremental compilations', () => {
We should have a test with a component, as otherwise no TTC program has to be created. This currently only tests program -> program reuse, not program -> TC program -> program.

2020-06-22 18:24 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/template_typecheck_spec.ts
> +      it('should allow for complete program reuse during incremental compilations', () => {
It does have a component. The "stability" tests have a `beforeEach` which writes a component. I added `other.ts` so the program actually changes between compilations.

That's why I needed to add `getReuseTsProgram()` to the environment - because `getTsProgram()` returns the _emit_ program, not the template type-checking program that will be reused.

2020-06-22 18:24 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/tsc_plugin.ts
> +    this.host.postProgramCreationCleanup();
You're right, that should be in `setupCompilation`

2020-06-22 18:28 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/tsc_plugin.ts
> +    const original: ts.SourceFile|undefined = ts.getOriginalNode(sf) as ts.SourceFile;
Good to know that's been fixed then!

2020-06-22 18:28 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/testing/src/utils.ts
> +const STRUCTURE_IS_REUSED_COMPLETELY = 2;
Done!

2020-06-22 18:28 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/shims/src/util.ts
> +/**
Moved to `expando.ts`

2020-06-22 21:34 UTC, kyliau commented
Thank you @alan-agius4. Looking at the numbers, there is indeed an improvement in both time and memory usage, but they are pretty small. This gives us confidence that there is not significant regression in the external toolchain, therefore this commit is not v10.0.0 blocking. This will likely be released in v10.0.1.

2020-06-23 15:09 UTC, JoostK approved these changes

2020-06-23 18:03 UTC, josephperrott approved these changes
LGTM

Reviewed-for: dev-infra

2020-06-25 21:12 UTC, closed without merging