fix(core): fake_async_fallback should have the same logic with fake-async
angular/angular pull request #37680
Opened 2020-06-23 00:59 UTC by JiaLiPassion

PR #37523 failed when trying to use `rxjs delay` operator
inside `fakeAsync`, and the reasons are:

1. we need to import `rxjs-fake-async` patch to make the integration work.
2. since in `angular` repo, the bazel target `/tools/testing:node` not using `zone-testing` bundle,
instead it load `zone-spec` packages seperately, so it causes one issue which is the `zone.js/testing/fake-async`
package is not loaded, we do have a fallback logic under `packages/core/testing` calles `fake_async_fallback`,
but the logic is out of date with `fake-async` under `zone.js` package.

So this PR, I updated the content of `fake_async_fallback` to make it consistent with
`fake-async`. And I will make another PR to try to remove the `fallback` logic.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 37523

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-06-23 09:47 UTC, JoostK commented
Would this maybe also address #37653?

2020-06-23 13:25 UTC, atscott commented
[presubmit](http://test/OCL:317852724:BASE:317852737:1592918729076:f69f53b7)

2020-06-23 16:31 UTC, atscott commented on packages/core/testing/src/fake_async_fallback.ts
> +  if (_fakeAsyncTestZoneSpec) {
Hi Jia, should this be extracted to a shared method so we don't have to maintain two identical implementations here and in `fake-async.ts`? I noticed that these two methods are exactly the same and `fakeAsync` / `fakeAsyncFallback` are _almost_ the same so maybe there are some common blocks that can be extracted in those as well.

2020-06-23 17:37 UTC, JiaLiPassion commented on packages/core/testing/src/fake_async_fallback.ts
> +  if (_fakeAsyncTestZoneSpec) {
@atscott , yes, you are right, the code here is for some history reason, since the old `zone.js` doesn't have this logic, I will create another PR to remove all those `fallback` logic.

2020-06-23 17:40 UTC, atscott approved these changes

2020-06-29 17:32 UTC, mhevery requested changes
Could we have a test demonstrating the correct behavior?

2020-06-29 17:55 UTC, JiaLiPassion commented
@mhevery, there is test for the `patch Date` in `zone.js`, and the `fallback` logic doesn't have any test, since it should not be called at all, so this PR is a quick fix to make the current test work, I will create a follow up PR to remove all the `fallback` logic.

2020-06-29 18:01 UTC, mhevery approved these changes

2020-06-29 18:55 UTC, AndrewKushnir approved these changes

2020-06-29 19:23 UTC, closed without merging