build: upgrade angular build, integration/bazel and @angular/bazel package to rule_nodejs 2.2.0
angular/angular pull request #37727
Opened 2020-06-25 08:34 UTC by gregmagolan

Updates to rules_nodejs 2.2.0. This is the first major release in 7 months and includes a number of features as well
as breaking changes.

Release notes:
https://github.com/bazelbuild/rules_nodejs/releases/tag/2.0.0
https://github.com/bazelbuild/rules_nodejs/releases/tag/2.0.1
https://github.com/bazelbuild/rules_nodejs/releases/tag/2.0.2
https://github.com/bazelbuild/rules_nodejs/releases/tag/2.2.0

Features of note for angular/angular:

* stdout/stderr/exit code capture; this could be potentially be useful

* TypeScript (ts_project); a simpler tsc rule that ts_library that can be used in the repo where ts_library is too
  heavy weight

Breaking changes of note for angular/angular:

* loading custom rules from npm packages: `ts_library` is no longer loaded from `@npm_bazel_typescript//:index.bzl`
  (which no longer exists) but is now loaded from `@npm//@bazel/typescript:index.bzl`

* with the loading changes above, `load("@npm//:install_bazel_dependencies.bzl", "install_bazel_dependencies")` is
  no longer needed in the WORKSPACE which also means that yarn_install does not need to run unless building/testing
  a target that depends on @npm. In angular/angular this is a minor improvement as almost everything depends on @npm.

* @angular/bazel package is also updated in this PR to support the new load location; Angular + Bazel users that
  require it for ng_package (ng_module is no longer needed in OSS with Angular 10) will need to load from
  `@npm//@angular/bazel:index.bzl`. I investigated if it was possible to maintain backward compatability for the old
  load location `@npm_angular_bazel` but it is not since the package itself needs to be updated to load from
  `@npm//@bazel/typescript:index.bzl` instead of `@npm_bazel_typescript//:index.bzl` as it depends on ts_library
  internals for ng_module.

* runfiles.resolve will now throw instead of returning undefined to match behavior of node require

Other changes in angular/angular:

* integration/bazel has been updated to to use both ng_module and ts_libary with use_angular_plugin=true.
  This latter is the recommended way for rules_nodejs users to compile Angular 10 with Ivy. Bazel + Angular ViewEngine is
  supported with @angular/bazel <= 9.0.5 and Angular <= 8. There is still Angular ViewEngine example on rules_nodejs
  https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular_view_engine on these older versions but users
  that want to update to Angular 10 and are on Bazel must switch to Ivy and at that point ts_library with
  use_angular_plugin=true is more performant that ng_module. Angular example in rules_nodejs is configured this way
  as well: https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular. As an aside, we also have an
  example of building Angular 10 with architect() rule directly instead of using ts_library with angular plugin:
  https://github.com/bazelbuild/rules_nodejs/tree/stable/examples/angular_bazel_architect.

NB: ng_module is still required for angular/angular repository as it still builds ViewEngine & @angular/bazel
also provides the ng_package rule. ng_module can be removed in the future if ViewEngine is no longer needed in
angular repo.

* JSModuleInfo provider added to ng_module. this is for forward compat for future rules_nodejs versions.
  @josephperrott, this touches `packages/bazel/src/external.bzl` which will make the sync to g3 non-trivial.

2020-07-01 08:59 UTC, gregmagolan commented
Two fixes to rules_nodejs 2.0.0-rc.0 so far due to bugs that angular repo exposed:
1. https://github.com/bazelbuild/rules_nodejs/pull/1987; linker bug; landed and added test case
2. https://github.com/bazelbuild/rules_nodejs/pull/1991; ts_library + linker bug; pending

2020-07-10 20:36 UTC, jbedard commented
@angular/bazel/src/external.bzl also needs a minor change:

```
--- a/node_modules/@angular/bazel/src/external.bzl
+++ b/node_modules/@angular/bazel/src/external.bzl
@@ -2,11 +2,11 @@
 """
 
 load(
-    "@npm_bazel_typescript//internal:build_defs.bzl",
+    "@@npm//@bazel/typescript//internal:build_defs.bzl",
     _tsc_wrapped_tsconfig = "tsc_wrapped_tsconfig",
 )
 load(
-    "@npm_bazel_typescript//internal:common/compilation.bzl",
+    "@@npm//@bazel/typescript//internal:common/compilation.bzl",
     _COMMON_ATTRIBUTES = "COMMON_ATTRIBUTES",
     _COMMON_OUTPUTS = "COMMON_OUTPUTS",
     _DEPS_ASPECTS = "DEPS_ASPECTS",
@@ -14,7 +14,7 @@ load(
     _ts_providers_dict_to_struct = "ts_providers_dict_to_struct",
 )
 load(
-    "@npm_bazel_typescript//internal:ts_config.bzl",
+    "@@npm//@bazel/typescript//internal:ts_config.bzl",
     _TsConfigInfo = "TsConfigInfo",
 )
 load(

```

2020-07-17 03:05 UTC, alexeagle commented
🦸‍♀️

2020-07-17 08:29 UTC, petebacondarwin commented
@gregmagolan - could you make this PR "draft" so that it doesn't trigger review request from lots of the team?

2020-07-23 10:15 UTC, petebacondarwin commented on packages/localize/src/tools/BUILD.bazel
> +load("@npm//@bazel/typescript:index.bzl", "ts_config")
Perhaps we should have a macro for `ts_config` and then we would not have needed to update all these references to `@npm_bazel_typescript`, since the change would have been isolated to the `tools:defaults.bzl` file?

2020-07-23 10:17 UTC, petebacondarwin commented on tools/npm_integration_test/test_runner.js
> +          binary = (runfilesBinary && fs.existsSync(runfilesBinary)) ? runfilesBinary : binary;
NIT: This could be a bit simpler:

```suggestion
          try {
            const runfilesBinary = runfiles.resolveWorkspaceRelative(binary);
            binary = (runfilesBinary && fs.existsSync(runfilesBinary)) ? runfilesBinary : binary;
          } catch (e) {
          }
```

2020-07-23 10:18 UTC, petebacondarwin approved these changes
Reviewed-for: fw-i18n

2020-07-23 10:33 UTC, devversion commented on packages/localize/src/tools/BUILD.bazel
> +load("@npm//@bazel/typescript:index.bzl", "ts_config")
yeah, I'd like that too. That is one of the primary reasons why we proxy a lot of these things through `defaults.bzl` in the components repo. We should probably do it here too, but maybe as a follow-up.

2020-07-23 11:13 UTC, devversion reviewed
A few minor comments, but otherwise this looks great to me!

2020-07-23 11:13 UTC, devversion commented on packages/bazel/BUILD.bazel
> +        "//packages/bazel/src/ng_package:collect-type-definitions.bzl": "//:node_modules/@angular/bazel/src/ng_package/collect-type-definitions.bzl",
Given the comment below (on `_DEFAULT_ROLLUP` etc.) I think it would be better to always use `@npm//@angular/bazel`. Especially since binaries like `api-extractor` are accessed from there too (consistency might make debugging significantly easier here)

2020-07-23 11:13 UTC, devversion commented on tools/npm_integration_test/test_runner.js
> +fs.writeFileSync(nodePath, nodeContents, 'utf8');
Does this have the side-effect in non-sandbox environments (i.e. windows) to change the actual `build_bazel_rules_nodejs` repository? If so, that _could_ potentially cause a lot of confusion/debugging resources.

2020-07-23 15:43 UTC, josephperrott reviewed
Have we confirmed this updates effect on RBE?

2020-07-23 15:43 UTC, josephperrott commented on integration/bazel/tools/angular_ts_library.bzl
> +def ng_ts_library(**kwargs):
I agree that we should continue to use `ng_module` until we transition away from it in our actual builds as well.

But as @devversion mentioned, we should probably have tests set up for both of these.

2020-07-24 19:36 UTC, gregmagolan commented on integration/bazel/tools/angular_ts_library.bzl
> +def ng_ts_library(**kwargs):
Oh. I thought I switched it in the example. Agreed that we should keep coverage for ng_module but also add coverage for ts_library with use_angular_plugin. The two should be compatible so I'll update the integration test can be to exercise both.

2020-07-24 19:40 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +fs.writeFileSync(nodePath, nodeContents, 'utf8');
That is a very good point. With no sandbox this will modify the actual build_bazel_rules_nodejs. I need to think about how to get around this problem some more.

2020-08-10 17:43 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +          binary = (runfilesBinary && fs.existsSync(runfilesBinary)) ? runfilesBinary : binary;
Nice catch. Thanks.

2020-08-11 00:45 UTC, gregmagolan commented on integration/bazel/tools/angular_ts_library.bzl
> +def ng_ts_library(**kwargs):
Done. integraiton/bazel now tests both ng_module & ts_library with use_angular_plugin. Ivy only.

2020-08-11 00:50 UTC, gregmagolan commented on packages/bazel/src/ng_package/ng_package.bzl
> +_DEFAULT_ROLLUP = "@npm//@angular/bazel/src/ng_package:rollup_for_ng_package"
That is correct. We want to remove the hard-coded @npm here. Thanks.

2020-08-11 00:57 UTC, gregmagolan commented on packages/bazel/BUILD.bazel
> +        "//packages/bazel/src/ng_package:collect-type-definitions.bzl": "//:node_modules/@angular/bazel/src/ng_package/collect-type-definitions.bzl",
Yes. We can simplify to one substitution per package given the different location of `:`. Could potentially be done in a single regex with groups but doesn't seem worth the effort.
To your point of original vs. copied .bzl files. The copied one is the one that is typically loaded in user space so I'll change to,
```
        "//packages/bazel/src/ng_package:": "//:@angular/bazel/src/ng_package/",
        "//packages/bazel/src:": "//:@angular/bazel/src/",
```

2020-08-11 01:03 UTC, gregmagolan commented
> Have we confirmed this updates effect on RBE?

Doesn't fix OSX cross-platform after the Bazel 3.0 breakage. I need to dig into that at some point and fix the toolchains in Bazel to work with OSX. I presume linux is covered by CI?

2020-08-11 01:06 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +fs.writeFileSync(nodePath, nodeContents, 'utf8');
There are likely other issues with npm_integration_test and Windows. I don't think it works on Windows yet anyway so we may just have to detect if OS is WIndows and fail gracefully. However, the issue at hand here is non-sandbox envs which could be OSX & Linux as well if strategy is forced to local. Still thinking about this.

2020-08-11 01:08 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +fs.writeFileSync(nodePath, nodeContents, 'utf8');
Looks like that last issue with this upgrade.

2020-08-12 06:43 UTC, JiaLiPassion approved these changes
reviewed for @angular/fw-zones , LGTM!

2020-08-12 07:38 UTC, devversion commented on tools/npm_integration_test/test_runner.js
> +fs.writeFileSync(nodePath, nodeContents, 'utf8');
yeah, that is a good point. I agree with Windows being a good exception here. Also good point that other platforms could run in non-sandbox too.

One option might be to restore the binary file after test completion.. though that still has the risk of never cleaning up I'd guess.

2020-08-12 07:40 UTC, devversion commented on packages/bazel/src/ng_package/ng_package.bzl
> +_DEFALUT_TERSER_CONFIG_FILE = "//:node_modules/@angular/bazel/src/ng_package/terser_config.default.json"
Just coming back to this: Do you think it might make sense to just use `@npm//@angular/bazel` here too? That will make all labels to the Angular Bazel code consistent and the source of truth would be `external/npm/@angular/bazel` instead of a mix?

2020-09-08 18:59 UTC, gregmagolan commented
Sorted out the `--preserve-symlinks-main` issue upstream. When this lands https://github.com/bazelbuild/rules_nodejs/pull/2176 and we cut a 2.1.1 then this PR can finally be wrapped up.

2020-09-08 19:01 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +fs.writeFileSync(nodePath, nodeContents, 'utf8');
https://github.com/bazelbuild/rules_nodejs/pull/2176  will sort this out upstream

2020-09-10 18:34 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +fs.writeFileSync(nodePath, nodeContents, 'utf8');
updating to 2.2.0 which just got released makes this hack no longer necessary :)

2020-09-10 18:41 UTC, gregmagolan commented on packages/localize/src/tools/BUILD.bazel
> +load("@npm//@bazel/typescript:index.bzl", "ts_config")
good idea. there were only a handful of spots so added that change into this PR. thanks for the suggestion.

2020-09-10 18:48 UTC, gregmagolan commented on packages/bazel/src/ng_package/ng_package.bzl
> +_DEFALUT_TERSER_CONFIG_FILE = "//:node_modules/@angular/bazel/src/ng_package/terser_config.default.json"
Not entirely sure what you mean

2020-09-10 18:49 UTC, gregmagolan commented on packages/bazel/src/ng_package/ng_package.bzl
> +_DEFALUT_TERSER_CONFIG_FILE = "//:node_modules/@angular/bazel/src/ng_package/terser_config.default.json"
The default ```_DEFAULT_NG_PACKAGER = "//@angular/bazel/bin:packager"``` would be to the `@npm` workspace in user-land. That default is overridden in `/tools/defaults.bzl` to be ```_INTERNAL_NG_PACKAGE_PACKAGER = "//packages/bazel/src/ng_package:packager"``` since `@npm//@angular/bazel` does not exist during the angular build.

2020-09-10 18:55 UTC, devversion commented on packages/bazel/src/ng_package/ng_package.bzl
> +_DEFALUT_TERSER_CONFIG_FILE = "//:node_modules/@angular/bazel/src/ng_package/terser_config.default.json"
I might be missing something here but my understanding is that there will be two versions of `@angular/bazel`. 

* One in `external/npm/@angular/bazel`
* One in `external/npm/node_modules/@angular/bazel

We rely on the files from the first path in the majority of cases IIRC, but currently the rollup config and terser config are explicitly going with the latter. I'm proposing to use (1) here for consistency. If we have a mix of (1) and (2) then it will be hard to debug things (based on my experience in the past with how e.g. `npm_angular_bazel` has existed as separate repository)

2020-09-11 16:15 UTC, josephperrott reviewed
I think this looks overall good.  I am also curious about Paul's outstanding comment regarding loading via `//@npm` vs `//:node_modules`

2020-09-16 04:25 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +          } catch (e) {
The intention is that if `runfiles.resolveWorkspaceRelative(binary);` throws then the binary specified by the user is just a built-in command such as `mkdir` or `rm`.
For example,
```
commands = [
        "rm -rf ./.yarn_local_cache",
        "mkdir .yarn_local_cache",
        "$(rootpath @nodejs//:yarn_bin) install --cache-folder ./.yarn_local_cache",
        "$(rootpath @nodejs//:yarn_bin) test",
]
```

2020-09-16 04:25 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +          } catch (e) {
resolveWorkspaceRelative would resolve for something like `$(rootpath @nodejs//:yarn_bin)`

2020-09-16 04:25 UTC, gregmagolan commented on tools/npm_integration_test/test_runner.js
> +          } catch (e) {
I'll add a comment so this is clearer

2020-09-28 22:11 UTC, josephperrott approved these changes
LGTM

2020-09-29 15:03 UTC, josephperrott requested changes

2020-09-29 19:52 UTC, josephperrott commented
Caretaker Note: The local changes required `JSModuleInfo` in `ng_module` for g3 have already landed in google.

2020-09-29 21:43 UTC, gregmagolan commented on packages/bazel/src/ng_module.bzl
> +    "//packages/bazel/src:external.bzl",
that change doesn't look necessary; put it back to `":external.bzl"`

2020-09-29 21:44 UTC, gregmagolan commented
Rebased this and resolved a few inflight build failures with bazel load statements. I'll keep an eye on it and rebase it periodically as needed until it lands.

2020-09-29 22:19 UTC, josephperrott commented on packages/bazel/src/ng_package/ng_package.bzl
> +_DEFALUT_TERSER_CONFIG_FILE = "//:node_modules/@angular/bazel/src/ng_package/terser_config.default.json"
Can you confirm our understanding of this?

2020-09-30 02:57 UTC, AndrewKushnir approved these changes
Reviewed-for: fw-testing

2020-10-01 20:18 UTC, gregmagolan commented on packages/bazel/src/ng_package/ng_package.bzl
> +_DEFALUT_TERSER_CONFIG_FILE = "//:node_modules/@angular/bazel/src/ng_package/terser_config.default.json"
Okay. I think I understand what @devversion was getting at. It is a good question.

I suspect the better pattern is to use .js and other files required for rules from their installed node_modules location in @npm. We've discussed changing rules_nodejs to _only_ copy over .bzl and BUILD.bazel from `external/npm/node_modules/@scope/package` to `external/npm/@scope/package` instead of copying _all_files as it currently does. Not having duplicate copies would remove the ambiguity for debugging @devversion alluded to. Keeping this as

```
_DEFAULT_ROLLUP_CONFIG_TMPL = "//:node_modules/@angular/bazel/src/ng_package/rollup.config.js"
_DEFALUT_TERSER_CONFIG_FILE = "//:node_modules/@angular/bazel/src/ng_package/terser_config.default.json"
```

as it currently is would be forward compatible with that change.

Actually, to be completely portable, there can be no references to `@npm` in the published package. The pattern for @angular/bazel should be

```
            # BEGIN-INTERNAL
            "@npm" +
            # END-INTERNAL
            "//label:path"
```

otherwise it assumes @npm is the name of the external repository for the end-user.

I will add that change right now. Its a quick one.

2020-10-01 21:03 UTC, josephperrott approved these changes
LGTM

Reviewed-for: global-approvers

2020-10-01 22:34 UTC, closed without merging