fix(http): Add support for requesting body as URLSearchParams type
angular/angular pull request #37767
Opened 2020-06-26 03:34 UTC by sera0731

There is no support for URLSearchParams type request in the current version. This commit adds serialize body function for URLSearchParams type.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 36317

## What is the new behavior?
There is no support for URLSearchParams type request in the current version. When a user passes the body parameter with this type, Angular considers it as a random object. It ends up being omitted. This commit adds serialize body function for URLSearchParams type.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-06-26 04:25 UTC, alfaproject commented on packages/common/http/src/request.ts
> +function isURLSearchParams(value: any): value is URLSearchParams {
```suggestion
function isURLSearchParams(value: unknown): value is URLSearchParams {
```

2021-01-28 19:42 UTC, petebacondarwin requested changes
Hi @sera0731 - thanks for sending in this PR.

I note that @ajitsinghkaler also created a PR at #37852. But since yours came first I would like to help you to get this merged if you are still interested.

I think that serializing the value to a string is not the correct approach. Instead I think we should do similar to the other PR where we treat it like a special type that just gets passed through - like Blob and FormData.  The gives the most flexibility to the caller to then use the `URLSearchParams` API to extract what they want.

Can you update your code to do this and change the test accordingly?

2021-01-29 22:19 UTC, alxhub commented
👍 to @petebacondarwin's requests.

Additionally, this PR is currently 4 separate commits - it should probably be squashed into a single commit with the full implementation, and a commit message describing the changes being made and why in more detail.

2021-04-17 12:33 UTC, petebacondarwin commented
Reverting to #37852 due to a lack of response.

2021-04-17 12:33 UTC, closed without merging