refactor(compiler): Shorten %COMP% to %C%
angular/angular pull request #37775
Opened 2020-06-26 16:50 UTC by ngwattcos

This commit reduces the length of the component placeholder. No functionality changes.

Shortening the attribute allows a smaller bundle size and a smaller download before the platform-server shis the component attribute with component ID.

All spec tests involving %COMP% have been updated to use %C%.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-12-02 11:40 UTC, petebacondarwin requested changes
Hi @ngwattcos - sorry for the time it has taken to review this PR.
The tests have changed since you made it, so the files are now conflicted.
Further we are moving the compliance tests over to a new model, so this PR will need to update the new "test-cases" as well.

2021-11-02 22:58 UTC, jessicajaniuk commented
@ngwattcos @petebacondarwin This would be a great optimization to land. If we can get it rebased and updated, that would be great.

2021-11-06 13:41 UTC, petebacondarwin commented
Also, we determined that (although this shouldn't be) there is a chance of it being a breaking change, in the case where someone is relying upon the previous form of these ids.

2022-01-18 19:26 UTC, JoostK commented
Closing as stale

2022-01-18 19:26 UTC, closed without merging