fix(elements): elements should run in correct zone (#24181)
angular/angular pull request #37814
Opened 2020-06-29 00:43 UTC by remackgeek

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

When an angular element is created outside the angular zone, such as in setTimeout(), automatic change detection no longer works

Issue Number:  [#24181](https://github.com/angular/angular/issues/24181)

## What is the new behavior?
ComponentNgElementStrategy captures the zone it was created in and insures all methods are run in that zone.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## Other information

2020-06-29 13:46 UTC, kseamon commented
As I had commented way back, what this is still missing is exiting the NgZone in outputs - we don't want to leak our app's NgZone to the parent app (which would cause unrelated activities in the parent app to trigger change detection within the wrapped child application).

2020-06-29 15:40 UTC, gkalpak commented
For reference: There is some relevant discussion in #24185.

2020-06-29 19:06 UTC, gkalpak commented
@kseamon, can you give an example of the problem (I don't quite understand how we can "leak" our Zone).
Also, is this issue something that is introduced by this PR? Or is it possible that this "Zone leaking" can happen today (without the PR)?

2020-06-29 20:23 UTC, kseamon commented
It would look something like this:

// Parent app
ngElementNode.addEventListener('customEvent', () => {
  setTimeout(() => {
    doSomethingUnrelated();
    // Whoops we just triggered CD within the Angular Element.
  });
});

2020-06-30 13:56 UTC, gkalpak commented
Since this change is unrelated to this PR, I consider it outside of scope for this PR. Feel free to create an issue about so we can discuss there.

##
On a quick note:

I wouldn't expect Zones to be leaked the way you described (neither with nor without the changes in this PR). If I am not mistaken, what matters is the Zone in which you subscribe to the observable and this happens in the CustomElement's [connectedCallback()][1] and is not affected by the strategy's `runInZone()`.

If anything, we might need to enter the Zone in the event listener callback, if the element is created in a way that causes its `connectedCallback()` method to be called outside of the Angular Zone 😛

<sub>I only took a quick look, so I may have missed something. We should take a closer look and look at concrete examples (both with and without CustomElement polyfills).</sub>

[1]: https://github.com/angular/angular/blob/71956250ddc7faee2a813c293f4ebf91a1509afa/packages/elements/src/create-custom-element.ts#L189-L214

2020-06-30 15:00 UTC, gkalpak requested changes
Thx for working on this, @remackgeek!

I think this is heading into the right direction. I have left a few minor comments.
Can you also please rebase on latest master and squash the commits into one?

##
BTW, it would be great to have a more realistic test via an actual example app (either in [packages/examples/][1] or in [integration/][2] (similar to or as part of [integration/ng_elements/][3])), but that might be too much to ask for this PR :grin:

[1]: https://github.com/angular/angular/tree/71956250ddc7faee2a813c293f4ebf91a1509afa/packages/examples
[2]: https://github.com/angular/angular/blob/71956250ddc7faee2a813c293f4ebf91a1509afa/integration
[3]: https://github.com/angular/angular/blob/71956250ddc7faee2a813c293f4ebf91a1509afa/integration/ng_elements

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/src/component-factory-strategy.ts
> +  private readonly zoneless: boolean;
Let's move the initialization here. I would also consider renaming this to `isZoneless`:

```suggestion
  private readonly isZoneless = typeof Zone === 'undefined';
```

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/src/component-factory-strategy.ts
> +  private runInZone(fn: () => any) {
Please move private methods below protected ones. (Although I have no idea why they are protected instead of private 🤷)

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/src/component-factory-strategy.ts
> +  private runInZone(fn: () => any) {
Please use `unknown` instead of `any` whenever possible.

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/src/component-factory-strategy.ts
> +  /** service for setting zone context */
```suggestion
  /** Service for setting zone context. */
```

(for consistency 😇)

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/src/component-factory-strategy.ts
> +  private readonly ngZone: NgZone;
Let's move the initialization here:

```suggestion
  private readonly ngZone = this.injector.get<NgZone>(NgZone);
```

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/src/component-factory-strategy.ts
> +  /** the zone the element was created in */
```suggestion
  /** The zone the element was created in or `null` if Zone.js is not loaded. */
```

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/src/component-factory-strategy.ts
> +  private readonly elementZone: Zone|undefined;
Can we move the initialization here?

```suggestion
  private readonly elementZone = (typeof Zone === 'undefined') ? null : this.ngZone.run(() => Zone.current);
```

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/src/component-factory-strategy.ts
> +  private readonly zoneless: boolean;
Actually, do we need this extra property? Couldn't we use `elementZone` being `undefined` (or `null`) instead?

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +    });
This doesn't seem to add much value (just asserting internal implementation details). Let's remove it.

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +      ngZone.run.calls.reset();
Is this necessary?

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +    it('should run already in original zone', () => {
Consider something more descriptive, such as:

```suggestion
    it('should run the callback directly when invoked in element\'s zone', () => {
```

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +    it('should run placed in original zone', () => {
```suggestion
    it('should run the callback inside the element\'s zone when invoked in a different zone', () => {
```

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +      ngZone.run.calls.reset();
Is this necessary?

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +      expect(ngZone.run).toHaveBeenCalled();
Can you also verify that it was called with the correct callback?

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +  });
Please add some tests emulating a zoneless setup.

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +    });
```suggestion
    ngZone.run.and.callFake((fn: () => unknown) => fn());
```

2020-06-30 15:00 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +    });
This implementation does not look very robust or easy to work with. How about something like:

```ts
describe('ComponentFactoryNgElementStrategy', () => {
  ...
  let injectables: Map<Type, unknown>;

  beforeEach(() => {
    ...

    injector = jasmine.createSpyObj('injector', ['get']);
    injector.get.and.callFake((token: Type) => {
      if (!injectables.has(token)) {
        throw new Error(`Failed to get injectable from mock injector: ${token}`);
      }

      injectables.get(token);
    });

    ...

    injectables = new Map([
      [ApplicationRef, applicationRef],
      [NgZone, ngZone],
    ]);
  });

  ...
});
```

Then, if a test needs to inject somethine else, it can do `injectables.set(<token>, <value>). E.g.:

```ts
injectables.set(ComponentFactoryResolver, factoryResolver);
```

2020-07-01 15:02 UTC, remackgeek commented on packages/elements/test/component-factory-strategy_spec.ts
> +      ngZone.run.calls.reset();
Yes, ngZone.run() gets called once during construction of the strategy (setting elementZone).

2020-07-01 15:10 UTC, remackgeek commented on packages/elements/test/component-factory-strategy_spec.ts
> +      expect(ngZone.run).toHaveBeenCalled();
I'm not sure what you're asking for here. Don't those 2 expectations show that the callback was called and in the correct way?

2020-07-01 15:32 UTC, remackgeek commented on packages/elements/test/component-factory-strategy_spec.ts
> +      ngZone.run.calls.reset();
Yes, ngZone.run() gets called once during construction of the strategy (setting elementZone).

2020-07-02 15:06 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +      expect(ngZone.run).toHaveBeenCalled();
The current assertions prove that the callback was called and that `ngZone.run()` was called. But they don't prove that the callback was called by `ngZone.run()`. (For all we know, we could be doing something like `callback(); ngZone.run(() => {});` and the test would still pass :grin:)

2020-07-02 15:08 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +      ngZone.run.calls.reset();
Right. In that case, can you move the `ngZone.run.calls.reset()` call right below the strategy construction?

2020-07-04 12:56 UTC, gkalpak requested changes

2020-07-04 12:56 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +  let factoryResolver: any;
This is only used in one tests. There is no benefit in having it as a `describe`-wide variable here.

2020-07-04 12:56 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +    factoryResolver = jasmine.createSpyObj('factoryResolver', ['resolveComponentFactory']);
```suggestion
    const factoryResolver = jasmine.createSpyObj('factoryResolver', ['resolveComponentFactory']);
```

2020-07-04 12:56 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +         expect(ngZone.run).toHaveBeenCalled();
This is now redundant (since it is covered by the `toHaveBeenCalledWith()` below):

```suggestion
```

2020-07-04 12:56 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +    it('should run the callback directly when called without without zone.js loaded', () => {
```suggestion
    it('should run the callback directly when called without zone.js loaded', () => {
```

2020-07-04 12:56 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +  let injectables: Map<unknown, unknown>;
Couldn't this be `Map<Type, unknown>` (or `Map<Type<unknown>, unknown>`)?

2020-07-04 20:14 UTC, remackgeek commented on packages/elements/test/component-factory-strategy_spec.ts
> +  let injectables: Map<unknown, unknown>;
Those don't work because `ComponentFactoryResolver` is an abstract class. You get this:
**Argument of type 'typeof ComponentFactoryResolver' is not assignable to parameter of type 'Type<unknown>'.
  Cannot assign an abstract constructor type to a non-abstract constructor type.ts(2345)**

Using `unknown` makes this inconsistent:
` injector.get.and.callFake((token: Type<unknown>) => {`
but typescript didn't catch it and it works at runtime. Should I change it to `unknown` or leave it because it's more descriptive of what's going on?

2020-07-04 20:39 UTC, gkalpak commented on packages/elements/test/component-factory-strategy_spec.ts
> +  let injectables: Map<unknown, unknown>;
Yeah, in that case, `unknown` sounds good.

2020-07-06 14:04 UTC, gkalpak approved these changes
LGTM - Thx, @remackgeek ✨
Can you please update [goldens/size-tracking/aio-payloads.json#L15][1] to the new size?

For reference, this PR increases the angular.io main bundle by 295B (451100B --> 451395B). I inspected the bundle and confirmed that the only difference is the updated `ComponentFactoryNgStrategy` class.

[1]: https://github.com/angular/angular/blob/196bfa8fae6b7da9df2601a400164e35e45cefd6/goldens/size-tracking/aio-payloads.json#L15

2020-07-16 00:56 UTC, jelbourn approved these changes
LGTM

Reviewed-for: size-tracking

2020-07-16 21:10 UTC, petebacondarwin commented
Can you rebase and fix the size-tracking conflict so that we can approve for `size-tracking`?

2020-07-17 02:53 UTC, remackgeek commented
Rebased, broken size tracking changed to match actuals (not sure what else to put there).

2020-07-17 09:45 UTC, petebacondarwin approved these changes
Reviewed-for: size-tracking

2020-07-17 09:45 UTC, petebacondarwin commented
Awesome thanks!

2020-07-17 15:07 UTC, kyliau commented
presubmit: http://test/OCL:321780152:BASE:321780169:1594998439408:2f37a981

2020-07-21 23:56 UTC, AndrewKushnir commented
[Presubmit #2](http://test/OCL:322471863:BASE:322471888:1595375776801:19f72b8f) (will also start global presubmit in a couple hours).

2020-07-23 03:35 UTC, closed without merging