docs: mention for depreciation for `Testbed.get()`
angular/angular pull request #37815
Opened 2020-06-29 07:26 UTC by OmarioHasan

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
There is no mention for the depreciation in v12 for `Testbed.get()` and this is announced in https://angular.io/guide/deprecations

Issue Number: N/A

## What is the new behavior?

As mention in https://angular.io/guide/deprecations for this API, it may be important mention for this to make developers migrate or avoid using it

![image](https://user-images.githubusercontent.com/8146344/85985107-813d8580-b9ea-11ea-9af0-2245a876d300.png)

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-06-29 07:28 UTC, OmarioHasan commented
@googlebot I signed it!

2020-06-29 17:55 UTC, AndrewKushnir requested changes

2020-06-29 17:55 UTC, AndrewKushnir commented on aio/content/guide/testing.md
> +**Note:** We used to have `TestBed.get()` - **will be deprecated in v12** - instead of `TestBed.inject()`.
Hi @OmarioHasan, the `TestBed.get` function is already deprecated (see [TestBed.get docs here](https://angular.io/api/core/testing/TestBed#get)) and it might be removed from Angular codebase starting from v12. So may be we can add a comment regarding that at the end of this section, for example (see last sentence):
```
We decided to migrate to a new function instead of updating the existing one given
the large scale use that would have an immense amount of breaking changes.
The `get` method was deprecated since v9 and might be removed in one of the future versions of Angular.
```
I'm also adding @kapunahelewong as a reviewer to this PR to get some input from docs perspective (whether we have similar cases in other parts of docs and whether adding one here is needed).
Thank you.

2020-06-30 06:34 UTC, OmarioHasan commented on aio/content/guide/testing.md
> +**Note:** We used to have `TestBed.get()` - **will be deprecated in v12** - instead of `TestBed.inject()`.
Thanks for your reply 
I've made the change as you suggest it's perfect to describe the status for this API 
and waiting for review or for any changing

2020-06-30 08:42 UTC, OmarioHasan commented
@kapunahelewong  i'm tried to fix this commit message but failed will I have to make another PR or there is something to do?

2020-06-30 09:30 UTC, OmarioHasan commented
@AndrewKushnir  sorry for re-requesting review it's my fault

2020-07-01 15:43 UTC, kapunahelewong commented on aio/content/guide/testing.md
> +**Note:** We used to have `TestBed.get()` - **will be deprecated in v12** - instead of `TestBed.inject()`.
How about replacing the entire note with this instead?

```
`TestBed.get()` was deprecated as of Angular version 9. 
To help minimize breaking changes, Angular introduces a 
new function called `TestBed.inject()`, which you should use instead. 
For information on the removal of `TestBed.get()`, 
see its entry in the [Deprecations index](guide/deprecations#index).
```

The reason I'm suggesting something so different is because the writing as it is in there currently still needs to be aligned with the Google doc styles. We are supposed to avoid the use of first person ("we") and limit referencing future plans. Since the future of a deprecated feature is still important, though, we can link to it. This way, we're also keeping the info in one place in case plans shift.

What do you two think? Does this help?

2020-07-01 15:48 UTC, OmarioHasan commented on aio/content/guide/testing.md
> +**Note:** We used to have `TestBed.get()` - **will be deprecated in v12** - instead of `TestBed.inject()`.
it's amazing refactor @kapunahelewong 
can i make this change or wait for Andrew opinion ?

2020-07-01 16:10 UTC, kapunahelewong commented on aio/content/guide/testing.md
> +**Note:** We used to have `TestBed.get()` - **will be deprecated in v12** - instead of `TestBed.inject()`.
Thank you, @OmarioHasan! 😊 Let's see what Andrew thinks.

2020-07-01 17:26 UTC, AndrewKushnir commented on aio/content/guide/testing.md
> +**Note:** We used to have `TestBed.get()` - **will be deprecated in v12** - instead of `TestBed.inject()`.
That looks great, thanks @kapunahelewong 👍

2020-07-01 17:27 UTC, OmarioHasan commented on aio/content/guide/testing.md
> +**Note:** We used to have `TestBed.get()` - **will be deprecated in v12** - instead of `TestBed.inject()`.
can i update this commit with her edits and push again ?

2020-07-01 17:29 UTC, AndrewKushnir commented on aio/content/guide/testing.md
> +**Note:** We used to have `TestBed.get()` - **will be deprecated in v12** - instead of `TestBed.inject()`.
@OmarioHasan, feel free to use the proposed update from @kapunahelewong. Please let us know (by sending a message here) once the update is made, so we can perform final review. Thank you.

2020-07-01 18:01 UTC, AndrewKushnir approved these changes
LGTM 👍 Thanks for the update @OmarioHasan.

2020-07-01 18:04 UTC, OmarioHasan commented
@AndrewKushnir it's my first contribution thanks for your encouragement it will never be the last

2020-07-01 18:13 UTC, OmarioHasan commented on aio/content/guide/testing.md
> +**Note:** We used to have `TestBed.get()` - **will be deprecated in v12** - instead of `TestBed.inject()`.
@AndrewKushnir  @kapunahelewong  all tests are passed

2020-07-01 18:19 UTC, kapunahelewong approved these changes
LGTM! Thank you so much, @OmarioHasan!

Reviewed-for: global-docs-approvers

2020-07-01 18:27 UTC, kapunahelewong commented
Hey @OmarioHasan, I just squashed the three commits so we'd just have one. (I only noticed after approving.) As soon as everything passes, I can mark it for merge. Woo!

2020-07-01 18:30 UTC, OmarioHasan commented
@kapunahelewong It's really an awesome feeling for my contribution to my lovely framework, I'm very glad to your encourage and hope to do more

2020-07-01 19:17 UTC, OmarioHasan commented
@kapunahelewong  it's ready now 🎉🎉🎉

2020-07-02 11:49 UTC, OmarioHasan commented
@kapunahelewong  is there any missed changes from my side

2020-07-02 14:17 UTC, kapunahelewong commented
@OmarioHasan, you have everything perfectly ready!

2020-07-06 20:42 UTC, closed without merging