fix(zone.js): remove global declaration
angular/angular pull request #37861
Opened 2020-06-30 22:05 UTC by JiaLiPassion

Close #37531

Remove `global` declaration in zone.ts to avoid compile error when
upgrade to `@types/node`.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 37531

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-07-15 19:10 UTC, mhevery approved these changes

2020-07-16 18:08 UTC, mhevery commented
[presubmit](http://test/OCL:321604106:BASE:321604156:1594922892130:a09509ed)

2020-07-16 18:14 UTC, mhevery commented
CARETAKER: Needs cl/321604430

2020-07-24 22:42 UTC, mhevery commented
This is failing with 
```
third_party/javascript/angular2/rc/packages/zone.js/lib/zone.ts:1437:86 - error TS2304: Cannot find name 'global'.

1437 })(typeof window !== 'undefined' && window || typeof self !== 'undefined' && self || global);
```

I think adding 
```
(typeof window !== 'undefined' && window || typeof self !== 'undefined' && self || typeof global !== 'undefined' && global);
```

solves the problem.

2020-07-24 22:52 UTC, JiaLiPassion commented
@mhevery , got it, thanks, I just updated the `zone.ts`.

2020-07-27 18:02 UTC, mhevery commented
[presubmit](http://test/OCL:321604106:BASE:323396881:1595872926994:2beef057)

2020-07-27 18:04 UTC, mhevery commented
Argh! Seems like that did not help. :-(

```
third_party/javascript/angular2/rc/packages/zone.js/lib/zone.ts:1438:11 - error TS2304: Cannot find name 'global'.

1438    typeof global !== 'undefined' && global);
               ~~~~~~
third_party/javascript/angular2/rc/packages/zone.js/lib/zone.ts:1438:37 - error TS2304: Cannot find name 'global'.

1438    typeof global !== 'undefined' && global);
                                         ~~~~~~
```

2020-07-27 23:28 UTC, JiaLiPassion commented
@mhevery, The motivation is the issue #37531, 
```
In DefinitelyTyped/DefinitelyTyped#44700, the type definition of the global variable was updated to NodeJS.Global & typeof globalThis. Which makes the Zone.js package not compatible with @types/node 14.0.5 or up.
```

I will update the `global` type definition to match the new `nodejs` definition.

2020-07-30 12:06 UTC, JiaLiPassion commented
@mhevery , for now I updated the global declaration to `any` just like https://github.com/angular/angular/blob/master/packages/core/src/util/global.ts#L14. 
After we updated `@types/node` to `v14+`, I will update the `global` type again.

2020-07-30 20:31 UTC, mhevery approved these changes

2020-07-30 20:32 UTC, mhevery commented
Hmm, it seems like the build system does not like that.

2020-08-15 23:00 UTC, dag03tsc commented
The `@types/node` module loads before the `zone.js` one and it declares the global variable so its type can't be changed later.

Therefore, I think the solution could be, in fact, to exactly mirror the global declaration (Or maybe remove it instead?).

I've bypassed this since the bug appeared by applying the next patch after `npm install`.

> --- node_modules/zone.js/dist/zone.js.d.ts
> +++ node_modules/zone.js/dist/zone.js.d.ts
> @@ -600,34 +600,54 @@
> -declare var global: NodeJS.Global;
> +declare var global: NodeJS.Global & typeof globalThis;
> 
> --- node_modules/zone.js/lib/zone.d.ts
> +++ node_modules/zone.js/lib/zone.d.ts
> @@ -600,34 +600,54 @@
> -declare var global: NodeJS.Global;
> +declare var global: NodeJS.Global & typeof globalThis;

It doesn't generate any side effects and everything seems alright so far.

I guess the global type should be declared as `NodeJS.Global & typeof globalThis` instead of `any`.

Maybe removing it could solve it too, just by letting the `@types/node` handle it all, but I'm not sure if it'd carry any unwanted side effects due to the missing declaration if, somehow, `@types/node` isn't available, so the first option seems safer.

2020-08-16 02:15 UTC, ghost approved these changes

2020-08-16 02:15 UTC, kenaidri commented on packages/zone.js/lib/zone.ts
> -declare var global: NodeJS.Global;
Thanks

2020-08-16 03:16 UTC, dag03tsc commented on packages/zone.js/lib/zone.ts
> -declare var global: NodeJS.Global;
Oh! I see! I didn't knew about the suggestion feature. Thanks @kenaidri!

2020-08-16 03:22 UTC, dag03tsc commented on packages/zone.js/lib/zone.ts
> +declare var global: any;
```suggestion
declare var global: NodeJS.Global & typeof globalThis;
```
Make sure that the global type match the one provided by the current `@types/node` module.

2020-08-16 03:23 UTC, dag03tsc commented on packages/zone.js/package.json
> +    "@types/node": "^14.0.5",
```suggestion
    "@types/node": "^14.0.27",
```
Upgrade `@types/node` to last version.

2020-08-16 03:35 UTC, JiaLiPassion commented on packages/zone.js/package.json
> +    "@types/node": "^14.0.5",
Yeah, we have to wait for node in `angular` repo update to `14.0.27+` and continue on this PR later.

2020-08-16 03:36 UTC, dag03tsc commented on packages/zone.js/test/common/zone.spec.ts
> +          (global as any).Promise = WrongPromise;
```suggestion
          global.Promise = WrongPromise;
```
I'm not actually sure about this one. How do you think it should be done?
 - [X]  Leave global uncasted as it was before.
 - [ ]  Replace the `any` global cast with a `(NodeJS.Global & typeof globalThis)` one.
 - [ ]  Don't change anything at all.

2020-08-16 03:54 UTC, dag03tsc requested changes
Upgrade `@types/node` from `v14.0.5` to `v14.0.27`.
Mirror the global declaration provided by the `@types/node` module ([breaking change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44700)).

Edit: I apologize for sending 4 reviews in a row. It's been an error due to my lack of experience with the suggestion feature! I've learnt the lesson and next times I'll start a review instead of adding single comments!

2020-08-16 03:58 UTC, dag03tsc commented on packages/zone.js/package.json
> +    "@types/node": "^14.0.5",
I see. Nevermind!

2020-08-16 04:25 UTC, JiaLiPassion commented
@dag03tsc , no problem, thank you for the review, `nodejs` update may not happen right now, will continue working on this PR after that.

2020-09-28 21:05 UTC, josephperrott approved these changes
LGTM

Reviewed-for: dev-infra

2020-10-22 14:33 UTC, josephperrott commented
Caretaker Note: This will require cl/338344996 to land before it can be merged.

2020-10-22 23:06 UTC, AndrewKushnir commented
@josephperrott @JiaLiPassion based on the "target: major" label and the current state of release train, this PR will be included into v12 (and will not land in upcoming v11). The target was set a couple months ago, so I believe the intention was to land it in v11, so should we change the label to "target: rc" to reflect that? Please confirm.

2020-10-23 00:15 UTC, JiaLiPassion commented
@AndrewKushnir , yes, this one is targeting `v11`, I have updated the label to `target: rc`.

2020-10-23 22:19 UTC, closed without merging