fix(compiler): check more cases for pipe usage inside host bindings
angular/angular pull request #37883
Opened 2020-07-02 06:10 UTC by crisbeto

Builds on top of #34655 to support more cases that could be using a pipe inside host bindings (e.g. ternary expressions or function calls).

Fixes #37610.

2020-07-02 16:10 UTC, JoostK requested changes

2020-07-02 16:10 UTC, JoostK commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +    it('should throw if a pipe is used inside a conditional in a host binding', () => {
I think these detailed tests would be more appropriate as simple unit tests here:

https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/compiler/test/expression_parser/parser_spec.ts#L728-L732

2020-07-02 16:10 UTC, JoostK commented on packages/compiler/src/expression_parser/parser.ts
> +    ast.expression.visit(this, context);
I think it's best for this class to use `RecursiveAstVisitor` as base class. That would require that `SimpleExpressionChecker` becomes an interface, but that should be a quick change to make.

2020-07-02 16:10 UTC, JoostK commented on packages/compiler/src/expression_parser/parser.ts
> +  }
These are missing the visits of `target`/`receiver`. One of the reasons why I'd prefer we switch this over to `RecursiveAstVisitor` :-)

2020-07-04 07:49 UTC, crisbeto commented
Thanks for the feedback @JoostK, the recursive visitor definitely cleaned things up 👍. Can you take another look?

2020-07-04 10:21 UTC, JoostK approved these changes
LGTM

2020-07-10 18:00 UTC, closed without merging