fix(common): add body to delete request
angular/angular pull request #37894
Opened 2020-07-02 16:27 UTC by ajitsinghkaler

delete request supports a body but it was left out as many dont support the http body. As it is supported by default so angular should not take any decision weather to add it or not the decision should be given to the developer

Fixes #19438

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Delete request cannot send a body

Issue Number: #19438

## What is the new behavior?
Delete request can send a body

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## Other information

2020-07-14 21:52 UTC, jelbourn commented
This change, as is, looks like it's a pretty big breaking change. I'm wondering if we can make it a non-breaking change by adding more method overloads, and then having the concrete implementation handle the difference in behavior for two vs. three arguments. Otherwise, it would take a large effort to land this change, which probably isn't the most valuable use of resources (compared to other higher priority issues/features).

2020-07-15 04:54 UTC, ajitsinghkaler commented
@jelbourn but overloads will create confusion that sometimes the second parameter of the function is the options and sometimes the third.

We can create the body as the third parameter in that case but the main problem is that it will not conform with the style of post and put request.

2020-07-16 00:44 UTC, jelbourn commented
Yeah, I don't see adding the body as a third argument as a viable option. Unfortunately, just making this breaking change is also not a viable option. Changes like this are genuinely painful for both our customers and the team ourselves, because we're responsible for updating all usage inside Google (which has to happen as part of landing the change because [all of Google is one massive repo where everything is at head all the time](https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext)).

2020-07-16 16:30 UTC, ajitsinghkaler commented
@jelbourn so what do you think we should do it's a highly requested feature 66 likes or should I drop this pr

2020-07-16 20:57 UTC, petebacondarwin requested changes
I don't think we should land this PR. The large breaking change or inconsistent API is not offset by the minimal benefit to developers.

There is a perfectly reasonable workaround, which is to use the `client.request()` method: https://github.com/angular/angular/issues/19438#issuecomment-346596988

2020-07-16 23:21 UTC, jelbourn commented
If we could make it work in an ergonomic way with overloads it could be doable, but I don't see a practical way to move forward on this in any near timeframe.

2020-07-18 14:02 UTC, closed without merging