docs: Refactor feature-modules.md to make it a tutorial
angular/angular pull request #37948
Opened 2020-07-06 23:01 UTC by rockument69

Project DOCS-738 to make the topic easier to understand. In addition,
make corrections based on customer issue 21531.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Mistakes in the NgModule guide.
In addition, the NgModule section is too long and confusing. This is one of the “buried” tutorials that we need to highlight as a tutorial in the Tutorials section.

Issue Number: 21531

## What is the new behavior?
The refactoring creates the basic steps for the tutorial. Changes are made to the example descriptions to clarify or remove "mistakes" in the doc.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-07-06 23:13 UTC, mary-poppins commented
You can preview 78f70df at https://pr37948-78f70df.ngbuilds.io/.

2020-07-07 22:14 UTC, mary-poppins commented
You can preview 206de7a at https://pr37948-206de7a.ngbuilds.io/.

2020-07-07 23:33 UTC, mary-poppins commented
You can preview 748e9de at https://pr37948-748e9de.ngbuilds.io/.

2020-07-13 15:39 UTC, jbogarthyde commented
- If this is a tutorial, it should go into the Tutorials doc section
- Do you want to keep the term "feature module", so identify the design pattern of creating modules for an app's features? If so, the name should be something like "Create a feature module". Then it can be described, at the beginning, as using NgModules to facilitate a modular approach to app design.

2020-07-13 18:25 UTC, rockument69 commented
> * If this is a tutorial, it should go into the Tutorials doc section
> * Do you want to keep the term "feature module", so identify the design pattern of creating modules for an app's features? If so, the name should be something like "Create a feature module". Then it can be described, at the beginning, as using NgModules to facilitate a modular approach to app design.

@jbogarthyde : Yes, this is a tutorial. I included an edit to navigation.json to move this doc from the NgModules section of Fundamentals to the Tutorials. However this change doesn't show up in the previews. I'm not sure why.

2020-07-13 21:55 UTC, mary-poppins commented
You can preview 1bfc4e3 at https://pr37948-1bfc4e3.ngbuilds.io/.

2020-07-14 16:58 UTC, mary-poppins commented
You can preview d91879f at https://pr37948-d91879f.ngbuilds.io/.

2020-07-14 23:17 UTC, mary-poppins commented
You can preview c861acd at https://pr37948-c861acd.ngbuilds.io/.

2020-07-15 17:58 UTC, mary-poppins commented
You can preview 0d47df1 at https://pr37948-0d47df1.ngbuilds.io/.

2020-07-16 17:17 UTC, mary-poppins commented
You can preview e8957b7 at https://pr37948-e8957b7.ngbuilds.io/.

2020-07-17 16:52 UTC, mary-poppins commented
You can preview 0679bfe at https://pr37948-0679bfe.ngbuilds.io/.

2020-07-20 16:53 UTC, mary-poppins commented
You can preview 9cf23e4 at https://pr37948-9cf23e4.ngbuilds.io/.

2020-07-21 20:52 UTC, mary-poppins commented
You can preview ce0ae79 at https://pr37948-ce0ae79.ngbuilds.io/.

2020-07-22 21:47 UTC, mary-poppins commented
You can preview 277828e at https://pr37948-277828e.ngbuilds.io/.

2020-07-27 23:06 UTC, mary-poppins commented
You can preview 33eeaad at https://pr37948-33eeaad.ngbuilds.io/.

2020-07-28 22:21 UTC, mary-poppins commented
You can preview 97c3d1b at https://pr37948-97c3d1b.ngbuilds.io/.

2020-07-29 21:38 UTC, mary-poppins commented
You can preview c0f03b9 at https://pr37948-c0f03b9.ngbuilds.io/.

2020-07-29 22:01 UTC, mary-poppins commented
You can preview 02aed3f at https://pr37948-02aed3f.ngbuilds.io/.

2020-07-29 22:13 UTC, mary-poppins commented
You can preview 1f07e31 at https://pr37948-1f07e31.ngbuilds.io/.

2020-07-30 20:51 UTC, kapunahelewong requested changes
It's looking good, @rockument69! 

As I mentioned in an offline conversation we generally use just `1.` to denote each item in a numbered list. That is, each list item gets 1. at the beginning. This way markdown will number the items automatically so you don’t have to do it manually. It seems a little weird and you have to be mindful of the spacing, especially when a list item has code snippets in it. I’d recommend playing around with it to get the hang of it (and when you know everything else is rendering correctly) as sometimes, lists with code samples and multiple paragraphs can break with a subtle misstep of alignment.

2020-07-30 20:51 UTC, kapunahelewong commented on aio/content/guide/feature-modules.md
> +To add a component to the new NgModule, enter the following CLI command, specifying the generated folder for the NgModule (`customer-dashboard`) and the component name (`CustomerDashboard`):
```suggestion
To add a component to the new NgModule, enter the following CLI command, which specifes the folder for the NgModule, `customer-dashboard`, and the component name `CustomerDashboard`:
```

2020-07-30 20:51 UTC, kapunahelewong commented on aio/content/guide/feature-modules.md
> +This command generates a folder for the new component within the `customer-dashboard` folder, and updates the `customer-dashboard.module.ts` file with the `CustomerDashboardComponent` info:
You might be able to combine this sentence with the next (line 147) as they are covering very similar ground.

2020-07-30 20:51 UTC, kapunahelewong commented on aio/content/guide/feature-modules.md
> +* Specify only [declarables](guide/glossary#declarable "Definition of a declarable") (component, directives, and pipes) in the `declarations` array.
```suggestion
* Specify only [declarables](guide/glossary#declarable "Definition of a declarable")&mdash;components, directives, and pipes&mdash;in the `declarations` array.
```

2020-07-30 20:51 UTC, kapunahelewong commented on aio/content/guide/feature-modules.md
> +* Declare these classes in an NgModule _only if_ they belong to that NgModule.
```suggestion
* Declare these classes in an NgModule _only_ if they belong to that NgModule.
```

Did you mean to include the "if"?

2020-07-30 20:51 UTC, kapunahelewong commented on aio/content/guide/feature-modules.md
> +* Do _not_ declare a class that's already declared in another NgModule, whether it be in the root NgModule, another NgModule, or a third-party NgModule.
Bravo for the subjunctive! 🎉

2020-07-30 20:51 UTC, kapunahelewong commented on aio/content/guide/feature-modules.md
> +If you add service providers to the new NgModule, `AppModule` would know about those too, so that they can be used by other NgModules.
You could link to the [hierarchical injectors guide](https://angular.io/guide/hierarchical-dependency-injection) here or the [DI intro page](.io/guide/dependency-injection). The `ModuleInjector` is the reason for this behavior.

2020-07-30 20:51 UTC, kapunahelewong commented on aio/content/guide/feature-modules.md
> +When the CLI generated the `CustomerDashboardComponent` for the new NgModule, the component included a template, `customer-dashboard.component.html`, with the following HTML markup:
```suggestion
When the CLI generated the `CustomerDashboardComponent` for the new NgModule, the component included a template, `customer-dashboard.component.html`, with the following HTML:
```

You can omit the word `markup` because it is the `M` in `HTML` (Like "ATM machine").

2020-07-30 20:51 UTC, kapunahelewong commented on aio/content/guide/feature-modules.md
> +As a result, the `CustomerDashboardComponent` template renders along with the title (which renders by default):
```suggestion
As a result, the `CustomerDashboardComponent` template renders along with the title:
```

Since we added this `title` above, we configured it to be that way. "Default" implies that the system creates and assumes this configuration. The way you've written it, without the parenthetical, is already clear.

2020-07-30 20:51 UTC, kapunahelewong commented on aio/content/guide/feature-modules.md
> +## Next steps
```suggestion
## What's next
```

2020-07-30 20:51 UTC, kapunahelewong commented on aio/content/guide/feature-modules.md
> +* To learn more about the root NgModule, see [Launching an app with a root module](guide/bootstrapping "Launching an app with a root module").
```suggestion
* To learn more about the root NgModule, see [Launching your app with a root module](guide/bootstrapping "Launching an app with a root module").
```

2020-07-31 16:51 UTC, mary-poppins commented
You can preview 63e65ce at https://pr37948-63e65ce.ngbuilds.io/.

2020-07-31 17:01 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +You might find the [Tour of Heroes tutorial](tutorial "Tour of Heroes") helpful, but it is not required.
Fixed manually, appears in the next commit.

2020-07-31 17:03 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +</div>
Fixed manually, appears in the next commit.

2020-07-31 17:04 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +## Create an app project
Using "Create a new app", thanks! Fixed manually, appears in the next commit.

2020-07-31 17:10 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +   Respond by typing **N** (no routing).
Also fixed the list numbering so that these instructions are numbered underneath the list item.

2020-07-31 17:11 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +   Press Enter (Return) to accept the default stylesheet.
Fixed manually, appears in the next commit.

2020-07-31 17:13 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +   Both are needed for the example app to work, but are not required for creating NgModules.
Fixed manually, appears in the next commit.

2020-07-31 17:19 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +6. In the same file, add `HttpClientModule` and `FormsModule` to the imports array in the `NgModule` metadata (which already includes `BrowserModule`):
Used the following:

> In the same file, add `HttpClientModule` and `FormsModule` to the imports array in the `@NgModule()` metadata, which already includes `BrowserModule`:

2020-07-31 17:20 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +1. Change to the workspace root folder (`feature-modules`).
Fixed manually, appears in the next commit.

2020-07-31 17:28 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +Note that new NgModules should import `CommonModule` rather than `BrowserModule`, which is  imported only once in the [root](guide/bootstrapping "Launching your app with a root module") NgModule and
I fixed this as above, but also made it accurate, as "you" don't import, the `ng new` command sets up that import. Here's the new version:

> Note that for new NgModules, you should import `CommonModule` rather than `BrowserModule`.
> The [root NgModule](guide/bootstrapping "Launching your app with a root module"), generated by the CLI `ng new` command, already imports `BrowserModule` in order to configure the entire app for the browser.
>

2020-07-31 17:31 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +You use the (now empty) `declarations` array in the `customer-dashboard.module.ts` file to declare the components, directives, and pipes that will belong exclusively to this particular NgModule.
Fixed manually, appears in the next commit.

2020-07-31 17:33 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +To add a component to the new NgModule, enter the following CLI command, specifying the generated folder for the NgModule (`customer-dashboard`) and the component name (`CustomerDashboard`):
Fixed manually, appears in the next commit.

2020-07-31 17:37 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +This command generates a folder for the new component within the `customer-dashboard` folder, and updates the `customer-dashboard.module.ts` file with the `CustomerDashboardComponent` info:
I combined them as follows:

> This command adds the `CustomerDashboardComponent` to the import list at the top of the `customer-dashboard.module.ts` file, and also adds it to the `declarations` array, which lets Angular know to associate this new component with this NgModule.
> The command also generates a folder for the new component within the `customer-dashboard` folder, and updates the `customer-dashboard.module.ts` file with the `CustomerDashboardComponent` info:
>

2020-07-31 17:39 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +* Specify only [declarables](guide/glossary#declarable "Definition of a declarable") (component, directives, and pipes) in the `declarations` array.
Fixed manually, appears in the next commit.

2020-07-31 17:41 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +* Declare these classes in an NgModule _only if_ they belong to that NgModule.
I did, but it doesn't matter, because either way is correct, so I chose your suggestion because it looks better.

2020-07-31 18:59 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +If you add service providers to the new NgModule, `AppModule` would know about those too, so that they can be used by other NgModules.
Adding context as well as the DI intro page link. The paragraph is now as follows:

> Now that the the root `AppModule` knows about the new NgModule, other NgModules in your app can use its implementation even though the new NgModule doesn't expose its components.
> You can add service providers to the new NgModule, as described in [Providing dependencies in modules](guide/providers "Providing dependencies in modules"). 
> `AppModule` would know about those too, so that they can be used by other NgModules.
> For more about service dependency injection, see [Dependency injection in Angular](guide/dependency-injection "Dependency injection in Angular").
>

2020-07-31 19:02 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +When the CLI generated the `CustomerDashboardComponent` for the new NgModule, the component included a template, `customer-dashboard.component.html`, with the following HTML markup:
Fixed manually, appears in the next commit.

2020-07-31 19:03 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +As a result, the `CustomerDashboardComponent` template renders along with the title (which renders by default):
Fixed manually, appears in the next commit.

2020-07-31 19:04 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +## Next steps
Fixed manually, appears in the next commit.

2020-07-31 19:06 UTC, rockument69 commented on aio/content/guide/feature-modules.md
> +* To learn more about the root NgModule, see [Launching an app with a root module](guide/bootstrapping "Launching an app with a root module").
Fixed manually, appears in the next commit.

2020-07-31 19:18 UTC, mary-poppins commented
You can preview 5e3d53b at https://pr37948-5e3d53b.ngbuilds.io/.

2020-08-03 17:13 UTC, mary-poppins commented
You can preview 65c0b3d at https://pr37948-65c0b3d.ngbuilds.io/.

2020-08-03 20:12 UTC, kapunahelewong approved these changes
LGTM! Thanks, @rockument69!

Reviewed-for: global-docs-approvers

2020-11-02 19:55 UTC, closed without merging