docs: add carlos caballero to GDE resources
angular/angular pull request #37976
Opened 2020-07-08 14:18 UTC by Caballerog

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2020-07-08 15:50 UTC, PuntoTechAcademy commented
@googlebot I signed it!

2020-07-26 08:37 UTC, ajitsinghkaler requested changes
Can you please [rebase](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) on master

2020-07-26 08:37 UTC, ajitsinghkaler commented on aio/content/marketing/contributors.json
> +  "carloscaballero": {
Please use the keys as your GitHub username 

carloscaballero -> Caballerog

2020-08-26 18:27 UTC, kapunahelewong requested changes
Congratulations, @Caballerog! I have just a couple of questions. Well done!

2020-08-26 18:27 UTC, kapunahelewong commented on aio/content/marketing/contributors.json
> +    "bio": "Carlos Caballero is a Computer Science Engineer and a PhD. in Computer Science from the University of Málaga. Master in Software Engineering and Artificial Intelligence. He is Full-time t
```suggestion
    "bio": "Carlos Caballero is a computer science engineer and a PhD in Computer Science from the University of Málaga. He earned his masters in Software Engineering and Artificial Intelligence. He is a full-time teacher in vocational training. He has written several teaching books and more than a dozen research articles in the first international journals.",
```

Regarding this sentence:
> He is a full-time teacher in vocational training.
Could you clarify what you mean with vocational training? In the US there's a difference between vocational education (trade- or craft-based, technicians) and professional (law, the sciences, math, humanities - all areas in which one might pursue a PhD and work in academia).

And by "first international journals", would this be the same as peer-reviewed journals?

2020-08-26 19:54 UTC, Caballerog commented on aio/content/marketing/contributors.json
> +    "bio": "Carlos Caballero is a Computer Science Engineer and a PhD. in Computer Science from the University of Málaga. Master in Software Engineering and Artificial Intelligence. He is Full-time t
Hi @kapunahelewong !

Thank you very much for your suggestions, I will make the change with the one proposed by @ajitsinghkaler .

Regarding your questions, I try to answer them.

I think the training that I teach is equivalent in the US with "Associate Degree", in Europe there is no consensus and normally when I travel to other countries of the European Union we usually indicate it as Vocational Training Education.

Regarding the second question, I mean that they are publications of the first quartile in their category according to the JCR (Journal Citation Reports).

2020-08-26 19:55 UTC, Caballerog commented on aio/content/marketing/contributors.json
> +  "carloscaballero": {
Thank you!

I will do it together with the changes that @kapunahelewong  proposes to me. That way, I'll just do one commit.

2020-08-27 13:39 UTC, kapunahelewong commented on aio/content/marketing/contributors.json
> +    "bio": "Carlos Caballero is a Computer Science Engineer and a PhD. in Computer Science from the University of Málaga. Master in Software Engineering and Artificial Intelligence. He is Full-time t
Oh, I see! Thank you for explaining, @caballerog. Apologies for the messed up formatting on my comment. 

Since you'll be making an extra commitment with your new changes, just remember to squash so that ultimately there's only one commit. I have [some notes](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) on the process that you may find helpful. If you have any questions though, just let me know.

2020-09-08 08:51 UTC, Caballerog commented
I just made the changes following the instructions you gave me (The documentation is great). I hope I did well :-)

2020-09-09 12:47 UTC, kapunahelewong approved these changes
This is great! I'm so glad you liked my notes, thank you! Our next step is to get marketing review and approval. Once we have that, we can move forward. I'll keep an eye on this to see when it's approved, but if you notice before I do or have any questions, just tag me. Congratulations!

LGTM! 

Reviewed-for: global-docs-approvers

2020-09-15 03:46 UTC, ajitsinghkaler approved these changes
LGTM.

2020-09-21 17:59 UTC, StephenFluin approved these changes

2020-10-05 13:16 UTC, kapunahelewong commented
Hey, @Caballerog! Could you rebase and tag me when you're ready? I'll keep a lookout for your notification. That's the last thing we need to do before merging! 🎉

2020-10-09 14:50 UTC, Caballerog commented
It is ready!  :tada:  @kapunahelewong

2020-10-28 14:43 UTC, kapunahelewong commented
Thank you for your patience, @Caballerog!! 

Note for caretaker, the inclusive language check is flagging "masters" degree.

2020-10-28 17:52 UTC, closed without merging