docs: update router api documentation
angular/angular pull request #37980
Opened 2020-07-08 15:57 UTC by jbogarthyde

Edit descriptions, usage examples, and add links to be complete and consistent with API reference doc style

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Router API docs are incomplete and do not follow current standards. 
Does not use terminology consistently or in accordance with guide usage.

Issue Number: N/A

## What is the new behavior?
Adds links to guides and among members, adds, restructures, and edits descriptions of public members.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-07-08 16:06 UTC, mary-poppins commented
You can preview 8e4b631 at https://pr37980-8e4b631.ngbuilds.io/.

2020-07-08 16:42 UTC, mary-poppins commented
You can preview 049a6fd at https://pr37980-049a6fd.ngbuilds.io/.

2020-07-08 17:44 UTC, mary-poppins commented
You can preview 8e06739 at https://pr37980-8e06739.ngbuilds.io/.

2020-07-08 18:29 UTC, mary-poppins commented
You can preview f32977e at https://pr37980-f32977e.ngbuilds.io/.

2020-07-08 19:15 UTC, mary-poppins commented
You can preview 924df2e at https://pr37980-924df2e.ngbuilds.io/.

2020-07-08 20:34 UTC, mary-poppins commented
You can preview ec00597 at https://pr37980-ec00597.ngbuilds.io/.

2020-07-08 20:58 UTC, mary-poppins commented
You can preview abbfa49 at https://pr37980-abbfa49.ngbuilds.io/.

2020-07-08 21:38 UTC, mary-poppins commented
You can preview 4bbd262 at https://pr37980-4bbd262.ngbuilds.io/.

2020-07-08 23:05 UTC, mary-poppins commented
You can preview 45425df at https://pr37980-45425df.ngbuilds.io/.

2020-07-13 22:47 UTC, atscott requested changes

2020-07-13 22:47 UTC, atscott commented on packages/router/src/config.ts
> + * @see `Route#loadChildrenCallback`.
I think this update isn't correct. It was linking to the `loadChildren` property in the `Route` config https://angular.io/api/router/Route#loadChildren. There's no `loadChildrenCallback` there. 

Same comment for the update below on `DeprecatedLoadChildren`

2020-07-13 22:47 UTC, atscott commented on packages/router/src/config.ts
> +   * A `LoadChildrenCallback` object specifying lazy-loaded child routes.
Hmmm, I'm not sure about this update either. The documentation is linking to a different type than the actual type of the key. Maybe this should be left alone as well.

2020-07-13 22:47 UTC, atscott commented on packages/router/src/events.ts
> +   * @see `NavigationError`   *
```suggestion
   * @see `NavigationError`
   * @see `NavigationStart`
```

Based on the other updates, it looks like you're prioritizing links to these 4 events?

2020-07-13 22:47 UTC, atscott commented on packages/router/src/events.ts
> + * The events occur in the following sequence.
```suggestion
 * The events occur in the following sequence:
```

2020-07-13 22:47 UTC, atscott commented on packages/router/src/router.ts
> + * Options that modify the Router navigation strategy.
```suggestion
 * Options that modify the `Router` navigation strategy.
```

2020-07-13 22:47 UTC, atscott commented on packages/router/src/router.ts
> + * * *extras* : The previously successful `Navigation` object. Only one previous navigation
I think you meant to put something like 
```
/**
   * Options that controlled the strategy used for this navigation.
   * See `NavigationExtras`.
   */
```
:)

2020-07-13 22:47 UTC, atscott commented on packages/router/src/router.ts
> +   * @returns A Promise that resolves to 'true' when navigation succeeds, to 'false' when navigation
```suggestion
   * @returns A Promise that resolves to `true` when navigation succeeds, to `false` when navigation
```

2020-07-13 22:47 UTC, atscott commented on packages/router/src/router_module.ts
> + * You can import this NgModule multiple times, once for each lazy-loaded bundle.
```suggestion
 * You can import this `NgModule` multiple times, once for each lazy-loaded bundle.
```

2020-07-13 22:47 UTC, atscott commented on packages/router/src/router_module.ts
> + * However, only one Router service can be active.
```suggestion
 * However, only one `Router` service can be active.
```

2020-07-13 22:47 UTC, atscott commented on packages/router/src/router_module.ts
> + * routes, but does not include the Router service.
```suggestion
 * * The `forRoot()` method creates an `NgModule` that contains all the directives, the given routes,
 * and the Router service itself.
 * * The `forChild()` method creates an `NgModule` that contains all the directives and the given
 * routes, but does not include the `Router` service.
```

2020-07-13 22:47 UTC, atscott commented on packages/router/src/router_module.ts
> + * overview of how the Router service should be used.
```suggestion
 * overview of how the `Router` service should be used.
```

2020-07-13 22:47 UTC, atscott commented on packages/router/src/router_module.ts
> +   * When registering the NgModule at the root, import as follows:
```suggestion
   * When registering the `NgModule` at the root, import as follows:
```

2020-07-13 22:47 UTC, atscott commented on packages/router/src/router_module.ts
> +   * @return The new NgModule.
```suggestion
   * @return The new `NgModule`.
```

2020-07-13 22:47 UTC, atscott commented on packages/router/src/router_module.ts
> +   * ```   *
This line is showing up in the documentation (maybe because of the trailing `*`*)

2020-07-13 22:47 UTC, atscott commented on packages/router/src/router_state.ts
> + * of the current state to establish its own route tree.
```suggestion
 * of the current state to establish its own route tree:
```
I think we discussed this before and we realized that the colon was now recommended in the tech writing style guide?

2020-07-14 15:30 UTC, jbogarthyde commented on packages/router/src/router_module.ts
> + * You can import this NgModule multiple times, once for each lazy-loaded bundle.
Actually "NgModule" is the mandated term for an `NgModule` -- this is descriptive, it doesn't need to be a link to the class.

2020-07-14 15:33 UTC, jbogarthyde commented on packages/router/src/router_module.ts
> +   * When registering the NgModule at the root, import as follows:
Again, a descriptive term.

2020-07-14 17:51 UTC, mary-poppins commented
You can preview 8a23ef0 at https://pr37980-8a23ef0.ngbuilds.io/.

2020-07-14 18:48 UTC, mary-poppins commented
You can preview 1af4f1a at https://pr37980-1af4f1a.ngbuilds.io/.

2020-07-14 19:06 UTC, mary-poppins commented
You can preview e32d303 at https://pr37980-e32d303.ngbuilds.io/.

2020-07-14 20:57 UTC, jelbourn commented
I don't know why this PR is requesting public-api approvers because AFAICT it doesn't touch anything there. @atscott once you approve this PR feel free to ping me for global approval

2020-07-14 21:01 UTC, petebacondarwin commented
@jelbourn it is because of this line here https://github.com/angular/angular/pull/37980/files?file-filters%5B%5D=.ts#diff-d4a2188410be78a020e88630cdafa20dL151

2020-07-14 21:36 UTC, atscott approved these changes

2020-07-14 21:36 UTC, atscott commented on packages/router/src/router_module.ts
> + * The following values have been [deprecated since v4](guide/releases#deprecation-practices),
```suggestion
 * The following values have been [deprecated](guide/releases#deprecation-practices) since v4,
```

I think the current scope of the link implies that it will go to the deprecation notice in v4 for these values. Maybe just link the "deprecation"

2020-07-14 21:36 UTC, atscott commented on packages/router/src/router_module.ts
>   * The 'legacy_enabled' and 'legacy_disabled' should not be used for new applications.
Is this sentence needed, given the previous section?

2020-07-15 14:40 UTC, jbogarthyde commented on packages/router/src/router_module.ts
>   * The 'legacy_enabled' and 'legacy_disabled' should not be used for new applications.
Not in the current text.

2020-07-15 14:54 UTC, mary-poppins commented
You can preview 7ee48c6 at https://pr37980-7ee48c6.ngbuilds.io/.

2020-07-15 16:58 UTC, mary-poppins commented
You can preview 3efead9 at https://pr37980-3efead9.ngbuilds.io/.

2020-07-15 23:48 UTC, jelbourn approved these changes
LGTM - using global-approvers because the public API change is removing a deprecation marker that wasn't supposed to be on that symbol in the first place

Reviewed-for: global-approvers

2020-07-16 15:49 UTC, mary-poppins commented
You can preview ce88f29 at https://pr37980-ce88f29.ngbuilds.io/.

2020-07-16 20:52 UTC, closed without merging