fix(docs-infra): header external icons is not shown in IE11
angular/angular pull request #38046
Opened 2020-07-14 14:16 UTC by saifabusaleh

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

Issue Number: https://github.com/angular/angular/issues/37847

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## Other information

This issue fixes the issue of hidden icons in IE11

Changed the right container of the tool bar to contains the whole items in the right and gave `flew-grow:1` to search input
This also fixes that in mobile the icons is trunicated
![image](https://user-images.githubusercontent.com/15147809/87434068-b228d780-c5f2-11ea-9f71-3e52691be157.png)

There is still an issue that the github icon is not shown in IE, its because the svg of gitHub itself need to be replaced.
I would be glad if someone can provide updated Github svg

2020-07-15 18:52 UTC, mary-poppins commented
You can preview 3189c2e at https://pr38046-3189c2e.ngbuilds.io/.
You can preview 8ea2e50 at https://pr38046-8ea2e50.ngbuilds.io/.

2020-07-16 08:47 UTC, saifabusaleh commented
Hi @gkalpak, please let me know if there something missing to push this PR forward

Thanks

2020-07-16 19:13 UTC, gkalpak requested changes
Thx for starting work on this, @saifabusaleh :+1:

I am afraid this is a little more complicated than we initially expected. AFAICT, there are two issues:

1. No SVG icon other than the Twitter-logo seems to be displayed on IE 11. If you check the source, you will see that the other SVGs (such as the GitHub logo and the right arrows in the sidenav) appear empty (i.e. `<svg></svg>`). No idea why this happens.

2. The Twitter and GitHub logo `<mat-icon>` elements next to the search bar are very small (they do not respect the `width: 24px; height: 24px;` CSS styles). Again no idea why 😕

We need to figure these two issues out before we can proceed with an appropriate fix. I started looking into it, but no luck so far 😞 
If I find something I will post an update here.

##
BTW, can you please add `Fixes #37847` at the bottom of the commit message (to more closely follow our [commit message guidelines](https://github.com/angular/angular/blob/1d9e56eba06958e37ef8062ae7b65afa85f90632/CONTRIBUTING.md#commit)).

2020-07-16 19:44 UTC, gkalpak commented
I think adding `flex-shrink: 0;` to the styles for [.toolbar-external-icons-container][1] solves the second issue. Can you confirm that works for you too?
AFAICT, we can replace the changes that you currently have in this PR with that change. Did I miss something?

Now we need to figure out what's going on with the first issue 🤔 

[1]: https://github.com/angular/angular/blob/79850983e6fcedb82377f2784e6d59c62727b71e/aio/src/styles/1-layouts/_top-menu.scss#L244

2020-07-16 21:11 UTC, gkalpak commented
Regarding the second issue, it turns out that IE 11 messes up the SVGs if we use the same `<div>` elements to create them. If we move the `const div = document.createElement('DIV');` inside the `forEach()` callback, everything seems to work fine 🤷‍♂️

https://github.com/angular/angular/blob/019a696a6a5f3ef4f53253558559b713e3e596dd/aio/src/app/shared/custom-icon-registry.ts#L59-L70

##
@saifabusaleh, can you apply these two changes, verify that they work for you too (and I didn't miss something) and update the PR. Also, please add some comments above the updated lines to explain that the changes are needed for IE 11 to show the SVG correctly.

2020-07-16 21:22 UTC, saifabusaleh commented
@gkalpak great job :) I tried to apply what you posted for both of the issues and it seems to fix everything 💯 
I didn't know that icons working with `CustomIconRegistry`

should I revert commit what I did so far and do another commit with the fixes?

2020-07-16 21:24 UTC, mary-poppins commented
You can preview 31ff0a1 at https://pr38046-31ff0a1.ngbuilds.io/.

2020-07-16 21:26 UTC, gkalpak commented
Awesome! So, yes, if you find that my proposed changes fix the issues, I suggest you revert your original changes and apply mine (since they seem to be simpler/less disruptive). WDYT?

2020-07-16 21:32 UTC, saifabusaleh commented
@gkalpak  Looks fine for me 👍 Doing revert and pushing new changes now

2020-07-16 21:56 UTC, mary-poppins commented
You can preview 612cdb5 at https://pr38046-612cdb5.ngbuilds.io/.

2020-07-16 22:08 UTC, mary-poppins commented
You can preview dd1d2bd at https://pr38046-dd1d2bd.ngbuilds.io/.

2020-07-16 22:28 UTC, saifabusaleh commented
Tested on IE and looks fine, also verified that it didn't break behavior in chrome/safari 

@gkalpak I think its better also if you double check everything, and if everything is fine its possible to merge
Thanks for helping me out with this issue and pointing me to the root cause

2020-07-17 09:54 UTC, gkalpak requested changes
Thx, @saifabusaleh! It seems to work fine for me too.

I have left a couple of minor suggestions. OTher than that lgtm :+1:

Can you also squash all commits into one and update the commit message to mention both fixes. For example:

> fix(docs-infra): correctly display SVG icons in IE11
>
> Fix two issues that affected displaying of SVG icons in IE11:
> 1. All SVG icons except for one appeared empty. This was related how the
>    `CustomIconRegistry` re-used the same `<div>` element to create all
>    SVG elements.
> 2. The GitHub and Twitter buttons next to the search bar were not sized
>    properly. 
>
> Fixes #37847

2020-07-17 09:54 UTC, gkalpak commented on aio/src/styles/1-layouts/_top-menu.scss
> +    flex-shrink: 0;
Could you add a comment here to avoid someone accidentally removing it in the future (thinking it is not needed):

```suggestion
    flex-shrink: 0;  // This is required for the icons to be displayed correctly in IE11.
```

2020-07-17 09:54 UTC, gkalpak commented on aio/src/app/shared/custom-icon-registry.ts
> +      // this change is fix for IE11 to show the SVG correctly
It is not clear what the change is by looking at the comment. How about making more clear (without having to look at the code histiry) with something like:

```suggestion
      // Creating a new `<div>` per icon is necessary for the SVGs to work correctly in IE11.
```

2020-07-17 11:23 UTC, saifabusaleh commented
@gkalpak Done :)

Thanks for all the feedback

2020-07-17 11:32 UTC, mary-poppins commented
You can preview 2bbc6ce at https://pr38046-2bbc6ce.ngbuilds.io/.

2020-07-17 11:47 UTC, gkalpak approved these changes
LGTM ✨

One last thing: Please update the commit message header as suggested in https://github.com/angular/angular/pull/38046#pullrequestreview-450500631 :pray:

2020-07-17 11:47 UTC, gkalpak commented on aio/src/app/shared/custom-icon-registry.ts
>      svgIcons.forEach(icon => {
💡 Idea: We can lazy-create SVGs when requested, instead of creating them up-front.
Something you can do in a future PR, if interested :wink:

2020-07-17 11:59 UTC, saifabusaleh commented on aio/src/app/shared/custom-icon-registry.ts
>      svgIcons.forEach(icon => {
Not sure how it can be done, also I don't think it will change much since there there is only 6 SVG's for now

+ Updated the commit message header

2020-07-17 12:03 UTC, mary-poppins commented
You can preview acff36f at https://pr38046-acff36f.ngbuilds.io/.

2020-07-17 12:21 UTC, gkalpak commented on aio/src/app/shared/custom-icon-registry.ts
>      svgIcons.forEach(icon => {
Yes it wouldn't have a dramatic impact indeed. At the same time there is no downside in doing it and it would save some unnecessary work.

Thx for updating the header :tada:

2020-07-17 18:44 UTC, closed without merging