buid(ivy): create sample forms app
angular/angular pull request #38044
Opened 2020-07-14 12:53 UTC by sonukapoor

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [X] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-07-15 08:55 UTC, devversion commented
@googlebot I consent.

2020-07-17 01:30 UTC, AndrewKushnir requested changes

2020-07-17 01:30 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/index.ts
> +import {FormArray, FormBuilder, FormControl, FormGroup, FormsModule, ReactiveFormsModule, Validators,} from '@angular/forms';
```suggestion
import {FormArray, FormBuilder, FormControl, FormGroup, FormsModule, ReactiveFormsModule, Validators} from '@angular/forms';
```

2020-07-17 01:30 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/treeshaking_spec.ts
> +describe('treeshaking with uglify', () => {
I think we should have some simple e2e tests here with basic checks that Angular was loaded, 2 forms present on the page and may be 1-2 actions (like clicking a button/input field). See `packages/core/test/bundling/todo/todo_e2e_spec.ts` as an example.

2020-07-17 23:05 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/forms_e2e_spec.ts
> +const UTF8 = {
It looks like this is unused in this file (probably copy-n-paste'ed from a different one).

2020-07-17 23:05 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/forms_e2e_spec.ts
> +    describe(bundle, () => {
```suggestion
    describe(`using ${bundle} bundle`, () => {
```

2020-07-17 23:05 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/forms_e2e_spec.ts
> +      require(path.join(PACKAGE, bundle));
Should it be in `beforeAll` call like this:
```
beforeAll(() => {
  require(path.join(PACKAGE, bundle));
});
```

2020-07-17 23:05 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/forms_e2e_spec.ts
> +      it('should render reactove form', withBody('<app-root></app-root>', async () => {
```suggestion
      it('should render reactive form', withBody('<app-root></app-root>', async () => {
```

2020-07-18 01:37 UTC, sonukapoor commented
@AndrewKushnir ci failed for some reason. I have added the `PR action: rerun CI at HEAD`

2020-07-20 21:32 UTC, AndrewKushnir requested changes
Hi @sonukapoor, thanks for additional updates. I've left a couple comments regarding specific places that we can improve. Also some additional comments:

- I think we should match Reactive and Template-driven Form examples closer (basically make them equal, just implement using different techniques)
- Let's merge all commits into one
- In commit message (and in PR description) it'd be great to mention that this test app was created to introduce the symbol test and this app is also a foundation for additional tests/checks in the future including payload size tests (i.e. let's describe why we add this test app to a repo).

Thank you.

2020-07-20 21:32 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/index.ts
> +  addItem(form: NgForm) {}
It's a bit unexpected that this function is empty. Could we add some basic logic to mimic what we have in Reactive Forms component below?

2020-07-20 21:32 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/index.ts
> +      <div [formGroupName]='i'>
It looks like `*ngFor` should be placed on this `<div>`, but not the container one?

2020-07-20 21:32 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/index.ts
> +    <button (click)='addItem()'>Add</button>
```suggestion
    <button (click)='addCity()'>Add City</button>
```

2020-07-21 22:22 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/forms_e2e_spec.ts
> +           // check for inputs
nit: the comments start with lowercase letters in some cases and uppercase in others, let's use them consistently.

2020-07-21 22:22 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/index.ts
> +  <div ngModelGroup='profileForm' #nameCtrl='ngModelGroup'>
I don't see how `#nameCtrl` and `#f` local refs are used in the template. Do we need them?

2020-07-21 22:22 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/index.ts
> +      <input name='first' ngModel required #first='ngModel' />
This local ref seems to be unused as well.

2020-07-21 22:22 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/index.ts
> +      <input name='last' ngModel />
It looks like we use double quotes in templates of other test apps, may be use them for these components too?

2020-07-21 22:22 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/index.ts
> +    (window as any).templateFormsComponent = this;
I'd propose to put a quick comment here saying that we do that to have a reference to a component instance in tests.

2020-07-21 22:22 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/index.ts
> +    >
```suggestion
    <div formArrayName="addresses">
```

2020-07-22 02:09 UTC, AndrewKushnir reviewed
LGTM, just one final comment (indentation in a template). Thanks Sonu!

You'll also need to rebase, since there are new symbols that should be included into the golden file.

2020-07-22 02:09 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/index.ts
> +  <form novalidate>
Indentation is a bit incorrect in this template (around open and close `<form>` tags)

2020-07-22 02:24 UTC, sonukapoor commented on packages/core/test/bundling/forms/index.ts
> +  <form novalidate>
Please check now. I have checked the other files and the template usually starts in a new line. I did the same with this file.

2020-07-22 19:25 UTC, AndrewKushnir approved these changes
LGTM, just one minor comment on template formatting.

2020-07-22 19:25 UTC, AndrewKushnir commented on packages/core/test/bundling/forms/index.ts
> +  <form novalidate>
Thanks for the comment. Sorry for the confusion, I wanted to point out that the `<form>` and `<div>` are on the same level when `<div>` is actually a child of a `<form>`, thus it needs to be moved a couple spaces to the right (as well as the rest of the template). The `ReactiveFormsComponent` component has it right.

2020-07-22 19:28 UTC, AndrewKushnir commented
FYI, I also changed the PR target to master-only, since the golden file would be slightly different between master and patch (thus this PR will cause CI errors on patch branch). I think having it only in master is OK and it will become a part of the patch branch after `10.1.0` release. Thank you.

2020-07-22 19:50 UTC, sonukapoor commented on packages/core/test/bundling/forms/index.ts
> +  <form novalidate>
Ah. My bad - It should be fixed now

2020-07-22 19:51 UTC, sonukapoor commented
@AndrewKushnir My bad about the indentation. It should be fixed now.

2020-07-23 07:58 UTC, devversion approved these changes
LGTM. Just a few minor nits for the BUILD configuration

2020-07-23 07:58 UTC, devversion commented on packages/core/test/bundling/forms/treeshaking_spec.ts
> +  const contentPath = require.resolve(path.join(PACKAGE, 'bundle.min_debug.js'));
Can you add a comment here that we use the debug bundle as otherwise symbols/identifiers would be mangled (and the test would always pass).

2020-07-23 07:58 UTC, devversion commented on packages/core/test/bundling/forms/BUILD.bazel
> +        "@npm//:node_modules/tslib/tslib.js",
Is this genrule actually needed here? I don't see tslib being imported anywhere and I'd assume it's included in the bundle already.

2020-07-23 07:58 UTC, devversion commented on packages/core/test/bundling/forms/BUILD.bazel
> +        "//packages/core/test/bundling/util:reflect_metadata",
Is reflect metadata here and above needed? I think since we use `ng_module` for compilation, there are no instances where the `Reflect` API is needed and this just complicates/slows-down our build graph.

2020-07-23 07:58 UTC, devversion commented on packages/core/test/bundling/forms/BUILD.bazel
> +        ":tslib",
Do we actually need the prodserver and the devserver? I don't see any protractor e2e tests here, so we could probably just remove those targets. We could keep the prodserver for testing the app in a browser.

2020-07-23 11:15 UTC, devversion approved these changes
LGTM.

2020-07-23 18:05 UTC, closed without merging