Edit and organize router guide
angular/angular pull request #38085
Opened 2020-07-15 20:25 UTC by jbogarthyde

Adds conceptual material from tutorial into guide, edits content for structure, style, and clarity, removing redundancy.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Router guide does not conform to current standards of style and terminology, and does not present concepts logically.

Issue Number: N/A

## What is the new behavior?
Edited for style and structure, concept sections added for topics that were introduced and discussed only in the tutorial.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-07-15 20:28 UTC, jbogarthyde commented
@atscott This is the same content for the one file (the main Routing guide) that you previously reviewed in https://github.com/angular/angular/pull/37405
This PR is limited in scope to that file. Corresponding changes to the tutorials will be made in separate PRs.

2020-07-15 21:09 UTC, atscott approved these changes
Did a quick pass review since I already reviewed this in the other PR; nothing jumped out as needing revision. LGTM from a technical standpoint

2020-07-15 21:11 UTC, mary-poppins commented
You can preview 0350b87 at https://pr38085-0350b87.ngbuilds.io/.

2020-07-20 17:42 UTC, mary-poppins commented
You can preview e9f6734 at https://pr38085-e9f6734.ngbuilds.io/.

2020-07-21 15:37 UTC, mary-poppins commented
You can preview 8e1b588 at https://pr38085-8e1b588.ngbuilds.io/.

2020-07-22 15:13 UTC, mary-poppins commented
You can preview 70c6c77 at https://pr38085-70c6c77.ngbuilds.io/.

2020-07-27 14:45 UTC, mary-poppins commented
You can preview 871f436 at https://pr38085-871f436.ngbuilds.io/.

2020-07-27 16:08 UTC, aikithoughts requested changes
I don't think this PR is moving the content in the right direction. It's combining conceptual information with tasks, which makes it harder for users to figure out how to get things done. Let's focus on the tasks, and we can research what conceptual information users need at a later point.

2020-07-27 18:42 UTC, mary-poppins commented
You can preview 7589d61 at https://pr38085-7589d61.ngbuilds.io/.

2020-08-12 16:10 UTC, bampakoa commented on aio/content/guide/router.md
> +To set up a redirect, configure a route with the `path` you want to redirect from, the `component` you want to redirect to, and a `pathMatch` value that tells the router how to match the URL.
The redirect path contains a `redirectTo` property which is the actual path of the component that we want to navigate to. So, I think that the phrase 

`the component you want to redirect to`

could be rephrased as

`the path of the component that you want to redirect to`

2020-08-12 16:23 UTC, bampakoa commented on aio/content/guide/router.md
> +      this.selectedId = Number(params.get('id'));
Should we change this to `+params.get('id')`? Looks more readable to me 😃

2020-08-12 16:25 UTC, bampakoa commented on aio/content/guide/router.md
> +Create a service for your guard:
Since Angular CLI has a schematic to create a guard, we could instead say `Create a guard using the Angular CLI:` and not mention service at all. What do you think?

2020-11-02 19:57 UTC, closed without merging