fix(compiler): mark `NgModuleFactory` construction as not side effectful
angular/angular pull request #38147
Opened 2020-07-20 19:49 UTC by dgp1130

This allows Closure compiler to tree shake unused constructor calls to `NgModuleFactory`, which is otherwise considered
side-effectful. Without removing this statement, it continues to reference the associated `NgModule` and prevents the
module and all its unused dependencies from being tree shaken.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-07-21 22:45 UTC, dgp1130 commented
http://test/OCL:322443590:BASE:322443701:1595367128330:be18d491

2020-07-24 17:18 UTC, dgp1130 commented
@mhevery, @alxhub, can you please take a look at this PR?

2020-07-24 21:10 UTC, mhevery approved these changes

2020-07-27 20:27 UTC, dgp1130 commented
Status checks wanted me to rerun g3 presubmit, so here's the new results:
http://test/OCL:322443590:BASE:323406497:1595875409766:177c87aa

Just a number of flakes/preexisting failures. I don't see anything that seems related to this PR.

2020-07-27 20:38 UTC, alxhub requested changes
This LGTM, save for the formatting of `ngtsc_spec`.

2020-07-27 20:38 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/fake_core/index.ts
> +  return fn();
This is fine, but there's no actual reason to have an implementation here - `fake_core` is just used for its type.

2020-07-27 20:38 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +runInEachFileSystem(
There are some weird formatting issues in this file - we should be able to avoid this.

2020-07-27 21:03 UTC, dgp1130 commented on packages/compiler-cli/test/ngtsc/fake_core/index.ts
> +  return fn();
Updated to an `export declare function` with no body.

2020-07-27 21:03 UTC, dgp1130 commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +runInEachFileSystem(
Sorry, the formatter got a little over-zealous. Reverted the changes and updated my code so the formatter doesn't flip out from it.

2020-07-29 18:04 UTC, alxhub approved these changes

2020-07-29 20:32 UTC, closed without merging