refactor(dev-infra): update commit body checks
angular/angular pull request #38168
Opened 2020-07-21 23:11 UTC by AndrewKushnir

This commit updates the commit body checking logic:
* avoid checking the length of lines in commit body
* ignores lines that start with `#` char, since these lines are skipped by git
* adds `release` into the `minBodyLengthTypeExcludes` list in a config rather than having a hard-coded exclusion for this commit type in the code

Resolves #37865.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-07-22 01:31 UTC, jelbourn approved these changes
lgtm

2020-07-22 08:26 UTC, devversion approved these changes
LGTM. Nice cleanup!

2020-07-22 08:40 UTC, gkalpak reviewed
FWIW, I am not in favor of removing the max line length limit, but otherwise lgtm :grin:

2020-07-22 08:40 UTC, gkalpak commented on dev-infra/commit-message/validate.ts
> +            .join('')
Why not join on `'\n'` (since that is what you split on)?
Also, I would suggest `trim()`ing (as we did before).

2020-07-22 21:31 UTC, AndrewKushnir commented on dev-infra/commit-message/validate.ts
> +            .join('')
Thanks for the review @gkalpak.

> Why not join on '\n' (since that is what you split on)?

Joining on `\n` will add 2 chars to the body for each line, so 10+ empty lines would be treated as a valid commit message body.

> Also, I would suggest trim()ing (as we did before).

We didn't trim lines before, we just trimmed the whole body contents and this logic is present now as well.

2020-07-22 22:08 UTC, josephperrott requested changes
A couple of things:

Can you split the commits into one that contains the changes to the `.ng-dev/commit-messages.ts` file and one that contains the rest.

The commit scope of the config file change should be `ci` while the others scope should be `dev-infra`


---

Additionally, I would like to push back on the line length removal?  I don't understand the historical context for why it was in place and I want to be sure that we aren't having unintended/misunderstood consequences.

Do we know why it was in place in the first place?

2020-07-23 07:38 UTC, gkalpak commented on dev-infra/commit-message/validate.ts
> +            .join('')
> Joining on `\n` will add 2 chars to the body for each line, so 10+ empty lines would be treated as a valid commit message body.

While this is partially true (if you trim the body as suggested above, then one would need to have consecutive empty lines between actual text), if someone did this then it sounds intentional enough (and if they wanted to trick the validation script, they could have used twenty dots or something instead).

Also, not removing the nwlines is the behavior we had before, so if this is an intentional change/improvement, it should go on its own commit (with an explanation of the reasoning).

<sub>(For the record, `\n` adds one characters 🤓)</sub>

> We didn't trim lines before, we just trimmed the whole body contents and this logic is present now as well.

Yes, I am not suggesting trimming individual lines. I am suggesting trimming the body _after_ removing the comments. The intention was to remove extra space around the actual commit message body, so we should trim it after having remove the comments to make sure that any extra space between the actual body and the comments is also removed.

2020-07-24 05:33 UTC, AndrewKushnir commented on dev-infra/commit-message/validate.ts
> +            .join('')
Thanks for additional clarification @gkalpak 👍
I've applied the necessary changes (and added a test to verify the behavior).

2020-07-28 09:24 UTC, gkalpak commented
If you are curious, this is how long commit messages are displayed on GitHub's PR commit tab 😛:

![long-commit-message](https://user-images.githubusercontent.com/8604205/88645585-f1fcbe00-d0cc-11ea-8e6d-b8154670dc84.png)

2020-08-13 04:42 UTC, closed without merging