Refactor observables doc for style, clarity, and structure
angular/angular pull request #38165
Opened 2020-07-21 20:18 UTC by jbogarthyde

Edit to conform to current doc standards, combine overview and RxJS pages into one, introduce relationship to RxJS

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Document uses older styles, language not always clear

Issue Number: This replaces earlier PR https://github.com/angular/angular/pull/38027

## What is the new behavior?
-- Correct construction and language for style and clarity
-- Add ref to RxJS Subject doc for multicasting, with example  (from contributor suggestion).
-- Combine short RxJS page w/Overview page, clarify relation to RxJS in introduction

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-07-21 22:47 UTC, mary-poppins commented
You can preview 66aed51 at https://pr38165-66aed51.ngbuilds.io/.

2020-07-21 23:15 UTC, mary-poppins commented
You can preview b03c285 at https://pr38165-b03c285.ngbuilds.io/.

2020-07-22 15:11 UTC, mary-poppins commented
You can preview 61602cc at https://pr38165-61602cc.ngbuilds.io/.

2020-07-22 16:14 UTC, aikidave commented on aio/content/guide/observables.md
> +Operators are functions that build on the observables foundation to enable sophisticated manipulation of collections. For example, RxJS defines operators such as `map()`, `filter()`, `concat()`, and
```suggestion
Operators are functions that allow you to manipulate the values observables return. For example, RxJS defines operators such as `map()`, `filter()`, `concat()`, and `flatMap()`.
```

2020-07-22 16:14 UTC, aikidave commented on aio/content/guide/observables.md
> +Operators take configuration options, and they return a function that takes a source observable. When executing this returned function, the operator observes the source observable’s emitted values, t
```suggestion
Operators take configuration options, and they return a function that takes a source observable. When executing this returned function, the operator observes the source observable’s emitted values, transforms them, and returns a new observable of those transformed values. For example:
```

2020-07-22 16:14 UTC, aikidave commented on aio/content/guide/observables.md
> +  Note that, for Angular apps, combining operators with pipes is preferred to _chaining_, which is used in many RxJS examples.
```suggestion
 For Angular applications, it is recommended that you combine operators with pipes.
```

2020-07-22 16:14 UTC, aikidave commented on aio/content/guide/observables.md
> +A set of operators applied to an observable is a recipe&mdash;that is, a set of instructions for producing the values you’re interested in. By itself, the recipe doesn’t do anything. You need to call
Is recipe in our glossary?

2020-07-22 16:14 UTC, aikidave commented on aio/content/guide/observables.md
> +The `pipe()` function is also a method on the RxJS `Observable`, so you can use this shorter form to define the same operation:
```suggestion
The `pipe()` function is also a method on the RxJS `Observable`, which means you can use this shorter form to define the same operation:
```

2020-07-22 16:14 UTC, aikidave commented on aio/content/guide/observables.md
> +
```suggestion
RxJS provides many operators. The most common operators used in Angular applications are as follows: 

| Area | Operators |
| :------------| :----------|
| Creation |  `from`,`fromEvent`, `of` |
| Combination | `combineLatest`, `concat`, `merge`, `startWith` , `withLatestFrom`, `zip` |
| Filtering | `debounceTime`, `distinctUntilChanged`, `filter`, `take`, `takeUntil` |
| Transformation | `bufferTime`, `concatMap`, `map`, `mergeMap`, `scan`, `switchMap` |
| Utility | `tap` |
| Multicasting | `share` |

For a full list of operators and usage samples, visit the [RxJS API documentation](https://rxjs.dev/api).
```

2020-07-22 16:14 UTC, aikidave commented on aio/content/guide/observables.md
> +Because Angular applications are mostly written in TypeScript, you will typically know when a variable is an observable. Although the Angular framework does not enforce a naming convention for observ
```suggestion
Angular applications are mostly written in TypeScript, which makes it easier to know when a variable is an observable. However, a common naming convention for observables is to add a `$` to the variable name. For example, `response$`. Remember that the Angular framework does not enforce this convention.
```

2020-07-22 16:14 UTC, aikidave commented on aio/content/guide/observables.md
> +This can be useful when scanning through code and looking for observable values. Also, if you want a property to store the most recent value from an observable, it can be convenient to simply use the
```suggestion
Using this naming convention can help you when you are scanning through code and looking for observable values. 
```
I recommend deleting the last sentence. First we tell people about a convention, then we tell them it's not enforced, then we tell them they may or may not use it? I think it's fine to explain that it's a useful, if unenforced, convention, but that's it.

2020-07-22 17:36 UTC, jbogarthyde commented on aio/content/guide/observables.md
> +  Note that, for Angular apps, combining operators with pipes is preferred to _chaining_, which is used in many RxJS examples.
I think we should keep the note about pipes vs chaining, since we refer to RxJS doc for operators, and their examples use chaining.

2020-07-22 17:38 UTC, jbogarthyde commented on aio/content/guide/observables.md
> +A set of operators applied to an observable is a recipe&mdash;that is, a set of instructions for producing the values you’re interested in. By itself, the recipe doesn’t do anything. You need to call
No, it's a general descriptive term that Jason came up with. I'll try to rephrase.

2020-07-22 17:50 UTC, jbogarthyde commented on aio/content/guide/observables.md
> +This can be useful when scanning through code and looking for observable values. Also, if you want a property to store the most recent value from an observable, it can be convenient to simply use the
Rephrased to describe usage in example.

2020-07-22 17:51 UTC, jbogarthyde commented
Thanks @aikidave

2020-07-23 17:52 UTC, niklas-wortmann commented on aio/content/guide/observables.md
> +Observables get their name from the observer _pattern_. In this pattern, an object (sometimes called the *subject*) maintains a list of its dependents, called *observers*, and notifies them automatic
I honestly think this might confuse many readers or at least moves them in the wrong direction as Subjects and Observables are fundamentally different in RxJS.

2020-07-23 17:52 UTC, niklas-wortmann commented on aio/content/guide/observables.md
> +The interface for listening to values and stopping listening is the same, regardless of whether the value stream reports keystrokes, an HTTP response, or the state of an interval timer.
"The interface for listening to values and stopping listening is the same" I don't understand this?

2020-07-23 17:52 UTC, niklas-wortmann commented on aio/content/guide/observables.md
>  In either case, a `next` handler is required. The `error` and `complete` handlers are optional.
Not part of this pr, but this sentence is actually wrong. One can also just call `subscribe()` without any callback

2020-07-23 17:52 UTC, niklas-wortmann commented on aio/content/guide/observables.md
> +When an observer subscribes, the observable wires up an event handler and delivers values to that observer.
Event handler might be a little bit irritating. I think what you are referring to is a Producer instance?

2020-07-23 17:52 UTC, niklas-wortmann commented on aio/content/guide/observables.md
> +RxJS provides the [`Subject` class](https://rxjs.dev/guide/subject "RxJS API reference") that simplifies the process of multicasting, allowing you to take any observable and make it multicasting.
Maybe it's just the fact that I am not a native speaker but "allowing you to take any observable and make it multicasting" kinda sounds like an Observable is a constructor argument for a Subject.

2020-07-23 17:52 UTC, niklas-wortmann commented on aio/content/guide/observables.md
> +An observable can either produce values (calling the `next` callback), or it can complete, calling either the `complete` or `error` callback.
technically an Observable can produce values and complete afterwards or error and it can also do none of those :D

2020-07-23 17:52 UTC, niklas-wortmann commented on aio/content/guide/observables.md
> +Because observables produce values asynchronously, the try/catch construction does not effectively catch errors. Instead, you generally handle errors by specifying an `error` callback on the observer
Values are not produced asynchronously, at least not if it isn't necessary. But errors are always emitted asynchronously

2020-07-23 17:52 UTC, niklas-wortmann commented on aio/content/guide/observables.md
> +For example, RxJS defines operators such as `map()`, `filter()`, `concat()`, and `flatMap()`.
flatMap is deprecated, please use mergeMap

2020-07-27 14:38 UTC, jbogarthyde commented on aio/content/guide/observables.md
>  In either case, a `next` handler is required. The `error` and `complete` handlers are optional.
What happens to the published values if there is no next handler? Should this option be mentioned?

2020-07-27 14:41 UTC, mary-poppins commented
You can preview ab174d9 at https://pr38165-ab174d9.ngbuilds.io/.

2020-07-27 14:46 UTC, jbogarthyde commented on aio/content/guide/observables.md
> +An observable can either produce values (calling the `next` callback), or it can complete, calling either the `complete` or `error` callback.
Is this true:  "It can also do none of these things, producing only side effects." 

 Is this why the "next" handler is not required? How would this work? Example?

Should there be a section discussing this usage? (Presumably it wouldn't go in the "Error handling" section.)

2020-07-27 15:02 UTC, mary-poppins commented
You can preview 54aa165 at https://pr38165-54aa165.ngbuilds.io/.

2020-07-27 16:18 UTC, niklas-wortmann commented on aio/content/guide/observables.md
> +An observable can either produce values (calling the `next` callback), or it can complete, calling either the `complete` or `error` callback.
yes it is true, but the next handler is not required just from an API design perspective, maybe you are not interested in the next values but just error or complete or you really just want to perform the side effects and therefore you just want to subscribe to an observable. 

I am not really sure if this should be covered in more detail as this is very specific and not really help with the overall understanding of rxjs. I just wanted to clarify this information here.

2020-07-27 16:21 UTC, niklas-wortmann commented on aio/content/guide/observables.md
>  In either case, a `next` handler is required. The `error` and `complete` handlers are optional.
so if you have no handler registered it will not be handled, but produced. So in angular, especially with the `async`pipe I often see people doing any kind of side effect in `tap` and actually not subscribing manually anymore therefore I would like this to be corrected. I am not sure what level of information should be part of this document, but probably @aikidave has an opinion on this

2020-07-27 17:15 UTC, jbogarthyde commented on aio/content/guide/observables.md
>  In either case, a `next` handler is required. The `error` and `complete` handlers are optional.
This does seem a bit out of scope, especially this early in the description. I took out the optional/required language.

2020-07-27 17:29 UTC, mary-poppins commented
You can preview 76e2a28 at https://pr38165-76e2a28.ngbuilds.io/.

2020-07-28 16:06 UTC, mary-poppins commented
You can preview f1617f6 at https://pr38165-f1617f6.ngbuilds.io/.

2020-07-29 20:18 UTC, mary-poppins commented
You can preview 699d0b9 at https://pr38165-699d0b9.ngbuilds.io/.

2020-07-29 20:45 UTC, kapunahelewong approved these changes
LGTM. Thank you, Judy!!

Reviewed-for: global-docs-approvers

2020-08-03 14:37 UTC, mary-poppins commented
You can preview 02b5671 at https://pr38165-02b5671.ngbuilds.io/.

2020-08-03 22:26 UTC, alxhub requested changes

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +You subscribe to an observable to consume values, and unsubscribe when the execution completes or you no longer need to listen for new values.
I think it's worth expanding on the concepts here, so I've taken a stab at this:

You subscribe to an observable to begin receiving values from it, and can unsubscribe when you no longer need to listen for new values. Some observables (such as those from `HttpClient`) are finite, and will unsubscribe automatically upon completion.

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +An `Observable` instance begins publishing values only when you subscribe to it.
It may be worth including here that subscribing may cause the observable to take some action to begin producing values - for example, subscribing to an `HttpClient` observable causes an HTTP request to be made.

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +As an alternative to passing in an observer object, the `subscribe()` method can accept inline callback function definitions for `next`, `error`, and `complete` handlers, in that order. For example,
Is it worth switching this example around? In my experience subscribing using an observer is fairly uncommon, and the majority of applications will use the inline form.

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +## Multicasting  values to multiple subscribers
```suggestion
## Multicasting values to multiple subscribers
```

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +Consider the following example that counts from 1 to 3, with a one-second delay after each number emitted.
It might be valuable to use `HttpClient` observables instead, since this offers a real-world example of when multicasting might be valueable.

A single HttpClient observable, subscribed twice -> two separate HTTP requests
A single HttpClient observable, multicasted and subscribed twice -> a single HTTP request with two observers

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +When creating the observable, you should determine how you want to use that observable and whether you want to multicast its values.
It's not actually when creating the observable, but when subscribing. You might want to multicast observables that you didn't create yourself (e.g. those from `HttpClient`).

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +The following code changes the observable to use multicasting instead:
Looking through the examples here, I think unfortunately they all really miss the point of multicasting.

The example actually has nothing to do with multicasting. It defines a custom "hot" observable which treats subsequent subscribers differently than the first one. This is not how most applications would make use of multicasting.

Most applications will deal with multicasting by using operators to share a single (unicast?) observable subscription among multiple subscribers, typically with the `multicast` or `share` operators (with which one can choose a specific `Subject` implementation to fine tune the behavior).

So a better set of examples would be:

1. One showing the problem of duplicate requests when subscribing to an HTTP request observable in two places
2. Using the `share()` operator to turn the observable into a multicast observable, ensuring that only one request is made for both subscriptions
3. Using the `shareReplay()` operator to ensure that late subscribers still receive the response, even after the HTTP request is complete.

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +Where the `catchError` operator provides a simple path of recovery, the [`retry` operator](https://rxjs.dev/api/operators/retry "RxJS API reference") lets you retry a failed request.
```suggestion
Whereas the `catchError` operator provides a simple path of recovery, the [`retry` operator](https://rxjs.dev/api/operators/retry "RxJS API reference") lets you retry a failed request.
```

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +For instance, suppose you have an observable that makes an API request and maps to the response from the server. If the server returns an error or the value doesn’t exist, an error is produced. If yo
```suggestion
For instance, suppose you have an observable that makes an API request and maps to the response from the server. If the server returns an error or the value doesn’t exist, an error is produced. If you catch this error and supply a default value, your stream continues to process values rather than propagating the error.
```

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +Use the `retry` operator before the `catchError` operator. It resubscribes to the original source observable, which can then re-run the full sequence of actions that resulted in the error. If this in
It might be worth mentioning that retrying works by re-subscribing to the original observable, which e.g. for HTTP requests, will result in a new request being fired.

That's also why it's important to `retry()` before `catchError()` or any multicasting operations like `share()`.

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +You can use _pipes_ to link operators together. Pipes let you combine multiple functions into a single function.
This is a little confusingly worded. There is no named concept of a "pipe" in Rx. `pipe()` is the name of the method we use to transform an observable via one or more operators.

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> + For Angular applications, it is recommended that you combine operators with pipes (rather than _chaining_, which is used in many RxJS examples).
```suggestion
 For Angular applications, it is recommended that you combine operators with `pipe()` (rather than _chaining_, which was used in older versions of RxJS).
```

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +<code-example path="rx-library/src/operators.1.ts" header="Standalone pipe function"></code-example>
Nobody uses the standalone `pipe` function - we should either switch these examples, or just not teach the standalone way at all.

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +| Utility | `tap` |
It might actually be useful to have a section on debugging RxJS code, where `tap` can come in handy for logging or adding breakpoints during an RxJS sequence.

2020-08-03 22:26 UTC, alxhub commented on aio/content/guide/observables.md
> +Using this naming convention can help you when you are scanning through code and looking for observable values, or when you want to associate an observable with a property that stores its returned va
I've also found it useful when you have both an Observable and its value in the same namespace. For example, within a template, the following might be common:
```html
<div *ngFor="let user of users$ | async as users">...</.div>
```
where `users$` is the Observable that's passed to the `async` pipe, and the unwrapped/emitted value is aliased as `users`. This saves you from having to get creative with naming for both the sync and async versions of a value.

2020-08-03 23:29 UTC, jbogarthyde commented on aio/content/guide/http.md
> + When you pass an interface as a type parameter to the `HttpClient.get()` method, you can use the [RxJS `map` operator](guide/observables#operators) to transform the response data as needed by the UI
massaged it a little -- not sure if it makes sense to shoehorn in the part about what to do with the response data - moved it out of the type discussion.

2020-08-03 23:51 UTC, jbogarthyde commented on aio/content/guide/observables.md
> +Consider the following example that counts from 1 to 3, with a one-second delay after each number emitted.
I added the description of the more realistic case, but left in the old example that shows how to make the observable multicasting.  

Can you make the observable returned by an `HttpClient` call multicasting? 
Again, the example came from someone else, and I can't create an equivalent -- do you want to try?

2020-08-03 23:57 UTC, jbogarthyde commented on aio/content/guide/observables.md
> +The following code changes the observable to use multicasting instead:
Can you or someone please supply these examples?

2020-08-04 00:12 UTC, jbogarthyde commented on aio/content/guide/observables.md
> +| Utility | `tap` |
Let me know if you can provide source for such a section.

2020-08-13 00:11 UTC, vhnguyen28 approved these changes

2020-08-13 14:43 UTC, aikithoughts requested changes
Need to examine these changes more thoroughly. Thanks!

2020-11-02 19:57 UTC, closed without merging