docs: mention ng-add save option
angular/angular pull request #38198
Opened 2020-07-23 13:55 UTC by timdeschryver

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The `save` option of the `ng-add` schematic, introduced in https://github.com/angular/angular-cli/pull/15815 isn't documented AFAIK. 
Yet, I think it can be useful to library authors.

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-07-23 17:02 UTC, alan-agius4 approved these changes
Approved on behalf of: docs-schematics

2020-07-23 17:13 UTC, alan-agius4 commented on aio/content/guide/schematics-for-libraries.md
> +
The `</code-example>` should be here.

2020-07-23 17:14 UTC, alan-agius4 requested changes
See above.

2020-07-23 17:32 UTC, gkalpak requested changes
Thx, @timdeschryver!

2020-07-23 17:32 UTC, gkalpak commented on aio/content/guide/schematics-for-libraries.md
> +<code-example lang="json" header="package.json">
Shouldn't this be:

```suggestion
<code-example lang="json" header="projects/my-lib/package.json">
```

2020-07-23 17:32 UTC, gkalpak commented on aio/content/guide/schematics-for-libraries.md
> +Possible values are;
```suggestion
Possible values are:
```

2020-07-23 18:20 UTC, timdeschryver commented
Thanks for the review @alan-agius4 and @gkalpak 👍

2020-07-24 07:26 UTC, gkalpak commented on aio/content/guide/schematics-for-libraries.md
> +
```suggestion
```

2020-07-24 07:26 UTC, gkalpak commented on aio/content/guide/schematics-for-libraries.md
> +  * `devDependencies` - Add the package to the devDependencies
Maybe wrap these in quotes to make it clear these are string values (while the `true`/`false` above are booleans):

```suggestion
  * `"dependencies"` - Add the package to the dependencies
  * `"devDependencies"` - Add the package to the devDependencies
```

2020-07-24 07:26 UTC, gkalpak commented on aio/content/guide/schematics-for-libraries.md
> +}
Instead of hard-coding the example here, would it make sense to actually included it in [projects/my-lib/package.json](https://github.com/angular/angular/blob/b7906e9ad98ae38df4b45ffe65e81d95b852a997/aio/content/examples/schematics-for-libraries/projects/my-lib/package.json)?

2020-07-24 10:00 UTC, timdeschryver commented
I've made these changes via the github editor, is there a way to verify that the snippet renders correctly?
I tried using https://pr38198-22e6276.ngbuilds.io/ from the preview build, but I get a 404.

If there's no way to preview, I'll pull this branch in and spin it up locally.

2020-07-24 10:02 UTC, mary-poppins commented
You can preview 12b8572 at https://pr38198-12b8572.ngbuilds.io/.
You can preview b7906e9 at https://pr38198-b7906e9.ngbuilds.io/.
You can preview 071a856 at https://pr38198-071a856.ngbuilds.io/.
You can preview 22e6276 at https://pr38198-22e6276.ngbuilds.io/.

2020-07-24 10:03 UTC, JoostK commented
> I've made these changes via the github editor, is there a way to verify that the snippet renders correctly?
> I tried using https://pr38198-22e6276.ngbuilds.io/ from the preview build, but I get a 404.
> 
> If there's no way to preview, I'll pull this branch in and spin it up locally.

I added the preview label for you, so you do now get the preview :-)

2020-07-24 10:10 UTC, timdeschryver commented
Here's the preview:

![image](https://user-images.githubusercontent.com/28659384/88381410-ae414600-cda6-11ea-9cc8-c760b6dca138.png)

2020-07-24 10:28 UTC, gkalpak approved these changes
One minor comment. Otherwise lgtm ✨

2020-07-24 10:28 UTC, gkalpak commented on aio/content/examples/schematics-for-libraries/projects/my-lib/package.json
> +}
I think it is better to keep the `ng-add` section out of the `collection` docregion, since the guide hasn't mentioned `ng-add` before showing the `collection` docregion:

```diff
   "schematics": "./schematics/collection.json",
+// #enddocregion collection
 // #docregion ng-add
   "ng-add": {
     "save": "devDependencies"
   }
 // #enddocregion ng-add
+// #docregion collection
 }
```

2020-07-24 11:05 UTC, timdeschryver commented on aio/content/examples/schematics-for-libraries/projects/my-lib/package.json
> +}
I agree.
I need to have a better understanding on how the docregions work 😅
Thanks for your review and patience

2020-07-24 11:17 UTC, mary-poppins commented
You can preview 913050e at https://pr38198-913050e.ngbuilds.io/.

2020-07-24 12:34 UTC, gkalpak commented on aio/content/examples/schematics-for-libraries/projects/my-lib/package.json
> +}
Thx for following through, @timdeschryver ❤️ 

BTW, in case you've missed it you can read all about docregions and code snippets in the [Code snippets](https://angular.io/guide/docs-style-guide#code-snippets) and [Source code markup](https://angular.io/guide/docs-style-guide#source-code-markup) sections of the Documentation Style Guide 😉

2020-07-24 15:10 UTC, gkalpak requested changes
Actually, I just realized (after @alan-agius4 dreaw my attention to it 😛) that the commits need to be squashed into one.

2020-07-24 19:06 UTC, timdeschryver commented
No problem @gkalpak  😁

2020-07-24 19:10 UTC, mary-poppins commented
You can preview 1b50149 at https://pr38198-1b50149.ngbuilds.io/.

2020-07-24 19:25 UTC, alan-agius4 approved these changes
LGTM

2020-07-26 13:10 UTC, gkalpak approved these changes

2020-07-27 16:52 UTC, closed without merging