docs(workspace-config): remove old content
angular/angular pull request #38243
Opened 2020-07-27 13:11 UTC by kasaharu

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
- Creating an application with `with ng generate application` does not add a project for end-to-end testing.

2021-01-15 02:11 UTC, clydin approved these changes

2021-01-15 09:20 UTC, gkalpak requested changes
Thx, @kasaharu!

Could you please update the commit message to not include `docs-infra` as the scope (`docs(docs-infra)` means "documentation for the documenttion infrastructure/tooling"). You can change it so something like:

> docs: remove old content from CLI configuration guide

2021-01-20 20:27 UTC, AndrewKushnir commented
@gkalpak I've rebased this PR and updated commit message as you proposed. Could you please have a quick look (and add the "merge" label if everything looks ok)? Thank you.

2021-01-21 16:47 UTC, gkalpak approved these changes

2021-01-21 21:49 UTC, closed without merging