fix(dev-infra): roll back phased review conditions
angular/angular pull request #38257
Opened 2020-07-27 23:28 UTC by atscott

It was determined that the list of 'pending' groups also included inactive groups.
That means that the 'no-groups-above-this-pending' would generally fail because
there's almost always some inactive group above it.

This commit removes the conditions for phased review while we
investigate if the inactive groups can be excluded.

2020-07-27 23:40 UTC, jelbourn approved these changes
LGTM

2020-07-27 23:58 UTC, josephperrott approved these changes
LGTM

2020-07-28 00:11 UTC, josephperrott requested changes
This change commit should actually be type `ci`

```
ci: roll back phased review conditions
```

2020-07-28 00:13 UTC, josephperrott approved these changes
LGTM

2020-07-28 17:02 UTC, closed without merging