fix(platform-browser): key event handler should run in the correct zone
angular/angular pull request #38263
Opened 2020-07-28 05:25 UTC by JiaLiPassion

Close #38260 .

Currently the KeyEventPlugin handle key event such as `keydown.enter` and always run into `ngZone` no matter
which zone it is added. And this behavior is not consistent with the other event handlers.

So this commit fixes this issue.

Also it make sure the `event handler` in key event plugin call on the correct context object.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #38260

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-07-29 19:45 UTC, mhevery requested changes

2020-07-29 19:45 UTC, mhevery commented on packages/platform-browser/test/dom/events/key_events_spec.ts
> +      it('key event handler should in the ngZone when added inside ngZone', () => {
```suggestion
      it('key event handler should be in the ngZone when added inside ngZone', () => {
```

2020-07-29 19:45 UTC, mhevery commented on packages/platform-browser/test/dom/events/key_events_spec.ts
> +      it('global key event handler should in the ngZone when added inside ngZone', () => {
```suggestion
      it('global key event handler should be in the ngZone when added inside ngZone', () => {
```

2020-07-29 19:45 UTC, mhevery commented on packages/platform-browser/test/dom/events/key_events_spec.ts
> +      it('key event handler should outside of the ngZone when added outside of the ngZone', () => {
```suggestion
      it('key event handler should be outside of the ngZone when added outside of the ngZone', () => {
```

2020-07-29 19:45 UTC, mhevery commented on packages/platform-browser/test/dom/events/key_events_spec.ts
> +      it('global key event handler should outside of the ngZone when added outside of the ngZone',
```suggestion
      it('global key event handler should be outside of the ngZone when added outside of the ngZone',
```

2020-07-29 19:45 UTC, mhevery commented on packages/platform-browser/testing/src/browser_util.ts
> +  for (let i = 0; i < keyCodeMapping.length; i++) {
instead of having a big loop, would it not be more intuitive to store `keyCodeMapping` as a map?

2020-07-29 19:45 UTC, mhevery commented on packages/platform-browser/testing/src/browser_util.ts
> +export function createKeyboardEvent(
This seems like a public API. Can we have proper jsdocs for it?

2020-07-29 19:45 UTC, mhevery commented on packages/platform-browser/src/dom/events/key_events.ts
> +    return function(this: unknown, event: any /** TODO #9100 */) {
could we resolve the todo?

2021-11-02 23:02 UTC, jessicajaniuk commented
@JiaLiPassion Any updates on this PR? Is it still needed?

2022-02-23 19:41 UTC, devversion approved these changes, later dismissed
LGTM conceptually. Nice 👍 

@JiaLiPassion should we also remove the `runGuarded` calls in other event plugins then?

2022-02-23 19:41 UTC, devversion commented on packages/platform-browser/src/dom/events/event_manager.ts
> +    if (NgZone.isInAngularZone()) {
How helpful is it actually knowing that the event is "registered" in the proper zone? Couldn't the event plugins still somehow mess this up, depending on how the event is registered (it might not be patched by zonejs for e.g. hammerjs right?)

TL;DR: Would it make sense to always run the handler guarded in the zone?

2022-02-24 02:15 UTC, dylhunn approved these changes
reviewed-for: fw-core

2022-02-28 12:12 UTC, JiaLiPassion commented on packages/platform-browser/src/dom/events/event_manager.ts
> +    if (NgZone.isInAngularZone()) {
@devversion, I updated the PR to include several fixes.
And the reason I didn't use 
```
ngZone.runOutside(() => {
  addEventListener(element, eventName, () => {
     ngZone.run(() => {listener(eventName});
  });
});
```
to do this because there are several issues with this solution.

1. this solution will bypass all functionality of `zone.js`, zone.js will not be able to moniter the `eventTask`, so the `onScheduleTask`, `onInvokeTask` will not be triggered if some user want to moniter.
2. now `zone.js` support `UNPATCHED_EVENTS` feature, the user can define `UNPATCHED_EVENTS=['mouseover', 'scroll']` so the `zone.js` will use the `native addEventListener` for these events, and the listeners will not trigger change detection. So if we are using the solution above, this feature will be lost.

So to still use `zone.js` functionality, the behavior should be ensure the `addEventListener` happened inside of `NgZone`.

2022-02-28 14:22 UTC, devversion reviewed
Seems very reasonable to me. Just added one question (similar to my previous) comment, wondering if we could simplify code a little more

2022-02-28 14:22 UTC, devversion commented on packages/core/src/application_ref.ts
> +      this._zone.run(() => this._tick());
This is related to my previous comment (which I think was a little confusingly phrased): Is there any benefit in checking with `NgZone.isInAngularZone()`, or could we just always run it in the zone? like:

```ts
function tick(): void {
  this._zone.run(() => this._tick());
}
```

2022-02-28 14:22 UTC, devversion commented on packages/platform-browser/src/dom/dom_renderer.ts
>      // can inspect the listener toString contents for the existence of this special token. Because
Can this logic below `event === '__ngUnwrap__'` be removed now?

2022-02-28 14:22 UTC, devversion commented on packages/platform-browser/src/dom/events/event_manager.ts
> +  ensureAddListenerInZone(element: HTMLElement, eventName: string, handler: Function): Function {
If you would be okay with it: I think we should add a `JSDoc` description here explaining why this is desirable. It's surely obvious to us from the context of your PR but this would be helpful long-term I feel like

2022-02-28 14:23 UTC, devversion commented on packages/platform-browser/src/dom/events/event_manager.ts
> +    if (NgZone.isInAngularZone()) {
@JiaLiPassion all of this makes sense! I think my comment was a little ambiguous/unclear. I was more asking why we would not always do the following:

```js
ngZone.run(() => 
  plugin.addEventListener(element, eventName, handlerEnsureInZone));
```

I added a new comment for it though. Thanks for the reply/and details.

2022-02-28 17:41 UTC, dylhunn submitted a review, later dismissed
reviewed-for: fw-core

2022-02-28 22:54 UTC, JiaLiPassion commented on packages/core/src/application_ref.ts
> +      this._zone.run(() => this._tick());
@devversion , the reason not to use `this._zone.run()` directly is if we use `this.zone.run()` even we are already inside the `NgZone`, it will trigger another `ApplicationRef.tick()` and cause the `NG0101 nested ApplicationRef.tick()` error.

2022-02-28 22:56 UTC, JiaLiPassion commented on packages/platform-browser/src/dom/dom_renderer.ts
>      // can inspect the listener toString contents for the existence of this special token. Because
I am just concerned about that some app or the dev tools are using `eventListener('__ngUnwrap__')` to retrive the original listener, I will remove it and if the `g3` is ok, I think it is safe.

2022-02-28 23:06 UTC, JiaLiPassion commented on packages/platform-browser/src/dom/events/event_manager.ts
> +  ensureAddListenerInZone(element: HTMLElement, eventName: string, handler: Function): Function {
Sure, I just add the `JSDoc` to explain this function.

2022-03-02 03:08 UTC, AndrewKushnir commented
[Global Presubmit](https://test.corp.google.com/OCL:431828588:BASE:431828730:1646190511323:68bf6ddf).

2022-03-02 05:38 UTC, AndrewKushnir commented
FYI, based on a global presubmit, there are ~500 failing targets, so I'm adding the "blocked" label for now.

2022-03-02 14:55 UTC, devversion commented on packages/platform-browser/src/dom/dom_renderer.ts
>      // can inspect the listener toString contents for the existence of this special token. Because
👍

2022-03-02 14:57 UTC, devversion commented on packages/core/src/application_ref.ts
> +      this._zone.run(() => this._tick());
interesting, good thing to have this noted here 👍

2023-03-25 02:44 UTC, closed without merging