feat(docs-infra): Lazy-loads SVG icons
angular/angular pull request #38268
Opened 2020-07-28 12:25 UTC by sonukapoor

Prior to this commit, SVG icons were all loaded in the constructor
of the `CustomIconRegistry`. This commit avoids that, and loads SVG
icons on demand.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-07-28 13:48 UTC, mary-poppins commented
You can preview abb6422 at https://pr38268-abb6422.ngbuilds.io/.

2020-07-28 21:49 UTC, gkalpak requested changes
Thx, @sonukapoor! I left a couple of minor comments/suggestions. Otherwise lgtm :+1:

BTW, I believe the commit message type should be `refactor` (or potentially `perfromance`, although this change is unlikely to have any tangible performance impact).

2020-07-28 21:49 UTC, gkalpak commented on aio/src/app/shared/custom-icon-registry.ts
> +  private svgIcons: SvgIconInfo[];
Could we mark the constructor parameter with `private` instead (and avoid the explicit declaration/assignment)?

2020-07-28 21:49 UTC, gkalpak commented on aio/src/app/shared/custom-icon-registry.ts
> +    let preloadedElement: SVGElement | undefined = nsIconMap && nsIconMap[iconName];
Do we need the explicit type?

2020-07-28 21:49 UTC, gkalpak commented on aio/src/app/shared/custom-icon-registry.ts
> +  private lazyloadSvgElement(iconName: string, namespace?: string) {
The `lazy` part is irrelevant here. This method loads an SVG element. Let's rename to `loadSvgElement()`.

2020-07-28 21:57 UTC, sonukapoor commented on aio/src/app/shared/custom-icon-registry.ts
> +    let preloadedElement: SVGElement | undefined = nsIconMap && nsIconMap[iconName];
Yes, we do. The `lazyLoadSvgElement` function can return `SVGElement` or `undefined`

2020-07-28 22:01 UTC, sonukapoor commented on aio/src/app/shared/custom-icon-registry.ts
> +  private svgIcons: SvgIconInfo[];
Oops.. yes. Should have done that in first place.

2020-07-28 22:08 UTC, gkalpak commented on aio/src/app/shared/custom-icon-registry.ts
> +    let preloadedElement: SVGElement | undefined = nsIconMap && nsIconMap[iconName];
But, I mean doesn't TypeScript automatically infer the type here?
(BTW, I am always in favor of adding types to method signatures, so feel free to add an explicit return type :grin:)

2020-07-28 22:11 UTC, mary-poppins commented
You can preview f01325f at https://pr38268-f01325f.ngbuilds.io/.

2020-07-29 01:27 UTC, sonukapoor commented on aio/src/app/shared/custom-icon-registry.ts
> +    let preloadedElement: SVGElement | undefined = nsIconMap && nsIconMap[iconName];
Unfortunately, it doesn't.

2020-07-29 01:38 UTC, mary-poppins commented
You can preview 1677bd1 at https://pr38268-1677bd1.ngbuilds.io/.

2020-07-29 07:50 UTC, gkalpak approved these changes
LGTM, thx :sparkles:

(For future commits, please try to follow the [commit message guidelines][1] more closely. For example, the [summary][2] must use imperative, present tense and not be capitalized.)

[1]: https://github.com/angular/angular/blob/57575e379fce9eb2367bfd48a8eb8be81f1d082c/CONTRIBUTING.md#commit
[2]: https://github.com/angular/angular/blob/57575e379fce9eb2367bfd48a8eb8be81f1d082c/CONTRIBUTING.md#summary

2020-07-29 17:33 UTC, closed without merging