fix(compiler-cli): type-check inputs that include undefined when there's coercion members
angular/angular pull request #38273
Opened 2020-07-28 18:19 UTC by JoostK

For attribute bindings that target a directive's input, the template
type checker is able to verify that the type of the input expression is
compatible with the directive's declaration for said input. This
checking adheres to the `strictNullChecks` flag as configured in the
TypeScript compilation, such that errors are reported for expressions
that include `undefined` or `null` in their type if the input's
declaration does not include those types.

There was a bug with this level of type-checking for directives that
also declare coercion members, where binding an expression that includes
the `undefined` type to a directive's input that does not include the
`undefined` type would not be reported as error.

This commit fixes the bug by changing the type-constructor in type-check
code to use an intersection type of regular inputs and coerced inputs,
instead of a union type. The union type would inadvertently allow
`undefined` types to be assigned into the regular inputs, as that would
still satisfy the characteristics of a union type.

2020-07-29 18:38 UTC, atscott commented
[presubmit](https://test.corp.google.com/ui#id=OCL:323823951:BASE:323824019:1596045746186:3f0c8d92)

2020-07-30 17:13 UTC, atscott requested changes
@JoostK - Can you update the commit message to include a small note about how to get around this, either by using a non-null assertion operator or by turning off `strictNullInputTypes` (?). In addition, maybe adding another test to demonstrate that `strictNullInputTypes: false` (again, not sure if this is the correct option) does not produce an error in this case.

2020-08-05 21:46 UTC, atscott approved these changes

2020-08-05 22:28 UTC, devversion approved these changes
LGTM for dev-infra.

@JoostK When you get a chance (for later reference): could you briefly explain why we go from v7 to v9 in the cache key?

2020-08-05 22:35 UTC, JoostK commented
D'oh! I meant to do that but then completely forgot about it.

I used the v8 key for testing against the required commit using my fork, to verify whether the components repo PR would actually build successfully. Upon switching back to the primary repo, the v8 fallback cache was poisoned with a checkout of my fork.

2020-08-06 22:21 UTC, closed without merging

2020-08-06 22:22 UTC, AndrewKushnir commented
Hi @JoostK, thanks for fixing the issue! 👍 

Quick question: should this PR be also included into the patch branch, since this is a fix (it has a `master-only` PR target atm)?

Thank you.

2020-08-06 22:35 UTC, atscott commented
@AndrewKushnir We merged to master only out of an abundance of caution. It's technically a breaking change because it can produce new errors that weren't detected before. Those errors _should_ have already been appearing though, so this is a bug fix but also breaking.

2020-08-06 22:36 UTC, atscott commented
@JoostK Speaking of breaking, should we have added the `BREAKING CHANGE:` footnote?

2020-08-06 22:38 UTC, AndrewKushnir commented
Thanks for additional information @atscott, that makes sense.

2020-08-07 16:46 UTC, JoostK commented
@AndrewKushnir the change to update the components repo commit should also be in patch, so I opened #38378 to land that in patch.

@atscott I intentionally did _not_ include an explicit breaking changes note, as we considered this as a true bug fix that can land anytime, without constraining ourselves to targeting it for a major. I guess we don't really have a proper communication channel to give people a heads up about these kinds of changes; the callout in the changelog would still be useful, but currently that can only be done using a breaking change note (AFAIK).

2020-08-07 16:52 UTC, AndrewKushnir commented
Thanks @JoostK 👍