Experimental and test only - Strictly types reactive forms
angular/angular pull request #38406
Opened 2020-08-11 02:32 UTC by sonukapoor

Based on the original work from #37389

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Feature

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2020-08-11 03:50 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:325946371:BASE:325946388:1597117795227:f501461d).

2020-08-11 04:04 UTC, destus90 commented on goldens/public-api/forms/forms.d.ts
> +    patchValue(value: null | T, options?: {
Is it correct? As described in the docs, we might provide some fields we would like to update, not the full model structure. With these changes, we will have some TypeScript types errors.
```suggestion
    patchValue(value: null | Partial<T>, options?: {
```

2020-08-11 13:04 UTC, KostyaTretyak commented on goldens/public-api/forms/forms.d.ts
> +    patchValue(value: null | T, options?: {
@destus90 , I think it's correct, `Partial<T>` need only for `FormGroup`. Please give an example with `FormControl` where `Partial<T>` really needs to be used.

2020-08-11 14:41 UTC, destus90 commented on goldens/public-api/forms/forms.d.ts
> +    patchValue(value: null | T, options?: {
Ok, you are right. At first I thought these changes will affect to all the reactive directives.

2020-08-11 22:00 UTC, AndrewKushnir commented
Hi,

Quick update after running tests in Google's codebase: this change is breaking a portion of targets.

I performed initial investigation and it looks like a lot of targets are failing with a similar error and we also have this scenario in tests:

```
const c = new FormControl(null, {validators});
c.setValue('value');
```

TypeScript infers the generic type (`T`) as `null`, thus the `setValue` call argument with the string type produces an error. In the tests this is solved by adding the `<string>` generic type, i.e.:

```
const c = new FormControl<string>(null, {validators});
c.setValue('value');
```

It'd be great to investigate if adding a generic type can be avoided in this case (without loosing type safety) - it should reduce the number of failing targets.

Thank you.

2020-08-25 19:39 UTC, JoostK commented
Quick note on the current state of the PR: Sonu and I made some changes over the weekend to strongly type `AbstractControl.value` and modified some constructor overloads in order to allow type inference to work as expected, but then hit a bit of a problem that is causing tests to fail left and right.

The gist of the issue that is yet to be resolved is how to deal with nullability in form controls, where type inference did not include the null. For example:

```ts
const group = new FormGroup({ name: 'Joost', age: 28 });
```

This will be inferred as `FormGroup<{name: string, age: number}>`, so `FormGroup.value` is typed as `{name: string, age: number}|null`, whereas it could be `{name: string|null, age: number|null}`. We played with a mapped type in `FormGroup.value`'s type, however that will start generating an incompatible redeclaration of `AbstractControl.value` as it is `T|null`.

---

Another use-case that needs some discussion is how to deal with `addControl`. This is an interesting API in terms of the keys that can be added, and how that newly added key can be accessed. If the `FormGroup` models some interface, then you'd expect the keys you can add to be restricted to the properties declared in the interface, but if the type is inferred then you may want to add additional controls after construction. The latter is problematic, given that it can't reflect the newly added key in te generic type (that would require `addControl` to have a return type and reassignment of the whole group). Also, the API can't differentiate between explicitly declared generic types (where it makes sense for `addControl` to be restricted) vs. an inferred type based on how the `FormGroup` was created (but no generic type declared). Add to that the backwards compatibility concert and you have several more constraints.

2020-09-29 15:45 UTC, AndrewKushnir commented
[Presubmit #2](http://test/OCL:334386792:BASE:334386832:1601394323682:a1a6fcad).

2020-10-01 07:01 UTC, wiesnery commented on goldens/public-api/forms/forms.d.ts
> +    get<T = any>(path: Array<string | number> | string): AbstractControl<T> | null;
can't we use something like:
`get<S extends keyof T>(path: Array<string | number> | S): AbstractControl<T[S]> | null  {`

This way we can achieve that we can only access FormControls wich are defined in the type.

2020-10-01 07:08 UTC, wiesnery commented on goldens/public-api/forms/forms.d.ts
> +    readonly value: T | null;
Maybe we could also think of using `Partial<T> | null` as return type, as some values might have a null value if they weren't initialized and we provide a useful hint to the consumer of the object.

2020-12-28 15:44 UTC, leo6104 requested changes

2020-12-28 15:44 UTC, leo6104 commented on goldens/public-api/forms/forms.d.ts
> +export declare interface FormArray<T = any> extends AbstractControl<T> {
```
export declare interface FormArray<T = any> extends AbstractControl<T[]> {
```
its AbstractControl should have T[] as value type. `AbstractControl<T[]>` 

```
formArray = new FormArray([ new FormControl(1), new FormControl(2) ]);
formArray.value // [ 1, 2 ] 
```

2021-04-01 04:06 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:366177614:BASE:366177629:1617249967434:2a0247c).

2021-06-29 14:19 UTC, ydmitry commented on packages/forms/test/value_accessor_integration_spec.ts
> +        next: (value: any) => {
`unknown` instead of `any` could be better here

2021-12-16 20:53 UTC, atscott commented
Closing since this is being actively worked on by @dylhunn as part of the typed forms project (#43834, #44513)

2021-12-16 20:53 UTC, closed without merging