docs: mention setUpLocationSync with $locationShim
angular/angular pull request #38472
Opened 2020-08-14 23:28 UTC by jamie-pate

$locationShim doesn't seem to connect to the Location service at all
if you don't call `setUpLocationSync` from @angular/router/upgrade

This may not be the best place, but it should be mentioned somewhere?

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-08-14 23:31 UTC, jamie-pate commented
@googlebot I signed it!

2020-08-20 15:38 UTC, gkalpak requested changes
Thx, @jamie-pate! I think this is a useful addition, but we should expand a bit/have a more clear explanation and instructions.

2020-08-20 15:38 UTC, gkalpak commented on aio/content/guide/upgrade.md
> +setUpLocationSync(this.upgrade);
This feels a little out of place in this code snippet. It is not clear where this code should be placed and what `this.upgrade` is.

Maybe you could add a new code snippet below and have a small paragraph explaining where/how to call it.

2020-12-08 11:20 UTC, petebacondarwin commented
@jamie-pate - are you able to address the comments from @gkalpak above so that we can merge this?

2021-04-17 12:31 UTC, petebacondarwin commented
@gkalpak - I think we might close this PR since we have not heard back from @jamie-pate ??

2021-04-17 14:44 UTC, closed without merging

2021-04-17 15:38 UTC, jamie-pate commented
Sorry for the lack of response, server had a very busy release schedule, but Angular is finally part of fortios 7.0.0!

I'm not sure I can properly document this, but feel it should be documented, since it's still very confusing. Until an owner of the upgrade system has time to add proper docs for this feature this dead pr will have to serve as a clue to others who are trying to upgrade.