docs: Typos fixes in built-in directives guide
angular/angular pull request #38520
Opened 2020-08-19 07:20 UTC by bampakoa

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-08-19 17:54 UTC, petebacondarwin requested changes

2020-08-19 17:54 UTC, petebacondarwin commented on aio/content/guide/built-in-directives.md
> +* Why we can only apply [one structural directive](guide/structural-directives#one-per-element "one per host element") to an element.
These changes are not typos but more subjective stylistic changes.
I don't think they are necessary in this case.

2020-08-19 17:54 UTC, petebacondarwin commented on aio/content/guide/built-in-directives.md
> +The following example shows `NgFor` applied to a simple `<div>`.
Also, this is not a typo. I will defer to the docs team as to whether this is suitable change... @kapunahelewong ?

2020-08-20 17:37 UTC, bampakoa commented on aio/content/guide/built-in-directives.md
> +* Why we can only apply [one structural directive](guide/structural-directives#one-per-element "one per host element") to an element.
@petebacondarwin you are right, especially about the first one. However, as I read the guide and stumbled upon the second one, it did not feel *natural* along with the other bullet points. What do you think?

2020-08-20 17:40 UTC, bampakoa commented on aio/content/guide/built-in-directives.md
> +The following example shows `NgFor` applied to a simple `<div>`.
@petebacondarwin thanks for your comment 😃 I stated it as a typo because the same sentence is repeated again in line 290

2020-08-24 17:01 UTC, kapunahelewong requested changes
Just a few suggestions. Thank you, @bampakoa!

2020-08-24 17:01 UTC, kapunahelewong commented on aio/content/guide/built-in-directives.md
> +The following example shows `NgFor` applied to a simple `<div>`.
Ah, I see. Good catch, @bampakoa.

2020-08-24 20:20 UTC, bampakoa commented
@kapunahelewong thanks very much for your suggestions. This is now ready.

2020-08-25 19:36 UTC, kapunahelewong approved these changes
LGTM @bampakoa! Could you squash? Thanks for this!


Reviewed-for: global-docs-approvers

2020-08-25 22:15 UTC, bampakoa commented
@kapunahelewong oh yes, I always forget squashing. Sorry about that 😊 . I think it is ok now

2020-08-26 12:48 UTC, petebacondarwin approved these changes

2020-08-26 12:50 UTC, petebacondarwin approved these changes
One thing I would say, not so important for this fix is that the commit heading should be of the form of an imperative statement. I.e. `fix typos in the built-in directives guide` rather than `Typos fixes in built-in directives guide`. We are stating the action that the commit is doing to the code base rather than a description of the change in the heading.

2020-10-16 16:05 UTC, gkalpak approved these changes
Reviewed-for: global-docs-approvers

2020-10-16 17:05 UTC, closed without merging