fix(router): preload router should use loaded config #38557
angular/angular pull request #38567
Opened 2020-08-25 02:07 UTC by zangguodong

Router preloading use asynchronous calculation, but if we navigate to target route when that calculation not complete.
This may cause applyRedirect create config for that route.
After a while, preload procedure got its _loadedConfig and override the one created by applyRedirect.
This is naturally not we want, it may cause page component destroy and rebuild unintentional.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 38557

## What is the new behavior?

Async prelad will use Loadedconfig, not create new one

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-08-25 02:14 UTC, zangguodong commented
@googlebot I fixed it.

2020-08-28 08:22 UTC, zangguodong commented
@atscott please give review, your comments are welcome 😁

2020-08-28 16:10 UTC, atscott requested changes
Hi @zangguodong, this doesn't quite fix the underlying issue fully. Take a look at this PR #36760. You should should return the loaded config if it exists before calling `loader.load` or you would still end up loading that module twice (even if the result is unused on the second load). Additionally, this doesn't solve the interaction between routing and preloading. Navigation to a route with a lazy loaded module will load the config a second time if a load is in progress. 

If you want to adapt part of the solution in that PR into this one and fix up the tests, I can review it again. It looks like the author there isn't working on the requested changes.

2020-08-31 01:00 UTC, zangguodong commented
> Hi @zangguodong, this doesn't quite fix the underlying issue fully. Take a look at this PR #36760. You should should return the loaded config if it exists before calling `loader.load` or you would still end up loading that module twice (even if the result is unused on the second load). Additionally, this doesn't solve the interaction between routing and preloading. Navigation to a route with a lazy loaded module will load the config a second time if a load is in progress.
> 
> If you want to adapt part of the solution in that PR into this one and fix up the tests, I can review it again. It looks like the author there isn't working on the requested changes.

Thanks for advising, i've been learning about pr #36760, which gives me many many benefits. He use operator self to judge whether in progress, and prevent duplication load.
It means a lot to me. Sincerely, and hope to contribute to ng next time~

2020-08-31 01:00 UTC, closed without merging