feat(dev-infra): tool for checking service statuses
angular/angular pull request #38601
Opened 2020-08-26 21:13 UTC by josephperrott

The angular team relies on a number of services for hosting code, running CI, etc. This
tool allows for checking the operational status of all services at once.

2020-08-27 09:53 UTC, devversion approved these changes
LGTM. nice! 

I wonder if there would be name category for these utils. `yarn ng-dev caretaker` is a bit out of the row IMO because technically `merge` / `rebase` etc. could be part of that too, right?

2020-08-27 09:53 UTC, devversion commented on dev-infra/caretaker/service-statuses/cli.ts
> +  describe: 'check statuses',
Nit: Add a more meaningful description here?

2020-08-27 09:53 UTC, devversion commented on dev-infra/caretaker/service-statuses/service-statuses.ts
> +  info(`Statuses checked at: ${new Date().toString()}`);
Just a thought: Did you consider using `toLocaleString()`?

2020-08-27 17:58 UTC, devversion approved these changes

2020-08-28 22:24 UTC, Matausi29 approved these changes

2020-08-28 22:36 UTC, Matausi29 approved these changes

2020-08-28 22:54 UTC, josephperrott commented
@devversion PTAL nearly everything has changed since your last review

2020-08-31 08:34 UTC, devversion commented on .ng-dev/caretaker.ts
> +      query: `is:pr is:open status:success label:"PR action: merge-assistance"`,
I think the labels now need to be updated to `action:` due to our recent changes

2020-08-31 08:34 UTC, devversion commented on dev-infra/caretaker/check/check.ts
> +  await getG3Comparison(git);
I'd change the functions to `print` instead of `get` because they are not returning anything.

2020-08-31 08:34 UTC, devversion commented on dev-infra/caretaker/check/cli.ts
> +export interface CheckOptions {
```suggestion
export interface CaretakerCheckOptions {
```

2020-08-31 08:34 UTC, devversion commented on dev-infra/caretaker/check/g3.ts
> +  git.run(['fetch', 'upstream']);
Generally, we don't assume `upstream` in the repository. Can we just use the http/ssh URL from the git client as in all other tools?

2020-08-31 08:34 UTC, devversion commented on dev-infra/caretaker/check/g3.ts
> +  git.run(['fetch', 'upstream']);
You could even fetch only specific branches to speed this up. i.e. g3 and `master`.

2020-08-31 08:34 UTC, devversion commented on dev-infra/caretaker/check/g3.ts
> +      parseYaml(readFileSync(join(getRepoBaseDir(), '.github/angular-robot.yml')).toString());
It's a bit unfortunate that we go against our practice of having dev-infra command configurations inside the `.ng-dev` folder. Can we have a comment and check for the Angular robot config to be set up instead of failing unexpectedly if not set up?

2020-08-31 08:34 UTC, devversion commented on dev-infra/caretaker/check/g3.ts
> +          line => [parseInt(line[0], 10), parseInt(line[1], 10),
Maybe even add an example of the output to the comment above for parsing.

```suggestion
          line => [Number(line[0]), Number(line[1]), line[2]]),
```

2020-08-31 08:34 UTC, devversion commented on dev-infra/caretaker/check/g3.ts
> +        diffStats.all.files += 1;
I guess it's nice to have, but where is `all` used? Since this function is local to the `g3` file and not a dev-infra util, I think we should just remove it.

2020-08-31 08:34 UTC, devversion commented on dev-infra/caretaker/check/github.ts
> +  const repo = `repo:${git.remoteConfig.owner}/${git.remoteConfig.name}`;
```suggestion
  /** The Github search filter for the configured repository. */
  const repoFilter = `repo:${git.remoteConfig.owner}/${git.remoteConfig.name}`;
```

2020-08-31 08:34 UTC, devversion commented on dev-infra/caretaker/check/github.ts
> +    title = queries.find(query => query.name.replace(/ /g, '') === title)?.name || title;
I think we could do a little better here by just assuming order as is?

2020-08-31 08:34 UTC, devversion commented on dev-infra/utils/git/index.ts
> +    // info('Executing: git', this.omitGithubTokenFromMessage(args.join(' ')));
I assume this is not desired to land as part of this PR right? might be a leftover from testing

2020-08-31 17:49 UTC, josephperrott commented on dev-infra/caretaker/check/g3.ts
> +      parseYaml(readFileSync(join(getRepoBaseDir(), '.github/angular-robot.yml')).toString());
I had planned to put in the checks and forgot, done now.

2020-08-31 17:52 UTC, josephperrott commented on dev-infra/caretaker/check/g3.ts
> +        diffStats.all.files += 1;
I originally had included lines about both all changes and g3 scoped changes

2020-08-31 17:54 UTC, josephperrott commented on dev-infra/utils/git/index.ts
> +    // info('Executing: git', this.omitGithubTokenFromMessage(args.join(' ')));
Correct, oops

2020-08-31 18:01 UTC, josephperrott commented on dev-infra/caretaker/check/github.ts
> +    title = queries.find(query => query.name.replace(/ /g, '') === title)?.name || title;
Done, I didn't believe the order was preserved, but after searching a bit it seems that it is expected to be.

2020-08-31 18:10 UTC, devversion requested changes
LGTM. One minor comment that could simplify things a bit

2020-08-31 18:10 UTC, devversion commented on dev-infra/caretaker/check/g3.ts
> +  const fetchResult = git.runGraceful(['fetch', refUrl, `master:${masterRef}`, `g3:${g3Ref}`]);
We could just fetch the branches but not specify a destination, right? That way we can later just access them from the remote and we wouldn't need to deal with random prefix and deletion

2020-08-31 18:42 UTC, josephperrott commented on dev-infra/caretaker/check/g3.ts
> +  const fetchResult = git.runGraceful(['fetch', refUrl, `master:${masterRef}`, `g3:${g3Ref}`]);
As far as I can tell, `git diff` and `git rev-list` are not able to run against url refs.  And since there is only one `FETCH_HEAD`, we end up needing to store at least one of them in a named location.

2020-09-01 19:06 UTC, devversion commented on dev-infra/caretaker/check/g3.ts
> +  const fetchResult = git.runGraceful(['fetch', refUrl, `master:${masterRef}`, `g3:${g3Ref}`]);
Oh, I was somehow under the impression that we could access them both from the `FETCH_HEAD` file. I think ideally we'd just get the refs from `g3` and `master` and deal with those instead of writing to temporary branches, but I don't feel too strong about it. Personally I just don't like to create branches if they aren't needed.

2020-09-01 19:07 UTC, devversion approved these changes

2020-09-01 20:05 UTC, closed without merging