fix(docs): Clear up scenario in which ngOnChanges is not called before ngOnInit. Closes #38613
angular/angular pull request #38625
Opened 2020-08-28 08:19 UTC by danmana

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #38613

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-08-28 18:22 UTC, kapunahelewong requested changes
Thanks for this, @danmana! We will still need engineering review and approval, but here's one suggestion from a docs style perspective.

2020-08-28 18:22 UTC, kapunahelewong commented on aio/content/guide/lifecycle-hooks.md
> +	  Note that if your component is used without binding any inputs, `ngOnChanges()` will not be called.
```suggestion
	  Note that a component  must bind at least one `@Input()` in order to use `ngOnChanges()`.
```

Here's an idea to switch it from passive to active voice. Does this maintain the meaning you intend?

2020-08-28 18:44 UTC, AndrewKushnir commented on aio/content/guide/lifecycle-hooks.md
> +	  Note that if your component is used without binding any inputs, `ngOnChanges()` will not be called.
@kapunahelewong I think the meaning was slightly changed.

We should communicate that the `ngOnChanges()` lifecycle hook is not invoked in the following cases:

- if a component has no inputs
- if a component has inputs, but they are not provided during component initialization

Here is my attempt to update original text to reflect that:
```
Note that if your component has no inputs or it's used without providing any inputs, `ngOnChanges()` will not be called.
```

@kapunahelewong what do you think? Please let us know if there is a better way to phrase it given the above-mentioned conditions (when `ngOnChanges()` is not invoked).

2020-08-31 13:52 UTC, kapunahelewong commented on aio/content/guide/lifecycle-hooks.md
> +	  Note that if your component is used without binding any inputs, `ngOnChanges()` will not be called.
Oh, thank you @AndrewKushnir. Now I understand better. Is there a way to state _what_ is calling (or not calling) `ngOnChanges()`? I ask because to fully change the sentence to the active voice we would just need to tweak it a little. So if we could do something like this:

```
Note that if your component has no inputs or you use it without providing any inputs, _________ will not call `ngOnChanges()`.
```

So, only these two tweaks: 
1. `is used` --> `you use`
2. a subject for whatʻs doing the calling of `ngOnChanges()`. 

Thank you for bearing with me!

2020-08-31 16:36 UTC, AndrewKushnir commented on aio/content/guide/lifecycle-hooks.md
> +	  Note that if your component is used without binding any inputs, `ngOnChanges()` will not be called.
Thanks for updating the message @kapunahelewong 👍 The `ngOnChanges` is called by the framework, so the final version of the message might look like this:

```
Note that if your component has no inputs or you use it without providing any inputs, the framework will not call `ngOnChanges()`.
```

2020-09-03 18:02 UTC, AndrewKushnir approved these changes
The change LGTM, thanks for improving Angular docs @danmana!

Could you please update the commit message so that the `lint` check pass? For example:

```
docs: describe a scenario in which ngOnChanges is not called before ngOnInit

Closes #38613.
```

Thank you.

2020-09-04 15:16 UTC, AndrewKushnir commented
Hi @danmana, thanks for updating commit message, it looks good.

@kapunahelewong could you please review this PR once again when you get a chance?

Thank you.

2020-09-08 19:27 UTC, kapunahelewong approved these changes
LGTM! Thank you, @danmana 

Reviewed-for: global-docs-approvers

2020-09-08 21:06 UTC, closed without merging