feat(zone.js): test zone.js packge with tgz
angular/angular pull request #38649
Opened 2020-08-31 04:49 UTC by JiaLiPassion

2020-08-31 20:00 UTC, gkalpak requested changes
Nit: The commit message should be of type `build` or `test`. Otherwise lgtm.

While I don't mind the changes, I wonder whether we are testing the implementation of `npm_package` vs `npm_package.pack`. Is it expected that `npm_package` would yield different results than `npm_package.pack`? Or is it a bug in `npm_package`?

2020-08-31 20:00 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +  if (test('-d', distArchiveDir)) rm('-rf', distArchiveDir);
Why not just:

```suggestion
  rm('-rf', distArchiveDir);
```

2020-08-31 20:00 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +  console.info(`# Copy npm_package archive file to ${distTargetDir}`);
Let's move this above the associated commands (starting with the `rm()` command two lines above).

2020-08-31 20:00 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +  const distArchiveDir = `${absDestPath}/archive`;
```suggestion
  const distArchiveTargetDir = `${absDestPath}/archive`;
```

2020-08-31 20:00 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +  cp('-R', `${baseDir}/zone.js-${zonePackageJson.version}.tgz`, `${distArchiveDir}/zone.js.tgz`);
This will be included in the [published build artifacts][1] for each PR ([example][2]). This is a little confusing, because this is not really a package published to npm (it is just a directive containing a `.tgz` file).
Maybe at least rename the `archive` directory to something more descriptive, such as `zone.js-as-tgz`.

[1]: https://github.com/angular/angular/blob/4f28192d62b59a4a45f7f27890e9fb356e2cf885/docs/DEVELOPER.md#getting-packages-from-build-artifacts
[2]: https://app.circleci.com/pipelines/github/angular/angular/20623/workflows/95e0117d-09f7-42d1-8262-6bf6e559f94a/jobs/796646/artifacts

2020-09-03 16:43 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +  if (test('-d', distArchiveDir)) rm('-rf', distArchiveDir);
Thanks for the review, I will update this one.

2020-09-03 16:49 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +  console.info(`# Copy npm_package archive file to ${distTargetDir}`);
Got it!

2020-09-03 16:49 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +  const distArchiveDir = `${absDestPath}/archive`;
Got it!

2020-09-03 16:51 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +  cp('-R', `${baseDir}/zone.js-${zonePackageJson.version}.tgz`, `${distArchiveDir}/zone.js.tgz`);
Thanks for pointing out this one, I don't know there is an `artifacts` there, I will try to find out whether I can add this `zone.js-as-tgz` there too.

2020-09-03 17:22 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +  cp('-R', `${baseDir}/zone.js-${zonePackageJson.version}.tgz`, `${distArchiveDir}/zone.js.tgz`);
It is added automatically. The script that prepares the artifacts is [scripts/ci/create-package-archives.sh][1]

[1]: https://github.com/angular/angular/blob/2cb3d58b428c211c660d82eb82a566b68124f74c/scripts/ci/create-package-archives.sh

2020-09-10 04:03 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +  cp('-R', `${baseDir}/zone.js-${zonePackageJson.version}.tgz`, `${distArchiveDir}/zone.js.tgz`);
@gkalpak , I added the script here https://github.com/angular/angular/pull/38649/files#diff-1d37e48f9ceff6d8030570cd36286a61R568 to remove the tar directory before creating the archive dir.

2020-09-15 23:54 UTC, mhevery approved these changes

2020-09-16 12:17 UTC, JiaLiPassion commented
@gkalpak, could you check this PR again? Thanks.

2020-09-16 15:28 UTC, gkalpak requested changes

2020-09-16 15:28 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +const zonePackageJson = require('../../packages/zone.js/package.json');
Let's keep the imports alphabetically ordered:

```suggestion
const zonePackageJson = require('../../packages/zone.js/package.json');
const {baseDir, bazelBin, bazelCmd, exec, scriptPath} = require('./package-builder');
```

2020-09-16 15:28 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +  const distArchiveDir = `${absDestPath}/archive`;
```suggestion
  const distArchiveTargetDir = `${absDestPath}/archive`;
```

2020-09-16 15:28 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +  if (test('-d', distArchiveDir)) rm('-rf', distArchiveDir);
Why not just:

```suggestion
  rm('-rf', distArchiveDir);
```

2020-09-16 15:28 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +  console.info(`# Copy npm_package archive file to ${distTargetDir}`);
Let's move this above the associated commands (starting with the `rm()` command two lines above).

2020-09-16 15:28 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +  cp('-R', `${baseDir}/zone.js-${zonePackageJson.version}.tgz`, `${distArchiveDir}/zone.js.tgz`);
I don't see where/how this is being resolved. Did you provide the wrong link?

2020-09-16 21:03 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +const zonePackageJson = require('../../packages/zone.js/package.json');
Got it, just updated, thanks.

2020-09-16 21:04 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +  const distArchiveDir = `${absDestPath}/archive`;
Sorry, it happened again, I pushed the wrong commit.

2020-09-16 21:04 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +  if (test('-d', distArchiveDir)) rm('-rf', distArchiveDir);
Sorry, it happened again, I pushed the wrong commit.

2020-09-16 21:04 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +  console.info(`# Copy npm_package archive file to ${distTargetDir}`);
Sorry, it happened again, I pushed the wrong commit.

2020-09-16 21:05 UTC, JiaLiPassion commented
@gkalpak , Sorry, it happened again, I pushed the wrong commit. Please take a look again, and I added the logic to remove `zone.js-dist/archive` dir before publish archive in circleci here https://github.com/angular/angular/pull/38649/files#diff-1d37e48f9ceff6d8030570cd36286a61R569

2020-09-17 10:45 UTC, gkalpak requested changes
No worries, @JiaLiPassion. Thx for making the changes :+1:

2020-09-17 10:45 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +  exec(`${bazelCmd} --output_base=$(mktemp -d) run //packages/zone.js:npm_package.pack`);
I am concerned the `mktemp -d` part makes it less platform-agnostic (e.g. does it work on Windows?).
I think it would be better to use something like Node.js' [fs.mkdtempSync()][1].

[1]: https://nodejs.org/api/fs.html#fs_fs_mkdtempsync_prefix_options

2020-09-17 10:45 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +     `${distArchiveTargetDir}/zone.js.tgz`);
I am a little confused here. Does the `//packages/zone.js:npm_package.pack` command above generate a `.tgz` file in `baseDir`? What is the purpose of specifying `--output_base` then?

Also, you shouldn't need the `-R` option (since we are copying files, not directories):

```suggestion
  cp(`${baseDir}/zone.js-${zonePackageJson.version}.tgz`, `${distArchiveTargetDir}/zone.js.tgz`);
```

2020-09-17 10:45 UTC, gkalpak commented on .circleci/config.yml
> +          command: rm -rf $ZONEJS_PACKAGES_DIR/archive && ./scripts/ci/create-package-archives.sh $CI_BRANCH $CI_COMMIT $ZONEJS_PACKAGES_DIR $ZONEJS_PACKAGES_ARCHIVES_DIR
Not super happy with this, but it's good enough for now.

2020-09-18 01:05 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +  exec(`${bazelCmd} --output_base=$(mktemp -d) run //packages/zone.js:npm_package.pack`);
I just removed the `--output_base` since I believe it is only used in local build.

2020-09-18 01:05 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +     `${distArchiveTargetDir}/zone.js.tgz`);
Yeah, you are right, thanks.

2020-09-18 01:05 UTC, JiaLiPassion commented on .circleci/config.yml
> +          command: rm -rf $ZONEJS_PACKAGES_DIR/archive && ./scripts/ci/create-package-archives.sh $CI_BRANCH $CI_COMMIT $ZONEJS_PACKAGES_DIR $ZONEJS_PACKAGES_ARCHIVES_DIR
Got it, will consider better method later.

2020-09-19 17:48 UTC, gkalpak requested changes
Generally lgtm, but I am a little concernd about the potential Windows incompatibility. (We need to investigate that before merging.)

BTW, there's a typo in the commit message header:

```diff
-test(zone.js): test zone.js packge with tgz
+test(zone.js): test zone.js package with tgz
```

2020-09-19 17:48 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +  cp(`${baseDir}/zone.js-${zonePackageJson.version}.tgz`, `${distArchiveTargetDir}/zone.js.tgz`);
This will leave untracked `.tgz` files in the user's root dir (which they might accidentally commit or will have to manually delete).

I don't know if there is a way to specify the output directory. If not, we could use `mv()` instead of `cp()`.

2020-09-19 17:48 UTC, gkalpak commented on scripts/build/zone-js-builder.js
> +  exec(`${bazelCmd} run //packages/zone.js:npm_package.pack`);
This command fails for me on Windows. I don't know yet whether it is just me or an `npm_package.pack` issue with Windows, but I don't want to change this script in a way that breaks Windows users.
(NOTE: This script is also used when you want to test angular.io against the locally built Angular packages.)

I have started a discussion [here][1] (sorry, not public).

[1]: https://angular-team.slack.com/archives/C042EU9T5/p1600524045002400

2020-09-19 23:45 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +  cp(`${baseDir}/zone.js-${zonePackageJson.version}.tgz`, `${distArchiveTargetDir}/zone.js.tgz`);
Got it, thanks.

2020-09-19 23:47 UTC, JiaLiPassion commented on scripts/build/zone-js-builder.js
> +  exec(`${bazelCmd} run //packages/zone.js:npm_package.pack`);
Yeah, I tested it too, it throw a error like this.
```
java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(356): NativeProcess:WriteStdin(1153200)
```

2020-10-14 23:58 UTC, IgorMinar reviewed
this change looks good to me, if we can resolve the Windows incompatibility.

2020-10-15 21:19 UTC, AndrewKushnir commented
FYI, replacing "merge" label with "cleanup" one since there is a conflict with master branch. Feel free to put the "merge" label back once this PR is rebased. Thank you.

2020-10-15 23:47 UTC, JiaLiPassion commented
@AndrewKushnir , got it, thanks!

@gkalpak, I tried again, to run `bazel clean` and build on windows, it seems now it run successfully, could you check it again?
Thank you!

2020-10-17 18:33 UTC, gkalpak commented
It is still failing for me 😕

2020-10-19 09:55 UTC, gkalpak commented
@googlebot I consent.

2020-10-19 09:55 UTC, gkalpak approved these changes

2020-10-19 15:06 UTC, closed without merging