fix(router): remove preserveQueryParams symbol
angular/angular pull request #38762
Opened 2020-09-09 16:56 UTC by josephperrott

Remove preserveQueryParams as it was deprecated for removal in v4, use
queryParamsHandling="preserve" instead.

2020-09-15 16:01 UTC, atscott approved these changes
LGTM, but would add blocked label to wait for the migration PR to merge.

2020-09-17 23:20 UTC, IgorMinar approved these changes
This one has been deprecated for a long time, so it's great that we are removing it!

Do we understand the impact of this change? it's likely low, but we should verify. I see at least two instances in google3, I haven't tried to search github.

If a migration was part of this PR then this change would be totally fine, but I get that creating migrations for absolutely everything doesn't always makes sense const/benefits-wise. Maybe get @mgechev to weigh in on skipping a migration?

If we are not going to create a migration for this change, then we should at least document the decision in the PR with a brief justification, something along the lines: "This api has been deprecated for a long time, and we don't have evidence that it's being used.

And additionally we should highlight this change in the v11 release notes / update guide.

Otherwise lgtm.

2020-09-17 23:20 UTC, IgorMinar commented on aio/content/guide/deprecations.md
> -{@a router}
instead of deleting this section, can you please move it to the removed apis section: https://angular.io/guide/deprecations#removed-apis-1

2020-09-18 06:28 UTC, petebacondarwin approved these changes
Reviewed-for: public-api

LGTM after @IgorMinar's comments are addressed.

2020-09-29 00:03 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2020-10-05 19:26 UTC, IgorMinar requested changes
just resubmitting https://github.com/angular/angular/pull/38762#pullrequestreview-491047920 to get this out of my review queue for now

Reviewed-for: public-api, docs-packaging-and-releasing

2020-10-12 20:08 UTC, IgorMinar requested changes
just a few nits, the rest looks good.

2020-10-12 20:08 UTC, IgorMinar commented on packages/core/schematics/test/preserve_query_params_migration_spec.ts
> +    it('should migrate when the value is `false`', async () => {
```suggestion
    it('should remove when the value is `false`', async () => {
```

2020-10-12 20:08 UTC, IgorMinar commented on packages/core/schematics/test/preserve_query_params_migration_spec.ts
> +    it('should migrate when the property is unused', async () => {
```suggestion
    it('should not modify when the property is not present', async () => {
```

2020-10-12 20:08 UTC, IgorMinar commented on packages/core/schematics/test/preserve_query_params_migration_spec.ts
> +    it('should migrate when the value is `false`', async () => {
```suggestion
    it('should remove when the value is `false`', async () => {
```

2020-10-12 20:08 UTC, IgorMinar commented on packages/core/schematics/test/preserve_query_params_migration_spec.ts
> +    it('should migrate when the property is unused', async () => {
```suggestion
    it('should not modify when the property is not present', async () => {
```

2020-10-12 20:08 UTC, IgorMinar commented on packages/core/schematics/migrations/router-preserve-query-params/README.md
> +    this._router.navigate('/', { skipLocationChange: 'foo', queryParamsHandler: 'preserve' });
it is easier to spot the difference if you preserve the prop order:

```suggestion
    this._router.navigate('/', { queryParamsHandler: 'preserve', skipLocationChange: 'foo' });
```

2020-10-12 20:08 UTC, IgorMinar commented on aio/content/guide/deprecations.md
> -{@a router}
Please update the deprecations.md as mentioned above. thanks!

2020-10-14 16:29 UTC, IgorMinar approved these changes
LGTM! Thanks!

Reviewed-for: public-api

2020-10-14 16:30 UTC, IgorMinar approved these changes

2020-10-14 16:31 UTC, IgorMinar approved these changes
Reviewed-for: global-approvers, docs-packaging-and-releasing, dev-infra,

2020-10-14 17:41 UTC, closed without merging