docs: describe your change...
angular/angular pull request #38770
Opened 2020-09-09 19:18 UTC by Mwiku

Update the build output folder name. Newer versions of angular put the production build output in the folder "dist/workspace-name"

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-09-10 13:40 UTC, gkalpak requested changes
Good catch! Thx, @Mwiku :+1:

While you are at it, there are a few more places that need updating:
- [L100]
- [L214] and [L218], where I would change `dist/` to `project-name/`.
- [L386]
- [L399] (also remove the `.bundle` part):
  ```diff
  -node_modules/.bin/source-map-explorer dist/main.*.bundle.js
  +node_modules/.bin/source-map-explorer dist/project-name/main.*.js
  ```

Could you take care of them as well?

Also, please change the commit message to something descriptive (according to our [commit message guidelines](https://github.com/angular/angular/blob/1d9e56eba06958e37ef8062ae7b65afa85f90632/CONTRIBUTING.md#commit)), such as:

> docs: update build directory in Deployment guide

##
You have probably created the pull request via the GitHub UI, which does not allow you to update it directly. You can either check out your branch locally and update it using `git` (either on the command-line or via a UI git client) or you can create a new pull request via the GitHub UI (and close this one).

LMK if you have any trouble making the changes. I'd be happy to help out.

[L100]: https://github.com/angular/angular/blame/28cc87c79c5dae7bbd3726042cc3aee470c6774b/aio/content/guide/deployment.md#L100
[L214]: https://github.com/angular/angular/blame/28cc87c79c5dae7bbd3726042cc3aee470c6774b/aio/content/guide/deployment.md#L214
[L218]: https://github.com/angular/angular/blame/28cc87c79c5dae7bbd3726042cc3aee470c6774b/aio/content/guide/deployment.md#L218
[L386]: https://github.com/angular/angular/blame/28cc87c79c5dae7bbd3726042cc3aee470c6774b/aio/content/guide/deployment.md#L386
[L399]: https://github.com/angular/angular/blame/28cc87c79c5dae7bbd3726042cc3aee470c6774b/aio/content/guide/deployment.md#L399

2020-09-10 13:40 UTC, gkalpak commented on aio/content/guide/deployment.md
> +  ls dist/workspace-name/*.bundle.js
This is actually the project name (which might or might not be the same as the workspace name). Also, the `.bundle` part has been dropped from the file names for a while.

```suggestion
  ls dist/project-name/*.js
```

2020-09-17 23:22 UTC, IgorMinar requested changes
+1 to @gkalpak's suggestion.

2021-01-25 22:25 UTC, jelbourn commented
Closing this PR due to lack of CLA

2021-01-25 22:25 UTC, closed without merging