feat(common): Add ISO week-numbering year formats support to formatDate
angular/angular pull request #38828
Opened 2020-09-12 15:02 UTC by prashant-tholia

Add ISO 8601 week-numbering year formats ('r', 'rr', 'rrr', 'rrrr') support for formatDate function.

Issue:https://github.com/angular/angular/issues/38739

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
No current behavior. New feature.

Issue Number: 38739

## What is the new behavior?
Examples - 
formatDate('2013-06-14', 'rrrr', 'en') //'2013'
formatDate('2013-12-29', 'rrrr', 'en') //'2013'
formatDate('2013-12-31', 'rrrr', 'en') //'2014'

formatDate('2010-08-04', 'rrrr', 'en') //'2010'
formatDate('2010-01-02', 'rrrr', 'en') //'2009'
formatDate('2010-01-04', 'rrrr', 'en') //'2010'

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-09-13 18:04 UTC, sonukapoor commented on packages/common/src/i18n/format_date.ts
> +    // 2010 => 2010)
Should this be `2010 => 010`?

2020-09-13 18:46 UTC, prashant-tholia commented on packages/common/src/i18n/format_date.ts
> +    // 2010 => 2010)
Hi @sonukapoor, I implemented this similar to the year format 'y' implementation. For 'y' format, year trimming is applied only for the 2-digit 'yy' case, while padding is added to all formats except for the single-digit 'y' case. ([API Reference])(https://angular.io/api/common/DatePipe)

Similarly, here too, while 2010 would be formatted to '10' with 'yy' format, it would not be trimmed and return '2010' for other formats.

2020-09-15 02:00 UTC, AndrewKushnir commented on packages/common/src/i18n/format_date.ts
> +  }
It looks like this is the main delta between this function and the `getThursdayThisWeek` function defined above. I'm wondering if we could just merge functions into one and add a function argument to see if we need to invoke extra logic:

```
function getThisISOWeekThursday(datetime: Date, useISOFormat = false) {
  const day = datetime.getDay();
  let daysToThursday = THURSDAY - day;
  /* ... move the comment here ... */
  if (day === SUNDAY && useISOFormat) {
    daysToThursday -= 7;
  }
  return new Date(datetime.getFullYear(), datetime.getMonth(), datetime.getDate() + daysToThursday);
}
```

That'd be a bit more compact, i.e. we'll add less code (since this code is not tree-shakable).

2020-09-15 03:29 UTC, prashant-tholia commented on packages/common/src/i18n/format_date.ts
> +  }
Yes, I totally agree, @AndrewKushnir . I'll update the code right away.

2020-09-15 10:08 UTC, sonukapoor commented
@prashant-tholia Can you also fix the [linting](https://circleci.com/gh/angular/angular/808053?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) issues? The file is not formatted. You can format the file using:

```
yarn ng-dev format files packages/common/src/i18n/format_date.ts
```

2020-09-15 13:09 UTC, prashanttholia commented
Done.

2020-09-15 13:58 UTC, petebacondarwin approved these changes
Great work thanks @prashanttholia.

Can you squash all the commits into one?

Normally one does add additional commits to update after a review but they need to be "fixup" commits, which our merge script will automatically squash. But since your commits are not fixups then you might as well do the squashing too.

2020-09-15 13:58 UTC, petebacondarwin commented on packages/common/src/i18n/format_date.ts
> + * Gets this week Thursday date. By default, it considers a week to be from Sunday to Saturday.
```suggestion
 * Gets the date of Thursday this week. By default, it considers a week to be from Sunday to Saturday.
```

2020-09-15 15:48 UTC, prashanttholia commented
Thanks a lot, @petebacondarwin! I have a query - At present, for 'r' formats, I have passed useISOFormat parameter as true to the getThursdayThisWeek function, making it an ISO 8601 implementation. Wheras, the implementation for the formats 'w' & 'W' is a non-ISO one. This could give results which are in themselves inconsistent for format patterns such as 'rrrr ww'. I request you to let me know whether I should change implementation for 'r' format to use non-ISO as well?

I also wanted to mention that I had worked on ISO implementation of 'w' & 'W' formats as well. So, in case you choose to make the implementation consistent using ISO 8601, I can commit it right away.

2020-09-15 15:51 UTC, AndrewKushnir approved these changes
Thanks for additional changes @prashanttholia 👍 I've just left a minor comment on removing `()` around days to Thu calculation expression.

2020-09-15 15:51 UTC, AndrewKushnir commented on packages/common/src/i18n/format_date.ts
> +  let daysToThursday = (THURSDAY - day);
```suggestion
  let daysToThursday = THURSDAY - day;
```

2020-09-17 17:18 UTC, petebacondarwin commented on packages/common/src/i18n/format_date.ts
> +function getThursdayThisWeek(datetime: Date, useISOFormat = false): Date {
Since it is not that clear to me, at a glance, what the `useISOFormat` does, I would consider renaming it... WDYT @AndrewKushnir ?

```suggestion
function getThursdayThisWeek(datetime: Date, weekStartMonday = false): Date {
```

or 

```suggestion
function getThursdayThisWeek(datetime: Date, useISOWeekStart = false): Date {
```

2020-09-17 17:21 UTC, petebacondarwin commented
> Thanks a lot, @petebacondarwin! I have a query - At present, for 'r' formats, I have passed useISOFormat parameter as true to the getThursdayThisWeek function, making it an ISO 8601 implementation. Wheras, the implementation for the formats 'w' & 'W' is a non-ISO one. This could give results which are in themselves inconsistent for format patterns such as 'rrrr ww'. I request you to let me know whether I should change implementation for 'r' format to use non-ISO as well?
> 
> I also wanted to mention that I had worked on ISO implementation of 'w' & 'W' formats as well. So, in case you choose to make the implementation consistent using ISO 8601, I can commit it right away.

Hmm, If I understand correctly the difference is that our current algorithm assumes that the week starts on Sunday, whereas the ISO spec (?) has it starting on Monday. Correct?

I think that perhaps what we should have is a backward compatible consistent mode (i.e. `rrrr` and `ww` uses the Thursday with week starting on Sunday). And then we could have an "ISO" mode, that flips all these to the week starting on Monday. Not sure how best that would be exposed.

But in the meantime, I "think" that for consistency we should start with the backward compatible mode for both `r` and `w`.
WDYT @AndrewKushnir ?

2020-09-18 00:25 UTC, AndrewKushnir commented
> I think that perhaps what we should have is a backward compatible consistent mode (i.e. rrrr and ww uses the Thursday with week starting on Sunday). And then we could have an "ISO" mode, that flips all these to the week starting on Monday. Not sure how best that would be exposed.

I think we may consider introducing a new token (similar to `LOCALE_ID`) that can control whether ISO format should be used. It can be consumed by i18n date pipe and transform the value based on that.

> But in the meantime, I "think" that for consistency we should start with the backward compatible mode for both r and w.

Agree, I think we should have the version that'd be consistent with the current implementation and introduce ISO-based transformation later as a new feature.

2020-09-18 05:13 UTC, prashanttholia commented on packages/common/src/i18n/format_date.ts
> +function getThursdayThisWeek(datetime: Date, useISOFormat = false): Date {
Updated.

2020-09-18 05:17 UTC, prashanttholia commented
@petebacondarwin @AndrewKushnir , updated to make it backward compatible and consistent.

2020-09-18 07:16 UTC, prashanttholia commented
Hi, I'm not able to figure out what is causing the check failure. I request for help.

2020-09-18 07:23 UTC, petebacondarwin commented
It looks like a couple of ngcc workers crashed, which then probably caused the later failure. I've restarted the job.

2020-09-18 08:04 UTC, prashanttholia commented
Thanks.

2020-09-19 00:08 UTC, AndrewKushnir requested changes

2020-09-19 00:08 UTC, AndrewKushnir commented on packages/common/src/i18n/format_date.ts
> +function getThursdayThisWeek(datetime: Date, useISOWeekStart = false): Date {
It looks like the changes in this function are no longer used, so we can revert back to the original version of the `getThursdayThisWeek` function.

2020-09-19 14:34 UTC, prashanttholia commented on packages/common/src/i18n/format_date.ts
> +function getThursdayThisWeek(datetime: Date, useISOWeekStart = false): Date {
Done.

2020-09-19 16:49 UTC, AndrewKushnir commented on packages/common/src/i18n/format_date.ts
> +function getThursdayThisWeek(datetime: Date, useISOWeekStart = false): Date {
Thanks for updating the code 👍

2020-09-19 16:51 UTC, AndrewKushnir approved these changes
Thanks for the updates @prashanttholia 👍 

The changes looks good, I've also started tests in [Google's codebase](http://test/OCL:332629457:BASE:332629467:1600534274260:5d0c9a3f) and will keep this thread updated.

2020-09-19 17:33 UTC, prashanttholia commented
Thanks, @AndrewKushnir. I'll look forward to the updates.

2020-09-21 16:09 UTC, AndrewKushnir commented
Hi @prashanttholia, the tests in Google's codebase went well and this PR has the necessary approvals now, so I'm adding this PR to the merge queue. Thanks for contributing to Angular framework!

2020-09-21 17:39 UTC, prashanttholia commented
Thanks @AndrewKushnir! I'm glad to know that the PR is being added to the merge queue. Thanks @petebacondarwin for the opportunity to contribute!

2020-09-21 19:24 UTC, closed without merging