perf(ngcc): performance improvements
angular/angular pull request #38840
Opened 2020-09-14 12:24 UTC by JoostK

See individual commits.

2020-09-14 15:22 UTC, nutza249949 commented
@JoostK 

_Sent from my Vivo 1901 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2020-09-14 15:56 UTC, JoostK commented
I ran this on ngcc-validation on a 8-core/16-threads CPU:

Using 4 workers:
```bash
time ./node_modules/.bin/ngcc --create-ivy-entry-points --error-on-failed-entry-point --first-only --properties es2015 browser module main --no-tsconfig
315.90s user / 29.88s system / 454% cpu / 1:16.06 total
```

Using 8 workers:
```bash
time ./node_modules/.bin/ngcc --create-ivy-entry-points --error-on-failed-entry-point --first-only --properties es2015 browser module main --no-tsconfig
423.24s user / 41.97s system / 830% cpu / 56.000 total
```

Here, the 8 worker scenario is slightly faster, which is somewhat expected for ngcc-validation as it has lots of independent packages, so it is able to feed all workers with work very effectively. The situation with 4 workers is still significantly faster than master currently is using 8 workers:

```bash
time ./node_modules/.bin/ngcc --create-ivy-entry-points --error-on-failed-entry-point --first-only --properties es2015 browser module main --no-tsconfig
1083.92s user / 107.51s system / 913% cpu / 2:10.39 total
```

Additionally, quad-core CPUs with hyper-threading report 8 available CPUs, so we'd completely drown the CPU in 7 ngcc workers. So I think that reducing the number of workers to a maximum of 4 is the right balance.

2020-09-14 16:24 UTC, JoostK commented on packages/compiler-cli/ngcc/src/execution/create_compile_function.ts
> +    const compilationCache = new TransformCache(fileSystem);
Note to self: rename this variable name. I'm not sold on `TransformCache` for the class name anyway, so suggestions welcome.

2020-09-14 16:25 UTC, JoostK commented on packages/compiler-cli/ngcc/src/packages/transform_cache.ts
> +    if (/^lib\..+\.d\.ts$/.test(basename(fileName))) {
Maybe this should be more specific to targeting files within `node_modules/typescript/lib/`.

2020-09-14 20:12 UTC, JoostK commented
Here's the figures for a bare CLI app with `@angular/material` added, such that there is a somewhat representative number of entry-points to process:

```bash
npx @angular/cli new ngcc-perf
cd ngcc-perf
yarn ng add @angular/material
```

On master, sync:
```bash
time ./node_modules/.bin/ngcc --properties es2015 module main --first-only --create-ivy-entry-points --no-async
101.68s user / 6.31s system / 155% cpu / 1:09.60 total
```

This PR, sync:
```bash
time ./node_modules/.bin/ngcc --properties es2015 module main --first-only --create-ivy-entry-points --no-async
24.48s user / 1.58s system / 164% cpu / 15.845 total
```

On master, async (8 workers):
```bash
time ./node_modules/.bin/ngcc --properties es2015 module main --first-only --create-ivy-entry-points
170.34s user / 12.49s system / 888% cpu / 20.581 total
```

This PR, async (4 workers):
```bash
time ./node_modules/.bin/ngcc --properties es2015 module main --first-only --create-ivy-entry-points
40.32s user / 3.23s system / 463% cpu / 9.407 total
```

2020-09-15 08:25 UTC, petebacondarwin requested changes
Nice work @JoostK - I don't see any issues with the logic.

Regarding structure, I would extract the module resolution cache from the `TransformCache` unless I am missing something.

Regarding naming, I would consider `SharedFileCache` and `EntryPointFileCache` - which only work if they are not responsible for the module resolution cache.

2020-09-15 08:25 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/transform_cache.ts
> +  for (const pattern of segments.slice().reverse()) {
To avoid having to create and reverse the array every time, why not just use a traditional for loop?

```
for(let i = segments.length-1; i >= 0; --i) {
  const pattern = segments[i];
  ...
}
```

2020-09-15 08:25 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/packages/transform_cache.ts
> +  readonly moduleResolutionCache: ts.ModuleResolutionCache;
I don't really understand the point of including the `moduleResolutionCache` as part of the `TransformCache` nor the `EntryPointCache`. They seem entirely independent of each other. Neither relies upon or uses the other.

If it is just to avoid passing around 2 objects then I would say it dilutes and confuses the meaning of the `TransformCache`.

2020-09-15 08:25 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/main.ts
> +      const workerCount = Math.min(4, os.cpus().length - 1);
Given that you are changing this, I wonder if we should take this opportunity to have an environment variable or similar to set the value on a project basis?

2020-09-15 08:31 UTC, JoostK commented on packages/compiler-cli/ngcc/src/packages/transform_cache.ts
> +  private getDefaultLibFileCached(absPath: AbsoluteFsPath): ts.SourceFile|undefined {
I can agree with renaming the method names, but I prefer to keep the logic around determining which files to consider very simple. IMHO the cache is the one to be smart about what it considers cachable, not the creator of the cache.

2020-09-15 08:31 UTC, JoostK commented on packages/compiler-cli/ngcc/src/packages/transform_cache.ts
> +  for (const pattern of segments.slice().reverse()) {
Haha, I never thought about doing it like this. Yeah, that's definitely better :-)

2020-09-15 08:34 UTC, petebacondarwin commented
Oh one more thing regarding the synchronous CLI integration. What about adding the `TransformCache` to the API that the CLI uses to invoke ngcc. This would allow the CLI to be able to provide a cache where it can control invalidating files, since it would be able to know about that. Then we could share these cached files between synchronous invocations of ngcc in the CLI.

2020-09-15 08:38 UTC, JoostK commented on packages/compiler-cli/ngcc/src/packages/transform_cache.ts
> +  readonly moduleResolutionCache: ts.ModuleResolutionCache;
So my idea was to encapsulate the cacheable entities in a class that correspond with the lifecycle the cache is valid for. Things in `TransformCache` are deemed valid across a single ngcc invocation, and the module resolution cache is one of those things that belongs in this lifecycle.

What I like in the current setup is that it's clear from looking at `EntryPointCache` that it reuses the module resolution cache that is available for all entry-points. Having an individual MRC passed around defeats this insight.

I do think that `TransformCache` is an awful name, though. It was `CompilationCache` at first, but that's not much better/worse. This morning I figured just naming it `SharedCache` might be better, although it's still unclear what "Shared" means in that sense. I can see how you're suggesting it to be named `SharedFileCache`, but that defeats my design goal of representing the two layers of caching (for all entry-points (`TransformCache`) vs a single entry-point (`EntryPointCache`)).

2020-09-15 08:43 UTC, JoostK commented
> Oh one more thing regarding the synchronous CLI integration. What about adding the `TransformCache` to the API that the CLI uses to invoke ngcc. This would allow the CLI to be able to provide a cache where it can control invalidating files, since it would be able to know about that. Then we could share these cached files between synchronous invocations of ngcc in the CLI.

I would rather not at this point. The configuration is already complex and allowing for external invalidation of caches introduces yet more public API and the possibility for bugs of stale caches. The changes in this PR are purely internal, which gives us infinite freedom in what we deem safe to cache and for how long.

2020-09-15 12:43 UTC, petebacondarwin approved these changes
LGTM

2020-09-15 13:41 UTC, d3lm commented
Very cool! Nice job @JoostK 👍 Love this ❤️ 

👏 👏 👏

2020-09-15 16:21 UTC, gkalpak approved these changes
Fantastic work! 💯 🚀 👨‍🎤

2020-09-15 16:21 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/ngcc_options.ts
> +    return Math.max(1, Math.min(4, os.cpus().length - 1));
Nit: FWIW, I would find it more intuitive to return 0 when there are not enough CPUs for workers (i.e. when `os.cpus().length < 2`).

2020-09-15 16:28 UTC, JoostK commented on packages/compiler-cli/ngcc/src/ngcc_options.ts
> +    return Math.max(1, Math.min(4, os.cpus().length - 1));
That's an interesting point, especially when considering how to configure `NGCC_MAX_WORKERS`. Currently I require that to be at least 1, but that doesn't mean that it'll actually spawn a single worker, as it's smart enough to run it in the same process. So from that perspective, returning 0 here if there's too few CPUs would be inconsistent. I feel it would be quite awkward to allow `NGCC_MAX_WORKERS=0` which would operate identically to `NGCC_MAX_WORKERS=1`.

2020-09-15 16:34 UTC, JoostK commented on packages/compiler-cli/ngcc/src/packages/source_file_cache.ts
> + * @param path The path for which to determine whether it represented to provided segments.
Rephrased slightly.

2020-09-15 18:23 UTC, closed without merging

2020-09-15 18:45 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/ngcc_options.ts
> +    return Math.max(1, Math.min(4, os.cpus().length - 1));
I don't necessarily agree, but I don't feel strongly about this at all (so it works for me as is) 😅