fix(compiler): source span for microsyntax bindings should be the bin…
angular/angular pull request #38855
Opened 2020-09-15 16:10 UTC by atscott

…ding span

In a microsyntax expression, the source spans of the individual bindings should
to be distinguished from each other and only contain the relavent parts.

```
<div *ngFor="let item of items; trackBy: trackByFn">
</div>
```

In this example, the current source span for `ngForTrackBy` and
`ngForOf` are both the entire span `*ngFor="let item of items; trackBy: trackByFn"`.
With this change, the source span for `ngForOf` would be `of items; `
and the source span for `ngForTrackBy` would be `trackBy: trackByFn`.

2020-09-15 16:17 UTC, kyliau requested changes
Please add a test for `<div *ngFor="let item of items$ | async as items">`
I'm a little concerned about this case.
The source span for `items` should be
```
of items$ | async as items
^^value              ^^^^^name
```

2020-09-15 16:17 UTC, kyliau commented on packages/compiler/test/render3/r3_ast_spans_spec.ts
>        expectFromHtml('<div *ngFor="item of items"></div>').toEqual([
This example is actually "wrong" - not technically wrong, but it's not how `ngFor` is typically used because `let` is missing. Could you please update both test cases?

2020-09-15 16:20 UTC, atscott commented on packages/compiler/test/render3/r3_ast_spans_spec.ts
>        expectFromHtml('<div *ngFor="item of items"></div>').toEqual([
The first one is _intentionally_ "wrong" (based on the comment) to test that this still works. I'll update the second case though!

2020-09-15 16:34 UTC, kyliau commented on packages/compiler/test/render3/r3_ast_spans_spec.ts
>        expectFromHtml('<div *ngFor="item of items"></div>').toEqual([
haha, I was the person who added the comment! No wonder it looked familiar.

2020-09-17 17:28 UTC, atscott commented
Closing. Going in another direction: adding `keySpan` to bindings

2020-09-17 17:28 UTC, closed without merging