docs(docs-infra): widen scrollbar for accessibility
angular/angular pull request #38852
Opened 2020-09-15 13:03 UTC by kapunahelewong

This commit widens the webkit scroll bar. This makes it easier
to grab the scroll bar using assistive technology and devices,
and provides a wider target for those who have dexterity issues.
The width is now a minimum of 1rem, which is scalable so if the
user needs to zoom content for visibility, the scroll bar
width zooms with it.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:

UI/UX/accessibility improvement.

## What is the current behavior?

Currently, the scroll bar is narrow which makes it difficult to grab with assistive devices or if the user has dexterity issues. It is also set in pixels currently which does not scale when zooming.

Issue Number: N/A

## What is the new behavior?

This commit widens the webkit scroll bar. This makes it easier
to grab the scroll bar using assistive technology and devices,
and provides a wider target for those who have dexterity issues.
The width is now a minimum of 1rem, which is scalable so if the
user needs to zoom content for visibility, the scroll bar
width zooms with it.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-09-15 13:23 UTC, mary-poppins commented
You can preview 679976a at https://pr38852-679976a.ngbuilds.io/.

2020-09-15 14:26 UTC, gkalpak commented on aio/src/styles/2-modules/_scrollbar.scss
>  body::-webkit-scrollbar, mat-sidenav.sidenav::-webkit-scrollbar, .mat-sidenav-content::-webkit-scrollbar {
Not directly related to this PR, but the `mat-sidenav.sidenav::...` and `.mat-sidenav-content::...` selectors are no longer relevant. (In fact, I am seeing at least three different scrollbar styles: one one the main content, one in the sidenav and one in the TOC.)

Maybe you want to take care of that while you're at it (in a separate PR maybe).

2020-09-15 14:26 UTC, gkalpak commented on aio/src/styles/2-modules/_scrollbar.scss
> +  min-width: 1rem;
Why `min-width`? Wouldn't `width` work too?

2020-09-15 14:27 UTC, gkalpak commented
BTW, the commit message type should be `fix` (not `docs`) 🙏

2020-09-15 18:26 UTC, kapunahelewong commented on aio/src/styles/2-modules/_scrollbar.scss
> +  min-width: 1rem;
Good question - I had to test it because I did it by habit! `width: 1rem;` gets very tiny on zoom out, where min-width maintains a target (like the default scroll bar).

2020-09-15 18:30 UTC, kapunahelewong commented on aio/src/styles/2-modules/_scrollbar.scss
>  body::-webkit-scrollbar, mat-sidenav.sidenav::-webkit-scrollbar, .mat-sidenav-content::-webkit-scrollbar {
Sure, easy enough to do here. Now it's:

```
body::-webkit-scrollbar {
  height: 6px;
  min-width: 1rem;
}
```

Is that what you meant?

2020-09-15 18:40 UTC, mary-poppins commented
You can preview 8439764 at https://pr38852-8439764.ngbuilds.io/.

2020-09-15 18:46 UTC, gkalpak commented on aio/src/styles/2-modules/_scrollbar.scss
>  body::-webkit-scrollbar, mat-sidenav.sidenav::-webkit-scrollbar, .mat-sidenav-content::-webkit-scrollbar {
That would remove the obsolete selectors (which don't do anything).
Then you could update the styling of the other scrollbars (for sidenav and TOC).

2020-09-16 18:58 UTC, kapunahelewong commented on aio/src/styles/2-modules/_scrollbar.scss
>  body::-webkit-scrollbar, mat-sidenav.sidenav::-webkit-scrollbar, .mat-sidenav-content::-webkit-scrollbar {
OK, I have added that same width to the TOC, but the side NAV doesn't look like it's actually inheriting any of the styles anyway (and the default is usable because the target is bigger than our styles). If we're going to go further with scrollbar edits, another PR might be the way to go, like you mentioned earlier. What do you think? Is what I have ok?

2020-09-16 19:09 UTC, mary-poppins commented
You can preview 2191aef at https://pr38852-2191aef.ngbuilds.io/.

2020-09-16 22:17 UTC, sjtrimble approved these changes
This is super! 👍

2020-09-17 13:41 UTC, gkalpak requested changes

2020-09-17 13:43 UTC, gkalpak commented on aio/src/styles/2-modules/_scrollbar.scss
>  body::-webkit-scrollbar, mat-sidenav.sidenav::-webkit-scrollbar, .mat-sidenav-content::-webkit-scrollbar {
I left a comment on what changes need to be made to fix the sidenav too: https://github.com/angular/angular/pull/38852#discussion_r490156122

I am fine with fixing the sidenav in a different PR.

2020-09-17 18:17 UTC, mary-poppins commented
You can preview 6561d7e at https://pr38852-6561d7e.ngbuilds.io/.

2020-09-18 19:13 UTC, aikidave approved these changes
This looks great. Improves accessibility **and** reduces code. Awesome!

@gkalpak, what do we need to do to move this forward? It looks like @kapunahelewong has already spent quite a bit of time on this issue. Thanks!

2020-09-18 23:09 UTC, sjtrimble commented on aio/src/styles/2-modules/_scrollbar.scss
> +  min-width: 1rem;
I think having it be consistent makes sense.

2020-09-19 14:30 UTC, gkalpak approved these changes

2020-09-21 19:22 UTC, closed without merging