docs: deprecate displaying data in views topic
angular/angular pull request #38885
Opened 2020-09-17 16:52 UTC by aikidave

The Displaying Data in Views topic is actually a small tutorial
that describes Angular features such as interpolation and
structural directives. These content is already covered in
our getting started tutorial and in Tour of Heroes.

This change adds a deprecation notice to the Displaying Data in
Views topic and adds redirects to the Template Syntax section
of the Getting Started tutorial.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Currently, the topic, Displaying Data in Views, is really just a tutorial that covers interpolation and structural directives. This content is already covered in two other tutorials.

Issue Number: N/A

## What is the new behavior?
Add a note to the topic to indicate that it's deprecated, and added redirects.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-09-17 17:06 UTC, sonukapoor approved these changes

2020-09-17 17:15 UTC, mary-poppins commented
You can preview a91f299 at https://pr38885-a91f299.ngbuilds.io/.

2020-09-17 19:40 UTC, IgorMinar approved these changes
LGTM!

2020-09-17 19:41 UTC, IgorMinar commented on aio/firebase.json
> +      {"type": 301, "source": "/guide/displaying-data", "destination": "/start#template-syntax"}
```suggestion
      {"type": 301, "source": "/guide/displaying-data", "destination": "/start#template-syntax"},
```

2020-09-17 20:04 UTC, mary-poppins commented
You can preview b20d521 at https://pr38885-b20d521.ngbuilds.io/.

2020-09-19 16:20 UTC, gkalpak requested changes
This PR seems to be doing two different things:
1. It deprecates the `displaying-data.md` guide (adding deprecation notice, removing from sidenav).
2. It updates the hosting config to redirect its URL to a different one (thus making it inaccessible).

Due to the second change the users won't be able to land on the deprecated guide so there is little point in keeping it around (plus it causes tests to fail :grin:). So:
- If you want to deprecate the content, but still allow users to access it, then you need to remove the changes related to redirects.
- If you want to remove the guide and send users to the new URL instead, then you should remove the `displaying-data.md` file altogether.

2020-09-19 16:20 UTC, gkalpak commented on aio/tests/deployment/shared/URLS_TO_REDIRECT.txt
> +/guide/displaying-data  /start#template-syntax
The two values must be separated by one `\t` (tab) character, because we [split each line by `\t`][1]. This is what is causing one of the CI failures.

[1]: https://github.com/angular/angular/blob/a91f0f6b82f340cfde5a01bc328d2723dc4248f0/aio/tests/deployment/shared/helpers.ts#L44

2020-09-21 20:35 UTC, aikidave commented on aio/tests/deployment/shared/URLS_TO_REDIRECT.txt
> +/guide/displaying-data  /start#template-syntax
Fixed. Thank you!

Is there anything we can do to make redirects easier in AIO? Having to touch 3(?) files just to redirect a single topic, and having to be very careful about how you do so, its really cumbersome. Any thoughts?

2020-09-21 20:48 UTC, mary-poppins commented
You can preview 94af263 at https://pr38885-94af263.ngbuilds.io/.

2020-09-22 18:26 UTC, mary-poppins commented
You can preview 14fdd50 at https://pr38885-14fdd50.ngbuilds.io/.

2020-09-23 04:57 UTC, JiaLiPassion commented on aio/content/guide/zone.md
> +The `AppComponent` is the bootstrap component. This component has the properties `title` and `myHero`, which the application renders in the HTML.
Since we don't have the `displaying-data` chapter, so the `AppComponent` and the `title/myHero` are not available here, maybe we should just remove this line.

2020-09-23 16:02 UTC, gkalpak approved these changes
A couple of minor comments (plus what @JiaLiPassion said above). Otherwise lgtm :+1:

2020-09-23 16:02 UTC, gkalpak commented on aio/content/guide/architecture-next-steps.md
> +* The Components and Templates sections of this guide explain how to connect the application data in your [components](guide/glossary#component) to your page-display [templates](guide/glossary#templa
This seems confusing. Where are the Components and Templates sections? I don't see any such sections in this guide.

Even more confusingly, some sections below mention [**Components and Templates** guide](https://github.com/angular/angular/blame/14fdd50818a82f93d8f5fd2a9e0b566017054ac8/aio/content/guide/architecture-next-steps.md#L24) and [**Development Workflow** section](https://github.com/angular/angular/blame/14fdd50818a82f93d8f5fd2a9e0b566017054ac8/aio/content/guide/architecture-next-steps.md#L55) without linking to them, so I don't know what these refer to either 🤷‍♂️

This doesn't have to block this PR, since the situation was already quite messy before this PR, but it might be a good idea to improve these references in a follow-up PR.

2020-09-24 16:08 UTC, aikidave commented on aio/content/guide/architecture-next-steps.md
> +* The Components and Templates sections of this guide explain how to connect the application data in your [components](guide/glossary#component) to your page-display [templates](guide/glossary#templa
Yes, this page is basically just a bunch of links. We may want to revisit the page's usefulness later. For now, I've removed some of the introductory statements, which is adding to the confusion that you mentioned.

2020-09-24 16:17 UTC, JiaLiPassion approved these changes
LGTM, thanks.

2020-09-24 16:22 UTC, mary-poppins commented
You can preview 451b782 at https://pr38885-451b782.ngbuilds.io/.

2020-09-24 17:16 UTC, gkalpak requested changes

2020-09-24 17:16 UTC, gkalpak commented on aio/content/guide/architecture-next-steps.md
> -For some platforms and applications, you might also want to use the PWA (Progressive Web App) model to improve the user experience.
OOC, why remove this?

2020-09-24 17:16 UTC, gkalpak commented on aio/content/guide/architecture-next-steps.md
> -
IMO it is important to keep these. Especially the link to `guide/template-syntax`. If you decide to get rid of these paragraphs, at least add a bullet-point mentioning the `Template syntax` guide.

You could also link the `collect input from users` part to `guide/user-input`.

2020-09-24 17:16 UTC, gkalpak commented on aio/content/guide/architecture-next-steps.md
> -* The [Components and templates](guide/displaying-data) guide explains how to connect the application data in your [components](guide/glossary#component) to your page-display [templates](guide/glossa
IMO, we should keep this paragraph (and just remove/fix the now broken link). Not mentioning `components` and `templates` (which are two of the main building blocks of Angular apps) in this `Application architecture` section doesn't make sense.

2020-09-24 17:16 UTC, gkalpak commented on aio/content/guide/zone.md
> -1. Component initialization. For example, when bootstrapping an Angular application, Angular loads the bootstrap component and triggers the [ApplicationRef.tick()](api/core/ApplicationRef#tick) to ca
Thie first sentence contains an important bit of info (because it applies to every application basically), so I would recommend keeping it. It's the rest (starting as "Just as in...") that we should get rid of, since the `displaying-data` guide has been removed.

2020-09-24 19:04 UTC, mary-poppins commented
You can preview 00f6788 at https://pr38885-00f6788.ngbuilds.io/.

2020-09-25 09:59 UTC, gkalpak approved these changes
LGTM :+1:

Reviewed-for: global-docs-approvers

2020-09-29 17:25 UTC, kapunahelewong approved these changes
LGTM!

Reviewed-for: global-docs-approvers

2020-10-15 16:29 UTC, mary-poppins commented
You can preview eb143a0 at https://pr38885-eb143a0.ngbuilds.io/.

2020-10-15 21:05 UTC, closed without merging