feat(compiler): make `keySpan` available for `BoundAttributes`
angular/angular pull request #38898
Opened 2020-09-17 23:03 UTC by atscott

Though we currently have the knowledge of where the `key` for an
attribute binding appears during parsing, we do not propagate this
information to the output AST. This means that once we produce the
template AST, we have no way of mapping a template position to the key
span alone. The best we can currently do is map back to the
`sourceSpan`. This presents problems downstream, specifically for the
language service, where we cannot provide correct information about a
position in a template because the AST is not granular enough.

2020-09-17 23:15 UTC, mary-poppins commented
You can preview 1ce7375 at https://pr38898-1ce7375.ngbuilds.io/.

2020-09-18 06:38 UTC, petebacondarwin commented on packages/compiler/test/render3/r3_ast_spans_spec.ts
> +        ['BoundAttribute', '5:31', '22:24', '25:30'],  // *ngFor="let item of items" -> of -> items
Is `of` really the correct key value span for this binding?
I would have expected it to be `*ngFor`.

2020-09-18 06:41 UTC, petebacondarwin commented on packages/compiler/src/expression_parser/ast.ts
> +      public valueSpan?: ParseSourceSpan) {
I assume you are 100% sure you have checked all places that call this and for the similar classes below? Since the type checker will not fail if you have passed a `valueSpan` in the slot for the new `keySpan`.

2020-09-18 14:52 UTC, atscott commented on packages/compiler/test/render3/r3_ast_spans_spec.ts
> +        ['BoundAttribute', '5:31', '22:24', '25:30'],  // *ngFor="let item of items" -> of -> items
`of` is technically the correct `keySpan` for the microsyntax. The de-sugared form of this is `ngFor let-item [ngForOf]="items"` -- the `of items` parts is the section in the microsyntax that maps to the `ngForOf`. This actually illustrates one of the problems that was difficult to solve when trying to go map backwards from the template AST to the template for the Language Service. If given the location for `of`, there wasn't anywhere in the AST that had that span specifically.

2020-09-18 18:00 UTC, kyliau requested changes

2020-09-18 18:00 UTC, kyliau commented on packages/compiler/src/expression_parser/ast.ts
> +      public sourceSpan: ParseSourceSpan, readonly keySpan: ParseSourceSpan|undefined,
+1 for making it readonly!

Please document when `keySpan` is undefined and when it's not.

2020-09-18 18:00 UTC, kyliau commented on packages/compiler/src/template_parser/binding_parser.ts
> +      targetProps: ParsedProperty[], keySpan?: ParseSourceSpan) {
Please add a doc here to explain `keySpan` is not passed in VE AST implementation.

2020-09-18 18:00 UTC, kyliau commented on packages/compiler/src/template_parser/binding_parser.ts
> +      targetMatchableAttrs: string[][], targetProps: ParsedProperty[], keySpan?: ParseSourceSpan) {
same as comment above, please add doc

2020-09-18 18:00 UTC, kyliau commented on packages/compiler/test/render3/r3_ast_spans_spec.ts
> +        ['BoundAttribute', '5:19', '6:14', '17:18'],
Please add a trailing comment to denote what sourceSpan, keySpan, and valueSpan are, like what we've done for some of the newer tests.

2020-09-18 18:00 UTC, kyliau commented on packages/compiler/src/render3/r3_ast.ts
> +    if (prop.keySpan === undefined) {
If keySpan is undefined here, we should just throw an error, because it indicates a bug in our implementation, not user code.

On a separate note, doesn't this mean we'll return null for `BoundElementProperty` for host binding?
I think the solution we discussed is to use sourceSpan as the keySpan for this edge case.
If possible, please look into how we could add a test for this scenario.

2020-09-18 18:00 UTC, kyliau commented on packages/compiler/src/template_parser/binding_parser.ts
> +      targetProps: ParsedProperty[], keySpan?: ParseSourceSpan): boolean {
ditto

2020-09-18 18:00 UTC, kyliau commented on packages/compiler/src/render3/r3_template_transform.ts
> +      const normalizationAdjustment = attribute.name.length - name.length;
Please add comment to explain that this is to account for `data-`.

2020-09-18 18:00 UTC, kyliau commented on packages/compiler/src/render3/r3_template_transform.ts
> +      const keySpanEnd = keySpanStart.moveBy(identifier.length + normalizationAdjustment);
we don't need normalization adjustment for keySpanEnd since it's relative to keySpanStart, no?
If that's the case, I wonder why our tests didn't catch this...

2020-09-18 18:00 UTC, kyliau commented on packages/compiler/src/render3/r3_template_transform.ts
> +          this.reportError(
We shouldn't need this, since reportError() is for errors in user code.

2020-09-18 18:00 UTC, kyliau commented on packages/compiler/src/render3/r3_template_transform.ts
> +        const keySpan = createKeySpan(srcSpan, bindParts[KW_BIND_IDX], bindParts[IDENT_KW_IDX]);
Nit: In the else cases below, `bindParts[IDENT_KW_IDX]` is extracted into a variable named `identifier`. We should do the same here.

2020-09-18 19:52 UTC, atscott commented on packages/compiler/test/render3/r3_ast_spans_spec.ts
> +        ['BoundAttribute', '5:19', '6:14', '17:18'],
Resolving as superseded by https://github.com/angular/angular/pull/38902

2020-09-18 19:52 UTC, atscott commented on packages/compiler/src/render3/r3_template_transform.ts
> +      const keySpanEnd = keySpanStart.moveBy(identifier.length + normalizationAdjustment);
Yikes, good catch! I added tests for all the data- binding types

2020-09-18 20:54 UTC, atscott commented on packages/compiler/src/render3/r3_ast.ts
> +    if (prop.keySpan === undefined) {
Yes, this would return null (actually error now after the change) for host bindings. However, `BoundElementProperty`s of host bindings aren't converted to a `BoundAttribute`s but rather converted to a host binding function here: https://github.com/angular/angular/blob/88d7bb838607622c48488a828286c54fe091d8f0/packages/compiler/src/render3/view/compiler.ts#L546. I've added a lengthy comment to `binding_parser` about using `sourceSpan` as the `keySpan` for host bindings.

2020-09-21 16:56 UTC, kyliau approved these changes
LGTM, this looks great!

2020-09-22 14:52 UTC, alxhub approved these changes
Wow, this was definitely more work than I expected.

Consider making this a `refactor()` commit as it's not a user-facing feature and should not appear in the CHANGELOG.

2020-09-22 22:04 UTC, closed without merging