feat(zone.js): monkey patches queueMicrotask()
angular/angular pull request #38904
Opened 2020-09-19 05:14 UTC by JiaLiPassion

Close #38863

Monkey patches `queueMicrotask()` API, so the callback runs in the zone
when scheduled, and also the task is run as `microTask`.

```
Zone.current.fork({
  name: 'queueMicrotask',
  onScheduleTask: (delegate: ZoneDelegate, curr: Zone, target: Zone, task: Task) => {
    logs.push(task.type);
    logs.push(task.source);
    return delegate.scheduleTask(target, task);
  }
}).run(() => {
    queueMicrotask(() => {
      expect(logs).toEqual(['microTask', 'queueMicrotask']);
      expect(Zone.current.name).toEqual('queueMicrotask');
      done();
  });
});

```

2020-09-30 04:47 UTC, mhevery requested changes
LGTM, but please incorporate these changes.

2020-09-30 04:47 UTC, mhevery commented on packages/zone.js/lib/zone.configurations.api.ts
> +   * Disable the monkey patch of the browser `queueMicrotask()` API.
```suggestion
   * Disable the monkey patching of the browser's `queueMicrotask()` API.
```

2020-09-30 04:47 UTC, mhevery commented on packages/zone.js/lib/zone.configurations.api.ts
> +   * scheduled. And also the callback is running as `microTask` like `Promise.prototype.then()`.
```suggestion
   * By default, `zone.js` monkey patches the browser's `queueMicrotask()` API
   * to ensure that `queueMicrotask()` callback is invoked in the same zone as zone used to invoke 
   * `queueMicrotask()`.
```

2020-09-30 04:47 UTC, mhevery commented on packages/zone.js/lib/zone.configurations.api.ts
> +   *     // in the zone myZone'
```suggestion
   *     // Since `queueMicrotask()` was invoked in `myZone`, same zone is restored 
   *     // when 'queueMicrotask() callback is invoked, resulting in `myZone` being console logged.
```

2020-09-30 04:47 UTC, mhevery commented on packages/zone.js/lib/zone.configurations.api.ts
> +   * outputs 'queueMicrotask() callback is invoked in the zone <root>'.
```suggestion
   * If you set `__Zone_disable_queueMicrotask = true` before importing `zone.js`,
   * `zone.js` does not monkey patch the `queueMicrotask()` API and the above code
   * output will change to: 'queueMicrotask() callback is invoked in the zone <root>'.
```

2020-09-30 06:01 UTC, JiaLiPassion commented on packages/zone.js/lib/zone.configurations.api.ts
> +   * Disable the monkey patch of the browser `queueMicrotask()` API.
Got it, thanks.

2020-09-30 06:01 UTC, JiaLiPassion commented on packages/zone.js/lib/zone.configurations.api.ts
> +   * scheduled. And also the callback is running as `microTask` like `Promise.prototype.then()`.
Got it, thanks.

2020-09-30 06:01 UTC, JiaLiPassion commented on packages/zone.js/lib/zone.configurations.api.ts
> +   * outputs 'queueMicrotask() callback is invoked in the zone <root>'.
Got it, thanks.

2020-09-30 06:01 UTC, JiaLiPassion commented on packages/zone.js/lib/zone.configurations.api.ts
> +   *     // in the zone myZone'
Got it, thanks.

2020-09-30 07:50 UTC, alfaproject commented on packages/zone.js/test/browser/queue-microtask.spec.ts
> +fdescribe(
```suggestion
describe(
```

2020-09-30 08:40 UTC, JiaLiPassion commented on packages/zone.js/test/browser/queue-microtask.spec.ts
> +fdescribe(
Got it, thanks!

2020-09-30 16:14 UTC, mhevery commented on goldens/size-tracking/integration-payloads.json
> +        "polyfills-es2015": 36964
This is + 393 bytes. That seems quite a lot. What is going on?

2020-10-01 13:37 UTC, JiaLiPassion commented on goldens/size-tracking/integration-payloads.json
> +        "polyfills-es2015": 36964
I have checked the diff results, the `393 bytes` is not only this PR, but also from several PRs before.
https://github.com/angular/angular/pull/38836
https://github.com/angular/angular/pull/38476
https://github.com/angular/angular/issues/38795
https://github.com/angular/angular/issues/38361
https://github.com/angular/angular/issues/37333

And before this PR, the size increased but not over the limit, and this PR is the last straw.

2020-10-01 17:06 UTC, mhevery approved these changes

2020-10-01 17:06 UTC, mhevery commented on goldens/size-tracking/integration-payloads.json
> +        "polyfills-es2015": 36964
thanks

2020-10-01 17:10 UTC, AndrewKushnir approved these changes
LGTM (based on [the comment here](https://github.com/angular/angular/pull/38904/files#r498250282))

Reviewed-for: size-tracking

2020-10-01 20:02 UTC, atscott approved these changes
Reviewed-for: size-tracking

2020-10-19 16:13 UTC, mhevery commented
[presubmit](http://test/OCL:337868057:BASE:337868086:1603123991324:9aaaab4e)

2020-11-04 17:47 UTC, jelbourn commented
@JiaLiPassion is this a breaking change? If not it could be `target: minor`

2020-11-04 17:53 UTC, JiaLiPassion commented
@jelbourn , got it, updated, thanks.

2020-11-05 19:23 UTC, closed without merging