test(docs-infra): add unit tests for rxjs examples
angular/angular pull request #38905
Opened 2020-09-19 11:20 UTC by sonukapoor

This commit adds missing unit tests for all rxjs examples from the docs.

Closes #28017

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Documentation content changes

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2020-09-19 19:50 UTC, gkalpak requested changes
Thx, @sonukappor!

Awesome to see that these tests provide immediate value by finding broken examples (such as the `retry-on-error` one) :tada:

Please update the commit message to mention that this PR is targeting the `rx-library` example specifically.

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/error-handling.ts
> +export function docRegionApiData(console, ajax) {
I would prefer to keep the convention that these function are named after the PascalCased docregion name, prefixed with `docRegion`. For the unnamed, default docregions, I suggest we use a consistent name acriss all files. Something like `docRegionDefault()` or `docRegionUnnamed()`.

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/operators.2.ts
> +import { of } from 'rxjs';
I know this was like this before, but I think this should actually be part of the docregion.

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/operators.ts
> +import { of } from 'rxjs';
I know this was like this before, but I think this should actually be part of the docregion.

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.1.spec.ts
> +    const fetch = () => of({});
Let's use a property to make this more distinct:

```suggestion
    const fetch = () => of({foo: 42});
```

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.1.spec.ts
> +    expect(console.log).toHaveBeenCalledWith('Completed');
```suggestion
    expect(console.log.calls.allArgs()).toEqual([
      [{}],
      ['Completed'],
    ]);
```

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.2.spec.ts
> +  });
Let's keep this consistent with other recently added tests:

```suggestion
  beforeEach(() => jasmine.clock().install());
  afterEach(() => jasmine.clock().uninstall());
```

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.2.spec.ts
> +    jasmine.clock().tick(1001);
```suggestion
    jasmine.clock().tick(1000);
```

Also, to make sure it works as expected, let's add an assertion that there is nothing emitted after 999ms.

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.2.spec.ts
> +    expect(console.log).toHaveBeenCalledWith('It\'s been 0 seconds since subscribing!');
Let's verify at least one more emission:

```suggestion
    expect(console.log).toHaveBeenCalledWith('It\'s been 0 seconds since subscribing!');
    
    console.log.calls.reset();
    
    jasmine.clock().tick(999);
    expect(console.log).not.toHaveBeenCalled();
    
    jasmine.clock().tick(1);
    expect(console.log).toHaveBeenCalledWith('It\'s been 1 seconds since subscribing!');
```

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.2.ts
> +    console.log(`It's been ${n} seconds since subscribing!`));
This is actually wrong :smiley:

```suggestion
    console.log(`It's been ${n + } seconds since subscribing!`));
```

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.ts
>  apiData.subscribe(res => console.log(res.status, res.response));
No tests for this? 🤨

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.3.spec.ts
> +  it('should call unsubscribe when clientX and clientY are below < 40 ', () => {
Please add two tests: One that verifies it prints coorsidnates and one that verifies the unsubscription.

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.3.spec.ts
> +    expect(console.log).not.toHaveBeenCalled();
Let's also verify that `removeEventListener` was called (with appropriate arguments).

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/retry-on-error.ts
> +import { of } from 'rxjs';
I know this was like this before, but I think this should actually be part of the docregion.

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/retry-on-error.ts
> +    retry(3), // Retry up to 3 times before failing
This fix is independent from adding tests. Please move it to a separate commit.

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +  });
We should also verify that `ajax()` is called three times (perhaps by adding a `console.log()` call inside the fake ajax implementation.

2020-09-19 19:50 UTC, gkalpak commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +  it('should return an empty array', () => {
It should also be cool to have a test that shows that the outer observable completes with the correct value if the response comes successfully after a couple of attempts.

2020-09-20 01:16 UTC, sonukapoor commented on aio/content/examples/rx-library/src/error-handling.spec.ts
> +  it('should return an empty array', () => {
That makes a lot more sense.

2020-09-20 01:23 UTC, sonukapoor commented on aio/content/examples/rx-library/src/error-handling.ts
> +      console.log('Caught error.');
I have reverted this.

2020-09-20 02:11 UTC, sonukapoor commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +  });
Please correct me if I am wrong, but I don't think the `ajax()` method will be called three times. I think the underlying `retry` will `subscribe` to the returned observable from the `ajax` call and call `next` on it. I have tried to add `console.log()` into the `ajax()` method, and it gets only called once. I can add that if you like.

2020-09-20 02:14 UTC, sonukapoor commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +  it('should return an empty array', () => {
I am not entirely sure how this would be done here. Can you help?

2020-09-20 09:01 UTC, gkalpak commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +  });
Yes, you are right. Sorry for the confusion.
What I meant is verify that the observable returned by `ajax()` will be subscribed to 3 times.

You can do this with something like:

```ts
const ajax = jasmine.createSpy('ajax').and.callFake((url: string) =>
  of(true).pipe(tap(() => console.log('Subscribed to AJAX'))));
```

2020-09-20 09:04 UTC, gkalpak commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +  it('should return an empty array', () => {
Sure. You could do something like:

```ts
let i = 0;
const ajax = jasmine.createSpy('ajax').and.callFake((url: string) =>
  of(null).pipe(mergeMap(() => (++i < 4) ? throwError('Test error') : of(/* Proper response */))));
```

2020-09-20 13:36 UTC, sonukapoor commented on aio/content/examples/rx-library/src/simple-creation.2.ts
> +    console.log(`It's been ${n} seconds since subscribing!`));
I am not following on this one. Can you please explain?

2020-09-20 13:50 UTC, sonukapoor commented on aio/content/examples/rx-library/src/simple-creation.3.spec.ts
> +  it('should call unsubscribe when clientX and clientY are below < 40 ', () => {
There are many expectations that verify the coordinates through the `console.log` spy. Is there any specific we need? I will add the un-subscription test.

2020-09-20 14:04 UTC, sonukapoor commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +  it('should return an empty array', () => {
I was not able to get this working, so I left it as is. Please add a commit if you can. Thanks 👍

2020-09-20 15:37 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.2.ts
> +    console.log(`It's been ${n} seconds since subscribing!`));
Sorry, I meant `n + 1`. I've updated the original comment.

2020-09-20 15:39 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.3.spec.ts
> +  it('should call unsubscribe when clientX and clientY are below < 40 ', () => {
We need to have small focused tests. We can test everything in one giant tests, but that is not very ergonomic when the test starts failing :smiley:

2020-09-21 11:23 UTC, gkalpak requested changes
Reminder to self: https://github.com/angular/angular/pull/38905#discussion_r491494196 is still pending.

2020-09-21 11:23 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.2.ts
> +    console.log(`It's been ${n} seconds since subscribing!`));
As per https://github.com/angular/angular/pull/38905#discussion_r491486940, this should actually be:

```suggestion
    console.log(`It's been ${n + 1} seconds since subscribing!`));
```

2020-09-21 11:23 UTC, gkalpak commented on aio/content/examples/rx-library/src/error-handling.ts
> +export function docRegionApiData(console, ajax) {
As per https://github.com/angular/angular/pull/38905#discussion_r491483373, I would prefer to keep the convention that these function are named after the PascalCased docregion name, prefixed with `docRegion`. For the unnamed, default docregions, I suggest we use a consistent name acriss all files. Something like `docRegionDefault()` or `docRegionUnnamed()`.

2020-09-21 11:23 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.3.spec.ts
> +    expect(input.removeEventListener).toHaveBeenCalledWith('mousemove', jasmine.any(Function), undefined);
Couldn't this be:

```suggestion
    expect(input.removeEventListener).toHaveBeenCalledWith('mousemove', triggerMousemove, undefined);
```

2020-09-21 11:23 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.3.spec.ts
> +  it('should call unsubscribe when clientX and clientY are below < 40 ', () => {
As per https://github.com/angular/angular/pull/38905#discussion_r491490796, this should be broken up into multiple tests (i.e. `it()` calls).

2020-09-21 11:23 UTC, gkalpak commented on aio/content/examples/rx-library/src/simple-creation.ts
> +
There is not reason to have an empty line here (since it is at the end of the docregion). Whitespace is trimmed on docregion content anyway.

2020-09-21 11:23 UTC, gkalpak commented on aio/content/examples/rx-library/src/retry-on-error.ts
>  import { map, retry, catchError } from 'rxjs/operators';
Please indent the imports (as stated by the comment above and as is done in other examples) and indent the function body (for consistency).

2020-09-21 11:23 UTC, gkalpak commented on aio/content/examples/rx-library/src/retry-on-error.ts
> +      console.log('Error occured. Retrying...');
The `Retrying...` part is not necessarily true and therefore confusing.
Let's stick to:

```suggestion
      console.log('Error occured.');
```

2020-09-25 08:00 UTC, gkalpak requested changes
https://github.com/angular/angular/pull/38905#discussion_r491963927 doesn't seem to have been addressed.

Reminder to self: https://github.com/angular/angular/pull/38905#discussion_r491494196 is still pending.

2020-09-26 18:32 UTC, sonukapoor commented on aio/content/examples/rx-library/src/error-handling.spec.ts
> +    subject.next({});
Good catch!

2020-09-27 09:03 UTC, gkalpak requested changes
https://github.com/angular/angular/pull/38905#discussion_r494813072 doesn't seem to have been addressed.

##
Reminder to self: https://github.com/angular/angular/pull/38905#discussion_r491494196 is still pending.

2020-09-27 09:03 UTC, gkalpak commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +      return of(true).pipe(tap(() => mockConsole.log('Subscribed to AJAX')));
`true` is a little confusing. Let's use `of({})` instead.

2020-09-27 15:45 UTC, sonukapoor commented
> [#38905 (comment)](https://github.com/angular/angular/pull/38905#discussion_r494813072) doesn't seem to have been addressed.
> 
> Reminder to self: [#38905 (comment)](https://github.com/angular/angular/pull/38905#discussion_r491494196) is still pending.

I see the change here:

https://github.com/angular/angular/blob/546e665760e6acbcb1225d57c8808eb3ae319fcf/aio/content/examples/rx-library/src/retry-on-error.ts

2020-09-27 15:45 UTC, sonukapoor commented on aio/content/examples/rx-library/src/error-handling.spec.ts
> +    ajax = ajax.and.returnValue(throwError('Test Error'));
Good point

2020-09-27 15:47 UTC, sonukapoor commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +    });
Since we do not have any linter any place for this. What is the rule of thumb here to break the lines?

2020-09-27 16:00 UTC, gkalpak commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +    });
The limit is 100 chars per line.

2020-09-27 16:02 UTC, gkalpak commented
>> [#38905 (comment)](https://github.com/angular/angular/pull/38905#discussion_r494813072) doesn't seem to have been addressed.
>> 
>> Reminder to self: [#38905 (comment)](https://github.com/angular/angular/pull/38905#discussion_r491494196) is still pending.

> I see the change here:
>
> https://github.com/angular/angular/blob/546e665760e6acbcb1225d57c8808eb3ae319fcf/aio/content/examples/rx-library/src/retry-on-error.ts

I don't see it. My comment was about `error-handling.spec.ts`, but you linked to `retry-on-error.ts` 😕

2020-09-27 16:20 UTC, sonukapoor commented
> I don't see it. My comment was about `error-handling.spec.ts`, but you linked to `retry-on-error.ts` 😕

Strange, pretty sure that the original comment was pointing to the import alignment. Regardless, I have fixed the variable renaming from `subject` to `ajaxSubject`.

2020-09-28 14:41 UTC, sonukapoor commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +    });
Is that documented anywhere?

2020-09-28 14:48 UTC, gkalpak commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +    });
It's in [CONTRIBUTING.md#rules][1].

[1]: https://github.com/angular/angular/blob/323be39297450fa5a4a70f800511722b4964dec2/CONTRIBUTING.md#rules

2020-09-28 16:36 UTC, gkalpak commented on aio/content/examples/rx-library/src/retry-on-error.spec.ts
> +  it('should return an empty array', () => {
For reference: I pushed commit e0e139daeb4a21b19cf57fcfd597b59c7556fccd.

2020-09-28 16:36 UTC, gkalpak commented
@googlebot I consent.

2020-09-28 16:38 UTC, gkalpak approved these changes
LGTM :shipit:
Thank you, @sonukapoor, for getting everything sorted out ❤️ 

Reviewed-for: global-docs-approvers

2020-09-28 16:40 UTC, gkalpak commented
@sonukapoor: FYI, I rebased this on master, squashed fixup commits, added a new fixup commit with some minor clean-up and added a new commit with the test we discussed in https://github.com/angular/angular/pull/38905#discussion_r491494196.

Please, take a look and confirm this looks good to you 👀

2020-09-28 16:57 UTC, sonukapoor commented
> @sonukapoor: FYI, I rebased this on master, squashed fixup commits, added a new fixup commit with some minor clean-up and added a new commit with the test we discussed in [#38905 (comment)](https://github.com/angular/angular/pull/38905#discussion_r491494196).
> 
> Please, take a look and confirm this looks good to you 👀

LGTM. Thanks @gkalpak

2020-09-28 20:20 UTC, closed without merging