docs (docs-infra): fix broken command
angular/angular pull request #38960
Opened 2020-09-23 18:49 UTC by dkreider

Angular [no longer uses the `.bundle.` file extension](https://github.com/angular/angular-cli/issues/13145#issuecomment-445220083) so this example command is broken. This proposed change shows an updated example that actually works instead of leaving the user confused as to why nothing happens.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-09-25 10:34 UTC, gkalpak approved these changes
Thx, @dkreider :+1:

There seems to be one more occurrence of `.bundle.js` on [line 390][L390]. Could you take care of that as well:

```diff
-  ls dist/*.bundle.js
+  ls dist/*.js
```


[L390]: https://github.com/angular/angular/blame/a1cd10598b839c979dcdf8da5302544241d1d0ce/aio/content/guide/deployment.md#L390

2020-09-25 10:36 UTC, gkalpak requested changes
Thx, @dkreider :+1:

There seems to be one more occurrence of `.bundle.js` on [line 390][L390]. Could you take care of that as well:

```diff
-  ls dist/*.bundle.js
+  ls dist/*.js
```


[L390]: https://github.com/angular/angular/blame/a1cd10598b839c979dcdf8da5302544241d1d0ce/aio/content/guide/deployment.md#L390

2020-09-25 20:15 UTC, gkalpak requested changes
Thx for making the change, @dkreider!
It is not exactly right - I left a comment.

2020-09-25 20:15 UTC, gkalpak commented on aio/content/guide/deployment.md
> +  ls dist/main*
As mentioned in https://github.com/angular/angular/pull/38960#pullrequestreview-496304659, this should be `  ls dist/*.js`.

2020-09-25 21:04 UTC, dkreider commented
Ugh! So sorry for overlooking that and thanks for the correction. 

Anything else I'm missing?

Thanks for your patience and help.

2020-09-26 15:28 UTC, gkalpak requested changes
The changes look great now. Thx for seeing it through, @dkreider :tada:
Now, you just need to squash all commits into one. (And while you're at it, you might also want to update the commit message to reflect the fact that the commit now fixes to commands (instead of just one) :wink:)

2020-09-28 17:39 UTC, dkreider commented
@gkalpak Of course! You're very welcome!

Commits have been squashed. Anything else needed?

This is my first time contributing to Angular and I've enjoyed the experience. Thank you so much for your patience with me.

2020-09-29 15:22 UTC, gkalpak approved these changes
LGTM 🚀 Thx, @dkreider!
Looking forward to your next PR 😉 

Reviewed-for: global-docs-approvers

2020-09-30 13:17 UTC, closed without merging