Initial support for autocompletion operations in the TemplateTypeChecker
angular/angular pull request #39048
Opened 2020-09-29 18:22 UTC by alxhub

See individual commits for descriptions

2020-09-30 18:54 UTC, atscott requested changes

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +    this.ensureAllShimsForOneFile(component.getSourceFile());
Why not `this.ensureShimForComponent(component)` here? It might be useful to add some documentation to the `ensure...Shim...` functions to explain what scenarios you should use them for.

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +    }
Other than the errors you're throwing, this looks pretty similar to `this.getTemplateData`

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +    let tcb: ts.Node|null = findTypeCheckBlock(shimSf, id);
This looks pretty much exactly `this.getTypeCheckBlock`, which also duplicates a bunch of the logic above, including the errors.

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +
I think everything below this line should be extracted to a new function, potentially even in a separate file. The logic below is the core implementation of the `getGlobalCompletions` functionality while everything above is pretty much separate "setup" code.

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +      position: globalRead.name.pos,
Didn't we settle on `getStart()` as being the source of truth for positions? I think maybe it doesn't make a difference here because the form of the component completion context is always `ctx.` so `pos` and `getStart()` would be the same but it might be worth changing this for the sake of consistency.

// cc @kyliau

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +    // Next, produce a list of all variable or reference completions. This is done in two steps:
This comment seems to indicate a good place to create a separate helper function.

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +    while (true) {
Can this be `do..while` instead?
```
    do {
...
    } while (scope !== null)
```

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +    // Step 2: convert `namedEntities` into a list of `VariableCompletion` or
It seems like step 1 and 2 could also be separate helper functions or something like:

```
function getVaraibleAndReferenceCompletions() {
  const namedEntities = getNamedEntities(...);
  for (const node of namedEntities.values()) {
    ...
  }
}
```
or 
```
function getVaraibleAndReferenceCompletions() {
  const namedEntities = getNamedEntities(...);
  const varAndRefCompletions = toCompletions(namedEntities.values());
  completions.push(...varAndRefCompletions);
}
```

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +      // Add references first, since references shadow variables.
Is this accurate?

* If you reorder these, the tests will still pass (well, one fails because of the completion names are in a different order)
* The shadowing is based on scopes, not the type, right? 
* The test for shadowing actually shows a variable shadowing a reference.

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/comments.ts
> +  COMPONENT_COMPLETION = 'COMPCOMP',
😆

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/test/type_checker__completion_spec.ts
> +      expect(rest.length).toBe(0);
clever!

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +      shimFile: shimPath,
Should we use the common `ShimLocation` from `symbols.ts` to encapsulate `shimFile` and `position`?

2020-09-30 18:54 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/test/type_checker__completion_spec.ts
> +      expect(completionKeys).toEqual(['innerRef', 'user', 'topLevelRef']);
```suggestion
      expect(completionKeys.sort()).toEqual(['innerRef', 'user', 'topLevelRef'].sort());
```
Unless the order matters here, consider using `sort`. The order might actually matter for prioritizing completions in the language service though...

2020-09-30 19:09 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +    }
It is, but because we need _both_ the TCB and the template data itself, it made sense to inline the operations.

2020-09-30 22:02 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/api/checker.ts
> +/**
Done!

2020-09-30 22:02 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +    this.ensureAllShimsForOneFile(component.getSourceFile());
Good point. The refactoring already includes this.

2020-09-30 22:03 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +    }
I've refactored this logic into a `getLatestComponentState` function, which returns both the TCB and the `TemplateData`. It should cut down on the need to repeat the data structure walking from function to function. `getSymbolOfNode` uses it now too.

2020-09-30 22:04 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +
Yep, the setup code is extracted out. I do think the implementation belongs in the `TemplateTypeCheckerImpl` class though.

2020-09-30 22:06 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +    while (true) {
No, since `scope` will become `null` but we still need to process the root template in that case.

2020-09-30 22:07 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +      shimFile: shimPath,
Good idea - done!

2020-10-01 18:56 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +      // Add references first, since references shadow variables.
Shadowing is now handled by the binder :)

2020-10-01 19:12 UTC, atscott approved these changes
Beautiful! 👌

2020-10-01 19:12 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +    // 1. produce a mapping of entity names to their declarations which takes into account shadowing
👍 I think this all looks good now that the setup code moved out. Just the comments here about the steps need to be updated.

2020-10-01 19:12 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +    if (tcb === null || data === null) {
nit: shimPath can be moved up here too

2020-10-01 19:12 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +      }
```suggestion
const kind = node instanceof TmplAstReference ? CompletionKind.Reference : CompletionKind.Variable;
completions.push({kind, node});
```

2020-10-01 19:12 UTC, atscott commented on packages/compiler/src/render3/view/t2_api.ts
> +  getEntitiesInTemplateScope(template: Template|null): ReadonlySet<Reference|Variable>;
Nice, I like how this is analogous to `ts.TemplateTypeChecker#getSymbolsInScope`. I optionally rename this to just `getEntitiesInScope` since the `Template` is a parameter, I think it's somewhat self-explanatory that it is template scope. This would also align more with `getNestingLevel` which isn't `getTemplateNestingLevel`, likely for the same reason.

2020-10-02 00:01 UTC, atscott commented
[presubmit](https://test.corp.google.com/ui#id=OCL:334917714:BASE:334917767:1601593704924:6daadded)

2020-10-02 14:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/comments.ts
> +  COMPONENT_COMPLETION = 'COMPCOMP',
😂

2020-10-02 17:08 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +      }
I don't think this will work, since both `CompletionKind.Reference` and `CompletionKind.Variable` have constraints on the `node` type and TS won't be able to prove that they're met.

2020-10-06 20:55 UTC, closed without merging