feat(language-service): add quick info for inline templates in ivy
angular/angular pull request #39060
Opened 2020-09-30 15:40 UTC by atscott

Adds implementation for `getQuickInfoAtPosition` to the Ivy Language
Service, which now returns `ts.QuickInfo` for inline templates.

2020-09-30 16:25 UTC, josephperrott approved these changes
LGTM

Reviewed-for: dev-infra

2020-09-30 23:22 UTC, ayazhafiz reviewed
This is very nice!! Awesome stuff.

A general comment: does this work with `ref-`, `bind-`, `on-` syntaxes? If so, could tests for that be added as well?

2020-09-30 23:22 UTC, ayazhafiz commented on packages/language-service/ivy/test/quick_info_spec.ts
> +        // expectedDisplayParts: '(directive) AppModule.StringModel: typeof StringModel'
Do we want the ": typeof StringModel" part?

2020-09-30 23:22 UTC, ayazhafiz commented on packages/language-service/ivy/test/quick_info_spec.ts
> +      expect(quickInfo).toBeUndefined();
Is there value in providing documentation for what ng-template is?

2020-09-30 23:22 UTC, ayazhafiz commented on packages/language-service/ivy/test/quick_info_spec.ts
> +        expectedDisplayParts: '(directive) NgForOf<any, any>'
Are the type parameters `any, any` because `items` does not exist? Could we run this test with an iterable that is valid to demonstrate correct typing?

2020-09-30 23:22 UTC, ayazhafiz commented on packages/language-service/ivy/test/quick_info_spec.ts
> +          expectedDisplayParts: '(property) StringModel.model: string'
I would expect the quick info here to be an event, and a property only if I clicked between `[(` or `)]`. Is there a reason we want property quick info?

2020-09-30 23:22 UTC, ayazhafiz commented on packages/language-service/ivy/test/quick_info_spec.ts
> +          expectedDisplayParts: '(parameter) $event: MouseEvent'
Wow!! nice!

2020-09-30 23:22 UTC, ayazhafiz commented on packages/language-service/ivy/test/quick_info_spec.ts
> +        expectedDisplayParts: '(local var) chart: HTMLDivElement'
I would prefer "reference" or "(ref var)" rather than "(local var)" here since references are the common term for this in templates, and "(local var)" feels like more like a detail on how this template could look like if it was JS code.

2020-09-30 23:22 UTC, ayazhafiz commented on packages/language-service/ivy/test/quick_info_spec.ts
> +        expectedDisplayParts: '(local var) chart: HTMLDivElement'
Also, `(local var)` is used by `ts.ScriptElementKind.localVariableElement` which corresponds to a variable in a local scope (like a function) which feels very different than what is happening here.

2020-09-30 23:28 UTC, kyliau requested changes

2020-09-30 23:28 UTC, kyliau commented on packages/language-service/ivy/utils.ts
> +    fileName: string, position: number, program: ts.Program,
Consider passing `NgCompiler` instead, since it has both the program and the template type checker.

2020-09-30 23:28 UTC, kyliau commented on packages/language-service/ivy/utils.ts
> +    attributes = [...attributes, ...hostNode.templateAttrs];
We can declare `attributes` as const and use `attributes.push(...hostNode.templateAttrs)` here

2020-09-30 23:28 UTC, kyliau commented on packages/language-service/ivy/utils.ts
> +  const toAttributeString = (a: TmplAstTextAttribute|TmplAstBoundAttribute) =>
nit: in google3 the TS style guide recommends using `function() { ... }` declaration if access to `this` is not needed.

2020-09-30 23:28 UTC, kyliau commented on packages/language-service/ivy/utils.ts
> +        p.kind === ALIAS_NAME && p.text.match(tcbAliasImportRegex) !== null;
`RegExp.test()` is better if we don't need the matching results.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

2020-09-30 23:28 UTC, kyliau commented on packages/language-service/test/project/tsconfig.json
> +    "strictTemplates": true
`strictTemplates` is a superset of `fullTemplateTypeCheck`, so we don't need the latter.

2020-09-30 23:28 UTC, kyliau commented on packages/language-service/ivy/test/quick_info_spec.ts
> +    expect(text.substr(textSpan.start, textSpan.length)).toEqual(expectedSpanText);
`.substr()` is deprecated, please use `.substring()`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring

2020-09-30 23:28 UTC, kyliau commented on packages/language-service/ivy/test/quick_info_spec.ts
> +          {templateOverride: string, expectedSpanText: string, expectedDisplayParts: string}):
`expectedDisplayParts` seems to imply `ts.DisplayParts[]`, perhaps we should call it `expectedDisplayString`?

2020-10-01 00:46 UTC, ayazhafiz commented on packages/language-service/ivy/utils.ts
> +  const components = compiler.getComponentsWithTemplateFile(fileName);
Is this deterministic? Can we document whether it is?

2020-10-01 00:46 UTC, ayazhafiz commented on packages/language-service/ivy/utils.ts
> +    {template: TmplAstNode[], component: ts.ClassDeclaration}|undefined {
Same suggestion as Keen had for `getTemplateInfoAtPosition`, consider an interface for the rt

2020-10-01 00:46 UTC, ayazhafiz commented on packages/language-service/ivy/utils.ts
> +  const attrs = attributes.map(a => toAttributeString(a));
nit
```suggestion
  const attrs = attributes.map(toAttributeString);
```

2020-10-01 00:46 UTC, ayazhafiz commented on packages/language-service/ivy/utils.ts
> +    attribute: string, hostNode: TmplAstTemplate|TmplAstElement, directives: DirectiveSymbol[]) {
Can we document the return type, either in code or in comments or both?

2020-10-01 00:46 UTC, ayazhafiz commented on packages/language-service/ivy/utils.ts
> +  return directivesWithAttribute.filter(d => !directivesWithoutAttribute.some(s => s === d));
Why not have `directivesWithoutAttribute` be a set rather than iterating over it each time?

2020-10-01 00:46 UTC, ayazhafiz commented on packages/language-service/ivy/utils.ts
> +    const nextPart = displayParts![i + 1];
```suggestion
    const previousPart = displayParts[i - 1];
    const nextPart = displayParts[i + 1];
```

I don't think the ! is needed

2020-10-01 00:46 UTC, ayazhafiz commented on packages/language-service/ivy/utils.ts
> +        p.kind === SYMBOL_PUNC && p.text === '.';
can we pull these lambdas outside the filter lambda? The TCB import regex could be pulled out as well.

2020-10-01 00:46 UTC, ayazhafiz commented on packages/language-service/src/hover.ts
>    const containerDisplayParts = containerName ?
Do you think this should be pulled out until utils or similar since hover and quick_info are sharing this now? Doesn't need to be done in this PR.

2020-10-01 15:45 UTC, atscott commented on packages/language-service/ivy/test/quick_info_spec.ts
> +        // expectedDisplayParts: '(directive) AppModule.StringModel: typeof StringModel'
I felt like it was pretty redundant so I left it out intentionally.

2020-10-01 18:22 UTC, atscott commented on packages/language-service/ivy/utils.ts
> +  return directivesWithAttribute.filter(d => !directivesWithoutAttribute.some(s => s === d));
👍

2020-10-01 18:22 UTC, atscott commented on packages/language-service/ivy/utils.ts
> +  const components = compiler.getComponentsWithTemplateFile(fileName);
I don't think so. Pinging @alxhub for ideas here. I guess we could sort the results on source file name if not?

2020-10-01 18:26 UTC, alxhub commented on packages/language-service/ivy/utils.ts
> +  const components = compiler.getComponentsWithTemplateFile(fileName);
It's deterministic within a single `NgCompiler` instance (you can call it repeatedly to return the same results), but likely not stable across incremental changes to the `ts.Program`. The return value is a `Set`, which does tend to communicate that the order of the results is not specified (although in practice `Set`s do indeed have a defined iteration order).

I think sorting on the file name is a reasonable approach to ensuring stability.

2020-10-01 21:10 UTC, ayazhafiz commented on packages/language-service/ivy/test/quick_info_spec.ts
> +        // expectedDisplayParts: '(directive) AppModule.StringModel: typeof StringModel'
Could we exclude it from the comment here then?

2020-10-01 21:11 UTC, ayazhafiz commented on packages/language-service/ivy/test/quick_info_spec.ts
> +          expectedDisplayParts: '(property) StringModel.model: string'
Makes sense, thanks for the explanation!

2020-10-01 21:26 UTC, ayazhafiz commented on packages/language-service/ivy/quick_info.ts
> +      undefined,
```suggestion
      /** container */ undefined,
```

2020-10-01 21:26 UTC, ayazhafiz commented on packages/language-service/ivy/quick_info.ts
> +      undefined,
```suggestion
      /** container */ undefined,
```

2020-10-01 21:26 UTC, ayazhafiz commented on packages/language-service/ivy/test/language_service_spec.ts
> +      'strictTemplates': true,
Is there a reason strictTemplates is in quotes?

2020-10-01 21:26 UTC, ayazhafiz commented on packages/language-service/ivy/quick_info.ts
> +            'The `<ng-template>` is an Angular element for rendering HTML. It is never displayed directly.',
Do you think it would be helpful to include a link to https://angular.io/guide/structural-directives#the-ng-template as well?

Sorry to spin the wheel again, maybe a discussion about extensiveness of the info is better to be had another time after we have support for quick info.

2020-10-01 21:26 UTC, ayazhafiz commented on packages/language-service/ivy/utils.ts
> +export function filterAliasImports(displayParts: ts.SymbolDisplayPart[]) {
I almost feel like this should be a util provided by the compiler. But I guess the language service relies on the TCB leaking, so I am ambivalent either way. Just thought I would comment.

2020-10-01 22:47 UTC, atscott commented on packages/language-service/ivy/quick_info.ts
> +            'The `<ng-template>` is an Angular element for rendering HTML. It is never displayed directly.',
No worries! I thought about including it, but linking to the structural directive doc isn't always relevant. A lot of use-cases for the `ng-template` are just for later use in `ngTemplateOutlet` without a structural directive so I thought it best to not link there. We can certainly revisit this in the future.

2020-10-01 22:48 UTC, atscott commented on packages/language-service/ivy/test/language_service_spec.ts
> +      'strictTemplates': true,
Nope! I think this was a copy-paste error.

2020-10-01 22:49 UTC, atscott commented on packages/language-service/ivy/test/quick_info_spec.ts
> +        // expectedDisplayParts: '(directive) AppModule.StringModel: typeof StringModel'
👍

2020-10-02 00:51 UTC, kyliau approved these changes

2020-10-02 00:51 UTC, kyliau commented on packages/language-service/ivy/quick_info.ts
> +      symbol: InputBindingSymbol|OutputBindingSymbol, node: TmplAstNode|AST) {
nit: consider adding return types for all methods.
It's optional, but one benefit is that it'll help surface potential type errors faster in the future if there are code changes that inadvertently change the return type of the function.

2020-10-02 00:51 UTC, kyliau commented on packages/language-service/ivy/quick_info.ts
> +function createNgTemplateQuickInfo(node: TmplAstNode|AST) {
maybe add a TODO: there are also ng-content and ng-container
https://github.com/angular/angular/blob/db56cf18ba52e32c9481deb86e2c39262a2e7db6/packages/language-service/src/completions.ts#L30-L46

2020-10-02 00:51 UTC, kyliau commented on packages/language-service/ivy/test/BUILD.bazel
> +        "//packages/language-service/test:test_utils_lib",
If we dupe the `toText` function then we don't need this dependency, I think?

2020-10-02 00:51 UTC, kyliau commented on packages/language-service/ivy/utils.ts
> +import {AbsoluteSourceSpan, AST, BindingPipe, CssSelector, MethodCall, ParseSourceSpan, PropertyRead, PropertyWrite, SelectorMatcher, TmplAstBoundAttribute, TmplAstElement, TmplAstNode, TmplAstTempla
I don't think we need `TmplAst*` since we've already imported them as `t` on line 12

2020-10-02 00:51 UTC, kyliau commented on packages/language-service/ivy/utils.ts
> +  if (isTemplateNode(node)) {
this can be just
```ts
if (isTemplateNodeWithKeyAndValue(node)) {
  return toTextSpan(node.keySpan);
}
```
the final else case already handles `node.sourceSpan`.

2020-10-02 00:51 UTC, kyliau commented on packages/language-service/ivy/utils.ts
> +function getFirstComponentForTemplateFile(fileName: string, compiler: NgCompiler) {
please add return type

2020-10-02 00:51 UTC, kyliau commented on packages/language-service/ivy/utils.ts
> +  const sortedComponents = Array.from(components).sort((a, b) => {
consider pulling the comparator out as a standalone function.

2020-10-02 18:01 UTC, closed without merging