feat(dev-infra): add a command to verify NgBot YAML config syntax
angular/angular pull request #39071
Opened 2020-09-30 21:37 UTC by AndrewKushnir

This commit adds a new command to the `ng-dev` suite, which verifies that the NgBot YAML config is
correct. It also adds this command to the `lint` CircleCI job so that we execute this check while
running CI.

This should help prevent syntax errors similar to the one introduced in:
https://github.com/angular/angular/commit/393ce5574b76ad1344554a6aa9e2e8a6c3591ac9

## PR Type
What kind of change does this PR introduce?

- [x] Feature

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-09-30 22:56 UTC, josephperrott requested changes
Just a few comments

2020-09-30 22:56 UTC, josephperrott commented on dev-infra/ngbot/verify.ts
> +    info('NgBot YAML config is valid');
Can we include the green check mark to show the success?

```suggestion
    info(`${green('√')}  Valid NgBot YAML config`);
```

2020-09-30 22:56 UTC, josephperrott commented on dev-infra/ngbot/verify.ts
> +    error(e);
Can we have a line expressing directly that the config was not validated?

```suggestion
    error(`${red('!')} Invalid NgBot YAML config`);
    error(e);
```

2020-09-30 22:56 UTC, josephperrott commented on dev-infra/ngbot/verify.ts
> +    process.exit(1);
We should use `process.exitCode` instead of calling `exit()`

```suggestion
    process.exitCode = 1;
```

2020-10-01 02:10 UTC, AndrewKushnir commented
Thanks for the review @josephperrott! I've addressed your comments, could you please take another look? Thank you.

2020-10-01 18:56 UTC, josephperrott approved these changes
LGTM, just a couple little comments.

2020-10-01 18:56 UTC, josephperrott commented on dev-infra/ngbot/verify.ts
> +  /** The pull approve config file. */
This is actually the config for for NgBot I believe.

2020-10-01 18:56 UTC, josephperrott commented on dev-infra/cli.ts
> +    .command('ngbot <command>', '', buildNgbotParser)
Since this isn't something we are expecting users to run locally really, lets hide it from the default help menu.

 ```suggestion
    .command('ngbot <command>', false, buildNgbotParser)
```

2020-10-01 19:06 UTC, AndrewKushnir commented
Thanks @josephperrott, I've applied the updates based on your comments, adding the "merge" label.

2020-10-01 19:31 UTC, closed without merging