fix(dev-infra): run caretaker checks asyncronously
angular/angular pull request #39086
Opened 2020-10-01 18:36 UTC by josephperrott

Run each check in the caretaker check process asyncronously.

2020-10-30 15:29 UTC, gkalpak requested changes

2020-10-30 15:29 UTC, gkalpak commented on dev-infra/caretaker/check/github.ts
> +                                              repo}/issues?q=${queries[i]?.query}`),
Why do we need a `?` in `queries[i]?.query` but not in `queries[i].name` above?
Could we get rid of it here too?

2020-10-30 15:29 UTC, gkalpak commented on dev-infra/caretaker/check/github.ts
> +  const minQueryNameLength = Math.max(...results.map(result => result.queryName.length));
:100:

2020-11-02 18:00 UTC, josephperrott commented
@gkalpak Moved to the "module" system we discussed, PTAL

2020-11-03 18:44 UTC, gkalpak requested changes
Generally lgtm (with a few minor comments/questions/suggestions) :+1:

2020-11-03 18:44 UTC, gkalpak commented on dev-infra/caretaker/check/github.spec.ts
> +    it('if there are no maches of the query', async () => {
```suggestion
    it('if there are no matches of the query', async () => {
```

2020-11-03 18:44 UTC, gkalpak commented on dev-infra/caretaker/check/g3.ts
> +      info(`${stats.commits} commits between g3 and master`);
OOC, why only log commits when no sync is needed?

2020-11-03 19:41 UTC, josephperrott commented on dev-infra/caretaker/check/services.ts
> +    for (const service of data) {
I changed the name of the `data` to `services` which makes it more obvious that we are iterating through the list of  services and looking at each service individually.  Thoughts?

2020-11-03 20:02 UTC, josephperrott commented on dev-infra/caretaker/check/services.spec.ts
> +const ServicesModule = servicesExports.ServicesModule;
Legacy from when I was having to spy on something exported by `./services`

2020-11-03 20:11 UTC, josephperrott commented on dev-infra/caretaker/check/github.ts
> +    let queries = this.config.caretaker?.githubQueries!;
Added comment expressing why its needed.

2020-11-03 20:14 UTC, josephperrott commented on dev-infra/caretaker/check/g3.ts
> +      info(`${stats.commits} commits between g3 and master`);
I don't have a good reason, I think it stems from still wanting to express that a difference between the two branches exists, but I have moved it outside the conditional block.

2020-11-03 20:16 UTC, josephperrott commented on dev-infra/caretaker/check/g3.ts
> +      info(`${stats.commits} commits between g3 and master`);
Actually, I went back to how it was, but included the information in both resulting statements instead.

2020-11-03 21:31 UTC, gkalpak commented on dev-infra/caretaker/check/services.ts
> +    for (const service of data) {
I still think `status`/`statuses` is more descriptive. For example, `service.description` below sounds as if it refers to the description of the service (while it's the description of the status).

But I don't feel strongly about it - leaving it up to you 👉

2020-11-03 21:35 UTC, josephperrott commented on dev-infra/caretaker/check/services.ts
> +    for (const service of data) {
Updated.

2020-11-03 22:33 UTC, gkalpak approved these changes
LGTM 🚀

2020-11-03 22:33 UTC, gkalpak commented on dev-infra/caretaker/check/ci.spec.ts
> +/** Build a mock set of ActiveReleaseTrains.  */
```suggestion
/** Build a mock set of ActiveReleaseTrains. */
```

😇

2020-11-04 00:33 UTC, closed without merging