fix(router) onSameUrlNavigation config is now passed through RouterTestingModule
angular/angular pull request #39096
Opened 2020-10-02 16:01 UTC by zelliott

Previously, setting onSameUrlNavigation in the config for RouterTestingModule in a unit test did not update the router's config. Now, it properly updates the router's config.

Fixes #23347

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Setting onSameUrlNavigation in the config for RouterTestingModule in a unit test did not update the router's config.

Issue Number: 23347

## What is the new behavior?

Setting onSameUrlNavigation in the config for RouterTestingModule in a unit test correctly updates the router's config.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-10-02 17:05 UTC, atscott requested changes
Hi @zelliott, thanks for the PR. As mentioned in the last comment on the bug, there are actually several options that don't make it from `ExtraOptions` to the `router` when using `RouterTestingModule`. I think we should address those as well. 

It might be a good idea to create a function in `router_module` like `assignExtraOptionsToRouterFields(router: Router, options: ExtraOptions) { ... }` and share the code for the `RouterModule` implementation and the `RouterTestingModule` https://github.com/angular/angular/blob/db56cf18ba52e32c9481deb86e2c39262a2e7db6/packages/router/src/router_module.ts#L443-L483 (excluding `enableTracing`)

2020-10-03 16:43 UTC, zelliott commented
> As mentioned in the last comment on the bug, there are actually several options that don't make it from `ExtraOptions` to the `router` when using `RouterTestingModule`. I think we should address those as well.

Done, PTAL.

2020-10-05 16:55 UTC, atscott approved these changes
One small nit on the test organization but otherwise LGTM. [presubmit](http://test/OCL:335438288:BASE:335438319:1601916909728:cba28fa0). Starting global as well.

We might want to consider adding a breaking change note even though it's pretty unlikely/rare that this would break people. Something like 
"BREAKING CHANGE: The `RouterTestingModule` now correctly assigns `errorHandler`, `urlUpdateSstraategy`, (...etc) from the `ExtraOptions` to the test module rather than just `malformedUriErrorHandler` and `paramsInheritanceStrategy`. If your test is setting these options, they will now be applied to navigations where they were ignored before and could result in a change in test behavior."

2020-10-05 16:55 UTC, atscott commented on packages/router/test/integration.spec.ts
> +  describe('onSameUrlNavigation', () => {
nit: I think these tests should be organized like 

```
describe('should configure the router', () => {
  it('assigns paramsInheritanceStrategy', () => {
     TestBed.configureTestingModule(
          {imports: [RouterTestingModule.withRoutes([], {paramsInheritanceStrategy: 'always'})]});
    expect(router.paramsInheritanceStrategy).toEqual('always');
  });
  it('assigns relativeLinkResolution', () => {
    TestBed.configureTestingModule(
          {imports: [RouterTestingModule.withRoutes([], {relativeLinkResolution: 'corrected'})]});
    expect(router.relativeLinkResolution).toEqual('corrected');
  });
});

Or even a single test that assigns all the different configs and does all the assertions there.

2020-10-05 19:04 UTC, IgorMinar approved these changes
LGTM, thank you

2020-10-05 19:32 UTC, zelliott commented on packages/router/test/integration.spec.ts
> +  describe('onSameUrlNavigation', () => {
Done

2020-10-05 23:19 UTC, atscott commented
[global presubmit](https://test.corp.google.com/ui#id=OCL:335438288:BASE:335403625:1601933298758:72451a4a) shows no related failures (1 test failed, but it's already failing at head). Marking as merge ready.

2020-10-05 23:35 UTC, closed without merging