fix(router): Allow undefined inputs on routerLink
angular/angular pull request #39151
Opened 2020-10-07 06:29 UTC by PowerKiKi

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

When compiling in the most strict mode, the following will throw error, but it is should be valid:

```html
    <a [routerLink]="['foo']" [fragment]="null">some link</a>
```

The error would be similar to:

```
    ERROR in foo.component.html:2:52 - error TS2322: Type 'null' is not assignable to type 'string'.
    
    2         <a [routerLink]="['foo']" [fragment]="null">some link</a>
```

## What is the new behavior?

This make it coherent with typing of Router.createUrlTree to which those inputs are directly forwarded to. And hence it allow to pass `undefined`, `null` or a value to the routerLink directive.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-10-07 06:34 UTC, alfaproject commented on packages/router/src/directives/router_link.ts
> +import {Params} from '@angular/router';
Use a relative import

2020-10-07 06:34 UTC, alfaproject commented on packages/router/src/directives/router_link.ts
>    // TODO(issue/24571): remove '!'.
I guess this comment is no longer needed

2020-10-07 06:37 UTC, PowerKiKi commented on packages/router/src/directives/router_link.ts
> +import {Params} from '@angular/router';
fixed in a forced pushed commit

2020-10-07 06:37 UTC, PowerKiKi commented on packages/router/src/directives/router_link.ts
>    // TODO(issue/24571): remove '!'.
fixed in a forced pushed commit

2020-10-09 15:14 UTC, atscott requested changes
Hi @PowerKiKi, thanks for the PR. Just a couple notes:

* Please fix the lint failure by running `yarn ng-dev format files packages/router/src/directives/router_link.ts`
* Please fix the test failure by running `yarn bazel run //packages/router:router_api.accept`
* On the surface, this is a really good quality of life change. These types should have been aligned from the very beginning. Unfortunately, we have to consider this a breaking change because this could produce new TS errors (i.e. `Object is possible 'null' or 'undefined'`) in locations that access these public fields. I'll need to run a global presubmit to see how often this generally occurs in user code. If it causes a lot of breakages, we'll need to think about adding a migration to automatically add the null assertion operator for those.
* Because of the note above, please add a `BREAKING CHANGE: ` footer to your commit message and just quickly highlight what changed and what needs to be done to fix the build failure if devs see this when upgrading to v11
* Lastly, the feature freeze for v11 is next week so depending on the results of the testing, it's quite likely that this is going to miss the cut-off and will need to be pushed back until v12 ☹️  Hopefully testing goes smoothly though! 🤞

2020-10-09 21:37 UTC, atscott commented
[global presubmit](https://test.corp.google.com/ui#id=OCL:336293970:BASE:336280767:1602276583973:5505f02a) shows now breakages due to this change. 

@PowerKiKi This means there's a pretty strong indication that the change here will not break user code in the vast majority of cases. I think it'd still be a good idea to add the breaking change note to the commit message as mentioned above. The message can be pretty minimal, given that this is rare / will never happen.

2020-10-11 01:16 UTC, PowerKiKi commented
Thank you for the review, I fixed the code style, commit message and accepted the API changes in the golden files.

Hopefully that should be enough for merging.

2020-10-12 15:14 UTC, atscott approved these changes
reviewed-for: fw-router
reviewed-for: public-api

2020-10-12 16:53 UTC, petebacondarwin approved these changes
Reviewed-for: public-api

Anyone expecting these to be defined is probably in trouble any way, right?
Since the inputs are not required on the directive they could indeed be undefined at runtime.

2020-10-12 17:10 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2020-10-12 19:23 UTC, atscott approved these changes

2020-10-12 19:52 UTC, closed without merging