feat(core): support passing Trusted Types around sanitization pipeline
angular/angular pull request #39217
Opened 2020-10-10 22:59 UTC by bjarkler

Angular's sanitization pipeline is an application's last line of defence against XSS vulnerabilities. However, it currently outputs plain strings that are then passed to the DOM, where they may cause Trusted Types violations. As a step towards fixing that, make it possible to return Trusted Types from the sanitization pipeline.

This is based on #39207. See the individual commits for more details.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information
This is part of an ongoing effort to add support for Trusted Types to Angular.

2020-10-13 21:42 UTC, bjarkler commented on packages/core/src/sanitization/bypass.ts
> +export function unwrapSafeValue<T>(value: SafeValue): string|T;
Good catch. I reverted this part of the PR since it's not needed for the MVP, but will make sure to fix this when we do make this change.

2020-10-15 22:01 UTC, bjarkler commented
[presubmit](http://test/337380467)

2020-10-16 00:25 UTC, IgorMinar commented
I believe that this PR can be closed as the relevant changes were included in #39218 which is already in the merge queue.

2020-10-16 00:26 UTC, IgorMinar requested changes
I believe that this PR can be closed because the relevant changes were already included in the #39218 PR which is already in the merge queue.

2020-10-16 00:26 UTC, IgorMinar requested changes
Reviewed-for: fw-security

2020-10-16 00:55 UTC, bjarkler commented
You're right, closing in favor of #39218.

2020-10-16 00:55 UTC, closed without merging