docs(core): Changes in the "View Encapsulation" guide
angular/angular pull request #39246
Opened 2020-10-13 17:13 UTC by pkyriazo

1. In line 25 changed the word "components" to "component's".
2. In line 66 changed the phrase "you never refer to them" to "you should never refer to them".
3. Appended the paragraph containing the above phrase in a `div` with the class `alert is-helpful`.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-10-13 17:48 UTC, pkyriazo commented
@googlebot I signed it!

2020-10-15 01:26 UTC, AndrewKushnir requested changes
@pkyriazo thanks for the updates to Angular docs. The content looks good, but I believe we should not add the `<div class="alert is-helpful">`, since that block refers to a code example below. Could you please remove the `<div>` and keep the rest of the changes? Thank you.

2020-10-15 06:12 UTC, pkyriazo commented
Done!

2020-10-15 13:10 UTC, gkalpak approved these changes
Thx, @pkyriazo!

Can you please rebase on latest master and squash the commits together (to make CI happy)?

2020-12-02 01:39 UTC, AndrewKushnir approved these changes
The changes look good, thanks @pkyriazo.

Could you please squash commits as George mentioned? That should make CI happy and would allow us to add this PR into the merge queue.

2020-12-08 12:02 UTC, petebacondarwin commented
I took the liberty of squashing the commits.

2020-12-08 16:53 UTC, closed without merging