docs: rename `ng xi18n` to `ng extract-i18n`
angular/angular pull request #39337
Opened 2020-10-20 07:44 UTC by alan-agius4

In Angular CLI version 11, xi18m has been changes to `ng xi18n` to `extract-i18n`.

2020-10-21 07:34 UTC, petebacondarwin reviewed
Missed one here https://github.com/angular/angular/pull/39337/files#diff-cfdcd6009e2e7f5e57c71c3541c6d893706f4a79881ac17790beb0447d2f65d3R330

2020-10-21 07:35 UTC, petebacondarwin commented on aio/content/guide/i18n.md
> +The ng extract-i18n extraction mechanism uses the ViewEngine compiler, which is not able to cope with some code syntax that the Ivy compiler can handle. A fix for this issue is currently under develo
Actually we need to rewrite this paragraph since #32912 landed and we no longer use the ViewEngine for extraction in v11, right?

2020-10-21 07:36 UTC, petebacondarwin commented on aio/content/guide/i18n.md
> +The ng extract-i18n extraction mechanism uses the ViewEngine compiler, which is not able to cope with some code syntax that the Ivy compiler can handle. A fix for this issue is currently under develo
Or perhaps just remove this whole alert box?

2020-10-21 07:37 UTC, petebacondarwin reviewed
Missed another https://github.com/angular/angular/pull/39337/files#diff-cfdcd6009e2e7f5e57c71c3541c6d893706f4a79881ac17790beb0447d2f65d3R379

2020-10-21 07:38 UTC, petebacondarwin commented on aio/content/guide/workspace-config.md
> +* The `architect/extract-i18n` section configures defaults for options of the `ng-xi18n` tool used by the `ng extract-i18n` command, which extracts marked message strings from source code and outputs
Is the `ng-xi18n` tool still a thing? Perhaps we should reword this?

2020-10-21 07:38 UTC, alan-agius4 commented on aio/content/guide/i18n.md
> +The ng extract-i18n extraction mechanism uses the ViewEngine compiler, which is not able to cope with some code syntax that the Ivy compiler can handle. A fix for this issue is currently under develo
ViewEngine extraction can still be used for Ivy apps but it's opt in.

2020-10-21 07:39 UTC, petebacondarwin reviewed
Also need to change this one:

https://github.com/angular/angular/blob/d37939623ff756dbd7908db0d39d05ac7920d79a/integration/cli-hello-world-ivy-i18n/package.json#L13

2020-10-21 07:40 UTC, alan-agius4 commented
@petebacondarwin the above command will need to be changed in the future, the current CLI on npm doesn't contain the new command name.

2020-10-21 07:41 UTC, petebacondarwin commented on integration/ivy-i18n/e2e/README.md
> +The legacy `ng extract-i18n` tool extracts the messages from the Angular templates, into the XLIFF 1.2
It is not actually legacy - I used this terminology incorrectly when writing this doc.

```suggestion
The CLI `ng extract-i18n` tool extracts the messages from the Angular templates, into the XLIFF 1.2
```

2020-10-21 07:43 UTC, alan-agius4 commented on aio/content/guide/workspace-config.md
> +* The `architect/extract-i18n` section configures defaults for options of the `ng-xi18n` tool used by the `ng extract-i18n` command, which extracts marked message strings from source code and outputs
done

2020-10-21 07:46 UTC, petebacondarwin requested changes
A couple of fixes worth doing in this PR. I think.
Thanks for updating the docs etc @alan-agius4

2020-10-21 07:47 UTC, alan-agius4 commented
@petebacondarwin pushed

2020-10-21 07:54 UTC, petebacondarwin commented on integration/ivy-i18n/e2e/README.md
> +### CLI
```suggestion
### legacy
```

This bit was actually correct :-)

2020-10-22 12:53 UTC, petebacondarwin approved these changes

2020-10-22 21:29 UTC, atscott approved these changes

2020-10-22 22:44 UTC, AndrewKushnir commented
@alan-agius4 @petebacondarwin I was wondering if there is a chance that we may need to add more i18n-related scripts to CLI? If I remember correctly Pete mentioned a migration tool/script to convert legacy message ids to new format (we don't have it, but may consider adding it in the future). If we plan to add more scripts, make be we can take that into account and format the command like this:
```
ng i18n:extract
ng i18n:<subcommand>
```
or
```
ng i18n-extract
ng i18n-<subcommand>
```
What do you think? May be we already have similar APIs in CLI?

Thank you.

2020-10-23 14:39 UTC, alan-agius4 commented
@AndrewKushnir, initially we were going for `ng i18n-extract` but we realised that currently the builder and the key defined in the users project `angular.json` is already set to `extract-i18n`. In order to avoid users from being confused we decided the align everything and go for `extract-i18n`.

When it comes to migration tool, this to me sounds like it should fall under `ng update` and shouldn't add added as a separate command.

That being said, at the moment we do have a sub-command pattern in the CLI like:

```cmd
ng generate component
ng generate app-shell
```

But then again the infra-structure currently only works for the `ng generate`.

In general if a command will not be used frequently on can opt to use `ng run` instead of `ng command`. 

Example:
```
ng run my-application:server:production
```

The above is how a server bundle is build because there is no command to build a server application like (`ng server`).  

That being said most ng commands can be configured and "mapped" by the users. Example, a user can choose that `ng build` will be mapped to building server application instead of the browser application, or to use a 3rd party builder which builds their application as an electron wrapped application.

This also means, that the users can change the mapping of `ng extract-i18n` (If there is a tool out there that can extract i18n from Angular templates) or maybe create a new builder that wraps the official one, and add functionality on top of that.

2020-10-23 17:05 UTC, AndrewKushnir approved these changes
Thanks for additional clarification @alan-agius4 👍

2020-10-27 12:18 UTC, JoostK approved these changes

2020-10-27 15:42 UTC, mhevery approved these changes
reviewd-for: integration-tests

2020-10-27 15:44 UTC, mhevery approved these changes
reviewed-for: global-approvers

2020-10-27 19:19 UTC, alan-agius4 commented
**Caretaker**: I don't think this requires a g3 pre-submit. Feel free to ruin it if you think otherwise.

2020-10-28 21:42 UTC, closed without merging