fix(ngcc): capture UMD inner class implementation correctly
angular/angular pull request #39346
Opened 2020-10-20 18:39 UTC by petebacondarwin

Previously, UMD class inline declarations of the form:

```ts
exports.Foo = (function() { function Foo(); return Fool; })();
```

were capturing the whole IIFE as the implementation, rather than
the inner class (i.e. `function Foo() {}` in this case). This caused
the interpreter to break when it was trying to access such an export,
since it would try to evaluate the IIFE rather than treating it as a class
declaration.

2020-10-21 12:46 UTC, gkalpak approved these changes
LGTM with a couple of comments:
- It would be cool if we could have an integration test showing all the bits working together (unless it would be too messy).
- Commit message typo: `Fool` --> `Foo` :grin:

2020-10-21 12:46 UTC, gkalpak commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
>          // Inline declarations with an `implementation` should be visited as expressions
This comment could be updated to mention the new requirement or `implementation` being a `ts.Expression`.

2020-10-21 12:46 UTC, gkalpak commented on packages/compiler-cli/ngcc/test/host/umd_host_spec.ts
> +                  `SomeClass = (function() {\n    function SomeClass() {}\n    return SomeClass;\n  }())`,
```suggestion
                  'SomeClass = (function() {\n    function SomeClass() {}\n    return SomeClass;\n  }())',
```

2020-10-21 16:09 UTC, petebacondarwin commented
Hmm, an integration test... Let me look into that. Trouble is that we don't have any UMD packages to test against.

2020-10-21 16:31 UTC, alxhub commented
[Presubmit](http://test/OCL:338278630:BASE:338278645:1603297845685:127d159e)

2020-10-21 17:04 UTC, petebacondarwin commented
@gkalpak - I managed to create an integration test that actually fails without this fix!!

2020-10-21 17:21 UTC, JoostK commented on packages/compiler-cli/ngcc/test/integration/ngcc_spec.ts
> +      // Setup an Angular entry-point in UMD module format has an inline exports declaration
```suggestion
      // Setup an Angular entry-point in UMD module format which has an inline exports declaration
```

2020-10-21 17:21 UTC, JoostK commented on packages/compiler-cli/ngcc/test/integration/ngcc_spec.ts
> +                  core.NgModule({declarations: [exports.FooDirective]})
You can make this more challenging when this is a reference to an inline declaration of an expression.
```suggestion
                  core.NgModule({declarations: exports.declarations})
```

and then have

```ts
exports.declarations = [exports.FooDirective];
```

this was the pattern that broke after the initial fix.

2020-10-21 17:21 UTC, JoostK commented on packages/compiler-cli/ngcc/test/integration/ngcc_spec.ts
> +          .not.toThrow();
I'd extend this to verify that the output files contain AOT output, as this wouldn't currently fail when none of the declarations are found at all.

2020-10-21 20:08 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/integration/ngcc_spec.ts
> +      // Setup an Angular entry-point in UMD module format has an inline exports declaration
I'm going with `that` instead but 🤷

2020-10-21 20:09 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/integration/ngcc_spec.ts
> +                  core.NgModule({declarations: [exports.FooDirective]})
Great! Will do.

2020-10-21 20:09 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/integration/ngcc_spec.ts
> +          .not.toThrow();
Yep - good idea

2020-10-21 21:28 UTC, JoostK requested changes

2020-10-21 21:28 UTC, JoostK commented on packages/compiler-cli/ngcc/test/integration/ngcc_spec.ts
> +              'ɵngcc0.ɵɵsetNgModuleScope(FooModule, { declarations: function () { return [FooDirective]; } });');
Uhm, this looks like a bug w.r.t `FooDirective`, as that won't be declared :( We should refer to it as `exports.FooDirective`

2020-10-21 21:37 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/integration/ngcc_spec.ts
> +              'ɵngcc0.ɵɵsetNgModuleScope(FooModule, { declarations: function () { return [FooDirective]; } });');
Ahah! OMG. I didn't notice....
Hmm, so we appear to be referring to inner class declaration here...
😭

2020-10-22 09:13 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/integration/ngcc_spec.ts
> +              'ɵngcc0.ɵɵsetNgModuleScope(FooModule, { declarations: function () { return [FooDirective]; } });');
Right, so the problem is that in the Angular compiler we refer to classes such as `exports.FooDirective` via a `Reference` object, which gives special meaning to identifiers that "reference" the class.

Then when we are converting the `Reference` to an `R3Reference` the `LocalIdentifierStrategy` makes the assumption that any identifier of a reference is free standing (i.e. it is a single expression in its own right and not the RHS of a property access).  This is why we end up emitting `FooDirective` rather than `exports.FooDirective`.

I think the solution is to get the `LocalIdentifierStrategy` to check whether the reference identifier is actually the child of a property expression, and if so then return that parent expression rather than the identifier itself.

Anyone have any better ideas?

2020-10-22 16:50 UTC, JoostK approved these changes

2020-10-23 16:34 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:338689278:BASE:338689303:1603470826992:87bc035f).

2020-10-23 19:02 UTC, AndrewKushnir commented
FYI, presubmit is successful (I've updated g3 status for this PR).

2020-10-23 19:03 UTC, petebacondarwin commented
Thanks @AndrewKushnir

2020-10-23 22:17 UTC, closed without merging