docs: Document how to turn on strict mode for an existing project.
angular/angular pull request #39412
Opened 2020-10-24 16:40 UTC by chrisjsimpson

Document how to turn on strict mode for an existing project. 

It's just as, if not more likely, developers will want to turn this on for an existing project so it's useful to document how to do that.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

Issue Number: N/A

2020-11-03 20:49 UTC, kapunahelewong reviewed
This is a really nice addition, @chrisjsimpson. Thank you. I've added some docs style-related comments, but we'll still need engineering review.

We try to use code snippets that are part of examples, but I believe json is an exception. So,  in the cases where we do have in-line hardcoded examples, we've been using `<code-example>` rather than code fencing so we can have a header on it. The header includes the file that the person is working in, which helps orient the reader. cc @gkalpak 

Feel free to tag me with any questions.

2020-11-03 20:49 UTC, kapunahelewong commented on aio/content/guide/strict-mode.md
> +#### To enable strict mode for an *existing project*
```suggestion
#### Enabling strict mode for an existing project
```

2020-11-03 20:49 UTC, kapunahelewong commented on aio/content/guide/strict-mode.md
> +Edit your `angular.json` and add `@schematics/angular:application` with `"strict": true` to the `schematics` property:
```suggestion
Edit your `angular.json` by adding `@schematics/angular:application` with `"strict": true` to the `schematics` property as follows.
```

2020-11-03 20:49 UTC, kapunahelewong commented on aio/content/guide/strict-mode.md
> +Edit `compilerOptions` in `tsconfig.json` to include:
```suggestion
Add the following to `compilerOptions` in `tsconfig.json`.
```

2020-11-03 20:49 UTC, kapunahelewong commented on aio/content/guide/strict-mode.md
> +```
```suggestion
<code-example header="tsconfig.json">
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
</code-example>
```

2020-11-03 20:49 UTC, kapunahelewong commented on aio/content/guide/strict-mode.md
> + ```
```suggestion
<code-example header="angular.json">
  ...
  "projects": {
    "app": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:application": {
          "strict": true
        }
      }
   ...
</code-example>
```

2020-11-03 20:49 UTC, kapunahelewong commented on aio/content/guide/strict-mode.md
> +```
```suggestion
<code-example header="tsconfig.json">
  "angularCompilerOptions": {
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
</code-example>
```

2020-11-03 20:49 UTC, kapunahelewong commented on aio/content/guide/strict-mode.md
> +Finally add `"no-any": true` to `rules` in `tslint.json`.
```suggestion
Finally, add `"no-any": true` to `rules` in `tslint.json`.
```

2020-11-04 00:07 UTC, IgorMinar requested changes
overall this looks great @chrisjsimpson! can you please incorporate the review feedback as a fixup commit and rerequest a review? thank you!

2020-11-04 00:07 UTC, IgorMinar commented on aio/content/guide/strict-mode.md
> +Finally add `"no-any": true` to `rules` in `tslint.json`.
`no-any` is no longer part of the strict mode as of v11. Can you please remove this part?

2020-11-04 00:07 UTC, IgorMinar commented on aio/content/guide/strict-mode.md
> +Finally add `"no-any": true` to `rules` in `tslint.json`.
I don't see a mention of stricter bundle budgets, can you please add a mention of updating those?

2020-12-08 12:08 UTC, petebacondarwin commented
@chrisjsimpson - could you address the outstanding comments and squash all the commits into one? Thanks!

2021-04-13 22:15 UTC, AndrewKushnir commented
@alan-agius4 could you please have a quick look at this PR when you get a chance (to double check whether the content is correct given the strict mode changes in CLI)?

2021-04-14 11:09 UTC, alan-agius4 commented
@AndrewKushnir, it looks like this PR is stalled. @IgorMinar's comments are still not addressed.

2021-04-14 16:15 UTC, AndrewKushnir commented
Closing this PR due to the lack of reply. Please reopen if needed.

2021-04-14 16:15 UTC, closed without merging