Update property to disable IntersectionObserver
angular/angular pull request #39429
Opened 2020-10-26 16:40 UTC by mejackreed

Update the property in this documentation to reflect the correct syntax for disabling IntersectionObserver

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-10-26 16:45 UTC, mejackreed commented
@googlebot I signed it!

2020-10-27 00:15 UTC, JiaLiPassion requested changes
@mejackreed, the change LGTM, please update the commit message to match the rule https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

2020-10-27 13:14 UTC, mejackreed commented
Thanks for the review @JiaLiPassion . I have updated the commit message accordingly.

2020-10-27 18:14 UTC, JiaLiPassion approved these changes

2020-10-27 20:33 UTC, closed without merging