fix(core): trigger change detection for hostView
angular/angular pull request #39463
Opened 2020-10-27 22:44 UTC by JiaLiPassion

Close #39462, #36667

In `bootstrap` and `dynamic` components, there is a hostview to contain
the component view, if the component is OnPush, trigger change detection on the
hostview will not check on the OnPush rootComponent,
so we need to mark child components for check.

The cases are:

case 1: AppComponent is OnPush

```
import { Component, NgModule, ViewContainerRef, ComponentFactoryResolver, Injector,
 ChangeDetectionStrategy } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

@Component({
  selector: 'my-app',
  template: `
    {{name}}
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent  {
  name = 'initial value';
  ngOnInit() {

    setTimeout(() => {
      this.name = 'new value'
    }, 2000);
  }
}

@NgModule({
  imports:      [ BrowserModule ],
  declarations: [ AppComponent],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```

case 2: Dynamic component

```
@Component({
  selector: 'dynamic',
  template: `{{name}}`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class Dynamic  {
  name = 'initial name';
}

@Component({
  selector: 'my-app',
  template: `
    <b>Expected</b>: "initial name" changes to "changed name" after 2s<br>
    <b>Actual</b>:<br>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent  {
  constructor(private _vcRef: ViewContainerRef,
     private _cfr: ComponentFactoryResolver, private _injector: Injector) {}

  ngOnInit() {
    const cmptRef = this._cfr.resolveComponentFactory(Dynamic).create(this._injector);
    this._vcRef.insert(cmptRef.hostView);

    setTimeout(() => {
        cmptRef.instance.name = 'changed name';
        console.log('changing name');
        cmptRef.changeDetectorRef.detectChanges();
    }, 2000);
  }
}
```

So in this PR, for `RootViewRef.detectChanges`, we should always markViewDirty for
root component in the hostview.

2020-11-02 18:02 UTC, atscott commented
At the very least, the current approach (by making the component view `CheckAlways`) is going to be a breaking change because it can produce new (valid) `ExpressionChangedAfterItHasBeenCheckedError`. `OnPush` components currently do not throw these errors when they should so by changing the component view to `CheckAlways`, the errors will now be produced. For reference, I had a PR a while back that would address this (#34443) but it is very break-y. This was also [proposed as a project](https://docs.google.com/document/d/1RJ1S4qdlwktm9Bx-3tfyIWE1tPZ-blAaSQrea601gYY/edit#heading=h.yg86x3m6xp64) at some point but must have been lost. I thought it was an item in the planning spreadsheet, but I was either mistaken or it got dropped/lost.

Example test (which passes without your changes but fails with your changes):
```

    it('works', () => {
      @Component({
        template: '{{message}}',
        changeDetection: ChangeDetectionStrategy.OnPush
      })
      class OnPushCmp {
        @Input() message = 'initial';

        ngAfterViewInit() {
          this.message = 'updated';
        }
      }
      const comp = TestBed.configureTestingModule({declarations: [OnPushCmp]}).createComponent(OnPushCmp);
      expect(() => comp.detectChanges()).not.toThrow();
    });
```

2020-11-03 13:10 UTC, JiaLiPassion commented
@atscott, I added a commit to keep the current behavior, so the current behavior is `onPush` component doesn't run `checkNoChanges()` at all, since the `Dirty` flag is cleared after `detectChanges()`, so this commit https://github.com/angular/angular/pull/39463/commits/91e1521f8a3db954539958b49befa35efb415fd8 ignore the `checkNoChanges()` code path if the view is onPush.

2020-11-03 17:45 UTC, atscott requested changes
@JiaLiPassion I'm a little confused by some of the changes in 91e1521 . Is it necessary to add this special case check to so many places? I would have thought that it would only have to affect the root view, but there are changes to `refreshComponent` and `checkNoChangesInternal`.  It would be good to know what tests were failing before - I was trying `yarn bazel test //packages/core/test/acceptance --config=ivy` and all of those tests were still passing if I reverted some of the changes.

In addition, the return value in `isLRootViewAndNoNeedToCheck` for the special case seems to be backwards: since your intent was to skip `OnPush` components when in `checkNoChanges`, then the logical return value should be `true` to indicate that there is "no need to check".  I think it would be better to change the entire function to be `isLRootViewAndNeedsCheck` rather than dealing with how to interpret a double negative.

Lastly, I'm not really convinced that this is the correct solution. The rules for checking a view are correct and logical at the moment - this commit introduces a special path to work around a bug in the current system instead of fixing the root problem that came up.

I think it would also be good to get @mhevery's thoughts on this as well and/or add this to the agenda for our sync.

2020-11-03 21:36 UTC, JiaLiPassion commented
@atscott. 

> I'm a little confused by some of the changes in 91e1521 . Is it necessary to add this special case check to so many places? I would have thought that it would only have to affect the root view, but there are changes to refreshComponent and checkNoChangesInternal.

Yeah, you are right, `refreshComponent` doesn't need to add this logic, I am not sure about `checkNoChangesInternal`, I will check it again.

> In addition, the return value in isLRootViewAndNoNeedToCheck for the special case seems to be backwards: since your intent was to skip OnPush components when in checkNoChanges, then the logical return value should be true to indicate that there is "no need to check". I think it would be better to change the entire function to be isLRootViewAndNeedsCheck rather than dealing with how to interpret a double negative.

Yes, you are right, I updated this part and also added test cases.

> Lastly, I'm not really convinced that this is the correct solution. The rules for checking a view are correct and logical at the moment - this commit introduces a special path to work around a bug in the current system instead of fixing the root problem that came up.

Yeah, I totally understand, so if we want to fix this issue, just like we discussed, I think remove this `special` logic to handle `onPush checkNoChanges()` is the correct behavior, but it will break so many existing applications. I believe this `special handling` make the current behavior the same to give us some time. 
Also I think maybe we can provide a `flag` such like `enableOnPushNoChangeCheck` when bootstrap module to let user use the correct behavior.

2020-11-04 13:19 UTC, JiaLiPassion commented
I created another commit to add a `isOnPushCheckNoChangesEnabled` option to enable `checkNoChanges` for the `OnPush` component https://github.com/angular/angular/pull/39463/commits/4dcf5bdab2cfeded3adafba19329e7772ae217a7

2020-11-04 17:40 UTC, atscott commented on packages/core/src/application_ref.ts
> +  isOnPushCheckNoChangesEnabled?: boolean;
So I think the problem with this flag is that it's really misleading. Enabling this doesn't `'fix'` the issue with `OnPush` components in most cases. It only changes the behavior when the `OnPush` component is the root component. However, it does nothing to fix `checkNoChanges` mode for non-root `OnPush` components, which will _still_ not be checked because their dirty flags have been cleared.

Having this flag is one of the possible solutions to add to a _complete_ fix of the `OnPush` components in `checkNoChanges` mode, but I don't think it should be added for this partial fix because:
* It's misleading, as mentioned above
* It doesn't avoid the extra "special case" logic as discussed in a previous comment on this PR. It actually just adds another condition to the special case logic, which is potentially even more confusing.

Another possible way to avoid the new `ExpressionChanged` errors would be to make them "warnings" if the component is `OnPush` rather than errors.

So I think again, the way forward is:
* First fix the behavior for `OnPush` components in `checkNoChanges` mode in all cases. The options here are numerous for how to approach the `ExpressionChanged` error:
  * Keep it an error and make the change in  a major release. Patch g3 to not produce the error
  * Make it a warning instead
  * Add a flag like you have here to control the behavior
* Ignore the underlying issue and add the special case logic. I think if this option is chosen, we _should not_ add this flag because it just adds to the confusion and special case logic.

Either way, I'll run another presubmit to see if there are other types of failures caused by this change. 

Sorry to keep pushing back on this, but I want to be sure we get it right. In my opinion, this is a pretty significant change. It'll be good to see how others feel about this when we discuss in the team sync.

2020-11-04 18:44 UTC, atscott commented on packages/core/src/application_ref.ts
> +  isOnPushCheckNoChangesEnabled?: boolean;
[presubmit](https://test.corp.google.com/ui#id=OCL:340242567:BASE:340666852:1604511736133:24f3550) is showing several failures and require additional investigation.

2020-11-04 18:51 UTC, JiaLiPassion commented on packages/core/src/application_ref.ts
> +  isOnPushCheckNoChangesEnabled?: boolean;
@atscott , thank you for the review, and you are right, this flag not fixing the whole issue, it only fixed the `dynamic onpush checkNoChanges` issue for now, I will update the commit to try to fix the `normal onpush checkNoChanges` issue too. 

> 
> First fix the behavior for OnPush components in checkNoChanges mode in all cases. The options here are numerous for how to approach the ExpressionChanged error:
> Keep it an error and make the change in a major release. Patch g3 to not produce the error
> Make it a warning instead
> Add a flag like you have here to control the behavior
> Ignore the underlying issue and add the special case logic. I think if this option is chosen, we should not add this flag because it just adds to the confusion and special case logic.

Got it, I think this is reasonable, I will continue to work on it!

> Sorry to keep pushing back on this, but I want to be sure we get it right. In my opinion, this is a pretty significant change. It'll be good to see how others feel about this when we discuss in the team sync.

Yeah, no problem, thank you again for the detailed review, I have added an item in the team sync meeting note.

2020-11-19 19:30 UTC, closed without merging