fix(core): mark Trusted Types as declarations
angular/angular pull request #39471
Opened 2020-10-28 16:21 UTC by bjarkler

Angular-internal type definitions for Trusted Types were added in #39211.
When compiled using the Closure compiler with certain optimization
flags, identifiers from these type definitions (such as createPolicy)
are currently uglified and renamed to shorter strings. This causes
Angular applications compiled in this way to fail to create a Trusted
Types policy, and fall back to using strings.

To fix this, mark the internal Trusted Types definitions as declarations
using the "declare" keyword.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2020-10-28 16:22 UTC, bjarkler commented
[global presubmit](http://test/OCL:339220852:BASE:339419647:1603876838547:84ff1abe)

2020-10-28 16:52 UTC, AndrewKushnir approved these changes
@bjarkler the changes looks good to me, but I've also added @IgorMinar since he reviewed other TrustedTypes-related PRs.

One question that I have is how we can prevent regressions in the future. If we can't catch that with tests, I think it'd be great to add a quick comment explaining that we should keep `declare` to avoid issues with Closure.

Thank you.

2020-10-28 18:10 UTC, bjarkler commented
> One question that I have is how we can prevent regressions in the future. If we can't catch that with tests, I think it'd be great to add a quick comment explaining that we should keep `declare` to avoid issues with Closure.

Good point @AndrewKushnir. We will have integration tests up and running shortly (blocked on pulling in the v11 release of angular-cli, which @IgorMinar is working on). Until then, there's never harm in having better documentation, so I updated the comment blocks to quickly explain why the "declare" keywords are used.

2020-10-28 23:19 UTC, IgorMinar requested changes
thanks @bjarkler, good catch!

I've poked around and realized that the `declare` keyword in front of `type` is meaningless and doesn't change anything with tsickle, `declare` in front of an `interface` causes tsickle to generate an externs for it, which prevents closure from mangling the property name.

Can you please update the PR to remove the `declare` from `type` declarations and keep it only for interfaces? also, can you please update the comment by associating it only with the interfaces.

Thank you.

2020-10-29 00:39 UTC, IgorMinar commented
Actually after reading https://ncjamieson.com/prefer-interfaces/ and discussing this with internal TS team members, it seems that it would be preferable for us to use interfaces everywhere where we can instead of `types`, so could you please try to switch all the types to interfaces and leave the rest as is? thank you

2020-10-29 13:54 UTC, bjarkler commented
Thanks for digging into this @IgorMinar! I've updated the PR based on your suggestions.

2020-10-29 18:15 UTC, IgorMinar approved these changes
LGTM now! thank you!

2020-10-29 18:58 UTC, closed without merging