feat(dev-infra): provide tooling to check what branches a pr targets
angular/angular pull request #39504
Opened 2020-10-29 23:05 UTC by josephperrott

Create a command in the `ng-dev` toolset that allows user's to check
what branches a PR will merge into based on its targeting.

2020-10-30 17:53 UTC, gkalpak requested changes

2020-11-02 18:13 UTC, josephperrott commented on dev-infra/pr/check-target-branches/check-target-branches.ts
> +    throw Error(`Invalid configuration found: ${errors}`);
The distinction I see is that we throw an error, when the configuration fails for the `ng-dev` command itself, however the error log message is that the command executed correctly, it was just targeting a PR which did not have the label required.

2020-11-03 19:02 UTC, gkalpak approved these changes
LGTM :+1:

2020-11-03 19:02 UTC, gkalpak commented on dev-infra/pr/check-target-branches/cli.ts
> +  describe: 'Check a PR to determine what branches it is currently targetting',
Shouldn't it be `targeting` (with one `t`)?

2020-11-03 22:55 UTC, closed without merging