feat: linker compilation of directives
angular/angular pull request #39518
Opened 2020-10-30 22:56 UTC by JoostK

See individual commits.

2020-11-02 12:18 UTC, petebacondarwin commented on packages/compiler-cli/test/compliance/prelink/bootstrap.ts
> + * @returns The file's source content which has been transformed using the linker.
```suggestion
@returns The file's source content, which has been transformed using the linker if necessary.
```

2020-11-02 14:42 UTC, petebacondarwin requested changes
Nice! I love how clean the whole PR feels. It is really easy to follow along with what it does.

2020-11-02 14:42 UTC, petebacondarwin commented on packages/compiler/src/render3/partial/directive.ts
> +  meta.set('static', o.literal(query.static));
All of these except for `predicate` are either optional already (e.g. `read`) or are simple booleans that can be made optional with suitable defaults, yes?

2020-11-02 14:42 UTC, petebacondarwin commented on packages/compiler/src/render3/partial/directive.ts
> +  definitionMap.set('host', compileHostMetadata(meta.host));
If the result of `compileHostMetadata()` is null we should not add this property.

2020-11-02 14:42 UTC, petebacondarwin commented on packages/compiler/src/render3/partial/directive.ts
> +  const attributes = o.literalMap(Object.keys(meta.attributes).map(key => {
The code to add `attributes`, `listeners` and `properties` is very similar. Could we DRY it up by using a helper like:

```ts
function addMapToDefinition(
    definition: DefinitionMap, propertyName: string,
    map: {[key: string]: string|o.Expression}): void {
  const keys = Object.keys(map);
  if (keys.length > 0) {
    const literalMap = o.literalMap(Object.keys(map).map(key => {
      const rawValue = map[key];
      const value = typeof rawValue === 'string' ? o.literal(rawValue) : rawValue
      return {key, value, quoted: true};
    }));
    definition.set(propertyName, literalMap);
  }
}
```

2020-11-02 14:42 UTC, petebacondarwin commented on packages/compiler/src/render3/partial/directive.ts
> +  const attributes = o.literalMap(Object.keys(meta.attributes).map(key => {
Also I wonder whether we always need to quote the key?
I see in `mapToExpression()`, there is:

```ts
quoted: UNSAFE_OBJECT_KEY_NAME_REGEXP.test(minifiedName),
```

2020-11-02 14:42 UTC, petebacondarwin commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +    const def = compileDirectiveFromMetadata(meta, constantPool, makeBindingParser());
Normally `makeBindingParser()` takes the interpolation config, but I guess since directives have no template there is not need to specify interpolation markers, right?
But we should consider this when implementing the component declaration linking.

2020-11-02 14:42 UTC, petebacondarwin commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +  const typeName = metaObj.getValue('type').getSymbolName() ?? 'anonymous';
Is "anonymous" a valid scenario? Perhaps we should throw an error here?
From digging through the code, it looks like this directive type name is used to create names for queries and template functions. I think it would be worth, if not erroring, making sure that this is unique for the given constant pool?

2020-11-02 14:42 UTC, petebacondarwin commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +  const typeName = metaObj.getValue('type').getSymbolName() ?? 'anonymous';
The `type` property is not optional on the `R3DeclareDirectiveMetadata` interface, so it seems unlikely (impossible?) that a directive would be defined as an anonymous class?

2020-11-02 14:42 UTC, petebacondarwin commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +  const range = metaObj.getValue('type').getRange();
BIKESHED: `typeRange`.

2020-11-02 14:42 UTC, petebacondarwin commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +    throw new FatalLinkerError(value.expression, 'Unsupported input, expected exactly two strings');
Might be worth mentioning the other available option here:

```
'Unsupported input property, expected a string or an array containing exactly two strings'
```

2020-11-02 14:42 UTC, petebacondarwin commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +  const sourceFile = new ParseSourceFile(code, sourceUrl);
We will end up creating lots of identical `ParseSourceFile` objects - one for each partial in the source file. I wonder if we ought to have a cache of these somehow? In fact, the `PartialDirectiveLinkerVersion1` would be a suitable place to hold this cache, since its life is the same as the plugin.

2020-11-02 14:42 UTC, petebacondarwin commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_linker_selector.ts
>  export class PartialLinkerSelector<TStatement, TExpression> {
You can remove the `TStatement` here too.

2020-11-02 14:45 UTC, petebacondarwin commented
Also, I am not sure whether these commits should be `feat` or `refactor`... In any case, I think that the 3rd commit message should probably reworded slightly:

```
feat(compiler-cli): implement partial directive declaration linking 

This commit implements the logic to compile a partial declaration of a
directive into its full AOT compilation output.
```

2020-11-02 16:05 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
> +  }
Works for me, done!

2020-11-02 16:06 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/directive.ts
> +      resolution: Readonly<unknown>): CompileResult|CompileResult[] {
Switched to `CompileResult[]`. The interface declares the union type, so my IDE copied that when implementing the method.

2020-11-02 16:07 UTC, JoostK commented on packages/compiler/src/render3/partial/api.ts
> +  version: 1;
Yes, but doing that now would also require changes to the selector logic etc. which I felt was better left for another PR.

2020-11-02 16:10 UTC, petebacondarwin commented on packages/compiler/src/render3/partial/api.ts
> +  version: 1;
OK

2020-11-02 16:24 UTC, JoostK commented on packages/compiler/src/render3/partial/api.ts
> +  // Map of inputs, keyed by the name of the input field.
I'm surprised these descriptions are different in the first place; I copied this interface from the spike code, but I'm not sure how that one was put together. Tweaked the text a bit, also in `R3DirectiveMetadata`, to hopefully make it more clear.

2020-11-02 16:25 UTC, JoostK commented on packages/compiler/src/render3/partial/api.ts
> +  usesInheritance: boolean;
I wasn't sure about these and left all booleans as required. I'm fine with changing them to a sane default, though.

2020-11-02 16:28 UTC, JoostK commented on packages/compiler/src/render3/partial/api.ts
> +  // to all Angular exports, including Ivy instructions.
Changed all of these.

2020-11-02 16:29 UTC, JoostK commented on packages/compiler/src/render3/partial/directive.ts
> +export function baseDirectivePartialCompile(meta: R3DirectiveMetadata): DefinitionMap {
This was mirrored from the full AOT compiler. I like `createDirectiveDefinitionMap`, going with that.

2020-11-02 16:29 UTC, JoostK commented on packages/compiler/src/render3/partial/directive.ts
> +  definitionMap.set('version', o.literal(1));
Leaving for future PR.

2020-11-02 16:30 UTC, JoostK commented on packages/compiler/src/render3/partial/directive.ts
> +  definitionMap.set('providers', meta.providers);
Actually `DefinitionMap` has a trick up its sleeve:

https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/compiler/src/render3/view/util.ts#L151

so passing in null here does in fact result in not having that property.

2020-11-02 16:31 UTC, JoostK commented on packages/compiler/src/render3/partial/directive.ts
> +  definitionMap.set('usesOnChanges', o.literal(meta.lifecycle.usesOnChanges));
Done.

2020-11-02 16:35 UTC, JoostK commented on packages/compiler/src/render3/partial/directive.ts
> +  meta.set('static', o.literal(query.static));
Correct. Done.

2020-11-02 16:35 UTC, JoostK commented on packages/compiler/src/render3/partial/directive.ts
> +  definitionMap.set('host', compileHostMetadata(meta.host));
It won't as mentioned before.

2020-11-02 16:46 UTC, JoostK commented on packages/compiler/src/render3/partial/directive.ts
> +  const attributes = o.literalMap(Object.keys(meta.attributes).map(key => {
`mapToExpression` is careful about only using quotes when needed, as non-quoted keys will be subject to Closure's minification which is desirable here, to correspond with the minification done to the respective class properties. We don't need that here so I choose to always use quotes.

I did refactor the logic of transforming an object literal into an object literal expression a bit, but a bit differently to what you suggested.

2020-11-02 16:47 UTC, JoostK commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +    const def = compileDirectiveFromMetadata(meta, constantPool, makeBindingParser());
Good point, yes indeed this becomes relevant for components.

2020-11-02 16:47 UTC, JoostK commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +  const typeName = metaObj.getValue('type').getSymbolName() ?? 'anonymous';
Yes I agree this case should throw instead of the magic anonymous name.

2020-11-02 16:52 UTC, JoostK commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +  const range = metaObj.getValue('type').getRange();
Instead of painting the bikeshed I tore it down; inlined this variable into its only usage. 🚲🏠

2020-11-02 16:52 UTC, JoostK commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +    throw new FatalLinkerError(value.expression, 'Unsupported input, expected exactly two strings');
Done

2020-11-02 16:55 UTC, JoostK commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +  const sourceFile = new ParseSourceFile(code, sourceUrl);
I don't follow. All these calls would be unique per type, no?

2020-11-02 16:56 UTC, JoostK commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_linker_selector.ts
>  export class PartialLinkerSelector<TStatement, TExpression> {
Done.

2020-11-02 17:46 UTC, petebacondarwin commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +  const sourceFile = new ParseSourceFile(code, sourceUrl);
My suggestion is that we have a map of `sourceUrl` to `ParseSourceFile` stored somewhere. There could be a map per partial linker (or better per `PartialLinkerSelector` - or perhaps even passed through to that from the `FileLinker`?)

Then this function would either be moved inside the partial linker of have the map passed to it.

2020-11-02 18:36 UTC, JoostK commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +  const sourceFile = new ParseSourceFile(code, sourceUrl);
Oh, I was confusing this to be about the `ParseSourceSpan`, but it's just the file. I don't think it's a concern that we need to have a cache for these; they are effectively free and will be GC'd after the metadata has been compiled (practically immediately). I'd rather leave as-is.

2020-11-02 18:56 UTC, petebacondarwin commented on packages/compiler-cli/linker/src/file_linker/partial_linkers/partial_directive_linker_1.ts
> +  const sourceFile = new ParseSourceFile(code, sourceUrl);
Yeah - fair enough

2020-11-02 21:04 UTC, petebacondarwin approved these changes
LGTM!

2020-11-02 21:13 UTC, JoostK commented on packages/compiler/src/render3/partial/directive.ts
> +  if (query.descendants) {
I would guess that `ViewChild` is most common, but honestly I have no idea what the distribution actually is.

I did consider basically this question but then for the `first` flag, which I suspect is more often `true` than `false`. But it did indeed feel simpler/more consistent to go with `false` as a default here.

2020-11-02 23:33 UTC, jessicajaniuk approved these changes
This looks really clean to me! LGTM!

2020-11-03 08:20 UTC, petebacondarwin approved these changes
Reviewed-for: public-api

2020-11-03 19:31 UTC, AndrewKushnir commented on goldens/public-api/core/core.d.ts
> +export declare function $ngDeclareDirective(decl: unknown): unknown;
Just curious if we can use `ɵɵ` here (i.e. `ɵɵngDeclareDirective`)?

2020-11-03 19:35 UTC, JoostK commented on goldens/public-api/core/core.d.ts
> +export declare function $ngDeclareDirective(decl: unknown): unknown;
The `$ng` dollar syntax is as originally proposed by @alxhub. I suppose it's to make the linker more rigid in detecting these calls at link-time.

2020-11-03 19:43 UTC, AndrewKushnir commented on goldens/public-api/core/core.d.ts
> +export declare function $ngDeclareDirective(decl: unknown): unknown;
Thanks for additional information @JoostK!

I'd vote for a consistent way to annotate such APIs with `ɵ`s :) If there are advantages of using a different prefix - may be we can document it in the code somewhere (in the `ngDeclareDirective ` function docs) so that we can refer to it?

2020-11-03 20:40 UTC, JoostK commented on goldens/public-api/core/core.d.ts
> +export declare function $ngDeclareDirective(decl: unknown): unknown;
Your vote has been recorded and will be included in the final count. Due to the large number of votes by mail during this election, it might take a while to count them all.

Just kidding; I had a chat with Alex and we did end up changing the function to use `ɵɵ` as prefix.

2020-11-03 20:47 UTC, AndrewKushnir commented on goldens/public-api/core/core.d.ts
> +export declare function $ngDeclareDirective(decl: unknown): unknown;
Thanks @JoostK 😄

2020-11-03 20:50 UTC, AndrewKushnir commented
After changing `$ng` prefix to `ɵɵ` one it looks like `public-api` group approval is not needed for this PR.

2020-11-03 21:58 UTC, alxhub approved these changes

2020-11-03 22:03 UTC, petebacondarwin commented on packages/compiler/src/render3/partial/api.ts
> +  usesInheritance: boolean;
Actually, I think it is quite relevant. Some libraries (e.g. Material) might contain many many directives and components. While the final application production code will not contain this, there is a cost both in space and parse time, etc for the published library code.

2020-11-04 02:18 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:340562894:BASE:340562903:1604456308358:2278dbc).

2020-11-04 17:30 UTC, AndrewKushnir commented
FYI, presubmit is successful, I'm removing the "presubmit" label.

2020-11-04 18:44 UTC, closed without merging