fix(common): cleanup location change listeners when the root view is removed
angular/angular pull request #39570
Opened 2020-11-04 22:01 UTC by arturovt

## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #31546

In the current behavior Angular doesn't cleanup `popstate` and `hashchange` event listeners when the root view gets destroyed when calling `ngModuleRef.destroy()`. This entails duplicating event handlers every time the application is bootstrapped again.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## Other information

2020-11-09 16:13 UTC, petebacondarwin requested changes
Nice PR thanks @arturovt!

This also changes the public API for methods on the `PlatformLocation` class. So that will need to have its public-api golden files updated too. I was wondering whether this could be made non-breaking by making the return values of `onPopState()` and `onHashChange()` in the `PlatformLocation` classes optionally `void`. For example:

```ts
onPopState(fn: LocationChangeListener): void|() => void;
```

And then the `LocationStrategy` classes would need to check that the return value was not undefined before adding it to the list of listeners. But then I felt that this would lead to unclear behaviour for scenarios where someone had created their own subclass of `PlatformLocation`, so I think it is probably best to go with the breaking change.

In any case we need to update the documentation of `PlatformLocation` to ensure that the new return value is described.

Can you also fix the commit message. It appears to be all on one line. See the [CI job failure](https://app.circleci.com/pipelines/github/angular/angular/24301/workflows/eb37ec51-241f-4dcd-91e2-4606feef6543/jobs/852496). The commit message would also need a BREAKING CHANGE block to describe the change to the return types of the `OnPopState` etc methods.

This change also increases the size of applications so you need to update the size tracking files at `goldens/size-tracking/integration-payloads.json` and goldens/size-tracking/aio-payloads.json. See [CI job failure 1](https://app.circleci.com/pipelines/github/angular/angular/24301/workflows/eb37ec51-241f-4dcd-91e2-4606feef6543/jobs/852495) and [CI job failure 2](https://app.circleci.com/pipelines/github/angular/angular/24301/workflows/eb37ec51-241f-4dcd-91e2-4606feef6543/jobs/852507).

Let me know if you need any help here.

2020-11-10 00:25 UTC, arturovt commented
@petebacondarwin thanks for the response! I've made changes to update the size of tracking files and also updated commit message with BREAKING CHANGE, but seems like the `lint` job is still unhappy :grin:

2020-11-10 09:14 UTC, petebacondarwin requested changes
I think the problem with the linting is that the lines in the commit message body are still too long.

2020-11-10 09:14 UTC, petebacondarwin commented on packages/common/src/location/location_strategy.ts
> +      ɵɵinject(PlatformLocation as any), (location && location.origin) || '');
Is this change needed?

2020-11-10 09:14 UTC, petebacondarwin commented on packages/common/src/location/location_strategy.ts
> +    this._removeListenerFns.forEach(fn => fn());
I'm not sure but to be on the safe side, it might be a good idea to clear the `_removeListenerFns ` array to help with garbage collection. Similarly in other `ngOnDestroy` methods in this PR.

2020-11-10 12:18 UTC, arturovt commented on packages/common/src/location/location_strategy.ts
> +      ɵɵinject(PlatformLocation as any), (location && location.origin) || '');
No, it was made automatically when I ran `yarn ng-dev format changed`.

2020-11-10 13:11 UTC, arturovt commented on packages/common/src/location/location_strategy.ts
> +    this._removeListenerFns.forEach(fn => fn());
Makes sense. I've updated PR with settings `removeListenerFns` to an empty array `[]` in all `ngOnDestroy` methods.

2020-11-10 13:12 UTC, petebacondarwin commented on packages/common/src/location/location_strategy.ts
> +      ɵɵinject(PlatformLocation as any), (location && location.origin) || '');
/shrug!

2020-11-10 13:13 UTC, petebacondarwin approved these changes
LGTM! Thanks @arturovt for your patience.

2020-11-12 19:46 UTC, atscott approved these changes
[presubmit](https://test.corp.google.com/ui#id=OCL:342094093:BASE:342094135:1605209917494:883e998a)

2020-11-12 19:46 UTC, atscott commented on packages/router/test/bootstrap.spec.ts
> +
nit: The call to `ngOnDestroy` actually isn't important. What we really care about is that the listeners are removed, but we don't care _how_ that happens. I would rename this test and remove this assertion.

2020-11-16 21:51 UTC, mhevery approved these changes

2020-11-16 21:51 UTC, mhevery commented on packages/common/src/location/hash_location_strategy.ts
> +    this._removeListenerFns = [];
```suggestion
    while (this._removeListenerFns.length) {
      this._removeListenerFns.pop()();
    }
```

I think the above is better because if `fn` throws exception than this is left in inconsistent state. Where as with the above change it is clear what to do next.

2020-11-16 21:52 UTC, mhevery reviewed
reviewed-for: global-approvers

2020-11-16 21:53 UTC, mhevery approved these changes
reviewed-for: global-approvers

2020-11-16 22:15 UTC, atscott requested changes

2020-11-16 22:15 UTC, atscott commented on packages/common/src/location/platform_location.ts
> +  abstract onPopState(fn: LocationChangeListener): () => void;
Please add documentation indicating what this returned function is. There wasn't as much need before since it was void, but now we need to be clear about what classes should be returning from this function. I know it's in the release notes and PR description, but it should also be added here.

2020-11-16 22:15 UTC, mary-poppins commented
You can preview c740d63 at https://pr39570-c740d63.ngbuilds.io/.
You can preview fa3097b at https://pr39570-fa3097b.ngbuilds.io/.
You can preview 82cb8a0 at https://pr39570-82cb8a0.ngbuilds.io/.
You can preview 54fbbfc at https://pr39570-54fbbfc.ngbuilds.io/.
You can preview e87f8a4 at https://pr39570-e87f8a4.ngbuilds.io/.
You can preview 67ea52e at https://pr39570-67ea52e.ngbuilds.io/.

2020-11-18 13:19 UTC, mary-poppins commented
You can preview ce3c7b0 at https://pr39570-ce3c7b0.ngbuilds.io/.

2020-11-18 14:36 UTC, mary-poppins commented
You can preview 90883ff at https://pr39570-90883ff.ngbuilds.io/.

2020-11-18 16:49 UTC, arturovt commented on packages/common/src/location/platform_location.ts
> +  abstract onPopState(fn: LocationChangeListener): () => void;
Updated.

2020-12-08 21:58 UTC, atscott approved these changes
reviewed-for: size-tracking
reviewed-for: public-api

2020-12-08 21:59 UTC, atscott commented
@arturovt looks like this needs a rebase but otherwise has the necessary approvals

2020-12-09 05:56 UTC, mary-poppins commented
You can preview f5adf98 at https://pr39570-f5adf98.ngbuilds.io/.

2020-12-09 06:37 UTC, mary-poppins commented
You can preview c664c05 at https://pr39570-c664c05.ngbuilds.io/.

2020-12-09 20:14 UTC, mary-poppins commented
You can preview e11e1a4 at https://pr39570-e11e1a4.ngbuilds.io/.

2021-02-16 21:51 UTC, atscott commented
Replaced by #40867

2021-02-16 21:51 UTC, closed without merging