(docs|fix): update links, use HTTPS as protocol
angular/angular pull request #39718
Opened 2020-11-16 21:46 UTC by Marcono1234

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Documentation, code comments and example and test code is using HTTP for links and URLs despite the target sites supporting HTTPS. When the user then opens the site, the browser first tries to create an unencrypted connection. An adversary in the same local network could abuse this.

## What is the new behavior?

The links have been updated where the target site supports HTTPS (and is correctly configured); some links have been updated to their current redirect destination.

Note that this pull request might have missed a few cases. Additionally it is a draft for now to make sure that it does not break anything (since there are also a few code changes).
Though I do not mind if you think this effort is not worth it. Also feel free to pick the relevant edits from the pull request then, or let me know if you want something to be changed, or if you want this pull request to be split.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

I hope not.

2020-11-16 21:55 UTC, Marcono1234 commented on aio/content/guide/security.md
> +Google Developers website.
Not sure if the wording here is good. The reason for this change is that http://www.html5rocks.com/en/tutorials/security/content-security-policy/ redirects to the Google Developers site.

2020-11-16 21:55 UTC, Marcono1234 commented on aio/content/guide/deployment.md
> +[here](https://stackoverflow.com/a/26152011):
I have removed the user ID at the end. Could be added again if that user wants [badges](https://meta.stackoverflow.com/a/277770) 😄

2020-11-16 21:55 UTC, Marcono1234 commented on aio/content/guide/forms.md
> +6. The sample form uses some style classes from [Twitter Bootstrap](https://getbootstrap.com/css/): `container`, `form-group`, `form-control`, and `btn`.
Maybe this could also be changed to https://getbootstrap.com/, or a different link, in case this applies to version 4 as well. The current link leads to version 3.4.

2020-11-17 15:48 UTC, gbumanzordev approved these changes

2020-11-17 20:21 UTC, gkalpak reviewed
This is amazing, @Marcono1234 ❤️
I could help taking a look, even if it's in draft state 😇

2020-11-17 20:21 UTC, gkalpak commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> + * An injectable [HammerJS Manager](https://hammerjs.github.io/api/#hammer-manager)
This doesn't work for me. `#hammermanager` (without the hyphen) does:

```suggestion
 * An injectable [HammerJS Manager](https://hammerjs.github.io/api/#hammermanager)
```

2020-11-17 20:21 UTC, gkalpak commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> +   * Creates a [HammerJS Manager](https://hammerjs.github.io/api/#hammer-manager)
This doesn't work for me. `#hammermanager` (without the hyphen) does:

```suggestion
 * An injectable [HammerJS Manager](https://hammerjs.github.io/api/#hammermanager)
```

2020-11-17 20:21 UTC, gkalpak commented on aio/content/guide/animations.md
> +Check out this full animation [demo](https://animationsftw.in/#/) with accompanying [presentation](https://www.youtube.com/watch?v=JhNo3Wvj6UQ&feature=youtu.be&t=2h47m53s), shown at the AngularConnec
Unfortunately, animationsftw.in seems to be permanently down. So, we should remove that particular link (or maybe link to the [source code][1]). 

[1]: https://github.com/matsko/animationsftw.in

2020-11-17 20:22 UTC, gkalpak commented on aio/content/guide/security.md
> +Google Developers website.
I think "Web Fundamentals guide" is better. Other than that, everything sounds good to me.

2020-11-18 00:21 UTC, Marcono1234 commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> + * An injectable [HammerJS Manager](https://hammerjs.github.io/api/#hammer-manager)
Good that you spotted this! I have used the links from the table of contents at the top, but it appears they are broken (https://github.com/hammerjs/hammerjs.github.io/issues/66)

2020-11-18 00:27 UTC, Marcono1234 commented on aio/content/guide/animations.md
> +Check out this full animation [demo](https://animationsftw.in/#/) with accompanying [presentation](https://www.youtube.com/watch?v=JhNo3Wvj6UQ&feature=youtu.be&t=2h47m53s), shown at the AngularConnec
Hmm, maybe I changed this link then by accident without checking if the site is still online. Though https://webcache.googleusercontent.com/search?q=cache:RcgBJMgFQu0J:https://animationsftw.in/ suggests it was still online 8 days ago (unless I am misinterpreting that cached site), so maybe it went down in the last hours?

2020-11-18 17:37 UTC, Marcono1234 commented on aio/tools/examples/shared/boilerplate/cli/.gitignore
> +# See https://help.github.com/ignore-files/ for more about ignoring files.
Do you want me to normalize trailing `/` in some way?
For example for https://ng-lightning.github.io/ng-lightning it redirects (HTTP 301) to the same page with a trailing `/`, so I am not sure if trying to perform any normalization regarding trailling `/` is really worth it.

2020-11-18 17:37 UTC, Marcono1234 commented on docs/DEVELOPER.md
> +* [Node.js](https://nodejs.org), (version specified in the engines field of [`package.json`](../package.json)) which is used to run a development web server,
Do you want in general a trailing `/` if the URL has no path?

2020-11-18 17:47 UTC, Marcono1234 commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> +   * Creates a [HammerJS Manager](https://hammerjs.github.io/api/#hammer-manager)
Looks like there is a copy-paste error (you also changed the start of the line); I will revert that in a subsequent commit.

2020-11-18 18:10 UTC, Marcono1234 commented
I have force-pushed to fix a merge conflict by rebasing onto `master`; maybe it would have been better to merge `master` in instead, sorry.

I can also squash the commits at the end, but for now I think having them separate makes it easier to see the changes.

2020-11-18 18:19 UTC, gkalpak commented on packages/platform-browser/src/dom/events/hammer_gestures.ts
> +   * Creates a [HammerJS Manager](https://hammerjs.github.io/api/#hammer-manager)
Ooops 😇

2020-11-18 18:23 UTC, gkalpak commented on aio/tools/examples/shared/boilerplate/cli/.gitignore
> +# See https://help.github.com/ignore-files/ for more about ignoring files.
Yeah, I wouldn't bother tbh 😅 (It's doesn't make a difference anyway.)

<sub>
Just to give some context:<br />
Personally, I like to strip trailing `/`, unless the whole path is just `/`. But this is more of a personal preference, not really useful in any way :grin:<br />
<br />
I just commented, because I thought you were doing that too, but then I realized you probably weren't, so I refrained from commenting on all occurences.
</sub>

2020-11-18 18:24 UTC, gkalpak commented on docs/DEVELOPER.md
> +* [Node.js](https://nodejs.org), (version specified in the engines field of [`package.json`](../package.json)) which is used to run a development web server,
No need to bother with that (see https://github.com/angular/angular/pull/39718#discussion_r526322351).

2020-11-18 19:05 UTC, Marcono1234 commented on aio/tools/examples/shared/boilerplate/cli/.gitignore
> +# See https://help.github.com/ignore-files/ for more about ignoring files.
Ok thanks for the insight, I will leave it as is then. I mostly copied the final target URL after any redirects, which is also why some had `/#/` as path / fragment.

2020-11-18 19:40 UTC, mary-poppins commented
You can preview e9fab14 at https://pr39718-e9fab14.ngbuilds.io/.
You can preview 700d266 at https://pr39718-700d266.ngbuilds.io/.
You can preview 6f1cfbd at https://pr39718-6f1cfbd.ngbuilds.io/.

2020-11-18 20:00 UTC, gkalpak requested changes
Thx, @Marcono1234! One last comment and this should be good to go 🚀 

We prefer rebasing over merging, so force-pushing to a PR branch is fine :wink:

You are right that we will need the commits squashed eventually. A better way to keep incremental changes separate is using fixup commits. See [here][1] for more details. At this point, you could squash your existing commits into one and add any new changes to a fixup commit (so they are easier to review).

[1]: https://github.com/angular/angular/blob/cc509d609f2bb729820792b4ba751c2534702a97/CONTRIBUTING.md#addressing-review-feedback

2020-11-18 21:40 UTC, Marcono1234 commented
Thanks! I was not aware that Git offered a fixup feature. I have now squashed all review feedback changes into a single fixup commit, hopefully that is alright and useful.

2020-11-18 21:50 UTC, mary-poppins commented
You can preview 8eb8896 at https://pr39718-8eb8896.ngbuilds.io/.

2020-11-19 10:43 UTC, gkalpak requested changes
One last comment about (sorry I keep finding them one by one 😇).

Also, there are some lint/test failures that need to be fixed. You can see the CI logs for more details, but from a quick look the following need to be fixed:

- There are some more occurrances of `http://g.co/ng/security#xss` (without `https`) in test assertions. These have to be changes to match the actual messages (i.e. with `https`).

- `packages/core/src/render3/i18n/i18n_parse.ts` is not formatted to the formatters taste. You can fix it by running `yarn ng-dev format files packages/core/src/render3/i18n/i18n_parse.ts`

- The commit message does not follow our [commit message guidelines](https://github.com/angular/angular/blob/1d9e56eba06958e37ef8062ae7b65afa85f90632/CONTRIBUTING.md#commit). You can use something like:

  > docs: update links to use HTTPS as protocol

##
Tha again for all the work you've put into this, @Marcono1234 ❤️
It's a big one, but hopefully we're really close.

(LMK if you need any help with fixing the CI failures.)

2020-11-19 10:43 UTC, gkalpak commented on aio/content/guide/animations.md
> +Check out this this [presentation](https://www.youtube.com/watch?v=rnTK9meY5us), shown at the AngularConnect conference in November 2017, and the accompanying [source code](https://github.com/matsko/
```suggestion
Check out this [presentation](https://www.youtube.com/watch?v=rnTK9meY5us), shown at the AngularConnect conference in November 2017, and the accompanying [source code](https://github.com/matsko/animationsftw.in).
```

2020-11-19 18:21 UTC, Marcono1234 commented on packages/core/src/render3/i18n/i18n_parse.ts
> +                        `(see https://g.co/ng/security#xss)`);
The `format` task wanted to wrap this in a weird way:
```ts
console.warn(
    `WARNING: ignoring unsafe attribute value ` +
    `${lowerAttrName} on element ${
        tagName} (see https://g.co/ng/security#xss)`);
```

I am not really familiar with TypeScript, but that did not look right to me so I manually wrapped it instead.

2020-11-19 19:18 UTC, gkalpak commented on packages/core/src/render3/i18n/i18n_parse.ts
> +                        `(see https://g.co/ng/security#xss)`);
You should never argue with the formatter 😛
Your way is fine too, though, so heppy to go with that (as long as the formatter is happy).

2020-11-19 19:22 UTC, gkalpak approved these changes
:tada:

Reviewed-for: global-docs-approvers

2020-11-19 19:25 UTC, gkalpak commented
@googlebot I consent.

2020-11-19 19:30 UTC, gkalpak approved these changes
Reviewed-for: dev-infra, global-docs-approvers

2020-11-19 19:30 UTC, mhevery approved these changes
reviewed-for: integration-tests

2020-11-19 19:44 UTC, IgorMinar approved these changes
wow.. nice cleanup. thank you, @Marcono1234!

Reviewed-for: global-approvers

2020-11-19 20:47 UTC, Marcono1234 commented
No problem and thanks for the review comments!

It appears the CircleCI "Details" links require you to authenticate with your GitHub account, even though you just want to see the build logs. This is rather cumbersome, especially since CircleCI requests quite a lot permissions<sup>1</sup>. Is this something you can control and potentially turn off?

---

1: Requested permissions:
- "This application will be able to read and write all public repository data."
- "This application will be able to read your organization, team membership, and private project boards."

2020-11-20 09:21 UTC, gkalpak commented
Unfortunately that is not something we control 😞
We have raised it with CircleCI, so it's on them to fix it.

2020-11-20 20:52 UTC, closed without merging