feat(router): add `relativeTo` as an input to `routerLink`
angular/angular pull request #39720
Opened 2020-11-16 23:45 UTC by atscott

Allow configuration of `relativeTo` in the `routerLink` directive. This
is related to the clearing of auxiliary routes, where you need to use
`relativeTo: route.parent` in order to clear it from the activated
auxiliary component itself. This is because `relativeTo: route` will
consume the segment that we're trying to clear, so there is really no
way to do this with routerLink at the moment.

Related issue: #13523
Related (internal link): https://yaqs.corp.google.com/eng/q/5999443644645376

2020-11-17 14:02 UTC, petebacondarwin requested changes

2020-11-17 14:02 UTC, petebacondarwin commented on packages/router/src/directives/router_link.ts
> +  @Input() relativeTo?: ActivatedRoute|null;
I think it would be really helpful to explain the use case for which this has been added in the docs.

2020-11-17 14:02 UTC, petebacondarwin commented on packages/router/test/integration.spec.ts
> +         expect(link.nativeElement.getAttribute('href')).toEqual('root/childRoot');
The tests indicate that the href is absolute - i.e. `/root/childRoot`.

2020-11-17 17:54 UTC, atscott commented on packages/router/src/directives/router_link.ts
> +      relativeTo: this.relativeTo !== undefined ? this.relativeTo : this.route,
There's a difference here between `undefined` and `null`. In order to preserve current behavior, `undefined` must mean "use `this.route`" whereas `undefined` in `router.createUrlTree` would mean `routerState.root`. These are two different things.

2020-11-17 17:54 UTC, atscott commented on packages/router/src/directives/router_link.ts
> +  @Input() relativeTo?: ActivatedRoute|null;
Added some docs here as well as in `router.createUrlTree`.

2020-11-25 00:20 UTC, AndrewKushnir approved these changes
LGTM 👍  Just a couple comments to add some notes on `undefined` vs `null` values.

Reviewed-for: public-api

2020-11-25 00:20 UTC, AndrewKushnir commented on packages/router/src/directives/router_link.ts
> +  @Input() relativeTo?: ActivatedRoute|null;
I noticed that the `undefined` case is covered by the docs above, but the `null` case doesn't. Can we add a note on the `null` values here as well?

2020-11-25 00:20 UTC, AndrewKushnir commented on packages/router/src/directives/router_link.ts
> +      relativeTo: this.relativeTo !== undefined ? this.relativeTo : this.route,
I'd propose adding a quick comment to the code here to document the difference between handling `null` and `undefined` (that we specifically check for `undefined`, but not `null`).

2020-11-25 00:34 UTC, atscott commented on packages/router/src/directives/router_link.ts
> +  @Input() relativeTo?: ActivatedRoute|null;
I only covered `undefined` because it's the only value that's interpreted as a special case here. Otherwise, users should refer to the docs for `UrlCreationOptions`. I don't feel like it's necessary to copy all the documentation there to here. That said, the documentation there was lacking a definition for `null` and `undefined` so I updated it.

2020-11-25 00:34 UTC, atscott commented on packages/router/src/directives/router_link.ts
> +      relativeTo: this.relativeTo !== undefined ? this.relativeTo : this.route,
Done.

2020-11-25 00:41 UTC, AndrewKushnir commented on packages/router/src/directives/router_link.ts
> +  @Input() relativeTo?: ActivatedRoute|null;
Cool, thanks @atscott 👍

2020-11-25 17:00 UTC, petebacondarwin approved these changes

2020-11-25 17:01 UTC, petebacondarwin approved these changes
Reviewed-for: public-api

2020-11-25 21:05 UTC, jelbourn reviewed
We should add docs for this in the same PR

2020-11-25 21:05 UTC, jelbourn commented on goldens/public-api/router/router.d.ts
> +    relativeTo?: ActivatedRoute | null;
Are there cases where someone would want to put a string here?

2020-12-01 18:52 UTC, atscott commented on goldens/public-api/router/router.d.ts
> +    relativeTo?: ActivatedRoute | null;
`string` is not supported for `relativeTo`, see docs here: https://angular.io/api/router/UrlCreationOptions#relativeTo.

2020-12-07 23:41 UTC, jelbourn approved these changes
LGTM

Reviewed-for: public-api

2020-12-10 19:21 UTC, closed without merging