docs: edit attribute-directives.md
angular/angular pull request #39849
Opened 2020-11-25 21:57 UTC by kapunahelewong

Copy edit of `attribute-directives.md`. Moves to task-based. 

To do: Need to find places for commented out sections at the end.

2020-11-30 16:17 UTC, mary-poppins commented
You can preview 1439909 at https://pr39849-1439909.ngbuilds.io/.

2020-12-09 20:42 UTC, mhevery approved these changes
LGTM with one suggestion / cleanup.

I reviewed for logical correctness, and it LGTM. I did not review for grammar.

2020-12-09 20:42 UTC, mhevery commented on aio/content/guide/attribute-directives.md
> +## Rendering code in the browser with `ngNonBindable`
```suggestion
## Disabling interpolation, directives and binding with  `ngNonBindable`
```

I don't think "Rendering code" is what is actually being done here so I don't think it is the right title. I think a better title is "disabling" something. Such as "interpolation" etc...

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
> +With attribute directives, you can change the appearance or behavior of DOM elements.
is it worth calling out components here too? E.g.

```suggestion
With attribute directives, you can change the appearance or behavior of DOM elements and Angular components.
```

Not sure about this but I want people to be clear that it is not just native DOM elements that receive directives.

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
> +  The `@Directive()` decorator's only configuration property specifies the directive's CSS attribute selector, `[appHighlight]`.
I think only suggests that there are no other options available, which is not the case.
Arguably, `lone` was more accurate. But if that is deemed to unusual to use for non-native speakers, then I would just remove the word altogether.

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
> +This section shows you how to detect when a user mouses into or out of the element and respond by setting or clearing the highlight color.
```suggestion
This section shows you how to detect when a user mouses into or out of the element and to respond by setting or clearing the highlight color.
```

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
> +1. In `highlight.directive.ts`, import `Input` from `@angular/core`.
Sometimes you say `from '@angular/core'` but other times not (e.g. "Import `HostListener`).
Should this be consitent?

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
>  <code-example path="attribute-directives/src/app/highlight.directive.2.ts" header="src/app/highlight.directive.ts"></code-example>
Note that this file (`attribute-directives/src/app/highlight.directive.2.ts`) also contains `Input` bindings. So perhaps it is needs modifying?

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
>  <code-example path="attribute-directives/src/app/highlight.directive.2.ts" header="src/app/highlight.directive.ts"></code-example>
Also that file contains a number of regions that are no longer referenced (AFAICT) so we should remove those.

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
> +1. To bind to the `AppComponent.color` and fall back to "violet" as the default color, add the following HTML.
Is it worth noting that in this case the binding is "static" i.e. it doesn't use the `[...]` square brackets. A beginner reading this might be confused that one attribute uses `[]` and the other doesn't...

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
> +  As with components, you can add as many directive property bindings as you need by adding them to the host element in the template.
```suggestion
  As with components, you can add as many directive property bindings as you need by adding attributes to the host element in the template.
```

??

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
> +When the user chooses a color the selected color becomes the default.
"becomes the default" doesn't seem quite right to me. The default is still red, the chosen color is becomes the active highlight color.

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
> +## Rendering code in the browser with `ngNonBindable`
"DIsabling Angular processing with `NgNonBindable`"?

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
> +Applying `ngNonBindable` to an element stops binding at that element, including child elements.
As I understand it `ngNonBindable` only stops Angular for child elements, not the element where it appears.

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
> +Applying `ngNonBindable` to an element stops binding at that element, including child elements.
E.g. the `title` attribute is still evaluated as expected here: https://stackblitz.com/edit/angular-ivy-tdjmsd?file=src%2Fapp%2Fapp.component.html

2020-12-10 10:57 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
> +<!-- Where should this go?-->
??

2020-12-10 14:57 UTC, kapunahelewong commented on aio/content/guide/attribute-directives.md
> +## Rendering code in the browser with `ngNonBindable`
Thank you both. What about this is a combined option? 

```
## Deactivating Angular processing with `NgNonBindable`

To prevent .... (leave 1st sentence)
`ngNonBindable` deactivates interpolation, directives, and binding in templates.

```

2020-12-10 16:07 UTC, kapunahelewong commented on aio/content/guide/attribute-directives.md
> +  As with components, you can add as many directive property bindings as you need by adding them to the host element in the template.
Hm, yes, my sentence could be cleaned up. How about this?

```
As with components, you can add multiple directive property bindings 
to the host element in the template.
```

2020-12-10 16:14 UTC, petebacondarwin commented on aio/content/guide/attribute-directives.md
> +  As with components, you can add as many directive property bindings as you need by adding them to the host element in the template.
Sounds good with or without the template.

2020-12-10 16:26 UTC, mhevery commented on aio/content/guide/attribute-directives.md
> +## Rendering code in the browser with `ngNonBindable`
Yes, I can go with that!

2020-12-10 16:59 UTC, kapunahelewong commented on aio/content/guide/attribute-directives.md
> +<!-- Where should this go?-->
That comment is regarding the following commented out part:

```
<!-- Where should this go?-->

<!-- Directives _do not_ support namespaces.

<code-example path="attribute-directives/src/app/app.component.avoid.html" 
header="src/app/app.component.avoid.html (unsupported)" region="unsupported"></code-example>

-->
```

I'm not sure where that fits conceptually. Is it specific to attribute directives, or does this apply to all kinds of directives? Would you have any recommendations? 🧐

2020-12-10 22:14 UTC, kapunahelewong commented on aio/content/guide/attribute-directives.md
> +Applying `ngNonBindable` to an element stops binding at that element, including child elements.
Thanks for the demo! Fixed!

2020-12-10 22:27 UTC, mary-poppins commented
You can preview b6d473d at https://pr39849-b6d473d.ngbuilds.io/.

2020-12-11 16:01 UTC, kapunahelewong commented on aio/content/guide/attribute-directives.md
> -can change several element styles at the same time.
Agreed completely, @jelbourn! I think this would fit nicely in the built-in directives doc. How about this (Removes repeated info): [https://github.com/angular/angular/pull/39816/files#diff-b61a89e0db979510ad8c477d373af8971179c5876edc6c951dd2ae21904ae9f7R12](https://github.com/angular/angular/pull/39816/files#diff-b61a89e0db979510ad8c477d373af8971179c5876edc6c951dd2ae21904ae9f7R12)

2020-12-11 16:16 UTC, kapunahelewong commented on aio/content/guide/attribute-directives.md
> +<!-- Where should this go?-->
Do you think we should put it somewhere temporarily until we have such a document, @jelbourn? I thought about the style guide, but that doesn't seem quite right since it would be incorrect rather than a style choice, right?

Here it is with the code snippet for reference:


```
Directives do not support namespaces.

<p app:Highlight>This is invalid</p>
```

2020-12-11 17:49 UTC, mary-poppins commented
You can preview 9e2ff85 at https://pr39849-9e2ff85.ngbuilds.io/.

2020-12-14 17:32 UTC, mary-poppins commented
You can preview 750aed0 at https://pr39849-750aed0.ngbuilds.io/.

2020-12-15 19:41 UTC, TeriGlover approved these changes
LGTM

2020-12-18 17:25 UTC, aikidave approved these changes
Looks very clean. Approving, but would like to have @jelbourn's approval as well.

Reviewed-for: global-docs-approvers

2020-12-18 17:25 UTC, aikidave commented on aio/content/guide/attribute-directives.md
> -can change several element styles at the same time.
Now that you've moved this to PR 39816, I think we're good!

2020-12-18 17:25 UTC, aikidave commented on aio/content/guide/attribute-directives.md
> +<!-- Where should this go?-->
A question to ask: How often are developers confused by this? While including it might be great for completeness sake, if the vast majority of Angular developers don't get tripped up over this, I think it's okay to remove.

Also, when in doubt, we can always file issues against the docs that includes the information that we're removing, requesting that identify a better place to include it. As @jelbourn has mentioned before, we may create a "How Angular Works" section that provides more detailed overviews of, well, how Angular works. When filing issues, I'd recommend linking to a version-specific aio link, such as v10.angular.io/guide/<name>.

2021-01-08 01:24 UTC, jelbourn commented on aio/content/guide/attribute-directives.md
> -can change several element styles at the same time.
While moving part of this content to the built-in directives doc is good, the bit that still disappears would be the "There are three kinds of directives in Angular". Reviewing this and the structural directive doc makes me realize that we need something like a "Directives overview" sooner than I thought (still as a follow-up). I don't think this doc would be very long or complicated- @aikidave  would it make sense to have a quick brainstorm about this sometime in the next week?

2021-01-08 01:24 UTC, jelbourn commented on aio/content/guide/attribute-directives.md
> +<!-- Where should this go?-->
IMO this information is rather important, and I'm actually surprised it was relegated to an appendix. My stance is that a developer should never be in a position where they can't answer "Why do I have to write this here?" 

Rather than deleting it, I would leave it here for now until we can create a better home for content that applies to both components and directives (selectors, inputs/outputs, lifecycle hooks, etc.)

2021-02-08 23:26 UTC, aikidave commented on aio/content/guide/attribute-directives.md
> +<!-- Where should this go?-->
If we don't have resolution on this, I suggest filing an issue and moving on.

2021-02-08 23:27 UTC, aikidave commented on aio/content/guide/attribute-directives.md
> +<!-- Where should this go?-->
I'm fine with @jelbourn's suggestion. (Leave it in place and evaluate during a future update.)

2021-02-08 23:31 UTC, aikidave commented on aio/content/guide/attribute-directives.md
> -can change several element styles at the same time.
@jelbourn We can certain discuss this! I've created https://github.com/angular/angular/issues/40755 to track this.

2021-02-09 00:47 UTC, jelbourn approved these changes
LGTM

2021-02-09 15:50 UTC, kapunahelewong commented on aio/content/guide/attribute-directives.md
> +<!-- Where should this go?-->
Leaving in the same place (the Building an attribute directive section) as current version. Placed it in an `is-helpful` `div`.

2021-02-09 15:59 UTC, kapunahelewong commented on aio/content/guide/attribute-directives.md
> +<!-- Where should this go?-->
Putting this in the Building an attribute directive section per https://github.com/angular/angular/pull/39849#discussion_r539677232

2021-02-09 18:45 UTC, mary-poppins commented
You can preview 72d68b8 at https://pr39849-72d68b8.ngbuilds.io/.

2021-02-09 19:23 UTC, mary-poppins commented
You can preview b064022 at https://pr39849-b064022.ngbuilds.io/.

2021-02-09 21:29 UTC, jessicajaniuk requested changes

2021-02-09 21:29 UTC, jessicajaniuk commented on aio/content/guide/attribute-directives.md
> +      <img src="generated/images/guide/attribute-directives/highlight-directive-v2-anim.gif" alt="Highlight v.2">
I'm not sure the alt text here provides a good enough description for someone with visual impairment to fully understand what's happening in the image.

2021-02-09 21:29 UTC, jessicajaniuk commented on aio/content/guide/attribute-directives.md
> +    <img src="generated/images/guide/attribute-directives/highlight-directive-final-anim.gif" alt="Final Highlight">
I think the same comment here about alt text. These are convenient for us to understand that this is the final highlight image, but it doesn't really tell a user that's using a screen reader anything of value.

2021-02-17 16:25 UTC, mary-poppins commented
You can preview 6cf6661 at https://pr39849-6cf6661.ngbuilds.io/.

2021-02-17 21:29 UTC, jessicajaniuk approved these changes
LGTM 🍪 

Thanks for addressing the alt tags feedback!

2021-02-19 14:49 UTC, kapunahelewong commented
Hi caretaker, could you help me with this one? I think I have enough reviews. Can I move forward as it stands or should I get more? Thank you!

2021-02-19 14:52 UTC, petebacondarwin commented
The problem you have @kapunahelewong is that you now need `public-api` approval too, which requires people to approve with `Reviewed-for: public-api` in their review.

2021-02-19 16:15 UTC, closed without merging