docs(common): fix typos in HttpClient docs
angular/angular pull request #39904
Opened 2020-12-01 10:02 UTC by nicholasp

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-12-01 10:48 UTC, gkalpak requested changes
Thank you, @nicholasp :100:
I made a couple of minor suggestions (otherwise lgtm :+1:).

2020-12-01 10:48 UTC, gkalpak commented on packages/common/http/src/client.ts
> +   * Sends an `HttpRequest` and returns a stream of `HttpEvents`.
Actually, there is no `HttpEvents` type (only [HttpEvent][1]). Let's change this to:

```suggestion
   * Sends an `HttpRequest` and returns a stream of `HttpEvent`s.
```

(Same for other occurrences of `HttpEvents` below.)

[1]: https://angular.io/api/common/http/HttpEvent

2020-12-01 10:48 UTC, gkalpak commented on packages/common/http/src/client.ts
>     * request.
While you are at it, feel free to get rid of the unnecessary newline here:

```suggestion
   *     the request.
```

2020-12-01 10:51 UTC, mary-poppins commented
You can preview 56c93a5 at https://pr39904-56c93a5.ngbuilds.io/.

2020-12-01 11:14 UTC, nicholasp commented
Hi, @gkalpak ! Thanks I did fixup

2020-12-01 11:18 UTC, mary-poppins commented
You can preview 8b446f3 at https://pr39904-8b446f3.ngbuilds.io/.

2020-12-01 11:32 UTC, gkalpak requested changes
Thx for making the changes, @nicholasp! Seems like you missed an "s" at the end :smiley:

Note, we still want to have the "s" (for grammatical conrectness), but we want it to be outside the backticks (i.e. outside the generated `<code>` blocks).

2020-12-01 11:32 UTC, gkalpak commented on packages/common/http/src/client.ts
> +   * Sends an `HttpRequest` and returns a stream of `HttpEvent`.
```suggestion
   * Sends an `HttpRequest` and returns a stream of `HttpEvent`s.
```

2020-12-01 11:32 UTC, gkalpak commented on packages/common/http/src/client.ts
> +   * the request.
```suggestion
   *     the request.
```

2020-12-01 14:30 UTC, mary-poppins commented
You can preview 78c84fe at https://pr39904-78c84fe.ngbuilds.io/.

2020-12-01 17:00 UTC, gkalpak requested changes
Nice work, @nicholasp ✨
I've left a few more comments with typos to be fixed 😇

2020-12-01 17:39 UTC, nicholasp commented
@gkalpak  :D 👍

2020-12-01 17:50 UTC, mary-poppins commented
You can preview c21b32d at https://pr39904-c21b32d.ngbuilds.io/.

2020-12-01 19:13 UTC, gkalpak requested changes
Last two comments :grin:
(BTW, thx for adding the changes in fixup commits. It makes it so much easier to review :100:)

2020-12-01 19:13 UTC, gkalpak commented on packages/common/http/src/client.ts
> +   * @return An `Observable` of all `HttpEvent` for the request, with a response body
```suggestion
   * @return An `Observable` of all `HttpEvent`s for the request, with a response body
```

2020-12-01 19:13 UTC, gkalpak commented on packages/common/http/src/client.ts
> +   * @return An `Observable` of all `HttpEvent` for the request, with the response body of type
```suggestion
   * @return An `Observable` of all `HttpEvent`s for the request, with the response body of type
```

2020-12-02 07:47 UTC, nicholasp commented
:) thanks also for guiding me @gkalpak

2020-12-02 10:42 UTC, gkalpak approved these changes
The changes look great 🚀 :100: ✨
It seems like you need to rebase on latest master one last time :wink:

Reviewed-for: global-docs-approvers

2020-12-02 11:58 UTC, mary-poppins commented
You can preview 759b3a1 at https://pr39904-759b3a1.ngbuilds.io/.

2020-12-02 19:16 UTC, closed without merging