feat(core): lazy load zone-testing in fake_async
angular/angular pull request #39941
Opened 2020-12-03 05:05 UTC by JiaLiPassion

Angular requires to load `zone-testing` before loading `@angular/core/testing`,
since `zone-testing` provide `fakeAsync/async` test util methods.
So if the user load the bundles with wrong order, `please load zone-testing`
error will be thrown.
This PR make `fakeAsync` loading `Zone` object lazyly, so even the
`zone-testing` is loaded after `@angular/core/testing`, the test will
 still be success.

2021-01-21 19:05 UTC, IgorMinar requested changes
thanks for the PR @JiaLiPassion, can you please take a look at the concerns I brought up?

2021-01-21 19:05 UTC, IgorMinar commented on packages/core/testing/src/fake_async.ts
> +  const fakeAsyncTestModule = getFakeAsyncTestModule();
I'm not keen on making the change in this commit because it makes the contract between @angular/core/testing and zone.js/zone-testing more ambiguous.

Currently it's clear that all the zone code needs to be loaded before everything else because zone.js acts as a polyfill and needs to setup the environment for the rest of the code that will be loaded and executed.

Is there a reason why developers would have a hard time loading all the zone.js code before any Angular code? If not, then I'd prefer if we skipped the change in this entire commit.

2021-01-21 19:05 UTC, IgorMinar commented on packages/core/testing/src/before_each.ts
> -    resetFakeAsyncZone();
this change looks good to me even without the change in the previous commit. The reset of the fakeAsyncZone does belong to the zone.js package.

2021-01-22 02:13 UTC, JiaLiPassion commented on packages/core/testing/src/fake_async.ts
> +  const fakeAsyncTestModule = getFakeAsyncTestModule();
Yeah, as a contract, zone.js need to be loaded before angular as a polyfills,  recently some library is using `eslint` to format the code in `test.ts`, so the code here
```
import 'zone.js/dist/zone-testing';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';
```
becomes 

```
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';
import 'zone.js/dist/zone-testing';
```

after lint.

And most developers will not even notice this change, and it will not cause the test crash, but will cause some issues and very difficult to debug.

So for `zone.js` itself, it is a `polyfill` and need to be loaded first, but for `zone-testing`, it is a helper util library, I think maybe we can do some improvement to make the developer test easier.

2021-01-22 02:14 UTC, JiaLiPassion commented on packages/core/testing/src/before_each.ts
> -    resetFakeAsyncZone();
Yes, I agree, we need to separate `@angular/core/testing` and `zone-testing` more clearly.

2021-02-16 21:20 UTC, mhevery requested changes
It is unclear what benefit would developer get by lazy loading `zone.js/dist/zone-testing` Could we define the problem we are trying to solve first.

2021-02-16 21:20 UTC, mhevery commented on packages/core/testing/src/fake_async.ts
> +  const fakeAsyncTestModule = getFakeAsyncTestModule();
What benefit would the developer get by allowing `zone.js/dist/zone-testing` to be lazy loaded?

2021-02-17 00:39 UTC, JiaLiPassion commented
@mhevery , the main benefit is when the user is using `eslint`, the code in `test.ts` generated by Angular CLI becomes from 

```
import 'zone.js/dist/zone-testing';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';
```

to 

```
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';
import 'zone.js/dist/zone-testing';
```

And the user rarely noticed this change, and the test fail with `fakeAsync()`, the current solution is to import `zone.js/dist/zone-testing` in the correct order and add `eslint ignore` comment, so I think maybe we can just let user load `zone-testing` without care about the order.

2021-02-17 17:57 UTC, mhevery requested changes

2021-02-17 17:57 UTC, mhevery commented on packages/core/testing/src/before_each.ts
> -    resetFakeAsyncZone();
Remove `import {resetFakeAsyncZone} from './fake_async';` as it is unneeded now?

2021-02-17 22:52 UTC, JiaLiPassion commented
@mhevery, I removed the unused import now, please review, thank you!

2021-02-18 18:47 UTC, mhevery approved these changes
I think supporting tslint is a reasonable request. LGTM

2021-03-03 22:12 UTC, IgorMinar commented
I still think that this PR is problematic because it's just working around the formatter that is doing the wrong thing.

Unlike other formatting changes, changing the order of imports, especially side-effecty (bare) imports is not safe. These imports change global state and because of that their order matters and can't be arbitrarily changed.

Yes, we could make the zone.js code more convoluted to support both orders between zone.js and @angular/core/testing but it comes at the cost of making the contract unclear and code more convoluted.

btw if you use reasonable eslint import sorting rule, I'd expect the bare imports to end up being first because they clearly exist only to introduce side-effects into the global state or module that imports them.

2021-03-04 18:02 UTC, zarend commented
[presubmit](http://test/OCL:360942311:BASE:360942396:1614880921744:37a7fe1f)

2021-12-18 00:09 UTC, JiaLiPassion commented
It seems this issue has been gone with the newest version of eslint, I will continue to confirm it and will close this issue for now.

2021-12-18 00:09 UTC, closed without merging

2022-01-02 03:11 UTC, matheo commented
For some reason I'm getting the error reported at #40305 and I would have loved this PR getting merged so I could have avoided the headache I'm having trying to figure out this unexpected one :(

Importing `zone.js` and `zone.js/testing` to my `jest-setup.ts` doesn't solve my issue.