fix(service-worker): handle error with ErrorHandler
angular/angular pull request #39990
Opened 2020-12-05 16:39 UTC by chrisguttandin

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #39913

## What is the new behavior?

Errors thrown when trying to register a Service Worker are now passed to the global ErrorHandler.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-12-05 17:34 UTC, gkalpak requested changes
Thx for working on this, @chrisguttandin :+1:

I've left a couple of minor comments. Could you also add a test for the new behavior in [service-worker/test/module_spec.ts][1]?

Also, let's add a short description of the motivation for the change in the commit message body and also add `Fixes #39913` at the bottom (per our [commit message guidelines][2]).

[1]: https://github.com/angular/angular/blob/63213a78cdc1f31cd13dd2e43c3a564168fa424d/packages/service-worker/test/module_spec.ts
[2]: https://github.com/angular/angular/blob/1d9e56eba06958e37ef8062ae7b65afa85f90632/CONTRIBUTING.md#commit

2020-12-05 17:34 UTC, gkalpak commented on packages/service-worker/src/module.ts
> +import {APP_INITIALIZER, ApplicationRef, InjectionToken, Injector, ErrorHandler, ModuleWithProviders, NgModule, NgZone, PLATFORM_ID} from '@angular/core';
```suggestion
import {APP_INITIALIZER, ApplicationRef, ErrorHandler, InjectionToken, Injector, ModuleWithProviders, NgModule, NgZone, PLATFORM_ID} from '@angular/core';
```

2020-12-05 17:34 UTC, gkalpak commented on packages/service-worker/src/module.ts
> +    const errorHandler = injector.get(ErrorHandler);
I suggest we move this line into the `catch()` callback, so we avoid retrieving the `ErrorHandler` if we don't need it.

2020-12-05 22:29 UTC, chrisguttandin commented on packages/service-worker/src/module.ts
> +import {APP_INITIALIZER, ApplicationRef, InjectionToken, Injector, ErrorHandler, ModuleWithProviders, NgModule, NgZone, PLATFORM_ID} from '@angular/core';
Thanks for catching this. I meant to order the imports alphabetically but got it wrong.

2020-12-05 22:30 UTC, chrisguttandin commented on packages/service-worker/src/module.ts
> +    const errorHandler = injector.get(ErrorHandler);
Yes, good idea. I applied it.

2020-12-05 22:31 UTC, chrisguttandin commented
Hi @gkalpak, thanks for your feedback. I made the changes and updated the test. Please let me know if there is anything else I should change.

2020-12-06 11:29 UTC, gkalpak approved these changes
One super-minor nit. Otherwise lgtm (as long as CI is happy :smiley:)
Thx again, @chrisguttandin ✨

2020-12-06 11:29 UTC, gkalpak commented on packages/service-worker/test/module_spec.ts
> +          {provide: PLATFORM_ID, useValue: 'browser'}
Nit:

```suggestion
          {provide: PLATFORM_ID, useValue: 'browser'},
```

2020-12-06 13:12 UTC, chrisguttandin commented on packages/service-worker/test/module_spec.ts
> +          {provide: PLATFORM_ID, useValue: 'browser'}
No problem, I added the comma.

2020-12-08 20:03 UTC, closed without merging