Non template diagnostics round2
angular/angular pull request #40026
Opened 2020-12-08 17:49 UTC by zarend

refactor(compiler-cli): move template parse errors to TemplateData

During analysis we find template parse errors. This commit changes
where the type checking context stores the parse errors. Previously, we
stored them on the genesisDiagnostics on the shim. this commit changes the
errors to be stored on the TemplateData (which is a property on the
shim). That way, the template parse errors can be grouped by template.

Please ignore the first commit, that will go away when we merge: [#40013](https://github.com/angular/angular/pull/40013).

2020-12-08 18:30 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +   * TODO(Ayaz): store parse errors from overridden template
Just a couple nits:
- I'm wondering if this is the right place for the `TODO` (since it's just an interface). I saw a similar comment below near the actual implementation, should that be sufficient?
- I'd propose to put Ayaz's GitHub handle so that it's easier to find all TODOs later, i.e. something like `TODO(ayazhafiz): ...`.

2020-12-08 18:30 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +      templateDiagnostics.push(...parseErrors.map(error => {
Given the current size of the `addTemplate` function, I'd propose to move the logic that converts parse errors into template diagnostics into a new private function, so this call would look like:
```
  templateDiagnostics.push(...this.convertParseErrorsToDiagnostic(parseErrors, ref.node));
```

2020-12-08 18:47 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +      }
Do we want to retrieve typecheck diagnostics for templates that have parse errors? I imagine there may be some invalid/non-sensical typeck diagnostics that can be produced if we pass an invalid (even if well-formed) template to the typechecker. For example, once #39523 lands, a template like

```
<div ()="something"></div>
```

would produce a parse error about an empty event, but given that we still form an AST with an empty event binding name, would the typechecker also give a diagnostic about no event found for the div element?

@alxhub and @atscott probably have more insight here; I am fine lumping both kinds of diagnostic for now and figuring out if/where this leads to poor diagnostic reporting later on, but just something to think about.

2020-12-08 18:47 UTC, ayazhafiz commented on packages/language-service/ivy/test/diagnostic_spec.ts
> +    ]);
nit: no need to assert the length since the array is matched for equality

2020-12-08 18:47 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +   * TODO(Ayaz): store parse errors from overridden template
I think you should assign this TODO to yourself just so there is less "handing off" and this work can land faster 🙂

2020-12-08 19:04 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +   * TODO(Ayaz): store parse errors from overridden template
fair enough, Andrew S. and I will take this on :)

2020-12-11 18:01 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +      }
Thanks for review @ayazhafiz . Yes, there might be some confusing errors caused by an upstream template parse error. It is also valuable to show some errors on a template if it has parse errors, and we that that makes this worth it.

For example, here I make parse error by doing an illegal assignment, then I continue to write html that parses okay, but has typechecking errors. It's valuable to show developers errors in the rest of the template, even if another part of the template has a parse error.

```
<input ngModel="foo = $event"/> <!-- Parse error, assignments not allowed -->
<app-cat [name]="bar"></app-cat> <!-- Error, type number is not assigning to type string-->
```

@alxhub , care to weigh in :)

2020-12-11 18:08 UTC, ayazhafiz commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +      }
I agree it would be good to have both parse and typeck errors at the same time. I mean to say that a parse error could cause us to parse an AST that would also then have a typecheck error over the same span as a parse error, and maybe we don't care about the typecheck error in this case. But I don't think this is something worth trying to "fix" at this point.

2020-12-11 18:13 UTC, atscott requested changes
What happened to the change to prevent compilation of a component if there are parse errors? and handling the potential for `null` resolution data?

2020-12-11 18:13 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +          ...(this.getTemplateDiagnostics(parseErrors, templateId, sourceMapping)));
nit: this extra parens isn't necessary.

2020-12-11 18:13 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +    shimData.templates.set(templateId, {template, boundTarget, parseErrors: templateDiagnostics});
nit: add trailing comma to this object so each property gets its own line

2020-12-11 19:53 UTC, zarend commented
> What happened to the change to prevent compilation of a component if there are parse errors? and handling the potential for `null` resolution data?

### How do we avoid compiling components with parse errors?

We don't want to do that because we could cause confusing errors from things being in an invalid state. These could look like red herrings when the source of the problem is the parse error. (E.G. if you try to compile a template with nested `i18n` sections, you get `i18n context not available`. Instead we provide a parse error saying `nesting i18n sections is not allowed. Please remove the nesting).

![image](https://user-images.githubusercontent.com/7720245/101948724-64b39500-3ba7-11eb-8890-e8cf96750129.png)
The safeguard from compiling a bad template is handed in packages/compiler-cli/src/perform_compile.ts. If we have any diagnostics, then we refuse the emit the program.

We know there's a diagnostic for template parse errors because we put them there in the NgCompiler. Emit is the phase we don't want to do because it will compile the template.

2020-12-11 20:25 UTC, atscott approved these changes

2020-12-11 21:08 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +      for (let templateData of shimRecord.templates.values()) {
```suggestion
      for (const templateData of shimRecord.templates.values()) {
```

2020-12-11 21:14 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +      describe('i18n errors', () => {
Remove from (new) compliance tests

2020-12-11 21:15 UTC, alxhub approved these changes

2020-12-11 21:22 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +          ...(this.getTemplateDiagnostics(parseErrors, templateId, sourceMapping)));
What if the template is overridden? Let's capture and use those parse errors instead here.

2020-12-11 21:35 UTC, zarend commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +      describe('i18n errors', () => {
✔️ they've been removed in commit `3d7344172f269bf2560dd8ccafeaae8819d441c1`

2020-12-11 21:56 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +          ...(this.getTemplateDiagnostics(parseErrors, templateId, sourceMapping)));
done 👍

2020-12-11 22:28 UTC, AndrewKushnir approved these changes
LGTM (with a couple minor comments) 👍

2020-12-11 22:28 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/typecheck/api/context.ts
> +      parseErrors: ParseError[]|null): void;
It looks like this new params need to be added to JSDoc above.

2020-12-11 22:28 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +  parseErrors: TemplateDiagnostic[];
Nit: I was thinking if `parseErrors` name here overlap with `parseErrors` in other parts of the code where fields with the same name have `ParseError[]` type. May be it makes sense to call it `errors` or `diagnostics`? Or be a bit more specific and call it `parseErrorDiagnostics`?
(Note: I'm also ok to keep it as is, just sharing some thoughts)

2020-12-11 22:28 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +      parseErrors: ParseError[]|null): void {
JSDoc for this fn looks outdated (and also missing new arg).

2020-12-11 22:28 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +      parseErrors: ParseError[], templateId: TemplateId, sourceMapping: TemplateSourceMapping) {
nit: function is missing its return type.

2020-12-11 22:28 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +      parseErrors: ParseError[], templateId: TemplateId, sourceMapping: TemplateSourceMapping) {
One more note: it looks like all private methods of the `TypeCheckContextImpl` class go after non-private ones. For consistency, I'd propose moving this method down as well (put it after `finalize` method).

2020-12-12 00:24 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +  parseErrors: TemplateDiagnostic[];
cool, I named it templateDiagnostics

2020-12-14 22:50 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +        isPoisoned: false,
We should make sure to early-exit from `compilePartial` and `compileFull` for components that have parse errors, since we're removing the diagnostics from here, which will allow this component to "proceed" down the line with compilation.

2020-12-14 22:50 UTC, alxhub approved these changes

2020-12-15 00:47 UTC, zarend commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +        it('report a diagnostic and doesn\'t emit ' +
@alxhub would you do this as two seperate `it`'s? One it to check the diagnostics, and another to make sure it doesn't emit the component with a bad template?

2020-12-15 16:36 UTC, zarend commented
> > What happened to the change to prevent compilation of a component if there are parse errors? and handling the potential for `null` resolution data?
> 
> ### How do we avoid compiling components with parse errors?
> We don't want to do that because we could cause confusing errors from things being in an invalid state. These could look like red herrings when the source of the problem is the parse error. (E.G. if you try to compile a template with nested `i18n` sections, you get `i18n context not available`. Instead we provide a parse error saying `nesting i18n sections is not allowed. Please remove the nesting).
> 
> ![image](https://user-images.githubusercontent.com/7720245/101948724-64b39500-3ba7-11eb-8890-e8cf96750129.png)
> The safeguard from compiling a bad template is handed in packages/compiler-cli/src/perform_compile.ts. If we have any diagnostics, then we refuse the emit the program.
> 
> We know there's a diagnostic for template parse errors because we put them there in the NgCompiler. Emit is the phase we don't want to do because it will compile the template.

^ I was partially correct about this. We also need to early return in `compileFull` and `compilePartial` so that we try to compile a bad template and crash internally. Ty to @alxhub for catching this.

2020-12-15 17:07 UTC, atscott commented
> We also need to early return in compileFull and compilePartial so that if someone trys to call emit directly, we don't crash internally when trying to compile a bad template. 

@zarend - Do you have any examples of scenarios where this would happen? Incremental builds?

2020-12-15 19:10 UTC, alxhub commented
> > We also need to early return in compileFull and compilePartial so that if someone trys to call emit directly, we don't crash internally when trying to compile a bad template.
> 
> @zarend - Do you have any examples of scenarios where this would happen? Incremental builds?

If a consumer of the `NgtscProgram` APIs attempts to `emit()` even if there are diagnostics.

2020-12-15 21:28 UTC, alxhub approved these changes

2020-12-15 21:31 UTC, closed without merging