docs: update CLI MAN page format
angular/angular pull request #40038
Opened 2020-12-09 11:34 UTC by alan-agius4

With this change we update the CLI docs template to seperate the following the default and value types from the argument field.

This should make it clearer and more understandable

2020-12-09 11:43 UTC, mary-poppins commented
You can preview 21c0fd1 at https://pr40038-21c0fd1.ngbuilds.io/.

2020-12-09 11:54 UTC, mary-poppins commented
You can preview 4749e84 at https://pr40038-4749e84.ngbuilds.io/.

2020-12-09 12:08 UTC, alan-agius4 commented
Example can be viewed https://pr40038-4749e84.ngbuilds.io/cli/build

2020-12-09 12:18 UTC, mary-poppins commented
You can preview a2091f0 at https://pr40038-a2091f0.ngbuilds.io/.

2020-12-09 15:13 UTC, petebacondarwin requested changes
Perhaps also do the same for the "Arguments" section?

<img width="884" alt="Screenshot 2020-12-09 at 15 12 45" src="https://user-images.githubusercontent.com/15655/101647809-12e8fe80-3a31-11eb-9305-7859b94dfb7c.png">

2020-12-09 15:13 UTC, petebacondarwin commented on aio/tools/transforms/templates/cli/lib/cli.html
> +{%- if valString.length > 15 %}{% endif %}{$ valString $}
Now that the length of `valString` makes no difference this whole macro can be significantly simplified:

```suggestion
{$ values.join('|') $}
```

2020-12-09 15:44 UTC, alan-agius4 commented
@petebacondarwin, yeah I can do it for arguments as well, I wasn’t aware that they was an argument which was not a free string.

2020-12-10 08:49 UTC, mary-poppins commented
You can preview 980f0ca at https://pr40038-980f0ca.ngbuilds.io/.

2020-12-10 09:59 UTC, petebacondarwin approved these changes
LGTM! Thanks @alan-agius4

2020-12-10 11:42 UTC, alan-agius4 commented
@kyliau, @aikidave & @clydin thoughts?

2020-12-10 14:44 UTC, clydin commented
I think this is a good incremental improvement.

Long-term (and out of scope for this PR), however, I think the overall structure of this page should be adjusted.  The `Options` listed are currently a mixture of the `ng build` command's arguments (e.g., `--configuration`) and the options for the `@angular-devkit/build-angular:browser` builder (e.g., `--base-href`).  The later of which are not necessarily relevant or valid for a given execution of `ng build`.  This invalid nature is most evident when attempting to build a library via `ng build` wherein a completely separate set of options are used and attempting to use the aforementioned `browser` builder options will result in an error.

2020-12-10 22:20 UTC, aikidave approved these changes
I think this is a very useful change. Thanks!

Reviewed-for: global-docs-approvers

2020-12-11 00:53 UTC, kyliau approved these changes

2020-12-14 19:31 UTC, closed without merging