fix(animations): allow animations in shadow DOM
angular/angular pull request #40134
Opened 2020-12-15 16:44 UTC by jeripeierSBB

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number:  #25672

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-12-29 13:21 UTC, pipeBuitragoFiduciariaBogota approved these changes

2021-02-24 12:34 UTC, LinPoLen commented
ping @IgorMinar

2021-03-18 11:34 UTC, IonelLupu commented
hey. How can we help with this PR? Maybe we can have it in the next Angular release. It's blocking some other animation related issues

2021-04-02 14:52 UTC, petebacondarwin commented
I am aware that I have still not reviewed this PR. I will prioritise it for next week.

2021-04-06 18:49 UTC, petebacondarwin requested changes
OK, so I finally got round to taking a look at this PR.
Thank you @jeripeierSBB for putting this together, and for your patience, everyone.
I think it is in pretty good shape. Just a couple of suggestions.

Also, since the commit message will appear in the CHANGELOG, can we reword it slightly...

```
fix(animations): allow animations on elements in the shadow DOM

When determining whether to run an animation, the `TransiationAnimationPlayer`
checks to see if a DOM element is attached to the document. This is done by
checking to see if the element is "contained" by the document body node.

Previously, if the element was inside a shadow DOM, the engine would
determine that the element was not attached, even if the shadow DOM's
host was attached to the document. This commit updates the `containsElement()`
method on `AnimationDriver` implementations to also include shadow DOM
elements as being contained if their shadow host element is contained.

Further, when using CSS keyframes to trigger animations, the styling
was always added to the `head` element of the document, even for
animations on elements within a shadow DOM. This meant that those
elements never receive those styles and the animation would not run.
This commit updates the insertion of these styles so that they are added,
to the element's "root node", which is the nearest shadow DOM host, or the
`head` of the document if the element is not in a shadow DOM.

Closes #25672
```

2021-04-06 19:19 UTC, jeripeierSBB commented
@petebacondarwin thanks a lot for your review. I will update the PR in the next days.

2021-04-07 06:30 UTC, jeripeierSBB commented on packages/animations/browser/test/render/css_keyframes/css_keyframes_driver_spec.ts
> +}
Changed to use BrowserDetection from @angular/platform-browser/testing/src/browser_util

2021-04-07 15:51 UTC, petebacondarwin commented on packages/animations/browser/test/render/css_keyframes/css_keyframes_driver_spec.ts
> +}
Good call. Thanks

2021-04-07 18:35 UTC, petebacondarwin approved these changes
LGTM! Thanks @jeripeierSBB 

Reviewed-for: size-tracking

We will need to get further reviews

2021-04-08 18:06 UTC, crisbeto commented on packages/animations/browser/src/render/css_keyframes/css_keyframes_driver.ts
> +  while (element && element !== document.documentElement) {
Maybe I'm missing some context, but wouldn't this loop always resolve to `document.documentElement` if `shadowRoot` isn't supported? [According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/shadowRoot), IE doesn't support `shadowRoot` either. 

If that's the case, we could get away with something like `element.getRootNode?.() || document.head`.

2021-04-08 18:06 UTC, crisbeto commented on packages/animations/browser/src/render/css_keyframes/css_keyframes_driver.ts
> +  return document.querySelector('head')!;
You should be able to use `document.head` for this.

2021-04-08 18:06 UTC, crisbeto commented on packages/animations/browser/src/render/css_keyframes/css_keyframes_driver.ts
> +function findNodeToAppendKfElm(element: any): Node {
`findNodeToAppendKfElm` -> `findNodeToAppendKeyframeElmement`. We should avoid abbreviations in symbol names.

2021-04-08 18:06 UTC, crisbeto commented on packages/animations/browser/src/render/css_keyframes/css_keyframes_driver.ts
> +  return document.querySelector('head')!;
Also do we need to account for non-browser environments here?

2021-04-09 07:04 UTC, jeripeierSBB commented on packages/animations/browser/src/render/css_keyframes/css_keyframes_driver.ts
> +  return document.querySelector('head')!;
I can't decide that, but I think if using your suggested shortcut (getRootNode), we could not save a lot if checking for isBrowser and creating a switch. Non browser environments would fallback to document.head (as it was before anyways).

2021-04-09 07:34 UTC, jeripeierSBB commented on packages/animations/browser/src/render/css_keyframes/css_keyframes_driver.ts
> +  while (element && element !== document.documentElement) {
I think you are right, my original thought (back in December ;) ) was that ShadowRoot was introduced a few versions earlier in some browsers than getRootNode. But for example Firefox had getRootNode before ShadowRoot... So I think this doesn't matter.
Shadow Dom doesn't seem to be supported in Internet Explorer without a polyfill.

2021-04-09 09:08 UTC, crisbeto commented on packages/animations/browser/src/render/shared.ts
> +  if (!isBrowser()) {
Isn't this check always going to be true? There's an `if (_isNode)` a couple of lines above.

2021-04-09 10:13 UTC, jeripeierSBB commented on packages/animations/browser/src/render/shared.ts
> +  if (!isBrowser()) {
No because, `_isNode || typeof Element !== 'undefined'` is true in browsers and node applications (`typeof Element !== 'undefined'`).
Do you know why the check of `_isNode || typeof Element !== 'undefined'` exists? This seems to match in almost all circumstances.

The reason I made the isBrowser check was to introduce a shortcut to not check for shadow hosts in non browser environments. But I think we could in every case also use the part of the else block and remove the switch. What do you think?

2021-04-09 11:37 UTC, crisbeto approved these changes
LGTM

2021-04-09 11:37 UTC, crisbeto commented on packages/animations/browser/src/render/shared.ts
> +  if (!isBrowser()) {
I see. Let's keep it as is then.

2021-04-09 13:15 UTC, petebacondarwin approved these changes
One last change and then we are good to merge.

2021-04-09 13:15 UTC, petebacondarwin commented on goldens/size-tracking/aio-payloads.json
> +        "main-es2015": 452289,
@jeripeierSBB this can no be changed to `452203` since you reduced the `findNodeToAppendKeyframeElement()` function size.

2021-04-09 13:15 UTC, petebacondarwin commented on goldens/size-tracking/aio-payloads.json
> +        "main-es2015": 437924,
Similarly this one can be `437844`.

2021-04-09 13:29 UTC, jeripeierSBB commented on goldens/size-tracking/aio-payloads.json
> +        "main-es2015": 437924,
Sorry I did not really get the size tracking thing.. Thanks for pointing me in the right direction ;)

2021-04-09 13:41 UTC, alxhub commented on packages/animations/browser/src/render/shared.ts
> +      while (elm2 && elm2 !== document.documentElement) {
Would it be worth having a short circuit `if (elm1.contains(elm2)) { return true; }` here to optimize the common case?

2021-04-09 13:41 UTC, alxhub approved these changes

2021-04-09 13:51 UTC, jeripeierSBB commented on packages/animations/browser/src/render/shared.ts
> +      while (elm2 && elm2 !== document.documentElement) {
I guess that ‚contains‘ internally also does kind of tree walking, so it would not speed up a lot but slow down by 2 in the shadow dom context usage

2021-04-09 18:14 UTC, atscott approved these changes
Reviewed-for: size-tracking

2021-04-09 21:35 UTC, AndrewKushnir approved these changes

2021-04-09 21:35 UTC, AndrewKushnir commented on packages/animations/browser/src/render/shared.ts
>    // this is well supported in all browsers
I'm a bit confused by this comment, should we remove/update it as well?

2021-04-13 07:15 UTC, jeripeierSBB commented on goldens/size-tracking/aio-payloads.json
> +        "main-es2015": 437924,
@petebacondarwin I tried several ways to locally get the right size to enter here, but failed. What is the correct way to get the bundle file size which should be entered here (not waiting for ci to fail)?

2021-04-13 07:16 UTC, jeripeierSBB commented on packages/animations/browser/src/render/shared.ts
>    // this is well supported in all browsers
I will remove the comment as it does not provide any information.

2021-04-13 18:57 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:368264198:BASE:368264220:1618340234704:884a7b3).

2021-04-14 06:18 UTC, AndrewKushnir commented
@petebacondarwin FYI, presubmits (including the global one) are successful for the changes in this PR.

2021-04-14 09:15 UTC, petebacondarwin commented
Thanks @AndrewKushnir - let's merge it!

2021-04-15 19:46 UTC, closed without merging

2021-04-15 19:47 UTC, AndrewKushnir commented
FYI, this change was merged into the `master` and `12.0.x` (RC) branches, but there was a conflict while merging into `11.2.x` branch. If the change should also be included into the `11.2.x` branch, please create a new PR targeting `11.2.x` branch. Thank you.

2021-04-22 10:06 UTC, lubos-bistak commented
Is it possible to apply this fix also to Angular 9?

2021-04-22 15:46 UTC, petebacondarwin commented
Since v9 is in LTS, it will not receive this bug fix, sorry.