fix(dev-infra): delay checking if a closed pr has been merged by 30 seconds
angular/angular pull request #40181
Opened 2020-12-17 20:23 UTC by josephperrott

Delaying the check if a closed PR was closed by a merge or just closed by 30 seconds
allows for Github to have time to update the PR to be associated to the commit which
closed the PR.  Without this delay, a race condition can exist in which we check for
how a PR was closed before this association is made.

2020-12-18 16:18 UTC, gkalpak requested changes

2020-12-18 16:18 UTC, gkalpak commented on dev-infra/release/publish/pull-request-state.ts
> +const THIRY_SECONDS_IN_MS = 30000;
```suggestion
const THIRTY_SECONDS_IN_MS = 30000;
```

2020-12-18 16:18 UTC, gkalpak commented on dev-infra/release/publish/pull-request-state.ts
> +  if (new Date(data.closed_at).getTime() - THIRY_SECONDS_IN_MS > new Date().getTime()) {
This condition will never be true (theoretically). I think you were going for something like:

```suggestion
  if ((data.closed_at !== null) && (new Date(data.closed_at).getTime() < Date.now() - THIRY_SECONDS_IN_MS)) {
```

2020-12-22 17:35 UTC, gkalpak requested changes

2020-12-22 17:35 UTC, gkalpak commented on dev-infra/release/publish/pull-request-state.ts
> +  if (new Date(data.closed_at).getTime() + THIRTY_SECONDS_IN_MS > new Date().getTime()) {
This condition is not correct. It will be true only if _not_ more than 30s have passed since `closed_at`. I think you were going for something like:

```suggestion
  if ((data.closed_at !== null) && (new Date(data.closed_at).getTime() + THIRY_SECONDS_IN_MS < Date.now())) {
```

2020-12-27 00:30 UTC, sonukapoor approved these changes

2020-12-28 17:07 UTC, gkalpak requested changes

2020-12-28 17:07 UTC, gkalpak commented on dev-infra/release/publish/pull-request-state.ts
> +  if (new Date(data.closed_at).getTime() + THIRTY_SECONDS_IN_MS < new Date().getTime()) {
This condition is still wrong. You need something like [this][1] or [that][2] 😂 

[1]: https://github.com/angular/angular/pull/40181#discussion_r545938673
[2]: https://github.com/angular/angular/pull/40181#discussion_r547408380

2021-01-08 15:31 UTC, gkalpak approved these changes

2021-01-08 17:38 UTC, closed without merging