docs: specify fallback generic font family
angular/angular pull request #40254
Opened 2020-12-23 19:31 UTC by AlexElin

https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
> You should always include at least one generic family name in a font-family list,
>  since there's no guarantee that any given font is available. This lets the browser
>  select an acceptable fallback font when necessary.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-12-28 16:47 UTC, atscott approved these changes

2020-12-28 17:04 UTC, gkalpak requested changes
Thx, @AlexElin 🤩
I left one minor comment. Otherwise lgtm :+1:

2020-12-28 17:04 UTC, gkalpak commented on aio/content/examples/getting-started-v0/src/app/app.component.css
> +  font-family: Lato, sans-serif;
This is supposed to emulate what new StackBlitz projects look like, so it should remain as is.

2020-12-29 18:05 UTC, gkalpak approved these changes
Thx for making the changes, @AlexElin :+1:

LGTM as soon as the commits are squashed into one 🚀
(In the future, if you want to address review feedback in a new commit - which is a great idea - you can use `fixup` commits. See [here][1] for more info.)

Reviewed-for: global-docs-approvers

[1]: https://github.com/angular/angular/blob/d7665fdc96e30a21cf33c96fb0cc29a90404b5f9/docs/FIXUP_COMMITS.md

2021-01-06 15:09 UTC, closed without merging