fix(compiler): don't report parse error for interpolation inside string in property binding
angular/angular pull request #40267
Opened 2020-12-26 10:46 UTC by crisbeto

Currently we check whether a property binding contains an interpolation using a regex so that we can throw an error. The problem is that the regex doesn't account for quotes which means that something like `[prop]="'{{ foo }}'"` will be considered an error, even though it's not actually an interpolation.

These changes build on top of the logic from #39826 to account for interpolation characters inside quotes.

Fixes #39601.

2020-12-29 11:22 UTC, petebacondarwin requested changes

2020-12-29 11:22 UTC, petebacondarwin commented on packages/compiler/src/expression_parser/parser.ts
> +    });
I think that this is a bit inefficient, since it will continue to run through each unquoted character even `indexOf` found the start.

Also I am concerned that the following string would find a false positive:

```
abc '{{' }} def
```

since the `{{` is in a string, it should be ignored but would be picked up by the `indexOf()`, when the `charIndex` is `0`.

2020-12-29 11:22 UTC, petebacondarwin commented on packages/compiler/src/expression_parser/parser.ts
> +    });
I think this would also be clearer if you created a new function `_getInterpolationStartIndex(input, expressionStart, start)`:

```ts
  private _getInterpolationStartIndex(input: string, expressionStart: string, start: number): number {
    let result = -1;
    this._forEachUnquotedChar(input, start, charIndex => {
      if (input.startsWith(expressionStart, charIndex)) {
        result = charIndex;
        return true;
      } else {
        return false;
      }
    });
   return result;
```

Then you could do:

```ts
const startIndex = this._getInterpolationStartIndex(input, start, 0);
if (startIndex === -1) {
  return;
}
const endIndex = this._getInterpolationEndIndex(input, end, startIndex+start.length);
if (endIndex === -1) {
  return;
}

this._reportError(...);
```

2020-12-29 11:22 UTC, petebacondarwin commented on packages/compiler/src/expression_parser/parser.ts
> +  private _forEachUnquotedChar(input: string, start: number, callback: (index: number) => boolean):
Interesting idea:  this is an opportunity to use a generator function, which yields each unquoted character.

2020-12-29 11:45 UTC, crisbeto commented on packages/compiler/src/expression_parser/parser.ts
> +    });
I didn't want to add a `_getInterpolationStartIndex`, because there's some other logic that looks for an interpolation start  in `splitInterpolation`, but the requirements there are slightly different. As for the `abc '{{' }} def` case, I think I tried something similar and it was reported as a different (syntax?) error further down the compilation process.

2020-12-29 11:45 UTC, crisbeto commented on packages/compiler/src/expression_parser/parser.ts
> +  private _forEachUnquotedChar(input: string, start: number, callback: (index: number) => boolean):
That's true, but it using a generator seemed like overkill, considering that we're only dealing with synchronous code.

2020-12-29 11:45 UTC, crisbeto commented on packages/compiler/test/expression_parser/parser_spec.ts
> +      expect(parseAction('"{{a()}}"').errors).toEqual([]);
I'll add assertions for single quoted strings, but I don't think we support backticks in templates. I kept these tests minimal since they reuse other logic that has better test coverage.

2020-12-29 11:45 UTC, crisbeto commented on packages/core/test/acceptance/property_binding_spec.ts
> +    @Component({template: `<span [id]="'{{ id }}'"></span>`})
I'll add another test case, but I think that it should be in the parser suite.

2020-12-29 12:18 UTC, crisbeto commented
I've added the extra test cases and addressed the feedback.

2020-12-29 12:30 UTC, crisbeto commented on packages/compiler/src/expression_parser/parser.ts
> +  private _forEachUnquotedChar(input: string, start: number, callback: (index: number) => boolean):
ok, I tried it out for the sake of argument and it is actually much cleaner 🙂. I've changed it to use a generator.

2020-12-29 14:10 UTC, petebacondarwin requested changes
Thanks for the changes @crisbeto. One last thing.

2020-12-29 14:10 UTC, petebacondarwin commented on packages/compiler/src/expression_parser/parser.ts
>          startIndex = input.indexOf(start, charIndex);
I still think that this should be `startsWith()`, right

2020-12-29 14:26 UTC, crisbeto commented on packages/compiler/src/expression_parser/parser.ts
>          startIndex = input.indexOf(start, charIndex);
No, we need the index for the error message. The `endIndex` can be a boolean, but I kept it as a number for consistency.

2020-12-29 14:28 UTC, petebacondarwin commented on packages/compiler/src/expression_parser/parser.ts
>          startIndex = input.indexOf(start, charIndex);
```suggestion
        if (input.startsWith(start, charIndex)) {
          startIndex = charIndex;
        }
```

2020-12-29 14:40 UTC, crisbeto commented on packages/compiler/src/expression_parser/parser.ts
>          startIndex = input.indexOf(start, charIndex);
Isn't that basically the same? If the input starts with the start character, the index is going to be the same as the `charIndex`.

2020-12-29 15:03 UTC, petebacondarwin commented on packages/compiler/src/expression_parser/parser.ts
>          startIndex = input.indexOf(start, charIndex);
But if it doesn't start with the start character, `indexOf()` will find a later one, even though we are only really interested in one that appears at `charIndex`. So if the string was very long, then `indexOf` would have to search all the way to the end of the string for every character, which I think makes O(n^2), right?

Moreover, the `indexOf()` doesn't know about quoted strings so it would find the `{{` in `abc '{{' def`.

2020-12-29 15:27 UTC, crisbeto commented on packages/compiler/src/expression_parser/parser.ts
>          startIndex = input.indexOf(start, charIndex);
Ah, you're right. Changed to your suggestion.

2020-12-29 15:39 UTC, petebacondarwin approved these changes
Great! Thanks for the quick turnaround.

2021-01-05 17:46 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:350159619:BASE:350159632:1609868789183:cd06c4d9).

2021-01-05 19:24 UTC, AndrewKushnir commented
FYI, presubmit is successful for the changes in this PR.

2021-01-05 20:22 UTC, AndrewKushnir approved these changes

2021-01-05 21:57 UTC, closed without merging