feat(compiler-cli): provide the animations for `DirectiveMeta`
angular/angular pull request #40300
Opened 2021-01-04 01:48 UTC by ivanwonder

In `language-service`, the `checker.getDirectiveMetadata` doesn't return the animations meta of the `Component`.
but it's useful for animation completion.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-01-05 19:10 UTC, AndrewKushnir reviewed
@ivanwonder, thanks for the PR!

I've left a couple comments and also added @JoostK as a reviewer to take another look as well.

Thank you.

2021-01-05 19:10 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    let animations: Map<string, string>[]|undefined;
I'd propose to use `null` instead of `undefined` here:
```suggestion
    let animations: Map<string, string>[]|null = null;
```
and also make the `animations` field of the `DirectiveMeta` structure non-optional. This should be more inline with the rest of the code.

2021-01-05 19:10 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +              (analysis.meta.animations as WrappedNodeExpr<ts.ArrayLiteralExpression>).node) as any;
Can we avoid having `any` here?

2021-01-05 21:18 UTC, JoostK requested changes
Hi @ivanwonder, thanks for taking the time to make progress towards support animation completions. I have a few suggestions below, PTAL.

Additionally, I would prefer if support for animation completions could land together with adding the necessary compiler bits, as to avoid introducing logic without any usages and knowing that it will end up satisfying the desired goal. It's fine to have multiple commits to separate the work into smaller chunks, though, so you can just extend this PR with new commits as you see fit.

2021-01-05 21:18 UTC, JoostK commented on packages/compiler/src/render3/view/t2_api.ts
> +  animations?: Map<string, string>[];
The value type of `string` is not accurate here; animations are a complex structure of objects to describe the animation sequences. This also isn't necessarily an array of `Map`s, as it could be entirely dynamic as mentioned before, and animations also support nested arrays (e.g. `[[trigger('trigger')]]` is supported). If we have logic to extract just the animation trigger names as suggested before, this comment will also be addressed.

2021-01-06 03:56 UTC, ivanwonder commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +        animationsMeta,
@JoostK I add a new `animationsMate` here because I don't know why the `meta.animations` will be replaced during the compilation step, see the comment in line 346.

2021-01-06 03:56 UTC, ivanwonder commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +  animationsMeta: string[]|'dynamic'|null;
> This could be modelled as e.g. string[] | 'dynamic' | null to distinguish statically analyzable animation triggers, dynamic animations and no animations. It does not allow for partially dynamic animations, but I would keep it simple for now (treat it as dynamic if it's not possible to extract all trigger names)

@JoostK  I think it's better to be `Array<string|DynamicValue>|null`. It's still useful to provide the completion if not all trigger names can be extracted.
Now I will ignore the `DynamicValue` if the nested array contains the dynamic animations. Or I should clear the collected name and treat it as `dynamic`

2021-01-06 20:17 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +        animationsMeta,
That comment is outdated, it used to be associated with `pipes` and `directives` (see 27bc7dcb43ec20d185b92986cba06cbc0329b58f). Feel free to remove it.

You'll need a new field for this data anyway, as the existing `animations` is a `WrappedNodeExpr` that just contains the original `ts.Node` from the source, without having gone through any static analysis.

2021-01-06 20:17 UTC, JoostK commented on packages/compiler/src/render3/view/t2_api.ts
> +  animations: string[]|'dynamic'|null;
Consider using a more descriptive name for this as well, ideally it's identical to the name used in the analysis object.

2021-01-06 20:17 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/test/component_spec.ts
> +          }) class TestCmp {}
```suggestion
          })
          class TestCmp {}
```

2021-01-06 20:17 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/test/component_spec.ts
> +            animations: [trigger('animationName'), [trigger('nestedAnimationName')]],
You'll also want tests for dynamic data, where two cases are relevant:

1. the value itself is completely dynamic:

```ts
animations: buildComplexAnimations(),
```
2. an individual animation is dynamic:

```ts
animations: [trigger('a'), buildComplexAnimations()],
```

where `buildComplexAnimations` can be something that will be dynamic due to containing multiple statements:

```ts
function buildComplexAnimations() {
  const name = 'complex';
  return [trigger(complex)];
}
```

2021-01-07 07:54 UTC, ivanwonder commented on packages/compiler/src/render3/view/t2_api.ts
> +
I just add a new interface, that's more descriptive.
Maybe it's better to use `isPartial` instead of `includeDynamicAnimations`.

2021-01-13 20:04 UTC, JoostK reviewed
Hi @ivanwonder this looks much better now! I left a bunch of suggestions.

What is your plan on incorporating this into the LS? As mentioned before I would prefer it we could make this change together with the support in the language service's autocompletion capabilities. That avoids leaving the compiler in a state where the computed data isn't yet used.

Additionally, the commit is currently a "feat", but I'd consider it just a "refactor" as there's no user facing change that is worth noting in the changelog.

2021-01-14 02:20 UTC, ivanwonder commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +        const res: string[] = [];
The `animations` should be `Array`, but if the user's input is not `Array` (although the ts will report the error). This is why I add the condition here. If it's no `Array`, the function `collectAnimationNames` will be broken.

2021-01-14 02:21 UTC, ivanwonder commented
Thanks, I will add another commit to provide the capabilities in language service in this PR soon.

2021-01-14 08:42 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +        const res: string[] = [];
You are correct. My suggestion was to remove the `res` variable but I somehow goofed up the selection range. But I notice you removed the `res` so this one has been resolved :-)

2021-01-16 12:10 UTC, ivanwonder commented
Now I have added a new commit to support animation in the language service.
I pass the `position` into the `CompletionBuilder` because I need to determine where the cursor is (e.g. `<input (@my¦.done¦)>`). I don't know if it's the right way, but if not, maybe we need three new `Node` for animation name and animation phase to locate which node the cursor is in.

2021-12-16 20:48 UTC, atscott commented
@ivanwonder Sorry this got lost. I think the best way forward would be to create a new PR for this if it's something you still want to contribute. Thanks for all your hard work with your language service contributions!

2021-12-16 20:48 UTC, closed without merging

2021-12-17 15:13 UTC, ivanwonder commented
Why the `packages/language-service/test/completions_spec.ts` has been removed? 🤔️

2021-12-17 15:43 UTC, JoostK commented
> Why the `packages/language-service/test/completions_spec.ts` has been removed? 🤔️

@ivanwonder looks like it was accidentally removed in bb9ff6003c620b3cf00232189d60097395382802, together with `packages/language-service/test/definitions_spec.ts` (and perhaps others). The Ivy implementation had already been promoted to take the place where the VE tests used to be, perhaps some wires got crossed during a rebase there.

2021-12-17 18:44 UTC, atscott commented
@ivanwonder @JoostK Those were intentionally removed because they were tests for the legacy VE language service. Every Ivy test lived under the packages/language-service/ivy subfolder.

2021-12-17 18:54 UTC, JoostK commented
> @ivanwonder @JoostK Those were intentionally removed because they were tests for the legacy VE language service. Every Ivy test lived under the packages/language-service/ivy subfolder.

These tests did exist for Ivy as well:

https://github.com/angular/angular/blob/12.2.x/packages/language-service/ivy/test/completions_spec.ts

your commit to promote the Ivy LS into the primary language-service folder landed before the VE cleanup, which is how I think the VE cleanup ended up removing files that had since been replaced with Ivy variants.

2021-12-17 19:03 UTC, atscott commented
@JoostK Ahhhhh. Yes, you're right. Anything in that commit which touched the language service should likely be reverted since I had already removed VE in a separate commit.