docs: fix template variable name in interpolation doc and fix example CSS
angular/angular pull request #40451
Opened 2021-01-15 20:12 UTC by kapunahelewong

Fixes #40403 and fixes imgs and layout of example
that are unrestrained and thus are too big in StackBlitz.

Possible To do: 
Remove `#customerInput` section in example. Would like @petebacondarwin's take on whether I should remove it or not. It is no longer in the doc but being in the example provides a working sample devs can reference. Beginners might especially find it helpful. I could go either way. We do have a doc dedicated to template ref vars, so maybe we don't need it.

2021-01-15 20:26 UTC, mary-poppins commented
You can preview 63dca3d at https://pr40451-63dca3d.ngbuilds.io/.

2021-01-16 00:53 UTC, jessicajaniuk approved these changes

2021-01-16 13:29 UTC, petebacondarwin requested changes
@kapunahelewong - thanks for taking this one.

I think that rather than changing the template reference snippet we should change the `currentCustomer` property in the `AppComponent` to be called a `customer`. This would then match the text in the guide. And we could then have a snippet of the `AppComponent` to show the property. Does that make sense?

2021-01-19 15:39 UTC, kapunahelewong commented
Is this update more along the lines of what you were thinking, @petebacondarwin?

2021-01-19 16:09 UTC, petebacondarwin commented
Yeah sort of. But when I look at the preview everything from

> The previous example presents a name collision. The component has a customer property and the *ngFor defines a customer template variable.

to the end of that section does read clearly.

2021-01-19 19:35 UTC, mary-poppins commented
You can preview 8424b2d at https://pr40451-8424b2d.ngbuilds.io/.

2021-01-19 19:36 UTC, petebacondarwin commented on aio/content/guide/interpolation.md
> +The `customer` within the `ngFor` is in the context of the `<ng-template>` and so refers to the `customer` in the class, in this case `Ebony` and `Chiho`.
```suggestion
The `customer` within the `ngFor` is in the context of the `<ng-template>` and so refers to the `customer` in `ngFor` iteration, in this case `Ebony` and `Chiho`.
```

2021-01-19 21:18 UTC, mary-poppins commented
You can preview d91d571 at https://pr40451-d91d571.ngbuilds.io/.

2021-01-20 09:04 UTC, petebacondarwin approved these changes
Great! We got there. Thanks for you patience @kapunahelewong.

I made one small suggestion below; and can you update the commit message, since it appears to be a bit out of date now.

Reviewed-for: global-docs-approvers

2021-01-20 09:04 UTC, petebacondarwin commented on aio/content/guide/interpolation.md
> +<code-example path="interpolation/src/app/app.component.1.ts" region="var-collision" header="src/app/app.component.ts"></code-example>
Should we move the snippet before the preceding paragraph? I.e. directly after the 

> An `ngFor` then lists each `customer` in the `customers` array.

paragraph?

2021-01-20 14:41 UTC, petebacondarwin approved these changes
LGTM!

Reviewed-for: global-docs-approvers

2021-01-20 14:43 UTC, kapunahelewong commented
Thank you so much for your guidance on this PR, @petebacondarwin! 

Commit message updated.

2021-01-20 14:48 UTC, mary-poppins commented
You can preview 7b10be6 at https://pr40451-7b10be6.ngbuilds.io/.

2021-01-21 00:13 UTC, closed without merging