docs: fix NG0201 error description
angular/angular pull request #40500
Opened 2021-01-21 09:53 UTC by cexbrayat

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The current description of NG0201 is `NG0201: No provider for found injectorDetails`
(which is probably a copy/paste of the source code `No provider for ${stringifyForError(token)} found${injectorDetails}``
See https://angular.io/errors/NG0201

Issue Number: N/A

## What is the new behavior?

It fixes the description, by changing it to the video's title.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-01-21 10:12 UTC, petebacondarwin requested changes
Thanks for catching this @cexbrayat - one comment

2021-01-21 10:12 UTC, petebacondarwin commented on aio/content/errors/NG0201.md
> +@shortDescription No provider for {Class} found!
The reason for this incorrect description is that it was extracted from https://github.com/angular/angular/blob/3b2e5be6cb5ee7d0d7630a6cc3a2d7111dc3dad9/packages/core/src/render3/errors_di.ts#L45

I would note that the `token` mentioned in the code above doesn't have to be a "class", so I wonder if this should be:

```suggestion
@shortDescription No provider for {token} found!
```

2021-01-21 10:15 UTC, cexbrayat commented on aio/content/errors/NG0201.md
> +@shortDescription No provider for {Class} found!
Sure! Note that the title of the video is using `Class`, hence my choice.

https://www.youtube.com/watch?v=lAlOryf1-WU

2021-01-21 10:16 UTC, cexbrayat commented on aio/content/errors/NG0201.md
> +@shortDescription No provider for {Class} found!
Now fixed according to your suggestion.

2021-01-21 17:35 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2021-01-21 18:08 UTC, IgorMinar approved these changes
oops.. thanks for catching this.

2021-01-22 17:48 UTC, petebacondarwin approved these changes

2021-01-22 17:48 UTC, petebacondarwin reviewed
Reviewed-for: public-api

2021-01-22 17:49 UTC, petebacondarwin approved these changes
Reviewed-for: public-api

2021-01-22 18:01 UTC, atscott approved these changes
reviewed-for: public-api

2021-01-22 21:35 UTC, closed without merging