fix(currencyPipe): set currencyCode from injected value
angular/angular pull request #40505
Opened 2021-01-21 13:24 UTC by gvmohzibat

When providing `DEFAULT_CURRENCY_CODE`, it's expected that the `CurrenyPipe` would pass it as `currencyCode` to `formatCurrency` function.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently providing the `DEFAULT_CURRENCY_CODE` changes the symbol that's being displayed but it's not used inside the `formatCurrency` function for getting the `minFrac` ([link to source code](https://github.com/angular/angular/blob/master/packages/common/src/i18n/format_number.ts#L156)), therefore the default value (USD) is being used. So as an example, despite providing `{ provide: DEFAULT_CURRENCY_CODE, useValue: 'IRR' }`, the code `{{ 1000 | currency }}` will result in `1,000.00` but it should be `1,000` based on [this line](https://github.com/angular/angular/blob/69385f7df4/packages/common/src/i18n/currencies.ts#L70)

## What is the new behavior?

With this change, the provided value for `DEFAULT_CURRENCY_CODE` will be passed as `currencyCode` to `formatCurrency` function.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-01-21 13:30 UTC, petebacondarwin requested changes
Thanks for this PR - this fix looks sound.
Could you please provide a unit test for this functionality by adding an `it` clause to the describe block at https://github.com/angular/angular/blob/7b2aac97df63717fd2dfbb81903d12221ae29ba1/packages/common/test/pipes/number_pipe_spec.ts#L117

2021-01-21 18:56 UTC, gvmohzibat commented
Done.
@petebacondarwin

2021-01-21 19:36 UTC, petebacondarwin requested changes
Thanks for adding the test.

2021-01-21 19:36 UTC, petebacondarwin commented on packages/common/test/pipes/number_pipe_spec.ts
> +          expect(pipe.transform(1234)).toEqual('1,234');
Did you mean for this to be `clpPipe`?

Please can you move the new expectation into its own `it` clause that describes what is being tested. And then you don't really need the external variable. For example something like:

```ts
it('should use the injected default currency code if none is provided', () => {
  const clpPipe = new CurrencyPipe('en-US', 'CLP');
  expect(clpPipe.transform(1234)).toEqual('1,234');
});
```

2021-01-21 20:22 UTC, petebacondarwin commented on packages/common/src/pipes/number_pipe.ts
> +      return formatCurrency(num, locale, currency, currency, digitsInfo);
@Joostk just pointed out that this is not correct. Instead we need to initialize the `currencyCode` correctly in the `transform()` call:

```ts
  transform(
      value: number|string|null|undefined, currencyCode: string = this._defaultCurrencyCode,
      display: 'code'|'symbol'|'symbol-narrow'|string|boolean = 'symbol', digitsInfo?: string,
      locale?: string): string|null {
```

And then we can simplify line 251:

```
let currency = currencyCode;
```

And the rest can stay as it was before.

2021-01-22 21:51 UTC, gvmohzibat commented on packages/common/test/pipes/number_pipe_spec.ts
> +          expect(pipe.transform(1234)).toEqual('1,234');
You're totally right. Sorry, I don't have enough experience in writing tests. Will do.

2021-01-22 21:59 UTC, gvmohzibat commented on packages/common/src/pipes/number_pipe.ts
> +      return formatCurrency(num, locale, currency, currency, digitsInfo);
I see! :+1:

2021-01-23 12:30 UTC, petebacondarwin requested changes
Thanks @gvmohzibat - we are getting there. Just a couple more tweaks.

2021-01-23 12:30 UTC, petebacondarwin commented on packages/common/test/pipes/number_pipe_spec.ts
> +		});
The output actually contains the `CLP` as the currency.
Also we need to fix the indentation.

```suggestion
        it('should use the injected default currency code if none is provided', () => {
		      const clpPipe = new CurrencyPipe('en-US', 'CLP');
		      expect(clpPipe.transform(1234)).toEqual('CLP1,234');
		    });
```

2021-01-24 18:58 UTC, petebacondarwin approved these changes

2021-03-04 22:18 UTC, mhevery approved these changes

2021-03-04 22:21 UTC, mhevery commented
[presubmit](http://test/OCL:361002828:BASE:361002860:1614896442108:685ce6b2)

2021-03-06 09:55 UTC, petebacondarwin commented
@googlebot I consent.

2021-03-07 22:18 UTC, AndrewKushnir commented
[Global Presubmit](https://test.corp.google.com/OCL:361449108:BASE:361449137:1615155475672:ade562eb) (internal-only link).

2021-03-07 23:19 UTC, AndrewKushnir commented
Quick update after running tests in Google's codebase: this change is causing some internal tests to fail and more investigation is needed, so I'm adding the "blocked" label for now. We'll perform further investigation and keep this thread updated. Thank you.

2021-03-13 01:12 UTC, AndrewKushnir commented
Hi @vmohir,

I've performed additional investigation and it turned out that the problem was caused by passing empty string as the currency code (with the expectation that the pipe will use the default code). Here is an example of such situation:

https://stackblitz.com/edit/angular-pr-40505?file=src%2Fapp%2Fapp.component.html

Currently it outputs `$10.00`, but with the changes from this PR it'd be just `10.00` (the `$` sign is missing).

I've also confirmed that by creating a test (in `packages/core/test/acceptance/pipe_spec.ts` file):

```
  fit('...', () => {
    @Component({
      template: `{{ amount | currency:currencyCode }}`,
    })
    class App {
      amount = 10;
      currencyCode = '';
    }

    TestBed.configureTestingModule({
      imports: [CommonModule],
      declarations: [App],
    });
    const fixture = TestBed.createComponent(App);
    fixture.detectChanges();

    expect(fixture.nativeElement.textContent).toBe('$10.00'); // will fail since the output would be `10.00`
  });
```

I believe the problem is that the default value of the `currencyCode` argument is not applied when an empty string is passed, but in the previous logic (with `||` comparison), empty string would be a false-y value, thus default code is used.

Looking at the change, it feels like the suggested change and the current code works quite similar (with the exception of the empty string case described above). The mentioned Stackblitz demo also contains the code from the test added in this PR and it seems to be working correctly even without any changes. So I'm a bit confused and I think it'd be great to:

- come up with a test case that would fail with the current version of code and would pass after the change
- add a test case with currency code defined as an empty string and make sure there is no regression

Please let me know if additional information is needed.

Thank you.

2021-03-15 14:05 UTC, vmohir commented
Hi @AndrewKushnir,

> come up with a test case that would fail with the current version of code and would pass after the change

I believe the test that I've currently added, does the job.

> add a test case with currency code defined as an empty string and make sure there is no regression

about this part, I think if I revert the change on [line 271](https://github.com/angular/angular/pull/40505/files#diff-34f4c0d152e190d625cd388d9fb6a1054d7795f3b39ee6b29063843898f1dcbbL271), the issue will be fixed. Would you please check that line and see if I've understood your request.

2021-03-16 01:31 UTC, AndrewKushnir commented
> >come up with a test case that would fail with the current version of code and would pass after the change
>
> I believe the test that I've currently added, does the job.

@vmohir yes, you are right, without your fix the fractional part is incorrect in the test.

> about this part, I think if I revert the change on line 271, the issue will be fixed. Would you please check that line and see if I've understood your request.

I've tested the following version (lines 270-271):

```
currencyCode = currencyCode || this._defaultCurrencyCode; 
let currency: string = currencyCode;
// ... the rest of the code ...
```

and all targets worked correctly in Google's codebase. So I guess the question is whether we want to be less restrictive and allow false-y `currencyCode` argument values (like an empty string) to be treated as "no value" and use the default instead, or keep existing change (where only `undefined` triggers default value) and do a cleanup in Google's codebase.

@mhevery @petebacondarwin what do you think?

2021-03-16 08:40 UTC, petebacondarwin commented
I think we should leave the behaviour as it is before this PR: any falsy value causes the default currency code to be used.
While this is not really consistent with how we normally handle optional parameters - and if we were writing this from scratch I wouldn't choose it - I don't think there is much value in making such a breaking change at this point.

2021-04-28 13:36 UTC, petebacondarwin requested changes

2021-04-28 13:36 UTC, petebacondarwin commented on packages/common/src/pipes/number_pipe.ts
> +    let currency: string = currencyCode;
@vmohir  - further to our discussion, I think the plan is to revert this change, yes?

2021-04-28 20:14 UTC, vmohir commented on packages/common/src/pipes/number_pipe.ts
> +    let currency: string = currencyCode;
Yes, I think so.

2021-05-04 10:40 UTC, petebacondarwin commented
@vmohir - do you have some time to do the final updates?

2021-05-05 07:14 UTC, vmohir commented
Sorry I did some wrong git commands

2021-05-05 10:09 UTC, petebacondarwin requested changes

2021-05-05 10:09 UTC, petebacondarwin commented on packages/common/src/pipes/number_pipe.ts
> +    let currency: string = currencyCode;
Please revert this change:

```suggestion
    let currency: string = currencyCode || this._defaultCurrencyCode;
```

2021-05-08 12:30 UTC, petebacondarwin reviewed
Thanks for the update @vmohir - can you either squash the two commits into one or convert the second commit to a "fixup" commit as described here https://github.com/angular/angular/blob/master/docs/FIXUP_COMMITS.md

Also, while you are doing this, please rebase on master to get the CI to run.

2021-05-14 06:36 UTC, vmohir commented
Sorry for being late. Done.

2021-05-14 14:07 UTC, petebacondarwin commented
@vmohir thanks for merging the commits. Did you actually rebase on the current upstream master? See the `setup` failure in the CI.

2021-05-31 07:10 UTC, vmohir commented
I'm not sure if I correctly rebased it. But I think it's good.

2021-05-31 19:44 UTC, petebacondarwin approved these changes

2021-06-01 20:35 UTC, jessicajaniuk approved these changes
LGTM :cookie:

2021-06-01 23:49 UTC, AndrewKushnir commented
[Presubmit #2](http://test/OCL:376946737:BASE:376946761:1622591371936:395402a0) (will also run a global one tonight).

2021-06-03 17:52 UTC, closed without merging