docs(http): add custom JSONParser example
angular/angular pull request #40645
Opened 2021-01-30 22:19 UTC by petebacondarwin

Update the HTTP guide and associated example to demonstrate
how an interceptor can be used to provide a custom JSON parser.

Resolves #21079

2021-02-01 18:20 UTC, mary-poppins commented
You can preview 4db6659 at https://pr40645-4db6659.ngbuilds.io/.
You can preview eb73c62 at https://pr40645-eb73c62.ngbuilds.io/.

2021-02-01 18:41 UTC, gkalpak requested changes
Just a couple of comments/suggestions. Otherwise lgtm :+1:

2021-02-01 18:41 UTC, gkalpak commented on aio/content/examples/http/src/app/http-interceptors/custom-json-interceptor.ts
> +  }
I think it would be helpful to add some comments in this method, explaining what is going on.
(Potentially in other methods as well, but I founf this a little too "cryptic".)

2021-02-01 18:41 UTC, gkalpak commented on aio/content/guide/http.md
> +{@ custom-json-parser}
```suggestion
{@a custom-json-parser}
```

2021-02-01 18:41 UTC, gkalpak commented on aio/content/examples/http/src/app/http-interceptors/custom-json-interceptor.ts
> +export class JsonParser {
I am a little torn on this. Setting this up as you have here (using DI and having a default implementation and a "customized" one) has its merit, but it also increases the complexity and the concepts that people need to mentally process.

The exampe would be easier to follow imo if either:
- there was one JSON parser class (which would act as both the DI token and the implementation)...or...
- the `CustomJsonInterceptor` did the JSON parsing itself (without importing a parser class).

I don't feel strongly about this, but I think the pros of a simpler example would outweight the cons.

2021-02-01 19:35 UTC, zarend approved these changes
👍 awesome, thanks for doing this.

2021-02-01 19:35 UTC, zarend commented on aio/content/examples/http/src/app/config/config.component.ts
> +  getType(val: any): string {
Minor Suggestion: make the return type of this function:

` "string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function" | "date" | "array"`

That way callers can switch on the value this returns.

This is not a blocker for me :).

2021-02-02 15:08 UTC, petebacondarwin commented on aio/content/examples/http/src/app/config/config.component.ts
> +  getType(val: any): string {
There is always a tension in these examples between completeness and brevity.

I think in this case adding the long explicit return type would be something you would do in real life but would only. make this example less clear.

2021-02-02 15:12 UTC, petebacondarwin commented on aio/content/examples/http/src/app/http-interceptors/custom-json-interceptor.ts
> +export class JsonParser {
I agree that in a closed environment it would be simpler to embed the custom parser into the interceptor.

I explicitly wanted to call out how you could write an interceptor to replace the JSON parser, where the downstream developer only had to provide a parser and not thing too much about how it got wired up.

This is because it is that requirement that was being requested in the original issue.

I also considered only having a single CustomJsonParser class, but then you would need to define a DI token and an interface, which makes the example even more crowed.

2021-02-02 15:12 UTC, petebacondarwin commented on aio/content/guide/http.md
> +{@ custom-json-parser}
Oops!

2021-02-02 15:12 UTC, petebacondarwin commented on aio/content/examples/http/src/app/http-interceptors/custom-json-interceptor.ts
> +  }
Good call.

2021-02-02 15:35 UTC, mary-poppins commented
You can preview 19a190d at https://pr40645-19a190d.ngbuilds.io/.

2021-02-03 11:22 UTC, gkalpak approved these changes
:100:

2021-02-03 11:22 UTC, gkalpak commented on aio/content/examples/http/src/app/http-interceptors/custom-json-interceptor.ts
> +import {map} from 'rxjs/operators';
Please revert these 😇

2021-02-03 11:25 UTC, petebacondarwin commented on aio/content/examples/http/src/app/http-interceptors/custom-json-interceptor.ts
> +import {map} from 'rxjs/operators';
Darn it!

2021-02-03 11:28 UTC, petebacondarwin commented
@TeriGlover would you be able to give this a once-over? Thanks

2021-02-03 11:35 UTC, mary-poppins commented
You can preview 9e5d9e6 at https://pr40645-9e5d9e6.ngbuilds.io/.

2021-02-16 16:03 UTC, closed without merging