fix(compiler-cli): don't crash when we can't resolve a resource
angular/angular pull request #40660
Opened 2021-02-01 23:28 UTC by zarend

Produces a diagnostic when we cannot resolve a component's external style sheet or external template.

The previous behavior was to throw an exception, which crashed the
Language Service.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-02-02 00:43 UTC, zarend commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +      const nodeForError = component.get('styleUrls') ?? Decorator.nodeForError(decorator);
use the `styleUrls` property when available because it is more specific to the root cause of the error

2021-02-02 20:30 UTC, atscott approved these changes

2021-02-02 20:30 UTC, atscott commented on packages/compiler-cli/src/ngtsc/diagnostics/src/error_code.ts
> +
nit: extra new line not needed

2021-02-02 20:30 UTC, atscott commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +
nit: extra new line not needed

2021-02-02 20:33 UTC, atscott commented
Could you also add "fixes https://github.com/angular/vscode-ng-language-service/issues/1079" to your commit message footer?

2021-02-03 00:54 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +          ErrorCode.COMPONENT_RESOURCE_NOT_FOUND, nodeForError, e.message);
Instead of `e.message` which is the message from an internal compiler assertion failure, we should provide a thoughtful, actionable diagnostic message to the user which explains the problem.

2021-02-03 01:00 UTC, alxhub requested changes

2021-02-03 01:00 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +      const nodeForError = styleUrlsExpr ?? Decorator.nodeForError(decorator);
Yikes, this gets messy. There are two problems here:

1) we're using the same `nodeForError` for each style URL, regardless of where it came from.

Some of the URLs in `styleUrls` may have come from the `styleUrls` of the component.
Some of the URLs may have come from `<link rel=stylesheet>` tags in the template.

Additionally, we're using the entire `styleUrls` expression for the diagnostic, when in fact there might be multiple URLs and it's a specific one that failed to resolve.

I don't think we should deal with `<link rel=stylesheet>`-based URLs at the moment - we can punt on that and use `Decorator.nodeForError` there. But we _should_ at least attempt to select a narrower expression if the URL in question is in `styleUrls`.

That means that when we read `styleUrls`, we should check if it's a `ts.ArrayLiteralExpression`. If so, we should attempt to resolve each entry within it individually, so that we can retain a specific `ts.Expression` node for each URL. Then, if the URL fails to resolve later, we can show the diagnostic and highlight the real expression for each URL.

If we _have_ to fall back on resolving the whole of `styleUrls` at once, then that's fine - and we can use the entire expression in that case. But I'd prefer if the primary experience showed a narrower diagnostic.

2021-02-04 21:03 UTC, zarend commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +      if (!isStringArray(evaluatedStyleUrls)) {
use a type guard so we don't have to cast `styleUrl` as a `string` in the code below. This is a bit more robust than casting because typescript can validate that `styleUrl` is actually a `string`. With the typecast, typescript says "I don't see any reason why this wouldn't be a string, so I'll treat it as a string".

2021-02-04 21:07 UTC, zarend commented
hi @alxhub 👋 . The PR fixes have been made and this is ready for your eyes again 👀

2021-02-04 21:43 UTC, atscott requested changes

2021-02-04 21:43 UTC, atscott commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    }
```suggestion
    const componentStyles = this._extractComponentStyleUrls(component);
    const templateStyles = this._extractTemplateStyleUrls(template);

    const styles: string[] = [];
    const styleUrls: StyleUrl[] = [...componentStyles, ...templateStyles];
```

It looks like there's not really a reason `styles` or `styleUrls` should be set to `null`. In the end, the output for `styles` is `styles: styles || []` and `styleUrls` is just iterated so it makes no difference if it's empty or `null`.
In addition to that, there would then not really be a reason for `_extractComponentStyleUrls` or `_extractTemplateStyleUrls` to return `null` either but can instead return empty array.

2021-02-04 21:43 UTC, atscott commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +interface StyleUrl {
```suggestion
interface StyleUrlMeta {
```

I would rename this to `StyleUrlMeta` along with all the functions and variables that get/refer to this. They are no longer just urls, but metadata with more information now. It's rather difficult to keep this straight when reading the code later on.

2021-02-04 21:43 UTC, atscott commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +// determines if the result of an evalutation is a string array.
```suggestion
/** Determines if the result of an evaluation is a string array. */
```

2021-02-04 21:43 UTC, atscott commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +      if (template === null) {
I think this was easier to read as it was before. Please move it back to the `then` of the `_preloadAndParseTemplate` rather than allowing a `null` template in this function.

2021-02-04 21:43 UTC, atscott commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> -    const resolveStyleUrl = (styleUrl: string): Promise<void> => {
`resolveStyleUrl` could instead been updated to accept more arguments - `nodeForError` and the `ResourceTypeForDiagnostics`, right? Can we make that change instead - it's a smaller diff, has better code reuse, and is easier to read the `Promise.all...map...then`.

2021-02-04 21:43 UTC, atscott commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +  private _extractComponentStyleUrls(
Do we need a helper function for this? This seems easy enough to inline, especially if we're not returning `null`.

2021-02-04 22:09 UTC, zarend commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    }
I think the existing code is trying to avoid allocating an empty array when it's not necessary for better perf.

For `styles`, initializing as an empty array would not cause a performance hit because the output ends up as `styles: styles || []`. Let's go ahead and initialize it as `[]` ✔️ 

`styleUrls` is null in the output when there are no styles, so changing it to empty array would *theoretically* cause a perf hit. Initializing it as `[]` would cause 1 extra array to be allocated each analysis phase for components with no styles. If you ask me, I'd say this is probably fine, but when do we need to be careful about this?

2021-02-04 22:13 UTC, zarend commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> -    const resolveStyleUrl = (styleUrl: string): Promise<void> => {
I can do that no problem, but we still need to use `Promise.all...map...then`. We `map` over the style urls, pass then to `Promise.all`, and throw away the result with `.then(() => undefined)`

2021-02-04 22:18 UTC, zarend commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +interface StyleUrl {
How about `StyleUrlData`. It disambiguates because the actual `styleUrl` string and this object with extra properties. metadata has a special meaning in the context of the trait compiler, and I don't think this counts as metadata?

2021-02-04 22:19 UTC, atscott commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    }
I would really not think this theoretical performance difference is significant enough to matter.

2021-02-04 22:22 UTC, zarend commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +interface StyleUrl {
cool, I'll rename it to `StyleUrlMeta` ✔️

2021-02-04 22:24 UTC, zarend commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    }
okay, I'll change it to use `[]` instead of `null` ✔️

2021-02-04 22:40 UTC, zarend commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +  private _extractComponentStyleUrls(
Well, doing it this way gives us consistency with `_extractTemplateStyleUrls`

2021-02-04 22:56 UTC, zarend commented
@atscott I've made PR fixes in response to your comments and this is ready for your eyes again :)

@alxhub, since you last saw this, I renamed a few variables, improved misc code comments, used a type guard for validating evaluation results and made misc code style fixes.

2021-02-08 22:26 UTC, alxhub approved these changes

2021-02-08 22:26 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +  source: 'decorator'|'template';
Consider making this `ResourceTypeForDiagnostic.StylesheetFromTemplate|ResourceTypeForDiagnostic.StylesheetFromDecorator`.

2021-02-08 22:26 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +interface StyleUrlMeta {
I believe this should be exported, since it's now depended upon by an exported type.

2021-02-08 22:26 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +              const nodeForError = template.declaration.isInline ?
You might encounter some g3 issues here, as g3 is not always able to do type narrowing in the same way as TS externally.

2021-02-09 00:53 UTC, jelbourn commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +      if (!isStringArray(evaluatedStyleUrls)) {
Similar to Andrew's comment, any commentary like this should be turned into a code comment

2021-02-09 00:53 UTC, jelbourn commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    } catch (e) {
If `e` is unused here, you should be able to omit it
```suggestion
    } catch {
```

2021-02-09 02:08 UTC, jessicajaniuk approved these changes
LGTM other than the outlying requested comments

reviewed-for: public-api

2021-02-09 11:29 UTC, petebacondarwin approved these changes
Approval for the public-api, which I think is simply the new ERROR code?
Added a couple of non-behavioural NITs and I agree with the outstanding comments.

Reviewed-for: public-api

2021-02-09 11:29 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
>      if (styleUrls !== null) {
AFAICT `styleUrls` will never be `null` since it is now defined above as an array. So this check seems superfluous.

2021-02-09 11:29 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +      styles = [];
I don't think this line is needed? The `styles` variable is now defined as an empty array above.

2021-02-09 11:29 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +enum ResourceTypeForDiagnostics {
Could we make this `const enum`?

2021-02-09 16:19 UTC, atscott approved these changes
reviewed-for: public-api

2021-02-09 16:26 UTC, zarend commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    const resolveStyleUrl = (styleUrl: string, node: ts.Node): Promise<void> => {
fixed, named it to `nodeForError`

2021-02-09 16:26 UTC, zarend commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +      const nodeForError = styleUrlsExpr ?? Decorator.nodeForError(decorator);
👍

2021-02-09 16:38 UTC, zarend commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    } catch (e) {
That was more intended as a comment for the reviewers to explain why I did a (small) refactor here. For future readers of this code, the type signature explains what `isStringArray` does.

2021-02-09 16:50 UTC, zarend commented
> Approval for the public-api, which I think is simply the new ERROR code?
> Added a couple of non-behavioural NITs and I agree with the outstanding comments.
> 
> Reviewed-for: public-api

Yes, the public api change is adding a new error code. ✔️

2021-02-09 19:12 UTC, jelbourn approved these changes
LGTM

Reviewed-for: public-api

2021-02-09 19:12 UTC, jelbourn commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    } catch (e) {
I think you responded to my other comment on this thread

2021-02-10 18:44 UTC, alxhub approved these changes

2021-02-10 18:48 UTC, closed without merging