fix(compiler-cli): `readConfiguration` existing options should override options in tsconfig
angular/angular pull request #40694
Opened 2021-02-03 15:17 UTC by alan-agius4

At the moment, when passing an Angular Compiler option in the `existingOptions` it doesn't override the defined in the TSConfig.

2021-02-04 11:41 UTC, petebacondarwin requested changes
Ugh, I hate how convoluted this whole area of code is.
I appreciate that this is not the fault of this PR.
But I wonder if we ought to take this opportunity to clean it up rather than patching it after the fact, which is basically what we are doing in this PR.

As I understand it there are "TypeScript" configurations and "Angular" configurations.
We have to effectively parse the `tsconfig.json` twice with two different tools to extract each.
On top of this the caller can pass in an object of programmatically defined `existingOptions` which should override those that appear in the `tsconfig.json`. But since this `existingOptions` (despite the typing) can contain Angular options too, we have to do this overriding twice.

So I think that the `config` object should only contain Angular options and the `parsed.options` should only contain TypeScript options.

I believe that the call to `ts.parseJsonConfigFileContent()` should already override the TypeScript options with those from `existingOptions` but I think that this will not apply the Angular parts of `existingOptions` over the top of those in `config`.

So I think that the right thing to do is to fix the `config` object so that it has the Angular options overridden by those in `existingOptions` before passing it to `createNgCompilerOptions()`, which should not have to care about overriding.

Does that sound right?

2021-02-04 11:41 UTC, petebacondarwin commented on packages/compiler-cli/src/perform_compile.ts
> +    ...(config.angularCompilerOptions ?? {}),
I don't believe the `?? {}` is needed here: [TS Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeBDA-ALigZ2AJwEsA7AcwBooAjTXQ0gXwG4AoAMwFciBjYAgeyJRWfPgAoAHllSZY9AJTJmUZVC4DcqgawIkMcREigosAcgEQTFAHQ3xVlBUqngAdz4mmzekA)

2021-02-04 11:41 UTC, petebacondarwin commented on packages/compiler-cli/src/perform_compile.ts
> +  mergedConfig.enableIvy = !!mergedConfig.enableIvy;
Nice refactoring

2021-02-04 11:41 UTC, petebacondarwin commented on packages/compiler-cli/test/perform_compile_spec.ts
> +  it('"existingOptions" should override options defined in tsconfig', () => {
```suggestion
  it('should override options defined in tsconfig with those defined in `existingOptions`', () => {
```

2021-02-08 13:49 UTC, petebacondarwin approved these changes
LGTM - just a couple of suggested refactorings.

2021-02-08 13:49 UTC, petebacondarwin commented on packages/bazel/src/ngc-wrapped/index.ts
> +  const allowedNgCompilerOptionsOverrides = [
Might as well make this a `Set()` and then you can do much faster check below.

2021-02-08 13:49 UTC, petebacondarwin commented on packages/compiler-cli/src/perform_compile.ts
> +          if (parentOptions && config.angularCompilerOptions) {
`parentOptions` will always be truthy, since it is initialized to `{}` above.

So we can drop this `if` and just do 

```ts
const existingNgCompilerOptions = {...config.angularCompilerOptions, ...parentOptions};
```

2021-02-08 13:49 UTC, petebacondarwin commented on packages/compiler-cli/src/perform_compile.ts
> +            }
I would move this block of code into its own function. Something like

```ts
getExtendedConfigPath(extendsValue: string): AbsoluteFsPath|null;
```

2021-02-08 13:57 UTC, alan-agius4 commented on packages/bazel/src/ngc-wrapped/index.ts
> +  const allowedNgCompilerOptionsOverrides = [
Indeed.

2021-02-08 14:05 UTC, alan-agius4 commented
@petebacondarwin updated.

2021-02-08 18:46 UTC, josephperrott approved these changes
LGTM

Reviewed-For: bazel

2021-02-08 19:50 UTC, JoostK commented on packages/bazel/src/ngc-wrapped/index.ts
> +    ...overrides,
I didn't know you could spread the result of `Object.entries` into an object literal, so I tried it and it looks like it doesn't work?

```ts
{...[['a', 1]]}
// -> {0: ["a", 1]}

{...Object.fromEntries([['a', 1]])}
// {a: 1}
```

which would be concerning if no tests fail

2021-02-08 19:50 UTC, JoostK commented on packages/bazel/src/ngc-wrapped/index.ts
> +  const {errors: userErrors, options} = ng.readConfiguration(project);
I'd use `options: userOptions` here as that should make it more clear how it differs from `config`.

2021-02-08 19:50 UTC, JoostK commented on packages/bazel/src/ngc-wrapped/index.ts
> +    ...overrides,
Additionally, it looks like `overrides` is what used to be `userConfig.angularCompilerOptions`? It used to be that Bazel configuration (`angularCompilerOptions` before) was preferred over user configuration (`userConfig.angularCompilerOptions`), but now this is the other way around?

Notice also that the previous behavior was pretty susceptible to bugs for e.g. boolean flags: an explicit `false` value would get overridden by a user's `true` value, but not the other way around?!

2021-02-08 19:50 UTC, JoostK commented on packages/compiler-cli/src/perform_compile.ts
> +    useCaseSensitiveFileNames: true,
This appears to have been inherited from code in master, but it's strange to me that this isn't using `fs.isCaseSentive()`. Also one can wonder why `readDirectory` and `readFile` don't get routed through `fs`. I think it's fine to not touch this in this PR, just noting it here.

2021-02-08 19:50 UTC, JoostK commented on packages/compiler-cli/src/perform_compile.ts
> +    useCaseSensitiveFileNames: true,
Also this may benefit from being extracted to a function (e.g. `createConfigHost`) as it's now declared twice.

2021-02-08 19:50 UTC, JoostK commented on packages/compiler-cli/src/perform_compile.ts
> +  let extendedConfigPath: AbsoluteFsPath|undefined;
In the compiler we tend use `null` with an explicit initializer (in this case at least, as not all code paths below assign a value to `extendedConfigPath`).

2021-02-08 19:50 UTC, JoostK commented on packages/compiler-cli/src/perform_compile.ts
> +  if (extendedConfigPath && host.exists(extendedConfigPath)) {
This would become `extendedConfigPath !== null`.

2021-02-08 20:01 UTC, alan-agius4 commented on packages/compiler-cli/src/perform_compile.ts
> +  let extendedConfigPath: AbsoluteFsPath|undefined;
Will change to adhere to the code style.

2021-02-09 07:11 UTC, alan-agius4 commented on packages/bazel/src/ngc-wrapped/index.ts
> +    ...overrides,
Good catch.

Previously the user config was preferred example, indeed there does appear to be a bug with boolean flags.

```
angularCompilerOptions['i18nOutFormat'] = angularCompilerOptions['i18nOutFormat'] ||	
          userConfig.angularCompilerOptions.i18nOutFormat;
```

2021-02-09 07:27 UTC, alan-agius4 commented on packages/compiler-cli/src/perform_compile.ts
> +    const parseConfigHost = {
Actually this is `ts.ParseConfigHost`

2021-02-09 10:29 UTC, alan-agius4 commented
**Caretaker**: can you please run a TGP as the ngc-wrapped changes can be risky? Thanks.

2021-02-09 10:30 UTC, JoostK approved these changes

2021-02-10 05:48 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:356664930:BASE:356664940:1612936109271:1be0667d).

2021-02-10 19:55 UTC, AndrewKushnir commented
@alan-agius4 I've ran a presubmit (with a subset of targets) and there are some build failures from the scripts (g3-specific) that use `createNgCompilerOptions` function (which was removed in this PR).

@kyliau could you please help look into the failures to see if g3 scripts need refactoring or the PR should be update to avoid removing the `createNgCompilerOptions` function?

2021-02-10 20:18 UTC, alan-agius4 commented
I can re-add that method although I prefer not to.

2021-02-11 02:57 UTC, AndrewKushnir commented
@alan-agius4 FYI I've started a [new presubmit](http://test/OCL:356665121:BASE:356878807:1613012117726:94b352ac) after @kyliau submitted an internal refactoring to avoid using `createNgCompilerOptions` function (thanks Keen!). Will keep this thread updated.

2021-02-11 18:38 UTC, AndrewKushnir commented
@alan-agius4 FYI presubmits were successful for the changes in this PR, adding the "merge" label back. Thank you.

2021-02-11 18:47 UTC, kyliau commented
thanks @AndrewKushnir !

2021-02-11 19:00 UTC, alan-agius4 commented
Thanks @AndrewKushnir & @kyliau for your help.

2021-02-11 21:30 UTC, closed without merging