Update to rulesnodejs@3.1.0
angular/angular pull request #40710
Opened 2021-02-04 22:49 UTC by josephperrott

See individual commits.

2021-02-05 06:34 UTC, AndrewKushnir reviewed
@josephperrott could you plz share a link (may be add to a PR description) to a change that triggered JSON.parse type cast (as an additional context for CR)?

2021-02-05 11:59 UTC, alan-agius4 commented
@AndrewKushnir https://github.com/bazelbuild/rules_nodejs/wiki#stricter-ts-typechecks

2021-02-05 12:00 UTC, alan-agius4 commented on packages/bazel/src/ng_package/packager.ts
> +  const modulesManifest = JSON.parse(modulesManifestArg) as {[key: string]: any};
```suggestion
  const modulesManifest = JSON.parse(modulesManifestArg) as Record<string, any>;
```

2021-02-05 12:01 UTC, alan-agius4 commented
@josephperrott, most of the casts are `as any` maybe it's just better to disable the plugin.

2021-02-05 19:01 UTC, josephperrott commented
@alan-agius4 I updated the PR to include more specific typings throughout.

2021-02-05 21:57 UTC, petebacondarwin requested changes
Awesome (and wide ranging!!) PR @josephperrott.

I made a whole host of suggestions for the casts; primarily focussed on areas that I have some ownership over (e.g. ngcc and localize).
I skipped over some of the other packages like elements and router, etc.

2021-02-05 21:57 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/packages/configuration_spec.ts
> +                JSON.parse(originalDefaultConfig) as {[key: string]: RawNgccPackageConfig});
How about:

```suggestion
                JSON.parse(originalDefaultConfig) as NgccProjectConfig['packages'];
```

2021-02-05 21:57 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/packages/entry_point_spec.ts
> +          EntryPoint;
👍

2021-02-05 21:57 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/rendering/renderer_spec.ts
> +                 .toEqual(MERGED_OUTPUT_PROGRAM_MAP.toObject());
This one really should be `as any`, since that is the return type of `SourceMapConverter.toObject()`.

```suggestion
             expect(JSON.parse(mapFile.contents) as any)
                 .toEqual(MERGED_OUTPUT_PROGRAM_MAP.toObject());
```

2021-02-05 21:57 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/writing/new_entry_point_file_writer_spec.ts
> +               JSON.parse(fs.readFile(_('/node_modules/test/__ivy_ngcc__/es2015/index.js.map'))) as
I think we could use import `RawSourceMap` from `'../../../src/ngtsc/sourcemaps'` here, and below.

2021-02-05 21:57 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/writing/new_entry_point_file_writer_spec.ts
> +            {fesm5_ivy_ngcc?: string, module_ivy_ngcc?: string};
OMG in `ngcc/src/packages/entry_points.ts` we should create the following type:

```ts
export type NewEntryPointPropertiesMap = {
  [Property in PackageJsonFormatProperties as `${Property}_ivy_ngcc`]?: string;
};
```

And then this can be:

```suggestion
        const packageJsonFromFile1 = JSON.parse(fs.readFile(packageJsonPath)) as
            NewEntryPointPropertiesMap;
```

2021-02-05 21:57 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/writing/package_json_updater_spec.ts
> +    const readJson = <T>(path: AbsoluteFsPath) => JSON.parse(fs.readFile(path)) as T;
🎉

2021-02-05 21:57 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/writing/package_json_updater_spec.ts
> +    const readJson = <T>(path: AbsoluteFsPath) => JSON.parse(fs.readFile(path)) as T;
Although.... in this case we never actually access any of the properties of the parsed objects directly. So I think it might be simpler (for the tests) just to go with `any` here!

2021-02-05 21:57 UTC, petebacondarwin commented on packages/compiler-cli/src/transformers/metadata_reader.ts
> +        JSON.parse(host.readFile(metadataPath)) as ModuleMetadata[] | undefined;
I think (to be exact):

```suggestion
        JSON.parse(host.readFile(metadataPath)) as ModuleMetadata | ModuleMetadata[] | undefined;
```

2021-02-05 21:57 UTC, petebacondarwin commented on packages/compiler-cli/src/transformers/metadata_reader.ts
> +        JSON.parse(host.readFile(metadataPath)) as ModuleMetadata[] | undefined;
And then we can drop the type on the `metadatas` const below.

2021-02-05 21:57 UTC, petebacondarwin commented on packages/compiler-cli/test/compliance/partial/partial_compliance_goldens.bzl
> +            "--bazel_patch_module_resolver",
Ooh! What effect does this have?
And will it allow us to generate golden files on Windows??

2021-02-05 21:57 UTC, petebacondarwin commented on packages/compiler-cli/test/compliance/test_helpers/get_compliance_tests.ts
> +        {cases: {expectations: Expectation[], focusTest: boolean, excludeTest: boolean}[]};
This is not quite accurate. The parsed value can be a single object (say `TestCaseJson`) or an array of objects (`TestCaseJson[]`), where `TestCaseJson` is:

```ts
interface TestCaseJson {
  description: string;
  compilationModeFilter?: ('fulll compile'|'linked compile')[];
  inputFiles?: string[];
  expectations?: {
    failureMessage?: string;
    files?: ExpectedFiles[]|string;
    expectedErrors?: {message: string, location?: string};
    extraChecks?: (string|string[])[];
  };
  compilerOptions?: ConfigOptions>;
  angularCompilerOptions?: ConfigOptions>;
  focusTest?: boolean;
  excludeTest?: boolean;
}
```

I think we should probably create this interface and use it.
(By the way it has to match the definition in `packages/compiler-cli/test/compliance/test_cases/test_case_schema.json` so that might be worth a comment.

2021-02-05 21:57 UTC, petebacondarwin commented on packages/elements/schematics/ng-add/index_spec.ts
> +    const pkgJson = JSON.parse(pkgJsonText) as {dependencies: any};
I feel like `@angular-devkit/schematics/testing` should export some `PackageJsonObject` interface to be used by all these schematics tests, since loading a package.json is so common.

2021-02-05 21:57 UTC, petebacondarwin commented on packages/localize/src/tools/src/extract/translation_files/format_options.ts
> +}
❤️

2021-02-05 21:57 UTC, petebacondarwin commented on packages/localize/src/tools/src/translate/translation_files/translation_parsers/simple_json_translation_parser.ts
> +      const json = JSON.parse(contents) as ParsedTranslationBundle;
This is not quite right since `ParsedTranslationBundle` contains a required `diagnostics: Diagnostics` property, which is not in the JSON.

Instead we should create a local interface in this file:

```ts
interface SimpleJsonFile {
  locale: string;
  translations: {[messageId: string]: string};
}
```

and use it here and also on line 74 below.

2021-02-05 21:57 UTC, petebacondarwin commented on packages/localize/src/tools/src/translate/translation_files/translation_parsers/simple_json_translation_parser.ts
> +    const {locale: parsedLocale, translations} = json || JSON.parse(contents) as any;
```suggestion
    const {locale: parsedLocale, translations} = (json || JSON.parse(contents)) as SimpleJsonFile;
```

2021-02-05 21:57 UTC, petebacondarwin commented on tools/symbol-extractor/symbol_extractor.ts
> +      expected = JSON.parse(expected) as (Symbol | string)[];
I don't think that JSON.parse can produce `Symbol` objects so...

```suggestion
      expected = JSON.parse(expected) as string[];
```

2021-02-05 21:57 UTC, petebacondarwin commented on tools/symbol-extractor/symbol_extractor.ts
> +    expected.forEach((nameOrSymbol) => {
👍 
You can even remove the parens...

```suggestion
    expected.forEach(nameOrSymbol => {
```

2021-02-05 22:24 UTC, josephperrott commented on packages/compiler-cli/ngcc/test/writing/new_entry_point_file_writer_spec.ts
> +               JSON.parse(fs.readFile(_('/node_modules/test/__ivy_ngcc__/es2015/index.js.map'))) as
It looks like the typings of those don't line up.

```ts
export interface RawSourceMap {
  version: number|string;
  file?: string;
  sourceRoot?: string;
  sources: string[];
  names: string[];
  sourcesContent?: (string|null)[];
  mappings: string;
}
```
where as the object we are checking comes out to

```ts
interface {
  version: number;
  file: string;
  sources: string[];
  mappings: string;
  sourceRoot: string;
}
```

2021-02-05 22:40 UTC, josephperrott commented on WORKSPACE
> +    strict_visibility = False,
It is related to strict dependencies of npm packages and their presence in the package.json file, I added a comment in the WORKSPACE file to express that a follow up is needed to correct this.  It just will be a ton of tiny changes everywhere.

2021-02-05 22:47 UTC, josephperrott commented on packages/compiler-cli/test/compliance/partial/partial_compliance_goldens.bzl
> +            "--bazel_patch_module_resolver",
I updated the PR to note it needs to be removed, but yes it puts the monkey patching back in for the `resolve` tooling to work with bazel.  We need to go back and fixup all of the dependencies in the build rules to be able to remove it again.

2021-02-05 22:58 UTC, josephperrott commented on dev-infra/release/publish/actions.ts
> +        JSON.parse(await fs.readFile(pkgJsonPath, 'utf8')) as {version: string, [key: string]: any};
I think a helper function for parsing JSON would be helpful, but I don't know that it makes sense to do at this point.

I believe that `readFileSync` comes from `fs-extra` rather than `fs` so we avoided using it.

2021-02-08 16:15 UTC, petebacondarwin commented on dev-infra/release/publish/actions.ts
> +        JSON.parse(await fs.readFile(pkgJsonPath, 'utf8')) as {version: string, [key: string]: any};
`readFileSync` is straight from node.js: https://nodejs.org/dist/latest-v14.x/docs/api/fs.html#fs_fs_readfilesync_path_options

2021-02-08 16:20 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/writing/new_entry_point_file_writer_spec.ts
> +               JSON.parse(fs.readFile(_('/node_modules/test/__ivy_ngcc__/es2015/index.js.map'))) as
That actually highlights an issue with the test data :-)
Earlier one we have 

```ts
const sourceMap = {
  version: 3,
  file: 'index.js',
  sources: ['../src/index.ts'],
  mappings: 'AAAA',
};
```

This is actually wrong and should be:

```ts
const sourceMap: RawSourceMap = {
  version: 3,
  file: 'index.js',
  sources: ['../src/index.ts'],
  names: [],
  mappings: 'AAAA',
};
```

2021-02-08 16:24 UTC, petebacondarwin commented on dev-infra/release/publish/actions.ts
> +        JSON.parse(await fs.readFile(pkgJsonPath, 'utf8')) as {version: string, [key: string]: any};
But I guess that you are consistently using async functions throughout so it makes sense to leave this as-is.

2021-02-08 16:28 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/writing/new_entry_point_file_writer_spec.ts
> +import {RawSourceMap} from '@angular/compiler-cli/src/ngtsc/sourcemaps';
```suggestion
import {RawSourceMap} from '../../../src/ngtsc/sourcemaps';
```

2021-02-08 16:30 UTC, petebacondarwin approved these changes
NICE!

2021-02-08 23:50 UTC, IgorMinar requested changes
lgtm except for the CI change. can you please clarify what's going on there? thanks!

2021-02-08 23:50 UTC, IgorMinar commented on .circleci/config.yml
> -      - lint:
What are all these CI changes for The commit message just says "WIP". Is this to be removed?

2021-02-09 00:05 UTC, josephperrott commented on .circleci/config.yml
> -      - lint:
Yes, I am working to solve the windows test failures, and need to run the test in a windows environment.  The will be removed.

2021-02-09 00:06 UTC, IgorMinar commented on .circleci/config.yml
> -      - lint:
oh, I see. thanks

2021-02-09 00:08 UTC, IgorMinar approved these changes
LGTM! Thank you!

Reviewed-for: global-approvers

2021-02-09 01:13 UTC, josephperrott commented
Caretaker Note: We should merge this and then watch the next few merges after to make sure there are not flakes.

2021-02-09 18:48 UTC, closed without merging