feat(docs-infra): add documentation for HostListener
angular/angular pull request #40720
Opened 2021-02-05 10:51 UTC by abarghoud

add return value documentations for HostListener callbacks

Closes #40708

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-02-05 10:53 UTC, petebacondarwin approved these changes

2021-02-10 23:56 UTC, josephperrott requested changes
@abarghoud The commit message type and scope I believe are incorrect for this change.

I believe that this should actually be:

`docs:` or `docs(core):`

2021-02-11 09:57 UTC, petebacondarwin commented
Good spot @josephperrott - thanks. Can you update the commit @abarghoud ?

2021-02-11 09:59 UTC, abarghoud commented
Thanks @josephperrott, @petebacondarwin will do.

2021-02-11 11:17 UTC, abarghoud commented
> @abarghoud The commit message type and scope I believe are incorrect for this change.
> 
> I believe that this should actually be:
> 
> `docs:` or `docs(core):`

Done.

2021-02-11 17:29 UTC, josephperrott approved these changes
LGTM

2021-02-12 22:22 UTC, AndrewKushnir approved these changes

2021-02-17 14:55 UTC, closed without merging