Update heroes.component.ts
angular/angular pull request #40735
Opened 2021-02-06 13:38 UTC by hilmer-martin

Because of changes in Typescript a property must have an initializer or be set to undefined. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#strict-class-initialization

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-02-06 16:32 UTC, hilmer-martin commented
@googlebot I signed it!

2021-02-07 15:42 UTC, petebacondarwin requested changes

2021-02-07 15:42 UTC, petebacondarwin commented on aio/content/examples/toh-pt2/src/app/heroes/heroes.component.ts
> +  selectedHero: Hero | undefined;
I think it would be cleaner to go with

```suggestion
  selectedHero?: Hero;
```

2021-02-08 16:34 UTC, petebacondarwin requested changes
Looks much better.
Just need to sort out the commit message linting:
* the first commit has body lines that are too long (more than 120 chars). Can you split the lines up with some `\n`s.
* the second commit should be a fixup commit with the following commit message:

```
fixup! docs: changes for typescript 2.7
```

See https://github.com/angular/angular/blob/6e0a8eb268d8f88866c15a1d5cda651edc558081/docs/FIXUP_COMMITS.md for more info on fixup commits.

2021-02-09 16:58 UTC, hilmer-martin commented
@petebacondarwin I changed the commits, but the cla-bot is failing now. What should I do next?

2021-02-09 17:44 UTC, petebacondarwin commented
@googlebot I consent.

2021-02-09 17:45 UTC, petebacondarwin approved these changes
Reviewed-for: global-docs-approvers

2021-02-09 18:52 UTC, closed without merging