feat(zone.js): Provide auto fakeAsync() functionality
angular/angular pull request #40798
Opened 2021-02-11 12:27 UTC by JiaLiPassion

2021-02-11 19:22 UTC, jessicajaniuk approved these changes
LGTM 🍪 

Just some minor language suggestions.

2021-02-11 19:22 UTC, jessicajaniuk commented on aio/content/guide/testing-components-scenarios.md
> +When using `jasmine.clock()`, the test case becomes `fakeAsync()` automatically, the same
```suggestion
When using `jasmine.clock()`, the test case becomes `fakeAsync()` automatically. The same
```

2021-02-11 19:22 UTC, jessicajaniuk commented on packages/core/testing/src/fake_async.ts
> + * describe('Auto go into fakeAsync()', () => {
Maybe prepend this with "Example:". I was confused why a test was fully commented out here for a second.

2021-02-16 21:16 UTC, mhevery requested changes
Perhaps I am misunderstanding this PR, so please correct me.  To me it seems like jasmine.clock() turns on `fakeAsync` functionality. The issue is that `fakeAsync` does a lot more than just work with clock. For example `Promise`s are now also async. I don't think this kind of magic is a good idea as adding `jasmine.clock()` changes a lot more than just make `setTimeout` into mockable version.

2021-02-17 00:44 UTC, JiaLiPassion commented
@mhevery , yeah, so the motivation of this PR is just make a existing feature of zone.js easier to use.
When the user is using `jasmine.clock()`, it will turn on `fakeAsync()` automatically, the user doesn't need to write the code `fakeAsync()` and the test cases automatically becomes `fakeAsync()` test, so I just think if we make this feature also available without using `jasmine.clock()`.

2021-02-17 17:50 UTC, mhevery commented
> The benefit is just let user write a little bit less code.

I think this is too much magic. I think we should stick to explicit `fakeAsync`. We can discuss this on our team meeting.

2021-02-17 22:55 UTC, JiaLiPassion commented
@mhevery, got it, I agree explicit `fakeAsync` is better to understand, and I just have this idea when I am working on https://github.com/angular/angular/pull/40611, since when the user is using `jest` or `jasmine.clock`, they don't need to call some explicit function such as `fakeAsync()`, so I think maybe in `zone.js` we can provide the similar functionality.

2021-02-19 00:19 UTC, closed without merging