feat(core): drop support for zone.js 0.10.x
angular/angular pull request #40823
Opened 2021-02-12 10:17 UTC by alan-agius4

With this change we drop support for zone.js 0.10.x. This is needed because in version 12. The CLI will only work with 0.11.x. https://github.com/angular/angular-cli/pull/20034
    
BREAKING CHANGE:
    
Minimum supported `zone.js` version is `0.11.1`

2021-02-12 17:36 UTC, gkalpak requested changes
Yay :tada:

I still see some occurrences of `zone.js/dist/...` (mostly in error messages and docs. They should also be updated, right?

- [aio/content/guide/testing-components-scenarios.md](https://github.com/angular/angular/blob/838e3bdb6d97bb3251b5518febc1fa9d110e3c4b/aio/content/guide/testing-components-scenarios.md)
- [dev-infra/BUILD.bazel](https://github.com/angular/angular/blob/838e3bdb6d97bb3251b5518febc1fa9d110e3c4b/dev-infra/BUILD.bazel)
- [packages/core/src/testability/testability.ts](https://github.com/angular/angular/blob/838e3bdb6d97bb3251b5518febc1fa9d110e3c4b/packages/core/src/testability/testability.ts)
- [packages/core/testing/src/async.ts](https://github.com/angular/angular/blob/838e3bdb6d97bb3251b5518febc1fa9d110e3c4b/packages/core/testing/src/async.ts)
- [packages/localize/schematics/ng-add/index_spec.ts](https://github.com/angular/angular/blob/838e3bdb6d97bb3251b5518febc1fa9d110e3c4b/packages/localize/schematics/ng-add/index_spec.ts)
- [packages/zone.js/MODULE.md](https://github.com/angular/angular/blob/838e3bdb6d97bb3251b5518febc1fa9d110e3c4b/packages/zone.js/MODULE.md)
- [packages/zone.js/NON_STANDARD_APIS.md](https://github.com/angular/angular/blob/838e3bdb6d97bb3251b5518febc1fa9d110e3c4b/packages/zone.js/NON_STANDARD_APIS.md)
- [packages/zone.js/README.md](https://github.com/angular/angular/blob/838e3bdb6d97bb3251b5518febc1fa9d110e3c4b/packages/zone.js/README.md)
- [packages/zone.js/lib/zone-spec/async-test.ts](https://github.com/angular/angular/blob/838e3bdb6d97bb3251b5518febc1fa9d110e3c4b/packages/zone.js/lib/zone-spec/async-test.ts)
- [packages/zone.js/lib/zone-spec/fake-async-test.ts](https://github.com/angular/angular/blob/838e3bdb6d97bb3251b5518febc1fa9d110e3c4b/packages/zone.js/lib/zone-spec/fake-async-test.ts)


Also, I think we should add the `zone.js/plugins/` directory in `.github/angular-robot.yml`:

https://github.com/angular/angular/blob/838e3bdb6d97bb3251b5518febc1fa9d110e3c4b/.github/angular-robot.yml#L76-L80

I accept that some (or maybe all) of these changes are not directly related to this PR (and should have happened independently). I am bringing them up as you seem to have made similar changes in other places as part of this PR, but happy to captrure them in an issue to make them in a new PR (also happy to take them on).

##
BTW, there are some minor typos in the commit messages:

- One of the commits says _"Minimum supported `zone.js` version is `0.11.1`"_, but based on the changes in `packages/core/package.json`, it seems that `0.11.3` is the minimum required version. Do I miss something?
- ```diff
  -This is needed because in version 12. The CLI will only work with 0.11.x. angular/angular-cli#20034
  +This is needed because in version 12 the CLI will only work with 0.11.x. See angular/angular-cli#20034.
  ```
- ```diff
  -In CLI version 12, the old style of imports are no longer supported.
  +In CLI version 12, the old style of imports is no longer supported.
  ```
- `zone.js` incosistently appearing both wrapped in backticks and unwrapped :grin:
- Some trailing periods are missing :grin:

2021-02-12 17:39 UTC, alan-agius4 commented on aio/tools/examples/shared/yarn.lock
> +    zone.js "~0.11.3"
Can you elaborate why this is incorrect?

2021-02-12 17:40 UTC, alan-agius4 commented on aio/tools/examples/shared/yarn.lock
> +zone.js@~0.11.3:
This is auto generated.

2021-02-12 17:40 UTC, alan-agius4 commented on aio/tools/examples/shared/yarn.lock
> +  version "0.11.3"
I am not sure what you mean by we need both versions. This lock file is auto generated.

2021-02-12 17:41 UTC, alan-agius4 commented on aio/tools/examples/shared/yarn.lock
> +zone.js@~0.11.3:
Oh I see the problem now.

2021-02-12 17:43 UTC, alan-agius4 commented
Thanks for the review @gkalpak. I can definitely that the other suggest changes.

Let me get back to this PR on Monday.

2021-02-13 10:27 UTC, JiaLiPassion commented
@alan-agius4 , since `zone.js` 0.11.1~0.11.3 has an issue with `es2015` bundle, and it has been fixed here https://github.com/angular/angular/pull/40456, and is available in `0.11.4`. This issue will have some impact when user using the new bundle `import 'zone.js'` , So I think maybe we should use the new `0.11.4` version as the minimum support version?

2021-02-13 11:32 UTC, alan-agius4 commented
@JiaLiPassion, that would be possible, when is 0.11.4 scheduled to be released?

2021-02-13 11:51 UTC, JiaLiPassion commented
@alan-agius4 , the release PR has been merged, I believe it will be released very soon.

2021-02-15 10:28 UTC, alan-agius4 commented
@JiaLiPassion & @gkalpak, I update the PR once `zone.js` 0.11.4 is released I'll update the PR with the new version. 

@JiaLiPassion, can we prioritize a zone.js release? Since this will also need to be synced in https://github.com/angular/angular-cli/pull/20034

2021-02-15 10:54 UTC, JiaLiPassion commented
@alan-agius4 , sure, I will contact @mhevery to make the new release.

2021-02-15 16:21 UTC, gkalpak approved these changes
Awesome work, @alan-agius4! Very thorough :100:

One last thing:
Should we update the reference to Angular CLI in [packages/zone.js/README.md (line 32)][1]?

```diff
-If you are using `Angular CLI`, the `polyfills.ts` file will contain:
+If you are using an older `Angular CLI`, the `polyfills.ts` file will contain:
```
(...or something along those lines.)

[1]: https://github.com/angular/angular/blame/618bb8bf267c5d0e00b684705b5dd812469e2df5/packages/zone.js/README.md#L32

2021-02-17 00:34 UTC, JiaLiPassion commented
@alan-agius4 , zone.js 0.11.4 is released, please update to this new version.

2021-02-17 00:35 UTC, JiaLiPassion approved these changes
LGTM after update to 0.11.4

2021-02-17 02:11 UTC, AndrewKushnir approved these changes

2021-02-17 07:52 UTC, alan-agius4 commented
Updated PR to use zone.js 0.11.4.

2021-02-17 14:45 UTC, josephperrott requested changes

2021-02-17 14:45 UTC, josephperrott commented on .github/angular-robot.yml
> +      - "packages/zone.js/plugins/**"
This code should not be excluded as it is synced into google3.

2021-02-17 15:15 UTC, alan-agius4 commented on .github/angular-robot.yml
> +      - "packages/zone.js/plugins/**"
PTAL

2021-02-17 15:39 UTC, josephperrott approved these changes
LGTM

2021-02-17 16:59 UTC, alxhub approved these changes

2021-02-23 17:30 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:359064352:BASE:359064387:1614101425642:90460e4f).

2021-02-24 15:58 UTC, closed without merging