docs: format null as code fragment
angular/angular pull request #40852
Opened 2021-02-15 09:36 UTC by AlexElin

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2021-02-15 11:29 UTC, petebacondarwin requested changes
One suggestion, otherwise LGTM.

2021-02-15 11:29 UTC, petebacondarwin commented on packages/core/src/di/injector_compatibility.ts
> + * @returns True if injection is successful, `null` otherwise.
Well if we are going to fix the `null` then we should fix its alternative return value to...

```suggestion
 * @returns the injected value if injection is successful, `null` otherwise.
```

2021-02-15 11:46 UTC, AlexElin commented on packages/core/src/di/injector_compatibility.ts
> + * @returns True if injection is successful, `null` otherwise.
fixed

2021-02-15 11:52 UTC, petebacondarwin approved these changes
LGTM

Reviewed-for: global-docs-approvers

2021-02-16 05:34 UTC, AndrewKushnir approved these changes

2021-02-16 17:24 UTC, closed without merging