refactor(common): add generic type to async pipe
angular/angular pull request #40870
Opened 2021-02-16 15:01 UTC by antonkri97

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
Type improvements

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

At first glance, the `SubscriptionStrategy` types were not obvious to me. Since `updateLatestValue` is always a function, I think it's better to show this explicitly. More than that now we can't return anything from `transform` or assign anything to `_latestValue`.

## What is the new behavior?
No breaking change, only types.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

2021-02-16 15:21 UTC, petebacondarwin commented
This is a big breaking change, and the compiler would need to be changed to generate code that applied the appropriate `T` type to the pipe usages. I am not sure that this is a valuable improvement. @alxhub & @JoostK might have a view?

2021-02-16 21:09 UTC, JoostK commented
> the compiler would need to be changed to generate code that applied the appropriate `T` type to the pipe usages.

Yeah, this is a problem for the template type checker. Moving the generic type from the `transform` method to the class would require the type to be known at the pipe's declaration, but the type checker actively relies on type inference through the value that is passed in to `transform` to infer the resulting type `T`.

This PR would become feasible and non-breaking if just the internal `SubscriptionStrategy` type and friends are updated, but not the `AsyncPipe` itself. Unfortunately that doesn't achieve much more type-safety that what we currently have, but at least it makes the type of `updateLatestValue` more clear.

2021-02-16 21:18 UTC, antonkri97 commented
Thanks @JoostK @petebacondarwin a lot for reviewing! I will try 
> he type of updateLatestValue more clear

2021-02-17 22:00 UTC, alxhub commented
I agree with @JoostK here. As an example, suppose the user has a template `{{ (foo | async).bar }}`. To type-check this template, the compiler generates code similar to the following:

```typescript
const p1 = new AsyncPipe();
p1.transform(ctx.foo).bar;
```

with `ctx` being the synthetic component instance. As Joost mentioned, the compiler is relying on type inference of the generic type of the `transform` method from its argument (`ctx.foo`) to ensure that the return of `transform()` represents the type of values that the `async` pipe will produce at runtime. That way, the compiler can check that `.bar` is a valid property access for such values.

Moving this generic type from `transform` to the `AsyncPipe` definition itself introduces a challenge: how does the compiler know what type of `AsyncPipe` to produce? The current constructor call:

```typescript
const p1 = new AsyncPipe();
```

won't produce a useful inference for the `AsyncPipe`'s generic type parameter, as TypeScript has nothing to go on here - `T` will be inferred as `unknown`. The subsequent call to `transform`, then, won't be able to type-check anything. That's because the generic type of `AsyncPipe` is not defined by how it's constructed, it needs to be defined by what values are passed to `transform()`.

Interestingly, the compiler already faces this challenge with directives. `NgForOf` has two generic type parameters, representing the item type and iterable type of an `*ngFor` invocation. Like with the hypothetical generic `AsyncPipe`, these parameters cannot be inferred from `NgForOf`'s constructor. For directives, its the _inputs_ that determine the directive type. In `NgForOf`'s case, it's the iterable that you bind to the `ngForOf` input which determines the generic type of the `NgForOf` instance.

To solve this problem for directives, the compiler creates a synthetic "type constructor" for generic directives, which uses its inputs to infer its generic parameters. Roughly, this looks like:

```typescript
declare const NgForOfTypeCtor<T, U extends Iterable<T>>(inputs: {ngForOf: U}) => NgForOf<T, U>;
```

When the user writes `*ngFor="let item of items"`, then, the compiler doesn't do `new NgForOf()` to construct the `NgForOf` instance type for type-checking. Instead, it calls this synthetic type constructor:

```typescript
const d1 = NgForOfTypeCtor({ngForOf: ctx.items}); // NgForOf<Item, Item[]>
```

Basically, the generated type constructor allows for the input bindings to `NgForOf` to feed into type inference of the resulting directive type for template type-checking, even though the real constructor of `NgForOf` doesn't behave this way.

To make `transform` non-generic, we'd have to do something similar with pipes in the template type-checker, and generate a synthetic pipe type constructor:

```typescript
declare const AsyncPipeTypeCtor<T>(expr: Observable<T>): AsyncPipe<T>;
```

This synthetic type constructor would have the same generic parameters as `AsyncPipe` itself, with `AsyncPipe` as its return type. It would also need to have the same function parameters as `AsyncPipe.transform`.

Then, each instance of `AsyncPipe`'s type could be inferred using this synthetic constructor:

```typescript
const p1 = AsyncPipeTypeCtor(ctx.foo); // AsyncPipe<Foo>
p1.transform(ctx.foo).bar;
```

The expectation here is that the generic type of `AsyncPipe` should be inferred from the arguments to `transform()`, so we'd create a synthetic type constructor that mimics `transform()` in terms of parameters but instead produces the overall instance type for the pipe invocation.

Arguably this is a reasonable thing to do, and it definitely has conceptual symmetry with how directives work today. But it really wouldn't have any user-facing impact, so I don't see it as much of a priority at the moment.

But again, I do agree with Joost that changing the type of `SubscriptionStrategy` is reasonable and non-breaking, and while it doesn't improve type safety it does at least improve readability.

2021-04-07 20:07 UTC, petebacondarwin requested changes
I don't believe that the changes from `any` to `Object` are correct. AFAICT The `async` pipe can be given a `Subscribable`/`Promise`/`EventEmitter` that will emit/resolve to `any` type, not just an object.  This means that the `value` that is unwrapped from these could also be of type `any`, right?

2022-01-27 21:46 UTC, alxhub commented
Closing as @petebacondarwin's above comment is correct - we don't want to use `Object` in these cases.

2022-01-27 21:46 UTC, closed without merging