docs: improve accessibility of router example
angular/angular pull request #40914
Opened 2021-02-18 22:08 UTC by kapunahelewong

Fixes contrast issues.
Makes labels explicitly reference inputs.
Adds padding to buttons so they are an easier target for touch or pointer.
Changes "Message: " label to "Enter your message: ".
Fixes layout issue of hero names displaying against the edges of their containers.
Changes markup to make it more semantic.
Updates CSS.
Change all uppercase headers to lowercase (wasn't using a pipe, but written in all caps as a style).

## To do
Change app to application.
Check against md file
Fix any e2e tests I broke 🙃

2021-02-18 22:16 UTC, mary-poppins commented
You can preview 2d86e38 at https://pr40914-2d86e38.ngbuilds.io/.

2021-02-19 02:25 UTC, theBolck commented
kapunahelewong:a11y-router``

2021-02-19 19:28 UTC, aikidave approved these changes
Reviewed-for: global-docs-approvers

2021-02-19 21:31 UTC, mary-poppins commented
You can preview 66af008 at https://pr40914-66af008.ngbuilds.io/.

2021-02-19 22:22 UTC, mary-poppins commented
You can preview ed684c7 at https://pr40914-ed684c7.ngbuilds.io/.

2021-02-22 21:33 UTC, mary-poppins commented
You can preview ce8adcd at https://pr40914-ce8adcd.ngbuilds.io/.

2021-02-22 21:37 UTC, THEBOLCK79 commented
- Recibido

2021-02-24 17:38 UTC, gkalpak requested changes
Nice work! (And the screenshots make revieweing so much easier 😍)

My general comment is that I would prefer if we could re-use more styles across examples (so we don't have to maintain a ton of styles and also keep a consistent look-and-feel across examples).

BTW, I don't know if it is intentional but there are a bunch of screenshot images in the router tutorial that depict the old styles (and might confuse users). I understand updating all of them can be a lot of work and might not be worth the time. I just wanted to bring it up to make sure it has been considered.

2021-02-24 17:38 UTC, gkalpak commented on aio/content/examples/router/src/app/admin/admin-dashboard/admin-dashboard.component.css
> +}
Since this is rule is defined in several places, would it make sense to add it to [aio/tools/examples/shared/boilerplate/common/src/styles.css][1] (so that it affects all examples and we don't have to define it over and over)?

[1]: https://github.com/angular/angular/blob/ce8adcd4ba68be1bb93e3478f55b0133ec281d1f/aio/tools/examples/shared/boilerplate/common/src/styles.css

2021-02-24 17:38 UTC, gkalpak commented on aio/content/examples/router/e2e/src/app.e2e-spec.ts
> +      secondaryOutlet: element.all(by.css('app-root app-compose-message'))
Why not remove the `app-root` and `div` parts altogether (as in the other selectors above)? Would that not work here?

2021-02-24 17:38 UTC, gkalpak commented on aio/content/examples/router/src/app/app.component.css
> + }
Do these styles have to be different than the ones defined in [aio/tools/examples/shared/boilerplate/common/src/styles.css][1]? Could we update `common/src/styles.css` instead (and have the changes affect all examples)?

[1]: https://github.com/angular/angular/blob/ce8adcd4ba68be1bb93e3478f55b0133ec281d1f/aio/tools/examples/shared/boilerplate/common/src/styles.css#L39-L58

2021-02-24 17:38 UTC, gkalpak commented on aio/content/examples/router/src/app/compose-message/compose-message.component.css
> +}
Same here. Could we move generic styles (for example, for buttons) into [aio/tools/examples/shared/boilerplate/common/src/styles.css][1]?

[1]: https://github.com/angular/angular/blob/ce8adcd4ba68be1bb93e3478f55b0133ec281d1f/aio/tools/examples/shared/boilerplate/common/src/styles.css#L39-L58

2021-02-24 17:38 UTC, gkalpak commented on aio/content/examples/router/src/app/app.component.html
>    <router-outlet #routerOutlet="outlet"></router-outlet>
```suggestion
    <router-outlet #routerOutlet="outlet"></router-outlet>
```

2021-02-24 17:38 UTC, gkalpak commented on aio/content/examples/router/src/app/heroes/hero-list/hero-list.component.css
> +
```suggestion
```

2021-02-24 17:38 UTC, gkalpak commented on aio/content/guide/router-tutorial-toh.md
> -
Why remove this (and the corresponding styles)?

2021-03-01 22:21 UTC, kapunahelewong commented on aio/content/guide/router-tutorial-toh.md
> -
I got mixed up. Fixed.

2021-03-01 22:29 UTC, mary-poppins commented
You can preview f4b2ac5 at https://pr40914-f4b2ac5.ngbuilds.io/.

2021-03-02 13:46 UTC, kapunahelewong commented on aio/content/examples/router/src/app/app.component.css
> + }
Done in [#40890](https://github.com/angular/angular/pull/40890/files#diff-fc4733198c39ce5dbd8bd4dd55f1db545f4002ff73109111056ffa811f7f5748R63)

2021-03-02 16:10 UTC, kapunahelewong commented on aio/content/examples/router/src/app/admin/admin-dashboard/admin-dashboard.component.css
> +}
Agreed. I had started https://github.com/angular/angular/pull/40890 but missed this before that one merged.

Moving this to https://github.com/angular/angular/pull/41052 in the interest of scope.

2021-03-02 16:11 UTC, kapunahelewong commented on aio/content/examples/router/src/app/app.component.css
> + }
Doing this in #41052.

2021-03-02 16:11 UTC, kapunahelewong commented on aio/content/examples/router/src/app/compose-message/compose-message.component.css
> +}
Doing this in #41052.

2021-03-02 16:29 UTC, kapunahelewong commented on aio/content/examples/router/src/app/compose-message/compose-message.component.css
> +}
PS, @gkalpak did you want me to leave the `textarea` `width: 100%` in compose-message.component.css? In #41052 I've put it in [aio/tools/examples/shared/boilerplate/common/src/styles.css](https://github.com/angular/angular/blob/ce8adcd4ba68be1bb93e3478f55b0133ec281d1f/aio/tools/examples/shared/boilerplate/common/src/styles.css#L39-L58).

2021-03-02 16:35 UTC, mary-poppins commented
You can preview a99f242 at https://pr40914-a99f242.ngbuilds.io/.

2021-03-02 17:18 UTC, gkalpak commented on aio/content/examples/router/src/app/compose-message/compose-message.component.css
> +}
If we have `textarea`s in several examples (and the `width: 100%` style is suitable for all of them), then it makes sense to move it the boilerplate CSS. If it's only used in a couple of places, then it is probably best to style it in each example that uses it.

2021-03-03 10:23 UTC, gkalpak requested changes
Thx, @kapunahele! The new styles look much better 🚀

Some comments:
- Can you please rebase this on latest master and remove any component styles that are also defined in the [boilerplate CSS][1]? :pray:
- There are a couple more `app` occurrences at the bottom of `router-tutorial-toh.md`:
  - [router-tutorial-toh.md: line 2882][4]
  - [router-tutorial-toh.md: line 2884][5]
- Regarding the new images:
  - OOC, why use GIFs instead of PNGs?
  - Many of them include the `Angular Router` header which doesn't add anything afaict and unnecessarily increases the file size.
  - [hero-list.gif][2] has hover styles on `Crisis Center`, which is a little confusing.
  - [router-1-anim.gif][3] increased in size ~120x (9.74 KB --> 1.13 MB) 😱 Could we keep it close to the original size?
- Something I noticed while playing with the example is that the "Crisis Center" list item hover styles are slightly different that those of "Heroes" (for example, there is no change in the horizontal position). Assume that was not intentional...

##
<sub>

For personal reference, unresolved comments from previous review: https://github.com/angular/angular/pull/40914#discussion_r582148027, https://github.com/angular/angular/pull/40914#discussion_r582149449

</sub>

[1]: https://github.com/kapunahelewong/angular/blob/3370ade9a4873919c0797c04ac84b2c18f357c13/aio/tools/examples/shared/boilerplate/common/src/styles.css
[2]: https://github.com/angular/angular/blob/a99f24256fb45167618b7b44a240a66573f8c19d/aio/content/images/guide/router/hero-list.gif
[3]: https://github.com/angular/angular/blob/a99f24256fb45167618b7b44a240a66573f8c19d/aio/content/images/guide/router/router-1-anim.gif
[4]: https://github.com/angular/angular/blame/a99f24256fb45167618b7b44a240a66573f8c19d/aio/content/guide/router-tutorial-toh.md#L2882
[5]: https://github.com/angular/angular/blame/a99f24256fb45167618b7b44a240a66573f8c19d/aio/content/guide/router-tutorial-toh.md#L2884

2021-03-03 10:23 UTC, gkalpak commented on aio/content/guide/router-tutorial-toh.md
> +  <img src='generated/images/guide/router/selected-hero.png' alt="Selected hero in list has different background color">
:100:

2021-03-03 10:23 UTC, gkalpak commented on aio/content/guide/router-tutorial-toh.md
```suggestion
```

2021-03-05 18:26 UTC, kapunahelewong commented on aio/content/examples/router/src/app/app.component.css
> +  max-width: 800px;
Yeah, it doesn't apply anymore after the boilerplate css was updated. Removing all these. I'd started here and then realized I'd be better served updating the universal styles first. Now I have some clean up to do.

2021-03-05 18:34 UTC, kapunahelewong commented on aio/content/examples/router/src/app/crisis-center/crisis-detail/crisis-detail.component.html
> +  <p for="crisis-name">Id: {{ crisis.id }}</p>
nope, it was a mistake. Thank you for catching it!

2021-03-05 20:11 UTC, kapunahelewong commented on aio/content/examples/router/src/app/heroes/hero-detail/hero-detail.component.html
> +</div>
Oh yes, I meant to! Thanks!

2021-03-05 21:42 UTC, kapunahelewong commented on aio/content/examples/router/src/app/heroes/hero-detail/hero-detail.component.css
> +button {
This was just leftovers from before I started the boilerplate changes. Thank you for catching it. Removing.

2021-03-05 22:10 UTC, mary-poppins commented
You can preview 38230d8 at https://pr40914-38230d8.ngbuilds.io/.

2021-03-08 21:37 UTC, kapunahelewong commented on aio/content/examples/router/src/app/compose-message/compose-message.component.css
> +}
Ok, moved `textarea` to the example. I think `textarea` elements are few throughout the examples.

2021-03-08 21:47 UTC, kapunahelewong commented
> * Can you please rebase this on latest master and remove any component styles that are also defined in the [boilerplate CSS](https://github.com/kapunahelewong/angular/blob/3370ade9a4873919c0797c04ac84b2c18f357c13/aio/tools/examples/shared/boilerplate/common/src/styles.css)? 🙏

Done. ✅

> * There are a couple more `app` occurrences at the bottom of `router-tutorial-toh.md`:
Done. ✅


>   * OOC, why use GIFs instead of PNGs?

I was going with whichever file was smaller when exporting it from Affinity Photo.

>   * Many of them include the `Angular Router` header which doesn't add anything afaict and unnecessarily increases the file size.

Cropped.

>   * [hero-list.gif](https://github.com/angular/angular/blob/a99f24256fb45167618b7b44a240a66573f8c19d/aio/content/images/guide/router/hero-list.gif) has hover styles on `Crisis Center`, which is a little confusing.

Done. ✅

>   * [router-1-anim.gif](https://github.com/angular/angular/blob/a99f24256fb45167618b7b44a240a66573f8c19d/aio/content/images/guide/router/router-1-anim.gif) increased in size ~120x (9.74 KB --> 1.13 MB) 😱 Could we keep it close to the original size?

Oops! I recreated it with a smaller area (leaving out the title), trimmed it down to be a shorter loop, and then optimized it  at https://www.iloveimg.com, but it's still 76k. Is there something else I can do to make it smaller, @gkalpak?

> * Something I noticed while playing with the example is that the "Crisis Center" list item hover styles are slightly different that those of "Heroes" (for example, there is no change in the horizontal position). Assume that was not intentional...

Good catch! Fixed. ✅


> For personal reference, unresolved comments from previous review: [#40914 (comment)](https://github.com/angular/angular/pull/40914#discussion_r582148027), [#40914 (comment)](https://github.com/angular/angular/pull/40914#discussion_r582149449)

Both done!  ✅

2021-03-08 21:57 UTC, mary-poppins commented
You can preview 8e3763a at https://pr40914-8e3763a.ngbuilds.io/.

2021-03-09 18:06 UTC, gkalpak requested changes
The example looks so much better! Thank you, @kapunahelewong 🚀

Just a few more minor comments/questions. We're close 😉
(I am a tiny bit concerned about the slightly increased image sizes, but probably nothing worth spending any more time on.)

>> * [router-1-anim.gif](https://github.com/angular/angular/blob/a99f24256fb45167618b7b44a240a66573f8c19d/aio/content/images/guide/router/router-1-anim.gif) increased in size ~120x (9.74 KB --> 1.13 MB) 😱 Could we keep it close to the original size?
> 
> Oops! I recreated it with a smaller area (leaving out the title), trimmed it down to be a shorter loop, and then optimized it at https://www.iloveimg.com, but it's still 76k. Is there something else I can do to make it smaller, @gkalpak?

No idea tbh 😅
Maybe you could make it smaller or reduce the resolution? 🤷‍♂️

2021-03-09 18:06 UTC, gkalpak commented on aio/content/examples/router/src/app/compose-message/compose-message.component.css
> +}
Did you forget to style the buttons here?
You even have a screenshot showing them styled, but maybe you accidentally removed the styles later: ![][1]

[1]: https://user-images.githubusercontent.com/4116963/108772154-a4451880-752a-11eb-8992-c2eac4a3574d.png

2021-03-09 21:46 UTC, kapunahelewong commented on aio/content/examples/router/src/app/heroes/hero-detail/hero-detail.component.css
> +  color: #3d3d3d;
IIRC it was from before I had started the boilerplate PR. I started this one and then realized I should be working in boilerplate CSS. I hadn't yet figured it all out. Thanks for catching this.

2021-03-15 14:39 UTC, kapunahelewong commented on aio/content/guide/router-tutorial-toh.md
> -  <code-pane header="src/app/compose-message/compose-message.component.css" path="router/src/app/compose-message/compose-message.component.css">
Because in a previous comment I'd move those styles to boilerplate. I thought I'd put it back, but apparently missed it. Thank you for catching it! Fixed.

2021-03-15 15:08 UTC, kapunahelewong commented on aio/content/examples/router/src/app/crisis-center/crisis-detail/crisis-detail.component.css
> +button.active {
I meant `:`. Fixed.

2021-03-15 15:24 UTC, kapunahelewong commented on aio/content/examples/router/src/app/compose-message/compose-message.component.css
> +}
No, I didn't forget. When I started styling the router example, I realized boilerplate would be better suited, thus the timing of https://github.com/angular/angular/pull/40890 with this PR. You can even see I used router screenshots in that one. 

After #40890 was merged I started https://github.com/angular/angular/pull/41052, in part because of our dialogue here. I've put `state: blocked` on this PR because it should not merge before https://github.com/angular/angular/pull/41052. Hopefully this helps clarify things. Thanks for your excellent reviews, @gkalpak.

2021-03-15 15:28 UTC, kapunahelewong commented on aio/content/examples/router/src/app/heroes/hero-list/hero-list.component.css
>  }
Yes, removing in favor of https://github.com/angular/angular/pull/41052, which edits the boilerplate button styles more in keeping with what I'd started to do here..

2021-03-15 16:57 UTC, mary-poppins commented
You can preview d84d52c at https://pr40914-d84d52c.ngbuilds.io/.

2021-03-18 14:12 UTC, mary-poppins commented
You can preview 290d148 at https://pr40914-290d148.ngbuilds.io/.

2021-03-26 17:36 UTC, mary-poppins commented
You can preview 6164c36 at https://pr40914-6164c36.ngbuilds.io/.

2021-03-31 15:53 UTC, mary-poppins commented
You can preview bfb935f at https://pr40914-bfb935f.ngbuilds.io/.

2021-03-31 18:09 UTC, gkalpak requested changes
Is it intentional that the `Crisis Center` and the `Heroes` list item styles are different (different background colors when selected, different hover style, etc.)?

2021-03-31 18:09 UTC, gkalpak commented on aio/content/guide/router-tutorial-toh.md
> +Here's the component and its template:
Revert this now that you've added back the styles?

```suggestion
Here's the component, its template and styles:
```

2021-03-31 19:43 UTC, kapunahelewong commented on aio/content/examples/router/src/app/heroes/hero-detail/hero-detail.component.css
> +    font-size: 1.1rem;
ah, it was leftover from before https://github.com/angular/angular/pull/40890 was merged. Thanks for catching it!

2021-04-01 13:05 UTC, kapunahelewong commented on aio/content/examples/router/src/app/crisis-center/crisis-list/crisis-list.component.html
> +    <a [routerLink]="[crisis.id]" [class.selected]="crisis.id === selectedId">
Sure, here's my thinking. Currently, there are hover styles on the `<li>` as well as on the `<a>`, but it makes sense to apply all the interactivity-related styles to one element. Because the `<a>` tag is the interactive element which involves routing, it is the`<a>` tag with its content of the crisis that is selected, rather than the wrapper (`<li>`). What do you think?

2021-04-01 14:07 UTC, mary-poppins commented
You can preview 902ad36 at https://pr40914-902ad36.ngbuilds.io/.

2021-04-01 14:08 UTC, kapunahelewong commented on aio/content/examples/router/src/app/crisis-center/crisis-detail/crisis-detail.component.css
> +  margin-right: 1rem;
Added to boilerplate in https://github.com/angular/angular/pull/41413

2021-04-03 12:40 UTC, gkalpak commented on aio/content/examples/router/src/app/crisis-center/crisis-list/crisis-list.component.html
> +    <a [routerLink]="[crisis.id]" [class.selected]="crisis.id === selectedId">
I am on the fence regarding the semantics. One could argue that the it is the list-item that is selected (and the fact that the list-item contains a link to the corresponding hero is an implementation detail).

But semantics aside, from my experience it is always easier to add the class to the `<li>` (i.e. the outer element), because otherwise it is not possible to style the `<li>` itself (if needed) and it is easier to style sibling elements of the `<a>`. So, it is preferable imo to add the class to the `<li>` (even if it is not strictly needed).

I don't feel strongly about it, though. Leaving it up to you.

2021-04-03 12:41 UTC, gkalpak requested changes
Almost there :smiley:

My last question:
Is it intentional that the `Crisis Center` and the `Heroes` list item styles are different (different background colors when selected, different hover style, etc.)?

<sub>

[Note-to-self] Unresolved comments from previous review: https://github.com/angular/angular/pull/40914#discussion_r605097711

</sub>

2021-04-07 19:50 UTC, jelbourn approved these changes
Overall looks good except for @gkalpak's outstanding comment

2021-06-08 18:55 UTC, aikidave commented
@gkalpak Do you think you could make the last remaining changes to this PR so we can get merge it?

2021-06-10 09:10 UTC, gkalpak commented
@googlebot I consent.

2021-06-10 11:25 UTC, mary-poppins commented
You can preview 2d86e38 at https://pr40914-2d86e38.ngbuilds.io/.
You can preview 66af008 at https://pr40914-66af008.ngbuilds.io/.
You can preview ed684c7 at https://pr40914-ed684c7.ngbuilds.io/.
You can preview ce8adcd at https://pr40914-ce8adcd.ngbuilds.io/.
You can preview f4b2ac5 at https://pr40914-f4b2ac5.ngbuilds.io/.
You can preview a99f242 at https://pr40914-a99f242.ngbuilds.io/.
You can preview 38230d8 at https://pr40914-38230d8.ngbuilds.io/.
You can preview 8e3763a at https://pr40914-8e3763a.ngbuilds.io/.
You can preview d84d52c at https://pr40914-d84d52c.ngbuilds.io/.
You can preview 290d148 at https://pr40914-290d148.ngbuilds.io/.
You can preview 6164c36 at https://pr40914-6164c36.ngbuilds.io/.
You can preview 5dbd7a9 at https://pr40914-5dbd7a9.ngbuilds.io/.
You can preview bfb935f at https://pr40914-bfb935f.ngbuilds.io/.
You can preview 902ad36 at https://pr40914-902ad36.ngbuilds.io/.
You can preview 0a1bb38 at https://pr40914-0a1bb38.ngbuilds.io/.

2021-06-10 11:27 UTC, gkalpak approved these changes

2021-06-10 17:28 UTC, closed without merging