feat(common): add params percent encoding option
angular/angular pull request #40958
Opened 2021-02-23 05:48 UTC by solos

Previously, if a http param's value contains reserved characters such as
";", the value is not encoded correctly. It was encoded and then replaced.
But change the encoding method may cause some problems for old projects.
So this commit adds an option for http params percent encoding.

## PR Checklist

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [11058](https://github.com/angular/angular/issues/11058)  [26979](https://github.com/angular/angular/issues/26979 )  

## What is the new behavior?

  If create a http with option percentEncoding=true, the params will be percent encoded.
     var params  = new HttpParams({percentEncoding: true}); 

## Does this PR introduce a breaking change?

- [x] No

## Other information

2021-02-23 14:31 UTC, petebacondarwin requested changes
Thanks for getting this feature moving.
I have made some inline comments.

Ideally I would also like to see some more detailed tests of more cases for this codec.

2021-02-23 14:31 UTC, petebacondarwin commented on packages/common/http/src/params.ts
> +  percentEncoding?: boolean;
The idea is that the new encoder would be provided via the `encoder` property of this `options` object.
So there is no need to add a new property here.

2021-02-23 14:31 UTC, petebacondarwin commented on packages/common/http/src/params.ts
> +    }
This should be removed.

2021-02-23 14:31 UTC, petebacondarwin commented on packages/common/http/test/params_spec.ts
> +        const body = new HttpParams({fromObject: {a: '@:$,;+=?/', b: '2'}, percentEncoding: true});
```suggestion
        const encoder = new HttpUrlPercentEncodingCodec();
        const body = new HttpParams({fromObject: {a: '@:$,;+=?/', b: '2'}, encoder});
```

2021-02-23 14:31 UTC, petebacondarwin commented on packages/common/http/src/params.ts
> +export class HttpUrlPercentEncodingCodec implements HttpParameterCodec {
This class needs to be exported from  [packages/common/http/public_api.ts](https://github.com/angular/angular/blob/6fe3a1de7fc452d3e1240be392333126981e3516/packages/common/http/public_api.ts#L15).

2021-02-23 14:31 UTC, petebacondarwin commented on packages/common/http/src/params.ts
> +export class HttpUrlPercentEncodingCodec implements HttpParameterCodec {
And then the public API golden file will need to be updated.

2021-02-23 15:15 UTC, shardt68 commented
why don't use the fix from 
https://github.com/alxhub/angular/commit/fa5a37ecd8c3aeaa1269746818e8f6b9fbf063e5
it is a general solution for the bug

2021-02-23 16:08 UTC, petebacondarwin commented
I was not aware of alxhub@fa5a37e. I have to admit that is a reasonable solution. Perhaps @alxhub could make a call here?

2021-02-23 17:59 UTC, alxhub commented
I think reviving that commit would be ideal (and fixing it - that initial work was not fully baked yet) I have two concerns about this PR:

1) the name `HttpUrlPercentEncodingCodec` is too specific to the bug. It should describe what the class does, not what it fixes.

2) as @petebacondarwin notes, the `percentEncoding` flag is unnecessary.

I'm wondering if perhaps making the fix opt-in is unnecessary. Maybe in 12 we should just fix the bug, and have an opt-out to return to the old behavior if required.

2021-02-24 01:25 UTC, solos commented on packages/common/http/src/params.ts
> +  percentEncoding?: boolean;
Yeah, adding this option is just for convenience. Without this opt, I have to import class and create a new encoder and pass it. Do you think it is unnecessary?

2021-02-24 01:47 UTC, solos commented
1. HttpUrlPercentEncodingCodec 's function is  percent encoding for params. It does not fix something. It just for  percent encoding.
2. percentEncoding is for convenience. So need not to create a new  encoder where create http params.
It has been a long time since the issue was created. I think it should be resolved in Angular 11.

2021-03-09 17:16 UTC, closed without merging