refactor(zone.js): remove onProp eventName array to reduce bundle size
angular/angular pull request #40962
Opened 2021-02-23 13:54 UTC by JiaLiPassion

Zone.js supports google closure compiler in advance optimization mode,
to prevent closure compiler modify the `onProperty` name such as `Element.prototype.onclick`,
Zone.js implements the `onProperty` patch logic by declaring all the
event names in source code, this increases the bundle size and also require
updating the event names array to keep the information updated.

Now google closure compiler has the required event names defined in the built-in
externs files, so zone.js can use more simple implementation and decrease the bundle size
of zone.js.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-02-23 14:44 UTC, josephperrott approved these changes
LGTM

Looks like we just need the size tracking to be updated.

2021-02-24 00:39 UTC, AndrewKushnir approved these changes
Great refactoring and almost 4Kb savings! 👍 

Reviewed-for: size-tracking

2021-02-24 00:42 UTC, AndrewKushnir commented
@JiaLiPassion it looks like there are more places where payload size should be updated, see `test_ivy_aot` CI job output.

Could you please also set the "target" label (would it be safe to land in patch version or only in major)?

2021-02-24 01:16 UTC, JiaLiPassion commented
@AndrewKushnir , @josephperrott , thank you for the review. I have updated the size and also added the target label.
@AndrewKushnir , could you also run a `presubmit` to check whether it breaks `g3`, I remembered there was an issue about using closure complier advanced optimization failed without these event names.

2021-02-24 01:33 UTC, AndrewKushnir commented
@JiaLiPassion sure, I've started a [presubmit](http://test/OCL:359172596:BASE:359172611:1614130382899:f0e69ed), will let you know how it goes.

2021-02-24 06:29 UTC, AndrewKushnir commented
@JiaLiPassion FYI presubmits went well, but I think we'd need to run a global one before merging this change. Thank you.

2021-02-24 06:43 UTC, JiaLiPassion commented
@AndrewKushnir , got it, thank you!

2021-02-24 17:27 UTC, petebacondarwin approved these changes
Reviewed-for: size-tracking

2021-02-24 21:33 UTC, jelbourn commented on packages/zone.js/lib/browser/api-util.ts
> +  const eventNames: string[] = [];
I might leave a comment here like
```ts
// Collect native event names by looking at properties
// on the global namespace, e.g. 'onclick'.
```

2021-02-24 21:33 UTC, jelbourn commented on packages/zone.js/lib/browser/property-descriptor.ts
> +function getOnEventNames(target: any) {
Could this `any` be something more specific? Even if it's just `object`.

2021-02-24 21:33 UTC, jelbourn commented on packages/zone.js/lib/browser/property-descriptor.ts
> +  let patchTargets: any[] = [];
Should this be `string[]`?

2021-02-24 21:33 UTC, jelbourn commented on packages/zone.js/lib/browser/property-descriptor.ts
> +  patchTargets.forEach(t => {
Could this use a `for` loop rather than `.forEach`?

https://github.com/angular/angular/blob/master/docs/CODING_STANDARDS.md#iteration

2021-02-24 23:53 UTC, JiaLiPassion commented on packages/zone.js/lib/browser/api-util.ts
> +  const eventNames: string[] = [];
Got it, thanks, I updated the comment here.

2021-02-24 23:54 UTC, JiaLiPassion commented on packages/zone.js/lib/browser/property-descriptor.ts
> +  let patchTargets: any[] = [];
Yes, I updated the type here, thanks!

2021-02-24 23:56 UTC, JiaLiPassion commented on packages/zone.js/lib/browser/property-descriptor.ts
> +  patchTargets.forEach(t => {
Got it, I updated the code to `for` loop. Thanks.

2021-02-25 00:02 UTC, JiaLiPassion commented on packages/zone.js/lib/browser/property-descriptor.ts
> +function getOnEventNames(target: any) {
Yeah, it is the prototype, so it can be specific to `object`.

2021-02-25 01:15 UTC, jelbourn approved these changes
LGTM

Reviewed-for: size-tracking

2021-02-25 08:22 UTC, Nikhil27b approved these changes

2021-03-01 21:15 UTC, mhevery approved these changes

2021-03-01 21:18 UTC, mhevery commented
[presubmit](http://test/OCL:360261758:BASE:360261797:1614633496382:90cf212a)

2021-03-03 19:30 UTC, AndrewKushnir commented
FYI, adding a cleanup label since there is a merge conflict with the master branch. @JiaLiPassion could you please rebase and resolve the conflict when you get a chance? Thank you.

2021-03-04 01:32 UTC, JiaLiPassion commented
@AndrewKushnir , got it, I rebased the PR and resolved the conflict, thank you!

2021-03-04 05:51 UTC, AndrewKushnir commented
@JiaLiPassion thanks for rebasing this PR 👍 I've also started a [global presubmit](https://test.corp.google.com/OCL:359172596:BASE:360831617:1614836992627:90ec4972) (in addition to a subset of tests that were checked before), will let you know how it goes. Thank you.

2021-03-04 19:47 UTC, AndrewKushnir commented
@JiaLiPassion it looks like there are few affected targets in Google's codebase that would require additional investigation. I'm adding the "blocked" label for now and will share more info once I perform further investigation. Thank you.

2021-03-05 01:38 UTC, JiaLiPassion commented
@AndrewKushnir , got it, thank you. I will wait for your information.

2021-03-08 18:14 UTC, mhevery requested changes
Failing in g3 due to the comment below.

2021-03-08 18:14 UTC, mhevery commented on packages/zone.js/lib/browser/property-descriptor.ts
> +  return Object.getOwnPropertyNames(target)
I don't believe this function is correct.
`getOnEventNames(XMLHttpRequest)` returns `[]`. The reason for this is that we need to walk the inheritance hierarchy to collect all of the properties. Could you update the code and add some tests which shows that this is the case. 

ALSO: It seems like this function and `for (let key in global) {` has some overlap. Not sure if we can merge the to, but worth investigating.

2021-03-09 00:37 UTC, JiaLiPassion commented on packages/zone.js/lib/browser/property-descriptor.ts
> +  return Object.getOwnPropertyNames(target)
@mhevery, the current logic is to call `getOnEventNames(XMLHttpRequest.prototype)` which returns `['readystatechange']`, and since `XMLHttpRequest` inherits `XMLHttpRequestEventTarget`, so here https://github.com/angular/angular/pull/40962/files#diff-75568e77504519f5bd9d81b3baacea64225e1f015f030fb0fa767b5b5df69853R79 we also patch the `XMLHttpRequestEventTarget.protptype`, `getOnEventNames(XMLHttpRequestEventTarget.prototype)` returns `["loadstart", "progress", "abort", "error", "load", "timeout", "loadend"]`.

So I believe this is the expect result, could you post more information about the failure in `g3`?

`ALSO: It seems like this function and for (let key in global) { has some overlap. Not sure if we can merge the to, but worth investigating.`

Got it, I will check this one.

2021-03-09 19:18 UTC, mhevery commented
[presubmit](http://test/OCL:360261758:BASE:361853862:1615317487110:e7a84c84)

2021-03-09 19:19 UTC, mhevery commented on packages/zone.js/lib/browser/property-descriptor.ts
> +  return Object.getOwnPropertyNames(target)
let me rerun presubmit to see if it helps

2021-03-10 03:08 UTC, JiaLiPassion commented
@mhevery , I added another test cases to make sure all `evergreen browsers` are patched correctly, and this PR should patch the same eventNames with the old way.

And I found a breaking change is the `eventNames` array is also used for `legacy browser` patch, and the new way lack of some events, so I put the old eventNames array to the `legacy patch` code here https://github.com/angular/angular/pull/40962/files#diff-4351958690be6f3466945830172d704d8e1d8711ec9eb3fdf41c7abd4b641cd6R110. It will not impact the bundle size of bundle of `evergreen` browsers.

Could you start another `global presubmit`, if still fail, I will create another `debug commit` to check which event is not patched, thank you.

2021-03-10 03:45 UTC, AndrewKushnir commented
@JiaLiPassion @mhevery FYI I've just tested the most recent changes from this PR with the targets that were failing previously.- the targets are still failing ([internal-only link to test results](https://test.corp.google.com/ui#id=OCL:359172596:BASE:361953196:1615347181700:1a09b9a7)).

2021-03-10 03:57 UTC, JiaLiPassion commented
@AndrewKushnir , got it, thank you, I will create a debug PR to check which eventName is not patched.

2021-03-10 05:45 UTC, JiaLiPassion commented
@AndrewKushnir , I created a debug commit, could you run another presubmit? If the error is gone, could you send me the console log where the error occurs without this debug commit? Thank you.

2021-03-12 00:11 UTC, AndrewKushnir commented
Hi Jia, just ran the tests again, the targets are still failing (and I verified that they work correctly without the change from this PR). Please let me know what we can try next. Thank you.

2021-03-12 03:08 UTC, JiaLiPassion commented
@AndrewKushnir, it is a little weird that the debug version still failed the `g3`, I updated another `debug` version, could you try the `presubmit` again? Thank you.

2021-03-12 03:12 UTC, JiaLiPassion commented
@AndrewKushnir, it is a little weird that the debug version still failed the `g3`, I updated another `debug` version, could you try the `presubmit` again? Thank you.

2021-03-12 05:02 UTC, AndrewKushnir commented
Hi @JiaLiPassion, sure, I can try again. Could you please rebase this PR on top of the most recent version of the master branch and resolve conflicts (so that I can try to sync it again)? Thank you.

2021-03-12 06:54 UTC, JiaLiPassion commented
@AndrewKushnir , got it, I just rebased the PR, thank you.

2021-03-12 23:38 UTC, AndrewKushnir commented
Hey @JiaLiPassion, thanks for rebasing.

I've performed additional investigation and found out that the problem was caused by the presence of extra property on the `window` that starts with `on`, something like:
```
window.one_two_three = { ... };
```
as a result, that was picked up by the `getOnEventNames` function as a possible event name. If I filter out that property, everything works as expected.

Is there any protection that we can add (for ex. check the type of the field before patching it)?

Thank you.

2021-03-13 00:52 UTC, JiaLiPassion commented
Got it, thank you very much for the investigation, I have updated the code to also support onProperty which is not a function, could you run another presubmit?

2021-03-13 01:35 UTC, AndrewKushnir commented
@JiaLiPassion thanks for the fixes! I've started a new set of tests and will run a broader set of targets tonight as well. I've checked one of the previously failing target and it works correctly now, which is a good sign! Will keep you updated. Thank you.

2021-03-13 19:28 UTC, AndrewKushnir commented
[Global Presubmit #2](https://test.corp.google.com/OCL:362441781:BASE:362717130:1615663689287:fb41967).

2021-03-15 19:38 UTC, AndrewKushnir commented
Hi @JiaLiPassion, just a quick update: the most recent change resolved the issue with one target, but there is a couple more failing targets still. We'll need to perform more investigation to find the origin of the problem. Will keep you updated.

2021-03-16 01:10 UTC, JiaLiPassion commented
@AndrewKushnir , got it, thank you, please tell me if any debug version is needed.

2022-02-10 02:53 UTC, AndrewKushnir commented
[Global Presubmit](https://test.corp.google.com/OCL:427626829:BASE:427626881:1644461610052:6d68a356).

2022-02-10 06:23 UTC, AndrewKushnir commented
@JiaLiPassion FYI the presubmit went well (all targets are "green").

The change was reviewed and approved previously (almost a year ago), but I'd like to ask @alxhub to take a look as well.

Thank you.

2022-02-10 06:45 UTC, JiaLiPassion commented
@AndrewKushnir, got it, thank you very much!

2022-02-25 21:59 UTC, alxhub approved these changes

2022-02-25 21:59 UTC, alxhub commented on packages/zone.js/lib/browser/property-descriptor-legacy.ts
> +const eventNames = globalEventHandlersEventNames.concat(
This is a slightly confusing way to write this. Perhaps:

```typescript
const eventNames = [
  ...globalEventHandlersEventNames,
  ...webglEventNames,
  ...
];
```

would be slightly more readable. Or is this version preferred for code size?

2022-02-25 21:59 UTC, alxhub commented on packages/zone.js/lib/browser/property-descriptor.ts
> +  return Object.getOwnPropertyNames(target)
Can you add a doc comment to this function describing its intention (and specifically, that it only considers the immediate object properties and not any inherited properties).

2022-02-25 22:33 UTC, JiaLiPassion commented on packages/zone.js/lib/browser/property-descriptor-legacy.ts
> +const eventNames = globalEventHandlersEventNames.concat(
Got it, I updated the code style with `[...]`, thank you.

2022-02-25 22:33 UTC, JiaLiPassion commented
@alxhub , thank you for the review, I have added the comments and update the code style.

2022-03-01 05:19 UTC, AndrewKushnir commented
[Global Presubmit #2](https://fusion2.corp.google.com/presubmit/tap/427626829/OCL:427626829:BASE:431596891:1646111892580:557f826c/targets).

2022-03-01 17:09 UTC, AndrewKushnir commented
FYI, the presubmit is "green", so I'm adding this PR to the merge queue.

2022-03-01 17:11 UTC, AndrewKushnir commented
Note to the Caretaker: please sync this PR into g3 as a separate change.

2022-03-01 18:39 UTC, jessicajaniuk commented
This does not merge cleanly with `13.2.x`. I'll update to `target: minor` and land it. Please create a patch PR targeting `13.2.x` and we'll land that one, too.

2022-03-01 18:41 UTC, jessicajaniuk commented
This PR was merged into the repository by commit 1b85811c00fdf1164649df66f4c20c5da5765e42.

2022-03-01 18:41 UTC, closed without merging