fix(core): create component should always inside angular zone
angular/angular pull request #40989
Opened 2021-02-25 01:44 UTC by JiaLiPassion

Close #38260, #37223
related to #40860

When `bootstrap` or `dynamic` create component, it may happen outside of ngZone, such as
use a `route guard` outside of ngZone, or trigger `*ngIf` with a `eventListener` outside of ngZone,
so this PR ensure all component creation(view rendering) happen in the angular zone.

2021-02-25 01:44 UTC, JiaLiPassion commented
@atscott, this is related to #40860, this is a generic solution for the issue, since not only `router`, there also other cases may cause the similar issues. Please review this is a reasonable solution or not, thanks.

2021-02-25 03:07 UTC, atscott commented
@JiaLiPassion does this replace #40860 or should this be merged in addition to that one?

2021-02-25 06:09 UTC, JiaLiPassion commented
@atscott , if this idea is ok, this will be a replace of #40860, since this will not only fix the issue of `router`, but also fix other similar issues.

2021-02-25 13:48 UTC, arturovt commented on packages/core/src/render3/component_ref.ts
> +          return ngZone.run(() => {
Hey @JiaLiPassion . I've got a question regarding that. Since this is a public API this is likely introducing a relatively big breaking change from behavior standpoint where more views would be processed by change detection. We have components that are explicitly created outside of the zone manually via `factory.create()`. We could at least have some option to opt out from this behavior.

2021-02-25 15:56 UTC, JoostK commented on packages/core/src/render3/component_ref.ts
> +          return ngZone.run(() => {
I also think that incorporating Zone logic in the primary rendering primitive itself is not really desirable; as @arturovt points out there are valid cases where one explicitly opts-out of zone tracking.

It currently works very consistently to me: every activity that originates from outside of the Zone will also run outside of the Zone. I would personally not even consider #37223 as a bug: I'd consider the code that leaves the Zone to also be responsible for re-entering the Zone when applicable. Without this symmetry the behavior becomes hard to reason about.

2021-03-04 00:21 UTC, mhevery requested changes
I don't believe we should be merging this either. If you feel otherwise feel free to bring it up in team meeting. As pointed out there are valid cases where components should not be in Zone.

2021-03-04 00:21 UTC, mhevery commented on packages/core/src/render3/component_ref.ts
> +          return ngZone.run(() => {
I agree, I don't believe we should be special casing this.

2021-03-22 15:23 UTC, atscott commented
Closing, per discussions above.

2021-03-22 15:23 UTC, closed without merging

2021-03-22 15:55 UTC, bbaia commented
The goal is to remove zone.js to be fully reactive.

For now, I have to do this on a zoneless app:
```typescript
@Component({
  selector: 'app-sample',
  template: '<router-outlet (activate)="onRouteActivated()"></router-outlet>'
})
export class SampleComponent {
  constructor(private cdRef: ChangeDetectorRef) {}

  onRouteActivated() {
    this.cdRef.detectChanges();
  }
}
```