fix(ngcc): do not fail hard when a format-path points to a non-existing or empty file
angular/angular pull request #40985
Opened 2021-02-24 18:48 UTC by gkalpak

Previously, when `ngcc` encountered an entry-point with a format-path that pointed to a non-existing or empty file it would throw an error and stop processing the remaining tasks.

In the past, we used to ignore such format-paths and continue processing the rest of the tasks ([see code][1]). This was changed to a hard failure in 2954d1b5ca212548c5c4634a30ce773cfe3b9410. Looking at the code history, the reason for changing the behavior was an (incorrect) assumption that the condition could not fail. This assumption failed to take into account the case where a 3rd-party library has an invalid format-path in its `package.json`. This is an issue with the library, but it should not prevent `ngcc` from processing other packages/entry-points/formats.

This commit fixes this by reporting the task as failed but not throwing an error, thus allowing `ngcc` to continue processing other tasks.

Fixes #40965.

[1]: https://github.com/angular/angular/blob/3077c9a1f89c5bd75fb96c16e/packages/compiler-cli/ngcc/src/main.ts#L124

2021-02-24 18:59 UTC, mary-poppins commented
You can preview 0b49aee at https://pr40985-0b49aee.ngbuilds.io/.

2021-02-24 20:50 UTC, mary-poppins commented
You can preview e8a341a at https://pr40985-e8a341a.ngbuilds.io/.

2021-02-25 09:45 UTC, mary-poppins commented
You can preview d0a6348 at https://pr40985-d0a6348.ngbuilds.io/.

2021-02-25 10:41 UTC, petebacondarwin requested changes

2021-02-25 10:41 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/create_compile_function.ts
> +            `property '${formatProperty}' pointing to a missing or empty file (${formatPath}).`);
Subjective NIT:

```suggestion
            `property \`${formatProperty}\` pointing to a missing or empty file: ${formatPath}.`);
```

2021-02-25 10:41 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/tasks/completion.ts
> +  const jsFormat = `${task.formatProperty} as ${
Subjective NIT:

```suggestion
  const jsFormat = `\`${task.formatProperty}\` as ${
```

2021-02-25 10:41 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/integration/ngcc_spec.ts
> +        propertiesToConsider: ['es2015', 'fesm5', 'main'],
Perhaps put the `main` property earlier in the list so that we can see that it failure does not block other formats from being processed.

Also, what happens if the `main` property is the one that is assigned to the `typings` processing?

2021-02-25 13:56 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/execution/tasks/completion.ts
> +  const jsFormat = `${task.formatProperty} as ${
This seems out of scope for this PR.
(Also, you do realize this is _your_ code, right? 😛)

2021-02-25 14:05 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/execution/tasks/completion.ts
> +  const jsFormat = `${task.formatProperty} as ${
Given that you are changing the line anyway. (And I have never been one to ideologically stick with my previous decisions).

2021-02-25 14:59 UTC, gkalpak commented on packages/compiler-cli/ngcc/test/integration/ngcc_spec.ts
> +        propertiesToConsider: ['es2015', 'fesm5', 'main'],
> Also, what happens if the main property is the one that is assigned to the typings processing?

Not great things :grin:

Hopefully, since `main` is low in the list of default properties to consider (and in CLI's list of properties), `main` will rarely be associated with processing typings.

In any case, this is not much different from what would happen if the `formatPath` for another property (which is associated with typings processing) points to a missing/empty file. In fact, `ngcc` seems to fail silently (from a super-quick loog) in that case, which is argueably worse than failing the taks and printing an error message :grin:

2021-02-25 15:11 UTC, mary-poppins commented
You can preview fcb6051 at https://pr40985-fcb6051.ngbuilds.io/.

2021-02-25 15:28 UTC, mary-poppins commented
You can preview f82d92b at https://pr40985-f82d92b.ngbuilds.io/.

2021-02-25 15:53 UTC, mary-poppins commented
You can preview 50265ed at https://pr40985-50265ed.ngbuilds.io/.

2021-02-25 16:18 UTC, JoostK approved these changes

2021-02-25 17:32 UTC, petebacondarwin approved these changes

2021-02-26 16:26 UTC, closed without merging