feat(localize): add scripts to migrate away from legacy message IDs
angular/angular pull request #41026
Opened 2021-02-27 10:54 UTC by crisbeto

Adds a new flag to `localize-extract` called `--migrateMapFile` which will generate a JSON file that can be used to map legacy message IDs to canonical ones.

Also includes a new script called `localize-migrate` that can take the mapping file which was generated by `localize-extract` and migrate all of the IDs in the files that were passed in.

2021-02-27 14:01 UTC, crisbeto commented on packages/localize/src/tools/test/migrate/integration/main_spec.ts
> +    function readAndNormalize(path: AbsoluteFsPath): string {
This function is a little weird, but it's necessary to pass the Windows check on Circle. For some reason it only happened on the CI, the line endings were correct when I was running it locally on my Windows machine.

2021-03-01 12:23 UTC, petebacondarwin requested changes
I left a lot of comments. Many are just suggestions.

Once I finished I had an idea. How about instead of adding a new option to extract we add a new format type. This will be much easier to integrate into the CLI and also easier to remove later. It would also reduce the amount of changes needed in the `extract/main.ts` file.

 What do you think?

2021-03-01 12:23 UTC, petebacondarwin commented on packages/localize/src/tools/test/migrate/integration/test_files/messages.xlf
> +<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="en-GB">
I think it is worth also having an XLIFF 1.2 file too.

2021-03-01 12:23 UTC, petebacondarwin commented on packages/localize/src/tools/test/migrate/integration/test_files/messages.xlf
> +<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="en-GB">
Although I see that the unit tests use XLIFF 1.2 so perhaps that is covered there.

2021-03-01 12:23 UTC, petebacondarwin commented on packages/localize/src/tools/test/migrate/integration/main_spec.ts
> +      return fs.readFile(path).replace(/\r\n|\r|\n/g, '\n');
```suggestion
      return fs.readFile(path).replace(/\r?\n/g, '\n');
```

2021-03-01 12:23 UTC, petebacondarwin commented on packages/localize/src/tools/test/migrate/integration/main_spec.ts
> +    function readAndNormalize(path: AbsoluteFsPath): string {
That is weird... I think it might be because you were joining using `\n` rather than whatever the OS was setup to use? Perhaps on your machine git is set up to use `\n` rather than `\r\n` line-endings whereas the CI was setup to use `\r\n`?

2021-03-01 12:23 UTC, petebacondarwin commented on packages/localize/src/tools/src/migrate/main.ts
> +                'A glob pattern indicating what files to migrate. Either absolute or relative to the current working directory',
Should this be "relative to the `root` path"?

2021-03-01 12:23 UTC, petebacondarwin commented on packages/localize/src/tools/src/migrate/main.ts
> +                'Path to the migration mapping file generated by `localize-extract`. Either absolute or relative to the current working directory.',
According to the usage later on this should be relative to `root`.

Given that we are not really manipulating the paths, the `root` is not that important. We could probably drop the `root` option altogether and insist that all paths are relative to the CWD?

2021-03-01 12:23 UTC, petebacondarwin commented on packages/localize/src/tools/src/migrate/main.ts
> +  const logger = new ConsoleLogger(LogLevel.warn);
Is it worth making the logger level configurable?

2021-03-01 12:23 UTC, petebacondarwin commented on packages/localize/src/tools/src/migrate/main.ts
> +  const mappingFilePath = fs.resolve(options.m);
```suggestion
  const mappingFilePath = fs.resolve(rootPath, options.m);
```

2021-03-01 12:23 UTC, petebacondarwin commented on packages/localize/src/tools/src/migrate/main.ts
> +  const mappingFilePath = fs.resolve(options.m);
Or given that this is resolved again later in the `migrateFiles()` function we could just get rid of this line altogether.

2021-03-01 12:23 UTC, petebacondarwin commented on packages/localize/src/tools/src/migrate/main.ts
> +  const mappingContents = fs.readFileBuffer(absoluteMappingPath);
Why use `readFileBuffer()` here? You can just use `readFile()` which will return a string:

```
const mapping = JSON.parse(fs.readFile(absoluteMappingPath)) as MigrationMapping;
```

2021-03-01 12:23 UTC, petebacondarwin commented on packages/localize/src/tools/src/migrate/main.ts
> +    translationFilePaths.map(relativeFrom).forEach(path => {
`relativeFrom` should not be needed here. `fs.resolve()` can just take any string for its arguments.

2021-03-02 16:42 UTC, crisbeto reviewed
Thank you for the feedback @petebacondarwin, most of it should be addressed. Regarding the point around making the migration file a new format, I can see two points against it:
1. It might just be me, but it feels weird to call it a new translation format when it really isn't. It's just a mapping between IDs.
2. Outputting it in addition to the actual translations would make sure that the source translations are up to date.

I don't feel strongly against it, it just seems like we're mixing up the terminology.

2021-03-02 16:42 UTC, crisbeto commented on packages/localize/src/tools/src/extract/main.ts
> +    migrationMapFile: options.migrationMapFile,
I thought about this when I was considering whether to add a warning if `migrationMapFile` is passed in, but `useLegacyIds` is false. Wouldn't doing this for a project that isn't using legacy IDs cause the existing translations to be overwritten with legacy IDs?

2021-03-02 16:42 UTC, crisbeto commented on packages/localize/src/tools/src/extract/main.ts
> +    }
Doesn't this go against the single responsibility of the serializer (serializing messages to files)?

2021-03-02 16:42 UTC, crisbeto commented on packages/localize/src/tools/src/extract/translation_files/legacy_message_id_migration_serializer.ts
> +  /** Gets whether any of the passed-in messages need to be migrated. */
We've had the exact opposite conversation with Jeremy on the Components repo 😅. The argument against using "returns" is that it could be confused with the `@returns` jsdoc tag.

2021-03-02 16:42 UTC, crisbeto commented on packages/localize/src/tools/src/extract/translation_files/legacy_message_id_migration_serializer.ts
> +          output[legacyId] = message.id;
I think that it's unlikely since we filter out messages that have a `customId`.

2021-03-02 16:42 UTC, crisbeto commented on packages/localize/src/tools/src/extract/translation_files/legacy_message_id_migration_serializer.ts
> +  return !message.customId && !!message.legacyIds && message.legacyIds.length > 0;
That doesn't work, because `message.legacyIds?.length` resolves to `number | undefined`.

2021-03-02 16:42 UTC, crisbeto commented on packages/localize/src/tools/src/migrate/main.ts
> +                'Path to the migration mapping file generated by `localize-extract`. Either absolute or relative to the current working directory.',
I set up this way so it's consistent with the other `localize-` scripts. I think that it won't matter in practice, because the `root` is optional and it defaults to the current working directory.

2021-03-02 16:42 UTC, crisbeto commented on packages/localize/src/tools/src/migrate/main.ts
> +  const logger = new ConsoleLogger(LogLevel.warn);
I don't think so. The main reason I added the logger was so that there's an easy place to hook in for unit tests.

2021-03-02 16:45 UTC, petebacondarwin commented on packages/localize/src/tools/src/extract/translation_files/legacy_message_id_migration_serializer.ts
> +  /** Gets whether any of the passed-in messages need to be migrated. */
LOL!

For me "gets whether" is rather ambiguous and unclear.

Clearly for a more complicated function that does stuff and then happens to return a boolean, it would be better to describe what that stuff is, and then use a `@returns` tag to specify what the boolean return value means.

But in these cases where the whole purpose of the function is to return a boolean, this is the most clear and straightforward description.

2021-03-02 16:47 UTC, petebacondarwin commented on packages/localize/src/tools/src/extract/main.ts
> +    migrationMapFile: options.migrationMapFile,
If a project is not using legacy IDs then why would it run the migration?
This is an argument for changing the whole approach so that we have a `legacy-migrate` translation file format, so that only the migration file is generated and not any other translation file.

2021-03-02 16:52 UTC, crisbeto commented on packages/localize/src/tools/src/extract/main.ts
> +    migrationMapFile: options.migrationMapFile,
That's a good point about it being another argument for the new format. Regarding this:

>If a project is not using legacy IDs then why would it run the migration?

My thinking was that people might run the script since they don't actually know if they have any legacy message IDs.

2021-03-02 16:56 UTC, petebacondarwin commented on packages/localize/src/tools/src/extract/main.ts
> +    }
I don't think so. The `TranslationSerializer` ought to be able record diagnostic issues when doing its job.

2021-03-02 16:56 UTC, petebacondarwin commented on packages/localize/src/tools/src/extract/translation_files/legacy_message_id_migration_serializer.ts
> +  return !message.customId && !!message.legacyIds && message.legacyIds.length > 0;
But it turns out (rather fortuitously) that `undefined > 0` is `false` 😄 
(I checked this before making the suggestion.)

2021-03-02 16:58 UTC, petebacondarwin commented on packages/localize/src/tools/src/migrate/main.ts
> +                'Path to the migration mapping file generated by `localize-extract`. Either absolute or relative to the current working directory.',
If we do have the `root` option then all the other options should be relative to it, not CWD.

2021-03-02 16:58 UTC, petebacondarwin commented on packages/localize/src/tools/src/migrate/main.ts
> +  const logger = new ConsoleLogger(LogLevel.warn);
👍

2021-03-02 16:59 UTC, crisbeto commented on packages/localize/src/tools/src/extract/translation_files/legacy_message_id_migration_serializer.ts
> +  return !message.customId && !!message.legacyIds && message.legacyIds.length > 0;
Sure, but `strictNullChecks` doesn't like comparing `undefined` to a number.
![legacy_message_id_migration_serializer ts_-_angula_2021-03-02_17-59-08](https://user-images.githubusercontent.com/4450522/109684913-07fdc000-7b81-11eb-8023-b581fc2a72fc.png)

2021-03-02 17:00 UTC, petebacondarwin commented on packages/localize/src/tools/src/extract/translation_files/legacy_message_id_migration_serializer.ts
> +  return !message.customId && !!message.legacyIds && message.legacyIds.length > 0;
But perhaps this is a bit too magical...

2021-03-02 17:01 UTC, crisbeto commented on packages/localize/src/tools/src/migrate/main.ts
> +                'Path to the migration mapping file generated by `localize-extract`. Either absolute or relative to the current working directory.',
They're relative to it already, the docs were inaccurate before because I started off with them being relative to the CWD.

2021-03-05 16:20 UTC, crisbeto commented
@petebacondarwin I've addressed the latest set of feedback.

2021-03-05 18:00 UTC, petebacondarwin commented on packages/localize/src/tools/src/extract/main.ts
> +function getSerializer(
👍

2021-03-05 18:09 UTC, petebacondarwin approved these changes
Just one NIT. Nice work @crisbeto

2021-03-05 18:09 UTC, petebacondarwin commented on packages/localize/src/tools/src/migrate/main.ts
> +      const sourceCode = Buffer.from(contents).toString('utf8');
```suggestion
      const sourceCode = fs.readFile(absolutePath);
```

2021-03-05 18:11 UTC, petebacondarwin commented
I switched the `dev-infra` reviewer as Joey is away

2021-03-05 21:34 UTC, AndrewKushnir commented
Hey @crisbeto, just want to double check whether this PR is ready for merge, since I see that the `dev-infra` group has not reviewed the changes yet, but there is a "merge-assistance" label. Thank you.

2021-03-05 21:37 UTC, crisbeto commented
Yes, it's ready to go. I'm not sure why `dev-infra` was requested since there aren't any dev infra changes.

2021-03-05 21:40 UTC, petebacondarwin commented
The dev-infra approval is for the Bazel changes

2021-03-08 17:46 UTC, josephperrott approved these changes
LGTM

2021-03-08 18:05 UTC, closed without merging