fix(compiler-cli): ensure ngcc can handle wildcard base-paths
angular/angular pull request #41033
Opened 2021-02-28 18:21 UTC by petebacondarwin

Ngcc uses the `paths` property to compute the potential base-paths
for packages that are being processed. If the `paths` contain a wildcard
`*` within a path segment, ngcc was not finding the base-path correctly.

Now when a wildcard is found, there is an additional search to look for
paths that might match the wildcard.

Fixes #41014

2021-02-28 20:20 UTC, JoostK commented on packages/compiler-cli/ngcc/test/entry_point_finder/utils_spec.ts
> +      const pathMappings = {baseUrl: projectDirectory, paths: {'@dist-*': ['dist-*']}};
Would be interesting to have a test for something like `'@scope/*': ['dist/*']`, i.e. the wildcard spans the full directory name.

2021-03-01 10:01 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/test/entry_point_finder/utils_spec.ts
> +      const pathMappings = {baseUrl: projectDirectory, paths: {'@dist-*': ['dist-*']}};
As it stands in that case the base path will just be `dist`: Since we check whether `dist/` is a directory (after stripping the `*`), the code will never get to the bit where it has to search for additional base-paths. This already covered in the test at https://github.com/angular/angular/blob/master/packages/compiler-cli/ngcc/test/entry_point_finder/utils_spec.ts#L40 - note that `libs` is one of the identified base-paths: https://github.com/angular/angular/blob/master/packages/compiler-cli/ngcc/test/entry_point_finder/utils_spec.ts#L46

2021-03-01 10:08 UTC, JoostK approved these changes

2021-03-01 15:03 UTC, gkalpak requested changes

2021-03-01 15:06 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/entry_point_finder/utils.ts
> +          continue;
In that case the base-path would be `dist/foo` and we would not pick up `foo-one` as a base-path.

But given that this problem has not come up before and the issue being fixed is an uncommon case, and the case you propose would be even more rare, I don't think it is worth worrying about.

2021-03-01 15:08 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/entry_point_finder/utils.ts
> +            }
This is to stop us reaching the debug log warning below for this `path`.

2021-03-01 15:18 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/entry_point_finder/utils.ts
> +          continue;
But the fix would be trivial 🙏 🙏 🙏 

```diff
       for (const path of paths) {
+        let foundMatch = false;
         // We only want base paths that exist and are not files
         const {prefix, hasWildcard} = extractPathPrefix(path);
         let basePath = fs.resolve(baseUrl, prefix);
         if (fs.exists(basePath) && fs.stat(basePath).isFile()) {
           basePath = fs.dirname(basePath);
         }
         if (fs.exists(basePath)) {
           basePaths.push(basePath);
-          continue;
+          foundMatch = true;
         }
 
         if (hasWildcard) {
           // The path contains a wildcard so try searching for matching paths
           const wildcardContainer = fs.dirname(basePath);
           const wildcardPrefix = fs.basename(basePath);
           if (isExistingDirectory(fs, wildcardContainer)) {
-            let foundMatch = false;
             const candidates = fs.readdir(wildcardContainer);
             for (const candidate of candidates) {
               if (candidate.startsWith(wildcardPrefix)) {
                 const candidatePath = fs.resolve(wildcardContainer, candidate);
                 if (isExistingDirectory(fs, candidatePath)) {
                   foundMatch = true;
                   basePaths.push(candidatePath);
                 }
               }
             }
-            if (foundMatch) {
-              continue;
-            }
           }
         }
 
+        if (foundMatch) {
+          continue;
+        }
+
         logger.debug(
             `The basePath "${basePath}" computed from baseUrl "${baseUrl}" and path mapping "${
                 path}" does not exist in the file-system.\n` +
             `It will not be scanned for entry-points.`);
       }
```

2021-03-01 15:19 UTC, gkalpak commented on packages/compiler-cli/ngcc/src/entry_point_finder/utils.ts
> +            }
Ooops, missed that 😇

2021-03-01 15:20 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/entry_point_finder/utils.ts
> +          continue;
OOOKKKK then 😸

2021-03-01 15:29 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/entry_point_finder/utils.ts
> +          continue;
Done. PTAL

2021-03-01 15:31 UTC, petebacondarwin commented on packages/compiler-cli/ngcc/src/entry_point_finder/utils.ts
> +          continue;
As a bonus we get rid of all the `continue` statements in that block.

2021-03-01 18:12 UTC, gkalpak approved these changes
❤️

2021-03-01 23:26 UTC, closed without merging