progress on milestone 1
angular/angular pull request #41043
Opened 2021-03-02 00:32 UTC by zarend

not ready yet, making a draft for the code diff and to run CI.

2021-03-05 20:35 UTC, atscott requested changes
You have a pretty good overview of the issue in the comment. Please add a similar description to the commit message. The commit messages should contain all the same information about why a change is being made - it shouldn't only be in the PR comment.

2021-03-05 20:35 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/test/type_check_block_spec.ts
> +        interface PrivateInterface{}; export class Dir<T extends PrivateInterface, U extends string> {};
```suggestion
        interface PrivateInterface{}; 
        export class Dir<T extends PrivateInterface, U extends string> {};
```

2021-03-05 20:35 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/test/test_utils.ts
> +export type TestBase = {
This type `TestBase` and the property `code` are somewhat poorly named, especially without documentation. I needed to actually find where code was used to figure out what it did. Also, why not just add the new `code`/`customCode` to the existing type rather than creating a new one and doing `&TestBase`?

2021-03-05 20:35 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> -      if (missingInlines.length > 0) {
Shouldn't we still be keeping track of these? Wouldn't we still want to produce an informational diagnostic to indicate that we don't have the correct types but are instead using `any` in these cases?

2021-03-05 20:35 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/api/api.ts
> +  useInlineTypeConstructors: boolean;
I'm a bit confused with how this interacts with `InliningMode`. If `useInlineTypeConstructors` is `true` and `InliningMode` is `Error`, what do you expect to happen when something requires inlining? If that's not a valid configuration, then shouldn't we just have one way to configure inlining rather than two that can be at odds with each other?

2021-03-06 00:03 UTC, alxhub requested changes

2021-03-06 00:03 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      if (dir.isGeneric) {
The flow of this `if` structure is very unintuitive, and I think it could be made a lot cleaner and more readable by putting the cases in the order of commonality:

```
if (!dir.isGeneric) {
  // TcbDirectiveTypeOp
} else if (useInlineTypeCtors || !requiresInLineTypeCtor) {
  // TcbDirectiveCtorOp
} else {
  // fallback op (name subject to bikeshedding)
}
```

2021-03-06 00:03 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_file.ts
> +  render(options?: {removeComments?: boolean}): string {
Yeah, I think required here would be better.

2021-03-06 00:03 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/test/test_utils.ts
> +export type TestBase = {
Also both this and `TestPipe`/`TestDirective` should arguably be interfaces, not `type`s.

2021-03-06 00:11 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +        useInlineTypeConstructors: false,
This should definitely not be `false`. Inline type constructors are required for how the compiler normally operates.

This should probably be set based on whether the current `TypeCheckingProgramStrategy` supports inline operations (it exposes a `supportsInlineOperations` property to report this).

2021-03-09 16:34 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_file.ts
> +  render(options?: {removeComments?: boolean}): string {
fixed: make this a required param

2021-03-09 16:38 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +        dirRef.node.typeParameters!.map(() => ts.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword));
Good suggestions, I made this an explicit check-and-throw. I like doing a check-and-throw instead of a non-null assertion, so that it doesn't look like a mistake to the reader of the code. In this example, null really is an invalid state as this Op is only intended for generic directives.

2021-03-09 16:38 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/test/test_utils.ts
> +export type TestBase = {
done,  TestPipe/TestDirective are interfaces now, and there is no more `TestBase`

2021-03-09 17:22 UTC, zarend commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +        useInlineTypeConstructors: false,
🤦 , that is correct.

For strict mode, I made it
 `useInlineTypeConstructors: this.typeCheckingProgramStrategy.supportsInlineOperations,`
That's because

For non-strict mode, I set it to false. That's because we want to be as lenient as possible in non-strict mode. When `useInlineTypeConstructors` is `false`, we use any for the generic params of bound generics instead of trying to infer the types. It's better to avoid inlining unless we have to because it's problematic ( perf issues, complications with editing user's files).

2021-03-09 17:24 UTC, zarend commented
@alxhub @atscott , I've addressed the PR comments, and this PR is ready for your eyes again. 

(I still need to update the commit description, will take care of that this morning).

2021-03-09 18:25 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +        useInlineTypeConstructors: this.typeCheckingProgramStrategy.supportsInlineOperations,
This should probably also take into consideration the `InliningMode` - if inlining is disabled, we should honor that even if the type-checking strategy supports it.

2021-03-09 18:27 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +    if (!dirRef.node.typeParameters) {
Explicitly test for `undefined` and don't rely on truthiness.

2021-03-09 18:28 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      if (!dir.isGeneric) {
This construct could benefit from some inline comments, describing the logic behind each case.

2021-03-09 18:30 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      } else if (
I also suggest inverting this condition and switching it with the one below, so the logic proceeds according to most common -> least common.

That is, the cases are:
* Literal type is okay (most likely)
* Requires a type constructor, and we can generate one (less likely)
* Would require a type constructor, but we have to fall back on a literal type with anys due to inlining restrictions (least likely)
 
This helps to make the logic easier to read and reason about.

2021-03-09 22:19 UTC, zarend commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +        useInlineTypeConstructors: this.typeCheckingProgramStrategy.supportsInlineOperations,
Hmm... I think we're mixing up `InliningMode` and `supportsInlineOperations`.

`supportsInlineOperations` it's a parameter of the `TypecheckContextImpl`. It is `false` for the language service, since we cannot edit working users files. It is `true` while compiling for real.

`InliningMode` is an enum that says how the type-checking context handles inlining. 

```
export enum InliningMode {
  /**
   * Use inlining operations when required.
   */
  InlineOps, // <- use this when `supportsInlineOperations` is true.

  /**
   * Produce diagnostics if an operation would require inlining.
   */
  Error, // use this when `supportsInlineOperations` is false.
}
```

The InliningMode is only used only by the type-checking context, and it is set based on the `supportsInlineOperations`. This is handled in `TemplateTypechecker::newContext`.

https://github.com/zarend/angular/blob/master/packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts#L397

Since the source of truth for InliningMode is `supportsInlineOperations`. We only need to check `supportsInlineOperations` here, and we don't need to know about `InliningMode`.

2021-03-09 22:28 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      } else if (
done, I added inline comments, and reordered the branches. It turned out nicely, it looks less complicated after doing this 💯

2021-03-10 17:34 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      protected tcb: Context, protected scope: Scope,
Ah, I do like how the inheritance lets us share a bunch of stuff. Civen that our decision was that the new Op and this existing one serve separate purposes, it feels a bit odd that the new Op would extend the existing one. Would it be better to have an abstract base class?

```
abstract class X extends TcbOp {
...
 abstract execute(): ts.Identifier;
...
}

class TcbDirectiveTypeOp extends X {
  execute(): ts.Identifier {
    const type = this.tcb.env.referenceType(this.dir.ref);
    return this.createVariableDeclaration(type);
  }
}

class TcbGenericDirectiveTypeWithAnyParamsOp extends X {
  execute() {...}
}
```
@alxhub

2021-03-10 22:28 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      protected tcb: Context, protected scope: Scope,
I don't think an abstract base class is necessary, but I don't feel strongly about it :).

Extending `TcbDirectiveTypeOp` seems natural to me, because the new op does the exact same thing, except it also "fills in" the generic parameters.

In other works. `TcbDirectiveTypeOp` is the basic version which makes a tcb that looks like this.
`var dir1: i0.Dir = (null!); //psuedo code, actual tcb may vary`

and `TcbGenericDirectiveTypeWithAnyParamsOp`, builds on the previous op by filling in the `<>`
`var dir1: i0.Dir<any,any> = (null!); //psuedo code, actual tcb may vary`

Potentially, we could extend `TcbDirectiveTypeOp` again to make another op which tries to use actual types instead of anys. (not a real use case right now, but the point is that `TcbDirectiveTypeOp` is extendable.
`var dir1: i0.Dir<string,number> = (null!); //psuedo code, actual tcb may vary`

2021-03-10 22:31 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      protected tcb: Context, protected scope: Scope,
Would it help if I wrote a comment for `TcbDirectiveTypeOp` that says it's extensible? That makes it's not ambiguous which op's are intended to be extended or not.

2021-03-11 18:52 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      protected tcb: Context, protected scope: Scope,
I don't think either option is right, personally. Extension implies substitutability, which is not true in this case because `TcbGenericDirectiveTypeWithAnyParamsOp` is semantically different than `TcbDirectiveTypeOp` and cannot be used in its place. Instead, we should put the logic either in an abstract base class or in a shared utility function.

2021-03-11 18:59 UTC, alxhub requested changes

2021-03-11 18:59 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> -    let missingInlines: ClassDeclaration[] = [];
We should, however, throw an exception here if the `InliningMode` is `Error`, but `config.useInlineTypeConstructors` is `true`.

2021-03-11 19:28 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      protected tcb: Context, protected scope: Scope,
okay, I changed it to use a helper function.

2021-03-11 22:18 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +function createVariableDeclarationOfType(
This name is fairly generic for its purpose, which specifically handles a variable for a directive type on a `TmplAstTemplate|TmplAstElement` node.

Additionally, I think a lot more of the logic could be shared.

Think about it this way: both operations do the same thing from a structural standpoint. The only difference is whether type parameters are allowed or not.

I think we should use an abstract base class `TcbOp`, which performs the logic:

* import the directive raw type
* if the directive has generic parameters, build a type that has `any`s
* tag it appropriately
* return the id

Then, both `TcbDirectiveTypeOp` and `TcbGenericDirectiveTypeWithAnyParamsOp` can extend from the base version, and specialize the `execute()` operation:

* `TcbDirectiveTypeOp` will assert that the directive class is _not_ generic, before delegating to `super.execute()`.
* `TcbGenericDirectiveTypeWithAnyParamsOp` will assert that the directive class _is_ generic.

2021-03-16 15:18 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      protected tcb: Context, protected scope: Scope,
after further discussion over github and offline, implemented this using an abstract class – see comments below

2021-03-16 15:19 UTC, zarend commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +function createVariableDeclarationOfType(
done ✔️

2021-03-16 15:46 UTC, zarend commented on packages/language-service/ivy/test/quick_info_spec.ts
> +    it('should get quick info for the generic input of a directive that normally requires inlining',
Note to reviewers: this tests the original bug that we're trying to fix :). Language service crashes when encountering directives that would normally be inlined. This makes some IDE features not work such as quick info, and causes some of the developer's code not to be type checked.

2021-03-16 15:49 UTC, zarend commented
@atscott @alxhub the PR comments have been fixed, and this is ready for your eyes again.

Since you last reviewed, I've used an abstract class to implement TcbOb's, updated the comments for `useInlineTypeConstructors`, made it an error to set `useInlineTypeConstructors` to `true` when the inlining mode is `InliningMode.Error`, and made a few other misc fixes.

2021-03-16 16:54 UTC, atscott approved these changes
👌  I like how clean the abstract base class ends up being. Good work!

2021-03-16 21:16 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +    if ((inlining === InliningMode.Error) && config.useInlineTypeConstructors) {
Not: no need for the extra paren wrapping here.

2021-03-16 21:18 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
> +    if (this.inlining === InliningMode.Error && tcbRequiresInline) {
Having `tcbRequiresInline` here means that the inner `if` on line 273 is redundant.

2021-03-16 21:18 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +/*
?

2021-03-16 21:19 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +abstract class TcbDirectiveTypeBaseOp extends TcbOp {
```suggestion
abstract class TcbDirectiveTypeOpBase extends TcbOp {
```

2021-03-16 21:20 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +  private createVariableDeclarationOfType(type: ts.TypeNode): ts.Identifier {
There's only one caller here - shouldn't we just inline this?

2021-03-16 21:21 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +    if (this.dir.isGeneric === true) {
```suggestion
    if (this.dir.isGeneric) {
```

2021-03-16 21:21 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +    if (dirRef.node.typeParameters === undefined) {
Should we check `!this.dir.isGeneric` too?

2021-03-16 21:23 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/test/type_check_block_spec.ts
> +       const config: Partial<TypeCheckingConfig> = {useInlineTypeConstructors: false};
Probably don't need to have this declared as a separate constant.

2021-03-16 21:24 UTC, alxhub approved these changes

2021-03-16 21:27 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/test/test_utils.ts
> +    defaultConfig.useInlineTypeConstructors = overrides.inlining;
This is overwriting a constant. We should set this on `fullConfig` below instead.

2021-03-18 16:53 UTC, closed without merging

2021-03-18 16:54 UTC, mhevery commented
@zarend This had a merge conflict on patch branch. Please create a new PR and label accordingly

2021-03-18 19:21 UTC, zarend commented
> @zarend This had a merge conflict on patch branch. Please create a new PR and label accordingly

Thanks, here's a PR to merge it into patch branch.
#41268