docs: add contributors guide to aio
angular/angular pull request #41061
Opened 2021-03-03 00:07 UTC by aikidave

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-03-03 00:17 UTC, mary-poppins commented
You can preview 6be5190 at https://pr41061-6be5190.ngbuilds.io/.

2021-03-08 19:18 UTC, mary-poppins commented
You can preview dfd6e92 at https://pr41061-dfd6e92.ngbuilds.io/.

2021-03-08 20:04 UTC, kapunahelewong reviewed
Looks great! Thank you!

2021-03-08 20:32 UTC, kapunahelewong reviewed
I just noticed a small thing after submitting my earlier review!

2021-03-08 20:32 UTC, kapunahelewong commented on aio/content/guide/contributors-guide-overview.md
> +      <p class="card-footer">Reviewing content</p>
Is there a way to vary the content in the card footer so it isn't a duplicate of the `<section>` content? Maybe instead somehow expand on what the card title says? Maybe this one could be something like this:

```suggestion
      <p class="card-footer">Keep things current</p>
```

Or some other phrase that's short, given the space issue.

2021-03-08 20:32 UTC, kapunahelewong commented on aio/content/guide/contributors-guide-overview.md
> +      <p class="card-footer">Updating search keywords</p>
```suggestion
      <p class="card-footer">Improve documentation search</p>
```

2021-03-08 20:32 UTC, kapunahelewong commented on aio/content/guide/contributors-guide-overview.md
> +      <p class="card-footer">Updating content through GitHub</p>
```suggestion
      <p class="card-footer">Contribute to Angular in your browser</p>
```

2021-03-08 20:32 UTC, kapunahelewong commented on aio/content/guide/contributors-guide-overview.md
> +      <p class="card-footer">Documentation style guide</p>
```suggestion
      <p class="card-footer">Get to know the writing style</p>
```

Might be a bit long, but something along these lines might be helpful.

2021-03-08 23:41 UTC, aikidave commented on aio/content/guide/updating-search-keywords.md
> +</code-example>
We can't use {@searchKeywords} in the text, because the system thinks it's an actual tag. I couldn't figure out a way to fix that, so I did this:

{`@searchKeywords`}

2021-03-08 23:48 UTC, mary-poppins commented
You can preview 4f6b7e7 at https://pr41061-4f6b7e7.ngbuilds.io/.

2021-03-09 22:23 UTC, kapunahelewong approved these changes
LGTM! Thank you!

Reviewed-for: global-docs-approvers

2021-03-09 22:38 UTC, josephperrott requested changes

2021-03-09 22:38 UTC, josephperrott commented on aio/content/guide/contributors-guide-overview.md
> +  <a href="" class="docs-card"
An href of `""` it seems navigates back to `/`, so it ends up back at the landing page of angular.io

It looks like paths were created for these cards, but might not be linked up yet

2021-03-09 22:38 UTC, josephperrott commented on aio/content/guide/reviewing-content.md
> +You can review a topic using either the GitHub user interface or the command line on your local machine. You can also review any topic that you like. Previous experience in the subject of the topic i
Would it be more accurate to say you can review the topic in the Github UI or "in an editor on your local machine"

2021-03-09 22:38 UTC, josephperrott commented on aio/content/guide/updating-content-github-ui.md
> +1. At the bottom of the screen, update the Commit Changes box with a description of the change. Use the format `docs: <short-description-of-change>`, where `<short-description-of-change>` briefly des
```suggestion
1. At the bottom of the screen, update the Commit Changes box with a description of the change. Use the format `docs: <short-description-of-change>`, where `<short-description-of-change>` briefly describes your change. Keep the description under 100 characters. For example:
```

2021-03-09 23:16 UTC, mary-poppins commented
You can preview 5a73e63 at https://pr41061-5a73e63.ngbuilds.io/.

2021-03-12 02:13 UTC, mary-poppins commented
You can preview 2d8cc6b at https://pr41061-2d8cc6b.ngbuilds.io/.

2021-03-12 16:36 UTC, josephperrott approved these changes
LGTM

Just one spacing nit.

2021-03-12 16:36 UTC, josephperrott commented on aio/content/guide/contributors-guide-overview.md
> +    <a href="guide/docs-style-guide" class="docs-card"
```suggestion
  <a href="guide/docs-style-guide" class="docs-card"
```

2021-03-12 16:44 UTC, mary-poppins commented
You can preview 2cd17a4 at https://pr41061-2cd17a4.ngbuilds.io/.

2021-03-12 17:03 UTC, mary-poppins commented
You can preview 628fa64 at https://pr41061-628fa64.ngbuilds.io/.

2021-03-12 21:01 UTC, mgechev approved these changes

2021-03-12 22:08 UTC, yallen011 commented
I can help review/test this PR @aikidave

2021-03-15 18:38 UTC, mary-poppins commented
You can preview e2670c4 at https://pr41061-e2670c4.ngbuilds.io/.

2021-03-15 19:16 UTC, closed without merging