fix(language-service): no completion for two-way binding `ngModel`
angular/angular pull request #41081
Opened 2021-03-05 06:06 UTC by ivanwonder

The attribute `ngModel` is in two directive classes `NgControlStatus` and `NgModel`.
After the ivy LS resolves the first class `NgControlStatus` which has no input and
output and save it in the table, the second directive class will be skipped. So no
completion for `[(ngModel)]`. In this commit the kind of attribute can be reset from
`DirectiveAttribute` into `DirectiveInput` or `DirectiveOutput`, but not vice versa.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-04-20 00:00 UTC, atscott requested changes

2021-04-20 00:00 UTC, atscott commented on packages/language-service/ivy/attribute_completions.ts
> +            const completionItem = table.get(attrName);
Can't comment on unchanged lines but this same issue exists for directives that have already matched:

```
@Directive({
  selector: 'div',
  inputs: ['something'],
})
export class DirA {}

@Directive({
  selector: 'div',
  outputs: ['something']
})
export class DirB {}

<div a some|></div>
```

The above would only produce the `input` completion for `DirA`.

2021-04-20 09:44 UTC, ivanwonder commented on packages/language-service/ivy/attribute_completions.ts
> +            const completionItem = table.get(attrName);
Oh, I see. The map key can be used to distinguish between the `input` and `output`, if the `table` set the value like this. 
```js
table.set('(somgthing)', {});
table.set('[something]', {});
```

2022-03-29 22:41 UTC, dylhunn commented
As this PR seems to be abandoned, I will close it. Feel free to open a new PR if you want to merge this change in the future.

2022-03-29 22:41 UTC, closed without merging

2022-03-31 17:27 UTC, atscott commented
@ivanwonder just for more context, this is quite an edge-case and we couldn’t come up with a good, clean solution for every scenario. I think it’s okay to not address this problem, at least for now. I didn’t really see any reports for developers encountering this and requesting a fix.