docs: fix broken tables in browser-support.md
angular/angular pull request #41122
Opened 2021-03-08 21:28 UTC by leandrodiniz

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-03-12 16:06 UTC, mary-poppins commented
You can preview 143b17a at https://pr41122-143b17a.ngbuilds.io/.

2021-03-12 16:09 UTC, jelbourn commented
@leandrodiniz it's not clear from your PR/commit description what's actually broken here; it looks like the changes are mostly formatting. Additionally, this change seems to have broken the link rendering in the "Optional browser features to polyfill" table (you can see in the preview link posted above)

2021-03-17 01:54 UTC, mary-poppins commented
You can preview 2e89f2a at https://pr41122-2e89f2a.ngbuilds.io/.

2021-03-17 01:54 UTC, leandrodiniz commented
@jelbourn actually it's mostly formatting changes but that impacts the way the tables are displayed on GitHub. You can check the differences here:

**master:**
https://github.com/angular/angular/blob/master/aio/content/guide/browser-support.md

**my branch:**
https://github.com/angular/angular/blob/2e89f2ac0f78651653824efd8cf4f36a74d4c274/aio/content/guide/browser-support.md

and I also fixed the link rendering in the 'polyfills' table that was broken.

2021-03-17 02:10 UTC, mary-poppins commented
You can preview be74fa2 at https://pr41122-be74fa2.ngbuilds.io/.

2021-03-17 23:46 UTC, jelbourn commented
Ah, I see. Can you squash your changes into a single commit with a message that clarifies that this addresses rendering _on GitHub_. Something like

```
docs: format browser-support tables for GitHub markdown

Format the HTML used in browser-support.md such that the tables
render correctly under GitHub markdown.
```

2021-03-18 01:31 UTC, leandrodiniz commented
Done. I squashed my changes into a single commit with a clearer message.

2021-03-18 13:19 UTC, gkalpak requested changes
Thx, @leandrodiniz! 

OOC, why were you trying to view the file on GitHub? (Just making sure there are no links we need to update, because this file is not intended to be viewed in the source code directly.)

2021-03-18 13:19 UTC, gkalpak commented on aio/content/guide/browser-support.md
>   <tr>
While you're at it, you could fix the indentation here too 🙏 

```suggestion
  <tr>
```

2021-03-18 13:19 UTC, gkalpak commented on aio/content/guide/browser-support.md
> +    <a href="guide/browser-support#core-es6" class="code-anchor">ES2015</a>
```suggestion
      <a href="guide/browser-support#core-es6">ES2015</a>
```

2021-03-18 13:19 UTC, gkalpak commented on aio/content/guide/browser-support.md
> +      <a href="api/animations/AnimationBuilder" class="code-anchor">AnimationBuilder</a>
```suggestion
      <a href="api/animations/AnimationBuilder">AnimationBuilder</a>
```

2021-03-18 13:19 UTC, gkalpak commented on aio/content/guide/browser-support.md
> +      <a href="guide/browser-support#web-animations" class="code-anchor">Web Animations</a>
```suggestion
      <a href="guide/browser-support#web-animations">Web Animations</a>
```

2021-03-18 13:19 UTC, gkalpak commented on aio/content/guide/browser-support.md
> +      <a href="api/common/NgClass" class="code-anchor">NgClass</a> on SVG elements
```suggestion
      <a href="api/common/NgClass">NgClass</a> on SVG elements
```

2021-03-18 13:19 UTC, gkalpak commented on aio/content/guide/browser-support.md
> +      <a href="guide/browser-support#classlist" class="code-anchor">classList</a>
```suggestion
      <a href="guide/browser-support#classlist">classList</a>
```

2021-03-18 13:19 UTC, gkalpak commented on aio/content/guide/browser-support.md
> +      <a href="guide/router" class="code-anchor">Router</a> when using <a href="guide/router#location-strategy" class="code-anchor">hash-based routing</a>
```suggestion
      <a href="guide/router">Router</a> when using <a href="guide/router#location-strategy">hash-based routing</a>
```

2021-03-18 13:19 UTC, gkalpak commented on aio/content/guide/browser-support.md
> +      <a href="guide/browser-support#core-es7-array" class="code-anchor">ES7/array</a>
```suggestion
      <a href="guide/browser-support#core-es7-array">ES7/array</a>
```

2021-03-23 11:18 UTC, gkalpak approved these changes
LGTM :+1: Thx, @leandrodiniz!
(FYI, I have rebased the PR on master to resolve a conflict and allow CI to run.)

OOC, why were you trying to view the file on GitHub? (Just making sure there are no links we need to update, because this file is not intended to be viewed in the source code directly.)

2021-03-23 11:28 UTC, mary-poppins commented
You can preview e489f66 at https://pr41122-e489f66.ngbuilds.io/.

2021-03-23 17:37 UTC, jelbourn approved these changes
LGTM

Reviewed-for: docs-packaging-and-releasing

2021-03-23 20:08 UTC, closed without merging