feat(ngcc): support `__spreadArray` helper as used by TypeScript 4.2
angular/angular pull request #41201
Opened 2021-03-13 23:37 UTC by JoostK

In TypeScript 4.2 the `__spread` and `__spreadArrays` helpers were both
replaced by the new helper function `__spreadArray` in
microsoft/TypeScript#41523. These helpers may be used in downleveled
JavaScript bundles that ngcc has to process, so ngcc has the ability to
statically detect these helpers and provide evaluation logic for them.
Because Angular is adopting support for TypeScript 4.2 it becomes
possible for libraries to be compiled by TypeScript 4.2 and thus ngcc
has to add support for the `__spreadArray` helper. The deprecated
`__spread` and `__spreadArrays` helpers are not affected by this change.

Closes #40394

2021-03-14 03:29 UTC, petebacondarwin approved these changes
Ahead of the game @JoostK

2021-03-14 03:30 UTC, petebacondarwin requested changes

2021-03-14 03:30 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/ts_helpers.ts
> +    return from.concat(to);
Oops, I spoke too soon. This should be

```suggestion
    return to.concat(from);
```

2021-03-14 07:57 UTC, crisbeto reviewed
I don't have a lot of context here, but do we also have to account for the `__read` helper? It seems to be used together with `__spreadArray`. See https://github.com/angular/angular/pull/41158/files#diff-e5db61a4fea6171227d1b25300c43bc2f33613fefb1d98bb37ad746264c3661bR3006

2021-03-14 11:26 UTC, JoostK commented
> I don't have a lot of context here, but do we also have to account for the `__read` helper? It seems to be used together with `__spreadArray`. See https://github.com/angular/angular/pull/41158/files#diff-e5db61a4fea6171227d1b25300c43bc2f33613fefb1d98bb37ad746264c3661bR3006

Very good point, yes we do! The `__read` helper is emitted if `downlevelIteration` is set, which is quite likely for libraries (ng-packagr has that on by default). I'll add another commit to add support for `__read`

2021-03-14 11:28 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/ts_helpers.ts
> +    return from.concat(to);
That is entirely correct! I didn't notice as the evaluator spec are part of `ngtsc/partial_evaluator` and I only ran the `ngcc` test targets.

2021-03-16 08:27 UTC, petebacondarwin commented
> but for ngcc's static evaluation support it is sufficient to only deal with arrays as is

Is it not possible for a developer to use an iterator in a spread expression?

2021-03-16 09:00 UTC, petebacondarwin approved these changes
I would like to know why the implementation of `__read` doesn't require iterator support. But that could be added on as a subsequent PR if it is found to be necessary.

2021-03-16 09:26 UTC, JoostK commented
> > but for ngcc's static evaluation support it is sufficient to only deal with arrays as is
> 
> Is it not possible for a developer to use an iterator in a spread expression?

AFAIK this would not be statically evaluable, i.e. instantiating a `Set` needs the `new` operator which is not supported, and generator functions nor the iterator protocol is implemented by ngtsc's evaluator.

2021-03-16 16:19 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:363198615:BASE:363198630:1615911529715:d3c1b3fe).

2021-03-16 18:06 UTC, closed without merging