Update app.component.css
angular/angular pull request #41222
Opened 2021-03-15 19:29 UTC by BendikSkarpnes

added missing semicolon

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-03-16 19:50 UTC, gkalpak requested changes
Thx, @BendikSkarpnes :+1:

Can you please update the commit message to more closely follow our [commit message guidelines](https://github.com/angular/angular/blob/1d9e56eba06958e37ef8062ae7b65afa85f90632/CONTRIBUTING.md#commit). For example:

> docs: fix styling issues in example CSS

2021-04-17 00:19 UTC, AndrewKushnir approved these changes

2021-04-17 00:20 UTC, AndrewKushnir commented
@gkalpak I've rebased this PR and updated commit message as you proposed. Could you please have a quick look again? Thank you.

2021-04-17 14:47 UTC, gkalpak approved these changes

2021-04-19 21:15 UTC, closed without merging