docs: replace deprecated karma-coverage-istanbul-reporter (#1)
angular/angular pull request #41246
Opened 2021-03-17 17:15 UTC by manueledones

'karma-coverage-istanbul-reporter' usage has been deprecated since version 11.
Please install 'karma-coverage' and update 'karma.conf.js.' For more info, see https://github.com/karma-runner/karma-coverage/blob/master/README.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-03-17 18:22 UTC, AndrewKushnir commented
@kyliau could you please help with the review of this change? Thank you.

2021-03-17 18:29 UTC, kyliau commented on aio/content/guide/testing-code-coverage.md
> +coverageReporter: {
Please fix indentation

2021-03-17 18:29 UTC, kyliau approved these changes

2021-03-17 18:38 UTC, AndrewKushnir approved these changes
LGTM too once comments from Keen are addressed.

@manueledones thanks for improving Angular docs 👍

2021-03-17 18:39 UTC, gkalpak requested changes
Good catch! Thx, @manueledones :+1:

I left a couple fo comments/suggestions. As you make the changes, could you also remove the ` (#1)` suffix from the commit message header? :pray:

2021-03-17 18:39 UTC, gkalpak commented on aio/content/guide/testing-code-coverage.md
> +You can find the configuration [here](https://github.com/karma-runner/karma-coverage/blob/master/docs/configuration.md).
I would put this sentence below the code snippet and change it to something like:

```suggestion
You can find more info about the different coverage configuration options [here](https://github.com/karma-runner/karma-coverage/blob/master/docs/configuration.md).
```

2021-03-17 18:39 UTC, gkalpak commented on aio/content/guide/testing-code-coverage.md
>  ```
```suggestion
```js
```

2021-03-17 18:39 UTC, gkalpak commented on aio/content/guide/testing-code-coverage.md
> +      dir: require('path').join(__dirname, './coverage/...'),
I think we should either remove the existing properties (and only show the newly added `check` property) or make it more clear that the path should include the project's name:

```suggestion
      dir: require('path').join(__dirname, './coverage/<project-name>'),
```

...or...

```suggestion
      dir: require('path').join(__dirname, './coverage/angular.io-example'),
```

(`angular.io-example` is the project name used in the associated StackBlitz live example.)

2021-03-17 18:39 UTC, gkalpak commented on aio/content/guide/testing-code-coverage.md
> +    }
This snippet is not indented correctly.

2021-03-18 12:52 UTC, mary-poppins commented
You can preview fc7ba65 at https://pr41246-fc7ba65.ngbuilds.io/.
You can preview 765e3a3 at https://pr41246-765e3a3.ngbuilds.io/.
You can preview b78a4b5 at https://pr41246-b78a4b5.ngbuilds.io/.

2021-03-18 12:53 UTC, gkalpak approved these changes

2021-03-18 17:02 UTC, closed without merging