docs: improve accessibility of reactive-forms example
angular/angular pull request #41252
Opened 2021-03-17 20:58 UTC by kapunahelewong

Fixes contrast issues.
Makes labels explicitly reference inputs.
Adds padding to labels.
Changes label to explicitly state intent.
Adds explanatory text about disabled button.
Adds `aria-disabled=true` to  disabled button.
Changes markup to make it more semantic.
Updates CSS.

2021-03-17 21:08 UTC, mary-poppins commented
You can preview 8390b90 at https://pr41252-8390b90.ngbuilds.io/.

2021-03-18 20:44 UTC, mary-poppins commented
You can preview 5efff7a at https://pr41252-5efff7a.ngbuilds.io/.

2021-03-26 19:47 UTC, mary-poppins commented
You can preview 0c1d835 at https://pr41252-0c1d835.ngbuilds.io/.

2021-03-29 23:26 UTC, AndrewKushnir approved these changes

2021-03-29 23:45 UTC, AndrewKushnir reviewed
@kapunahelewong thanks for the PR 👍 

I've originally approved it, but I'd like to ask @jelbourn to have a quick look as well.

It looks like you've changed patterns like this one:

```
<label>
  Name:
  <input type="text" [formControl]="name">
</label>
```
to
```
<label for="name">Name: </label>
<input id="name" type="text" [formControl]="name">
```

If I understand correctly, there is no difference from a11y perspective and the first one (what we currently have) is easier to read.

2021-03-29 23:45 UTC, AndrewKushnir commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.1.html
> +  <input id="first-name" type="text" formControlName="firstName">
It looks like the previous version and the new one are equivalent from a11y perspective and I find the current code easier to read (less attributes, the relation between the `<label>` and `<input>` is clear).

Adding @jelbourn to have a look at this change too.

2021-04-01 14:54 UTC, kapunahelewong commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.1.html
> +  <input id="first-name" type="text" formControlName="firstName">
For context, the choice for making them explicit (rather than wrapped/implicit) is because explicit is better supported by assistive technology. 
Links that encouraged me in this direction:

[Accessibility Support's "Test: Implicit labels"](https://a11ysupport.io/tests/html_label_element_implicit)
[W3's Labeling controls](https://www.w3.org/WAI/tutorials/forms/labels/)

2021-04-03 11:12 UTC, gkalpak requested changes
Thx, @kapunahelewong! 

(BTW, I would prefer using PNG images everywhere instead of mixing GIFs and PNGs. OOC, what are the size differences between GIF and PNG?)

2021-04-03 11:12 UTC, gkalpak commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.html
> +  <button type="submit" aria-disabled=true [disabled]="!profileForm.valid">Submit</button>
Does `aria-disabled` make a difference here? Isn't setting the disabled property (which automatically sets the attribute as well) enough?

2021-04-07 20:05 UTC, jelbourn commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.html
> +  <button type="submit" aria-disabled=true [disabled]="!profileForm.valid">Submit</button>
+1, the native disabled attribute does the same job as `aria-disabled` on a button

2021-04-15 21:15 UTC, aikidave approved these changes
No issues on my end that I can see.

Reviewed-for: global-docs-approvers

2021-04-27 18:37 UTC, kapunahelewong commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.1.html
> +      <input id="alias" type="text" [formControlName]="i">
Thanks, @gkalpak! I've made the changes but need to figure the point out about dynamic IDs. 

@jelbourn, would you know how accessible dynamic IDs are? I searched and found these articles, but am still uncertain:

[https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions)

[https://www.levelaccess.com/lesser-known-details-that-seriously-impact-the-usage-of-dynamically-generated-aria-behaviors/](https://www.levelaccess.com/lesser-known-details-that-seriously-impact-the-usage-of-dynamically-generated-aria-behaviors/)

Do these fall into the aria category of live regions? [https://webaim.org/techniques/aria/#dynamic](https://webaim.org/techniques/aria/#dynamic)

2021-04-27 21:08 UTC, mary-poppins commented
You can preview 27b6f28 at https://pr41252-27b6f28.ngbuilds.io/.

2021-04-28 12:41 UTC, kapunahelewong commented
> (BTW, I would prefer using PNG images everywhere instead of mixing GIFs and PNGs. OOC, what are the size differences between GIF and PNG?)

`name-editor-2.gif `is 13k vs 19k as a png
`profile-editor-1.gif `is 9k vs 16k as a png

Would you like me to convert them to png instead?

2021-04-28 12:52 UTC, gkalpak commented
Argh... Let's keep the GIFs :smiley:
Thx for getting the numbers, @kapunahelewong!

2021-04-30 23:22 UTC, jelbourn commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.1.html
> +      <input id="alias" type="text" [formControlName]="i">
Dynamic IDs are fine (and necessary to make any complex interaction work). Live regions are referring to use of `aria-live`, `role="status`", and `role="alert"` that announce when some text on the page changes.

2021-05-03 14:06 UTC, kapunahelewong commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.1.html
> +      <input id="alias" type="text" [formControlName]="i">
Thank you, @jelbourn!

2021-05-04 13:12 UTC, gkalpak approved these changes
A couple of minor comments. Otherwise lgtm 🚀

2021-05-04 13:12 UTC, gkalpak commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.html
> +  <p>Complete the form to enable button.</p>
Won't this be confusing once the form is completed and the button enabled?
If we are to show such a message, I think we should only show it when needed imo (i.e. only when the button is disabled).

2021-05-05 21:01 UTC, kapunahelewong commented on aio/content/examples/reactive-forms/src/app/profile-editor/profile-editor.component.html
> +  <p>Complete the form to enable button.</p>
It isn't confusing because the app is minimal. The paragraph is there for those who can't rely on visual cues. IMO, adding logic to this `<p>` tag would clutter the example for a new developer. However, if we'd like to add such logic, then we should also cover it in the doc. In that case, it might be better to create a follow up PR. cc @aikidave

2021-05-05 23:42 UTC, PingPongSet commented
Will this example be hosted under https://angular.io/docs? If so, which section and when?

2021-05-06 13:03 UTC, kapunahelewong commented
> Will this example be hosted under https://angular.io/docs? If so, which section and when?

Hi @PingPongSet! There is currently a version out there that goes with the [reactive forms documentation](https://angular.io/guide/reactive-forms). There are two links at the top of the reactive forms doc that you can use to get to the example as it currently stands. The` live example `link takes you to a [stackblitz example](https://stackblitz.com/angular/nqylylrbmag?file=src%2Fapp%2Fapp.component.ts). The `download link` downloads the example app for you so you can run it locally. If you go to the [Reactive Forms doc](https://angular.io/guide/reactive-forms), these links are just after the first paragraph in a call out. Here's a screenshot with them circled in case it helps:

<img width="500" alt="Reactive forms doc with links circled" src="https://user-images.githubusercontent.com/4116963/117301568-c1f6fe00-ae48-11eb-860a-6ddfc5b3b2c4.png">

This PR doesn't change the functionality of the application. Instead it works to improve areas where it could be more accessible by making it more screenreader friendly, enlarging touch targets, and improving contrast, so if it's the functionality you're looking for, you'll find it in that reactive forms example app even before this PR is merged. Once this PR is merged, all these changes will be reflected in the example app on stackblitz and the downloaded example. Let me know if you have any questions.

2021-05-06 14:36 UTC, mary-poppins commented
You can preview 8de816b at https://pr41252-8de816b.ngbuilds.io/.

2021-05-07 18:28 UTC, PingPongSet commented
> 
> 
> > Will this example be hosted under https://angular.io/docs? If so, which section and when?
> 
> Hi @PingPongSet! There is currently a version out there that goes with the [reactive forms documentation](https://angular.io/guide/reactive-forms). There are two links at the top of the reactive forms doc that you can use to get to the example as it currently stands. The`live example`link takes you to a [stackblitz example](https://stackblitz.com/angular/nqylylrbmag?file=src%2Fapp%2Fapp.component.ts). The `download link` downloads the example app for you so you can run it locally. If you go to the [Reactive Forms doc](https://angular.io/guide/reactive-forms), these links are just after the first paragraph in a call out. Here's a screenshot with them circled in case it helps:
> 
> <img alt="Reactive forms doc with links circled" width="500" src="https://user-images.githubusercontent.com/4116963/117301568-c1f6fe00-ae48-11eb-860a-6ddfc5b3b2c4.png">
> 
> This PR doesn't change the functionality of the application. Instead, it works to improve areas where it could be more accessible by making it more screenreader friendly, enlarging touch targets, and improving contrast, so if it's the functionality you're looking for, you'll find it in that reactive forms example app even before this PR is merged. Once this PR is merged, all these changes will be reflected in the example app on stackblitz and the downloaded example. Let me know if you have any questions.
> 
> Edit: In terms of timing, I believe it'll be merged after v12 as the PRs not directly related to v12 have to wait a bit. cc @aikidave in case he knows more about the timeline.

@kapunahelewong 
Thank you. Its very helpful.

I wonder if there is a way to know if a page under https://angular.io/docs has been updated. Because I was told there is no Last updated date on each page. That means I don't know when a page has been updated. 
Sorry for the question, it is not related to this PR. I raised the question in this github before.
The changes in the PR look good anyway.

2021-05-07 18:35 UTC, petebacondarwin commented
> I wonder if there is a way to know if a page under https://angular.io/docs has been updated. Because I was told there is no Last updated date on each page. That means I don't know when a page has been updated.
> Sorry for the question, it is not related to this PR. I raised the question in this github before.

One way you can find out the history of a page is to click on the "edit this page" button (looks like a pencil), which will take you to github. You can then click the "Cancel Changes" button followed by the "History" link.

2021-05-07 18:40 UTC, PingPongSet commented
> 
> 
> > I wonder if there is a way to know if a page under https://angular.io/docs has been updated. Because I was told there is no Last updated date on each page. That means I don't know when a page has been updated.
> > Sorry for the question, it is not related to this PR. I raised the question in this github before.
> 
> One way you can find out the history of a page is to click on the "edit this page" button (looks like a pencil), which will take you to github. You can then click the "Cancel Changes" button followed by the "History" link.

@petebacondarwin 
Great, thanks for the prompt advice!

2021-06-08 19:01 UTC, AndrewKushnir commented
FYI I've rebased this PR and resolved merge conflicts. This PR should be ready for merge once CI run is completed.

2021-06-08 19:42 UTC, closed without merging