docs(docs-infra): review components overview guide
angular/angular pull request #41263
Opened 2021-03-18 16:23 UTC by yallen011

* added links to navigate to the create workspace and application and install Angular CLI how-to steps for easy navigation
* added reviewed tag

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-03-18 16:29 UTC, atscott approved these changes
LGTM but not sure what @aikidave has in mind for the reviewed date so I've added him to the review here.

2021-03-18 16:41 UTC, yallen011 commented
Thank you, it wouldn't let me add him myself

2021-03-18 16:50 UTC, petebacondarwin requested changes
Thanks for this review and update. Would you mind tweaking the commit message?

`docs-infra` is used for the underlying angular.io application and the tooling that generates the docs.

In this case I think it would be enough not to provide a target:

```
docs: review components overview guide
```

2021-03-18 17:03 UTC, gkalpak requested changes
Drive-by review 🚗

2021-03-18 17:03 UTC, gkalpak commented on aio/content/guide/component-overview.md
> +1. [Install the Angular CLI.](https://angular.io/guide/setup-local#install-the-angular-cli)
```suggestion
1. [Install the Angular CLI.](guide/setup-local#install-the-angular-cli)
```

2021-03-18 17:03 UTC, gkalpak commented on aio/content/guide/component-overview.md
> +1. [Create an Angular workspace](https://angular.io/guide/setup-local#create-a-workspace-and-initial-application) with initial application.
```suggestion
1. [Create an Angular workspace](guide/setup-local#create-a-workspace-and-initial-application) with initial application.
```

2021-03-18 17:50 UTC, aikidave approved these changes
Thanks for this! LGTM!

Reviewed-for: global-docs-approvers

2021-03-18 17:57 UTC, petebacondarwin approved these changes
Looking good, we just need to sort out the commit messages. I guess you are making these changes via the Github UI? If not and you are working in a local git repository, then could you rebase and squash all the commits, into one that uses the proposed commit title?

If not then one of us could probably fix it up for you.

2021-03-18 18:33 UTC, gkalpak approved these changes

2021-03-28 05:48 UTC, yallen011 commented
fixed squashed commits and fixed commit message

2021-03-28 05:55 UTC, mary-poppins commented
You can preview 29192fd at https://pr41263-29192fd.ngbuilds.io/.

2021-03-29 14:52 UTC, gkalpak approved these changes

2021-03-30 23:44 UTC, closed without merging