doc: specify date format for reviewed tag
angular/angular pull request #41269
Opened 2021-03-18 19:26 UTC by yallen011

specify a date format for the reviewed tag and provided an example.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-03-18 19:28 UTC, yallen011 commented
does the`{@a review-criteria}` part needs to be removed.

2021-03-18 20:13 UTC, mary-poppins commented
You can preview abf99f3 at https://pr41269-abf99f3.ngbuilds.io/.

2021-03-18 20:13 UTC, aikidave commented
> does the`{@a review-criteria}` part needs to be removed.

It does no harm, even if we aren't using the anchor tag.

2021-03-18 20:14 UTC, aikidave approved these changes
Looks good to me. Added the `aio: preview` label so we can see the rendered content.

Reviewed-for: global-docs-approvers

2021-03-18 20:22 UTC, yallen011 commented
@aikidave I think it can be removed because it currently looks incorrect syntax that didn't get parsed and all the headers are linked without it there

2021-03-18 20:26 UTC, gkalpak commented
> does the `{@a review-criteria}` part needs to be removed.

We do use it [here][1], so we should not remove it. The fact that the heading-based auto-generated anchor is the same (and thus the link works even if we remove the `@a` anchor is coincidental and could change in the future. You can find more info on why we prefer `@a` anchors [here][2].

[1]: https://github.com/angular/angular/blame/abf99f300e86d88d09aeff39f7d8c3983253a63d/aio/content/guide/reviewing-content.md#L27
[2]: https://angular.io/guide/docs-style-guide#section-header-anchors

2021-03-18 20:33 UTC, gkalpak requested changes
Good catch! Thx, @yallen011 :+1:

BTW, CI is unhappy, because the commit message does not follow our [commit message guidelines](https://github.com/angular/angular/blob/655507012b7b59c83e27429349ce3ac10608a82d/CONTRIBUTING.md#commit) 😞
You can make CI happy by changing the commit message to something like:

> docs: specify date format for \`@reviewed\` tag
>
> Specify a date format for the \`@reviewed\` tag and provide an example.

2021-03-18 20:33 UTC, gkalpak commented on aio/content/guide/reviewing-content.md
> +
```suggestion
```

2021-03-18 20:45 UTC, mary-poppins commented
You can preview 2c5a2ba at https://pr41269-2c5a2ba.ngbuilds.io/.

2021-03-18 20:49 UTC, gkalpak requested changes

2021-03-18 20:49 UTC, gkalpak commented on aio/content/guide/reviewing-content.md
> -{@a review-criteria}
As mentioned in https://github.com/angular/angular/pull/41269#issuecomment-802267819, we should rather keep this.

2021-03-18 20:55 UTC, yallen011 commented on aio/content/guide/reviewing-content.md
> -{@a review-criteria}
so keep it as `-{@a review-criteria}` or just `{@a review-criteria}`

2021-03-18 20:58 UTC, aikidave commented on aio/content/guide/reviewing-content.md
> -{@a review-criteria}
It should be:

`{@a review-criteria}`

2021-03-18 21:02 UTC, yallen011 commented on aio/content/guide/reviewing-content.md
> -{@a review-criteria}
ok, will change it now

2021-03-18 21:04 UTC, yallen011 commented on aio/content/guide/reviewing-content.md
> -{@a review-criteria}
changed

2021-03-18 21:08 UTC, gkalpak commented on aio/content/guide/reviewing-content.md
> -{@a review-criteria}
Did you forget to push the changes? I am still seeing the old commit 😕

2021-03-18 21:14 UTC, mary-poppins commented
You can preview 870c108 at https://pr41269-870c108.ngbuilds.io/.

2021-03-19 00:07 UTC, yallen011 commented on aio/content/guide/reviewing-content.md
> -{@a review-criteria}
@gkalpak sorry, added it. I thought it got pushed last time but it didn't

2021-03-19 00:12 UTC, mary-poppins commented
You can preview 9892733 at https://pr41269-9892733.ngbuilds.io/.

2021-03-19 14:14 UTC, gkalpak approved these changes

2021-03-19 14:25 UTC, mary-poppins commented
You can preview b758f11 at https://pr41269-b758f11.ngbuilds.io/.

2021-03-19 19:39 UTC, closed without merging