refactor(dev-infra): use conventional-commits-parser for commit parsing
angular/angular pull request #41286
Opened 2021-03-19 19:54 UTC by josephperrott

Use conventional-commits-parser for parsing commits for validation, this is being done
in anticipation of relying on this parser for release note creation.  Unifying how commits
are parsed will provide the most consistency in our tooling.

2021-03-20 17:18 UTC, gkalpak requested changes
Mostly lgtm :+1:
My main concern is removing the squash commits check 🤔

2021-03-20 17:18 UTC, gkalpak commented on dev-infra/commit-message/parse.ts
> +  BREAKING_CHANGE = 'BREAKING_CHANGE',
Shouldn't this be:

```suggestion
  BREAKING_CHANGE = 'BREAKING CHANGE',
```

(Maybe we should have some tests for these note sections :wink:)

2021-03-22 16:47 UTC, josephperrott commented on dev-infra/commit-message/parse.ts
> +  BREAKING_CHANGE = 'BREAKING_CHANGE',
Whoops

2021-03-22 19:08 UTC, devversion approved these changes
LGTM. Just some minor comments

2021-03-22 19:08 UTC, devversion commented on dev-infra/commit-message/parse.ts
> +const headerPattern = /^(?:(?:fixup!|revert!|squash:?)\s)?(\w*)(?:\((?:([^/]+)\/)?(.*)\))?: (.*)$/;
Would it be possible to add a comment explaining that there are several match groups that need to match with the correspondence "keys" below. Maybe the correspondence array could be a constant here too?

2021-03-22 19:08 UTC, devversion commented on dev-infra/commit-message/validate.ts
> +    // All squash and revert commits are considered valid.
Nit: Why add the `squash` here when it's handled below and has a separate comment?

2021-03-22 19:08 UTC, devversion commented on dev-infra/commit-message/validate.ts
> +        (commit.body || '').trim().length < config.minBodyLength) {
Is this needed? I see that above commit.body (where it's returned) already has a fallback?

2021-03-22 19:50 UTC, josephperrott commented on dev-infra/commit-message/validate.ts
> +        (commit.body || '').trim().length < config.minBodyLength) {
Correct, now that we created a wrapper type, we can be sure the `body` property will be a string.

2021-03-23 15:06 UTC, gkalpak requested changes

2021-03-23 15:06 UTC, gkalpak commented on dev-infra/commit-message/parse.ts
> +  BREAKING_CHANGE = 'BREAKING CHANGE',
Actually, it seems that `conventional-commits-parser` supports a [notesPattern][1] option, so we could use it is `parseOptions`:

```ts
const parseOptions: Options = {
  // ...
  noteKeywords: [NoteSections.BREAKING_CHANGE, NoteSections.DEPRECATED],
  notesPattern: keywords => new RegExp(`(${keywords})(?:: ?)(.*)`),
};
```

[1]: https://github.com/conventional-changelog/conventional-changelog/tree/8076d4666c2a3ea728b95bf1e4e78d4c7189b1dc/packages/conventional-commits-parser#notespattern

2021-03-23 15:29 UTC, josephperrott commented on dev-infra/commit-message/parse.spec.ts
> -
They were removed when we no longer had `isSquash`/`isFixup`/`isRevert` properties.  Added back.

2021-03-23 15:30 UTC, josephperrott commented on dev-infra/commit-message/validate.spec.ts
> -    });
I have never seen these tests in my life...

Actually thats not true, I reviewed them a few days ago, but I must have missed properly including them on rebase.

2021-03-23 15:38 UTC, josephperrott commented on dev-infra/commit-message/parse.spec.ts
> +  });
Added.

2021-03-23 15:40 UTC, josephperrott commented on dev-infra/commit-message/parse.ts
> +  const commit = parse(strippedCommitMsg, parseOptions);
Ahhh yes thats true, that should simplify some things.

2021-03-23 15:41 UTC, josephperrott commented on dev-infra/commit-message/parse.ts
> +const headerPattern = /^(?:(?:fixup!|revert!|squash:?)\s)?(\w*)(?:\((?:([^/]+)\/)?(.*)\))?: (.*)$/;
Removed that section as you noted in another comment, we are already stripping it out before the header pattern is processed.

2021-03-23 16:05 UTC, josephperrott commented on dev-infra/commit-message/parse.ts
> +  BREAKING_CHANGE = 'BREAKING CHANGE',
I did a bunch of testing and it seems to fall somewhere in the middle.  Only the footer section is checked, so the `breaking change` found in the body would not get selected, but the second one inside the footer would.

So I think your notes pattern idea is the best way to go, I was under the understanding that the default `notesPattern` was case sensitive, however it appears not to be.

2021-03-23 18:52 UTC, gkalpak approved these changes
One last comment. Otherwise lgtm 🚀

2021-03-23 18:52 UTC, gkalpak commented on dev-infra/commit-message/parse.ts
> +const headerPattern = /^(\w*)(?:\((?:([^/]+)\/)?(.*)\))?: (.*)$/;
This pattern will not work for revert commits. Not a huge deal, since we don't do any further validation on revert commits, but I think we should more gracefully handle them. We chould either update `headerPattern` to match revert commits as well or strip the `revert[:]` prefix from the commit before parsing (similar to what we do for `fixup!`/`squash!`).

Also, this regex could get confused if the subject contains `():`, for example: `foo(bar): baz(): qux`
Therefore, I suggest something like:

```suggestion
const headerPattern = /^(\w+)(?:\((?:([^/]+)\/)?([^)]+)\))?: (.*)$/;
```

(If you update the regex, don't forget to also update the comment above :wink:)

<sub>(The change  from `\w*` to `\w+` is not strictly necessary, but it better conveys the intended format imo :grin:)</sub>

2021-03-23 19:00 UTC, josephperrott commented on dev-infra/commit-message/parse.ts
> +const headerPattern = /^(\w*)(?:\((?:([^/]+)\/)?(.*)\))?: (.*)$/;
Updated.

2021-03-23 20:10 UTC, closed without merging