refactor(compiler-cli): support transforming component style resources
angular/angular pull request #41307
Opened 2021-03-22 00:40 UTC by clydin

This change introduces a new hook on the `ResourceHost` interface named `transformResource`.
Resource transformation allows both external and inline resources to be transformed prior to
compilation by the AOT compiler. This provides support for tooling integrations to enable
features such as preprocessor support for inline styles.
Only style resources are currently supported. However, the infrastructure is in place to add
template support in the future.

2021-03-25 16:48 UTC, petebacondarwin reviewed
One concern I have, which may be unfounded, with this feature is that resource pre-processing can only be done async. This means that compiling the application synchronously would produce a different result to compiling it asynchronously. I am not sure how common this would be a problem... does the CLI "always" run the pre-analyze async run? I think that unit testing via the TestBed would normally be sync?

2021-03-25 16:48 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/src/api.ts
> +  type: 'style'|'template';
Although I see it is needed because of the way that `loadResource()` is called.

2021-03-25 17:00 UTC, clydin commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    let inlineStyles;
yes.  At its usage point below in the last `Promise.all` the type is `Promise<void> | undefined`.  `Promise.all` supports non-Promise types within the pass iterable.

2021-03-26 11:15 UTC, clydin commented on packages/compiler-cli/src/ngtsc/annotations/src/api.ts
> +  canPreprocessInline: boolean;
My concept here was that the consumer could make processing decisions within the `transformResource` call via the context's `type` property.  If only styles would be transformed, the consumer can check (e.g., `type !== 'style'`) and immediately return `null` for non-styles.  This follows the model of the `loadResource` hook which is executed for all resource types (although it currently does not provide contextual info but this is something I'd like to add at some point).

2021-03-26 12:16 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/src/api.ts
> +  canPreprocessInline: boolean;
From what I can see below, if `resourceLoader.canPreprocessInline` is true then we will always run code like `parseFieldArrayValue(component, 'styles', this.evaluator);` whether or not the `resourceLoader` plans to actually do anything with styles.

2021-03-26 13:43 UTC, clydin commented on packages/compiler-cli/src/ngtsc/annotations/src/api.ts
> +  canPreprocessInline: boolean;
When `resourceLoader.canPreprocessInline` is `true`, the inline style extraction and analysis will happen in the asynchronous preanalyze phase and then the stored results will be used in the synchronous analyze phase.  When `false`, the inline styles will only be extracted and analyzed in the synchronous analyze phase.  In both cases the style related code will only be executed once.  This mirrors the existing behavior of the template async/sync handling.

The `ResourceLoader` class and `canPreprocessInline` property are also internal so we could refactor any of this in the future without breaking users.  Only the members of `ResourceHost` (`transformResource` in this case) are available to downstream consumers of the compiler.

2021-03-26 16:28 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/src/api.ts
> +  canPreprocessInline: boolean;
In that case what is the value in `canPreprocessInline`? Why not just always call `transformResource()` and let it return `null` if it doesn't plan to do any work?

2021-03-26 17:31 UTC, clydin commented on packages/compiler-cli/src/ngtsc/annotations/src/api.ts
> +  canPreprocessInline: boolean;
good point.  `canPreprocessInline` was added to mimic the `canPreload`/`preload` behavior but realistically `canPreload` is not really needed either.

2021-03-26 17:33 UTC, clydin commented on packages/compiler-cli/src/ngtsc/annotations/src/api.ts
> +  type: 'style'|'template';
As mentioned, the `loadResource` execution path requires the information to guard the `transformResource` call.  This usage is only internal though and the consumer won't see it until template support is fully added.

2021-03-26 17:37 UTC, clydin commented
The CLI and in turn the Angular Webpack plugin always execute asynchronously.  Integration with the Webpack pipeline requires asynchronous compiler analysis.  The current set of potential transformations are all asynchronous as well so at this point there would be no consumer for a synchronous variant.  However, if such a requirement is later introduced, synchronous support could be added without any breaking API changes.

2021-03-26 17:53 UTC, clydin commented on packages/compiler-cli/src/ngtsc/annotations/src/api.ts
> +  containingFile: string;
I went with `containingFile` since it is used fairly frequently already (~20 times) within `ComponentDecoratorHandler` but if you would prefer I can change it.

2021-03-29 13:50 UTC, clydin commented on packages/compiler-cli/src/ngtsc/annotations/src/api.ts
> +  canPreprocessInline: boolean;
Removed `canPreprocessInline`.

2021-03-29 19:12 UTC, petebacondarwin commented on packages/compiler-cli/src/ngtsc/annotations/src/api.ts
> +  containingFile: string;
I didn't realise it was like that elsewhere.

2021-03-29 19:22 UTC, petebacondarwin approved these changes

2021-03-29 21:25 UTC, alxhub approved these changes

2021-03-29 21:25 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/api.ts
> +  preprocessInline(data: string, context: ResourceLoaderContext): Promise<string>;
Re: the async-only nature of this transformation, I would suggest:

1. Mark this method as optional for an implementer of `ResourceLoader`.

2. Have the compiler throw an assertion if provided with a `ResourceLoader` that defines `preprocessInline` and the preanalyze phase is not executed (that is, analysis is synchronous only).

This way, we safeguard against the surprising result of async and sync compilations being different.

2021-03-29 21:46 UTC, JoostK requested changes
I have some concerns about the preprocessing not being considered when `loadNgStructureAsync` is not used.

Additionally, I'd like to see integration-level tests using `NgtscTestEnvironment`, to actually run this through the whole pipeline.

2021-03-29 21:46 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
>      if (componentStyleUrls === null) {
This is a dead code path, but having it here is now incorrect in addition to being dead.

2021-03-29 21:46 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    let inlineStyles = this.preanalyzeStylesCache.get(node) || null;
Even though we still downlevel to ES5 we have started to adopt `??` in compiler code:

```suggestion
    let inlineStyles = this.preanalyzeStylesCache.get(node) ?? null;
```

2021-03-29 21:46 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
>        const litStyles = parseFieldArrayValue(component, 'styles', this.evaluator);
Not going trough the `ResourceLoader` here means that forgetting to call `loadNgStructureAsync` silently skips all preprocessing, unlike non-inline resources that would error out if `ResourceLoader.load` is unable to synchronously return the resource data. I see two potential designs to align this:

1. Have both `preprocessInline` and `preprocessInlineAsync` (or some other names)
2. Allow `preprocessInline` to return a `string | Promise<string>` and also call it in the sync-path, requiring that no `Promise` is returned. Maybe `ResourceLoaderContext` has to indicate whether it's sync or async; I'm not sure how useful that would be.

2021-03-29 21:46 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/core/api/src/interfaces.ts
> +   * * Resources referenced via a component's `styles` or `styleUrls` properties are of
Was the `* *` here intentional?

2021-03-29 21:46 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/core/api/src/interfaces.ts
> +  readonly resourceFile?: string;
We've generally been avoiding optional properties in the compiler:

```suggestion
  readonly resourceFile: string|null;
```

2021-03-29 21:46 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/core/api/src/interfaces.ts
> +   * cause a diagnostics error or an exception to be thrown.
I doubt this is currently the case, as a missing entry in `preanalyzeStylesCache` currently uses `ResourceLoader.load` which doesn't consider `transformResource` at all.

2021-03-29 21:46 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    if (inlineStyles !== null) {
Oh but actually, the compiler is in the habit of an explicit `has` call before calling `get`:

```suggestion
    let inlineStyles: string|null = null;
    // If inline styles were preprocessed use those
    if (this.preanalyzeStylesCache.has(node)) {
      inlineStyles = this.preanalyzeStylesCache.get(node)!;
```

2021-03-29 21:46 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    let inlineStyles;
My preference would be to type this explicitly here; it's currently left undecided what this is meant to be which is making it harder to read (at least for me)

```suggestion
    let inlineStyles: Promise<void>|null = null;
```

2021-03-29 22:05 UTC, clydin commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    if (inlineStyles !== null) {
That requires a double lookup and a non-null assertion though.

2021-03-29 22:07 UTC, clydin commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    let inlineStyles = this.preanalyzeStylesCache.get(node) || null;
I'd be nice if we could avoid the null completely here actually

2021-03-29 22:11 UTC, clydin commented on packages/compiler-cli/src/ngtsc/core/api/src/interfaces.ts
> +   * * Resources referenced via a component's `styles` or `styleUrls` properties are of
yes. it shows up as a list.

2021-03-29 22:16 UTC, clydin commented on packages/compiler-cli/src/ngtsc/core/api/src/interfaces.ts
> +  readonly resourceFile?: string;
Outside the DOM API, `null` is rarely used.  Any particular reason for avoiding optional properties?

2021-03-29 23:08 UTC, clydin commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
>      if (componentStyleUrls === null) {
I started a separate refactor PR to address some things like this but I can make this change here.

2021-03-29 23:45 UTC, clydin commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
>        const litStyles = parseFieldArrayValue(component, 'styles', this.evaluator);
There are currently no use cases where a transform would be synchronous so I intentionally avoided the extra complexity of the synchronous path.

It should now assert and throw if `loadNgStructureAsync` is not executed.

2021-03-29 23:46 UTC, clydin commented on packages/compiler-cli/src/ngtsc/core/api/src/interfaces.ts
> +   * cause a diagnostics error or an exception to be thrown.
it should throw now with the latest changes.

2021-03-30 08:12 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +    if (inlineStyles !== null) {
Yes; we've found that to not add any noticeable overhead though.

2021-03-30 08:15 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/core/api/src/interfaces.ts
> +  readonly resourceFile?: string;
The primary reason for required properties is that they can't be forgotten about when creating such objects. As for `null`, that's us being explicit about an absent value. I don't feel too strongly about it, though.

2021-03-30 08:16 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
>      if (componentStyleUrls === null) {
I would be okay with a follow-up refactor PR to clean this up.

2021-03-30 08:22 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
>      if (componentStyleUrls === null) {
Oh, it's gone already 🚀

2021-03-30 20:15 UTC, JoostK approved these changes
The changes LGTM to land for v12. Would be good to expand our test coverage of (async) resource loading/processing in a followup PR.

2021-04-02 18:46 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:366484014:BASE:366484048:1617389156867:acbe315d).

2021-04-02 22:48 UTC, closed without merging