fix(compiler-cli): support more `extends` like TypeScript
angular/angular pull request #41349
Opened 2021-03-26 09:22 UTC by JounQin

close #41343

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #41343

## What is the new behavior?

support sub file of node package and relative path without json extension

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-03-26 17:14 UTC, alan-agius4 commented
Hi @JounQin,

Thanks for this, I’ll try to review this next week as had some days off.

Just 2 points.

1. The CI failure seems to be related to this change
2. When you check for extension, let’s validate that these are json.
2. Can try to implant this change without using TSC private API? I don’t think it should be too difficult to achieve the same behaviour using the public API.

2021-03-26 17:17 UTC, alan-agius4 commented
Also maybe the commit message can be changed to provide additional context.

```
fix(compiler-cli): fix extending angularCompilerOptions from unrooted and extension less TypeScript configurations TypeScript

2021-03-29 06:42 UTC, JounQin commented
> Hi @JounQin,
> 
> Thanks for this, I’ll try to review this next week as had some days off.
> 
> Just 3 points to keep in mind.
> 
> 1. The CI failure seems to be related to this change
> 2. When you check for extension, let’s validate that these are json.
> 3. Can try to implement this change without using TSC private API? I don’t think it should be too difficult to achieve the same behaviour using the public API. We should avoid using private APIs.

@alan-agius4 

1. I have no idea why the CI failed. `Error: ENOENT: no such file or directory, unlink 'C:\users\circleci\_bazel_circleci\u4uoan2j\execroot\angular\node_modules\@angular\compiler'`, I don't have a Windows PC personally, do you have any idea to fix?

fixed 2 and 3

2021-03-29 17:27 UTC, alan-agius4 commented on packages/compiler-cli/src/perform_compile.ts
> +    } else
If we use a recursive function this code can be simplified, also for consistence either use  `host.extname` or `.endsWith`

```ts
function getExtendedConfigPath(
  configFile: string,
  extendsValue: string,
  host: ConfigurationHost,
  fs: FileSystem,
  forceJsonExtension = false,
): AbsoluteFsPath | null {
  let extendedConfigPath: AbsoluteFsPath | null = null;

  if (forceJsonExtension && !extendsValue.endsWith('.json')) {
    extendsValue = `${extendsValue}.json`;
  }

  if (extendsValue.startsWith('.') || fs.isRooted(extendsValue)) {
    extendedConfigPath = host.resolve(host.dirname(configFile), extendsValue);
  } else {
    const parseConfigHost = createParseConfigHost(host, fs);

    // Path isn't a rooted or relative path, resolve like a module.
    const {
      resolvedModule,
    } = ts.nodeModuleNameResolver(
      extendsValue, configFile,
      { moduleResolution: ts.ModuleResolutionKind.NodeJs, resolveJsonModule: true },
      parseConfigHost);
    if (resolvedModule) {
      extendedConfigPath = absoluteFrom(resolvedModule.resolvedFileName);
    }
  }

  if (host.exists(extendedConfigPath) || extendedConfigPath.endsWith('.json') || forceJsonExtension) {
    return extendedConfigPath;
  }

  return getExtendedConfigPath(configFile, extendsValue, host, fs, true);
}
```

2021-03-29 17:28 UTC, alan-agius4 commented on packages/compiler-cli/test/perform_compile_spec.ts
> +  it('should merge tsconfig "angularCompilerOptions" when extends point to sub file of node package',
```suggestion
  it('should merge tsconfig "angularCompilerOptions" when extends point to file without extension in a node package',
```

2021-03-29 17:33 UTC, alan-agius4 requested changes
Thanks for this.

2 small nits.

2021-03-29 17:34 UTC, alan-agius4 commented
Can you also please add `close #41343` as commit message footer.

2021-03-29 19:22 UTC, AndrewKushnir commented on packages/compiler-cli/src/perform_compile.ts
> +    // https://github.com/microsoft/TypeScript/blob/4774666f2343c6ffdbf862ffff63f8653a09449b/src/compiler/commandLineParser.ts#L2806
Quick comment: could you please add a couple sentences in the code (as inline comments) describing this, so that there is always a quick context available.

2021-03-30 04:38 UTC, JounQin commented
@alan-agius4 I have no idea why CI is broken again, and it seems the master branch is also broken. (I've just rebased from the master branch)

2021-03-30 09:37 UTC, alan-agius4 approved these changes
LGTM, thanks

2021-03-30 09:44 UTC, alan-agius4 commented on packages/compiler-cli/src/perform_compile.ts
> +  // ./tsconfig.app -> ./tsconfig.app.json
Nit 
```suggestion
```

In think it's clear what this is doing, I think it's better to add the comment when we use `forceJsonExtension`  to explain why.

2021-03-30 09:45 UTC, alan-agius4 commented on packages/compiler-cli/src/perform_compile.ts
> +  return getExtendedConfigPath(configFile, extendsValue, host, fs, true);
Nit:
 
```suggestion
  // Try to resolve the paths with a json extension append a json extension to the file in case if is is missing and the resolution failed. This is to replicate TypeScript behaviour
  // See: https://github.com/microsoft/TypeScript/blob/4774666f2343c6ffdbf862ffff63f8653a09449b/src/compiler/commandLineParser.ts#L2806
  return getExtendedConfigPath(configFile,`{extendsValue}.json`, host, fs);
```

2021-03-30 09:46 UTC, alan-agius4 commented on packages/compiler-cli/src/perform_compile.ts
> +    forceJsonExtension = false,
```suggestion
    forceJsonExtension = false,
```

2021-03-30 09:46 UTC, alan-agius4 commented on packages/compiler-cli/src/perform_compile.ts
> +  if (forceJsonExtension && !extendsValue.endsWith('.json')) {
```suggestion
```

2021-03-30 09:47 UTC, alan-agius4 commented on packages/compiler-cli/src/perform_compile.ts
> +
Actually I just figured that this is not needed at all. Sorry about this.

```suggestion
```

2021-03-30 09:48 UTC, alan-agius4 requested changes
Actually, just realised that `forceJsonExtension` is not needed and we can simplify the method even more. Sorry about this.

2021-03-30 09:56 UTC, JounQin commented
> Actually, just realised that `forceJsonExtension` is not needed and we can simplify the method even more. Sorry about this.

Then we need to change `extendedConfigPath.endsWith('.json')` to `extendsValue.endsWith('.json')` right?

2021-03-30 10:01 UTC, alan-agius4 commented
Yes

2021-03-30 10:02 UTC, alan-agius4 commented
Yes and for performance reasons the check should be inverted
```ts
if (extendsValue?.endsWith('.json') || host.exists(extendedConfigPath))** {
```

2021-03-30 10:08 UTC, JounQin commented
@alan-agius4 Done!

2021-03-30 10:17 UTC, alan-agius4 approved these changes
LGTM, thanks

2021-03-30 11:49 UTC, JounQin commented on packages/compiler-cli/src/perform_compile.ts
> +  // is is missing and the resolution failed. This is to replicate TypeScript behaviour See:
@alan-agius4 Should it be `it is`? I’ve just copied your comments.

2021-03-30 11:57 UTC, alan-agius4 commented on packages/compiler-cli/src/perform_compile.ts
> +  // is is missing and the resolution failed. This is to replicate TypeScript behaviour See:
Yeah absolutely

2021-04-01 21:59 UTC, JoostK commented on packages/compiler-cli/test/perform_compile_spec.ts
> +  it('should merge tsconfig "angularCompilerOptions" when extends point to an extension less non rooted file',
How is this test different from the existing one above? It looks like the same scenario to me.

2021-04-01 21:59 UTC, JoostK commented on packages/compiler-cli/src/perform_compile.ts
> +  return getExtendedConfigPath(configFile, `${extendsValue}.json`, host, fs);
I think I prefer the way TypeScript structured this code, instead of the recursive invocation. The recursion makes it less obvious that only two files are attempted, and the recursion is actually not relevant for the module resolution case (because the result from module resolution has already been verified to exist) but that's not clear from the code paths.

I would suggest to make the change closer to TypeScript's logic. The `if (extendedConfigPath !== null && host.exists(extendedConfigPath))` condition that used to be at the top-level of this function can actually be moved into the block for relative and rooted files, which is where the json file handling can then be handled as well. You can then even remove the separate declaration of the `extendedConfigPath` variable as it won't be necessary in the module resolution block anymore; that one can be simplified to `return absoluteFrom(resolvedModule.resolvedFileName);`. This results in the exact same structure as TS uses.

2021-04-02 00:15 UTC, alan-agius4 commented on packages/compiler-cli/test/perform_compile_spec.ts
> +  it('should merge tsconfig "angularCompilerOptions" when extends point to an extension less non rooted file',
That test is different because the extends point to a package and the path of the tsconfig is resolved from https://github.com/angular/angular/blob/07fe4dc6267a25fdea45cd2f29c705a82add9663/packages/compiler-cli/test/perform_compile_spec.ts#L127

In this case the extends point to an extension less json file in a package, which resolution is slightly different, as module resolution will fail in this case and needs to be invoked with a json extension. 

Ie: in this case module resolution will be called twice, once without extension and when that fails it will be called again with the json extension.

2021-04-02 00:21 UTC, alan-agius4 commented on packages/compiler-cli/src/perform_compile.ts
> +  return getExtendedConfigPath(configFile, `${extendsValue}.json`, host, fs);
Note: module resolution might fail in which case it needs to be invoked again with the json extension. 

TS logic doesn’t need this because they have an option `lookupConfig ` which is not exposed as part of the API that allows this behaviour. 

https://github.com/microsoft/TypeScript/blob/b34e705672cc31b86ce9291f1e234b387aaa3184/src/compiler/moduleNameResolver.ts#L925

2021-04-05 14:23 UTC, JoostK approved these changes
Thank you for working on this. Some nits, but happy to approve.

2021-04-05 14:23 UTC, JoostK commented on packages/compiler-cli/test/perform_compile_spec.ts
> +  it('should merge tsconfig "angularCompilerOptions" when extends point to an extension less non rooted file',
```suggestion
  it('should merge tsconfig "angularCompilerOptions" when extends points to a non rooted file without json extension',
```

2021-04-05 14:23 UTC, JoostK commented on packages/compiler-cli/test/perform_compile_spec.ts
> +  it('should merge tsconfig "angularCompilerOptions" when extends point to relative config without json extension',
```suggestion
  it('should merge tsconfig "angularCompilerOptions" when extends points to relative config without json extension',
```

2021-04-05 14:23 UTC, JoostK commented on packages/compiler-cli/src/perform_compile.ts
> +  return getExtendedConfigPath(configFile, `${extendsValue}.json`, host, fs);
Ooh, sneaky. I still think that the overarching `extendedConfigPath` variable is redundant, though, as its assignment in the module resolution block can be replaced with an immediate return. The recursion can be avoided by having a separate function that does the work, which can then be invoked twice:

```ts
function getExtendedConfigPath(configFile: string, extendsValue: string, host: ConfigurationHost, fs: FileSystem): AbsoluteFsPath|null {
  const result = getExtendedConfigPathWorker(configFile, extendsValue, host, fs);
  if (result !== null) {
    return result;
  }

  // Try to resolve the paths with a json extension append a json extension to the file in case if
  // it is missing and the resolution failed. This is to replicate TypeScript behaviour, see:
  // https://github.com/microsoft/TypeScript/blob/294a5a7d784a5a95a8048ee990400979a6bc3a1c/src/compiler/commandLineParser.ts#L2806
  return getExtendedConfigPathWorker(configFile, `${extendsValue}.json`, host, fs);
}

function getExtendedConfigPathWorker(configFile: string, extendsValue: string, host: ConfigurationHost, fs: FileSystem): AbsoluteFsPath|null {
  if (extendsValue.startsWith('.') || fs.isRooted(extendsValue)) {
    const extendedConfigPath = host.resolve(host.dirname(configFile), extendsValue);
    if (host.exists(extendedConfigPath))) {
      return extendedConfigPath;
    }
  } else {
    const parseConfigHost = createParseConfigHost(host, fs);

    // Path isn't a rooted or relative path, resolve like a module.
    const {
      resolvedModule,
    } =
        ts.nodeModuleNameResolver(
            extendsValue, configFile,
            {moduleResolution: ts.ModuleResolutionKind.NodeJs, resolveJsonModule: true},
            parseConfigHost);
    if (resolvedModule) {
      return absoluteFrom(resolvedModule.resolvedFileName);
    }
  }

  return null;
}
```

I don't feel too strongly about this, though, so happy to approve the current approach.

2021-04-06 07:58 UTC, JounQin commented on packages/compiler-cli/src/perform_compile.ts
> +  return getExtendedConfigPath(configFile, `${extendsValue}.json`, host, fs);
@alan-agius4 What's your opinion here? I'm fine with this change or not.

2021-04-06 08:05 UTC, alan-agius4 commented on packages/compiler-cli/src/perform_compile.ts
> +  return getExtendedConfigPath(configFile, `${extendsValue}.json`, host, fs);
I am good either way. But let's go with @JoostK approach since it's a bit easier to follow.

2021-04-06 09:07 UTC, JounQin commented on packages/compiler-cli/src/perform_compile.ts
> +  return getExtendedConfigPath(configFile, `${extendsValue}.json`, host, fs);
Done!

2021-04-06 18:34 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:367049056:BASE:367049088:1617734035013:27be8d22).

2021-04-07 16:37 UTC, closed without merging