fix(platform-browser): improve error message for missing animation tr…
angular/angular pull request #41356
Opened 2021-03-27 20:33 UTC by kirjs

…igger

There are two reasons why this error can be called, but only one was covered before.

Fixes #15581

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [n/a] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #15581 

## What is the new behavior?
An example of a new error message is: 
```
Found the synthetic property @myAnimation. Possible reasons:
  - "BrowserAnimationsModule" or "NoopAnimationsModule" are missing in your application.
  - There is no corresponding configuration for the animation named `@myAnimation` defined in the `animations` field of the `@Component` decorator (see https://angular.io/api/core/Component#animations).

```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-03-27 20:35 UTC, kirjs commented
I'm not sure if the animation message is relevant for the server code.
Should I roll that one back?

2021-03-29 20:03 UTC, jessicajaniuk commented
> I'm not sure if the animation message is relevant for the server code.
> Should I roll that one back?

Leave it in. It's possible this error could happen server side depending on how the person configured things, and the NoopAnimationsModule would be what they should see there. So it's definitely helpful for debugging.

2021-03-29 20:04 UTC, jessicajaniuk approved these changes
LGTM 🍪 

Thank you!

2021-03-29 22:18 UTC, AndrewKushnir requested changes
@kirjs thanks for improving the error message 👍

I've left a few comments, could you please have a look when you get a chance?

2021-03-29 22:18 UTC, AndrewKushnir commented on packages/core/test/animation/animation_integration_spec.ts
> +    it('should throw when using an @prop listener, BrowserAnimationModule is imported, but there is no animation rule',
Could you please add a test case with property binding as well?

```
it('should throw when using a @prop property, BrowserAnimationModule is imported, but there is no animation rule', () => {
  @Component({template: `<div [@myAnimation]="true"></div>`})
  class Cmp {}

  TestBed.configureTestingModule({declarations: [Cmp], imports: [BrowserAnimationsModule]});

  expect(() => TestBed.createComponent(Cmp)).toThrowError(syntheticPropError('@myAnimation', 'property'));
});
```

2021-03-29 22:18 UTC, AndrewKushnir commented on packages/platform-browser/src/dom/dom_renderer.ts
> +        name}\` defined in the \`animations\` field of the \`@Component\` decorator (see https://angular.io/api/core/Component#animations).`);
I'd propose rephrasing it a bit:

```suggestion
    throw new Error(`Unexpected synthetic ${nameKind} ${name} found. Please make sure that:
  - Either "BrowserAnimationsModule" or "NoopAnimationsModule" are imported in your application.
  - There is corresponding configuration for the animation named \`${
        name}\` defined in the \`animations\` field of the \`@Component\` decorator (see https://angular.io/api/core/Component#animations).`);
```

2021-03-29 22:18 UTC, AndrewKushnir commented on packages/platform-browser/src/dom/dom_renderer.ts
> +
Could you please revert extra lines?

2021-04-04 19:13 UTC, kirjs commented
Addressed the feedback PTAL

2021-04-05 21:07 UTC, AndrewKushnir approved these changes
Thanks for addressing the feedback @kirjs 👍 

I've left 1 minor comment, please have a look when you get a chance.

2021-04-05 21:07 UTC, AndrewKushnir commented on packages/platform-browser/src/dom/dom_renderer.ts
> +  - Either "BrowserAnimationsModule" or "NoopAnimationsModule" are imported in your application.
I'd propose using backticks here for consistency with the second item:
```suggestion
  - Either \`BrowserAnimationsModule\` or \`NoopAnimationsModule\` are imported in your application.
```

2021-04-12 20:42 UTC, AndrewKushnir reviewed
Thanks for updating this PR @kirjs. It looks there is a couple more places where we can replace double quotes with backticks (for consistency). Could you please have a look at the comments when you get a chance? Thank you.

2021-04-12 20:42 UTC, AndrewKushnir commented on packages/core/test/animation/animation_integration_spec.ts
> +  - Either "BrowserAnimationsModule" or "NoopAnimationsModule" are imported in your application.
```suggestion
  - Either \`BrowserAnimationsModule\` or \`NoopAnimationsModule\` are imported in your application.
```

2021-04-12 20:42 UTC, AndrewKushnir commented on packages/core/test/animation/animation_integration_spec.ts
> +          a: any;
```suggestion
          a: boolean = false;
```

2021-04-12 20:42 UTC, AndrewKushnir commented on packages/platform-server/src/server_renderer.ts
> +  - Either "BrowserAnimationsModule" or "NoopAnimationsModule" are imported in your application.
```suggestion
  - Either \`BrowserAnimationsModule\` or \`NoopAnimationsModule\` are imported in your application.
```

2021-04-12 20:43 UTC, AndrewKushnir commented
@kirjs there are some lint warning as well, caused by the commit messages not being compliant with the format (the scope is missing, i.e. `fix(...):` part). Could you plz squash all commits into one once the feedback is addressed?

2021-09-15 14:30 UTC, petebacondarwin commented
@google I consent

2021-09-15 14:31 UTC, petebacondarwin commented
I have rebased and fixed up the requested changes.
@AndrewKushnir once this goes green (hopefully) can you mark it for merge?

2021-09-15 14:34 UTC, alan-agius4 approved these changes
LGTM for platform-server

2021-09-15 17:53 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:396873211:BASE:396873241:1631728339528:f01cfe18).

2021-09-15 17:54 UTC, AndrewKushnir commented
@petebacondarwin thanks for pushing updates! I've started a new presubmit and will add the PR to the merge queue once presubmit is completed. Thank you.

2021-09-15 21:09 UTC, closed without merging

2021-09-15 21:14 UTC, jessicajaniuk commented
Ignore the closed message. This PR has been merged through tooling.