build: update to husky@6
angular/angular pull request #41405
Opened 2021-04-01 04:33 UTC by damingerdai

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-04-01 15:17 UTC, gkalpak approved these changes
Thx, @damingerdai!
Should we switch to `prepare` npm script (instead of `postinstall`) as is the new recommended way (after typicode/husky#890)?

2021-04-01 15:23 UTC, gkalpak commented
BTW, you need to add a commit message body (of at least 20 characters) to pass linting.

2021-04-02 02:06 UTC, damingerdai commented
> Should we switch to `prepare` npm script (instead of `postinstall`) as is the new recommended way (after [typicode/husky#890](https://github.com/typicode/husky/pull/890))?

I agree with you, but I am not sure whether I should complete the changes in this pr.

2021-04-02 02:14 UTC, damingerdai commented
@gkalpak please review

2021-04-02 14:52 UTC, gkalpak commented
@damingerdai, I don't see any changes. Did you forget to push them maybe?

2021-04-02 15:03 UTC, damingerdai commented
> @damingerdai, I don't see any changes. Did you forget to push them maybe?

i just add commit message body.

2021-04-02 15:31 UTC, gkalpak commented
Oh, I see, sorry 😅
I thought you implemented switching to `prepare` and was looking for code changes 😇

I think it is reasonable to switch to `prepare` as part of this PR, since it is a new recommendation in husky 6, so it makes sense to make the change along with the updating imo.

2021-04-02 23:15 UTC, damingerdai commented
@gkalpak please review

2021-04-03 13:29 UTC, gkalpak requested changes
Thx for making the changes, @damingerdai :+1:

Can you please change the second commit message to mention typicode/husky#890, where the recommendation to switch to `prepare` is made. For example:

> build: install husky in \`prepare\` script instead of \`postinstall\`
>
> With typicode/husky#890, the recommended way to install husky is in the
> \`prepare\` script instead of the \`postinstall\`. This commit moves
> the husky installation to the \`prepare\` script to align with the new
> recommendation.

2021-04-03 13:29 UTC, gkalpak commented on package.json
> +    "prepare": "husky install"
Please move this script just below `postinstall` (since that is conceptually closer to how the scripts are called).

2021-04-05 13:06 UTC, damingerdai commented
@gkalpak thanks for your suggestions. please review again.

2021-04-05 14:01 UTC, gkalpak approved these changes
Thx again, @damingerdai :+1:

LGTM, except you need to rebase on latest master to make CI happy :smiley:

2021-04-06 02:38 UTC, damingerdai commented
@gkalpak i have rebased on latest master but there still are two ci failed

2021-04-06 11:02 UTC, gkalpak approved these changes
Thx again, @damingerdai!
The latest CI failures were flakes. I have restarted the job and it passes now 🚀

2021-04-06 17:03 UTC, closed without merging