fix(compiler-cli): Allow analysis to continue with invalid style url
angular/angular pull request #41403
Opened 2021-03-31 21:28 UTC by atscott

Currently, we throw a FatalDiagnosticError when we fail to load a resource
(`templateUrl` or `styleUrl`) at various stages in the compiler. This prevents
analysis of the component from completing. This will result in in users not being
able to get any information in the component template when there is a missing
`styleUrl`, for example.

This commit simply tracks the diagnostic, marks the component as poisoned, and
continues merrily along. Environments configured to use poisoned data
(like the language service) will then be able to use other information from the analysis.

Fixes https://github.com/angular/vscode-ng-language-service/issues/1241

2021-04-01 21:33 UTC, atscott commented
[presubmit](http://test/OCL:366331453:BASE:366331510:1617312659573:16f5b1a9)

2021-04-05 20:43 UTC, alxhub requested changes

2021-04-05 20:43 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +        const resourceUrl = this._resolveResourceOrThrow(
Rather than this `try`/`catch`, we should make `_resolveResourceOrThrow` _not_ throw, and instead return some kind of error that we can choose to deal with (or ignore) as we see fit. Possibly this means its return value will be some kind of union between a success type and a failure type that also includes a diagnostic.

2021-04-05 20:43 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +          isPoisoned = true;
`isPoisoned` means "cannot be relied upon by consuming components" - a component shouldn't be poisoned because its own template or stylesheets are unavailable as they're not a part of its public API.

2021-04-06 22:10 UTC, alxhub approved these changes

2021-04-07 16:42 UTC, closed without merging