feat(compiler-cli): mark ability to use partial compilation mode as stable
angular/angular pull request #41518
Opened 2021-04-08 20:35 UTC by JoostK

This commit marks the `compilationMode` compiler option as stable, such
that libraries can be compiled in partial compilation mode.

In partial compilation mode, the compiler's output changes from fully
compiled AOT definitions to an intermediate form using partial
declarations. This form is suitable to be published to NPM, which now
allows libraries to be compiled and published using the Ivy compiler.

Please be aware that libraries that have been compiled using this mode
can only be used in Angular 12 applications and up; they cannot be used
when Ivy is disabled (i.e. when using View Engine) or in versions of
Angular prior to 12. The `compilationMode` option has no effect if
`enableIvy: false` is used.

Closes #41496

2021-04-08 21:15 UTC, atscott approved these changes
reviewed-for: public-api

2021-04-08 21:18 UTC, jessicajaniuk approved these changes
LGTM 🍪 

reviewed-for: public-api

2021-04-09 10:32 UTC, petebacondarwin approved these changes
Reviewed-for: public-api

2021-04-09 10:34 UTC, petebacondarwin requested changes
Actually we need to update this doc too: https://github.com/angular/angular/blob/master/aio/content/guide/angular-compiler-options.md

2021-04-09 13:47 UTC, alxhub approved these changes
🎉

2021-04-10 11:49 UTC, petebacondarwin approved these changes
Just a couple of docs suggestions.

2021-04-10 11:49 UTC, petebacondarwin commented on aio/content/guide/angular-compiler-options.md
> +- `'full'`: generates fully AOT-compiled code using Ivy instructions.
I am not sure if we should mention ivy here. But if we do perhaps it sounds better as:

```suggestion
- `'full'`: generates fully AOT-compiled code containing Ivy instructions.
```

2021-04-10 11:49 UTC, petebacondarwin commented on aio/content/guide/angular-compiler-options.md
> +- `'partial'`: generates code in a stable, but intermediate form suitable for publication to NPM.
How about? In case there are other ways to publish?

```suggestion
- `'partial'`: generates code in a stable, but intermediate form suitable for a published library.
```

2021-04-11 19:01 UTC, JoostK commented on aio/content/guide/angular-compiler-options.md
> +- `'full'`: generates fully AOT-compiled code using Ivy instructions.
Rephrased this to remove the Ivy instruction reference but instead mention that the generated code is according to the version of Angular that is currently being used.

2021-04-12 05:02 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:367931793:BASE:367931800:1618203683314:749d5cae).

2021-04-12 17:31 UTC, closed without merging