docs: reword references to change detection status
angular/angular pull request #41551
Opened 2021-04-10 05:33 UTC by cesperian

Fixes #40761

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 40761

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## Other information

2021-04-10 05:54 UTC, cesperian commented
rebase. standby...

2021-04-10 12:21 UTC, petebacondarwin commented on aio/content/guide/glossary.md
> +There are 2 internal state  available for change detection; "CheckAlways" (the default) and "CheckOnce".
```suggestion
There are 2 internal states available for change detection; "CheckAlways" (the default) and "CheckOnce".
```

2021-04-10 12:22 UTC, petebacondarwin commented on aio/content/guide/glossary.md
> +When using the CheckAlways change-detection strategy, the change detector goes through the [view hierarchy](#view-tree) on each VM turn to check every [data-bound property](#data-binding) in the temp
```suggestion
When using the CheckAlways change-detection strategy, the change detector goes through the [view hierarchy](#view-tree) on each pass to check every [data-bound property](#data-binding) in the template. In the first phase, it compares the current state of the dependent data with the previous state, and collects changes.
```

2021-04-10 12:24 UTC, petebacondarwin commented on aio/content/guide/pipes.md
> +Impure pipes are called whenever change detection runs for a component, which could be every few milliseconds with the default `ChangeDetectionStrategy` setting.
```suggestion
Impure pipes are called whenever change detection runs for a component, since it cannot infer whether the pipe output needs to change. This could be every few milliseconds with the default `ChangeDetectionStrategy` setting.
```

2021-04-10 12:25 UTC, petebacondarwin requested changes
Made a few suggestions. Thanks for working on this @cesperian

2021-04-11 06:07 UTC, cesperian commented
@petebacondarwin thanks for the suggestions. I'll have a look at these (and the ones I saw you recently made for PR 41332 also).

Do you know of any additional instances in the documentation where the wording should be updated besides in the two I submitted?...

2021-04-11 14:23 UTC, petebacondarwin commented
A quick search comes up with:

- https://github.com/angular/angular/blob/master/packages/core/src/change_detection/constants.ts#L18-L32
- https://github.com/angular/angular/blob/master/packages/core/src/change_detection/change_detector_ref.ts#L35-L55
- https://github.com/angular/angular/blob/master/packages/core/src/change_detection/change_detector_ref.ts#L68-L80
- https://github.com/angular/angular/blob/master/packages/core/src/metadata/directives.ts#L458-L466

2021-05-25 16:14 UTC, aikidave commented
Hi @cesperian ! We refined our thinking on this issue, but I didn't realize you had created this PR! I have a separate PR, #42300 that we're going to use to address this issue. Sorry for the overlap in work, but I am very grateful for your continued contributions to the repository!

2021-05-25 16:14 UTC, closed without merging