fix(zone.js): should continue to executue listeners when throw error
angular/angular pull request #41562
Opened 2021-04-11 06:27 UTC by JiaLiPassion

Close #41522

`zone.js` patches event listeners and run all event listeners together, if
one event handler throws error, the listeners afterward may not be invoked.

Reproduction:

```
export class AppComponent implements AfterViewInit {
  @ViewChild('btn') btn: ElementRef;
  title = 'event-error';

  constructor(private ngZone: NgZone) {}

  ngAfterViewInit() {
    this.ngZone.runOutsideAngular(() => {
      this.btn.nativeElement.addEventListener('click', () => {
        throw new Error('test1');
      });
      this.btn.nativeElement.addEventListener('click', () => {
        console.log('add eventlistener click');
      });
    });
  }
}
```

Until now no Angular users report this issue becuase in the `ngZone`, all
error will be caught and will not rethrow, so the event listeners afterward
will still continue to execute, but if the event handlers are outside of `ngZone`,
the error will break the execution.

This commit catch all errors, and after all event listeners finished invocation,
rethrow the errors in seperate `microTasks`, the reason I am using `microTask` here
is to handle multiple errors case.

2021-04-11 16:20 UTC, petebacondarwin approved these changes

2021-04-11 16:24 UTC, petebacondarwin requested changes
Reviewed-for: size-tracking

2021-04-11 16:24 UTC, petebacondarwin commented on packages/zone.js/lib/common/events.ts
> +          });
This whole block is a duplicate of the same earlier on in the file (~lines 156-171).
Can you reduce the increase in size of the polyfill file by using a shared function?

2021-04-11 16:34 UTC, mleibman commented on packages/zone.js/lib/common/events.ts
> +          const err = invokeTask(copyTasks[i], target, event);
`invokeTask()` is what's throwing the exception here, breaking out of the loop and the function.
I don't see how this could work without a try-catch.

2021-04-11 16:39 UTC, petebacondarwin commented on packages/zone.js/lib/common/events.ts
> +          const err = invokeTask(copyTasks[i], target, event);
The try-catch is in the `invokeTask()` function above: https://github.com/angular/angular/pull/41562/files#diff-08d8fc6c9e986dfc70c1cb881850be682b6294bf645e2d4b53b74a9c4a358c3aR104

2021-04-11 16:41 UTC, mleibman commented on packages/zone.js/lib/common/events.ts
> +          const err = invokeTask(copyTasks[i], target, event);
d'oh! didn't notice that

2021-04-12 01:28 UTC, JiaLiPassion commented on packages/zone.js/lib/common/events.ts
> +          });
@petebacondarwin , sure , the duplicate code is for some legacy reason, I have just updated the code to use a shared function.

2021-04-12 10:01 UTC, petebacondarwin approved these changes
Great - and this avoids the need for `size-tracking` approval!

2021-04-12 17:40 UTC, AndrewKushnir commented
FYI I've started a [presubmit](http://test/OCL:368033629:BASE:368033670:1618248872431:ba168e12), but it looks like we'd need to run a global one tonight as well, since this is a change in behavior as well and might potentially affect apps that rely on the current behavior. Depending on the presubmit results, we may need to consider landing this change in major/minor only (avoid patch).

2021-04-13 04:39 UTC, AndrewKushnir commented
@JiaLiPassion FYI presubmits (including a global one) went well.

@mhevery could you please have a look at the changes when you get a chance?

2021-04-13 17:44 UTC, mhevery approved these changes

2021-04-13 17:52 UTC, AndrewKushnir commented
Note to caretaker: TGP for the changes in this PR is successful, but it'd be great to merge and sync that in g3 as a separate change (for easier rollback if needed). Thank you.

2021-04-15 19:41 UTC, AndrewKushnir commented
JFYI, since the last global presubmit was 3 days ago, I'll run another one tonight to make sure there are no issues in g3 and if everything goes well, will merge it tomorrow.

2021-04-16 03:32 UTC, AndrewKushnir commented
[Global Presubmit #2](https://test.corp.google.com/ui#id=OCL:368033629:BASE:368769700:1618543932045:65759225).

2021-04-16 21:35 UTC, AndrewKushnir commented
Just a quick update: TGP went well (no issues), but I think it'd be safer to merge this change on Monday (vs Friday afternoon), so that we have time for rollback if needed.

2021-04-19 06:19 UTC, AndrewKushnir commented
[Global Presubmit #3](https://test.corp.google.com/OCL:368033629:BASE:369158251:1618813127016:7eafe1b8).

2021-04-19 18:50 UTC, AndrewKushnir commented
FYI, reopening this PR due to CI flakiness introduced by these change, see https://github.com/angular/angular/pull/41562.
Example CI failure: https://app.circleci.com/pipelines/github/angular/angular/31536/workflows/28d37712-9f5b-484b-85d4-9f4b029f1e4b/jobs/968579.

2021-04-21 02:18 UTC, AndrewKushnir commented
[Global Presubmit #4](https://test.corp.google.com/ui#id=OCL:368033629:BASE:369568351:1618971484577:ce2da00b).

2021-04-21 22:54 UTC, closed without merging