Fix AsyncPipe types for RxJS 6 and 7
angular/angular pull request #41590
Opened 2021-04-13 00:18 UTC by benlesh

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [] ~~Tests for the changes have been added (for bug fixes / features)~~ (this is a non-breaking change and adding a test would require adding a development dependency to this project of `rxjs@next`, which seems like overkill). However this will get exercised extremely well in `google3`.
- [x] ~~Docs have been added / updated (for bug fixes / features)~~ unnecessary

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:

This resolves an issue reported to me by @leggechr and escalated to @alxhub. The issue is discussed here as well: https://github.com/microsoft/TypeScript/issues/43643

## What is the current behavior?
Currently, when upgrading to RxJS 7, in many cases Angular templates are unable to infer the proper value type from RxJS observables. This is because of the TypeScript issue/quirk pointed out above.

## What is the new behavior?
The value types will be inferred properly in the Angular template.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This is affecting targets within `google3` and I recommend you work with @leggechr and escalate this as a Googler issue.

2021-04-13 05:43 UTC, martinmcwhorter commented on packages/common/src/pipes/async_pipe.ts
> +  private _obj:|Subscribable<any>|Promise<any>|EventEmitter<any>|null = null;
Leading |
Did you mean to add Observable?

2021-04-13 12:40 UTC, alxhub requested changes

2021-04-13 12:40 UTC, alxhub commented on packages/common/src/pipes/async_pipe.ts
> +    return async.then(updateLatestValue, (e) => {
Spurious change?

2021-04-13 12:40 UTC, alxhub commented on packages/common/src/pipes/async_pipe.ts
> +  private _obj:|Subscribable<any>|Promise<any>|EventEmitter<any>|null = null;
Yeah, this change seems to have been corrupted before it was pushed.

2021-04-13 17:32 UTC, benlesh commented on packages/common/src/pipes/async_pipe.ts
> +  private _obj:|Subscribable<any>|Promise<any>|EventEmitter<any>|null = null;
Weird, not sure what happened here.

2021-04-13 17:32 UTC, benlesh commented on packages/common/src/pipes/async_pipe.ts
> +    return async.then(updateLatestValue, (e) => {
formatter, most likely.

2021-04-13 17:45 UTC, benlesh commented on packages/common/src/pipes/async_pipe.ts
> +    return async.then(updateLatestValue, (e) => {
Okay, reverted everything, disabled my local format on save option, and tried again. Hopefully this resolves the issue.

2021-05-01 08:25 UTC, e-oz commented
Sorry if it's a noobish request, but could one of you help bots to complete the checks? Please.
I'd like to try RxJS 7 with the Angular :)

2021-05-01 11:52 UTC, petebacondarwin approved these changes
LOL! We only just recently switched this from Observable to Subscribable!

I am not sure where this puts us in terms of breaking changes... it is possible that, since we made the change, someone has implemented this pipe with a `Subscribable` object rather than an `Observable`, which would no longer work. But I suspect this is very unlikely.

Approving generally. This should trigger a public-api review round.

2021-05-01 21:40 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:371516472:BASE:371516478:1619905190091:368f21cf).

2021-05-03 21:32 UTC, alxhub commented
> I am not sure where this puts us in terms of breaking changes... it is possible that, since we made the change, someone has implemented this pipe with a `Subscribable` object rather than an `Observable`, which would no longer work. But I suspect this is very unlikely.

Since this change only adds `Observable<T>` to the signature and doesn't remove `Subscribable<T>`, such a usage should still work.

2021-05-03 21:32 UTC, alxhub approved these changes

2021-05-03 21:33 UTC, alxhub approved these changes
Reviewed-for: public-api

2021-05-03 22:02 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2021-05-03 22:08 UTC, jessicajaniuk approved these changes
I _Observe_ that these changes look good.

reviewed-for: public-api

2021-05-03 22:10 UTC, AndrewKushnir commented
FYI, presubmit looks good, the changes were approved (and the changes look backwards-compatible), so I'm adding the "merge" label. Thank you.

2021-05-04 15:32 UTC, closed without merging