fixup! fix(docs-infra): update glossary to include the term template-…
angular/angular pull request #41593
Opened 2021-04-13 02:39 UTC by andrewasche

…input-variable (#41516)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-04-13 14:52 UTC, atscott requested changes
Hi @andrewasche, thanks for the contribution. Could you also fix the commit message? Looks like it's not quite right.

2021-04-13 14:52 UTC, atscott commented on aio/content/guide/glossary.md
> +A template input variable is a variable you can reference within a single instance of the template. You declare a template input variable using the let keyword as in let hero.
```suggestion
A template input variable is a variable you can reference within a single instance of the template. You declare a template input variable using the let keyword as in `let hero`.
```

2021-04-13 14:52 UTC, atscott commented on aio/content/guide/glossary.md
> +Read and learn more about [Template Input Variables](template-reference-variables#template-input-variable).
```suggestion
Read and learn more about [template input variables](template-reference-variables#template-input-variable).
```

2021-04-13 23:04 UTC, andrewasche commented
I gave it another try. Think it is getting better. I didn't get rid of the old mention to #41516, but I hope the right one sticks

2021-04-14 17:57 UTC, atscott commented
Hi @andrewasche - your PR needed a rebase and the commit message still needed updating. I force pushed these updates to your branch, but the commit is now authored only by me. I suggest creating a new branch, making the change, and opening a new PR so you can get credit for the change. Thanks.

2021-04-14 17:57 UTC, closed without merging