partial evaluator supports primitive declarations
angular/angular pull request #41661
Opened 2021-04-16 15:51 UTC by zarend

partial evaluator can eval string constant, number constant, true,
false and null declarations.

work-in-progress: creating a draft PR for the diff

2021-04-29 18:59 UTC, atscott requested changes

2021-04-30 00:01 UTC, zarend commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/dynamic.ts
> +  DYNAMIC_TYPE,
This is when we try to evaluate something like this

`evaluate('declare x: string', 'x');`

Since the value of `x` cannot be determined statically, we return a dynamic value.

2021-04-30 00:02 UTC, zarend commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
> +      // fallback to returning a reference if this variable declaration does not have a type or we
That's a good point. It's better to return a reference than a `DynamicValue`. `DynamicValue` is the error result, and a reference could be useful to the caller.

I'll rewrite this comment.

2021-05-01 14:51 UTC, atscott commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/dynamic.ts
> +  DYNAMIC_TYPE,
I see that but I don’t think this answers the question of how it’s different from UNKNOWN. _All_ of the enums here can’t be evaluated statically. The enum name _is_ DynamicValueReason and to say it’s a dynamic value because it’s a dynamic value is not super informative.

2021-05-01 15:03 UTC, atscott commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/dynamic.ts
> +  DYNAMIC_TYPE,
Ohhh hold on, this is _type_ versus _value_. I understand now :) 
I think this could possibly still be named better in this case. The type isn't actually "dynamic". This is a dynamic value because there isn't a value assigned. The type is static, we just can't determine the value because there isn't one assigned at the declaration location and the type isn't narrow enough for us to know exactly what it will be. i.e. `: string` can be any string, but `: 'myString'` can only be assigned 'myString' even if the assignment is somewhere else. Is that right?

2021-05-01 15:05 UTC, atscott requested changes

2021-05-01 15:05 UTC, atscott commented on packages/compiler-cli/src/ngtsc/partial_evaluator/test/evaluator_spec.ts
> +      if (!(value[1] instanceof DynamicValue)) {
I think this should be converted to an `expect`.
`expect(value[1]).not.toBeInstanceOf(DynamicValue)`

Same with the if above: `expect(Array.isArray(value)).toBe(true, 'expected an array');`

2021-05-01 15:11 UTC, atscott commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/dynamic.ts
> +  DYNAMIC_TYPE,
some ideas: `AMBIGUOUS_TYPE` / `UNASSIGNED_MUTABLE_VAR` / `UNASSIGNED_AMBIGUOUS_TYPE` / `UNASSIGNED_BROAD_TYPE` / `UNASSIGNED_MUTABLE_TYPE` ?
Also, fleshing out the documentation on this type would help a lot.

2021-05-03 16:27 UTC, zarend commented
Thanks for reviewing. I'll keep the name `DYNAMIC_TYPE`, and I'll work on improving the documentation 🛠️

2021-05-03 18:55 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
> +    }
Since primitive types are already handed in the `visitExpression` function [here](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts#L99-L107), we could just delegate the call? 
```suggestion
      case ts.SyntaxKind.TrueKeyword:
      case ts.SyntaxKind.FalseKeyword:
      case ts.SyntaxKind.NullKeyword:
      case ts.SyntaxKind.PrefixUnaryExpression:
        return this.visitExpression(node.literal, context);
    }
```

2021-05-05 17:45 UTC, zarend commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/dynamic.ts
> +  DYNAMIC_TYPE,
Thanks for the suggestions, I completely rewrote the documentation on the enum member for `DYNAMIC_TYPE`.

2021-05-05 17:46 UTC, zarend commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
> +      // fallback to returning a reference if this variable declaration does not have a type or we
Okay, I rewrote this comment to make it more clear that we're returning a reference to avoid making a behavior change.

2021-05-05 17:50 UTC, zarend commented on packages/compiler-cli/src/ngtsc/partial_evaluator/test/evaluator_spec.ts
> +      if (!(value[1] instanceof DynamicValue)) {
How come? If I use an expect, then I have to type cast value to access `value[0]`.

the code would look like this
```
    it('evaluates tuple elements it cannot understand to DynamicValue', () => {
      const value = evaluate(`declare const x: ['foo', string];`, `x`);

      expect(Array.isArray(value)).toBeTrue();
      expect(( value as any[])[0]).toEqual('foo');
      expect((value as any[])[1] instanceof DynamicValue).toBeTrue();
      expect((value as [string, DynamicValue])[1].isFromDynamicType()).toBe(true);
    });
```

IMHO, this is more cumbersome to write, and is harder to read because it's muddied with type casts.

2021-05-05 17:52 UTC, zarend commented on packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts
> +    }
yeah, good observation. I delete the entire `visitLiteralTypeNode` method since we can delete to `visitExpression`.

2021-05-05 17:56 UTC, atscott commented on packages/compiler-cli/src/ngtsc/partial_evaluator/test/evaluator_spec.ts
> +      if (!(value[1] instanceof DynamicValue)) {
You can actually write that as 
```
const value = evaluate(`declare const x: ['foo', string];`, `x`) as [string, DynamicValue];
```

Stylistically, you should avoid control structures in your tests. https://engdoc.corp.google.com/eng/doc/devguide/testing/unit/best-practices.md?cl=head&polyglot=typescript#control-structures

2021-05-05 18:03 UTC, zarend commented on packages/compiler-cli/src/ngtsc/partial_evaluator/test/evaluator_spec.ts
> +      if (!(value[1] instanceof DynamicValue)) {
Thanks, didn't know that was in the style guide.

I used the cast as you suggested and removed all branching from the test.

2021-05-05 18:07 UTC, zarend commented
@alxhub and @atscott , I've addressed the PR comments and this is ready for your eyes again 👀 . Since you last saw this, I rewrote the code comments documentation, and removed the unnecessary `visitLiteraltypeNode` method.

2021-05-06 20:43 UTC, atscott approved these changes

2021-05-10 15:12 UTC, alxhub approved these changes

2021-05-11 22:09 UTC, zarend commented
[presubmit](/cl/372420651)

2021-06-24 10:32 UTC, petebacondarwin commented
@zarend - it looks like presubmit failed here. Other than that, is this PR ready to go?

2021-06-24 15:22 UTC, zarend commented
This should be ready once presubmit passes. I'm running a fresh presubmit for it...

2021-06-25 16:59 UTC, closed without merging