refactor(common): change missing NgSwitch provider error message
angular/angular pull request #41704
Opened 2021-04-19 14:35 UTC by stefanoww

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
It's change error message throw when using NgSwitchDefault and NgSwitchCase outisde of NgSwitch

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Old message was not enough descriptive e.g. : "No provider for NgSwitch found in NodeInjector"

Issue Number: N/A
 #41591

## What is the new behavior?
Currently following error message is displayed: "NgSwitchDefault must be inside NgSwitch"

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2021-04-19 14:36 UTC, va-stefanek commented
@googlebot I consent.

2021-04-19 15:47 UTC, petebacondarwin commented on packages/common/src/directives/ng_switch.ts
> +    }
I don't think we need to test for `ngSwitch` in production mode. It will just fail when we try to call `_addCase()`.

Also, I don't believe we need `_view` to be optional, since if `ngSwitch` is not valid this whole class will never complete instantiation.

```suggestion
if ((typeof ngDevMode === 'undefined' || ngDevMode) && isDevMode()) {
  if (!ngSwitch) {
    throwNgSwitchProviderNotFoundError('NgSwitchCase');
  }
}
ngSwitch._addCase();
this._view = new SwitchView(viewContainer, templateRef);
```

2021-04-19 21:09 UTC, stefanoww commented on packages/common/src/directives/ng_switch.ts
> +    }
Thanks, I have change code according to your recommendations.

2021-04-19 21:41 UTC, AndrewKushnir requested changes
@stefanoww thanks for improving developer experience by providing more detailed error message! 👍 

I've left a couple comments and also I think we'd need to add some tests to cover newly added behavior. You can add tests in the [ng_switch_spec.ts](packages/common/test/directives/ng_switch_spec.ts) file.

Thank you.

2021-04-19 21:41 UTC, AndrewKushnir commented on packages/common/src/directives/ng_switch.ts
> +      RuntimeErrorCode.PROVIDER_NOT_FOUND, `${directiveName} must be inside NgSwitch`);
While the problem was caused by the missing provider in the code, the original error is coming from the fact that elements in the template were not configured properly. Reusing the `PROVIDER_NOT_FOUND` would result in the following link added to the error message: https://angular.io/errors/NG0201 and that page talks about missing providers/tokens and might be confusing to developers.

I think we should probably create a new error code and provide more descriptive error message (and refer to attribute names (that developer used in a template) vs having directive class names (which might be confusing since a user would not reference/use them anywhere to get the error)):

```suggestion
function throwNgSwitchProviderNotFoundError(attrName: string, directiveName: string): never {
  throw new RuntimeError(
      RuntimeErrorCode.TEMPLATE_STRUCTURE_ERROR, `An element with the "${attrName}" attribute ` +
        `(matching the "${directiveName}" directive) must be located inside an element with the "ngSwitch" attribute ` +
        `(matching "NgSwitch" directive)`);
```

The error can be added here (as a part of the "Template errors" section):
https://github.com/angular/angular/blob/master/packages/core/src/render3/error_code.ts#L24-L29

@stefanoww @petebacondarwin what do you think?

2021-04-19 21:41 UTC, AndrewKushnir commented on packages/common/src/directives/ng_switch.ts
> +    if ((typeof ngDevMode === 'undefined' || ngDevMode) && isDevMode() && !ngSwitch) {
My understanding is that the `isDevMode()` is not required, since it's essentially a ViewEngine-only version of the `ngDevMode` flag (which is also supported in ViewEngine):
```suggestion
    if ((typeof ngDevMode === 'undefined' || ngDevMode) && !ngSwitch) {
```
The only delta is that the `ngDevMode` would be undefined for apps built with ViewEngine without using Angular CLI (i.e. some custom build setup).

2021-04-20 20:55 UTC, stefanoww commented on packages/common/src/directives/ng_switch.ts
> +      RuntimeErrorCode.PROVIDER_NOT_FOUND, `${directiveName} must be inside NgSwitch`);
Yeah, I totally agree with you. I was mostly confused with that part, whether should I reuse the error code and where should I put that part. Thanks for your review :)

2021-04-21 16:26 UTC, IgorMinar commented on packages/common/src/directives/ng_switch.ts
> +    if ((typeof ngDevMode === 'undefined' || ngDevMode) && isDevMode() && !ngSwitch) {
@AndrewKushnir you are right. The `isDevMode()` should not be used here as it will break tree-shaking and cause the diagnostic error to be retained in the production code - rendering the `(typeof ngDevMode === 'undefined' || ngDevMode)` check useless.

The only time when `isDevMode()` should be used is for code that we can't tree-shake anyway AND it is too expensive to run that code in production. The only great example of this I can think of right now is the second change detection pass in dev mode to surface `ExpressionChangedAfterItHasBeenCheckedError`.

2021-04-22 08:23 UTC, petebacondarwin requested changes
Great work @stefanoww - just an issue with the `RuntimeError` imports to resolve. @AndrewKushnir might have a view on how best to do this.

2021-04-22 08:23 UTC, petebacondarwin commented on packages/common/src/directives/ng_switch.ts
> +import {RuntimeError, RuntimeErrorCode} from '../../../core/src/render3/error_code';
This import is not correct. We cannot deep import into core from here.
I believe that using `RuntimeError` outside core is unprecedented, and I note that it is stored in the `render3` directory. I don't think this would matter in terms of View Engine, but I guess we need to export these two items "privately" from core to access them here.

2021-04-22 08:55 UTC, stefanoww commented on packages/common/src/directives/ng_switch.ts
> +import {RuntimeError, RuntimeErrorCode} from '../../../core/src/render3/error_code';
I also can take care of that if you have some proposal or existing example how to do it.

2021-04-28 01:38 UTC, AndrewKushnir commented on packages/common/src/directives/ng_switch.ts
> +import {RuntimeError, RuntimeErrorCode} from '../../../core/src/render3/error_code';
@stefanoww Pete's proposal looks good, you can export `RuntimeError` and `RuntimeErrorCode` symbols using [packages/core/src/core_private_export.ts](https://github.com/angular/angular/blob/master/packages/core/src/core_private_export.ts) like this:

```
export {RuntimeError as ɵRuntimeError, RuntimeErrorCode as ɵRuntimeErrorCode} from './render3/error_code';
```

which should make them available via `@angular/core` import (which you can use in the `common` package code):

```
import {ɵRuntimeError as RuntimeError, RuntimeErrorCode as ɵRuntimeErrorCode} from '@angular/core';
```

Please let us know if any additional information is needed.

2021-05-04 11:05 UTC, stefanoww commented on packages/common/src/directives/ng_switch.ts
> +import {RuntimeError, RuntimeErrorCode} from '../../../core/src/render3/error_code';
No, it's clear. Today I will add changes.

2021-05-05 08:25 UTC, stefanoww commented
@AndrewKushnir I have added private import.
I have some problem with the test, I can not run it locally. However I start's them they don't run: 

1. Using Web Storm and Karma runner - In this case, chrome opens and than nothing happens. Test doesn't execute.
2. Using script from the package.json - Here I get following error: "Failed at the angular-srcs@12.1.0-next.0 test-ivy-aot script."
3. Using commands from [developer documentation](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md) - Here I get error that "Build did NOT complete successfully", but all of them got "NO STATUS". It happens with test command, when I run build all is fine.

2021-05-05 10:01 UTC, petebacondarwin commented
@stefanoww you probably do not need to run all the possible tests locally.
You can see from the CI jobs that `//packages/common/test:test` is failing. So I would start there.
In most setups (Windows users sometimes have issues) you should be able to run:

```bash
yarn bazel test //packages/common/test:test
```

Try that.

2021-05-05 10:23 UTC, stefanoww commented
> @stefanoww you probably do not need to run all the possible tests locally.
> You can see from the CI jobs that `//packages/common/test:test` is failing. So I would start there.
> In most setups (Windows users sometimes have issues) you should be able to run:
> 
> ```shell
> yarn bazel test //packages/common/test:test
> ```
> 
> Try that.

Thanks, that helped! Now I was able to fix the tests. Last with to clarify is whether I should use `formatRuntimeError` method to properly assert error message or hardcoded as it is now is fine?

2021-05-05 13:47 UTC, petebacondarwin approved these changes
A small NIT about formatting the error message string.

You don't need to worry about calling `formatRuntimeError()` since this is done inside the `RuntimeError` constructor for you already.

2021-05-05 13:47 UTC, petebacondarwin commented on packages/common/src/directives/ng_switch.ts
> +          `(matching "NgSwitch" directive)`);
If you are going to split up this string to make it format better then you might as well go with something like:

```suggestion
      `An element with the "${attrName}" attribute ` +
          `(matching the "${directiveName}" directive) ` +
          `must be located inside an element with the "ngSwitch" attribute ` +
          `(matching "NgSwitch" directive)`);
```

2021-05-05 17:42 UTC, AndrewKushnir approved these changes
LGTM, thank you 👍

2021-05-05 17:44 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:372158800:BASE:372158820:1620236640533:a21d3ba8).

2021-05-06 19:44 UTC, closed without merging