fix(docs-infra): fix `autoLinkCode` Dgeni post-processor
angular/angular pull request #41709
Opened 2021-04-19 20:28 UTC by gkalpak

A couple of fixes related to auto-linking `<code>` elements in the docs.
(See individual commits for details.)

2021-04-19 20:38 UTC, mary-poppins commented
You can preview 38128e3 at https://pr41709-38128e3.ngbuilds.io/.

2021-04-20 09:44 UTC, petebacondarwin requested changes
Can you look into skipping the whole generated tree instead of patching the text node?

2021-04-20 09:44 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +
I think we can do this without adding properties to the nodes...
In the case where we call `getNodes()` I think we can indicate to the `visit()` that we do not want to recurse into the text further. See https://github.com/syntax-tree/unist-util-visit-parents#next--visitornode-ancestors. I think we could do something like:


```ts
} else {
            // Parse the text for words that we can convert to links
            const nodes = getNodes(node, file);
            // Replace the text node with the links and leftover text nodes
            Array.prototype.splice.apply(parent.children, [index, 1].concat(nodes));
            return [SKIP, index+1];
          }
```

2021-04-24 08:01 UTC, mary-poppins commented
You can preview fe37001 at https://pr41709-fe37001.ngbuilds.io/.

2021-04-24 08:09 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/post-processors/auto-link-code.js
> +
I added a fixup commit. PTAL

2021-04-24 09:48 UTC, petebacondarwin approved these changes
LGTM! Nice fixes

2021-04-26 16:31 UTC, mary-poppins commented
You can preview 7ca4b6f at https://pr41709-7ca4b6f.ngbuilds.io/.

2021-04-26 17:58 UTC, jessicajaniuk commented
@gkalpak This PR has merge conflicts with `11.2.x`. It's been merged into `master` and `12.0.x`. Can you create a patch CL targeting `11.2.x`?

2021-04-26 17:59 UTC, closed without merging

2021-04-28 12:44 UTC, gkalpak commented
For reference, here is the PR for patch: #41854