test(common): synchronise location mock behavior with the navigators
angular/angular pull request #41730
Opened 2021-04-20 16:53 UTC by aahmedayed

do not emit event for imperative navigation.
emit a `popstate` event before each `hashchange` to have the same
behavior of the `history API`.

BREAKING CHANGE:

After this change we should not use location.go to test an imperative navigation, we
have to use route.navigate or route.navigateByUrl methods.
`popstate` will be emitted before each `hashchange` event. We'll need to
remove all `simulateUrlPop` called before `simulateHashChange` in the
spec files.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## Other information

2021-04-20 16:56 UTC, aahmedayed commented
Hi, this is related to #41730

2021-04-20 17:32 UTC, atscott requested changes
Consider adding "fixes #27059" to the commit message and address the `normalize` and `path` inconsistencies as well.

Also, I would propose changing the commit message to:

```
fix(common): align `SpyLocation` behavior with real `Location`

* `location.go` is a wrapper around `pushState`. Calling `history.pushState` does not trigger the `popstate` nor the `hashchange` event in browsers.
* [other changes as bullet points as well]


BREAKING CHANGE:
* Previously, the `SpyLocation` used in tests would simulate an event when calling `location.go`. However, this is different from actual behavior in browsers when the real `Location` class is used (no event is fired in this case). This change aligns the behavior of the location mock with what can be observed in the browser during runtime. Tests will need to be updated to account for this. When testing the router behavior, navigations should be triggered through `router.navigate` and `router.navigateByUrl` rather than `location.go`.
* In addition, the `SpyLocation` emits both a `popstate` and `hashchange` event when calling `simulateHashChange` as would happen in the browser at runtime. Tests may need to be adjusted to account for this change as well.
```

2021-04-20 17:32 UTC, atscott commented on packages/common/testing/src/location_mock.ts
> -    this._subject.emit({'url': url, 'pop': false});
I believe this should be replaced with a call to `notifyUrlChangeListeners`:

https://github.com/angular/angular/blob/73824d53371f054b1c3277fbdb0481074a36b710/packages/common/src/location/location.ts#L158-L160

That should be done in `replaceState` as well

2021-04-20 17:32 UTC, atscott commented on packages/common/testing/src/location_mock.ts
> +    this._subject.emit({'url': pathname, 'pop': true, 'type': 'popstate'});
```suggestion
    this.simulateUrlPop(pathname);
```

2021-05-06 21:20 UTC, atscott submitted a review, later dismissed
Oh, the commit message should also be `fix(common)` rather than `test(common)`. A bit confusing, but this is for testing infrastructure, not just an update to an internal test so it's public facing and should be marked as a fix to the mock behavior.

2021-08-04 02:12 UTC, aahmedayed commented
@googlebot I consent.

2021-08-04 03:57 UTC, aahmedayed commented
Hi @atscott, I'm not sure but I think we can remove the `RouterSpyLocation` class of `computed_state_restoration.spec.ts` in this PR. What do you think ?

2021-08-04 04:08 UTC, atscott commented
@aahmedayed yes, that’s right. We could remove that one with this PR

2021-08-04 06:06 UTC, aahmedayed commented
@atscott I did it. I also added `'type': 'popstate'` to the emitted value in `forward` and `back` methods of `SpyLocation`.

2021-08-31 15:29 UTC, atscott commented
green [global presubmit](https://fusion2.corp.google.com/presubmit/tap/393461713/OCL:393461713:BASE:394002091:1630422106141:2eae9f90/targets) after resolving issues in g3.

2021-08-31 19:20 UTC, AndrewKushnir reviewed
Looks great, just left some comments around possible edge cases. Thank you.

2021-08-31 19:20 UTC, AndrewKushnir commented on packages/common/testing/src/location_mock.ts
> +function _stripIndexHtml(url: string): string {
It's be great to add a comment here to explain why we strip `index.html`. We do remove the `index.html` once there is nothing else at the end of the URL string, it'd be great to include that into the doc (why we do that).

Also we can probably add tests for cases like `http://domain-a.com?goto=http://domain-b.com/index.html` to verify that we do not remove `index.html` if it's in the GET params part of the URL.

2021-08-31 19:20 UTC, AndrewKushnir commented on packages/common/testing/src/location_mock.ts
> +function _stripBaseHref(baseHref: string, url: string): string {
Is it possible to have a situation here when `baseHref` is something like `abc` and the `url` starts with it, but it's not a full section of the URL (for ex. `abc-domain.com`)?

2021-08-31 19:20 UTC, AndrewKushnir commented on packages/common/testing/src/location_mock.ts
> +    this.pushHistory(path, query, state);
👍

2021-08-31 19:42 UTC, atscott commented on packages/common/testing/src/location_mock.ts
> +function _stripIndexHtml(url: string): string {
This is only here to match the behavior of the actual `Location`: https://github.com/angular/angular/blob/dcfabf08afd888dcc891900c883910ab35efb8eb/packages/common/src/location/location.ts#L127

I'd be more inclined to remove this addition than attempt to explain the decisions made there, which may or may not be correct (see #19296). To my knowledge, nobody uses `Location.normalize` in tests anyways; they can't because it just returns `null`.

We can either export `stripIndexHtml` and `stripBaseHref` from `location.ts` and use them here or just revert this part of the change. WDYT?

2021-08-31 19:45 UTC, atscott commented on packages/common/testing/src/location_mock.ts
> +    this.pushHistory(path, '', null);
`Location.go` uses the path later in the function implementation. `pushHistory` would then have to return the path created by `prepareExternalUrl`. I don't have any strong feelings either way so I'll let you make the call.

2021-08-31 20:13 UTC, AndrewKushnir commented on packages/common/testing/src/location_mock.ts
> +    this.pushHistory(path, '', null);
Good point, I'm ok keeping it like it's currently implemented. Since it's a part of the testing logic, it has no impact on bundle size, so this optimization is not important.

2021-08-31 21:25 UTC, AndrewKushnir approved these changes
@atscott thanks for addressing comments 👍

2021-09-01 16:02 UTC, atscott approved these changes
reviewed-for: fw-router

2021-09-01 20:50 UTC, atscott commented
[another global presubmit](https://test.corp.google.com/ui#id=OCL:394010119:BASE:394276650:1630521063172:1d9d7415) for sanity. Looks good to go.

2021-09-01 20:51 UTC, atscott commented
caretaker note: merge and sync on its own. This is a test-only change so there's no risk of breaking any production code but it would be nice to have the change on its own nevertheless

2021-09-02 16:53 UTC, closed without merging