Docs infra: ambiguous letter-casing doc filenames
angular/angular pull request #41788
Opened 2021-04-23 15:18 UTC by petebacondarwin

The motivation for this PR is actually to support upgrading AIO to Angular CLI v12 (and so Webpack 5).

2021-04-23 15:21 UTC, petebacondarwin commented
Although this PR will result in some URL changes, the original URLs should land on the disambiguation page leading the reader to the correct place anyway.

2021-04-23 15:28 UTC, mary-poppins commented
You can preview dcfb22d at https://pr41788-dcfb22d.ngbuilds.io/.

2021-04-23 15:48 UTC, mary-poppins commented
You can preview 39ca413 at https://pr41788-39ca413.ngbuilds.io/.

2021-04-23 16:06 UTC, atscott approved these changes

2021-04-23 16:06 UTC, atscott commented on aio/tools/transforms/templates/disambiguator.template.html
> +{% endblock %}
I'm not familiar with the docs infrastructure. Can you link to an example where this is shown?

2021-04-23 16:12 UTC, petebacondarwin commented on aio/tools/transforms/templates/disambiguator.template.html
> +{% endblock %}
Here you go: https://pr41788-39ca413.ngbuilds.io/api/core/injector

2021-04-23 16:12 UTC, petebacondarwin commented on aio/tools/transforms/templates/disambiguator.template.html
> +{% endblock %}
<img width="775" alt="Screenshot 2021-04-23 at 17 12 25" src="https://user-images.githubusercontent.com/15655/115899793-18cb0380-a457-11eb-9284-0566110ed604.png">

2021-04-23 16:21 UTC, mary-poppins commented
You can preview 852e97c at https://pr41788-852e97c.ngbuilds.io/.

2021-04-24 07:42 UTC, gkalpak requested changes
Awesome work! (You make look too easy, which is demotivating :stuck_out_tongue:)

One comment:
We could improve how the disambiguation pages show up in search results: 
![disambiguation-search](https://user-images.githubusercontent.com/8604205/115951430-5d06e400-a4e9-11eb-94f0-80daf8e4d708.png)

Ideally we should not show them at all (but that might be a bigger change). Maybe we could at least give them a [label + symbol][1] :grin:

Commit message typos:
  - `initlalized` --> `initialized` (in the first commit)
  - `ambigous` --> `ambiguous` (in the second and third commits)

[1]: https://github.com/angular/angular/blob/73105aa7d6cf1116a6a9f103bd074f65db7584fe/aio/src/styles/_constants.scss#L69-L127

2021-04-24 07:42 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.js
> +      for(const doc of docs) {
```suggestion
      for (const doc of docs) {
```

2021-04-24 07:42 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.js
> +      // and update the ambigous docs to have unique `path` and `outputPath` properties.
```suggestion
      // and update the ambiguous docs to have unique `path` and `outputPath` properties.
```

2021-04-24 07:42 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.js
> +      for(const outputPath of ambiguousDocMap.keys()) {
```suggestion
      for (const outputPath of ambiguousDocMap.keys()) {
```

You could also use the entries directly (and not have to retrieve the value):

```suggestion
      for (const [outputPath, ambiguousDocs] of ambiguousDocMap) {
```

2021-04-24 07:42 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.js
> +        for(const doc of ambiguousDocs) {
```suggestion
        for (const doc of ambiguousDocs) {
```

2021-04-24 07:42 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.js
> +  return outputPath.replace(/(\.[^.]*)?$/, `-${count}$1`).toLowerCase();
Thought: Would it be better to not use `toLowerCase()` (and thus keep the casing (for browsers and case-sensitive OSes)?

```suggestion
  return outputPath.replace(/(\.[^.]*)?$/, `-${count}$1`);
```

2021-04-24 07:42 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.spec.js
> +  beforeEach(function() {
You forgot the `=>` and there seems to be some stray random string (`function`) before the `()`.
(Strange that the JS parser didn't complain 😛)

2021-04-24 07:42 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.spec.js
> +    expect(docs[docs.length-2]).toEqual({
```suggestion
    expect(docs[docs.length - 2]).toEqual({
```

😇

2021-04-24 07:42 UTC, gkalpak commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.spec.js
> +    expect(docs[docs.length-1]).toEqual({
```suggestion
    expect(docs[docs.length - 1]).toEqual({
```

😇

2021-04-24 09:26 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.js
> +      for(const doc of docs) {
We really need to get doc-formatting up and running for the doc-gen code.

2021-04-24 09:26 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.js
> +      // and update the ambigous docs to have unique `path` and `outputPath` properties.
and spell checking :-)

2021-04-24 09:30 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.js
> +  return outputPath.replace(/(\.[^.]*)?$/, `-${count}$1`).toLowerCase();
Yeah - we can try that.

2021-04-24 09:53 UTC, mary-poppins commented
You can preview 887cbb3 at https://pr41788-887cbb3.ngbuilds.io/.

2021-04-24 10:02 UTC, petebacondarwin commented
The disambiguator pages are gone from the search.

https://pr41788-887cbb3.ngbuilds.io/?search=inject

2021-04-24 10:36 UTC, mary-poppins commented
You can preview 80eed49 at https://pr41788-80eed49.ngbuilds.io/.

2021-04-24 10:52 UTC, gkalpak approved these changes
:100: 🚀 🏆 

(BTW, there is still an `ambigous` occurrence in the third (non-fixup) commit.)

2021-04-24 13:33 UTC, mary-poppins commented
You can preview 61c1da1 at https://pr41788-61c1da1.ngbuilds.io/.

2021-04-26 15:33 UTC, jelbourn approved these changes
LGTM

Reviewed-for: docs-packaging-and-releasing

2021-04-26 15:33 UTC, jelbourn commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.js
> + * are disambiguated.
Could you expand this comment with an example of a case that would require disambiguation?

2021-04-26 16:13 UTC, petebacondarwin commented on aio/tools/transforms/angular-base-package/processors/disambiguateDocPaths.js
> + * are disambiguated.
Will do! Thanks for the review @jelbourn

2021-04-26 16:38 UTC, atscott approved these changes
reviewed-for: public-api

2021-04-26 16:43 UTC, mary-poppins commented
You can preview 65b24bc at https://pr41788-65b24bc.ngbuilds.io/.

2021-04-26 16:50 UTC, jelbourn approved these changes
LGTM

Reviewed-for: public-api

2021-04-26 18:08 UTC, jessicajaniuk approved these changes
LGTM :cookie:

reviewed-for: public-api

2021-04-26 19:12 UTC, closed without merging