fix(docs-infra): fix external link icons positioning
angular/angular pull request #41794
Opened 2021-04-24 09:12 UTC by gkalpak

While trying to fix the appearance of `<code>` elements inside of anchors with external URLs in #41694, the positioning of external link icons was broken for anchors that would span multiple lines (see #41774 for details).

This commit fixes the positioning of external link icons, while still preserving the correct appearance of `<code>` elements inside anchors with external URLs.

NOTE:
Different types of links with external URLs can be seen in the following docs sections:
- http://localhost:4200/docs#assumptions
- http://localhost:4200/guide/http#security-xsrf-protection
- http://localhost:4200/guide/workspace-config#generation-schematics

Fixes #41774.

2021-04-24 09:23 UTC, mary-poppins commented
You can preview a8b5588 at https://pr41794-a8b5588.ngbuilds.io/.

2021-04-25 20:26 UTC, petebacondarwin requested changes

2021-04-25 20:26 UTC, petebacondarwin commented on aio/src/styles/0-base/_typography.scss
> +          display: inline-flex;
Rather than using inline-flex here, which causes the whole like to be on one line.
Can't we just change the position of the `open_in_new` icon to be relative?
I think that we can then also remove the following `padding-right` line, and not need the additional styling in `_code.scss`.

But I might be missing something?

2021-04-26 08:24 UTC, gkalpak commented on aio/src/styles/0-base/_typography.scss
> +          display: inline-flex;
With relative positioning, the icons get underlines on hover (which is what was fixed with 7944ee2c30c1f09219e152a4a1b2c5e51dd2c9c4). I couldn't find any other style combination that checked all boxes :grin:

2021-04-26 09:48 UTC, petebacondarwin commented on aio/src/styles/0-base/_typography.scss
> +          display: inline-flex;
I see what you mean. Oh well.

2021-04-26 09:49 UTC, petebacondarwin approved these changes

2021-04-26 16:24 UTC, closed without merging