fix(zone.js): only one listener should also throw an error
angular/angular pull request #41868
Opened 2021-04-29 01:09 UTC by JiaLiPassion

Close #41867

In the previous commit https://github.com/angular/angular/pull/41562#issuecomment-822696973,
the error thrown in the event listener will be caught and re-thrown, but there is a bug
in the commit, if there is only one listener for the specified event name, the error
will not be re-thrown, so this commit fixes the issue and make sure the error is re-thrown.

2021-04-29 18:31 UTC, jessicajaniuk commented
There seems to be a few legit failures in Google3 related to this change where we see this:

`Error: Uncaught (in promise): Object: {"error":"unexpected error"}`
and
`Error: Uncaught (in promise): TypeError: Cannot read property 'pipe' of undefined`

2021-04-30 01:59 UTC, JiaLiPassion commented
@jessicajaniuk, I updated the PR and keep the behavior compatible, could you re-run the presubmit? Thank you.

2021-04-30 19:31 UTC, jessicajaniuk commented
@JiaLiPassion We're unfortunately still seeing the exact same failing tests.

2021-04-30 22:23 UTC, jessicajaniuk commented
@JiaLiPassion I'll try to put a stackblitz together for you to see an example of the tests.

2021-04-30 22:37 UTC, JiaLiPassion commented
@jessicajaniuk , got it, thank you!

2021-05-03 17:24 UTC, br-star commented
Hi folks, how is the progress going on this?

2021-05-03 19:41 UTC, jessicajaniuk commented
@br-star We're seeing issues within Google3 with this change. So it's still being iterated on. There's also a big timezone difference between contributors. So we thank you for your patience.

2021-05-18 17:17 UTC, br-star commented
Any update? We're having to manually cherrypick the revert CL to our rapid prod branch as a workaround.

2021-05-18 17:33 UTC, jessicajaniuk commented
We talked off github, but just for visibility, @br-star is going to create a stackblitz for this issue.

2021-05-21 23:11 UTC, AndrewKushnir reviewed
Thanks for the fix @JiaLiPassion. I've left a couple comments, could you please have a look when you get a chance?

We are also investigating the issues in Google's codebase related to this fix (it looks like some errors where not re-thrown and silently ignored) and will share more info soon.

2021-05-21 23:11 UTC, AndrewKushnir commented on packages/zone.js/lib/common/events.ts
> +      if (errors.length === 1) {
@JiaLiPassion could you please add a comment here to explain why we special-case this situation (I believe it's for performance reasons)?

2021-05-21 23:11 UTC, AndrewKushnir commented on packages/zone.js/lib/common/events.ts
> +        const err = invokeTask(tasks[0], target, event);
nit: could you plz add return type to the `invokeTask` function? It's not directly related to this PR, but it'd just be a bit easier to review in case the `invokeTask` return type is clear (to assess whether any specific checks are needed for the line below or it's enough to check that the value if truthy).

2021-05-22 12:10 UTC, petebacondarwin requested changes
Reviewed-for: size-tracking

2021-05-22 12:10 UTC, petebacondarwin commented on packages/zone.js/lib/common/events.ts
> +        const err = invokeTask(tasks[0], target, event);
Is this actually relevant to this bug?
It seems to me that this PR has two parts:

1) Fixing the bug which is when there is only one task, and that task has a error, we were not throwing the error.
2) Speeding up the case where there are multiple tasks but only one of them has an error.

Is the second part actually necessary? I think the code could be smaller without this performance change.

2021-06-01 23:43 UTC, alxhub approved these changes
This LGTM as a fix, though I second @AndrewKushnir's desire for some additional type info within the larger system here.

2021-06-02 00:09 UTC, JiaLiPassion commented on packages/zone.js/lib/common/events.ts
> +      if (errors.length === 1) {
Got it, I just added the comment, since there is only one error, we don't need to `scheduleMicroTask` to throw it.

2021-06-02 00:13 UTC, JiaLiPassion commented on packages/zone.js/lib/common/events.ts
> +        const err = invokeTask(tasks[0], target, event);
@AndrewKushnir, got it, I added the type information here.
@petebacondarwin , yes, you are right, the 2nd is to improve the performance. I will try to do refactor in the other PR to make the `event handling` part more smaller (not only this part)

2021-06-09 21:21 UTC, AndrewKushnir commented
Getting ready for landing this PR:

- cleanup in Google's codebase is nearing completion
- I've rebased this PR to rerun CI
- [new presubmit](http://test/OCL:374925847:BASE:378497586:1623273592626:b660c843) was also started and I'll run a global one tonight as well

Thank you.

2021-06-09 21:22 UTC, AndrewKushnir approved these changes
Reviewed-for: size-tracking

2021-06-10 15:46 UTC, petebacondarwin approved these changes
Reviewed-for: size-tracking

2021-06-10 16:13 UTC, jessicajaniuk approved these changes
LGTM :cookie:

Thanks, @JiaLiPassion, for your work on this.

reviewed-for: size-tracking

2021-06-10 16:24 UTC, closed without merging

2021-06-10 19:32 UTC, AndrewKushnir commented
Just a quick comment as a wrap up: this change was merged and synced into Google's codebase. Google's codebase required a sizable amount of cleanup work since the change that introduced the problem became available in g3 immediately after the sync (on Apr 21), thus there was a number of regressed targets. This problem does **not** seem to affect users externally since the latest ZoneJS package release (0.11.4) happened mid Feb, so the code that had the bug was not released publicly yet and the next ZoneJS release will have the fix as well.