feat(compiler): support safe keyed read expressions
angular/angular pull request #41911
Opened 2021-05-01 12:21 UTC by crisbeto

Currently we support safe property (`a?.b`) and method (`a?.b()`) accesses, but we don't handle safe keyed reads (`a?.[0]`) which is inconsistent. These changes expand the compiler in order to support safe key read expressions as well.

2021-05-03 18:27 UTC, AndrewKushnir approved these changes
@crisbeto thanks for the changes 👍 I've just added a couple minor comments related to extra test cases.

Reviewed-for: fw-core

2021-05-03 18:27 UTC, AndrewKushnir commented on packages/compiler/test/expression_parser/parser_spec.ts
> +        checkAction('this.a?.["a"]', 'a?.["a"]');
Could you plz add a case with nested reads like this:
```
this.a?.[this.b?.["a"] ?? 'a']
```

2021-05-03 18:27 UTC, AndrewKushnir commented on packages/core/test/acceptance/integration_spec.ts
> +        You are a Balrog: {{ species?.[0]?.[1]?.[2]?.[3]?.[4]?.[5] || 'unknown' }}
I'd propose adding a couple cases:
- nested reads: `species?.[keys?.[0] ?? 'key']`
- with string-based keys: ``species?.['key']`

2021-05-04 18:24 UTC, JoostK reviewed
This looks pretty good. I left some comments and a request to add tests for the Ivy language service in `packages/language-service/ivy/test/legacy/template_target_spec.ts`.

2021-05-04 18:24 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/test/diagnostics_spec.ts
> +            diagnose(`<div [class.red-text]="person.favoriteColors?.[0] === 'red'"></div>`, `
It's funny you choose a class binding here, I believe those aren't currently type-checked at all.

2021-05-04 18:24 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/test/diagnostics_spec.ts
> +      it('does not produce diagnostic for safe keyed access', () => {
Can we also have a case that does report an error? e.g. calling a method that takes a non-nullable arg but called with an argument that contains an optional chain, to see its type is `X | undefined`.

2021-05-04 18:24 UTC, JoostK commented on packages/compiler-cli/test/compliance/test_cases/r3_view_compiler/safe_access/GOLDEN_PARTIAL.js
> +MyApp.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "12.0.0", version: "0.0.0-PLACEHOLDER", type: MyApp, selector: "ng-component", ngImport: i0, template: `
This raises the question: should we bump the `minVersion` for this change to `12.1.0`? Maybe only if the new syntax is actually used? Older versions of Angular would fail to parse the template. We discussed some of these scenarios when `minVersion` was introduced; @alxhub can probably weigh in here as to how we want to approach this.

2021-05-04 18:28 UTC, crisbeto commented on packages/compiler-cli/src/ngtsc/typecheck/test/diagnostics_spec.ts
> +            diagnose(`<div [class.red-text]="person.favoriteColors?.[0] === 'red'"></div>`, `
I just copied it over from another test, but it did actually flag that the `favoriteColors` can be undefined.

2021-05-04 18:29 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/test/diagnostics_spec.ts
> +            diagnose(`<div [class.red-text]="person.favoriteColors?.[0] === 'red'"></div>`, `
Maybe I'm wrong then!

2021-05-04 18:33 UTC, petebacondarwin commented on packages/compiler-cli/test/compliance/test_cases/r3_view_compiler/safe_access/GOLDEN_PARTIAL.js
> +MyApp.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "12.0.0", version: "0.0.0-PLACEHOLDER", type: MyApp, selector: "ng-component", ngImport: i0, template: `
I don't think, in this case, we need to bump minVersion since we are not event at 12.0.0 yet :-)

But good spot @JoostK - this is the kind of thing we need to watch out for, going forward.

2021-05-04 18:35 UTC, JoostK commented on packages/compiler-cli/test/compliance/test_cases/r3_view_compiler/safe_access/GOLDEN_PARTIAL.js
> +MyApp.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "12.0.0", version: "0.0.0-PLACEHOLDER", type: MyApp, selector: "ng-component", ngImport: i0, template: `
But this will only release in 12.1.0 at the earliest!

2021-05-04 18:44 UTC, petebacondarwin commented on packages/compiler-cli/test/compliance/test_cases/r3_view_compiler/safe_access/GOLDEN_PARTIAL.js
> +MyApp.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "12.0.0", version: "0.0.0-PLACEHOLDER", type: MyApp, selector: "ng-component", ngImport: i0, template: `
Ah yes, I didn't notice that this is a feature that won't make 12.0.0.

In that case, I definitely think we definitely need to bump the `minVersion`.
The question therefore is really, whether we should hold off such "minor" features to major releases.

2021-05-04 19:05 UTC, Toledochrist commented
Thanks

2021-05-05 19:20 UTC, JoostK commented on packages/compiler/src/expression_parser/parser.ts
> +    let result: AST|undefined;
Good point, I missed that. `withContext` returns its inner result though, so you could still achieve it by moving the `EmptyExpr` fallback into the closure as well.

2021-05-05 20:58 UTC, crisbeto commented
All of the feedback has been addressed.

2021-05-06 23:34 UTC, Toledochrist approved these changes

2021-05-07 18:23 UTC, JoostK commented on packages/compiler-cli/test/compliance/test_cases/r3_view_compiler/safe_access/safe_keyed_read_template.js
> +    i0.ɵɵproperty("title", "Your last name is " + ((ctx.unknownNames == null ? null : ctx.unknownNames[0]) || "unknown"));
In light of #34385, what do we want to do about using `null` vs `undefined` here? The TS39 spec uses `undefined` and Angular has historically used `null` as optional value. If we do intend to align with the TC39 behavior, do we want to let `?.` use `undefined` immediately, or change it later across the board?

2021-05-07 18:23 UTC, JoostK commented on packages/compiler/test/expression_parser/parser_spec.ts
> +        checkAction('this.a?.["a"]', 'a?.["a"]');
I'm not sure what's going on there. Maybe a bug in the expression printer that's used in the test?

2021-05-07 18:40 UTC, crisbeto commented on packages/compiler-cli/test/compliance/test_cases/r3_view_compiler/safe_access/safe_keyed_read_template.js
> +    i0.ɵɵproperty("title", "Your last name is " + ((ctx.unknownNames == null ? null : ctx.unknownNames[0]) || "unknown"));
Just to capture what we discussed in DM: I decided to align the behavior to our current behavior for safe property reads, rather than the TC39 behavior in order to maintain consistency with the existing code and to reuse our existing logic. I think that we should tackle this across the board as a part of #34385.

2021-05-07 18:42 UTC, JoostK approved these changes

2021-05-13 20:44 UTC, AndrewKushnir commented
@crisbeto once again, thanks a lot for these changes, this is a great thing to support in expressions! 👍 

I'm curious if it might be straightforward to also add optional chaining with function calls (as a followup PR, following the changes from this one), like `someObj.method?.()`. If we need to bump a compiler version and/or do any other checks for libraries, we can just do that for both changes at the same time. If it's not an easy change - no worries, we can do that later!

2021-05-13 20:46 UTC, crisbeto commented
From what I could tell, we already support safe function calls.

2021-05-13 20:50 UTC, JoostK commented
> From what I could tell, we already support safe function calls.

Those may actually only be `someObj?.method()`, which is a `SafeMethodCall` in the AST (we're not treating the safe property read as the receiver of a call expression, but rather the whole call expression is specialised for the `?.` syntax). So it could be that Andrew's point is valid.

2021-05-13 20:54 UTC, crisbeto commented
For reference, I'm talking about these tests: https://github.com/angular/angular/blob/master/packages/compiler/test/expression_parser/parser_spec.ts#L371

From an AST standpoint, would it be weird to classify `someObj?.method()` as a safe method call? I believe that under the TS AST that would be a safe property access expression.

2021-05-13 21:02 UTC, JoostK commented
> From an AST standpoint, wouldn't it be weird to classify `someObj?.method()` as a safe method call? I believe that under the TS AST that would be a safe property access expression.

Yes, our AST is weird. I don't actually know why we're treating it as a special AST node. We have the same weirdness around `FunctionCall` vs `MethodCall`, where the latter has a property access receiver.

2021-05-20 15:22 UTC, tehpsalmist commented
Just as a suggestion, it might be a good idea to include `[a]?.[b]` as a test case for the functionality, too. Thanks to everyone involved!

2021-05-21 16:32 UTC, crisbeto commented
Marking this as ready for presubmit and merge, based on our discussion.

2021-05-21 17:18 UTC, JoostK commented
@crisbeto didn't we want to keep `minVersion` at 12.0.0 if the syntax is not used?

2021-05-21 17:33 UTC, petebacondarwin commented
The plan is to land this and add the minVersion calculations ASAP before 12.1.0 is released

2021-05-21 17:44 UTC, crisbeto commented
@petebacondarwin just to double-check: should I keep the changes to the `minVersion` here? https://github.com/angular/angular/pull/41911/files#diff-cf1b6ab0cb8378b511b1930cd9def496e3f238504d3f28168ae7a97a457f8047L110

2021-05-21 18:47 UTC, petebacondarwin commented
I'd be cool either leaving it as it currently is.
But perhaps changing it back to 12.0.0 is better. This would avoid churning that bit of code, and the application developer would still get an error if they tried to use a library which had this feature in a 12.0.0 app.

2021-05-21 18:54 UTC, crisbeto commented
The `minVersion` changes have been reverted.

2021-05-21 20:45 UTC, alxhub commented on packages/compiler-cli/test/compliance/test_cases/r3_view_compiler/safe_access/GOLDEN_PARTIAL.js
> +MyApp.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "12.0.0", version: "0.0.0-PLACEHOLDER", type: MyApp, selector: "ng-component", ngImport: i0, template: `
I don't think it's necessary to bump `minVersion` at the moment in order to land this PR (largely echoing what's been discussed offline).

This issue of forward compatibility has always been a problem in Angular, and one that's largely been ignored. We should work to address it, but there's nothing in particular about this change that adds any fresh urgency.

2021-05-21 20:52 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/expression.ts
> +    addParseSpanInfo(node, ast.sourceSpan);
I'm not sure this is necessary/desirable. In 2 of the 3 cases, a sub-expression is already marked with the source span of the `SafeKeyedRead`. It's odd to have an outer expression that's also annotated.

I think this could be refactored:

* don't have the catch-all `addParseSpanInfo`, and mark the element access expression with the span inside the `veWillInferAnyFor` case.
* that'll let you get rid of `let node` and `return` from inside each case instead.

2021-05-21 20:55 UTC, alxhub requested changes

2021-05-21 20:55 UTC, alxhub commented on packages/compiler/test/expression_parser/parser_spec.ts
> +        checkAction('this.a?.["a"]', 'a?.["a"]');
Was this resolved?

2021-05-21 20:55 UTC, alxhub commented on packages/compiler/src/expression_parser/ast.ts
> +  constructor(span: ParseSpan, sourceSpan: AbsoluteSourceSpan, public obj: AST, public key: AST) {
It seems like a lot of disambiguation elsewhere in this PR could be avoided if `obj` were renamed `receiver` here. Then a value typed like `ast: SafeKeyedRead | SafePropertyRead` would still allow `ast.receiver` to refer to the receiver of the read, without needing to disambiguate between the two cases.

2021-05-23 07:48 UTC, crisbeto reviewed
I've addressed the latest set of feedback.

2021-05-23 07:48 UTC, crisbeto commented on packages/compiler-cli/src/ngtsc/typecheck/src/expression.ts
> +    addParseSpanInfo(node, ast.sourceSpan);
I don't have the full context here, but I was following the pattern from `visitSafeMethodCall` and `visitSafePropertyRead` right above it. Should they be refactored as well?

2021-05-23 07:48 UTC, crisbeto commented on packages/compiler/src/expression_parser/ast.ts
> +  constructor(span: ParseSpan, sourceSpan: AbsoluteSourceSpan, public obj: AST, public key: AST) {
The reason I called it `obj` was to align it with `KeyedRead` and `KeyedWrite`. I'll refactor all of them.

2021-05-23 07:48 UTC, crisbeto commented on packages/compiler/test/expression_parser/parser_spec.ts
> +        checkAction('this.a?.["a"]', 'a?.["a"]');
I figured out why it was failing: it was asserting using `checkAction` which had a parse error since pipes aren't allowed in actions, but the parse errors are suppressed unless the assertion error goes through `checkActionWithError`.

I've changed it to `checkBinding` and added the pipe case.

2021-05-26 21:11 UTC, AndrewKushnir commented
@crisbeto FYI I've started [a presubmit](https://test.corp.google.com/ui#id=OCL:376025233:BASE:376025268:1622063347758:3e0a5f45), will keep this thread updated. I've also removed the "action: merge" label for now since @alxhub requested changes (which you've addressed), so he may want to have a final look. Thank you.

2021-06-01 23:13 UTC, alxhub approved these changes

2021-06-01 23:13 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/expression.ts
> +    addParseSpanInfo(node, ast.sourceSpan);
Possibly, but I think that's a bigger change that should be in a different PR. For now, I think following the pattern from `visitSafeMethodCall` and `visitSafePropertyRead` is correct.

2021-06-02 05:30 UTC, AndrewKushnir commented
[Global Presubmit](https://test.corp.google.com/ui#id=OCL:376987525:BASE:376987566:1622611826072:7290fae2).

2021-06-02 20:31 UTC, AndrewKushnir commented
FYI presubmits (including a global one) went well, waiting for the `language-service` group approval before merging this PR.

2021-06-02 21:32 UTC, atscott approved these changes
LGTM for language service. Looks like no updates are needed there. I might still recommend adding a simple quick info or go to definition test for a property read on `a?.[0].pr|op` just to have an automated test for it (rather than the manual testing I did).

2021-06-03 20:22 UTC, closed without merging