doc: update testing components doc with generated compileComponent
angular/angular pull request #41947
Opened 2021-05-04 15:49 UTC by iRealNirmal

Updated testing-components-scenarios.md to match CLI generated test case.

Closes #39740

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Current document isn't reflecting CLI generated test case.

Issue Number: [https://github.com/angular/angular/issues/39740](https://github.com/angular/angular/issues/39740)

## What is the new behavior?
Updated document to show CLI generated test case and it's working example

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-05-04 15:54 UTC, AndrewKushnir commented
@petebacondarwin could you please have a look at this change when you get a chance?

2021-05-04 15:59 UTC, petebacondarwin commented
Hi @iRealNirmal - rather than add a new example, I think what we ought to do is actually change the current guide, removing the references to `waitForAsync` from this section and updating the example. See https://angular.io/guide/testing-components-scenarios#compilecomponents-is-async

2021-05-04 18:30 UTC, petebacondarwin requested changes

2021-05-04 18:30 UTC, petebacondarwin commented on aio/content/guide/testing-components-scenarios.md
> +(e.g., forget to use `async()` as described below),
```suggestion
(e.g., forget to use the `async` keyword as described below),
```

2021-05-04 18:30 UTC, petebacondarwin commented on aio/content/guide/testing-components-scenarios.md
> +To follow this pattern, import the `async()` helper with the other testing symbols.
This is no longer a helper, it is a language construct...

```suggestion
To follow this pattern, make the function asynchronous by adding the `async` keyword.
```

2021-05-04 18:30 UTC, petebacondarwin commented on aio/content/guide/testing-components-scenarios.md
> +The `async()` helper function takes a parameterless function with the body of the setup.
I think we should just remove this sentence.

2021-05-04 19:06 UTC, Toledochrist commented
Thanks

2021-05-05 10:03 UTC, mary-poppins commented
You can preview 9a1c5f8 at https://pr41947-9a1c5f8.ngbuilds.io/.
You can preview 2deb41c at https://pr41947-2deb41c.ngbuilds.io/.
You can preview 858d897 at https://pr41947-858d897.ngbuilds.io/.

2021-05-05 10:06 UTC, petebacondarwin commented
This is looking great! I added the preview label so that you can see what it looks like in the actual docs.

https://pr41947-858d897.ngbuilds.io/guide/testing-components-scenarios#calling-compilecomponents

I note the following:

<img width="857" alt="Screenshot 2021-05-05 at 11 05 14" src="https://user-images.githubusercontent.com/15655/117125746-d88e4e00-ad91-11eb-8332-916ba3f73fb7.png">

I think this whole bit should be removed altogether. Also the import of `waitForAsync` should be removed from the example.

2021-05-05 10:08 UTC, petebacondarwin commented
Further I see that in https://pr41947-858d897.ngbuilds.io/guide/testing-components-scenarios#consolidated-setup it once again mentions `waitForAsync`. This should also be updated to this new format.

2021-05-05 13:28 UTC, mary-poppins commented
You can preview 414694b at https://pr41947-414694b.ngbuilds.io/.

2021-05-06 02:08 UTC, mary-poppins commented
You can preview c7c5b95 at https://pr41947-c7c5b95.ngbuilds.io/.

2021-05-06 05:54 UTC, mary-poppins commented
You can preview 7e16cb7 at https://pr41947-7e16cb7.ngbuilds.io/.

2021-05-06 07:42 UTC, petebacondarwin commented on aio/content/examples/testing/src/app/banner/banner-external.component.spec.ts
> +      .compileComponents();
May as well join up these lines:

```suggestion
      }).compileComponents();
```

2021-05-06 10:40 UTC, mary-poppins commented
You can preview 53261cd at https://pr41947-53261cd.ngbuilds.io/.

2021-05-06 11:14 UTC, mary-poppins commented
You can preview 28fb8b8 at https://pr41947-28fb8b8.ngbuilds.io/.

2021-05-06 13:00 UTC, petebacondarwin requested changes
Looking good. A few NITs and then we are done.

2021-05-06 13:00 UTC, petebacondarwin commented on aio/content/examples/testing/src/app/twain/twain.component.spec.ts
> +    await TestBed.configureTestingModule({
I don't think this need to be async, since there is no call to `compileComponents()`.

2021-05-06 13:00 UTC, petebacondarwin commented on aio/content/examples/testing/src/app/twain/twain.component.spec.ts
> +    it('should show quote after getQuote (waitForAsync)', waitForAsync(() => {
👍

2021-05-06 13:00 UTC, petebacondarwin commented on aio/content/examples/testing/src/app/welcome/welcome.component.spec.ts
> +    await TestBed.configureTestingModule({
Similarly, no async-await needed here.

2021-05-06 13:00 UTC, petebacondarwin commented on aio/content/guide/testing-components-scenarios.md
> +The `async()` utility hides some asynchronous boilerplate by arranging for the tester's code
```suggestion
The `waitForAsync()` utility hides some asynchronous boilerplate by arranging for the tester's code
```

2021-05-06 13:00 UTC, petebacondarwin commented on aio/content/guide/upgrade-setup.md
> +## Appendix: Test using `fakeAsync()/async()`
```suggestion
## Appendix: Test using `fakeAsync()/waitForAsync()`
```

2021-05-06 13:00 UTC, petebacondarwin commented on aio/content/guide/upgrade-setup.md
> +If you use the `fakeAsync()/async()` helper function to run unit tests (for details, read the [Testing guide](guide/testing-components-scenarios#fake-async)), you need to import `zone.js/testing` in
```suggestion
If you use the `fakeAsync()/waitForAsync()` helper functions to run unit tests (for details, read the [Testing guide](guide/testing-components-scenarios#fake-async)), you need to import `zone.js/testing` in your test setup file.
```

2021-05-06 13:47 UTC, mary-poppins commented
You can preview 762981c at https://pr41947-762981c.ngbuilds.io/.

2021-05-06 14:02 UTC, iRealNirmal commented
> Looking good. A few NITs and then we are done.
Thanks took care of it.

2021-05-06 14:50 UTC, petebacondarwin approved these changes
Reviewed-for: global-docs-approvers

2021-05-06 19:40 UTC, closed without merging

2021-05-06 19:40 UTC, alxhub commented
Hello @iRealNirmal,

This conflicts with the 11.2.x branch. Since it's a docs change, I think it's fine to merge it into the 12.x docs only. If you really really want to land this in 11.2.x, feel free to open a separate PR against that branch specifically. I don't think that's necessary, though.

Cheers,
Alex