docs(core): update `Injector.create` signature to latest
angular/angular pull request #42006
Opened 2021-05-08 20:42 UTC by MrJithil

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
This will address issue #41783 and other examples which were using a deprecated signature of `Injector.create`.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Some examples in the aio docs which are using deprecated signature for `Injector.create`.
Issue Number: 41783 

## What is the new behavior?
Correct the signature to the new/non-deprecated one.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-05-09 06:07 UTC, MrJithil commented
reopening.

2021-05-09 16:58 UTC, petebacondarwin requested changes
Thanks @MrJithil - one small comment, and also could you update the commit message to make it clear that you are updating code in an example rather than the core framework.

2021-05-09 16:58 UTC, petebacondarwin commented on packages/upgrade/static/test/integration/injection_spec.ts
> +import {destroyPlatform, InjectionToken, Injector, NgModule, ProviderToken} from '@angular/core';
Is this change necessary?

2021-05-11 10:35 UTC, petebacondarwin commented on packages/upgrade/static/test/integration/injection_spec.ts
> +             expect(injector.get(Injector)).toBeDefined();
I'm not sure this is correct...

2021-05-11 10:39 UTC, petebacondarwin requested changes
Can we tweak the commit message further. I am thinking something like:

```
docs: update examples to use correct `Injector.create()` overload

The `Injector.create(providers, ...)` overload has been deprecated.
The examples now use the `Injector.create(options)` overload.
```

2021-05-11 11:26 UTC, MrJithil commented
> Can we tweak the commit message further. I am thinking something like:
> 
> ```
> docs: update examples to use correct `Injector.create()` overload
> 
> The `Injector.create(providers, ...)` overload has been deprecated.
> The examples now use the `Injector.create(options)` overload.
> ```

Done. Added the same. Thanks for introducing the pattern.

2021-05-11 11:30 UTC, MrJithil commented on packages/upgrade/static/test/integration/injection_spec.ts
> +             expect(injector.get(Injector)).toBeDefined();
`injector.get(token,...)` is deprecated. That's why I used the class there. But, now reverted the changes. Because there is `n` number of places, this issue has to be corrected. So, it could be a different PR.

2021-05-11 11:32 UTC, petebacondarwin commented on packages/upgrade/static/test/integration/injection_spec.ts
> +             expect(injector.get(Injector)).toBeDefined();
My concern was over the change of token from `$INJECTOR` to `Injector`. The former is the AngularJS injector and the latter is the Angular injector.

2021-05-11 13:24 UTC, petebacondarwin approved these changes
Great. Thanks

2021-05-11 16:57 UTC, jessicajaniuk approved these changes
LGTM :cookie:

2021-05-16 16:00 UTC, MrJithil commented
@petebacondarwin Could you please merge this as we received enough green flags?

2021-05-17 17:53 UTC, closed without merging