docs: fix typo
angular/angular pull request #42008
Opened 2021-05-09 06:03 UTC by Sliqric7053

correct a misspelled word

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-05-09 06:07 UTC, Sliqric7053 commented
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fangular%2Fangular%2Fpull%2F42008) for more info**.

@googlebot I signed it!

2021-05-09 07:25 UTC, MrJithil requested changes
Change the PR header to explanatory.

E.g.: `docs: fix a grammatical error in Lazy-loading feature.`

Also, it's good to have some content in the `current behavior` and `new behavior` sections. It will be helpful for contributors to understand the relevance of this change at a glance.

2021-05-09 11:56 UTC, Sliqric7053 commented
@googlebot I signed it!

On Sun, 9 May 2021 at 08:03, google-cla[bot] ***@***.***>
wrote:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project (if not, look below for help).
> Before we can look at your pull request, you'll need to sign a Contributor
> License Agreement (CLA).
>
> 📝 *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed (or fixed any issues), please reply here with @googlebot
> I signed it! and we'll verify it.
> ------------------------------
> What to do if you already signed the CLA Individual signers
>
>    - It's possible we don't have your GitHub username or you're using a
>    different email address on your commit. Check your existing CLA data
>    <https://cla.developers.google.com/clas> and verify that your email is
>    set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>
> Corporate signers
>
>    - Your company has a Point of Contact who decides which employees are
>    authorized to participate. Ask your POC to be added to the group of
>    authorized contributors. If you don't know who your Point of Contact is,
>    direct the Google project maintainer to go/cla#troubleshoot (Public
>    version <https://opensource.google/docs/cla/#troubleshoot>).
>    - The email used to register you as an authorized contributor must be
>    the email used for the Git commit. Check your existing CLA data
>    <https://cla.developers.google.com/clas> and verify that your email is
>    set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - The email used to register you as an authorized contributor must
>    also be attached to your GitHub account
>    <https://github.com/settings/emails>.
>
> ℹ️ *Googlers: Go here
> <https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fangular%2Fangular%2Fpull%2F42008>
> for more info*.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/42008#issuecomment-835702117>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB4YOZHXDBYT5FO5WCZTWODTMYQU3ANCNFSM44OR3H3Q>
> .
>

2021-05-09 12:11 UTC, Sliqric7053 commented
> Change the PR header to explanatory.
> 
> E.g.: `docs: fix a grammatical error in Lazy-loading feature.`
> 
> Also, it's good to have some content in the `current behavior` and `new behavior` sections. It will be helpful for contributors to understand the relevance of this change at a glance.

Thanks for your feedback, I've updated the PR : )

2021-05-09 16:55 UTC, petebacondarwin commented
> > Change the PR header to explanatory.
> > E.g.: `docs: fix a grammatical error in Lazy-loading feature.`
> > Also, it's good to have some content in the `current behavior` and `new behavior` sections. It will be helpful for contributors to understand the relevance of this change at a glance.
> 
> Thanks for your feedback, I've updated the PR : )

Sadly this is not exactly accurate. It doesn't really matter what the PR title and description are (other than to make it easier for us to triage and review). The more important point is that the commit message itself has to follow our [commit requirements](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit). Please take a look and let me know if you need help amending the commit.

2021-05-10 04:31 UTC, Sliqric7053 commented
> > > Change the PR header to explanatory.
> > > E.g.: `docs: fix a grammatical error in Lazy-loading feature.`
> > > Also, it's good to have some content in the `current behavior` and `new behavior` sections. It will be helpful for contributors to understand the relevance of this change at a glance.
> > 
> > 
> > Thanks for your feedback, I've updated the PR : )
> 
> Sadly this is not exactly accurate. It doesn't really matter what the PR title and description are (other than to make it easier for us to triage and review). The more important point is that the commit message itself has to follow our [commit requirements](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit). Please take a look and let me know if you need help amending the commit.

Thanks for the feedback, yes please - should I discard the PR and create a new one with a proper commit message, or can I amend the current one? If the latter, I would appreciate your assistance in this regard.

Thanks again.

2021-05-10 06:46 UTC, petebacondarwin commented
You should not need to start a new PR, although I suspect you made this change via the GitHub UI, rather than cloning the repository locally. One approach would be:

```bash
git clone https://github.com/Sliqric7053/angular
git checkout patch-1
git commit --amend -m"docs: fix a grammatical error in lazy-loading-ngmodules guide"
git push --force-with-lease
```

2021-05-10 06:47 UTC, petebacondarwin commented
If you struggle to do this, I could probably fix it up for you from here.

2021-05-10 09:01 UTC, petebacondarwin commented
And finally you just need to post a comment with:

```
@googlebot I fixed it.
```

2021-05-10 09:01 UTC, Sliqric7053 commented
> Thanks for the update @Sliqric7053 - unfortunately your local git was setup with the following email address: `riccirich@Riccis-MacBook-Pro.local`, which is not what you used to sign the CLA.
> 
> I think you could fix this by running:
> 
> ```
> git config --global user.email "email@example.com"
> ```
> 
> with your actual email address, and then amending the commit once again:
> 
> ```
> git commit --amend --reuse-message=HEAD
> git push --force-with-lease
> ```

Hmm.. I've updated the git username/email as advised, but I think git is still picking up my default (incorrect details).

![image](https://user-images.githubusercontent.com/7964516/117634184-f20f0b80-b17e-11eb-82a3-204ae2862b19.png)

2021-05-10 09:02 UTC, petebacondarwin commented
Try this: https://github.com/angular/angular/pull/42008#issuecomment-836431260

2021-05-10 09:03 UTC, Sliqric7053 commented
> @googlebot I fixed it.

@googlebot I fixed it.

2021-05-10 09:04 UTC, Sliqric7053 commented
> Try this: [#42008 (comment)](https://github.com/angular/angular/pull/42008#issuecomment-836431260)

![image](https://user-images.githubusercontent.com/7964516/117634681-7792bb80-b17f-11eb-845d-20c7db9fc7d5.png)

The bot says.. No : (

2021-05-10 09:09 UTC, petebacondarwin commented
😭 

I can see that the commit doesn't seem to have changed: https://github.com/angular/angular/commit/8cbf84a948d06fbcb45bb87c89c014a75151d0c5.patch

Perhaps try:

```
git commit --amend --author="Richard Sithole <your@email.address>"
```

2021-05-10 10:47 UTC, Sliqric7053 commented
> 😭
> 
> I can see that the commit doesn't seem to have changed: https://github.com/angular/angular/commit/8cbf84a948d06fbcb45bb87c89c014a75151d0c5.patch
> 
> Perhaps try:
> 
> ```
> git commit --amend --author="Richard Sithole <your@email.address>"
> ```

Finally, bot seems to be happy :)

Just awaiting these tasks..

![image](https://user-images.githubusercontent.com/7964516/117647844-cd6e6000-b18d-11eb-8101-193e7538eef4.png)

Thanks so much for your help and patience 💯  : )

2021-05-10 10:55 UTC, petebacondarwin approved these changes
Reviewed-for: global-docs-approvers

2021-05-10 15:53 UTC, closed without merging