Update builder documentation to be platform-agnostic.
angular/angular pull request #42371
Opened 2021-05-26 22:09 UTC by dgp1130

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [N/A] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Documentation content changes

## What is the current behavior?

Builder CLI documentation references Unix commands such as `touch` and `ls`, which do not apply to Windows users.

Issue Number: #35373

## What is the new behavior?

Example is changed to simply copy a file rather than run arbitrary commands. This way it requires no knowledge of or support for Unix commands on the reader's machine.

## Does this PR introduce a breaking change?

- [X] No

2021-05-27 12:45 UTC, mary-poppins commented
You can preview 97ed25d at https://pr42371-97ed25d.ngbuilds.io/.

2021-05-27 13:37 UTC, gkalpak requested changes
Awesome re-work :tada:
(Just a few typos and minor suggestions.)

OOC, why `target: major`?

2021-05-27 13:37 UTC, gkalpak commented on aio/content/examples/cli-builder/src/my-builder.ts
> +    context.logger.error(`Failed to copy file.`);
```suggestion
    context.logger.error('Failed to copy file.');
```

Also, is the error message surfaced somewhere? Would it be helpful to include it here?

2021-05-27 13:37 UTC, gkalpak commented on aio/content/examples/cli-builder/src/my-builder.ts
> +  context.reportStatus(`Done.`);
```suggestion
  context.reportStatus('Done.');
```

Also, this line doesn't seem to belong to the `handling-output` docregion.

2021-05-27 17:18 UTC, dgp1130 commented on aio/content/examples/cli-builder/src/my-builder.spec.ts
>      const run = await architect.scheduleBuilder('@example/command-runner:command', {
Ah yes, I knew I would miss one of those!

2021-05-27 17:18 UTC, dgp1130 commented on aio/content/examples/cli-builder/src/my-builder.spec.ts
> +    });
Ah cool, I didn't know that!

2021-05-27 17:19 UTC, dgp1130 commented on aio/content/guide/cli-builder.md
> +* In addition to the contextual information, the `context` object, which is an instance of the `BuilderContext`, also provides access to a scheduling method, `BuilderContext.prototype.scheduleTarget(
Good point, replaced `BuilderContext.prototype` with `context`.

2021-05-27 17:19 UTC, dgp1130 commented on aio/content/examples/cli-builder/src/my-builder.ts
> +  context.reportStatus(`Done.`);
Good catch.

2021-05-27 17:19 UTC, dgp1130 commented on aio/content/examples/cli-builder/src/my-builder.ts
> +    context.logger.error(`Failed to copy file.`);
The error gets returned and architect shows it to the user, this is just providing some additional context for the following error message.

2021-05-27 17:19 UTC, dgp1130 commented
> OOC, why `target: major`?

I was trying to say that since this is a docs change it only needs to merge into `master`. Is there a different label I should use here?

2021-05-27 17:22 UTC, clydin commented
master is `target: minor` currently.  That will change to `target: major` when master is in v13 prerelease.

2021-05-27 17:26 UTC, dgp1130 commented
Actually, I forgot this was on aio rather than a simple README. Would this make more sense as a patch release? I'm not sure where exactly we draw the line between "bug" and "feature" for docs?

2021-05-27 17:28 UTC, clydin commented
Looks like pretty much all the docs PRs are for `target: patch` so that probably makes sense here as well

2021-05-27 17:29 UTC, clydin commented on aio/content/guide/cli-builder.md
> +* The target named "copy" uses our builder, which we published to `@example/copy-file`. (See [Publishing your Library](guide/creating-libraries#publishing-your-library))
```suggestion
* The target named "copy-package" uses our builder, which we published to `@example/copy-file`. (See [Publishing your Library](guide/creating-libraries#publishing-your-library))
```

2021-05-27 17:29 UTC, clydin commented on aio/content/guide/cli-builder.md
>  * The configurations key is optional, we'll leave it out for now.
```suggestion
* The `configurations` key is optional, we'll leave it out for now.
```

2021-05-27 17:31 UTC, clydin approved these changes
Nice job.
The copy file concept is a good choice to reduce the complexity of the example.

Just two comments.

2021-05-27 17:31 UTC, mary-poppins commented
You can preview 0c45b83 at https://pr42371-0c45b83.ngbuilds.io/.

2021-05-27 17:43 UTC, mary-poppins commented
You can preview c8ed982 at https://pr42371-c8ed982.ngbuilds.io/.

2021-05-28 10:38 UTC, gkalpak approved these changes
🚀

2021-06-01 17:13 UTC, closed without merging