docs: move fine-grained strictness flags docs to guide/angular-compiler-options
angular/angular pull request #42400
Opened 2021-05-27 22:46 UTC by IgorMinar

I moved the fine-grained strictness flags from the template-typecheck guide to the angular-compiler-guide so that
all of the flags are documented on a single page.

Additionally, I simplified some wording in these docs and added links between the two guides.

Fixes #39354

2021-06-01 23:08 UTC, alxhub requested changes

2021-06-01 23:08 UTC, alxhub commented on aio/content/guide/angular-compiler-options.md
> +Turning on all the following fine-grained strictness flags is equivalent to turning on the `strictTemplates` flag.
This is not actually true. There's plenty of strictness functionality not controlled by an exposed flag.

These individual flags are meant to be used as opt-outs. Projects trying to transition to strict type-checking incrementally should enable `strictTemplates`, then explicitly **disable** any of the strictness checks that are causing them issues.

2021-06-01 23:08 UTC, alxhub commented on aio/content/guide/template-typecheck.md
> +* If you want to use [`strictTemplates`](guide/angular-compiler-options#stricttemplates) and[`strictNullChecks`](https://www.typescriptlang.org/tsconfig#strictNullChecks) together, you can opt out of
```suggestion
* If you want to use [`strictTemplates`](guide/angular-compiler-options#stricttemplates) and [`strictNullChecks`](https://www.typescriptlang.org/tsconfig#strictNullChecks) together, you can opt out of strict null type checking specifically for input bindings via the fine-grained strictness flag [`strictNullInputTypes`](guide/angular-compiler-options#stricttemplates).
```

2021-06-02 00:22 UTC, IgorMinar commented on aio/content/guide/angular-compiler-options.md
> +Turning on all the following fine-grained strictness flags is equivalent to turning on the `strictTemplates` flag.
ah, interesting. That makes things even more confusing and more challenging to document. I gave it a shot, PTAL.

2021-06-03 15:25 UTC, alxhub approved these changes

2021-06-03 20:57 UTC, AndrewKushnir commented
@IgorMinar it looks like there are some legit failures on CI. Could you please have a look when you get a chance? Thank you.

2021-06-04 18:18 UTC, IgorMinar commented
@AndrewKushnir rebased 🤞🏻

2022-01-27 21:33 UTC, closed without merging