feat(compiler): add support for shorthand property declarations in templates
angular/angular pull request #42421
Opened 2021-05-30 08:35 UTC by crisbeto

Adds support for shorthand property declarations inside Angular templates. E.g. doing `{foo, bar}` instead of `{foo: foo, bar: bar}`.

Fixes #10277.

2021-06-01 18:19 UTC, jessicajaniuk approved these changes
LGTM :cookie:

2021-06-01 18:31 UTC, JoostK requested changes
The change generally looks good, with a comment on parse spans.

I think this syntax requires special attention in the language service when renaming a property, as the shorthand syntax may need to be expanded in that case. @atscott WDYT about this case?

2021-06-01 18:31 UTC, JoostK commented on packages/compiler/src/expression_parser/parser.ts
> +          const sourceSpan = this.sourceSpan(start);
Using `start` looks incorrect here, as that's the index of the opening `{`. We have some AST parse span tests that can verify this is correct.

2021-06-01 18:31 UTC, JoostK commented on packages/compiler-cli/test/compliance/test_cases/r3_view_compiler_template/GOLDEN_PARTIAL.js
> +MyComponent.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "12.0.0", version: "0.0.0-PLACEHOLDER", type: MyComponent, selector: "ng-component", ngImport: i0, template: `
Just a note that this needs the same `minVersion` treatment as the `?.[]` syntax.

2021-06-01 18:36 UTC, crisbeto commented on packages/compiler-cli/test/compliance/test_cases/r3_view_compiler_template/GOLDEN_PARTIAL.js
> +MyComponent.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "12.0.0", version: "0.0.0-PLACEHOLDER", type: MyComponent, selector: "ng-component", ngImport: i0, template: `
Just to capture what we decided in the other PR (https://github.com/angular/angular/pull/41911): we'll merge in the new syntax without bumping the `minVersion` and land a compiler change later on to deal with it in a better way.

2021-06-02 17:52 UTC, crisbeto commented
I've addressed the span issue @JoostK.

2021-06-02 18:27 UTC, JoostK commented on packages/compiler/src/expression_parser/parser.ts
> +          const sourceSpan = this.sourceSpan(spanStart, spanEnd);
At this point in the parse the `key` has already been parsed, so the cursor and thus `this.inputIndex` is beyond the key. I think we'd have to capture `this.inputIndex` before parsing `key` and the `spanEnd` can be dropped, as `this.span` and `this.sourceSpan` select the proper end offset.

2021-06-02 18:41 UTC, crisbeto commented
Addressed the latest set of feedback and fixed the test failure.

2021-06-02 19:03 UTC, atscott requested changes
I think we should add more tests around each part of the system that supports the language service:

The "template target" code ensures that we can map a position in a template to a target node in the TCB. This code is tested in `packages/language-service/ivy/test/legacy/template_target_spec.ts` (note that these tests do not pass so there needs to be an update to the template target code):

```

  describe('object literal shorthand', () => {
    fit('with one item', () => {
      debugger;
      const {errors, nodes, position} = parse(`{{ {va¦l1} }}`);
      expect(errors).toBe(null);
      const {context} = getTargetAtPosition(nodes, position)!;
      expect(context.kind).toBe(TargetNodeKind.RawExpression);
      // Maybe this should be multinode target so we target both the key and the value of the object
      // literal map
      const {node} = context as SingleNodeTarget;
      expect(node).toBeInstanceOf(e.PropertyRead);
      expect((node as e.PropertyRead).name).toBe('val1');
    });

    fit('with two shorthands', () => {
      const {errors, nodes, position} = parse(`{{ {val1, va¦l2} }}`);
      expect(errors).toBe(null);
      const {context} = getTargetAtPosition(nodes, position)!;
      expect(context.kind).toBe(TargetNodeKind.RawExpression);
      const {node} = context as SingleNodeTarget;
      expect(node).toBeInstanceOf(e.PropertyRead);
      expect((node as e.PropertyRead).name).toBe('val2');
    });

    fit('with shorthand and regular syntax', () => {
      const {errors, nodes, position} = parse(`{{ {val1: 'val1', va¦l2} }}`);
      expect(errors).toBe(null);
      const {context} = getTargetAtPosition(nodes, position)!;
      expect(context.kind).toBe(TargetNodeKind.RawExpression);
      const {node} = context as SingleNodeTarget;
      expect(node).toBeInstanceOf(e.PropertyRead);
      expect((node as e.PropertyRead).name).toBe('val2');
    });
  });
```
This brings up an immediate question:  Should we just target the property read node via a `SingleNodeTarget`? The way the TCB is currently generated, I think that's all we can do. 

We should add some tests around the TCB generation in `packages/compiler-cli/src/ngtsc/typecheck/test/span_comments_spec.ts`. This is the second part of the question above: What do we do about the divergent representations in the type check block vs what's in the template? The template code is written as `{val1}` and then generated as `{"val1": ((ctx).val1 /*span*/) /*span*/}` in the TCB. The language service leverages the TCB for most of the actions we perform. Because the TCB output is different than the representation in the template, it would be hard to get everything fully correct (renames, go to definition, etc.). This might just be something we have to be okay with and just do actions off of the property read. We might need to add a new template target type that can detect this case and not allow renaming. Or we just allow a rename from the property read and be okay that we get it wrong where template shorthand is used (which hopefully isn't many places and at least the compiler will detect them and complain).

After the template node is found, the language service builds a symbol for the template node. This part is tested in `packages/compiler-cli/src/ngtsc/typecheck/test/type_checker__get_symbol_of_template_node_spec.ts`. Please add a test there to ensure we build the correct symbol for this case.

Lastly, we have specific functions in the language service for LSP operations (quick info, definitions, etc) using the template symbol information. Generally if the symbol was built correctly, the other parts _should_ also work. Here's a test for quick info (`packages/language-service/ivy/test/quick_info_spec.ts`):

```

  // TODO(atscott): This should be able to be added to the previous section as long as the project
  // has a different name than the one in the beforeEach but something goes wrong in the test
  // environment
  describe('non-skeleton project', () => {
    beforeEach(() => {
      initMockFileSystem('Native');
      env = LanguageServiceTestEnv.setup();
    });
    fit('should work for shorthand object literal', () => {
      project = env.addProject(
          'test', {
            'app.ts': `
            import {Component, NgModule} from '@angular/core';
            import {CommonModule} from '@angular/common';

            @Component({
              selector: 'some-cmp',
              templateUrl: './app.html',
            })
            export class SomeCmp {
              val1 = 'one';
              val2 = 2;

              doSomething(obj: {val1: string, val2: number}) {

              }
            }

            @NgModule({
              declarations: [SomeCmp],
              imports: [CommonModule],
            })
            export class AppModule{
            }
       `,
            'app.html': `{{doSomething({val1, val2})}}`,
          },
          {strictTemplates: true});
      env.expectNoSourceDiagnostics();
      project.expectNoSourceDiagnostics();

      const template = project.openFile('app.html');
      template.moveCursorToText('val¦1');
      const quickInfo = template.getQuickInfoAtPosition();
      expect(toText(quickInfo!.displayParts)).toEqual('(property) val1: string');
      template.moveCursorToText('val¦2');
      const quickInfo2 = template.getQuickInfoAtPosition();
      expect(toText(quickInfo!.displayParts)).toEqual('(property) val2: number');
    });
  });
```
You propably want to add a similar test to `definitions_spec` in the same folder to ensure "go to definition" works properly as well as the `references_and_rename_spec`.

2021-06-06 18:07 UTC, crisbeto commented
@atscott all of the feedback should be covered in the latest fixup commit. I've also included more tests for safe keyed reads since I didn't get the chance to add them before #41911 got merged in.

2021-06-07 16:50 UTC, atscott requested changes

2021-06-07 16:50 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/test/type_checker__get_symbol_of_template_node_spec.ts
> +          const literalMap = interpolation.expressions[2] as LiteralMap;
Could you update this or add a test that gets the symbol for the property in the map rather than the map itself? I don't know if, in practice, the vscode extension requests symbols for the whole map.

2021-06-07 16:50 UTC, atscott commented on packages/language-service/ivy/test/legacy/definitions_spec.ts
> +      expect(def.contextSpan).toContain('name: string;');
Can you add an assert for `def.fileName` as well? This part is currently not working - the "go to definition" attempts to go to the typecheck file which doesn't exist on disk.

2021-06-07 21:02 UTC, crisbeto commented
The latest set of feedback has been addressed.

2021-06-08 05:51 UTC, JoostK approved these changes
LGTM for fw-compiler

2021-06-08 17:18 UTC, atscott commented on packages/language-service/ivy/test/legacy/definitions_spec.ts
>    });
Ah, interesting. The above test _does_ work for go to definition. I was actually testing this case locally: 
`{{ {name} }}`.

Could you add another test for that case? I think the `fileName` for that one is going to be the typecheck file which will give this error if you try to go to definition:
![image](https://user-images.githubusercontent.com/479713/121227560-8c2aa800-c840-11eb-9be8-af687fe548e6.png)

It seems the symbol you're going to is the key of the object rather than the property read. This'll happen because they have the same source span `"name": ((ctx).name /*49,58*/) /*49,58*/` and we just target the first one we find.

We should update the code in `template_symbol_builder` to be 

```
function getSymbolOfTemplateExpression...
   ...
    const anyNodeFilter = (n: ts.Node): n is ts.Node => true;
    const filter =
        expression instanceof PropertyRead ? ts.isPropertyAccessExpression : anyNodeFilter;
    let node = findFirstMatchingNode(this.typeCheckBlock, {withSpan, filter});
    ...
```

This will also update the test you have for that part to be 
`expect(program.getTypeChecker().symbolToString(symbol.tsSymbol!)).toEqual('foo');` 
instead of
`expect(program.getTypeChecker().symbolToString(symbol.tsSymbol!)).toEqual('__type');`
which I think is what we want.

2021-06-10 09:13 UTC, crisbeto commented
The last comment has been addressed @atscott.

2021-06-11 17:02 UTC, atscott approved these changes
👍  LGTM

2021-06-11 17:03 UTC, atscott commented
[presubmit](http://test/OCL:378894848:BASE:378894881:1623431003756:21964cd6)

2021-06-11 21:57 UTC, alxhub requested changes

2021-06-11 21:57 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/test/span_comments_spec.ts
> +    it('should annotate safe keyed reads', () => {
This test appears unrelated to everything else in this PR. Is it here because prior designs broke this feature?

Either way, I would recommend extracting the addition of this test as a separate commit prior to the main commit, to avoid confusion.

2021-06-11 21:57 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/template_symbol_builder.ts
> +    let node =
This operation took me a while to unravel. Two comments:

1) Why is it now necessary to prioritize `ts.PropertyAccessExpression` nodes over other nodes in the case of `PropertyRead` operations? This seems like it might be an avoidable change. If not, I think we should document here why `PropertyRead` is special-cased.

2) We should also restructure this flow to be much more obvious - the `||` operation I think is a bit too hard to follow. Extracting the node search into a utility function could be extremely helpful here. Something like:

```typescript
function getExpressionTsNode(...): ts.Node|null {
  if (expression instanceof PropertyRead) {
    // Prioritize looking for a `ts.PropertyAccessExpression` for `PropertyRead` expressions, because
    // ...
    const node = findFirstMatchingNode(..., ts.isPropertyAccessExpression);
    if (node !== undefined) {
      return node;
    }
  }

  // In most cases, find the first matching node of any kind.
  return findFirstMatchingNode(..., anyNodeFilter) ?? null;
}
```

2021-06-11 22:44 UTC, alxhub commented
If you wouldn't mind, I think we could also use a test here for a case like:
```html
<div #foo></div>
{{ m({foo}) }}
```
just to verify that a shorthand reference to a property defined in the template itself still works.

2021-06-11 22:47 UTC, alxhub commented
(and apologies for the last-minute change requests! this PR is 👍 otherwise, this is just a confusing part of the system and i want to make sure it's as clear as possible for people in the future)

2021-06-12 07:05 UTC, crisbeto commented on packages/compiler-cli/src/ngtsc/typecheck/test/span_comments_spec.ts
> +    it('should annotate safe keyed reads', () => {
These are tests that I missed in my safe keyed reads PR (https://github.com/angular/angular/pull/41911). I decided to add them here since this PR touches the same test files.

2021-06-12 07:15 UTC, crisbeto commented
I've addressed the latest set of feedback @alxhub.

2021-06-18 20:22 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/test/span_comments_spec.ts
> +    it('should annotate safe keyed reads', () => {
I think we should squash the commits and then extract these tests into a separate commit, honestly.

It's not a big deal, but I think in the name of having a clean history, it makes sense not to bundle unrelated tests.

To avoid another round trip and blocking this PR, I'll go ahead and do that for you since I think it's ready to merge otherwise.

2021-06-18 23:16 UTC, alxhub approved these changes
(I've pushed an update that splits out the extra tests for keyed reads into a separate commit, to keep the history clean)

2021-06-21 18:26 UTC, dylhunn commented
@AndrewKushnir suggests running a TGP, I will do so today.

2021-06-21 18:48 UTC, dylhunn commented
This CL is on the 1pm TAP train, should have results this afternoon.

2021-06-21 23:40 UTC, dylhunn commented
TGP is green.

2021-06-21 23:40 UTC, closed without merging