fix(complier-cli): check split two way binding
angular/angular pull request #42601
Opened 2021-06-18 21:00 UTC by danieltre23

Check for split two way binding when output is not declared to make error message clearer.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 39300

## What is the new behavior?
The new error message for a banana-in-a-box binding with the output not declared should be "The output {outputName} for the two way binding is not declared."

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-06-18 21:58 UTC, dgp1130 reviewed
Great job Daniel! This looks really cool. Just a few nitpicks and a couple edge cases to consider and this should be good to go.

One general nit: Prefer `const` over `let` wherever possible, just to reduce the possibility of mutation where its not needed.

2021-06-18 21:58 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      private claimedOutputs: Set<string>, private claimedInputs: Set<string>) {
Nit: I would swap the `claimedInputs` and `claimedOutputs` parameters so inputs comes first. Otherwise I think it would be pretty easy for users to accidentally pass their arguments backwards.

2021-06-18 21:58 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      let inputName = output.name.replace('Change', '');
We can probably limit this to just outputs which *end* with `Change`, otherwise a name like `ChangeDataEvent` would become `DataEvent` and lead to strange behavior.

I think we can use a regex to only replace a `Change` which is the last part of the string:

```typescript
output.name.replace(/Change$/, '');
```

2021-06-18 21:58 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +      // Check for split two way binding with unclaimed outputs
Instead of removing `Change` and then looking for an input with that name, we should look for an input *only if* the output ends with `Change`. Otherwise something like:

```typescript
class MyComponent {
  @Input() @Output() something: string;
}
```

Would lead to strange behavior. Admittedly that's probably its own bug, but I imagine we'd want to handle that separately from this.

2021-06-18 21:58 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +        if (input?.sourceSpan == output.sourceSpan) {
Nit: Since already know the `inputName` is claimed, if we don't get an `input`, that's an internal compiler error. I'm thinking we should either assert that `input` is defined (not sure of the best way to do that in the compiler) or use `input!.sourceSpan` so we get a real error.

2021-06-18 21:58 UTC, dgp1130 commented on packages/compiler-cli/test/ngtsc/template_typecheck_spec.ts
> +          @Output() incrementValue = new EventEmitter<number>();
Nit: Consider adding a comment here which points out that this name should be `valueChange`, but the user got it wrong which causes the error. This will make it more clear exactly what mistake this is testing for.

2021-06-18 21:58 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +    const errorMsg = `The output ${output.name} for the two way binding is not declared.`;
Nit: I'm thinking we should include a link to https://angular.io/guide/two-way-binding#how-two-way-binding-works which gives a much more complete explanation of the two-way binding contract. That would help users understand exactly what they did wrong and how to fix it.

2021-06-22 05:06 UTC, dgp1130 commented
All the code looks good to me, and I kicked off a google3 presubmit, but it looks like it has a few legitimate failures: http://test/OCL:380647145:BASE:380647172:1624306026646:e07d2f4f.

Looks like there's a lot of code which two-way binds to `model` properties that don't have a `modelChange` event. I'm surprised this wasn't an error before, do we special case the `model` property in some way? I'm wondering if we should exempt it from this check or else we'll likely need to roll this out behind a flag. Thoughts, @alxhub?

2021-06-22 15:29 UTC, danieltre23 commented
> All the code looks good to me, and I kicked off a google3 presubmit, but it looks like it has a few legitimate failures: http://test/OCL:380647145:BASE:380647172:1624306026646:e07d2f4f.
> 
> Looks like there's a lot of code which two-way binds to `model` properties that don't have a `modelChange` event. I'm surprised this wasn't an error before, do we special case the `model` property in some way? I'm wondering if we should exempt it from this check or else we'll likely need to roll this out behind a flag. Thoughts, @alxhub?

I think the error should only show when the strictTemplates flag is true, I noticed that the error in the issue #39300 is only for strictTemplates, so I'll add that check.

2021-06-22 17:33 UTC, dgp1130 commented
Passing presubmit: http://test/OCL:380647145:BASE:380826857:1624379963990:c3d8b02d

2021-06-23 17:04 UTC, dgp1130 commented
Ran a global presubmit since strict templates is not widely used internally and I wanted to make sure we were checking at least some strict templates targets, everything looks good: http://test/OCL:380970929:BASE:380971055:1624432874430:81de2e8d.

2021-06-24 20:05 UTC, dgp1130 approved these changes
Forgot to approve after the google3 tests passed.

2021-06-24 20:24 UTC, alxhub requested changes
Overall I think the mechanics of this PR are solid. Let's tweak the error message a bit to more accurately reflect the situation in the template, and then this should be good to go.

2021-06-24 20:24 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/diagnostics/src/error_code.ts
> +   * A template has a double binding in which the output is not declared.
I think we need to elaborate more on what this means, and clarify:

* We're talking about a two way binding, where a single syntactical element creates two bindings (one to an input, one to an output).
* This binding is "split", meaning that the input and output are interpreted as going to different places (as opposed to the same component or directive).

2021-06-24 20:24 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +  splitTwoWayBinding(templateId: TemplateId, output: TmplAstBoundEvent): void {
I think we're missing an important distinction here.

The fundamental issue is that for a true two way binding, both the input and output halves should go to the same place (either a directive of some kind, or to DOM). If we see a usage where this _isn't_ the case, it doesn't automatically mean that the component is missing an `@Output`. It might very well be that the user has misunderstood the component's API, or that the `@Input` is actually the part that's in the wrong (maybe the output goes to a directive, but the input doesn't?).

Right now, we're only really catching the case where the `@Input` goes to a directive, but the `@Output` goes to DOM. In this case, I think we should give an error that:

* Reports the problem, e.g. "The input and output halves of this two-way binding don't bind to the same target"
* Describes where each of the bindings goes. For example, if the input half of the binding goes to a component/directive, we can add an additional pointer to the diagnostic saying "the input half of the binding goes to this directive".

Our error shouldn't favor any particular interpretation (e.g. that an `@Output` is missing somewhere) but should instead describe the actual situation. In the error guide, we can then make suggestions about what _might_ be wrong in the program to have caused the error.

2021-06-24 20:24 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/template_typecheck_spec.ts
> +          @Output() incrementValue = new EventEmitter<number>();
We shouldn't actually need an `@Output` here at all - the test is equally valid and effective if this is missing.

2021-06-28 17:44 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +    const errorMsg = `The input and output of the two-way binding '${
This error is getting better! Let's adjust a few more things:

1. Inputs and outputs are features of components and directives. In the context of a binding, you bind to a _property_ or to an _event_. Inputs are a feature of components that can receive property bindings, outputs are a feature of components that can raise events. So using the property/event terminology is more accurate in this context.

2. It's not a great developer experience for us to say "the output is bound to null". In this case, we should tell them that the property half of the binding targets a component, whereas the event binding is targeting the DOM.

3. The property/event names for the binding are wholly predictable, as they're determined by the binding the user wrote. If the user wrote `[(ngModel)]` then the property name will be `ngModel` and the event name will be `ngModelChange`. It'd be more useful to name the component(s) which are receiving the binding(s).

. `ts.Diagnostic` has a way of attaching related information beyond the primary error message. This is extremely useful for building a good developer experience for an error, as we can include pointers to other locations in the code that are relevant to the error. For example, in this case we could point to the component that's accepting the property binding. Some of the other OOB diagnostics make use of this facility - you can use them as examples.

2021-06-28 17:47 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +          if (input && input.sourceSpan == output.sourceSpan) {
In the compiler we prefer to check values explicitly rather than relying on truthiness. Additionally, in JavaScript you should always prefer `===` to `==` as the latter has some really unintuitive behavior in specific cases. For example, `3 == '3'` is true.


```suggestion
          if (input !== undefined && input.sourceSpan === output.sourceSpan) {
```

2021-06-28 17:47 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +          const input = this.element.inputs.find(input => input.name == inputName);
(same as below, prefer `===`)

2021-06-28 17:47 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +            let inputProptertyName = null;
```suggestion
            let inputPropertyName = null;
```
and throughout

2021-06-28 20:36 UTC, atscott requested changes

2021-06-28 20:36 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +        input.name}' are not binded to the same target.
Nit: these should be “bound” not “binded”

2021-06-28 20:36 UTC, atscott commented on packages/compiler-cli/test/ngtsc/template_typecheck_spec.ts
> +          .toEqual(
We should probably assert the error code here rather than the text of the message. We shouldn’t have to keep updating this test assertion if we revise the wording of the error. 

Edit: note that the error codes are a relatively new thing we introduced so the old tests probably didn’t have that option and May no longer be the best example of what the test should assert.

2021-07-01 01:10 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +  splitTwoWayBinding(templateId: TemplateId, output: TmplAstBoundEvent): void {
Hi @danieltre23, unresolving this again. Please add the following test to your suite, which should pass when this comment is resolved: 

```
      it('when input and output go to different directives', () => {
        env.tsconfig({strictTemplates: true});
        env.write('test.ts', `
        import {Component, Input, NgModule, Output, Directive} from '@angular/core';

        @Component({
          selector: 'test',
          template: '<child-cmp [(value)]="counterValue"></child-cmp>',
        })
        export class TestCmp {
          counterValue = 0;
        }

        @Directive({
          selector: 'child-cmp'
        })
        export class ChildCmpDir {
          @Output() valueChange: any;
        }

        @Component({
          selector: 'child-cmp',
          template: '',
        })
        export class ChildCmp {
          @Input() value = 0;
        }

        @NgModule({
          declarations: [TestCmp, ChildCmp, ChildCmpDir],
        })
        export class Module {}
      `);
        const diags = env.driveDiagnostics();
        expect(diags.length).toBe(1);
        expect(diags[0].code).toBe(ngErrorCode(ErrorCode.SPLIT_TWO_WAY_BINDING));
        expect(getSourceCodeForDiagnostic(diags[0])).toBe('[(value)]="counterValue"');
        expect(diags[0].relatedInformation!.length).toBe(2);
      });
```

2021-07-01 18:00 UTC, atscott approved these changes
Adding my approval. Left a couple comments that could be addressed but they're minor/trivial.

2021-07-01 18:00 UTC, atscott commented on packages/compiler-cli/src/ngtsc/diagnostics/src/error_code.ts
> +   * <div [(ngModel)]="..."/>
I think this example should either be removed completely or changed. `ngModel` typically is not a split two way binding.

2021-07-01 20:38 UTC, danieltre23 commented
Flaky failures in presubmit: http://test/OCL:382577037:BASE:382578882:1625167383976:5adc77a7 forced green.

2021-07-02 17:23 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +      inputConsumerIdentifier: ts.Identifier, outputConsumer: ts.Identifier|TmplAstElement): void {
I would suggest passing the `ClassDeclaration` here instead of the `ts.Identifer`, as logically the binding goes to the class. Let `splitToWayBinding` decide how it wants to identify the component.

2021-07-02 17:24 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +    const errorMsg = `The property and event of the two-way binding '${
Let's refer to them as the "property and event halves of the two-way binding"

2021-07-02 17:26 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +    diagnostic.relatedInformation = relatedDiagnostics;
We shouldn't need to modify `diagnostic.relatedInformation` here. `makeTemplateDiagnostic` should be able to fully construct the diagnostic with all information already present. If it can't, we can modify it to be more flexible in that regard.

2021-07-02 17:27 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +      Are you missing an output declaration called '${output.name}'?`,
We should only show this hint if the component belongs to the user, and doesn't come from a library.

`ts.SourceFile` has `.isDeclarationFile`, which signifies that the source file is a `.d.ts` file from a library instead of a `.ts` file that the user wrote, which can distinguish these two cases.

2021-07-02 17:34 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +      file: mapping.node.getSourceFile(),
I think this is wrong - `inputConsumerIdentifier` may be in an entirely different file than the template itself.

2021-07-02 21:12 UTC, danieltre23 commented
Flaky failures in presubmit: http://test/OCL:382577037:BASE:382802023:1625257425653:73bd3481 forced green.

2021-07-08 21:30 UTC, alxhub requested changes
Last round of comments - after this it should be good to go!

Also, even though this is an unlikely error, it's still a new error and thus we should only land it in a `minor` version instead of a `patch`.

2021-07-08 21:30 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +      text: `The property is bound to the '${inputConsumer.name.getText()}' component.`,
```suggestion
      text: `The property half of the binding is to the '${inputConsumer.name.getText()}' component.`,
```

2021-07-08 21:30 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +      let message = `The output binding is to a native event called '${input.name}' on the '${
```suggestion
      let message = `The event half of the binding is to a native event called '${input.name}' on the '${
```

2021-07-08 21:30 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +          outputConsumer.name}' DOM element.`;
Consider maybe `<${outputConsumer.name}>` instead of single quotes?

2021-07-08 21:30 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +        start: outputConsumer.sourceSpan.start.offset,
Let's be a little tricky here, and only highlight the tag name. We can do that by computing the start and end positions of the tag name.

Since the element looks like `<tag-name ....>`, we see that the tag name starts at the start span + 1, and ends at that start + the length of the tag name. That should be enough to find the tag name span.

2021-07-08 21:30 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +        text: `The event is bound to the '${outputConsumer.name.getText()}' component.`,
```suggestion
        text: `The event is bound to the '${outputConsumer.name.text}' component.`,
```

2021-07-08 21:30 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +    let relatedMessages = [];
It's always good to explicitly type arrays like this. Also, this can be `const` since we don't need to change its value.

2021-07-08 21:30 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/template_typecheck_spec.ts
> +      expect(getSourceCodeForDiagnostic(diags[0])).toBe('[(value)]="counterValue"');
We should assert that the related messages are also pointing to the right things.

2021-07-08 21:30 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts
> +        templateId, mapping, input.sourceSpan, ts.DiagnosticCategory.Error,
```suggestion
        templateId, mapping, input.keySpan, ts.DiagnosticCategory.Error,
```

This will limit the diagnostic to highlight the left side of the binding (`[(foo)]`) instead of the whole expression, which looks cleaner.

2021-07-09 18:08 UTC, danieltre23 commented
Flaky failures in presubmit: http://test/OCL:382577037:BASE:383866895:1625849540387:7301e2db forced green.

2021-07-09 18:52 UTC, alxhub approved these changes

2021-07-09 18:52 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/diagnostics/src/diagnostic.ts
> +      relatedMessages.forEach(relatedMessage => {
```suggestion
      for (const relatedMessage of relatedMessages) {
```

Besides being easier to debug, this will also allow TypeScript to better understand how the types are narrowed here, so you shouldn't need to use `?.push()`.

2021-07-09 18:52 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/diagnostics/src/diagnostic.ts
> +        relatedInformation?.push({
Just as an FYI, this is a situation where you, as a developer, know that `relatedInformation` can never be `undefined` here - it's initialized above. In this case, using the non-null assertion operator (`!`) is more correct than safe navigation (`?.`). But, switching to an actual loop instead of `.forEach` (which we almost never use in the compiler these days) should make this unnecessary.

2021-07-09 18:52 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/diagnostics/src/diagnostic.ts
> +      relatedMessages.forEach(relatedMessage => {
Same here.

2021-07-09 21:09 UTC, alxhub commented
Reviewed-for: public-api

2021-07-09 21:27 UTC, atscott approved these changes
reviewed-for: public-api

2021-07-09 21:29 UTC, jessicajaniuk approved these changes
LGTM :cookie:

I left a couple of suggestions, but nothing I feel strongly about.

reviewed-for: public-api

2021-07-09 21:29 UTC, jessicajaniuk commented on packages/compiler-cli/src/ngtsc/typecheck/diagnostics/src/diagnostic.ts
> +      relatedMessages.forEach(relatedMessage => {
You could also consider using `.reduce` here since you're transforming the data while iterating through it. That would look like
```
let relatedInformation = relatedMessages.reduce((infoArr, relatedMessage) => {
       infoArr.push({
          category: ts.DiagnosticCategory.Message,
          code: 0,
          file: relatedMessage.sourceFile,
          start: relatedMessage.start,
          length: relatedMessage.end - relatedMessage.start,
          messageText: relatedMessage.text,
       });
       return infoArr;
}, []);
```

2021-07-09 21:29 UTC, jessicajaniuk commented on packages/compiler-cli/src/ngtsc/typecheck/src/type_check_block.ts
> +function checkIsSplitTwoWayBinding(
The naming here is a bit redundant. `checkIsSplitTwoWayBinding` vs just `isSplitTwoWayBinding`. Both mean the same thing.

2021-07-09 21:46 UTC, danieltre23 commented
@jessicajaniuk updated relatedMessages to use for-of per a separate suggestion from Alex.

2021-07-12 11:36 UTC, petebacondarwin approved these changes
Reviewed-for: public-api

2021-07-13 05:31 UTC, dgp1130 commented
One final TGP looks good: http://test/OCL:384348576:BASE:384348514:1626141913210:709ae796

2021-07-13 15:47 UTC, closed without merging

2021-07-13 21:15 UTC, zarend commented
👍 🍌 📦💥