fix(docs-infra): remove unnecessary `Title` provider in AppModule
angular/angular pull request #42696
Opened 2021-06-29 08:22 UTC by kroeder

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The docs show an example of  `providers: [Title]` in `AppModule` in https://angular.io/guide/set-document-title

## What is the new behavior?

The `Title` service uses `providedIn: 'root'` and therefore does not need to be provided in `AppModule` anymore.
https://stackblitz.com/edit/angular-ivy-vma9du?file=src/app/app.component.ts

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Although this PR makes the docs more correct I'm still not yet satisfied. E.g. is every paragraph in `Why provide the Title service in bootstrap` really useful? To me, it would be important to know that `Title` is something that works differently on each platform (Mobile, Browser, etc.) 

But things like the code snippet of `main.ts` that represents a default main.ts without any changes is not.

If you agree I'd like to add a commit (or open another PR) with a suggestion. Though, I'm also no expert in terms of writing great docs. 🙂

2021-06-29 14:08 UTC, mary-poppins commented
You can preview 9ce59b7 at https://pr42696-9ce59b7.ngbuilds.io/.

2021-06-29 14:14 UTC, petebacondarwin requested changes
Thanks for updating our docs examples to best practices.

There is a section following the "complete example" that discusses registering the `Title` service. Since this now happens implicitly by injecting it into the `AppComponent` this whole section needs to be rewritten, otherwise it doesn't make sense.

2021-06-29 14:14 UTC, petebacondarwin commented on aio/content/guide/set-document-title.md
> -  <code-pane header="src/app/app.module.ts" path="set-document-title/src/app/app.module.ts"></code-pane>
I am not sure if this should be deleted. The `main.ts` file imports this file, so for this example to be a "complete" solution, it is still needed.

2021-06-29 14:14 UTC, petebacondarwin commented on aio/content/examples/set-document-title/src/app/app.module.ts
> -    Title
The `Title` import can also be removed.

2021-06-29 14:29 UTC, kroeder commented on aio/content/guide/set-document-title.md
> -  <code-pane header="src/app/app.module.ts" path="set-document-title/src/app/app.module.ts"></code-pane>
Can't we as well remove `main.ts` because it does not offer any further information about the `Title` service and how to use it?

2021-06-29 14:44 UTC, petebacondarwin commented on aio/content/guide/set-document-title.md
> -  <code-pane header="src/app/app.module.ts" path="set-document-title/src/app/app.module.ts"></code-pane>
That's an option but then I think we would need to reword the guide since it is no longer a "complete" solution.

2021-06-30 13:22 UTC, kroeder commented on aio/content/guide/set-document-title.md
> -  <code-pane header="src/app/app.module.ts" path="set-document-title/src/app/app.module.ts"></code-pane>
Okay, next try: How about only showing the `app.component.ts` example + add a stackblitz link to the complete solution? 🙂  Every other code snippet in the documentation got one 

Whatever you decide, should we add a StackBlitz link nonetheless?

2021-06-30 13:39 UTC, petebacondarwin commented on aio/content/guide/set-document-title.md
> -  <code-pane header="src/app/app.module.ts" path="set-document-title/src/app/app.module.ts"></code-pane>
> Okay, next try: How about only showing the app.component.ts example + add a stackblitz link to the complete solution? 🙂 Every other code snippet in the documentation got one

This works for me!

2021-06-30 14:45 UTC, kroeder commented on aio/content/guide/set-document-title.md
> -  <code-pane header="src/app/app.module.ts" path="set-document-title/src/app/app.module.ts"></code-pane>
At the top of the page, there's already this one https://stackblitz.com/angular/yjpkxkvjbjxq
Can you take care of it in case you want/need to update something in the StackBlitz example? 🙂 

Also, I cannot find any documentation with a code snippet that has the "show in stackblitz" icon at the top-right corner
Is this something you don't do anymore? That was my original plan.

2021-06-30 14:58 UTC, petebacondarwin commented on aio/content/guide/set-document-title.md
> -  <code-pane header="src/app/app.module.ts" path="set-document-title/src/app/app.module.ts"></code-pane>
> I cannot find any documentation with a code snippet that has the "show in stackblitz" icon at the top-right corner

This is only in the Angular Material docs, I think.

2021-06-30 14:59 UTC, petebacondarwin commented on aio/content/guide/set-document-title.md
> -  <code-pane header="src/app/app.module.ts" path="set-document-title/src/app/app.module.ts"></code-pane>
The stackblitz links are generated by the `<live-example>` component which you place in the markdown.

2021-10-27 23:24 UTC, closed without merging