docs(docs-infra): edit and add docs for ng-template
angular/angular pull request #42704
Opened 2021-06-29 21:20 UTC by dario-piotrowicz

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

Issue Number: https://github.com/angular/angular/issues/42678

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2021-06-30 07:36 UTC, mary-poppins commented
You can preview 41584cd at https://pr42704-41584cd.ngbuilds.io/.

2021-06-30 08:07 UTC, petebacondarwin requested changes
Great start - thanks for identifying all the use cases and relevant aspects of ng-template.
I left a lot of comments. Feel free to take what you think works.

2021-06-30 08:07 UTC, petebacondarwin commented on aio/content/special-elements/core/ng-template.md
> +    Inside the `<ng-template>` tags developers can reference variables present in the outer template in which the elements are defined, moreover `<ng-template>` elements can also have an associated c
Can we provide an example of how to do this?

2021-06-30 08:07 UTC, petebacondarwin commented on aio/content/special-elements/core/ng-template.md
> +    _This is for example how `<ng-template>` elements are used as [ngIf](/api/common/NgIf) else clauses._
```suggestion
    _This is how `<ng-template>` elements are used as [ngIf](/api/common/NgIf) else clauses._
```

2021-06-30 08:07 UTC, petebacondarwin commented on aio/content/special-elements/core/ng-template.md
> +    Such template variables can also be used to reference `<ng-template>` elements in the component's template when using [`ngTemplateOutlet`](/api/common/NgTemplateOutlet) directives.
Should we show an example of this too?

2021-06-30 08:07 UTC, petebacondarwin commented on aio/content/special-elements/core/ng-template.md
> +- **can be used to programmatically**
```suggestion
### Querying for templates
```

2021-06-30 08:07 UTC, petebacondarwin commented on aio/content/special-elements/core/ng-template.md
> +    A [Query](/api/core/Query) can find the `TemplateRef` associated to an `<ng-template>` element and then it can be used to directly create embedded views using the `ViewContainerRef`'s `createEmbe
I think it might be better to talk about ContentQuery and ViewQuery explicitly rather than the generic Query class... what do you think?

An example would also be very helpful here.

2021-06-30 12:43 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +    Inside the `<ng-template>` tags developers can reference variables present in the outer template in which the elements are defined, moreover `<ng-template>` elements can also have an associated c
maybe, but this is already covered in the [`NgTemplateOutlet` docs](https://angular.io/api/common/NgTemplateOutlet)

maybe I could put an example using `createEmbeddedView`?

2021-06-30 12:45 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +    Such template variables can also be used to reference `<ng-template>` elements in the component's template when using [`ngTemplateOutlet`](/api/common/NgTemplateOutlet) directives.
again this is already presented in the `ngTemplateOutlet` docs and since they are referenced there directly it is very straightforward for visitors to just click the link and see the example

so I am not totally sure, I do can put a small example anyway if you feel it'd be good

please let me know what you think about it :slightly_smiling_face:

2021-06-30 13:00 UTC, petebacondarwin commented
OK - so let's go without the examples for now. We will get the docs team (e.g. @TeriGlover) to go over it once you are happy.

2021-06-30 13:11 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +    A [Query](/api/core/Query) can find the `TemplateRef` associated to an `<ng-template>` element and then it can be used to directly create embedded views using the `ViewContainerRef`'s `createEmbe
About the generic `Query` I kind of just followed the [`templateRef` docs](https://angular.io/api/core/TemplateRef#description), I may amend it I'd imagine (would you also like me to chage the `templateRef` docs?)

About the example, yeah I actually had a quick look and at a first glance no such example does not seem to in the docs, so that would definitely be a good addition :slightly_smiling_face: 

but I am not 100% sure if it should be added here or in the `templateRef` docs, as it is kind of more related to that, what do you think?

2021-06-30 13:14 UTC, petebacondarwin commented on aio/content/special-elements/core/ng-template.md
> +    A [Query](/api/core/Query) can find the `TemplateRef` associated to an `<ng-template>` element and then it can be used to directly create embedded views using the `ViewContainerRef`'s `createEmbe
I think you are right that this doc should just reference the detail (including examples) in other docs.
If there is no example for this, perhaps an extra PR with such an example would be a good future task.

2021-06-30 19:37 UTC, dario-piotrowicz commented
Thanks a lot @petebacondarwin yeah ok, I like the idea let's leave the examples for later
(we can add them to the issue and track the progress there)

I will get on with the changes and will let you know when I am happy with them :slightly_smiling_face:

2021-06-30 21:06 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +> When using the [structural directive shorthand](/guide/structural-directives#structural-directive-shorthand), Angular creates an `<ng-template>` element behind the scenes.
I tired using `>` here and below.... I am not completely sure about the result...

2021-06-30 21:07 UTC, dario-piotrowicz commented
@petebacondarwin I hope I am not bothering you too much, I made changes and I was hoping you could give it another glance? :sweat: 

I followed you comments but I changed something here and there, I hope it's fine :slightly_smiling_face:

2021-06-30 21:14 UTC, mary-poppins commented
You can preview 4ce7c48 at https://pr42704-4ce7c48.ngbuilds.io/.

2021-07-01 11:21 UTC, petebacondarwin reviewed
Looking good. I made a few more suggestions.

2021-07-01 11:21 UTC, petebacondarwin commented on aio/content/special-elements/core/ng-template.md
> +> When using the [structural directive shorthand](/guide/structural-directives#structural-directive-shorthand), Angular creates an `<ng-template>` element behind the scenes.
I think we should avoid block quotes. They are not used in any of our other docs.
If you want to call out this paragraph then you could use an [alert or callout](https://angular.io/guide/docs-style-guide#alerts-and-callouts).
```

2021-07-01 11:21 UTC, petebacondarwin commented on aio/content/special-elements/core/ng-template.md
> +This class exposes methods to make use of the defined template's content.
Actually i don't think one generally uses this object directly, right?
Instead what about saying:

```suggestion
Pass this object to `ViewContainerRef.createEmbeddedView()` in order to add copies of the template to the DOM.
```

2021-07-01 11:21 UTC, petebacondarwin commented on aio/content/special-elements/core/ng-template.md
> +A [Query](/api/core/Query) (such as `ViewChild`) can find the `TemplateRef` associated to an `<ng-template>` element so that it can be used programmatically. Generally to directly create embedded vie
This last sentence doesn't make sense to me:

> Generally to directly create embedded views via the `ViewContainerRef`'s `createEmbeddedView` method.

Did you mean something like:

> For instance, to pass it to the `ViewContainerRef.createEmbeddedView()` method.

2021-07-01 11:21 UTC, petebacondarwin commented on aio/content/special-elements/core/ng-template.md
> +Inside the `<ng-template>` tags you can reference variables present in the surrounding outer template, additionally a context objects can be associated to `<ng-template>` elements, such object can co
```suggestion
Inside the `<ng-template>` tags you can reference variables present in the surrounding outer template.
Additionally, a context object can be associated with `<ng-template>` elements.
Such an object contains variables which can be accessed from within the template contents via template (`let` and `as`) declarations.
```

2021-07-01 13:45 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +> When using the [structural directive shorthand](/guide/structural-directives#structural-directive-shorthand), Angular creates an `<ng-template>` element behind the scenes.
yeah I considered using alerts, but they seems to be too strong, this text is not that important

I think I'll just leave it as normal text

2021-07-01 13:50 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +This class exposes methods to make use of the defined template's content.
you where the one who suggested that change! :stuck_out_tongue_winking_eye: 

anyway I am not totally convinced in mentioning `createEmbeddedView` here, as it is already mentioned below, and also `TemplateRef`s have more broad uses, for example they are used by `ngTemplateOutlet`

so I will change the text, but it's ok with you I would try to keep it generic here :slightly_smiling_face:

2021-07-01 13:53 UTC, petebacondarwin commented on aio/content/special-elements/core/ng-template.md
> +This class exposes methods to make use of the defined template's content.
Sorry if I misled you with my suggestions. They are more a guide than a requirement.
As long as these are technically correct, we can leave the docs-team to decide upon stylistic and language improvements.

2021-07-01 13:54 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +A [Query](/api/core/Query) (such as `ViewChild`) can find the `TemplateRef` associated to an `<ng-template>` element so that it can be used programmatically. Generally to directly create embedded vie
Sorry if my wording is confusing, what I tried to convey is that the most common use of a queried `TemplateRef` is to create a view using `createEmbeddedView` and that it id done directly as opposed to other views which created indirectly (by Angular)

I'll amend this thanks :slightly_smiling_face:

2021-07-01 14:08 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +This class exposes methods to make use of the defined template's content.
nono no need to apologise I was kidding :sweat: 

(and I so much appreciate all your help :slightly_smiling_face: )

I'll think of something to put here :slightly_smiling_face:

2021-07-01 14:14 UTC, mary-poppins commented
You can preview 2e8d3fd at https://pr42704-2e8d3fd.ngbuilds.io/.

2021-07-01 17:51 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +This class exposes methods to make use of the defined template's content.
Actually I have been thinking and it is a bit redundant to mention that the `TemplateRef` gets used by `ngTemplateOutlet` as that is sort of implied below, so there is no point in mentioning that again here

Besides that and `createEmbeddedView` I am not really sure if there are other uses of `TemplateRef`s to be honest :cry: 

 So I am just going with what you suggested, though I wonder if mentioning twice `ViewContainerRef.createEmbeddedView()` will look ugly :thinking:

2021-07-01 17:55 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +A [Query](/api/core/Query) (such as `ViewChild`) can find the `TemplateRef` associated to an `<ng-template>` element so that it can be used programmatically. Generally to directly create embedded vie
Sorry I just noticed that with `ViewContainerRef.createEmbeddedView()` we don't get the text to link to the method

Would the original version not be ok for you? 
```
`ViewContainerRef`'s `createEmbeddedView()` method
```

2021-07-01 18:04 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +A [Query](/api/core/Query) (such as `ViewChild`) can find the `TemplateRef` associated to an `<ng-template>` element so that it can be used programmatically. Generally to directly create embedded vie
Alternatively I could even go with: 
```
`ViewContainerRef`.`createEmbeddedView()`
```
which would look like this:
![Screenshot at 2021-07-01 19-02-56](https://user-images.githubusercontent.com/61631103/124170236-16aca300-da9f-11eb-9674-52a10966f901.png)

2021-07-01 18:12 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +A [Query](/api/core/Query) (such as `ViewChild`) can find the `TemplateRef` associated to an `<ng-template>` element so that it can be used programmatically. Generally to directly create embedded vie
or I can just copy what the TemplateRef docs do:
![Screenshot at 2021-07-01 19-08-44](https://user-images.githubusercontent.com/61631103/124170927-d568c300-da9f-11eb-8500-bf9f6926c0b4.png)

as in:
![Screenshot at 2021-07-01 19-11-28](https://user-images.githubusercontent.com/61631103/124171240-34c6d300-daa0-11eb-802c-2c9708f37a13.png)

2021-07-02 06:53 UTC, petebacondarwin commented on aio/content/special-elements/core/ng-template.md
> +A [Query](/api/core/Query) (such as `ViewChild`) can find the `TemplateRef` associated to an `<ng-template>` element so that it can be used programmatically. Generally to directly create embedded vie
Gosh! You are right. We should actually fix the auto-code linker to handle that better. But in the meantime, feel free to choose a form that you feel works best for you. Perhaps copying the `TemplateRef` approach for consistency?

2021-07-02 13:00 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +A [Query](/api/core/Query) (such as `ViewChild`) can find the `TemplateRef` associated to an `<ng-template>` element so that it can be used programmatically. Generally to directly create embedded vie
ok yeah, I just copied `TemplateRef`'s approach then :slightly_smiling_face:

2021-07-02 13:08 UTC, mary-poppins commented
You can preview 228c7fe at https://pr42704-228c7fe.ngbuilds.io/.

2021-07-02 13:12 UTC, dario-piotrowicz commented
@petebacondarwin Thanks for all your help :slightly_smiling_face: 

I made the PR ready for review as I hope that now the docs seem good enough to be passed on to the docs team

Hope you are happy with them too :slightly_smiling_face:

2021-07-02 14:02 UTC, petebacondarwin approved these changes
This is a considerable improvement over the current minimal docs for ng-element. Thanks @dario-piotrowicz.

Let's see what @aikidave or @TeriGlover have to say about styling, although I am not sure if they are online right now. We might need to wait a little while to get their review.

2021-07-02 14:08 UTC, dario-piotrowicz commented
Thanks a lot @petebacondarwin 

If this goes well the other two special elements are next :stuck_out_tongue_winking_eye: 

(plus the examples we said I could add for the templates :slightly_smiling_face: )

2021-07-02 15:55 UTC, jessicajaniuk approved these changes
LGTM :cookie:

This is great! Thanks for this work!

2021-07-03 09:29 UTC, mary-poppins commented
You can preview 5579ea0 at https://pr42704-5579ea0.ngbuilds.io/.

2021-07-09 19:24 UTC, TeriGlover approved these changes
Copy edit complete; several comments. Otherwise, LGTM.

2021-07-09 19:24 UTC, TeriGlover commented on aio/content/special-elements/core/ng-template.md
> +Such an object contains variables which can be accessed from within the template contents via template (`let` and `as`) declarations.
```suggestion
Such an object contains variables that can be accessed from within the template contents via template (`let` and `as`) declarations.
```

2021-07-09 20:53 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +With `<ng-template>`, you can define template content that is only being rendered by Angular when you (directly or not) specifically instruct it to do so, allowing you to have full control over how a
Yeah I didn't see that before but that "specifically" part definitely needs improvements, I will look into it thanks! :slightly_smiling_face:

2021-07-09 21:19 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +With `<ng-template>`, you can define template content that is only being rendered by Angular when you (directly or not) specifically instruct it to do so, allowing you to have full control over how a
About the "Further information available in the Usage Notes..."

That text is being set by dgeni in the docs generation as you can see here:
https://github.com/angular/angular/blob/9d58ebfcee7aef63b71bc133fc9f172d63fc9b14/aio/tools/transforms/templates/api/includes/description.html#L5

(and it is generated by the "@usages" below)

So I am not 100% sure if I can just change that as I am afraid that that is just out of scope here and also I am not sure how many docs actually use it, maybe I could investigate a bit and create a new PR for that change...

anyway I just wanted to say that it'd be a global change and is by no means restricted to this file

@petebacondarwin could you please advice on what to do here? :slightly_smiling_face:

2021-07-09 21:20 UTC, dario-piotrowicz commented on aio/content/special-elements/core/ng-template.md
> +Pass this object to the `ViewContainerRef` method `createEmbeddedView()` in order to add copies of the template to the DOM.
yeah your version looks nicer and clearer thanks! :slightly_smiling_face:

2021-07-09 21:31 UTC, dario-piotrowicz commented
@TeriGlover Thanks a lot for the review :slightly_smiling_face: , I addressed all your comments, all besides the Usage Notes text, I can amend that text, but would love to hear from @petebacondarwin if he agrees with my changing it here :slightly_smiling_face:

2021-07-09 21:38 UTC, mary-poppins commented
You can preview f290f84 at https://pr42704-f290f84.ngbuilds.io/.

2021-07-10 09:46 UTC, mary-poppins commented
You can preview 68f1b49 at https://pr42704-68f1b49.ngbuilds.io/.

2021-07-10 10:53 UTC, gkalpak reviewed
Drive-by review:
Please update the commit message to be `docs(core): ...`.
`docs(docs-infra): ...` means documentation about the documentation infrastructure (which is not what this PR is about :grin:).

2021-07-10 11:14 UTC, dario-piotrowicz commented
@gkalpak sorry about that, I've fixed it thanks! :slightly_smiling_face:

2021-07-10 11:26 UTC, mary-poppins commented
You can preview b9ea229 at https://pr42704-b9ea229.ngbuilds.io/.

2021-07-12 15:42 UTC, aikidave approved these changes
Thank you so much for this addition! LGTM!

Reviewed-for: global-docs-approvers

2021-07-12 16:39 UTC, closed without merging