refactor(docs-infra): migrate from tslint to eslint
angular/angular pull request #42820
Opened 2021-07-11 09:29 UTC by dario-piotrowicz

migration to eslint as tslint has been deprecated

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

`ng lint` runs the deprecated tslint

Issue Number: N/A

## What is the new behavior?
`ng lint` runs eslint

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2021-07-11 09:42 UTC, dario-piotrowicz commented
Hi @gkalpak :slightly_smiling_face: 

So, the migration is looking.... good?... hopefully? :sweat_smile: 

![Screenshot at 2021-07-11 10-41-04](https://user-images.githubusercontent.com/61631103/125190352-91f71d00-e234-11eb-828f-3a096efbc555.png)

I opened this draft PR so start a bit of a discussion and see how you see this, I hope you don't mind :slightly_smiling_face:

2021-07-11 09:43 UTC, dario-piotrowicz commented
First of all, what do you think of the incompatible typescript version? is this something we can accept or it's a deal breaker? :thinking: 

(I would not want to downgrade the current typescript just to accommodate eslint)

2021-07-11 09:45 UTC, dario-piotrowicz commented on aio/.eslintrc.json
> +          },
I needed to put this here as the eslint rule `no-console` didn't seem to be working... (no idea why... maybe it could be because of the typescript version mismatch?)

2021-07-11 09:51 UTC, dario-piotrowicz commented on aio/src/404-body.html
> +                <img src="assets/images/support/angular-404.svg" width="300" height="300" alt="not-found"/>
Fixes
![Screenshot at 2021-07-11 10-49-41](https://user-images.githubusercontent.com/61631103/125190597-e222af00-e235-11eb-87d7-b5a00c532dc1.png)

2021-07-11 09:56 UTC, dario-piotrowicz commented on aio/src/app/app.component.spec.ts
> +      const preventedScrolling = (currentTarget: { scrollTop: number, scrollHeight?: number, clientHeight?: number }, deltaY: number) => {
here and in the other instances of `:object`, I changed those as `object` seems to have issues
![Screenshot at 2021-07-11 10-54-29](https://user-images.githubusercontent.com/61631103/125190747-98869400-e236-11eb-9650-f5189f2aa091.png)

2021-07-11 09:59 UTC, dario-piotrowicz commented on aio/src/app/shared/search-results/search-results.component.ts
> +// not sure why the above eslint-disable comment is necessary (eslint bug?)
This is rather strange (again, may this be because of the typescript version mismatch? :thinking: )

eslint complains that `SearchState` gets shadowed... but it does not seem to be the case

2021-07-11 10:08 UTC, dario-piotrowicz commented on aio/src/app/custom-elements/resource/resource-list.component.html
> +      <span id="{{subCategory.id}}"></span>
fixes 
![Screenshot at 2021-07-11 11-03-44](https://user-images.githubusercontent.com/61631103/125190950-cd471b00-e237-11eb-9e42-eb63017dee43.png)

I had a look at the site and I am not sure the the `a` was necessary there

I guess the `id` is used for fragment navigation, but not sure why the element needed to be an anchor

2021-07-11 10:12 UTC, dario-piotrowicz commented on aio/src/app/custom-elements/resource/resource-list.component.html
> +      <span id="{{subCategory.id}}"></span>
Also I put the rule there to `"warn"`, not sure about it... should all our rules be `"error"`?

2021-07-12 15:08 UTC, rafaelss95 commented on aio/src/app/shared/search-results/search-results.component.ts
> +// not sure why the above eslint-disable comment is necessary (eslint bug?)
Have you tried to use [**`@typescript-eslint/no-shadow`**](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-shadow.md) instead?

2021-07-12 15:08 UTC, rafaelss95 commented on aio/.eslintrc.json
> +          }
I know it might have come from the automatic conversion, but you can condense these two into:

```suggestion
          {
            "selector": "CallExpression[callee.name=/^(fdescribe|fit)$/]",
            "message": "Don't keep jasmine focus methods."
          }
```

2021-07-12 18:19 UTC, dario-piotrowicz commented on aio/src/app/shared/search-results/search-results.component.ts
> +// not sure why the above eslint-disable comment is necessary (eslint bug?)
good point, I'll give it a shot thanks! :slightly_smiling_face:

2021-07-12 18:21 UTC, dario-piotrowicz commented on aio/src/app/custom-elements/resource/resource-list.component.ts
> +/* eslint-disable @angular-eslint/template/accessibility-elements-content */
ah! yeah I think you're right! thanks!!! :slightly_smiling_face:

2021-07-12 18:24 UTC, dario-piotrowicz commented on aio/.eslintrc.json
> +          }
good point! :slightly_smiling_face: 

This actually was not automated but it myself :sweat_smile:  (as the tslint ban rule doesn't have a 1-to-1 alternative), I did it separately as I thought that the two rules had each a different/specific message, I did notice that the error message was the same but forgot to combine the rules! thanks for noticing it! :slightly_smiling_face:

2021-07-12 20:03 UTC, rafaelss95 commented on aio/.eslintrc.json
> +          }
😮 Maybe you could have follow the steps described [here](https://github.com/angular-eslint/angular-eslint#migrating-an-angular-cli-project-from-codelyzer-and-tslint) 😄

2021-07-12 20:13 UTC, dario-piotrowicz commented on aio/.eslintrc.json
> +          }
yeah I did!

sorry if my comment was unclear :stuck_out_tongue_winking_eye: , I did follow that, what I meant is that the schematics failed to the tslint ban rules one rule (which did what I am doing here), they just provided such line in the log file: 
```
* tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "ban".
```

so I wrote this rule myself :slightly_smiling_face: 
(the schematics did an awesome job but after those I did need to do quite some manual adjustments and stuff)

2021-07-12 20:24 UTC, dario-piotrowicz commented on aio/src/app/shared/search-results/search-results.component.ts
> +// not sure why the above eslint-disable comment is necessary (eslint bug?)
spot on! :smiley:

2021-07-13 15:45 UTC, gkalpak commented on aio/src/app/custom-elements/resource/resource-list.component.html
> +      <span id="{{subCategory.id}}"></span>
I'd rather have errors over warnings whenever possible.

2021-07-13 19:02 UTC, gkalpak requested changes
Awesome work (as usual), @dario-piotrowicz ❤️
Just a few minor comments, but this is looking very promising :smiley:

2021-07-13 21:42 UTC, dario-piotrowicz commented
> Awesome work (as usual), @dario-piotrowicz 
> Just a few minor comments, but this is looking very promising

Thanks a lot for the kind words!!!! :slightly_smiling_face: 

Well, your comments don't seem to be "just a few" :sweat_smile: (I'm going to check them out now!),
I really hope I am not burdening you with this :sweat:
thank you so very much for taking the time to review the PR :smiling_face_with_three_hearts: 
___

By the way, could you comment on the typescript version warning? don't you see it as a problem here? :slightly_smiling_face:

2021-07-13 22:04 UTC, dario-piotrowicz commented on aio/src/app/custom-elements/resource/resource-list.component.html
> +      <span id="{{subCategory.id}}"></span>
got it, I'll see all rules to error :slightly_smiling_face: 

___

about the `h3` you are totally right... but yeah I am bit confused... why wasn't that done in the first place? are we missing something? :thinking: 

it's been like that for a long time: https://github.com/angular/angular/commit/196203f6d76ac5240d1485dbd9701bfb026eab56

but actually if you look at the commit also the categories were implemented in the same way, but those have been updated to `a` tags altogether around a year ago: https://github.com/angular/angular/commit/e672b1f2ac42b3a3b59f6020457318f8e1aa78dd 

I guess it is fine to change it, but yeah I am a bit confused on why it's been implemented that way :thinking: 

___

Actually.... I don't think any id is necessary/used here :confused: , we may want to clean those up (after this PR maybe? :) )
For example check this out: https://angular.io/resources#data-libraries (the url gets changed in the onInit regardless and the fragment gets ignored)

2021-07-13 22:07 UTC, dario-piotrowicz commented on aio/angular.json
> +    "defaultCollection": "@angular-eslint/schematics"
:open_mouth: wow yeah!

sorry the sneaky eslint schematics must have put that there when I run them for the automated conversion process, I didn't noticed this

I'll get rid of it :slightly_smiling_face:

2021-07-13 22:10 UTC, dario-piotrowicz commented on aio/angular.json
> +              "src/**/*.html"
yeah good point! :slightly_smiling_face: :+1:

2021-07-13 22:12 UTC, dario-piotrowicz commented on aio/package.json
> +    "@angular-eslint/template-parser": "12.2.2",
:sweat: 

I am no expert... they do seem necessary right? the only one I guess we could remove if we wanted to are the schematics I'd imagine

2021-07-13 22:13 UTC, dario-piotrowicz commented on aio/package.json
> +    "eslint-plugin-import": "latest",
my bad I was warned about this by the schematics but forgot to fix it! sorry! :sob:

2021-07-13 22:14 UTC, dario-piotrowicz commented on aio/package.json
> +}
it wasn't me, it was the schematics :see_no_evil:

2021-07-13 22:16 UTC, dario-piotrowicz commented on aio/src/404-body.html
> +                <img src="assets/images/support/angular-404.svg" width="300" height="300" alt="not-found"/>
ah yeah good point I will amend the md too :slightly_smiling_face: 

about the dash.... yeah sorry, force of habit I guess :sweat_smile:

2021-07-13 22:20 UTC, dario-piotrowicz commented on aio/src/app/custom-elements/resource/resource-list.component.ts
> +/* eslint-disable @angular-eslint/template/accessibility-elements-content */
sorry! I did remove it and forgot to push the change! on it! :stuck_out_tongue_winking_eye:

2021-07-13 22:22 UTC, dario-piotrowicz commented on aio/src/app/app.component.spec.ts
> +  /* eslint-disable quotes, @typescript-eslint/quotes */
yeah, this was done automatically and I didn't question it, it indeed doesn't make much sense... sorry :sweat:  I'll remove them anyways :slightly_smiling_face:

2021-07-13 22:33 UTC, dario-piotrowicz commented on aio/.eslintrc.json
> +    "projects/**/*"
the schematics mention something about `projects/`: https://github.com/angular-eslint/angular-eslint#step-2---run-the-convert-tslint-to-eslint-schematic-on-a-project

I guess this is done by default so that if we did have multiple projects eslint wouldn't be applied to all of them

Sorry I didn't notice this, I'll get rid of it :slightly_smiling_face:

2021-07-13 22:38 UTC, dario-piotrowicz commented on aio/.eslintrc.json
> +}
makes sense! I'll get right on it! :slightly_smiling_face:

2021-07-13 22:57 UTC, dario-piotrowicz commented on aio/src/app/custom-elements/code/code-example.component.ts
> +  /* eslint-disable quotes, @angular-eslint/no-input-rename */
sorry it was automated the `quotes` one is indeed unnecessary

Also I just saw that all automated `eslint-disable`s lack the `next-line` bit, I will amend that :disappointed:

2021-07-13 22:57 UTC, dario-piotrowicz commented on aio/src/app/custom-elements/code/code-example.component.ts
> +  /* eslint-disable quotes, @angular-eslint/no-input-rename */
same as above I'll fix it :slightly_smiling_face:

2021-07-13 22:57 UTC, dario-piotrowicz commented on aio/src/app/custom-elements/code/code.component.spec.ts
> +/* eslint-disable @typescript-eslint/member-ordering */
sorry what does? isn't this just a one-to-one conversion of the already existing rule? :sweat:

2021-07-13 22:57 UTC, dario-piotrowicz commented on aio/.eslintrc.json
> +          "e2e/tsconfig.json"
yeah, this was automated, I'm on it :slightly_smiling_face:

2021-07-14 08:58 UTC, alan-agius4 commented on aio/angular.json
> +              "src/**/*.html"
`tests/` is missing from the files to lint.

2021-07-14 08:58 UTC, alan-agius4 commented on aio/package.json
> +    "@angular-eslint/template-parser": "12.2.2",
`@angular-eslint/schematics` shouldn't be needed.

2021-07-14 08:59 UTC, alan-agius4 commented on aio/package.json
> +    "eslint-plugin-import": "^2.23.4",
This seems to be unused.

2021-07-14 09:00 UTC, alan-agius4 commented on aio/package.json
> +    "eslint-plugin-jsdoc": "^35.4.3",
Also this one.

2021-07-14 09:03 UTC, alan-agius4 commented on aio/.eslintrc.json
> +{
I am seeing a lot of missing rules from here. Was the tslint.json migrated using the migration tool
[Uploading Alan_Agius_-_Alan_Agius.pdf…]()
?

Example, `ban`, `no-console` rules are missing.

2021-07-14 09:05 UTC, alan-agius4 commented on aio/package.json
> +    "@angular-eslint/template-parser": "12.2.2",
Tbh, to keep the same lint behaviour we might need to add additional dependencies. IMHO, this is one of the biggest drawbacks of Eslint.

2021-07-14 09:49 UTC, dario-piotrowicz commented on aio/.eslintrc.json
> +{
There isn't an eslint `ban` rule, I used the `no-restricted-syntax` to accomplish the same thing here

2021-07-14 09:54 UTC, dario-piotrowicz commented on aio/package.json
> +    "@angular-eslint/template-parser": "12.2.2",
well, eslint is a more general purpose tool whilst tslint was typescript specific, so it kind of bundled for us everything we needed, things tat now we need to bring in with plugins... yeah not the best, but I think it is already quite impressive that eslint can manage tyepscript at all in the first place! :slightly_smiling_face:

2021-07-14 15:30 UTC, gkalpak commented on aio/src/app/custom-elements/resource/resource-list.component.html
> +      <span id="{{subCategory.id}}"></span>
Yeah, they are probably unusable. But let's keep them in this PR, since removing them is outside the scope of it. (Moving the IDs to the `h3` elements should preserve the previous behavior (broken or not), I think it is a good way to pass linting :smiley:)

2021-07-14 15:34 UTC, gkalpak commented on aio/package.json
> +    "@angular-eslint/template-parser": "12.2.2",
Yeah, I was hoping that `@typescript-eslint` or `@angular-eslint` could include the necessary dependencies and we wouldn't have to bring in (and have to manage) a ton of them 🤷‍♂️

2021-07-14 15:41 UTC, gkalpak commented on aio/src/app/custom-elements/code/code.component.spec.ts
> +/* eslint-disable @typescript-eslint/member-ordering */
Yeah, I mean the already existing rule was redundant (and by extention the updated rule is redundant as well :grin:)

2021-07-14 15:59 UTC, gkalpak requested changes
Thx for making the changes, @dario-piotrowicz :+1:
Getting closer 🏃‍♂️

> Well, your comments don't seem to be "just a few" 😅

Given the size of the PR, they were really "just a few" 😛

> I really hope I am not burdening you with this 😓
> thank you so very much for taking the time to review the PR 🥰

It would have taken me much more time to do the actual work myself, so thank _you_ for taking it on 💪

> By the way, could you comment on the typescript version warning? don't you see it as a problem here? 🙂

Sorry, I mean to comment on that, but then forgot.
Yeah, it's not ideal, but I don't think it is a problem here (as long as linting passes 😅).

##
<sub>**[NOTE-TO-SELF]** Unresolved comments from previous review:</sub>
<sub>https://github.com/angular/angular/pull/42820#discussion_r668897702, https://github.com/angular/angular/pull/42820#discussion_r668900621, https://github.com/angular/angular/pull/42820#discussion_r668906308, https://github.com/angular/angular/pull/42820#discussion_r668907227, https://github.com/angular/angular/pull/42820#discussion_r668908351, https://github.com/angular/angular/pull/42820#discussion_r668998288</sub>

2021-07-14 15:59 UTC, gkalpak commented on aio/.eslintrc.json
> +        "@typescript-eslint/member-delimiter-style": ["error", {
:grin:

```suggestion
        "@typescript-eslint/member-delimiter-style": ["error", {
          "singleline": {
            "delimiter": "comma",
            "requireLast": false
          }
        }],
```

2021-07-14 15:59 UTC, gkalpak commented on aio/.eslintrc.json
> +        }]
:grin:

```suggestion
        "semi": "error"
```

2021-07-14 20:08 UTC, dario-piotrowicz commented on aio/.eslintrc.json
> +        "@typescript-eslint/member-delimiter-style": ["error", {
:man_facepalming: sorry

2021-07-14 20:41 UTC, dario-piotrowicz commented on aio/src/app/custom-elements/code/code.component.spec.ts
> +/* eslint-disable @typescript-eslint/member-ordering */
ah ok :slightly_smiling_face: , removed :+1:

2021-07-14 20:41 UTC, dario-piotrowicz commented on aio/src/app/custom-elements/resource/resource-list.component.html
> +      <span id="{{subCategory.id}}"></span>
yeah agreed! I'm on it :slightly_smiling_face:

2021-07-14 20:41 UTC, dario-piotrowicz commented on aio/angular.json
> +              "src/**/*.html"
the addition of the tests one reveals other files that I need to amend there :sweat: 

I'll get on with it after fixing the other stuff, good catch! :slightly_smiling_face:

2021-07-14 20:58 UTC, dario-piotrowicz commented on aio/package.json
> +    "@angular-eslint/template-parser": "12.2.2",
I removed the schematics

I am honestly not sure about the others, I will look into whether they are necessary or not

(@alan-agius4 did you comment that some are not?)

2021-07-14 21:32 UTC, dario-piotrowicz commented
Just checked the `eslint-disable`s without `next-line` there were just two :slightly_smiling_face:

2021-07-14 21:34 UTC, dario-piotrowicz commented on aio/src/app/custom-elements/code/code-example.component.ts
> +  /* eslint-disable quotes, @angular-eslint/no-input-rename */
actually I think only the two `eslint-disable`s in this file lacked the `next-line` :sweat_smile:

2021-07-14 21:49 UTC, dario-piotrowicz commented on aio/package.json
> +    "@angular-eslint/template-parser": "12.2.2",
Here's a description of the dependencies: https://github.com/angular-eslint/angular-eslint#packages-included-in-this-project

I have read them the descriptions and had a (very) quick look at the sources and I do think that:
 - `builder` is necessary (to actually execute eslint)
 - `eslint-plugin` is necessary for the `@angular-eslint` rules (we have them)
 - `template-parser` is necessary for the parsing of the templates (which we have rules for)
 - `eslint-plugin-template` is necessary for the `@angular-eslint/template` rules (we have them)
 - `schematics`, I actually removed them but maybe they could be useful for maintaining eslint in the project? :thinking:

2021-07-14 22:22 UTC, dario-piotrowicz commented
@gkalpak I think that it's looking good :smiley: 

I was about to put this as ready for review but I noticed that the `test_aio` is failing and it is because of the `example-lint` and `tools-lint` scripts which don't work anymore as they use tslint which has been removed as part of the migration

I did not notice those before (and I am not sure what they are about), I will have a look tomorrow, hopefully once these are taken care of we will be in a good place with this :slightly_smiling_face:

2021-07-15 12:03 UTC, gkalpak commented
> I was about to put this as ready for review but I noticed that the `test_aio` is failing and it is because of the `example-lint` and `tools-lint` scripts which don't work anymore as they use tslint which has been removed as part of the migration

Ah, good point. For now, I think it is better to just focus on migrating the AIO app to eslint and keep tslint for the other scripts that need it (to keep the PR scope manageable). In a follow-up PR we can look into switching to eslint for more AIO scripts.

2021-07-15 14:04 UTC, dario-piotrowicz commented
All right @gkalpak !!! :rocket: 

I reinstated tslint and codelyzer and all seems to pass (the ci was a bit flaky and I needed to re-run it a couple of times :sweat_smile:)

it's looking quite good I think/hope :smile:

Today after work I'll put there a good comprehensive commit message and I will move it to ready for review :slightly_smiling_face:

2021-07-15 21:14 UTC, dario-piotrowicz commented
So commit message updated and PR ready for review, hopefully we're in a good spot now and we're getting close! :slightly_smiling_face: 

@rafaelss95 and @alan-agius4  thanks a lot for your nice reviewing I really appreciate it!!! :slightly_smiling_face: 
( @rafaelss95 not sure why I am not able to re-request your review :confused: )
(please feel free to check again the PR with the latest changes if you'd like)

And of course @gkalpak can't really thank you enough for all the support you always give me!!!! :smiling_face_with_three_hearts:

2021-07-16 13:22 UTC, gkalpak approved these changes
Looks awesome 🏆
Thank you so much for taking care of this, @dario-piotrowicz 😍

And the detailed commit message is super helpful too :100:

##
One last question regarding:
> for some reason the "no-console" rule would not work in eslint and has been substituted with an equivalent "no-restricted-syntax" one

What exactly didn't work with the `no-console` rule? (I've never had problems with it in other projects 😕)

2021-07-16 13:22 UTC, gkalpak commented on aio/tests/e2e/src/app.e2e-spec.ts
> +
Nit: 

```suggestion
```

2021-07-16 13:22 UTC, gkalpak commented on aio/tests/deployment/e2e/site.po.ts
>      return await results.map<string>(link => link!.getText());
I think you can also do `(link as ElementFinder).getText()` or even `link?.getText()` and avoid disabling the lint rule.

2021-07-16 14:32 UTC, dario-piotrowicz commented
> Looks awesome 
> Thank you so much for taking care of this, @dario-piotrowicz 
> 
> And the detailed commit message is super helpful too 
> 
> One last question regarding:
> 
> > for some reason the "no-console" rule would not work in eslint and has been substituted with an equivalent "no-restricted-syntax" one
> 
> What exactly didn't work with the `no-console` rule? (I've never had problems with it in other projects )
> 
> Reviewed-for: global-docs-approvers

thanks!!!!! :heart_eyes: 

about the `"no-console"`, sorry that's just another silly mistake of mine :see_no_evil: :sweat_smile: 

I just checked and it does work, the issue now is that the eslint rule has the `allows` option in which you specify which methods you want to allow, whilst the tslint rule made you specify which you didn't want to allow.

so with `no-restricted-syntax` I am keeping the same exact behaviour here, if I had to do the same with `no-console` I think I'd have to specify quite some methods :sad (https://developer.mozilla.org/en-US/docs/Web/API/Console#methods)

Alternatively I can just put `no-console` and only allow `log`, `warn` and `error`, that should also be pretty similar I think

what do you think the best solution here would be? :slightly_smiling_face:

2021-07-17 16:05 UTC, gkalpak reviewed
Cool! I think enabling the `no-console` rule and only allowing `log`, `warn` and `error` is fine. (We could also consider `info` and `debug`, but they are not used anywhere, we can leave them out for now.)

2021-07-19 18:16 UTC, dario-piotrowicz commented
@gkalpak should be all good now :smiley:

2021-07-20 09:51 UTC, gkalpak approved these changes
:100: 🚀 :shipit:

2021-07-20 09:51 UTC, gkalpak commented on aio/.eslintrc.json
> +        "no-console": [ "error", {"allow": ["log", "warn", "error"]} ],
Super-nit: Let's be consistent with whitespace around array brackets:

```suggestion
        "no-console": ["error", {"allow": ["log", "warn", "error"]}],
```

##
Meta-question: Who lints your lint-config 🤔 😛

2021-07-20 10:16 UTC, dario-piotrowicz commented on aio/.eslintrc.json
> +        "no-console": [ "error", {"allow": ["log", "warn", "error"]} ],
sorry :bow: 

About the linting on the lint-config, who needs that when we've got such an awesome reviewer!? :heart_eyes: :stuck_out_tongue_winking_eye: 

`gkalpakLint` for the win! :rocket:

2021-07-20 18:55 UTC, alxhub commented
I switched this to `target: minor` because it doesn't merge cleanly into the current patch branch (`12.1.x`). Given the nature of this change, I think this is probably fine.

2021-07-20 18:55 UTC, closed without merging