docs(animations): improve the aio animations introduction
angular/angular pull request #42885
Opened 2021-07-17 16:49 UTC by dario-piotrowicz

slight improvements to the angular.io animation introduction guide

URLs: 
 - https://angular.io/guide/animations
 - https://angular.io/guide/transition-and-triggers
 - https://angular.io/guide/complex-animation-sequences
 - https://angular.io/guide/reusable-animations
 - https://angular.io/guide/route-animations

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
I appreciate that some of these changes may be based on personal preferences/opinions, I'll naturally remove anything you don't agree with :slightly_smiling_face: 
( but I do believe that some in here are objective improvements :slightly_smiling_face: )

I'll also add comments in the PR for not self-explanatory changes :slightly_smiling_face:

2021-07-17 17:12 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/hero-list-page.component.html
> -<form>
the form is not used in the example, so I think it should remove to keep the examples as simple as they can be

2021-07-17 17:12 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/hero-list-page.component.ts
> -        query('.hero, form', [
the form is not really related to the list we want to animate

2021-07-17 17:12 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/hero-list-page.component.ts
> +          stagger(30, [
The guide specifies that the elements enter from top to bottom but if the stagger value is negative they are inserted from bottom to top

[stackblitz example](https://stackblitz.com/edit/angular-anim-stagger-positive-vs-negative?file=src%2Fapp%2Fheroes%2Fheroes.component.ts)

2021-07-17 17:12 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/hero-list-page.component.ts
> +          style({ opacity: 0, width: 0 }),
here and below I just thought that `0` looks nicer and also shows that `width`'s value does not necessarily need to be a string

2021-07-17 17:12 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/open-close.component.4.ts
> +        backgroundColor: 'blue'
above we have `'yellow'` but here we have a hex instead, I think it would be nicer the have the two consistent

2021-07-17 17:12 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/open-close.component.ts
> +        backgroundColor: 'blue'
above we have `'yellow'` but here we have a hex instead, I think it would be nicer the have the two consistent

2021-07-17 17:14 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/hero-list-page.component.ts
> -// #enddocregion filter-animations
the example uses the variable so I think it makes sense to include how the value is computed in it

2021-07-17 17:15 UTC, dario-piotrowicz commented on aio/content/guide/animations.md
> +<td><code><a href="api/animations/state" class="code-anchor">state</a>()</code></td>
all standard method references in the docs don't have the brackets included in the link

2021-07-17 17:19 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> +* <code><a href="api/animations/group" class="code-anchor">group</a>()</code> runs multiple animation steps in parallel.
here and in other places I make this change, it makes for an uglier markdown but a much nicer and more consistent outcome

before:
![Peek 2021-07-17 18-17](https://user-images.githubusercontent.com/61631103/126044847-928dd5c4-d484-492b-8d86-e11b89263356.gif)

after:
![Peek 2021-07-17 18-18](https://user-images.githubusercontent.com/61631103/126044852-22c40f78-1990-47e7-a111-46f81742efc5.gif)

2021-07-17 17:22 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> +* For each of these elements, use `style()` to set the same initial style for the element. Make it transparent and use `transform` to move it out of position so that it can slide into place.
not sure about the word `invisible` makes me think of the css visibility property...

I think "transparent" is actually a better word here (it is the synonym of opaque)

2021-07-17 17:23 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> +making things more complex -->
sorry, regardless on my typo I put this here for myself as a reminder I will remove it

but yeah I do believe that the example here is unnecessarily complex and that it could be simpler

2021-07-17 17:24 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> +Let's take a look at another animation example. We have a search input which filters some heroes.
I have no idea what live example page this is mentioning (I mean, I've found it in the code, but I could not find it in the docs)

2021-07-17 17:26 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> -The animation does the following:
This was not the best wording I believe, for example we had something like:

- The animation does the following:
 * Ignores any animations ...
 
doesn't really make too much sense, does it? :confused:

2021-07-17 22:16 UTC, dario-piotrowicz commented on aio/content/guide/reusable-animations.md
> +In the above code snippet, `transitionAnimation` is made reusable by declaring it as an export variable.
this was inconsistent, in the code the variable is actually called `transitionAnimation`:
![Screenshot at 2021-07-17 17-50-54](https://user-images.githubusercontent.com/61631103/126050411-9a8bfdd5-9705-48a9-8d29-c79135316cf6.png)

2021-07-17 22:30 UTC, dario-piotrowicz commented on aio/content/guide/route-animations.md
> +The animation definition (which we will break down in the next sections) does several things:
here and below I wanted to emphasise that the next sections break down the same example

In the guide ([link](http://localhost:4200/guide/route-animations#animation-definition)) that's not made clear and got me quite confused while reading

(I wasn't sure if it was adding or improving the example or something)

2021-07-17 22:32 UTC, dario-piotrowicz commented on aio/content/guide/transition-and-triggers.md
> +Wildcard states are more useful when an element in one particular state has multiple potential states that it can change to.
better seems a pretty ambiguous term here, how are they better? do they change?

2021-07-17 22:52 UTC, dario-piotrowicz commented on aio/content/guide/transition-and-triggers.md
> +In the HTML template, the animation event is passed back via `$event`, as `@triggerName.start` and `@triggerName.done`, where `triggerName` is the name of the trigger being used.
if we used `trigger` as the name, the word would be considered a link to the animation trigger function is just wrong and confusing:
![Screenshot at 2021-07-17 23-44-07](https://user-images.githubusercontent.com/61631103/126050962-24d81212-69af-480d-96d8-a6c22804d94b.png)

___

Besides that, we already use the term `triggerName` in the first page of the guide ([link](http://localhost:4200/guide/animations#defining-animations-and-attaching-them-to-the-html-template)):
![Screenshot at 2021-07-17 23-45-18](https://user-images.githubusercontent.com/61631103/126050989-783ae6a7-d1dd-4088-963c-72901ab07d44.png)
so using it here is also more consistent

2021-08-20 12:04 UTC, dario-piotrowicz commented
@petebacondarwin  so sorry for bothering you :bow: , I was just wondering if you could help me out getting a pair of eyes on this PR as I think I am making a few nice improvements to the docs but I'm afraid this PR is just getting forgotten :cry:

2021-08-20 20:03 UTC, petebacondarwin commented
I'm going to ping @aikidave on this one to get some review from the docs team.

2021-08-20 21:04 UTC, dario-piotrowicz commented
> I'm going to ping @aikidave on this one to get some review from the docs team.

Thank you so very much!!! :slightly_smiling_face: :slightly_smiling_face: :slightly_smiling_face:

2021-08-20 22:48 UTC, aikidave commented
I'm on this! Stay tuned, Dario! Won't keep you waiting!

On Fri, Aug 20, 2021 at 2:04 PM Dario Piotrowicz ***@***.***>
wrote:

> I'm going to ping @aikidave <https://github.com/aikidave> on this one to
> get some review from the docs team.
>
> Thank you so very much!!! 🙂 🙂 🙂
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/pull/42885#issuecomment-902956383>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHGDHY54EINELB3W42WKEDTT527OJANCNFSM5ARHLDXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-21 08:50 UTC, dario-piotrowicz commented
> I'm on this! Stay tuned, Dario! Won't keep you waiting!
> […](#)

@aikidave  Thanks!!!!! :heart_eyes: :heart_eyes: :heart_eyes:

2021-08-30 15:31 UTC, aikidave reviewed
Wow. There's a lot here, @dario-piotrowicz. I appreciate all the thought you've clearly put into this.

I've made some wording suggestions to help make the meaning a little clearer. Reviewing this PR, however, makes me think that we could do even more to make this content easier for developers to read. 

Your PR is a great step forward in that effort! Thank you!

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/animations.md
> +Use the `style()` function to define a set of styles to associate with a given state name. Note that the style attributes containing dashed must either be written in [*camelCase*](guide/glossary#case
```suggestion
Use the `style()` function to define a set of styles to associate with a given state name. You must write style attributes that contain dashes in [*camelCase*](guide/glossary#case-conventions), such as `'backgroundColor'` or denoted as strings, such as `'background-color'`.
```

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/complex-animation-sequences.md
> +You've seen how to add a delay between each successive animation. But you may also want to configure animations that happen in parallel. For example, you may want to animate two CSS properties of the
```suggestion
Previous sections describe how to add a delay between successive animations. But you might also want to configure animations that happen in parallel. For example, you might want to animate two CSS properties of the same element but use a different `easing` function for each one. To accomplish this task, you can use the animation <code><a href="api/animations/group" class="code-anchor">group</a>()</code> function.
```

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/complex-animation-sequences.md
> +Let's take a look at another animation example. We have a search input which filters some heroes.
Hm. Are we missing a link? If so, let's add it! Can you tell me where the example is?

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/complex-animation-sequences.md
> -The animation does the following:
What about:

"The code in this example performs the following tasks:" ?

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/complex-animation-sequences.md
> +* Doesn't animate any element when the user first opens or navigates to this page (the filter animation narrows what is already there, so it only works on elements already exist in the DOM).
```suggestion
* Skips animating elements when the user first opens or navigates to this page (the filter animation narrows what is already there, so it only works on elements that already exist in the DOM).
```

What do you think of this wording?

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/route-animations.md
> +Let's illustrate a router transition animation by navigating between two routes, *Home* and *About* associated with the `HomeComponent` and `AboutComponent` views respectively. Both of these componen
```suggestion
Let's illustrate a router transition animation by navigating between two routes, *Home* and *About*, which are associated with the `HomeComponent` and `AboutComponent` views respectively. Both of these component views are children of the top-most view, hosted by `AppComponent`. We'll implement a router transition animation that slides in the new view from the left and slides out to the right the old view when the user navigates between the two.
```

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/route-animations.md
> +Use the `RouterModule.forRoot` method to define a set of routes. Also, import this `RouterModule` by adding it to the `imports` array of the main module, `AppModule`.
```suggestion
Use the `RouterModule.forRoot` method to define a set of routes. Also, add `RouterModule` to the `imports` array of the main module, `AppModule`.
```

Just tightening up the wording here.

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/route-animations.md
> +**Note:** Use the `RouterModule.forRoot` method in the root module, `AppModule`, to register top-level application routes and providers. For feature modules, call the  `RouterModule.forChild` method
```suggestion
**Note:** Use the `RouterModule.forRoot` method in the root module, `AppModule`, to register top-level application routes and providers. For feature modules, call the `RouterModule.forChild` method instead.
```

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/route-animations.md
> +After configuring the routes, tell the Angular router where to render the views when matched with a route. You can set a router outlet by inserting a `<router-outlet>` directive inside the root `AppC
```suggestion
After configuring the routes, add a `<router-outlet>` to configure where to render the views when matched with a route. You can set a router outlet by inserting a `<router-outlet>` directive inside the root `AppComponent` template.
```

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/transition-and-triggers.md
> +Let's now add a new behavior:
```suggestion
Add a new behavior:
```

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/transition-and-triggers.md
> +**Note:** The following example uses `query()` and `stagger()` methods, which are discussed in the [complex sequences](guide/complex-animation-sequences#complex-sequence) page.
```suggestion
**Note:** The following example uses `query()` and `stagger()` methods. For more information on these methods, see the [complex sequences](guide/complex-animation-sequences#complex-sequence) page.
```

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/transition-and-triggers.md
> +In the code snippet above, the HTML template binds a `<div>` element to a trigger named `openClose` with a status expression of `isOpen`, and with possible values of `true` and `false`. This is an al
```suggestion
In the code snippet above, the HTML template binds a `<div>` element to a trigger named `openClose` with a status expression of `isOpen`, and with possible values of `true` and `false`. This pattern is an alternative to the practice of creating two named states like `open` and `close`.
```

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/transition-and-triggers.md
> +In the component code, inside the `@Component` metadata under the `animations:` property, when the state evaluates to `true` (meaning "open" here), the associated HTML element's height is a wildcard
```suggestion
In the component code, inside the `@Component` metadata under the `animations:` property, when the state evaluates to `true` (meaning "open" here), the associated HTML element's height is a wildcard style or default. In this case, the animation uses whatever height the element already had before the animation started. When the element is "closed", the element gets animated to a height of 0, which makes it invisible.
```

2021-08-30 15:31 UTC, aikidave commented on aio/content/guide/transition-and-triggers.md
> +* A sub-animation can be queried by a parent and then later animated with the `animateChild()` function.
```suggestion
* A sub-animation can be queried by a parent and then later animated with the `animateChild()` function.
```

Do we need a new term, sub-animation? Could we just refer to this as a secondary animation or a child animation?

2021-08-31 21:22 UTC, dario-piotrowicz commented
> Wow. There's a lot here, @dario-piotrowicz. I appreciate all the thought you've clearly put into this.
> 
> I've made some wording suggestions to help make the meaning a little clearer. Reviewing this PR, however, makes me think that we could do even more to make this content easier for developers to read.
> 
> Your PR is a great step forward in that effort! Thank you!

@aikidave Thank you so very much for spending your precious time reviewing my PR, yeah I can't imagine it taking little time, I really appreciate it :slightly_smiling_face: 

About the "even more to make the is content easier" I totally agree, I remember there were parts which were not just the easiest to follow (and not because of the topic), but ultimately I just figured it would be best not to make any major change

2021-08-31 21:24 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> -The animation does the following:
yeah it makes much more sense than what I put there :sweat_smile:

2021-08-31 21:26 UTC, dario-piotrowicz commented on aio/content/guide/route-animations.md
> +After configuring the routes, tell the Angular router where to render the views when matched with a route. You can set a router outlet by inserting a `<router-outlet>` directive inside the root `AppC
mh.... are you sure? :thinking: 

aren't we mentioning `<router-outlet>` too often here? 

like "add a router-outlet..." then just in the immediately next sentence "...you can set a router outlet by inserting a <router-outlet>"

2021-08-31 21:30 UTC, dario-piotrowicz commented on aio/content/guide/route-animations.md
> +After configuring the routes, tell the Angular router where to render the views when matched with a route. You can set a router outlet by inserting a `<router-outlet>` directive inside the root `AppC
Actually... if someone is reading the animations guide... I guess we could assume that they do know how to use the router already... maybe we could just get rid of the second sentence altogether? 

or just cpmbine the two like:
```
After configuring the routes, add a `<router-outlet>` in the root `AppComponent`
template to configure where to render the views when matched with a route.
```
?

2021-08-31 21:35 UTC, dario-piotrowicz commented on aio/content/guide/transition-and-triggers.md
> +* A sub-animation can be queried by a parent and then later animated with the `animateChild()` function.
mh... I'd imagine that we could go with `secondary animation`, it does sound better, doesn't it? :slightly_smiling_face: 

I guess I would personally not go with a `child animation` since that can be more open to interpretation and/or be more confusing (like that to me could sound like a specific concept in the angular animations package or something... :thinking: )

2021-08-31 21:43 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> +Let's take a look at another animation example. We have a search input which filters some heroes.
Sorry, it's been a couple of weeks since I made this change so I am not 100% sure, but I think that the issue is that here it mentions this example but it's not like it's introducing it and I could not find anywhere were it was actually uses, so I think that my understanding was that probably such an example existed but it was removed or something but still referenced here

but the code is actually still there, so it may actually be used somewhere....

so yeah I am not completely sure :sweat_smile: , I'll need to have another look at it and give you more details, sorry :pray: :bow:

2021-08-31 22:41 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> +Let's take a look at another animation example. We have a search input which filters some heroes.
ok.... so sorry I was mistaken! :bow: 

Here's the example: https://angular.io/guide/example-apps-list#animations

The thing is that that is the only single place in the whole site which actually links to the example....

I don't think we should just here say something and link the page I just mentioned, I think we should mention the live example somewhere (like at the start of the guides) and then refer to that :thinking: 

What do you think @aikidave do you agree?

2021-09-01 05:42 UTC, aikidave reviewed
Nice work! Added a few more comments to the conversation.

2021-09-01 05:42 UTC, aikidave commented on aio/content/guide/route-animations.md
> +After configuring the routes, tell the Angular router where to render the views when matched with a route. You can set a router outlet by inserting a `<router-outlet>` directive inside the root `AppC
How about:

After configuring the routes, add a `<router-outlet>` inside the root `AppComponent` template. The `<router-outlet>` tells the Angular router where to render the views when matched with a route.

2021-09-01 05:42 UTC, aikidave commented on aio/content/guide/transition-and-triggers.md
> +Wildcard states are more useful when an element in one particular state has multiple potential states that it can change to.
Maybe:

`Wildcard state can help you when an element...`

2021-09-01 05:42 UTC, aikidave commented on aio/content/guide/transition-and-triggers.md
> +* A sub-animation can be queried by a parent and then later animated with the `animateChild()` function.
In general, I prefer to avoid introducing new terms. I think `child animation` works, because you already refer to the parent animation in the previous paragraph.

2021-09-01 05:42 UTC, mary-poppins commented
You can preview 9a7dfd1 at https://pr42885-9a7dfd1.ngbuilds.io/.
You can preview cc8d305 at https://pr42885-cc8d305.ngbuilds.io/.
You can preview 24702d5 at https://pr42885-24702d5.ngbuilds.io/.
You can preview 8ccca9d at https://pr42885-8ccca9d.ngbuilds.io/.
You can preview c88576d at https://pr42885-c88576d.ngbuilds.io/.
You can preview 41e244c at https://pr42885-41e244c.ngbuilds.io/.
You can preview d812ee9 at https://pr42885-d812ee9.ngbuilds.io/.
You can preview 212a848 at https://pr42885-212a848.ngbuilds.io/.

2021-09-01 22:02 UTC, dario-piotrowicz commented on aio/content/guide/route-animations.md
> +The `<router-outlet>` directive has an attribute directive that contains data about active routes and their states, based on the `data` property that we set in the route configuration.
the router-outlet is a directive and not a container, that's the only thing I noticed and was fixing... but reading the sentence now it just seems off.... I'll need to think about this a bit :thinking:

2021-09-01 22:15 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> +Let's take a look at another animation example. We have a search input which filters some heroes.
@aikidave I am so sorry :bow: :bow: :bow: :bow: :bow: :bow: :bow: :bow: :bow: :bow: 

The guide already presents the example:
![Screenshot at 2021-09-01 23-09-59](https://user-images.githubusercontent.com/61631103/131752045-16f998ee-9bcf-47e5-9aaa-b45580e972c4.png)

(I missed that because if just has it as `<live-example></live-example>` I didn't know that was another way to include it :sweat: )

So should I just revert the sentence to its original form? :thinking: 

> ps: I admit that I may just have been stupid... but if I got confused/lost about this I believe it is possible that it is not really crystal clear... I think my issue was that this is just quickly mentioned like this at the beginning of the guide, and then mentioned again only a couple of times many sections/guides later... I wonder if we can do anything about that :sweat:

2021-09-01 22:15 UTC, mary-poppins commented
You can preview 7b0f5f2 at https://pr42885-7b0f5f2.ngbuilds.io/.

2021-09-01 22:19 UTC, dario-piotrowicz commented on aio/content/guide/transition-and-triggers.md
> +* A sub-animation can be queried by a parent and then later animated with the `animateChild()` function.
mh... the more I am thinking of it the more "child animation" is actually growing on me :sweat_smile::+1:

2021-09-04 21:28 UTC, mary-poppins commented
You can preview ae56feb at https://pr42885-ae56feb.ngbuilds.io/.

2021-09-13 23:59 UTC, aikidave approved these changes
I think this is all a great improvement. LGTM!

Reviewed-for: global-docs-approvers

2021-09-13 23:59 UTC, aikidave commented on aio/content/guide/transition-and-triggers.md
> +Wildcard states are more useful when an element in one particular state has multiple potential states that it can change to.
How about: 

"Use wildcard states when an element in one particular state has multiple potential states that it can change to."

Puts more of the focus on the user than the feature.

2021-09-16 11:37 UTC, dario-piotrowicz commented on aio/content/guide/transition-and-triggers.md
> +Wildcard states are more useful when an element in one particular state has multiple potential states that it can change to.
The problem is that your latest sentence doesn't follow what the previous sentence says,
how about: 
```
In general you use wildcard states when an element in one particular state has multiple potential states that it can change to.
```

so that we get:
```
In the two-state button example, the wildcard isn't that useful because there are only two possible states, `open` and `closed`.
In general you use wildcard states when an element in one particular state has multiple potential states that it can change to.
```

?

2021-09-16 11:44 UTC, dario-piotrowicz commented on aio/content/guide/route-animations.md
> +During a transition, a new view is inserted directly after the old one and both elements appear on screen at the same time. To prevent this, apply additional styling to the host view, and to the remo
Yes your version is much more clear! :slightly_smiling_face::+1:

It is correct except that the child view needs to use `absolute` and not `relative` positioning :slightly_smiling_face::+1:

2021-09-16 14:49 UTC, aikidave approved these changes
From a documentation perspective, this looks good! Thanks, @dario-piotrowicz ! I'll leave code reviews to those who know more than I. :)

Reviewed-for: global-docs-approvers

2021-09-16 14:49 UTC, aikidave commented on aio/content/guide/transition-and-triggers.md
> +Wildcard states are more useful when an element in one particular state has multiple potential states that it can change to.
Sounds good. Just one small change:

`In general, use wildcard states when an element in one particular state has multiple potential states that it can change to.`

2021-09-16 18:12 UTC, mary-poppins commented
You can preview 4aaffdf at https://pr42885-4aaffdf.ngbuilds.io/.

2021-09-16 18:18 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> +Let's take a look at another animation example. We have a search input which filters some heroes.
Sorry I am not sure if your suggestion has a typo of something (I don't get the `in the .` part :sweat:)

___

Anyways my issue here is a general one, seems like we have this live example and I actually I think that all (or most of) the examples presented in this guide are from the live example.

If you're ok with it I am thinking to just revert it back to the original text (as it is sort of right, it's just that I didn't get it) and then if we want I can go back to the guide and try to make generally clear that the examples are taken from the live/example one.

What do you say about that? :slightly_smiling_face:

2021-09-16 18:20 UTC, dario-piotrowicz commented
Thank you so very much @aikidave :slightly_smiling_face: 

I addressed all your comments, the only thing we still need to sort out is this I believe: https://github.com/angular/angular/pull/42885/files#r710365959

:slightly_smiling_face::+1: 

(then afterwords maybe you could ping some team member to review this? :heart_eyes: )

2021-09-17 20:46 UTC, mary-poppins commented
You can preview 6ea6570 at https://pr42885-6ea6570.ngbuilds.io/.

2021-09-17 21:00 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> +Let's take a look at another animation example. We have a search input which filters some heroes.
Actually this was involved into a merge conflict so I too the occasion to revert it back to it's original form, @aikidave please let me know if it's ok :sweat:

2021-09-20 14:08 UTC, aikidave commented on aio/content/guide/complex-animation-sequences.md
> +Let's take a look at another animation example. We have a search input which filters some heroes.
I have a plan to do some additional work on these topics; your efforts are making that work much easier, @dario-piotrowicz !

As the merge conflict caused you to revert these sentences back to their original form, I'm fine if we leave them as is. Let's not have perfect be the enemy of good!

2021-09-20 21:15 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> +Let's take a look at another animation example. We have a search input which filters some heroes.
wow I am really glad if I could be any useful!!!! :smile: 

Yeah the merge conflict was nothing breaking really, but since I was already thinking of reverting it back I just took it as a good chance to just do that :sweat_smile: 

Any yeah I agree with the perfection thing, this PR's been open for ages, the priority should be hopefully to get it merged (as it is improving things anyways) and take care of other stuff later on :slightly_smiling_face: 

> PS: if there'll be anything I could do to assist you please let me know! :smile:

2021-09-25 16:05 UTC, dario-piotrowicz commented
@petebacondarwin and @gkalpak so sorry for bothering you :cry:, @aikidave seems fine with the changes from a documentation point of view, could either of you have a look from a code point of view? :bow: :pray: (or ping someone that could? :slightly_smiling_face:)

2021-09-27 15:50 UTC, gkalpak requested changes
Great work as usual, @dario-piotrowicz 💯
I've just left a few questions/suggestions.

2021-09-27 15:50 UTC, gkalpak commented on aio/content/guide/complex-animation-sequences.md
> +* Skips animating elements when the user first opens or navigates to this page (the filter animation narrows what is already there, so it only works on elements that already exist in the DOM).
"Skips animating elements" is a bit confusing here (at first I was interpreting it as "skips elements that are animated").
How about:

```suggestion
* Skips animations when the user first opens or navigates to this page (the filter animation narrows what is already there, so it only works on elements that already exist in the DOM).
```

2021-09-27 15:50 UTC, gkalpak commented on aio/content/examples/animations/src/app/app.component.ts
> -    // animation triggers go here
OOC, why remove this?

2021-09-27 20:39 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> +making things more complex -->
sorry! gosh I can't believe this wasn't already removed :sweat: :bow: :pray: +

It's been ages since I created this PR, not even sure why I found this too complicated, we can ignore this for now I think :slightly_smiling_face:

2021-09-27 20:45 UTC, dario-piotrowicz commented on aio/content/guide/animations.md
> +Use the `style()` function to define a set of styles to associate with a given state name. You must write style attributes that contain dashes in [*camelCase*](guide/glossary#case-conventions), such
ah ok :slightly_smiling_face::+1: 

But I think something in your suggestion is missing... :thinking: 
`You must [*camelCase*](guide/glossary#case-conventions) for style attributes...`
did you missed something like "use"?
`You must use [*camelCase*](guide/glossary#case-conventions) for style attributes...`
or maybe the "for" is to be removed? (using camelCase as a verb)?
`You must [*camelCase*](guide/glossary#case-conventions) style attributes...`

2021-09-27 20:48 UTC, dario-piotrowicz commented on aio/content/guide/complex-animation-sequences.md
> +* Skips animating elements when the user first opens or navigates to this page (the filter animation narrows what is already there, so it only works on elements that already exist in the DOM).
ah.... yeah I understand what you mean :+1: 

(like "animating" could interpreted as the verb for the execution or the adjective for the elements)

2021-09-27 20:49 UTC, dario-piotrowicz commented on aio/content/guide/reusable-animations.md
> +From this point, you can import reusable animation variables in your component class. For example, the following code snippet imports the `transitionAnimation` variable and uses it via the the `useAn
:man_facepalming::+1:

2021-09-27 20:53 UTC, dario-piotrowicz commented on aio/content/guide/route-animations.md
> +During a transition, a new view is inserted directly after the old one and both elements appear on screen at the same time. To prevent this behavior, update the host view to use relative positioning.
ah ok! :+1: 

I think I misinterpreted the original sentence, yeah yours make much more sense :sweat_smile:

2021-09-27 21:03 UTC, mary-poppins commented
You can preview b45e48c at https://pr42885-b45e48c.ngbuilds.io/.

2021-09-27 21:08 UTC, dario-piotrowicz commented on aio/content/guide/reusable-animations.md
> +To create a reusable animation, use the <code><a href="api/animations/animation" class="code-anchor">animation</a>()</code> function to define an animation in a separate `.ts` file and declare this a
that works great!!! amazing suggestion!!! :heart_eyes: I'll amend the various links :+1:

2021-09-27 21:17 UTC, dario-piotrowicz commented on aio/content/guide/reusable-animations.md
> +To create a reusable animation, use the <code><a href="api/animations/animation" class="code-anchor">animation</a>()</code> function to define an animation in a separate `.ts` file and declare this a
done :slightly_smiling_face:  (https://github.com/angular/angular/pull/42885/commits/7e66c5ce4a48536eabdb6d34587c83739b110e81)

2021-09-27 21:24 UTC, mary-poppins commented
You can preview 7e66c5c at https://pr42885-7e66c5c.ngbuilds.io/.

2021-09-27 21:25 UTC, dario-piotrowicz commented on aio/content/guide/route-animations.md
> +<code-example path="animations/src/app/animations.ts" header="src/app/animations.ts (Break down)" region="style-view" language="typescript"></code-example>
ah.... sorry if it's confusing :sweat: 

basically the same file is presented fully at the beginning of the section:
![Screenshot at 2021-09-27 22-21-05](https://user-images.githubusercontent.com/61631103/134987167-32a6bc1e-a82c-4e2f-bda4-1517a1828f10.png)

and then it's broken down two different smaller examples/explanations below:
![Screenshot at 2021-09-27 22-21-26](https://user-images.githubusercontent.com/61631103/134987291-582f36dd-86a9-40bd-a6e2-49da40c80762.png)
![Screenshot at 2021-09-27 22-23-26](https://user-images.githubusercontent.com/61631103/134987353-f4a079ff-174a-4518-a5db-64e751120542.png)

so I wanted to add something to sort of emphasize that this is just a broken down of the example shown above...

is this just silly unnecessary? :sweat:

2021-09-27 21:36 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/app.component.ts
> -    // animation triggers go here
Actually now that you ask about it I am not really sure the removal is necessary... :thinking: 

The fact is that this appears in two places:

[![Screenshot at 2021-09-27 22-30-48](https://user-images.githubusercontent.com/61631103/134988609-104777c4-069f-4669-a44a-db21c35cd62d.png)](https://angular.io/guide/transition-and-triggers#disabling-all-animations)

[![Screenshot at 2021-09-27 22-32-18](https://user-images.githubusercontent.com/61631103/134988551-7a53477b-8697-47f4-bff8-31d5855ed260.png)](https://angular.io/guide/route-animations#animation-definition)

both cases are not indicating where the triggers should go (that is covered in other parts of the guide) and to me that comment sort of just looks distracting as there is already an animation in the array

so it is sort of like us telling the reader where the triggers go and then adding this comment sort of indicating where they go... not sure :sweat_smile: 

please let me know what you think, if you think it should stay I don't mind putting it back in :slightly_smiling_face:

2021-09-29 14:33 UTC, gkalpak requested changes
Almost there 🥁 :tada:

2021-09-29 14:33 UTC, gkalpak commented on aio/content/guide/animations.md
> +Use the `style()` function to define a set of styles to associate with a given state name. You must write style attributes that contain dashes in [*camelCase*](guide/glossary#case-conventions), such
Sorry, I meant _"You must **use** camelCase for ..."_ 😇

2021-09-29 14:33 UTC, gkalpak commented on aio/content/guide/route-animations.md
> +During a transition, a new view is inserted directly after the old one and both elements appear on screen at the same time. To prevent this behavior, update the host view to use relative positioning.
Nit: `of the other` sounds better to me (since we are talking about two views here:

```suggestion
During a transition, a new view is inserted directly after the old one and both elements appear on screen at the same time. To prevent this behavior, update the host view to use relative positioning. Then, update the removed and inserted child views to use absolute positioning. Adding these styles to the views animates the containers in place and prevents one view from affecting the position of the other on the page.
```

2021-09-29 14:33 UTC, gkalpak commented on aio/content/guide/route-animations.md
> +<code-example path="animations/src/app/animations.ts" header="src/app/animations.ts (Break down)" region="style-view" language="typescript"></code-example>
I see. That makes sense. We typically use ` (excerpt)` for that. Would that work here (to keep it consistent with the rest of the docs)?

2021-09-29 14:33 UTC, gkalpak commented on aio/content/examples/animations/src/app/app.component.ts
> -    // animation triggers go here
I see. In the two cases you mentioned it is indeed redundant (or even confusing).
But I think it is still relevant in [Adding the animation metadata property][1] section (which uses the `decorator` docregion).

How about we keep the comment only for the `decorator` docregion then?

[1]: https://angular.io/guide/animations#step-3-adding-the-animation-metadata-property

2021-09-29 20:53 UTC, dario-piotrowicz commented on aio/content/guide/animations.md
> +Use the `style()` function to define a set of styles to associate with a given state name. You must write style attributes that contain dashes in [*camelCase*](guide/glossary#case-conventions), such
done :smile:

2021-09-29 20:55 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/app.component.ts
> -    // animation triggers go here
yeah.... I am so sorry I got confused with the start and end of regions and thought it was only used in those 2 :sweat: 

(quite silly of me :sweat_smile:)

anyway yeah, sounds like a plan! :smiley::+1:

2021-09-29 21:02 UTC, mary-poppins commented
You can preview e685f94 at https://pr42885-e685f94.ngbuilds.io/.

2021-09-29 21:14 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/app.component.ts
> -    // animation triggers go here
done: https://github.com/angular/angular/pull/42885/commits/55de8e0038c5aec2e6b2315dfbd76b89844a1b7b

let me know if it's ok :smile: 

would you add a comma after `slideInAnimation`? :thinking:

2021-09-29 21:18 UTC, dario-piotrowicz commented on aio/content/guide/route-animations.md
> +During a transition, a new view is inserted directly after the old one and both elements appear on screen at the same time. To prevent this behavior, update the host view to use relative positioning.
Ah sorry I changed that as it made more sense to me :sweat:
I sort of got confused and thought it was a different example and there were more than 2 elements, sorry :sweat:

2021-09-29 21:20 UTC, dario-piotrowicz commented on aio/content/guide/route-animations.md
> +<code-example path="animations/src/app/animations.ts" header="src/app/animations.ts (Break down)" region="style-view" language="typescript"></code-example>
yeah that looks nicer :slightly_smiling_face::+1:

2021-09-29 21:26 UTC, dario-piotrowicz commented
@gkalpak should be all good please have another look when you can :smile: 

By the way, just wanted to ask you, I'd like to rebase to master as I am a bit far behind I think, that would break the fixup hashes/links I use in comments, is that anything I can do about that? :thinking:

2021-09-29 21:33 UTC, mary-poppins commented
You can preview bdff258 at https://pr42885-bdff258.ngbuilds.io/.

2021-09-30 14:58 UTC, gkalpak commented on aio/content/examples/animations/src/app/app.component.ts
> +    return outlet?.activatedRouteData?.animation;
I think it is fine.

2021-09-30 15:01 UTC, gkalpak commented on aio/content/examples/animations/src/app/app.component.ts
> -    // animation triggers go here
👌

2021-09-30 15:04 UTC, gkalpak approved these changes
One last (really minor) suggestion. Otherwise looks perfect :100:

2021-09-30 15:04 UTC, gkalpak commented on aio/content/examples/animations/src/app/app.component.ts
>  // #docregion decorator
Nit: (Although either way works) I think the interleaved docregions would be a little easier to grok if these too lines were swapped:

```suggestion
// #docregion decorator
// #enddocregion toggle-app-animations, define
```

2021-09-30 20:50 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/app.component.ts
>  // #docregion decorator
yeah, sorry I must have gotten my wires crossed, this is of course much much better :sweat:

2021-09-30 20:50 UTC, dario-piotrowicz commented
> One last (really minor) suggestion. Otherwise looks perfect 100

Thank you so very much @gkalpak !!!! :smile: :smile: :smile:

2021-09-30 21:00 UTC, mary-poppins commented
You can preview 514e59d at https://pr42885-514e59d.ngbuilds.io/.

2021-10-01 10:25 UTC, gkalpak approved these changes

2021-10-01 12:42 UTC, dario-piotrowicz commented
@gkalpak thanks for rebasing for me! :slightly_smiling_face: 

sorry I'll try to be more vigilant next time :sweat_smile:

2021-10-01 12:51 UTC, mary-poppins commented
You can preview a1d476c at https://pr42885-a1d476c.ngbuilds.io/.

2021-10-01 15:34 UTC, closed without merging