feat(compiler-cli): add makeTemplateDiagnostic wrapper
angular/angular pull request #42937
Opened 2021-07-22 21:04 UTC by danieltre23

Add a `makeTemplateDiagnostic` wrapper in the `TemplateTypeChecker`, since it has the templateId and mapping available in it's scope. This makes creating template diagnostics easier.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently to create a template diagnostic you need to pass the templateId and it's mapping as parameters.

## What is the new behavior?
The wrapper function takes the `ts.ClassDeclaration` and gets the templateId and mapping from it to create the template diagnostic. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-07-22 22:59 UTC, atscott requested changes
This is minor detail when working with the compiler: 

We typically mark these as a `refactor` rather than `feat` because there's no publicly facing feature that can be used so we want to avoid adding this to the changelog.

2021-07-22 22:59 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/api/checker.ts
> +   */
Even though it's just a wrapper, you should really document it better than saying "this is just a wrapper, look somewhere else". What you've documented is an implementation detail rather than a behavior. Your documentation should aim to explain the publicly facing behavior, not the internal implementation details that could change.

You could likely copy-past the documentation straight from the other `markTemplateDiagnostic` funciton.

2021-07-22 23:05 UTC, atscott commented
I think you could also make the commit message a bit more clear in terms of what's going to be using this new method and defend why it's appropriate to be placed here (i.e. it makes sense for the template type checker to have this method because users of the `TemplateTypeChecker` could use the typing information available there to determine if a diagnostic should be produced). 

Try to provide the whole context in your commit message so if someone were to look at this in isolation, it would still make sense.

2021-07-23 00:58 UTC, dgp1130 approved these changes
I agree with @atscott's comments, but looks good beyond that.

Apologies for the `feat()` commit message, that was my suggestion as I totally forgot that `refactor()` existed. Is there any recommendation for whether to target `minor` or `patch` with this? It's only needed in `minor` for future changes, but I'd rather not diverge `patch` more than we need to.

2021-07-23 15:45 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/typecheck/api/checker.ts
> +   */
Used the same documentation as the other `makeTemplateDiagnostic` function.

2021-07-23 20:59 UTC, atscott commented
>  Is there any recommendation for whether to target minor or patch with this?

We often merge these types of things to `patch` to avoid diverging the two branches.

2021-07-23 20:59 UTC, atscott approved these changes
👍  LGTM

2021-07-23 21:00 UTC, atscott commented
[presubmit](https://test.corp.google.com/ui#cl=386467688) (unrelated failures, forcing green)

2021-07-23 21:02 UTC, dgp1130 commented
Targetting patch to avoid unnecessary divergence per @atscott's comment.

2021-07-26 20:09 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +      errorCode: number, message: string): TemplateDiagnostic {
Should we use our `ErrorCode` enum here?

2021-07-26 20:10 UTC, alxhub approved these changes

2021-07-27 01:00 UTC, closed without merging

2021-07-27 17:11 UTC, dylhunn commented
This PR must be rolled back, as it caused the patch branch to go red.

2021-07-27 17:29 UTC, dylhunn commented
#42971 rolls this back in patch branch only.