docs: Edits to remove jargon
angular/angular pull request #42965
Opened 2021-07-26 20:12 UTC by TeriGlover

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2021-07-26 20:22 UTC, mary-poppins commented
You can preview 6775a35 at https://pr42965-6775a35.ngbuilds.io/.

2021-07-28 13:18 UTC, petebacondarwin requested changes

2021-07-28 13:18 UTC, petebacondarwin commented on aio/content/guide/i18n.md
> +If `@angular/localize` is not installed, the Angular CLI might generate an error when you try to build a localized version of your app.
what is the motivation behinding switching from `may` to `might`?

2021-07-28 13:18 UTC, petebacondarwin commented on aio/content/guide/testing-pipes.md
> +  For a hands-on experience, <live-example name="testing" stackblitz="specs" noDownload>run tests and explore the test code</live-example> in your browser as your read this guide.
```suggestion
  For a hands-on experience, <live-example name="testing" stackblitz="specs" noDownload>run tests and explore the test code</live-example> in your browser as you read this guide.
```

2021-07-28 13:18 UTC, petebacondarwin commented on aio/content/guide/testing-utility-apis.md
>        this default in the middle of your test run, call `resetTestEnvironment` first.
```suggestion
      Call this method _exactly once_. To change
      this default in the middle of a test run, call `resetTestEnvironment` first.
```

2021-07-30 16:58 UTC, aikidave approved these changes
Looks good. Please address Pete's additional changes and this PR should be good to go.

Reviewed-for: global-docs-approvers

2021-07-30 16:58 UTC, aikidave commented on aio/content/guide/i18n.md
> +If `@angular/localize` is not installed, the Angular CLI might generate an error when you try to build a localized version of your app.
The simplest reason: to comply with the Google Developer Style Guide: https://developers.google.com/style/word-list?hl=en#might. 

In addition, "may" and "might" can be localized differently; by using "might" we ensure more consistency across documentation sets.

2021-09-15 20:37 UTC, aikidave commented
@JoostK can you add a comment, `@googlebot I consent` to this PR? Thank you!

2021-09-15 20:59 UTC, JoostK commented
@aikidave  it looks like my commit got in here by accident. Can this be rebased to drop my commit?

2021-09-17 15:43 UTC, mary-poppins commented
You can preview 23b0413 at https://pr42965-23b0413.ngbuilds.io/.

2021-09-21 21:37 UTC, mary-poppins commented
You can preview 5be11d5 at https://pr42965-5be11d5.ngbuilds.io/.

2021-09-22 20:00 UTC, petebacondarwin approved these changes
LGTM - but did you mean to revert the changes to the links?
E.g.  from

```
[explore the translated example app][AioGuideI18nAppPreTranslation]
```

to

```
[explore the translated example app](#app-pre-translation)
```

If you do want to revert these then you should also remove them from the foot of the file.

2021-09-23 21:35 UTC, closed without merging