feat(language-service): auto-apply optional chaining on nullable symbol
angular/angular pull request #42995
Opened 2021-07-30 03:19 UTC by ivanwonder

Support automatically inserts the optional chaining operator (`?.`)
when property access (`.`) is done on a nullable symbol.

Fixes https://github.com/angular/vscode-ng-language-service/issues/1094

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-08-02 23:25 UTC, atscott commented
[presubmit](https://test.corp.google.com/ui#id=OCL:388322936:BASE:388330194:1627946705334:dd2ddeb2)

2021-08-02 23:39 UTC, atscott commented on packages/language-service/ivy/completions.ts
> +          options?.includeCompletionsWithInsertText) {
drive-by comment: I think you'll also need to ensure that `includeAutomaticOptionalChainCompletions !== false` `https://sourcegraph.com/github.com/microsoft/TypeScript/-/blob/lib/tsserverlibrary.d.ts?L9424:1

2021-08-06 19:40 UTC, atscott requested changes

2021-08-06 19:40 UTC, atscott commented on packages/language-service/ivy/completions.ts
> +          options.includeAutomaticOptionalChainCompletions) {
```suggestion
          options.includeAutomaticOptionalChainCompletions !== false) {
```
Based on the documentation for this option, it has to explicitly be set to `false` to disable it.



> Unless this option is `false`, or `includeCompletionsWithInsertText` is not enabled,
> member completion lists triggered with `.` will include entries on potentially-null and potentially-undefined
> values, with insertion text to replace preceding `.` tokens with `?.`.
>

2021-08-06 19:40 UTC, atscott commented on packages/language-service/ivy/completions.ts
> +  if (includeDot) {
Hmm, I actually think this might make more sense to pull our of `makeReplacementSpanFromAst` and move it up to where you're checking to include the dot. That way, there's no need for the variable in the first place so we don't have to think about documenting it further and trying to make the name understandable. In addition, the context for  _what_ we're doing and _why_ we do it is all in the same place. So this would all change to 

```
      const replacementSpan = makeReplacementSpanFromAst(this.node);
      if (!(this.node.receiver instanceof ImplicitReceiver) &&
          options?.includeCompletionsWithInsertText &&
          options.includeAutomaticOptionalChainCompletions) {
        const symbol = this.templateTypeChecker.getSymbolOfNode(this.node.receiver, this.component);
        if (symbol?.kind === SymbolKind.Expression) {
          const type = symbol.tsType;
          const nonNullableType = this.typeChecker.getNonNullableType(type);
          if (type !== nonNullableType) {
            // adjust the replacement span to include the preceding dot of the property access
            replacementSpan.start--;
            replacementSpan.length++;
          }
        }
      }
```

2021-08-09 16:42 UTC, atscott approved these changes
One small request for comment. Otherwise LGTM

2021-08-09 16:42 UTC, atscott commented on packages/language-service/ivy/completions.ts
> +          if (type !== nonNullableType && replacementSpan !== undefined) {
```suggestion
          if (type !== nonNullableType && replacementSpan !== undefined) {
            // Shift the start location back one so it includes the `.` of the property access. 
            //In combination with the options above, this will indicate to the TS LS to include optional chaining completions `?.` for nullable types.
```
Could you add a quick comment here just so it's easier for a passerby to understand why we're doing this?

2021-08-12 16:23 UTC, closed without merging

2021-08-31 20:55 UTC, ties-s commented
How does this handle https://github.com/angular/angular/issues/37619

2021-09-01 01:06 UTC, ivanwonder commented
It's still a bug, this will auto-apply optional chaining for you, `foo?.bar?.baz`, because the LS relies on the code the compiler generates.