Extended diagnostics integration
angular/angular pull request #43107
Opened 2021-08-10 20:57 UTC by danieltre23

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

Integrate extended template diagnostics generation with compiler.

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-08-10 23:09 UTC, dgp1130 commented
I think you probably want to rebase this against `master` now that your previous PR has been merged. That should drop most of the extra commits here.

2021-08-11 23:16 UTC, dgp1130 requested changes
Looks good! Just a couple nits and a few questions for Andrew.

One other nit: The first commit message should probably have "refactor(compiler-cli): export `getExtendedTemplateDiagnosticsForComponent` and template checks" as its first line so it's more easily scanable when abbreviated to one line.

2021-08-11 23:16 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +  private getExtendedTemplateDiagnostics(sf?: ts.SourceFile): ts.Diagnostic[] {
A doc comment here explaining that not providing a source file returns extended diagnostics for *all* source files in the program would be helpful. It's a private function, so we don't need to be too detailed, but at least calling out what happens when not given a source file would be useful.

2021-08-11 23:16 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +    for (const clazz of this.fileToClasses.get(sf)!) {
Nit: I generally recommend checking the result of `.get()` over using `.has()` and with a non-null assertion. Something like:

```typescript
const classes = this.fileToClasses.get(sf);
if (classes === undefined) {
  return [];
}

const diagnostics: ts.Diagnostic[] = [];
for (const clazz of classes) {
  // ...
}
```

This way we're able to leverage the type inference capabilities of the language and let the compiler validate that `classes` is defined where we expected it to be, rather than relying on a programmer-authored `!` operator.

2021-08-11 23:16 UTC, dgp1130 commented on packages/compiler-cli/test/ngtsc/extended_template_diagnostics_spec.ts
> +    });
Should we consider an error if `strictTemplates` is disabled but `extendedTemplateDiagnostics` are enabled? In that case, it's a configuration error and I think we should fail the compilation in this case and give a hard error to the user about it.

2021-08-12 18:35 UTC, atscott requested changes
Looks great overall! 

One thing about the `feat` commit in the middle: If we decide this is appropriately a `feat`, then we'll need to change the target to `minor`. If we want to merge to `patch`, that'll have to change to `refactor` because the tool won't allow `feat` commit in the patch branch.

2021-08-12 18:35 UTC, atscott commented on packages/compiler-cli/src/ngtsc/core/api/src/public_options.ts
> +  extendedTemplateDiagnostics?: boolean;
`StrictTemplateOptions` isn't automatically extracted to `angular.io`. We document each option at https://github.com/angular/angular/blob/master/aio/content/guide/template-typecheck.md. So I think maybe just adding a sentence to the top to indicate it's for experimental, internal use only would work.

2021-08-12 18:35 UTC, atscott commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +    if (!this.options.extendedTemplateDiagnostics || !this.options.strictTemplates) {
Your understanding of `strictTemplates` is correct. Users _could_ enable it and also specifically disable each option. I don't think it's worth worrying about this case. Most devs won't be touching the options beyond what the cli does during the new project generation. Anyone who specifically edits those options should be aware of what that might mean for the compiler's understanding of the code.

2021-08-12 18:35 UTC, atscott commented on packages/compiler-cli/src/ngtsc/transform/src/api.ts
> +      (component: ts.ClassDeclaration, tempalteTypeChecker: TemplateTypeChecker,
```suggestion
      (component: ts.ClassDeclaration, templateTypeChecker: TemplateTypeChecker,
```

2021-08-12 18:35 UTC, atscott commented on packages/compiler-cli/test/ngtsc/extended_template_diagnostics_spec.ts
> +/**
nit: the commit header should use `test(compiler-cli)` rather than `refactor(compiler-cli)`

2021-08-12 18:35 UTC, atscott commented on packages/compiler-cli/test/ngtsc/extended_template_diagnostics_spec.ts
> +    });
Agreed, this should be an error.

2021-08-12 18:35 UTC, atscott commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +      ...this.getExtendedTemplateDiagnostics()
```suggestion
      ...this.getExtendedTemplateDiagnostics(),
```

2021-08-12 18:35 UTC, atscott commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +      ...this.getExtendedTemplateDiagnostics(file)
```suggestion
      ...this.getExtendedTemplateDiagnostics(file),
```

2021-08-12 18:51 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +    if (!this.options.extendedTemplateDiagnostics || !this.options.strictTemplates) {
SGTM. I think in that case extended checks wouldn't fail or cause any problems, they just wouldn't trigger some places where they otherwise would have. I think that's a reasonable degradation of behavior for having less accurate types.

2021-08-13 00:19 UTC, dgp1130 approved these changes
Looking good! Just a couple minor nits, but no major concerns here.

2021-08-13 00:19 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +        throw new Error(`The 'extendedTemplateDiagnostics' don't work without 'strictTemplates'.`);
Nit: phrasing.

"The 'extendedTemplateDiagnostics' option requires 'strictTemplates' to also be enabled."

2021-08-13 00:19 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +        if (isNamedClassDeclaration(clazz)) {
Nit: Since this is only dependent on `clazz`, could we move this up a bit to skip iterating over traits when not necessary? Something like:

```typescript
for (const clazz of classes) {
  if (!isNamedClassDeclaration(clazz)) continue;

  for (const trait of record.traits) {
    // ...
  }
}
```

2021-08-16 18:02 UTC, atscott approved these changes

2021-08-16 23:53 UTC, alxhub requested changes

2021-08-16 23:53 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +      ...this.getExtendedTemplateDiagnostics(),
Should we not check the flag here before adding extended diagnostics to the mix? I think this would be preferable to allocating an array for each call.

2021-08-16 23:53 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +        throw new Error(
This check should probably happen at creation time, or as part of option diagnostics, not on-demand.

2021-08-16 23:53 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/src/component.ts
> +        component, templateTypeChecker, typeChecker, allTemplateChecks);
This is a little strange, architecturally.

1) the compiler (by that I mean the core `NgCompiler`) has no ability to control which template checks run. We're importing a random collection of checks from the _implementation_ of extended diagnostics, which this class should know nothing about.

2) we're receiving the `ts.TypeChecker` as an argument here, even though we already have a reference to it from our constructor

3) we're receiving the `TemplateTypeChecker` here, even though we're not going to do anything with it but pass it along.

Instead, we should architect `extendedTemplateCheck` similarly to how `typeCheck` works:

* Create an interface (`ExtendedTemplateChecker` maybe) which will represent the operation of performing extended template checks. `ComponentDecoratorHandler` can then depend on this interface without needing to care about how these checks work. Basically, this method becomes `return extendedTemplateChecker.check(component)`.

* We can then have an implementation `ExtendedTemplateCheckerImpl` which captures any needed dependencies (`ts.TypeChecker`, `TemplateTypeChecker`, and any requested `TemplateCheck`s in its `constructor`.

* `ExtendedTemplateCheckerImpl` can be constructed by the `NgCompiler` (with some number of `TemplateCheck`s selected) and then `extendedTemplateCheck` can be called with that checker.

Using the interface means that `ComponentDecoratorHandler` and `TraitCompiler` don't need to depend on the implementation, nor do they need to be concerned with what checks are being run or what services are required to implement them.

2021-08-17 09:34 UTC, petebacondarwin approved these changes

2021-08-18 18:46 UTC, alxhub requested changes

2021-08-18 18:46 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +      throw new Error(
Consider moving this check into `verifyCompatibleTypeCheckOptions`.

2021-08-18 18:46 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +    if (this.options._extendedTemplateDiagnostics) {
I think it'd be cleaner to implement this by constructing the main diagnostics array and then `.push()`ing the extended diagnostics if requested.

2021-08-18 18:46 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +        compilation.templateTypeChecker, typeChecker, allTemplateChecks);
Instead of having `allTemplateChecks` imported as a constant, we should explicitly list out and construct the checks here.

2021-08-18 18:46 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/transform/src/compilation.ts
> +      if (isNamedClassDeclaration(clazz)) {
Invert this condition:
```suggestion
      if (!isNamedClassDeclaration(clazz)) {
        continue;
      }
```

This keeps the rest of the code cleaner - the "main case" should always be the least indented and guarded.

2021-08-18 18:46 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/extended/index.ts
> +import {TemplateCheck} from './api/api';
When you have a separate package, always import from the index:
```suggestion
import {TemplateCheck} from './api';
```

2021-08-18 18:46 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/extended/index.ts
> +export const allTemplateChecks: TemplateCheck<ErrorCode>[] = [new InvalidBananaInBoxCheck()];
1) don't declare things in the `index.ts` file, that's exclusively for re-exports
2) this doesn't need to be a constant anyway, it should be the consumer's responsibility to select which checks they want to use.

2021-08-18 18:46 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/typecheck/extended/BUILD.bazel
> +        "//packages/compiler-cli/src/ngtsc/typecheck/extended/src/template_checks/invalid_banana_in_box",
This shouldn't be needed - only consumers should depend on the specific checks that they want to use.

2021-08-18 19:10 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +      throw new Error(
Talked offline and concluded that moving the check into `verifyCompatibleTypeCheckOptions` would require a new `ErrorCode` for the diagnostic, and since the `_extendedTemplateDiagnostics` flag is for internal use only it wouldn't make sense to have a public api `ErrorCode` for that.

2021-08-18 20:32 UTC, alxhub approved these changes

2021-08-19 18:55 UTC, closed without merging