feat(core): Enable tsec checks for @angular/core.
angular/angular pull request #43108
Opened 2021-08-10 23:18 UTC by uraj

tsec is a static analyzer that discovers Trusted Types violations.
Deploy tsec to make sure there will be no TT regression in the core
package. Existing violations have been reviewed and exempted in
packages/tsec-exemption.json.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-08-10 23:23 UTC, uraj commented
@josephperrott This is the PR that enables TT static analysis for the core package. Could you take a look?

2021-08-11 18:03 UTC, IgorMinar reviewed
Thanks @uraj for sending us this PR! I'm supportive of adding tsec to our repo.

Overall I like where this is heading, I left a few comments primarily asking for clarification on your intention here.

If we could change the PR to run these tests via bazel, then that would be better, but I can't easily estimate how much more work that would be. @josephperrott might have a better understanding. Maybe running it via the new https://bazelbuild.github.io/rules_nodejs/ that autogenerate bazel rules for npm binaries (see the babel example in that link) would make it trivial if we can collect all the right inputs easily.

Please take a look at the other comments. Thank you again.

2021-08-11 18:05 UTC, IgorMinar commented on packages/tsec-exemption.json
> +/**
oh, one more thing

can you please add this file (and possibly all tsec tsconfig files) to the pullapprove security group: https://github.com/angular/angular/blob/9fb79d38aade67f6f3bcdac0ffa93b8806baa215/.pullapprove.yml#L732-L738 so that we request the reviews from the right people for changes to these files? thanks

2021-08-11 18:28 UTC, uraj commented on packages/core/tsconfig-tsec.json
> +    "outDir": ".tsec"
Tsetse (the checker engine used by tsec) used to be part of @bazel/typescript, but the support was discontinued due to the TS team being understaffed. I will see if I can make a custom rule to run tsec.

2021-08-11 18:31 UTC, uraj commented on packages/localize/tsconfig-tsec.json
> +/** For building //packages/localize. */
I saw `//packages/localize` as one of `core`'s dependencies in packages/core/BUILD.bazel, so I though I will need to build it as a reference of `core`. But it turns out it's actually not needed.

I will add `platform-browser` and `platform-server`.

2021-08-11 19:44 UTC, uraj commented on packages/tsconfig-tsec.json
> +  "include": ["*.ts"]
You're right that this one doesn't cover anything meaning full (only empty.ts). I've changed this to a master config that builds all packages we want to check.

2021-08-11 19:44 UTC, uraj commented on packages/tsec-exemption.json
> +/**
Done.

2021-08-11 20:47 UTC, uraj commented on packages/zone.js/lib/tsconfig-tsec.json
> +  "files": ["zone.ts"]
The original plan is to only check `core`, which only depends on `zone.d.ts`. Do we actually want to check `browser/*`? If so, I can include it as one of the to-be-checked packages.

2021-08-13 18:52 UTC, uraj commented on packages/core/tsconfig-tsec.json
> +    "outDir": ".tsec"
I was able to do certain amount of bazel integration. There are several caveats though.
  - tsconfig-tsec.json files are still not auto-generated and have to be maintained manually to make it consistent with BUILD.bazel. The maintenance cost should be low though.
  -  The bazel rule `tsec_test` does not check transitive dependencies, so each dependency needs to have its own `tsec_test`. This is hard to fix, unless we can have some upstream patches for the vanilla `ts_library` bazel rule.

2021-08-16 18:57 UTC, uraj commented
@IgorMinar Thanks for the review! I managed to implement some basic integration for tsec and Bazel (details are in my reply to code review comments). PTAL.

2021-09-08 04:43 UTC, IgorMinar reviewed
At a high level this looks good to me. So much better than the original version. I think it was @josephperrott who suggested that this check should really be done as part of the npm_package/ng_package rules but i don't think that that implementation is strictly needed for the initial version. 

I'd love for @devversion or @josephperrott to sign off on the bazel rule implementation, but again I think this is pretty close to a mergable V1. Thanks for all the iterations on this.

2021-09-08 16:36 UTC, josephperrott requested changes

2021-09-08 16:36 UTC, josephperrott commented on tools/tsec.bzl
> +    all_data = name + "_all_data"
Historically we have preferred to use python's string formatting for substitutions like this.

```suggestion
    all_data = "%s_all_data" % name
```

2021-09-08 16:36 UTC, josephperrott commented on tools/tsec.bzl
> +    all_data = name + "_all_data"
Can we just do the substitutions in place, or change the variable name used?  It seems odd to have `all_data` as a string that we use as a parameter on `_all_data`

2021-09-08 16:36 UTC, josephperrott commented on tools/tsec.bzl
> +_all_data = rule(
I think we can find a better name for this than `_all_data`, how about something like `_all_dependencies` or `_all_transitive_deps`

2021-09-08 16:36 UTC, josephperrott commented on packages/compiler/BUILD.bazel
> +tsec_test(
For these `tsec_test` usages, they are going to be the only ones in each package they are found in.

Can we just use the name `tsec_test` instead of `<package name>_tsec_test`

2021-09-08 18:00 UTC, uraj commented on tools/tsec.bzl
> +_all_data = rule(
Changed to `_all_transitive_deps`.

2021-09-08 18:07 UTC, uraj commented on packages/compiler/BUILD.bazel
> +tsec_test(
Done.

2021-09-08 18:07 UTC, uraj commented on tools/tsec.bzl
> +    all_data = name + "_all_data"
Done.

2021-09-08 18:34 UTC, devversion approved these changes
Overall LGTM. Unfortunately this rule is not working on Windows though (we try making most of the tooling windows-compatible). The problem is that on Windows the test inputs are not symlinked, so the `.ts` sources end up staying in the actual project directory while dependencies are in the `bazel-out`. It would require module resolution through `@bazel/runfiles` to make it work. 

It's unfortunate that this won't work on Windows, but I assume it's not necessarily blocking. cc. @josephperrott and @IgorMinar for feedback on this.

2021-09-08 18:34 UTC, devversion commented on tools/defaults.bzl
> +
It seems like we can drop all of this additional targets by just using an aspect that does not have propagation enabled. The aspect will only check the `target` passed to the `tsec_test` macro and it will augment the target with the `TsLibInfo` provider. This has the following benefits:

* We keep all the tsec logic local to the `tsec.bzl` file. No other infrastructure setup is involved.
* We do not need to setup additional targets for all `ng_module` or `ts_library` targets (most of these would be unused as we only test a subset with tsec).

e.g.

```bzl

def _capture_tsec_deps_aspect_impl(target, ctx):
    """Forward `srcs` and `deps` of `ts_library` and `ng_module` macros to `_tsec_test`."""
    return [TsLibInfo(srcs = ctx.rule.attr.srcs, deps = ctx.rule.attr.deps)]

capture_tsec_deps_aspect = aspect(
    implementation = _capture_tsec_deps_aspect_impl,
)
```

and this aspect would be applied to e.g.

```bzl
_all_data = rule(
    implementation = _all_data_impl,
    attrs = {
        "tsconfig": attr.label(),
        "target": attr.label(aspects = [capture_tsec_deps_aspect]),
    },
```

What do you think? cc. @josephperrott

2021-09-08 23:00 UTC, uraj commented on tools/defaults.bzl
> +
Yes, aspects is so much better. I have updated the code.

2021-09-10 22:37 UTC, josephperrott approved these changes
LGTM

Per our conversation offline, I would love for us to make this work without having to have an additional set of `tsconfig`s checked in and with windows support.  But we can do these things in follow up PRs.

2021-09-12 10:50 UTC, devversion approved these changes
LGTM. Thanks for switching to the aspect. 

We should definitely look into the Windows support. Usually doing these things in follow-ups tend to be forgotten so we should create an issue for tracking IMO.

2021-09-13 17:18 UTC, uraj commented
@devversion I filled google/tsec#23 to track Windows compatibility.

2021-09-13 19:15 UTC, AndrewKushnir commented
@josephperrott there is an indication that this PR needs g3 presubmit and it looks like only `**/tsconfig-tsec.json` files are synced (see [presubmit CL](https://critique-ng.corp.google.com/cl/396412772)). Do we need those files in g3 of should we exclude them from the sync? Adding the "cleanup" label to this PR for now.

2021-09-13 19:21 UTC, uraj commented
@AndrewKushnir I think they can be excluded.

2021-09-13 19:24 UTC, AndrewKushnir commented
@uraj thanks for the comment. Could you please update the exclude list in https://github.com/angular/angular/blob/master/.github/angular-robot.yml#L42 to reflect that (and also the file in g3 that is mentioned at https://github.com/angular/angular/blob/master/.github/angular-robot.yml#L35)? That should eliminate the need to have a presubmit for this PR.

2021-09-13 19:34 UTC, uraj commented
@AndrewKushnir Updated.

2021-09-13 19:38 UTC, AndrewKushnir commented
Thanks for the update @uraj. I've updated g3 status for this PR and removed the "cleanup" label.

2021-09-13 21:45 UTC, AndrewKushnir commented
Merge-assistance: it's ok to proceed with the current set of reviews, since its just testing changes around everything and not changing the code in those areas.

2021-09-13 21:46 UTC, closed without merging