docs: i18n code snippets
angular/angular pull request #43216
Opened 2021-08-20 20:24 UTC by petebacondarwin

Fixes #43215

2021-08-20 20:34 UTC, mary-poppins commented
You can preview 44983ce at https://pr43216-44983ce.ngbuilds.io/.

2021-08-30 10:47 UTC, mary-poppins commented
You can preview 13b5093 at https://pr43216-13b5093.ngbuilds.io/.

2021-08-30 16:20 UTC, mary-poppins commented
You can preview f60a8e7 at https://pr43216-f60a8e7.ngbuilds.io/.

2021-08-30 17:31 UTC, mary-poppins commented
You can preview 5dd512d at https://pr43216-5dd512d.ngbuilds.io/.

2021-08-31 10:43 UTC, mary-poppins commented
You can preview 70bdf1a at https://pr43216-70bdf1a.ngbuilds.io/.

2021-08-31 16:49 UTC, mary-poppins commented
You can preview 10f7cb8 at https://pr43216-10f7cb8.ngbuilds.io/.

2021-08-31 17:57 UTC, mary-poppins commented
You can preview 2a19278 at https://pr43216-2a19278.ngbuilds.io/.

2021-08-31 18:02 UTC, josmar-crwdstffng approved these changes
The changes meet the requirements for documentation request.  Thank you.

2021-09-07 16:55 UTC, gkalpak requested changes
Looks mostly good :+1:
I have some concerns on externalizing specific code types 🤔

2021-09-07 16:55 UTC, gkalpak commented on aio/content/examples/i18n/doc-files/nginx
> +# #docregion
I think `nginx.conf` would be a better filename.

But again, I am not sure whether having these configs as external files offers any benefit over keeping them inline (where they are easier to keep up-to-date).

2021-09-07 16:55 UTC, gkalpak commented on aio/content/examples/i18n/doc-files/rendered-output.html
> +<!--#docregion-->
This is redundant afaict.

2021-09-07 16:55 UTC, gkalpak commented on aio/tools/transforms/examples-package/services/region-parser.js
> +                const indent = startRegion[0].split(/[^ ]/,1);
Nice one ✨

```suggestion
                const indent = startRegion[0].split(/[^ ]/, 1);
```

2021-09-07 16:55 UTC, gkalpak commented on aio/content/examples/i18n/doc-files/angular.json
> +// #docplaster ...
I am torn on this one (extracting `angular.json` code snippets from `angular.json` copies).
This is less than ideal, but so is hard-coding code-snippets.

Maybe at least add a comment in [aio/tools/examples/UPDATING.md][1].
(It would be even better if we could have a script that checks to ensure this file is the same as the corresponding boilerplate one (minus the docregion comments), but that might be going a bit too far :grin:)

[1]: https://github.com/angular/angular/blob/2a192782faa15e996be37f6d1fe8afd5b4280d42/aio/tools/examples/UPDATING.md

2021-09-08 10:21 UTC, petebacondarwin commented on aio/content/examples/i18n/doc-files/commands.sh
> +# #enddocregion build-production-french
@josmar-crwdstffng ^^^

2021-09-08 10:23 UTC, petebacondarwin commented on aio/tools/transforms/examples-package/services/region-parser.js
> +    nginx: inlineHash,
👍  - I was basing this off the original example. I'll use `nginx.conf` - thanks

2021-09-08 13:03 UTC, petebacondarwin commented on aio/content/guide/i18n.md
> +To change the language, see another subdirectory.
Two white spaces (rather than the one that was there before) adds a soft line break, which is what was actually desired but missed from a previous update to the docs.

2021-09-08 13:11 UTC, mary-poppins commented
You can preview 8686fba at https://pr43216-8686fba.ngbuilds.io/.

2021-09-08 13:25 UTC, petebacondarwin commented on aio/content/guide/i18n.md
> +To change the language, see another subdirectory.
I have reverted the change here, and the change that deleted the single whitespace at the end.
I will leave it to @josmar-crwdstffng to fix this when splitting up this doc.

2021-09-08 13:36 UTC, mary-poppins commented
You can preview 57656b4 at https://pr43216-57656b4.ngbuilds.io/.

2021-09-08 14:59 UTC, petebacondarwin commented on aio/content/examples/i18n/doc-files/angular.json
> +// #docplaster ...
I am going to have a think about fixing this problem of annotating boilerplate files, since there are other cases coming up in other tickets.

2021-09-08 15:35 UTC, josmar-crwdstffng commented on aio/content/examples/i18n/doc-files/commands.sh
> +# #enddocregion build-production-french
@gkalpak @petebacondarwin 

There are multiple items that have been brought into scope, but the focus of this PR is to ensure the following.

*   The markdown should always be using code examples that are valid and tested.
*   The markdown should not be the source for code examples.
*   The markdown should be validated using a linter that meets the needs of the docs.

With those items in mind, we may need to a centralized token for commands to ensure the following.

*   commands are valid and tested
*   commands are not running as part of a build

---  

> In response to "We do not lint, test or otherwise validate them (afaict) and it just makes it harder for authors to edit them (and ensure they remain relevant with the surrounding text)."

If an author/editor knows where to look there is no change in difficulty, and any changes are not hidden among markdown changes.
By enforcing that all code examples are placed outside of the markdown, the location of the source code is identified and code is updated when the code changes (not when during an doc update.

We may need a centralized (non-doc specific) location, such as a sample app to pull the doc-region content and ensure the code matches what a reader will experience.

2021-09-08 15:37 UTC, josmar-crwdstffng commented on aio/content/examples/i18n/doc-files/commands.sh
> +# #enddocregion build-production-french
@gkalpak @petebacondarwin
As long as the files and doc-regions that are implemented in this PR do not cause issues, we should move forward.

2021-09-08 21:00 UTC, petebacondarwin commented on aio/content/examples/i18n/doc-files/commands.sh
> +# #enddocregion build-production-french
> We may need a centralized (non-doc specific) location, such as a sample app to pull the doc-region content and ensure the code matches what a reader will experience.

This is actually what we have at https://github.com/angular/angular/tree/master/aio/content/examples/i18n

The problem is that things like shell commands are things typed in by the user rather than scripts that are executed, so there is no way for these to be verified automatically. But this is true whether they are inline or external. So if you feel that it makes no difference to the doc author then that is fine.

That being said, I think that there are two levels of expertise required. The baseline is being able to find where a doc-region is and to modify it; the more complex requirement is to be able to create these examples (so that they are runnable/testable/etc) and create the doc-regions in the first place. The latter is more tricky for most doc authors I expect.

2021-09-08 21:01 UTC, petebacondarwin commented on aio/content/examples/i18n/doc-files/angular.json
> +// #docplaster ...
@gkalpak  - what do you think?

https://github.com/angular/angular/pull/43216/commits/74cf63325e43ec5968104da13883031a29634bca

2021-09-08 21:04 UTC, mary-poppins commented
You can preview eee6ade at https://pr43216-eee6ade.ngbuilds.io/.

2021-09-08 21:05 UTC, josmar-crwdstffng commented on aio/content/examples/i18n/doc-files/commands.sh
> +# #enddocregion build-production-french
I think we are in agreement.
The doc author should be able to rely on a SME or the tech review (TR) stage to ensure the code example is accurate for the placement in the docs.

2021-09-13 16:10 UTC, gkalpak commented on aio/content/examples/i18n/doc-files/commands.sh
> +# #enddocregion build-production-french
I might be missing something, but I don't see the benefit of moving certain types of code-snippets outside the Markdown.

In fact, there is quite an overhead for authors (whomever that might be: the docs team, SWEs and most importantly community contributors). FWIW, our early choice to move the TypeScript and HTML code-snippets outside the Markdown was only made because we believe the benefits of being able to validate the code outweigh the cost of not having the code side-by-side with the rest of the docs content (where it would be much easier to keep in-sync).

So, I strongly believe that there are certain code types (i.e. those we cannot validate) that would be better off being left in the Markdown.

But, since this is related to docs authoring, I am happy to leave it up to the docs team :smiley:

2021-09-13 16:13 UTC, petebacondarwin commented on aio/tools/transforms/examples-package/processors/collect-examples.spec.js
> +    fileInfo: {relativePath: relativePath, baseName: path.basename(relativePath), extension: path.extname(relativePath).substr(1)},
Ah that might have been to support a previous change in this PR that we decided was not necessary - i.e. the nginx extensionless config file.

2021-09-13 16:15 UTC, petebacondarwin commented on aio/tools/transforms/examples-package/processors/collect-examples.spec.js
> +    fileInfo: {relativePath: relativePath, baseName: path.basename(relativePath), extension: path.extname(relativePath).substr(1)},
I'll remove it

2021-09-13 16:23 UTC, gkalpak commented on aio/content/examples/i18n/doc-files/angular.json
> +// #docplaster ...
I am not particularly happy with this approach 😅
(But I probably wouldn't be happy with any approach 😞)

Could you please update [aio/tools/examples/README.md][1] and [aio/tools/examples/UPDATING.md][2] to take this into account? :pray:

[1]: https://github.com/angular/angular/blob/75a3c778b1f7be913f0287423d40fade68ee9adc/aio/tools/examples/README.md#the-example-configjson
[2]: https://github.com/angular/angular/blob/75a3c778b1f7be913f0287423d40fade68ee9adc/aio/tools/examples/UPDATING.md

2021-09-15 10:24 UTC, petebacondarwin commented on aio/content/examples/i18n/doc-files/angular.json
> +// #docplaster ...
How about this @gkalpak : https://github.com/angular/angular/pull/43216/commits/8b8ad520b86c6a1699a8ceb5e04cb3dd59bf42d0

2021-09-15 10:38 UTC, mary-poppins commented
You can preview 6241cf4 at https://pr43216-6241cf4.ngbuilds.io/.

2021-09-15 11:48 UTC, gkalpak commented on aio/tools/examples/README.md
> +- `"override-boilerplate": string[]`: A list of paths to boilerplate files that are overridden by custom files in this example. Commonly this is used when a boilerplate file is referenced in a guide
Can you also mention that the files listed here might need to be "un-ignored" for this specific example (i.e. by adding something like `!<example-name>/path/to/file` in the appropriate place in `content/examples/.gitignore`)? :pray:

2021-09-15 11:48 UTC, gkalpak commented on aio/tools/examples/example-boilerplate.js
> +  listOverrides() {
:100:

2021-09-15 11:48 UTC, gkalpak commented on aio/content/examples/i18n/doc-files/angular.json
> +// #docplaster ...
Looks great! The `list-overrides` command addition is awesome 🏆

2021-09-15 11:55 UTC, gkalpak approved these changes
Looks great :shipit:

2021-09-15 11:55 UTC, gkalpak commented on aio/tools/examples/README.md
> +- `"override-boilerplate": string[]`: A list of paths to boilerplate files that are overridden by custom files in this example. Commonly this is used when a boilerplate file is referenced in a guide
Actually, why not use camelCase (easier to access from JS and more consistent with `useCommonBoilerplate`)? :grin:

2021-09-15 11:59 UTC, mary-poppins commented
You can preview d649db5 at https://pr43216-d649db5.ngbuilds.io/.

2021-09-15 12:18 UTC, mary-poppins commented
You can preview 094cbfb at https://pr43216-094cbfb.ngbuilds.io/.

2021-09-15 17:46 UTC, closed without merging