refactor(compiler-cli): deprecate the `fullTemplateTypeCheck` compile…
angular/angular pull request #43224
Opened 2021-08-22 19:33 UTC by JoostK

…r option

When compiling your application using the AOT compiler, your templates
are type-checked according to a certain strictness level. Before Angular 9
there existed only two strictness levels of template type checking as
determined by [the `fullTemplateTypeCheck` compiler option](guide/angular-compiler-options).
In version 9 the `strictTemplates` family of compiler options has been
introduced as a more fine-grained approach to configuring how strict your
templates are being type-checked.

The `fullTemplateTypeCheck` flag is being deprecated in favor of the new
`strictTemplates` option and its related compiler options. When
`fullTemplateTypeCheck` is eventually removed, its default value of
`false` will effectively change to `true` which results in type-checking
the following aspects of Angular templates:

1. The content of embedded templates (for example the templates created
   using the `*ngIf` and `*ngFor` structural directive) is type-checked.
2. The arguments to pipes and their return type will be accurately
   checked, instead of resulting in an `any` type.
3. A template reference for an Angular directive or component will be
   inferred as the directive's type, instead of `any`. This check can be
   disabled by disabling the `strictDomLocalRefTypes` option.

2021-08-23 20:53 UTC, mary-poppins commented
You can preview 6ed8ed4 at https://pr43224-6ed8ed4.ngbuilds.io/.

2021-08-23 20:57 UTC, atscott requested changes
I think you'll also want to update the actual readme for the compiler options: https://github.com/angular/angular/blob/master/aio/content/guide/angular-compiler-options.md


* Note there that it's deperated
* Don't use it in examples (use `strictTemplates` instead)

2021-08-23 21:02 UTC, atscott commented on aio/content/guide/deprecations.md
> +When `fullTemplateTypeCheck` is eventually removed, its default value of `false` will effectively change to `true` which results in type-checking
Have we decided exactly what we will do when `fullTemplateTypeCheck` is removed? 

Maybe we shouldn't guess at what _might_ happen but instead just point people to `strictTemplates` as the replacement. We'll have to have a separate breaking changes note when we end up removing `fullTemplateTypeCheck` anyways.

2021-09-18 18:40 UTC, mary-poppins commented
You can preview 7273fb0 at https://pr43224-7273fb0.ngbuilds.io/.

2021-09-18 18:54 UTC, JoostK commented on aio/content/guide/deprecations.md
> +When `fullTemplateTypeCheck` is eventually removed, its default value of `false` will effectively change to `true` which results in type-checking
The primary goal of the deprecation is to get rid of the "basic mode" that is currently available using `fullTemplateTypeCheck: false`, which is the default currently. So from that perspective the eventual removal has to mean that the option is treated as if it were `true` al along, which is indeed a breaking change for projects for which either 1) the `fullTemplateTypeCheck` option has not been configured and `strictTemplates` is not `true`, or 2) the option is explicitly disabled.

The tricky bit about pointing people to `strictTemplates` is that it can only get you even more strict template type-checking. The breaking change only concerns projects that do not have `fullTemplateTypeCheck` at all, in which case the `strictTemplates` option won't help in suppressing template type-errors that may be caused by the breaking change.

Concretely, the following internal type-check flags are to be removed, as they can only be `true` if `fullTemplateTypeCheck` is removed:

- `alwaysCheckSchemaInTemplateBodies`
- `checkTemplateBodies`
- `checkTypeOfNonDomReferences`
- `checkTypeOfPipes`

We discussed in a FW meeting a while ago (when discussing the deprecation of `fullTemplateTypeCheck`) that we don't intent to add new strictness flags to allow disabling some of the above options. Hence, this paragraph goes into detail which template features may start reporting errors once `fullTemplateTypeCheck` is eventually removed.

2021-09-18 18:55 UTC, JoostK commented
@atscott good points on the examples and Angular compiler option docs page, I have added a fixup commit to address that.

2021-09-19 08:50 UTC, JoostK commented on aio/content/guide/deprecations.md
> +When `fullTemplateTypeCheck` is eventually removed, its default value of `false` will effectively change to `true` which results in type-checking
I realized that maybe we could/should push for enabling `fullTemplateTypeCheck` as a separate breaking change before removing the option entirely (perhaps even in v13). Projects that don't have the option configured will then become aware of any new errors and have the choice to temporarily disable `fullTemplateTypeCheck`, at which point they explicitly opt in to the deprecated behavior.

2021-09-20 16:33 UTC, atscott approved these changes
LGTM, thanks for the updates!

2021-09-26 19:16 UTC, mary-poppins commented
You can preview c4b481b at https://pr43224-c4b481b.ngbuilds.io/.

2021-09-27 14:06 UTC, JoostK commented on aio/content/examples/schematics-for-libraries/projects/my-lib/tsconfig.lib.json
> +    "strictTemplates": true,
Can you point me to where those are defined?

2021-09-27 20:10 UTC, mary-poppins commented
You can preview b1dba8e at https://pr43224-b1dba8e.ngbuilds.io/.

2021-09-27 20:15 UTC, JoostK commented on aio/content/examples/schematics-for-libraries/projects/my-lib/tsconfig.lib.json
> +    "strictTemplates": true,
I have been told that these options are handled by StackBlitz; we'll reach out to get them updated. Thanks for letting us know about this.

2021-10-01 16:43 UTC, atscott approved these changes
🥳

2021-10-01 17:25 UTC, alxhub approved these changes
Reviewed-for: public-api

2021-10-01 17:40 UTC, IgorMinar approved these changes
LGTM! Thank you!

Reviewed-for: global-docs-approvers, docs-packaging-and-releasing

2021-10-04 14:18 UTC, iRealNirmal commented on aio/content/guide/deprecations.md
> +    "strictTemplates": true,
if PR [https://github.com/angular/angular/pull/43545](https://github.com/angular/angular/pull/43545) gets merged before this you can update this snippet as well.  

else It has to be taken care in the PR [https://github.com/angular/angular/pull/43545](https://github.com/angular/angular/pull/43545).

2021-10-04 17:33 UTC, alan-agius4 approved these changes

2021-10-04 17:42 UTC, atscott approved these changes
reviewed-for: public-api

2021-10-04 18:38 UTC, mary-poppins commented
You can preview d7ab46c at https://pr43224-d7ab46c.ngbuilds.io/.

2021-10-04 19:04 UTC, jessicajaniuk approved these changes
LGTM :cookie:

reviewed-for: public-api

2021-10-04 23:32 UTC, dylhunn commented
This PR was merged into the repository by commit cc96f322df85f5159ff51c590518acf14f242264.

2021-10-04 23:32 UTC, closed without merging