Extended refactor
angular/angular pull request #43232
Opened 2021-08-23 18:10 UTC by danieltre23

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The extended package had some refactors pending which are addressed here.

Issue Number: #42966

## What is the new behavior?
Refactored the extended package, added a `TemplateCheckWithVisitor` abstract class and added a new `TemplateCheck` for when the left side of a binary nullish coalescing operation is not nullable.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information
Ignore first 3 commits since they are addressed in #43134

2021-08-23 19:00 UTC, dgp1130 reviewed
Awesome work, thanks for putting this all together!

Mostly a bunch of nits and even the non-nits are fairly nitpicky.

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/api/api.ts
> +export interface TemplateDiagnostic extends ts.Diagnostic {
Would it make sense to always use `NgTemplateDiagnostic` / include the `__ngCode` brand into `TemplateDiagnostic`? Is there a need to have two distinct types here, or is this just because we don't want to take the effort to update all existing references right now?

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +            this, typeCheckProgram.getTypeChecker(), [new InvalidBananaInBoxCheck()]);
Would it be possible to share the `[ new InvalidBananaInBoxCheck() ]` array between both the compiler and language service code paths? That way we don't need to remember to update two places when we add a new check.

2021-08-23 19:00 UTC, dgp1130 commented on packages/language-service/ivy/test/diagnostic_spec.ts
> +  it('should not produce invalid banana in box warning in external html file', () => {
```typescript
it('... in external html file with correct two-way binding syntax', () => { /* ... */ });
```

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/src/extended_template_checker.ts
> +      private readonly templateChecks: TemplateCheck<ErrorCode>[]) {
Can we drop the `private` from these and just use the instances on `this.ctx`? That would be three less fields to have to maintain.

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/api/api.ts
> +      readonly check: TemplateCheckWithVisitor<T>) {
Nit: Can these fields be `private` or at least `protected`?

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/invalid_banana_in_box/index.ts
> +  override code: ErrorCode.INVALID_BANANA_IN_BOX = 8101;
Nit: Can we do:

```typescript
override code = ErrorCode.INVALIDA_BANANA_IN_BOX;
```
Or at least:
```typescript
override code = ErrorCode.INVALIDA_BANANA_IN_BOX as const;
```
to avoid the `8101` literal?

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/invalid_banana_in_box/index.ts
> +    if (node instanceof TmplAstBoundEvent) {
We only ever return one diagnostic now right, since we don't need to manually track the `diagnostics` array anymore? So I think we could simplify this to something like:

```typescript
override visitNode(/* ... */): NgTemplateDiagnostic<ErrorCode.INVALID_BANANA_IN_BOX>[] {
  if (!(node instanceof TmplAstBoundEvent)) return [];

  const {name} = node;
  if (!name.startsWith('[') || !name.endsWith(']')) return [];

  const diagnostic = ctx.templateTypeChecker.makeTemplateDiagnostic(/* ... */);
  return [diagnostic];
}
```

This eliminates the unnecessary `diagnostics` array and uses early returns to reduce indentation to make things a little easier to read.

(I'm not totally convinced that inverting the `name` check actually makes this simpler, since that's a more complex expression, so up to you if you want to leave that one as is.)

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/src/extended_template_checker.ts
> -function deduplicateDiagnostics(diagnostics: TemplateDiagnostic[]): TemplateDiagnostic[] {
Glad we're able to remove this now!

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/api/api.ts
> +      NgTemplateDiagnostic<T>[];
I'm glad we're able to structure this type to completely hide the `diagnostics` array and just have it return `NgTemplateDiagnostic<T>[]`. Much cleaner this way!

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/diagnostics/src/error_code.ts
> +   * The left side of a nullish coalescing operation is not nullable.
Nit: This feels self-explanatory to me atm, but I have all the context about what's going on here. Consider adding a short example to show the kind of mistake this is trying to catch.

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +  override code: ErrorCode.NULLISH_COALESCING_NOT_NULLABLE = 8101;
Same as the banana in box check, any way to not use the literal `8101` here?

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +        if (typeLeft.getNonNullableType() === typeLeft) {
What about `undefined`? I believe `undefined ?? 'test' === 'test'`, so we should allow the left-operand to be `undefined` without throwing a warning. Is that covered here as well?

We should also call out that case in the doc comments for the class/error code.

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +              `The left side of this nullish coalescing operation is not nullable, therefore the '??' operator can be safely removed.`));
Nit: `The left side of this nullish coalescing operation does not include `null` or `undefined` in its type, therefore the '??' operator can be safely removed.`

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +          const symbol = ctx.templateTypeChecker.getSymbolOfNode(node, component);
Would we want to use the span of the left operand specifically, or the whole operation? Not sure about the best option here, but want to make sure that is at least considered.

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/nullish_coalescing_not_nullable/spec.ts
> +  describe('TemplateChecks', () => {
Nit: `describe('NullishCoalescingNotNullableCheck', ...)`

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/nullish_coalescing_not_nullable/spec.ts
> +    it('should not produce nullish coalescing warning', () => {
Nit: `should not produce nullish coalescing warning for a nullable input`

2021-08-23 19:00 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/nullish_coalescing_not_nullable/spec.ts
> +    });
We should also add a test that a `string | undefined` type does not show the warning.

2021-08-23 19:07 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +          const symbol = ctx.templateTypeChecker.getSymbolOfNode(node, component);
I actually had just the left operand here at first, but it made more sense to me to include the nullish operator since that's the part that needs to be removed. But if you think just the left operand makes sense here I can change it.

2021-08-23 19:10 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/typecheck/api/api.ts
> +export interface TemplateDiagnostic extends ts.Diagnostic {
I guess it was just to avoid the effort of updating the existing references, but I could updated them if you'd prefer that.

2021-08-23 19:12 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +          const symbol = ctx.templateTypeChecker.getSymbolOfNode(node, component);
I'm not sure how it displays or if we could use related information to be helpful here at all.

I'll defer to others on this if anyone has strong opinions here. I mainly just wanted to make sure we had considered it.

2021-08-23 19:13 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/api/api.ts
> +export interface TemplateDiagnostic extends ts.Diagnostic {
I'm fine with deferring them for now, we can always merge these two types later.

2021-08-23 19:14 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +            this, typeCheckProgram.getTypeChecker(), [new InvalidBananaInBoxCheck()]);
I actually exported this array from the extended package, but @alxhub suggested that it should be the consumer's responsibility to select the checks it wants to use. https://github.com/angular/angular/pull/43107#discussion_r691515257

2021-08-23 19:16 UTC, danieltre23 commented on packages/language-service/ivy/test/diagnostic_spec.ts
> +  it('should not produce invalid banana in box warning in external html file', () => {
This is actually from the first 3 commits, which are already in #43134 so I will address it there.

2021-08-23 19:24 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +            this, typeCheckProgram.getTypeChecker(), [new InvalidBananaInBoxCheck()]);
I agree it's the consumer's responsibility, but I also think the compiler and language service should share a set of checks if possible.

I'm not sure where exactly it makes sense for that to live, but maybe just another file in `typecheck/` which re-exports the array? @alxhub, what do you think?

2021-08-23 19:24 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +        if (typeLeft.getNonNullableType() === typeLeft) {
It is covered, but I'll add a test anyways. And include it in the doc comments.

2021-08-23 20:21 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +            this, typeCheckProgram.getTypeChecker(), [new InvalidBananaInBoxCheck()]);
`NgCompiler` should have a `getDiagnosticsForComponent()` which calls through to extended template diagnostics, then the language service simply calls that.

https://github.com/angular/angular/blob/261bce65fbcce5623044d43c52905424f98e65b7/packages/compiler-cli/src/ngtsc/core/src/compiler.ts#L1048

2021-08-23 20:26 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +          const symbol = ctx.templateTypeChecker.getSymbolOfNode(node, component);
After discussion, let's just leave it highlighting the whole operator.

2021-08-23 22:26 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts
> +            this, typeCheckProgram.getTypeChecker(), [new InvalidBananaInBoxCheck()]);
Addressed in #43134

2021-08-23 22:28 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/diagnostics/src/error_code.ts
> +   * The left side of a nullish coalescing operation is not nullable.
I added the example.

2021-08-23 22:30 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/nullish_coalescing_not_nullable/spec.ts
> +    it('should not produce nullish coalescing warning', () => {
Changed `input` to `type`, hope that's okay.

2021-08-23 22:33 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/nullish_coalescing_not_nullable/spec.ts
> +    it('should not produce nullish coalescing warning', () => {
:+1:

2021-08-24 06:27 UTC, dgp1130 approved these changes
LGTM, just a few small improvements and a test to double check.

2021-08-24 06:27 UTC, dgp1130 commented on packages/language-service/ivy/test/diagnostic_spec.ts
> +       const project = createModuleAndProjectWithDeclarations(env, 'test', files);
Should we be enabling `strictTemplates` and `_extendedTemplateDiagnostics` here and the above test ("should not produce invalid banana in box warning with correct two-way binding syntax")? I noticed some of the other tests explicitly include those flags.

I'm wondering if these tests are skipping the extended template checks altogether. Might be worth changing the template to introduce the error and make sure it properly fails the test.

2021-08-24 06:27 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/src/extended_template_checker.ts
> +      readonly templateChecks: TemplateCheck<ErrorCode>[]) {
Nit: Can we also drop the `readonly` here so we don't have unnecessary fields?

2021-08-24 06:27 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +    if (typeLeft.getNonNullableType() !== typeLeft) return [];
Nit: The comment and the if statement are inverted, which can be a bit confusing. I suggest updating the comment to be the same, something like:

> If the left operand's type is different from its non-nullable self, then it must contain a `null` or `undefined` so this nullish coalescing operator is useful. No diagnostic to report.

Alternatively/in addition, you could include a comment shortly after the if-statement to the extent of:

> Left operand's type is equivalent to its non-nullable self, so it must *not* include `null` or `undefined` so the nullish coalescing operator is useless and should be removed. Emit a diagnostic to inform the user.

2021-08-24 06:27 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/nullish_coalescing_not_nullable/spec.ts
> +          'TestCmp': '{{ var1 ?? null }}',
I suggest using a non-nullable value as the right operand for these tests.

It is reasonable that the same or a different check could flag `x ?? null` as that is also useless (if the left operand does not include `undefined` in its type). So this could encounter an edge case we don't intend and it could mislead readers into the thinking the intent of this check is to detect `?? null`.

Just using `?? 'foo'` in these tests should be enough to avoid that misrepresentation and still satisfy all the requirements of the tests.

2021-08-24 16:05 UTC, atscott requested changes
This looks great! Only some small nits, but otherwise LGTM.

2021-08-24 16:05 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +    // Get span of binary node
nit: I don't think this comment is useful and should be removed

2021-08-24 16:05 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +    // Get the type of the value on the left side.
nit: I don't think this comment is useful and should be removed

2021-08-24 16:05 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +                     ?.span!;
This operation is a bit odd. You use optional chaining and then say "none of these were nullable" with `!`.

2021-08-24 16:14 UTC, danieltre23 commented on packages/language-service/ivy/test/diagnostic_spec.ts
> +       const project = createModuleAndProjectWithDeclarations(env, 'test', files);
Actually the comment for the test was wrong, this is not testing the correct syntax, it's testing that diagnostics are not generated when the flags are not set, I fixed the comment in #43134

2021-08-24 16:19 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/src/extended_template_checker.ts
> +      readonly templateChecks: TemplateCheck<ErrorCode>[]) {
I can do that for `templateTypeChecker` and `typeChecker`, but `templateChecks` is needed in the `getDiagnosticsForComponent` function.

2021-08-24 16:51 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/api/api.ts
> +    if (template.tagName === 'ng-template') {
Done, please let me know if I explained it correctly.

2021-08-24 16:52 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +                     ?.span!;
Changed the `!` to `getTemplateMappingAtShimLocation`.

2021-08-24 16:55 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +    const typeLeft = (symbolLeft as ExpressionSymbol).tsType;
`ExpressionSymbol` is an interface so I can't use `instanceof` but let me think about this.

2021-08-24 17:06 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +    const typeLeft = (symbolLeft as ExpressionSymbol).tsType;
Ah, you do `symbolLeft.kind !== SymbolKind.Expression` then

2021-08-24 18:09 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +        ctx.templateTypeChecker.getSymbolOfNode((node.left as PropertyRead), component);
Noticed this in the screenshare just now: the LHS of a binary is not necessarily a `PropertyRead`, as e.g. you can also have a call expression `call() ?? 'fallback'`.

2021-08-24 18:09 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/nullish_coalescing_not_nullable/index.ts
> +    if (typeLeft.getNonNullableType() !== typeLeft) return [];
I wonder if this works correctly if `strictNullChecks` is disabled, can you add tests for that?

2021-08-24 19:26 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/nullish_coalescing_not_nullable/spec.ts
> +    it('should produce nullish coalescing warning with `strictNullChecks` disabled', () => {
My expectation would actually be the opposite here: if `strictNullChecks` is disabled then we'd have to assume that everything is nullable, as an assignment like `field: string = null;` is accepted. The opposite is also true: if a field is declared as `string|null` type then the `null` type is elided under `strictNullChecks: false`, so you'd always find that `typeLeft.getNonNullableType() === typeLeft` is true. I'd suggest to also add a testcase for that scenario (and assert that _no_ diagnostics are reported in both cases).

tldr; I think the rule itself has to be excluded if `strictNullChecks` is disabled. I'm not sure if the rules have access to configuration options at the moment or if this should be the responsibility of the consumer of this API (which is responsible for creating set of rules to use in the first place). I'd be great if the rule could disable itself (possibly avoiding the visitor walk) as that would make it more self-contained.

2021-08-24 22:56 UTC, danieltre23 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/nullish_coalescing_not_nullable/spec.ts
> +    it('should produce nullish coalescing warning with `strictNullChecks` disabled', () => {
The `NullishCoalescingNotNullableCheck` will only be called if `strictNullChecks` is enabled.

2021-08-25 18:11 UTC, JoostK approved these changes
Overall LGTM, left a few nit comments

2021-08-25 18:29 UTC, atscott approved these changes

2021-08-25 20:35 UTC, atscott approved these changes
reviewed-for: public-api

2021-08-26 18:09 UTC, IgorMinar approved these changes
LGTM! Thanks!

Reviewed-for: public-api

2021-08-26 19:35 UTC, alxhub approved these changes
Reviewed-for: public-api

2021-08-26 23:36 UTC, closed without merging