docs: add subtopics fo internationalization
angular/angular pull request #43245
Opened 2021-08-24 15:49 UTC by josmar-crwdstffng

Add subtopics fo internationalization guide. Update links.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The Internationalization guide is a single topic.

Issue Number: N/A

## What is the new behavior?

The Internationalization guide is a multiple topics.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

The links embedded in existing code comments point new subtopics.

## Other information

2021-08-24 16:07 UTC, mary-poppins commented
You can preview 111b447 at https://pr43245-111b447.ngbuilds.io/.

2021-09-01 21:50 UTC, mary-poppins commented
You can preview 88832fb at https://pr43245-88832fb.ngbuilds.io/.

2021-09-01 22:01 UTC, mary-poppins commented
You can preview a2265eb at https://pr43245-a2265eb.ngbuilds.io/.

2021-09-01 22:12 UTC, mary-poppins commented
You can preview f58efe1 at https://pr43245-f58efe1.ngbuilds.io/.

2021-09-02 23:49 UTC, mary-poppins commented
You can preview dc4fe47 at https://pr43245-dc4fe47.ngbuilds.io/.

2021-09-10 09:11 UTC, petebacondarwin requested changes
The separation of the topics looks good! This PR is probably blocked on the one that pulls the examples out into separate files, since the two PRs conflict with each other.

---

Removing `aio/content/guide/i18n.md` will cause lots of inbound links (from 3rd party sites) pointing to a 404 page - e.g. https://pr43245-dc4fe47.ngbuilds.io/guide/i18n.

Perhaps instead, keep this page but use the content you have put in `aio/content/guide/i18n-overview.md` instead? This would also help with SEO for this page.

Alternatively, I think we would need to setup a redirect from the `guide/i18n` to `guide/i18n-overview`.

---

Could you factor out the non-i18n changes from this PR (or at least create a separate commit)? It makes it harder to review the differences specific to this change and also makes the git history less clear.

2021-09-10 09:11 UTC, petebacondarwin commented on aio/content/guide/angular-compiler-options.md
> +<code-example language="json">
The changes to this file (and others below), other than updating the links to i18n pages, do not seem relevant to this PR. Perhaps put these additional changes into another PR, or at least a separate commit?

2021-09-13 19:11 UTC, mary-poppins commented
You can preview 9ca9df4 at https://pr43245-9ca9df4.ngbuilds.io/.

2021-09-13 19:59 UTC, petebacondarwin commented on aio/tests/deployment/shared/URLS_TO_REDIRECT.txt
> +/guide/i18n --> /guide/i18n-overview
👍

2021-09-13 22:26 UTC, josmar-crwdstffng commented on aio/content/guide/angular-compiler-options.md
> +<code-example language="json">
The markdown was cleaned as part of the update to the link to the i18n content.

2021-09-13 23:00 UTC, mary-poppins commented
You can preview 5221837 at https://pr43245-5221837.ngbuilds.io/.

2021-09-14 18:18 UTC, TeriGlover approved these changes
Editing review completed with several comments. Otherwise, LGTM.

2021-09-14 18:18 UTC, TeriGlover commented on aio/content/navigation.json
> +                  "tooltip": "Mearge translations into your app"
```suggestion
                  "tooltip": "Merge translations into your app"
```

2021-09-14 21:53 UTC, mary-poppins commented
You can preview 21958a0 at https://pr43245-21958a0.ngbuilds.io/.

2021-09-14 22:10 UTC, josmar-crwdstffng reviewed
Acknowledged or implemented all edit review feedback.

2021-09-14 22:10 UTC, josmar-crwdstffng commented on aio/content/guide/i18n-common-merge.md
> +When a translation is missing, the build succeeds but generates a warning such as `Missing translation for message "foo"`.
Updated text.

```md
When a translation is missing, the build succeeds but generates a warning such as `Missing translation for message "{translation_text}"`.
```

2021-09-14 22:10 UTC, josmar-crwdstffng commented on aio/content/guide/i18n-common-locale-id.md
> +*   IDs conform to the Unicode Common Locale Data Repository (CLDR).
Updated link since the site is insecure.

```md
[LocStandardsIso6392]: http://www.loc.gov/standards/iso639-2 "ISO 639-2 Registration Authority | Library of Congress"
```

2021-09-14 22:14 UTC, josmar-crwdstffng commented on aio/content/guide/deprecations.md
> +***Note***: *IE11 will be supported in Angular v12 LTS releases through November 2022.*
Updated text.

```md
**Note**: IE11 will be supported in Angular v12 LTS releases through November 2022.
```

2021-09-14 22:16 UTC, josmar-crwdstffng commented on aio/content/guide/pipes.md
> +*   In the `flying-heroes.component.html (v1)` template, the `*ngFor` repeater displays the hero names.
@TeriGlover The linking is not handled in this file.

2021-09-14 22:17 UTC, mary-poppins commented
You can preview 7d2a259 at https://pr43245-7d2a259.ngbuilds.io/.

2021-09-14 22:32 UTC, mary-poppins commented
You can preview ab47d0f at https://pr43245-ab47d0f.ngbuilds.io/.

2021-09-14 22:37 UTC, TeriGlover commented
@googlebot I consent.

2021-09-14 22:41 UTC, TeriGlover commented
@googlebot I consent.

2021-09-14 22:42 UTC, josmar-crwdstffng commented
@googlebot I consent.

2021-09-15 10:36 UTC, petebacondarwin approved these changes

2021-09-15 10:37 UTC, petebacondarwin commented
@TeriGlover will need to consent to fix the CLA issue.
And the PR needs a rebase to resolve the conflicting files.

2021-09-15 15:33 UTC, josmar-crwdstffng commented
> @TeriGlover will need to consent to fix the CLA issue.
> And the PR needs a rebase to resolve the conflicting files.

@petebacondarwin 
The rebase was successful and @TeriGlover comment `@googlebot I consent.` multiple times.
What is the next step?

2021-09-15 15:37 UTC, petebacondarwin commented
The next step is to get a Googler to override the bot

2021-09-15 15:42 UTC, mary-poppins commented
You can preview 8b2d586 at https://pr43245-8b2d586.ngbuilds.io/.

2021-09-15 18:34 UTC, mary-poppins commented
You can preview 69183ba at https://pr43245-69183ba.ngbuilds.io/.

2021-09-16 21:18 UTC, josmar-crwdstffng commented
@gkalpak @alxhub @IgorMinar @JoostK

You were added as reviewers.  

The changes in the PR include the following.

*   Updated links in notes in `.ts` files
*   Separated `.md` file into multiple `.md` files
*   Added redirect
*   Updated left-nav toc

Please review the changes for technical accuracy.

2021-09-16 21:20 UTC, mary-poppins commented
You can preview 6050161 at https://pr43245-6050161.ngbuilds.io/.

2021-09-20 16:51 UTC, aikidave approved these changes
Reviewed-for: global-docs-approvers

2021-09-20 19:38 UTC, mary-poppins commented
You can preview b26ef3b at https://pr43245-b26ef3b.ngbuilds.io/.

2021-09-20 21:38 UTC, alxhub approved these changes

2021-09-20 21:56 UTC, mary-poppins commented
You can preview 78659ba at https://pr43245-78659ba.ngbuilds.io/.

2021-09-23 21:42 UTC, alxhub commented
Hi @josmar-crwdstffng,

This PR needs to be rebased before it can land - thanks!

2021-09-23 21:52 UTC, josmar-crwdstffng commented
@alxhub
Rebased and pushed.  Please continue merge.
@josephperrott has flipped the `cla: yes` label multiple times.

2021-09-23 21:58 UTC, mary-poppins commented
You can preview 4eb47e5 at https://pr43245-4eb47e5.ngbuilds.io/.

2021-09-23 22:40 UTC, closed without merging