docs: code examples spacing enhancements
angular/angular pull request #43241
Opened 2021-08-24 09:36 UTC by eneajaho

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Code style update (formatting, local variables)

## What is the current behavior?
Many code examples don't have good formatting.

## What is the new behavior?
This PR addresses some of them in the first sections.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

2021-08-24 09:42 UTC, eneajaho commented
@googlebot I fixed it.

2021-08-25 07:50 UTC, eneajaho commented
Hi @aikidave,  should I continue to work on this PR? I'm planning to check also the other examples in the other sections, but I wanted to make sure that I'm in the right direction.

2021-08-25 14:42 UTC, aikidave commented
Hi @eneajaho! Thanks for this PR!

I can't speak to the impact of these spacing changes. I'm looping in @gkalpak, who knows more than I do. George, what do you think?

2021-08-30 21:24 UTC, mary-poppins commented
You can preview 639f480 at https://pr43241-639f480.ngbuilds.io/.

2021-08-30 21:36 UTC, gkalpak requested changes
I think it looks good. Thx, @eneajaho :+1:

I think it makes sense to try and land this PR without touching other examples and potentially make similar refactorings/improvements to other examples in a separate PR. (These types of PRs tend to become really big and hard to review.)

It would also greatly help with reviewing if you did any follow-up changes in [fixup commits][1] 🙏

##
Thx again for working on this, @eneajaho ✨ 

[1]: https://github.com/angular/angular/blob/dcfabf08afd888dcc891900c883910ab35efb8eb/docs/FIXUP_COMMITS.md

2021-08-30 21:36 UTC, gkalpak commented on aio/content/examples/dynamic-component-loader/src/app/app.module.ts
> +    AdDirective ],
Since you're at it already:

```suggestion
    AdDirective
  ],
```

2021-08-30 21:36 UTC, gkalpak commented on aio/content/examples/getting-started/src/app/product-list/product-list.component.html
> +       [routerLink]="['/products', product.id]">
This seems inconsistent with how other elements are wrapped.
IMO, this could also be left as one line, since it is quite short.

2021-08-31 07:32 UTC, eneajaho commented on aio/content/examples/getting-started/src/app/product-list/product-list.component.html
> +       [routerLink]="['/products', product.id]">
Yes, it's true that it's a bit inconsistent. But I don't think it will be better if it was a one liner, check the screenshots below: 

Current: 
![image](https://user-images.githubusercontent.com/25394362/131461532-e1b8a413-8b04-4d5a-a8a3-134bfc1f8c9f.png)

My fix: 
![image](https://user-images.githubusercontent.com/25394362/131461610-4d4a6902-a47e-4334-a074-846f460409ba.png)

I think it's more readable if it's in a new line.

What do you think it's done like this: 

```html
<a
  [title]="product.name + ' details'"
  [routerLink]="['/products', product.id]">
    {{ product.name }}
</a>
```

2021-08-31 07:38 UTC, mary-poppins commented
You can preview 9bade58 at https://pr43241-9bade58.ngbuilds.io/.

2021-09-01 13:36 UTC, gkalpak commented on aio/content/examples/getting-started/src/app/product-list/product-list.component.html
> +       [routerLink]="['/products', product.id]">
Fair enough. Let's go with your last suggestion :+1:

2021-09-01 20:31 UTC, eneajaho commented on aio/content/examples/getting-started/src/app/product-list/product-list.component.html
> +       [routerLink]="['/products', product.id]">
Done.

2021-09-01 20:34 UTC, mary-poppins commented
You can preview ec963c6 at https://pr43241-ec963c6.ngbuilds.io/.

2021-09-02 11:58 UTC, gkalpak approved these changes
Nice! Thx again, @eneajaho :+1:

Reviewed-for: global-docs-approvers

2021-09-02 16:45 UTC, closed without merging