feat(router): emit activate/deactivate events when an outlet gets attached/detached
angular/angular pull request #43333
Opened 2021-09-03 14:36 UTC by dimakuba

Previously the events of `RouterOutlet` (activate/deactivate) were not fired
when an outlet got attached/detached with `RouteReuseStrategy`. The changes configure
`RouterOutlet` to emit events when an outlet gets attached/detached.

2021-09-03 16:21 UTC, atscott requested changes
This changes the meaning of the `activate` and `deactivate` events. The `attach` and `detach` are _similar_ but not exactly the same. Especially when comparing `detach` with `deactivate`, the `deactivate` emits after the component is destroyed.

In fact, this behavior is _specifically_ documented by the `activate` and `deactivate` events. 
> A router outlet emits an activate event when a new component is instantiated,
and a deactivate event when a component is destroyed.

This change is contrary to the documented behavior. Please open a feature request for new events `attached` and `detached` rather than changing the meaning of the current `activate` and `deactivate` events.

2021-09-09 19:01 UTC, atscott requested changes
Just a note that it would be nice to mention a use-case for this feature either in the commit message or a resolved issue.

2021-09-10 15:30 UTC, atscott requested changes

2021-09-10 15:30 UTC, atscott commented on packages/router/src/directives/router_outlet.ts
> + * and detached event when the `RouteReuseStrategy` instructs to detach the subtree.
```suggestion
 * deactivate event when a component is destroyed.
 * An attached event emits when the `RouteReuseStrategy` instructs the outlet to reattach the subtree,
 * and the detached event emits when the `RouteReuseStrategy` instructs the outlet to detach the subtree.
```

2021-09-10 15:30 UTC, atscott commented on packages/router/src/directives/router_outlet.ts
> +   */
Could you be more explicit about what's emitted here? The documentation doesn't specify what the emitted value actually is.

2021-09-13 16:05 UTC, atscott approved these changes

2021-09-13 16:05 UTC, atscott approved these changes
reviewed-for: public-api

2021-09-13 23:26 UTC, atscott commented
[presubmit](https://fusion2.corp.google.com/presubmit/tap/396375213/targets?utm_source=tap-redirect)

2021-09-14 01:37 UTC, alfaproject commented on packages/router/src/directives/router_outlet.ts
> +  @Output('attached') attachedEvents = new EventEmitter<unknown>();
The verb tense between activate/deactivate and attached/detached is not consistent. Is that on purpose?

2021-09-14 23:05 UTC, jessicajaniuk approved these changes
LGTM :cookie:

reviewed-for: public-api

2021-09-24 01:02 UTC, IgorMinar approved these changes
LGTM for api changes! Thank you, @dimakuba. This is a nice addition.

Reviewed-for: public-api

2021-09-24 22:34 UTC, atscott commented on packages/router/src/directives/router_outlet.ts
> +  @Output('attached') attachedEvents = new EventEmitter<unknown>();
@dimakuba I noticed this as well but thought at the time that it wouldn't matter too much. But I think we might as well just stay consistent. Let's rename these to `attachEvents` and `detachEvents` to match the existing `activateEvents` and `deactivateEvents`.

This otherwise has all the necessary approvals and is merge ready.

2021-09-27 07:43 UTC, dimakuba commented on packages/router/src/directives/router_outlet.ts
> +  @Output('attached') attachedEvents = new EventEmitter<unknown>();
thanks for the suggestion, now it look consistently

2021-09-28 21:16 UTC, closed without merging