fix(docs-infra): improve aio contributors page responsiveness
angular/angular pull request #43355
Opened 2021-09-05 13:00 UTC by dario-piotrowicz

Improve the aio contributors page responsiveness regarding the browser's
font-size so that the page looks good regarding on font-size settings
(no cropped or cramped content)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

The angular.io contributors page doesn't adapt well on different front-size settings

![before](https://user-images.githubusercontent.com/61631103/132127703-5bdc367f-0fbc-42c1-9406-537a16247d41.gif)

## What is the new behavior?

The angular.io contributors page adapt well on different front-size settings

![after](https://user-images.githubusercontent.com/61631103/132127714-f9aa9ac7-0147-4f4f-aaf9-7777eb3cf84a.gif)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2021-09-07 17:11 UTC, mary-poppins commented
You can preview 5ec6556 at https://pr43355-5ec6556.ngbuilds.io/.

2021-09-07 17:38 UTC, gkalpak reviewed
Nice one, @dario-piotrowicz :100:
A couple of comments - otherwise lgtm :+1:

2021-09-07 17:38 UTC, gkalpak commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +          $size: 2rem;
Do we need a separate `$size` variable here? Shouldn't this match the `.icon`'s size?

2021-09-07 17:38 UTC, gkalpak commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +          }
These changes seem to be making the icons smaller. Could we get the responsiveness while keeping the current sizes (which are easier to click//tap, esp. on mobile devices)?

2021-09-07 20:18 UTC, dario-piotrowicz commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +          }
mh.... yeah I totally see what you mean.... I made the icon becoming smaller because on a very small font-size setting it really looked way too big compared to the contributor image and text... but I do understand what you mean and it is totally a valid point....

maybe I could put here a min-width or something.... :thinking: 

If it's ok with you, I'll just try share some screenshots here and we can decide what's best :slightly_smiling_face:

2021-09-07 21:06 UTC, dario-piotrowicz commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +          $size: 2rem;
indeed! :+1:

2021-09-07 21:13 UTC, dario-piotrowicz commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +          }
This is how it looks on a very small font-size setting:
![Screenshot at 2021-09-07 22-09-57](https://user-images.githubusercontent.com/61631103/132411421-be55ff73-446b-4c5d-8ed1-5ea46049401a.png)

The icons get a bit too big, but it's not actually that bad :thinking:

2021-09-07 22:08 UTC, dario-piotrowicz commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +          }
Could we put the "view bio" on a separate line? in that way I could use clamp and make sure it never gets too small (compared to the icons), this would be the result:
![Screenshot at 2021-09-07 23-05-44](https://user-images.githubusercontent.com/61631103/132416942-1043d3e9-1f25-4624-b522-36bf2ff7769c.png)

2021-09-10 17:30 UTC, gkalpak commented
@dario-piotrowicz, can you please rebase this PR to allow CI to generate the preview :pray:

2021-09-10 17:54 UTC, dario-piotrowicz commented
> @dario-piotrowicz, can you please rebase this PR to allow CI to generate the preview

Done! :slightly_smiling_face: :+1: 

So sorry I thought you could fix it with a click on the ci or something so didn't try to fix the failing ci process :sweat: :bow:

2021-09-10 18:04 UTC, mary-poppins commented
You can preview 1a99f9d at https://pr43355-1a99f9d.ngbuilds.io/.

2021-09-13 15:39 UTC, gkalpak requested changes

2021-09-13 15:39 UTC, gkalpak commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +      font-size: clamp(10px, 1.4rem, 30px);
Please also use a fallback value for browsers that do not support `clamp` (_\*cough\* IE \*cough\*_).

2021-09-13 15:39 UTC, gkalpak commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +          }
The icons seems to still be smaller that they are now (originally discussed in https://github.com/angular/angular/pull/43355#discussion_r703702947).
Can please make sure that they remain the same size (with default browser font-size settings)?

2021-09-13 20:16 UTC, dario-piotrowicz commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +      font-size: clamp(10px, 1.4rem, 30px);
The fallback value is implemented by the mixin on line 62 :smile: 

![Screenshot at 2021-09-13 21-12-16](https://user-images.githubusercontent.com/61631103/133150402-b06739ac-4429-486f-87b5-ec75334d8515.png)

2021-09-13 20:27 UTC, dario-piotrowicz commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +          }
yes indeed... Sorry my bad I missed that :sweat: 

(the size should not be 20px but 23px as that is the height of the icons in live)

2021-09-13 20:29 UTC, dario-piotrowicz commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +          }
ps: sorry I missed that about your comment as I thought that it was originally only saying that the icons become smaller with smaller font-sizes (thing that I already amended) :sweat_smile: :slightly_smiling_face:

2021-09-13 20:36 UTC, mary-poppins commented
You can preview 63e056b at https://pr43355-63e056b.ngbuilds.io/.

2021-09-14 11:01 UTC, gkalpak commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +      font-size: clamp(10px, 1.4rem, 30px);
Ah, I missed that :+1:

2021-09-14 11:36 UTC, gkalpak requested changes
The styles look good :+1: Thx, @dario-piotrowicz!

The last remaining issue is updating the CSS payload size limits. I.e. update the `styles` entry for both [aio][1] and [aio-local][2] to reflect the new (increased :cry:) size of the `styles.css` file (currently **69724**B (from **69237**B on master)).

I have also left some comments on rules that I believe could be removed (and potentially reduce the size impact of this PR).

[1]: https://github.com/angular/angular/blob/63e056b7cd2397eb67f168d83ace011cc22664af/goldens/size-tracking/aio-payloads.json#L8
[2]: https://github.com/angular/angular/blob/63e056b7cd2397eb67f168d83ace011cc22664af/goldens/size-tracking/aio-payloads.json#L20

2021-09-14 11:36 UTC, gkalpak commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +    width: 100%;
Width this change (or even without), I believe you can remove the `display`, `justify-content` and `align-items` styles from `.contributor-image` block above (since `.contributor-info` is the one and only child of `.contributor-image`).

2021-09-14 11:36 UTC, gkalpak commented on aio/src/styles/2-modules/contributor/_contributor.scss
>      flex-direction: row;
This can be remove, since it is the default.

2021-09-14 11:36 UTC, gkalpak commented on aio/src/styles/2-modules/contributor/_contributor.scss
>      align-items: center;
This doesn't seem to be necessary any more.

2021-09-14 11:36 UTC, gkalpak commented on aio/src/styles/2-modules/contributor/_contributor.scss
>      text-align: center;
This doesn't seem to be necessary any more.

2021-09-14 11:36 UTC, gkalpak commented on aio/src/styles/2-modules/contributor/_contributor.scss
>        padding: 0;
This doesn't seem to do much. Maybe it could be removed?

2021-09-14 11:36 UTC, gkalpak commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +            transform: translateY(-10%) rotateZ(45deg);
I think you leave it as `transform: rotate(45deg);` and also remove the `line-height: 0` from `mat-icon[svg-icon]`.
The icons still look fine (if not pixel-perfect), the styles will be slightly more generic and we'll even save a few bytes of CSS 😛

2021-09-15 20:36 UTC, dario-piotrowicz commented on aio/src/styles/2-modules/contributor/_contributor.scss
>        padding: 0;
yes the computed padding is still 0 anyways, I imagine this is the default value for anchors

2021-09-15 20:39 UTC, dario-piotrowicz commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +            transform: translateY(-10%) rotateZ(45deg);
ok

![PaleHelplessGorilla-size_restricted](https://user-images.githubusercontent.com/61631103/133506197-dbb3a9b2-8b38-4ea0-bd92-735355d6c6c7.gif)

2021-09-15 20:51 UTC, mary-poppins commented
You can preview a4ca120 at https://pr43355-a4ca120.ngbuilds.io/.

2021-09-15 21:10 UTC, dario-piotrowicz commented
> The styles look good  Thx, @dario-piotrowicz!
> 
> The last remaining issue is updating the CSS payload size limits. I.e. update the `styles` entry for both [aio](https://github.com/angular/angular/blob/63e056b7cd2397eb67f168d83ace011cc22664af/goldens/size-tracking/aio-payloads.json#L8) and [aio-local](https://github.com/angular/angular/blob/63e056b7cd2397eb67f168d83ace011cc22664af/goldens/size-tracking/aio-payloads.json#L20) to reflect the new (increased ) size of the `styles.css` file (currently **69724**B (from **69237**B on master)).
> 
> I have also left some comments on rules that I believe could be removed (and potentially reduce the size impact of this PR).

Thanks a bunch for the comments, I should have addressed all of them! :slightly_smiling_face: 

About the payload size.... I am sorry for the increase, and... ever more sorry for my ignorance.... could you tell me how/where I can check the size? :sweat: 

Regarding the CSS size I will try to get it down if I can, I actually already found that we have a bunch of css that doesn't seem to do anything, so I went ahead and removed it ( https://github.com/angular/angular/pull/43355/commits/381434218f230ec046b1e6697bbbce5b6845d507 ), please have a look to see if I got it right (it seems so to me :sweat_smile: )

2021-09-15 21:14 UTC, dario-piotrowicz commented
More css removed! :slightly_smiling_face: https://github.com/angular/angular/pull/43355/commits/9cbac890c88cc2c8ebeaad0c87338261756ca503

2021-09-15 21:30 UTC, mary-poppins commented
You can preview 689a54f at https://pr43355-689a54f.ngbuilds.io/.

2021-09-16 11:56 UTC, gkalpak commented on aio/src/styles/2-modules/contributor/_contributor.scss
> +            transform: translateY(-10%) rotateZ(45deg);
🤗

2021-09-16 13:09 UTC, gkalpak approved these changes
LGTM :shipit: Thx, @dario-piotrowicz 🚀 

> could you tell me how/where I can check the size? 😓

The size we check against is the `styles.<hash>.css` file generated in the dist output. If you want to check the size locally, you can just build the AIO app and check `aio/dist/`. You can also check the computed sizes on CI: it's the `yarn --cwd aio payload-size` step of the `test_aio` and `test_aio_local` jobs ([example][1]).

That said, it seems you have brought the size down (this PR now slightly decreases the `styles.css` size by a few bytes :tada:), so you don't have to deal with payload size limits any more :wink:

[1]: https://circleci.com/gh/angular/angular/1049681

2021-09-16 13:46 UTC, gkalpak commented
BTW, the CI failures in `test_docs_examples` are unrelated to this PR (and will be fixed by #43475).

2021-09-16 18:22 UTC, dario-piotrowicz commented
seems like the other PR has been merged, could we put the `action: merge` label back here? :smiley:

2021-09-16 18:25 UTC, dario-piotrowicz commented
Just rebased it that was necessary :slightly_smiling_face::+1:

2021-09-16 18:37 UTC, mary-poppins commented
You can preview dfe6b87 at https://pr43355-dfe6b87.ngbuilds.io/.

2021-09-20 16:02 UTC, closed without merging