Feat/expose more events from service worker
angular/angular pull request #43535
Opened 2021-09-22 10:03 UTC by spike-rabbit

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #39840 

## What is the new behavior?

Exposing a versionUpdate Event and adding a meaningful return value for `SwUpdate#activateUpdate` and ´SwUpdate#checkForUpdate´. Basically implementing what is suggested [here](https://github.com/angular/angular/issues/39840#issuecomment-901157285):

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

The return type of `SwUpdate#activateUpdate` and `SwUpdate#checkForUpdate` changed to `Promise<boolean>`. Variable declaration adjustments might be necessary.

## Other information
@gkalpak as promised here is the PR. I did not update the docs completly yet. I guess waiting for the other changes to be ready makes sense.

2021-09-23 15:21 UTC, gkalpak requested changes
Awesome work :100: Thx so much, @spike-rabbit :heart:
I've left some comments, but this is looking great already.

2021-09-23 15:21 UTC, gkalpak commented on packages/service-worker/src/low_level.ts
> +  result: boolean;
It is not guaranteed that there will be a `result`, right?
I think we should either ensure that there is already a `result` property (setting it to `null` on error) and/or use a more complex type - something like:

```ts
type OperationCompletedEvent = {
  type: 'OPERATION_COMPLETED';
  nonce: number;
  result: boolean;
} | {
  type: 'OPERATION_COMPLETED';
  nonce: number;
  result?: undefined;
  error: string;
};
```

2021-09-23 15:21 UTC, gkalpak commented on packages/service-worker/src/low_level.ts
>    }
Is the `waitForStatus()` method needed any more? Could we remove it?

2021-09-24 07:42 UTC, spike-rabbit commented
thx a lot @gkalpak for taking care of this PR. I did the changes you requested.

Is it up to me to resolve the discussions or will you do this?

2021-09-24 08:29 UTC, gkalpak commented
Thx for making the changes, @spike-rabbit :tada:
I will take a look asap.

> Is it up to me to resolve the discussions or will you do this?
Either way is fine. (Personally, I prefer for the reviewer to resolve them, but many prefer the other way around.)

2021-09-24 08:58 UTC, mary-poppins commented
You can preview c82e8f0 at https://pr43535-c82e8f0.ngbuilds.io/.
You can preview f0f7a94 at https://pr43535-f0f7a94.ngbuilds.io/.
You can preview 0a5740b at https://pr43535-0a5740b.ngbuilds.io/.
You can preview eb652dc at https://pr43535-eb652dc.ngbuilds.io/.

2021-09-24 09:53 UTC, gkalpak requested changes

2021-09-24 09:53 UTC, gkalpak commented on packages/service-worker/src/update.ts
> +   * @deprecated use {@link versionUpdates} instead.
```suggestion
   * @deprecated Use {@link versionUpdates} instead.
```

Maybe also mention that they can filter to only keep `VersionReadyEvent` (or even show the code to do it).

2021-09-24 09:53 UTC, gkalpak commented on packages/service-worker/src/update.ts
> +  checkForUpdate(): Promise<boolean> {
We need to add some docs and explain how the return value should be interpreted.

2021-09-24 09:53 UTC, gkalpak commented on packages/service-worker/src/update.ts
> +  activateUpdate(): Promise<boolean> {
We need to add some docs and explain how the return value should be interpreted.

2021-09-24 09:53 UTC, gkalpak commented on packages/service-worker/src/low_level.ts
> + * @deprecated
We should explain why it is deprecated/what to use instead. I.e. that it only emitted by the deprecated `SwUpdate#available` and they could instead listen for `VersionReadyEvent`s from `SwUpdate#versionUpdates`.

2021-09-24 09:53 UTC, gkalpak commented on packages/service-worker/src/low_level.ts
> + * @deprecated
We should explain why it is deprecated/what to use instead. I.e. that it only emitted by the deprecated `SwUpdate#activated` and they could instead use the return value of `SwUpdate#activateUpdate()`.

2021-09-24 09:53 UTC, gkalpak commented on packages/service-worker/src/low_level.ts
> + * An event emitted when a new version of the app has been detected but downloaded yet.
```suggestion
 * An event emitted when a new version of the app has been detected but not downloaded yet.
```

Or (to make it clear that they don't need to do anything to start the download) maybe even:

```suggestion
 * An event emitted when the service worker has detected a new version of the app on the server and is about to start downloading it.
```

2021-09-24 09:53 UTC, gkalpak commented on packages/service-worker/src/low_level.ts
> + * An event emitted when the installation of a new version failed.
Maybe we should add that developers can use the error to send it to their app monitoring/error tracking provider (since that's probably the only useful thing they can do - on production at least).

2021-09-24 12:16 UTC, spike-rabbit commented
@gkalpak changes are done as requested.
Do you know why the aio pipelines are failing?
Error:
```
 yarn docs-only
$ dgeni ./tools/transforms/angular.io-package
info:    running processor: readFilesProcessor
info:    running processor: extractJSDocCommentsProcessor
info:    running processor: collectExamples
info:    running processor: readTypeScriptModules
info:    running processor: linkInheritedDocs
info:    running processor: processPseudoClasses
info:    running processor: parseTagsProcessor
info:    running processor: extractTagsProcessor
error:   Error running processor "extractTagsProcessor":
Cannot read property 'forEach' of undefined
error:   Failed to process the docs
error Command failed with exit code 1.

```

2021-09-24 13:56 UTC, gkalpak commented
> Do you know why the aio pipelines are failing?

It is probably because of [this][1] `@example` annoatation. We use `@example` differently.
For now just use tripple-backticks to wrap the example code to make CI happy.

[1]: https://github.com/angular/angular/pull/43535/commits/f26d2323a5b1b09f01ab17984c58e28e3e11a061#diff-dfafc6b8e9532859dce9c5a05329ed1f56166bcfcf0bc889201d571598e2b736R44

2021-09-27 05:44 UTC, mary-poppins commented
You can preview 3e986c4 at https://pr43535-3e986c4.ngbuilds.io/.

2021-09-27 06:07 UTC, spike-rabbit commented on packages/service-worker/src/low_level.ts
> + * Use the `VersionEvent` instead which is emitted by {@link SwUpdate#versionUpdates}.
It seems like `{@link VersionEvent}` does not work here. @gkalpak Any Idea how to fix this?

2021-09-27 06:08 UTC, spike-rabbit commented
As the pipeline is fixed, I guess this is ready for the next review

2021-09-29 09:31 UTC, gkalpak requested changes
Thx for making the changes again, @spike-rabbit :+1:
A couple more docs suggestions and this should be good to go 🚀

One thing we need to consider is whether this is a breaking change due to the `checkForUpdate()` and `activateUpdate()` signature changes. (and if so, how to handle that - for example, it might need to go into the next major release).

2021-09-29 09:31 UTC, gkalpak commented on packages/service-worker/src/update.ts
> +   * ```
Eventually, this should be extracted from an example app (see the [docs style guide][1] for more info).

This is not super straight-forward (esp. if you haven't done it before), so happy to take care of it myself (unless you're feeling adventurous :wink:).

[1]: https://angular.io/guide/docs-style-guide#hard-coded-snippets

2021-09-29 09:31 UTC, gkalpak commented on packages/service-worker/src/update.ts
> +   * ).subscribe(...)
We should not use `this.versionUpdates` here :grin:
Also, we don't need to show `.subscribe()`, since `SwUpdate#available` has to be subscribed to as wll (i.e. it is not a hot observable). Something like the following would be more accurate imo:

```suggestion
   * import {filter, map} from 'rxjs/operators';
   * // ...
   * const updatesAvailable = swUpdate.versionUpdates.pipe(
   *   filter((evt): evt is VersionReadyEvent => evt.type === 'VERSION_READY'),
   *   map(evt => ({
   *     type: 'UPDATE_AVAILABLE',
   *     current: evt.currentVersion,
   *     available: evt.latestVersion,
   *   })));
```

2021-09-29 09:31 UTC, gkalpak commented on packages/service-worker/src/update.ts
> +   * Activates an update that is ready for activation.
Let's make it clear it only affects the calling client (not other clients). How about:
```suggestion
   * Updates the current client (i.e. browser tab) to the latest version that is ready for activation.
```

2021-09-29 09:31 UTC, gkalpak commented on packages/service-worker/src/update.ts
> +   *  - resolves to `false` if no updated was ready for activation
```suggestion
   *  - resolves to `false` if no update was available (for example, the client was already on the latest version).
```

2021-09-29 09:31 UTC, gkalpak commented on packages/service-worker/src/update.ts
> +   * Checks for an update and waits until the new version is ready for activation.
Let's be more explicit that this includes downloading the necessary assets from the server:

```suggestion
   * Checks for an update and waits until the new version is downloaded from the server and ready
   * for activation.
```

2021-09-29 13:48 UTC, spike-rabbit commented on packages/service-worker/src/update.ts
> +   * ```
Although I am a little curios how this would done, I guess I can leave this one open for you ;)

2021-09-29 14:14 UTC, mary-poppins commented
You can preview c47a3b4 at https://pr43535-c47a3b4.ngbuilds.io/.

2021-09-29 14:39 UTC, mary-poppins commented
You can preview 8271e70 at https://pr43535-8271e70.ngbuilds.io/.

2021-09-29 14:52 UTC, spike-rabbit commented
All the requested changes are done, unless commented otherwise, and also rebased on the master due to the merge conflict.

I already included a breaking change notice in the commit message.  But I would expect that this is no issue for most applications. Why should one store the result in an explicit declared variable. Even if they did so, it should be easy to fix, only once per application. Or am I too naive?

Is there any chance that this will be part v13?

2021-09-29 15:11 UTC, gkalpak commented
Thx again, @spike-rabbit :heart:
I'll take a look asap.

Yes, this is a minor breaking change, but it is theoretically possible to break an app (mostly due to the typings changes, not the actual runtime behavior). I think it can make it into v13, but let me confirm with the team and get back to you (because we are nearing the feature-freeze date for v13).

BTW, according to our [deprecation practices][1], we need to mention the deprecated APIs in the [Deprecations][2] guide and in the Changelog (which is auto-generated from the commit messages). So, it would be great if you could update the `Deprecations` guide and the commit message to include a `DEPRECATED` section for the deprecated APIs. (The `DEPRECATED` section of the commit message should have the exact same format as the [BREAKING CHANGE][3] section.) 

[1]: https://angular.io/guide/releases#deprecation-practices
[2]: https://angular.io/guide/deprecations
[3]: https://github.com/angular/angular/blob/4555d8a31625564d457b93113ce8c71a24bdd472/CONTRIBUTING.md#commit-message-footer

2021-09-30 07:24 UTC, mary-poppins commented
You can preview b90d695 at https://pr43535-b90d695.ngbuilds.io/.

2021-09-30 07:50 UTC, mary-poppins commented
You can preview 0e99749 at https://pr43535-0e99749.ngbuilds.io/.

2021-10-01 13:10 UTC, gkalpak requested changes
I have confirmed that this can be part of v13 (as long as we can get it in before Wednesday, Oct 6). I have left some final (minor) docs-related comments and then this would be ready for a public-API review.

In the interest of moving this forward quickly:
- I have captured some additional docs work that does not have to happen as part of this PR in #43665. (This is non-breaking and can be done after the v13.0.0 feature-freeze or release.)
- I will go ahead and address my final comments myself (to get this ready for public-API review asap).

##
Thank you again for the amazing work and perseverance, @spike-rabbit 🥇

2021-10-01 13:10 UTC, gkalpak commented on aio/content/guide/deprecations.md
> +
```suggestion
{@a service-worker}

### @angular/service-worker

| API                                                           | Replacement                                                                            | Deprecation announced    | Notes
|:---                                                           |:---                                                                                    |:---                      |:---
| [`SwUpdate#activated`](api/service-worker/SwUpdate#activated) | [`SwUpdate#activateUpdate()` return value](api/service-worker/SwUpdate#activateUpdate) | v13                      | The return value of `SwUpdate#activateUpdate()` indicates whether an update was successfully activated. |
| [`SwUpdate#available`](api/service-worker/SwUpdate#available) | [`SwUpdate#versionUpdates`](api/service-worker/SwUpdate#versionUpdates)                | v13                      | The behavior of `SwUpdate#available` can be rebuilt by filtering for `VersionReadyEvent` events on [`SwUpdate#versionUpdates`](api/service-worker/SwUpdate#versionUpdates) |

{@a upgrade}

```

2021-10-01 13:11 UTC, gkalpak commented on packages/service-worker/src/update.ts
> +   * ```
This is now tracked in #43665.

2021-10-01 15:36 UTC, spike-rabbit commented
@gkalpak thanks a lot for your time and making it possible for me to bring a feature into Angular 🚀. It would be really awsome if I can try this out already with v13.

Just to clarify as you opened a new PR: Will you take care of it from now on and I am done here?

2021-10-01 15:45 UTC, gkalpak commented
It turns out that I am not authorized to push to your branch, @spike-rabbit. So I created a new PR (keeping you as the author of the commits): #43668
I have slightly reworded the commit messages and addressed the comments in my last review. Can you please take a look and make sure everything looks good to you, @spike-rabbit?

@IgorMinar, please review #43668 for public API instead of this PR.

2021-10-05 17:36 UTC, dylhunn commented
@spike-rabbit @gkalpak Just a heads up that the v13 freeze is in about 24 hours -- you will need to rebase on master, and get all the needed approvals to make v13.

2021-10-05 17:51 UTC, gkalpak commented
Closing in favor of #43668. Thx again, @spike-rabbit, for the amazing work 💪

2021-10-05 17:51 UTC, closed without merging