Nullish coalescing symbol
angular/angular pull request #43572
Opened 2021-09-24 18:10 UTC by dgp1130

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-09-24 18:11 UTC, dgp1130 commented
^ @alxhub @atscott, not sure what the right function to fix this is. Need some way of converting an expression node to its type.

2021-09-24 23:30 UTC, dgp1130 reviewed
After some discussion with @alxhub, it seems that `getSymbolForNode()` is the right function here, it's just that it shouldn't special-case `Call` expressions. Updated the PR to fix this behavior.

2021-09-24 23:30 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/src/template_symbol_builder.ts
> +      withSpan = expression.sourceSpan;
This is the main bug fix. We use the whole expression rather than just the receiver's name.

2021-09-24 23:30 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/test/type_checker__get_symbol_of_template_node_spec.ts
> -            .toEqual('(v: any) => string');
Not sure how important this functionality is, no other existing tests were broken by the change.

2021-09-25 02:27 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/src/template_symbol_builder.ts
> +      withSpan = expression.sourceSpan;
The initial assignment is to `expression.sourceSpan` so this `else if` case should just be removed completely _if_ this is what we want to do in the end. That said, I'm quite suspicious that this was done without reason. It was added very specifically in https://github.com/angular/angular/pull/38844 and it's possible that there just wasn't the Language Service side of things to test yet. I'll take a look at this more closely tomorrow/Monday, but it's likely related to how things work in the language service with respect to "go to definition"/"find references", etc.

2021-09-27 18:10 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/nullish_coalescing_not_nullable/nullish_coalescing_not_nullable_spec.ts
> -    });
Did you mean to delete this test?

2021-09-27 18:22 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/nullish_coalescing_not_nullable/nullish_coalescing_not_nullable_spec.ts
> -    });
I didn't mean to delete it, just restructure it. Previously it only verify if there was no symbol for the left side, so I changed it to test if there an expression on the left side, which I felt was still in line with the original intent of the test.

In retrospect, I don't think I fully understand what "symbol" means to the compiler. Is there a symbol for `func() ?? 'foo'` but *not* a symbol for `(123 | doesNotExist) ?? 'invalid date'`? I would expect neither cases to have symbols, but based on my investigation here I think that understanding is incorrect. If these are distinct cases, then you're right that we probably should keep the old test, but if they are the same then the new test should be enough on its own.

2021-09-27 19:10 UTC, atscott requested changes

2021-09-27 19:12 UTC, atscott commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/nullish_coalescing_not_nullable/nullish_coalescing_not_nullable_spec.ts
> -    });
Ah, I understand. Your new test should cover this case I think.

2021-09-28 22:21 UTC, dgp1130 commented on packages/compiler-cli/src/ngtsc/typecheck/src/template_symbol_builder.ts
> +      withSpan = expression.sourceSpan;
Thanks for the deep analysis and extra test case, really helpful! Updated to remove these hacks and just use the return type of the expression without reaching into the receiver. Also added the test case you suggested.

2021-10-01 16:52 UTC, atscott approved these changes
👌

2021-10-04 23:34 UTC, dylhunn commented
This PR doesn't merge cleanly into 12.2.x. Mind rebasing, or targeting major?

2021-10-05 00:09 UTC, dgp1130 commented
@dylhunn, sorry about that. It looks like the previous PR (#38844) which introduced some of this code was not merged to `patch`, so it causes conflicts here. I could manually back port this PR, but extended templates diagnostics won't be shipped to `patch` anyways, so I'm not sure it's worth the effort. I was intending to keep `patch` synchronized to reduce differences with `major`, but since there will be differences anyways due to #38844 and `patch` will be falling into LTS soon anyways, I'm not too concerned about it.

I think we can just merge this to `major` and go with that.

2021-10-05 00:32 UTC, dylhunn commented
This PR was merged into the repository by commit 263feba5c2d56e8433068718d1fdcbc3b2ae144c.

2021-10-05 00:33 UTC, closed without merging