refactor(router): remove support for `loadChildren` string syntax
angular/angular pull request #43591
Opened 2021-09-25 19:58 UTC by JoostK

This commit removes the ability to configure lazy routes using a string
for `loadChildren`, together with the supporting classes to load an
`NgModuleFactory` at runtime.

BREAKING CHANGE:

It is no longer possible to use `Route.loadChildren` using a string
value. The following supporting classes were removed from
`@angular/core`:

- `NgModuleFactoryLoader`
- `SystemJsNgModuleFactoryLoader`

The `@angular/router` package no longer exports these symbols:

- `SpyNgModuleFactoryLoader`
- `DeprecatedLoadChildren`

The signature of the `setupTestingRouter` function from
`@angular/core/testing` has been changed to drop its `NgModuleFactoryLoader`
parameter, as an argument for that parameter can no longer be created.

---

This PR is an alternative to #43575 and removes `NgModuleFactoryLoader` and the `string` type for `Route.loadChildren` altogether.

2021-09-26 14:18 UTC, JoostK commented on packages/compiler-cli/test/ngc_spec.ts
> +          export function foo(): any {
These tests are retained as special handling in the VE compiler was not removed, as it's not currently worth the risk/effort to change VE's behavior.

2021-09-26 14:18 UTC, JoostK commented on goldens/public-api/router/testing/testing.md
> +export function setupTestingRouter(urlSerializer: UrlSerializer, contexts: ChildrenOutletContexts, location: Location_2, compiler: Compiler, injector: Injector, routes: Route[][], opts?: ExtraOptions
This is technically a breaking change (and mentioned in the commit message) to a signature that was not marked as deprecated, but I don't see a different way of achieving this. Since this is test-only code it is unlikely to be called from a library, so I'd consider this an acceptable break.

@atscott This particular change is not accounted for in the fixup commit that removes `NgModuleFactoryLoader`. Any g3 usages need to be cleaned up separately (or we'd have to extend the patch to undo this change and create an intermediate `Injector` to provide the given `NgModuleFactoryLoader`)

2021-09-26 14:18 UTC, JoostK commented on packages/compiler-cli/integrationtest/ngtools_src/feature2/feature2.module.ts
> +    {path: 'd', loadChildren: () => import('./default.module')},
@alan-agius4 Do you know if using default imports like this is actually supported in the CLI? I believe only limited syntax is supported and I am unsure if this is accepted.

2021-09-26 16:41 UTC, alan-agius4 commented on packages/compiler-cli/integrationtest/ngtools_src/feature2/feature2.module.ts
> +    {path: 'd', loadChildren: () => import('./default.module')},
I highly doubt, but I can check tomorrow.

2021-09-26 17:13 UTC, dario-piotrowicz commented on aio/content/guide/deprecations.md
> +Find more information about the replacement [in the `LoadChildrenCallback` documentation](api/router/LoadChildrenCallback).
:thinking: 
```suggestion
Find more information about the replacement in the [`LoadChildrenCallback` documentation](api/router/LoadChildrenCallback).
```

2021-09-26 17:13 UTC, dario-piotrowicz commented on packages/core/src/linker/ng_module_factory_loader.ts
> +import {Injectable} from '../di';
are you using this import? :thinking:

2021-09-26 17:16 UTC, alan-agius4 commented on packages/compiler-cli/integrationtest/ngtools_src/feature2/feature2.module.ts
> +    {path: 'd', loadChildren: () => import('./default.module')},
Note: string based lazy loading isn’t even possible in version 12 with Angular CLI. Therefore, I think this is not a problem.

2021-09-26 17:18 UTC, JoostK commented on packages/compiler-cli/integrationtest/ngtools_src/feature2/feature2.module.ts
> +    {path: 'd', loadChildren: () => import('./default.module')},
> Note: string based lazy loading isn’t even possible in version 12 with Angular CLI. Therefore, I think this is not a problem.

That's why this commit updates the examples to move away from that syntax. But it used to be possible to use default imports and I'm not sure if that's supported with dynamic import syntax.

2021-09-26 17:22 UTC, alan-agius4 commented on packages/compiler-cli/integrationtest/ngtools_src/feature2/feature2.module.ts
> +    {path: 'd', loadChildren: () => import('./default.module')},
I think for the default use case the syntax would be

```
loadChildren: () => import('../feature/feature.module').then(mod => mod.default)
```

2021-09-26 17:25 UTC, JoostK commented on packages/core/src/linker/ng_module_factory_loader.ts
> +import {Injectable} from '../di';
I used to but then changed some stuff around; good catch, I'll remove it.

2021-09-26 17:25 UTC, JoostK commented on aio/content/guide/deprecations.md
> +Find more information about the replacement [in the `LoadChildrenCallback` documentation](api/router/LoadChildrenCallback).
I like to extend links with a bit of context like this, do you have a strong preference towards your suggestion here?

2021-09-26 17:26 UTC, JoostK commented on packages/compiler-cli/integrationtest/ngtools_src/feature2/feature2.module.ts
> +    {path: 'd', loadChildren: () => import('./default.module')},
Thanks; I'll try.

2021-09-26 17:42 UTC, JoostK commented on packages/compiler-cli/integrationtest/ngtools_src/feature2/feature2.module.ts
> +    {path: 'd', loadChildren: () => import('./default.module')},
You are correct, this needs `.then(mod => mod.default)` 👍

2021-09-26 19:14 UTC, dario-piotrowicz commented on aio/content/guide/deprecations.md
> +Find more information about the replacement [in the `LoadChildrenCallback` documentation](api/router/LoadChildrenCallback).
mh.... I see what you mean, I think this caught my attention because it felt inconsistent with what we have in the docs, and by running a regex search it does sort of look like that:

![Screenshot at 2021-09-26 20-07-35](https://user-images.githubusercontent.com/61631103/134821068-d1c62b46-9279-49f0-a853-eafc44b0f150.png)

vs

![Screenshot at 2021-09-26 20-08-18](https://user-images.githubusercontent.com/61631103/134821071-cfecb65a-fb6f-40a6-8e5f-b69864eed3be.png)

so from a consistency point of view I would definitely put the "in the" bit outside the link

of course I leave the decision up to you :slightly_smiling_face:

2021-09-29 00:49 UTC, IgorMinar requested changes

2021-09-29 00:49 UTC, IgorMinar commented on goldens/public-api/core/core.md
> -export abstract class NgModuleFactoryLoader {
we cannot remove this class because it's heavily used in google3 - for this reason https://github.com/angular/angular/pull/43575 seems like much more viable path towards incrementally making this change.

2021-09-29 17:20 UTC, atscott commented
@googlebot I consent

2021-09-29 19:42 UTC, atscott approved these changes
LGTM

[presubmit (with patch applied)](https://fusion2.corp.google.com/presubmit/tap/399717242/OCL:399717242:BASE:399745023:1632942904042:1feaaf08/targets)
[Patch CL](https://critique-ng.corp.google.com/cl/399714087) (which still exports `SpyNgModuleFactoryLoader` and provides it by default in `RouterTestingModule`)

2021-09-29 19:43 UTC, atscott commented on goldens/public-api/core/core.md
> -export abstract class NgModuleFactoryLoader {
Resolving since we are planning to include this in the g3 patch.

2021-09-29 19:53 UTC, IgorMinar commented on goldens/public-api/core/core.md
> -export abstract class NgModuleFactoryLoader {
I see. sgtm

2021-09-29 19:55 UTC, IgorMinar approved these changes
LGTM now that we have the g3 patch! Thanks!

Reviewed-for: public-api, fw-testing, fw-playground, docs-packaging-and-releasing

2021-09-29 21:24 UTC, alxhub approved these changes
Reviewed-for: public-api

2021-09-29 21:32 UTC, atscott approved these changes
reviewed-for: public-api
reviewed-for: size-tracking

2021-09-29 21:41 UTC, jessicajaniuk approved these changes
LGTM :cookie:
reviewed-for: public-api

2021-09-29 21:42 UTC, alxhub approved these changes

2021-09-29 21:44 UTC, alxhub commented
Pull Approve is confused...

2021-09-29 21:45 UTC, closed without merging