feat(language-service): provide snippets for attribute
angular/angular pull request #43590
Opened 2021-09-25 14:26 UTC by ivanwonder

Support snippet completions for dom attribute whose value
is empty. For Example `<div (my¦) />`, the `insertText`
will return `(myOutput)="$0"`.

Fixes https://github.com/angular/vscode-ng-language-service/issues/521

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-09-27 20:19 UTC, atscott requested changes

2021-09-27 20:19 UTC, atscott commented on packages/language-service/ivy/completions.ts
> +            if (nodeEnd?.after[1] !== '=' && replacementSpan) {
I think all of these checks for there not being an `=` after the key are essentially checking to ensure that there is no value/valueSpan/handler/handlerSpan. With that being the case, could you simply update the replacement span to just encompass the whole `sourceSpan` rather than shifting `start` and `length`?

2021-09-28 11:56 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +            if (nodeEnd?.after[1] !== '=' && replacementSpan) {
There is an edge case for the microsyntax template expression.
If the value of `ngIf` is empty, the `SourceSpan` only includes the `ngIf`.
https://github.com/angular/angular/blob/38daf7a36ed553daafff40a2454c302851bd6a1f/packages/compiler/test/render3/r3_ast_spans_spec.ts#L231-L233
https://github.com/angular/angular/blob/38daf7a36ed553daafff40a2454c302851bd6a1f/packages/compiler/test/render3/r3_ast_spans_spec.ts#L325-L330
https://github.com/angular/angular/blob/38daf7a36ed553daafff40a2454c302851bd6a1f/packages/compiler/test/render3/r3_ast_spans_spec.ts#L345-L349
I think we can add a optional property for the `TextAttribute` to include the whole span.

2021-09-28 11:57 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +    let insertSnippet: true|undefined;
consistent with [tsserver](https://sourcegraph.com/github.com/microsoft/TypeScript/-/blob/lib/tsserverlibrary.d.ts?L6289:9)

2021-09-28 11:57 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +    if (options?.includeCompletionsWithSnippetText && options.includeCompletionsWithInsertText) {
I think it's disabled by default. Only the IDE extension enable it by `includeCompletionsWithSnippetText `

2021-09-28 16:29 UTC, atscott commented on packages/language-service/ivy/completions.ts
> +    let insertSnippet: true|undefined;
👍

2021-09-28 16:29 UTC, atscott commented on packages/language-service/ivy/completions.ts
> +    if (options?.includeCompletionsWithSnippetText && options.includeCompletionsWithInsertText) {
You're right - it's disabled by default. I came back to this comment and confused myself. I think the change is still good though: `options?.includeCompletionsWithSnippetText === true`

2021-09-28 16:29 UTC, atscott commented on packages/language-service/ivy/completions.ts
> +            if (nodeEnd?.after[1] !== '=' && replacementSpan) {
Hmm, interesting. Does this matter though? We don't _have_ to include the preceding `*` in the snippet, do we? Based on my understanding, this would still work.

2021-09-30 04:19 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +        }
This is a copy from here
https://github.com/angular/angular/blob/a07cb097e9124738880f7978658a2972d25b892e/packages/language-service/ivy/template_target.ts#L377-L394

2021-09-30 05:22 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +            if (nodeEnd?.after[1] !== '=' && replacementSpan) {
Now I changed the implementation of the code to use the `SourceSpan ` to complete the snippet. It's no need to care about whether it's triggered by `()` or `on-`, or it includes the `=`(`(click)`, `(click)=`, `(click)=""`). The results will be filtered by vscode.
But for the structural directive attribute, for example, `*ngFor`,`*ngFor=""`, `*ngFor="let a of b"`, the `SourceSpan` is always the `ngFor`, so I need to know if it includes the `=`

2021-09-30 05:48 UTC, ivanwonder commented on packages/language-service/ivy/test/completions_spec.ts
> +    });
I think this is expected behavior.

2021-09-30 19:53 UTC, atscott commented on packages/language-service/ivy/attribute_completions.ts
> +        });
Please revert these changes. `on-`, `bind-`, and `bindon-` should not be included in the completions. They aren't exactly deprecated, but I don't think we actively want to promote them as options.

2021-09-30 19:53 UTC, atscott commented on packages/language-service/ivy/completions.ts
> +        options.includeCompletionsWithInsertText) {
```suggestion
    if (options?.includeCompletionsWithSnippetText === true) {
```

2021-09-30 19:53 UTC, atscott commented on packages/language-service/ivy/completions.ts
> +        }
Let's extract this code to a helper `isBoundEventWithSyntheticHandler`. We should keep this special handling logic in one place rather than duplicating it around.

2021-09-30 21:21 UTC, atscott requested changes
Could you also send out the PR in the vscode-ng-language-service so I can test it end-to-end?

Specifically, I'm not sure how this works with when `clientCapabilities.textDocument?.completion?.completionItem?.snippetSupport !== true`. We've changed every completion item to be a snippet without accounting for the fact that not all clients will support snippets.

2021-09-30 21:21 UTC, atscott commented on packages/language-service/ivy/completions.ts
> +    let includeBindingSugar = false;
Is this variable necessary? It looks like you could just use `insertSnippet` instead.

2021-09-30 21:21 UTC, atscott commented on packages/language-service/ivy/test/completions_spec.ts
> +    });
Isn't the behavior the same as the one "should not be included in the complete for an attribute with a value"? I think your implementation intends for that to be the case so should we just assert that behavior?

2021-10-01 05:29 UTC, ivanwonder commented on packages/language-service/ivy/test/completions_spec.ts
> +    });
same as the one `[myIn¦]="" -> [myInput]="¦"`, it works for event and attribute. But for the structural directive, `*ngF¦="" -> *ngFor¦=""`, snippet works only when no `=` after the structural directive.
I think It's safe to remove.

2021-10-01 05:29 UTC, ivanwonder commented on packages/language-service/ivy/attribute_completions.ts
> +        });
If remove it from the completion list. there will be no completion for `bind-myInput¦`.
If it will be deprecated, maybe it's safe to remove them.

2021-10-01 05:30 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +             this.node.value.ast instanceof EmptyExpr)) {
I think the synthetic node is only for `BoundEvent`. And the helper `hasSyntheticValueOrHandler` only works here, no need to extract this code.

2021-10-01 05:30 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +             this.node.value.ast instanceof EmptyExpr)) {
Done

2021-10-01 05:31 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +        options.includeCompletionsWithInsertText) {
Sorry, I don't know.
https://sourcegraph.com/github.com/microsoft/vscode-languageserver-node/-/blob/types/src/main.ts?L2143
What I know it's the `insertText` will be transformed to `textEdit` in `@angular/vscode-ng-language-service`.

2021-10-01 05:31 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +    let includeBindingSugar = false;
It's necessary for `BoundAttribute` and `BoundEvent`, because the  `replacementSpan` includes the `(`, `[`.

2021-10-01 05:32 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +        }
Done

2021-10-01 09:42 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +    if (options?.includeCompletionsWithSnippetText && options.includeCompletionsWithInsertText) {
I think the logic is simple now.

> Also, if this can be extracted to a helper function, you can add an early return for `this.node.keySpan === undefined` and remove the separate checks from each `if`

remove the unnecessary `if`.

2021-10-01 15:39 UTC, atscott commented on packages/language-service/ivy/attribute_completions.ts
> +        });
Hmm... @alxhub How do you feel about not having autocomplete for `bind-` and `bindon-` syntax? They're so rarely used, I don't know if it would be much of an issue if we just don't support autocomplete for them.

2021-10-01 16:11 UTC, atscott commented on packages/language-service/ivy/test/completions_spec.ts
> +    });
Oh, right. I forgot we changed the implementation to check for the value/handler rather than the `=`. Yea, this seems fine. Could you actually enable the test and just assert what currently happens with a comment about what we would _like_ to do if the `sourceSpan`/`valueSpan` made more sense?

2021-10-01 16:11 UTC, atscott commented on packages/language-service/ivy/completions.ts
> +          }
Could you add a quick comment about why we have to special case this? i.e., the `sourceSpan` only includes `ngFor` and the `valueSpan` is always empty even if there is something there because we split this up into the desugared AST, `ngFor ngForOf=""`

2021-10-01 17:05 UTC, atscott commented on packages/language-service/ivy/attribute_completions.ts
> +        });
Yea, let's remove these. Feature freeze for v13 is Wednesday so we'll miss that and these will be deprecated in v14. I created #43669 for tracking this.

2021-10-02 02:55 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
>            (this.node instanceof TmplAstElement || this.node instanceof TmplAstTextAttribute);
Done, moved into `addAttributeCompletionEntries`.

2021-10-02 03:00 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +          }
Done

2021-10-02 03:00 UTC, ivanwonder commented on packages/language-service/ivy/completions.ts
> +    let includeBindingSugar = false;
Done

2021-10-02 03:01 UTC, ivanwonder commented on packages/language-service/ivy/attribute_completions.ts
> +        });
Done

2021-10-03 03:16 UTC, ivanwonder commented on packages/language-service/ivy/attribute_completions.ts
> +
Changed to `$1`, after the user input the value and presses `Tab`, the cursor will jump to the end of the snippet.

2021-10-03 03:21 UTC, ivanwonder commented on packages/language-service/ivy/test/completions_spec.ts
> +    });
Add a new test. If the `AttributeCompletionKind` is `DirectiveAttribute`, no need to insert the snippet, and because it does not also correspond to an input or output binding.
https://github.com/angular/angular/blob/c721135e370b34c840756bcfb22c8119b4c8c452/packages/language-service/ivy/attribute_completions.ts#L40-L43

2021-10-03 03:26 UTC, ivanwonder reviewed
Add some new tests for dom event and dom property.

2021-10-05 18:35 UTC, atscott approved these changes
LGTM! I just had one question about the reordered completion for input bindings as an attribute. I think you may have unintentionally moved it.

2021-10-05 18:35 UTC, atscott commented on packages/language-service/ivy/attribute_completions.ts
> +        });
Was this intentionally moved from below or is this an artifact of the reordering you had when adding the `bind-`/`bindon-`, etc? The comment on the sort text wasn't updated so it still indicates that it should be after the two way binding completion

2021-10-05 22:14 UTC, atscott commented on packages/language-service/ivy/attribute_completions.ts
> +        });
FYI - I pushed a fixup to revert this reordering so we can merge today before feature freeze tomorrow. We can always go back and change it with a refactor.

2021-10-06 00:29 UTC, closed without merging

2021-10-06 01:57 UTC, ivanwonder commented on packages/language-service/ivy/attribute_completions.ts
> +        });
Yes, the order of completion should be reverted.