feat(common): Support years greater than 9999
angular/angular pull request #43622
Opened 2021-09-28 03:46 UTC by pshahidi

Since According to ISO8601 The Year is minimum of 4 digits, to support years greater than 9999 (Similar to the change in input.js: https://github.com/LeeAdcock/angular.js/commit/e157d6fa69fecbee766e109c6b452f629bc00c8a)
Changed /^(\d{4}) to /^(\d{4,})

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Dates with year greater than 9999 throws error (Cannot format)

Issue Number: N/A

## What is the new behavior?
Years greater than 9999 will be accepted

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## Other information

2021-09-30 14:50 UTC, josephperrott commented
Manually confirmed CLA is signed for @pshahidi, looks like the email address associated to the commit is not the one on file due to github's email masking.

2021-09-30 14:56 UTC, petebacondarwin requested changes, later dismissed
Please could you add a unit test to `packages/common/test/i18n/format_date_spec.ts` that demonstrates this fix? Thanks.

2021-10-28 17:13 UTC, jessicajaniuk requested changes
This looks great and thanks for the contribution! If you could get that unit test added, we can get this landed.

2022-02-04 07:50 UTC, dylhunn commented
I went ahead and added the missing test.

2022-02-04 17:00 UTC, jessicajaniuk approved these changes

2022-02-04 17:03 UTC, jessicajaniuk commented
@dylhunn Looks like one file needs to be formatted and we need @dgp1130 to do a quick review.

2022-02-04 17:28 UTC, dylhunn commented
Awesome, formatting updated.

2022-02-04 18:24 UTC, dgp1130 approved these changes

2022-02-04 18:25 UTC, dylhunn approved these changes

2022-02-04 18:27 UTC, dylhunn commented
Started a presubmit: [link](http://test/OCL:426435447:BASE:426435480:1643999175818:7eec593b)

2022-02-04 18:43 UTC, closed without merging