refactor(docs-infra): remove eslint comments from examples
angular/angular pull request #43831
Opened 2021-10-13 21:17 UTC by dario-piotrowicz

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Issue

Issue Number: https://github.com/angular/angular/issues/43788

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2021-10-15 13:29 UTC, mary-poppins commented
You can preview 0e7ec3f at https://pr43831-0e7ec3f.ngbuilds.io/.
You can preview 5132024 at https://pr43831-5132024.ngbuilds.io/.
You can preview 8a92e31 at https://pr43831-8a92e31.ngbuilds.io/.

2021-10-15 13:33 UTC, gkalpak requested changes
Off to a great start, @dario-piotrowicz 👏

(The regexes were really good for what you were trying to do. I just think we should be doing something slightly different (mostly wrt surrounding whitespace), so I left some regex suggestions.)

2021-10-15 21:52 UTC, mary-poppins commented
You can preview c58f950 at https://pr43831-c58f950.ngbuilds.io/.

2021-10-16 16:45 UTC, mary-poppins commented
You can preview 781bf72 at https://pr43831-781bf72.ngbuilds.io/.

2021-10-16 18:24 UTC, mary-poppins commented
You can preview 9e55557 at https://pr43831-9e55557.ngbuilds.io/.

2021-10-16 20:25 UTC, dario-piotrowicz commented
@gkalpak... I just realized something :sweat: 

The division between js/ts and html is a bit flawed, as we can have the html in the component's decorator :cry: 
(js/ts can't really be present in html to the extent of having eslint comments there I believe)

so I may need to rethink that... or just apply the all regexes to all types js/ts/html (I don't see too much a problem with that, except having html comments with js/ts code with eslint comments and vice versa)....

( this could actually force me to restart from scratch :disappointed: )

I am so sorry for realizing this only now... :cry: 

What are your thoughts on it?

2021-10-17 11:27 UTC, gkalpak requested changes

2021-10-17 21:11 UTC, dario-piotrowicz commented
> > so I may need to rethink that... or just apply the all regexes to all types js/ts/html (I don't see too much a problem with that, except having html comments with js/ts code with eslint comments and vice versa)....
> 
> Aha, excellent point bulb I think it is fine to always apply all regexes (or just apply the HTML regexes on TS files). If we wanted to be even more sophisticated, we could look for an `@Component` annotation, but looking for a `template` property sounds a bit too much. (I won't stop you if you want to give it a shot, but it will complicate things quite a bit.)

Mh.... ok I think that then it is best to just get the thing working and at the end we may have a think about whether any more sophistications can be useful/worth the extra effort (and if that's the case take care of those in a follow up PR, so that we can at least unblock #43218 first)

(also yeah honestly applying the HTML regex to whole ts files does't really sound likely to cause issues :thinking:)

&NewLine;
&NewLine;
> 
> **Fun fact** (not pragmatically relevant, but...): HTML comments are [kind of respected](https://riptutorial.com/javascript/example/9722/using-html-comments-in-javascript--bad-practice-) in JavaScript (for legacy reasons).

ah! yeah I forgot about that one! :laughing: my god the sort of hoops/hacks people needed to use in the old days :sweat_smile:

2021-10-17 22:56 UTC, mary-poppins commented
You can preview 5b99979 at https://pr43831-5b99979.ngbuilds.io/.

2021-10-18 15:46 UTC, gkalpak requested changes

2021-10-26 14:34 UTC, gkalpak requested changes
Thx, @dario-piotrowicz :+1:

I can tell you put a lot of work into crafting the regexes 👏
I have left some comments. Basically (after ironing out some wrinkles in both our regexes) our regexes are very similar. The main different is that I usually opt for matching newlines and indentation on the same side (either leading or trailing), while yours seem to match indentation on one side and newline on the other.
I think both ways are valid (and will work correctly in well formatted code, which is our main target), so happy to go either way (leaving it up to you - decisions, decision 😱 😛).

2021-10-28 13:11 UTC, gkalpak requested changes
Getting there :wink: :tada:

2021-11-05 16:52 UTC, gkalpak commented on aio/tools/transforms/examples-package/services/removeEslintComments.js
> +  /\/\*\s*eslint-disable(?:-next-line)? [\s\S]*?\*\/ *(?:\n *)?/,
```suggestion
  /\/\*\s*eslint-disable(?:-next-line)?(?: [\s\S]*?)?\*\/ *(?:\n *)?/,
```

2021-11-05 16:52 UTC, gkalpak commented on aio/tools/transforms/examples-package/services/removeEslintComments.spec.js
> +    });
Good call regarding descriptions :+1:

2021-11-05 16:55 UTC, gkalpak commented on aio/tools/transforms/examples-package/services/removeEslintComments.spec.js
> +      const source = `/* eslint-disable @angular-eslint/no-input-rename,
SGTM :+1:

2021-11-05 16:59 UTC, gkalpak commented on aio/tools/transforms/examples-package/services/removeEslintComments.spec.js
> +  const partiallyEscapedString = str.replace(/(?:[.?*+\\|^$()[\]])|({(?!\d+\}))|(?<!\d)}/g, '\\$&');
Right! Lookbehinds should be fine here, since the code is run on Node.js (as you said).

2021-11-05 17:19 UTC, gkalpak requested changes
Sorry for the delayed review, @dario-piotrowicz 😇
(It's been a hectic week with the v13 release 😅)

I left one last comment regarding the regexes and then we need the test updates discussed in https://github.com/angular/angular/pull/43831#discussion_r738357016 and https://github.com/angular/angular/pull/43831#discussion_r738358336 and we're good to go 🚀

2021-11-05 21:04 UTC, dario-piotrowicz commented
> Sorry for the delayed review, @dario-piotrowicz innocent (It's been a hectic week with the v13 release sweat_smile)

Ah no problem, at all :slightly_smiling_face::+1: (I can imagine! yay Angular 13! :partying_face:)

2021-11-05 21:26 UTC, dario-piotrowicz commented on aio/tools/transforms/examples-package/services/removeEslintComments.spec.js
> +      const source = `/* eslint-disable @angular-eslint/no-input-rename,
Done, please have a loot to see if it's ok :slightly_smiling_face:

2021-11-05 21:36 UTC, mary-poppins commented
You can preview 25d7485 at https://pr43831-25d7485.ngbuilds.io/.

2021-11-05 21:42 UTC, dario-piotrowicz commented on aio/tools/transforms/examples-package/services/removeEslintComments.spec.js
> +    });
I've added the checks for multiple rules, I added `expect` for them in the already existing rules, I hope it's fine, not sure if you preferred having a dedicated test for them, please let me know :slightly_smiling_face: 

For the descriptions I'll add a dedicated test, I'll need to have a look to where we can have the descriptions (multiline, single line, etc...) and also see if html comments can also have descriptions (and in that case I'll also add an html test)

2021-11-05 21:47 UTC, mary-poppins commented
You can preview 2731c2c at https://pr43831-2731c2c.ngbuilds.io/.

2021-11-06 11:00 UTC, dario-piotrowicz commented on aio/tools/transforms/examples-package/services/removeEslintComments.spec.js
> +      expect(rmv(source)).toMatch(createRegexForMatching('\n {6}\n {6}<main>'));
@gkalpak the result here is not ideal... :man_shrugging: 

what do you think? is it worth tryng to fix it?

2021-11-06 11:01 UTC, dario-piotrowicz commented on aio/tools/transforms/examples-package/services/removeEslintComments.spec.js
> +    });
@gkalpak added tests regarding descriptions

I checked and they can be used both to js/ts and html comments so I added tests for both :slightly_smiling_face:

please have a look

2021-11-06 11:10 UTC, mary-poppins commented
You can preview a1a9fc1 at https://pr43831-a1a9fc1.ngbuilds.io/.

2021-11-08 13:11 UTC, gkalpak commented on aio/tools/transforms/examples-package/services/removeEslintComments.spec.js
> +        expect(rmv(source)).toMatch(
Yeah, not much relevant any more (since I don't think we should change the current format - not as part of this PR, at least 😅), but basically the problem you described is exactly what a [stripIntentation()][1] helper function helps with :smiley:

For example, the code you have in your last comment could be written as:

```js
    expect(fixture.nativeElement.innerHTML).toEqual(stripIndentation(`
      <div>Contenu: <div>avant<span>milieu</span>après</div><!--bindings={
        "ng-reflect-ng-if": "true"
      }-->!</div>
    `));

    fixture.componentRef.instance.visible = false;
    fixture.detectChanges();
```

[1]: https://github.com/gkalpak/aliases/blob/9fb7a691d8ff6a071bacfd1c05d67e47eb75e99a/lib/utils.js#L84-L92

2021-11-08 13:13 UTC, gkalpak approved these changes
LGTM :shipit:

Amazing work and perseverance, @dario-piotrowicz :100:

2021-11-08 20:21 UTC, dario-piotrowicz commented on aio/tools/transforms/examples-package/services/removeEslintComments.spec.js
> +        expect(rmv(source)).toMatch(
ahhhh!!!! ok sorry for being dumb! :sweat: 

All this time, for whatever reason I though we were talking about the `expect`'s argument not the `toEqual`'s one, so yeah removing the indentation in that one would indeed solve the issue I was mentioning! you're (unsurprisingly) totally right! thank's a lot for clarifying! your last code snippet does indeed look very very nice!!! :heart_eyes: 
___

Thank you so very much, I really really appreciate you clarifying this even if it's such an old discussion at this point! :heart: 
(ps: it does really look like a nice trick I'll try to remember it! :smiley:)

2021-11-09 18:02 UTC, atscott commented
This PR was merged into the repository by commit 0ae4187566bb6e0121b0026cb897f00a328d2aa8.

2021-11-09 18:02 UTC, closed without merging