feat(forms): Implement strict types for the Angular Forms package.
angular/angular pull request #43834
Opened 2021-10-14 02:33 UTC by dylhunn

This PR strongly types the forms package by adding generics to `AbstractControl` classes as well as `FormBuilder`. This makes forms type-safe and null-safe, for both controls and values.

The design uses a "control-types" approach. In other words, the type parameter on `FormGroup` is an object containing controls, and the type parameter on `FormArray` is a control.

Issue: #13721

**How to try out typed forms with your project:**

1. Update `@angular/core` to version `14.0.0-next.8` or higher: `ng update @angular/cli @angular/core --next`
2. In package.json, switch `@angular/forms` from `14.0.0-next.x` to `https://output.circle-artifacts.com/output/job/f35a2f67-f228-4906-b3fe-6af3047479c1/artifacts/0/angular/forms-pr43834-15d86e186e.tgz`
3. Install the new dependencies, ignoring peer dependency warnings: `npm i --force` or `yarn install --force`
4. Run the typed forms experimental migration: `ng update @angular/core --migrate-only --name migration-v14-typed-forms`

2021-10-14 13:51 UTC, NetanelBasal commented
There are a lot of challenges in this area due to the flexibility of the API. As far as I can tell, I've written a typed version that reaches the maximum we can without breaking the API. Feel free to look at the source code:

https://github.com/ngneat/reactive-forms

2021-11-04 01:07 UTC, AndrewKushnir reviewed
FYI, just sharing first batch of comments, will publish more comments tomorrow.

2021-11-04 01:07 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +  abstract patchValue(value: ValT, options?: Object): void;
Just an idea: should we call the `ValT` (partial) and `RawValT` (full) pair as `PartialValueT` and `ValueT`? I think that might convey the meaning a bit better.

2021-11-04 08:43 UTC, criskrzysiu commented
one question, should new spec follow https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#exact-optional-property-types  in how optional fields are specified?

For example if we have model like 
```typescript
{
age?: number
}
````
then the control can not be removed using removeControl()

while with
```typescript
{
age: number | undefined
}
```
this should be possible

2021-11-18 22:01 UTC, sonukapoor commented on packages/forms/src/model.ts
> +  abstract patchValue(value: ValT, options?: Object): void;
Agreed.

2021-11-30 09:40 UTC, ramthir commented
I tested out the typed form a bit, and it's excellent with inferring types and stuff.

I've one question. When we `patchValue`, we use a `Partial` data structure, but when we `setValue` we're considering all the properties to be mandatory. Of course, we allow it to be null, but can't we make the optional fields based on the mandatory validation optional in the type itself?

2021-12-13 22:43 UTC, dylhunn commented on packages/forms/src/model.ts
> +  abstract patchValue(value: ValT, options?: Object): void;
Fixed.

2021-12-13 22:43 UTC, dylhunn commented on packages/forms/src/form_builder.ts
> +       asyncValidator?: AsyncValidatorFn|AsyncValidatorFn[]|null): FormControl<T|null>;
Discussed in RFC -- controls that don't reset to their initial value will be nullable. This will also be documented at length.

2021-12-13 22:43 UTC, dylhunn commented on packages/forms/src/form_builder.ts
> + * validators.
Fixed.

2021-12-14 07:35 UTC, SchnWalter commented on packages/forms/src/form_builder.ts
> +       asyncValidator?: AsyncValidatorFn|AsyncValidatorFn[]|null): FormControl<T|null>;
> Discussed in RFC

Where can I find the RFC? I couldn't find it.

(Thanks for all the hard work)

2021-12-15 00:39 UTC, dylhunn commented
Rerunning failures reveals these are flakes: https://fusion2.corp.google.com/presubmit/tap/416417012/OCL:416417012:BASE:416422956:1639528317533:31818db4/targets

2021-12-16 17:16 UTC, dylhunn commented
[The RFC with this PR as a demo](https://github.com/angular/angular/discussions/44513
) has now been posted!

2022-02-01 01:18 UTC, dylhunn commented
This is starting to converge. The [RFC is complete](https://github.com/angular/angular/discussions/44513), a number of preparatory PRs have landed, and this is now rebased on head. The next step is to update this PR with feedback from the RFC.

2022-02-02 21:37 UTC, dylhunn commented
All bugs that I'm aware of are fixed, and the PR is reduced to its smallest possible footprint. I think this is now ready for review.

2022-02-03 21:10 UTC, atscott requested changes, later dismissed
reviewed-for: public-api

2022-02-03 21:10 UTC, atscott commented on packages/forms/test/typed_integration_spec.ts
> +    }
```suggestion
    interface Cat {
      lives: number;
    }
    interface Person {
      nickname: string;
    }
    interface CatControls {
      lives: FormControl<number>;
    }
    interface PersonControls {
      nickname: FormControl<string>;
    }
```
nit: code style

2022-02-03 21:10 UTC, atscott commented on packages/forms/src/model.ts
> +    ;
Would it be more helpful to just turn clang format off for these lines with `// clang-format: off`/`// clang-format: on` comments?

2022-02-03 22:39 UTC, dylhunn commented on goldens/public-api/forms/forms.md
> +    group(cc: {
I believe I renamed this parameter because `controlsConfig` was no longer accurate -- the proper type is wider. I went ahead and used `childControls` wherever applicable.

2022-02-03 22:40 UTC, dylhunn commented on packages/forms/test/typed_integration_spec.ts
> +(function() {
I don't think so, I must have copied this from elsewhere. I have removed it.

2022-02-03 22:41 UTC, dylhunn commented on packages/forms/test/typed_integration_spec.ts
> +    {
The stuff inside `{ ... }` is identical in every test, and is a multiline check I couldn't figure out how to factor out. I can change it if you like.

2022-02-03 22:42 UTC, dylhunn commented on packages/forms/test/typed_integration_spec.ts
> +      t1 = null as unknown as ValueType;
Technically yes, but I've used precisely the same format in every test as it's a bit tricky to check assignability both ways.

2022-02-03 22:42 UTC, dylhunn commented on packages/forms/src/form_builder.ts
> +  * @see [Reactive Forms Guide](/guide/reactive-forms)
Fixed.

2022-02-03 22:43 UTC, dylhunn commented on packages/forms/src/form_builder.ts
> +    * TODO: Do we want to support providing default values to create non-nullable controls?
Removed -- this TODO is months stale.

2022-02-03 22:43 UTC, dylhunn commented on packages/forms/test/typed_integration_spec.ts
> +    }
Fixed.

2022-02-03 22:47 UTC, dylhunn commented on packages/forms/src/model.ts
> +    ;
Yes, I've made this change.

2022-02-05 02:39 UTC, AndrewKushnir reviewed
@dylhunn awesome work! 👍 I've left some comments, but they are not critical.

It'd be great if @alxhub and/or @JoostK can take a look at those changes from more in-depth TypeScript perspective.

2022-02-05 02:39 UTC, AndrewKushnir commented on goldens/public-api/forms/forms.md
> +export class FormArray<ElemT extends AbstractControl<Value<ElemT>, RawValue<ElemT>> = any> extends AbstractControl<Array<Value<ElemT>>, Array<RawValue<ElemT>>> {
As an idea: would it make sense to call it `ControlT`, so it's a bit better fit for methods (like `at`, `setControl`, etc)?

2022-02-05 02:39 UTC, AndrewKushnir commented on goldens/public-api/forms/forms.md
> +    array<T>(childControls: Array<T | FormState<T> | ControlConfig<T> | AbstractControl<T> | FormControl<T>>, validatorOrOpts?: ValidatorFn | ValidatorFn[] | AbstractControlOptions | null, asyncValid
I think "childControls" may be a misleading name here. Those controls are elements of an array, not its children. I'd probably call it just "controls" :)

2022-02-05 02:39 UTC, AndrewKushnir commented on goldens/public-api/forms/forms.md
> +export class FormGroup<CtrlT extends {
nit: should we use a full name here as well for consistency (`CtrlT` -> `ControlT`)?

2022-02-05 02:39 UTC, AndrewKushnir commented on goldens/public-api/forms/forms.md
> +}> extends AbstractControl<FormGroupValue<CtrlT>, FormGroupRawValue<CtrlT>> {
I don't see `FormGroupValue` and `FormGroupRawValue` type definitions in the public API (in this file). They'd probably become visible in the public surface, so we should export them too?

2022-02-05 02:39 UTC, AndrewKushnir commented on packages/forms/src/form_builder.ts
> +         AbstractControl<T[K]>|T[K]
The `FormControl<T[K]>` is a more precise version of the `AbstractControl<T[K]>`. I believe we need both here, but it's unclear why. Can we add a quick comment to explain this?

2022-02-05 02:39 UTC, AndrewKushnir commented on packages/forms/src/form_builder.ts
> +     initialValueIsDefault: true
Could you please add a comment in the code on why we use `FormControlOptions&{initialValueIsDefault: true}` here?

2022-02-05 02:39 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +export type TypedOrUntyped<T, Typed, Untyped> = T extends never ? Untyped : Typed;
If I understand correctly, this type is temporary (while we support mixed typed and untyped forms) and we don't want developers to rely on it? I'd propose adding it into a description.

2022-02-05 02:39 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> + * That type can contain partials, due to disabled controls. The optional type parameter RawValueT
I think we need to link it to some page that has a thorough description of the disabled state impact on the data structure (that disabled controls are excluded from the `.value`).

2022-02-05 02:39 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +  // TODO(issue/24571): remove '!'.
Drop this `TODO`?

2022-02-05 02:39 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> -  _isBoxedValue(formState: any): boolean {
nit: we use "boxed" as a term in some tests. We can do a separate PR to cleanup it before/after this one.

2022-02-05 02:39 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> + * @publicApi
Do we expect developers to interact with those types? I understand that they'd "leak" into the public API, but we could add a quick comment to the description that those types should only be used when absolutely needed (avoided in most cases).

2022-02-05 02:46 UTC, dram2040 commented on goldens/public-api/forms/forms.md
> +    get parent(): AbstractControl<any> | null;
**A1B2C3**
-true> - opinion
¬</¿
?>2.17.97

2022-02-05 23:20 UTC, JoostK reviewed
Here's an initial batch of comments. I've only now reached the interesting TS types, those will take me some more time to go over :-)

2022-02-05 23:20 UTC, JoostK commented on packages/forms/src/form_builder.ts
> +       return this.control<T>(value, validator, asyncValidator);
All type annotations and the non-null assertion operators are unnecessary here, as TS has narrowed `childControls` to be the tuple `ControlConfig` here, because that's the only array type among the constituents of the `childControls` parameter's union type. But feel free to keep them if you think it helps clarify the code.

```suggestion
       const value = childControls[0];
       const validator = childControls.length > 1 ? childControls[1] : null;
       const asyncValidator = childControls.length > 2 ? childControls[2] : null;
       return this.control<T>(value, validator, asyncValidator);
```

2022-02-05 23:20 UTC, JoostK commented on packages/forms/src/model.ts
> +function assertControlPresent(parent: FormGroup<any>|FormArray<any>, key: string|number): void {
Consider using `unknown` to avoid proliferation of `any`s in the codebase (same for `assertAllValuesPresent` below)

2022-02-05 23:20 UTC, JoostK commented on packages/forms/src/model.ts
> + * TypedOrUntyped allows one of two different types to be selected, depending on whether the Forms
```suggestion
 * `TypedOrUntyped` allows one of two different types to be selected, depending on whether the Forms
```

2022-02-05 23:20 UTC, JoostK commented on packages/forms/src/model.ts
> + * Class it's applied to is typed or not.
nit: since `class` doesn't have a symbol (like it has in Java, for example) I'd opt to use lowercase here:

```suggestion
 * class it's applied to is typed or not.
```

2022-02-05 23:20 UTC, JoostK commented on packages/forms/src/model.ts
> +export type TypedOrUntyped<T, Typed, Untyped> = T extends never ? Untyped : Typed;
Does this really have to be public API at all? I see it's used in the declaration of the public `FormGroupValue` and `FormGroupRawValue`, but I don't think that necessitates that `TypedOrUntyped` also becomes public as no-one would ever have to refer to that type by name.

Looking closer, do `FormGroupValue` and `FormGroupRawValue` have to be public API? They're used in public API, but I think they can act as opaque type-aliases. Although I guess that would introduce unresolvable references in the documentation?

2022-02-05 23:20 UTC, JoostK commented on packages/forms/src/model.ts
> + * Value gives the type of `.value` in an AbstractControl.
```suggestion
 * Value gives the type of `.value` in an `AbstractControl`.
```

2022-02-07 17:10 UTC, atscott commented on packages/forms/src/model.ts
> +export type TypedOrUntyped<T, Typed, Untyped> = T extends never ? Untyped : Typed;
FWIW, things have to be marked public api in order to show up on the angular.io site. If it's used in something that appears in the public API and this _wasn't_, it would mean you wouldn't be able to see what `TypedOrUntyped` actually was from aio. This is currently true of the `Tree` and `TreeNode` of the `RouterState` (https://angular.io/api/router/RouterState).

2022-02-07 17:12 UTC, JoostK commented on packages/forms/src/model.ts
> +export type TypedOrUntyped<T, Typed, Untyped> = T extends never ? Untyped : Typed;
Yeah, I thought that would be the case, unfortunately.

2022-02-07 17:25 UTC, dylhunn commented
Thanks everyone! It will take me a day or so to respond to all the comments, then I will @ my reviewers and put the PR back in reviewable state.

2022-02-08 18:09 UTC, mikaelboff commented
Very nice job, waiting for this!!

2022-02-12 18:53 UTC, sonukapoor commented on goldens/public-api/forms/forms.md
> +export class FormArray<ElemT extends AbstractControl<Value<ElemT>, RawValue<ElemT>> = any> extends AbstractControl<Array<Value<ElemT>>, Array<RawValue<ElemT>>> {
I agree `ControlT` would be better here and in the below where `ElemT` is used.

2022-02-12 18:57 UTC, sonukapoor commented on packages/forms/src/form_builder.ts
> +    * @param cc A collection of child controls. The key for each child is the name
@JoostK I think @AndrewKushnir mentioned somewhere in that this should maybe just called `controls` instead. Is that what it was renamed to?

2022-02-13 14:25 UTC, JoostK reviewed
Having that `typed_integration_spec.ts` open in IntelliJ seems to kill my CPU:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/123679/153757489-29fd88c5-20d1-4b88-9765-5a44ad794285.png">

the drop is when I closed the editor and then reopened it again, spiking yet again. Not sure if this is specific to IntelliJ or if it's the TS language server that's spiking. I suspect it's IntelliJ, would be good to have someone confirm that this doesn't cause issues in VS Code.

2022-02-13 14:25 UTC, JoostK commented on packages/forms/test/typed_integration_spec.ts
> +      t1 = null as unknown as ValueType;
What is this trying to assert?

Would it be helpful to have something like the following to more easily/clearly assert that the desired type is produced?

```ts
function expectType<T>(type: T): void {}

expectType<string>(valueWhichShouldBeOfTypeString);
```

2022-02-13 14:25 UTC, JoostK commented on packages/forms/test/typed_integration_spec.ts
> +    c.setValue('');
I'd personally opt to use `@ts-expect-error` expectations here for invalid usages of the API, e.g.

```ts
// @ts-expect-error
c.setValue(null);
```

As currently we seem to be confirming that anything valid is accepted, but not that invalid values produce a compilation error.

2022-02-14 11:33 UTC, sonukapoor commented
> Having that `typed_integration_spec.ts` open in IntelliJ seems to kill my CPU:
> 
> <img alt="image" width="646" src="https://user-images.githubusercontent.com/123679/153757489-29fd88c5-20d1-4b88-9765-5a44ad794285.png">
> 
> the drop is when I closed the editor and then reopened it again, spiking yet again. Not sure if this is specific to IntelliJ or if it's the TS language server that's spiking. I suspect it's IntelliJ (almost certain since the language service is single threaded), would be good to have someone confirm that this doesn't cause issues in VS Code.

I took a quick look at this in VS Code and don't see anything unusual. VS Code behaves normal.

2022-02-14 11:34 UTC, sonukapoor commented
> Having that `typed_integration_spec.ts` open in IntelliJ seems to kill my CPU:
> 
> <img alt="image" width="646" src="https://user-images.githubusercontent.com/123679/153757489-29fd88c5-20d1-4b88-9765-5a44ad794285.png">
> 
> the drop is when I closed the editor and then reopened it again, spiking yet again. Not sure if this is specific to IntelliJ or if it's the TS language server that's spiking. I suspect it's IntelliJ (almost certain since the language service is single threaded), would be good to have someone confirm that this doesn't cause issues in VS Code.

I took a quick look at this in VS Code and don't see anything unusual. VS Code behaves normal.

2022-02-15 16:50 UTC, dylhunn reviewed
@JoostK @AndrewKushnir @atscott Thank you all for the thorough review comments! I have responded to all comments, incorporated the changes, and updated the PR. I'm ready for another round of review when you're available, thanks!

2022-02-15 16:50 UTC, dylhunn commented on packages/forms/src/form_builder.ts
> +     initialValueIsDefault: true
Done: "This signature captures calls which set `initialValueIsDefault: true`."

2022-02-15 17:32 UTC, JoostK commented on packages/forms/src/form_builder.ts
> +       return childControls;
Narrowing at call sites won't depend on the implementation of a function, only its return type.

Here, `childControls` would have been narrowed to `AbstractControl` which satisfies the return type, so TS accepts this return value. If you were to remove the `childControls instanceof FormControl` check then we'd pass this `AbdtractControl` condition instead, and `childControls` would still be accepted as return value as an `AbstractControl` is still a value return type.

The only difference is that there won't be a return statement that has been narrowed to `FormControl<T>` even though that is specified as a return type, but that's not visible from callers.

2022-02-15 17:33 UTC, JoostK commented on packages/forms/src/form_builder.ts
> +       return this.control<T>(value, validator, asyncValidator);
Hmm that's surprising, IIRC I did try the code I suggested and I don't remember seeing any errors. But happy to keep as is as this is indeed non-trivial to follow.

2022-02-20 00:25 UTC, dylhunn commented
Typed Forms TGP Update: By using qualified exports (e.g. `export {UntypedFormGroup as FormGroup}`), it was possible to run a TAP global presubmit on the typed forms prototype: [link to deflake run](https://fusion2.corp.google.com/OCL:429799493:BASE:429799995:1645316597494:8b7b1c22). There is only one failing cluster, with a single underlying root cause.

However, the one root cause is depended on by 20 targets, and it exposes an interesting issue. I have created a minimal reproduction: [playground link](https://www.typescriptlang.org/play?#code/PTAEGUEsFsAcBtIDNIFMAmpoHt2vqAC4CesqAzqEtgE6gBit0A4jdgK6ygCGAdpkhpp+5AHQAoEBGzRUobEiIALCnLyFukeJW405kGnvioAbn0IAaUACN2hUJF4BjeOzwDaoJzISpCqXgoxcXESMghCIV4AcwBpVGJyAHkkAB4AFVBUAA9-EXlrACtUJ0IAPlAAXlAAUVyablLUgGsEhVB0q3JIx2iygG4QvBddORHySgBBa26G0oBhbF5I7HgMqp5eYgqAb3FQA9AzV1QALg7Bw68l2fZS2gAKY-YzjoBKQYBfELC5ADVuCd1jk8ugpjNIo1CItlmx4AAfdj8VAoQLoCqVfaHTIggJg0DTWZQmErNZ8bYAfg6AG0AOTPVC0gC6oHOgRMqBog1CpDkjBoLDYnHSvPQSRoAFVlqLUiS4Z0OqKrFLfuiNnsDtTWsRzrNekzzuTxJ8srk8ZQ5atMlSVaLWYqyOhub8GExWBxYACgTizfkdtTYg5eKBte10kyKedCZCFktSZ8MViDvzBR6RY7xbbHRkrAAFXSESCA1L+wOOENtRTh85el4ZANMsoJqz+7W6noxA2bYgJ7niYbwUZeQcTV0C92cWVx+Wm0GUUtBivEdqW+DVgkQubQ6erE3VVsJdtRaJd6Nb1cJ2fmpNXDdE2Ow1apFMT2DpjCZ6XZ1cKl9Cz2AnWP5lFY5JlLsN7eLwtz3DQDxQaS5DnD+Hw3no0SQN0nKrqkga4vk4AdnECTJGkwFlA8vDcLI5yxG85wmNgkBOsaIRSOkSiYdc0HsLIdAuvh+LUAKoDRP+myYE47CGAEhDwMQoAAO60M0wRSAA6nI0DsN0NhjKMSDsAQvDYPYhDYDYejcM0DiEBI-YlIOejDtwo6Ece8TEK+GQVIJlB-h6oAaoc6GYf4NCrpR1GvHqMT0UcTEsd8khgBxXFQeQvGckQvJXvkAWcKB-CgOg2AUKAJn2LYWjoPZA5DuMlDgNABacgVsA+Xl+LtUFaGoBhWERTuax4b6+KhlWFFUTRoB0QxiVfCEQA).

2022-02-23 18:46 UTC, mary-poppins commented
You can preview d4a3e01 at https://pr43834-d4a3e01.ngbuilds.io/.
You can preview ba6dae0 at https://pr43834-ba6dae0.ngbuilds.io/.
You can preview 788d6da at https://pr43834-788d6da.ngbuilds.io/.
You can preview a3362d2 at https://pr43834-a3362d2.ngbuilds.io/.
You can preview 0e99ee7 at https://pr43834-0e99ee7.ngbuilds.io/.
You can preview d8ede69 at https://pr43834-d8ede69.ngbuilds.io/.
You can preview 4ada340 at https://pr43834-4ada340.ngbuilds.io/.
You can preview d991f13 at https://pr43834-d991f13.ngbuilds.io/.
You can preview e805c6c at https://pr43834-e805c6c.ngbuilds.io/.
You can preview b40238f at https://pr43834-b40238f.ngbuilds.io/.
You can preview 0223e92 at https://pr43834-0223e92.ngbuilds.io/.
You can preview 0501e05 at https://pr43834-0501e05.ngbuilds.io/.
You can preview 10879c9 at https://pr43834-10879c9.ngbuilds.io/.
You can preview 44a1f0b at https://pr43834-44a1f0b.ngbuilds.io/.
You can preview f3b256a at https://pr43834-f3b256a.ngbuilds.io/.
You can preview 3626aab at https://pr43834-3626aab.ngbuilds.io/.
You can preview 8ec6bf7 at https://pr43834-8ec6bf7.ngbuilds.io/.
You can preview 6f1c40e at https://pr43834-6f1c40e.ngbuilds.io/.
You can preview ccc46df at https://pr43834-ccc46df.ngbuilds.io/.
You can preview b496ad6 at https://pr43834-b496ad6.ngbuilds.io/.
You can preview 5850beb at https://pr43834-5850beb.ngbuilds.io/.
You can preview 06f35f3 at https://pr43834-06f35f3.ngbuilds.io/.
You can preview d71ca33 at https://pr43834-d71ca33.ngbuilds.io/.
You can preview 8139256 at https://pr43834-8139256.ngbuilds.io/.
You can preview 281aa00 at https://pr43834-281aa00.ngbuilds.io/.
You can preview 61a333c at https://pr43834-61a333c.ngbuilds.io/.
You can preview 9b85074 at https://pr43834-9b85074.ngbuilds.io/.
You can preview a3da34d at https://pr43834-a3da34d.ngbuilds.io/.
You can preview b34146f at https://pr43834-b34146f.ngbuilds.io/.
You can preview c7c1a20 at https://pr43834-c7c1a20.ngbuilds.io/.
You can preview 058e1ac at https://pr43834-058e1ac.ngbuilds.io/.

2022-02-23 19:12 UTC, mary-poppins commented
You can preview 45e2a88 at https://pr43834-45e2a88.ngbuilds.io/.

2022-03-03 03:18 UTC, dylhunn commented
I have updated the PR to avoid [the issue with tsc](https://github.com/microsoft/TypeScript/issues/48033), and am running [another TGP](https://test.corp.google.com/OCL:432053390:BASE:432082831:1646276600728:40d99410) (looks good so far).

2022-03-04 02:48 UTC, alfaproject commented on goldens/public-api/forms/forms.md
> +export abstract class AbstractControl<ValueT = any, RawValueT extends ValueT = ValueT> {
I work with a lot of TS projects from multiple companies and I never seen a `T` suffix like this. Generics from C# and Java always use a prefixed `T` like in `TData`, `TReq`, etc

Microsoft, Facebook, Apollo just to give a few examples always have a prefixed T. Is this style a Google thing? I've tried to look it up but couldn't find anything in Google style guides. It looks super weird o:

Actually, I remembered to look into Angular repo and it looks the 'right thing' is already being done https://github.com/angular/angular/search?q=TExpression

2022-03-04 23:40 UTC, dylhunn commented on goldens/public-api/forms/forms.md
> +export abstract class AbstractControl<ValueT = any, RawValueT extends ValueT = ValueT> {
Thanks, we have actually received this feedback in a couple places. I've updated all instances to use the `T` as a prefix instead of a suffix.

2022-03-09 23:18 UTC, dylhunn commented
I will put this back in draft state for now, since I'm OOO next week. Once I'm back I will push to finalize and review the PR. Thanks everyone!

2022-03-12 02:04 UTC, hussinhassan80 approved these changes

2022-03-21 18:17 UTC, dylhunn commented
Marking ready for review again, now that I'm back.

2022-03-21 21:27 UTC, alxhub commented on packages/forms/src/model/abstract_model.ts
> +export type Get<T, K> =                                                   /*\n*/
All of these helper types need to be exported from the forms package root, as they're effectively part of the public API surface.

We should also give them more descriptive names, and namespace them with `ɵ` to indicate that they're not meant for user consumption.

2022-03-21 21:44 UTC, dylhunn commented on packages/forms/src/model/abstract_model.ts
> +export type Get<T, K> =                                                   /*\n*/
For all types which are named in the public API, I have marked them exported, added `ɵ` to their names, and reexported them from `forms.ts`.

Do you think I need to do this for inner types as well, which are never named in the public API but are implementation details of public types? (e.g. `abstract_model.ts#Tokenize`)

2022-03-21 22:11 UTC, mary-poppins commented
You can preview d4a3e01 at https://pr43834-d4a3e01.ngbuilds.io/.
You can preview ba6dae0 at https://pr43834-ba6dae0.ngbuilds.io/.
You can preview 788d6da at https://pr43834-788d6da.ngbuilds.io/.
You can preview a3362d2 at https://pr43834-a3362d2.ngbuilds.io/.
You can preview 0e99ee7 at https://pr43834-0e99ee7.ngbuilds.io/.
You can preview d8ede69 at https://pr43834-d8ede69.ngbuilds.io/.
You can preview 4ada340 at https://pr43834-4ada340.ngbuilds.io/.
You can preview d991f13 at https://pr43834-d991f13.ngbuilds.io/.
You can preview e805c6c at https://pr43834-e805c6c.ngbuilds.io/.
You can preview b40238f at https://pr43834-b40238f.ngbuilds.io/.
You can preview 0223e92 at https://pr43834-0223e92.ngbuilds.io/.
You can preview 0501e05 at https://pr43834-0501e05.ngbuilds.io/.
You can preview 10879c9 at https://pr43834-10879c9.ngbuilds.io/.
You can preview 44a1f0b at https://pr43834-44a1f0b.ngbuilds.io/.
You can preview f3b256a at https://pr43834-f3b256a.ngbuilds.io/.
You can preview 3626aab at https://pr43834-3626aab.ngbuilds.io/.
You can preview 8ec6bf7 at https://pr43834-8ec6bf7.ngbuilds.io/.
You can preview 6f1c40e at https://pr43834-6f1c40e.ngbuilds.io/.
You can preview ccc46df at https://pr43834-ccc46df.ngbuilds.io/.
You can preview b496ad6 at https://pr43834-b496ad6.ngbuilds.io/.
You can preview 5850beb at https://pr43834-5850beb.ngbuilds.io/.
You can preview 06f35f3 at https://pr43834-06f35f3.ngbuilds.io/.
You can preview d71ca33 at https://pr43834-d71ca33.ngbuilds.io/.
You can preview 8139256 at https://pr43834-8139256.ngbuilds.io/.
You can preview 281aa00 at https://pr43834-281aa00.ngbuilds.io/.
You can preview 61a333c at https://pr43834-61a333c.ngbuilds.io/.
You can preview 9b85074 at https://pr43834-9b85074.ngbuilds.io/.
You can preview a3da34d at https://pr43834-a3da34d.ngbuilds.io/.
You can preview b34146f at https://pr43834-b34146f.ngbuilds.io/.
You can preview c7c1a20 at https://pr43834-c7c1a20.ngbuilds.io/.
You can preview 058e1ac at https://pr43834-058e1ac.ngbuilds.io/.
You can preview 30630ce at https://pr43834-30630ce.ngbuilds.io/.
You can preview 45e2a88 at https://pr43834-45e2a88.ngbuilds.io/.
You can preview 69ca188 at https://pr43834-69ca188.ngbuilds.io/.
You can preview 5a5206a at https://pr43834-5a5206a.ngbuilds.io/.
You can preview c76fc16 at https://pr43834-c76fc16.ngbuilds.io/.
You can preview 6dbb737 at https://pr43834-6dbb737.ngbuilds.io/.
You can preview cb2ef62 at https://pr43834-cb2ef62.ngbuilds.io/.
You can preview 0935411 at https://pr43834-0935411.ngbuilds.io/.
You can preview 88a236c at https://pr43834-88a236c.ngbuilds.io/.
You can preview d938471 at https://pr43834-d938471.ngbuilds.io/.
You can preview bc16de0 at https://pr43834-bc16de0.ngbuilds.io/.
You can preview da7b896 at https://pr43834-da7b896.ngbuilds.io/.
You can preview 4b2644f at https://pr43834-4b2644f.ngbuilds.io/.
You can preview f4d1918 at https://pr43834-f4d1918.ngbuilds.io/.
You can preview b6d3604 at https://pr43834-b6d3604.ngbuilds.io/.
You can preview 555c6d4 at https://pr43834-555c6d4.ngbuilds.io/.
You can preview f9ce55d at https://pr43834-f9ce55d.ngbuilds.io/.

2022-03-21 22:16 UTC, atscott commented on packages/forms/src/model/abstract_model.ts
> +export type Get<T, K> =                                                   /*\n*/
I added the aio preview label so you can check what things look like there. I think the answer is going to be "yes". Anything that appears in the public API types will need to be exported through the index or it won't be navigable on aio.

2022-03-22 18:20 UTC, dylhunn commented on packages/forms/src/model/abstract_model.ts
> +export type Get<T, K> =                                                   /*\n*/
I believe prefixing with `ɵ` actually causes the symbols to be *dropped* from the public docs, which makes sense. I recommend that we drop the `ɵ` from the top-level exported symbols. WDYT?

2022-03-22 18:36 UTC, mary-poppins commented
You can preview f2e959d at https://pr43834-f2e959d.ngbuilds.io/.

2022-03-23 01:10 UTC, AndrewKushnir reviewed
@dylhunn looks great, just left some minor comments.

2022-03-23 01:10 UTC, AndrewKushnir commented on packages/forms/src/model/form_group.ts
> +        (this.controls as any)[name]!.patchValue(
Possible refactoring:
```suggestion
      // ... comment on why we use `as any` here ...
      const control = (this.controls as any)[name];
      control?.patchValue(
```

2022-03-23 02:05 UTC, dylhunn commented on packages/forms/src/model/abstract_model.ts
> +export type ɵIsAny<T, Y, N> = 0 extends(1&T) ? Y : N;
Done.

2022-03-23 02:05 UTC, dylhunn commented on packages/forms/src/model/abstract_model.ts
> +// clang-format off
Done.

2022-03-23 02:05 UTC, dylhunn commented on packages/forms/src/model/abstract_model.ts
> + * The optional type parameter TRawValue  represents the raw value type (`control.getRawValue()`).
I don't think that `AbstractControl` is the right place to highlight this distinction -- for some subclasses the two types will be related differently (as in `FormControl`). We do need some more documentation though; I will do a separate PR soon to supplement the docs.

2022-03-23 02:05 UTC, dylhunn commented on packages/forms/src/model/form_array.ts
> +      (this.at(index) as any).setValue(newValue, {onlySelf: true, emitEvent: options.emitEvent});
It's actually not needed! I've removed it.

2022-03-23 02:07 UTC, dylhunn commented on packages/forms/src/model/form_group.ts
> +        (this.controls as any)[name]!.patchValue(
Fixed.

2022-03-23 02:08 UTC, dylhunn commented on packages/forms/src/form_builder.ts
> +     * @deprecated This API is not typesafe and can result in issues with Closure Compiler renaming.
I think we should clean this up, but in a separate PR. I'll do a follow up after this lands.

2022-03-23 02:08 UTC, dylhunn commented on goldens/public-api/forms/forms.md
> +    get<P extends string | (readonly (string | number)[])>(path: P): AbstractControl<ɵGetProperty<TRawValue, P>> | null;
All sites fixed, and also resolving the above relevant comment.

2022-03-23 02:08 UTC, dylhunn commented on packages/forms/src/model/abstract_model.ts
> +export type Get<T, K> =                                                   /*\n*/
Resolved according to discussion with Andrew below (https://github.com/angular/angular/pull/43834#discussion_r832739101).

2022-03-30 00:45 UTC, AndrewKushnir approved these changes
👍

2022-03-30 18:39 UTC, alxhub requested changes

2022-03-30 18:39 UTC, alxhub commented on packages/forms/src/model/form_control.ts
> +  new<T = any>(value: FormState<T>|T, opts: FormControlOptions&{initialValueIsDefault: true}):
Should we have a default `T = any` here? I'm not sure it serves any purpose. Untyped creations will go through the `UntypedFormControl` constructor, so I think we should just have a `<T>` parameter here. Or am I misunderstanding?

2022-03-30 18:39 UTC, alxhub commented on packages/forms/src/model/form_control.ts
> +function isFormState<T>(formState: unknown): formState is FormState<T> {
```suggestion
function isFormState(formState: unknown): formState is FormState<unknown> {
```

There's no need for this function to make any assertions about the generic type of the `FormState` - the `<T>` parameters is never passed in this code anyway.

2022-03-30 18:39 UTC, alxhub commented on packages/forms/src/model/form_control.ts
> +        this._applyFormState(formState as FormState<TValue>| TValue);
I think this is an unnecessary cast?

2022-03-30 18:39 UTC, alxhub commented on packages/forms/src/model/form_group.ts
> +  contains<K extends string&keyof TControl>(controlName: K): boolean;
Should we limit the type of `contains`? It may not make sense to disallow checking the existence of arbitrary keys.

2022-03-30 18:39 UTC, alxhub commented on packages/forms/src/form_builder.ts
> +    group<T extends {[key: string]: any} = {[key: string]: any}>(
This is another place where I wonder if we should have default type parameters here. Untyped users will go through the `UntypedFormControl` interface, so I don't think these are useful/desirable?

2022-03-31 00:21 UTC, dylhunn reviewed
All comments addressed below.

2022-03-31 00:21 UTC, dylhunn commented on packages/forms/src/model/form_control.ts
> +type FormControlInterface<TValue = any> = FormControl<TValue>;
Done.

2022-03-31 00:21 UTC, dylhunn commented on packages/forms/src/model/form_control.ts
> +function isFormState<T>(formState: unknown): formState is FormState<T> {
Makes sense, fixed.

2022-03-31 00:21 UTC, dylhunn commented on packages/forms/src/model/form_control.ts
> +        this._applyFormState(formState as FormState<TValue>| TValue);
Indeed. I have removed it.

2022-03-31 00:21 UTC, dylhunn commented on packages/forms/src/model/form_array.ts
> +   *     around from the back, and if index is greatly negative (less than `-length`), the result
Fixed.

2022-03-31 00:21 UTC, dylhunn commented on packages/forms/src/model/form_control.ts
> +  new<T = any>(value: FormState<T>|T, opts: FormControlOptions&{initialValueIsDefault: true}):
I think this is OK to change as well; I've applied the fix.

2022-03-31 00:21 UTC, dylhunn commented on packages/forms/src/model/form_group.ts
> +  contains<K extends string&keyof TControl>(controlName: K): boolean;
I agree that it's probably not helpful for us to constrain `contains` like this. I've removed the constraint and added a unit test for it.

2022-03-31 00:21 UTC, dylhunn commented on packages/forms/src/form_builder.ts
> +    group<T extends {[key: string]: any} = {[key: string]: any}>(
I think this is *probably* OK, and I have removed all the default type arguments on `FormBuilder`. To be honest, I need to add a lot more typed unit tests of `FormBuilder` -- it's not as tested as the new typed model classes. I'll do this tomorrow, to make sure we're not breaking any use case we haven't considered.

2022-03-31 00:21 UTC, dylhunn commented on packages/forms/src/model/form_array.ts
> +export class FormArray<TControl extends AbstractControl<ɵValue<TControl>, ɵRawValue<TControl>> =
Your comment got dropped from the GitHub UI due to me deleting that line, but here it was:

> Does this include unknown in the untyped case? It shouldn't - AbstractControl<unknown> should use the typed API. We should really delegate this to the canonical TypedOrUntyped implementation in abstract_model.

This is a really interesting question. I spent quite a bit of time thinking about this, and I think that having a separate `FormArrayTypedOrUntyped` is both confusing and technically incorrect in the `unknown` case.

I have reworked the type of `TControl` a bit -- I'm now using an identical approach to the one above in `FormGroup.controls`. Specifically, `TControl` defaults to `any`, which can always be disambiguated from the typed case of `AbstractControl<T>`, using the same `TypedOrUntyped` helper as above. It's at the cost of a bit of added complexity in the type of `TControl`, but I think that it is more correct.

2022-03-31 00:23 UTC, dylhunn commented on packages/forms/src/model/form_array.ts
> +    T extends AbstractControl<infer U>? (unknown extends U ? Untyped : Typed) : never;
See response below.

2022-03-31 20:10 UTC, alxhub approved these changes
🎉 nice work, Dylan, I think this is in great shape! Just another couple small comments but otherwise LGTM!

2022-03-31 20:13 UTC, dylhunn commented on packages/forms/src/model/abstract_model.ts
> +*/
Thanks, good catch. Fixed.

2022-03-31 20:13 UTC, dylhunn commented on packages/forms/src/model/abstract_model.ts
> +type Writeable<T> = {
Fixed.

2022-04-01 00:41 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2022-04-04 13:21 UTC, cexbrayat commented on packages/forms/test/typed_integration_spec.ts
> +      //     new FormArray([new FormControl(true, {initialValueIsDefault: true})]);
FYI this is commented out, is it on purpose?

2022-04-04 18:07 UTC, alxhub approved these changes
Reviewed-for: public-api

2022-04-04 18:12 UTC, dylhunn commented on packages/forms/test/typed_integration_spec.ts
> +      //     new FormArray([new FormControl(true, {initialValueIsDefault: true})]);
No -- cleaned up, thanks!

2022-04-04 18:12 UTC, dylhunn commented on packages/forms/src/model/form_array.ts
> + * FormGroupRawValue extracts the type of `.getRawValue()` from a FormArray's element type, and
Yes, thanks!

2022-04-04 19:17 UTC, atscott approved these changes
reviewed-for: public API

2022-04-04 19:17 UTC, atscott commented on goldens/public-api/forms/index.md
>          [key: string]: AbstractControl;
For places where we we are opting in to the untyped behavior, should `AbstractControl` explicitly be written as `AbstractControl<any>` rather than just `AbstractControl` (which, from what I understand, is implicitly `AbstractControl<any>` because of the default type)?

```suggestion
        [key: string]: AbstractControl<any>;
```

This question applies above to the `addControl` method and below to the `setControl`

2022-04-04 20:41 UTC, dylhunn commented on goldens/public-api/forms/index.md
>          [key: string]: AbstractControl;
Yes, I will make this update everywhere the `any` is implicit.

2022-04-04 21:00 UTC, atscott approved these changes
reviewed-for: public-api

2022-04-07 22:12 UTC, itotallyrock commented on packages/forms/src/model/form_control.ts
>     * It is `any` because the value is untyped.
I don't think this comment is necessary anymore 😃 
```suggestion
```

2022-04-08 07:01 UTC, dylhunn commented on packages/forms/src/model/form_control.ts
>     * It is `any` because the value is untyped.
Thanks!

2022-04-08 19:07 UTC, mary-poppins commented
You can preview f161700 at https://pr43834-f161700.ngbuilds.io/.

2022-04-11 23:59 UTC, dylhunn commented
merge-assistance: merge separately, Tuesday morning

2022-04-12 17:37 UTC, closed without merging