docs: initial commit of Angular Package Format documentation
angular/angular pull request #43987
Opened 2021-10-29 22:32 UTC by alxhub

This commit adds the Angular Package Format to AIO. Previously this document
was updated and versioned in Google Docs.

The document is also updated for the Angular Package Format version 13.

2021-10-29 22:42 UTC, mary-poppins commented
You can preview b4b44e2 at https://pr43987-b4b44e2.ngbuilds.io/.

2021-10-29 23:03 UTC, mary-poppins commented
You can preview f747b4c at https://pr43987-f747b4c.ngbuilds.io/.

2021-10-30 17:17 UTC, alan-agius4 commented on aio/content/guide/angular-package-format.md
> +As of APF v8 we now prefer to run the .d.ts bundler tool from https://api-extractor.com/ so that the entire API appears in a single file.
As of APF v8 we prefer to run [API Extractor](https://api-extractor.com/), to bundle TypeScript definitions so that the entire API appears in a single file.

2021-10-30 17:17 UTC, alan-agius4 commented on aio/content/guide/angular-package-format.md
> +As of APF v8 we now prefer to run the .d.ts bundler tool from https://api-extractor.com/ so that the entire API appears in a single file.
```suggestion

As of APF v8 we prefer to run [API Extractor](https://api-extractor.com/), to bundle TypeScript definitions so that the entire API appears in a single file.
```

2021-10-31 19:22 UTC, literalpie commented on aio/content/guide/angular-package-format.md
> +The general rule in for APF packages is to use entrypoints for the smallest sets of logically connected code possible. For example, the Angular Material package publishes each logical component or se
Should this be "The general rule for APF packages"? (remove "in")

2021-10-31 19:22 UTC, literalpie commented on aio/content/guide/angular-package-format.md
> +Not all libraries require such granularity. Most libraries with a single logical purpose should be published as a single entrypoint. `@angular/core` for example uses a single entrypoint for the runti
I think the characters after the period are unintentional.

2021-11-01 11:02 UTC, petebacondarwin requested changes, later dismissed
Great stuff @alxhub - thanks for getting this on track. I made a few mostly stylistic suggestions which I think are worthwhile.

2021-11-01 18:35 UTC, mary-poppins commented
You can preview 25f17fa at https://pr43987-25f17fa.ngbuilds.io/.

2021-11-01 21:26 UTC, alxhub commented on aio/content/guide/angular-package-format.md
> +<code-example language="html">
Converted to a table!

2021-11-01 21:47 UTC, petebacondarwin approved these changes

2021-11-01 21:52 UTC, aikidave approved these changes
Reviewed-for: global-docs-approvers

2021-11-01 21:53 UTC, petebacondarwin approved these changes
Reviewed-for: public-api

2021-11-01 22:05 UTC, alxhub commented on aio/content/guide/angular-package-format.md
> +* `"default"` selects flattened ES2020 code for all other consumers.
> then it is unlikely to have implemented the appropriate transformations to handle async-await properly.
I believe that we assume that whenever people are doing custom build/bundling, that they know what they're doing and will configure any necessary downleveling correctly.

It's only for Node, which usually runs code _unbundled_, that we have to explicitly provide code as ES2015.

2021-11-01 22:15 UTC, jessicajaniuk approved these changes
LGTM :cookie:
reviewed-for: public-api

2021-11-01 22:15 UTC, IgorMinar reviewed
This is shaping up very nicely! I'm still reviewing.. but here is what I have so far...

2021-11-01 22:15 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +APF is an Angular specific specification for layout of npm packages that is used by all first-party Angular packages and most third-party Angular libraries.
are we sure about "most"? wouldn't "many" be better?

2021-11-01 22:15 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +This document describes the structure and format of the Angular framework packages currently available on npm. This format applies to packages distributing Angular components (like Angular Material)
yeah. I'd drop this paragraph.

2021-11-01 22:15 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +* `"default"` selects flattened ES2020 code for all other consumers.
In theory you could build your app without zone.js, in which case this is the more inclusive default. But I see how this could bite people that are building custom build pipelines - the good thing is that we now throw an error if you run your app in a way where async/await runs natively (without down-leveling).

2021-11-01 22:15 UTC, IgorMinar commented on aio/content/navigation.json
> +              "title": "Angular Package Format",
something is not right about the menu item setup - I don't see the whole "Angular Libraries" section in the menu when I navigate to the preview: https://pr43987-25f17fa.ngbuilds.io/docs

2021-11-01 22:21 UTC, alxhub commented on aio/content/navigation.json
> +              "title": "Angular Package Format",
It shows up for me: `Tutorials > Angular Libraries` with 4 entries, including the APF doc.

Another question is whether Tutorials is the right location - I copied that from the previous PR.

2021-11-01 22:23 UTC, alxhub commented on aio/content/guide/angular-package-format.md
> +This document describes the structure and format of the Angular framework packages currently available on npm. This format applies to packages distributing Angular components (like Angular Material)
Done, you're right, it was very redundant.

2021-11-01 22:23 UTC, mary-poppins commented
You can preview fc22f55 at https://pr43987-fc22f55.ngbuilds.io/.

2021-11-01 22:33 UTC, IgorMinar commented on aio/content/navigation.json
> +              "title": "Angular Package Format",
ah.. you are right. I looked but didn't see it there. And in any case, this content doesn't belong there. But let's settle that in a separate PR.

2021-11-01 22:33 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +APF is an Angular specific specification for layout of npm packages that is used by all first-party Angular packages and most third-party Angular libraries.
sgtm

2021-11-01 22:33 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +This document describes the structure and format of the Angular framework packages currently available on npm. This format applies to packages distributing Angular components (like Angular Material)
great! thanks

2021-11-01 22:58 UTC, IgorMinar reviewed
more feedback...

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +<table>
this whole table doesn't render well on angular.io: https://pr43987-fc22f55.ngbuilds.io/guide/angular-package-format#file-layout

There is a lot of wasted space in cells and some cells are empty which makes the whole row look odd and redundant.

I wonder if it wouldn't be better to format this via either custom CSS or as monospaced code block (with ascii-art text layout).

Or at minimum move the whole thing to the bottom of the page? I dunno.. but we should do something about it — other ideas?

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +Besides defining the package to NPM, the primary `package.json` performs several important functions:
```suggestion
Besides defining the package to NPM, the primary `package.json` performs several important functions:
The primary `package.json` contains important package metadata, including the following:
```

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +* It declares the package to be in EcmaScript Module (ESM) format, using `.mjs` files.
```suggestion
* It declares the package to be in EcmaScript Module (ESM) format.
```

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +* It declares the side-effectfulness of the package.
link to the section below.

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +* It declares the package to be in EcmaScript Module (ESM) format, using `.mjs` files.
and link to the section below

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +* It contains an `"exports"` field which defines the available source code formats of all entrypoints.
and link to the section below

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +This informs resolvers that code within the package is using EcmaScript Modules as opposed to CommonJS modules, and uses the `.mjs` file extension.
is the ".mjs" comment right? I believe that with the `"type": "module"` set, the extension is non-loadbearing. We just happen to use .mjs because the bazel rules output that. But we can and might switch to `.js` extension in the future.

With the `"exports"` field set to `"module"`, the extension is an implementation detail not visible to package consumer.

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +To work around this problem, packages can declare that they do not depend on side-effectful code at the top level of their modules, giving optimizers more freedom to tree-shake code from the package.
Please link to https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free here or somewhere else in this section. thanks!

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +This secondary `package.json` is required for legacy resolvers which do not support `"exports"`.
please add "And we expect these files to be removed from future versions of APF once more tools are updated to support the `"exports"` field.". thank you

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +Specific entrypoints might only be used for special purposes, such as testing. Such APIs can be separated out from the primary entrypoint to reduce the chance of them being used accidentally or incor
this content should be offset, otherwise it renders poorly:

![Uploading Screen Shot 2021-11-01 at 3.51.25 PM.png…]()

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +Many modern build tools are only capable of "code splitting" (aka lazy loading) at the ES Module level. Since the Angular Package Format uses primarily a single "flat" ES Module per entrypoint, this
same here

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +The ESM2020 format is included for the purpose of experimentation. Current bundlers are generally better at optimizing flattened files, but new tools are in development which may benefit from process
link to the section below (and possibly shorten this explanation)

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +### Side effects
there is another whole section below on "sideEffects: false"- maybe shorten this one and move stuff down? or consider somehow combining the two please.

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +<dl>
it seems that we don't have css for dl/dt/dd tags (or if we do have some then they are not good) because the output is poorly rendered and hard to read:

<img width="899" alt="Screen Shot 2021-11-01 at 3 55 54 PM" src="https://user-images.githubusercontent.com/216296/139752847-ada6ef0a-8cb9-4043-8fbc-9872e860b923.png">

2021-11-01 22:58 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +<dl>
I'm not quite sure what's the best way to fix this. Adding styles? turning this into a simple list? Moving most of these definitions to the glossary.md file?

2021-11-01 23:04 UTC, mary-poppins commented
You can preview 8052391 at https://pr43987-8052391.ngbuilds.io/.

2021-11-01 23:14 UTC, alxhub commented on aio/content/guide/angular-package-format.md
> +This informs resolvers that code within the package is using EcmaScript Modules as opposed to CommonJS modules, and uses the `.mjs` file extension.
👍 references to `.mjs` have been cleaned up.

2021-11-01 23:20 UTC, jelbourn commented on aio/content/guide/angular-package-format.md
> +<table>
FWIW an ASCII layout probably isn't great for accessibility (vs. a list with nested ul/li)

2021-11-01 23:22 UTC, jelbourn commented on aio/content/guide/angular-package-format.md
> +This document describes the Angular Package Format (APF).
I left a number of comments on a previous PR that turned the Google Doc into formal docs here: https://github.com/angular/angular/pull/37093. I think a fair number of these still apply.

2021-11-01 23:33 UTC, IgorMinar commented on aio/content/guide/angular-package-format.md
> +<table>
right, we discussed this with Alex offline already. I agree.

2021-11-01 23:38 UTC, alxhub commented on aio/content/guide/angular-package-format.md
> +This document describes the Angular Package Format (APF).
I actually incorporated most of those comments into this doc (at least, I think I hit most of them)

2021-11-01 23:44 UTC, mary-poppins commented
You can preview 9308db9 at https://pr43987-9308db9.ngbuilds.io/.

2021-11-01 23:56 UTC, mary-poppins commented
You can preview 2c087b3 at https://pr43987-2c087b3.ngbuilds.io/.

2021-11-02 00:21 UTC, IgorMinar approved these changes
this looks much better! thanks for all the changes. As discussed offline the only remaining nit is the duplicate content about `sideEffects` field. Otherwise this looks great! thanks @alxhub

2021-11-02 00:21 UTC, IgorMinar approved these changes
Reviewed-for: public-api

2021-11-02 00:25 UTC, IgorMinar commented on aio/tests/deployment/shared/URLS_TO_REDIRECT.txt
> +/apf -> /guide/angular-package-format
```suggestion
/apf --> /guide/angular-package-format
```

2021-11-02 00:33 UTC, alxhub commented on aio/content/guide/angular-package-format.md
> +<dl>
I added styles that make the section look much nicer - we can figure out if there's a better approach in a followup.

2021-11-02 00:38 UTC, mary-poppins commented
You can preview a2bcaf7 at https://pr43987-a2bcaf7.ngbuilds.io/.

2021-11-02 01:24 UTC, alxhub commented
This PR was merged into the repository by commit 509b14536abe5c8ab086a8be2e1fb7d4c70035a0.

2021-11-02 01:24 UTC, closed without merging