fix(docs-infra): prevent automatic linking of 'number'
angular/angular pull request #44000
Opened 2021-10-31 11:36 UTC by dario-piotrowicz

add 'number' to the ignoreGenericWords set so that it doesn't get
wrongly linked to the decimalPipe during the aio docs generation
as it is a generic typescript term

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

Various docs pages wrongly automatically link `number` to the decimalPipe

like:

- the [animate docs](https://angular.io/api/animations/animate):
![number-animate](https://user-images.githubusercontent.com/61631103/139580706-0ad9224f-7e37-4146-a62b-7628dc8c9482.png)

- the [docs style guide](https://angular.io/guide/docs-style-guide):
![number-docs-style-guide](https://user-images.githubusercontent.com/61631103/139580760-d08b3260-a23e-4142-8670-3937912381af.png)

- and even the [decimalPipe](https://angular.io/api/common/DecimalPipe) docs themselves:
![number-number](https://user-images.githubusercontent.com/61631103/139580796-1f7f0354-979a-4eed-9183-4b3c3752e2b2.png)

- since this will be present for any instance with the number typescript type I can bet there must be lots more instances of this wrong linking

## What is the new behavior?

The term has been added to the ignoreGenericWords set so that the automatic linking is not performed

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- @gkalpak I think this PR is your cup of tea :slightly_smiling_face: 
- I checked and I think that there are no instances in which the linking is necessary/wanted (I would have added manual linking had I found any), but I am by no means sure of it, I think with something as generic as `number` it's a bit tricky being sure.... but at the very least I believe that the number of unwanted auto-linkings must by far surpass the wanted ones (if there actually are any), so either way I think this change is beneficial (and if someone could suggest how/where to look for instances I must have missed I am all ears :slightly_smiling_face:)
- look at the docs style guide image, can you see the `json` at the bottom? I think that should probably also be added to the ignoreGenericWords set, what do you think? :slightly_smiling_face: (shall I have a look here? or just do it in a separate PR?)
- ah another small thing, in the animate docs the `number` present in `animate(timings: string | number, ...` that is actually a link, but it doesn't have any link styling (except getting underlined on hover) is that ok? :thinking:

2021-11-05 15:06 UTC, mary-poppins commented
You can preview 52dd66c at https://pr44000-52dd66c.ngbuilds.io/.

2021-11-05 15:19 UTC, gkalpak requested changes
Thx, @dario-piotrowicz :+1:

I found only one occurrence where the linking was useful, in [ajs-quick-reference.md][1]. If you could update it to an explicit link, that would be great 🙏

##
Regarding `json`:
That might be worth investigating further. I don't think `json` would appears much inside code-snippets (so it might be preferable to opt-out of auto-linking in specific instances), but that would require more investigation to determine.

Therefore, I suggest we leave this change for a separate PR.

[1]: https://github.com/angular/angular/blob/523e8fd8a347fd5e56833f8bd27b3d7d57ca5d5b/aio/content/guide/ajs-quick-reference.md?plain=1#L934

2021-11-05 20:57 UTC, dario-piotrowicz commented
> I found only one occurrence where the linking was useful, in [ajs-quick-reference.md](https://github.com/angular/angular/blob/523e8fd8a347fd5e56833f8bd27b3d7d57ca5d5b/aio/content/guide/ajs-quick-reference.md?plain=1#L934). If you could update it to an explicit link, that would be great pray

Done, I added the link there :slightly_smiling_face: (sorry for missing it :sweat_smile:)
(PS: the `number` in the code snippet there doesn't get linked (the other pipes do, is there anything we can do about that? :confused:)

> 
> Regarding `json`: That might be worth investigating further. I don't think `json` would appears much inside code-snippets (so it might be preferable to opt-out of auto-linking in specific instances), but that would require more investigation to determine.
> 
> Therefore, I suggest we leave this change for a separate PR.

Cool, I'll look into that then! :slightly_smiling_face::+1:

2021-11-05 21:13 UTC, gkalpak approved these changes
Thx, @dario-piotrowicz :shipit: 

##
> PS: the number in the code snippet there doesn't get linked (the other pipes do, is there anything we can do about that? 😕)

Nope, there's nothing that we can do :grin:
Auto-linking in code-snippets is supposed to be a nice-to-have, so it is not a big deal. Besides, there are links to the `DecimalPipe` nearby, so it should be easy for the user to get to its API docs.

2021-11-05 21:14 UTC, gkalpak commented
BTW, this needs a final rebase to make CI happy :wink:

2021-11-05 21:19 UTC, dario-piotrowicz commented
> BTW, this needs a final rebase to make CI happy wink

sorry it slipped my mind :sweat_smile:, rebase done :slightly_smiling_face::+1:

2021-11-05 21:23 UTC, dario-piotrowicz commented
> Thx, @dario-piotrowicz :shipit:
> 
> > PS: the number in the code snippet there doesn't get linked (the other pipes do, is there anything we can do about that? confused)
> 
> Nope, there's nothing that we can do grin Auto-linking in code-snippets is supposed to be a nice-to-have, so it is not a big deal. Besides, there are links to the `DecimalPipe` nearby, so it should be easy for the user to get to its API docs.

Yeah... I think that the autolinking it really awesome, but yeah I came to grips with there being some circumstances in which it is quite difficult (or like in this case nearly impossible) to make it perfect (which hurts my OCD :sweat_smile:) :sweat:

2021-11-05 21:27 UTC, mary-poppins commented
You can preview 4c3c863 at https://pr44000-4c3c863.ngbuilds.io/.

2021-11-09 18:03 UTC, atscott commented
This PR was merged into the repository by commit c3b583864ee46d5335652a4c8aec8278b724ee2c.

2021-11-09 18:03 UTC, closed without merging