docs: update link
angular/angular pull request #44017
Opened 2021-11-02 15:15 UTC by josmar-crwdstffng

Update link to match heading.

## PR Checklist

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2021-11-02 17:24 UTC, petebacondarwin requested changes
Thanks for fixing the alignment problem of this anchor.

The redirect should be dropped since it does not have the expected effect.

2021-11-02 17:24 UTC, petebacondarwin commented on aio/firebase.json
> +      {"type": 301, "source": "/guide/upgrade#follow-the-angular-styleguide", "destination": "/guide/upgrade#follow-the-angularjs-style-guide"},
The fragment part of a URL is not sent to the server as part of the request, so firebase will not match this rule. In the worst case, this could even cause an infinite redirect loop depending on whether firebase strips such fragments from the source property.

2021-11-02 17:36 UTC, josmar-crwdstffng commented on aio/firebase.json
> +      {"type": 301, "source": "/guide/upgrade#follow-the-angular-styleguide", "destination": "/guide/upgrade#follow-the-angularjs-style-guide"},
@petebacondarwin 
Is there a fix to align with https://datatracker.ietf.org/doc/html/rfc3986 and https://www.w3.org/Protocols/HTTP/Fragment/draft-bos-http-redirect-00.txt?

All of my firebase searches return to the following article.
https://firebase.google.com/docs/hosting/full-config

This article discusses the use of the location header field to inherit the fragment.
https://stackoverflow.com/questions/2286402/url-fragment-and-302-redirects

The previous article references the following rfc.
https://www.rfc-editor.org/rfc/rfc7231

2021-11-03 09:03 UTC, petebacondarwin commented on aio/firebase.json
> +      {"type": 301, "source": "/guide/upgrade#follow-the-angular-styleguide", "destination": "/guide/upgrade#follow-the-angularjs-style-guide"},
This is a feature of how the browser works - not something that Angular has any control over.

From https://www.w3.org/Protocols/HTTP/Fragment/draft-bos-http-redirect-00.txt

> A client that is retrieving this fragment will ask a server for the
> resource "http://www.w3.org/TR/REC-xml-names" and will then locate
> the fragment "NT-NCName" in that resource.

The point is that the client (the browser) does not send the fragment to the server as part of the request. So the server cannot use that information to do a redirect.

2021-11-03 15:17 UTC, josmar-crwdstffng commented on aio/firebase.json
> +      {"type": 301, "source": "/guide/upgrade#follow-the-angular-styleguide", "destination": "/guide/upgrade#follow-the-angularjs-style-guide"},
@petebacondarwin 
Thank you for the clarification.
I removed the redirect and the test for the redirect.
I will reach out to discuss this more as time permits.

2021-11-03 15:27 UTC, mary-poppins commented
You can preview e080c1d at https://pr44017-e080c1d.ngbuilds.io/.

2021-11-03 15:36 UTC, mary-poppins commented
You can preview 4e98a32 at https://pr44017-4e98a32.ngbuilds.io/.

2021-11-04 15:02 UTC, aikidave approved these changes
Reviewed-for: global-docs-approvers

2021-11-06 12:58 UTC, petebacondarwin approved these changes

2021-11-08 17:00 UTC, atscott commented
This PR was merged into the repository by commit 36e75d3ddb5f579c26435ddba76b4e8fe79bca1c.

2021-11-08 17:00 UTC, closed without merging