docs: improve consuming partial-Ivy code outside the Angular CLI
angular/angular pull request #44027
Opened 2021-11-03 08:11 UTC by alan-agius4

With this change we add an example of how to consume the linker plugin and also clean up the parts of this section.

Closes #44026

2021-11-03 08:20 UTC, mary-poppins commented
You can preview a500fd8 at https://pr44027-a500fd8.ngbuilds.io/.

2021-11-03 08:25 UTC, petebacondarwin requested changes
Looks good @alan-agius4.
We are trying to avoid adding inline code snippets to the docs.
Do you need any help moving this to an external example?

2021-11-03 09:32 UTC, mary-poppins commented
You can preview 8028832 at https://pr44027-8028832.ngbuilds.io/.

2021-11-03 10:06 UTC, mary-poppins commented
You can preview 92471a9 at https://pr44027-92471a9.ngbuilds.io/.

2021-11-03 12:19 UTC, mary-poppins commented
You can preview 3472e54 at https://pr44027-3472e54.ngbuilds.io/.

2021-11-03 15:31 UTC, petebacondarwin approved these changes
Great work @alan-agius4 thanks.
Strictly the second commit should probably be a `build(docs-infra): ...` but won't block the merge over it.

2021-11-03 15:39 UTC, gkalpak commented on aio/tools/transforms/examples-package/services/region-parser.js
> +    mjs: inlineCOnly,
OOC, why not `inlineC`?

2021-11-03 15:41 UTC, alan-agius4 commented on aio/tools/transforms/examples-package/services/region-parser.js
> +    mjs: inlineCOnly,
Because of the docs plaster comment, looks neater using `// …` IMHO.

2021-11-03 16:39 UTC, atscott approved these changes

2021-11-04 18:55 UTC, atscott commented
This PR was merged into the repository by commit 36388b3ab23578151d7edad5106a26af69bcb45e.

2021-11-04 18:55 UTC, closed without merging