docs: document `ng update` support guarantees
angular/angular pull request #44142
Opened 2021-11-10 23:57 UTC by dgp1130

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Documentation content changes\

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

This adds explicit documentation about official support for `ng update`, which is a bit awkward since it upgrades between two versions. It specifically calls out two aspects:

1. `ng update` can only update across one major version at a time. The CLI should enforce this at run time, but it's good to document this more officially anyways.
2. Updating from an unsupported version is ok as long as it is updating to a supported version. This clarifies which of the two versions (current vs destination of the update) is relevant for determining the support level.

2021-11-18 01:11 UTC, jelbourn approved these changes
LGTM for content, though one of the tech writers should weigh in on structure

2021-11-19 05:49 UTC, alan-agius4 approved these changes

2021-11-19 16:28 UTC, aikidave commented on aio/content/guide/releases.md
> +supported.
This paragraph is a bit confusing. What are we trying to tell users? Is it that you can update between any two versions of Angular, so long as both versions are still supported?

2021-11-19 20:28 UTC, dgp1130 commented on aio/content/guide/releases.md
> +supported.
I'm trying to say that you can update between two versions provided that the version you are upgrading **to** is supported. This is confusing so I tried to give this a more specific example. Happy to change this if you have any thoughts about how to make it more clear?

2021-11-22 16:47 UTC, aikidave requested changes
Did a rewrite of your second paragraph to try to help clarify the meaning. Let me know what you think.

2021-11-22 16:47 UTC, aikidave commented on aio/content/guide/releases.md
> +supported.
```suggestion
You can use `ng update` to any version of Angular, provided that the following criteria are met:

* The version you want to update *to* is supported
* The version you want to update *from* is within one major version of the version you want to upgrade to

For example, you can update from version 11 to version 12. But you can also update from version 8 to version 9, provided that version 9 is still supported.
```
What about something like this?

2021-11-22 23:08 UTC, dgp1130 commented on aio/content/guide/releases.md
> +supported.
Thanks, I like this a lot. Made some minor syntactic tweaks and added an explanation about how to upgrade multiple majors by migrating individually, since I expect that will be a common question.

I also noticed there was an existing section on `ng update` support. I replaced that section instead of adding a new one.

2021-11-23 00:46 UTC, aikidave reviewed
Looking good! A few minor changes. Some details as to why:

1. Words like "simply" can be construed as condescending and are usually unnecessary anyway.
2. Made the steps to update across multiple versions into a procedure to make it easier to read (and harder to skip. :) )

2021-11-23 00:46 UTC, aikidave commented on aio/content/guide/releases.md
> +version 10 to version 11 *and then* update from version 11 to version 12.
```suggestion
supported. If you want to update across multiple major versions, perform each update one
major version at a time. For example, to update from version 10 to version 12:

1. Update from version 10 to version 11.
1. Update from version 11 to version 12.
```

2021-11-23 00:57 UTC, dgp1130 commented on aio/content/guide/releases.md
> +version 10 to version 11 *and then* update from version 11 to version 12.
Thanks! Updated.

2021-11-23 00:59 UTC, aikidave approved these changes
LGTM!
Reviewed-for: global-docs-approvers

2021-11-24 18:56 UTC, jessicajaniuk commented
This PR was merged into the repository by commit 83bbbd3784991ace4b3ce76db02c75725a6fbdec.

2021-11-24 18:56 UTC, closed without merging