docs: add profanis to GDE resources
angular/angular pull request #44147
Opened 2021-11-11 10:32 UTC by profanis

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-11-11 10:53 UTC, petebacondarwin requested changes
Thanks @profanis

I checked the github and twitter handles. Both are valid. And the website link is good too.

Please can you fix the image size: 

```
Error: The following pictures exceed maximum size limit of 30kb:
  - /home/circleci/ng/aio/content/images/bios/profanis.png
```

2021-11-11 10:53 UTC, petebacondarwin commented on aio/content/marketing/contributors.json
> +    "bio": "Fanis is a Full Stack JavaScript developer, Angular GDE, speaker at meetups, author of the Mastering Angular Reactive Forms, and he constantly creates videos in his YouTube channel to sha
```suggestion
    "bio": "Fanis is a Full Stack JavaScript developer, Angular GDE, speaker at meetups, author of the Mastering Angular Reactive Forms, and he constantly creates videos in his YouTube channel to share his knowledge with others. He also teaches Angular in Code.Hub institute and mentors other developers. When he is not behind a keyboard, he spends time with his lovely daughter and enjoys family time with his wife.",
```

2021-11-12 08:34 UTC, profanis commented on aio/content/marketing/contributors.json
> +    "bio": "Fanis is a Full Stack JavaScript developer, Angular GDE, speaker at meetups, author of the Mastering Angular Reactive Forms, and he constantly creates videos in his YouTube channel to sha
Thanks for the suggestions @petebacondarwin.
I did the changes and then I `git commit --all --fixup HEAD`. 
If this is not OK, I can do an interactive rebase to one commit and force push it

2021-11-12 08:38 UTC, mary-poppins commented
You can preview 2da54de at https://pr44147-2da54de.ngbuilds.io/.

2021-11-12 09:12 UTC, petebacondarwin approved these changes
Spot on @profanis - thanks.

This looks good to me!

2021-11-13 21:10 UTC, twerske approved these changes
Welcome to GDE!

2021-11-15 15:54 UTC, gkalpak commented on aio/content/marketing/contributors.json
> +    "bio": "Fanis is a Full Stack JavaScript developer, Angular GDE, speaker at meetups, author of the Mastering Angular Reactive Forms, and he constantly creates videos in his YouTube channel to sha
Not a native speaker, but I believe you don't need an article before a book name:

```diff
-[...] author of the Mastering Angular Reactive Forms [...]
+[...] author of Mastering Angular Reactive Forms [...]
```

...or:

```diff
-[...] author of the Mastering Angular Reactive Forms [...]
+[...] author of the book 'Mastering Angular Reactive Forms' [...]
```

2021-11-15 16:24 UTC, petebacondarwin commented on aio/content/marketing/contributors.json
> +    "bio": "Fanis is a Full Stack JavaScript developer, Angular GDE, speaker at meetups, author of the Mastering Angular Reactive Forms, and he constantly creates videos in his YouTube channel to sha
Good spot @gkalpak

2021-11-16 09:39 UTC, profanis commented on aio/content/marketing/contributors.json
> +    "bio": "Fanis is a Full Stack JavaScript developer, Angular GDE, speaker at meetups, author of the Mastering Angular Reactive Forms, and he constantly creates videos in his YouTube channel to sha
thanks a lot for this @gkalpak

2021-11-16 09:48 UTC, mary-poppins commented
You can preview 86663f3 at https://pr44147-86663f3.ngbuilds.io/.

2021-11-16 18:50 UTC, gkalpak commented on aio/content/marketing/contributors.json
> +    "bio": "Fanis is a Full Stack JavaScript developer, Angular GDE, speaker at meetups, author of the Mastering Angular Reactive Forms, and he constantly creates videos in his YouTube channel to sha
Any time :smiley:

BTW, git does not recognize fixups of fixups, so all fixup commits must refer to the original (non-fixup) commit.
So, you must change your last commit message:

```diff
-fixup! fixup! docs: add profanis to GDE resources
+fixup! docs: add profanis to GDE resources
```

2021-11-16 20:29 UTC, AndrewKushnir commented
@profanis thanks for the fixup commit. The `lint` CI job is failing due to the commit message (it has 2 `fixup`s there). Could you please merge all commits into one and let us know (by leaving a comment here) once it's done? Thank you.

2021-11-17 10:29 UTC, profanis commented
> @profanis thanks for the fixup commit. The `lint` CI job is failing due to the commit message (it has 2 `fixup`s there). Could you please merge all commits into one and let us know (by leaving a comment here) once it's done? Thank you.

My apologies for this :(
I blindly followed the instructions of this https://github.com/angular/angular/blob/master/CONTRIBUTING.md#reviewing-a-pull-request and didn't spend a minute reading how the fixup commit works.

Lesson learned :)

2021-11-17 10:36 UTC, mary-poppins commented
You can preview cc40ef0 at https://pr44147-cc40ef0.ngbuilds.io/.

2021-11-17 18:32 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 80a90f0ad73de11af7eb0d3af41ba925392508dc.

2021-11-17 18:32 UTC, closed without merging