perf(http): remove IE special status handling and throw JSONP error o…
angular/angular pull request #44354
Opened 2021-12-02 20:30 UTC by diicar

…nly in dev mode

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## What is the current behavior?
Contains a workaround for IE

## What is the new behavior?
- Removed IE special Case handling
- Only throws error message in dev mode

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2021-12-02 20:49 UTC, diicar commented
cla signed

2021-12-03 20:09 UTC, dylhunn commented
It looks like CircleCI failed to run due to a rebase conflict. Can you rebase on master and push again?

2021-12-03 20:14 UTC, dylhunn requested changes
(Needs a rebase and fresh CI run)

2021-12-03 21:41 UTC, diicar commented
conflicts are now resolved.
I updated the description by moving up because of **ci/circleci: lint** . 
Can you please rerun  **ci/circleci: lint**.
Thank you.

2022-01-06 22:56 UTC, alxhub commented on packages/common/http/src/xhr.ts
> +    if (typeof ngDevMode === 'undefined' || ngDevMode) {
This seems like a candidate for @AndrewKushnir's improvements to `RuntimeError` - we could use this to make the actual error message tree-shakable while still catching the issue even in production mode.

2022-01-07 00:41 UTC, AndrewKushnir commented on packages/common/http/src/xhr.ts
> +    if (typeof ngDevMode === 'undefined' || ngDevMode) {
@diicar as Alex mentioned above, we'd like to keep the check, but improve the code by leveraging the `RuntimeError` class and wrapping the error message (which contributes to the payload size the most) in `ngDevMode` check, [see here for an example](https://github.com/angular/angular/commit/67df935b411ca5c79b33dd13c93933c41e8e3ae4#diff-61abe7c733b66d542f4f5bd4365382ab7c6a7a55327e3b7cb09d46b6c376b561R207).

For this PR though, my proposal is to revert that change (just keep the IE-related cleanup) and create a separate PR with the refactoring to the error message. Please let me know (as a reply here) if you have any questions.

2022-01-07 01:47 UTC, diicar commented on packages/common/http/src/xhr.ts
> +    if (typeof ngDevMode === 'undefined' || ngDevMode) {
Thank you guys. 
Reverted the changes.

2022-01-07 10:38 UTC, diicar commented on packages/common/http/src/xhr.ts
> +    if (typeof ngDevMode === 'undefined' || ngDevMode) {
updated the description and squashed the commits into one.

2022-02-03 23:46 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:426256229:BASE:426256276:1643931953310:5fd8bde8).

2022-02-03 23:46 UTC, AndrewKushnir approved these changes

2022-02-03 23:50 UTC, dylhunn approved these changes
reviewed-for: fw-http

2022-02-04 19:27 UTC, AndrewKushnir commented
@dylhunn FYI the TGP is green, this PR is ready to go.

2022-02-04 19:45 UTC, dylhunn commented
This PR was merged into the repository by commit 28393031b10f4dbefab7587c19641e49cb820785.

2022-02-04 19:45 UTC, closed without merging