feat(forms): Allow a FormControl to be reset to its initial value.
angular/angular pull request #44434
Opened 2021-12-10 22:02 UTC by dylhunn

Allow a FormControl to be reset to its initial value. Provide this feature via a new option in a FormControlOptions interface, based on AbstractControlOptions.

This was originally proposed as part of typed forms. As discussed in the GDE session (and after with akushnir/alxhub), it is likely better to just reuse the initial value rather than accepting an additional default.

It is desirable to land this separately in order to reduce the scope of the typed forms PR, and make it a types-only change.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
It is impossible to specify the value to which a control will reset ahead of time.

Issue Number: #13721

## What is the new behavior?
It is now possible to cause a control to reset to its initial value. This will be useful for simplifying the types in strongly typed reactive forms.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-12-11 22:24 UTC, dylhunn commented
Presubmit is green: http://test/OCL:415607582:BASE:415607613:1639173976883:195d84c6

2021-12-11 22:35 UTC, JoostK commented on goldens/public-api/forms/forms.md
> +    resetToInitialValue?: boolean;
Can we reasonably infer whether a control's type needs to include `|null` based on this option? Especially since it's `boolean`, the presence of the field is not sufficient to know that `null` has to be excluded.

2021-12-11 23:38 UTC, dylhunn commented on goldens/public-api/forms/forms.md
> +    resetToInitialValue?: boolean;
Yes, we can! Here is a toy example of how it would work:

```
interface FormControlOptions {
  resetToDefault?: boolean;
}

declare interface FormControl<T> {
}

declare class FormControlImpl<T> {
  constructor(value: T, options?: FormControlOptions);
}

declare interface FormControlCtor {
  new<T>(
      value: T,
      options: FormControlOptions & {resetToDefault: true}): FormControl<T>;
  new<T>(
      value: T,
      options?: FormControlOptions): FormControl<T|null>;
}

export const FormControl: FormControlCtor = FormControlImpl as FormControlCtor;

// Usage

const fc = new FormControl(42, {resetToDefault: true});
```

2021-12-11 23:44 UTC, dylhunn commented on goldens/public-api/forms/forms.md
> +    resetToInitialValue?: boolean;
(In the above example, if the compiler can prove that `resetToDefault` is always `true` then you get a `FormControl<T>`. In all other cases, you get `FormControl<T|null>`.)

2021-12-11 23:54 UTC, JoostK commented on goldens/public-api/forms/forms.md
> +    resetToInitialValue?: boolean;
Thanks! Yeah, it depends on the literal true type being captured.

2021-12-13 17:39 UTC, jessicajaniuk approved these changes
LGTM :cookie:

reviewed-for: public-api

2021-12-13 19:37 UTC, dylhunn commented
@alxhub I renamed the key to `initialValueIsDefault` as you suggested on our call, as well as exporting the `defaultValue` field for public usage.

2021-12-13 19:38 UTC, dylhunn commented on packages/forms/src/model.ts
> +  _resetToValue: any = null;
Done, as well as exporting it.

2021-12-13 19:41 UTC, mary-poppins commented
You can preview 6f2c319 at https://pr44434-6f2c319.ngbuilds.io/.

2021-12-13 19:48 UTC, mary-poppins commented
You can preview 0c70f88 at https://pr44434-0c70f88.ngbuilds.io/.

2021-12-13 19:52 UTC, AndrewKushnir reviewed
@dylhunn thanks for additional changes 👍 I've left a few more comments.

Could you please also have a look at the commit message to reflect the recent changes (that `defaultValue` is a new public API field)?

2021-12-13 19:52 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +   * defaultValue contains the value that this `FormControl` will reset to.
```suggestion
   * Contains the value that this `FormControl` will reset to.
   * See `initialValueIsDefault` config parameter for additional information.
```

2021-12-13 19:52 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +   * Whether to reset to the initial constructed value of the control.
I think it'd be great to have an example or two (with and without a flag) on how this flag affects the behavior of the `reset` method.

2021-12-13 19:52 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +  defaultValue: any = null;
```suggestion
  readonly defaultValue: any = null;
```

2021-12-13 19:52 UTC, AndrewKushnir commented on packages/forms/test/form_control_spec.ts
> +      expect(c2.value).toBe('foo');
Let's also add some assertions for the `defaultValue` field as well (since it's a part of the public API now).

2021-12-13 20:05 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * defaultValue contains the value that this `FormControl` will reset to.
Done.

2021-12-13 20:05 UTC, dylhunn commented on packages/forms/src/model.ts
> +  defaultValue: any = null;
Done.

2021-12-13 20:05 UTC, dylhunn commented on packages/forms/test/form_control_spec.ts
> +      expect(c2.value).toBe('foo');
Done.

2021-12-13 20:05 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * Whether to reset to the initial constructed value of the control.
Done.

2021-12-13 20:13 UTC, mary-poppins commented
You can preview b7b1bfe at https://pr44434-b7b1bfe.ngbuilds.io/.

2021-12-13 20:23 UTC, mary-poppins commented
You can preview 2b217eb at https://pr44434-2b217eb.ngbuilds.io/.

2021-12-13 20:53 UTC, AndrewKushnir approved these changes
👍

2021-12-13 20:53 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +   * cat.reset(); // cat.value is "tabby"
Thanks for adding examples!
I'd propose adding one more where we pass a value to the `reset` function to illustrate that passed value has a precedence.

2021-12-13 20:53 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +   * @publicApi
```suggestion
   * See `initialValueIsDefault` config parameter for additional information.
   * @publicApi
```

2021-12-13 20:53 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +  override reset(formState: any = this.defaultValue, options: {
Let's also update the docs of this `reset` method to include a reference to the `initialValueIsDefault` config parameter.

2021-12-13 20:54 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2021-12-13 21:13 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * cat.reset(); // cat.value is "tabby"
Done.

2021-12-13 21:13 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * @publicApi
Done.

2021-12-13 21:13 UTC, dylhunn commented on packages/forms/src/model.ts
> +  override reset(formState: any = this.defaultValue, options: {
Done.

2021-12-13 21:23 UTC, mary-poppins commented
You can preview 7a66809 at https://pr44434-7a66809.ngbuilds.io/.

2021-12-13 22:09 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +   * fish.reset('bubble'); // cat.value is "bubble"
```suggestion
   * fish.reset('bubble'); // fish.value is "bubble"
```

2021-12-13 22:09 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +   * the value. The new will be the provided value (if passed), `null`, or the initial value if
Looks like a typo in the sentence?
```suggestion
   * the value. The new value will be the provided one (if passed), `null`, or the initial value if
```

2021-12-13 22:16 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * fish.reset('bubble'); // cat.value is "bubble"
Fixed.

2021-12-13 22:16 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * the value. The new will be the provided value (if passed), `null`, or the initial value if
Fixed.

2021-12-13 22:24 UTC, mary-poppins commented
You can preview 9e60bfa at https://pr44434-9e60bfa.ngbuilds.io/.

2021-12-14 00:40 UTC, mary-poppins commented
You can preview 538b1e0 at https://pr44434-538b1e0.ngbuilds.io/.

2021-12-14 01:31 UTC, mary-poppins commented
You can preview 15e380c at https://pr44434-15e380c.ngbuilds.io/.

2021-12-14 04:50 UTC, dylhunn commented
merge-assistance: test_aio appears to be erroneously failing:

```
Api pages should not show a "Properties" section if there are only internal properties
```

However, the page does have public properties, namely the new `defaultValue` property.

2021-12-14 17:43 UTC, mary-poppins commented
You can preview 71aea55 at https://pr44434-71aea55.ngbuilds.io/.

2021-12-14 18:11 UTC, dylhunn commented
merge-assistance: when this PR is merged, it must be merged after #44479 for the tests to be green.

2021-12-14 20:25 UTC, alxhub requested changes, later dismissed

2021-12-14 20:25 UTC, alxhub commented on packages/forms/src/model.ts
> +   * Whether to reset to the initial constructed value of the control.
The docs here are accurate, but they describe the implementation behavior more than the concept. I took a stab at reframing them to talk more about "default":

> Whether to use the initial value used to construct the `FormControl` as its default value as well. If this option is `false` or not provided, the default value of a `FormControl` is `null`.
>
> When a `FormControl` is reset without an explicit value, its value reverts to its default value.

The example you have here of reset to default value vs explicit value is great, but I think it should go on the docs of the `reset()` method, not the docs of the constructor.

2021-12-14 20:25 UTC, alxhub commented on packages/forms/src/model.ts
> +   * Contains the value that this `FormControl` will reset to.
I attempted to rephrase this too, to focus on the concept instead of the implementation.

> The default value of this `FormControl`, used whenever the control is reset without an explicit value.
>
> See {@link FormControlOptions#initialValueIsDefault} for more information on configuring a default value.

2021-12-14 20:25 UTC, alxhub commented on packages/forms/src/model.ts
> +      this.defaultValue = formState;
Can't `formState` be an object here with a nested value? This seems wrong - default values shouldn't be `FormState`s I would think.

2021-12-14 20:25 UTC, alxhub commented on packages/forms/src/model.ts
> +   * if `initialValueIsDefault` was set in the constructor via {@link FormControlOptions}.
These docs would be a great place for the example above.

2021-12-14 20:34 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * Whether to reset to the initial constructed value of the control.
I went ahead and adopted this change, and moved the examples.

2021-12-14 20:35 UTC, dylhunn commented on packages/forms/src/model.ts
> +      this.defaultValue = formState;
Nice catch! I have added a check for `formState`, as well as a test to verify it's handled properly.

2021-12-14 20:35 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * if `initialValueIsDefault` was set in the constructor via {@link FormControlOptions}.
I have moved the example!

2021-12-14 20:35 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * Contains the value that this `FormControl` will reset to.
I have merged this rephrasing.

2021-12-14 20:42 UTC, mary-poppins commented
You can preview 685b8af at https://pr44434-685b8af.ngbuilds.io/.

2021-12-14 20:49 UTC, AndrewKushnir approved these changes

2021-12-14 20:49 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +   * When a FormControl is reset without an explicit value, its value reverts to its default value.
May be we can add a link to the `reset` function (to get more info and see examples)?

2021-12-14 20:49 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +      }
Great catch 👍 I didn't mention this since there is a handling for the "boxed value" in the `reset` function (within `_applyFormState` code), but it would also update the disabled status, which is something we need to avoid (so special handling makes sense here).

2021-12-14 20:49 UTC, AndrewKushnir commented on packages/forms/test/form_control_spec.ts
> +      const c2 = new FormControl({value: 'foo', disabled: false}, {initialValueIsDefault: true});
Let's also add a quick test with a "boxed value" and `disabled: true` to make sure that we do not reset the disabled state as well:

```
const c3 = new FormControl({value: 'foo', disabled: true}, {initialValueIsDefault: true});

expect(c3.status).toBe('DISABLED');

c3.enable();
c3.reset();

expect(c3.value).toBe('foo');
expect(c3.defaultValue).toBe('foo');
expect(c3.status).toBe('VALID'); // enabled
```

2021-12-14 21:00 UTC, dylhunn commented on packages/forms/test/form_control_spec.ts
> +      const c2 = new FormControl({value: 'foo', disabled: false}, {initialValueIsDefault: true});
Done.

2021-12-14 21:00 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * When a FormControl is reset without an explicit value, its value reverts to its default value.
Done.

2021-12-14 21:18 UTC, dylhunn commented
(Rebased and all comments addressed)

2021-12-14 21:47 UTC, dylhunn commented
@alxhub I just did one last push with all the comments addressed!

2021-12-14 21:55 UTC, mary-poppins commented
You can preview 2a1cd13 at https://pr44434-2a1cd13.ngbuilds.io/.

2021-12-14 22:06 UTC, mary-poppins commented
You can preview 3ab141c at https://pr44434-3ab141c.ngbuilds.io/.

2021-12-15 04:20 UTC, mary-poppins commented
You can preview 831a87f at https://pr44434-831a87f.ngbuilds.io/.

2021-12-15 15:36 UTC, alxhub commented
This PR was merged into the repository by commit 72092ebd26d6670a7dd02f6db5515d2afd27c4d6.

2021-12-15 15:36 UTC, closed without merging