fix(common) unused return value from attemptFocus
angular/angular pull request #44457
Opened 2021-12-12 18:24 UTC by Dok11

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:

## What is the current behavior?

The function `attemptFocus` had a return value that nowhere is used. But it still saves in the bundle as:

```js
attemptFocus(e){return e.focus(),this.document.activeElement===e}
```

## What is the new behavior?

And after this small optimization we can fit it to simple (save 39 chars in the each main.js bundle):
```js
attemptFocus(e){e.focus()}
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2021-12-12 18:55 UTC, dario-piotrowicz commented
Looks good to me :slightly_smiling_face: 

But I am wondering, was it supposed to be used or anything? (for example to provide a warning in dev mode? :thinking:)

@atscott I think you added the function in PR #40241 and even there you were not using the return value, do you remember why? was it just a mistake? or did you add it to make the function more reusable? or were you planning to use it later on? :slightly_smiling_face:

2021-12-13 11:28 UTC, Dok11 commented
And it feels strange. The private method, which calls only once, is still saved as an external method.
What I mean, currently in the bundle, we have this code:
```
// ...
t&&(this.scrollToElement(t),
this.attemptFocus(t))

// ...

attemptFocus(e){e.focus()}
```

While this method is used only one time, we can change it in theory to:
```
t&&(this.scrollToElement(t),
t.focus()
```

Is it needed to extract one code line into a separate method? :)

2021-12-13 23:02 UTC, AndrewKushnir commented
@Dok11 thanks for the cleanup 👍 I'm adding @atscott as a reviewer, so he can provide more info.
If the code is needed, we can still make an improvement by adding a comment to explain why it's needed.

2021-12-16 18:29 UTC, atscott requested changes
The return value was more of a future-proofing in case we were to implement more robust focusing. You can remove this function altogether, but please copy the context in the function documentation to the calling location (specifically, the links to the specs on focus behavior)

2021-12-16 22:16 UTC, Dok11 commented
> You can remove this function altogether, but please copy the context in the function documentation to the calling location (specifically, the links to the specs on focus behavior)

Ok, thanks, I did it. Check, please

2021-12-16 22:22 UTC, atscott approved these changes

2021-12-16 22:22 UTC, atscott commented
LGTM!

2022-01-21 19:56 UTC, AndrewKushnir commented
@Dok11 sorry for the delay. I've rebased this PR and changed the commit message a bit (changed `fix(common)` -> `refactor(common)`). We've also started [tests in Google's codebase](http://test/OCL:423374058:BASE:423374076:1642794879072:1dc049cb) and if they are "green", we'll proceed with merging.

Thanks for contributing to Angular!

2022-01-21 21:11 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 80467c3aa522296d3b3098145fca1c767a9f5396.

2022-01-21 21:11 UTC, closed without merging