refactor(docs-infra): fix template eslint issues in aio examples
angular/angular pull request #44557
Opened 2021-12-23 17:44 UTC by dario-piotrowicz

the aio examples have various eslint issues regarding template rules, those
are currently turned off and TODO comments have been added to them in the
examples eslintrc, fix such issues and remove the respective TODO comments

this also includes examples refactoring to use buttons for better accessibility,
this change tries to make the smallest amound of changes to the examples' behaviors
and designs/UI

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Issue
Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
@gkalpak 😃 👍

2021-12-23 17:52 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/hero-list-page.component.css
> -  text-align: right;
I made this change here, but in other instances I've kept the relative positioning 🤔 

probably I should update them all in the same way for consistency sake

(unfortunately they are not all like 100% the same... it's such a shame we have such code repetition around the heroes list 😓 )

2021-12-23 17:52 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/hero-list-page.component.css
> +  line-height: 1em;
I copy pasted this block of code from somewhere else, I kept the backround-color and the line-height from there to have a more consisteny styling 🙂 

(ps: missing space after the background-color colon, need to fix it)

2021-12-23 17:52 UTC, dario-piotrowicz commented on aio/content/examples/docs-style-guide/src/app/app.component.css
> +/* HeroesComponent's private CSS styles */
to remove

2021-12-23 17:52 UTC, dario-piotrowicz commented on aio/content/examples/router/src/app/admin/admin-dashboard/admin-dashboard.component.2.html
> -<a id="anchor"></a>
I could not figure out why this was here and what for 😓 , does someone know? 🙂

2021-12-23 17:52 UTC, dario-piotrowicz commented on aio/content/examples/router/src/app/admin/admin-dashboard/admin-dashboard.component.html
> -<a id="anchor"></a>
I could not figure out why this was here and what for 😓 , does someone know? 🙂

2021-12-23 17:52 UTC, dario-piotrowicz commented on aio/content/examples/toh-pt2/src/app/heroes/heroes.component.html
> +      <span class="badge">{{hero.id}}</span> {{hero.name}}
missing indentation 😓

2021-12-23 17:52 UTC, dario-piotrowicz commented on aio/content/examples/toh-pt3/src/app/heroes/heroes.component.html
> +      <span class="badge">{{hero.id}}</span> {{hero.name}}
missing indentation 😓

2021-12-23 17:53 UTC, dario-piotrowicz commented
Note: for `img` with missing `alt`, I’ve added those most of the time, hopefully it doesn’t make the examples less clear (if you think it does please let me know and I will just add eslint disable comments instead)

I’ve just disable those eslint errors in a couple of places where I felt that adding an `alt` would make the example less clear

2021-12-23 20:10 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/hero-list-page.component.css
> -  text-align: right;
I've updated most of the heroes lists to follow this pattern (instead of a relative positioning and negative left and top, I've defined a flex container and used that to position the badge)

not all use heroes list use this pattern and not all are identical, but most of them are very similar, so hopefully this should be ok consistency wise 🙂

2021-12-24 22:59 UTC, dario-piotrowicz commented on aio/content/examples/architecture/src/app/hero-list.component.1.html
>  <li (click)="selectHero(hero)"></li>
I'm not completely sure what this is for.... so I figured I could just ignore the line to be on the safe side 😓

2021-12-24 23:04 UTC, dario-piotrowicz commented on aio/content/examples/toh-pt2/src/app/heroes/heroes.component.1.html
>  <li *ngFor="let hero of heroes" (click)="onSelect(hero)">
I'm not completely sure what this is for.... so I figured I could just ignore the line to be on the safe side 😓

2021-12-27 10:39 UTC, dario-piotrowicz commented
@gkalpak just wanted to ask you, I had to change some protractor tests in this PR, this made me wonder, since protractor is on its way out, should be maybe look into re-implementing the e2es with some other tool? 🙂 

> I would love to help in that if I can 🙂  (btw I've got Cypress experience and I do think it is a great tool nice to work with 😄 )

2022-01-04 17:51 UTC, mary-poppins commented
You can preview 695fd55 at https://pr44557-695fd55.ngbuilds.io/.
You can preview 6ba979d at https://pr44557-6ba979d.ngbuilds.io/.
You can preview 9668614 at https://pr44557-9668614.ngbuilds.io/.
You can preview 770211b at https://pr44557-770211b.ngbuilds.io/.
You can preview ae5eacb at https://pr44557-ae5eacb.ngbuilds.io/.
You can preview 31bd056 at https://pr44557-31bd056.ngbuilds.io/.
You can preview d1f792b at https://pr44557-d1f792b.ngbuilds.io/.
You can preview a6cdc2b at https://pr44557-a6cdc2b.ngbuilds.io/.
You can preview 441f4b8 at https://pr44557-441f4b8.ngbuilds.io/.
You can preview 5201481 at https://pr44557-5201481.ngbuilds.io/.
You can preview 0f2126d at https://pr44557-0f2126d.ngbuilds.io/.
You can preview cc64142 at https://pr44557-cc64142.ngbuilds.io/.
You can preview 2bac073 at https://pr44557-2bac073.ngbuilds.io/.
You can preview c4195a6 at https://pr44557-c4195a6.ngbuilds.io/.
You can preview ba6fcc1 at https://pr44557-ba6fcc1.ngbuilds.io/.
You can preview 7c0971b at https://pr44557-7c0971b.ngbuilds.io/.

2022-01-04 20:33 UTC, dylhunn approved these changes
This is too large for me to review all changes line-by-line, but the general impact looks really good. Let me know if you'd like eyes on anything specific in detail.

reviewed-for: fw-core, fw-forms, fw-http, fw-platform-server, fw-testing, docs-observables

2022-01-04 21:08 UTC, dario-piotrowicz commented
> This is too large for me to review all changes line-by-line, but the general impact looks really good. Let me know if you'd like eyes on anything specific in detail. You'll still need other approvals for other areas.
> 
> reviewed-for: fw-core, fw-forms, fw-http, fw-platform-server, fw-testing, docs-observables

Thank you so very much! 😄 

I think it should be all ok, but since you're asking 😜 , if possible I would love it if you could pick randomly a couple of examples in which I switched `label` to `span` and double check that the example (in stackblitz should be enough I think) does still look good (hopefully exactly the same), I did so for a couple of them, if anyone could also do the same for another random couple that'd be great 😄  (but I did check the code and it should indeed be fine, unless there's some quite hidden(/up the chain css) that targets specifically labels that I've missed)

2022-01-06 01:16 UTC, jessicajaniuk requested changes
Overall this looks great, @dario-piotrowicz. My only concern is the alt tags. Can you address those?

2022-01-06 01:16 UTC, jessicajaniuk commented on aio/content/examples/template-syntax/src/app/app.component.html
> +<!-- eslint-disable @angular-eslint/template/accessibility-alt-text -->
Rather than disabling alt text here, can we just create some that's relevant? Like `interpolated image of {{currentHero.name}}` would work.

2022-01-06 01:16 UTC, jessicajaniuk commented on aio/content/examples/template-syntax/src/app/app.component.html
> +<!-- eslint-disable @angular-eslint/template/accessibility-alt-text -->
Can we just add some alt text here?

2022-01-06 01:16 UTC, jessicajaniuk commented on aio/content/examples/property-binding/src/app/app.component.html
> +  <p><img alt="item" src="{{itemImageUrl}}"> is the <i>interpolated</i> image.</p>
If we know the item, can we make sure these two alt tags are unique? We could put something like `item {{item.name}}` interpolated image`. I don't know if that property is there, but that ensure we don't have 3 images with `item` as the alt text.

2022-01-06 01:16 UTC, jessicajaniuk commented on aio/content/examples/interpolation/src/app/app.component.html
> +  <img alt="item" [src]="itemImageUrl2">
We should ensure that two images on the same page don't have the same alt text.

2022-01-07 22:12 UTC, dario-piotrowicz commented on aio/content/examples/property-binding/src/app/app.component.html
> +  <p><img alt="item" src="{{itemImageUrl}}"> is the <i>interpolated</i> image.</p>
the `itemImageUrl` is always the same, so it doesn't make sense for the `alt` to be the same as well? (since the image is always supposed to be the same) :thinking:

2022-01-07 22:17 UTC, dario-piotrowicz commented on aio/content/examples/interpolation/src/app/app.component.html
> +  <img alt="item" [src]="itemImageUrl2">
I just put `"item 2"` as the alt, I hope it makes enough sense given that the image url ends with 2 :slightly_smiling_face:

2022-01-07 22:24 UTC, mary-poppins commented
You can preview fad8f03 at https://pr44557-fad8f03.ngbuilds.io/.

2022-01-07 22:27 UTC, dario-piotrowicz commented on aio/content/examples/template-syntax/src/app/app.component.html
> +<!-- eslint-disable @angular-eslint/template/accessibility-alt-text -->
I am afraid that would just make the examples more confusing

I am not totally sure what the first example is showing, but it does seem to be specific to only `src` so adding an `alt` would just risk to make things less clear

the second example shows the difference between the property binding `[src]` and the attribute binding `[attr.src]` here even more I believe that throwing alts in the mix would make things more confusing (we could add `[alt]` and `[attr.alt]` but it doesn't really seem very clear to me what's going on)

so I am not really sure, I would prefer not put `alt`s here, what do you think? :sweat: 

Also, alternatively if we want to bind a single property/attribute I think that the element doesn't actually need to necessarily be the an `img`, for example instead of having images we could have an `input` and compare `[type]` to `[attr.type]`, couldn't we? :thinking:

2022-01-07 22:41 UTC, mary-poppins commented
You can preview 358151a at https://pr44557-358151a.ngbuilds.io/.

2022-01-11 11:22 UTC, gkalpak requested changes
Amazing work getting all these errors fixed, @dario-piotrowicz 🥇
I just left a few (mostly minor) comments.

The CSS duplication is indeed not great, but I don't think we can do much about it (and definitely not as part of this PR - the duplication was there before). FWIW, we have a [common stylesheet][1] that is included in all examples, but I am not sure the style changes in this PR are generic enough to be included there.

[1]: https://github.com/angular/angular/blob/af2a1317cbfba985233f510bbe9e49016968307c/aio/tools/examples/shared/boilerplate/common/src/styles.css

2022-01-11 11:22 UTC, gkalpak commented on aio/content/guide/binding-syntax.md
> +      <code>alt</code>, <code>src</code>, <code>hero</code>, and <code>ngClass</code> in the following:
:100:

2022-01-11 11:22 UTC, gkalpak commented on aio/content/examples/interpolation/src/app/app.component.html
> +    <div><img alt="item" src="{{itemImageUrl}}"></div>
Nit: Maybe use "The first item."/"The second item." as alt text?

2022-01-11 19:42 UTC, dario-piotrowicz commented on aio/content/examples/router/src/app/admin/admin-dashboard/admin-dashboard.component.html
> -<a id="anchor"></a>
ah ok sorry I missed that :sweat: , I'll revert this change then :slightly_smiling_face:

2022-01-11 19:45 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/hero-list-groups.component.ts
> +        width: '*',
it was to fix some small visual issue if I remember correctly :thinking:

I'll look into that and give you more details :slightly_smiling_face:

2022-01-11 19:45 UTC, dario-piotrowicz commented on aio/content/examples/docs-style-guide/src/app/app.component.html
> +  <div><span>id: </span>{{selectedHero.id}}</div>
yeah good point! :stuck_out_tongue_winking_eye:

2022-01-11 19:47 UTC, dario-piotrowicz commented on aio/content/examples/hierarchical-dependency-injection/src/app/hero-tax-return.component.html
> +    <span>
yeah.... doesn't seem right, I may have just changed it by mistake with the rest present in the file, sorry! :sweat: 

I'll double check it and revert it back :slightly_smiling_face::+1:

2022-01-11 19:50 UTC, dario-piotrowicz commented on aio/content/examples/toh-pt2/src/app/heroes/heroes.component.1.html
> +<!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events -->
ahhh, I didn't know! :sweat: 

thanks so much, I'll double check and make sure they do match :slightly_smiling_face::+1:

2022-01-11 20:09 UTC, dario-piotrowicz commented on aio/content/examples/docs-style-guide/src/app/app.component.html
> +  <div><span>id: </span>{{selectedHero.id}}</div>
PS: below it should actually be a `label` associated to that input :slightly_smiling_face:

2022-01-11 20:18 UTC, dario-piotrowicz commented on aio/content/examples/testing/src/app/hero/hero-list.component.spec.ts
>         // https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill
@gkalpak I think this comment can be removed ([caniuse Event](https://caniuse.com/mdn-api_event_event)) what do you think? :slightly_smiling_face:

2022-01-11 20:26 UTC, dario-piotrowicz commented on aio/content/examples/testing/src/app/hero/hero-list.component.spec.ts
>         // https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill
(same for the same comment above)

2022-01-11 20:36 UTC, mary-poppins commented
You can preview 1ad40aa at https://pr44557-1ad40aa.ngbuilds.io/.

2022-01-11 20:50 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/hero-list-groups.component.ts
> +        width: '*',
Ok, `120` is an hardcoded value and doesn't work very well, this is how the thing actually currently looks in the aio live example:
![currently](https://user-images.githubusercontent.com/61631103/149019114-321f10ec-cab3-4842-a19f-abee14ef607e.gif)
as you can see using `*` (which relies on the current width of the element instead of providing a hardcoded value) works much better

Furthermore I am actually updating the styles in order to make the various heroes lists consistent looking so with my changes this is what the thing looks like:
![withmychange](https://user-images.githubusercontent.com/61631103/149019410-c9418d7d-c19c-4c88-a029-1e55393cfde3.gif)

:slightly_smiling_face:

2022-01-11 21:39 UTC, dario-piotrowicz commented on aio/content/examples/upgrade-phonecat-1-typescript/app/phone-detail/phone-detail.template.html
> +  <img ng-src="{{img}}" class="phone" alt="phone {{$index}}"
@gkalpak I am not too sure what to use here as `alt`s :confused: 

this first list and the one below seem to be of the same images (for the same phone), I think the first just shows all the images and styles the selected one differently

below instead the same list is used to actually select the image.... `phone {{$index}}` and `phone thumb {{$index}}` aren't really appropriate.... but do you have any suggestion?

PS: since the images are the same I guess also the alts should be the same, maybe something like: `phone view ${{index}}`? how does that sound? :slightly_smiling_face:

2022-01-11 21:39 UTC, mary-poppins commented
You can preview 64fc9b0 at https://pr44557-64fc9b0.ngbuilds.io/.

2022-01-11 21:40 UTC, dario-piotrowicz commented on aio/content/examples/upgrade-phonecat-1-typescript/app/phone-detail/phone-detail.template.html
> +  <img ng-src="{{img}}" class="phone" alt="phone {{$index}}"
( Here and in the files below too of course :slightly_smiling_face: )

2022-01-11 21:48 UTC, dario-piotrowicz commented on aio/content/examples/interpolation/src/app/app.component.html
> +    <div><img alt="item" src="{{itemImageUrl}}"></div>
mh... I am not completely sure, the fact is that they are a bit far apart ([aio link](https://angular.io/guide/interpolation#displaying-values-with-interpolation))

so when someone first reads the `Displaying values with interpolation` they do not see the two items there and could look a bit strange to just see a "The first item" without a second one

But that may just be my opinion, I can use your proposed alt text if you do prefer that version :slightly_smiling_face:

2022-01-11 21:49 UTC, dario-piotrowicz commented on aio/content/examples/router/src/app/admin/admin-dashboard/admin-dashboard.component.html
> -<a id="anchor"></a>
I've putted it back but as a `div` :slightly_smiling_face:

2022-01-11 22:16 UTC, dario-piotrowicz commented on aio/content/examples/toh-pt2/src/app/heroes/heroes.component.1.html
> +<!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events -->
yeah I had it quite differently, I've fixed this so that it looks like the final version of the file and updated the aio toh guide accordingly :slightly_smiling_face: 

(PS: in the toh I am saying to add a `button` with the click event binding instead of saying to add the event binding to the `li` element, I would like to also add an alert or callout saying that for accessibility it is generally better to use `button` elements instead of having `click` event bindings assigned to other elements, but that may be a bit out of place in the toh, what do you think?)

2022-01-11 22:18 UTC, mary-poppins commented
You can preview 791e02c at https://pr44557-791e02c.ngbuilds.io/.

2022-01-11 22:35 UTC, mary-poppins commented
You can preview 132c4a3 at https://pr44557-132c4a3.ngbuilds.io/.

2022-01-12 19:03 UTC, gkalpak commented on aio/content/examples/animations/src/app/hero-list-groups.component.ts
> +        width: '*',
Thx for the detailed comment :100:

2022-01-12 19:06 UTC, gkalpak commented on aio/content/examples/testing/src/app/hero/hero-list.component.spec.ts
>         // https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill
Agreed :+1:

2022-01-12 19:09 UTC, gkalpak commented on aio/content/examples/toh-pt2/src/app/heroes/heroes.component.1.html
> +<!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events -->
I'm on the fence on that too. Whatever you think is best 😅

2022-01-12 19:15 UTC, gkalpak commented on aio/content/examples/upgrade-phonecat-1-typescript/app/phone-detail/phone-detail.template.html
> +  <img ng-src="{{img}}" class="phone" alt="phone {{$index}}"
Couldn't we use the phone's name here?

2022-01-12 19:15 UTC, gkalpak commented on aio/content/examples/interpolation/src/app/app.component.html
> +    <div><img alt="item" src="{{itemImageUrl}}"></div>
I don't feel strongly about it, so up to you.

2022-01-12 19:17 UTC, gkalpak requested changes

2022-01-12 19:17 UTC, gkalpak commented on aio/content/examples/router/src/app/admin/admin-dashboard/admin-dashboard.component.2.html
> +<div id="anchor"></div>
This whole file doesn't seem to be used, so I think it can be removed altogether.

2022-01-12 19:44 UTC, dario-piotrowicz commented on aio/content/examples/router/src/app/admin/admin-dashboard/admin-dashboard.component.2.html
> +<div id="anchor"></div>
ah wow, you're right! :open_mouth::+1:

2022-01-12 19:47 UTC, dario-piotrowicz commented on aio/content/examples/architecture/src/app/hero-list.component.1.html
>  <li (click)="selectHero(hero)"></li>
yeah I know understand the numbering in the filenames :sweat_smile: 

this doesn't align with the full file so I need to update it :+1:

2022-01-12 19:55 UTC, dario-piotrowicz commented on aio/content/examples/upgrade-phonecat-1-typescript/app/phone-detail/phone-detail.template.html
> +  <img ng-src="{{img}}" class="phone" alt="phone {{$index}}"
I don't think so :sweat: 

this is the application on a random phone I just picked: [phonecat motorola](http://angular.github.io/angular-phonecat/step-14/app/#!/phones/motorola-xoom-with-wi-fi)

As you can see:
![Screenshot at 2022-01-12 19-53-19](https://user-images.githubusercontent.com/61631103/149211914-231d26ee-fbe7-4680-b260-bb726f292b5e.png)

The images are all of the same phone so it wouldn't make much sense to just use the same exact `alt` (the phone's name) for all of them, right? :thinking:

2022-01-12 19:56 UTC, mary-poppins commented
You can preview 72173ae at https://pr44557-72173ae.ngbuilds.io/.

2022-01-12 19:59 UTC, dario-piotrowicz commented on aio/content/examples/interpolation/src/app/app.component.html
> +    <div><img alt="item" src="{{itemImageUrl}}"></div>
I don't feel strongly about it either :stuck_out_tongue_winking_eye: , but I do slightly prefer it with the number, so I guess if you're ok with it I'll keep it as it is :slightly_smiling_face:

(unless @jessicajaniuk thinks otherwise :slightly_smiling_face:)

2022-01-12 20:37 UTC, mary-poppins commented
You can preview 633bb35 at https://pr44557-633bb35.ngbuilds.io/.

2022-01-12 20:39 UTC, dario-piotrowicz commented on aio/content/examples/toh-pt2/src/app/heroes/heroes.component.1.html
> +<!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events -->
I've tried adding an alert ([link](https://pr44557-633bb35.ngbuilds.io/tutorial/toh-pt2#add-a-click-event-binding)) I am not totally convinced.... what do you think? :confused:

2022-01-12 21:57 UTC, dario-piotrowicz commented on aio/content/guide/architecture-components.md
> +
I changed this to keep the order or the binding in the code and in the list

before:
[![Screenshot at 2022-01-12 21-54-24](https://user-images.githubusercontent.com/61631103/149229056-212f9c5a-d231-47fa-914e-37ee2f0220f4.png)](https://angular.io/guide/architecture-components#data-binding)

after:
[![Screenshot at 2022-01-12 21-53-43](https://user-images.githubusercontent.com/61631103/149229068-6d07e7a3-4383-4e46-aff4-9de80325f1a5.png)](https://pr44557-fc99d3f.ngbuilds.io/guide/architecture-components#data-binding)

I think it is a bit uglier now, but this was needed in order to keep the button :sweat: 

(alternatively I can just put the eslint disable comment for the li click binding)

@gkalpak what do you think? :slightly_smiling_face: :sweat:

2022-01-13 15:48 UTC, gkalpak commented on aio/content/tutorial/toh-pt2.md
> +<header>Clickable Elements</header>
```suggestion
  <header>Clickable elements</header>
```

2022-01-13 15:48 UTC, gkalpak commented on aio/content/guide/architecture-components.md
> +
I think this seems reasonable. The two `<li>` didn't make much sense (esp. since the second is empty).

2022-01-13 15:48 UTC, gkalpak commented on aio/content/examples/upgrade-phonecat-1-typescript/app/phone-detail/phone-detail.template.html
> +  <img ng-src="{{img}}" class="phone" alt="phone {{$index}}"
Yeah, sorry, I meant use the phone's name in the alt text. Something like "Phone X - thumbnail Y".

2022-01-13 16:22 UTC, gkalpak requested changes
One last comment from me 🚀

2022-01-13 16:22 UTC, gkalpak commented on aio/content/tutorial/toh-pt2.md
> +  `<button>` elements we get all the desired behaviors for free.
I suggest keeping this shorter and focused to clicks (since it is a side-note and targets beginners). How about:

```suggestion
  Note that we added the click event binding on a new `<button>` element. While we could have added
  the event binding on the `<li>` element directly, it is better for accessibility purposes to use
  the native `<button>` element to handle clicks.

  For more details on accessibility, see [Accessibility in Angular](guide/accessibility).
```

2022-01-13 18:55 UTC, dario-piotrowicz commented on aio/content/guide/architecture-components.md
> +
yeah :slightly_smiling_face: 

it was nicer to have 3 lines and 3 bullet points, but hopefully this is just as clear :smile:

2022-01-13 19:02 UTC, dario-piotrowicz commented on aio/content/examples/upgrade-phonecat-1-typescript/app/phone-detail/phone-detail.template.html
> +  <img ng-src="{{img}}" class="phone" alt="phone {{$index}}"
sounds good, thanks :slightly_smiling_face::+1:

2022-01-13 19:13 UTC, mary-poppins commented
You can preview 38d6476 at https://pr44557-38d6476.ngbuilds.io/.

2022-01-13 19:38 UTC, dario-piotrowicz commented
@gkalpak should be all good now :smile: 

as far as I can tell there are only a couple of comments left to address with @jessicajaniuk :slightly_smiling_face:

2022-01-13 19:44 UTC, mary-poppins commented
You can preview 826440d at https://pr44557-826440d.ngbuilds.io/.

2022-01-14 14:09 UTC, gkalpak approved these changes
:tada:

Thx for making all the changes, @dario-piotrowicz!
Amazing work 🚀 :shipit:

2022-01-14 14:09 UTC, gkalpak commented on aio/content/examples/upgrade-phonecat-2-hybrid/app/phone-detail/phone-detail.template.html
> +    <img [src]="img" class="phone" [alt]="'Phone ' + phone.name + ' - thumbnail ' + index"
Nit: I find that the attribute binding would be a little more readable here (and below):

```suggestion
    <img [src]="img" class="phone" alt="Phone {{ phone.name }} - thumbnail {{ index }}"
```

2022-01-14 14:09 UTC, gkalpak commented on aio/content/tutorial/toh-pt2.md
> +  For more details on accessibility, see [Accessibility in Angular](guide/accessibility).
Nit: I'd leave an empty line above this sentence.

2022-01-14 14:11 UTC, gkalpak requested changes

2022-01-14 14:11 UTC, gkalpak commented on aio/content/tutorial/toh-pt2.md
> +<header>Clickable Elements</header>
```suggestion
  <header>Clickable elements</header>
```

2022-01-14 18:27 UTC, dario-piotrowicz commented on aio/content/tutorial/toh-pt2.md
> +  For more details on accessibility, see [Accessibility in Angular](guide/accessibility).
sorry I must removed it by mistake as I copy-pasted your suggestion :sweat:

2022-01-14 18:28 UTC, dario-piotrowicz commented on aio/content/tutorial/toh-pt2.md
> +<header>Clickable Elements</header>
sorry I was pretty sure I already made this change! :bow: :cry:

2022-01-14 18:37 UTC, gkalpak approved these changes
:shipit:

2022-01-14 18:40 UTC, mary-poppins commented
You can preview 5f9125f at https://pr44557-5f9125f.ngbuilds.io/.

2022-01-14 19:23 UTC, mary-poppins commented
You can preview 5436947 at https://pr44557-5436947.ngbuilds.io/.

2022-01-18 23:55 UTC, jessicajaniuk requested changes
Almost there! Just a couple of things.

2022-01-18 23:55 UTC, jessicajaniuk commented on aio/content/examples/http/src/app/heroes/heroes.component.html
> +    <button class="edit" (click)="edit(hero)">
It's invalid HTML to put a text input inside a button. This will need to be re-structured to make it valid.

2022-01-18 23:55 UTC, jessicajaniuk commented on aio/content/examples/template-syntax/src/app/app.component.html
> +<!-- eslint-disable @angular-eslint/template/accessibility-alt-text -->
It depends. If we're actually displaying the image, and not just showing demo code, it may be fine. However skipping alt text violates WCAG accessibility rules. So I'd prefer we have them. We should be demonstrating a11y best practices. So we should have alt text for real images and those alt texts should be clear as to what's in the image disambiguating it from other images and providing context.

2022-01-18 23:55 UTC, jessicajaniuk commented on aio/content/examples/animations/src/app/hero-list-auto.component.html
> +      <button class="inner" (click)="removeHero(hero.id)">
Any time we have a button, we should be defining a type attribute. Can we just mass add `type="button"` to all of these?

2022-01-19 20:07 UTC, dario-piotrowicz commented on aio/content/examples/http/src/app/heroes/heroes.component.html
> +    <button class="edit" (click)="edit(hero)">
Yes and it is slightly awkward from the UI as well

You can check the example here: [server communication example](https://angular.io/guide/example-apps-list#server-communication)

I'd imagine that as it is (an `input` inside an `a`) is just as invalid, so at the very least I am not making things any worse.

I am wondering, would it be ok to keep this as is for this PR and do a more proper rework/cleanup of the example in a separate one? (as I am seeing that this is not the only thing that could be improved there)

2022-01-19 20:18 UTC, dario-piotrowicz commented on aio/content/examples/template-syntax/src/app/app.component.html
> +<!-- eslint-disable @angular-eslint/template/accessibility-alt-text -->
This is just demo code, there isn't actually any valid image assigned to those `img`s as you can see from the example, which you can find here: [template syntax example](https://angular.io/guide/example-apps-list#template-syntax)

this anyways is that it looks like:
![Screenshot at 2022-01-19 20-11-55](https://user-images.githubusercontent.com/61631103/150206637-2f225924-9d37-4202-8c66-ef9efa06c081.png)

So I would actually use different elements with different properties/attributes to try to keep this as similar as possible to the existing example but without violating accessibility rules, what do you think? :slightly_smiling_face:

2022-01-21 22:10 UTC, dario-piotrowicz commented on aio/content/examples/animations/src/app/hero-list-auto.component.html
> +      <button class="inner" (click)="removeHero(hero.id)">
I've added the `type` to all the buttons in the aio examples :smile: 

I had to add them one by one as I needed to check that they didn't already have one and also make sure that the type made sense (there were a couple of times where I was tempted to use the `"reset"` type but at the end of the day those were normal buttons too, just with a sort of reset-like logic)

you can check out the commit :slightly_smiling_face: 
(I made it as a separate commit and not a fixup one as it feels a bit out of the scope of the original one, I hope that's ok :slightly_smiling_face:)

2022-01-21 22:12 UTC, mary-poppins commented
You can preview 899120c at https://pr44557-899120c.ngbuilds.io/.

2022-01-21 22:17 UTC, mary-poppins commented
You can preview 5f50abb at https://pr44557-5f50abb.ngbuilds.io/.

2022-01-21 22:17 UTC, dario-piotrowicz commented
sorry @dylhunn I re-requested your review by mistake :sweat: :bow:

2022-01-21 22:21 UTC, dario-piotrowicz commented
@jessicajaniuk please have another look, most of your comments should be addressed :slightly_smiling_face: 

I think we just need to:
 - sort this conversation out: https://github.com/angular/angular/pull/44557#discussion_r779236631
 - decide if a follow up PR is ok for this: https://github.com/angular/angular/pull/44557#discussion_r787239658

2022-01-21 22:23 UTC, mary-poppins commented
You can preview 64680e5 at https://pr44557-64680e5.ngbuilds.io/.

2022-01-21 22:25 UTC, jessicajaniuk commented on aio/content/examples/template-syntax/src/app/app.component.html
> +<!-- eslint-disable @angular-eslint/template/accessibility-alt-text -->
I think as long as we are doing the alt texts in a way where inside these examples it's distinguishable between images, then I'm ok with it.

2022-01-21 22:27 UTC, jessicajaniuk commented on aio/content/examples/property-binding/src/app/app.component.html
> +  <p><img alt="item" src="{{itemImageUrl}}"> is the <i>interpolated</i> image.</p>
What it's rendering is implying different things here. So I think you can distinguish alt text with "Interpolated item image" and "Property Bound item image" to distinguish between the two in the example. It may be the same URL but the purpose of them is different, and the alt text should convey that.

2022-01-21 22:31 UTC, jessicajaniuk commented on aio/content/examples/http/src/app/heroes/heroes.component.html
> +    <button class="edit" (click)="edit(hero)">
You are correct in that an input inside an anchor tag is just as invalid. So a follow up is fine given the effort. Thanks!

2022-01-21 22:45 UTC, jessicajaniuk commented on aio/content/examples/template-syntax/src/app/app.component.html
> +<!-- eslint-disable @angular-eslint/template/accessibility-alt-text -->
Sorry, I missed the last bit there and was focused on the img code. Yes, we can definitely use different elements.

2022-01-21 22:58 UTC, dario-piotrowicz commented on aio/content/examples/property-binding/src/app/app.component.html
> +  <p><img alt="item" src="{{itemImageUrl}}"> is the <i>interpolated</i> image.</p>
ah ok sure I can go with that :slightly_smiling_face: (without the `Image` part I think because that gets already dictated :thinking:)

2022-01-21 23:13 UTC, dario-piotrowicz commented on aio/content/examples/property-binding/src/app/app.component.html
> +  <p><img alt="item" src="{{itemImageUrl}}"> is the <i>interpolated</i> image.</p>
I made the change I hope I got it right :smiley:

2022-01-24 17:40 UTC, jessicajaniuk commented on aio/content/examples/template-syntax/src/app/app.component.html
> +<!-- eslint-disable @angular-eslint/template/accessibility-alt-text -->
I think I'm just going to say let's move forward as is. I think given where we were before and where we are now is markedly better than we were. We can increment and add effective alt text later.

2022-01-24 17:41 UTC, jessicajaniuk approved these changes
LGTM :cookie:

Thanks for your work, Dario!

2022-01-24 20:54 UTC, dario-piotrowicz commented on aio/content/examples/template-syntax/src/app/app.component.html
> +<!-- eslint-disable @angular-eslint/template/accessibility-alt-text -->
sure :slightly_smiling_face: 

I wanted to check with @petebacondarwin (which I think created the example there) what he thinks about switching to a different HTML element (as in, there is a specific reason/benefit as to why `img`s were used?)

Anyways @jessicajaniuk as you said that can also come as a follow up PR in case :slightly_smiling_face:

2022-02-03 19:41 UTC, AndrewKushnir approved these changes

2022-02-03 19:48 UTC, jessicajaniuk approved these changes
reviewed-for: public-api

2022-02-03 19:52 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2022-02-03 19:54 UTC, jessicajaniuk commented
Caretaker Note: We can ignore the public-api reviews. This PR affects files that are in pull approve for public-api, but just the examples change. Nothing actually changes in the public api.

2022-02-03 20:44 UTC, dylhunn commented
This PR was merged into the repository by commit 0d19be199617b0bf2f65b19bf95a41247978fb8d.

2022-02-03 20:44 UTC, closed without merging