feat(router): take only the first emitted value of every resolver
angular/angular pull request #44573
Opened 2021-12-28 13:49 UTC by dimakuba

For now the router waits for resolvers to complete even they emitted at
least one value. The changes make it possible to take only the first
emitted value of every resolver and proceed the navigation.

2022-01-04 17:13 UTC, atscott requested changes
I certainly don't disagree that this likely _should_ have been written this way in the first place. That said, this change is at the very least a breaking change and will need to wait until the next major version. You'll need to add a `BREAKING CHANGES` footer note to the commit message.

Depending on internal test results, we'll have to determine if this is worth the migration effort. I imagine there should be little to no failures so we should be able to do this, but you never really know until the test results come back.

Also, I think you will need to update the documentation. There are two places that mention that observables must complete in the [tutorial](https://angular.io/guide/router-tutorial-toh). While those mention guards rather than resolvers, I believe that documentation is incorrect or outdated since I see `observable.pipe(first())` in the guard execution code. I thought there was also somewhere that mentions this for resolvers, but I can't find it. Maybe I was thinking of this:  https://github.com/angular/angular/blob/8ebc946c0e7bf80d26ec8268acb4ff0af9e5c34a/aio/content/guide/router-tutorial-toh.md#L2444

2022-01-04 17:13 UTC, atscott commented on packages/router/test/operators/resolve_data.spec.ts
> +        {provide: 'resolveZero', useValue: (a: any, b: any) => interval()},
nit: Given that this doesn't really resolve 0, but is rather an interval, I think this should be renamed.

2022-01-05 00:59 UTC, atscott commented
@dimakuba Can you also explain the rationale behind this change? What does this help or solve? Is it just for consistency with guards?

Because the `Observable` isn't subscribed to and published, this change is functionally just taking the first value rather than the last one before completion. Generally I would expect this change to be a no-op for all existing use-cases. I can't think of an existing use-case that makes sense to emit multiple values with the intent of resolving just the last one. I might categorize this as a `refactor` rather than a `feat` unless you have an example of a feature use-case this change would unlock.

2022-01-05 07:29 UTC, dimakuba commented
> @dimakuba Can you also explain the rationale behind this change? What does this help or solve? Is it just for consistency with guards?
> 
> 
> 
> Because the `Observable` isn't subscribed to and published, this change is functionally just taking the first value rather than the last one before completion. Generally I would expect this change to be a no-op for all existing use-cases. I can't think of an existing use-case that makes sense to emit multiple values with the intent of resolving just the last one. I might categorize this as a `refactor` rather than a `feat` unless you have an example of a feature use-case this change would unlock.

Yes, you're right, this change is mostly for consistency with guards to take only the first emitted value and complete the `Observable` automatically rather then manually for "complete-less" observables.

2022-01-07 00:02 UTC, atscott commented
@dimakuba That's fair and I think this is worth making consistent.

Action items for merging:

- [ ] Please update the docs as mentioned in the previous comment. This should resolve #44643 (while you're at it, please update the sentence mentioned in that bug to say "resolvers" instead of guards).
- [ ] Add "resolves #44643" to the footer of your commit message so that issue is closed when this PR is merged
[ ] Update the commit to be `refactor` rather than `feat`. Another option might be `fix(router):...` but this isn't exactly a bug...
- [ ] Add the breaking changes note in the footer. i.e. "BREAKING CHANGE: previously, resolvers.... with this change, the router now only takes the first value...This is now consistent with `Observables` returned by guards..."
- [ ] Update the commit message to explain why you made this change (i.e. consistency with guards)
- [ ] AI for me: There were 4 failures in the [global presubmit tests](https://fusion2.corp.google.com/presubmit/tap/419612275/OCL:419612275:BASE:419701114:1641341512420:b0140bdb/targets). I'll need to investigate and resolve those before this can be merged.

2022-02-03 18:59 UTC, atscott commented
@dimakuba The main branch is now targeting v14 so we can land this change when the action items are addressed.

2022-02-12 11:09 UTC, dimakuba commented
- [x] Please update the docs as mentioned in the previous comment. This should resolve https://github.com/angular/angular/issues/44643 (while you're at it, please update the sentence mentioned in that bug to say "resolvers" instead of guards).
- [x]  Add "resolves https://github.com/angular/angular/issues/44643" to the footer of your commit message so that issue is closed when this PR is merged
- [x]  Update the commit to be refactor rather than feat. Another option might be fix(router):... but this isn't exactly a bug...
- [x]  Add the breaking changes note in the footer. i.e. "BREAKING CHANGE: previously, resolvers.... with this change, the router now only takes the first value...This is now consistent with Observables returned by guards..."
- [x]  Update the commit message to explain why you made this change (i.e. consistency with guards)
- [ ]  AI for me: There were 4 failures in the [global presubmit tests](https://fusion2.corp.google.com/presubmit/tap/419612275/OCL:419612275:BASE:419701114:1641341512420:b0140bdb/targets). I'll need to investigate and resolve those before this can be merged.

2022-02-12 12:11 UTC, dimakuba commented
@atscott the only last point left to resolve

2022-02-28 22:05 UTC, atscott approved these changes

2022-03-01 17:12 UTC, jessicajaniuk commented
This PR was merged into the repository by commit c9679760b2bf5c607c957c20482b9cea7a21702b.

2022-03-01 17:12 UTC, closed without merging