build: enable useUnknownInCatchVariables for packages
angular/angular pull request #44679
Opened 2022-01-11 00:00 UTC by atscott

This unblocks the internal migration to turn the option on in g3.

2022-01-11 08:17 UTC, alfaproject commented on packages/tsconfig.json
> +    "useUnknownInCatchVariables": true,
You can just remove this now. It's part of `strict` I believe?

2022-01-18 19:48 UTC, atscott commented
[presubmit](https://fusion2.corp.google.com/presubmit/tap/422578754/OCL:422578754:BASE:422578827:1642527876641:804c068b/targets)

2022-01-19 17:23 UTC, dylhunn commented
Labeling this as core to clear it from the triage queue, it doesn't really fit in any single component though.

2022-01-31 21:47 UTC, alxhub requested changes
We should also update `tsconfig-build.json` files as these explicitly override `useUnknownInCatchVariables` to be `false`.

2022-01-31 21:59 UTC, alxhub approved these changes

2022-01-31 23:53 UTC, atscott commented
[presubmit](https://fusion2.corp.google.com/presubmit/tap/421419430/OCL:421419430:BASE:425466167:1643669128016:1aa6c385/targets)

2022-02-01 18:14 UTC, josephperrott approved these changes
LGTM

Approved-for: global-approvers

2022-02-01 18:17 UTC, jessicajaniuk commented
This PR was merged into the repository by commit fdfcef5a0a6187eeffa936de86d780d464178521.

2022-02-01 18:17 UTC, closed without merging