feat(animations): allow animations with unsupported CSS properties
angular/angular pull request #44729
Opened 2022-01-16 11:42 UTC by dario-piotrowicz

currently animations with unsupported CSS properties cause a hard error
and the crash of the animation itself, instead of this behaviour just
ignore such properties and provide a warning for the developer in
the console (only in dev mode)

resolves #23195

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Issue

Issue Number: #23195

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

I don't think it's a breaking change, unless someone was actually in some circumstances relying on the animations crushing when finding unsupported CSS properties :thinking: 

## Other information

You can notice that the warnings I've added are `string`s which is inconsistent with the errors being `any`s, I believe the errors should actually also be strings and I've already opened #44726 to update their type :slightly_smiling_face:

2022-01-18 22:43 UTC, jessicajaniuk reviewed
Thanks, @dario-piotrowicz! I like this a lot. Definitely take a look at the comment below. One thing I've been thinking about as I read this is that there's similar code used every time you output them to `console.warn`. This suggests to me maybe an abstraction makes sense. What do you think?

2022-01-18 22:43 UTC, jessicajaniuk commented on packages/animations/browser/src/dsl/animation_ast_builder.ts
> +          delete tuple[prop];
Deleting properties has a permanent negative impact on performance. Do we need to delete this here?

2022-01-18 22:52 UTC, dario-piotrowicz commented on packages/animations/browser/src/dsl/animation_ast_builder.ts
> +          delete tuple[prop];
Yes I thought the same! :slightly_smiling_face: 

I did actually try not to remove the property and all still worked the same, I thought that the cleanest thing was to just remove the property so that we actually end up with the exact same result as if the property wasn't there in the first place, and figured the negative impact would be negligible

I can definitely remove the `delete` here, but I'll need to investigate things first, I think that something somewhere may still try to use it (and fail), and if that's the case, it could cause unexpected behaviors in some cases or even have a worst performance impact compared to just use the `delete`

Moreover I was thinking that when you land your `Map`s PR this wouldn't be an object `delete` anymore but a Map one which should be totally fine :slightly_smiling_face: 

Anyways let me do a bit of investigation and see if I can figure the impact of keeping the prop lingering :slightly_smiling_face::+1:

2022-01-18 23:04 UTC, dario-piotrowicz commented
> Thanks, @dario-piotrowicz! I like this a lot. Definitely take a look at the comment below. One thing I've been thinking about as I read this is that there's similar code used every time you output them to `console.warn`. This suggests to me maybe an abstraction makes sense. What do you think?

Thanks! :smiley: 

Yes an abstraction would make total sense, the issue is that if you look at the `console.warn`s they are not all the same, I am actually following what the errors do (before each of my `console.warn`s you can see an error being thrown and that I am generating the warning string in the same manner as the error throw).

I am not sure why they are different and figured the safest thing would be to follow that for the introduction of warnings, but I could definitely abstract the console warnings in some reusable way and then we can pick the errors up separately?

or would it make sense to just keep the warnings as they are for this PR and abstract both errors and warnings at the same time in a separate PR? :thinking: 

regardless there are many ways these errors can pop up, I haven't really tried triggering them all, I will have to have an investigation in this too to see if there is a reason we have different formats for errors in different places or not (probably not, but still would be good to have a look around I think :smile:)

2022-01-22 15:37 UTC, dario-piotrowicz commented on packages/animations/browser/src/dsl/animation_ast_builder.ts
> +          delete tuple[prop];
I just checked and the property if not deleted/removed actually gets treated like any other and ends up being applied to the element (of course it does not produce any animation/visual effect since it is not supported anyways):
![Screenshot at 2022-01-22 15-27-33](https://user-images.githubusercontent.com/61631103/150644867-5df8060c-e767-4943-ba2e-8e5911f19d52.png)

this means (I also double checked it) that it passes through params interpolation, prop normalization, and all the various (rather small) steps that each property passes through...

On the other hand the delete I'm adding only occurs once per property (during the trigger initialization), whilst the aforementioned operation occur for any transition/animation (/when necessary)

So I am not actually sure what would be the best solution, what do you think? :thinking: 

By the way, one solution could also be to remove the `delete` and add a Todo comment referring to your Maps PR (#44482) and saying that when that one lands a delete should be added here (as it would be quite more efficient at that point, right? :thinking:)

2022-01-22 17:24 UTC, dario-piotrowicz commented
@jessicajaniuk I've looked into the errors and they are all just results of `buildAnimationAst` calls, so it doesn't really look like there is any reason to present them differently (on the contrary, it would be good to display them in a consistent format)

So I'll add a commit to add some shared functionality for the errors and warnings :slightly_smiling_face::+1:

2022-01-22 20:40 UTC, dario-piotrowicz commented on packages/animations/browser/src/render/transition_animation_engine.ts
> +        instruction.errors!.forEach(error => errors.push(error));
I needed to change this because with the new change it was looking pretty awkward:
![Screenshot at 2022-01-22 19-07-47](https://user-images.githubusercontent.com/61631103/150654614-f38f8452-b44c-4855-8161-b98c6b56ba3b.png)
(note the double `-`s)

without the `-` here it gets a little better:
![Screenshot at 2022-01-22 19-31-46](https://user-images.githubusercontent.com/61631103/150654626-c936ec7d-5b41-4ac2-b6d8-7fa4b6d2c3ef.png)

but it still is a bit awkward looking... (adding the error message and singular errors like this seems pretty hacky :confounded: )

what do you think @jessicajaniuk?

2022-01-22 20:41 UTC, dario-piotrowicz commented
@jessicajaniuk added shared functions for both the errors throwing and the warnings logging, please have a look :smile:

2022-01-24 17:56 UTC, jessicajaniuk commented on packages/animations/browser/src/dsl/animation_ast_builder.ts
> +          delete tuple[prop];
If it is passing a field we don't want, then I suggest a hybrid solution. I'd say keep the delete statement for now, but add a TODO on that line for me. It would be great if you could also add a comment referring to this change on my PR so I remember to address it before v14.

2022-01-24 20:34 UTC, dario-piotrowicz commented on packages/animations/browser/src/dsl/animation_ast_builder.ts
> +          delete tuple[prop];
of course! :slightly_smiling_face::+1:

2022-02-10 18:59 UTC, jessicajaniuk requested changes
@dario-piotrowicz I managed to break this again with the Error tree shaking pull request. So you'll want to take a look again. We'll want to be sure that warnings are also tree shakable, as well. Definitely take a look and let me know if you need any pointers. I'm pretty sure we can still get this in the v14 release.

2022-02-10 18:59 UTC, jessicajaniuk commented on packages/animations/browser/src/errors-and-warnings.utils.ts
> +function generateErrorsOrWarningsCombination(message: string, errorsOrWarnings: string[]) {
So we've now strongly typed all of the errors as `Error` and they've been moved into a tree shaking friendly location. So this abstraction won't work for us. Take a look at the new code after a rebase. I think that'll give you a solid idea of the best way to make these warnings abstracted in a friendly and tree shakable way.

2022-02-11 00:02 UTC, dario-piotrowicz commented on packages/animations/browser/src/errors-and-warnings.utils.ts
> +function generateErrorsOrWarningsCombination(message: string, errorsOrWarnings: string[]) {
ok sure, I'll have a look thanks :slightly_smiling_face::+1:

2022-02-12 21:47 UTC, dario-piotrowicz commented on packages/animations/browser/src/render/transition_animation_engine.ts
> +        instruction.errors!.forEach(error => errors.push(error));
no longer valid

2022-02-16 18:06 UTC, jessicajaniuk requested changes
@dario-piotrowicz This is super close. I like the changes, and I have a few suggestions for making it a bit cleaner here. Should be very quick to address and we should be able to land it.

2022-02-16 18:06 UTC, jessicajaniuk commented on packages/animations/browser/test/shared.ts
> +  }
Similar case here. You can simplify this since we're not shipping error codes and we're only warning in dev mode. The `console.warn` call can be embedded in the warnings helpers.

```suggestion
  if (warnings.length) {
    triggerParsingWarnings(name, warnings);
  }
```

2022-02-16 18:06 UTC, jessicajaniuk commented on packages/animations/browser/src/warnings.ts
> +export type RuntimeWarning = string|false;
I think you can skip this. The reason we have a RuntimeError class is for special code handling and making it easy to manage errors / track them. Warnings don't have the same code system or needs. They're just strings. So we can just put those strings in the helpers class. It should still be tree shaken nicely.

2022-02-16 18:06 UTC, jessicajaniuk commented on packages/animations/browser/src/render/animation_engine_next.ts
> +      }
```suggestion
      if (warnings.length) {
        triggerBuildWarnings(name, warnings);
      }
```

2022-02-16 18:06 UTC, jessicajaniuk commented on packages/animations/browser/src/render/timeline_animation_engine.ts
> +      }
```suggestion
      if (warnings.length) {
        registerWarnings(warnings);
      }
```

2022-02-16 23:30 UTC, jessicajaniuk requested changes
@dario-piotrowicz One last issue to resolve.

2022-02-16 23:30 UTC, jessicajaniuk commented on packages/animations/browser/src/dsl/animation_ast_builder.ts
> +          `The provided CSS properties are not recognized properties supported for animations: ${
We should move this into a helper method, too. This will ensure the message itself gets shaken away. You could perhaps do one that just pushes to the warnings array. Something like the following in the helpers.

```
function warnUnrecognizedProperties(warnings: []string, props: []string): void {
  if (ngDevMode && props.length) {
     warnings.push(`[...your existing message goes here]`);
  }
}
```

2022-02-16 23:30 UTC, jessicajaniuk commented on goldens/size-tracking/aio-payloads.json
> +        "main": 450579,
I think you have a file conflict to resolve for this file.

2022-02-16 23:31 UTC, dario-piotrowicz commented on goldens/size-tracking/aio-payloads.json
> +        "main": 450579,
sorry I thought I solved it :sweat: :shrug:

2022-02-16 23:32 UTC, dario-piotrowicz commented on packages/animations/browser/src/dsl/animation_ast_builder.ts
> +          `The provided CSS properties are not recognized properties supported for animations: ${
ah yeah sounds great! thanks! :smile::+1:

2022-02-16 23:44 UTC, dario-piotrowicz commented on packages/animations/browser/src/dsl/animation_ast_builder.ts
> +          `The provided CSS properties are not recognized properties supported for animations: ${
done, I put the function in the warnings helper file, I hope that's ok :slightly_smiling_face:

2022-02-16 23:46 UTC, jessicajaniuk approved these changes
LGTM :cookie:

Thanks for working through this, @dario-piotrowicz!

2022-02-16 23:54 UTC, dario-piotrowicz commented
> LGTM cookie
> 
> Thanks for working through this, @dario-piotrowicz!

Thank you for the awesome reviewing, sorry I went in the wrong direction a couple of times! :stuck_out_tongue_winking_eye:

2022-02-18 21:37 UTC, alxhub commented
@dario-piotrowicz currently this is tagged as `feat`, meaning it won't be mergeable into the `13.2.x` branch. However, this definitely feels like a bugfix instead. Should we update the commit tag and land this as a `fix`?

2022-02-18 22:30 UTC, dario-piotrowicz commented
> @dario-piotrowicz currently this is tagged as `feat`, meaning it won't be mergeable into the `13.2.x` branch. However, this definitely feels like a bugfix instead. Should we update the commit tag and land this as a `fix`?

Sorry I am not really sure.... the original code was __purposely__ stopping animations for unsupported properties, and I changed it to ignore them instead... so it does sort of sound like a feature (even if a very small one) :shrug: 

I don't even know what difference it makes to land this as a `feat` or a bugfix, I guess I don't mind either way, please let me know what you think/suggest

(@jessicajaniuk, what do you think? :slightly_smiling_face:)

2022-02-22 20:59 UTC, dario-piotrowicz commented
@alxhub Updated to `fix` :slightly_smiling_face::+1:

2022-02-23 16:57 UTC, atscott commented
FYI - This had a conflict with `13.2.x`. Please open a new PR to target that branch only.

2022-02-23 16:57 UTC, atscott commented
This PR was merged into the repository by commit f8dc66060591e1ce42265a7862c3df16e40b05e1.

2022-02-23 16:58 UTC, closed without merging