refactor(forms): Move FormControl to an overridden exported constructor.
angular/angular pull request #44806
Opened 2022-01-24 18:10 UTC by dylhunn

This implementation change was originally proposed as part of Typed Forms, and will have major consequences for that project as described in the design doc. Submitting it separately will greatly simplify the risk of landing Typed Forms. This change should have no visible impact on normal users of FormControl.

See the Typed Forms design doc here: https://docs.google.com/document/d/1cWuBE-oo5WLtwkLFxbNTiaVQGNk8ipgbekZcKBeyxxo.

PR Close #44316

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-01-24 18:22 UTC, mary-poppins commented
You can preview 2a9d1aa at https://pr44806-2a9d1aa.ngbuilds.io/.

2022-01-24 19:06 UTC, mary-poppins commented
You can preview 769eb1d at https://pr44806-769eb1d.ngbuilds.io/.

2022-01-25 00:10 UTC, dylhunn commented
I ran a TGP on the train today, and it seems to be green except a few flakes: [link](https://fusion2.corp.google.com/presubmit/tap/423847958/OCL:423847958:BASE:423790319:1643065809226:7c859c88/targets)

2022-01-25 02:31 UTC, mary-poppins commented
You can preview dd48cec at https://pr44806-dd48cec.ngbuilds.io/.

2022-01-25 02:39 UTC, mary-poppins commented
You can preview 451a968 at https://pr44806-451a968.ngbuilds.io/.

2022-01-25 17:31 UTC, gkalpak requested changes
Overall lgtm. Just some minor comments/suggestions.

2022-01-25 17:31 UTC, gkalpak commented on packages/forms/src/model.ts
> +   * such functions, or an `FormControlOptions` object that contains validation functions
```suggestion
   * such functions, or a `FormControlOptions` object that contains validation functions
```

2022-01-25 17:31 UTC, gkalpak commented on packages/forms/src/model.ts
> +   * @param asyncValidator A single async validator or array of async validator functions
```suggestion
   * @param asyncValidator A single async validator or array of async validator functions.
```

2022-01-25 17:31 UTC, gkalpak commented on packages/forms/src/model.ts
> +   * @param formState Initializes the control with an initial value,
```suggestion
   * @param value Initializes the control with an initial value,
```

2022-01-25 17:31 UTC, gkalpak commented on packages/forms/src/model.ts
> +  new(value: any, validatorOrOpts?: ValidatorFn|ValidatorFn[]|FormControlOptions|null,
Could we avoid using `any` here? Could we make `FormControlCtor` generic maybe?

2022-01-25 17:31 UTC, gkalpak commented on packages/forms/test/form_control_spec.ts
> +    });
Shouldn't this test have an assertion?

2022-01-25 17:31 UTC, gkalpak commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
>              throw new Error(`@overriddenImplementation requires that the provided constructor ${symbolNames[1]} have exactly one member called "new", possibly with multiple overrides.`);
It sounds like it is no longer a requirement to have exactly one member.

```suggestion
            throw new Error(`@overriddenImplementation requires that the provided constructor ${symbolNames[1]} have a member called "new", possibly with multiple overrides.`);
```

2022-01-25 17:31 UTC, gkalpak commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
> +          const symbolNames = [doc.name, doc.overriddenImplementation, doc.typeDefinition];
Now that the format requirements have changed, we should also update the jsdoc comment above.

2022-01-25 17:35 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * such functions, or an `FormControlOptions` object that contains validation functions
Fixed.

2022-01-25 17:36 UTC, dylhunn commented on packages/forms/src/model.ts
> +  new(value: any, validatorOrOpts?: ValidatorFn|ValidatorFn[]|FormControlOptions|null,
That's actually exactly what we're preparing to do with this project -- Typed Forms will allow us to get rid of the `any`s once and for all :)

There's a bit more work to do first though.

2022-01-25 17:37 UTC, dylhunn commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
>              throw new Error(`@overriddenImplementation requires that the provided constructor ${symbolNames[1]} have exactly one member called "new", possibly with multiple overrides.`);
Right, good catch. This changed due to the need to provide the explicit prototype property for google3 backwards compatibility.

2022-01-25 17:38 UTC, dylhunn commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
> +          const symbolNames = [doc.name, doc.overriddenImplementation, doc.typeDefinition];
This has been fixed.

2022-01-25 17:39 UTC, dylhunn commented on packages/forms/test/form_control_spec.ts
> +    });
No, it will actually fail to compile in the event that we break FormControl extensions.

2022-01-25 17:40 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * @param asyncValidator A single async validator or array of async validator functions
Fixed.

2022-01-25 17:41 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * @param formState Initializes the control with an initial value,
We are actually going to extract this into a named type called `FormState` in the next PR, so I think it's best to update the name. The issue is that this isn't just a value, it can also be a state dictionary of the shape `{value: T, disabled: boolean}`.

2022-01-25 17:42 UTC, dylhunn commented
Thank you George, I have replied to all your comments, and committed the fixes for most of them!

2022-01-25 17:48 UTC, mary-poppins commented
You can preview e14468a at https://pr44806-e14468a.ngbuilds.io/.

2022-01-25 17:56 UTC, AndrewKushnir commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
> + * *\/
Just checking if a black slash is intentional (if yes, should the slash on line 25 have it as well?).

2022-01-25 17:56 UTC, AndrewKushnir commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
> +        if (doc.overriddenImplementation) {
It'd be great to move the dgeni changes to a separate commit (so it can have a separate commit message, etc), but if it's too much work, let's leave it as is.

2022-01-25 17:56 UTC, AndrewKushnir commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
> +            throw new Error(`@overriddenImplementation ${doc.overriddenImplementation} in incorrect format: type ${doc.name} = ${doc.typeDefinition}`);
Can we use some bits of the previous error message and provide a hint to a user on the expected format (so the error message is a bit more actionable)?

2022-01-25 17:56 UTC, AndrewKushnir commented on goldens/public-api/forms/forms.md
> +    getControl(dir: NgControl): FormControlImpl;
The `FormControlImpl` symbols will likely show up in the docs. Can we use `FormControl` instead?

2022-01-25 17:56 UTC, AndrewKushnir commented on packages/forms/src/forms.ts
> +export const FormControl: FormControlCtor = FormControlImpl as FormControlCtor;
Should we add the `@publicApi` annotation to the `FormControl` symbols as well?

2022-01-25 17:56 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +  prototype: FormControl;
Let's add a note on why adding the `prototype` here is needed (for better backwards-compatibility).

2022-01-25 17:56 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +  _pendingValue!: any;
If it's `any`, the non-null assertion should not be needed.

2022-01-25 17:56 UTC, AndrewKushnir commented on packages/forms/test/form_control_spec.ts
> +    });
Let's add a quick comment on why there are no assertions in this test (I agree with George that the test looks confusing without extra context :)).

2022-01-25 18:04 UTC, dylhunn commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
> +            throw new Error(`@overriddenImplementation ${doc.overriddenImplementation} in incorrect format: type ${doc.name} = ${doc.typeDefinition}`);
I fixed this with a much more descriptive error message.

2022-01-25 18:04 UTC, dylhunn commented on packages/forms/src/model.ts
> +  prototype: FormControl;
Done.

2022-01-25 18:04 UTC, dylhunn commented on packages/forms/src/model.ts
> +  _pendingValue!: any;
Fixed.

2022-01-25 18:14 UTC, mary-poppins commented
You can preview 1d5216e at https://pr44806-1d5216e.ngbuilds.io/.

2022-01-25 18:18 UTC, gkalpak commented on packages/forms/src/model.ts
> +   * @param formState Initializes the control with an initial value,
In any case, this jsdoc `@param` annotation should use the same name as the name of the argument used below. So, either both should be `fromState` or  both should be `value` :smiley:

2022-01-25 18:28 UTC, gkalpak approved these changes
LGTM :+1:

2022-01-25 18:28 UTC, gkalpak commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
> + * *\/
```suggestion
 *  * @overriddenImplementation FooCtor
 *  *\/
```

2022-01-25 19:10 UTC, dylhunn commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
> + * *\/
Fixed.

2022-01-25 19:12 UTC, dylhunn commented on packages/forms/src/model.ts
> +   * @param formState Initializes the control with an initial value,
Ah, good catch, thank you! Fixed.

2022-01-25 19:18 UTC, dylhunn commented on goldens/public-api/forms/forms.md
> +    getControl(dir: NgControl): FormControlImpl;
Closing, as I am applying changes as discussed on VC.

2022-01-25 23:55 UTC, mary-poppins commented
You can preview 3c12d5c at https://pr44806-3c12d5c.ngbuilds.io/.

2022-01-26 04:16 UTC, mary-poppins commented
You can preview ae6036d at https://pr44806-ae6036d.ngbuilds.io/.

2022-01-26 04:21 UTC, mary-poppins commented
You can preview 858d415 at https://pr44806-858d415.ngbuilds.io/.

2022-01-26 04:46 UTC, mary-poppins commented
You can preview b925fe4 at https://pr44806-b925fe4.ngbuilds.io/.

2022-01-26 04:47 UTC, dylhunn commented
A new TGP has been started with the latest fixes: [link](https://test.corp.google.com/OCL:424249050:BASE:424249257:1643172339910:770886b2)

2022-01-26 17:53 UTC, mary-poppins commented
You can preview a96f73d at https://pr44806-a96f73d.ngbuilds.io/.

2022-01-26 19:02 UTC, jessicajaniuk approved these changes
LGTM :cookie:

reviewed-for: public-api

2022-01-27 02:35 UTC, AndrewKushnir commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
> + * This processor will correct the docs for symbol `Foo` by copying all documented constructor overrides from `FooCtor`.
```suggestion
 * This processor will extend the docs for symbol `Foo` by copying all documented constructor overrides from `FooCtor`.
```

2022-01-27 02:35 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +export interface FormControlCtor {
Quick question: do we exclude this symbol from the docs after merging those signatures into the `FormControl`?

2022-01-27 02:35 UTC, AndrewKushnir commented on packages/forms/src/forms.ts
> +export {AbstractControl, AbstractControlOptions, FormArray, FormControl, FormControlCtor, FormControlOptions, FormControlStatus, FormGroup} from './model';
Can we keep the `FormControlCtor` symbol private?

2022-01-27 02:37 UTC, dylhunn commented on packages/forms/src/model.ts
> +export interface FormControlCtor {
Yes, this symbol will be removed from the generated documentation.

2022-01-27 02:37 UTC, dylhunn commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
> + * This processor will correct the docs for symbol `Foo` by copying all documented constructor overrides from `FooCtor`.
Fixed.

2022-01-27 02:39 UTC, dylhunn commented on packages/forms/src/forms.ts
> +export {AbstractControl, AbstractControlOptions, FormArray, FormControl, FormControlCtor, FormControlOptions, FormControlStatus, FormGroup} from './model';
No, we must export it. The main reason is that documentation is never processed for non-exported symbols, so we can't merge constructor documentation that isn't generated. I think this should be OK, given that `FormControl` is used everywhere in the `.d.ts` files and docs (`FormControlImpl` and `FormControlCtor` never show up as return types, etc.)

2022-01-27 03:32 UTC, mary-poppins commented
You can preview 5028400 at https://pr44806-5028400.ngbuilds.io/.

2022-01-27 20:10 UTC, mary-poppins commented
You can preview 27b7545 at https://pr44806-27b7545.ngbuilds.io/.

2022-01-28 06:09 UTC, AndrewKushnir commented on goldens/public-api/forms/forms.md
> +export const FormControl: θFormControlCtor;
Let's use a different symbol, which is used in other APIs: `ɵ`.
```suggestion
export const FormControl: ɵFormControlCtor;
```

2022-01-28 06:09 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> +      /** @publicApi */
Do we need `@publicApi` here (we don't have it on other fields)?

2022-01-28 17:14 UTC, dylhunn commented on packages/forms/src/model.ts
> +      /** @publicApi */
No, we don't. Removed.

2022-01-28 17:14 UTC, dylhunn commented on goldens/public-api/forms/forms.md
> +export const FormControl: θFormControlCtor;
Fixed.

2022-01-28 17:23 UTC, mary-poppins commented
You can preview 9e5fad1 at https://pr44806-9e5fad1.ngbuilds.io/.

2022-01-31 03:25 UTC, AndrewKushnir approved these changes
Looks great, thanks @dylhunn 👍

2022-01-31 03:25 UTC, AndrewKushnir commented on packages/forms/src/model.ts
> + * ```
Could you please add a quick comment on why we prefix this symbol with `ɵ`?

2022-01-31 03:27 UTC, AndrewKushnir reviewed
@dylhunn quick question: could you please also check what do we have in the d.ts file (related to the `FormControl`) in the forms package with this change?

2022-01-31 18:23 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2022-01-31 18:27 UTC, mary-poppins commented
You can preview 8de8db9 at https://pr44806-8de8db9.ngbuilds.io/.

2022-01-31 20:14 UTC, atscott approved these changes
reviewed-for: public-api

2022-01-31 20:14 UTC, atscott commented on packages/forms/src/model.ts
> +  new(formState: any, validatorOrOpts?: ValidatorFn|ValidatorFn[]|FormControlOptions|null,
Not blocking, but it looks like dgeni doesn't have this signature in the top section, but only in the detailed constructor info: 
https://pr44806-9e5fad1.ngbuilds.io/api/forms/FormControl#formcontrol
vs
https://pr44806-9e5fad1.ngbuilds.io/api/forms/FormControl#constructor

2022-01-31 20:14 UTC, atscott commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
> + * *\/
Is this intentional? ` * *\/`

2022-01-31 20:47 UTC, dylhunn commented on packages/forms/src/model.ts
> +  new(formState: any, validatorOrOpts?: ValidatorFn|ValidatorFn[]|FormControlOptions|null,
Interesting, thanks for pointing that out. It's because I hacked Dgeni to put a constructor signature on an interface, looks like I might need to do a bit more tinkering down the line.

2022-01-31 20:47 UTC, dylhunn commented on aio/tools/transforms/angular-api-package/processors/mergeOverriddenImplementation.js
> + * *\/
Yes -- otherwise the enclosing comment is broken unfortunately

2022-01-31 22:48 UTC, jessicajaniuk commented
This PR was merged into the repository by commit f0cfa00a340800af4670cbfb5604f001e8bbebd0.

2022-01-31 22:48 UTC, closed without merging