docs: Explain how ngsw.json is generated.
angular/angular pull request #44823
Opened 2022-01-25 18:35 UTC by Arjen-1

ngsw.json is the manifest file which is generated at build time ( based on ngsw-config.json ). This explains this a bit clearer.
At first, I thought that it was a wrongly named filename. Not is it explicitly described.

## PR Type
Docs

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Its not explained how ngsw is created and how it differs from ngsw-config

## What is the new behavior?
It explains it.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

 

## Other information
Still a proces of my first contribution!

2022-01-26 08:38 UTC, Arjen-1 commented
I'd love to know if my first contribution has a green light ! :D

2022-01-26 15:15 UTC, gkalpak requested changes
Thx, @Arjen-1 :heart:
I made a small suggestion - otherwise lgtm :+1:

2022-01-26 15:15 UTC, gkalpak commented on aio/content/guide/service-worker-devops.md
> +build time based on `ngsw-config.json`.
I think it would be better to make this an [alert][1]:

```suggestion
<div class="alert is-helpful">

`ngsw.json` is the manifest file that is generated at 
build time based on `ngsw-config.json`.

</div>
```

[1]: https://angular.io/guide/docs-style-guide#alerts

2022-01-26 18:14 UTC, mary-poppins commented
You can preview ae49391 at https://pr44823-ae49391.ngbuilds.io/.
You can preview 21c1180 at https://pr44823-21c1180.ngbuilds.io/.

2022-01-26 18:14 UTC, gkalpak approved these changes
Thx for making the update, @Arjen-1 :+1:
LGTM :shipit:

2022-01-26 18:15 UTC, gkalpak commented
Oh, wait! Can you please squash the commits into one?

2022-01-27 10:40 UTC, Arjen-1 commented
@gkalpak , I believe it's squashed into one commit now. Thanks for the tip!

2022-01-28 15:25 UTC, gkalpak commented
The for squashing, @Arjen-1. I'm afraid there are some more changes needed, though 😅
The commit message has to follow our [commit message guidelines](https://github.com/angular/angular/blob/655507012b7b59c83e27429349ce3ac10608a82d/CONTRIBUTING.md#commit). So, could you change it again to something like your original commit message? :pray:
For example:

> docs: explain how \`ngsw.json\` is generated
>
> \`ngsw.json\` is the manifest file which is generated at build time (based
> on \`ngsw-config.json\`). This commit explains this a bit clearer. At
> first, I thought that it was a wrongly named filename. Now is it
> explicitly described.

2022-01-28 17:22 UTC, gkalpak commented
I forgot to mention that we also need you to sign the CLA before we can merge this PR, @Arjen-1. See [here][1] for more details.

[1]: https://github.com/angular/angular/pull/44823/checks?check_run_id=4964844866

2022-02-01 18:11 UTC, AndrewKushnir commented
@Arjen-1 thanks for addressing the feedback. I've noticed that the `setup` CI job is failing and I've rebased the PR on top of the most recent version of the master branch. I'm adding this PR to the merge queue. Thanks for improving Angular docs!

2022-02-01 18:18 UTC, mary-poppins commented
You can preview d0c5449 at https://pr44823-d0c5449.ngbuilds.io/.

2022-02-01 18:26 UTC, jessicajaniuk commented
This PR was merged into the repository by commit 9f5edce0e9378bae07b1fa1539ef915a4aa62b0a.

2022-02-01 18:26 UTC, closed without merging