feat(router): set stricter type for Route.title
angular/angular pull request #44939
Opened 2022-02-02 02:23 UTC by markostanimirovic

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The type of `Route.title` is `string | unknown`.

Issue Number: #44936

## What is the new behavior?

The type of `Route.title` is `string | Type<Resolve<string>>`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

AFAIK, the route title feature is not released yet. So there will be no breaking changes.

2022-02-02 09:29 UTC, alfaproject commented on packages/router/test/page_title_strategy_spec.ts
> +                 // `undefined` prevents inheriting from parent if it doesn't have its own value.
This doesn't sound right. So if you want to inherit from parent, do you have to do it manually in all children?

2022-02-02 13:14 UTC, markostanimirovic commented on packages/router/test/page_title_strategy_spec.ts
> +                 // `undefined` prevents inheriting from parent if it doesn't have its own value.
AFAIK there is no need to explicitly set `title` to `undefined` if you want to inherit the title from the parent.

So, with the following route config:

```ts
const routes: Routes = [
  {
    path: 'foo',
    component: FooComponent,
    title: 'FOO',
    children: [
      { path: 'bar', component: BarComponent }
    ]
  },
]
```

the title for route `foo/bar` will be `FOO`.

2022-02-02 18:32 UTC, atscott requested changes

2022-02-02 18:32 UTC, atscott commented on packages/router/src/config.ts
> +import {Resolve} from './interfaces';
Totally reasonable. The specific locations of the types don't really matter since they're all just exported from the index.

I'd recommend doing this as a separate commit (same PR) to make things easier to review.

2022-02-03 17:21 UTC, atscott approved these changes
LGTM 👍  Thanks for the improvement!

reviewed-for: fw-router
reviewed-for: public-api

public API review notes: 
As I mentioned in the issue report, I do prefer keeping this as `Type<Resolve<string>>` rather than creating a type alias that would be another click-through in the documentation just to arrive at the same `Resolve<string>` type. I don't think the type alias would be useful in this situation and would actually make things _more_ obscure.

2022-02-03 17:45 UTC, jessicajaniuk approved these changes
LGTM :cookie:

reviewed-for: public-api

2022-02-03 18:17 UTC, atscott commented
caretaker note: this will require an update to one of the patches in g3: [cl/426173402](http://cl/426173402)

2022-02-03 19:09 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2022-02-03 19:12 UTC, atscott approved these changes

2022-02-03 20:40 UTC, dylhunn commented
This PR was merged into the repository by commit 791bd3142432ed7caf14a68a6e434b27004e634b.

2022-02-03 20:40 UTC, closed without merging