feat(devtools): adding firefox support
angular/angular pull request #44952
Opened 2022-02-02 19:55 UTC by sumitarora

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-02-03 15:57 UTC, devversion approved these changes
LGTM for the bazel setup. Would be good to also preserve trailing newlines for consistency.

2022-02-03 15:57 UTC, devversion commented on devtools/projects/shell-chrome/src/manifest/BUILD.bazel
> +    srcs = glob(["*.json"]),
Nit: Since I don't expect this list to grow a lot, you could hard-code the manifest names here to avoid globs (generally a good best practice)

2022-02-03 15:57 UTC, devversion commented on devtools/projects/shell-chrome/src/BUILD.bazel
> +    name = "prod_app_static_files_" + build_target,
You could potentially use a more specific variable name. It seems like the value currently does not refer to a build target directly (in the context of Bazel), and you could store `[chrome, firefox]` as variable to avoid duplication

```suggestion
    name = "prod_app_static_files_" + browser,
```

2022-02-03 16:59 UTC, mgechev commented on devtools/docs/firefox.md
> +To install Angular DevTools in the firefox browser. Follow below steps:-
```suggestion
To install Angular DevTools in Firefox follow the steps:
```

2022-02-03 17:01 UTC, mgechev commented on devtools/docs/firefox.md
> +Click on `Load Temporary Add-on` button to select and load Angular Devtools extension for firefox.
```suggestion
Click on `Load Temporary Add-on` button to select and load the Angular DevTools extension for Firefox.
```

2022-02-03 17:02 UTC, mgechev commented on devtools/docs/firefox.md
> +Select any file from `dist -> shell chrome` directory to load extension. If you have not build extension for firefox yet. You can do it using `yarn build:firefox` which will generate build for firefo
This seems a little off? Do we have a directory `shell chrome`? Why not `dist/shell-firefox`?

2022-02-03 17:02 UTC, mgechev commented on devtools/docs/firefox.md
> +After selecting file and clicking open, you should be able to see Angular DevTools as a Temporary Extension in firefox.
```suggestion
After selecting file and clicking open, you should be able to see Angular DevTools as a Temporary Extension in Firefox.
```

2022-02-03 17:02 UTC, mgechev commented on devtools/docs/firefox.md
> +Open any angular application in dev mode and open Firefox Devtools you should see Angular Tab in there.
```suggestion
Open any Angular application in dev mode and open Firefox DevTools you should see Angular Tab in there.
```

2022-02-03 17:03 UTC, mgechev commented on devtools/projects/shell-chrome/src/manifest/manifest.firefox.json
> +  "description": "Angular DevTools extends Chrome DevTools adding Angular specific debugging and profiling capabilities.",
```suggestion
  "description": "Angular DevTools extends Firefox DevTools adding Angular specific debugging and profiling capabilities.",
```

2022-02-03 17:03 UTC, mgechev requested changes
Mostly looks good to me. Left a few suggestions.

2022-02-07 18:07 UTC, JimMorrison723 commented on devtools/docs/firefox.md
> +# Installing Angular DevTools in Firefox
Isn't adding 1,5MB of photos for a bullet point list is overkill? I feel like if the steps are well written there is no need for the images. This is something that will be used once by every devtools dev (max), they should be fine without them. (And don't forget to update the images beside the text when it comes to it)

2022-02-08 01:35 UTC, mgechev commented on devtools/docs/firefox.md
> +# Installing Angular DevTools in Firefox
Good point.

2022-02-14 19:13 UTC, mgechev commented on package.json
> +    "devtools:build:firefox": "bazelisk build --config snapshot //devtools/projects/shell-chrome/src:prodapp_firefox",
`shell-chrome` -> `shell-browser`?

2022-02-14 20:37 UTC, SchnWalter commented on devtools/projects/shell-chrome/src/manifest/manifest.chrome.json
> +    "file:///*"
The `file://` protocol should be removed from both the chrome and firefox extensions. Angular applications can not be opened because of CORS issues. To see the issues you just need top open an Angular build in a browser by following these steps:
```
ng new test-file-proto
cd test-file-proto
ng build
```
After running those commands, open the generated dist/test-file-proto/index.html in your favorite browser using the file protocol (e.g. drag-and-drop), at this point you should see multiple errors among these lines:
* in chromium based browsers:
  > Access to script at 'file:///runtime.597fc8828f410f46.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
* in firefox based browsers:  
  > Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///runtime.597fc8828f410f46.js. (Reason: CORS request not http).

2022-02-15 18:02 UTC, sumitarora commented on devtools/docs/firefox.md
> +# Installing Angular DevTools in Firefox
@JimMorrison723 @mgechev Removed

2022-02-18 17:53 UTC, sumitarora commented
@mgechev @devversion Updated PR with all the changes. Should be good to review.

2022-02-19 09:29 UTC, devversion commented on package.json
> +    "devtools:build:firefox": "bazelisk build --config snapshot //devtools/projects/shell-browser/src:prodapp --define browser=firefox",
The use of `--define` is a legacy construct in Bazel FYI. It would be better to use a custom flag (also enabling the use of Bazel transitions for dependant targets in the future)

<sup>https://docs.bazel.build/versions/main/configurable-attributes.html#custom-flags</sup>

2022-02-24 21:39 UTC, sumitarora commented on package.json
> +    "devtools:build:firefox": "bazelisk build --config snapshot //devtools/projects/shell-browser/src:prodapp --define browser=firefox",
@devversion done 😉

2022-02-25 07:32 UTC, devversion approved these changes
Still LGTM for the bazel setup. One minor comment for the markdown file.

I think @mgechev needs to have another look as well (for the manifest specifically)

2022-02-25 07:32 UTC, devversion commented on devtools/docs/firefox.md
> +* Select any file from `dist/bin/devtools/projects/shell-browser/src/prodapp` directory to load extension. If you have not build extension for Firefox yet. You can do it using `yarn build:firefox` wh
```suggestion
* Select any file from `dist/bin/devtools/projects/shell-browser/src/prodapp` directory to load extension. If you have not built the extension for Firefox yet. You can do it using `yarn devtools:build:firefox` which will generate build for Firefox.
```

2022-02-25 07:34 UTC, devversion commented
@sumitarora It would be cool if addressed comments are marked as resolved by you, so that it's easy for reviewers to see what is missing/and if another pass is worth doing

2022-02-26 06:35 UTC, TimJ0212 commented on devtools/docs/firefox.md
> +* After selecting file and clicking open, you should be able to see Angular DevTools as a Temporary Extension in Firefox.
```suggestion
* After selecting file and clicking open, you should be able to see Angular DevTools as a temporary extension in Firefox.
```

2022-03-21 03:39 UTC, AleksanderBodurri approved these changes
LGTM overall. After we address the remaining comments and the merge conflicts, this should be good to go @sumitarora

2022-03-30 00:16 UTC, dylhunn commented
@sumitarora Would you mark resolved all the comments you have addressed, and rebase on the latest master? I'd love to get this merged.

2022-04-04 21:02 UTC, sumitarora commented
@devversion @dylhunn updated PR and rebased as well

2022-04-04 21:22 UTC, dylhunn commented
@AndrewKushnir Since you're caretaking now, would you mind seeing this one through? Seems like it's just about ready.

2022-04-04 22:46 UTC, AndrewKushnir commented
> Since you're caretaking now, would you mind seeing this one through? Seems like it's just about ready.

@dylhunn Sure! It looks like there is missing approval from Minko. @mgechev or @AleksanderBodurri could you please let me know if this PR is ready for merge or needs extra reviews? Thank you.

2022-04-11 21:20 UTC, mgechev commented on devtools/README.md
> +4. In the dialog, select the directory `dist/shell-browser`.
I suppose this is `dist/shell-chrome`? Can we install the browser shell?

2022-04-11 21:21 UTC, mgechev commented on devtools/docs/firefox.md
> +To install Angular DevTools in Firefox follow the steps:-
```suggestion
To install Angular DevTools in Firefox follow the steps:
```

2022-04-11 21:22 UTC, mgechev commented on devtools/docs/firefox.md
> +* Select any file from `dist/bin/devtools/projects/shell-browser/src/prodapp` directory to load extension. If you have not built the extension for Firefox yet. You can do it using `yarn devtools:buil
```
* Select any file from `dist/bin/devtools/projects/shell-browser/src/prodapp` directory to load extension. If you have not built the extension for Firefox yet, you can do it using `yarn devtools:build:firefox` which will generate build for Firefox.
```

2022-04-11 21:24 UTC, mgechev commented on devtools/projects/shell-browser/src/popups/not-angular.html
> +</html>
We don't open `<html>` anywhere.

2022-04-11 21:24 UTC, mgechev commented on devtools/projects/shell-browser/src/popups/not-angular.html
> +
```suggestion
<html>
```

2022-04-11 21:24 UTC, mgechev commented on devtools/projects/shell-browser/src/popups/production.html
> +
```suggestion
<html>
```

2022-04-11 21:25 UTC, mgechev commented on devtools/projects/shell-browser/src/popups/supported.html
> +
```suggestion
<html>
```

2022-04-11 21:25 UTC, mgechev commented on devtools/projects/shell-browser/src/popups/unsupported.html
> +
```suggestion
<html>
```

2022-04-11 21:28 UTC, mgechev approved these changes
LGTM once we resolve the typos! :)

2022-04-12 16:41 UTC, mgechev commented
Changed the target to minor since this PR introduces a new feature.

2022-04-12 18:41 UTC, jessicajaniuk commented
This PR was merged into the repository by commit b5f39c5da1f98e522947f0f843fcd9b27150a098.

2022-04-12 18:41 UTC, closed without merging