Part 2 of Standalone Components
angular/angular pull request #44973
Opened 2022-02-04 16:38 UTC by alxhub

Part 1 implemented the `standalone` flag in components/directives/pipes, and `imports` for components. In this PR, NgModules gain support for importing standalone types.

2022-02-04 17:43 UTC, pkozlowski-opensource commented on packages/compiler-cli/test/ngtsc/standalone_spec.ts
> +          imports: [StandaloneCmp],
Maybe add a test for importing standalone directives and pipes as well?

2022-02-04 17:43 UTC, pkozlowski-opensource commented on packages/compiler-cli/test/ngtsc/standalone_spec.ts
> +            imports: [TestDir],
Maybe add a test for importing a non-standalone component and pipes as well?

2022-02-04 19:17 UTC, krishna96-tecdune commented on packages/compiler-cli/test/ngtsc/standalone_spec.ts
> +          imports: [StandaloneCmp],
test

2022-02-07 23:36 UTC, atscott requested changes, later dismissed
As mentioned by Pawel, this could generally use more test coverage for the various diagnostics and types of standalone entities.

2022-02-07 23:36 UTC, atscott commented on packages/compiler-cli/src/ngtsc/scope/src/util.ts
> +          extraText}`,
```suggestion
  let diagnosticMessage = `The ${kind} '${
          ref.node.name
              .text}' appears in 'imports', but is not standalone and cannot be imported directly`;
  if (relatedInformation === undefined) {
    // If no contextual pointers can be provided to suggest a specific remedy, then at least tell
    // the user broadly what they need to do.
    diagnosticMessage += ' It must be imported via an NgModule.';
  }
  return makeDiagnostic(
      ErrorCode.COMPONENT_IMPORT_NOT_STANDALONE, getDiagnosticNode(ref, rawExpr),
      diagnosticMessage,
```

Similar to the other comment, I think maybe this is a tad more straightforward.

2022-02-07 23:36 UTC, atscott commented on packages/compiler-cli/src/ngtsc/scope/src/local.ts
> +      `Can't be exported from this NgModule as ${specificIssue}.`);
Nit: The construction of the sentence reads a bit weird when it's split into two variables like this. Especially since when you read the code, you're reading the end of the sentence first (without a period), and then you later read the beginning of the sentence. It might be helpful to just write it as two separate sentences.

```
let diagnosticMessage = `Can't be exported from this NgModule.`
if (x) {
  diagnosticMessage += ` It must be imported first.`;
} else if (y) {
 ...
} else {
 ...
}
return makeDiagnostic(x, y, diagnosticMessage);
```

2022-02-07 23:36 UTC, atscott commented on packages/compiler-cli/src/ngtsc/testing/src/utils.ts
> +  debugger;
nit: debugger;

2022-02-07 23:36 UTC, atscott commented on packages/compiler-cli/src/ngtsc/testing/src/utils.ts
> +    throw new Error(`Expected ts.Diagnostic to have a file source`);
```suggestion
    throw new Error(`Expected ts.Diagnostic to have a file source.`);
```
nit

2022-03-22 22:32 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/testing/src/utils.ts
> +    throw new Error(`Expected ts.Diagnostic to have a file source`);
This is actually existing code, just moved.

2022-03-22 22:37 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/scope/src/util.ts
> +          extraText}`,
👍 much cleaner.

2022-03-22 22:37 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/scope/src/local.ts
> +      `Can't be exported from this NgModule as ${specificIssue}.`);
👍 done

2022-03-22 22:38 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/scope/src/local.ts
> +        }
👍 we have a test for this!

2022-03-24 19:13 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/scope/src/local.ts
> +          const isStandalone = (dirMeta?.isStandalone || pipeMeta?.isStandalone)!;
nit: a `??` would be slightly more appropriate here, also allowing to remove one `?.` in favor of `!`.

```suggestion
          const isStandalone = dirMeta?.isStandalone ?? pipeMeta!.isStandalone;
```

2022-03-24 19:13 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/scope/src/util.ts
> +        scope.exported.pipes.some(exp => exp.ref.node);
This is missing `=== ref.node` in the search among exported pipes.

2022-03-24 19:13 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/scope/src/local.ts
> +    message += 'it must be imported first';
I don't see tests for the case where a standalone entity is exported from an NgModule that doesn't import it.

2022-03-24 19:13 UTC, JoostK commented on packages/core/src/render3/definition.ts
> +  isStandalone?: boolean;
Since this is optional, can we do `isStandalone?: true;` here or would that be inaccurate?

2022-03-24 19:13 UTC, JoostK commented on packages/core/src/render3/definition.ts
> +      isStandalone: componentDefinition.isStandalone !== true,
The `!== true` seems like a bug here?!

2022-03-24 19:13 UTC, JoostK commented on packages/core/src/render3/definition.ts
> +    isStandalone: pipeDef.isStandalone !== true,
The `!== true` seems like a bug here?!

2022-03-28 11:53 UTC, pkozlowski-opensource commented on packages/core/src/render3/definition.ts
> +      isStandalone: componentDefinition.isStandalone !== true,
Looks like it to me as well. Also points out that we are probably missing a test for this case (not sure what would be the best test case, though, as we are not using this runtime flag anywhere yet).

2022-03-28 19:46 UTC, alxhub commented on packages/core/src/render3/definition.ts
> +      isStandalone: componentDefinition.isStandalone !== true,
Yeah, I expect we'll add tests once we have the full runtime output defined.

2022-03-28 20:04 UTC, alxhub commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +        }
I don't think so, because `relatedInformation` is not the same as using a `DiagnosticMessageChain` for `messageText`. But I might be misunderstanding the TS APIs here?

2022-03-28 20:06 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/scope/src/local.ts
> +          const isStandalone = (dirMeta?.isStandalone || pipeMeta?.isStandalone)!;
I think this is too magical actually (both the original and the suggested) - I've changed it to be more explicit.

2022-03-29 13:36 UTC, ahasall commented on packages/core/src/render3/interfaces/definition.ts
> +  isStandalone: boolean;
Is it possible to rename `isStandalone` to just `standalone` ? It’s shorter and consistent with what we already have with the `pure` option of pipes.

2022-03-29 18:04 UTC, JoostK approved these changes

2022-03-29 18:04 UTC, JoostK commented on packages/compiler-cli/test/ngtsc/ngtsc_spec.ts
> +        }
Oh, you are correct. It could be used within the `.map(info => ...)` transform here to avoid an `[object object]` string in the case of a message chain, but we can adjust once we need it (since this is just testing code).

2022-03-29 18:09 UTC, pkozlowski-opensource approved these changes
LGTM

2022-03-29 20:06 UTC, dylhunn commented
This PR was merged into the repository by commit 2142ffd295de491eb8582c2eb1712b5b48044f24.

2022-03-29 20:06 UTC, closed without merging