docs: improve try-it-now card focus area
angular/angular pull request #45002
Opened 2022-02-07 21:44 UTC by dario-piotrowicz

the focus/interactable area for the try-it-now card is wider than
necessary, reduce such width to the appropriate size

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

![try-it-now-before](https://user-images.githubusercontent.com/61631103/152876738-40f2badf-5f5a-49be-be21-1b4ab3ab213c.gif)

(it is pretty minor, but I just figured why not fixing it :sweat_smile:)

Issue Number: N/A

## What is the new behavior?

![try-it-now-after](https://user-images.githubusercontent.com/61631103/152876805-59866631-bd8f-4bbc-b297-3aa6d29dbed2.gif)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-02-07 23:04 UTC, mary-poppins commented
You can preview 3ac42df at https://pr45002-3ac42df.ngbuilds.io/.

2022-02-07 23:14 UTC, josephperrott requested changes

2022-02-07 23:14 UTC, josephperrott commented on aio/content/marketing/index.html
> +      <a href="start" class="card-wrapper">
Rather than add another class here, I think it actually makes the most sense to use the `<a>` as the card element.

This eliminates the odd case of padding being present within the `<a>` from the card but ending up as clickable area.

```suggestion
      <a href="start" class="card">
        <img src="generated/images/marketing/home/code-icon.svg" alt="Get Started with Angular" width="70" height="70" loading="lazy">
        <div class="card-text-container">
          <div class="text-headline">Try it now</div>
          <p>Explore Angular's capabilities with a ready-made sample app. No setup required.</p>
        </div>
      </a>
```


Alternatively, we could just switch the `<a>` and `<div class="card">` in the hierarchy and perform a similar result.

2022-02-07 23:24 UTC, dario-piotrowicz commented on aio/content/marketing/index.html
> +      <a href="start" class="card-wrapper">
yeah, you're totally right! I made the change :slightly_smiling_face::+1:

2022-02-07 23:26 UTC, josephperrott approved these changes
LGTM

2022-02-07 23:27 UTC, josephperrott approved these changes
LGTM

Approved-for: global-approvers

2022-02-07 23:33 UTC, mary-poppins commented
You can preview b58c9b5 at https://pr45002-b58c9b5.ngbuilds.io/.

2022-02-09 18:23 UTC, alxhub commented
This PR was merged into the repository by commit 7ea70c4292efbc775390dd898decd14d8cbe8df0.

2022-02-09 18:23 UTC, closed without merging