build(bazel): add bazel target for aio build
angular/angular pull request #45022
Opened 2022-02-08 23:24 UTC by kormide

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?

Added a target for the aio project to be built by bazel. It does not yet include the generated content and is not used by the ci.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Since architect requires the generated ngsw-config.json to be in the source root, I added a rule that will write to it and ensure it exists and is up to date (see [write_source_files](https://docs.aspect.build/aspect-build/bazel-lib/v0.4.3/docs/docs/write_source_files-docgen.html)). I chose to commit that file here, and that will be required once aio is fully built with bazel, but if you prefer I can leave it uncommitted for now---running the bazel build on aio will just pop out an error with a command to generate it.

Another decision I made was to move the ngsw-config.json out of `src/generated` to the root. This is because on each regular build the `generated` folder is deleted, and since I would need a `BUILD.bazel` file in there to stamp the `write_source_files`, it would be deleted and someone developing using the regular build would see the file missing in their git diff.

Overall this is a first partial step in the migration.

2022-02-08 23:26 UTC, kormide commented on WORKSPACE
> +)
I think the desired outcome is to use a single external npm repository for angular and aio, but for the purposes of migrating it's simpler right now to keep them separated.

2022-02-09 00:10 UTC, josephperrott commented on aio/BUILD.bazel
> +npm_package_bin(
I can't come up with it in my head right now, but it seems to me that it should be possible to just provide this output in a way that it can be directly relied on as a dependency for `//aio:build` and just generated during build.

2022-02-09 00:13 UTC, josephperrott commented on WORKSPACE
> +)
Yep, we definitely want to move to one, but its definitely understandable that it complicates things during migration.  Once its migrated it will be much easier to merge them.

2022-02-09 07:20 UTC, kormide commented on aio/BUILD.bazel
> +npm_package_bin(
The issue is that `architect` expects this file to exist in the source tree and won't look in the bazel output directory, so we either need to change architect or write the generated file to the source tree like I did here.

2022-02-10 19:22 UTC, devversion commented on aio/BUILD.bazel
> +write_source_files(
I know this is maintained externally, but the name of the rule/macro seems missing some important information IMO. i.e. that is also comes with a test for ensuring the checked-in file stays up-to-date.

We should add a comment I think, and potentially a better name can be determined? I liked `generated_file_tests` because really what we are doing is testing that the generated file matches with an input.

2022-02-10 19:22 UTC, devversion commented on aio/scripts/build-ngsw-config.js
> +    : NGSW_CONFIG_OUTPUT_PATH;
Nit: I think we should extract the argument parsing to the beginning of the function for readability. Something like:

2022-02-10 19:22 UTC, devversion commented on aio/BUILD.bazel
> +npm_package_bin(
Is there any design doc or something on the approach being taken with the architect runner? I'm just a little curious personally because it seems really like it wouldn't provide a lot benefit if we'd move forward with this long-term. I might be missing something though and would like to hear more 😄 or is this just in the interim as part of "beginning the migration"?

2022-02-10 19:45 UTC, kormide commented on aio/BUILD.bazel
> +npm_package_bin(
I haven't explored the architect approach yet. I'll look into what would be involved and I'll share that with you.

2022-02-12 01:27 UTC, gregmagolan commented on WORKSPACE
> +)
Agreed. It's better sequencing to hoist the deps after aio is fully cut-over to bazel so we don't break the legacy build

2022-02-12 01:31 UTC, gregmagolan commented on aio/BUILD.bazel
> +npm_package_bin(
Might be possible to add a flag to angular-cli that accepts additional root dirs to inject into the tsconfig it is using. That would allow it to resolve imports from the bazel out tree.

It is the shape: https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/typescript/test/ts_project/tsconfig-base.json#L14. In this case, we're manually adding all of the possible platforms which is not great. Actually, it might work to do something similar in `aio/tsconfig.json`. @alexeagle has been talking to the typescript team to provide a better API that we can hook into for this problem.

2022-02-12 01:34 UTC, gregmagolan commented on aio/BUILD.bazel
> +write_source_files(
we could rename at load at the top with `generated_files_test = "write_source_files"` or wrap with a macro to rename it to your preference.

the naming we settled on is of the same vein as `write_file` from `bazel/sky-lib` but with the added implicit test since we're writing to the source tree

2022-02-12 01:39 UTC, gregmagolan commented on aio/BUILD.bazel
> +npm_package_bin(
@devversion, the benefit of using architect() in this case is it is roughly equivalent to bazel calling the angular-cli directly so you keep all of the same semantics of the current build. You don't get a speed improvement at all for the build you you do get onto the bazel graph and you get cacheing. To break out the aio build into a fine grained build with `ts_project(with ngc)` or `ng_module` would be a much larger effort and you'd loose everything youget with the angluar-cli for free. Might not be worth it. The end result there is that you're no longer using the angular-cli for aio as well and it seems that this is a nice test piece of an application to use all of its built-in features.

2022-02-12 01:41 UTC, gregmagolan commented on WORKSPACE
> +)
I suppose one consideration for angular aio developers if we hoist the deps is that they can still use the angular-cli to perform upgrades

2022-02-16 19:54 UTC, kormide commented on WORKSPACE
> +    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/4.6.2/rules_nodejs-4.6.2.tar.gz"],
We backported a fix needed for `chdir` to work in the `architect_test` rule.

2022-02-16 21:29 UTC, kormide commented on aio/BUILD.bazel
> +npm_package_bin(
@josephperrott @devversion Do you have a preference between the `write_source_files` approach versus injecting additional rootDirs as Greg described?

2022-02-18 18:12 UTC, josephperrott approved these changes
LGTM

Would love @devversion and @gkalpak to take a look as well

2022-02-18 18:18 UTC, kormide commented on aio/BUILD.bazel
> +write_source_files(
@devversion Do you still prefer to use the name `generated_files_test` here?

2022-02-18 19:33 UTC, devversion commented on aio/BUILD.bazel
> +write_source_files(
@kormide Yeah, if that is possible. That would be preferred personally.

2022-02-18 19:50 UTC, devversion approved these changes
LGTM, one question & the rename of `write_source_files`

2022-02-18 19:50 UTC, devversion commented on aio/BUILD.bazel
> +        "no-bazelci-mac",
Quick question: Is this relevant to the Angular repo here? I don't remember us using Mac

2022-02-18 20:04 UTC, kormide commented on aio/BUILD.bazel
> +        "no-bazelci-mac",
This is boilerplate I copied over from the angular example in rules_nodejs. You're right I don't think we need it. Will remove.

2022-02-18 20:24 UTC, kormide commented on aio/BUILD.bazel
> +write_source_files(
Updated.

2022-02-18 20:33 UTC, kormide commented
> LGTM, one question & the rename of `write_source_files`

Addressed both.

2022-02-23 18:29 UTC, josephperrott requested changes
@kormide After discussing the change a bit with @gkalpak we wanted to actually ask if you could create a plan/proposal for this migration to using bazel?

We want to make sure we understand how the orchestration of the build will work with many of the generated items, as well as ensuring that everything is simple enough for contributors not familiar with bazel.

2022-02-24 00:21 UTC, gregmagolan commented on aio/BUILD.bazel
> +npm_package_bin(
Sounds good. @devversion, the alternative to using the angular-cli via the `architect` entry point here is to do a full bazel migration and break up the graph. We compile sass in separate targets, use ts_project(with ngc) or ng_module rules to transpile typescript -> javascript and then finally bundle with webpack or esbuild.

We've done these before and the end result is more incremental (since you can break up the graph into smaller targets) but it is harder to maintain.

2022-02-24 00:25 UTC, gregmagolan commented
> @kormide After discussing the change a bit with @gkalpak we wanted to actually ask if you could create a plan/proposal for this migration to using bazel?
> 
> We want to make sure we understand how the orchestration of the build will work with many of the generated items, as well as ensuring that everything is simple enough for contributors not familiar with bazel.

Sounds good. We'll write up a brief document on the approach. In short, with the architect() approach where we're levering the angular-cli build as a single target the bazel build configuration should be minimal and easy to maintain.

Developers should be able to build locally with bazel or use the angular-cli... although there is a danger that the local angular-cli build could regress if there is no coverage on CI for it. Not sure how to address that. Perhaps a CI cron job that runs the legacy build at least once a day from HEAD if you still want to use it?

The output of the build is a directory artifact that should be identical to what comes out of the current legacy build and then that is fed into whatever your release/deploy mechanism currently is.

2022-03-04 19:55 UTC, gkalpak reviewed
I left a few comments/questions, but the rest looks reasonable to me (although I won't pretend I understand 100% what's going on :grin:).

One more question:
I noticed that the `pre~~build` script that builds `ngsw-config.json` was "bazelified" in this PR, but the [post~~build][1] script wasn't. Is that intentional?

[1]: https://github.com/angular/angular/blob/31dcc8ca9a1d1b20431652ec654fdef9fe030ff3/aio/package.json#L77

2022-03-04 19:55 UTC, gkalpak commented on WORKSPACE
> +http_archive(
Consider adding a comment explaining what this is needed for.

2022-03-04 19:55 UTC, gkalpak commented on aio/BUILD.bazel
> +load("@aspect_bazel_lib//lib:write_source_files.bzl", generated_files_test = "write_source_files")
Are there any docs for this?

2022-03-04 19:55 UTC, gkalpak commented on aio/BUILD.bazel
> +APPLICATION_DEPS = [
Could you add a comment on what kinds of deps should go into this list?

2022-03-04 19:55 UTC, gkalpak commented on aio/BUILD.bazel
> +    "@aio_npm//@types/trusted-types",
Does ordering matter here? Could we order these alphabetically?

2022-03-04 19:55 UTC, gkalpak commented on aio/BUILD.bazel
> +            # build until the whole project is build by bazel and this directory
Nit:

```suggestion
            # build until the whole project is built by bazel and this directory
```

2022-03-04 19:55 UTC, gkalpak commented on aio/ngsw-config.json
> +{
This file should not be checked in, right?
(If so, we should also add it to `.gitignore`.)

2022-03-04 19:55 UTC, gkalpak commented on aio/angular.json
> +            "ngswConfigPath": "ngsw-config.json",
OOC, why this change? Couldn't bazel output the file in `src/generated/`?
It would be cleaner for the workspace to have generated/not-checked-in files in a dedicated directory rather than in the root dir.

2022-03-04 20:04 UTC, kormide commented
> I left a few comments/questions, but the rest looks reasonable to me (although I won't pretend I understand 100% what's going on grin).
> 
> One more question: I noticed that the `pre~~build` script that builds `ngsw-config.json` was "bazelified" in this PR, but the [post~~build](https://github.com/angular/angular/blob/31dcc8ca9a1d1b20431652ec654fdef9fe030ff3/aio/package.json#L77) script wasn't. Is that intentional?

This PR is incremental and doesn't yet replace the legacy build (and is not built by ci), so the answer to your question is that might be required but I haven't gotten there yet.

2022-03-04 20:04 UTC, kormide commented on aio/BUILD.bazel
> +load("@aspect_bazel_lib//lib:write_source_files.bzl", generated_files_test = "write_source_files")
Yup: https://docs.aspect.build/aspect-build/bazel-lib/v0.5.0/docs/docs/write_source_files-docgen.html

2022-03-04 20:06 UTC, kormide commented on aio/BUILD.bazel
> +    "@aio_npm//@types/trusted-types",
Ordering doesn't matter. I'll see if there's something I can do buildifier orders them, but if not I'll do it manually.

2022-03-04 20:10 UTC, kormide commented on aio/ngsw-config.json
> +{
So the issue was that architect only knows how to look for this file in the source directory, where it's currently generated before the build. It doesn't know how to look into some bazel output directory (and doesn't have a flag we can pass to tell it where to look). One option is to change architect. Another option (which we did here) is to have bazel generate and write it to the source directory. Bazel only lets you write the source directory on a `bazel run`, not a bazel build, so we have to commit it to the repo. However, the rule we're using, `write_source_files`, also stamps out tests that will fail if the file is ever out of date.

For now, the legacy build will continue to overwrite it, and it doesn't matter if it's committed or not (though I can see that being an awkward DX). The bazel test will demand that it be updated, and will give the user the command to update it before tests will pass.

2022-03-04 20:11 UTC, kormide commented on aio/angular.json
> +            "ngswConfigPath": "ngsw-config.json",
I can have bazel write the file to `src/generated`. I just figured that this was simpler since the `src/generated` folder is cleared on a legacy build. I'd have to change that yarn script to (or maybe write a separate script that yarn invokes) to delete everything except for this file.

Either works. Let me know what you think.

2022-03-04 20:14 UTC, kormide commented on aio/ngsw-config.json
> +{
Perhaps we can commit it, then add it to `.gitignore` right after so that it won't bother current developers? Then we'll remove it once the build is fully under bazel.

2022-03-07 22:50 UTC, kormide commented on aio/ngsw-config.json
> +{
What I suggested above with `.gitignore` won't work, as files that are checked in cannot be then ignored by git.

2022-03-07 22:51 UTC, kormide commented on WORKSPACE
> +http_archive(
Added

2022-03-07 22:52 UTC, kormide commented on aio/BUILD.bazel
> +APPLICATION_DEPS = [
Added

2022-03-08 20:55 UTC, gkalpak commented on aio/angular.json
> +            "ngswConfigPath": "ngsw-config.json",
I do think that having generated files in a dedicated folder is a good idea. We could create a new directory for this (something like `src/bazel-generated/`) and just `.gitignore` that, so that we don't have to alter/complicate the legacy clean-up script.

2022-03-08 20:58 UTC, gkalpak commented on aio/ngsw-config.json
> +{
1. Why can't checked-in files be `.gitignore`'d?
2. Why can't the architect look for the file in an alternative location? Is the path of this hard-coded into the architect? That would be very strange 🤔 Doesn't the architect look at the `angular.json` file?

2022-03-08 21:06 UTC, gkalpak commented on aio/BUILD.bazel
> +load("@aspect_bazel_lib//lib:write_source_files.bzl", generated_files_test = "write_source_files")
Thx!

I don't know if it's just me, but I think it would be useful to add this link as a comment :grin:

2022-03-08 21:14 UTC, gkalpak reviewed
Thx for addressing my comments, @kormide ❤️
I've left a couple more comments/questions.

2022-03-08 21:14 UTC, gkalpak commented on aio/BUILD.bazel
> +# Deps required to build the architect application
Thx for adding this comment :+1:

Could you expand a bit in order to help the reader understand what kind of stuff should go here. I.e. I want to know when I should add a new dep here.

For example, if I add a new dependency in `aio/package.json`, I am not sure if it should go here as well. (As you can tell, I am not too familiar with bazel 😇)

By looking at this list, it seems that `package.json > dependencies` should go here, but then I see some `package.json > devDependencies` (but not all). So, how do you make the distinction?

2022-03-09 19:07 UTC, kormide commented on aio/ngsw-config.json
> +{
1. I tried this, but if a file has been previously checked in, then git ignores the .gitignore statement and you see changes to the file.
2. You're right that the path to `ngsw-config.json` is set in `angular.json`, but the bazel output path depends on the host platform so we'd have to template the angular.json file and bazel would have to generated one with the right path. But I think that would cause some other problems since architect runs in the root of the source tree but the generated angular.json would be in the output directory, and I think we've come full circle back to the original problem. I think the only way to do this without writing to the source tree would be to change architect to accept and command line argument that can point to the generated ngsw-config in the output dir.

2022-03-09 19:12 UTC, kormide commented on aio/BUILD.bazel
> +# Deps required to build the architect application
Good call, I'll add some more prescriptive comments here.

2022-03-09 19:26 UTC, kormide commented on aio/angular.json
> +            "ngswConfigPath": "ngsw-config.json",
The consequence of this approach for the developer is...
* If something causes the generated ngsw-config.json to change, then developers will notice the changes in their git status after a build. I'm not familiar with service workers so I don't know how often that would occur.
* They can choose to commit it with their changes or not. The legacy build overwrites it with the most up to date version anyway.
* The bazel build (which devs are not using and is not yet part of ci) will complain if the file committed to source isn't up to date. It can then be updated and committed with any other changes.

So it's a bit quirky until we flip to bazel.

2022-03-09 19:27 UTC, kormide commented on aio/angular.json
> +            "ngswConfigPath": "ngsw-config.json",
@gregmagolan Can you think of any other way we can do this without degrading the experience?

2022-03-09 19:54 UTC, kormide commented on aio/BUILD.bazel
> +# Deps required to build the architect application
I reorganized how the files and deps are grouped and added some comments. Is this clearer?

> For example, if I add a new dependency in aio/package.json, I am not sure if it should go here as well. (As you can tell, I am not too familiar with bazel innocent)

If you add a new dependency to package.json and a source file imports it, bazel will complain that it's missing if you didn't include here.

2022-03-09 19:55 UTC, kormide commented on aio/BUILD.bazel
> +# Deps required to build the architect application
> By looking at this list, it seems that package.json > dependencies should go here, but then I see some package.json > devDependencies (but not all). So, how do you make the distinction?

I had to add the build-angular dependency here because the architect rule we're invoking requires it.

2022-03-10 00:21 UTC, gregmagolan commented on aio/angular.json
> +            "ngswConfigPath": "ngsw-config.json",
Hmmm. If the file falls out of date then bazel CI will fail so developers would have to update it anyway to get a green CI.

2022-03-10 00:21 UTC, gregmagolan commented on aio/angular.json
> +            "ngswConfigPath": "ngsw-config.json",
Oh I see. For this in-between before their bazel CI is turned on it is confusing

2022-03-10 00:34 UTC, gregmagolan commented on aio/angular.json
> +            "ngswConfigPath": "ngsw-config.json",
You could make use a different file path for the bazel build vs. the legacy build. It looks like there is only one place that it is loaded
```
export function getSwNavigationUrlChecker() {
  const config = loadJson(`${AIO_DIR}/src/generated/ngsw-config.json`);
```
in `aio/tests/deployment/shared/helpers.ts` and it would be a trivial `if (isBazel)` there to choose a different path so the legacy flow is not affect at all until bazel is on CI

2022-03-10 00:55 UTC, Awnisaeed commented
--
Sent from myMail for Android الخميس, ١٠ مارس ٢٠٢٢, ٠٣:٣٧ص +03:00 from Greg Magolan  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  aio/angular.json :
> @@ -32,7 +32,7 @@
>             "index": "src/index.html",
>             "main": "src/main.ts",
>             "polyfills": "src/polyfills.ts",
>-            "ngswConfigPath": "src/generated/ngsw-config.json",
>+            "ngswConfigPath": "ngsw-config.json",
>
>You could make use a different file path for the bazel build vs. the legacy build. It looks like there is only one place that it is loaded
>export function getSwNavigationUrlChecker() {
>  const config = loadJson(`${AIO_DIR}/src/generated/ngsw-config.json`);
>
>in aio/tests/deployment/shared/helpers.ts and it would be a trivial if (isBazel) there to choose a different path so the legacy flow is not affect at all until bazel is on CI
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you are subscribed to this thread. Message ID:  @ github . com>

2022-03-10 07:02 UTC, kormide commented on aio/angular.json
> +            "ngswConfigPath": "ngsw-config.json",
I think the main case is the reference to the file in `angular.json`, where we can't add that conditional logic. I suppose we could maintain a `angular.bazel.json` until we're ready to switch over.

2022-03-10 07:07 UTC, kormide commented on aio/angular.json
> +            "ngswConfigPath": "ngsw-config.json",
Wdyt @gkalpak?

2022-03-10 16:10 UTC, gkalpak approved these changes
LGTM (pending the discussions in the unresolved comments from previews reviews) :+1:
Thx for putting this together, @kormide 👏

2022-03-10 17:25 UTC, kormide commented on aio/angular.json
> +            "ngswConfigPath": "ngsw-config.json",
The file would still need to be checked into source since we're using the architect rule, which doesn't know how to look for that file in the bazel output directory (where bazel must put all files it generates during a build).

2022-03-10 17:55 UTC, josephperrott approved these changes
LGTM

2022-03-11 18:16 UTC, gkalpak commented on aio/angular.json
> +            "ngswConfigPath": "ngsw-config.json",
For posterity:
@kormide and I discussed this "offline" and decided to keep `ngsw-config.json` at the AIO root while we are in the transitional phase. Once we have fully switched AIO to Bazel, we will move it to a dedicated directory (e.g. `src/bazel-genenerated`)  to more clearly convey that this file is generated and people should not manually edit it.

2022-03-14 16:25 UTC, closed without merging