docs(docs-infra): fix the stackblitz on page i18n-example
angular/angular pull request #45097
Opened 2022-02-15 22:54 UTC by GuillaumeBonnet

Pasted from the issue #45066
> Description
> The provided I18n live example does not run succesfully and raises an error.
>
>What is the affected URL?
>https://angular.io/guide/i18n-example

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The provided I18n live example does not run succesfully and raises an error.

Issue Number: #45066

## What is the new behavior?
The provided I18n live example runs succesfully.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-02-17 07:20 UTC, alan-agius4 commented on aio/content/examples/i18n/angular.json
> +              "browserTarget": "angular.io-example:build:development:fr"
```suggestion
              "browserTarget": "angular.io-example:build:development,fr"
```

2022-02-17 07:21 UTC, alan-agius4 commented on aio/content/examples/i18n/angular.json
> +            "development:fr": {
This new section is redundant as you can run the builder with multiple configurations. 

Ex: `angular.io-example:build:development,fr`

2022-02-17 07:23 UTC, alan-agius4 commented on aio/content/examples/i18n/angular.json
> +              "localize": ["fr"],
```suggestion
              "localize": false,
```

2022-02-17 07:24 UTC, alan-agius4 requested changes
Thanks for this. 

Just to minor comments.

2022-02-17 18:07 UTC, alan-agius4 approved these changes

2022-02-17 18:07 UTC, alan-agius4 approved these changes
LGTM, thanks for this.

2022-02-17 18:12 UTC, GuillaumeBonnet commented
Thank you for the changes,

I think having the french translation showing by default is better for the i18n chapter and that's what the failing e2e test expected.

Can we add the aoi:preview label to check the result ?

### package.json
The scripts in the package.json of the example are:
```json
"start": "ng serve",
"start:fr": "ng serve --configuration=fr",
"build": "ng build",
"build:fr": "ng build --configuration=production-fr",
```

- "production-fr" is not a configuration anymore.
- does it make sense to have "build:fr" since "build" already build the two languages?
- "start:fr" doesn't make sense to have because "start" is already fr
- do we need a 'start:enUS' ?

2022-02-17 18:21 UTC, mary-poppins commented
You can preview f6c71e2 at https://pr45097-f6c71e2.ngbuilds.io/.
You can preview 9e6cb3c at https://pr45097-9e6cb3c.ngbuilds.io/.

2022-02-17 18:29 UTC, alan-agius4 commented
- `build:fr` can indeed be removed now. 
- `start:enUS` - not needed since `start` will load the default locale which is `en`.
- "start:fr" this is needed as start is `en`.

2022-02-17 18:48 UTC, GuillaumeBonnet commented
I misunderstood the config, `start` does load in `en`.
I removed that one `build:fr` line

2022-02-17 18:54 UTC, mary-poppins commented
You can preview 59fcf34 at https://pr45097-59fcf34.ngbuilds.io/.

2022-02-17 19:06 UTC, mary-poppins commented
You can preview 28faf51 at https://pr45097-28faf51.ngbuilds.io/.

2022-02-17 19:42 UTC, GuillaumeBonnet commented
test `//src/material/select:unit_tests_firefox` failed for commit [28faf51](https://github.com/angular/angular/commit/28faf5134832d5c293b00b4e296bef708f5509d1) when it passed for the previous commit [9e6cb3c](https://github.com/GuillaumeBonnet/angular/commit/9e6cb3c24dbb1bd53770406ce0906ed4e0a4d57c).
The differences are so small that I don't get why it would fail, can we restart the failing ci step ?

2022-02-17 19:49 UTC, alan-agius4 commented
> test `//src/material/select:unit_tests_firefox` failed for commit [28faf51](https://github.com/angular/angular/commit/28faf5134832d5c293b00b4e296bef708f5509d1) when it passed for the previous commit [9e6cb3c](https://github.com/GuillaumeBonnet/angular/commit/9e6cb3c24dbb1bd53770406ce0906ed4e0a4d57c).
> The differences are so small that I don't get why it would fail, can we restart the failing ci step ?

That should be a flake. I’ll restart the CI step.

2022-02-18 09:00 UTC, alan-agius4 approved these changes

2022-02-18 09:46 UTC, josephperrott approved these changes
LGTM

2022-02-22 11:40 UTC, hossein13m approved these changes
everything seems OK

2022-02-28 01:10 UTC, AndrewKushnir approved these changes

2022-02-28 17:25 UTC, jessicajaniuk commented
This PR was merged into the repository by commit cbbf13f1004f2f40bd08381d2420375da9e8c029.

2022-02-28 17:25 UTC, closed without merging