Fix service worker generation
angular/angular pull request #45262
Opened 2022-03-04 12:01 UTC by LucaBruni

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #45133

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-03-04 16:51 UTC, gkalpak requested changes
Thx, @LucaBruni :+1:
I left a couple of minor comments - otherwise this looks good 🚀

2022-03-04 16:51 UTC, gkalpak commented on packages/service-worker/config/test/generator_spec.ts
> +    const files = [...Array(fileCount).keys()].reduce((acc: any, _, i) => {
Let's not use `any`:

```suggestion
    const files = [...Array(fileCount).keys()].reduce((acc: Record<string, string>, _, i) => {
```

2022-03-04 16:51 UTC, gkalpak commented on packages/service-worker/config/test/generator_spec.ts
> +        .toBeTruthy();
Please break this up into multiple assertions.

(BTW, have you verified that the test fails without your changes?)

2022-03-04 16:52 UTC, gkalpak commented
Also, please squash the commits into one.

2022-03-07 09:23 UTC, LucaBruni commented on packages/service-worker/config/test/generator_spec.ts
> +        .toBeTruthy();
Thanks, we'll update the PR with the suggested modifications.
And about the failed tests, we noticed the CI messages, so we immediately tried the tests again, but under linux we had no problems with or without our commit (on windows we had some problems during build, so we quickly switched to linux)

2022-03-08 12:56 UTC, gkalpak requested changes
Thx for making the changes, @LucaBruni :+1:
One last comment and this should be good to go 🚀

2022-03-08 12:56 UTC, gkalpak commented on packages/service-worker/config/test/generator_spec.ts
> +    expect(fs.maxConcurrentHashings).toBeLessThanOrEqual(500);
Out of curiosity, why not use `.toBe(500)`? Are there cases where this assertion would fail (for example, a race condition)?
My concern with `toBeLessThanOrEqual(500)` is that it would succeed even if `maxConcurrentHashings` was 1 (meaning that we accidentally made the `Generator` process files serially).

So, if it is not possible to go for `.toBe(500)`, I would at least add another assertion to ensure files were processed in parallel (i.e. something like `expect(fs.maxConcurrentHashings).toBeGreaterThan(1)`).

2022-03-08 14:48 UTC, gkalpak approved these changes
LGTM

2022-03-08 18:23 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 3ecf93020ce06b9b8621f0c83126cb3d584d4181.

2022-03-08 18:23 UTC, closed without merging