fix(router): merge inherited resolved data and static data in layers
angular/angular pull request #45276
Opened 2022-03-05 12:06 UTC by martinsik

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Right now, route static `data` are collected from its parents based on the logic described in [`router_state.ts`](https://github.com/angular/angular/blob/14.0.0-next.5/packages/router/src/router_state.ts#L217-L244), **merged into a single object and then merged again with merged data from resolvers**. This means that a **child's data will be overriden by a resolver defined in its parent (#34361) if they're using the same keys**. However, I don't think this behavior is documented anywhere, resolvers are used in https://angular.io/guide/router-tutorial-toh#resolve-pre-fetching-component-data but it doesn't mention the way static `data` is merged with resolved data.

The logic when and why route's data is merged with its parents isn't documented anywhere either (at least I couldn't find anything). Based on the logic here [`inheritedParamsDataResolve()`](https://github.com/angular/angular/blob/14.0.0-next.5/packages/router/src/router_state.ts#L217`) a route inherits its parent's data (recursively) only when:
- The route has an empty path.
- Its parent is componentless.

For example the following route structure:

```
[{
  path: 'a',
  component: WrapperCmp,
  resolve: {prop2: 'resolveTwo'},
  data: {prop: 'wrapper-a'},
  children: [
    // will inherit data from this child route because it has `path` and its parent has component
    {
      path: 'b',
      data: {prop: 'nested-b'},
      resolve: {prop3: 'resolveFour'},
      children: [
        {
        path: 'c',
        children:
          [{path: '', component: NestedComponentWithData, data: {prop3: 'nested'}}]
        },
      ]
    },
  ],
}]
```

... will for URL `/a/b/c` produce `{prop: 'nested-b', prop3: 4}` data for component `NestedComponentWithData`. This is because `'c'` inherits data from `'b'` (but not `'a'`) and the resolver `{prop3: 'resolveFour'}` will override static data set in `'c'` (`{prop3: 'nested'}`). This is the same situation as in #34361.

Stackblitz demo: https://stackblitz.com/edit/angular-ivy-ynjet6?file=src%2Fapp%2Fapp.module.ts

Issue Number: #34361

## What is the new behavior?

This PR changes this behavior and merges static data and resolved data in "layers" (route by route) so child's static data and resolved data cannot be overriden by their parents.

For the same example the data generated for route `'c'` will be `{prop: 'nested-b', prop3: 'nested'}` because `prop3` has priority over `prop3` defined in the parent route.

I also added more tests to cover the expected behavior when inheriting data from parents as defined by `inheritedParamsDataResolve()`.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

This is probably a breaking change, although the current behavior doesn't seem to be defined anywhere so it's hard to tell if anyone might be rallying on it.

## Other information

2022-03-05 12:08 UTC, martinsik commented on packages/router/test/operators/resolve_data.spec.ts
> +      outputTransition.guards.canActivateChecks[1].route.data = {e2: 4};
I'm actually not sure how/why these tests worked because `_resolvedData` should be merged into `data`.`

2022-03-07 20:52 UTC, atscott requested changes
Thanks for the fix and additional tests! I believe what you've done does produce the correct result now. That said, I think this can be achieved in a much simpler way:

Here's the `git diff` I have:

```
diff --git a/packages/router/src/operators/resolve_data.ts b/packages/router/src/operators/resolve_data.ts
index fb5f42e9ab..5f484978b2 100644
--- a/packages/router/src/operators/resolve_data.ts
+++ b/packages/router/src/operators/resolve_data.ts
@@ -62,8 +62,9 @@ function runResolve(
       .pipe(map((resolvedData: any) => {
         futureARS._resolvedData = resolvedData;
         futureARS.data = {
+          ...inheritedParamsDataResolve(futureARS, paramsInheritanceStrategy).resolve,
           ...data,
-          ...inheritedParamsDataResolve(futureARS, paramsInheritanceStrategy).resolve
+          ...resolvedData,
         };
         return null;
       }));
```

1. Start with the inherited resolved data. We only care about resolved data at this stage because static data was already taken care of during route recognition [here](https://github.com/angular/angular/blob/d336ba96d922363235688f54d8af108ef7ab01f0/packages/router/src/recognize.ts#L75-L87)
2. Overwrite that with any static data the explicitly exists on the current `Route`
3. Overwrite that with any resolved data from the current `Route`

2022-03-09 16:16 UTC, martinsik commented on packages/router/test/operators/resolve_data.spec.ts
> +      outputTransition.guards.canActivateChecks[1].route.data = {e2: 4};
I think this was working because these tests are using `deepClone()`...

2022-03-09 22:14 UTC, martinsik commented
@atscott I forgot to add one more test (and didn't realize my original implementation was failing there as well). In this use-case:

```
router.resetConfig([{
 path: 'a',
 component: WrapperCmp,
 resolve: {prop2: 'resolveTwo'},
 data: {prop: 'wrapper-a'},
 children: [
   // will inherit data from this child route because it has `path` and its parent has
   // component
   {
     path: 'b',
     data: {prop2: 'parent-b', prop: 'parent-b'},
     children: [
       {
         path: 'c',
         resolve: {prop2: 'resolveFour'},
         children: [
           {
             path: '',
             component: NestedComponentWithData,
             data: {prop: 'nested-d'},
           },
         ]
       },
     ]
   },
 ],
}]);
```
`NestedComponentWithData` should receive data `{prop: 'nested-d', prop2: 4}`. Route `b` defines static data `prop2: 'parent-b'` that is override in route `'c'` by resolver `resolveFour`. But if I merge data with the following:

```
futureARS.data = {
  ...inheritedParamsDataResolve(futureARS, paramsInheritanceStrategy).resolve, // already merged with inherited routes
  ...data, // already merged with inherited routes
  ...resolvedData, // this route's resolved data
};
```

...then static `data` from route `'b'` will override resolved data from `'c'`. This is basically the same problem as in #34361, just the roles of what overrides what are reversed. This is the [relevant unit test](https://github.com/angular/angular/pull/45276/files#diff-c89e4eb845a28c0d2385a4460f9d27259558686f192bdb0fe61953e057be803eR2305-R2344).

I tried to debug the whole thing again and was able to simplify it a little bit comapred to what I made previously.

2022-03-09 23:20 UTC, atscott commented
@martinsik Good catch and thanks for the additional test. My main issue with the fix here is that it's duplicating and fixing the logic that already exists in `flattenInherited` rather than fixing it there. Here's the new git diff I have which also passes your new test:

```
diff --git a/packages/router/src/operators/resolve_data.ts b/packages/router/src/operators/resolve_data.ts
index fb5f42e9ab..a9af4a979e 100644
--- a/packages/router/src/operators/resolve_data.ts
+++ b/packages/router/src/operators/resolve_data.ts
@@ -10,7 +10,7 @@ import {Injector} from '@angular/core';
 import {EMPTY, from, MonoTypeOperatorFunction, Observable, of} from 'rxjs';
 import {concatMap, map, mergeMap, take, takeLast, tap} from 'rxjs/operators';
 
-import {ResolveData} from '../models';
+import {ResolveData, Route} from '../models';
 import {NavigationTransition} from '../router';
 import {ActivatedRouteSnapshot, inheritedParamsDataResolve, RouterStateSnapshot} from '../router_state';
 import {wrapIntoObservable} from '../utils/collection';
@@ -50,21 +50,16 @@ function runResolve(
     paramsInheritanceStrategy: 'emptyOnly'|'always', moduleInjector: Injector) {
   const config = futureARS.routeConfig;
   const resolve = futureARS._resolve;
-  const data = {...futureARS.data};
-  if (config?.title !== undefined) {
-    if (typeof config.title === 'string' || config.title === null) {
-      data[RouteTitle] = config.title;
-    } else {
-      resolve[RouteTitle] = config.title;
-    }
+  if (config?.title !== undefined && !hasStaticTitle(config)) {
+    resolve[RouteTitle] = config.title;
   }
   return resolveNode(resolve, futureARS, futureRSS, moduleInjector)
       .pipe(map((resolvedData: any) => {
         futureARS._resolvedData = resolvedData;
-        futureARS.data = {
-          ...data,
-          ...inheritedParamsDataResolve(futureARS, paramsInheritanceStrategy).resolve
-        };
+        futureARS.data = inheritedParamsDataResolve(futureARS, paramsInheritanceStrategy).resolve;
+        if (config && hasStaticTitle(config)) {
+          futureARS.data[RouteTitle] = config.title;
+        }
         return null;
       }));
 }
@@ -106,3 +101,7 @@ function getResolver(
   return resolver.resolve ? wrapIntoObservable(resolver.resolve(futureARS, futureRSS)) :
                             wrapIntoObservable(resolver(futureARS, futureRSS));
 }
+
+function hasStaticTitle(config: Route) {
+  return typeof config.title === 'string' || config.title === null;
+}
diff --git a/packages/router/src/router_state.ts b/packages/router/src/router_state.ts
index 45de9af4a2..96c2926194 100644
--- a/packages/router/src/router_state.ts
+++ b/packages/router/src/router_state.ts
@@ -248,9 +248,9 @@ function flattenInherited(pathFromRoot: ActivatedRouteSnapshot[]): Inherited {
   return pathFromRoot.reduce((res, curr) => {
     const params = {...res.params, ...curr.params};
     const data = {...res.data, ...curr.data};
-    const resolve = {...res.resolve, ...curr._resolvedData};
+    const resolve = {...res.resolve, ...curr.routeConfig?.data, ...curr._resolvedData};
     return {params, data, resolve};
-  }, <any>{params: {}, data: {}, resolve: {}});
+  }, {params: {}, data: {}, resolve: {}});
 }
 
 /**
```

2022-03-20 16:16 UTC, martinsik commented
@atscott I understand what you mean. When I implemented the first solution I posted here I was thinking if changing the `flattenInherited` function won't alter its expected behavior. I thought it's supposed to merge static data and resolved data separately but now with:

```
const resolve = {...res.resolve, ...curr.routeConfig?.data, ...curr._resolvedData};
```
it's already combining static and resolved data so I'm not sure this is expected from `flattenInherited`. But this solution is definitelly easier than mine :).

2022-03-21 16:51 UTC, atscott commented
> I thought it's supposed to merge static data and resolved data separately but now with

@martinsik Yea, I think that was certainly the idea but as pointed out in #34361 and what you've found during the fix up here, this doesn't work or provide anything truly useful as an intermediate output. Since we only use this value in one place, we can change the meaning of the "resolve" to be the "merged and final data, including resolved data". That's what we want anyways. There's not much reason to produce an intermediate value and then transform it immediately.

2022-03-21 16:52 UTC, atscott approved these changes
LGTM. Thanks again for fixing this! I'll run internal tests to see if this breaks anything.

2022-03-22 01:00 UTC, atscott commented
[global presubmit](https://fusion2.corp.google.com/presubmit/tap/436234785/OCL:436234785:BASE:436191103:1647903117406:eb525161/targets) There are 3 distinct failures that will need to be investigated.

2022-03-22 21:17 UTC, atscott requested changes

2022-03-22 21:17 UTC, atscott commented on packages/router/src/router_state.ts
> +    const resolve = {...res.resolve, ...curr.routeConfig?.data, ...curr._resolvedData};
```suggestion
    const resolve = {...curr.data, ...res.resolve, ...curr.routeConfig?.data, ...curr._resolvedData};
```

Some developers have apparently discovered they can directly mutate the data in their guards/resolvers. We'll need to also copy `curr.data` to prevent that from breaking.

2022-03-26 21:15 UTC, martinsik commented on packages/router/src/router_state.ts
> +    const resolve = {...res.resolve, ...curr.routeConfig?.data, ...curr._resolvedData};
@atscott Should I include a test for this use-case even when it's probably not a recommended way of using it.

2022-03-28 17:02 UTC, atscott commented on packages/router/src/router_state.ts
> +    const resolve = {...res.resolve, ...curr.routeConfig?.data, ...curr._resolvedData};
Yea, probably. You can add a comment to the test case as well to explain why it's there. i.e. "This is not documented or recommended behavior but is here to prevent unexpected regressions. This behavior isn't necessary 'by design' but it was discovered during a refactor that some teams depend on it."

2022-04-01 23:40 UTC, atscott approved these changes

2022-04-01 23:42 UTC, atscott commented
I've removed the breaking change label. We can consider this just a bug fix since there weren't any failures detected internally due to this change.

2022-04-01 23:44 UTC, atscott commented
[final presbumit](https://fusion2.corp.google.com/presubmit/tap/436234785/OCL:436234785:BASE:438903785:1648856451038:c9a58376/targets) as a sanity check

2022-04-02 09:48 UTC, martinsik commented on packages/router/src/router_state.ts
> +    const resolve = {...res.resolve, ...curr.routeConfig?.data, ...curr._resolvedData};
Actually, it took me a while to figure out what scenario would not work without `...curr.data` :).

2022-04-04 21:56 UTC, AndrewKushnir commented
@atscott FYI the commit message still has the breaking changes section, so the merge tooling is not allowing this change to be in a patch branch. Could you please update the commit message or a label (to make it master-only)?

2022-04-04 22:15 UTC, atscott commented
@AndrewKushnir Done

2022-04-05 15:49 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 1c11a5715576632a4fb7170202395cf95dfbce09.

2022-04-05 15:49 UTC, closed without merging

2022-04-05 15:51 UTC, AndrewKushnir commented
@atscott there was a merge conflict with the patch (13.3.x) branch, so the change was merged into the master branch only. Could you please create a patch-only version of this change if needed?

2022-04-05 16:14 UTC, atscott commented
@AndrewKushnir @martinsik There's little activity on #34361 so I don't think this is a pressing issue to be backported to v13.3. I think it's okay to leave it as just a fix for v14. @martinsik If you feel differently, please open a new PR to that targets the 13.3.x branch.