docs: update component content
angular/angular pull request #45501
Opened 2022-04-01 02:09 UTC by josmar-crwdstffng

Reorganize component content to be more module and align with 1 content type per topic.

Update content in component-overview topic. 
Create new component-create topic. 
Create new component-usage topic. 
Create new component-example topic. 
Move content from existing topics. 
Update links. 
Cleanup up markdown in new topics.

## PR Checklist

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [X] Yes
- [ ] No

The changes do not affect implementation of code, but do affect the organization of content

2022-04-01 02:10 UTC, josmar-crwdstffng commented
@TMDavisGoogle 
Please perform an edit pass at your earliest convenience.
Thank you

2022-04-01 02:18 UTC, mary-poppins commented
You can preview 06ea065 at https://pr45501-06ea065.ngbuilds.io/.

2022-04-01 16:24 UTC, TMDavisGoogle commented on aio/content/errors/NG0100.md
> +This error commonly occurs when you have added template expressions or begun to implement lifecycle hooks like `ngAfterViewInit` or `ngOnChanges`.
```suggestion
This error commonly occurs when you have added template expressions or have begun to implement lifecycle hooks like `ngAfterViewInit` or `ngOnChanges`.
```

2022-04-01 18:33 UTC, dgp1130 commented
@jelbourn should we use a global approval for this? It touches a lot of things but doesn't seem to be changing much of the semantics.

2022-04-04 17:14 UTC, josmar-crwdstffng commented on aio/content/errors/NG0100.md
> +This error commonly occurs when you have added template expressions or begun to implement lifecycle hooks like `ngAfterViewInit` or `ngOnChanges`.
Updated.

```markdown
This error commonly occurs when you have added template expressions or have begun to implement lifecycle hooks like `ngAfterViewInit` or `ngOnChanges`.
```

2022-04-04 17:15 UTC, josmar-crwdstffng commented on aio/content/errors/NG0100.md
> +It is also common when dealing with loading status and asynchronous operations, or a child component changes its parent bindings.
Updated.

```markdown
It is also common when dealing with loading status and asynchronous operations, or when a child component changes its parent bindings.
```

2022-04-04 20:35 UTC, mary-poppins commented
You can preview ff289e8 at https://pr45501-ff289e8.ngbuilds.io/.

2022-04-04 20:59 UTC, mary-poppins commented
You can preview 5849e27 at https://pr45501-5849e27.ngbuilds.io/.

2022-04-05 19:21 UTC, TMDavisGoogle requested changes
Punctuation, grammar, spelling edits for clarity.

2022-04-05 19:54 UTC, josmar-crwdstffng commented on aio/content/guide/component-overview-old.md
> +Components are the main building block for Angular applications. Each component consists of:
This topic is being removed.

2022-04-05 19:55 UTC, josmar-crwdstffng commented on aio/content/guide/component-styles-old.md
> +Component styles have a few special &ast;selectors&ast; from the world of shadow DOM style scoping
This topic is being removed.

2022-04-05 19:55 UTC, josmar-crwdstffng commented on aio/content/guide/component-styles-old.md
> +In this example the host's content also becomes bold when the &grave;active&grave; CSS class is applied to the host element.
This topic is being removed.

2022-04-05 19:56 UTC, josmar-crwdstffng commented on aio/content/guide/component-styles-old.md
> +Add selectors behind the &grave;:host&grave; to select child elements, for example using &grave;:host h2&grave; to target all &grave;&lt;h2&gt;&grave; elements inside a component's view.
This topic is being removed.

2022-04-05 19:56 UTC, josmar-crwdstffng commented on aio/content/guide/component-styles-old.md
> +For example, a CSS theme class could be applied to the document &grave;&lt;body&gt;&grave; element, and
This topic is being removed.

2022-04-05 19:57 UTC, josmar-crwdstffng commented on aio/content/guide/component-styles-old.md
> +Applying the &grave;::ng-deep&grave; pseudo-class to any CSS rule completely disables view-encapsulation for
This topic is being removed.

2022-04-05 19:58 UTC, josmar-crwdstffng commented on aio/content/guide/component-styles-old.md
> +As such we plan to drop support in Angular \(for all 3 of &grave;/deep/&grave;, &grave;&gt;&gt;&gt;&grave; and &grave;::ng-deep&grave;\).
This topic is being removed.

2022-04-05 19:58 UTC, josmar-crwdstffng commented on aio/content/guide/component-styles-old.md
> +When building with the CLI, be sure to include the linked style file among the assets to be copied to the server as described in the \[Assets configuration guide\]\(guide/workspace-config&num;assets-
This topic is being removed.

2022-04-05 19:58 UTC, josmar-crwdstffng commented on aio/content/guide/component-styles-old.md
> +Once included, the CLI includes the stylesheet, whether the link tag's href URL is relative to the application root or the component file.
This topic is being removed.

2022-04-05 20:04 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-dynamic-load.md
> +Use the `loadComponent()` method complete the majority of the work for you.
Updated.

```markdown
Use the `loadComponent()` method to complete the majority of the work for you.
```

2022-04-05 20:05 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-usage-complex-content-projection.md
> +Typically usage for [Multi-slot Content Projection][AioGuideComponentUsageMultiSlotContentProjection] include using an attribute, element, style defintion, or some combination of all three to identif
Updated.

```markdown
Typically usage for [Multi-slot Content Projection][AioGuideComponentUsageMultiSlotContentProjection] includes using an attribute, element, style definition, or some combination of all three to identify where to project your content.
```

2022-04-05 20:22 UTC, mary-poppins commented
You can preview 02f32be at https://pr45501-02f32be.ngbuilds.io/.

2022-04-05 21:56 UTC, josmar-crwdstffng commented
@TMDavisGoogle 
All edit review comments were addressed or applied.
Please verify.
Thank you

2022-04-05 22:03 UTC, mary-poppins commented
You can preview e9d83b3 at https://pr45501-e9d83b3.ngbuilds.io/.

2022-04-08 19:49 UTC, jessicajaniuk commented
Looks like since the most recent docs PR merge, this needs a rebase.

2022-04-11 22:52 UTC, mary-poppins commented
You can preview bf32e0c at https://pr45501-bf32e0c.ngbuilds.io/.

2022-04-12 15:44 UTC, TMDavisGoogle requested changes
Second pass: light edits (punctuation, grammar) for better clarity.

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/component/component-lifecycle.md
> +The lifecycle of a Angular component starts when the Angular instantiates the component class and ends when Angular destroys the instance of the component.
```suggestion
The lifecycle of a Angular component starts when the Angular instantiates the component class, and ends when Angular destroys the instance of the component.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/component/component-overview.md
> +Every Angular application has at least one component, the *root component* that connects a component hierarchy with the document object model \(DOM\) of the page.
```suggestion
Every Angular application has at least one component, the *root component*, that connects a component hierarchy with the document object model \(DOM\) of the page.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/component/component-usage-conditional-content-projection.md
> +Using an `ng-content` element in these cases is not recommended, because when the consumer of a component supplies the content, that content is always initialized, even if the component does not defi
```suggestion
Using an `ng-content` element in these cases is not recommended because when the consumer of a component supplies the content, that content is always initialized, even if the component does not define an `ng-content` element or if that `ng-content` element is inside of an `ngIf` statement.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/component/component-usage-exchange-data.md
> +Before you exchange data between to a child component and a parent component in an Angular [component][AioGuideGlossaryComponent], verify that you have met the following prerequisites.
```suggestion
Before you exchange data between a child component and a parent component in an Angular [component][AioGuideGlossaryComponent], verify that you have met the following prerequisites.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/component/component-usage-lifecycle-hooks.md
> +Use a [lifecycle hook method][AioGuideGlossaryLifecycleHook] to tap into key events in the lifecycle of a component or directive and complete the following actions.
```suggestion
Use a [lifecycle hook method][AioGuideGlossaryLifecycleHook] to tap into key events in the lifecycle of a component or directive, and complete the following actions.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/component/component-usage-lifecycle-hooks.md
> +| Perform complex initializations outside of the constructor   | Components should be cheap and safe to construct. Do not fetch data in a component constructor. Do not worry that a new component trie
```suggestion
| Perform complex initializations outside of the constructor   | Components should be cheap and safe to construct. Do not fetch data in a component constructor. Do not worry that a new component tries to contact a remote server when created under test, or before you decide to display it. <br /> An `ngOnInit()` hook method is a good place for a component to fetch the initial data. For an example, see the [Tour of Heroes tutorial][AioTutorialTohPt4CallItInNgoninit].                                                                                                                                                                  |
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/component/component-usage-multi-slot-content-projection.md
> +Each slot is able to specify a CSS selector that determines the content goes into each slot.
```suggestion
Each slot is able to specify a CSS selector that determines the content that goes into each slot.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/component/component-usage-send-data-to-parent.md
> +    | `new{nameOfChildProperty}Event` | The name of the property. The `new` and `Event` terms were used to indicate the property emits a new event.
```suggestion
    | `new{nameOfChildProperty}Event` | The name of the property. The `new` and `Event` terms were used to indicate that the property emits a new event.                                                        |
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/component/component-usage-send-data-to-parent.md
> +    It uses the value the user types into the `input` element.
```suggestion
    It uses the value that the user types into the `input` element.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/dynamic-component-loader.md
> +The &grave;loadComponent\(\)&grave; method is doing a lot of the heavy lifting here.
```suggestion
The &grave;loadComponent\(\)&grave; method is doing a lot of the work here.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/lightweight-injection-tokens.md
> +This lets full tree shaking of `LibHeaderComponent` component take place.
```suggestion
This lets full tree-shaking of `LibHeaderComponent` component take place.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/lightweight-injection-tokens.md
> +This lets full tree shaking of `LibHeaderComponent` component take place.
```suggestion
This lets full tree-shaking of `LibHeaderComponent` component take place.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/testing-components-basics.md
> +Consider this `LightswitchComponent` which toggles a light on and off \(represented by an on-screen message\) when the user clicks the button.
```suggestion
Consider this `LightswitchComponent`, which toggles a light on and off \(represented by an on-screen message\) when the user clicks the button.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/testing-components-basics.md
> +To write these kinds of test, you will use additional features of the `TestBed` as well as other testing helpers.
```suggestion
To write these kinds of tests, you will use additional features of the `TestBed` as well as other testing helpers.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/testing-components-basics.md
> +Later you will call `TestBed.configureTestingModule()` with imports, providers, and more declarations to suit your testing needs.
```suggestion
Later, you will call `TestBed.configureTestingModule()` with imports, providers, and more declarations to suit your testing needs.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/guide/testing-components-basics.md
> +Later you will encounter the `DebugElement.nativeElement` and it too has the `any` type.
```suggestion
Later, you will encounter the `DebugElement.nativeElement`, and it also has the `any` type.
```

2022-04-12 15:44 UTC, TMDavisGoogle commented on aio/content/tutorial/toh-pt4.md
> +* You registered the `HeroService` as the *provider* of its service at the root level so that it can be injected anywhere in the application.
```suggestion
* You registered the `HeroService` as the *provider* of its service at the root level, so that it can be injected anywhere in the application.
```

2022-04-13 16:14 UTC, josmar-crwdstffng commented on aio/content/guide/component-styles-old.md
> +For example, a CSS theme class could be applied to the document &grave;&lt;body&gt;&grave; element, and
This topic is being removed.

2022-04-13 16:22 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-overview.md
> +Every Angular application has at least one component, the *root component* that connects a component hierarchy with the document object model \(DOM\) of the page.
Updated.

```markdown
Every Angular application has at least one component, the *root component*, that connects a component hierarchy with the document object model \(DOM\) of the page.
```

2022-04-13 16:24 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-usage-conditional-content-projection.md
> +Using an `ng-content` element in these cases is not recommended, because when the consumer of a component supplies the content, that content is always initialized, even if the component does not defi
Updated.

```markdown
Use of an `ng-content` element in these cases is not recommended, because when the consumer of a component supplies the content.
That content supplied by the consumer is always initialized, even if the component does not define an `ng-content` element or if that `ng-content` element is inside of an `ngIf` statement.
```

2022-04-13 16:25 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-usage-exchange-data.md
> +Before you exchange data between to a child component and a parent component in an Angular [component][AioGuideGlossaryComponent], verify that you have met the following prerequisites.
Updated.

```markdown
Before you exchange data between a child component and a parent component in an Angular [component][AioGuideGlossaryComponent], verify that you have met the following prerequisites.
```

2022-04-13 16:26 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-usage-lifecycle-hooks.md
> +Use a [lifecycle hook method][AioGuideGlossaryLifecycleHook] to tap into key events in the lifecycle of a component or directive and complete the following actions.
Updated.

```markdown
Use a [lifecycle hook method][AioGuideGlossaryLifecycleHook] to tap into key events in the lifecycle of a component or directive, and complete the following actions.
```

2022-04-13 16:28 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-usage-lifecycle-hooks.md
> +| Perform complex initializations outside of the constructor   | Components should be cheap and safe to construct. Do not fetch data in a component constructor. Do not worry that a new component trie
Updated.

```markdown
| Perform complex initializations outside of the constructor   | Components should be cheap and safe to construct. Do not fetch data in a component constructor. Do not worry that a new component tries to contact a remote server when created under test, or before you decide to display it. <br /> An `ngOnInit()` hook method is a good place for a component to fetch the initial data. For an example, see the [Tour of Heroes tutorial][AioTutorialTohPt4CallItInNgoninit].                                                                                                                                                                  |
```

2022-04-13 16:30 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-usage-send-data-to-parent.md
> +    | `new{nameOfChildProperty}Event` | The name of the property. The `new` and `Event` terms were used to indicate the property emits a new event.
Updated.

```markdown
| `new{nameOfChildProperty}Event` | The name of the property. The `new` and `Event` terms were used to indicate that the property emits a new event.                                                   |
```

2022-04-13 16:31 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-usage-send-data-to-parent.md
> +    It uses the value the user types into the `input` element.
Updated.

```markdown
It uses the value that the user types into the `input` element.
```

2022-04-13 16:34 UTC, josmar-crwdstffng commented on aio/content/guide/lightweight-injection-tokens.md
> +This lets full tree shaking of `LibHeaderComponent` component take place.
Updated.

```markdown
This allows full tree-shaking of `LibHeaderComponent` component take place.
```

2022-04-13 16:36 UTC, josmar-crwdstffng commented on aio/content/guide/testing-components-basics.md
> +Consider this `LightswitchComponent` which toggles a light on and off \(represented by an on-screen message\) when the user clicks the button.
Updated.

```markdown
Consider this `LightswitchComponent`, which toggles a light on and off \(represented by an on-screen message\) when the user clicks the button.
```

2022-04-13 16:40 UTC, josmar-crwdstffng commented on aio/content/guide/testing-components-basics.md
> +Later you will call `TestBed.configureTestingModule()` with imports, providers, and more declarations to suit your testing needs.
Updated.

```markdown
Later, use `TestBed.configureTestingModule()` with imports, providers, and more declarations to suit your testing needs.
```

2022-04-13 16:41 UTC, josmar-crwdstffng commented on aio/content/guide/testing-components-basics.md
> +Later you will encounter the `DebugElement.nativeElement` and it too has the `any` type.
Updated.

```markdown
Later, you encounter the `DebugElement.nativeElement`, and it also has the `any` type.
```

2022-04-13 16:47 UTC, josmar-crwdstffng commented on aio/content/tutorial/toh-pt4.md
> +* You registered the `HeroService` as the *provider* of its service at the root level so that it can be injected anywhere in the application.
Updated.

```markdown
*   You registered the `HeroService` as the *provider* of its service at the root level, so that it can be injected anywhere in the application
```

2022-04-15 16:51 UTC, dylhunn commented
I am concerned about the size of this PR. Due to the extraordinarily large size, it's effectively unreviewable.

Was this PR automatically generated? It seems to affect a lot of files we don't want to touch, such as `CHANGELOG.md`.

2022-04-15 17:26 UTC, jelbourn reviewed
+1 to @dylhunn - this PR is effectively unreviewable. 

I've tried to read through some of it, and have left some comments based on what I could see, but it's impossible to tell which content was already here and moved versus new content being written for this PR.

2022-04-15 17:26 UTC, jelbourn commented on aio/content/guide/architecture-next-steps.md
> +[AioCli]: cli "CLI Overview and Command Reference | Angular"
I'm concerned these titles will cause extra noise for screen-reader users.  For example, on this link (based on how it's used) a screen-reader would announce:
```
CLI Command Reference CLI Overview and Command Reference Angular
```
Which is more confusing than if it were just the link text of "CLI Command Reference"

2022-04-15 17:26 UTC, jelbourn commented on aio/content/guide/architecture.md
> +*   [Introduction to Components](guide/architecture-components)<!--*   [Templates and views](guide/architecture-components#templates-and-views)-->
What's this comment?

2022-04-15 17:26 UTC, jelbourn commented on aio/content/guide/component-interaction-old.md
> +# Component interaction
Should this file be deleted?

2022-04-15 17:26 UTC, jelbourn commented on aio/content/guide/component-overview-old.md
> +## old content
Should this file be deleted?

(same for other files marked as -"old")

2022-04-15 17:26 UTC, jelbourn commented on aio/content/guide/component/component-overview.md
> +<div class="card-container">
I don't think this card-styled set of links looks particularly good in a guide page like this vs. a higher-level landing page.

2022-04-15 18:30 UTC, josmar-crwdstffng commented on aio/content/guide/component-overview-old.md
> +## old content
Yes, this topic is retained for reference only during the review.

2022-04-15 18:30 UTC, josmar-crwdstffng commented on aio/content/guide/component-interaction-old.md
> +# Component interaction
Yes, this topic is retained for reference only during the review.

2022-04-15 18:38 UTC, josmar-crwdstffng commented on aio/content/guide/architecture-components.md
> +<header><b>Example</b>: Individual components define and control each of the following views from the <a href="tutorial" alt="Tour of Heroes app and tutorial | Angular">Tour of Heroes tutorial</a></h
Html tags can be inserted in markdown without issue.
When you use an html tag, you should continue to use html until the html tag is closed in order to eliminate conflicts between the parsing of markdown and passing through of html style definitions.

2022-04-15 18:48 UTC, dylhunn commented
> it's impossible to tell which content was already here and moved versus new content being written for this PR

I agree with this as well -- I think we should put moves and additions in separate PRs.

2022-05-17 23:38 UTC, mary-poppins commented
You can preview 6a7c174 at https://pr45501-6a7c174.ngbuilds.io/.

2022-05-19 14:18 UTC, mary-poppins commented
You can preview 9d42558 at https://pr45501-9d42558.ngbuilds.io/.

2022-05-19 14:36 UTC, josmar-crwdstffng commented on aio/content/errors/NG0100.md
> +
@jelbourn 
The updates have been moved into another branch.

2022-05-19 14:38 UTC, josmar-crwdstffng commented on aio/content/guide/architecture-components.md
> +<!-- structure but point to component structure for details -->
@jelbourn 
The comment was updated to reflect changes in the content structure.

2022-05-19 14:40 UTC, josmar-crwdstffng commented on aio/content/cli/index.md
> +    &verbar;                    &verbar;                   &verbar;                     &verbar;
@jelbourn 
The updates have been moved into another branch.

2022-05-19 14:42 UTC, josmar-crwdstffng commented on aio/content/guide/architecture-components.md
> +<img alt="Metadata" class="left" src="generated/images/guide/architecture/metadata.png" />
@jelbourn 
I reverted most of the changes.
The changes were suggested to reflect closure activity found in the `angular/angular` repo.

2022-05-19 14:43 UTC, josmar-crwdstffng commented on aio/content/guide/architecture.md
> +*   [Introduction to Components](guide/architecture-components)<!--*   [Templates and views](guide/architecture-components#templates-and-views)-->
@jelbourn 
The content was commented out to retain location of previous information during peer and technical review.
All non-todo comments should be removed prior to publication.

2022-05-19 17:02 UTC, TMDavisGoogle commented on aio/content/errors/NG0100.md
> +Ensure that there are no changes to the bindings in the template after change detection is run. This often means refactoring to use the correct [component lifecycle hook][AioGuideComponentUsageLifecy
```suggestion
Ensure that there are no changes to the bindings in the template after change detection is run. This often means refactoring to use the correct [component lifecycle hook][AioGuideComponentUsageLifecycleHooks] for your use case. If the issue exists within `ngAfterViewInit`, the recommended solution is to use a constructor or `ngOnInit` to set initial values, or use `ngAfterContentInit` for other value bindings.
```

2022-05-19 18:32 UTC, TMDavisGoogle commented on aio/content/guide/component/component-encapsulate-style.md
> +These modified selectors make sure the styles to be applied to the views of the components in an isolated and targeted fashion.
```suggestion
These modified selectors make sure that the styles are to be applied to the views of the components in an isolated and targeted fashion.
```

2022-05-19 21:51 UTC, TMDavisGoogle reviewed
LGTM.

2022-05-19 22:10 UTC, josmar-crwdstffng commented on aio/content/errors/NG0100.md
> +Ensure that there are no changes to the bindings in the template after change detection is run. This often means refactoring to use the correct [component lifecycle hook][AioGuideComponentUsageLifecy
Updated.

```md
Ensure that there are no changes to the bindings in the template after change detection is run. This often means refactoring to use the correct [component lifecycle hook][AioGuideComponentUsageLifecycleHooks] for your use case. If the issue exists within `ngAfterViewInit`, the recommended solution is to use a constructor or `ngOnInit` to set initial values, or use `ngAfterContentInit` for other value bindings.
```

2022-05-19 22:11 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-encapsulate-style.md
> +These modified selectors make sure the styles to be applied to the views of the components in an isolated and targeted fashion.
Updated.

```md
These modified selectors ensure that the styles to be applied to the views of the components are in an isolated and targeted fashion.
```

2022-05-19 22:47 UTC, TMDavisGoogle reviewed
LGTM.

2022-05-19 23:24 UTC, mary-poppins commented
You can preview a4dfd63 at https://pr45501-a4dfd63.ngbuilds.io/.

2022-05-20 00:28 UTC, mary-poppins commented
You can preview 895cc77 at https://pr45501-895cc77.ngbuilds.io/.

2022-05-20 23:03 UTC, jelbourn reviewed
I've started reviewing, but this PR is still massive with no clear way to tell what is new content and what is moved existing content. From a cursory scan there does appear to be a fair amount of new content, so I'm comparing side-by-side with the old content. I will continue when I can, but at this pace it may be well over a week until I get can through it all.

2022-05-23 14:45 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-overview.md
> +It is the class that controls the portion of a browser screen identified as a [view][AioGuideGlossaryView].
Updated.

```md
The root component is the class that controls the portion of a browser screen identified as a [view][AioGuideGlossaryView].
```

2022-05-23 16:00 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-overview.md
> +It is the class that controls the portion of a browser screen identified as a [view][AioGuideGlossaryView].
Reworked and moved.

```md
A component contains the data and logic metadata for your Angular application
A component contains the metadata for an associated HTML [template][AioGuideTemplateOverview].

Angular uses a component and the associated HTML [template][AioGuideTemplateOverview] to render a collection of DOM elements.
The collection of DOM elements define an Angular [view][AioGuideGlossaryView].
An Angular [view][AioGuideGlossaryView] is the portion of a browser screen.
A component and the associated HTML template define and control an Angular [view][AioGuideGlossaryView].
```

2022-05-23 16:06 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-overview.md
> +The `@Component()` decorator identifies the class immediately below it as a component, and provides the template and related component-specific metadata.
Updated.

```md
A component is a TypeScript class that is defined using the the `@Component()` decorator.
```

2022-05-23 16:24 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-overview.md
> +Decorators are functions that modify JavaScript classes. Angular defines a number of decorators that attach specific kinds of metadata to classes, so that the system knows what those classes mean and
Updated.

```md
<div class="alert is-helpful">

The `@Component` decorator is a [decorator][TypescriptlangDocsHandbookDecoratorsHtmlDecorators] that augments your TypeScript class with additional Angular-specific information.
The Angular-specific information defines how the Angular framework renders the component in the document object model \(DOM\).

</div>
```

2022-05-23 16:24 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-overview.md
> +[MediumGoogleDevelopersExploring-es7-decorators-76ecb65fb841#.x5c2ndtx0]: https://medium.com/google-developers/exploring-es7-decorators-76ecb65fb841#.x5c2ndtx0 "Exploring EcmaScript Decorators | medi
Removed.

2022-05-23 16:40 UTC, mary-poppins commented
You can preview 23f5c67 at https://pr45501-23f5c67.ngbuilds.io/.

2022-05-26 14:59 UTC, mary-poppins commented
You can preview acc7dcb at https://pr45501-acc7dcb.ngbuilds.io/.

2022-06-09 15:56 UTC, mary-poppins commented
You can preview 6dfb376 at https://pr45501-6dfb376.ngbuilds.io/.

2022-06-10 00:00 UTC, jelbourn commented on aio/content/navigation.json
> +              "title": "Component projection",
I would prefer to keep the content projection topic all in one page. Looking at the production content on aio today, it seems like it wouldn't be too much work to tweak the content to not be tutorial-ified / step-by-step; the vast majority of the content is overview/guide style, it just has a few paragraphs that devolve into step territory.

2022-07-12 22:01 UTC, josmar-crwdstffng commented on aio/content/guide/component-overview-old.md
> +@reviewed 2022-05-17
@jelbourn 

Removed file.

2022-07-12 22:01 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-overview.md
> +The Angular-specific information defines how the Angular framework renders the component in the document object model \(DOM\).
@jelbourn 

Updated.

```md
The `@Component` statement is a [decorator][TypescriptlangDocsHandbookDecoratorsHtmlDecorators] that augments your TypeScript class with Angular-specific information.
The information defines how the Angular framework renders the component in the document object model \(DOM\).
```

2022-07-12 22:01 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-overview.md
> +When a user interacts with your application, Angular uses APIs to create, update, and remove [components][AioGuideGlossaryComponent].
@jelbourn 

Updated.

```md
The Angular framework uses a [component][AioGuideGlossaryComponent] and the associated HTML [template][AioGuideTemplateOverview] to complete the following actions.

*   Render the HTML template in the DOM structure
*   Update the rendered DOM structure
*   Remove a component and the associated DOM structure

The Angular framework updates your component when a user interacts with your application.
```

2022-07-12 22:01 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-structure.md
> +# Understand the structure an Angular component
@jelbourn 

I reworked the page to include your suggestions and describe all parts of a component.

2022-07-12 22:01 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-structure.md
> +The logic of a [component][AioGuideGlossaryComponent] class uses methods and properties in an API to define and interact with the [view][AioGuideGlossaryView].
@jelbourn 

I replaced the `view` term with the `rendered DOM elements` or `HTML template` as appropriate.

2022-07-12 22:01 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-structure.md
> +| Inline CSS          | In the template HTML                 | **Optional**. <br /> The CSS styles directly applied to the template.                                        |
@jelbourn

I restructured the component and metadata tables to better scope the parts.

Updated.

```md
Each [component][AioGuideGlossaryComponent] class must have the following parts.

| Part                   | Details |
|:---                    |:---     |
| `@component` decorator | Informs the Angular framework that Angular-specific information is included in the TypeScript class. |
| metadata object        | Includes the `selector` and other properties for the component class.                                |
```

```md
Each component in your application has separate metadata and allows you to use a different combination of inline and file references for each component.

The metadata for each component must include the `selector` property.

The following table lists the properties of the metadata object.

| Property                               | Details |
|:---                                    |:---     |
| [`selector`](#selector-property)       | **REQUIRED**. The name of the CSS selector the Angular framework replaces in the HTML [template][AioGuideGlossaryTemplate] with an instance of the component. |
| [`template`](#template-property)       | The inline HTML template of the component. If you specify the `templateUrl` property, you must not specify the `template` property.                                 |
| [`templateUrl`](#templateurl-property) | The relative path to the HTML template file of the component. If you specify the `template` property, you must not specify the `templateUrl` property.              |
| [`styles`](#styles-property)           | The inline CSS styles for the template of the component.                                                                                                      |
| [`styleUrls`](#styleurls-property)     | The relative path to each CSS style file for the template of the component.                                                                                   |
| [`providers`](#providers-property)     | An array of [providers][AioGuideGlossaryProvider] for services that the component requires.                                                                   |
```

2022-07-12 22:01 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-structure.md
> +</div>
@jelbourn 

Updated.

```md
<div class="alert is-helpful">

**TIP**: <br />
The Angular framework provides [lifecycle hook methods][AioGuideComponentLifecycleUseLifecycleHookMethod] to access [different phases of the rendering process][AioGuideComponentLifecycle] for each component.
To learn more about the different phases of the rendering process, see [Understand the lifecycle of a component][AioGuideComponentLifecycle].
To learn more about the lifecycle hook methods, see [Use lifecycle hook method][AioGuideComponentLifecycleUseLifecycleHookMethod].

</div>
```

2022-07-12 22:01 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-structure.md
> +A [component][AioGuideGlossaryComponent] is a specific type of [directive][AioGuideGlossaryDirective].
@jelbourn 

I removed the discussion of the relationship between a directive and component.

2022-07-12 22:01 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-structure.md
> +The component metadata associates the HTML [template][AioGuideGlossaryTemplate] with the `@Component()`.
@jelbourn

I restructured the component and metadata tables to better scope the parts.

Updated.

```md
Each [component][AioGuideGlossaryComponent] class must have the following parts.

| Part                   | Details |
|:---                    |:---     |
| `@component` decorator | Informs the Angular framework that Angular-specific information is included in the TypeScript class. |
| metadata object        | Includes the `selector` and other properties for the component class.                                |
```

```md
Each component in your application has separate metadata and allows you to use a different combination of inline and file references for each component.

The metadata for each component must include the `selector` property.

The following table lists the properties of the metadata object.

| Property                               | Details |
|:---                                    |:---     |
| [`selector`](#selector-property)       | **REQUIRED**. The name of the CSS selector the Angular framework replaces in the HTML [template][AioGuideGlossaryTemplate] with an instance of the component. |
| [`template`](#template-property)       | The inline HTML template of the component. If you specify the `templateUrl` property, you must not specify the `template` property.                                 |
| [`templateUrl`](#templateurl-property) | The relative path to the HTML template file of the component. If you specify the `template` property, you must not specify the `templateUrl` property.              |
| [`styles`](#styles-property)           | The inline CSS styles for the template of the component.                                                                                                      |
| [`styleUrls`](#styleurls-property)     | The relative path to each CSS style file for the template of the component.                                                                                   |
| [`providers`](#providers-property)     | An array of [providers][AioGuideGlossaryProvider] for services that the component requires.                                                                   |
```

2022-07-12 22:01 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-structure.md
> +| [`styleUrls`](#style-metadata)      | The module-relative address of each CSS style file for the template of the component.        |
@jelbourn 

Replaced instances of the `module-relative address of` phrase with the `relative path to` phrase.

2022-07-12 22:01 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-structure.md
> +<img alt="Metadata" class="left" src="generated/images/guide/architecture/metadata.png" />
@jelbourn 

Yes.
Removed.

2022-07-12 22:01 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-structure.md
> +export class &lcub;NameOfComponent&rcub;Component implements OnInit {
Task-based topics should be be constructed to address the functionality with descriptive names.
The use of a specific scenario fits a procedure or tutorial topic, but is not useful in a task-based topic.

2022-07-12 22:02 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-lifecycle.md
> +# Understand the lifecycle of a component
@jelbourn 

Removed redundant item form the left-nav TOC.

2022-07-12 22:02 UTC, josmar-crwdstffng commented on aio/content/navigation.json
> +              "title": "Component data",
@jelbourn 

The left-nav is adaptable.
I placed the content where it appeared to fit in context.

Updated.

2022-07-12 22:02 UTC, josmar-crwdstffng commented on aio/content/navigation.json
> +          "title": "Component",
One of the main tenets for the document restructure project is separating out the various content types into topics that focus on 1 content type.
This increases readability, reduces cognitive load, reduces maintenance, and increases consistency.

2022-07-12 22:02 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-web.md
> +# Web component
@jelbourn 

Moved the content under from `guide/component/component-web` to `guide/element/custom-element`.

2022-07-12 22:02 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-web.md
> +# Web component
@jelbourn 

Singular term is more clear.

The title was changed to `Understand custom element`.

2022-07-12 22:02 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-web.md
> +A *custom element* is also refernced as a [Web Component][MdnDocsWebWebComponents].
@jelbourn 

Updated.

```md
An *Angular element* is an Angular component packaged as a [custom element][MdnDocsWebWebComponentsUsingCustomElements].
A *custom element* is also called a [Web Component][MdnDocsWebWebComponents].
A web component is a custom element that also defines a [Shadow Root][MdnDocsWebApiShadowroot] interface.
[Web Components][MdnDocsWebWebComponents] are a web standard that allows you to define a new HTML element in a framework-agnostic way.
```

2022-07-12 22:02 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-example.md
> +# Example Angular component applications
@jelbourn 

Tearing apart the tutorials to create anonymized task-based topics.

2022-07-12 22:02 UTC, josmar-crwdstffng commented on aio/content/navigation.json
> +              "title": "Component projection",
@jelbourn

Tearing apart the tutorials to create anonymized task-based topics while retaining the overview topic.

2022-07-12 22:02 UTC, josmar-crwdstffng commented on aio/content/guide/component/component-lifecycle.md
> +# Understand the lifecycle of a component
@jelbourn

Tearing apart the tutorials to create anonymized task-based topics.

2022-07-12 23:01 UTC, mary-poppins commented
You can preview d4996d5 at https://pr45501-d4996d5.ngbuilds.io/.

2022-08-15 22:35 UTC, closed without merging

2022-08-15 22:36 UTC, josmar-crwdstffng commented
Closed PR to implement with feedback and comments.