Fix: docs code style
angular/angular pull request #45527
Opened 2022-04-05 03:20 UTC by Piyush132000

Updated Product list & shipping component code style

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines:https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

Update  the code style of Product-list & Shipping component.
Removed Unnecessary code.

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Same behavior as previous

Issue Number: N/A

## What is the new behavior?
NA
## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-04-07 11:18 UTC, AlirezaEbrahimkhani commented
@Piyush132000 
Tnx
but can you please update the commit message to more closely follow angular [commit message guidelines](https://github.com/angular/angular/blob/655507012b7b59c83e27429349ce3ac10608a82d/CONTRIBUTING.md#commit)? :pray:
Somthing like this :

> docs: fix code style
> 
> Updated Product list & shipping component code style

 
To update, your last commit message you can use this command `git commit --amend` and then force push your branch
remember you do not need to add another commit message just edit your last commit message. :+1:

2022-04-07 11:34 UTC, Piyush132000 commented
> @Piyush132000 Tnx but can you please update the commit message to more closely follow angular [commit message guidelines](https://github.com/angular/angular/blob/655507012b7b59c83e27429349ce3ac10608a82d/CONTRIBUTING.md#commit)? 🙏 Somthing like this :
> 
> > docs: fix code style
> > Updated Product list & shipping component code style
> 
> To update, your last commit message you can use this command `git commit --amend` and then force push your branch remember you do not need to add another commit message just edit your last commit message. 👍

@AlirezaEbrahimkhani thanks sir and I updated the commit message.

2022-04-11 17:25 UTC, jessicajaniuk commented
@Piyush132000 this has some lint and test failures that should be quick to resolve. If you can get them addressed, this is otherwise green and should be quick to land.

2022-04-13 02:55 UTC, Piyush132000 commented
> @Piyush132000 this has some lint and test failures that should be quick to resolve. If you can get them addressed, this is otherwise green and should be quick to land.

Sorry for inconvenience, can you please help me how can I remove these failure?

2022-04-13 16:02 UTC, Piyush132000 commented
> @Piyush132000 The test_aio failure looks like a simple linting issue where you need a space after a `:` in one of your files. The test_docs_examples test looks like an issue with one of the types used in the template. You can always click on "Details" in the failed tests listed below in the PR here to see the details of the failed tests.

Thanks @jessicajaniuk

2022-04-15 03:10 UTC, Piyush132000 commented
Hii @jessicajaniuk, I have fixed lint-related issues. 

Please verify.

2022-04-15 16:09 UTC, jessicajaniuk commented
@Piyush132000 Looks like the lint issues are fixed, but you still have some test_docs_examples issues. You can see them [here](https://circleci.com/gh/angular/angular/1149963?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

2022-04-20 03:56 UTC, Piyush132000 commented
> @Piyush132000 Looks like the lint issues are fixed, but you still have some test_docs_examples issues. You can see them [here](https://circleci.com/gh/angular/angular/1149963?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

Sorry for the inconvenience, @jessicajaniuk I tried but was not able to fix the test failed.

2022-04-28 02:35 UTC, Piyush132000 commented
> > @Piyush132000 Looks like the lint issues are fixed, but you still have some test_docs_examples issues. You can see them [here](https://circleci.com/gh/angular/angular/1149963?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).
> 
> Sorry for the inconvenience, @jessicajaniuk I tried but was not able to fix the failed tests.

Hii @jessicajaniuk  can you please help me more so I can fix these failures.

2022-04-28 11:04 UTC, jessicajaniuk submitted a review, later dismissed

2022-04-28 11:04 UTC, jessicajaniuk commented on aio/content/examples/getting-started/src/app/shipping/shipping.component.ts
> +  shippingCosts: {  type: string , price: number}[] = [];
This is what's breaking the tests. shippingCosts should be an observable since the cartService `getShippingPrices` method returns an observable. The error in the tests is this:

```
error TS2740: Type 'Observable<{ type: string; price: number; }[]>' is missing the following properties from type '{ type: string; price: number; }[]': length, pop, push, concat, and 27 more
```

This is essentially saying there's a type mismatch between what you've specified here, which is just a simple array of objects, and the actual return value, which is an Observable. This needs to be resolved to fix the tests.

2022-04-29 19:58 UTC, gkalpak requested changes
Thx for making these improvements, @Piyush132000 :+1:
I left a couple of suggestions.

2022-04-29 19:58 UTC, gkalpak commented on aio/content/examples/getting-started/src/app/shipping/shipping.component.ts
> +  shippingCosts: Observable<{  type: string , price: number}[]>;
Nit:

```suggestion
  shippingCosts: Observable<{ type: string, price: number }[]>;
```

2022-04-29 19:58 UTC, gkalpak commented on aio/content/examples/getting-started/src/app/shipping/shipping.component.ts
>  // #docregion props
This should be part of the `props` docregion:

```suggestion
// #docregion props

  ngOnInit(): void {
    this.shippingCosts =  this.cartService.getShippingPrices();
  }

```

Could you also please update the part of the guide where this snippet is used to reflect the change (i.e. mention that the property is initialized in an `ngOnInit()` method)? 🙏 

[1]: https://github.com/angular/angular/blob/42289f25c69ec7a36d2e3ef424d32f77bc7cd19a/aio/content/start/start-data.md?plain=1#L269-L271

2022-05-05 03:46 UTC, Piyush132000 commented
Hii @jessicajaniuk @gkalpak  please check my PR again. 

Thanks

2022-05-05 10:05 UTC, mary-poppins commented
You can preview 052aa44 at https://pr45527-052aa44.ngbuilds.io/.
You can preview 228febc at https://pr45527-228febc.ngbuilds.io/.
You can preview 2068330 at https://pr45527-2068330.ngbuilds.io/.
You can preview c7fb01d at https://pr45527-c7fb01d.ngbuilds.io/.
You can preview 96281dc at https://pr45527-96281dc.ngbuilds.io/.
You can preview cc445b9 at https://pr45527-cc445b9.ngbuilds.io/.

2022-05-05 10:09 UTC, gkalpak requested changes
Just a couple of formatting suggestions. Otherwise lgtm :+1:

2022-05-05 10:09 UTC, gkalpak commented on aio/content/start/start-data.md
> +1. Define a `shippingCosts` property that sets the `shippingCosts` property using the `getShippingPrices()` method from the `CartService`. Initialize the `shippingCosts` property inside `ngOnInit()`
Some formatting suggestions (to align with overall style):

```suggestion
1.  Define a `shippingCosts` property that sets the `shippingCosts` property using the `getShippingPrices()` method from the `CartService`.
    Initialize the `shippingCosts` property inside `ngOnInit()` method.
```

2022-05-05 10:09 UTC, gkalpak commented on aio/content/examples/getting-started/src/app/shipping/shipping.component.ts
> +   ngOnInit(): void {
In order for all docregions to be formatted correctly, we need to have an empty line before `ngOnInit()` (inside the `props` docregion). So, this needs to be:

```diff
 // #enddocregion inject-cart-service
+// #docregion props
 
-// #docregion props
   ngOnInit(): void {
```

2022-05-05 10:09 UTC, gkalpak commented on aio/content/examples/getting-started/src/app/shipping/shipping.component.ts
> +   }
Incorrect indentation:

```suggestion
  }
```

2022-05-05 10:09 UTC, gkalpak commented on aio/content/examples/getting-started/src/app/shipping/shipping.component.ts
> +import { Component , OnInit  } from '@angular/core';
Nit: Inconsistent spacing:

```suggestion
import { Component, OnInit  } from '@angular/core';
```

2022-05-05 12:10 UTC, mary-poppins commented
You can preview 0da8181 at https://pr45527-0da8181.ngbuilds.io/.

2022-05-09 04:16 UTC, Piyush132000 commented
Hii @gkalpak @jessicajaniuk, please review my PR.

2022-05-09 13:07 UTC, gkalpak approved these changes
Thx, @Piyush132000 :+1:

2022-05-09 13:13 UTC, gkalpak requested changes

2022-05-09 13:13 UTC, gkalpak commented on aio/content/examples/getting-started/src/app/shipping/shipping.component.ts
> +import { Observable } from 'rxjs';
Nit: Put this above the `CartService` import (since we try to keep relative imports below non-relative ones).

2022-05-09 13:13 UTC, gkalpak commented on aio/content/examples/getting-started/src/app/shipping/shipping.component.ts
> +  shippingCosts: Observable<{ type: string, price: number }[]>;
Actually, this change causes TypeScript to complain (and CI to fail) with:

```
Property 'shippingCosts' has no initializer and is not definitely assigned in the constructor
```

Maybe use:

```suggestion
  shippingCosts!: Observable<{ type: string, price: number }[]>;
```

2022-05-10 03:22 UTC, Piyush132000 commented on aio/content/examples/getting-started/src/app/shipping/shipping.component.ts
> +  shippingCosts: Observable<{ type: string, price: number }[]>;
Hii @gkalpak , Thanks for the suggestions, I have done your suggested changes. If any other changes are required let me know.

Thanks

2022-05-10 17:26 UTC, jessicajaniuk commented
@Piyush132000 I rebased this on main for you, but it looks like you still have some failing tests.

2022-05-16 00:55 UTC, Piyush132000 commented
Hii @jessicajaniuk , @gkalpak  is there any changes required for merge to main?

2022-05-16 12:30 UTC, gkalpak commented
@Piyush132000, there are some CI failures that need to be fixed. In particular, the `getting-started` example is failing.

You can see the failed test output [here][1]. In case it helps, here is the error message:

```
Warning: 1 rules skipped due to selector errors:
  router-outlet + * -> Cannot read properties of undefined (reading 'type')


Error: src/app/shipping/shipping.component.html:3:52 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(obj: Observable<any[] | Iterable<any> | undefined> | Subscribable<any[] | Iterable<any> | undefined> | Promise<any[] | Iterable<any> | undefined>): any[] | ... 2 more ... | undefined', gave the following error.
    Argument of type '{ type: string; price: number; }[]' is not assignable to parameter of type 'Observable<any[] | Iterable<any> | undefined> | Subscribable<any[] | Iterable<any> | undefined> | Promise<any[] | Iterable<any> | undefined>'.
      Type '{ type: string; price: number; }[]' is missing the following properties from type 'Observable<any[] | Iterable<any> | undefined>': source, operator, lift, subscribe, and 2 more.
  Overload 2 of 3, '(obj: null | undefined): null', gave the following error.
    Argument of type '{ type: string; price: number; }[]' is not assignable to parameter of type 'null | undefined'.
  Overload 3 of 3, '(obj: Observable<any[] | Iterable<any> | undefined> | Subscribable<any[] | Iterable<any> | undefined> | Promise<any[] | Iterable<any> | undefined> | null | undefined): any[] | ... 2 more ... | undefined', gave the following error.
    Argument of type '{ type: string; price: number; }[]' is not assignable to parameter of type 'Observable<any[] | Iterable<any> | undefined> | Subscribable<any[] | Iterable<any> | undefined> | Promise<any[] | Iterable<any> | undefined> | null | undefined'.
      Type '{ type: string; price: number; }[]' is not assignable to type 'Observable<any[] | Iterable<any> | undefined>'.

3 <div class="shipping-item" *ngFor="let shipping of shippingCosts | async">
                                                     ~~~~~~~~~~~~~

  src/app/shipping/shipping.component.ts:10:16
    10   templateUrl: './shipping.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ShippingComponent.


Error: src/app/shipping/shipping.component.ts:24:5 - error TS2740: Type 'Observable<{ type: string; price: number; }[]>' is missing the following properties from type '{ type: string; price: number; }[]': length, pop, push, concat, and 27 more.

24     this.shippingCosts =  this.cartService.getShippingPrices();
       ~~~~~~~~~~~~~~~~~~
```

[1]: https://circleci.com/gh/angular/angular/1165448

2022-05-22 16:18 UTC, mary-poppins commented
You can preview 4cb7ec8 at https://pr45527-4cb7ec8.ngbuilds.io/.

2022-05-22 16:30 UTC, Piyush132000 commented
Hi @jessicajaniuk, @gkalpak Please review my PR.

Thanks

2022-05-23 11:18 UTC, gkalpak approved these changes
LGTM 🚀
Thx, @Piyush132000 :+1:

2022-05-23 11:18 UTC, gkalpak commented on aio/content/start/start-data.md
> +   Initialize the `shippingCosts` property inside `ngOnInit()` method.
Nit: The indentation does not match the other items here, but not worth blocking this PR over that.

2022-05-23 16:35 UTC, jessicajaniuk approved these changes
LGTM :cookie:

Thanks for your work and persistence in getting this green, @Piyush132000! 🎉

2022-05-23 20:47 UTC, alxhub requested changes
Hello @Piyush132000 

Sorry to kick this back, but when I was going to merge this I noticed this PR is composed of 4 commits, all of which have the same generic title and no description.

Please squash these commits into one, and add a short description describing why we're making these changes.

2022-05-24 05:18 UTC, mary-poppins commented
You can preview 77979d9 at https://pr45527-77979d9.ngbuilds.io/.

2022-05-27 02:20 UTC, mary-poppins commented
You can preview 425a619 at https://pr45527-425a619.ngbuilds.io/.

2022-06-04 05:12 UTC, Piyush132000 commented
Hii @jessicajaniuk, @gkalpak and @alxhub are any changes required to merge this PR to main?. I already squashed the commits.

2022-06-14 19:55 UTC, alxhub approved these changes

2022-06-14 19:56 UTC, jessicajaniuk commented
This PR was merged into the repository by commit 9ce733aacb00777bc1cf01bb9ef1ce9534437512.

2022-06-14 19:56 UTC, closed without merging

2022-06-15 03:52 UTC, Piyush132000 commented
Thanks, @jessicajaniuk @gkalpak @alxhub