build(docs-infra): introduce new process for generating data for the events page
angular/angular pull request #45588
Opened 2022-04-11 16:19 UTC by gkalpak

TODO: Add desc.

**TODECIDE**

- [ ] How we want to present dates (esp. the `Starts on` prefix).
- [ ] What to do about events with invalid dates. (Currently, the script prints them and then removes them from the list.)
- [ ] Whether we want to update past events with links (or maybe just the 2022 ones).
- [ ] Whether we want to automatically keep X last years worth of events.
  (We could keep them all in the DB, but not put them in `events.json` for displaying in AIO.)
- [ ] How much back we want to go. (NOTE: Sheets before 2019 use different formats).
- [ ] Whether to only retrieve events from the DB when building `next.angular.io` on upstream CI and get `next.angular.io/generated.events.json` for other builds.
  (This would allow us to lock down reading on the database fwiw.)

**TODO**

- [ ] Update `DB_URL` value in `constants.js` and `index.mjs`.
- [ ] Set up Apps Script extension on the actual spreadsheet and create time-driven trigger.
- [ ] Ensure the installable trigger creator has access to the `angular-io` Firebase project.

2022-04-11 19:23 UTC, mary-poppins commented
You can preview 832adb0 at https://pr45588-832adb0.ngbuilds.io/.

2022-04-11 20:04 UTC, mary-poppins commented
You can preview a551b54 at https://pr45588-a551b54.ngbuilds.io/.

2022-04-11 21:09 UTC, mgechev approved these changes

2022-04-11 21:10 UTC, mgechev commented on aio/src/app/custom-elements/events/events.component.html
> +        <td>{{ event.location ?? '-' }}</td>
Maybe we can remove this column? We're not providing a location for now.

2022-04-11 21:11 UTC, mgechev commented on aio/src/app/custom-elements/events/events.component.ts
> +      const datePrefix = event.date.end ? '' : 'Starts on ';
Can we remove the prefix "Starts on"? Maybe we can update the column title to be "Starts on date" to avoid duplication.

2022-04-11 21:11 UTC, mgechev requested changes
Left two comments. Looks really well!

2022-04-11 21:12 UTC, jessicajaniuk submitted a review, later dismissed
reviewed-for: size-tracking

2022-04-14 16:18 UTC, mary-poppins commented
You can preview ed461dc at https://pr45588-ed461dc.ngbuilds.io/.

2022-04-18 20:18 UTC, mgechev submitted a review, later dismissed

2022-04-19 09:43 UTC, mary-poppins commented
You can preview fcce55c at https://pr45588-fcce55c.ngbuilds.io/.

2022-04-19 10:04 UTC, mary-poppins commented
You can preview 2bb3c74 at https://pr45588-2bb3c74.ngbuilds.io/.

2022-04-30 14:33 UTC, mary-poppins commented
You can preview 9845308 at https://pr45588-9845308.ngbuilds.io/.

2022-04-30 14:59 UTC, mary-poppins commented
You can preview 47462ab at https://pr45588-47462ab.ngbuilds.io/.

2022-05-23 16:52 UTC, mary-poppins commented
You can preview 490d3ba at https://pr45588-490d3ba.ngbuilds.io/.

2022-05-23 17:13 UTC, mary-poppins commented
You can preview f8f12ab at https://pr45588-f8f12ab.ngbuilds.io/.

2022-05-24 18:54 UTC, mary-poppins commented
You can preview 3363959 at https://pr45588-3363959.ngbuilds.io/.

2022-05-24 19:15 UTC, mary-poppins commented
You can preview 28a2e0d at https://pr45588-28a2e0d.ngbuilds.io/.

2022-05-25 19:17 UTC, AndrewKushnir approved these changes
Reviewed-for: size-tracking

2022-06-03 13:18 UTC, gkalpak commented
After discussing this with the dev-infra team, we decided to change the implementation as follows in order to keep CI more deterministic and avoid introducing a CI dependency on an external system:

- The Firebase DB will continue to be updated from the spreadsheet as happens currently.
- The `events.json` file will be checked into the repo (and not be generated on every build).
- A GitHub Action will be implemented that will check the Firebase DB daily and (if necessary) send a PR to update `events.json`.

2022-06-27 17:28 UTC, mary-poppins commented
You can preview 82b95f4 at https://pr45588-82b95f4.ngbuilds.io/.

2022-06-27 18:13 UTC, mary-poppins commented
You can preview bbb3d2b at https://pr45588-bbb3d2b.ngbuilds.io/.

2022-06-28 12:17 UTC, mary-poppins commented
You can preview 6b6e3c6 at https://pr45588-6b6e3c6.ngbuilds.io/.

2022-07-24 13:44 UTC, mary-poppins commented
You can preview 09fd410 at https://pr45588-09fd410.ngbuilds.io/.

2022-07-24 15:12 UTC, mary-poppins commented
You can preview c3e545f at https://pr45588-c3e545f.ngbuilds.io/.

2022-07-24 17:39 UTC, mary-poppins commented
You can preview ab490fc at https://pr45588-ab490fc.ngbuilds.io/.

2022-08-11 21:37 UTC, mgechev approved these changes

2022-08-22 11:13 UTC, mary-poppins commented
You can preview 8969655 at https://pr45588-8969655.ngbuilds.io/.

2022-08-22 11:52 UTC, mary-poppins commented
You can preview c4cb9f7 at https://pr45588-c4cb9f7.ngbuilds.io/.

2022-08-26 20:27 UTC, mary-poppins commented
You can preview 8573647 at https://pr45588-8573647.ngbuilds.io/.

2022-08-26 21:00 UTC, mary-poppins commented
You can preview 9ec7d45 at https://pr45588-9ec7d45.ngbuilds.io/.

2022-09-07 17:51 UTC, AndrewKushnir commented
Merge-assistance: needs a "green light" from @mgechev before landing this PR.

2022-09-12 18:27 UTC, AndrewKushnir commented
Got a "green light" from @mgechev offline, so we can proceed with merging this PR. // cc @dylhunn

2022-09-12 19:25 UTC, dylhunn commented
This PR was merged into the repository by commit c9241fdeb0b889f883cb375d0cb822603d233290.

2022-09-12 19:25 UTC, closed without merging

2022-09-13 18:21 UTC, dylhunn commented
@gkalpak Was this PR related to `update-events.yml`? I have started getting emails that the Update AIO events script has failed to run, with [links like this one](https://github.com/angular/angular/actions/runs/3046168453).

2022-09-14 08:39 UTC, gkalpak commented
Yes. As discussed "offline", notifications for scheduled workflows go to the last person that modified the schedule: [GitHub docs][1]

Once the errors are fixed, hopefully there won't be any notifications :grin:

[1]: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule:~:text=Notifications%20for%20scheduled%20workflows