Introducing EnvInjector!
angular/angular pull request #45626
Opened 2022-04-14 01:07 UTC by alxhub

This PR includes a couple commits which introduce the new `EnvInjector` concept. `EnvInjector` is a generalized version of `NgModuleRef` which represents the "module injector" (now renamed to "environment injector"). It's one of the primitives needed to support upcoming standalone components APIs.

2022-04-14 01:42 UTC, pkozlowski-opensource commented on packages/core/src/render3/interfaces/definition.ts
> +import {EnvInjector} from '../../di/r3_injector';
nit: import without usage?

2022-04-15 04:56 UTC, AndrewKushnir approved these changes
Looks great 👍 Just left a few minor comments (none of them are blockers, we can update things in followup PRs).

2022-04-15 04:56 UTC, AndrewKushnir commented on goldens/public-api/core/index.md
> +    abstract onDestroy(callback: () => void): void;
I think we should provide an ability to unsubscribe, similar to the code here:
https://github.com/angular/angular/pull/45624/files#diff-c3bc2f4d2923398d46897c1233ab19cec2611e44ea60592e7e0d5ed03747a897R937

Not a blocker, we can do that in a followup PR.

2022-04-15 04:56 UTC, AndrewKushnir commented on goldens/public-api/core/index.md
> +    abstract get(token: any, notFoundValue?: any): any;
Can we drop this deprecated signature from the `EnvironmentInjector` class?

2022-04-15 04:56 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/annotations/directive/src/handler.ts
> +      if (this.isCore) {
May be add a quick comment on why there is a special handling for core?

2022-04-15 04:56 UTC, AndrewKushnir commented on packages/core/src/di/r3_injector.ts
> + */
```suggestion
 * created by the framework.
 *
 * @publicApi
 */
```

2022-04-15 04:56 UTC, AndrewKushnir commented on packages/core/src/di/r3_injector.ts
> +          validateProvider(provider, providers || EMPTY_ARRAY, ngModule);
Should we guard it with the `ngDevMode` flag?
```suggestion
          ngDevMode && validateProvider(provider, providers || EMPTY_ARRAY, ngModule);
```

2022-04-15 04:56 UTC, AndrewKushnir commented on packages/core/src/di/r3_injector.ts
> +      validateProvider(provider, defProviders as any[], injectorType);
```suggestion
      ngDevMode && validateProvider(provider, defProviders as any[], injectorType);
```

2022-04-15 04:56 UTC, AndrewKushnir commented on packages/core/src/di/r3_injector.ts
> +  const providers: SingleProvider[] = [];
```suggestion
  const providers: Provider[] = [];
```
(so that it's aligned with the return type)

2022-04-15 04:56 UTC, AndrewKushnir commented on packages/core/src/di/r3_injector.ts
> +    providersOut: SingleProvider[], parents: InjectorType<unknown>[],
```suggestion
    providersOut: Provider[], parents: InjectorType<unknown>[],
```

2022-04-15 17:05 UTC, alxhub commented on packages/core/src/di/r3_injector.ts
> +  const providers: SingleProvider[] = [];
`SingleProvider` doesn't allow recursion (nested provider arrays). It's a good distinction to have here.

2022-04-15 17:05 UTC, alxhub commented on packages/core/src/di/r3_injector.ts
> +    providersOut: SingleProvider[], parents: InjectorType<unknown>[],
Same as above.

2022-04-15 17:06 UTC, alxhub commented on goldens/public-api/core/index.md
> +    abstract get(token: any, notFoundValue?: any): any;
I don't think so, because it's needed to implement the `Injector` interface.

2022-04-15 17:06 UTC, alxhub commented on goldens/public-api/core/index.md
> +    abstract get(token: any, notFoundValue?: any): any;
I don't think so, because it's needed to implement the `Injector` interface.

2022-04-15 18:08 UTC, atscott requested changes
reviewed-for: public-api

2022-04-15 18:08 UTC, atscott commented on goldens/public-api/core/index.md
> +    providedIn?: Type<any> | 'root' | 'platform' | 'any' | 'env' | null;
bike-shedding: I still think I would prefer `'environment'` here.

2022-04-15 18:08 UTC, atscott approved these changes
reviewed-for: size-tracking

2022-04-15 20:57 UTC, dylhunn approved these changes
reviewed-for: public-api, size-tracking

2022-04-15 21:44 UTC, jessicajaniuk reviewed
LGTM :cookie:

Just a few non-blocking comments.

reviewed-for: public-api, size-tracking

2022-04-15 21:44 UTC, jessicajaniuk commented on goldens/public-api/core/index.md
> +    providedIn?: Type<any> | 'root' | 'platform' | 'any' | 'env' | null;
➕  1 to this

2022-04-15 21:44 UTC, jessicajaniuk commented on packages/core/src/di/interface/defs.ts
> +  providedIn: InjectorType<any>|'root'|'platform'|'any'|'env'|null;
Similar comment to earlier ones about this being `environment` instead of the abbreviation.

2022-04-15 21:44 UTC, jessicajaniuk commented on packages/core/src/di/interface/defs.ts
> +  providedIn?: Type<any>|'root'|'platform'|'any'|'env'|null, factory: () => T,
Here too.

2022-04-15 21:44 UTC, jessicajaniuk commented on packages/core/src/di/scope.ts
> +export type InjectorScope = 'root'|'platform'|'env';
Here as well.

2022-04-15 21:44 UTC, jessicajaniuk commented on packages/core/src/di/r3_injector.ts
> +    if (scopes.has('env')) {
Here's another instance of `env`. Is there any way to make these not magic strings?

2022-04-15 21:44 UTC, jessicajaniuk commented on packages/core/src/di/r3_injector.ts
> +  // Determine the InjectorType. In the case where `defOrWrappedDef` is an `InjectorType`,
Just a loose comment to say I appreciate how well commented this is. Thank you for that!

2022-04-15 21:44 UTC, jessicajaniuk commented on packages/core/src/render3/ng_module_ref.ts
> +                           stringify(ngModuleType), new Set(['env'])) as R3Injector;
The other locations would be env-ious if you didn't also change this one.

2022-04-15 21:44 UTC, jessicajaniuk commented on packages/core/src/render3/ng_module_ref.ts
> +        parent || getNullInjector(), source, new Set(['env']));
Apologies for the `env` spam

2022-04-15 21:45 UTC, jessicajaniuk approved these changes
reviewed-for: public-api, size-tracking

2022-04-15 22:29 UTC, alxhub commented on packages/core/src/render3/ng_module_ref.ts
> +        parent || getNullInjector(), source, new Set(['env']));
You're always `env`-ited to review as meticulously as you'd like.

2022-04-15 22:29 UTC, alxhub commented on packages/core/src/di/r3_injector.ts
> +    if (scopes.has('env')) {
They're sort of by definition magic strings, since they're typically generated by the compiler.

2022-04-15 22:30 UTC, alxhub commented on packages/core/src/di/r3_injector.ts
> +      validateProvider(provider, defProviders as any[], injectorType);
I think this would be a behavior change - r3_injector previously validated providers even in prod mode.

2022-04-15 22:45 UTC, alxhub commented on goldens/public-api/core/index.md
> +    abstract onDestroy(callback: () => void): void;
Actually I marked this method `@internal` - we shouldn't make it public API (yet).

2022-04-15 23:19 UTC, pkozlowski-opensource commented on packages/core/src/core.ts
> +export {createNgModuleRef, createEnvironmentInjector} from './render3/ng_module_ref';
nit: import without usage?

2022-04-15 23:19 UTC, pkozlowski-opensource commented on packages/core/src/di/index.ts
> +export {EnvironmentInjector, INJECTOR_INITIALIZER} from '../di/r3_injector';
nit: import without usage?

2022-04-15 23:21 UTC, pkozlowski-opensource commented on packages/core/src/render3/index.ts
> +export {NgModuleFactory, NgModuleRef, createEnvironmentInjector} from './ng_module_ref';
nit: import without usage?

2022-04-15 23:43 UTC, atscott approved these changes
reviewed-for: public-api

2022-04-16 00:36 UTC, alxhub commented
Caretaker: this has all required approvals

2022-04-16 01:37 UTC, AndrewKushnir approved these changes

2022-04-16 14:10 UTC, alxhub commented on packages/core/src/render3/index.ts
> +export {NgModuleFactory, NgModuleRef, createEnvironmentInjector} from './ng_module_ref';
This is an `export` :)

2022-04-16 16:20 UTC, pkozlowski-opensource commented on packages/core/src/render3/index.ts
> +export {NgModuleFactory, NgModuleRef, createEnvironmentInjector} from './ng_module_ref';
OMG, tired brain :-)

2022-04-18 16:28 UTC, dylhunn commented
This PR was merged into the repository by commit 3578e943841f0ca0f8496ed06c901a72a8356f9f.

2022-04-18 16:28 UTC, closed without merging