feat(common): add getState method to LocationStrategy interface
angular/angular pull request #45648
Opened 2022-04-15 08:12 UTC by mmaterowski

Add getState to LocationStrategy interface as it suppose to be the place to control all window.location interactions

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #34603

## What is the new behavior?

LocationStrategy implements getState() method which will eventually call  _window.history_ to access current history state.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Only classes that implement Abstract `LocationStrategy` are `PathLocationStrategy` (test already present) and `HashLocationStrategy`. Currently there are no tests for `HashLocationStrategy`, if you find them necessary for this PR to merge let me know.

2022-04-15 08:54 UTC, mmaterowski commented
I'm having trouble understating how my change is failing following test 

> styling should set class based on priority in **styling_spec.ts**

Seems to work locally  when I execute
`KARMA_WEB_TEST_MODE=SL_REQUIRED yarn karma start ./karma-js.conf.js --single-run
`
Result:
![image](https://user-images.githubusercontent.com/23449082/163549443-d138d598-58b5-4894-9e1c-39b4a09e8806.png)

2022-04-15 16:14 UTC, atscott requested changes
@mmaterowski Thanks for the PR. This does not fully address #34603 because `Location` still uses `PlatformLocation` directly rather than going through the new API you're providing here. 

In addition, you'll have to note in the commit message that this is a breaking change (add `BREAKING CHANGE: <description>` to your footer) because it adds a new required class member that any implementors of the `LocationStrategy` will need to satisfy.

2022-04-15 17:17 UTC, mmaterowski commented on packages/common/src/location/location.ts
> +  constructor(platformStrategy: LocationStrategy) {
Is `platformStrategy` still valid parameter name? Is there any reason no to rename it to `locationStrategy`?

2022-04-15 17:35 UTC, atscott commented on packages/common/src/location/location.ts
> +  constructor(platformStrategy: LocationStrategy) {
Yea, I think renaming it is a good idea.

2022-04-15 17:37 UTC, atscott commented
> I'm having trouble understating how my change is failing following test

Yea, there is known flakiness with a few tests at the moment. Sorry about the friction.

2022-04-15 17:40 UTC, mmaterowski commented
@atscott thanks for reviewing my PR.
Since `PlatformLocation` is no longer used in `Location` I removed it from Location's constructor. 
Breaking changes footer added.

2022-04-15 17:42 UTC, atscott approved these changes
LGTM 👍

2022-04-15 17:45 UTC, jessicajaniuk approved these changes
reviewed-for: public-api

2022-04-15 17:50 UTC, atscott approved these changes
reviewed-for: public-api

2022-04-15 18:12 UTC, atscott commented
Note for team members: Since this is a breaking change, I've triggered [global presubmits](http://tap/442050757) to identify what needs to be updated. 

Also adding the blocked label until they necessary internal cleanup has been completed.

2022-04-15 19:36 UTC, dylhunn approved these changes
reviewed-for: public-api

2022-04-15 19:38 UTC, dylhunn commented
@atscott by internal cleanup, do you mean TGP breakage? The linked presubmit is not showing any real failures.

2022-04-15 20:15 UTC, atscott commented
@dylhunn The TGP isn't finished (the full train runs don't show up in the UI until they are; only the smoke test is available immediately). From prior work in this area, I know there will be failures that need to be fixed.

2022-04-15 20:50 UTC, dylhunn commented
> only the smoke test is available immediately

Thanks for clarifying!

2022-04-21 16:22 UTC, atscott commented
Internal cleanup is finished. Started a new global presubmit to ensure there weren't any regressions. Then this should be good to go today or tomorrow.

2022-04-22 16:48 UTC, atscott commented
merge assistance: requires internal patch when syncing: http://cl/443689787

2022-04-25 17:41 UTC, atscott commented
This PR was merged into the repository by commit 31d7c3bd71fdab3fef1b4615ecb8124fe6c165bd.

2022-04-25 17:41 UTC, closed without merging