refactor(docs-infra): Redirect old document title guide to new router…
angular/angular pull request #45857
Opened 2022-05-03 21:01 UTC by atscott

… feature

The "set-document-title" guide was in place to direct developers to the
`Title` service for managing page titles. Managing the title is now
available in the `Router` package and is much easier. This change
deletes the old guide and redirects it to the section in the router
guide about setting the page title.

2022-05-03 21:03 UTC, twerske submitted a review, later dismissed
lgtm thank you for this simplification of the guides!

2022-05-03 21:10 UTC, mary-poppins commented
You can preview 6b2f283 at https://pr45857-6b2f283.ngbuilds.io/.

2022-05-03 21:26 UTC, mary-poppins commented
You can preview a9ed7d0 at https://pr45857-a9ed7d0.ngbuilds.io/.

2022-05-03 21:51 UTC, mary-poppins commented
You can preview 7185a85 at https://pr45857-7185a85.ngbuilds.io/.

2022-05-03 23:23 UTC, andrewseguin commented
Pull approve really really wants me to review this.

2022-05-04 09:14 UTC, gkalpak approved these changes

2022-05-04 09:14 UTC, gkalpak commented on aio/content/guide/router.md
> +<a id="setting-the-page-title"></a>
Nit: Using `@a` would more idiomatic for docs-infra :grin:

```suggestion
{@a setting-the-page-title}
```

2022-05-04 09:19 UTC, gkalpak requested changes
One comment. Otherwise lgtm :+1:

Also, one question:
What about apps that don't use the router? Would it make sense to keep the `et-document-title` guide (and add a reference to the router guide for people that _are_ using the router)?

2022-05-04 09:19 UTC, gkalpak commented on aio/content/guide/example-apps-list.md
> +<code-example header="AppRoutingModule (excerpt)" path="router/src/app/app-routing.module.10.ts" region="page-title"></code-example>
This document just lists example apps. I don't think it makes sense to show a code snippets here.
I would just remove this section (since the router example is already listed).

2022-05-04 16:12 UTC, atscott commented on aio/content/guide/router.md
> +<a id="setting-the-page-title"></a>
I think this may have actually changed? The `{@a...` is actually showing up on the page and none of the other links here use that format https://angular.io/guide/router#setting-the-page-title

2022-05-04 16:34 UTC, gkalpak commented on aio/content/guide/router.md
> +<a id="setting-the-page-title"></a>
The reason it renders on the page is because it is `{@` and not `{@a` (i.e. it is missing the `a`) :grin:
But, nevermind, let's keep it consistent with the rest of the links here 🤔

2022-05-04 16:37 UTC, gkalpak approved these changes, later dismissed

2022-05-04 16:37 UTC, gkalpak commented on aio/content/guide/example-apps-list.md
Nit: Since this document lists live examples, I would remove the whole `Setting the document title` section (since it doesn't include a live example and the associated live example is already mentioned in this doc.

2022-05-04 17:58 UTC, atscott commented on aio/content/guide/example-apps-list.md
Done!

2022-05-04 18:04 UTC, josephperrott submitted a review, later dismissed
LGTM

2022-05-04 23:30 UTC, AndrewKushnir commented
This PR was merged into the repository by commit e4538e03d6baf3e0968a9491b70a209fb6ba5053.

2022-05-04 23:37 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 8786c609f8ea6ba4c9e3fbb037d47d83f0940e3a.

2022-05-04 23:37 UTC, closed without merging