docs: update service-worker-config to more clearly describe behavior
angular/angular pull request #45909
Opened 2022-05-06 08:31 UTC by jekru

Fixes #45280

2022-05-12 14:46 UTC, gkalpak requested changes
Thx, @jekru, and sorry it took me so long to get around to it 😇
I left a couple of suggestions.

2022-05-12 14:46 UTC, gkalpak commented on aio/content/guide/service-worker-config.md
> +* `^` is another character with a special meaning in a regular expression and matches the position before the first character in a string. This character will not be added in the conversion from glob
I wouldn't say it is recommended (because some URLs are just partial patterns). Let's just say that if you want your pattern to match the beginning of the URL, you should add it :smiley:

2022-05-18 11:11 UTC, gkalpak requested changes
Thx for making the changes, @jekru.
Left a few more comments (mostly formatting).

2022-05-18 11:11 UTC, gkalpak commented on aio/content/guide/service-worker-config.md
> +</div>
Formatting suggestion:

```suggestion
    <div class="alert is-helpful">

      `foo/bar/$value` is an unmatchable expression because it is impossible to have a string that has any characters after it has ended.

    </div>
```

(Note that for our Markdown parser to work correctly, there should be a empty line when switching from HTML to Markdown.)

Same for the other alert below.

2022-05-18 11:11 UTC, gkalpak commented on aio/content/guide/service-worker-config.md
> +*   `$` is a special character in regex that matches the end of a line and will not be escaped in the internal conversion from glob to regex format. Be aware that you have to escape it yourself, othe
Please start each sentence on a new line (here and below):

```suggestion
*   `$` is a special character in regex that matches the end of a line and will not be escaped in the internal conversion from glob to regex format.
    Be aware that you have to escape it yourself, otherwise your url can result in an unmatchable regular expression.
```

2022-05-18 11:11 UTC, gkalpak commented on aio/content/guide/service-worker-config.md
> +* `^` is another character with a special meaning in a regular expression and matches the position before the first character in a string. This character will not be added in the conversion from glob
Can you please uppercase `URL` (to maintain consistency throughout the doc) :pray:

2022-05-19 15:47 UTC, gkalpak approved these changes
Thx again for making the changes, @jekru :+1:

I rebased this on latest `main` and squashed the commits to get CI green.
As I was looking at the final text, I realized the whole section would fit better into the guide flow it is were an alert, so I went ahead and made some adjustment. I added them in a separate fixup commit, so my changes are easier to review.

Can you please take a look and lmk what you think? If the changes look good to you, we can go ahead and get this merged 🚀 

Thx again for working on this and following through with my review suggestions :heart:

2022-05-19 19:23 UTC, jekru commented
> Thx again for making the changes, @jekru 👍
> 
> I rebased this on latest `main` and squashed the commits to get CI green. As I was looking at the final text, I realized the whole section would fit better into the guide flow it is were an alert, so I went ahead and made some adjustment. I added them in a separate fixup commit, so my changes are easier to review.
> 
> Can you please take a look and lmk what you think? If the changes look good to you, we can go ahead and get this merged 🚀
> 
> Thx again for working on this and following through with my review suggestions ❤️

Looks good to me!

2022-05-23 20:17 UTC, alxhub commented
This PR was merged into the repository by commit e235c70d7d38c50561f14b08ce17021e1d357c69.

2022-05-23 20:18 UTC, closed without merging