feat(core): update unknown tag error for jit standalone components
angular/angular pull request #45920
Opened 2022-05-08 08:58 UTC by dario-piotrowicz

update the error message presented during jit compilation when an unrecognized
tag/element is found in a standalone component so that it does not mention
the ngModule anymore

Note: the aot variant is present in PR #45919

resolves #45818

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (may be a bugfix)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Issue

Issue Number: #45818

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-05-08 09:08 UTC, dario-piotrowicz commented on packages/core/src/render3/instructions/lview_debug.ts
> +      public standalone: boolean,
adding the standalone flag to the `Tview` seemed to me the cleanest way to get that info in the `validateElementIsKnown`, I hope that makes sense :sweat:

2022-05-08 09:11 UTC, dario-piotrowicz commented
I wanted to add unit tests for this, but it does not seem like there are any unit tests regarding this sort of functionality, please let me know if I should add some somewhere

(I may be wrong but I imagine that jit is almost deprecated in favour of aot? so maybe that's why unit testing functionalities here is not as important?)

2022-05-10 04:54 UTC, AndrewKushnir commented
@dario-piotrowicz thanks for creating this PR! I think we should try to use the approach proposed by Joost (in https://github.com/angular/angular/issues/45818#issuecomment-1120960917) vs adding it to the `TView`. Since this information is not needed anywhere other than the error message, we'd be able to tree-shake away that code in prod bundles (unlike the changes in `TView`, which would not be tree-shakable). 

Quick comment: let's update the commit message to say `fix(core): ...`, since this is the fix to the error message, which looks incorrect in a context of standalone components (the second PR can be marked as a fix as well).

2022-05-10 13:07 UTC, pkozlowski-opensource commented
@dario-piotrowicz yes, I still believe that we should add relevant tests for the JIT case to exercise changes to packages/core/src/render3/instructions/element.ts. As for the test location I've suggested on in my previous comment  https://github.com/angular/angular/issues/45818#issuecomment-1120950658

2022-05-12 07:57 UTC, dario-piotrowicz commented
@AndrewKushnir @pkozlowski-opensource Thank you very much :slightly_smiling_face: 

I'll address all your comments this coming weekend, sorry that it's been a slow few days :sweat:

2022-05-16 11:09 UTC, dario-piotrowicz commented on packages/core/test/acceptance/standalone_spec.ts
> +        it('should not warn the user when an unknown element is present inside an ng-template',
@pkozlowski-opensource is this what you had in mind in https://github.com/angular/angular/issues/45818#issuecomment-1120950658? :slightly_smiling_face:

2022-05-16 17:27 UTC, AndrewKushnir commented on packages/core/src/render3/instructions/element.ts
> +    const hostIsStandalone = !!(def?.standalone);
I feel like we may need this logic in other error messages as we start to update them with standalone context more. I'd like to propose that we extract it to a separate function (for ex. `isHostComponentStandalone` and put it in `render3/instructions/shared.ts` file) and add a check like this:
https://github.com/angular/angular/blob/ca04ecedec42bc15a8135936ae33a8850cbd641d/packages/core/src/render3/state.ts#L355
It should help avoid adding this relatively slow path into the perf-sensitive code (like change detection). If we come across a situation when we need similar detection in the non-dev mode, we'd need to re-consider adding a flag to the `TView` (as it was implemented originally in this PR).

2022-05-16 17:27 UTC, AndrewKushnir commented on packages/core/src/render3/instructions/element.ts
> +                             'part of this module'}.\n`;
```suggestion
                             'a part of this module'}.\n`;
```

2022-05-16 21:43 UTC, dario-piotrowicz commented on packages/core/src/render3/instructions/element.ts
> +    const hostIsStandalone = !!(def?.standalone);
sounds good! :slightly_smiling_face::+1:

I actually did think of creating a function for this piece of code but I was afraid of overengineer things :sweat_smile:

2022-05-16 22:09 UTC, dario-piotrowicz commented on packages/core/test/acceptance/standalone_spec.ts
> +        it('should not warn the user when an unknown element is present inside an ng-template',
I've added the test with the `[ngIf]="true]` below :slightly_smiling_face:

2022-05-18 12:17 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/standalone_spec.ts
> +      describe('unknown elements', () => {
nit: do we need the nested `describe` blocks here? IMO one block would be enough. Alternatively pull it into the existing `describe('schemas', () => {` block.

2022-05-18 12:35 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/element.ts
> +    const hostIsStandalone = !!(def?.standalone);
Agree with @AndrewKushnir - we should have a utility function here.

2022-05-18 12:38 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/element.ts
> +    const def = getComponentDef(context.constructor);
So I'm nervous about the usage of the `context.constructor` here as it is not 100% reliable AFAIK. Kind of thinking that maybe we should store the `isStandalone` flag on the `TView` instead.

2022-05-18 18:05 UTC, dario-piotrowicz commented on packages/core/test/acceptance/standalone_spec.ts
> +      describe('unknown elements', () => {
ah yeah good point, I am not sure why I did it this way :sweat: 

anyways I removed the inner describe block and changed the text to `unknown template elements` that should be clear enough I hope, what do you think is that ok? :slightly_smiling_face: 

(by the way, I can put this new describe inside the schemas one, I didn't do that as here nothing is being directly done with schemas, so I am not sure I am totally a fan of that, but if you'd prefer it that way I can move it there :slightly_smiling_face: )

2022-05-18 18:58 UTC, dario-piotrowicz commented on packages/core/src/render3/instructions/element.ts
> +    const def = getComponentDef(context.constructor);
I've added a `isHostComponentStandalone` function as suggested by Andew, I hope that's fine :slightly_smiling_face: 

if not please let me know :slightly_smiling_face:

2022-05-18 19:04 UTC, dario-piotrowicz commented on packages/core/src/render3/instructions/element.ts
> +    const hostIsStandalone = !!(def?.standalone);
I've added the `isHostComponentStandalone` function please have a look :slightly_smiling_face: 

(by the way, seems like the other functions in the shared file don't have unit tests associated to them, what do you think should I add one for the new function? if so could you suggest a file? :pray:)

___

Also, would it be worth it to also extract this two lines into another function?
```ts
  const declarationLView = lView[DECLARATION_COMPONENT_VIEW] as LView<Type<unknown>>;
  const context = declarationLView[CONTEXT];
```
(something like `getLViewContext` or something along those lines), let me know if this is a good idea and in that case if you'd like me to do it here or in a separate PR :slightly_smiling_face:

2022-05-18 22:27 UTC, AndrewKushnir reviewed
@dario-piotrowicz thanks for addressing the feedback 👍
I've left some final comments from my side (Pawel may provide some additional feedback as well).

2022-05-18 22:27 UTC, AndrewKushnir commented on packages/core/src/render3/instructions/element.ts
> +  }
super nit: I think we can remove new lines in between:
```suggestion
    const hasDirectives =
        resolveDirectives(tView, lView, tNode, getConstant<string[]>(tViewConsts, localRefsIndex));
    const hostIsStandalone = isHostComponentStandalone(lView);
    validateElementIsKnown(native, tNode.value, tView.schemas, hasDirectives, hostIsStandalone);
  }
```
Usually I use new lines to separate a particular block of code from the rest of the code, but in our case this is a single logical block, so we can just remove line breaks.

2022-05-18 22:27 UTC, AndrewKushnir commented on packages/core/src/render3/instructions/shared.ts
> + * Checks if the component of a given view is a standalone one or not.
```suggestion
 * Checks if the current component is declared inside of a standalone component template.
```

2022-05-18 22:27 UTC, AndrewKushnir commented on packages/core/src/render3/instructions/shared.ts
> + * @returns `true` if the component owning this view is a standalone one, `false` otherwise
I'd suggest that we drop `@returns` as it's covered in the function description.
```suggestion
 * @param lView An `LView` that represents a current component that is being rendered.
```

2022-05-18 22:27 UTC, AndrewKushnir commented on packages/core/src/render3/instructions/shared.ts
> +  return !!(def?.standalone);
```suggestion
  const componentDef = getComponentDef(context.constructor);
  return !!(componentDef?.standalone);
```

2022-05-18 22:49 UTC, AndrewKushnir approved these changes
👍

2022-05-18 22:51 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:449597217:BASE:449597243:1652914246287:67afc63a).

2022-05-19 07:11 UTC, pkozlowski-opensource approved these changes
LGTM

2022-05-19 08:54 UTC, dario-piotrowicz commented on packages/core/src/render3/instructions/element.ts
> +    const hostIsStandalone = !!(def?.standalone);
@AndrewKushnir , @pkozlowski-opensource any comment on this one? :slightly_smiling_face:

2022-05-19 19:03 UTC, AndrewKushnir requested changes

2022-05-19 19:03 UTC, AndrewKushnir commented on packages/core/src/render3/instructions/element.ts
> +    const hostIsStandalone = isHostComponentStandalone(lView);
```suggestion
    const hasDirectives =
        resolveDirectives(tView, lView, tNode, getConstant<string[]>(tViewConsts, localRefsIndex));
    if (ngDevMode) {
        const hostIsStandalone = isHostComponentStandalone(lView);
```

2022-05-19 19:03 UTC, AndrewKushnir commented on packages/core/src/render3/instructions/element.ts
> +    const hostIsStandalone = isHostComponentStandalone(lView);
@dario-piotrowicz we've ran into some issues during the presubmit and it turned out that the origin of it is the fact that the `resolveDirectives` got moved within the `ngDevMode` block, so it's removed in prod builds. However the line is load-bearing for prod mode as well. Could you please update it?

Also coincidentally the CI didn't start for the PR, so we were unable the verify the code during the CI run (it's very likely that the CI would've caught it).

2022-05-19 19:09 UTC, dario-piotrowicz commented on packages/core/src/render3/instructions/element.ts
> +    const hostIsStandalone = isHostComponentStandalone(lView);
sure :slightly_smiling_face::+1:

2022-05-19 20:10 UTC, dario-piotrowicz commented on packages/core/src/render3/instructions/element.ts
> +    const hostIsStandalone = isHostComponentStandalone(lView);
done :slightly_smiling_face:, sorry for the inconvenience :sweat:

2022-05-19 22:26 UTC, AndrewKushnir approved these changes
@dario-piotrowicz thanks for addressing the feedback 👍 I'm starting a new presubmit and will add the PR to the merge queue if there are no failing targets.

2022-05-19 22:32 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:449846345:BASE:449846380:1652999411972:1cee7b50).

2022-05-19 22:39 UTC, AndrewKushnir approved these changes

2022-05-20 00:59 UTC, AndrewKushnir commented on packages/core/src/render3/instructions/shared.ts
> +  return !!(componentDef?.standalone);
@dario-piotrowicz it looks like some tests are failing on CI because the `context` becomes undefined in some cases. Looking at some of the tests in the `render3` folder, they seem to use old testing infrastructure and we didn't have a chance to convert them to the new one yet. However, according to the docs for the `lView[CONTEXT]` field:
https://github.com/angular/angular/blob/0e14df697ad00a094b3a2a07e6e5e4295e978830/packages/core/src/render3/interfaces/view.ts#L176-L183
we should account for the fact that the `lView[CONTEXT]` might be `null` or `undefined`.

So I'd propose adding a check like this:
```suggestion
  const context = declarationLView[CONTEXT];
  
  // Unable to obtain a context, fall back to the non-standalone scenario.
  if (!context) return false;
  
  const componentDef = getComponentDef(context.constructor);
  return !!(componentDef?.standalone);
```

2022-05-20 07:44 UTC, dario-piotrowicz commented on packages/core/src/render3/instructions/shared.ts
> +  return !!(componentDef?.standalone);
sounds good, thanks a lot! :slightly_smiling_face:

2022-05-21 01:24 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:449846345:BASE:450102044:1653096249424:2b9430b0).

2022-05-23 16:27 UTC, closed without merging