docs: add selin tunc to contributors
angular/angular pull request #45989
Opened 2022-05-13 15:10 UTC by celinetunc

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-05-13 16:43 UTC, jessicajaniuk requested changes
You're missing closing quotes and a comma. Once you fix that, this should be green and ready to merge.

2022-05-13 16:43 UTC, jessicajaniuk commented on aio/content/marketing/contributors.json
> +      "bio": "Selin is a Software Developer Expert using Angular and Java at Garanti BBVA Technology in Turkey. She is the first woman Angular GDE in Turkey. She spends her spare time with her family
```suggestion
      "bio": "Selin is a Software Developer Expert using Angular and Java at Garanti BBVA Technology in Turkey. She is the first woman Angular GDE in Turkey. She spends her spare time with her family, especially her little son, and by keeping herself up-to-date.",
```

2022-05-13 17:53 UTC, jessicajaniuk approved these changes, later dismissed
LGTM :cookie:

Thanks for the quick fix!

2022-05-13 19:30 UTC, mgechev commented on aio/content/marketing/contributors.json
> +},
```suggestion
  },
```

2022-05-13 19:30 UTC, mgechev approved these changes, later dismissed

2022-05-13 20:12 UTC, jessicajaniuk approved these changes, later dismissed

2022-05-13 20:53 UTC, jessicajaniuk commented
@celinetunc  The size change here is not from your PR. If you rebase to main, this should go away. Could you also squash your commits? That should eliminate the lint issue.

2022-05-13 21:19 UTC, mgechev submitted a review, later dismissed

2022-05-13 21:44 UTC, jessicajaniuk approved these changes

2022-05-13 22:01 UTC, mgechev approved these changes

2022-05-13 22:05 UTC, jessicajaniuk commented
This PR was merged into the repository by commit 3e873b55165cabb8d340811670a159e6ad9c3680.

2022-05-13 22:05 UTC, closed without merging

2022-05-15 11:07 UTC, celinetunc commented
> @celinetunc The size change here is not from your PR. If you rebase to main, this should go away. Could you also squash your commits? That should eliminate the lint issue.

Thank you so much for your support Jessica. :)