feat(http): improve error message for nullish header
angular/angular pull request #46059
Opened 2022-05-19 10:53 UTC by markostanimirovic

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #46048

## What is the new behavior?

Improved error message for nullish headers.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-06-14 23:29 UTC, AndrewKushnir requested changes

2022-06-15 00:20 UTC, markostanimirovic commented on packages/common/http/src/headers.ts
> +          if (!values) {
Thanks Andrew! I'd move the check to the top of the `HttpHeaders` constructor instead of `HttpClient` to display the same error also when the `HttpHeaders` class is instantiated with nullish headers outside of `HttpClient` class:

```ts
class HttpHeaders {
  constructor(headers?: string | { [name: string]: string | string[] }) {
    if (typeof ngDevMode === 'undefined' || ngDevMode) {
      assertNoEmptyHeaders(options.headers);
    }

    // ...
  }
}

// throw the error in both cases
const headers = new HttpHeaders({ h1: null, h2: undefined });
this.http.get(URL, { headers: { h1: null, h2: undefined } });
```

What do you think?

Btw, it's possible to pass `null` or `undefined` as value when the `strictNullChecks` flag is set to `false`. ([TS Playground](https://www.typescriptlang.org/play?strictNullChecks=false#code/MYGwhgzhAEASAu8AOsCmYAmqBOMDeAUNMdMAPYB2E82ArsPGdgBQAW6WuAXNHtANoUwAW1Q9q2AJYUA5gF1xNaTOgAfaBOX850AL4BKXroLGC5KvGjtMOGAF5oFVAHc4iFB1vM+rAIw8KWhAQABorACYeWgosADNpVAw9fQBuAiA))

2022-06-15 01:16 UTC, AndrewKushnir commented on packages/common/http/src/headers.ts
> +          if (!values) {
Good catch, thanks @markostanimirovic 👍 

In this case, I think we can move an the assert just a few lines higher:
```
         this.headers = new Map<string, string[]>();
+        if (typeof ngDevMode === 'undefined' || ngDevMode) {
+          assertValidHeaders(headers);
+        }
         Object.keys(headers).forEach(name => {
```
The `assertValidHeaders` function may look like this (note: I haven't tested the function, this is mostly to illustrate the idea):
```
// Verifies that the headers object has the right shape: the values
// must be either strings or arrays. Throws an error if an invalid
// header value is present.
function assertValidHeaders(headers: {[name: string]: string|string[]}) {
  for (const [key, value] of Object.entries(headers)) {
    if (typeof value !== 'string' && !Array.isArray(value)) {
      throw new Error(
          `Unexpected value of the \`${key}\` header provided. ` +
          `Expecting either a string or an array, but got: \`${value}\`.`);
    }
  }
}
```
It'd be great to add some tests for the `HttpClient` case as well.

2022-06-15 01:16 UTC, AndrewKushnir commented on packages/common/http/test/headers_spec.ts
> +        const headers = new HttpHeaders({foo: null!});
I'd propose adding a comment here to explain that the `strictNullChecks` may affect the typing and allow null/undefined values:
```suggestion
        // Note: the `strictNullChecks` set to `false` in TS config would make `null` and `undefined`
        // valid values within the headers object, thus this test verifies this scenario.
        const headers = new HttpHeaders({foo: null!});
```
The second test would benefit from the same comment as well.

2022-06-16 19:36 UTC, AndrewKushnir approved these changes
@markostanimirovic thanks for addressing the feedback. The change looks good 👍 

I've also ran tests in Google's codebase ([internal link](http://tap/OCL:455298649:BASE:455403061:1655397510321:6664063c)) and they came back as "green".

2022-06-16 21:39 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 82acbf919bae2ddb6a46f41239aa2a101901f089.

2022-06-16 21:39 UTC, closed without merging