fix(core): include component name into unknown element/property error message
angular/angular pull request #46160
Opened 2022-05-26 22:45 UTC by AndrewKushnir

This commit adds the component name into unknown element/property error message, so that it's easier to find a location of a template where the problem happened.

Closes #46080.

// cc @dario-piotrowicz 

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-05-26 22:52 UTC, dario-piotrowicz commented on packages/core/src/render3/instructions/shared.ts
>    return !!(componentDef?.standalone);
maybe it could be good to mention in the function's comment or here that if we are unable to get the component def then we fallback to the non-standalone scenario?

2022-05-27 01:28 UTC, AndrewKushnir commented on packages/core/src/render3/instructions/shared.ts
>    return !!(componentDef?.standalone);
Thanks @dario-piotrowicz, I've added a comment.

I think we should update the code in the followup PR to handle a case when we can't get a component def. In this case we can say in the error message something like "if the component is standalone - do <this>, otherwise - do <that>", i.e. include both branches of the error message.

2022-05-27 10:19 UTC, pkozlowski-opensource requested changes
LGTM overall, needs a bit of cleanup (see the in-line comments).

2022-05-27 10:19 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/element.ts
> +import {createDirectivesInstances, executeContentQueries, getDeclarationComponentDef, getOrCreateTNode, isHostComponentStandalone, matchingSchemas, resolveDirectives, saveResolvedLocalsInData} from '
The `isHostComponentStandalone` import is unused. As soon as you remove it you realise that the `isHostComponentStandalone` function is unused and could be removed.

2022-05-27 10:19 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +export function isHostComponentStandalone(lView: LView): boolean {
I think that this function is unused and can be removed.

2022-05-27 10:19 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +      componentClassName ? ` (used in the '${componentClassName}' component template)` : '';
This block of code is duplicated with https://github.com/angular/angular/pull/46160/files?diff=unified&w=1#diff-d872dd53a3ca6fcd2ed09a36f6a49d09cfdb185270dd090b50837b2e1f3d9c0cR253-R257 - can you think of factoring it into a common utility?

2022-05-27 16:36 UTC, dario-piotrowicz commented on packages/core/src/render3/instructions/shared.ts
>    return !!(componentDef?.standalone);
Yeah sounds like a good idea :slightly_smiling_face: 

Is there a specific circumstance when the contex/component def can't be determined?

2022-05-27 17:12 UTC, AndrewKushnir commented on packages/core/src/render3/instructions/shared.ts
> +      componentClassName ? ` (used in the '${componentClassName}' component template)` : '';
Thanks for the comment. I've extracted the common logic into separate functions that are reused in both places now.

I think what would be great to do as a followup is to extract those two functions that throw the unknown element and unknown property errors into a separate file (may be a new one) and make all of those helper functions (annotated with a "WARNING") "private" to that file, so they never leak to other code. This should also simplify the maintenance and future updates.

// cc @dario-piotrowicz to see if he might be interested in helping with the refactoring, since he is familiar with this part of the codebase.

2022-05-27 17:15 UTC, AndrewKushnir commented on packages/core/src/render3/instructions/shared.ts
>    return !!(componentDef?.standalone);
The scenarios are described here:
https://github.com/angular/angular/blob/f87aa2da8c908fedeb71a8757d6f5228d037d471/packages/core/src/render3/interfaces/view.ts#L176-L183

(we should double check though as some info might be outdated)

2022-05-27 17:15 UTC, pkozlowski-opensource approved these changes
LGTM

2022-05-27 17:22 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:451424190:BASE:451424232:1653672136156:3f7b99c5).

2022-05-27 17:23 UTC, dario-piotrowicz commented on packages/core/src/render3/instructions/shared.ts
>    return !!(componentDef?.standalone);
ok! that's super helpful! thanks a lot!!! :slightly_smiling_face:

2022-05-27 18:45 UTC, atscott commented
This PR was merged into the repository by commit b7394bf77f1444611cf1cb74d7629e9a243e141f.

2022-05-27 18:45 UTC, closed without merging