docs: update example file name
angular/angular pull request #46164
Opened 2022-05-27 03:59 UTC by mattshaffer11

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] ~Tests for the changes have been added (for bug fixes / features)~
- [ ] ~Docs have been added / updated (for bug fixes / features)~

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

The file `environment.prod.ts` is repeated twice in the first screenshot below (docs from [guide/build](https://angular.io/guide/build)). The second screenshot shows that the intention was to have one of the duplicated files be named `environment.staging.ts`.

<img width="1374" alt="screenshot-1" src="https://user-images.githubusercontent.com/6943927/170625480-a23102e6-58f0-40da-92c0-912279d15c94.png">

<img width="1376" alt="screenshot-2" src="https://user-images.githubusercontent.com/6943927/170625497-c7fb994d-b957-406b-b6f6-a7706575d550.png">

## What is the new behavior?

One of the duplicated `environment.prod.ts` file is renamed to `environment.staging.ts`.

<img width="1392" alt="screenshot-3" src="https://user-images.githubusercontent.com/6943927/170625581-405dc47d-4be9-44c4-ba7a-2efa30d163d3.png">

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
N/A

2022-05-27 12:24 UTC, clydin approved these changes

2022-05-27 12:53 UTC, mary-poppins commented
You can preview 699ae77 at https://pr46164-699ae77.ngbuilds.io/.

2022-05-27 12:57 UTC, clydin requested changes
Thank you for the contribution.

Can you also update the following line from `stage` to `staging`? https://github.com/angular/angular/pull/46164/files#diff-4dad243a888405ea923d4f7878048c5c03dda3b8139a03acad1736a052814052R33

2022-05-27 14:46 UTC, clydin approved these changes
LGTM

2022-05-27 14:46 UTC, mattshaffer11 commented
@clydin of course. Updated in 1508b887df094250c3a886377f918a679212912d. There was one other use of `stage` left that I renamed to `staging` as well.

2022-05-27 14:55 UTC, mary-poppins commented
You can preview 1508b88 at https://pr46164-1508b88.ngbuilds.io/.

2022-05-31 18:59 UTC, atscott commented
This PR was merged into the repository by commit efed24eb70187564e958f1b9231050d85b4979f3.

2022-05-31 18:59 UTC, closed without merging