Added online version of autoprefixer.
angular/angular pull request #46176
Opened 2022-05-29 08:33 UTC by rahulkumarsingh73690

Added online version of Autoprefixer. So users can instantly use it without installing it.

2022-05-30 10:27 UTC, alan-agius4 commented on aio/content/guide/build.md
> +Internally, [Autoprefixer](https://goonlinetools.com/autoprefixer/) relies on a library called [Browserslist](https://github.com/browserslist/browserslist) to figure out which browsers to support wit
We should use the official REPL. 

```suggestion
Internally, [Autoprefixer](https://autoprefixer.github.io/) relies on a library called [Browserslist](https://github.com/browserslist/browserslist) to figure out which browsers to support with prefixing.
```

2022-05-30 10:29 UTC, alan-agius4 requested changes
Thanks for this. 

Can you please update the commit message as per [guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit)? Thanks.

2022-05-30 10:36 UTC, rahulkumarsingh73690 commented on aio/content/guide/build.md
> +Internally, [Autoprefixer](https://goonlinetools.com/autoprefixer/) relies on a library called [Browserslist](https://github.com/browserslist/browserslist) to figure out which browsers to support wit
None of these are official but I recommend this one (https://goonlinetools.com/autoprefixer/) because it highlights css code error and both works on latest autoprefixer and postcss.

2022-05-30 10:37 UTC, rahulkumarsingh73690 commented
> Thanks for this.
> 
> Can you please update the commit message as per [guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit)? Thanks.

Isn’t this already follow all guidelines.

None of these are official but I recommend this one (https://goonlinetools.com/autoprefixer/) because it highlights css code error and both works on latest autoprefixer and postcss.

2022-05-30 11:35 UTC, alan-agius4 reviewed
The commit message should have `docs: ` as type example. 
`docs: update build section to include autoprefixer link`.

Thinking a bit more, I think it would be better to actually link to the autoprefixer docs (https://github.com/postcss/autoprefixer) which do include a link to a REPL. I think in this case users would expect that the link points tool docs based on the context of the paragraph. I'd expect a link to a REPL, if the wording mentions this.

2022-05-30 11:43 UTC, rahulkumarsingh73690 commented
> The commit message should have `docs: ` as type example. `docs: update build section to include autoprefixer link`.
> 
> Thinking a bit more, I think it would be better to actually link to the autoprefixer docs (https://github.com/postcss/autoprefixer) which do include a link to a REPL. I think in this case users would expect that the link points tool docs based on the context of the paragraph. I'd expect a link to a REPL, if the wording mentions this.

Official docs is already linked from above doc. So it doesn’t make sense for linking again.

I am closing this pr

2022-06-24 22:04 UTC, dylhunn commented
As Alan said above, it's probably OK just to link to the official docs, rather than a third party online service directly.

2022-06-24 22:04 UTC, closed without merging