docs: replace double dashes with m-dashes, fix typos
angular/angular pull request #46174
Opened 2022-05-28 11:59 UTC by looshch

Fixes #46173

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #46173 

## What is the new behavior?

m-dashes are used instead of double dashes and typos aren’t present

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-05-31 14:54 UTC, gkalpak requested changes
Thx, @looshch!
I requested one change. Otherwise lgtm :+1:

2022-05-31 14:54 UTC, gkalpak commented on aio/content/examples/animations/src/app/app.component.ts
> +    return this.contexts.getContext('primary')?.route?.snapshot?.data?['animation'];
This change is actually invalid. When accessing properties using square bracket notation, the [correct syntax][1] for optional chaining is indeed `o?.[prop]`.

Can you please revert this change :pray:

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#syntax

2022-06-01 13:28 UTC, gkalpak approved these changes
🚀

2022-06-01 13:29 UTC, gkalpak approved these changes
Reviewed-for: global-docs-approvers

2022-06-01 15:51 UTC, jessicajaniuk approved these changes
reviewed for: fw-animations, docs-getting-started-and-tutorial

2022-06-01 18:03 UTC, closed without merging