Add loaders for Cloudinary and ImageKit
angular/angular pull request #46277
Opened 2022-06-07 00:50 UTC by khempenius

## PR Type
What kind of change does this PR introduce?
- [x] Feature

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-06-07 09:03 UTC, pkozlowski-opensource requested changes
The change LGTM overall but we start to have code duplication between various loaders and I would love to see the common logic extracted before this PR gets merged.

2022-06-07 09:03 UTC, pkozlowski-opensource commented on packages/common/src/directives/ng_optimized_image/image_loaders/cloudinary_loader.ts
> +function assertValidPath(path: unknown) {
The code from here down to the end of this file is duplicated between loaders (similar code already [exists in the repo already](https://github.com/angular/angular/blob/7173711d16668003a41f095c615e39ae125f760a/packages/common/src/directives/ng_optimized_image/image_loaders/imgix_loader.ts#L39-L67)).

We should extract those utilities into something like loader_utils.ts or similar.

2022-06-07 09:03 UTC, pkozlowski-opensource commented on packages/common/src/directives/ng_optimized_image/image_loaders/imagekit_loader.ts
> +function assertValidPath(path: unknown) {
The code from here down to the end of this file is duplicated between loaders (similar code already [exists in the repo already](https://github.com/angular/angular/blob/7173711d16668003a41f095c615e39ae125f760a/packages/common/src/directives/ng_optimized_image/image_loaders/imgix_loader.ts#L39-L67)).

We should extract those utilities into something like loader_utils.ts or similar.

2022-06-07 15:03 UTC, kara approved these changes
LGTM, minor nits below

2022-06-07 15:03 UTC, kara commented on packages/common/src/directives/ng_optimized_image/image_loaders/cloudinary_loader.ts
> +      let params = `f_auto,q_auto`;
Can we add a brief comment for what these options mean and why we're adding them?

2022-06-07 15:03 UTC, kara commented on packages/common/src/directives/ng_optimized_image/image_loaders/imagekit_loader.ts
> +      let params = `tr:q-auto`;
Comment for what this param does?

2022-06-09 09:07 UTC, pkozlowski-opensource approved these changes
LGTM

2022-06-09 09:08 UTC, merged