refactor(common): throw an error if an absolute URL is passed to Image Loaders
angular/angular pull request #46368
Opened 2022-06-14 22:17 UTC by AndrewKushnir

This commit updates the logic of Image Loaders to throw an error in case an absolute URL is provided an an input to the loader function. The loaders can construct URLs based on image paths relative to the bas URL configured for a loader.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-06-15 06:09 UTC, pkozlowski-opensource commented on packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
> +      if (isAbsoluteURL(config.src)) {
Question: currently this check is not guarded by the `ngDevMode` and I wonder if it should?

2022-06-15 06:09 UTC, pkozlowski-opensource reviewed
LGTM overall, just wonder if we shouldn't guard the absolute URL checks with the dev mode?

2022-06-15 18:30 UTC, kara requested changes

2022-06-15 18:30 UTC, kara commented on packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
> +      if (isAbsoluteURL(config.src)) {
I thought we decided to allow support for absolute URLS in custom loaders, since that's valid for some CDNs? And just throw for built-ins. Can we add a test to ensure custom loaders don't throw?

2022-06-15 18:39 UTC, AndrewKushnir commented on packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
> +      if (isAbsoluteURL(config.src)) {
Yes, that's right, we keep an ability to use absolute URLs and let them be processed by the custom loaders. This change affects an internal helper function that we use to avoid code duplication. I'll add an explicit test as well to make sure that a custom loader registered via the `IMAGE_LOADER` token works with absolute URLs.

2022-06-15 18:53 UTC, AndrewKushnir commented on packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
> +      if (isAbsoluteURL(config.src)) {
The test is now added to the `packages/common/test/directives/ng_optimized_image_spec.ts` file.

2022-06-15 18:53 UTC, AndrewKushnir commented on packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
> +      if (isAbsoluteURL(config.src)) {
Good catch, I've missed it somehow 🤦‍♂️ The code is now updated.

2022-06-16 06:14 UTC, pkozlowski-opensource commented on packages/common/src/directives/ng_optimized_image/image_loaders/image_loader.ts
> +      RuntimeErrorCode.INVALID_LOADER_ARGUMENTS,
Thnx for doing this change @AndrewKushnir - I've noticed it while doing previous reviews and had it on my TODO list but it is now fixed :-) 👍

2022-06-16 06:15 UTC, pkozlowski-opensource approved these changes
It LGTM now. Let's make sure that Kara's concerns are addressed before merging, though.

2022-06-16 15:49 UTC, kara approved these changes
LGTM, thanks for adding the test!

2022-06-16 16:27 UTC, merged