refactor(common): make di error messages tree shakable
angular/angular pull request #46422
Opened 2022-06-18 03:49 UTC by ramthir

Tree shake error messages from the production build and introduce error codes.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Errors under ID are not tree-shakable in the production build.

Issue Number: N/A

## What is the new behavior?
Make the Errors under ID tree-shakable in the production build.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-06-21 12:19 UTC, pkozlowski-opensource commented on packages/core/src/di/reflective_key.ts
> +
nit: revert formatting?

2022-06-21 12:19 UTC, pkozlowski-opensource commented on packages/core/src/di/reflective_key.ts
> +      throw new RuntimeError(RuntimeErrorCode.MISSING_INJECTION_TOKEN, 'Token must be defined!');
Shouldn't we guard the "Token must be defined!" error message with `ngDevMode`?

2022-06-21 12:24 UTC, pkozlowski-opensource requested changes
@ramthir thnx for the PR. It seems like the error message in the `ReflectiveKey` class is not guarded with `ngDevMode` - is it intentional? 

Also the commit message should be changed from `refactor(common): ...` to `refactor(core): ...` as the changes touch the `core` package and not the `common` one.

2022-06-22 02:05 UTC, ramthir commented on packages/core/src/di/reflective_key.ts
> +
Storage, it gets formatted with `yarn ng-dev format changed`. I've reverted it.

2022-06-22 02:21 UTC, ramthir commented
@pkozlowski-opensource, thanks a lot for the review comments. I've made the changes you requested.

2022-06-22 08:11 UTC, pkozlowski-opensource approved these changes
LGTM

Reviewed-for: public-api

2022-06-22 08:12 UTC, pkozlowski-opensource approved these changes

2022-06-22 16:03 UTC, atscott approved these changes
reviewed-for: public-api

2022-06-22 20:45 UTC, AndrewKushnir commented on packages/core/src/di/reflective_key.ts
> +          RuntimeErrorCode.INJECTION_TOKEN_UNDEFINED, ngDevMode && 'Token must be defined!');
I think we can name this error code `MISSING_INJECTION_TOKEN`, similar to an existing `MISSING_INJECTION_CONTEXT` token:
```suggestion
          RuntimeErrorCode.MISSING_INJECTION_TOKEN, ngDevMode && 'Token must be defined!');
```

2022-06-23 02:19 UTC, ramthir commented on packages/core/src/di/reflective_key.ts
> +          RuntimeErrorCode.INJECTION_TOKEN_UNDEFINED, ngDevMode && 'Token must be defined!');
@AndrewKushnir, I've changed the error code to `MISSING_INJECTION_TOKEN` so it's more aligned with the existing ones.

2022-06-23 05:41 UTC, AndrewKushnir approved these changes
@ramthir thanks for the update 👍

2022-06-23 05:41 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2022-06-23 23:37 UTC, dylhunn commented
Would you be able to rebase this @ramthir?

2022-06-23 23:59 UTC, AndrewKushnir approved these changes

2022-06-24 00:14 UTC, ramthir commented
@dylhunn, I've rebased it. Now you can proceed with the merge.

2022-06-24 20:12 UTC, dylhunn commented
This PR was merged into the repository by commit 07828528be7cd64f0a8a9be3d574ab560815520d.

2022-06-24 20:12 UTC, closed without merging