feat(core): update `Injector.get` and `TestBed.inject` to support object-based flags
angular/angular pull request #46761
Opened 2022-07-09 01:59 UTC by AndrewKushnir

See individual commits.

## PR Type
What kind of change does this PR introduce?

- [x] Feature

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-07-10 21:31 UTC, AndrewKushnir commented
[Exploratory Presubmit](http://test/OCL:460085725:BASE:460085755:1657488626784:aa9bac4) (TGP will also be required).

2022-07-12 16:53 UTC, atscott requested changes

2022-07-12 16:53 UTC, atscott commented on goldens/public-api/core/testing/index.md
> +    inject<T>(token: ProviderToken<T>, notFoundValue: null, options?: InjectOptions): T | null;
A few questions here:

* Should `Injector.get` have an override like this one? 
* Shouldn't this include `undefined` as well as `null`?
* I think return value `| null` depends on `optional` being explicitly `true`, right?

2022-07-13 00:46 UTC, AndrewKushnir commented on goldens/public-api/core/testing/index.md
> +    inject<T>(token: ProviderToken<T>, notFoundValue: null, options?: InjectOptions): T | null;
> Can we add a TODO for v15 then?

Added a note to revisit this in one of the major versions.

> Both? TestBed.inject mimics injector.get. But also Injector.get doesn't have this override at the moment anyways. The previous bullet was requesting to add it.

Added the override that we've discussed.

2022-07-13 05:43 UTC, AndrewKushnir commented
[TGP #2](https://test.corp.google.com/OCL:460085725:BASE:460631437:1657690975961:2319f4a8).

2022-07-13 08:29 UTC, alxhub reviewed
FYI, I think that modifying the signature of `Injector.get` is a breaking change. We should add the appropriate notice and push this to v15.

2022-07-13 08:29 UTC, alxhub commented on packages/core/src/di/injector_compatibility.ts
> +  if (typeof flags === 'undefined' || typeof flags === 'number') return flags;
```suggestion
  if (typeof flags === 'undefined' || typeof flags === 'number') {
    return flags;
  }
```

2022-07-13 08:29 UTC, alxhub commented on packages/core/src/di/injector_compatibility.ts
> +export function convertToBitFlags(flags: InjectOptions|InjectFlags|undefined): InjectFlags|
```suggestion
export function convertToBitFlags(flags: undefined): undefined;
export function convertToBitFlags(flags: InjectOptions|InjectFlags): InjectFlags;
export function convertToBitFlags(flags: InjectOptions|InjectFlags|undefined): InjectFlags|
```

Setting up the signature like this will allow you to skip the `as InjectFlags` cast later when TS knows that `flags` is defined.

2022-07-13 17:13 UTC, AndrewKushnir commented
Discussed offline: this is a breaking change, so we postpone it for now and will come back to this PR once the `main` branch opens up for v15 changes (after v14.2.0 release). I've applied the necessary labels and added this PR to the `v15-candidates` milestone.

2022-09-13 01:04 UTC, AndrewKushnir commented
[Presubmit #3](http://test/OCL:473891486:BASE:473891527:1663031040658:38744377).

2022-09-23 10:19 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/di_spec.ts
> +      it('should be able to optionally inject a service', () => {
nit: I find the title of this test a bit misleading since we don't inject any service. I would expect something along the lines of "should return null when trying to inject non-existing service with optional flag" - or something like this.

2022-09-23 10:21 UTC, pkozlowski-opensource reviewed
@AndrewKushnir the change LGTM overall, I'm just confused by the e2e tests change. Would love to discuss this before the final approval.

2022-09-23 19:10 UTC, pkozlowski-opensource approved these changes

2022-09-23 20:42 UTC, alxhub approved these changes

2022-09-23 20:45 UTC, alxhub requested changes

2022-09-23 20:45 UTC, alxhub commented on packages/core/src/di/injector.ts
> +  abstract get<T>(token: ProviderToken<T>, notFoundValue?: T, options?: InjectOptions|InjectFlags):
We should absolutely extend the type here so that if you pass `undefined, {optional: true}` you get a `T|null` return type. Ditto for `TestBed.inject()`.

2022-09-23 20:48 UTC, atscott approved these changes

2022-09-23 22:19 UTC, AndrewKushnir commented on packages/core/src/di/injector.ts
> +  abstract get<T>(token: ProviderToken<T>, notFoundValue?: T, options?: InjectOptions|InjectFlags):
Thanks for the feedback @alxhub 👍 I've pushed a fixup commit:
https://github.com/angular/angular/pull/46761/commits/8690b13fcb8813263aedeefef0fbab4c7076a1ce

Could you please take another look?

2022-09-24 00:40 UTC, AndrewKushnir commented
@alxhub I've updated the API and added a couple tests as we discussed (fixup commit: https://github.com/angular/angular/pull/46761/commits/6159102533dc3f61ba39f0dc5a6d735ccedc2831). Could you please take another look?

2022-09-27 02:30 UTC, alxhub approved these changes

2022-09-27 03:48 UTC, AndrewKushnir commented
[One more TGP before the submission](https://test.corp.google.com/OCL:477065069:BASE:477065121:1664250511881:faede2ec).

2022-09-27 15:43 UTC, jessicajaniuk approved these changes
reviewed-for: public-api

2022-09-27 16:17 UTC, alxhub approved these changes
Reviewed-for: public-api

2022-09-27 16:19 UTC, jelbourn approved these changes
LGTM

Reviewed-for: public-api

2022-09-27 16:25 UTC, pkozlowski-opensource approved these changes
LGTM

Reviewed-for: public-api 
Reviewed-for: fw-core

2022-09-27 17:09 UTC, alxhub commented
This PR was merged into the repository by commit 120555a626d66523e46ce01681b11a0f38e3a40a.

2022-09-27 17:09 UTC, closed without merging