docs: add info about request timeouts
angular/angular pull request #46803
Opened 2022-07-12 17:31 UTC by bob-watson

Docs-only change that:

* Adds a short note about how service workers report request timeouts
* Updated heading levels to present a clearer hierarchy and cleaner local TOC
* Removed documentation lint errors
* Fixes #46445

2022-07-14 17:01 UTC, mary-poppins commented
You can preview c04ab73 at https://pr46803-c04ab73.ngbuilds.io/.
You can preview 1804e4e at https://pr46803-1804e4e.ngbuilds.io/.
You can preview 1573c35 at https://pr46803-1573c35.ngbuilds.io/.

2022-07-14 18:30 UTC, gkalpak commented on aio/content/guide/service-worker-config.md
> +## Handling errors when the server can't be reached
This section feels a little out of place in this guide. I'd rather put it in the [SW introduction][1] or the [SW in production][2] guide.

[1]: https://pr46803-1573c35.ngbuilds.io/guide/service-worker-intro
[2]: https://pr46803-1573c35.ngbuilds.io/guide/service-worker-devops

2022-07-14 19:58 UTC, mary-poppins commented
You can preview e367391 at https://pr46803-e367391.ngbuilds.io/.

2022-07-14 22:38 UTC, bob-watson commented on aio/content/guide/service-worker-config.md
> +2.  If the network request does not complete immediately, ignore the cache age and fall back to the cached value.
Thanks!

2022-07-14 22:41 UTC, bob-watson commented on aio/content/guide/service-worker-config.md
> +| Groups with the `performance` strategy | The default value is `false` and the service work doen't cache opaque responses. These groups would continue to return a cached response until `maxAge` expi
Thanks.

2022-07-14 23:42 UTC, bob-watson commented on aio/content/guide/service-worker-config.md
> +## Handling errors when the server can't be reached
I agree.
How does it look in its new home?

2022-07-14 23:49 UTC, mary-poppins commented
You can preview 7a6fc47 at https://pr46803-7a6fc47.ngbuilds.io/.

2022-07-15 14:25 UTC, mary-poppins commented
You can preview d45ec84 at https://pr46803-d45ec84.ngbuilds.io/.

2022-07-18 20:09 UTC, gkalpak requested changes

2022-07-18 20:09 UTC, gkalpak commented on aio/content/guide/service-worker-devops.md
> +If the service worker doesn't receive a response, it returns a [504 Gateway Timeout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) status. A `504` status could be returned because the
This is definitely simpler than my [previous suggestion][1] (:+1:), but there are a couple of points that are missing/conveyed incorrectly. It would be great if we could make these more clear:

- This SW behavior applies to all failed requests. I.e. not just when no response is received, but also when an error response is received (for example, a response with a 4xx or 5xx status code). The client' being offline or the server's being down are just two examples (of many possible causes).

- I'd prefer to give the 504 response as an example of the type of response that the SW would generate, not as a de facto behavior. I.e. I would put more emphasis on the fact that the SW will generate its own error response and what it tries to indicate, rather than the specific status code.
  The reason is that I would like to discourage people from treating the 504 response as an API, but rather build their apps so they can handle regular failure responses. This is better for the apps (since you cannot rely on the SW always being in effect) and a easier for us to potentially change the SW behavior in the future (while keeping the same intent).

I don't feel too strongly about these, but if we could somehow include them (without hurting simplicity/clarity) it would be great 🚀 

[1]: https://github.com/angular/angular/pull/46803#discussion_r921454991

2022-07-18 23:52 UTC, bob-watson commented on aio/content/guide/service-worker-devops.md
> +`ngsw.json` is the manifest file that is created at build time based on `ngsw-config.json`.
simpler language.

2022-07-18 23:56 UTC, bob-watson commented on aio/content/guide/service-worker-devops.md
> +In a normal HTTP cache, a hard refresh or the cache expiring limits the negative effects of caching an file that's not valid.
Thanks!

2022-07-19 00:09 UTC, bob-watson commented on aio/content/guide/service-worker-devops.md
> +As a result, the service worker must get the correct content.
This section was hard for me to parse. I see a lot of facts, but what's important and what's merely descriptive is hard to separate. 

Re-reading this, it looks like we might be burying the lede, in that the critical fact here seems to be that **the service worker long-caches the application.**

Reading further, I'm thinking the **Resource integrity** section might benefit from a rewrite to help sort out descriptions from key takeaways.  Adding a section to indicate **Hashed content** as separate from **Unhashed content**, which already has a header, might also help.

2022-07-19 00:12 UTC, bob-watson commented on aio/content/guide/service-worker-devops.md
> +If necessary, the service worker enters a safe mode where requests fall back on the network. The service worker doesn't use its cache if there's a high risk of serving content that is not valid, brok
Interesting point. I see what you mean. I'll  reorder them which should remove that risk of confusion.

2022-07-19 00:13 UTC, bob-watson commented on aio/content/guide/service-worker-devops.md
> +All requests pass through the service worker to the service unless
What does the service worker pass them through to?

2022-07-19 00:14 UTC, bob-watson commented on aio/content/guide/service-worker-devops.md
> +the [service worker is explicitly bypassed](guide/service-worker-devops#bypassing-the-service-worker).
Thanks. I missed the forest for the tree :)

2022-07-19 00:16 UTC, bob-watson commented on aio/content/guide/service-worker-devops.md
> +Also included in the `@angular/service-worker` NPM package is a small script `safety-worker.js`, which when loaded un-registers itself from the browser and remove the service worker caches.
Thanks!

2022-07-19 00:17 UTC, bob-watson commented on aio/content/guide/service-worker-devops.md
> +The old worker, which was registered at `example.com`, tries to update and sends requests to the old location `example.com`. This request is redirected to the new location `www.example.com` and creat
Thanks!

2022-07-19 02:00 UTC, bob-watson commented on aio/content/guide/service-worker-devops.md
> +If the service worker doesn't receive a response, it returns a [504 Gateway Timeout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) status. A `504` status could be returned because the
I tried to work that in. Let me know what you think.

2022-07-19 02:01 UTC, bob-watson commented on aio/content/guide/service-worker-config.md
> +| Groups with the `performance` strategy | The default value is `false` and the service work doesn't cache opaque responses. These groups would continue to return a cached response until `maxAge` exp
Thanks!

2022-07-19 02:39 UTC, bob-watson commented
The commit list got all out-of-whack for this, so I opened PR #46882 with the commits that address the last round of comments.

2022-07-19 02:39 UTC, closed without merging