feat(router): expose resolved route title
angular/angular pull request #46826
Opened 2022-07-13 17:13 UTC by EmmanuelRoux

fixes #46825

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #46825 

## What is the new behavior?
Since Angular 14, router has a new mechanism to update page title from route config. The route can either be a static string or resolved in the same way as `resolve` data.

But the resolved route title is not exposed and inaccessible from client application (it seems the title is actually stored in the resolved `Data`, but using a private `Symbol` so it can't be accessed properly).

This PR adds a new `title` property on `ActivatedRoute` and `ActivatedRouteSnapshot`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-07-13 19:25 UTC, atscott requested changes

2022-07-13 19:25 UTC, atscott commented on packages/router/src/router_state.ts
> +  _title!: Observable<string|undefined>;
```suggestion
  readonly title = this.data.pipe(map(data => data[TitleKey]));
```

2022-07-13 19:25 UTC, atscott commented on packages/router/src/router_state.ts
> +
```suggestion
  /** The resolved route title */
  readonly title = this.data[TitleKey];
```
(and move this line up above the constructor)

2022-07-13 19:25 UTC, atscott commented on packages/router/src/router_state.ts
> +
```suggestion
```

2022-07-13 19:25 UTC, atscott commented on packages/router/test/router_state.spec.ts
> +import {RouteTitle as TitleKey} from "@angular/router/src/page_title_strategy";
```suggestion
import {RouteTitle as TitleKey} from "../src/page_title_strategy";
```

2022-07-15 21:31 UTC, EmmanuelRoux commented on packages/router/src/shared.ts
> +export const RouteTitleKey = Symbol('RouteTitle');
Not sure about moving that here, that's because of circular dependencies:
`packages/router/src/page_title_strategy.ts → packages/router/src/router_state.ts`

2022-07-16 00:33 UTC, atscott commented on packages/router/src/router_state.ts
> +  _title!: Observable<string|undefined>;
I think it would be best to update it in a different PR to keep things here more focused. Aligning with existing code isn't always the best thing to do given that existing code was often written long ago when TypeScript was less mature and our code style has evolved since then as well.

2022-07-18 17:52 UTC, atscott commented on packages/router/src/shared.ts
> +export const RouteTitleKey = Symbol('RouteTitle');
Yea, this should be fine.

2022-07-18 17:53 UTC, atscott requested changes
LGTM for the changes. Before we merge, could you please squash the commits into one?

2022-07-18 17:57 UTC, atscott commented on packages/router/src/router_state.ts
> +  readonly title: string|undefined = this.data?.[RouteTitleKey];
Actually one thing that came up in our presubmit checks was build failures due to this being required. Since it's also optional on the `Route` interface, this should be optional as well. Making it required here would be breaking for something like ngrx's serializer: https://github.com/ngrx/platform/blob/bdb86344c05b88c96602692dbc7310154e16cf0f/modules/router-store/src/serializers/full_serializer.ts#L19-L51

I don't think this is strictly necessary for the `ActivatedRoute`.

2022-07-18 20:08 UTC, atscott approved these changes

2022-07-18 20:09 UTC, atscott approved these changes
reviewed-for: public-api

2022-07-18 20:36 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2022-07-18 20:57 UTC, jessicajaniuk approved these changes
reviewed-for: public-api

2022-07-18 22:07 UTC, atscott requested changes

2022-07-18 22:33 UTC, atscott approved these changes

2022-07-20 20:54 UTC, atscott commented
caretaker note: This will require patching [cl/462221001](http://cl/462221001) when syncing.

2022-07-20 22:41 UTC, atscott commented
[green TGP](https://fusion2.corp.google.com/presubmit/tap/461692865/OCL:461692865:BASE:462193069:1658342251290:d215760e/targets) with patches

2022-07-20 22:43 UTC, atscott commented
merge assistance:

* This will require patching [cl/462221001](http://cl/462221001) when syncing.
* TGP was green with the local patch but it would be a good idea to merge and sync this on its own

2022-07-21 09:24 UTC, pkozlowski-opensource commented
This PR was merged into the repository by commit 10289f1f6e3d5935304a38d4300d4dadfea66150.

2022-07-21 09:25 UTC, closed without merging