docs: initial upload of styles used by doc linter
angular/angular pull request #46897
Opened 2022-07-19 22:53 UTC by bob-watson

This PR replaces  PR #46854 and includes the edits to the comments from that PR.

Adds styles and configuration files for contributors to use the Vale documentation linter in their IDE while they edit angular.io topics.
This commit includes documentation for using the documentation linter in the README.md file.
This commit does not alter any angular.io or other published documentation.

This commit is going to cause problems with the inclusive language CI test because it includes files with all the prohibited words in its tests to look for those words in the documentation.

These seem to be only two files:

aio/tools/doc-linter/dictionaries/en_us/en_US-web.dic
aio/tools/doc-linter/styles/Angular/Angular_Inclusive.yml

2022-07-19 23:01 UTC, mary-poppins commented
You can preview d22e60d at https://pr46897-d22e60d.ngbuilds.io/.

2022-07-20 20:25 UTC, gkalpak requested changes
A couple of comments that probably need addressing and a few optional suggestions.

BTW, you can ensure VSCode will show the vale extension as recommended for the workspace when people open the `angular/angular` repo, by adding it in [.vscode/extensions.json][1] (or leave it commented out at the bottom of the list if it's only useful when working with docs inside the `aio/` directory):

```diff
   "recommendations": [
     "devondcarew.bazel-code",
     "gkalpak.aio-docs-utils",
     "ms-vscode.vscode-typescript-tslint-plugin",
     "xaver.clang-format",
     // The following extensions are useful when working on angular.io (i.e. inside the `aio/` directory).
     //"angular.ng-template",
     //"dbaeumer.vscode-eslint",
+    //"errata-ai.vale-server",
   ],
```

[1]: https://github.com/angular/angular/blob/d583f85701b0424496e263bf1cbc2c619869437e/.vscode/extensions.json

2022-07-20 20:25 UTC, gkalpak commented on aio/tools/doc-linter/README.md
> +> you might miss an update to the style tests if it falls behind the `angular/angular` repo.
Here to, you could style it as a note (if you wanted) with:

```suggestion
> **Note**
> The style tests used by Vale are stored in your clone of the `angular/angular` repo.
> For best results, use the `main` branch of the `angular/angular` repo when you set the path of `vale.ini` in the IDE extension settings.
> While the style tests don't change frequently, if you reference a fork or another branch of that repo,
> you might miss an update to the style tests if it falls behind the `angular/angular` repo.
```

2022-07-20 20:25 UTC, gkalpak commented on aio/tools/doc-linter/README.md
> +> While the style tests don't change frequently, if you reference a fork or another branch of that repo,
This is potentially misleading/confusing. You can't really reference a specific branch in a local file path.

2022-07-20 20:25 UTC, gkalpak commented on aio/tools/doc-linter/README.md
> +1.  Install the `Vale` Visual Studio Code extension.
Maybe mention that you need to go the Extensions pane first :smiley:
You can also put the link the extension's page on the VSCode marketplace: https://marketplace.visualstudio.com/items?itemName=errata-ai.vale-server
(You can install an extension from there directly, which is potentially easier.)

2022-07-20 20:25 UTC, gkalpak commented on aio/tools/doc-linter/README.md
> +    > **NOTE** <br />
Here too (if desired):

```suggestion
    > **Note**
```

2022-07-20 20:25 UTC, gkalpak commented on aio/tools/doc-linter/README.md
> +    > On macOS, the **Preferences** menu item is located under the **Code** nav-bar.
FWIW, on Windows **Preferences** is under **File**.

2022-07-20 20:25 UTC, gkalpak commented on aio/tools/doc-linter/README.md
> +    2.  In your `github` workspace, navigate to the `angular\aio\tools\doc-linter` directory.
https://github.com/angular/angular/pull/46854#discussion_r923513658 still applies here :smiley:

2022-07-20 22:39 UTC, mary-poppins commented
You can preview e326d94 at https://pr46897-e326d94.ngbuilds.io/.

2022-07-21 01:46 UTC, bob-watson commented
Thanks for the notes!
The latest commit should address all of your comments.

2022-07-21 01:51 UTC, mary-poppins commented
You can preview 90a3123 at https://pr46897-90a3123.ngbuilds.io/.

2022-07-21 15:15 UTC, mary-poppins commented
You can preview f7dd117 at https://pr46897-f7dd117.ngbuilds.io/.

2022-07-22 14:36 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +> Keeping the docs easy to read, lets the developers concentrate on their coding.
Thanks! The most recent commit includes this.

2022-07-22 14:36 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +> Style guides and tests can change and evolve.
Thanks! The most recent commit includes this.

2022-07-22 14:36 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +Long sentences, as well as the use of parentheses, semi-colons, or a words identified as *too-wordy*, generally require rethinking and rewriting.
Thanks! The most recent commit fixes this.

2022-07-22 14:36 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +        Save the returned path for use in the next procedure.
Thanks! The most recent commit fixes this.

2022-07-22 14:37 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +        Save the returned path for use in the next procedure.
Thanks! The most recent commit fixes this.

2022-07-22 14:37 UTC, mary-poppins commented
You can preview afade27 at https://pr46897-afade27.ngbuilds.io/.

2022-07-22 14:38 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +> you might miss an update to the style tests if it falls behind the `angular/angular` repo.
Thanks. 
I removed this note. It seemed to confuse more than help when I read it again (and again).

2022-07-22 14:39 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +> While the style tests don't change frequently, if you reference a fork or another branch of that repo,
See previous reply.

2022-07-22 14:40 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +1.  Install the `Vale` Visual Studio Code extension.
Thanks.
This should be clearer in the current version, although i didn't include the link.

2022-07-22 14:40 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +    > **NOTE** <br />
Thanks! The most recent commit fixes this.

2022-07-22 14:40 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +    > On macOS, the **Preferences** menu item is located under the **Code** nav-bar.
Thanks! The most recent commit fixes this.

2022-07-22 14:40 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +    2.  In your `github` workspace, navigate to the `angular\aio\tools\doc-linter` directory.
Thanks! The most recent commit fixes this.

2022-07-22 14:40 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +    2.  In your `github` workspace, navigate to the `angular/aio/tools/doc-linter` directory.
Thanks! The most recent commit fixes this.

2022-07-22 22:59 UTC, gkalpak approved these changes
Basically, one last issue regarding `git` workspace. Otherwise lgtm :tada:

##
FYI, while the commit messages follow the [commit message guidelines][1], having separate commits for addressing review comments is against the _spirit_ of the guidelines. I.e. all commits should be self-contained. For example, for this PR all changes could be part of one commit, sine they are all implementing the addition of the doc linter.

This is not terribly important for docs commits, because those do not end up in the auto-generated [changelog][2]. But it does affect the readability of the commit history and makes it more difficult to find out when a particular change was introduced (and why/what is the context). To be clear, it does to remove anything from our ability to read history and find out these things - it just makes it less easy.

BTW, there is currently a mechanism for adding new commits to address review feedback (which makes it easier for the reviewer) while at the same time ensuring that all changes will be combined into one commit when the PR is merged into the target branch: [fixup commits][3]
However, they are less straight-forward (especially if you are not using the git CLI or a git UI that supports this feature).

This is not necessarily a blocker. I just wanted to bring it up.
(BTW, happy to elaborate more on any points that are not clear.)

[1]: https://github.com/angular/angular/blob/3ca985269d3e961321075f0e7facd10ef335be4c/CONTRIBUTING.md#commit
[2]: https://github.com/angular/angular/blob/3ca985269d3e961321075f0e7facd10ef335be4c/CHANGELOG.md
[3]: https://github.com/angular/angular/blob/main/docs/FIXUP_COMMITS.md

2022-07-22 22:59 UTC, gkalpak commented on aio/tools/doc-linter/README.md
> +1.  You have cloned the [`angular/angular` repo][GithubAngularAngular] in the `git` workspace on your system. You can work in a fork of the `angular/angular` repo,
It sounds like there might be some confusion here. This sentence seems to imply that there is a `git` workspace inside of which repositories are cloned. This is not exactly the case.

You can clone a `git` repository anywhere on your file system. The process of cloning will create a directory. This directory is called the "workspace" (or "working directory") in the context of `git`. So, basically, each repository that you clone on your local system creates a `git` workspace (or working directory).

I think this [StackOverflow answer][1] does a good job explaining the concept of the `git` workspace.

##
So, based on the above, I'd keep the sentence as:

```
You have cloned the [`angular/angular` repo][GithubAngularAngular] on your system.
```

[1]: https://stackoverflow.com/questions/59441589/how-is-repository-different-from-workspace#answer-63523191

2022-07-22 22:59 UTC, gkalpak commented on aio/tools/doc-linter/README.md
> +    2.  In your `git` workspace, navigate to your clone of the `angular/angular` repo.
What you refer to as "the cloned repo" here _is_ the `git` workspace. See my comment on line 164 for more details.

So, I would combine these two sentences in one and only mention either "the `git` workspace" or "the cloned repo" (both options are fine imo).

The same applies to the Windows instructions below.

2022-07-25 14:01 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +Vale evaluates a markdown \(`.md`\) file when you open it in the IDE and each time you save it. Vale does not review your document as you make changes in it.
The contractions style is still under discussion/consideration/revision so, for now, it's disabled in the `vale.ini` config file.

2022-07-25 14:13 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +    2.  In your `git` workspace, navigate to your clone of the `angular/angular` repo.
Thanks for the SO explanation. That's a big help!

2022-07-25 14:16 UTC, bob-watson commented on aio/tools/doc-linter/README.md
> +1.  You have cloned the [`angular/angular` repo][GithubAngularAngular] in the `git` workspace on your system. You can work in a fork of the `angular/angular` repo,
Thanks!

2022-07-25 14:24 UTC, mary-poppins commented
You can preview 36464ea at https://pr46897-36464ea.ngbuilds.io/.

2022-07-26 21:55 UTC, gkalpak approved these changes
:shipit:

2022-08-01 16:29 UTC, AndrewKushnir commented
This PR was merged into the repository by commit bfddfe5622b2cc7cf874f9c0e303aed8b7dbae00.

2022-08-01 16:29 UTC, closed without merging