fix(common): allow null/undefined to be passed to ngClass input (#39280)
angular/angular pull request #46906
Opened 2022-07-20 16:08 UTC by imirkin

With strict template type checking, a null/undefined value will raise an
error. However the implementation is completely fine with it, and it
would be pointless to "fix" it at the callsite and convert to e.g. an
empty string. Allow all of the "supported types" to be passed in
directly to ngClass.

Fixes #39280

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Issue Number: #39280

Currently bindings to `[ngClass]` that may return null or undefined are rejected by typescript as a result of enabling `strictTemplates` (e.g. `map.get('foo')` or anything else whose type includes undefined)

## What is the new behavior?

undefined/null are allowed by the `@Input` type and thus `strictTemplate`-enabled builds

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

Wasn't sure how to add a test for this specifically, since one has to enable strictTemplates for the source issue to occur. Suggestions welcome.

2022-07-20 17:55 UTC, imirkin commented
Looks like the google3 presubmit check is failing, but I don't have access to the details (having left G ~14y ago...). Happy to fix whatever's needed if I could get some details on what's failing.

Also, not 100% sure how this will look in the public docs (i.e. https://angular.io/api/common/NgClass), so let me know if I should flip it back to the explicit types and just add `|null|undefined` to the end.

2022-07-21 09:10 UTC, pkozlowski-opensource requested changes
The proposed change would expose `NgClassSupportedTypes` to the public API surface. `NgClassSupportedTypes` is not part of the public API currently and we really don't want to expose it since it would enlarge the public API.

Could you add `null` / `undefined` to the `ngClass` setter instead?

2022-07-21 20:54 UTC, imirkin commented
> The proposed change would expose `NgClassSupportedTypes` to the public API surface. `NgClassSupportedTypes` is not part of the public API currently and we really don't want to expose it since it would enlarge the public API.
> 
> Could you add `null` / `undefined` to the `ngClass` setter instead?

Sure thing. Done.

2022-07-22 02:07 UTC, AndrewKushnir commented
Just a quick comment: I think it'd be also great to add some tests into the `packages/common/test/directives/ng_class_spec.ts` file to check for `undefined` case (there are some existing tests there for `null` already).

2022-07-22 02:36 UTC, imirkin commented
> Just a quick comment: I think it'd be also great to add some tests into the `packages/common/test/directives/ng_class_spec.ts` file to check for `undefined` case (there are some existing tests there for `null` already).

Just like copy the null ones, and s/null/undefined, or something more creative?

2022-07-22 04:13 UTC, AndrewKushnir commented
@imirkin it should be sufficient to copy the `null`-based test cases and use `undefined` instead.

2022-07-22 14:55 UTC, imirkin commented
> @imirkin it should be sufficient to copy the `null`-based test cases and use `undefined` instead.

Done.

2022-07-22 16:54 UTC, AndrewKushnir commented
@imirkin thanks for adding a test. I think it'd be great to have a similar set of tests for `null` and `undefined` (i.e. cover the cases that you've mentioned), just to make sure all code paths are covered (and there are no places like `=== null` that would work for `null` only). As an option, you can just extend existing tests to add one more check there (so both `null` and `undefined` cases are co-located).

2022-07-22 17:00 UTC, imirkin commented
@AndrewKushnir how's this update?

2022-07-22 17:08 UTC, AndrewKushnir commented
@imirkin the change looks good, thanks for adding extra tests 👍 

I've been looking at the `NgStyle` as well and found out that there is only `null` there in the input type, but there is no `undefined`:
https://github.com/angular/angular/blob/main/packages/common/src/directives/ng_style.ts#L59

I'm wondering if we should just add `null` as a type to the `NgClass` for now (in this PR) to achieve consistency with `NgStyle` and investigate the `undefined` case a bit more to see if this is used in other FW APIs in the same way.

@pkozlowski-opensource WDYT?

2022-07-22 17:21 UTC, imirkin commented
@AndrewKushnir Well, what I really need is "undefined". I don't need null. I was just adding it in because it was (a) already being used and (b) seemed like the right thing.

I can add another commit here adding undefined to NgStyle if you like.

2022-07-23 07:22 UTC, pkozlowski-opensource commented
@AndrewKushnir @imirkin IMO we can handle `NgStyle` in a separate PR, no need to delay / making this one bigger.

2022-07-26 17:25 UTC, imirkin commented
@AndrewKushnir @pkozlowski-opensource so this is all good? or more work to be done? Let me know either way, happy to make additional changes, but I really do want the "undefined" bit of it...

2022-08-01 17:57 UTC, pkozlowski-opensource approved these changes
LGTM

Reviewed-for: public-api 
Reviewed-for: fw-core

2022-08-01 17:58 UTC, pkozlowski-opensource approved these changes
LGTM

Reviewed-for: public-api 
Reviewed-for: fw-common

2022-08-01 18:02 UTC, atscott approved these changes
reviewed-for: public-api

2022-08-01 18:46 UTC, jessicajaniuk approved these changes
reviewed-for: fw-common, public-api

2022-08-01 19:55 UTC, AndrewKushnir commented
This PR was merged into the repository by commit e2ab99b95efd893c49d15c02cccd72ef82ea1cae.

2022-08-01 19:55 UTC, closed without merging

2022-08-01 19:58 UTC, AndrewKushnir commented
@imirkin thanks for improving typings 👍 If you get a chance to add `undefined` to the `ngStyle` (in a separate PR) for symmetry - that'd be great.