fix(core): only set input on specific instance in ComponentRef.setInput
angular/angular pull request #46997
Opened 2022-07-31 10:58 UTC by crisbeto

`ComponentRef.setInput` works by calling `setInputsForProperty` internally. It can be problematic, because it will set the all inputs on the specific node matching the passed-in name, including other directives that aren't associated with the `ComponentRef`. Currently this isn't a problem, because the only way to get a `ComponentRef` is as a result of `ComponentFactory.create` and there is no way to apply other directives through there, however I see a couple of ways that it can manifest itself in the future:
1. Once the runtime for host directives is implemented (after #46868), users will be able to apply directives to the root component.
2. If we were to make it possible to inject `ComponentRef` in the future.

These changes add some extra logic so that the input is only assigned to the component instance that is associated with the `ComponentRef`.

2022-07-31 12:16 UTC, crisbeto commented on packages/core/src/render3/component_ref.ts
> +          break;
This `break` may be problematic if we somehow end up with multiple inputs on the same instance with the same name. Not sure if that's actually possible, but I'm open to removing it.

2022-07-31 12:16 UTC, crisbeto commented on packages/core/src/render3/component_ref.ts
> +        if (this._rootLView[index] === this.instance) {
Figuring out which inputs belong to this instance like this felt a little weird, but the only alternative would be to look at the index and I couldn't find a good way of getting the index of the component instance within the root `LView`.

2022-07-31 12:16 UTC, crisbeto commented on packages/core/src/render3/component_ref.ts
> +function createRootComponent<T>(
Unrelated change to the rest of the fix, I just saw that this function is only used within the file.

2022-07-31 12:16 UTC, crisbeto commented on packages/core/src/render3/instructions/shared.ts
> +  for (let i = 0; i < inputs.length; i += 2) {
This change is also unrelated to the fix, but I think that it's more readable like this compared to incrementing `i` from within the loop. I'm fine with reverting it as well.

2022-08-01 17:26 UTC, pkozlowski-opensource commented on packages/core/src/render3/component_ref.ts
> +function createRootComponent<T>(
nit: could we move those refactor changes to a separate (refactor) commit?

2022-08-01 17:26 UTC, pkozlowski-opensource commented on packages/core/src/render3/instructions/shared.ts
> +  for (let i = 0; i < inputs.length; i += 2) {
nit: could we move those refactor changes to a separate (refactor) commit?

2022-08-01 17:47 UTC, pkozlowski-opensource requested changes
@crisbeto there are few things here:

* the current behaviour of the `setInput` assumes that it behaves as a regular binding in a template and this is intentional. IMO we we should define the semantics of the bindings in a template to inputs for components with host directives first and use the same behaviour; in this sense I would rather do the runtime part of host directives first, iron out the semantics and modify the ComponentRef bit then - if needed;

* the assumptions in this PR is that, when binding to a component's inputs, its host directives shouldn't get the binding. This would be different from how the runtime behaves today for directives composed on the same host node. I was under the impression that host directives with exposed inputs should behave as a set of directives on the same node;

* currently there is no way of writing tests for this change;

I would much rather do the change in the runtime that accounts for the host directives and IMO the `setInput` should "just work". 

So my preference would be to do the `setInput` change _after_ the regular bindings are figured out.

2022-08-01 17:56 UTC, crisbeto commented
You're right that the intent with host directives is for them to work as if they were applied inside a template. I think that this case is different, because you have a reference pointing to a specific component class. As a user, I would find it odd if calling `setInput` would modify the input of a host directive I have no access to.

Small aside regarding tests: I have it on my list to add tests for this specific use case once I start working on the runtime implementation.

2022-08-01 18:05 UTC, pkozlowski-opensource commented
> You're right that the intent with host directives is for them to work as if they were applied inside a template. I think that this case is different, because you have a reference pointing to a specific component class. As a user, I would find it odd if calling setInput would modify the input of a host directive I have no access to.

@crisbeto I can see it as a different way of looking at the problem. Again, the initial assumption was that it _does_ behave as a regular input.  And it does make total sense to me in case of host directives. We can certainly review this assumption. Maybe an item on the fwk sync agenda?

2022-08-01 18:26 UTC, crisbeto commented
Sure, let's discuss it. I've added it to the agenda.

2022-09-20 07:45 UTC, closed without merging