Draft: Create APIs for using `Router` without `RouterModule`
angular/angular pull request #47010
Opened 2022-08-01 20:34 UTC by atscott

Creating draft PR so work can be picked up by someone else if needed 

See individual commits

TODOs:

* **Documentation**
* `RouterTestingModule` equivalent (i.e. `provideRouterForTesting`)
* Determine how to expose configuration used by [`assignExtraOptionsToRouter`](https://github.com/angular/angular/blob/2123317d025cbfe33e9c7ed398c6b0ebeccdcc73/packages/router/src/router.ts#L295-L323). The new API only uses a subset of the `ExtraOptions` so the whole `ExtraOptions` config is not a good fit anymore, at the very least.
* Additional tests

2022-08-02 23:19 UTC, atscott commented
Open question for reviewers: When updating the tests in the router package to use the new `provideRouterForTesting` API, I kept using `withXFeature` without putting it in an array. Should we use a rest parameter for the features or should we keep it as an array in the second argument?

2022-08-02 23:20 UTC, atscott commented on goldens/public-api/router/index.md
> +export function provideRouter(routes: Routes, features?: RouterFeatures[]): Provider[];
Copying from comment so we can discuss in a thread: Open question for reviewers: When updating the tests in the router package to use the new provideRouterForTesting API, I kept using `withXFeature` without putting it in an array. Should we use a rest parameter for the features or should we keep it as an array in the second argument?

2022-08-04 14:52 UTC, pkozlowski-opensource commented on goldens/public-api/router/index.md
> +export function provideRouter(routes: Routes, features?: RouterFeatures[]): Provider[];
+1 from me for the rest parameters - I don't see any specific reasons for _not_ using them and, as you've noted, there are mechanical advantages of skipping the `[]`

2022-08-08 15:26 UTC, pkozlowski-opensource commented on goldens/public-api/router/index.md
> +export function withInMemoryScrolling(options?: Pick<ExtraOptions, 'anchorScrolling' | 'scrollPositionRestoration'>): InMemoryScrollingFeature;
nit / open question: is the `InMemory` part of the `InMemoryScrollingFeature` important / relevant enough to highlight in the name? Do I care as the user that the implementation uses "in memory"?

2022-08-08 15:42 UTC, pkozlowski-opensource reviewed
Did another pass today, things looks really good so far! 

I've left a couple of comments around the public API surface - I guess I'm missing important bits of context but I would like to discuss and make sure that we are on the same page.

Other than this I can see that some public API docs and usage examples are missing, so leaving a comment review for now. Will do another pass after public API surface is clarified and the docs bits are done.

2022-08-08 15:42 UTC, pkozlowski-opensource commented on goldens/public-api/router/index.md
> +export function withEnabledBlockingInitialNavigation(): EnabledBlockingInitialNavigationFeature;
nit / open question: not sure, but maybe it is not unreasonable to ponder merging the `withDisabledInitialNavigation` and `withEnabledBlockingInitialNavigation` into one, centered around initial navigation? 

I know that the tree-shaking / modularity would suffer...

2022-08-08 15:42 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> + *
TODO: missing docs

2022-08-08 15:42 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> +export function provideRoutes(routes: Routes): Provider[] {
TBH I'm surprised to see `provideRoutes` in the public API surface. I guess I'm missing context / reasoning here and I would love to understand more.

2022-08-08 16:11 UTC, atscott commented on goldens/public-api/router/index.md
> +export function withInMemoryScrolling(options?: Pick<ExtraOptions, 'anchorScrolling' | 'scrollPositionRestoration'>): InMemoryScrollingFeature;
Yes, I want to make the distinction here between the existing scrolling, which stores scroll positions in memory, and a potential future where we have a different strategy which uses the [Navigation API](https://github.com/WICG/navigation-api) to handle the scroll restoration.

We could still omit the "inMemory" if you'd like. The new feature would still be specifically something like "withBrowserScrolling" or something like that. We'd just have a generic, non-descriptive "withScrolling" and a specific "withBrowserScrolling" in that world. Though we could also do a migration for the "withScrolling" at that time to make it more specific.

@AndrewKushnir @alxhub @tbondwilkinson

2022-08-08 16:13 UTC, atscott commented on goldens/public-api/router/index.md
> +export function withEnabledBlockingInitialNavigation(): EnabledBlockingInitialNavigationFeature;
I had this thought as well. I don't think we should merge the two into one provider with an option because of the loss of tree shaking (there's a non-trivial amount of code in the EnabledBlocking option). _But_, we could combine them into a single feature in the `RouterFeatures` like this:

```
export type RouterFeatures = DebugTracingFeature|InitialNavigationFeature|...

export type InitialNavigationFeature = EnabledBlockingInitialNavigationFeature|DisabledInitialNavigationFeature;
```
WDYT?

2022-08-08 16:14 UTC, atscott commented on packages/router/src/provide_router.ts
> +export function provideRoutes(routes: Routes): Provider[] {
This is already in the public API. Removing it would be a breaking change.

Also, `RouterModule.forChild` is essentially just `provideRoutes`. i.e. `provideRoutes` is a 1:1 replacement for `RouterModule.forChild`

2022-08-08 16:15 UTC, atscott commented on packages/router/src/provide_router.ts
> + *
Yea, there's a lot of TODO documentation still.

2022-08-08 16:48 UTC, pkozlowski-opensource commented on goldens/public-api/router/index.md
> +export function withInMemoryScrolling(options?: Pick<ExtraOptions, 'anchorScrolling' | 'scrollPositionRestoration'>): InMemoryScrollingFeature;
I see. I don't feel too strongly about it, let's see what are other opinions here.

2022-08-08 16:49 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> +export function provideRoutes(routes: Routes): Provider[] {
oh, I didn't realise it was part of the public API already...

2022-08-08 16:50 UTC, pkozlowski-opensource commented on goldens/public-api/router/index.md
> +export function withEnabledBlockingInitialNavigation(): EnabledBlockingInitialNavigationFeature;
sgtm

2022-08-08 18:56 UTC, AndrewKushnir reviewed
Just publishing some comments. I will probably take care of most of them myself.

2022-08-08 18:56 UTC, AndrewKushnir commented on packages/router/src/provide_router.ts
> +export function provideRoutes(routes: Routes): Provider[] {
(unresolving the conversation)
Note to myself: I can update an example to focus on `provideRoutes` (the current example looks confusing to me as well).

2022-08-08 18:56 UTC, AndrewKushnir commented on packages/router/src/provide_router.ts
> +export function withInMemoryScrolling(
Bike-shedding (not blocking): the "InMemory" part might look a bit too technical (refers to the implementation details) to API users. I understand the motivation to avoid too generic names (i.e. `withScrolling`) to leave room for other types of scrolling implementations, so I was wondering if we can find some middle ground and ask for the feedback from other public-api reviewers.

2022-08-08 18:56 UTC, AndrewKushnir commented on packages/router/src/router_module.ts
> +import {getBootstrapListener, provideRoutes, rootRoute, withDebugTracing, withDisabledInitialNavigation, withEnabledBlockingInitialNavigation, withPreloading} from './provide_router';
The `getBootstrapListener` might be unused here...

2022-08-08 18:56 UTC, AndrewKushnir commented on packages/router/src/provide_router.ts
> +export function getBootstrapListener() {
We can probably remove `export` here is this function is only used locally in this file.

2022-08-08 18:56 UTC, AndrewKushnir commented on packages/router/testing/src/router_testing_module.ts
> +  // TODO: Add a `provideRouterForTesting` equivalent
We can drop this TODO now (the `provideRouterForTesting` was introduced)?

2022-08-08 22:52 UTC, AndrewKushnir commented on packages/router/src/provide_router.ts
> +export function withInMemoryScrolling(
Closing in favor of the discussion above.

2022-08-08 23:00 UTC, mary-poppins commented
You can preview fc15d93 at https://pr47010-fc15d93.ngbuilds.io/.
You can preview ab4fcbc at https://pr47010-ab4fcbc.ngbuilds.io/.
You can preview 5a8e486 at https://pr47010-5a8e486.ngbuilds.io/.
You can preview f85589d at https://pr47010-f85589d.ngbuilds.io/.
You can preview 30b165f at https://pr47010-30b165f.ngbuilds.io/.
You can preview 3ea0fc3 at https://pr47010-3ea0fc3.ngbuilds.io/.
You can preview 80fbf37 at https://pr47010-80fbf37.ngbuilds.io/.
You can preview c3da7e1 at https://pr47010-c3da7e1.ngbuilds.io/.
You can preview b485db9 at https://pr47010-b485db9.ngbuilds.io/.
You can preview a739550 at https://pr47010-a739550.ngbuilds.io/.

2022-08-08 23:06 UTC, mary-poppins commented
You can preview 954da58 at https://pr47010-954da58.ngbuilds.io/.

2022-08-08 23:44 UTC, mary-poppins commented
You can preview de9be67 at https://pr47010-de9be67.ngbuilds.io/.

2022-08-09 00:01 UTC, mary-poppins commented
You can preview 0d9e4cc at https://pr47010-0d9e4cc.ngbuilds.io/.

2022-08-09 00:17 UTC, mary-poppins commented
You can preview 7b05799 at https://pr47010-7b05799.ngbuilds.io/.

2022-08-09 13:26 UTC, pkozlowski-opensource approved these changes
LGTM

The public API surface looks great! I've left lots of nit comments about the documentation bits but I don't consider them blocking and we can follow up in a separate PR. 

Reviewed-for: public-api

2022-08-09 13:26 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> + * Extra logging might be useful for debugging.
nit: this sentence sounds "incomplete". How about "useful for debugging router-related issues"? Or even something more precise, specifying what type of debugging we are talking about.

2022-08-09 13:26 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> + * Extra logging might be useful for debugging.
Also, I would _love_ to see usage examples for those APIs - even if it is simple function call it is very handy to have it as a copy & paste example. And the for the people new to the API it is easier to see things in context.

2022-08-09 13:26 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> + *
nit: I would _love_ to see usage examples for those APIs - even if it is simple function call it is very handy to have it as a copy & paste example. And the for the people new to the API it is easier to see things in context.

2022-08-09 13:26 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> + * reference to a class that implements a `PreloadingStrategy`.
nit: "providing a reference" might be confusing here as it is not clear if we are talking about passing a type as an argument to the `withPreloading` or if DI is involved somehow. 

Maybe we don't need to alter the text if there is usage example.

2022-08-09 13:26 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> + *
Also, would love to see an example where `PreloadingStrategy` has dependencies retrieved from DI

2022-08-09 13:26 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> +    EnabledBlockingInitialNavigationFeature|DisabledInitialNavigationFeature;
Looking at the [angular.io preview](https://pr47010-7b05799.ngbuilds.io/api/router/RouterFeatures) for some reason the `InitialNavigationFeature` link is not clickable. This is a bummer since it makes `EnabledBlockingInitialNavigationFeature|DisabledInitialNavigationFeature` harder to discover.

This type also doesn't show up in the angular.io search.

I'm not sure what is going on here...

2022-08-09 13:26 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> + * @see `ExtraOptions#initialNavigation`
nit: not sure if we should link to the `ExtraOptions` here are we are not meant to use it with the new APIs. I would rather drop it.

2022-08-09 13:26 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> + * @see `ExtraOptions#initialNavigation`
Also, I still believe that we should have the usage example here.

2022-08-09 13:26 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> + * [server-side rendering](guide/universal) to work.
Could we provide usage example here so people understand how the server-side configuration should look like?

2022-08-09 13:26 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> + *
nit: add usage example.

2022-08-09 13:26 UTC, pkozlowski-opensource commented on packages/router/src/provide_router.ts
> +                                 'paramsInheritanceStrategy'|'urlUpdateStrategy'>):
thinking out loud: when we see the angular.io preview (https://pr47010-7b05799.ngbuilds.io/api/router/withRouterConfig) the signature doesn't look "pretty". Not sure if it would make sense to introduce type alias for the options argument?

2022-08-09 13:37 UTC, brandonroberts commented
Really like that this makes the router features more tree-shakeable! Few questions:

- Is it possible to have an object-based config to enable features and provide the same tree-shaking? This makes configuring the router much more verbose if you enable all the features.
- What will the default be for a new application that uses this API? Are all the features included in the array, and you must delete them?
- Will there be something to prevent using these provider features outside of the `provideRouter` function?
- What about `provideMockRouter` or `provideTestRouter` instead of `providerRouterForTesting`

Thanks in advance!

2022-08-09 15:23 UTC, atscott commented
@brandonroberts Thanks for the feedback!

> Is it possible to have an object-based config to enable features and provide the same tree-shaking? This makes configuring the router much more verbose if you enable all the features.

Yes, but the object-based configuration would actually be even more verbose. For example:
```
type RouterTracingFeature = Provider[];
function provideTracing(): RouterTracingFeature { … }

// Group all features in one interface:
type RouterFeatures = {
  tracing?: RouterTracingFeature,
  preloading?: RouterPreloadingFeature,
  …
};

// Usage
provideRouter([], {tracing: withTracing()});
```

The issue is that we can't have an `if`/`else` in the runtime code based on a runtime value. That makes both branches non-tree shakeable. The only way to do that in a way that would be tree shakeable would be to have compiler constants like `ngDevMode`.

Lastly, I think the verbosity actually isn't that much of an issue:
`enableTracing: true`
`withDebugTracing()` 
`initialNavigation: 'disabled'`
`withDisabledInitialNavigation()`

Scrolling does require `withInMemoryScrolling` as a prefix for its options. But this change is worthwhile in my opinion because it namespaces the options to related the feature area rather than having a bunch of unrelated options live in one massive config object.
The options in `withRouterConfig` aren't tree shakeable and don't really fall into a feature bucket. So those also require a slightly more verbose `withRouterConfig` as a prefix.

All that said, this config is only done once per application rather than being typed a bunch of times in various places. Additionally, I haven't found that it's super common to provide these options either, especially in simple apps. 

> What will the default be for a new application that uses this API? Are all the features included in the array, and you must delete them?

None of the features that have been split out are provided by default today in new applications. The only exception is the `RouterScroller`. But that only includes the event; you still have to opt-in to the scrolling behavior.
So to answer the question directly, my feeling is that new applications would not have any of them. We could definitely consider adding some by default.

> Will there be something to prevent using these provider features outside of the provideRouter function?

We certainly could consider this and do something like the trick for `importProvidersFrom`. 

> What about provideMockRouter or provideTestRouter instead of providerRouterForTesting

Happy to continue bikeshedding some options. You'll notice that the _only_ distinguishing factor for the test router is the locations strategy used. I'll throw another option in there: `provideRouter([], withTestingLocationStrategy())` (or another feature function with a similar name). This way, tests would look _exactly_ the same as a regular application.

2022-08-09 16:10 UTC, atscott commented on goldens/public-api/router/testing/index.md
> +export function provideRouterForTesting(routes?: Routes, ...features: RouterFeatures[]): Provider[];
From @brandonroberts 
What about `provideMockRouter` or `provideTestRouter` instead of `providerRouterForTesting`

Additional proposal from me: 
We actually don't need a special `provideRouter` at all. The function only registers two additional location providers `SpyLocation` and `MockLocationStrategy`. These providers could be their own feature, so it could be `provideRouter([], withMockLocation())`.

Arguably, the location strategies are the responsibility of the Router itself. The two providers could be their own thing altogether: `TestBed.configureTestingModule({providers: [provideRouter([]), provideMockLocation()]});`

@pkozlowski-opensource @alxhub @AndrewKushnir

2022-08-09 16:45 UTC, alfaproject commented on goldens/public-api/router/testing/index.md
> +export function provideRouterForTesting(routes?: Routes, ...features: RouterFeatures[]): Provider[];
I suppose that people could write their own `provideTestRouter` function which is tailor made for their apps. I'd be totally fine with that as an advanced user but not sure if you want to provide some convenience method that setups something that works for the 90 percentile, still?

2022-08-09 16:57 UTC, jessicajaniuk approved these changes
I don't have much to say other than I really like these APIs. Well done! 👏🏻 

reviewed-for: public-api, fw-core, size-tracking, integration-tests, fw-testing

2022-08-09 17:39 UTC, brandonroberts commented on goldens/public-api/router/testing/index.md
> +export function provideRouterForTesting(routes?: Routes, ...features: RouterFeatures[]): Provider[];
@atscott I'm torn! I like the concept, but it still goes back to being one thing that did both and now I have to remember to add the router provider and the mock location provider. I don't know how many developers actually know that's what happens today with the RouterTestingModule

2022-08-09 17:51 UTC, brandonroberts commented
@atscott 

I was thinking something more like

```ts
import { provideRouter } from '@angular/router';

  provideRouter([], {
    enabletTracing: true,
    preloading: true
  })
```

vs

```ts
import { provideRouter, withDebugTracing, withPreloading } from '@angular/router';

  provideRouter([], [
    withDebugTracing(),
    withPreloading()
  ])
```

Additional imports are needed also, but if it can't be tree-shaken out by the compiler, I get it.

2022-08-09 17:51 UTC, atscott commented on goldens/public-api/router/testing/index.md
> +export function provideRouterForTesting(routes?: Routes, ...features: RouterFeatures[]): Provider[];
@brandonroberts Developers already had to be trained to use `RouterTestingModule` in tests. Regardless of what the new API is, people will have to learn a new thing to use for tests. The reason I kind of like the idea of using `provideRouter` and either `withMockLocation()` or a separate `provideMockLocation` is that it's more transparent about _what's_ being modified. Currently, `RouterTestingModule` is a black box that seems like it could be doing any number of things to enable testing behavior. But in reality, it's extremely simple. 

One other point that might be worth considering is that with something like `provideRouterForTesting` instead, we have more flexibility in that we can add more test-specific things in the future. What about `provideRouter([], withTestingProviders())` which reads quite nicely as "provide router with testing providers".

2022-08-09 18:09 UTC, AndrewKushnir commented on goldens/public-api/router/testing/index.md
> +export function provideRouterForTesting(routes?: Routes, ...features: RouterFeatures[]): Provider[];
My personal preference in terms of API names is:
1. provideRouterForTesting
2. provideMockRouter
3. provideTestRouter

I like the current name (`providerRouterForTesting`), since it mimics the `provideRouter` function name (just adds a suffix) and clearly describes the intention. Regarding `Mock` or `Test` added to the name: as you pointed out, we are not changing/mocking the Router, we are adding mocks for other services, so it feels like the 2nd and 3rd name from the list might be a bit misleading.

> We actually don't need a special provideRouter at all. The function only registers two additional location providers SpyLocation and MockLocationStrategy. These providers could be their own feature, so it could be provideRouter([], withMockLocation()).

I think it'd still be great to have a special function that sets up everything for testing. It should cover most of the cases and can be used for automated migrations in the future. For complex scenarios, we can expose more granular functions for use with `provideRouter` (like `withMockLocation`) is there is an interest from the community.

2022-08-09 18:24 UTC, atscott commented on goldens/public-api/router/testing/index.md
> +export function provideRouterForTesting(routes?: Routes, ...features: RouterFeatures[]): Provider[];
@AndrewKushnir I want to make sure we're not making the mistake of creating `provideRouterForTesting` simply because there's an existing `RouterTestingModule`. I'm currently feeling that this might be carrying over implementation details of the module-based world where `NgModule`s encapsulate all the behaviors you want for any context. The migration of `RouterTestingModule.withRoutes(routes)` => `provideRouter(routes, withTestingProviders())` still makes sense. I don't know that a separate provider is _required_ to give a natural feeling for a migration from the old API to the new one.

2022-08-09 18:47 UTC, AndrewKushnir commented on goldens/public-api/router/testing/index.md
> +export function provideRouterForTesting(routes?: Routes, ...features: RouterFeatures[]): Provider[];
@atscott I see your point. A couple additional thoughts on having a special function:
- it'd be easier to explain in docs/tutorials what you should do to setup your testing environment (you don't have to learn about "features" unless you want to use one of them for testing, so the setup and the learning journey might be more gradual)
- having a special function would allow us to keep some implementation details inside and retain the flexibility to include more mocks by default in the future (in case we need to introduce an abstraction, which would also require a mock for testing).
- this conversation reminded me of [the HTTPClient changes](https://github.com/angular/angular/pull/46682/files#diff-a384e18e5a34388dfc8a4473593e749d29f4bfbce97c98a3867d9cb508574fc2). I think it'd be great to examine both cases from the API consistency perspective (including naming) and see if there is a common pattern that we can work out and use for other packages that would need this.

2022-08-09 22:33 UTC, AndrewKushnir commented on packages/router/src/provide_router.ts
> + *
I didn't find a canonical example in our docs to illustrate the `PreloadingStrategy` implementation. I've added an example on how to use `withPreloading` with `PreloadAllModules`, which would likely be useful as well. We can come back to this and add a custom strategy example as a followup.

2022-08-09 22:34 UTC, AndrewKushnir commented on packages/router/src/provide_router.ts
> +    EnabledBlockingInitialNavigationFeature|DisabledInitialNavigationFeature;
Great catch! I've exported this type via the `packages/src/router/index.ts`, it should show up now.

2022-08-09 23:42 UTC, mary-poppins commented
You can preview 7db44bd at https://pr47010-7db44bd.ngbuilds.io/.

2022-08-09 23:52 UTC, AndrewKushnir commented on packages/router/src/provide_router.ts
> +                                 'paramsInheritanceStrategy'|'urlUpdateStrategy'>):
Good point, I've made a couple updates in a [separate fixup commit](https://github.com/angular/angular/pull/47010/commits/7db44bd84630bafa81c9940ae97e7b740bb17684):
- removed references to the `ExtraOptions` interface from the new functions
- extracted 2 interfaces from the `ExtraOptions` interface: one for `withInMemoryScrolling` function argument and the second one - for the `withRouterConfig ` function.

This helped improve the docs ([for example here](https://pr47010-7db44bd.ngbuilds.io/api/router/withInMemoryScrolling)) and avoid the duplication.

@atscott @pkozlowski-opensource WDYT?

2022-08-10 00:04 UTC, atscott commented on packages/router/src/provide_router.ts
> +                                 'paramsInheritanceStrategy'|'urlUpdateStrategy'>):
LGTM

2022-08-10 16:33 UTC, atscott commented on goldens/public-api/router/testing/index.md
> +export function provideRouterForTesting(routes?: Routes, ...features: RouterFeatures[]): Provider[];
I have one more comment here that I don't want to forget:

We will be more or less boxing ourselves into a corner with _how_ the current router implementation interacts with and tests the browser state. Currently, this is being done via Location and pushState/replaceState/go along with the `SpyLocation` and `MockLocationStrategy` which mock those methods. 
If we're looking at a future where we integrate with the [Navigation API](https://github.com/WICG/navigation-api), the way we test navigations might look pretty different. `provideRouterForTesting` might need to be completely different. Maybe we just punt that decision because we have no idea what that integration might look like.

2022-08-10 17:14 UTC, AndrewKushnir commented on goldens/public-api/router/testing/index.md
> +export function provideRouterForTesting(routes?: Routes, ...features: RouterFeatures[]): Provider[];
Discussed offline: this topic would require additional design work. We plan to exclude the `provideRouterForTesting` function from the public API for now, so we can land other APIs and come back to the testing APIs in the future (may be in conjunction with other testing functions for other packages).

2022-08-10 17:21 UTC, AndrewKushnir commented on goldens/public-api/router/testing/index.md
> +export function provideRouterForTesting(routes?: Routes, ...features: RouterFeatures[]): Provider[];
FYI, the function is removed from the public API via https://github.com/angular/angular/pull/47010/commits/f8ab94e04cb576eda7044341955f628ec5e572a5.

2022-08-10 17:29 UTC, mary-poppins commented
You can preview f8ab94e at https://pr47010-f8ab94e.ngbuilds.io/.

2022-08-11 22:10 UTC, alxhub requested changes

2022-08-11 22:10 UTC, alxhub commented on goldens/public-api/router/index.md
> +export type DebugTracingFeature = Provider[];
We should give these features a nominal type of their own, so that they can't be dropped directly into a `Provider[]` array. Maybe like:

```typescript
export enum RouterFeatureKind {
  DebugTracing,
  DisabledInitialNavigationFeature,
  EnabledBlockingInitialNavigationFeature,
  ...
}
```

Then each feature can become something like:
```suggestion
export type DebugTracingFeature = {ɵkind: RouterFeatureKind.DebugTracing};
```

The `providers` can be stored on the object and accessed via a cast to an internal interface.

We can either leave off the `ɵkind` property, or add it and use it to check that features aren't provided more than once.

2022-08-12 00:06 UTC, AndrewKushnir commented on goldens/public-api/router/index.md
> +export type DebugTracingFeature = Provider[];
Thanks for the feedback Alex! I've added a fixup commit with the changes: https://github.com/angular/angular/pull/47010/commits/1694a27e978753909273cbdc8e65e3e69f8e7547. Please let me know what you think.

2022-08-12 00:18 UTC, mary-poppins commented
You can preview a0b4a6b at https://pr47010-a0b4a6b.ngbuilds.io/.

2022-08-12 15:02 UTC, markostanimirovic commented on packages/router/src/provide_router.ts
> +export function provideRouter(routes: Routes, ...features: RouterFeatures[]): Provider[] {
Btw, what do you think about renaming `ImportedNgModuleProviders` type to `EnvironmentProviders` or something similar, and using it as a return type of the `provideRouter` function too?

This can be useful to show a compilation error when `provideRouter` is used in the wrong place, e.g. in the `Component/Directive.providers` array:

```ts
@Component({
  providers: [provideRouter(appRoute)], // compilation error
})
export class AppComponent {}
```

The `EnvironmentProviders` type can be further used for all "provide" functions that cannot be used in components or directive providers.

cc @atscott @AndrewKushnir

2022-08-12 21:26 UTC, alxhub approved these changes
Reviewed-for: public-api

2022-08-12 21:26 UTC, alxhub commented on packages/router/src/provide_router.ts
> +interface RouterFeature<FeatureKind> {
```suggestion
export interface RouterFeature<FeatureKind extends RouterFeatureKind> {
```

This needs to be exported as its a part of other exported types.

2022-08-12 21:44 UTC, alxhub approved these changes
(can't approve enough)

2022-08-12 21:50 UTC, mary-poppins commented
You can preview df29701 at https://pr47010-df29701.ngbuilds.io/.

2022-08-12 22:19 UTC, mary-poppins commented
You can preview 87b1b3e at https://pr47010-87b1b3e.ngbuilds.io/.

2022-08-13 02:07 UTC, AndrewKushnir commented
[Presubmit](https://test.corp.google.com/OCL:467340353:BASE:467340405:1660356426916:6af8690b) (TGP).

2022-08-13 05:32 UTC, AndrewKushnir commented
FYI, TGP is "green", the PR is now ready for merge 🎉

2022-08-15 22:58 UTC, alxhub commented
This PR was merged into the repository by commit 75df4044675c61d2b646437cfe64fe828a39b3a0.

2022-08-15 22:58 UTC, closed without merging