refactor (forms): using more utility functions and optimizing is-true condition statements
angular/angular pull request #47210
Opened 2022-08-22 05:09 UTC by vyom1611

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-08-22 20:18 UTC, dylhunn requested changes

2022-08-22 20:18 UTC, dylhunn commented on packages/forms/src/validators.ts
> +  return (control.value) ? null : {'required': true};
I don't think this is right. What if `control.value` is `null`?

2022-08-22 20:18 UTC, dylhunn commented on packages/forms/src/validators.ts
> +  if (!hasValidLength(presentValidators)) return null;
This appears to be an entirely different check:

```
return value != null && typeof value.length === 'number';
```

Is this a safe substitution? It doesn't seem so to me.

2022-08-22 20:20 UTC, dylhunn commented
P.S. I think as a matter of code style, we generally prefer to keep explicit checks rather than relying on implicit comparisons and coercion.

2022-08-22 20:45 UTC, vyom1611 commented
Why does the validLength function not work on line 633, the original condition was checking for length to be 0, which would be falsy

2022-08-29 18:28 UTC, AndrewKushnir commented
Closing this PR, since it changes the code to rely on implicit comparisons and coercion, which we generally try to avoid.

2022-08-29 18:28 UTC, closed without merging