docs: fixing typos and grammatical errors in several documentation files
angular/angular pull request #47254
Opened 2022-08-25 14:56 UTC by vyom1611

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Fixed documentation erroes

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-08-29 18:29 UTC, josephperrott commented
Adding @bob-watson to review for grammar

2022-08-29 18:33 UTC, bob-watson commented on docs/BAZEL.md
> +will be installed through NPM, and therefore it's not necessary to install Bazel
suggested edit: `will be installed through NPM. It's not necessary to install Bazel`

2022-08-29 18:35 UTC, bob-watson commented on docs/BAZEL.md
> +Currently, we only use remote caching on CircleCI, and we let Angular core developers enable remote caching to speed up their builds.
Suggested edit: Currently, we only use remote caching on CircleCI. We let Angular core developers enable remote caching to speed up their builds.

2022-08-29 18:36 UTC, bob-watson commented on docs/DEVELOPER.md
> +automatically publishes build artifacts to repositories in the Angular org, e.g. the `@angular/core`
suggestion: replace `e.g.` with `for example,`

2022-08-29 18:41 UTC, bob-watson requested changes
Thanks for cleaning this up.
Most of these edits look good.
I left minor comments on a couple of them that should be reviewed before this is merged.

2022-08-29 22:28 UTC, vyom1611 commented
Changes added to this branch

2022-08-30 01:47 UTC, bob-watson requested changes
I don't see any changes or comments made for the change requests that are marked as resolved. Please make the requested edits so I can approve this.

2022-08-30 03:24 UTC, vyom1611 commented
Hey,
Anywhere I check, this branch has the updated code, and am unable to push any commits because it already has the changes. Where can you spot the original unchanged code?

2022-08-30 14:16 UTC, bob-watson commented
@vyom1611 , it doesn't look like you've pushed any revisions to the documentation topics up to github since Aug. 25, at least that's how I read the table at the top of https://github.com/angular/angular/pull/47254/commits.

2022-08-30 16:23 UTC, gkalpak requested changes
I confirm I also see what @bob-watson sees. The requested changes are not applied (and the PR includes unrelated changes).

@vyom1611, if you look at the [Commits][1] tab, you can see there are several commits (some of them "merge" commits or unrelated to this PR). Normally, there should be one commit that contains the relevant changes.

You can also check out [Submitting a Pull Request][2] and [Addressing review feedback][3] for more details on the suggested process. Let me know if you need any help with getting this PR into shape.

[1]: https://github.com/angular/angular/pull/47254/commits
[2]: https://github.com/angular/angular/blob/7d3df4724d2baf087453d317ab6ab893d4a7b85f/CONTRIBUTING.md#-submitting-a-pull-request-pr
[3]: https://github.com/angular/angular/blob/7d3df4724d2baf087453d317ab6ab893d4a7b85f/CONTRIBUTING.md#addressing-review-feedback

2022-08-30 16:23 UTC, gkalpak commented on docs/GITHUB_PROCESS.md
> +management process. After we triage an issue, and we identify it as a feature request, it goes
I don't think the comma is needed here.

2022-08-30 16:23 UTC, gkalpak commented on docs/BAZEL.md
> +- If you're debugging a test, and you want to inspect the generated template instructions, find the template of your component in the call stack and click on `(source mapped from [CompName].js)` at t
I don't think the comma is needed here.

2022-08-30 16:34 UTC, vyom1611 commented
Hey @bob-watson @gkalpak , sorry for all the confusion. I have added both the review changes in new commits. Should be resolved.

2022-08-30 18:26 UTC, gkalpak approved these changes
Thank you for making the changes, @vyom1611 :heart:

BTW, I have fixed the commits for you (removing the "merge" commits and the unrelated commits). This should be good to go now 🚀

Thank you again for working on this.
(For future PRs, you might want to go through the [submission guidelines][1] to avoid issues :smiley:)

[1]: https://github.com/angular/angular/blob/9a623c03b27e35f23d4834188880a9d669020e30/CONTRIBUTING.md#-submission-guidelines

2022-08-30 18:29 UTC, bob-watson approved these changes
LGTM
Thanks for the fixes!

2022-09-06 16:14 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 0d13cc78485b0631a744024bcbb01a94b274d335.

2022-09-06 16:14 UTC, closed without merging