docs: fix minor typos in various documentations
angular/angular pull request #47290
Opened 2022-08-29 20:30 UTC by marcwrobel

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-08-29 21:22 UTC, bob-watson commented on docs/BAZEL.md
> +In the upper right corner that is a small table of contents with links to three areas: Tasks, Legend and Statistics.
Our style guide prefers the use of the Oxford comma in lists for clarity.
Suggest: `Tasks, Legend, and Statistics.` at the end of the sentence.

2022-08-29 21:24 UTC, bob-watson commented on docs/DEVELOPER.md
> +automatically publishes build artifacts to repositories in the Angular org, e.g. the `@angular/core`
`e.g.` should be `for example`

2022-08-29 21:26 UTC, bob-watson commented on docs/PUBLIC_API.md
> +One intentional omission from this list is `@angular/compiler`, which is currently considered a low level api and is subject to internal changes. These changes will not affect any applications or lib
`api` should be capitalized throughout. If you need to refer to more than one, you can use: `APIs`.

2022-08-29 21:30 UTC, bob-watson requested changes
Thanks for the edits!
This looks good with only a few minor changes to make.

2022-08-30 08:19 UTC, marcwrobel commented on docs/BAZEL.md
> +In the upper right corner that is a small table of contents with links to three areas: Tasks, Legend and Statistics.
Done.

2022-08-30 08:19 UTC, marcwrobel commented on docs/DEVELOPER.md
> +automatically publishes build artifacts to repositories in the Angular org, e.g. the `@angular/core`
Done.

2022-08-30 08:19 UTC, marcwrobel commented on docs/PUBLIC_API.md
> +One intentional omission from this list is `@angular/compiler`, which is currently considered a low level api and is subject to internal changes. These changes will not affect any applications or lib
Done.

2022-08-30 09:01 UTC, devversion approved these changes

2022-08-30 14:20 UTC, bob-watson commented on docs/DEVELOPER.md
> +automatically publishes build artifacts to repositories in the Angular org, for example the
It just needs a comma after *for example*, then it LGTM.

2022-08-30 14:24 UTC, bob-watson requested changes
one more comma and it LGTM

2022-08-30 14:51 UTC, marcwrobel commented on docs/DEVELOPER.md
> +automatically publishes build artifacts to repositories in the Angular org, for example the
I also split the sentence in two : `in the Angular org. For example, the`. I think it's easier to read that way. Do you think it is OK ?

2022-08-30 15:14 UTC, bob-watson approved these changes
LGTM!

2022-08-30 16:42 UTC, AndrewKushnir approved these changes

2022-09-06 16:28 UTC, AndrewKushnir commented
@marcwrobel it looks like this PR has a conflict after merging some other PRs. Could you please rebase and resolve conflicts when you get a chance? Thank you.

2022-09-07 08:02 UTC, marcwrobel commented
@AndrewKushnir, conflicts resolved.

2022-09-07 17:41 UTC, AndrewKushnir commented
@marcwrobel thanks for resolving conflicts! I'm adding this PR to the merge queue.

2022-09-07 17:48 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 25c4e4cd5d8314f393837faf3f0c27d1496eb38a.

2022-09-07 17:48 UTC, closed without merging