feat(devtools): implement inspect functionality for directives
angular/angular pull request #47334
Opened 2022-09-02 19:29 UTC by sbrshkappa

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
Devtools Feature

## What is the current behavior?
Previously, you could inspect the source code of a component but not a directive.

Issue Number: 45882

## What is the new behavior?
 This commit adds functionality to inspect source code for directives as well. Now you will see the inspect icon on the header component of each directive on a selected element.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-09-07 21:36 UTC, AleksanderBodurri requested changes
It was nice meeting you at NG Conf 😄 Thanks for the PR. I left a couple of comments to be resolved but overall this looks good to me

2022-09-07 21:36 UTC, AleksanderBodurri commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/directive-explorer/directive-explorer.component.ts
> +      this._appOperations.viewSource(this.currentSelectedElement.position, directiveIndex);
Small nit

```suggestion
    if (directiveIndex ===  -1) {
      // view the component definition
      this._appOperations.viewSource(this.currentSelectedElement.position);
      return;
   }
    
    // view the directive definition
   this._appOperations.viewSource(this.currentSelectedElement.position, directiveIndex);
```

2022-09-07 21:36 UTC, AleksanderBodurri commented on devtools/projects/shell-browser/src/app/chrome-window-extensions.ts
> +        console.error(
Lets add an early return after this line so we never run the code underneath it

2022-09-07 22:47 UTC, sbrshkappa commented
> It was nice meeting you at NG Conf 😄 Thanks for the PR. I left a couple of comments to be resolved but overall this looks good to me

Absolutely! Great meeting you as well. Helps to work in person, to get things moving quickly.

2022-09-08 03:07 UTC, sbrshkappa commented on devtools/projects/shell-browser/src/app/chrome-window-extensions.ts
> +        console.error(
Added a return here. Is that what you meant?

2022-09-08 03:18 UTC, sbrshkappa commented
@AleksanderBodurri I have the changes merged, I did a combination of using the github "Apply changes" and committing the other changes from my local. Hopefully the branch looks good. Let me know.

2022-09-08 18:01 UTC, sbrshkappa commented
@AleksanderBodurri , I accidentally did some merge that messed up this branch, can you help with fixing this?

2022-09-11 21:45 UTC, AleksanderBodurri commented
Backup your branch just in case
```bash
git checkout -b view-source-directive-bkp
git checkout sk-view-source-directives
```

You can reset to a branch with only your commits by:
```bash
# reset softly to the commit right before 7f3180e and f86b36d
git reset --soft 0dc66120f053e610398cbdba61b6951ce77ee5b4
# stash the changes from 7f3180e and f86b36d
git stash
# reset hard to right before the merge 
git reset --hard 3cf56797ca
# pop stash to bring back the changes from 7f3180e and f86b36d
git stash pop
# make new commit with the changes from 7f3180e and f86b36d
git add .
git commit
# update remote branch
git push -f
```

2022-09-11 22:15 UTC, sbrshkappa commented
Thank you for the detail steps, @AleksanderBodurri. The branch should be back in the original state.

2022-09-11 22:38 UTC, AleksanderBodurri commented
Awesome 😄 The last thing I would suggest is that you squash your 3 commits into 1. You can do this anyway you're comfortable with, I'll leave a description of how I would do this below for reference.

Run the following in your terminal
```
git rebase -i main
```
and then change the `pick` next to [0597b8f](https://github.com/angular/angular/pull/47334/commits/0597b8f3daedf283f5562098322e7a955915f567) and [3cf5679](https://github.com/angular/angular/pull/47334/commits/3cf56797ca0ff1f71c88c98e5367ac642b912aa6) to `fixup` or `f`. Saving this file will cause the rebase to fixup these 2 commits onto [b161d6b](https://github.com/angular/angular/pull/47334/commits/b161d6bed527f79a4ff98abc9e6c953fe369b92f). Then update your remote branch with `git push -f`.

2022-09-12 00:24 UTC, sbrshkappa commented
@AleksanderBodurri . Done!

2022-09-13 03:53 UTC, AleksanderBodurri approved these changes
LGTM

2022-09-19 15:26 UTC, AleksanderBodurri approved these changes

2022-09-19 15:40 UTC, AleksanderBodurri approved these changes

2022-09-19 15:43 UTC, AleksanderBodurri approved these changes
Reviewed-for: devtools

2022-09-19 15:48 UTC, josephperrott approved these changes
LGTM

2022-09-19 16:59 UTC, pkozlowski-opensource commented
This PR was merged into the repository by commit 32cad55f0d6ad2af6841e05e26a97bad9abc17cc.

2022-09-19 16:59 UTC, closed without merging