feat(core): improve typings to allow for multi provided ProviderToken
angular/angular pull request #47341
Opened 2022-09-04 10:48 UTC by basti-n

Multi-provided tokens (`multi` option, see e.g. ClassProvider) causes the injector to return an array of provided instances. 
Currently, this behavior is not being correctly reflected in the injector method typings. 

This PR ensures the consumers of applicable methods (i.e. methods were the returned type of the injector is concerned) can define that the token is being multi-provided and hence the injectors return is an array instead of just one instance.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [] Other... Please describe:

## What is the current behavior?

For example the Testbed's static `inject` method.
```javascript
beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [AppComponent],
      providers: [
        {
          provide: RandomTextProvider,
          useClass: BuzzwordService,
          multi: true,
        },
        {
          provide: RandomTextProvider,
          useClass: LoremIpsumService,
          multi: true,
        },
      ],
    }).compileComponents();

    /*
      Does not work!
      Argument of type 'typeof RandomTextProvider' is not assignable to parameter of type 'ProviderToken<RandomTextProvider[]>'.
      Type 'typeof RandomTextProvider' is not assignable to type 'Type<RandomTextProvider[]>'.
    */
    textProviders = TestBed.inject<RandomTextProvider[]>(RandomTextProvider);
```

Issue Number: N/A

## What is the new behavior?

Consumers of the Testbed `inject` can specify that the requested Token is being multi-provided.

```javascript
    /*
      Does work!
    */
    textProviders = TestBed.inject<RandomTextProvider[]>(RandomTextProvider);
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-09-08 18:11 UTC, jessicajaniuk approved these changes
LGTM :cookie:

Thanks for this!

reviewed-for: public-api

2022-09-08 18:12 UTC, jessicajaniuk commented
@basti-n looks like this needs a rebase to main.

2022-09-08 19:09 UTC, basti-n commented
> @basti-n looks like this needs a rebase to main.

consider it done :) thanks for the review

2022-09-08 23:38 UTC, dylhunn approved these changes
reviewed-for: public-api

2022-09-09 22:24 UTC, AndrewKushnir commented on packages/core/test/test_bed_spec.ts
> +      const multiProvidedToken = new InjectionToken<{value: string}>('multiProvidedToken');
Could you please add a test to illustrate a use-case where a generic used for the `InjectionToken` has an array type? For multi-provider tokens, we use an array as a generic type, for example:
https://github.com/angular/angular/blob/9e2d3ed2d13c0e12bc2e7ae733661ac2c2e97fed/packages/forms/src/directives/control_value_accessor.ts#L212-L213

2022-09-10 09:38 UTC, basti-n commented on packages/core/test/test_bed_spec.ts
> +      const multiProvidedToken = new InjectionToken<{value: string}>('multiProvidedToken');
ℹ️ I added the test

2022-09-12 17:18 UTC, pkozlowski-opensource requested changes
Thnx for the PR @basti-n - the change LGTM overall but the PR needs a bit of cleanup:
* it looks like it contains an unrelated commit https://github.com/angular/angular/pull/47341/commits/9d575b3c238558668b43686595e2003a664bf515
* could you please squash the change and the test commits to one - this is important for cases where we want to, say, pick this commit into different branches and / or rollback. 

Thnx!

2022-09-12 18:33 UTC, JoostK commented
Hi @basti-n,

Thank you for your contribution. We've just discussed this issue some more and we'd like to take a step back to evaluate how multi providers currently work and what we can do to improve the type-safety for multi providers. We'll get back to you here once we know more of how/if we'd like to proceed with this PR.

2022-09-15 06:35 UTC, basti-n commented
> Hi @basti-n,
> 
> Thank you for your contribution. We've just discussed this issue some more and we'd like to take a step back to evaluate how multi providers currently work and what we can do to improve the type-safety for multi providers. We'll get back to you here once we know more of how/if we'd like to proceed with this PR.

Wouldn't the proposed change be any hindrance to future changes to how multi providers work though? 

The returned type of multi-providers cannot be inferred by simply looking at the token itself. The provider context needs to be taken into consideration, which will not work for the TestBed.inject I suppose (unless you change the function signature and provide some more context).

2024-09-25 15:05 UTC, JoostK commented
Sorry that this got lost. The comment in https://github.com/angular/angular/pull/47341#issuecomment-1244138890 is unfortunately still true today; we believe there's a better design possible and this change complicates the types quite a bit, which doesn't align with the direction we'd like to evolve this in.

Thanks for the contribution though, sorry for the lack of follow-ups.

2024-09-25 15:05 UTC, closed without merging