docs: update contribution docs for serving a local library/project
angular/angular pull request #47421
Opened 2022-09-13 20:16 UTC by fabioemoutinho

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

#46771
when trying to build Angular packages locally for the first time, there's a knowledge barrier that is difficult to overcome. It is not explicit anywhere that you should disable the Angular CLI cache in your app, which causes serving an app to use cached builds of the local Angular packages, and also there's no explicit information other than in issue #46771 that explains how to run `ng serve`. This PR is an attempt to add that information to the documentation.

Issue Number: #46771

## What is the new behavior?
Added information to DEVELOPER.md

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Please review or contribute and I'll gladly update the PR, this is my first PR.

2022-09-13 20:18 UTC, fabioemoutinho commented
@alan-agius4 thank you for the information in #46771. Here's the PR to update docs. :)

2022-09-13 21:55 UTC, josephperrott approved these changes
LGTM

2022-09-13 22:11 UTC, fabioemoutinho commented
> LGTM
@josephperrott thanks for reviewing so quickly! Is there anything I need to do on my end? There are some failing tests but I think they are not related to this PR's changes

2022-09-14 09:15 UTC, alan-agius4 commented on docs/DEVELOPER.md
> +`s` in commands above is an alias for `serve` but could be any CLI command
Maybe instead of using `s` use `serve` so you don't have to explain what `s` is?

2022-09-14 09:18 UTC, alan-agius4 commented on docs/DEVELOPER.md
> +- `set BAZEL_TARGET="1" && node --preserve-symlinks node_modules/@angular/cli/lib/init.js s`
```suggestion
**Windows**
```bash
set BAZEL_TARGET="1" && node --preserve-symlinks node_modules/@angular/cli/lib/init.js serve
```

**Unix Systems**
```
BAZEL_TARGET="1" node --preserve-symlinks "node_modules/.bin/ng serve
```

2022-09-14 09:23 UTC, alan-agius4 commented on docs/DEVELOPER.md
> +### Serving a local library/project
```suggestion
### Building and serving a project
```

2022-09-14 09:23 UTC, alan-agius4 commented on docs/DEVELOPER.md
> +#### Serve
```suggestion
#### Invoking the Angular CLI
```

2022-09-14 09:23 UTC, alan-agius4 commented on docs/DEVELOPER.md
> +If you see warnings like `There's already a package called "@angular/router" registered. [...]` when running `build-and-link` you might need to use node's `--preserve-symlinks` option with `ng serve`
```suggestion
You need to invoke the Angular CLI using Node.js [`--preserve-symlinks`](https://nodejs.org/api/cli.html#--preserve-symlinks)  option.
```

You will always need to use `--preserve-symlinks` when serving and building.

2022-09-14 09:24 UTC, alan-agius4 commented on docs/DEVELOPER.md
> +When making changes to Angular packages and testing in a local library/project you need to run `ng cache disable` to disable CLI cache. If you are making changes that are not reflected in your locall
```suggestion
When making changes to Angular packages and testing in a local library/project you need to run `ng cache disable` to disable the Angular CLI disk cache. If you are making changes that are not reflected in your locally served library/project, verify if you have [CLI Cache](https://angular.io/guide/workspace-config#cache-options) disabled.
```

2022-09-14 09:28 UTC, alan-agius4 requested changes
Thanks for this. I couple of minor suggestions to make it clear.

2022-09-14 14:41 UTC, fabioemoutinho commented on docs/DEVELOPER.md
> +- `set BAZEL_TARGET="1" && node --preserve-symlinks node_modules/@angular/cli/lib/init.js s`
I didn't have to use BAZEL_TARGET="1" on my machine, is there a specific scenario where it is needed?

2022-09-14 14:46 UTC, fabioemoutinho commented on docs/DEVELOPER.md
> +`s` in commands above is an alias for `serve` but could be any CLI command
that's a good idea. Is there any other scenario that you need to use `--preserve-symlinks`? Should we keep the text that the user could use other CLI commands other than serve?

2022-09-14 19:52 UTC, fabioemoutinho commented
> Thanks for this. I couple of minor suggestions to make it clear.

@alan-agius4 Requested changes addressed. There's only one thing I'd still like to be clear though: https://github.com/angular/angular/pull/47421#discussion_r970906625
when and why is BAZEL_TARGET="1" needed? It works without setting BAZEL_TARGET for me.

2022-09-15 07:56 UTC, alan-agius4 commented on docs/DEVELOPER.md
> +- `set BAZEL_TARGET="1" && node --preserve-symlinks node_modules/@angular/cli/lib/init.js s`
In case you need packages to be NGCC'd. Nowadays however this should rarely be the case. Maybe we can just omit this.

2022-09-15 07:57 UTC, alan-agius4 commented on docs/DEVELOPER.md
> +`s` in commands above is an alias for `serve` but could be any CLI command
Actually you always need to use `--preserve-symlinks`, so might as well make this section more generic.

2022-09-15 08:01 UTC, alan-agius4 approved these changes
LGTM, thanks for this. 

CI is failing because the last commit has double `fixup!` can you please address that?

2022-09-15 12:41 UTC, fabioemoutinho commented
> LGTM, thanks for this.
> 
> CI is failing because the last commit has double `fixup!` can you please address that?

Absolutely. Is it fine if I rebase and force push a new ref with one commit?

2022-09-15 13:38 UTC, fabioemoutinho commented on docs/DEVELOPER.md
> +- `set BAZEL_TARGET="1" && node --preserve-symlinks node_modules/@angular/cli/lib/init.js s`
@alan-agius4 just waiting your input on this 😬

2022-09-16 18:30 UTC, alan-agius4 approved these changes

2022-09-16 18:30 UTC, alan-agius4 approved these changes
LGTM, thanks for your contribution.

2022-09-19 07:41 UTC, pkozlowski-opensource commented
This PR was merged into the repository by commit 8654e5cbd38740eabe94fc8bdf163eae42046f02.

2022-09-19 07:41 UTC, closed without merging