docs: add missing commas
angular/angular pull request #47540
Opened 2022-09-24 19:36 UTC by twentyfivedots

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The Oxford comma is used in some lists but not in others.

## What is the new behavior?
Use of the Oxford comma in missing lists.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-09-27 14:04 UTC, bob-watson requested changes
Thanks for the edits!
Just a couple of comments to look into, but other than that, LGTM!

2022-09-27 14:04 UTC, bob-watson commented on aio/content/guide/deprecations.md
> +The supporting classes `NgModuleFactoryLoader`, `SystemJsNgModuleLoader`, and `SystemJsNgModuleLoaderConfig` classes were removed from `@angular/core`, as well as `SpyNgModuleFactoryLoader` from `@an
`classes` is mentioned before the list, so it's not necessary after the list.
```suggestion
The supporting classes `NgModuleFactoryLoader`, `SystemJsNgModuleLoader`, and `SystemJsNgModuleLoaderConfig` were removed from `@angular/core`, as well as `SpyNgModuleFactoryLoader` from `@angular/router`.
```

2022-09-27 14:04 UTC, bob-watson commented on aio/content/guide/glossary.md
> +Standalone components, directives, and pipes mainly differ from non-standalone ones by:
```suggestion
Standalone components, directives, and pipes differ from non-standalone ones by:
```

2022-09-27 15:44 UTC, bob-watson requested changes
LGTM.
Can you please clean up the branch by squashing the four commits into one and formatting the resulting commit message so that it starts with `docs: `?

Thanks, again, for your contribution!

2022-09-27 16:39 UTC, twentyfivedots commented
> 



> LGTM. Can you please clean up the branch by squashing the four commits into one and formatting the resulting commit message so that it starts with `docs: `?
> 
> Thanks, again, for your contribution!

Done. Thanks for the hints!

2022-09-27 17:17 UTC, bob-watson approved these changes
LGTM

Reviewed-for: global-docs-approvers

2022-09-29 23:40 UTC, AndrewKushnir approved these changes

2022-09-29 23:41 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 752e2245f4893573c66203bc733804534707eb2f.

2022-09-29 23:41 UTC, closed without merging