docs: fix linter errors for lazy-loading-ngmodules.md
angular/angular pull request #47645
Opened 2022-10-05 18:05 UTC by dsnoeijer

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #47179

## What is the new behavior?
No more linting errors.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-10-05 19:26 UTC, bob-watson requested changes
Thanks for the edits!

These are great. I left one comment on a related issue that the linter would catch if it was smarter, but this is great.

2022-10-05 19:26 UTC, bob-watson commented on aio/content/guide/lazy-loading-ngmodules.md
> +If the Angular CLI generates an error when using the `--route` parameter, but runs correctly without it, you might have imported the same module in multiple places.
Try this:

```suggestion
If `ng generate module` with the `--route` parameter returns an error, but runs correctly without it, you might have imported the same module in multiple places.
```

Anywhere you can replace `Angular CLI` with an actual command, that generally makes the sentence clearer and easier to understand. Generally, such cases are when `Angular CLI` is attributed with performing some action (creating a module, in this case). If you'd like to review the topic to make similar changes, that'd be great. If not, that's fine, too.

As an anecdote, I spent about 5 minutes looking up the replacement command. I found `ng generate module`, which I think would the replacement in this example. Had the original writer used that instead of `CLI` or `Angular CLI`, I'd have saved those 5 minutes. If just 1% of the readers of that page had the same experience, fixing just this one instance would save its readers 38 hours a month.

This isn't called out by the linter (yet), because our initial tests of that rule had too many false positives. This is mostly due to how generic `CLI` is and we didn't have much luck trying to tune the rule to figure out whether `CLI` was used in an appropriate context or not.

2022-10-05 20:05 UTC, dsnoeijer commented on aio/content/guide/lazy-loading-ngmodules.md
> +If the Angular CLI generates an error when using the `--route` parameter, but runs correctly without it, you might have imported the same module in multiple places.
Hi @bob-watson,

Thanks for the explanation about using Angular CLI in documentation, I'll keep it in mind for future changes!
I clicked the "Commit Suggestion" below your post, but I'm not sure how to squash both commits now.

Is this something you can do on your end?

2022-10-05 20:29 UTC, bob-watson commented on aio/content/guide/lazy-loading-ngmodules.md
> +If the Angular CLI generates an error when using the `--route` parameter, but runs correctly without it, you might have imported the same module in multiple places.
[Update a documentation pull request](https://pr47381-0644028.ngbuilds.io/guide/doc-pr-update#clean-up-the-branch) is a documentation update that's in review and talks about squashing your commits.
Be sure that the resulting commit message has the correct format.

2022-10-05 20:33 UTC, bob-watson requested changes
This update LGTM.

[Update a documentation pull request](https://pr47381-0644028.ngbuilds.io/guide/doc-pr-update#clean-up-the-branch) is a documentation update that's in review and talks about squashing your commits.
Be sure that the resulting commit message has the correct format.

2022-10-06 00:48 UTC, bob-watson approved these changes
Thanks for the updates to this topic!

LGTM
Reviewed-for: global-docs-approvers

2022-10-06 00:49 UTC, bob-watson commented
@AndrewKushnir this is ready for your review and merge.

2022-10-06 01:52 UTC, AndrewKushnir approved these changes

2022-10-06 16:50 UTC, closed without merging