docs: fix linter errors for security.md
angular/angular pull request #47688
Opened 2022-10-07 02:18 UTC by dsnoeijer

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #47179

## What is the new behavior?
No more linter errors in the file.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-10-07 17:47 UTC, bob-watson requested changes
Thanks for the edits.
Just a few suggestions to tighten up the text.

2022-10-07 17:47 UTC, bob-watson commented on aio/content/guide/security.md
> +Such code can then, for example, steal user data, in particular login data, or perform actions to impersonate the user.
```suggestion
Such code can then, for example, steal user and login data, or perform actions that impersonate the user.
```

2022-10-07 17:47 UTC, bob-watson commented on aio/content/guide/security.md
> +It is recommended to use [Trusted Types](https://w3c.github.io/webappsec-trusted-types/dist/spec) as a way to help secure your applications from cross-site scripting attacks.
```suggestion
It is recommended that you use [Trusted Types](https://w3c.github.io/webappsec-trusted-types/dist/spec) as a way to help secure your applications from cross-site scripting attacks.
```

2022-10-07 17:47 UTC, bob-watson commented on aio/content/guide/security.md
> +Don't create Angular templates on the server side using a templating language. Doing this carries a high risk of introducing template-injection vulnerabilities.
```suggestion
Don't create Angular templates on the server side using a templating language. This carries a high risk of introducing template-injection vulnerabilities.
```

2022-10-07 19:55 UTC, dsnoeijer commented
@bob-watson 
Changes have been added.

2022-10-07 20:55 UTC, bob-watson approved these changes
LGTM

reviewed-for: global-docs-approvers

2022-10-10 16:59 UTC, josephperrott approved these changes
LGTM

2022-10-10 16:59 UTC, josephperrott commented on aio/content/guide/security.md
> +### Enforcing trusted types
Since this is a proper noun, I believe we would still prefer to have "Enforcing Trusted Types"

2022-10-10 21:17 UTC, dsnoeijer commented on aio/content/guide/security.md
> +### Enforcing trusted types
Reverted it to Trusted Types.

2022-10-11 22:04 UTC, alxhub approved these changes
Reviewed-for: global-approvers

(globally approving as this is a docs-only cleanup and does not need `fw-security` review)

2022-10-11 22:05 UTC, jessicajaniuk commented
This PR was merged into the repository by commit bbbd4c3ac87bf5ff0fb2b080cff4890d66ed0269.

2022-10-11 22:05 UTC, closed without merging