docs: fix linter errors for accessibility.md
angular/angular pull request #47725
Opened 2022-10-10 23:05 UTC by dsnoeijer

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #47179

## What is the new behavior?
No more linter errors in the file.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-10-11 18:08 UTC, bob-watson requested changes
Thanks for the edit.
This is a complex topic with challenging text.
I added some suggestions for you to review.
Thanks!

2022-10-11 18:08 UTC, bob-watson commented on aio/content/guide/accessibility.md
> +CSS classes applied to active `RouterLink` elements (usually via `RouterLinkActive`) provide a visual guide to which link is currently active. This guide doesn't apply to blind or visually impaired u
This is a pretty dense sentence. I tried to split the ideas out here. If this conveys the same information, you can use this change. If not, please revise as required.
```suggestion
CSS classes applied to active `RouterLink` elements, such as `RouterLinkActive`, provide a visual cue to identify the active link.
Unfortunately, a visual cue doesn't help blind or visually impaired users.
Applying the `aria-current` attribute to the element can help identify the active link.
For more information, see [Mozilla Developer Network (MDN) aria-current](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current)).
```

2022-10-11 18:08 UTC, bob-watson commented on aio/content/guide/accessibility.md
> +## Extra resources
```suggestion
## More information
```

2022-10-13 20:56 UTC, dsnoeijer commented
@bob-watson Done.

2022-10-17 16:03 UTC, bob-watson approved these changes
LGTM

reveiwed-for: global-docs-approvers

2022-10-17 18:28 UTC, AndrewKushnir approved these changes

2022-10-17 18:29 UTC, AndrewKushnir commented
Caretaker note: this PR was globally approved, so we can proceed with the merge.

2022-10-19 18:14 UTC, closed without merging