docs: highlight scripts in markdown
angular/angular pull request #47778
Opened 2022-10-14 22:48 UTC by nouraellm

This PR highlights all lines of code/cmds/error messages by specifying the used language

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-11-01 21:27 UTC, bob-watson requested changes
Thanks for your revisions!
I added a couple of comments where output was formatted as shell, which can cause some inappropriate formatting when keywords are present in the output.

2022-11-01 21:27 UTC, bob-watson commented on docs/BAZEL.md
> +```sh
This block looks like output and should probably not be formatted as a shell command.

2022-11-01 21:27 UTC, bob-watson commented on docs/BAZEL.md
> +```sh
This block looks like output and should probably not be formatted as a shell command.

2022-11-01 21:27 UTC, bob-watson commented on docs/PUBLIC_API.md
> +```sh
This block looks like output and should probably not be formatted as a shell command.

2022-11-01 21:27 UTC, bob-watson commented on docs/BAZEL.md
>  If you see the following error:
Move the command from the following block with the error messages to here, such as: 
```suggestion
If running `yarn bazel build packages/...` returns the following error:
```

2022-11-01 21:27 UTC, bob-watson commented on docs/BAZEL.md
>  $ yarn bazel build packages/...
It might also be more clear in this context to move the command to before this block.

2022-11-01 21:27 UTC, bob-watson commented on docs/BAZEL.md
> +```sh
This block is mostly output and should probably not be formatted as a shell command.

2022-11-06 17:51 UTC, nouraellm commented
@bob-watson thank you very much for the review, changes requested have been applied as required!
Everyone else who got the notification to review this PR .. sorry 🙈 fixup commits are still new to me.
Good day!

2022-11-07 15:34 UTC, bob-watson approved these changes
LGTM

Reviewed-for: global-docs-approvers

2022-11-07 18:57 UTC, jessicajaniuk approved these changes

2022-11-15 23:04 UTC, atscott approved these changes

2023-01-11 22:54 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 1cb93ce4e17e1a04e74303c0f4b89c2019e34337.

2023-01-11 22:54 UTC, closed without merging