docs: add a link to hierarchical-dependency-injection
angular/angular pull request #47979
Opened 2022-11-05 11:59 UTC by lsst25

It is not clear that when we provide a service to some eagerly loaded module of an application, then that service is available for components of all eagerly loaded modules of that application. It would be better to give a link for more information at least.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x ] No

## Other information

2022-11-05 23:05 UTC, hexiaokang approved these changes

2022-12-13 16:40 UTC, bob-watson requested changes
Thanks for the valuable suggestion.
I just had a comment on how it's presented. If you can't make that edit, let me know.

2022-12-13 16:40 UTC, bob-watson commented on aio/content/guide/dependency-injection.md
> +When you register a provider with a specific NgModule, the same instance of a service is available to all components in that NgModule (to understand all edge-cases, see [Hierarchical injectors](guide
We try to avoid parenthetical clauses in the documentation as they are easily ignored or skipped when they are read. 
The text you added would be more useful to readers are a new sentence.
```suggestion
When you register a provider with a specific NgModule, the same instance of a service is available to all components in that NgModule.
To understand all edge-cases, see [Hierarchical injectors](guide/hierarchical-dependency-injection).
```

2022-12-13 22:16 UTC, bob-watson approved these changes
updated to meet style guide

reviewed-for: global-docs-approvers

2022-12-13 22:17 UTC, jessicajaniuk approved these changes

2022-12-13 22:47 UTC, jessicajaniuk commented
This PR was merged into the repository by commit f6ac94c81cf91116cbe8f9165f12d30f75eefc1d.

2022-12-13 22:47 UTC, closed without merging