feat(core): Allow typeguards on QueryList.filter
angular/angular pull request #48042
Opened 2022-11-14 09:12 UTC by JeanMeche

To match the behaviour of Array.filter, typeguards can now be used on QueryList.filter to narrow the return type.

Fixes #38446

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-11-14 10:21 UTC, JeanMeche commented
I'm also thinking about including the fix for #39602 in this PR.

2022-11-29 21:27 UTC, AndrewKushnir commented
Just a quick note to myself: the typings for the `Array.filter` are here: https://github.com/microsoft/TypeScript/blob/main/lib/lib.es5.d.ts#L1256

2022-11-30 01:42 UTC, AndrewKushnir reviewed
@JeanMeche thanks for the PR! I've checked that the typings of the `QueryList.filter` are similar to the typings of [the `Array.filter` method](https://github.com/microsoft/TypeScript/blob/main/lib/lib.es5.d.ts#L1256).

This change might introduce a breaking change in apps code. The possibility is very low, so we probably won't need a schematic to migrate the code (we'll be able to tell precisely after running tests in Google's codebase), but we'd be able to include this change only into the next **major** version (v16) according to the SemVer. I've added this PR to the "v16-candidates" Github milestone and we'll get back to this PR once the main branch is open for v16 changes (which will happen after releasing the last v15.x minor version).

Thank you.

2023-03-06 03:59 UTC, AndrewKushnir commented
[Global Presubmit](https://test.corp.google.com/OCL:514281007:BASE:514280872:1678075098360:f4e190bd).

2023-03-30 23:31 UTC, AndrewKushnir commented
@pkozlowski-opensource yes, it should be ready for merge after one more TGP (just in case). Will update the PR once I have TGP results.

2023-03-31 02:21 UTC, AndrewKushnir commented
[Global Presubmit #2](https://test.corp.google.com/OCL:514281007:BASE:520802990:1680229265094:4b13a3e).

2023-03-31 02:22 UTC, AndrewKushnir approved these changes
Reviewed-for: fw-core, public-api

2023-03-31 16:32 UTC, jessicajaniuk approved these changes
reviewed-for: public-api

2023-03-31 16:46 UTC, AndrewKushnir commented
**Caretaker note**: the TGP is "green", this PR is ready for merge.

2023-03-31 16:47 UTC, alxhub requested changes

2023-03-31 16:47 UTC, alxhub commented on packages/core/src/linker/query_list.ts
> +  filter(predicate: (value: T, index: number, array: readonly T[]) => unknown, thisArg?: any): T[];
We should not declare `thisArg` as a parameter here, since we don't seem to use/support it in the implementation.

2023-04-01 19:19 UTC, AndrewKushnir commented
[Global Presubmit #3](https://test.corp.google.com/OCL:514281007:BASE:521168295:1680376749172:5d6b2cf6).

2023-04-03 16:27 UTC, alxhub approved these changes
Reviewed-for: public-api

2023-04-04 02:35 UTC, dylhunn commented
This PR was merged into the repository by commit b2327f4df12ca91d7cdbc3dc5c0f5cb3ab88a30e.

2023-04-04 02:35 UTC, closed without merging