feat(core): Expose render3's isStandalone()
angular/angular pull request #48114
Opened 2022-11-18 09:19 UTC by JeanMeche

Making isStandalone() a public api

fixes #47919

## PR Type
What kind of change does this PR introduce?

- [x] Feature

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No (outside of not removing `ɵisStandalone`)

2022-11-18 18:33 UTC, AndrewKushnir reviewed
@JeanMeche thanks for the PR 👍

I've left some comments, but also wanted to propose an update to the error message:

```
feat(core): Make the `isStandalone()` function available in public API

This commit updates an internal `isStandalone` function and exposes it as a public API,
so that it can be used in applications code.

Fixes #48114.
```

Thank you.

2022-11-18 18:33 UTC, AndrewKushnir commented on packages/core/src/render3/definition.ts
> + * @publicApi
```suggestion
 * Checks whether a given Component, Directive or Pipe is marked as standalone.
 * See this guide for additional information: https://angular.io/guide/standalone-components
 *
 * @param type A reference to a Component, Directive or Pipe.
 * @publicApi
```

2022-11-18 18:33 UTC, AndrewKushnir commented on packages/core/test/render3/definition_spec.ts
> +/**
We plan to remove the `render3` folder eventually and migrate tests to the `packages/core/test/acceptance` folder, so let's move these tests to the `packages/core/test/acceptance/standalone_spec.ts` file instead.

2022-11-18 18:33 UTC, AndrewKushnir commented on packages/core/test/render3/definition_spec.ts
> +describe('definition isStandalone()', () => {
```suggestion
describe('isStandalone()', () => {
```

2022-11-18 18:33 UTC, AndrewKushnir commented on packages/core/test/render3/definition_spec.ts
> +    @Component({selector: 'standalone-cmp', standalone: true})
I think it'd be great to add some tests for a case when non-annotated class is used as an argument in the `isStandalone` function.

2022-11-18 18:33 UTC, AndrewKushnir commented on packages/core/test/render3/definition_spec.ts
> +    @Component({selector: 'standalone-cmp', standalone: true})
Actually, if a non-annotated class is used as an argument, we should probably throw an error, similar to this one (and have tests that verify this behavior):

https://github.com/angular/angular/blob/764fa3d9c37eb70acd21879296ec039de07173ea/packages/core/src/render3/errors.ts#L36-L39

2022-11-21 10:19 UTC, JeanMeche commented
@AndrewKushnir I took your suggestions into account  !

2022-11-21 18:11 UTC, AndrewKushnir reviewed
@JeanMeche thanks for addressing the feedback! I've added a few more comments.

2022-11-21 18:11 UTC, AndrewKushnir commented on packages/core/src/render3/definition.ts
> +  if (def === null) {
We'd also need to add the `ngDevMode` here, so that this code is tree-shaken away from production bundles:
```suggestion
  if (ngDevMode && def === null) {
```

2022-11-21 18:11 UTC, AndrewKushnir commented on packages/core/test/acceptance/standalone_spec.ts
> +      class ClassyMcClassFace {}
```suggestion
      class NonAnnotatedClass {}
```

2022-11-21 21:58 UTC, JeanMeche commented on packages/core/src/render3/jit/module.ts
> +      isStandalone(moduleType)) {
Yes ! That's the purpose !

2022-11-23 06:28 UTC, AndrewKushnir approved these changes
@JeanMeche thanks for addressing the feedback. The changes look good 👍 

Note: since this PR updates the public API, it'd require a couple more reviews (they'll be requested automatically), so you may receive some additional comments.

Thank you.

2022-11-23 15:43 UTC, atscott requested changes

2022-11-23 15:43 UTC, atscott commented on packages/core/src/render3/definition.ts
>  export function isStandalone<T>(type: Type<T>): boolean {
Since the generic type isn't returned by the function, I don't think there's really a reason to use a generic, right? This could just be `isStandalone(type: Type<unknown>): boolean`

2022-11-23 15:43 UTC, atscott commented on packages/core/src/render3/jit/module.ts
> +      isStandalone(moduleType)) {
I'm not sure I agree with this design decision because it makes the code kind of awkward. Throwing in one environment and not throwing in the other and then needing these extra checks because it throws in dev but in prod this code is unnecessary. 

If the intent is to throw an error in dev, we should just throw it. The code here should not need to know the implementation details of `isStandalone` to avoid an error. If we want to avoid a possible breaking change, this should start as a warning and be made an error in a later version (this is something we've done before https://github.com/angular/angular/blob/6948f0f0f39c65f3dd0b2098774083f9c5a93352/packages/core/src/di/interface/defs.ts#L220-L224)

2022-11-23 19:49 UTC, AndrewKushnir commented on packages/core/src/render3/jit/module.ts
> +      isStandalone(moduleType)) {
@JeanMeche can you try reverting this part of the PR and push the change? It'll trigger CI rerun and we can see which test cases fail because of this (so we can review them and come up with a better approach if needed).

2022-11-24 08:42 UTC, JeanMeche commented on packages/core/src/render3/jit/module.ts
> +      isStandalone(moduleType)) {
@AndrewKushnir done

2022-11-24 18:23 UTC, JeanMeche commented on packages/core/src/render3/jit/module.ts
> +      isStandalone(moduleType)) {
@atscott I think this check is necessary if we want to throw an error.

`isStandalone` here is being passed modules and potentially non annotated classes.  `isStandalone()` should have to handle those calls. 

Either we go with a warning or we first narrow `moduleType` to Components/Directives/Pipes.

2022-11-28 15:09 UTC, atscott commented on packages/core/src/render3/definition.ts
> +  return def ? def.standalone : false;
We prefer strict equality checks in the compiler code. Please revert this to how it was before: `def !== null ? def.standalone : false`

2022-11-28 15:16 UTC, atscott commented on packages/core/src/render3/jit/module.ts
> +      isStandalone(moduleType)) {
Actually, thinking about this a bit more, do we even _have_ public API exposed that allows you to do something similar to `getComponentDef(moduleType) || getPipeDef(moduleType) || getDirectiveDef(moduleType)`? If developers are in a situation where calling `isStandalone` might result in an error, how do they add checks to avoid the error? Unless we have public API exposed that allows developers to only call `isStandalone` when they have a component, pipe, or directive, I don't think throwing an error is at all the right thing to do because there's no way around the error without `try...catch`.

2022-11-28 18:03 UTC, JeanMeche commented on packages/core/src/render3/jit/module.ts
> +      isStandalone(moduleType)) {
You're making a point ! Actually OP on #47919 was bothered that only components had this ability through `reflectComponentType`. 

@AndrewKushnir Maybe we just log a warn in dev when used with bad arguments ?

2022-11-30 01:35 UTC, AndrewKushnir commented on packages/core/src/render3/definition.ts
> +    throw new RuntimeError(
@JeanMeche we've discussed this further with the team and the proposal is that we should revert this check and basically keep the code of the function as is (which would also avoid the need to change the code within `packages/core/src/render3/jit/module.ts`). Could you please update the code (and drop unnecessary tests that check that the error is thrown)?

2022-11-30 13:12 UTC, JeanMeche commented
@atscott  @AndrewKushnir I think we're good this time 👍

2022-11-30 17:04 UTC, atscott commented on packages/core/src/render3/definition.ts
> + * See this guide for additional information: https://angular.io/guide/standalone-components
nit: Maybe just mention that it will just return `false` if you pass anything other than a Component, Directive, or Pipe class?

2022-11-30 17:05 UTC, atscott approved these changes
LGTM. Thanks for your patience on this!

2022-11-30 18:07 UTC, JeanMeche commented on packages/core/src/render3/definition.ts
> + * See this guide for additional information: https://angular.io/guide/standalone-components
✅

2022-11-30 21:35 UTC, AndrewKushnir reviewed
@JeanMeche thanks for addressing the feedback, I've added one quick comment about extra tests for non-annotated classes and an NgModule.

2022-11-30 21:35 UTC, AndrewKushnir commented on packages/core/test/acceptance/standalone_spec.ts
> +    });
@JeanMeche let's also add cases for (1) a non-annotated class and (2) an NgModule (in both cases we expect `false` to be returned).

2022-11-30 21:41 UTC, JeanMeche commented on packages/core/test/acceptance/standalone_spec.ts
> +    });
Thx, I appreciate the feedback. 

I've added the 2 tests ✅

2022-11-30 22:16 UTC, AndrewKushnir approved these changes
@JeanMeche the changes look great, I'm adding an LGTM. We'd need to get a couple more approvals since this PR changes the public API surface.

2022-11-30 22:16 UTC, AndrewKushnir commented on packages/core/test/acceptance/standalone_spec.ts
> +    });
Great, thanks! 👍

2022-12-01 17:04 UTC, jessicajaniuk approved these changes
LGTM! This looks great! Thanks, @JeanMeche!

reviewed-for: public-api, fw-core

2022-12-01 17:59 UTC, AndrewKushnir commented on packages/core/src/render3/definition.ts
> +  return type[NG_COMPz_DEF] || null;
@JeanMeche it looks like this a new (and likely unwanted?) change. Could you please take a look?

2022-12-01 20:05 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:492262961:BASE:492263009:1669925080225:f2f61da7).

2022-12-01 21:19 UTC, AndrewKushnir commented
**Caretaker Note:** Please ignore the `google-internal-tests` status. Unrelated and pre-existing failing targets.

2022-12-01 21:21 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 38421578a2573bcbc86c927ed4015e20fc39f04a.

2022-12-01 21:21 UTC, closed without merging

2022-12-01 21:22 UTC, AndrewKushnir commented
@JeanMeche thanks again for creating this PR and addressing the feedback 👍
The PR is now merged and will be released as a part of Angular v15.1.0 in a few weeks.