docs(router): Deprecate canLoad guards in favor of canMatch
angular/angular pull request #48180
Opened 2022-11-22 19:57 UTC by atscott

As mentioned in #46021, `canMatch` guards can replace `canLoad`. There are slight differences between the two but the purpose of preventing user access to feature modules is still achievable. There are several reasons keeping `CanLoad` around is detrimental to the API surface:

* Lazy loading should not be an architectural feature of an application. It's an optimization you do for code size. That is, there should not be an architectural feature in the router to directly specifically control whether to lazy load something or not based on conditions such as authentication. This is a slightly nuanced difference between the proposed `canMatch` guard: this guard would control whether you can use the route at all and as a side-effect, whether we download the code. `CanLoad` only specified whether the code should be downloaded so `canMatch` is more powerful and more appropriate.

* The naming of `CanLoad` will be potentially misunderstood for the `loadComponent` feature. Because it applies to `loadChildren`, it feels reasonable to think that it will also apply to `loadComponent`. This isn’t the case: since we don't need to load the component until right before activation, we defer the loading until all guards/resolvers have run.

* Unnecessary API surface bloat where two features (CanMatch and CanLoad) do essentially the same thing. This affects code size for supporting two nearly identical features as well as the learning and teaching journey for them both.

2022-11-23 18:20 UTC, bob-watson requested changes
Looks good, overall.
I just had some suggestions to tighten up the language some.

2022-11-23 18:20 UTC, bob-watson commented on aio/content/guide/router-tutorial-toh.md
> +A `canMatch` guard will control whether the `Router` even attempts to match a `Route`. This allows you to have
```suggestion
A `canMatch` guard controls whether the `Router` attempts to match a `Route`. This lets you have
```

2022-11-23 18:20 UTC, bob-watson commented on aio/content/guide/router-tutorial-toh.md
> +multiple `Route` configurations which share the same `path` but are matched based on different conditions. In addition, this approach
```suggestion
multiple `Route` configurations that share the same `path` but are matched based on different conditions. This approach
```

2022-11-23 18:20 UTC, bob-watson commented on aio/content/guide/router-tutorial-toh.md
> +can allow the `Router` to match the wildcard `Route` instead.
```suggestion
allows the `Router` to match the wildcard `Route` instead.
```
But, I'm not sure if `instead` should be `as well`.

2022-11-23 18:20 UTC, bob-watson commented on aio/content/guide/router-tutorial-toh.md
> +The existing `authGuard` already has the essential logic to support the `canMatch` guard.
```suggestion
The existing `authGuard` contains the logic to support the `canMatch` guard.
```

2022-11-23 18:20 UTC, bob-watson commented on aio/content/guide/router-tutorial-toh.md
> +All you need to do is add the `authGuard` to the `canMatch` array property for the `admin` route.
```suggestion
Finally, add the `authGuard` to the `canMatch` array property for the `admin` route.
```

2022-11-23 22:57 UTC, bob-watson approved these changes
LGTM

Reviewed-for: global-docs-approvers

2022-11-23 23:19 UTC, jessicajaniuk approved these changes
reviewed-for: public-api

2022-11-28 16:38 UTC, pkozlowski-opensource approved these changes
LGTM

Reviewed-for: public-api

2022-11-28 17:04 UTC, atscott commented
This PR was merged into the repository by commit 228e992db75bd7a2213b4596e6e2a8696578aa19.

2022-11-28 17:04 UTC, closed without merging