Feature/fix 24571 common http
angular/angular pull request #48241
Opened 2022-11-27 10:04 UTC by JeanMeche

## PR Type
- [x] Refactoring (no functional changes, no api changes)

Issue Number: #24571

## Does this PR introduce a breaking change?
- [x] No

2022-11-27 10:18 UTC, JeanMeche commented on packages/common/http/test/xhr_mock.ts
> +export class MockXMLHttpRequest implements XMLHttpRequest {
I would have prefered to use `extends` instead of `implements` but I couldn't get it to work. 

I got error `XMLHttpRequest is not defined` (I understand that `XMLHttpRequest` is not available on `NodeJS` but I thought tslib would provide it). Anyway any help on this is welcome

2022-12-12 09:45 UTC, pkozlowski-opensource commented on packages/common/src/directives/ng_for_of.ts
> +  // waiting for microsoft/typescript#43662 to allow the return type `TrackByFunction|undefined` for
Not sure if this comment adds value. Revert?

2022-12-12 09:49 UTC, pkozlowski-opensource requested changes
@JeanMeche thnx for the PR. There is quite a bit going on in there and the main difficulty in reviewing those PRs is that there are many changes in several packages.
Could you please split your PR into 2 and:
* separate common/http changes from other changes in a separate PR?
* have a separate commit / PR for each directive ?

2023-02-27 19:23 UTC, JeanMeche commented
How breaking is the change for `HttpResponseBase.type` in G3 ?

2023-05-01 14:07 UTC, closed without merging