refactor(common): remove non-null assertions from directives
angular/angular pull request #48476
Opened 2022-12-13 17:21 UTC by JeanMeche

## PR Checklist
Per request from @pkozlowski-opensource, I'm splitting PR #48241 into 2. 

See individual commits. 

These are fixes targeted to resolve https://github.com/angular/angular/issues/24571

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [x] No

2022-12-13 19:24 UTC, atscott requested changes

2022-12-13 19:24 UTC, atscott commented on packages/common/src/directives/ng_plural.ts
> +    if (this._switchValue !== undefined) {
Would `_switchValue` be better with a default value? It's actually kind of correct with the `!` right now. The directive won't match unless this is defined. It's a little unfortunate that we have to _add_ code to account for the possibility of `undefined` when it really can't ever be in production.

2022-12-13 19:24 UTC, atscott commented on packages/common/src/directives/ng_switch.ts
> +  private _defaultViews?: SwitchView[];
Should this have a default of empty array instead of undefined?

2022-12-21 19:21 UTC, JeanMeche commented on packages/common/src/directives/ng_plural.ts
> +    if (this._switchValue !== undefined) {
You're right, we can keep the type safety by passing the value to `_updateView`

2022-12-21 19:30 UTC, JeanMeche commented on packages/common/src/directives/ng_switch.ts
> +  private _defaultViews?: SwitchView[];
I'd rather see undefined or null as a default value.  It's created when needed by `_addDefault` and checked by `_updateDefaultCases`. 

I'm always to other point of views though.

2022-12-21 20:21 UTC, atscott commented on packages/common/src/directives/ng_switch.ts
> +  private _defaultViews?: SwitchView[];
Having it be nullable rather than empty list provides no additional meaning. I feel quite strongly that this should never be `null` or `undefined`. You can also update the rest of the code to remove the truthiness checks of this value.

2022-12-22 22:09 UTC, JeanMeche commented on packages/common/src/directives/ng_switch.ts
> +  private _defaultViews?: SwitchView[];
I used empty array as default value. It seems presubmit is failing now with the changes. Any heads-up ?

2022-12-27 17:39 UTC, atscott approved these changes
👍 LGTM

2022-12-27 17:50 UTC, atscott requested changes

2022-12-27 17:50 UTC, atscott commented on packages/common/src/directives/ng_plural.ts
> +  private _switchValue?: number;
It doesn't look like this is used anywhere now that the value is passed to `_updateView`. Let's remove it.

2022-12-27 17:52 UTC, JeanMeche commented on packages/common/src/directives/ng_plural.ts
> +  private _switchValue?: number;
done 👍

2022-12-27 17:53 UTC, atscott requested changes

2022-12-27 17:53 UTC, atscott commented on packages/common/src/directives/ng_switch.ts
> +    if (useDefault !== this._defaultUsed) {
```suggestion
    if (this._defaultViews.length > 0 && useDefault !== this._defaultUsed) {
```
I think you need to have the `length` check here to be equivalent with how it was before.

2022-12-27 19:18 UTC, JeanMeche commented on packages/common/src/directives/ng_switch.ts
> +    if (useDefault !== this._defaultUsed) {
Done. I also cleaned up the commits to match 1 file changed/per commit.

2022-12-28 19:39 UTC, atscott approved these changes
@JeanMeche looks like the lint test is failing. The code changes otherwise look good and the internal test failures are unrelated

2023-01-05 17:29 UTC, atscott approved these changes

2023-01-05 22:46 UTC, alxhub commented
This PR was merged into the repository by commit d887d69f241f67dd77c8533f7eed08d6397f98a8.

2023-01-05 22:46 UTC, closed without merging