docs(aio): add Angular, Node.js, TypeScript, and RxJS version compatibility matrix
angular/angular pull request #48753
Opened 2023-01-16 22:00 UTC by LayZeeDK

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Angular consumers find it difficult to find an overview of version compatibility between Angular and its peer dependencies.

Issue Number: #47771

## What is the new behavior?
Add compatibility matrix for Angular, Node.js, TypeScript, and RxJS.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Zone.js is missing from the matrix. Anyone feel free to add it.

2023-01-16 22:08 UTC, LayZeeDK commented
Let me know how we proceed from here, @bob-watson.

2023-01-17 09:10 UTC, alan-agius4 commented on aio/content/guide/versions.md
> +| ------------------------------------------- | ----------------- | ------------------------------------ | ------------------ | ------------------ |
Thanks for this. 

Couple of points though:
- I don't think we should include non LTS versions of Angular.
- Some versions below are a bit confusing, example why `~14.0.7` and not `~14.0.0`
- Do we need to distinguish between Angular CLI and Framework? My 2 cents would be no.

2023-01-17 12:47 UTC, vmasek commented on aio/content/guide/versions.md
> +| ------------------------------------------- | ----------------- | ------------------------------------ | ------------------ | ------------------ |
I would advocate to keep the non-LTS versions in, especially if there are ones that differ somehow from the steps in between.

Use case for them is, that as a developer that has to fix, takeover, audit or support app in any way that includes building it, you are often facing strange version alignments that were just left as is. Matrix that includes these semi steps really helps you identify what node to use and what TS version to correct to.

I am up for reducing if possible, but I would discourage switching to much less informative table that only includes the LTS versions and does not keep the history, as this was the biggest advantage of the table from @LayZeeDK over just opening the package JSON of the Angular version you are struggling with.

2023-01-17 13:13 UTC, alan-agius4 commented on aio/content/guide/versions.md
> +| ------------------------------------------- | ----------------- | ------------------------------------ | ------------------ | ------------------ |
For history purposes, users can check the archived versions of the Angular docs. Example: https://v10.angular.io One of the reasons that I think we should not keep LTS versions is that they are no longer maintained and supported.

2023-01-17 13:27 UTC, vmasek commented on aio/content/guide/versions.md
> +| ------------------------------------------- | ----------------- | ------------------------------------ | ------------------ | ------------------ |
Yes, you can potentially get to this info even easier than digging in old docs, but knowing the requirements to build/serve an old can be very helpful for its update, especially if a lot needs to be manually checked and compared.

Knowing what you need to build an Angular 5 project can be difference between attempting to migrate to latest LTS and abandoning it completely.

2023-01-17 17:20 UTC, bob-watson requested changes
This looks great!

I added the `aio:preview` label to see what the rendered page will look like and made a couple of comments to address some of the earlier feedback.

I don't see where this is added to the navigation, so `aio/content/navigagtion.json` will need this object added between the `guide/releases` and the `guide/browser-support` entries for it to show up in the ToC.

```
        {
          "url": "guide/versions",
          "title": "Version compatibility",
          "tooltip": "Angular framework, Angular CLI, Node.js, TypeScript, and RxJS version compatibility"
        },
```

2023-01-17 17:20 UTC, bob-watson commented on aio/content/guide/versions.md
> +| ------------------------------------------- | ----------------- | ------------------------------------ | ------------------ | ------------------ |
@alan-agius4 would a note/disclaimer about the support, or lack thereof, for non LTS versions be satisfactory. I tend to lean towards including historical info for the reasons listed above. But annotated with exceptions, e.g. versions not receiving support. Because this is a reference table, it seems like it should have all the reference data--historical and otherwise.

To address this, I added the comment & suggestion above.

2023-01-17 17:20 UTC, bob-watson commented on aio/content/guide/versions.md
> +Angular CLI, Angular, Node.js, TypeScript, and RxJS version compatibility.
Introductory text to describe the context and limitations of this info might help resolve some of the issues raised in the following conversation. Something like:

```suggestion

The following table describes the versions of node.js, TypeScript, and RxJS that each version of Angular requires.

This information is collected from Angular's [package.json](https://unpkg.com/browse/@angular/core/package.json) file and is only guaranteed for the [Angular versions under long-term support (LTS)](guide/releases#actively-supported-versions). Information about earlier Angular versions was correct when that version went out of LTS.
```

2023-01-17 19:30 UTC, bob-watson commented
@LayZeeDK Thanks for pulling this together.

This is a great addition to the documentation.
I can't tell you how many times I've tried to find this in the docs (well, after the first time, I knew it wasn't there, but felt that it should've been on all the subsequent times).

Going forward, I'll add updating this to our new version checklist so that it stays up-to-date.

2023-01-17 23:02 UTC, JeanMeche commented
It would be nice to also include a links to this page for example from : `guide/releases ` !

2023-01-18 19:58 UTC, alan-agius4 commented
@bob-watson regarding the decision if we should include LTS versions or not, I’d deferred to someone from @angular/fw-public-api.

// cc @jelbourn / @AndrewKushnir

2023-01-18 20:00 UTC, alan-agius4 requested changes
- Some versions in the table do not include the correct path. example `~14.0.7 `and not `~14.0.0`

- Do we need to distinguish between Angular CLI and Framework?

2023-01-18 20:01 UTC, LayZeeDK commented
@alan-agius4
Please see https://github.com/angular/angular/pull/48753#discussion_r1074017946.

2023-01-18 20:26 UTC, alan-agius4 commented
> Thank you for your suggestions, @bob-watson. I included all of them. Can we have another preview deployment?

AIO preview is will automatically be generated when CI is green.  Note that the link will be updated in the previous comment https://github.com/angular/angular/pull/48753#issuecomment-1385760294

2023-01-18 20:31 UTC, JeanMeche commented
> Sorry missed that comment completely. I think in this case I would recommend to drop the patch and tilde completely or using `x`
> 
> Ex: `15.0` or `15.0.x`

In this case, should the 2 columns (angular & cli) be merged (rowspan=2) when they have the sam value ?

2023-01-18 20:39 UTC, bob-watson approved these changes
LGTM

Reviewed-for: global-docs-approvers

2023-01-19 05:55 UTC, LayZeeDK commented on aio/content/guide/versions.md
> +| ------------------------------------------- | ----------------- | ------------------------------------ | ------------------ | ------------------ |
The primary reason I oppose only including LTS versions in the table is that it wouldn't cover historical versions which is just as useful as LTS versions. Maybe we could backport a table to each archived version of the docs and in that way cover all versions.

2023-01-19 11:23 UTC, LayZeeDK commented
> In this case, should the 2 columns (angular & cli) be merged (rowspan=2) when they have the same value ?

How to do that would depend on the Markdown flavor supported by angular.io.

2023-01-19 12:55 UTC, LayZeeDK commented
@alan-agius4 

> Sorry missed that comment completely. I think in this case I would recommend to drop the patch and tilde completely or using x
> Ex: 15.0 or 15.0.x

The version ranges are npm-compatible. So it should either be in the format `~15.0.0` or `15.0.x` for Angular CLI and Angular framework packages.

2023-01-19 13:17 UTC, LayZeeDK commented
@alan-agius4 

The version ranges now list `0` as the patch version.

2023-01-19 18:38 UTC, alan-agius4 commented
> @alan-agius4
> 
> The version ranges now list `0` as their patch version although technically [Angular requires](https://unpkg.com/browse/@angular/core/package.json) for example RxJS in version `^6.5.3`.

I only mean the `0`/`x` for Angular and Angular CLI versions.

2023-01-19 20:03 UTC, dgp1130 commented
/cc @bob-watson @jelbourn

Some more general feedback from the tooling team:

Our biggest concern is probably that this list includes non-LTS versions which can make these appear more supported than they should. If we do include non-LTS, there should at least be a very clear boundary between that and the LTS versions, that could be a big red row between them stating "Everything below this is unsupported", or even just using two tables, one for LTS and one for non-LTS with appropriate text beforehand to explain.

The next major concern is about how we update this table. This will be very easy to forget about between versions and we've been trying to reduce the amount of toil we need to do for releases. For major releases we have a big checklist of stuff to go through, so we could add it there, but we don't have such a checklist for minor releases (and shouldn't need one). Given that this list kind of needs to be updated for minor releases (TypeScript version can expand in minors), we're not sure how to include a regular update of this table into our processes.

Pre-release CLI versions shouldn't be included in this list as those were never officially supported. I suggest replacing those with `N/A` or `-` as if the CLI didn't exist at that time. Maybe include an asterisk with a footnote explaining that the CLI didn't exist yet.

The chart mostly aligns framework and CLI minor versions, but that's not accurate. The CLI supports any framework version of the same major. You can run CLI v14.2.0 with the framework at v14.0.0 and vice versa. We should consider merging those columns with maybe some caveats for the older versions where they do diverge.

We should link to the [semver page](https://semver.org/) so readers can understand the syntax (I know I can never remember `~` vs `^`). Or we should consider simplifying to be more human-readable as @alan-agius4 suggested (15.2.x, 15.2, ...). Mostly happy to defer to @bob-watson on what the right approach is here, but something to think about.

We currently have version information scattered a bit around AIO. This is somewhat unrelated to this PR, but adding an additional page make the problem worse. Should add this table to [the versions page](https://angular.io/guide/releases)?

## Node version

The most complex issue here is that our Node.js support policy has historically been a bit vague. I think the only official documentation is [here](https://angular.io/guide/setup-local#prerequisites) which states "Angular requires an [active LTS or maintenance LTS](https://nodejs.org/about/releases) version of Node.js." This is a unclear since Angular and Node release at different cadences. So if Angular releases version X supporting Node versions Y and Z, then Node drops support for version Y while Angular X is still in LTS, does Angular still support version X running on Node Y? This has come up in the past when a transitive dependency pushed an `engines` field update dropping support for Node Y in such a situation and resulted in Angular X breaking on Node Y.

We've had some discussion about the right support model here, but wanted to run an RFC through the community before committing to any changes to the support policy. I got busy with other things and never had a chance to run that RFC, so we never improved the documentation and the vague Node.js policy still stands.

The tricky part for this documentation is that it does impact the Node.js versions included here in a much more concrete way. Angular v13 includes Node v12 in this table but [Node v12 is no longer supported by the Node team](https://nodejs.dev/en/about/releases/). It will probably work, but I don't know if we technically support that configuration. This also affects when we update the table, given that if we decide we _don't_ support out of LTS Node versions, then we need to update the table whenever that happens (ie. when Node v14 falls out of support in April).

2023-01-23 10:44 UTC, JeanMeche commented
It looks much better 👍

2023-02-04 20:00 UTC, LayZeeDK commented
@alan-agius4
Please add another review when time allows.

2023-02-08 20:18 UTC, LayZeeDK commented
@bob-watson 
What do you think of the latest version?

2023-02-08 21:45 UTC, bob-watson commented
@LayZeeDK I think it looks great!

2023-02-08 22:38 UTC, mgechev approved these changes

2023-02-27 12:07 UTC, LayZeeDK commented
@jelbourn 
What do you think, is this ready to go to docs production?

2023-03-28 15:53 UTC, dscalzi commented
Would be great to have this available in the official documentation.

2023-03-30 23:04 UTC, jelbourn approved these changes
Thanks for the patience- I kept generating a new preview and then getting distracted. 

LGTM

2023-03-30 23:07 UTC, jelbourn commented
@alan-agius4 is your review comment satisfied?

2023-03-31 11:08 UTC, alan-agius4 commented
@jelbourn, we just need to add the versions for 15.2 since it is not outdated.

2023-04-01 17:50 UTC, LayZeeDK commented
That's okay, @jelbourn. I'm glad that this will be accepted.

I updated it to cover Angular 15.2, @alan-agius4. Thanks for the heads up.

2023-04-13 22:16 UTC, JeanMeche commented
The CLA is failing now because Bob left the angular team and likely revoked it. 

You'll need to remove him as an author of the commits. Also a rebase is necessary. 

I'm still looking to get this merged =)

2023-04-16 07:07 UTC, LayZeeDK commented
Thank you, @JeanMeche. Are you an Angular Collaborator or just interested in this contribution? 😊

2023-04-16 07:13 UTC, LayZeeDK commented
@alan-agius4  @andrewseguin 
I would appreciate you approving this pull request to proceed.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/6364586/232279417-e19b6086-c7fc-47db-a2f4-c7bc67bd4cb0.png">

2023-04-16 08:41 UTC, alan-agius4 commented on aio/content/guide/versions.md
> +## LTS Angular versions
Maybe change this and the below link
to “actively supported versions”?  https://angular.io/guide/releases#actively-supported-versions

As technically version 15 is not in LTS.

2023-04-16 08:41 UTC, alan-agius4 approved these changes
LGTM, on small nit

2023-04-16 21:34 UTC, dscalzi commented on aio/content/guide/versions.md
> +## LTS Angular versions
```suggestion
## Actively supported versions
```

2023-04-17 11:41 UTC, alan-agius4 approved these changes
LGTM, thanks

2023-04-17 11:43 UTC, alan-agius4 commented
@LayZeeDK, looks like you co authored a commit with @dscalzi who did not sign a CLA.

2023-04-18 05:57 UTC, dscalzi commented
> @LayZeeDK, looks like you co authored a commit with @dscalzi who did not sign a CLA.

Send me a link and I'll sign it, no worries

2023-04-18 06:26 UTC, JeanMeche commented
The link is available in the CI reports just below : https://github.com/angular/angular/pull/48753/checks?check_run_id=12792458701

2023-04-18 19:24 UTC, dscalzi commented
All set

2023-04-19 14:07 UTC, jessicajaniuk commented
This PR was merged into the repository by commit aa960c7db4fb36912c196e3f16daf4ddfff1bbbc.

2023-04-19 14:07 UTC, closed without merging