docs: Fix small bugs and typos
angular/angular pull request #49138
Opened 2023-02-20 03:15 UTC by OnkarRuikar

Explanation for the changes:

1.`aio/content/examples/animations/src/app/animations.ts`
`aio/content/examples/animations/src/app/insert-remove.component.ts`
Animation duration is too short to see the opacity related changes. Increased the duration.
2. `aio/content/examples/animations/src/app/status-slider.component.ts`
They forgot to do the accessibility related change on line 35. Also `#754600` is `saddlebrown`, so used it to match other values.
3. `aio/content/examples/dependency-injection/src/app/injector.component.ts`
The video is no longer available.
4. `aio/content/examples/form-validation/src/app/reactive/hero-form-reactive.component.html`
`aio/content/examples/form-validation/src/app/template/hero-form-template.component.html`
The definition for the class`alert-danger` has not been provided anywhere in the example. Also, the compiler omits it from the output.
The documentation mentions of using `{{name.errors?.['forbiddenName'].value}}` in the output, but `Bob` is hard coded in the template instead.
5. `aio/content/examples/http/src/app/http-interceptors/caching-interceptor.ts`
Removed unused import.
6. `aio/content/guide/change-detection-skipping-subtrees.md`
As per the statement in `## Common change detection scenarios` following sections need to be subsections.
7. `aio/content/guide/event-binding-concepts.md`
The text doesn't match the sample code above.
8. `aio/content/guide/i18n-common-prepare.md`
We don't have to create a list for single point and repeat same explanation again.
9. `aio/content/guide/image-directive.md`
Avoid creating actual links for the demo urls.
10. `aio/content/guide/router-tutorial.md`
The explanation doesn't match sample code below. The route  `/crisis-center` comes into picture later in the tutorial.
11. `aio/content/guide/testing-utility-apis.md`
The table is broken due to these mysterious anchors. Also, the anchors haven't been used anywhere in the docs.
12. `aio/content/navigation.json`
Putting "Next Steps" at the end of the navigation list.

***
## PR Type
What kind of change does this PR introduce?
- [x] Documentation content changes

## Does this PR introduce a breaking change?
- [x] No

2023-02-21 14:24 UTC, hexiaokang approved these changes

2023-04-18 15:39 UTC, jessicajaniuk commented
@hexiaokang Could you rebase and resolve the conflicts? We should be able to review after that.

2023-04-19 03:00 UTC, OnkarRuikar commented on aio/content/navigation.json
> +                },
```suggestion
```
It has been removed in main branch.

2023-04-19 03:26 UTC, OnkarRuikar commented
@jessicajaniuk  I've resolved the conflicts.\
I hope most of the changes suggested in the PR still remain valid.

2023-04-19 14:51 UTC, jessicajaniuk reviewed
Overall these seem fine, but I'm a little confused as to why some of the changes are here. Once you respond to these, feel free to request my review again.

2023-04-19 14:51 UTC, jessicajaniuk commented on aio/content/examples/animations/e2e/src/app.e2e-spec.ts
> +    it('should be active with an saddlebrown background', async () => {
It's unclear to me why this is changed.

2023-04-19 14:51 UTC, jessicajaniuk commented on aio/content/examples/animations/src/app/animations.ts
> +          animate('500ms ease-out', style({ left: '100%', opacity: 0 }))
Is there a reason the timing here is being changed?

2023-04-20 05:49 UTC, OnkarRuikar commented on aio/content/guide/testing-utility-apis.md
> -<a id="testbed-inject"></a>
> Why are we removing these anchors? Are they not used anywhere?

Markdown tables do not support HTML tags. These anchor tags are breaking the rendered markdown tables: https://angular.io/guide/testing-utility-apis#testbed-class-summary

Also they are not being used anywhere in the repo: `rg "testbed-inject"` returns 0 results.

2023-04-20 06:35 UTC, OnkarRuikar commented on aio/content/examples/animations/src/app/status-slider.component.ts
> +      state('active', style({ backgroundColor: 'saddlebrown' })),
> Is there a reason we're switching from a hex color to saddlebrown in these examples?

This change is related to point no. 2 in the opening post. This is for example [animations](https://angular.io/generated/live-examples/animations/stackblitz.html). They changed color `orange` to `#754600`(saddlebrown) in #41385 to increase the contrast. Ideally they should've used color name and not hex value as all other used values are color names.

Color names are easy to grasp for readers. While reading the example for the first time I was a bit confused about why hex value among color names (there is no explanation for use of hex in the example description). Since `#754600` is almost equal to `saddlebrown` we can use the color name instead.

2023-04-20 06:38 UTC, OnkarRuikar commented on aio/content/examples/animations/e2e/src/app.e2e-spec.ts
> +    const activeColor = 'rgba(139, 69, 19, 1)';
> Is there a particular reason that these values were changed?

See comment https://github.com/angular/angular/pull/49138/files#r1172138990

2023-04-20 06:42 UTC, OnkarRuikar commented on aio/content/examples/animations/e2e/src/app.e2e-spec.ts
> +    it('should be active with an saddlebrown background', async () => {
They didn't update the color name  in #41385. `#754600` is not orange.

This change is related to https://github.com/angular/angular/pull/49138/files#r1172138990

2023-04-20 07:01 UTC, OnkarRuikar commented on aio/content/examples/animations/src/app/insert-remove.component.ts
> +        animate('1s', style({ opacity: 1 })),
This is related to point no. 1 in the OP. Related to [animations](https://angular.io/generated/live-examples/animations/stackblitz.html) live example `Insert/Remove` component.

100ms is too short to perceive the opacity change. As this being a demo app we can exaggerate values to make it easy to understand.

2023-04-20 07:04 UTC, OnkarRuikar commented on aio/content/examples/animations/src/app/animations.ts
> +          animate('500ms ease-out', style({ left: '100%', opacity: 0 }))
> Is there a reason the timing here is being changed?

This is related to https://github.com/angular/angular/pull/49138/files#r1172162528 .
It is apparent the component is moving from left to right, but with that short duration, change in opacity is not perceivable.

2023-04-20 07:37 UTC, OnkarRuikar commented on aio/content/examples/form-validation/src/app/template/hero-form-template.component.html
> +              Name cannot be {{name.errors?.['forbiddenName'].value}}.
> I see this has changed from the original error, but it's unclear why we're changing this behavior.

This is related to point no. 4 in the OP. Related to live example [form-validation](https://angular.io/generated/live-examples/form-validation/stackblitz.html). 

On form [validation documentation page](https://angular.io/guide/form-validation) it says:
> Each nested `<div>` can present a custom message for one of the possible validation errors. There are messages for required, [minlength](https://angular.io/api/forms/MinLengthValidator), and forbiddenName.

So why not use custom message to actually demonstrate it?\
Also, as per code on line 28 we already have the custom error. Why not use it instead of the hard coded value `bob`?

Hard coded value doesn't sound appropriate:
![wrong](https://user-images.githubusercontent.com/87750369/233293515-84677b5c-06b4-4cfc-8e7d-ff91f57f0e95.png)

vs custom value:
![correct](https://user-images.githubusercontent.com/87750369/233293610-65dfa6d3-a749-4a73-a59d-4a8021c3115f.png)

***

If we do not want to do this then we need to correct the error message as:
```diff
-- Name cannot be Bob.
++ Name cannot contain 'bob'.
```

2023-04-20 07:39 UTC, OnkarRuikar commented on aio/content/examples/form-validation/e2e/src/app.e2e-spec.ts
> +  const emsg = 'Name cannot be Bobby.';
> This is incorrect. The actual page being tested has the error "Name cannot be Bob."

This change is related to https://github.com/angular/angular/pull/49138/files#r1172197928 .
If we drop that then we'll drop this as well.

2023-04-20 08:01 UTC, OnkarRuikar commented on aio/content/examples/form-validation/src/app/reactive/hero-form-reactive.component.html
> +              class="alert">
This is related to point no. 4 in the OP. Related to live example [form-validation](https://angular.io/generated/live-examples/form-validation/stackblitz.html).

> Why are we removing the `alert-danger` class here? That typically indicates a level of severity of the alert.

The `alert-danger` class is a `Material` specific thing and the example doesn't use it. In the example the danger color has been sort of merged in `alert` class:

https://github.com/angular/angular/blob/c029c678d9587d3bbeeb60720b226c83ec52bedf/aio/content/examples/form-validation/src/assets/forms.css#L10-L15

The definition for the class `alert-danger` has not been provided anywhere in the example. Also, the compiler omits it from the output:\
`<div _ngcontent-iag-c0="" class="alert"><div _ngcontent-iag-c0="">Name cannot be Bob.</div></div>`

Not everyone starting to learn Angular knows about Material. So this class adds a lot of confusion.

2023-04-20 14:50 UTC, jessicajaniuk approved these changes
LGTM

2024-01-26 19:31 UTC, JeanMeche commented
Looks like this needs a rebase to fix the conflits. Could you do that. ?

2024-01-27 00:11 UTC, OnkarRuikar commented
> Looks like this needs a rebase to fix the conflits. Could you do that. ?

Then why did you close the PR? :confused:

2024-01-28 07:22 UTC, OnkarRuikar commented
@JeanMeche I've resolved the conflicts.

2024-02-01 18:56 UTC, JeanMeche commented on aio/content/navigation.json
> +          "title": "Español",
Could you remove this entry from the list, this site is unmaintained.

2024-02-01 19:58 UTC, JeanMeche requested changes
Cf my last comment.

2024-02-02 02:46 UTC, OnkarRuikar commented on aio/content/navigation.json
> +          "title": "Español",
@JeanMeche done

2024-02-22 00:15 UTC, closed without merging