refactor(core): separate LView-level and TView-level destroy hooks
angular/angular pull request #49158
Opened 2023-02-22 11:15 UTC by pkozlowski-opensource

2023-02-22 16:04 UTC, atscott requested changes

2023-02-22 16:39 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> -    for (let i = lastLCleanupIndex + 1; i < lCleanup.length; i++) {
oh, good catch, thnx!

2023-02-22 17:22 UTC, atscott commented on packages/core/src/linker/destroy_ref.ts
> +  return new NodeInjectorDestroyRef(getLView());
When Dylan and I were working on this, we found bit of code for injecting renderer:
https://github.com/angular/angular/blob/02cd490115f7b3ce4a8d78e044127bee2582fc91/packages/core/src/render/api.ts#L240-L245
So I think you're likely getting the wrong `LView` here. I think you might want to add another test to your suite that includes a child component like we did [here](https://github.com/angular/angular-private/commit/b364ef865142edefe5a01dd78e062aac5abb30b6#diff-5dcde40de520324465c5de4a3fd03b0b5cf6273d09d48eeec81ad305f4fc74e0) (`it('can inject into a child component')`)

2023-02-22 17:39 UTC, pkozlowski-opensource commented on packages/core/src/linker/destroy_ref.ts
> +  return new NodeInjectorDestroyRef(getLView());
Interesting. I've added the mentioned test and it seems to pass with the implementation from this PR.

2023-02-22 18:14 UTC, eneajaho commented on packages/core/src/linker/destroy_ref.ts
> + * - a component or en embedded view;
```suggestion
 * - a component or an embedded view
```

2023-02-22 21:25 UTC, jelbourn commented on packages/core/src/linker/destroy_ref.ts
> + * DestroyRef represents a concept of lifecycle scope where destroy callbacks can be registered.
```suggestion
 * `DestroyRef` lets you set callbacks to run when a component or directive is destroyed.
```

I would make the description a bit more practically-oriented

2023-02-22 21:25 UTC, jelbourn commented on packages/core/src/linker/destroy_ref.ts
> +  abstract onDestroy(callback: () => void): void;
Could the injected token just _be_ this function?

2023-02-23 09:59 UTC, pkozlowski-opensource commented on packages/core/src/linker/destroy_ref.ts
> + * - a component or en embedded view;
Thnx!

2023-02-23 10:13 UTC, pkozlowski-opensource commented on packages/core/src/linker/destroy_ref.ts
> + * DestroyRef represents a concept of lifecycle scope where destroy callbacks can be registered.
Let's chat about this one. We definitively should include injectors here as this is the main point of this API - to unify the concept of "cleanup" across components and injectors. Also, not sure about mentioning component / directive destruction: it is really about a view boundary.

2023-02-23 16:39 UTC, pkozlowski-opensource commented on packages/core/src/linker/destroy_ref.ts
> +  return new NodeInjectorDestroyRef(getLView());
@atscott I've looked into it today and we are good with the implementation in this PR.

The tl;dr; is that we want to scope cleanup scope to the "parent" LView - or, to be precise - to the view that "owns" a host element of a given component. Trying to use the LView of a component's _template_ wouldn't buy us anything as there is no public-API operation of "destroy this template". Destroying a component means destroying its host element and this happens with the view that own the said host element.

2023-02-24 15:19 UTC, Harpush commented
@pkozlowski-opensource Does this allow for destroy logic in inject based functions without hacks (`inject(ChangeDetectorRef) as ViewRef`)? If it is please make it public API.

2023-02-25 08:04 UTC, gmfun commented
> @pkozlowski-opensource Does this allow for destroy logic in inject based functions without hacks (`inject(ChangeDetectorRef) as ViewRef`)? If it is please make it public API.

inject(DestroyRef).onDestroy is available now as per the tests

2023-02-25 20:22 UTC, elgreco247 commented on packages/core/src/linker/destroy_ref.ts
> + * - injectors (instances of `EnvironnementInjector`).
typo: should be 'EnvironmentInjector'

2023-02-27 17:11 UTC, atscott approved these changes

2023-02-27 17:14 UTC, atscott approved these changes
reviewed-for: public-api, circular-deps

2023-02-28 11:59 UTC, pkozlowski-opensource commented on packages/core/src/linker/destroy_ref.ts
> +  abstract onDestroy(callback: () => void): void;
Resolved offline in a design doc.

2023-02-28 12:38 UTC, pkozlowski-opensource commented on packages/core/src/linker/destroy_ref.ts
> + * - injectors (instances of `EnvironnementInjector`).
Fixed, thnx!

2023-02-28 16:54 UTC, jelbourn commented on packages/core/src/linker/destroy_ref.ts
> + * DestroyRef represents a concept of lifecycle scope where destroy callbacks can be registered.
My motivation here is that the bit "concept of a lifecycle" is odd/confusing. 

Maybe something roughly like
```markdown
`DestroyRef` lets you set callbacks to run for any cleanup or destruction behavior.
The scope of this destruction depends on where `Destroy` is injected. If `DestroyRef`
is injected in a component or directive, the callbacks run when that component or
directive is destroyed. If <other case>
```

2023-02-28 16:54 UTC, jelbourn commented on packages/core/src/linker/destroy_ref.ts
> +export abstract class DestroyRef {
Why make this abstract if there's only one implementation?
(add an inline comment to explain?)

2023-02-28 16:54 UTC, jelbourn commented on packages/core/src/render3/instructions/shared.ts
> +  ngDevMode &&
Add a comment here that explains the context behind this check?

2023-02-28 16:54 UTC, jelbourn commented on packages/core/src/render3/interfaces/view.ts
> +export const ON_DESTROY_HOOKS = 22;
I know it wasn't like this before, but it would be nice if there was a comment with some context for these index constants as to what they represent in the LView. 

(just for the newly added one)

2023-02-28 16:54 UTC, jelbourn commented on packages/core/src/render3/interfaces/view.ts
> +  [ON_DESTROY_HOOKS]: Array<() => void>|null;
If would be convenient to mention here _how_ the user defines these callsbacks. This would be useful for newcomers to this codebase.

2023-02-28 16:54 UTC, jelbourn commented on packages/core/src/render3/node_manipulation.ts
> +    }
```suggestion
    for (const destroyHookFn of destroyHooks) {
      ngDevMode && assertFunction(destroyHooksFn, 'Expecting destroy hook to be a function.');
      destroyHooksFn();
    }
```
Why not use a `for of` loop?

2023-02-28 16:54 UTC, jelbourn commented on packages/core/test/acceptance/destroy_ref_spec.ts
> +  describe('environnement injector', () => {
```suggestion
  describe('for environment injectors', () => {
```
nit: could make this read like a sentence (and similar below)

(https://github.com/angular/angular/blob/main/docs/CODING_STANDARDS.md#testing)

2023-02-28 17:08 UTC, alxhub approved these changes

2023-02-28 18:01 UTC, dylhunn approved these changes
Looks very nice.
reviewed-for: public-api, fw-core

2023-02-28 18:12 UTC, pkozlowski-opensource commented on packages/core/src/di/r3_injector.ts
> +    if (token.hasOwnProperty('__NG_ENV_ID__')) {
Oh, thnx! Changed!

2023-02-28 18:14 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +    }
Mostly to avoid the iterator protocol as it is reasonably "hot" code path and I didn't feel like it negatively impacts readability here. Would prefer to leave it as-is if you don't mind.

2023-02-28 18:19 UTC, pkozlowski-opensource commented on packages/core/src/linker/destroy_ref.ts
> +export abstract class DestroyRef {
Added, thnx for the nudge!

2023-02-28 18:34 UTC, pkozlowski-opensource commented on packages/core/src/render3/interfaces/view.ts
> +export const ON_DESTROY_HOOKS = 22;
Those are documented on the `LView` interface.

2023-02-28 18:37 UTC, pkozlowski-opensource commented on packages/core/src/linker/destroy_ref.ts
> + * DestroyRef represents a concept of lifecycle scope where destroy callbacks can be registered.
👍

2023-02-28 19:14 UTC, pkozlowski-opensource commented on packages/core/test/acceptance/destroy_ref_spec.ts
> +  describe('environnement injector', () => {
👍

2023-02-28 19:30 UTC, alxhub approved these changes
Reviewed-for: size-tracking

2023-02-28 19:49 UTC, AndrewKushnir reviewed
FYI, just a minor (non-blocking) comment, which can be addressed in a followup PR (if needed). I will proceed with merging this PR.

2023-02-28 19:49 UTC, AndrewKushnir commented on packages/core/src/linker/destroy_ref.ts
> + */
```suggestion
 * directive is destroyed. Otherwise the callbacks run when a corresponding injector is destroyed.
 *
 * @publicApi
 */
```

2023-02-28 19:49 UTC, AndrewKushnir commented on packages/core/src/linker/destroy_ref.ts
> + */
Do we want "Developer Preview" label here as well?

2023-02-28 19:51 UTC, pkozlowski-opensource commented on packages/core/src/linker/destroy_ref.ts
> + */
Actually, I'm not sure :-) I _do_ think that we might want to have this API regardless of other dev-preview work where it is going to be used primarily. 

But yep, this is good discussion to be had! I would appreciate if we could get it in (was trying to make it green for a while...) and decide on the API flag in a separate PR.

Thnx for checking @AndrewKushnir !

2023-02-28 19:52 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 0f5c8003ccd1a75516d6a0e31cdb752d031ec430.

2023-02-28 19:52 UTC, closed without merging

2023-03-17 08:13 UTC, ajafff commented on goldens/public-api/core/index.md
> +    abstract onDestroy(callback: () => void): void;
how would I unregister the callback to avoid leaking memory in long-lived `DestroyRef`s?