fix(common): make Location.normalize() return the correct path when the base path contains characters that interfere with regex syntax.
angular/angular pull request #49181
Opened 2023-02-23 16:50 UTC by wartab

Fix the function stripping the base path from the URL, as the current implementation uses the base path as part of a regex, which wrongly makes paths fails that contain characters such as a parenthesis (example: C:/Users/MyUser(Test)/project).

Fixes #49179

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

When an Angular project build is served from a base path containing characters that are special characters in a regex, the Angular router does not work anymore. (for example C:/Users/MyUser(Test)/my-project).
Issue Number: 49179

## What is the new behavior?
Paths containing such characters will not break routing anymore.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x ] No

## Other information

2023-02-23 17:00 UTC, atscott commented
This is now a bandaid on a bandaid on a bandaid. I think the best approach here would be to revert the change which caused the regression and resolve the issue more completely if possible at a later time: https://github.com/angular/angular/blob/3d589d8bdeb81e953d1c3b6516cebcf07c214f52/packages/common/src/location/location.ts#L71-L76

2023-02-23 17:49 UTC, atscott commented
Actually, this fix seems reasonable. It's pretty close to what the revert would be anyways, but with some additional logic to fix the old bug again.

2023-02-23 18:26 UTC, atscott requested changes

2023-02-23 18:26 UTC, atscott commented on packages/common/src/location/location.ts
> +    url;
This code is a bit confusing, especially `array.includes`. 

What do you think of this instead?
```suggestion
  const strippedBasePath = url.substring(basePath.length);
  const nonSegmentTerminator = new RegExp(`[^/;?#]`);
  // Ensure that the stripped path does not start with a character that's not a segment terminator.
  // This is because the URL does not technically match the base path.
  // i.e. if base path is a/b/c and the URL is a/b/cat.
  return nonSegmentTerminator.test(strippedBasePath[0]) ? url : strippedBasePath;
```

2023-02-23 22:57 UTC, wartab commented
Yes, my fix had your changes in mind, it was just to address the problem our customers were facing, because they somehow thought it was a good idea to add parenthesis to their username in Windows.

I don't have a preference for the solution, I generally tend to avoid regular expressions and operations that could be avoided when they are not needed, which is why I suggested my fix.

2023-02-24 00:26 UTC, atscott approved these changes

2023-02-24 00:35 UTC, jessicajaniuk approved these changes

2023-02-27 16:56 UTC, atscott commented
[Global internal tests](https://fusion2.corp.google.com/presubmit/tap/511810902/OCL:511810902:BASE:511847196:1677215217389:b2ed37d3/targets) came back green as well

2023-02-27 18:02 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 3c9d49a4d7304202d60eeed97b2bb00686c079d0.

2023-02-27 18:02 UTC, closed without merging