refactor(compiler): handle #24571 todos.
angular/angular pull request #49220
Opened 2023-02-26 22:39 UTC by JeanMeche

I looking to tackle the ~200ish TODOs related to #24571 to finally close it. 

This commit removes the remaining ones in compiler code base

## Does this PR introduce a breaking change?

- [x] No

2023-02-26 22:40 UTC, JeanMeche commented on packages/compiler/test/integration_spec.ts
> -             // TODO(issue/24571): remove '!'.
It's acceptable to have this todo removed without comment : Its common to have non-null assertions on inputs in spec files.

2023-02-27 18:02 UTC, atscott requested changes

2023-02-27 18:24 UTC, atscott approved these changes

2023-04-15 22:56 UTC, JeanMeche commented
@dgp1130 By any chance could you have a look in the next few days ?

2023-04-18 00:41 UTC, AndrewKushnir approved these changes

2023-04-18 00:45 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:524997685:BASE:524997707:1681778732713:f2e2a14a).

2023-04-18 16:30 UTC, closed without merging