refactor(compiler): required inputs prerequisite refactors
angular/angular pull request #49333
Opened 2023-03-06 12:16 UTC by crisbeto

Based on the discussion in https://github.com/angular/angular/pull/49304#discussion_r1124732608. Reworks how inputs are stored throughout the compiler to allow for required information to be stored alongside them. The refactor introduces a new `ClassInputPropertyMapping` class which is similar to the existing `ClassPropertyMapping`, but with the ability to store additional information about the mapping which may be handy for future features as well.

2023-03-07 15:05 UTC, crisbeto commented on packages/compiler-cli/src/ngtsc/metadata/src/property_mapping.ts
> + * A binding of a directive that has both a named JavaScript class property on a component
The diff in this file is pretty large, but the behavior is the same as before. I just split up the input-specific and output-specific code from `ClassPropertyMapping` into two separate classes so that inputs can be marked as required in the next PR.

2023-03-07 15:09 UTC, crisbeto commented on packages/compiler/src/render3/view/api.ts
> +  inputs: {[field: string]: {alias: string, classPropertyName: string}|string};
Note here: technically we should be able to remove the `|string` for the values, but the way `ngUpgrade` maps inputs between AngularJS and Angular components depends specifically on the `string` signature further downstream. I decided to keep it for now, because I want to avoid large refactors in `ngUpgrade` and because the string signature doesn't require much code to support.

2023-03-07 15:09 UTC, crisbeto commented on packages/core/test/render3/jit/declare_component_spec.ts
> +  expect(actual.selectors).withContext('selectors').toEqual(expectation.selectors);
I added all of these `withContext` calls to make the failures easier to read.

2023-03-07 17:47 UTC, crisbeto commented
[Passing TGP](http://test/OCL:514674933:BASE:514760641:1678211173388:60758be7).

2023-03-08 20:41 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/directive/src/shared.ts
> +    const value = inputsArray[i];
Will `i` end up being used besides reading from `inputsArray` with required inputs? If not, this could become a `for-of` loop

2023-03-08 20:41 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/directive/src/shared.ts
> +    const [publicName, fieldName] = parseMappingString(value);
I see both `public` and `alias` being used now, would it make sense to always switch to `alias`?

2023-03-08 20:41 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/metadata/src/property_mapping.ts
> +  private requiredBindingNames = new Set<BindingPropertyName>();
Did you intent to include this in this PR?

2023-03-08 20:41 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/metadata/src/property_mapping.ts
> +  readonly alias: BindingPropertyName;
We're still all-over-the-place with naming. Since this PR is already large I wouldn't want to introduce additional renames, but it wouldn't hurt to go over this in another pass to become more consistent with naming.

2023-03-08 20:41 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/metadata/src/property_mapping.ts
> +abstract class BasePropertyMapping implements InputOutputPropertySet {
I'm not sure I like this split/base class setup, as it seems simpler to have something like the following:

```ts
class ClassPropertyMapping<P extends PropertyMapping> implements InputOutputPropertySet {}
```

Methods like `hasRequiredBindingName` can then no longer exist on this class, and have to be implemented using `getByBindingPropertyName().some(mapping => mapping.required)`, but I'd argue this is desirable: the property mapping's concern is about providing a two-way association of alias/field names and their metadata, _not_ interpreting that metadata.

I might be missing something here.

2023-03-08 20:41 UTC, JoostK commented on packages/compiler/src/jit_compiler_facade.ts
> +    const value = inputs![key];
```suggestion
    const value = inputs[key];
```

2023-03-08 20:41 UTC, JoostK commented on packages/compiler/src/compiler_facade_interface.ts
> +  inputs: (string|{name: string, alias?: string})[];  // TODO(required-inputs): add required flag
Can we normalise this to just the object-literal type? I don't quite see why we retain the bare `string` type here.

2023-03-08 20:41 UTC, JoostK commented on packages/compiler/src/render3/view/compiler.ts
> +    return ({key, value: o.literal(typeof value === 'string' ? value : value.alias), quoted: true});
This appears to have been pulled from an arrow function's expression body, but now that it's a return statement the parens are redundant:

```suggestion
    return {key, value: o.literal(typeof value === 'string' ? value : value.alias), quoted: true};
```

2023-03-08 21:53 UTC, crisbeto commented on packages/compiler-cli/src/ngtsc/metadata/src/property_mapping.ts
> +  private requiredBindingNames = new Set<BindingPropertyName>();
I left it here for myself since this ties into the required inputs PR.

2023-03-08 21:57 UTC, crisbeto commented on packages/compiler-cli/src/ngtsc/metadata/src/property_mapping.ts
> +abstract class BasePropertyMapping implements InputOutputPropertySet {
I agree that this is a little janky, but I wanted to avoid reusing the exact same data structure both for inputs and outputs since outputs are likely to stay as they are while we'll probably add some more properties for the inputs. The problem with your approach is that the mapping gets constructed from a `Record<string, string|[string, string]>` so there's no place to encode the additional field.

2023-03-08 21:58 UTC, crisbeto commented on packages/compiler/src/compiler_facade_interface.ts
> +  inputs: (string|{name: string, alias?: string})[];  // TODO(required-inputs): add required flag
That's what I was referring to here: https://github.com/angular/angular/pull/49333#discussion_r1128017957.

2023-03-08 22:40 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/metadata/src/property_mapping.ts
> +abstract class BasePropertyMapping implements InputOutputPropertySet {
Yeah, that would need to become `Record<string, P>`, where `<P extends PropertyMapping>`. I'm not sure how that pans out for real.

2023-03-08 22:42 UTC, JoostK commented on packages/compiler/src/compiler_facade_interface.ts
> +  inputs: (string|{name: string, alias?: string})[];  // TODO(required-inputs): add required flag
I already thought so, but that comment is for code in the compiler, whereas this is the JIT bridge to the compiler which I suppose is not concerned with `ngUpgrade` usages?

2023-03-10 17:58 UTC, alxhub requested changes

2023-03-10 17:58 UTC, alxhub commented on packages/compiler/src/render3/view/api.ts
> +  inputs: {[field: string]: {alias: string, classPropertyName: string}|string};
I don't think we should change the format of generated code at all - the current `string|[string, string]` is optimized for code size. Switching to an object literal with named fields definitely makes it more readable, but is likely a significant size regression.

2023-03-10 18:07 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/metadata/src/property_mapping.ts
> +abstract class BasePropertyMapping implements InputOutputPropertySet {
+1 to this suggestion - I like the idea of a generic data structure for these property mappings, which allows for additional metadata to be present on the metadata it stores.

2023-03-10 20:18 UTC, crisbeto commented on packages/compiler/src/render3/view/api.ts
> +  inputs: {[field: string]: {alias: string, classPropertyName: string}|string};
FWIW this isn't the generated code, it's just the common interface between AOT and JIT. The generated code is the same as before.

2023-03-13 13:07 UTC, crisbeto commented on packages/compiler-cli/src/ngtsc/metadata/src/dts.ts
> +function readInputsType(type: ts.TypeNode): {[field: string]: InputPropertyMapping} {
This is currently a placeholder, but it'll have some more input-specific logic in the next PR.

2023-03-13 13:49 UTC, crisbeto commented
@JoostK @alxhub I've reworked the PR based on your feedback. Can you take another look?

2023-03-13 18:36 UTC, JoostK approved these changes
I like the cleanup around `ClassPropertyMapping`! Some nits for your consideration but otherwise LGTM

2023-03-13 18:36 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/directive/src/shared.ts
> +      bindingPropertyName: bindingPropertyName ?? fieldName,
Is this fallback necessary? `bindingPropertyName` is non-nullable, so something appears off here.

2023-03-13 18:36 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/annotations/directive/src/symbol.ts
> +  return isInputOrOutputEqual(current, previous) && current.required === previous.required;
For a future PR where required inputs are added, we should add a test for this in `packages/compiler-cli/test/ngtsc/incremental_semantic_changes_spec.ts`.

2023-03-13 18:36 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/metadata/src/property_mapping.ts
> +  // TODO: rename this method?
Is this pending? I don't really have suggestions for an alternative name here.

2023-03-13 18:36 UTC, JoostK commented on packages/compiler-cli/src/ngtsc/metadata/src/property_mapping.ts
> +    for (const [_classPropertyName, inputOrOutput] of this.forwardMap.entries()) {
Consider iterating over `.values()` to avoid needing to destructure and ignoring the key.

2023-03-13 18:36 UTC, JoostK commented on packages/compiler/src/jit_compiler_facade.ts
> +      const [bindingPropertyName, fieldName] = parseMappingString(value);
Rename `fieldName` to `classPropertyName` here to use shorthand property assignment in the line below.

2023-03-13 19:20 UTC, alxhub approved these changes

2023-03-13 19:20 UTC, alxhub commented on packages/compiler/src/render3/view/util.ts
>        minifiedName = declaredName = key;
Nit: I think it's more readable to not use assignment chaining (if we aren't optimizing for conciseness / code size).

2023-03-13 19:20 UTC, alxhub commented on packages/compiler/src/render3/view/api.ts
> +  inputs: {[field: string]: {classPropertyName: string, bindingPropertyName: string}};
I would suggest creating the interface:

```typescript
export interface R3InputMetadata {
  classPropertyName: string;
  bindingPropertyName: string;
}
```

Then the `inputs` declaration could become:
```suggestion
  inputs: R3InputMetadata[],
```

Using an array instead of an object also makes the downstream iteration easier, and avoids the need to do `Object.key` operations to iterate it.

2023-03-13 19:20 UTC, alxhub commented on packages/compiler/src/render3/view/compiler.ts
> +      value: o.literal(typeof value === 'string' ? value : value.bindingPropertyName),
Can `typeof value` be a `string` here? We changed the type to always be always be an object (instance of `R3InputMetadata`).

2023-03-13 19:20 UTC, alxhub commented on packages/compiler/src/render3/view/util.ts
> +export function conditionallyCreateMapObjectLiteral(map: Record<string, string|{
Nit: we should name this something to do with inputs/outputs, for clarity.

2023-03-14 11:46 UTC, crisbeto commented
[Almost passing TGP](http://test/OCL:514674933:BASE:516481213:1678791604448:ffb850b9). There's one unrelated failure.

2023-03-14 16:27 UTC, alxhub commented
This PR was merged into the repository by commit be97c8702319c9e1467c4fddba868e8f23ebe159.

2023-03-14 16:27 UTC, closed without merging