feat(core): Provide a diagnostic for missing Signal invocation in template interpolation.
angular/angular pull request #49660
Opened 2023-03-31 16:23 UTC by JeanMeche

To improve DX for beginners, this commit ads an extended diagnostic for Signals in template interpolations.

See #49657

## PR Type
What kind of change does this PR introduce?

- [x] Feature

## Does this PR introduce a breaking change?

- [x] No

2023-03-31 18:22 UTC, dylhunn commented
This sounds like a great idea for a template diagnostic! Looking forward to it being ready for review/discussion!

2023-04-02 10:48 UTC, elgreco247 commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/interpolated_signal_not_called/index.ts
> + * Ensures that the special attribute `ngSkipHydration` is not a binding and has no other
Comment copy'n'pasted?

2023-04-04 02:25 UTC, dylhunn commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/interpolated_signal_not_invoked/index.ts
> +                /* can this condition be improved ? */
Checking the `escapedName` seems totally reasonable to me.

2023-04-04 02:25 UTC, dylhunn commented on packages/compiler-cli/src/ngtsc/typecheck/extended/checks/interpolated_signal_not_invoked/index.ts
> +              const errorString = `${item.name} is a function should be invoked : ${item.name}()`;
Can we clean up this error string a bit? Maybe mention that it's a signal?

2023-04-04 02:25 UTC, dylhunn commented
@AndrewKushnir This basically looks OK to me. I can't approve it for fw-compiler though, and it would be nice to get this improvement in v16!

2023-04-04 18:50 UTC, dylhunn commented
@JeanMeche Since this visits every node in the AST, what about expressions like `fn(signalA)`? It seems like this diagnostic will still fire. But you might sometimes want to actually pass the signal, as opposed to just reading it?

2023-04-04 19:58 UTC, JeanMeche commented
@dylhunn This is already covered, I'll add a test though !

2023-04-04 22:54 UTC, dylhunn approved these changes

2023-04-05 17:34 UTC, dylhunn commented
@crisbeto Highlighted some potential concerns before we merge this. Let's target v16.1.

1. It only checks interpolations, not things like [attr.foo]="signal"
2. It doesn’t check host bindings because extended diagnostics don’t have access to them.
3. Would be better to fin a cleaner way to detect a Signal

2023-08-05 21:11 UTC, JeanMeche commented
@dylhunn Do you see other kinds of bindings besides of attributes bindings that should be coverd by this diagnostic ? 

Note: since 16.2 is now in RC, this will shift to v17.

2023-10-05 14:07 UTC, pkozlowski-opensource commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/interpolated_signal_not_invoked/interpolated_signal_not_invoked_spec.ts
> +  describe('Interpolated Signal ', () => {
I would love to see the following cases covered in tests / diagnostic:
* making sure that the diagnostic works with both signals and computed (this should be fine already as computed have the signal type, but a test wouldn't hurt);
* interpolations in bindings (ex. `<div id="{{signal}}">` - those should be consistent with the text node interpolations

I'm also curious about your thoughts on a diagnostic that tries to figure out similar signal access patterns in property bindings.

2023-10-05 14:07 UTC, pkozlowski-opensource requested changes
LGTM overall but I think that we should add more tests for the computed / property / attribute interpolation cases (see inline comments).

2023-10-09 16:45 UTC, dylhunn commented
@JeanMeche Would you be interested in trying to land this one in v17? I think @pkozlowski-opensource had some feedback he wanted to go over, mainly around the above comments. If you're interested in prioritizing this, I can try to push it forward!

2023-10-09 19:59 UTC, JeanMeche commented
@pkozlowski-opensource I've added support for bindings checks. Let me know what you think of it !

2023-10-10 10:58 UTC, pkozlowski-opensource commented on packages/compiler-cli/src/ngtsc/typecheck/extended/test/checks/signal_not_invoked/signal_not_invoked_spec.ts
> +    it('should not produce a warning', () => {
nit: should not produce a warning when a signal getter is invoked

2023-10-10 11:05 UTC, pkozlowski-opensource commented
@JeanMeche  I was assuming that the idea is to limit the check to interpolations, that is, to the following situations:
* `<div>{{sig}}</div>`  (interpolation in a text node)
* `<img src="/path/{{sig}}.png">` (interpolation in property bindings)
* `<img attr.src="/path/{{sig}}.png">` (interpolation in attribute bindings)

The regular binding (ex.: `<div [myDirectiveInput]="sig">` is tricker as there are legitimate cases where someone might want to pass a reference to a signal (instead of unwrapping its value).

2023-10-10 11:25 UTC, devversion commented
> The regular binding (ex.: <div [myDirectiveInput]="sig"> is tricker as there are legitimate cases where someone might want to pass a reference to a signal (instead of unwrapping its value).

Just to capture this here: And in those cases, the normal type-checking is already sufficient and will complain if e.g. `myDirectiveInput` does not take a `Singal<T>`

2023-10-10 13:06 UTC, pkozlowski-opensource approved these changes

2023-10-10 16:15 UTC, dylhunn commented
@pkozlowski-opensource @JeanMeche Just to confirm, the regular binding case `<div [myDirectiveInput]="sig">` Pawel describes does not produce a diagnostic, right?

2023-10-10 16:21 UTC, JeanMeche commented
> the regular non-interpolated binding case `<div [myDirectiveInput]="sig">` Pawel describes does not produce a diagnostic, right?

No, it won't produce a diagnostic. The typechecker should do that.

2023-10-10 16:25 UTC, dylhunn approved these changes
For pullapprove:

reviewed-for: fw-compiler, public-api

2023-10-10 18:55 UTC, closed without merging