feat(common): add component input support for NgComponentOutlet
angular/angular pull request #49735
Opened 2023-04-06 16:48 UTC by HyperLife1119

This commit adds component input support for NgComponentOutlet.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-04-06 18:36 UTC, ajafff commented on packages/common/src/directives/ng_component_outlet.ts
> +        this.differ ??= this.differs.find(inputs).create();
why would you even need a differ? `setInput` already compares the current and the previous value to not do unnecessary change detection

2023-04-06 22:34 UTC, atscott requested changes

2023-04-06 22:34 UTC, atscott commented on packages/common/src/directives/ng_component_outlet.ts
> +    }
```
    for (const [key, value] of Object.entries(this. ngComponentOutletInputs)) {
      this.componentRef.setInput(key, value);
    }
```

Arguably we really should throw an error if there's an input that doesn't match rather than filtering it out.

2023-04-06 22:34 UTC, atscott commented on packages/common/src/directives/ng_component_outlet.ts
> +  @Input() ngComponentOutletInputs?: Record<string, any>;
```suggestion
  @Input() ngComponentOutletInputs?: Record<string, unknown>;
```

2023-04-06 22:34 UTC, atscott commented on packages/common/src/directives/ng_component_outlet.ts
> +        this.differ ??= this.differs.find(inputs).create();
This behavior was added in a recent change. Totally understandable if it was missed. You're right though, the differ shouldn't be necessary anymore.

2023-04-06 22:34 UTC, atscott commented on packages/examples/common/ngComponentOutlet/ts/module.ts
> +  myInputs = {label: 'Complete'};
```suggestion
  myInputs = {'label': 'Complete'};
```

The name should be quoted or a compiler with property renaming might come by and break things since the mirror _won't_ have renamed properties for the "templateName"

2023-04-07 01:55 UTC, HyperLife1119 commented on packages/common/src/directives/ng_component_outlet.ts
> +        this.differ ??= this.differs.find(inputs).create();
I know `setInput()` will compare the current value with the previous value, let's consider this situation:

```ts
@Component(...)
class Cmp {
  @Input() a?: any;
  @Input() b?: any;
  @Input() c: any = 3;
}

@Component({
  template: `<ng-container *ngComponentOutlet="cmp; inputs: inputs" />`
})
class TestCmp {
  cmp = Cmp;
  inputs = { a: 1, b: 2 };
}
```
Without using differ, we can't get all changed key names. 

When the inputs change from `{ a: 1, b: 2 }` to `{ a: 1 }`, after running the change detection, the `b` input value of the component in the outlet is still 2, if this is what we want, we can completely remove the differ.

2023-04-07 04:16 UTC, destus90 commented
Should partially close https://github.com/angular/angular/issues/15360

2023-04-07 15:18 UTC, ajafff commented on packages/common/src/directives/ng_component_outlet.ts
> +        this.differ ??= this.differs.find(inputs).create();
since we're talking about diffing: other builtin directives (e.g. ngClass, ngStyle, ngFor) assume input object to be mutable and therefore do the diffing in `ngDoCheck` lifecycle hook

I really don't like that, since this defeats the purpose of OnPush. Anyways, it should probably be consistent ...

2023-04-07 15:23 UTC, ajafff commented on packages/common/src/directives/ng_component_outlet.ts
> +    }
AFAICT the error reporting is already built into `setInput`, so there's no need for each call-site to duplicate that

2023-04-08 06:41 UTC, HyperLife1119 commented
I resolved all and updated the public API.

2023-04-08 16:42 UTC, gmfun reviewed
Shouldn't it check if key is an input in the component. Because if it is not, it will throw error. We can use ComponentMirror to check.

2023-04-11 16:35 UTC, atscott approved these changes

2023-04-17 19:00 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2023-04-17 19:12 UTC, jessicajaniuk approved these changes
reviewed-for: public-api

2023-04-17 19:14 UTC, jessicajaniuk commented
@HyperLife1119 looks like this needs a bit of cleanup before we can merge. Can you address the size ci check?

2023-04-17 19:16 UTC, JeanMeche commented
@jessicajaniuk AFAIK all `ci/angular: size` were all failing last week. It's probably not an issue.

2023-04-17 19:17 UTC, atscott commented
Adding blocked label to ensure @pkozlowski-opensource gets a chance to review

2023-04-17 19:18 UTC, AndrewKushnir commented
FYI I've pushed a rebase, which would rerun the CI and likely fix the `size` CI job.

2023-04-21 07:56 UTC, JeanMeche commented on packages/common/src/directives/ng_component_outlet.ts
> +      this._componentRef!.setInput(key, value);
nit: you could pass `_componentRef` and `ngComponentOutletInputs` as argument to remove the non-null assertions.

2023-04-21 10:56 UTC, pkozlowski-opensource requested changes
I think that logic here is incomplete and requires more tests / implementation - see inline comments.

2023-04-21 10:56 UTC, pkozlowski-opensource commented on packages/common/src/directives/ng_component_outlet.ts
> +    } else if (this._componentRef && inputsChange && inputs) {
I don't think that this logic is correct - what will happen in the following case:

```html
<ng-container *ngComponentOutlet="componentTypeExpression; inputs: inputsExpression;">
```

and inside TS code someone does:

```typescript
inputsExpression.foo = 'changed';
```

In other words - the _content_ and / or _shape_ of the inputs object literal can change _without_ changing identity of the said object.

We absolutely need tests / implementation for those cases - NgClass could be used as inspiration.

2023-04-21 16:53 UTC, HyperLife1119 commented on packages/common/src/directives/ng_component_outlet.ts
> +    } else if (this._componentRef && inputsChange && inputs) {
My idea is to use `KeyValueDiffer` to diff `inputs` in the `ngDoCheck` lifecycle, and then apply the diff result to the outlet component.

Prior to this, @ajafff had his own [opinion](https://github.com/angular/angular/pull/49735#discussion_r1160134288) on whether to use differ.

2023-04-21 17:03 UTC, pkozlowski-opensource commented on packages/common/src/directives/ng_component_outlet.ts
> +    } else if (this._componentRef && inputsChange && inputs) {
Yeh.... I kind of see that we do "design in the PR" which is not ideal.

What would you your preferred approach and reasoning for it?

2023-04-21 17:38 UTC, HyperLife1119 commented on packages/common/src/directives/ng_component_outlet.ts
> +    } else if (this._componentRef && inputsChange && inputs) {
As I said, I will use `KeyValueDiffer`, which will be able to support:
> The content and / or shape of the inputs object literal can change without changing identity of the said object.

2023-04-22 02:55 UTC, HyperLife1119 commented on packages/common/src/directives/ng_component_outlet.ts
> +    } else if (this._componentRef && inputsChange && inputs) {
In the latest commit, the mutable inputs will work:
```ts
inputsExpression.foo = 'changed';
```

2023-05-04 12:54 UTC, JeanMeche commented
Hi, any updates on the review ? I see that it's breaking internal tests, what kind of breakage do we have here ?

2023-05-28 03:29 UTC, ankitkaushik24 commented
Waiting on this PR merge for so long. This is a great effort @HyperLife1119 and could be a splendid accomplishment in Angular history for **Lazy first components**. As of now, we might be doing it this way: https://ankit-kaushik.medium.com/component-switching-dynamically-using-lazy-loading-in-angular-templates-81f026e4b148. Going forward if this PR gets merged, we'll certainly see a major diversion in the way code splitting is achieved in Angular.

@atscott @AndrewKushnir @jessicajaniuk let's speed this up

2023-05-31 03:31 UTC, HyperLife1119 commented
Can someone help me push this PR forward?

2023-06-06 09:22 UTC, pkozlowski-opensource commented on packages/common/test/directives/ng_component_outlet_spec.ts
> +  it('should be binding the component input', () => {
nit: it would be great to move those new tests to a dedicated `describe` block and declare `ComponentWithInputs` / `AnotherComponentWithInputs` in this new block. Not a blocker for this PR to get landed.

2023-06-06 09:58 UTC, pkozlowski-opensource requested changes
@HyperLife1119 thnx for doing the first round of updates. I still do believe that the implementation logic is not handling correctly the cases of the inputs object _shape_ change. 

I've left more detailed info in the inline comments but generally speaking I think that you should take the implementation from the NgClass as inspiration. 

Feel free to ping me in this PR if you need more help.

2023-06-06 09:58 UTC, pkozlowski-opensource commented on packages/common/test/directives/ng_component_outlet_spec.ts
> +@Component({selector: 'cmp-with-inputs', template: '{{ foo }}{{ bar }}{{ baz }}'})
nit: I find it rather hard to read the tests / assertions as it is not very clear which inputs values are being written to the DOM. It would be probably clearer with sth like: `foo: {{ foo }}; bar: {{ bar }}; baz: {{ baz }}'`. Not a blocker for this PR to get landed.

2023-06-06 09:58 UTC, pkozlowski-opensource commented on packages/common/test/directives/ng_component_outlet_spec.ts
> +    expect(fixture.nativeElement.textContent).toBe('FooBar!');
This does seem wrong: I think it would be rather confusing that the bound object is of shape `{foo: 'Foo'}` but the `bar` binding retains value from the previous `{foo: 'Foo', bar: 'Bar'}` object literal. 

As noted in my [previous comment](https://github.com/angular/angular/pull/49735#discussion_r1173633011) I think that we should use approach similar to NgClass implementation where we do maintain a `Map` of key / value pairs so we can detect properties that were removed due to the object shape change.

I hope that the NgClass implementation is reasonably easy to follow but I'm happy to share more details if needed.

2023-06-06 09:58 UTC, pkozlowski-opensource commented on packages/common/test/directives/ng_component_outlet_spec.ts
> +    expect(fixture.nativeElement.textContent).toBe('Foo!');
Again, this doesn't seem correct to me, it has the same underlying implementation issue as pointed out in the previous comment.

2023-06-07 15:49 UTC, HyperLife1119 commented on packages/common/test/directives/ng_component_outlet_spec.ts
> +    expect(fixture.nativeElement.textContent).toBe('FooBar!');
Thanks for your comment, I think I fixed this issue in the latest commit.

2023-06-07 16:08 UTC, pkozlowski-opensource approved these changes
LGTM

Reviewed-for: public-api 
Reviewed-for: fw-common

2023-06-08 17:00 UTC, alxhub commented
This PR was merged into the repository by commit f3867597f079794ae9c7ed8be3788c9cea5123a3.

2023-06-12 10:52 UTC, pkozlowski-opensource commented
Adding "blocked" label since this PR will require investigation on our side before merging.

2023-06-15 16:51 UTC, closed without merging

2023-06-15 17:07 UTC, HyperLife1119 commented
Sorry, due to an incorrect rebase operation, the PR has been transferred to #50736.