feat(compiler): Add local compilation mode
angular/angular pull request #49846
Opened 2023-04-14 15:34 UTC by pmvald

In this mode the compiler generates code based on each individual source file without using its dependencies. This mode is suitable only for fast edit/refresh during development.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
No change to current behaviour.

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-04-14 16:23 UTC, pmvald commented
Don't know why sub_module samples also got included. Thought there is a way to exclude it, but no way! So I created another [PR](https://github.com/angular/angular/pull/49848) where I just add it to gitignore. See which one makes more sense and close the other one.

2023-04-14 18:19 UTC, JeanMeche commented
You should close this one yourself then :)

2023-04-14 20:21 UTC, devversion commented on packages/compiler-cli/src/ngtsc/core/api/src/public_options.ts
> +  compilationMode?: 'full'|'partial'|'experimental-local';
Have we considered naming this "experimental-single-file"? Local is quite a broad term, but definitely works, just an idea.

2023-04-14 20:33 UTC, pmvald commented on packages/compiler-cli/src/ngtsc/core/api/src/public_options.ts
> +  compilationMode?: 'full'|'partial'|'experimental-local';
Yeah, but there would be a risk that for some reason we cannot achieve single file compilation in Angular, and have to content ourselves with "single compile unit" instead. So, I chose local compilation as a more conservative choice. 

But at the end if we were successful we can change the value to "signle-file" (instead of "local"). This should be a one line change in the helper `isLocalCompilation`

2023-04-15 18:38 UTC, devversion commented on packages/compiler-cli/src/ngtsc/core/api/src/public_options.ts
> +  compilationMode?: 'full'|'partial'|'experimental-local';
Sounds good. Like you said, we can always change this in the future, and you also explained "local" in the JSDoc

2023-04-15 18:38 UTC, devversion commented on packages/compiler-cli/src/ngtsc/util/src/local_compilation.ts
> +/** Cannonical logic as to whether the compilation is in local mode. */
typo for canonical, and I'd propose something like:

```suggestion
/** Gets whether local compilation is enabled in the compiler options. */
```

2023-04-15 18:38 UTC, devversion commented on packages/compiler-cli/src/ngtsc/util/BUILD.bazel
> +        "//packages/compiler-cli/src/ngtsc/core:api",
Nit might want to move `isLocalCompilation` to `core/src/` so that `utils` does not have a dependency on core (even if just API)

2023-04-18 11:55 UTC, devversion approved these changes

2023-04-18 20:22 UTC, alxhub requested changes
There are also two commits with identical messages in this PR, which should be squashed into one.

2023-04-18 22:40 UTC, alxhub requested changes

2023-04-19 22:50 UTC, alxhub approved these changes

2023-04-19 22:53 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2023-04-20 14:51 UTC, jessicajaniuk approved these changes
reviewed-for: public-api

2023-04-20 14:52 UTC, jessicajaniuk commented
Caretaker: win_tests are known flakes. This is safe to merge.

2023-04-24 01:19 UTC, dylhunn commented
This PR was merged into the repository by commit 345dd6d81acc6be15cb1b822afa39d6a8548e0b5.

2023-04-24 01:20 UTC, closed without merging