refactor(common): remove unused isPlatform functions
angular/angular pull request #50055
Opened 2023-04-28 00:30 UTC by JeanMeche

The Web worker platform was removed in v11.
`isPlatformWorkerApp` & `isPlatformWorkerUi` have no purpose.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [x] Yes but. 

This will probably require a presubmit. Are these 2 functions still used on G3 ?

2023-04-28 08:36 UTC, alan-agius4 approved these changes
LGTM, thanks

2023-04-28 15:32 UTC, atscott approved these changes

2023-04-28 15:38 UTC, atscott requested changes
Actually, these functions are public API. If they're exported, they can't be removed with deprecation and then waiting 2 major versions, right?

2023-04-28 15:40 UTC, JeanMeche commented
Yeah you're right. 
But they don't have any purpose since v11. So I why really wondering about their usage and if the 2 version depreciation period was necessary !

2023-04-28 15:48 UTC, atscott commented
> So I was really wondering about their usage and if the 2 version depreciation period was necessary !

Unless they were officially already deprecated in v11, yes

2023-04-28 16:17 UTC, JeanMeche commented
Let's deprecate them then !

2023-04-28 16:21 UTC, atscott approved these changes

2023-04-28 16:23 UTC, pkozlowski-opensource approved these changes
LGTM

Reviewed-for: public-api

2023-04-28 16:59 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2023-05-01 14:39 UTC, alxhub commented
This PR was merged into the repository by commit f49c6d0a2fe2642707205bc0b83def46293cebee.

2023-05-01 14:39 UTC, closed without merging