docs: Avoid absolute links to angular.io
angular/angular pull request #50213
Opened 2023-05-08 23:51 UTC by JeanMeche

This PR introduces a new transform processor to warn about absolute links to angular.io. 

Absolute links to aio should be avoided as they will appear as external links in the doc. 

This is a follow-up work of #50080

2023-05-08 23:55 UTC, JeanMeche commented
Logging a warning or throwing an error, what do you prefer actually ?

2023-05-09 04:42 UTC, SwamiSanapathi approved these changes

2023-05-09 14:43 UTC, jessicajaniuk requested changes
This is really helpful other than the one usecase we do have for absolute links.

2023-05-09 14:43 UTC, jessicajaniuk commented on aio/tools/transforms/angular-base-package/processors/checkAbsoluteAioLinks.js
> +module.exports = function checkAioAbsoluteLinks(log, createDocMessage) {
There is an exception to this rule sometimes, and that's as we're developing new features, we may need to directly link to next.angular.io so that the docs go to the right place. There needs to be a carve out for that usecase.

2023-05-09 14:45 UTC, JeanMeche commented on aio/tools/transforms/angular-base-package/processors/checkAbsoluteAioLinks.js
> +module.exports = function checkAioAbsoluteLinks(log, createDocMessage) {
Yes of course ! This use cases is actually already handled as it's checking for urls starting with `https://angular.io/` !  Maybe the phrasing is a bit confusing !

2023-05-09 14:50 UTC, jessicajaniuk approved these changes
LGTM

2023-05-09 14:50 UTC, jessicajaniuk commented on aio/tools/transforms/angular-base-package/processors/checkAbsoluteAioLinks.js
> +module.exports = function checkAioAbsoluteLinks(log, createDocMessage) {
Yeah, you're right. I didn't pay enough attention here to see it's exact matching of that pattern. Thank you!

2023-05-09 16:16 UTC, dylhunn commented
@jelbourn This might be a good candidate for the `global-review` hammer. Otherwise we'll be collecting a lot of reviews.

2023-05-10 18:47 UTC, jelbourn approved these changes
LGTM

Reviewed-for: global-approval

2023-05-10 18:47 UTC, jelbourn approved these changes
LGTM

Reviewed-for: global-approvers

2023-05-10 21:29 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 5db170c501b22841023281fe4dcf8dcbf7c8f7ef.

2023-05-10 21:30 UTC, closed without merging