fix(forms): add FileList length check to isEmptyInputValue
angular/angular pull request #50436
Opened 2023-05-23 19:18 UTC by sashaqred

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Empty `FileList` (length === 0) is valid with `Validator.required`

Issue Number: 50431

## What is the new behavior?
Empty `FileList` (length === 0) is invalid with `Validator.required`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

`FileList` is not a constructor, so it can't

2023-05-23 19:21 UTC, JeanMeche commented on packages/forms/src/validators.ts
> +        ((globalThis as any).FileList != null && value instanceof (globalThis as any).FileList)) &&
This could be simplified
```suggestion
        typeof FileList !== 'undefined'
```

2023-05-23 19:26 UTC, JeanMeche commented on packages/forms/src/validators.ts
> +        // Need to use check of FileList in globalThis to prevent crashing on browser environments
```suggestion
        // Need to use check of FileList in globalThis to prevent crashing on non-browser environments
```

2023-05-23 19:50 UTC, JoostK requested changes
I don't think we should be making this change. There are lots of array-like structures that are not accounted for, nor do I believe they should. `FileList` is iterable, so you can copy over the items to an array using `Array.from()` to derive an actual array.

2023-05-23 19:53 UTC, JeanMeche commented
>  `FileList` is iterable.
Just to be pendantic, it's not iterable because it doesn't implement `Symbol.Iterator` but it is `ArrayLike`.

2023-05-23 20:50 UTC, sashaqred commented
> I don't think we should be making this change. There are lots of array-like structures that are not accounted for, nor do I believe they should. `FileList` is iterable, so you can copy over the items to an array using `Array.from()` to derive an actual array.

Yes, but `FileList` is a result of a native HTML input, unlike other array-like structures.

2023-05-23 21:02 UTC, JoostK commented
> > I don't think we should be making this change. There are lots of array-like structures that are not accounted for, nor do I believe they should. `FileList` is iterable, so you can copy over the items to an array using `Array.from()` to derive an actual array.
> 
> Yes, but `FileList` is a result of a native HTML input, unlike other array-like structures, which are hard to edit with native HTML inputs.

I don't quite understand what you mean by "which are hard to edit with native HTML inputs".

---

Also interestingly, [the 2023 draft spec has this note](https://w3c.github.io/FileAPI/#filelist-section):

> **Note**
> The [FileList](https://w3c.github.io/FileAPI/#dfn-filelist) interface should be considered "at risk" since the general trend on the Web Platform is to replace such interfaces with the [Array](http://tc39.github.io/ecma262/#sec-array-constructor) platform object in ECMAScript [[ECMA-262]](https://w3c.github.io/FileAPI/#biblio-ecma-262). In particular, this means syntax of the sort `filelist.item(0)` is at risk; most other programmatic use of [FileList](https://w3c.github.io/FileAPI/#dfn-filelist) is unlikely to be affected by the eventual migration to an [Array](http://tc39.github.io/ecma262/#sec-array-constructor) type.

2023-05-24 15:44 UTC, sashaqred commented
> > > I don't think we should be making this change. There are lots of array-like structures that are not accounted for, nor do I believe they should. `FileList` is iterable, so you can copy over the items to an array using `Array.from()` to derive an actual array.
> > 
> > 
> > Yes, but `FileList` is a result of a native HTML input, unlike other array-like structures, which are hard to edit with native HTML inputs.
> 
> I don't quite understand what you mean by "which are hard to edit with native HTML inputs", nor why the origin of the `FileList` would make a difference as to whether it should be special-cased?
> 
> Also interestingly, [the 2023 draft spec has this note](https://w3c.github.io/FileAPI/#filelist-section):
> 
> > Note
> > The [FileList](https://w3c.github.io/FileAPI/#dfn-filelist) interface should be considered "at risk" since the general trend on the Web Platform is to replace such interfaces with the [Array](http://tc39.github.io/ecma262/#sec-array-constructor) platform object in ECMAScript [[ECMA-262]](https://w3c.github.io/FileAPI/#biblio-ecma-262). In particular, this means syntax of the sort `filelist.item(0)` is at risk; most other programmatic use of [FileList](https://w3c.github.io/FileAPI/#dfn-filelist) is unlikely to be affected by the eventual migration to an [Array](http://tc39.github.io/ecma262/#sec-array-constructor) type.

I mean that `FileList` is a kinda result of HTML input. So for me, `FileList` is a native "data structure" for a form. While other array-like structures aren't the result of a form. This is a reason why I suggest validating `FileList` like arrays or strings.

Also, I opened the issue https://github.com/angular/angular/issues/50431 before this pull request. I was testing validators and found that `Validators.required` wasn't working for `FileList`. And as I remember, it worked a couple of years before. After some research, I found the pr, which probably broke it for `FileList` https://github.com/angular/angular/pull/33729/files

After creating the issue, I took a bit of inspiration from CONTRIBUTING.md

> If you find a bug in the source code, you can help us by submitting an issue to our GitHub Repository. **Even better, you can submit a Pull Request with a fix.**

And here I am 🙂

2023-05-29 13:15 UTC, sunshuhan commented
>  And as I remember, it worked a couple of years before. 

Hi, I checked the history of **validators.ts** from 6 years ago, it just changed from
```
function isEmptyInputValue(value: any): boolean {
  // we don't check for string here so it also works with arrays
  return value == null || value.length === 0;
}

```

to current

```
function isEmptyInputValue(value: any): boolean {
  /**
   * Check if the object is a string or array before evaluating the length attribute.
   * This avoids falsely rejecting objects that contain a custom length attribute.
   * For example, the object {id: 1, length: 0, width: 0} should not be returned as empty.
   */
  return value == null ||
      ((typeof value === 'string' || Array.isArray(value)) && value.length === 0);

```

So, i don't agree that it's an issue that needs to be fixed based on " it worked a couple of years before"

2023-06-05 09:23 UTC, sashaqred commented
> So, If it worked a few years ago, maybe you were using an index(files[0]) at that time, instead of files

@sunshuhan, no, I used `FileList`. As you mention previous implementation

```
function isEmptyInputValue(value: any): boolean {
  // we don't check for string here so it also works with arrays
  return value == null || value.length === 0;
}
```

It was working with `FileList`, since `FileList` has `length` property.

2023-06-07 01:19 UTC, sunshuhan commented
sorry i missed that , agree with this situation considered!

2023-06-07 01:21 UTC, sunshuhan commented
Sorry, I forgot to consider this., thanks for your detailed explanation.  I agree again that this scenario should be fixed.

2023-06-07 01:26 UTC, sunshuhan commented
> > So, If it worked a few years ago, maybe you were using an index(files[0]) at that time, instead of files
> 
> @sunshuhan, no, I used `FileList`. As you mention previous implementation
> 
> ```
> function isEmptyInputValue(value: any): boolean {
>   // we don't check for string here so it also works with arrays
>   return value == null || value.length === 0;
> }
> ```
> 
> It was working with `FileList`, since `FileList` has `length` property.

Thanks for your detailed explanation! I agree again that this scenario should be fixed.

2024-01-31 16:08 UTC, JeanMeche commented
Per Joost rationale, we'll close this. We do not want to handle every array like structures. You can use `Array.from` as a workaround.

2024-01-31 16:08 UTC, closed without merging