docs: Angular sanitizes untrusted values for HTML, styles, and URLs
angular/angular pull request #50538
Opened 2023-06-01 11:48 UTC by aanchal88

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-06-05 10:26 UTC, pkozlowski-opensource requested changes
Thank you for opening the pull request, we do appreciate all the contributions.

We do follow certain commit message guidelines (to automatically generate changelog, among other things). This PR does not follow the recommended git commit message format and it will need cleanup. You can find more information about our commit message format here: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format

2023-06-05 10:45 UTC, aanchal88 commented
Hii @pkozlowski-opensource , updated the commit message. Please have a look.
Thanks

2023-06-05 11:42 UTC, pkozlowski-opensource approved these changes
LGTM

Reviewed-for: fw-security

2023-06-09 20:26 UTC, alxhub requested changes

2023-06-09 20:26 UTC, alxhub commented on aio/content/guide/security.md
> +Angular sanitizes untrusted values for HTML and URLs; modern web browser sanitizes untrusted values for styles; sanitizing resource URLs isn't possible because they contain arbitrary code.
```suggestion
Angular sanitizes untrusted values for HTML and URLs, and modern web browsers sanitize untrusted values for styles. Sanitizing resource URLs isn't possible because they contain arbitrary code.
```

2023-06-12 06:19 UTC, aanchal88 commented
Hii @alxhub, updated the requested changes. Please review.

2023-06-12 16:36 UTC, josephperrott approved these changes
LGTM

2023-06-12 16:41 UTC, josephperrott approved these changes
LGTM

Reviewed-for: fw-security

2023-06-12 23:03 UTC, alxhub approved these changes
Reviewed-for: fw-security

2023-06-12 23:04 UTC, alxhub requested changes
Hi @aanchal88,

I think you need to squash the `update` commit into the original one - there should only be one commit in the PR.

2023-06-13 11:43 UTC, aanchal88 commented
Hii @alxhub , I am closing this PR as by mistake multiple commits have been done.
Opening another PR https://github.com/angular/angular/pull/50697 for the same. Please have a look.
Thanks

2023-06-13 11:43 UTC, closed without merging