fix(devtools): ensure that inspected component label is always in the viewport
angular/angular pull request #50656
Opened 2023-06-11 07:39 UTC by crisbeto

Currently the label showing the component name is always positioned from the bottom/right edge of the element which may be outside of the viewport. These changes add some logic to fall back to a different position so that the label is always visible.

Fixes #48479.

2023-06-11 08:02 UTC, crisbeto commented on devtools/projects/ng-devtools-backend/src/lib/highlighter.ts
> +  // Attempt to position the content element so that it's always in the
Note that a far simpler way of fixing the issue would've been to reduce the size of the container element so it's never outside of the viewport. I felt like this approach offers a better experience, because the container accurately reflects the size of the element you're inspecting.

2023-06-19 04:38 UTC, AleksanderBodurri requested changes
Thanks @crisbeto 🙏  Left a small comment.

I like the recommendation you left about changing the size of the container element instead of the content element, so that it's always within the viewport. Since the implementation in this PR is an improvement on the current behaviour, I'm okay to move forward with what we have here and look into improving this more after it's merged. Let me know how you want to proceed 🙏

2023-06-26 15:14 UTC, crisbeto commented
@AleksanderBodurri I played around with it a bit and I think that the current approach has a better UX, compared to reducing the height of the container. The problem with reducing the height is that some elements can be very slim and can have their content covered up by the label like in this example:

<img width="516" alt="image" src="https://github.com/angular/angular/assets/4450522/d83c0a34-1d37-4876-92d3-d987ce6d5d47">

2023-06-26 15:15 UTC, crisbeto commented on devtools/projects/ng-devtools-backend/src/lib/highlighter.ts
> +  const yOffset = 23;
The 23 was hardcoded already, I just had to move it out so that I could use it in the calculations.

2023-07-26 12:16 UTC, crisbeto commented
@AleksanderBodurri pinging here again.

2023-07-26 15:40 UTC, AleksanderBodurri approved these changes

2023-07-26 17:04 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 3a59de681fd9899a40c49b3bce6f101d3d1b95cd.

2023-07-26 17:04 UTC, closed without merging