docs: fix untrust values for html, styles and urls
angular/angular pull request #50697
Opened 2023-06-13 11:42 UTC by aanchal88

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-06-14 08:41 UTC, pkozlowski-opensource approved these changes
LGTM

Reviewed-for: fw-security

2023-06-19 11:49 UTC, aanchal88 commented
Hii @pkozlowski-opensource , please merge the PR.

2023-06-22 14:33 UTC, josephperrott requested changes

2023-06-22 14:33 UTC, josephperrott commented on aio/content/guide/security.md
> +Angular sanitizes untrusted values for HTML and URLs, and modern web browsers sanitize untrusted values for styles. Sanitizing resource URLs isn't possible because they contain arbitrary code.
I am not sure this is explicitly true.  It is possible to perform injection via css particularly related to exfiltration attacks.  This is part of the reason that we continue to perform sanitization when binding to the style attribute.

2023-08-31 18:13 UTC, closed without merging