feat(animations): Provide a way to lazy load the animations
angular/angular pull request #50738
Opened 2023-06-15 22:40 UTC by JeanMeche

WIP - Doesn't work as expected yet. 

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-06-27 01:03 UTC, AndrewKushnir commented on packages/platform-browser/lazy-animations/src/async_animation_renderer.ts
> +      moduleImpl: Promise<FromAnimationBrowserModule> = import('@angular/animations/browser')) {
I'd propose kicking off a dynamic import in the `createRenderer` function. We can also do that **if** there is any animations defined on the `@Component` (i.e. `type.data?.['animation']` is defined). WDYT?

2023-06-28 12:24 UTC, devversion commented on WORKSPACE
> +filegroup(\r
is this change intentional?

2023-06-28 12:43 UTC, JeanMeche commented on WORKSPACE
> +filegroup(\r
It was triggered by the linting if I remember correctly

2023-09-18 19:44 UTC, jessicajaniuk requested changes

2023-09-18 19:44 UTC, jessicajaniuk commented on goldens/public-api/platform-browser/lazy-animations/index.md
> +export function provideLazyLoadedAnimations(type?: 'animations' | 'noop'): Provider[];
We've had some conversations about the term "Lazy Loading" internally, and we'd like to move away from it. Please rename this to `provideAnimationsAsync`.

2023-09-18 19:44 UTC, jessicajaniuk commented on packages.bzl
> +    "platform-browser/lazy-animations",
Let's change this path to `platform-browser/animations/async` instead. This is what we'd like users to write:
`import {provideAnimationsAsync} from '@angular/platform-browser/animations/async';`.

2023-09-18 19:44 UTC, jessicajaniuk commented on packages/animations/browser/src/error_helpers.ts
> + * The following code is a copy of the same from the Core package, please keep in sync.
I'm not thrilled about having to duplicate this code from Core, and my understanding is the only reason we're doing this is due to webpack. Can we add a TODO here to remove this once we remove support for Webpack?

2023-09-18 19:44 UTC, jessicajaniuk commented on packages/platform-browser/BUILD.bazel
> +        "//packages/platform-browser/lazy-animations",
Let's change this path, as well, so that it doesn't use `lazy`. Let's go with `animations-async` for consistency.

2023-09-18 19:44 UTC, jessicajaniuk commented on packages/platform-browser/lazy-animations/src/async_animation_renderer.ts
> +  private _moduleLoaded: Promise<AnimationRendererFactory>|null = null;
I know we refer to this as the `Browser Animations Module`, but there's a bit of overloading with the term `Module`. We could consider renaming this to be something else that's less overloaded.

2023-09-18 19:44 UTC, AndrewKushnir requested changes
@JeanMeche thanks for making progress on this PR, leaving some comments after the initial review with @jessicajaniuk.

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/animations/browser/src/createEngine.ts
> +  }
In this scenario the `NoopAnimationDriver` and `NoopAnimationStyleNormalizer` would become non-tree-shakable (as they are eagerly referenced). Can we refactor the code to avoid this?

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/animations/browser/src/render/animation_renderer.ts
> +      }
nit: to improve minification (property names are not minified), we can reference `this._rendererCache` once and use a const after that.
```suggestion
      const cache = this._rendererCache;
      let renderer: BaseAnimationRenderer|undefined = cache.get(delegate);
      if (!renderer) {
        // Ensure that the renderer is removed from the cache on destroy
        // since it may contain references to detached DOM nodes.
        const onRendererDestroy = () => cache.delete(delegate);
        renderer =
            new BaseAnimationRenderer(EMPTY_NAMESPACE_ID, delegate, this.engine, onRendererDestroy);
        // only cache this result when the base renderer is used
        cache.set(delegate, renderer);
      }
```

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/animations/browser/src/render/animation_renderer.ts
> +    if (this._animationCallbacksBuffer.length == 0) {
Similar comment to improve minification:
```suggestion
    const animationCallbacksBuffer = this._animationCallbacksBuffer;
    if (animationCallbacksBuffer.length == 0) {
```

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/animations/browser/src/render/animation_renderer.ts
> +    if (this._animationCallbacksBuffer.length == 0) {
note: there might be similar cases as well

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/animations/browser/src/render/renderer.ts
> +type FactoryWithListenerCallback = RendererFactory2&
nit: let's include "Animation" here for readability:
```suggestion
type AnimationFactoryWithListenerCallback = RendererFactory2&
```

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/animations/browser/src/render/web_animations/web_animations_driver.ts
> + * This class should not import from @angular/core as it breaks the tree shaking
Quick question: if we accidentally introduce a dependency on `@angular/core`, would we catch it with tests as well (size-tracking or symbol-tracking)?

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/platform-browser/animations/src/animation_builder.ts
> +@Injectable({providedIn: 'root'})
Can we extract this into a separate PR?

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/platform-browser/lazy-animations/src/async_animation_renderer.ts
> +type FromAnimationBrowserModule = {
```suggestion
type AnimationBrowserModuleImports = {
```

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/platform-browser/lazy-animations/src/async_animation_renderer.ts
> +type FromAnimationBrowserModule = {
Could you please also add a JSDoc above it to explain why we need this type?

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/platform-browser/lazy-animations/src/async_animation_renderer.ts
> +    return moduleImpl
nit: for readability, I'd propose avoid using a dynamic import as a default value and assign the default value for the `moduleImpl` at the very beginning of the file:
```suggestion
  private loadImpl(
      type: 'animations'|'noop',
      moduleImpl?: Promise<FromAnimationBrowserModule>): Promise<AnimationRendererFactory> {
    moduleImpl ??= import('@angular/animations/browser');
    return moduleImpl
```

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/platform-browser/lazy-animations/src/async_animation_renderer.ts
> +    return moduleImpl
We also accept the `moduleImpl` as a constructor argument. Are we supposed to use it here if it was not provided into this function as an argument? If no, we can probably rename the argument to avoid possible confusion.

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/platform-browser/lazy-animations/src/async_animation_renderer.ts
> +    if ('throwOnSyntheticProps' in renderer) {
I'd propose this refactoring to make the code more compatible with Closure Compiler optimizations that rename fields:
```suggestion
    if (typeof renderer.throwOnSyntheticProps === 'boolean') {
```

2023-09-18 19:44 UTC, AndrewKushnir commented on packages/platform-browser/src/dom/dom_renderer.ts
> +  throwOnSyntheticProps = true;
I'd propose adding a JSDoc here to explain what this flag represents and why it's `true`.

2023-09-18 20:05 UTC, JeanMeche commented on packages.bzl
> +    "platform-browser/lazy-animations",
I like that idea very much 👍

2023-09-18 20:36 UTC, JeanMeche commented on packages/platform-browser/lazy-animations/src/async_animation_renderer.ts
> +type FromAnimationBrowserModule = {
I rewrote that type + added a JSDOC 👍

2023-09-18 21:01 UTC, JeanMeche commented on packages/animations/browser/src/render/animation_renderer.ts
> +      }
Interesting knowledge, TIL 👍

2023-09-18 22:54 UTC, JeanMeche commented on packages/platform-browser/animations/src/animation_builder.ts
> +@Injectable({providedIn: 'root'})
There is definitely some work to do on this. 
Pulling the `BrowserAnimationBuilder` breaks the code splitting because it's in the `platform-browser/animations` (and not in the `async` secondary entry we had to created). 

I'll remove this from the scope of this PR.

2023-09-18 23:31 UTC, JeanMeche commented on packages/animations/browser/src/error_helpers.ts
> + * The following code is a copy of the same from the Core package, please keep in sync.
I'm happy to report that I'm not able to reproduce the initial issue. I've removed the duplicate code.

2023-09-19 00:13 UTC, JeanMeche commented
@AndrewKushnir @jessicajaniuk Thank you both for your feedbacks !

I have a great news, for a reason I could not determine, the import of the core module in not an issue anymore when using the webpack builder !

2023-09-19 01:06 UTC, AndrewKushnir reviewed
> I have a great news, for a reason I could not determine, the import of the core module in not an issue anymore when using the webpack builder !

This is great 🎉

2023-09-19 01:06 UTC, AndrewKushnir commented on packages/animations/browser/src/createEngine.ts
> +  }
@JeanMeche as a possible solution, we can mimic the `provideNoopAnimations()` function and call it `provideNoopAnimationsAsync()`, so that we create one of the engines depending on the function used.

2023-09-19 01:06 UTC, AndrewKushnir commented on packages/animations/browser/src/render/animation_renderer.ts
> +    this._animationCallbacksBuffer.push([fn, data]);
```suggestion
          animationCallbacksBuffer.forEach(tuple => {
            const [fn, data] = tuple;
            fn(data);
          });
          this._animationCallbacksBuffer = [];
        });
      });
    }

    animationCallbacksBuffer.push([fn, data]);
```

2023-09-19 01:14 UTC, JeanMeche commented on packages/animations/browser/src/render/animation_renderer.ts
> +    this._animationCallbacksBuffer.push([fn, data]);
About the `createEngine` function, I thought about your suggestion. I doesn't seem applicable to me. 

`createEngine()`, the drivers and the styleNormalizers are part of the lazy loaded bundle so we cannot use providers.

2023-09-19 01:15 UTC, JeanMeche commented on packages/animations/browser/src/createEngine.ts
> +  }
About that,  I thought about your suggestion. I doesn't seem applicable to me.

createEngine(), the drivers and the styleNormalizers are part of the lazy loaded bundle so we cannot use providers.

2023-09-20 00:31 UTC, AndrewKushnir reviewed
@JeanMeche thanks for addressing the feedback, I think we are very close!

I'm also thinking that it'd be great to add a new integration testing app to have a way to capture the bundle size in the size tracking golden files (so that we confirm that everything works as expected and there are no regressions in the future). We can copy the `integration/animations` app and update it to use the `provideAnimationsAsync` function there.

2023-09-20 00:31 UTC, AndrewKushnir commented on packages/animations/browser/src/createEngine.ts
> +/**
Could you please rename the file to `create_engine.ts`?

2023-09-20 00:31 UTC, AndrewKushnir commented on packages/animations/browser/src/createEngine.ts
> +  }
Could you please elaborate a bit on this? My assumption is that having the `provideNoopAnimationsAsync()` function would allow us to reference the noop-related code there, so we don't have to do it in the `provideAnimationsAsync()` function. As an option, we can have a callback there that we define there:

```
      useFactory: (doc: Document, renderer: DomRendererFactory2, zone: NgZone) => {
        // in `provideAnimationsAsync`:
        const getEngine = (m) => m.getEngine();
        // in `provideNoopAnimationsAsync`:
        const getEngine = (m) => m.getNoopEngine();
        return new AsyncAnimationRendererFactory(doc, renderer, zone, type, getEngine);
      },
```

2023-09-20 14:47 UTC, JeanMeche commented on packages/animations/browser/src/createEngine.ts
> +  }
Sure, 

`NoopAnimationDriver`/`NoopAnimationStyleNormalizer` are part of the animation module, the module we want to lazy load. By referencing anything of that module outside of it, we will break the code splitting/lazy loading, so we can't define them in the providers.  

Currently `createEngine()` is not imported statically but via the dynamic import of `@angular/animations/browser`. That why it doesn't break the lazy loading. 

I have tried using  the `animationType` parameter to determine which of `createEngine` or `createNoopEngine` to call.  But both builder don't seem able to infer that `animationType` is readonly in `AsyncAnimationRendererFactory` (and it doesn't tree shake the unused one).

2023-09-20 17:27 UTC, JeanMeche commented
@AndrewKushnir  I've added the integration tests and checked, they fail when the code split/lazy loading is broken.

2023-09-22 18:24 UTC, JeanMeche commented on goldens/size-tracking/integration-payloads.json
> +      "main": 221187,
Both apps are quite different, the async one uses the router, I'll update the "eager" one for us to have a good comparaison !

2023-09-22 23:06 UTC, AndrewKushnir approved these changes
@JeanMeche thanks for addressing the feedback, the change looks great! 👍

2023-09-25 14:09 UTC, jessicajaniuk approved these changes
LGTM!!!! 🎉

2023-09-26 16:08 UTC, jessicajaniuk requested changes

2023-09-27 14:36 UTC, jessicajaniuk approved these changes
The issue was resolved in #51910. Once we have G3 issues resolved, this is good to go.

reviewed-for: fw-animations, fw-core, integration-tests, public-api, size-tracking

2023-09-27 14:41 UTC, devversion approved these changes
LGTM for Bazel

2023-09-27 16:34 UTC, dylhunn approved these changes
reviewed-for: public-api

2023-09-28 02:02 UTC, jessicajaniuk commented
[TGP](https://fusion2.corp.google.com/presubmit/568390727/OCL:568390727:BASE:569020688:1695866485607:d5ce5688/targets)

2023-09-29 17:49 UTC, alxhub commented
This PR was merged into the repository by commit 81e7f5be0380f58b0d7e74c7e8190c865316becc.

2023-09-29 17:49 UTC, closed without merging

2023-10-05 21:26 UTC, robertIsaac commented
was it renamed to `provideAnimationsAsync`?

2023-10-05 21:49 UTC, jessicajaniuk commented
@robertIsaac yes, it was.

2023-10-05 21:51 UTC, robertIsaac commented
I tried it, but saw size increases instead of decrease
The component that have animation is deferred, can it be related?
I can share a reproduce repo if you wish to investigate further

2023-10-05 21:53 UTC, jessicajaniuk commented
@robertIsaac Please file an issue with the repro and we can take a look.

2023-10-05 21:53 UTC, JeanMeche commented
@robertIsaac Please open an new issue with a repro repo and we'll happily investigate that  😊