feat(devtools): added instances count and total time in bar chart
angular/angular pull request #50866
Opened 2023-06-27 19:10 UTC by eneajaho

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?

In the bar chart in the devtools now we can see the total time of all the component instances in one change detection run, and all the directive instances count.

- [x] Feature

## What is the current behavior?
Currently, the time for single component/directive instances is shown. Because we can have the same with flamegraph, converting the bar chart to show this new feature was thought as the way to go (as we don't need the same stat twice). 

Issue Number: #50555

## What is the new behavior?
<img width="1512" alt="CleanShot 2023-06-27 at 21 07 20@2x" src="https://github.com/angular/angular/assets/25394362/f0e06500-9717-4947-b07f-cd253a605fb2">

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-06-28 01:25 UTC, AleksanderBodurri requested changes
Thanks for working on this 🙏 Left a few comments 😄

2023-06-28 01:25 UTC, AleksanderBodurri commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/record-formatter/bargraph-formatter/bargraph-formatter.ts
> +        acc[key].original.children.push(...item.original.children);
Mutating `original.children` here may have unintentional upstream effects. Can we find a way to squash this data for the bar graph without mutating the underlying profiler frame?

2023-06-28 01:25 UTC, AleksanderBodurri commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/record-formatter/bargraph-formatter/bargraph-formatter.ts
> +        acc[key].original.directives.push(...item.original.directives);
See related comment

2023-06-28 01:25 UTC, AleksanderBodurri commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/record-formatter/bargraph-formatter/bargraph-formatter.ts
> +    const uniqueNodes = nodesWithValue.reduce((acc, item) => {
Nit: I think achieving the same thing by instantiating a new object and doing a `forEach` would be more readable than a `reduce`

```ts
const labelToDirectives = {};
nodesWithValue.forEach(node => {
  if (labelToDirectives[node.label] === undefined) {
    // create labelToDirectives[node.label]
  } else {
    // update labelToDirectives[node.label]
  }
});
```

2023-06-28 12:22 UTC, eneajaho commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/record-formatter/bargraph-formatter/bargraph-formatter.ts
> +        acc[key].original.children.push(...item.original.children);
I'm thinking of creating another field in the object so we use it only for the bargraph.

2023-06-29 09:25 UTC, enea4science commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/recording-visualizer/bar-chart.component.ts
> +        value: Math.floor((node.value / max) * 100),
@AleksanderBodurri 
Is this right?

2023-06-29 09:26 UTC, eneajaho commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/recording-visualizer/bar-chart.component.ts
> +        value: Math.floor((node.value / max) * 100),
@AleksanderBodurri 
Is this right?

2023-06-29 09:55 UTC, JeanMeche reviewed
2 small nits, from me. Thanks for this Enea !

2023-06-29 09:55 UTC, JeanMeche commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/record-formatter/bargraph-formatter/bargraph-formatter.ts
> +          directives: node.original.directives || [],
nit: let's use `??` instead. 
```suggestion
          directives: node.original.directives ?? [],
```

2023-06-29 09:55 UTC, JeanMeche commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/recording-visualizer/bargraph-visualizer.component.ts
> +    return formatDirectiveProfile(bargraphNode.directives || []);
nit: Same here, let's use `??`.

2023-06-29 09:57 UTC, JeanMeche commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/record-formatter/bargraph-formatter/bargraph-formatter.ts
> +            ++;  // increment count of merged nodes with the same label
This linter isn't happy about a missing semi colon (`yarn lint`). Let's put comment before the line.

2023-06-30 05:25 UTC, AleksanderBodurri requested changes

2023-06-30 05:25 UTC, AleksanderBodurri commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/record-formatter/bargraph-formatter/bargraph-formatter.ts
> +        labelToBarGraphNodes[node.label].directives!.push(...node.original.directives);
I think we can remove this line

2023-06-30 05:25 UTC, AleksanderBodurri commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/recording-visualizer/bar-chart.component.ts
> +        value: Math.floor((node.value / max) * 100),
Hmm, I think we should do a few refactors here actually 🤔 

First we should make originalData be of type `BargraphNode[]`;

Then lets rename the `Data` interface to `BarData`, and modify it so that we have
```ts
interface BarData {
  label: string;
  count: number;
  width: number;
  time: number;
}
```

And then in the template we can reference the width and time as separate variables.

The line of code you highlight here for example should be
```ts
      this.internalData.push({
        label: node.label,
        count: node.count ?? 1,
        width: (node.value / max) * 100,
        time: node.value,
      });
```

2023-06-30 05:25 UTC, AleksanderBodurri commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/record-formatter/bargraph-formatter/bargraph-formatter.ts
> +  count?: number;  // number of merged nodes with the same label
Lets make this a required field

2023-06-30 05:25 UTC, AleksanderBodurri commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/recording-visualizer/bar-chart.component.html
> +    [matTooltip]="'Total time for all ' + bar.label + ' instances'"
Can we include the time and amount of instances in the tooltip as well?

2023-06-30 15:47 UTC, eneajaho commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/record-formatter/bargraph-formatter/bargraph-formatter.ts
> +        labelToBarGraphNodes[node.label].directives!.push(...node.original.directives);
If we don't save the directives, how can we show them in the table then? 

We cannot just show one there I think. We need to show all of them as they can have different time spent, also they're sum time will be the same as the total. 

@AleksanderBodurri 

![CleanShot 2023-06-30 at 17 44 59@2x](https://github.com/angular/angular/assets/25394362/e2b8276f-ecd0-4e66-9002-4df58e7fd7a5)

2023-06-30 15:53 UTC, eneajaho commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/recording-visualizer/bar-chart.component.html
> +    [matTooltip]="'Total time for all ' + bar.label + ' instances'"
Because the tooltip and the bar will have the same text, I'm refactoring it to a function that generates the bar text.

2023-07-08 19:06 UTC, eneajaho commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/record-formatter/bargraph-formatter/bargraph-formatter.ts
> +        labelToBarGraphNodes[node.label].directives!.push(...node.original.directives);
@AleksanderBodurri 
Any comment on this one?

2023-07-12 20:36 UTC, AleksanderBodurri commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/record-formatter/bargraph-formatter/bargraph-formatter.ts
> +        labelToBarGraphNodes[node.label].directives!.push(...node.original.directives);
Ahh good point 🤔

The main concern I have with this line is that `labelToBarGraphNodes[node.label].directives.push(...)` is mutating the directives array directly. Ideally any transformations we do to the input data to generate the output (the formatted data for our visualizer) does not modify the input data at all

2023-08-09 11:11 UTC, eneajaho commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/record-formatter/bargraph-formatter/bargraph-formatter.ts
> +        labelToBarGraphNodes[node.label].directives!.push(...node.original.directives);
@AleksanderBodurri 
The directives array I believe is needed in order to show correct info regarding where time was spent (changes (CD), outputs or lifecycle hooks), and also we don't change the original directives array but the array we created specifically for the purpose of storing those which added time to total time. So, I think it's ok to modify it. 

Please let me know what I can do in order to merge this PR 🙌

2023-08-09 12:08 UTC, JeanMeche commented
Enea, can you squash your commits, rebase on main and remove that merge commit. Thank you 👍🏻

2023-08-31 20:32 UTC, AleksanderBodurri approved these changes
Thanks for the PR @eneajaho 🙏  Could you rebase to main and make sure that the commit message is formatted correctly? Will tag for merge after that

2023-09-02 17:05 UTC, JeanMeche commented
@eneajaho Can you drop that merge commit and do a rebase on main instead ?

2023-09-02 17:06 UTC, eneajaho commented
> @eneajaho Can you drop that merge commit and do a rebase on main instead ?

I'm figuring it out 😅 Give me a sec

2023-09-21 14:37 UTC, AleksanderBodurri approved these changes

2023-09-22 16:50 UTC, dylhunn commented
This PR was merged into the repository by commit ee6c915c82b838ee1b3a1e979ab8dc70b3986485.

2023-09-22 16:50 UTC, closed without merging