feat(language-service): support to fix missing required inputs diagno…
angular/angular pull request #50911
Opened 2023-07-01 03:55 UTC by ivanwonder

…stic

Support to add the missing required inputs into the element and append after the last attribute of the element.

But it skips the structural directive shorthand attribute. For example, `<a *ngFor=""></a>`, its shorthand is `<ng-template ngFor>`, the `valueSpan` of the `ngFor` is empty, and the info is lost, so it can't use to insert the missing attribute after it.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2025-06-04 15:31 UTC, thePunderWoman commented
@ivanwonder Sorry for the long wait on getting this looked at. If you're still willing to get this landed, can you rebase and resolve the conflicts. It looks like a nice feature to get landed.

2025-06-04 15:43 UTC, thePunderWoman commented
> @ivanwonder Sorry for the long wait on getting this looked at. If you're still willing to get this landed, can you rebase and resolve the conflicts. It looks like a nice feature to get landed.

Actually, nevermind on the rebase. I was able to resolve those for you.

2025-06-04 16:40 UTC, thePunderWoman commented
@ivanwonder Yeah, looks like even with resolving the conflicts, this is broken. Can you take a look?

2025-06-05 02:09 UTC, ivanwonder commented
> @ivanwonder Yeah, looks like even with resolving the conflicts, this is broken. Can you take a look?

OK, I'll take a look.

2025-06-05 13:39 UTC, ivanwonder commented
> @ivanwonder Yeah, looks like even with resolving the conflicts, this is broken. Can you take a look?

@thePunderWoman Done. It seems that the `NgModule` does not recognize the standalone component in the test case.

2025-06-11 17:28 UTC, atscott approved these changes

2025-06-11 17:28 UTC, atscott commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +          } else {
```suggestion
          } else {
            // For other input types (numbers, objects, etc.), no type-specific shorthand
            // attribute suggestion is generated here. The general property binding suggestion
            // `[inputName]=""` (added below for all missing inputs) covers these cases.
```

2025-06-11 17:28 UTC, atscott commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +          const insertBoundText = `[${input.bindingPropertyName}]=""`;
```suggestion
          // As a general solution, always offer a property binding suggestion (e.g., `[inputName]=""`).
          // This is the most versatile way for users to satisfy a required input,
          // allowing them to bind to component properties or provide initial literal values.
          const insertBoundText = `[${input.bindingPropertyName}]=""`;
```

2025-06-11 17:28 UTC, atscott commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +          if (memberType.flags & tss.TypeFlags.BooleanLike) {
```suggestion
          // For boolean inputs, suggest adding the attribute name directly (e.g., `attrName`).
          // This is a common way to set boolean inputs to true.
          if (memberType.flags & tss.TypeFlags.BooleanLike) {
```

2025-06-11 17:28 UTC, atscott commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +              fixName: FixIdForCodeFixesAll.FIX_SPELLING,
Is FIX_SPELLING a historical choice or a way to categorize simple attribute additions that don't involve values or brackets, making it a common fix ID? Should the commented out lines be removed below?

2025-06-11 17:28 UTC, atscott commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +          } else if (memberType.flags & tss.TypeFlags.StringLike) {
```suggestion
          // For string inputs, suggest adding an empty string binding (e.g., `attrName=""`).
          } else if (memberType.flags & tss.TypeFlags.StringLike) {
```

2025-06-12 02:47 UTC, ivanwonder commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +              fixName: FixIdForCodeFixesAll.FIX_SPELLING,
https://github.com/microsoft/TypeScript/blob/dd1e258ba56f1b511879372c857fb625de3dec4a/src/services/types.ts#L963_L972

This fixName is a mistake. I'll fix it.

Now this doesn't support fixing all the same type of error, so I commented out the fixId.

2025-06-12 02:50 UTC, ivanwonder commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +              fixName: FixIdForCodeFixesAll.FIX_SPELLING,
Done

2025-06-16 18:51 UTC, atscott approved these changes

2025-06-16 23:24 UTC, atscott requested changes

2025-06-16 23:24 UTC, atscott commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +import tss from 'typescript/lib/tsserverlibrary';
```suggestion
import ts from 'typescript';
```

2025-06-16 23:24 UTC, atscott commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +import {Node} from '@angular/compiler/src/render3/r3_ast';
This should be `TmplAstNode` imported from `@angular/compiler`

2025-06-16 23:24 UTC, atscott commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +import {Reference} from '@angular/compiler-cli/private/migrations';
What's this type used for? I'm not seeing you read `transformType` anywhere. If you really need it, can we get it instead from 

```
import {DecoratorInputTransform} from '@angular/compiler-cli/src/ngtsc/metadata';
...
transformType: DecoratorInputTransform['type'] | null
```

2025-06-17 08:16 UTC, ivanwonder commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +import tss from 'typescript/lib/tsserverlibrary';
Done

2025-06-17 08:17 UTC, ivanwonder commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +import {Node} from '@angular/compiler/src/render3/r3_ast';
Done

2025-06-17 08:17 UTC, ivanwonder commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +import {Reference} from '@angular/compiler-cli/private/migrations';
Done

2025-06-17 08:21 UTC, ivanwonder commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +): ts.Type {
I forgot to support the input transform and the signal type.

@atscott This needs to be reviewed again.

2025-06-17 16:37 UTC, atscott approved these changes

2025-06-17 16:37 UTC, atscott commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +          // This is a common way to set boolean inputs to true.
This is making a bit of an assumption that the input's most common value is going to be `true`, right?

2025-06-17 16:37 UTC, atscott commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +          } else if (memberType.flags & ts.TypeFlags.StringLike) {
I think this along with the choice for booleans above is something we should consider looking for feedback on or removing in the first iteration. It makes those inputs static by default and also complicates this codefix a fair bit. All of the input type analysis would be unnecessary if we didn't have these.

2025-06-17 16:38 UTC, atscott approved these changes

2025-06-17 17:12 UTC, atscott commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +          // This is a common way to set boolean inputs to true.
BTW, does this approach work without the `booleanAttribute` transform?

2025-06-18 11:31 UTC, ivanwonder commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +          } else if (memberType.flags & ts.TypeFlags.StringLike) {
Ok, I'll remove this and look for feedback on

2025-06-18 12:15 UTC, ivanwonder commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +          } else if (memberType.flags & ts.TypeFlags.StringLike) {
Done

2025-06-18 12:19 UTC, ivanwonder commented on packages/language-service/src/codefixes/fix_missing_required_inputs.ts
> +          // This is a common way to set boolean inputs to true.
> BTW, does this approach work without the `booleanAttribute` transform?

Yes, this only cares about the input type.

2025-06-18 13:43 UTC, atscott approved these changes

2025-06-19 08:13 UTC, crisbeto commented
This PR was merged into the repository by commit 5d2e85920e714560e8d06bfb9c41d9312eeaae3b.

The changes were merged into the following branches: main

2025-06-19 08:13 UTC, closed without merging