[WIP] refactor(compiler): initial changes to compute defer block dependencies
angular/angular pull request #51162
Opened 2023-07-25 05:18 UTC by AndrewKushnir

⚠️ **Disclaimer** ⚠️ **this PR implements syntax that is still in an open RFC. It will be adjusted once the RFC is closed.**

This PR contains several commits (see each commit for additional info) that add initial version of the logic to compute dependencies of defer blocks used in a template. The code contains a few TODOs that will be resolved in followup PRs.

TODOs for this PR: add extra tests to cover more use-cases, resolve type-related TODOs.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2023-07-25 20:23 UTC, alxhub requested changes

2023-07-25 20:23 UTC, alxhub commented on packages/compiler/src/render3/view/template.ts
> +          const importExpr = (new o.DynamicImportExpr(fileName)).prop('then').callFn([innerFn]);
Shouldn't we coalesce multiple imports from the same location?

2023-07-25 20:23 UTC, alxhub commented on packages/compiler/src/render3/view/t2_binder.ts
> +    if (directives.length > 0 && !this.isInDeferBlock) {
This seems odd to me - the binder shouldn't be ignoring directives inside defer blocks completely. That's going to mess up future processing and responses, like the below logic which tries to determine the target of local references.

2023-07-25 22:33 UTC, AndrewKushnir commented on packages/compiler/src/render3/view/template.ts
> +          const importExpr = (new o.DynamicImportExpr(fileName)).prop('then').callFn([innerFn]);
Thanks Alex! Yes, we should coalesce multiple imports. I'll take a note on it and will create a followup PR with the improvement (to keep things simple in TDB in this PR).

2023-07-25 23:26 UTC, AndrewKushnir commented on packages/compiler/src/render3/view/t2_binder.ts
> +    if (directives.length > 0 && !this.isInDeferBlock) {
This check prevents adding found directives to the set that is later returned from `getUsedDirectives()` function (and later treated as "eager" in the `.../annotations/component/src/handler.ts`). The logic below in this function still has access to all matched directives (from the local `directives` set).

2023-07-26 01:52 UTC, AndrewKushnir commented on packages/compiler/src/render3/view/t2_binder.ts
> +    if (directives.length > 0 && !this.isInDeferBlock) {
As we discussed offline, I've pushed one more commit with the changes to retain an old interface of the DirectiveBinder class and introduce 2 new methods to retrieve eagerly used directives and pipes: https://github.com/angular/angular/pull/51162/commits/7faa2264aac11fa4b533130646c58f7de3085b40.

2023-07-26 02:30 UTC, AndrewKushnir commented
[Exploratory presubmit](https://test.corp.google.com/OCL:551028495:BASE:551064988:1690338620872:afc1ea1e).

2023-07-28 22:18 UTC, alxhub approved these changes

2023-07-29 20:49 UTC, AndrewKushnir commented
[Global presubmit](https://test.corp.google.com/OCL:551028495:BASE:552142744:1690663752138:20a2b7c3).

2023-07-30 03:40 UTC, AndrewKushnir commented
Caretaker note: [the TGP is "green"](https://fusion2.corp.google.com/presubmit/551028495/OCL:551028495:BASE:552153337:1690670321007:452b13b9/targets), this PR is ready for merge.

2023-08-01 18:50 UTC, alxhub commented
This PR was merged into the repository by commit efb486e8bc8712a961a73180fed324bbaac93348.

2023-08-01 18:50 UTC, closed without merging