[WIP] refactor(compiler): apply component metadata asynchronously when defer blocks are present
angular/angular pull request #51182
Opened 2023-07-27 01:25 UTC by AndrewKushnir

⚠️ **Disclaimer** ⚠️ **this PR uses a syntax that is still in an open RFC. It will be adjusted once the RFC is closed.**

**NOTE**: this PR is based on top of PR #51162, so only the last commit (https://github.com/angular/angular/commit/83b02bb5accc7297e7a45732d2363aa5f4072a92) contains a new change.

This commit updates compiler logic to generate the `setClassMetadataAsync` calls for components that used defer blocks. The `setClassMetadataAsync` function loads deferrable dependencies and invokes the `setClassMetadata` synchronously once everything is loaded. This change is needed to avoid eager references to deferrable symbols in component metadata in generated code.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2023-08-02 04:28 UTC, AndrewKushnir commented
Currently blocked by PR #51171.

2023-08-03 17:45 UTC, alxhub requested changes

2023-08-03 17:45 UTC, alxhub commented on packages/core/src/render3/jit/directive.ts
> +  if (getAsyncClassMetadata(type)) {
`compileComponent` is JIT compilation and should have nothing to do with async metadata. Note that this is production code, so it's odd that it refers to TestBed.

Instead, it should be `TestBed` which complains only if you try to override metadata on a component that had unresolved async metadata.

2023-08-03 19:27 UTC, AndrewKushnir commented on packages/core/src/render3/jit/directive.ts
> +  if (getAsyncClassMetadata(type)) {
Thanks Alex, that makes sense 👍 I've moved this check to the TestBed at the location where we invoked `compileComponent` function.

2023-08-03 19:29 UTC, AndrewKushnir commented
@alxhub thanks for the review, the feedback is now addressed, please take a look when you get a chance.

2023-08-04 23:41 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:553945808:BASE:553945846:1691192451072:225c5304).

2023-08-08 03:47 UTC, AndrewKushnir commented
[Global Presubmit](https://test.corp.google.com/OCL:553945808:BASE:554678779:1691466432014:134fa59d).

2023-08-10 02:24 UTC, AndrewKushnir commented
[Global Presubmit](https://test.corp.google.com/OCL:553945808:BASE:555342377:1691634234922:7bba6a60).

2023-08-11 22:58 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/annotations/component/src/handler.ts
> +      const rewrittenDecoratorsNode = removeIdentifierReferences(
Aren't we doing this via `setAsyncClassMetadata` anyway? Why would we need to remove the deferred symbols here?

This seems like we're changing the meaning of the user's decorator, which we should try and avoid.

2023-08-14 03:15 UTC, AndrewKushnir commented on packages/compiler-cli/src/ngtsc/annotations/component/src/handler.ts
> +      const rewrittenDecoratorsNode = removeIdentifierReferences(
We are not removing symbols themselves, we replace existing identifier objects with new ones that do not have connections to the import declarations, [see function logic here](https://github.com/angular/angular/blob/main/packages/compiler-cli/src/ngtsc/annotations/common/src/metadata.ts#L162-L176) (function name is a bit confusing). The decorator shape remains the same. We also perform a very similar operation in [another place](https://github.com/angular/angular/blob/main/packages/compiler-cli/src/ngtsc/annotations/common/src/metadata.ts#L39-L49) (also related to class metadata).

2023-08-14 18:16 UTC, alxhub approved these changes

2023-08-15 00:22 UTC, AndrewKushnir commented
**Caretaker note**: TGP is "green", this PR is ready for merge.

2023-08-15 18:32 UTC, closed without merging