docs: mention DomSanitizer in ElementRef documentation
angular/angular pull request #51207
Opened 2023-07-30 19:03 UTC by ToneyPK

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
In the current state, the documentation suggests that usage of `Renderer2` provides a safe way to access DOM elements. It only provides a wrapper method around it thus we are not using DOM API directly when coding, which is fine, but doesn't provide any additional security so it might be confusing. (to me it was until I checked the source code and saw that I also need to use `.sanitize()` for security benefits)

Sorry if I misunderstood something.

Issue Number: N/A

## What is the new behavior?
I mentioned the `DomSanitizer` so that it is a bit more clear that using `Renderer2` isn't enough by itself but for maximum security but that it should be used in combination with the `DomSanitizer`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-07-30 20:17 UTC, JeanMeche commented
Hi, can you run `yarn lint` to fix the linting issues ?

2023-07-30 20:38 UTC, ToneyPK commented
@JeanMeche 
> Hi, can you run `yarn lint` to fix the linting issues ?

Done, sorry about that.

2023-07-31 17:23 UTC, ToneyPK commented on packages/core/src/linker/element_ref.ts
> +   * recommended to use {@link DomSanitizer} in combination with the {@link Renderer2}.
@bougwal 
In my opinion we should either remove the mention of Renderer2 entirely in ElementRef docs and just mention the DomSanitizer OR we can actually make Renderer2 actually do a security check as I suggested in https://github.com/angular/angular/issues/51208

What do you say?

2023-07-31 17:28 UTC, JeanMeche commented on packages/core/src/linker/element_ref.ts
> +   * recommended to use {@link DomSanitizer} in combination with the {@link Renderer2}.
Adding sanitization will be probably too much of a breaking change.  Let's do rather the change suggested by pawel !

2023-07-31 19:13 UTC, ToneyPK commented on packages/core/src/linker/element_ref.ts
> +   * recommended to use {@link DomSanitizer} in combination with the {@link Renderer2}.
What do you think about current changes?

2023-08-01 14:10 UTC, JeanMeche commented on packages/core/src/linker/element_ref.ts
> +   * recommended to use {@link DomSanitizer} in combination with the {@link Renderer2}.
It looks good 👍. 
The broken test is unrelated, you just need a final review from the team and you're good to go !

2023-10-18 19:11 UTC, alxhub requested changes

2023-10-18 19:11 UTC, alxhub commented on packages/core/src/linker/element_ref.ts
> +   * recommended in combination with {@link DomSanitizer} for maxiumum security;
I believe the "safely" here originally referred to server-side rendering and other non-browser options, not security.

We should link to the guide on this: https://angular.io/guide/security#direct-use-of-the-dom-apis-and-explicit-sanitization-calls.

2023-10-18 19:11 UTC, alxhub commented on packages/core/src/render/api.ts
> + * extra security which makes it equivalent to {@link ElementRef}.
Same here - this should link to https://angular.io/guide/security#direct-use-of-the-dom-apis-and-explicit-sanitization-calls instead.

2023-12-22 15:53 UTC, meeque commented on packages/core/src/linker/element_ref.ts
> +   * recommended in combination with {@link DomSanitizer} for maxiumum security;
I guess that @alxhub might be right about the original phrasing. The link seems also relevant.

Imho the focus of the documentation here should be on telling developers how to prevent XSS.

Personally, I would not put too much emphasis on the `DomSanitizer`. It just provides one out of many ways to use the `nativeElement` securely. Use of secure native DOM-APIs that prevent XSS by design, is another secure alternative. (I'm assuming this is what most users of `nativeElement` woiuld do.) Less elegantly, users might also perform manual HTML output encoding or validation to prevent XSS.

2024-11-24 22:07 UTC, JeanMeche commented
Closing this PR as it became stale.

2024-11-24 22:07 UTC, closed without merging