feat(zone): implement flag to ignore ngZone in message event listener
angular/angular pull request #51339
Opened 2023-08-12 07:24 UTC by AleksanderBodurri

This flag allows message event listeners to prevent callbacks from executing within the NgZone if they contain a special `__ignore_ng_zone__` flag.

This flag is built with Angular DevTools in mind, where it prevents an infinite change detection loop in inspecting applications that have message event listeners:

CD -> Inspected app emits componentTreeDirty event to DevTools -> DevTools emits event to get new component Tree from Inspected app -> Inspected app message event listener fires -> CD

closes #45572

2023-08-14 21:04 UTC, dgp1130 requested changes
Are there any tests in Zone.js or DevTools we should update?

It would be very cool if we could have an e2e test for DevTools which runs on an app that sends a `MessageEvent` and confirms that things don't break. That might be a very involved test though, so I don't think it's strictly blocking here. Just some kind of automated validation would be useful.

2023-08-14 21:04 UTC, dgp1130 commented on devtools/src/app/app.component.ts
> +  }
Was this intended for testing? Can we delete this part of the change?

2023-08-16 00:23 UTC, JiaLiPassion commented on packages/core/src/zone/ng_zone.ts
> +          }
I believe it is ok that we only add this logic to `onInvokeTask`, since `message` is an `eventTask` and triggers the `onInvokeTask` callback.

And `onInvoke` hook is triggered when `ngZone.run(fn)` is invoked.

2023-08-16 00:25 UTC, JiaLiPassion approved these changes
LGTM! Thank you.

2023-08-16 10:44 UTC, mikezks commented
@brandonroberts, @markostanimirovic 

Will this fix the issue with the Redux DevTools for NgRx in combination with the Angular DevTools as well?

2023-08-16 12:07 UTC, brandonroberts commented
> @brandonroberts, @markostanimirovic
> 
> Will this fix the issue with the Redux DevTools for NgRx in combination with the Angular DevTools as well?

Maybe. We recently introduced a change in NgRx 16.2 that lets you opt-out with StoreDevtools. https://github.com/ngrx/platform/issues/3839

It may be possible that we send this flag along with the message to the DevTools, but then it may show up in the action log. Needs more investigation there.

2023-08-16 16:17 UTC, dgp1130 commented on packages/core/src/zone/ng_zone.ts
> +          }
Ok makes sense. An opt-out for `ngZone.run` doesn't make a whole lot of sense, so limiting to `onInvokeTask` sounds right.

2023-08-28 17:40 UTC, dgp1130 approved these changes
LGTM, I'll leave the question of how to handle `__ignore_ng_zone__` check for callbacks with multiple arguments to you. I don't feel very strongly about it, just something which stood out to me.

2023-08-31 17:23 UTC, AndrewKushnir approved these changes

2023-08-31 22:09 UTC, dgp1130 commented on packages/core/src/zone/ng_zone.ts
> +  }
Followed up outside GitHub, apparently `task.invoke` is only ever called with a single argument:
https://github.com/angular/angular/blob/3658e25f2eb884fc0b1cea0203a5244d7c592581/packages/zone.js/lib/common/events.ts#L125

The ideal behavior in this case is a bit unclear, since we're not too sure what the semantics or expected contract would be if multiple arguments are passed in the future. For now we'll just restrict this to single argument calls, if it becomes a problem in the future we should hopefully have a better sense of what the right behavior is here.

2023-08-31 22:09 UTC, dgp1130 approved these changes

2023-09-01 23:32 UTC, AndrewKushnir approved these changes

2023-09-01 23:34 UTC, AndrewKushnir commented
[Presubmit](http://test/OCL:562076119:BASE:562076137:1693611269241:a39dd0de).

2023-09-02 19:41 UTC, AndrewKushnir commented
**Caretaker note**: TGP is "green".

2023-09-02 19:43 UTC, AndrewKushnir commented
@AleksanderBodurri could you please update commit messages to change them from `feat` to `refactor`? This would avoid a confusion in changelog, since this is not a feature that we want to expose publicly, it's more a compatibility improvement between Angular and DevTools.

2023-09-05 17:48 UTC, AndrewKushnir commented
**Caretaker note**: there was a rebase to update commit messages, but there were no changes to the code, so we can reuse a previous TGP which was "green".

2023-09-05 18:16 UTC, jessicajaniuk commented
This PR was merged into the repository by commit 4b54947c97568352decf4b54938d5a1eb5ae26f5.

2023-09-05 18:16 UTC, closed without merging