Migrate monitoring jobs
angular/angular pull request #51350
Opened 2023-08-14 15:45 UTC by josephperrott

2023-08-14 15:53 UTC, pkozlowski-opensource commented
@josephperrott looks like this PR still needs a bit of cleanup (lint job is failing)

2023-08-21 11:39 UTC, devversion approved these changes
Nice, that's so clean!

2023-08-21 11:39 UTC, devversion commented on .github/workflows/monitoring.yml
> +    - cron: '0 10 * * *'
Do you want to add a comment like in Circle?

2023-08-21 11:39 UTC, devversion commented on .github/workflows/monitoring.yml
> +  check_aio_production:
Nit: Do we just want to name this `check_aio_deployments`? We are not deploying any canary/staging so production seems to be more confusing than helpful IMO

2023-08-21 15:22 UTC, AndrewKushnir commented
(FYI, changing the label from "merge" -> "review", since there is some feedback from Paul)

2023-08-21 21:40 UTC, MarkTechson requested changes
we should keep the one that wasn't dead, I commented.

2023-08-21 21:40 UTC, MarkTechson commented on aio/content/marketing/contributors.json
> -    "website": "https://unravelweb.dev",
This URL is not dead.

2023-08-21 22:48 UTC, josephperrott commented on aio/content/marketing/contributors.json
> -    "website": "https://unravelweb.dev",
reverted

2023-08-21 23:35 UTC, AndrewKushnir commented
(FYI, removing the "merge" label since the PR needs a re-review from Mark)

2023-08-27 02:55 UTC, MarkTechson approved these changes
LGTM

2023-08-30 19:41 UTC, jessicajaniuk commented
This PR was merged into the repository by commit e6235accb11fd63854d37c910212b5125ef435e4.

2023-08-30 19:42 UTC, closed without merging