docs(): migrate template guide and its code examples to standalone.
angular/angular pull request #51364
Opened 2023-08-15 06:34 UTC by wardbell

Guide pages do not mention `NgModule` so they are untouched (and not "reviewed" either).

All code was migrated, including code in the `template-expression-operators` folder despite it only being referenced in the “archived” guide, `template-expression-operators.md`.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-08-15 07:54 UTC, eneajaho commented on aio/content/examples/template-expression-operators/src/app/app.component.ts
> +    CurrencyPipe, DatePipe, JsonPipe, LowerCasePipe, TitleCasePipe, UpperCasePipe
Doesn't CommonModule export all these pipes?

2023-08-15 13:03 UTC, MarkTechson requested changes
I think this is close, just need to update a few small nits/questions.

2023-08-15 13:03 UTC, MarkTechson commented on aio/content/examples/template-expression-operators/src/app/app.component.ts
> +    CurrencyPipe, DatePipe, JsonPipe, LowerCasePipe, TitleCasePipe, UpperCasePipe
Another question, is there any reason to not list these vertically?

2023-08-15 13:03 UTC, MarkTechson commented on aio/content/examples/template-syntax/src/app/app.component.ts
> +    BigHeroDetailComponent, HeroDetailComponent,
One import per line perhaps?

2023-08-15 20:08 UTC, wardbell commented on aio/content/examples/template-expression-operators/src/app/app.component.ts
> +    CurrencyPipe, DatePipe, JsonPipe, LowerCasePipe, TitleCasePipe, UpperCasePipe
I thought they would be easier to see lumped together. Moot now that the pipe list is removed.

2023-08-15 20:08 UTC, wardbell commented on aio/content/examples/template-syntax/src/app/app.component.ts
> +    BigHeroDetailComponent, HeroDetailComponent,
OK. They are in one line because they are defined in the same file. That's MY convention, not Ng's

2023-08-21 18:53 UTC, MarkTechson approved these changes
LGTM

2023-08-21 23:58 UTC, AndrewKushnir approved these changes

2023-08-25 18:53 UTC, twerske approved these changes

2023-08-28 18:36 UTC, jessicajaniuk commented
This PR was merged into the repository by commit a28864d0f74a7a001cce02fedaee0187533714a9.

2023-08-28 18:36 UTC, closed without merging