docs(animations): update animation docs to be standalone first
angular/angular pull request #51390
Opened 2023-08-16 17:44 UTC by MarkTechson

Update the animation example files to be standalone and use boostrap application, update the documentation to prioritize standalone

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:
Examples have been updated to use bootstrap application and the standalone flag.

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Animations docs are focused on standalone

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-08-16 17:52 UTC, eneajaho commented on aio/content/guide/route-animations.md
> +Create a `Routes` array to define a set of routes. Add the routes to the `provideRouter` function in the providers array of the `bootstrapApplication` function call in `main.ts`.
Hello @MarkTechson 

When we create a new Angular app from scratch our bootstrapApplication looks like this: 

```ts
bootstrapApplication(AppComponent, appConfig)
```

And the appConfig in `app.config.ts` has the providers array. 

Do we wanna move away from that default?

2023-08-18 19:09 UTC, MarkTechson commented on aio/content/guide/route-animations.md
> +Create a `Routes` array to define a set of routes. Add the routes to the `provideRouter` function in the providers array of the `bootstrapApplication` function call in `main.ts`.
Good call out, this should be fixed now!

2023-08-18 20:19 UTC, eneajaho commented on aio/content/examples/animations/src/app/app.config.ts
> +        provideProtractorTestingSupport(),
```suggestion
        provideProtractorTestingSupport(), // needed only for docs 
```

2023-08-18 20:22 UTC, MarkTechson commented on aio/content/examples/animations/src/app/app.config.ts
> +        provideProtractorTestingSupport(),
Hmm, I think that in this case we can just leave it as is? Unless you feel like someone may misconstrue why this would be needed?

2023-08-18 20:23 UTC, eneajaho commented on aio/content/guide/route-animations.md
> +- Add the routes to the `provideRouter` function in the providers array in the `bootstrapApplication` function call in `app.config.ts`.
```suggestion
- Add the routes to the `provideRouter` function in the providers array in the `app.config.ts`.
```

2023-08-18 20:42 UTC, jessicajaniuk requested changes

2023-08-18 20:42 UTC, jessicajaniuk commented on aio/content/examples/animations/src/app/app.component.ts
> +import { ChildrenOutletContexts, RouterModule, RouterOutlet } from '@angular/router';
Since this is supposed to be about switching to standalone, we should import the bits from the Router that we need instead of the whole RouterModule.

2023-08-18 20:42 UTC, jessicajaniuk commented on aio/content/examples/animations/src/app/hero-list-page.component.ts
> +import { CommonModule } from '@angular/common';
This is fine, but if you know what you are actually using from the CommonModule, you should probably just import those things rather than the whole module.

2023-08-18 21:25 UTC, MarkTechson commented on aio/content/guide/route-animations.md
> +- Add the routes to the `provideRouter` function in the providers array in the `bootstrapApplication` function call in `app.config.ts`.
GREAT catch!

2023-08-18 21:25 UTC, MarkTechson commented on aio/content/examples/animations/src/app/app.component.ts
> +import { ChildrenOutletContexts, RouterModule, RouterOutlet } from '@angular/router';
true.

2023-08-21 17:49 UTC, bencodezen approved these changes
Looks great from my end. Nice job @MarkTechson! 🙌

2023-08-21 18:49 UTC, MarkTechson commented
@jessicajaniuk I've updated the code based on your feedback

2023-08-21 18:53 UTC, jessicajaniuk approved these changes
LGTM!

2023-08-21 20:01 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 38671f7c1425c701f9eca946663f8f2481856734.

2023-08-21 20:01 UTC, closed without merging