docs: add v17 versions support
angular/angular pull request #51443
Opened 2023-08-21 17:33 UTC by JeanMeche

* Node 16 support is dropped per angular/angular-cli#25675 
* TS 5.2 is supported per #51334

2023-08-21 17:38 UTC, alan-agius4 commented on aio/content/guide/versions.md
> +| 17.0.x             | ^18.13.0                             | >=4.9.3 <5.3.0 | ^6.5.3 \|\| ^7.4.0 |
I recommend that we do this in a separate PR so that we only target the main branch.

2023-08-21 18:05 UTC, JeanMeche commented on aio/content/guide/versions.md
> +| 17.0.x             | ^18.13.0                             | >=4.9.3 <5.3.0 | ^6.5.3 \|\| ^7.4.0 |
Should start from the 16.2.x branch for the 16.2 update ?

2023-08-21 20:25 UTC, JeanMeche commented on aio/content/guide/versions.md
> +| 17.0.x             | ^18.13.0                             | >=4.9.3 <5.3.0 | ^6.5.3 \|\| ^7.4.0 |
See #51448, is this what you meant ?

2023-08-22 02:45 UTC, alan-agius4 commented on aio/content/guide/versions.md
> +| 17.0.x             | ^18.13.0                             | >=4.9.3 <5.3.0 | ^6.5.3 \|\| ^7.4.0 |
Yes, thanks

2023-09-13 05:16 UTC, alan-agius4 commented
The removal of support of Node.js 16 hasn’t actually landed yet in the framework.

2023-09-13 11:07 UTC, alan-agius4 approved these changes

2023-10-11 18:20 UTC, dylhunn approved these changes

2023-11-05 19:24 UTC, LayZeeDK commented
issue: add `6208865206c9a9402ba21afffe982f2192a19438` to include v16.2.x version compatibility.

2023-11-05 19:24 UTC, LayZeeDK requested changes
Request change.

2023-11-05 19:24 UTC, LayZeeDK commented on aio/content/guide/versions.md
>  | 16.1.x             | ^16.14.0 \|\| ^18.10.0               | >=4.9.3 <5.2.0 | ^6.5.3 \|\| ^7.4.0 |
issue: add `6208865206c9a9402ba21afffe982f2192a19438` to include v16.2.x version compatibility.

2023-11-06 23:28 UTC, AndrewKushnir approved these changes

2023-11-08 16:50 UTC, atscott commented
This PR was merged into the repository by commit 289a178ef0af2c0f8ac3c41097a7bbea7985994d.

2023-11-08 16:50 UTC, closed without merging