docs: migrate user-input code example to standalone
angular/angular pull request #51466
Opened 2023-08-23 01:05 UTC by bencodezen

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-08-23 18:26 UTC, MarkTechson requested changes

2023-08-23 18:26 UTC, MarkTechson commented on aio/content/examples/user-input/src/main.ts
> +}).catch((err) => console.error(err));
Can we remove the catch here?

2023-08-25 18:56 UTC, jessicajaniuk approved these changes

2023-08-25 19:00 UTC, twerske approved these changes

2023-08-28 16:05 UTC, bencodezen commented on aio/content/examples/user-input/src/main.ts
> +}).catch((err) => console.error(err));
```suggestion
})
```

I got you!

2023-08-28 16:35 UTC, twerske approved these changes

2023-08-31 01:11 UTC, MarkTechson approved these changes
LGTM

2023-08-31 16:37 UTC, jessicajaniuk commented
This PR was merged into the repository by commit e4d2018f46d5b08d1de4e9f8d22fa294c0878286.

2023-08-31 16:37 UTC, closed without merging