docs: Migrate Observables guides & code examples to standalone
angular/angular pull request #51516
Opened 2023-08-27 00:24 UTC by wardbell

None of the guide pages mentions ngModules. Only `observables-in-angular` needed conversion to Standalone.

However, some of the guide pages reflect old versions of RxJS, including signatures that are no longer valid. These have been corrected.

More significantly, *the existing guide is pretty bad at explaining RxJS and its usage*. It was written (by me I think) in the very early days of Angular and Angular RxJS instruction. I've taught numerous "RxJS in Angular" classes since and learned from that experience what does and does not work with students.

There was neither the time nor the charter to completely overhaul this guide. But this commit attempts to remove what flops with students and to bring the teaching closer to what seems more effectively. I hope reviewers agree that my revisions are an improvement.

**Revised Overview**

The overview doc, `observables.md`, had a few errors (ex: `next` is NOT REQUIRED) and deprecated patterns (you now must pass the Observer object to `subscribe`).

More importantly, it was wildly overcomplicated and scary, especially when it got into multi-casting.

Angular docs are not the place to learn RxJS. Hardly anyone needs to know about multi-casting and certainly not in this depth.

Therefore, I deleted that section (and its multicasting.ts code), corrected mistakes and tried to make RxJS a little more approachable.

I also reworked the "Basic usage and terms" section to be more comprehensive and more clear.

Finally, I moved the "Naming conventions for observables" section here from `rx-library`. It made more sense for it to be here. This is the section that describes the dollar-sign convention.

**Revised "RxJS Library" page and code**

*RxJS no longer supports chaining* and hasn't for a very long time. Removed note in `rx-library.md` that suggested you could use operator chaining.

The RxJS `pipe` discussion in the "Operators" section was just weird. Almost no one calls the `pipe` function. We certainly should *start* there. We should start with how people actually use operators - by adding them to the argument list of the `Observable.pipe()` method.

I kept the original `pipe` function example but subordinated it in a "callout". Most readers will (and should) ignore it.

`Subject` is a *critically important RxJS mechanism for creating custom observables*. It was completely missing from the list of observable creators on this guide page. So I added it to the "Observable creation functions" section of the guide and wrote an accompanying `MessageService` code sample (see the new `rx-library/app/` folder).

The `MessageService` is a pretty common pattern in Angular apps - far more common than creating an observable from a counter or an event, two of the creation patterns currently on this page.

This new section also afforded an opportunity to show how RxJS helps with building loosely coupled applications. We will soon be talking about Signals. Many will wonder whether and when they should still use RxJS.

At least a partial answer is that RxJS is really good at progressively combining and enhancing streams of data as they cross component boundaries. Of course you can pass signals around; but they are not as rich in transformers as RxJS. This is where RxJS shines.

**Revised "Comparing observables"**

The Promises section in `comparing-observables.md` had many errors and misleading remarks.

The comparison of error handling was especially egregious; the code example for that was nonsense.

The "Chain" sub-section was really about transforming values. It also failed to demonstrate chaining promise `.then`s.

Reworked these sub-sections and improved the code samples to match.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-08-28 13:27 UTC, JeanMeche reviewed
I enjoyed reading these docs, it's well written. 

See below for my nits.

2023-08-28 17:14 UTC, wardbell commented on aio/content/guide/rx-library.md
> +An [RxJS `Subject`](https://rxjs.dev/guide/subject) is a popular way to create and control an observable of your own design.
Right you are! Fixing.

2023-08-28 17:22 UTC, MarkTechson requested changes
Small changes, but overall looks good.

2023-08-28 17:22 UTC, MarkTechson commented on aio/content/examples/rx-library/src/error-handling.ts
> +    // Important: the `catchError` argument must be a function that returns an observable.
To avoid the confusion, let's use a block comment:

```
/*
 * Catch the error, either from the AJAX call or from the map operator,
 * and return an observable of empty array.
 * Important: the `catchError` argument must be a function that returns an observable.
 */
```

This way, it'll be very clear that there is not `ovservable.catchError()`

2023-08-28 20:36 UTC, wardbell commented on aio/content/examples/rx-library/src/error-handling.ts
> +    // Important: the `catchError` argument must be a function that returns an observable.
I tried something to address this.

2023-08-28 20:37 UTC, wardbell commented on aio/content/guide/observables.md
> +Here's a simple observable that will emit `1`, then `2`, then `3`, and then stop (AKA "complete").
Agreed

2023-08-28 21:30 UTC, MarkTechson approved these changes
LGTM

2023-08-29 10:31 UTC, devversion approved these changes
LGTM for dev-infra (i.e. `.bzl`)

2023-08-30 21:29 UTC, twerske approved these changes

2023-08-30 23:00 UTC, wardbell commented on aio/content/guide/rx-library.md
> +An [RxJS `Subject`](https://rxjs.dev/guide/subject) is a popular way to create and control an observable of your own design.
Fixed

2023-08-31 16:49 UTC, atscott approved these changes

2023-08-31 17:00 UTC, jessicajaniuk approved these changes

2023-08-31 17:00 UTC, jessicajaniuk commented
This PR was merged into the repository by commit acd59ad0371a19838813cfc934a73fa3cc357602.

2023-08-31 17:00 UTC, closed without merging