docs(docs-infra): correct spelling praticesto practices, seperateto s…
angular/angular pull request #51527
Opened 2023-08-27 12:32 UTC by akib1997

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Correct some spellings

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-08-27 13:34 UTC, ernest-rudnicki commented on aio/content/marketing/contributors.json
> +    "bio": "Antonio is a senior Angular developer from Honduras, focus on immersive experiences and Web Performance, He is a public Speaker, Mentor and Facilitator for entrepreneurship programs as Te
I just noticed a bit weird grammar it this sentence. I think it should be more like this:
```suggestion
    "bio": "Antonio is a senior Angular developer from Honduras, who focuses on immersive experiences and Web Performance, He is a public Speaker, Mentor and Facilitator for entrepreneurship programs as Techstars Startup Weekend, Content Creator and tech writer Cofounder of non profit organization @Macaotech, Loves to share knowledge Typescript Coffee and Cats 🐱.",
```

What do you think?

2023-08-27 13:45 UTC, akib1997 commented on aio/content/marketing/contributors.json
> +    "bio": "Antonio is a senior Angular developer from Honduras, focus on immersive experiences and Web Performance, He is a public Speaker, Mentor and Facilitator for entrepreneurship programs as Te
Yes, it can be improved.

2023-08-27 14:20 UTC, akib1997 commented on aio/content/marketing/contributors.json
> +    "bio": "Antonio is a senior Angular developer from Honduras, focus on immersive experiences and Web Performance, He is a public Speaker, Mentor and Facilitator for entrepreneurship programs as Te
https://github.com/angular/angular/pull/51527/commits/7f4127e36512086bdd827c696de3c3fbfac62573

2023-08-28 16:36 UTC, twerske commented on aio/content/marketing/contributors.json
> +    "bio": "Antonio is a senior Angular developer from Honduras, who focuses on immersive experiences and Web Performance, He is a public Speaker, Mentor and Facilitator for entrepreneurship programs
This was written by the GDE themselves and I prefer not to edit their bio on their behalf. Please remove from the PR thank you!

2023-08-28 16:37 UTC, twerske requested changes
One comment and a lint fix needed! Thank you!

2023-08-28 17:08 UTC, akib1997 commented on aio/content/marketing/contributors.json
> +    "bio": "Antonio is a senior Angular developer from Honduras, who focuses on immersive experiences and Web Performance, He is a public Speaker, Mentor and Facilitator for entrepreneurship programs
https://github.com/angular/angular/pull/51527/commits/4118afc1cd5002585aea11739ac00f41575ef8f0

2023-08-29 05:43 UTC, akib1997 reviewed
Done this by keeping the bio as it was.

2023-11-09 01:06 UTC, twerske approved these changes

2023-11-09 01:06 UTC, twerske commented
Please resolve merge conflicts then we can merge

2024-01-20 21:42 UTC, JeanMeche commented
In absence of the required changes, I'll close this PR. feel free to reopen a new one.

2024-01-20 21:42 UTC, closed without merging