docs: migrate erorrs code example and guide to standalone
angular/angular pull request #51536
Opened 2023-08-28 16:39 UTC by bencodezen

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-08-28 16:47 UTC, MarkTechson requested changes

2023-08-28 16:47 UTC, MarkTechson commented on aio/content/errors/NG3003.md
>  @reviewed 2022-02-28
Can you please update the reviewed date?

2023-08-28 16:53 UTC, JeanMeche commented on aio/content/errors/NG3003.md
> +- Try to rearrange your dependencies to avoid the cycle.
This is likely unwanted, we only use `*` on the markdown lists

2023-08-29 05:01 UTC, twerske approved these changes

2023-08-29 17:19 UTC, bencodezen commented
@MarkTechson Ready for round 2!

2023-08-29 22:54 UTC, jessicajaniuk approved these changes

2023-08-29 22:54 UTC, jessicajaniuk commented on aio/content/examples/errors/cyclic-imports/child.component.ts
> +  template: 'The child!',
His name is Grogu.

2023-09-06 16:37 UTC, bencodezen commented
I think the only thing missing on this is to have @MarkTechson approve on this.

Let me know if I need to do anything else though!

2023-09-06 21:49 UTC, MarkTechson approved these changes
LGTM! ✅

2023-09-07 17:04 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 763314f3009a9ea605bad182798035e12a70a1e6.

2023-09-07 17:04 UTC, closed without merging