docs: Migrate Universal guide and code to Standalone
angular/angular pull request #51564
Opened 2023-08-30 05:20 UTC by wardbell

**DO NOT MERGE YET**

This is a draft of a migration to universal standalone.

I doubt it works. It is certainly full of holes ... holes that I cannot fill at present.

I've seasoned it with RED CALLOUTS for information I didn't understand or couldn't provide.

Ready for help!

**Added `universal-ngmodule`**

The existing ngModule-based doc has a lot of guidance for developers who are still building with NgModule. Given that we are preserving the existing NgModule guidance (with modifications), it seems prudent to preserve the NgModule form of the Universal guidance. So I copied the existing guide and code to `universal-ngmodule` and added it to the left-side navigation under the "NgModules" sub-tree.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-08-30 12:13 UTC, alan-agius4 requested changes
See comments.

2023-08-30 12:13 UTC, alan-agius4 commented on aio/angular.json
>          "build": {
This changes in this file does not seem right. As this effect the AIO apps itself.

2023-08-30 12:13 UTC, alan-agius4 commented on aio/package.json
>      "~~audit-web-app": "node scripts/audit-web-app.mjs",
This changes in this file does not seem right. As this effect the AIO apps itself.

2023-08-30 12:13 UTC, alan-agius4 commented on aio/server.ts
> +import 'zone.js/node';
This file should be deleted. (Same as previous)

2023-08-30 12:13 UTC, alan-agius4 commented on aio/src/app/app.server.module.ts
> +import { NgModule } from '@angular/core';
Same as previous.

2023-08-30 12:13 UTC, alan-agius4 commented on aio/src/main.server.ts
> +
Same as previous.

2023-08-30 12:13 UTC, alan-agius4 commented on aio/tsconfig.server.json
> +/* To learn more about this file see: https://angular.io/config/tsconfig. */
Same as previous.

2023-08-30 12:13 UTC, alan-agius4 commented on aio/yarn.lock
>      "@angular-devkit/core" "16.2.0-next.3"
Same as previous.

2023-08-30 12:14 UTC, alan-agius4 commented on aio/content/guide/universal.md
> +</div>
I am not understanding this callout.

2023-08-30 12:15 UTC, alan-agius4 commented on aio/content/guide/universal.md
> +<div class="alert is-critical">
This seems a problem with the migration itself. //cc @crisbeto

2023-08-30 12:16 UTC, alan-agius4 commented on aio/content/guide/universal.md
> +Does this command work? It didn't for me. IIRC, it didn't generate any of the asterisked files.
Looks like you ran the command in the wrong directory.

2023-08-30 12:21 UTC, alan-agius4 commented on aio/content/guide/universal.md
> +<div class="alert is-critical">
https://github.com/angular/angular/pull/51564/files#r1310182506

2023-08-30 12:22 UTC, alan-agius4 commented on aio/content/guide/universal.md
> +<div class="alert is-critical">
Technically, the requirement is that it supports Node.js APIs

2023-08-30 13:10 UTC, MarkTechson requested changes
Let's chat about how we can reduce the scope of the changes for this PR.

2023-08-30 15:35 UTC, josephperrott requested changes
Overall LGTM minus the changes to the actual AIO application itself

2023-08-30 17:55 UTC, wardbell commented on aio/server.ts
> +import 'zone.js/node';
REVERTING. See explanation above for how this happened.

2023-08-30 17:55 UTC, wardbell commented on aio/src/main.server.ts
> +
REVERTING. See explanation above for how this happened.

2023-08-30 17:55 UTC, wardbell commented on aio/tsconfig.server.json
> +/* To learn more about this file see: https://angular.io/config/tsconfig. */
REVERTING. See explanation above for how this happened.

2023-08-30 17:55 UTC, wardbell commented on aio/yarn.lock
>      "@angular-devkit/core" "16.2.0-next.3"
REVERTING. See explanation above for how this happened.

2023-08-30 18:10 UTC, wardbell commented on aio/content/guide/universal.md
> +Does this command work? It didn't for me. IIRC, it didn't generate any of the asterisked files.
Yes it does!  I think that explains why AIO itself was updated. Yikes. Reverted _that_ effect.

2023-08-30 18:14 UTC, wardbell commented on aio/content/guide/universal.md
> +Standalone doesn't use the `renderModule` function. The `renderApplication` function is hidden within `provideServerRendering`. Unfortunately, you can't pass any options to `provideServerRendering` a
That is tempting. But then how do you pass options?

2023-08-30 18:24 UTC, wardbell commented on aio/content/guide/universal.md
> +</div>
> Why reference the AOT compiler at all?

Not sure if the reader will know what the AOT compiler is ... or needs to know. The instructions in the guide don't offer a JIT alternative. It just seems unnecessary to say this.

If there really is a potential for trouble, what would that be? We should be more explicit about the concern if we're going to have this warning, don't you think?

I'm removing my red flag. You can let me know if you want to adjust the text.

2023-08-30 18:36 UTC, wardbell commented on aio/content/guide/universal.md
> +Is `server.ts` supposed to be generated? How could it know how to configure the ngExpressEngine?
We know that I screwed up running this command. The `server.ts` would have been generated if I had run it correctly.

My remaining concern is _how would it know how to setup `server.ts` without presupposing `bootstrap`, `app.config.ts`,  `app.server.config.ts` and `main.server.ts`?_

We don't discuss any of those things in this guide (or the original guide, preserved in `universal-ngmodule`).

2023-08-30 18:42 UTC, wardbell commented on aio/content/guide/universal.md
> +<div class="alert is-critical">
Added that qualifier and removed red note.

2023-08-30 21:17 UTC, wardbell commented on aio/content/guide/universal.md
> +</div>
In light of @jelbourn Slack comments about [minimizing AOT/JIT distinctions](https://angular-team.slack.com/archives/C05LN876AM9/p1693430083567749?thread_ts=1693427649.841489&cid=C05LN876AM9), should we just delete this AOT reference?

2023-08-30 21:19 UTC, JeanMeche commented on aio/content/guide/universal.md
> +</div>
I'd be in favor of it !

2023-08-30 21:24 UTC, JeanMeche commented on aio/content/guide/universal.md
> +The callout is kind of old. Is Client Hydration stable now?
cc @AndrewKushnir // @jessicajaniuk is Hydration going stable in v17 ?

2023-08-30 21:39 UTC, JeanMeche commented on aio/content/guide/universal.md
> +It passes `html`, not `index.html`.
The first parameter is a file extension, here `html` butut it could be something like `[jade](https://github.com/dscape/jade)`.  

So it's not a file, but is it worth mentioning ?

2023-08-30 22:54 UTC, wardbell commented on aio/content/guide/universal.md
> +It passes `html`, not `index.html`.
Not in this context where you are describing what is happening "under the hood". I was confused by the earlier calling out of the generated line, `server.engine('html', ngExpressEngine({ bootstrap }));`.

Removed the RED note.

2023-08-31 09:42 UTC, alan-agius4 commented on aio/content/guide/universal.md
> +Standalone doesn't use the `renderModule` function. The `renderApplication` function is hidden within `provideServerRendering`. Unfortunately, you can't pass any options to `provideServerRendering` a
Using the `ngExpressEngine`, typically users are discouraged to interact with these methods directly.

2023-08-31 09:46 UTC, alan-agius4 commented on aio/content/guide/universal.md
> +Is `server.ts` supposed to be generated? How could it know how to configure the ngExpressEngine?
- `app.server.config.ts`, `main.server.ts` and `server.ts` are generated when running `ng add @nguniversal/express-engine `
- `app.config.ts`, `app.routes.ts` and the `bootstrap` are standard for standalone applications that are generated using the Angular CLI. These however are not part of the style guide as the style guide itself was meant to be updated as a separate effort.

2023-08-31 09:48 UTC, alan-agius4 commented
`app.module.server.ts` should be renamed to `app.server.module.ts`, as the former was the old filename.

2023-08-31 21:14 UTC, wardbell commented
> `app.module.server.ts` should be renamed to `app.server.module.ts`, as the former was the old filename.

Hmm. That was in the OLD version of this doc, the `NgModule` version. Are you sure you want me to touch that? Happy to do so when you say "Yes"

2023-08-31 22:04 UTC, alan-agius4 commented
> Hmm. That was in the OLD version of this doc, the NgModule version. Are you sure you want me to touch that? Happy to do so when you say "Yes"

Happy to leave it part of a separate PR, but we should definitely update it. As that is the old naming convention and users will not find that file in there project.

2023-09-06 11:45 UTC, alan-agius4 commented on aio/content/guide/universal-ngmodule.md
> +# Server-side rendering (SSR) with Angular Universal (NgModule Version)
It appears that there is a lot of duplicate content between this and the standalone version, is that intentional?

2023-09-06 12:13 UTC, alan-agius4 commented on aio/content/guide/universal.md
> +<a id="boot-with-app-config"></a>
I feel like anything in this section is a better fit in the style guide.

Thoughts @MarkTechson & @jelbourn?

2023-09-06 19:52 UTC, wardbell commented on aio/content/guide/universal-ngmodule.md
> +# Server-side rendering (SSR) with Angular Universal (NgModule Version)
Yes it is intentional. 

The `universal-ngmodule.md` page exists _solely for folks who are still on the NgModules

2023-09-06 19:55 UTC, MarkTechson commented on aio/content/guide/universal.md
> +<a id="boot-with-app-config"></a>
This is a good callout @alan-agius4 but this is better suited for a different PR. I'll make a note and we should be good to go.

2023-09-06 19:56 UTC, MarkTechson approved these changes
LGTM 🚀

2023-09-07 07:41 UTC, alan-agius4 approved these changes

2023-09-11 23:42 UTC, twerske approved these changes

2023-09-12 18:04 UTC, josephperrott approved these changes
LGTM

2023-09-12 19:20 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 44c74694953d5cf8ee247a9a9b0076a186d9a071.

2023-09-12 19:20 UTC, closed without merging