docs: migrate toh-pt4 to standalone
angular/angular pull request #51612
Opened 2023-08-31 22:10 UTC by bencodezen

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-08-31 22:28 UTC, bencodezen commented
@MarkTechson @twerske  @jessicajaniuk I'm trying out the ng schematics automated migration for this PR. The tests say that everything passes, but the syntax looks a bit different from the way I've been doing it. 

Any guidance on whether this should be the preferred method going forward would be a great help!

2023-09-01 14:48 UTC, jessicajaniuk commented on aio/content/examples/toh-pt4/src/main.ts
> +    providers: [importProvidersFrom(BrowserModule, FormsModule)]
We should switch this to use the native providers rather than `importProvidersFrom`.

2023-09-01 17:50 UTC, jessicajaniuk requested changes
Other than the `importProvidersFrom` fix, this is good. Once that's updated, re-request my review.

2023-09-06 17:04 UTC, bencodezen commented on aio/content/examples/toh-pt4/src/main.ts
> +    providers: [importProvidersFrom(BrowserModule, FormsModule)]
I figured it out!

The `BrowserModule` is needed for Protractor, but to standardize, I've used the `provideProtractor...` helper so it's easy for us to deprecate once we finish this effort.

And the `FormsModule` is no longer needed as well. So that's gone now too!

2023-09-06 17:17 UTC, jessicajaniuk approved these changes

2023-09-06 22:13 UTC, MarkTechson approved these changes
LGTM

2024-01-26 17:36 UTC, closed without merging