docs: Phase2 - convert providers sample to Standalone
angular/angular pull request #51968
Opened 2023-09-30 22:52 UTC by wardbell

The `providers.md` page that goes with the `providers` sample code is listed in NgModules section. It seems to be the NgModule version of `dependency-injection-providers.md`.

I didn’t realize that this guidw was in the NgModules section until AFTER I had converted the sample code to Standalone and modified the text of `providers.md`.

In so doing, I improved the sample to show how to provide services in a route setup. This is actually working code, unlike the markdown version in `guide/standalone-components.md` !!!

Overall, I think the text and code changes are an improvement, properly inform the NgModules reader, and should be incorporated in the updated docs.

However, should you disagree, you can easily discard these changes as this commit is in its own PR.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-10-01 00:38 UTC, dylhunn approved these changes
Not sure if I'm the right reviewer for this. Perhaps Emma or Mark is?

2023-10-01 14:21 UTC, bougwal approved these changes

2023-10-01 14:21 UTC, bougwal commented on aio/content/guide/providers.md
> +## Providing services in NgMmodules
nit: typo
```suggestion
## Providing services in NgModules
```

2023-10-02 15:47 UTC, wardbell commented on aio/content/guide/providers.md
> +## Providing services in NgMmodules
Good catch. Fixed.

2023-10-09 21:55 UTC, MarkTechson requested changes

2023-10-09 21:55 UTC, MarkTechson commented on aio/content/guide/providers.md
I see that you've had to make some updates to reference new files that were created. Can we keep the changes to the text minimal here? The original text does not appear to be in conflict with being migrated to standalone. We can add a contextual label, such as "For NgModule based apps..." and make a concise suggestion. Is that possible here?

2024-01-26 18:30 UTC, closed without merging