doc(router): update withHashLocation return type
angular/angular pull request #52016
Opened 2023-10-04 13:10 UTC by Nicoss54

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
 This Pull request is a change on the router documentation

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currenty, according to the documentation, withHashLocationStrategy function return RouterConfigurationFeature type

## What is the new behavior?

Now withHashLocationStrategy return the correct alias type:  RouterHashLocationFeature

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2023-10-04 13:22 UTC, JeanMeche commented
Hi Nicolas, can you reword your commit message, this is more a `refactor` than a doc change !

2023-10-04 13:26 UTC, Nicoss54 commented
> Hi Nicolas, can you reword your commit message, this is more a `refactor` than a doc change !

@JeanMeche done, thanks for the feedback

2023-10-04 16:42 UTC, atscott approved these changes
reviewed-for: fw-router, public-api

2023-10-04 16:50 UTC, jessicajaniuk approved these changes
reviewed-for: public-api

2023-10-04 20:16 UTC, JeanMeche commented
I've pinged Nico about the linting issue. I'll provide some help if needed 👍

2023-10-05 13:16 UTC, JeanMeche requested changes
There are 2 things remaning before we can merge this: 

* fix the linting issue (format) 
* squash your commits

2023-10-05 16:24 UTC, JeanMeche approved these changes

2023-10-09 15:54 UTC, atscott commented
This PR was merged into the repository by commit e25006b341503d7e227d9bcbe1fd2fe66dc8d651.

2023-10-09 15:54 UTC, closed without merging