fix(platform-browser): prevent duplicate stylesheets from being created
angular/angular pull request #52019
Opened 2023-10-04 13:51 UTC by mattlewis92

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

In https://github.com/angular/angular/pull/51808 a change was made to prevent stylesheets from being destroyed and re-created every time the associated component is destroyed and re-created. Our application was being affected by the performance issue that PR was trying to fix, so we tried it out on our application. However, we noticed that it didn't work as expected and the stylesheets were still being created for each component initialisation, and worse the previously disabled stylesheets would remain in the document head and continue to grow as the user navigated around the app.

## What is the new behavior?

Stylesheets are now correctly re-used when components are destroyed and re-created, and no duplicates are created.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-10-04 13:58 UTC, crisbeto commented
Forwarding this to @alan-agius4 who was working with this recently.

2023-10-04 16:51 UTC, alan-agius4 requested changes
Hi @mattlewis92, thanks for this. I left some comments. Let me know if you need further clarifications or wish for me to take over.

Thanks again.

2023-10-04 16:51 UTC, alan-agius4 commented on packages/platform-browser/src/dom/shared_styles_host.ts
> +      const existingStyleElement =
I would prefer if we keep linear access, by updating `elements` to use a `Map`, this would also address the problem that the style node is being added to `elements` multiple times.

```ts
  private readonly styleRef = new Map<
    string /** Style string */,
    {
      elements: Map</** Host */ Node ,  /** Style Node */ HTMLStyleElement>;
      usage: number;
    }
  >();
```

2023-10-04 17:00 UTC, mattlewis92 commented on packages/platform-browser/test/dom/dom_renderer_spec.ts
> +      it('should not add duplicate stylesheets', async () => {
Running this on my branch will fail for me:
```
git checkout origin/main packages/platform-browser/src/dom/shared_styles_host.ts
yarn test //packages/platform-browser/test:test_web
...
Firefox 97.0 (Mac OS 10.15) DefaultDomRendererV2 When `REMOVE_STYLES_ON_COMPONENT_DESTROY` is `true` or default. should not add duplicate stylesheets FAILED
Expected 2 to be 1.
```

I suspect you might have made the same mistake as me and ran `//packages/platform-browser/test` instead of `//packages/platform-browser/test:test_web`

2023-10-04 17:01 UTC, mattlewis92 commented on packages/platform-browser/src/dom/shared_styles_host.ts
>      if (styleResult) {
Oh good catch, I will fix that!

2023-10-04 17:01 UTC, mattlewis92 commented on packages/platform-browser/src/dom/shared_styles_host.ts
> +      const existingStyleElement =
Oh yes, this is a much nicer solution!

2023-10-04 17:01 UTC, mattlewis92 commented
> Hi @mattlewis92, thanks for this. I left some comments. Let me know if you need further clarifications or wish for me to take over.
> 
> Thanks again.

Thanks for the quick review! I will make those changes now

2023-10-04 17:08 UTC, mattlewis92 commented on packages/platform-browser/src/dom/shared_styles_host.ts
> +      const existingStyleElement =
Fixed in [`02803ea` (#52019)](https://github.com/angular/angular/pull/52019/commits/02803ea01f9cbd2453281eee7b03c9c887796ba3)

2023-10-04 17:12 UTC, alan-agius4 commented on packages/platform-browser/src/dom/shared_styles_host.ts
> +      }
This does not need to be nested here, it can be moved at the very top of this function.

2023-10-04 17:15 UTC, mattlewis92 commented on packages/platform-browser/src/dom/shared_styles_host.ts
> +      }
Fixed in [`13fd0d5` (#52019)](https://github.com/angular/angular/pull/52019/commits/13fd0d5c15bfbc8c05b8ef8693a9e0d02d49f577)

2023-10-04 17:15 UTC, alan-agius4 reviewed
Couple of NITS

2023-10-04 17:15 UTC, alan-agius4 commented on packages/platform-browser/src/dom/shared_styles_host.ts
> +    const styleResult = styleRef.get(style);
```suggestion
    const styleResult = styleRef.get(style)! // This cannot never be undefined;
```

2023-10-04 17:15 UTC, alan-agius4 commented on packages/platform-browser/src/dom/shared_styles_host.ts
> +      styleRef.set(style, {elements: new Map([[host, styleEl]]), usage: 1});
There isn't any case, there this could be triggered, thus we should remove this line and save some bytes and remove the above if block.

2023-10-04 17:15 UTC, alan-agius4 commented on packages/platform-browser/src/dom/shared_styles_host.ts
> +    elements: Map</** Host */ Node, /** Style Node */ HTMLStyleElement>;
On host removals this map now needs to be cleaned.

```ts
  removeHost(hostNode: Node): void {
    this.hostNodes.delete(hostNode);
    for (const {elements} of this.styleRef.values()) {
      elements.delete(hostNode);
    }
  }

```

2023-10-04 17:22 UTC, mattlewis92 commented on packages/platform-browser/src/dom/shared_styles_host.ts
> +    const styleResult = styleRef.get(style);
Fixed in [`1f6fc87` (#52019)](https://github.com/angular/angular/pull/52019/commits/1f6fc876619c9fd7a27f8f9afbe39c8b84f80bd7) (I added a note about where it was defined for clarity)

2023-10-04 17:23 UTC, mattlewis92 commented on packages/platform-browser/src/dom/shared_styles_host.ts
> +      styleRef.set(style, {elements: new Map([[host, styleEl]]), usage: 1});
Nice spot, fixed in [`1f6fc87` (#52019)](https://github.com/angular/angular/pull/52019/commits/1f6fc876619c9fd7a27f8f9afbe39c8b84f80bd7)

2023-10-04 17:23 UTC, mattlewis92 commented on packages/platform-browser/src/dom/shared_styles_host.ts
> +    elements: Map</** Host */ Node, /** Style Node */ HTMLStyleElement>;
Fixed in [`1f6fc87` (#52019)](https://github.com/angular/angular/pull/52019/commits/1f6fc876619c9fd7a27f8f9afbe39c8b84f80bd7)

2023-10-04 17:28 UTC, alan-agius4 approved these changes
LGTM, thanks for you contribution and addressing the feedback so swiftly.

2023-10-04 17:32 UTC, crisbeto approved these changes

2023-10-04 17:35 UTC, alan-agius4 commented
[Presubmit](http://test/OCL:570735019:BASE:570735168:1696440632410:ea769d56)

2023-10-05 21:06 UTC, atscott commented
This PR was merged into the repository by commit 65786b2b96ba198034ff23bb14571a659a491b50.

2023-10-05 21:07 UTC, closed without merging