docs: update typescript configuration
angular/angular pull request #52046
Opened 2023-10-05 11:52 UTC by uneknown

This commits update the TypeScript configuration for the updated version 16 release.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-10-11 14:26 UTC, jessicajaniuk requested changes
We only really need the one line change here. FWIW, there's also quite a few more tsconfig files throughout aio.

2023-10-11 14:26 UTC, jessicajaniuk commented on aio/content/examples/getting-started/tsconfig.0.json
> +    "outDir": "./dist/out-tsc",
You can omit this line as it's unnecessary for us since we don't use tsc directly.

2023-10-11 14:26 UTC, jessicajaniuk commented on aio/content/examples/getting-started/tsconfig.0.json
> +/* To learn more about this file see: https://angular.io/config/tsconfig. */
This should be kept as the original link as it's a link to the user guide, not the tsconfig directly.

2024-01-26 20:14 UTC, JeanMeche commented
Without any feedback, I'll consider this PR as stale. Feel free to ping if you'd like to reopen it.

2024-01-26 20:14 UTC, closed without merging