Update zone.md
angular/angular pull request #52409
Opened 2023-10-26 23:07 UTC by tommygaessler

Updated the "Setting up Zone.js" instructions to the latest convention from how the Angular CLI configures it.

https://angular.io/guide/zone#setting-up-zonejs

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The current [Setting up Zone.js documentation](https://angular.io/guide/zone#setting-up-zonejs) is outdated and shows the previous way of how `zone.js` is setup when using the Angular CLI.

The docs say you must import `zone-flags` before you import `zone.js` in the `polyfills.ts`, but there is no longer a `polyfills.ts` file.

Current: 

`angular.json`:
```json
"polyfills": "src/polyfills.ts"
```

`src/polyfills.ts`:
```ts
import './zone-flags';
import 'zone.js/dist/zone';
```

Issue Number: N/A

## What is the new behavior?

The new behavior in the latest Angular CLI (when creating a new angular app via `$ ng new appname`), does not generate a `src/polyfills.ts` file, nor does the `polyfills` value point to that file in `angular.json`. Instead, it includes a reference to `zone.js` directly in the `angular.json` file, in a `polyfills` array.

To set or change settings from `zone.js`, you must add your `zone-flags.ts` in the `polyfills` array, before `zone.js`.

New: 

`angular.json`:
```json
"polyfills": [
    "src/zone-flags.ts",
    "zone.js"
  ]
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-01-26 20:18 UTC, JeanMeche commented
@JiaLiPassion Do you mind doing a quick review ? Thx !

2024-01-27 04:27 UTC, JiaLiPassion commented
@tommygaessler 
it seemd we also need to add `zone-flag.ts` to `tsconfig.app.json` files section, otherwise it will not be compiled.

2024-01-29 23:26 UTC, tommygaessler commented
Thanks for catching that @JiaLiPassion . I took a look at my `tsconfig.app.json` file, but I have it in the `include` array.

I updated my comment to include the `tsconfig.app.json` step.

2024-01-30 02:04 UTC, JiaLiPassion commented
@tommygaessler , thank you, I didn't see your new commit, could you check it?

2024-01-30 20:08 UTC, tommygaessler commented
@JiaLiPassion , commit added.

2024-01-30 22:22 UTC, JiaLiPassion approved these changes
LGTM! Thanks.

2024-02-02 01:18 UTC, JiaLiPassion requested changes
@tommygaessler , CI lint is failing, please update the commit message, and also squash all the commits into one. thanks.

2024-02-02 21:41 UTC, tommygaessler commented
@JiaLiPassion just squashed and updated the commit message.

2024-02-03 00:47 UTC, JiaLiPassion approved these changes
Thanks.

2024-02-28 16:35 UTC, pkozlowski-opensource commented
This PR was merged into the repository by commit 06ffe9a021a1f454392a6bcb0c18e36051bb2629.

2024-02-28 16:35 UTC, closed without merging