docs: remove duplicate words
angular/angular pull request #52415
Opened 2023-10-27 11:17 UTC by aanchal88

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-12-20 11:47 UTC, aanchal88 commented
Hi @jessicajaniuk, please merge the PR.

2023-12-20 14:59 UTC, jessicajaniuk requested changes
Thanks for helping improve the docs. Please address the feedback and I can re-review.

2023-12-20 14:59 UTC, jessicajaniuk commented on packages/animations/PACKAGE.md
> +@see What polyfills you might need in the [browser support guide](guide/browser-support).
This is not a duplicate word removal. Please revert this file.

2023-12-21 09:57 UTC, aanchal88 commented
Hi @jessicajaniuk , I have re-opened another PR for the same. Please refer https://github.com/angular/angular/pull/53673.
Thanks

2023-12-21 09:57 UTC, closed without merging