fix(docs-infra) code example in 'usage notes' tab is shrunk
angular/angular pull request #52821
Opened 2023-11-11 16:33 UTC by dnlrbz

Fixes CSS bug that docs detail tabs are shrunk and not have full available width

Fixes #52818

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Docs tabs are shrunk and not whole content is visible

Issue Number: 52818

## What is the new behavior?
Docs tabs take full width (except API tab), and whole content is visible

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

## Other information

2023-11-11 20:56 UTC, tieppt commented on adev/src/app/features/references/api-reference-details-page/api-reference-details-page.component.scss
> +        width: 100%;
If you apply this rule, the other pages that have the right sticky sidebar might not work as expected.

This is the current UI. 
<img width="1404" alt="image" src="https://github.com/angular/angular/assets/7151365/a657ee75-6888-4a43-87e6-741eb5d59f85">

This is after this change. The `width: 60%` rule will be overridden
<img width="1417" alt="image" src="https://github.com/angular/angular/assets/7151365/1b296178-3cca-4f4e-bb89-b11f19518946">


I think we can add one more rule to check if there is no sidebar like this.


```scss
&:not(:has(+ .adev-reference-members-container)) { /* .adev-header-and-tabs:not(:has(+ .adev-reference-members-container)) */
    width: 100%;
    max-width: 100ch; /* expand to fit the container */
}
```

2023-11-12 03:35 UTC, JeanMeche commented
Since the infra isn't ready yet for ADEV, I'm marking this PR as blocked until we can have a live demo of the fix !

2023-11-18 10:25 UTC, dnlrbz commented on adev/src/app/features/references/api-reference-details-page/api-reference-details-page.component.scss
> +        width: 100%;
thanks, fixed and checked it.

2023-11-18 10:41 UTC, JeanMeche approved these changes
The change LGTM but as said, we'll wait to be able to deploy ADEV to test it before we'll merge your change !

2024-01-25 22:21 UTC, jessicajaniuk requested changes
We now have a preview and I was able to verify that the fix mostly works, but there's an issue that'll need to be addressed. The first load of the page has the tab contents invisible. You can switch tabs at that point, and the content appears, but initially it's hiding the content. https://ng-dev-previews-fw--pr-angular-angular-52821-adev-prev-86vygrel.web.app/api/router/UrlTree?tab=usage-notes

2024-01-31 15:59 UTC, jessicajaniuk commented
I'm going to close this since we've heard no updates, but feel free to open a new PR with this change and the associated fix for visibility if you'd like to see this change landed. Thanks for your contribution!

2024-01-31 15:59 UTC, closed without merging