docs: updates the documentation for the ToH tutorial more comprehensi…
angular/angular pull request #53117
Opened 2023-11-22 15:28 UTC by aparzi

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

Issue Number: #52961

## What is the new behavior?
 Update documentation

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2023-11-24 16:55 UTC, aparzi commented
Hi @AndrewKushnir any news for this PR?

2023-11-27 23:24 UTC, AndrewKushnir commented
@MarkTechson just wanted to see if you have some thoughts on how to communicate the fact that `ng new` generates standalone version since v17 and the ToH guides rely on NgModule-based structure.

2023-11-27 23:24 UTC, AndrewKushnir commented
> Hi @AndrewKushnir any news for this PR?

@aparzi thanks for creating this PR. I've added Mark as a reviewer to see if we need to communicate this more in Tour of Heroes tutorial. Thank you.

2023-11-28 08:12 UTC, aparzi commented
> > Hi @AndrewKushnir any news for this PR?
> 
> @aparzi thanks for creating this PR. I've added Mark as a reviewer to see if we need to communicate this more in Tour of Heroes tutorial. Thank you.

@AndrewKushnir ok thanks. Available for any modification or update.

2023-11-28 15:42 UTC, MarkTechson requested changes
Thanks for this feedback, left a suggestion. If you can add this then I think we'll be good to go.

2023-11-28 16:03 UTC, aparzi commented on aio/content/tutorial/tour-of-heroes/toh-pt0.md
> +<b>Please note:</b> From version 17 of Angular a standalone project will be created by default. To create a project with the old scaffolding you need to use the option `ng new --no-standalone`
Hi @MarkTechson, thanks for your review. I applied the requested changes

2023-11-28 16:52 UTC, MarkTechson approved these changes
LGTM, thanks so much for this contribution!

2023-11-28 17:06 UTC, aparzi commented
> LGTM, thanks so much for this contribution!

it's a pleasure

2023-11-28 18:18 UTC, AndrewKushnir approved these changes

2023-11-28 18:43 UTC, pkozlowski-opensource commented
This PR was merged into the repository by commit e3dbadd9a496c076f32da965d709d17314ad7dd7.

2023-11-28 18:43 UTC, closed without merging

2023-11-29 06:24 UTC, Tweniee commented
I can quickly create a new pull request (PR) that incorporates the current changes and the requested changes. This would streamline the process and minimize any delays. Would you like me to proceed with creating the new PR?

2023-11-29 06:57 UTC, aparzi commented
> I can quickly create a new pull request (PR) that incorporates the current changes and the requested changes. This would streamline the process and minimize any delays. Would you like me to proceed with creating the new PR?

I have already done so and the PR with my changes and modification requests has already been accepted