docs: add link for control flow migration
angular/angular pull request #53375
Opened 2023-12-05 22:52 UTC by santoshyadavdev

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #53147

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-12-05 22:55 UTC, JeanMeche commented on adev/src/content/reference/migrations/control-fow.md
> +[Control flow syntax](../../guide/templates/control-flow) is available from Angular 17 and simplified way to use the control-flow directives like *ngFor, *ngIf and *ngSwitch.
I believe the link should be relative to the root. 
```suggestion
[Control flow syntax](guide/templates/control-flow) is available from Angular 17 and simplified way to use the control-flow directives like *ngFor, *ngIf and *ngSwitch. 
```

2023-12-06 16:05 UTC, jessicajaniuk commented on adev/src/content/reference/migrations/control-fow.md
> +[Control flow syntax](../../guide/templates/control-flow) is available from Angular 17 and simplified way to use the control-flow directives like *ngFor, *ngIf and *ngSwitch.
Agree. if you can apply these suggestions, I'll approve.

2023-12-06 17:09 UTC, jessicajaniuk commented on adev/src/content/reference/migrations/control-fow.md
> +[Control flow syntax](../../guide/templates/control-flow) is available from Angular 17 and simplified way to use the control-flow directives like *ngFor, *ngIf and *ngSwitch.
Yes, please squash the commits.

2023-12-06 17:25 UTC, santoshyadavdev commented on adev/src/content/reference/migrations/control-fow.md
> +[Control flow syntax](../../guide/templates/control-flow) is available from Angular 17 and simplified way to use the control-flow directives like *ngFor, *ngIf and *ngSwitch.
Done

2023-12-06 17:40 UTC, jessicajaniuk approved these changes
LGTM! Thank you!

2024-01-25 21:29 UTC, jessicajaniuk commented
@santoshyadavdev  Looks like the link is actually incorrect in the preview. Can you fix?

2024-01-25 21:30 UTC, jessicajaniuk requested changes
The preview shows the link to the control flow landing page to be broken. This needs to be fixed before we can merge.

2024-01-25 21:31 UTC, santoshyadavdev commented
@jessicajaniuk sure I will get it fixed in morning

2024-01-26 22:25 UTC, santoshyadavdev commented
> @jessicajaniuk sure I will get it fixed in morning

sorry @jessicajaniuk I ended up screwing up this branch, and ported changes to this PR https://github.com/angular/angular/pull/54108

2024-01-29 15:21 UTC, jessicajaniuk approved these changes
Thanks for taking care of this! Looks like the link works now.

2024-01-29 15:39 UTC, closed without merging

2024-01-29 15:39 UTC, jessicajaniuk commented
This PR was merged into the repository by commit d9a84705c969a8fdc6dfa37a85fc20e903cdbc04.