Misc fixes for template pipeline to align its behavior with TemplateDefinitionBuilder
angular/angular pull request #53596
Opened 2023-12-16 00:48 UTC by mmalerba

See individual commits for details

2023-12-16 00:53 UTC, dylhunn approved these changes

2023-12-16 01:07 UTC, dylhunn requested changes
(edit -- nevermind)

2023-12-16 01:15 UTC, dylhunn approved these changes

2023-12-18 21:47 UTC, dylhunn commented
Caretaker -- no effect on g3

2023-12-18 21:48 UTC, dylhunn approved these changes

2023-12-18 22:09 UTC, jessicajaniuk commented
This PR was merged into the repository by commit d485cfef28ab4143a31cb42b7a4bb3f99cc2dd00.

2023-12-18 22:09 UTC, closed without merging