(docs) Fix links for NgZone
angular/angular pull request #53612
Opened 2023-12-17 19:41 UTC by Yozmo

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Link references for NgZone from https://angular.dev/best-practices/zone-pollution#run-tasks-outside-ngzone leads to Page Not Found

Issue Number: #53608

## What is the new behavior?
Fixing the link references for NgZone from https://angular.dev/best-practices/zone-pollution#run-tasks-outside-ngzone

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-12-18 15:07 UTC, jessicajaniuk requested changes
Thanks for the PR. Links here should be relative rather than absolute. You'll also need to fix your commit message to address the failing lint check. It should be `docs: Fix links for NgZone'.

2023-12-18 15:07 UTC, jessicajaniuk commented on adev/src/content/best-practices/runtime-performance/zone-pollution.md
> +In such cases, you can instruct Angular to avoid calling change detection for tasks scheduled by a given piece of code using [NgZone](https://angular.dev/api/core/NgZone).
```suggestion
In such cases, you can instruct Angular to avoid calling change detection for tasks scheduled by a given piece of code using [NgZone](/api/core/NgZone).
```

2023-12-18 15:07 UTC, jessicajaniuk commented on aio/content/guide/change-detection-zone-pollution.md
> +In such cases, you can instruct Angular to avoid calling change detection for tasks scheduled by a given piece of code using [NgZone](https://angular.dev/api/core/NgZone).
```suggestion
In such cases, you can instruct Angular to avoid calling change detection for tasks scheduled by a given piece of code using [NgZone](/api/core/NgZone).
```

2023-12-19 16:12 UTC, srinathsree66 commented
Can you please squash that additional commits  into single one?

2023-12-20 22:39 UTC, jessicajaniuk commented
It looks like you have a merge commit in your commits. You'll need to get rid of that commit.

2023-12-23 23:03 UTC, louaymeskini commented
> It looks like you have a merge commit in your commits. You'll need to get rid of that commit.

hi @jessicajaniuk, here is an updated PR for mentionned issue: please review it and thanks.

https://github.com/angular/angular/pull/53667

2024-01-15 23:17 UTC, JeanMeche commented
I'll close this in favor of #53667

2024-01-15 23:17 UTC, closed without merging