docs:  remove outdated info about ng serve
angular/angular pull request #53890
Opened 2024-01-11 20:58 UTC by mooyil

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-01-11 22:51 UTC, alxhub requested changes
Thanks for the PR!

I think we can simplify the language even further - we don't need to talk about the historical context, and can describe the current behavior directly.

2024-01-25 21:04 UTC, jessicajaniuk approved these changes
LGTM

2024-02-01 20:51 UTC, sonukapoor approved these changes

2024-02-01 22:38 UTC, alxhub approved these changes

2024-02-01 23:00 UTC, closed without merging

2024-02-01 23:00 UTC, jessicajaniuk commented
This PR was merged into the repository by commit bdf6927125d17a09c49e42f523781547aa5a8b2d.