docs: remove ngx-deploy-npm from deployers table
angular/angular pull request #53999
Opened 2024-01-19 23:28 UTC by dianjuar

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

In the [deployment documentation](https://angular.io/guide/deployment#automatic-deployment-with-the-cli), there is a listed tool that no longer offers support for Angular.

## What is the new behavior?

Remove the deployer `ngx-deploy-npm` from the documentation since it will no longer work for Angular workspaces.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

More information can be found on ngx-deploy-npm [blog post about version 8](https://dev.to/dianjuar/whats-coming-to-ngx-deploy-npm-v8-23gn), where the maintainers announced the removal of Angular workspace support.

2024-01-23 23:00 UTC, dgp1130 approved these changes

2024-01-23 23:02 UTC, dgp1130 requested changes
Oh I think we would also want to update angular.dev which has a similar table here:

https://github.com/angular/angular/blob/a3787bdfa61ef98c9e109d62c49e7bf873c03807/adev/src/content/tools/cli/deployment.md?plain=1#L37

2024-01-24 15:50 UTC, dianjuar commented
@dgp1130 Changes applied

2024-01-24 22:28 UTC, dgp1130 approved these changes

2024-01-25 06:40 UTC, alan-agius4 approved these changes

2024-01-25 06:41 UTC, alan-agius4 commented
Caretaker note: current approvals should suffice

2024-01-25 16:07 UTC, closed without merging