fix(router): preserve replaceUrl when returning a urlTree from CanAct…
angular/angular pull request #54042
Opened 2024-01-23 22:38 UTC by blathers16

…ivate

This commit will fix the issue of the setting of NavigationExtras.replaceUrl being lost when returning a urlTree from a CanActivateFn.

Fixes #53503

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
     I didn't see anything in the docs that mentions the bug.

## PR Type
What kind of change does this PR introduce?

- [ X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

https://github.com/angular/angular/issues/53503
Issue Number: 53503

## What is the new behavior?
NavigationExtras.replaceUrl is preserved.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2024-01-23 23:08 UTC, atscott commented on packages/router/src/router.ts
> +              replaceUrl: currentTransition.extras.replaceUrl ??
This change isn't quite correct. If `replaceUrl` is specifically `false`, it should still use the other logic, which is meant to capture when the URL has already changed during the current navigation.

2024-02-03 20:34 UTC, blathers16 commented
Hi @atscott I have updated the pull request as well as added extra tests to confirm that your above suggestion is working.

2024-02-03 22:41 UTC, JeanMeche commented
@blathers16 It looks like something went wrong during rebase. Your PR includes 167 commits, can you have a look ? thank you.

2024-02-03 23:00 UTC, blathers16 commented
hi @JeanMeche that is probably because I didn't try to rebase.  What is the goal here? To end up with a single commit for the entire PR?

2024-02-03 23:02 UTC, JeanMeche commented
Yes, the PR should include only the changes intended for the fix. Currently having 1,017 file changes makes it hard to review.

2024-02-03 23:51 UTC, blathers16 commented
Hi, @JeanMeche, I think I fixed it.  I have no idea where the 1,017 files came from, all I did was merge in upstream/main.  Anyways, it should be all in one commit with no unrelated changes now.

2024-02-06 20:28 UTC, atscott requested changes

2024-02-06 20:28 UTC, atscott commented on packages/router/src/router.ts
> +              replaceUrl: currentTransition.extras.replaceUrl ? true :
```suggestion
              replaceUrl: currentTransition.extras.replaceUrl ||
```

2024-02-06 20:28 UTC, atscott commented on packages/router/test/computed_state_restoration.spec.ts
> +import {NavigationExtras, Router, RouterModule, RouterOutlet, UrlTree, withRouterConfig} from '@angular/router';
Could you please revert these changes and just right a few tests targeting this change directly? The updates in this file make it _really_ difficult to understand and review.

2024-02-07 01:05 UTC, blathers16 commented on packages/router/test/computed_state_restoration.spec.ts
> +import {NavigationExtras, Router, RouterModule, RouterOutlet, UrlTree, withRouterConfig} from '@angular/router';
Hi, @atscott, most of those changes were mismatched indentation, (they had stuff indented half a 2-space indent), I fixed that to match the original, can you please take a look and see if it is readable now or if you still need me to simplify it.

2024-02-07 16:51 UTC, atscott commented on packages/router/test/computed_state_restoration.spec.ts
> +import {NavigationExtras, Router, RouterModule, RouterOutlet, UrlTree, withRouterConfig} from '@angular/router';
Honestly, I don't think that helps. The tests in this file have a very specific purpose that's _similar_ to the change in this PR but make it unclear what's being tested when reused for a slightly different purpose. I would very much prefer a completely separate set of tests.

2024-02-14 22:00 UTC, blathers16 commented on packages/router/test/computed_state_restoration.spec.ts
> +import {NavigationExtras, Router, RouterModule, RouterOutlet, UrlTree, withRouterConfig} from '@angular/router';
@atscott are you saying you would prefer them to be in a separate file?

2024-02-16 00:49 UTC, atscott commented on packages/router/test/computed_state_restoration.spec.ts
> +import {NavigationExtras, Router, RouterModule, RouterOutlet, UrlTree, withRouterConfig} from '@angular/router';
Yes, this set of tests was meant to verify `canceledNavigationResolution: 'computed'` by building up several items in the navigation history. It's much more than needed for this change. A new spec file would be easier to review. `regression_integration.spec.ts` could also be a good place. It has a set of tests built around bug fixes and is much shorter than the general dumping ground that is `integration.spec.ts`.

2024-02-21 21:02 UTC, blathers16 commented on packages/router/src/router.ts
> +              replaceUrl: currentTransition.extras.replaceUrl ? true :
This suggested fix is incorrect logic, it will fail to evaluate the second condition when replaceUrl is false due to short-circuiting.

2024-02-21 21:03 UTC, blathers16 commented on packages/router/test/computed_state_restoration.spec.ts
> +import {NavigationExtras, Router, RouterModule, RouterOutlet, UrlTree, withRouterConfig} from '@angular/router';
Hi, @atscott I have moved a set of more focused tests into a separate file.  Please review.

2024-02-23 22:32 UTC, atscott requested changes
There's quite a lot of unused code here and tests that could be simplified by using newer features: standalone, functional guards, `RouterTestingHarness`, etc. Older tests in the router code unfortunately aren't good examples of how new ones should be written.

2024-02-24 19:19 UTC, blathers16 commented
Hi, @atscott, I made most of the requested changes except using RouterTestingHarness.  It doesn't seem to have a way to pass NavigationExtras, so I don't think it can be used in this case.  Feel free to correct me if I am wrong.

2024-03-26 19:34 UTC, atscott approved these changes

2024-03-27 15:16 UTC, atscott commented
[green TGP](https://fusion2.corp.google.com/presubmit/619277389/OCL:619277389:BASE:619239464:1711527242436:32425d61/targets)

2024-03-27 17:56 UTC, dylhunn commented
caretaker: this change has a green TGP above

2024-03-27 17:57 UTC, dylhunn commented
This PR was merged into the repository by commit 60f1d681e0ba66d3d94b0819f2c612f095c2d3d3.

2024-03-27 17:57 UTC, closed without merging