After render notifies scheduler (afterRender hooks are guaranteed to run)
angular/angular pull request #54083
Opened 2024-01-26 00:29 UTC by atscott

Blocked by https://github.com/angular/angular/pull/54074

2024-03-05 13:48 UTC, pkozlowski-opensource requested changes
As far as I can tell the logic around scheduling CD upon installation of a render hook needs tests.

2024-03-05 13:48 UTC, pkozlowski-opensource commented on packages/core/src/render3/node_manipulation.ts
> +  lView[ENVIRONMENT].changeDetectionScheduler?.notify(NotificationType.AfterRenderHooks);
nit: currently the `NotificationType` indicates what _should_ happen in the scheduler. An alternative would be send a notification indicating what happened (ex.: view added, after render hook created etc.) and leave it to the scheduler to figure out appropriate actions.

While I would structure code this way I do recognize that it might be a personal preference so feel free to ignore.

2024-03-05 14:44 UTC, atscott commented on packages/core/src/render3/node_manipulation.ts
> +  lView[ENVIRONMENT].changeDetectionScheduler?.notify(NotificationType.AfterRenderHooks);
I thought about this as well but decided against it because it’s one additional type of thing that isn’t really used in any way. That is, we’d notify with a bunch of different sources and then map all those sources back to just two actions again. Until we have a use case for interpreting the sources in different ways (even just for logging), I feel this approach is much simpler.

2024-03-06 20:30 UTC, atscott commented
> As far as I can tell the logic around scheduling CD upon installation of a render hook needs tests.

Added a couple tests. Good catch.

2024-03-07 15:20 UTC, pkozlowski-opensource approved these changes

2024-03-07 15:20 UTC, pkozlowski-opensource commented on packages/core/test/change_detection_scheduler_spec.ts
> +      // reattaching non-dirty view does not notifies scheduler because afterRender hooks must run
"does not notifies" => "notifies"

2024-03-07 20:59 UTC, atscott commented
This PR was merged into the repository by commit 2787c501074daf3bf5f0e014e18e02ad2a61fcf1.

2024-03-07 20:59 UTC, closed without merging