docs: fix link missing to lazy loading module
angular/angular pull request #54113
Opened 2024-01-27 11:23 UTC by Narendherraj

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #53903 

## What is the new behavior?
Issue of the missing link to the lazy loading module is fixed with this change .
## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2024-01-29 16:17 UTC, jessicajaniuk requested changes
Once you update the link to something appropriate for adev, I can re-review this.

2024-01-29 16:17 UTC, jessicajaniuk commented on adev/src/content/guide/routing/common-router-tasks.md
> +For more information on lazy loading and preloading see the dedicated guide [Lazy loading](guide/lazy-loading-ngmodules).
The lazy loading ngmodules link here does not exist on angular.dev. I think that's only on angular.io. So this will need a different link.

2024-01-31 04:19 UTC, Narendherraj commented
@jessicajaniuk Have updated the correct link now

2024-01-31 15:03 UTC, jessicajaniuk commented
@Narendherraj The link looks correct now. Can you squash your commits so there's only one commit? Other than that, this is ready to go.

2024-01-31 15:03 UTC, jessicajaniuk approved these changes
LGTM! Once you squash your commits, we'll merge it. Thank you!

2024-01-31 15:06 UTC, jessicajaniuk commented
@Narendherraj Looks like we'll also need to have you sign the CLA. Looks like you have 2 emails on your account, and it needs to be signed for both.

2024-01-31 16:41 UTC, jessicajaniuk approved these changes
Thanks for the cleanup! LGTM!

2024-01-31 16:42 UTC, Narendherraj commented
@jessicajaniuk Squashed the commits and took care of the CLA thing .

2024-01-31 16:45 UTC, closed without merging

2024-01-31 16:45 UTC, jessicajaniuk commented
This PR was merged into the repository by commit 318a181d8ee1961eb6f936fd73200c534460f21a.