(docs): add sample usage of the FormArray API for reactive forms
angular/angular pull request #54138
Opened 2024-01-28 23:12 UTC by maequise

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Missing a more concrete sample on how to use the FormArray API

Issue Number: #53705

## What is the new behavior?
Include a more concrete sample of how to use the FormArray API on the site into the guide of reactive forms

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-01-29 15:25 UTC, jessicajaniuk commented
@maequise Looks like your commit message is causing the lint to fail. It's very close though. Run `git commit --amend` and change your commit message to `docs: add sample usage of the FormArray API for reactive forms`, and then force push. That'll fix it.

2024-01-29 15:26 UTC, jessicajaniuk commented
@dylhunn Can you review the content here?

2024-01-30 13:38 UTC, sonukapoor commented on adev/src/content/guide/forms/reactive-forms.md
> +  //component declaration
Do we need this comment?

2024-01-30 13:44 UTC, maequise commented on adev/src/content/guide/forms/reactive-forms.md
> +  //component declaration
This comment is not revelant, I certainly forgot to remove it. If need I can remove it and make a new push.

2024-01-30 14:14 UTC, sonukapoor commented on adev/src/content/guide/forms/reactive-forms.md
> +  //component declaration
Yes, remove anything that is not relevant.

2024-01-30 14:18 UTC, sonukapoor commented on adev/src/content/guide/forms/reactive-forms.md
> +In a more concrete sample, we can imagine the following use case. You are application needs a basic form, with known information, but the user has the ability to add more or less sub-form.
```suggestion
In a more concrete sample, we can imagine the following use case. Your application needs a basic form, with known information, but the user has the ability to add more or less sub-form.
```

2024-01-30 14:18 UTC, sonukapoor commented on adev/src/content/guide/forms/reactive-forms.md
> +Tip: If you watch the HTML template, you will notice that the access to the `FormArray` is not from the `FormGroup` directly with the **get()** method. We will define a getter method.
```suggestion
Tip: If you watch the HTML template, you will notice that the access to the `FormArray` is not from the `FormGroup` but directly using the **get()** method. We will define a getter method.
```

2024-01-30 14:18 UTC, sonukapoor commented on adev/src/content/guide/forms/reactive-forms.md
> +With this method, when the user click on the button, it is adding a new `FormGroup` in the `FormArray`. When adding a new entry, the template will be updated.
```suggestion
With this method, when the user clicks on the button, it is adding a new `FormGroup` in the `FormArray`. When adding a new entry, the template will be updated.
```

2024-01-30 14:18 UTC, sonukapoor commented on adev/src/content/guide/forms/reactive-forms.md
> +We can add entries to the `FormArray` but we should be able to remove a specific entry. The `FormArray` has the **removeAt()** method that permits to delete a specific index of the `FormArray`.
```suggestion
We can now add entries to the `FormArray` but we should also be able to remove a specific entry. The `FormArray` has the **removeAt()** method that permits to delete a specific index of the `FormArray`. 
```

2024-01-30 16:57 UTC, maequise commented
@sonukapoor  thank you for the review, I made the corrections (the last forced "push"  was because I missed one edit)

2024-01-30 22:39 UTC, MarkTechson commented
I really appreciate this work but this should really be a tutorial or code example, not necessarily an additional guide. I would also add here that we should consider revamping this guide and converting it to an issue that we should track and keep track of this work.

@twerske can you chime in on this?

2024-01-30 23:01 UTC, maequise commented
> I really appreciate this work but this should really be a tutorial or code example, not necessarily an additional guide. I would also add here that we should consider revamping this guide and converting it to an issue that we should track and keep track of this work.
> 
> @twerske can you chime in on this?

I was thinking earlier in the afternoon adding a tutorial on the suject.

2024-02-01 19:34 UTC, twerske commented
> I really appreciate this work but this should really be a tutorial or code example, not necessarily an additional guide. I would also add here that we should consider revamping this guide and converting it to an issue that we should track and keep track of this work.
> 
> @twerske can you chime in on this?

I agree. This should be a tutorial not a guide since it's a walk through of a code example.

2024-02-04 09:36 UTC, maequise commented
As suggested, I made a tutorial for this part and removed the guide part.

2024-03-15 15:55 UTC, BojanKogoj requested changes

2024-12-14 08:50 UTC, closed without merging