docs: add guide for signal inputs
angular/angular pull request #54316
Opened 2024-02-07 15:17 UTC by devversion

Adds a guide for signal inputs.

We will port that to `angular.dev` once we finalized this version.

2024-02-07 15:31 UTC, eneajaho commented on aio/content/guide/signal-inputs.md
> +An input signal in practice is a trivial extension of signals that were mentioned in [the signals library guide](/guide/signals).
```suggestion
A signal input in practice is a trivial extension of signals that were mentioned in [the signals library guide](/guide/signals).
```

They are called signal inputs instead of input signal over the other parts of the doc

2024-02-07 15:32 UTC, eneajaho commented on aio/content/guide/signal-inputs.md
> +Previously, with `@Input` it was rather difficult to monitor whenever an is input changing.
```suggestion
Previously, with `@Input` it was rather difficult to monitor whenever an input is changing.
```

2024-02-07 15:33 UTC, eneajaho commented on aio/content/guide/signal-inputs.md
> +For example, issuing HTTP requests whenever the first name, or last name inputs change.
```suggestion
For example, issuing HTTP requests whenever the first name input changes.
```

There's no `lastName` input in the example below ?

2024-02-07 15:35 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +An input signal in practice is a trivial extension of signals that were mentioned in [the signals library guide](/guide/signals).
This was an intentional difference to refer to `InputSignal`, but I see what you're saying. Leaving open for others to weigh in.

2024-02-07 15:36 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +For example, issuing HTTP requests whenever the first name, or last name inputs change.
I was imaging it to be based on the previous sections, but it's likely non-ideal to have that dependency.

2024-02-07 15:36 UTC, eneajaho commented on aio/content/guide/signal-inputs.md
> +      this.fetchUserFromDatabase(this.firstName());
Should we include the `onCleanup` function here, to cleanup some subscription maybe, or cancel a promise? Devs will look at this code, and see it as best practice (because it's the docs)

2024-02-07 15:37 UTC, eneajaho commented on aio/content/guide/signal-inputs.md
> +Do not use transforms if they change the meaning of the input, or if they are [impure](https://en.wikipedia.org/wiki/Pure_function).
```suggestion
Do not use transforms if they change the meaning of the input, or if they are [impure](https://en.wikipedia.org/wiki/Pure_function#Impure_functions).
```

2024-02-07 18:59 UTC, pkozlowski-opensource reviewed
I've left some "thinking out loud" comments.

2024-02-07 18:59 UTC, pkozlowski-opensource commented on aio/content/guide/signal-inputs.md
> +Conceptually, signal inputs are similar to the inputs you already know with `@Input`.
It is probably obvious but we are not calling out that _values_ are actually expoed as signal. I think it would be helpful to call it out explicitly - otherwise people might get an impression that it more about the authoring that the essence of values as a reactive primitive.

2024-02-07 18:59 UTC, pkozlowski-opensource commented on aio/content/guide/signal-inputs.md
> +      this.fetchUserFromDatabase(this.firstName());
Alternatively we should make this example simpler by using say `console.log` - otherwise I agree with @eneajaho that we should make this example more "real life". My vote would go to changing this example to something that doesn't involve http

2024-02-07 18:59 UTC, pkozlowski-opensource commented on aio/content/guide/signal-inputs.md
> +## Aliasing an input
I would move those sections earlier on as those are more relevant to inputs - the previous discussion in computed / effect is not crucial here (the same logic applies to all signals) and might "distract" from the input essentials.

2024-02-07 18:59 UTC, pkozlowski-opensource commented on aio/content/guide/signal-inputs.md
> +Instead, consider using a `computed` for transformations with different meaning, or an `effect` for impure code that should run whenever the input changes.
👍

2024-02-07 18:59 UTC, pkozlowski-opensource commented on aio/content/guide/signal-inputs.md
> +In some cases though, value transforms are a good fit for input.
How about inverting things here and showing a "positive" example first, with "avoid" bits after?

2024-02-07 21:20 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +In some cases though, value transforms are a good fit for input.
Fair suggestion. Not sure. I started with avoid bits beforehand to not encourage transforms too early, but I see that a simpler positive example might actually help. Will check tomorrow

2024-02-08 08:20 UTC, simonaco commented on aio/content/guide/signal-inputs.md
> +Conceptually, signal inputs are similar to the inputs you already know with `@Input`.
thinking about the audience for this guide, could be Angular devs but also non-Angular devs learning Angular directly with Signals. I think in the overview we should provide a short description that can be understood standalone, without having to go read the guide about `@Input`.

2024-02-08 08:57 UTC, simonaco commented on aio/content/guide/signal-inputs.md
> +In some cases though, value transforms are a good fit for input.
+1 to showing an example of `how/why to use` first and after that share best practices/what to avoid.

2024-02-08 09:12 UTC, simonaco commented on aio/content/guide/signal-inputs.md
> +Signal inputs are non-writable signals.
```suggestion
Signal inputs are read-only signals.
```

2024-02-08 09:24 UTC, simonaco commented on aio/content/guide/signal-inputs.md
> +  disabled = computed(() => this.disabled() === '' || !!this.disabled());
I am confused by the naming here, based on the alias example my understanding is that `this.disabled()` should be `this.disabledRaw()` here.

2024-02-08 10:58 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +  disabled = computed(() => this.disabled() === '' || !!this.disabled());
Good catch!

2024-02-08 11:54 UTC, simonaco commented on aio/content/guide/signal-inputs.md
> +Signal inputs are non-writable signals.
For readability purposes it's generally advised against negative forms like `non-writable` in documentation. In the signals guide, we say `Signals may be either writable or read-only.`

2024-02-08 12:16 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +Signal inputs are non-writable signals.
I don't feel strongly, so happy to change. Do you have any resources on this advise? Note that we were also using `non-writable` in the RFC. See https://github.com/angular/angular/discussions/49683 (and some blog posts also seem to use that). `readonly` works, but doesn't align nicely with the API surface + can be confused easily with the `readonly` modifier of class members.

2024-02-08 18:24 UTC, MarkTechson requested changes
Great PR. Developers are going to benefit from this. Left some tweaks, let me know if you have any questions.

2024-02-08 19:53 UTC, itea-dev commented on aio/content/guide/signal-inputs.md
> +Previously, with `@Input` it was rather difficult to monitor whenever an is input changing.
"to" and "is" are missing in the suggested change.

> When using decorator based inputs (`@Input`) it is difficult **to** monitor whenever an input's value **is** changing.

2024-02-12 16:11 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +      this.fetchUserFromDatabase(this.firstName());
Using `console.log` to not convolute this example here. Agreed not using http here.

2024-02-12 16:13 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +## Aliasing an input
Sounds good. Moving aliasing.

I did think we want to keep transforms last as `computed` expressions are most of the time the thing people are looking for I'd assume and transforms may be misunderstood then.

2024-02-12 16:24 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +In some cases though, value transforms are a good fit for input.
Improved! reworked a little more

2024-02-12 16:26 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +API might change without deprecation.
Done!

2024-02-12 16:28 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +The difference is that you no longer use a decorator to declare an input, but instead the input is automatically recognized by Angular whenever you use the `input` or `input.required` functions as in
Good suggestion. Actually dropping `@input` here completely. Thx

2024-02-12 16:46 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +Conceptually, signal inputs are similar to the inputs you already know with `@Input`.
Improving!

2024-02-12 16:47 UTC, devversion commented on aio/content/guide/inputs-outputs.md
> +Consider exploring [signal inputs](/guide/signal-inputs).
Great! thx

2024-02-12 16:47 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +* Optional inputs that _can_ have an initial value (see `age` above).
Improved!

2024-02-12 16:48 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +
Love it!

2024-02-12 16:48 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +Similar to normal signals, you can derive values from inputs using `computed`.
Great suggestion!

2024-02-12 16:50 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +Previously, with `@Input` it was rather difficult to monitor whenever an is input changing.
thx updated!

2024-02-12 16:54 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +For example, issuing HTTP requests whenever the first name, or last name inputs change.
Updated, but not using http here as per previous commits

2024-02-12 16:56 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +Inputs can be aliased in case the name of the input cannot match the class member name.
reworded

2024-02-12 17:14 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +With the example above, you will use `this._rawAge` inside your component or template.
I think this is fine, but I'm making the example a bit simpler.

2024-02-12 17:21 UTC, devversion commented
Feedback addressed. Please have another look.

2024-02-12 22:43 UTC, MarkTechson approved these changes
LGTM.

2024-02-14 14:35 UTC, simonaco commented on aio/content/guide/signal-inputs.md
> +Signal inputs are a reactive alternative to decorator-based `@Input()`.
This still feels like we're leading with the comparison with the existing `@Input`. We might want to jump directly into the text from the Overview section and move the alert about dev preview lower in that section.

2024-02-14 14:52 UTC, simonaco requested changes
Looks great, left a few minor changes

2024-02-14 14:52 UTC, simonaco commented on aio/content/guide/signal-inputs.md
> +Signal inputs are non-writable signals.
I think it would be useful to consistently use the same wording across our guides. we refer to computed as read-only as well.

2024-02-14 14:52 UTC, simonaco commented on aio/content/guide/signal-inputs.md
> +When using decorator-based inputs (`@Input`), it is difficult to monitor whenever an input's value is changing.
This section comparing with @Input might be a good one to include in the section `Why should we use signal inputs and not @[Input]` To keep focus on `input()` we could start directly with line 110.

2024-02-14 14:52 UTC, simonaco commented on aio/content/guide/signal-inputs.md
> +The `fetchUserFromDatabase` function is invoked every time the `firstName` input changes.
```suggestion
The `console.log` function is invoked every time the `firstName` input changes.
```

2024-02-14 15:05 UTC, JeanMeche reviewed
Minor typos

2024-02-14 15:05 UTC, JeanMeche commented on aio/content/guide/signal-inputs.md
> +This access to the the value is captured in reactive contexts and can notify active consumers, like Angular itself, whenever the input value changes.
```suggestion
This access to the value is captured in reactive contexts and can notify active consumers, like Angular itself, whenever the input value changes.
```

2024-02-14 15:05 UTC, JeanMeche commented on aio/content/guide/signal-inputs.md
> +An input signal in practice is a trivial extension of signals that you know from the [the signals guide](/guide/signals).
```suggestion
An input signal in practice is a trivial extension of signals that you know from [the signals guide](/guide/signals).
```

2024-02-14 15:25 UTC, pkozlowski-opensource approved these changes

2024-02-14 17:18 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +They are declared using the `input.required` function.
Interesting. This is clearly subjective, but it does feel like I'd prefer a good intro for the two possible variants.

2024-02-14 17:19 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +Signal inputs are non-writable signals.
Updated, but I personally wish we would clarify this more somewhere.

2024-02-14 17:19 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +  age = input(null, {alias: 'studentAge'});
Done!

2024-02-14 17:23 UTC, devversion commented on aio/content/guide/signal-inputs.md
> +Angular supports two variants of inputs:
(as discussed offline- will follow-up on this with you)

2024-02-14 17:23 UTC, devversion commented
Marking for merge as we got sufficient reviews, I've addressed 99% of feedback, and this would be a good starter content for 17.2. Will discuss/and address remaining feedback from @jelbourn in a follow-up.

2024-02-14 17:37 UTC, simonaco approved these changes
Thank you Paul

2024-02-14 23:22 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 12d4b8eb47cccac39e95c0d1e48f56212cba09aa.

2024-02-14 23:22 UTC, closed without merging