docs: refactor docs navigation to reduce in-depth guides length
angular/angular pull request #54365
Opened 2024-02-09 15:28 UTC by bencodezen

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/angular/angular/issues/54203

## What is the new behavior?

Introduces a revised information architecture that reduces the number of top level items when readers are looking at the content.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-02-09 16:46 UTC, surajchopra1234 commented
### Preview Bug:

When I click on **Performance** in the in-depth guide, the **Template Syntax** is opened

### Suggestion:

I think that the **NgModule** guide should not be shown in the in-depth guides because we promote standalone components. We also have a migration for this. Instead, the **HttpClient** guide should be in the in-depth guides because it can be more useful.

2024-02-09 23:34 UTC, bencodezen commented
> When I click on Performance in the in-depth guide, the Template Syntax is opened

Thanks for flagging this @surajchopra1234! 

> HttpClient guide should be in the in-depth guides because it can be more useful.

It's still in the in-depth guides. The difference is that it's been moved into dependency injection in order to provide a better grouping for concepts and where things live.

2024-02-13 00:21 UTC, mgechev commented
Looks like a good start! Adding also @jelbourn as a reviewer.

2024-02-13 00:21 UTC, mgechev approved these changes

2024-02-13 00:24 UTC, mgechev requested changes
- I couldn't find `NgModules` under reference
- I couldn't also find Custom Elements under components

For the latter, I'm not sure that's where we'd like to promote the content. It makes logical sense, but Custom Elements (Angular Elements) are way less likely to be used than Angular components. I'm fine moving it to reference.

2024-02-13 07:00 UTC, KhizerRehan commented
@bencodezen  Great changes :) I see clean docs in preview but based on changes done. I can't open following pages after navigation refactoring Getting console errors.

I am checking in this preview link: 

https://github.com/angular/angular/pull/54365#issuecomment-1936178316

console:
<img width="1250" alt="Screenshot 2024-02-13 at 11 50 30 AM" src="https://github.com/angular/angular/assets/17727069/3b4c7c93-f583-414a-8633-fe39da1a8a07">

- Neither i can open "Concepts/" navigation

Maybe something i am missing. Thank you!

2024-02-15 17:24 UTC, bencodezen commented
@KhizerRehan Thanks for the feedback! 

The links should work for the "Pipes" and "Best Practices Security" now. (Still debugging the Concepts one)

Let me know if you see anything else!

2024-03-12 16:25 UTC, mgechev approved these changes

2024-03-12 17:25 UTC, atscott commented
This PR was merged into the repository by commit 4ff94aa46c514342b80f70b925203e8159f2a95d.

2024-03-12 17:25 UTC, closed without merging