refactor(compiler-cli): use semver for version parsing
angular/angular pull request #54429
Opened 2024-02-14 08:30 UTC by crisbeto

Follow-up to #54423 which uses `semver` to parse the version instead of doing it ourselves.

2024-02-14 13:04 UTC, devversion approved these changes

2024-02-14 13:04 UTC, devversion commented on packages/compiler-cli/src/ngtsc/core/src/compiler.ts
> +        semver.satisfies(this.angularCoreVersion, `0.0.0-${'PLACEHOLDER'} || >= 17.2.0-0`);
😆

2024-02-14 20:14 UTC, alxhub approved these changes

2024-02-20 10:04 UTC, crisbeto commented
Caretaker note: these changes require a new patch in g3. You'll have to patch cl/608525899 into the sync CL.

2024-02-20 17:29 UTC, alxhub requested changes

2024-02-20 17:29 UTC, alxhub commented on packages/compiler-cli/src/ngtsc/core/src/feature_detection.ts
> +// more detection functions here, the caretaker may have to update a patch internally.
With a slightly different approach, we can make this patching process a lot less brittle.

Rather than export specific feature detection functions, let's export a single general-purpose one. Something like:

```typescript
export function coreVersionSupportsFeature(coreVersion: string, minFeatureVersion: string): boolean {...}
```

Then, we can inline the appropriate version into the consumer code (e.g. `17.2.0-0` for signal two-way bindings). In g3, we can replace the implementation of this function with `return true` since g3 runs at HEAD and by definition supports all features.

That way, we don't have to update the patch file every time we have a new feature which needs feature detection.

2024-02-21 09:48 UTC, crisbeto commented
@alxhub I've updated the feature detection and the patch in cl/608525899.

2024-02-21 10:05 UTC, devversion commented on packages/bazel/src/ng_package/ng_package.bzl
> +    "semver",
Nit: is this needed/expected?

2024-02-21 10:13 UTC, crisbeto commented on packages/bazel/src/ng_package/ng_package.bzl
> +    "semver",
Removed.

2024-02-23 16:39 UTC, alxhub approved these changes

2024-02-24 00:02 UTC, AndrewKushnir commented
@crisbeto I've added a "cleanup" label for now and sent a proposal on how we can make g3 patch less brittle. Please let me know what you think. Thank you.

2024-02-24 17:36 UTC, crisbeto commented
Based on the discussion over DM, I'll continue with the current approach which can be revisited if it's a problem.

2024-02-27 23:24 UTC, dylhunn commented
This PR was merged into the repository by commit df0e69b464928ad78bfdab38eed555ba9e0db458.

2024-02-27 23:24 UTC, closed without merging