docs: add a guide for model inputs
angular/angular pull request #54514
Opened 2024-02-20 10:40 UTC by crisbeto

Adds a guide for `model()` inputs for angular.io. Will port this over to angular.dev once it's finalized.

2024-02-20 11:22 UTC, Segdo commented on aio/content/guide/model-inputs.md
> +This exposes a `studentAge` input and a `studentChange` output on the `StudentDirective`.
```suggestion
This exposes a `studentAge` input and a `studentAgeChange` output on the `StudentDirective`.
```

2024-02-20 23:43 UTC, jelbourn reviewed
Here's a commit with my proposed changes
https://github.com/jelbourn/angular/commit/96b82924fb2cb4a20ff2cfaefb9332b7209024e1

Feel free to push back on anything here; I tried to reorient the guide to de-emphasize the automatic creation of the output and put more emphasis on the support for two way binding, as well as deferring to the `input` doc to cover aliasing and required vs. optional

2024-02-21 21:11 UTC, jelbourn approved these changes
LGTM

2024-02-21 23:15 UTC, MarkTechson requested changes
I left a few small feedback points. I think it's good to go otherwise.

2024-02-21 23:15 UTC, MarkTechson commented on aio/content/guide/model-inputs.md
> +Model inputs do not support input transforms.
This, to me, is an important point and I would consider highlighting it with a helpful or some other emphasis block.

2024-02-22 07:55 UTC, crisbeto commented on aio/content/guide/model-inputs.md
> +name is the model input's name suffixed with "Change".
The only way to access it is through the template. I updated the comment to call it out.

2024-02-22 07:55 UTC, crisbeto commented on aio/content/guide/model-inputs.md
> +Model inputs do not support input transforms.
It's called out again in the "Differences between `model()` and `input()`" section so I'm not sure if we need any more.

2024-02-22 07:55 UTC, crisbeto commented
Feedback has been addressed.

2024-02-22 21:28 UTC, MarkTechson approved these changes
LGTM

2024-02-23 19:47 UTC, dylhunn commented
This PR was merged into the repository by commit 4efcc74dd6f039373894a515e10c5339f2935c88.

2024-02-23 19:47 UTC, closed without merging