fix(core): ensure change detection runs in a reasonable timeframe wit…
angular/angular pull request #54578
Opened 2024-02-22 20:07 UTC by atscott

…h zone coalescing

Zone event and run coalescing now races `requestAnimationFrame` and `setTimeout`. There are tradeoffs to both functions and racing the two gives us the benefits of both. This is explained in more detail in the jsdoc comment. This change also aligns the timing of zone coalescing with what will be used for zoneless.

BREAKING CHANGE: The exact timing of change detection execution when using event or run coalescing with `NgZone` is now the first of either `setTimeout` or `requestAnimationFrame`. Code which relies on this timing (usually by accident) will need to be adjusted. If a callback needs to execute after change detection, we recommend `afterNextRender` instead of something like `setTimeout`.

fixes #54544
fixes #44314
fixes #39854 (unverified but seems likely)

2024-02-23 23:40 UTC, atscott commented
[Green TGP]https://fusion2.corp.google.com/presubmit/609455884/OCL:609455884:BASE:609758268:1708710829821:901fbdd5/targets)

2024-02-24 00:24 UTC, alxhub approved these changes

2024-03-13 14:34 UTC, pkozlowski-opensource commented on packages/core/src/util/raf.ts
> +/**
I think we should move this code to a different file or rename this one - the current `util/raf.ts` is suggesting that this is just an rAf util but now we deal with the whole scheduler.

2024-03-13 14:35 UTC, pkozlowski-opensource commented on packages/core/test/zone/ng_zone_spec.ts
> +import {getCallbackScheduler} from '../../src/util/raf';
We should add tests for the new behaviour...

2024-03-13 14:35 UTC, pkozlowski-opensource requested changes
Left a couple of comments that I would love to see addressed before merging this one.

2024-03-13 15:21 UTC, atscott commented on packages/core/test/zone/ng_zone_spec.ts
> +import {getCallbackScheduler} from '../../src/util/raf';
I'm not sure how exactly you would observe the new behavior consistently. We can patch or spy on `rAF` and `setTimeout` but that turns into a change detector test pretty easily.

2024-03-13 17:00 UTC, pkozlowski-opensource approved these changes

2024-03-13 18:09 UTC, atscott commented
This PR was merged into the repository by commit 0dd441d08fb3249916f5ace7786cadf4afe49726.

2024-03-13 18:09 UTC, closed without merging