feat(common): add height support for custom image loaders
angular/angular pull request #54718
Opened 2024-03-06 13:06 UTC by charsleysa

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #51723

## What is the new behavior?
Add support to pass through the height to the custom image loader if the height is available. This allows custom image loaders to know the height at different breakpoints instead of using a fixed value using loaderParams.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-03-06 13:11 UTC, JeanMeche commented
Hi, this PR seems to be a duplictate of #51951 were this change has been discussed.

2024-03-06 13:19 UTC, charsleysa commented
> Hi, this PR seems to be a duplictate of #51951 were this change has been discussed.

From what I can tell, that PR is unfinished and modifies the default image loaders, and hasn't had any activity since November 2023.

This PR aims to only provide the height to custom loaders and does not change how the default loaders function.

2025-06-05 17:16 UTC, AndrewKushnir requested changes

2025-06-05 17:16 UTC, AndrewKushnir commented on packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
> +    const ratio = this.width != null && this.height != null ? this.width / this.height : 0;
I think it'd be great to move this logic to a separate function and reuse it in the code. In addition to checking for `this.width` and `this.height` being present, we'd need to check that the `this.height` is not 0 to avoid division by 0. Also instead of returning `0` as the default value, we should probably return `null` as an indication that the `ratio` can not be calculated, thus the `height` should not be provided to image loaders.

2025-06-25 13:29 UTC, thePunderWoman commented
Since we've not seen any movement on this, and not much community feedback, I'm going to close this for now. If you'd like to get this landed, please open a new PR. Thanks for your contribution!

2025-06-25 13:29 UTC, closed without merging