Devtools/fix signal
angular/angular pull request #54912
Opened 2024-03-17 13:58 UTC by JeanMeche

See individual commits.

2024-04-17 23:32 UTC, dgp1130 requested changes
Thanks for putting this together and apologies for the review delay. No major concerns, I think you just dropped a file in your `stopPropagation` commit.

@AleksanderBodurri, can you take a quick look as well just to make sure I'm not missing anything?

2024-04-17 23:32 UTC, dgp1130 commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/directive-explorer/directive-forest/directive-forest.component.ts
> +  }
Question: Is this used anywhere? Was this referenced in the template somewhere and dropped from this commit?

2024-04-17 23:32 UTC, dgp1130 commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/directive-explorer/directive-forest/directive-forest.component.html
> +            <mat-icon matTooltip="Mismatch" class="hydration mismatched">error_outline</mat-icon>
Suggestion: One of my points of feedback was that it's not super clear what was "Mismatched", especially for users not that familiar with hydration. Should we update these tool tips to actually use the word "hydration" such as "Hydration skipped" and "Hydration mismatch"? That way a developer would have something meaningful to search for if they want to understand what exactly this means.

2024-04-17 23:37 UTC, JeanMeche commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/directive-explorer/directive-forest/directive-forest.component.ts
> +  }
Yeah I'm not sure why the change was missing, It's back now.

2024-04-17 23:45 UTC, dgp1130 approved these changes
LGTM.

My one other minor suggestion is a brief comment either on `(dblclick)` or `stopPropogation` about the action it's trying to prevent, since it's purpose doesn't seem super obvious to me.

2024-04-25 13:10 UTC, AleksanderBodurri approved these changes

2024-04-25 21:34 UTC, AndrewKushnir commented
@JeanMeche the merge tooling failed to process this PR. Could you please rebase on top of the most recent `main` and merge fixup commits into corresponding parent commits? Merging fixup commits is automatic in the tooling, but for some reasons failed for this PR.

2024-04-25 21:50 UTC, JeanMeche commented
We should be ✅ now

2024-04-25 21:57 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 96972b45ec919a77e6031d3d0eb479905b4a699b.

2024-04-25 21:57 UTC, closed without merging