fix(common): include transferCache when cloning HttpRequest
angular/angular pull request #54939
Opened 2024-03-19 07:54 UTC by mlz11

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 54924

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-03-19 10:11 UTC, alan-agius4 commented on packages/common/http/src/request.ts
> +
```suggestion
    // Carefully handle the transferCache to differentiate between
    // `false` and `undefined` in the update args.
    const transferCache = update.transferCache ?? this.transferCache;

```

2024-03-19 10:14 UTC, alan-agius4 requested changes
Thanks for this. 

Can you please update the commit message scope from `common` to `http`?

2024-03-19 10:26 UTC, mlz11 commented
> Thanks for this.
> 
> Can you please update the commit message scope from `common` to `http`?

Of course, done ✅

2024-03-19 10:31 UTC, mlz11 commented on packages/common/http/src/request.ts
> +
Done ✅

2024-03-19 10:53 UTC, alan-agius4 approved these changes
LGTM, thanks for your contribution

2024-03-19 10:55 UTC, alan-agius4 commented
Can you please run update the golden files via `yarn bazel run //packages/common:common_api.accept`?

2024-03-19 10:57 UTC, mlz11 commented
> Can you please run update the golden files via `yarn bazel run //packages/common:common_api.accept`?

Of course, done ✅ 
I was wondering why tests were failing. Is this the reason ?

2024-03-19 11:07 UTC, kbrilla commented on packages/common/http/src/request.ts
> +    // `false` and `undefined` in the update args.
now it also handles `null` so mayby add that to comment : `undefined or null` here and in other places that were edited. Also why not add move this logic together with `withCredentials` and `reportProgress`? becouse now  
this comment is duplicated in lines 485 and 495

2024-03-19 17:33 UTC, AndrewKushnir approved these changes

2024-03-19 17:33 UTC, alan-agius4 approved these changes
LGTM

2024-03-19 22:03 UTC, dylhunn approved these changes
reviewed-for: public-api

2024-03-19 22:05 UTC, jessicajaniuk approved these changes
reviewed-for: public-api

2024-03-20 16:00 UTC, atscott approved these changes
reviewed-for: public-api

2024-03-22 05:13 UTC, dylhunn commented
This PR was merged into the repository by commit b80434a07b57229492040cbb4932c165fab44e6c.

2024-03-22 05:13 UTC, closed without merging