Docs: add a note about adding other provider configurations as options to @Injectable
angular/angular pull request #55006
Opened 2024-03-23 00:08 UTC by Ahmed-Hakeem

Adding this note to expose that user can explicitly define how the service can be called using hooks = or provider configurations that are defined by InjectableProvider type

2024-04-25 10:42 UTC, pkozlowski-opensource requested changes
Thnx for the PR. It will need some more work before we can land it:
* the commit indicates that this is a doc change but there are code changes as well - please revert those;
* I think that we should add more usage examples instead of a note

2024-04-25 10:42 UTC, pkozlowski-opensource commented on packages/core/src/di/injectable.ts
> +   * service.
I think that a code example would get the point across in a stronger / more practical way.

2024-04-25 10:42 UTC, pkozlowski-opensource commented on packages/core/src/di/injectable.ts
> +import {ClassSansProvider, ConstructorSansProvider, ExistingSansProvider, FactorySansProvider, StaticClassSansProvider, ValueSansProvider,} from './interface/provider';
code change: revert

2024-04-25 10:42 UTC, pkozlowski-opensource commented on packages/core/src/di/injectable.ts
> +export type InjectableProvider =|ValueSansProvider|ExistingSansProvider|StaticClassSansProvider|
code change: revert

2024-05-01 23:05 UTC, Ahmed-Hakeem commented
> Thnx for the PR. It will need some more work before we can land it:
> 
> * the commit indicates that this is a doc change but there are code changes as well - please revert those;
> * I think that we should add more usage examples instead of a note

I agree with you regarding adding a usage example, will add that : ) 
code changes appear to me that they're applied because of git hooks linting operations applied before commiting, I haven't intentionally added it, let me check.

2024-08-29 19:18 UTC, Ahmed-Hakeem commented
@pkozlowski-opensource I apologize for being so late on this one; I just missed it. I've included an example of how to benefit from this feature and fixed the incorrect formatting that was accidentally inserted.

2024-08-29 19:46 UTC, JeanMeche commented on packages/core/src/di/injectable.ts
> +   * <code-example path="core/di/ts/metadata_spec.ts" region="InjectableWithUseFactory"></code-example>
Note, referenced code examples don't work atm, (no idea it they will in the future, you probably want to inline it in a code blocK.

2024-08-29 19:56 UTC, Ahmed-Hakeem commented on packages/core/src/di/injectable.ts
> +   * <code-example path="core/di/ts/metadata_spec.ts" region="InjectableWithUseFactory"></code-example>
I'll update it to the inline syntax then

2024-08-29 20:40 UTC, Ahmed-Hakeem commented on packages/core/src/di/injectable.ts
> +   * <code-example path="core/di/ts/metadata_spec.ts" region="InjectableWithUseFactory"></code-example>
Now changed 👍. Thank you

2025-02-02 21:30 UTC, JeanMeche requested changes

2025-02-02 21:30 UTC, JeanMeche commented on packages/core/src/di/injectable.ts
> +   * <code-example language="typescript">
Use a 3 backtick code block instead, this is one is unstyled.

2025-05-02 11:00 UTC, JeanMeche commented
I'm going to deny the change as the belongs more into the DI guide which we are currently re-writing.

2025-05-02 11:00 UTC, closed without merging

2025-05-09 21:11 UTC, Ahmed-Hakeem commented
> I'm going to deny the change as the belongs more into the DI guide which we are currently re-writing.

Alright .... thank you @JeanMeche  for your review ❤️ 

If it hasn't been added already I'd be happy to add that to the new guide .....please let me know the PR of it if this is the case