docs: update NgClass example description to match the example's behavior
angular/angular pull request #55209
Opened 2024-04-04 05:26 UTC by Ahmed-Hakeem

Since `setCurrentClasses` is called either the dependent properties change or not, I've updated the description to mention that.

Also I've clarified that changes applied to the object is what considered by angular to update the classes and apply it = means that changes to `CurrentClasses` properties' values doesn't update the NgClass value until you reassign the `CurrentClasses` with the new values

2024-04-04 11:30 UTC, PedroMiguel7 approved these changes

2024-04-05 10:37 UTC, sonukapoor requested changes

2024-04-29 17:15 UTC, bencodezen approved these changes
Thanks for the PR!

2024-04-29 20:39 UTC, AndrewKushnir commented
This PR was merged into the repository by commit b87a4c40bf24f00fd1ea90dc8430b830fe2278d4.

2024-04-29 20:39 UTC, closed without merging