refactor(core): Make hydration zoneless compatible
angular/angular pull request #55214
Opened 2024-04-04 09:24 UTC by JeanMeche

Schedule a CD after hydration cleanup on zoneless apps.

Fixes #52160

2024-04-05 05:31 UTC, AndrewKushnir commented on packages/core/src/hydration/api.ts
> +              typeof Zone !== 'undefined' && NgZone.assertInAngularZone();
nit:
```suggestion
              if (typeof Zone !== 'undefined') {
                NgZone.assertInAngularZone();
              }
```

2024-04-05 05:31 UTC, AndrewKushnir commented on packages/core/src/hydration/api.ts
> +              typeof Zone !== 'undefined' && NgZone.assertInAngularZone();
I'm also wondering if we should add `ngDevMode` check around it.

2024-04-05 21:06 UTC, AndrewKushnir approved these changes

2024-04-05 21:15 UTC, atscott requested changes

2024-04-05 21:15 UTC, atscott commented on packages/core/src/hydration/api.ts
> +              }
I would prefer removing this entirely, to be honest.

2024-04-05 21:15 UTC, atscott commented on packages/core/src/zone/ng_zone.ts
>      Assures that the method is called within the Angular Zone, otherwise throws an error.
Probably should update the documentation here to indicate that this is a no-op if zone isn't defined.

2024-04-05 21:15 UTC, atscott commented
Removing the `patch` target. We should discuss whether this should be included in `patch`. Changing the behavior of the assert function could be considered a breaking change.

2024-04-05 21:17 UTC, atscott commented
@JeanMeche Can you update the commit message to make clear that this does not actually make zoneless hydration compatible? All this does is remove an error that would be thrown. It _does not_ add the necessary APIs that make hydration zoneless-compatible. Hydration still relies on ZoneJS to know when the application is stable.

2024-04-09 18:40 UTC, atscott commented on packages/core/src/zone/ng_zone.ts
> +   * In case of a zoneless app, this is a no-op.
> In case of a zoneless app, this is a no-op.

Sorry to have to go back and forth on this in a PR... This statement isn't true. Zone is a global and if you have 1 zoneless and and 1 zone app on the page or even import Zone and don't use it in Angular, this function _does_ still do something. I think it'd be better to revert the change here completely and only remove the assertion in hydration. We need to review what the future of this function is and how it's expected to work. If it's being used in context that absolutely does require something to be in the Angular zone, it would be wrong to make it a no-op. It's also wrong to have the assert in code that doesn't actually require something to be in the zone.

2024-04-09 18:51 UTC, atscott approved these changes

2024-04-09 19:13 UTC, atscott commented
This PR was merged into the repository by commit 4b31a88592cb5a8e4438dfa08dc031b65897cc40.

2024-04-09 19:13 UTC, closed without merging