ci: Merge primitives-shared and primitives-event-dispatch groups
angular/angular pull request #55273
Opened 2024-04-09 22:35 UTC by rahatarmanahmed

This simplifies the approvals necessary for the event dispatch directory

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] ~~Tests for the changes have been added (for bug fixes / features)~~
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Previously PRs in the event-dispatch directory required reviews from both primitives-shared and primitives-event-dispatch groups. 

Issue Number: N/A

## What is the new behavior?

Both teams have agreed to merge, so now only one reviewer is necessary.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-04-09 22:47 UTC, jatraman commented on .pullapprove.yml
> -    labels:
Do we still need these labels?

2024-04-09 22:52 UTC, rahatarmanahmed commented on .pullapprove.yml
> -    labels:
Oops, fixed.

2024-04-09 22:53 UTC, jatraman approved these changes

2024-04-10 14:10 UTC, thePunderWoman requested changes
I am not in favor of this change. These groups were designed the way they were to ensure the people dedicated to the event-dispatch work had specific approvers and ownership of that area. The pullapprove group ensures one of them is requested for review on any PR affecting that section.

If we want to have them as part of the shared primitives group, too, I think that's fine, but we should leave both.

2024-04-10 17:45 UTC, thePunderWoman approved these changes
I'm ok with this due to offline conversations. LGTM

2024-04-10 17:59 UTC, atscott commented
This PR was merged into the repository by commit 92debf44761603b0e8b8c9c8efbee17f25391c06.

2024-04-10 17:59 UTC, closed without merging