feat(core): Add a public API to establish events to be replayed and a…
angular/angular pull request #55356
Opened 2024-04-16 01:39 UTC by iteriani

…n attribute to mark an element with an event handler.

These will be consumed by the event-dispatch contract to replay events. The contract and the dispatcher inclusion will be in followups.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-04-16 11:47 UTC, alan-agius4 commented on packages/core/src/hydration/event_replay.ts
> +    script.id = 'jsa';
[We should probably add the APP ID here to handle possible multiple apps. 
](https://github.com/angular/angular/blob/bce5e2344f312dc3a8a30d54e412958bd07180c1/packages/platform-server/src/transfer_state.ts#L36)

2024-04-16 16:13 UTC, tbondwilkinson requested changes

2024-04-16 16:13 UTC, tbondwilkinson commented on goldens/public-api/platform-browser/index.md
> +    // (undocumented)
Why out of order

2024-04-16 16:13 UTC, tbondwilkinson commented on packages/core/src/hydration/annotate.ts
> +let getElementsToEvents: (tView: TView, lView: LView) => Map<Element, string[]> = () => EMPTY_MAP;
getElementsToEventTypes

they're not events themselves

2024-04-16 16:13 UTC, tbondwilkinson commented on packages/core/src/hydration/annotate.ts
> +    (eventMapGetter: typeof getElementsToEvents, attrSetter: typeof setJSActionAttribute,
I would just reuse the same variable names rather than choosing different ones. Same for the rest of the parameters

2024-04-16 16:13 UTC, tbondwilkinson commented on packages/core/src/hydration/annotate.ts
> +  eventsToReplay: Set<string>;
eventTypesToReplay

2024-04-16 16:13 UTC, tbondwilkinson commented on packages/core/src/hydration/annotate.ts
> +  const eventsToReplay = new Set<string>();
same

2024-04-16 16:13 UTC, tbondwilkinson commented on packages/core/src/hydration/annotate.ts
> +  const nativeElementsToElements = getElementsToEvents(tView, lView);
this should probably be nativeElementsToEventTypes

2024-04-16 16:13 UTC, tbondwilkinson commented on packages/core/src/hydration/annotate.ts
> +    setJSActionAttribute(tNode, lView[i], nativeElementsToElements!, context);
nativeElementsToElements is not nullable here, ! probably unnecessary

2024-04-16 16:13 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +    const events = Array.from(eventsToReplay);
eventTypes

2024-04-16 16:13 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +function getElementsToEvents(tView: TView, lView: LView): Map<Element, string[]> {
eventTypes

2024-04-16 16:13 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +  const events = new Map<Element, string[]>();
elementsToEventTypes

2024-04-16 16:13 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +      jsaction += `${event}:e;`;
any particular reason for `e` here? rather than no handler name?

2024-04-16 18:06 UTC, AndrewKushnir commented on packages/core/src/hydration/event_replay.ts
> +    // 4. Add `jsaction` attribute
I think this comment can be removed, since some of those actions are performed elsewhere and some actions (related to defer blocks) are not present in this PR.

2024-04-16 18:06 UTC, AndrewKushnir commented on packages/core/src/hydration/event_replay.ts
> +      context.eventsToReplay.add(event);
I think we can move the logic that adds events to this set outside of this function. Potentially, it can live inside the logic that collects events (i.e. in the `getElementsToEvents` function).

2024-04-16 18:06 UTC, AndrewKushnir commented on packages/platform-browser/src/hydration.ts
> + * Enables support for event replay
nit: we may need a bit more info here, since this would become visible on angular.dev, but we can do it in a followup PR.

2024-04-16 18:06 UTC, AndrewKushnir commented on packages/platform-server/test/event_replay_spec.ts
> +function stripUtilAttributes(html: string, keepNgh: boolean): string {
It looks like those helper methods and setup code came from the `hydration_spec.ts`. We can refactor this in a followup PR to extract common code into a separate helper file and reuse the code across both spec files.

2024-04-16 18:15 UTC, rahatarmanahmed commented on packages/core/src/hydration/annotate.ts
> +      insertEventReplaySupport = replaySupportSetter;
nit: should we be more specific here: insertEventReplayBinary/Script?

2024-04-16 18:33 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +        if (type === 'dom') {
Is there a way to make JSON data structures not have XSS vulnerabilities?

2024-04-16 21:08 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +    script.id = 'jsa';
done

2024-04-16 21:09 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +    script.textContent = JSON.stringify(events);
I changed this to a script tag that directly calls the bootstrapping function. It still needs the same exemption though

2024-04-16 22:30 UTC, iteriani commented on packages/core/src/hydration/annotate.ts
> +let getElementsToEvents: (tView: TView, lView: LView) => Map<Element, string[]> = () => EMPTY_MAP;
done

2024-04-16 22:30 UTC, iteriani commented on packages/core/src/hydration/annotate.ts
> +    (eventMapGetter: typeof getElementsToEvents, attrSetter: typeof setJSActionAttribute,
done

2024-04-16 22:30 UTC, iteriani commented on packages/core/src/hydration/annotate.ts
> +  const eventsToReplay = new Set<string>();
done

2024-04-16 22:30 UTC, iteriani commented on packages/core/src/hydration/annotate.ts
> +    setJSActionAttribute(tNode, lView[i], nativeElementsToElements!, context);
done

2024-04-16 22:30 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +    const events = Array.from(eventsToReplay);
done

2024-04-16 22:30 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +function getElementsToEvents(tView: TView, lView: LView): Map<Element, string[]> {
done

2024-04-16 22:30 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +      jsaction += `${event}:e;`;
nope. removed

2024-04-16 22:30 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +        setJsactionFunctions(getElementsToEvents, setJSActionAttribute, insertEventReplaySupport);
done

2024-04-16 22:31 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +function getElementsToEvents(tView: TView, lView: LView): Map<Element, string[]> {
done

2024-04-16 22:31 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +    // 4. Add `jsaction` attribute
done

2024-04-16 22:31 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +      context.eventsToReplay.add(event);
done

2024-04-16 22:31 UTC, iteriani commented on packages/platform-browser/src/hydration.ts
> + * Enables support for event replay
Ah of course.

2024-04-16 22:31 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +  if (tCleanup && lCleanup) {
done

2024-04-16 22:31 UTC, iteriani commented on packages/platform-server/test/event_replay_spec.ts
> +function stripUtilAttributes(html: string, keepNgh: boolean): string {
done

2024-04-16 22:31 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +        const type =
this is copy paste from the prototype. maybe @AndrewKushnir can help out here.

2024-04-16 22:31 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +      if (typeof firstParam === 'string') {
done

2024-04-16 22:32 UTC, iteriani commented on packages/core/src/hydration/annotate.ts
> +      insertEventReplaySupport = replaySupportSetter;
done

2024-04-17 01:28 UTC, AndrewKushnir commented on packages/core/src/hydration/annotate.ts
> +        shouldReplayEvents: shouldReplay,
```suggestion
        shouldReplayEvents,
```

2024-04-17 01:28 UTC, AndrewKushnir commented on packages/core/src/hydration/annotate.ts
> +  const shouldReplay = injector.get(IS_EVENT_REPLAY_ENABLED, false);
It'd be great to extract `false` into a const (add it to the `event_replay.ts` file), so that we can find it easier and also use in other places where it might be relevant.
```suggestion
  const shouldReplayEvents = injector.get(IS_EVENT_REPLAY_ENABLED, EVENT_REPLAY_ENABLED_DEFAULT);
```

2024-04-17 01:28 UTC, AndrewKushnir commented on packages/core/src/hydration/annotate.ts
> +  const nativeElementsToElements = context.shouldReplayEvents ?
```suggestion
  const nativeElementsToEvents = context.shouldReplayEvents ?
```

2024-04-17 01:28 UTC, AndrewKushnir commented on packages/core/src/hydration/event_replay.ts
> +    script.textContent = `window.__jsaction_bootstrap('ngContracts', document.body, '${appId}', ${
Where do we have `__jsaction_bootstrap ` defined? Is it a part of JSAction script that we plan to inline into HTML? It'd be great to add a comment in the code here to explain this.

2024-04-17 01:28 UTC, AndrewKushnir commented on packages/core/src/hydration/annotate.ts
> +      new Map();
nit: we can avoid creating an empty `Map` here (use `null`) and instead update the `if` condition below and check for `null`.

2024-04-17 01:28 UTC, AndrewKushnir commented on packages/platform-server/test/hydration_spec.ts
> +import {getAppContents, stripUtilAttributes} from './dom_utils';
Thanks for the refactoring 👍

2024-04-17 05:32 UTC, AndrewKushnir commented on packages/core/src/hydration/annotate.ts
> +export function annotateForHydration(appId: string, appRef: ApplicationRef, doc: Document) {
Just realized that we don't need to pass `appId` here, since we can retrieve it from the injector available on appRef (see another comment below).
```suggestion
export function annotateForHydration(appRef: ApplicationRef, doc: Document) {
```

2024-04-17 05:32 UTC, AndrewKushnir commented on packages/core/src/hydration/annotate.ts
> +  }
```suggestion
  if (shouldReplayEvents) {
    const appId = injector.get(APP_ID);
    insertEventListenerScript(appId, eventTypesToReplay, doc);
  }
```

2024-04-17 05:32 UTC, AndrewKushnir commented on packages/core/src/hydration/event_replay.ts
> +    }
It looks like we'll be retaining an extra `;` char for each event listener, i.e. `<div jsaction="click:;">` when it should be `<div jsaction="click:">` and the `;` char is only needed when we have multiple events.

```suggestion
    const parts = events.map(event => `${event}:`);
    if (parts.length > 0) {
      nativeElement.setAttribute('jsaction', parts.join(';'));
    }
```

2024-04-17 05:32 UTC, AndrewKushnir commented on packages/core/src/hydration/event_replay.ts
> +  if (tNode.type && TNodeType.Element) {
```suggestion
  if (tNode.type & TNodeType.Element) {
```
(see https://github.com/angular/angular/blob/main/packages/core/src/render3/interfaces/node.ts#L31)

2024-04-17 05:32 UTC, AndrewKushnir commented on packages/platform-server/src/utils.ts
> -    annotateForHydration(applicationRef, doc);
We can revert this change as not required (see a comment above).

2024-04-17 12:22 UTC, pkozlowski-opensource approved these changes
LGTM

Reviewed-for: public-api

2024-04-17 15:12 UTC, josephperrott approved these changes
LGTM

Reviewed-for: dev-infra

2024-04-17 15:52 UTC, tbondwilkinson approved these changes

2024-04-17 16:14 UTC, rahatarmanahmed commented on packages/core/src/hydration/event_replay.ts
> +        const type =
OK actually I think I get it now. I'm guessing the unsubscribe method is like an observable for the event or something?

2024-04-17 16:16 UTC, rahatarmanahmed approved these changes

2024-04-17 16:26 UTC, iteriani commented
I'm chasing down an approval for the security failure exception

2024-04-17 16:30 UTC, iteriani commented on packages/core/src/hydration/annotate.ts
> +  }
See above. this causes circular deps errors.

2024-04-17 16:30 UTC, iteriani commented on packages/core/src/hydration/annotate.ts
> +export function annotateForHydration(appId: string, appRef: ApplicationRef, doc: Document) {
I tried this earlier and I got a circular dependency build failure

2024-04-17 16:33 UTC, iteriani commented on packages/platform-server/src/utils.ts
> -    annotateForHydration(applicationRef, doc);
see comment above

2024-04-17 16:33 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +  if (tNode.type && TNodeType.Element) {
done

2024-04-17 17:39 UTC, iteriani commented on packages/platform-server/src/utils.ts
> -    annotateForHydration(applicationRef, doc);
done

2024-04-17 17:40 UTC, iteriani commented on packages/core/src/hydration/annotate.ts
> +export function annotateForHydration(appId: string, appRef: ApplicationRef, doc: Document) {
done

2024-04-17 17:50 UTC, AndrewKushnir commented on packages/platform-browser/src/hydration.ts
> +export function withEventReplay(): HydrationFeature<HydrationFeatureKind.EventReplay> {
This function didn't make it into the public API (the golden file doesn't include it). We'd need to re-export the function via https://github.com/angular/angular/blob/main/packages/platform-browser/src/platform-browser.ts#L81 and re-generate golden files once again.

2024-04-17 18:13 UTC, AndrewKushnir approved these changes

2024-04-17 18:15 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2024-04-17 23:33 UTC, AndrewKushnir commented on packages/platform-server/src/utils.ts
> +      const events = Array.from(eventTypesToBeReplayed);
nit: I'd propose extracting this logic into a separate function (similar to how we had it in the `core`).

2024-04-17 23:33 UTC, AndrewKushnir commented on packages/platform-server/src/utils.ts
> +    if (eventTypesToBeReplayed) {
If we have an empty `Set`, we would also be adding a script. I think we should only return a `Set` when there are some events defined.

2024-04-17 23:33 UTC, AndrewKushnir commented on packages/core/src/hydration/annotate.ts
> +  return undefined;
In some cases we might be returning an empty `Set`. We can add a check here and only return a `Set` if it's not empty. Also see a comment below (where we invoke the `annotateForHydration` function).
```suggestion
  return eventTypesToReplay.size > 0  ? eventTypesToReplay : undefined;
```

2024-04-17 23:42 UTC, iteriani commented on packages/core/src/hydration/annotate.ts
> +  return undefined;
done

2024-04-17 23:42 UTC, iteriani commented on packages/platform-server/src/utils.ts
> +    if (eventTypesToBeReplayed) {
done

2024-04-17 23:42 UTC, iteriani commented on packages/platform-server/src/utils.ts
> +      const events = Array.from(eventTypesToBeReplayed);
done

2024-04-17 23:55 UTC, AndrewKushnir approved these changes

2024-04-18 04:48 UTC, iteriani commented
Caretaker note: this PR requires [cl/625907131](https://critique.corp.google.com/625907131) to be submitted first.

2024-04-19 07:35 UTC, devversion approved these changes

2024-04-19 13:29 UTC, alxhub commented on packages/platform-server/src/utils.ts
> +  const replayScript = `window.__jsaction_bootstrap('ngContracts', document.body, '${appId}', ${
Maybe the same for `appId` for defensive purposes?

2024-04-19 13:47 UTC, iteriani commented on packages/platform-server/src/utils.ts
> +  const replayScript = `window.__jsaction_bootstrap('ngContracts', document.body, '${appId}', ${
done

2024-04-19 16:35 UTC, AndrewKushnir commented
**Caretaker note**: [presubmit](https://fusion2.corp.google.com/presubmit/625831277/OCL:625831277:BASE:625849907:1713398597020:a131293a/targets) is "green", this PR is ready for merge.

2024-04-19 20:12 UTC, alxhub commented
This PR was merged into the repository by commit a730f09ae9e729da79a3e0951e15e0139ef67713.

2024-04-19 20:12 UTC, closed without merging