feat(core) Replay events from the event contract using the dispatcher
angular/angular pull request #55408
Opened 2024-04-18 20:39 UTC by iteriani

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-04-18 21:07 UTC, tbondwilkinson requested changes

2024-04-18 21:07 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +              const eventContract = (globalThis as any)[CONTRACT_PROPERTY][appId] as EventContract;
Do you want to define an interface for this instead?

2024-04-18 21:07 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +                const dispatcher: Dispatcher = new Dispatcher(() => handleEvent);
Do you even need a getHandler function? Event replay comes through the event replayer.

2024-04-18 21:07 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +        return () => {};  // noop
This is kinda odd, is there no other way to indicate an injection for side-effect only?

Or do you want to return this factory so that people can call it directly in a bootstrap?

2024-04-18 21:07 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +  const eventName = event.getEventType();  // 'click'
remove comment

2024-04-18 21:07 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +  const nativeElement = event.getAction()?.element;
you can do event.getAction()!.element

no events are sent to the dispatcher without an action

2024-04-18 21:07 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +        listener();
don't you need to pass the event at least?

2024-04-18 21:07 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +    tView: TView, lView: LView, nativeElement: Element, eventName: string): Function[] {
provide a better type than `Function[]`

2024-04-18 21:07 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +  const listeners: Function[] = [];
ditto

2024-04-18 21:07 UTC, tbondwilkinson commented on packages/platform-server/test/dom_utils.ts
I'm sort of unclear on what these functions are for and how they fit into the bigger picture of this PR

2024-04-18 21:07 UTC, tbondwilkinson commented on packages/platform-server/test/event_replay_spec.ts
> +      let eventContract!: EventContract;
is ! necessary here

2024-04-18 21:27 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +                const dispatcher: Dispatcher = new Dispatcher(() => handleEvent);
i don't

2024-04-18 21:27 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +        return () => {};  // noop
This is called in two places; on SSR and hydration. In SSR this needs to be a noop.

2024-04-18 21:27 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +  const eventName = event.getEventType();  // 'click'
done

2024-04-18 21:27 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +        listener();
done

2024-04-18 21:28 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +    tView: TView, lView: LView, nativeElement: Element, eventName: string): Function[] {
you're not gonna like this one

2024-04-18 21:28 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +  const listeners: Function[] = [];
done

2024-04-18 21:28 UTC, iteriani commented on packages/platform-server/test/event_replay_spec.ts
> +      let eventContract!: EventContract;
guess not

2024-04-18 21:28 UTC, iteriani commented on packages/platform-server/test/dom_utils.ts
This is code that is shared between event_replay_spc and hydration_spec. Notably, the render() and hydrate() calls are found here.

2024-04-18 21:29 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +              const eventContract = (globalThis as any)[CONTRACT_PROPERTY][appId] as EventContract;
Something like:

interface Window {
  [CONTRACT_PROPERTY]: {[key: string]?: EventContract}
}

2024-04-18 21:31 UTC, tbondwilkinson requested changes

2024-04-18 21:31 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +type Listener = (value: any) => any;
Do we not know the type of value? Isn't it Event? and the return value is unknown (since we don't use it?)

2024-04-18 22:59 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  anyWindow: any = window,
nit: we can also include this param into the docs above (and also add docs for the `events` argument).

2024-04-18 22:59 UTC, AndrewKushnir commented on packages/core/src/hydration/event_replay.ts
> +            whenStable(appRef).then(() => {
nit: I'd propose adding a comment to mention that the timing is the same as post-hydration cleanup. That might be relevant as a context for further changes.
```suggestion
          return () => {
            // Kick off event replay logic once hydration for the initial part
            // of the application is completed. This timing is similar to the unclaimed
            // dehydrated views cleanup timing.
            whenStable(appRef).then(() => {
```

2024-04-18 22:59 UTC, AndrewKushnir commented on packages/core/src/hydration/event_replay.ts
> +                const dispatcher: Dispatcher = new Dispatcher();
The type would be inferred in this case.
```suggestion
                const dispatcher = new Dispatcher();
```

2024-04-18 22:59 UTC, AndrewKushnir commented on packages/core/src/hydration/event_replay.ts
> +        return () => {};  // noop
nit: we can expand the comment to mention that this is a noop for the server code:
```suggestion
        return () => {};  // noop for the server code
```

2024-04-18 22:59 UTC, AndrewKushnir commented on packages/core/src/hydration/event_replay.ts
> +  const lContext = getLContext(element);
We'd need to refactor this code to extract only relevant parts and avoid referencing debug utils (i.e. we need to address this TODO). Let's sync offline.

2024-04-18 22:59 UTC, AndrewKushnir commented on packages/core/src/hydration/event_replay.ts
> +function setEventReplayer(appRef: ApplicationRef, namespaces: Set<string>, dispatcher: Dispatcher) {
We don't make use of `namespaces` (yet), let's remove it for now.

2024-04-18 22:59 UTC, AndrewKushnir commented on packages/core/src/hydration/event_replay.ts
> +      handleEvent(event);
Do we get all events here or they are filtered by APP_ID already?

2024-04-18 22:59 UTC, AndrewKushnir commented on packages/core/test/bundling/defer/bundle.golden_symbols.json
> +  {
Looks like we have a "leak" here, i.e. those extra symbols made it into a bundle that was not supported to have them...

2024-04-18 23:06 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  anyWindow: any = window,
done in the other PR

2024-04-22 17:33 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +      handleEvent(event);
All events I think...need to do a followup on the case where there's multiple diffrrent app ids.

2024-04-22 18:02 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +function setEventReplayer(appRef: ApplicationRef, namespaces: Set<string>, dispatcher: Dispatcher) {
done

2024-04-22 18:02 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +        return () => {};  // noop
done

2024-04-22 18:02 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +            whenStable(appRef).then(() => {
done

2024-04-22 18:02 UTC, iteriani commented
Need to remake this branch. Ill resend a separate PR with the comments resolved

2024-04-22 18:02 UTC, closed without merging