refactor(core): Allow the container and the listenable element to be …
angular/angular pull request #55586
Opened 2024-04-30 00:15 UTC by iteriani

…configurable for early event contract.

This will allow a multi-app application to listen to early events from different elements and place them on a separate field on the window.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-04-30 15:48 UTC, tbondwilkinson submitted a review, later dismissed
Let's fix capture events too.

The smallest way is maybe

```
addEvents(types: string[], capture = false)
```

You'll need to also add an extra property for event types that are capture

2024-04-30 18:06 UTC, tbondwilkinson requested changes

2024-04-30 18:06 UTC, tbondwilkinson commented on packages/core/primitives/event-dispatch/src/earlyeventcontract.ts
> +      }
```suggestion
     const eventTypes = capture ? this.replaySink._ejsa!.etc : this.replaySink._ejsa!.et;
     eventTypes.push(eventType);
```

2024-04-30 18:06 UTC, tbondwilkinson commented on packages/core/primitives/event-dispatch/src/earlyeventcontract.ts
> +  addEvents(types: string[], capture = false) {
```suggestion
  addEvents(types: string[], capture?: boolean) {
```

2024-04-30 18:06 UTC, tbondwilkinson commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  eventContract.addEvents(events);
You'll need to actually separate out capture and non-capture events here, right?

2024-04-30 18:06 UTC, tbondwilkinson commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  events: string[],
eventTypes

2024-04-30 18:06 UTC, tbondwilkinson commented on packages/core/primitives/event-dispatch/src/earlyeventcontract.ts
> +  interface Object {
Object is a horrible name for an interface because that's a native keyword.

EarlyJsactionTracker

or something

2024-04-30 18:06 UTC, tbondwilkinson commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  anyWindow: any = window,
This may not be window, strictly speaking. Maybe rename "earlyJsactionTracker" or whatever you choose for above.

2024-04-30 18:06 UTC, tbondwilkinson commented on packages/core/primitives/event-dispatch/test/eventcontract_test.ts
> +      button.dispatchEvent(focusEvent);
button.focus() is a clearer API than creating the focusEvent

2024-04-30 18:16 UTC, iteriani commented on packages/core/primitives/event-dispatch/test/eventcontract_test.ts
> +      button.dispatchEvent(focusEvent);
the test fails when i do that :|

2024-04-30 18:16 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/earlyeventcontract.ts
> +      }
done

2024-04-30 18:16 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  eventContract.addEvents(events);
done

2024-04-30 18:17 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/earlyeventcontract.ts
> +  interface Object {
I intended this to be placed on the native object type.

2024-04-30 18:22 UTC, tbondwilkinson submitted a review, later dismissed

2024-04-30 18:22 UTC, tbondwilkinson commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  captureEventTypes: [],
```suggestion
  captureEventTypes: string[],
```

2024-04-30 18:22 UTC, tbondwilkinson commented on packages/core/primitives/event-dispatch/test/eventcontract_test.ts
> +      button.dispatchEvent(focusEvent);
Did you debug to determine why it fails?

2024-04-30 18:22 UTC, tbondwilkinson commented on packages/core/primitives/event-dispatch/src/eventcontract.ts
> +    const earlyEventHandlerCapture: (event: Event) => void = earlyJsactionData.h;
You can just reuse the earlyEventHandler variable, since it's the same

2024-04-30 19:16 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/eventcontract.ts
> +    const earlyEventHandlerCapture: (event: Event) => void = earlyJsactionData.h;
done

2024-04-30 19:17 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  events: string[],
done

2024-04-30 19:17 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/earlyeventcontract.ts
> +  addEvents(types: string[], capture = false) {
done

2024-04-30 19:17 UTC, iteriani commented on packages/core/primitives/event-dispatch/test/eventcontract_test.ts
> +      button.dispatchEvent(focusEvent);
dondone

2024-04-30 19:18 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  captureEventTypes: [],
done

2024-04-30 19:18 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/eventcontract.ts
> +    const earlyEventHandlerCapture: (event: Event) => void = earlyJsactionData.h;
done

2024-04-30 20:24 UTC, tbondwilkinson requested changes
Last comment, otherwise things look good

2024-04-30 20:24 UTC, tbondwilkinson commented on packages/core/primitives/event-dispatch/src/earlyeventcontract.ts
> +  interface Object {
It's still weird to add this to the global Object.

I think you should do:

```
export declare interface EarlyJsactionDataContainer {
  _ejsa?: EarlyJsactionData;
}

constructor(private readonly earlyJsactionDataContainer: EarlyJsactionDataContainer = window,     private readonly container = window.document.documentElement) {
  this.earlyJsactionDataContainer._ejsa = ...;
}

replayEarlyEvents(earlyJsactionDataContainer: EarlyJsactionDataContainer = window) {}

2024-04-30 20:30 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/earlyeventcontract.ts
> +  interface Object {
done

2024-04-30 20:36 UTC, tbondwilkinson approved these changes

2024-05-01 01:32 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/eventcontract.ts
> +    delete earlyJsactionContainer._ejsa;
This is a pre-existing code, but I wanted to mention that we generally try not to use `delete` operations to avoid potential performance penalties related to deopt in hidden classes in V8. We can set the value to `undefined` instead. Since this is pre-existing, we can do it in a separate PR.

2024-05-01 01:32 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/register_events.ts
> + * window object.
```suggestion
 * Provides a factory function for bootstrapping an event contract and exposing it on a
 * specified object (by default, exposed on the `window`).
```

2024-05-01 01:32 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/register_events.ts
> + * @param anyWindow The global window object that should receive the event contract.
The docs for this parameter need an update.

2024-05-01 01:32 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  earlyJsactionTracker: any = window,
Can we use more specific type here?
```suggestion
  earlyJsactionTracker: EarlyJsactionDataContainer = window,
```

2024-05-01 01:32 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  earlyJsactionTracker[field][appId] = {};
Can we do a tree-shakable dev-mode checks in this code? If yes, it might be great to assert whether `earlyJsactionTracker[field][appId]` already exists and throw an error (otherwise, we just override what we've stored before).

2024-05-01 01:32 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/register_events.ts
> + * @returns The `event` contract. This is both assigned to `anyWindow` and returned for testing.
We don't seem to return anything from this function - we can either return the event contract instance or update the docs.

2024-05-01 20:30 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/earlyeventcontract.ts
> +      this.container.addEventListener(eventType, this.replaySink._ejsa!.h, capture);
done

2024-05-01 20:30 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/register_events.ts
> + * @param anyWindow The global window object that should receive the event contract.
done

2024-05-01 20:30 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  earlyJsactionTracker: any = window,
the EarlyJsactionDataContainer is actually a field [field][appId] on the container.

2024-05-01 20:31 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  earlyJsactionTracker[field][appId] = {};
there's no such thing as a dev mode binary i think...

2024-05-01 20:31 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/register_events.ts
> + * @returns The `event` contract. This is both assigned to `anyWindow` and returned for testing.
done

2024-05-02 00:34 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/eventcontract.ts
> +      earlyJsactionData.c.removeEventListener(eventType, earlyEventHandler);
Should we add a "capture" argument while removing a listener?
```suggestion
      earlyJsactionData.c.removeEventListener(eventType, earlyEventHandler, true /* useCapture */);
```

2024-05-02 00:34 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +declare const ngDevMode: boolean | undefined;
This looks unused.

2024-05-02 00:34 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  earlyJsactionTracker: any = window,
Would it be something like this? We can also move that into a separate `type` and add some docs. Do we have other places where such type might be needed?
```suggestion
  earlyJsactionTracker: {[key: string]: {[appId: string]: EarlyJsactionDataContainer} } = window,
```

2024-05-02 00:34 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  earlyJsactionTracker[field][appId] = {};
I think we do have some dev-mode flags 1P/3P compatible (via copybara transform) in the signals code.

2024-05-02 00:35 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  earlyJsactionTracker[field][appId] = {};
We can also do this in a followup PR (let's not block this PR on this change).

2024-05-02 03:15 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/eventcontract.ts
> +      earlyJsactionData.c.removeEventListener(eventType, earlyEventHandler);
yes

2024-05-02 03:19 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +declare const ngDevMode: boolean | undefined;
yep it is. it was when i tried the dev mode thing. The issue is that we want this code to be optimized even in debug mode (or that's how it is set up), so the distinction between ngDevMode and prod isn't really a thing. (this answers the devmode comment below, which I can't respond to for some reason).

Also as a response to the type comment, I put a type in, but it's not really something that's used outside of this file. There's something similar in event_replay.ts, but we have more information there

2024-05-02 04:14 UTC, AndrewKushnir reviewed
@iteriani looks great, just a couple minor refactoring proposals.

2024-05-02 04:14 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +type Container = {[key: string]: {[appId: string]: EarlyJsactionDataContainer}};
nit: we can add a generic type here:

```suggestion
type Tracker<T> = {[key: string]: {[appId: string]: T}};
```
and use it in both functions in this file:

```
earlyJsactionTracker: Tracker<EventContract> = window,
```

(btw, should we rename this argument to something like `jsactionEventContractTracker` to drop "early" from it, since it's a different type)

and

```
earlyJsactionTracker: Tracker<EarlyJsactionDataContainer> = window,
```

2024-05-02 04:14 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/eventcontract.ts
> +      earlyJsactionData.c.removeEventListener(eventType, earlyEventHandler, /* useCapture */ true);
nit: I think there might be an opportunity for refactoring - we can move the generic code to a utility function:
```suggestion
    const {c: container, et: eventTypes, etc: eventTypesWithCapture} = earlyJsactionData;
    removeEventListeners(container, eventTypes);
    removeEventListeners(container, eventTypesWithCapture, /* useCapture */ true);
```

2024-05-02 04:14 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/eventcontract.ts
> +      earlyJsactionData.c.removeEventListener(eventType, earlyEventHandler, /* useCapture */ true);
(note: the `removeEventListeners` function is outside of the class (not a private method on a class), so that its name can be minified in 3P)

2024-05-02 18:04 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/eventcontract.ts
> +      earlyJsactionData.c.removeEventListener(eventType, earlyEventHandler, /* useCapture */ true);
done

2024-05-02 18:05 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +type Container = {[key: string]: {[appId: string]: EarlyJsactionDataContainer}};
done

2024-05-02 19:06 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  earlyJsactionTracker: any = window,
Can we use `Tracker` type here as well?
```suggestion
  earlyJsactionTracker: Tracker<EventContract> = window,
```

2024-05-02 19:06 UTC, AndrewKushnir commented on packages/core/primitives/event-dispatch/index.ts
> +export {bootstrapEventContract, Tracker} from './src/register_events';
Should we also export the newly added `bootstrapEarlyEventContract` function?

We can also update the `Tracker` type name, since it makes it into the public API (the current name is very generic). May be something like `EventContractTracker`?

2024-05-02 19:12 UTC, iteriani commented on packages/core/primitives/event-dispatch/index.ts
> +export {bootstrapEventContract, Tracker} from './src/register_events';
done

2024-05-02 19:12 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/register_events.ts
> +  earlyJsactionTracker: any = window,
done

2024-05-02 19:17 UTC, AndrewKushnir approved these changes
@iteriani thanks for addressing all the feedback 👍

2024-05-02 19:17 UTC, AndrewKushnir commented on goldens/public-api/core/primitives/event-dispatch/index.md
> +export function bootstrapEventContract(field: string, container: Element, appId: string, events: string[], earlyJsactionTracker?: any): void;
You'll probably need to re-generate golden files, this `any` would be replaced with `Tracker` type.

2024-05-02 19:21 UTC, thePunderWoman approved these changes
reviewed-for: fw-core, primitives, public-api

2024-05-02 19:57 UTC, iteriani commented
Caretaker note: This needs cl/629827687 to be merged in

2024-05-02 20:04 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2024-05-03 15:14 UTC, iteriani commented
[TGP](https://fusion2.corp.google.com/presubmit/630151652/OCL:630151652:BASE:630393398:1714749064537:bd7ec39f;groups=PossiblyNewlyFailing/targets)

2024-05-03 18:26 UTC, AndrewKushnir commented
TESTED=[TGP](https://fusion2.corp.google.com/presubmit/630151652/OCL:630151652:BASE:630393398:1714749064537:bd7ec39f;groups=PossiblyNewlyFailing/targets)

2024-05-03 18:27 UTC, AndrewKushnir commented
**Caretaker note**: the merge is scheduled for Monday, 05/06.

2024-05-06 15:15 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 8f273ce7a8de4df75c855205af03d7a9f8d56618.

2024-05-06 15:15 UTC, closed without merging