docs: add more concise description of AfterContentInit
angular/angular pull request #55609
Opened 2024-05-01 10:35 UTC by krp12345

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Term Initialized in AfterContentInit is not well defined. I attempted to well define it. 

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-05-01 11:06 UTC, krp12345 commented
I am adding commit to fix linting

2024-05-01 12:04 UTC, krp12345 commented
I fixed linting issues

2025-02-02 21:19 UTC, JeanMeche requested changes

2025-02-02 21:19 UTC, JeanMeche commented on packages/core/src/interface/lifecycle_hooks.ts
> + * A lifecycle hook that is called after Angular has fully initialized all projected content of a directive.
```suggestion
 * A lifecycle hook that is invoked after Angular has fully initialized all projected content of a directive.
```

2025-02-02 21:19 UTC, JeanMeche commented on packages/core/src/interface/lifecycle_hooks.ts
> + * A projected content is fully initialized when it is ready to be picked up for first change detection cycle.
The hook itself is part of the CD. I'm not sure this sentence make sense. I'd remove it.

2025-02-02 21:19 UTC, JeanMeche commented on packages/core/src/interface/lifecycle_hooks.ts
> + * For that, Angular executes all lifecycle hooks required before first change detection cycle on the projected content.
Not sure what's the message you're trying to convey here. Some hooks run after it.

2025-02-03 05:58 UTC, krp12345 commented
@JeanMeche 
Please take a look at this simple application: https://stackblitz.com/edit/demo-angular-standalone-components-3xpp6hso?file=src%2Fapp%2Fapp.component.ts

I believe it's important for developers to clearly understand the sequence of lifecycle hooks that Angular calls in projected components, such as Content1 and Content2, before the ngAfterContentInit hook is invoked in the CardComponent.

From the logs, we can see that ngOnChanges, ngOnInit, and ngDoCheck are called in Content1 and Content2 before ngAfterContentInit in the CardComponent. Currently, this information is something developers need to discover on their own, and I think it should be documented.

The existing documentation states that ngAfterContentInit is "called after Angular has fully initialized all content of a directive." However, there is no clear definition of what "fully initialized" means in this context.

2025-02-03 08:29 UTC, krp12345 commented on packages/core/src/interface/lifecycle_hooks.ts
> + * For that, Angular executes all lifecycle hooks required before first change detection cycle on the projected content.
The **ngOnChanges**, **ngOnInit**, and **ngDoCheck** hooks are invoked on **all projected content components** before Angular executes ngAfterContentInit **on the component that accepts the content projection**. 
The very first time execution of these hooks ensures that the component instance is thoroughly prepared for the first cycle of change detection.

Developers implement logic within these hooks to make necessary preparations prior to the first change detection cycle. This is why Angular performs the initial change detection only after these hooks (**ngOnChanges**, **ngOnInit**, and **ngDoCheck** ) have been executed.

2025-04-02 14:08 UTC, JeanMeche commented
Thank you for your contribution, but we'd like to keep the comments as is for now.

2025-04-02 14:08 UTC, closed without merging