docs: small updates to zoneless docs
angular/angular pull request #55636
Opened 2024-05-02 14:56 UTC by atscott

2024-05-02 15:59 UTC, jnizet commented on adev/src/content/guide/zoneless.md
> +- **Better ecosystem compatibility**: ZoneJS works by patching browser APIs but does not automatically have patches for every new browser API. In addition, some APIs simply cannot be patched effecitv
effecitvely -> effectively
and has to be -> and have to be

2024-05-02 18:20 UTC, bencodezen commented on adev/src/content/guide/zoneless.md
> +several change detection rounds. Ineffecitvely other cases, these observables were used because they happened to be
```suggestion
several change detection rounds. Ineffectively other cases, these observables were used because they happened to be
```

2024-05-02 18:22 UTC, bencodezen requested changes
Not sure if it was a spelling error or you meant to add another word, but after that clarification, happy to approve and mark as ready for merge!

2024-05-02 18:23 UTC, atscott commented on adev/src/content/guide/zoneless.md
> +several change detection rounds. Ineffecitvely other cases, these observables were used because they happened to be
Yea, no idea what happened there.

2024-05-06 18:03 UTC, bencodezen approved these changes
LGTM! Thanks for the PR @atscott!

2024-05-06 19:28 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 464dae94eefc12c1e7f3fabe99ea54f0c583def0.

2024-05-06 19:28 UTC, closed without merging