forms: Emit events for Submit+Reset on forms.
angular/angular pull request #55667
Opened 2024-05-03 20:58 UTC by JeanMeche

This commit add 2 new events sent over the unified event observable.

Fixes ?

2024-05-05 14:14 UTC, jnizet requested changes
It would be nice if the Formgroup could have a getter to tell us if it has been submitted, too

2024-05-05 14:14 UTC, jnizet commented on goldens/public-api/forms/index.md
> +export class FormResettedEvent extends ControlEvent {
FormResetEvent (resetted is not correct English)

2024-05-05 22:29 UTC, JeanMeche commented on goldens/public-api/forms/index.md
> +export class FormResettedEvent extends ControlEvent {
Of course, thank you.

2024-05-06 14:57 UTC, msmallest commented
> It would be nice if the Formgroup could have a getter to tell us if it has been submitted, too

Yeah, having existing getters for the types of events captured the with this unified events API has been really nice. For example:

```ts
export function touchedEvents$<T>(form: AbstractControl<T>) {
  return form.events.pipe(
    filter(
      (event: ControlEvent): event is TouchedEvent =>
        event instanceof TouchedEvent
    )
  );
}

observableValue$ = this.touchedEvents$(form).pipe(startWith(form.touched))
$signalValue = toSignal(this.observableValue$);
```

For `value`/`status`/`pristine`/`touched` events exposed so far. These initial values allow not just observables but also `toSignal`ed things to have a starting value. Having a getter to get the status of the submit at the time of the `startWith` would be great for things like this, as well as other use cases beyond this.

2024-05-07 02:50 UTC, dylhunn approved these changes
reviewed-for: fw-core, public-api, fw-forms

A nice addition to the new API! I think we need to get this in v18, even though it's technically after feature freeze, since it will be more breaking to land if we wait for v18.1.

2024-05-08 16:31 UTC, atscott approved these changes
reviewed-for: public-api

2024-05-08 17:23 UTC, dylhunn commented
Presubmit looks good: https://fusion2.corp.google.com/presubmit/631188647/OCL:631188647:BASE:631188670:1715031403246:38e97a8c/targets

2024-05-09 16:21 UTC, closed without merging