fix(core): add warning when using zoneless but zone.js is still loaded
angular/angular pull request #55769
Opened 2024-05-13 07:02 UTC by crisbeto

Users may be using zoneless, but are still loading Zone.js in which case they won't get the full benefits like reduced bundle size. These changes detect such a case and log a warning.

2024-05-13 11:37 UTC, pkozlowski-opensource requested changes
LGTM (with one nit comment) but as @JeanMeche noted the negative error code suggest that there are docs for this error, while docs are not part of this PR. Either add docs or flip the negative sign on the error code.

2024-05-13 15:56 UTC, crisbeto commented
I've switched it to a positive error code.

2024-05-13 15:57 UTC, JeanMeche approved these changes

2024-05-13 23:39 UTC, dylhunn approved these changes
reviewed-for: fw-core

2024-05-14 00:41 UTC, atscott approved these changes

2024-05-14 07:49 UTC, pkozlowski-opensource approved these changes

2024-05-15 05:16 UTC, AndrewKushnir commented on packages/core/src/change_detection/scheduling/zoneless_scheduling_impl.ts
> +      RuntimeErrorCode.ZONELESS_REMOVE_ZONE,
nit:
```suggestion
      RuntimeErrorCode.UNEXPECTED_ZONEJS_PRESENT_IN_ZONELESS_MODE,
```

2024-05-15 05:16 UTC, AndrewKushnir commented on packages/core/src/change_detection/scheduling/zoneless_scheduling_impl.ts
> +        `Consider removing Zone.js to get the full benefits of zoneless.`,
```suggestion
        `Consider removing Zone.js import (typically located in the 'polyfills.ts' file) to get the full benefits of zoneless.`,
```

2024-05-15 05:16 UTC, AndrewKushnir commented on packages/core/src/change_detection/scheduling/zoneless_scheduling_impl.ts
> +  if ((typeof ngDevMode === 'undefined' || ngDevMode) && typeof Zone !== 'undefined' && Zone) {
Quick question: why do we also do `&& Zone` after checking a `typeof`?

2024-05-15 05:19 UTC, JeanMeche commented on packages/core/src/change_detection/scheduling/zoneless_scheduling_impl.ts
> +        `Consider removing Zone.js to get the full benefits of zoneless.`,
`polyfills.ts` isn't generated by the CLI anymore since a couple of versions. We could mention the `polyfills` entry in `angular.json` though.

2024-05-15 05:24 UTC, AndrewKushnir commented on packages/core/src/change_detection/scheduling/zoneless_scheduling_impl.ts
> +        `Consider removing Zone.js to get the full benefits of zoneless.`,
> polyfills.ts isn't generated by the CLI anymore since a couple of versions

Where do we add the zone.js import? We can update the error message to use a different location.

2024-05-15 05:25 UTC, JeanMeche commented on packages/core/src/change_detection/scheduling/zoneless_scheduling_impl.ts
> +        `Consider removing Zone.js to get the full benefits of zoneless.`,
In the `angular.json`  : `"polyfills: ['zone.js']`

2024-05-15 06:37 UTC, crisbeto commented on packages/core/src/change_detection/scheduling/zoneless_scheduling_impl.ts
> +        `Consider removing Zone.js to get the full benefits of zoneless.`,
I intentionally kept this a bit vague, because there are many ways to load Zone.js. E.g. it could also be a random `script` tag on the page.

2024-05-15 06:38 UTC, crisbeto commented on packages/core/src/change_detection/scheduling/zoneless_scheduling_impl.ts
> +  if ((typeof ngDevMode === 'undefined' || ngDevMode) && typeof Zone !== 'undefined' && Zone) {
It's just in case `Zone` is defined but null. It's a bit of an edge case, but it doesn't hurt to have it since it'll be removed in production mode.

2024-05-15 16:02 UTC, AndrewKushnir commented on packages/core/src/change_detection/scheduling/zoneless_scheduling_impl.ts
> +        `Consider removing Zone.js to get the full benefits of zoneless.`,
@crisbeto thanks for additional info 👍 Do we expect to have zone.js at the same location for the majority of CLI apps? If that's the case, here is an alternative proposal for the error message, feel free to use and update it as you see fit. 
```suggestion
        `Consider removing Zone.js to get full benefits of zoneless. In CLI-based applications, ` + 
        `zone.js reference is typically located in the "polyfills" section of the \`angular.json\` file.`,
```

2024-05-15 16:03 UTC, AndrewKushnir approved these changes
LGTM (just 1 **non-blocking** comment) 👍

2024-05-15 16:03 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2024-05-15 20:32 UTC, atscott approved these changes
reviewed-for: public-api

2024-05-15 20:45 UTC, thePunderWoman approved these changes
reviewed-for: fw-core, public-api

2024-05-21 06:37 UTC, dylhunn commented
This PR was merged into the repository by commit ae0baa25228d679c7a4df6950676b39417ad2f1a.

2024-05-21 06:37 UTC, closed without merging

2024-05-22 01:31 UTC, spock123 commented
Just FYI, @angular/fire does not work without Zones, so the only way to use that with zoneless, is to still load zoneJS in polyfills, but use the zoneless change detection. Removal of zoneJS from polyfills will lead to @angular/fire crashing out badly.

So for a while , until they get that fixed (if they do), this will give a warning for a lot of people trying out zoneless with @angular/fire.