feat(router): export function to run guards serially
angular/angular pull request #55890
Opened 2024-05-20 13:22 UTC by junpls

When multiple guards are defined for a route, they run concurrently by default. There are use cases in which it is desirable to compose guards serially, e.g., when one guard depends on pre-conditions established by another one. A basic `runSerially` function existed in the tests already. This commit makes the function importable and modifies it to handle more edge cases that will occur in practical use.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?
A helper function is added to compose functional guards serially.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2024-05-20 14:41 UTC, atscott requested changes
👍

2024-05-20 14:41 UTC, atscott commented on packages/router/src/utils/functional_guards.ts
> +export function runSerially(
In order for this to be part of the public API, you also have to export it from `packages/router/src/index.ts` and then run the command to accept the new public API golden: `yarn bazel run //packages/router:router_api.accept`

2024-05-20 14:44 UTC, JeanMeche commented on packages/router/src/utils/functional_guards.ts
> +export function runSerially(
Would be great to also add `@publicApi`, usually at the last of the JSDoc.

2024-05-20 15:07 UTC, junpls commented on packages/router/src/utils/functional_guards.ts
> +export function runSerially(
Thanks for the quick feedback. I will use the same JSDoc footer section as in the other functions within this file.

2024-05-20 15:58 UTC, atscott commented on goldens/public-api/router/index.md
> +export function runSerially(guards: CanActivateFn[] | CanActivateChildFn[]): CanActivateFn | CanActivateChildFn;
Hmm, now that I'm seeing the types here in the public API, I'm wondering if we should name this `runCanActivateGuardsSerially` or something similar. It's more certainly more verbose but what happens if/when there's a request to have a similar function for `CanMatch` or `CanDeactivate` (or any other guard)

2024-05-20 17:33 UTC, atscott commented on goldens/public-api/router/index.md
> +export function runSerially(guards: CanActivateFn[] | CanActivateChildFn[]): CanActivateFn | CanActivateChildFn;
>  One could argue that the compatible signatures of these types are just incidental.

It is somewhat incidental but also at the same time, it's not. The guards are run at the some point in the router pipeline so they have all these same data available to them. It's very unlikely that these two would ever diverge in parameters or return values.

2024-05-21 18:25 UTC, atscott approved these changes

2024-05-28 13:26 UTC, pkozlowski-opensource reviewed
LGTM

Reviewed-for: public-api

2024-05-28 13:27 UTC, pkozlowski-opensource commented
This PR will need rebase after all the recent merges.

2024-05-28 14:22 UTC, JeanMeche approved these changes
Docs wise

2024-06-06 20:15 UTC, atscott approved these changes
reviewed-for: public-api

2024-06-06 20:19 UTC, thePunderWoman approved these changes
reviewed-for: public-api

2024-08-09 15:23 UTC, atscott commented
Closing. After further discussion, this is something that fits better in a community library. The framework aims to provide the building blocks that can be composed in community libraries to create utilities for various usage patterns.

2024-08-09 15:23 UTC, closed without merging