refactor(core): Use event_dispatcher in event_replay code.
angular/angular pull request #56036
Opened 2024-05-23 10:59 UTC by iteriani

This makes events bubble! This change also contains changes to dispatcher and event_dispatcher to make replay synchronous, so that we avoid odd timing issues. This can be split out though.

Lastly, we have one cleanup change to move the mapping from event type to functions on the element itself.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-05-23 19:54 UTC, tbondwilkinson requested changes

2024-05-23 19:54 UTC, tbondwilkinson commented on packages/core/primitives/event-dispatch/src/event_dispatcher.ts
> +const COMPOSED_PATH_ERROR_MESSAGE_DETAILS = () =>
This probably shouldn't be an arrow function.

2024-05-23 19:54 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
>   * Associates a DOM element with `jsaction` attribute to a map that contains info about all event
Update comment

2024-05-23 19:54 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
> +                  el.__jsaction_fns = undefined;
detele el.__jsaction_fns removes it entirely

2024-05-23 19:54 UTC, tbondwilkinson commented on packages/platform-server/test/BUILD.bazel
> +ts_library(
I don't see this file in this PR

2024-05-23 19:59 UTC, iteriani commented on packages/platform-server/test/BUILD.bazel
> +ts_library(
this file already exists; it's a common dep of both event_replay_spc and hydration_spec

2024-05-23 19:59 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
> +                  el.__jsaction_fns = undefined;
andrew asked us to avoid using delete keyword because it may have perf implications.

2024-05-23 20:00 UTC, iteriani commented on packages/core/primitives/event-dispatch/src/event_dispatcher.ts
> +const COMPOSED_PATH_ERROR_MESSAGE_DETAILS = () =>
oops yea needed to finish that part

2024-05-23 20:00 UTC, iteriani commented on packages/core/src/hydration/event_replay.ts
>   * Associates a DOM element with `jsaction` attribute to a map that contains info about all event
this still needs to happen right?

2024-05-23 20:02 UTC, tbondwilkinson approved these changes

2024-05-23 20:02 UTC, tbondwilkinson commented on packages/core/src/hydration/event_replay.ts
>   * Associates a DOM element with `jsaction` attribute to a map that contains info about all event
The comment is about a map and it's now a set.

2024-05-23 22:37 UTC, AndrewKushnir approved these changes

2024-05-23 22:38 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2024-05-28 12:44 UTC, pkozlowski-opensource approved these changes
LGTM

Reviewed-for: public-api

2024-05-28 21:40 UTC, thePunderWoman approved these changes
LGTM

reviewed-for: fw-core, primitives, public-api

2024-05-28 21:40 UTC, thePunderWoman commented on packages/core/src/hydration/event_replay.ts
>   * Associates a DOM element with `jsaction` attribute to a map that contains info about all event
Fixing this comment would `Set` us up for success.

2024-05-29 03:11 UTC, iteriani commented
TESTED=[TGP](https://fusion2.corp.google.com/presubmit/636611255/OCL:636611255:BASE:637888240:1716942237857:2996fa6/targets)

2024-05-29 10:59 UTC, pkozlowski-opensource commented
This PR was merged into the repository by commit 1223122080ada636443950d5f70fe11eb7ef72dd.

2024-05-29 10:59 UTC, closed without merging