docs(language-service): Fix quick info URLs
angular/angular pull request #56416
Opened 2024-06-12 19:21 UTC by ViktorTyultinov

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #56410

## What is the new behavior?
Proper redirection to the new angular website from the quick info 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-06-12 19:30 UTC, atscott requested changes

2024-06-12 19:30 UTC, atscott commented on packages/language-service/src/quick_info_built_ins.ts
> +    links: ['[AIO Reference](https://angular.dev/guide/defer#defer)'],
```suggestion
    links: ['[Reference](https://angular.dev/guide/defer#defer)'],
```

nit: Remove AIO as well from the text

2024-06-12 19:35 UTC, ViktorTyultinov commented on packages/language-service/src/quick_info_built_ins.ts
> +    links: ['[AIO Reference](https://angular.dev/guide/defer#defer)'],
I just did. I also made the links one bit more specific

2024-06-12 19:37 UTC, atscott approved these changes

2024-06-12 19:40 UTC, JeanMeche commented
Can you fix the formatting by running `yarn ng-dev format files packages/language-service/src/quick_info_built_ins.ts`

2024-06-12 20:00 UTC, ViktorTyultinov commented
@JeanMeche It should be fine now. Thank you for the guidance!

2024-06-12 21:27 UTC, atscott approved these changes

2024-06-13 16:22 UTC, AndrewKushnir approved these changes

2024-06-13 16:23 UTC, closed without merging

2024-06-13 16:23 UTC, AndrewKushnir commented
This PR was merged into the repository by commit c698668a522e927d3a90fdf3494747930911d106.

The changes were merged into the following branches: main, 18.0.x