docs: fix code example for http headers
angular/angular pull request #56508
Opened 2024-06-19 00:00 UTC by JeanMeche

2024-06-19 07:33 UTC, jnizet requested changes

2024-06-19 07:33 UTC, jnizet commented on adev/src/content/guide/http/making-requests.md
> +  params: baseHeaders.set('X-Debug-Level', 'verbose'),
The option name should be `headers`, not `params`

2024-06-19 09:01 UTC, JeanMeche commented on adev/src/content/guide/http/making-requests.md
> +  params: baseHeaders.set('X-Debug-Level', 'verbose'),
Good catch !

2024-06-19 21:05 UTC, AndrewKushnir approved these changes

2024-06-20 15:55 UTC, closed without merging

2024-06-20 15:55 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 55835e9bc99acd7ac4c3cb4b35898121268dba18.

The changes were merged into the following branches: main, 18.0.x