docs: add documentation page for let declarations
angular/angular pull request #56886
Opened 2024-07-08 07:56 UTC by crisbeto

Adds a docs page for the new `@let` syntax in Angular 18.1.

2024-07-08 08:00 UTC, crisbeto commented on adev/src/content/guide/templates/overview.md
> +| Topics                                                                    | Details                                                                       |
Context here is that I:
1. Added a link to the control flow guide since it wasn't mentioned here.
2. Added a link to the `@let` guide.

2024-07-08 15:31 UTC, MarkTechson requested changes
One small change request but otherwise this is good to go.

2024-07-08 15:31 UTC, MarkTechson commented on adev/src/content/guide/templates/let-template-variables.md
> +`@let` declarations are scoped to the current view and its descendants, but they **cannot** be
```suggestion
`@let` declarations are scoped to the current view and its descendants. `@let` declarations are not hoisted so they **cannot** be
```

What do you think about calling out the lack of hoisting directly?

2024-07-08 16:37 UTC, crisbeto commented on adev/src/content/guide/templates/let-template-variables.md
> +`@let` declarations are scoped to the current view and its descendants, but they **cannot** be
Good callout, I've updated it.

2024-07-08 16:39 UTC, MarkTechson approved these changes
LGTM!

2024-07-09 07:38 UTC, pkozlowski-opensource commented
This PR was merged into the repository by commit 02a31c5e4b1a8c8f55d9b3a11a13e64ad77368a0.

The changes were merged into the following branches: main, 18.1.x

2024-07-09 07:38 UTC, closed without merging