docs: Adding Router service hierarchical injection level
angular/angular pull request #57053
Opened 2024-07-19 07:14 UTC by krp12345

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Each service in angular framework should have a level at which it is provided. This is for better clarity. 

Issue Number: N/A

## What is the new behavior?
Router service will have level of hierarchy at which it is provided.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-07-19 14:32 UTC, atscott requested changes

2024-07-19 14:32 UTC, atscott commented on packages/router/src/router.ts
> + * This service is provided at root level in hierarchical dependency injection structure by importing module returned from `forRoot` method of [RouterModule](api/router/RouterModule) .
```suggestion
 * This service is provided in the root scope and configured with [provideRouter](api/router/provideRouter).
```

2024-07-19 14:32 UTC, atscott commented on packages/router/src/router.ts
>   * @see {@link Route}
```suggestion
 * @see {@link Route}
 * @see {@link provideRouter}
```

2024-07-19 15:45 UTC, krp12345 reviewed
Agreed with @atscott

2024-07-19 15:48 UTC, krp12345 commented
@atscott I did not know that new way to configure routes. Thanks

2024-07-22 17:49 UTC, atscott approved these changes

2024-07-22 17:52 UTC, atscott commented
This PR was merged into the repository by commit 13bc8d7d81ae1c8a5281522e9c8f4c03ed07fa5f.

The changes were merged into the following branches: main, 18.1.x

2024-07-22 17:52 UTC, closed without merging