feat(core): introduce debugName optional arg to framework signal functions
angular/angular pull request #57073
Opened 2024-07-22 04:52 UTC by AleksanderBodurri

Angular DevTools is working on developing signal debugging support. This commit is a step in the direction of making available debug information to the framework that will allow Angular DevTools to provide users with more accurate information regarding the usage of signals in their applications.

Follow up PRs that will use this arg will:
- Develop a typescript transform that will detect usages of signal functions and attempt to add a debugName without the user needing to specify one directly
- Develop debug APIs for discovering signal graphs within Angular applications (using debugName as a way to label nodes on the graph)

2024-07-22 17:42 UTC, mturco approved these changes
LGTM

2024-07-22 23:07 UTC, dgp1130 reviewed
Thanks @AleksanderBodurri, this look great! A lot more places to update than I expected. :sweat_smile:

I just have one question about `ngDevMode` usage and a few minor nits, but nothing too significant here.

2024-07-22 23:12 UTC, JeanMeche commented on packages/core/primitives/signals/src/graph.ts
> +   * A debug name for the reactive node. Used in Angular DevTools to identify the node.
+1 I'd add the details when the final implementation of the removal has landed.

2024-07-26 22:37 UTC, JeanMeche commented on packages/core/src/authoring/model/model_signal.ts
> +export function createModelSignal<T>(initialValue: T, opts?: ModelOptions): ModelSignal<T> {
`ModelOptions`'s alias isn't used in the function. Should we narrow down the type here ?

2024-07-26 22:45 UTC, JeanMeche commented on packages/core/test/signals/signal_spec.ts
That would be `packages/core/test/render3/reactivity_spec.ts` I think.

2024-07-27 02:15 UTC, AleksanderBodurri commented on packages/core/primitives/signals/src/graph.ts
> +   * A debug name for the reactive node. Used in Angular DevTools to identify the node.
Good point, although this makes me wonder if removing it from production builds is the correct behaviour in the case where its provided by developers manually 🤔 

Will add an explanation assuming we always remove it for now.

2024-07-27 02:41 UTC, AleksanderBodurri commented on packages/core/src/render3/reactivity/effect.ts
> +    ngDevMode ? options?.debugName : undefined,
I see what you mean, this kind of relates to https://github.com/angular/angular/pull/57073#discussion_r1687218883

I see the options as:

**debugName is always removed in a production build**.
- Requires ngDevMode to be generated by the transform as well as the ngDevMode in this PR. Without those, debugName could be output in a prod build in a case like the one you describe above
- Docstring makes it clear debugName is a dev mode only option

OR

**debugName is only removed in a production build if it is not provided manually by the developer**
-  transform logic only gates debugName behind ngDevMode if it is not alread provided. All of the ngDevMode checks in other places in this PR are removed

thoughts @dgp1130 ?

2024-07-29 15:54 UTC, dgp1130 commented on packages/core/src/render3/reactivity/effect.ts
> +    ngDevMode ? options?.debugName : undefined,
I think this is a slightly different question. How `debugName` relates to `ngDevMode` is not a concern for functions like `effect`. From the perspective of `effect`, either it's given a `debugName` or it isn't. The current value of `ngDevMode` is irrelevant to supporting `debugName`.

The compiler transform is the part where we define the relationship with `ngDevMode` and its behavior for production builds. That would include whether or not we eliminate a user-provided `debugName`.

This does imply that use cases which the compiler transform cannot detect (ex `signal(0, options)`) will still retain `debugName` at runtime in production builds. That behavior seems reasonable to me given that other tools could call reflection-style APIs which expose this `debugName` or maybe surface it in error messages (ex "`computed` value 'getFullName' threw error: ..."). I'd be curious if there's other trade offs here or if anyone from the framework team has opinions on it. Arguably we could have ever so slightly smaller bundles by eliminating statements like `data.debugName = options.debugName;`, but I'm not sure that's worth the effort.

2024-07-29 16:15 UTC, AleksanderBodurri commented on packages/core/src/render3/reactivity/effect.ts
> +    ngDevMode ? options?.debugName : undefined,
Makes sense, will update this PR to remove those checks

2024-08-12 21:13 UTC, dgp1130 reviewed
@alxhub, can you take a look? Any concerns on your end?

2024-08-12 21:13 UTC, dgp1130 commented on packages/core/test/acceptance/authoring/model_inputs_spec.ts
> +    }
Nit: Do we need the directives for these test cases? Can we move the signals into the components instead and simplify?

2024-09-05 17:37 UTC, alxhub requested changes
Generally this LGTM. For g3sync reasons you'll need to separate the changes to `@angular/core/primitives` code into a separate PR, plus there are a few topics to discuss on

2024-09-05 17:37 UTC, alxhub commented on packages/core/src/render3/reactivity/computed.ts
> +  getter[SIGNAL].debugName = options?.debugName;
Should we not assign this only in`ngDevMode` above? Also, we should _conditionally_ assign only if `options?.debugName` is defined (otherwise we add an extra property to all nodes of this type, which has a high memory cost).

2024-09-05 17:37 UTC, alxhub commented on packages/core/src/render3/reactivity/effect.ts
> +    ngDevMode ? options?.debugName : undefined,
We should discuss and answer this question before landing the PR, for sure.

In general, my expectation was that `debugName`s would not appear in production bundles. This is for several reasons:

1. code size. we want to allow developers to specify descriptive strings, but not pay the cost of these strings in the production bundle.
2. obfuscation. these strings may be variable names extracted from the application that the developer is otherwise expecting to be minified/obfuscated in the final bundle.

2024-09-05 23:49 UTC, dgp1130 commented on packages/core/src/render3/reactivity/effect.ts
> +    ngDevMode ? options?.debugName : undefined,
Discussed this a bit offline. The goal was always to omit `debugNames` in production, the main question is whether that's done solely in the compiler or also enforced at runtime in the framework. Gating these on `ngDevMode` can slightly reduce bundle size by eliminating these assignments and also reduce memory if the properties aren't added.

Would something like:

```typescript
if (options.debugName) {
  signal.debugName = options.debugName;
}
```

Address the memory concerns or should just gate everything on `ngDevMode` in the framework as well?

```typescript
if (ngDevMode && options.debugName) {
  signal.debugName = options.debugName;
}
```

I was thinking it would be better for maintainability to not couple to `ngDevMode` at this layer, but if we need to do this for memory usage or bundle size, I'm ok with that.

2024-09-09 20:53 UTC, dgp1130 approved these changes

2024-09-09 20:53 UTC, dgp1130 commented on packages/core/src/render3/reactivity/effect.ts
> +    ngDevMode ? options?.debugName : undefined,
Had a brief conversation with @alxhub and we ultimately decided to gate all the `.debugName` assignments on `ngDevMode` as this would save a few bytes on the wire and we couldn't come up with any compelling uses for retaining this information in production given that it won't be accessible in the `ng` global anyways. If we ever find a valid use case in the future, we can consider revisiting this.

2024-09-12 17:23 UTC, dgp1130 approved these changes

2024-10-08 23:49 UTC, dgp1130 approved these changes

2024-10-10 17:10 UTC, alxhub approved these changes

2024-10-10 17:10 UTC, alxhub commented on packages/core/src/authoring/queries.ts
> +    opts: {
It surprises me that this works - I would expect TS to fall into the optional signature, because `{read: X}` is assignable to `{debugName?: string}|undefined`. I would suggest putting this signature first in the list.

2024-10-22 01:56 UTC, AndrewKushnir approved these changes
Reviewed-for: public-api

2024-10-22 13:50 UTC, thePunderWoman approved these changes
reviewed-for: public-api

2024-10-22 17:23 UTC, alxhub commented
Caretaker: this is "green" in g3.

2024-10-22 18:09 UTC, alxhub approved these changes

2024-10-22 18:26 UTC, closed without merging