docs(docs-infra): remove hash before link
angular/angular pull request #57351
Opened 2024-08-12 16:55 UTC by vladboisa

Remove hash in link for correct view

Fixes #57349

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #57349 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-08-12 16:57 UTC, JeanMeche requested changes
This won't fix the issue.

2024-08-13 17:39 UTC, vladboisa commented
> This won't fix the issue. `@link` cannot be used to point to a method.
> 
> `{@link MyClass#myMethod}` should work though.

Done, thank you for a hint!

2024-08-14 17:35 UTC, JeanMeche commented on packages/core/src/linker/compiler.ts
> +   * Same as {@link Compiler#compileModuleSync} but also creates ComponentFactories for all components.
Actually we'll need to go one step further: 
```suggestion
   * Same as {@link Compiler#compileModuleSync compileModuleSync} but also creates ComponentFactories for all components.
```

2024-08-15 11:52 UTC, vladboisa commented on packages/core/src/linker/compiler.ts
> +   * Same as {@link Compiler#compileModuleSync} but also creates ComponentFactories for all components.
Fixed it.
Didn't even think of that, is it to display the link name correctly?
Thank you!

2024-08-18 12:51 UTC, JeanMeche approved these changes

2024-08-29 14:41 UTC, AndrewKushnir approved these changes

2024-08-29 14:42 UTC, AndrewKushnir commented
This PR was merged into the repository by commit cacf2b6fc61b9163aaccdda3a6985f72dd55c634.

The changes were merged into the following branches: main, 18.2.x

2024-08-29 14:42 UTC, closed without merging