refactor(devtools): use signal apis in profiler and frame-selector
angular/angular pull request #57558
Opened 2024-08-28 06:17 UTC by sheikalthaf

Refactor the profiler and frame-selector components to use signal apis, in future we can make the components onPush and zoneless

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #57557 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2024-09-02 00:43 UTC, sheikalthaf commented on devtools/projects/ng-devtools-backend/src/lib/highlighter.ts
> +  unHighlight();
yes because calling `highlightSelectedElement` lost the previous `selectedElementOverlay` reference. Also we are hightlight one element at a time.

2024-09-05 15:39 UTC, sheikalthaf commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/profiler.component.ts
> +    afterNextRender({
@AleksanderBodurri we are using `afterNextRender` in our refactor to follow the latest Angular feature and i believe this is the future and also `afterBextEffect` also released.

2024-09-09 16:08 UTC, AleksanderBodurri requested changes

2024-09-09 16:08 UTC, AleksanderBodurri commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/profiler.component.ts
> +    afterNextRender({
The usecase for `afterNextRender` and `afterRender` are around performing DOM operations. It seems like this code block is setting up some message bus listeners.

2024-09-09 16:08 UTC, AleksanderBodurri commented on devtools/projects/ng-devtools-backend/src/lib/highlighter.ts
> +  unHighlight();
If it's not too much work, could you open a GitHub issue with a description and screenshot of the bug that this is causing? We can retroactively attach this PR to that issue

2024-09-10 00:54 UTC, sheikalthaf commented on devtools/projects/ng-devtools-backend/src/lib/highlighter.ts
> +  unHighlight();
@AleksanderBodurri ok, will create the separate PR

2024-09-10 01:03 UTC, sheikalthaf commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/profiler.component.ts
> +    afterNextRender({
@AleksanderBodurri removed the afterNextRender and directly added to constructor.

2024-09-29 02:10 UTC, sheikalthaf commented
@AleksanderBodurri addressed the given suggestion, can review this PR again.

2024-09-29 16:00 UTC, pkozlowski-opensource reviewed
Some drive-by comments...

2024-09-29 16:00 UTC, pkozlowski-opensource commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/timeline.component.ts
> +    // this._graphDataSubject.next(this._graphDataSubject.value.slice());
why was this line commented out?

2024-09-30 05:07 UTC, sheikalthaf commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/frame-selector.component.html
> +    [disabled]="endFrameIndex() >= frameCount() - 1 || selectedFrameIndexes().size > 1"
@pkozlowski-opensource moved the disable logic `computed`.

2024-09-30 05:08 UTC, sheikalthaf commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/frame-selector.component.ts
> +    effect(() => {
@pkozlowski-opensource now using `afterRenderEffect` based on your suggestion and simplifed the code.

2024-09-30 05:08 UTC, sheikalthaf commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/frame-selector.component.ts
> +    effect(() => {
@pkozlowski-opensource now using `afterRenderEffect` based on your suggestion and simplifed the code.

2024-09-30 05:09 UTC, sheikalthaf commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/timeline.component.ts
> +    // this._graphDataSubject.next(this._graphDataSubject.value.slice());
@pkozlowski-opensource we no longer using the `this._graphDataSubject` instead using signal property which changes the reference on every update.

2024-09-30 19:53 UTC, pkozlowski-opensource commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/timeline.component.ts
> +    // this._graphDataSubject.next(this._graphDataSubject.value.slice());
Right, in this case just delete this code, instead of commenting it out.

2024-10-01 02:32 UTC, sheikalthaf commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/profiler/timeline/timeline.component.ts
> +    // this._graphDataSubject.next(this._graphDataSubject.value.slice());
Yes, removed the commented lines in recent push.

2024-10-07 04:49 UTC, AleksanderBodurri approved these changes
LGTM, approved with a small nit

2024-10-07 04:49 UTC, AleksanderBodurri commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/directive-explorer/directive-forest/directive-forest.component.ts
> +      const _ = this._tabUpdate.tabUpdate();
Nit: we can avoid the variable assignment here by invoking the signal and leaving a comment explaining why it's a dependency.

2024-10-07 05:22 UTC, sheikalthaf commented on devtools/projects/ng-devtools/src/lib/devtools-tabs/directive-explorer/directive-forest/directive-forest.component.ts
> +      const _ = this._tabUpdate.tabUpdate();
@AleksanderBodurri removed the variable assignment and added comments.

2024-10-08 16:09 UTC, sheikalthaf commented
@AleksanderBodurri can you move this PR for merge.

2024-10-21 17:17 UTC, sheikalthaf commented
@AleksanderBodurri @dgp1130 @pkozlowski-opensource any update on this PR?

2024-10-21 18:03 UTC, AleksanderBodurri commented
> @sheikalthaf 

Apologies for the wait 🙏 this is on my radar for review this week

2024-10-25 00:32 UTC, AleksanderBodurri approved these changes

2024-10-28 19:28 UTC, alxhub commented
This PR was merged into the repository by commit d98d7dc1ec6e93f2849668395fefcc6403db7d8e.

The changes were merged into the following branches: main

2024-10-28 19:28 UTC, closed without merging