docs: changed wording in ComponentDecorator to incorporate components…
angular/angular pull request #57786
Opened 2024-09-12 05:09 UTC by enstenr

… without NgModule #57709

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-09-12 13:45 UTC, thePunderWoman requested changes
Thanks for the effort here. I think it could use a little more though.

2024-09-12 13:45 UTC, thePunderWoman commented on packages/core/src/metadata/directives.ts
> +   * When running Angular application with NgModule, a component must belong to an NgModule in order for it to be available
The grammar here isn't quite right. However I think this could be updated to be even better incorporating standalone and NgModules. Something like "If you're using NgModules in your application, you may have to declare your directives as part of an NgModule. Standalone components do not require this."

2024-09-12 13:49 UTC, JeanMeche commented
FYI, we have another PR in parallel for the same issue #57709

2024-09-13 05:19 UTC, enstenr commented
> FYI, we have another PR in parallel for the same issue #57709

So can i discard this PR, will this be handled there ?

2024-09-24 11:17 UTC, JeanMeche commented
Yes #57878 was merged.

2024-09-24 11:17 UTC, closed without merging