refactor(router): publishing getLoadedRoutes using the global utils function
angular/angular pull request #58199
Opened 2024-10-14 23:45 UTC by sumitarora

Angular DevTools uses globally available functions to provide debugging information to the framework. This commit exports `getLoadedRoutes` function using the `ɵpublishExternalGlobalUtil` function added in PR: https://github.com/angular/angular/commit/f5cd8f7ab498f35dc2ec3c6662d4443135989720.

Follow-up PRs that will:
- Add a new router example in the Angulat DevTools demo application.
- Implement the router graph in the Angular DevTools to view the routes that are loaded in the application

2024-10-14 23:50 UTC, dgp1130 approved these changes
One minor suggestion on a side-effectful import, but otherwise LGTM.

2024-10-14 23:50 UTC, dgp1130 commented on packages/router/src/index.ts
> +export * from './router_devtools';
Nit: I suggest changing this to `import './router_devtools';`, for two reasons:

1. Nothing is exported from this module, so an `export *` doesn't actually export anything, which is a bit confusing.
2. What we want is to execute the top-level side effect to publish the goal. Using `import` without referencing any symbols is at least clear that we care about the side-effect of importing the file, not importing any particular symbol.

2024-10-15 02:57 UTC, AndrewKushnir commented on packages/router/src/index.ts
> +export * from './router_devtools';
I think the recommended change would also solve [the CI issue](https://github.com/angular/angular/actions/runs/11336651558/job/31526981953?pr=58199).

2024-10-21 23:00 UTC, alxhub requested changes
It's surprising to me that this PR touches `yarn.lock` - did that get accidentally included?

2024-10-21 23:03 UTC, dgp1130 commented
@alxhub, it's intentional as this needed to bump the internal dependency on `@angular/core` in order for `ɵpublishExternalGlobalUtil` to exist in ADEV, otherwise there's a failure in CI.

2024-10-22 00:29 UTC, dgp1130 approved these changes

2024-10-22 09:54 UTC, josephperrott approved these changes
LGTM

Reviewed-for: dev-infra

2024-10-22 15:08 UTC, alxhub approved these changes

2024-10-22 16:40 UTC, AndrewKushnir commented
This PR was merged into the repository by commit 0ea9b8892bf68f8cf3af6ca243760e571e8c5a69.

The changes were merged into the following branches: main

2024-10-22 16:40 UTC, closed without merging