fix(core): cleanup `rxResource` abort listener
angular/angular pull request #58306
Opened 2024-10-22 15:58 UTC by arturovt

This commit updates the `rxResource` functionality. Currently, we're attaching an `abort` event listener to the signal (when provided) and never removing it. To ensure proper resource management, we should remove event listeners when they are no longer needed, allowing objects to be garbage collected. In Firefox, saving a heap snapshot and analyzing it with `fxsnapshot` reveals that querying `AbortSignal` prints a "CaptureMap" with a list of "lambdas", indicating that the signal is not garbage collected due to the event listener's lambda function.

2024-10-23 11:37 UTC, pkozlowski-opensource approved these changes

2024-10-23 14:54 UTC, pkozlowski-opensource requested changes
See https://github.com/angular/angular/pull/58306/files#r1812963772

2024-10-23 17:23 UTC, arturovt commented on packages/core/rxjs-interop/src/rx_resource.ts
> +          finalize(() => params.abortSignal.removeEventListener('abort', onAbort)),
The controller itself is not a "leaker"; leaks are usually caused by closures associated with functions, such as an event listener function in this case.

2024-10-25 09:36 UTC, arturovt commented
@pkozlowski-opensource I have rebased after `firstValueFrom` has been removed.

2024-12-20 23:36 UTC, arturovt commented
@pkozlowski-opensource could you have a look?

2025-05-21 14:25 UTC, pkozlowski-opensource approved these changes

2025-05-21 15:17 UTC, closed without merging

2025-05-21 15:17 UTC, thePunderWoman commented
This PR was merged into the repository by commit 93e8565f0ef550fcea8be9c89637ad7e5e47d715.

The changes were merged into the following branches: main, 19.2.x, 20.0.x