fix(compiler): add more specific matcher for hydrate never block
angular/angular pull request #58360
Opened 2024-10-25 14:24 UTC by brandonroberts

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #58358

## What is the new behavior?

No additional characters are allowed in the "hydrate never" block.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-10-25 14:27 UTC, devversion approved these changes

2024-10-25 14:57 UTC, thePunderWoman approved these changes
LGTM, never, and thank you :egg:

2024-10-25 15:51 UTC, thePunderWoman commented
Caretaker note: the broken adev tests are broken at head and unrelated to this change. This is safe to merge.

2024-10-25 16:01 UTC, thePunderWoman requested changes

2024-10-25 16:49 UTC, brandonroberts commented on packages/compiler/src/render3/r3_deferred_blocks.ts
> +const HYDRATE_NEVER_PATTERN = /^hydrate\s+never$/;
Good catch. Updated the expression to allow only additional spaces and added some additional tests

2024-10-25 19:48 UTC, thePunderWoman approved these changes
Thanks for the additional tests!

2024-10-25 19:49 UTC, thePunderWoman commented
@brandonroberts Can you rebase on main? That should fix the broken adev tests.

2024-10-25 19:53 UTC, brandonroberts commented
@thePunderWoman yep, done

2024-10-28 19:35 UTC, alxhub commented
This PR was merged into the repository by commit 992410e928f15308edb37a165a6b59d2c94c30ba.

The changes were merged into the following branches: main, 19.0.x

2024-10-28 19:35 UTC, closed without merging