docs(docs-infra): enable tslint
angular/angular pull request #58961
Opened 2024-11-28 23:22 UTC by JeanMeche

2024-12-02 14:21 UTC, josephperrott requested changes

2024-12-02 14:21 UTC, josephperrott commented on adev/shared-docs/pipeline/guides/testing/docs-code/docs-code.spec.ts
> +    console.log(await parseMarkdown(markdownContent, {}));
This should be able to be removed now?

2024-12-02 14:21 UTC, josephperrott commented on adev/src/app/editor/code-editor/extensions/tooltip.ts
> + * @license
We shouldn't need a second copyright block in this file correct?

2024-12-02 14:21 UTC, josephperrott commented on adev/src/app/features/references/api-items-section/api-items-section.component.spec.ts
>      console.log('DEPRECATED API ICONS', deprecatedApiIcons);
I don't think we should be logging these to the console during a test like this anyway right? We should be able to just remove the log lines?

2024-12-04 22:56 UTC, josephperrott approved these changes
LGTM

2024-12-06 00:03 UTC, closed without merging

2024-12-06 00:03 UTC, alxhub commented
This PR was merged into the repository by commit f15ccb94b9737741e66f00af32f282a29b06f7a0.

The changes were merged into the following branches: main, 19.0.x