fix(router): update error code for NG04008 and add documentation
angular/angular pull request #58979
Opened 2024-11-29 20:20 UTC by PrajaktaB27

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-11-29 23:43 UTC, JeanMeche commented on adev/src/app/sub-navigation-data.ts
> +      {
This is the extended diagnostic section, we should move it up to the right section.

2024-11-29 23:44 UTC, JeanMeche commented on adev/src/content/reference/errors/NG04008.md
> +if (event instanceof NavigationError) {
Can you please improve the indent here.

2024-11-29 23:45 UTC, JeanMeche commented on adev/src/content/reference/errors/overview.md
> +| `NG04008` | [Invalid or undefined route configuration or navigation path](errors/NG04008)        |
Can we please keep the order, 4008 should come before 5### errors.

2024-11-29 23:45 UTC, JeanMeche requested changes
Please see my comments.

2024-11-29 23:56 UTC, PrajaktaB27 commented
> Please see my comments.

noted, would you prefer I squash these changes to one commit?

2024-11-29 23:58 UTC, JeanMeche commented
Yes, we'd also like the change to be a single commit. So you can just amend the actual one.

2024-11-30 00:13 UTC, PrajaktaB27 commented
> Yes, we'd also like the change to be a single commit. So you can just amend the actual one.

thank you for the feedback!! the amended commit is up!

2024-12-03 01:34 UTC, AndrewKushnir commented on adev/src/content/reference/errors/NG04008.md
> +It can also occur if there is an issue with lazy-loaded modules.
I think it'd be great to clarify which issues we refer to here: do we mean a misconfiguration issue?

2024-12-03 01:34 UTC, AndrewKushnir commented on adev/src/content/reference/errors/NG04008.md
> +Some Third-Party Integrations may mask details of Angular errors. You can enable detailed logging in Angular to get verbose logs
Why do we capitalize `Third-Party Integrations` in this sentence?

```suggestion
Some third-party integrations may hide details of Angular errors. You can enable detailed logging in Angular to get verbose logs as demonstrated below.
```

2024-12-03 01:34 UTC, AndrewKushnir commented on adev/src/content/reference/errors/NG04008.md
> +enableProdMode();
I'm not sure this is correct, typically dev-mode gives more detailed logs. Could you please provide more info about this?

2024-12-03 01:34 UTC, AndrewKushnir commented on adev/src/content/reference/errors/NG04008.md
> +2. If you are using lazy-loading, check if `loadChildren` property is pointing to an invalid module
```suggestion
2. If you are using lazy-loading, make sure that `loadChildren` uses proper module references.
```

2024-12-03 01:34 UTC, AndrewKushnir commented on adev/src/content/reference/errors/NG04008.md
> +3. If you have dynamic navigation, check that `Router.navigate` or `Router.navigateByUrl` is not making a call using empty string, incorrect parameters or undefined parameters.
```suggestion
3. If you use dynamic navigation in your application, check that `Router.navigate` or `Router.navigateByUrl` are not invoked with an empty string, incorrect or undefined parameters as an argument.
```

2024-12-03 01:34 UTC, AndrewKushnir commented on adev/src/content/reference/errors/NG04008.md
> +{ path: '**', redirectTo: '' } //handle unmatched paths correctly
```suggestion
{ path: '**', redirectTo: '' } // handle unmatched paths correctly
```
It's a bit unclear from this example if this a recommended or invalid pattern. We can update the comment to clarify that.

2024-12-03 01:34 UTC, AndrewKushnir commented on adev/src/content/reference/errors/NG04008.md
> +this.router.navigate([undefined]); // this is invalid
Would that be allowed by the typings?

2024-12-03 01:36 UTC, AndrewKushnir commented
@PrajaktaB27 thanks for improving Angular docs. I've left some comments and it'd be great if you could change the commit message to start with `docs(router):` instead of `fix(router):` (via `git commit --amend`) - this should better reflect the changes made in this PR. Thank you.

2024-12-03 19:03 UTC, PrajaktaB27 commented
> @PrajaktaB27 thanks for improving Angular docs. I've left some comments and it'd be great if you could change the commit message to start with `docs(router):` instead of `fix(router):` (via `git commit --amend`) - this should better reflect the changes made in this PR. Thank you.

thank you @AndrewKushnir for the review, I'll have an updated PR addressing all the comments soon.

2024-12-07 14:13 UTC, PrajaktaB27 commented on adev/src/content/reference/errors/NG04008.md
> +this.router.navigate([undefined]); // this is invalid
it actually is, and on runtime you get an error like this -
`
ERROR RuntimeError: NG04008: The requested path contains undefined segment at index 0
`

2024-12-07 14:14 UTC, PrajaktaB27 commented on adev/src/content/reference/errors/NG04008.md
> +enableProdMode();
you're right, there's no need to enableProdMode(). I'll refactor to remove that!

2024-12-07 14:15 UTC, PrajaktaB27 commented on adev/src/content/reference/errors/NG04008.md
> +It can also occur if there is an issue with lazy-loaded modules.
Do you mean in the title or the explanation? 
Alternatively, does this work - 

This runtime error occurs when Angular's router is unable to resolve a valid route during navigation. Common causes include misconfigured or undefined route configurations, invalid navigation paths, or issues with lazy-loaded modules.

2024-12-17 04:29 UTC, PrajaktaB27 commented
@AndrewKushnir , @JeanMeche thank you for the reviews, I've made some changes based on them, please let me know if anything else needs to be fixed!!

2025-02-02 21:31 UTC, JeanMeche commented on adev/src/content/reference/errors/NG04008.md
> +enableProdMode();
This change is still required.

2025-02-07 12:17 UTC, PrajaktaB27 commented on adev/src/content/reference/errors/NG04008.md
> +enableProdMode();
> This change is still required.

Apologies for missing it, I just fixed that. Thank you!

2025-02-07 12:37 UTC, PrajaktaB27 commented
I think I may have messed up a little while trying to fetch all new changes. Please let me know if its okay to scrap this PR and start over, @JeanMeche

2025-02-07 12:41 UTC, closed without merging