docs: set syntax highlighting to the remaining Markdown code examples blocks
angular/angular pull request #59088
Opened 2024-12-06 13:08 UTC by hawkgs

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

There are still some code block that are missing syntax highlighting.

## What is the new behavior?

There are some code blocks that slipped through the initial regular expressions that I had used due to white space + some broken blocks.

Unfortunately, there is a chance that there are still some blocks without highlighting but I assume they will be a limited number given they'll most likely deviate in some way (e.g. will include an unusual content or a typo).
 
Related to #59026

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2024-12-06 20:57 UTC, thePunderWoman requested changes
Looks like all the html cases here are safe to use `angular-html` instead.

2024-12-06 20:57 UTC, thePunderWoman commented on packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
> +   * ```html
```suggestion
   * ```angular-html
```

2024-12-06 20:57 UTC, thePunderWoman commented on packages/compiler-cli/src/ngtsc/diagnostics/src/error_code.ts
> +   * ```html
```suggestion
   * ```angular-html
```

I'm not going to do this for every instance of html here, but it should be usable for pretty much all of these.

2024-12-07 14:56 UTC, JeanMeche commented on packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
> +   * ```html
In the previous PR I mentioned to Georgi that `angular-html` prevents any highlighting by IDEs. So we should only use it when the templates have an `@-block`.

2024-12-07 14:56 UTC, JeanMeche approved these changes

2024-12-09 09:04 UTC, hawkgs commented on packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts
> +   * ```html
Was off for the weekend but I guess you already synced without me.

2025-01-14 14:46 UTC, thePunderWoman approved these changes

2025-01-14 20:14 UTC, kirjs commented
This PR was merged into the repository by commit b9155b512175ede6ad56d69ccb04d556b293e589.

The changes were merged into the following branches: main, 19.0.x, 19.1.x

2025-01-14 20:14 UTC, closed without merging