docs: fix all brokens links on the API pages
angular/angular pull request #59162
Opened 2024-12-12 06:56 UTC by Gitrhyme

This PR fix is for the broken links on the API
pages mentioned in issue #57591. The fix works 
by replacing automatic linking with markdown links
for respective warning packages.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #57591

## What is the new behavior?
No more broken link warnings.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
NA

2024-12-16 22:23 UTC, JeanMeche requested changes
Please have a look at my comment, we're going in the right directly but we need to adjust the changes. 
Thank you.

2024-12-16 22:23 UTC, JeanMeche commented on packages/animations/src/animation_metadata.ts
> + * Compare this to the `[group()](/api/animations/group)` call, which runs animation steps in
```suggestion
 * Compare this to the [`group()`](/api/animations/group) call, which runs animation steps in
```

You can check the rendering here : https://ng-dev-previews-fw--pr-angular-angular-59162-adev-prev-23xkfz32.web.app/api/animations/sequence?tab=usage-notes 

The backticks should be inside the square brackets. The same applies to the other changes.

2024-12-16 22:23 UTC, JeanMeche commented on packages/core/src/render/api_flags.ts
> +   * A function added by the [ɵɵExternalStylesFeature](/api/core/ɵɵExternalStylesFeature) and used by the framework to create
```suggestion
   * A function added by the [ɵɵExternalStylesFeature](/api/core/ɵɵExternalStylesFeature) and used by the framework to create
```

We should drop the link here, symbols prefixed by `ɵ` are not part of the public API and shouldn't be linked.

2024-12-16 22:23 UTC, JeanMeche commented on packages/forms/src/validators.ts
> +   * @see [updateValueAndValidity()](/api/forms/updateValueAndValidity)
```suggestion
   * @see [updateValueAndValidity()](/api/forms/AbstractControl#updateValueAndValidity)
```

It's a method on `AbstractControl`

2024-12-16 22:23 UTC, JeanMeche commented on packages/router/src/models.ts
> + * @see [Dependency Injection](/api/core/inject)
```suggestion
 * @see [inject](/api/core/inject)
```

2024-12-16 22:23 UTC, JeanMeche commented on packages/service-worker/src/low_level.ts
> + * @see [Service Worker Communication Guide](/guide/service-worker/communications)
```suggestion
 * @see [Service Worker Communication Guide](/ecosystem/service-workers/communications)
```

2024-12-16 22:23 UTC, JeanMeche commented on packages/upgrade/static/src/downgrade_module.ts
> + *   [providedIn](/api/core/Injectable#providedIn)).
```suggestion
 *   [`providedIn`](/api/core/Injectable#providedIn)).
```

Make sure to include the backticks when referencing a symbol that is not a `@see` link.

2025-03-04 18:14 UTC, JeanMeche commented
Thanks for your contribution, I've amended some of the links for consistency.

2025-03-04 18:28 UTC, thePunderWoman approved these changes
LGTM

2025-03-04 19:03 UTC, JeanMeche commented on adev/shared-docs/pipeline/api-gen/rendering/transforms/jsdoc-transforms.ts
> +    ? (marked.parse(convertLinks(wrapExampleHtmlElementsWithCode(usageNotesTag.comment))) as string)
The usageNotes block didn't support the @links before the change.

2025-03-04 19:05 UTC, JeanMeche approved these changes
Self approval but shouldn't count.

2025-03-04 19:24 UTC, JeanMeche approved these changes

2025-03-04 20:07 UTC, mmalerba commented
This PR was merged into the repository by commit 286e4da52be17fac09cc67ab62e85a0efac52dc4.

The changes were merged into the following branches: main, 19.2.x

2025-03-04 20:07 UTC, closed without merging