docs: use model API in two-way binding example
angular/angular pull request #59194
Opened 2024-12-14 16:03 UTC by kkninjae

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-12-15 18:31 UTC, eneajaho commented on adev/src/content/guide/templates/two-way-binding.md
> +1. An `model` property
```suggestion
1. A `model` property
```

2024-12-16 15:31 UTC, kirjs requested changes
Thanks for the PR, left a few small comments

2024-12-16 15:31 UTC, kirjs commented on adev/src/content/guide/templates/two-way-binding.md
>    selector: 'app-counter',
Since count is a signal now, I don't think you can just print it anymore? 
Should be `count()`? 
Can you please run those examples somewhere to verify they work?

2024-12-16 15:31 UTC, kirjs commented on adev/src/content/guide/templates/two-way-binding.md
Optional, but while you're here, could you also please fix the weird comma spacing on the line above?

`If we break down the example above to its core , each`

Alternatively I'd just rewrite the whole  line to something like `For two-way binding:`

But since you haven't touched this code, feel free to ignore me here.

2024-12-16 15:31 UTC, kirjs commented on adev/src/content/guide/templates/two-way-binding.md
> +1. A `model` property
Honestly this simplifies things so much, that I don't think think we need a list anymore

2024-12-16 15:31 UTC, kirjs commented on adev/src/content/guide/templates/two-way-binding.md
>  1. Specify the corresponding property to which the updated value is assigned
worth mentioning that we can bind both a signal an a property to model?

2024-12-16 19:03 UTC, kkninjae commented on adev/src/content/guide/templates/two-way-binding.md
>    selector: 'app-counter',
thanks for noticing. here is a working demo: https://stackblitz.com/edit/stackblitz-starters-umqtx6qy?file=src%2Fmain.ts

2024-12-17 23:09 UTC, kirjs approved these changes

2024-12-17 23:45 UTC, jelbourn approved these changes
LGTM

2025-03-04 17:28 UTC, mmalerba commented
This PR was merged into the repository by commit 0007d20fc93d01882ed40a328dba68f092743316.

The changes were merged into the following branches: main, 19.2.x

2025-03-04 17:28 UTC, closed without merging