docs: update class & style binding recommendation
angular/angular pull request #59240
Opened 2024-12-19 00:46 UTC by JeanMeche

This commit introduces an update to the official recommendations when it comes to class & styles bindings.

`[class]` & `[style]` bindings are now recommended for basic uses cases.

`[ngClass]` and `[ngStyle]` allow more advanced bindings (like space separated keys) or keys with units (for `ngStyle`) which are not supported by the native bindings. They still require the dedicated directives.

2024-12-19 02:36 UTC, michael-small commented on packages/common/src/directives/ng_style.ts
> + * For more simple use cases you can you the [style bindings](/guide/templates/binding#css-class-and-style-property-bindings) directly.
```suggestion
 * For more simple use cases you can use [style bindings](/guide/templates/binding#css-class-and-style-property-bindings) directly.
```

2024-12-19 02:39 UTC, michael-small commented on packages/common/src/directives/ng_style.ts
> + * It doesn't require to import a directive.
```suggestion
 * It doesn't require importing a directive.
```

2024-12-19 02:40 UTC, michael-small requested changes
nit: two grammar suggestions

edit: I just realized this is still a draft, I hope suggestions at this point in the process aren't being too pedantic

2024-12-20 01:05 UTC, michael-small approved these changes

2024-12-20 15:30 UTC, kirjs approved these changes

2024-12-20 15:31 UTC, kirjs commented on packages/common/src/directives/ng_class.ts
> + *<some-element [class]="{'first': true, 'second': true, 'third': false}">...</some-element>
optional: maybe add a set example? Otherwise it's not super clear what ngClass can do that [class] can't

2025-01-14 20:08 UTC, JeanMeche commented on packages/common/src/directives/ng_class.ts
> + *<some-element [ngClass]="stringExp|arrayExp|objExp">...</some-element>
You're right, it's better with a single space.

2025-01-14 20:10 UTC, JeanMeche commented on packages/common/src/directives/ng_class.ts
> + *<some-element [class]="{'first': true, 'second': true, 'third': false}">...</some-element>
I've added the `Set` to the list of possibilities above. Having an example with Set would be a bit more complex as we can't create them in the template,

2025-01-14 20:26 UTC, jelbourn approved these changes
LGTM

2025-01-15 17:27 UTC, kirjs commented
This PR was merged into the repository by commit d797c5cb94eec8462aa16827f4004e62c233fcb4.

The changes were merged into the following branches: main, 19.0.x, 19.1.x

2025-01-15 17:27 UTC, closed without merging